### PR TITLE
Update to simplified ecal pfcluster corrections on top of new Global Tags for PF corrections plus fixes for Run2 MC production

### PR DESCRIPTION
**Pull request by diguida**
Move to updated version of ecal pfcluster corrections with reduced number of input variables, plus some additional pt binning and slightly different parameterization to improve the behaviour at very low energies. Originally in #8818 

New Global Tags including updated set of PF corrections for E-gamma and hadrons, and a couple of fixes for Run2 MC production. Originally in #8869

### CODE REVIEW

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by bendavid** [comment]
Yes, this looks right to me (therefore superseding https://github.com/cms-sw/cmssw/pull/8818 )

**Comment by slava77** [comment]
it would have still been much easier to test and sign off if #8818 was updated (cherry-picking).
since all distributions change, it's easier to compare to the old run (to see no diffs); which is only meaningful in the same release; this PR starts from a different point in 74X history.
I will do this on my side.

Just to confirm: are the payloads in GT the same as the ones that were picked with esprefer?

**Comment by slava77** [comment]
... OTOH, I now realize that my comment doesn't make much sense in view of other changes in the GT.

**Comment by slava77** [comment]
I'll just wait for the comparisons from jenkins and then can sign off.
Based on the code changes, the ecal pf part is ok (all payloads are available since the jenkins jobs ran fine).

**Comment by slava77** [comment]
Looking at jenkins, I noticed this, only in 25 ns run2 fullsim setup (25202)

wf25202_l1nonisoeg

It may seem to have something to do with 
https://github.com/cms-sw/cmssw/pull/8869#issuecomment-95923122
the change in L1RCTParametersRcd.
It's unclear though why the same doesn't show up in other workflows (not in 50202, which is Run 2 50 ns).
L1RCT plots changed in both Run2 25 and 50 ns.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8872	fb88a8f
the reco code part of the changes here is consistent with https://github.com/cms-sw/cmssw/pull/8818 	5717860
jenkins tests confirm that payloads are in place, so the reco signature for #8818 transfers here.

jenkins comparisons show changes in places consistent with changes in the payloads.
On the small number of events available, nothing on the reco side appear to be broken.

I've started higher stat tests to check the incremental changes (between the ecal pf calibrations and all other changes in GT); these will be just for the record of a combined incremental change.

**Comment by diguida** [comment]
+1

**Comment by slava77** [comment]
About https://github.com/cms-sw/cmssw/pull/8872#issuecomment-95946577
Based on my local tests with higher stats, I don't see the same big discrepancy in the plot for the wf 25202.

There are visible changes in flat-pthat dijet sample, which is more sane
wf1338_l1t_isoeg30
I'd suspect something odd happening on the plotting side of the DQM that triggered that large change in https://github.com/cms-sw/cmssw/pull/8872#issuecomment-95946577

**Comment by slava77** [comment]
Some notes on the impact of GT changes (incrementally, on top of the ecal pfcluster correction changes)

PF hadron corrections are visible in expected places:
- 3 TeV dijet shows clear increase in response of neutral hadrons 
all_sign543vssign542_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50
all_sign543vssign542_qcd13tevpt3ts3t5wf1313p0c_log10recopfmets_pfmet__reco_obj_sumet
all_sign543vssign542_qcd13tevpt3ts3t5wf1313p0c_recopfmets_pfmet__reco_obj_neutralhadronetfraction

jet response is much better (resolution is about the same)
wf1313_ptcor_resp_b_hist
wf1313_ptcor_resp_b

the same sampled with dijet QCD 
wf1338_ptcor_resp_b
wf1338_ptcor_resp_e


Castor response changes are visible:
noise component changes quite a lot (this is ele gun event, electrons don't point to castor)
all_sign543vssign542_singleelectron13pt35wf1317p0c_castorrechitssorted_castorreco__reco_obj_obj_energy

the effects decrease with increased energy flow:
Flat-ptHat QCD sample (1338 workflow)
all_sign543vssign542_qcd13tevflatpt15s3000wf1338p0c_log10recocastortowers_castortowerreco__reco_obj_energy

and even less in ttbar with PU35
all_sign543vssign542_ttbarpuwf25202p0c_log10recocastortowers_castortowerreco__reco_obj_energy

**Comment by davidlange6** [comment]
+1

**Comment by diguida** [comment]
@slava77 Sorry, it seems that the reply I sent you via mail for https://github.com/cms-sw/cmssw/pull/8872#issuecomment-95883891 did not land in the PR. 
I confirm that the payloads in GT for PF E-gamma corrections are the same you have already tested in #8818 In addition to that, we have also made few more updates:
* improved set of PF hadron calibrations for all scenarios;
* fix of the L1 RCT parameters for Run2 simulations: they are now able to reproduce the behaviour of the L1T firmware
* fix of the Castor gains, in order to avoid saturation of the digis.
Your tests look consistent with the internal validation presented to AlCa and PPD.

Hope this clarifies

**Pull request merged**
