### PR TITLE
Package refactoring

### PR DESCRIPTION
**Pull request by pjurgielewicz**
The code was split back into source and header maintaining the same functionality. 
Histogram < enums > where changed (shortened).
Fixed flipped / outer ladder recognition in Barrel L4.

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by VinInn** [comment]
why splitting the file?
why removing the final?
why not moving everyone in plugin in anonymous namespace?

**Comment by pjurgielewicz** [comment]
It can all be enclosed in a single sentence: to make it consistent with all other plugins as it was initially designed.

**Comment by VinInn** [comment]
I suggest to move ALL plugins to a single file inside anonymous namespace and make the class final.
This is to avoid polluting the global namespace, reduce code size and eventually improve runtime performance. 

CMS rules also state that In interface there should be ONLY header files shared among multiple packages.

**Comment by fioriNTU** [comment]
@VinInn I asked Pawel to rever back the structure of the code to be consistent with any other plugins in the Phase1 DQM. We have a plan to restyle the code later (probably after 2018 data taking), David already gave us some guidelines, for the moment I prefer clarity against performance, this is gonna be another year with no expert developers in TkDQM.

**Comment by fioriNTU** [comment]
@VinInn what you say makes perfectly sense, we will change our strategy and go in the direction you propose. What is important for me is the consistency among different packages, better achieving this saving resources. Will close this PR and follow your indications. Thanks.

**Comment by fioriNTU** [comment]
@VinInn is it better now? Do not hesitate to suggest other improvements if you have already in mind ...

**Comment by VinInn** [comment]
> @VinInn is it better now?
definetively.
> Do not hesitate to suggest other improvements if you have already in mind ...
will have a look. Nothing obvious for the points I raised previosly

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@VinInn so do you agree to move forward with this PR?

**Comment by fioriNTU** [comment]
@fabiocos and @VinInn can we move ahead with this PR? We need to add quite some other changes on top of this to be included in the next production release.

**Comment by VinInn** [comment]
+1 on my side

**Comment by fabiocos** [comment]
+1

**Pull request merged**
