### PR TITLE
Apply existing clang-tidy checks

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

As a prerequisite for enabling additional `clang-tidy` checks, apply the *existing* checks to the whole code base.

Technical changes only, no changes expected.

### CODE REVIEW

**Comment by fwyzard** [comment]
This should be a baseline for #29858 / #29863.

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
few of the changes actually break the code ...

**Comment by smuzaffar** [comment]
@fwyzard , when we integrated clang-tidy/format in cmssw, it was decided to not apply clang-tidy changes on files under test directory.

**Comment by fwyzard** [comment]
I see.

Do we apply the checks to tune files under test when people submit PRs ?

**Comment by smuzaffar** [comment]
No, we don't apply clang-tidy checks (https://github.com/cms-sw/cms-bot/blob/master/run-pr-code-checks#L33) but we do apply clang-format though.

**Comment by fwyzard** [comment]
OK, I've restricted the changes to exclude `test/` files.

**Comment by fwyzard** [comment]
On the other hand, given that the fixes are automatic, if the code builds and the tests pass, is there any reason for not applying the rules under `test/` ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
can you please  squash this history here

**Comment by fwyzard** [comment]
I actually would rather not, because that makes it much harder to see what changes come from `clang-tidy` what are independent formatting changes.

**Comment by smuzaffar** [comment]
then may be open a new pr with two commits.

**Comment by fwyzard** [comment]
This is quickly starting to become annoying. 

May I assume that every other PR will be requested to squash the commit history ?

**Comment by smuzaffar** [comment]
sorry my bad, I thought this PR still has the initial commit with over 1K changed files. I missed your force push message.

**Comment by fwyzard** [comment]
I moved the application of `clang-format` *before* the application of `clang-tidy` to #29868 #29869 #29870 #29871 #29872 #29873 .

**Comment by fwyzard** [comment]
Interesting...
I cannot have PR with `clang-format` checks only, because the bot complains about the failing `clang-tidy` checks.
I cannot have PR with `clang-tidy` checks only, because the bot complains about the failing `clang-format` checks.

**Comment by smuzaffar** [comment]
this is correct, bot checks for both clang-tidy and format.

**Comment by fwyzard** [comment]
OK, then let me split this into one PR per subsystem, to ease the signatures.

**Pull request closed without merging**
