### PR TITLE
Fix the record-tag mapping for the AAG harvesting

### PR DESCRIPTION
**Pull request by mmusich**
Fixes issue reported at: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2435.html

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test seem stuck here

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
