### PR TITLE
Adding 2016C relvals

### PR DESCRIPTION
**Pull request by fabozzi**
New data relvals from 2016C (run 275657)

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by mmusich** [comment]
@fabozzi do you plan to include these in the next release validation campaign for 81x? The conditions in the offline GTs are not up-to-date to cover up to 2015C!

**Comment by fabozzi** [comment]
@mmusich: OK thanks for reminding me. Having these relvals in next 81X pre-release is not urgent; we can have this PR synchronized with GT update

**Comment by fabozzi** [comment]
close

**Comment by mmusich** [comment]
@fabozzi, techincally we are now covered to have 2016C relvals as well.

**Comment by fabozzi** [comment]
@mmusich 
OK, but I prefer to close this and start from a new PR

**Pull request closed without merging**
