### PR TITLE
Removed legacy b tagging using tight track selection from MiniAOD

### PR DESCRIPTION
**Pull request by ferencek**
This PR addresses the issue discussed in https://github.com/cms-sw/cmssw/issues/17573

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
Tiny differences in the slimmed jets, and in the DQM analyses which use them.
No significant effect on the event size (tiny reduction, though)

**Comment by slava77** [comment]
@perrotta 
jenkins comparisons report is not available anymore.
which differences did you see in the slimmed jets and where?
Please clarify.
Thank you.

**Comment by perrotta** [comment]
Indeed, I looked at the jenkins comparisons yesterday, but as you say  
the report today is not available any more (not even for the 90X  
version of this PR): that's why I did not put the link. We can try to  
reconstruct some comparison from scratch, if you think so.

Feel free of putting this PR on hold, if you want to apply some extra check.


Slava Krutelyov <notifications@github.com> ha scritto:

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
hold
(while tests are re-running)

**Comment by slava77** [comment]
@smuzaffar @iahmad-khan I can not access jenkins pages anymore outside CERN
https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/

**Comment by perrotta** [comment]
please test
(addon's failed beacause of file access issues)

**Comment by monttj** [comment]
+1

**Comment by perrotta** [comment]
+1
(Once again)
No significant effect on the event size (tiny reduction, though)
Differences are observed in the slimmed jets related plots: however, they look like being due to different roundings originated by having touched the slimmed jets, and do not affect significantly the jet parameters, see e.g.
--- Muon Energy fraction's in slimmed jets:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-26-1100+17839/19027/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/JetMET_JetValidation_slimmedJets.html
--- Event logger in Physics/Top/SingleTopElectronMediumDQM_miniAOD:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-26-1100+17839/19027/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/Physics_Top_SingleTopElectronMediumDQM_miniAOD_presel.html

**Comment by perrotta** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Pull request merged**
