### PR TITLE
Fix import in Phase1L1TJetSumsProducer_cfi for python 3

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This should fix the failures seen in CMSSW_12_0_PY3_X_2021-05-23-2300

#### PR validation:

None

### CODE REVIEW

**Comment by makortel** [comment]
test parameters
  - release = CMSSW_12_0_PY3_X_2021

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Ok, the latest PY3 IB is already too old.

**Comment by makortel** [comment]
test parameters

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_12_0_PY3_X_2021-05-24-2300

**Comment by srimanob** [comment]
+Upgrade

Same fix as https://github.com/cms-sw/cmssw/pull/33747 to make python 2 and 3 compatible.

**Comment by jfernan2** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
