### PR TITLE
Remove RecoJets/JetProducers/test/BuildFile.xml as unnecessary

### PR DESCRIPTION
**Pull request by makortel**
Fixes the following warning from scram
```
tmp/slc6_amd64_gcc630/MakeData/DirCache.mk:12514: No such file exists: src/RecoJets/JetProducers/test/test-large-voronoi-area.cc. Please fix src/RecoJets/JetProducers/test/BuildFile.
```
The `test-large-voronoi-area.cc` was removed in #22305, and this `BuildFile.xml` was only instructed to build that.

Tested in 10_1_0_pre3, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22634	5e79aea
- technical; in line with the description
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

fix

**Pull request merged**
