### PR TITLE
Create new ECAL DQM GpuTask to monitor and compare CPU and GPU generated ECAL Rec Hits

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

PPD has requested DQM subsystems to monitor several [GPU-enabled collections] being introduced in CMSSW_12_1_X. We have introduced a new EcalMonitorTask called GpuTask designed to take in CPU and GPU generated rec hits and produce plots comparing several rec hit quantities for each run. We don't explicitly plot the GPU rec hit values for the sake of memory efficiency. Additional plots may be added in the future.

This task will not run by default on the regular Online DQM workflow.

#### PR validation:

One caveat to this version of the code is that we have not been able to test it on actual GPU rec hits. There appears to be no workflow currently that produces both types of rec hit collections. We have been informed by Thomas Reis that CPU and GPU ECAL rec hits are the same data type, so our testing is done by changing the input tags so that both collections are the CPU rec hits.

This code was run with the runTheMatrix workflow 10842.512 and the new plots look as expected.

[GPU-enabled collections]: https://docs.google.com/presentation/d/1pCbC-PU2LJMpWK9JxYrRIjpKXMH_QG47py5joFImiAQ/edit#slide=id.gf6f43175a4_0_11

#### Backport

This is a backport of https://github.com/cms-sw/cmssw/pull/35946 to include this code in the 12_1_X release.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by jfernan2** [comment]
backport

**Comment by perrotta** [comment]
backport of #35946

**Comment by alejands** [comment]
We believe that the tests failed due to the GPU ecalRecHits not being enabled in CMSSW at the moment. The `@cuda` version is commented out here: [RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cff.py#43]. For the time being, we'll modify the GPU input tags to also read from the CPU ecalRecHits. This can be quickly changed back when the GPU rec hits are available.

[RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cff.py#43]: https://github.com/cms-sw/cmssw/blob/master/RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cff.py#L43

**Comment by jfernan2** [comment]
@alejands the UnitTest failed due to the issue fixed in this PR https://github.com/cms-sw/cmssw/pull/35921  not to your code, so I would bring back the code as you had it. Thanks

**Comment by alejands** [comment]
@jfernan2 I have removed the modification commit from the commit history

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@perrotta @qliphy I am not sure if a test with enable gpu may give some check to this PR given its nature

**Comment by jfernan2** [comment]
-1
Same comment as in master PR

**Comment by jfernan2** [comment]
enable gpu

**Comment by jfernan2** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by alejands** [comment]
@qliphy I have significant updates to this code that I'm about to submit as a new PR very soon. Perhaps it's best to close this PR and submit it all together

**Comment by qliphy** [comment]
please abort

**Comment by qliphy** [comment]
> @qliphy I have significant updates to this code that I'm about to submit as a new PR very soon. Perhaps it's best to close this PR and submit it all together

Ok, thanks @alejands

**Pull request closed without merging**
