### PR TITLE
Add frozen "V1.4" HLT menu for "postEE" MC [`12_4_X` only]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is specific to the `12_4_X` release cycle.

It adds (configuration files for) the frozen HLT "V1.4" pp menu. TSG's plan is to use this "V1.4" menu for the `12_4_X` MC production of the "post ECAL Endcap+ issue" scenario.

This PR simply adds the HLT menu: no test in `12_4_X` will exercise this menu for now (not in RelVals, nor in IBs). This also means that this PR poses no risks to other workflows (e.g. online operations).

My understanding of [CMSHLT-2524](https://its.cern.ch/jira/browse/CMSHLT-2524) is that PdmV will add RelVal wfs to test this new MC scenario (using the HLT menu added by this PR), once AlCa releases the GT for "postEE" MC.

This "V1.4" menu will be accessible via `--step HLT:@relval2022_postEE` (it sounds like "postEE" is the common label for this MC production; if not, please comment here and we will improve the name of the keyword).

Attn: @cms-sw/pdmv-l2 @cms-sw/alca-l2

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by missirol** [comment]
+hlt

**Comment by rappoccio** [comment]
+1 

* Expected to be parasitic functionality.

**Pull request merged**
