### PR TITLE
Tracer: add performance statistics

### PR DESCRIPTION
**Pull request by fwyzard**
this PR is not being submitted for integration in its present form, but only as a request for comments

### CODE REVIEW

**Comment by fwyzard** [comment]
@Dr15Jones , can you comment about few aspects ?

   * I've started playing with the Tracer service to test the per-thread cpu time and memory statistics.
What do you think about adding time and memory reports to the tracer service ?
If you think it's useful, I can clean up the implementation and make it dependent on additional configuration parameters.
Otherwise, I'll scrap this part of the changes.

   * The per-thread cpu timer should be fine as it is, but I do not know if there already is a similar tool in CMSSW, nor where it would better be put.

  * The per-thread memory statistics is a bit more complicated, since it requires a recompiled version of jemalloc to be useful.
      - I think I will add a method to check if the underlying stuff is available (i.e. we are running with jemalloc AND it was compiled with --enable-stats), to avoid reporting 0 allocated/deallocated kB for every module :-)
      - would it be better to return the stats via a dedicated struct instead of using a tuple ? 

By the way, is there a way for a Service to look at the objects produced (i.e. put in the event) by a module, in that module's postModuleEvent handler ?
It might be useful to check how much memory is going into the event.

**Comment by fwyzard** [comment]
-1
not ready for merging yet

**Comment by Dr15Jones** [comment]
@fwyzard it is my preference to have each Service do one particular tightly focused job. Therefore I do not wish performance measurements to be added to the Tracer. I am perfectly fine with a new Service being added which does per module level performance measurements.

As for Services having access to the Event, we removed that when we went to multi-threading since it was to likely to be abused. If you want to do a memory check on objects in the event (how would that even be possible for things that do internal memory allocation like ```std::vector<>```?) you could use an EDAnalyzer.

**Comment by fwyzard** [comment]
> @fwyzard it is my preference to have each Service do one particular tightly focused job. Therefore I do not wish performance measurements to be added to the Tracer. I am perfectly fine with a new Service being added which does per module level performance measurements.

OK.

> As for Services having access to the Event, we removed that when we went to multi-threading since it was to likely to be abused.

I remember the fact that you do not want a Service to trigger producing new collections, but simply monitoring what a module puts into the event (so with a const access to the event) could in principle be fine.
Anyway, I take this as "it's not possible" :-)

> If you want to do a memory check on objects in the event (how would that even be possible for things that do internal memory allocation like std::vector<>?) you could use an EDAnalyzer.

Well, for vectors it's easy, I can do `sizeof(vector) + sizeof(vector::value_type) * vector.capacity()` .
For other containers it would be more difficult.

.A

**Comment by Dr15Jones** [comment]
-1

**Pull request closed without merging**
