### PR TITLE
[BUGFIX] CocoaModel/src/Model.cc gcc11 compile error fix (issues #34756)

### LINKED ISSUE #34756: [GCC 11] CocoaModel/src/Model.cc: error: 'this' pointer is null
Building CMSSW with gcc11 fails:
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/src/Model.cc: In static member function 'static void Model::readSystemDescription()':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/src/Model.cc:437:28: error: 'this' pointer is null [-Werror=nonnull]
   437 |         meastemp->construct();
      |         ~~~~~~~~~~~~~~~~~~~^~
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/src/Model.cc:13:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/interface/Measurement.h:35:8: note: in a call to non-static member function 'void Measurement::construct()'
   35 |   void construct();
      |        ^~~~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/src/Model.cc:440:28: error: 'this' pointer is null [-Werror=nonnull]
   440 |         meastemp->construct();
      |         ~~~~~~~~~~~~~~~~~~~^~
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/src/Model.cc:13:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3f7c5ca595fd8634b26b919adc27f210/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-07-30-0900/src/Alignment/CocoaModel/interface/Measurement.h:35:8: note: in a call to non-static member function 'void Measurement::construct()'
   35 |   void construct();
      |        ^~~~~~~~~
```

Judging by [this line](https://github.com/cms-sw/cmssw/blob/master/Alignment/CocoaModel/src/Model.cc#L472), these two branches are not supposed to be executed. Looking at github history of this file, the commented out likes are there from the start of github era.

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:
fixes #34756

Remove two types: DIFFCENTRE and DIFFANGLE

These types are removed before but remained in the if statement.

@tvami

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bugfix

**Comment by francescobrivio** [comment]
test parameters:
  - addpkg = Alignment/CocoaModel

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
test parameters:
 - release = slc7_amd64_gcc11
 - addpkg = Alignment/CocoaModel

**Comment by tvami** [comment]
(the issue comes up with GCC 11)

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
fixes https://github.com/cms-sw/cmssw/issues/34756

**Comment by tvami** [comment]
@hyunyong I think it's prefered to have PR titles that explain the PR without the need to clicking to the issue, so would you please rename to something describing the problem? Thanks!

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
