### PR TITLE
Store EW parameter weights in NanoAOD of W mass samples

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Explicitly stores the EW parameter weights in the NanoAOD for the W mass Drell-Yan and W MC samples. Adds 43 weights for the DYJetsToMuMu_M-50_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos and 33 fro the W*JetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos samples. The weights include mV and sintheta variations that are essential to the analysis. No other samples are affected.

#### PR validation:

Confirmed that the weights are added correctly for these samples and that others are unaffected.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
assign generators

**Comment by agrohsje** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by gouskos** [comment]
+xpog

**Comment by silviodonato** [comment]
+1
@kdlong @cms-sw/xpog-l2 
`std::cout` should be removed from the whole `PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc`

**Pull request merged**
