### PR TITLE
Replace Geometry_cff with GeometryDB_cff in RecoLocalTracker

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoLocalTracker configuration files (3 files) are fixed.
```
        modified:   RecoLocalTracker/SiPixelClusterizer/test/readClusters_cfg.py
        modified:   RecoLocalTracker/SiPixelRecHits/test/readRecHits_cfg.py
        modified:   RecoLocalTracker/SiStripRecHitConverter/test/DigisToRecHitRead_cfg.py
```
#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
+reconstruction

- technical PR
- no reco changes

**Comment by tvami** [comment]
unhold

**Comment by perrotta** [comment]
assign alca

**Comment by tvami** [comment]
+alca

**Comment by clacaputo** [comment]
+reconstruction

**Comment by qliphy** [comment]
+1

**Pull request merged**
