### PR TITLE
[94XminiAOD][updated GT] Change HcalRespCorrs and updated BS

### PR DESCRIPTION
**Pull request by lpernie**
# Updated GTs [94X]
1) 94X_dataRun2_v6 -> 94X_dataRun2_v7
-  HcalRespCorrs_v6.5_offline
-  BeamSpotObjects_LumiBased_v4_offline
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v6/94X_dataRun2_v7

2) 94X_dataRun2_relval_v11 -> 94X_dataRun2_relval_v12
-  HcalRespCorrs_v6.5_offline
-  BeamSpotObjects_LumiBased_v4_offline
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v11/94X_dataRun2_relval_v12

### CODE REVIEW

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie @arunhep do we have a corresponding PR for master?

**Comment by lpernie** [comment]
Hello @fabiocos ,
The tags we are adding are already present in master [1].
They where never back-propagated to 94X.

**Comment by fabiocos** [comment]
+1

content already present in master, this PR supports the tests of #22713

**Pull request merged**
