### PR TITLE
Cleanups in PhysicsTools and OnlineDB

### PR DESCRIPTION
**Pull request by davidlange6**
Finish old migration and remove long-ago-moved headers in PhyscisTools
Add virtual destructor to a presumably unused class in OnlineDB.
Both identified as warnings in the modules IB.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- It also include some code-format adjustments
- Jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
any objections @cms-sw/db-l2 ?

**Comment by silviodonato** [comment]
merge
fyi @ggovi

**Pull request merged**
