### PR TITLE
Validation fixes - 10_6_X

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Backport of the fixes merged in master with #27116 for the UL release

Starting from some issue reported by the static analyzer, I think there are two real bugs in these Validation files which are fixed here:
- L732 of Validation/EventGenerator/plugins/TauValidation.cc, where with the original formulation the case with two negative and one positive pion is never hit
- The fix in Validation/EventGenerator/src/HepMCValidationHelper.cc

A few other minor adjustments are also included here.

Furthermore, in order to recycle and cherry-pick the same commits as in the master version, the very first commit in this PR applies clang-format to the files affected, as it was done already in the master version.

Changes are expected in the DQM output because of the fixes (the same as in the mother version of this PR)

#### PR validation:

It compiles

#### if this PR is a backport please specify the original PR:

backport of #27116

### CODE REVIEW

**Comment by perrotta** [comment]
type bug-fix

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #27116

**Comment by jfernan2** [comment]
+1 as long as generator team finds it useful

**Comment by fabiocos** [comment]
@jfernan2 apparently the comment must be in a separate line, otherwise the bot does not correctly set the status (it does not matter in this case, I take your signature)

@efeyazgan @qliphy @alberto-sanchez I imagine this would be useful for GEN validation during UL activities

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
