### PR TITLE
Fixing tracking in tilted and adapting Occupancy Map tool

### PR DESCRIPTION
**Pull request by ebrondol**
This PR contains two main parts:
- the tilted DetId scheme and navigation has been modified in order to reconstruct tracks also in the tilted geometry (tested with OLD clusters).
- the DPG tool regarding Occupancy/Multiplicity map has been updated in order to take into account also the possibility to have phase2Clusters and for both tilted and flat geometry. Here how to run it for the new clusters produced by the tilted WF [1] and for the old ones produced by the flat [2].

Still missing:
- using new clusters in tracking
- adapting DPG tool for the phase2clusters on track

@boudoul @delaere @venturia

[1] _cmsRun DPGAnalysis/SiStripTools/test/OccupancyPlotsTest_phase2_newClus_cfg.py print globalTag=DES23_62_V1::All inputFiles=file:10800/step3.root triggerPath="*" geometry="tilted" tag="newClusters_tilted"_ 
[2] _cmsRun DPGAnalysis/SiStripTools/test/OccupancyPlotsTest_phase2_cfg.py print globalTag=DES23_62_V1::All inputFiles=file:13000/step3.root triggerPath="*" geometry="flat" tag="oldClusters_flat" _

### CODE REVIEW

**Comment by ebrondol** [comment]
@boudoul 
Please, let me know if I need to get rid of the following files:
SLHCUpgradeSimulations/Configuration/python/phase2TkTilted_oldClusters.py

They allow to switch geometry and clusterization: the tilted with old clusters and the flat with the new ones.

**Comment by venturia** [comment]
a clarification for the record: the functionality to monitor the _on track_ new clusters is not something specific of the SiStripToolsAnalysis package. The code in that package monitors whatever cluster collection is provided. What has to be developed is the possibility to produce in an easy way a collection of on track clusters. So far this was achieved using the AlignmentTrackSelector.

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by ebrondol** [comment]
@civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @cmsbuild, @slava77, @davidlange6, @boudoul
... any progress on this PR?

**Comment by davidlange6** [comment]
please test

**Pull request merged**
