### PR TITLE
EMTF Primitive Conversion LUT update

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR adds options to use the new primitive conversion LUTs in the EMTF emulator. The LUTs were deployed at P5 on October 6th, but they are not used in the emulator yet. 

This PR needs the LUTs in https://github.com/cms-data/L1Trigger-L1TMuon/pull/23 to work.

We see improvement in EMTF performance at P5 with these new LUTs, so changes to muon efficiencies etc are expected when testing the re-emulation workflows from recent runs (after October 6th). Otherwise this PR shouldn't change anything in the emulator.

This PR should be backported to 12_4 if there is an opportunity to run this at P5 to improve data/emulator comparisons in DQM. If data taking with 12_5 is expected we should also backport it there. 

This has no effect on MC production so MC campaigns do not matter for the purpose of this PR.

#### PR validation:

`runTheMatrix.py -l limited -i all --ibeos` has no failures. Also validated by unpacking one of the recent runs to compare LUT outputs and it matches.  

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Comment by eyigitba** [comment]
I want to mention that https://github.com/cms-data/L1Trigger-L1TMuon/pull/23 needs to be merged as well for this to work with recently collected data.

The tests are not useful to catch a crash for this change since the firmware was deployed on October 6th and any data before that run will not trigger the changes.

**Comment by perrotta** [comment]
> I want to mention that [cms-data/L1Trigger-L1TMuon#23](https://github.com/cms-data/L1Trigger-L1TMuon/pull/23) needs to be merged as well for this to work with recently collected data.
> 
> The tests are not useful to catch a crash for this change since the firmware was deployed on October 6th and any data before that run will not trigger the changes.

Thank you for having reminded it @eyigitba 

I think that some workflow, or maybe unit test, should be made available in order to test this with the data collected with the new firmware: does it mean that the cmssw software with this update included was never tested with the new firmware? This has to be clarified before we can think at a possible backport to the current data taking releases.

**Comment by eyigitba** [comment]
Hi @perrotta , I can provide a workflow to test this with the recent data collected. 

I ran this test myself before submitting the PR and everything worked fine (the code uses the correct LUTs and matches the online eta/phi values). Since we had a similar issue before I wanted to be more careful this time.

**Comment by perrotta** [comment]
> Hi @perrotta , I can provide a workflow to test this with the recent data collected.

Thank you @eyigitba , yest that would be useful
I think we can merge https://github.com/cms-data/L1Trigger-L1TMuon/pull/23 now in master, but wait for that workflows before backporting this into previous cycles, as it is the intention as far as I understood

> I ran this test myself before submitting the PR and everything worked fine (the code uses the correct LUTs and matches the online eta/phi values). Since we had a similar issue before I wanted to be more careful this time.

**Comment by mmusich** [comment]
at the[ Joint Operations meeting today]( https://docs.google.com/document/d/1mDdCUu8PxEeWPLzG1SnKFQMFcxPR5bfGNMAQdJ1pG1s/edit#heading=h.qjo9twjj7id3), it was mentioned that a backport of this PR would be desirable in the next CMSSW_12_4_X release. Does such a backport exist yet?

**Comment by francescobrivio** [comment]
@eyigitba any update on opening the backports to 12_$_X and 12_5_X of this PR?
Cheers,
Francesco as ORM

**Comment by eyigitba** [comment]
Sorry, I couldn't do it yesterday. I'll submit the PRs and a workflow to test these soon.

**Comment by eyigitba** [comment]
Here is a simple PSET file that runs on recent data: https://github.com/eyigitba/cmssw/blob/d4b832735b26d45e7c74e6ec8a9f0195b1424df7/L1Trigger/L1TMuonEndCap/test/unittests/emtf_run3_test.py

In LogInfo one can see:

```
%MSG-i L1T:  L1TMuonEndCapTrackProducer:simEmtfDigisData  25-Oct-2022 15:21:04 CEST Run: 360820 Event: 129711316
EMTF updating conditions: pc_lut_ver: 3 pt_lut_ver: 8 fw_ver: 1664468309
```

which is the new settings added with this PR. When `pc_lut_ver = 3` is set, we will need the new LUTs in https://github.com/cms-data/L1Trigger-L1TMuon/pull/23.

Please let me know if this looks good to you. 

I'll submit the other 2 PRs now.

**Pull request merged**
