### PR TITLE
Phase2-hgx287X Next step for V16 Geometry for HGCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Next step for V16 Geometry for HGCAL; allow parameters for layer rotation and differing wafer thicknesses

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob @silviodonato @qliphy Could you approve this PR and get it integrated

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
