### PR TITLE
Fix several bugs introduced in the Pixel PI

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

After PR #29864 has been merged, it has been possible to visually inspect the rendering of all the newly added plots at [ConDBBrowser](http://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod/CMSSW_11_1_X_2020-05-20-2300).
This has revealed that several of the plots introduced in PR #29864 had some problems in the rendering in the browser. This PR aims to fix this, as well as addressing some of the comments received at https://github.com/cms-sw/cmssw/pull/29864#pullrequestreview-414457447

#### PR validation:

Individual plots have been tested by hand, (see results at [link1](http://musich.web.cern.ch/musich/display/plots_PerRegion/), [link2](http://musich.web.cern.ch/musich/display/plots_PerRegion/comparisons/) and [link3](http://musich.web.cern.ch/musich/display/plots_Templates/) ) . Moreover this branch is passing standard unit tests provided in the package.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, but it has been backported at #29980

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
