### PR TITLE
Revert "Improvements and fixes for the BPH-trigger offline DQM code"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#23738

The PR causes a list of reproducible crashes in CMSSW_10_2_X_2018-07-12-2300 for several workflows, e.g. 136.851, 136.852, ...

#0  0x00000035236ac8dd in waitpid () from /lib64/libc.so.6
#1  0x000000352363e4e9 in do_system () from /lib64/libc.so.6
#2  0x000000352363e820 in system () from /lib64/libc.so.6
#3  0x00007f6d4f254be8 in TUnixSystem::StackTrace() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-07-12-1100/external/slc6_amd64_gcc630/lib/libCore.so
#4  0x00007f6d4f2570ec in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-07-12-1100/external/slc6_amd64_gcc630/lib/libCore.so
#5  <signal handler called>
#6  0x00007f6d00ea751d in BPHMonitor::Prescale(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, edm::Event const&, edm::EventSetup const&, HLTPrescaleProvider*) () from /build/fabiocos/102X/crash/prova/CMSSW_10_2_X_2018-07-12-1100/lib/slc6_amd64_gcc630/pluginDQMOfflineTriggerPlugins.so
#7  0x00007f6d00eabd3d in BPHMonitor::analyze(edm::Event const&, edm::EventSetup const&) () from /build/fabiocos/102X/crash/prova/CMSSW_10_2_X_2018-07-12-1100/lib/slc6_amd64_gcc630/pluginDQMOfflineTriggerPlugins.so

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.

#6  0x00007f6d00ea751d in BPHMonitor::Prescale(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, edm::Event const&, edm::EventSetup const&, HLTPrescaleProvider*) () from /build/fabiocos/102X/crash/prova/CMSSW_10_2_X_2018-07-12-1100/lib/slc6_amd64_gcc630/pluginDQMOfflineTriggerPlugins.so
#7  0x00007f6d00eabd3d in BPHMonitor::analyze(edm::Event const&, edm::EventSetup const&) () from /build/fabiocos/102X/crash/prova/CMSSW_10_2_X_2018-07-12-1100/lib/slc6_amd64_gcc630/pluginDQMOfflineTriggerPlugins.so

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.851,136.852,136.853,136.854,136.855,136.86

**Comment by fabiocos** [comment]
+1

temporary revert of this PR so as to avoid crashes, waiting for a fix

**Comment by fabiocos** [comment]
merge

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
