### PR TITLE
MTD geometry: update MTDGeometry test, use only DD4hep backend, add ETL pixel position test

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Complete revision of the (unit) test suite for ```Geometry/MTDGeometryBuilder```:

- ```MTDDigiGeometryAnalyzer``` simplified, no full dump of geometry;
- ```DD4hep_TestBTLPixelTopology``` moved to ```DD4hep_TestPixelTopology```, full comparison of ideal and reco geometries for both BTL and ETL, with dump of position of ETL reference pixel (needed to test the development of ETL v9).

Only the DD4hep version of the test is now run, since ```MTDGeometry``` is independent on the backend, provided the ```MTDNumberingBuilder``` output is the same.

The filtering of volumes has been optimized to prevent the navigation of the full volume tree.

#### PR validation:

The code runs for scenario D110, providing the expected output. The reference needs to be updated in the ```cms-data``` area to have a successful completion of the unit test.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/16

**Comment by fabiocos** [comment]
Failures appear unrelated to this PR

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/16

**Comment by fabiocos** [comment]
@cms-sw/geometry-l2 @cms-sw/upgrade-l2 the errors have nothing to do with this PR, any comment?

**Comment by Moanwar** [comment]
+Upgrade

**Comment by fabiocos** [comment]
@cms-sw/geometry-l2 comments?

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/16

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by fabiocos** [comment]
I see that the unit test is failing in the IB, while it was successful in the PR test. I wonder whether it depends on details of the architecture, as this appears to be linked to rounding. I will fix that by reducing the number of digits used to the strict minimum needed

**Comment by fabiocos** [comment]
@makortel no, I see it also in aarch64. There was a similar issue in the ```RecoMTD/DetLayers``` test in the past, I'll adopt the same approach as there, and test it also on ARM to be sure

**Pull request merged**
