### PR TITLE
From cmssw 9 4 9

### PR DESCRIPTION
**Pull request by psiddire**
Commenting lines in EnergyScaleCorrection_class which are not needed. There are some conditions inside the class which won't be met with the Scales and Smearing's data and it inevitable causes the job to halt.

### CODE REVIEW

**Comment by slava77** [comment]
-1

wrong base or release target

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by kpedro88** [comment]
-1
wrong branch

**Comment by fabiocos** [comment]
@psiddire I think it was a wrong PR, could you please clarify, close it in case and submit a correct one?

**Pull request closed without merging**
