### PR TITLE
EMTF DQM for emulator and data comparison

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by davidlange6** [comment]
Hi all- again, please use a different repo for your private testing. Thanks.
@dmitrijus

**Comment by EsmaeelEskandari** [comment]
@davidlange6 Hi, Actually it is re-activating PR 15748. It is working very well over online production now.

**Comment by davidlange6** [comment]
it doesn’t appear to be targeted for cmssw integration?

**Comment by EsmaeelEskandari** [comment]
It should be integrated. Its 81X is PR #16738 .

**Comment by davidlange6** [comment]
nothing with the title of test pr16654 would be considered for integration. Please take a bit of time to make your requests clear. Thanks

**Comment by EsmaeelEskandari** [comment]
@davidlange6 I made another PR #16751 which is exactly the same as this one.  Please use it for online production. I updated the tagCollector too.

**Comment by EsmaeelEskandari** [comment]
@davidlange6 PR #16737 is validated and it is now deploying in online production now. PR #16751 can be superseded this one safely.

**Comment by davidlange6** [comment]
Then please close this one. For the future there is a handy edit button in github that would be an easier way to change your pr.


On 24 Nov 2016, at 13:36, EsmaeelEskandari <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> PR #16737<https://github.com/cms-sw/cmssw/pull/16737> is validated and it is now deploying in online production now. PR #16751<https://github.com/cms-sw/cmssw/pull/16751> can be superseded this one safely.

**Comment by EsmaeelEskandari** [comment]
Really? So I think it is better to keep this PR ( #16737 )which is already deployed for online production rather than PR #16751. I will close PR #16751 .

**Comment by EsmaeelEskandari** [comment]
#16654 has the same content as this current PR, so it was closed.

**Comment by dmitrijus** [comment]
please close this PR.

**Pull request closed without merging**
