### PR TITLE
Migrate module configuration in RecoVertex to use default cfipython v2

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. 

In this PR, 1 file changed.  
RecoVertex/BeamSpotProducer/python/BeamSpotOnline_cfi.py 
The previous PR is #35194

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_1_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by jpata** [comment]
+reconstruction
- technical, no reco differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
