### PR TITLE
Run3-alca181 Modify one analyzer (StudyCaloResponse) to handle MC samples

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify one analyzer (StudyCaloResponse) to handle MC samples. Also bunch all example cfg's in test/python 

#### PR validation:

Tested using the cfg's in the test directory

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by silviodonato** [comment]
The error is not related to this PR
```
----- Begin Fatal Exception 15-Feb-2021 13:15:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.�
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=&xrdcl.requuid=6bf4650c-fe39-4d9b-b4d0-51868268f097
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by bsunanda** [comment]
I am redoing the test. The failure was not due to this PR

**Comment by christopheralanwest** [comment]
I don't think that re-doing the test will help. The test is failing in the IBs as well. There is only one file from the relevant dataset in the IB EOS area:

`/eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0A3C1F91-2ECD-E311-8E64-90E6BA442F3F.root`

It is not the file that the IB tests look for:

`/eos/cms/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root`

The ordering of the files from the DAS queries differs in recently IBs from previous IBs. For example, in `CMSSW_11_3_X_2021-02-09-1100`:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-09-1100/pyRelValMatrixLogs/run/4.76_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT/step2_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT.log

and in `CMSSW_11_3_X_2021-02-15-2300`:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-15-2300/pyRelValMatrixLogs/run/4.76_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT/step2_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT.log

I don't know the reason for the change. @silviodonato Do you know the origin of the difference?

**Comment by silviodonato** [comment]
@christopheralanwest  I read in a comment by @smuzaffar that the problem has been solved. The next IB should be ok.

**Comment by smuzaffar** [comment]
@christopheralanwest , recently we update `dasgoclient` which now uses `Rucio`  instead of `PhEDEx`. There are few das queries for which `rucio` returns some extra files which were not registered/returned by `PhEDEx` .
For now , I have added a workaround to ignore extra `rucio` files. workflow 4.76 should now look for  `/eos/cms/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root` again which is caches in IB EOS.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by yuanchao** [comment]
+1
* add python cfg for MC processing
* static build warnings are not part of the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
