### PR TITLE
 Add back call to consumes within loop in the MixingModule.

### PR DESCRIPTION
**Pull request by ndaci**
This fix adds back a call to consumes in a loop, that is able to load the correct inputs.
This is needed by the TSG-STEAM group in the context of MC Trigger Rate Studies.

Backport in 80X of PR #17262

### CODE REVIEW

**Comment by mdhildreth** [comment]
+1

**Comment by mdhildreth** [comment]
-1

oops, thought that this had been tested already

**Comment by davidlange6** [comment]
it was tested and failed tests in 90x.. presumably the same failures will happen here.

**Comment by ndaci** [comment]
The 90X version (#17262) of this PR has been merged. Can we please test this PR again ?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fwyzard** [comment]
backport of 17262

**Comment by ndaci** [comment]
Do you think we can get this PR merged?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
