### PR TITLE
Removing Muon POG DQM sequence from Express pipeline - backport to 14_1_X

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Removing Muon POG DQM sequence from Express pipeline to reduce memory load at T0.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46293

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test workflow 1001.3,1001.4

**Comment by antoniovagnerini** [comment]
#backport of 46293

**Comment by antoniovagnerini** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
