### PR TITLE
Fix for LLVM 7.0.0: Explicitly pass the gcc-toolchain to clang

### PR DESCRIPTION
**Pull request by smuzaffar**
We have updated LLVM to version 7.0 for DEVEL IBs. The command `echo "" | clang++ -xc++  -v -E -` now returns system gcc include paths
```
clang version 7.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /build/muz/llvm/install-llvm/slc6_amd64_gcc700/external/llvm/7.0.0-cms/bin
Found CUDA installation: /cvmfs/cms-ib.cern.ch/nweek-02542/slc6_amd64_gcc700/external/cuda/9.2.148, version 9.2
 "/build/muz/llvm/install-llvm/slc6_amd64_gcc700/external/llvm/7.0.0-cms/bin/clang-7" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /build/muz/llvm/install-llvm/slc6_amd64_gcc700/external/llvm/7.0.0-cms/lib64/clang/7.0.0 -internal-isystem /usr/local/include -internal-isystem /build/muz/llvm/install-llvm/slc6_amd64_gcc700/external/llvm/7.0.0-cms/lib64/clang/7.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /build/muz/llvm/CMSSW_10_3_X_2018-09-20-2300/src -ferror-limit 19 -fmessage-length 363 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ - -faddrsig
clang -cc1 version 7.0.0 based upon LLVM 7.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /build/muz/llvm/install-llvm/slc6_amd64_gcc700/external/llvm/7.0.0-cms/lib64/clang/7.0.0/include
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 389 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

while with LLVM 6.0 it was returnings cms external GCC path. This PR should explicitly pass --gcc-toolchain to force clang++ to look in to cms external gcc.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
FYI @fwyzard, I do not know if there is any better way to fix this e.g. by setting some env variable or building llvm with some flag?

**Comment by fwyzard** [comment]
I can look if it can be set when building llvm.
However, wouldn't it break when we relocate the packages during installation ?

**Comment by smuzaffar** [comment]
yes build time path will break unless there is way to relocate e.g. some configuration file in llvm.

**Comment by smuzaffar** [comment]
we are missing this CMS patch clang 7 https://github.com/cms-externals/llvm-project-20170507/commit/85a9c36d893831f7c7ea73eaa6a74997739a0a0b#diff-c338d6d0b1a666a15fa597e194768aa3

@fwyzard , I would suggest to close this PR and patch clang 7, any objections?

**Comment by fwyzard** [comment]
Hi Shazad,
is there no way to do this already in clang ?

.A

**Comment by fwyzard** [comment]
OK. On the other hand, do you know what may have changed, that clang needs to be told how to find the "correct" gcc ?
It used to be that clang would use what it finds on the PATH, right ?

**Comment by smuzaffar** [comment]
@fwyzard , nothing changed on the clang side. clang was always looking for GCC_INSTALL_PREFIX (provided at built time) and if not found then was falling back to default system path (/usr). We were patching it to first look in to COMPILER_RUNTIME_OBJECTS. Only thing changed for 7.0 is that we did not apply our patch.

**Pull request closed without merging**
