### PR TITLE
Backport of new pileup jet ID for MiniAOD re-processing

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of the following PRs:
#10398 jbrands:newOfflinePuID_new
#10730 ahinzmann:fixpuid
#10625 ahinzmann:PUjetIDcleanup76
#10923 ahinzmann:pileupjetiddqm76

They contain a new training of the pileup jet ID with 74 MC.
This is not the final/optimal training, but already better than the 53 training on 74 MC (ROC curves are in #10625). Optimization of a working point for MVAmet is also not yet done, thus it is not configured to be used in MVAmet.

runTheMatrix -l limited works in CMSSW_7_4_10_patch1

@gpetruc this can be included in the MiniAOD processing

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ahinzmann** [comment]
@slava77 maybe this needs another triggering of tests, since I included one commit a minute after the test was requested

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1
This is backport from 76X PRs which are already approved.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11007	 e00bc47
- backport contains changes from the 76X PRs as described
- jenkins tests pass and comparisons with baseline show differences only in DQM plots in cleaned jets and in PU-ID variables, as expected (monitored RECO products are unchanged)
- the list of products stored in RECO/AOD output and their size is unchanged

**Comment by slava77** [comment]
@deguio @danduggan please check this PR

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
