### PR TITLE
New E/g HLT Pixel Matching : 90X

### PR DESCRIPTION
**Pull request by Sam-Harper**
This pull request upgrades the pixel matching used by the E/gamma HLT to be able to match to hits other than doublets to take advantage of the new phase I pixels. 

This PR creates new modules and producers for pixel matching, the old objects continue to work and will behave exactly the same as before. So no changes are expected to be observed in any current test. It is expected that RECO will eventually move to these new producers.  

The one potential impact and the area is the ElectronSeed class. We need a dataformat change to deal with the fact we now have a variable number of pixel hit matches. ElectronSeeds are used downstream by several modules and it would be messy to have another ElectronSeeds class in parallel (ie ElectronSeeds and ElectronNHitSeeds) as we would have to adapt all those modules to look for both. Both options are not great but I think its probably better long term to change ElectronSeed rather than making a new class. Up for discussion of course. 

New Classes: 

EgammaHLTFilteredSuperClusterProducer  : filters the superclusters on which the pixel matching is to be performed. This will be HLT specific, reco will have different criteria. A major benefit of this is that now the pixel matching and H/E cuts cut on the same H/E value rather than trying to sync two different calculations

TrackingRegionsFromSuperClustersProducer:  makes the tracking region around the supercluster, accepts a std::vector<reco::SuperClusterRef> telling it which superclusters to use. Can not use a edm::RefVector as the superclusters are in different collections (barrel and endcap) and its awkward to seperate them back into separate collections from the input we have (a single collection of reco::EcalCandidates). 

TrajSeedMatcher:  replaces PixelHitMatcher, actually does the matching. In general some clean up is needed (it has an intermediate format like PixelHitMatcher has which is probably redundant). Not fully happy with the name

ElectronNHitSeedProducer : makes the electron seeds with a variable number of matched hits

I have now done the initial validation such that I'm confident that its worth running the jenkins tests. I have been focusing on ensuring I do not make any unintentional changes to RECO output  (and I intend zero changes other than the format change) and that I can read back old ElectronSeeds correctly in the new format. I have been using a privately produced 900 (GEN-SIM) + 902 (RAW-RECO) Single Electron gun pt1To100, noPU 100K sample to validation on

First I can read back old seeds with the new code and all the member functions return identical results:
https://sharper.web.cern.ch/sharper/cms/egamma/eleSeedValidation/readingOldSeeds/

Secondly, I made sure that I didnt not disrupt RECO electron reconstruction by running in 902 and 902+this PR to check that there were no differences as expected. 

https://sharper.web.cern.ch/sharper/cms/egamma/eleSeedValidation/newRECOvsOldRECO/#h_ele_seedSubdet2

unit tests are being re-run in the latest IB, (already all passed in 902) and then runTheMatrix will be launched.

### CODE REVIEW

**Comment by perrotta** [comment]
Please @Sam-Harper go ahead with your tests and possible updates, and let us know when you are done with them so that jenkins tests can be launched and we can start our review.
Please be aware that before having it backported to 90X it has to be first submitted and merged in the master,

**Comment by slava77** [comment]
@Sam-Harper 
what is the size of the new ElectronSeed object compared to the old one?
It looks like it may be doubles or even triples.
It should be checked probably up to PU200 that this is still manageable.

**Comment by Sam-Harper** [comment]
A good point. I am being a little wasteful storing the DetIds and can trim a little if really needed although it probably wont help much. Which sample would you recommend to do measure ?  /RelValTTbar_14TeV/CMSSW_9_0_0_pre5-PU25ns_90X_upgrade2023_realistic_v4_D11TPU200-v1/GEN-SIM-DIGI-RAW ? 

Here are the size arguments: 

For RECO, we go from 2references + 2 bools +  10 floats + 2 ints + 1 char to a vector of  4 floats + 2 ints with two entries   + 2references + 2 bools + 1 int.  

So ignoring the references and bools, we go from 10 floats + 2 ints + 1 char -> 8 floats + 4 ints + whatever vector overhead there is.  And the the Trajectory seed object has and edm::OwnVector of TrackingRecHits (3-5) and a PTrajectoryStateOnDet. So while compression can help out and make this more difficult, I would say more 10-20% increase than tripling it. 

Anything that is not ecalDriven has the std::vector empty which also further reduces the change but by how much I dont know.

**Comment by Sam-Harper** [comment]
Oh and runTheMatrix.py -l limited -i all  and scram b runtests have now all succeeded (except for some das errors) again in the latest 90X integration build. I'll port it to 91X tomorrow and re-run the tests there.

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
ah didnt release gcc making std::cos constexpr was not actually part of the c++ standard. easy fix. done.

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@Sam-Harper 
Thanks for the more detailed size estimates from the first principles. It seems like the size increase is not as significant as I guessed.
If it's within 10-40%, maybe a faster check could be to look at the electronMergedSeeds in phase-1 with PU (e.g. ttbar PU35, matrix workflow 10224 or a similar).

PU200 check will just take longer and appears less critical if the increase in size is moderate.

**Comment by Sam-Harper** [comment]
So now the HLT has moved to 910pre3, I'm no longer sure we need this in 90X. If I dont hear otherwise, I'll close it tomorrow, with the discussion continuing on  https://github.com/cms-sw/cmssw/pull/18541

**Comment by Martin-Grunewald** [comment]
In principle yes (ie, no longer needed), but perhaps hold off until we get a proper GT to actually run with 91X on the 83X TSG samples...

**Comment by Sam-Harper** [comment]
Okay, I'll continue to maintain this branch untill we get that GT. Although probably not worth re-running tests until we know we need it.

**Comment by perrotta** [comment]
+1
(Same commits and code changes as in #18541: same comments)
Based on the extensive code review and adjustments applied after it, plus:
- Explanation of the observed reduced event size of recoElectronSeeds_electronMergedSeeds as in https://github.com/cms-sw/cmssw/pull/18541#issuecomment-299230470
- No effect on jenkins outputs
- Validation provided in https://github.com/cms-sw/cmssw/pull/18541#issuecomment-299037499
- Result of the consultation with experts about the dictionary directives, summarized in https://github.com/cms-sw/cmssw/pull/18541#issuecomment-299222246

**Comment by perrotta** [comment]
I see that signatures were not requested yet for this 90X pull request...

Ok, don't remove it anyhow, so that it gets off our list. This PR needs anyhow to be signed by HLT before proceeding: HLT can then either decide to close or push it.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
