### PR TITLE
Add new Run3_ckfPixelLessStep to StandardSequences

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Add the new `Run3_ckfPixelLessStep` era (introduced in #38437) to `Configuration/StandardSequences/python/Eras.py`.

While starting the release validation of CMSSW_12_4_1, @bbilin noticed that the driver was failing with the error:
```
raise Exception( "'%s' is not a valid option for '--era'. Valid options are %s." % (eraName, validOptions) )
Exception: 'Run3_ckfPixelLessStep' is not a valid option for '--era'. Valid options are 'Run1_pA', 'Run1_peripheralPbPb', 'Run2_50ns', 'Run2_50ns_HIPM', 'Run2_25ns', 'Run2_25ns_HIPM', 'Run2_25ns_peripheralPbPb', 'Run2_HI', 'Run2_2016', 'Run2_2016_HIPM', ....
```
So the new era was not recognized.
With the input from @mmusich I added the new era (and the modifier) in the (hopefully) correct place.

At the same time the era cfg was wrongly named `Era_Run3_ckfPixelLessStep.py` instead of `Configuration/Eras/python/Era_Run3_ckfPixelLessStep_cff.py`. This is fixed in this PR as well.

#### PR validation:
N/A

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, a backport to 12_4_X will be needed

### CODE REVIEW

**Comment by mmusich** [comment]
@mmasciov @slava77

**Comment by mmusich** [comment]
can we please add a workflow that tests this?

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by mmusich** [comment]
duplicate of https://github.com/cms-sw/cmssw/pull/38565

**Pull request closed without merging**
