### PR TITLE
Generate events without MPI if LBCR or CRSS performed with MPI.

### PR DESCRIPTION
**Pull request by EmyrClement**

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@EmyrClement was this practically tested? The PR test does not probe this piece of code...

**Comment by qliphy** [comment]
@fabiocos   The issue was identified during last Friday's [Sherpa workshop](https://indico.cern.ch/event/779232/).   MakeSherpaLibs.sh is used to create Sherpa gridpack, but also contains 101 events production for a sanity check.  It was found by Emyr that with MPI, the sanity check step is very slow.  (It will not affect the afterwards event producing with sherpa gridpack)  

Both us have checked with this PR and it works well.

**Comment by fabiocos** [comment]
+1

@EmyrClement @qliphy thanks for the clarification

**Pull request merged**
