### PR TITLE
Removed histograms from an EDProducer, new EDAnalyzer, some configuration adjustments and update of the documentation

### PR DESCRIPTION
**Pull request by venturia**

### CODE REVIEW

**Comment by venturia** [comment]
@threus , @suchandradutta @gbenelli , @jlagram: if you want to test you can check whether the DQM plots which depends on the APV cycle phases or the badstrip ALCARECO workflow filters are different after this change.

**Comment by venturia** [comment]
@Dr15Jones this pull request contains a change you have asked for

**Comment by Dr15Jones** [comment]
thanks for the change

**Comment by venturia** [comment]
Added new macros and configurations to analyze out of time occupancy. Replace kCanRebin with SetCanExtend

**Comment by venturia** [comment]
kCanRebin replaced also in Validation/RecoVertex

**Comment by deguio** [comment]
+1

**Pull request merged**
