### PR TITLE
Phase2-hgx360Q Correct the passive absorber description and add the cooling petal for HGCal EE detector

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the passive absorber description and add the cooling petal for HGCal EE detector

#### PR validation:

Test using fireworks

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar, @subirsarkar Please approve this

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
