### PR TITLE
update the list of the paths monitored in the Higgs HLT (backport)

### PR DESCRIPTION
**Pull request by HuguesBrun**
This PR in the backport in 74X of the PR #9170

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by HuguesBrun** [comment]
Dear all,
 I updated this PR with a commit corresponding to a bug fix mentioned in PR #9271.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
