### PR TITLE
Add HCAL LLP Jet Skim config

### PR DESCRIPTION
**Pull request by kennedykiley**
#### PR description:

This PR adds the config for a RAW-AOD skim for HCAL-based LLP candidate events, based on new LLP trigger paths.
The HCAL RecHit skim saves the following collections in addition to standard RAW-AOD output:
```
HBHERecHit (via 'keep *_hbhereco__*')
```
The HCAL RecHit skim selects events passing the following HLT paths, which are included in the prompt HLT menu: 
```
HLT*_L1SingleLLPJet_*
```
[LLP HLT Jira Ticket ](https://its.cern.ch/jira/browse/CMSHLT-2280)

#### PR validation:

Tested with the following 2022 data samples in ```CMSSW_12_4_0_pre1```:
```
/DisplacedJet/CMSSW_12_4_11-124X_dataRun3_Prompt_v4_gtval_RelVal_2022D-v1/RECO
```
The skimmed file event size was 0.7 MB (87 total events) and the unskimmed file was 3.2 GB (1000 total events). 

The test script, generated with cmsDriver, is on lxplus: ```/afs/cern.ch/user/k/kikenned/public/Skims/2023-03-20/test_EXOLLPJetHCAL_SKIM.py```

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @kennedykiley , please make another PR to backport this PR to 13_0_X milestone for 2023 data taking.

**Comment by perrotta** [comment]
@kennedykiley even before preparing a backport, please fix the conflicts here in the master, so that this PR can be tested

**Comment by kennedykiley** [comment]
Hello! Thanks for your comments and suggestions. I've rebased my branch with the official master & added a PR for 13_0_X.

**Comment by tvami** [comment]
> Hello! Thanks for your comments and suggestions. I've rebased my branch with the official master & added a PR for 13_0_X.

You should have rebased to `13_1_X` not `13_0_X`

**Comment by tvami** [comment]
-1
 * rebase to `13_0_X` brought in alca signature

**Comment by aloeliger** [comment]
-1

- Duplicate L1 commits

@kennedykiley did you use `cms-merge-topic` instead of `cms-rebase-topic`? These are all duplicate commits.

**Comment by bsunanda** [comment]
-1

**Comment by missirol** [comment]
@kennedykiley , please do a proper rebase, or close this PR and open a new one.

**Comment by kennedykiley** [comment]
I'm very sorry about all the issues I inadvertently caused in the PR with my improper rebase. Closing now -- I'll open a fresh PR started from the latest release. Thanks for everyone's help and feedback!

**Pull request closed without merging**
