### PR TITLE
[L1T] fix signed integer overflow in LUT.cc

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Addressing issue https://github.com/cms-sw/cmssw/issues/35005

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
please test for CMSSW_12_5_UBSAN_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_5_UBSAN_X

**Comment by cecilecaillol** [comment]
+l1

**Comment by tvami** [comment]
+1

**Comment by perrotta** [comment]
+1
- Issue https://github.com/cms-sw/cmssw/issues/35005 reports about undefined behavior is reported in two files for CondFormats:
  - CondFormats/JetMETObjects/src/SimpleJetCorrector.cc
  - CondFormats/L1TObjects/src/LUT.cc
- This PR fixes the second one, while the first still needs to be addressed

**Pull request merged**
