### PR TITLE
Add dictionaries for FindUsingAdvance in TrackReco

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This appears to stop some of ROOT's auto parsing.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- technical PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
