### PR TITLE
New HLT DEBUG object: EgTrigSumObj : CMSSW_11_1_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR adds the new E/gamma trigger debug object (now renamed trigger::EgammaObject 

No changes are expected as this is a producer which is only so far run in the e/gamma phase-II HLT

#### PR validation:

Tested in E/gamma Phase-II HLT

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
backport of
https://github.com/cms-sw/cmssw/pull/32486

useful for HLT TDR

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
What about 11_2?

**Comment by Sam-Harper** [comment]
I wasnt planning on bothering for 11_2 but could do if you think we should

**Comment by silviodonato** [comment]
please test
(the error should not be related to this PR)

**Comment by qliphy** [comment]
The error is not related to this PR

----- Begin Fatal Exception 15-Feb-2021 15:38:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------

**Comment by Martin-Grunewald** [comment]
Users may miss it when moving from 11_1 to 11_2...

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
