### PR TITLE
[125X] Fixed RP IDs in the PPS alignment harvester

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

See #39358

#### PR validation:

See #39358

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #39358

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39358

**Comment by tvami** [comment]
type bugfix,ctpps

**Comment by tvami** [comment]
test parameters:
  - workflows = 1042,1045

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
+alca

- backport-ok
- tests pass
- differences not related to this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
