### PR TITLE
add TenTau gen fragments

### PR DESCRIPTION
**Pull request by mtosi**
as requested by TAU POG,
there is the need of having this new gen fragment 
for increasing the effective statistics in the relval sample
used for the TAU @HLT release validation

@rmanzoni

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by rmanzoni** [comment]
before merging, see comment
https://github.com/cms-sw/cmssw/pull/18040#issuecomment-289782672

**Comment by govoni** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
