### PR TITLE
PF code clean up and refactor [ConvBremPFTrackFinder]

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
Clean up of `RecoParticleFlow/PFTracking/src/ConvBremPFTrackFinder.cc`

#### PR validation:
Tested with `12434.0_TTbar_14TeV+2023`

### CODE REVIEW

**Comment by swagata87** [comment]
enable profiling

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
