### PR TITLE
Remove cscTriggerPrimitiveDigis to prevent online client from crashing. Backport of PR24905

### PR DESCRIPTION
**Pull request by dildick**
@barvic @ptcox

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by boudoul** [comment]
[just adding the master PR number here : #24905  , so that the reference of the backport  is visible in the master PR ]

**Comment by fabiocos** [comment]
backport #24905

**Comment by fabiocos** [comment]
+1

affecting online DQM configuration, not probed by relvals

**Pull request merged**
