### PR TITLE
[Framework] Move publically used private headers in to interface dir

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR proposes to make private headers public as the public interface of these packages use them ( https://github.com/cms-sw/cmssw/issues/34718#issuecomment-902007063 )

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
any objections @Dr15Jones , @makortel ?

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
