### PR TITLE
[13_0_X backport] New Run3 era for updated HB thresholds in 2023

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/41271

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by malbouis** [comment]
@cms-sw/reconstruction-l2, in case you agree with this PR would you please sign it? We would like to have it integrated in a release soon so that it can be properly tested on a Tier0 replay.

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
