### PR TITLE
Improvements in DBOutputService transaction workflow

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

The PoolDBOutputService object is the main CMSSW interface for the creation of new condition set and the update of Tags in the central database.  The actions supported ( create, append, write, erase, ... ) require to operate within a transactional workflow, generally explicit, optionally implicit. The overall model and the implementation has been revisited, simplifying and clarifying the usage of the interface on the client side.

#### PR validation:

unit tests and integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ggovi** [comment]
please test

**Comment by tvami** [comment]
+1
 * Jenkins tests pass, diff in MsgLogger only

**Comment by qliphy** [comment]
+1

**Pull request merged**
