### PR TITLE
Fix a typo in quadruplet seeds

### PR DESCRIPTION
**Pull request by rovere**
This only affects PhaseII.
Due to the current redundancy in seeding, I do not expect substantial changes (if any at all).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
type bugfix

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17421	4f167ab
- clear fix for a typo in negative z side seeding layers for phase2 quadruplets
- jenkins tests pass and comparisons with baseline show small differences only in 2023 workflows
- local test with PU200 shows somewhat expected behavior, done mostly to see how these specific layer combinations contribute 

in 23034 with PU200, there is a clear recovery in negative eta

all_sign847vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recopfcandidates_particleflow__reco_obj_eta43
all_sign847vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recotracks_generaltracks__reco_obj_eta

these are all mostly pt~<0.5GeV


pixel tracks have a more significant increase
all_sign847vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recotracks_pixeltracks__reco_obj_eta

Looking at MTV plots, it seems like an example where the MTV doesn't capture the changes:
- efficiency is unchanged
- dup rate is slightly lower
- fake rate is slightly higher

wf23034pu200_general_fake_eta
wf23034pu200_general_dup_eta


on the technical side:
- CPU total is roughly unchanged (initialStep is up, others are down)
```
delta/moduleMean  delta/jobMean  baseline       new
   -0.563402      -0.01%       331.97 ms/ev ->       186.05 ms/ev detachedQuadStepHitDoublets
   -0.481590      -0.01%       209.22 ms/ev ->       128.02 ms/ev lowPtQuadStepHitDoublets
   -0.358772      -0.00%        75.78 ms/ev ->        52.73 ms/ev newCombinedSeeds
   -0.178422      -0.00%       162.87 ms/ev ->       136.19 ms/ev highPtTripletStepHitDoublets
   -0.069062      -0.00%       123.30 ms/ev ->       115.07 ms/ev initialStepHitDoublets
   -0.058785      -0.00%       224.56 ms/ev ->       211.74 ms/ev pixelTracksHitDoublets
   +0.112079      +0.00%       335.06 ms/ev ->       374.84 ms/ev initialStepSeeds
   +0.057769      +0.12%     22367.90 ms/ev ->     23698.50 ms/ev initialStepTrackCandidates
   +0.104160      +0.02%      1745.87 ms/ev ->      1937.71 ms/ev allConversions

```
- product totals are up a bit (0.5% for generalTracks, 3% for pixelTracks, smaller effects downstream)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
