### PR TITLE
Fix configurations and their descriptions in recoTau

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

This PR is intended to fix the issues reported in https://github.com/cms-sw/cmssw/issues/26236, which were subsequent to the merge of #24501
The test PhysicsTools/PatAlgos/test/patTuple_PATandPF2PAT_cfg.py was testing a few configs not touched in the standard workflows, and which were evidently badly configured in the fillDescription of the relevant producers

A previous attempt was made with #26252, but while testing it it hits a segmentation violation in fastsim: that seems to be related to the fix.
Let retry this other possible fix, before giving up.

This PR:
- adjusts those fillDescriptions() so that all needed parameters can be included and validated;
- avoids duplicating a few configs, by renaming the default ones produced by the configuration validation (or by simply removing PFRecoTauProducer_cfi.py as a whole, it being a duplicate of the one created by fillDescriptions());
- removes the useless specific definitions of hltPFTauPiZeros & hltPFTauPiZerosReg in the fillDescriptions(), which are never used as such and add nothing to the validation

Still  to be done:
- Further cleaning the duplicate modules
- Possibly avoid replicas of validations, see for example all the variants included in RecoTauPiZeroProducer::fillDescriptions() which I bet they could more conveniently get specialized in the cfi config starting from a common parameterSetValidation

@swozniewski @mbluj please have a look. 

#### PR validation:

Tested running the previously failing PhysicsTools/PatAlgos/test/patTuple_PATandPF2PAT_cfg.py
It passes the unit test "fastsim1", which fails in #26252
Short matrix also succeeds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@Martin-Grunewald

**Comment by perrotta** [comment]
+1
- Changes in the configs, both explicit and automatically created by fillDescriptions(), solve the crash of the unit test patTuple_PATandPF2PAT_cfg.py that was reported in #26236
- No changes in the reco output due to these changes
- jenkins tests pass
- Still to be done (in a future cleaning PR):
  - Further cleaning the duplicate modules
  - Possibly avoid replicas of validations

**Comment by fabiocos** [comment]
+1

@perrotta thanks

**Comment by Martin-Grunewald** [comment]
There is still a problem:

```
  -> hltHpsTauPFJetsRecoTauChargedHadronsWithNeutrals [PFRecoTauChargedHadronProducer] CHANGED
       int32 verbosity = 0 [ADDED]
       VPSet builders [REMOVED]
       VPSet ranking [REMOVED]
```
ie, two VPSets seem erranoeusly dropped from the generated cfi file of ```PFRecoTauChargedHadronProducer]```

**Comment by perrotta** [comment]
> There is still a problem:
> 
> ```
>   -> hltHpsTauPFJetsRecoTauChargedHadronsWithNeutrals [PFRecoTauChargedHadronProducer] CHANGED
>        int32 verbosity = 0 [ADDED]
>        VPSet builders [REMOVED]
>        VPSet ranking [REMOVED]
> ```
> ie, two VPSets seem erranoeusly dropped from the generated cfi file of `PFRecoTauChargedHadronProducer]`

Thank you @Martin-Grunewald : I think the very same fix provided for the RecoTauPiZeroProducer (her + #26273) should be applied for the PFRecoTauChargedHadronProducer].

@swozniewski could you please take care of it? It can be done with a different PR than #26273, no need to merge the things (although at some point some factorizations which avoids code duplication in the whole package could be attempted... but not now, as the configs are slitghtly different in the different producers, and some more work is needed for it)

**Comment by swozniewski** [comment]
@perotta yes, I'll take care of it. Is it urgent or can combine it in a PR with some more clean up, let's say on a timescale of one or two weeks?

**Comment by perrotta** [comment]
> @perotta yes, I'll take care of it. Is it urgent or can combine it in a PR with some more clean up, let's say on a timescale of one or two weeks?

Please take into account that officially Apr 9 is the deadline for the last open pre-release for the UL release: we may expect a few days delay, but I wouldn't count of them in my planning

**Comment by perrotta** [comment]
@swozniewski please let us know if you plan to provide the fix in short. Next week the release will be closed for update, and we need to have it earlier on

**Comment by swozniewski** [comment]
@perotta, yes I planned to provide it today

**Comment by perotta** [comment]
> @perotta, yes I planned to provide it today

I appreciate your inviting to contribute in this project but I'm afraid I will not attempt to help you guys this time. See you next time!

**Pull request merged**
