### PR TITLE
Run3-alca142 Modify the datastream for HcalIsolatedBunchSelector

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the datastream for HcalIsolatedBunchSelector

#### PR validation:

Add HcalIsolatedBunchSelector AlCaReco to the Commissioning data stream

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May be needed to backport this to 13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@cmsbuild , please abort
 * the wf that runs the alcareco mtx was not set

**Comment by bsunanda** [comment]
@tvami We can remove HcalCalIsolatedBunchFilter from the matrix to be used. Can HcalCalIsolatedBunchSelector stay unchanged? We can make these changes now.

**Comment by tvami** [comment]
@bsunanda I didnt mean to remove it just from the matrix, but completely remove it from CMSSW. It is a dupplicate after all...

**Comment by bsunanda** [comment]
@tvami I have removed the IsolatedBunchFilter from all Configuration packages. Which is the wf that runs the AlCaReco matrix which needs to be set?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
hi @bsunanda , the producer itself, the cc files, could be cleaned up as well, not just the mentioning of it

> Which is the wf that runs the AlCaReco matrix which needs to be set?

these ones: `1001.2, 1001.3, 1002.3, 1002.4`

**Comment by bsunanda** [comment]
@tvami I have to clean HcalAlCaProducer. I shall remove them soon. But this PR is to be integrated first. Could you start those AlCaReco matrices?

**Comment by tvami** [comment]
> But this PR is to be integrated first.

There must be a misunderstanding here. This PR is not relevant for data taking, the AlCaRECO matrix dict is only used in the rereco, i.e. not urgent until October. T0 has `HcalCalIsolatedBunchFilter` attached to the `Commissioning` PD, as it was earlier requested from HCAL. If you want `HcalCalIsolatedBunchSelector` to be attached to the `Commissioning` PD, you need to ask the T0 friends to do that, here https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210

FYI @mariadalfonso (I feel like we are going back and forth between these HCAL isobunch ALCARECOs -- but given that they are supposed to do the same thing, maybe it doesnt matter...)

**Comment by bsunanda** [comment]
@tvami Please approve this PR. I cannot make a separate PR to remove the duplicate code unless this PR is merged.

**Comment by tvami** [comment]
@bsunanda I'm sorry by why couldn't you? Also, as I've been trying to say for a month now, this PR is not relevant for data taking, see https://github.com/cms-sw/cmssw/pull/41510#issuecomment-1538452509

**Comment by tvami** [comment]
>  I'm sorry by why couldn't you?

I mean, just make other commits to this PR.

**Comment by bsunanda** [comment]
@tvami I have one more branch ready to be submitted - just waiting for this PR to be merged

**Comment by tvami** [comment]
+alca
 * see https://github.com/cms-sw/cmssw/pull/41510#issuecomment-1566361254

**Comment by bsunanda** [comment]
@perrotta Could you please merge this now?

**Comment by perrotta** [comment]
@cmsbuild please test workflow 1001.2,1001.3,1002.3,1002.4

**Comment by perrotta** [comment]
+1

**Pull request merged**
