### PR TITLE
HLT menu "Luna" V3.1 (93X) 

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT menu "Luna" V3.1 (93X) 
Based on CMSSW_9_3_0_pre5

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #20455

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
please sign for addOnTests (backport 1)

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
