### PR TITLE
[HCAL-DQM] New plot BadQualityEvents vs all LS and changes of alarm threshold for CapID and BadQEvents for CMSSW_14_0_15_patch1

### PR DESCRIPTION
**Pull request by denizsun**
#### PR description:

  - A new plot BadQualityEvents vs all LS is added, 
  - Changes of error and warning alarm thresholds from 1 to 0.994 for both CapID and BadQEvents
 
#### PR validation:

<!-- runTheMatrix test is done

#### This is not a backport PR.

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
backport of #46173

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
hold 
any reason to put this in 14_0_X at this point?

**Comment by antoniovagnerini** [comment]
as these set of changes are meant for the live monitoring, I believe you can close the PR @mandrenguyen

**Comment by antoniovilela** [comment]
please close

**Pull request closed without merging**
