### PR TITLE
GT Initialization: ignoring non-existing record in the plugins pre-load

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

CMSSW Workflows requiring the consumption of conditions can be successfully executed  when all the records involved in the code are represented by their corresponding entries in the Global Tag loaded from the Condition Database. 

Conversely, additional Records included in the GT Record-Tag map could be ignored when they are not involved in the Workflow code.  This is the case, for instance, of Records that have been completely removed from the CMSSW Code.

This PR is addressing this last particular circumstance.  The GT initialisation has been modify to ignore the Records for which the corresponding plugin can't be found in CMSSW.

The new behaviour is obviously applied to Records added manually with toGet statements, when not present in the release.

Note that these changes are not altering the current behaviour for other possible mis-matches between release and database,  that could happen at later stage in the processing:

- Failures produced when no suitable IOV is found for a record invoked in the Workflow
- Failures produced when the payload to be used for a given record cannot be read in the release, because written with a higher boost version
- Failures produced when the Record, associated to given CondFormat in the release,  is mapped in the GT, to a Tag populated with payloads from a different class ( this is normally forbidden by policy )

#### PR validation:

Integration test, executed with a specific GT (106X_mcRun2_asymptotic_v15) triggering in 12X the condition of 'missing record plugin'

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by francescobrivio** [comment]
+alca

**Comment by silviodonato** [comment]
@fwyzard  asked by e-mail what happens if a record class is changed (from v1 to v2). 
If I've understood correctly, CMSSW will check if a payload of the required record (v2) is contained in the global tag and it will give error if the record is missing, even if a payload of the old record (v1) is contained.
Same thing happens if the differences between the two classes two incompatible versions of boost.
https://groups.cern.ch/group/cms-release-dataops/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fcms%2Drelease%2Ddataops%2FLists%2FArchive%2FPolicy%20for%20Removal%20of%20Condition%2Drelated%20record%20from%20CMSSW&FolderCTID=0x01200200730B983A7D7A6A42AC4F2B748B8D1551

Shortly, in both cases, there is no risk to read a payload in a wrong way.

@ggovi have I understood it correctly?

**Comment by ggovi** [comment]
The record class in itself cannot change, as its scope is essentially labelling a data consumption context. In theory, what can be changed is the CondFormat class associated via the macro 'REGISTER_PLUGIN'. This change is already forbidden by policy. Anyhow, non-spotted changes of this type cannot cause mis-interpreted reading of stored payload, as the de-serialization is attempted only when the payload class matches the record class. In case of mis-match, an exception is thown at the payload consuming time. This behavior is not altered by the present PR.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
