### PR TITLE
[10X] Fix return value for TIB and TOB in 'TrackerTopology::side'.

### PR DESCRIPTION
**Pull request by ghellwig**
Fixes an inconsistent behaviour of `TrackerTopology::side`.
Did also some clean-up of the method.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ianna** [comment]
@ghellwig - it looks like there is a bug in determining the side:
```
%MSG
----- Begin Fatal Exception 01-Nov-2017 15:47:01 CET-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'prevalidation_step1'
   [2] Calling method for module MultiTrackValidator/'trackValidatorBuilding'
Exception Message:
Unknown side 3
----- End Fatal Exception -------------------------------------------------
```

**Comment by ianna** [comment]
-1

**Comment by ghellwig** [comment]
@makortel Looks like you are relying on the previous behaviour:
https://github.com/cms-sw/cmssw/blob/master/Validation/RecoTrack/src/MTVHistoProducerAlgoForTracker.cc#L1584-L1590

@ianna I don't know why exactly a value of 3 is returned, but it might be related to a bug in the behaviour in phase2.

**Comment by ghellwig** [comment]
I would assume this could be fixed by a proper payload of the `TrackerTopologyRcd` for phase2.
Closing this now...

**Comment by makortel** [comment]
@ghellwig Indeed I am. And actually TrackerTopology (helpers) itself assume that `side()` is the same for all modules within a layer/disk
https://github.com/cms-sw/cmssw/blob/2f95528444c246a659126fdc8251a0bf4cbf0bd1/DataFormats/TrackerCommon/interface/TrackerTopology.h#L116-L124
(ok, I'm the guilty one for that aswell...)

Without thinking too much further I'd say that it would be easier to preserve the behaviour of `side()`, and if there is a use case for the `side()` proposed in this PR add a new function for that (or rename the old `side()` and migrate all current users of it).

**Comment by ghellwig** [comment]
@makortel thanks for the explanation.
There is actually no use-case yet, but I have a small tool to be submitted to CMSSW soon that calls `TrackerTopology::side` for the endcaps and the barrel-side methods afterwards.
I just thought it would be convenient to return the side directly by `TrackerTopology::side` also for the barrels.
For two reasons, this is apparently a bad idea: This PR breaks the consistency of the `TrackerTopology` class itself (as pointed out by you) without further extensive changes and if I want to extend the concept of a side to barrels, I would need it also for the pixel barrel where such a method is not implemented.

Anyway, at least the switch statement would have been nicer from my point of view, but that's certainly not sufficient to make a PR ;)

**Pull request closed without merging**
