### PR TITLE
Fix era for DQM BeamSpot clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Fix the era modifier for the DQM BeamSpot clients.

#### PR validation:
Compiles - 12_0_X version should be tested in Playback at P5.

#### Backport
Will provide backport to 12_1_X and 12_0_X

FYI: @gennai @mtosi @mmusich @dzuolo @vmariani

### CODE REVIEW

**Comment by francescobrivio** [comment]
please test with #35905

**Comment by mmusich** [comment]
please test with https://github.com/cms-sw/cmssw/pull/35921

**Comment by francescobrivio** [comment]
please test with #35921,#35766

**Comment by francescobrivio** [comment]
@qliphy @perrotta I don't understand the `errors in the baseline`...
Anyway the 12_0_X PR is already merged.

**Comment by qliphy** [comment]
@francescobrivio 
This is because IB already having errors, and has just been fixed by #35766

**Comment by qliphy** [comment]
please test with #35921

**Comment by francescobrivio** [comment]
> please test with #35921

I already tested this including that PR, see https://github.com/cms-sw/cmssw/pull/35898#issuecomment-955768008

**Comment by qliphy** [comment]
> @qliphy I already tested this PR including that PR, see [#35898 (comment)](https://github.com/cms-sw/cmssw/pull/35898#issuecomment-955768008)

Yes, but this time we will test against new IB:   CMSSW_12_2_X_2021-10-31-2300
which doesn't have so many errors as last IB.

**Comment by jfernan2** [comment]
+1
Backport tested in Online DQM at P5

**Comment by perrotta** [comment]
+1
- Move to Run3 era

**Pull request merged**
