### PR TITLE
Updating FastjetJetProducer (and related producers) with fillDescriptions (version3)

### PR DESCRIPTION
**Pull request by alefisico**
Continuing #18975, removing duplicate fillDescriptions.

### CODE REVIEW

**Comment by perrotta** [comment]
@alefisico 

I don't think this PR actually removes duplicate pieces of code. If I am not wrong, this is the old one, with some less commit and some less file changed: is it this what you had in mind? If so could you please explain the differences with respect to the previous PR? 

What I had in mind, instead, is in perrotta:CMSSW_9_2_X_FastjetJetProducerUpdateWithFactorizedFilldescriptions
where the commit 7f6906b718f38e4459191216e4eb63388b12f992 is what factorizes the calls in the different fillDescriptions. Could you please check if that git branch actually contains what you need? If you (and @makortel and @fwyzard as well, who also proposed a possible fix) agree, we can make a PR out of that branch and go on with it.

**Comment by alefisico** [comment]
@perrotta it does. 
FastjetJetProducer is a subclass of VirtualJetProducer, and CATopJetProducer is a subclass of FastjetJetProducer.
The "duplicate fillDescriptions" was in VirtualjetJetProducer https://github.com/cms-sw/cmssw/pull/18975/files#diff-83b3daa59ef1831efd0323d3a7ac058f
and I remove it, since we needed in FastjetJetProducer for confdb.  
However, since the FastjetJetProducer has a fillDescription method, the CATopJetProducer requires it too. That is the one duplicate now. 
I also remove several other changes in the python config files that make some people worried.

**Comment by rappoccio** [comment]
I think we need to refactor these classes. At the time (many years ago) this was acceptable practice, but after the fillDescriptions migration it does not seem like this is optimal anymore. We should move toward a templated solution instead.

**Comment by perrotta** [comment]
Thank you @alefisico and @rappoccio 

In the short term, what about using the factorization as in https://github.com/cms-sw/cmssw/compare/master...perrotta:CMSSW_9_2_X_FastjetJetProducerUpdateWithFactorizedFilldescriptions (the same that I pointed out above in https://github.com/cms-sw/cmssw/pull/19090#issuecomment-306158450)? One could further apply on top of it the removal of the "several other changes in the python config files that make some people worried"

That could allow this PR being merged and made available for HLT development...

**Comment by alefisico** [comment]
I would just like to mention that we need this PR included in the release because we want to have some subtructure techniques available at HLT throught confdb. I understand there should be better ways to do it, but in principle these changes do not affect anything in the reconstruction or any other part of the code.
Now, as @fwyzard knows better than me, the next deadline for trigger approvals is in two weeks, which in case this PR goes fast and the changes are available in confdb by this week, leaves us just one week to study the changes in the triggers. It is an already extremely tight schedule. 
If I can suggest, I would ask to merge this PR as soon as possible in order to try to achieve these deadlines. Otherwise, if it keeps getting delay, we may drop it, keep just trimming at trigger level, and make a proper "cleaning/updating" of all these classes with more time.

**Comment by alefisico** [comment]
sorry, I didn't see https://github.com/cms-sw/cmssw/pull/19090#issuecomment-306200062 
I'm fine with it.

**Comment by perrotta** [comment]
Ok, if you are fine with it, we could either:
1) you take that branch (which is based on CMSSW_9_2_X_2017-06-04-2300), apply your latest python changes on it, and make a PR yourself out of it
2) you tell me which are those python to be adjusted (better if you provide the commit itself), I will add it to my branch. and I will make a PR out of it

Please let me know what do you prefer

**Comment by alefisico** [comment]
@perrotta I double check it and I think the python changes that you have in that branch are fine. (the only difference is here: https://github.com/cms-sw/cmssw/compare/master...perrotta:CMSSW_9_2_X_FastjetJetProducerUpdateWithFactorizedFilldescriptions#diff-5ad0f3bf52d042e35538780caf9c729dR14 but I think is fine)
Then please, go ahead an make the PR. 
Thanks

**Comment by perrotta** [comment]
Done, see #19098

**Comment by Martin-Grunewald** [comment]
@alefisico 
please close this PR as being obsolete.

**Pull request closed without merging**
