### PR TITLE
[13_0_X] Fix generator interface to Geant4

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
his is a backport of https://github.com/cms-sw/cmssw/pull/40820. See discussions on https://github.com/cms-sw/cmssw/pull/39427 and https://indico.cern.ch/event/1242612/

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

there is DAS timeout not related to this PR.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
