### PR TITLE
Decrease begin Run startup time for HLT

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Running igprof on an example HLT configuration uncovered that the vast amount of time spent in the begin Run transition was all the ShmStreamConsumer OutputModules calculating the ParameterSetBlobs to be stored in the files. This pull request adds the option to run ParameterSetBlobProducer at begin Run to create the ParameterSetBlobs once and then have all the OutputModules use that information. This decreased the time spent making the blobs from 147s in the orginal job to 4s.

#### PR validation:

The test configuration I was using ran fine both with and without ParameterSetBlobProducer added.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@fwyzard FYI I found this from the configuration you sent me.

**Comment by fwyzard** [comment]
thanks, looks like an interesting improvement !

**Comment by Dr15Jones** [comment]
In order to turn on the feature, I added the following to the test configuration I was using
```python
process.psetMap = cms.EDProducer("ParameterSetBlobProducer")
process.PhysicsMuonsOutput.associate(cms.Task(process.psetMap))
```

I.e. I added the EDProducer as a Task to one of the EndPaths, that made it available to all of the OutputModules.

**Comment by mommsen** [comment]
This sounds like a great improvement. Thanks for looking into this.
@smorovic, @emeschi, this could be of interest for you, too.

**Comment by emeschi** [comment]
Yes, very interesting. Do I get it right that the whole configuration is stored as a blob in every output file ?
Is this really necessary ?
If the numbers quote by   @Dr15Jones<https://github.com/Dr15Jones> are for a realistic HLT menu we should re-evaluate the actual startup time and see if we can say something new about the amount of input buffer needed in the HLT…
To be followed up


On 16 Apr 2020, at 17:08, Remi Mommsen <notifications@github.com<mailto:notifications@github.com>> wrote:



This sounds like a great improvement. Thanks for looking into this.
@smorovic<https://github.com/smorovic>, @emeschi<https://github.com/emeschi>, this could be of interest for you, too.

**Comment by smorovic** [comment]
Thanks for looking into it.
@emeschi, if I understand well, it is run product so it isn't written in every file or event (just INI file).

I can look at intialization time on HLT machine(s). @fwyzard, could you please point to this HLT python configuration? Is it similar to collision physics menu (i.e. something with similar number of modules, paths and output modules as we could have in Run 3)?

**Comment by emeschi** [comment]
Ah yes you’re right @smorovic. I had completely forgotten the init file.
Okay so the solution proposed is to only serialise the pest once and then have each output module get it from the run, right @Dr15Jones<https://github.com/Dr15Jones> ?
This means we had roughly 147/4-1~36 output modules in this config doing the same thing again and again…
That I guess sounds about right as the number of streams…

**Comment by Dr15Jones** [comment]
The relevant bit of the igprof log of the original version of the code is
```
[17]       59.6     154.72       0.00 / 154.72     edm::StreamerOutputModuleBase::beginRun(edm::RunForOutput const&)
           58.0  .........     150.65 / 150.65       edm::StreamerOutputModuleCommon::serializeRegistry(SerializeDataBuffer&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&, edm::ThinnedAssociationsHelper const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::Hash<1> const&) [18]

[18]       58.0     150.65       0.00 / 150.65     edm::StreamerOutputModuleCommon::serializeRegistry(SerializeDataBuffer&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&, edm::ThinnedAssociationsHelper const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::Hash<1> const&)
           57.9  .........     150.37 / 150.37       edm::StreamSerializer::serializeRegistry(SerializeDataBuffer&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&, edm::ThinnedAssociationsHelper const&) [19]

[19]       57.9     150.37       0.00 / 150.37     edm::StreamSerializer::serializeRegistry(SerializeDataBuffer&, std::vector<std::vector<unsigned int, std::allocator<unsigned int> >, std::allocator<std::vector<unsigned int, std::allocator<unsigned int> > > > const&, edm::ThinnedAssociationsHelper const&)
           56.8  .........     147.46 / 147.46       edm::pset::Registry::fillMap(std::map<edm::Hash<1>, edm::ParameterSetBlob, std::less<edm::Hash<1> >, std::allocator<std::pair<edm::Hash<1> const, edm::ParameterSetBlob> > >&) const [20]

```

**Comment by Dr15Jones** [comment]
> This means we had roughly 147/4-1~36 output modules in this config doing the same thing again and again…

Doing
```python
>>> len(process.outputModules)
36
```

shows your math is exactly right :).

**Comment by mommsen** [comment]
I think we should do a test with this change under realistic conditions asap. Not sure how to do it, though. @fwyzard, @smorovic, any suggestions?

If the speedup is indeed confirmed in HLT (which needs to load the conditions, too), it could save us quite a bit of money otherwise spent on DIMMs for the RAMdisk to buffer data during the CMSSW startup on the HLT farm.

**Comment by fwyzard** [comment]
> @fwyzard, could you please point to this HLT python configuration? Is it similar to collision physics menu (i.e. something with similar number of modules, paths and output modules as we could have in Run 3)?

@smorovic yes, it's a "frozen" version of an HLT menu from 2018, adapted to run with CMSSW 11.1.x (though I later realised that DQM and JSON monitoring is missing).
Here is the [hlt.py](https://fwyzard.web.cern.ch/fwyzard/hlt_timing/hlt.py) and a [data.tar.xz](https://fwyzard.web.cern.ch/fwyzard/hlt_timing/data.tar.xz) archive with the input in FED raw data format.

**Comment by fwyzard** [comment]
> I think we should do a test with this change under realistic conditions asap. Not sure how to do it, though.

I can run a realistic test once 11.1.0-pre6 is available (to use as a baseline).

By realistic I mean
  - 2018 HLT menu and L1-selected data at pileup ~50
  - using `.raw` input and `.dat` output
  - with 16 jobs with 4 threads each, running in parallel on a hilton-like machine

**Comment by mommsen** [comment]
One more point: the content of the blob (i.e. the init file) depends on the products which are written by the output module, IIRC. Is this taken into account with these changes @Dr15Jones ? It also implies that not all output modules can reuse the same blob.

**Comment by Dr15Jones** [comment]
> One more point: the content of the blob (i.e. the init file) depends on the products which are written by the output module, IIRC. Is this taken into account with these changes @Dr15Jones ? It also implies that not all output modules can reuse the same blob.

The part I did was the part they all use, the storage of the ParameterSets.

**Comment by smorovic** [comment]
@fwyzard thanks for the files.
We should install 11_1_0_pre6 in Hilton and BU appliance that I use for tests as soon as it's available. It was being prepared this morning so we can expect it soon.
I can run tests with scripts in BU appliance. It is equivalent to Hilton tests so we can compare (but I expect the same conclusion). In appliance test we can see init period from the microstate plot. Event sample won't matter since this all comes before first event.

**Comment by makortel** [comment]
+core

**Comment by mommsen** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Since ConfDB is not yet task-aware, how should this new producer be included in a menu?
Adding it to each EndPath with an OutputModule?

**Comment by fwyzard** [comment]
I would add it to the `HLTriggerFirstPath`, together with `hltGetConditions` and `hltGetRaw` .

**Comment by Dr15Jones** [comment]
> I would add it to the HLTriggerFirstPath, together with hltGetConditions and hltGetRaw .

I think Andrea's suggestion is a good one. It actually doesn't much matter since during Run and LuminosityBlock transitions modules are run in data dependency order, not in strict Path order.

**Comment by perrotta** [comment]
+1
- It adds the option to run ParameterSetBlobProducer at begin Run to create the ParameterSetBlobs once, and then have all the OutputModules use that information: this may speed up beginRun startup time for HLT: that option is not enabled by default
- Reco only affected by the needed modifications (new parameter added) in EventFilter/Utilities/EvFOutputModule
- Jenkins tests pass

**Comment by fwyzard** [comment]
On a job with 4 threads I see a reduction in the startup time (measured from the `%MSG-i ThreadStreamSetup
[diff.txt](https://github.com/cms-sw/cmssw/files/4493310/diff.txt)
 pre-events` message to the `Begin processing the 1st record` message) from `106 ± 2 s` to `62 ± 2 s`.

The diff to the hlt configuration is attached.

@Dr15Jones do you think this is coherent with your results ?

**Comment by Dr15Jones** [comment]
> do you think this is coherent with your results ?

There are two things happening
1. when using the old code under multi-threading several output modules could run concurrently at begin Run and just doing the exact same work so the biggest benefit happens at 1 thread in a job (since everything is serialized and the doing the same work over and over hurts the most). When using multiple threads, if the framework can find more work to do (based on data dependencies) then you can get a bigger 'win'.
1. conditions access can become the dominant timing for begin Run (I saw large variations in timing because of different response time from the frontier servers).

The work I'm trying to do for allowing EventSetup modules to run concurrently should also allow the framework to do better scheduling at begin Run.

**Comment by fwyzard** [comment]
OK, I'll try again
  - with a single threaded job
  - with a multi-threaded job
  - with a single threaded job, without any actual events and conditions data
  - with a multi-threaded job, without any actual events and conditions data

**Comment by smorovic** [comment]
I get similar result with BU-FU appliance. 
With12 FUs, 4-streams/thread processes (1 thread per hyperthread). I did two tries each case.

116 s, 113 s (no blob producer module)
73 s, 78 s (module added)

Average improvement: 39 seconds.
Note:  one HLT machine took longer than others, but only in "no blob producer" case. I ignored it for the result.

As far as I know, squid cache expiration is 30 seconds in HLT, and repeated attempts don't happen within that time frame.

**Comment by fwyzard** [comment]
> As far as I know, squid cache expiration is 30 seconds in HLT, and repeated attempts don't happen within that time frame.

Is that only for the data with a short lifetime (i.e. IOVs) or also for the actual immutable payloads ?

**Comment by Dr15Jones** [comment]
Another thing to keep in mind is when accessing data from the EventSetup the module takes a lock. The framework doesn't know about the lock so in multi-threading the framework can schedule multiple modules who all want the EventSetup lock so no progress gets made on some of the threads while waiting for the lock. (This is again why I'm working on running EventSetup modules concurrently and why we are adding 'consumes' to modules for EventSetup products.) The TimeReport does say how much time was spent waiting on the EventSetup lock.

**Comment by smorovic** [comment]
@fwyzard  good question. It was discussed in context of lumi-based conditions and Dave Dykstra mentioned it, but did not specify if there is different setting for IOVs and payloads.

**Comment by fwyzard** [comment]
For a single threaded job the time drops from `150 ± 20s (best: 138s)` to `63 ± 1s (best: 62s)`, with a gain of `-87 ± 20s (best: 76s)`.

For a multi threaded job the time drops from `107 ± 3s (best: 103s)` to `62 ± 2s (best: 60s)`, with a gain of `-45 ± 3s (best: 43s)`.

So, the startup time with the new approach is independent of using multiple threads, while the original approach had some benefit from it (as expected following the explanation by Chris).

In any case, the improvement is impressive :-)

**Comment by silviodonato** [comment]
+1
wow! Impressive improvement!

**Pull request merged**
