### PR TITLE
Pf cluster truth selector 90X

### PR DESCRIPTION
**Pull request by rafaellopesdesa**
Description:

   * This is a backport https://github.com/cms-sw/cmssw/pull/18106
   * Please, refer to the link above for more in-depth description of the PR. In few words, it is used for ECAL PF cluster studies and calibration.
   * Recalibration will be necessary following the modifications as a result of #18016 .

@perrotta @slava77 Related to the discussion we had in #18106 , I checked the location of the new dictionaries. It doesn't complain of this PR, but it does complain about:

https://github.com/cms-sw/cmssw/blame/CMSSW_9_0_X/SimTracker/TrackTriggerAssociation/src/classes.h

(and associated xml file) in 90X. I think it is related to #15949 . Should I do anything about it?

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
New producer used in some local test, with no effext on standard workflows
Changes are the same as in 91X version #18106

**Comment by perrozzi** [comment]
+1

**Comment by perrotta** [comment]
@davidlange6 : can this be merged as soon as a window for it open up? Thank you

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
