### PR TITLE
Backport to 10.3.X: add 2 production-like workflows for HI 2018

### PR DESCRIPTION
**Pull request by zhenhu**
backport of #25005 

Related to issue #24587 . Added two realistic chains 140.56 and 140.57.

Local test successful, but the input RAW datasets are not available on DAS yet.

### CODE REVIEW

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
please test workflow 140.56,140.57

Run 325174 is available on DAS now! I slightly updated the input dataset names. Now we can do the final test for these two workflows

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 the backport looks ok to me

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
