### PR TITLE
[`12.4_HLT_X`] HLT configurations for 2022 MC: remove menu 2022 V1.2 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menu for `CMSSW_12_4_HLT_X`.
This update is meant *exclusively* for the Summer2024 production of Run 3 MC. 

**This PR is NOT a backport**.

This PR is a follow-up to https://github.com/cms-sw/cmssw/pull/45939.
The goal of this PR is to remove the frozen menu 2022 V1.2 **only** from `CMSSW_12_4_HLT_X`  (which is the branch in which CMS targets to run the HLT step of the `Run3Summer2024` MC production). 
As it was agreed to use the frozen menu V1.5 for that (that was proposed in https://github.com/cms-sw/cmssw/pull/45939),  the earlier version V1.2 (for 2022 pre-EE era) will not be needed in this particular branch, thus it is removed to avoid possible confusions.
In order to remove the menu from the release and avoid massive relval failures, jointly with the removal commit 72a3bd0149a2dd256c21aa23bc2b34a843be1a36 there is an update of the GlobalTags in `autoCond.py` (commit adc04b6706bd4c41c81d477f1abf257afd1e695a) for the following keys:

   * `run3_hlt_relval` : `124X_dataRun3_HLT_relval_v9` → `124X_dataRun3_HLT_relval_v10` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_relval_v10/124X_dataRun3_HLT_relval_v9))
   *  `run3_data_relval` : `124X_dataRun3_relval_v13`  →  `124X_dataRun3_relval_v14` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_relval_v13/124X_dataRun3_relval_v14))
   * `phase1_2022_realistic` : `124X_mcRun3_2022_realistic_v12` → `124X_mcRun3_2022_realistic_v13` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_v12/124X_mcRun3_2022_realistic_v13))
   * `phase1_2023_realistic` : `124X_mcRun3_2023_realistic_v13` →  `124X_mcRun3_2023_realistic_v14` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2023_realistic_v14/124X_mcRun3_2023_realistic_v13))
   *  `phase1_2024_realistic` : `124X_mcRun3_2024_realistic_v13` → `124X_mcRun3_2024_realistic_v14` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2024_realistic_v13/124X_mcRun3_2024_realistic_v14))
   *  `phase1_2022_realistic_postEE` : `124X_mcRun3_2022_realistic_postEE_v1` → `124X_mcRun3_2022_realistic_postEE_v3` ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_postEE_v1/124X_mcRun3_2022_realistic_postEE_v3))
   
The first five of them contain the L1T menu tag `L1Menu_Collisions2022_v1_2_0_xml` (which is incompatible with the menu 2022 V1.5 that we are targeting to use for tests), while the last is an update requested by AlCa.
The exact content of the MC GT is still being discussed in this [cmsTalk thread](https://cms-talk.web.cern.ch/t/gt-for-the-hlt-step-of-the-2022-re-mc-production/48005/1), but these are intermediate GlobalTags for these keys that contain instead `L1Menu_Collisions2022_v1_3_0-d1_xml` (compatible with menu V1.5) such that we could (at least techincally) remove V1.2 from this branch.

#### PR validation:

I performed the following tests:

   * `addOnTests.py` runs fine.
   * `runTheMatrix.py -l limited --ibeos` 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
>  I am opening this PR in "Draft mode" because the update of autoCond.py is not complete, the 2023 relvals have the same issue:

Incidentally, I checked with [this script](https://gist.github.com/mmusich/fc8e5dea7e2c07151e4d0bc4b8fa5abb) which are the GTs in autoCond that still contain the L1T menu `L1Menu_Collisions2022_v1_2_0_xml` and here they are:

```
key: run3_data_relval : GlobalTag: 124X_dataRun3_relval_v13 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2022_design : GlobalTag: 124X_mcRun3_2022_design_v7 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2022_cosmics : GlobalTag: 124X_mcRun3_2022cosmics_realistic_deco_v13 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2022_cosmics_design : GlobalTag: 124X_mcRun3_2022cosmics_design_deco_v7 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2022_realistic_hi : GlobalTag: 124X_mcRun3_2022_realistic_HI_v12 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2023_realistic : GlobalTag: 124X_mcRun3_2023_realistic_v13 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase1_2024_realistic : GlobalTag: 124X_mcRun3_2024_realistic_v13 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: phase2_realistic : GlobalTag: 124X_mcRun4_realistic_v8 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: upgrade2021 : GlobalTag: 124X_mcRun3_2022_design_v7 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: upgrade2022 : GlobalTag: 124X_mcRun3_2022_design_v7 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
key: upgradePLS3 : GlobalTag: 124X_mcRun4_realistic_v8 | Record: L1TUtmTriggerMenuRcd, Label: -, Tag: L1Menu_Collisions2022_v1_2_0_xml
```

I would still at least update the keys `run3_data_relval` , `phase1_2023_realistic` and `phase1_2024_realistic`.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by perrotta** [comment]
+alca
- For AlCa mostly L1T menus updated in the GT to be compatible with the HLT menus 2022 V1.4 and 2022 V1.5

**Pull request merged**
