### PR TITLE
Move Phase2 HLT to ticl_v4 [13_1_X]

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Backport of  #42759

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42759

**Comment by jfernan2** [comment]
please test

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/42759
   * needed for the coming HLT Upgrade Annual Review,

**Comment by srimanob** [comment]
+Upgrade

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
