### PR TITLE
Phas2-sim86 Add MTD in the list of tracking type detector

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add MTD in the list of tracking type detector and add regions of moderator in this part

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

@bsunanda , I am not sure, that 0.01 mm cut is needed for this detector but this can be address later.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@civanch the ETL active module is 50 microns thick, that is the reason why I have reduced the cut when I have introduced back last year the new geometry. @bsunanda as far as I can see inside the MTD configuration the only difference is the addition of ```CALOECTSFront``` to the FastTimeRegion. What is the final purpose of this PR? Adding primaries and their decay products inside the MTD volume as ```SimTracks```?

**Comment by bsunanda** [comment]
@fabiocos @civanch Yes it will be nice that MTD is treated as an extension of tracker in view of MC truth information. This is the reason for the changes in StackingAction. It will be good to include the surrounding volume of ETL which consists of its thermal screen and neutron absorber in it as well. That is why the prodcuts xml file is changed and may be included in the next revision of geometry. I have in mind for D83 already. Do you have any idea when the next version of MTD geometry is expected?

**Comment by fabiocos** [comment]
@bsunanda with @martatornago we are reviewing the internal structure of ETL according to the most recent drawings, this will mostly affect the passive structure. But as it is an internal structure update, I believe it can be decoupled from possible other surrounding developments, if they are needed on a very short time scale.

**Comment by civanch** [comment]
Hi all,

I think it is correct to have the same approach in MTD as in tracker. In Tracker volumes are assigned to sensitive or to passive regions, MC truth is treated in both cases in the same way, cuts are different, in general, we have a flexibility to perform stepping/stacking/tracking action depending of in what G4Region a concrete step is done. In this sense, all volumes of a sub-detector should belong to one of these logical G4Regions for the sub-detector. 

Note, that G4Region is a logical sum of volumes, they do not necessary contact to each other. Addition of an extra region increase as memory and CPU for Geant4, so there is no sense creating extra region if cuts, limits, and user actions for them are the same. More optimal would be an addition of extra root logical volume to the already existing region.

**Pull request merged**
