### PR TITLE
Remove PixelTracksForL3Isolation configurations and IsolationRegionAroundL3Muon as obsolete

### PR DESCRIPTION
**Pull request by makortel**
While migrating `PixelTrackProducer` to the new seeding framework (from #16635), I encountered `*TracksForL3Isolation_cf*.py` set of configuration files and `IsolationRegionAroundL3Muon` `TrackingRegionProducer` that seem to be currently unused. ~~I'm asking if they are obsolete and can be removed, or still need to be maintained? (I'm more interested in the configs than the region producer).~~ The files were confirmed to be obsolete (see message below https://github.com/cms-sw/cmssw/pull/16863#issuecomment-265126046).

The commit shows the exact set of files.

Tested in CMSSW_9_0_X_2016-12-02-1100, no changes expected.

@slava77 @cvuosalo @rovere @VinInn @mtosi

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@jhgoh, @calderona, @HuguesBrun, @battibass please confirm that it's OK to remove these muon HLT modules

**Comment by HuguesBrun** [comment]
Hello @slava77 , 
After double check with the muon HLT conveners (@sarafiorendi and @BenjaminRS) we confirm that this code is not used anymore in muon reconstruction at HLT. It was used in run 1 but we switched to the regional iterative tracking so we do not see any reason for maintaining this piece of code

**Comment by makortel** [comment]
@HuguesBrun @sarafiorendi @BenjaminRS Thanks for the confirmation, I'll modify the PR title and description accordingly.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16863 de47aa4
- removal of obsolete code (not present in tested workflows)
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
