### PR TITLE
Add differential pulls, and resolutions+pulls for PV to vertex validation

### PR DESCRIPTION
**Pull request by makortel**
This PR updates the vertex validation in the following way
- Adjust "merge rate vs. closest vertex in z" x axis range to have uniform bin width when drawn with logarithmic x axis, and extend the minimum to 1e-4 cm
- Add pulls vs. number of tracks, PU, z, and sum(pT)
- Add resolution and pull plots for the PV
  * only for events where the reco PV is correctly identified
  * regardless if the PV is a merged vertex or not (to remind, for all vertices the plots are separate for non-merged and merged vertices)

Tested in 9_0_0_pre4, in addition of added histograms expecting changes in the merge rate vs. closest vertex in z histogram.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by ebrondol** [comment]
Thanks @makortel ! 
Is it going to also "solve" what we discussed about the x min of merged vtx for Phase2, right?

**Comment by makortel** [comment]
@ebrondol 
> Is it going to also "solve" what we discussed about the x min of merged vtx for Phase2, right?

Yes (this is the first bullet of the description).

**Comment by ebrondol** [comment]
Exactly, great.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
