### PR TITLE
[81X] Geometry independent SiPixelAli PCL (backport of #16749)

### PR DESCRIPTION
**Pull request by ghellwig**
backport of #16749

- replace hard-coded labels with automatically deduced labels, based on the used tracker geometry
- move MillePede-related part from PCLTrackerAlProducer to MillePedeAlignmentAlgorithm
  --> step towards unification of PCLTrackerAlProducer and AlignmentProducer

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
```
%MSG-e  ConditionDBWriter::setTime(): PoolDBOutputService is not available...cannot set current time:  SiStripGainFromCalibTree:ALCARECOSiStripCalib 24-Nov-2016 14:09:19 CET  Run: 165121 Event: 23634374

%MSG
%MSG-e  ConditionDBWriter::setTime(): PoolDBOutputService is not available...cannot set current time:  SiStripGainFromCalibTree:ALCARECOSiStripCalibAfterAbortGap  24-Nov-2016 14:09:19 CET Run: 165121 Event: 23634374
```
I would say this is unrelated to my PR. This error is issued here:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CommonTools/ConditionDBWriter/interface/ConditionDBWriter.h#L333-L344

In any case, it looks a bit weird. @Dr15Jones, do you have an idea why this service might be not available?

**Comment by Dr15Jones** [comment]
I'm afraid the `PoolDBOutputService` is not something managed by the framework, but instead by the DB group. @ggovi 
As a first guess, I'd say the configuration is missing a required Service definition.

**Comment by ghellwig** [comment]
> As a first guess, I'd say the configuration is missing a required Service definition.
This is where I know this message from, too.
However, nothing related to `PoolDBOutputService` has been changed by this PR, i.e. it must be a long standing problem which does not happen everytime the workflow is run.

**Comment by mmusich** [comment]
>  it must be a long standing problem which does not happen everytime the workflow is run.
it has never showed before as far as I can recall, also the very same workflow runs on a daily basis in PCL. (notice that 90X version of this PR https://github.com/cms-sw/cmssw/pull/16749 just run fine)

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
@mmusich just for the record, the 90X PR has the very same messages in it's [output](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16749/16578/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log):
```
%MSG-e  ConditionDBWriter::setTime(): PoolDBOutputService is not available...cannot set current time:  SiStripGainFromCalibTree:ALCARECOSiStripCalibAfterAbortGap  24-Nov-2016 15:22:41 CET Run: 165121 Event: 23634374

%MSG
%MSG-e  ConditionDBWriter::setTime(): PoolDBOutputService is not available...cannot set current time:  SiStripGainFromCalibTree:ALCARECOSiStripCalib 24-Nov-2016 15:22:41 CET  Run: 165121 Event: 23634374
```

This leads to the question, why it was considered as failed here and not in the other case?

**Comment by mmusich** [comment]
@ghellwig it's the case in all recent PR tests (i.e. same message, but no failure).

**Comment by mmusich** [comment]
so... we spent some time with @diguida to understand the issue here:

First, the failure in the relval seems unrelated to the message of being unable to set the time. The issue with the `PoolDBOutputService` is indeed due to the fact that the service is not declared in the[ step3 configuration](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16750/16579/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_ALCA.py) simply because it is not supposed to be.
Unfortunately the same module `SiStripGainFromCalibTree` is lies in the path both at step3 (via `process.ALCARECOStreamPromptCalibProdSiStripGains` and in the subsequent `alcaharvest` step via `process.ALCAHARVESTSiStripGainsAfterAbortGap`.
In the `alcaharvest` the service[ is in the config](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16740/16574/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step6_ALCAHARVEST.py) but not in step3.
The complication stems by the fact that `SiStripGainFromCalibTree` inherits from `ConditionDBWriter` that resets the time at each event in the [analyze method](https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/CommonTools/ConditionDBWriter/interface/ConditionDBWriter.h#L233-L240) even when it is called with `doStoreOnDB` parameter set to false https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdSiStripGainsAfterAbortGap_cff.py#L95

**Comment by ghellwig** [comment]
@smuzaffar do we understand why the test are  marked as failure?
I do not see anything else except the items discussed above, which are apparently not the reason.

**Comment by smuzaffar** [comment]
@ghellwig , no idea. All I know is that the step3 exited with non-zero code so that is why it is marked as failed :-)
While comparing the out of it with the one in IB, I see in IBs we have something like
```
Packages accessing DQM:
  AlCaReco: 90210
We have 86845 TH1F objects
We have 0 TH1S objects
We have 0 TH1D objects
We have 375 TH2F objects
We have 0 TH2S objects
We have 0 TH2D objects
We have 0 TH3F objects
We have 415 TProfile objects
We have 70 TProfile2D objects
We have 2505 Double objects
We have 0 Int64 objects
We have 0 String objects
```
while in the PR every thing is 0. Is there any thing which looks some objects to be generated?

**Comment by ghellwig** [comment]
@smuzaffar hm, that's strange...
In the 90X version the output at the end is exactly the same, while it does not fail there.
That is, we have twice the same output, while it fails only in one case.
However, it looks like it should actually fail in both cases.

@mmusich since you looked already into the details, do you have an idea what could go wrong here?

**Comment by mmusich** [comment]
@smuzaffar, about:

> marked as failed :-)
While comparing the out of it with the one in IB, I see in IBs we have something like
>Packages accessing DQM:
  AlCaReco: 90210
We have 86845 TH1F objects
We have 0 TH1S objects
We have 0 TH1D objects
We have 375 TH2F objects
We have 0 TH2S objects
We have 0 TH2D objects
We have 0 TH3F objects
We have 415 TProfile objects
We have 70 TProfile2D objects
We have 2505 Double objects
We have 0 Int64 objects
We have 0 String objects

how many events are used to run the IB relvals? The difference in the number of DQM objects might be just that in PRs test a very limited number of events is used. 

Also how can we know that the exit code was non-zero? I don't see fatal exceptions in the log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16750/16592/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log

**Comment by mmusich** [comment]
@ghellwig I assume you tested it locally before submitting the PR, right?

**Comment by smuzaffar** [comment]
@mmusich , the exit codes can be found in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16750/16592/runTheMatrix-results/runall-report-step123-.log

and full runTheMatrix log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16750/16592/runTheMatrix-results/matrixTests.log

both IB and PR tests runs the same number of events and for this workflow it is 100.

**Comment by diguida** [comment]
@smuzaffar the error message in `runTheMatrix` log:

````
ERROR executing  cd 1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5; cmsDriver.py step3  --datatier ALCARECO --conditions auto:run1_data -s ALCA:SiStripCalZeroBias+TkAlMinBias+DtCalib+Hotline+LumiPixelsMinBias+PromptCalibProd+PromptCalibProdSiStrip+PromptCalibProdSiStripGains+PromptCalibProdSiStripGainsAfterAbortGap+PromptCalibProdSiPixelAli --eventcontent ALCARECO -n 100  --filein file:step2.root  --fileout file:step3.root  --suffix "-j JobReport3.xml "  > step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log  2>&1;  ret= 34304
````

The `step3` exits with code 34304

**Comment by diguida** [comment]
The `step3` job is aborted: the process gets a `SIGABRT` (signal 6).

````
34304 >> 8 = 134
134 - 128 = 6
````

**Comment by mmusich** [comment]
```
cmsrel CMSSW_8_1_X_2016-11-25-1100
cd CMSSW_8_1_X_2016-11-25-1100/src/
git cms-merge-topic 16750
scramv1 b -j 8
cmsenv
runTheMatrix.py -l 1001.0
```

on cmsdev03 returns as expected:

```
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED Step7-PASSED  - time date Fri Nov 25 16:19:10 2016-date Fri Nov 25 16:06:27 2016; exit: 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed
```

**Comment by ghellwig** [comment]
I just made exactly the same check (since I run the matrix in 810pre16 + my modifications).
Same results as for Marco and also this output at the end:
```
Packages accessing DQM:
We have 0 TH1F objects
We have 0 TH1S objects
We have 0 TH1D objects
We have 0 TH2F objects
We have 0 TH2S objects
We have 0 TH2D objects
We have 0 TH3F objects
We have 0 TProfile objects
We have 0 TProfile2D objects
We have 0 Double objects
We have 0 Int64 objects
We have 0 String objects
```

**Comment by davidlange6** [comment]
could you try running runTheMatrix.py with -t 4 in the options.

**Comment by smuzaffar** [comment]
@davidlange6 , ah that reminds me that PR tests are not run in threaded mode which IBs does

**Comment by davidlange6** [comment]
ok, so never mind my suggestion…

**Comment by smuzaffar** [comment]
@mmusich , can you try try by making sure that you can run cmsenv before running git cms-merge-topic? I tried your recipe (but moving the cmsenv in right place) and I do get step3 failed.

**Comment by mmusich** [comment]
@smuzaffar for my own education why should be cmsenv issued before merging the topic?

**Comment by ghellwig** [comment]
@smuzaffar this is what I did:
```
cmsrel CMSSW_8_1_X_2016-11-25-1100
cd CMSSW_8_1_X_2016-11-25-1100/src/
cmsenv
git cms-merge-topic 16750
scram b -j 4
voms-proxy-init -voms cms -rfc
time runTheMatrix.py -i all --what production -l 1001
```
resulting in no (detected) error

**Comment by smuzaffar** [comment]
@mmusich , git-cms-merge-topic uses $CMSSW_BASE env variable and checkouts code in that path. So if you have cmsenv in different dev A and then go to dev area B and run git-cms-merge-topic then it will be checking out code in dev area A

**Comment by mmusich** [comment]
@smuzaffar I've first run `CMSSW_8_1_X_2016-11-25-1100` out-of-the-box to check if there was any problem, so I had already set $CMSSW_BASE before merging the topic (in the same area). I don't see how this can make a difference (see also @ghellwig confirmation)

**Comment by smuzaffar** [comment]
@Dr15Jones , Looks like it has something to do with job reports. The tests run without --job-reports works while
```
runTheMatrix.py --job-reports  -i all -l 1001.0
```
fails.

**Comment by Dr15Jones** [comment]
@smuzaffar can you run the failing job in the debugger and find where the abort happens?
(It's a holiday in the US)

**Comment by smuzaffar** [comment]
I tried (3 times) but in gdb it did not fail. I am now running valgrind.

**Comment by smuzaffar** [comment]
valgrind shows this
```
Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning             16448               16448
Error                 126                 126
System                  3                   3
==2828== Invalid free() / delete / delete[] / realloc()
==2828==    at 0x4029134: operator delete(void*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2828==    by 0x3B1CAD88: std::vector<unsigned int, std::allocator<unsigned int> >::~vector() (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/external/fastjet-contrib/1.020/lib/libfastjetcontribfragile.so)
==2828==    by 0x3CEE035AE1: exit (in /lib64/libc-2.12.so)
==2828==    by 0x3CEE01ED23: (below main) (in /lib64/libc-2.12.so)
==2828==  Address 0x60aa9a60 is 0 bytes inside a block of size 16 free'd
==2828==    at 0x4029134: operator delete(void*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2828==    by 0x3B1CAD88: std::vector<unsigned int, std::allocator<unsigned int> >::~vector() (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/external/fastjet-contrib/1.020/lib/libfastjetcontribfragile.so)
==2828==    by 0x3CEE035AE1: exit (in /lib64/libc-2.12.so)
==2828==    by 0x3CEE01ED23: (below main) (in /lib64/libc-2.12.so)
==2828==  Block was alloc'd at
==2828==    at 0x4028108: operator new(unsigned long) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/external/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2828==    by 0x4C0776D: void std::vector<unsigned int, std::allocator<unsigned int> >::_M_emplace_back_aux<unsigned int>(unsigned int&&) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==2828==    by 0x3BFFDD6C: TrackerAlignmentLevelBuilder::buildPXBAlignmentLevels() (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libAlignmentTrackerAlignment.so)
==2828==    by 0x3BFFEA48: TrackerAlignmentLevelBuilder::build() (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libAlignmentTrackerAlignment.so)
==2828==    by 0x3C0028BD: AlignableTrackerBuilder::buildAlignableComposites() (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libAlignmentTrackerAlignment.so)
==2828==    by 0x3C00457A: AlignableTrackerBuilder::buildAlignables(AlignableTracker*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libAlignmentTrackerAlignment.so)
==2828==    by 0x3BFF4C98: AlignableTracker::AlignableTracker(TrackerGeometry const*, TrackerTopology const*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libAlignmentTrackerAlignment.so)
==2828==    by 0x3BEBC4D3: PCLTrackerAlProducer::createAlignables(TrackerTopology const*) (in /var/build/muz/pip/x/CMSSW_8_1_X_2016-11-25-1100/lib/slc6_amd64_gcc530/pluginAlignmentPCLTrackerAlignmentProducerPlugin.so)
==2828==    by 0x3BEC56D0: PCLTrackerAlProducer::initAlignmentAlgorithm(edm::EventSetup const&) (in /var/build/muz/pip/x/CMSSW_8_1_X_2016-11-25-1100/lib/slc6_amd64_gcc530/pluginAlignmentPCLTrackerAlignmentProducerPlugin.so)
==2828==    by 0x3BEC6C1E: PCLTrackerAlProducer::beginRun(edm::Run const&, edm::EventSetup const&) (in /var/build/muz/pip/x/CMSSW_8_1_X_2016-11-25-1100/lib/slc6_amd64_gcc530/pluginAlignmentPCLTrackerAlignmentProducerPlugin.so)
==2828==    by 0x4B441BA: edm::EDAnalyzer::doBeginRun(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
==2828==    by 0x4B729DF: edm::WorkerT<edm::EDAnalyzer>::implDoBegin(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/2016-48/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-23-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so)
```

**Comment by ghellwig** [comment]
@smuzaffar just for the record, when running in plain `CMSSW_8_1_X_2016-11-25-1100` I also get this:
```
Packages accessing DQM:
  AlCaReco: 90210
We have 86845 TH1F objects
We have 0 TH1S objects
We have 0 TH1D objects
We have 375 TH2F objects
We have 0 TH2S objects
We have 0 TH2D objects
We have 0 TH3F objects
We have 415 TProfile objects
We have 70 TProfile2D objects
We have 2505 Double objects
We have 0 Int64 objects
We have 0 String objects
```

Looks like my PR indeed changes behaviour there and the jop report just does not ignore the problem (at least not always...).

**Comment by ghellwig** [comment]
@smuzaffar alright, will check this further and put also the 90X on hold
thanks for your investigations.

**Comment by ghellwig** [comment]
hold

**Comment by ghellwig** [comment]
just one more comment: I got non-zero numbers when running this command
```
time runTheMatrix.py -i all --what production -l 1001 -t 4
```

**Comment by Dr15Jones** [comment]
This may not be related, but I found it while looking through the code based on Shahzad's valgrind report. The following is not thread safe

http://cmslxr.fnal.gov/source/Alignment/CommonAlignment/src/AlignableObjectId.cc#0217

**Comment by Dr15Jones** [comment]
Here is the thread unsafe global which is probably causing the crash at the end

http://cmslxr.fnal.gov/source/Alignment/TrackerAlignment/interface/TPBNameSpace.h#0027

the vector is begin filled here
http://cmslxr.fnal.gov/source/Alignment/TrackerAlignment/src/TrackerAlignmentLevelBuilder.cc#0200

This is a violation of CMS programming policy (code is only allowed to communicate via the Run/Lumi/Event and not through globals).

**Comment by Dr15Jones** [comment]
In addition, declaring a global in a header without using `extern` means the object is instantiated in every compilation unit that includes the header although only one symbol will be used in the program. However, this also means at the end of the program when the globals are being destroyed, the same one will be destroyed multiple times. This matches what valgrind is reporting.

**Comment by ghellwig** [comment]
@Dr15Jones Thank you for further checking this issue!
I agree that communication via globals has to be avoided. This should be rather easy to fix, I think because communication between modules is actually not intended here.
In fact, the problem seems to appear in this PR because two modules are using the same infrastructure (to build the AlignableTracker object), while previously it was used only in one place.
I'll try to come up with a solution this week.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
unhold

**Comment by mmusich** [comment]
+1

**Pull request closed without merging**
