### PR TITLE
TH1ClusterCharge and TH1ClusterStoNCorr plots per ring

### PR DESCRIPTION
**Pull request by idebruyn**

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by boudoul** [comment]
hi @dmitrijus , I see that the corresponding 81X version is merged (se PR #14569 ) , can we proceed with this one now ? Thanks

**Comment by boudoul** [comment]
hi @dmitrijus , could you please proceed with this PR?

**Comment by boudoul** [comment]
ping @dmitrijus

**Comment by dmitrijus** [comment]
+1
of course!

**Pull request merged**
