### PR TITLE
Backporting of BSOnlineProducers for Run3

### PR DESCRIPTION
**Pull request by gennai**
have modified the Online BS Producers to take the values from the transient record produced in the related ESProducer.
This is intended for HLT and express stream reconstruction for Run3. There is a new parameter that if set to False, it would revert back to Run2 code.

A second PR on a ERA modifier configuration will follow.

PR validation:

I have checked the behavior of the code using the test_scalers.py script modified accordingly

This is the backporting of 34295 and should be included in the release in use for CRUZET

### CODE REVIEW

**Comment by gennai** [comment]
@mtosi @mmusich @francescobrivio you may want to follow this PR as well

**Comment by perrotta** [comment]
backport of #34295

**Comment by mmusich** [comment]
urgent

it would be great to exercise this in CRUZET

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
@gennai @mmusich  How urgent is this PR for CRUZET? 

Notice the original plan is :  for CRUZET (July 12 - Aug 14)
   - 29 June : PRs ready in 12_0_X   (i.e. #34295)
   - 6 July : PRs merged in 11_3_X   (i.e. this PR)

cc @amassiro @boudoul

**Comment by gennai** [comment]
Hi,
well it is needed for the express workflow. I would let @mmusich comment further

**Comment by mmusich** [comment]
@qliphy, technically it should be ~ transparent to reconstruction for cosmics, but it would a good opportunity to commission the changes that are mandatory for collision data-taking in 2022.

**Comment by francescobrivio** [comment]
+alca

**Comment by jpata** [comment]
+reconstruction
- direct backport of #34295, needed for CRUZET
- off by default, so there should be no issues wrt. the no change rule

**Comment by qliphy** [comment]
+1

**Pull request merged**
