### PR TITLE
BMTF fixes for the AlgoSelector and the Unpacker

### PR DESCRIPTION
**Pull request by panoskatsoulis**
Includes 2 fixes:
a) Fixes the L1TBMTFAlgoSelector SEGFAULT issue when there is no MP7 header to read by introducing a default configuration for the DQM Fix logic.
b) Fixes issue that lies in one BMTFUnpacker Constructor and leaves the 'isKalman' boolean undefined.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
privately tested to fix the crashing workflows

**Comment by panoskatsoulis** [comment]
@fabiocos 
Sorry I can understand the last message.
Is it fixed or not?

**Comment by fabiocos** [comment]
@panoskatsoulis the problem is fixed, as you may see in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24652/30638/runTheMatrix-results/ the crashing workflows completed smoothly

**Comment by fabiocos** [comment]
@thomreis @andrius-k this PR looks to fix the recent crashes we have observed in the IB, see the tests. Could you please comment or sign it so as we fix this issue?

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
