### PR TITLE
Migration of modules used in PbPb HLT to do ZeroSuppression to "stream" modules in 80X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of modules used in PbPb HLT to do ZeroSuppression to stream modules in 80X
Forward port of #12419

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@emeschi, @mommsen
please sign this PR.
Thanks!

**Comment by Martin-Grunewald** [comment]
@cvuosalo, @slava77
please sign this PR.
Thanks!

**Comment by cvuosalo** [comment]
+1

For #13053 ae0622aff7ae3cb283081e1d707fc0b28f16b88e

Migrating modules that do PbPb HLT ZeroSuppression to support thread safety. There should be no change in monitored quantities. #12415 is the 75X version of this PR, and it was already merged last year.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13053/10718/summary.html) against baseline CMSSW_8_0_X_2016-01-24-2300 show no significant differences, as expected.

**Comment by mommsen** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
