### PR TITLE
Run3-sim112 Take care of deprecated code in FastSimulation/ForwardDetectors

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of deprecated code in FastSimulation/ForwardDetectors

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@sbein Please approve

**Comment by civanch** [comment]
+1

this Castor FastSim - safe to merge

**Comment by sbein** [comment]
+1

**Comment by qliphy** [comment]
please test
just to refresh

**Comment by perrotta** [comment]
+1

**Pull request merged**
