### PR TITLE
[BeamSpot]: update script to condDB v2 commands

### PR DESCRIPTION
**Pull request by rmanzoni**
Make script used to produce beam spot payloads condDB v2 compliant.
This should have gone into CMSSW before, so far we've patched the command by hand at each iteration.

@sarafiorendi 
@mmusich 
@franzoni

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15844 adc7b1a
- technical change in line with the description. 
- jenkins tests pass. The modified script is not a part of workflows used in jenkins.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
