### PR TITLE
fix bug about lambda error + small cleanup

### PR DESCRIPTION
**Pull request by VinInn**
it may affect JetCore for largish eta
http://innocent.home.cern.ch/innocent/RelVal/qcd35_fixDL/plots_building_jetCoreRegionalStep/effandfake1.pdf

### CODE REVIEW

**Comment by VinInn** [comment]
@arizzi

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
type bug-fix

**Comment by perrotta** [comment]
Tiny regression in all tracking related quantities, as expected from the description of this PR: this has been verified in some high pt QCD and PU25 TTbar sample. A few exemple follow:

- Theta of gsf electrons in 400 events produced with wf 10059 (high pt QCD):
all_testpr18896vsorig_qcd13tevpt3ts3t5in2017wf10059p0c_recogsftracks_electrongsftracks__reco_obj_theta

- Eta of general tracks in 400 events produced with wf 10059 (high pt QCD):
all_testpr18896vsorig_qcd13tevpt3ts3t5in2017wf10059p0c_recotracks_generaltracks__reco_obj_eta

- nSecondaryTracks in recoPFDisplacedVertex in TTbarPUwf25202
all_testpr18896vsorig_ttbarpuwf25202p0c_recopfdisplacedvertexs_particleflowdisplacedvertex__reco_obj_nsecondarytracks

and so on so forth...

**Comment by perrotta** [comment]
+1
After visual inspection, https://github.com/cms-sw/cmssw/pull/18896#issue-230697537 and https://github.com/cms-sw/cmssw/pull/18896#issuecomment-304276120

**Comment by slava77** [comment]
On 5/26/17 5:57 AM, perrotta wrote:
> with wf 10059 (high pt QCD):

this wf is not practical for tests of high-pt jet behavior for higher eta.
Changes in this PR are apparently relevant in regions where lambda
differs from tanLambda or eta (eta>~2).
3TeV (ptHat) dijet sample has only very central jets as seen from the
posted plots.

**Comment by perrotta** [comment]
Ok, but there is anyhow some stat in the forward region in that high pt QCD sample as well, and nothing disrupting shows up there, thus confirming what was observed in the specific plot appended to the description of this PR

Other plots from the 25PU TTbar sample (200 events) do not show any specific accumulation of the tiny regressions in the forward region, though. For example:

- eta of ak4 PF jets
all_testpr18896vsorig_ttbarpuwf25202p0c_recopfjets_pfjetsei__reco_obj_eta

- eta of conversion step tracks
image

- eta of general tracks
image

**Comment by slava77** [comment]
On 5/26/17 7:06 AM, perrotta wrote:
> Ok, but there is anyhow some stat in the forward region in that high pt
> QCD sample as well, and nothing disrupting shows up there, thus
> confirming what was observed in the specific plot appended to the
> description of this PR
> 

forward region has only underlying event-like low-pt tracks/jets in that
region.
If there may be changes in jetCore (jet pt>100 is required to be present
for this iteration), it can be checked only with high-pt jets in that area.
the tests with 10059 do not test it; the pileup ttbar likely doesn't
cover that either.

**Comment by perrotta** [comment]
There are 74 jets with pt>100 and |eta|>1 in the QCD sample, and 73 jets as such in the TTbar sample.
Not such a big stat, but not even fully negligible,..

**Comment by slava77** [comment]
On 5/26/17 8:24 AM, perrotta wrote:
> There are 74 jets with pt>100 and |eta|>1 in the QCD sample, and 73 jets
> as such in the TTbar sample.
> Not such a big stat, but not even fully negligible,..

what about |eta|>2 ?
eta ~1 is still a region with tan(x)~x~eta

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@VinInn 
please clarify which sample you used for the QCD tests in the MTV provided with this PR.
Thank you.

**Comment by VinInn** [comment]
the plot refers to 3TeV jets. I also looked to ttbar and 600GeV jets.
One point is that whatever the result one can claim that is intended: jet core is supposed to improve tracking in the core of the jet, not in its periphery.... (and in any case no one has ever tuned (even looked at) jetCore at eta=2 at best of my knowledge)

**Pull request merged**
