### PR TITLE
[GENERATORS] Update all the scripts to use python3

### PR DESCRIPTION
**Pull request by smuzaffar**
Cleanup python2 usage

### CODE REVIEW

**Comment by Saptaparna** [comment]
@Dominic-Stafford: does this affect anything significantly regarding Herwig? 
@SiewYan: Do we need to implement further checks for python 3?   

Thanks!

**Comment by SiewYan** [comment]
@Saptaparna  I don't think so for now, it is included in the unit test.

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
@Saptaparna , there is no python error/warning found in the tests [*],[**]. 

[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-479fd8/22755/clang-logs/
[**] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-479fd8/22755/build-logs/

**Comment by smuzaffar** [comment]
@SiewYan , please check the unit tests e.g. 

- cmsLHEtoEOSManager.py: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-479fd8/22755/unitTests/src/GeneratorInterface/LHEInterface/test/test_cmsLHEtoEOSManager/testing.log 
- https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-479fd8/22755/unitTests/src/GeneratorInterface/LHEInterface/test/testGeneratorInterfaceLHEInterface_TP/testing.log

is there any unit test for testing `GeneratorInterface/LHEInterface/scripts/mergeLHE.py` and `GeneratorInterface/Herwig7Interface/scripts/parallelization.py`

**Comment by Dominic-Stafford** [comment]
> @Dominic-Stafford: does this affect anything significantly regarding Herwig?

No, the only change on the Herwig side is to the parallelisation.py script, which isn't currently used for anything as far as I know.

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
@smuzaffar thanks for catching this error, apparently there is a bug on the unitest code, the file format is different, cmsLHEtoEOSManager.py.

I will address this later this week.

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 can you please review this? I think this looks good and does not break any thing new :-)

**Comment by SiewYan** [comment]
@smuzaffar , sure no problem! i will work on this tiny issue from another PR. Thanks for pointing out though.

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
