### PR TITLE
Phase2-hgx222 Correct some of the cfg files and make file naming more homogeneous

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the cfg files so that the dump geometries are visible in firework. Also try to have similar file names of the dumped files

#### PR validation:

Tested privately using the cfg files in the test area

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this looks quite technical and ok to me, I see you already approved it at the first round, so I will integrated it

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
