### PR TITLE
Removed operator= from Phase2L1CaloJetEmulator helpers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The default generated operator does the exact same work.

#### PR validation:

Code compiles without warnings in CMSSW_14_0_DEVEL_X_2023-12-19-1100.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
ping

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
