### PR TITLE
Restore CMS geometry overlap checks

### PR DESCRIPTION
**Pull request by civanch**
In this sub-library CMS custom geometry checks including overlap checks are performed. Code is cleaned up and the functionality restored for the newest Geant4. An example of alternative overlap check using only Geant4 tool is added. Now each test is a small python file which is using common part the same for all CMS tests. Old geometry configurations are removed.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@ianna , this PR is a simple one.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
