### PR TITLE
Backport of #6030. Add features offline validation for53 x

### PR DESCRIPTION
**Pull request by tlampen**
In offline validation: a bugfix and lots of improvements to automatize
plotting.

### CODE REVIEW

**Comment by mmusich** [comment]
@tlampen @hroskes, to ease the integration procedure in 53X, could you please merge the committs of PR #6587 #6475 #6459 and #6071 in a single PR? All the updates are in the same package. 
Thanks

**Comment by diguida** [comment]
+1
This is the last PR which was still missing according to the list prepared by @mmusich

**Comment by mmusich** [comment]
hold
@diguida, I think this was already adressed in #6459. @hroskes can you confirm?

**Comment by hroskes** [comment]
@mmusich @diguida yes, as you requested I combined #6587, #6475, and #6071 into #6459.

After #6459 was merged I closed #6475.  Apparently #6587 was merged anyway.  This is the last one remaining, and it's no longer necessary.

**Comment by mmusich** [comment]
@hroskes thanks for the prompt feedback! @tlampen can you close this one?

**Comment by diguida** [comment]
@mmusich @tlampen @hroskes I have just checked.
#6459 contains all the changes in this PR, the commits are rebased.

**Comment by diguida** [comment]
-1
superseded by #6459

**Pull request closed without merging**
