### PR TITLE
add unit test for correctionlib library

### PR DESCRIPTION
**Pull request by davidlange6**
as requested in https://github.com/cms-sw/cmsdist/pull/6659

### CODE REVIEW

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#6659

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6659

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy can we get this merged?
FYI @cms-sw/analysis-l2

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
