### PR TITLE
fix preexisting tracker alignment validation

### PR DESCRIPTION
**Pull request by hroskes**
backport of #22799

Fixing a stupid mistake.  The default behavior is setting this parameter to "true" which doesn't work with int.  I missed this one place in 297cb18bf0610f3184fb2ce9b4466b6ebddc6c05.

### CODE REVIEW

**Comment by arunhep** [comment]
@hroskes not sure if we will have new 10.0.X release

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
not sure if we will have new 10.0.X release, is this PR in 100X really needed?

**Comment by hroskes** [comment]
Hi @lpernie and @arunhep, it depends what you mean by "needed".  We came across this bug in validating CRUZET alignments, but if necessary we can just fix it privately, it doesn't have to be in a release.

**Comment by arunhep** [comment]
@hroskes since we dont expect new 10.0.X release so it would be good to close it

**Pull request closed without merging**
