### PR TITLE
extendedO2O

### PR DESCRIPTION
**Pull request by kkotov**
Backporting the L1T O2O that has been running for many months at p5 to the 8_0_x.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
@kkotov 
does this PR contain the same code currently running for the L1T O2O?

**Comment by kkotov** [comment]
@ggovi , it is not diff-identical (few comments + more advanced version of the L1TriggerKeyExt), but it is conceptually the same meaning that if you run the code from this branch, you'll get the right payload

**Comment by ggovi** [comment]
@kkotov 
Did you run some test against the prep db?

**Comment by ggovi** [comment]
+1
Basically trusting the above 'validation'...

**Comment by ggovi** [comment]
@smuzaffar 
Did I involuntarily trigger the test? Maybe the word in quote?

**Comment by smuzaffar** [comment]
@ggovi , no tests are triggered by either saying 
 - please test or 
 - if a category manager approves the PR by doing "+1" and tests were not yet ran

**Comment by smuzaffar** [comment]
by the way, in this case, as you have updated the PR https://github.com/cms-sw/cmssw/pull/15204/commits/979eff5ef9a00f5870fd953684ea9ec4206a7f3b and there were no tests ran after the update so first +1 should have triggered the tests.

**Comment by ggovi** [comment]
ah ok, that's the reason, thanks!

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
@kkotov @mulhearn 
we need this PR to be integrated today

**Comment by kkotov** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by kkotov** [comment]
Could anyone comment if I need to perform any other actions here? The compilation in 81x fails, not a big surprise though. This PR is meant only for 80x.

**Comment by ggovi** [comment]
Please recall that any change requested for 80X  needs to be a back-port of a change validated in 81X. So, please act accordingly (=provide a corresponding PR for 81X that works). Unless you have a special agreement with the Offline Coordinator...

**Comment by koskot77** [comment]
@ggovi The other PR #15243 (extendedO2Ofor81X branch) is porting the same changes to 81X. Is there a way to connect the two on github?

**Comment by ggovi** [comment]
you don't need to connect the two PRs... I guess you only need to follow up the signatures from your team. The one for 81X has not been approved.

**Comment by mmusich** [comment]
@smuzaffar, the situation here seems inconsistent to me. Why the PR is tests-approved but the check box claims a Clang error?

**Comment by koskot77** [comment]
Because for some reason the check on PR for 80x was also done on 81X where it predictably fails

**Comment by smuzaffar** [comment]
@mmusich , yes it looks wrong. Unfortunately the jenkins build logs are gone (so can not tell muh why it happened) but the build results for Clang looks good https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15204/14163/buildClang.log

**Comment by smuzaffar** [comment]
looks like Clang error URL points to #15189
something went wrong there, I am checking

**Comment by smuzaffar** [comment]
Looks like the information in status box is based on commit. As the tests ran for #15189 (which has the same commits https://github.com/cms-sw/cmssw/pull/15189/commits/979eff5ef9a00f5870fd953684ea9ec4206a7f3b failed so that is why Github also showed "Clang error" for this PR.

**Comment by kkotov** [comment]
@smuzaffar ok, since the #15189 is now closed, would it be sufficient just simply test this PR once again to get the final green light for the integration?

**Comment by smuzaffar** [comment]
yes @kkotov. Last tests ran 8 days ago  so better to rerun

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@kkotov compilation errors in the stat-box are gone. The only show-stopper for this to be merged is that we miss L1 signatures on the 81x equivalent Pull Request #15243 which still misses L1 signatures.

**Comment by rekovic** [comment]
@mmusich  Done.  #15243 signed.

**Comment by mmusich** [comment]
@rekovic thanks!

**Comment by franzoni** [comment]
hello @davidlange6 
would it be possible to have this PR merged, now that its counter part on 81x is merged #15243 ? 
AlCa/DB would like to have a 80x release by the end of this week containing it, in order to deploy on the production o2o during the MD (starting Aug 22nd)
Thanks and cheers,
@ggovi @franzoni

@mmusich

**Comment by davidlange6** [comment]
+1

**Pull request merged**
