### PR TITLE
CTPPS: miniAOD (second resubmission)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This is a continuation of #17424 after it has been reverted (#17630). It contains:
 * the same commits as #17424 
 * plus a mechanism to inhibit `CTPPSLocalTrackLiteProducer` if era `ctpps_2016` is not selected, as suggested in https://github.com/cms-sw/cmssw/pull/17424#issuecomment-282569060 .

`runTheMatrix -l limited` gave
 * `14 14 13 11 6 0 0 0 tests passed, 2 0 0 0 0 0 0 0 failed`
 * the two failures were `DAS_ERROR` in workflows 4.22 and 1001.0

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17650	fa8e156
- bug fix since earlier submission of https://github.com/cms-sw/cmssw/pull/17424	fc9b28c
: https://github.com/cms-sw/cmssw/compare/30888fe22098c9b910a0a2afb157d9b52644afa2...fa8e1562b81f54ce2be6d87b68ed2c6ae2292bfa to add configurable skip of execution in eras without CTPPS in order to not interfere with the miniAOD workflows there
- jenkins tests pass (the test used includes not the 4.53 workflow which was previously failing and not tested at submission)

**Comment by jan-kaspar** [comment]
This PR is deprecated by already merged #17701.

**Comment by slava77** [comment]
@jan-kaspar 
should I take it that you do not want this change to be in release 900?
The #17701 is 91X.

**Comment by jan-kaspar** [comment]
> should I take it that you do not want this change to be in release 900?

We need this change for:
 * 2017 reconstruction: in my understanding 9_1_X should be sufficient - or am I wrong?
 * 2016 legacy re-reco: a back-port will be issued soon by Laurent

**Comment by slava77** [comment]
On 3/7/17 7:30 AM, jan-kaspar wrote:
>     should I take it that you do not want this change to be in release 900?
> 
> We need this change for:
> 
>   * 2017 reconstruction: in my understanding 9_1_X should be sufficient
>     - or am I wrong?
>   * 2016 legacy re-reco: a back-port will be issued soon by Laurent

OK, this is fine

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
