### PR TITLE
EventFilter/Utilities: potential bug -- beginRun and beginStreams could be run

### PR DESCRIPTION
**Pull request by gartung**
because the function parameters have been changed to match
the base class functions to remove clang warning hides overloaded
virtual. Also clanged class to struct in forward declarations to
match previous declarations

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #17024 06f3538e14b25e5e6169ae48d450e4dbc6f3762d

Fixing a Clang warning about overloading in EventFilter/Utilities so derived-class methods are actually called. The affected code is only used by `test` programs. There should be no change in standard workflows.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-16-1100 show no significant differences, as expected.

**Comment by slava77** [comment]
@gartung 
there are merge conflicts

@davidlange6 were there any concerns to merge this in 2016?

**Comment by gartung** [comment]
It looks like the initialization of the histograms was moved to the constructor instead of beginStream. I will merge and resubmit.

**Pull request closed without merging**
