### PR TITLE
adding Herwig7 workflows to release validation

### PR DESCRIPTION
**Pull request by theofil**
#### PR description:

Adding Herwig 7 workflows in release validation. Provided this PR is approved, it needs to be back ported also to 106X

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by theofil** [comment]
sorry for the double commit, I had to update the PR, to move the Herwig workflows in the appropriate place under the LHE Generation + Hadronization block,

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
@theofil 
The workflow 537 runs fine, but 538 has an issue. Could you please check?

Here is the report:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46213e/16766/runTheMatrix-results/538.0_DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7+DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7+HARVESTGEN/step1_DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7+DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7+HARVESTGEN.log

Thanks.

**Comment by theofil** [comment]
@srimanob 
still haven't figure out why it doesn't work, it used to work but not it doesn't also in my local configuration.

one question, if I would like to emulate the exact command issued by the relval, how should I write it ? I start by /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/34463/16766/install.sh and then what is the appropriate cmsDriver syntax to run the 538 workflow, as the test parameters:
   workflows = 537, 538
is doing ?

**Comment by davidlange6** [comment]
runTheMatrix.py -l 537,538 -n 2

**Comment by theofil** [comment]
@srimanob 

after talking also with @Dominic-Stafford we believe that the crash is not related to Herwig per se, but is related to a change regarding the number of threads (concurrent) mode. There is a warning produced while invoking 

`cmsDriver.py Configuration/Generator/python/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cff.py --conditions auto:run2_mc -s LHE,GEN --datatier LHE,GEN -n 10 --eventcontent LHE,RAWSIM --no_exec`
 

```
/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_0_pre4/python/Configuration/Applications/ConfigBuilder.py:2266: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if self._options.nThreads != 1

```

regardless if the warning is the sole responsible for the crash, the bottomline is that the produced *cfg.py, contains inside 

`generateConcurrently = cms.untracked.bool(True)`

which is not going to work with Herwig. 

For reference, the working cfg 


https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Herwig7Interface/test/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cfg.py

and the one produced by the current version of the **ConfigBuilder.py**

http://theofil.web.cern.ch/theofil/images/H7cfgs/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cff_py_LHE_GEN.py

which has the `generateConcurrently = cms.untracked.bool(True)` inside the  `process.externalLHEProducer` block

**Comment by srimanob** [comment]
Hi @theofil 

The warning is fine. We have a PR to fix it already, but it will not affect the test. In addition, the short PR test runs with 1 core.

To answer about `generateConcurrently`, it is not that simple because
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/DYToLL01234Jets_5FS_TuneCH3_13TeV_madgraphMLM_herwig7_cff.py
calls
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py
where `generatedConcurrently` is set to true.

**Comment by qliphy** [comment]
You can refer to what was done in https://github.com/cms-sw/cmssw/pull/33985 for https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/TTbar_Pow_LHE_13TeV_cff.py  
and update accordingly
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py

**Comment by theofil** [comment]
@qliphy thanks for the resolution, I updated the files accordingly. I also update the NLO version with FxFx, of the Herwig hadronizer to be informed of the concurrent mode and the need for merging the output in the end of the processing

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

Adding new Herwig7 workflows. Short matrix with new additional workflows run fine.

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
(GEN(Alexander) has informed us that he is on vacation for 2 weeks)

**Comment by qliphy** [comment]
merge

**Pull request merged**
