### PR TITLE
fix L1TGlobalPrescalesVetosESProducer

### PR DESCRIPTION
**Pull request by fwyzard**
Fix a bug when less than 512 prescales are given in the XML file.
Before, the prescales for some of the triggers without an entry would not be initalised, and would be set to random values.

clean up
  - fill whole vectors instead of individual values
  - issue a LogError if a non-empty filename is not found
  - clang-tidy 3.8.0 modernize checks

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@rekovic can you sing this ASAP ?
this breaks all trigger studies using the current recipe to load prescales from an XML file

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
