### PR TITLE
Improved performance of c-hadron origin identification

### PR DESCRIPTION
**Pull request by bartosik-hep**
C-hadrons performance as for b hadrons.
Example configuration extended by test of c harons.
Simpler configuration of the JetFlavour tool.

### CODE REVIEW

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , CMSSW_7_3_X is disabled for IBs. That is why tests are not running for this PR. Should we enable 73X if we want this PR in 73X?

**Comment by slava77** [comment]
@bartosik-desy 
73X is abandoned (the last release was built in May and there will not be any more).
You should resubmit this PR to 74X (and also 75X, 76X)

**Comment by bartonaz** [comment]
Ok, thanks.
It was already done, and corresponding PRs are merged.

**Comment by gudrutis** [comment]
Hi,
This PR is almost 4 years old. Do we still care about it or can we close it?

**Comment by bartosik-hep** [comment]
@gudrutis This particular PR can be closed. The relevant changes have already been included in newer releases.

**Comment by smuzaffar** [comment]
please close

**Pull request closed without merging**
