### PR TITLE
modifications for SiStrip online DQM config for HI run

### PR DESCRIPTION
**Pull request by threus**
Modifications for SiStrip online DQM config for HI run.
Supersedes #12506

Thanks to  @BetterWang for help.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please submit to 76 and 80 as well.
thanks,
F.

**Comment by threus** [comment]
@deguio: 76x/80x PRs submitted

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
merge

80X version #12533  in merged already

**Pull request merged**
