### PR TITLE
[DB] Fixes needed for GCC 10

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Fixes needed for GCC 10.
1. `bin >= 0` is always true as `bin` is of type `size_t (unsigned)`
2. For `index > (sz - 1)` , GCC 10 complains 
```
error: comparison of unsigned expression in '< 0' is always false
```

#### PR validation:

Local build with GCC 10 and normal IB look good

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi , can you please look in to this?
@silviodonato , this is techinical fix without change in any behaviour so can be merged

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@smuzaffar thanks!

**Comment by silviodonato** [comment]
+1

**Pull request merged**
