### PR TITLE
Run3-gex180X Modify the 2024 scenarios for the corrected positions of the GE21 detectors

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the 2024 scenarios for the corrected positions of the GE21 detectors

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
FYI @cms-sw/alca-l2 @cms-sw/pdmv-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
