### PR TITLE
Realistic vertex smearing for 2015 PbPb MC (75X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
75X version of #15224

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by mandrenguyen** [comment]
@civanch I that a transient error related to xrootd or a filesystem problem?  When I execute runTheMatrix.py -l 25202.0  I see that it's failing trying to open the pileup_input dataset.

**Comment by civanch** [comment]
Problem is not related to this PR, pileup file is not available.

**Comment by mmusich** [comment]
@mandrenguyen @jrcastle @davidlange6 : 
I have the updated Global Tag with the requested Beamspot payload in this [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2538.html), but to make the change meaningful (i.e. Vtx Smearing parameters + Reco BS in GT updated together), I need the new scenario in release, therefore I have just opened this one: #15457

**Comment by davidlange6** [comment]
merged as part of #15457

**Pull request closed without merging**
