### PR TITLE
Expanding HLT Configuration Proxy Support and Adding Tunnel Support : 12_5

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This expands proxy and tunneling support for confdb scripts for 12_5

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/40454

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40454

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

Verbatim backport of https://github.com/cms-sw/cmssw/pull/40454. Update of HLT utilities across release cycles still used for Run-3 trigger studies.

(No risk for IBs, as these utilities are not tested centrally.)

**Comment by perrotta** [comment]
+1

**Pull request merged**
