### PR TITLE
Speed up newCell() in HcalGeometry

### PR DESCRIPTION
**Pull request by kpedro88**
@Dr15Jones profiled the `beginRun` step for a phase2 configuration and found that 200s was spent initializing the HCAL geometry (using FlexiHardcodeLoader). This is because each new cell addition triggered a sorted `insert()` into a vector of valid DetIds.

Since the geometry is filled all at once by the loader, I was able to modify this setup to use regular `push_back()` when adding valid DetIds, and then sort the vector at the end. Intelligent `reserve()`s are also used where possible. This "fast" alternative uses private functions of the geometry, so only friend classes (loaders) can use it. If for some reason, a new cell is added by other code that doesn't guarantee sorting at the end, it will still use the regular sorted insert from `CaloSubdetectorGeometry`.

This changed reduced the 200s setup time to 10s. Much of the remaining time was due to the use of `LogInfo`, which is now replaced by `EDM_ML_DEBUG` preprocessor flags, so messages are only printed in debug mode.

attn: @ianna, @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
