### PR TITLE
Run3-hcx247 Try to make Hcal reco geometry to be derived from dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to complete the geometry access from dd4hep for the hadron calorimeter

#### PR validation:

It is tested with 2 cfg files in Geometry/HcalCommonData/test/python and also used the standard runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Normal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 23434.1001

**Comment by silviodonato** [comment]
+1

**Pull request merged**
