### PR TITLE
[HGCal] HGCalValidation: added hitCalibration for web page

### PR DESCRIPTION
**Pull request by yguler**
#### PR description:
This PR includes updates, which have been done hit Calibration plot for HGCalValidation.

hgcalPlots.py and makeHGCalValidationPlots.py files are modified to read the HGCalHitCalibration folder in the DQM file and plot it in a webpage.

#### PR validation:

python Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root --outputDir HGCalHitCalibration --no-ratio --png --html-sample  TTbar_14TeV --html-validation-name hitCalibration --subdirprefix layerclusters --separate --collection hitCalibration

http://yalcin.web.cern.ch/yalcin/HGCalHitCalibration/

@apsallid, @felicepantaleo , @rovere, @bsunanda, 

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @yguler, could you please make sure that subsystem name appears in the title of the PR?

**Comment by jfernan2** [comment]
@yguler please add a description and the validation performed

**Comment by jfernan2** [comment]
Hi @yguler, I can't seem to find you in [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts). Could you please briefly introduce yourself?

**Comment by fabiocos** [comment]
@yguler could you please:

- give this PR a meaningful title;

- solve the conflicts.

If you have no time to act on this PR now, please close it and reopen when ready.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@yguler please update the title, we use it in the release-notes to know what was done in each PR, "Validation" sounds meaningless in this context

**Comment by apsallid** [comment]
@yguler 

In the title of the PR add [HGCal] in the beginning plus some nicely descriptive title of the work. 
Also, in the description mention sth like (feel free to adjust/change it as you like): 

As part of the Validation of campaings regurarly announced from PdmV and UPSG, HGCal wants to monitor 
the performance of the rechit calibration among other objects. Usually, RelMon and DQM GUI 
is being used for this task. However, in order to quantify the performance of certain clustering algorithms or optimizing the same algorithm or checking different calibration algorithms or inspect the plots in the DQM file easier, we include in the webpage results 
from HGCalHitCalibration DQM folder. 

In the validation part give the link to your webpage with the plots. 

At the end add all people involved with the @ symbol plus some more: 

@apsallid, @felicepantaleo , @rovere, @bsunanda plus shuichi github i do not know.

Most of those people are in cmsbot so they will take it automatically, but I believe is a good practice. 

Finally, to the core of the work. You are changing only the basic script, if i am not mistaken. You should also add your work on the hgcalPlots.py file.

**Comment by yguler** [comment]
I have updated my PR with your suggestions please take a look.

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1 
@yguler I understand the changes are for internal use, the pR is not modifying any workflow

**Comment by fabiocos** [comment]
+1

**Pull request merged**
