### PR TITLE
Fix synchronization in ContextState test [13.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport of #40827:

> @fwyzard mentioned the `testHeterogeneousCoreCUDACore` unit test was segfaulting on a specific Power9 machine after the `ContextState` test section in a way that hinted towards a problem in how TBB was being used. The existing code indeed could destruct the `task_group` while it was still being used in an `task_arena::enqueue()`'d task. This PR fixes the synchronization problem in the test.

#### PR validation:

Tested on `el8_ppc64le_gcc11` on top of `CMSSW_13_0_0_pre4` on a Power 9 node.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #40827

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test on el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for el8_ppc64le_gcc11

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
