### PR TITLE
L1T O2O: degubing of uGMT + new prototype for caloParams payload + scripts' development

### PR DESCRIPTION
**Pull request by kkotov**
Few non-critical cosmetic changes to the L1T O2O utilities and scripts including:
1) viewer for comparing the L1TMuonGlobalParams payloads (useful for debugging)
2) version of the prototyping caloParams, that O2O starts with and reloads with config from the online
3) fixes to the "trigger key validation" script and suppressing verbosity of the main runL1-O2O-iov.sh script

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
Hi @kkotov - please update the title of this PR to be descriptive of the changes for the release notes. Thanks.

**Comment by kkotov** [comment]
Hi @davidlange6 , I've changed the PR's title (hopefully in a more or less laconic way)

**Pull request merged**
