### PR TITLE
Add status flags to GenParticles as analysis aid

### PR DESCRIPTION
**Pull request by bendavid**
Adds status flags which fold useful information about particle status+history into a simplified set of persistent flags which can be used at analysis level and which are less generator dependent.

Use of flags related to the hard process is still discouraged unless absolutely needed.  More robust prompt/non-prompt/from tau decay type flags are provided and preferred.

Preferred flag for matching to prompt leptons/photons at generator level:
isPromptFinalState()
This encompasses any final state particle which is NOT from a hadron, muon, or tau decay.  Practically this means that for charged leptons they either came from the hard process or from (rare) internal conversions of radiated photons.  For photons this flag is a bit more encompassing since it includes all ISR/FSR photons as well as those strictly from the hard process (ie hard matrix element).

Hard process related flags are currently only implemented for pythia6 and pythia8.

isHardProcess() is the closest to pythia6 status 3, but does NOT in general represent final state kinematics and should NOT be used directly for matching to reco objects.  If matching to reco objects is needed and the hard process matching is strictly required, then fromHardProcessFinalState() can be used.

Note that tau decay products must be treated with dedicated flags.
More details in accessor comments
https://github.com/bendavid/cmssw/blob/73d2957327d2b844c439b9e89889d52c6f4bd420/DataFormats/HepMCCandidate/interface/GenParticle.h
https://github.com/bendavid/cmssw/blob/73d2957327d2b844c439b9e89889d52c6f4bd420/DataFormats/HepMCCandidate/interface/GenStatusFlags.h

These flags are currently computed and stored in the GenParticle at GEN-SIM or DIGI-RECO time and are propagated to the prunedGenParticles in the miniaod (but they could be easily recomputed when producing the prunedGenParticles in a future miniaod reprocessing if needed).

Since the flags are persistent and do not rely on any mother-daughter links once stored, potentially the number of intermediate particles in the prunedGenParticles might be possible to reduce.

To be discussed whether these flags should also be added to the packedGenParticles.
(13 bits but only ~10 allowed values, so should compress extremely well)

### CODE REVIEW

**Comment by bendavid** [comment]
@arizzi @gpetruc

**Comment by bendavid** [comment]
Small update coming for this (removing the two muonDecayProduct flags, which are useless, and adding two additional flags in their place for "isFirstCopy" and "isPreFSR")

**Comment by bendavid** [comment]
There are still a few border cases affecting flags for intermediate quarks/gluons (mainly cases where particles have more than one mother).  This won't affect the vast majority of use cases, so it can be fixed later.

Now also adding these flags to both pruned and packed gen particles in MiniAOD.

@arizzi @gpetruc why did PackedGenParticle not have a class version and checksum defined in the class def?  I've added one now, but let me know if there was a reason to leave it out.

MINIAOD size impact estimated on 100 events of ttbar pu35bx25 (what's in relval)

before:
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
patPackedGenParticles_packedGenParticles__PAT. 27574.7 3894.05
recoGenParticles_prunedGenParticles__PAT. 7483.44 1906.53

after:
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
patPackedGenParticles_packedGenParticles__PAT. 36434.6 4117.75
recoGenParticles_prunedGenParticles__PAT. 9255.97 2025.46

So we're looking at ~120 bytes/event for the pruned and 225 bytes/event for the packed.  (Before we start cutting the pruned content of course).  Maybe will be a bit less properly evaluated on more events.

**Comment by arizzi** [comment]
@bendavid it has been fixed in #7584  that switches from pseudorapidity to rapidity.
Btw if you change packedgenparticle you should start from that PR.

**Comment by bendavid** [comment]
Uh, failure looks unrelated to this pull request

##Failure Location unknown## : Error
Test name: testExpressionParser::checkAll
uncaught exception of type N3edm9ExceptionE
- An exception of category 'Configuration' occurred.
Exception Message:
Expression parser error:method named "bDiscriminator" for type "pat::Jet" was p
assed the wrong types of arguments. (char 0)

**Comment by bendavid** [comment]
Combined with the changes from https://github.com/cms-sw/cmssw/pull/7584

**Comment by bendavid** [comment]
+1

**Comment by monttj** [comment]
+1
agreed to have it and #7584 has been already approved.

**Comment by bendavid** [comment]
The failing tests seem related to btag discriminators at
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/CommonTools/Utils/test/testExpressionParser.cc#L221

checking expression: "bDiscriminator("aaa")"E

##Failure Location unknown## : Error
Test name: testExpressionParser::checkAll
uncaught exception of type N3edm9ExceptionE
- An exception of category 'Configuration' occurred.
Exception Message:
Expression parser error:method named "bDiscriminator" for type "pat::Jet" was p
assed the wrong types of arguments. (char 0)


Does anyone have any ideas?  It doesn't look related to the content of this pull request at least.

**Comment by bendavid** [comment]
Really at a loss what the problem is here...

Only thing I can think is that pat::Jet indirectly (through pat object) potentially has an embedded GenParticle.  Checked that DataFormats/PatCandidates DOES explicitly declare a dependency in the build file for DataFormats/HepMCCandidate, so dictionaries should hopefully be building in the right order.

@Dr15Jones @wmtan @VinInn  any ideas?

**Comment by davidlange6** [comment]
@bendavid - could you reproduce this problem locally?

**Comment by bendavid** [comment]
How do I trigger those tests interactively?

**Comment by bendavid** [comment]
Ok, never mind, figured it out.  I cannot reproduce the problem locally, running test/slc6_amd64_gcc491/testCommonToolsUtil succeeds. ( But I had to rebase the changes on 7_4_0_pre7 to test,  since the IB I had used had gone away.)

**Comment by bendavid** [comment]
Is it possible that CommonTools/Utils needs to declare in the BuildFile dependencies on all of the DataFormats packages which are used by https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/CommonTools/Utils/test/testExpressionParser.cc and the like?

**Comment by bendavid** [comment]
I've rebased this pull request on 7_4_0_pre7 in order to be consistent with my local attempts to reproduce the unit test problems.  Let's see what happens to the automated tests this time...

**Comment by davidlange6** [comment]
@cmsbuild, please test

lets see if jenkins reproduces the problem

**Comment by bendavid** [comment]
+1

**Comment by bendavid** [comment]
Ah, yikes.   now I've pulled in some unwanted changes somehow.

Closing this one in favor of 
https://github.com/cms-sw/cmssw/pull/7772

**Pull request closed without merging**
