### PR TITLE
Completed test coverage for Ecal O2Os

### PR DESCRIPTION
**Pull request by ggovi**
Added tests for Ecal code accessing Oracle with OCCI  - production related use cases:
EcalADCToGeV update
EcalIntercalib update
EcalDCS o2o
EcalIntercalibConstants o2o
EcalLaser o2o
EcalTPGBadStripStatus o2o
EcalTPGCrystalStatus o2o
EcalTPGFineGrainEBGroup o2o
EcalTPGFineGrainEBIdMap o2o
EcalTPGFineGrainStripEE o2o
EcalTPGFineGrainTowerEE o2o
EcalTPGLinearizationConst o2o
EcalTPGLutGroup o2o
EcalTPGLutIdMap o2o
EcalTPGPedestals o2o
EcalTPGPhysicsConst o2o
EcalTPGSlidingWindow o2o
EcalTPGSpike o2o
EcalTPGTowerStatus o2o
EcalTPGWeightGroup o2o
EcalTPGWeightIdMap o2o

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
just made an other commit, tests need to be re-lauched

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
