### PR TITLE
Fastsim: 74X premixing

### PR DESCRIPTION
**Pull request by lveldere**
backport of #8490 #8608 #8583 #8455  #8705

@Martin-Grunewald @perrotta 
I will get back to you tomorrow or next week about the back-porting of the FastSim changes in #8753,
that remove the FastSimulation/Configuration/python/HLT_*_Famos_cff.py files

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@civanch, @nclopezo, @boudoul, @mdhildreth, @cmsbuild, @srimanob, @franzoni, @davidlange6 

this *critical* backport is ready for your signature

Would you mind reviewing the changes in your area?
If anything keeps you from signing, please let me know asap how we have to deal with that.

Many thanks

Lukas

**Comment by civanch** [comment]
+1

**Comment by lveldere** [comment]
@nclopezo, @boudoul, @srimanob, @franzoni, @davidlange6

this critical backport is ready for your signature

Would you mind reviewing the changes in your area?
If anything keeps you from signing, please let me know asap how we have to deal with that.

Many thanks

Lukas

**Comment by Martin-Grunewald** [comment]
@nclopezo, @boudoul, @srimanob, @franzoni, @davidlange6

What is this PR waiting for?

**Comment by lveldere** [comment]
Hi Martin

I think PdmV could and should sign this,
but the merge signature is waiting for validation of the FullSim mixing and
premixing machinery in 75X,
because my pr acts on it.

Cheers

Lukas

**Comment by davidlange6** [comment]
@cmsbuild, please test (update the tests to recover the logs)

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by lveldere** [comment]
thanks Giovanni!

On Wed, May 20, 2015 at 8:43 AM, Giovanni Franzoni <notifications@github.com

**Comment by davidlange6** [comment]
+1

**Pull request merged**
