### PR TITLE
Backport of #14048: Speedup ECAL (for HLT)

### PR DESCRIPTION
**Pull request by makortel**
This PR backports #14048 from CMSSW_8_1_X to CMSSW_8_0_X. Original description by @VinInn 

> two independent speedups.
> use cached eta,phi for CaloCell
> remove redundant computations in EcalUncalibRecHitWorkerMultiFit.
> No regression observed.
> http://innocent.home.cern.ch/innocent/regress/pu35_SpeedECAL
> (for HLT, no difference in TriggerResult)

Tested in CMSSW_8_0_14, no changes expected in RECO quantities in here either.

@fwyzard @gennai @slava77 @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Timing tests are in progress...

**Comment by makortel** [comment]
@cvuosalo Are you running reco timing tests, or the HLT timing tests Clint sent in the e-mail thread?

**Comment by fwyzard** [comment]
tracked at #15151

**Comment by perrotta** [comment]
@makortel : could you please check from where the changes in
  RecoParticleFlow/PFClusterProducer/src/PFMultiDepthClusterizer.cc
sneaked in this pull request?

They were not in the original #14048, and looking at the comparison with what is currently in the 80X and 81X queues my impression is that they could revert some update that was already included in 80X.

**Comment by makortel** [comment]
@perrotta Thanks for pointing it out, indeed I was a bit careless when solving "merge" conflict.

The changes in `RecoParticleFlow/PFClusterProducer/src/PFMultiDepthClusterizer.cc` creeped in in commit 5ad35dfe655a6e75bc55db2ad811a60ddc88957e of this PR which is a cherry-pick of commit f86f543274cc545e061c07266ab69918a0e541ff of #14048. In #14048 the produces no differences because the changes were already part of #14058. I agree it would be better to stay with its 80X version, #14057.

I'll test dropping commit 5ad35dfe655a6e75bc55db2ad811a60ddc88957e from this PR (after I finish my currently running test) and update the PR if things look fine. Even if `runTheMatrix -l limited` stats the commit did not show any differences with this PR as it is now.

**Comment by ianna** [comment]
+1

**Comment by makortel** [comment]
I've now taken out the changes in `RecoParticleFlow/PFClusterProducer/src/PFMultiDepthClusterizer.cc` (#14048 had actually more commits than the one I pointed out earlier that mostly undid the changes in the one). Thanks again @perrotta for the catch!

**Comment by makortel** [comment]
@smuzaffar Is there possibly some bug in cms-bot? @ianna's +1 came before I pushed changes to the branch, but it decided to set "geometry-approved" after my push. It also looks like that on the same go it decided to launch tests.

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@makortel , No, there is no bug. According to github the last commit is
```
Latest commit d55f61fb132e567e1bc1c95d0590c13e689a3a86 by  Matti Kortelainen at 2016-07-21T08:27:10Z
```
and Ianna's +1 came at ```Ianna 2016-07-21T08:59:14Z``` which is after the latest commit date that is why
cmsbot consider it as approved changes from geometry.

**Comment by makortel** [comment]
@smuzaffar Ok, I understand the logic, but I'd still argue it is a bit counterintuitive that with the sequence of events
* I file a PR with a commit A
* I develop a commit B in a private branch
* Some L2 +1's the PR (still showing commit A)
* I push the commit B to the PR's branch

cms-bot acknowledges the +1 for the PR with commit B.

I guess I don't really complain (of getting super-fast +1 ;), I was just a bit surprised of the behaviour.

**Comment by cvuosalo** [comment]
@makortel; I'm trying a combination of the HLT and RECO timing tests.

**Comment by cvuosalo** [comment]
+1

For #15231 d55f61fb132e567e1bc1c95d0590c13e689a3a86

Speed-ups for ECAL HLT. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-07-20-2300 show no significant differences, as expected. An extended test of workflow 134.705_RunMET2015B with 100 events against baseline CMSSW_8_0_14 also shows no significant differences.

An HLT timing test was performed against baseline CMSSW_8_0_14 using a config provided by TSG and run on file /store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/Timing/run276935/HLTPhysics_Run276935_LS80-220.root. CPU timing improves by 1.75 ms out of an average 200 ms per event, or about 1%.
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -1.103813      -0.01%         0.03 ms/ev ->         0.01 ms/ev hltRecHitInRegionForMuonsES
   -1.091516      -0.39%         0.92 ms/ev ->         0.27 ms/ev hltRechitInRegionsES
   -1.027878      -0.00%         0.01 ms/ev ->         0.00 ms/ev hltRecHitInRegionForTkMuonsES
   -0.094719      -0.64%        11.81 ms/ev ->        10.74 ms/ev hltEcalUncalibRecHit
  ---------- ------------     --------                  ----       ------------
```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
