### PR TITLE
Relval update after 7_6_0_pre6

### PR DESCRIPTION
**Pull request by hengne**
Relval update after 7_6_0_pre6

1.) re-gen gen-sim for fullSIm, update gen-sim inputs, and premix inputs.

2.) turn off experimental test dqm gui url

3.) add fine jobs splitting for 2015 data workflows

4.) change H130GGgluonfusion_13 to H125xxx, because pythia default mH value changed from mH130 to 125GeV, as requested by generator team

5.) add new 2015B/C data workflows for SingleElectron SingleMuon, SinglePhoton, ZeroBias

6.) add 2015D data workflows.

7.) switch to use "global symbolic tag" for choosing right L1 menu for a given HLT, as suggested by tsg.

8.) update golden json for 2015 data workflows

9.) fix jobs splitting issue for Hadronizer step for newly arranged extended generator workflows.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
