### PR TITLE
Add l1tPhase2L1CaloEGammaEmulator to the phase 2 L1 event content

### PR DESCRIPTION
**Pull request by epalencia**
This PR adds a new collection to the phase-2 L1 event content.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

As for https://github.com/cms-sw/cmssw/pull/43869, we are sort of hoping for this content to make it into the scheduled HLT MC production for CMSSW_14_0. Therefore, this PR may need to be backported based on whether or not it can be quickly included in the final build of CMSSW_14_0.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@skkwan @pallabidas What is the status of a fix for serializing Calo EGamma objects? I am going through today and trying to un-stick L1T PRs and finalize them. Are we ready to retest adding these objects to event content?

**Comment by skkwan** [comment]
@aloeliger @pallabidas We have a fix tested locally that serializes the Calo EGamma objects without errors. We will submit a PR ASAP, only pending one or two changes to the data format of the clusters send to the Correlators that will provide them with the quality bits they need to use.

**Comment by aloeliger** [comment]
Please test with https://github.com/cms-sw/cmssw/pull/44390

**Comment by aloeliger** [comment]
Oh, not even paying attention. @epalencia Could you rebase this when you get the chance?

**Comment by epalencia** [comment]
I'm closing this PR, superseeded by https://github.com/cms-sw/cmssw/pull/44450.

**Pull request closed without merging**
