### PR TITLE
tuning MVA cuts for lowPt and tobTec

### PR DESCRIPTION
**Pull request by mhwalker**
Retuned LowPtTripletStep highPurity MVA cut to remove the step in the chi2 distribution - it pretty much disappears.

Retuned TobTecStep highPurity MVA cut to recover some efficiency at high dxy. Most efficiency lost for dxy < 50 cm recovered.

effvspos
tuning

### CODE REVIEW

**Comment by mhwalker** [comment]
The problems can be seen here (high dxy efficiency loss): http://cmsdoc.cern.ch/cms/Physics/tracking/validation/MC/CMSSW_7_5_0_pre5/MCRUN2_75_V5_PU_highPurity_25ns/RelValTTbar/effvspos.pdf

(chi2 step):
http://cmsdoc.cern.ch/cms/Physics/tracking/validation/MC/CMSSW_7_5_0_pre5/MCRUN2_75_V4_PU_highPurity_50ns/RelValTTbar/tuning.pdf

**Comment by VinInn** [comment]
Let's go with this, we can retune later...

**Comment by slava77** [comment]
@VinInn @rovere 
I suppose we are giving up on vxy>50 cm, right?
(efficiency for vxy>50 cm look about the same in pre4.vs.pre5 comparisons as in pre4.vs.fixFromThisPR)

**Comment by slava77** [comment]
@cmsbuild please test
at least the change in the code looks next to trivial, nice.
There are no payloads changes, right?
@mhwalker please confirm

**Comment by mhwalker** [comment]
@slava77 Correct, no payload changes, only changing the cut value.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10086	bbfedcc
- tested in CMSSW_7_5_0_pre6 /test area sign569/ including higher stat tests (still not much to get a high precision picture)
- the efficiency in high purity tracks is slightly higher for tracks with larger displacement (in agreement with the plots from Matt)
- generalTracks distributions are almost unchanged (as expected: only high-purity assignment changes)
- in ttbar and dijet events there is also a fairly similar noticeable change in the number of higher level objects or other tracks:
    - ~5-10% increase in recoConversions (in gamma 35 sample it's even more significant: ~30% more single leg conversions in the barrel, and 10% more in the endcap)
    - ~0.5% increase in pf candidates
    - ~1.5% increase in electronGsfTracks

flat-pt dijet sample  (400 events here)
wf1313_hp_eff_vs_vtx

the rest if the plots are with ttbar run1-like (pu~20; 200 events here, just higher stat test)
 in line with the plot from Matt
wf202_hp_eff_vs_vtxpos

wf202_hp_eff_vs_dxy

wf202_hp_dups_vs_eta
wf202_hp_fake_vs_eta

**Comment by slava77** [comment]
(NB: my plots were in a comparison with 750pre6 [black])

**Comment by davidlange6** [comment]
+1

**Pull request merged**
