### PR TITLE
GEM dataformat - fix classversion

### PR DESCRIPTION
**Pull request by jshlee**
#### PR description:
 - fix classverions for GEMAMC13Status, GEMAMCStatus, GEMOHStatus and GEMVFATStatus 
 - requested from #34585 
 - removed cout from GEMPackingTester 

#### PR validation:
wf 11634.0 and 34611.0

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by civanch** [comment]
+1

Problem with HI data seems not connected with this PR

**Comment by srimanob** [comment]
+Upgrade

This is a PR that follows the discussion in https://github.com/cms-sw/cmssw/pull/34585.

**Comment by perrotta** [comment]
@jshlee could you please prepare also a backport of this fix for 12_0_X?

**Comment by jshlee** [comment]
> @jshlee could you please prepare also a backport of this fix for 12_0_X?

done

**Comment by davidlange6** [comment]
@slava77 @jpata - this is needed for cruzet. could you have a look?

**Comment by jpata** [comment]
Formally from the reco point of view this can be signed. I was just waiting for the tests to be green, I'm not quite sure what is going on with them...

**Comment by davidlange6** [comment]
the tests are green from what I see

**Comment by jpata** [comment]
I opened an issue for the bot: https://github.com/cms-sw/cms-bot/issues/1605

**Comment by jpata** [comment]
+reconstruction
- only logging changes in reco
- no changes expected/observed

**Comment by perrotta** [comment]
+1

**Pull request merged**
