### PR TITLE
Removed unused RecoParticleFlow/PFClusterTools code

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

I have not idea how controversial this PR will be. In my opinion, the first step to bring the ParticleFlow code under our control would be a serious refactor, which I already contributed to a little bit last year.

Sadly, working on the PF code is not fun at all so I didn't do that anymore, because if you try to improve something you usually break some old code. You'd also have to change this old code that is not even used anymore, which means you just waste your time. Not to mention the cognitive overhead that this old code induces if you want to understand the PF algorithms. This situation can be improved by sweeping through RecoParticleFlow and removing this unused code.

So that's what I try to do here: I removed as many files form RecoParticleFlow/PFClusterTools as possible if you still want CMSSW to compile and the matrix tests to pass.

This code included no plugins which were not used in it's own tests. Please, if you know what this code was used for or if it's still necessary, I am happy to learn about it :)

#### PR validation:

CMSSW still compiles and local matrix tests pass.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@hatakeyamak 
@seemasharmafnal 
@spandeyehep 

is any of the code proposed for removal used in PF calibration?

**Comment by slava77** [comment]
The tests passed and there were no objections yet to the removal.
My plan is to leave this open for comments for a few more days and then signoff by the end of the week if there will be no objections.

**Comment by fabiocos** [comment]
@slava77 I agree, if the code is unused no need to maintain it. In any case it may always be resurrected from the previous versions in case it is really needed

**Comment by hatakeyamak** [comment]
I checked:
https://github.com/hatakeyamak/PFCalibration
which is a fork of:
https://github.com/spandeyehep/PFCalibration
and I don't see any reference to PFClusterTools, so I think it's safe to remove it.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26184	33a1f62
- deletion appears to be safe in the central CMSSW release as well as in some more likely cases of potential use outside of it
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by spandeyehep** [comment]
Hi @slava77 , @hatakeyamak ,
Apologies, I somehow missed this PR updates and comments in the chunk of my other mails.
I was looking at the other of my PR #25883 and noticed that few of the codes have been removed and creating a conflict. e.g.  RecoParticleFlow/PFClusterTools/test/ProducePFCalibration.py and  RecoParticleFlow/PFClusterTools/test/ProducePFCalibrationObject.cc (which we use to generate payload).
Can you please give us any suggestion?

**Comment by perrotta** [comment]
@spandeyehep : if you do need those tests, please reinstantiate them.
Your open #25883 can be used for that (once rebased).
Please also check is some other config which is needed was removed here, and reinstantiate also those ones, in case.

**Comment by spandeyehep** [comment]
Thanks a lot @perrotta for your valuable suggestion. 
I'll re-instantiate all the needed configs.

**Comment by hatakeyamak** [comment]
I was about to give the same suggestions as @perrotta...

**Comment by spandeyehep** [comment]
Thanks a lot @hatakeyamak 
I am working on the fix.

**Pull request merged**
