### PR TITLE
Pixel Material Budget Changes (updated)

### PR DESCRIPTION
**Pull request by schneiml**
Like #17209, but one more material updated after measurements.

- For FPIX, 290um instead of 300um sensor thickness (value measured at FNAL). This change will affect positions of the senstive volumes, even if it is just a few um.

- For BPIX (thanks @zucchett )
   - Correct material for Flange4. This significantly increases the mass of this volume, the old material was incorrect. 
   - Changs to densities to match measurements at PSI
   - Changes to the Sector D shield material.
   - Update to SupplyTubeConn3 to match Supply Tube weight measurements.

If we can get this into pre3, #17209 is obsolete; otherwise, we'll rebase this later.

### CODE REVIEW

**Comment by schneiml** [comment]
@ianna I think what to do with this PR depends on your progress on building the GT.

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
+1

@rovere - I think, you can safely assume this is the last material budget change.
@schneiml - I'll take this one for GT

**Comment by rovere** [comment]
Ok @ianna, I can start building on top of this PR. It will take a while. I'll open a *separate* PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
