### PR TITLE
Protecting E/gamma Scale and Smearing from "nan" energies : 103X

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All, 

This protects the E/gamma scale and smearing from electrons and photons that have nan energies. This will cause problems when finding the scale/smear corrections and cause an exception to be thrown as it rightly detected an inconsistency. 

This fix now makes it so the scale and smearing is not run when the energy is nan and default values are returned. This has happened once so far in the AOD. 

Issue reported and discussed here: https://its.cern.ch/jira/browse/CMSCOMPPR-3266

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24093	2e48433
- the implementation is in line with the PR description. This presently should affect only very rare cases with NaN inputs and (most likely) leading to a crash as reported in https://its.cern.ch/jira/browse/CMSCOMPPR-3266. 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
