### PR TITLE
Tracker DQM HI Quality Test tuning for Offline and Online

### PR DESCRIPTION
**Pull request by arossi83**
This changes are meant only for 10_3_X since there are specific for 2018 HI data taking.
Updates of some DQM Quality Test threshold for both Offline and Online Tracker DQM.

### CODE REVIEW

**Comment by arossi83** [comment]
@mmusich @jandrea FYI

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@arossi83 @andrius-k do we have a master version of this PR? It does not look to be the case...

**Comment by mmusich** [comment]
@fabiocos please cross-check the PR description. This is meant only for HI so it's targeting 10.3.X alone

**Comment by fabiocos** [comment]
@mmusich yes, I saw it, nothing new compared to other PRs. We have plenty of code that is targeting only HI and goes through the regular integration path, moreover here I see some HI dedicated files that are likely not supposed to be overwritten. I would like to maintain some minimal coherence of the code and avoid to jeopardise the release content.

**Comment by mmusich** [comment]
Hi @fabiocos I am not sure to follow. I thought the changes proposed here are not to be used in pp. I don't think it makes sense to apply the changes in 10.4.x to revert them in Run3. Maybe there is a way to enclose the changes in the configuration file via era modifier? @arossi83

**Comment by mmusich** [comment]
@fabiocos, by the way it would help the TK certification team to get these changes integrated before the end of the HI run. Can you clarify if it is unrenounceable to have a master PR? changes proposed here look totally harmless.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@mmusich @arossi83 I do not think that differentiating between HI and pp in live DQM clients is something unusual, I see for instance

https://cmssdt.cern.ch/lxr/source/DQM/Integration/python/clients/pixel_dqm_sourceclient-live_cfg.py#0101

Concerning xml configurations, again they could be easily specialized for pp or HI without this unhealthy trick of commenting/uncommenting lines in different releases, that looks to me quite an error prone approach

**Pull request merged**
