### PR TITLE
Fix output format of MET covariance matrix in MET significance code

### PR DESCRIPTION
**Pull request by mmarionncern**
Fix the output format of the MET covariance matrix, as discussed in https://github.com/cms-sw/cmssw/pull/7163

Minor fix, do not change anything for any sequence.

### CODE REVIEW

**Comment by slava77** [comment]
@mmarionncern Please submit the same to 75X as well.
We'll integrate it into 75X and then could go to 74X after it looks ok in 75X.

**Comment by mmarionncern** [comment]
@slava77 , done for 75X in #7852

**Comment by cvuosalo** [comment]
+1

For #7832 37b348167a616f92bd39fb96ad8ad3f32fa2340c

Small change to improve the format of the new MET covariance matrix. It should not create any differences.

The code change is satisfactory, and the Jenkins tests against [CMSSW_7_4_X_2015-02-18-1400] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7832/2743/summary.html) show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
