### PR TITLE
Add the ASSERT_DEVICE_MATCHES_HOST_COLLECTION macro

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a macro to check that the portable device collection for the host device is the same as the portable host collection.

Add tests from the event data and event setup portable collections.

#### PR validation:

The code compiles correctly, including the new static assertions.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Should be OK for me.
@makortel, I let you review and sign this (or tell me to go ahead).

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/35109

**Comment by makortel** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@cms-sw/orp-l2 could you merge this in `master` ?
We have a few follow up PRs that depend on it.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
