### PR TITLE
Made L1RCTProducer a stream module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The module is used in integration build release validations and was prohibiting use of concurrent LuminosityBlocks.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
prompted by #25090

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
I will merge this tonight. @rekovic let me know if you have any objections

**Comment by silviodonato** [comment]
merge

**Pull request merged**
