### PR TITLE
Remove obsolete KalmanAlignmentAlgorithm

### PR DESCRIPTION
**Pull request by VinInn**
Should have been done long (long) ago...

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
+1
@VinInn thanks. This was a pending issue...

**Comment by frmeier** [comment]
There is likely more obsolete code related to the Kálmán alignment algorithm. Maybe check the ReferenceTrajectories for classes that were only used by Kálmán. I guess it is worthwhile to review the ReferenceTrajectories and keep only what is used by current algorithms.

**Comment by diguida** [comment]
@frmeier IIUC the further cleanup you propose is on the interfaces of `ReferenceTrajectories` related to the Kalman alignment.

**Comment by frmeier** [comment]
@diguida Yes. I guess one should not withhold this PR and make another one for the interface cleanup.

**Comment by diguida** [comment]
@frmeier agreed. Indeed I have just given +1 for this. For the interface cleanup, we can think of doing the following:

1. check in the removed packages which interfaces are used exclusively
1. remove them; if it is used elsewhere, compilation will fail.

Any feedback is welcome.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
