### PR TITLE
Test regression in GPU WF

### PR DESCRIPTION
**Pull request by VinInn**
Just a test to check if regression as seen for instance in #35713 are common

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by VinInn** [comment]
also in this PR https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21d468/21070/summary.html
we observe similar regression

**Comment by VinInn** [comment]
Let's give another spin

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
Ok. I think there is enough evidence for the size of the effect.

**Comment by VinInn** [comment]
shall we close this? Archive the DQM?

**Comment by fwyzard** [comment]
hi @VinInn, for my education, could you point out the effect you are referring to ?

**Comment by VinInn** [comment]
@jpata FYI. did not notice reco was not notified

**Comment by VinInn** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_3_X_2021-12-07-2300+8e524b/47331/validateJR/all_OldVSNew_TTbar14TeV2021pixel3GPUwf11634p506/

**Comment by VinInn** [comment]
see also the same plots in the other PR testing GPU wf.

**Comment by fwyzard** [comment]
and the differences are the small blue dots at the bottom ?

**Comment by VinInn** [comment]
after the DQM PR the regression in the SoA itself are much more reduced https://tinyurl.com/yyobpf2c
(before early-duplicates were included which are not fitted (their params are random at best)

**Comment by VinInn** [comment]
> and the differences are the small blue dots at the bottom ?

yes

**Comment by VinInn** [comment]
maybe we should run 100 events for the GPU wf!

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
@VinInn can we close this ?

**Comment by VinInn** [comment]
Sent from my iPhone

> On May 17, 2022, at 15:06, Andrea Bocci ***@***.***> wrote:
> 
> ﻿
> @VinInn can we close this ?
> 
Ok

**Pull request closed without merging**
