### PR TITLE
Ensure GEANT simulation of exotic long-lived particles that decay outside beampipe

### PR DESCRIPTION
**Pull request by wulsin**
To accomplish this, for any particle with status > 3, set its status to 2.  All such particles are then checked to see if their decay vertex is outside the beampipe; if so it will be passed to GEANT for simulation.  

This fix addresses the problem of a long-lived exotic particle with status code > 3 (e.g., an R-hadron, or chargino), which decays outside the beampipe.  Before this fix, its detector interactions would not be simulated by GEANT, because this module was looking specifically for status values of 1, 2, or 3.  

This fix has been tested for the case of di-chargino pair production, with the chargino ctau set to 1000 cm (decaying to neutralino + pion).  Before the fix, there are no tracks associated to the chargino because no energy deposits have been simulated by GEANT.  After the fix, there are reconstructed tracks for each chargino.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@wulsin , my interpretation of the problem: some particles produced in TTbar_Tauola cannot be tracked by Geant4, so cannot have status=2.

**Comment by wulsin** [comment]
@civanch , Do you have a suggestion for how to avoid this problem?  For certain particles, we could leave their status unchanged.  Or perhaps there is another solution?

**Comment by wulsin** [comment]
I changed this so that only exotic particles have their status modified.  This is to avoid propagating certain Standard Model particles (like K0), that GEANT does not know how to handle.  Let's see if this change solves the errors that we saw before.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
assign generators
(as I'd like to be sure the exit codes of pythia8 are correctly interpreted)

**Comment by perrozzi** [comment]
The PR looks good to me from the GEN point of view. However let me tag also @bendavid to crosscheck as I never specifically used this module. Josh can you please crosscheck?

**Comment by civanch** [comment]
@thuer,@perrozzi,@govoni,  @bendavid, please, sign or comment.

**Comment by civanch** [comment]
@davidlange6 , it seems that GEN has "soft" approval and this PR cannot wait more.

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
