### PR TITLE
Workaround ICC bug.

### PR DESCRIPTION
**Pull request by ktf**
CMSSW compiled with ICC reports a bunch of link errors of the kind:

```
tmp/slc6_amd64_gcc491/src/HLTrigger/Egamma/src/HLTriggerEgamma/HLTDisplacedEgammaFilter.o:(.data._ZTVN3edm6global8EDFilterIIEEE9HLTFilter__24HLTDisplacedEgammaFilter[_ZTVN3edm6global8EDFilterIIEEE9HLTFilter__24HLTDisplacedEgammaFilter]+0x18):
undefined reference to `edm::global::EDFilter<>::~EDFilter()'
tmp/slc6_amd64_gcc491/src/HLTrigger/Egamma/src/HLTriggerEgamma/HLTDisplacedEgammaFilter.o:(.data._ZTVN3edm6global8EDFilterIIEEE9HLTFilter__24HLTDisplacedEgammaFilter[_ZTVN3edm6global8EDFilterIIEEE9HLTFilter__24HLTDisplacedEgammaFilter]+0x20):
undefined reference to `edm::global::EDFilter<>::~EDFilter()'
```

and similar for other `edm::global::EDFilter<>` derived classes.

Notice `edm::global::EDFilterBase`, one of the two parent classes of `edm::global::EDFilter<>`, does have a virtual destructor, so I do believe this is actually a wrong behavior in ICC.

Swapping the order of parent classes in `edm::global::EDFilter` and adding an explicit virtual destructor there makes the problem disappear.

This is clearly not an acceptable solution, but so far I could not find anything else. This PR is just to keep track of the issue.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@cmsbuild, please test
(maybe the tests are stuck @ktf)

**Comment by nclopezo** [comment]
It had the <pre> Couldn't find remote ref refs/pull/7583/head </pre> issue. I restarted the tests using the branch name.

**Comment by ktf** [comment]
Can you please fail the test when that happens?

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by ktf** [comment]
+1
I think we agreed with @Dr15Jones the ifdef is fine.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
