### PR TITLE
Strip packer: protect against invalid header types

### PR DESCRIPTION
**Pull request by pieterdavid**
Fix for a crash in the HLT repacking of HI events where a FED gives an raw data packet with only zeros between the DAQ header and trailer, e.g. (the second warning printout was only for debugging, it's not in the commits of this PR)
```
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigis  23-Nov-2018 21:39:49 CET Run: 327078 Event: 121269290
Exception caught when creating FEDBuffer object for FED: id 101: An exception of category 'FEDBuffer' occurred.
Exception Message:
Buffer format not recognized. Tracker special header: 00 00 00 00 00 00 00 00

Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigis  23-Nov-2018 21:39:49 CET Run: 327078 Event: 121269290
[sistrip::RawToDigiUnpacker::dumpRawData] Dump of buffer for FED id 101
 Buffer contains 96 bytes (NB: payload is byte-swapped)
  Byte |  <---- Byte order ----<  | Byte
  cntr |  7  6  5  4  3  2  1  0  | cntr
     7 : 5f aa 2c 1f 86 20 65 00 :     0
    15 : 00 00 00 00 00 00 00 00 :     8
    23 : 00 00 00 00 00 00 00 00 :    16
    31 : 00 00 00 00 00 00 00 00 :    24
    39 : 00 00 00 00 00 00 00 00 :    32
    47 : 00 00 00 00 00 00 00 00 :    40
    55 : 00 00 00 00 00 00 00 00 :    48
    63 : 00 00 00 00 00 00 00 00 :    56
    71 : 00 00 00 00 00 00 00 00 :    64
    79 : 00 00 00 00 00 00 00 00 :    72
    87 : 00 00 00 00 00 00 00 00 :    80
    95 : a0 00 00 0c cf 8a 00 40 :    88
[sistrip::RawToDigiUnpacker::dumpRawData] End of FED buffer
```

CC: @icali @stahlleiton @CesarBernardes @erikbutz @mmusich

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by icali** [comment]
Hi, 
just wanted to point out that also if the rate of error is reduced and we loose only a couple of 100s of event per run, it would be useful to have this PR online asap. Failing jobs in HLT are indeed slowing down also the transfer system.

**Comment by mmusich** [comment]
urgent

**Comment by perrotta** [comment]
@pieterdavid : the log in the PR description describes the sympton, but if I am not wrong it does not show that this PR fixes it (at least, I don't see the string "Invalid header type for FED, skipping" in the log).
Do you have a log which also shows how these events are handled by this fix?

**Comment by pieterdavid** [comment]
@perrotta yes (sorry, I forgot to add it yesterday), when running `cmsRun` with the output of
```
hltGetConfiguration v2/adg:/cdaq/physics/Run2018HI/v1.5.1/HLT/V9 --globaltag 103X_dataRun2_HLT_v1 --input /store/group/phys_heavyions/errorStream/errorstream327078/Run327078_streamError.root --process MYHLT --full --offline --data --max-events -1 --l1 L1Menu_CollisionsHeavyIons2018_v4_1_1-d1_xml --eras Run2_2018_pp_on_AA --no-output --unprescale
```
with this PR I see 
```
%MSG
%MSG-w DigiToRaw:  SiStripDigiToRawModule:hltSiStripDigiToZSRaw  23-Nov-2018 22:42:34 CET Run: 327078 Event: 121269289
Invalid header type for FED, skipping: id 101
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
```
in the output.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
