### PR TITLE
EventShape and UCC DQM offline HLT 753p1

### PR DESCRIPTION
**Pull request by BetterWang**
Q2 and UCC HLT trigger offline DQM
[+] EventShape histograms for Q2 HLT
[+] SumEt and PixelCluster histograms for UCC HLT
@mandrenguyen

### CODE REVIEW

**Comment by BetterWang** [comment]
Hi @deguio , can you trigger the test? Thanks

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@BetterWang 
this same PR should be submitted to 80x and 76x. needs to be merged there first.
thanks,
F.

**Comment by BetterWang** [comment]
back port from #12339 #12338

**Comment by deguio** [comment]
-1
ventshapeDQM_Q2_top10_cent1030 not defined. in addition please see my comments at #12338

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @BetterWang 
in the end did you collect feedback about the need of all those modules in the trigger sequence for HI?
thanks,
F.

**Comment by BetterWang** [comment]
Hi @deguio , is this necessary for before the HI run?
Currently HI group is focussing on the run prep. Can we separate the trigger sequence after the run?
Just to try not breaking anything for the moment. Thanks.

**Comment by deguio** [comment]
it is ok to me even if a number of non HI-like modules will run even if not needed...
we can fix in a following PR.

**Comment by deguio** [comment]
+1

**Comment by BetterWang** [comment]
Hi @deguio , Can we have this merged before HI data taking?
Thanks,

**Comment by BetterWang** [comment]
The path names are updated to reflect the HI menu.
Can anyone trigger the test please?
Thanks

**Comment by deguio** [comment]
is this one final?
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
merge

the modules run and make empty histograms in 140.53 [among the visible effects using jenkins short tests], this is expected considering the trigger list
80X PR is merged already

**Pull request merged**
