### PR TITLE
Rebase of hgcal validation PR 11649

### PR DESCRIPTION
**Pull request by davidlange6**
@bsunanda #11649 

   145  11:02   cd CMSSW_7_6_X_2015-10-16-1100
   146  11:02   cmsenv
   147  11:02   cd src
   148  11:02   git cms-merge-topic 11649
   150  11:05   git rebase CMSSW_7_6_X_2015-10-16-1100

was sufficient (assuming this PR works)

### CODE REVIEW

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@cmsbuild Please test



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by bsunanda** [comment]
@cmsbuild Please test


Sent from Samsung Mobile

cmsbuild <notifications@github.com> wrote:

-1
Tested at: 5f67c67<https://github.com/cms-sw/cmssw/commit/5f67c67b7245aa7576c69473b8ed560f4182e9b5>
When I ran the RelVals I found an error in the following worklfows:
1003.0 step1

DAS Error

you can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11861/8976/summary.html

**Comment by lgray** [comment]
@bsunanda There is a problem with that particular test not related to this PR. Please stop resubmitting tests for the moment.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
this looks ok and could go in, but its 80x version is broken. wait to see a fix there.

**Comment by bsunanda** [comment]
@deguio DataFormat is changed in 80X - the code needs to be changed for the new DataFormat for 80X - for 76X that changed version will not work. It is better to go for 76X now and I shall make a fresh PR for 80X
________________________________

**Comment by deguio** [comment]
+1
then

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
