### PR TITLE
Merge .h and .cc files of remaining RecoParticleFlow plugins

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Part of the series of PRs that merges `.h` files with the `.cc` files of the plugins in the RecoParticleFlow subsystem, including the Validation package.

This continues the work done in https://github.com/cms-sw/cmssw/pull/34069.

It makes maintaining the plugins much easier and also excludes the possibility to wrongly include plugin header files.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1
No DQM changes as expected

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34660	9ec03c1 
- code changes are technical, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by perrotta** [comment]
+1
- Technical, no changes in outputs

**Pull request merged**
