### PR TITLE
Workflow 511.1: herwig7+ MG5+Openloops pptoee at NLO QCD

### PR DESCRIPTION
**Pull request by Andrej-CMS**
New workflow for testing Openloops with Herwig7

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test workflow 511.1

**Comment by zhenhu** [comment]
+1

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@alberto-sanchez @smuzaffar I notice that this test quite often goes in TimeOut because the LHE calculation is quite heavy (I guess). Although it could be useful to have defined fragments, do you think it is fundamental to probe regularly this code at every IB?

**Comment by alberto-sanchez** [comment]
Not really. I think we really would to have it when the involved libraries or relevant code is updated.
Like in this case openloops was modified. We will have a discussion about this and other possible FW in the following GEN meetings.

**Comment by fabiocos** [comment]
@alberto-sanchez yes please, unless @smuzaffar has some bright idea I do not think it makes sense to have a test that most of the times fails with a TimeOut problem. This looks more suitable for standalone checks

**Comment by smuzaffar** [comment]
@fabiocos , we have a way to customize the timeout per release per workflow. So if no objections I can see timeout for workflow 511.1 to be 3 hours?

**Comment by davidlange6** [comment]
I agree - perhaps a simpler process could be tested instead?

**Comment by smuzaffar** [comment]
almost all the time is taken by the initialization (before first event) in step1. If we can improve this time then we are fine. Rest of the job just took less than a minute for 10 events.

[a]
Started: Tue Oct 16 08:08:34 2018
Finished: Tue Oct 16 09:57:24 2018

[b] Step1 log
%MSG-i ThreadStreamSetup:  (NoModuleName) 16-Oct-2018 08:08:59 CEST pre-events
...
....
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 2 at 16-Oct-2018 09:56:55.891 CEST

**Comment by fabiocos** [comment]
@smuzaffar @davidlange6 it is the openloops calculation at the beginning that takes all the time. If people wants to test it, I do not know whether there is something simpler that might be tried, @Andrej-CMS could you please comment? Otherwise a 3 hours timeout would do the job for what i could see in my check

**Comment by davidlange6** [comment]
> On Oct 16, 2018, at 2:35 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @smuzaffar @davidlange6 it is the openloops calculation at the beginning that takes all the time. If people wants to test it, I do not know whether there is 

Right - i presume that the time for that calculation depends on the physics process...I'll take a look just for fun

**Comment by Andrej-CMS** [comment]
@fabiocos 

the time is taken by the integration of phase space by mg5+openloops. The card has pp->ee +1j. I'm not aware of any easier/faster process at NLO QCD.

**Comment by davidlange6** [comment]
Hi

So have you discussed how this fits into the CMS production infrastructure then? It would be quite wasteful if the usual procedure is followed (8 hour jobs running GEN-SIM with threads)?

otherwise, I tried running this application through igprof - aside from the mystery that it runs much faster (eg, 45 minutes), its straightforward to speed up the initialization I believe. Are there Q/A plots in the DQM for this workflow? 

(but first i need to convince myself that the same job is running with and without igprof...)

**Comment by davidlange6** [comment]
> On Oct 18, 2018, at 9:38 AM, David Lange <David.Lange@cern.ch> wrote:
> 
> Hi
> 
> So have you discussed how this fits into the CMS production infrastructure then? It would be quite wasteful if the usual procedure is followed (8 hour jobs running GEN-SIM with threads)?
> 
> otherwise, I tried running this application through igprof - aside from the mystery that it runs much faster (eg, 45 minutes), its straightforward to speed up the initialization I believe. Are there Q/A plots in the DQM for this workflow? 
> 
> (but first i need to convince myself that the same job is running with and without igprof...)

ok, it seems it makes a big difference if one reruns in a directory that has the Herwig-scratch area already present or not. Starting again from scratch

>

**Comment by prebello** [comment]
@efeyazgan @qili 
could you help to clarify @davidlange6 's question?

**Comment by qliphy** [comment]
@davidlange6 @prebello   I am not sure I understand the question.  But if you want to check the DQM plots, you may do as following:     

CMSSW_10_3_0
runTheMatrix -l 511.1
and after finishing the run, do
cmsRun step3_HARVESTING.py
then you can find all the plots inside the DQM*root file.

**Comment by davidlange6** [comment]
sure. the question is if there are relevant plots for this physics process included?

**Pull request merged**
