### PR TITLE
Run3-sim103 Add tools to study big xml file which goes in the DB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add tools to study big xml file which goes in the DB

#### PR validation:

Used to test the latest big DB produced for dd4hep usage

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

geometry has signed already.

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Test files added, which were already privately used "to test the latest big DB produced for dd4hep usage" (as stated in the PR description)
- They do not affect currently tested workflows

**Pull request merged**
