### PR TITLE
Add DeepMET into NanoAOD for UltraLegacy in 10_6_X (backport of 30291 and 30926)

### PR DESCRIPTION
**Pull request by yongbinfeng**
#### PR description:

Backport DeepMET NanoAOD integration into CMSSW_10_6_X, such that it could be included in UL Nano. More description of DeepMET can be found in the orignal PR. (https://github.com/cms-sw/cmssw/pull/30291). Most of the changes in `PhysicsTools/PatAlgos/plugins/RecoMETExtractor.cc` come from the code-format checks. Also backport https://github.com/cms-sw/cmssw/pull/30926/ to fix the break condition.

For the ultra legacy (`run2_miniAOD_devel`) DeepMETs will not be computed on the fly, but to be extracted from MiniAOD. For other eras DeepMETs will be computed on the fly and saved to Nano.

#### PR validation:

Check with different eras and work as expected. Also passed the `runTheMatrix.py` without errors.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/30291 and https://github.com/cms-sw/cmssw/pull/30926/

@steggema @intrepid42

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of 30291

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31120	78461c1 
- the backports are appropriate
    - backport of #30291 has a feature difference in PhysicsTools/NanoAOD/python/nano_cff.py where the nanoAOD_DeepMET_switch is enabled for a generic/simpler ```(~run2_miniAOD_devel)``` instead of a longish list of modifiers in the master; this seems appropriate in the context of 10_6_X; other changes are consistent with the master (the update in RecoMETExtractor.cc is bringing clang-format changes from the master, which is OK)
    - backport of #30926 is exact by line diffs
- jenkins tests pass and comparisons with the baseline show that the ```deepMet*TuneTable``` products now show up in wf 1325.7 94Xv2Nano (new products should be OK even in the context of the general no-change rule, but also here the re-nano is not from the UL production campaign anyways)

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
@yongbinfeng 
there is a merge conflict in  PhysicsTools/NanoAOD/python/met_cff.py  now.
Please update this PR.

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by yongbinfeng** [comment]
> @yongbinfeng
> there is a merge conflict in PhysicsTools/NanoAOD/python/met_cff.py now.
> Please update this PR.

@slava77 I used the 'resolve conflicts' from this webpage and it seems to have synchronized with all the other updates and made the commit very heavy. (The diff is still clean though.) Is it fine doing this? Or should I do a rebase (or something else) instead? Thanks!

**Comment by slava77** [comment]
> > @yongbinfeng
> > there is a merge conflict in PhysicsTools/NanoAOD/python/met_cff.py now.
> > Please update this PR.
> 
> @slava77 I used the 'resolve conflicts' from this webpage and it seems to have synchronized with all the other updates and made the commit very heavy. (The diff is still clean though.) Is it fine doing this? Or should I do a rebase (or something else) instead? Thanks!

which web page?
Did you follow the rebase-topic from http://cms-sw.github.io/tutorial-resolve-conflicts.html#the-above-is-all-great-stuff-but-i-need-a-quick-recipe ?

In the context of the PR the commit diff is rather simple https://github.com/cms-sw/cmssw/pull/31120/commits/2703a466183ce58e1bd674982c7173f97d75a042
So, this is an acceptable way.

**Comment by yongbinfeng** [comment]
> > > @yongbinfeng
> > > there is a merge conflict in PhysicsTools/NanoAOD/python/met_cff.py now.
> > > Please update this PR.
> > 
> > 
> > @slava77 I used the 'resolve conflicts' from this webpage and it seems to have synchronized with all the other updates and made the commit very heavy. (The diff is still clean though.) Is it fine doing this? Or should I do a rebase (or something else) instead? Thanks!
> 
> which web page?
> Did you follow the rebase-topic from http://cms-sw.github.io/tutorial-resolve-conflicts.html#the-above-is-all-great-stuff-but-i-need-a-quick-recipe ?

Sorry I meant: if there are conflicts, at the bottom of this page there is an option 'resolve conflicts', offered by github to resolve the conflicts interactively. I should have checked the CMSSW resolve-conflicts instructions more carefully. 

> 
> In the context of the PR the commit diff is rather simple [2703a46](https://github.com/cms-sw/cmssw/commit/2703a466183ce58e1bd674982c7173f97d75a042)
> So, this is an acceptable way.

Thanks for confirming this!

**Comment by mariadalfonso** [comment]
+xpog 
the deepMET is added for previous eras or recomputed when the run2_miniAOD_devel is active.

**Comment by ahinzmann** [comment]
Doesn't run2_miniAOD_devel need to be renamed to run2_miniAOD_UL? See #31072.

**Comment by mariadalfonso** [comment]
We decided to use uniformly the run2_miniAOD_devel and we will change later
https://github.com/cms-sw/cmssw/pull/31065#issuecomment-679898951

Decoupling the new mini and new nano give us some flexibility.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31120	2703a46
- since the last reco signoff, this was updated in PhysicsTools/NanoAOD/python/met_cff.py to resolve a conflict in a context line (a somewhat trivial change, which is also not in the reco category)

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
