### PR TITLE
[13_0_X] Add HARVEST step to SKIM WF for Run3

### PR DESCRIPTION
**Pull request by youyingli**
Backport of #42277

### CODE REVIEW

**Comment by youyingli** [comment]
@srimanob @sunilUIET please consider triggering this PR and sign it later

**Comment by srimanob** [comment]
test parameters:
- workflows = 141.101,141.102,141.103,141.104,141.105,141.106,141.107,141.108,141.109,141.110,141.111,141.112,141.113,141.114
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
@youyingli the 13_0_X (this one) and 13_1_X (#42291) backports are different: could you please explain why?
In particular 13_0_X is identical to 13_2_X (#42296), while only the backport to 13_1_X includes also the backport of https://github.com/cms-sw/cmssw/pull/42107, https://github.com/cms-sw/cmssw/pull/42229...

**Comment by perrotta** [comment]
+1

**Pull request merged**
