### PR TITLE
Update of L1T menu in TSG GTs to `L1Menu_Collisions2022_v1_2_0_xml` [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #38405

#### PR description:

Update of L1T menu in TSG GTs (tag name: [`L1Menu_Collisions2022_v1_2_0_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_Collisions2022_v1_2_0_xml)) [[documented in CMSLITDPG-980]](https://its.cern.ch/jira/browse/CMSLITDPG-980?focusedCommentId=4385693&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4385693).

#### PR validation:

Relies on the validation done for the original PR (the HLT menus are currently the same in `master` and `CMSSW_12_4_X`).

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#38405

Development of HLT menus for Run-3 pp data-taking operations, and MC production.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by perrotta** [comment]
> +hlt

@missirol if you want this is 12_4_X, you should also sign the PR in the master, so that it can be merged first

**Comment by missirol** [comment]
> > +hlt
> 
> @missirol if you want this is 12_4_X, you should also sign the PR in the master, so that it can be merged first

Sure, done (the tests in `master` just hadn't finished yet).

**Comment by perrotta** [comment]
+1
- Intended to the 12_4_1 release for data taking

**Pull request merged**
