### PR TITLE
Fix ME0 validation

### PR DESCRIPTION
**Pull request by calabria**
Fix association to match the recent digitizer updates 
@kpedro88

### CODE REVIEW

**Comment by calabria** [comment]
Hi @kpedro88 , this is not high priority, but it is good to start the review and have it integrated. Thanks.

**Comment by kpedro88** [comment]
please test
(I'm not actually responsible for validation/DQM...)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
