### PR TITLE
Fix memory leak in GenParticles2HepMCConverter

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

When checking the NANO matrix tests I noticed some MC workflows show very high memory usage (~6GB). This was tracked down to a memory leak due to undeleted raw pointer in GenParticles2HepMCConverter. This PR fixes that by switching to `unique_ptr`.

#### PR validation:

Tested with NANO matrix test and see much lower and stable memory usage after the fix.

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

Maxmem profiling shows expected reduction:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_2_X_2024-10-02-1100+2e6197/64878/maxmem-comparison/

**Comment by mseidel42** [comment]
Whoops, sorry for introducing this :man_facepalming:  We should also have a backport to 14_1 so that it can be used for Rivet 4 development

**Comment by hqucms** [comment]
> Whoops, sorry for introducing this 🤦‍♂️ We should also have a backport to 14_1 so that it can be used for Rivet 4 development

np :) I will do a backport after this is merged for master.

**Comment by hqucms** [comment]
> Whoops, sorry for introducing this 🤦‍♂️ We should also have a backport to 14_1 so that it can be used for Rivet 4 development

@mseidel42 I opened the backport to 14_1_X in https://github.com/cms-sw/cmssw/pull/46254.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
assign xpog

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
@cms-sw/generators-l2 Could you please review and sign? Thanks!

**Comment by hqucms** [comment]
ping @cms-sw/generators-l2

**Comment by hqucms** [comment]
type bugfix

**Comment by bbilin** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
