### PR TITLE
Include dedx collections in fastsim output [94X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #28257

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical backport of #28257 (the fix in https://github.com/cms-sw/cmssw/pull/28257/files#diff-101886b28ed5eac69de0441e29672a3fR252 was already merged in 94X)
- Changes in the reco configs only refer to fastsim customizations
- Jenkins tests pass and show no changes in reco outputs

**Comment by fabiocos** [comment]
+1

after master validation by @sbein

**Pull request merged**
