### PR TITLE
Add 2023 WFs in runTheMatrix for tests

### PR DESCRIPTION
**Pull request by sunilUIET**
This PR adds more 2023 WFs in the runTheMatrix to be consistent with WFs with 2022 conditions as discussed in https://github.com/cms-sw/cmssw/issues/41410

### CODE REVIEW

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
Hi @sunilUIET 
To me, we have too many MC of Run-3 (8 workflows of MC 2021+2023) and we don't have any Run-3 Data workflow in the short matrix. I don't think it is in the good shape of testing new software.

**Comment by sunilUIET** [comment]
@srimanob good point. We can add say JetMET for 2022 C,D 2023C,D. If you think any other addition will be good, please let me know.

**Comment by srimanob** [comment]
Hi @sunilUIET 
May I propose to reduce 2021 MC workflows, for example, removing PU samples. Then add a workflow of 2023 Data. Either C,D is good from my point.

**Comment by sunilUIET** [comment]
please test

**Comment by srimanob** [comment]
Hi @sunilUIET 
Maybe I don't say it clear. I propose to remove only 2021 PU workflow, but add 2023 PU workflows as you did before. I'm sorry for confusion.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
Hi @sunilUIET 
Do we have 2023 PU workflow at the end?

**Comment by sunilUIET** [comment]
@srimanob Sorry, I missed your last week comment. In that case, I do not see any harm in keeping in 2021 PU WF as well

**Comment by srimanob** [comment]
I just try to reduce no. of workflows that run for PR test. They are workflows that need to run at all for PR test.
So I propose to keep only a year for Run-3 and one for Phase-2.

**Comment by sunilUIET** [comment]
@srimanob would you like to keep PU WF for fastSim as well?

**Comment by srimanob** [comment]
Would be great, thx.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

Note to @cms-sw/reconstruction-l2 to update the comparison matrix later. Thx.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
