### PR TITLE
Run3-hcx326Y Try to use one/EDAnalyzer in some testing codes of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to use one/EDAnalyzer in some testing codes of HCAL

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * test pass nicely

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35964	b5ab699 
- code changes are in line with the PR description: moving from `edm::EDAnalyzer` to `edm::one::EDAnalyzer`
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
