### PR TITLE
[GCC13] Added missing cstdint include

### PR DESCRIPTION
**Pull request by smuzaffar**
Added missing `cstdint` includes to fix the GCC build errors about 
```
error: 'uint32_t' does not name a type
```

This is a technical update

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by smorovic** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio @perrotta , this is just a technical update (adding missing cstdint include), can we get this in to fix some of GCC13 build errors

**Comment by smuzaffar** [comment]
please test

to get clean comparison

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge
(technical and simple enough, I think @cms-sw/reconstruction-l2 won't complain...)

**Comment by jfernan2** [comment]
+1  (for the records)

**Pull request merged**
