### PR TITLE
Update of HLT menu to V1.2 and adjustment of GTs for TSG tests (92X) (on top of #19431 and #19445)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Adjustment of GTs for internal TSG tests (92X)
Based on 924
Includes #19431 and #19445

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by arunhep** [comment]
@Martin-Grunewald I dont understand why autoCond is listed here in the change of files.
Can you may be rebase it so that you can get rid of AlCa signature?

**Comment by Martin-Grunewald** [comment]
This is because #19431 (and #19445) are not yet integrated in 92X, and this is on top of those,
they they are included here. Once #19431 is in, I can rebase the other two PRs.

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
addOnTests fixed by using a 2017 raw-data file for 2017 addOn tests.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
@arunhep @franzoni 
Please sign - the AlCa part is the SAME as already signed in included #19431 and #19445.
Thanks!

**Comment by arunhep** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones
please sign this backport PR (as far as core is concerned: addOnTests)

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
@Martin-Grunewald - ha- i was fooled by the title of this PR, which is now rather misleading. Please update the title and close the obsoleted PRs. I'd rather we see a glimpse of L1 checks in 930pre1 before pushing this back - there were a lot of pieces to be assembled in the end (basically to get things running without crashing)

**Comment by Martin-Grunewald** [comment]
This works for L1 as in 93X - and you have already integrated #19511.
Title of this PR is updated and the other two (one asked to be) closed.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
BTW, we can not wait for 930pre1 relval cycle - that takes too long, and anyway important parts were integrated in 93X only after 930pre1 (V1.2 menu and GT adjustment etc)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
