### PR TITLE
enable MiniAOD validation, in default validation switch GenJets to GenJetsNoNu as new default

### PR DESCRIPTION
**Pull request by webermat**
...validations. Back port for 74X, since 74X is forseen for a test run of MiniAOD validations (75X PR is https://github.com/cms-sw/cmssw/pull/8672) . 

The MiniAOD validation modules are now put in file
Configuration/StandardSequences/python/Validation_cff.py
into validationMiniAOD instead of the prevalidationMiniAOD sequence

Reorganisation for the MET Harvesting to include a PostProcessor for an overall MET Resolution summary plot and a MET PostProcessorHarvester to compare output of RECO and MiniAOD validations.

Tested successfully locally using the mentioned unscheduled Validation
runTheMatrix.py -l 11325 -i all

### CODE REVIEW

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8674	 ed7c357
the same code change as in https://github.com/cms-sw/cmssw/pull/8672	ed7c357
(signed off already)

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
does this one have problems with 74X integration?
(DQM, the main signature, is missing)

**Comment by webermat** [comment]
The issues of PR  #8632 misbehaving was traced back to the MET part of the miniaod sequence. Running the DQM sequence before the minaod validation MET sequence solves that issue, but that is not the desired solution. Thus for now we put the jet part of the jetmet miniaod monitoring sequence into the forseen validation sequence. Once we figure out how to solve the issue on the MET part the miniaod MET monitoring sequence will follow.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8674	5721562
- jenkins tests completed (compiled OK)
- this is the same code (same topic branch) as the signed off 75X version https://github.com/cms-sw/cmssw/pull/8672	5721562
- reco is not affected

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
While checking the output of the MiniAOD vs RECO directory, the default collection in MiniAOD for genjets changed to the ak4GenJetsNoNu collection. Thus we move to ak4GenJetsNoNu as default for RECO too. This hardly affects QCD dijet datasets, but leads to sizable differences for TTbar samples.

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
as expected we see the differences on the GenJet side for TTbar (due to not including neutrinos anymore), while everything on detector level remains unchanged. So everything looks fine.

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8674	10a17d1
this is the same topic branch as the signed off 75X PR #8672 

I personally have doubts about changing the default validation configuration so late in 74X cycle; but DQM signed off. So, should be OK, I suppose.

**Pull request merged**
