### PR TITLE
Run2-hcx36 Add in the digitization code for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
This is done by adding a new package SimCalorimetry/HGCalSimProducers
@lgray

### CODE REVIEW

**Comment by bsunanda** [comment]
@lgray  We want SimCalorimetry/HGCalSimProducers under Simulation category
________________________________

**Comment by lgray** [comment]
@bsunanda I don't manage that.

@smuzaffar could you point us in the right direction?

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@bsunanda I'll rebase all the fast-tining development ontop of your branch and send you a PR. It would be best to

**Comment by lgray** [comment]
@bsunanda actually since that involves the RecHits as well I will make a separate PR with that one after this PR is merged.

**Comment by lgray** [comment]
@smuzaffar once this one is merged can you add it to the list of SIM packages and also add @vandreev11, @pfs, and @lgray as additional watchers for the package? Thanks!

**Comment by slava77** [comment]
@lgray or @bsunanda 
I suggest you edit the categories.py file and submit a PR to cms-bot
https://github.com/cms-sw/cms-bot/blob/master/categories.py

**Comment by lgray** [comment]
@slava77 @bsunanda Will do! Thanks for the pointer.

**Comment by smuzaffar** [comment]
@lgray , please also update the cms-bot/watchers.yaml file to include @vandreev11, @pfs, and @lgray as watcher for this new package.

**Comment by lgray** [comment]
@smuzaffar https://github.com/cms-sw/cms-bot/pull/542 for this package and watchers.

**Comment by smuzaffar** [comment]
cms-bot changes merged. This PR now needs simulation signatures

**Comment by lgray** [comment]
@civanch @mdhildreth

**Comment by lgray** [comment]
@civanch @mdhildreth (sorry for spam) This now needs your signature, we have just added it as a watched simulations package. Please review this PR! Thanks!

**Comment by lgray** [comment]
@civanch @mdhildreth Please review this PR. Thank you!

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
