### PR TITLE
Phase2-gex154C Backport to 13_0_X to fix the issues of 2026D91 and 2026D94

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport to 13_0_X to fix the issues of 2026D91 and 2026D94

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport PR's #40837 and #40838

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
please abort

**Comment by srimanob** [comment]
test parameters:
- workflows = 22034.911,23234.911
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
