### PR TITLE
Phase2-Trk11 Modified 2026D100 scenario after fixing the overlap issue in the Tracker geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modified 2026D100 scenario after fixing the overlap issue in the Tracker geometry

#### PR validation:

Use the runTheMatrix test workflow 25634.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
type tracker

**Comment by srimanob** [comment]
@cmsbuild please test

This is to test on updated D100 geometry. FYI @emiglior

**Comment by bsunanda** [comment]
Hi Ernesto

I told that to Vladimir. This is only a short-term solution as suggested by Vladimir. Once you have that version of pixel.xml, we shall use that only. I agree with your views.

Sunanda
________________________________

**Comment by civanch** [comment]
@emiglior , next week 13_3_X release will be cut. We would prefer to have Phase-2 geometry free of overlaps for the release (see Sunanda talk at the last SIM meeting:  https://indico.cern.ch/event/1333324/ ).  We well understand that it is "work around" and wait for the proper solution from tracker group, we will include it promptly to the baseline for the Phase-2 geometry.

**Comment by srimanob** [comment]
Hi @civanch
I am not sure I get the point of having temporary fix. I think the discussion was only that we will get a fix of pixel XML in the same D100. Since we have no plan yet to move to D100 in the next 2-3 pre-release. Why do we need this now?
@emiglior Can you provide the ETA of fixing?

Thx all.

**Comment by civanch** [comment]
@srimanob , for me it is not a critical question. I would merge this PR and wait for the real fix.

**Comment by bsunanda** [comment]
Hi

It is definitely a better solution than one with overlap. So it is good to merge this and then wait for the final version.

Sunanda
________________________________

**Comment by srimanob** [comment]
+Upgrade

Temporary fix for overlap in D100. However, it is not clear to me on pushing this for a short term as proper fix will come. We don't have plan to use D100, and validation will not happen until proper fix comes. I leave this decision to @emiglior

**Comment by antoniovilela** [comment]
> +Upgrade
> 
> Temporary fix for overlap in D100. However, it is not clear to me on pushing this for a short term as proper fix will come. We don't have plan to use D100, and validation will not happen until proper fix comes. I leave this decision to @emiglior

@emiglior @srimanob @civanch
We will close 13_3_0_pre5, the last open, in the end of the month, so this gives the timescale.
Phat, if you think input is still needed, let's wait.

**Comment by antoniovilela** [comment]
@cms-sw/upgrade-l2 @bsunanda @emiglior
Phat, Sunanda,
Maybe Ernesto is not checking regularly the GitHub notifications.
Could you send a message to him and others, so that we conclude on the questions raised in https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1761487110 and https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1762883933.

**Comment by bsunanda** [comment]
As we mentioned this is only an intermediate step. We do not want to have a scenario which has overlap issues. The Tracker group's fix may take a while. Once we have that we shall update that yet again. Meanwhile, you can merge this PR which will give more sensible results than the one in the repository.
________________________________

**Comment by emiglior** [comment]
> @cms-sw/upgrade-l2 @bsunanda @emiglior Phat, Sunanda, Maybe Ernesto is not checking regularly the GitHub notifications. Could you send a message to him and others, so that we conclude on the questions raised in [#43007 (comment)](https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1761487110) and [#43007 (comment)](https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1762883933).

Sorry for not reacting earlier. 
Currently, I cannot provide an ETA for solving this issue from basic principles (e.g. through the tkLayout->CMSSW chain).
Would you agree that once we have the fix based on tkLayout, we simply overwrite the current files defining T33 geometry without introducing a new one? 
Or do you need a new version (T34) anyway, as you plan to use T33 for some production?

**Comment by antoniovilela** [comment]
> > @cms-sw/upgrade-l2 @bsunanda @emiglior Phat, Sunanda, Maybe Ernesto is not checking regularly the GitHub notifications. Could you send a message to him and others, so that we conclude on the questions raised in [#43007 (comment)](https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1761487110) and [#43007 (comment)](https://github.com/cms-sw/cmssw/pull/43007#issuecomment-1762883933).
> 
> Sorry for not reacting earlier. Currently, I cannot provide an ETA for solving this issue from basic principles (e.g. through the tkLayout->CMSSW chain). Would you agree that once we have the fix based on tkLayout, we simply overwrite the current files defining T33 geometry without introducing a new one? Or do you need a new version (T34) anyway, as you plan to use T33 for some production?

@bsunanda
Sunanda, all,
Please coordinate with the Tracker group for the best strategy. We will merge this as proposed, as a temporary fix.

**Comment by antoniovilela** [comment]
+1
   - Since the final solution still needs time, we go with the temporary fix as proposed.

**Comment by civanch** [comment]
@emiglior ,  just now T33 is opened for fixes and will be opened until a decision to freeze this version. When this will happen we do not know yet.

**Pull request merged**
