### PR TITLE
fix MeVperADC default

### PR DESCRIPTION
**Pull request by VinInn**
as reported in
https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1741.html

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21722	3cfb695
- fixed values in the DeDxEstimatorProducer::fillDescriptions. These are not used in CMSSW module instances directly and still come from the old style [partly redundant] configs
- jenkins tests pass and comparisons with baseline show no relevant differences
- git grep shows that no changes are expected in CMSSW module instances
    - DeDxEstimatorProducer_cfi made by the framework is not used 
    - all instances of DeDxEstimatorProducer use correct values

**Comment by VinInn** [comment]
Should this DeDx package be cleanup?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
