### PR TITLE
Enable PPS transport

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Attempt to enable PPS proton transport

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@mundim ,  please, check this PR - this is an attempt to enable PPS simulation again.

**Comment by civanch** [comment]
+1

**Comment by mundim** [comment]
> @mundim , please, check this PR - this is an attempt to enable PPS simulation again.

Hi Vladimir. Sorry to have nor replied you directly. I have done some tests with Gustavo Gil (@diemort ?) and the simulation is working properly, but I'm not 100% sure I have tests specifically this PR. I mentioning Gustavo here, hopefully he can reply you. I'm no longer in the PPS simulation group, but could give some help in case it is needed.

**Comment by perrotta** [comment]
+1
- As agreed right now at the ORP meeting, let enable PPS Transport in the master IBs and verify as such if the fix implemented long time ago to solve the thread issues actually works

**Comment by diemort** [comment]
dear all, I tested the flag in the last night IB and it works as expected: without any flag the CTPPS simulation is active and it is skipped by setting manually the flag to False. So, this change is good from my side.

**Pull request merged**
