### PR TITLE
Various improvements in the conddb command tools

### PR DESCRIPTION
**Pull request by ggovi**
conddb tools fixes and new features:
- init command has been fixed
- iov insertion time is generated ( rather then copied ) while copying
- updating commands ( copy and edit ) are generating the TagLog entries
- authentication for offlcial database targets supports .netrc credential file
- reading/writing from/to official databases supports GENERAL_READER and GENERAL_WRITER users
- updates on existing tag requires confirmation
- copy command support --override option for Tags
- edit in official databases cannot delete iovs
- edit in official database generates insertion time for added iov entries

uploadCondtion command
- support the re-upload of an already attempted file with the -r option

o2o commands
- fix for job enabling/disabling

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@slava77, @smuzaffar 
any hint about what is going wrong here?

**Comment by smuzaffar** [comment]
we are having various random issues with github. conenction to github is timing out due to which tests are not running properly. 
Github support team is looking in to the issue

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
