### PR TITLE
ECAL : DB PayloadInspector modification

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:

ECAL : DB PayloadInspector : modification of limits for display of EcalPedestals plots (due to noise increase with integrated luminosity)

#### PR validation:

Tested in local with CondCore/Utilities/getPayloadData.py : Json file produced on a recent iov

### CODE REVIEW

**Comment by tvami** [comment]
@depasse please also squash the two commits into one (let me know if you need instructions on how to do that)

**Comment by depasse** [comment]
Yes I need.  I suppose I must go to the commits tab but after ?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * tests pass

**Pull request merged**
