### PR TITLE
[PDMV-UPGRADE] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 can you please review this PR.  This is just a technical update to drop the use of `__future__` py2/3 compatibility module.

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
