### PR TITLE
bsunada:Run2-alca21 Modify HO calibration code - taken from Gobinda

### PR DESCRIPTION
**Pull request by bsunanda**
Gobinda's modification to AlCaReco code and the analyzer for HO calibration

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@bsunanda the error above though related to a missing record in the ES doesn't come from the GT....

**Comment by smuzaffar** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Several new changes are made and a new pull request will be made for 8_0_X version

**Pull request closed without merging**
