### PR TITLE
Protect against reading invalid prescales

### PR DESCRIPTION
**Pull request by Dr15Jones**
Avoid reading beyond the end of the vector.
Problem was found by address sanitizer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This fixes problems seen in the ASAN IB RelVals. E.g.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_10_1_ASAN_X_2018-02-04-0000/pyRelValMatrixLogs/run/136.75_RunJetHT2016D+RunJetHT2016D+HLTDR2_2016+RECODR2_2016reHLT_skimJetHT_HIPM+HARVESTDR2/step2_RunJetHT2016D+RunJetHT2016D+HLTDR2_2016+RECODR2_2016reHLT_skimJetHT_HIPM+HARVESTDR2.log

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@nsmith- @thomreis @rekovic @fabiocos ping. This is a memory problem that needs to be solved.

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
@fabiocos didn’t this pass all the tests already?

**Comment by fabiocos** [comment]
@Dr15Jones it ran indeed, I see anyway more than thousand histos are different, and this test picked other PR for what I see. Looking randomly at the differences the histos seem essentially identical...

**Comment by Dr15Jones** [comment]
@fabiocos the original code was creating objects using random memory (actually reading parts of the next object in the container or whatever was off the end of the container). If any later code made decisions based on those random values, I'd definitely expect differences.

**Comment by fabiocos** [comment]
@Dr15Jones thanks for the clarification. In the last test apparently no difference, may be just good luck? I merge the fix.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
