### PR TITLE
Fixing AlCaRecoTriggerBits reading/writing for condDBv2 

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all. No need here to change `Configuration.StandardSequences.FrontierConditions_GlobalTag_cfi`, since it's already pointing to condDBv2 by default.

### CODE REVIEW

**Comment by mmusich** [comment]
plase test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
