### PR TITLE
Fixed CMS Deprecated warnings in RecoTracker/DebugTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- moved modules away from legacy base classes
- added esConsumes (and some consumes)
- removed unused CkfDebugger class

#### PR validation:

Code compiles and no longer issues the warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
NOTE: some of the modules do not even have Event consumes declared so have not functioned for all of Run 2. Perhaps an audit of what code can be removed would be in order.

**Comment by slava77** [comment]
assign tracking-pog

to signoff on removal of `CkfDebugger` class
@mmusich

**Comment by mmusich** [comment]
> to signoff on removal of `CkfDebugger` class.

I would prefer it to be kept (even for pedagogical purposes). If it needs maintenance, I can pledge to do it for after the break. 
Thanks

**Comment by Dr15Jones** [comment]
@mmusich @slava77 what is the plan then for this PR?

**Comment by mmusich** [comment]
@Dr15Jones what about undoing the changes about "removed unused CkfDebugger class" from this PR and I can take care of those in a follow-up one?

**Comment by Dr15Jones** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- technical, no reco changes

**Comment by jpata** [comment]
ping @cms-sw/tracking-pog-l2 just in case, you were assigned earlier to explicitly sign this before this can move forward.

**Comment by mmusich** [comment]
unassign tracking-pog

As agreed [here](https://github.com/cms-sw/cmssw/pull/36582#issuecomment-1008966655) there will be a follow-up PR to finish cleaning the package

**Comment by perrotta** [comment]
+1

**Pull request merged**
