### PR TITLE
Run3-sim67 Add 2 physics lists for use in verification using HGCal TB data

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use of physics lists in the tests of Geant4 using HGCal TB data

#### PR validation:

Use standard runTheMatrix.py and also use private tests with the new physics lists

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , we may add these two extra PLs but do you understand that they are equivalent to QGSP_FTFP_BERT_EMM and QGSP_FTFP_BERT_EMN? For me there is nothing bad but we only duplicate exist PLs.

**Comment by bsunanda** [comment]
@civanch May be I close this PR and add a couple of python scripts which can be used by the TB teams. Please suggest

**Comment by bsunanda** [comment]
I am closing this PR and adding a PR to add a few cfg files which will help TB jobs

**Pull request closed without merging**
