### PR TITLE
TRK DQM : add dz and dzErr profiles

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:
while looking at the track-vertex association, it turns out we do not monitor the track dz
in particular its error as function of the track eta

this update introduces new plots to the TRK directories

#### PR validation:
pass all tests done via `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by silviodonato** [comment]
@mtosi we cannot do anything until you apply the automatic code-format fixes

> -code-checks
> 
> Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29455/14645
> 
>     * This PR adds an extra 40KB to repository
> 
> 
> Code check has found code style and quality issues which could be resolved by applying following patch(s)
> 
>     * **code-format**:
>       https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29455/14645/code-format.patch
>       e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29455/14645/code-format.patch | patch -p1`
>       You can also run `scram build code-format` to apply code format directly

**Comment by mtosi** [comment]
@silviodonato thanks for the reminder !

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
Ciao @mtosi , I have several quetions:

- could you please elaborate a bit where the new plots should be added?

- What is the scope of these new plots? Release validation? Tracking scenarios test? The plots are being addeed in every single workflow but FastSim: data, cosmics, HI, MC, Run1, Run2, Run3, Phase2

- Have you checked in your tests if the output makes sense beyond a successful runTheMatrix -l ?

- I see that plots are added not only to the Tracking folder but in many other places like HLT, EGM, Muon, and even EXO, and in many cases empty, instead the Tracking folder has stats.

- In particular plots dubbed *DCASi*_inner are always empty for every workflow and every folder, while DistanceOfClosestApproachAlongZ* in the same folder are totally filled with plenty of stats, is this expected?
Thanks

**Comment by silviodonato** [comment]
> Ciao @mtosi , I have several quetions:
> 
>     * could you please elaborate a bit where the new plots should be added?
> 
>     * What is the scope of these new plots? Release validation? Tracking scenarios test? The plots are being addeed in every single workflow but FastSim: data, cosmics, HI, MC, Run1, Run2, Run3, Phase2
> 
>     * Have you checked in your tests if the output makes sense beyond a successful runTheMatrix -l ?
> 
>     * I see that plots are added not only to the Tracking folder but in many other places like HLT, EGM, Muon, and even EXO, and in many cases empty, instead the Tracking folder has stats.
> 
>     * In particular plots dubbed _DCASi__inner are always empty for every workflow and every folder, while DistanceOfClosestApproachAlongZ* in the same folder are totally filled with plenty of stats, is this expected?
>       Thanks

@mtosi

**Comment by arossi83** [comment]
Hi @mtosi, are the plots on OfflinePV not sufficient to monitor  such quantities? https://tinyurl.com/y7f66a4d
Here the code where those plots are filled: https://github.com/cms-sw/cmssw/blob/master/DQMOffline/RecoB/plugins/PrimaryVertexMonitor.cc

**Comment by silviodonato** [comment]
Kind reminder @mtosi

**Comment by silviodonato** [comment]
Just a reminder that 11_1_X will be closed to new features in one week.

**Comment by silviodonato** [comment]
Please let me know as soon as you want to open back this PR.

**Pull request closed without merging**
