### PR TITLE
[13_2_X] Vertex smearing for PbPb MC based on 2023 PbPb data

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #43217
See master PR for detailed description

#### PR validation:
See master PR

#### Backport:
Backport of #43217

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #43217

**Comment by francescobrivio** [comment]
@cmsbuild please test

- even though nothing is really consuming this for now AFAIU

**Comment by mmusich** [comment]
urgent. See https://its.cern.ch/jira/browse/PDMVRELVALS-223

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
@cms-sw/simulation-l2 
Please check and sign.
Thanks.

**Comment by civanch** [comment]
+1

**Comment by ashleyahram** [comment]
Dear @antoniovilela, 

Can I ask a new release so that we can produce a relval MC sample using CSMSW_13_2_X with the implemented PR. We are waiting for it to produce MC described in this JIRA ticket ([PDMVRELVALS-223](https://its.cern.ch/jira/browse/PDMVRELVALS-223))

Thank you,
Saeahram

**Pull request merged**
