### PR TITLE
Run2-gex117 Make a set of material files for tracker which does not complain about 'the sum of components do not add to 1' for 2016 setup

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a set of material files for tracker which does not complain about 'the sum of components do not add to 1' for 2016 setup. Useful for testing new geant4 versions

#### PR validation:

Use specific workflows using 2016 setups (defined HcalCommonData)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
This is OK to me.

**Comment by civanch** [comment]
@cvuosalo , can , please, comment

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
