### PR TITLE
[MuonHLT]:  BugFix for TSGforOI

### PR DESCRIPTION
**Pull request by folguera**
This fixes a couple of bugs discovered that were affecting the efficiency specially in the overlap region:
- Added error-rescaling for hit-based seeds.
- Correct reseting of the number of made seeds (affecting the overlap region)
- Add a configuration parameter to chose the name of the propagator in the config file (it was previously hard-coded) 

This only affects the outside-in component of the Muon HLT reconstruction.

### CODE REVIEW

**Comment by perrotta** [comment]
Please provide a PR for the master release first.
When that will get merged this backport to 92X can be taken into account

**Comment by slava77** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
backport of #20396

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20393	340eeb1
- the same changes as in the parent PR https://github.com/cms-sw/cmssw/pull/20396	8b05427 in the master branch; affects only HLT products
- jenkins tests pass and comparisons show changes only in HLT plots directly or consequently related to muons

**Comment by davidlange6** [comment]
+1

**Pull request merged**
