### PR TITLE
Add missing namespace to isnan calls

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

See description. Technical fix, required to update ROOTmaster

#### PR validation:

Bot tests here + https://github.com/cms-sw/cmsdist/pull/8777

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 @cms-sw/reconstruction-l2 can you please review this. It is just a technical fix ( adding missing `std` namespace for `isnan`)

**Comment by tjavaid** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio @antoniovilela , can we merge this before 11h00 IB? This is needed for ROOT master IBs

**Pull request merged**
