### PR TITLE
Add TICL from Reco customise

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Add a `customise` function to be able to quickly run HGCAL TICL-reconstruction from the RECO data-tier. This will cut down the development cycle by a considerable amount. Also, save the output using a dedicated, slimmed, HGCAL-only event content to save space.

#### PR validation:

Local testing works just fine.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@rovere just to check - this does not run in any standard workflow, it's just for "private" tests by the TICL team?

**Comment by rovere** [comment]
> @rovere just to check - this does not run in any standard workflow, it's just for "private" tests by the TICL team?
@jpata that's exactly correct. I'd prefer to have it in release so that it can be used by all the developers. Re-running just TICL -related reconstruction from RECO, instead of the full workflow is just much faster. And the event content is up to ~10 times smaller. Quite useful, I think.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

The introduced customization does not effect the main workflow.

**Comment by jpata** [comment]
+reconstruction
- private customization not used in standard reco

**Comment by qliphy** [comment]
+1

**Pull request merged**
