### PR TITLE
Phase2-hgx287V New Validation tool for HGCal Geometry from Imran Yusuff

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

New Validation tool for HGCal Geometry from Imran Yusuff

#### PR validation:

Tested for the 2026D83 Geometry using cmsRun testHGCalWaferVallidation_cfg.py geometry=D83

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
@bsunanda  the new plugin uses couts everywhere, which are highly discouraged. I understand it is for private use, I do not know if this can be an exception.
I let @qliphy and @silviodonato to comment

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by qliphy** [comment]
> @bsunanda the new plugin uses couts everywhere, which are highly discouraged. I understand it is for private use, I do not know if this can be an exception.
> I let @qliphy and @silviodonato to comment

Yes, it is better not to use cout here,   https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger

**Comment by jfernan2** [comment]
@bsunanda please consider the comments above about couts

**Comment by imranyusuff** [comment]
I have changed all couts to use MessageLoggers and emailed the changes into a git bundle to @bsunanda however there are still issues in merging them into this branch. Need assistance in this.

**Comment by jfernan2** [comment]
What kind of conflicts?
Have you checked this link related to merge conflicts?
http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by bsunanda** [comment]
Done now. Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
