### PR TITLE
[10.6.X] Backport of APV Simulation RelVals

### PR DESCRIPTION
**Pull request by mmusich**
Backport of https://github.com/cms-sw/cmssw/pull/28024 and https://github.com/cms-sw/cmssw/pull/28082

#### PR description:
This PR:
   * adds 4 TTbar workflow with the feature activated in the digitizer: `1325.9` (TTbar 2016, noPU), `25202.1` (TTbar + PU, std. mixing),  `250202.2` (TTbar + PU, premixing) and  `250202.3` (TTbar + PU, premixing - redoing the mixing library). 
  * add for the various no-PU, PU (std. mixing) and PU (premixing) dynamic APV gains simulation relvals the HIP mitigation customization as it is meant to be run for the pre-VFP 2016 MC.

#### PR validation:
Code changes passes dedicated testing via:
```
runTheMatrix.py -l 25202.1,25202.2,250202.2,250202.3,250202.4,250202.5,1325.9,1325.91 --ibeos
```

#### if this PR is a backport please specify the original PR:
This is a combined backport of https://github.com/cms-sw/cmssw/pull/28024 and https://github.com/cms-sw/cmssw/pull/28082

**N.B. this PR can be used to test  #28512**

### CODE REVIEW

**Comment by fabiocos** [comment]
@chayanit @kpedro88 this backport looks consistent with the corresponding code in master, merged quite sometime ago, and it is needed to finalize next 10_6_X release for 2016 UL asap . Please check it, I go on with its integration to speed up things

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Pull request merged**
