### PR TITLE
Add zoomed dxy(PV) and dz(PV) to MultiTrackValidator, and a B-hadron TP instance to standalone/trackingOnly modes

### PR DESCRIPTION
**Pull request by makortel**
This PR adds zoomed-in versions of dxy(PV) and dz(PV) to MultiTrackValidator, to better monitor the region of |dxy|<1cm that is important for b tagging. In addtion, an instance of MTV with B-hadron TrackingParticles is added to the standalone and trackingOnly sequences (possibly to be added to the standard sequence if proves to be useful in private tests).

Tested in 9_0_0_pre4, expecting appearance of `*_dxypv_zoomed` and `*_dzpv_zoomed*` histograms. No changes are expected in existing histograms.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
