### PR TITLE
New feature: CSC CLCT pre-trigger digi object in CSC L1 trigger emulator

### PR DESCRIPTION
**Pull request by dildick**
@tahuang1991 is looking into how `CSCCLCTDigis` in a chamber correlate to the CLCT pre-trigger digi(s).  For detailed analyses we need to write out the pre-trigger digi as EDM products. Therefore Tao suggested to add the `CSCCLCTPreTriggerDigi` as a dataformat. These `CSCCLCTPreTriggerDigi`'s will not be used in the CSC local trigger nor in the CSC DAQ.  However, they are essential to understand the trigger and DAQ rates in Run-3 and Phase-2 when GEMs come online.

For now, the `CSCCLCTPreTriggerDigi` format is the same as for `CSCCLCTDigi`. In the future we may want to extend the dataformat with a list of half-strips that participated in the pre-trigger. For this reason we did not want to re-use the `CSCCLCTDigi` format.

I also added a template function in `CSCTriggerPrimitivesBuilder` which removes a lot of code-duplication.

@tahuang1991 @ptcox FYI

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
@dildick Why don't we want to simply extend the current CSCCLCTDigi DataFormat ?  Pre-firing sounds like a useful information.

**Comment by tahuang1991** [comment]
The reason is that
1.  In firmware (O)TMB just sends out CLCTs and LCTs but no pre-trigger information is saved and sent out  because of bandwidth limit. In offline re-emulation using real data and in simulation, we do want to look into pretrigger to have a better understanding on  (O)TMB. 
2. Pre-trigger itself is not necessary to be associated to any CLCTs,  Since CLCTs construction is  in 2BX  after pretrigger and the requirement to build CLCT is different from the one for pretrigger. It is always possible that we can see pretrigger but not CLCTs.
3. Pre-trigger can have similar structure as CLCT does.  In term of consistence between firmware and simulation, we do not want to modify the CLCT digi in simulation, but we may modify the pretrigger class in simulation (like including more information if we need)  without complaining from firmware.


Cheers,
Tao

**Comment by ptcox** [comment]
Hi Tao,

That's a very thorough justification. Thanks!

But I think the simple answer is that the CSC  'pretrigger' is a well-defined, early stage of the electronic logic in trigger primitive formation, and doesn't directly relate to any issues of 'prefiring'. 

Regards, Tim

**Comment by dildick** [comment]
@rekovic As Tim pointed out, the ~1% LCT pre-firing that has been reported is not related to the CLCT pre-trigger. The latter will be understood better by writing out CLCT pre-triggers. The former is related to the way BX is assigned to ALCT/CLCT and/or the ALCT-CLCT correlation algorithm.  This is still under investigation.

**Comment by dildick** [comment]
@rekovic Do you have any more comments on this PR?

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
@rekovic Thanks!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
