### PR TITLE
Make separate L1T autoDQM sequences for efficiency measurements

### PR DESCRIPTION
**Pull request by thomreis**
The L1T offline DQM efficiency measurements for objects do not need to run on every dataset.
L1T muon, tau, MET, and jet efficiencies can use the singleMuon dataset and L1T EGamma efficiencies are calculated using the singleElectron dataset.

This PR creates new DQM sequences for L1T in autoDQM.py that contain only the efficiency modules. For running at the T0 the DQM sequences need to be added to the dmwm/T0/etc/ProdOfflineConfiguration.py configuration for the singleMuon dataset (https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L599) and the singleElectron dataset (https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L584).

For RelVal some changes would be needed as well (probably somewhere in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1566) to run the DQM efficiency calculation only for some MC and data samples.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

The l1TriggerDqmOffline sequence was put back in the DQMOfflineCommonSiStripZeroBias sequence to avoid a crash with missing hcal TP emulation in a module named tpTask.

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be reviewed/merged please?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
