### PR TITLE
Validation/Geometry: Fix floats definition. default constructor

### PR DESCRIPTION
**Pull request by vargasa**
Address reviewer's comments: https://github.com/cms-sw/cmssw/pull/25139#discussion_r231835206

### CODE REVIEW

**Comment by cvuosalo** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by smuzaffar** [comment]
@vargasa , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by perrotta** [comment]
-1
(Not for reco, rebase needed)

**Comment by kpedro88** [comment]
FYI, how to rebase: http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fabiocos** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by vargasa** [comment]
Hi @alja. This PR was rebased. Could you please sign it again? Thanks :)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
