### PR TITLE
get rid of more UB in `TrackListMerger`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In response to https://github.com/cms-sw/cmssw/issues/35036#issuecomment-1079718341, follow-up to https://github.com/cms-sw/cmssw/pull/37308.

#### PR validation:

`cmssw` compiles, also run `runTheMatrix.py -l limited -j 8 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
seems tests have been stuck here for a while?

**Comment by jpata** [comment]
I checked UBSAN with this PR and the number of errors is reduced but does not completely disappear.
 
```
joosep@joosep-desktop-work:~/reco/37384/CMSSW_12_4_UBSAN_X_2022-03-28-1100/35434.0_TTbar_14TeV+2026D78+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal$ grep TrackListMerger step3_TTbar_14TeV+2026D78+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log 
/home/joosep/reco/37384/CMSSW_12_4_UBSAN_X_2022-03-28-1100/src/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:451:45: runtime error: variable length array bound evaluates to non-positive value 0
/home/joosep/reco/37384/CMSSW_12_4_UBSAN_X_2022-03-28-1100/src/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:452:20: runtime error: variable length array bound evaluates to non-positive value 0
```

**Comment by jpata** [comment]
@smuzaffar looks like the bot may need manual intervention here, could you please check? Or would "please cancel / please test" have an effect here?

**Comment by smuzaffar** [comment]
please test
as previous run was 2 days ago, so let re-run the full tests

**Comment by mmusich** [comment]
> I checked UBSAN with this PR and the number of errors is reduced but does not completely disappear (2 errors in 100 events)

thanks @jpata I am addressing those. Running local tests now.

**Comment by jpata** [comment]
@mmusich just to check in on this - were you able to reproduce the failing UBSAN even after this PR?

**Comment by mmusich** [comment]
@jpata 

> just to check in on this - were you able to reproduce the failing UBSAN even after this PR?

yes, but after applying the same kind of trivial fix that I have applied everywhere (which is to return after the arrays with size `ngood` are created)

```diff
diff --git a/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc b/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
index 3be2d7e3db0..98ae408d4f0 100644
--- a/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
+++ b/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc
@@ -448,6 +448,13 @@ void TrackListMerger::produce(edm::Event& e, const edm::EventSetup& es) {
   typedef std::pair<unsigned int, const TrackingRecHit*> IHit;
   std::vector<std::vector<IHit>> rh1(ngood);  // "not an array" of vectors!
   //const TrackingRecHit*  fh1[ngood];  // first hit...
+
+  if (ngood == 0) {
+    // output empty collections and early return
+    this->returnEmptyCollections(e);
+    return;
+  }
+
   reco::TrackBase::TrackAlgorithm algo[ngood];
   float score[ngood];
 ```
I run into an assertion failure (for a single wf in the limited matrix `23234.0`):

```console
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/06ca28086ff42d83fe311221dd768eec/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-04-10-2300/src/RecoLocalTracker/SubCollectionProducers/src/TrackClusterRemoverPhase2.cc:156: virtual void {anonymous}::TrackClusterRemoverPhase2::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const: Assertion `s == (*quals).size()' failed.
```
a quick solution would just be to create the arrays `algo` and `score` with size `std::max(1,ngood)` (I tested that it removes all remaining UBSAN warnings in `TrackListMerger`), but I am not sure if that's acceptable or not.

**Comment by mmusich** [comment]
type tracking

**Comment by mmusich** [comment]
> a quick solution would just be to create the arrays algo and score with size std::max(1,ngood) (I tested that it removes all remaining UBSAN warnings in TrackListMerger), but I am not sure if that's acceptable or not.

@cms-sw/reconstruction-l2 any thoughts on this came up in the past 15 days?

**Comment by jpata** [comment]
Naively, why does the assert in TrackClusterRemoverPhase2.cc:156 get triggered? By a quick look, it's comparing the number of tracks (apparently not 0) to the number of quals (which should be 0, because there were no tracks).

**Comment by mmusich** [comment]
> By a quick look, it's comparing the number of tracks (apparently not 0) to the number of quals (which should be 0, because there were no tracks).

this is quite literally what the assertion message is saying. 
I am rather asking if the solution I proposed at https://github.com/cms-sw/cmssw/pull/37384#issuecomment-1095361635 is acceptable.
If not, I would suggest to merge to the PR as it is in its current state because I won't have time to track down the remaining issue and as far as I understand it is already a step forward as the number of errors is decreases (as per https://github.com/cms-sw/cmssw/pull/37384#issuecomment-1082738174)

**Comment by jpata** [comment]
> this is quite literally what the assertion message is saying.

Sure, I'm trying to undestand why?

> If not, I would suggest to merge to the PR as it is in its current state because I won't have time to track down the remaining issue and as far as I understand it is already a step forward as the number of errors is decreased (as per

Sounds fine to me.

**Comment by jpata** [comment]
+reconstruction
- technical, reduces (but does not completely remove) UBSAN warnings in TrackListMerger

**Comment by perrotta** [comment]
please test
(27 days old tests must be refreshed)

**Comment by perrotta** [comment]
+1

**Pull request merged**
