### PR TITLE
Update 14 TeV relval workflows to Pythia8

### PR DESCRIPTION
**Pull request by kpedro88**
This PR updates almost all 14 TeV relval workflows for Phase2 to Pythia8 fragments, and adds a few that were requested.

There were two rather obscure ones with no pythia8 examples in Configuration/Generator, so I left them as pythia6:
LM1_sfts_14TeV_cfi
H200ChargedTaus_Tauola_14TeV_cfi

@bendavid @calabria I absorbed #16497 and #16522 into this more general PR (to avoid conflicts), so you can close those ones.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
```
----- Begin Fatal Exception 09-Nov-2016 18:53:37 CET-----------------------
An exception of category 'DatabaseError ' occurred while
   [0] Processing run: 1
   [1] Calling global beginRun for module LumiProducer/'lumiProducer'
Exception Message:
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 83 on chan 2 failed at Wed Nov  9 18:53:37 2016: -8 [payload.c:101]: Server signalled payload error 1: LumiProd java.sql.SQLException: ORA-00942: table or view does not exist at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:456)) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )
----- End Fatal Exception -------------------------------------------------
```
Pretty sure I did not cause that... @smuzaffar?

**Comment by smuzaffar** [comment]
please test
looks like a glitch on frontier side

**Comment by hengne** [comment]
@kpedro88 did you merged all the changes in PR #16522 ? I see there are 4 commits there, but only see 2 commits here merged from PR #16522 . may be no difference at all, just want to double check with you.

**Comment by hengne** [comment]
@kpedro88 @bendavid @calabria @davidlange6   Would be best to first merge PR #16497 and #16522 and then this PR, and solve all the conflicts here in this PR.

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
test once more, seems to be only some das error or temporary failures when fetching input files.

**Comment by kpedro88** [comment]
@hengne I squashed some of the commits from #16522. It would be best to close #16522 and #16497, since this one already includes those changes. Merging those first will just require multiple rebases.

**Comment by kpedro88** [comment]
@hengne I squashed some of the commits from #16522. It would be best to close #16522 and #16497, since this one already includes those changes. Merging those first will just require multiple rebases.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@smuzaffar the frontier problem seems to be persisting, please advise

**Comment by smuzaffar** [comment]
@kpedro88 , we have reported i here https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3278.html but still do not know the reason behind this

**Comment by kpedro88** [comment]
Okay, thanks. I'll keep an eye on that thread.

**Comment by hengne** [comment]
@kpedro88 from my previous experience, i think no rebase is needed for PR(N) if PR(N) includes PR(N-1) and merged after PR(N-1) .

**Comment by kpedro88** [comment]
@hengne the problem is that #16522 and #16497 conflict with each other. I resolved the conflicts manually when creating this PR that contains both of them. It's pointless to go through that process again.

**Comment by hengne** [comment]
@kpedro88 ok, also makes sense. so, let's focus on working out this PR here, no conflicts in any case for this PR here anyway.  And let the computing/offline side to decide the merging strategy, i believe they will simply click the "close" button for the other two prs if it is more convenient for them.  sounds good for you ?

**Comment by kpedro88** [comment]
@hengne yes, let's just work on this PR here. (I *am* on the offline/computing side, and this topic, upgrade workflows, is specifically my area of responsibility, which is why I put holds on the other PRs until someone closes them. No offense meant to the submitters, I appreciate their help, but it is just easier to coordinate potentially conflicting changes in one PR.)

**Comment by hengne** [comment]
@kpedro88 right, agree, you see, i also don't have the permission to click the "close" buttons, i would have done that already if i have the permission.  

btw, i will need to add another PR on top of yours this week for the 2017 scenarios to have a full list of standard 13 tev workflows (as the default 2016 sets fullsim noPU + PU). will need this PR here to be worked out asap. i will @ you in my later PR for a cross-check.

**Comment by kpedro88** [comment]
@hengne yes, there isn't really a formal/standard procedure for moving a set of workflows from "upgrade" style to "operations" style (or otherwise synchronizing)...

Hopefully the frontier issue gets solved soon so this PR can be approved.

**Comment by hengne** [comment]
@kpedro88 right, we plan to first complete a full set gen segments in the "upgrade structure" for 2017 scenario, and have at least 1 round of full-set relval validation campaign. When everything looks good and gets converged, simply replace the current 2016 workflows in the standard/old/default structure (let's call it "production structure") with the 2017 sim/digi/reco/etc configurations for the future relvals for 2017 data taking /mc production.

**Comment by hengne** [comment]
@kpedro88 at the same time, release circle 90x will come soon, i think it would be best to have these developments on the "upgrade structure" done before the fork of the 90x branch.

**Comment by kpedro88** [comment]
@hengne yes, indeed

**Comment by makortel** [comment]
> simply replace the current 2016 workflows in the standard/old/default structure

Out of curiosity, what will happen to 2016 workflows then?

**Comment by smuzaffar** [comment]
please test
looks like issue is fixed now  https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3278.html

**Comment by hengne** [comment]
@makortel we will keep a couple of "legacy" workflows with 2016 configurations and keep them running in each relval campaign to keep the backward compatibility.

**Comment by perrozzi** [comment]
+1

**Comment by kpedro88** [comment]
@hengne any issues or can you sign?

**Comment by davidlange6** [comment]
Hi @kpedro88 - could you clean up the now obsolete configs in a followup PR? (those now replaced by the new cfis..)?

**Comment by kpedro88** [comment]
@davidlange6 sure - so nobody wants to keep any of the old pythia6 configs around for any reason? (These seem to exist not just for 14 TeV, but also 7/8/13 in many cases...)

**Comment by davidlange6** [comment]
thanks - these are only in the release for relvals - (yes, I guess there were past instances not noticed)

**Comment by hengne** [comment]
@kpedro88 those old pythia6 configs are not needed anymore since mid-2015, i think we have cleaned up all 2015/2016 workflows in the "standard structure" already (unless some of them might be missed.. or for some special reasons),  but we keep some (limited number of) "legacy" 7/8 TeV wfs using pythia6 as some kind of "technique preservation".

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 I'll have a follow up to this one for a few timing group workflows.

**Pull request merged**
