### PR TITLE
Run3-alca216X Bug fix to HcalHBHEMuonANalyzer code in Calibration/HCalCalibAlgos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to HcalHBHEMuonANalyzer code in Calibration/HCalCalibAlgos

#### PR validation:

Tested using test beam data 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please commit

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
