### PR TITLE
L1FinalOR decision in BX-1 and -2 in NANOAOD 

### PR DESCRIPTION
**Pull request by lathomas**
#### PR description:

This PR adds two booleans to NANOAOD (`L1_FinalOR_BXmin1`, `L1_FinalOR_BXmin2`) checking whether the L1 final or was fired in BX-2 or -1 (which would lead the BX0 to be masked by trigger rules). 

#### PR validation:

The NANO steps of workflows  `2500.4`, `141.044` ran succesfully. It was explicitly checked on a few events known to prefire that the boolean decisions are correct.  
 
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

My understanding is that a backport to `13_3_X` is needed for future reNANO of 2022/2023 (?).

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
Hi @lathomas, talks for future reNANOs are ongoing. It would indeed be good to have this change backported to 13_3 as well.

**Comment by lathomas** [comment]
I don't think the reported errors are related to this PR which doesn't touch RECO. @simonepigazzini any thought? Thanks.

**Comment by simonepigazzini** [comment]
I agree, I will retrigger the tests anyway. It won't take long anyway

**Comment by simonepigazzini** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by lathomas** [comment]
Hello @vlimant @simonepigazzini This time the tests succeeded. Can you review the PR and eventually sign off? 

Thanks, 
Laurent

**Comment by simonepigazzini** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
