### PR TITLE
add pixel roc occupancy dqm plots

### PR DESCRIPTION
**Pull request by gouskos**
Add Pixel ROC occupancy plots in ONLINE DQM [both for Barrel and Endcap]
Add Pixel Endcap ROC occupancy for off-track case

### CODE REVIEW

**Review by dmitrijus — APPROVED** [review]

**Comment by dmitrijus** [comment]
81x version of this?

**Comment by dmitrijus** [comment]
found it, https://github.com/cms-sw/cmssw/pull/15821

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
-1
please fix the compiler warnings

**Comment by gouskos** [comment]
Fixed the error after compiling with the following command:
scram b vclean && scram build -k -j 16 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
-1
let us discuss everything in 81x thread

**Comment by fioriNTU** [comment]
Can someone merge this PR please?

**Comment by gouskos** [comment]
@davidlange6 @dmitrijus hello. I updated this PR based on the comments received on the 81X version [#15821] . thank you.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
@dmitrijus @davidlange6  is this PR reasonable now? It would be very useful to have it in the Online release in the coming days.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
