### PR TITLE
 Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Clean unused dependencies from BuildFiles.

Originally part of #39160 by @guitargeek.

#### PR validation:

CMSSW compiles.

#### If this PR will be backported please specify to which release cycle the backport is meant for:

No backport intended.

### CODE REVIEW

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
