### PR TITLE
MTD geometry: add new topology mode, adapt code to it

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

As a follow up of #29207 and #29231 this PR adds a number of updates needed for te integration of the new ETL geometry:

- a new topology mode 5 ```btlv1etlv5``` that corresponds to the latest BTL and the TDR ETL scenario D53. As this potentially breaks the one-to-one correspondence with the ```CrysLayout``` enum of ```BTLDetId```, a ```MTDTopologyMode``` function is provided to give the ```CrysLayout``` corresponding to a given topology mode, and the code using this correspondence is updated so as to keep the previous results unchanged;

- the SpecParSection names are set equal to the file names, as discussed in #29231 ;

- The ```ETLDetId.geographicalId()``` method now gives back just ```ETLDetId``` as it should have already done (the type was 0 up to D50 anyway, and for D53 it is properly taken into account). The Digitization step for D53 now runs, with the ```BTLDeviceSim``` and ```ETLDeviceSim``` code adapted to the changes. We should check any other possible place where hardcoded 0 is assumed for ```ETLDetId.modType()``` and fix it in case (@casarsa @gsorrentino18 FYI).

As a side remark for @casarsa : likely the detId conversion in https://github.com/cms-sw/cmssw/blob/master/SimFastTiming/FastTimingCommon/src/ETLDeviceSim.cc#L42 is not needed, it should be reviewed.

#### PR validation:

test wf 23234.0 runs untile the end, 24434.0 runs for step1 and step2, if fails step3 as ```RecoMTD/DetLayer``` needs still to be adapted. The validation tests for the various MTD geometry packages run and give unchanged results for D50, and show the new topology mode (but no other change) for D53.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+dqm

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@silviodonato the update pf MtdValidation by @gsorrentino18 in #29275 is i conflict with my samll update. I will refresh this PR and relaunch the tests.

**Comment by fabiocos** [comment]
simple rebase onto CMSSW_11_1_X_2020-03-24-2300 , no other change (i.e. ```BtlRecHitsValidation``` renamed to ```BtlLocalRecoValidation```)

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29270	289ec0b 
- technical for reco
- there are no (relevant) changes in comparisons

**Comment by fabiocos** [comment]
@civanch comments? Doubts? The update to SimFastTiming is not changing anything in old scenarios, as the module type is always 0 there

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
