### PR TITLE
More diagnostic plots for CSC trigger primitives in validation step

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

New class to plot CSC TP position and bending resolutions in release validation. Plots are made for CLCT bending resolution, and CLCT 1/2-strip, 1/4-strip and 1/8-strip resolution. The latter two only make sense for chambers that have the CCLUT algorithm enabled (MEX/1 in the baseline commissioning model). 

I also added diagnostic plots for ALCT, CLCT, CLCT pre-trigger, and LCT for each chamber type and for each endcap (sometimes we see asymmetries in the performance). I borrowed a lot of code from the L1T CSC DQM tools which I wrote earlier this year. I organized the plots by object, and by type of plot, so it's not all in one directory. The screenshot below shows the directory structure (tested on 100 1TeV muon events). Not every object has each type of plot. E.g. I don't have resolution plots for ALCTs.

Screen Shot 2021-09-22 at 4 39 39 PM

This PR is part of an investigation into the EMTF performance for 1 TeV muons with Run-3 CSC trigger primitives. 

#### PR validation:

Ran 1000 events from ```/RelValSingleMuPt1000/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM-DIGI-RAW``` with 
```
cmsRun Validation/MuonCSCDigis/test/runCSCDigiValidation_cfg.py
cmsRun Validation/MuonCSCDigis/test/runCSCDigiHarvesting_cfg.py
```

Plots should automatically appear in ```MuonCSCDigisV/CSCDigiTask/Stub/Resolution/```. I added a few examples below

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N.A.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

FYI @ptcox @AFJohan92

### CODE REVIEW

**Comment by dildick** [comment]
Examples of position resolutions (ME1/a and ME1/b are split up)

Screen Shot 2021-09-17 at 10 06 01 PM

Screen Shot 2021-09-17 at 10 06 10 PM

Screen Shot 2021-09-17 at 10 05 54 PM

Screen Shot 2021-09-17 at 10 05 47 PM

Screen Shot 2021-09-17 at 10 05 39 PM

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
@jfernan2 Tests look good.

**Comment by jfernan2** [comment]
OK, @dildick though I wonder why small differences appear in BeamMonitor for wf 10224
https://tinyurl.com/ygvkubw6

**Comment by dildick** [comment]
I don't think it's related. These plots do not affect the primary vertex collection.

**Comment by jfernan2** [comment]
I know, just trying yo understand. If you don't mind I will retrigger the tests to see if this is decoupled.
In the meantime, does this PR indeed help to underdstand the issue at high eta and 1TeV muons seen in HLT?

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
It might. But if the key positions are shifted such that the average shift is 0, then we may not see anything. If there is a systematic shift of +1 or -1 halfstrips, it would be clear instantly.

Even better would be to have actual ALCT/CLCT/LCT validation plots for MC production. the `CSCALCTDigiValidation` and `CSCCLCTDigiValidation` provide some features, but it's mainly timing and number of TPs per event. What we should have are distributions for wiregroup, 1/2-strip, 1/4-strip, 1/8-strip, Run-2 pattern ID, Run-3 pattern ID, Run-3 slope (if applicable), comparator code (if applicable), quality, bending, split up per station and per endcap. Basically, the plots I have already in the L1T CSC DQM (https://github.com/cms-sw/cmssw/blob/master/DQM/L1TMonitor/src/L1TdeCSCTPG.cc). I would have to extend `CSCALCTDigiValidation` and CSCCLCTDigiValidation`, and introduce a class for LCTs `CSCCorrelatedLCTDigiValidation`. With that in place in standard workflows, any difference in CSC TP properties would be flagged. EMTF, OMTF, uGMT and others would benefit from such diagnostic tools.

Javier, I'll just go ahead and add those plots to the standard CSC TP validation. We really should have those for Run-3 and Phase-2. Once implemented I can ask a student to run the cmsRun configurations on these two datasets ```/RelValZMM_14/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM-DIGI-RAW``` and ```/RelValZMM_14/CMSSW_12_0_0_pre6-120X_mcRun3_2021_realistic_v4-v1/GEN-SIM-DIGI-RAW``` and get back to you.

**Comment by dildick** [comment]
@jfernan2 Done. I added diagnostic plots for ALCT, CLCT, CLCT pre-trigger, and LCT.  I borrowed a lot of code from the L1T CSC DQM tools which I wrote earlier this year. I also organized the plots by object, and by type of plot, so it's not all in one directory. The screenshot below shows the directory structure. Not every object has each type of plot. E.g. I don't have resolution plots for ALCTs.

Screen Shot 2021-09-22 at 4 39 39 PM

There used to be a strip resolution plot. The implementation did not make any sense. Histograms were only being filled when there is a single strip digi in a CSC layer. But that is never the case by design. In the simulation, each CFEB with hits will produce exactly 16 strip digis, each having a pedestals and amplitudes. To get an idea of the position resolution along the local-x axis, I move this part the comparator validation code. There can be 1 comparator digi in a CSC layer, e.g. ME+1/2/4/6 (6th layer of the 4th ME1/1 chamber in the positive endcap) with a single comparator digi. Those plots are now being filled and make sense.

@ptcox FYI I'm adding more diagnostics in the CSC digi validation step to better understand issues with TeV muons at the local trigger level.

**Comment by dildick** [comment]
A few validation plots (on 1000 1TeV muons) 

Screen Shot 2021-09-22 at 5 29 55 PM
Screen Shot 2021-09-22 at 5 30 05 PM
Screen Shot 2021-09-22 at 5 31 38 PM
Screen Shot 2021-09-22 at 5 31 51 PM
Screen Shot 2021-09-22 at 5 31 58 PM
Screen Shot 2021-09-22 at 5 32 09 PM
Screen Shot 2021-09-22 at 5 32 22 PM
Screen Shot 2021-09-22 at 5 32 29 PM
Screen Shot 2021-09-22 at 5 32 38 PM
Screen Shot 2021-09-22 at 5 32 46 PM
Screen Shot 2021-09-22 at 5 32 55 PM
Screen Shot 2021-09-22 at 5 33 12 PM

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
Just one more thing, I'm going to add an option in the validation step to skip SIM step (by default off though), so that I don't have to run the mixing module to validate the key properties of ALCT, CLCT and LCT. I won't have efficiencies or resolutions in that case, but at least it will run very fast and provide results quickly.

**Comment by dildick** [comment]
I also modified the harvesting configuration so that it produces a DQM output file like ```DQM_V0001_R000000001__RelValZMM_14__120X_mcRun3_2021_realistic_v2__CMSSW_12_1_X_2021-09-16-2300.root```

**Comment by dildick** [comment]
@jfernan2 With the doSim=False option I'm able to quickly get the plots for 1TeV muons in CMSSW_12_0_0_pre4 and CMSSW_12_0_0_pre6 in DQM files. Just need a simple python analysis tool that puts it all together in a PDF.

**Comment by dildick** [comment]
@jfernan2 The baseline code for this PR is good enough. I may end up putting the

I have a PDF, ~400 pages long, with the plots I need. I have a script to leave out plots for which the KS-test result between the reference and the new histogram is too small to be a likely outlier. Even with a KS cut, there are still too many plots to understand differences. I will reprocess the CMSSW_12_0_0_pre4 digis in CMSSW_12_0_0_pre6 in order to compare the trigger primitives.

[CSC_test.pdf](https://github.com/cms-sw/cmssw/files/7220289/CSC_test.pdf)

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick there is a compilation warning to fix:
Validation/MuonCSCDigis/src/CSCStripDigiValidation.cc:55:9: warning: unused variable 'detId' [-Wunused-variable]

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
It seems stuck like in other PR, let's try again

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick now the PR is adding ~500 new plots, if this goes to production I am not sure who is going to monitor them... would it make sense to restrict only to those significant to research the problem? 
I am not sure of the strategy, could you please elaborate it a bit more? 
Thanks

**Comment by dildick** [comment]
Well, there are 9 different chamber types, each of which has different performance for the trigger primitives. There are two endcaps (sometimes performance is not symmetrical). There are 3 types of primitives ALCT, CLCT and LCT.  Each has several data members. It sums up to several hundred plots, indeed. However, it's all organized into directories. Hopefully they will actually help with debugging the endcap muon trigger performance throughout Run-3 and Run-4. At the moment there are no plots at all in release validation.

**Comment by dildick** [comment]
I could remote "quartstripbit" and "eighthstripbit" for CLCT and LCT. That would save 2 x 2 x 18 plots.

**Comment by dildick** [comment]
In addition, what options are there in CMS DQM to only display the ones that have differences?

**Comment by jfernan2** [comment]
The option is to use the DQM BInByBin tool, which is what the Jenkins test does here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-27-2300+f3372e/45801/dqm-histo-comparison-summary.html

and that you can run on any DQM root file standalon:
https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/scripts/compareDQMOutput.py
and it creates a web page like the one above after uploading the differences to the development DQM GUI

**Comment by jfernan2** [comment]
So, if these new plots are needed to stay. fine.
If you just need them to debug the high eta issue at large pT muons, perhaps it would be great to just run a 1TeV gun sample standalone with these plots with and w/o some changes, and debug them using compareDQMOutput.py tool above

**Comment by dildick** [comment]
Hi @jfernan2, yes I would like these plots to stay. There are a lot of plots, but the CSC trigger is also pretty complicated. Those plots should have been in release validation years ago. At the moment I am using the plots to debug the high pT muon issue. Assuming that will be fixed soon, I still need those plots in there for future debugging. I am not using compareDQMOutput, but I wrote a simple script that dumps all plots that are substantially different to a postscript file.

**Comment by jfernan2** [comment]
> I could remove "quartstripbit" and "eighthstripbit" for CLCT and LCT. That would save 2 x 2 x 18 plots.

OK, could you then remove these ones or just if necessary? Thanks for your colaboration

**Comment by dildick** [comment]
Yes, in principle we can validate the quartstripbit and eighthstripbit by looking at the corresponding quartstrip and eighthstrip. If there are differences in those plots, they originate from  quartstripbit and eighthstripbit. I will push an update.

**Comment by jfernan2** [comment]
Thank you!!

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
I was able to run WF 11634.0
```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Sep 29 11:31:25 2021-date Wed Sep 29 11:13:08 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```
quartstripbit and eighthstripbit plots were removed.
I added a plot for the pre-CLCT CFEB, but removed pre-CLCT pattern, bending, and quality. Overall, a reduction in number of 108 plots.

**Comment by jfernan2** [comment]
+1
~400 new MEs added accounting for ~200KiB in memory, they are needed for trigger primitives validation

**Comment by dildick** [comment]
@qliphy Can you sign off, please?

**Comment by qliphy** [comment]
+1

**Comment by Dr15Jones** [comment]
It seems highly likely that this change introduced a call to a thread-unsafe ROOT function which is causing jobs in the IB RelVals to fail with
```
----- Begin Fatal Exception 02-Oct-2021 09:15:32 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'validation_step'
   [2] Calling method for module CSCDigiValidation/'cscDigiValidation'
   Additional Info:
      [a] Fatal Root Error: @SUB=TF1::AddToGlobalList
Function is supposed to be in the global list but it is not present

----- End Fatal Exception -------------------------------------------------
```

**Comment by dildick** [comment]
@Dr15Jones It's not obvious to me which ROOT function is doing that. If you have an idea, let me know, and I will try to address it.

**Comment by Dr15Jones** [comment]
The problem is almost certainly here

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/Validation/MuonHits/src/CSCSimHitMatcher.cc#L239-L240

See #18370 for the resolution of the same problem.

**Comment by dildick** [comment]
I will submit a fix.

**Pull request merged**
