### PR TITLE
DeepCore model 2.2.1 CMSSW_13_3_0_pre3 (fixed comments)

### PR DESCRIPTION
**Pull request by bouchamaouihichem**
#### PR description:

This PR updates the model used when ```--procModifiers seedingDeepCore``` is used in CMSSW workflows. The DeepCoreSeedGenerator.cc file is updated with the new model path as well as new prediction thresholds. This PR depends on [another PR](https://github.com/cms-data/RecoTracker-TkSeedGenerator/pull/3), which will add the DeepCore 2.2.1 model.

Relevant Links:

- [Track POG Update 09/11/2023](https://indico.cern.ch/event/1315747/contributions/5553878/attachments/2712109/4709601/DeepCore_TrackPOG_23_0911.pdf)
- [DeepCore 2 Website](https://hboucham.web.cern.ch) (includes testing workflows and documentation)
- [DeepCore 2 repository](https://github.com/bouchamaouihichem/DeepCore)

#### PR validation:

Workflows 11923.17/0 and 11834.17/0. More details provided in the slides of [Track POG Update 09/11/2023](https://indico.cern.ch/event/1315747/contributions/5553878/attachments/2712109/4709601/DeepCore_TrackPOG_23_0911.pdf) and all the plots are in [DeepCore 2 Website](https://hboucham.web.cern.ch).

### CODE REVIEW

**Comment by slava77** [comment]
@bouchamaouihichem 
for the future, please first try to update a PR instead of making a new one.
This loses past relevant review comments.

**Comment by slava77** [comment]
test parameters:
-  workflow = 11723.17
-  pull_request = cms-data/RecoTracker-TkSeedGenerator#3

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
+1
Changes to comparisons for the dedicated deepCore relVal workflow are consistent with a modest change to the tracking, as would be expected for an updated training.

**Comment by antoniovilela** [comment]
ping bot

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
