### PR TITLE
Framework code format

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

The first commit includes only changes from scram build code-format-all and nothing else. I included here core packages that I will be changing in my concurrent IOV pull request, because I want to rebase that on top of this. More PRs for other core packages coming soon.

There were a few addition changes that showed up in code-checks. I had to manually fix one line to get it to compile.

#### PR validation:

The only test I performed was checking that the revised packages compile and build.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@wddgit @smuzaffar the need for a manual adjustment in the third commit is due to a failure of clang-tidy I would say, not clang-format, am I correct?

**Comment by wddgit** [comment]
Yes. It was clang-tidy that created the problem.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
