### PR TITLE
Exotica dqm updated histograms

### PR DESCRIPTION
**Pull request by aescalante**
Updated charge cuts to deal with 0T conditions, updated range of some histograms, updated constrains in dijet and diphoton histograms to reduce background and added histograms to monitor dijet an wprime tails

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @aescalante 
are the corresponding PR for 75 and 76 there?
thanks,
F.

**Comment by aescalante** [comment]
I have just created two additional pull request for 75 and 76 with the propagated changes. #11357 #11358

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
it looks like the GT used by the Tier0 does not include the JEC needed by this PR. The AlCa team does not have the conditions needed, so for the moment, we will revert this PR.

**Comment by aescalante** [comment]
I can remove the JEC if needed to avoid this kind of problems.
Alberto.

**Comment by aescalante** [comment]
note that #PR1357 #11358 are committed on top of the changes in this PR, so they should be reverted/cancelled in that case.

**Comment by diguida** [comment]
@aescalante 
I see that [here](https://github.com/cms-sw/cmssw/pull/11216/files#diff-5565cdf5eed227fb02aa7907e1ae872bR20) you changed the quantity requested to the JEC from `L1FastL2L3` for PF jets with anti-kT 0.4 to `L1FastjetCorrector` for PF charge-hadron subtracted jets with anti-kT 0.4. Most likely, they are not provided by the current JEC in the GT.
I have dumped the values in prompt and re-reco GT:
* in prompt, still containing old JEC, where the crash happens, I find these keys:
````
L2Relative=1,
L3Absolute=2,
L2L3Residual=8,
Uncertainty=9,
L1FastJet = 10,
````
* in re-reco, updated to the new JEC for Summer15, where the crash *did* not happen in the release integration, I find:
````
L2Relative=1,
L3Absolute=2,
L2L3Residual=8,
L1FastJet = 10,
````
So, apart from the uncertainty, the same keys are available in both payloads.

Am I missing something?

@mmusich this is something you might want to watch as well

**Comment by aescalante** [comment]
Thanks for the help @diguida 

Yes I changed that because at some point I had some problems running locally in data and I thought that was problematic and the change was the solution, but it seems that the proposed change is problematic.

So I can go back to the "old" configuration if its ok or I can also drop the JEC since Exotica is not validating the JEC and the validation can work without them.

Alberto

**Comment by diguida** [comment]
@aescalante 
As found by @blinkseb , it is an issue with python configuration.
Please follow the discussion in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2028.html

**Comment by deguio** [comment]
@aescalante 
while the discussion is ongoing:
- I have removed my 'plus1' in PR #11357 since wasn't merged yet
- please revert #11358 . there must be a button on the bottom of the PR that does the trick.

for the reverted PRs you will need to resubmit them again with the fix on top.
thanks,
F.

**Comment by aescalante** [comment]
ciao @deguio 
Done, I have reverted #11358 I will make new PRs once there is an outcome of the discussion. 
Alberto.

**Comment by aescalante** [comment]
Hi all, finally how can we proceed with this PR?? Should I remove the JEC from the PR or change the way I get them (to the way I used to do it before)?

Alberto.

**Pull request merged**
