### PR TITLE
Use C++ concepts for InputProcessBlockCacheImpl

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Switched from SFINAE to concepts to enforce the type requirements.

#### PR validation:

Code compiles. Test using compiler explorer show the mechanism works as expected.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@wddgit This might interest you (the changes look fine to me).

**Comment by wddgit** [comment]
It is interesting. Something new. Looks like it ought to work.

**Comment by makortel** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
