### PR TITLE
TECRing7 +/- 1.33 mm Scenario added

### PR DESCRIPTION
**Pull request by eavdeeva**
backport of 7070
#7070

TECRing7 plus and minus 1.33 mm Scenarios added (plain TECRing7-moved scenarios and TECRing7+LS1BPixRepair)

### CODE REVIEW

**Comment by ktf** [comment]
@diguida, @mmusich ping. Is this still needed?

**Comment by diguida** [comment]
@ktf This is a backport, and it has been used for the correction of the TEC R7 fix with AlCaReco produced in that release, @mmusich to confirm.
If so, I'd prefer it in.

**Comment by diguida** [comment]
+1

**Comment by mmusich** [comment]
@ktf @diguida. Yes please this is needed because the Tracker alignment group has MC AlCaReco in 7.2.X and 7.0.X. So please re-open #7075

**Comment by davidlange6** [comment]
+1

**Pull request merged**
