### PR TITLE
Change CICADA model to be function local

### PR DESCRIPTION
**Pull request by aloeliger**
#### PR description:

This PR changes the L1T CICADA function model to be local the function where it is used, where it is hoped that the potential bug seen in https://github.com/cms-sw/cmssw/issues/44435, https://github.com/cms-sw/cmssw/pull/44397, https://github.com/cms-sw/cmssw/pull/44433. No change is expected to CICADA, however it is hoped that Trigger changes for AXOL1Tl might be seen (becoming more reasonable and removing the possible collision issue).

#### PR validation:

All code compiles and has had code formatting applied. Trigger results testing needs to be tested in conjunction with other PRs here (potentially).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport, but if it proves to solve the issue, should be backported immediately.

### CODE REVIEW

**Comment by aloeliger** [comment]
@artlbv @mmusich FYI

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@artlbv @mmusich 

- 141.044: [Removes all AXOL1TL events](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-15-2300+67d8c5/61719/triggerResults/141.044_RunJetMET2023D/reHLT.log)

**Comment by fwyzard** [comment]
Please rename all data members to follow CMS conventions: [2.9](https://cms-sw.github.io/cms_coding_rules.html#2--naming-rules-1):

> Start data member names with lower case. A trailing `_` is the preferred method to distinguish a data member from the getter method (e.g. `momentum_`).

**Comment by fwyzard** [comment]
what is the impact of the job timing / throughput of creating an `hls4mlEmulator::ModelLoader` object and loading the model for every event ?

**Comment by fwyzard** [comment]
These changes are a random attempt, without any justification based on an understanding of the C++ standard and the `dlopen` semantics.

It basically amount to reshuffling the order in which libraries are loaded in the hope that the right symbol is used in the right place.

Whether this works or not in a specific case, there is not guarantee that the same problem will not resurface after any other random changes; for example, changing the order in which the CICADA and AXO models are used with the job.

Please go back to the design stage, and implement a more robust approach for using HLS4ML models in CMSSW.

**Comment by aloeliger** [comment]
Obsolete in favor of https://github.com/cms-sw/cmsdist/pull/9087

**Pull request closed without merging**
