### PR TITLE
EgammaTools - empty classes to free functions and ConversionInfo to struct

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another of the occasional quick PRs where the member functions of classes without data members get converted to free functions, so these classes don't have to be instantiated.

Besides, I realized that the ConversionInfo class was basically just an immutable data structure, so this is made explicit by turning it into a struct with const members only, also avoiding some "magic" 9999 literals. I want to showcase that not everything has to be a class, and getters/setters are not always needed:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-get

#### PR validation:

Local matrix tests pass.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- The PR integrates what stated in the description
- Jenkins tests pass with no changes, as expected

**Comment by pohsun** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald objections?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
