### PR TITLE
Validation/RecoEGamma PF Cluster Iso v1

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

Monitoring of the hcalPF isolation and ecalPF isolation, which are important ingredients of the photon/electron ID at HLT, and which should also be monitored at the RECO level. These quantities are also likely to be used for the (offline) ID criteria for Run 3.
The monitoring of the "extended" region (2.5<|eta|<3) has also been added. 

Modifications are made on the following files :
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc 
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.h 

Some other small (they do not concern the extended eta range) modifications are made on :
Validation/RecoEgamma/test/ElectronMcSignalValidation_gedGsfElectrons_cfg.py
Validation/RecoEgamma/python/ElectronMcSignalPostValidator_cfi.py
Validation/RecoEgamma/test/electronValidationCheck_Env.py 

This can be viewed with the following pictures:
for hcalPFClusterIso
h_ele_hcalPFClusterIso

ecalPFClusterIso
h_ele_ecalPFClusterIso

and the Extended version with extended eta range
h_ele_ecalPFClusterIso_Extended

#### PR validation:

compilation is OK, basics tests (scram b runtests or local tests) are OK too.

runTheMatrix.py -l limited -i all --ibeos tests are fine
50 49 48 35 18 4 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed

@beaudett @swagata87

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by swagata87** [comment]
@cmsbuild  please test

**Comment by archiron** [comment]
it seems that errors are not due to the modification but to some time out or "failed to parse X509 proxy".

**Comment by archiron** [comment]
it seems that errors are not due to the modification but to some time out or "failed to parse X509 proxy".

**Comment by emanueleusai** [comment]
Indeed... let's retest

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
