### PR TITLE
ECAL GPU unpacker - Add detection of corrupted DCC tower headers and recovery - backport 12_2_X

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/37430

Up to now the ECAL GPU unpacker did not check the DCC tower headers consistency when using it. A corrupted header with tower block length extracted as 0 leads to an infinite loop.

This PR fixes this by first building a list of FE channels that are expected to contain data and checking the TT id extracted from the tower header against it. In case of a mismatch the tower block is skipped and the next good tower header is searched in the raw data. The unpacking then continues with the tower block with the next good header.

This PR fixes https://github.com/cms-sw/cmssw/issues/37323.

#### PR validation:

No infinite loop anymore with the configuration and data described in https://github.com/cms-sw/cmssw/issues/37323.

### CODE REVIEW

**Comment by thomreis** [comment]
type bugfix

**Comment by jpata** [comment]
enable gpu

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- an exact backport of https://github.com/cms-sw/cmssw/pull/37430, needed for datataking
- no relevant reco changes
- I didn't check explicitly that the bug was fixed also in the backport, relying on the tests done in the original PR

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/37430

**Comment by fwyzard** [comment]
@perrotta would it be possible to have a new 12.2.x (patch) release with this fix, so it can be deployed at HLT ?

**Comment by fwyzard** [comment]
@mzarucki FYI

**Comment by perrotta** [comment]
@fwyzard I started building CMSSW_12_2_3_patch1

**Comment by fwyzard** [comment]
Thanks @perrotta :+1:

**Pull request merged**
