### PR TITLE
L1T DQM Allow minBias bit comparison failure if ET=0 10_0_X

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes a corner case in which HCal zero-suppressed readout does not contain information about the minBias feature bit in TPs, whereas the bit is sent to CaloLayer1 even if ET=0, raising a mismatch error.

backport of #22645

### CODE REVIEW

**Comment by nsmith-** [comment]
backport of #22645 
guess it has to be first line or else

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by nsmith-** [comment]
Online DQM has moved to 10_1_X, this is no longer necessary.

**Pull request closed without merging**
