### PR TITLE
Update the HLT customisation for running over 2018 data

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the HCAL customisation for running the latest GRun HLT menu over 2018 data (and MC), with the Phase-0 HCAL barrel.

#### PR validation:

Check that the GRun menu can be run over 2018 data.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
type bug-fix

**Comment by fwyzard** [comment]
+hlt

**Comment by qliphy** [comment]
+1

**Pull request merged**
