### PR TITLE
Clean some more BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/32030).

This PR deals with some BuildFiles that were not processed by the BuildFile cleaning script so far and revisits some BuildFiles in the reco area that can be cleaned further after https://github.com/cms-sw/cmssw/pull/32266.

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
Are the changes in recoConversions for the Phase 2 D49 workflow caused by this PR?
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_recoConversions_allConversions__RECO_obj_nTracks

**Comment by jpata** [comment]
good catch, it does seem like that, since this PR was the only one in the test?

**Comment by kpedro88** [comment]
An alternative could be some inherent instability (uninitialized memory etc.), but I haven't observed that before for these particular plots.

**Comment by guitargeek** [comment]
I don't think this PR responsible for that. The differences are apparent in many PRs right now, e.g.:
https://github.com/cms-sw/cmssw/pull/32326
https://github.com/cms-sw/cmssw/pull/32327

**Comment by kpedro88** [comment]
thanks for checking @guitargeek - I opened #32338 to track this problem

**Comment by kpedro88** [comment]
+upgrade

**Comment by jpata** [comment]
+reconstruction

- technical, removes unneeded imports in a few BuildFiles (and rearranges in CalibTracker/SiStripLorentzAngle)
- no reco changes as expected (only irrelevant ones in 23434.0)

**Comment by silviodonato** [comment]
kind reminder 
@cms-sw/alca-l2 @cms-sw/l1-l2

**Comment by silviodonato** [comment]
kind reminder 
@cms-sw/alca-l2 @cms-sw/l1-l2

**Comment by yuanchao** [comment]
+1
* modifications only on BuildFiles, no compiling error caused
* matrix tests and unit tests passed

**Comment by guitargeek** [comment]
Hi @rekovic, is this okay for L1?

**Comment by silviodonato** [comment]
merge
@cms-sw/l1-l2 please let us know

**Pull request merged**
