### PR TITLE
Move SiStrip calibration DQM modules back to Sequence

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a follow-up to #29630 and reverts the changes made to SiStrip calibration DQM modules by moving them back to Sequences, i.e. to be run only if the preceding filters keep processing the event.

#### PR validation:

Limited matrix runs, expecting changes in SiStrip AlcaReco DQM plots.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1
Since Tracker approved these changes accoording to:
https://github.com/cms-sw/cmssw/pull/29630#issuecomment-623905262

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
