### PR TITLE
Hlt tau trigger validation update92x 18102017

### PR DESCRIPTION
**Pull request by slehti**
Backported a number of commits from 94X to 92X to have the HLTTau DQM updates available also in 92X.

This is basicly the same PR as #20916, but now the code is cherry picked instead of copying files, and contains more commits than only #20613.

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
So, question, can you link the pull request which added the "extra changes" to the master branch?

**Comment by slehti** [comment]
The extra changes came from these two commits:

commit 08aa7e7184f431f1f5f35f03852277e99c2e95fe
Author: Christopher Jones <chrisdjones15@gmail.com>
Date:   Thu Jun 15 08:34:38 2017 -0500

    Module labels are not allowed to contain underscores

    It has always been the case that module labels are not suppose to contain
    underscores. However, that is only enforced for EDProducers. With the
    change to DQMEDHarvester now inheriting from EDProducer, all harvesting
    modules must conform to the proper naming convention.



commit 6fb1e35a3c98b332cb4761d12fe4a970a0e942da
Author: Andrea Bocci <fwyzard@gmail.com>
Date:   Wed Jul 26 02:44:44 2017 +0200

    cleaned up by clang-tidy 4.0.0 modernize checks

    Enabled checks:
        boost-use-to-string
        cppcoreguidelines-no-malloc
        google-build-explicit-make-pair
        misc-inefficient-algorithm
        misc-string-compare
        modernize-avoid-bind
        modernize-deprecated-headers
        modernize-loop-convert
        modernize-make-shared
        modernize-make-unique
        modernize-pass-by-value
        modernize-redundant-void-arg
        modernize-replace-auto-ptr
        modernize-shrink-to-fit
        modernize-use-auto
        modernize-use-bool-literals
        modernize-use-emplace
        modernize-use-equals-default
        modernize-use-equals-delete
        modernize-use-nullptr
        modernize-use-override
        modernize-use-transparent-functors
        modernize-use-using
        performance-faster-string-find
        performance-for-range-copy
        performance-implicit-cast-in-loop
        performance-inefficient-string-concatenation
        performance-type-promotion-in-math-fn
        performance-unnecessary-copy-initialization
        performance-unnecessary-value-paramnnSee http://releases.llvm.org/4.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html for details.

**Comment by dmitrijus** [comment]
Thanks for clarifying :)

So, PRs: https://github.com/cms-sw/cmssw/pull/19247 and https://github.com/cms-sw/cmssw/pull/19917

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
