### PR TITLE
add monitoring of tracks stopping source

### PR DESCRIPTION
**Pull request by mtosi**
this PR is meant to add monitoring plots for the stopping source

3 plots (1 1D and 2 2D) are added in the general properties directories
3 plots (1 1D and 2 2D) x each step of the iterative tracking are added in the TrackBuilding directory

the 1D plot has 10bins (one per source type)
the 2D plots give this info as function of the track eta and phi, respectively (using the usual eta and phi binning)

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by mtosi** [comment]
for both this PR and https://github.com/cms-sw/cmssw/pull/13593
what should I do ?

thanks

**Comment by VinInn** [comment]
not sure, @davidlange6 , what is the procedure for getting PRs against 8_0_0 to be tested?

**Comment by smuzaffar** [comment]
I am manually start the tests based on CMSSW_8_0_0_patch3

**Comment by VinInn** [comment]
errors unrelated

**Comment by davidlange6** [comment]
please reopen on 80x if needed

**Pull request closed without merging**
