### PR TITLE
Monitor seed stopping reason and number of trajectory candidates per seed in tracking DQM

### PR DESCRIPTION
**Pull request by makortel**
This PR
* enables the seed stopping reason by default (introduced in #17792 as optional) in `CkfTrackCandidateMakerBase`
  * add new stopping reason (`SEED_REGION_REBUILD`) whose possibility was omitted earlier
* extends the saved information with the number of trajectory candidates per seed (those that the `maxCand` parameter controls)
  * done by adding new transient class `SeedStopInfo` and storing the stop reason and this number there
* add monitoring of both stop reason and number of candidates per seed to tracking DQM
* in addition some minor cleanup + code style checks

Tested in 9_3_0_pre5, expecting only new histograms and no changes in existing quantities or plots.

@rovere @VinInn @mtosi

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- New functionality enabled
- Jrnkins tests show no effect on reco quantities, as expected

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
