### PR TITLE
2017 Overlaps Fix

### PR DESCRIPTION
**Pull request by ianna**
- Remove Tracker overlap with Beampipe
- Use 2015 dev Castor as prod in 2017
- Add Pixel nose to 2017
- Synchronize all 2017 scenarios

Note: based on fully signed https://github.com/cms-sw/cmssw/pull/15833, https://github.com/cms-sw/cmssw/pull/16050, and https://github.com/cms-sw/cmssw/pull/16087

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by Dr15Jones** [comment]
Could this change be causing this crash?
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_NONTHREADED_X_2016-10-07-1100/pyRelValMatrixLogs/run/136.7321_RunZeroBias2016BnewL1repack+RunZeroBias2016BnewL1repack+HLTDR2newL1repack_2016+RECODR2newL1repack_2016reHLT_HIPM+HARVESTDR2/step3_RunZeroBias2016BnewL1repack+RunZeroBias2016BnewL1repack+HLTDR2newL1repack_2016+RECODR2newL1repack_2016reHLT_HIPM+HARVESTDR2.log

It happens in the threaded and non-threaded IB

**Comment by Dr15Jones** [comment]
Ignore my previous comment, the problem is MUCH more likely to be another pull request which actually changed the module which is crashing :).

**Pull request merged**
