### PR TITLE
Make MonitorElement to emit LogWarning instead of writing to std::cout

### PR DESCRIPTION
**Pull request by dmitrijus**

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by davidlange6** [comment]
-1

**Comment by dmitrijus** [comment]
Hi @davidlange6,
this should be merged, eventually.

I changed LogInfo to LogWarning. Either way, this is preferred to std::cout.

**Comment by davidlange6** [comment]
for 91x

**Pull request closed without merging**
