### PR TITLE
DQM GT to 112X in view of MWGR

### LINKED ISSUE #32796: Failures in two L1 TestDQMOnlineClient unit tests
Two unit tests in `DQM/Integration` package are failing since CMSSW_11_3_X_2021-02-02-1100
```
----- Begin Fatal Exception 02-Feb-2021 16:05:10 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 334393 stream: 0
   [1] Calling method for module L1TStage2uGT/'l1tStage2uGT'
Exception Message:
No "L1TGlobalPrescalesVetosFractRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
..
---> test TestDQMOnlineClient-l1tstage2_dqm_sourceclient had ERRORS

----- Begin Fatal Exception 02-Feb-2021 16:05:10 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 334393 stream: 0
   [1] Calling method for module L1TStage2uGT/'l1tStage2uGtEmul'
Exception Message:
No "L1TGlobalPrescalesVetosFractRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
---> test TestDQMOnlineClient-l1tstage2emulator_dqm_sourceclient had ERRORS
```
http://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-02-1100/unitTestLogs/DQM/Integration

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fixes https://github.com/cms-sw/cmssw/issues/32796

following comment:

https://github.com/cms-sw/cmssw/issues/32796#issuecomment-771937851

Tested that the issue above is solved

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
FYI @rekovic

**Comment by mmusich** [comment]
shouldn't something similar be done also for:

https://github.com/cms-sw/cmssw/blob/2dc7c8c99ef80efaba11bcd9549ae4c527d7631c/DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py#L10

(as a fallback protection during operations)?

**Comment by jfernan2** [comment]
Thanks @mmusich 
Certainly yes, we are waiting for the GT to be used in the next MWGR in express and prompt

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test
Now in 112X

**Comment by silviodonato** [comment]
Thank you for the fix. 
We need a similar PR also in 11_3_X (the unit tests are failing both in 11_3 and 11_2)

**Comment by jfernan2** [comment]
OK @silviodonato however it is not clear to me if we should use the 112X GT in 113X too, indeed AlCaDB is still working on a candidate for express and prompt GTs:

https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4373.html

**Comment by silviodonato** [comment]
urgent 
for the MWGR

**Comment by christopheralanwest** [comment]
> Thanks @mmusich
> Certainly yes, we are waiting for the GT to be used in the next MWGR in express and prompt



> OK @silviodonato however it is not clear to me if we should use the 112X GT in 113X too, indeed AlCaDB is still working on a candidate for express and prompt GTs:
> 
> https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4373.html

You can use the `112X_dataRun3_Express_v2 ` GT for the express GT and `112X_dataRun3_Prompt_v2` for the prompt GT. These are likely to be the GTs used for the upcoming MWGR. There are no new features in 113X that are not present in 112X so for now we simply use the 112X GT for both 11_2_X and 11_3_X.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Tested at P5 with DQM Online

**Comment by silviodonato** [comment]
+1

**Pull request merged**
