### PR TITLE
Updates to HCAL Run 3 conditions

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR performs several updates to HCAL conditions for Run 3.

HB and HE have been recalibrated using isolated tracks. The energy scale needed adjustment after changes to the local HCAL reconstruction since 2019 and an asymmetry in the HB-HE transition region is fixed. The HcalRespCorrs are updated for all Run 3 scenarios.

In addition, `HcalSiPMParameters`, `HcalPedestals`, and `HcalPedestalWidths` have been updated for 2021 scenarios

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2021_design_v4/112X_mcRun3_2021_design_v1 

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2021_realistic_v4/112X_mcRun3_2021_realistic_v1

**2021 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2021cosmics_realistic_deco_v4/112X_mcRun3_2021cosmics_realistic_deco_v1 

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2021_realistic_HI_v5/112X_mcRun3_2021_realistic_HI_v1

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2023_realistic_v4/112X_mcRun3_2023_realistic_v1 

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun3_2024_realistic_v4/112X_mcRun3_2024_realistic_v1 

#### PR validation:

See the June 8 AlCaDB meeting (https://indico.cern.ch/event/927125/) and HN followup (https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4305/1/1.html) for details.

In addition, a technical test was performed:

`runTheMatrix.py -l limited,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but may be backported to 11_1_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 7.23,159.0,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- conditions validated in [local tests](https://indico.cern.ch/event/927125/#25-hcal-condition-update-for-r)
- changes in comparison tests seen only in expected workflows: 11634.0 and 12434.0. Small changes involving non-HCAL quantities are because of random number usage by the noise simulation in the digitizer

**Comment by silviodonato** [comment]
+1

**Pull request merged**
