### PR TITLE
[Update GT] High Level conditions for 2017miniAOD rereco

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunII data
   * **RunII Offline relval processing** : [94X_dataRun2_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v10) as [94X_dataRun2_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v10/94X_dataRun2_relval_v11):
      * JEC data
      * JetProbability (by IOV appending)
      * All changes in the offline rereco 94X_dataRun2_ReReco_EOY17_v4

   * **RunII Offline processing** : [94X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v4) as [94X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v4/94X_dataRun2_v6):
      * JEC data
      * JetProbability (by IOV appending)
      * All changes in the offline rereco 94X_dataRun2_ReReco_EOY17_v4

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v9) as [94X_mc2017cosmics_realistic_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v9/94X_mc2017cosmics_realistic_peak_v7):
      * JetProbability
      * JEC

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v9) as [94X_mc2017cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v9/94X_mc2017cosmics_realistic_deco_v7):
      * JetProbability
      * JEC

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v9) as [94X_mc2017_design_IdealBS_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v9/94X_mc2017_design_IdealBS_v8):
      * JetProbability
      * JEC

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v13) as [94X_mc2017_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v13/94X_mc2017_realistic_v11):
      * JetProbability
      * JEC

* **NOTE**:
      * JEC queued to mcRun2 GTs have not been included, since I believe this has been a mistake and only should go into 2017

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie I assume that similar conditions for 2017 should be made available in the master release, right?

**Comment by lpernie** [comment]
Yes they are included in: https://github.com/cms-sw/cmssw/pull/22290

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 136.733,136.779,136.773

**Comment by lpernie** [comment]
@fabiocos workflow 136.733,136.779,136.773 passed the tests

**Comment by fabiocos** [comment]
+1

**Pull request merged**
