### PR TITLE
Remove PFElectronAlgo and PFPhotonAlgo used back in Run 1

### LINKED ISSUE #26658: Cleaning up Run 1 EGamma ParticleFlow code
The old egamma particle flow code has not been used for 5 years but still is strongly entangled with the current particle flow code, which poses an unnecessary maintenance burden.  As discussed with @bendavid, @Sam-Harper, @slava77 and @hatakeyamak, a clean-up of the legacy PF egamma code is on our todo list for the 11XY cycle.

I open an issue on this topic so I can link it in my presentation tomorrow and we can discuss the problems and progress here.

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

The old egamma particle flow code has not been used for 5 years but still is strongly entangled with the current particle flow code, which poses an unnecessary maintenance burden. As discussed with @bendavid, @Sam-Harper, @slava77 and @hatakeyamak, a clean-up of the legacy PF egamma code is on our todo list for the 11XY cycle.

I keep things minimal for now so it can be easily reviewed and keep the risk of differences minimal:
* remove the PFElectronAlgo and PFPhotonAlgo classes
* remove PFAlgo code that requires any of the two classes (could easily be spotted by `usePFPhotons_` or `usePFPElectrons_`)
* remove the configuration for these algos from PFProducer
* in passing, merge the PFProducer.h file with the PFProducer.cc file

Of course what's still missing is cleaning up the configurations from now unused parameters, of better even implement a `fillDescriptions` method for the PFProducer. However, this would require editing various HLT configs which are huge and tedious to edit, so I think that action could be for another PF (or this one after initial tests pass and no differences are observed).

Fixes https://github.com/cms-sw/cmssw/issues/26658.

#### PR validation:

CMSSW compiles and matrix tests pass.

#### if this PR is a backport please specify the original PR:

No backport is intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
happy days :D Thanks Jonas!

**Comment by perrotta** [comment]
@guitargeek 

What about cleaning since now from the un-needed parameters also the ```particleFlowTmp``` config in ```RecoParticleFlow/PFProducer/python/particleFlow_cfi.py```?

This will get automatically propagated to the HLT configs when they will be parsed next (no need to touch them, therefore: since there is no fillDescritpion in this code, the unneeded parameters remaining in the HLT configs in the meanwhile will not hurt, and there will be no need to customize them, then).

I think you should further remove those old parameters from the configs which clones that ```particleFlowTmp```. If the list in https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_0_X_2019-05-19-2300&_filestring=&_string=particleFlowTmp is complete they should be just a few:
- RecoHI/Configuration/python/Reconstruction_hiPF_cff.py
- RecoHI/Configuration/python/customise_PF.py
- RecoJets/JetProducers/python/hltParticleFlowForJets_cfi.py
- RecoParticleFlow/Configuration/test/RecoToDisplay_cfg.py

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
Hi, another quick update. I rushed a bit the initial commit to get something that works with error quickly. Now I think I actually cleaned up all the pieces in PFAlgo.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Removal of unused parts of code and configs
- Jenkins tests pass and show no differences

Once merged, this will affect #26825, as part of the code in PFAlgo.cc which is modified in that PR is removed here. Since one of the two PR's has to be rebased anyhow, I think it it is easier if one first do the removal, and then the modification will be avoided in the other PR

**Comment by guitargeek** [comment]
Thank you Andrea, that is indeed the easiest way and also what we discussed in https://github.com/jpata/cmssw/pull/44.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
