### PR TITLE
Solve vectorization issue by forcing inlining and Silence CLANG Warning by making pragma optional

### LINKED ISSUE #32746: Two build warnings in CLANG DataFormats/Math/test/CholeskyInvert_t.cpp
In the Clang IB we have two warnings due to 

`  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/cff53344cac83c1abd88bb561d95fc5c/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_CLANG_X_2021-01-25-2300/src/DataFormats/Math/test/CholeskyInvert_t.cpp:48:6: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]`

which says clang unable to vectorize a loop 
probably around the pragmas in the same file 
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/test/CholeskyInvert_t.cpp#L97

Full log is in:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_CLANG_X_2021-01-25-2300/DataFormats/Math

One hint is there is a option to be enabled in our llvm build to enable clang to vectorize loops (have not tried yet if the problem is in the llvm external).

### PR DESCRIPTION
**Pull request by VinInn**
Resolves #32746 

only one test affected.
I verified that no timing regression occur anyhow (so pragma not really needed)

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
compiling with -DUSE_VECTORIZATION_PRAGMA -Rpass=loop-vectorize will produce
```
src/DataFormats/Math/test/CholeskyInvert_t.cpp:81:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (auto& m : mm) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:75:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (unsigned int i = 0; i < SIZE; ++i) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:114:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (auto& m : mm) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:103:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (unsigned int i = 0; i < SIZE; ++i) {
      ^
>> Building binary DataFormatsFastMath_t
src/DataFormats/Math/test/CholeskyInvert_t.cpp:81:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (auto& m : mm) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:75:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (unsigned int i = 0; i < SIZE; ++i) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:103:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (unsigned int i = 0; i < SIZE; ++i) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:114:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (auto& m : mm) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:81:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (auto& m : mm) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:75:5: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
    for (unsigned int i = 0; i < SIZE; ++i) {
    ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:103:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (unsigned int i = 0; i < SIZE; ++i) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:114:7: remark: vectorized loop (vectorization width: 2, interleaved count: 1) [-Rpass=loop-vectorize]
      for (auto& m : mm) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:114:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
src/DataFormats/Math/test/CholeskyInvert_t.cpp:103:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
      for (unsigned int i = 0; i < SIZE; ++i) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:114:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
      for (auto& m : mm) {
      ^
src/DataFormats/Math/test/CholeskyInvert_t.cpp:103:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
      for (unsigned int i = 0; i < SIZE; ++i) {
      ^
```

that shows that vectorize for ranks 2,3,4 and not for 5,6
My recollection is that GCC was vectorizing rank 5 as well

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
ok after forcing inlining for all functions I get all vector vectorized ("no warning if pragma used") and timing DO improve for ranks 5 and 6 as well.

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
how to ask a clang test?

**Comment by mrodozov** [comment]
please test for CMSSW_11_3_CLANG_X
you test it against a the clang release which will bring the clang compiler
Could you edit your initial comment first line:
Adresses issue #32746 -> Resolves #32746

**Comment by smuzaffar** [comment]
> Adresses issue #32746 -> Resolves #32746

done @mrodozov

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33355	57d7dfd
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences
- CMSSW_11_3_CLANG_X build log does not show a warning for CholeskyInvert_t.cpp anymore (present in the IB, e.g. https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_CLANG_X_2021-04-04-2300/DataFormats/Math )

**Comment by qliphy** [comment]
+1

**Pull request merged**
