### PR TITLE
replace explicit configuration of puppi with a reference from cfipython/, generated by PuppiProducer::fillDescriptions

### PR DESCRIPTION
**Pull request by slava77**
This is a technical PR to reduce replication of configuration(s) and improve maintenability.
- parameters present in cfipython/fillDescriptions reference and repeated in the source python are dropped
- parameters which are present in cfipython/ but have a different value in the source python are kept after dropping the parameter type for improved syntax safety
- parameters with comments not present in cfipython/ are left
- other commented lines are left

Correctness is checked with expanded configuration in wf 136.888 which includes both a PAT and RECO variants of `PuppiProducer` (checked using `edmConfigDump` followed by a `diff`).

@jeongeun 
this is an example PR for the follow up migration activity/task.

@camclean @alefisico please check and confirm if this update is acceptable.
Thank you.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by alefisico** [comment]
I dont see any obvious mistake. I think the update is ok.

**Comment by slava77** [comment]
> I dont see any obvious mistake. I think the update is ok.

Thank you for checking/confirming.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33207	162ce95 
- configuration python code changes are technical
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
