### PR TITLE
(Backport 11_1_X) L1T CondFormats classes updates for UTM v_0.8.1 (v_0.8.0) 

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:

Needed updates for L1T CondFormat classes for updated external library UMT v_0.8_1 or v_0.8.0.

#### PR validation:

Needs UTM v_0.8.1 installed (https://github.com/cms-sw/cmsdist/pull/6340)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of cms-sw/cmssw#32020

### CODE REVIEW

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#6340

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
