### PR TITLE
Updated HLTTau validation to include legs X in tau+X triggers

### PR DESCRIPTION
**Pull request by slehti**
HLT Tau validation update for 75X. This update adds legs X from tau+X trigger into validation. The code changes in this PR are the same as in PR #9257, but starting from a new from-branch. The PR #9257 can now be dropped.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by slehti** [comment]
I made a last minute update due to a request from the Tau POG, added monitoring for L1 IsoTaus.

**Comment by deguio** [comment]
-1
let's converge on 76x first

**Comment by slehti** [comment]
Made a new PR #9928 due to missing release top, this PR can now be dropped.

**Comment by davidlange6** [comment]
@slehti - for future reference you can "close" your own PR if its no longer needed (or superceded by a different one). Thanks!

**Pull request closed without merging**
