### PR TITLE
added esConsumes to  modules in RecoLocalCalo/CastorCalo

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Comment by kruezbergbier** [comment]
> +1
> Tested at: 5486ec010bc00082cb891577cba38a9cd73373f5
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c076c9/7870/summary.html
> CMSSW: CMSSW_11_2_X_2020-07-10-1100
> SCRAM_ARCH: slc7_amd64_gcc820

Uploading 87245531...

**Comment by kruezbergbier** [comment]
\

**Pull request merged**
