### PR TITLE
ETL Digitization: update of pulse shape

### PR DESCRIPTION
**Pull request by 24LopezR**
#### PR description:

This PR modifies the base pulse shape used in the ETL digitization model, as well as the time walk correction parameters and the measure of the ETL time resuloution (used for obtaining the ETL RecHits). For more details check the relevant presentations:

MTD DPG (04/10/24): https://indico.cern.ch/event/1458405/#12-etl-pulse-shape-update-in-s
MTD DPG (25/10/24): https://indico.cern.ch/event/1466678/#15-update-of-etl-digitization

#### PR validation:

Standard validation run with TTBar 14 TeV workflow (31234.0), expected changes in LocalReco plots

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport, and it is not intended for backporting.

@fabiocos @martinamalberti

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+simulation

**Comment by antoniovagnerini** [comment]
+dqm
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
