### PR TITLE
Enable printout in ReusableObjectHolder test

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

To debug unit test failure on ARM, see https://github.com/cms-sw/cmssw/issues/34647.

#### PR validation:

None.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Majority of the relevant differences are from 140.53 that has different input wrt. baseline. In RECO comparisons 1000.0 shows a difference in `all_OldVSNew_RunMinBias2011Awf1000p0c_edmTriggerResults_TriggerResults__RECO_obj_paths__25__accept.png`
image
that I have not seen before. This PR anyway can not be causing that.

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
