### PR TITLE
add track filter for N tracks with minimum pt

### PR DESCRIPTION
**Pull request by antoniovagnerini**
EDFilter to be used in the cosmics during collision (CDC) trigger @HLT
It selects N tracks passing a certain pT cut. 

This PR is a follow-up of the PR https://github.com/cms-sw/cmssw/pull/21241 and it uses the template approach suggested previously.

### CODE REVIEW

**Comment by mtosi** [comment]
@antoniovagnerini thanks !
are you going to add the possibility of using other criteria (like the #hits, the eta acceptance, ..) as well ?

**Comment by antoniovagnerini** [comment]
@miatosi thank you, this is a good point. For the moment, this only performs a cut on the track candidate pT, but in principle one can add in the Fill Description template some extra parameters. I will have a look.

**Comment by slava77** [comment]
> Code check has found code style and quality issues which could be resolved by applying following patch(s)

these have to be addressed before other tests can run

**Comment by slava77** [comment]
@antoniovagnerini 
please clarify on the status of this PR.
Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test with #29826

**Comment by slava77** [comment]
@cmsbuild please test with #29826

the last tests got stuck apparently

**Comment by slava77** [comment]
> The tests are being triggered in jenkins.
> Tested with other pull request(s) #29826
> https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/6303/console Started: 2020/05/14 15:53

I see in the console:
```
16:35:58 Aborted by localcli
16:35:58 Finished: ABORTED
```

@smuzaffar @mrodozov please check
It would be nice to know that tests failed in the github thread when it happens, without checking the console manually after things seem to be slow.

**Comment by smuzaffar** [comment]
@slava77 , bot only allows one test at a time for a PR. If multiple PRs starts their tests using a common PR then only one of them will run (all others will be aborted).

**Comment by smuzaffar** [comment]
CMSSW_11_1_X_2020-05-14-1100 IB with fix is now available, so no need to start tests with #29826

**Comment by slava77** [comment]
> @slava77 , bot only allows one test at a time for a PR. If multiple PRs starts their tests using a common PR then only one of them will run (all others will be aborted).

ah, does this mean that the tests that were triggered 21 hours ago as in https://github.com/cms-sw/cmssw/pull/29604#issuecomment-628201204 were still blocking the ones started 3 hours ago https://github.com/cms-sw/cmssw/pull/29604#issuecomment-628646574?

OK, I'll try to "abort" first

**Comment by slava77** [comment]
@cmsbuild please abort test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29604	42f3ef6 
- code changes are in line with the PR description; the implementation is rather straightforward
- jenkins tests pass and comparisons with the baseline show no (relevant) differences (the new module is not used in the standard workflows)

**Comment by silviodonato** [comment]
@antoniovagnerini have you consider to use a generic `CandViewSelector`?

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePhysicsCutParser
Something like
```
process.selector5 = cms.EDFilter("CandViewSelector",
    src = cms.InputTag("genParticles"),
    cut = cms.string("pt > 5.0")
)
process.filter = cms.EDFilter("PATCandViewCountFilter", 
    maxNumber = cms.uint32(999), 
    src = cms.InputTag("selector5"), 
    minNumber = cms.uint32(1)
)
```

**Comment by antoniovagnerini** [comment]
The idea of this PR was to introduce an ED filter specifically for tracks, enabling pT and other cut variables. As discussed in https://github.com/cms-sw/cmssw/pull/21241, this kind of approach is needed for Cosmic During Collision track reconstruction.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
