### PR TITLE
Removed unused header from EcalRecHitWorkerRecover.cc

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is part of a cleanup campaign for deprecated headers.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test with #39654 #39639 #39584

**Comment by Dr15Jones** [comment]
Testing to see if can consolidated testing of multiple PRs into one test

**Comment by Dr15Jones** [comment]
please test with #39654, #39639, #39584

**Comment by clacaputo** [comment]
+reconstruction

- technical PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
