### PR TITLE
bsunanda:Run2-alca17 Update the AlCaReco part for IsoTrack and Muon part

### PR DESCRIPTION
**Pull request by bsunanda**
Make the code compatible to mult-threading
Modify the selection to improve throughput in endcap region
Get rid of unused parameters from the code and parameter lists

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by bsunanda** [comment]
Can this be tested and integrated soon? Thanks Sunanda
________________________________

**Comment by davidlange6** [comment]
@cmsbuild, please test
(sorry, this one i lost at some point)

**Comment by bsunanda** [comment]
Failure in opening a file is not due to this PR. Can the test be retried?
________________________________

**Comment by davidlange6** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
As reported by @bsunanda the 76X version has all the fixes: no crashes reported, events are selected.

**Comment by diguida** [comment]
+1
Back port of #10178 
One small comment: it is missing only a change in a test cfg [`Calibration/HcalAlCaRecoProducers/test/AlCaHBHEMuonProducer_cfg.py`](https://github.com/cms-sw/cmssw/pull/10178/files#diff-3531fcee0ee8ad0f7ae29584888b86e9)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
