### PR TITLE
relval matrix update, add 3 Higgs LHE basked fullsim workflows

### PR DESCRIPTION
**Pull request by hengne**
relval matrix update, add 3 Higgs LHE basked fullsim workflows
Needed for near future HLT validation.
based on PR #14224 and PR #14117

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by govoni** [comment]
+1

**Comment by davidlange6** [comment]
@davidlt , @smuzaffar - what do we need add to CMSSW in order to run these workflows in the IBs?

**Comment by smuzaffar** [comment]
@davidlange6 , tar files are already on cvmfs, so there should not be any issue running these in IBs. We can even test these workflows in this PR testing by explicitly providing the extra workflows to run. Should I try running with workflows 1360,1361,1362, 1363 .... any other wfs to test?

**Comment by davidlt** [comment]
From our we don't need to do anything. This looks to be Generators stuff which they manage themselves on CVMFS.

**Comment by davidlange6** [comment]
ok- so we are now happy with using cvmfs (e.g., relying on it) in the IBs.

**Comment by hengne** [comment]
@davidlange6 @davidlt Actually there are the extended generator workflows in the matrix, they all use LHE based generation which fetch gridpacks from cvmfs. If they are all in the IB tests since the beginning, it should be fine also for the 3 newly added workflows.

**Comment by davidlange6** [comment]
Ok, thought we had disabled most of the , but seems I'm confused.

**Comment by davidlt** [comment]
I think, majority of 5XX workflows are like that. That's why they are failing on POWER8 and ARMv8, because they get some tarball from CVMFS which contains x86_64 binaries.

**Pull request merged**
