### PR TITLE
Bug fix for multiple detectors in PFRecHitQTestHCALThresholdVsDepth test 

### PR DESCRIPTION
**Pull request by marksan87**
#### PR description:

The PFRecHitQTestHCALThresholdVsDepth test is used for HBHE and HF PFRecHits. It can accept a parameter set vector for threshold cuts, one for each subdetector, but only one set can be saved at a time. This PR extends this class to accommodate parameter sets for multiple detector enums. 

#### PR validation:

Passes all matrix tests in `runTheMatrix.py -l limited -i all --ibeos`. 

This change only affects [HBHE](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitHBHE_cfi.py), where different thresholds are specified for barrel and endcap depths since Phase I. Physics changes for HBHE are minor.

[summary_pfcHBHE.pdf](https://github.com/cms-sw/cmssw/files/8235671/summary_pfcHBHE.pdf)
[summary_pfcHF.pdf](https://github.com/cms-sw/cmssw/files/8235672/summary_pfcHF.pdf)
[summary_jet.pdf](https://github.com/cms-sw/cmssw/files/8235676/summary_jet.pdf)
[summary_fatjet.pdf](https://github.com/cms-sw/cmssw/files/8235678/summary_fatjet.pdf)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport.

@laurenhay @hatakeyamak @juska @kdlong @silviodonato @rappoccio @bendavid

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by clacaputo** [comment]
> Thank you @marksan87 I think changes being rather small are expected, because the correct thresholds are applied at the PF cluster level anyway, but it's good to apply the intended thresholds at the pf rechit level as implemented here.

Hi @hatakeyamak could you please point to me where the correct thresholds are applied at PF cluster level?. Thanks

**Comment by marksan87** [comment]
> > Thank you @marksan87 I think changes being rather small are expected, because the correct thresholds are applied at the PF cluster level anyway, but it's good to apply the intended thresholds at the pf rechit level as implemented here.
> 
> Hi @hatakeyamak could you please point to me where the correct thresholds are applied at PF cluster level?. Thanks

Hi @clacaputo. At the PF cluster level these are the [gathering energy thresholds](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py#L6-L7) in the topo clustering [config](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py#L38-L49). The cuts are applied [here](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericTopoClusterizer.cc#L99).

**Comment by clacaputo** [comment]
> Hi @clacaputo. At the PF cluster level these are the [gathering energy thresholds](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py#L6-L7) in the topo clustering [config](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/python/particleFlowClusterHBHE_cfi.py#L38-L49). The cuts are applied [here](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/plugins/Basic2DGenericTopoClusterizer.cc#L99).

Hi @marksan87 , thanks for the reply. I have a follow-up question: if in the topo clustering you are filtering on the RecHits based on the same thresholds, why if you filter in `PFRecHitQTestHCALThresholdVsDepth` you introduce some differences?

**Comment by clacaputo** [comment]
Hi @marksan87 , any update on this question https://github.com/cms-sw/cmssw/pull/37219#issuecomment-1075075479?
Thanks

**Comment by marksan87** [comment]
Hi @clacaputo, I have been looking into these differences and it seems they are the result of using the GPU Hcal/Ecal local reco. I re-ran some tests using the CPU reco and there is no longer any difference at the PFCluster or jet levels.

[summary_fatjet.pdf](https://github.com/cms-sw/cmssw/files/8344114/summary_fatjet.pdf)
[summary_jet.pdf](https://github.com/cms-sw/cmssw/files/8344115/summary_jet.pdf)
[summary_pfcHBHE.pdf](https://github.com/cms-sw/cmssw/files/8344116/summary_pfcHBHE.pdf)

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
> Hi @clacaputo, I have been looking into these differences and it seems they are the result of using the GPU Hcal/Ecal local reco. I re-ran some tests using the CPU reco and there is no longer any difference at the PFCluster or jet levels.
> 
> [summary_fatjet.pdf](https://github.com/cms-sw/cmssw/files/8344114/summary_fatjet.pdf) [summary_jet.pdf](https://github.com/cms-sw/cmssw/files/8344115/summary_jet.pdf) [summary_pfcHBHE.pdf](https://github.com/cms-sw/cmssw/files/8344116/summary_pfcHBHE.pdf)

Hi @marksan87 thanks a lot for the plots, just for my education, which workflow have you used for validation?

**Comment by marksan87** [comment]
> > Hi @clacaputo, I have been looking into these differences and it seems they are the result of using the GPU Hcal/Ecal local reco. I re-ran some tests using the CPU reco and there is no longer any difference at the PFCluster or jet levels.
> > [summary_fatjet.pdf](https://github.com/cms-sw/cmssw/files/8344114/summary_fatjet.pdf) [summary_jet.pdf](https://github.com/cms-sw/cmssw/files/8344115/summary_jet.pdf) [summary_pfcHBHE.pdf](https://github.com/cms-sw/cmssw/files/8344116/summary_pfcHBHE.pdf)
> 
> Hi @marksan87 thanks a lot for the plots, just for my education, which workflow have you used for validation?

Hi @clacaputo, these plots were created with a reHLT workflow I was using for validation testing for  https://its.cern.ch/jira/browse/CMSHLT-2250. It was generated with the following command:

```
cmsDriver.py reHLT \
    --processName reHLT \
    -s HLT:@relval2021 \
    --conditions auto:phase1_2021_realistic \
    --datatier GEN-SIM-DIGI-RAW \
    -n 100 \
    --eventcontent FEVTDEBUGHLT \
    --geometry DB:Extended \
    --era Run3 \
    --filein /store/relval/CMSSW_12_3_0_pre5/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_123X_mcRun3_2021_realistic_v6-v1/10000/3f4a564a-b65a-4f45-87df-5d908f0757d3.root \
    --outputCommand 'keep *_*articleFlow*HBHE*_*_*' \
    --no_exec

tee -a reHLT_HLT.py <<EOF

# Adjust qtest for PFHBHERecHitCreator (https://its.cern.ch/jira/browse/CMSHLT-2250)
from HLTrigger.Configuration.common import *
for producer in producers_by_type(process, "PFRecHitProducer"):
    if producer.producers[0].name.value() == 'PFHBHERecHitCreator':
        print(producer.producers[0].qualityTests[0].name)
        producer.producers[0].qualityTests[0].name = "PFRecHitQTestHCALThresholdVsDepth"
        print(producer.producers[0].qualityTests[0].name)
EOF

```

**Comment by clacaputo** [comment]
Hi  @marksan87 , so the plot that you have posted have been obtained at HLT level, do I understand it correctly?
At RECO I can still see some minimal differences mostly in `PFCandidate` and downstream related collections.

For examples in wf `250202.181`

**log10recoPFCandidates_particleFlow__RECO_obj_pt** for neutral hadron [link](https://cmssdt.cern.ch/lxr/source/DataFormats/ParticleFlowCandidate/interface/PFCandidate.h#0044)

all_OldVSNew_TTbar13TeVPUppmx2018wf250202p181c_log10recoPFCandidates_particleFlow__RECO_obj_pt80

**log10recoPFJets_ak4PFJets__RECO_obj_energy**
all_OldVSNew_TTbar13TeVPUppmx2018wf250202p181c_log10recoPFJets_ak4PFJets__RECO_obj_energy

It's not clear to me whether these differences should be there.

**Comment by marksan87** [comment]
Hi @clacaputo. Yes my plots were from HLT level. I've been looking into the `250202.181` wf at RECO level and I see some minor differences like you are describing. 

For example, in the third event I found two extra PFClusters with the PR changes that are just a seed rechit. These PFRechits are not classified as seeds in the base version as they have neighbors with higher energy. This is a rare situation but it seems problematic to include these failing PFRecHits in the seed finding step, which occurs before topo clustering thresholds are applied.

**Comment by clacaputo** [comment]
> These PFRechits are not classified as seeds in the base version as they have neighbors with higher energy. This is a rare situation but it seems problematic to include these failing PFRecHits in the seed finding step, which occurs before topo clustering thresholds are applied.

Thanks for checking @marksan87 . If I understood correctly, the PR recovers some PFRecHits that shouldn't be recovered, although it's a rare situation it's problematic. I'd like to have an opinion from @cms-sw/pf-l2

**Comment by marksan87** [comment]
Hi @clacaputo. My original assumption that this was a bug in the seed finding logic was incorrect. The difference was due to Phase 0 thresholds being used for HB in [particleFlowRecHitHBHE_cfi.py](https://github.com/marksan87/cmssw/blob/85702bc92e7572a1a0555d9ba4ffbe0d24042375/RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitHBHE_cfi.py) for 2018 offline reco.

The default thresholds in these config files are for Phase 0. If used in Phase I runs, the thresholds are updated to the Phase I values. For HBHE in this 2018 workflow, HB was using the Phase 0 thresholds. This wasn't noticed before since the HB thresholds were effectively ignored. 

However, the Phase I thresholds are also not correctly applied in the PFCluster config for HBHE and HCAL (multidepth HBHE) clusters. I have updated these configs to correctly update all applicable thresholds to Phase I values where appropriate. Results from `250202.181` show noticeable changes in PFCluster and ak4jets, though presumably this is the desired behavior?

[summary_pfcHBHE.pdf](https://github.com/cms-sw/cmssw/files/8393605/summary_pfcHBHE.pdf)
[summary_jet.pdf](https://github.com/cms-sw/cmssw/files/8393606/summary_jet.pdf)

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by marksan87** [comment]
Hi @clacaputo. I removed the previous commit and comment since this reasoning was not correct. Sorry for the confusion. 

The correct explanation for the differences seen in this 2018 wf is that some seeds are being excluded due to their neighbors having higher energy. In the example from above, two HE rechits have HB rechits as neighbors. The HB neighbors have energies below the Phase 0 threshold (0.8 GeV) but still higher than the HE rechit energy (cut on the lower Phase I threshold of 0.2 GeV). In the base version, all HB rechits are included since this q test is not correctly applied to them, so this prevents those HE rechits from becoming seeds. The PR removes these failing HB rechits which causes the two HE rechits to now meet the seeding conditions. 

This begs the question of whether to exclude a seed based on [neighbor rechit energy](https://github.com/marksan87/cmssw/blob/depthThresholdTest/RecoParticleFlow/PFClusterProducer/plugins/LocalMaximumSeedFinder.cc#L161-L169) before checking if those neighbors actually belong to the [same depth/layer](https://github.com/marksan87/cmssw/blob/depthThresholdTest/RecoParticleFlow/PFClusterProducer/plugins/LocalMaximumSeedFinder.cc#L170-L196).

**Comment by clacaputo** [comment]
+reconstruction

- applying the intended rechit thresholds at the PF rechit list creation step
  - differences were seen in this 2018 wf at the HB-HE boundary
  - detailed explanation https://github.com/cms-sw/cmssw/pull/37219#issuecomment-1087687532
- reco changes are in-line with the PR changes

**Comment by missirol** [comment]
@marksan87 @hatakeyamak , since this is a bugfix (by the way, should it be labelled as such by the bot?)

could you remind me (1) how/if this relates to the request in [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250), and (2) if in general this bugfix should be backported to `12_3_X` (since HLT will use that cycle at the start of Run 3)?

(cc: @silviodonato @Martin-Grunewald)

**Comment by hatakeyamak** [comment]
Hi @missirol 
Thank you for your comment.
As mentioned already here https://its.cern.ch/jira/browse/CMSHLT-2250, 12_3_X with the proposed change with CMSHLT-2250 produce intended PF clusters (because the correct threshold will be applied at the PF clustering level), so this bugfix is not absolutely necessary, and we were hoping that https://its.cern.ch/jira/browse/CMSHLT-2250 will be propagated. But, I can certainly backoort it, so that the intended thresholds will be applied at the earlier PF rechit level. We can certainly backport this PR though.

**Comment by missirol** [comment]
Hi @hatakeyamak , thanks for your explanation.

If I understand correctly, if we backport this PR now, the HLT outputs will not change, because the HLT module is currently misconfigured (as it uses `PFRecHitQTestThreshold`). The HLT outputs will change (in any case) once we integrate [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250).

If this is correct, I would suggest to backport this PR for `12_3_0`, so that the source code is bug-free, and we can decide in [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250) when the HLT outputs will change.

> we were hoping that https://its.cern.ch/jira/browse/CMSHLT-2250 will be propagated

The request in the JIRA is very easy to implement, but TSG is waiting for the feedback of POGs to understand if any calibrations (e.g. JECs) would have to be redone because of that change.

**Comment by missirol** [comment]
type bugfix

This PR fixes a bug in PFlow. The possibility to backport it to `12_3_X` is still under discussion, but that should not delay the integration of this PR (it might be useful to test it in 12_4_X IBs soon, in case a backport is opened in time for 12_3_0, cc: @cms-sw/orp-l2).

**Comment by perrotta** [comment]
+1

**Comment by missirol** [comment]
@hatakeyamak 

Regarding https://github.com/cms-sw/cmssw/pull/37219#issuecomment-1088359636, did I understand correctly? If so, should we have a backport of this bugfix to `12_3_X`?

**Comment by missirol** [comment]
@hatakeyamak 

Kind ping on the question in https://github.com/cms-sw/cmssw/pull/37219#issuecomment-1095600142.

**Comment by hatakeyamak** [comment]
https://github.com/cms-sw/cmssw/pull/37219#issuecomment-1088359636
Sorry. I had some emergencies since last week, but I am gradually catching up.

I am not sure if I understand the summary. Regardless of we backport this branc to 12_3 or not, HLT outputs will change once we integrate [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250) in very similar way or identical way.

This bug fix just enforces that the correct threshold gets applied at the rechit level and not at the cluster level.

**Comment by hatakeyamak** [comment]
Okay. See https://github.com/cms-sw/cmssw/pull/37550.

**Pull request merged**
