### PR TITLE
enabling 2D plots for muon inner track monitoring [backport #23940]

### PR DESCRIPTION
**Pull request by mtosi**
backport https://github.com/cms-sw/cmssw/pull/23940

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by andrius-k** [comment]
please test

**Comment by kpedro88** [comment]
-1
wrong branch or bad merge

**Comment by perrotta** [comment]
-1

**Comment by mtosi** [comment]
rebasing the branch, I screwed up this PR :(
sorry !
=> I'm closing this PR, because I've just opened https://github.com/cms-sw/cmssw/pull/23986

**Pull request closed without merging**
