### PR TITLE
Exo trigger prompt monitoring92 x

### PR DESCRIPTION
**Pull request by gomber**
@fwyzard Here is the same PR #18971  in 92X.

### CODE REVIEW

**Comment by perrotta** [comment]
-1
@gomber : the 92X and 93X had diverged, and you can't use the same git branch for the pull requests in the two queues. (Unless you base it on an old 92X IB from before the opening of the 93X queue: but in that case you must be 100% sure that you won't have to apply any commit update to them on a newer IB, which would break one of the two PRs. In summary: better never use the same git branch for submitting pull requests in two different releases)

**Comment by gomber** [comment]
@perrotta So the original branch which I have is done with CMSSW_9_2_4, and I guess @fwyzard suggested that we can use the same branch and I did that..So I am not sure what you are suggesting here? Are you saying that I start from some CMSSW_9_2_X IB and then create a new branch for this, which I use to create this new PR in 92X? May be I am missing something?

**Comment by fwyzard** [comment]
Sorry @gomber , I thought it would be fine as the branch was originally based on 9.2.4, but the problem is that last Tuesday you merged "master" into your branch, making it depend on 9.3.x .

Unfortunately it looks like you do need to make a separate branch for 9.2.x; you could start back from 9.2.4 and cherry-pick only the commits you actually need. 
Or, is there some dependency on features or other PRs that are only in 9.3.x ?

**Comment by gomber** [comment]
@fwyzard It has no dependency on 9.3.X features, so I can start from scratch, but since it passed all the checks, so I am wondering if I need to make new PR, just let me know. I am done with everything in my local area, can commit anytime.

**Pull request closed without merging**
