### PR TITLE
Modernize RecoEgamma/PhotonIdentification helpers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- fix static analyzer and compiler warnings
- made all methods const
- avoid using member data for temporary storage
- comply with CMS naming conventions
- use modern C++ constructs

Changes are purely technical and should have no change on the results (probably will be faster and use less memory however).

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

previous failures are unrelated to this PR.

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
