### PR TITLE
removing duplicate ALCARECO from Run2 Cosmic relval (90X)

### PR DESCRIPTION
**Pull request by fabozzi**
backport of #18094 

Removing duplicate ALCARECO wf from sequence of Run2 Cosmics.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
