### PR TITLE
Add Score histos for Primary Vertices 

### PR DESCRIPTION
**Pull request by VinInn**
backport of #16026

### CODE REVIEW

**Comment by VinInn** [comment]
type backport

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
if everything ok (as it looks like) please approve.
I would like to have in next release

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
