### PR TITLE
Cleaning code recently added in DQMOffline/RecoB

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Right after having signed [#36884](https://github.com/cms-sw/cmssw/pull/36884) for merge, I realized that I did not manage to ask to apply a few simple code cleanings. to recover it, I implement them here all together.

@marco-link @jfernan2 please check if there is anything wrong with them.

#### PR validation:

It builds, no changes expected

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by marco-link** [comment]
Thanks @perrotta, I see nothing that's wrong.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
