### PR TITLE
SubtractionSolid Vs UnionSolid For Muon Barrel

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

This PR has been triggered by what @ianna wrote in the PRs #31520 and #31576. The Subtraction Solids have been replaced by Union Solids inside the Muon Barrel (MB). The same job, for ME, will be performed in a next PR.
This PR is not related to DD4hep migration.

**PR validation:**

1) validation by "cmsShow.exe -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS"
The attached picture shows, after this PR, no Muon overlaps.

2) validation by "nohup cmsRun SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4Hep_cfg.py >& overlaps.out &" 
Muon's volumes are not present in the overlaps.out file.
 
3) validation by runTheMatrix.py -l 25202.1 :

25202.1_TTbar_13+TTbar_13+DIGIUP15APVSimu_PU25+RECOUP15_PU25+HARVESTUP15_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct  6 09:14:40 2020-date Tue Oct  6 08:53:00 2020; 
exit: 0 0 0 0 
1 1 1 1 tests passed, 0 0 0 0 failed

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

Schermata 2020-10-06 alle 09 17 48

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
It may be a while before this change can be get into a new Global Tag.

**Comment by qliphy** [comment]
+1

**Pull request merged**
