### PR TITLE
Adding L1T O2O parsing for the EMTF + taking CaloParams prototype from the CondDB

### PR DESCRIPTION
**Pull request by kkotov**
1) full L1T O2O functionality for the EMTF
2) the prototype of CaloParams is now taken from CondDB (as opposed to the static python)
3) various little fixes in scripts and configs

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
Following Giacomo's suggestion to use production DB for the CaloParams prototype (as opposed to the original configuration from the development DB) I've updated the branch as well as I added a central handles to switch databases (e.g. cms_orcon_prod <-> cms_orcon_adg or cms_omds_ld <-> cms_omds_adg). This allows to validate the L1T O2O on lxplus (away from the production environment). @rekovic , could you please trigger the tests again? Thanks.

**Comment by kkotov** [comment]
And the last conflict was resolved. Now this is really ready for tests.

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
We've decided to go forward with 90x version (16664) without having this back-port.

**Pull request closed without merging**
