### PR TITLE
[14.0.X] TkAl: fix PV validation and PV resolution submission scripts

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44467

#### PR description:

The goal of this PR is to fix the scripts `submitPVResolutionJobs.py` and `submitPVValidationJobs.py` such that they can run in recent releases and with recent (Run 3) data.
The related unit tests are improved such that, in addition to technically creating the configuration to be run with HTCondor, said configuration is also tested for at least one job (running locally).

#### PR validation:

Run successfully:
   * `scram b runtests_SubmitPVsplit`
   * `scram b runtests_SubmitPVrbr`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44467 for the 2024 data-taking release

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
> . Was it done on purpose?

no, even if it's harmless, it should be commented (or even removed) also here, because that script doesn't exist anymore:

```console
./batchHarvester_Prompt_0.sh: line 2: /afs/cern.ch/cms/caf/setup.sh: No such file or directory
```

at the end of the [log file](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-49b002/38275/unitTests/src/Alignment/OfflineValidation/test/SubmitPVsplit/testing.log)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/44467, by now successfully merged in master

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
