### PR TITLE
DD4hep: Merge Geometry Event Setup Records

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

Use the same geometry records for both the DD and the DD4hep-based geometries. 
@Dr15Jones - FYI, it looks like this takes more time:
```
< Benchmark 'DTGeometryESProducer' took 3117.68 millis
---
> Benchmark 'DTGeometryESProducer' took 2673.57 millis

```
#### PR validation:

The tests are run automatically during the PR integration

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna sorry, this looks just an updated version of #26231, at least for most of the commits (apart some merges of master to keep the branch up to date), do you confirm?

**Comment by fabiocos** [comment]
merging one after the other or merging just this one looks equivalent to me:

```
17:42 cmsdev25 604> git log --topo-order --oneline --graph  HEAD 
*   f710664670a (HEAD -> tmp/merge-test) Merged refs/pull/26352/head from repository cms-sw with cms-merge-topic
|\
| * ec28c2eb6a0 (pull/26352_backup, cms-sw/refs/pull/26352/head) Update testDDCompactView.cpp
| * 8444fcfbe42 Update dumpDDExpandedView.cpp
| * 0021c74460c Update dumpDDCompactView.cpp
| * 9cd9c11da0b Update testmat.cpp
| *   9c382f928f4 Merge branch 'master' into dd4hep-merge-geometry-v1
| |\
| * \   fb758d2b4a3 Merge branch 'master' into dd4hep-merge-geometry-v1
| |\ \
| * | | 000305ccc68 Megre Geometry records
* | | |   db2cd47e77d Merged refs/pull/26231/head from repository cms-sw with cms-merge-topic
|\ \ \ \
| * \ \ \   265b2c5c37e (pull/26231_backup, cms-sw/refs/pull/26231/head) Merge branch 'master' into dd4hep-merge-geometry-v0
| |\ \ \ \
| | |/ / /
| |/| | |
| * | | | c8f01c32a47 Move the validation plugin
| * | | | 8a3f6f55637 Fix script
| * | | | e99fc64be39 Correct includes
| * | | | ecf03186c79 Correct includes
| * | | | 417adf327f7 Correct include
| * | | | 94b6c1b0144 Use emplace_back
| * | | | 1847306aa71 Add DT geometry validation
| * | | | 37db9fbfc45 Merge development code to a usual Geometry structure
* | | | |   e9fc368d9e9 (tag: CMSSW_10_6_X_2019-04-07-0000, tag: CMSSW_10_6_ROOT6_X_2019-04-07-0000, tag: CMSSW_10_6_ROOT614_X_2019-04-07-0000, tag: CMSSW_10_6_CLANG_X_2019-04-07-0000, official-cmssw/master, official-cmssw/HEAD, official-cmssw/CMSSW_10_6_X, from-CMSSW_10_6_X_2019-04-07-0000, CMSSW_10_6_X) Merge pull request #26375 from deguio/fixAgingPhase2
```

**Comment by ianna** [comment]
@fabiocos - I'd prefer merging one after the other even though this PR depends on the previous one.

**Comment by fabiocos** [comment]
Not sure why GitHub presents these conflicts, a manual merging is successful

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
