### PR TITLE
Phase2-hgx336F Fix a bug in HGCalWaferMask to avoid overlaps of partial wafers in the V17 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix a bug in HGCalWaferMask to avoid overlaps of partial wafers in the V17 geometry of HGCal

#### PR validation:

Tested by running the overlap finding scripts and also using Firework

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need to be back ported to the version 13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
type bugfix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @srimanob Please approve this PR. Need to backport it to 13_0_X

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- There are quite several changes in the outputs of wf 23234.0 (TTbar_14TeV+2026D94), which is certainly expected given the updates to the geometry. I give for granted that who already signed this PR verified that all modified outputs make sense (at a first glance I would say so).

**Pull request merged**
