### PR TITLE
Extend DQMGlobalEDAnalyzer to allow additional template options

### PR DESCRIPTION
**Pull request by Dr15Jones**
The BeamConditionsMonitor module was a prime candidate to become a DQMGlobalEDAnalyzer. To make that happen, the module wanted to see the beginLuminosityBlock callback from the framework. This required the use of the edm::LuminosityBlockCache<> option. This could be accomodated by a simple extension to DQMGlobalEDAnalyzer to allow addition template arguments to be passed on to the base class.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by schneiml** [comment]
@Dr15Jones 
> The BeamConditionsMonitor module was a prime candidate to become a DQMGlobalEDAnalyzer

Would you care to elaborate?

This module runs online only, and I am not sure if we run _any_ `DQMGlobalEDAnalyzer` in online, or if this works at all, or if we want to support it in the future.

So, I see the merits of this as a research project (and btw, thanks for having a look at these ancient artifacts of DQM history!), but I feel a bit uncomfortable with merging such things into a release right now -- this will need some validation and maybe a strategic decision.

**Comment by Dr15Jones** [comment]
> This module runs online only, and I am not sure if we run any DQMGlobalEDAnalyzer in online, or if this works at all, or if we want to support it in the future.

Let us break this down into two parts: being a global module and being a DQMGlobalEDAnalyzer.

As for converting from a `edm::EDAnalyzer` to a `edm::global::EDAnalyzer<>` as the underlying base class, this module only looks at information from the EventSetup, never from the event. Therefore calling it concurrently during event processing is perfectly safe. If we were to use an `edm::DQMEDAnalyzer` the framework would have prevented concurrent event access which is a waste here. In addition, items in the EventSetup are allowed to update no faster than once per LuminosityBlock. Therefore doing the work at beginLuminosityBlock rather than getting data out each event and then filling the histograms and endLuminosityBlock yields identical results since the EventSetup object is the same for each event in a LuminosityBlock. If you'd prefer, I could move the filling of the histograms back to the `globalEndLuminosityBlock` transition, however the resulting histograms will be identical to doing it at `begin` time.

Now converting from the legacy `edm::EDAnalyzer` to `edm::global::EDAnalyzer<>`. The histogram booking changes from happening at `beginJob` to `globalBeginRun`.  That change is, I believe, irrelevant for the DQMStore since no access to the histogram should happen between `beginJob` and `globalBeginRun`.  In addition, `DQMEDAnalyzer` books its histograms at `globalBeginRun` as well, so if _online_ used `DQMEDAnalyzers` already, you have proof that is safe. In fact, the DQMStore does not have any transition callbacks related to `beginJob` so can not do any activities at that transition boundary. Also, for both direct book calls to `DQMStore` (done by the old `edm::EDAnalyzer`) and `edm::global::EDAnalyzer<>`, they use `moduleID == 0` so my change does not affect the _globalness_ of the histograms being filled.

So from what I can tell, `edm::global::EDAnalyzer<>` is a near perfect replica of calling the `DQMStore` directly (except for which transition gets the booking calls) but with proper thread safety applied.

**Comment by Dr15Jones** [comment]
please test

**Comment by schneiml** [comment]
@Dr15Jones re testing, what matters is what the GUI shows in live mode. The online file content is only a weak proxy for that. The proper procedure is not very hard, but quite manual: TaDQM/Integration/python/config/fileinputsource_cfi.pyke the client config from `DQM/Integration/python/clients`, modify it to use the file input source from `DQM/Integration/python/config/fileinputsource_cfi.py` (some have a flag to switch to that, feel free to add if it is missing), then run using some recent run number (it will try to find files on DAS automagically), and run a local online DQMGUI to see the plots in live mode (the client should connect to it automatically).

In general I am not too scared about live mode breaking (it is not *that* complicated on the cmssw side), but we should definitly test it at some point. I might try it with this PR later today.

**Comment by schneiml** [comment]
@Dr15Jones re `DQMGlobalEDAnalyzer`:
> this module only looks at information from the EventSetup, never from the event
Ah, I was not aware of that.

The rest of your argument seems valid (or at least it looks like you actually thought about what will happen, while I have not...). My concern is mostly that online runs the `DQMStore` in non-indexed legacy mode, while the `DQMGlobalEDAnalyzer` as used by HLT always runs in threaded mode. And while things are called and implemented the same ("global" by setting `moduleId` to 0), the semantics are subtly different, and trying to use the same logic for threaded and legacy mode failed when we tried to do this for the one-module migration.

So, it might be fine in practice, but I had no reason to think so without actually checking the code again.

**Comment by schneiml** [comment]
Mhh, actually, I don't see any of the two MEs booked in this plugin in production or when running the client stand-alone. But the cff file is loaded. Not sure what is going on there, but I guess this PR will not make things worse...

**Comment by Dr15Jones** [comment]
@schneiml In the _cfg file I used to test, the module's _cfi file was loaded, however the module itself was never put on a path. To do my testing, I had to explicitly add the module to a path in order to get the module to be run.

**Comment by schneiml** [comment]
@Dr15Jones ah, ok. It indeed seems the module is also never added anywhere in the production config. So while I could still try running it, there is obviously no risk in breaking production online DQM atm...

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
