### PR TITLE
Run3-gex112Z Try to address missing chambers for RPC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address missing chambers for RPC

#### PR validation:

Use Overlap testing tool

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
> @cmsbuild Please test

Please don't keep testing: the issue with the missing input file for wf 4.76 is not fixed yet, and we should simply ignore it, by now.
As far I can see, this PR could be merged even now (as soon as @cms-sw/geometry-l2 signs it), as I see no problems with having it merged in advance to the other ones from you list.

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Test outputs already available in https://github.com/cms-sw/cmssw/pull/36755#issuecomment-1017155638, it is not needed to wait for the new ones

**Comment by perrotta** [comment]
merge

**Comment by cvuosalo** [comment]
With this PR, the missing RPC chambers are restored. With this PR and #36654, the RPC geometry has:
```
RPCGeom:
 I have 2752 detTypes
 I have 2752 detUnits
 I have 3812 dets
 I have 2752 rolls
 I have 1060 chambers
```

**Pull request merged**
