### PR TITLE
FWCore/ParameterSet changes for python3 compatibility

### PR DESCRIPTION
**Pull request by davidlange6**
Unit tests in FWCore/PyDevParameterSet now run correctly if python3 is used (in addition to already working with python2)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
The unit test failure TestFWCoreParameterSetDriver looks like it was caused by this pull request.

**Comment by Dr15Jones** [comment]
The unit test failure is NOT from this pull request since it is happening in the IB.

**Comment by davidlange6** [comment]
i think its still my fault...

**Comment by fabiocos** [comment]
@Dr15Jones @davidlange6 indeed the failure https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_6_X_2019-02-26-2300/unitTestLogs/FWCore/ParameterSet#/59-59 seems due to a missing . in Modules.py when there are import from Types, but I already verified this morning that just fixing it triggers another problem

**Comment by Dr15Jones** [comment]
#26026 fixes the unit test problem

**Comment by fabiocos** [comment]
please test with #26026

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test with #26026

**Comment by davidlange6** [comment]
hi @Dr15Jones - did this PR need more attention?

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
