### PR TITLE
HLT menu development for `14_1_X` (4/N)  [`15_0_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_1_X` (branch `CMSSW_15_0_X`): **this is the close-out PR for HLT development in the CMSSW_14_1_X cycle**.
   * This is the PR for the master branch, which will then be backported down to 14_1_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
   * These updates correspond to the changes accumulated in the 14_1_X release cycle after the "V1.0" `HIon` menu for the 2024 PbPb data-taking period was released.
   
This update includes the integration of the following JIRA tickets:
- [CMSHLT-3382](https://its.cern.ch/jira/browse/CMSHLT-3382) [HIN] Addition of a `L1_FirstCollisionInTrain` passthrough trigger for ZDC physics analysis
- [CMSHLT-3386](https://its.cern.ch/jira/browse/CMSHLT-3386) [ECAL] Downgrading `EnergyInDeadEB/EE_FE` Warning by setting `logWarningEtThreshold_EB/EE_FE` parameters in the HLT configuration to -1
- [CMSHLT-3388](https://its.cern.ch/jira/browse/CMSHLT-3388) [HIN/TRK] New centrality BS trigger for PbPb menu
- [CMSHLT-3390](https://its.cern.ch/jira/browse/CMSHLT-3390) [HIN/DQM] Misnaming of the output folders for DQM analyzers in `HLTDQMPixelReconstructionPPOnAA`
- [CMSHLT-3392](https://its.cern.ch/jira/browse/CMSHLT-3392) [TSG/DQM] Missing collections for HLT dqm client in PbPb 2024 runs
- [CMSHLT-3393](https://its.cern.ch/jira/browse/CMSHLT-3393) [HIN] New HLT paths for low pT double EG UPC triggers
- [CMSHLT-3394](https://its.cern.ch/jira/browse/CMSHLT-3394) [HIN/AlCa] Change of L1 seed for `AlCa_EcalPhiSymForHI_v` in the `HIon` menu
- [CMSHLT-3395](https://its.cern.ch/jira/browse/CMSHLT-3395) [HIN] Request for modifying UPC HLT paths for ZDC triggers
- [CMSHLT-3400](https://its.cern.ch/jira/browse/CMSHLT-3400) [HIN] Sync `HIon` table with online post-HIRun2024B
- [CMSHLT-3401](https://its.cern.ch/jira/browse/CMSHLT-3401) [HIN] Sync `PRef` table with online post-Run2024J

In addition, the following changes are included:
   * 6007679640da752e93aff8c1e11e9ddfec7cd49f : update of L1T HIon menu in TSG GTs to `L1Menu_CollisionsHeavyIons2024_v1_0_6_xml`
   * 24289e7fcd1257387c3128f5c3adeb983ee6fc3f : move from `L1Menu_Collisions2024_v1_3_0_xml` to `L1Menu_Collisions2024_v1_3_0-d1_xml` in `autoCondHLT` in order to have the same firmware `uuid` as in the real data-taking 
   * b06577fedee374d09235d07e4ccf8505ad3647ac : fix buggy customization function `customiseHLTFor46647`
   * db1d41b560c69cf64257ea72d9d44e09a3fce726: update `phase1_2024_realistic_hi` autoCond key to have the latest 2024 L1T HIon menu: `L1Menu_CollisionsHeavyIons2024_v1_0_6_xml` (as per this [cmsTalk](https://cms-talk.web.cern.ch/t/gt-mc-updata-of-l1t-menu-v1-0-6-in-pbpb-mc-gt-for-14-1-x/60606/3))
        * The GT in autoCond was modified to [141X_mcRun3_2024_realistic_HI_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun3_2024_realistic_HI_v10), which includes the L1 menu required by these HLT updates.
      * The difference from the previous version _v8 in autoCond can be seen [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_HI_v10/141X_mcRun3_2024_realistic_HI_v8) , where one can see that only the L1 menu was updated wrt _v8.

#### PR validation:

TSG integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_1_X` (2024 PbPb data-taking release).

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
test parameters:
   * workflows = 161, 161.02, 161.03, 161.1, 161.2, 161.3, 161.4, 180.0, 180.1, 181, 181.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@cms-sw/alca-l2 if you're happy with the autoCond change, can you sign here (and backports)?

**Comment by perrotta** [comment]
@mmusich could you please add the following bullets in the PR description (here as well as in the backport PRs)?

- The GT in autoCond was modified to [141X_mcRun3_2024_realistic_HI_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun3_2024_realistic_HI_v10), which includes the L1 menu required by these HLT updates.
- The difference from the previous version `_v8` in autoCond can be seen [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_HI_v10/141X_mcRun3_2024_realistic_HI_v8) , where one can see that only the L1 menu was updated wrt `_v8`.

**Comment by perrotta** [comment]
+alca

**Comment by mmusich** [comment]
> could you please add the following bullets in the PR description (here as well as in the backport PRs)?

done.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
