### PR TITLE
fix unit test if it is run from base release i.e. not locally build

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the unit tests failing in IBs where we run unit tests from the release

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@wmtan , does these changes looks good to you?
Note that during IB tests, we create dev area and then run all unit tests from the release area.

**Comment by wmtan** [comment]
@Dr15Jones @smuzaffar This doesn't "fix" the unit test for locality. It just removes it.
This may be the best we can do, but I'm not sure.

**Comment by Dr15Jones** [comment]
@smuzaffar I'm not a big fan of removing the test for that feature. I went looking but couldn't find a written description of the change done in the build system that triggered this test to fail. If you could remind me maybe we could come up with an alternate solution which preserves the test. For example, if we made the test look for a file in its own package, would that help? Would it help if we checked if CMSSW_BASE and CMSSW_RELEASE_BASE were pointing to the same area and if so do something different?

**Comment by smuzaffar** [comment]
Change is not in the build system but it is in the way we run tests in for IBs. Previously we were installing cmssw release locally on the build machine and then were running tests in the release area. But now we use the AFS/CVMFS installation of IB and create a dev area to run tests.

Anyway, this test even fails in dev area e.g doing something like this will fail this test
```
scram p CMSSW_8_0_X_2015-11-05-2300
cd CMSSW_8_0_X_2015-11-05-2300/
cmsenv
git cms-addpkg FWCore/PythonParameterSet
scram b -v -j 20
scram build runtests
```
Looks like , test assumes that FWCore/ParameterSet is available in local area and Geometry/TrackerSimData is available from release area which is not always true. I think test should assume that these files can be load from either local area or release area

**Comment by Dr15Jones** [comment]
@wmtan @smuzaffar I've lost track, is this pull request needed anymore?

**Comment by wmtan** [comment]
@wmtan No, this PR should be closed because it disables the locality check in all cases.

**Comment by smuzaffar** [comment]
yes this is not needed any more, closing it

**Pull request closed without merging**
