### PR TITLE
Moved DBremWatcher to plugins directory

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This avoids having the module be registered in multiple shared libraries.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This should fix a QA problem seen in the IBs.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
@revering Could you backport this to the same earlier release cycles as #38329 was backported to? Thanks!

**Comment by qliphy** [comment]
+1

**Pull request merged**
