### PR TITLE
Run2-alca151 Backport PR #25793

### PR DESCRIPTION
**Pull request by bsunanda**
Provide year dependent threshold for ECAL recHits

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by bsunanda** [comment]
@fabiocos We are trying to make some calibration constants for HCAL for the ultra legacy rereco. Aren't some of the preproduction will be done using 10_4?

**Comment by fabiocos** [comment]
@bsunanda the original plan was updated in December, the pre-production for calibration will be done using 10_5_X, 10_4_X has been left only for the MTD production

**Comment by kpedro88** [comment]
@bsunanda please close this PR

**Comment by bsunanda** [comment]
Not needed for 10_4_X

**Pull request closed without merging**
