### PR TITLE
mt safety updates around RecoLocalCalo RecoMET and JetMETCorrections/Type1MET

### PR DESCRIPTION
**Pull request by slava77**
this should clear most relevant issues reported by the static analyzer in JetMETCorrections/Type1MET RecoLocalCalo and RecoMET

The original was developed in 740pre8. Tested with a short matrix (regular running) to see no difference.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by slava77** [comment]
it's still barely a 1% of legacy modules

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8004	952fdcc
tested in CMSSW_7_4_0_pre8 (test area mt-safe-devA)

short matrix tests pass without differences in the outputs.
The static analyzer shows that the problems reported earlier are gone (ignoring the dead store or dead assignment issues).

Issues related to FFT still remain
JetMETCorrections/FFTJetObjects/interface/FFTJetRcdMapper.h
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_7_4_X_2015-02-25-1400/slc6_amd64_gcc491/llvm-analysis/report-d914d5.html#EndPath
rm * for this code is a more tempting solution

**Comment by slava77** [comment]
-1

Need to fix the problem

**Comment by slava77** [comment]
I couldn't reproduce the build problem
I guess the fix will need to be made blindly via jenkins

**Comment by slava77** [comment]
@cmsbuild please test
lets see if this helps

**Comment by davidlt** [comment]
@slava77 it crashed for me locally too.

```
export SCRAM_ARCH=slc6_amd64_gcc491
scram p CMSSW_7_5_X_2015-02-28-1400
cd CMSSW_7_5_X_2015-02-28-1400
eval $(scram r -sh)
git cms-merge-topic slava77:CMSSW_7_4_0_pre8/mt-safe-devA
scram b -v -k -j 32 COMPILER=llvm 2>&1 | tee b.log
```

```
/data/davidlt/CMSSW_7_5_X_2015-02-28-1400/src/JetMETCorrections/Type1MET/interface/CorrectedMETProducerT.h:98:76: error: default initialization of an object of const type 'const CorrectedMETProducer_namespace::CorrectedMETFactoryT<MET>' without a user-provided default constructor
/data/davidlt/CMSSW_7_5_X_2015-02-28-1400/src/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h:154:90: error: default initialization of an object of const type 'const PFJetMETcorrInputProducer_namespace::InputTypeCheckerT<Jet, PATJetCorrExtractor>' without a user-provided default constructor
/data/davidlt/CMSSW_7_5_X_2015-02-28-1400/src/JetMETCorrections/Type1MET/interface/CorrectedMETProducerT.h:98:76: error: default initialization of an object of const type 'const CorrectedMETProducer_namespace::CorrectedMETFactoryT<CaloMET>' without a user-provided default constructor
/data/davidlt/CMSSW_7_5_X_2015-02-28-1400/src/JetMETCorrections/Type1MET/interface/CorrectedMETProducerT.h:98:76: error: default initialization of an object of const type 'const CorrectedMETProducer_namespace::CorrectedMETFactoryT<PFMET>' without a user-provided default constructor
/data/davidlt/CMSSW_7_5_X_2015-02-28-1400/src/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h:154:90: error: default initialization of an object of const type 'const PFJetMETcorrInputProducer_namespace::InputTypeCheckerT<PFJet, JetCorrExtractorT<PFJet> >' without a user-provided default constructor
```

**Comment by slava77** [comment]
When did we switch to building with clang by default?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8004	aeb9175
jenkins tests confirm the (partial) cleanup of issues spotted by the static analyzer; no differences are found in the reco outputs

**Comment by ktf** [comment]
@slava77 we started building with clang since a few weeks, since we do need to have a working clang build for both the static analyzer and root6 serialization to work correctly.

**Comment by slava77** [comment]
I remember that the builds were added,  but didn't realize that jenkins
test use clang in the pr compilation.

Please add the compiler detail to the jenkins compilation error reports.
This has to be there until scram b uses llvm by default.

**Comment by ktf** [comment]
To clarify, we build PRs both for gcc and clang. The clang command can be found in the first line when you click on the logs:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8004/3000/buildClang.log

**Comment by slava77** [comment]
Giulio,
the setup is clear to me now.
Still, please update the cms-bot messages to be more specific which build failed.
It will be much more clear to the developers.
(we can't expect all developers to test builds with both compilers)

**Comment by ktf** [comment]
The bot said: "I found a compilation error while trying to compile with **clang**" (emphasis added). The actual compilation command is inside the details pointed by the bot. If you have suggestions on how to improve the current setup, I'm happy to ask @nclopezo to implement it, however at this point I'm not sure what you are asking for.

**Comment by slava77** [comment]
This tells how much attention I paid to that part of the message heading.

Since it's a non-default compiler setup, please add a link or text to the message how to reproduce (either what David posted or the ``` scram b vclean && scram build -k -j 8 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile' ``` that I can find at the jenkins build log [the non-verbose from jenkins tests may be easier] )

**Pull request merged**
