### PR TITLE
L1T offline DQM directory cleanup

### PR DESCRIPTION
**Pull request by thomreis**
Grouping all L1T offline DQM efficiency plots made with Reco objects in the same directory structure for clarity.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

This PR does not create or change histograms but just moves some to different directories.

**Comment by thomreis** [comment]
Hi @jfernan2 @dmitrijus 
please review this PR so that it can go in pre2 if possible.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
