### PR TITLE
Added EventSetup consumes calls to MuonNumberingESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added EventSetup consumes calls to MuonNumberingESProducer.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Part of #26584

**Comment by Dr15Jones** [comment]
Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
