### PR TITLE
sort or order btags in python configuration

### PR DESCRIPTION
**Pull request by slava77**
this was triggered by observed non-repeatable btag comparison plots https://github.com/cms-sw/cmsdist/pull/7112#issuecomment-876589924

apparently the difference originates from python `set` being not ordered (not repeatable either)

I found two places based on config dumps of 136.88811 and 136.874 
- setupBTagging where the patJets discriminatorSources (and related) are defined using python set
- DeepDoubleX : here the clone parameters were using a set display `{ }` (instead of a more common list display `[ ]` that we use in other python configs

@makortel 
the order of the following is not repeatable; This may complicate the edmConfigDump-based comparisons:
- `canDeleteEarly` 
- `logErrorHarvester.excludeModules` and `.includeModules`

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
> the order of the following is not repeatable; This may complicate the edmConfigDump-based comparisons:

Thanks, I'll take a look.

**Comment by makortel** [comment]
> the order of the following is not repeatable; This may complicate the edmConfigDump-based comparisons:
> 
> * `canDeleteEarly`
> * `logErrorHarvester.excludeModules` and `.includeModules`

These are addressed in https://github.com/cms-sw/cmssw/pull/34412

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34409	b325bb2 
- code changes are technical for the physics results, but is meant to recover the simple functionality of the reco comparison scripts
- jenkins tests pass and comparisons with the baseline show differences only in the pat jet tagging variables in reco comparison script outputs; no differences appear in the DQM plots
- a manual check of the step2.root output of the wf 136.88811 using https://github.com/slava77/cms-reco-tools/blob/master/printFWLite.C#L90 `compare_patJets_btags` shows that the order of tagging variables changed to alpha-ordered and the saved values did not change
- repeatability of configuration was checked with config dump before the PR was made

**Comment by qliphy** [comment]
+1

**Pull request merged**
