### PR TITLE
migrate to concurrent DQM

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
An alternative implementation of #21764, for reference.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
I understand that @VinInn is OK with these changes.

@vazzolini, @kmaeshima, @dmitrijus, could please sign or comment ?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
This pull request is causing a crash in the IBs. 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_X_2018-01-17-1100/pyRelValMatrixLogs/run/5.4_ZEE+ZEEFS+HARVESTFS/step1_ZEE+ZEEFS+HARVESTFS.log

The problem is DTSegment2DSLPhiQuality is a legacy EDAnalyzer which does NOT inherit from DQMEDAnalyzer. The module is calling directly into the DQMStore at global begin Run and happens to do it at the exact same time as PrimaryVertexMonitor.

**Comment by Dr15Jones** [comment]
DTSegment2DSLPhiQuality did not cause a problem previously because the DQMEDAnalyzers were all stream modules so they filled their histograms at streamBeginRun and streamBeginLuminosityBlock which happen after their global counterparts.

**Comment by Dr15Jones** [comment]
DTRecHitQuality is also causing crashes in the beginRun for the same reason as DTSegment2DSLPhiQuality.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_X_2018-01-17-1100/pyRelValMatrixLogs/run/5.6_QCD_FlatPt_15_3000+QCDFlatPt153000FS+HARVESTFS/step1_QCD_FlatPt_15_3000+QCDFlatPt153000FS+HARVESTFS.log

**Comment by fabiocos** [comment]
@fwyzard @Dr15Jones given that we need to converge for pre4, I will revert the PR in case we do not have quickly a fix

**Comment by Dr15Jones** [comment]
DTSegment4DQuality is also causing crashes:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_10_0_X_2018-01-17-1100/pyRelValMatrixLogs/run/5.3_SingleMuPt100+SingleMuPt100FS+HARVESTFS/step1_SingleMuPt100+SingleMuPt100FS+HARVESTFS.log

**Comment by VinInn** [comment]
Do I understand correctly that before any module is migrated to the new concurrent DQM ```DTSegment2DSLPhiQuality``` need to be fixed (as well as any other module operating in the same way)?
 @kmaeshima, @dmitrijus please take note

**Comment by dmitrijus** [comment]
Reverting this PR will not solve the issue...

I will migrate/disable DTSegment2DSLPhiQuality later today.

**Comment by fwyzard** [comment]
> Do I understand correctly that before any module is migrated to the new concurrent DQM `DTSegment2DSLPhiQuality` need to be fixed (as well as any other module operating in the same way)?

Correct.

**Pull request merged**
