### PR TITLE
pr91x Update 2023 RelVal workflows with HLT@fake2

### PR DESCRIPTION
**Pull request by rekovic**
91x PR

Switch from HLT@fake to fake2 in 2023 RelVal workflows, by changing the 
configuration of upgradeWorkflowComponents. 

This is needed since we are switching from L1TLegacy to L1TStage2 for Phase2, 
and HLT PR 91x #17796 is introducing an appropriate HLT@fake2 menu. 

To test, needs in 91x both #17796 (already merged) and #17709.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test
@rekovic - do we need a merged PR with your L1 PR to get the tests to be happy?

**Comment by rekovic** [comment]
@davidlange6
Yes.  To get the tests for this PR happy, you also need to merge #17709.

Also answered in https://github.com/cms-sw/cmssw/pull/17709#issuecomment-285360938.

**Comment by davidlange6** [comment]
so then I need one pr not two... could you merge them together

**Comment by rekovic** [comment]
@davidlange6 
Done.
Now this PR is merged into PR #17709 (91x) and #17629 (90x).

**Pull request closed without merging**
