### PR TITLE
Improve constructor for PhotonIsolationCalculator

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

It is in general better to use a constructor rather than a setup method.

#### PR validation:

Compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
After the merge of https://github.com/cms-sw/cmssw/pull/46276 there is a conflict

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
