### PR TITLE
Hcal ODF Corrections - new condition object

### PR DESCRIPTION
**Pull request by audrium**
The goal of creating this new HCAL condition object is to store these parameters:
https://github.com/cmssw/cmssw/blob/CMSSW_7_2_X/RecoLocalCalo/HcalRecAlgos/src/HcalSimpleRecAlgo.cc#L459
into the Offline Database

### CODE REVIEW

**Comment by abdoulline** [comment]
The compilation error has to be fixed. This PR is still aimed at 740.

**Comment by ktf** [comment]
please test

**Comment by davidlange6** [comment]
Is this PR obsolete? Seems still not to compile...

**Comment by abdoulline** [comment]
Hope for some fix/progress this week, so please, don't close it...

**Comment by davidlange6** [comment]
I'll close this so I can stop looking at it - doesn't merge nor compile at this point.. Reopen or just make a new pull request once needed (but we are running out of time for 2015 reco now)

**Comment by abdoulline** [comment]
OK. It's not really a showstopper for 2015, but just a (first) attempt to 
get a group of hardwired parameters moved from code to DB, which has just 
failed at the moment.

**Pull request closed without merging**
