### PR TITLE
Run2-sim18 Give optional possibility of reproducing old error in ECAL simulation

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , what is the reason of this PR, there is ECal group request?

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
-1
i would think that the 71x release is sufficient for a check and move on to the fixed code..

**Comment by bsunanda** [comment]
Agree with David. Closing the PR

**Pull request closed without merging**
