### PR TITLE
[test only] add CUDA 9.1.85 samples

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#3629

**Comment by fwyzard** [comment]
@smuzaffar , is there a way to request a test build with llvm/clang ?

**Comment by smuzaffar** [comment]
@fwyzard , currently there is now way to do it via github comment but I can force start a test using clang IB.

**Comment by fwyzard** [comment]
Thanks.

I wanted to check if this actually worked with clang 4 - however I've noticed that in the meantime we moved to clang 5, which is not supported.

So there is no need to try...

**Comment by fwyzard** [comment]
OK, that's a different kind of error.

How can I reproduce the test locally ?

**Comment by smuzaffar** [comment]
@fwyzard , by doing something like
```
scram p CMSSW_10_0_CLANG_X_2017-12-17-0000
cd CMSSW_10_0_CLANG_X_2017-12-17-0000
cmsenv
git cms-merge-topic -u 21700
scram build
```

**Comment by fwyzard** [comment]
Ah OK - I was looking for them on SLC7, but now I see that CLANG builds are SLC6.
I'll have a look, thanks.

**Pull request closed without merging**
