### PR TITLE
replace TTbar_Tauola_13TeV_cfi with TTbar_13TeV_TuneCUETP8M1_cfi

### PR DESCRIPTION
**Pull request by franzoni**
- replace TTbar_Tauola_13TeV_cfi with TTbar_13TeV_TuneCUETP8M1_cfi
- follow up to: https://hypernews.cern.ch/HyperNews/CMS/get/relval/3550/6.html

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
@bendavid
@inugent

**Comment by davidlange6** [comment]
+1

**Pull request merged**
