### PR TITLE
TkAl: protect unit tests against empty queries and drop unused tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is in response to https://github.com/cms-sw/cmssw/pull/44467#issuecomment-2031697824. 
Protect the unit test such that it doesn't fail in case the DAS query doesn't find any useful run (which should not happen in any case).
Also in fe9b0a50868bcd01d7886146c456588528126efc drop an unused test configuration.

#### PR validation:

Run successfully:
   * `scram b runtests_SubmitPVsplit`
   * `scram b runtests_SubmitPVrbr`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
