### PR TITLE
Added missing efficiency histograms.

### PR DESCRIPTION
**Pull request by mohsinwaseem**

### CODE REVIEW

**Comment by mtosi** [comment]
@mohsinwaseem, 
first thanks
then, could you please quantify the increase in # bins, please ?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mohsinwaseem** [comment]
@mtosi what increase in number of bins?

**Comment by mtosi** [comment]
this PR is not adding histograms ?
=> it will add bins !

**Comment by mohsinwaseem** [comment]
@mtosi 
This PR is adding efficiency histograms that were missing. The input num and den histos were already present.

**Comment by mtosi** [comment]
I understand that both numerator and denominator were already there,
but aren't you adding the efficiency plot ?!?!!?!?!?

**Comment by mohsinwaseem** [comment]
So there are four 1-D phi plots -> 32*4 = 128 Bins.
For added 2-D plots, the bins added are as follows.
11 EtaPhi plots = 11*24*32 = 8448
15 PtEta plots = 15*60*24 = 21600 
4 EtaPhiHep17 plots = 4*10*18 = 720
3 PhiPhi plots = 3*32*32 = 3072
3 PtHT plots  = 3*60*60 = 10800

This makes the total of 44768 bins.

**Comment by mtosi** [comment]
pardon me,
I think it is not clear to me "32

*4 = 128 Bins."*

*  mia*

**Comment by mohsinwaseem** [comment]
I have edited the comment replacing * with X.

It means that the histogram for phi has 32 bins. there are total 4 histograms for phi that are added so it makes a total of 128 bins.
Similarly for 2-D histos, for instance EtaPhi plots have 24X32 bins. (24 for Eta and 32 for Phi). And there are 11 histograms so 11X24X32 makes 8448 bins.

and hence forth.

-----------------
Best Regards
Mohsin
________________________________

**Comment by mtosi** [comment]
;)
thanks
  mia

**Comment by mohsinwaseem** [comment]
@cmsbuild @mtosi Following a discussion with expert, I would like to roll back some minor changes in TopMonitoring_cff.py.

Can I do it?

**Comment by mtosi** [comment]
uhmm, are you decreasing the number of bins, you aren't ?

**Comment by mohsinwaseem** [comment]
no actually the number of bins has increased as a result of this new update that I just did. There were two files so I had to do them separately using online editor.

I will quantify additional bins in a moment.

**Comment by mtosi** [comment]
please

**Comment by mohsinwaseem** [comment]
4 jetMulti plots = 4X11 = 44
4 bjetMulti plots = 4X6 = 24
3 muMulti plots = 3X6 = 18
2 eleMulti plots = 2X6 = 12

Total additional bins = 98

**Comment by mtosi** [comment]
uhmm, sorry
98 is the number of extra histograms or extra bins ?

**Comment by mohsinwaseem** [comment]
number of extra bins from 13 histograms

**Comment by mtosi** [comment]
on top of the number you quoted before ?

**Comment by mohsinwaseem** [comment]
yes

**Comment by mtosi** [comment]
I know it is a silly sum
but can you please answer to the question
w/ the final number of extra bins you are adding, please ?
thanks !

**Comment by mohsinwaseem** [comment]
Sure,

Added 1-D histograms:
4 phi plots = 32X4 = 128 
4 jetMulti plots = 4X11 = 44
4 bjetMulti plots = 4X6 = 24
3 muMulti plots = 3X6 = 18
2 eleMulti plots = 2X6 = 12

Added 2-D histograms
11 EtaPhi plots = 11X24X32 = 8448
15 PtEta plots = 15X60X24 = 21600
4 EtaPhiHep17 plots = 4X10X18 = 720
3 PhiPhi plots = 3X32X32 = 3072
3 PtHT plots = 3X60X60 = 10800

Total number of additional bins =  44866

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
