### PR TITLE
Retrieval of PPS diamond detector mapping from XML and CondDB

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

The aim of this PR is **to discuss the possible approach** to retrieval of PPS diamond detector mapping from XML and CondDB.

Moving mapping records to CondDB would give us flexibility in upcoming run.
On the other hand migration of all mapping records (including Run2) means validation of Run2 data reconstruction.

Therefore we explore the possibility to stay with XML-based records for Run2 and 2022 data, while retrieving the records from CondDB in 2023 run.

#### PR validation:

Validation is still ongoing, this PR is meant to serve as a place to discuss the code.

### CODE REVIEW

**Comment by tvami** [comment]
@grzanka please do `code-checks` so the bot properly triggers all parties

**Comment by grzanka** [comment]
> @grzanka please do `code-checks` so the bot properly triggers all parties

Sure, we can fix it. We are however still developing the code to "switch" between XML and CondDB data sources, as seen here:
https://github.com/cms-sw/cmssw/pull/40765/files#diff-1eb4c964687bc0dbea0102fa7d717cc7f42908aa1979fbc22cde1db187b8e3faR147

The idea of this PR was basically to discuss the code.

**Comment by tvami** [comment]
> The idea of this PR was basically to discuss the code.

I understand, but the people who sign are not notified until code checks is satisfied. I got here bc of Vale's talk just a bit ago

**Comment by mmusich** [comment]
It looks like this PR is trying to fix an original sin of PPD conditions.

> On the other hand migration of all mapping records (including Run2) means validation of Run2 data reconstruction.

if there are (even minor) changes shouldn't they show up in this PR integration tests? I guess PPD DQM is run several (Run-2) workflows. If by-bin comparisons come out perfectly clean, wouldn't that be a sufficient proof?

> Therefore we explore the possibility to stay with XML-based records for Run2 and 2022 data, while retrieving the records from CondDB in 2023 run.

mixing XML and Conditions database sort of defies the purpose of GlobalTags. 
https://github.com/cms-sw/cmssw/blob/f1d17c6a27e19a5dc6b55213dc2006c5dae1eeee/CalibPPS/ESProducers/test/test_readTotemDAQMapping.py#L31-L43

setting aside fetching conditions from an sql file in production jobs (which is totally incompatible with the CMS computing model), do you still plan to have a separate `ESSource` ?

**Comment by tvami** [comment]
> Therefore we explore the possibility to stay with XML-based records for Run2 and 2022 data, while retrieving the records from CondDB in 2023 run.
> mixing XML and Conditions database sort of defies the purpose of GlobalTags.

I wrote this to Vale on mattermost, but let me stress that we really should *not* do this mixing.

**Comment by vavati** [comment]
@mmusich @tvami : you are right, this is the original sin and i am still convinced that we should pay the price (this is the history of mankind!)
 In details:
- it seems that to include the diamond mapping in condDB we need to modify the behavior of the data unpacker. Which is a monster used for several different HW (detector type). Unfortunately the layout of this project has changed during the years. very different from any central detector.
- this change could be just the top of the iceberg: we still have "strips", "ufsd", "sampic" , "T2" on xml
- i understand that the mix solution is not good for you. For the backward compatibility and tests I don't think we have "relval" for all the layouts in the past. For sure it will require an effort on our side to validate the past and of course the present
- after all we are not talking about calibrations which change often but about mapping which changes per detector ~1 year at max 
Honestly we really want to go on a series of complicated PRs and validation rather than approving few simple PRs per year?

**Comment by tvami** [comment]
I would agree with you Vale if

>  few simple PRs per year?

was true, but having all these interdependencies of the `eras` is everything but simple. :D

I understand https://github.com/cms-sw/cmssw/pull/40765/commits/2e9a0f7e31f21a7e4d542e9d58ef0213a3cf8c2f already switched sources in the unpacker, is there more to do here?

**Comment by mmusich** [comment]
> after all we are not talking about calibrations which change often but about mapping which changes per detector ~1 year at max

just to add the *all* other subsystems in CMS store cabling / e-maps in DB and they all do changes with rate of ~1 per year.

**Comment by grzanka** [comment]
During this PR we learned a lot how to make the transition to the CondDB. We propose to postpone the migration to the summer time this year and focus now on other tasks. At that time we also foresee to complete the project of LHCInfo (some work needs to follow after https://github.com/cms-sw/cmssw/pull/40817 is merged).

**Comment by emanueleusai** [comment]
-1

- remove from dqm queues

**Comment by tvami** [comment]
-1
 * remove from the queues

**Comment by jfernan2** [comment]
-1
To clean the queue

**Pull request closed without merging**
