### PR TITLE
Remove left over uGMT ZS configuration [12_4_X]

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This removes some left over calls to modules that were removed in https://github.com/cms-sw/cmssw/pull/38115.

cc @pmandrik and @vukasinmilosevic

Backport of #40107.

### CODE REVIEW

**Comment by emanueleusai** [comment]
type l1t

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40107

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- this is a config edit that was deployed online already during the HI run.

**Comment by perrotta** [comment]
+1
- Merging just to have the offline release aligned with what deployed in the online DQM release at P5 at the end of the data taking: there will be no real usage for this PR in a possible future release in this cycle.

**Pull request merged**
