### PR TITLE
Fix logical error in the check of mask flag bits [13_1_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

1) This PR fixes a bug in the ECAL DQM code which affected the check of status flag bits set on each channel.
For eg in EnergyTask.cc [here](https://github.com/cms-sw/cmssw/pull/41830/files#diff-e149a50e5de8ea1748eb4c84b4e56343a2bc188557b1f50268ce94230986d823L42) and [here](https://github.com/cms-sw/cmssw/pull/41830/files#diff-e149a50e5de8ea1748eb4c84b4e56343a2bc188557b1f50268ce94230986d823L46) all other flag bits except kGood and kPoorCalib are being checked when the mask is bitwise inverted, but this is not what was intended. 
The intended behaviour is to check whether kGood or kPoorCalib is set, if not then ignore that channel.
Similar changes are made in other affected files OccupancyTask.cc and TimingTask.cc

2) Another small fix is made to change the PU condition in MLClient.cc to ignore the PU=0 runs for the ML inference.

#### PR validation:

This was validated by running the online DQM workflow and testing the plots on a test DQM GUI.
Also validated by running the runtheMatrix workflow 136.874

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 13_1_X, which is next in production. 
Master PR is : https://github.com/cms-sw/cmssw/pull/41830

### CODE REVIEW

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41830

**Comment by emanueleusai** [comment]
please test

**Comment by abhih1** [comment]
The test failure seems unrelated to the PR.

**Comment by emanueleusai** [comment]
+1

- unrelated failures

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
