### PR TITLE
Fixed bug which was crashing ROOT in fitting empty histograms

### PR DESCRIPTION
**Pull request by dinardo**
#### PR description:

I fixed a bug that was crashing ROOT: the application was trying to fit empty histograms.
Now I've protected the fit by checking whether the histogram is empty or not

#### PR validation:

Now the crash should not occur anymore

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N.A.

### CODE REVIEW

**Comment by dinardo** [comment]
Are these errors related to my commit?
The very same commit to CMSSW_12_0_X was successful: https://github.com/cms-sw/cmssw/pull/35908

**Comment by qliphy** [comment]
> Are these errors related to my commit? The very same commit to CMSSW_12_0_X was successful: #35908

This needs #35905

**Comment by qliphy** [comment]
please test with #35905

**Comment by emanueleusai** [comment]
please test with #35921

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
