### PR TITLE
Avoid leaking memory in DTDeadFlagHandler

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Avoid leaking on a failed conditions. This was found by the static analyzer.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
+1
@ggovi please have a look

**Comment by silviodonato** [comment]
merge

**Pull request merged**
