### PR TITLE
Remove old-style track associators

### PR DESCRIPTION
**Pull request by makortel**
The Event-based track-TrackingParticle associators were introduced in #7175. This PR migrates the remaining references (either in configuration or code) to old-style track associators to the new-style, and finally removes the old-style associators, in order to avoid confusion and to reduce maintenance burden (e.g. in #8540 I fixed only the new-style associators).

No regression expected, none observed. Tested in CMSSW_7_5_X_2015-03-24-1100, but rebased on top of CMSSW_7_5_X_2015-03-31-2300 (due to a merge conflict).

@rovere @VinInn

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by cvuosalo** [comment]
Jenkins alternative-comparisons are showing differences for workflow 4.22_RunCosmics2011A. Two out of 558 muon DT segments disappear from several plots. This PR should not cause any differences, so there may be a problem. I will run short matrix tests against baseline CMSSW_7_5_X_2015-03-31-2300 to see if the differences persist. Jenkins used baseline CMSSW_7_5_X_2015-04-01-1100.
4 22select

**Comment by slava77** [comment]
I think I've seen DTSegmentsMonitor occasionally has differences like
this, most likely due to some ininitialized variables

On 4/2/15 4:21 PM, Carl Vuosalo wrote:
> Jenkins alternative-comparisons are showing differences for workflow
> 4.22_RunCosmics2011A. Two out of 558 muon DT segments disappear from
> several plots. This PR should not cause any differences, so there may be
> a problem. I will run short matrix tests against baseline
> CMSSW_7_5_X_2015-03-31-2300 to see if the differences persist. Jenkins
> used baseline CMSSW_7_5_X_2015-04-01-1100.
> 4 22select
> <https://cloud.githubusercontent.com/assets/5736159/6973942/2287bb86-d954-11e4-9670-6e52b763e8d5.png>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8635#issuecomment-89047584>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by cvuosalo** [comment]
+1

For #8635 9b9fdeb395bdf29b5235dee789f00915b58c8a26

This PR removes obsolete track associators. It should not change program outputs since it is removing leftover features that are no longer used.

The code changes are satisfactory, as are the Jenkins tests. The small differences noted above are spurious and not related to this PR.

Short matrix tests against baseline CMSSW_7_5_X_2015-03-31-2300 show no significant differences, as expected.

**Comment by makortel** [comment]
Referring to @slava77's https://github.com/cms-sw/cmssw/pull/8635#issuecomment-89055463, would it be possible to try to get these fixed (as they arise)? These random differences are somewhat annoying when testing purely technical developments.

**Comment by deguio** [comment]
@makortel 
I am aware of this but I wasn't able to fix it quickly when I had a quick look. I guess I need to spend some more time on this.
F.

**Pull request merged**
