### PR TITLE
Gathering detail plots into directories, online & offline & relval & …

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
We have several updates on GEM onlineDQM.

- Plots for detailed information per chambers are gathered into directories
- Online & offline & relval & allplot modes
- Removed non-useful plots and stuffs

This PR is a backport to CMSSW_12_3_X of #37786.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
backport of #37786

**Comment by perrotta** [comment]
+1

**Pull request merged**
