### PR TITLE
Jet ID and b-tag information for Scouting Calojets (80X)

### PR DESCRIPTION
**Pull request by duanders**
Backport of https://github.com/cms-sw/cmssw/pull/14271 to 80X.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
@davidlange6  Are there restrictions on format changes to scouting products?

**Comment by Martin-Grunewald** [comment]
Well, can we move on this, please?

**Comment by davidlange6** [comment]
Hi @Dr15Jones- there are (you wrote them).adding simple types was within them - was there something here that you were worried about root supporting long term?

**Comment by Dr15Jones** [comment]
+1
I hadn't remembered what was allowed or not allowed so wanted confirmation from someone with a working memory :)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
