### PR TITLE
add 2018 Prod-like workflow w & w/o bParking

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:

Adding 2018 production-like workflows to relvals.

#### PR validation:

Workflow 1304.18 runs out-of-box locally. The 1304.181 will need another PR (back port of https://github.com/cms-sw/cmssw/pull/26325)

#### if this PR is a backport please specify the original PR:
backport of https://github.com/cms-sw/cmssw/pull/26365

### CODE REVIEW

**Comment by kpedro88** [comment]
backport of #26365

**Comment by kpedro88** [comment]
I'm now somewhat confused about the status of this PR. If #26404 is the backport of #26365, why is this PR also listed as a backport of that PR?

**Comment by kpedro88** [comment]
please test workflow 1304.18,1304.181 with #26404

**Comment by fabiocos** [comment]
@kpedro88 @prebello @zhenhu this is required for the next 10_2_X version, the RECO part for low pt electrons has been already merged. Could you please check and sign, or comment?

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
