### PR TITLE
[12_4_X] Add new functions to AlCaNano.py needed for the T0 replay

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

see https://github.com/cms-sw/cmssw/pull/38664

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/38664

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38664

**Comment by tvami** [comment]
urgent
 * should be in 12_4_3

**Comment by tvami** [comment]
type ecal,bugfix

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+1

 - verbatim backport
 - will be tested in Tier0 replay

**Comment by tvami** [comment]
@qliphy can you please merge this too? the master IB is fine

**Comment by qliphy** [comment]
+1
bug fix

**Pull request merged**
