### PR TITLE
added esConsumes to modules in L1Trigger/CSCTriggerPrimitives

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 3 modules

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This was done under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @rekovic

**Comment by silviodonato** [comment]
merge

**Pull request merged**
