### PR TITLE
Update TSG tests from 2017 real data to 2018 real data (11_1_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Update TSG tests from 2017 real data to 2018 real data (11_1_X)
Based on CMSSW_11_1_2_patch1

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #30882 

Avoid flood of error messages in log files of tests

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #30882

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
