### PR TITLE
 new T0 scenario ppEra_Run2_2016_pA; migration of customise_PPwithHI to eras (fw port of #16394)

### PR DESCRIPTION
**Pull request by slava77**
[copy-paste from the 80X PR, mostly]
- no changes to the currently available workflows
- customisePPrecoForPeripheralPbPb should be replaced by Run2_25ns_peripheralPbPb
- customisePPrecoforPPb  is replaced by Run2_2016_pA
- added T0 scenario ppEra_Run2_2016_pA to be used for the upcoming pA processing
- cleaned up some remaining imports of global Eras

Primary reason that forced the move to eras was the event content edits, which are not compatible with the DataProcessing workflow setup (fully python process preparation). In 75X for pp reference run we ended up making edits in the actual release.
Given that special settings are applicable to both data and MC, it is more appropriate to have them set up using eras.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by goni** [comment]
Hi @slava77 , Do we need to use --era Run2_2016_pa regarding this PR #16288 #16289 ?

**Comment by slava77** [comment]
On 11/1/16 5:32 AM, Geonhee Oh wrote:
> Hi @slava77 <https://github.com/slava77> , Do we need to use --era
> Run2_2016_pa regarding this PR #16288
> <https://github.com/cms-sw/cmssw/pull/16288> #16289
> <https://github.com/cms-sw/cmssw/pull/16289> ?
> 

yes

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16405   baf8f72
- jenkins tests pass and comparisons show no differences
- local test with wf 281 show no differences in output products or running modules or in monitored quantities (wf 281 is tha pPb workflow which had the customise_PPwithHI use replaced by the new pA era)

**Pull request merged**
