### PR TITLE
Only call consumes in ElectronSeedProducer if actually needed

### PR DESCRIPTION
**Pull request by Dr15Jones**
A data product is only consumed if a particular parameter value is used.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
We found this when we were comparing what modules said they consumed to what their actual dependencies were.

**Comment by Dr15Jones** [comment]
please test
[try to test without the global tag change]

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
