### PR TITLE
HLT TDR event content refinements: 11_1_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

tweaks the TDR event content to fix some missing products as well as removing some unnecessary ones

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

back port of https://github.com/cms-sw/cmssw/pull/30972 needed for HLT TDR production event content

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
back port of #30972

**Comment by Martin-Grunewald** [comment]
backport of #30972

**Comment by silviodonato** [comment]
urgent

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
