### PR TITLE
[13_0] Preserve electron mass after FastSim Bremsstrahlung emmision

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/42250

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by sbein** [comment]
+1 Thanks Phat

**Comment by perrotta** [comment]
> +1 Thanks Phat

@sbein I imagine you wanted to approve for fastsim. However, if the"+1" is not in an isolated line, bot does not recognize it as an approval. I'm going to edit your comment, assuming this is what you meant

**Comment by sbein** [comment]
+1

**Comment by sbein** [comment]
> > +1 Thanks Phat
> 
> @sbein I imagine you wanted to approve for fastsim. However, if the"+1" is not in an isolated line, bot does not recognize it as an approval. I'm going to edit your comment, assuming this is what you meant

Sorry! Thanks @perrotta!

**Comment by perrotta** [comment]
+1

**Pull request merged**
