### PR TITLE
Clang tidy checks - fix clang warnings

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes the last failures when the checks in https://github.com/cms-sw/cmssw/pull/30508 were applied. 
The checks created const refs with the original types which resulted in clang warnings:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fc4bbb/7669/clang-new-warnings.log

#### PR validation:

Builds, clang checks and format passes

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
@rekovic do you have any comments?

**Comment by silviodonato** [comment]
@mrodozov I solved a conflict, please double check https://github.com/cms-sw/cmssw/pull/30632/commits/7b6ce551ed1b41988a2c66d752fd19bc19bcf21c . Thank you
@rekovic

**Comment by silviodonato** [comment]
please test

**Comment by mrodozov** [comment]
@silviodonato I see redundant headers removed, should be fine

**Comment by silviodonato** [comment]
merge

**Comment by jfernan2** [comment]
+1
For the records

**Pull request merged**
