### PR TITLE
Rebased full l1 to2 ofor81 x

### PR DESCRIPTION
**Pull request by kkotov**
This PR is a cleaner version of https://github.com/cms-sw/cmssw/pull/15516

### CODE REVIEW

**Comment by mmusich** [comment]
@kkotov, thanks!

**Comment by mmusich** [comment]
please tesr

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by kkotov** [comment]
Looks like the testing went fine. I just realized that there is one more commit needed to this branch before we can merge it. This is merely a little bug fix in the XML parser, but I'll better wait till the author comes back next week to do it himself.

Meanwhile, I'd encourage @ggovi to start reviewing the (mostly cosmetic) changes to the CondFormats classes, as, I suspect, this sensitive area may require the highest level scrutiny.

**Comment by kkotov** [comment]
The XML parser's bugfix is in. But before we test it I'll need to push yet another change that has to deal intelligently with the broken XML configuration for the uGT. That should be implemented imminently.

**Comment by kkotov** [comment]
Now this branch is ready for the integration. Another PR https://github.com/cms-sw/cmssw/pull/15814 is mirroring the commits in this branch for 80X

**Comment by franzoni** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by kkotov** [comment]
Should we maybe try restarting the tests in a hope that DAS is back operational?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kkotov** [comment]
I have to create yet another rebased version and PR it separately. Closing this PR, opening a new one ...

**Pull request closed without merging**
