### PR TITLE
Efficiencies of CSC trigger primitives in validation step and clean-up

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Addition of efficiencies of CSC trigger primitives vs true muon |eta| in validation step (through truth-matching of simtracks to ALCT/CLCT/LCT). 

Also, I gave the code a thorough clean-up. 
   * Added missing titles and labels for histograms
   * Fixed bin ranges where necessary
   * Changed to more obvious naming of histograms (ending with "_MEXY" instead of a number 1 through 10)
   * Filled the existing wire Y and strip X position resolution plots

#### PR validation:

Tested with a 11_2_0_pre7 single muon relval (```/store/relval/CMSSW_11_2_0_pre7/RelValSingleMuPt10/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v8-v1/20000/0ED98457-2CEC-924D-AAFC-4F3F705C2DCC.root```)

Code can be tested with
```
cmsRun Validation/MuonCSCDigis/test/runCSCDigiValidation_cfg.py
cmsRun Validation/MuonCSCDigis/test/runCSCDigiHarvesting_cfg.py
cmsRun Validation/CSCRecHits/test/runCSCRecHitValidation_cfg.py
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

FYI @tahuang1991 @ptcox @AFJohan92

### CODE REVIEW

**Comment by dildick** [comment]
A few screenshots of a short run: 

(1) an ALCT efficiency plot
Screen Shot 2021-03-06 at 1 19 59 AM

(2) an LCT efficiency plot
Screen Shot 2021-03-06 at 1 24 04 AM

(3) Histograms end with MEXY
Screen Shot 2021-03-06 at 1 20 25 AM

(4) Most histograms were given more appropriate titles and labels
Screen Shot 2021-03-06 at 1 20 44 AM

**Comment by dildick** [comment]
A few more timing plots (such plots sometimes show up as differences in PR integration tests)

Screen Shot 2021-03-06 at 1 48 09 AM

Screen Shot 2021-03-06 at 1 47 34 AM

**Comment by dildick** [comment]
@jfernan2 Could you start the tests, please?

**Comment by qliphy** [comment]
please test

**Comment by dildick** [comment]
Some clean-up is also needed in `CSCRecHits`. I'll fix it asap.

**Comment by dildick** [comment]
@qliphy I'll run a standard WF to see if it would run now.

**Comment by dildick** [comment]
@civanch Could you stop the tests? It would appear that a module is still not registered.

**Comment by dildick** [comment]
In WF 11650.0

```
----- Begin Fatal Exception 08-Mar-2021 13:52:37 CST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] While attempting to load plugin CSCRecHitValidation
Exception Message:
unable to load /uscms_data/d3/dildick/work/CSCValJohan/CMSSW_11_3_X_2021-03-04-2300/lib/slc7_amd64_gcc900/poisoned/plugin-poisoned-ValidationCSCRecHitsPlugin.so because /uscms_data/d3/dildick/work/CSCValJohan/CMSSW_11_3_X_2021-03-04-2300/lib/slc7_amd64_gcc900/poisoned/plugin-poisoned-ValidationCSCRecHitsPlugin.so: cannot open shared object file: No such file or directory
----- End Fatal Exception ----
```

**Comment by civanch** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@silviodonato I need to disable the CSCStubEfficiencyValidation for Run-1 and Run-2 and fastsim, as it relies on GEM information being present. Perhaps at some point I could update the code so that it can handle Runs 1, 2 and 3. I'll also check what's going on with the CSCRecHitValidation

**Comment by dildick** [comment]
The last commit should fix the fastsim issue. Not yet sure what to do about the other errors.

**Comment by dildick** [comment]
The last commit should work for WF 10042.0

**Comment by dildick** [comment]
Okay, WF 10042.0 runs

```
10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Tue Mar  9 12:58:14 2021-date Tue Mar  9 12:40:20 2021; exit: 0 0 0 0 0 0
1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 failed
```

@jfernan2 Can you reinitiate the tests? Most should succeed now.

**Comment by dildick** [comment]
@silviodonato Can you rerun the tests, please?

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
Looks like I need to switch off the efficiencies for fastsim altogether, or change the label for the simtracks.

**Comment by dildick** [comment]
This should fix the fastsim

**Comment by jfernan2** [comment]
@dildick  have you tested your changes locally? Thanks

**Comment by dildick** [comment]
This was from half an hour ago:
```
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Mar 11 06:07:17 2021-date Thu Mar 11 05:53:30 2021; exit: 0 0 0
1 1 1 tests passed, 0 0 0 failed
```

**Comment by dildick** [comment]
```
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Thu Mar 11 07:00:28 2021-date Thu Mar 11 06:49:54 2021; exit: 0 0
1 1 tests passed, 0 0 failed
```

**Comment by dildick** [comment]
@jfernan2 This should fix the issue with WF 5.1 and 135.4

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick  there are entries in most of the plots 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-10-2300+f94ccb/41648/dqm-histo-comparison-summary.html

but I cannot judge if they are what you expect, could you please have a look? Thanks

**Comment by dildick** [comment]
I see that some WFs have entries in the CSC digi and rechit occupancy plots. That is good. I also checked those plots with a relval. It was much clearer then. Efficiency plots look mostly empty. Three plots have one bin filled. I guess in that test there was only one true muon in 10 events that went through a CSC chamber and produced digis and stubs.

**Comment by dildick** [comment]
@AFJohan92 You made a few plots for a relval, right? Can you attach them to this PR for reference?

**Comment by civanch** [comment]
unhold

**Comment by AFJohan92** [comment]
> @AFJohan92 You made a few plots for a relval, right? Can you attach them to this PR for reference?

Yes, I've attached example plots from each of the categories with filled plots. They were done with 8k events from the following relval: /store/relval/CMSSW_11_2_0_pre7/RelValSingleMuPt10/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v8-v1/20000/0ED98457-2CEC-924D-AAFC-4F3F705C2DCC.root

Please let me know if there's anything else I should add.
CSCComparatorDigisPerLayer_ME31
CSCComparatorDigisPerEvent
CSCComparatorDigiTime_ME22
CSCComparator3StripAmplitude_ME21
CLCTDigisPerEvent
CSCCLCTDigisPerChamber_ME21
CSCCLCTDigiTime_ME1B
ALCTDigisPerEvent
CSCALCTDigisPerChamber_ME13
CSCALCTDigiTime_ME12
CSCLCTOccupancyNum_ME41
CSCLCTOccupancyDenom_ME32
CSCCLCTOccupancyNum_ME31
CSCCLCTOccupancyDenom_ME22
CSCALCTOccupancyNum_ME21
CSCALCTOccupancyDenom_ME1B
CSCLCTEfficiency_ME1A
CSCCLCTEfficiency_ME13
CSCALCTEfficiency_ME12
CSCWireDigisPerLayer_ME1A
CSCWireDigisPerEvent
CSCWireDigiTime_ME42
CSCWireDigiResolution_ME41
CSCStripDigisPerLayer
CSCStripDigisPerEvent
CSCStripAmplitude
CSCStrip4to5
CSCPedestal
CSCComparatorStripAmplitude_ME32

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
