### PR TITLE
Allow ProcessAccelerators to delete Services

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

#40725 deletes an existing Service in `ProcessAccelerator.apply()`, which was noticed in https://github.com/cms-sw/cmsdist/pull/8301#issuecomment-1424072445 to not work, because the `Process` is wrapped into `ProcessForProcessAccelerator` when passed to `ProcessAccelerator.apply()`, and the `ProcessForProcessAccelerator` did not implement `__delattr__()`. This PR implements the `__dellattr__()`.

#### PR validation:

Added unit test succeeds. A simple test configuration reproducing the behavior in https://github.com/cms-sw/cmsdist/pull/8301#issuecomment-1424072445 succeeds.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@makortel @perrotta @rappoccio can we have this in pre4 ?
thanks !

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
