### PR TITLE
bsunanda:Phase2-gem14 Update the forward muon definition in 2023 Geometry scenario

### PR DESCRIPTION
**Pull request by bsunanda**
Correct the shortcoming in PR13916 (etaMax file was missing in PR13916)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Thanks @bsunanda - but could you change the title of this PR to be more descriptive. Thanks

**Comment by bsunanda** [comment]
@davidlange6 Changed the title

**Comment by davidlange6** [comment]
+1

**Comment by boudoul** [comment]
Hi @bsunanda ,
I'm trying to built the phase2 WFs (2023dev and 2023LReco) but it seems that this PR causes problems in the DIGI step for the phase 2 geometries -I put here (*) a snippet of the traceback  -  could you have a look using this recipe ? 


git cms-merge-topic 13923
scramv1 b -j 8
runTheMatrix.py -l 10600

Adding @kpedro88 FYI 
 Many Thanks 

(*)
#5  0x00007fa284763594 in DDValue::doubles() const () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gcc530/libDetectorDescriptionCore
.so
#6  0x00007fa27cc21c40 in RPCGeometryBuilderFromDDD::buildGeometry(DDFilteredView&, MuonDDDConstants const&) () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-0
4-10-0000/lib/slc6_amd64_gcc530/libGeometryRPCGeometryBuilder.so
#7  0x00007fa27cc22bcc in RPCGeometryBuilderFromDDD::build(DDCompactView const*, MuonDDDConstants const&) () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-1
0-0000/lib/slc6_amd64_gcc530/libGeometryRPCGeometryBuilder.so
#8  0x00007fa27cf520bc in RPCGeometryESModule::produce(MuonGeometryRecord const&) () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gc
c530/pluginRPCGeometryESModule.so
#9  0x00007fa27cf53f8c in edm::eventsetup::CallbackProxy<edm::eventsetup::Callback<RPCGeometryESModule, std::shared_ptr<RPCGeometry>, MuonGeometryRecord, edm::eventsetup::CallbackSimpleDecorato
r<MuonGeometryRecord> >, MuonGeometryRecord, std::shared_ptr<RPCGeometry> >::getImpl(edm::eventsetup::EventSetupRecord const&, edm::eventsetup::DataKey const&) () from /cvmfs/cms-ib.cern.ch/201
6-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gcc530/pluginRPCGeometryESModule.so
#10 0x00007fa2972eb7df in edm::eventsetup::DataProxy::get(edm::eventsetup::EventSetupRecord const&, edm::eventsetup::DataKey const&, bool) const () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64
_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#11 0x00007fa2972e4d0b in edm::eventsetup::EventSetupRecord::getFromProxy(edm::eventsetup::DataKey const&, edm::eventsetup::ComponentDescription const*&, bool) const () from /cvmfs/cms-ib.cern.
ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#12 0x00007fa2708b64b2 in RPCTechnicalTrigger::beginRun(edm::Run const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/li
b/slc6_amd64_gcc530/pluginL1TriggerRPCTechnicalTrigger.so
#13 0x00007fa2972a899b in edm::EDProducer::doBeginRun(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/2016-16/slc6_amd64_gcc530
/cms/cmssw/CMSSW_8_1_X_2016-04-10-0000/lib/slc6_amd64_gcc530/libFWCoreFramework.so

**Comment by kpedro88** [comment]
@boudoul @bsunanda - There was some previous discussion about the Phase2 muon geometry here: https://github.com/cms-sw/cmssw/pull/13992#discussion-diff-59030839

If it's still causing problems, needs to be sorted out ASAP.

**Pull request merged**
