### PR TITLE
Heppy 74X integration

### PR DESCRIPTION
**Pull request by cbernet**
Latest version of the Heppy analysis software package, tested in 7_4_1_patch1. 
This PR affects one package that does not belong to Heppy, EgammaAnalysis/ElectronTools. 
These changes have also been requested by @dimarco here: https://github.com/cms-sw/cmssw/pull/9006. 

@gpetruc @arizzi

### CODE REVIEW

**Comment by cbernet** [comment]
Hello, I don't know how to deal with that. 
I tried to merge my branch into the latest IB CMSSW_7_4_X_2015-05-10-1100.
It compiles and runs fine, without any further modification. 

Could a human please help? :-) 
I'd be happy to help in the integration, just let me know what you'd like me to do. 

Thanks, 

Colin

**Comment by cbernet** [comment]
Hi @ktf, would you know how to deal with this? 
Am I supposed to do anything? As I said already my PR is working well even on a recent IB. 
Cheers, 

Colin

**Comment by ktf** [comment]
@nclopezo please restart the tests.

**Comment by cbernet** [comment]
Thanks Giulio! 
Colin

**Comment by monttj** [comment]
+1

**Comment by cbernet** [comment]
Hello, 

Could you please tell me what needs to be discussed so that I can get prepared, 
and also tell me when is the next ORP meeting? 

Many thanks, 

Colin

**Comment by cbernet** [comment]
Hello, 

Could you please let me know what needs to be discussed and when?  
If there is in fact nothing to discuss, could somebody please merge?

Thanks, 

Colin

**Comment by gpetruc** [comment]
Hi Colin,

It was discussed at the ORP yesterday, and this and the other analysis-only
pull requests will be merged soon,

   Giovanni

**Comment by davidlange6** [comment]
+1

**Comment by cbernet** [comment]
Thanks all! 
Colin

**Pull request merged**
