### PR TITLE
Cleanup RPC local reconstruction

### PR DESCRIPTION
**Pull request by jhgoh**
The PR is to cleanup the RPC local reconstruction codes for better readability with help of modern C++ syntax.

The largest change is on the clustering algorithm to remove unnecessary if-statements inside of the loop to make the logic clear and short. 
This does not change actual idea of the clustering, therefore the output should be exactly same as the previous one.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@bapavlov @mileva 
you may want to be added as watchers of the RPC local reco packages.
Edit this file online and submit a pull request to cms-bot 
https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml
(or submit an issue on https://github.com/cms-sw/cms-bot repository)

**Comment by cvuosalo** [comment]
+1

For #14707 3d77b06c57d1a065db761082708c5e6b497e0740

Code clean-up in RPC local reconstruction to improve readability. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-05-29-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
