### PR TITLE
Xi Production gen-fragment

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR add the fragment for the production of a Xi- long lived particle (decayed via GEANT).

This would be needed to have a dedicated production for checking tracking performance for BPH (see e.g. mkFit validation [here](https://indico.cern.ch/event/1087315/contributions/4571634/attachments/2329725/3969669/TRK_BPH_mkFit%26loopers_Adriano.pdf)). This sample was also used to derive the performance of the new setup used for bParking re-miniAOD (see [here](https://github.com/cms-sw/cmssw/issues/33917)).

N.B.
`Filter efficiency (event-level)= (58) / (5000) = 1.160e-02 +- 1.514e-03 `

fyi: @vmariani @mmusich

### CODE REVIEW

**Comment by qliphy** [comment]
please test
ping @cms-sw/generators-l2

**Comment by Saptaparna** [comment]
Any reason why theses parameter sets were chosen:

> parameterSets = cms.vstring('pythia8CommonSettings',
                                     'pythia8CUEP8M1Settings',
                                     'processParameters',
                                     )

**Comment by AdrianoDee** [comment]
@Saptaparna any suggestion? Is it fine to be tested?

**Comment by qliphy** [comment]
> @Saptaparna any suggestion? Is it fine to be tested?

@AdrianoDee 
CUEP8M1 is now outdated and CP5 is the new tune 
Perhaps GEN prefers to update the tune, for which you can refer to e.g.
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/ZpTT_1500_14TeV_TuneCP5_cfi.py

**Comment by AdrianoDee** [comment]
> @AdrianoDee CUEP8M1 is now outdated and CP5 is the new tune Perhaps GEN prefers to update the tune, for which you can refer to e.g. https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/ZpTT_1500_14TeV_TuneCP5_cfi.py

Thanks for the clarification.

**Comment by AdrianoDee** [comment]
please test

**Comment by agrohsje** [comment]
+generators
looks good.

**Comment by qliphy** [comment]
+1

**Pull request merged**
