### PR TITLE
Adding HI MEs to per-LS scope in JetMET offline DQM - backport to 14_1_X

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Adding the following MEs to the per-LS scope:

```
JetMET/HIJetValidation/akCs4PFJets/SumPFPt
JetMET/HIJetValidation/akCs4PFJets/NJets
JetMET/HIJetValidation/akCs4PFJets/NPFpart
JetMET/HIJetValidation/akPu4CaloJets/SumCaloPt
JetMET/HIJetValidation/akPu4CaloJets/NCalopart
JetMET/HIJetValidation/akPu4CaloJets/NJets
```

#### PR validation:

Tested running the `@jetmet` sequence on run 375703 HIMinimumBias0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46548

### CODE REVIEW

**Comment by rseidita** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1

**Comment by antoniovagnerini** [comment]
backport of #46548

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
