### PR TITLE
Run3-sim95 Small fix which works with future Geant4 versions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Small fixes which work with both current and future Geant4 versions

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , I am in process of more radical solution in few minutes.

**Comment by civanch** [comment]
In #35926 most of problems you mention are fixed.

**Comment by bsunanda** [comment]
@cmsbuild Please test with #35766

**Comment by civanch** [comment]
This and more fixes are in #35926 , which is ready to merge.

**Comment by bsunanda** [comment]
@civanch I am closing this PR in favor of #35926

**Pull request closed without merging**
