### PR TITLE
Phase2-hgx217 Convert DDHGCalModuleAlgo.cc to dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert yet another algorithm (DDHGCalModuleAlgo) to DD4Hep format

#### PR validation:

Checked with cfg files in the area Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@smuzaffar Please see why this PR is stuck

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
