### PR TITLE
Updated gridpacks to point to 2.4.2 gridpacks

### PR DESCRIPTION
**Pull request by Saptaparna**
Updated gridpacks to point to 2.4.2 gridpacks.

### CODE REVIEW

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Saptaparna** [comment]
@davidlange6 Are you referring to the conflicts? They are to be expected as I have changed the path to the gridpacks: https://github.com/cms-sw/cmssw/pull/24183/conflicts

Are there any other issues?

**Comment by alberto-sanchez** [comment]
@Saptaparna , these files seems to come from your CMSSW_7_4_X to master (10_3_x), can you move those to your master an then do the PR again?.

**Comment by fabiocos** [comment]
@Saptaparna this PR needs to be rebased on master before it can be used

**Comment by Saptaparna** [comment]
@fabiocos I will take care of this today.

**Comment by fabiocos** [comment]
@Saptaparna ping

**Comment by Saptaparna** [comment]
@fabiocos Apologies, I tried to rebase and that kept failing repeatedly, so I did:
git fetch upstream
git checkout master

and created a new PR from master (I don't know if I can update this PR to start from master). This is the new PR:

https://github.com/cms-sw/cmssw/pull/24268

I apologize for the confusion and will be happy to implement any easier solution that you may have.

**Comment by alberto-sanchez** [comment]
@Saptaparna , You can close this one.

**Pull request closed without merging**
