### PR TITLE
[ROOTMaster] Fix include for RNTuple*

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

* Fix include for RNTupleWriterOptions after root-project/root#14799;
* Fix renaming of RCollectionNTupleWriter class to RNTupleCollectionWriter, add new include (https://github.com/root-project/root/pull/14797);
* Reapply changes from https://github.com/cms-sw/cmssw/pull/44032.

#### PR validation:

Bot tests in https://github.com/cms-sw/cmsdist/pull/9034

### CODE REVIEW

**Comment by makortel** [comment]
FYI @Dr15Jones @dan131riley @nsmith-

**Comment by vlimant** [comment]
enable nano

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
