### PR TITLE
No hack conditions

### PR DESCRIPTION
**Pull request by kkotov**
A simple patch to get L1T conditions from CondDB as opposed to the static pythons.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
As one could expect, the tests are failing. Changing L1TCaloStage2ParamsRcd -> L1TCaloParamsRcd in the calo emulator presumably fixes the problem. Good thing: now we know for sure that the taken out static producers are indeed nowhere to be found in the chain.

**Comment by kkotov** [comment]
The last commit should fix the problem, but I couldn't check it explicitly in my working directory. At the last stage of compilation I've got complains for the build tool, indicating some problem with the release:

****WARNING: Invalid tool FWCore/Framework. Please fix src/L1Trigger/L1TCalorimeter/plugins/BuildFile.xml file.
****WARNING: Invalid tool tmp/slc6_amd64_gcc530/cache/bf/src/L1Trigger/L1TCalorimeter/plugins/BuildFile_USE_ERR+=FWCore/Utilities. Please fix src/L1Trigger/L1TCalorimeter/plugins/BuildFile.xml file.
****WARNING: Invalid tool FWCore/Framework. Please fix src/L1Trigger/L1TCalorimeter/src/BuildFile.xml file.

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic , hmm, yet another package using L1TCaloStage2ParamsRcd. I fixed that one as well. Let's hope this is the last one...

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic , to my best understanding we now declaring a victory on this PR as it failed exactly where we expected it to fail due to the missing MC conditions. Btw, could you trigger the tests again on PRs: #18493, #18517 ?

**Comment by davidlange6** [comment]
its not a victory that will get the PR merged, however...

**Comment by kkotov** [comment]
@davidlange6 , we wanted first to make sure DQM can run with these modifications. They rely only on online Global Tag that how has all of the trigger conditions. After we confirm that DQM can run, I'll push MC conditions, request a Global Tag from AlCa, and reiterate this PR once again.
P.S. since it is taking time for Vladimir to catch up with this thread, could you start the tests for my PRs:
#18493, #18517, #18665, #18668 ? Thanks.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
closing to avoid wasting more resources on tests. we can reopen when its expected to work..

**Comment by rekovic** [comment]
@kkotov 
Please make a new PR to 93x.  We should now have all conditions in MC GlobalTags.

**Comment by kkotov** [comment]
@rekovic , done: #19456

**Pull request closed without merging**
