### PR TITLE
Phase2-hgx311 First attempt to make the EE compartment of V17 geometry version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

First attempt to make the EE compartment of V17 geometry version

#### PR validation:

Tested by dumping the geometry and using fireworks.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob Could you review this quickly. We would like to have a few more PR's which could be submitted once this PR is merged.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob Please sign this PR. These changes are needed to be in the master so that we can proceed for the next step.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

First adding EE compartment of V17 as mentioned in the PR description. No change is expected from test workflow as this new geometry has not been used yet.

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
I also approve this PR.

**Comment by bsunanda** [comment]
@perrotta @qliphy Please merge this PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
