### PR TITLE
bsunanda:Phase2-hgx42 Making an application for TB simulation of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @civanch Please review the changes and approve

**Comment by boudoul** [comment]
hi @bsunanda , out of curiosity, what TB stands for ?

**Comment by bsunanda** [comment]
Test Beam
________________________________

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
