### PR TITLE
[12.4.X] implement event consumes in `MuScleFit`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39029

#### PR description:

Title says it all.

#### PR validation:

Run with this branch the configuration posted at https://github.com/cms-sw/cmssw/issues/38958#issuecomment-1203927278 (for convenience also available [here](https://gist.github.com/mmusich/80fa5cb6e192c9f424f715b598b22604)) successfully.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/39029 to CMSSW_12_4_X, needed for tracker alignment purposes

### CODE REVIEW

**Comment by mmusich** [comment]
urgent
    * needed for data-taking validation purposes

**Comment by mmusich** [comment]
assign alca

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
