### PR TITLE
Run4-hgx262 Correct name of Digi collection

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct name of Digi collection

#### PR validation:

Test using runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
@bsunanda with the change of digi collection, plots now are empty for HGCAL / HGCalDigisV , is this expected?
https://tinyurl.com/y36s3arr
https://tinyurl.com/y6rorlhe

**Comment by bsunanda** [comment]
@jfernan2 No - that must be a mistake. I reverted the old ones. I tested the ones which are run on o/p of step2 without rawtodigi

**Comment by jfernan2** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
