### PR TITLE
Improved unit tests in FWCore/Framework

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- moved tests to catch framework
- removed useless test
- consolidated tests into one executable
- moved test code out of .cc file

#### PR validation:

Code compiles and tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
The usual
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
