### PR TITLE
Rel val74 x back port to71 x step2

### PR DESCRIPTION
**Pull request by inugent**
Pull request to back-port the relval from 7_4/5_X to 7_1_X requested by Giovanni.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
hello @inugent 
thanks for this. Since the tests performed by the IB nearly all recycle existing GEN-SIM, we'll need some time to run independent tests.
Working on it.

**Comment by franzoni** [comment]
Hello @inugent

good to go - the tests of this PR have not added failures with respect to those pre-existing in CMSSW_7_1_X_2015-03-22-2300 . 

If at all possible, it would be good adding back :
Hydjet_Quenched_B3_2760GeV_cfi
@mandrenguyen can remind us if/how the workflow 143 can/needs be put back.

If Hydjet takes iterations, we might as well add later - no need to defer this PR much a tall.

**Comment by franzoni** [comment]
+1

**Comment by mandrenguyen** [comment]
Hi @franzoni 
We'd like to be able run Hydjet for central events (B3 is 'mid-central'), but currently the RSS limits don't permit this.  I suggest we discuss this with you and the other pdmv conveners at some point over the next few weeks, but let's not interfere with this PR.

**Comment by franzoni** [comment]
@mandrenguyen - fair enough.

 @inugent : no action for you on this matter. As far as PdmV is concerned, this PR is good to go.

**Comment by bendavid** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
