### PR TITLE
Fix MonitorElement exception in L1TTau offline DQM. - 92x v2

### PR DESCRIPTION
**Pull request by thomreis**
This reverts the revert in #20168 to get back the L1T tau offline DQM introduced with #20043 and then adds the patch of #20157 to avoid it crashing.

This was tested with the configuration that was run at the T0 playback when the problem was first discovered. The exception does not show anymore now.

### CODE REVIEW

**Comment by thomreis** [comment]
@davidlange6 does this need to be declared a backport of something? The 93x version of the fix is in #20156 but here is also the revert of #20168 .

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport of  #20043 and #20157

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@dmitrijus please sign.
This is a backport of already merged PRs in 93x.

**Comment by thomreis** [comment]
backport of #20157

**Comment by thomreis** [comment]
backport of #20156

**Comment by thomreis** [comment]
Before, I pointed to the wrong PR for the backport. PR #20156 is already merged and I think it should say backport-ok.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
