### PR TITLE
Update GPU workflows [13.2.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Clean up the definition of the GPU workflows.
Drop 2022 MC GPU workflows.
Move Patatrack data workflows to 2023.
Add workflows for GPU validation and profiling on data.

#### PR validation:

New matrix workflows pass (tested in 13.3.x):
```
runTheMatrix.py -w gpu -l 141.008507,141.008508,141.008513,141.008514,141.008523,141.008524
...
141.008507_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU_Validation Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Sep  5 07:39:36 2023-date Tue Sep  5 07:29:23 2023; exit: 0 0 0 0
141.008508_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU_Profiling Step0-PASSED Step1-PASSED Step2-PASSED  - time date Tue Sep  5 07:37:50 2023-date Tue Sep  5 07:29:24 2023; exit: 0 0 0
141.008513_Run3-2023_JetMET2023B_RecoECALOnlyGPU_Validation Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Sep  5 07:39:40 2023-date Tue Sep  5 07:29:24 2023; exit: 0 0 0 0
141.008514_Run3-2023_JetMET2023B_RecoECALOnlyGPU_Profiling Step0-PASSED Step1-PASSED Step2-PASSED  - time date Tue Sep  5 07:37:48 2023-date Tue Sep  5 07:29:25 2023; exit: 0 0 0
141.008523_Run3-2023_JetMET2023B_RecoHCALOnlyGPU_Validation Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Sep  5 07:48:39 2023-date Tue Sep  5 07:37:48 2023; exit: 0 0 0 0
141.008524_Run3-2023_JetMET2023B_RecoHCALOnlyGPU_Profiling Step0-PASSED Step1-PASSED Step2-PASSED  - time date Tue Sep  5 07:41:42 2023-date Tue Sep  5 07:37:50 2023; exit: 0 0 0
6 6 6 3 tests passed, 0 0 0 0 failed
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #42713, in case it is requested.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #42713

**Comment by fwyzard** [comment]
(wait for the 13.3.x tests to pass before testing in 13.2.x)

**Comment by fwyzard** [comment]
test parameters:
  - enable_tests = gpu
  - workflows_gpu = 141.008507,141.008508,141.008513,141.008514,141.008523,141.008524
  - pull_requests = #42631

**Comment by fwyzard** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
I am still not quite sure what mechanism provokes it, but reverting this PR locally on top of `CMSSW_13_2_4` solves https://github.com/cms-sw/cmssw/issues/42831

**Pull request merged**
