### PR TITLE
remove unused variable to avoid gcc493 build errors

### PR DESCRIPTION
**Pull request by smuzaffar**
this should fix the build error of gcc493 IBs 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_1_X_2016-08-22-1100/DQM/TrackingMonitor

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
@smuzaffar - do you understand why its not seen in gcc53?

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@davidlange6 , Although for both gcc493 and gcc530 archs gcc toolfile sets
```
-Werror=unused-variable
```
but for gcc530 , boost and clhep toolfiles add https://github.com/cms-sw/cmsdist/commit/d71935269531b0034e6381bb7100420eb972c590
```
<flags CXXFLAGS="-Wno-error=unused-variable"/>
```

**Pull request merged**
