### PR TITLE
Explictly include root's TObjString header to fix the unit test for ROOT6 Ibs

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

This is needed due to headers cleanup in ROOT6 master branch ( see https://github.com/cms-sw/cmssw/pull/29740 ). The unit test fails for root6 master based IBs [a]

[a]
```
Info in <TUnixSystem::ACLiC>: creating shared library CMSSW_11_1_ROOT6_X_2020-05-15-2300/tmp/PixelBaryCentreTool/PixelBaryCentrePlottingTools/./PlotMillePede
_C.so
In file included from input_line_12:6:
././PlotMillePede.C:410:76: error: unknown type name 'TObjString'
  if (whichOne.Contains("result", TString::kIgnoreCase)) whichOnes.Add(new TObjString("result"));
                                                                           ^
././PlotMillePede.C:411:76: error: unknown type name 'TObjString'
  if (whichOne.Contains("start",  TString::kIgnoreCase)) whichOnes.Add(new TObjString("start"));
                                                                           ^
././PlotMillePede.C:412:76: error: unknown type name 'TObjString'
  if (whichOne.Contains("diff",   TString::kIgnoreCase)) whichOnes.Add(new TObjString("diff"));
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
