### PR TITLE
[10.1.X] Add Payload Inspector plugins for Tracker Alignment 

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
this PR aims to add several plots to the Payload Inspector for the three types of `CondFormat` objects in which Tracker Alignment conditions are stored:  
   * `TrackerAlignment` : 
     * Difference between two alignment payloads (IOVs) for translations and rotations, plotted by `DetId` index;
     * Difference between two alignment payloads (IOVs) for translations and rotations, aggregated by sub-detector;
     * Trend plot of the position of the translational coordinates for the Pixel Barrel barycenter;

   * `TrackerAlignmentErrorsExtended`:
     * Summary of the APE values by element of the error matrix in each sub-detector, for a single IOV;
     * TrackerMap of the APE values by element of the error matrix, for a single IOV;
     * Detailed average values of the APE by element of the error matrix by Tracker sub-sector (same granularity as used for the derivation), for a single IOV;
      * Detailed comparison between two palyoads (IOVs) of the average APE element of the error matrix, by Tracker sub-sector (same granularity as used for the payload derivation).

   * `TrackerSurfaceDeformations`:
     * Summary of the values for each of (up-to 13) parameters describing the surface deformation broken down by sub-detector;
     * Comparison between two IOVs  of the values for each of (up-to 13) parameters describing the surface deformation broken down by sub-detector;
     * Tracker Map of the Surface deformation parameters, for a single IOV;
     * Tracker Map of the differences between two IOV of the Surface deformation parameters;
     * Detailed average values of the Surface Deformation for each parameter, by Tracker sub-sector (same granularity as used for the APE).

A dedicated unit test is added, as well as few testing scripts.
@ghellwig @hroskes you might want to follow.

[edited] this tool has been presented at [TlAl Meeting 20.02.2018](https://indico.cern.ch/event/688838/contributions/2903081/attachments/1603462/2542900/mm_TkAl20.02.2018_PayloadInspector.pdf)
___

Few examples of added plots (plots have been edited after receiving comments):

   * ## for the alignment object:

trackeralignmentcomparez

   * ## for the APE object: 

trackeralignmenterrorextended_xx_comparison

   * ## for the surface deformations:

surfacedeformationtrackermapparameter_6

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by ghellwig** [comment]
@mmusich very nice tool!
May I suggest that you add the test script also to the unit test, i.e. just adding one `test` tag for each script?
Another item: Would you like to present this in one of the next TkAl meetings?

**Comment by ghellwig** [comment]
I have some suggestions concerning the plots, though.
The z-translation plot nicely shows the boundaries between the different subdetectors, but it would be nice if you could add labels with the subdetector names to guide users of the plot that do not know the ordering by heart.
Btw., without looking to deep into the code: What happens for APEs that are set per module? Normally we do not set them with module-level granularity, i.e. your summary plot is well suited, but I wanted to understand the behaviour if we make use of the maximum granularity.

**Comment by ghellwig** [comment]
Regarding the surface deformation maps: Is there a general plan to resurrect the pixel part for phase-1?

**Comment by mmusich** [comment]
> Regarding the surface deformation maps: Is there a general plan to resurrect the pixel part for phase-1?

not that I am aware of. 
I considered using the `TH2Poly` code that the TkDQM group devised some time ago (https://twiki.cern.ch/twiki/bin/viewauth/CMS/Phase1TkMap), but it has two fundamental drawbacks.
   * it doesn't integrate the strip partitions
   * it would have pulled in a substantial amount of codebase which is not integrated in CMSSW (AFAIK), and it would have had little to do with the purpose of the current PR, creating dependencies with DQM code.

I am adding @fioriNTU, if he wants to add something about eventual plans for 2018.

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
