### PR TITLE
Re-adding cosmic track collection ALCARECOTkAlCosmicsCosmicTF0T

### PR DESCRIPTION
**Pull request by consuegs**
#### PR description:

This PR has a single commit:
  - re-adding ALCARECOTkAlCosmicsCosmicTF0T track collection from [PR#35694](https://github.com/cms-sw/cmssw/pull/35694)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by tvami** [comment]
+alca

**Comment by mmusich** [comment]
@consuegs I guess this should be backported to at least 13.0.x for ease of analyzing the 2023 data. Will you take care of that?

**Comment by consuegs** [comment]
> @consuegs I guess this should be backported to at least 13.0.x for ease of analyzing the 2023 data. Will you take care of that?

@mmusich, I see is already taken care, thanks

**Pull request merged**
