### PR TITLE
Improve exception message from a ROOT read

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

No matter the exception type, make sure the branch name is known.

#### PR validation:

Code compiles and framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@smuzaffar Would it make sense to produce comparisons even if RelVals-INPUT fail if the usual matrix workflows succeed? (I went through DQM bin-by-bin this time)

**Comment by smuzaffar** [comment]
@makortel , Relval-INPUT tests mostly fails due to network or eos issues ( which we either mostly ignore or just re-run the input tests). So I think it is fine to run comparisons even if Relval-INPUT tests failed.

**Comment by makortel** [comment]
Yeah, nevermind, I see the comparisons were actually there and I yesterday I was looking from a wrong place in the test summary page. Sorry for the noise.

**Comment by Dr15Jones** [comment]
ping @cms-sw/orp-l2

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
