### PR TITLE
Avoid compilation errors in L1Trigger/Phase2L1GMT/src/KMTFCore.cc

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

 L1Trigger/Phase2L1GMT/src/KMTFCore.cc has compilation warnings in gcc12 and errors in gcc13.  These appear to be another example of LTO exposing compiler errors.  This PR works around the warnings/errors mostly by declaring some SMatrix variables as const.

#### PR validation:

Compiles, should be a simple technical fix.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc13

**Comment by smuzaffar** [comment]
thanks @dan131riley , this has fixed the el9/gcc13 compilation issues https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fcf9d7/40763/build-logs/

**Comment by smuzaffar** [comment]
@cms-sw/l1-l2  can you please review this? This should fix the build errors for el9/gcc13 IBs

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
