### PR TITLE
New pat zpeak py3

### PR DESCRIPTION
**Pull request by jmejiagu**
#### Move patZpeak.py code to python3

It was necessary because of the FWLite.Python section of the CMSWorbook (3.5.4) has been updated.
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookFWLitePython

It has been tested in this repository:
https://github.com/jmejiagu/MyFWLite_12
where you can see instructions for running the "new" patZpeak code.

### CODE REVIEW

**Comment by jpata** [comment]
please rebase fc8230b on top of master. unrelated commits are included in this PR.

**Comment by Martin-Grunewald** [comment]
-1
rebase needed

**Comment by perrotta** [comment]
Please @jmejiagu : either rebase, or close this one and open another PR in the master branch which only inlcudes your wanted commit

**Comment by tvami** [comment]
-1
 * unrelated to AlCaDB

**Comment by jpata** [comment]
-reconstruction
- DataFormats/FWLite, where the changes are proposed, is not under reco, so once rebased, this PR would anyway disappear from the reco view.

**Pull request closed without merging**
