### PR TITLE
Run3-TB43 Create interface/src for SimG4CMS/HGCalTestBeam to help TB analysis

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

HGCal test beam analysis is done in a separate Sw by linking some of the libraries from CMSSW. They need to have AHCalDetId and AHCalGeometry and they cannot link with the plugins. So these two are moved back to interface/src. Also some of the magic numbers used for AHCal are removed.

#### PR validation:

It is verified by private tests with the cfg 's in the test area

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
