### PR TITLE
Fix CaloTower outer energy for HE 2018

### PR DESCRIPTION
**Pull request by kpedro88**
For the full HE upgrade in 2018, we will not combine RecHits to resemble the old (phase 0) depth segmentation scheme.

However, egamma would like to retain (as much as possible) the definitions of "outer energy" and "inner energy" for CaloTowers in HE. This PR implements that, using the existing `HcalPhase` parameter (held over from 62XSLHC, so far unused in modern releases).

I also added a case for tower 17, which now has 2 depths and can be treated similarly to the other towers.

These diagrams show phase 0, phase 1, and "HEP17" = phase 1 combined to be as close to phase 0 as possible (though NB above caveat about tower 17 in this PR):

phase 0 depths phase 1 depths phase 1 depths

attn: @abdoulline @igv4321 @bsunanda @Sam-Harper

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by Sam-Harper** [comment]
thanks Kevin! I discussed with Salavat. Theres not much we can do testing with this now but we'll test when either we get relvals or the TSG 94X 2018 samples arrive. Thanks again.

**Comment by deguio** [comment]
thanks kevin.
do I understand correctly that the other cases listed at:
https://docs.google.com/document/d/11BzN5hnF3bw3DFEhOmYisC4fXhN7xaJdSWZzKGgs8fk/edit
should be fixed in a similar way?

for example:
https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/EgammaIsolationAlgos/src/EgammaHcalIsolation.cc#L90-L91

**Comment by Sam-Harper** [comment]
I dont think that code is actually used. It exists but isnt actually run as far as I'm aware for standard pp reco

**Comment by deguio** [comment]
ok, thanks. you have mentioned that already, but I forgot.  :)

**Comment by kpedro88** [comment]
(if it were used, it should be fixed similarly; but if it's not, easier to leave it alone)

**Comment by perrotta** [comment]
Electron and photon id quantitities are touched for 2018 and 2019 workflows: differences look like being compatible for moving from phase0 to phase1

For example, in TTbar13TeVPU2017 wf 10224:

image

image

image

**Comment by slava77** [comment]
On 12/18/17 12:43 AM, perrotta wrote:
> Electron and photon id quantitities are touched for 2018 and 2019
> workflows: differences look like being compatible for moving from phase0
> to phase1
> 
> For example, in TTbar13TeVPU2017 wf 10224:
> 

there is some inconsistency in this message: the PR and the first
sentence say 2018, but the example plots are from 2017.
I'm probably missing something.

**Comment by perrotta** [comment]
Thank you for noticing it Slava 
I copy/pasted The name from the wrong line: in the plots there are 200 events from the 2018 wf 10824.0, TTbar13TeV
I will edit and fix the text above as soon as I have something easier to use than a cell phone

**Comment by perrotta** [comment]
+1
- It does what in the description: for theHcalPhase=1 the energy content of the new depth segmentations in the HE towers are summed up to give an outer energy as close as possible to the one in Phase0

**Comment by davidlange6** [comment]
+1

**Pull request merged**
