### PR TITLE
Phase2-hgx351 Modify to analyze flat files contatining only full silisonlayers of EE and HE (usefule for HFNose)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify to analyze flat files contatining only full silisonlayers of EE and HE (usefule for HFNose)

#### PR validation:

Use it to analyse hfnose01.txt

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
