### PR TITLE
moreobservables_and_bugFix

### PR DESCRIPTION
**Pull request by ramankhurana**
This PR has multiple (minor) changes or fixes in the JME DQM s/w. The slides were presented in JME-DPG few weeks ago. it will be good for 2018 data taking. https://indico.cern.ch/event/697045/contributions/2863770/attachments/1586988/2509637/JME-DQM-ReReco2018.pdf

The previous PR #22167 always failed at the runTheMatrix checks. This PR is checked and tested. I will delete that PR.

### CODE REVIEW

**Comment by perrotta** [comment]
-1
(need a rebase)

**Comment by slava77** [comment]
-1

this PR is either made to a wrong release branch or is in bad need of a rebase

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by boudoul** [comment]
hi @ramankhurana , In addition to the rebase, may I kindly ask you could to provide a more specific title ? ("For2018 data taking" is not very explicit .....) , thanks .

**Comment by kpedro88** [comment]
-1
wrong branch or something

**Comment by arunhep** [comment]
-1
(needs a rebase and proper title)

**Comment by ramankhurana** [comment]
it seems to be broken due to some reason and unable to fix it in short time with given expertise I have. So I create another branch.

**Pull request closed without merging**
