### PR TITLE
Add weights config for 2018 Run Dependent MC

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR introduces weights used for 2018 Run Dependent MC.

#### PR validation:
No. The test should be done when agreeing on how to pass information to WMAgents

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport should be done to 11_1, for a pilot of the production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
