### PR TITLE
[100X] GEMDigiForRun2

### PR DESCRIPTION
**Pull request by jshlee**
backport #22619

this will run for run2 workflows using #22592 autoCond updates

@kpedro88 @arunhep @perrotta @hyunyong

### CODE REVIEW

**Comment by kpedro88** [comment]
please test with #22592

**Comment by slava77** [comment]
On 3/16/18 9:37 AM, Jason Lee wrote:
> backport #22619 <https://github.com/cms-sw/cmssw/pull/22619>
> 
> this will run for run2 workflows using #22592
> <https://github.com/cms-sw/cmssw/pull/22592> autoCond updates
> 

I think that this will need a full validation in the master first and
this feature missed the last open pre-release in 10_1_X.
So, it's unlikely to converge for the practical needs of 10_0_X.

If this PR is needed in the same old context of producing only digis
only for DQM and not running anything else downstream, then perhaps it's
fine for 10_0_X.
But then in this case it probably doesn't really introduce anything new.

**Comment by perrotta** [comment]
The error is in the 2018 workflow, and it seems to be related:
```
#5  0x00007fc766d74f04 in GEMTrackMatch::setGeometry(GEMGeometry const&) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-03-11-0000/lib/slc6_amd64_gcc630/libValidationMuonGEMHits.so
#6  0x00007fc766cde27a in GEMRecHitTrackMatch::bookHistograms(DQMStore::IBooker&, edm::Run const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-03-11-0000/lib/slc6_amd64_gcc630/libValidationMuonGEMRecHits.so
#7  0x00007fc7a1b7ec6d in DQMEDAnalyzer::beginRun(edm::Run const&, edm::EventSetup const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_0_X_2018-03-16-1100/lib/slc6_amd64_gcc630/libDQMServicesCore.so
```

**Comment by jshlee** [comment]
@perrotta yes, this was due to the new gem geometry in the new GTs.
I've updated the gem geometry maker with the version that is currently in master

**Comment by perrotta** [comment]
please test with #22592

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@jshlee 
please clarify operational plans and needs for having this in 10_0_X.
We expect to have a 10_1_X release deployed online at T0 in about a week.
Is this code required before that? (my guess is no, but please clarify).
Thank you.

**Comment by jshlee** [comment]
@slava77 we would like gem local reco for T0. 
If 10_1_X is going to be deployed in a week, then this backport is not needed.

**Comment by slava77** [comment]
-1

@jshlee 
10_1_0 was released earlier today.
The plans are to deploy early next week.

If you still want to keep this PR open, just in case, it has to be updated to be in sync with changes made in #22619

**Comment by jshlee** [comment]
no this can be closed

**Pull request closed without merging**
