### PR TITLE
update 2018 design GT with pixel 2D temalates

### PR DESCRIPTION
**Pull request by arunhep**
It should address the this github issue : https://github.com/cms-sw/cmssw/issues/23666

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_design_v5/102X_upgrade2018_design_v3

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by mmusich** [comment]
@tvami @arunhep, 
just for my understanding, looks like the denominator and numerator tags are different in the change proposed here. IIUC this means the charge reweighting will be applied and a deteriorarion of performance will follow. Is this the desired outcome for a design GT, which I thought should  implement a non irradiated scenario? 
Was this discussed elsewhere? What does Tk POG thinks about it?

**Comment by arunhep** [comment]
@mmusich good point ! Thanks.
@tvami can you confirm please? I will then use same tag for numerator and denominator which should switchoff this correction.

**Comment by tvami** [comment]
Thanks Marco for pointing to this. Indeed in this case the same tags should
be used for num and denom, too.

Arun Kumar <notifications@github.com> ezt írta (időpont: 2018. jún. 24.,
Vas 13:02):

**Comment by arunhep** [comment]
please test workflow 11224.0,11224.6

**Comment by fabiocos** [comment]
@arunhep the test looks successful. If the applied record is what really intended in the design scenario, as I understand it is in its latest version, could you please sign. so as I we can remove this issue?

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
