### PR TITLE
VID fix & core unit tests + Regression ValueMap Producer code cleanup. (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11229.

@ikrav please base your user recipes off of this PR.

@gpetruc @arizzi @davidlange6 Since this now contains a bugfix for the regression it is necessary.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
How essential is this one in 74X perspective?
We will start taking data at 3.8 T imminently and making substantive changes mid-way may make things more complicated for analyzers.

From what I noticed already, this PR modifies the miniAOD egamma object momenta.
What else is here that changes the miniAOD content?

@davidlange6 @gpetruc

**Comment by lgray** [comment]
The only super essential change is baef928. The rest of the changes are code clean up and analysis level issues.

There is one additional necessary variable calculation bugfix from @ikrav that is important and could be integrated easily.

**Comment by lgray** [comment]
There are no other modifications to the MiniAOD content in this PR (as it is at present).

**Comment by slava77** [comment]
so, I will try to sign off this one today.
@davidlange6 if we can put this in 74X, some prompt delay would be needed, otherwise it goes to some later "natural" time.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11232	baef928

- same code changes as in the 76X PR #11229 (except for the change in the input files used in the /test configurations)
    - mostly refactoring and addition of unit tests. there is also a bugfix in the regresion input variable computations
- plot from wflow 4.53 in jenkins shows the expected small change in the miniAOD electron kinematics
wf4 53_pt_slimmedele

**Comment by lgray** [comment]
@davidlange6 @gpetruc Just to make sure, this PR, #11282, and #11262 will make it in for the MiniAOD reprocessing?

**Comment by gpetruc** [comment]
Hi,
I hope they can go in a patch release as soon as possible, for prompt reco
too.

Giovanni

**Comment by davidlange6** [comment]
how confident are we that there are not other small fixes needed?

**Comment by lgray** [comment]
At this point I am pretty confident. The evaluation code now matches what
was used in the training.

**Comment by davidlange6** [comment]
I mean in the miniAOD - we don’t want too many breakpoints.

**Comment by lgray** [comment]
Translation: the miniaod regressions and mva IDs are now fixed, considering
all three relevant PRs.

(Sent from my Nexus 6)

**Comment by gpetruc** [comment]
If we put this in before the prompt of the first collision run of 2015D we
have no breakpoints (beyond the already existing one between 2015C and
2015D), and no need of reprocessing the beginning of 2015D unless other
bugs are found.

There's a possible change in the type1 MET definition (a change in the jet
pt threshold), but that's useful only on MC or re-reco/re-miniaod of old
data, since for prompt reco data the type1 correction will have to be
recomputed anyway when new JEC residuals for 2015D will become available.

Ciao,

Giovanni

**Comment by davidlange6** [comment]
+1

**Pull request merged**
