### PR TITLE
Add cpuset size information to the FJR.

### PR DESCRIPTION
**Pull request by bbockelm**
We have found that it's difficult to detect when the cpuset (set by
some batch systems) is limiting the number of cores we can run on.

In one extreme case, the batch system arguments were being done
incorrectly and 32 cores worth of CMS jobs were being forced onto a
single core.

This records the current cpuset size to the FJR when CPU information
reporting is enabled.  The resulting line looks like:

```
<Metric Name="cpusetCount" Value="1"/>
```

With this, we hope that experts are more likely to notice that the
cpuset is different from expectations

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@smuzaffar Why didn't the bot see this pull request ?

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
