### PR TITLE
Run3-gex95 Introduce the corrected material files for modified tracker geometry of Run3

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Introduce the corrected material files for modified tracker geometry of Run3

#### PR validation:

Checked using cfg's in the test area's of Geometry files

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@civanch Should this be back ported to 12_0? Also, I don't understand why a Run3 menu needs signature from Upgrade convener

**Comment by bsunanda** [comment]
@AdrianoDee @srimanob Please approve this PR

**Comment by AdrianoDee** [comment]
+1

**Comment by srimanob** [comment]
I don't think we need a backport to 12_0. I assume the change will not affect on 2021 geometry because I don't see 2021 geometry updated in this PR. Production test in 12_0 should not need this clean up, or later clean up. We can validate it directly in 12_1_0_pre4, pre5.

**Comment by bsunanda** [comment]
I agree with this. But one should remember that 12_0 and 12_1 description of 2021 geometries are identical only for full Run3 and Run3 with zero tracker material.

**Comment by perrotta** [comment]
+1
- There is no plan to backport this in the 12_0_2 that will be built in a few hours from now
- If needed/requested a backport in a forthcoming 12_0_N, with N>2, can be taken into account

**Comment by srimanob** [comment]
Thanks @bsunanda 
I think it is fine. We currently freeze autocond GT which have geometry == XML in 12_0_0. Advance from that is a plus on testing for DDD and DD4hep only. not for the production goal of the release.

**Pull request merged**
