### PR TITLE
SUSY HLT DQM path and filter name fixes for various paths, 80X

### PR DESCRIPTION
**Pull request by olivito**
This is a fix in the SUSY HLT DQM python config for various path and filter names which have changed in the HLT menu but weren't updated here.

80x version of this PR: #14751

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
