### PR TITLE
argparse migration for PhysicsTools and FWLite

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Followup to #43042. Probably the last one of these I'll have time to do.

#### PR validation:

Ran each script to ensure it still works. Unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Unlikely to be backported.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by tvami** [comment]
+analysis

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
