### PR TITLE
Online DQM changes for MWGR#2

### PR DESCRIPTION
**Pull request by dmitrijus**
Changes affect only the online DQM. Tested and run at MWGR#2 and  MWGR#3.

1. GT and GT related changes.
2. A few bug fixes in several online DQM clients. Bug were mostly typos, previously undetected.
3. Remove unused "playback" script.
4. Implement "repacker" output module, to create input streamer data from GEN-SIM. Used for test purposes only.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
merge conflicts and too many commits (rebase...)

**Comment by ianna** [comment]
-1

please rebase

**Comment by slava77** [comment]
-1

rebase needed if this isn't just on a wrong branch

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
