### PR TITLE
esConsumes migration, 4 more modules

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Migrates MonitorTrackResiduals, SiPixelPhase1Clusters,
SiPixelStatusHarvestor, and SiPixelStatusProducer.

Deletes SiPixelQuality::IsAreaBad which was not used
anywhere in the repository and was causing problems with
the way it used the EventSetup. I could restore this function
if it is actually needed.

Note GeometryInterface gets SiPixelFedCablingMap in somewhat
inconsistent ways, one way allows a label but the other doesn't.
I preserved the current behavior (probably harmless), but
I could modify this if someone understands what it should be
doing here.

#### PR validation:

Relies on existing tests. Results should be unchanged. There is no new functionality.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
please test

**Comment by jfernan2** [comment]
+dqm

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28710	dbced6d 
- reco category change in EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc is essentially trivial
- jenkins tests pass

**Comment by tocheng** [comment]
@cmsbuild please test workflow 1001.2, 1040

**Comment by tocheng** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
