### PR TITLE
[BTV, NanoAOD] Add UParT discriminants for strange-jet tagging

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR defines the UParT discriminants for strange jet tagging (`SvsUDG `, `SvsCB`) and store them in NanoAOD (and JMENano) for AK4 jets.  The sum of u, d and g raw scores  (`UDG`) is also stored, which can be used to re-calculate the raw scores. These new branches are for the NanoAODv15 campaign.

The UParT strange jet tagging performance is documented in a recently released DP-note ([CMS-DP-2024-066](https://cds.cern.ch/record/2904702) Figure 4)

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- ran workflow `141.044_RunJetMET2023D`  and had checked that the new discriminants and scores are in MiniAOD and NanoAOD

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
[nurfikri89](https://github.com/nurfikri89) is there some documentation of the performance you can add to the PR description?

**Comment by mandrenguyen** [comment]
enable nano
sorry, should have done it the first time

**Comment by mandrenguyen** [comment]
There are some differences in the comparisons that are not obviously expected for me.
Why are SVs now empty, e.g.?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-09-1100+42bce6/63954/validateJR/25202.0_TTbar_13/all_NANO_step5/c_nanoaodFlatTable_jetPuppiTable__NANO_obj_floats__nSVs_304.png

**Comment by nurfikri89** [comment]
> [nurfikri89](https://github.com/nurfikri89) is there some documentation of the performance you can add to the PR description?

@mandrenguyen I have added a link to the DP-note which documents the performance of UParT.

> There are some differences in the comparisons that are not obviously expected for me. Why are SVs now empty, e.g.? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-09-1100+42bce6/63954/validateJR/25202.0_TTbar_13/all_NANO_step5/c_nanoaodFlatTable_jetPuppiTable__NANO_obj_floats__nSVs_304.png

Hmm it is not clear to me also. I will try to take a look at them with a local test on lxplus.

**Comment by vlimant** [comment]
please test
(with nano now)

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
hold 
I think we're still waiting for an answer to this:
https://github.com/cms-sw/cmssw/pull/45684#issuecomment-2282190336

**Comment by hqucms** [comment]
> hold I think we're still waiting for an answer to this: [#45684 (comment)](https://github.com/cms-sw/cmssw/pull/45684#issuecomment-2282190336)

@mandrenguyen I think it's not a real difference, just that the order of variables in the nano flat table changed because of the new variables?

**Comment by mandrenguyen** [comment]
unhold

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
