### PR TITLE
[14_0_X] Fix LHCInfoPer* PopCons to produce lumi-type IOVs when running in duringFill mode

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #43837.

Update the `LHCInfoPerLS` and `LHCInfoPeFill` PopCons so that, when running in `duringFill` mode (used to populate the HLT GT), they produce `lumiid`-type IOVs.

#### PR validation:
See master PR. 
Also, the LHCInfoPer* O2Os will be validated by the AlCa-DB group before deploying them in production.

#### Backport:
Backport of #43837

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #43837

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+db

 - since the master PR has been signed by the AlCaDB conveners and it has been (successfully) merged in master since yesterday (last night's IB shows no errors related to this PR), I take the liberty to self-sign this backport

**Comment by francescobrivio** [comment]
urgent

 - following the new guidelines defined in https://github.com/cms-sw/cmssw/issues/44283 I mark this urgent and tag @cms-sw/orp-l2 
 - all details have been included in a mail forwarded to ORM and Release Managers

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
