### PR TITLE
B2G HLT monitoring 92x

### PR DESCRIPTION
**Pull request by UBParker**

### CODE REVIEW

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by mtosi** [comment]
uhmm
how is this in synch w/ PR https://github.com/cms-sw/cmssw/pull/18978 ?
could you please be in contact w/ @sudhaahuja
for instance, couldn't we merge the 2 developments in a single PR ?
I think it would help the integration process ...

why are you adding HT monitoring in the METMonitor ?
couldn't you use 2 modules in the same sequence ?

the HT definition should not depend on the jetSelection done at even level !

**Comment by UBParker** [comment]
Hello Mia, Sal, Sudha, All,

Apologies, I have never done this before so please bear with me but I
merged the topic #18978 <https://github.com/cms-sw/cmssw/pull/18978>
then added the 2 files in a commit here [1], I see now that I probably
should have waited for the PR to be complete. We could easily add these
into a single PR, I cc. Sudha so that we can coordinate the effort.

I will look into fixing the issues you describe, could you clarify on some
of them?

I am not sure what you mean by adding HTmonitoring in the MET monitor as
the HT monitoring is used for all triggers except AK8jetmass360_trimmass30
[2].

I don't know what you mean by using 2 modules in the same sequence, which 2
modules?

I have removed the jetSelection cuts, that was a rookie mistake. Here is
the latest version of that file [3].

Best,
Ashley


[1]
https://github.com/UBParker/cmssw/commit/5391c413fbefbc27ebbf2df9af1dfecab4bbeba4

[2]
https://github.com/cms-sw/cmssw/pull/19214/commits/5391c413fbefbc27ebbf2df9af1dfecab4bbeba4#diff-f2b7d1c5f082de54fef4306967601fd8R14

[3]
https://github.com/UBParker/cmssw/blob/B2GTrigger_92X/DQMOffline/Trigger/python/B2GMonitoring_cff.py

**Comment by mtosi** [comment]
ciao

I have to go and pick my kid at the creche, now
if you are still at CERN, what about meeting tomorrow morning around 11
@bld40 ?
(my office is 40-1-b01)

have a nice day
  mia

**Comment by UBParker** [comment]
Hi,

OK I will come to your office at 11am, Thank you.

Best,
Ashley

**Comment by mtosi** [comment]
;)
  mia

**Comment by sudhaahuja** [comment]
@UBParker - The B2G client and cff files you provided today were updated from this PR into PR #18978 in the following commit - https://github.com/cms-sw/cmssw/pull/18978/commits/fb01b61319972652e3e688d9658b70db166590d2

**Pull request closed without merging**
