### PR TITLE
Phase2-hgx356Y Update the Analyzer code for 2023 HGCal Test Beam codes utilizing 8 inch wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the Analyzer code for 2023 HGCal Test Beam codes utilizing 8 inch wafers

#### PR validation:

Tested using the TB code in SimG4CMS/HGCalTestBeam/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob please approve

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
