### PR TITLE
Use unique_ptr when constructing ProductHolders

### PR DESCRIPTION
**Pull request by Dr15Jones**
Change the interface in Principal from auto_ptr to unique_ptr when constructing ProductHolders.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
thanks!

**Comment by Dr15Jones** [comment]
llvm is unhappy? I don't think it came from this pull since that file doesn't read the header I changed.

**Comment by davidlt** [comment]
Known issue. Needs to be fixed at TBB level to properly detect Clang in this case. You don't get C++11 `emplace` with Clang because Clang reports GCC 4.2.1 compatibility.

**Pull request merged**
