### PR TITLE
Added names for hardcoded constants and added one TP plot

### PR DESCRIPTION
**Pull request by tanmaymudholkar**
1) Add Real vs Emulated TP Et plot
2) Replaced hardcoded constants for the number of inner and outer trigger towers with constant variables having suitable names

Similar PR made for 8_1_X: https://github.com/cms-sw/cmssw/pull/14368

### CODE REVIEW

**Comment by tanmaymudholkar** [comment]
Are there any updates regarding the status of this PR? Could someone please initiate tests? Thanks!

**Comment by vanbesien** [comment]
Hey @dmitrijus, we're gonna put this as a patch on the online testbed tomorrow. Can you take a quick look at the code to see if all looks fine?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
I need a 81x version of this

**Comment by tanmaymudholkar** [comment]
@dmitrijus : I had made a PR for the 81x version too. I included the link in the comment to reflect this. Here's the link again: https://github.com/cms-sw/cmssw/pull/14368

**Comment by dmitrijus** [comment]
Thanks! It is  much easier to follow if pull requests are cross-referenced.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
