### PR TITLE
SimVertexs collection for FastTiming studies

### PR DESCRIPTION
**Pull request by simonepigazzini**
Adding SimVertex collection for interaction vertices only (PU+Signal), the collection are produced as a slimmer version of the CrossingFrame transient collection. This PR addresses the memory issues of the default CFWriter module collections.

@amartelli

### CODE REVIEW

**Comment by simonepigazzini** [comment]
compiling with 'scram b runtests' locally does not show any error

**Comment by fratnikov** [comment]
The problem can be reproduced with (C-shell):
setenv LOCAL_TEST_DIR $CMSSW_RELEASE_BASE/src/Configuration/DataProcessing/test
$CMSSW_RELEASE_BASE/src/Configuration/DataProcessing/test/run_CfgTest.sh

**Comment by fratnikov** [comment]
Looks like the problem is not related to this PR

**Comment by davidlange6** [comment]
the unit test is also failing in the integration build - so indeed, its failure is unrelated.

**Comment by mark-grimes** [comment]
Just to update this PR with details discussed in private mail:
There is a big memory leak when reloading crossing frames from disk.  We are currently investigating doing the FastTimer studies using the TrackingVertex class instead of using SimVertex in CrossingFrames.  If this bears fruit this PR will be obsolete. I propose keeping it open until we know that works though.

**Comment by mark-grimes** [comment]
@simonepigazzini, you can close this now.  The required changes were introduced with #8975 and #8979.

**Comment by simonepigazzini** [comment]
thanks @mark-grimes. closing now

**Pull request closed without merging**
