### PR TITLE
New pixel geometry in runTheMatrix tests

### PR DESCRIPTION
**Pull request by davidlange6**
Merge #19091 and #19038

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
the tests are triggered with recycled gen-sim thanks to @smuzaffar

**Comment by kpedro88** [comment]
For some reason the 2017 WF comparison folders are empty. Both the baseline and PR matrix tests appear to have finished successfully...

**Comment by davidlange6** [comment]
yes, the comparison was ruined by the "INPUT" in the directory names due to the -i all..

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by smuzaffar** [comment]
I have restarted the comparison after fixing the dir/log file names. Results should be available in 30 mins

**Pull request merged**
