### PR TITLE
Adding OutIn Muon Step in Phase-2 tracking [91X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #18553

Requested for muon TDR.

attn: @ebrondol @VinInn @makortel @HuguesBrun

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
(Identical to #18553 in the master, same effect on jenkins outputs)

**Pull request merged**
