### PR TITLE
Phase2-hgx352 Modify the scenarios D104, D105 to accommodate modified T35 and I17 (also go back to C17 for D105). Add a new scenario D106 with C23 (same as C22 but without cell definition in Geant4)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the scenarios D104, and D105 to accommodate modified T35 and I17 (also go back to C17 for D105). Add a new scenario D106 with C23 (same as C22 but without cell definition in Geant4)

#### PR validation:

Tested with modified workflows 27234, 27634 and also with the new workflow 28034 (for 2026D106)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
FYI @emiglior @fabiocos

**Comment by civanch** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
Hi @bsunanda @emiglior @fabiocos 
Thanks @bsunanda for the PR. With this PR it means the order of validation will be
- D102 (new Tracker + Muon wrt D98)
and then if success
- 105 (new MTD wrt D102)

My original proposal is to have new MTD (I17) + D98, so that we can validate MTD and Tracker+Muon in parallel. If both success, we merge and validate again before moving. This will save PPD/PdmV time of campaign migration, we don't migrate twice in one release cycle.

**Comment by bsunanda** [comment]
@srimanob Please approve

**Comment by srimanob** [comment]
Hi @bsunanda 

Please acknowledge the above comment, as this PR does not follow what we have during the meeting. If we want to go to tracker-only first, I am fine that this PR to merge. But we will have a very short lifetime baseline, and effort will be almost double from the validation side. I would like to avoid it. If D105 contains only MTD changes, we can validate in parallel with tracker, i.e. with 14_0_0_pre3.

**Comment by srimanob** [comment]
+Upgrade

I propose to merge to avoid delay. @fabiocos could you please make the new one on top of this? Thx.

**Comment by fabiocos** [comment]
@srimanob I'll do it on top of this PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
