### PR TITLE
Phase2 OMTF emulator

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR introduces phase-2 specific part of the L1 OMTF emulator. It is build on top of phase1 OMTF emulator refactored in #43687. 
Changes by this PR are added in a new CMSSW package named `L1Trigger/L1TMuonOverlapPhase2`.

This PR adds currently non-present dependency of #44498.

FYI, @kbunkow, @akalinow, @aloeliger

#### PR validation:

Tested with matrix tests (limited set) and by the L1T software team during integration with the so-called "L1T integration branch": https://github.com/cms-l1t-offline/cmssw/pull/1196

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of this PR is not expected unless explicitly requested by the L1T team (backport to 14_0 could be possible).

### CODE REVIEW

**Comment by zhenbinwu** [comment]
@mbluj  Can you update this PR to include the fixes from https://github.com/cms-l1t-offline/cmssw/pull/1247.
Please only add the changes from `L1Trigger/L1TMuonOverlapPhase2/python/fakeOmtfParamsPhase2_cff.py` and `L1Trigger/L1TMuonOverlapPhase2/python/simOmtfPhase2Digis_extrapol_cfi.py `, as the other changes will be included in the GMT PR. Thanks

**Comment by mbluj** [comment]
> @mbluj Can you update this PR to include the fixes from [cms-l1t-offline#1247](https://github.com/cms-l1t-offline/cmssw/pull/1247). Please only add the changes from `L1Trigger/L1TMuonOverlapPhase2/python/fakeOmtfParamsPhase2_cff.py` and `L1Trigger/L1TMuonOverlapPhase2/python/simOmtfPhase2Digis_extrapol_cfi.py `, as the other changes will be included in the GMT PR. Thanks

Sure, I will include the fixes. However, I am afraid that if they are included manually, i.e. w.o proper include of commits, they will introduce merge conflicts. But, let's try this way.

**Comment by zhenbinwu** [comment]
> > @mbluj Can you update this PR to include the fixes from [cms-l1t-offline#1247](https://github.com/cms-l1t-offline/cmssw/pull/1247). Please only add the changes from `L1Trigger/L1TMuonOverlapPhase2/python/fakeOmtfParamsPhase2_cff.py` and `L1Trigger/L1TMuonOverlapPhase2/python/simOmtfPhase2Digis_extrapol_cfi.py `, as the other changes will be included in the GMT PR. Thanks
> 
> Sure, I will include the fixes. However, I am afraid that if they are included manually, i.e. w.o proper include of commits, they will introduce merge conflicts. But, let's try this way.

Thanks. Since these two files are part of the L1TMuonOverlapPhase2, I don't expect there will be conflicts from the GMT PR.

**Comment by mbluj** [comment]
Updated configuration files added in https://github.com/cms-sw/cmssw/pull/44557/commits/c68aa87943cad6516e1a774cd1dd9d1c7923df81. Changes require merging https://github.com/cms-data/L1Trigger-L1TMuon/pull/27 to cms-data.

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please abort

**Comment by aloeliger** [comment]
test parameters:
- pull_requests = https://github.com/cms-data/L1Trigger-L1TMuon/pull/27, https://github.com/cms-sw/cmssw/pull/44751
- workflow = 24834.78
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@artlbv @mbluj This PR removes several multi jet triggers from HLT in phase 2 workflows. Is that expected?

**Comment by artlbv** [comment]
Are you referring to these results? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-24-1100+93b48c/62531/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.log
```
Found 10 matching events, out of which 4 have different HLT results

      Events    Accepted      Gained        Lost       Other  Trigger
          10           0           -           -          ~4  HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
          10           0           -           -          ~4  HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
          10           0           -           -          ~3  HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
          10           0           -           -          ~4  HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
          10           0           -           -          ~4  HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
          10           0           -           -          ~3  HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4
Created the following JSON files:
 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/upload/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.json
```

I am not aware how HLT uses the L1 seeds, hence this is a question to @SohamBhattacharya and @rovere 
Also I do not know what `Other` means. Could someone clarify?

**Comment by artlbv** [comment]
After a quick look at the PR: it seems to only add a new package, but does not add the new producer in any sequence or as an input to e.g. the GMT. How could this affect the trigger results at all?

**Comment by mbluj** [comment]
This PR adds only OMTF Phase2 L1T stuff and should not directly affect any HLT paths, e.g. remove some of them. What could be a cause of the observed changes is #44751 which was run together in the recent tests. I wonder how #44751 is related to this PR and why it was included in tests.  Should #44498 be used instead?

**Comment by SohamBhattacharya** [comment]
> Are you referring to these results? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-24-1100+93b48c/62531/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.log
> 
> ```
> Found 10 matching events, out of which 4 have different HLT results
> 
>       Events    Accepted      Gained        Lost       Other  Trigger
>           10           0           -           -          ~4  HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
>           10           0           -           -          ~4  HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
>           10           0           -           -          ~3  HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
>           10           0           -           -          ~4  HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
>           10           0           -           -          ~4  HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
>           10           0           -           -          ~3  HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4
> Created the following JSON files:
>  /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/upload/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.json
> ```
> 
> I am not aware how HLT uses the L1 seeds, hence this is a question to @SohamBhattacharya and @rovere Also I do not know what `Other` means. Could someone clarify?

Afaik (see [comment](https://github.com/cms-sw/cmssw/pull/43738#issuecomment-1900186136) by @mmusich ) it's to do with reordering of the trigger bits. There's an open [issue](https://github.com/cms-sw/cmssw/issues/43790) on that.

**Comment by aloeliger** [comment]
Okay then. No issues

**Comment by aloeliger** [comment]
Ahh, upgrade needs to be added on this though. Hang on.

**Comment by aloeliger** [comment]
assign upgrade

**Comment by aloeliger** [comment]
Upgrade has been added to the `L1Trigger/L1TMuonOverlapPhase2` package by https://github.com/cms-sw/cms-bot/pull/2220 in the future.

**Comment by aloeliger** [comment]
@cms-sw/upgrade-l2 gentle ping on this

**Comment by srimanob** [comment]
@mbluj @aloeliger 

I am ok with the code. One thing I am not sure is that, in the test directory, your config use GT and Geometry which are not for Phase-2. Since they are in test config, I can ignore them for now. However, it is better if you clarify why you put in that way. Thx.

**Comment by srimanob** [comment]
+Upgrade

There are config files in the test which uses GT and Geometry from non Phase-2. It is unclear why, but I think they can be ignored for now.

**Comment by antoniovilela** [comment]
https://github.com/cms-data/L1Trigger-L1TMuon/pull/27 now merged.
cmsdist PR: https://github.com/cms-sw/cmsdist/pull/9179

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
