### PR TITLE
Fix dtSpecFilter of M9 and add DD4hep wf for D77

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR follows https://github.com/cms-sw/cmssw/pull/37078, to fix M9 geometry. In case we don't move to D88 in the near future, we plan to use D77 to vallidate DDD-vs-DD4hep of Phase-2. No change is expected for existing DDD wf (as see in the #37078).

#### PR validation:
Test with wf 35034.911 (TTbar NoPU D77 DD4hep XML)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport and no need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test with workflow 35034.911

**Comment by srimanob** [comment]
test parameters:
- workflow = 35034.911

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

This PR follows the discussion with @civanch @cvuosalo to fix dtSpecFilter on M9. This will allow us to validate Phase-2 DD4hep on D77 in case we will need to stay with it a bit longer. 

The PR test run fine with no change is expected on current DDD workflow. The new D77 DD4hep (35034.911) wf runs until finish.

**Comment by srimanob** [comment]
Urgent

Need it for 12_3_0_pre6, to allow DD4hep Phase-2 validation using D77

**Comment by kskovpen** [comment]
+pdmv

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
