### PR TITLE
Set MaxADC0 threshold to 9999

### PR DESCRIPTION
**Pull request by dertexaner**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
it looks like jenkins resources are out of order

**Comment by slava77** [comment]
jenkins current status:
rage

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10372 dc61c57
- changes are as expected, the same as in the 74X version
- jenkins tests pass and comparisons with the baseline show no difference as expected for the inputs used
- see #10371 summary for an example plot/effects in a run2 2015b dimuon data file in 251721

**Comment by davidlange6** [comment]
+1

**Pull request merged**
