### PR TITLE
RPCDigis validaiton module update

### PR DESCRIPTION
**Pull request by jhgoh**
#### PR description:

This PR is to update the RPCDigis validation.
Main motivation of the proposed change is to cleanup unused plots, fix empty plots if any
and add more useful plots to perform the release validation.

The proposal for this update was presented in the RPC-DPG working meeting 22 May 2024: [link to the slide](https://indico.cern.ch/event/1419527/contributions/5967272/attachments/2861397/5006306/%5B2024.05.22%5D%20Update%20of%20RPCDigi%20Validation.pdf)

This PR addresses suggestions during the meeting, to keep the plots for residual distributions but fixing the (known) bug in the code.
It only modifies/adds DQM plots during the validation step.

#### PR validation:

Performed tests on `CMSSW_14_1_0_pre3` release
- `runTheMatrix.py -l 12834.0` 
- Run cmsDriver step3 and step4 with the existing GEN-SIM-DIGI-RAW samples stored in eos (no crashes, DQM plots seems to be OK)
- code-checks OK
- code-format OK

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We want to have backport to the currently active release cycles
- 14_0_X
- 14_1_X

Possible watchers:  @mileva @mrcthiel

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

- getting fresh results

**Comment by tjavaid** [comment]
+dqm

**Comment by rappoccio** [comment]
+1

**Pull request merged**
