### PR TITLE
TrackingTools/RecoGeometry: change return type of ESProducers

### PR DESCRIPTION
**Pull request by gartung**
Remove class member that is not needed.
Change return type to unique_ptr and return directly from make_unique.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
looks good

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21986	b212d4a
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
