### PR TITLE
Fix several usages of un-initialized variables in DQM.

### PR DESCRIPTION
**Pull request by dmitrijus**
In CastorMonitor and DTSegmentsTask the initialization from
ParameterSet was commented out, I don't know why.
I haven't un-un-commented them, just added initial values.

In QcdPhotonsDQM the variable was used to count the number of events,
and scale the histogram at the endJob.
This should be done via dqm harvesting now what we are multithreaded,
and does not make sense in the DQMEDAnalyzer.
If someone cares or needs the rates (instead of actual
values), we will create a DQMEDHarvester.

In L1TdeCSCTF.cc the array was not properly initialized,
because of the single-character error left by the developer.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by deguio** [comment]
thanks @dmitrijus 
I believe that everything included in the endRun
https://github.com/dmitrijus/cmssw/blob/dqm_not_init/DQM/Physics/src/QcdPhotonsDQM.cc#L530
should be removed. I mean ratios as well in addition to the scaling you removed already (and the ratio MEs).

this is one of the modules for which nobody took care of consumes migration and MT migration. please just remove and we will find out if somebody complains.

this PR should be submitted to 75 and 76 as well.
cheers,
F.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
