### PR TITLE
Muon dqm 13 te v 74 x

### PR DESCRIPTION
**Pull request by folguera**
Added Efficiency Measurements for different IDs: Loose, Medium and Tight
Updated MuonRecoAnalyzer to use 13TeV HLT paths.
Added 2D phi vs eta plots to monitor possible holes.

Similar commit as PR: #9935 but back-porting changes to 74X

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
@folguera, can you also make an equivalent PR in 75x?

**Comment by folguera** [comment]
There is one already for 75X and for 76X.



El 20/8/2015, a las 18:06, danduggan <notifications@github.com<mailto:notifications@github.com>> escribió:


@folguera<https://github.com/folguera>, can you also make an equivalent PR in 75x?

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
