### PR TITLE
drop wrong default params in TLorentzVector in TestCorrections.C

### PR DESCRIPTION
**Pull request by slava77**
tested in root with simple .L TestCorrections.C, which now works

### CODE REVIEW

**Comment by slava77** [comment]
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30872/17239/code-format.patch
touches CondFormats/JetMETObjects/test/TestCorrections.C

@mrodozov @smuzaffar 
I thought that the code-checks were not supposed to apply to /test directories, even less so the root scripts.
Is this new?

**Comment by mrodozov** [comment]
they code checks not, this is code format. the format will be applied on anything that was touched.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mrodozov** [comment]
please test
this is weird

**Comment by slava77** [comment]
@cmsbuild please test

new IB is out now CMSSW_11_2_X_2020-07-22-1200

**Comment by mrodozov** [comment]
I know it's weird why it didn't picked it, twice

**Comment by slava77** [comment]
> I know it's weird why it didn't picked it, twice

the artifacts page https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/
has 22-1200 dated at 20:01.
The last failed attempt has "Started: 2020/07/22 19:47"
It seems reasonable to expect that at 19:47 it couldn't pick up 22-1200 yet.

**Comment by mrodozov** [comment]
right thats why, the IB was done earlier but not the baseline

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
merge
@ggovi this is a trivial fix in `CondFormats/JetMETObjects/test/TestCorrections.C`

**Pull request merged**
