### PR TITLE
New stop-run control and more debugging info on JSON parse error in input source (DAQ) - 80X

### PR DESCRIPTION
**Pull request by smorovic**
- File-based mechanism to stop data processing based on specific pid
- dump json library message full content of the json file in case before parsing exception is thrown

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15647 163c00b
- daq code changes, reco is not affected. The same change as in 81X 
- jenkins tests pass

**Comment by slava77** [comment]
backport of #15649

**Comment by davidlange6** [comment]
+1

**Comment by emeschi** [comment]
+1

**Pull request merged**
