### PR TITLE
DummyLHEAnalyzer: add option not to print event 

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Per request of K. Lassila-Perini, add to the DummyLHEAnalyzer the option to print only the header (to be used to extract configuration).

#### PR validation:

Test run on the output of step1 of wf 521.0.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

testing nothing...

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
@katilp FYI

**Comment by fabiocos** [comment]
+1

**Pull request merged**
