### PR TITLE
Apply suggested fix for Wdangling-reference

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

As suggested by @makortel here: https://github.com/cms-sw/cmssw/pull/45735/files/917d36f1e24533647eaff38bcf4400794d7fac13#r1723513370 I changed the way Wdangling-reference warnings are fixed. 

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el9_amd64_gcc13

**Comment by iarspider** [comment]
@cmsbuild ignore tests-rejected with ib-failure
Missing geometry files are due to https://github.com/cms-sw/cmssw/pull/45370

**Comment by mmusich** [comment]
> Missing geometry files are due to https://github.com/cms-sw/cmssw/pull/45370 

https://github.com/cms-sw/cmssw/pull/45764 should fix a bunch of them.

**Comment by perrotta** [comment]
+alca

**Comment by jfernan2** [comment]
+1

**Pull request merged**
