### PR TITLE
Add missing headers for DD4

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fix header check, two headers added

#### PR validation:

Builds

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by ianna** [comment]
@mrodozov - thanks, unless this goes in really fast, I'd prefer not to deal with rebasing the branches. The fix is coming in the next PR

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , we need to get this in to avoid header check error in IB. In order to avoid this in future, we make botto mark PR test failed if header check does not pass for development release cycle (i.e. 11.0.X now).

**Comment by fabiocos** [comment]
@smuzaffar yes, I had commented this morning https://github.com/cms-sw/cmssw/pull/27907/files#r319871916 , thanks to @mrodozov for the fix

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar we need to be careful about possible fake failures though...

**Pull request merged**
