### PR TITLE
Fix unit test: use LNF so that input files can be read from ibeos - 12_5_X

### PR DESCRIPTION
**Pull request by perrotta**
Unit tests failing for testSiStripHitEfficiency are annoying also in 12_5_X
Let backport @smuzaffar 's PR #39872 also in this release cycle

backport of #39872

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39872

**Comment by francescobrivio** [comment]
+alca 

 - verbatim backport of master PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
