### PR TITLE
[12.4.X] SiStripHitEfficiency PCL Workflow: miscellaneous fixes

### PR DESCRIPTION
**Pull request by mmusich**
backport of #38075

#### PR description:

This PR implements few bug-fixes in the SiStripHitEfficiency PCL Workflow as spotted in the Tier-0 replay https://github.com/dmwm/T0/pull/4674#issuecomment-1131255929.
   * 28b45e323b745b62daa0d6a025cd62b894733a77 loosens the cut on the track multiplicity (used to be 100 to limit the size of the internal SiStrip Calibration Trees, but now that the workflow is centrally supported that is not a problem anymore)
   * 412f37926b9a6d2a98d87415c14fd220440e0933 adds plots for monitoring the total number of tracks used and its correlation with PU
   * 1c9637e6c20683f47e04ea5d622053f5e7c157f8 and b8e5f2a92454baf25f1108328ebd6390c3ea81fc are the core of the bug-fix and allow several histograms that were previously empty to be filled.
   * 615a8718238c6991d5ec45677a95ad21b223d2c6 makes the input / output folder in the DQM file configurable
   * ed6ba6f681c8ea3373cad101f11e082878c1e49e reduces the amount of hardcoded constants in the code

#### PR validation:

I've run the following commands to test the `ALCAPROMPT` production:

```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiStripHitEfficiency --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Run2018D-SiStripCalMinBias-Express-v1/ALCARECO run=325172' --nThreads=4 --no_exec 
```

followed by:

```console
cmsDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiStripHitEfficiency.root -n -1 --no_exec                        
```
to test the `ALCAHARVESTING` step.
I have also run successfully:
   * `runTheMatrix.py -l 1001.0, 1001.2` 
   * `scram b runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of #38075

### CODE REVIEW

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/alca-l2, I have a branch with the same changes for 12.3.X too.
I know it's too late for the first collisions at 900GeV, let me know if you think it's worth opening a PR or not.

**Comment by tvami** [comment]
Hi Marco, given that we need the GEM change in 12_3_X for early 13.6 TeV collisions, I'd say it makes sense to do the 12_3_X backport.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
