### PR TITLE
Run2-hcx145 Change o/p definition for HBHEMuonFilter AlCaReco (Backport PR #20138)

### PR DESCRIPTION
**Pull request by bsunanda**
This PR allows AlCaReco files for HBHEMuonFilter to keep the prereco collection for HBHE so that one can look at the RecHits before depth collapsing. It is needed for calibration studies

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Kindly approve the backporting

**Comment by lpernie** [comment]
Hi @bsunanda I see several failures in the ALCARECO:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-08-15-1100+20180/21978/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/
There is some reason for that?

**Comment by bsunanda** [comment]
@lpernie I cannot think of anything. The changes as you see are mainly in the o/p collection. There are 3 other changed files which are nothing but cfg files for some test programs. These cannot change the comparison plots - addition of collection can only change the disk size for one AlCaReco (using HBHEMuons)

**Comment by lpernie** [comment]
@bsunanda Could you trigger the tests again? Maybe this was a glitch?

**Comment by lpernie** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
hello @lpernie @bsunanda,
the irreproducibility of  DQM comparisons in `AlCaReco/SiStrip/MechanicalView` that you can see in e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-08-21-2300+20180/22040/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/AlCaReco_SiStrip_MechanicalView.html) is a long standing issue described in https://its.cern.ch/jira/browse/CMSTRACK-151. 
As far as I know a fix has been provided for 93X in https://github.com/cms-sw/cmssw/pull/20050, but I think this has not been backported to 92X (hence the issue should still be present here). Should be safe to ignore.

**Comment by franzoni** [comment]
@bsunanda 
may you please describe this PR and its reason/purpose ?
thanks.

**Comment by bsunanda** [comment]
@franzoni Added some description - can it be approved now?

**Comment by bsunanda** [comment]
@franzoni @lpernie Can you approve this urgently

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
