### PR TITLE
EMTF emulate directly from unpacked CPPF digis - 10_2_X backport

### PR DESCRIPTION
**Pull request by abrinke1**
Backport of https://github.com/cms-sw/cmssw/pull/23747 for DQM, forward port of https://github.com/cms-sw/cmssw/pull/23919

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #23747

**Comment by thomreis** [comment]
Hi @abrinke1 
thanks for making this one. We still need a PR to the master with the last commit with the DQM configuration change.

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1
backport of #23747 and #24120

**Comment by fabiocos** [comment]
@thomreis as far as I understand, this PR does not modify the event content, but it affects the physics output of the simulation as well, do you confirm?

**Comment by fabiocos** [comment]
@thomreis actually it should not affect MC according to the discussion in master, could you please confirm it?

**Comment by abrinke1** [comment]
@fabiocos you are correct: this update does not affect anything in the MC.

**Comment by thomreis** [comment]
Hi @fabiocos 
@abrinke1 is one of the experts of the EMTF and his comment is correct.

**Comment by fabiocos** [comment]
@abrinke1 @thomreis perfect, thank you

**Pull request merged**
