### PR TITLE
[10.1.X] Bug fixed in SiStripBadComponentInfo

### PR DESCRIPTION
**Pull request by mmusich**
backport of #23554

Greetings,
this PR implements a bug-fix in SiStripBadComponentInfo.cc where bad fiber histogram never got filled (same a proposed in  #23491).
In addition for what concerns the addition of bad components from FED errors, this PR is implements a fix via cloning the `siStripQualityESProducer` and then modifying the attributes instead of just changing the attributes from the imported module.
Tested against the regular workflow (non-DQM based) and found perfect agreement.
@suchandradutta  @fioriNTU @jandrea @arossi83

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
dear @jfernan2, any objection to signing this backport of #23554? 
The same changes have been merged in the master branch and included in the CMSSW_10_2_X_2018-06-12-2300 IB, where they don't seem to cause troubles.
It would be desirable to have this fix in production as soon as we restart taking data after the TS, since there are other potential downstream workflows in data certification that can profit of this.
Thanks,
Marco

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

tested in Configuration/DataProcessing on 2018B express and prompt

**Pull request merged**
