### PR TITLE
Geometry FileBlob Dump

### PR DESCRIPTION
**Pull request by ianna**
* Add an analyzer and its configuration to dump a specific FileBlob as xml

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - please, include it in the next IB

**Comment by ianna** [comment]
@davidlange6 - please, include it for the next IB

**Comment by ianna** [comment]
@davidlange6 - please, include it for the next IB

**Comment by ianna** [comment]
@davidlange6 - please, include it in the next CMSSW_8_1_X. It is needed for geometry validation.

**Comment by ianna** [comment]
@davidlange6 - as discussed at ORP this is needed in 81x for geometry comparison. I'm expecting with the "new" HCal the question will arise again.

**Comment by ianna** [comment]
@davidlange6 - please include it in the next 81x

**Pull request closed without merging**
