### PR TITLE
Fix dtSpecsFilter XML used by Phase-2 wf for DD4hep

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
It seems we are missing the update on dtSpecsFilter.xml, which happened in 2019, in Phase-2 XMLs (introduced in https://github.com/cms-sw/cmssw/pull/26218 and updated in https://github.com/cms-sw/cmssw/pull/26535). This leads to the crash of DT superlayer & layer producer in mb3, see report in https://github.com/cms-sw/cmssw/issues/36837#issuecomment-1046148021.

This code
https://github.com/cms-sw/cmssw/blob/master/Geometry/DTGeometryBuilder/plugins/DTGeometryESModule.cc#L194-L195
looks for MuonBarrelDT in DD4hep detector construction.

I currently migrate only M10. This should be OK if we want to use D88 as a starting point of DD4hep migration. However, migration of M9 or older is fine for me. This is to discuss with Geometry expert and come in the follow up PR.

FYI @slomeo @ianna @civanch @cvuosalo 

#### PR validation:
Local test of workflow 39634.911 with #37005 runs until the ends. We have a warning from HCAL to follow (but it does not stop the job)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport, and no need of backport

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 39634.911
- pull_request = #37005
- relvals_opt = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please abort

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
test parameters:
- workflows = 39434.911
- pull_request = #37005
- relvals_opt = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Same comment mentioned in https://github.com/cms-sw/cmssw/pull/37079#issuecomment-1053708966

**Comment by srimanob** [comment]
+Upgrade

This PR will make Phase-2 D88 DD4hep wf runs until complete. The validation of result should come in the follow up PR. PR test result is as expected, https://github.com/cms-sw/cmssw/pull/37079#issuecomment-1053708966

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
@srimanob do I understand correctly that this PR does not need #37005 for being merged? Should we trigger the tests without that other PR for doing so?

**Comment by srimanob** [comment]
Hi @perrotta 
No, this PR does not need #37005. This PR fix the obsolete xml file defined in Phase2 geometry XML. You can trigger the test as standalone. As far as I understand, the DDD workflow will not affected by the change in this PR. But this can be seen in the last test also. Thanks.

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
I think the test result is as expected. It does not touch DDD workflow. 
By the way, do we understand the issue of warning in MTD Failing Comparisons of simPVZ?

**Comment by perrotta** [comment]
> I think the test result is as expected. It does not touch DDD workflow. By the way, do we understand the issue of warning in MTD Failing Comparisons of simPVZ?

Thank you @srimanob, I'm going to sign this then
About the (long standing) issues of the non reproducible MTD comparisons in DQM, which is totally unrelated from this PR but worth being solved sooner or later, it should be rather addressed to MTD and/or DQM.

**Comment by perrotta** [comment]
+1

**Pull request merged**
