### PR TITLE
Migrate leftover modules

### PR DESCRIPTION
**Pull request by lgray**
Migrate some leftover modules to the threaded framework.
Most seem to be deprecated.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Failed because of:
```NameError: global name 'customiseFor10234' is not defined```

Guess the IB is broken.

**Comment by lgray** [comment]
@mulhearn 76X IBs won't run because of this. Can you please fix this up (saw you put this customize in, but it didn't survive 75X->76X)? 

That function name does not exist here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/HLTrigger/Configuration/python/customizeHLTforCMSSW.py

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10335 8c7798a75fd2904728473289602dd3a58ae0abfb

Migration of some remaining E/Gamma and PF modules to support multi-threading. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10335/6692/summary.html) against baseline CMSSW_7_6_X_2015-07-25-2300 show no significant differences, as expected.

**Comment by lgray** [comment]
@monttj @vadler +1 here please, and for backports too (unless there is a problem?

**Pull request merged**
