### PR TITLE
Updated configurations in SimG4CMS to new MessageLogger syntax

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All configurations in SimG4CMS subsystem which explicitly create a MessageLogger have been converted to the new syntax.
#### PR validation:

All files were passed to `python` and no failures as a result of these change were seen.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda FYI

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
