### PR TITLE
Pr80x l1t integration (upto 89.20) fix SumEt, uGT prescales, memory leaks, clean-up

### PR DESCRIPTION
**Pull request by rekovic**
PR 80x. Replaces #16717.  It is needed in 80x for multiple reasons:

1. HI MC production 
2. Analysis of Trigger of 2016 runs

Compared to #16717 it has:

- fix to SumEt packer introduced in 8_0_22
- fix in GT prescales to cover all 512 files 
- fixes a problem of a few missing commits

Now after back-port of #17053, it merges all the development
in l1t-integration up to v89.20, so it also has

- New EGamma var (HoverE) in DataFormats/L1Trigger
- Gen fix in L1TNtuple

(For completion)PR #16717 Includes all fixes for the L1T emulator:
- BMTF unpacker memory leak
- TwinMux memory leak (already in 81x)
- Layer2 emulator to do what in FW (bug in FW tower max eta in TowerCount for HI)
- Turn off warnings in L1T Ntuple maker.
- uGT handling of saturated Et bins in CorrelationConditions to be as in FW.

### CODE REVIEW

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
all the above tests are failling due to a missing new prescales table, which is PRed 
https://github.com/cms-data/L1Trigger-L1TGlobal/pull/6
@smuzaffar, please merge the above data, and I will restart the tests.

**Comment by rekovic** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2738

**Comment by rekovic** [comment]
@smuzaffar I cannot access the test summary page
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16966/88/summary.html

Is there some other page that is available?

**Comment by rekovic** [comment]
Last set of commits is the back port of #17053, so l1t-integration v89.15 to v85.20.

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by mandrenguyen** [comment]
Hi @rekovic , the DIGI production for the pA will be ready to start soon.  It looks like this PR is needed.  What's the prospects for solving this error in the addOn test?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2738
this needs to be tested along with the external data

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2738

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2738
this should be tested along with the external

**Comment by davidlange6** [comment]
+1

**Pull request merged**
