### PR TITLE
Pr103x hi 2018 uGT

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_3_X

HeavyIon 2018 updates for the uGT emulator.

This PR takes advantage of HeavyIon developments in CaloLayer2 emulator (#24569)
and the UTM library v 0.7.1 (external  cms-sw/cmsdist#4338) which provides the interface b/w the L1TMenu xml and this uGT emulator.  

Both are needed for this PR to successfully test.

### CODE REVIEW

**Comment by fabiocos** [comment]
@rekovic please check the suggested fix

**Comment by rekovic** [comment]
@fabiocos 
I am not sure about the suggested fix. 
Is there any way we can test this PR as is?

**Comment by rekovic** [comment]
please test with #24569

**Comment by davidlange6** [comment]
some impressive cascades of if statements;)

you might confirm that this code compiles, often not compiling is a reason for clang-tidy to do something strange.likely the new utm library was not available?

**Comment by rekovic** [comment]
@davidlange6 Thanks.

The new UTM library should be in the IB from last night at 0000.
https://github.com/cms-sw/cmsdist/pull/4338

In which log can I check against which version of IB is this PR being tested?

**Comment by davidlange6** [comment]
so it would have required a time machine in this case. You can see from the logs what was done.

**Comment by davidlange6** [comment]
code-checks

**Comment by rekovic** [comment]
Ok. Thanks for restarting code checks.

Now the code-check patch with newer  IB `CMSSW_10_3_X_2018-09-17-2300`
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24570/6465/git-diff.patch
are much smaller that with previous IB `CMSSW_10_3_X_2018-09-17-1100`
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24570/6460/git-diff.patch

**Comment by rekovic** [comment]
Still the suggested patch does not make sense to me.
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24570/6465/git-diff.patch

**Comment by rekovic** [comment]
@fabiocos @kpedro88 
Can we disable the code checks here, as the suggested patch, although very small,  does not make sense ?

**Comment by davidlange6** [comment]
does your code compile in the IB used?

**Comment by kpedro88** [comment]
@rekovic the code is not correct. Check the full log: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-24570/6465/code-checks.log

It is complaining about this:
```
/build/cmsbld/jenkins/workspace/run-pr-code-ckecks/CMSSW_10_3_X_2018-09-17-2300/src/L1Trigger/L1TGlobal/plugins/GtRecordDump.cc:487:38: error: no member named 'kCentrality' in 'l1t::EtSum::EtSumType' [clang-diagnostic-error]
                       case l1t::EtSum::EtSumType::kCentrality:
                                                   ^
/build/cmsbld/jenkins/workspace/run-pr-code-ckecks/CMSSW_10_3_X_2018-09-17-2300/src/L1Trigger/L1TGlobal/plugins/GtRecordDump.cc:729:10: error: no member named 'kCentrality' in 'l1t::EtSum::EtSumType'; did you mean 'centrality'? [clang-diagnostic-error]
           case l1t::EtSum::EtSumType::kCentrality:
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                centrality
```

`EtSumType` is the name of the enum, not a namespace. You should refer to the enum value as ` l1t::EtSum::kCentrality`.

**Comment by davidlange6** [comment]
my guess is that you miss a needed change in ETSum.h for this code to compile...

**Comment by davidlange6** [comment]
whoops I pressed the wrong button

**Comment by davidlange6** [comment]
its just #24569 missing...

**Comment by rekovic** [comment]
Thanks @kpedro88 and @davidlange6 for the comments. 
Yes, it needs #24569 to be tested.

**Comment by rekovic** [comment]
With the IB of last night CMSSW_10_3_X_2018-09-17-2300 + #24569, this PR compiles.
```
cmsrel CMSSW_10_3_X_2018-09-17-2300
cd CMSSW_10_3_X_2018-09-17-2300/src
cmsenv
git cms-init
git chk -b mydevel
git cms-merge-topic -u 24569
git cms-merge-topic -u 24570
scramv1 b -j 4
```

> so we wait for #24569 to be merged and then restart the code checks.

OK. Thanks @smuzaffar.

**Comment by fabiocos** [comment]
+code-checks

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
+1

**Pull request merged**
