### PR TITLE
hltGetConfiguration: update server URL

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
hum, git is unhappy with this PR as it claims it cannot be merged (I won't manage to investigate until later, but maybe @fwyzard you have a moment)

**Comment by fwyzard** [comment]
I do not know why github complains about merge conflicts, I tried rebasing on top of the latest CMSSW_7_3_X, and it says it is already up to date.

**Comment by fwyzard** [comment]
closed, and re-opened as #7243

**Pull request closed without merging**
