### PR TITLE
Offline DQM for Top and BTV -  CMSSW_9_2_X

### PR DESCRIPTION
**Pull request by defranchis**

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by fwyzard** [comment]
backport to 92x of #19119 and #19471

**Comment by dmitrijus** [comment]
+1

**Comment by defranchis** [comment]
@davidlange6 this PR adds 487138 bins (and should be the first one to be merged)

**Comment by slava77** [comment]
-1

needs rebase
http://cms-sw.github.io/tutorial-resolve-conflicts.html may help

**Comment by slava77** [comment]
-1

still not good

**Comment by defranchis** [comment]
@slava77 it's probably better I open a new PR with a new branch

**Comment by defranchis** [comment]
new PR: https://github.com/cms-sw/cmssw/pull/19616

**Pull request closed without merging**
