### PR TITLE
Update Global Tag for Collisions2016_v1 L1T menu and splitting Ecal Pedestal tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v13) as [80X_mcRun2_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v13/80X_mcRun2_design_v12): 
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v12) as [80X_mcRun2cosmics_startup_peak_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v12/80X_mcRun2cosmics_startup_peak_v11): 
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v13) as [80X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v13/80X_mcRun2_asymptotic_v12): 
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
- **RunII Startup scenario** : [80X_mcRun2_startup_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v13) as [80X_mcRun2_startup_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v13/80X_mcRun2_startup_v12): 
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
## RunII data
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v9) as [80X_dataRun2_HLTHI_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v9/80X_dataRun2_HLTHI_frozen_v7): 
  - new tag for DT and CSC Alignment errors (allow updates via append IOV with hlt synchronization)
  - updated AK4CaloHLT JEC with L2L3 residuals for [CMSHLT-518](https://its.cern.ch/jira/browse/CMSHLT-518)
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v12) as [80X_dataRun2_HLT_frozen_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v12/80X_dataRun2_HLT_frozen_v11): 
  -  new tag for DT and CSC Alignment errors (allow updates via append IOV with hlt synchronization)
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v10) as [80X_dataRun2_HLT_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v9/80X_dataRun2_HLT_relval_v8): 
  - new tag for DT and CSC Alignment errors (allow updates via append IOV with hlt synchronization)
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
- **RunII Offline processing** : [80X_dataRun2_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v14) as [80X_dataRun2_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v14/80X_dataRun2_v13): 
  - split Ecal pedestal tags as agreed in [AlCa meeting](https://indico.cern.ch/event/523683/contributions/2145029/attachments/1263035/1868225/AlCaDB-v12.pdf) to ease validation procedure
- **RunII Offline relval processing** : [80X_dataRun2_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v11) as [80X_dataRun2_relval_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v11/80X_dataRun2_relval_v9): 
  - update uGT L1 menu to `L1Menu_Collisions2016_v1_xml`
  - split Ecal pedestal tags as agreed in [AlCa meeting](https://indico.cern.ch/event/523683/contributions/2145029/attachments/1263035/1868225/AlCaDB-v12.pdf) to ease validation procedure

### CODE REVIEW

**Comment by mmusich** [comment]
plese test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 @mulhearn 
What is holding up this PR?

**Comment by Martin-Grunewald** [comment]
@davidlange6 
What is holding up integration of this PR?

**Comment by mmusich** [comment]
@Martin-Grunewald, nothing is holding this on the alca side

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi @mmusich 
Something must have gone wrong as there is now an error on an HIon real-data workflow:
(cf https://github.com/cms-sw/cmssw/pull/14325 addOn test) using ```run2_hlt_hi```:
```
----- Begin Fatal Exception 11-May-2016 21:37:51 CEST-----------------------
An exception of category 'InvalidInput' occurred while
   [0] Processing run: 263689 lumi: 5 event: 395501
   [1] Running path 'HLT_HIPuAK4CaloJet40_Eta5p1_v2'
   [2] Calling event method for module LXXXCorrectorProducer/'hltAK4CaloResidualCorrector'
Exception Message:
 cannot find key 8 in the JEC payload, this usually means you have to change the global tag
----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
@mmusich 
Hmm, I can't reproduce the jenkins test failure offline....

**Comment by mmusich** [comment]
@Martin-Grunewald let me have a look.

**Comment by mmusich** [comment]
@Martin-Grunewald indeed everything looks fine:
```
$ conddb list 80X_dataRun2_HLTHI_frozen_v9 | grep AK4Calo
JetCorrectionsRecord         AK4CaloHLT     JetCorrectorParametersCollection_HI_PythiaCUETP8M1_5020GeV_753p1_AK4Calo_v4_hlt

$ conddb list JetCorrectorParametersCollection_HI_PythiaCUETP8M1_5020GeV_753p1_AK4Calo_v4_hlt
Since: Run   Insertion Time       Payload                                   Object Type                       
-----------  -------------------  ----------------------------------------  --------------------------------  
1            2016-03-07 17:26:34  d9f9a8bc9eb2f4c40aa1dee8d5c90aebe28c5d41  JetCorrectorParametersCollection  

$ conddb dump d9f9a8bc9eb2f4c40aa1dee8d5c90aebe28c5d41 | grep first
			<first>1</first>
			<first>2</first>
			<first>8</first>
			<first>10</first>
```
maybe the tests were trigger against an IB yet without the update?
How are we doing in 81X? We have the same Heavy Ion Data GT there. Is the HLT table the same as in #14325 ?

**Comment by Martin-Grunewald** [comment]
Everywhere else it does work indeed!
So I guess you are right, the IB used for the jenkins test did not yet include the PR.
I asked for new tests (I thought once an IB is listed on the IB page it is used for the tests, but in this case there may have been a delay - maybe due to a specific architecture not ready).
So let's see what the new test brings.

**Comment by Martin-Grunewald** [comment]
@mmusich 
OK, all is fine with the tests redone! Thanks for your checking and apologies for the noise.

**Pull request merged**
