### PR TITLE
[Not to merge] first attempt to run ULHLT in runTheMatrix in a single step

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:

This PR is not to merge for now. This is a first attempt to setup runTheMatrix to be able to inject the whole MC for UL, including HLT using the native release in 1 step.

#### PR validation:

> runTheMatrix.py --what run2UL -l 2250200.17 --noCaf -t 4 -m 11500 -b 'ul17_pilot_1' --label 'ul17_pilot_4' --wm init

gives the reasonable JSON

But with --wm force, we still have issue to upload HLT config, as HLT_2e34v40_cff does not exist in 10_5. Trying to work that.

> Importing the config, this may take a while... Importing the config, this may take a while...Traceback (most recent call last):
>   File "/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/bin/slc7_amd64_gcc700/runTheMatrix.py", line 338, in <module>
>     ret = runSelected(opt)
>   File "/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/bin/slc7_amd64_gcc700/runTheMatrix.py", line 41, in runSelected
>     wfInjector.upload()
>   File "/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/python/Configuration/PyReleaseValidation/MatrixInjector.py", line 664, in upload
>     d['ConfigCacheUrl']
>   File "/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/python/Configuration/PyReleaseValidation/MatrixInjector.py", line 641, in uploadConf
>     cacheIds = pool.map( upload_to_couch_oneArg, [(filePath,labelInCouch,self.user,self.group,where)] )
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/multiprocessing/pool.py", line 253, in map
>     return self.map_async(func, iterable, chunksize).get()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/multiprocessing/pool.py", line 572, in get
>     raise self._value
> ImportError: No module named HLT_2e34v40_cff

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by srimanob** [comment]
adding PYTHON27PATH does not help,

> DEBUG - new filePath (ULHLT) = /afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_9_4_13_patch2/src/2250200.17_ZEE_13UP17+ZEE_13UP17+DIGIPRMXUP17_NoHLT_PU25+ULHLT17+RECOPRMXUP17_PU25_PRODLIKE/ULHLT17.py
> DEBUG-UploadToCouch-filePath: /afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_9_4_13_patch2/src/2250200.17_ZEE_13UP17+ZEE_13UP17+DIGIPRMXUP17_NoHLT_PU25+ULHLT17+RECOPRMXUP17_PU25_PRODLIKE/ULHLT17.py
> /afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/python:/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_10_5_0_pre2/lib/slc7_amd64_gcc700:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0_pre2/python:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_0_pre2/lib/slc7_amd64_gcc700:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/coral/CORAL_2_3_21-dlmfga2/slc7_amd64_gcc700/python:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/coral/CORAL_2_3_21-dlmfga2/slc7_amd64_gcc700/lib:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/xrootd/4.8.5/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/external/fastjet/3.3.0-omkpbe/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-tool-conf/45.0-dlmfga2/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc7_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_13_patch2/python
> ULHLT17
> /afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_9_4_13_patch2/src/2250200.17_ZEE_13UP17+ZEE_13UP17+DIGIPRMXUP17_NoHLT_PU25+ULHLT17+RECOPRMXUP17_PU25_PRODLIKE
> <open file '/afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_9_4_13_patch2/src/2250200.17_ZEE_13UP17+ZEE_13UP17+DIGIPRMXUP17_NoHLT_PU25+ULHLT17+RECOPRMXUP17_PU25_PRODLIKE/ULHLT17.py', mode 'U' at 0x7f0d04e6b930>
> /afs/cern.ch/work/s/srimanob/test/UL-HLT/development/git/CMSSW_9_4_13_patch2/src/2250200.17_ZEE_13UP17+ZEE_13UP17+DIGIPRMXUP17_NoHLT_PU25+ULHLT17+RECOPRMXUP17_PU25_PRODLIKE/ULHLT17.py
> ('.py', 'U', 1)

We still see the issue on uploading. It seems to come from
https://github.com/cms-PdmV/wmcontrol/blob/master/modules/wma.py#L197-L198

**Comment by davidlange6** [comment]
hi

Thinking bigger picture, I see several things that we probably don't want 
1) Releases calling out to other magic releases. No way for WM to understand this (as it wants self-describing software stacks) 
2) hardwired cvmfs dependencies
3) any hacking of env-vars - the better approach will be to create a subprocess, create a new scram area and cmsenv. [this avoids concern 2 but not concern 1]

**Comment by srimanob** [comment]
Hi,
Thanks for comment. 

> hardwired cvmfs dependencies
At this step, I want to solve the issue of uploading, so I do hard-code on adding PYTHON27PATH to cover 9_4 for now, this should be changed at the end.

> Releases calling out to other magic releases. No way for WM to understand this (as it wants self-describing software stacks)
Not clear. As the goal is to dump the configuration properly, proper JSON is created as a taskchain, and configuration is uploaded successfully.

**Comment by davidlange6** [comment]
> On Mar 13, 2019, at 4:48 PM, Phat Srimanobhas <notifications@github.com> wrote:
> 
> Hi,
> Thanks for comment.
> 
> hardwired cvmfs dependencies
> At this step, I want to solve the issue of uploading, so I do hard-code on adding PYTHON27PATH to cover 9_4 for now, this should be changed at the end.
> 
> Releases calling out to other magic releases. No way for WM to understand this (as it wants self-describing software stacks)
> Not clear. As the goal is to dump the configuration properly, proper JSON is created as a taskchain, and configuration is uploaded successfully.
> 

I guess i'm saying that doing this within one cmssw release is the wrong goal. CMS uses multiple releases to run production workflows routinely, this should not be new.

**Comment by srimanob** [comment]
> I guess i'm saying that doing this within one cmssw release is the wrong goal. CMS uses multiple releases to run production workflows routinely, this should not be new.

Ah, understand, and totally agree. I think one point to start is how we use runTheMatrix and McM: 
- runTheMatrix: we create the release and inject from configuration that dump from that. This is the start point that I work on, to setup another release on top of that.
- McM, each request/task is set separately on difference campaign, then we link them together later

**Comment by kpedro88** [comment]
can this be closed?

**Comment by srimanob** [comment]
Closed.

**Pull request closed without merging**
