### PR TITLE
Run3-hcx241 Cleanup some of the algos and files for testing dd4hep implementation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Cleanup some of the algorithms used in describing Hcal TB setups and configuration files for testing dd4hep implementation

#### PR validation:

Tested using cfg files in Geometry/HcalAlgo/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , this https://github.com/cms-sw/cmssw/pull/28396#issuecomment-553938228 comparison was run on new Open stack VM. I restarted it on new VM to see if comparison works and produce consistent results.

**Comment by fabiocos** [comment]
@smuzaffar thanks for warning me, let's see

**Comment by fabiocos** [comment]
+1

**Pull request merged**
