### PR TITLE
Avoid unneccessary copies in RecoParticleFlow__PFProducer with emplace

### PR DESCRIPTION
**Pull request by guitargeek**

### CODE REVIEW

**Comment by slava77** [comment]
@guitargeek 
did you see any change in performance?
Most of your changes look like the compiler will do already and will yield a no-op from this PR.

**Comment by guitargeek** [comment]
Hi Slava, no I didn't check performance. Sorry, I suddenly had no time anymore to write a good description.

So here is the thing: working on the EGamma PF algo to e.g. improve it for low-pt is not so easy because the code is hard to digest. One of my little personal goals is therefore to refactor PFEGammaAlgo to make it more comprehensible such that is can be easily hacked with and improved.

In the past I made some experience with my "mammoth" PRs, which I think might took just more time to review than if there were split up in little pieces because they touched many aspects at once.

So yes, this PR does nothing except for making the code (in my opinion) more expressive. Why counting on compiler optimizations if you can say with even fewer words how it should be?

So: this PR would be just a tiny step towards a bigger goal. It's up to you to decide if that makes sense or if it would be just a waste of effort :)

**Comment by slava77** [comment]
@guitargeek 
thanks for the longer message.

I was just trying to understand if "avoid unnecessary copies" was a factual thing at run time.
If it is the case, it can be a reason to review similar cases in our code base. Otherwise, it has less incentive to be applied elsewhere.

I'm fine if this is just a cosmetic update.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24846	034f525
- technical update; there is no clear evidence that this introduces reduction in CPU use or memory allocations. Still, the style is improved.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
