### PR TITLE
Me0 digitizer neutr bkg fix slhc

### PR DESCRIPTION
**Pull request by pietverwilligen**
Neutron background simulated in the ME0Digitizer did not follow the shape of the implemented polynomial function. This is fixed now.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by pietverwilligen** [comment]
Hi David

I checked myself the first workflow that is not working: 12800, and I see that it breaks with exactly the same errors when I am running without my pull request, in a fresh CMSSW_6_2_SLHCDEV_X_2016-01-10-1100. So it seems that this build was broken in the first place, and not due to my pull request. 

Do you know what exactly is going on? Can you test my pull request on top of a working build?
Thanks
Piet

**Comment by davidlange6** [comment]
please test

**Comment by pietverwilligen** [comment]
so still the same workflows are providing errors ... I am quite convinced the problem has nothing to do with this pull request but with the release itself. Note that the same PR for 800 passed without any problems: #12945. What do you suggest to do David?

**Comment by pietverwilligen** [comment]
Hi David
How shall we proceed to get this PR included?
Thanks
Piet

**Comment by davidlange6** [comment]
@pietverwilligen - we've been getting the slhcdev tests to work. 
what is the 80x PR for this? (or plan to get it there)

**Comment by davidlange6** [comment]
please test

**Comment by pietverwilligen** [comment]
Hi David.
Thanks for looking into this. The corresponding PR for 80X is #12945.
greets
Piet

On Sun, Jan 31, 2016 at 9:47 PM, cmsbuild <notifications@github.com> wrote:

> +1
> Tested at: 75180f8
> <https://github.com/cms-sw/cmssw/commit/75180f89940a9a1bc6f6b6f87c05fb1168b91ee8>
>
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12944/10864/summary.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/12944#issuecomment-177606184>.
>



-- 
Piet Verwilligen

INFN -- Sezione di Bari
Via E. Orabona 4
I-70125 Bari, Italy
Phone: +39 345 74 70 642

**Pull request merged**
