### PR TITLE
[14_0_X] Update HLTPixelTrackFilter to store candidates

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/45373

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

@vince502 @mandrenguyen

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
type hlt-int

**Comment by rappoccio** [comment]
+1

**Pull request merged**
