### PR TITLE
[HGC trigger] Update mapping for V11 (backport 11_1_X)

### PR DESCRIPTION
**Pull request by silviodonato**
Backport of #30470

#### PR description of #30470:
Updated mapping for V11 after the changes in the cell validity checks implemented in #30323

Depends on external cms-data/L1Trigger-L1THGCal#19
Since PR #30323 has been reverted, it should be tested with #30467 + re-enable of L1T HGCAL in V11 (since it is disabled in #30467).

### CODE REVIEW

**Comment by silviodonato** [comment]
@jbsauvan @bsunanda Could you confirm that we need to backport #30467? I'm trying to do it but it is not trivial. Could you have a look?

**Comment by silviodonato** [comment]
please test with cms-data/L1Trigger-L1THGCal#19

**Comment by jbsauvan** [comment]
In principle this PR should work even without #30467. But I'm not sure what #30467 brings in addition to the cell validity criteria and whether it can be backported.

**Comment by silviodonato** [comment]
merge

**Pull request merged**
