### PR TITLE
bsunanda:Phase2 hgx41Validation code due to Maksat

### PR DESCRIPTION
**Pull request by bsunanda**
This watches steps in simulation and prepares data for validating geometry and hits

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1
Now the test is working but the sub-package requires clean-up of the directory structure

**Comment by bsunanda** [comment]
@deguio Please review the code and approve. Do you want us to explain this in some meeting?

**Comment by deguio** [comment]
ciao @bsunanda 
sorry for being late.
it is not fully clear why the class SimG4HGCalValidation.cc should go in the Validation code. normally we accept only analyzers that book histograms there. is the addition of a plotting step foreseen for those products?

F.

**Comment by bsunanda** [comment]
Yes - of course. Maksat is preparing the code for plots - that part of the code is being tested right now.
________________________________

**Comment by deguio** [comment]
+1

**Comment by bsunanda** [comment]
@davidlange6 Could you please merge this. We would like to add some addition on top of this soon.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
