### PR TITLE
Fix position of unconstrained pT coming from OMTF (backport for 14_0_X)

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

Due to a miscommunication the incoming unconstrained pT from OMTF as expected at the wrong position in the bitword on the link. This PR fixes this.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/44798

### CODE REVIEW

**Comment by aloeliger** [comment]
type bug-fix

**Comment by aloeliger** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44798

**Comment by aloeliger** [comment]
please test

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
