### PR TITLE
SIM code cleanup

### PR DESCRIPTION
**Pull request by civanch**
Fixed some static analyser warnings; removed commented lines and unused headers; added getByToken; added c++11 keywords. For HcalTestBeam enable Russian roulette by default; fixed sampling of noise in HCAL.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
