### PR TITLE
[13_0_X] [Nano] Fix JetTable genJetIdx matching

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/41039 for NanoAODv12 production in 13_0_X.

### CODE REVIEW

**Comment by swertz** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41039

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
