### PR TITLE
Test Candidate GTs for 2017 and 2018

### PR DESCRIPTION
**Pull request by ianna**
* Test candidate GTs which include new reco material as defined in #18824 

@arunhep and @franzoni - If full comparison tests are satisfactory, I'll submit a request for new GTs

@slava77 and @rovere - please, check and confirm if this change indeed improves reconstruction

@boudoul, @veszpv, @VinInn - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
assign reconstruction

**Comment by ianna** [comment]
assign simulation

**Comment by ianna** [comment]
assign analysis

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
@slava77 and @rovere - as expected this PR introduces changes in reco material for 2017 and 2018:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-06-20-2300+19390/20807/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/Tracking__RecoMaterial_DeltaPt_in_out_vs_eta.png
as well has an impact on Tracking and Physics. Please, confirm if these changes are acceptable.

**Comment by slava77** [comment]
From the GT comparison it doesn't look like this PR is testable in full
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v2/92X_upgrade2017_realistic_Candidate_2017_06_21_08_28_33: PFCalibrations_v6 can not be used with the baseline IB. This issue affects only PF reco and tracking plots should still be usable.

I noticed that the content of TKExtra_Geometry_92YV1 and TKExtra_Geometry_92YV3 is identical. Is this expected?

**Comment by franzoni** [comment]
hold

**Comment by franzoni** [comment]
@ianna hi,
@arunhep and I have no clear picture of what leads to this pr,
 hence the conversation planned with @rovere  and you later today

We put on hold in relation to 3 other AlCa  integration pull requests which have been in the pipeline  for a while, which we  need  a to  perform  sequentially , in  order to avoid conflicting changes

**Comment by ianna** [comment]
@slava77 - yes, TKExtra_Geometry_xxx contains GeometricDetExtra. These describe simulated properties (material, density, volume) which did not change. Only GeometricDet s are changed (rad. length, interaction length).

**Comment by rovere** [comment]
Hi all,
judging from the differences here and the one that I privately produced[1], I think we can safely deploy the original material tuning that @ianna already integrated into this GT.

Ciao,
M.

[1]
https://rovere.web.cern.ch/rovere/MaterialTuningAfterPR18651/FullValidation/

**Comment by arunhep** [comment]
@rovere thanks for the checks and confirmation.
@ianna can you please announce the 92YV3 (tags containing first iteration of reco material update, which is sufficient) and we will consider them in next update of global tags.

**Comment by ianna** [comment]
@rovere - thanks! I'll close this PR and announce the 92YV3 tags.

**Comment by slava77** [comment]
On 6/21/17 11:20 PM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - yes, TKExtra_Geometry_xxx
> contains GeometricDetExtra. These describe simulated properties
> (material, density, volume) which did not change. Only GeometricDet s
> are changed (rad. length, interaction length).

For my reference:
does this correspond to the same actual payload in the DB (and this is
just a symbolic tag),
or do we have an actual new payload with this identical content?
Please let me know.
Thank you.

**Comment by slava77** [comment]
On 6/22/17 3:08 AM, Marco Rovere wrote:
> Hi all,
> judging from the differences here and the one that I privately
> produced[1], I think we can safely deploy the original material tuning
> that @ianna <https://github.com/ianna> already integrated into this GT.

If I'm not mistaken,
the reason for the "revert" PR #19384
was that there was no difference or indication of a significant change
from applying this new reco material.

Marco,
could you please point me to some plot that show that something changes
and indicates an improvement
( and not just in the obvious plots like in /RecoMaterial RadLen_vs_Eta
plots).

Thank you.

**Comment by ianna** [comment]
@slava77 - it's a new payload with an identical content.

**Pull request closed without merging**
