### PR TITLE
74x: Additional features needed for P5 visualization

### PR DESCRIPTION
**Pull request by alja**

### CODE REVIEW

**Comment by alja** [comment]
#### Scaling of rechits per collection.
Screenshot: scaled EB rechits for factor of 5
screen shot 2015-05-13 at 1 19 34 pm

**Comment by alja** [comment]
#### Add option to draw ECal halo in 3D Tower view
towe-halo

**Comment by alja** [comment]
#### Stop autoplay events on 'Space' key

By the default Ctrl+Space switches mode of play space.
In live event display mode Space key can only stop playing of events. The Space key would else grab all Space events in collection filter editor and event filter editor.

**Comment by davidlange6** [comment]
@cmsbuild please test

**Comment by alja** [comment]
#### Partial save and load of configuration

Menu entry in 'File' category:
screen shot 2015-05-28 at 8 23 03 am

Can choose configuration entries after picking up input/output file. Here is an example of partial save:
screen shot 2015-05-28 at 8 24 18 am

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
Some combination of this package and debug symbols is making our patch release build die. For tonight, I'll revert this so the rest can go forward and then we'll merge this in tomorrow.

**Pull request merged**
