### PR TITLE
add plots of wire group and strip numbers for all chambers

### PR DESCRIPTION
**Pull request by rjwang**
add plots of wire group and strip numbers for all chambers, 
add back flag gangedME11a_ for Run2 LUT, which is deleted during last pull request
add back all deleted me11, me42 and csctflcts plots

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by rjwang** [comment]
the bug is fixed

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
