### PR TITLE
DD Store Lock

### PR DESCRIPTION
**Pull request by ianna**
* Lock the Stores when asked to do so
* Add a DDCompactView constructor which allows to unlock the Stores. 

Note: The only use case where the Stores need to be unlocked is the MagneticField geometry producer.

This is a new PR is based on https://github.com/cms-sw/cmssw/pull/24355 and addresses https://github.com/cms-sw/cmssw/pull/24355#discussion_r211944953

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
All the errors come from attempts to write in the locked stores:
---> test testRecoMETMETProducers had ERRORS
```
----- Begin Fatal Exception 23-Aug-2018 18:22:32 CEST-----------------------
An exception of category 'DetectorDescriptionStore' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
   [3] Using EventSetup component XMLIdealGeometryESProducer/'XMLFromDBSource' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
 Store has been locked. Illegal attempt to add cms:OCMS to a global store.
----- End Fatal Exception -------------------------------------------------
```

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
- The reco part is kind of technical
- Jenkins tests pass and show no difference

**Comment by kpedro88** [comment]
@ianna this needs to be rebased now

**Comment by ianna** [comment]
ok, will do it later today

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by ianna** [comment]
please test

**Comment by perrotta** [comment]
+1
- Just rebased since https://github.com/cms-sw/cmssw/pull/24378#issuecomment-416255287

**Comment by kpedro88** [comment]
+1

**Comment by Dr15Jones** [comment]
@ianna This change appears to have caught something in the IB: See
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc810/CMSSW_10_3_X_2018-08-30-2300/pyRelValMatrixLogs/run/11626.0_QCD_Pt_600_800_13+QCD_Pt_600_800_13TeV_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019/step3_QCD_Pt_600_800_13+QCD_Pt_600_800_13TeV_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019.log#/

which has
```
----- Begin Fatal Exception 31-Aug-2018 07:21:34 CEST-----------------------
An exception of category 'DetectorDescriptionStore' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module L1TMuonOverlapTrackProducer/'valOmtfDigis'
   [2] Using EventSetup component RPCGeometryESModule/'' to make data RPCGeometry/'' in record MuonGeometryRecord
   [3] Using EventSetup component XMLIdealGeometryESSource/'' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
 Store has been locked. Illegal attempt to add DdBlNa:DdBlNa418 to a global store.
----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
The same thing also happened in workflow 11625.0. It looks like it might be thread related, since that workflow has different exception messages for different platforms.

on slc7_amd64_gcc810
```
----- Begin Fatal Exception 31-Aug-2018 07:34:03 CEST-----------------------
An exception of category 'DetectorDescriptionStore' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module L1TMuonOverlapTrackProducer/'valOmtfDigis'
   [2] Using EventSetup component RPCGeometryESModule/'' to make data RPCGeometry/'' in record MuonGeometryRecord
   [3] Using EventSetup component XMLIdealGeometryESSource/'' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
 Store has been locked. Illegal attempt to add cms:OCMS to a global store.
----- End Fatal Exception -------------------------------------------------
```

on slc7_amd64_gcc700
```
----- Begin Fatal Exception 31-Aug-2018 08:04:46 CEST-----------------------
An exception of category 'DetectorDescriptionStore' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module CaloTowersAnalyzer/'AllCaloTowersDQMOffline'
   [2] Using EventSetup component HcalDDDRecConstantsESModule/'hcalDDDRecConstants' to make data HcalDDDRecConstants/'' in record HcalRecNumberingRecord
   [3] Using EventSetup component HcalParametersESModule/'hcalParameters' to make data HcalParameters/'' in record HcalParametersRcd
   [4] Using EventSetup component XMLIdealGeometryESSource/'' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
 Store has been locked. Illegal attempt to add cms:OCMS to a global store.
----- End Fatal Exception -------------------------------------------------
```

and on two others, the workflow ran fine.

**Comment by fabiocos** [comment]
@ianna @Dr15Jones indeed running wf 11626 in single threaded mode does not show any failure, while 24034 does it anyway. At this point, unless a fix is available by today, I would consider to temporarily revert this PR in view of having a working pre3, and let its fixed version enter afterwards

**Comment by ianna** [comment]
@Dr15Jones and @fabiocos - It's strange that the RPCGeometry (e.g. a reconstruction geometry) is built from a full XML geometry while it should be taken from a DB. I've observed a similar thing with a MagneticField producer on an IOV boundary: its record is taken from a DB if the processed events are in one IOV, but if there is another IOV, the MF is built from the DD (which causes the bad_alloc case due to a large number of the DDName pairs left over in its singleton map). 

Please, revert the PR.

**Pull request merged**
