### PR TITLE
Implement multi-processing in fastHadd to merge DQM histograms faster.

### PR DESCRIPTION
**Pull request by dmitrijus**
## Removed a few small optimizations:
- first file is no longer added to the set, but merged on top  of an empty set, just like any other file;
- removed dirnames, objnames, fullnames string caches;
- removed fullname from MicroME, since it can be generated using other fields;
- replaced 'custom' merge algorithm with std::set::insert (with hints).

As a result, the code is way more simplier and does not increase the
time it takes to merge.
## Implement multi-process merging in fastHadd.

A group of processes are organized in a virtual tree.

Each process has a unique node_id (1 - number_of_proc) and
will start (fork) 2*node_id + {0,1} processes (if new node_id <=
number_of_proc).

Each process will merge all files identified by (file_index % (node_id - 1) == 0),
plus all histograms from his child processes.
IPC is done via pipe()s.

This gives us somewhat good latency. With 7 processes this will
decrease the merging down 11s (see below).

I have tried using threads to merge faster, but this was futile.
Root just has too many global internal states.
And I couldn't serialize root access, since it takes the majority of time.

I've tried fastParallelHadd.py (changing various parameters),
but the lowest time I could get was ~26seconds.

All numbers were done using fastHadd to merge 100 files, summary:

```
- 50.321s, 227mb  -> old fastHadd with no changes
- 50.198s, 225mb  -> new fastHadd
- 18.719s, 550mb  -> new fastHadd, using 3 processes
- 11.143s, 1202mb -> new fastHadd, using 7 processes
```

Memory is sum of proportional set size (PSS).

I will make ports to 75 and 76 after and if this is accepted.

### CODE REVIEW

**Comment by deguio** [comment]
+1
I validated the content and I confirm 100% success in the following cases:
- standard fastHadd VS new version with 1 node
- standard fastHadd VS new version with 7 nodes

the performance are also confirmed.

@dmitrijus 
please submit to 75 and 76 as well.
thanks,
F.

**Comment by deguio** [comment]
hello @davidlange6 
can we have this one merged? this is used in the online world and to propagate it to the prod system we need to submit a PR to cmsdist as well.
ideally we would like to prepare the RPM and ask for its installation tomorrow.
thanks,
F.

**Comment by dmitrijus** [comment]
@diguida please watch it.

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@dmitrijus , this PR (though very old) had removed  DQMServices/Components/test/fastParallelHadd.py which is needed here https://github.com/cms-sw/cmssw/blob/master/DQMServices/Components/test/run_fastHadd_tests.sh#L115 

Can you please provide a fix for the and also @Dr15Jones noticed that run_fastHadd_tests.sh runs ```rm -fr *.root``` which deletes root files needed by other unittests. Can you please make sure that run_fastHadd_tests.sh create a sub-directory e.g.  runFastHadd and it creates/deletes file only under this sub-dir?

**Comment by dmitrijus** [comment]
@smuzaffar https://github.com/cms-sw/cmssw/pull/20385

**Comment by smuzaffar** [comment]
thanks @dmitrijus for quick fix

**Pull request merged**
