### PR TITLE
DQM: Reduce TH1 Usage

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

This PR includes a few cherry-picks from the "new DQMStore" branch that remove unnecessary calls to `getTH1` and friends. While there is no specific reason to do this now, `getTH1` is unsafe in general and will become illegal at some point (for certain situations, at least).

For now, this is just general cleanup of the DQM codebase.

Some new APIs in the `MonitorElement` are required for this, since those are present in #28092, it is included here. This PR should wait until #28092 is merged.

I excluded the changes regarding `SetCanExtend`, since I am not really sure if and where it is safe to remove these calls. This will need to be figured out later.

#### PR validation:
No changes expected.

### CODE REVIEW

**Comment by tlampen** [comment]
please test

**Comment by schneiml** [comment]
Rebased to remove the merge commit (from #28092).

**Comment by schneiml** [comment]
please test

no changes expected, nothing really dangerous in here.

**Comment by schneiml** [comment]
Not much in terms of changes apart from what looks like an instability in `HCAL/DigiTask`. I think I remember seeing that one before, is it unrelated? Either ways, looks like only numerical differences.

**Comment by schneiml** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

- Changes in AlCa domain are trivial
- Observed instability in `HCAL/DigiTask` comparisons an unrelated issue (#28367)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
@smuzaffar it looks like that the problem in the check between overlapping PRs is back again. #28092 was merged several days ago...
I see that the file in https://github.com/cms-sw/cms-prs/tree/master/cms-sw/cmssw/.other used for this test is now 12 days old, was the procedure updating it accidentally stopped?

**Comment by fabiocos** [comment]
@rekovic this PR looks ok to me, please have a look, I plan to integrate it in one of the next IBs

**Comment by smuzaffar** [comment]
@fabiocos , the PR files  cache should be updated now. The job was running due to a bug it was not pushing back the updates to github.

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar the failure in this PR is that previously reported by @civanch

**Comment by smuzaffar** [comment]
please test
@fabiocos , I have added a work around for PR tests to avoid this issue. I will check tomorrow how to fix this properly

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
