### PR TITLE
adding Pythia8 Filter for genparticles HT

### PR DESCRIPTION
**Pull request by alefisico**
Hi,

I need to include this filter for the generation of our signal. It only calculates the HT of generated particles from pythia8. I think for the actual generation I need it to be backported to 7_1_X ( the release that will actually be used) and  7_6_X as the release the output will be in.

Please let me know if you have any question.

### CODE REVIEW

**Comment by bendavid** [comment]
The filter is only needed in 80x and 71x  (you don't need it in 76x, since only the digi-reco will be done there)

If you only use the status 23 particles, then you will end up with ~exactly the same result as if you just applied the HT cuts at the madgraph level.

Instead I think what you will want to do is run the genparticle and genjet producers and then filter on the HT of the GenJet collection  (This is as close as you can get to reconstruction-level jets)

**Comment by alefisico** [comment]
Hi Josh, I cannot applied an HT cut at madgraph level since the quarks coming from the stops are not generated in madgraph but in pythia8. I tried to apply an HT cut in madgraph but it is applied only to the extra partons. That is the reason I have to use this filter after pythia8.

**Comment by bendavid** [comment]
Ah ok yes you're right.  If you do it like this then indeed the HT calculation will include the stop decay products.

So indeed what is here should be ok and does address the original issue.

On the other hand, since you already have to run pythia, you COULD do the filtering at genjet level, and this would be closer to the kinematics of the reconstructed jets.

Let me know if you want to try that or if you're happy with what you have here, in which case I'll just merge it.

**Comment by alefisico** [comment]
yes, we checked it with genJets.  You can see the plot here, where I am comparing the samples without extra partons, with extra partons and without this filter and with this filter, using AK4 genJets:
rawak4ht_all
basically, by applying this HT filter I think we are fine.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
