### PR TITLE
Fixed variable names in PFBlockAlgo to abide by CMS coding rules 

### PR DESCRIPTION
**Pull request by uhussain**

### CODE REVIEW

**Comment by uhussain** [comment]
@VinInn What are you referring to exactly?

**Comment by VinInn** [comment]
on your last commit... that changes unique in auto back...

**Comment by cvuosalo** [comment]
@uhussain, @slava77: I think Slava is right. We should use shared_ptr here, not unique_ptr. It looks to me like it should work.

One small issue is that the blocksNew_ member is never used at all as far as I can tell. I think it can just be deleted.

**Comment by VinInn** [comment]
```
transferBlocks() {return std::move(blocks_);}
```

if it is a transfer please transfer. do not share

**Comment by cvuosalo** [comment]
@uhussain, @VinInn, @slava77: I think Vincenzo is correct here. If we use unique_ptr and std::move, it should work the same way as the auto_ptr version was working.
It looks like RecoParticleFlow/PFProducer/plugins/PFBlockProducer.cc will also need to be changed. Its last line should become (after deleting the unneeded variable):
```
iEvent.put(std::move(pfBlockAlgo_.transferBlocks()));
```

**Comment by uhussain** [comment]
@cvuosalo  and @VinInn . Thanks for the suggestions, i think the issue is resolved now.

**Comment by slava77** [comment]
On 8/1/16 10:01 AM, Carl Vuosalo wrote:
> @uhussain <https://github.com/uhussain>, @VinInn
> <https://github.com/VinInn>, @slava77 <https://github.com/slava77>: I
> think Vincenzo is correct here. If we use unique_ptr and std::move, it
> should work the same way as the auto_ptr version was working.


I didn't look at use cases.
If you see that the pointer is passed with intent to hand over the
ownership, then use unique and move.

**Comment by cvuosalo** [comment]
@uhussain: Remember to change the PR title for the new file. Or just make the title less specific: "Fixed variable names in PFBlockAlgo to abide by..."
In general, it is probably not a good idea to list the files changed in a PR title, since the file list might change as you're working on it, and then you have to keep updating the title. A general description of the module or package the PR is changing is usually better.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15334 c43805685b3d28d2a4a340e0daf35d9d48ac7daa

Fix variable naming violations and convert deprecated auto_ptr to unique_ptr in PFBlockAlgo. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-01-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
