### PR TITLE
Python3 syntax upgrade

### PR DESCRIPTION
**Pull request by conetthuerta**
#### PR description:

~/CMSSW_12_2_X_2021-11-17-1100/src/Validation/Geometry/test/MaterialBudget.py is updated;
  - Syntax is upgraded from Python2 to Python3, this is necessary as per the migration to Python3 (MaterialBudget.py will not run without these changes in some versions of CMSSW_12).
  - No dependency on any other PR's or externals.
  - https://www.python.org/download/releases/3.0/

#### PR validation:

Tracker Material Budget Validation was run with CMSSW_12_2_X_2021-11-17-1100 (https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackerMaterialBudgetValidation - TWiki needs to be updated), "Validation plots: single geometry configuration" were produced (.png and .pdf files that illustrate the tracker material budget, measured in fractional radiation lengths x or hadronic interaction lengths l, plotted as a function of eta, or phi, or R, or eta and phi, etc.).
  - "Validation plots: single geometry configuration" cannot be produced when MaterialBudget.py is run in Python2 syntax in some versions of CMSSW_12 - upgrading to Python3 syntax is necessary.
  - Relevant TWiki page (needs to be updated): https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackerMaterialBudgetValidation

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@conetthuerta What updates need to be made to the TrackerMaterialBudgetValidation twiki? Could you make those updates?

**Comment by conetthuerta** [comment]
@cvuosalo instructions available on TrackerMaterialBudgetValidation TWiki will be updated to work post SLC6-CC7 migration (for CMS-SW10 and CMS-SW12).
The Catholic University of America (CUA) is going through the motions to have these updates up on TWiki ASAP.

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
