### PR TITLE
[13_2_X] EMTF add DQM plots for unconstrained pT and dxy

### PR DESCRIPTION
**Pull request by elledesa**
PR description:
This PR adds DQM plots using unconstrained pT and dxy. These plots will be useful for monitoring now that the neural network is working at P5.

This is a backport of [#42155](https://github.com/cms-sw/cmssw/pull/42155)

PR validation:
Validated by `runTheMatrix.py -l limited -i all --ibeos` and everything looks good.

If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: @eyigitba

### CODE REVIEW

**Comment by mmusich** [comment]
-hlt

@lutuck it looks like this PR was addressed to the wrong branch. The title says [13_2_X] but the selected milestone is 13.3.X. 
Please check .

**Comment by syuvivida** [comment]
Hi @lutuck does this PR affect offline L1T DQM?

**Comment by eyigitba** [comment]
Hi @syuvivida , this doesn't affect offline L1T DQM, and it's not urgent at all. It can go in whenever it's easier/safer for everybody.

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
backport of #42155

**Comment by tjavaid** [comment]
type l1t

**Comment by tjavaid** [comment]
+1

- P5 tests okay ([link](http://cmsonline.cern.ch/cms-elog/1197544)).

**Comment by rappoccio** [comment]
+1

**Pull request merged**
