### PR TITLE
Updates RelVal scripts

### PR DESCRIPTION
**Pull request by hengne**
1.) fixed missing letters in gen-sim recycle dataset names for workflows 1352,1353,1354
2.) update HI GEN-SIM recycle to CMSSW_7_5_0_pre4-MCHI2_75_V0-v1

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by hengne** [comment]
Re-based to the head, and updated the fullSim premixing input samples.
@franzoni Please test again, thanks!

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
