### PR TITLE
B2G HLT DQM for 93x, part 2

### PR DESCRIPTION
**Pull request by rappoccio**
Here are the promised updates for the B2G HLT DQM, after the previous monitors were integrated. This adds the single jet plus mass triggers and the e+jet boosted top trigger. 

@alefisico @UBParker

### CODE REVIEW

**Comment by alefisico** [comment]
thanks @rappoccio, including @lbenato in the loop

**Comment by davidlange6** [comment]
please test

**Comment by rappoccio** [comment]
@mtosi is should be good to go for these B2G triggers.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
