### PR TITLE
Global tags for Run 2 UL reprocessing [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a backport of PR #28524. 

The GT differences between the 10_6_X GTs and the corresponding 11_0_X GTs consist entirely of tau ID payloads (which are not taken from a GT in 10_6_X) and three obsolete pixel payloads.

**GT diffs with respect to GTs in version of autoCond in master**

**2016 pp collision MC**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_v5/106X_mcRun2_asymptotic_v8 

**2016 pp collision MC for "pre-VFP" era (new autoCond key)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_preVFP_v1/106X_mcRun2_asymptotic_preVFP_v1

**2016 cosmic MC**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2cosmics_startup_deco_v4/106X_mcRun2cosmics_startup_deco_v5

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v9/106X_dataRun2_v25
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_v9/106X_dataRun2_relval_v23

**Prompt-like data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HEfail_v9/106X_dataRun2_PromptLike_HEfail_v13
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_v9/106X_dataRun2_PromptLike_v14
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HI_v9/106X_dataRun2_PromptLike_HI_v14

**2018 cosmic GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018cosmics_realistic_deco_v5/106X_upgrade2018cosmics_realistic_deco_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018cosmics_realistic_peak_v6/106X_upgrade2018cosmics_realistic_peak_v9

#### PR validation:

The PR validation is described in the introduction to PR #28524.

#### if this PR is a backport please specify the original PR:

This PR is a backport of PR #28524.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test workflow 7.2,7.4,7.21,7.22

**Comment by christopheralanwest** [comment]
please test workflow 7.2,7.4,7.21,7.22

I had accidentally created a GT `106X_dataRun2_relval_23` (no "v") rather than `106X_dataRun2_relval_v23`. I created the appropriate GT and so the tests should now run without any changes to the PR.

**Comment by christopheralanwest** [comment]
please test workflow 7.2,7.4,7.21,7.22

I'm not sure why the global tag `106X_dataRun2_relval_v23` was not found in the latest round of tests. Some sort of caching issue? In any case, the tests run successfully locally.

**Comment by christopheralanwest** [comment]
+1

PR #28512 should be merged prior to this PR and I will resolve the conflict by preferring the changes in this PR.

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 7.2,7.4,7.21,7.22

**Comment by fabiocos** [comment]
@christopheralanwest I have merged #28512 after the approval of @slava77 and solved the conflict in favour of the proposal in this PR, as mentioned in https://github.com/cms-sw/cmssw/pull/28577#issuecomment-562890876 please verify. This is the last missing bit to start building 10_6_7 https://github.com/cms-sw/cmssw/issues/28582

@kpedro88 @chayanit I consider your previous signatures as valid

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@christopheralanwest please verify, as far as I can see this PR should correspond to what intended

**Comment by fabiocos** [comment]
merge

**Comment by christopheralanwest** [comment]
> @christopheralanwest please verify, as far as I can see this PR should correspond to what intended

Yes, it is. Thanks.

**Comment by christopheralanwest** [comment]
+1

**Comment by chayanit** [comment]
@christopheralanwest , do I understand correctly that the GTs in this PR for UL2016 somehow outdated already?
preVFP : 106X_mcRun2_asymptotic_preVFP_v3
postVFP : 106X_mcRun2_asymptotic_v9

**Comment by christopheralanwest** [comment]
> @christopheralanwest , do I understand correctly that the GTs in this PR for UL2016 somehow outdated already?
> Should the most update be?
> preVFP : 106X_mcRun2_asymptotic_preVFP_v3
> postVFP : 106X_mcRun2_asymptotic_v9

Yes, that's correct. I will create a backport PR once I have a clear idea what the corresponding GT updates in master will look like (probably later today).

**Pull request merged**
