### PR TITLE
By-pass scalers input collection for `hltScalersRawToDigi` for Heavy Ions pp-reco workflows post merge of #41815

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, address https://github.com/cms-sw/cmssw/pull/41815#issuecomment-1606825744. Done similarly as previously done for `siStripDigisHLT` collection.

#### PR validation:

```
runTheMatrix.py -l 159.02,159.03,160.02,160.03
```

runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

Cc: @Ksavva1021

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflows = 159.02,159.03,160.02,160.03

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- Workflows failing in the IB succeed with this PR
- @cms-sw/pdmv-l2 while we merge it to fix the IBs, feel free to suggest and provide a different fix if you think this is not the correct one

**Comment by perrotta** [comment]
merge

**Pull request merged**
