### PR TITLE
decoupling NANO V10 and V11 [WIP]

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

This is work in progress, but I'd like to have initial feedback on some of the changes in ConfigBuilder.

The aim with this changes is to be able to support both V10 and V11(in development) in 12.6, in a sustainable way.
The current process is to add whatever NANO feature to master/12.6 for V11, and "remove it" by customisation "back to" V10 ; which obviously is extremely error prone.

The proposal here is copying most configuration under the V10 directory to avoid touching it while putting new features in V11 (master) ; there are however, it seems some dependencies still to be removed in this initial PR. We might have to dump some of the module configs in V10 directory to fully decouple.

#### PR validation:

for NANO, these commands run and produce runable configurations
for the V11 configuration `cmsDriver.py nanoMaster --step NANO --datatier NANOAOD --eventcontent NANOAOD --conditions 124X_dataRun3_Prompt_v4 --era Run3 --no_exec --data --filein "file:86c32527-92dd-4ec9-9e72-aba8878ab893.root" --fileout nanoMaster.root -n 100` 

for the V10 configuration `cmsDriver.py nanoV10 --step NANO:PhysicsTools/NanoAOD/V10/nano_cff --datatier NANOAOD --eventcontent NANOAOD --conditions 124X_dataRun3_Prompt_v4 --era Run3 --no_exec --data --filein "file:86c32527-92dd-4ec9-9e72-aba8878ab893.root" --fileout nanoV10.root -n 100 `

ConfigBuilder was tested with `runTheMatrix.py -l limited -j 0` that managed to configure all 50 workflows steps (except for dad queries) ; that indicates that I have not majorly broken cmsDriver

EDITS (30/9/22): 
The change in ConfigBuilder is done to allow `STEP:<a specific path to configuration>` without having to specify the actual Sequence to be used, and hence pick up the default ones defined in ConfigBuilder.
The new ERA is not mandatory in this PR, but will be later on #39452 and fits well in here.

### CODE REVIEW

**Comment by vlimant** [comment]
I might use #39342 to further cleanup the V10 configuration as part of the decoupling

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
@cms-sw/orp-l2 : I'd like to move this passed the WIP ; can this be considered for merging ?

**Comment by vlimant** [comment]
@mbluj can you please confirm I got the tau modifier right ?

**Comment by vlimant** [comment]
+1 
based on a full comparison based on lumis 8:19, 32:37, 81:85, 98:104, 237:243 of run 357734, comparing the promptNANO `/store/data/Run2022D/MuonEG/NANOAOD/PromptNanoAODv10-v1/2530000/a18c1abb-92a9-4f00-84c1-705f079bcb0a.root`  and a V10-like NANO output derived from `/store/data/Run2022D/MuonEG/MINIAOD/PromptReco-v2/000/357/734/00000/0aa9e6be-b262-4d70-a1b9-5be446c36bc0.root` and the configuration `cmsDriver.py nanoV10_124 --step NANO:PhysicsTools/NanoAOD/V10/nano_cff --datatier NANOAOD --eventcontent NANOAOD --conditions 124X_dataRun3_Prompt_v4 --era Run3,run3_nanoAOD_124 --no_exec --data --filein /store/data/Run2022D/MuonEG/MINIAOD/PromptReco-v2/000/357/734/00000/0aa9e6be-b262-4d70-a1b9-5be446c36bc0.root --fileout nanoMaster.root -n 100`
no difference were spotted

**Comment by perrotta** [comment]
urgent

**Comment by vlimant** [comment]
@forthommel : can you please take a look at https://github.com/cms-sw/cmssw/pull/39337/files#diff-fb6444724d4815cbb3a9591c8cd8a29c5bf1d306eb7cccf8f990ad01278a9af0 configuration-wise ?

**Comment by vlimant** [comment]
here an in the description:
The change in ConfigBuilder is done to allow `STEP:<a specific path to configuration>` without having to specify the actual Sequence to be used, and hence pick up the default ones defined in ConfigBuilder.
The new ERA is not mandatory in this PR, but will be later on #39452 and fits well in here.

**Comment by vlimant** [comment]
question for @cms-sw/orp-l2 : should I remove all other "NANO from MINI" dedicated workflows (not the ones in regular workflows) that are totally superseded by this set ?
that is : 
136.7722
136.7952
136.8521
136.8522
136.8523
1325.6
1325.7
1325.8
1325.61
1325.81
1329.1

I am actually wondering what is the purpose of those, and how often are they ran

**Comment by perrotta** [comment]
> question for @cms-sw/orp-l2 : should I remove all other "NANO from MINI" dedicated workflows (not the ones in regular workflows) that are totally superseded by this set ?

@vlimant this is not a question for ORP. The actual usefulness of those workflows must be assessed by XPOG (i.e. you...), and the implementation is normally dealt with by @cms-sw/pdmv-l2 

For what I am concerned, if those workflows are really outdated and cannot test nothing relevant for the nanoAOD production mechanism in addition to the new ones, they should be better removed.

**Comment by vlimant** [comment]
thanks @perrotta. My eyes crossed and meant to post this question in #39472 ; my apologies

**Comment by vlimant** [comment]
content-wise there will be no more modification to this PR from my end, unless people have feedback on the code itself

**Comment by vlimant** [comment]
any further comment from @cms-sw/operations-l2 ?

**Review by perrotta — COMMENTED** [review]
The comments I have are only in favor of implementing as much as possible a safer syntax for cloned or modified objects, which is even more usefol for these "far from simple" configurations

**Comment by perrotta** [comment]
assign core

@cms-sw/core-l2 can I ask you to review the changes in Configuration/Applications/python/ConfigBuilder.py?
(Please feel free to unassign yourself if you don't think that this is something that should end up in your expertise)

**Comment by vlimant** [comment]
> The comments I have are only in favor of implementing as much as possible a safer syntax for cloned or modified objects, which is even more usefol for these "far from simple" configurations

thanks @perrotta ! The recommendation, if I follow correctly is to not specify the type again during cloning but leave the default type to accept the modification. I will try to catch and modify as many as I can here, but might fit better in a subsequent PR that will also simplify some of the Modifier statements in the nano configuration

**Comment by makortel** [comment]
unassign core

> (Please feel free to unassign yourself if you don't think that this is something that should end up in your expertise)

The changes in `ConfigBuilder` go beyond to what `core` could reasonably review (would require a deep dive in how `ConfigBuilder` really works). On a cursory look I did not see any obvious problems or potential problems.

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by perrotta** [comment]
@rappoccio you have merged after the latest commit could be tested: it is a simple commented out line, but still we should have followed the usual procedure and let the test run...

By the way @smuzaffar why bot merged this even if it was still in the status "test started" right before https://github.com/cms-sw/cmssw/pull/39337#issuecomment-1267235718 ?

**Comment by perrotta** [comment]
@vlimant are the differences in the jet dqm plots understood?

I think this PR was merged a bit too hastily: I'm preparing a revert PR, to have it ready just in case we are not yet fully convinced by tomorrow, when we'll cut 12_6_0_pre3

**Comment by smuzaffar** [comment]
> By the way @smuzaffar why bot merged this even if it was still in the status "test started" right before https://github.com/cms-sw/cmssw/pull/39337#issuecomment-1267235718 ?

`@rappoccio merged commit aa85daa) into cms-sw:master 13 hours ago`

looks like @rappoccio  merged it instead of bot :-)

**Comment by vlimant** [comment]
11634.15 was not part of the CI tests it seems. It using the customize function for V10 that this PR is getting rid of.

**Pull request merged**
