### PR TITLE
Reorganization of MTD Validation plugins

### PR DESCRIPTION
**Pull request by gsorrentino18**
#### PR description:

The validation of the BTL RecHits and the validation of BTL reco clusters have been merged in a single plugin. The same operation has been performed for the ETL. The validation of BTL and ETL cluster-track association and primary vertex time has been merged in a single plugin  (@pmeridian @parbol).

#### PR validation:

The new code has been tested in the release CMSSW_11_1_X_2020-03-22-2300. The size of the new histograms on disk is:
481.31 KiB       MTD/ETL
237.54 KiB       MTD/BTL
compared with the previous size:
569.70 KiB       MTD/ETL
283.18 KiB       MTD/BTL

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@gsorrentino18  it seems to me that the added plots are all OK but if you could confirm:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-03-23-1100+f75a11/35598/dqm-histo-comparison-summary.html
Thank you

**Comment by civanch** [comment]
+1

**Comment by gsorrentino18** [comment]
@jfernan2 the plots are OK. Thanks.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
