### PR TITLE
New fastsim geometry - backport to 94X

### PR DESCRIPTION
**Pull request by ssekmen**
Backport of the new FastSim geometry/particle propagator and later corrections to 94X:
- PR #20666 : New fastsim geometry reb
- PR #22311 : Fix after urgent message from validation campaign 
- PR #22459 : Fix for observed muon efficiency loss in new FastSim geometry 
- PR #23174 : fixes in assignment of SimTracks/SimVertices
Also added:
- PR #21268 : Include PSet which is referenced via refToPSet_
- PR #24210 : Fixed memory leak in TrackerSimHitProducer

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by kpedro88** [comment]
backport of #20666

**Comment by ssekmen** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
There are changes in `PixelPhase1V/TrackingParticle` for (FullSim) workflows 10024.0, 10224.0, 10824.0 (2017/2018 Era). Is this expected?

**Comment by ssekmen** [comment]
As far as I see all code changes outside the FastSimulation area are are also related to FastSim, so I would not expect a change in the FullSim workflows.

**Comment by slava77** [comment]
```PixelPhase1V/TrackingParticle``` change randomly in every test in 94X

**Comment by kpedro88** [comment]
ah, great.

I noticed another issue: #21267 has reappeared in the IB after merging the first two FastSim backports. @ssekmen can you backport the fix #21268?

**Comment by ssekmen** [comment]
@kpedro88 , I also added #24210 , a recent PR from @skurz that fixed a memory leak in TrackerSimHitProducer .

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by ssekmen** [comment]
urgent

**Comment by perrotta** [comment]
+1
- Correct backport of the pull requests listed in the description
- Jenkins tests pass: differences observed in FastSim muons in wf 5.1 may correspond to what was integrated in the master with #22459 (fix for muon efficiency loss in new FastSim geometry), e.g.:
image

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by ssekmen** [comment]
@fabiocos , if I am reading the above information correctly, this problem happens because we are using a minbias sample with a different FastSim data format.  Following the link in your message, I see that an example cmsDriver command is as follows:

cmsDriver.py ZEE_13TeV_TuneCUETP8M1_cfi  --conditions auto:run2_mc --pileup_input das:/RelValMinBiasFS_13_ForMixing/CMSSW_9_4_0_pre3-94X_mcRun2_asymptotic_v0_FastSim-v1/GEN-SIM-RECO --fast  -n 10 --era Run2_2016 --eventcontent FEVTDEBUGHLT,DQM --relval 100000,500 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,VALIDATION:@standardValidation,DQM:@standardDQM --beamspot Realistic50ns13TeVCollision --datatier GEN-SIM-DIGI-RECO,DQMIO --pileup AVE_35_BX_25ns  --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --prefix '/build/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 7200 '  --fileout file:step1.root  --suffix "-j JobReport1.xml "  --nThreads 4 > step1_ZEE_13+FS_ZEE_13_UP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS.log  2>&1

The minbias file here should have the data formats of the old fastsim framework.  Running with a new minbias file should make the issue disappear.

**Comment by fabiocos** [comment]
@ssekmen thank you for the feedback. @prebello,@zhenhu we need to fix the input relvals. In order to do this I assume that you need anyway a new release to produce new MinBias, right?

**Pull request merged**
