### PR TITLE
Ecal DB PayloadInspector with one or two tags

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:

New features in DB PayloadInspector to compare IOVs in 2 different tags

#### PR validation:

Tests done in command line with getPayloadData.py, plots (png) correctly produced

### CODE REVIEW

**Comment by depasse** [comment]
Must I do stgh ? 
In the past, I reeived a message "A new Pull Request was created by @depasse for master.
It involves the following packages:...etc..."   Maybe it does not exist any more..
Thanks.

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
ping bot

**Comment by silviodonato** [comment]
@smuzaffar something weird is happening with @cmsbuild

**Comment by smuzaffar** [comment]
as code-checks were already run so looks like bot is confused about the explicit code-checks command. Anyway I have ran the code-checks by hand in jenkins.

**Comment by silviodonato** [comment]
please test
kind reminder @ggovi

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
