### PR TITLE
Phase2-hgx297C Safer syntax fr modifying configuration parameters in some of the cfi's in Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Safer syntax fr modifying configuration parameters in some of the cfi's in Geometry/HGCalCommonData

#### PR validation:

Use cfg's in Geometry/HGCalCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Comparison differences are not related to this PR.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by qliphy** [comment]
please test
just to double check the diffs

**Comment by perrotta** [comment]
+1

**Pull request merged**
