### PR TITLE
upgrade AMPT to v2.25t5

### PR DESCRIPTION
**Pull request by kurtejung**
75x extension to PRs #11701 (76x) and #11932 (80x)

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@kurtejung - are the issues brought up with #11932 addressed in a different pr?

**Comment by kurtejung** [comment]
@davidlange6 - no not yet - these will need to be addressed very carefully
since they involve directly toying with AMPT's base code.  I will create
another PR to address these concerns in the next few days (hopefully by the
end of the weekend)

**Comment by davidlange6** [comment]
ok - thanks - we can backport once they are fixed.

**Comment by kurtejung** [comment]
added new PR to address compiler warnings: #12323

**Comment by kurtejung** [comment]
not sure if my comments on github show up when i reply directly - in any
case, the compiler warnings have been addressed

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Pull request merged**
