### PR TITLE
Fix to findAndChange for the new All-in-one [13.2.x]

### PR DESCRIPTION
**Pull request by amecca**
#### PR description:

This is a small fix addressing issues with a global configuration for a new All-in-one validation tool:
-  fix on the findAndChange macro to recognize all protocols in a search path,
-  automated parsing of the ROOT colors to the integer values,
-  fix on the problem with a decimals in the plot's right-corner label (e.g. 13.6 TeV)

#### PR validation:
Run the package tests:
`scram b runtests use-ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [#42608](https://github.com/cms-sw/cmssw/pull/42608)

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by amecca** [comment]
backport 42608

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42608

**Comment by amecca** [comment]
backport https://github.com/cms-sw/cmssw/pull/42608

**Comment by perrotta** [comment]
+1

**Pull request merged**
