### PR TITLE
Run3-gex112Y Make the default creation of Simhits for Demo chambers to be true as required by the respective DPG's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make the default creation of Simhits for Demo chambers to be true as required by the respective DPG's

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
urgent

**Comment by perrotta** [comment]
@cmsbuild please test with #36654,#36679,#36766,#36765

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Merging together #36679 #36654 #36750 #36765 #36766 for pre4

**Comment by perrotta** [comment]
merge

**Pull request merged**
