### PR TITLE
[126X] Save iEta/iPhi & iX/iY indices of ECAL crystals in nanoAOD

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/40327
Needed for upcoming 12_6_X renano, so that users can veto EE+ leak region with some margin using seed iX, iY indices.

### CODE REVIEW

**Comment by swagata87** [comment]
enable nano

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by swagata87** [comment]
type egamma

**Comment by swertz** [comment]
+1

Verbatim backport of https://github.com/cms-sw/cmssw/pull/40327

**Comment by perrotta** [comment]
+1

**Pull request merged**
