### PR TITLE
quiet noisy module : hltBtagTriggerSelection  

### PR DESCRIPTION
**Pull request by davidlange6**
somehow printing 100s of lines per event. Experts please have a look

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
i forgot the corresponding harvesting step module.

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
@natalia-korneeva 
is it possible that this code was pretty noisy when we had a meaningless HLT menu in the release,
but now that we have --finally-- the 2017 HLT menu in the release,
this code becomes quite again ?

can you please
1. test that this is indeed the case
2. make sure the code will not be noisy if Fake menu will be run 
(in the meantime, I'll try to coordinate w/ PdmV @fabozzi to have dedicated sequences)
3. prepare a PR for re-enabling your VALIDATION code in both 93x and 92x

@davidlange6, do you agree ?

thanks
(let me stress that this should be done asap)

**Comment by natalia-korneeva** [comment]
@mtosi 
yes it is possible.
Will do the tests and then prepare a corresponding PR.

**Pull request merged**
