### PR TITLE
Run3-alca167 Update the analyzer to study low luminosity collision data

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the analyzer to study low luminosity collision data

#### PR validation:

Tested using cfg files in the test/python directory of Calibration/IsolatedParticles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by silviodonato** [comment]
Do you have any comments @pohsun @tlampen @tocheng @christopheralanwest?

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
