### PR TITLE
Allow chaining of Modifier toModify() and toReplaceWith() calls

### LINKED ISSUE #39335: chaining toReplaceWith
I was wondering if there is a major issue with allowing

`(Modifier_A | Modifier_B).toReplaceWith(something, something_else).toReplaceWith(something_dfiferent, something_else_different)`

instead of

`(Modifier_A | Modifier_B).toReplaceWith(something, something_else)
(Modifier_A | Modifier_B).toReplaceWith(something_dfiferent, something_else_different)`

and for other modifier functions

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/39335

#### PR validation:

Framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
seems good to me

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
