### PR TITLE
 Compute/store unprefirable event information by default in MINIAOD

### PR DESCRIPTION
**Pull request by lathomas**
Backport of https://github.com/cms-sw/cmssw/pull/39169 for 12_5.

The information about unprefirable events was only stored for Run 2 UL reprocessing.
It is however needed also for future data taking.
This PR stores this by default.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by rappoccio** [comment]
+1

**Pull request merged**
