### PR TITLE
Add DQM module to make uGT data/emulator comparisons

### PR DESCRIPTION
**Pull request by apana**
New DQM module to make uGT data/emulator comparisons. Also add option to use prescale column from unpacked GlobalAlgBlk in emulator

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
Is this a backport? Why does it target 10_1_X and not master?

**Comment by thomreis** [comment]
backport of #22907 

@dmitrijus yes it's a backport. The label was missing.

**Comment by kpedro88** [comment]
-1
wrong branch or something
follow http://cms-sw.github.io/tutorial-resolve-conflicts.html to make backports or rebase PRs

**Comment by perrotta** [comment]
-1

**Comment by Martin-Grunewald** [comment]
-1

**Comment by ianna** [comment]
-1

**Pull request closed without merging**
