### PR TITLE
Add UL18 V5 jet energy corrections + V2 jet resolution

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR add UL18 V5 jet energy corrections + V2 jet resolution to 2018 and 2021 realistic MC as well as to the corresponding IOVs of the data GTs. Validation slides can be found at https://github.com/cms-jet/JECDatabase/blob/master/PDF/Summer19UL18_V5/Validation_Summer19UL18_V5_JEC.pdf.

The GT diffs are as follows:

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_v5/112X_dataRun2_v6

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HEfail_v5/112X_dataRun2_HEfail_v6

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_relval_v5/112X_dataRun2_relval_v6

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_v4/112X_upgrade2018_realistic_v5

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HEfail_v4/112X_upgrade2018_realistic_HEfail_v5

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_deco_v4/112X_upgrade2018cosmics_realistic_deco_v5

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_peak_v4/112X_upgrade2018cosmics_realistic_peak_v5

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v11/112X_mcRun3_2021_realistic_v12

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v11/112X_mcRun3_2021cosmics_realistic_deco_v12

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v11/112X_mcRun3_2023_realistic_v12

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v11/112X_mcRun3_2024_realistic_v12

#### PR validation:

See the validation slides at https://github.com/cms-jet/JECDatabase/blob/master/PDF/Summer19UL18_V5/Validation_Summer19UL18_V5_JEC.pdf.

Also, a technical test was performed: `runTheMatrix.py -l limited,11024.2,7.4,7.23,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but it will be backported to 10_6_X for the re-miniAOD.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 11024.2,7.4,7.23,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The changes in the comparison tests look as expected to me: small changes in jet-related quantities only in 2018 data, 2018 MC and Run 3 MC. I've asked JEC experts in a private email to cross-check that everything looks OK in this PR prior to signing off on it and its backport PR #32170.

@lathomas @kirschen @juska

**Comment by bhoh** [comment]
> The changes in the comparison tests look as expected to me: small changes in jet-related quantities only in 2018 data, 2018 MC and Run 3 MC. I've asked JEC experts in a private email to cross-check that everything looks OK in this PR prior to signing off on it and its backport PR #32170.
> 
> @lathomas @kirschen @juska

label, tags names and queues looks OK.

**Comment by christopheralanwest** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
