### PR TITLE
New PF iso recomputation from miniAOD & Electron validation preshower histos 80X V1

### PR DESCRIPTION
**Pull request by archiron**
Portability of the validated PR15343 and 14412 from 81X to 80X.
Adding histograms to check the reproductibility of the PF isolation recomputation from miniAOD.

These are included in file ElectronMcMiniAODSignalValidator.cc (h) and in file ElectronMcSignalValidatorMiniAOD_cfi.py and in a new file ElectronIsolation_cfi.py which is taken into account in electronValidationSequenceMiniAOD_cff.py

The quantity superCluster()->preshowerEnergy() / superCluster()->rawEnergy() is used in the electron ID and tracking changes would be useful.

This new histo was added for validation in the case of endcaps only.
The files used for this implementation are :
Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc (h)
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc (h)

The files : Validation/RecoEgamma/test/ElectronMcSignalHistos.txt and Validation/RecoEgamma/test/ElectronMcFakeHistos.txt are used for web page creation and include the new histo.

Others minors correction (Validation/RecoEgamma/test)  are made to create these histos into the web page :
Validation/RecoEgamma/test/ElectronMcFakePostValidation_cfg.py
Validation/RecoEgamma/test/ElectronMcFakeValidation_gedGsfElectrons_cfg.py
in which a small Global Tag use is corrected
Validation/RecoEgamma/test/electronCompare.C
for these file, there is a small correction in web page creation due to gcc530.

@beaudett @matteosan1 @fcouderc

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1
Related PRs in 81x: https://github.com/cms-sw/cmssw/pull/15343 and https://github.com/cms-sw/cmssw/pull/14412

**Comment by archiron** [comment]
Please can you tell me why commits are unmerged ?

**Comment by davidlange6** [comment]
Its old and has merge conflicts (and DQM has not brought it up in a release meeting as something needed)

Auto-merging Validation/RecoEgamma/test/OvalFile
CONFLICT (content): Merge conflict in Validation/RecoEgamma/test/OvalFile
Automatic merge failed; fix conflicts and then commit the result.

**Comment by archiron** [comment]
OK thanks.
OvaFile is not a critical file (it is used only for local dev) and it may not be updated.
I will try to make another PR later.

**Pull request closed without merging**
