### PR TITLE
Update of HLT menu (102X)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR update the HLT menu to Lerici (V2).
Since it uses L1 V1_0_0, we need a new global tag

101X backport: #23079

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by silviodonato** [comment]
The tests will crash because it needs L1 menu V1_0_0 but we have V0_0_1 in the GlobalTag.
I'll ask AlCa to upload a new GT simultaneously with this PR.

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by silviodonato** [comment]
We need a new GT/L1Menu to integrate this PR (tests will fail because of wrong L1 menu).
I asked AlCa to add this PR in the next GT update.

**Comment by arunhep** [comment]
@silviodonato @Martin-Grunewald 
this commit https://github.com/cms-sw/cmssw/commit/7e216ba29d59b72b1d04fdc07984501129d1ca9a should suffice for this PR.

**Comment by Martin-Grunewald** [comment]
Thanks @arunhep

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_10_2_X_2018-05-08-2300 as to apply on top the new GT commit from @arunhep

**Comment by silviodonato** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
