### PR TITLE
Mask old b-taggers and keep only DNN taggers with Era modifier for run3.

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Regarding the AlCa issue #58 (https://github.com/cms-AlCaDB/AlCaTools/issues/58),  old b-tagging GT records are request to be removed (starting) from 12_1_X (and so on). Due to the dependency on "BTauGenericMVAJetTagComputerRcd" and "JetTagComputerRecord", the corresponding b-tagging computers need to be masked in run3. As DNN taggers will be the only supported ones in run3, this PR masks the old taggers with Era modifier and keeps only DNN taggers like DeepCSV and particleNet. (track counting and jet probability are kept for reference as requested)

#### PR validation:

PR tested in local with runTheMatrix.py processes. However, the standard run 2 validation sequences will fail due to missing b-tagger objects.

This PR is for run 3. Not a backport and no backport planed.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by AlexDeMoor** [comment]
Hi @yuanchao , what about JP and DeepJet ? 
Those taggers are still used by the BTV group. DeepJet is still the sota model and will be kept at the beginning of Run3  and JP is used for calibration

**Comment by yuanchao** [comment]
@AlexDeMoor Thank you very much for the comment. Originally I was told that DNN taggers will be the only supported ones in Run 3. Surely I can add back the JP tagger in the era modifier. As to DeepJet, it's not in the original RecoBTag_cff.py configuration file. This PR doesn't touch that.

**Comment by yuanchao** [comment]
@AlexDeMoor One more thing. Does JP depend on "JetTagComputerRecord" GT?

**Comment by AlexDeMoor** [comment]
Thank you for the information @yuanchao . Kindly ping @soureek and @johnalison . Do you have the answer about the GT ("Does JP depend on "JetTagComputerRecord" GT?")

**Comment by soureek** [comment]
> @AlexDeMoor One more thing. Does JP depend on "JetTagComputerRecord" GT?


As mentioned by Daniel Bloch in the email thread, we don't require this.

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/40043

**Comment by tvami** [comment]
@yuanchao did we expect this to work when tested together with https://github.com/cms-sw/cmssw/pull/40043 ?

**Comment by yuanchao** [comment]
@tvami it should be done with #40043 and #40058 .

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/40043 and https://github.com/cms-sw/cmssw/pull/40058

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-sw/cmssw/pull/40043,https://github.com/cms-sw/cmssw/pull/40058

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
> @tvami it should be done with #40043 and #40058 .

so it seems that didnt work either @yuanchao

**Comment by yuanchao** [comment]
@tvami I missed the patMuon part. ( #40100 )

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-sw/cmssw/pull/40043, https://github.com/cms-sw/cmssw/pull/40058, https://github.com/cms-sw/cmssw/pull/40100

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * changes are in BTV related folders which is expected

**Comment by AlexDeMoor** [comment]
After looking at the last test (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3763cc/29114/summary.html), it seems we have a lot of failings coming from the BTV HLT. I kindly ping @johnalison , @NiclasEich and @marco-link for their feedback on this part 👀

**Comment by clacaputo** [comment]
please test

refreshing the results

**Comment by mandrenguyen** [comment]
> After looking at the last test (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3763cc/29114/summary.html), it seems we have a lot of failings coming from the BTV HLT. I kindly ping @johnalison , @NiclasEich and @marco-link for their feedback on this part 👀

Hello, are we still waiting for feedback from BTV HLT?  @cms-sw/btv-pog-l2

**Comment by tvami** [comment]
hi @mandrenguyen I had a private communication with Soureek et al, and they said:
"We are discussing a bit with the developers how to simplify/update the access of the DNN tagger information within CMSSW. However, I'm sorry to say that this discussion will need a bit more time to come to a final conclusion leaving no loose ends. We expect to have a concrete plan by end-January, 2023. Hope this works with you."

I'd say we should let this PR in, and then let BTV remove the remaining dependencies for the HLT folder, what do you think?

**Comment by mandrenguyen** [comment]
> hi @mandrenguyen I had a private communication with Soureek et al, and they said: "We are discussing a bit with the developers how to simplify/update the access of the DNN tagger information within CMSSW. However, I'm sorry to say that this discussion will need a bit more time to come to a final conclusion leaving no loose ends. We expect to have a concrete plan by end-January, 2023. Hope this works with you."
> 
> I'd say we should let this PR in, and then let BTV remove the remaining dependencies for the HLT folder, what do you think?

Very good.  I just wanted to make sure it was not waiting on us.

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by rappoccio** [comment]
+1

**Pull request merged**
