### PR TITLE
Add option to cut H<a+bE+cE*E backport to 12_5_X

### PR DESCRIPTION
**Pull request by bennettgberg**
#### PR description:

Backport to 12_5_X for: https://github.com/cms-sw/cmssw/pull/39762

Adds an option to change the H/E cut to take the form H<a+bE+cE^2 for constants a, b, c.
This will be needed for Egamma objects in upcoming changes to the Scouting trigger.
Default behavior stays unchanged.

- No changes in output
- No external dependencies
- slides presented to TSG on the change in Scouting: https://indico.cern.ch/event/1186562/contributions/4992593/attachments/2489115/4274414/electronScouting_22-08-03.pdf
In particular, slide 10 shows the physics motivation--large increase in low-pT scouting electron signal reconstruction efficiency resulting from changing this cut.

#### PR validation:

Tested with scram b code-checks and scram b code-format. Further tests performed locally showing expected behavior of the code changes--namely, when doAnd is set to true with non-zero values for cut and cutOverE specified, all resulting scouting electrons in the collection obey H < cutOverE*E + cut and the number of these electrons is reasonable.

Tested in CMSSW_12_5_1 successfully with new 'doAnd' variable set to both True and False.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 12_5_X for: https://github.com/cms-sw/cmssw/pull/39762
Needed for possible testing of new Scouting menu at end of 2022 data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
backport of #39762

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
Removed the signature for now. Strange differences in wf `11634.7`. Likely unrelated to this PR, but we might want to rerun the tests, unless it is a known issue.

**Comment by perrotta** [comment]
please test
(let retrigger the tests, even though the differences in wf 11634.7 did not show up in the master version of this PR, nor in the 12_4_X backport)

**Comment by perrotta** [comment]
@missirol I was probably a bit too precipituous in relaunching the tests: the same differences in the same wf are also present in the unrelated PR https://github.com/cms-sw/cmssw/pull/39772

**Comment by missirol** [comment]
Thanks for the info. This confirms they are unrelated to HLT updates, b/c #39772 cannot cause them by construction.

**Comment by missirol** [comment]
+hlt

 - after re-running the PR tests, spurious differences in wf `11634.7` have disappeared (and this PR really isn't expected to lead to any differences, as the default behaviour of the plugin updated here is unchanged)

**Comment by perrotta** [comment]
+1

**Comment by missirol** [comment]
Interestingly, the bot didn't merge the PR..

**Pull request merged**
