### PR TITLE
Fix globToRegex and put it in anonymous namespace

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Follow-up on comments in #43334 

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@iarspider , please open a backport of this for 14.0.X

**Comment by smuzaffar** [comment]
type bug-fix

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 can you please review it.
@cms-sw/orp-l2 , this should also go in 14.0.X

**Comment by iarspider** [comment]
> @iarspider , please open a backport of this for 14.0.X

The original PR was not in 14_0_X, should I backport it as well?

**Comment by tjavaid** [comment]
> @cms-sw/dqm-l2 can you please review it.
> 
> @cms-sw/orp-l2 , this should also go in 14.0.X

Alright, I'll be able to get a bit later today.

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
