### PR TITLE
Added fillDescriptions to EmptyESSource

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added fillDescriptions to EmptyESSource

#### PR validation:

All the framework unit tests passed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
Why rerun the tests?

**Comment by fabiocos** [comment]
@Dr15Jones I want to verify the DQM differences, they are probably linked to a non reproducibility, do you agree?

**Comment by Dr15Jones** [comment]
I can not imagine a scenario where the DQM changes were caused by this pull request.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
