### PR TITLE
Forward-port #26937: Remove warnings from L1T DQM

### PR DESCRIPTION
**Pull request by benkrikler**
#### PR description:

Forward port of #26937.

#### PR validation:
No additional tests on top of what was done for #26937.

#### if this PR is a backport please specify the original PR:
* #26937

### CODE REVIEW

**Comment by fioriNTU** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@benkrikler could you please clarify in which workflow is the removal of the messages visible? 

@rekovic could you please cross check? Here essentially some parts are switched off

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@benkrikler could you please answer my question?

**Comment by fabiocos** [comment]
hold

pending an answer by @benkrikler

**Comment by benkrikler** [comment]
@fabiocos, apologies for not replying sooner, I'm on holiday and hadn't been checking emails.

The specific workflow I've tested this with is the one forwarded to us as being used for the UL rereco tests:

```
cmsdriver.py RECO -s RAW2DIGI,L1Reco,RECO,ALCA:SiStripCalZeroBias+TkAlMinBias+LumiPixelsMinBias+SiStripCalMinBias+AlCaPCCZeroBiasFromRECO,EI,PAT,DQM:@rerecoZeroBias --runUnscheduled --nThreads 8 --data --era Run2_2017 --scenario pp --conditions 106X_dataRun2_v10 --eventcontent AOD,MINIAOD,DQM --datatier AOD,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2017,Configuration/DataProcessing/Utils.addMonitoring --filein /store/data/Run2017B/ZeroBias/RAW/v1/000/297/047/00000/9678653B-D352-E711-B574-02163E01352E.root -n 1000 --python_filename=recoskim_Run2017B_ZeroBias.py --no_exec
```

**Comment by fabiocos** [comment]
unhold

@benkrikler ok, thank you for the clarification, I see the change

**Comment by fabiocos** [comment]
+1

**Pull request merged**
