### PR TITLE
Migration of HLT menus to 11_1_0 template (11_1_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration of HLT menus to 11_1_0 template (11_1_X)
Based on CMSSW_11_1_0

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

#30549
For MWGR use etc.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #30549

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
