### PR TITLE
[14_1_X] Add PbPbHighPtJets skim for 2024 PbPb backport

### PR DESCRIPTION
**Pull request by cfmcginn**
#### PR description:

This PR adds a new skim for high-pT jets (pT > 300, |eta| < 2.4) saving RAW-RECO in PbPb. Should correspond to no greater than 100k events (estimate from 2018 data puts it at ~20k). To be applied to the hadronic physics PDs (i.e. not HIForward/UPCs). This is a backport of existing PR to main, https://github.com/cms-sw/cmssw/pull/46499

@mandrenguyen

#### PR validation:

Tested as part of main PR, appears to create skim as expected for specified cuts. See main PR for details

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport, main PR is here: https://github.com/cms-sw/cmssw/pull/46499

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by cfmcginn** [comment]
Conflict is resolved

**Comment by AdrianoDee** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46560

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
