### PR TITLE
Removing Obsolete Phase2 Tracker (T4) and the corresponding WF (2023D20)

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
This PR is removing the obsolete phase2 Tracker T4 (flat barrel). 
It was included in only one phase2 WF : 2023D20 , which has been removed from runThematrix and from any configuration I could find.
I preserved the matrix ordering.

### CODE REVIEW

**Comment by boudoul** [comment]
@emiglior  FYI

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
@ianna @civanch could someone check and sign (or comment) for geometry?

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by kpedro88** [comment]
@boudoul sorry, there's a conflict with `numWFConflict` now

**Comment by boudoul** [comment]
Hi @kpedro88 , no pb  - I believe I fixed it, but I would appreciate your careful eyes to x-check, not really in front of a real screen as we speak

**Comment by kpedro88** [comment]
please test
@boudoul looks fine, thanks

**Comment by kpedro88** [comment]
@alja @fabozzi @ianna please sign (again)

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@alja ping

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@alja the Fireworks subsystem code change seems to me trivial

**Comment by fabiocos** [comment]
+1

**Comment by kpedro88** [comment]
it had also been signed by visualization previously before the update to fix a merge conflict....

**Comment by fabiocos** [comment]
@kpedro88 thanks, I take this as ok and merge

**Comment by fabiocos** [comment]
merge

**Pull request merged**
