### PR TITLE
Run3-gex74Y Backport #33760 to remove overlap in PPS

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #33760 to remove overlap in PPS. Works for DDD as well as DD4Hep

#### PR validation:

Tested using workflows for DDD as well as DD4Hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of the PR #33760 which is integrated with master for 12_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Why this PR needs backport? I assume we don't do anything with PPS with 11_3.

**Comment by civanch** [comment]
@srimanob , we have an agreement to backport to 11_3_0 all fixes for DDD and DD4Hep, which will are included into 12_0_X before migration to DD4Hep for Run-3 is done. This will allow to run full validation with 11_3 if will be needed.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
