### PR TITLE
[12_4_X] Add protection vs Minuit2 Fatal Root Error and update VxErrCorr in Vx3DHLTAnalyzer

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38687
This PR fixes the `beampixel` DQM client crashes observed recently, see master PR for detailed description

#### PR validation:
Code compiles + private tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Backport of #38687

FYI @dinardo

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #38687

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- For a backport in a closed release, maybe including just the bug fixes could have been sufficient. But ok, the additional cleanings seems quite harmlsess, and for DQM we have usually no such strict requirements as for other packages

**Pull request merged**
