### PR TITLE
update unit tests for `CondTools/SiPhase2Tracker` package to register failures and fix underlying code

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Unit tests for `CondTools/SiPhase2Tracker` are currently silently failing (see [logs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc11/CMSSW_13_2_X_2023-06-07-2300/unitTestLogs/CondTools/SiPhase2Tracker#/6-6), despite the test [declaring success](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc11/CMSSW_13_2_X_2023-06-07-2300/unitTestLogs/CondTools/SiPhase2Tracker#/201)). 
I modify the executable test script such that it registers the failure.
Also I update the configuration files in order to be able to run in recent releases.

#### PR validation:

Run successfully `scram b runtests_test_CondToolsSiPhase2Tracker`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   *  pull_request = #41901

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
test parameters:

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@tvami before you complain :) I am planning to leave 3 commits here (because they address all different issues). Let me know if that's acceptable.

**Comment by tvami** [comment]
+alca
 * relevant unit test passed

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- Contrarily to what written in the PR description, this PR also provides [a fix](https://github.com/cms-sw/cmssw/pull/41900/commits/1198fa4d9c030d11dc7f5f3cd995dd1cdd5d2ab5) for the unit test failure
- I imagine that after this merge, the other PR (#41901) which also includes that fix will need to be rebased

**Comment by mmusich** [comment]
@perrotta 

> Contrarily to what written in the PR description, this PR also provides [a fix](https://github.com/cms-sw/cmssw/pull/41900/commits/1198fa4d9c030d11dc7f5f3cd995dd1cdd5d2ab5) for the unit test failure

I've updated the PR description and title to be more adherent to the actual PR content

> I imagine that after this merge, the other PR (https://github.com/cms-sw/cmssw/pull/41901) which also includes that fix will need to be rebased

#41901 has been rebased.

**Pull request merged**
