### PR TITLE
New plots for Tracking Workspace (Backport to CMSSW_10_6_X of #27330)

### PR DESCRIPTION
**Pull request by hbecerri**
PR description:

Add new plots in the Tracking Workspace

dz with respect to BS
dxy with respect to the BS vs eta and phi,
q over p
track quality (isLoose, isTight, isHighQuality),
"inclusively" but also vs pT and eta
number of tracks per vertex, for the hard vertex and
for the other (PU) vertices
tracking efficiency plots from the folding method, for the
"eta vs phi map"
tracking efficiency vs pT of the tracks

Validated with runTheMatrix.py -l 10024

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of #27330

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@hbecerri could you please clarify the target of this backport? Is this meant to serve for UL validation purpose?

**Comment by mmusich** [comment]
@fabiocos, yes it was originally foreseen for the UL validation, I think it did not make it in time for the 2017 reprocessing, though we were wondering if could be accepted for 2018 and 2016. 
cc @jandrea @arossi83

**Comment by fabiocos** [comment]
hold

@hbecerri this PR should be updated according to #27535

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+1

**Pull request merged**
