### PR TITLE
Run3-sim159 Update the references to hcalRecNumbering files to have more appropriate flags to mark the Run2 period

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the references to hcalRecNumbering files to have more appropriate flags to mark the Run2 period

#### PR validation:

Tested with scripts in SimG4Core/PrintGeomInfo

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this PR

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
