### PR TITLE
fix `GeneralPurposeTrackAnalyzer` in the phase-2 case, due to missing conditions

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, becomes necessary because of https://github.com/cms-sw/cmssw/pull/42794.
Addresses https://github.com/cms-sw/cmssw/pull/42794#issuecomment-1725629229

#### PR validation:

`scram b runtests_PrimaryVertex use-ibeos` runs fine

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- Alignment/OfflineValidation unit tests that fail in the IBs are fixed with this PR: thank you @mmusich !

**Comment by mmusich** [comment]
@cms-sw/orp-l2 can you consider this to clean-up unit tests failures in IBs?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
