### PR TITLE
[ONLY FOR TESTING] [Basic2DGenericPFlowPositionCalc] Round PF cluster depth value if it is very close to an integer

### PR DESCRIPTION
**Pull request by silviodonato**
Details in https://github.com/cms-sw/cmssw/issues/35923
This fix resolves the GPU/CPU differences reported in the PFJet at HLT.
Please note that this bug affected also the CPU reconstruction! 

An alternative way to implement this fix is https://github.com/cms-sw/cmssw/commit/2077cfd519ed174a887bf762f18f2ff0d4053405, ie. by rounding value `(cluster2.depth() - cluster1.depth())` before using it.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
code-checks

**Comment by fwyzard** [comment]
Please, no: let's not add a fragile workaround on top of a more fragile code.

**Comment by silviodonato** [comment]
> Please, no: let's not add a fragile workaround on top of a more fragile code.

ok, I just wanted to check the severity of this bug

**Comment by silviodonato** [comment]
please test

**Pull request closed without merging**
