### PR TITLE
fixed CorrWithOverlapRemovalCondition.cc

### PR DESCRIPTION
**Pull request by namppl**
#### PR description:

Recently the overlap-removal condition (for 2 correlated legs + 1 overlap-removal leg) was found to be misconfigured in both L1 firmware and emulator code. The code has been fixed in accordance with the updated L1 firmware.

#### PR validation:

Unit tests done

### CODE REVIEW

**Comment by rekovic** [comment]
this is under discussion.

**Comment by rekovic** [comment]
hold

**Comment by qliphy** [comment]
@rekovic  Can this PR be closed by #36441 ?

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
unhold

**Comment by cecilecaillol** [comment]
@namppl Can you please close this PR? Changes were merged with #36758

**Pull request closed without merging**
