### PR TITLE
Implement second HF min-bias feature bit

### PR DESCRIPTION
**Pull request by christopheralanwest**
Only a single min-bias trigger has been used for 2018 pp running. For the upcoming 2018 HI run, two min-bias triggers that have different thresholds, but are otherwise identical, have been requested.

This PR implements two changes:

- The code changes needed to generate LUTs for the HCAL trigger that configure the second HF min-bias feature bit. This code has already been used to generate LUTs that have been used online for the HI test runs. 
- For the `pp_on_AA_2018` era, the HF trigger primitive simulation has been modified to generate two min-bias feature bits with thresholds of >15 and >19 ADC counts for the existing and new ("second") feature bit. These thresholds are similar to those that are expected to be used during the 2018 HI run. No changes are expected for any other era.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by christopheralanwest** [comment]
The comparison tests show an unexpected behavior for the second min-bias feature bit. Because of an indexing bug, the second min-bias feature bit was effectively the OR of the first and second min-bias feature bits. In my tests prior to PR submission, the threshold for the second min-bias feature bit was lower than that of the first, and so the algorithm behaved as expected. I've re-run the PR tests offline with the latest commit (08444b5d04286ee29872692219197fa1df29e149) to demonstrate that this problem is now fixed.

**Comment by thomreis** [comment]
please test

**Comment by christopheralanwest** [comment]
The expected effect of this PR is seen in the HI workflow [158.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-10-12-2300+24847/28889/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/L1T_L1TStage2CaloLayer1_HCalDetail.html). hcalOccSentFb and hcalOccRecdFb now have entries, corresponding to the new feature bit, and hcalOccSentFb2 and hcalOccRecdFb2 have more entries, a consequence of the lowered threshold for this bit in HI workflows.

I don't understand the changes in data/emulation comparisons for taus, which should be unaffected by any sort of change in HF. The backport of this PR (#24857) sees changes in electrons rather than taus, adding to the confusion. These changes seem unrelated to this PR.

**Comment by fabiocos** [comment]
@christopheralanwest thank you for your feedback, I am afraid the issue with taus is the same that we have already seen in previous PRs, and related to a non reproducibility of part of the L1T emulator/DQM chain, that should be fixed asap

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by lpernie** [comment]
+1

**Pull request merged**
