### PR TITLE
Backport Seed Fix for Herwig 7

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,

This is a backport of https://github.com/cms-sw/cmssw/pull/25180
to be tested with https://github.com/cms-sw/cmsdist/pull/4500

Kind regards,
Andrej

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test with  cms-sw/cmsdist#4500

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 511.0 with cms-sw/cmsdist#4500

**Comment by fabiocos** [comment]
+1

**Pull request merged**
