### PR TITLE
Run3-sim111 Take car of deprecated codes in FastSimulation/CaloGeometryTools

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take car of deprecated codes in FastSimulation/CaloGeometryTools

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

it is only test code - safe to merge

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
+1
- Code in \test

**Pull request merged**
