### PR TITLE
[Firework] Cleanup for public headers

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `Fireworks`
```
      1 src/Fireworks/Core/src/CmsShowMain.h
      4 src/Fireworks/Core/src/CmsShowTaskExecutor.h
      1 src/Fireworks/Core/src/FWDialogBuilder.h
      1 src/Fireworks/Core/src/FWItemSingleAccessor.h
     15 src/Fireworks/TableWidget/src/FWTabularWidget.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
