### PR TITLE
Fixup of L1REPACK for tasks

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fixup of L1REPACK for tasks

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

backport of #28012

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #28012

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
