### PR TITLE
Fix how empty FileInPaths are handled in python

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- set a default value in python
- have the cfi generator still add the default blank string

#### PR validation:

Unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
urgent

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
ping bot

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
core +1

**Comment by Dr15Jones** [comment]
+core

Doing this to give anyone in Europe a head start to integrate this

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
