### PR TITLE
HLT menu development for `12_3_X` + Update of L1T menu in TSG GTs [`12_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #37338

#### PR description:

Development of HLT menus for `CMSSW_12_3_X` + Update of L1T menu in TSG GTs to [`L1Menu_Collisions2022_v0_1_8_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_Collisions2022_v0_1_8_xml).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2245](https://its.cern.ch/jira/browse/CMSHLT-2245): introduction of Dataset Paths (and `FinalPath`s).

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37338

Development of HLT menus for Run-3 startup.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
The original PR (#37338) tested okay in IBs, including the "HLT-Validation" tests (see `CMSSW_12_4_X_2022-03-25-1100`).

**Comment by perrotta** [comment]
+1

**Pull request merged**
