### PR TITLE
Include "Scouting" packers and collections in MC production

### PR DESCRIPTION
**Pull request by fwyzard**
- update EndPaths kept in a cff python dump: keep Scouting* producers, drop the Scouting OutputModules, and change the Scouting EndPaths into regular Paths;
  - keep the Scouting collections in the RAW, RECO and AOD data tiers;
  - regenerate the python dumps.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
This changes the RAW data format!
The scouting products are NOT added to HLTDebug event content - why?

**Comment by fwyzard** [comment]
>This changes the RAW data format!

This is indeed what was discussed and agreed at the PPD meeting last week, being the easiest approach.

>The scouting products are NOT added to HLTDebug event content - why?

Good point, I will fix that.

**Comment by Martin-Grunewald** [comment]
Woha, so RAW is not that sacrosanct after all!

**Comment by fwyzard** [comment]
Only for data, for MC we can cheat :)

**Comment by fwyzard** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
backport #21297

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@Martin-Grunewald, @silviodonato, it looks like this should work. Can you have a look and double check I didn't miss or break anything ?

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
