### PR TITLE
fixes leftover from #45636

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

quick followup from  #45636
   * https://github.com/cms-sw/cmssw/pull/45768/commits/ce5b7ff57a3c5b88de7d8547b638d71bdb4fc4fe fixes the timing menu (after the sequences / products renaming - thanks @rovere for spotting)
   * https://github.com/cms-sw/cmssw/pull/45768/commits/6524606ef3adcaa719121cea5f7b8ffeba04e865 addresses https://github.com/cms-sw/cmssw/pull/45636#discussion_r1703888677
   
#### PR validation:

Run the following script to test the phase-2 timing menu:

```bash
#!/bin/bash -ex

DATASET="/RelValTTbar_14TeV/CMSSW_14_1_0_pre6-PU_141X_mcRun4_realistic_v1_STD_2026D110_PU-v3/GEN-SIM-DIGI-RAW"
ALL_FILES=( $(dasgoclient -query="file dataset=${DATASET}" --limit=-1 | sort | head -4) )

echo $ALL_FILES

cmsDriver.py Phase2 -s L1P2GT,HLT:75e33_timing --processName=HLTX \
  --conditions auto:phase2_realistic_T33 --geometry Extended2026D110 \
  --era Phase2C17I13M9 \
  --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
  --eventcontent FEVTDEBUGHLT \
  --filein=${ALL_FILES} \
  --mc --nThreads 4 --inputCommands='keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT' \
  -n 1000 --no_exec
```

No regression expected as this product should not be consumed in the menu, see https://github.com/cms-sw/cmssw/pull/45636#discussion_r1721955151

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
enable hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild ignore tests-rejected with ib-failure

**Comment by mmusich** [comment]
+hlt
   * hlt timing test runs correctly after this PR: [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_14_1_X_2024-08-22-1100&dataset=CMSSW_14_1_X_2024-08-22-1100-cmssw45768/el8_amd64_gcc12/15/Phase2Timing_resources), see https://github.com/cms-sw/cmssw/pull/45768#issuecomment-2306868343

**Comment by mandrenguyen** [comment]
+1

**Comment by mmusich** [comment]
For the record, the phase2 timing monitoring works again as of   [CMSSW_14_1_X_2024-08-23-2300](https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_14_1_X_2024-08-23-2300%2Fel8_amd64_gcc12%2FPhase2Timing_resources&resource=time_thread&colours=default&groups=hlt&filter=CMSSW_14_1_X_2024-08-23-2300&data_name=hlt-p2-timing&show_labels=true&threshold=0).

**Pull request merged**
