### PR TITLE
Modify vcal

### PR DESCRIPTION
**Pull request by dkotlins**
Modify the VCAL calibration for phase1 pixels.
Slope: 65->47, offset: -414  -> -60.
VCAL relates the internal charge injection to electrons.
Also change the channelThreshodl from 1000 to 250 electrons since layer 1 
can have pixel with very low charges,

### CODE REVIEW

**Comment by VinInn** [comment]
is this critical?

**Comment by dkotlins** [comment]
Vincenzo,
I have deleted this request because it again picked up 1 million other changes.
I have to learn how to push a single file with my change only

It will make the charge distribution closer to MC.
Should not affect resolution or efficiency.
D.

**Comment by VinInn** [comment]
is this valid for both phase0 and phase1?

**Comment by dkotlins** [comment]
It is only valid for phase1 so I guess we should modify the “era” setup, like for other things.
D.

**Comment by slava77** [comment]
On 6/8/17 11:40 PM, dkotlins wrote:
> Vincenzo,
> I have deleted this request because it again picked up 1 million other
> changes.
> I have to learn how to push a single file with my change only
> 
> It will make the charge distribution closer to MC.

This change should be applied both to data and MC, right?


> Should not affect resolution or efficiency.
> D.
>

**Comment by dkotlins** [comment]
YEs, this is correct. Janos will make it all using eras.

**Comment by jkarancs** [comment]
Dear all,
I am preparing a new PR with the eras implementation for both clusterizer and the digitizer (The latter is needed to be consitent with simulation). Where should I send the pull request: 92X or master?

**Comment by slava77** [comment]
On 6/9/17 7:13 AM, János Karancsi wrote:
> Dear all,
> I am preparing a new PR with the eras implementation for both
> clusterizer and the digitizer (The latter is needed to be consitent with
> simulation). Where should I send the pull request: 92X or master?
> 

master

**Pull request closed without merging**
