### PR TITLE
Fix HepMC3 conversion on MC without event weights (particle guns)

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

* Resolves https://github.com/cms-sw/cmssw/pull/44603#issuecomment-2205161533 by adding dummy event weights if none are present (most likely for particle guns)
* Add test to avoid this problem in the future

#### PR validation:

```
% runTheMatrix.py -l 11601.0 --ibeos -t 4
...
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test workflow 135.2,1317.0,2017.2,10001.0,10801.0,11604.0

**Comment by smuzaffar** [comment]
urgent

@cms-sw/generators-l2 , can you please review this? This should fix the many failing relvals

**Comment by antoniovilela** [comment]
+1
   - Will be merged once @cms-sw/generators-l2 sign.

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
