### PR TITLE
Condition access fix for Castor online DQM client

### PR DESCRIPTION
**Pull request by diguida**
The Castor online DQM application configured `DQM/Integration/python/clients/castor_dqm_sourceclient-live_cfg.py` now consumes all Castor related conditions by fetching them via the Global Tag centrally configured for online DQM.
Back-port of #16564

### CODE REVIEW

**Comment by diguida** [comment]
@popovvp this is the last step for Castor DQM operations
@mmusich @franzoni @arunhep watchers

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
@franzoni @arunhep further watchers

**Comment by dmitrijus** [comment]
Please close this. This PR is already irrelevant.

**Comment by diguida** [comment]
Closing, not needed anymore for online operations.

**Pull request closed without merging**
