### PR TITLE
CCLUT version 2.0 for the Run-3 CSC trigger (CCLUT-18)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

The CCLUT algorithm was implemented in Virtex-6 OTMBs ME1234/1. The older TMBs (ME1/3, ME1234/2) are based on Virtex-2 (XC2V4000). Presently, the logic resources are so strained that we have to simplify parts of the CCLUT algorithm in order to fit. 

To this end we're developing **CCLUT Version 2.0**. Two changes are made to reduce the resource usage: 
* The 9-bit quality word is removed from the LUT. This word is actually not even used in the simulation. Nor is it used in firmware. So it was basically an empty 9-bit word. This reduces the size of the result space from 18 bits to 9 bits. 
* In addition, we're adding 11-bit hit patterns (as opposed to 12-bit patterns). See https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/12. This reduces the size of the LUT by half.

We have decided to only have CCLUT version 2.0 in the OTMBs, but not yet in the TMBs (and not have it for start-up Run-3). R&D still ongoing how to fit the logic in the FPGA. We will split up TMB from OTMB in the code with separate switches. An update was made in the `CSCL1TPLookupTableEP` producer module so that it loads the text files for `CSCL1TPLookupTableCCLUT` from the correct directory.

I tested the modified CCLUT code on data from this Summer to verify that it still works. That appears to be the case indeed. 
[CSC_dataVsEmul_B904_Cosmic_Run_210701_135109.pdf](https://github.com/cms-sw/cmssw/files/7182825/CSC_dataVsEmul_B904_Cosmic_Run_210701_135109.pdf)
I should note that the LCT quality plot does not look as expected. This is because the CSC algorithm assumes a 2-bit quality code, and the firmware uses a 3-bit quality code. I will try to synchronize the definitions soon.

The code is not enabled yet, and is being tested with the B904 ME1/1, ME2/1 and ME4/2 test-stand in the coming weeks. Results from a test data run taken on September 17 shows poor agreement between data and emulation. In particular the comparator codes do not match yet.
[CSC_dataVsEmul_B904_Cosmic_Run_210917_122106.pdf](https://github.com/cms-sw/cmssw/files/7188176/CSC_dataVsEmul_B904_Cosmic_Run_210917_122106.pdf)

#### PR validation:

Code compiles. No LUTs for simulation are affected. There should be no change in any workflow.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
@tahuang1991 To produce the `.mem` files, follow the instructions in `L1Trigger/CSCTriggerPrimitives/test/README.md` in any release/IB after the PR has been integrated.

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
kindly ping @cms-sw/l1-l2

**Comment by dildick** [comment]
@cecilecaillol Can you sign off, please?

**Comment by dildick** [comment]
I notice that the function `calculateComparatorCode` is incomplete. I will commit the missing piece.

**Comment by dildick** [comment]
Results for 10k B904 cosmic run remain unchanged.

[CSC_dataVsEmul_B904_Cosmic_Run_210609_142357.pdf](https://github.com/cms-sw/cmssw/files/7100183/CSC_dataVsEmul_B904_Cosmic_Run_210609_142357.pdf)

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
There was a recent development yesterday. We have decided to only have CCLUT version 2.0 in the OTMBs, but not yet in the TMBs. R&D still ongoing how to fit the logic in the FPGA. I will introduce options to separate the two cases.

**Comment by rekovic** [comment]
+1

**Comment by smuzaffar** [comment]
@dildick , do we need to test this Pr with https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/12 ?

**Comment by dildick** [comment]
It's not absolutely necessary. They can be integrated separately. The CCLUT 2.0 tables were added, but they are not yet loaded (I would have to update an ES producer for that). Nor is the CCLUT 1.0 algorithm run in CMSSW.

**Comment by smuzaffar** [comment]
ok thanks

**Comment by dildick** [comment]
CCLUT v1.0 (algorithm + LUTs) was tested already with a cosmic test-stand at B904. That works fine. But we're now working on v2.0 which would have a smaller resource footprint on the chip. We have to wait with enabling it in CMSSW until downstream packages which consume CSC TPs are updated (next couple of weeks and months).

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
@qliphy Can this be signed off? Thanks!

**Comment by qliphy** [comment]
@dildick Can you fix the warning below?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-363a88/18584/llvm-analysis/runStaticChecks.log
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-13-2300/src/L1Trigger/CSCTriggerPrimitives/src/ComparatorCodeLUT.cc:152:75: warning: The result of the left shift is undefined because the left operand is negative [core.UndefinedBinaryOperatorResult]
    id += (calculateComparatorCodeLayer(column, halfStripPattern[column]) << shift);

**Comment by dildick** [comment]
yes, will do.

**Comment by dildick** [comment]
A few relevant plots:

Screen Shot 2021-09-17 at 12 28 41 AM
Screen Shot 2021-09-17 at 12 28 49 AM
Screen Shot 2021-09-17 at 12 28 56 AM
Screen Shot 2021-09-17 at 12 29 07 AM
Screen Shot 2021-09-17 at 12 29 21 AM
Screen Shot 2021-09-17 at 12 29 36 AM

**Comment by perrotta** [comment]
please test

**Comment by tvami** [comment]
+alca

 * new since the last signature: CCLUT code and configuration for 11 bits 
 * code looks fine, tests pass, no changes as expected

**Comment by dildick** [comment]
@tvami While initially I just wanted to update a script that produces the lookup tables for CCLUT v2.0, I ended up adding the algorithm and configuration as well since we're testing that at B904 for Run-3 at the moment.

**Comment by dildick** [comment]
Hi! Can this PR be signed off?

**Comment by smorovic** [comment]
+1

**Comment by dildick** [comment]
hold (until behavior of TeV muons in CMSSW_12_0_0_pre6 is understood)

**Comment by tvami** [comment]
@dildick would you please elaborate on why this was closed / what are the plans now?

**Comment by dildick** [comment]
There is a drop in the EMTF efficiency for TeV muons for |eta|>1.5 in recent relvals (CMSSW_12_0_0_pre6 and later). I wanted to hold off on integrating new features in the CSC trigger until that is understood.

**Pull request closed without merging**
