### PR TITLE
HCAL DQM: online config changes for 2018 (10_0_X version of #22109)

### PR DESCRIPTION
**Pull request by DryRun**
Some basic changes to the configurations for HCAL online DQM: change eras to 2018, remove plan-1-specific things.

This is the 10_0_X version of https://github.com/cms-sw/cmssw/pull/22109.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 can this be reviewed in time for 10_0_2?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
