### PR TITLE
HBHE: use proper quantization noise in the M2

### PR DESCRIPTION
**Pull request by mariadalfonso**
Hi.
Added proper quantization noise introduced in #16951 
Validation test in
http://dalfonso.web.cern.ch/dalfonso/dalfonso_M2adcFIX.pdf

Fix only the HE for the 2017 scenario. 
It affect both data and MC.

### CODE REVIEW

**Comment by slava77** [comment]
@mariadalfonso 
if the fix applies to QIE8 as well, I think we should apply changes everywhere.
If we need to compare 2016 data with 2017 data or MC or other permutations, we better have consistent reconstruction for the same detectors.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
if pre-2017 QIE8 reco can not be handled uniformly with 2017 with the new quantization uncertainties, I think it would be better to keep all QIE8/HPD reco the same in the same release.

**Comment by mariadalfonso** [comment]
@slava77

To have in the 2016 scenario as well I have to clone the function here
https://github.com/cms-sw/cmssw/pull/16951/files#diff-5bffd97385f18e7da1326160e40795c1R139
inside the RecoLocalCalo/HcalRecAlgos/src/PulseShapeFitOOTPileupCorrection.cc

I do think is better to have the fix for whole new 2017 detector (HB,HE) as we should aim to have the best hcal reco.
What is the pre-2017 use ?
1) comparison of the relVal ?
2) The "phase1" code can also be used for the run2 legacy re-reco and in case we have the full detector with the HPD thanks to the switch channelData.hasTimeInfo()
@igv4321

**Comment by slava77** [comment]
On 12/14/16 7:08 AM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77>
> 
> To have in the 2016 scenario as well I have to clone the function here
> https://github.com/cms-sw/cmssw/pull/16951/files#diff-5bffd97385f18e7da1326160e40795c1R139
> inside the
> RecoLocalCalo/HcalRecAlgos/src/PulseShapeFitOOTPileupCorrection.cc
> 
> I do think is better to have the fix for whole new 2017 detector (HB,HE)
> as we should aim to have the best hcal reco.
> What is the pre-2017 use ?
> 
>  1. comparison of the relVal ?
>  2. The "phase1" code can also be used for the run2 legacy re-reco and
>     in case we have the full detector with the HPD thanks to the switch
>     channelData.hasTimeInfo()
>     @igv4321 <https://github.com/igv4321>


We should have the best reco available everywhere a given detector is
active.
If the code is not flexible enough, it should be made so, and then the
reco applied.

**Comment by mariadalfonso** [comment]
@slava77 
ok, will change the 2016 scenario as well.
actually happy to do this for this and other fixes

**Comment by slava77** [comment]
On 12/14/16 7:20 AM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77>
> ok, will change the 2016 scenario as well.
> actually happy to do this for this and other fixes

Thank you very much.

**Comment by igv4321** [comment]
tsDFcPerADC is actually the differential gain: the width of that particular ADC count in fC. The nominal noise is actually tsDFcPerADC(ip)/sqrt(12.0). The factor 1/sqrt(12) is probably too optimistic, so (in an email thread "Re: QIE slope") I suggested to make it configurable.

**Comment by mariadalfonso** [comment]
@slava77 @igv4321 
I updated the run2 scenario as well. Low changes are expected there
The sqrt(12) is added to the ADC noise in both phase1 and run2.

The major impact is expected on the chi2 of the low recHit noise and hence the CPU time.

**Comment by slava77** [comment]
On 12/15/16 6:00 AM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77> @igv4321 <https://github.com/igv4321>
> I updated the run2 scenario as well. Low changes are expected there
> The sqrt(12) is added to the ADC noise in both phase1 and run2.
> 
> The major impact is expected on the chi2 of the low recHit noise and
> hence the CPU time.

Hi Maria,

Do you have comparison slides with the latest update?
IIUC, the reduction  of chi2 should be smaller now.

**Comment by mariadalfonso** [comment]
@slava77 
yes, posted in the PR description as well
http://dalfonso.web.cern.ch/dalfonso/dalfonso_M2adcFIX_PR17037.pdf

**Comment by slava77** [comment]
On 12/15/16 6:51 AM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77>
> yes, posted in the PR description as well
> http://dalfonso.web.cern.ch/dalfonso/dalfonso_M2adcFIX_PR17037.pdf



p2: in 2016 the chi2 at high pt in 2016 is worse by about 4 both in HB
and HE
p3: HB-HPD appears to change little at high E.
	Why do we have different performance in HB in p2 and p3?
p3: "HE HPD" is probably a "HE SiPM"
	at low E the chi2 is reduced by ~4 (good)
	at high E it looks somewhat similar

Could you please check and comment.

Thank you.

**Comment by mariadalfonso** [comment]
> p2: in 2016 the chi2 at high pt in 2016 is worse by about 4 both in HB
> and HE

--> yes , this is known.
the template used in MC comes from DATA, and a diffrent "timeslew" is adopted between the DIGI and RECO
the DIGI MC doens't match the template.
I'm pushing the HCAL guys to check the HPD DIGI steps (same review as been done for the siPM, need to be put for the )
worst case need to update the MC template (to be energy dependent)
I will add run2 data plots as well

> p3: HB-HPD appears to change little at high E.
> Why do we have different performance in HB in p2 and p3?
> 

--> noted and is puzzeling, can check more
 

> p3: "HE HPD" is probably a "HE SiPM"

--> yes fixed the label

>  at low E the chi2 is reduced by ~4 (good)
> at high E it looks somewhat similar
> 

--> yes indeed this is what we see, goes in the right direction

**Comment by slava77** [comment]
@mariadalfonso @igv4321 
it seems like based on discussion yesterday in the phase-1 meeting and also based on discrepancy in behavior between 2016 SIM and 2017 SIM, the HPD changes should be put on hold.

To keep moving with SiPMs, I suggest we use tsDFcPerADC only for SiPMs and postpone improvements for HPDs until they we have a setup with the same algorithm working for HPDs both in 2016 and 2017.

**Comment by mariadalfonso** [comment]
@slava77 

As promised I added the run2 DATA as well, see slide6 of 
http://dalfonso.web.cern.ch/dalfonso/dalfonso_M2adcFIX.pdf

Given the disagreemment in the 2016 and 2017 workflow, I agree it is wise to hold this HPD change and wait the HCAL-DPG to get organized for the HPD DIGI/RECO review.

The PR has been updated and the HPD-QIE8 changes removed in the run2 and phase1.
The PR description updated as well.
Please let me know if something else is needed from my side regarding this PR.

**Comment by slava77** [comment]
@cmsbuild please test

@mariadalfonso 
thank you for the quick update

**Comment by slava77** [comment]
@mariadalfonso 
there is a new quantum in chi2 values (~exactly 1)
pi500maria_chi2_elt5
Is this some numerical coincidence for "empty" TSs?

**Comment by mariadalfonso** [comment]
@slava77 

For low energy recHit, it often happen as follow
depth==1 chi2=0.831883
depth>1 chi2=0.893766
http://dalfonso.web.cern.ch/dalfonso/HCAL/depth1_afterPR17037.txt
http://dalfonso.web.cern.ch/dalfonso/HCAL/depthgt1_afterPR17037.txt
indeed those correspond to empty recHit

This happen for the high energy (E>5 and chi2>100)
http://dalfonso.web.cern.ch/dalfonso/HCAL/depth1_afterPR17037.txt
http://dalfonso.web.cern.ch/dalfonso/HCAL/depthgt1_afterPR17037.txt

**Comment by slava77** [comment]
Some plots from pi E 5 to 5000 gun (no PU), from endcap

(e_new - e_old)/e_raw vs e_raw
energynewminusold_over_eraw_vs_log10eraw_erawgt05
and the same zoomed to +/-0.1
energynewminusold_over_eraw_vs_log10eraw_erawgt05_zoom01

Looks like the 3-pulse fit results change by as much as 100%.
Above 20 GeV we now get about 10% less energy.

here is an overlay of the energy/eraw vs log10(eraw) profiles ("prof")
to show the change in response (new is in red)
energy_over_eraw_vs_log10eraw_erawgt05_prof_newred_oldblack

For your amusement, the scatter plot of new energy/eraw vs log10(eraw)  is
energynew_over_eraw_vs_log10eraw_erawgt05_wprof

chi2_new/chi2_old vs  log10(eraw)
log10chi2newoverold_vs_log10eraw

at lower energies the chi2 is smaller as expected
at high energy the chi2 gets worse as well as the response

Given that PF backs up calorimeter with tracking at lower energies, issues at higher energy are more important.
It's good that there are no tails here at high energy. So, a few % loss in response is probably OK since it can be calibrated away.

Is it clear that the high energy ADC uncertainty is correct?

**Comment by slava77** [comment]
@mariadalfonso @igv4321 @kpedro88 @abdoulline 
I will need some confirmation/clarification regarding behavior of M2 at high energy to sign off on this PR.

It looks like the errors decrease with this PR compared to the current CMSSW version.
If it is appropriate and expected from first principles, we can move on, hoping that the upcoming incorporation of  shape variations or other updates will take care of the excess chi2.

**Comment by mariadalfonso** [comment]
@slava77 

Thanks for the studies
I will compare the noise before as I obtained here 
https://indico.cern.ch/event/563410/contributions/2277004/attachments/1324249/2063825/ADCgranularity.pdf
Before the linear approximation, I should get the same error from igor implementation
I will come back to you by the end of my day

**Comment by slava77** [comment]
piE5to5000 sample calojet response.
this is essentially a single (charged) hadron response test

wfpie5to5000_ak4calo_corr_e

wfpie5to5000_ak4calo_reco_e

~5% drop, partly from averaging out over the hadron shower energy sample.

**Comment by abdoulline** [comment]
Slava, I do believe this implementation of ADC quantization error 
estimate is the move in the right direction, as it's based on a real ADC 
properties of QIE10 chip.

**Comment by slava77** [comment]
On 12/22/16 1:17 PM, Salavat Abdullin wrote:
> Slava, I do believe this implementation of ADC quantization error
> estimate is the move in the right direction, as it's based on a real ADC
> properties of QIE10 chip.

QIE11 (just a typo) ?

**Comment by abdoulline** [comment]
Right, mea cupla. Actually the only essential difference of QIE11 from 
QIE10 is a programmable shunt (of the input current) which is taken into 
account in the QIE11 calibration, other properties are very much the same.

**Comment by mariadalfonso** [comment]
@slava77 

I plotted here the relative error vs the input charge
http://dalfonso.web.cern.ch/dalfonso/HCAL/ADCnoiseVsCharge.gif

it's close enought to what I see in the slides of the electronic's guys see page2
https://indico.cern.ch/event/192695/contributions/353256/attachments/277181/387778/Elliot-Hughes.pdf
We can merge from my side

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17037 0035245
- code change is as described
- jenkins tests pass and show small differences in HCAL QIE11 and downstream variables in 2017 and in 2023 D4 and D8 workflows as expected
- local tests with more events confirm expected behavior: reduction of chi2 for lower energy hits (more so for very low-energy hits E<1 GeV). Also chi2 gets a bit worse for high energy and energy response decreases as discussed above. This specific change in uncertainty is more appropriate to what is done in digitization and what's expected for real QIE10/11 chips.
- technical performance with ttbar PU35  wf 10224 shows reduction in hbheprereco (M2, mostly) CPU by 0.4s/evt (~12% relative to the baseline module time or about 2% of the total reco time).

Note from PU35:
chi2 reduction is much more moderate
wf25202_he_log10chi2_vs_e

**Comment by davidlange6** [comment]
+1

**Pull request merged**
