### PR TITLE
[DQM] Migrated subsystem availability per lumi plot to softFED

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

`DSCRecord` data provided by softFED#1022 is now used to draw a subsystem availability per lumisection DQM plot. 

#### PR validation:

PR vas validated in the DQM playback system.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by arossi83** [comment]
@andrius-k There will be no backward compatibility with the changes on this PR, the code will run also on dat taken before 2018 but it will give no DCS info at all (the unpacker is run but there is no softFED 1022 before 2018). Probably this is not an issue since this is the DQM Online client but I just want to understand if you considered that. Thanks.

**Comment by andrius-k** [comment]
@arossi83 Yup, you're right! This PR is not ready yet. I will make sure that `DCSRecord` is used only when the old FED data is not present.
Also this PR need a corresponding render plugin change that is coming very soon.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by fioriNTU** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k @fioriNTU for what I can see, also in connection to the parallel discussion for #27676 and #27677 this PR is supposed to affect only online checks, ```DQMProvInfo``` is never used in any offline production workflow, am I correct?

For what i can see this PR is self-consistent, it would be good to have a common approach to manage this information across CMSSW

**Comment by fabiocos** [comment]
@andrius-k @fioriNTU do you confirm that this update is going to affect only online workflows?

**Comment by andrius-k** [comment]
Hi @fabiocos, yes, this PR affects only online workflows. This PR also doesn't need any changes from the subsystems but it requires a DQM GUI render plugin change to be fully usable: https://github.com/dmwm/deployment/pull/800

**Comment by fabiocos** [comment]
+1

**Pull request merged**
