### PR TITLE
uGT framework and L1 ntuples for showers in the muon system for Run-3 (HadronicShowerTrigger-8)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR does two things: (1) it builds out the Global Trigger framework for (hadronic) showers in the muon system for Run-3 (2) adds the `l1t::MuonShower` and `l1t::MuonRegionalShower` objects to the L1 Ntuples package for rate/efficiency studies.

* A new `MuonShower` object is introduced in the L1TGlobal emulator and data format packages. This object is treated separately from the regular Muon object. Much of it is based on the muon code, but fortunately it's much simpler.
* The code is based on UTM lib 0.9.X (https://gitlab.cern.ch/cms-l1t-utm/utm/-/releases/utm_0.9.0), which was recently integrated into CMSSW_12_0_X and CMSSW_12_1_X
   * cms-sw/cmsdist#7337 
   * cms-sw/cmsdist#7281 
* The uGT for Run-3 will have 4 bits per BX for muon showers: MUS0, MUS1, MUSOOT0 and MUSOOT1. They map to UTM bits MuonShower0, MuonShower1, MuonShowerOutOfTime0 and MuonShowerOutOfTime1
* For startup Run-3 we foresee MuonShower0 and MuonShower1 to be used by L1 trigger seeds. The other two bits can be used for enhanced shower triggers.
* Previous PRs include 
   * #35886
   * #34178
   * #33569
   * #33446
   * #33444
   * #33416
   * #33389
* Related PRs include:
   * https://github.com/cms-sw/cmssw/pull/35627 
   * https://github.com/cms-sw/cmssw/pull/34801
   * https://github.com/cms-sw/cmssw/pull/35461
   * https://github.com/cms-sw/cmssw/pull/35836 
* A few relevant presentations can be found here: 
    * [HadronicShowerTrigger_EXO_LL_L1DPG_6May2021.pdf](https://indico.cern.ch/event/1032087/contributions/4334392/attachments/2239866/3798910/HadronicShowerTrigger_EXO_LL_L1DPG_6May2021.pdf)
    * [HLT_muon_shower_martin.pdf](https://indico.cern.ch/event/1032087/contributions/4334095/attachments/2241349/3800447/HLT_muon_shower_martin.pdf)
   * [MuonShower_Oct1_Martin.pdf](https://indico.cern.ch/event/1080450/contributions/4548741/attachments/2320995/3952292/MuonShower_Oct1_Martin.pdf)
 * Related JIRA ticket to include new L1 seeds for Run-3:
    * https://its.cern.ch/jira/browse/CMSLITDPG-953  
* The design, implementation and performance of the hadronic shower trigger is documented here: https://gitlab.cern.ch/tdr/notes/DN-20-033/blob/master/temp/DN-20-033_temp.pdf
 * Integrating this PR is not urgent, but since it's quite a bit of code, it would be good to get early feedback from CMSSW managers.

#### PR validation:

* Code compiles. 
* A few integration tests have already been done with Run-3 GEN-SIM-RAW signal samples, such as 
`/HTo2LongLivedTo4b_MH-1000_MFF-450_CTau-100000mm_TuneCP5_14TeV_pythia8/Run3Winter20DRPremixMiniAOD-110X_mcRun3_2021_realistic_v6-v2/GEN-SIM-RAW`
* Rate studies are being carried out with this branch https://github.com/cms-l1t-offline/cmssw/pull/951 and with official L1 menu tools:
   * https://github.com/cms-l1-dpg/L1MenuTools/pull/62 
   * https://github.com/cms-l1-dpg/L1MenuTools/pull/66

There should be no changes in any workflow since the showers are not enabled in the global trigger logic.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by dildick** [comment]
FYI @giovanni-mocellin

**Comment by dildick** [comment]
Lots of failures. I'll have a look if it's always coming from ```EcalBarrelGeometryEPdd4hep``` or also from somewhere else

**Comment by dildick** [comment]
@rekovic A parameter for the muon showers is not there apparently. I'll need to fix that.

**Comment by dildick** [comment]
Ran  a quick test
```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecNan+HARVESTRecNan+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Nov 10 15:40:30 2021-date Wed Nov 10 15:07:13 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

**Comment by rekovic** [comment]
please test

**Comment by dildick** [comment]
* Someone will have to update `l1t::BXVectorInputProducer` to be thread-safe
* Similarly, `L1UpgradeTreeProducer` needs to be updated. Not sure which version is needed `stream` or `global`
* I'll need to check what is going on with the addon tests. Seems like it's trying to find a simulated product in the data. Maybe need similar approach as in https://github.com/cms-sw/cmssw/pull/36133

**Comment by dildick** [comment]
The addon tests are failing because it's trying to run the L1 trigger+HLT on 2018D data. Calling `simGmtShowerDigis` does not make a whole lot of sense, since it was not there. But it is included because it's a Run-3 era. For such repack runs it probably makes sense to configure simCscTriggerPrimitiveDigis as in PR https://github.com/cms-sw/cmssw/pull/33394

**Comment by dildick** [comment]
@francescobrivio Would PR https://github.com/cms-sw/cmssw/pull/36133 fix the failing addon tests in this PR?

**Comment by dildick** [comment]
@Martin-Grunewald By any chance, do you know if there is there a `L1REPACK` option for Run-3 eras but when you process Run-2 data for these HLT tests?

**Comment by dildick** [comment]
Certain https://github.com/cms-sw/cmssw/pull/36133 does not fix this issue. Just tried it myself.

**Comment by dildick** [comment]
The addon tests can probably all be fixed by adding `process.simCscTriggerPrimitiveDigis.GEMPadDigiClusterProducer='';process.simCscTriggerPrimitiveDigis.commonParam=dict(runME11ILT=False)`, e.g.

The driver command for the `hlt_data_PIon` repack test:
```
cmsDriver.py RelVal -s L1REPACK:Full --data --scenario=pp -n 10 --conditions auto:run3_hlt_PIon \
--relval 9000,50 --datatier RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run3 \
--eventcontent RAW --fileout file:RelVal_Raw_PIon_DATA.root --filein /store/data/Run2018D/EphemeralHLTPhysics1/RAW/v1/000/323/775/00000/2E066536-5CF2-B340-A73B-209640F29FF6.root \
--customise_commands="if hasattr(process,\"simMuonGEMPadTask\"): setattr(process,\"simMuonGEMPadTask\",cms.Task()); process.simCscTriggerPrimitiveDigis.GEMPadDigiClusterProducer='';process.simCscTriggerPrimitiveDigis.commonParam=dict(runME11ILT=False)"
```

**Comment by francescobrivio** [comment]
> The addon tests are failing because it's trying to run the L1 trigger+HLT on 2018D data. Calling `simGmtShowerDigis` does not make a whole lot of sense, since it was not there. But it is included because it's a Run-3 era. For such repack runs it probably makes sense to configure simCscTriggerPrimitiveDigis as in PR #33394

@dildick in my PR #36133 I did not see any addon failures, but as you already reported I don't think they are related.
Instead as you say "running on 2018D data with Era Run3" seems wrong to me, but i'm not very expert on how addon tests are configured...sorry!

**Comment by dildick** [comment]
@perrotta Do you have a suggestion?

**Comment by perrotta** [comment]
> @perrotta Do you have a suggestion?

Uhm, no I don't...
Did you try a similar fix as in #33394, as you suggested? Did it work?
In any case, if you want to touch the HLT addOn tests please coordinate with @cms-sw/hlt-l2 (@Martin-Grunewald @missirol )

**Comment by dinyar** [comment]
Hi @dildick,

Is it possible that you're running into the same issue as I was/am in https://github.com/cms-sw/cmssw/pull/35627?

Cheers,
Dinyar

**Comment by dildick** [comment]
@dinyar Possibly. But I don't know which script needs to change in order to let the addon tests pass.

**Comment by Martin-Grunewald** [comment]
The addOnTests for HLT are defined here:
https://github.com/cms-sw/cmssw/blob/master/Configuration/HLT/python/addOnTestsHLT.py 
We are looking into using a recent LHC pilot test beam data file which should be 'run3'.

**Comment by dildick** [comment]
@Martin-Grunewald Ok. In that case I will wait until HLT experts provide a solution for the `addOnTestsHLT.py` script.

**Comment by Martin-Grunewald** [comment]
Marino made the PR on the HLT side to update data-tests to run3: https://github.com/cms-sw/cmssw/pull/36222

**Comment by dildick** [comment]
Thanks!

**Comment by dildick** [comment]
@perrotta Can you restart the tests with #36222?

**Comment by perrotta** [comment]
test parameters:
- pull request = #36222

**Comment by missirol** [comment]
Hold on a moment, please; #36222 needs an update first. Then, I can restart the test here with that PR.

**Comment by perrotta** [comment]
> Hold on a moment, please; #36222 needs an update first. Then, I can restart the test here with that PR.

Ok, thank you @missirol : I'll let you start the tests when ready, the test parameters had been set already anyhow

**Comment by missirol** [comment]
test parameters:
  - pull_request = #36222

**Comment by missirol** [comment]
please test

(the bot disliked Andrea's suggestion b/c of a missing `_` ..)

**Comment by dildick** [comment]
Failures are coming from messagelogger.

**Comment by missirol** [comment]
#36222 has been merged yesterday and tested in the last IB without problems. This should solve any HLT-related issues initially encountered in this PR.

(I don't necessarily know how to undo the "test_parameters" instruction to the bot, and/or remove the label `requires-external` in this PR, but I guess those things are not strictly necessary.)

**Comment by dildick** [comment]
@rekovic With #36222 in place, ntuplization of Run-2 data should work then, not?

**Comment by dinyar** [comment]
Hi @dildick,

Only if this is done with Run-2 era. If someone wanted to repack Run-2 data using the Run-3 era (e.g. for some studies) it would fail with a rather hard to diagnose error. I the suggestion you made via email to have the CSC trigger primitives generator detect whether it's running on Run-2 data or not might be a pretty good solution to this.

Cheers,
Dinyar

**Comment by dildick** [comment]
Okay. In that case, I can amend this PR with such check.

**Comment by dildick** [comment]
@dinyar I had a look at the code. So a problem with the proposal, is that the `consumes` call happens at the constructor stage, before the event loop where you would do this check.

**Comment by rekovic** [comment]
@dildick 
Could we make the CSCTriggerPrimitive producer not crash in case GEM data are not available.  Instead of crashing on a non-existent ME11 record, could we simply have it issue a warning and proceed with producing trigger primitives in other detectors ?

**Comment by dildick** [comment]
@rekovic Is there a WF in CMSSW that is expected to crash without such change? That way I can try a few solutions today.

**Comment by rekovic** [comment]
Note that https://github.com/cms-sw/cmssw/pull/35627 is updated so that the [L1 Repack_Full configuration](https://github.com/cms-sw/cmssw/blob/f48ef6a5f075144f867ce8a07a46124a60eada0c/Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py) is now not changing the configuration of CSCTriggerPrimitives. That is to say, it is assumed that the `L1REPACK:Full` will be ran on Run3 data when invoked with `era=Run3` where CSC TP Producer is configured to create TPs from ME11 which are present, so that is fine.   
However, when running `L1REPACK:Full` on Run2 data the CSC TP Producer will crash.  This might not be a WF in CMSSW but a developer might be tempted to run L1REPACK on Run2 (ex. ZeroBias) data.

**Comment by dildick** [comment]
@rekovic OK. I'll try to fix this in the `CSCTriggerPrimitivesProducer`. I prefer to have https://github.com/cms-sw/cmssw/pull/36223 merged first, because that one also touches the producer module, and otherwise I'll need to rebase one or the other. But #36223 is a trivial addition.

**Comment by dildick** [comment]
Also, https://github.com/cms-sw/cmssw/pull/36046 needs to be merged first.

**Comment by dildick** [comment]
@rekovic So when I run on a Run-2 ZeroBias with this branch (but Run-3 era) with these instructions
```
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py l1=True mc=False maxEvents=100 run3=False dqm=True unpack=True inputFiles=file:18B49402-90AE-E811-972C-FA163E3D0B36.root
```
where 18B49402-90AE-E811-972C-FA163E3D0B36.root is a ZeroBias 2018D RAW file, I see messages such as 
```
Begin processing the 1st record. Run 322022, Event 3137354800, LumiSection 1811 on stream 0 at 30-Nov-2021 10:14:18.105 CST
%MSG-w CSCTriggerPrimitivesProducer:   CSCTriggerPrimitivesProducer:cscTriggerPrimitiveDigis 30-Nov-2021 10:14:18 CST  Run: 322022 Event: 3137354800
+++ Warning: Collection of GEM clusters with label simMuonGEMPadDigiClusters requested in configuration, but not found in the event... Running CSC-only trigger algorithm +++

%MSG
%MSG-w NoInputCollection:   CSCTriggerPrimitivesProducer:cscTriggerPrimitiveDigis 30-Nov-2021 10:14:18 CST  Run: 322022 Event: 3137354800
+++ Warning: Collection of GEM clusters with label simMuonGEMPadDigiClusters requested in configuration, but not found in the event... Running CSC-only trigger algorithm +++

%MSG
```
...
```
%MSG
30-Nov-2021 10:14:20 CST  Closed file file:18B49402-90AE-E811-972C-FA163E3D0B36.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 CSCTriggerPrimitives -w CSCTriggerPrimit                     100      100
    2 NoInputCollection    -w CSCTriggerPrimit                     100      100
    3 StatisticsSenderServ -w PostGlobalEndRun                       1        1
    4 fileAction           -s file_close                             1        1
    5 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 CSCTriggerPrimitivesProducer Run: 322022 Even Run: 322022 Even Run: 322022 Even
    2 NoInputCollection    Run: 322022 Even Run: 322022 Even Run: 322022 Even
    3 StatisticsSenderService PostGlobalEndRun                  
    4 fileAction           PostGlobalEndRun                  
    5 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning               201                 201
System                  3                   3

dropped waiting message count 0
```
It runs and does not crash.

**Comment by rekovic** [comment]
please test

**Comment by dildick** [comment]
@rekovic This needs to be rebased after #36046 and #36223 are merged.

**Comment by perrotta** [comment]
@rekovic @dildick #36223 and #36046 have been merged.
As soon as CMSSW_12_2_X_2021-12-02-1100 becomes available, this can be rebased

**Comment by dildick** [comment]
Still working on rebasing and cleaning up the commit history...

**Comment by dildick** [comment]
@perrotta Can you start the tests, please? Thanks

**Comment by perrotta** [comment]
please test

**Comment by dildick** [comment]
@perrotta This is good enough. There are some changes in the GEM-CSC trigger. That's fine. Tao Huang @tahuang1991 is going to switch it off anyway in the next PR  in preparation for Run-3 MC production. Ultimately, the GEM-CSC trigger won't be turned on for first collisions. Likely this will be turned on gradually. After talking to L1 DPG it seems best to turn it off for now. @tahuang1991 would also further improve the GEM-CSC trigger logic so it matches more closely the firmware. But it's important that the uGT emulator for the hadronic shower trigger goes in at this point.

**Comment by dildick** [comment]
@perrotta Scratch that... I need to fix the issue with GEM-CSC, even if we're going to turn of the GEM-CSC trigger in another PR... I'll look at it now. Maybe a pointer is invalid that's causing the GEM-CSC triggers not to be produced

**Comment by dildick** [comment]
```
%MSG
%MSG-w NoInputCollection:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  03-Dec-2021 14:21:13 CST Run: 1 Event: 8
+++ Warning: Collection of GEM clusters with label simMuonGEMPadDigiClusters requested in configuration, but not found in the event... Running CSC-only trigger algorithm +++

%MSG
```
Looks like a pointer is invalid, even in WF 11634.0

**Comment by dildick** [comment]
Probably the `getByToken` is at the wrong place

**Comment by dildick** [comment]
So now, when the GEM clusters are not there for some reason it prints out a warning and proceeds with building regular LCTs. Example when there was a typo `simMuonGEMPadDigiClustersA`


```
Begin processing the 10th record. Run 1, Event 10, LumiSection 1 on stream 0 at 03-Dec-2021 14:49:48.893 CST
%MSG-w CSCTriggerPrimitivesProducer:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  03-Dec-2021 14:49:55 CST Run: 1 Event: 10
+++ Warning: Collection of GEM clusters with label simMuonGEMPadDigiClustersA requested in configuration\
, but not found in the event... Running CSC-only trigger algorithm +++

%MSG
```

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
tests are not initiated for some reason.

**Comment by rekovic** [comment]
please abort test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
All failures are coming from the messagelogger

**Comment by dildick** [comment]
@rekovic Let me know if you have any more comments or questions.

**Comment by dildick** [comment]
@rekovic Can you sign off, please?

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
