### PR TITLE
Add a DQM sequence for pixel-only tracking

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel @rovere @VinInn please do comment if you think this is OK or not

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@smuzaffar, is it possible to ask @cmsbuild to run one particular matrix workflow ?

**Comment by kpedro88** [comment]
@fwyzard try
please test workflow #####

**Comment by fwyzard** [comment]
thank you

**Comment by fwyzard** [comment]
@cmsbuild please test workflow 10824.5

**Comment by makortel** [comment]
@fwyzard 

Looks otherwise good to me (thanks!), except

> I just realised that the MC-based validation uses the PixelTrack folder, while this is using the PixelTracks folder. Shall I correct this PR to use the same PixelTrack folder ?

I'd suggest to use `PixelTrackParameters` for the folder (to be consistent with the "full tracking" folders, that is `Tracks` for MC-validation and `TrackParameters` for DQM).

**Comment by fwyzard** [comment]
OK, I'll make the change.

Any comments on the flags being set ?
I've tried to follow what I found around and/or got from @JanFSchulte , but if you have a better suggestion I can change them.

**Comment by makortel** [comment]
> Any comments on the flags being set ?

Not really. I see you have `pixelTracksMonitoring.doAllPlots = True` so we should get almost everything (and in case we're missing something, I find it easier to notice when browsing the histograms than trying to follow the full logic of `TrackingMonitor`...).

**Comment by fwyzard** [comment]
Folder changed from `Tracking/PixelTracks` to `Tracking/PixelTrackParameters`

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
