### PR TITLE
Added signed GSF track variable collections to the HLT producer

### PR DESCRIPTION
**Pull request by arsahasransu**
#### PR description:

We plan to store the values of dEtaSigned, dPhi and 1/E-1/p for the best GSF track in the scouting electron collection. The default implementation is the absolute value. Hence, I named the new variable collections as signed parameters. The output of this HLT producer will now have three more variable collections. The corresponding change to computation time is expected to be negligible, as there is no additional computation required for these variables.

More details can be found in the following [Scouting Meeting Presentation](https://indico.cern.ch/event/1366361/#8-scouting-2024-egamma-updates).

#### PR validation:

 - Standard set of code checks and code-formatting done. 
 - Suggested test in [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html) passed successfully.
 - An HLT configuration was re-run on 100 events on a single thread and the output was manually verified. As expected the new collections had different signs (+ or -) compared to the previous collections. However, the absolute value was identical. The test configuration and output files are on AFS at /afs/cern.ch/work/a/asahasra/public/ScoutingStudy/For2024ScoutingEGUpdate/CMSSW_14_0_0_pre2/src/TestSignedOutput_scoutingPFMC.py and /afs/cern.ch/work/a/asahasra/public/ScoutingStudy/For2024ScoutingEGUpdate/CMSSW_14_0_0_pre2/src/TestSignedOutput_outputScoutingPF.root respectively.

|    Row   | Instance | dEta | dPhi | 1/E-1/p | dEta (Signed) | dPhi (Signed) | 1/E-1/p (Signed) |
|---------|-----------|------|------|---------|------|------|---------|
|        0 |        0 | 0.0014388 | 0.0044460 | 0.0011451 | 0.0014388 | 0.0044460 | 0.0011451 |
|        0 |        1 | 0.0012900 | 0.0017273 | 0.0007097 | 0.0012900 | -0.001727 | 0.0007097 |
|        1 |        0 | 0.0059239 | 0.0636629 | 0.0038597 | 0.0059239 | -0.063662 | 0.0038597 |
|        2 |        0 |           |           |           |           |           |           |
|        3 |        0 | 0.0007234 | 0.0008861 | 0.0009526 |  0.0007234 | 0.0008861 | -0.000952 |
|        4 |        0 | 0.0018080 | 0.3457266 | 0.3404662 | -0.001808 | -0.345726 | -0.340466 |
|        5 |        0 | 0.0015170 | 0.0008683 | 5.430e-05 | -0.001517 | -0.000868 | -5.43e-05 |
|        5 |        1 | 0.0182280 | 0.0482790 | 0.0161032 | -0.018228 | 0.0482790 | 0.0161032 |
|        5 |        2 | 0.0057608 | 0.0288665 | 0.0362727 | 0.0057608 | 0.0288665 | -0.036272 |
|        6 |        0 | 0.0011856 | 0.0052164 | 0.0001695 | -0.001185 | 0.0052164 | 0.0001695 |
|        6 |        1 | 0.0104081 | 0.0089188 | 0.0003987 | 0.0104081 | -0.008918 | -0.000398 |
|        7 |        0 | 0.0014166 | 0.0006581 | 0.0011761 | -0.001416 | 0.0006581 | 0.0011761 |
|        7 |        1 | 0.0044303 | 0.0087084 | 0.0006514 | 0.0044303 | -0.008708 | 0.0006514 |
|        7 |        2 | 0.0110887 | 0.1865830 | 0.0057946 | -0.011088 | -0.186583 | -0.005794 |
|        8 |        0 | 0.0027326 | 0.0096881 | 0.0123428 | 0.0027326 | 0.0096881 | 0.0123428 |
|        8 |        1 | 0.0036929 | 0.0480504 | 0.0082893 | -0.003692 | 0.0480504 | -0.008289 |
|        9 |        0 | 8.153e-05 | 0.0036187 | 0.0020031 | -8.15e-05 | -0.003618 | -0.002003 |
|        9 |        1 | 0.0004655 | 0.0014679 | 0.0021860 | -0.000465 | 0.0014679 | 0.0021860 |
|        9 |        2 | 0.0039569 | 0.0109441 | 0.0023139 | -0.003956 | 0.0109441 | -0.002313 |
|       10 |        0 | 0.0044148 | 0.0165488 | 0.0016855 | 0.0044148 | -0.016548 | 0.0016855 |
|       10 |        1 | 0.0002905 | 0.0013964 | 0.0009109 | -0.000290 | -0.001396 | -0.000910 |
|       10 |        2 | 0.0073547 | 0.0221956 | 0.0041651 | 0.0073547 | -0.022195 | -0.004165 |
|       11 |        0 | 0.0120838 | 0.2586605 | 0.0030191 | 0.0120838 | 0.2586605 | -0.003019 |
|       11 |        1 | 0.0022847 | 0.0024123 | 0.0002324 | 0.0022847 | -0.002412 | 0.0002324 |
|       11 |        2 | 0.0006264 | 0.0059466 | 0.0005957 | -0.000626 | 0.0059466 | -0.000595 |

 - PR needs to be back ported to CMSSW_13_3_X release cycle to enable testing on HLT development configurations.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
Sorry, but this seems to be a waste of space, because the unsigned versions (std::abs(...)) are already stored. Either get rid of those or simply store the signed quantities in the existing product collections.

**Comment by arsahasransu** [comment]
> Sorry, but this seems to be a waste of space, because the unsigned versions (std::abs(...)) are already stored. Either get rid of those or simply store the signed quantities in the existing product collections.

Changing the existing behaviour of this HLT producer is risky since it will be repeatedly used in the HLT paths of many electron and photon triggers, some of which rely on the absolute value of parameters. Of course, one can in principle track down the HLT filters where the GSF track variables have been used and check/update the implementation. I can contact EGM POG to find the most recommended way to move forward. Alternatively, I could add a bool flag which returns the signed/unsigned parameter, where the default behaviour is to return the unsigned value. What would you suggest?

**Comment by Martin-Grunewald** [comment]
Change the downstream code to put the std::abs there.

**Comment by Sam-Harper** [comment]
> Change the downstream code to put the std::abs there.

The downstream code is HLTEgammaGenericFilter which is used for all E/gamma ID cuts. So you cant just std::abs it, you need to have an option to have std::abs on it. 

While this is perfectly possible to do, one, we would need to update every filter which uses these variables (not a complete deal breaker, python script will do it) and two in the future we remember to do it for new filters. Again possible with some dedicated python scripts to check.

There is a risk that this is  done improperly. We thought the risk of difficult to spot errors was worse than storing a few extra floats temporarily in the event record. 

But I'm more than willing to follow STORM guidance on this, these sort of menu maintainability trade offs are judgement calls and STORM has a lot of experience in this.

**Comment by Sam-Harper** [comment]
Admittedly I cant think of any variable that goes negative and std::absing would be bad for so in theory we could always std::abs the variable in the filter but that feels a bit icky and possibly may cause problems down the road.  Possible the new MVA trigger would be broken by it.  Also I havent thought very hard so it possible I missed something, possibly involving defaults.

**Comment by Martin-Grunewald** [comment]
I'd still try to avoid the duplication of having both signed and unsigned collections in RAM, even if not (currently) persistet on file. 

(The downstream module instances know via their config what collections they access. Also, for example, the GenericFilter may move to std::abs dynamically on the first encounter of a negative input value, and until then since all values were positive, no change in behaviour...)

**Comment by Sam-Harper** [comment]
But what happens if you have variable which goes negative but no matter what the negative value it is its acceptable. 

I really dont like the dynamic solution, that feels asking for trouble.  I prefer explicit not implicit configurations as implicit rely on assumptions which is fine till they change. The downstream module knows the collection but has no idea what it is , its just a value to it. 

I will accept the adding a bool to EgammaGenericFilter to abs the variable though if its felt on reflection that this is the better way.  It doesnt feel like this is not a lot of memory either, what at best a 1kb over an entire machine running a 24 stream job? 

Of course ultimately we will do what you suggest here but I would advice strongly against a solution like the dynamic solution.

Thats all said, AR, two things
1) I thought we agreed on a bool to control the production of these variables. Scouting will have its own copy of the producer anyways
2) this is missing fbrem, why did that commit not make it here

**Comment by Martin-Grunewald** [comment]
Indeed I like ```adding a bool to EgammaGenericFilter```.

**Comment by Sam-Harper** [comment]
I have started another PR here
https://github.com/cms-sw/cmssw/pull/43774

**Comment by mmusich** [comment]
> I have started another PR here

thanks @Sam-Harper, do I understand correctly that we can close this one ?

**Comment by Sam-Harper** [comment]
Yes but its not mine so I cant.

**Comment by mmusich** [comment]
@cmsbuild please close

**Pull request closed without merging**
