### PR TITLE
Run3-gex157B Replace use of cout's with LogVerbatim in Geometry/DTGeo metry and Geometry/DTGeometryBuilder

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace use of cout's with LogVerbatim in Geometry/DTGeo metry and Geometry/DTGeometryBuilder

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
hold
(To be honest, there is no need to hold this one: I'd simply would like to force @bsunanda checking https://github.com/cms-sw/cmssw/pull/41048#pullrequestreview-1354154316, and act accordingly if needed)

**Comment by perrotta** [comment]
unhold
(There is another bug to fix anyhow in Geometry/HGCalCommonData/src/HGCalWaferMask.cc, see https://github.com/cms-sw/cmssw/issues/41184: the removal of the debug flag from the production release can be applied when fixing it @bsunanda)

**Comment by perrotta** [comment]
+1

**Pull request merged**
