### PR TITLE
Fix HLT Timing script for CI

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

This Pull Request addresses an issue with the Phase2 HLT performance monitoring script, which has been non-functional for several weeks due to incompatible changes introduced by L1T. The script has been updated to use a more recent version of the input dataset that includes all the necessary products. Additionally, the geometry and Global Tag (GT) have been updated to ensure compatibility with the new dataset.

#### PR validation:

Run locally w/o problems.

### CODE REVIEW

**Comment by rovere** [comment]
enable hlt_p2_timing

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> which has been non-functional for several weeks 

For my own education, where is one supposed to check?

**Comment by rovere** [comment]
> > which has been non-functional for several weeks
> 
> For my own education, where is one supposed to check?

Hi @mmusich,

Typically, this test is included in the regular test suite for every Integration Build (IB). The results, particularly the HLT pie chart, are usually accessible via a link from the main IB portal. However, the link is currently missing because the test is broken. This PR aims to address this issue.

**Comment by smuzaffar** [comment]
@rovere , HLT timing test still fails with error 
```
+ cmsDriver.py Phase2 -s L1P2GT,HLT:75e33_timing --processName=HLTX --conditions auto:phase2_realistic_T33 --geometry Extended2026D110 --era Phase2C17I13M9 --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 --eventcontent FEVTDEBUGHLT --filein= --mc --nThreads 4 '--inputCommands=keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT' -n 1000 --no_exec '--output={}'
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02850/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-08-14-2300/bin/el8_amd64_gcc12/cmsDriver.py", line 40, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02850/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-08-14-2300/bin/el8_amd64_gcc12/cmsDriver.py", line 11, in run
    options = OptionsFromCommandLine()
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02850/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-08-15-1100/src/Configuration/Applications/python/cmsDriverOptions.py", line 36, in OptionsFromCommandLine
    options=OptionsFromItems(sys.argv[1:])
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02850/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-08-15-1100/src/Configuration/Applications/python/cmsDriverOptions.py", line 153, in OptionsFromItems
    options.filein=trimmedEvtType+"_"+prec_step[first_step]+"."+filesuffix
KeyError: 'L1P2GT'

```

**Comment by smuzaffar** [comment]
also input data is missing https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f2d24e/40941/hlt-p2-timing.log

**Comment by rovere** [comment]
ciao @smuzaffar the first error is a consequence of the missing dataset.
I'll copy the dataset to the online machine and retrigger the test in this PR later this afternoon.

**Comment by rovere** [comment]
@smuzaffar files are now available on the machine. Is there a way to trigger only the `hlt-p2-timing` test w/o re-running everything else?

**Comment by rovere** [comment]
The script searches for the input files in the directory `/data/user/cmsbuild/store/relval/...`.
I'm not sure if the last time it was Andrea who copied the files over in the right place.
I copied them in the wrong place, so the test failed again.
@fwyzard do you remember by any chance?

**Comment by smuzaffar** [comment]
this job was running under our container and `/eos` was mount mounted that is why https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/HLT_75e33/test/runHLTTiming.sh#L20-L25 section was not able to copy files from /eos to local disk. This is fixed now and job is running

**Comment by rovere** [comment]
The test now runs but fails.
I tested it using `14_1_0_pre5`, but apparently since the merging of #44498, additional changes would be required in the current sequence used to run the HLT Timing test.
I'll test and update this PR with samples from `14_1_0_pre6`.

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
cmsbot tests run, this

> HLT P2 Timing: [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_14_1_X_2024-08-18-2300&dataset=CMSSW_14_1_X_2024-08-18-2300-cmssw45705/el8_amd64_gcc12/14/Phase2Timing_resources)

looks empty though.

**Comment by rovere** [comment]
> cmsbot tests run, this
> 
> > HLT P2 Timing: [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_14_1_X_2024-08-18-2300&dataset=CMSSW_14_1_X_2024-08-18-2300-cmssw45705/el8_amd64_gcc12/14/Phase2Timing_resources)
> 
> looks empty though.

indeed, maybe @smuzaffar knows why?

**Comment by smuzaffar** [comment]
I am looking in to this

**Comment by smuzaffar** [comment]
@rovere , hlt p2 timing chart is working now

**Comment by mmusich** [comment]
>  hlt p2 timing chart is working now

is it normal to have such a large "idle" fraction?

**Comment by rovere** [comment]
> > hlt p2 timing chart is working now
> 
> is it normal to have such a large "idle" fraction?

That's a good question. In general, I don't think we should have such a big contribution from `Idle`. Maybe @fwyzard could remind us, once again, what `Idle` means in this context, exactly?

I think, in any case, that this PR could proceed no matter what since the mechanics of the test are working ok. Agree?

**Comment by mmusich** [comment]
> I think, in any case, that this PR could proceed no matter what since the mechanics of the test are working ok. Agree?

agreed.

**Comment by mmusich** [comment]
+hlt
   * factually proved the Phase-2 HLT timing script runs (see https://github.com/cms-sw/cmssw/pull/45705#issuecomment-2296531724).
   * further refinements are left for a possible follow-up (see https://github.com/cms-sw/cmssw/pull/45705#issuecomment-2301336045)

**Comment by fwyzard** [comment]
> Maybe @fwyzard could remind us, once again, what `Idle` means in this context, exactly?

It _should_ mean that the TBB worker threads do not have any task they can do, so are sitting idle.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
