### PR TITLE
HLT config fix for TrackerTopologyEP (#7589)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
This PR addresses the HLT menu changes in #7589.
It makes the HLT config changes properly so that they do not get
overwritten when the HLT menus are updated from ConfDB.
This PR can go in even before #7589, because the module implements fillDescriptions(.)
which will put the removed parameters.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Actually, this PR can go in now because the module implements fillDescriptions(.)
which will put the removed parameters.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
yuck.. i'm not sure what the idea is here? Please clarify - it seems you will now produce something that has been there for several release cycles (but is going away) if the release is >=7_4

**Comment by Martin-Grunewald** [comment]
@davidlange6 

Indeed!

We use the same menus for 73X and 74X. Hence we need to ensure compatibility.
Yana's PR #7589 (74X only) removes most parameters from the ES module as they
will be taken from the GT/DB. Thus we have to remove those from the HLT dumps, but only
for 74X use. Hence this "release-dependent" customisation of the common HLT menu dumps
created from ConfDB (and the same there for 73X and 74X).
Once HLT moves to 74X, we'll put this directly into the menus in ConfDB and remove
the release dependent customisation - those menus will then no longer run with 73X.

**Comment by Martin-Grunewald** [comment]
This PR can go in now (even before Yana's) because the module implements fillDescriptions(.)
which will put the removed parameters back (this is changed by Yana's PR).

**Comment by davidlange6** [comment]
On Feb 10, 2015, at 9:38 AM, Martin Grunewald <notifications@github.com>
 wrote:

> @davidlange6
> 
> Indeed!
> 
> We use the same menus for 73X and 74X. Hence we need to ensure compatibility.
> Yana's PR #7589 (74X only) removes most parameters from the ES module as they
> will be taken from the GT/DB. Thus we have to remove those from the HLT dumps, but only
> for 74X use. Hence this "release-dependent" customisation of the common HLT menu dumps
> created from ConfDB (and the same there for 73X and 74X).
> Once HLT moves to 74X, we'll put this directly into the menus in ConfDB and remove
> the release dependent customisation - those menus will then no longer run with 73X.

I think you have this a bit backwards. The ES module in question will go away (or at least become useless) once Yana's changes are complete. So, once in there is no need to have the ESProducer in question. The fill descriptions are there in 73x (and 72x and 71x and�) - so I don't see the reason to have the if 74x statement at all.

Also note that it is not likely that Yana's PR will enter 74x at this point.

**Comment by Martin-Grunewald** [comment]
Well, up to 73X included we need the ES module (in the HLT dumps)
From 74X onward we no longer need it once Yana's PR gets accepted.

Please understand that we do not just work for CMSSW release but also developers
who use menus from ConfDB directly with either 73 or 74.

**Comment by davidlange6** [comment]
On Feb 10, 2015, at 9:49 AM, Martin Grunewald <notifications@github.com>
 wrote:

> Well, up to 73X included we need the ES module (in the HLT dumps)
> From 74X onward we no longer need it once Yana's PR gets accepted.

Right, I agree - but thats not what your code does. So I'm a bit lost.

Cheers-
David

**Comment by Martin-Grunewald** [comment]
The py code kills the excess parameters when used in a 74X release, 
but keeps it if the same menu is used in a 73X release (eg, by a developer
using 73 as stable platform). This is the compatibility we need.

**Comment by davidlange6** [comment]
i'm lost.. 73x and 74x are currently identical (and likely to remain so) as far as these parameters go.

**Comment by Martin-Grunewald** [comment]
OK, so if Yana's PR is just to dump stuff out into the domain without request of being merged,
also this PR is not needed. But then, please close Yana's PR to tidy things up.

**Comment by davidlange6** [comment]
Yana's PR will go to 75x, which we will seed from the 74x queue. So for the moment, it is in the right place.

**Comment by ianna** [comment]
@Martin-Grunewald - I'll merge your PR with mine, then it should be ok.

**Comment by ianna** [comment]
@davidlange6 - I would have hoped we can put #7589 in 74x

**Comment by Martin-Grunewald** [comment]
Closing as superseeded!

**Pull request closed without merging**
