### PR TITLE
GEMGeometryBuilderDB-fix [93X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #20260 

Important for HGCal TDR release

@jshlee I'm just submitting this now for expediency, reusing your existing branch

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
should this be closed in favor of a backport of #20562?

**Comment by davidlange6** [comment]
Closing PR as it is not needed for this release cycle. CMSSW_9_3_X is planned for use only for 2017 GEN-SIM production and HGCal TDR production.

**Pull request closed without merging**
