### PR TITLE
Update skim config for 2023 data taking and fix wrong assignment in skim wf

### PR DESCRIPTION
**Pull request by youyingli**
#### PR description:

* Add IsoPhotonEB skim given by #42150 to the 2023 skim config
* Fix the wrong assignment in skim wf

### CODE REVIEW

**Comment by sunilUIET** [comment]
please test

**Comment by youyingli** [comment]
Hi @sunilUIET , @srimanob, please sign it if no other consideration

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

Note that in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_standard.py#L537-L550, DQM is produced but no harvesting. This should be followed up. @youyingli @sunilUIET

**Comment by perrotta** [comment]
+1

**Pull request merged**
