### PR TITLE
Use an indexed sort for expensive comparisons in MuonShowerInformationFiller

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

MuonShowerInformationFiller has several sorts over the muon hits that use comparison functions involving complex calculations.  This has two problems, (1) the comparison function is executed O(n*log(n)), so the same complex calculations are performed multiple times, and (2) when vector instructions are enabled, the values calculated may not be completely stable, which may make the sort ill-defined.  See issue #33663 for details.

This PR replaces the use of `stable_sort` with a custom sort function that pre-calculates and caches the values to be sorted, performs an index sort on the cached values, and constructs the output container.  This reduces the number of complex calculations to O(n), at some cost in complexity and memory usage.  In practice this is measured to reduce the CPU time for a typical sort by 2/3.  It also fixes the segmentation faults.

In addition, this PR also corrects two places where I believe the in-place sorting of `stable_sort` was incorrectly sorting the input containers to two functions.

It would arguably be better for the MuonShowerInformationFiller to define its own hit type that caches the global coordinates and derived quantities; however, that would be a much more intrusive change, where this PR is fairly minimal.

#### PR validation:

Workflow 136.844 runs successfully in a Skylake IB, spot checks of the sort results found the results to be identical.  Mostly technical fix, but may cause small physics changes due to the correction of the inadvertent sorts.

### CODE REVIEW

**Comment by clacaputo** [comment]
enable profiling

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
type muon

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
