### PR TITLE
Fix synchronization in ContextState test

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

@fwyzard mentioned the `testHeterogeneousCoreCUDACore` unit test was segfaulting on a specific Power9 machine after the `ContextState` test section in a way that hinted towards a problem in how TBB was being used. The existing code indeed could destruct the `task_group` while it was still being used in an `task_arena::enqueue()`'d task. This PR fixes the synchronization problem in the test.

#### PR validation:

The unit test runs on lxplus-gpu and on the Power9 machine @fwyzard had access to.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test for el8_ppc64le_gcc11

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
