### PR TITLE
Add decay files and particle list files for BPH.

### PR DESCRIPTION
**Pull request by heppye**
Add decay files and particle list files for BPH.

### CODE REVIEW

**Comment by covarell** [comment]
For DECAY_NOLONGLIFE_Bstar.dec, the only difference is to add more B* particles, or are you changing their decay modes? In the first case, it should be sufficient to replace the original one

**Comment by heppye** [comment]
@covarell , in DECAY_NOLONGLIFE_Bstar.dec, some of the bstar decay modes were commented out. Otherwise, some spin dependent processes could not be passed since the spin has been changed in *.pdl.

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
I approved (although I thought the spins of B* states were well established...)

**Comment by heppye** [comment]
if i understand correctly, the analysis team actually 'hacked' the bstar to a possible new structure.

**Comment by covarell** [comment]
+1

**Comment by heppye** [comment]
@davidlange6 @cmsbuild , the test error 'cmsRun /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_X_2016-05-08-0000/src/PhysicsTools/PatAlgos/test/IntegrationTest_cfg.py : FAILED - time: date Tue May 10 10:31:23 2016-date Tue May 10 10:30:13 2016 s - exit: 23552' might not relate to the BPH patches. Local tests show those files are ok. Could you please have a look? Thanks.

**Comment by covarell** [comment]
Is there something preventing this to be merged? As Ye mentioned, we see the failure in tests in many 53X PRs but are unrelated. Thanks!

**Comment by perrozzi** [comment]
dear all, this PR has become extremely urgent. please merge asap

**Comment by perrozzi** [comment]
here is another reminder

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
The contents added by this PR are now part of CMSSW_5_3_33 via cmssw-data/GeneratorInterface-EvtGenInterface data directory. Please let me know if there is any mistake.

For next time, as I already discussed with Luca, moving forward these small dec files need to move into python configuration (requiring some code development) so that they can be easily added via the standard generator production area fragments. Requiring a CMSSW release for each new decay channel that CMS needs MC samples to study is clearly not a sustainable situation.

**Pull request closed without merging**
