### PR TITLE
[12_4_X] Fix for printouts with special (for python) chars

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38140
Fixes the  listing functions of `conddb` from command line.

#### PR validation:
Master PR is alredy integrated in CMSSW_12_5_0_pre2 and the `conddb` command works as expected.

#### Backport:
Backport of #38140

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
backport of #38140

**Comment by francescobrivio** [comment]
test parameters:

 - addpkg = CondTools

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+1

 - failure in the unittest is know and unrelated to this PR, see also the same comment in the master PR: https://github.com/cms-sw/cmssw/pull/38140#issuecomment-1142215204

**Comment by perrotta** [comment]
+1

**Pull request merged**
