### PR TITLE
Added links to inspect bin by bin comparison with a raw rootjs viewer

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Sometimes there are changes to DQM files that are not fully visualised
by the DQM GUI. For example when efficiency flag was added/removed or
when a QT test result changes but the ME that was tested does not. This
change allows to inspect resulting comparison files without treating them as DQM files.

#### PR validation:

PR vas validated locally with the Development DQM GUI.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge
(for some reason the +1 did not work)

**Pull request merged**
