### PR TITLE
Fix heap-buffer-overflow in OnlineDQMDigiAD (#42445)

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Apply fix from https://github.com/cms-sw/cmssw/issues/42445#issuecomment-1662397316

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by emanueleusai** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by emanueleusai** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by emanueleusai** [comment]
@rappoccio not sure how to proceed here, the relvals keep timing out

**Comment by iarspider** [comment]
please test

maybe this time it'll work...

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
test parameters:
- addpkg = DQM/Integration

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
@lwang046 could you please check the unit test failure: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0a8587/35445/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-hcal_dqm_sourceclient/testing.log ?

**Comment by muleina** [comment]
@lwang046 and @iarspider here is the fix for the issue:

// update ONNXOutputToDQMHistMap in OnlineDQMDigiAD_cmssw.cc 

std::vector<std::vector<std::vector<float>>> OnlineDQMDigiAD::ONNXOutputToDQMHistMap(
    const std::vector<std::vector<float>> &ad_model_output_vectors, const int numDepth, const int numDIeta, const int selOutputIdx) {
  // each output_vector is a serialized 3d hist map

  const std::vector<float> &output_vector = ad_model_output_vectors[selOutputIdx];
  std::vector<std::vector<float>> output_2d_vec = Map1DTo2DVector(output_vector, numDepth);

  std::vector<std::vector<std::vector<float>>> digiHcal3DHist;
  for (const std::vector<float> &output_vector_depth : output_2d_vec) {
    std::vector<std::vector<float>> digiHcal2DHist_depth = Map1DTo2DVector(output_vector_depth, numDIeta);
    digiHcal3DHist.push_back(digiHcal2DHist_depth);
  }

//update header of ONNXOutputToDQMHistMap in OnlineDQMDigiAD_cmssw.h

  std::vector<std::vector<std::vector<float>>> ONNXOutputToDQMHistMap(
      const std::vector<std::vector<float>> &ad_model_output_vectors, const int numDepth, const int numDIeta=64, const int selOutputIdx=7);


// update code in HcalMLTask.cc: Line 240-243

  std::vector<std::vector<std::vector<float>>> digiHcal3DHist_ANOMALY_FLAG_HB =
      dqmadObj_HB->ONNXOutputToDQMHistMap(ad_HBmodel_output_vectors, 4, 64, 7);
  std::vector<std::vector<std::vector<float>>> digiHcal3DHist_ANOMALY_FLAG_HE =
      dqmadObj_HE->ONNXOutputToDQMHistMap(ad_HEmodel_output_vectors, 7, 64, 7);

**Comment by iarspider** [comment]
@muleina could you please check if I got your changes right in [the last commit](https://github.com/cms-sw/cmssw/pull/42756/commits/af1a2f6a57cd86d698549cbb375dd1aa8742af48)?

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
I have cleaned up the commit history, no need to retest.

**Comment by iarspider** [comment]
please test for CMSSW_13_3_ASAN_X

**Comment by iarspider** [comment]
[Unit test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0a8587/35489/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-hcal_dqm_sourceclient/testing.log) no longer fails. @cms-sw/dqm-l2 could you please review and sign?

**Comment by smuzaffar** [comment]
please test

run tests for production IB/arch

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
