### PR TITLE
prod relval wfs: miniAOD from AODSIM (fwd port)

### PR DESCRIPTION
**Pull request by franzoni**
prod workflows output AODSIM (and not also RECO), make miniAOD from it
on top of #8322

### CODE REVIEW

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
+1

**Comment by franzoni** [comment]
+1
on top of #8322
the only workflows affected (1301, 1302, 1303) run happily

**Comment by davidlange6** [comment]
+1

**Pull request merged**
