### PR TITLE
Revert "migrating to multithreading of RPCPointProducer" (76X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Reverts cms-sw/cmssw#9760

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
I am using this PR to check whether the problem is indeed from #9760

**Comment by Martin-Grunewald** [comment]
@smuzaffar @nclopezo
Also here: Looks like cmsbot is in a loop stuck here, sending messages every 10 mins on "PR updated" while this is certainly not the case

**Comment by smuzaffar** [comment]
The login in the cms-bot is that it ignores all the comments which are made before the last commit timestamp. For some reason, you last commit has future timestamp.
In this case, the commit  
https://github.com/Martin-Grunewald/cmssw/commit/5ad58c463f87c438e464e39f433a8182a7f0ff36
tells that is is updated just now and that is why cmd-bot is ignoring its previous comments and putting the new one. Looks like a bug in github, I will check with github support to see if this can be avoided. For one only thing we can do is to close these PRs and generate new one

**Comment by smuzaffar** [comment]
looks like the time stamp for the last commit is not in past, so I am enabling cmd-bot again to process the PRs. You might get one more message from cmd-bot for these PRs.

**Comment by Martin-Grunewald** [comment]
@Dr15Jones @HuguesBrun @davidlange6
Just to wrap this up, also here I can confirm that this revert-PR fixes the problem I observe in 76X!
Both PRs are merged, thanks!

**Pull request merged**
