### PR TITLE
[QGL, JMENanoAOD] Backport of #40667 (PUPPI-compatible QGTagger producer) to 12_6_X 

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #40667 

#### Original PR description:

The main goal of this PR is to modify QGTagger producer (used to compute Quark-Gluon (QG) Likelihood) so that it is compatible with PUPPI jets. The `QGTagger` calculates three input variables, used to compute the likelihood, from PF constituents of jets. The changes in this PR allows the QGTagger to compute the input variables with PUPPI weights applied on the PF constituents by accessing the weights from the provided `ValueMap<float>`. This can also be done for any constituents weights, not just PUPPI.  Additionally, this PR makes it optional to not compute the likelihood and calculate just the three input variables for users who wants only them. 

With these modifications of the QGTagger, it should not affect CHS jets so we do not expect to see any change to the output of workflows. The QGTagger is currently scheduled to run only for AK4 CHS jets at the MiniAOD and (Run-2) NanoAOD production level.

Other changes:
- some fixes for JMENanoAOD. 
- fine-tune histograms in nanoDQM for JMENano.

#### Backport PR validation:
- Validation plots comparing the input variables before and after the fix can be found in this JMAR meeting [contribution](https://indico.cern.ch/event/1245910/#7-virtual-quark-gluon-likeliho). 
- passes reMiniAOD and reNanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 1325.518,2500.312`
- passes the JMENano workflows: `runTheMatrix.py -i all --ibeos -l 10224.15,11024.15,25202.15,11634.15`

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40667

**Comment by perrotta** [comment]
+1
- As agreed during the ORP on Feb 14, see minutes in the agenda https://indico.cern.ch/event/1252063/

**Pull request merged**
