### PR TITLE
Fix clang warnings alignment 80X (Backport of #14875)

### PR DESCRIPTION
**Pull request by ghellwig**
Fixes all clang warning originating from the `Alignment` code, except this one

```
${CMSSW_BASE}/src/Alignment/CocoaFit/src/MatrixMeschach.cc:68:8: warning: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Wtautological-undefined-compare]
  if ( this == 0 ) {
       ^~~~    ~
```

I did not want to remove this "protection" because some not well-defined code might rely on this.

Backport of #14875

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig 
the error reported by the bot is:
```
----- Begin Fatal Exception 14-Jun-2016 16:39:36 CEST-----------------------
An exception of category 'WrongPluginLoaded' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PCLTrackerAlProducer label='SiPixelAliMilleAlignmentProducer'
Exception Message:
The plugin 'MillePedeAlignmentAlgorithm' should have been loaded from
 '/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-06-12-2300/lib/slc6_amd64_gcc530/pluginAlignmentMillePedeAlignmentAlgorithmAuto.so'
 but instead it was already loaded from
 '/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-06-12-2300/lib/slc6_amd64_gcc530/pluginAlignmentPCLTrackerAlignmentProducerPlugin.so'
 because some other plugin was loaded from the latter loadables.
To work around the problem the plugin 'MillePedeAlignmentAlgorithm' should only be defined in one of these loadables.
----- End Fatal Exception -------------------------------------------------
```

**Comment by ghellwig** [comment]
@mmusich looking into this...
putting it on hold (and also the 81X PR)

**Comment by ghellwig** [comment]
hold

**Comment by ghellwig** [comment]
unhold

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@davidlange6 I see the following warning in the compilation:
```
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-06-14-2300/src/Alignment/CommonAlignmentProducer/plugins/FakeAlignmentSource.cc:28:54: warning: /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-06-14-2300/src/FWCore/Framework/interface/SourceFactory.h is shorter than expected
```
This also floods the clang output in the 81X PR. I think this should be fixed, right?

**Comment by ghellwig** [comment]
@davidlange6 I see the following warning in the compilation:
```
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-06-14-2300/src/Alignment/CommonAlignmentProducer/plugins/FakeAlignmentSource.cc:28:54: warning: /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-06-14-2300/src/FWCore/Framework/interface/SourceFactory.h is shorter than expected
```
This also floods the clang output in the 81X PR. I think this should be fixed, right?

**Comment by davidlange6** [comment]
looking, but btw, how can this==0 ever be true? and btw2, why change 5000 lines of whitespace?

**Comment by davidlange6** [comment]
please test 
(seems a cvmfs glitch?)

**Comment by ghellwig** [comment]
> looking, but btw, how can this==0 ever be true? and btw2, why change 5000 lines of whitespace?

@davidlange6 I am not sure, but maybe somewhere in the code (did not check it yet) someone is dereferencing a nullptr and tries to assign a new value to it.
Concerning the whitespace: I changed the file encoding from DOS to Unix as is the standard, right?
In some of the files, that I converted (always in a separate commit) it was even a mix.

**Comment by ghellwig** [comment]
please test

**Comment by davidlange6** [comment]
I think this can explain the reason for the chang warning (and why its a valid warning): http://stackoverflow.com/questions/1844005/checking-if-this-is-null

**Comment by ghellwig** [comment]
@davidlange6 I agree that it is a valid warning, that's why I explicitely mentioned it in the PR description. Probably an assert would be better here, as I learned from [your link](http://stackoverflow.com/questions/1844005/checking-if-this-is-null)
@mmusich I think we should open an issue and assign the appropriate person (who?) from muon alignment to it, right?

**Comment by mmusich** [comment]
@ghellwig I can contact privately Zoltan who I think is the only regular user of that code. I am not aware of him being on gitHub...

**Comment by mmusich** [comment]
@cmsbuild please test
let's try once again

**Comment by ghellwig** [comment]
@mmusich David also tried it for the 81X version w/o success, but he merged it anyways

**Comment by mmusich** [comment]
+1

**Pull request merged**
