### PR TITLE
CTPPS: new CondFormats related to TOTEM RP raw data and digi - backport of #13838

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #13838 from CMSSW 81X

2nd pull request out of 3 related to TOTEM RP raw-data unpacking and raw-to-digi conversion.

Validation config included in the 3rd pull request (EventFilter).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last iteration of tests got stuck

@mmusich @ggovi 
your attention to this is needed
The PR is supposed to be the same change as in 81X

**Comment by davidlange6** [comment]
@ggovi , @mmusich -please comment today if you have issues with this PR. Thanks

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Pull request merged**
