### PR TITLE
Add full5x5 shower shape block to non-GED photons producer

### PR DESCRIPTION
**Pull request by harmonicoscillator**
76X backport of #12085

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@slava77, @cvuosalo - what is the status of this PR?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12087 39868528c9daf3cbc5e945371314d8e00661a2cd

For Heavy Ions, adding full5x5 shower shape to non-GED photons. #12086 and #12085 are the 75X and 80X versions of this PR, and they have already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-11-04-1100 show no significant differences, except for the expected addition of the shower shapes.

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
