### PR TITLE
HLTTauRefProducer: bugfix

### PR DESCRIPTION
**Pull request by slehti**
HLTTauRefProducer: fixed selection of reference taus with nonexistent discriminators

### CODE REVIEW

**Comment by slehti** [comment]
Pushed a commit containing update on the reference tau selection to the HLTTauRefProducer_BugFix_80X branch.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@slehti @deguio - is there a quick way to motivate this change of behavior?

**Comment by slehti** [comment]
The intended change of behavior: if there is something wrong with the offline tau selection, like an obsolete discriminator being used, no offline tau is found and the DQM plots are empty.

**Comment by davidlange6** [comment]
+1
Thanks!

**Pull request merged**
