### PR TITLE
Migrate consumesMany() to edm::GetterOfProducts() in EgammaHLTExtraProducer

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:
Based on PR #40167 .
Migrate EgammaHLTExtraProducer away from consumesMany() to use edm::GetterOfProducts().

#### PR validation:
Tested in CMSSW_13_0_0_pre3, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by missirol** [comment]
@jeongeun, the review won't start until the PR passes the "code-checks" (see above).

**Comment by missirol** [comment]
> @jeongeun, the review won't start until the PR passes the "code-checks" (see above).

@jeongeun , please see above.

**Comment by missirol** [comment]
please test

Fwiw, I doubt this producer is used by any of the wfs in `runTheMatrix.py`.

> Tested in CMSSW_13_0_0_pre3, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@jeongeun , the implementation looks okay to me. Did you also test explicitly the producer `EgammaHLTExtraProducer` in some type of dedicated test?

**Comment by missirol** [comment]
+hlt

Maybe not explicitly tested (nor used in production), but the implementation looks okay.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping.

**Comment by perrotta** [comment]
As far as I understand, the updated producer had never been actually tested.
Is there a way to verify that after the modifications at least the code can still run? E.g. inserting it in an ad hoc HLT path for test?

**Comment by Sam-Harper** [comment]
I'll do it (was going to do it regardless), using this producer from some studies right now anyways. Should be done by tomorrow

**Comment by perrotta** [comment]
> I'll do it (was going to do it regardless), using this producer from some studies right now anyways. Should be done by tomorrow

Thank you Sam!

**Comment by Sam-Harper** [comment]
I tested this in  CMSSW_13_0_0_pre3 and it seems to work as expected. The module runs and produces the correct collection (which is correctly reading many E/gamma collections)
```
scram proj -n CMSSW_1300pre3_EgHLTExtra CMSSW CMSSW_13_0_0_pre3
cd CMSSW_1300pre3_EgHLTExtra/src/
cmsenv
git cms-init

git cms-merge-topic Sam-Harper:EGHLTCustomisation_1230pre6
git cms-merge-topic jeongeun:remove-consumesMany
scram b -j 4
hltGetConfiguration /users/sharper/2022/egamma/EgOpen1300GRunV5 --globaltag 126X_dataRun3_HLT_v1 --data --input /store/data/Run2022G/EGamma/RAW/v1/000/362/720/00000/621514aa-0966-46c5-a960-c9e5a3ee551f.root --customise HLTrigger/Configuration/customizeHLTforEGamma.customiseEGammaMenuDev > hlt.py
cmsRun hlt.py
```

I checked the variables are being filled (they appear to be) and are idenitcal for at least one

image


So I would say this is good to go

**Comment by perrotta** [comment]
+1
- Thank you @Sam-Harper for the validation!

**Comment by Sam-Harper** [comment]
> +1
> 
> * Thank you @Sam-Harper for the validation!

No worries, thank you for raising the issue so we are sure this wouldnt be broken by the change :)  I and other folks do use this module a lot :)

**Pull request merged**
