### PR TITLE
Get PhysicsTools/TensorFlow to compile with optimization off

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

PhysicsTools/TensorFlow doesn't compile with optimization off.  Compiling with
```
USER_CXXFLAGS="-g -O0" scram b
```
results in many "integer expressions of different signedness" warnings that we promote to errors:
```
/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/tensorflow/2.3.1/include/tensorflow/core/platform/default/logging.h:370:29: error: comparison of integer expressions of different signedness: 'const size_t' {aka 'const long unsigned int'} and int' [-Werror=sign-compare]
  370 |     if (TF_PREDICT_FALSE(v2 >= std::numeric_limits<int>::max())) {        \
      |                          ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/tensorflow/2.3.1/include/tensorflow/core/platform/macros.h:83:47: note: in definition of macro 'TF_PREDICT_FALSE'
   83 | #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
      |                                               ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/tensorflow/2.3.1/include/tensorflow/core/platform/default/logging.h:381:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
  381 | TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
      | ^~~~~~~~~~~~~~~~~~~~~~~
```
Apparently with the optimizer on these get optimized away and hence don't trigger the diagnostic.  This PR turns off the GCC sign-compare diagnostic for the TensorFlow include files.

#### PR validation:

Checked compilation following a "git cms-checkdeps -a".  Also checked that CLANG does not need any similar pragma (it doesn't issue a warning), and doesn't issue an error or warning for the GCC pragmas.  Since this is a purely technical change it shouldn't result in any performance changes.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
is it practical to pass this as an issue upstream to the TF?

Shouldn't we still pay attention to the warning if it's for an existing code?

Can we add a patch to the TF external instead?

**Comment by slava77** [comment]
> Can we add a patch to the TF external instead?

by a patch I meant using e.g. `std::numeric_limits<size_t>` in the case provided in the PR description 
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/core/platform/default/logging.h#L368-L370

**Comment by dan131riley** [comment]
> > Can we add a patch to the TF external instead?
> by a patch I meant using e.g. `std::numeric_limits<size_t>` in the case provided in the PR description
> https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/core/platform/default/logging.h#L368-L370

`std::numeric_limits<size_t>` would defeat the point of the test, which is to see if the value of v2 will fit into an int.  What we'd have to do is add a static cast to size_t.

**Comment by dan131riley** [comment]
> is it practical to pass this as an issue upstream to the TF?

Maybe, don't know how much attention it would get.  Many (most?) programmers don't consider signed to unsigned comparisons a problem.

> Shouldn't we still pay attention to the warning if it's for an existing code?

If it were just a warning I'd leave it, but we promote signed/unsigned mismatch to an error, so the code will not compile with optimization turned off.  I don't know of a way to turn the diagnostic back into a warning instead of turning it off entirely.
 
> Can we add a patch to the TF external instead?

I suppose.  I was hoping to avoid spending a lot of time on this...

**Comment by dan131riley** [comment]
> I don't know of a way to turn the diagnostic back into a warning instead of turning it off entirely.

Reading the docs a little more carefully, it is easy to set the diagnostic back to a warning, so I've updated the PR to do so instead of turning it off entirely.

**Comment by davidlange6** [comment]
It looks like usual cms practice to avoid warnings is to mark the external as being a system external. (Eg, for root)

**Comment by dan131riley** [comment]
> It looks like usual cms practice to avoid warnings is to mark the external as being a system external. (Eg, for root)

Ok, could do that too, it's a simple change to the toolfile spec, but it goes in the opposite directly from Slava (I just want it to compile with optimization off).

**Comment by slava77** [comment]
> > It looks like usual cms practice to avoid warnings is to mark the external as being a system external. (Eg, for root)
> 
> Ok, could do that too, it's a simple change to the toolfile spec, but it goes in the opposite directly from Slava (I just want it to compile with optimization off).

the goal of my comment/suggestion was to have the least impactful change in the CMSSW source code.
I was not aware of the "system external" option.

**Comment by dan131riley** [comment]
> the goal of my comment/suggestion was to have the least impactful change in the CMSSW source code.
> I was not aware of the "system external" option.

I wasn't either.  I will close this PR and make a new one on cmsdist to update the tool file, thanks @davidlange6

**Pull request closed without merging**
