### PR TITLE
Add explicit raw collection label for L1TRawToDigi (10_3_X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
Backport of #25193

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@bi-ran @icali

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic @thomreis this looks to work in master. Do you have any doubt about merging it?

**Comment by fabiocos** [comment]
@rekovic @thomreis this looks to work in master. Do you have any doubt about merging it?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@rekovic @thomreis please sign this for reference, or comment for possible further updates

**Pull request merged**
