### PR TITLE
fix num and den selection for the fractionOfGoodTracks plots [tracking DQM]

### PR DESCRIPTION
**Pull request by mtosi**
as requested/suggested by tracking POG ( @VinInn @rovere @makortel )
I've just updated/fixed the selection applied to the numerator and denominator used for the definition of "good tracks" in the sub set of plots of the tracking DQM

I tested this update by running
`runTheMatrix -l limited`
and I encouraged few failing jobs w/ exit code 256
which should not be related to this PR ... right ?

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
