### PR TITLE
Add consumes to CTPPSInterpolatedOpticalFunctionsESSource

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Call consumes and use the ESGetTokens.

#### PR validation:

Ran a runTheMatrix.py workflow using this module and it works.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please review this pull request. It is needed for waiting framework changes.

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
