### PR TITLE
adding unit test for jupyter notebook startup

### PR DESCRIPTION
**Pull request by davidlange6**
will work correctly once cms-sw/cmsdist/#4478 is merged

@smuzaffar  - any objections to the way an open port is found? I've checked that the timeout does cleanup the process such that the ports freed.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#4478

**Comment by smuzaffar** [comment]
@davidlange6 , we do not have `netstat` installed on arm64 and docker. Try to use `/etc/services` file.

**Comment by davidlange6** [comment]
> On Nov 5, 2018, at 4:34 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:
> 
> @davidlange6 , we do not have netstat installed on arm64 and docker. Try to use /etc/services file.

I tried, but I guess I need to learn more

 at least using jupyter as an example, it does not show up in /etc/services whereas netstat knows about it

[dlange@cmsdev15 test]$ netstat -tulpn | grep LIST | grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
[dlange@cmsdev15 test]$ grep 8080 /etc/services
webcache        8080/tcp        http-alt        # WWW caching service
webcache        8080/udp        http-alt        # WWW caching service

changes to

[dlange@cmsdev15 test]$ netstat -tulpn | grep LIST | grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8080              0.0.0.0:*                   LISTEN      30780/python        
tcp        0      0 ::1:8080                    :::*                        LISTEN      30780/python        
[dlange@cmsdev15 test]$ grep 8080 /etc/services
webcache        8080/tcp        http-alt        # WWW caching service
webcache        8080/udp        http-alt        # WWW caching service

when running a jupyter notebook.

**Comment by davidlange6** [comment]
ok - it looks like I can get what I wanted from /proc/net/tcp.

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
please test
lastest IB contains the external needed.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
