### PR TITLE
Fix for the recently updated HI event content

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

In the restructuring campaign for the reconstruction related event contents, PR #29990 updated the HI ones. In doing so, however, we overlooked the fact that all new event contents started with a "drop *" statement: when more than one of them is put in a row, the "drop *" statement of the second one reset the previous content.

This was noticed in the IB since CMSSW_11_2_X_2020-06-02-2300, and reported in issue #30095.

This PR reports back those event contents which were broken in the previous implementation, and solves that issue.

@jeongeun 

#### PR validation:

Workflows 140.0 and 150.0 now run without errors

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 140,150

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
+1
- It fixes the EventContent for HI workflows, that was broken after merging #29990
- HI workflows failing in IB now succeed. 
- Jenkins tests pass without changes in all other workflows

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
