### PR TITLE
Adding vtx smearing parameters for 2015 Beta*=90m for FSQ analyses

### PR DESCRIPTION
**Pull request by franzoni**
Including in 76x as it might ease/speed up relval for RECO BS measurement
From 2015B 3.8T data, beta*=90m (700 bunches fills)
Centroid absolute positions extracted from 700 bunches fills 4499-4511:

```
X = 0.068357 cm
Y = 0.109159 cm
Z = 0.131811 cm
```

BPIX absolute position extracted from Prompt Reco alignment of run 259352

```
X = -0.041651 cm
Y = -0.199279 cm
Z = -0.565093 cm
```

Emittance has been calculated to match a BeamWidth of O(10um) with: [https://lpc.web.cern.ch/lumi2.html](https://lpc.web.cern.ch/lumi2.html)

@fabozzi @hengne @mmusich @rmanzoni @sarafiorendi

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
locally tested with:

```
cmsDriver.py    MinBias_13TeV_pythia8_TuneCUETP8M1_cfi --conditions auto:run2_mc -n 10 --era Run2_25ns --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic100ns13TeVCollisionBetaStar90m 15Collision  -n 1 --fileout file:step1.root --no_exec  --python_filename Realistic100ns13TeVCollisionBetaStar90m.py

cmsDriver.py    MinBias_13TeV_pythia8_TuneCUETP8M1_cfi --conditions auto:run2_mc -n 10 --era Run2_25ns --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic100ns13TeVCollisionBetaStar90mLowBunches15Collision  -n 1 --fileout file:step1.root --no_exec  --python_filename Realistic100ns13TeVCollisionBetaStar90mLowBunches.py

cmsDriver.py    MinBias_13TeV_pythia8_TuneCUETP8M1_cfi --conditions auto:run2_mc -n 10 --era Run2_25ns --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic100ns13TeVCollisionBetaStar90mLowBunches  -n 1 --fileout file:step1.root --no_exec  --python_filename Realistic100ns13TeVCollisionBetaStar90mLowBunches.py

```

**Comment by franzoni** [comment]
+1

The tests don't access the new vtx smearing scenarios. The cmsDriver of above do.

**Comment by civanch** [comment]
+1

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
removed stale content which was inaccessible anyway already at commit fc1c14265750b6edbfd465b84e4b972b9cbe1a2c

**Comment by civanch** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
