### PR TITLE
Updated configurations in DPGAnalysis to new MessageLogger syntax

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All configurations in DPGAnalysis subsystem which explicitly create a MessageLogger have been converted to the new syntax.
#### PR validation:

All files were passed to `python` and no failures as a result of these change were seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1
There are static errors, in principle unrelated to this PR

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
kind reminder @cms-sw/pdmv-l2

**Comment by chayanit** [comment]
+1

**Pull request merged**
