### PR TITLE
[14_0_X] Remove tensorflow::setLogging() as thread-unsafe

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46065

#### PR validation:

None beyond https://github.com/cms-sw/cmssw/pull/46065

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/46065 (following request in https://github.com/cms-sw/cmssw/pull/46065#issuecomment-2363258207)

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmsdist/pull/9432

**Comment by mmusich** [comment]
+hlt

**Comment by valsdav** [comment]
+ml

**Comment by Moanwar** [comment]
+Upgrade

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46065

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
