### PR TITLE
Modernized RecoTauTag/HLTProducers modules

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed use of SealModule.cc
- moved plugin registration to individual module .cc files
- changed legacy modules to thread-friendly versions
- minor code improvements

#### PR validation:

Code compiles and does not generate any CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I had noticed this why recompiling the 'world' where the compiler was using a lot of memory (don't remember exactly how much now) while compiling this package. Now I don't see anything over 2 GB.

**Comment by missirol** [comment]
+hlt

 - side note: pre-PR and post-PR, `L2TauPixelTrackMatch` is not defined as a plugin (`DEFINE_FWK_MODULE`), for reasons I don't know.

**Comment by perrotta** [comment]
+1

**Pull request merged**
