### PR TITLE
MTD Sensitive Detector: make it independent on DDD

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR removes the residual dependency of the ```MtdSD``` class on DDD, which was used just to print in a LogInfo message the numerical code assigned to Barrel or Endcap as SpecPar. At the same time the old ```FastTimerSD``` class, used in the very first simulation of MTD (no more available) is removed, and the corresponding production cuts and sensitive volume definitions in ```Geometry/HGCalSimData``` are deleted.

The residual dependency of ```SimG4CMS/Forward``` on DDD is concentrated in Zdc. But as far as I can see the ```ZdcShowerLibrary``` doe not really use the ```DDCompactView```  passed through the constructor, so this dependency does not look real and could be removed: @bsunanda @civanch do you agree?

#### PR validation:

Test wf 23234.0 (scenario D49) step 1 runs smoothly providing the identical same set of Sim and Calo hits, as shown by https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/test/runSimHitCaloHitDumper_cfg.py

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@civanch @cvuosalo as ```FastTimerSD``` is no more used nor available, I do not see the point to maintain it in the ```g4SimHits``` configuration. In my understanding this should not affect any backward compatibility.

**Comment by fabiocos** [comment]
please test

in my private test nothing is changing as expected

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
I would agree to drop unused SD code.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
