### PR TITLE
Update fix76

### PR DESCRIPTION
**Pull request by mrcarver**
DQM module fixes for SUSY JetIdCleaned paths (CMSHLT-482:Reopened)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please change the title to something meaningful
thanks,
F.

**Comment by smuzaffar** [comment]
please test

**Comment by mrcarver** [comment]
Hi All,

I've pushed updates to remedy the matrix tests. Please retest, thanks.

Matt

**Comment by deguio** [comment]
please test

**Pull request closed without merging**
