### PR TITLE
Remove uses of input sources that no longer exist.

### PR DESCRIPTION
**Pull request by wmtan**
I discovered that there are a large number of python config files that cannot possibly be run because the input sources used no longer exist.  In particular, most of the generators were changed from sources to producers three years ago, and the old source classes were removed almost three years ago (Nov 2012).   I am working on a generator feature that requires looking at a lot of config files that use generators, so it will make life easier if these obsolete config files that cannot possibly be used are removed from the release.  The few changes to files not removed in this PR are trivial, namely removing or fixing obsolete comments or message wording.
This PR removes over 5500 source lines from CMSSW!

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
maybe this time it completes

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@cmsbuild @davidlange6 @Dr15Jones 
The link in the previous comment, which purports to show an issue with git-cms-merge-topic, is empty
(at least for me).  I can do a wget on it, but all that retrieves is an html file with a lot of meaningless content that has nothing to do with git.
So, we are at an impasse here.  Please provide meaningful information as to what the problem is.

**Comment by slava77** [comment]
@wmtan please ignore these
it was me trying to get the tests to run

**Comment by ianna** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
