### PR TITLE
Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1.

### PR DESCRIPTION
**Pull request by sifuluo**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/37188

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37188

**Comment by perrotta** [comment]
+1
- Succefully merged in master since CMSSW_12_4_X_2022-03-11-2300

**Pull request merged**
