### PR TITLE
GenParticles2HepMC for MiniAOD for 80X

### PR DESCRIPTION
**Pull request by jhgoh**
This PR is backport of #18115 , to be used in the Rivet analyses based on 80X releases.

This is supposed to run at the user analysis level, therefore it does not change the central workflows.

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by jhgoh** [comment]
updated to be synchronized with #18115 , use simple std::vector and std::find algorithm while assigning signal vertex.

**Comment by perrozzi** [comment]
please test

**Comment by jhgoh** [comment]
Could this PR be merged?

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by jhgoh** [comment]
Could this merged at some point?

**Comment by intrepid42** [comment]
Hi John, the BuildFile.xml has a trivial conflict now

**Comment by jhgoh** [comment]
@intrepid42 thank you for the alert :-)

**Comment by perrozzi** [comment]
please test

**Comment by jhgoh** [comment]
I believe the error is not relevent to this PR.

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by intrepid42** [comment]
@davidlange6 Could you merge this, please? It is required for running the ParticleLevelProducer (#18402) on MiniAOD

**Comment by intrepid42** [comment]
And it was already merged into master: #18115

**Comment by davidlange6** [comment]
+1

**Pull request merged**
