### PR TITLE
[cxxmodules] Remove the layering violation in BTauReco.

### PR DESCRIPTION
**Pull request by vgvassilev**
PatCandidates depends on BTauReco, not vice-versa.

This patch should allow us to enable the PatCandidates module.

Part of #15248 

cc: @davidlange6, @smuzaffar, @oshadura.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- "DataFormats/JetReco/interface/Jet.h" (which defines ```reco::Jet```)is included in "DataFormats/BTauReco/interface/BaseTagInfo.h"
- In "DataFormats/BTauReco/interface/FeaturesTagInfo.h" the ```Jet``` class is referenced within the ```namespace reco```, and therefore the ```pat::Jet``` is not accessed: the removed include was not needed, in fact
- Jenkins tests pass and show no difference

**Comment by davidlange6** [comment]
hi all - any further comments on this simple PR?

**Comment by silviodonato** [comment]
merge
@santocch please have a look later

**Comment by santocch** [comment]
+1

**Pull request merged**
