### PR TITLE
new vtx hist and updated dip file for LHC pub

### PR DESCRIPTION
**Pull request by sushilchauhan**
two new hist for N Vtx vs LS, dip file updated for correct LHC pub for luminous region (already installed by WBM team and running)

### CODE REVIEW

**Comment by deguio** [comment]
ciao @sushilchauhan 
this PR should be submitted to 75 and 76 as well.
thanks,
F.

**Comment by deguio** [comment]
please submit to 76 as well.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
