### PR TITLE
Particle gain multi run harvesting74 x (backport of #10680)

### PR DESCRIPTION
**Pull request by quertenmont**
This contains very important bugfix that are needed for PCL

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by quertenmont** [comment]
Is this going to be approved finally?
After 4months ?

**Comment by franzoni** [comment]
hello @quertenmont,
is this still relevant ?

**Comment by boudoul** [comment]
Hello @franzoni , I fear it is not anymore (74x won't anymore take data...)

**Comment by quertenmont** [comment]
why won't it be relevant?
Beside the fact that approving a simple PR take a decade and that the release cycle has moved forward by several release ?
I am not responsible of this package anymore, so I don't care... but this PR review highlight a real failure of the system which I personaly find quite worysome.

**Comment by quertenmont** [comment]
@boudoul 
several of the improvements of this PR are not saved anywhere else than here...
So unless you want to move backward by months of development toward gain calibration at PCL,
I suggest somebody move this PR to more recent release and make sure it is approved in a timely way this time.

**Comment by boudoul** [comment]
the 76X version is merged, isnt' it ?
https://github.com/cms-sw/cmssw/pull/10680

**Comment by quertenmont** [comment]
ha... right!
Sorry, I got confused with the 75X version which was recently closed.

**Pull request closed without merging**
