### PR TITLE
Reorganize HcalNoiseSummary in hopes it might be space efficient

### PR DESCRIPTION
**Pull request by lgray**
Reorganize HcalNoiseSummary into a compressible format expect decreases in compressed file size.
Block together bools, ints, floats, doubles.

No physics change expected/observed.
Please let me know if I need to add iorules (if we want to backport this to 74X).

It would be useful to inform future contributors to this class that they should first do their testing in human readable blocks and then put the necessary variables in the appropriate block of datatypes.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray which tests do you have showing it's better?
For in memory compact result smaller types should go last to align to cache line size. 
For on disk, I don't see offhand how this can help in full split mode.

**Comment by lgray** [comment]
For disk, putting similar types with repeated values together, rather than constantly changing types, should improve the compression or at least cause it to settle more quickly.

Benchmarks coming in a few, PU mixing is slow today, at least from this lxplus node...

For memory ordering, noted, I can make that improvement.
I guess it would be just moving the floats to the end of the class since bools are usually stored in integers? Likewise, moving the RecVectors to the beginning?

**Comment by slava77** [comment]
But in full split, if I understand correctly, each value is in a separate basket compressed individually

**Comment by lgray** [comment]
If that's the case then there won't be any improvement, sure. 
Let me finish testing, you can ignore this PR for now.

**Comment by lgray** [comment]
failures seem to be from xrootd.

**Comment by lgray** [comment]
@slava77 indeed, no effect. Closing this.

**Pull request closed without merging**
