### PR TITLE
Run3-sim41 Add provision for testing the passive material

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the basic tools used to verify the scoring mechanism using GeantV. Addition of test for the passive materials.

#### PR validation:

Tested in private configurations and also used for Geant4/GeantV comparisons

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda can you propagate the changes I made (using tuples)? https://github.com/kpedro88/SimGVCore/compare/028f0fc...6158b3d

**Comment by kpedro88** [comment]
please test
thanks @bsunanda

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
