### PR TITLE
75x Fireworks: obsolete -- auto-detect configuration after opening first file 

### PR DESCRIPTION
**Pull request by alja**
This is forward port of  #11055

### CODE REVIEW

**Comment by alja** [comment]
I don't know where the branch conflicts come from. I made the changes in this Fireworks 6 files on  base of cmssw 7_5_X branch.

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
@alja - this does not merge - could you have a look?

**Comment by alja** [comment]
@davidlange6 I will look what could be the problem...

**Comment by alja** [comment]
Create a new reattempt #11148

**Pull request closed without merging**
