### PR TITLE
GTupdates_for_910pre3_L1O2OTags_HCAL2018Geo_PCL_TkAl_AlignableThresholds

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## RunI data

   * **RunI HLT processing** : [91X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v3) as [91X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_frozen_v3/91X_dataRun2_HLT_frozen_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html

   * **RunI Offline processing** : [91X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v3) as [91X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_v3/91X_dataRun2_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html
      * addition of new record with PCL alignable configurable thresholds for tracker alignment

## RunII data

   * **RunII HLTHI processing** : [91X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLTHI_frozen_v3) as [91X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLTHI_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLTHI_frozen_v3/91X_dataRun2_HLTHI_frozen_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html

   * **RunII HLT processing** : [91X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v3) as [91X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_frozen_v3/91X_dataRun2_HLT_frozen_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html

   * **RunII HLT relval processing** : [91X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_relval_v3) as [91X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_relval_v3/91X_dataRun2_HLT_relval_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html

   * **RunII Offline processing** : [91X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v3) as [91X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_v3/91X_dataRun2_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html
      * addition of new record with PCL alignable configurable thresholds for tracker alignment

   * **RunII Offline relval processing** : [91X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_relval_v3) as [91X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_relval_v3/91X_dataRun2_relval_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html
      * addition of new record with PCL alignable configurable thresholds for tracker alignment

   * **RunII Prompt processing** : [91X_dataRun2_PromptLike_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_PromptLike_v3) as [91X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_PromptLike_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_PromptLike_v3/91X_dataRun2_PromptLike_v1):
      * addition of L1 O2O caloParam and Muon Param tags https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878.html
      * addition of new record with PCL alignable configurable thresholds for tracker alignment
## Upgrade

   * **PhaseI 2017 cosmics peak scenario** : [91X_upgrade2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v3) as [91X_upgrade2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v3/91X_upgrade2017cosmics_realistic_peak_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html

   * **PhaseI 2017 cosmics scenario** : [91X_upgrade2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v3) as [91X_upgrade2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v3/91X_upgrade2017cosmics_realistic_deco_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html

   * **PhaseI 2017 design scenario** : [91X_upgrade2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v3) as [91X_upgrade2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_design_IdealBS_v3/91X_upgrade2017_design_IdealBS_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html

   * **PhaseI 2017 realistic scenario** : [91X_upgrade2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v3) as [91X_upgrade2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_realistic_v3/91X_upgrade2017_realistic_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html

   * **PhaseI 2018 cosmics scenario** : [91X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v3) as [91X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v3/91X_upgrade2018cosmics_realistic_deco_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html
      * Update of HCAL geometry : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2859.html

   * **PhaseI 2018 design scenario** : [91X_upgrade2018_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v3) as [91X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_design_IdealBS_v3/91X_upgrade2018_design_IdealBS_v2):
      * Update of HCAL geometry : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2859.html
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html

   * **PhaseI 2018 realistic scenario** : [91X_upgrade2018_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v3) as [91X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_realistic_v3/91X_upgrade2018_realistic_v2):
      * updates of Pixel local reco conditions : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2885.html
      * Update of HCAL geometry : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2859.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@veszpv @mmusich @kkotov @ianna @abdoulline FYI

**Comment by mmusich** [comment]
@arunhep @franzoni this will not work. 

I am expecting failure of wf 1001.0, due to a duplication of ESSource for the `AlignPCLThresholdsRcd` record.
You'll need first to remove (as I explicitly mentioned in private message and as well [here](https://github.com/cms-sw/cmssw/pull/18196#issue-219303721) the additional `ESSource` I added in  two files in order for the tests to pass:            
   * `Alignment/CommonAlignmentProducer/python/ALCARECOPromptCalibProdSiPixelAli_cff.py`    
   * `Alignment/CommonAlignmentProducer/python/AlcaSiPixelAliHarvester_cff.py` 

You are welcome to cherry-pick this commit : https://github.com/mmusich/cmssw/commit/d87f994d358b8addf22b807e73641dbaed62f271

**Comment by arunhep** [comment]
please abort

**Comment by mmusich** [comment]
@arunhep thanks!

**Comment by arunhep** [comment]
@cmsbuild please abort

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
hello @kkotov @rekovic @bortigno 
for info @Martin-Grunewald 

there's a failure in [this add on test 
](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18269/19017/addOnTests/hlt_data_Fake1/) coming from the L1 repack step.
My conclusion is that the caloparams tag put forward in this PR
does not cover 2015 well/accurately enough to pass this test.
 
Please read on for more details, and please advise as to whether this test is relevant on 2015 data and, if yes, whether you can provide an alternative tag covering 2015 history (we need this PR ready by Monday morning, or we'll have to descope the L1T updates).

The is the error is:

----- Begin Fatal Exception 08-Apr-2017 00:06:02 CEST-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 256677 lumi: 380 event: 396742586 stream: 1
   [1] Running path 'L1RePack_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------

The GT consumed by such workflow is [run2_hlt_Fake1](https://github.com/cms-sw/cmssw/blob/43b7789a52a5899a0e533668704fb660b2fb271c/Configuration/HLT/python/autoCondHLT.py#L47), which inherits the chances of [run2_hlt_relval](https://github.com/cms-sw/cmssw/blob/43b7789a52a5899a0e533668704fb660b2fb271c/Configuration/AlCa/python/autoCond.py#L37), [see this list of changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_relval_v2/91X_dataRun2_HLT_relval_v1). The relevant change, i gather, is L1TCaloParams_CRAFT09_hlt  => L1TCaloParams_Stage2v1_hlt	, see the difference in payloads and history [here]( https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/L1TCaloParams_CRAFT09_hlt/L1TCaloParams_Stage2v1_hlt) .
For the run number in question, 256677, the payload consumed goes 

   from: 25c2d4585dded80b2dda7f27254214d71aeba066 
   to: 75bc16eda4a6d3cf7c0aefcbf5548884ab4999ac

Can the history of 2015 be copied over from L1TCaloParams_CRAFT09_hlt to L1TCaloParams_Stage2v1_hlt  ?

**Comment by kkotov** [comment]
@franzoni , @rekovic : I'd suggest to simply  drop Stage1 modules from the chain. It is already a history now.

**Comment by mmusich** [comment]
@franzoni @kkotov I am not sure the exception you observe here is due to the change in the `CaloParams`, as it is seen also in other PRs where no L1T conditions are changed (e.g. [here](https://github.com/cms-sw/cmssw/pull/18271#issuecomment-292804430)). Would it be worth to re-trigger the tests?

**Comment by makortel** [comment]
@mmusich I tested #18271 with this PR (as there is a logical dependence), so any failure here is visible also there.

**Comment by mmusich** [comment]
@markotel ah, nice! I didn't know one could test multiple cmssw PR.

**Comment by arunhep** [comment]
please test

**Comment by kkotov** [comment]
Following Arun's request, I've merged the history of L1TCaloParams_CRAFT09_hlt and L1TCaloParams_Stage2v1_hlt into L1TCaloParams_Stage2v2_hlt (https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloParams_Stage2v2_hlt). The L1T O2O at p5 is pointed to continue the history of v2 tag.

**Comment by rekovic** [comment]
running with stpe `-s L1REPACK:GCTGT` invokes the Stage1 emulator, and should not depend on the O2O tags used for Stage2. L1T Stage1 setup is used for 2015, and L1T Stage2 is used starting in 2016

@kkotov 
It is correct to merge the history of L1TCaloParams_CRAFT09_hlt and L1TCaloParams_Stage2v1_hlt into one tag (i.e. L1TCaloParams_Stage2v2_hlt) but please adjust IOVs so that 
L1TCaloParams_CRAFT09_hlt ends with last run in 2015, and L1TCaloParams_Stage2v1_hlt starts with first run in 2016.

**Comment by kkotov** [comment]
@rekovic , yes, IOV takes care of disambiguation of the payloads for different run intervals. I don't know what is in the L1T Stage1 unit tests (that is why I would get rid of those for good), but if they ran with CRAFT09, they should now run fine with Stage2v2.

**Comment by franzoni** [comment]
Status report:

+ how to deploy a history for the **L1T tag caloparams** in a way which is correct and complete (covering also 2015 => will also fix the failing add-on test) has been agreed with  L1T group Thanks @kkotov @rekovic! The tag is in the making and will be integrated here by the end of today 

+ the changes in **2017-2018 to the pixel conditions** are visible in the plots. Impact also on tracking and most other downstream PO's . @tvami @veszpv 
+ We have one doubt about the implications of pixel changes : there  are changes inducted in SiStrip related quantities, most of which depend on tracking or track-length, which we can conceive stem from pixel-inldiuced changes to tracking (see plot attached fist, below); it's not clear to us why DigiADCs plots change as well, in several of the SiStrip mechanical partitions @dimattia @mmusich might you give us hints here, please ? 

+ we don't find changes induced by the **update of the HCALParameters_Geometry_91YV3** tag; Based on the [hn-description](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2859/1/1.html) we inferred the crashes is only rare (i.e. not at every event): what impact do we expect on the 10 events of the tests run here ? 
@ianna @bsunanda may you please advise ?


sistrip__mechanicalview_tib_summary_clusterchargepercmfromorigin_offtrack__tib

sistrip__mechanicalview_tec_minus_wheel_8_summary_digiadcs__tec__minus__wheel__8

**Comment by mmusich** [comment]
> We have one doubt about the implications of pixel changes : there are changes inducted in SiStrip related quantities, most of which depend on tracking or track-length, which we can conceive stem from pixel-inldiuced changes to tracking (see plot attached fist, below); it's not clear to us why DigiADCs plots change as well, in several of the SiStrip mechanical partitions 

please clarify which are the affected workflow (a link is missing)

**Comment by ianna** [comment]
@mmusich - https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18269/19017/addOnTests/hlt_data_Fake1/

**Comment by mmusich** [comment]
@ianna, I am referring to the difference observed by Giovanni in the Strip  DigiADCs, not to the failure of the addOn test due to the L1T calibrations.

**Comment by arunhep** [comment]
@mmusich 
e.g. for wf 10024 in 2017
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-09-2300+18269/19303/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/SiStrip_MechanicalView_TEC_MINUS_wheel_8.html

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-09-2300+18269/19303/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/SiStrip__MechanicalView_TIB_layer_2_Summary_DigiADCs__TIB__layer__2.png

similarly for 10824 in 2018:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-09-2300+18269/19303/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/SiStrip_MechanicalView_TEC_MINUS_wheel_1.html

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@mmusich @dimattia @ianna @bsunanda 
can you please share your thoughts to the comment by @franzoni https://github.com/cms-sw/cmssw/pull/18269#issuecomment-292929648
we want to report it tomorrow in orp.

**Comment by mmusich** [comment]
@arunhep 
in relation to your enquiry in comments https://github.com/cms-sw/cmssw/pull/18269#issuecomment-292929648 and https://github.com/cms-sw/cmssw/pull/18269#issuecomment-292934475 (i.e. the tiny change in the SiStrip DIGIs spectra) 
from quick look to the DQM code, those histograms shall be filled [here](https://github.com/cms-sw/cmssw/blob/CMSSW_9_1_X/DQM/SiStripMonitorDigi/src/SiStripMonitorDigi.cc#L682).

The configuration of the `SiStripMonitorDigi` module is defined [here](https://github.com/cms-sw/cmssw/blob/CMSSW_9_1_X/DQM/SiStripMonitorDigi/python/SiStripMonitorDigi_cfi.py), where I don't see any explicit dependence on Pixel conditions; @fioriNTU to confirm. 
Incidentally the module level plots should be switched-off by default in this view, so this is the lowest hierarchy level histogram for DIGIs. 

Also the DIGI collection [validation plots](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-10-1100+18269/19313/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/GlobalDigisV_SiStrips.html), seem to point to a genuine change in the Strip DIGIs.

Now, **at contrast with the description you provided**, for the PhaseI 2017 realistic scenario Global Tag there is at least one change involving the digitization step (namely via `SiPixelLorentzAngleSimRcd` that is consumed in the pixel digitizer) see [GT diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_realistic_v3/91X_upgrade2017_realistic_v2). I am wondering if we might be witnessing irreproducibilities inherent from random number generation processes stemming from different conditions input. I am adding @boudoul as _ad-interim_ Strip simulation contact.

**Comment by franzoni** [comment]
Thanks @mmusich, 
we navigated the code yesterday and reached the same conclusions on SiStripMonitorDigi.cc .

> from random number generation processes stemming from different conditions input

How far would the irreproducibility triggered by a change in digi conditions propagate (I have a limited understanding of the pseudo-random number generation ) ? Your hypothesis is supported by small perturbations to the [ECAL digi occupancy](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-09-2300+18269/19303/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/EcalBarrel_EBOccupancyTask.html) , though no analogous changes are found in the HcalDigiTask.

**Comment by abdoulline** [comment]
From HCAL side with the update of the HCALParameters_Geometry_91YV3 tag
we just expect to fix the crashes in L1 emulator for 2018 workflows, as Yana has correctly described
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2859/1/1.html

**Comment by mmusich** [comment]
> we navigated the code yesterday and reached the same conclusions on SiStripMonitorDigi.cc .

Nice! 

> How far would the irreproducibility triggered by a change in digi conditions propagate (I have a limited understanding of the pseudo-random number generation ) ? 

Not being a digitization expert I cannot judge and defer to those more savvy than I am in this respect. 
I can claim - though - that re-running exactly the same setup for wf 10024 but reverting the change in `SiPixelLorentzAngleSimRcd` in step3 via:

```python
process.GlobalTag = GlobalTag(process.GlobalTag, '91X_upgrade2017_realistic_v3', '')
process.GlobalTag.toGet.extend(
    cms.VPSet(cms.PSet(connect= cms.string("frontier://FrontierProd/CMS_CONDITIONS"),
                       record = cms.string("SiPixelLorentzAngleSimRcd"),
                       tag = cms.string("SiPixelLorentzAngleSim_phase1_mc_v1")
                       )
              )
    )
```
I am able to restore a bitwise identity with the previous spectra.

comparesistripdigis

**Comment by franzoni** [comment]
hello @mmusich 
thanks, we have josbs running exactly what test, running with [91X_upgrade2017_realistic_v3_PIXEL_RECO_UP_ONLY](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_realistic_v3/91X_upgrade2017_realistic_v3_PIXEL_RECO_UP_ONLY).

We've also found that the DIGI step of the workflow has a single instance of the [RandomNumberGeneratorService](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGeneration#RndmSeeds) , which supports your [original conjecture](https://github.com/cms-sw/cmssw/pull/18269#issuecomment-293164935).
```

> runTheMatrix.py -l 10024 --command=' --dump_python '
> grep  RandomNumberGeneratorService TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM.py
process.RandomNumberGeneratorService = cms.Service("RandomNumberGeneratorService",
``` 

Thanks for the help, this PR is good to go for AlCa.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
