### PR TITLE
[9.4.X] DeepCSV and CSVv2 negative tagger bugfix

### PR DESCRIPTION
**Pull request by emilbols**
backport of https://github.com/cms-sw/cmssw/pull/23206

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23561	c67b7d9
- backport from the master version is correct (#23206 is available in CMSSW_10_2_0_pre5)
- jenkins tests pass and comparisons with the baseline show no differences.

This PR is needed for analysis workflows, it does not affect production workflows.
There will be more backport PRs related to Deep\* b-taggers and will (at times) depend on the previous backports.
@fabiocos  please merge this if there are no issues.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
