### PR TITLE
add MiniAOD sequences, add RECO vs MiniAOD comparisons in Harvesting Module

### PR DESCRIPTION
**Pull request by webermat**
add functionality to compare MINIAOD and RECO DQM Offline output in Harvesting module for Jets and MET. Add MiniAOD sequences into official DQM sequences

### CODE REVIEW

**Comment by webermat** [comment]
Unfortunately the naming scheme was not unified for MET and Jet modules. That is corrected now. While testing 5 histogram for the METAnalyzer were put at a wrong place, once again a fix has been provided. These histograms should have been filled only if both previous bunches were filled based on technical trigger information (in 25 ns spacing). So even in data they should not be filled right now.

**Comment by webermat** [comment]
comparisons are fine now

**Comment by deguio** [comment]
+1
seems ok to me.
thanks,
F.

**Comment by webermat** [comment]
Based on the comment we received for our update on the JetMET harvesting modules on the Validation side, we modified the code analogously. Thus we have loop now over the list of histograms instead of several repetitive loops for each quantity.

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
reformulate the Reco vs MiniAOD comparison implementation, use now Vectors of MonitorElements instead of maps

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
