### PR TITLE
[14_0_X] Update to `relval_gpu.py`for Alpaka and Pixel Triplets Alpaka Workflows

### PR DESCRIPTION
**Pull request by AdrianoDee**
Backport of https://github.com/cms-sw/cmssw/pull/45694 (with the exception of [a comment](https://github.com/cms-sw/cmssw/blob/master/DataFormats/VertexSoA/interface/ZVertexDefinitions.h#L12-L23) that will anyway disappear soon) and https://github.com/cms-sw/cmssw/pull/45963 (a fix) to `14_0_X`.

This is useful because it allows to run 2024 Alpaka wfs in the PR testing, meaning we test also the Alpaka HLT.

Note: for Phase2, differently from `master` and `14_1_X` we use D98 wfs here (since it was the baseline for `14_0_X`).

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 12834.406, 12834.402, 29834.402, 29634.406
- workflows_gpu = 12834.406, 12834.402, 12834.403, 29834.402, 29634.406, 29834.403, 29634.496, 12834.496
- relvals_opt = --what upgrade
- relvals_opt_gpu = --what upgrade

**Comment by AdrianoDee** [comment]
enable gpu

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 12834.406, 12834.402, 29834.402, 29634.406
- workflows_gpu = 12834.406, 12834.402, 12834.403, 25034.402, 24834.402, 24834.403, 24834.406, 12834.496
- relvals_opt = --what upgrade
- relvals_opt_gpu = --what upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 12834.406, 12834.402, 24834.402, 25034.406
- workflows_gpu = 12834.406, 12834.402, 12834.403, 25034.402, 24834.402, 24834.403, 24834.406, 12834.496
- relvals_opt = --what upgrade
- relvals_opt_gpu = --what upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 12834.406, 12834.402, 24834.402
- workflows_gpu = 12834.406, 12834.402, 12834.403, 25034.402, 24834.402, 24834.403, 24834.406, 12834.496
- relvals_opt = --what upgrade
- relvals_opt_gpu = --what upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by antoniovagnerini** [comment]
backport of #45694

**Comment by vicha-w** [comment]
Hi @AdrianoDee,

This PR has been successfully tested on central DQM playback machines with CMSSW 14_0_15_patch1 and run 384377. For more details please have a look at DQM^2 mirror here: https://cmsweb.cern.ch/dqm/dqm-square/?run=518487&db=playback

Best regards,
Vichayanun

**Comment by antoniovagnerini** [comment]
+1

**Comment by AdrianoDee** [comment]
@cms-sw/upgrade-l2 gentle ping

**Comment by mmusich** [comment]
@cms-sw/upgrade-l2 @srimanob can you please sign this? 
I suspect without it if we test the gpu matrix in 14.0.X the bot is expecting to run some workflows that don't exist, see e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-66ff18/41614/summary.html)

**Comment by mmusich** [comment]
urgent

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
