### PR TITLE
Hlt tau dqm update

### PR DESCRIPTION
**Pull request by slehti**
HLTTauDQM: Added regexp support to tag&probe, changed histogram binning.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
Please remove the code instead of just commenting out. Otherwise, this PR is fine.

**Comment by dmitrijus** [comment]
@slehti

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
