### PR TITLE
Catch case where parent index is bad in Hydjet

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Parent index should not be larger than child index for hydjet. This occurred when there was a high multiplicity which is causing an index overflow in the Fortran code.
- Now throw an exception when parent index is larger than child index. This is much preferred over the segmentation fault happening now.

#### PR validation:

Ran a job which before change would have a segmentation fault but after change throws exception and ends cleanly.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
FYI @wouf

**Comment by Dr15Jones** [comment]
Based on discussion in #39784

**Comment by wouf** [comment]
This PR related to cmsdist#8154

**Comment by Dr15Jones** [comment]
please test with cmsdist#8154

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#8154
- workflow = 159.03

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , if this PR looks good then should we go ahead with `hydjet 1.9.3` ( https://github.com/cms-sw/cmsdist/pull/8154 ) integration?

**Comment by SiewYan** [comment]
It is fine by me, @Saptaparna , @menglu21 , could you confirm and sign it? thanks

**Comment by Saptaparna** [comment]
+1

**Comment by wouf** [comment]
It won't work properly without cms-sw/cmsdist#8154 !

**Pull request merged**
