### PR TITLE
Re-add class version SiStripApproximateCluster

### PR DESCRIPTION
**Pull request by jpata**
As pointed out by @makortel https://github.com/cms-sw/cmssw/pull/38870#discussion_r938814564, we forgot to keep the old class version in https://github.com/cms-sw/cmssw/pull/38870.

### CODE REVIEW

**Comment by jpata** [comment]
test parameters:
  - workflow = 140.58

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
attn. @abaty

**Comment by jpata** [comment]
+reconstruction
- bugfix for backwards compatibility
- no reco changes

**Comment by qliphy** [comment]
+1

**Pull request merged**
