### PR TITLE
Update of the LumiPCC module veto list and afterglow factors for 2024

### PR DESCRIPTION
**Pull request by radla118**
#### PR description:

Update of the LumiPCC module veto list and afterglow parameters implemented in the corresponding configuration files.  The parameters and the veto are defined by studying the reprocessed 2023 data. The workflow remains unchanged. Similar changes have been requested for 2023 #41242 #41256 

#### PR validation:

Validated by running runTheMatrix.py -l 1020.0 configuration.

Backport will be requested later

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@radla118 in a [comment](https://github.com/cms-sw/cmssw/pull/41242#issuecomment-1491837880) posted for the similar PR prepared last year it was written:
"_privately also agreed with the developers that this list should be provided dynamically through the DB_"
After exactly one year, which is the status of that migration of these parameters into the DB?

And, besides the "technical" validation that you are mentioning in the PR description (i.e. the PR doesn't crash cmssw), how did you verify that the parameters were typed correctly in the updated configuration?

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test workflow = 1020

**Comment by radla118** [comment]
> @radla118 in a [comment](https://github.com/cms-sw/cmssw/pull/41242#issuecomment-1491837880) posted for the similar PR prepared last year it was written: "_privately also agreed with the developers that this list should be provided dynamically through the DB_" After exactly one year, which is the status of that migration of these parameters into the DB?

@perrotta we are working on a more flexible dynamic module veto (i e define unique veto list for ~100 LS periods). Some preliminary studies are already done, but the final strategy and the implementation is not finalized yet. It is clear that the current configuration is rather inconvenient, but we did not want to change it until everything is settled.

> 
> And, besides the "technical" validation that you are mentioning in the PR description (i.e. the PR doesn't crash cmssw), how did you verify that the parameters were typed correctly in the updated configuration?

We store our module veto in the dedicated  [CMS-LUMI-POG/PCCTools](https://github.com/CMS-LUMI-POG/PCCTools) git repo. I just compared the central list and the copied one using a simple script.

**Comment by perrotta** [comment]
+alca
- Same procedure to determine the misbehaving modules with past year data as was done for similar previous PRs
- The migration towards the storage of these parameters in the db rather than in python config is still ongoing...

**Pull request merged**
