### PR TITLE
Backport of PR #28474 [HB TDC conversion configurable]

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

Backport of PR #28474

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by abdoulline** [comment]
Arguments (in favor of backport) are very simple: 
- no impact on any regular workflow (including regular mix, premix, reco);
- this optional functionality is needed to produce (first) private and (eventually) centrally-managed 11_0 samples to begin LLP trigger/physics studies.

**Comment by perrotta** [comment]
backport of #28474

**Comment by perrotta** [comment]
+1
- This is an identical backport of #28474 (very same commits)
- HB TDC conversions are made configurable, and the mapping between the HE QIE bits and the four states of the HB TDC is also modified with respect to the previous one
- TDC plots gets modified as a consequence: this has no effect on other reco or whatever outputs in regular workflows: I think this can be included in 11_0 even after the last open pre, as requested in https://github.com/cms-sw/cmssw/pull/28525#issuecomment-561094218

**Comment by fabiocos** [comment]
+1

**Pull request merged**
