### PR TITLE
Replace getProcessParameterSet

### PR DESCRIPTION
**Pull request by wddgit**
Replace the function getProcessParameterSet
in HLTrigger and PhysicsTools. This function
is being removed from the CMSSW Framework
because it does not work properly with SubProcesses
and causes issues with multithreading. The
replacement should yield identical behavior
to what was originally there (except now it
works in a SubProcess job).

### CODE REVIEW

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
