### PR TITLE
Unordered Map Serialization

### PR DESCRIPTION
**Pull request by ianna**
- Add serialization for unordered map

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@ggovi - as discussed, here is a schema which requires unordered map serialization. Please, have a look and comment. Thanks.

**Comment by ggovi** [comment]
@ianna 
Indeed we discussed this - but you are modifying an existing CondFormat... We should not do that...

**Comment by ianna** [comment]
@ggovi - I do not think the schema was ever used, it is still under development.

**Comment by ggovi** [comment]
@ianna 
Ok after a check, there are no payloads stored for this class. we can go ahead with the PR, any payload stored meanwhile will be deleted.

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
