### PR TITLE
ResonanceDecayFilter:wzAsEquivalent setting for Pythia8Interface (backport 7_1_X)

### PR DESCRIPTION
**Pull request by kandrosov**
#### PR description:

Added ResonanceDecayFilter:wzAsEquivalent setting to Pythia8Interface. 

#### PR validation:

code compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This is port of #21132 for 7_1_X.
It is needed to produce 2016 HH->bbVV samples to decay H inclusively to a pair of gauge bosons.

@acarvalh

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@silviodonato   There are many DQM failures but seem not to be related to GEN.  Is it expected?

**Comment by silviodonato** [comment]
@qliphy see https://github.com/cms-sw/cmssw/issues/29365

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
