### PR TITLE
HLT updates on top of 741 with FastSim for 74X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
This PR includes #8808 (E/g seeded by jets) #8904 (fastsim backport) #8929 (fixes backport) #8931 (HLT updates) plus backport of #8916, and makes HLT work with all that!

Rebased to CMSSW_7_4_2 - at this stage it inlucdes just the fastsim PR #8904 plus HLT-only work.

Rebased further to 7_4_X (as of 20-May 5:10PM) as #8904 is now integrated in it...
...should reduce signatures required

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
@Martin-Grunewald 

Thanks a lot!
I will review after the FastSim backports get merged,
and after a rebase.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Rebased to resolve merge conflicts.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_7_4_2

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@nclopezo, @boudoul, @srimanob, @franzoni, @davidlange6 @lveldere 

What is this PR waiting for?

**Comment by lveldere** [comment]
for fastsim: merging of #8904, sorry...

**Comment by Martin-Grunewald** [comment]
Rebased to 7_4_X as #8904 is now integrated in it...
...should reduce signatures requyired

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@lveldere, @ssekmen
please have a look and sign...

**Comment by lveldere** [comment]
+1

thanks!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

We'll need this one for FastSim production,
please consider merging it before CMSSW_7_4_3 is released.

**Pull request merged**
