### PR TITLE
[14.0.X] Add customize to include Alpaka HCal PF Clustering at HLT 

### PR DESCRIPTION
**Pull request by waredjeb**
This is a backport of #43971

This PR add `customizeHLTforAlpakaParticleFlowClustering()` to `customizeHLTForAlpaka()` to integrate the Alpaka HCAL PF Clustering at HLT.

The function defines all the needed modules and replace them in the necessary Sequences. Currently it also run the Alpaka CPU-serial version up to the PFClusterSoA collection, before the Legacy conversion.

To compare the GPU version against the CPU version a follow-up PR will be needed to perform the CPU legacy conversion and the comparison at DQM.
Validation

Validated running the following HLT configuration
```
hltGetConfiguration /dev/CMSSW_14_0_0/GRun --unprescale --output all --globaltag auto:phase1_2024_realistic --mc --max-events 10 --input /store/mc/Run3Winter24Digi/TT_TuneCP5_13p6TeV_powheg-pythia8/GEN-SIM-RAW/133X_mcRun3_2024_realistic_v8-v2/80000/dc984f7f-2e54-48c4-8950-5daa848b6db9.root --customise HLTrigger/Configuration/customizeHLTforAlpaka.customizeHLTforAlpaka
```
And also by merging https://github.com/cms-sw/cmssw/pull/43958 and running workflow 12434.423

FYI @jsamudio @hatakeyamak

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43971

**Comment by mmusich** [comment]
type pf

**Comment by mmusich** [comment]
> And also by merging https://github.com/cms-sw/cmssw/pull/43701 and running workflow 12434.423

is there a backport of this too?

**Comment by waredjeb** [comment]
> > And also by merging #43701 and running workflow 12434.423
> 
> is there a backport of this too?

Yes: https://github.com/cms-sw/cmssw/pull/43958

**Comment by mmusich** [comment]
> Yes: https://github.com/cms-sw/cmssw/pull/43958

please amend the PR description then.

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu= 12434.423

**Comment by mmusich** [comment]
will trigger test here only once https://github.com/cms-sw/cmssw/pull/43971#discussion_r1491102408 is clarified.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please abort
   * needs https://github.com/cms-sw/cmssw/pull/43958 in an IB.

**Comment by mmusich** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
