### PR TITLE
Run3-gex52 Take care of issues in the Ecal endcap algorithm for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of issues in the Ecal endcap algorithm for dd4hep

#### PR validation:

Tested using cfg in SimG4Core/Configuration/test in a special built where dd4hep is built with Geant4 units. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda In the PR description, could you please describe the issues fixed by this PR?

**Comment by cvuosalo** [comment]
This PR still shows this error:
```
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
```

**Comment by bsunanda** [comment]
@cvuosalo The fix works for the SIM step going for both versions of dd4hep library - with units as G4 or as ROOT

**Comment by bsunanda** [comment]
@cvuosalo @ianna The issue for EB could be something to do with dd4hep. I sent a mail to you regarding that

**Comment by civanch** [comment]
@cvuosalo , @ianna , if this fix is valid, let us merge it and let us try to understand EB issue and make a new PR. This problem in EB appears after introduction of G4 units, it may be, of course, issue of DD4Hep but my guess it is most probably CMSSW.

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
