### PR TITLE
Fixes for HI MC (mainly L1)

### PR DESCRIPTION
**Pull request by mmusich**
# Changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [75X_mcRun2_design_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_design_v11) as [75X_mcRun2_design_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_design_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_design_v11/75X_mcRun2_design_v10): 
  - new JEC for MC Summer15_25nsV6 including uncerntainties
- **RunII Asymptotic scenario** : [75X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_asymptotic_v11) as [75X_mcRun2_asymptotic_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_asymptotic_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_asymptotic_v11/75X_mcRun2_asymptotic_v10): 
  - new JEC for MC Summer15_25nsV6 including uncerntainties
  - adding label AK4Calo for pp reference run at 5TeV JEC
- **RunII Heavy Ions scenario** : [75X_mcRun2_HeavyIon_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_HeavyIon_v9) as [75X_mcRun2_HeavyIon_v7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_HeavyIon_v7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_HeavyIon_v9/75X_mcRun2_HeavyIon_v7): 
  - Castor Gains to v1.0
  - updating ES Channel status, pedestal, thresholds (align to same values as in asymptotic pp)
  - adding HeavyIon event plane correction record
  - adding label AK4Calo for pp reference run at 5TeV JEC
  - changing the L1 menu to L1Menu_CollisionsHeavyIons2015_v2_mc
  - changing the L1TCalo parameters for HI collisions
  - updating the Strip APV gains from particles and Bad channel as in 76X for pp simulation
  - updating L1RCT parameters and L1RPCConfig to align as in following release cycles
## RunI data
- **RunI Offline processing** : [75X_dataRun1_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_v10) as [75X_dataRun1_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_v10/75X_dataRun1_v9): 
  - adding Heavy Ion event plane calibration record
  - adding label AK4Calo for pp reference run at 5TeV JEC
## RunII data
- **RunII Offline processing** : [75X_dataRun2_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_v10) as [75X_dataRun2_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_v10/75X_dataRun2_v9): 
  - adding Heavy Ion event plane calibration record
  - adding label AK4Calo for pp reference run at 5TeV JEC
  - new JEC for 2015 data including L2L3 residuals and  uncerntainties
- **RunII HLT processing** : [75X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HLT_frozen_v6) as [75X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_HLT_frozen_v6/75X_dataRun2_HLT_frozen_v4): 
  - adding the GBRForest payloads for MVA selection of HI Tracking
  - reverted BTag Jet MVA to the 74X values 
  - reverted PF hadron calibration to the 74X values
- **RunII HI HLT processing** : [75X_dataRun2_HLTHI_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HIHLT_v2) as [75X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HLT_frozen_v6) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_HLT_frozen_v6/75X_dataRun2_HLT_frozen_v6): 
  - adding negative energy filter tag
  - changing the AK4CaloHLT Jet Energy corrections to pick tag for Heavy Ions
  - using full Strip pedestals for Tracker Zero Suppression at HLT
## Upgrade
- **PhaseI design scenario** : [75X_upgrade2017_design_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_upgrade2017_design_v6) as [75X_upgrade2017_design_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_upgrade2017_design_v5) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_upgrade2017_design_v6/75X_upgrade2017_design_v5): 
  - new Pixel SIM LA for Phase-I
  - new Pixel LA for Phase-I
  - new Pixel templates for Phase-I
  - new Pixel SIM gains for Phase-I
  - new Pixel GenErrors for Phase-I
  - new Pixel gains for Phase-I
  - new Pixel quality for Phase-I

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
results of local tests:
`runTheMatrix -l limited`

```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Nov 18 14:38:24 2015-date Wed Nov 18 14:33:36 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Nov 18 14:50:15 2015-date Wed Nov 18 14:33:37 2015; exit: 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Nov 18 14:37:31 2015-date Wed Nov 18 14:33:42 2015; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Nov 18 14:38:13 2015-date Wed Nov 18 14:33:47 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Nov 18 14:51:39 2015-date Wed Nov 18 14:37:39 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Nov 18 14:47:39 2015-date Wed Nov 18 14:38:20 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Nov 18 14:47:30 2015-date Wed Nov 18 14:38:24 2015; exit: 0 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Nov 18 15:00:09 2015-date Wed Nov 18 14:47:40 2015; exit: 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Nov 18 14:57:08 2015-date Wed Nov 18 14:47:42 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED  - time date Wed Nov 18 14:58:17 2015-date Wed Nov 18 14:50:17 2015; exit: 0 0 0 0 0 0 0
10 10 9 7 5 1 1 tests passed, 0 0 0 0 0 0 0 failed
```
`addOnTests.py`
```
 34 tests passed, 0 failed 

```

**Comment by mulhearn** [comment]
I've got a version with the removal of customizations included here:  #12475

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@mmusich please close this PR since it's now superseded by #12475

**Comment by slava77** [comment]
Just to note that run2 data rereco changes slightly:
looking, e.g., at run2_data, together with the snapshot update we now have new IOV for CSC calibrations
(232000	insert on 2015-11-09 17:48:45). So, quite a few things change in run2 data. I suppose more IOVs probably changed in other calibrations.

**Pull request merged**
