### PR TITLE
[10_6_X] Add ParticleNet to NanoAOD

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/31096.

> This PR adds the ParticleNet tagger to NanoAOD. The following scores will be included in NanoAOD:
> 
> - ParticleNet: `TvsQCD`, `WvsQCD`, `ZvsQCD`, `HbbvsQCD`, `HccvsQCD`, `H4qvsQCD`, `QCD`
> - ParticleNet-MD: `Xbb`, `Xcc`, `Xqq`, `QCD`
> 
> The ParticleNet tagger needs to run in the NanoAOD sequence until we have the tagger stored in MiniAOD. The updated training [[V01](https://github.com/cms-sw/cmssw/pull/31036)] should be used for both UL and EOY samples.
> 
> FYI @camclean @alefisico

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@hqucms 
The use of modifiers is not appropriate we have to use the run2_miniAOD_devel (like for all the other back ports)

if run2_miniAOD_devel: 
all will be available in miniAOD

if (~run2_miniAOD_devel) recompute stuff

**Comment by hqucms** [comment]
> @hqucms
> The use of modifiers is not appropriate we have to use the run2_miniAOD_devel (like for all the other back ports)
> 
> if run2_miniAOD_devel:
> all will be available in miniAOD
> 
> if (~run2_miniAOD_devel) recompute stuff

@mariadalfonso 
Is this for the no-change policy (i.e., the new taggers should only be added when `run2_miniAOD_devel=True`)?

**Comment by mariadalfonso** [comment]
> > @hqucms
> > The use of modifiers is not appropriate we have to use the run2_miniAOD_devel (like for all the other back ports)
> > if run2_miniAOD_devel:
> > all will be available in miniAOD
> > if (~run2_miniAOD_devel) recompute stuff
> 
> @mariadalfonso
> Is this for the no-change policy (i.e., the new taggers should only be added when `run2_miniAOD_devel` is enabled)?

You are adding new variables for particleNet, and in previous eras the analyser will not use them so there is no problem is some variable is present. For the old tagger you were already re-running them before, so this will result in no change.

The new mini  in 10_6 are controlled by the run2_miniAOD_devel, so you can take particleNet from mini and add in nano only when the run2_miniAOD_devel is enabled.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #31096

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31244	cb85649
- the backport is essentially identical to the master version
    - this is appropriate in the context of miniAOD: changes appear only with the run_miniAOD_UL and show up only in the UL re-miniAOD workflow
    - in the context of nanoAOD, other production workflows now have the ParticleNet tagger info added; I suppose this is still formally within the permissive part of the "no-change" policy allowing a completely new variable/data to be added. The xpog review is in progress, so this part is not affecting my signature.
- jenkins tests pass and comparisons with the baseline show the new tagger data in re-miniAOD UL wf 136.88811 and also in standard nanoAOD outputs (a 2018 MC production from scratch 10824.0 and a 2017 nanoAOD from 2017 mini inputs 1325.7)

**Comment by hqucms** [comment]
@mariadalfonso I changed to using `run2_miniAOD_devel` in https://github.com/cms-sw/cmssw/pull/31244/commits/9cf15b74188f058617e5b674a37f3c1f618685ce. Let me know if it gives the desired behavior.

**Comment by mariadalfonso** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

**Comment by mariadalfonso** [comment]
+xpog
Taggers added in minAOD_devel otherwise recomputed, new branch  "ParticleNet" not present in previous nano will be available.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31244	9cf15b7
- changes since the last reco signoff https://github.com/cms-sw/cmssw/pull/31244#issuecomment-682058827 were outside (downstream) of reco, in nanoAOD https://github.com/cms-sw/cmssw/pull/31244/files/cb8564948618bcaa4699399fa339580a6148c3e4..9cf15b74188f058617e5b674a37f3c1f618685ce

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
