### PR TITLE
[92X] OnlineDQM : Move uGMT output to uGT input comparison histogram to the uGT directory

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/21367

This backport is done on top of https://github.com/cms-sw/cmssw/pull/20947 and https://github.com/cms-sw/cmssw/pull/21065

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @stahlleiton
Data taking with 92x has finished. This can be closed.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
