### PR TITLE
HcalDQM - Correct LED CU List for P5 (online DQM)

### PR DESCRIPTION
**Pull request by lwang046**
PR description:
Same feature of #33827 solving the calibration channels list error and the histogram y-axis limits, on top of CMSSW_11_3_0 intended for P5 (online DQM)

PR validation:
runTheMatrix.py -l limited -i all --ibeos okay

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by pmandrik** [comment]
Dear @lwang046 ,

please find the crash log file from DQM^2 in the attachment [0]. While the new book1DD function from your PR deals with TH1D, it is looks like there are still some MonitorElement::getTH1F() calls in the code.

Best regards, Petr

[0] [33838.txt](https://github.com/cms-sw/cmssw/files/6547359/33838.txt)

**Comment by lwang046** [comment]
Hi @pmandrik, thank you very much for spotting this! I have corrected them with getTH1FD() calls

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Tested succesfully in Online DQM at P5 playback

**Comment by silviodonato** [comment]
+1

>  Tested succesfully in Online DQM at P5 playback

**Pull request merged**
