### PR TITLE
Added L1TStage2uGT DQM module

### PR DESCRIPTION
**Pull request by mzarucki**
## **uGT DQM Module**

Data Quality Monitoring module for the L1 Micro Global Trigger (uGT):
- _L1TStage2uGT.h_
- _L1TStage2uGT.cc_
- _L1TStage2uGT_cfi.py_

The EDAnalyzer module takes the readout record from the **gtStage2Digis** unpacker as input, to produce DQM plots. The _DataFormats/L1TGlobal_ package was included to access the necessary methods used on the readout record. The module was added to the L1TStage2 monitoring sequence in the _L1TStage2_cff.py_ configuration file fragment, following the standard workflow for the L1T2016 DQM. 

The module was tested on 2016 MWGR2 and MWGR3 data.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
this PR looks ok to me. if you want it to be merged at p5 you should provide a 80x version of this asap.
thanks,
F.

**Comment by mzarucki** [comment]
I made a PR to 80X: https://github.com/cms-sw/cmssw/pull/13725

In 80X the uGT unpacker had some issues which were resolved in 81X. Is this important?

Furthermore, I noticed that compared to 81X, the EMTF DQM module is not included in 80X.

Best,
Mateusz

**Comment by mzarucki** [comment]
Closed PR as it will be incorporated in a combined L1Trigger DQM PR: https://github.com/cms-sw/cmssw/pull/13763

**Pull request closed without merging**
