### PR TITLE
Clang warnings L1Trigger/L1TMuonEndCap

### PR DESCRIPTION
**Pull request by Dr15Jones**
modified code to avoid clang compiler warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by thomreis** [comment]
@abrinke1 please take a look at this.

**Comment by abrinke1** [comment]
Hi @Dr15Jones ,
Can you specify exactly the errors are that you are seeing in the compiler?  Two of the functions you deleted are critical to the EMTF emulator:
scale_pt : http://cmslxr.fnal.gov/source/L1Trigger/L1TMuonEndCap/src/PtAssignment.cc?v=CMSSW_10_2_1#0082
unscale_pt : http://cmslxr.fnal.gov/source/L1Trigger/L1TMuonEndCap/src/PtAssignmentEngine.cc?v=CMSSW_10_2_1#0147

It looks like the dPhiNLBMap arrays you deleted were unused, so it's fine to delete those.  @jiafulow will also want to follow this conversation.

Best,
Andrew

**Comment by Dr15Jones** [comment]
@abrinke1 I didn't actually delete the functions, instead I said that those virtual functions must be defined in any inheriting class. As for the warnings, you can see them here:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_10_3_CLANG_X_2018-08-06-2300/L1Trigger/L1TMuonEndCap

**Comment by abrinke1** [comment]
Hi @Dr15Jones ,
Sorry about that. Discussing with @jiafulow , he confirms that your changes should make no difference to how the emulator runs.  So this looks fine to me.
Best,
Andrew

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
