### PR TITLE
Remove unused functionality from SeedComparitor

### PR DESCRIPTION
**Pull request by makortel**
While trying to understand where and why we use `TrackingRegion` in seeding (for planning of efficient regional CA), I removed two methods of `SeedComparitor` that had only trivial (`return true`) implementations, and removed the `TrackingRegion` parameters as they were not used by any implementation.

It turned out, however, that these changed will not help in any way the development towards regional CA (`TrackingRegion` will be needed for other reasons), so these changes are not needed for that. But since I already had committed them, I though it would still be worth of the effort to ask the question: do we have any foreseen use case in `SeedComparitor`s for either the removed methods, or for TrackingRegion? ~~(hence "RFC")~~ Apparently not.

Personally I would eventually revamp the whole `SeedComparitor` infrastructure as its internals are currently very confusing (and there are implementations only for pixel/strip cluster shape cuts, but with total of 4 of them...).

What do people think? Seems to be acceptable.

Tested in CMSSW_8_1_0_pre12, no changes expected anywhere.

@rovere @VinInn @felicepantaleo

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16031 ef465a4
- changes are as described and were signed off by TRK POG
- jenkins tests pass and comparisons with baseline show no difference
- local test with 70 event 25202 show somewhat significant decrease in the time taken by some of the seeding modules (some of the code removed was potentially consuming some time, hence the tests); the effect is rather small overall though.


```
   -0.782519      -0.04%        12.25 ms/ev ->         5.36 ms/ev newCombinedSeeds
   -0.099058      -0.02%        34.15 ms/ev ->        30.93 ms/ev ecalDrivenElectronSeeds
   -0.041253      -0.02%        69.36 ms/ev ->        66.56 ms/ev stripPairElectronSeeds
```
other more CPU-consuming seeding module times look rather unchanged

**Comment by makortel** [comment]
Given the +1's I better remove "RFC" from the description.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
