### PR TITLE
updating  TrackerGeometry in Geometry/TrackerGeometryBuilder to accom…

### PR DESCRIPTION
**Pull request by suchandradutta**
updating  TrackerGeometry in Geometry/TrackerGeometryBuilder to accommodate the final naming scheme for Phase2 Pixel detectors and corresponding update in Phase2Digitizer

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by boudoul** [comment]
Dear @suchandradutta and @ianna 
Could you apply also this change in Phase2TrackerDigitizer.cc (line 108) 

<     iSetup.get<IdealGeometryRecord>().get(tTopoHand);
---
>     iSetup.get<TrackerTopologyRcd>().get(tTopoHand);

it's needed to make it work in 8X
Thanks
Gaelle

**Comment by boudoul** [comment]
troubles with the formatting in github : reformulating here my previous comment 

changes 
IdealGeometryRecord
by 
TrackerTopologyRcd


in line108

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
