### PR TITLE
Clean BuildFiles in OnlineDB/CSCCondDB

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/31898).

This BuildFile cleaning was non-trivial because the affected test package also recompiled files from the corresponding `../src` directory, which should probably avoided. To make sure that these sources are not compiled twice, a OnlineDB/CSCCondDB library build target is introduced that is now used both by the plugins and the test library. I hope this is a fair solution!

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by guitargeek** [comment]
Please test, if this is ok?

**Comment by qliphy** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
