### PR TITLE
Old files removed

### PR DESCRIPTION
**Pull request by dnash86**
Old SLHA files removed, new ones in https://github.com/cms-data/Configuration-Generator/tree/53X_incremental

### CODE REVIEW

**Comment by bendavid** [comment]
@dnash86 can you confirm this removes ALL files from Configuration/Generator/data which are now present in the external?

**Comment by dnash86** [comment]
@bendavid The list of files to remove matched the list sent by the requesters that the new requests run on.  The other procedure could be to list those present in the external, and remove the filenames matching those, but I thought the easiest/best guarantee was to take the list of updated files provided by the analyzers themselves for removal.

**Comment by bendavid** [comment]
Can you explicitly check that there are no other duplicates compared to what is in https://github.com/cms-data/Configuration-Generator/tree/53X_incremental ?

**Comment by dnash86** [comment]
I checked, via this procedure:

git clone -b 53X_incremental git@github.com:dnash86/Configuration-Generator.git Configuration-Generator
ls Configuration-Generator/ > FilesToRemove.txt

I then tried to remove everything in that list from the directory I sent the pull from, and commit changes, and got a "nothing to commit" message.

**Comment by dnash86** [comment]
I will shortly be setting up a PR to the cms-data repository, with the updated slha files.

**Comment by dnash86** [comment]
PR to cms-data is set up, so we are ready to request a new CMSSW_5_3_X release, please advise on what else can be done to help.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
