### PR TITLE
Phase2-hgx327X Improve the scripts for muon tomography in Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Improve the scripts for muon tomography in Validation/HGCalValidation

#### PR validation:

Test the modified scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@emanueleusai Please approve this PR so that it can go to pre4 build

**Comment by emanueleusai** [comment]
+1

- jet/met dqm differences not related to this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
