### PR TITLE
Fix Unrunnable Schedule due to multiple offlineBeamSpots (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix Unrunnable Schedule due to multiple offlineBeamSpots (80X)
Backport of #14190

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@ssekmen, @lveldere 
Please sign for fastsim.
(BTW, the stage-2 L1T and HLT should work in FastSim - contrary what you presented today in the Plenary)

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
