### PR TITLE
Removes boost erase_all dependency

### PR DESCRIPTION
**Pull request by Purva-Chaudhari**
#### PR description:
Removes white spaces and removes boost dependency. Attempt to clear the ambiguity discussed in issue #35522 
std::isspace removes white spaces of type:
' '		space (SPC)
'\t'		horizontal tab (TAB)
'\n'		newline (LF)
'\v'		vertical tab (VT)
'\f'		feed (FF)
'\r'		carriage return (CR)

#### PR validation:

Compiles

#### if this PR is a backport:

@davidlange6 @vgvassilev

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
