### PR TITLE
HGCal DB Parameters Writer

### PR DESCRIPTION
**Pull request by ianna**
- HGCal DB parameters writer implemented
- HGCal DB parameters analyzer and test configuration

To write them out locally and read them back:

```
cmsRun CondTools/Geometry/test/hgcalgeometrywriter.py
cmsRun Geometry/HGCalCommonData/test/hgcalParameters_cfg.py
```

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@ianna 
#12862 is already merged. It is included in this PR as well and triggers extra signatures/labels. Please remove the parts already in #12862

**Comment by ianna** [comment]
@slava77  - yes, it's another branch based on #12862. As soon as an IB is available, I'll rebase this one.

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1
In workflow 5.1 (FastSIm for run1) there is a problem in HcalHitsV - many nans, it is likely not directly related

**Pull request merged**
