### PR TITLE
re-miniAOD workflows on 94X input datasets

### PR DESCRIPTION
**Pull request by fabozzi**
Adding 2 re-miniAOD workflows on 94X MINIAOD inputs (data and MC).

This follows discussion in #22197

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.8311,1325.51

**Comment by slava77** [comment]
The failure in 136.8311 will go away after #22105 is merged.
It can be temporarily avoided by adding ``` --customise_commands="process.patTaus.skipMissingTauID = True\n" ```

**Comment by fabozzi** [comment]
> The failure in 136.8311 will go away after #22105 is merged.
So, should we wait for #22105 to be merged before testing this? In any case, we have to wait Phedex transfer on disk of the AODSIM MC input datasets.

**Comment by slava77** [comment]
@cmsbuild please test workflow 136.8311,1325.51

this should work now

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Review by fabiocos — COMMENTED** [review]
Sorry, a wf labeled TTbar with an input file RelValProdZEE?

**Comment by fabozzi** [comment]
ooops... fixed

**Comment by fabozzi** [comment]
please test workflow 1325.51

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabozzi** [comment]
@fabiocos @slava77 
Do we need a backport to 94X / 10_0_X?

**Pull request merged**
