### PR TITLE
change from NoiseCleaned to JetIdCleaned

### PR DESCRIPTION
**Pull request by safarzad**
change paths from NoiseCleaned to JetIdCleaned

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
since you have to rebase the 74 version of this PR, do you mind removing the commented lines?
thanks,
F.

**Comment by davidlange6** [comment]
is this PR needed any more?
@safarzad @deguio

**Comment by safarzad** [comment]
To avoid conflict with new paths I think we should skip it.

**Pull request closed without merging**
