### PR TITLE
SonicTriton tests with Singularity

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

SonicTriton tests can now run on either Singularity or Docker. This makes the test setup more accessible (since Docker typically requires superuser permission). An augmented Docker image with PyTorch libraries included is now hosted on DockerHub at https://hub.docker.com/repository/docker/fastml/triton-torchgeo, while the Singularity version of that image is automatically generated and hosted on `/cvmfs/unpacked.cern.ch` thanks to https://gitlab.cern.ch/unpacked/sync.

A unified script `triton` is introduced to handle the server for both the Docker and Singularity cases. It also handles using GPU instead of CPU, verbosity, waiting for the server to actually start, and other details. The documentation is updated accordingly.

(This PR also fixes some alarmingly fast link rot in the tests... hopefully Nvidia is done renaming the triton inference server repository.)

#### PR validation:

Tested on several different machines, and had some other users test as well.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@makortel @fwyzard any comments?

**Comment by makortel** [comment]
The `fetch_model.sh` is not run by PR or IB tests, right?

**Comment by kpedro88** [comment]
No, not currently. (At some point, we'll try to introduce a unit test using the local CPU server, but this is not ready at present.)

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
