### PR TITLE
Stop invalid LCTs from being produced. Fix the duplicated LCT issue.

### PR DESCRIPTION
**Pull request by dildick**
Jia Fu saw some problems a while ago with GEM-based LCTs in upgrade scenarios. This PR fixes those issues. 
 
FYI @jiafulow @tahuang1991

### CODE REVIEW

**Comment by jiafulow** [comment]
Hi Sven,

Thanks for preparing the fixes! I'll try it out.

Best regards,
Jia Fu

**Comment by fabiocos** [comment]
please test

**Comment by dildick** [comment]
Hi, the tests have been running for two days now. Is it possible to restart them?

**Comment by dildick** [comment]
@fabiocos Can you please restart the tests?

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@thomreis @rekovic could you please have a look? I guess that, once this PR is validated, we will need a backport in 10_2_X...

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
@dildick do you want to make a backport PR to 10_2_X as well now that the master points to 10_3_X?

**Comment by dildick** [comment]
@thomreis Ok. I can take care of that.

**Comment by fabiocos** [comment]
@thomreis @rekovic is this fix potentially affecting also MC? If yes as I guess, we should backport it before starting a massive production, with 10_2_X we cannot take too much freedom...

**Comment by fabiocos** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
there is a backport PR now. #23833

**Pull request merged**
