### PR TITLE
Removed stub EGM regressor producers from production

### PR DESCRIPTION
**Pull request by guitargeek**
Hi,

while checking out how the EGM energy regression is done a few weeks ago, I realized there were some old producers `ElectronRegressionValueMapProducer` and `PhotonRegressionValueMapProducer`. They produce nothing, but are still in MiniAOD and NanoAOD production sequence. Maybe it would be good to remove them to get rid of the overhead they provide?

Local matrix tests all pass.

Cheers,
Jonas

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@Sam-Harper @jainshilpi 
do you happen to know when was the last time these producers (removed in this PR) were useful?

**Comment by Sam-Harper** [comment]
> @Sam-Harper @jainshilpi
> do you happen to know when was the last time these producers (removed in this PR) were useful?

No not off the top of my head exactly. My guess for this is when there were showershape variables not in the electron/photon that wanted to be used in the regression. Probably not been used for a while now as everything is in the electron/photon. If we need it back, we can always add it back but I would like to avoid doing that as much as possible. 

Its probably better to clean out dead code rather than having it hanging around, thanks @guitargeek

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24769	661272f
- cleanup of unused code (the removed producers were still loaded/constructed, but not running in mini/nano- AOD workflows)
- jenkins tests pass

**Comment by guitargeek** [comment]
Hi @slava77, I'm just curious to know how you could tell it doesn't run in the workflows. From my naive understanding, if it's in a sequence that is used like here in NanoAOD [1], then it runs each event. But apparently that doesn't seem to be the case. Can you please point me to an explanation? Thanks!

[1] https://github.com/cms-sw/cmssw/pull/24769/files#diff-6d69831bd3675c40ea80698b6ba12887R17

**Comment by Sam-Harper** [comment]
Hi @guitargeek , which exact tool Slava uses to determine this I dont know. However when CMSSW is run in unschedualled mode, it only runs modules whose output is used. So if nothing is consuming the module and no output module is writing it out, the module is simply not run. Our framework is actually pretty smart :)

**Comment by guitargeek** [comment]
Thank you Sam, that's what I wanted to know!

**Comment by slava77** [comment]
On 10/2/18 9:36 AM, Jonas Rembser wrote:
> Hi @slava77
> I'm just curious to know how you could tell it doesn't run in the
> workflows. From my naive understanding, if it's in a sequence that is
> used like here in NanoAOD [1], then it runs each event. But apparently
> that doesn't seem to be the case. Can you please point me to an
> explanation? Thanks!
> 


I'm often running workflows with --customise
Validation/Performance/TimeMemoryInfo.py
to monitor timing and memory technical performance.
It's then a matter of grepping for the module name in the log file

**Comment by guitargeek** [comment]
Thank you Slava, that is a very handy tool.

**Comment by fabiocos** [comment]
@slava77 @guitargeek indeed these modules do not spend time in wf 136.85

TimeReport   0.000000     0.000000     0.000000  electronRegressionValueMapProducer
TimeReport   0.000000     0.000000     0.000000  photonRegressionValueMapProducer

But also using the Tracer shows that they are initialized but never used in theevent processing:

++++ finished: begin stream for module: stream = 3 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin run for module: stream = 3 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin run for module: stream = 3 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin run for module: stream = 0 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin run for module: stream = 0 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin run for module: stream = 2 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin run for module: stream = 2 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin run for module: stream = 1 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin run for module: stream = 1 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin run for module: stream = 1 label = 'electronRegressionValueMapProducer' id = 1027
++++++ starting: begin run for module: stream = 2 label = 'electronRegressionValueMapProducer' id = 1027
++++++ finished: begin run for module: stream = 2 label = 'electronRegressionValueMapProducer' id = 1027
++++++ starting: begin lumi for module: stream = 3 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: begin lumi for module: stream = 2 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin lumi for module: stream = 2 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: begin lumi for module: stream = 3 label = 'electronRegressionValueMapProducer' id = 1027
++++++ finished: end lumi for module: stream = 3 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: end lumi for module: stream = 3 label = 'electronRegressionValueMapProducer' id = 1027
++++++ starting: end lumi for module: stream = 2 label = 'photonRegressionValueMapProducer' id = 2248
++++++ starting: end lumi for module: stream = 0 label = 'photonRegressionValueMapProducer' id = 2248
++++++ finished: end lumi for module: stream = 0 label = 'photonRegressionValueMapProducer' id = 2248
++++ starting: end stream for module: stream = 0 label = 'electronRegressionValueMapProducer' id = 1027

**Comment by fabiocos** [comment]
+1

cleaning of sequences

**Comment by fabiocos** [comment]
merge

**Pull request merged**
