### PR TITLE
bsunanda:Run2-hcx57 Utilize a test numbering scheme for HGCal in SIM step (as in #12572)

### PR DESCRIPTION
**Pull request by bsunanda**
To avoid the garbage history information which got collected for bsunanda:Run2-hcx53. 
This is the first step for SIM for hexgonal cell for HGCal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@bsunanda Just to confirm, this step does not yet make the jump into hex cells, but creates the abstraction layer that makes square and hex cell geometries similar to some extent?

**Comment by bsunanda** [comment]
@lgray Yes it does not. I am working on that
________________________________

**Pull request merged**
