### PR TITLE
Move all EDM plugins to the plugins/ directory

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
Nice!

**Comment by fwyzard** [comment]
I do get the same error testing locally:
> ----- Begin Fatal Exception 16-Nov-2017 16:51:12 CET-----------------------
> An exception of category 'PluginLibraryLoadError' occurred while
>    [0] Constructing the EventProcessor
> Exception Message:
> unable to load /data/user/fwyzard/CMSSW_10_0_0_pre1/lib/slc7_amd64_gcc630/poisoned/plugin-poisoned-HLTriggerspecial.so because /data/user/fwyzard/CMSSW_10_0_0_pre1/lib/slc7_amd64_gcc630/poisoned/plugin-poisoned-HLTriggerspecial.so: cannot open shared object file: No such file or directory
> ----- End Fatal Exception -------------------------------------------------

however I think this is a problem with the "poison" mechanism rather than with my changes - because I do see a plugin built for HLTrigger/special:
```sh
$ ls -lh lib/slc7_amd64_gcc630/pluginHLTriggerspecial*
-rwxrwxr-x. 1 fwyzard zh 2.3M Nov 16 16:47 lib/slc7_amd64_gcc630/pluginHLTriggerspecialAuto.so
```

@smuzaffar , is there a way to request a full build, with 10.0.x + this PR, instead of compiling the PR on top of an existing release ?

**Comment by smuzaffar** [comment]
@fwyzard , I am afraid that will still fail. Looks like there are packages still referring to the plugins you have removed. Trying running the following to find what is requiring these plugins
```
scram p CMSSW_10_0_X_2017-11-15-2300
cd CMSSW_10_0_X_2017-11-15-2300
cmsenv
grep DEFINE_FWK_MODULE $CMSSW_RELEASE_BASE/src/HLTrigger/special/src/SealModule.cc | sed 's|.*(||;s|).*||' | xargs -i cmsglimpse '{}' | grep -v '/HLTrigger/special/'
```
I get long with e.g.
```
src/Calibration/IsolatedParticles/python/isoTrack_cff.py: hltIsolPixelTrackL2FilterHE = cms.EDFilter("HLTPixelIsolTrackFilter",
src/Calibration/IsolatedParticles/python/isoTrack_cff.py: hltEcalIsolPixelTrackL2FilterHB = cms.EDFilter("HLTEcalPixelIsolTrackFilter",
```
```

**Comment by fwyzard** [comment]
I stand corrected, I'm really missing few plugins... patch in a bit

**Comment by fwyzard** [comment]
OK, now all the plugins mentioned in `.poisonededmplugincache` appear also in `.edmplugincache` ...

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fwyzard** [comment]
Well, yes, that happens if you merge some other PR first...

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
looks like this broke the build
see e.g. 
https://github.com/cms-sw/cmssw/pull/21037#issuecomment-346142090

@davidlange6 @fwyzard 
can we get a quick fix or is it better to revert?

**Comment by smuzaffar** [comment]
looks like a bug in checkdeps: for files which are moved  it is not treating them as changed files and that is why not creating poson files for them and checking out the dependent packages.
A full rebuild will show compilation errors as we see in DEVEL IBs now.

**Pull request merged**
