### PR TITLE
Phase2-gem60 Make a more realistic shielding around GE0

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a more realistic shielding around GE0

#### PR validation:

Tested using overlap checking tools (cmsShow as well as Geant4 internal)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @qliphy These are all DAS errors. Shall one redo the tests

**Comment by qliphy** [comment]
Please test
let's try again

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
