### PR TITLE
Low threshold triggers with PFHT

### PR DESCRIPTION
**Pull request by sudhaahuja**
Added the triggers proposed in this JIRA ticket - https://its.cern.ch/jira/browse/CMSHLT-1605, to the HT/MET Monitor

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@sudhaahuja please quantify the increase in the #bins

**Comment by sudhaahuja** [comment]
@mtosi - I do not understand your comment given above - 
"please quantify the increase in the #bins"
I did not change any bins in the code. I only added the new triggers as proposed in this ticket -  https://its.cern.ch/jira/browse/CMSHLT-1605

**Comment by mtosi** [comment]
adding new triggers means adding new plots
which then means adding bins...

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
-1

pending an answer from authors

**Comment by fabiocos** [comment]
@sudhaahuja @mtosi are these plots still needed? Otherwise I will just close the PR

**Comment by mtosi** [comment]
I would suggest to close this PR
if EXO and/or JME would need them, a dedicated PR should be made

**Comment by fabiocos** [comment]
@mtosi thanks, lacking activity and reaction from the author I close this PR, we may reopen or have a new one when it will be really needed

**Pull request closed without merging**
