### PR TITLE
L1T DQM timing plot upgrades - 101x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #23128 

and also of #23054 

This PR supersedes the initial backport #23053 that is currently deployed at P5.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

fastsim error is unrelated to this PR

**Comment by thomreis** [comment]
Hi @jfernan2 , @dmitrijus 
could you please approve this?

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
Successfully test and integrated in the Online DQM at P5.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
+1

integrated in CMSSW_10_2_0_pre4, not problem reported from validation

**Pull request merged**
