### PR TITLE
81X Update of MillePede production system (MPS)

### PR DESCRIPTION
**Pull request by ghellwig**
Summary of updates:
- tool to determine optimal parameters for the Z->mu mu mass constraint in MillePede for a given track selection (see slide 10 of [presentation at TkAl meeting 24-08-2016](https://indico.cern.ch/event/536885/contributions/2272807/attachments/1326335/1991545/SummaryPresentation_24_08_2016_.pdf))
  - updated default values in MPS
- update of the documentation in the template files
- moved MPS templates to a dedicated directory
- added script to create file lists for alignment and validation
  - ensures that all IOVs are well represented
  - allows random order of input files
  - used in September2016 alignment campaign
- fixed monitoring of used tracks in case of TwoBodyDecayTrajectories
- write out alignments, APEs, and surface deformations by default in MPS
- enable cosmics during collisions in MillePede workflow
- minor cosmetic changes

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
+1
@ghellwig: still it would be good if you can document why the changes in the Z peak parametrizations are preferred

**Comment by ghellwig** [comment]
@mmusich there are basically two reasons, one from first principles (i) and an empirical one (ii):

i. Pede assumes these parameters to be the first and second moment of the generator-level di-muon distribution within the applied selection. Therefore, I applied the same selection on the generator muons as are applied on the muon tracks in real data to obtain this distribution.

ii. Slide 10 in the linked presentation shows that the positive effect of the ZMuMu constraint is (slightly) stronger.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
