### PR TITLE
Introducing Stacks in CMSSW geometry (part II)

### PR DESCRIPTION
**Pull request by ebrondol**
The main goals of this PR are:
- update the TrackerTopology in order to have access of the stack info: I have added methods to access to the glued/stack info for each different strip subsystem (isStereo, isRPhi, isLower, isUpper). Moreover, the methods Glued() and Stack() returns the DetId of the double module itself.
- get the step3 run into the new geometry.

In order to do the second point three steps are needed:
1) fixing the Geometric Tracker Search introducing the stack concept and removing the DetsBrother
2) building the TrackerGeometry with a new GeomDet, which is StackGeomDet
3) adding in MeasurementTracker the possibility to build TkStackMeasurementDets

Moreover, the two cfg files that produces the clusters have been changed, just to temporary fix the workflow - another PR is requested to @thomaslenzi to fix it definitively.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ebrondol** [comment]
As we already discuss with the previous PR, the workflow should run in the upgrade scenario without keeping into account the L1 Track Trigger process in the second step and the Validation+DQM process in the third step.

**Comment by ebrondol** [comment]
All the errors are due to one of the two cfg files that produces the clusters (siPixelClusters). It should not affected the siPhase2Clusters. So, I have taken back the cfg file to the previous version. Please, test again and take this changes into account if you would like to test the RECO step into the upgrade workflow.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
please test

**Comment by mark-grimes** [comment]
With `runTheMatrix.py -w upgrade -l 10800` (Extended2023Muondev) I still get the reco step crashing, although with a different backtrace.  What I've tried is:

* running on CMSSW_6_2_SLHCDEV_X_2015-11-09-2300
* apply this PR, do full checkdeps (99 packages!) and compile
* start with the files from `runTheMatrix.py -w upgrade -l 10800`.
* add `process.schedule.remove( process.L1TrackTrigger_step )` to the step2 file (which then works).
* add `process.siPixelClusters.src = cms.InputTag('simSiPixelDigis', "Pixel")` to the step3 file, which gives the stacktrace below with or without that line.

Have I missed a step, or is there another pull request coming?
```
#4  <signal handler called>
#5  0x00007f27ea035d24 in SiPixelRawDataErrorSource::buildStructure(edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc472/cms/cmssw/CMSSW_6_2_SLHCDEV_X_2015-11-08-1100/lib/slc6_amd64_gcc472/pluginDQMSiPixelMonitorRawData.so
#6  0x00007f27ea0358ce in SiPixelRawDataErrorSource::beginRun(edm::Run const&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc472/cms/cmssw/CMSSW_6_2_SLHCDEV_X_2015-11-08-1100/lib/slc6_amd64_gcc472/pluginDQMSiPixelMonitorRawData.so
#7  0x00007f281bc70b10 in edm::EDAnalyzer::doBeginRun(edm::RunPrincipal const&, edm::EventSetup const&, edm::CurrentProcessingContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc472/cms/cmssw/CMSSW_6_2_SLHCDEV_X_2015-11-08-1100/lib/slc6_amd64_gcc472/libFWCoreFramework.so
```

SiPixelRawDataErrorSource is in DQM/SiPixelMonitorRawData, untouched by this PR.  It looks like that somehow needs updating for the changes made here.

**Comment by ebrondol** [comment]
Dear @mark-grimes ,

as I wrote in a previous comment 2 days ago, we agreed for this PR to have it run without keeping into account the L1 Track Trigger process in the second step and the Validation+DQM process in the third step. @boudoul and @delaere, please confirm if this is correct.

**Comment by boudoul** [comment]
grrrrr   I suspect we are in the bad things that we are struggling also for phase1  : process.SiPixelRawDataErrorSource.isUpgrade = cms.untracked.bool(True)
I think we should customize this nonsense by removing the SiPixelRawDataErrorSource process soemwhere during the dqm step, let me see if I can find a workaround (unless somebody is happy to do it)

**Comment by ebrondol** [comment]
@mark-grimes , sorry for the inconvenience. I will comment again this PR when is fixed.

**Comment by mark-grimes** [comment]
@boudoul 
> ...(unless somebody is happy to do it)

I can do the legwork but I'll need some guidance on what needs to be amended. I'll start with the steps above, take out SiPixelRawDataErrorSource and see what the next error is.  If I can't figure it out I'll contact you privately.

**Comment by mark-grimes** [comment]
Also, once this is working I'll request some 108xx tests are put in the list of automatic tests.

**Comment by ebrondol** [comment]
Dear @mark-grimes , for the SiPixelRawDataErrorSource, I am fixing this part in contact with the DQM expert. Once this is fixed (or skipped), the next error that will show up is again related with L1TrackTrigger... not sure how to fix it.

**Comment by delaere** [comment]
Concerning L1TrackTrigger, I would suggest to skip it in the automatic tests. The plan there is to fix the TK Primitives (up to stubs) within ~2 months, in time for 800, but the TTtrack reconstruction (AM, etc.) will take more time (half a year or more), as it has not only to be adapted to the technical changes, but also to the tilted geometry.

**Comment by mark-grimes** [comment]
Okay.  I'll put in customisations for the time being that disable it (and the other points above) so that the workflow runs.  Then with each pull request that fixes a particular part we can take the veto out of the customisation.

**Comment by mark-grimes** [comment]
merge

I was going to add the customisations at the same time but it's taking longer than expected.  Since the 108xx workflow is already broken adding this only improves the situation.  All the other tests pass.

**Comment by mark-grimes** [comment]
@ebrondol if you have fixes for any parts before I add the customisations to skip them (I'll ping you in any PRs) put them in new pull requests.

**Comment by ebrondol** [comment]
@mark-grimes, will do in the next days. Thanks a lot.

**Pull request merged**
