### PR TITLE
Add LHE filter to cut on VpT

### PR DESCRIPTION
**Pull request by perrozzi**
important filter to launch the production on MG5_aMC NLO V+jets
Thanks to @adewit 
@bendavid please cross-check
Validation ongoing, PR to master will follow

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/22006

**Comment by adewit** [comment]
Validation plots testing this filter: LHE-level V pT plotted after pythia+ this LHE filter (minimum V pT 50 GeV, maximum V pT 150 GeV), for W->ellnu, Z->nunu, Z->ellell, all +1jet. The initial number of LHE-events was 100k in each case.
Z->ellell:
[LHEfilter_validation_Zellell_50to150.pdf](https://github.com/cms-sw/cmssw/files/1673075/LHEfilter_validation_Zellell_50to150.pdf)
Z->nunu:
[LHEfilter_validation_Znn_50to150.pdf](https://github.com/cms-sw/cmssw/files/1673078/LHEfilter_validation_Znn_50to150.pdf)
W->ellnu:
[LHEfilter_validation_Wellnu_50to150.pdf](https://github.com/cms-sw/cmssw/files/1673079/LHEfilter_validation_Wellnu_50to150.pdf)

These look mostly as expected, although the W->ellnu fig is a bit bumpy. Possibly just a feature of limited stats, I'll add a plot of the W->ellnu W pT distribution without the LHE filter when it's ready.

**Comment by perrozzi** [comment]
+1
I agree the "bump" seems to be of statistical nature, approving

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
