### PR TITLE
add PixelTrack quality monitoring to `SiPixelPhase1MonitorTrackSoA`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to restructure `SiPixelPhase1MonitorTrackSoA` to use the pixel track quality information.
Two commits are proposed:
   * 1df6972 : add PixelTrack quality monitoring to `SiPixelPhase1MonitorTrackSoA`
   * 86af604 : SiPixelPhase1MonitorTrackSoA: restructure PixelTrack monitoring to filter for loose and above track quality

#### PR validation:

Run `runTheMatrix.py --what gpu -l 11634.506` on a `lxplus-gpu` node.
Obtained the following plot:

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but probably to be backported?
cc:
@VinInn @sroychow @vmariani

### CODE REVIEW

**Comment by VinInn** [comment]
ok. "As I was suspecting" 
edup and dup  are there (they are not promoted to legacy) and not supposed to be used for physics.
edup is even not fitted... (so the other params make no sense).

I propose to filter edup out for sure. Eventually dup as well (i.e. quality>=loose)
or make two folders.

Are those quadruplets only? Very surprised by the low number of "loose" w/r/t HP

**Comment by mmusich** [comment]
@VinInn 

> ok. "As I was suspecting"
> edup and dup are there (they are not promoted to legacy) and not supposed to be used for physics.
> edup is even not fitted... (so the other params make no sense).
> 
> I propose to filter edup out for sure. Eventually dup as well (i.e. quality>=loose)
> or make two folders.

OK.
Notice that @sroychow already left the provision for cutting below "loose", 

https://github.com/cms-sw/cmssw/blob/3fe21cfe88385750a8c8f3f1c6e2bc51bfac2823/DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc#L81-L82

https://github.com/cms-sw/cmssw/blob/3fe21cfe88385750a8c8f3f1c6e2bc51bfac2823/DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc#L124

but is is currently set to false.

https://github.com/cms-sw/cmssw/blob/3fe21cfe88385750a8c8f3f1c6e2bc51bfac2823/DQM/SiPixelPhase1Heterogeneous/plugins/SiPixelPhase1MonitorTrackSoA.cc#L123

> Are those quadruplets only? Very surprised by the low number of "loose" w/r/t HP

this is `11634.506_TTbar_14TeV+2021_Patatrack_PixelOnlyTripletsGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano`

so it's running 

```console
11634.506 2021_Patatrack_PixelOnlyTripletsGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano [1]: cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN,SIM -n 10 --conditions auto:phase1_2021_realistic --beamspot Run3RoundOptics25ns13TeVLowSigmaZ --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 9000,100 
                                           [2]: cmsDriver.py step2  -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2021 --conditions auto:phase1_2021_realistic --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --procModifiers gpu --customise HLTrigger/Configuration/customizeHLTforPatatrack.enablePatatrackPixelTriplets
                                           [3]: cmsDriver.py step3  -s RAW2DIGI:RawToDigi_pixelOnly,RECO:reconstruction_pixelTrackingOnly,VALIDATION:@pixelTrackingOnlyValidation,DQM:@pixelTrackingOnlyDQM --conditions auto:phase1_2021_realistic --datatier GEN-SIM-RECO,DQMIO -n 10 --eventcontent RECOSIM,DQM --geometry DB:Extended --era Run3 --procModifiers pixelNtupletFit,gpu --customise RecoPixelVertexing/Configuration/customizePixelTracksForTriplets.customizePixelTracksForTriplets
                                           [4]: cmsDriver.py step4  -s HARVESTING:@trackingOnlyValidation+@pixelTrackingOnlyDQM --conditions auto:phase1_2021_realistic --mc  --geometry DB:Extended --scenario pp --filetype DQM --era Run3 -n 100 
```

I chose this one only because it's in the PR tests short matrix, but I can run something else if it is relevant.

**Comment by VinInn** [comment]
```customizePixelTracksForTriplets``` so are triplets as well. OK!
I would say: plot quality for the whole collection and the rest cut "below" loose (hope will not confuse people)

**Comment by mmusich** [comment]
>  I would say: plot quality for the whole collection and the rest cut "below" loose (hope will not confuse people)

Sounds good (I can make it explicit on the axis title it's for "above loose" to avoid any possible confusion.

**Comment by mmusich** [comment]
>  I would say: plot quality for the whole collection and the rest cut "below" loose (hope will not confuse people)

addressed at 86af604.

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by VinInn** [comment]
btw now there is always the number of Layers stored in the track
https://cmssdt.cern.ch/lxr/source/CUDADataFormats/Track/interface/TrackSoAHeterogeneousT.h#0046

**Pull request merged**
