### PR TITLE
Make binning consistent and remove several plots in Offline DQM

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR make the binning of on track cluster charge histograms consistent and remove several plots in Offline DQM

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fioriNTU** [comment]
@fabiocos please consider to merge also this one, it reduce a lot the content of DQm histograms

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 could you please scrutinize the PR?

**Comment by jfernan2** [comment]
@fioriNTU Is it understood why the Historgram memory is increased despite you are removing histograms?

**Comment by fioriNTU** [comment]
@jfernan2 what you say is really surprising. I am just removing plots and rebinning a single histogram (reducing the number of plots), is it possible there is a bug in the report? I am sure this specific PR should produce a net reduction in memory usage for histograms.

**Comment by jfernan2** [comment]
@fioriNTU I can't tell since the test link does not exist any longer, but it says:
DQMHistoSizes: Histogram memory added: 579.83 KiB( 15 files compared)
I will check with @dmitrijus

**Comment by boudoul** [comment]
@jfernan2 , Maybe one should retrigger the tests (to get a fresh link) and also see if it is reproducble ?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
It seems the memory test could be fooled by the other commits that IB added on top of this PR. The new test will clarify. Sorry for the noise.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
The increase is there because other PRs were included in the test.
The latest test by @jfernan2 should show less memory usage.

I will check the actual reason for this memory change.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
