### PR TITLE
Clean up Utilities/StaticAnalyers scripts to avoid errors because of formatting.

### PR DESCRIPTION
**Pull request by gartung**
#### PR description:

Fix for this error found in `eventsetuprecord-get.txt`.

```
  File "./callgraph.py", line 36
    fields = line.split("'")
                           ^
TabError: inconsistent use of tabs and spaces in indentation
```
Also ran all of the python scripts through `autopep8 -i` and `flake8`  to catch any other errors.

#### PR validation:

Ran the scripts on output of IB static analyzer run.

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cms-bot/pull/1558

**Comment by mrodozov** [comment]
please test with  cms-sw/cms-bot#1558, #33875

**Comment by makortel** [comment]
+1

**Pull request merged**
