### PR TITLE
EGM VID IDs for 74X - PHYS14 tunings

### PR DESCRIPTION
**Pull request by lgray**
74X version of #9002

@ikrav @cmkuo

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Hi Lindsey,

Maybe for 74X it would be better to have a version of this PR that does not change what is stored normally in the miniAOD, since DigiReco of 74X MC is already running.
If we'll have a re-make of MiniAOD in a future 74X then you can make a second PR switching on the new IDs there.

**Comment by lgray** [comment]
Sure, that's fine with me. Getting dinner in a bit, will push a commit
later this evening.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@gpetruc These commits address the remaining issues of the IDs being contiguous between two 74X releases. The producer will complain about non-POG approved ID, but it is expected as these IDs are not approved for use on PHYS14 samples.

@slava77 ROOT6 vs. ROOT5 stuff coming soon.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9003	9cc037b
- last jenkins tests were successful and had no differences in comparisons with the baseline (as expected; comparisons don't cover the pat step
- ported the last commit to 75X to check it's identical to #9002 except for the part where the electron and photon ids are left as is: confirmed
- tested locally in CMSSW_7_4_X_2015-05-20-2300 using step5 in wf 25202 : 
    - (unnecessary) electronIDValueMapProducer is removed from the call list
    - output object sizes are unchanged (using 1 byte size comparison threshold)

**Comment by lgray** [comment]
@monttj Please give a +1 here as well! (this is just 74X backport of #9002)

**Comment by monttj** [comment]
+1
It is the same for 74X.

**Comment by lgray** [comment]
@slava77 @davidlange6 looks like a das problem for the minbias...

**Comment by davidlt** [comment]
There is a problem with servers DAS is running on. We will have random failures until problem is resolved.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9003	225dd32
- since the last sign-off for https://github.com/cms-sw/cmssw/pull/9003	9cc037b the additional changes in the code are the same as in the 75X version (additional HEEP ID, which is not running by default in the miniAOD)
- I confirmed using 25202 70 events that the products on disk are unchanged, based on branch size inspection.

**Comment by lgray** [comment]
@davidlange6 Any possibility to get a +1 here? It is the backport of #9002

**Comment by davidlange6** [comment]
@lgray - are the changes to miniaodtools really needed in this PR?

**Comment by lgray** [comment]
Yes, it removes an unnecessary module from the process.

-Lindsey

**Comment by davidlange6** [comment]
Are the git diffs correct - it seems to be adding one?

**Comment by lgray** [comment]
Ah, I was thinking only of the VID stuff.
I dont think that should be there, let me fix it.

-Lindsey

(Sent from my Nexus 6)

**Comment by davidlange6** [comment]
Thanks -it would make it much easier to convince myself that mini-AOD can not possibly be affected

**Comment by lgray** [comment]
@davidlange6 done

**Comment by slava77** [comment]
I think there was a problem with the web display
The caloJetMap is in the release file
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L136

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
refixing....

**Comment by slava77** [comment]
I don't think you need to
git just didn't manage to resolve that added code is already present. Now that you removed it explicitly, there's nothing that it can be confused about

**Comment by davidlange6** [comment]
+1

strange - ok. (github is still not happy, but now its been clarified).Thanks

**Pull request merged**
