### PR TITLE
Make L1Comparator a global module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This module is run in release validation and prohibits use of concurrent LuminosityBlocks.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
prompted by #25090

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
This is a technical PR. @benkrikler @rekovic Do you have any objections?

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
