### PR TITLE
 Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits [13.1.X]

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

plain backport of #42646, as [requested](https://github.com/cms-sw/cmssw/pull/42762#issuecomment-1718058774).

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42646

**Comment by mandrenguyen** [comment]
type muon

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge
   - Backport to intermediate release.

**Pull request merged**
