### PR TITLE
Run2-hcx141 Correct access of geometry for Hcal cells

### PR DESCRIPTION
**Pull request by bsunanda**
With Plan1 geometry of HCAL, access to geometry for getting position for a HCAL cell has changed and this is transmitted to some of the classes used for calibration.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Can you review and approve this PR?

**Comment by lpernie** [comment]
Hi @bsunanda , I see there are conflicts to be solved.
Could you also add a description for this PR?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie Added some description

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
