### PR TITLE
[10X] [L1T] [DQM] Adding HLT object matching for tag electron in EGamma

### PR DESCRIPTION
**Pull request by kreczko**
## Summary
Fixes issue https://its.cern.ch/jira/browse/CMSLITDPG-382: 
 - requiring single electron trigger
 - tag electron must match an HLT object of a fired trigger (within ΔR of 0.3 of the selected L1T jet).

## Dependencies
This PR depends on https://github.com/cms-sw/cmssw/pull/21822. Until this dependency is merged, please ignore commits 3cc1b47, 9b5d091, and 4baa92e.
The only two new commits are e4c22cf and 2da82f9.

## In addition
 - moved `L1TStage2CaloLayer2Offline::passesTrigger()` to L1TCommon:
```c++
bool passesAnyTriggerFromList(const std::vector<unsigned int> &triggers,
                              const edm::TriggerResults &triggerResults);
```
 - adjusted configuration names for trigger variables

Looking forward to the feedback.

### CODE REVIEW

**Comment by kreczko** [comment]
@cmsbuild please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be reviewed/merged please?

**Comment by fabiocos** [comment]
@kreczko @thomreis @dmitrijus This PR is not mergeable, please rebase it

**Comment by kreczko** [comment]
@fabiocos Have rebased the code using the github rebase feature.
It looks OK, but tests will show.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

@dmitrijus please sign again.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@jfernan2 this PR is claimed to be dependent on #21822, that is not signed. Could DQM experts please check that and clarify?

**Comment by thomreis** [comment]
#21822 is actually a subset of this PR. If this one is merged #21822 does not need to be merged anymore.

Both, #21822 and this PR needed to be signed again after a conflict was fixed. This has happened only for this PR but not for #21822.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
