### PR TITLE
fix patch area identification in ExpressionEvaluator

### PR DESCRIPTION
**Pull request by VinInn**
forgot that scram tool works only in a scram area...

### CODE REVIEW

**Comment by slava77** [comment]
there is an overlap now in changes proposed with https://github.com/cms-sw/cmssw/pull/9659
@lgray maybe you could cherry-pick Vincenzo's commit ... otherwise your PR #9659 will need a rebase after this gets merged

**Comment by VinInn** [comment]
I think  #9659 should add this or I can wait  #9659 to be merged and add mine...
the overlap is commenting out the debug flag...

**Comment by lgray** [comment]
Add this first... I can rebase.

-L

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
CMSSW_7_6_X_2015-06-28-2300 is now available and has a fix to the IB tests

**Comment by slava77** [comment]
@lgray 
I think you are better off to cherry pick the commit here.
Otherwise, if this gets merged first, you will end up with 75X and 76X branches for VID developments on separate tips, which may complicate the integration

**Comment by lgray** [comment]
@slava77 OK, will do in the morning.

**Comment by slava77** [comment]
I'm keeping this on hold for a moment pending clearance of interference with the VID PRs

**Comment by lgray** [comment]
Now ported to #9659 and #10059

**Comment by slava77** [comment]
-1
now absorbed in  #9659 and #10059
https://github.com/cms-sw/cmssw/pull/9950#issuecomment-119179642

**Pull request closed without merging**
