### PR TITLE
add missing stl container dictionaries for LHEXMLStringProduct changes

### PR DESCRIPTION
**Pull request by bendavid**
As per the discussion in
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3464/1/1/2/1.html

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
