### PR TITLE
Remove MuonToSimAssociatorBase, MuonToSimAssociatorByHits, and TrackAssociatorRecord as obsolete

### LINKED ISSUE #225: Remove obsolete TrackAssociatorRecord
Following #224 / https://github.com/cms-sw/cmssw/pull/34924

Done in https://github.com/cms-sw/cmssw/pull/34944

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

The cms-sw/cmssw#34924 removed last ESProduct from `TrackAssociatorRecord`, so the record can be removed now (as can the full subpackage as there would be nothing left).

The record was still being used in `testAssociatorRecoMuon`, but that test EDModule has been effectively dysfunctional since #8635 where all the corresponding ESProducers were removed. That EDModule, and the `MuonToSimAssociatorBase` and `MuonToSimAssociatorByHits` could have been removed already in #8635.

Resolves https://github.com/makortel/framework/issues/225.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34944	b19bdaa 
- code changes in reco are somewhat trivial (removing unused includes or update of package deps)
- jenkins tests pass

**Comment by perrotta** [comment]
+1
- Remove unused code and references to it
- Bypassing @cms-sw/analysis-l2 signature
- @abbiendi FYI

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
