### PR TITLE
Added monopole ionisation classes 

### PR DESCRIPTION
**Pull request by civanch**
This is a backport of #26048 - improved simulation of magnetic monopole ionisation. Should not affect mainstream simulation.

### CODE REVIEW

**Comment by civanch** [comment]
backport of #26048

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
