### PR TITLE
Extended HLT menus (pp and PbPb) for MC production (104X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Extended HLT menus (pp and PbPb) for MC production (104X)
Based on CMSSW_10_4_0_pre3

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Please sign for core (addOnTests)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald is this the final version for the HI MC production? I see that you have removed the legacy 2018v36 version, but I do not see other "frozen"-like versions. What is the proposal for the final setup here?

**Comment by Martin-Grunewald** [comment]
@fabiocos 
Indeed 2018v36 is now superseeded with the extended pp menu, adding more paths.
This new menu is the single pp menu we'll migrate forward (as needed for CMSSW developments
in future releases and release series.)

**Comment by fabiocos** [comment]
@Martin-Grunewald ok, so HIon is considered already as a production menu and not a development one?

**Comment by Martin-Grunewald** [comment]
Yes, from this PR on and for releases at least up to and including 10_5....

**Pull request merged**
