### PR TITLE
upgrade AMPT to v2.25t5

### PR DESCRIPTION
**Pull request by kurtejung**
Implementation of latest version of AMPT to include stability enhancements when running at LHC energies.  See changelog here: http://myweb.ecu.edu/linz/ampt/

### CODE REVIEW

**Comment by kurtejung** [comment]
Sorry - this should be titled "Upgrade AMPT to version 1.26t5 / 2.26t5" (not 1.25t5 / 2.25t5)

**Comment by kurtejung** [comment]
Hi All - just checking to see if there is some issue with the merge.  We are looking to generate an AMPT sample for the upcoming HI run very soon so there is some urgency attached to this PR.  Thanks.

**Comment by kurtejung** [comment]
Can someone please check this PR and/or start testing? It's been in standby for two weeks now.

Thanks

**Comment by kurtejung** [comment]
Hi Gen conveners, All,

We need to merge this request before the HI running period - please have a
look.

Thanks,
Kurt

**Comment by bendavid** [comment]
Which release is this ultimately needed in now?  75x?

**Comment by kurtejung** [comment]
Yes - I'd like to port to 75x and 76x.  Do I need to submit a new PR for
75X also?

**Comment by bendavid** [comment]
So in fact, please open pull requests for 75x and 80x

**Comment by kurtejung** [comment]
Hi Josh,

Thanks for the help.  I've submitted PR #12225 for 75x and PR #11932 (80x)
was automatically ported by CMSBuild.

-Kurt

**Comment by bendavid** [comment]
-1
(not needed in 76x)

**Comment by bendavid** [comment]
Thanks, have approved https://github.com/cms-sw/cmssw/pull/11932 and will do for 75x as well once everything is ok in 80x.

**Pull request closed without merging**
