### PR TITLE
BeamSpot Fitter: added parameters to the migrad functor to supersede EDM defaults

### PR DESCRIPTION
**Pull request by rmanzoni**
moving 75X PR fwd https://github.com/cms-sw/cmssw/pull/9852

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9858	a201ea8
- code changes are the same as in 75X and 74X versions
- jenkins tests pass and comparisons with baseline show differences only in the AlcaBeamMonitor plots with very small differences
- reco products are not affected

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
