### PR TITLE
add timing VS lumi (for HLT monitoring) 

### PR DESCRIPTION
**Pull request by mtosi**
it was https://github.com/cms-sw/cmssw/pull/14938
but because of issues w/ the synch between 81x and 80x
I preferred to have a dedicated branch for 80x

hope everything is fine, now
sorry for the confusion !
@fwyzard @dmitrijus @vanbesien @Martin-Grunewald @perrotta

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
In DQM/TrackingMonitor/interface/GetLumi.h, with respect to the 81X version you miss the    SQRT_S_13TeV in enum: I think you must fix it here.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport of #14937

**Comment by fwyzard** [comment]
+1

**Comment by perrotta** [comment]
@mtosi , @fwyzard : before testing further, I would like to see an answer to my comment above:
"In DQM/TrackingMonitor/interface/GetLumi.h, with respect to the 81X version you miss the SQRT_S_13TeV in enum: I think you must fix it here."

**Comment by perrotta** [comment]
-1

**Comment by mtosi** [comment]
it should be fixed, now
sorry, but I missed your comment last time
thanks a lot for the support !
@fwyzard @perrotta

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
