### PR TITLE
[Backport of 43805 to 14_0_X] Geometry: add Phase2 scenarios D107 = T32+C17+M11+I17+O9+F8 and D108 = T35+C19+M11+I17+O9+F8

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Backport of #43805 to 14_0_X branch. Addition of two Phase2 geometry scenarios:

- D107 = T32+C17+M11+I17+O9+F8 
- D108 = T35+C19+M11+I17+O9+F8

#### PR validation:

Code compiles and run (just moved from 14_0_X to 14_1_X today, tests ok in 14_0_X).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 28434.0,28834.0

**Comment by bsunanda** [comment]
+geometry

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
