### PR TITLE
 switch RAW repack compression to LZMA-4

### PR DESCRIPTION
**Pull request by slava77**
Based on tests by @mandrenguyen this saves 15% in output size.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
hold

based on https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2055/1/3/1/1/1/1/1/1/1/1/1/2/1/1/1/1.html

**Comment by fabiocos** [comment]
@slava77 I would imagine that we may close this PR, do you agree?

**Comment by slava77** [comment]
ok, closing

**Pull request closed without merging**
