### PR TITLE
Position Calc Fix 7_4_12pX

### PR DESCRIPTION
**Pull request by argiro**
removed caching of CaloGeom

### CODE REVIEW

**Comment by slava77** [comment]
Thanks, the history makes sense now.
[checks  before signing this one will be done in the mainstream 74X]

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11429 80f2bcf4a360de370059f8edcea6464c0e69e77d

Fixing buggy code related to the ECAL 2D position that was causing sporadic crashes. There should be no change in monitored quantities. #11415, #11417, and #11418 are the 74X, 75X, and 76X versions of this PR, and they have either been already merged or approved by Reco.

The code change fixes incorrect code. There are no Jenkins tests for this special branch. Additional testing was done for #11417 and found no significant changes in quantities or timing.

**Comment by lgray** [comment]
@davidlange6 @slava77 I think this one can be closed (it points at patchX branch, 7_4_X version already merged).

**Comment by lgray** [comment]
@argiro can you close this PR? Thanks!

**Comment by argiro** [comment]
fix already merged in other PR

**Pull request closed without merging**
