### PR TITLE
Initialize member data in PerigeeTrajectoryError

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

UBSAN reported reading uninitialized value of type bool.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- workflow = 13234.0,1337.0,136.759

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1
Crash test unrelated to this PR

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
