### PR TITLE
Common tkal dataset writing script

### PR DESCRIPTION
**Pull request by hroskes**
Trying to move towards a common interface for writing alignment datasets.  I start from the MillePede script and add functionality to write dataset files in the HipPy syntax as well.

I was holding off on making this PR because I wanted to replace Alignment/OfflineValidation/python/TkAlAllInOneTool/dataset.py with use of this script but didn't get a chance.  I don't want to wait any longer because of potential merge conflicts.

cc @connorpa @adewit @mmusich

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@hroskes could you please rebase this PR on a recent IB?

**Comment by pohsun** [comment]
please test

**Comment by hroskes** [comment]
Sorry I thought I had covered those.

**Comment by pohsun** [comment]
please test

**Comment by hroskes** [comment]
@smuzaffar  would it be worth checking in the code-checks that all new python files have `from __future__ import print_function` at the top?

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
