### PR TITLE
Add a tool to convert data to the .raw format used as input by the HLT [12.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add `convertToRaw`, a script that converts RAW data stored in one or more EDM .root files into the .raw file format used as input by the HLT.

```
usage: convertToRaw [-h] [-o PATH] [-f EVENTS] [-l EVENTS] [--one-file-per-lumi] FILES [FILES ...]

Convert RAW data from .root format to .raw format.

positional arguments:
  FILES                 input files in .root format

optional arguments:
  -h, --help            show this help message and exit
  -o PATH, --output PATH
                        base path to store the output files; subdirectories based on the run number are automatically created (default: )
  -f EVENTS, --events_per_file EVENTS
                        split the output into files with at most EVENTS events (default: 50)
  -l EVENTS, --events_per_lumi EVENTS
                        process at most EVENTS events in each lumisection (default: 11650)
  --one-file-per-lumi   assume that lumisections are not split across files (and disable --events_per_lumi) (default: False)
```

The default behaviour is to process a single luminosity section at a time, in order to support luminosity sections split across multiple files and a limit on the number of events in each lumisection.

If neither of these features is needed (_i.e._ if lumisections are not split, and all events should be converted) the `--one-file-per-lumi` can be used to process all data with a single job, speeding up the conversion considerably.

#### PR validation:

The files produced by `convertToRaw` can be used as input by an online-like HLT job.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38519 .

### CODE REVIEW

**Comment by fwyzard** [comment]
backport https://github.com/cms-sw/cmssw/pull/38519

**Comment by fwyzard** [comment]
please test

To make the bot happy. even if the new tool does not affect any workflow.

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
