### PR TITLE
Phase2-hgx127 Geometry definition of HF Nose detector

### PR DESCRIPTION
**Pull request by bsunanda**
This is a new detector proposed for Phase2 to be sitting just in front of current HF

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Pull request merged**
