### PR TITLE
Remove some const-away casts from AlCa

### PR DESCRIPTION
**Pull request by makortel**
To clean up static analyzer reports.

Tested in CMSSW_10_4_X_2018-10-25-2300, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
Added one case in `CocoaUnitsTable.cc` that I missed earlier.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
