### PR TITLE
[DQM-HLT] clang-tidy Performance inefficient vector operation suggestion applied

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by missirol** [comment]
+hlt

This will start the tests, I let others stop them if they think it's overkill.

**Comment by missirol** [comment]
@cms-sw/dqm-l2 , kind ping to review this PR.

(I dare say it could be merged right away in any case.)

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
