### PR TITLE
Pixel Heterogeneous DQM: add module rechit @cpu / @gpu comparisons [Backport to 12.4.X] 

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:

Backport of #37860 

#### PR validation:
Tests with pixelOnly wfs pass.

### CODE REVIEW

**Comment by sroychow** [comment]
type trk

**Comment by sroychow** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503, 11634.506, 11634.583, 11634.587
- workflow = 11634.501
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by sroychow** [comment]
enable gpu

**Comment by sroychow** [comment]
please test

**Comment by sroychow** [comment]
please test

**Comment by sroychow** [comment]
backport of #37860

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Succesfully merged in master since CMSSW_12_5_X_2022-05-20-1100

**Pull request merged**
