### PR TITLE
Added cmath header

### PR DESCRIPTION
**Pull request by Dr15Jones**
Previously, the cmath header was being indirectly included via
a boost header. In later versions of boost cmath was removed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This fixes problems in the CMSSW_10_2_DEVEL_X IB where we are testing the new boost 1.67.

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
