### PR TITLE
update trajectory filters (minNumberOfHits --> minNumberOfHitsForLoopers)

### PR DESCRIPTION
**Pull request by mtosi**
as requested by @slava77 
this PR is the same code update as in PR https://github.com/cms-sw/cmssw/pull/13421
but for 81x

@Martin-Grunewald @perrotta @rovere @VinInn

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by cvuosalo** [comment]
@mtosi: Please fix the reference in the PR description -- it should be #13421.

**Comment by cvuosalo** [comment]
+1

For #13436 91f9442cc50bce746314e39beb67ed4e67454f9e

Code clean-up of trajectory filters. There should be no change in monitored quantities. #13421 is the 80X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-02-22-1100 show no significant differences, as expected.

**Comment by mtosi** [comment]
can this PR be integrated ?
thanks

**Comment by Martin-Grunewald** [comment]
after the l1extra migration!

**Comment by davidlange6** [comment]
this PR looks obsolete (and would need rebasing) - closing for now.

**Comment by mtosi** [comment]
I'm preparing a new branch in 81x
hope it is fine

**Pull request closed without merging**
