### PR TITLE
Add a flag to prevent storage of LHEXMLStringProduct

### PR DESCRIPTION
**Pull request by fabiocos**
LHEXMLStringProduct is no more really used in production, and it is creating memory issues keeping on hold production in 93X. This PR adds a boolean flag as untracked parameter to activate/deactivate the storage of the xml output into the product, setting the default to "false" (i.e. do not store).

With the opportunity I fixed also the ExternalLHEAsciiDumper analyzer that was supposed to extract the xml file out of the edm root output, and that was no more working.

Both the "false" and "true" option have been tested in wf 512 (10 events), with a visible reduction of the final file size (84kB vs 112kB), and when the option was true the dumper was used to extract the xml file (216 kB after de-compression), proving that is again functional.

### CODE REVIEW

**Comment by fabiocos** [comment]
@Dr15Jones @bendavid @franzoni @vlimant I assume that this is what we want to get rid of the memory problem in 93X (at least part of it) without losing the possibility to optionally save and extract the xml file

**Comment by Dr15Jones** [comment]
> @Dr15Jones @bendavid @franzoni @vlimant I assume that this is what we want to get rid of the memory problem in 93X (at least part of it) without losing the possibility to optionally save and extract the xml file

From my point, it solves the file merge problem. It is unknown to me if this solves a memory problem as well.

**Comment by fabiocos** [comment]
@Dr15Jones to be verified, I agree, but it is something that anyway we want to have

**Comment by fabiocos** [comment]
addOn failures look unrelated to this PR, let's retry

**Comment by fabiocos** [comment]
please test

**Comment by perrozzi** [comment]
thanks Fabio. So, as far as I understand LHEXMLStringProduct was storing the LHE file as such and was used by the ExternalLHEAsciiDumper to dump it in case of need.
Always according to my understanding there is another copy of the LHE content denoted as "c++ translation" through LHEEventProduct and LHERunInfoProduct that saves all the important info but then there is no direct way to retrieve the original LHE file as it was.
I guess that one could always write another dumper and would just be a matter of formatting it.
I personally used the LHEXMLStringProduct in the past but only rarely, and maybe we can think of removing it if needed to solve merge (and memory?) issues.

**Comment by fabiocos** [comment]
@perrozzi in the present implementation nothing changes from the point of view of file structure (the product stays there) and provenance (I added an untracked parameter), but by default the product will be empty, so taking very little space. This should hopefully solve at least part of the problems keeping the production on hold (@kpedro88 FYI)

The LHEXML product was meant to store the XML file as we were doing in the past, but I understand this is no more the default since quite sometime. The C++ translation is what the CMS FW is practically using in its workflow, the xml can be read to build it with the other code in the package, here it is done on the fly.

I would suggest to move forward with this for the short term. If then the GEN group has plans for a deeper revision of the code he is welcome to present them. But be careful when you modify the file content, this should not happen in the middle of a production campaign.

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
