### PR TITLE
HLT migration and IrradiationBiasCorrection (110X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT migration to 11_0_0_pre4 and setting IrradiationBiasCorrection=true

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

changes are concentrated in the 2021 test workflow, affected by this menu update

**Pull request merged**
