### PR TITLE
HLTTauDQM: fixed empty hpstau trg object histograms

### PR DESCRIPTION
**Pull request by slehti**
HLT Tau pt,eta,phi histograms empty with HPS PFTau paths. Fixed.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@slehti the DQM comparison is not showing any difference, from the purpose of this PR I would expect to see some difference, could you please explain?

**Comment by slehti** [comment]
Directory PFTaus, paths 
HLT_DoubleMediumChargedIsoPFTauHPS35.. HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27... HLT_IsoMu20_eta2p1_MediumChargedIsoPFTauHPS35...
histograms TrigTauEt, TrigTauEta, TrigTauPhi

These were not filled before this fix.

**Comment by fabiocos** [comment]
@slehti I assume you verified yourself that the plots are filled, because in the test run in this PR it does not look to be the case, according to the above report and also rerunning the plots of 10824 on my own

**Comment by fabiocos** [comment]
+1

**Pull request merged**
