### PR TITLE
Move functions filling common provenance to IOPool/Provenance

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by smuzaffar** [comment]
@wddgit , can we avoid new package here?

**Comment by Dr15Jones** [comment]
@smuzaffar it was my suggestion to create the new package. We need to minimize coupling between the PoolSource, PoolOutputModule and the new 'micro' AOD output module.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
