### PR TITLE
Demangled log printout of Pedereader

### PR DESCRIPTION
**Pull request by phnattla**
#### PR description:

Demangled PedeReader output to make logs more readable

#### PR validation:

Used the following command to validated the changes:

```
cmsDriver.py stepHarvest2 -s ALCAHARVEST:SiPixelAliHGCombined --conditions 140X_dataRun3_Express_v3 --scenario pp --data --dasquery='file dataset=/StreamExpress/Run2024F-PromptCalibProdSiPixelAliHGComb-Express-v1/ALCAPROMPT run=383496' --custom_conditions=PCLThresholds_HG_Test_01,AlignPCLThresholdsHGRcd,frontier://FrontierPrep/CMS_CONDITIONS
```

@mmusich @henriettepetersen @TomasKello

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild ping?

**Comment by mmusich** [comment]
tests seem stuck here. @smuzaffar can you unstuck them?

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Comment by phnattla** [comment]
> @phnattla can you backport it as well?

Sure, I can look into that

**Pull request merged**
