### PR TITLE
get rid of UB in `TrackListMerger`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In partial response to https://github.com/cms-sw/cmssw/issues/35036#issuecomment-1044139169.
Followed suggestion at https://github.com/cms-sw/cmssw/issues/35036#issuecomment-982747450.

#### PR validation:

`cmssw` compiles, also run `runTheMatrix.py -l limited -j 8 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jpata** [comment]
as before, I'm running UBSAN offline to confirm, ETA 1 day.

**Comment by jpata** [comment]
+reconstruction
- technical bugfix
- confirmed the UBSAN error goes away

**Comment by perrotta** [comment]
Thank you @mmusich 
Not for this PR (I'll merge it as soon as bot resurrects...), but taking into account the static analizer reported logic error that vector `algo` could have size 0 at L472 of TrackListMerger.cc, shouldn't a check for `ngood>1` be anticipated before that line, instead of having it later at L507?

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@perrotta 

>  but taking into account the static analizer reported logic error that vector `algo` could have size 0 at L472 of `TrackListMerger.cc`, shouldn't a check for `ngood>1` be anticipated before that line, instead of having it later at L507?

The issue is already there in IBs:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_4_X_2022-03-24-2300/slc7_amd64_gcc10/llvm-analysis/index.html

I can take care of it with some other clean-up at a later time. I gather it's not a request for an immediate fix.

**Pull request merged**
