### PR TITLE
[12_6_X] Nano: fix and additions to collection matching, remove cross-cleaning

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

Fill in a few gaps in the matching between collections in Nano, remove the object cleanmask branches.

#### PR validation:

Done in #40162

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40162, relevant for a 12_6 nano

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

(for some reason, changes from #40224 are also visible in the comparisons...)

**Comment by mandrenguyen** [comment]
backport of #40162

**Comment by swertz** [comment]
> +reconstruction

@mandrenguyen it is strange, the `reconstruction-pending` label is still there :thinking:

**Comment by swertz** [comment]
@cms-sw/orp-l2 kind reminder, anything preventing this to go in?

**Comment by rappoccio** [comment]
> @cms-sw/orp-l2 kind reminder, anything preventing this to go in?

We wait until the master branch is successfully integrated before doing the backports, doing this now.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
