### PR TITLE
Run2 sim16 Add scenarios for T1/T2/BCML2 for post LS2 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
Add facilities for flux studies in T1/T2 region in PostLS1 and PostLS2 scenario
Avoid unwanted warnings from GEM geometry builder during initialization

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda I'm about to submit a PR for the Run3 workflow that will conflict with this one. Can we put this one on hold until that one goes in? That way, this one can be tested with the full workflow.

**Comment by kpedro88** [comment]
hold

**Comment by bsunanda** [comment]
@kpedro88 What is the status of the other PR. Could you please unhold this when appropriate

**Comment by kpedro88** [comment]
@bsunanda waiting on a fix related to Phase1 pixel DQM, hopefully it will be resolved soon

**Comment by ianna** [comment]
@kpedro88 - any news?

**Comment by kpedro88** [comment]
just waiting for one signature now...

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Any news?

**Comment by kpedro88** [comment]
now just waiting on @davidlange6 to merge #19889

**Comment by bsunanda** [comment]
@kpedro88 Can you untold this? I shall try to resolve the conflict

**Comment by kpedro88** [comment]
unhold
You can rebase onto the latest IB following http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@kpedro88 @ianna @civanch Please approve this

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda should https://github.com/cms-sw/cmssw/blob/master/Geometry/CMSCommonData/python/cmsExtendedGeometry2019XML_cfi.py be updated to use the new XML files introduced in this PR, or will that be done in a subsequent PR?

**Comment by bsunanda** [comment]
@kpedro88 It will be done in a subsequent PR. Please approve this

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
