### PR TITLE
Improvements to All In One validation tool

### PR DESCRIPTION
**Pull request by hroskes**
See this hypernews
https://hypernews.cern.ch/HyperNews/CMS/get/tif-alignment/312.html
for details of these new features.  Also includes some bugfixes, and removing a lot of duplicated code.

### CODE REVIEW

**Comment by frmeier** [comment]
The TkAlignment conveners endorse this PR. Due to ongoing work we will aks for backports.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@hroskes - this pr does not merge - please rebase.

**Comment by diguida** [comment]
@davidlange6 
@mmusich has a fixed version of the branch. @hroskes you have to cherry pick his commit

**Comment by hroskes** [comment]
@davidlange6 @diguida @mmusich 
Thanks! I think this worked

**Comment by mmusich** [comment]
+1 
Changes in template configuration and improvements in the validation tool

**Comment by mmusich** [comment]
@cmsbuild please notice the change

**Comment by frmeier** [comment]
> This pull request requires discussion in the ORP meeting before it's merged.

I cannot attend the meeting but if you need some information from the TkAlignment conveners please ask us beforehand and we are happy to provide you with answers.

**Comment by ktf** [comment]
@cmsbuild please test

**Comment by hroskes** [comment]
Removed cosmics parallel templates again, which were accidentally put back in.

**Comment by hroskes** [comment]
I don't think these changes could have caused the tests to fail... they're nothing to do with alignment

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by hroskes** [comment]
Thank you!

**Comment by mmusich** [comment]
+1
Changes in template configuration and improvements in the validation tool

**Comment by davidlange6** [comment]
+1

**Pull request merged**
