### PR TITLE
clang check misc-string-compare

### PR DESCRIPTION
**Pull request by davidlange6**
for comment (and likely not mergeable - this is what clang-tidy check misc-string-compare does

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
FWCore is fine

**Comment by alja** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

looks OK

a link to smth like this in the description would be nice
https://clang.llvm.org/extra/clang-tidy/checks/misc-string-compare.html

**Pull request closed without merging**
