### PR TITLE
[backport of #20672] New Candidate+Point seeded tracking region producer for Tau HLT tracking

### PR DESCRIPTION
**Pull request by tstreble**
Adds a new tracking region producer for HLT Tracking.
Provides same functionality than existing CandidateSeededTrackingRegion and PointSeededTrackingRegion producers + introduces new functionality with combination of candidate+point-seeded regions.
Once integrated and HLT configuration is updated, possible to make CandidateSeededTrackingRegion and PointSeededTrackingRegion producers deprecated.

This is the 92X back port of #20672

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Looks like the backport PR is missing a file from the 94 PR.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1
Identical to #20672 in the master, same comments apply:
- A new CandidatePointSeededTrackingRegionsProducer is introduced, to be used in HLT
- It is designed so that it can eventually replace the CandidateSeededTrackingRegionsProducer and PointSeededTrackingRegionsProducer, with dedicated setting of the parameters; those two producers will then be deprecated
- Also moving all those producers in the RecoTracker/TkTrackingRegions package
- No differences in jenkins tests (which is ok, since the new producer is not yet in use)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #20672 in the master

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
