### PR TITLE
Update Reconstruction_Data for move of jetCorrectorsForReco to Task

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Following the migration of jet reconstruction sequences to Task in #27887 and the failure in wf 140.54 deriving from this move discussed in #27919 , the updated suggested by @jeongeun is provided. 

#### PR validation:

Test wf 140.54 and 136.85 run successfully.

### CODE REVIEW

**Comment by fabiocos** [comment]
type bug-fix

**Comment by fabiocos** [comment]
please test workflow 140.54

**Comment by fabiocos** [comment]
@slava77 @perrotta @jeongeun FYI

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
> @slava77 @perrotta @jeongeun FYI

Thank you.
This seems fine.

**Pull request merged**
