### PR TITLE
Fix to 39434.502/501

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Solves issue :

- https://github.com/cms-sw/cmssw/issues/36661

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
enable gpu

**Comment by AdrianoDee** [comment]
test parameters:

workflows = 39434.501,39434.502,39434.5

**Comment by AdrianoDee** [comment]
test parameters:

workflows = 39434.501,39434.502,39434.5

**Comment by AdrianoDee** [comment]
enable gpu

**Comment by AdrianoDee** [comment]
please test

**Comment by perrotta** [comment]
urgent
(Thank you @AdrianoDee )

**Comment by jpata** [comment]
Are the changes observed in 11634.506 understood? Is it coming from this bugfix, or is it a known irreproducibility?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_3_X_2022-01-14-1100+e2955f/47866/validateJR/all_OldVSNew_TTbar14TeV2021pixel3GPUwf11634p506/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_3_X_2022-01-14-1100+e2955f/47866/validateJR/all_OldVSNew_TTbar14TeV2021pixel3GPUwf11634p506/all_OldVSNew_TTbar14TeV2021pixel3GPUwf11634p506c_log10recoTracks_pixelTracks__RECO_obj_p.png
image

**Comment by AdrianoDee** [comment]
This should be a known irreproducibility. The only module that is in common with 11634.506 is modified with the phase2 tracker procmodifier so I don't see any possible interference.

**Comment by jpata** [comment]
+reconstruction
- bugfix for #36661
- no relevant reco changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
