### PR TITLE
fix tracking DQM client config

### PR DESCRIPTION
**Pull request by mtosi**
there was a bug/typo in the config (a coma was missing) which prevented the proper functionality
it is fix, now
@rovere @VinInn

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by rovere** [comment]
Please back-port to 80X and ask for its inclusion.

**Comment by davidlange6** [comment]
+1

**Comment by dmitrijus** [comment]
How about 80X?

**Comment by mtosi** [comment]
ciao
because the corresponding PR in 80x (https://github.com/cms-sw/cmssw/pull/14448) was (and actually is) still open
the fix is already there
https://github.com/cms-sw/cmssw/pull/14448/commits/ab3d7a4b573480ff9834c74166ec319cd0ee31ff

or am I not getting your comment ?

**Comment by dmitrijus** [comment]
Hi, just asked if there was such pull request.
Since they title didn't match and there were no references, I wasn't able to find it.

It's now more clear - I will ask that PR to be merged.

**Comment by mtosi** [comment]
thanks !

**Pull request merged**
