### PR TITLE
additional features for alignment validation dmr plotting tool - backport

### PR DESCRIPTION
**Pull request by ssthr**
Two additional features to the All-In-One Alignment Validation tool are provided in separate commits.

-`parallel merging of DMR histos`: An option is given to merge the root dmr histograms in parallel to save runtime. Call tool with `--mergeOfflineParallel`-flag to activate the feature.

-`statistical measures`: Several statistical measures of potential interest are printed out for each DMR validation. Includes several p-Values to judge the significance of differences between the distributions and an estimate for the alignment uncertainty.

Further details can be found at:
https://indico.cern.ch/event/649310/contributions/2673094/attachments/1502539/2340536/presentation.pdf

backport to 92X of #20094

### CODE REVIEW

**Comment by arunhep** [comment]
@ssthr please open a PR in master (93X) as well.

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
@ssthr ah found the corresponding one in 93X ! PR #20094  Please keep the title same with explicit mention of [92X] and [93X]

**Comment by arunhep** [comment]
backport of #20094

**Comment by mschrode** [comment]
@arunhep do you want us to change the title of this PR to match the one of #20094 or can it stay as it is? Thanks!

**Comment by arunhep** [comment]
please change the title of this PR. 
Thanks.

**Comment by mschrode** [comment]
Thanks @ssthr !

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
