### PR TITLE
Fix undefined references in UBSAN IBs

### PR DESCRIPTION
**Pull request by davidlt**
The following resolves `undefined reference to` issues from the linker noticed in `CMSSW_10_0_UBSAN_X_2017-11-19-2300`.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by davidlt** [comment]
I think, those tests are already failing in normal IBs.

**Comment by perrotta** [comment]
please test with #21186

**Comment by davidlt** [comment]
I see that `HLTrigReport.h` was moved to a different place. I will update the PR.

**Comment by perrotta** [comment]
#21422 should have been taken care of it: please check it before committing anything here

**Comment by slava77** [comment]
this is fixed in CMSSW_10_0_X_2017-11-22-1100
Jenkins is not ready yet to switch to it. It looks like it should be in an hour or so

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
please test with #21186

**Comment by slava77** [comment]
@cmsbuild please abort

**Comment by slava77** [comment]
please test with #21186

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21396	fcd977b
- implemented as described; this is technical outside of the scope of the UBSAN build
- jenkins tests pass; the differences reported are due to gensim file i/o which apparently still lead to the same inputs.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
