### PR TITLE
[Backport 124X] OS requirement for Triple Muon seeds in the uGT emulator

### PR DESCRIPTION
**Pull request by elfontan**
Backport of https://github.com/cms-sw/cmssw/pull/40060 to CMSSW 12_4_X.

#### PR description:
This PR contains a fix in the correlation class to handle the three-body conditions in order to include the possibility to read the OS requirement for TripleMu seeds with the three-muon invariant mass requirement.
Reference PR: https://github.com/cms-sw/cmssw/pull/33911.

#### PR validation:
Basic tests performed successfully starting from CMSSW_12_4_X_2022-11-21-2300.
> cmsrel CMSSW_12_4_X_2022-11-21-2300
> cdCMSSW_12_4_X_2022-11-21-2300/src
> cmsenv
> git cms-addpkg L1Trigger/L1TGlobal
Added relevant files in _L1Trigger/L1TGlobal_.
> scram b distclean 
> git cms-checkdeps -a -A
> scram b -j 8
> scram build code-checks
> scram build code-format

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/33911

**Comment by rappoccio** [comment]
+1

**Pull request merged**
