### PR TITLE
Add GlobalCache to PileupJetIdProducer to improve startup performance.

### PR DESCRIPTION
**Pull request by wddgit**
Without the GlobalCache the startup time is proportional
to the number of streams and the time to initialize the
GBRForest is significant. Several of the other data members
that do not change after construction are needed to
initialize the GBRForest, so I also moved all those
into the GlobalCache (which also slightly improves
performance).

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
The intent is that after merging this PR the module will give identical results as before. I tested simply by putting in print statements for the mvas and idflags that are calculated and also all the parameter values I moved around. Then I compared the output before and after in a runTheMatrix test that runs it (25.0). All was identical. It would be nice if there was an expert who looked also at some histograms just to double check.  I also ran under igprof and verified the initialization time for the GBRForest initialization time is now constant and not proportional to the number of streams.

I noticed two other things in this code that I did not change, but I will change them if someone asks. First, the produceJetIds configuration option looks like it will cause an exception to be thrown if it is ever set to False. Seems like it and the code related to the False value could be deleted. Second, the tmvaNames_ data member seems pointless as it is now implemented. It could also be removed. Let me know and I will add additional commits to this PR to remove those things. I left them as is in the current version of the PR.

@Dr15Jones

**Comment by Dr15Jones** [comment]
This modification was chosen based on igprof measurements of time spent initializing jobs.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The test failures are unrelated to this pull request. The input files needed for the tests are unavailable.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22843	0600847
- the changes are technical, in line with the PR description
- jenkins tests pass and comparisons with baseline show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
