### PR TITLE
Clean Validation/Performance

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Remove obsolete code (the "CMS performance suite" of the beginning of Run1) no more used to avoid waste of time in maintaining and testing unused stuff. Move the digi dumper to a more appropriate location, nowadays SimGeneral/Debugging by @rovere looks appropriate (and the added code does not interfere with the existing one).

#### PR validation:

All the kept code is functional:

- cmsScimark2 runs and produces plots (probably of little interest but it does not harm)

- the digi dumper is running and producing output (in case of visual inspection of digis)

- a number of fragments used to set Timing and SimpleMemory services are in use and of course kept

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar @davidlange6 as far as I can see the code I have removed is unused since about 10 years, forgotten since when @VinInn and @dpiparo have started PyReleaseValidation. 

@slava77 @perrotta I understand that you performance studies are totally independent on this package and rely on different tools, please correct me in case.

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar comments? Doubts? Suggestions?

**Comment by Dr15Jones** [comment]
no comment from me

**Comment by fabiocos** [comment]
@Dr15Jones so may ```core``` sign? :-)

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
