### PR TITLE
Update Run3 GEM to use the eMap from the DB

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Fix for GEM crashing in Run3 data due to the emap not being read from the database. This patch instructs run3 to also use dbEmaps, as was done in slice test (its a minimal change as currently only slice test and run 3 emaps are in the db).

#### PR validation:

I tested on one of the files [1] and it no longer crashes. There are still warnings of the form
 
 %MSG-e BadDigiInput:  GEMRecHitProducer:gemRecHits 11-Mar-2020 11:39:34
 CET  Run: 335670 Event: 4434
 Failed to find GEMEtaPartition for ID  Re -1 Ri 1 St 1 La 2 Ch 25 Ro 8
 %MSG
 
which is due to currently only the slice test geometry being in the DB, which is being worked on.

I haven't checked on MC though.

[1] cmsDriver.py GEM --step=RAW2DIGI,L1Reco,RECO --filein=/store/data/Commissioning2020/MinimumBias/RAW/v1/000/335/670/00000/5F3ECF4A-0637-844F-AE67-6BB424F0BF80.root --data --conditions 110X_dataRun3_Prompt_v3 --no_exec --era Run3

@jshlee @hyunyong

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 343 differences found in the comparisons

it looks like run3 and phase2 MC is broken for GEMs using the database for emap.
Do we have a good payload to replace at least the Run3 version for the MC global tag (IIUC it's 111X_mcRun3_2021_realistic_v1 now).
For phase2 I can imagine that we still need a "hardcoded" emap.

**Comment by watson-ij** [comment]
We have a candidate GT for GEM eMap in MC. If I run the ttbar 2021 workflow with the auto GT and then with the following:
111X_mcRun3_2021_realistic_Candidate_2020_03_13_03_56_33
I see that the auto GT doesn't have GEM rechits (as seen in the comparison plots), but they're there for the candidate GT.

**Comment by slava77** [comment]
assign alca

I'm adding alca to keep track of the GT update.
I prefer that we have the GEM emap at least for the Run3 workflows.

@watson-ij 
is it practical to also make a GT payload for emap for phase2?
If not, please add phase2_GEM modifier and apply it in 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Eras/python/Era_Phase2_cff.py
while removing in copyAndExclude the run3_GEM currently inherited from Run3.

**Comment by slava77** [comment]
@christopheralanwest 
please clarify on the timeline for a possible update of the mcRun3 GT to include the GEM emap payload.
We will also need it for 11_0_X.

**Comment by tocheng** [comment]
> @christopheralanwest
> please clarify on the timeline for a possible update of the mcRun3 GT to include the GEM emap payload.
> We will also need it for 11_0_X.

Hello @slava77 , we will submit a PR to update GEM emap during this weekend to master and 11_0

**Comment by slava77** [comment]
> Hello @slava77 , we will submit a PR to update GEM emap during this weekend to master and 11_0

Thank you.
I guess we'll test them jointly, if merging that autoCond PR first is less practical.
Feel free to unassign alca here, if no alca changes will be necessary in this PR.

**Comment by slava77** [comment]
> Reco comparison results: 327 differences found in the comparisons

it looks like all differences are now just in phase-2 workflows.

@watson-ij 
I propose to add ```phase2_GEM``` modifier and apply it in
https://github.com/cms-sw/cmssw/blob/master/Configuration/Eras/python/Era_Phase2_cff.py
while removing in copyAndExclude the run3_GEM currently inherited from Run3.

**Comment by watson-ij** [comment]
Hi Slava, I talked with @jshlee and he proposed we add the phase2_GEM modifier to just turn off the db emap, as in the commit I pushed. This way we don't need to copy paste turning on GEM in phase2 all over the codebase. Once the db is in place everywhere, this modifier and run3_GEM could be unified again.

I checked on MC and it worked in reconstructing GEM rechits in phase2 using the GT from before.

**Comment by perrotta** [comment]
please test with #29210

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
test parameters
workflow = 159,159.1,159.2,159.3
pull_request = #29210

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29194	0fd5cc6
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences
- this PR is a follow up to the problem processing data at T0 https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1669/1/1/1/1/1/1/1/1.html . I checked that after adding ```process.muonGEMDigis.useDBEMap = True``` to the T0 config, the reco job in run 335670 completes OK.

**Comment by slava77** [comment]
@silviodonato 
this PR is to be merged with #29210

**Comment by slava77** [comment]
unassign alca
the feature needed for this PR is in a separate  PR #29210 , no need to have the extra signature here

**Comment by christopheralanwest** [comment]
Why are there single-bin differences in the L1T muon DQM plots for workflow 25202.0, which is a 2016 scenario? For example:
L1TEMU__L1TdeStage2uGMT_ugmtMuonhwPt

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-03-17-2300+0d2e15/35524/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25/L1TEMU__L1TdeStage2uGMT_ugmtMuonhwPt.png

**Comment by silviodonato** [comment]
@christopheralanwest the difference is related to https://github.com/cms-sw/cmssw/issues/29237

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
waiting for #29210

**Comment by silviodonato** [comment]
+1

**Pull request merged**
