### PR TITLE
Era for pp reco on AA for the 2018 detector (10_0_X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
A new era is implemented which is just a copy of the XeXe era, but for the 2018 detector instead of the 2017 one. 
We expect additional customizations to this era will be necessary, since PbPb events are larger than XeXe.   
A new relval workflow is added to test this, number 158.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
+1
- It just duplicates identically whatever was set for pp_on_XeXe_2017, but with the 2018 setup
- Additional customizations and modifications will be added later on, if needed
- The corresponding workflow provided (158) can run

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
please test workflow 158

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
merge

**Pull request merged**
