### PR TITLE
Update 2021 relval matrix for IB test

### PR DESCRIPTION
**Pull request by chayanit**
According to the open issue #32592, we would like to add more workflows in the list of IB test for Run3 2021. The set of workflows are compatible with 2018 set. 

PR validation :

The validation can only be done through cms-bot with test command. All GENSIM is produced.

### CODE REVIEW

**Comment by chayanit** [comment]
FYI. @slava77

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
assign reco

**Comment by srimanob** [comment]
+upgrade

This should be fine for now, however one should consider also remove unnecessary IB, i.e. 2017.

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
> +upgrade
> 
> This should be fine for now, however one should consider also remove unnecessary IB, i.e. 2017.

I propose to include the removal in this PR already to not have an extra work. I will update description. But who decide which workflows should be kept on IB test? Anyone knows?
@silviodonato , @qliphy , @slava77

**Comment by slava77** [comment]
> > +upgrade
> > This should be fine for now, however one should consider also remove unnecessary IB, i.e. 2017.
> 
> I propose to include the removal in this PR already to not have an extra work. I will update description. But who decide which workflows should be kept on IB test? Anyone knows? Shall we assign RECO?
> @silviodonato , @qliphy , @slava77

I think that at least one MC workflow should remain for each year.

**Comment by chayanit** [comment]
> > > +upgrade
> > > This should be fine for now, however one should consider also remove unnecessary IB, i.e. 2017.
> > 
> > 
> > I propose to include the removal in this PR already to not have an extra work. I will update description. But who decide which workflows should be kept on IB test? Anyone knows? Shall we assign RECO?
> > @silviodonato , @qliphy , @slava77
> 
> I think that at least one MC workflow should remain for each year.

OK I remove all 2017 workflows but TTbar on IB test

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to add/remove wfs, if agree, it is OK.

FYI @slava77 @jpata @silviodonato @qliphy 
PdmV proposes to remove all 2017 wfs, except ttbar (+pu). Please comment if something else should be kept.

**Comment by davidlange6** [comment]
So the idea is to end support for 2017 sim and reco in cms?

**Comment by chayanit** [comment]
> So the idea is to end support for 2017 sim and reco in cms?
> […](#)

No, we only reduce the dense in IB test. We still keep 2 workflows for 2017 TTbar and TTbar PU

**Comment by srimanob** [comment]
Hi @davidlange6 
Nope. The question from me if it is still useful to keep 2017 wfs in IB, as we remove don't do 2016 wf also, as dev for Legacy analysis will continue, but that should be OK to use 2018 output. Idea/objection is very welcomed, I think the question is to trigger ppl to think if we want to have a lot number of wf. run in IB for all PRs.

**Comment by davidlange6** [comment]
Which to me seems insufficient for any possible future validation

**Comment by srimanob** [comment]
Hi,
If there is an objection so that we can reverse back to add-only new Run-3 workflow. Could you please help, @chayanit ?
@davidlange6 , could you please share a bit the situation when Run-2 2017 will come back? Just to get an idea on which scenario that may come.

Thanks very much.

**Comment by srimanob** [comment]
-Upgrade

**Comment by davidlange6** [comment]
> On Jan 18, 2021, at 10:11 AM, Phat Srimanobhas <notifications@github.com> wrote:
> 
> 
> Hi,
> If there is an objection so that we can reverse back to add-only new Run-3 workflow. Could you please help, @chayanit ?
> @davidlange6 , could you please share a bit the situation when Run-2 2017 will come back? Just to get an idea on which scenario that may come.

The end of run3 when we may have the same lumi of run2 and run3 data? But I think the better question is are we sure we won’t ever be in a situation where we want Run-2 2017 sim or reco?

**Comment by srimanob** [comment]
> The end of run3 when we may have the same lumi of run2 and run3 data? But I think the better question is are we sure we won’t ever be in a situation where we want Run-2 2017 sim or reco?

Thanks for the clarification. Before, I assumed if we need to come back to 2017, we should do the same as when we developed Legacy of 2016 where specific workflows were called for testing as we don't keep 2016 workflows in IB also, i.e. in https://github.com/cms-sw/cmssw/pull/28082 
Or we can enable them as we want in future as it is not part of concerns now.

But as mentioned before, I am totally fine if we want to keep several workflows in IB if need. Just to make clear on reasons we follow.

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
