### PR TITLE
fixes for the conddb copy functions

### PR DESCRIPTION
**Pull request by ggovi**
These fixes allow the correct behaviour of some of the conddb copy functions:
- copy GlobalTags
- copy Tags with the snapshot selection

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fwyzard** [comment]
I can confirm that after applying https://github.com/cms-sw/cmsdist/pull/2644 and this PR, I can dump a global tag with a command like
```
conddb -v copy --destdb 80X_dataRun2_HLT_v12_280992-284177.db --from 280992 --to 284177 --type gt 80X_dataRun2_HLT_v12
```
and use it successfully in CMSSW (I haven't compared the results though).

Is there and 8.1.x version already ? I think that  #16548 is missing the second commit ?

**Comment by ggovi** [comment]
@fwyzard 
it has been merged in 90X: 
https://github.com/cms-sw/cmssw/pull/16655
I've just sent the PR for 81X:
https://github.com/cms-sw/cmssw/pull/16842

**Comment by davidlange6** [comment]
+1

**Pull request merged**
