### PR TITLE
Run3-hcx248 Add testing code to look at HCAL geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Check the overlap region between barrel and endcap hadron calorimeter 

#### PR validation:

Tested with standard workflows in runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport. It is normal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder to 
simulation: 
 @civanch
 @mdhildreth

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
