### PR TITLE
TEST Reverting PR#43799

### PR DESCRIPTION
**Pull request by artlbv**
Reverts cms-sw/cmssw#43799

This is only to recreate the test results of the PR #43799 which were already removed (based on the current master).
FYI @mmusich @eyigitba @aloeliger @quinnanm

### CODE REVIEW

**Comment by mmusich** [comment]
allow @artlbv test rights

**Comment by artlbv** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> found differences in 10 / 46 workflows

@aloeliger @artlbv looks like reverting this PR "fixes" AXO.

**Comment by aloeliger** [comment]
I posed this in #44397 but I'll post it here too.

@artlbv, @quinnanm, @mmusich I'm catching up after other work yesterday afternoon.

Melissa has seen that removing the CICADA emulator changes AXO's answers.

The CICADA team (myself actually) caught this one earlier this week looking at CICADA firmware/emulator matching. We could run multiple CICADA emulators at the same time and get different answers from a model than we would running only one emulator. I couldn't figure it out and reverted to only doing one at a time because that's how the emulator works anyways and I suspected it was some strange internal CICADA version that could be sorted out at some point later.

What I suspect now now is that this issue is fundamentally symbol collision. Strictly, there isn't anything wrong with CICADA or AXO, the issue is that they share c++ code/symbols that are not specific to themselves in the dynamic linking case used by the emulator technique.

My theory on what is happening is this:

n 14_1 we updated the CICADA model to 1.1.1. One of the layers of CICADA 1.1.1 is weights w2, seen here: https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v1p1p1/cicada.cpp#L36
https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v1p1p1/weights/w2.h#L12. Note that before, in model 2.1, w2 was not in use: https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v2p1/myproject.cpp#L57

AXO, by extension, uses w2 (and b2) as well: https://github.com/cms-hls4ml/AXOL1TL/blob/f21d72bc08ab6e7a86292db9ff0637532a311c2c/AXOL1TL_v3/NN/GTADModel_v3.cpp#L65 https://github.com/cms-hls4ml/AXOL1TL/blob/f21d72bc08ab6e7a86292db9ff0637532a311c2c/AXOL1TL_v3/NN/weights.h#L5 (notably, they are also sized such that AXO could comfortably use CICADA's weights).

These weights are defined globally for both models. As the CMSSW job runs, CICADA gets loaded and created, and these weights loaded into the symbol table here by the dlopen here: https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/17790de8f2f2892dfd8ff20fead8eedd3cf59b49/src/hls4ml/emulator.cc#L21. Later, the AXO model gets created, and the load also attempted. I suspect that behind the scenes, dlopen sees that it would be loading things into the symbol table that are already defined, and quietly drops it in favor of things that are already defined.

In essence, when we upgraded CICADA to 1.1.1, by no real fault of our own, we ended up accidentally switching AXO to CICADA's weights.

I suspect a quick and dirty solution would be to do to CICADA what AXOL1TL has accidentally been doing (and we've all been asking AXO to stop ironically), which is create and destroy itself in one swoop, with no real persistence for model objects beyond creating a result.

In the longer run, the usage of this emulator technique needs to be fixed or changed.

**Comment by mmusich** [comment]
> I'll post it here too.

Please post it in  https://github.com/cms-sw/cmssw/issues/44435 as well

**Comment by aloeliger** [comment]
> > I'll post it here too.
> 
> Please post it in #44435 as well

@mmusich Done.

**Comment by aloeliger** [comment]
I can try and create a PR where CICADA loads itself, creates a result and destroys itself all at once after I get back from the grocery store. Would it be possible to test with that?

**Comment by artlbv** [comment]
Right, so this AXO fix is what I expected.

But what I also was anticipating and seemingly got confirmed is that other hls4ml emulators might also be affected.
See https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-15-2300+e4d5b6/61716/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.log


Processed events: 9 out of 10 (90%)
Found 10 matching events, out of which 1 have different HLT results

      Events    Accepted      Gained        Lost       Other  Trigger
          10           3           -          -1           -  pDoublePuppiTau52_52
Created the following JSON files:
 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/upload/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.json


this is a PHASE2 workflow that @aloeliger added recently for the p2GT emulator. We see the Tau seed gets affected and this is because it is based on an NN in HLS4ML… 

so this is indeed something very hls4ml specific 
FYI @thesps @jmduarte

**Comment by artlbv** [comment]
Closing as this PR served its purpose and the follow up is in the issue.

**Pull request closed without merging**
