### PR TITLE
[CalibFormats] Remove explicit copy-assignment operator 

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Remove explicitly-defined trivial copy-assignment operator ([rule-of-three](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)) violation). 

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
