### PR TITLE
Remove unused pixel template records from ESProducers and update global tags

### LINKED ISSUE #21: Remove intermediate B field SiPixelTemplates
```
SiPixelTemplateDBObject_2T_v3_offline
SiPixelTemplateDBObject_35T_v3_offline
SiPixelTemplateDBObject_3T_v3_offline
SiPixelTemplateDBObject_4T_v3_offline
````
Never used, more info after https://indico.cern.ch/event/1000817/#8-removing-template-records-fo
--> It was agreed to remove this (PR is also needed)

HN request here:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4465.html

### PR DESCRIPTION
**Pull request by OzAmram**
This PR for removes the lookup of template records for intermediate magnetic field values from the SiPixelGenError and SiPixelTemplate ESProducers. These records are not currently used and given the labor intensive process required to produce the calibrations, we do not plan on supporting intermediate magnetic field values in the future. 

This proposed change was discussed at a [recent pixel offline meeting](https://indico.cern.ch/event/1000817/#8-removing-template-records-fo). 

The PR also changes the all the GTs in line with the code change. More info in
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4465/1/1.html

The differences in the GTs can be seen here and is only regarding this 4 tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_design_v1/121X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_realistic_v1/121X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_HeavyIon_v1/121X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_startup_v1/121X_mcRun2_startup_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_l1stage1_v1/121X_mcRun2_asymptotic_l1stage1_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_design_v1/121X_mcRun2_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_preVFP_v2/121X_mcRun2_asymptotic_preVFP_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_v2/121X_mcRun2_asymptotic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2cosmics_asymptotic_deco_v1/121X_mcRun2cosmics_asymptotic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_HeavyIon_v1/121X_mcRun2_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_pA_v1/121X_mcRun2_pA_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_v2/121X_dataRun2_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_HEfail_v1/121X_dataRun2_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_relval_v2/121X_dataRun2_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_PromptLike_HI_v1/121X_dataRun2_PromptLike_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/121X_dataRun3_HLT_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HLT_relval_v2/121X_dataRun2_HLT_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v4/121X_dataRun3_Express_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v3/121X_dataRun3_Prompt_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_v2/121X_dataRun3_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_design_v1/121X_mc2017_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_v1/121X_mc2017_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_forppRef5TeV_v2/120X_mc2017_realistic_forppRef5TeV_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_deco_v1/121X_mc2017cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_peak_v1/121X_mc2017cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_design_v1/121X_upgrade2018_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_v1/121X_upgrade2018_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_RD_v5/121X_upgrade2018_realistic_RD_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HI_v1/121X_upgrade2018_realistic_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HEfail_v1/121X_upgrade2018_realistic_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_deco_v1/121X_upgrade2018cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_peak_v1/121X_upgrade2018cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v2/121X_mcRun3_2021_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v3/121X_mcRun3_2021_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v3/121X_mcRun3_2021cosmics_realistic_deco_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v3/121X_mcRun3_2021_realistic_HI_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v2/121X_mcRun3_2023_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v2/121X_mcRun3_2024_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun4_realistic_v7/121X_mcRun4_realistic_v1

We do not expect any changes in output. 

Fixes cms-AlCaDB/AlCaTools#21

### CODE REVIEW

**Comment by tvami** [comment]
Hi @OzAmram thanks! I've created the GTs and pushed the autoCond file towards your branch in 
https://github.com/OzAmram/cmssw/pull/1

It seems you are not using the latest IB tho, please rebase your branch to something from today or tomorrow. We actually will need https://github.com/cms-sw/cmssw/pull/35277 to be merged first

**Comment by tvami** [comment]
This PR fixes https://github.com/cms-AlCaDB/AlCaTools/issues/21

**Comment by tvami** [comment]
>> Conflicting files: Configuration/AlCa/python/autoCond.py

This is coming from: https://github.com/cms-sw/cmssw/pull/35277
I think you'll need to rebase after 11:00 PM CERN time

**Comment by tvami** [comment]
test parameters:
  - workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
fixes https://github.com/cms-AlCaDB/AlCaTools/issues/21

**Comment by tvami** [comment]
Tests came back as expected: the 6 differences are in the msg logger and are unrelated to this PR

**Comment by tvami** [comment]
@malbouis @francescobrivio since I contributed to this PR, I don't think I should sign it for AlCa

**Comment by francescobrivio** [comment]
+alca

 - @OzAmram the link to the "recent pixel offline meeting" in the description is not really point to a meeting, please fix it
 - In the description usually we put the difference between the old and the new GT, not between the new GT and the Queue that changes with time...@tvami any particular reason to do that? Maybe we should update the links.

**Comment by OzAmram** [comment]
> * @OzAmram the link to the "recent pixel offline meeting" in the description is not really point to a meeting, please fix it

Sorry. Fixed now

**Comment by perrotta** [comment]
+1

**Comment by tvami** [comment]
> * In the description usually we put the difference between the old and the new GT, not between the new GT and the Queue which changes with time...@tvami any particular reason to do that? Maybe we should update the links.

Thanks for catching this, I just copy pasted the wrong column I think. Here is the list that should be in the describtions
```
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_design_v1/121X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_realistic_v1/121X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_HeavyIon_v1/121X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_startup_v1/121X_mcRun2_startup_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_l1stage1_v1/121X_mcRun2_asymptotic_l1stage1_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_design_v1/121X_mcRun2_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_preVFP_v2/121X_mcRun2_asymptotic_preVFP_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_v2/121X_mcRun2_asymptotic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2cosmics_asymptotic_deco_v1/121X_mcRun2cosmics_asymptotic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_HeavyIon_v1/121X_mcRun2_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_pA_v1/121X_mcRun2_pA_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_v2/121X_dataRun2_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_HEfail_v1/121X_dataRun2_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_relval_v2/121X_dataRun2_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_PromptLike_HI_v1/121X_dataRun2_PromptLike_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/121X_dataRun3_HLT_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HLT_relval_v2/121X_dataRun2_HLT_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v4/121X_dataRun3_Express_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v3/121X_dataRun3_Prompt_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_v2/121X_dataRun3_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_design_v1/121X_mc2017_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_v1/121X_mc2017_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_forppRef5TeV_v2/120X_mc2017_realistic_forppRef5TeV_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_deco_v1/121X_mc2017cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_peak_v1/121X_mc2017cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_design_v1/121X_upgrade2018_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_v1/121X_upgrade2018_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_RD_v5/121X_upgrade2018_realistic_RD_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HI_v1/121X_upgrade2018_realistic_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HEfail_v1/121X_upgrade2018_realistic_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_deco_v1/121X_upgrade2018cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_peak_v1/121X_upgrade2018cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v2/121X_mcRun3_2021_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v3/121X_mcRun3_2021_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v3/121X_mcRun3_2021cosmics_realistic_deco_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v3/121X_mcRun3_2021_realistic_HI_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v2/121X_mcRun3_2023_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v2/121X_mcRun3_2024_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun4_realistic_v7/121X_mcRun4_realistic_v1
```

**Comment by OzAmram** [comment]
> > * In the description usually we put the difference between the old and the new GT, not between the new GT and the Queue which changes with time...@tvami any particular reason to do that? Maybe we should update the links.
> 
> Thanks for catching this, I just copy pasted the wrong column I think. Here is the list that should be in the describtions
> 
> ```
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_design_v1/121X_mcRun1_design_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_realistic_v1/121X_mcRun1_realistic_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun1_HeavyIon_v1/121X_mcRun1_HeavyIon_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_startup_v1/121X_mcRun2_startup_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_l1stage1_v1/121X_mcRun2_asymptotic_l1stage1_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_design_v1/121X_mcRun2_design_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_preVFP_v2/121X_mcRun2_asymptotic_preVFP_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_asymptotic_v2/121X_mcRun2_asymptotic_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2cosmics_asymptotic_deco_v1/121X_mcRun2cosmics_asymptotic_deco_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_HeavyIon_v1/121X_mcRun2_HeavyIon_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mcRun2_pA_v1/121X_mcRun2_pA_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_v2/121X_dataRun2_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_HEfail_v1/121X_dataRun2_HEfail_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_relval_v2/121X_dataRun2_relval_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_dataRun2_PromptLike_HI_v1/121X_dataRun2_PromptLike_HI_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/121X_dataRun3_HLT_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HLT_relval_v2/121X_dataRun2_HLT_relval_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v4/121X_dataRun3_Express_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v3/121X_dataRun3_Prompt_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_v2/121X_dataRun3_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_design_v1/121X_mc2017_design_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_v1/121X_mc2017_realistic_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_forppRef5TeV_v2/120X_mc2017_realistic_forppRef5TeV_v2
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_deco_v1/121X_mc2017cosmics_realistic_deco_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017cosmics_realistic_peak_v1/121X_mc2017cosmics_realistic_peak_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_design_v1/121X_upgrade2018_design_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_v1/121X_upgrade2018_realistic_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_RD_v5/121X_upgrade2018_realistic_RD_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HI_v1/121X_upgrade2018_realistic_HI_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018_realistic_HEfail_v1/121X_upgrade2018_realistic_HEfail_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_deco_v1/121X_upgrade2018cosmics_realistic_deco_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_upgrade2018cosmics_realistic_peak_v1/121X_upgrade2018cosmics_realistic_peak_v1
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v2/121X_mcRun3_2021_design_v3
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v3/121X_mcRun3_2021_realistic_v4
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v3/121X_mcRun3_2021cosmics_realistic_deco_v4
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v3/121X_mcRun3_2021_realistic_HI_v4
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v2/121X_mcRun3_2023_realistic_v3
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v2/121X_mcRun3_2024_realistic_v3
> https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun4_realistic_v7/121X_mcRun4_realistic_v1
> ```

Ok I updated the PR description

**Pull request merged**
