### PR TITLE
Validation/Geometry: Fix TTree Option

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Enable output of `TTree` for Material budget studies

#### PR validation:

Unit test already present: `Validation/Geometry/test/genTrackerPlots.sh`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
