### PR TITLE
HLT menu development for 14_0_X (2/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44073

#### PR description:

Development of HLT menus for CMSSW_14_0_X:
   * this is an intermediate update towards the 2024 proton-proton run data-taking.
   
This is the 14_0_X branch, this is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3050](https://its.cern.ch/jira/browse/CMSHLT-3050): [SMP] Remove unused L1 seeds from the W3Pi HLT path
- [CMSHLT-3056](https://its.cern.ch/jira/browse/CMSHLT-3056): [TSG/EXO] Remove `HLT_DiPhoton10smin*` paths from the menu
- [CMSHLT-3063](https://its.cern.ch/jira/browse/CMSHLT-3063): [BPH/EXO] Remove `ParkingDoubleElectronLowMass` stream from the GRun menu
- [CMSHLT-3064](https://its.cern.ch/jira/browse/CMSHLT-3064): [TAU] Remove deprecated L1T seeds from `hltL1sTauVeryBigOR`
- [CMSHLT-3024](https://its.cern.ch/jira/browse/CMSHLT-3024): [BTV/SUS] MSSM Hbb triggers migration from `DeepJet` to `PNet`
- [CMSHLT-3068](https://its.cern.ch/jira/browse/CMSHLT-3068): [Scouting] Removal of the `EG30` Scouting path
- [CMSHLT-3055](https://its.cern.ch/jira/browse/CMSHLT-3055): [PPS/ALCA] Configuration in HLT menu for new O2O/`LHCInfoPer*`
- [CMSHLT-3028](https://its.cern.ch/jira/browse/CMSHLT-3028): [B2G/HIG] Replacement of `MassSD` paths with `SoftDropMass`
- [CMSHLT-3033](https://its.cern.ch/jira/browse/CMSHLT-3033): [SUS] Update of `HLT_DoubleMu3_DCA_PFMET50_PFMHT60` and new auxiliary paths
- [CMSHLT-3029](https://its.cern.ch/jira/browse/CMSHLT-3029): [TAU] Adding DoubleTau+Jet paths including `PNet`
- [CMSHLT-3046](https://its.cern.ch/jira/browse/CMSHLT-3046): [TSG] Cleanup of MC Paths in `GRun`
- [CMSHLT-3037](https://its.cern.ch/jira/browse/CMSHLT-3037): [HIG/TAU/SMP] ParticleNet Versions of ETau, MuTau, and ETau Monitoring HLTs
- [CMSHLT-3031](https://its.cern.ch/jira/browse/CMSHLT-3031): [EXO] Integration of MDS+X triggers
- [CMSHLT-3077](https://its.cern.ch/jira/browse/CMSHLT-3077): [HIG/TAU] Fix IsoMu+PNet control triggers (`'ignore'` filters)
- [CMSHLT-3034](https://its.cern.ch/jira/browse/CMSHLT-3034): [EGM/JME/EXO/HIG] 50 GeV unprescaled single photon path
- [CMSHLT-3030](https://its.cern.ch/jira/browse/CMSHLT-3030): [PPS/SMP] Add PPS-Jet trigger to the 2024 menu
- [CMSHLT-3058](https://its.cern.ch/jira/browse/CMSHLT-3058): [HIG/EXO] VBF parking triggers for 2024
- [CMSHLT-3052](https://its.cern.ch/jira/browse/CMSHLT-3052): [HIG/TAU] VBF `PNet` HLT Integration
- [CMSHLT-3035](https://its.cern.ch/jira/browse/CMSHLT-3036): [L1T] HLT menu updates for `L1Menu_Collisions2024_v1_0_0`

In addition:
   * commit https://github.com/cms-sw/cmssw/pull/44074/commits/eedd2faea86bbcb56584154a2dc753ad978f56bf : update of L1T `FULL`, `GRun`, `PIon`, `PRef`, `Special` menus in TSG GTs to `L1Menu_Collisions2024_v1_0_0_xml`
   * commit https://github.com/cms-sw/cmssw/pull/44074/commits/fe59acf98512479ca1668f25c948a59eb361234c : percolates the [CMSHLT-3027](https://its.cern.ch/jira/browse/CMSHLT-3027) (already integrated in https://github.com/cms-sw/cmssw/pull/44024)  changes to the `@Fake2` menu

#### PR validation:

TSG integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44073 to CMSSW_14_0_X for HLT menu development.

----
## Important Note

**N.B.** Note to @cms-sw/orp-l2 this PR **MUST** be merged together with https://github.com/cms-sw/cmssw/pull/44080, that PR updates the `L1TUtmTriggerMenu` record to use `L1Menu_Collisions2024_v1_0_0_xml` in the `Configuration/AlCa` package: (see more details at this [cmsTalk post](https://cms-talk.web.cern.ch/t/update-of-the-2024-l1-menu-tag-l1menu-collisions2024-v1-1-0/35509)). Updates:
   * 2024 simulation `autoCond` keys
   * symbolic `run3_data_relval` and `run3_hlt_relval` keys

### CODE REVIEW

**Comment by mmusich** [comment]
testing of this PR requires at least https://github.com/cms-sw/cmssw/pull/44045, so won't test for now.

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/44080

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
urgent

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
