### PR TITLE
Fix to bring back DT DQM in commissioning runs

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by jfernan2** [comment]
Backport of #19851

**Comment by dmitrijus** [comment]
Please fix the conflict.

**Comment by jfernan2** [comment]
Done. Sorry for the delay, I'm on holidays and the git cellular version did not allow me to fix it, I had to do it from a laptop...
Thanks

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
