### PR TITLE
conddb command line tools: support of conversion timestamp->run  for copy function

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

We are adding the conversion timestamp->run number as an option for the Tag copy function.
The support of this option is limited to the copy of timestamp-based source tag, and to destination run-based tag when already existing.  In case of multiple timestamp collapsing in the same run, the first IOV is considered. In case of timestamp with no match to existing run, the IOV is skipped.

#### PR validation:

Stand-alone local tests

### CODE REVIEW

**Comment by ggovi** [comment]
Please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
