### PR TITLE
Removed use of global histograms in DTVDriftCalibration

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Moved the histograms to a class that is shared between the two
uses of the histograms.

This was found by the static analyzer.
#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
+1
@christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng please have a look

**Comment by silviodonato** [comment]
merge

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
