### PR TITLE
fix segmentation fault in SiStripBadComponentInfo

### PR DESCRIPTION
**Pull request by mmusich**
Title says is it all: attempt to fix issue #22695.
Access to the `TrackerTopology` from DB is moved from `dqmEndJob` to `endRun` where framework should guarantee `edm::EventSetup` components are still accessible. Bin contents of the output monitor element are cached in a `std::map`.
This reverts also https://github.com/cms-sw/cmssw/pull/22690.
Tested locally with wf. `runTheMatrix.py -l 4.6 -t 4`

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by boudoul** [comment]
I say thank you to @mmusich in the coorresponding issue  instead of here, but I can repeat it here too :-) 

On the other hand let me add @jandrea and @suchandradutta  to make sure they are following (@fioriNTU is already a watcher)

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Not an issue, but a note: under multi run harvesting / PCL, endRun will be run multiple times.

I don't know if this module runs in multi run harvesting.
But either way, the code looks okay and should not crash even if called multiple times.

**Comment by mmusich** [comment]
@dmitrijus the conditions that are monitored are updated each run. It doesn't make sense to run this in multi-run mode.

**Comment by dmitrijus** [comment]
@mmusich Thanks!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
