### PR TITLE
HLT menu development for `12_4_X` (4/N) + migration to `12_4_0` + frozen menu `V1.2` for 2022

### PR DESCRIPTION
**Pull request by missirol**
backport of #38482

#### PR description:

 - Development of HLT menus for `CMSSW_12_4_X`.
 - Migration of HLT configs to release template `CMSSW_12_4_0`.
 - Introduction of `V1.2` frozen (GRun) menu to be used for MC production in `12_4_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2267](https://its.cern.ch/jira/browse/CMSHLT-2267): [EXO] Update of displaced-ditau trigger
  - [CMSHLT-2287](https://its.cern.ch/jira/browse/CMSHLT-2287): [TSG] Update of `HLTDebug*` EventContents with `DQMGPUvsCPU` output collections
  - [CMSHLT-2304](https://its.cern.ch/jira/browse/CMSHLT-2304): [MUO,BPH] Change L1T seed of `HLT_Mu15`, remove `HLT_Mu7p5_TkX`
  - [CMSHLT-2315](https://its.cern.ch/jira/browse/CMSHLT-2315): [ECAL] Disable energy-recovery in ECAL RecHit producers
  - [CMSHLT-2326](https://its.cern.ch/jira/browse/CMSHLT-2326): [EXO] Update of 2 triggers with new displaced-global-muon reconstruction
  - [CMSHLT-2336](https://its.cern.ch/jira/browse/CMSHLT-2336): [TSG] Disable unclaimed triggers (90 triggers in total)
  - [CMSHLT-2343](https://its.cern.ch/jira/browse/CMSHLT-2343): [TSG] Add `DQMGPUvsCPU` stream to `HIon` and `PRef` menus
  - [CMSHLT-2344](https://its.cern.ch/jira/browse/CMSHLT-2344): [BPH] Disabled `HLT_DoubleMu2_Jpsi_DoubleTkMu0_Phi_v`
  - [CMSHLT-2346](https://its.cern.ch/jira/browse/CMSHLT-2346): [BPH] Removed `*ToCSCS*` single-muon 2018-Parking triggers and dataset
  - [CMSHLT-2348](https://its.cern.ch/jira/browse/CMSHLT-2348): [BPH] Disabled single-muon 2018-Parking triggers _(integrated partially; Paths not yet removed nor replaced)_
  - [CMSHLT-2353](https://its.cern.ch/jira/browse/CMSHLT-2353): [L1T] Update of MET L1T seeds

In addition, HLT configs will now use `cms.ConditionalTask`s instead of `cms.Task`s thanks a recent update of `ConfDB` ([`V03-04-00`](https://github.com/cms-sw/hlt-confdb/releases/tag/V03-04-00)). Further details on the reasons behind this change can be found in https://github.com/cms-sw/cmssw/issues/36938.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#38482

Development of HLT menus for 2022 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/pull/38482#issuecomment-1165303040.

**Comment by missirol** [comment]
+hlt

 - the RelVal-INPUT error is most likely unrelated to this PR (we can rerun the tests, if others prefer)
 - outputs of PR tests are in line with changes to the HLT menus, even though some differences are not fully understood by me (see https://github.com/cms-sw/cmssw/pull/38482#issuecomment-1165303040)
 - in particular, it is not clear what causes the differences in [`GlobalRecHitsV/HCals`](https://tinyurl.com/28wg9ut2), and I don't see how HLT changes can induce those diffs (I see nothing to be changed on the HLT side, and I don't really know how those plots are filled)

**Comment by srimanob** [comment]
+Upgrade

Backport.

**Comment by srimanob** [comment]
@cmsbuild please test

Hope we remove relval input error from the test.

**Comment by perrotta** [comment]
urgent

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
