### PR TITLE
Reduce LogWarning for non-existing tau discriminators during pat::Tau candidate creation

### PR DESCRIPTION
**Pull request by roger-wolf**
The change is purely technical and minimal as can be seen from the commits. It follows an issue raised by Slava (*).

Cheers,
Roger

(*)
 https://github.com/cms-sw/cmssw/pull/21022/files#diff-c7c5c83df6323f1a53a05655cd079d3fR319

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Output of the PhysicsTools/PatAlgos unit tests improves from 
```
Begin processing the 1st record. Run 1, Event 2, LumiSection 1 at 20-Nov-2017 12:34:49.000 CET
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:34:59 CET  Run: 1 Event: 2
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
Begin processing the 2nd record. Run 1, Event 1, LumiSection 1 at 20-Nov-2017 12:35:01.206 CET
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:35:01 CET  Run: 1 Event: 1
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:35:01 CET  Run: 1 Event: 1
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:35:01 CET  Run: 1 Event: 1
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:35:01 CET  Run: 1 Event: 1
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
%MSG-w DataSource:  PATTauProducer:patTaus 20-Nov-2017 12:35:01 CET  Run: 1 Event: 1
Tau discriminator 'byVVLooseIsolationMVArun2v1DBoldDMwLT' has not been found in the event. It will not be embedded into the pat::Tau object.
%MSG
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 at 20-Nov-2017 12:35:01.259 CET
...
```

to
```
Begin processing the 1st record. Run 1, Event 2, LumiSection 1 at 17-Nov-2017 13:52:05.610 CET
%MSG-w DataSource:  PATTauProducer:patTaus 17-Nov-2017 13:52:07 CET  Run: 1 Event: 2
The following tau discriminators have not been found in the event:
byVVLooseIsolationMVArun2v1DBoldDMwLT
They will not be embedded into the pat::Tau object.
Note: this message will be printed only at first occurence.
%MSG
Begin processing the 2nd record. Run 1, Event 1, LumiSection 1 at 17-Nov-2017 13:52:16.029 CET
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 at 17-Nov-2017 13:52:16.064 CET
...
```

**Comment by perrotta** [comment]
+1
- The cleaning of the logs as in https://github.com/cms-sw/cmssw/pull/21348#issuecomment-345747858 corresponds to what asked for in #21346
- Differences in jenkis tests point to the log error harvester, not relates to this PR

**Comment by davidlange6** [comment]
merge

**Pull request merged**
