### PR TITLE
cleanup unnecessary FWCore/Framework dependencies in DataFormats

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Is it worth trying Jenkins again?

**Comment by cvuosalo** [comment]
+1

For #15210 971d48907c830369c3ae74df68db01f0f066dd2e

Correcting BuildFile.xml dependencies in DataFormats directories. There should be no change in compiled output.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-07-14-2300 show no significant differences, as expected.

**Comment by ianna** [comment]
+1

**Pull request merged**
