### PR TITLE
Adding (a lite version of) General Tracks to ALCARECO stream for Muon Alignment

### PR DESCRIPTION
**Pull request by lpernie**
Hello @mmusich ,
this is the PR concerning the addition of general tracks to the ALCARECO stream for muon alignment we proposed some times ago.
I took the changes from the latest PR:
https://github.com/cms-sw/cmssw/pull/9957
If I understand correctly everything was fine at the time, and a "lite" version of general tracks was added to the stream correctly, but just for matter of deadline the changes were never pushed into cmssw.

### CODE REVIEW

**Comment by mmusich** [comment]
@lpernie this branch has conflicts to be resolved. 
We need a rebase.
You should be able to do it via:
```
git fetch official-cmssw # get the latest updates from the official repository
git checkout newALCARECOstream  # checkout your branch (if you have not done yet)
git rebase official-cmssw/CMSSW_8_1_X # rebase your changes on top of the official branch
```

**Comment by lpernie** [comment]
@mmusich done!

**Comment by mmusich** [comment]
@lpernie,  OK, now it can be merged.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@lpernie,
trying to rebase your branch I see you still have conflicts in:

`Configuration/PyReleaseValidation/python/relval_steps.py`

also can you please change the title of the PR to something more explanatory?

**Comment by lpernie** [comment]
Hi @mmusich ,
I changed the name and I rebased the release.
(I did: 1) git fetch official-cmssw # get the latest updates from the official repository
2) git checkout newALCARECOstream  # checkout your branch (if you have not done yet)
3) git rebase official-cmssw/CMSSW_8_1_X # rebase your changes on top of the official branch )
Doing that I had to solve the conflicts in:
Configuration/PyReleaseValidation/python/relval_steps.py
Should I do something else to propagate this changes to this PR?

**Comment by mmusich** [comment]
Hi @lpernie, it seems there are further conflicts, as you can see the cms-bot complains with: "This branch has conflicts that must be resolved".
Can you try to rebase again?
Thanks,
Marco

**Comment by ghellwig** [comment]
@lpernie naive question: did you do `git rebase --continue` after you resolved the conflicts?

**Comment by lpernie** [comment]
Yes I did -- continue. Now I did it again and I noticed another conflict to be fixed that did not appear the first time.
Now I got:
git rebase official-cmssw/CMSSW_8_1_X
Current branch newALCARECOstream is up to date.
but I still see "This branch has conflicts that must be resolved". Should I also push this changes?

**Comment by ghellwig** [comment]
yes, you need to push it (with the `--force` flag)

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@lpernie apparently this branch is doomed to have conflicts... :(
can you rebase again?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
the error reported in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15179/14071/runTheMatrix-results/runall-report-step123-.log is not really informative...

**Comment by lpernie** [comment]
Let me know if I can i help with something.

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
Hi @degano, @smuzaffar, test outputs are not really useful for this PR: 

`tests passed,  failed`.

in:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15179/14103/runTheMatrix-results/runall-report-step123-.log.

Anything that can be done to move on? 
Thanks,
M.

**Comment by davidlange6** [comment]
does runTheMatrix work in your local tests?

**Comment by smuzaffar** [comment]
due to missing 2017 workflows , we have errors like
```
++ timeout 10800 runTheMatrix.py '--das-options=--cache das-cache.file --limit 0' --job-reports -j 24 -s -l 1306.0,101.0,1003.0,50202.0,9.0,25202.0
Deprecated, please use -l limited
processing relval_standard
ERROR importing file  relval_standard '2017'
processing relval_highstats
ERROR importing file  relval_highstats '2017'
processing relval_pileup
ERROR importing file  relval_pileup '2017'
```

and runTheMatrix did not run any thing

**Comment by mmusich** [comment]
@smuzaffar thanks, sorry I overlooked the changes in `Configuration/PyReleaseValidation/python/relval_steps.py` are really a no-go, I assumed it was somehow related to the other extensive failures reported last week, due to DAS, etc. etc.

**Comment by davidlange6** [comment]
indeed- it seems this PR introduces  lots of regression in relval_steps.py?

**Comment by mmusich** [comment]
@davidlange6 yes, it should have developed the regressions at some point during the multiple re-bases. @lpernie maybe it's more convenient to start from a fresh branch.

**Comment by lpernie** [comment]
Hello,
Sure, but how can I do that practically?
Before I simply took the latest 8_1_X release (CMSSW_8_1_0_pre8) and I changed the 14 files I needed to change.
Should I do this again and make a new PR?
I saw that the main problems come from "relval_steps.py", should I do not change this file?

**Comment by mmusich** [comment]
Hi @lpernie, you should change it, but limit the number of changes to the ones of these two committs:
   * https://github.com/cms-sw/cmssw/pull/9957/commits/d214718380d2db0822803ad8958cd89b50a8c862
   * https://github.com/cms-sw/cmssw/pull/9957/commits/0b2dec16091ce0e29c49f849acfcb76d6cdbe84f

**Comment by lpernie** [comment]
Ok, then I will do a new PR soon.

**Comment by mmusich** [comment]
@lpernie thanks!

**Comment by lpernie** [comment]
One question @mmusich:
The two d214718 and 0b2dec1 are going in different directions.
d214718 is proposing some changes and 0b2dec1 is proposing opposite changes.
Which one I should follow? The current relval_steps.py already have the changed proposed in 0b2dec1.

**Comment by mmusich** [comment]
@lpernie to me they don't seem to go in different directions, but rather complement each other. I think the desired effect is to have them merged sequentially.

**Comment by mmusich** [comment]
-1 
supersded by https://github.com/cms-sw/cmssw/pull/15221

**Pull request closed without merging**
