### PR TITLE
bsunanda:Run2-alca19 Fix for the crash in the relval for AlCa step with IsoTrack

### PR DESCRIPTION
**Pull request by bsunanda**
Modify the AlCaRecoProducer fo IsoTrack as well as HBHEMuon and also the fliters/scripts to avoid any crash in RelVal steps. The changes need to be backported to the CMSSW version used in Tier0.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Please note the IB against which this is tested has these errors. So the tests should be done against an IB which does not have this error. The crash is not due to the committed codes
________________________________

**Comment by bsunanda** [comment]
I tested the PR against today's IB and the tests pass. Please initiate the tests again
________________________________
From: Sunanda Banerjee
Sent: 14 July 2015 01:01
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-alca19 Fix for the crash in the relval for AlCa step with IsoTrack (#10178)

Please note the IB against which this is tested has these errors. So the tests should be done against an IB which does not have this error. The crash is not due to the committed codes
________________________________

**Comment by mmusich** [comment]
please test

**Comment by bsunanda** [comment]
Can this be tested and integrated soon? Regards                  Sunanda
________________________________

**Comment by diguida** [comment]
testing locally in order to see the event content...

**Comment by diguida** [comment]
@bsunanda from a check of the event content I see that now you have `generalTracks`, but no more the `IsoTrack` collection. From a quick check of the code, now you filter out particles, while before you were also putting them in a dedicated collection. Is this correct?

**Comment by bsunanda** [comment]
Yes - we keep all tracks - more likely it is a filter with 1 extra collection with results from linking isolated tracks with trigger information.
________________________________

**Comment by diguida** [comment]
@bsunanda Bad, I still get 0 events by running wf `25.0`...

**Comment by diguida** [comment]
Ok, but at least it runs without crashing... At this point, I think it is safe to approve here and check the IB relvals and more local tests even on data.

**Comment by diguida** [comment]
+1
Fixes observed crashes in `HcalCalIsoTrk`AlCaReco are removed. Still, the filter is not selecting any events.

**Comment by bsunanda** [comment]
David - could you integrate this PR for pre6?
________________________________

**Comment by davidlange6** [comment]
+1

**Pull request merged**
