### PR TITLE
Shift from Boost Python to Pybind11

### PR DESCRIPTION
**Pull request by Purva-Chaudhari**
#### PR description:

Shift from Boost Python to Pybind11 in CondCore Utilities

#### PR validation:

Passed on scram -b runtests (CondCore)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@davidlange6 @vgvassilev

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
isn't this a (partial) duplicate of #34672 ?

**Comment by davidlange6** [comment]
yes, working with @ggovi on this

**Comment by mmusich** [comment]
#34672 has been tested in a production environment aside from unit test, would be good that whatever final solution is used is tested in the same fashion (maybe you've already planned that)

**Comment by davidlange6** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by qliphy** [comment]
@cms-sw/db-l2 Any comment?

**Comment by ggovi** [comment]
I'm expecting instructions from @davidlange6 on how to deal with this one. https://github.com/cms-sw/cmssw/pull/34672 has been already validated in the web application.

**Comment by qliphy** [comment]
> I'm expecting instructions from @davidlange6 on how to deal with this one. #34672 has been already validated in the web application.

kindly ping @ggovi @davidlange6

**Comment by davidlange6** [comment]
sorry for the delay - I think its mostly the same in the end - this one diagonalizes the lexical_cast migration (partly done in @ggovi s pr) and follows the usual pybind11 conventions for declaring modules (functional interface rather than repeated m.def... ) but minor details.

**Comment by qliphy** [comment]
> sorry for the delay - I think its mostly the same in the end - this one diagonalizes the lexical_cast migration (partly done in @ggovi s pr) and follows the usual pybind11 conventions for declaring modules (functional interface rather than repeated m.def... ) but minor details.

Thanks @davidlange6 
As @ggovi mentioned:  #34672 "has been already validated in the web application.", and #34672 also touches additional files than in this PR.  Should we go ahead with #34672 and close this one?

**Comment by smuzaffar** [comment]
@qliphy , I would suggest to go ahead with #34672 which db has already tested in their web appilcation and close this

**Pull request closed without merging**
