### PR TITLE
use `cms_omds_adg` in lieu of `cms_omds_tunnel` for SiStrip O2O unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, attempt to solve https://github.com/cms-sw/cmssw/issues/37888

#### PR validation:

None, as I don't have the appropriate credentials to test. 
The bot will make the actual test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but will need to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
> I have tested it locally but the unit test still fails

how?

**Comment by smuzaffar** [comment]
@mmusich , I get messages like 
```
WARNING: if you set ttcrxBrcstStrTwoFineDelay, then this will overwrite the ttcrxL1AcceptFineDelay if the ttcrxClock40DeskwedTwo is set to DISABLE.
we add another FED to the vector, we now have 95 feds. the fedID for the last fed is 324
in string stream! 231003a7
******************** mode string node value = ZERO_SUPPRESSION
******************** super mode string node value = ZERO_LITE
WARNING: if you set ttcrxBrcstStrTwoFineDelay, then this will overwrite the ttcrxL1AcceptFineDelay if the ttcrxClock40DeskwedTwo is set to DISABLE.
fed pointer for freddy! = 0x7fc69681c000
Fed9UDeviceFactory::Address of Pointer: 0x7fc6db6a7660
SiStripCondObjBuilderFromDb::buildStripRelatedObjects] Unable to build Pedestals object! No DetIds found!
Entering [SiStripCondObjBuilderFromDb::buildFEDRelatedObjects]
Entering [SiStripCondObjBuilderFromDb::buildFECRelatedObjects]
%MSG-e SiStripConfigDb:  SiStripO2OBadStrip:siStripO2O  30-May-2022 09:28:21 CEST Run: 1 Event: 1
 Caught FecExceptionHandler exception in method getDeviceDescriptions with message: 
FecExceptionHandler: 
        What: PL/SQL exception raised for partition name : TI_27-JAN-2010_2 and version 900.0: ORA-16000: database or pluggable database open for read-only access
ORA-06512: at "CMS_TRK_TKCC.PKGLOGDEBUG", line 59
ORA-06512: at "CMS_TRK_TKCC.PKGFECXML", line 177
ORA-06512: at line 1

        File: /data/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/el8_amd64_gcc10/external/tkonlinesw/4.2.0-1_gcc7-700cdb630dfd2efe2b2ef741f0bb4f4c/trackerDAQ-4.2-tkonline/FecSoftwareV3_0//generic/src/common/XMLFec.cc line: 278
        Method: void XMLFec::parseDatabaseResponse(std::string, unsigned int, unsigned int, unsigned int, unsigned int)
        When: Mon May 30 09:28:21 2022
        Error code: 1004
        Error from the database layer accesses
%MSG
%MSG-w SiStripConfigDb:  SiStripO2OBadStrip:siStripO2O  30-May-2022 09:28:21 CEST Run: 1 Event: 1
[SiStripConfigDb::getDeviceDescriptions] Found 0 device descriptions in 0 database partition(s)
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
```

lets wait for PR tests results

**Comment by smuzaffar** [comment]
@mmusich , full unit test log is now available https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a68343/25064/unitTests/src/CondTools/SiStrip/test/SiStripDAQ_O2O_test/testing.log

**Comment by smuzaffar** [comment]
@mmusich , should we disable the unit test too?

**Comment by smuzaffar** [comment]
I tried those (e.g updating tnsnames.ora )  but did not work. @cms-sw/db-l2 should come up with setting up tunnel

**Comment by ggovi** [comment]
@smuzaffar I guess you have updated a private copy of the tnsnames.ora? Or the one in /etc?

**Comment by tvami** [comment]
> > I tried those (e.g updating tnsnames.ora ) but did not work. @cms-sw/db-l2 should come up with setting up tunnel
> 
> ok my bad, with updated `tnsnames.ora` ( as suggested by Alessandro Giassi) and `~/.netrc` test worked.

@smuzaffar can you please comment that on https://github.com/cms-sw/cmssw/issues/37888 as well? I understand that this means the issue can be closed, right?

**Comment by mmusich** [comment]
> I understand that this means the issue can be closed, right?

Let's wait the first IB that passes...

**Comment by smuzaffar** [comment]
@ggovi , the `cms_omds_tunnel` entry is not removed from `tnsnames.ora` but looks like it is not functional any more

**Comment by ggovi** [comment]
@smuzaffar ok, this is good then. It means there should be no security-related reason forbidding this approach

**Comment by ggovi** [comment]
My understanding of Kate (DBAs) feedback is that the official tnsnames.ora cannot contain this tunnel entry, as it involves a specific node. I'm not sure how this was possible before the changeover. 
In any case, it looks like we cannot rely on the official tnsnames.ora for these tests.

**Comment by smuzaffar** [comment]
@hqucms , yes we can but can not deploy it under `/etc` ( for many build nodes we do not have admin rights) but we can mount it under docker/singularity e.g. we can moint `~/tnsnames.ora:/etc/tnsnames.ora` when we start the singularity container

**Comment by tvami** [comment]
-db
 * the PR was closed

**Comment by mmusich** [comment]
not sure what's the point of rejecting a closed PR :D

**Comment by mmusich** [comment]
mmmh, you can just look at the open ones: https://github.com/cms-sw/cmssw/labels/db-pending. Actually to look at the closed ones you explicitly need to click on the button..but fine, if you deem that worth of your time be my guest :)

**Pull request closed without merging**
