### PR TITLE
NanoAOD developments: 190520 version, part 2 for UL

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

This PR contains the second part of NANOAOD developments for UL and full Run2 analyses.
No changes are expected outside of NANOAOD content.

Main items:
- updated muon preselection and ID content
- 2018 EGM scales and smearings
- Higgs STXS stage 1.1
- minor additions to generator and trigger content

Depends on #26724 and cms-sw/cmsdist#4995

### CODE REVIEW

**Comment by peruzzim** [comment]
Note: the diff also includes files that would not be modified by merging this PR, because of the peculiar merge history between these developments, #26486, and the master branch.

The actual list of modified files is:
```
M       PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
A       PhysicsTools/NanoAOD/plugins/GenJetTauTaggerProducer.cc
M       PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
M       PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
M       PhysicsTools/NanoAOD/python/common_cff.py
M       PhysicsTools/NanoAOD/python/electrons_cff.py
M       PhysicsTools/NanoAOD/python/genparticles_cff.py
M       PhysicsTools/NanoAOD/python/globals_cff.py
M       PhysicsTools/NanoAOD/python/isotracks_cff.py
M       PhysicsTools/NanoAOD/python/jets_cff.py
M       PhysicsTools/NanoAOD/python/muons_cff.py
M       PhysicsTools/NanoAOD/python/nanoDQM_cff.py
M       PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
M       PhysicsTools/NanoAOD/python/nano_cff.py
M       PhysicsTools/NanoAOD/python/particlelevel_cff.py
M       PhysicsTools/NanoAOD/python/photons_cff.py
M       PhysicsTools/NanoAOD/python/triggerObjects_cff.py
```

**Comment by perrotta** [comment]
@peruzzim I notice in the git diff the additions which were already merged with #26679 (since 10_6_0_pre4 already). Could you please rebase to the last 11_0 IB, so that you can get rid of the un-necessary files in the difference? I'd expect that this will also remove the request of a reco signature here.

**Comment by peruzzim** [comment]
@perrotta we would really like to avoid rebasing, as this already serves as development base for few people working on future additions to NANOAOD... it is just a matter of diff visualization after all, it can be verified that those files are not touched at all by this PR

**Comment by perrotta** [comment]
+1
- The difference with respect to the latest IB in the master shows that only files in PhysicsTools/NanoAOD are modified, as correctly reported in https://github.com/cms-sw/cmssw/pull/26844#issuecomment-494000227 and https://github.com/cms-sw/cmssw/pull/26844#issuecomment-494013137
- Since none of those files belongs to reco, this signature is just a pass-through

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26724, cms-data/PhysicsTools-NanoAOD#6

(not sure whether the test will run without a cmsdist PR)

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26724, cms-sw/cmsdist#4995

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26724, cms-sw/cmsdist#4995

**Comment by peruzzim** [comment]
+xpog

Changes only in NANOAOD, as expected. All test workflows run successfully.

**Comment by perrotta** [comment]
+1
- Confirming https://github.com/cms-sw/cmssw/pull/26844#issuecomment-494057579: also the latest commits do not touch reco code

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
