### PR TITLE
Remove obsolete cms scripts 74X (Backport of #12783, except APEEstimation package)

### PR DESCRIPTION
**Pull request by ghellwig**
This PR removes the usage of the following scripts in the alignment workflows:

cmsLs
cmsMkdir
cmsRm
cmsRmdir
cmsPfn
cmsStage
cmsStageIn
cmsStageOut

These will stop working in January 2016 [1] and have been replaced by supported alternatives.

Added also a commit to copy over a monitoring file for the MillePedeAlgorithm.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/cmpAnnounce/1031.html

Backport of #12783, except APEEstimation package

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ghellwig** [comment]
I should maybe mention, that it is very important that we have a release with this PR soon because alignment workf-lows depend on it.

**Comment by mmusich** [comment]
@ghellwig can you clarify why the stress is on 74X? 
You will get both data and MC reprocessed in 76X early next year. Just StreamExpress is bound to remain in 74X, but I am sure you are past this point

**Comment by ghellwig** [comment]
My understanding was that in beginning of 2016 we still need 74X, but if all data (incl. available MC) is usable in 76X you are absolutely right, that this stress is not needed.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
