### PR TITLE
Add missing include in FWCore/Utilities/src/path_configuration.cc

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

This should fix the issue reported in https://github.com/cms-sw/cmssw/pull/40425#issuecomment-1374635621 for gcc12
(Thank you @missirol for having checked and suggested)

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test
lets start the default arch tests too. For gcc12 tests, it shouldbe enough it FWCore/Utilities compiles

**Comment by smuzaffar** [comment]
> The remaining build errors with gcc12 are not related any more with FWCore/Utilities/src/path_configuration.cc , and as such we should be happy: correct @smuzaffar ?

yes that is correct. `FWCore/Utilities` compiled so it should be good to fix the GCC12 build/link errors.

**Comment by makortel** [comment]
Comparison differences are in 11634.7 (#39803 )

**Comment by perrotta** [comment]
+1

**Pull request merged**
