### PR TITLE
L1T BlockHeader changes for L1T ZS DQM

### PR DESCRIPTION
**Pull request by thomreis**
Added the ZS validation flag to the L1T BlockHeader to be used with the online DQM zero suppression module.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
This segfault does not seem to have anything to do with the L1 code. Can we run the tests again please?

**Comment by rekovic** [comment]
failing jobs 135.4 does not seem to point to this PR.

will try test again.

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
Hi @muzaffar, @davidlange6, @smuzaffar,
what is keeping this and #17958 from being merged?

**Comment by thomreis** [comment]
If there is a problem with this PR please let me know so that I can fix it. If not please merge it so that it can be in the next release deployed for the DQM at p5.

**Comment by thomreis** [comment]
@muzaffar, @davidlange6, @smuzaffar can someone please tell me what keeps this from being merged? It is fully signed for a month now.

**Comment by rekovic** [comment]
@davidlange6 
Please post your concerns.  We should fix this for data taking.  Thanks.

**Comment by rekovic** [comment]
Hi @davidlange6.
We should get this PR and #17958 ready for data taking.  
Can we please get your explicit comments, so that we can address them efficiently.

**Comment by davidlange6** [comment]
i finally connected with @rekovic on this PR _ we agreed that in a followup PR that Block would go into a DataFormats package so that the usual CMS structure of data formats, producers, analyzers could be adopted

**Comment by davidlange6** [comment]
+1

**Pull request merged**
