### PR TITLE
Re-inforce time of arrival threshold in aged scenarios

### PR DESCRIPTION
**Pull request by pfs**
#### PR description:

In the HGCAL DPG meeting of 29th March it was reported an incosistent behavior for the efficiency of time of arrival (TOA) when aging is applied [1].
This has been tracked down to a missing condition in the HGCalFEElectronics class requiring the charge deposited to be above the required threshold which this PR patches.

#### PR validation:

The PR has been validated locally using `runTheMatrix.py -w upgrade -l 23234.103` 
The charge spectra of the hits with TOA measurement is shown below. The left plot corresponds to the simhit level charge (before ageing) and the right plot corresponds to the reconstructed charge including noise and ageing. The nominal threshold for TOA measurement is 12 fC. Without the fix all simulated hits with 12 fC will generate TOA, however after ageing they'll correspond to <12 fC which is an unwanted behavior. After the fix one can observe that the sharp threshold is now at 12 fC at reconstruction level and depicts a slow rise at sim hit level.

qspectra_toa

The TOA efficiency curves are below

toaeff

The patch generates a different number of calls to the random number generator and thus a smearing in the digis. This is illustrated below for CE-H, CE-H Si and SiPM-on-tile sections. However the result is expected to be unbiased with respect to previous releases

| Section      | Migration of DIGIs expected after PR |
| ----------- | ----------- |
| CE-E | adcperdetid_0 |
| CE-H Si | adcperdetid_1 |
| CE-H SiPM-on-tile | adcperdetid_2 |

#### References

[1]  https://indico.cern.ch/event/1270358/#2-update-on-toa-studies

### CODE REVIEW

**Comment by pfs** [comment]
@stahlleiton

**Comment by pfs** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
