### PR TITLE
2nd attempt to fix PixelSLinkDataInputSource for phase1

### PR DESCRIPTION
**Pull request by dkotlins**
Try again to fix PixelSLinkDatInoutSources so they work with the phase1 data (dump files).

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
hello @davidlange6 @smuzaffar 
Is it expected that the alca signature assigned to IORawData/SiPixelInputSources ?
The content of its packages as it stands in master appears to me outside the range of responsibility/competence of our team...

**Comment by smuzaffar** [comment]
@franzoni and  @davidlange6 , IORawData/SiPixelInputSources package just hosts one class for an edm plugin. We should merge it with some other package. Any suggestions?

**Comment by dkotlins** [comment]
This package is used only to transform pixel calibration data from a private data format (called dmp) 
to the official raw data format used by CMSSW. It is only used when preparing pixel gain calibration
constants, that is by a pixel expert in a special processing step.

We could indeed move it somewhere,  e.g. to CalibTracker/SiPixelTools.
D.

**Comment by davidlange6** [comment]
CalibTracker/SiPixelTools sounds appropriate. Thanks!

**Comment by ghellwig** [comment]
@dkotlins your proposed package was fine for @davidlange6, i.e. you could update this PR to acknowlede this...

**Comment by franzoni** [comment]
hello is this PR still of relevance ? 

Moving `PixelSLinkDataInputSource `the  to `CalibTracker/SiPixelTools` would still imply AlCa signature (and not address https://github.com/cms-sw/cmssw/pull/18656#issuecomment-301544986 ). Imho binary parsing of hex data from FedRawData rather belongs to a packages holding the unpacking code (e.g. `EventFilter/SiPixelRawToDigi` )

**Comment by franzoni** [comment]
hello is this PR still of relevance ?

**Comment by arunhep** [comment]
Can this PR be closed if not of any relevance?

**Comment by arunhep** [comment]
-1
no response. rejecting to remove from the AlCa list.

**Pull request closed without merging**
