### PR TITLE
Use esConsumes in PileUpSubtractor

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This was missed in the VirtualJetProducer migration to esConsumes.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35392	196cb4a
- code changes are technical
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
