### PR TITLE
Update clang headers location and changed interfaces

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Adjusting to llvm8 interfaces

#### PR validation:

It compiles

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/5114

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#5114

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5114

**Comment by smuzaffar** [comment]
we are merging it for DEVEL IBs

**Pull request merged**
