### PR TITLE
Enable feature to recycle GEN for FastSim

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
As title said, this PR enables the feature to recycle GEN for FastSim workflow.

#### PR validation:
Try to run `runTheMatrix.py --what upgrade -l 13234.0 -i all -t 4 --wm init` locally.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
FYI @sunilUIET

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Hi @cms-sw/pdmv-l2 
Could you please submit a FastSim relvals, as done in https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_12_4_13__fastsim_noPU_2021_14TeV-1682560716
with workflow 13240.0? 

This will make MinBias NoPU workflow, and GEN dataset will be generated. The above relvals has only 13240.303 which is a workflow to prepare mixing, and no GEN is stored.

Thx.

**Comment by sunilUIET** [comment]
> Hi @cms-sw/pdmv-l2 Could you please submit a FastSim relvals, as done in https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_12_4_13__fastsim_noPU_2021_14TeV-1682560716 with workflow 13240.0?
> 
> This will make MinBias NoPU workflow, and GEN dataset will be generated. The above relvals has only 13240.303 which is a workflow to prepare mixing, and no GEN is stored.
> 
> Thx.

Hi @srimanob 

Sample is submitted

Sunil

**Comment by srimanob** [comment]
Thanks @sunilUIET, but [this submission](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_12_4_13__fastsim_noPU_PR41945-MinBias_14TeV-00002) will not work. We need exact processing string as before, which is `CMSSW_12_4_13-124X_mcRun3_2022_realistic_v12_2021_FastSim-v`

**Comment by sunilUIET** [comment]
Ok thanks for pointing it out

**Comment by sunilUIET** [comment]
Hi @srimanob 

Sample is available 

https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=CMSSW_12_4_13__fastsim_noPU_2021_14TeV-1686736377

Sunil

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Changes in DQM comes from workflow `13434.0_TTbar_14TeV+2021FSPU`, where the PU datasets change. This change comes from this PR where the 2021FS key is updated to last FastSim relvals in 12_4. So I would say change is expected.

After this PR, we should make a relvals with most recent release, then the key will be updated again. For now, I think it is OK as what we recycle is GEN.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
