### PR TITLE
Configuration arguments for version and packing schema of covariance in DeepJetTag producer [14_0_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds configuration arguments for version and packing schema of covariance to `DeepBoostedJetTagInfoProducer` module. 
Those are used by the module when construction of `hlt_features` is enabled and when the features are constructed from `reco::PFCandidates`, i.e. when the module is run at HLT. In the current code those are hard-coded which causes issues when the HLT RECO and miniAOD steps are run together in one workflow as discussed in #43861 issue.

The implementation is just a technical change and do not change behavior of the module as default values of newly added configuration arguments are equal to values which were hard-coded.

This is verbatim backport of #43917 (actually the same development branch is used for both PRs)

#### PR validation:

Verified that newly added parameters do not change previously used values.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43917 to 14_0_X release series that will be used for 2024 operations.

### CODE REVIEW

**Comment by mmusich** [comment]
type btv

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43917

**Comment by mandrenguyen** [comment]
+1

**Comment by mmusich** [comment]
urgent 
   * for 14_0_0, in order to be parsed in confDB for TSG purposes.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
