### PR TITLE
Improvements to `hltPhase2UpgradeIntegrationTests`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR packages a couple of minor improvements to the `hltPhase2UpgradeIntegrationTests` utility.
   * 228ce134f6b53eb48fa41442378d7952da8c7850 allows usage of cached RAW input data in the test
   * 51874701c3bdeb6e680b19d9904d1c6019fa0ec6 do not run twice the full menu (after having dumped it with `edmConfigDump`)

No regressions are expected, just a small speedup of the execution.

#### PR validation:

Run successfully the following script:

```bash
#!/bin/bash

# Exit the script immediately if any command fails
set -e

# Enable pipefail to propagate the exit status of the entire pipeline
set -o pipefail

# Define the dataset
DATASET="/RelValTTbar_14TeV/CMSSW_14_1_0_pre6-PU_141X_mcRun4_realistic_v1_STD_2026D110_PU-v3/GEN-SIM-DIGI-RAW"

# Fetch the list of files in the dataset
FILES=( $(dasgoclient -query="file dataset=${DATASET}" --limit=-1) )

# Loop through each file in the FILES array and pass it as --cachedInput
for FILE in "${FILES[@]}"; do
  echo "Running HLT test with cached input file: ${FILE}"
  
  hltPhase2UpgradeIntegrationTests \
    --parallelJobs 4 \
    --threads 4 \
    --cachedInput "$FILE" \
    --restrictPathsTo "HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1*"

  # Check if the test failed for a particular file
  if [ $? -ne 0 ]; then
    echo "Error occurred with input file: $FILE"
    exit 1  # Exit the loop if any command fails
  fi
done
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = hlt_p2_integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * script run fine in the tests

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
