### PR TITLE
Apply event filter before data prefetching for OutputModules

### PR DESCRIPTION
**Pull request by Dr15Jones**
There is no reason to prefetch data and subsequently causing either delayed read or unscheduled execution if the TriggerResults being watched designate that the event should not be stored.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failure has nothing to do with this pull request. The failure is caused by the Python module readline not being available on the build machine.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The testing error has nothing to do with this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
