### PR TITLE
L1t gt plus patfix 74x

### PR DESCRIPTION
**Pull request by mulhearn**
This PR combines the new GT PR (#10151) with an update of PAT tuples to cond db v2.  The latter fixes problems that were seen in unit tests of the original GT PR.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mmusich** [comment]
@mulhearn this is still a cheap trick. I agree there is an issue with the unit tests that still run on v1, but the payload in the v1 GT is still brocken

**Comment by mulhearn** [comment]
Sure, I just want to demonstrate the problem.

**Comment by mulhearn** [comment]
I don't know what to say about the difference between V1 and V2 of the cond db.  As I understand, these were put in DB via dropbox so payloads should have been synchronized.

**Comment by mmusich** [comment]
@mulhearn to build the v1 GT I had to migrate the payload from v2 to v1. @diguida suggested that there might have been a serialization issue. Would it be possible to re-run the O2O to write the payload directly in v1 format so that we could overwrite it in v1?

**Comment by mulhearn** [comment]
errrrrrr.... maybe?

**Comment by mulhearn** [comment]
The main problem is that I have a bunch of stuff that needs to be fixed to not disrupt data taking, and I don't believe making conddb V1 work is one of them...

**Comment by mmusich** [comment]
I see, my suggestion therefore would be to remove the autoCond update for what concerns the v1 GT. We have already phased-off V1 autocond in 75X, and as soon as @ggovi backports #8885 we will never hear about v1 again...

**Comment by mulhearn** [comment]
I vote for that!

**Comment by Martin-Grunewald** [comment]
Ah that famous PR which turned "connect" within "toGet" from untracked into tracked.
I just tripped over that when I added the newer L1 Menus to the GTs to cover the newer
HLT menus needing newer L1 menus...

**Comment by mulhearn** [comment]
@mmusich:  just to be clear, you will handle removing the V1 stuff from your PR, or do you need something from me?

**Comment by mmusich** [comment]
@mulhearn I'll do that.

**Comment by mmusich** [comment]
@mulhearn I have updated #10151 cherry-picking your commit, with the promised fix for v1. I would then supersed yours.

**Comment by diguida** [comment]
-1
superseded by #10151

**Pull request closed without merging**
