### PR TITLE
Avoid empty FED occupancy plot in PixDQM

### PR DESCRIPTION
**Pull request by fioriNTU**
Avoid empty FED occupancy histo in Offline Pix DQM

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
