### PR TITLE
[HGC trigger] Update module mapping

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
Update module mapping with additional wafers appearing after fix in the definition of valid cells. Fix issue #31506.

Depends on external  cms-data/L1Trigger-L1THGCal#20

#### PR validation:
Tested workflow 23234.0
Removes warning messages.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
pull_requests = cms-data/L1Trigger-L1THGCal#20

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
@jbsauvan Thanks.  Should we have a backport to CMSSW_11_1_X? 

As I understand, this PR is not meant to introduce any changes on the active HGC cells, and therefore is not supposed to have any effect on Level1 Phase2 Trigger ParticleFlow and Egamma in the EndCap.   Strictly speaking, we should have a backport of this PR into 11_1, in which case it would be included it in the finally validated release for reprocessing of HLT TDR samples.  (Attn @kpedro88 @silviodonato @Sam-Harper @fwyzard )

Attn: @gpetruc @cerminar

**Comment by rekovic** [comment]
+1

**Comment by jbsauvan** [comment]
@rekovic, there is no effect on the active trigger cells.
It will only fix the warnings that appeared after a fix in the HGCAL geometry (#31428). And in any case, it doesn't seem that this PR has been backported.

**Comment by silviodonato** [comment]
+1

**Comment by rekovic** [comment]
@jbsauvan  Mind you that this PR is depending on a newly introduced external library in 11_2.  Fine with me if other stake-holders are OK to go without backport. If no backport is made, one less thing to change underneath in 11_1.

**Comment by rekovic** [comment]
As I said, I don't expect any effects on L1T, but to be safe with 11_2 this will have to be validated in the future, ideally future Phase2 L1T RelVal and Phase2 HLT RelVal).

**Comment by kpedro88** [comment]
as @jbsauvan indicated, this PR is needed for compatibility with an HGCal geometry bug fix that has not been backported to 11_1_X. (It was deemed too late to include this in HLT TDR production, since most of the production is already finished, and the physics changes are minimal.) Therefore, this PR should not be backported either.

**Pull request merged**
