### PR TITLE
move also ttbarlepton to py8

### PR DESCRIPTION
**Pull request by franzoni**
replace TTbarLepton_Tauola_13TeV_cfi with TTbar_13TeV_TuneCUETP8M1_cfi
follow up to: https://hypernews.cern.ch/HyperNews/CMS/get/relval/3550/6.html

### CODE REVIEW

**Comment by franzoni** [comment]
@bendavid
@inugent

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
