### PR TITLE
Improved options handling for TensorFlow sessions

### PR DESCRIPTION
**Pull request by valsdav**
#### PR description:

This PR is a follow up from PR #40551,  https://github.com/cms-sw/cmssw/pull/40551#issuecomment-1427687134.

The PR improves the handling of the TF interface options by creating a new struct: 

```
Options {
    int _nThreads;
    Backend _backend;
    SessionOptions _options;
}
```

This change allows to have always a well defined default backend for TF sessions created with default options.
Moreover it simplifies the multiple overloaded functions  for TF graph loading and session creation.

We will try to make the interface to ONNX more  similar to the TF one in a separate PR,  as in https://github.com/cms-sw/cmssw/pull/39402

#### PR validation:

Technical PR: no changes on the reconstruction output are expected.

@riga @yongbinfeng

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
technical, no changes to reco comparisons

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@valsdav , I am testing TF 2.11 (https://github.com/cms-sw/cmsdist/pull/8258) and looks like all the TF-CUdA tests are crashing see details https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-39ea0b/31966/unitTests/failed.html.  I do see some warnings like [a] , any idea?

[a]
```
Running .WARNING:tensorflow:From /scratch/cmsbuild/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/el8_ppc64le_gcc11/external/py3-cmsml/0.1.2-29bd4c560ef9ea2cce051815781d3ff4/lib/python3.9/site-packages/cmsml/tensorflow/tools.py:120: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.
WARNING:tensorflow:From /scratch/cmsbuild/jenkins_a/workspace/ib-run-pr-tests/testBuildDir/el8_ppc64le_gcc11/external/py3-tensorflow/2.11.0-ce371cbe783600d67100f17a915f5d3f/lib/python3.9/site-packages/tensorflow/python/framework/convert_to_constants.py:943: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.

```

**Pull request merged**
