### PR TITLE
750 tracking particles PreMixing fixes

### PR DESCRIPTION
**Pull request by mdhildreth**
Modify merging of tracking particles to update references between new copies of TrackingParticles and TrackingVertices.  Set "validation" mode to be default for first PreMixing stage in RelVals so TrackingParticles are produced automatically.

### CODE REVIEW

**Comment by mdhildreth** [comment]
Waiting for validation from DPG folks.  Don't merge just yet!

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

@mdhildreth, @makortel  - is this ready now?

**Comment by makortel** [comment]
@davidlange6 I think this is still work in progress (e.g. I understood from @mdhildreth that he would some further developments for muons that I don't see here). But for tracking validation the following works
```
# Re-produce premixed pileup events
runTheMatrix.py -i all -l 250199.0

# Produce configurations only for subsequent steps 
# Apply the customisation only to step3 (yes, --apply has to be 2)
runTheMatrix.py -i all -l 250202.0 -j 0 --command="--customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPremixingInput" --apply 2
cd 250202.0*
cat >> step2_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_RAW2DIGI_L1Reco.py <<EOF
process.mixData.input.fileNames = ["file:$PWD/../250199.0_PREMIXUP15_PU25+PREMIXUP15_PU25/step1.root"]
process.FEVTDEBUGHLToutput.outputCommands.extend([
    "keep TrackingParticles_mixData_*_*",
    "keep TrackingVertexs_mixData_*_*",
    'keep *_*_StripDigiSimLink_*',
    'keep *_*_PixelDigiSimLink_*'
])
EOF
cmsRun step2_DIGIPREMIX_S2_DATAMIX_L1_DIGI2RAW_HLT_RAW2DIGI_L1Reco.py
cmsRun step3_RAW2DIGI_L1Reco_RECO_EI_VALIDATION_DQM.py
cmsRun step4_HARVESTING.py 
```
I have only tested with handful of events and not compared the results to classical mixing, but I can see from MTV output that it gets pileup TrackingParticles and e.g. fake rates have qualitatively similar structure as with classical mixing.

Important points
* premixed pileup events need to be reproduced (with `DIGIPREMIX:pdigi_valid`, as the default should be after this PR)
* step2 event content needs modifications (FEVTDEBUGHLT does not contain PREMIXRAWEventContent?)
* step3 needs `--customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPremixingInput`

The step3 output will be full of messages like
```
*** WARNING in MuonAssociatorByHitsHelper::associateRecoToSim: no matching PSimHit found for this reco::Track !
*** WARNING in CSCHitAssociator::associateCSCHitId - CSC layer 604018234 has no DigiSimLinks ! 
```
for whose I understood @mdhildreth should have further developments (not yet fully working).

**Comment by mdhildreth** [comment]
Gah!  The local repository in my working directory got corrupted, so I moved my changes on top of a nightly build since I didn't want to overwrite them.  Will have to re-base, somehow.

**Comment by slava77** [comment]
a rebase would be nice without all extra merge commits (so that my signature is not needed)

**Comment by mdhildreth** [comment]
Slava, looks like, even though there are no Reco packages, it thinks you still need to sign.  Past history?

**Comment by mdhildreth** [comment]
Still more changes coming...

**Comment by slava77** [comment]
Mike,
the need for reco signature went away.
Nice, one less PR on the list.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
is this P reqeust still relevant / needed ?

**Comment by makortel** [comment]
@franzoni Yes (although still not final, IIUC).

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by mdhildreth** [comment]
+1.  Ready to go, finally.

**Comment by mdhildreth** [comment]
+1

**Comment by fwyzard** [comment]
According to github there are over 250 commits.
Are you sure this does not need to be rebased ?

**Comment by mdhildreth** [comment]
@#$*&!!$#$&#&   (Swear words).  Ok, I will re-base, again.

**Comment by Dr15Jones** [comment]
please test

**Comment by deguio** [comment]
-1
DQM signature not needed. waiting for a rebase IIUC.

**Comment by mdhildreth** [comment]
Rebased now

**Comment by mdhildreth** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
DQM slightly touched

**Pull request merged**
