### PR TITLE
Remove run3_nanoAOD_122 & 124 modifiers

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

This PR removes the outdated `run3_nanoAOD_122` and `run3_nanoAOD_124` era modifiers.

#### PR validation:

`runTheMatrix.py -w nano --ibeos -l 2500.101,2500.111,2500.201,2500.211,2500.024`

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
@hqucms
This needs to resolve conflicts.

**Comment by hqucms** [comment]
+1

**Pull request merged**
