### PR TITLE
Remove the stream id from the MonitorElement public interface

### PR DESCRIPTION
**Pull request by fwyzard**
Complete the changes initiated in #22218 .

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
@fwyzard do you know if this fixes https://github.com/cms-sw/cmssw/issues/22281 ?

**Comment by fwyzard** [comment]
> @fwyzard do you know if this fixes #22281 ?

By itself I don't think it will, since the dependencies among the DQM modules are still missing.

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild please test with #22319

**Comment by dmitrijus** [comment]
please test with #22319

**Comment by fabiocos** [comment]
@fwyzard if I repeat the failing addOn test while merging this PR on top of the present master I see it works smoothly. Let's see the output of your new test

**Comment by fabiocos** [comment]
@dmitrijus @fwyzard the previous failure problem is solved, but in the test the comparison of AlcaReco histograms show lots of differences. For my understanding what is causing this behaviour in the PR?

**Comment by fwyzard** [comment]
I think the comparison we should do is from the latest IB pre-#22218 (or plain pre1) vs an IB with #22319 and #22364 (this PR).

If this is already the comparison you are looking at, can you point us to it ?

**Comment by fabiocos** [comment]
@fwyzard no, I was referring to the one of the test, that could start from a messy situation. I'll check it, in the meanwhile I integrate the PRs as they at least fix the issue of the missing ME.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
comparing the output of wf 4.53 of this test with that of CMSSW_10_1_0_pre1, the amount of differences observed in AlcaReco is vastly smaller, 7 histograms instead of 14865, so this sounds reassuring.

**Pull request merged**
