### PR TITLE
esConsumes migration of HLTrigger/

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This is a technical PR to address #31061 for the packages under `HLTrigger/`.

I'm not entirely sure I got all of them; experts could maybe suggest how to check this, if needed.

For some producers, some cleanup of `#include` statements was also done.

#### PR validation:

Passed a limited set of workflows with `runTheMatrix.py`.                                                                                                                                          

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Great stuff, @missirol , thanks a lot!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
