### PR TITLE
delete orphan scripts accessing Geometry_cff / GeometryDB_cff

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Following up the migration of Geometry_cff to GeometryDB_cff (#35278), proper GlobalTag needs to be set in advance. As
contacted to the sub-system experts, out-of-date scripts that won't be fixed would be cleaned up.

#### PR validation:

delete out-dates script.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a back port and no back port expected. These scripts will be kept in old CMSSW versions.

### CODE REVIEW

**Comment by tvami** [comment]
FYI @hyunyong

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type muon

**Comment by ChrisMisan** [comment]
+alca

- differences only in msgLogger and MTD
- PR in line with the description

**Comment by perrotta** [comment]
+1

**Pull request merged**
