### PR TITLE
Phase2-gex09 Add a new muon subscenario with changes for GEM

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new muon subscenario with changes for GEM. The complete scenario is not defined - will be done once the PR#31225 is integrated

#### PR validation:

Testing will be done once the workflow is fully defined.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @kpedro88 Could you approve this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
