### PR TITLE
HLTrigger for UPC Analysis for 80X Fix Final v2

### PR DESCRIPTION
**Pull request by illuzate**
Please check it as soon as possible.

### CODE REVIEW

**Comment by illuzate** [comment]
Please check it as soon as possible.

**Comment by dmitrijus** [comment]
You need to submit these changes to upstream first. I haven't seen a PR to 81x :(

**Comment by illuzate** [comment]
Hi. 
https://github.com/cms-sw/cmssw/pull/16415
Here is the link to the PR to 81X. :)

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
