### PR TITLE
Jet ID and b-tag information for Scouting Calojets

### PR DESCRIPTION
**Pull request by duanders**
This PR modifies HLTScoutingCaloProducer so that it can put b-tag and jet ID information (provided as JetTagCollections) into ScoutingCaloJet objects.

The change does not modify the current behavior of this producer in the HLT menu.  The new options (doJetBTags and doJetIDTags) are turned off by default.  

This is related to the PR from @silviodonato (https://github.com/cms-sw/cmssw/pull/14269), but the PRs can be merged independently of one another.  

When this looks ok, I will submit a backport PR for 80X.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1
Please make a PR for 80X.

**Comment by duanders** [comment]
Thanks, backport to 80X is here: https://github.com/cms-sw/cmssw/pull/14279

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Could you please sign this PR or comment otherwise?
Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
