### PR TITLE
HLT menu development for `14_0_X` (10/N) [`14_2_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_0_X` (branch `CMSSW_14_2_X`).
   * This is the PR for the master branch, which will then be backported down to 14_0_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
   * These updates correspond to the changes accumulated in the 14_0_X release cycle after the "V1.4" (last) menu for the 2024 pp data-taking period was released, and target the 2024 HIon and PRef data-taking as well as the first pp menu for 2025.
   
This update includes the integration of the following JIRA tickets:

- [CMSHLT-3296](https://its.cern.ch/jira/browse/CMSHLT-3296) [TSG] Remove unused Paths of the Special table
- [CMSHLT-3298](https://its.cern.ch/jira/browse/CMSHLT-3298) [TSG] Remove suppression of warnings and errors from HLT MessageLogger for `hltOnlineBeamSpot`
- [CMSHLT-3303](https://its.cern.ch/jira/browse/CMSHLT-3303) [EXO] Add missing `hltIter2MergedForDisplaced` from HLTMonitor event content
- [CMSHLT-3310](https://its.cern.ch/jira/browse/CMSHLT-3310) [TSG] Update to 2024 eras in TSG tests
- [CMSHLT-3306](https://its.cern.ch/jira/browse/CMSHLT-3306) [HIon/DQM] Review of HIDQM EventContent (HI Run 2024)
- [CMSHLT-3307](https://its.cern.ch/jira/browse/CMSHLT-3307) [BRIL] Update "LumiScan" offline menu (post Run2024G)
- [CMSHLT-3329](https://its.cern.ch/jira/browse/CMSHLT-3329) [Egamma/PF]  Fix mismatch of EB and EE recHits in supercluster producer modules
- [CMSHLT-3284](https://its.cern.ch/jira/browse/CMSHLT-3284) [HIon/TRK] Move to Pixel-Alpaka modules in the HIon menu
- [CMSHLT-3309](https://its.cern.ch/jira/browse/CMSHLT-3309) [DQM] Update DeltaR matching cut for `hltPixelTracksSoACompareGPUvsCPU` and `hltSiPixelTracksSoACompareGPUvsCPUPPOnAA`
- [CMSHLT-3323](https://its.cern.ch/jira/browse/CMSHLT-3323) [HIon] Muon Triggers for pp Reference Run 2024
- [CMSHLT-3332](https://its.cern.ch/jira/browse/CMSHLT-3332) [DQM] Fix inconsistent module labels for `HLTDQMPixelReconstruction` vs `HLTDQMPixelReconstructionPPOnAA`

In addition, the following changes are included:
   * 5b0df292e97ac9a9bf639b330574bb6d221f2d58: update of L1T PRef menu in TSG GTs to `L1Menu_CollisionsPPRef2024_v0_0_2_xml`
   * c171eb2fdaaf22a120baf062943e156cb7122da1:  remove `customizeHLTforAlpaka.py` file from 14.2.X branch

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_0_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
+hlt
   * changes observed in the HLT EXO DQM output (https://github.com/cms-sw/cmssw/pull/46048#issuecomment-2361370057) are due to the integration of [CMSHLT-3303](https://its.cern.ch/jira/browse/CMSHLT-3303)

**Comment by mmusich** [comment]
@cms-sw/orp-l2 please consider merging this (and all its backports markded as `hlt-integration`). We need to move forward to integrate more tickets for the upcoming `HIon` run

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
