### PR TITLE
Update muon timing analyzer 81x

### PR DESCRIPTION
**Pull request by jalimena**
Update the MuonTimingValidator to use getByToken and change debug bools to LogDebugs.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jalimena** [comment]
The tests have failed, but I don't understand the error or how to fix it. Any advice? Thanks!

**Comment by jalimena** [comment]
Actually, it looks like it is trying to test this on 2011 HI data? Is that necessary?

**Comment by slava77** [comment]
@cmsbuild please test
DAS errors are usually transient

**Comment by jalimena** [comment]
maybe the DAS error is fixed today? third time's the charm?
@cmsbuild please test

**Comment by slava77** [comment]
@jalimena 
this time it was not a transient error: the files for this workflow were removed from T2 CERN disk.
I think the transfer request is pending.

**Comment by slava77** [comment]
your changes are all in /test subdirectory. So, the completion of the tests running standard processing workflows is not necessary.

**Comment by cvuosalo** [comment]
+1

For #15348 927be351c8f1e54b76f82c7f1dcd2ccc04be057d

Code clean-up of muon timing analyzer used for testing. There should be no change in monitored quantities.

#15349 is the 80X version of this PR.

The code changes are satisfactory. Jenkins compilation and unit tests show no problems. The standard Jenkins workflows, which are not completing right now for any PRs, are not relevant for this PR, which only changes files under "test".

**Comment by jalimena** [comment]
thanks!

**Pull request merged**
