### PR TITLE
[CORE] Remove unused python scripts in FWCore/MessageService/test/PsetValidationSamples

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Fix syntax in python scripts:

* Switch to python 3 syntax: `print()`, `except ... as`
* Partial fix for indentation: make all indented line use the same characters for indentation (either spaces or tabs), remove mixing of tabs and spaces
* Add missing braces and commas, fix invalid syntax (`FWLiteEnabler::enable()` should be `ROOT.FWLiteEnabler.enable()`), remove trailing semicolons
* Replaced (potentially unsafe) `exec` with `import_module`

This is a preparation for fixing #46113 . Maybe some of these scripts are not needed anymore and can be removed?

#### PR validation:

Bot tests.

### CODE REVIEW

**Comment by makortel** [comment]
@Dr15Jones @wddgit Do you know if the files in `FWCore/MessageService/test/PsetValidationSamples/` are used for anything? By quick `git grep` I didn't see any indication they would be used by anything (and clearly the `debugModules_cfg.py` is not used).

Could we consider removing all these? Or are these meant as examples?

**Comment by makortel** [comment]
After looking a bit more detail, it seems these files were added in 546e000e5cf0984127fe0744f21591fc1015de79 as a very manual test (one would have to edit the files, and check the output). I'd bet these files are practically useless now, and would be best to be removed.

@iarspider Could you remove the directory `FWCore/MessageService/test/PsetValidationSamples/` instead?

**Comment by iarspider** [comment]
please test

**Comment by makortel** [comment]
Thanks. Could you also update the PR title?

**Comment by wddgit** [comment]
I wasn't aware these files existed. I agree that deleting is probably the best choice.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
