### PR TITLE
Fixes to  L3 Muon OI SeedGenerator (TSGForOI) for improved efficiency

### PR DESCRIPTION
**Pull request by bmahakud**
- The fixes added is supposed to enhance the L3 Outside-in reconstruction efficiency up to 3-4% depending on eta region 
    -  link to slides in HLT meeting : https://indico.cern.ch/event/724303/contributions/2979159/attachments/1638779/2615747/OI_improvementsPurdue_24thApril2018.pdf

- Currently OI starts from L2 muons with
    - Trajectory State on Surface (TSOS) in innermost Muon station (1)
    - TSOS at vertex after updating the parameters with vertex information (2) 
- Fix-I
    - Check compatibility between (1) and (2)
        - 5 parameter Chi2 and DeltaR(OuterTrakerStateInside,OuterTrackerStateOutside) 
        - If the two TSOS are too far apart use both states to start seed generation
   - To use (1)
       - first propagate from muon system to outer tracker surface using SteppingHelixPropagator,
       -  then use 'PropagatorWithMaterialParabolicMf' to propagate to TOB and TEC layers.  (In the previous version 'PropagatorWithMaterial' was used for both propagation steps.)
- Fix-II
   - Seeds are created on the outermost 2 layers:
      - The layer counter was not properly initialized before we proceed to step (2)
      - Has been fixed, initialized to 0 before layers are found for generating seeds using
TSOS at muon station
      - Scale factors have been optimized for different rapidity ranges:
           - Smaller scale factor in Barrel and Larger in the Endcap Use more eta bins 

- Fix-III
  - Optimize eta range where hits on stereo TEC dets are used to build seeds
    -  Before: If the L2 muon is 0.8-1.6
        - Create seeds using the stereo modules
        - Skip the modules without stereo hits
    - Now: 
       - Range is optimized to: (1.1 to 2.0 ) and (2.15 to 2.4)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@bmahakud 
please add a link to slides in a muon POG meeting and some brief description of expected changes in performance. Preferably, please edit the PR description text (the first text block in the page currently starting with "Fixes ").

**Comment by slava77** [comment]
```
   [1] Validating configuration of module: class=TSGForOI label='hltIterL3OISeedsFromL2Muons'
Exception Message:
Illegal parameter found in configuration.  The parameter is named:
 'tsosDiff'

```
the error is related to this PR.
Please fix and test locally first and then update this PR.

**Comment by bmahakud** [comment]
Dear Slava,

We found some more important fixes that improves the efficiency further. We will update this pull request after adding the changes. We have noted that there is this bug:
[1] Validating configuration of module: class=TSGForOI label='hltIterL3OISeedsFromL2Muons'
Exception Message:
Illegal parameter found in configuration.  The parameter is named:
 'tsosDiff'

We will fix this. This error has come because we have introduced few more parameters in the config.

We could provide the update on this pull request within one week from now.

Regards
Bibhu

**Comment by slava77** [comment]
@bmahakud 
regarding https://github.com/cms-sw/cmssw/pull/22912#issuecomment-379899853
are there some slides available to describe the expected performance of the updates?

Please add "muon" somewhere in the title of the PR and perhaps drop the april52018.

Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by bmahakud** [comment]
Dear Slava,

I have changed title of the PR. The slides are sent around including you. I hope you have received it.
The slides are also available here for the moment. 
http://bmahakud.web.cern.ch/bmahakud/MuonHLT/SecondRoundOIfixSlides/OI_improvementsPurdue.pdf

**Comment by slava77** [comment]
@bmahakud 
thank you for updating the title. However, now it is even less grammatically sound (MuonL3_OIseedGeneratorFix) than the previous one (Tracker seed generator fix april52018).
Please use a bit more plain English.
Thank you.

**Comment by slava77** [comment]
> I have changed title of the PR. The slides are sent around including you. 

Thank you.
Please make sure that the information about the slides is visible immediately in the PR description.
The primary goal is an improved self-documentation, not so much my personal education.

**Comment by slava77** [comment]
-1

http://cms-sw.github.io/PRWorkflow
The section "Before making your pull request" is probably of the most relevance for this PR.


apparently the updates did not intend to fix the operational problem yet
https://github.com/cms-sw/cmssw/pull/22912#issuecomment-381585805

It may be more practical to close the PR and reopen when all tests are expected to pass

**Comment by bmahakud** [comment]
Hi Slava,
I will get back with all the checks and description of the PR text in one day.

Thanks
Bibhu

**Comment by bmahakud** [comment]
Just few more changes to the code (improvements ) added so that people can look at this during today's meeting (24th April 2018) .  All code checks (runthematrix etc) are not performed yet. Will be updated soon

**Pull request closed without merging**
