### PR TITLE
Remove old-style track associator ESProducer configuration files

### PR DESCRIPTION
**Pull request by makortel**
The old-style associators and ESProducers were removed in #8635, but somehow I missed these files.

Tested in CMSSW_7_5_X_2015-04-20-2300, no changes in production workflows expected.

@rovere @VinInn

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
