### PR TITLE
Use puppi jets for phase2 scenario for PF validation

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

Monitor puppi jets instead of ak4 chs jets for phase2 scenarios

#### PR validation:

Compiles. Tested with phase2 scenarios.

#### if this PR is a backport please specify the original PR:

Not backport.

@juska @bendavid

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
DQM changes are only in phase2 workflows for PFlow JetResponse, as expected

**Comment by hatakeyamak** [comment]
Yes, looks good to me.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
