### PR TITLE
Fix Pedestal EB RMS threshold. Enable multifit chi2 cut.

### PR DESCRIPTION
**Pull request by mbandrews**
Fix Pedestal RMS threshold for EB to ( G1:1.0, G6:1.2, G12:2.0 ) ADC.

Enable chi2 cut for EB multifit.

### CODE REVIEW

**Comment by slava77** [comment]
@mbandrews please describe the physics impact (changes in observable distributions) expected for default reconstructed objects after this change. (e.g. what happens to rechits, clusters, egamma objects response).

If there is any noticeable physics change, it should be first implemented in 80X.
We can discuss backports based on integration results in 80X.

@emanueledimarco @argiro

**Comment by mbandrews** [comment]
@slava77 the chi2 cut should reduce the presence of spikes in rechits. This was requested by @emanueledimarco. I was planning on implementing this for 74X, 75X, 76X, and 80X.

**Comment by slava77** [comment]
We do not plan any low level reco changes in 74X.

@emanueledimarco are the changes significant?
If this changes MC in any way, we need an approval from physics coordination that these changes are needed in 76X
(if the change affects only data, it can probably still make it to 76X)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mbandrews** [comment]
Will modify chi2 cut to be applied only at dqm level.

**Comment by emanueledimarco** [comment]
@mbandrews @slava77 There was a misunderstanding here. 
This development should only enable the chi2 cut for hits entering the DQM plots. 
It should not be enabled in the ECAL local reconstruction (yet) until a study on the impact of such a filtering on physics quantities is performed. This won't be done for 76X, clearly. 
So the PR should only contain changes in DQM, not in RecoLocalCalo.

**Comment by slava77** [comment]
On 11/9/15 11:30 PM, Emanuele Di Marco wrote:
> @mbandrews <https://github.com/mbandrews> @slava77
> <https://github.com/slava77> There was a misunderstanding here.
> This development should only enable the chi2 cut for hits entering the
> DQM plots.
> It should not be enabled in the ECAL local reconstruction (yet) until a
> study on the impact of such a filtering on physics quantities is
> performed. This won't be done for 76X, clearly.
> So the PR should only contain changes in DQM, not in RecoLocalCalo.
> 

Updates for the DQM only make sense to me.
Thanks for the clarification.

**Pull request closed without merging**
