### PR TITLE
Common pp_on_AA modifier for 2018 and run 3 AA eras

### PR DESCRIPTION
**Pull request by mandrenguyen**
Use a common modifier 'pp_on_AA' for both Run2_2018_pp_on_AA and Run3_pp_on_PbPb eras.
Run3_pp_on_PbPb was initially implemented as a superset of Run2_2018_pp_on_AA, but they were factorized in #31668
This PR restores the previous behavior in a cleaner way. 
Run2_2018_pp_on_AA workflows should be unaffected, while Run3_pp_on_PbPb picks up many customizations that were dropped. 

The lighter systems (pPb, XeXe, pp ref and peripheral PbPb) are not included in the common modifier.  
One could imagine further adding an overarching process modifier for all heavy ion eras, since they have some common features.  
This is left for a possible future PR. 

I tested with wfs 158 and 159.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
I see Static Check build errors unrelated to this PR, does anybody have any idea of their source?

**Comment by makortel** [comment]
@jfernan2 Is the log itself not sufficient? Anyway, the static analyzer will give the subset of the total of ~41k warnings that originate from these packages.

**Comment by jfernan2** [comment]
Yes, the log is enough, I was just wondering why they do appear on this PR, which is not touching those pieces of code which crash now

**Comment by jpata** [comment]
Is it possible the static checker issues get triggered because this PR touches files in those packages, even though the change is unrelated to the pre-existing issues that the static checker now uncovers?
In this case, I would think it's high priority for the relevant POGs (several in this case) to fix those issues so that the code can be compiled and our tests keep passing.

Or did the static checker become more strict recently?

**Comment by makortel** [comment]
> Is it possible the static checker issues get triggered because this PR touches files in those packages, even though the change is unrelated to the pre-existing issues that the static checker now uncovers?

Yes, this is exactly what happens. (that's what I tried to say in https://github.com/cms-sw/cmssw/pull/31935#issuecomment-716577905).

**Comment by makortel** [comment]
By the way, there is a conflict now.

**Comment by jpata** [comment]
Thanks for the clarification!

> Note that static analyzer warnings do not flag tests to be failed (currently at least).

OK, so in principle this PR can move forward despite failing static checks. Nevertheless, we will highlight these code issues from the reco side with the relevant POGs and try to move forward with this.

@mandrenguyen can you take care of the conflict by rebasing?

**Comment by mandrenguyen** [comment]
> Thanks for the clarification!
> 
> > Note that static analyzer warnings do not flag tests to be failed (currently at least).
> 
> OK, so in principle this PR can move forward despite failing static checks. Nevertheless, we will highlight these code issues from the reco side with the relevant POGs and try to move forward with this.
> 
> @mandrenguyen can you take care of the conflict by rebasing?

Yes, just waiting for today's 11AM IB

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
please abort

**Comment by jpata** [comment]
@cmsbuild please test workflow 158.0,159.0

**Comment by jpata** [comment]
@cmsbuild please test workflow 158.0, 159.0

**Comment by jpata** [comment]
@cmsbuild please abort

**Comment by jpata** [comment]
Here's the issue for all tests:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e519da/10382/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

```python
RAW2DIGI,L1Reco,RECO,DQM
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in <module>
    run()
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/python/Configuration/Applications/ConfigBuilder.py", line 2127, in prepare
    self.loadAndRemember(self.EVTCONTDefaultCFF)  #load the event contents regardless
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/python/Configuration/Applications/ConfigBuilder.py", line 325, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-29-1100/python/FWCore/ParameterSet/Config.py", line 683, in load
    module = __import__(moduleName)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/python/Configuration/EventContent/EventContentCosmics_cff.py", line 59, in <module>
    from Configuration.EventContent.EventContent_cff import REGENEventContent,RESIMEventContent,REDIGIEventContent
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/python/Configuration/EventContent/EventContent_cff.py", line 799, in <module>
    from PhysicsTools.PatAlgos.slimming.slimming_cff import MicroEventContent,MicroEventContentMC,MicroEventContentGEN
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-29-1100/python/PhysicsTools/PatAlgos/slimming/slimming_cff.py", line 86, in <module>
    pp_on_AA_2018.toReplaceWith(
NameError: name 'pp_on_AA_2018' is not defined
```

**Comment by perrotta** [comment]
@cmsbuild please test workflow 159.0

**Comment by jfernan2** [comment]
+1

**Comment by jpata** [comment]
+reconstruction

- adds a modifier pp_on_AA instead of pp_on_AA_2018 for HI workflows
- standard reco is not affected
- HI test workflows 158.0 and 159.0 run successfully
- static analyzer failures are unrelated to the changes

**Comment by silviodonato** [comment]
+operations

**Comment by civanch** [comment]
+1

**Comment by christopheralanwest** [comment]
+alca

**Comment by rekovic** [comment]
+1

**Comment by slava77** [comment]
@qliphy @silviodonato 
may I suggest not to wait for analysis signature here.
Please consider.
Thank you.

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
