### PR TITLE
Minimal Change: reading tags from CondDBv2

### PR DESCRIPTION
**Pull request by mmusich**
Backported from 80X (#12094)

### CODE REVIEW

**Comment by mmusich** [comment]
@diguida @franzoni

**Comment by mmusich** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #12228 5f89c7b53fb125edb0ea971ebc9ecbdaa3f9d09c

Small change for reading tau tags from CondDBv2. #12094 is the 80X version of this PR, and it has already been merged.

Jenkins tests against baseline CMSSW_7_6_X_2015-11-01-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
