### PR TITLE
Fixing Memory Coruption for large histograms in DQMFileSaverPB : 12_4_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This is the backport of  https://github.com/cms-sw/cmssw/pull/38112

DQMFileSaverPB allocates its buffer to compress the histogram on the stack. This means it is limited to a size of 10MB. There are histograms which are bigger than this (specifically HLT paths vs bx) and thus can exceed this limit and crash the client. We encountered this when running the full menu of 800+ paths.

#### PR validation:

DQM team report successful playback

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/38112

needed for P5 DQM release series (aka 12_3, 12_4)

### CODE REVIEW

**Comment by Sam-Harper** [comment]
please test

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38112

(labels..)

**Comment by pmandrik** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
