### PR TITLE
Update of the HLT menu (100X)

### PR DESCRIPTION
**Pull request by silviodonato**
Update of the HLT menu to /dev/CMSSW_10_0_0/HLT/V140
based on L1Menu_Collisions2018_v0_0_1.

(base release: CMSSW_10_0_4)

101X: #22561

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
Error due to xrootd, I'll try again in a while:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22562/26818/runTheMatrix-results/136.788_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017/step2_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017.log

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_10_0_4.

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
Errors due to file readout. We'll try again in a while

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22562/26873/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step2_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT.log

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22562/26873/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step2_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
