### PR TITLE
Add ECAL-only workflows for 2018 data

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement ECAL-only local reconstruction workflows runnig over 2018D data, using the same sequences as the similar MC workflows (minus the MC-based validation):
  - **136.885511**: 2018D HLTPhysics dataset, ECAL-only running on CPU
  - **136.885512**: 2018D HLTPhysics dataset, ECAL-only running on GPU (currently a placeholder)
  - **136.888511**: 2018D JetHT dataset, ECAL-only running on CPU
  - **136.888512**: 2018D JetHT dataset, ECAL-only running on GPU (currently a placeholder)

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test workflow 136.885511, 136.885512, 136.888511, 136.888512

**Comment by fwyzard** [comment]
@rchatter @amassiro FYI

**Comment by rchatter** [comment]
> @rchatter @amassiro FYI

Thanks Andrea!

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
