### PR TITLE
Rebased full L1T O2O for 80X

### PR DESCRIPTION
**Pull request by kkotov**
A backport of https://github.com/cms-sw/cmssw/pull/15625 that is supposed to run in production at p5.
Validated on the whole of runs taken in August.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by kkotov** [comment]
Hmm, I wonder what is happening with the tests. It has been a day already, but there are still no results available. People cannot sign-off until the tests are done.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@smuzaffar 
the test trigger was somehow received on Monday but not results ever came back. Might you help with this please (in the meantime we've re-triggered the tests)

**Comment by smuzaffar** [comment]
@franzoni , jenkins/cms-bot is not ready to run tests for patchX branches which is in this case CMSSW_8_0_18_patchX. Ae you sure that this PR should go in a patch release?

**Comment by mmusich** [comment]
no... it should go in mainstream 80x. @kkotov can you please change the target branch (needs a new PR)?

**Comment by kkotov** [comment]
Ok, closing this and opening new PR. Now I only wonder which release I used for rebasing ... guess we will see it soon :0)

**Pull request closed without merging**
