### PR TITLE
Add support for CaloParticle in Fireworks

### PR DESCRIPTION
**Pull request by rovere**
CaloParticles have been added to Fireworks. They are displayed using the
track information coming from the associated simTrack, plus all the
information coming from the linked simClusters.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by rovere** [comment]
Yes I tested it in my private build of Fireworks.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
