### PR TITLE
Validation/Geometry: Tracker/HGCal Material Budget 'Other' Category fix

### PR DESCRIPTION
**Pull request by vargasa**
Work done with @apsallid regarding the Material Budget studies for Tracker/HGCal. For details please refer to:

*  https://github.com/cms-sw/cmssw/commit/24b5920d0dd9603af9b8f27a648d9fec7a368c6f#r31034588

### CODE REVIEW

**Comment by vargasa** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+geometry

**Comment by andrius-k** [comment]
Hi @vargasa, could you please make sure that subsystem name appears in the title of the PR?

**Comment by vargasa** [comment]
@andrius-k Do you mean to specify Tracker/HGCal in this PR?

**Comment by andrius-k** [comment]
@vargasa yes please.

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+geometry

**Comment by vargasa** [comment]
Hello @andrius-k. Is there any other suggestion/modification to be done here?

**Comment by andrius-k** [comment]
Hi @vargasa, you mentioned that there will be a back-port of this PR. Did I miss it?

**Comment by boudoul** [comment]
hello @andrius-k , @vargasa   - Remind me,  what would be the point of a backport ?  Thanks

**Comment by vargasa** [comment]
@boudoul it is 10_3_X. @andrius-k Thanks for the reminder, as I see https://github.com/cms-sw/cmssw/pull/24625/ also needs a backport as the milestone was changed in the review process. I'm looking into it

**Comment by fabiocos** [comment]
@vargasa @andrius-k this PR seems fully contained in #25133, am I correct? In this case I suggest to close this one and push forward the latter

**Comment by vargasa** [comment]
@fabiocos there should be no problem if you merge this PR first. I'd like to keep them separate as they address different problems as well

**Comment by fabiocos** [comment]
@vargasa well, this PR is what I understand, I have doubts on the other one https://github.com/cms-sw/cmssw/pull/25133#issuecomment-437299488

**Comment by fabiocos** [comment]
@andrius-k I will move forward with the integration of this PR, as you have signed already #25133 that is containing this one. Please sign it for reference anyway

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
