### PR TITLE
[LLVM10] Fixing compilation warnings for SIM/GEOM

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

- DetectorDescription/DDCMS/src/DDSpecparRegistry.cc: Return `string_view` instead of address of local temporary string object.
- SimTracker/TrackerMaterialAnalysis/plugins/dd4hep/DD4hep_MaterialAccountingGroup.cc :  Avoid loop variable copy.

#### PR validation:

Local compilation for CLANG and normal IBs show no warnings.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
