### PR TITLE
fix typos in HLT validation directories

### PR DESCRIPTION
**Pull request by mtosi**
by mistake (they were typos)
few DQM directories under HLT were misspelled

this PR fixes the following
HLT/EG/Tracking --> HLT/EGM/Tracking
HLT/RecHits --> HLT/HCAL/RecHits

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
Are these typos a sin of monitoring that is not used much (since February in the one case I checked)?

**Comment by mtosi** [comment]
I'm trying to have a "clean" HLT directory ..

**Comment by davidlange6** [comment]
hi @mtosi - i don't understand your comment? Is this a typo fix or just a renaming to make things consistent?

**Comment by mtosi** [comment]
the second, which is actually curing a typo made at the beginning ...

**Comment by davidlange6** [comment]
merge

**Pull request merged**
