### PR TITLE
port EDM2ME to consumes

### PR DESCRIPTION
**Pull request by deguio**
thanks @makortel 
I re-used your implementation and tested it. it seems to work fine.
the commit didn't merge anymore so I had to squash and edit and use the hammer.

cheers,
F.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
the error seems related to a cmsDriver problem. the following customize
customiseFor10234
is not found.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
I tested a couple of WF locally and it seems to work fine.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
