### PR TITLE
Make L1Trigger/CSCTriggerPrimitives comply with new CMSSW style rules.

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Make L1Trigger/CSCTriggerPrimitives comply with new CMSSW style rules. There should be no change in performance.

#### PR validation:

Code compiles. Analyzers in plugins/ can again be run with configurations in test/

@tahuang1991

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by dildick** [comment]
@fabiocos This is a similar PR as #26203

**Comment by fabiocos** [comment]
@rekovic could you please check? It looks ok to me, essentially a technical move

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
