### PR TITLE
Integrate HLT menu up to  /dev/CMSSW_7_3_0/HLT/V97

### PR DESCRIPTION
**Pull request by perrotta**
... and further include paths from a few more jira tickets in the GRun menu

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by degano** [comment]
@perrotta this PR can't be merged. Please rebase.

**Comment by perrotta** [comment]
+1
Rebased

**Comment by perrotta** [comment]
please test

**Pull request merged**
