### PR TITLE
Made function static const in SiPixelDetInfoFileReader

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by arunhep** [comment]
@Dr15Jones with only little change in this PR, do we expect changes in these distributions?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-11-2300+18336/19418/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1_Tracks_PXForward_HalfCylinder_mI_PXRing_2_PXDisk_-1.html

its everywhere in PixelPhase1 directory.

**Comment by Dr15Jones** [comment]
It is not possible for this change to affect any algorithm. Do we know if the results being compared use the same random numbers or same pile up?

**Comment by arunhep** [comment]
i dont find any other change in any directory, events should be same. may be @slava77 @perrotta can help? 
even the changes are not visible in every layer or ring. for example here in barrel layer 4 we see changes but not in other three layers 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-11-2300+18336/19418/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1_Tracks_PXBarrel_Shell_pO_PXLayer_4.html

**Comment by Dr15Jones** [comment]
@slava77 @perrotta ping

**Comment by perrotta** [comment]
@arunhep @Dr15Jones 

What I notice is that in https://github.com/cms-sw/cmssw/pull/18336#issuecomment-293701281 it is said that

"The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic:
...
44bc494
..."

And https://github.com/cms-sw/cmssw/commit/44bc494fdb63b59d33032d610f812290f0be4534 is the merge commit for #18278. If you look at the jenkins tests for that PR you can notice the very same features observed here. Therefore, I can imagine that those phase 1 SiPixel plots had been emptied by #18278, and not by this PR (I would be surprised to observe any such consequence because of the changes applied here, indeed). 

Whether these observed modifications in the DQM outputs are correct or not should have had been discussed in #18278: I don't see why it should be as such given the description of that PR, but I did not investigate ...

**Comment by arunhep** [comment]
+1

**Pull request merged**
