### PR TITLE
EMTF 2017 PR #1 - Renamed DataFormats

### PR DESCRIPTION
**Pull request by abrinke1**
Part 1 of set of PRs replacing PR #19451 

Renaming EMTF internal data formats to "2016", in preparation for adding in modified 2017 data formats.  Need to temporarily have both at the same time, so some old and some new EMTF modules (in the intermediate PRs) can run at the same time.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
we'll start with pr 2 of this set...

**Pull request closed without merging**
