### PR TITLE
Ad-hoc fix of Relvals TaskName more than 50 characters

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:

This PR aims to fix the restriction of TaskName added by WMCore in (https://github.com/dmwm/WMCore/commit/e15eee0763e86eadc5f38423d01f3542dbf0f6b6) for RelVals injection. Mainly due to GEN fragment convention. The solution is to check if the TaskName is greater than 50 characters and

- rename TaskName and InputTask to "GenSimFull" or "HadronizerFull"

#### PR validation:

Local test is done with one of the longest TaskName "DisplacedSUSY_stopToBottom_M_300_1000mm_TuneCUETP8M1_13TeV_pythia8_2018_GenSimFull"

`runTheMatrix.py --what upgrade -l 10884.0`

https://cmsweb.cern.ch/reqmgr2/fetch?rid=request-chayanit_RVCMSSW_11_0_0_pre5DisplacedSUSY_stopToBottom_M_300_1000mm_13_190820_164120_6223

The TaskName and InputTask is reduced to GenSimFull for this case

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by fabiocos** [comment]
@chayanit could you please list the resulting changes in the relval names?

**Comment by chayanit** [comment]
> @chayanit could you please list the resulting changes in the relval names?

@fabiocos , after checking with upgrade workflows, I decided to reduce the TaskName (>50) to 
"GenSim" for GenSim step and "Hadronizer" for hadronization step for example,
ADDMonoJet_13TeV_d3MD3_TuneCUETP8M1_2018_GenSimFull -> GenSim
Hadronizer_TuneCP5_13TeV_aMCatNLO_FXFX_5f_max2j_max1p_LHE_pythia8_evtgen -> Hadronizer

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Comment by Dr15Jones** [comment]
This appears to have a python 3 problem:
```
/cvmfs/cms-ib.cern.ch/nweek-02590/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-08-23-1100/external/slc7_amd64_gcc700/bin/python3 -m compileall -q src/GeneratorInterface/CosmicMuonGenerator/python
*** Error compiling 'src/Configuration/PyReleaseValidation/python/MatrixInjector.py'...
Sorry: TabError: inconsistent use of tabs and spaces in indentation (MatrixInjector.py, line 453)
```

**Comment by Dr15Jones** [comment]
fixed with #27859

**Pull request merged**
