### PR TITLE
[102X] Change GT. Update offline GTs. Add 2018 Peak Cosmic Queue.

### PR DESCRIPTION
**Pull request by lpernie**
# Offline Data
102X_dataRun2_v6 is identical to the validated GT for the 2018 ReReco
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_v4/102X_dataRun2_v6

# Offline Data Relval
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_relval_v6/102X_dataRun2_relval_v7

# Updated DECO 2018 Cosmic Queue
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v12/102X_upgrade2018cosmics_realistic_deco_v13

# Added PEAK 2018 Cosmic Queue
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v13/102X_upgrade2018cosmics_realistic_peak_v1

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
test workflow 1010.0

**Comment by lpernie** [comment]
test workflow 1010.0

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie the MC GT changes, this could impact the ongoing production. Which are the changes?

**Comment by lpernie** [comment]
Dear @fabiocos ,
I assume you are referring to the 2018 MC GTs:
The GT v15 is the one used for the new campaign (Autumn18 with new ECAL conditions), so no change in the ongoing MC production is expected. This PR actually make autocond in sync with conditions used by PdmV.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
