### PR TITLE
Bring L1T up-to-date with l1t-tsg-v5-cand

### PR DESCRIPTION
**Pull request by mulhearn**
We are waiting on performance results before declaring tag l1t-tsg-v5.  This PR makes the small changes needed to bring the L1T system configuration in sync with l1t-tsg-v5-cand, which is very likely to be l1t-tsg-v5.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by rekovic** [comment]
Performance results feedbacks show no problems for Calo L1T algorithms.
This is good enough to make a new tag l1t-tsg-v5 equivalent to l1t-tsg-v5-cand.  
Fixes for issues in Muon (EMTF) emulation will come in one of next tags.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
