### PR TITLE
<Backport of #19178> Prompt DQM for HLT Jet Trigger 92X 

### PR DESCRIPTION
**Pull request by physicist87**
This is back port of #19178.

Prompt DQM for HLT Jet Trigger.

### CODE REVIEW

**Comment by mtosi** [comment]
please, update the title and add in brackets the comment on the backport

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by physicist87** [comment]
@mtosi How do I add back port tag in the title ?

**Comment by mtosi** [comment]
please, update the tilte

**Comment by physicist87** [comment]
how long does it take to finish comparison job ? 
Is there some problem ?

**Comment by physicist87** [comment]
@mtosi Do you know why the status of this pr is still under the waiting comparison job ?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
