### PR TITLE
Added support of Authorization for Tag access

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Adding the ability to protect the DB-access on Tag:
-  for IOV updating. 
-  for concurrent update (lock)

The support of the new feature will be connected with a new version of the DB key certificate. 
No change is expected in the access of existing, not upgraded databases (central CMS servers or sqlite files ) . Also, the sqlite files produced with this change are fully forward compatible.

#### PR validation:

unit tests and integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by yuanchao** [comment]
+1

* updates on DB access
* WF tests and unit tests all passed
* Static build warnings are not part of the modification

**Comment by qliphy** [comment]
+1

**Pull request merged**
