### PR TITLE
[GCC 8][CondFormats] Fix buld error

### PR DESCRIPTION
**Pull request by mrodozov**
Fixes compiler complain listed here: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc810/CMSSW_10_2_X_2018-05-22-2300/CondFormats/Serialization

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi can you please review this.

**Comment by ggovi** [comment]
+1

**Pull request merged**
