### PR TITLE
EGM IDs for MiniAOD Reprocessing (75X)

### PR DESCRIPTION
**Pull request by lgray**
Forward port of #10598.

Depends on #10557.

Now includes backport of: #10873

Weight files are absent from this PR.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

ib with proper externals is now ready.

**Comment by lgray** [comment]
ping

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

Also DAS errors.

**Comment by slava77** [comment]
for https://github.com/cms-sw/cmssw/pull/10599	e597659
- backport is complete: all changes signed off in https://github.com/cms-sw/cmssw/pull/10619	6b8b134
(+ those from #10618) are in this PR; checked by cherry-picking commits from 10618+10619 with this PR
- ... the md5 hashes are probably not applicable to 75X: whatever managed through the DAS storm has warnings like this in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10599/7209/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT/step3_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT.log
```
ID: cutBasedElectronID-PHYS14-PU20bx25-V2-standalone-loose
The expected md5: fce6cef3a2c73849c527549af6a0dd86 does not match the md5
calculated by the ID: 0ccc07e6287048b3fccdc4d37d2ceb95 please
update your python configuration or determine the source
of transcription error!
```

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10599	99640de
- md5 hash related warnings are gone (only hash values were reverted since e597659 ; otherwise, the "backport" is consistent with 76X and is as expected (more in https://github.com/cms-sw/cmssw/pull/10599#issuecomment-130894690)
- signing off based on observations in 76X [releases are near-equivalent for this area at this point]

**Comment by lgray** [comment]
@slava77 Also, as far as I can tell the md5 hash issue is related to gcc version.

**Comment by slava77** [comment]
how exciting.
So, in a different build on a different day we will get these errors again.
:(

**Comment by Dr15Jones** [comment]
Are the hash code errors from the ROOT class version? If so, then I think that is an indication of improperly linked DataFormats packages. If the dictionary for a base class is not seen, ROOT will calculate one value for the md5 and if it can see the dictionary it will calculate another. If the package containing a derived class is not linked with the pack containing the base class than the md5 calculated becomes dependent upon the order in which the two packages happen to be loaded (or not loaded) into the checking code.

**Comment by lgray** [comment]
Hi Chris,

This is coming from using openssl to hash a dumped configuration string.

-Lindsey

(Sent from my Nexus 6)

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 Just to make sure you get this one as well. :-)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@davidlange6 reminder that this needs to be merged into 75X (it is in 76X for some time)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10599	c3e4a8f

- updates made since the last sign-off https://github.com/cms-sw/cmssw/pull/10598#issuecomment-131636009 are the same as the ones applied to 76X in https://github.com/cms-sw/cmssw/pull/10873	361837b (confirmed by cherry-picking the #10873) 
- jenkins tests pass to the extent possible with infrastructure issues
- tested locally in CMSSW_7_5_X_2015-08-20-2300 /test area sign579/ with a short matrix and 200 events each from DoubleMuon and DoubleEG in 251721
    - changes are only in MINIAOD-related products
    - matrix & run2 data run comparisons show no differences in monitored quantities (DQM or fwlite reco products comparisons)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@monttj Can you please sign here? Thanks.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@monttj  this one now has tests-approved, in case it was important

**Comment by monttj** [comment]
+1
It was approved already for the other release.

**Comment by davidlange6** [comment]
@lgray - this no longer merges - could you rebase?

**Comment by gpetruc** [comment]
I think Lindsey is away for at least a week, maybe somebody else can try rebasing or fixing the conflict. Maybe @ikrav ? (I can look if it's a trivial conflict or it really requires e/gamma to solve it)

**Comment by gpetruc** [comment]
The merge conflict is at the end of  RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py
( https://github.com/cms-sw/cmssw/pull/10599/files#diff-547ae967e410c72833b1da9af0345aa5 ) , which was modified also in #10690 and it is trivial.

Incidentally, I don't see why we need to recompute sigma(ieta ieta) and e5x5 for photons given that to my knowledge they're fixed in reco since `CMSSW_7_2_1`.

**Comment by ikrav** [comment]
Hi Giovanni,

   Usually Lindsey handles this, besides he somehow sets up what of VID
stuff goes into miniAOD.

  Regarding sigma_ieta_ieta and e5x5: these are needed by photon MVA. The photon MVA
uses a many different shower shapes, including these ones. All those other shapes
(such as sigmaIEtaIPhi, and misc sub-e5x5 shapes) are not available from the standard
photon object, so they are computed by a producer. Historically we had e5x5 and sigma_ieta_ieta
computed along with everything else. Now these variables are fixed, but we have
not changed the code (I was not aware that there is a good reason to do that).

   Sorry, I am not totally fluent with github. What exactly is the conflict? It is
in the egammaObjectModificationsInMiniAOD_cff.py, right? What exactly are
the lines? Is it the lines 4 and 7-8?

Thanks,
Ilya

**Comment by gpetruc** [comment]
Hi Ilya,

This PR is changing the last line of the file, replacing 
````
pho_spring15_nt.mvaSpring15NonTrigClassName
```` 
with 
````
pho_spring15_50_nt.mvaSpring15NonTrigClassName+pho_spring15_50_nt.mvaTag
``` 
but in the meantime the other pull request changed the end of the file to add the regression, and Git doesn't know what to do.

I don't know what's the best recipe on how to do the rebase of a PR, probably others can give better advice, I'll refrain from giving mine. Anyway, FWIW I did a rebase of this on top of the current `CMSSW_7_5_X branch` in https://github.com/cms-sw/cmssw/compare/CMSSW_7_5_X...gpetruc:pr_10599_rebased if @davidlange6 needs to get this integrated urgently.

Giovanni

**Comment by lgray** [comment]
@gpetruc keep the inclusion of the regressions and the version of the IDs where the 'mvaTag' is used.

**Comment by gpetruc** [comment]
I only modified the conflict that git was finding (and i think in the right direction), if there's more to change it's up to you - i'm gone as well now

**Comment by lgray** [comment]
Nah, that's all. Thanks!

(Sent from my Nexus 6)

**Comment by ikrav** [comment]
Giovanni, unfortunately I would say we wait for Lindsey unless someone else
has a better idea. I am not sure how these strings should be (and usually
need a lot of handholding for rebasing anything).

Regards,
Ilya

**Comment by lgray** [comment]
@ikrav I double checked giovanni's branch and the changes are fine (by eye
and memory) it would be useful if you could run tests on @gpetruc's branch.
@slava77 can show you how. Likewise if you want to validate further please
go ahead.

@slava77 @davidlange6 Please use giovanni's branch if time runs out before
I get back.

**Comment by arizzi** [comment]
@lgray beside the conflicts that emerged and should be fixed, is this still consistent  with what merged in 74X via @gpetruc branch? 
(this is one of the PR that is missing in 75X wrt 74X for miniaod)

**Comment by lgray** [comment]
@arizzi yes no changes have been made and they have not diverged since I am
in Japan without a laptop (and am for another week).

@gpetruc has kindly provided a rebased version already with the conflict
fixed.

(Sent from my Nexus 6)

**Comment by arizzi** [comment]
so should we just close this (if so please do it) and open a new PR from
CMSSW_7_5_X...gpetruc:pr_10599_rebased (if you confirm I can open the PR) ?

**Comment by lgray** [comment]
Yes please open the rebased PR, @ me and reference this PR.

(Sent from my Nexus 6)

**Comment by arizzi** [comment]
this can be closed in favour of #11118

**Pull request closed without merging**
