### PR TITLE
CSC TP bugfixes for high PU running

### PR DESCRIPTION
**Pull request by dildick**
Last week Stefan Piperov reported that the PU-samples with the D12 geometry crash with an error rate of 85% in the DIGI step with error
<PRE>
cmsRun1
Fatal Exception (Exit Code: 8001)
An exception of category 'InvalidDetId' occurred while
   [0] Processing  Event run: 1 lumi: 181 event: 9005 stream: 0
   [1] Running path 'L1simulation_step'
   [2] Calling method for module 
CSCTriggerPrimitivesProducer/'simCscTriggerPrimitiveDigis'
Exception Message:
GEMDetId ctor: det: 0 subdet: 0 is not a valid GEM id
</PRE>

After investigation it was found that the pad DetIds sometimes get corrupted. I put in place a few checks to ensure that the constructor is not called when the DetId is not a GEMDetId. 

This update needs to be included in 91X and 92X.

@calabria

### CODE REVIEW

**Comment by calabria** [comment]
@kpedro88 FYI
@dildick please send the same to 91X

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@dildick What does this mean for the events that did not crash?  Was the DetID properly set?

**Comment by dildick** [comment]
I believe so. I have not yet found the root cause of the corruption. But this prevents the run functions in the CSC-GEM Motherboards from crashing unnecessarily.

**Comment by kpedro88** [comment]
@dildick please reduce the number of messages printed; this PR added 1000+ lines to the log for 2023D8 step3, all like this:
```
%MSG-e GEMCoPadDigiValidation:  GEMCoPadDigiValidation:gemCoPadValidation  15-May-2017 22:11:02 CEST Run: 1 Event: 3
 Re 1 Ri 1 St 2 La 0 Ch 3 Ro 4  : This part can not load from GEMGeometry // Original Re 1 Ri 1 St 2 La 0 Ch 3 Ro 0  station : 2
%MSG
```

**Comment by dildick** [comment]
@kpedro88 The issue originates here: https://github.com/cms-sw/cmssw/blob/df5afe9fb3195e45552ae28d5e5778090071f32d/Validation/MuonGEMDigis/src/GEMCoPadDigiValidation.cc#L121-L129. I'll provide a fix later today.

**Comment by dildick** [comment]
This should address the issue.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Pull request merged**
