### PR TITLE
FastSim : HF : Shower Library: safe handling of pointers

### PR DESCRIPTION
**Pull request by lveldere**
- use smart pointers to:
  - remove memory leak in beginRun()
  - get rid of unsafe pointer handling in destructor
- this is a bugfix: I will backport to 74X as soon as tests succeed

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@Vlandr57 FYI

**Comment by lveldere** [comment]
please test

**Comment by davidlt** [comment]
I was having the same issue recently because a single package was not built. The problem was that `hfshower` is not initialized to `nullptr` and `FastHFShowerLibrary` is allocated in heap (thus contained garbage pointer). Pointer is initialized by a call to `FastHFShowerLibrary::initHFShowerLibrary`, which is called in `beginRun`.

The actual problem is in FWCore. Exception is triggered in `ModuleRegistry` or `Schedule` ctor, because PluginManager was not able to find the broken package. In C++ this automatically triggered auto-destruct. The run-time must make sure that the object should be like it was never constructed. Because pointer was not initialized (we haven't started running), dtor got non valid pointer to free, thus segfault.

Framework refactor the code to avoid exception in ctors.

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
