### PR TITLE
Phase2-hgx293A Extend the possibility of new cells needed for rotated full wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend the possibility of new cells needed for rotated full wafers (in place of #35864)

#### PR validation:

Use cfg's in Geometry/HGCalCommonData/test/python and also use the runTheMatrix test workflow

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@AdrianoDee, @srimanob Can you check & sign now

**Comment by bsunanda** [comment]
@AdrianoDee, @srimanob ping

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
