### PR TITLE
Renamed likely macro to avoid name collision

### PR DESCRIPTION
**Pull request by Dr15Jones**
The likely and unlikely macros were renamed to LIKELY and
UNLIKELY to avoid name collisions with a function in boost.
Using all capital letters is the C family standard for naming
macros so best to follow convention.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
In the DEVEL builds, we are testing boost 1.67 . These tests showed conflicts such as

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_DEVEL_X_2018-05-23-2300/CommonTools/Utils

```
  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/5ae405a053c0e18d060915cde2b0f108/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_DEVEL_X_2018-05-23-2300/src/FWCore/Utilities/interface/Likely.h:14:40: error: expected identifier before 'true'
  #define likely(x) (__builtin_expect(x, true))
                                        ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.67.0/include/boost/date_time/special_values_parser.hpp:105:17: note: in expansion of macro 'likely'
     static bool likely(const string_type& str)
                 ^
  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/5ae405a053c0e18d060915cde2b0f108/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_DEVEL_X_2018-05-23-2300/src/FWCore/Utilities/interface/Likely.h:14:40: error: expected ',' or '...' before 'true'
  #define likely(x) (__builtin_expect(x, true))
                                        ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.67.0/include/boost/date_time/special_values_parser.hpp:105:17: note: in expansion of macro 'likely'
     static bool likely(const string_type& str)
                 ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.67.0/include/boost/date_time/time_parsing.hpp: In function 'time_type boost::date_time::parse_iso_time(const string&, char)':
  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/5ae405a053c0e18d060915cde2b0f108/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_DEVEL_X_2018-05-23-2300/src/FWCore/Utilities/interface/Likely.h:14:19: error: expected unqualified-id before '(' token
  #define likely(x) (__builtin_expect(x, true))
                   ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.67.0/include/boost/date_time/time_parsing.hpp:312:19: note: in expansion of macro 'likely'
     if (svp_type::likely(s)) {
                   ^
  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/5ae405a053c0e18d060915cde2b0f108/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_DEVEL_X_2018-05-23-2300/src/FWCore/Utilities/interface/Likely.h:14:44: error: cannot convert 'const string {aka const std::__cxx11::basic_string<char>}' to 'long int' for argument '1' to 'long int __builtin_expect(long int, long int)'
  #define likely(x) (__builtin_expect(x, true))
                                            ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/slc6_amd64_gcc630/external/boost/1.67.0/include/boost/date_time/time_parsing.hpp:312:19: note: in expansion of macro 'likely'
     if (svp_type::likely(s)) {
                   ^
```

macros are dangerous because they are text replacers without the concept of a scope. The best one can do is to use naming conventions to try to avoid naming collisions.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
please test
(just to clean up comparisons)

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by mommsen** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , can we merge this? It is just a technical update.

**Comment by fabiocos** [comment]
@ggovi @lpernie @arunhep the changes look purely technical and do not affect the output. I merge this code, please comment in case you see issues

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
