### PR TITLE
L1 muon DQM CMSSW_8_0_23 81x synched

### PR DESCRIPTION
**Pull request by thomreis**
This is the same as PR #16511 except for the last commit there (https://github.com/cms-sw/cmssw/pull/16511/commits/825dbe69b1c3c8c7614de2cce46a227143a4198a) that was removed to be in sync with what is already merged in 81X.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Backport of:
https://github.com/cms-sw/cmssw/pull/15387 and https://github.com/cms-sw/cmssw/pull/16098

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
hi @thomreis - could you rebase this on top of 80x now that the plugin->src pr is in. Thanks

**Comment by thomreis** [comment]
I rebased it locally but now git complains when I want to push it to my-cmssw.
```
To git@github.com:thomreis/cmssw.git
 ! [rejected]        l1Muon-DQM_CMSSW_8_0_23_81Xsynched -> l1Muon-DQM_CMSSW_8_0_23_81Xsynched (non-fast-forward)
error: failed to push some refs to 'git@github.com:thomreis/cmssw.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
What to do in this situation?

**Comment by davidlange6** [comment]
some of the solutions at 
http://stackoverflow.com/questions/10298291/cannot-push-to-github-keeps-saying-need-merge
may be of help depending on the status of your repo

**Comment by davidlange6** [comment]
not everything needs to be signed again by everyone.

**Comment by rekovic** [comment]
please test

**Comment by davidlange6** [comment]
so if I've understood correctly, this PR is essentially a back port of #16098 - however it misses some of the commits in that PR (thus suggesting there is more to come to get things working. Any way to add the missing commits (looks like there are ~3 scattered through the history)?

**Comment by thomreis** [comment]
One missing commit is from a merge that adds only a comment.
The other one is a change from auto_ptr to unique_ptr to make the code compile in 81X. This was not needed in 80X.
And the third one is indeed a commit I missed while cherry picking.

**Comment by thomreis** [comment]
I have added the three missing commits.

**Comment by davidlange6** [comment]
i think you don't want to add the auto_ptr commit

**Comment by thomreis** [comment]
I have tested also with the auto_ptr commit now and see no problems. For what reason would you omit it?

**Comment by davidlange6** [comment]
other places have had problems with it. but if your tests say it works for you, then it can be ok.

**Comment by dmitrijus** [comment]
auto_ptr got upgraded into unique_ptrs in 81x, but a lot of places still use auto_ptr in 80x.
As long as 81x uses unique_ptrs, I'm fine with both in 80x :)

**Comment by thomreis** [comment]
OK, I keep unique_ptr then since it is already there now and works fine.

**Comment by dmitrijus** [comment]
Also, can you make a pull request to 81x to fix the emulator crash?
Then after it gets merged, you can just append it to this PR (if it is not merged yet), or create a new one to get it into 80x.

**Comment by thomreis** [comment]
Already done: #16512  
This fixes the EMTF emulator ProductNotFound error.
The uGT crash is something else that the uGT people are looking at.

**Comment by thomreis** [comment]
I will add the commit https://github.com/cms-sw/cmssw/pull/16512/commits/34128ec91b32034f1eac6a699f2bcc7a29cd9924 with the bugfix for the emulator configuration as well since #16512 is now merged in 81X.

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
