### PR TITLE
bsunanda:Run2-hgx30 Try to add the reconstruction geometry and topology for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
This is based on the IB CMSSW_7_6_X_2015-07-22-2300 and is on the top of PR 10268 which should have merged by now. This provides most of the material for reconstruction geometry and topology code for HGCal. The missing part are the test codes which will be integrated later

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - please rebase.

**Comment by bsunanda** [comment]
Rebased it against CMSSW_7_6_X_2015-07-29-2300
________________________________

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild - it's unrelated DAS error:

```
There was a problem while querying DAS with query 'file dataset=/RelValTTbar_13/CMSSW_7_2_0_pre1-PU50ns_POSTLS172_V2-v2/GEN-SIM-RECO | grep file.name'. Server reply was:
 {'status': 'fail', 'reason': 'client timeout after 302 sec'}
----- Begin Fatal Exception 03-Aug-2015 13:22:02 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_7_6_X_2015-08-02-2300/src/RecoMET/METProducers/test/recoMET_tcMet_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.SystemExit'>
1
----- End Fatal Exception -------------------------------------------------
Failure using recoMET_tcMet_cfg.py: status 90
status = 23040

---> test testRecoMETMETProducers had ERRORS

```

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Both failures are due to DAS queries which have nothing to do with this PR. It is a pity to have such a fragile thing in the test path
________________________________

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
