### PR TITLE
ECAL - Implement follow up issues for Phase 2 GPU reconstruction

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR addresses the first two items in #38619. The `edm::ExternalWork` is removed from modules that do not need it and the kernel is modified to be able t run with any number of threads and blocks.
The PR also adds new matrix workflows for Phase 2 ECAL developments with GPUs (*.612). The existing *.61 workflows remain CPU only.

No changes to the output are expected.

#### PR validation:

No changes observed.
Tested also with WF 28234.61 by manually adding the gpu modifier to the reconstruction step of the WF.
Passes 32234.61 and the new 32234.612.

### CODE REVIEW

**Comment by srimanob** [comment]
enable gpu

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
assign heterogeneous

(kindly asking the experts to take a look)

**Comment by thomreis** [comment]
I do not know where the difference in the GPU TriggerResults for 11634.512 HLT could come from. This PR only touches Phase 2 code, whereas 11634.512 is a Run 3 WF.

**Comment by mandrenguyen** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Is it possible to run 39434.612 in GPU using test parameters? 
@smuzaffar Thanks.

Normally, we can do
```
test parameters:
- workflows = 39434.612
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix
```
but this may not end up in GPU test.

**Comment by smuzaffar** [comment]
@srimanob , for  gpu test you need to use 
```
test parameters:
- workflows_gpu = 39434.612
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix
```

see the bot [command link](http://cms-sw.github.io/cms-bot-cmssw-cmds.html) available at https://github.com/cms-sw/cmssw/pull/39195#issuecomment-1227494331

**Comment by srimanob** [comment]
test parameters:
- workflows = 32234.61,32234.612
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

Thanks @smuzaffar

**Comment by smuzaffar** [comment]
@srimanob , I think you are missing `workflows_gpu` test parameter

**Comment by srimanob** [comment]
@cmsbuild please abort

**Comment by srimanob** [comment]
test parameters:
- workflows_gpu = 32234.61,32234.612
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
+heterogeneous

lgtm

**Comment by jpata** [comment]
+reconstruction
- technical cleanup

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by thomreis** [comment]
@cms-sw/pdmv-l2 do you have any comments on this?

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
please test 
(tests are 11 days old nowadays)

**Comment by perrotta** [comment]
+1

**Pull request merged**
