### PR TITLE
Make Pythia8 Photon Flux more configurable.

### PR DESCRIPTION
**Pull request by hjbossi**
#### PR description:

Changes made to make the Pythia8 photon flux more configurable. 

#### PR validation:

This PR is a backport of https://github.com/cms-sw/cmssw/pull/44549 meant for the next release cycle.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 180,181

**Comment by mandrenguyen** [comment]
please test
I forgot that 180,181 didn't exist yet in 13_0_X.
Let's see if the `test parameters` flag reset the extra workflows correctly.

**Comment by hjbossi** [comment]
Can someone merge this backport as all tests were successful?

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44549

**Comment by mandrenguyen** [comment]
@cms-sw/generators-l2 Please review this backport when you find a moment.

**Comment by bbilin** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
