### PR TITLE
First integration of Pixel Alignment of large structures in PCL (75X)

### PR DESCRIPTION
**Pull request by cerminar**
This PR integrates the alignment of the pixel large structures as a
new PCL workflow for Tier0.
There is no code change to any production workflow, only the alca
configurations are affected by the changes.

The new workflow has been integrated in the relval 1001 (which now has
one more step).

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by cerminar** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by boudoul** [comment]
+1

**Comment by ggovi** [comment]
+1

**Pull request merged**
