### PR TITLE
HLT menu development for `12_4_X` (8/N): HLT V1.4 of 2022 [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #39419

#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This version of the `GRun` HLT menu corresponds to "HLT V1.4" for 2022 pp data-taking.

This PR is not an exact backport. In addition to #39419, the `HLT:@relval2022` keyword is changed from `HLT:GRun` to `HLT:2022v14`, to use the frozen HLT-V1.4 menu from now on in `12_5_X` RelVals, ahead of the release of `CMSSW_12_5_0`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2461](https://its.cern.ch/jira/browse/CMSHLT-2461): [TSG] trigger for GPU-vs-CPU differences in `AlCa_PFJet40`
  - [CMSHLT-2352](https://its.cern.ch/jira/browse/CMSHLT-2352): [EXO] update of signal and control triggers for delayed-jet searches
  - [CMSHLT-2448](https://its.cern.ch/jira/browse/CMSHLT-2448): [TAU] tighten DeepTau wp for ditau triggers
  - [CMSHLT-2472](https://its.cern.ch/jira/browse/CMSHLT-2472): [TAU] re-add TAU backup triggers to GRun with PS=0
  - [CMSHLT-2468](https://its.cern.ch/jira/browse/CMSHLT-2468): [TSG] add `OnlyMuons` PS column
  - [CMSHLT-2467](https://its.cern.ch/jira/browse/CMSHLT-2467): [BPH] new lumi-based PS columns for BPH Parking
  - [CMSHLT-2454](https://its.cern.ch/jira/browse/CMSHLT-2454): [ECAL] run CPU ECAL unpacker on GPU to provide auxiliary collections
  - [CMSHLT-2445](https://its.cern.ch/jira/browse/CMSHLT-2445): [EXO] disable `HLT_HT430_DisplacedDijet30_Inclusive1PtrkShortSig5`
  - [CMSHLT-2469](https://its.cern.ch/jira/browse/CMSHLT-2469): [EXO] fix to inclusive delayed-jet triggers
  - [CMSHLT-2465](https://its.cern.ch/jira/browse/CMSHLT-2465): [MUO-DPGs] increase rate of muon triggers in Express PD
  - [CMSHLT-2466](https://its.cern.ch/jira/browse/CMSHLT-2466): [TAU] add `L1_DoubleIsoTau35er2p1` to relevant L1T seeds
  - [CMSHLT-2455](https://its.cern.ch/jira/browse/CMSHLT-2455): [PFlow] set maxIterations=5 in HBHE-PFClustering
  - [CMSHLT-2453](https://its.cern.ch/jira/browse/CMSHLT-2453): [EXO] fix to thresholds of DTCluster-based triggers
  - [CMSHLT-2463](https://its.cern.ch/jira/browse/CMSHLT-2463): [MUO] set PS=2 for `HLT_Mu15`
  - [CMSHLT-2464](https://its.cern.ch/jira/browse/CMSHLT-2464): [TRK] added RAW of OnlineMetaData to EventContent of DQMOnlineBeamSpot
  - [CMSHLT-2456](https://its.cern.ch/jira/browse/CMSHLT-2456): [TSG] remove unnecessary process-names in `InputTag`s
  - [CMSHLT-2410](https://its.cern.ch/jira/browse/CMSHLT-2410): [EXO] enable `DiPhoton10Time1p2ns` trigger
  - [CMSHLT-2457](https://its.cern.ch/jira/browse/CMSHLT-2457): [B2G] remove `BoostedDoubleB` triggers from `GRun`
  - [CMSHLT-2447](https://its.cern.ch/jira/browse/CMSHLT-2447): [JME] Add `DiPFJetAve260_HFJEC` trigger
  - [CMSHLT-2450](https://its.cern.ch/jira/browse/CMSHLT-2450): [JME] Add uncorrected version of jets to the EventContent of the `ALCALowPtJet` stream
  - [CMSHLT-2449](https://its.cern.ch/jira/browse/CMSHLT-2449): [DAQ,MUO] update of MessageLogger module to suppress known MUO-related warnings

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39419

Development of HLT menus for 2022 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - differences in outputs of PR tests are in line with changes to the HLT GRun menu

**Comment by perrotta** [comment]
+1

**Pull request merged**
