### PR TITLE
add tool to have single module occupancy trends

### PR DESCRIPTION
**Pull request by fioriNTU**
Add tool for offline shifter in a way to have trends vs run number of single module occupancy

### CODE REVIEW

**Comment by venturia** [comment]
check with @suchandradutta if you are not doing the same thing

**Comment by fioriNTU** [comment]
@venturia part of the code is from Suchandra, I added the script and the trend code, she modified the old single module occupancy code

**Comment by venturia** [comment]
OK thanks!

On 26 Oct 2016, at 10:31 , fioriNTU <notifications@github.com<mailto:notifications@github.com>> wrote:


@venturia<https://github.com/venturia> part of the code is from Suchandra, I added the script and the trend code, she modified the old single module occupancy code

**Comment by dmitrijus** [comment]
+1

**Comment by smuzaffar** [comment]
please test
there was an issue with local siteconf which should be fixed now

**Comment by davidlange6** [comment]
+1

**Pull request merged**
