### PR TITLE
BTagCalibration: Added protection against -ve eta values for SFs calculated on abs(eta) [102X]

### PR DESCRIPTION
**Pull request by mondalspandan**
Backport of #26248

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by peruzzim** [comment]
assign xpog

this is going to change the nanoaod for the ongoing campaigns, will discuss with authors what to do

**Comment by ggovi** [comment]
+1

**Comment by peruzzim** [comment]
Indeed the variable currently filled in the code is buggy, as shown by the comparison plot (unphysical peak at 1). I guess the fix could be merged, as the variable is anyways unusable in the ongoing production.

**Comment by peruzzim** [comment]
hold

as discussed during the ORP meeting, I propose to hold this until the next nanoAOD production with increased version number (v5) that should not be far away in time

**Comment by peruzzim** [comment]
unhold

as discussed in the last ORP meeting, we are breaking the nanoAOD output consistency with #26769

**Comment by peruzzim** [comment]
please test

re-testing just to verify that everything is ok, and nothing changes outside of nanoAOD (the previous test products have disappeared)

**Comment by peruzzim** [comment]
+xpog

**Comment by fabiocos** [comment]
+1

**Pull request merged**
