### PR TITLE
Move GEM offline DQM files from DQMOffline/Muon to DQM/GEM

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
- This PR moves GEM offline DQM files from `DQMOffline/Muon` to `DQM/GEM` for better packaging.
- In addition, this PR removes `GEMOfflineMonitor` because it has been replaced by `GEMDigiSource` and `GEMRecHitSource` since CMSSW_12_0_0_pre6.

#### PR validation:
Tested with the following wf:
- 11650.0: pp / Run3 / ZMM
- 35050.0: pp / Phase2 / ZMM
- 11654.0: cosmics / Run3 / CosmicsSPLoose
- 35054.0: cosmics / Phase2 / CosmicsSPLoose

It requires some modification to run the workflow with cosmics scenario option. See more details on the last page of [this slide](https://indico.cern.ch/event/1105924/contributions/4652889/attachments/2368910/4045552/220104__GEM_DPG__Moving_GEM_Offline_DQM.pdf).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
N/A

### CODE REVIEW

**Comment by seungjin-yang** [comment]
@jshlee @quark2

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
test parameters

- workflows = 11654.0

**Comment by jfernan2** [comment]
please test

**Comment by seungjin-yang** [comment]
Hi @jfernan2,
I checked [console output](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/14463/console) and the error was probably because 11654.0 is in the upgrade set (`-w upgrade`).

**Comment by jfernan2** [comment]
Thanks @seungjin-yang 
I tried to run it here since I thought some modification was needed but I realized now it is not

**Comment by jfernan2** [comment]
test parameters:
- workflows = 35054.0
- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
test parameters:

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
