### PR TITLE
Backport PR #23578 to 10_1_X [Add code/configs for monitoring the new HLT_Photon35_TwoProngs35_v* paths]]

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by covarell** [comment]
As asked by HIG trigger contacts

**Comment by jfernan2** [comment]
please test

**Comment by covarell** [comment]
Any news about merging this? Thanks

**Comment by boudoul** [comment]
PLease  @covarell , make an explicit title , otherwise we can't easily guess form the title what you are backporting

**Comment by fabiocos** [comment]
+1

not giving problems in CMSSW_10_2_0_pre6

**Pull request merged**
