### PR TITLE
93X version of #PR19762: Change to include HLT Muon filtering on DT DQM Online

### PR DESCRIPTION
**Pull request by jfernan2**
Expected change: reduction of events considered on DT DQM Online, only events which fired HLTMu paths hence less background/noise in plots

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
It seems the crash was due to a corrupted input file, not by the PR itself...
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19767/21517/runTheMatrix-results/1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM/step2_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM.log

@dmitrijus could you trigger the test again please?

**Comment by dmitrijus** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
