### PR TITLE
add `hltPrintMenuVersions` and utilities for HLT-menu spreadsheets [`13_2_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #42967
backport of #42976

#### PR description:

From the description of #42967:

>This PR adds a few utilities related to the maintenance of the HLT menus.
>
> - `hltPrintMenuVersions` is a modified version of a script shared by @silviodonato to print to stdout metadata ("save comment" and "release template") of each version of a given HLT menu in ConfDB. I have added some command-line options to it using `argparse` (see `--help` for more info). Some examples below.
>   ```bash
>   hltPrintMenuVersions /dev/CMSSW_13_2_0/Fake2 -c 'cms_hlt_v3_r/convertMe!@cmsr'
>   hltPrintMenuVersions /dev/CMSSW_13_2_0/Fake2 --db run3                        
>   hltPrintMenuVersions /dev/CMSSW_10_0_0/Fake2 --db run2
>   hltPrintMenuVersions /cdaq/special/PilotBeamTest2021/Circulating --db adg                        
>   ```
>
> - Upon the release of a new HLT menu for data-taking (or MC production), TSG produces a spreadsheet which contains information on the content of the menu. The tools used to create this spreadsheet are added in this PR to `HLTrigger/Configuration/scripts/utils` (see the readme file in `scripts/utils` for further details).
>
>Unit tests for `hltPrintMenuVersions` and `hltMenuContentToCSVs` are included. (These new tests rely on connecting to ConfDB, so I fear they might occasionally fail due to connection glitches, based on what I remember from https://github.com/cms-sw/cmssw/issues/37598#issuecomment-1326628334.)

From the description of #42976:

>This PR restricts the execution of the unit test of `hltPrintMenuVersions` (added in #42967) to the `x86-64` architecture, given that the python module `cx_Oracle` is not fully working in CMSSW builds with non-`x86-64` architecture (e.g. Aarch64 and PowerPC).
>
>The implementation is tentatively copied from other unit tests in CMSSW.

#### PR validation:

The new unit tests pass.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42967
#42976

Utilities for HLT-menu development.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/42967

**Comment by mmusich** [comment]
hold 
   * see https://github.com/cms-sw/cmssw/pull/42967#issuecomment-1755516365

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
plase test for el8_aarch64_gcc11

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
+hlt
   * tests pass now in all archs

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
