### PR TITLE
TriggerBxMonitor: monitor the BX accept of L1 and HLT triggers

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
I suspect the errors are unrelated with this pull request, since the new module is not used in any workflow (yet).

**Comment by deguio** [comment]
seems ok to me

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

we don't have any failing add on tests in the ribs - maybe was a glitch

**Pull request merged**
