### PR TITLE
[10_2_X] Make usage of TDC cuts on HF min-bias bits configurable

### PR DESCRIPTION
**Pull request by christopheralanwest**
Backport #24007

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@christopheralanwest @thomreis @rekovic do I understand correctly that this PR is not expected to have an impact on simulation production? It is important to assess it before the official production starts

**Comment by christopheralanwest** [comment]
@fabiocos This PR will not have any impact on simulation production; its primary use is in DQM monitoring used to assure that the TP generation in hardware works exactly as expected. The anomalous hits in HF that the TDC cuts are intended to suppress are not simulated and therefore the TDC cuts are not configured to be used in simulation.

**Comment by fabiocos** [comment]
@christopheralanwest perfect, thank you for the confirmation. As soon as there is a positive green light from 10_3_0_pre1 relvals I will merge it

**Comment by fabiocos** [comment]
+1

**Pull request merged**
