### PR TITLE
DetectorDescription Clang Check modernize-use-equals-delete

### PR DESCRIPTION
**Pull request by ianna**
* DetectorDescription part of @davidlange6's PR https://github.com/cms-sw/cmssw/pull/19655

Note: it should be taken after https://github.com/cms-sw/cmssw/pull/19974

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
The removal error does not seem to be related to this PR:
```
31-Jul-2017 14:12:29 CEST  Initiating request to open file file:step3_inDQM.root
31-Jul-2017 14:12:32 CEST  Successfully opened file file:step3_inDQM.root
%MSG-e DQMGenericClient:  DQMGenericClient:postProcessorTrack@endJob  31-Jul-2017 14:14:47 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackBHadron !!!
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:hltMuonPostNonIso@endJob  31-Jul-2017 14:15:14 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon/Distributions !!!
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:hltMuonPostIso@endJob  31-Jul-2017 14:15:15 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon/Distributions !!!
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:hltMuonPostMain@endJob  31-Jul-2017 14:15:15 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon/Distributions !!!
%MSG
%MSG-w EmDQMPostProcessor:  EmDQMPostProcessor:EgammaPostVal@endJob  31-Jul-2017 14:15:15 CEST PostGlobalEndRun
cannot find directory: HLT/HLTEgammaValidation , skipping
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:postProcessorHLTmuonTracking@endJob  31-Jul-2017 14:15:15 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon.Tracking/ValidationWRTtp !!!
%MSG
%MSG-w JetMETDQMPostProcessor:  JetMETDQMPostProcessor:JetMETPostVal@endJob  31-Jul-2017 14:15:24 CEST PostGlobalEndRun
cannot find directory: HLT/HLTJETMET , skipping
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:hltMuonEfficienciesMR@endJob  31-Jul-2017 14:15:57 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon/MR !!!
%MSG
%MSG-e DQMGenericClient:  HLTMuonRefMethod:hltMuonRefEfficienciesMR@endJob  31-Jul-2017 14:15:58 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon/MR !!!
%MSG
%MSG-e DQMGenericClient:   DQMGenericClient:double_soft_muon_backup_70_metpt_efficiency@endJob  31-Jul-2017 14:16:05 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/SUSY/SOS/backup70/MET !!!
%MSG
%MSG-e DQMGenericClient:   DQMGenericClient:double_soft_muon_backup_90_metpt_efficiency@endJob  31-Jul-2017 14:16:05 CEST PostGlobalEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/SUSY/SOS/backup90/MET !!!
%MSG
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
test with #20033

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
Close until https://github.com/cms-sw/cmssw/pull/20020 is merged.

**Comment by ianna** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- No changes expected, none observed in jenkins tests

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
