### PR TITLE
HLT menu development for `13_0_X` (9/N) [`13_2_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported down to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2705](https://its.cern.ch/jira/browse/CMSHLT-2705): [B2G] update of HT+6Jet+BTag triggers to PNet b-tagger
 - [CMSHLT-2731](https://its.cern.ch/jira/browse/CMSHLT-2731): [JME] updated PSs of `HLT_PFJetFwd60_v` and `HLT_AK8PFJetFwd60_v` triggers
 - [CMSHLT-2789](https://its.cern.ch/jira/browse/CMSHLT-2789): [TSG] re-ordered Paths/EndPaths/FinalPaths in the HLT combined table
 - [CMSHLT-2795](https://its.cern.ch/jira/browse/CMSHLT-2795): [TRK] adjust PSs of `HLT_HT300_Beamspot_v`
 - [CMSHLT-2800](https://its.cern.ch/jira/browse/CMSHLT-2800): [DQM] set PS=25 for `OnlineMonitor` PD and set all its smart-PSs to 1
 - [CMSHLT-2803](https://its.cern.ch/jira/browse/CMSHLT-2803): [DQM] increase upper limit on inst-lumi to 3E34 in `hltLumiMonitor` module (online DQM)
 - [CMSHLT-2807](https://its.cern.ch/jira/browse/CMSHLT-2807): [TSG] split EphemeralPhysics and EphemeralZeroBias datasets and streams (8 PDs and 4 streams each)
 - [CMSHLT-2811](https://its.cern.ch/jira/browse/CMSHLT-2811): [EXO] introduce double-CSC-shower triggers
 - [CMSHLT-2812](https://its.cern.ch/jira/browse/CMSHLT-2812): [EXO,HIG] use 8 split PDs for `ParkingVBF` (4 streams)
 - [CMSHLT-2814](https://its.cern.ch/jira/browse/CMSHLT-2814): [EXO,HIG] set PS=0 for `HLT_VBF_DiPFJet125_45_Mjj720_Detajj3p0*` triggers
 - [CMSHLT-2816](https://its.cern.ch/jira/browse/CMSHLT-2816): [EXO] set PS=0 for looser triggers of `ParkingLLP` dataset
 - [CMSHLT-2825](https://its.cern.ch/jira/browse/CMSHLT-2825): [B2G,HIG] use `hltPFJetForPNetAK8` in EventContent of `HLTMonitor` stream

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_1_X`
`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - Changes in the outputs of PR tests are in line with the updates to the HLT GRun menu.

**Comment by perrotta** [comment]
+1

**Pull request merged**
