### PR TITLE
 integration of the CT-PPS FastSim in CMSSW_8_0_X

### PR DESCRIPTION
**Pull request by sandrofonseca**
Those new modules are available to start your review:
FastSimulation/PPSFastObjects
FastSimulation/PPSFastSim
FastSimulation/PPSValidation

More information are this twiki page: https://twiki.cern.ch/twiki/bin/view/CMS/PPSFastSimulation

### CODE REVIEW

**Comment by slava77** [comment]
@lveldere a part of this will probably end up in your category

**Comment by slava77** [comment]
@cmsbuild 

The first feeling from looking at  FastSimulation/PPSFastObjects and some other files (more superficially)
is that a good fraction of this will need to be changed by quite a lot.
While that is happening, let's see how much of this even compiles.

**Comment by lveldere** [comment]
I asked Sandro to open a pr,
such that we can start a discussion.

Sandro, could you provide a recipe to run this?

Unfortunately I have to warn you:
Given the scale of this pr,
and given that I'm very busy until February 16,
it will take quite a bit of time to review this.

**Comment by sandrofonseca** [comment]
Of course, Lukas.
 You can find a recipe on twiki page:

https://twiki.cern.ch/twiki/bin/view/CMS/PPSFastSimulation
on tag Recipe cmsDriver commands for CMSSW_8_0_0_pre5

Let me know if it is OK for you.





Dr. Sandro Fonseca de Souza
__________________________________
Universidade do Estado do Rio de Janeiro - UERJ/IF/DFNAE
524 São Francisco Xavier Street,3rd Floor,Office 3016A, Maracanã, Rio de
Janeiro,
Brazil.
ZIP Code: 20559-900
Phone: +552123340623
Brazilian Mobile: +552182359943
Swiss Mobile:+41762197264
Skype Name: sandro_fonseca
MSN: sandrofonsecauerj@hotmail.com
C.Lattes:http://lattes.cnpq.br/4560612419350680
Home page: https://sites.google.com/site/sfonsecauerj2012/
------------------------------------------------
CERN - European Laboratory for Particle Physics
CH - 1211 Geneva 23
Tel:74949 (from outside: +41 22 76 74949 )
Office: 32 4-C14 Mailbox: J19910
email: sfonseca@cern.ch
Linkedin profile:
http://ch.linkedin.com/pub/sandro-fonseca-de-souza/29/85a/480

**Comment by slava77** [comment]
On 2/3/16 5:32 AM, lveldere wrote:
> I asked Sandro to open a pr,
> such that we can start a discussion.
> 
> Sandro, could you provide a recipe to run this?
> 
> Unfortunately I have to warn you:
> Given the scale of this pr,
> and given that I'm very busy until February 16,
> it will take quite a bit of time to review this.


Since suggested changes may be significant, Sandro,
I suppose you have a setup on your side to validate that any changes
will actually
stay technical, that plots of physics performance will not change.

**Comment by sandrofonseca** [comment]
Yes, we have to  analyzer to make a validation plots for central detector (CMS) and CT-PPS. You find it on FastSimulation/PPSValidation

As these new module are not interfere in the core of CMS Fast Simulation. We believe that physics performance distributions will not be affected.

**Comment by slava77** [comment]
On 2/3/16 5:57 AM, sandrofonseca wrote:
> Yes, we have to analyzer to make a validation plots for central detector
> (CMS) and CT-PPS. You find it on FastSimulation/PPSValidation
> 
> As these new module are not interfere in the core of CMS Fast
> Simulation. We believe that physics performance distributions will not
> be affected.

I meant the CT-PPS validation part.
For validation the existing other parts of CMS we have things setup
reasonably well.

**Comment by sandrofonseca** [comment]
Slava,
 I think that using exclusive dijets events@13 TeV( computed with ExHuME) is good experiment signature to evaluate a physics performance of CT-PPS. Thus we can make a comparison generator and reco level for CT-PPS.

For example: generated vs. reconstructed values of |t| and ξ for the protons within the CT-PPS detector acceptance, Mass acceptance as a function of centrally produced mass for exclusive dijet events and CT-PPS detector occupancy.

Our validation code are covering all main plots which are using to publish the CT-PPS TDR and I believe that we can include it in main CMS Fastsim validation in near future.

I will open  this topic for CT-PPS developers to elaborate it in details.

**Comment by slava77** [comment]
Hi Sandro,

Just to clarify my earlier question: I wanted to check that you have a setup  that can produce plots covering the necessary full space and is also fairly exhaustive in the variables checked.
In case changes are requested in the code, I'd like to be sure that you can check quickly that they do not introduce any changes (or if any changes show up, they will be easily spotted).
This is a rather technical validation question, not a physics generator vs reconstruction comparison point.

**Comment by slava77** [comment]
@sandrofonseca 
please review issues reported by the static code analysis
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13173/10973/llvm-analysis/

**Comment by lveldere** [comment]
@slava77 

I don't really know how this test works.
But, if Sandro's module is not run,
can it affect the static tests?
I mean, are these bugs related to Sandro's code,
or are they inside standard FastSim?

**Comment by slava77** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13173/10973/llvm-analysis/
Regarding the static analyzer report, it's just the code analysis (no runtime), done for the new code.
So, it is in Sandro's code.

@smuzaffar @Dr15Jones why do we get only the file names and no directory names in the report?

**Comment by sandrofonseca** [comment]
Yes, that setup is enough to do the necessary physics validation.




Dr. Sandro Fonseca de Souza
__________________________________
Universidade do Estado do Rio de Janeiro - UERJ/IF/DFNAE
524 São Francisco Xavier Street,3rd Floor,Office 3016A, Maracanã, Rio de
Janeiro,
Brazil.
ZIP Code: 20559-900
Phone: +552123340623
Brazilian Mobile: +552182359943
Swiss Mobile:+41762197264
Skype Name: sandro_fonseca
MSN: sandrofonsecauerj@hotmail.com
C.Lattes:http://lattes.cnpq.br/4560612419350680
Home page: https://sites.google.com/site/sfonsecauerj2012/
------------------------------------------------
CERN - European Laboratory for Particle Physics
CH - 1211 Geneva 23
Tel:74949 (from outside: +41 22 76 74949 )
Office: 32 4-C14 Mailbox: J19910
email: sfonseca@cern.ch
Linkedin profile:
http://ch.linkedin.com/pub/sandro-fonseca-de-souza/29/85a/480

**Comment by sandrofonseca** [comment]
Slava,
You can run my code using cmsDriver commands:
cmsDriver.py TTbar_Tauola_13TeV_cfi -n 10  \
   --fast --conditions auto:run2_mc --pileup_input file:minbias.root \
   --eventcontent AODSIM -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,RECO \
   --beamspot NominalCollision2015 --datatier GEN-SIM-DIGI-RECO \
   --pileup AVE_35_BX_25ns --era Run2_25ns \
   --customise FastSimulation/PPSFastSim/customise_FastSimCTPPS_cff.customise_pu_protons_ctpps 

This customize above file can load CT-PPS FastSim for AODSIM.

**Comment by slava77** [comment]
On 2/3/16 9:05 AM, sandrofonseca wrote:
> Slava,
> You can run my code using cmsDriver commands:
> cmsDriver.py TTbar_Tauola_13TeV_cfi -n 10 \
> --fast --conditions auto:run2_mc --pileup_input file:minbias.root \

Hi Sandro,

where/how do we get minbias.root?

**Comment by sandrofonseca** [comment]
You can produce minbias sample using another cmsDriver command:
cmsDriver.py MinBias_13TeV_pythia8_TuneCUETP8M1_cfi -n 1000 \ 
   --fast --conditions auto:run2_mc --magField 38T_PostLS1 \
   --beamspot NominalCollision2015 -s GEN,SIM,RECOBEFMIX \
   --eventcontent FASTPU --datatier GEN-SIM-RECO --era Run2_25ns --fileout minbias.root

**Comment by smuzaffar** [comment]
@slava77 , I will check why the package path is missing for the static analyzer

**Comment by smuzaffar** [comment]
@slava77 , It could be side effect of new clang version 3.7.1.  I think it now drops the common path from the file names. In this case, as all the files were in same directory so it just drop every thing.  For another PR analyzer keep the last directory
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13063/10964/llvm-analysis/
```
@davidlt , @gartung do you have any clue?

**Comment by gartung** [comment]
@smuzaffar Check the script that copies over the SA report. I think I did something with sed to remove long paths from the html file but I don't recall where that is done.

**Comment by smuzaffar** [comment]
@gartung , I do not think it is with the sed. Looks like it is just dropping the common part from the file name. I do not know if it is analyzer itself or some of our script. e.g. see this 
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13171/10971/llvm-analysis/
```
here it only drop the first / as the rest of the path was different

**Comment by gartung** [comment]
You are correct. I checked the jenkins script and there is no post processing with sed. I think scan-build decides what part of the path to report.

**Comment by smuzaffar** [comment]
@gartung, looks like we had this patch
```
https://github.com/cms-externals/clang/commit/40e9a1afcd0293fa93b8a6e8ef4e065668c147c6
```
for clang 3.6.0 which is not in 3.7.1 build of clang.

**Comment by gartung** [comment]
Yes that is the one.

**Comment by davidlt** [comment]
Yes, looks like I missed it as it was "recent" addition. I will put it in.

**Comment by sandrofonseca** [comment]
Hi @slava77 @lveldere 
What is status about this?
How can we move forward this PR?
Is there some a open issue of the my side?

**Comment by lveldere** [comment]
Hi Sandro

As said, I could not start reviewing right away.
(there was a fastsim workshop this week)
I'll start probably on Monday.

Cheers

Lukas

**Comment by sandrofonseca** [comment]
Hi Lukas,
Thanks for clarify this point.

Cheers,
Sandro

**Pull request closed without merging**
