### PR TITLE
add protection in customs functions for miniAOD-only relval workflows

### PR DESCRIPTION
**Pull request by hengne**
add protection in customs functions for miniAOD-only relval workflows
needed by https://github.com/cms-sw/cmssw/pull/12720

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by slava77** [comment]
@hengne 
for miniAOD-only workflows please use eras.
The customizations still stay for workflows with reco.

**Comment by slava77** [comment]
hold

**Comment by hengne** [comment]
@slava77 @mark-grimes Hi Slava, this is for 2015 data workflows, according to Mark, this --era is not yet done for 2015 data workflows. E.g. if you look at https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/Configuration/PyReleaseValidation/python/relval_steps.py#L911-L912

**Comment by slava77** [comment]
I know
there is nothing special in miniAOD for data. It should be the same as MC (modulo the bunchSpacingProducer).
Is there an indication that --era is not working for miniAOD? (I know that it runs)

**Comment by hengne** [comment]
@slava77 do you mean just the --era Run2_25ns or Run2_50ns for both MC and data?

**Comment by slava77** [comment]
right

**Comment by slava77** [comment]
data reco step still needs customization calls: the only relevant specifics there are affecting local reco setup which is not running in miniAOD-only.

**Comment by hengne** [comment]
@slava77 because we never used this --era for 2015 data workflows before, so I am not sure if they can produce the same results. And, i've never compared the two method if they produce the same configuration file. So, if you know this for sure, i will change it then.

**Comment by hengne** [comment]
@slava77 @davidlange6  i will close this PR and move back to https://github.com/cms-sw/cmssw/pull/12720 and update it accordingly.

**Comment by hengne** [comment]
close, confirmed can safely remove the custom function.

**Comment by slava77** [comment]
On 12/9/15 9:05 AM, Hengne Li wrote:
> @slava77 <https://github.com/slava77> because we never used this --era
> for 2015 data workflows before, so I am not sure if they can produce the
> same results. And, i've never compared the two method if they produce
> the same configuration file. So, if you know this for sure, i will
> change it then.
> 

Depending on the level of paranoia, anything can be unsafe.

I haven't noticed any differences in tests of 2015C about a week ago
(before the tau reminiaod PR was signed off).
But then the comparisons were at the level of event size.

There is a miniAOD standalone validation sequence available now.
We should probably have a comparison workflow
(stepX: data reco+miniAOD with customize
stepXharvest
stepY: data miniAOD-only with era + miniAOD validation
stepYharvest

**Comment by hengne** [comment]
@slava77 
```
We should probably have a comparison workflow (
stepX: data reco+miniAOD with customize stepXharvest 
stepY: data miniAOD-only with era + miniAOD validation stepYharvest
```
I can just dump the configuration files from the two cases and make a diff to check if there is any difference. sounds good?

**Comment by slava77** [comment]
On 12/9/15 9:25 AM, Hengne Li wrote:
> @slava77 <https://github.com/slava77>
> 
> |We should probably have a comparison workflow ( stepX: data reco+miniAOD
> with customize stepXharvest stepY: data miniAOD-only with era + miniAOD
> validation stepYharvest |
> 
> I can just dump the configuration files from the two cases and make a
> diff to check if there is any difference. sounds good?

yes it should work, assuming python doesn't reshuffle the psets.
(Maybe you have a more smart comparison tool though)

**Comment by hengne** [comment]
@davidlt OK, the diff of the full dump of the config files shows some difference but the "modules" of these differences are NOT used in the miniAOD step . ;-D So, we can safely remove this customise function. 

```
35222c35222
<     includeBadChambers = cms.bool(True),
---
>     includeBadChambers = cms.bool(False),
36167c36167
<         tag = cms.string('L1Menu_Collisions2015_50nsGct_v4')
---
>         tag = cms.string('L1Menu_Collisions2015_25nsStage1_v5')
38777,38778d38776
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
38781d38778
<         'keep *_simHcalUnsuppressedDigis_*_*', 
39301,39302c39298
<         'keep *_simHcalTriggerPrimitiveDigis_*_*', 
<         'keep *_simHcalUnsuppressedDigis_*_*' ) ),
---
>         'keep *_simHcalTriggerPrimitiveDigis_*_*' ) ),
39329,39330d39324
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
39333d39326
<         'keep *_simHcalUnsuppressedDigis_*_*', 
39854d39846
<         'keep *_simHcalUnsuppressedDigis_*_*', 
41065,41066d41056
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
41069d41058
<         'keep *_simHcalUnsuppressedDigis_*_*', 
43660,43661d43648
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
43664d43650
<         'keep *_simHcalUnsuppressedDigis_*_*', 
43838,43839d43823
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
43842d43825
<         'keep *_simHcalUnsuppressedDigis_*_*', 
43904,43905d43886
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
43908d43888
<         'keep *_simHcalUnsuppressedDigis_*_*', 
46220,46221d46199
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
46224d46201
<         'keep *_simHcalUnsuppressedDigis_*_*', 
46269,46270d46245
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
46273d46247
<         'keep *_simHcalUnsuppressedDigis_*_*', 
48017,48018d47990
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*', 
48021d47992
<         'keep *_simHcalUnsuppressedDigis_*_*', 
49260,49261c49231
<         'keep *_simHcalTriggerPrimitiveDigis_*_*', 
<         'keep *_simHcalUnsuppressedDigis_*_*')
---
>         'keep *_simHcalTriggerPrimitiveDigis_*_*')
49266,49267c49236
<         'keep EESrFlagsSorted_simEcalDigis_*_*', 
<         'keep *_simHcalUnsuppressedDigis_*_*')
---
>         'keep EESrFlagsSorted_simEcalDigis_*_*')
49326,49328c49295
<         'keep RPCDigiSimLinkedmDetSetVector_simMuonRPCDigis_*_*', 
<         'keep *_simMuonCSCDigis_*_*', 
<         'keep *_simMuonRPCDigis_*_*')
---
>         'keep RPCDigiSimLinkedmDetSetVector_simMuonRPCDigis_*_*')
```

**Pull request closed without merging**
