### PR TITLE
Switched from Xerces to tinyxml2 for Services

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

We already are dependent on tinyxml2 from MessageLogger. In addition, tinyxml2 is more thread friendly and seems lighter weight.

#### PR validation:

Code compiles and framework related tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic the L1 part of this PR is minimal and purely technical, please have a look, I will integrate it in next IB

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
