### PR TITLE
add wf 136.72411 re-miniAOD Run2 UL workflow for Run2016B useful for PPS testing

### PR DESCRIPTION
**Pull request by slava77**
the need for this was discussed by email about a month ago.
incidentally, the RECO is still in production https://cms-pdmv.cern.ch/pmp/historical?r=ReReco-Run2016B-JetHT-21Feb2020_ver2_UL2016_HIPM-0032
I tested that this wf runs locally.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 136.72411

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
