### PR TITLE
2017 Photon ID (cut based +MVA) Electron ID (cut based) implementation : 94X MiniAOD

### PR DESCRIPTION
**Pull request by lsoffi**
Already reviewed and merged in the master (PR #21975)
Link to PR #21975: https://github.com/cms-sw/cmssw/pull/21975

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
for this and the other PR we need to have the RecoEgamma/*Identification external in the release.
i've asked for an update in https://github.com/cms-sw/cmsdist/pull/3668

**Comment by Sam-Harper** [comment]
many thanks Slava!

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3763

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#3763

**Comment by slava77** [comment]
backport of #21975

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
it looks like this PR tests comparisons are also affected by cms-bot using a wrong baseline (94X instead of 9_4_MAOD_X)

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#3763

to clear irrelevant differences https://github.com/cms-sw/cmssw/pull/22303#issuecomment-368935226

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22302	a1c8d5b
- the same as https://github.com/cms-sw/cmssw/pull/21975	a1c8d5b (the same topic branch was used for this PR as in the master)
- jenkins tests pass and comparisons with the baseline show no differences (the IDs are not enabled in this PR yet)
- see notes from the master PR integration on more test results https://github.com/cms-sw/cmssw/pull/21975#issuecomment-367062350

This has to be merged together or after  https://github.com/cms-sw/cmsdist/pull/3763

**Comment by fabiocos** [comment]
@slava77 cms-sw/cmsdist#3763 has been merged earlier today so I assume this could be integrated even for this evening

**Comment by slava77** [comment]
On 3/1/18 10:15 AM, Fabio Cossutti wrote:
> @slava77 <https://github.com/slava77> cms-sw/cmsdist#3763
> <https://github.com/cms-sw/cmsdist/pull/3763> has been merged earlier
> today so I assume this could be integrated even for this evening
> 

Nice.
Thank you.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
