### PR TITLE
[12_6_X] Updates on GE21 online/offlineDQM plots with division on modules

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:

This PR provides massive updates on GE21 onlineDQM/offlineDQM plots. This work is focusing on the division of GE21 information by modules (M1-M4). It is necessary because of the electronic configuration of GE21 chambers.

It is also included that the module information is propagated to the GEM unpacker in a better way, which is done by @yeckang.

This update was planned to be implemented in CMSSW_12_6_X (#39985), but it wasn't because this PR was merged "after" the 12_6 branch was detached from HEAD, unfortunately. This PR is a fix for this accident.

#### PR validation:

The updates are exactly the same as #39985, and the previous PR is already valid.

@jshlee @watson-ij @seungjin-yang @yeckang

### CODE REVIEW

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39985

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
thank you very much @quark2

**Comment by quark2** [comment]
Thank you @emanueleusai for your quick actions. I should respond much earlier...

**Comment by emanueleusai** [comment]
+1

- differences as expected in GEM DQM plots.
- differences matching what observed in the already approved master branch PR

**Comment by civanch** [comment]
+1

@quark2 , your title is non-standard. Please, have a look into other PRs titles, as minimum, put [12_6_X] in front and remove the end of this title, which is misleading.

**Comment by quark2** [comment]
Hi @civanch, 

Okay, I didn't know that well... I've changed the title. Let me know if the title is still not good enough.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
hold

* As discussed in ORP meeting, this will be on indefinite hold and updated only in online dqm.

**Comment by clacaputo** [comment]
Can we close this PR, or is still needed for online operations?

**Comment by perrotta** [comment]
> Can we close this PR, or is still needed for online operations?

Online operations moved to 13_0_X since some while already: let close this PR

**Pull request closed without merging**
