### PR TITLE
Fixes for Tag&Probe in 7.5.X (fix of #8801)

### PR DESCRIPTION
**Pull request by gpetruc**
As #8801 but with the merge conflict solved and pushed to a different branch, to avoid overwriting the old one which was merging fine in 74X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar @degano 
please check the results of tests in this PR: the link https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9512/10135/summary.html is 404 now, and the comparisons available message was never sent.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
looks like the ib integration job failed to connect to cmssdt01 and was 
not able to copy the results there. For now I have asked for a retest

**Comment by cvuosalo** [comment]
+1

For #9512 a565d051d289b2f9798dbc65560ec29e663f835a

Fixes for tag & probe. Reco changes are very minor. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9512/8114/summary.html) against baseline CMSSW_7_5_X_2015-06-08-2300 show no significant differences, as expected.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
