### PR TITLE
First version of the DQMOffline for L1T Taus - 92x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #19441

### CODE REVIEW

**Comment by thomreis** [comment]
In order to avoid a crash of the L!TMuon harvesting PR #20032 should be merged first.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@dmitrijus please sign

93x version of this has been merged since 8 days ago.

**Comment by rekovic** [comment]
@davidlange6 
Please, first merge https://github.com/cms-sw/cmssw/pull/20032, before this PR is merged.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
