### PR TITLE
TAU LUTs to match data

### PR DESCRIPTION
**Pull request by mulhearn**
This is the 76X version of #10491

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
@mulhearn - is this good to go?

**Comment by mulhearn** [comment]
Data file are in CMS data, so if I remove those, yes.

**Comment by mulhearn** [comment]
Sorry, forgot this PR existed already... obsoleted by #11253 which has data files removed from PR.

**Pull request closed without merging**
