### PR TITLE
12_4_X Fixed FullModelHadronicProcess.cc energy deposit model

### PR DESCRIPTION
**Pull request by ctdax**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [previous PR](https://github.com/cms-sw/cmssw/pull/46728) to CMSSW_12_4_X. This backport is necessary because CMSSW_12_4_X is a version that we expect to use for an upcoming analysis.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46728

**Comment by tvami** [comment]
@cms-sw/orp-l2 we'd like a new 12_4_X release with this included too

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
