### PR TITLE
HLT development updates for 80X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT development updates for 80X

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones ,
please sign this PR. Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
