### PR TITLE
Update customisePixelL1ClusterThresholdForRun2Input to adjust also the GPU producer [12.1.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update `customisePixelL1ClusterThresholdForRun2Input()` to adjust also the GPU producer with the Run 2 settings.

#### PR validation:

None.

#### PR backport status:

Backport of #35901 to 12.1.x .

### CODE REVIEW

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
test parameters:
  - pull_request = #35905

**Comment by missirol** [comment]
+hlt

 - despite the label, this PR did not really require any externals
 (the other PR is not merged yet; it provides an unrelated fix for a timeout in a PR test)

**Comment by qliphy** [comment]
+1

**Pull request merged**
