### PR TITLE
Backport of HLTJetTagWithMatching in 73X (#6985)

### PR DESCRIPTION
**Pull request by silviodonato**
Backport of https://github.com/cms-sw/cmssw/pull/6985

---

"
I'm proposing to add the HLTJetTagWithMatching module in CMSSW.
This module is very similar to HLTJetTag.

HLTJetTag is a filter that pass events matching some requirements on the jetTag (eg. CSV>0.7).
It uses a jet InputTag only to fill the TriggerFilterObjectWithRefs.

HLTJetTagWithMatching is a filter that loop on a jet collection, and each jet is matched with the jetTag.
In this way it use the jet information from the jet collection, and the b-tag information by the jetTag collection.

With the new module, it will be possible, for instance, to have filter like "at least one jet with pT>50 GeV and CSV>0.7". In fact, you can produces a subset of jets and give it as InputTag to this module.

Silvio.
"

### CODE REVIEW

**Comment by perrotta** [comment]
wrt #6985, you do not include here the definition of the new module in HLTrigger/btau/src/modules.cc

**Comment by davidlange6** [comment]
@silviodonato - please give this PR a descriptive title for the release notes. Thanks

**Comment by Martin-Grunewald** [comment]
-1
The SaveTags() restoration is still neded here!

**Comment by Martin-Grunewald** [comment]
+1
(Wrong PR given -1)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
