### PR TITLE
Simplification of GEM onlineDQM, backport to CMSSW_11_2_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
We've modified the structure of GEM onlineDQM to make it simpler so that developers and shifters of GEM will have more convenience. For developers, we are planning to unify several modules for GEM; onlineDQM, offlineDQM, validation, and it will be the start of the unification work. For shifters, many summarizing plots are added and mainly displayed; the detail plots will be hidden but can be easily found.

And this PR is a backport of https://github.com/cms-sw/cmssw/pull/32792.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @hyunyong

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by quark2** [comment]
Hi all, 

we are supposed to see the updates by this PR in the coming MWGR. Because it has a lot of changes on the GEM onlineDQM, I guess I need to report about this in the coming DQM General meeting (on this Friday). Is it okay?

**Comment by jfernan2** [comment]
Hi @quark2 
I have included you in the agenda for Friday, thanks!
https://indico.cern.ch/event/1005033/

**Comment by quark2** [comment]
Hi @jfernan2 
Great, thanks!

**Comment by jfernan2** [comment]
+1
Backport tested at P5 in Online DQM

**Comment by silviodonato** [comment]
+1
(already tested at P5 in Online DQM)

**Comment by quark2** [comment]
Hi @silviodonato, 

I also made a PR to the DQM GUI software [1]. Have you also tested?
(I should inform about this PR already in this thread...)

Best regards, 
Byeonghak Ko

[1] https://github.com/dmwm/deployment/pull/1028

**Comment by jfernan2** [comment]
Hi @quark2 
We were not aware of this PR, we will test it at P5 right now
I hope you have already tested it on your side, however this would only affect the GUI, the worst thing is some plot not being displayed but no crashes are possible.

**Comment by quark2** [comment]
Hi @jfernan2,

Sorry for my late notice... I already tested the PR for GUI and then PRed. Hope the test on your side will be done well.

Best regards, 
Byeonghak Ko

**Pull request merged**
