### PR TITLE
Move files from CalibTracker/SiStripDCS to cms-data

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

I came across this webpage
https://cmssdt.cern.ch/SDT/cgi-bin/newQA.py?arch=el8_amd64_gcc10&release=CMSSW_13_0_X_2022-12-14-2300
which shows that 
https://github.com/cms-sw/cmssw/tree/master/CalibTracker/SiStripDCS/data
this is the 6 biggest directory in CMSSW. The PR moves the files out of CMSSW to cms-data 

#### PR validation:

O2O tests to be performed

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, no backport needed

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-data/CalibTracker-SiStripDCS/pull/2

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
test parameters:
   * addpkg = CondTools/SiStrip, OnlineDB/SiStripO2O

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-data/CalibTracker-SiStripDCS/pull/2
  - addpkg = CondTools/SiStrip, OnlineDB/SiStripO2O

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * unit test testing O2O passed

**Comment by perrotta** [comment]
+1

**Pull request merged**
