### PR TITLE
Migrate DigiToRaw to Tasks

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates DigiToRaw step to use Tasks in the configuration. This change should increase the available concurrency in the jobs running DigiToRaw.

#### PR validation:

Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Technical: migration from Sequences to Tasks is implemented as proposed in the PR description
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+operations

the StandardSequence configurations update looks coherent with the purpose of the PR

**Comment by fabiocos** [comment]
@rekovic could you please have a look?

**Comment by fabiocos** [comment]
@rekovic ping

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@rekovic please check and comment in case

**Comment by rekovic** [comment]
+1

**Pull request merged**
