### PR TITLE
Follow up to new high granularity pixel alignment for the PCL

### LINKED ISSUE #38506: Unit failure: test_PixelBaryCentreTool had ERRORS
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_5_X_2022-06-24-2300/unitTestLogs/Alignment/TrackerAlignment#/12-12

Local test output as below:
cmsrel CMSSW_12_0_X_2021-07-26-1100
cd CMSSW_12_0_X_2021-07-26-1100/src/
cmsenv
git cms-addpkg Alignment/TrackerAlignment
git cms-merge-topic 34542
scram b -j9
cd Alignment/TrackerAlignment/test/
source pixelPositions.sh

----- Begin Fatal Exception 25-Jun-2022 09:22:38 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing Looper: class=AlignmentProducer label='@main_looper'
Exception Message:
MissingParameter: Parameter 'trackerAlignmentRcdName' not found.
----- End Fatal Exception -------------------------------------------------

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/38506

#### PR description:

This PR has 3 commits:
   * 1ac393ce9dbd37d6f1944233b100b527425611ea addresses the comments left in this review: https://github.com/cms-sw/cmssw/pull/38449#pullrequestreview-1018465985
   * 63c4850f1b64c00b97ad7355335d29e95122ddc0 +  https://github.com/cms-sw/cmssw/pull/38508/commits/2ee03912aac32859f03b10528c64f8744330325d resolve issue #38506

#### PR validation:

Run the `Alignment/TrackerAlignment` unit tests successfully

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport but will need to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Alignment/TrackerAlignment

**Comment by tvami** [comment]
type bugfix,trk

**Comment by tvami** [comment]
urgent
 * the backport needs to go to 12_4_X

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
OK now it fails with:
```
----- Begin Fatal Exception 25-Jun-2022 15:04:58 CEST-----------------------
An exception of category 'MakeDataException' occurred while
   [0] Using EventSetup component AlignmentProducer/'' to make data TrackerGeometry/'' in record TrackerDigiGeometryRecord
Exception Message:
Error while making data "TrackerGeometry" "" in Record TrackerDigiGeometryRecord
----- End Fatal Exception -------------------------------------------------
```

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+1
 * the unit test reported in https://github.com/cms-sw/cmssw/issues/38506 is now working
 * the code changes are according to the PR describtion

**Comment by perrotta** [comment]
+1

**Pull request merged**
