### PR TITLE
particle guns (pythia8) for upgrade

### PR DESCRIPTION
**Pull request by boudoul**
[preparation of merging upgrade software into mainstream release]
Bunch of particle guns fragments used for upgrade relvals 
@mark-grimes:  FYI

### CODE REVIEW

**Comment by bendavid** [comment]
Naming note,
addAntiParticle = true I believe means that this is actually a particle-antiparticle gun (ie DOUBLE gun)

**Comment by boudoul** [comment]
that's right , actually this is the case for a large fraction of  the Single* fragments in this directory not only 'mine'

**Comment by bendavid** [comment]
Suggest to fix it at least for the new fragments.

(Either make them single particle gun, or change the fragment name as preferred...)

**Comment by boudoul** [comment]
Good suggestion , I will change the names and update this PR

**Comment by boudoul** [comment]
argh git didn't take into account the rm, I screwed up let m close this PR will redo a fresh one

**Pull request closed without merging**
