### PR TITLE
Add a LowPU version of the HP Beam Spot workflow for PCL

### PR DESCRIPTION
**Pull request by cerminar**
A new PCL workflow is defined targeting the Beam-Spot computation in LowPU environment.
This is defining `PromptCalibProdBeamSpotHPLowPU` and the corresponding AlCaHarvesting steps.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@cerminar do you also plan to have a backport in 10.1.X ?

**Comment by arunhep** [comment]
answering myself  : https://github.com/cms-sw/cmssw/pull/23559

**Comment by fabiocos** [comment]
@cerminar do we have a test wf that is really probing this code? 1030 is testing HPBS, but I guess that is code is not enabled in that test, right? Should one do an ad hoc test?

**Comment by cerminar** [comment]
Dear @fabiocos,

> @cerminar do we have a test wf that is really probing this code? 1030 is testing HPBS, but I guess that is code is not enabled in that test, right? Should one do an ad hoc test?

indeed there is currently no test of the new workflow beside those run by hand by @sarafiorendi.
We could indeed add `PromptCalibProdBeamSpotHPLowPU` and a dedicated harvesting to 1030.
The best would probably be to add it both in the UnitTests of `ConfigDP` and in the matrix.

**Comment by cerminar** [comment]
please test

**Comment by fabiocos** [comment]
@cerminar thanks

@arunhep @lpernie @fabozzi @prebello @kpedro88 this PR is needed for the Totem run, so it should enter 10_1_7 asap. Could you please check and comment or sign it? Thanks

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
@cerminar @arunhep running manually wf 1030 (now I triggered it in the 10_1_X PR test) I see it ends apparently fine, but in the step3 log output I see a list of messages

Begin processing the 100th record. Run 297557, Event 238868835, LumiSection 148 on stream 1 at 13-Jun-2018 09:35:05.706 CEST
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
Inversion failed
%MSG-w PVFitter:  AlcaBeamSpotProducer:alcaBeamSpotProducerHPLowPU@endLumi  13-Jun-2018 09:35:07 CEST Run: 297557 Lumi: 148
3D beam spot fit returns nan in 3rd iteration
%MSG

This should come from

https://cmssdt.cern.ch/lxr/source/RecoVertex/BeamSpotProducer/src/FcnBeamSpotFitPV.cc#0154

and it is induced by the new addition as it can be seen.

**Comment by fabiocos** [comment]
Interestingly, the same step in 10_1_X ends with a 

%MSG-w PVFitter:  AlcaBeamSpotProducer:alcaBeamSpotProducerHP@endLumi  13-Jun-2018 10:22:37 CEST Run: 297557 Lumi: 148
3D beam spot fit failed in 1st iteration
%MSG
%MSG-w PVFitter:  AlcaBeamSpotProducer:alcaBeamSpotProducerHPLowPU@endLumi  13-Jun-2018 10:22:37 CEST Run: 297557 Lumi: 148
3D beam spot fit failed in 2nd iteration
%MSG

**Comment by fabiocos** [comment]
+operations

the changes to StandardSequences and DataProcessing look consistent with the purpose of the PR, RelVal 1030 runs and the DataProcessing configuration is built correctly

**Comment by fabiocos** [comment]
running on 1000 events, the list of messages appear twice at the transitioon between lumi sections, while it does not appear (or the messages seen in 10_1_X test are seen) for others. So I assume that this is related to the specific set of data analysed, plus differences in the fit between 10_1_X and 10_2_X    (ROOT version ?)

**Comment by cerminar** [comment]
@fabiocos, the best person to look into these messages is probably @sarafiorendi .
Cheers

**Comment by fabiocos** [comment]
@cerminar in any case the basic operation of the workflow looks ok, the messages are likely related to the tuning of the algorithm parameters

**Comment by cerminar** [comment]
please test workflow 1030

**Comment by sarafiorendi** [comment]
hi,
I suggest to change the value of the "errorScale" parameter, currently = 1.1, to 0.9.
We verified in the past that using 1.1 (value measured via split vertex method on data) leads to a larger number of non-converging beamspot fits when running on ZeroBias data.
The needed modification is just to add this line:

alcaBeamSpotProducerHPLowPU.PVFitter.errorScale = cms.untracked.double(0.9)

here 
https://github.com/cerminar/cmssw/blob/f582ccfcdeecca3b00443d9861a776c8dc72c212/Calibration/TkAlCaRecoProducers/python/ALCARECOPromptCalibProdBeamSpotHPLowPU_cff.py#L10

I tested the workflow locally on 100 events (in 10_1_X) with this change and the fit does converge properly.

**Comment by fabiocos** [comment]
@sarafiorendi excellent, thanks, let me repeat my test with higher statistics

**Comment by fabiocos** [comment]
@sarafiorendi @cerminar running 1030 on 1000 events: there are 4 lumi section transitions, in the first one

%MSG-w PVFitter:  AlcaBeamSpotProducer:alcaBeamSpotProducerHP@endLumi  13-Jun-2018 16:32:58 CEST Run: 297557 Lumi: 148
3D beam spot fit failed in 1st iteration
%MSG

for the following two I still get "Inversion failed", while the last one looks ok "read without any error message)

**Comment by fabiocos** [comment]
@cerminar @sarafiorendi @arunhep I understand that this is not anyway a show-stopped to get the new PCL code integrated, possibly a further tuning (in case it is really needed) can happen in a patch

**Comment by fabiocos** [comment]
+operations

**Comment by kpedro88** [comment]
+1

**Comment by sarafiorendi** [comment]
Hi @fabiocos, 

I think the error message(s) is coming from the alcaBeamSpotProducerHP workflow, not the newly introduced one (alcaBeamSpotProducerHPLowPU). 
Step3 of this runTheMatrix runs both the HP fit (with more severe cuts on the input vertices and errorScale=1.1) and LowPU fit (w/o cuts and errorScale=0.9), and in fact if I run the two workflows offline on 1000 events I see converging fits for all the LSs for the second one (not for the first, which converges only in LS 152).

**Comment by fabiocos** [comment]
@sarafiorendi you are correct, they both run together, thanks for cross checking.

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

PdmV changes are working (wf 1030 used for this validation), the comparion was ok, and wf 1030 is not used in comparisons

**Comment by fabiocos** [comment]
merge

**Pull request merged**
