### PR TITLE
Fix for --dump_python option giving inconsistent output

### PR DESCRIPTION
**Pull request by pkalbhor**
#### PR description:
Bug fix for `cmsDriver.py` which when used with `--dump_python` giving inconsistent/incorrect output.
Issue was raise few times already [Issue#37976](https://github.com/cms-sw/cmssw/issues/37976), [Issue#38686](https://github.com/cms-sw/cmssw/issues/38686)

### CODE REVIEW

**Comment by emanueleusai** [comment]
-1

- remove from dqm queues

**Comment by jfernan2** [comment]
-1
remove from reco queues

**Comment by jfernan2** [comment]
+1
For the records

**Comment by tjavaid** [comment]
+1

**Comment by jfernan2** [comment]
+reconstruction

To clean the queue

**Pull request merged**
