### PR TITLE
[12.4.X] Pixel Heterogeneous DQM: add 1D differnce plots in vertex comparison module.

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #38245 

#### PR validation:
GPU wfs run.

### CODE REVIEW

**Comment by sroychow** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by sroychow** [comment]
enable gpu

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by sroychow** [comment]
backport of #38245

**Comment by mmusich** [comment]
type tracking

**Comment by emanueleusai** [comment]
again that doesn't look related to this PR

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
