### PR TITLE
 python3 compatibility in FWCore/ParameterSet

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:
string-escape and __cmp__ are removed in python3 - update FWCore/ParameterSet/python/Types classes not to use them.

#### PR validation:

reco sequence running in python3

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
