### PR TITLE
Run3-gex142D Replace cout with edm::LogVerbatim in Alignment/CommonAlignmentMonitor

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace cout with edm::LogVerbatim in Alignment/CommonAlignmentMonitor

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
@bsunanda could you also create fillDescription for those plugins?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
+alca

- no differences aside from msgLogger
- strictly technical changes

**Comment by rappoccio** [comment]
+1

* Technical migration.

**Pull request merged**
