### PR TITLE
L1T online DQM changes - 91x

### PR DESCRIPTION
**Pull request by thomreis**
91x version of #18662 

Improvements and fixes for the L1T online DQM

- Add fillDescriptions
- reorganizing config files
- Move uGMT emulator DQM before the fat event filter
- renaming L1T2016 directories that somehow managed to be only changed in 90x releases but not in 91x and 92x.
- fix bug in L1 muon comparison module

### CODE REVIEW

**Comment by thomreis** [comment]
This PR addresses a comment made here: https://github.com/cms-sw/cmssw/pull/18500#pullrequestreview-36213502

**Comment by thomreis** [comment]
backport of #18662

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
