### PR TITLE
Update the configuration for the `--timing` option [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Customise the `FastTimerService` to generate a JSON file that can be displayed in a pie chart.
Generate the configuration for the `ThroughputService`.

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38675 .

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #38675

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
