### PR TITLE
`SiStripClusters2ApproxClusters`: run `peakFilter` only if cluster is usable

### LINKED ISSUE #42131: [ASAN] heap-buffer-overflow in `SiStripClusters2ApproxClusters::produce`
```
=================================================================
==3373081==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x14c35b0b67ff at pc 0x14c375779a06 bp 0x14c36d3fd760 sp 0x14c36d3fd758
READ of size 1 at 0x14c35b0b67ff thread T2
    #0 0x14c375779a05 in SiStripClusters2ApproxClusters::produce(edm::Event&, edm::EventSetup const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/pluginRecoLocalTrackerSiStripClusterizerPlugins.so+0x12ba05)
    #1 0x14c3a9bae417 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x7c2417)
    #2 0x14c3a9b209a0 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) [clone .localalias] [clone .lto_priv.0] (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x7349a0)
    #3 0x14c3a98d2e2c in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x4e6e2c)
    #4 0x14c3a98f4a1a in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so+0x508a1a)
    #5 0x14c3aa87b6cb in tbb::detail::d1::function_task<edm::WaitingTaskList::announce()::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libFWCoreConcurrency.so+0x96cb)
    #6 0x14c3a766c96e in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
    #7 0x14c3a766c96e in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
    #8 0x14c3a766c96e in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/arena.cpp:137
    #9 0x14c3a766c96e in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/market.cpp:599
    #10 0x14c3a766ebb4 in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/private_server.cpp:271
    #11 0x14c3a766ebb4 in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/private_server.cpp:221
    #12 0x14c3a67c71c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #13 0x14c3a6433e72 in __clone (/lib64/libc.so.6+0x39e72)

0x14c35b0b67ff is located 1 bytes to the left of 10166112-byte region [0x14c35b0b6800,0x14c35ba68760)
allocated by thread T0 here:
    #0 0x14c3a9ef5f57 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x14c3815253db in std::vector<unsigned char, std::allocator<unsigned char> >::reserve(unsigned long) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libCondFormatsCommon.so+0x803db)
    #2 0x14c381560515 in boost::archive::detail::iserializer<eos::portable_iarchive, std::vector<unsigned char, std::allocator<unsigned char> > >::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [clone .localalias] [clone .lto_priv.0] (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/libCondFormatsCommon.so+0xbb515)
    #3 0x14c38132de3f in boost::archive::detail::basic_iarchive::load_object(void*, boost::archive::detail::basic_iserializer const&) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/external/el8_amd64_gcc11/lib/libboost_serialization.so.1.80.0+0x17e3f)

Thread T2 created by T0 here:
    #0 0x14c3a9e9c706 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x14c3a766e241 in tbb::detail::r1::rml::internal::thread_monitor::launch(void* (*)(void*), void*, unsigned long) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/rml_thread_monitor.h:208
    #2 0x14c3a766e241 in tbb::detail::r1::rml::private_worker::wake_or_launch() /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/private_server.cpp:305
    #3 0x14c3a766e241 in tbb::detail::r1::rml::private_server::wake_some(int) /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-b1d97183c007769a478c02aa8504b8cb/tbb-v2021.9.0/src/tbb/private_server.cpp:412

SUMMARY: AddressSanitizer: heap-buffer-overflow (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02791/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_ASAN_X_2023-06-28-2300/lib/el8_amd64_gcc11/pluginRecoLocalTrackerSiStripClusterizerPlugins.so+0x12ba05) in SiStripClusters2ApproxClusters::produce(edm::Event&, edm::EventSetup const&)
Shadow bytes around the buggy address:
  0x0298eb60eca0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0298eb60ecb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0298eb60ecc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0298eb60ecd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0298eb60ece0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0298eb60ecf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0298eb60ed00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0298eb60ed10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0298eb60ed20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0298eb60ed30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0298eb60ed40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3373081==ABORTING

```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_2_ASAN_X_2023-06-28-2300/pyRelValMatrixLogs/run/140.58_RunHI2018/step2_RunHI2018.log#/37-37)

### LINKED ISSUE #42162: [DBG_X] RelVal 140.58 Step 2: Corrupted data in SiStripNoises::getNoise
The following exceptions are reported:
```
REPACK:DigiToApproxClusterRaw,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
entry filelist:step1_dasquery.log
found files:  ['/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root', '/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/45001EBC-B4D4-9043-A276-8F3AF621C64A.root', '/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/7B3F72ED-E183-3F4B-9FE4-DAE6D911403E.root', '/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/853DBE29-53BA-9A44-9FDD-58E4E9064EB1.root']
Step: REPACK Spec: ['DigiToApproxClusterRaw']
Step: ENDJOB Spec: 
customising the process with customisePostEra_Run2_2018_pp_on_AA from Configuration/DataProcessing/RecoTLR
customising the process with customiseWithTimeMemorySummary from Validation/Performance/TimeMemorySummary
Starting python2 /data/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 9000  cmsRun -j JobReport2.xml  step2_REPACK.py
%MSG-i ThreadStreamSetup:  (NoModuleName) 30-Jun-2023 08:32:40 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
30-Jun-2023 08:33:02 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root
30-Jun-2023 08:33:05 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root
Begin processing the 1st record. Run 326479, Event 1394020, LumiSection 7 on stream 3 at 30-Jun-2023 08:33:13.279 CEST
Begin processing the 2nd record. Run 326479, Event 1579493, LumiSection 7 on stream 2 at 30-Jun-2023 08:33:13.279 CEST
Begin processing the 3rd record. Run 326479, Event 1402087, LumiSection 7 on stream 0 at 30-Jun-2023 08:33:13.279 CEST
Begin processing the 4th record. Run 326479, Event 1328354, LumiSection 7 on stream 1 at 30-Jun-2023 08:33:13.279 CEST
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  30-Jun-2023 08:33:13 CEST Run: 326479 Event: 1402087
NULL pointer to FEDRawData for FED: id 434
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  30-Jun-2023 08:33:13 CEST Run: 326479 Event: 1579493
NULL pointer to FEDRawData for FED: id 434
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  30-Jun-2023 08:33:13 CEST Run: 326479 Event: 1328354
NULL pointer to FEDRawData for FED: id 434
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  30-Jun-2023 08:33:13 CEST Run: 326479 Event: 1394020
NULL pointer to FEDRawData for FED: id 434
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
----- Begin Fatal Exception 30-Jun-2023 08:33:33 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 326479 lumi: 7 event: 1328354 stream: 1
   [1] Running path 'REPACKRAWoutput_step'
   [2] Prefetching for module PoolOutputModule/'REPACKRAWoutput'
   [3] Calling method for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 768
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 30-Jun-2023 08:33:33 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 326479 lumi: 7 event: 1402087 stream: 0
   [1] Running path 'REPACKRAWoutput_step'
   [2] Prefetching for module PoolOutputModule/'REPACKRAWoutput'
   [3] Calling method for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 768
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 30-Jun-2023 08:33:33 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 326479 lumi: 7 event: 1579493 stream: 2
   [1] Running path 'REPACKRAWoutput_step'
   [2] Prefetching for module PoolOutputModule/'REPACKRAWoutput'
   [3] Calling method for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 768
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 30-Jun-2023 08:33:33 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 326479 lumi: 7 event: 1394020 stream: 3
   [1] Running path 'REPACKRAWoutput_step'
   [2] Prefetching for module PoolOutputModule/'REPACKRAWoutput'
   [3] Calling method for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 768
```

There are also warnings about NULL pointers to FEDRawData, not sure if they are related or harmless:
```
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  30-Jun-2023 08:33:13 CEST Run: 326479 Event: 1402087
NULL pointer to FEDRawData for FED: id 434
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
(...)
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT@endStream  30-Jun-2023 08:33:33 CEST PostEndProcessBlock
[sistrip::RawToDigiUnpacker::createDigis] warnings:
NULL pointer to FEDRawData for FED (1)
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/42131
resolves https://github.com/cms-sw/cmssw/issues/42162

#### PR description:

The goal of this PR is to solve the issues https://github.com/cms-sw/cmssw/issues/42131 and https://github.com/cms-sw/cmssw/issues/42132. 
Those issues are caused because there is a condition (`SiStripNoises`) which is read off its domain from this call:

https://github.com/cms-sw/cmssw/blob/fe01c0ef7402cf507d76755af115cbbcb590b707/RecoTracker/PixelLowPtUtilities/interface/SlidingPeakFinder.h#L72

when it looks for the noise of strip n. 768 for Detid 369120277. 
Having established at https://github.com/cms-sw/cmssw/issues/42162#issuecomment-1663600451 that for this detId (and similar modules), the strip range is from 0 to 767 (also independently, see https://github.com/mmusich/cmssw/commit/c1e1ca0e90afb54ebab8280fcc3897f2e6dca6ee), thus excluding possible issues with conditions, and following the line of thought that (see https://github.com/cms-sw/cmssw/issues/42162#issuecomment-1664035106) a very similar code was already used in https://github.com/cms-sw/cmssw/blob/c2e865adc2671fa7d91832fbdab21b90db967572/RecoTracker/PixelLowPtUtilities/src/StripSubClusterShapeTrajectoryFilter.cc#L84  which I think it has been used since ever for the Strip seeded iterations, it begs the question on why this was not spotted before in `StripSubClusterShapeTrajectoryFilter`.
I propose in this PR to follow (almost) the same prescription used in that file before running the filter, namely using the output of `ClusterShapeHitFilter::getSizes` 
 
https://github.com/cms-sw/cmssw/blob/c2e865adc2671fa7d91832fbdab21b90db967572/RecoTracker/PixelLowPtUtilities/src/StripSubClusterShapeTrajectoryFilter.cc#L258-L259
 
and the check on the measured (and predicted) cluster widths
 
https://github.com/cms-sw/cmssw/blob/c2e865adc2671fa7d91832fbdab21b90db967572/RecoTracker/PixelLowPtUtilities/src/StripSubClusterShapeTrajectoryFilter.cc#L265-L267
 
Since `ClusterShapeHitFilter::getSizes` is not called with the measured trajectory direction, but rather with an approximated direction (the line joining the BeamSpot to the cluster) I enlarge the window to encompass 2 cluster pitches rather than 1.5.
 
#### PR validation:

In `CMSSW_13_3_DBG_X_2023-08-01-2300` run successfully `runTheMatrix.py -l 140.58 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but to be backported to CMSSW_13_2_X.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
Cc: @Ksavva1021

**Comment by mmusich** [comment]
test parameters:
   * workflow = 140.58

**Comment by mmusich** [comment]
@cmsbuild, please test for CMSSW_13_3_DBG_X

**Comment by mmusich** [comment]
>-1
> Failed Tests: HeaderConsistency RelVals

so analyzing the output of the bot tests:
   *  as already reported in https://github.com/cms-sw/cmssw/pull/42486#issuecomment-1668032162 the HeaderConsistency [failure](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-db4e21/34130/headers_chks.log) looks spurious 
   * the failure in [23234.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-db4e21/34130/runTheMatrix-results/23234.0_TTbar_14TeV+2026D94) is expected, see also issue https://github.com/cms-sw/cmssw/issues/41088
   * on the bright side [140.58](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-db4e21/34130/runTheMatrix-results/140.58_RunHI2018/) did succeed (in DBG_X build), as per PR intentions.
   
I am going to relaunch the tests with the regular build to get rid of the failures.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> -1
> Failed Tests: RelVals-INPUT

let's try again.

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
