### PR TITLE
Lumi-based status plots on GEM onlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
A new type of status plots are added; lumi-based status plots. It displays the change of statuses of chambers as a function of lumi-blocks (=time).

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters:
- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
@quark2 we need a backport to 12_2_X to test this PR at P5 Online machines

**Comment by jfernan2** [comment]
BTW: DQM shifter is complaining that GEM plots are not linked to the Shift workspace in Online DQM GUI.

Could you make them available? A shift_gem_layout.py and a shift_gem_T0_layout.py file for Online and Offline resp. are needed in:

https://github.com/dmwm/deployment/tree/master/dqmgui/layouts

Thanks,

**Comment by quark2** [comment]
Hi @jfernan2, 

Sorry for my terribly late... I've made a PR for the shift plots for GEM on the DQM GUI software. Please see [1].

Best regards, 
Byeonghak Ko

[1] https://github.com/dmwm/deployment/pull/1131

**Comment by quark2** [comment]
Hi @jfernan2, 

I think you forgot to write "please test". Could you check it?

Best regards, 
Byeonghak Ko

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
@quark2 we need a backport to 12_2_X to test this PR at P5 Online machines

**Comment by quark2** [comment]
Hi @jfernan2, 

Sorry for my late. Here is the backport, #37204.

Best regards, 
Byeonghak Ko

**Comment by perrotta** [comment]
Now the master branch has moved to 12_4_X
Since you have already a backport to 12_2, please also prepare a backport for the intermediate 12_3 cycle, which will be used online after 12_2?

**Comment by quark2** [comment]
Hi @perrotta, 

Yep, sure. The backport for 12_3_X is now ready -- #37213.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
+1
Backport PR in 12_2_X  Tested successfully in Online DQM at P5

**Comment by qliphy** [comment]
@quark2   Would you please confirm the followings are ok?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-08-1100+6bff3c/48804/validateJR/all_OldVSNew_TTbar14TeV2026D49wf23234p0/all_OldVSNew_TTbar14TeV2026D49wf23234p0.log

plotting variable: recoRecoEcalCandidates_hfRecoEcalCandidate__RECO.obj.pt()
Error in <TH1F::KolmogorovTest>: Histogram1 recoRecoEcalCandidates_hfRecoEcalCandidate__RECO_obj_pt_refplot integral is zero

plotting variable: recoRecoEcalCandidates_hfRecoEcalCandidate__RECO.obj.eta()
Error in <TH1F::KolmogorovTest>: Histogram1 recoRecoEcalCandidates_hfRecoEcalCandidate__RECO_obj_eta_refplot integral is zero

plotting variable: recoRecoEcalCandidates_hfRecoEcalCandidate__RECO.obj.phi()
Error in <TH1F::KolmogorovTest>: Histogram1 recoRecoEcalCandidates_hfRecoEcalCandidate__RECO_obj_phi_refplot integral is zero

Branch LumiDetails_lumiProducer__RECO.obj is not found in either of the inputs. Skip.
Branch .obj is not found in either of the inputs. Skip.
DONE calling validate

**Comment by quark2** [comment]
Hi @qliphy, 

I think these messages are not related to this PR. It's only about GEM onlineDQM, and it doesn't have any effect on ECAL and luminosity and so on. Other messages in the log file related to GEM are not related to GEM onlineDQM. I have no idea why these messages come out (lack of statistics?), but these are not in the coverage of GEM onlineDQM, I think.

Best regards, 
Byeonghak Ko

**Comment by qliphy** [comment]
please test
to check again for the differences as mentioned above

**Comment by qliphy** [comment]
+1
the unrelated differences seem to be clear now

**Pull request merged**
