### PR TITLE
Fix pixel CPE position [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Rewrite the pixel CPE position calculation to improve the reproducibility of the results.

Fix the includes used in `DataFormats/TrackingRecHitSoA` to avoid the dependency on `RecoLocalTracker/SiPixelRecHits`.

Thanks to @missirol for spotitng the source of the discrepancy.

#### PR validation:

Tested on top of CMSSW 14.0.11 running the HLT over 100k events:
  - the CPU-only results are reproducible, with and without these changes;
  - the GPU vs CPU results are in general slightly more reproducible; 
  - the biggest improvement is fixing the reproducibility of `HLT_SingleEle8_v7`, going from 2% of the accepted events to being fully reproducible.

##### GPU vs CPU results, without these changes
  - +4/-5 events in `HLT_SingleEle8_v7` (2% of the accepted events)
  -  +/-4 events in  1 path
  -  +/-3 events in  2 paths
  -  +/-2 events in  6 paths
  -  +/-1 event  in 59 paths

##### GPU vs CPU results, with these changes
  -  +/-3 events in  2 paths
  -  +/-2 events in 12 paths
  -  +/-1 event  in 46 paths

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #45471 to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #45471

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
test parameters:
  - enable = gpu
  - workflows_gpu = 12634.402,12634.403,12634.404

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
