### PR TITLE
[HCAL-DQM] New plot BadQualityEvents vs all LS and changes of alarm threshold for CapID and BadQEvents for CMSSW_14_1_X

### PR DESCRIPTION
**Pull request by denizsun**
#### PR description:
  - A new plot BadQualityEvents vs all LS is added, 
  - Changes of error and warning alarm thresholds from 1 to 0.994 for both CapID and BadQEvents
 
#### PR validation:

<!-- runTheMatrix test is done

### CODE REVIEW

**Comment by abdoulline** [comment]
@denizsun 
Shouldn't it be first submitted to the master branch (14_2_X),  
and (then, or even in parallel to save time)  backported to 14_1_X ?

**Comment by denizsun** [comment]
> @denizsun Shouldn't it be first submitted to the master branch (14_2_X), and (then, or even in parallel, to save time) backported to 14_1_X ?

@abdoulline 

We contacted to Dimitri and he wrote to create 3 PRs for CMSSW 14_2_X , 14_0_15_patch1 and 14_1_X. Since we started first with 14_1_X, we will create another PRs for the other two cmssw versions. We are working on that and these two will be ready today.

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1 
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
