### PR TITLE
 Modification of cone based tau algorithm to furbish it as fallback solution for the HLT for upcoming data taking (90X version)

### PR DESCRIPTION
**Pull request by roger-wolf**
Dear colleagues, 

this is the 90X equivalent PR of https://github.com/cms-sw/cmssw/pull/18429. See comments there for reference. 

Cheers,
Roger

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test

**Comment by roger-wolf** [comment]
Hi colleagues, 

I think these tests also would need to be re-initiated as done by Slava yesterday for https://github.com/cms-sw/cmssw/pull/18429. 

Cheers,
Roger

**Comment by roger-wolf** [comment]
Sorry pressed wrong button...

**Comment by perrotta** [comment]
@cmsbuild please test
(to get rid of the failed addOn)

**Comment by mbluj** [comment]
The PR was updated to align with changes introduced to its 91X sibling #18429

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
New features needed for possible HLT development, do not modify current behaviour.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
