### PR TITLE
More L1T compat work for TSG use (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
More L1T compat work for TSG use (93X)
Based on CMSSW_9_3_X_2017-08-08-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
