### PR TITLE
drop cms type specification in SiPixel_OfflineMonitoring_cff

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

as requested [here](https://github.com/cms-sw/cmssw/pull/40873#discussion_r1118726275).

#### PR validation:

```
runTheMatrix.py -l 140.063 -t 4 -j 8
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported in https://github.com/cms-sw/cmssw/pull/40875

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by mmusich** [comment]
> please test

@emanueleusai I am afraid the tests will fail again because of https://github.com/cms-sw/cmssw/issues/40889

**Comment by perrotta** [comment]
please abort
(don't waste resources for such a simple PR: the RelVal-input tests will keep failing anyhow, as pointed out [above](https://github.com/cms-sw/cmssw/pull/40891#issuecomment-1447775737) )

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
please abort

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
