### PR TITLE
Bph reco update

### PR DESCRIPTION
**Pull request by ronchese**
#### PR description:
Description:

Update of a reconstruction package used for BPH analysis; the package
is described in the twiki
https://twiki.cern.ch/twiki/bin/view/CMS/BPHReco_V2
The code currently in CMSSW official releases is obsolete, the updated 
version has been used in the past to obtained the results in DP2018_036
and now it's planned to be used for BPH DQM.
The updates are the following:
- code modernization (nullptr in place of 0, override declarations included...)
- a few bug fixes
- secondary vertices reconstruction and fit improved and refactored
- new functionalities added
- new decay channels reconstruction implemented

The update is splitted in several commits, each one improving a specific
aspect; the code resulting for each intermediate commit was tested against
compilation but not necessarily for run. Only the final version has been
tested and results validated.
No dependence on other PRs; detailed list of commits at the end.

#### PR validation:

Tests:

Full test directory with runTheMatrix.py output here:
https://cernbox.cern.ch/index.php/s/xOkaIEnE7kQ7VLs

Other tests performed processing a few events in datasets:
/Charmonium/Run2018A-PromptReco-v2/MINIAOD (with CMSSW_10_1_5)
/Charmonium/CMSSW_11_0_0_pre6-110X_dataRun2_v5_RelVal_2018A-v1/MINIAOD (with CMSSW_11_0_0_pre12)
and looking at the output.

Detailed commit list:

7efb6e4f914 Generic selectors redesigned and inlined, some code formatting fixed
5f74b94f9b3 include cleanup
dfb287a2f1b deleted constructors and operators declarations cleanup
f43a1deedde nullptr used in place of 0 and smart pointer usage improved
141edee870a virtual replaced with override in derived classes
f6555c0129a switch sequence reordered in BPHPlusMinusCandidate
dec061316a4 empty() function used to test null strings
19f483e6406 selection stopped at first fail in BPHRecoBuilder
7c47ec24106 template declarations format fixed
4d5591dbe08 different vertex fitters allowed in BPHDecayVertex
b136586146b pointer downcasts fixed
c76b5a532f6 clone() function added
88057a9f5ba electron ctf tracks included
fd5cdb464d7 unconstrained kinematic fit added
6959d11e257 direct access to top particle in KinematicTree added
861b7aebc14 KinematicParticle building refactored
4c410fda471 kinematic fit in cascade decays refactored
fe040a0a707 constrained kinematic fit refactored
bb4eb643b40 separate fit of flying cascade decays implemented
22e5fc57943 function order matched in interface and implementation
6a2b572d40e particle collections handling in BPHRecoBuilder fixed
de11fd46943 header file includes moved to separate wrapper files to ease porting
11fa35e8716 basic selections updated
c147c7ca4d3 generic decay builders added
206d7a03926 specific decays reconstruction updated
6bf92cda541 new decay channels added

### CODE REVIEW

**Comment by santocch** [comment]
please test

**Comment by santocch** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
