### PR TITLE
Apply clang-format to FWCore/Framework

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

Apply clang-format to FWCore/Framework

#### PR validation:

none yet - its only whitespace but...

### CODE REVIEW

**Comment by smuzaffar** [comment]
+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26398/1554973957

**Comment by smuzaffar** [comment]
-code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26398/1554974409

- Found files with invalid states:
  - fatal: bad object e38c373d4d4335d15e50bdbce782ca9197608049


Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26398/1554974409/code-checks.patch
e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26398/1554974409/code-checks.patch | patch -p1`

You can also run `scram build code-checks` to apply code checks directly

**Comment by davidlange6** [comment]
hi @Dr15Jones - should I close this?

**Comment by Dr15Jones** [comment]
@davidlange6 please close this. My intention is to have Core apply the formatting changes ourselves once two large pull requests are integrated.

**Pull request closed without merging**
