### PR TITLE
bsunanda:Run2-hcx98 Enable possibility of running GEN-SIM for some 2017 geometry and choosing Plan0/1/36 at DIGI-RECO level

### PR DESCRIPTION
**Pull request by bsunanda**
Apply the effect of neutral density filter if TestNumbering is enabled. So if GEN-SIM is done with TestNumbering, one can choose separate grouping with different neutral density filter

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@civanch Could you please approve this?

**Comment by civanch** [comment]
@bsunanda the PR is fine but there are few unusual differences in 21234.0 and 23234.0 WFs in HCal. ARe they expected?

**Comment by bsunanda** [comment]
@civanch There was a bug which is relevant for Phase I detector for HB/HE overlap region. So there may be some difference in the comparison plot. Also use of testNumbering in GEN-SIM and DIGI step was not handled correctly earlier but that effect will be seen only for mixed geometry mode (so called Plan-1)

**Comment by civanch** [comment]
+1
@bsunanda , these differences are in Phase-2 workflows, hope indeed improved

**Comment by kpedro88** [comment]
@bsunanda will this code cause a problem if DIGI-RECO is run on GEN-SIM which already had the layer0wt applied?

**Comment by kpedro88** [comment]
hold

**Comment by kpedro88** [comment]
https://github.com/cms-sw/cmssw/blob/CMSSW_8_2_0/Geometry/HcalCommonData/data/PhaseII/hcalSimNumbering.xml#L87 implies this could cause a problem for Phase2 production

**Comment by bsunanda** [comment]
@kpedro88 This is a self consistent set for GEN-SIM and DIGI-RECO. If any GEN-SIM is done with earlier code surely it will do the correction yet again at DIGI level. Only way to avoid this by introducing a flag which is by default true and for this redoing DIGI for earlier GEN-SIM sample to false. I am wondering if one needs this complication

**Comment by kpedro88** [comment]
We can't afford to screw up tracker TDR production, and remaking phase2 GEN-SIM is not on the table. Either we need a protection for this, or the PR can't go in pre3.

**Comment by bsunanda** [comment]
@kpedro88 I made those checks and current setting is like old times (make correction of neutral density filter at SIM step and not at DIGI step). I shall change defaults later when we put in Plan-1 configuration

**Comment by bsunanda** [comment]
@cmsbuild Please test
@kpedro88 Please unhold this

**Comment by kpedro88** [comment]
unhold

**Comment by bsunanda** [comment]
@ianna @civanch Could you approve this again? I have taken care of Kevin's objections

**Comment by civanch** [comment]
@bsunanda , in HcalDDDSimConstants.cc line 68: "-fioff" is the fix?

**Comment by bsunanda** [comment]
@civanch Yes it is a bug fix - but this part of the code is not used in the usual flow (fioff=0 for full detectors)

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@davidlange6 Could you merge this because Plan-1 version will be based on that IB?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
