### PR TITLE
[L1T][DQMOffline] Tau DQM updates (CMSLITDPG-590)

### PR DESCRIPTION
**Pull request by kreczko**
Fixing issue https://its.cern.ch/jira/browse/CMSLITDPG-590:
 - Error bars for efficiency plots. Possibly via the DQMGenericClient module (see muon harvesting). https://its.cern.ch/jira/browse/CMSLITDPG-579
 - Drop “events” y axis label for efficiency plots.
 - Review binning for 2D L1 vs. offline pT plots and normalise to the bin size.
    - Can keep the binning for now but the bin content should be normalised to the bin area. With the normalisation "(normalised to bin area)" should be added to the histogram title.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by smuzaffar** [comment]
please test
cms-bot had an issue with unittests, this should be fixed now.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by kreczko** [comment]
@davidlange6 rebased

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
now that the master points to 10_3_X you might also want to make a PR to the 10_2_X branch.

**Comment by andrius-k** [comment]
+1

**Pull request merged**
