### PR TITLE
Fix Inactive DOHM carriers with DD4hep

### PR DESCRIPTION
**Pull request by ghugo83**
This is to smoothen the number of volumes between DDD and DD4hep.

This removes **unnecessary extra logical volumes (DOHM carriers)**, created with DD4hep for **TIB inactive materials parts**. 
This also fixes **the children physical volumes (DOHM prim / aux)**.

The extra logical volumes with DD4hep were stemming down from internal implementation of **DNamespace::addVolumeNS, which just returns the logical volume provided as argument** ( https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/DDCMS/src/DDNamespace.cc#L161 ).
Instead, **DDNamespace::volume binds any duplicate logical volume to the already existing one** (https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/DDCMS/src/DDNamespace.cc#L208 ). 
Hence, in DD4hep, whenever a logical volume already exists, **DDNamespace::volume should be used.**

Instead, the way duplicated logical volumes are avoided in DDD is as follows.
The logical volumes are always created once only, as nodes of a graph. Whenever any existing logical volume is used for a new placement: an extra edge to the already existing logical volumes nodes is simply added, containing the placement information: https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/Core/src/DDCompactViewImpl.cc#L40

@civanch @cvuosalo @ianna

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
Comparison differences are just the statistical fluctuations caused by the desired change in the geometry.

**Comment by qliphy** [comment]
+1

**Pull request merged**
