### PR TITLE
New ceros id ros status mask

### PR DESCRIPTION
**Pull request by fcavallo**
title says it all

### CODE REVIEW

**Comment by slava77** [comment]
-1

wrong development branch

**Comment by slava77** [comment]
-1
it looks like either the branch is wrong or something else similar has happened.
This PR needs to be updated or closed and moved to a correct development branch.

**Comment by deguio** [comment]
-1

**Comment by diguida** [comment]
-1
This PR does not compile, and is not mergeable too.

**Comment by ggovi** [comment]
-1

**Pull request closed without merging**
