### PR TITLE
[12.3.X] Fix SiPixel Layer 1 efficiency calculation 

### PR DESCRIPTION
**Pull request by mmusich**
backport of #37778

#### PR description:

Following https://github.com/cms-sw/cmssw/pull/35058 a few fixes/changes in L1 efficiency calculation/hit classification are introduced: reject `TrajectoryMeasurements` w/o pixel hit, fix min.distance calculation and filling of the inactive hits, initialize valid/missing/passcuts_hit for each loop iteration.

Changes expected in L1 efficiency and hit classification.

#### PR validation:

Matrix run, no issue.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of https://github.com/cms-sw/cmssw/pull/37778

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
type bug-fix

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Fix to DQM already merged in master since CMSSW_12_4_X_2022-05-08-2300

**Pull request merged**
