### PR TITLE
[Backport] nanoDQMIO in one shot

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Backport of PRs #41196 and #41375

#### PR validation:

Same as in PRs above

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
backport of  https://github.com/cms-sw/cmssw/pull/41375
(just indicate the newest of the two backported PRs, to set the label)

**Comment by rappoccio** [comment]
@emanueleusai can we get a signature on this to get it into the next 13_0_X?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
