### PR TITLE
[124X backport] [GSF tracking] Add TSOS only if it is meaningful

### PR DESCRIPTION
**Pull request by swagata87**
This is a backport of https://github.com/cms-sw/cmssw/pull/39256, as requested by @fwyzard in https://github.com/cms-sw/cmssw/pull/39256#issuecomment-1233378004 

Related github issue: https://github.com/cms-sw/cmssw/issues/39234

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
