### PR TITLE
Fix HLT path selection and BaselineValidator module addition for HI

### PR DESCRIPTION
**Pull request by arossi83**
SiStrip Online DQM client setup for HI. All the changes affect only online (the SiStripBaselineValidator plugin is used only online).

### CODE REVIEW

**Comment by arossi83** [comment]
@mmusich FYI

**Comment by mmusich** [comment]
Ciao @arossi83, can you make also a PR for master?

**Comment by mmusich** [comment]
@icali FYI

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
backport of #25083

**Comment by fabiocos** [comment]
+1

**Pull request merged**
