### PR TITLE
improved printouts and G4 destruction

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Several misprints and improvements are added, which are useful for debugging. 

From destructors of Geant4 interface classes removed operations to destruct Geant4 - this should be performed in endRun methods called by the Framework. Should address #30863.

This PR should not affect any result.

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
no backport expected

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
