### PR TITLE
Check for null histogram in PlotAlignmentValidation

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes a compiler error when compiling with debug on.

#### PR validation:

Compiling under CMSSW_13_0_DBG_X_2022-12-08-2300 no longer issues an error.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_0_DBG_X

**Comment by tvami** [comment]
+alca
 * std CMSSW passes, the DBG still sees some more things to do

**Comment by perrotta** [comment]
+1

**Pull request merged**
