### PR TITLE
DAQ file broker client (10_1_X)

### PR DESCRIPTION
**Pull request by smorovic**
Backport of #23944 (10_3_X)
Client implementation for new DAQ File Broker protocol

Tested in DAQ production HLT based on CMSSW_10_1_7 (and is remaining deployed for MD2 period).

### CODE REVIEW

**Comment by mommsen** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
backport of #23944

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23948	660ad17
- the backport is correct (comparing to https://github.com/cms-sw/cmssw/pull/23944	4c7f2cd : only some of the removed code in EventFilter/Utilities/src/FedRawDataInputSource.cc differs by ```const&``` in two catch arguments; the changes are identical to the changes in the 102X version https://github.com/cms-sw/cmssw/pull/23947	09f835c
). The code changes are not really related to reco and do not affect the standard workflows tested offline.
- jenkins tests pass

**Pull request merged**
