### PR TITLE
[DD4hep] Remove unused PPS materials from Run 3 2021 (replaces #36163)

### PR DESCRIPTION
**Pull request by cvuosalo**
The file `Geometry/VeryForwardData/data/CTPPS_Pixel_2021/Modules/v2/ppstrackerMaterials.xml` contains PPS materials that are not used anywhere, as far as I can tell. Some of the composite materials are defined in the wrong order, which could cause problems in the future. It is planned to require that all components of a composite material be defined before the material itself is defined, but we can't make that change as long as there are existing composite materials defined in the wrong order. The PPS materials in this file are the only materials in the Run 3 geometry that are defined in the wrong order. Since they are not even used, it is fairly simple to just remove them.

Another unused material `PPS_Epoxy` is deleted from the `RP_Materials.xml` file in this PR.

After this PR, a new big XML file will be created and uploaded to the DB.

This PR is replaces #36163.

A late addition to this PR is a correction to the ordering of the materials in the `pixbarmaterial.xml` files for the reduced material scenarios. The materials "Polyurethane" and "SupplyTubeEpoxy" were referenced before being defined. The fix is just to move the definitions prior to the references in the file. This fix was made earlier in the main `pixbarmaterial.xml` file but did not get into the reduced material versions of that file until now.

PR validation:

The DD4hep XML workflow, 11634.911, was run successfully with this PR.

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@diemort Please check this PR to see if I made the PPS changes correctly.

**Comment by civanch** [comment]
+1

**Comment by diemort** [comment]
@cvuosalo these changes are fine with me.

**Comment by perrotta** [comment]
@cvuosalo 
> After this PR, a new big XML file will be created and uploaded to the DB.

Let me check if I'm understanding the plan correctly:
- You wait for this PR to be merged before creating the "big XML file", and uploading it in the DB
- Therefore, we should expect another PR with an updated GT within a day or two after this one gets merged: after that we will cut pre3 and close development for the 12_2_X cycle.

Is that correct?

**Comment by perrotta** [comment]
+1
- (Thank you @cvuosalo )

**Comment by tvami** [comment]
AlCa PR submitted in https://github.com/cms-sw/cmssw/pull/36326

**Pull request merged**
