### PR TITLE
made double em enrichment filter parameters tracked

### PR DESCRIPTION
**Pull request by andreh7**
as a follow-up to #22980, this pull request has the following changes:
* removed unused parameter maxEvents (still existed but was -- apart from a warning message -- ignored)
* made physics related parameters in PythiaHepMCFilterGammaGamma tracked parameters (these were untracked before)
* added parameter descriptions in =PythiaHepMCFilterGammaGamma.h= (and more comments on the algorithm in =PythiaHepMCFilterGammaGamma.cc=). I was considering implementing = fillDescriptions()= but since this filter does not inherit from =EDFilter= this method would not be used as far as I understood.

(mentioning @pgrash since he may be interested in seeing how this pull request progresses).

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@alberto-sanchez @andreh7 how was this practically tested? I mean, the change is straightforward, but was a workflow using this PR run? Furthermore, I assume this is for the future, not for backporting (as it changes the provenance)

**Comment by alberto-sanchez** [comment]
I am not aware on any  workflow

**Comment by fabiocos** [comment]
+1

**Comment by andreh7** [comment]
thanks for merging this !

Some checks have been done in the context of #22980 which was the first time this filter algorithm was used with a generator other than PYTHIA while this pull request here is merely about making the parameters tracked and adding comments to the code describing what the parameters do.

The presentation in an H -> gamma gamma meeting by @gourangakole is here: https://indico.cern.ch/event/754287/contributions/3143029/

**Pull request merged**
