### PR TITLE
Bugfix for mass-window cut in HLTMuonDimuonL3Filter

### PR DESCRIPTION
**Pull request by vjmastra**
#### PR description:

PR to fix the bug in HLTMuonDimuonL3filter.cc
The module allows selection of separate mass windows for dimuon candidates, 
but only the first mass window is considered because of the bug.
This affects for instance the HLT path HLT_DoubleMu4_LowMassNonResonantTrk_Displaced,
using [1.0, 2.9] U [4.0, 4.8]
Events in the windows other than the first are now considered

#### PR validation:

A trigger path for non resonant dimuons has been used for test
(config file: /afs/cern.ch/user/v/vmastrap/public/fix-dimu-mass-windows/hlt.py)
and run on EphemeralHLTPhysics dataset
(file list: /afs/cern.ch/user/v/vmastrap/public/fix-dimu-mass-windows/list_cff.py)
Events in the second mass window fire the trigger after the bug fix
(plot: /afs/cern.ch/user/v/vmastrap/public/fix-dimu-mass-windows/plot.pdf)

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Tagging Muon-HLT contacts: @JanFSchulte @khaosmos93

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
@vjmastra, please improve the PR title, for example with "Bugfix for mass-window cut in `HLTMuonDimuonL3Filter`". Thanks.

**Comment by JanFSchulte** [comment]
@missirol I case this is needed: As Muon HLT contacts we endorse this PR and thank the authors for finding and fixing this bug.

**Comment by missirol** [comment]
Thanks, @JanFSchulte ; I just wanted to make sure MUO was in the loop.

**Comment by missirol** [comment]
The filter in question could use a cleanup to at least improve code readibility.
Otoh, I prefer not to delay the integration of this bugfix for purely technical changes (the latter could be done in a future PR).

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
