### PR TITLE
add `makeTrackValidationPlots` test unit

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

As it seems that this crucial script for the tracking validation and development gets frequently broken (see  https://github.com/cms-sw/cmssw/issues/35827 and https://github.com/cms-sw/cmssw/issues/35225) I provide here some unit test that should make sure that it's not unintentionally left broken.

#### PR validation:

The unit test run locally

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by jfernan2** [comment]
+1
Thanks for this UnitTest @mmusich

**Comment by qliphy** [comment]
+1

**Pull request merged**
