### PR TITLE
Update EDM inputs to HLT-Validation tests [`9_4_X` only]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is specific to the `CMSSW_9_4_X` release cycle.

Some of the HLT-Validation tests running in IBs started to fail due to the unavailability of EDM files used as input to these tests (see [IB dashboard](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_9_4_X), and https://github.com/cms-sw/cmssw/issues/40013).

This PR updates the path to these files, ~~to use copies kept in the TSG area on EOS.~~ which will now rely on the cms-bot cache (see discussion in https://github.com/cms-sw/cmssw/issues/40013 and #40020, where the corresponding updates to `cms-bot` are also mentioned).

In addition, it disables the HLT-integration-tests part of the HLT-Validation tests for scram-archs in SLC6, which are incompatible with the most recent version of ConfDB-v2 (see https://github.com/cms-sw/cmssw/issues/40013#issuecomment-1326250032).

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/pull/40030#issuecomment-1325478219.

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/issues/40013#issuecomment-1326250032.

**Comment by missirol** [comment]
+hlt

This PR fixes the HLT-Val tests currently failing in `9_4_X` IBs (access EDM files from cms-bot cache + disable HLT-integration tests in SLC6).

The update of 1 input file of the `addOnTests` requires the signature of @cms-sw/core-l2 .

**Comment by missirol** [comment]
@smuzaffar , sorry but we are still missing a Core-Sw signature here and in #40028 (these PRs are basically identical to one signed in #40030).

**Comment by smuzaffar** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
