### PR TITLE
added GenLumiInfoProduct for a posteriori cross-section calculation

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by monttj** [comment]
@covarell I might have missed the discussion. Could you add a brief description of this PR? and Do you have an estimation of the file size increase? @gpetruc @arizzi

**Comment by covarell** [comment]
I understood @bendavid had already provided size estimates to @gpetruc and this was considered OK

**Comment by bendavid** [comment]
The dataformat is 12 doubles + 10 ints (and since it's a lumi product, for unskimmed MC that's 1 object per ~200 events).  So I would say the size is negligible.

**Comment by gpetruc** [comment]
The back of the envelop estimate looks ok, but for safety can somebody
re-run miniAOD out of some MC sample to check? (30-50k events should
suffice, our usual benchmark is TTbar so you could try
/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v2/AODSIM
or
/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM

Does the 200 events per lumi hold also in samples with low filter
efficiency (e.g.
/QCD_Pt-20toInf_MuEnrichedPt15_TuneCUETP8M1_13TeV_pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/AODSIM
<https://cmsweb.cern.ch/das/request?input=dataset%3D%2FQCD_Pt-20toInf_MuEnrichedPt15_TuneCUETP8M1_13TeV_pythia8%2FRunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1%2FAODSIM&instance=prod%2Fglobal>
) ?

    Giovanni

**Comment by bendavid** [comment]
Yes, the production system takes the matching*filter efficiency into account when setting number of events per lumi, so it's ~200events/lumi after matching and filtering.

**Comment by covarell** [comment]
Hi Giovanni, I did this test:
SIZE WITHOUT GENLUMIINFO
-rw-r--r--. 1 covarell zh 294296017 22. Jul  17:38 miniAOD-prod_PAT.root

**Comment by covarell** [comment]
SIZE WITH GENLUMIINFO
-rw-r--r--. 1 covarell zh 294492192 22. Jul  19:11 miniAOD-prod_PAT.root

The increase is only 0.7 permille on the ttbar event size.

**Comment by gpetruc** [comment]
Ok, looks fine for me.

   Giovanni

On Wed, Jul 22, 2015 at 7:14 PM, Roberto Covarelli <notifications@github.com

**Comment by covarell** [comment]
@monttj can we merge this (and the corresponding PRs for 74X and 75X)? We would like to have this in for the possible re-miniAOD campaign

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
