### PR TITLE
Remove PhysicsTools/MXNet (cms-sw/cmssw#30432)

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2 , following the https://github.com/cms-sw/cmssw/issues/30432 issue, this PR drops the `PhysicsTools/MXNet` package. Can you please review this?

**Comment by mandrenguyen** [comment]
There are some differences in the comparisons, e.g.
[here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_1_X_2023-04-19-2300+0797a7/56597/validateJR/23634.0_TTbar_14TeV+2026D95/all_RECO_step3/c_recoJetedmRefToBaseProdTofloatsAssociationVector_pfDeepCSVJetTags_probudsg_RECO_obj_data_111.png)

There's no PR description, but following the issue pointed to by @smuzaffar I was not expecting to see any differences at all.  Is that the wrong expectation?

**Comment by smuzaffar** [comment]
please test

let me re-run the tests

**Comment by smuzaffar** [comment]
https://github.com/orgs/cms-sw/teams/reconstruction-l2 , following the https://github.com/cms-sw/cmssw/issues/30432 issue, this PR drops the PhysicsTools/MXNet package. Can you please review this?

**Comment by perrotta** [comment]
+1

**Pull request merged**
