### PR TITLE
Adding Number of RecHits on Strip Stereo Modules

### PR DESCRIPTION
**Pull request by mascioti**
#### PR description:
Adding Number of RecHits on Strip Stereo Modules on the Tracker DQM

#### PR validation:

runTheMatrix.py -l 12434 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be backported to 13_0_X

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by sroychow** [comment]
A backport to 13.1 is also needed.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
