### PR TITLE
[GEM] GEMGeometryBuilder update for the 2024 geometry

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

* The GE2/1 demonstrator was installed at the beginning of Run 3.
* At the beginning of the year, we installed the 2 GE 2/1 production chambers on the other region of the demonstrator.
* @bsunanda made the GEM geometry for 2024. (#43876).
* On the testing for the new geometry, the demonstrator is not built with the new 2 production chambers.
* This PR allows the building of the demonstrator with the 2 new chambers.

#### PR validation:

* `scram b code-format` and `scram b code-checks` are applied
* The built geometry has been tested with `GEMGeometryAnalyzer`

@watson-ij

### CODE REVIEW

**Comment by watson-ij** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , is it enough to enable extra GEM station?

**Comment by bsunanda** [comment]
I am waiting to make a new scenario once I put up a version for the new RPC
________________________________

**Comment by civanch** [comment]
+1

@yeckang , please, try to make a backport of this PR to 14_0

**Comment by civanch** [comment]
@srimanob , please, review this PR

**Comment by srimanob** [comment]
@yeckang what do I expect from this PR? No change in any workflow?

Note that, @cms-sw/alca-l2 @cms-sw/pdmv-l2 PR test have not moved to 2024. Should it be moved? For example, https://github.com/cms-sw/cmssw/pull/43876 is XML of 2024, so we did not really test it until we have it in GT. Thx.

**Comment by saumyaphor4252** [comment]
> Note that, @cms-sw/alca-l2 @cms-sw/pdmv-l2 PR test have not moved to 2024. Should it be moved? For example, https://github.com/cms-sw/cmssw/pull/43876 is XML of 2024, so we did not really test it until we have it in GT. Thx.

We'll start updating the GT as soon as we have the tags/payloads from @bsunanda

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Converging with @civanch that this PR can be signed. No change is expected, but @yeckang please confirm.

**Comment by yeckang** [comment]
@srimanob I don't expect any changes from any workflow.
I will prepare the backport.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
