### PR TITLE
FWCore/Utilities : Changes needed to run scripts on macOS with SIP enabled

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@gartung , would it make sense to have this logic in separate file and import in these scripts?

**Comment by gartung** [comment]
Agreed. Do I put the scriptlet in the same directory and add include scriptlet?

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
hi @gartung @Dr15Jones - is this still relevant?

**Comment by gartung** [comment]
I guess not.

**Comment by gartung** [comment]
Actually this pull request is relevant if you want to run these scripts  with SIP enabled. It has nothing to do with using spack as the package build system.

**Comment by davidlange6** [comment]
Let's continue in 91

**Pull request closed without merging**
