### PR TITLE
added taggingMode functionality for ttHFGenFilter

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear experts,

I added the functionality for the Filter in case someone wants to run over the events and just tag them instead of filtering.

Please have a look at the code!

Kind regards,
Andrej

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
Hello @all,

could you please check this PR? Please also let me know, if something is wrong with it.

Kind regards,
Andrej

**Comment by fabiocos** [comment]
please test

**Comment by Andrej-CMS** [comment]
Dear @all,

All test seems be to successful. Is there anything more that you need from me in order to merge the PR?

Kind regards,
Andrej

**Review by fabiocos — COMMENTED** [review]
What is the purpose of the final OR? To tag any event regardless of pass and save it for an offline study?

**Comment by Andrej-CMS** [comment]
@all
 
Could you please check this PR again? There seem to be no issues, so is there something that is preventing the merge.

@fabiocos 

Yes, you are right. This is a common feature in all gen-filters.

**Comment by fabiocos** [comment]
+1

**Comment by missirol** [comment]
Hi, sorry for the late follow-up on this old PR. Would it be okay to backport this change to 94X?

**Pull request merged**
