### PR TITLE
New CondFormats/GBRForest package

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

To address issue https://github.com/cms-sw/cmssw/issues/23030.

The GBRForest classes are so general that they don't really belong to the CondFormats/EgammaObjects package. This PR suggests to split off a GBRForest package from the former EgammaObjects package.

In a followup PR, the remaining EgammaObjects package could be removed, because all other classes except for the GBRForest are unused. I think we can't do both steps in one PR, because deleted CondFormats packages are not correctly "poisoned", and the GBRForest symbols are found in 2 different places then. That's at least the problem I had in the matrix tests.

#### PR validation:

CMSSW compiles, local matrix tests pass.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by santocch** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/db-l2: files in this PR are moved from CondCore/EgammaPlugins and CondFormats/EgammaObjects, currently in the "db" area, to CondCore/GBRForestPlugins and CondFormats/GBRForest. If you agree with this PR (as reco does, but we are kind of "observers" here), will you also take care of assigning CondCore/GBRForestPlugins and CondFormats/GBRForest to the "db" category?

**Comment by guitargeek** [comment]
Any chance this will move forward?

**Comment by christopheralanwest** [comment]
Since CondFormats/EgammaObjects also requires a signature from AlCa http://cms-sw.github.io/categories.html, a signature from AlCa should also be required for CondFormats/GBRForest.

I will sign off for AlCa once @ggovi signs for DB. Does https://github.com/cms-sw/cms-bot/blob/master/categories_map.py need to be updated prior to sign-off to remove the "new package pending" flag or the update to the category map typically done just after the PR is merged?

**Comment by perrotta** [comment]
Happy new year! I'm restarting going through the still open PR

@guitargeek : there is a conflict to fix, now...
@cms-sw/db-l2: could you please have a look, so that we can move forward before a new conflict shows up

**Comment by guitargeek** [comment]
Happy New Year to you too! I just pushed the rebase.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Trying to speed up... I created https://github.com/cms-sw/cms-bot/pull/1462 to assign the new packages to @cms-sw/db-l2 and @cms-sw/alca-l2

**Comment by ggovi** [comment]
+1

**Comment by christopheralanwest** [comment]
+alca

**Comment by perrotta** [comment]
+1
- Changes in the reco code only reflect the relocation of the GBRForest files in the new packages
- Jenkins tests pass and show no differences: the changes observed in nanoAOD tables in wf 1325.81 for DeepTaus are those also described in issue #32628, and not related to this PR

**Comment by guitargeek** [comment]
Hi @santocch, could you please sign before this has to be rebased again? The PR touches many files, so the risk is high.

**Comment by perrotta** [comment]
> Hi @santocch, could you please sign before this has to be rebased again? The PR touches many files, so the risk is high.

@qliphy @silviodonato 
Maybe the analysis signature can be bypassed here, since the only think they have to acknowledge is the change of address of header files already included in the analysis code

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
