### PR TITLE
Fix ambiguous comparision in HcalDcsMap

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Applies fix fox https://github.com/cms-sw/cmssw/issues/42355 suggested by @Dr15Jones 

#### PR validation:

Local compilation shows no warnings

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_13_3_CPP20_X

**Comment by iarspider** [comment]
The warnings are gone, and the other failures are expected due to overall state of cpp20 IBs

**Comment by iarspider** [comment]
please test

let's also test for default IBs

**Comment by tvami** [comment]
+1
 * technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
