### PR TITLE
Hcal Parameters Payload Object Type

### PR DESCRIPTION
**Pull request by ianna**
- Introduce new payload object type for Hcal parameters

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@ggovi - Please, check what else is needed to upload the payloads - DropBox rejected them with an exception:
```
Payload type "PHcalParameters" is unknown.
```
Thanks.

**Comment by ggovi** [comment]
Hi Yana,
 the changes of this PR should be sufficient for the DropBox.

**Comment by ianna** [comment]
@ggovi - if it is all what's needed is there any reason why it's not signed yet? Do you need to update DropBox for this? Thanks.

**Comment by ianna** [comment]
@ggovi - is there any problem with this PR? Thanks.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
