### PR TITLE
Make dumpPython handle inf and nan

### PR DESCRIPTION
**Pull request by Dr15Jones**
The configurations could already handle float('inf') and float('nan'). Now dumpPython methods have been expanded to properly print parsable versions of those numerics.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar not sure what is really tested by the short matrix here, but the tests seem stuck, could you please "encourage" them?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
