### PR TITLE
Fix for FastSim L1T (73X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
This PR should fix, for 73X, the L1T-FastSim issues reported here:
https://hypernews.cern.ch/HyperNews/CMS/get/relval/3378.html

74X needs a somewhat different PR, which I'll do next....

### CODE REVIEW

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
