### PR TITLE
Precedence order fix in FormulaEvaluator

### PR DESCRIPTION
**Pull request by Dr15Jones**
This fixes a precedence order evaluation problem seen in another pull request.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25622	22e8816
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences. The bugfixes are essential for the code which is not yet in production.

**Comment by fabiocos** [comment]
+1

**Comment by perrotta** [comment]
Analysis signature is missing: an explicit "merge" is needed

**Comment by fabiocos** [comment]
merge

**Pull request merged**
