### PR TITLE
Update a few MC Gts in autoCond to the latest version available on 14/10/2024

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

The following GTs are updated in autoCond (in some cases they are not yet the final ones, but they can be tested as such in the IBs).

- `phase1_2022_realistic` : [140X_mcRun3_2022_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2022_realistic_v10)
  - Difference with previous version in confDB (v9) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022_realistic_v11/140X_mcRun3_2022_realistic_v9) and it comprises:
     - Update Tracker alignment (same as the one for the 2023 MC, as for https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/41) and the corresponding BeamSpot (see https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/45)
     - Update (fix) the SiStripBadComponents tag as for https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/47
- `phase1_2023_realistic`: [140X_mcRun3_2023_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2023_realistic_v7)
   - Difference with previous version in confDB (v6) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023_realistic_v7/140X_mcRun3_2023_realistic_v6) and it comprises:
      - Update the SiStripBadComponents tag as for https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/47
- `phase1_2024_realistic`: [140X_mcRun3_2024_realistic_v26](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2024_realistic_v26)
   - Difference with previous version in confDB (v25) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v26/140X_mcRun3_2024_realistic_v25) and it comprises:
      - Fix the `EcalLaserAPDPNRatios_2024_outliers_cleaned_3sigma_mc` with the correct `EcalLasrtAPDPNRatiosRcd` (while it had been previously wrongly uploaded in the `EcalLaserAPDPNRatiosMCRcd`)
- `phase1_2024_realistic_hi`: [141X_mcRun3_2024_realistic_HI_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun3_2024_realistic_HI_v8)
   - Difference with previous version in confDB (v5) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_HI_v8/141X_mcRun3_2024_realistic_HI_v5) and it comprises:
      - Update L1T menu to L1Menu_CollisionsHeavyIons2024_v1_0_5_xml, see https://cms-talk.web.cern.ch/t/gt-mc-update-of-l1t-menu-v1-0-0-in-pbpb-mc-gt-for-14-1-x/51295/13
      - Update tags to synchronize with the pp ref MC, see https://cms-talk.web.cern.ch/t/gt-mc-update-of-l1t-menu-v1-0-0-in-pbpb-mc-gt-for-14-1-x/51295/8
- `phase1_2024_realistic_ppRef5TeV`: [141X_mcRun3_2024_realistic_ppRef5TeV_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun3_2024_realistic_ppRef5TeV_v5)
   - Difference with previous version in confDB (v4) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_ppRef5TeV_v5/141X_mcRun3_2024_realistic_ppRef5TeV_v4) and it comprises:
      - Fix the `EcalLaserAPDPNRatios_2024_outliers_cleaned_3sigma_mc` with the correct `EcalLasrtAPDPNRatiosRcd` (while it had been previously wrongly uploaded in the `EcalLaserAPDPNRatiosMCRcd`)
- `phase2_realistic`: [141X_mcRun4_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun4_realistic_v3)
   - Difference with previous version in confDB (v2) is [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun4_realistic_v3/141X_mcRun4_realistic_v2) and it comprises:
      - Remove geometry tags to address a reported source of confusion caused by geometry mismatch crashes due to Phase 1 ideal simulation / reconstruction geometry present in the Phase 2 GTs, see https://cms-talk.web.cern.ch/t/mc-request-for-updates-to-the-phase2-realistic-gt/51430/6

Backports to CMSSW_14_1_X and CMSSW_14_0_X (limitately to the relevant GTs) wil be provided

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
please test for CMSSW_14_2_DBG_X

**Comment by perrotta** [comment]
I would be curious to understand why 2024 MC workflows show differences in tracking (e.g. generalTracks in [wf 12834.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-10-14-1100+be2eca/65094/validateJR/12834.0_TTbar_14TeV+2024/all_RECO_step3/)) when the only difference between the GTs used for them in reference and PR produced samples is the EcalLaserAPDPNRatios tag, see [here](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v26/140X_mcRun3_2024_realistic_v25) the diff wrt the 2024MC GT in autoCond in the reference IB. 

If someone has an explanation I would be happy to hear about it. On the other hand, since the GT update is quite simple and clear, I would be tempted to approve this PR nonetheless.

**Comment by mmusich** [comment]
> If someone has an explanation I would be happy to hear about it.

differences look widespread and compatible with a randomizing effect from regenerated random number sequences in the digitization step. I see that `EcalLaserAPDPNRatiosRcd` is used in the DIGI step as well in simulation in this [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/AlCaDBHLT2023#Table_of_conditions_for_Run_3_MC) - which I think explains why the tag used in the digitization should be compatible with the one used in reconstruction.

**Comment by perrotta** [comment]
> > If someone has an explanation I would be happy to hear about it.
> 
> differences look widespread and compatible with a randomizing effect from regenerated random number sequences in the digitization step. I see that `EcalLaserAPDPNRatiosRcd` is used in the DIGI step as well in simulation in this [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/AlCaDBHLT2023#Table_of_conditions_for_Run_3_MC) - which I think explains why the tag used in the digitization should be compatible with the one used in reconstruction.

It makes sense, indeed. Thank you Marco.

**Comment by perrotta** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
