### PR TITLE
[12_3_X] simple RECO squence for SPLASH runs

### PR DESCRIPTION
**Pull request by pmandrik**
#### PR description:
For the beam SPLASH runs simplification of RECO sequence is proposed in order to speed up event processing in Event Display DQM clients. As simplified sequence is needed only for SPLASH runs, not for regular 'cosmic' and 'beam operation', the customization in visualizationProcessing function is applied when beamSplashRun option is True.

#### PR validation:
Tested locally, to be tested at P5 in production using on-going runs.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
backport of https://github.com/cms-sw/cmssw/pull/37624
for ongoing operation at P5

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
Uhm, I did not realize that this PR was not in the master.
@pmandrik could you please make a master version of it now: it will be merged in the reverse order, but ok this seems safe enough not to require to revert this 12_3_X PR (provided that its master version is made available as soon as possible)

**Comment by perrotta** [comment]
backport of #37624

**Pull request merged**
