### PR TITLE
Re-adding 2016-2017 Cosmic WFs

### PR DESCRIPTION
**Pull request by boudoul**
This branch is re-adding the 2016-2017 Cosmic WFS  - The filter  is the usual one : filtering within the tracker volume, so that cosmic muons can cross the entire tracker Volume (and not only the Pixel volume like in the SP case)  
For 2016 I used the previous cosmic GTs defined in autocond which I believe was the one used in MC prod at that time but kept maintained: run2_mc_cosmics  , but we would need the final confirmation from @lpernie and @tocheng .

WF to be tested here : 7.21 7.22  (resp 2017, 2016)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
please test workflow 7.20,7.21,7.22

**Comment by fabiocos** [comment]
@slava77 this addresses your request

**Comment by fabiocos** [comment]
@lpernie @tocheng could you please confirm that the used GT here is the right one?

**Comment by lpernie** [comment]
Hello @fabiocos , this PR is pointing to the auto:run2_mc_cosmics which points to 103X_mcRun2cosmics_startup_deco_v1 in autocond.
This v1 GT, as all other 2016 GTs, has an incorrect ECAL PF threshold tag. This TAG has been fixed in #25256

**Comment by fabiocos** [comment]
@lpernie thank you, but apart for the problem that will be fixed by your additional PR the GT  is confirmed

**Comment by fabiocos** [comment]
@prebello @zhenhu @kpedro88 do you have objections/comments or can we move this PR forward?

**Comment by lpernie** [comment]
Yes

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
+1

no objections.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
