### PR TITLE
Remove the explicit dependency on non-alpaka main library

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Remove the explicit dependency of alpaka libraries on the non-alpaka main library, since this is now enabled by default in the 15.0.x branch.

#### PR validation:

Unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@slava77 is there some specific test we should run for the LST part, or is it enough that is builds correctly ?

**Comment by ariostas** [comment]
> is there some specific test we should run for the LST part, or is it enough that is builds correctly ?

I think it's enough that it builds correctly.

**Comment by slava77** [comment]
> @slava77 is there some specific test we should run for the LST part, or is it enough that is builds correctly ?

we have the following workflows included:
24834.704 GPU
24834.703 CPU

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
[fwyzard](https://github.com/fwyzard) looks like a conflict popped up

**Comment by fwyzard** [comment]
Curious that #46857 was merged without any review by @cms-sw/heterogeneous-l2 , considering that most of the comments it should address were from the @cms-sw/heterogeneous-l2 review.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
