### PR TITLE
Remove AnalysisDataFormats/SiStripClusterInfo and AnalysisDataFormats/Egamma packages plus dependent code

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

There was some old electron ID code hiding in the DataFormats. It was used in some DQM, where the code was actually inactive, and a class in the PatTools. This class was not used anywhere and is therefore also on the list. @Sam-Harper, since you seem dedicated to do some cleanup on behalf of egamma for 11X anyway (thanks a ton!), this will be my last PR of this sort so I won't interfere with your work.

On the side, I'm also removing the AnalysisDataFormats/SiStripClusterInfo package as it was consisting of literally just one line.

#### PR validation:

CMSSW compiles and matrix tests pass.

### CODE REVIEW

**Comment by pohsun** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for Utilities/ReleaseScripts changes

**Comment by pohsun** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26528	a93be64
- code changes are in line with the PR description; essentially trivial
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by andrius-k** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by Sam-Harper** [comment]
Thanks Jonas! So this was definitely on the hit list as it had blown up in my face a week ago, also the reason you now have to rebase ;(   

> @Sam-Harper, since you seem dedicated to do some cleanup on behalf of egamma for 11X anyway (thanks a ton!), this will be my last PR of this sort so I won't interfere with your work.

Oh dont let me stop you :) Although we should coordinate better. It'll be a little while till I get to it.  All this clean up you've been doing is very much appreciated :)

**Comment by fabiocos** [comment]
@guitargeek after the integration of #26485 the BuildFile that you remove was modified, and this induced the merge conflict above (trivial as you anyway want to delete the code). Could you please fix it so as we may merge this PR?

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> On the side, I'm also removing the AnalysisDataFormats/SiStripClusterInfo package 

It would be good this shows in the PR title as well.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26528	e059b65
- changes since the last reco signoff for a93be64 are almost trivial (a rebase)
- jenkins tests pass

**Comment by pohsun** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones I assume this is ok for your for the next IB...

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
