### PR TITLE
use `onlineMetaDataDigis` when available for retrieval of average PU in `AlCaHOCalibProducer`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR addresses one of the worst offenders in terms of `LogError` emissions recently collected at https://github.com/cms-sw/cmssw/issues/41456. 
As the title says, use `onlineMetaDataDigis` when available for retrieval of average online PU in `AlCaHOCalibProducer` (lumiscalers were decommisioned at the beginning of Run-3).
See https://github.com/cms-sw/cmssw/issues/41456#issuecomment-1530967785 and following for more details.
 
#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but a backport to 13.0.X would be desireable

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by francescobrivio** [comment]
Thanks a lot Marco for this!
I'd be ready to sign it, but should we hear the opinion of HCAL experts @bsunanda @abdoulline?

**Comment by francescobrivio** [comment]
type hcal

**Comment by tvami** [comment]
+alca
 * the PR is technical in the sense it accesses the same info as earlier (but through the `rcd` instead of the event)
 * one question to HCAL experts here https://github.com/cms-sw/cmssw/pull/41486#discussion_r1182594980 should be followed-up

**Comment by mmusich** [comment]
what's preventing this to be merged?

**Comment by abdoulline** [comment]
@bsunanda   could you, please take a look (together with Gobinda?)

**Comment by perrotta** [comment]
+1
- Please @bsunanda have a look at https://github.com/cms-sw/cmssw/pull/41486#discussion_r1182594980

**Pull request merged**
