### PR TITLE
[10_6_X] Adding TkAlMaps (tracker map plots for alignment validation)

### PR DESCRIPTION
**Pull request by SenneVanPutte**
#### PR description:

Adding the tracker map plots.
Tracker alignment independent version of TkMap, now able to plot phase1 tracker.
Meant to compare two alignments by visualising the physical relative displacements.

#####################

backport of #31376

### CODE REVIEW

**Comment by mmusich** [comment]
@SenneVanPutte PRs should be submitted first to master and once accepted backported to older releases. Can you produce a PR for master?

**Comment by SenneVanPutte** [comment]
I can try, but the All-In-One implementation is ment for the old version of it. I will see if it is compatible with the master

**Comment by silviodonato** [comment]
backport of #31376
(to be updated)

**Comment by mmusich** [comment]
@silviodonato for my own education, once Senne removes the files from here, how is it going to work? do we need a PR on the cms-data repo against the 10_6_X branch?

**Comment by mmusich** [comment]
please test

**Comment by silviodonato** [comment]
> @silviodonato for my own education, once Senne removes the files from here, how is it going to work? do we need a PR on the cms-data repo against the 10_6_X branch?

@mmusich `cms-data` is a standalone repository. As soon as https://github.com/cms-data/Alignment-OfflineValidation/pull/1 is merged in `cms-data`, we merge an automatic pull request in `cmsdist` branch `master` and then we make another PR for `10_6_X` branch.
Example: `cms-data` PR https://github.com/cms-data/Geometry-DTGeometryBuilder/pull/1
`cmsdist` PR https://github.com/cms-sw/cmsdist/pull/6198

**Comment by mmusich** [comment]
Thanks @silviodonato 
then there is no other action needed on Senne's side, right?

**Comment by silviodonato** [comment]
> Thanks @silviodonato
> then there is no other action needed on Senne's side, right?

yes, right

**Comment by tlampen** [comment]
+alca

**Comment by silviodonato** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6245

**Comment by silviodonato** [comment]
merge

**Pull request merged**
