### PR TITLE
L1 Prefiring weight extractor (backport to 10_2_X)

### PR DESCRIPTION
**Pull request by lathomas**
Backport of https://github.com/cms-sw/cmssw/pull/25380 for 10_2_X. 
N.B. This code makes use of external files in 
https://github.com/cms-data/PhysicsTools-PatUtils
which may imply a backport of the following PR as well (?)
https://github.com/cms-sw/cmsdist/pull/4595

### CODE REVIEW

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4635

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4635

**Comment by perrotta** [comment]
backport of #25380

**Comment by perrotta** [comment]
@lathomas : to simmetrize with the PR in the master, you could profit of the new externals and remove ```pfJetResolutionMCtoDataCorrLUT.root``` from ```PhysicsTools/PatUtils/data/```
(not really relevant, due to the limited gain in size: but having it in one single repository could avoid people making possible mistakes if they want to modify those LUTs privately for their own analysis)

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4635

**Comment by perrotta** [comment]
+1
- This is an analysis tool not used by default in any official workflow, but meant for now to private analyses and eventually possibly also nanoAOD production
- Identical to #25380
- Jenkins tests pass and show no (relevant) differences
- It needs cms-sw/cmsdist#4635

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by lathomas** [comment]
Hello, 

For my education how can I check what's the first 10_2_X release with this PR integrated?
I should know that but I don't.
Thanks !

**Comment by perrotta** [comment]
@lathomas 
For reco, we also list the reco-related pull requests merged in the different releases in https://twiki.cern.ch/twiki/bin/view/CMS/RecoIntegration#Integration_Status

**Comment by fabiocos** [comment]
@lathomas you may see the release notes https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_10/CMSSW_10_2_10.html
check the integration page https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_10_2_X (for recent things) or look at the github log: 

commit 1fcd3f3f8d95fc2e1c2b105ef9d7414d6b2e6975 (HEAD -> from-CMSSW_10_2_10, tag: CMSSW_10_2_X_2019-01-22-1100, tag: CMSSW_10_2_X_2019-01-21-2300, tag: CMSSW_10_2_X_2019-01-21-1100, tag: CMSSW_10_2_X_2019-01-20-2300, tag: CMSSW_10_2_X_2019-01-20-0000, tag: CMSSW_10_2_X_2019-01-19-1100, tag: CMSSW_10_2_X_2019-01-18-2300, tag: CMSSW_10_2_X_2019-01-18-1100, tag: CMSSW_10_2_X_2019-01-17-2300, tag: CMSSW_10_2_10)
Merge: a4180687550 8b2370fbf51
Author: cmsbuild <cmsbuild@cern.ch>
Date:   Thu Jan 17 12:41:23 2019 +0100

    Merge pull request #25645 from lathomas/L1Prefiring_CMSSW_10_2_X
    
    L1 Prefiring weight extractor (backport to 10_2_X)

**Pull request merged**
