### PR TITLE
Changes to store Daughters of Kshort and Lambda in the miniAOD prunedGenParticle Collection (backport to CMSSW_12_4_X)

### PR DESCRIPTION
**Pull request by gmelachr**
Following the pull request https://github.com/cms-sw/cmssw/pull/42464, this is a new PR to backport changes in CMSSW_12_4_X.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
please test

**Comment by perrotta** [comment]
backport of #42464

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
> Is everything fine with this PR, I think the test procedure is stuck since yesterday saying "bot/42461/jenkins Pending — Waiting for authorized user to issue the test command."

Tests have finished, see https://github.com/cms-sw/cmssw/pull/42498#issuecomment-1669526029

**Comment by gmelachr** [comment]
For some reason in this PR there is still this message 

image

while for this PR there is not: 

image

I thought both PR were in the same step, but maybe they weren't?

**Comment by simonepigazzini** [comment]
there seems to be some confusion in the bot output. It mentions a comment from Marco that is actually in a different PR: https://github.com/cms-sw/cmssw/pull/42461#issuecomment-1664014485. Which should be closed but was actually reopened. 

@gmelachr please close the linked PR. Everything else here looks ok

**Comment by simonepigazzini** [comment]
+1

**Comment by simonepigazzini** [comment]
@perrotta, @rappoccio 

we will need a release to be cut from 12_4_X to allow @cms-sw/pdmv-l2 to proceed with the MC production with the fix introduced by this PR. Both L2 XPOG are away this and the coming week, can you please note this down for next Tuesday meeting? Thank you a lot.

**Comment by gmelachr** [comment]
> there seems to be some confusion in the bot output. It mentions a comment from Marco that is actually in a different PR: [#42461 (comment)](https://github.com/cms-sw/cmssw/pull/42461#issuecomment-1664014485). Which should be closed but was actually reopened.
> 
> @gmelachr please close the linked PR. Everything else here looks ok


The linked PR is now closed.

**Comment by gmelachr** [comment]
> @perrotta, @rappoccio
> 
> we will need a release to be cut from 12_4_X to allow @cms-sw/pdmv-l2 to proceed with the MC production with the fix introduced by this PR. Both L2 XPOG are away this and the coming week, can you please note this down for next Tuesday meeting? Thank you a lot.

Just for a confirmation and in order to avoid a possible delay, when you say "next Tuesday meeting" you mean Tuesday on 15th of August right?

**Comment by perrotta** [comment]
+1

**Comment by gmelachr** [comment]
A kind reminder in order to request the new releases for this PR and this one https://github.com/cms-sw/cmssw/pull/42500 tomorrow. 

Thanks, 
Giorgos

**Pull request merged**
