### PR TITLE
added EcalPFSeedingThresholds to plugins

### PR DESCRIPTION
**Pull request by argiro**
#### PR description:
complements #28324, addition of a new record
The addition of the new record to plugins.cc was overlooked

### CODE REVIEW

**Comment by argiro** [comment]
@ggovi, @cmsbuild  can you please approve this trivial fix ? thanks

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
looking at the code it should not break #28214

**Comment by fabiocos** [comment]
+1

**Pull request merged**
