### PR TITLE
Extend the definition of good cell for v17 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by Pruthvi-ch**
PR description:

Extend the definition of good cell for partial wafers in v17 version of HGCal Geometry.

PR validation:

Use the runTheMatrix test workflows

if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Kindly approve this PR

**Comment by bsunanda** [comment]
@srimanob Please approve this PR urgently

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
@Pruthvi-ch 
Please have a look at 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-410312/25097/llvm-analysis/runStaticChecks.log


/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_X_2022-05-30-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:452:89: error: use of undeclared identifier 'type'; did you mean 'true'?
  edm::LogVerbatim("HGCalGeom") << "u|v " << u << ":" << v << " N " << n << " type " << type << " rot " << rotn
                                                                                        ^~~~
                                                                                        true
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_X_2022-05-30-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:452:72: error: use of undeclared identifier 'n'
  edm::LogVerbatim("HGCalGeom") << "u|v " << u << ":" << v << " N " << n << " type " << type << " rot " << rotn
                                                                       ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_5_X_2022-05-30-2300/src/Geometry/HGCalCommonData/src/HGCalWaferMask.cc:452:108: error: use of undeclared identifier 'rotn'
  edm::LogVerbatim("HGCalGeom") << "u|v " << u << ":" << v << " N " << n << " type " << type << " rot " << rotn

**Comment by Pruthvi-ch** [comment]
This PR has been closed and the changes are incorporated into PR 38217,

**Pull request closed without merging**
