### PR TITLE
skip bad channels in `PFRecHitProducerKernelConstruct<T>::applyCuts`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a simple fix for https://github.com/cms-sw/cmssw/issues/45595 and implements the suggestion at https://github.com/cms-sw/cmssw/issues/45595#issuecomment-2259266422
Skips bad channels in `PFRecHitProducerKernelConstruct<T>::applyCuts`
- as implemented in `HcalRecHitSoAToLegacy`
- also check `denseId` validity before retrieving  the corresponding PF threshold

#### PR validation:

Run successfully the reproducer script at https://github.com/cms-sw/cmssw/issues/45595#issuecomment-2259202142.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, we might backported it if accepted. In that case we'll need an urgent patch on to of `CMSSW_14_0_13`

### CODE REVIEW

**Comment by mmusich** [comment]
assign heterogeneous

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu=12434.422, 12434.423,12434.424,12434.492

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
+1
Backport expected

**Comment by mmusich** [comment]
type pf

**Pull request merged**
