### PR TITLE
Remove trackingPhase1QuadProp era and PixelQuadrupletGenerator as obsolete

### PR DESCRIPTION
**Pull request by makortel**
The "pixel quadruplets by triplet propagation" seeding algorithm was superseded by Cellular Automaton in the spring. We don't foresee "going back", so this PR removes the tracking customization with `trackingPhase1QuadProp` era, the special workflows exercising that tracking, and the algorithm code.

Tested in CMSSW_10_0_X_2017-12-05-1100, no changes expected.

@VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
+1 as far aa TRK-POG is concerned

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
