### PR TITLE
Phase2-sim142 Add more files to investigate differences etween DDD and DD4hep versions of Phase2 geometries

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add more files to investigate differences etween DDD and DD4hep versions of Phase2 geometries

#### PR validation:

Use the scripts in SimG4Core/PrintGeomInfo/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
