### PR TITLE
2017 preparation (PU case) 

### PR DESCRIPTION
**Pull request by boudoul**
Continue to prepare worklows fro 2017 
Fixing typo (left over for SLHC release) 
Adding the right input for MinBias and TTbar for  recycling
set up the stand PU value (PU35)

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild please test

**Comment by boudoul** [comment]
Not sure I understand when the error is, let me retrigger tests

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by boudoul** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
