### PR TITLE
whitespace and print fixes towards compiling with python3

### PR DESCRIPTION
**Pull request by davidlange6**
this PR reduces the # of files that don't compile with python3 by 6x (excluding test directory files which in any case do not always compile with python2). 

Changes are to fix whitespace errors (mix of tabs and spaces is no longer allowed) 

Changes done via:
autopep8 -i --select E101,W690 <file>
$CMSSW_RELEASE_BASE/../../../external/py2-future/0.16.0/bin/futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import <file>

applied to any file that does not compile with python3

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
Hi @fabiocos - are you expecting more comments on this pr?

Cheers,
David


On 13 Aug 2018, at 10:26, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for master.

It involves the following packages:

Alignment/CommonAlignmentProducer
Alignment/MillePedeAlignmentAlgorithm
Alignment/MuonAlignment
Alignment/MuonAlignmentAlgorithms
Alignment/OfflineValidation
CalibMuon/DTCalibration
CondCore/Utilities
CondFormats/Serialization
Configuration/Applications
Configuration/PyReleaseValidation
DQM/Integration
DQM/SiStripMonitorClient
DQMOffline/Trigger
HLTrigger/Tools
HLTriggerOffline/Exotica
PhysicsTools/Heppy
PhysicsTools/HeppyCore
PhysicsTools/PatAlgos
PhysicsTools/PatUtils
PhysicsTools/PythonAnalysis
RecoEgamma/Configuration
RecoLuminosity/LumiDB
RecoVertex/BeamSpotProducer
SUSYBSMAnalysis/HSCP
SimG4Core/CustomPhysics
SimGeneral/Configuration
SimGeneral/MixingModule
SimMuon/RPCDigitizer
SimTracker/Configuration
SimTransport/HectorProducer
TauAnalysis/MCEmbeddingTools
Utilities/RelMon
Utilities/ReleaseScripts
Utilities/StaticAnalyzers
Validation/Geometry
Validation/Performance
Validation/RecoB
Validation/RecoTau
Validation/Tools

@andrius-k<https://github.com/andrius-k>, @schneiml<https://github.com/schneiml>, @ianna<https://github.com/ianna>, @kpedro88<https://github.com/kpedro88>, @fabozzi<https://github.com/fabozzi>, @Martin-Grunewald<https://github.com/Martin-Grunewald>, @pohsun<https://github.com/pohsun>, @arizzi<https://github.com/arizzi>, @perrotta<https://github.com/perrotta>, @civanch<https://github.com/civanch>, @silviodonato<https://github.com/silviodonato>, @zhenhu<https://github.com/zhenhu>, @cmsbuild<https://github.com/cmsbuild>, @fwyzard<https://github.com/fwyzard>, @GurpreetSinghChahal<https://github.com/GurpreetSinghChahal>, @davidlange6<https://github.com/davidlange6>, @smuzaffar<https://github.com/smuzaffar>, @Dr15Jones<https://github.com/Dr15Jones>, @mdhildreth<https://github.com/mdhildreth>, @jfernan2<https://github.com/jfernan2>, @tocheng<https://github.com/tocheng>, @slava77<https://github.com/slava77>, @ggovi<https://github.com/ggovi>, @fabiocos<https://github.com/fabiocos>, @prebello<https://github.com/prebello>, @kmaeshima<https://github.com/kmaeshima>, @arunhep<https://github.com/arunhep>, @monttj<https://github.com/monttj>, @pgunnell<https://github.com/pgunnell>, @franzoni<https://github.com/franzoni>, @gpetruc<https://github.com/gpetruc>, @lpernie<https://github.com/lpernie> can you please review it and eventually sign? Thanks.
@echabert<https://github.com/echabert>, @TaiSakuma<https://github.com/TaiSakuma>, @gouskos<https://github.com/gouskos>, @felicepantaleo<https://github.com/felicepantaleo>, @jainshilpi<https://github.com/jainshilpi>, @schoef<https://github.com/schoef>, @rappoccio<https://github.com/rappoccio>, @HeinerTholen<https://github.com/HeinerTholen>, @fioriNTU<https://github.com/fioriNTU>, @thomreis<https://github.com/thomreis>, @tlampen<https://github.com/tlampen>, @ahinzmann<https://github.com/ahinzmann>, @lgray<https://github.com/lgray>, @abbiendi<https://github.com/abbiendi>, @mmusich<https://github.com/mmusich>, @seemasharmafnal<https://github.com/seemasharmafnal>, @venturia<https://github.com/venturia>, @pakhotin<https://github.com/pakhotin>, @mmarionncern, @smoortga, @hdelanno, @calderona, @makortel, @threus, @acaudron, @jhgoh, @varuns23, @jdolen, @prolay, @HuguesBrun, @drkovalskyi, @ferencek, @trocino, @rociovilar, @Sam-Harper, @GiacomoSguazzoni, @rovere, @VinInn, @jdamgov, @nhanvtran, @gkasieczka, @tocheng<https://github.com/tocheng>, @jandrea, @mschrode, @idebruyn, @ebrondol, @mtosi, @dgulhan, @clelange, @Martin-Grunewald<https://github.com/Martin-Grunewald>, @batinkov, @swertz, @battibass, @gbenelli, @wddgit, @JyothsnaKomaragiri, @mverzett, @cbernet, @gpetruc<https://github.com/gpetruc>, @imarches, @mariadalfonso, @pvmulder, @folguera this is something you requested to watch as well.
@davidlange6<https://github.com/davidlange6>, @slava77<https://github.com/slava77>, @fabiocos<https://github.com/fabiocos> you are the release manager for this.

cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-cmds.html>

**Comment by fabiocos** [comment]
+operations

the changes in the Configuration area are consistent with the purpose of the PR, and the diff -b/-w shows that differences affect only whitespaces

**Comment by fabiocos** [comment]
+1

@kpedro88 as far as I can see the changes in this PR are consistent with the declared purpose and simple enough to move forward

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade
(posthumously, just to express my great appreciation for unifying the indentation)

**Pull request merged**
