### PR TITLE
Pixel Material Budget Changes

### PR DESCRIPTION
**Pull request by schneiml**
Another set of changes for the Pixel Phase1 Material Budget.

- For FPIX, 290um instead of 300um sensor thickness (value measured at FNAL). This change will affect positions of the senstive volumes, even if it is just a few um.

- For BPIX (thanks @zucchett )
   - Correct material for Flange4. This significantly increases the mass of this volume, the old material was incorrect. 
   - Changs to densities to match measurements at PSI
   - Changes to the Sector D shield material.

The renaming in 171f8856dbeaf0e2090725aac6dbc3 might affect Phase2. We could omit this but actually we should really just make sure that Phase1 and Phase2 are independent.

The changes to the material budget are validated to be in the expected range. No new overlaps are created.
Sensor positions change by 5-10um in FPIX.
@veszpv

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - please, note that https://github.com/cms-sw/cmssw/pull/17156 is still pending integration

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Hi @ianna - in hopes of keeping the xml and the gt in sync, what are your plans for getting #17209 #17199 #17156 #17115 into a payload for a new gt? Can we converge on that for pre3?

**Comment by ianna** [comment]
@davidlange6 - I think, it's your call. I was hoping to have all the PRs in an IB since the've been signed for a while now. I can certainly bundle them together without an IB for a GT if that's your preference. I'm giving a short status to AlcaDB on Monday

**Comment by schneiml** [comment]
Superseded by #17245 .

**Pull request closed without merging**
