### PR TITLE
Trim FastjetJetProducer memory (forward port #9203)

### PR DESCRIPTION
**Pull request by mark-grimes**
This forward ports some memory improvements found in 6_2_X_SLHC.  At 200 pileup it saved ~70Mb memory, there are plots on #9203.  Presumably at lower pileup the savings aren't as good.

Note that this is from empirically checking where the memory was being used - there could be other subclasses of `VirtualJetProducer` that would benefit from a similar fix.  I didn't want to touch the `fjClusterSeq_` object in the base class because I didn't know how the other subclasses use it - for FastjetJetProducer I can see that it's recreated anew with every event.

At 200 pileup 1/7th of the memory saving was from swapping out the work vectors, and 6/7th was from freeing the `fjClusterSeq_` object.

@rappoccio, @lgray

### CODE REVIEW

**Comment by rappoccio** [comment]
This is a good cleanup anyway, so I think it should be included in 75x also.

Cheers,
Sal

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@mark-grimes: Static analyzer flags line 64 of VirtualJetProducer.cc for having a non-const static:

const char *VirtualJetProducer::JetType::names[]

It should be:

const char *const VirtualJetProducer::JetType::names[]

If you can quickly make the change, it might be nice to fix just to get rid of the static analyzer message. This issue could also be fixed in a later PR.

**Comment by mark-grimes** [comment]
Made static `names` a const as requested.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
new IB CMSSW_7_5_X_2015-05-23-1100 is in and seems ok at least on the build side

**Comment by cvuosalo** [comment]
+1

For #9206 927422cfd89c76492b040b29c6839ca90ba2259c

Reduces memory usage by clearing some FastJetProducer objects after they are no longer needed. No change in monitored quantities should occur. #9210 (already approved) is the 74X version of this PR.

The code changes are satisfactory, as are the Jenkins tests. Tests with workflow 25202.0_TTbar_13 against baseline CMSSW_7_5_X_2015-05-20-2300 using 50 events show no significant differences. Similar tests for #9210 show the same. Memory usage seems to go down slightly:

CMSSW_7_5_X_2015-05-20-2300
Summary for 50 events (sizes in MB)
Max VSIZ 3740.59 on evt 33 ; max RSS 3099.75 on evt 28

#9206
Summary for 50 events
Max VSIZ 3719.09 on evt 33 ; max RSS 3086.58 on evt 28

**Comment by davidlange6** [comment]
+1

**Pull request merged**
