### PR TITLE
reverts #44054 and  #44389

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Executing plan as per https://github.com/cms-sw/cmssw/pull/44054#issuecomment-2006798459

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+hlt
   * verbatim undo of #44054 and #44389

**Comment by perrotta** [comment]
+alca
- Following the decision taken at the Joint Ops meeting

**Comment by mmusich** [comment]
@cms-sw/l1-l2 your signature is required.

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
