### PR TITLE
[121X] Add label for SiPixelQualityRcd in RawToDigi 

### PR DESCRIPTION
**Pull request by tsusa**
#### PR description:

See description at #36255 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #36255 

Needed for ReReco of Pilot Run

### CODE REVIEW

**Comment by tsusa** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca

**Comment by francescobrivio** [comment]
urgent

**Comment by francescobrivio** [comment]
backport of #36255

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36286	c2985b6 
- code changes are the same as in #36255, which was already merged
- jenkins tests pass (the added code is not active in the PR tests)

**Comment by francescobrivio** [comment]
>     * jenkins tests pass (the added code is not active in the PR tests)

thanks @slava77! As soon as we have the final tag I will create a GT and activate the modifier in the PR tests!

**Comment by francescobrivio** [comment]
@perrotta @qliphy this is basically fully signed, only missing your signature 😄

**Comment by tsusa** [comment]
> > ```
> > * jenkins tests pass (the added code is not active in the PR tests)
> > ```
> 
> thanks @slava77! As soon as we have the final tag I will create a GT and activate the modifier in the PR tests!

@francescobrivio  for the test I have used 139.002, with the following change in cmsDriver for step3 

cmsDriver.py step3_procModiff --conditions 122X_dataRun3_Candidate_2021_11_28_01_19_18 -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@rerecoZeroBias+@ExtraHLT+@miniAODDQM --datatier RECO,MINIAOD,DQMIO --eventcontent RECO,MINIAOD,DQM --data --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 -n 100 --filein file:step2.root --fileout file:step3_withModifier.root --no_exec --python_filename step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM_withModifier.py --procModifier siPixelQualityRawToDigi

**Comment by francescobrivio** [comment]
> @francescobrivio for the test I have used 139.002, with the following change in cmsDriver for step3
> 
> cmsDriver.py step3_procModiff --conditions 122X_dataRun3_Candidate_2021_11_28_01_19_18 -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@rerecoZeroBias+@ExtraHLT+@miniAODDQM --datatier RECO,MINIAOD,DQMIO --eventcontent RECO,MINIAOD,DQM --data --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 -n 100 --filein file:step2.root --fileout file:step3_withModifier.root --no_exec --python_filename step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM_withModifier.py --procModifier siPixelQualityRawToDigi


@tsusa sounds good thanks! once we have the final tag I will add this customization!

@mmusich @slava77 at the moment for 2021 pp data we have MinBias, ZeroBias and HLTPhysics wfs (139.001/002/003) do you think we should apply this customization to all of them?

**Comment by tvami** [comment]
@francescobrivio I think MinBias was fine, but it's definitely a yes for ZeroBias and HLTPhysics

**Comment by mmusich** [comment]
> at the moment for 2021 pp data we have MinBias, ZeroBias and HLTPhysics wfs (139.001/002/003) do you think we should apply this customization to all of them?

@francescobrivio as I thought I had already explained via private chat, there is no physics reason not to apply the customization everywhere. 
The surge in the number of fake tracks is mostly evident in ZeroBias and HLTPhysics, because a vast fraction of the events in those datasets are empty and the FPix noise hits are the *only* hits from which to make tracks. 
MinimumBias contains a much higher relative fraction of collision events with real tracks in them, thus lowering the probability of associating noise hits, though the effect is still somewhat visible. Before moving on with MinimumBias as well - though - it would be better to check if there are any adverse effects on the real tracks that might be passing through the masked ROCs. For that as explained at the last AlCa/DB meeting a suitable payload for the unlabeled flavour (consumed during track reconstruction) is needed.  Once that's available a more thorough validation can be done.

**Comment by perrotta** [comment]
+1
- Identical to the corresponding PR, succesfully merged in master since CMSSW_12_2_X_2021-11-30-1100
- Expected to be used in the the ReReco of Pilot Run data

**Pull request merged**
