### PR TITLE
Test GT Queues: Extended 2018 without Totem

### PR DESCRIPTION
**Pull request by ianna**
* Update conditions to test Extended 2018 scenarios without Totem

@arunhep - update of the scenarios was discussed at Friday's sim meeting. The agreement was to remove Totem as it's no longer installed. This PR is for test purposes only to speed up the integration. 

@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
@fabiocos - this PR should not be merged, but replaced by a subsequent GT update one.

**Comment by ianna** [comment]
@civanch - please, check if the differences in the 2018 scenario workflow are as expected:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-03-18-2300+22659/25707/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/

**Comment by civanch** [comment]
@ianna , @fabiocos , it is expected that simulation history changed when Totem T1 and T2 detectors are taken out. For small statistic runs the difference may be substantial. For high statistic run one should not expect big difference in HF. I would guess the difference may be smaller than that due to PR #22145. But this is a reality: detectors mechanically removed from the beam.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by ianna** [comment]
AlCaDB will open a PR soon in master.

**Pull request closed without merging**
