### PR TITLE
LLP GenFilter based on transverse displacement and pdgId - backport #37669 

### PR DESCRIPTION
**Pull request by Raffaella07**
###PR description:
The filter selects particles based on transverse displacement (by means of a lower and/or upper cut) and pdgIds.
The filter is developed for searches of long lived HNLs in B meson decays (@rmanzoni @pandolf @amlyon)

The filter is included in the /plugins subdirectory of GeneratorInterface/GenFilters .

###PR validation:
Filter behavior can be tested in the test subdirectory of GeneratorInterface/GenFilters through the module test_MCLongLivedFilter_cfg.py

Backporting https://github.com/cms-sw/cmssw/pull/37669

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by SiewYan** [comment]
@smuzaffar , sorry if this has been asked many time..

could you point me to the instruction/documentation on how to trigger user addOn test, for example trigger this ```test_MCLongLivedFilter_cfg.py``` with cms-bot command?

thanks..

**Comment by smuzaffar** [comment]
@SiewYan , bot runs all tests which are mentioned in `cmssw/Subsystem/Package/test/Buildfile.xml`. If you need to run `cmsRun test_MCLongLivedFilter_cfg.py` then please add `GeneratorInterface/GenFilters/test/BuildFile.xml` which following contents
```
<test name="test_MCLongLivedFilter_cfg" command="cmsRun $${SCRAM_TEST_PATH}/test_MCLongLivedFilter_cfg.py"/>
```

**Comment by SiewYan** [comment]
@Raffaella07 , could you use @smuzaffar 's advice on your PR, add the mentioned line on top of your PR? I will re-trigger the test. The test result is needed for the record.

Thanks!

**Comment by SiewYan** [comment]
> @SiewYan , bot runs all tests which are mentioned in `cmssw/Subsystem/Package/test/Buildfile.xml`. If you need to run `cmsRun test_MCLongLivedFilter_cfg.py` then please add `GeneratorInterface/GenFilters/test/BuildFile.xml` with following contents
> 
> ```
> <test name="test_MCLongLivedFilter_cfg" command="cmsRun $${SCRAM_TEST_PATH}/test_MCLongLivedFilter_cfg.py"/>
> ```

Thank you @smuzaffar , i will keep that in mind.

**Comment by perrotta** [comment]
> @Raffaella07 , could you use @smuzaffar 's advice on your PR, add the mentioned line on top of your PR? I will re-trigger the test. The test result is needed for the record.
> 
> Thanks!

Well, I'd rather do it in the master, so that it will get propagated to all future releases.
For the backports it is enough to confirm that it runs when it is merged, by running the script by hand just once

**Comment by SiewYan** [comment]
+1

Thanks, I'll sign this off then. @Saptaparna

**Comment by perrotta** [comment]
+1

**Comment by Saptaparna** [comment]
Thanks, Siewyan!

**Pull request merged**
