### PR TITLE
Run2-sim19 Enable G4GEOM_USE_USOLIDS to use VecGeom library

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , code check finds out many problem in this class. It should fix all automatically, if you locally do 'scram build code-checks'

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @davidlange6 The failure has nothing to do with this PR

**Comment by bsunanda** [comment]
@civanch Can you approve this now?

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
