### PR TITLE
Add DQM for 90m run observables [101X backport]

### PR DESCRIPTION
**Pull request by JanFSchulte**
Backport of #23629 

This PR modifies the Online DQM to monitor the special pixel cluster and track collections used in the 90m beta star run. To be rolled back after this run is over.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@fabiocos 
I think we should make a special 90m CMSSW 10_1 release for this.

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@JanFSchulte @fabiocos 
No activity on this for a week - if no longer needed, please close this PR!

**Pull request closed without merging**
