### PR TITLE
Move TF session in L1Trigger/L1NNTauProducer to global cache

### PR DESCRIPTION
**Pull request by riga**
#### PR description

This PR adapts the `L1NNTauProducer` and `TauNNId` helper object in `L1Trigger` to use a single, const tensorflow session stored in the global cache. For this, it's using the central `SessionCache` struct introduced in #40284.

This is part of the planned changes documented in #40248, intended to treat all tf sessions as constant for model evaluation purposes and therefore preventing copies across stream module instances for saving memory.

#### PR validation

There was no new functionality added to the `L1NNTauProducer`, so existing test cases should fully cover the changes.

@clacaputo @yongbinfeng @valsdav

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade
Technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
