### PR TITLE
EMTF three fixes to unpacking and emulation bugs, 10_1_X back-port

### PR DESCRIPTION
**Pull request by abrinke1**
Back-port of https://github.com/cms-sw/cmssw/pull/23136

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #23136

**Comment by fabiocos** [comment]
@abrinke1 @thomreis as far as I can see the modified DataFormat is a transient one, not part of any persistent data tier, do you confirm? Furthermore, besides MC tests in the IB, how has been this code verified?

**Comment by thomreis** [comment]
Yes, the data format is transient.
For the testing @abrinke1 has the details.

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
