### PR TITLE
HLT tools: improve support for ConfDB v2 (updated)

### PR DESCRIPTION
**Pull request by fwyzard**
- use prebuilt Java binaries (backport of #15928)
- add subtables supprt for ConfDB v2 (backport of #15922)

Includes #15836 (backport of #15837)
- update documentation
- fix choice of ConfDB v2 by default
- add support for the schema and database to hltIntegrationTest --setup

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
