### PR TITLE
add cfg for l1tstage1 dqm running on live

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@jingyucms - it looks like your code and python are inconsistent. Could you have a look?

**Comment by deguio** [comment]
-1
correct. the same applies to #9500
rejecting for now.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
