### PR TITLE
SIM muon filter 71X backport

### PR DESCRIPTION
**Pull request by kskovpen**
71X backport for #20209 to use this new filter in MC production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi @kskovpen @civanch - what is an example cmsdriver command that runs this filter?

**Comment by kskovpen** [comment]
@davidlange6 the filter can be run with --step FILTER:SimMuon/MCTruth/SimMuFiltSingle_cff.SimMuFiltSeq (single muon filter) or --step FILTER:SimMuon/MCTruth/SimMuFiltDouble_cff.SimMuFiltSeq (double muon filter) on top of GEN-SIM (G4 hits)

**Comment by davidlange6** [comment]
+1

**Comment by dlont** [comment]
In which release this PR will be integrated?

**Pull request merged**
