### PR TITLE
Add more `fillDescriptions` to `Alignment/OfflineValidation` plugins

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a companion of https://github.com/cms-sw/cmssw/pull/40695, in which a `fillDescptions` method is added to few other plugins. These changes are proposed separately because in order to profit of `fillPSetDescription` methods used in auxiliary classes in other subsystems, this PR will trigger reconstruction and simulation signatures.

#### PR validation:

Relies on the existing unit tests:

 `scram b runtests`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * relevant unit tests pass

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
