### PR TITLE
Remove all nanoV10 workflows

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

Remove the left-over nanoAOD v10-frozen workflows forgotten in #40321, fix issue reported in https://github.com/cms-sw/cmssw/pull/40321#issuecomment-1378782477

### CODE REVIEW

**Comment by swertz** [comment]
code-checks

**Comment by swertz** [comment]
please test

**Comment by smuzaffar** [comment]
please test
lets run the tests for failing workflows too

**Comment by perrotta** [comment]
type bugfix

**Comment by perrotta** [comment]
urgent

**Comment by perrotta** [comment]
+1
- Previously failing run3 nanoAOD workflows can finish without errors with this fix
- @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 let me bypass your signature to have the IB clean in master, but please feel free to comment or propose different solutlons even after this PR gets merged

**Comment by perrotta** [comment]
merge

**Comment by srimanob** [comment]
Hi @perrotta 

As a question in https://github.com/cms-sw/cmssw/pull/40321#issuecomment-1378810922, should we consider to add 2022 data workflow to runTheMatrix? So it can be tested at every PR test, and spot any issues before we reprocess it.
We currently have only 2021 wf, which I think they will be less use, for physics analysis, compared with 2022.

https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L77-L79

**Comment by perrotta** [comment]
> Hi @perrotta
> 
> As a question in [#40321 (comment)](https://github.com/cms-sw/cmssw/pull/40321#issuecomment-1378810922), should we consider to add 2022 data workflow to runTheMatrix? So it can be tested at every PR test, and spot any issues before we reprocess it. We currently have only 2021 wf, which I think they will be less use, for physics analysis, compared with 2022.
> 
> https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L77-L79

I fully agree.
We can either add the 2022 workflows, or just replace the 2021 ones with them, which is probably better if we want to keep the short matrix short

**Pull request merged**
