### PR TITLE
Moved modules.py out of edmWriteConfig

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- is now a file in the template directory
- modification of scram  will use the new file and place in the correct directory.

#### PR validation:

Code compiles. Needs change to scram to fully test.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@smuzaffar  FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar looks like other PR tests are failing in the same way.

**Comment by valsdav** [comment]
The change on the ONNX version was merged yesterday in https://github.com/cms-sw/cmsdist/pull/9046
at 15:00.  Here it is using IB `CMSSW_14_1_X_2024-03-13-1100`. Don't we have to refresh the tests?

**Comment by smuzaffar** [comment]
@Dr15Jones , we need to wait for newer IB. PR tests here are picking up https://github.com/cms-sw/cmssw/pull/44354 for an IB which has old ONNXRuntime. 

Last night's 23h IB is still in build phase for production arch. It will take few more hours as it has to build many externals

**Comment by makortel** [comment]
The "next IB" CMSSW_14_1_X_2024-03-13-2300 does not seem to be available for el8_amd64_gcc12 yet

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw-config#104 for el9_amd64_gcc12

lets test it for available arch

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw-config/pull/104

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@smuzaffar Just to clarify, are the scram-side changes already in? I.e. this PR can safely be merged?

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by smuzaffar** [comment]
> @smuzaffar Just to clarify, are the scram-side changes already in? I.e. this PR can safely be merged?

yes, scram side changes are alreay in.

**Comment by makortel** [comment]
+core

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
