### PR TITLE
Fixed memory leak in TrackerSimHitProducer

### PR DESCRIPTION
**Pull request by skurz**
This issue is addressed in #23795 
-> Removed memory allocation with `new` and replaced it with a unique pointer.

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by skurz** [comment]
I don't think this is related to my PR?

**Comment by fabiocos** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
