### PR TITLE
Fix L1T MuonShowers for HLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix L1T MuonShowers for HLT
Change in uGT repack file fixes issue https://github.com/cms-sw/cmssw/issues/37482

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of bug fix #37502

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
backport of #37502

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@fabiocos, @davidlange6 please sign for operations

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
Ok, by mistake I merged the 12_3_X version before the master one.
I don't expect problems with it, anyhow: let it as such, no need to revert while waiting for the master version being tested in the IBs (we can still revert just in case of unexpected issues there)

**Pull request merged**
