### PR TITLE
[13_2_X] Run3 era for 2023 PbPb UPC re-reco

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of [#43378](https://github.com/cms-sw/cmssw/pull/43378) which creates a new era "Run3_2023_UPC" meant for the 2023 PbPb UPC re-reco.

#### PR validation:

Relval workflow 141.901 and private (documented in [slides](https://docs.google.com/presentation/d/1nK3r-i3EwV0YvkpJQb--lPLivD1NCmBTG-XZr__Xr0o/edit?usp=sharing))

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport from master (14_0_X) to 13_2_X

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please abort

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by srimanob** [comment]
+Upgrade

**Comment by vlimant** [comment]
+1

**Comment by stahlleiton** [comment]
@cms-sw/pdmv-l2 please review/sign this PR

**Comment by stahlleiton** [comment]
@cms-sw/pdmv-l2 would you kindly review/sign ?

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Comment by antoniovilela** [comment]
@smuzaffar 
Hi Shahzad,
Do you understand why this PR was not automatically merged after all the signatures?
Thanks.

**Comment by smuzaffar** [comment]
no idea but I am looking in to it @antoniovilela

**Comment by smuzaffar** [comment]
@antoniovilela , fixed now. Due to latest bot changes, bot was waiting for non-blocking `tracking` to be approved. This has been fixed now

**Comment by antoniovilela** [comment]
> @antoniovilela , fixed now. Due to latest bot changes, bot was waiting for non-blocking `tracking` to be approved. This has been fixed now

Thanks!

**Pull request merged**
