### PR TITLE
Use correct beamspot for 2016 MC + update MC tracker alignment scenario for 2016 pre-VFP era

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

The MC that has been used to simulate 2016 data so far assumes a beamspot that is appropriate for describing the beamspot of data taken in 2015 with 25 ns bunch spacing. Previously the 2016 beamspot simulation was never changed to avoid inconsistencies between 2016 MC that had already been generated and any newly generated MC. There is no such consistency requirement for the UL as it will involve the regeneration of all GEN-SIM and so we can use the correct beamspot simulation. See the news from the [12 December 2019 PPD meeting](https://indico.cern.ch/event/863633/#7-news) for details.

The global tag updates change the `BeamSpotObjectsRcd` tag to `BeamSpotObjects_Realistic25ns_13TeV2016Collisions_v1_mc` for 2016 MC scenarios. The vertex smearing used by 2016 workflows has also been updated for consistency.

It also updates the [MC tracker alignment scenario for the 2016 pre-VFP era](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4254.html).

**Global tag diffs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_design_v3/110X_mcRun2_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_preVFP_v1/110X_mcRun2_asymptotic_preVFP_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_v5/110X_mcRun2_asymptotic_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2cosmics_startup_deco_v4/110X_mcRun2cosmics_startup_deco_v5

#### PR validation:

The beamspot parameters  are explicitly listed on slide 5 of the news from the [12 December 2019 PPD meeting](https://indico.cern.ch/event/863633/#7-news) together with fitted beamspot parameters from data and MC. In addition, a technical test was performed: `runTheMatrix.py -l 7.22,limited --ibeos`. Note that no RelVal workflows use either `auto:run2_design` or `auto:run2_mc_l1stage1` (though the addOn tests use `auto:run2_mc_l1stage1`) so a similar technical test cannot be performed for these GTs.

#### if this PR is a backport please specify the original PR:

This PR is not a backport but will be backported to 11_0_X and 10_6_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test workflow 7.22

**Comment by mmusich** [comment]
@christopheralanwest thanks for this.
I have few comments:
   * indeed there is no RelVal wf which runs `auto:run2_mc_l1stage1` but there is one `addOn` test which consumes it: https://github.com/cms-sw/cmssw/blob/0d3768d63689ca8b98c9a08c206566e5eebf2bdb/Utilities/ReleaseScripts/scripts/addOnTests.py#L92  As the vertex smearing there is `NominalCollision2015` which in turn points to : https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L47 i.e. https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py#L459-L468 I am wondering if that should not be changed as well. Maybe @Martin-Grunewald can clarify what is the preference on the TSG side.
   * as for `auto:run2_design` (as it is also not exercised in any RelVal) we might take the occasion to move it to consume a really ideal BeamSpot as it is already done for the upgrade 2017 and 2018 workflows which point to `Ideal_Centered_SLHC_v3`. The dump is the following: 
image
  * the vertex smearing `Realistic50ns13TeVCollision` is used in combination with the autoCond key `run2_mc` in at least one unit test (Tau embedding):  https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/TauAnalysis/MCEmbeddingTools/test/runtests.sh#L37 After this update the consistency in that test will be broken. I am wondering if there are other cases in cmssw. 
   * last but not the least, the `Realistic50ns13TeVCollision` is used as default key https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L68 which in my understanding is used in a workflwow by the ConfigBuilder in case the Beam Spot is **NOT** specified, see https://github.com/cms-sw/cmssw/blob/7e27750861f9d80a2254a83af0d1f9f94f7f803f/Configuration/Applications/python/ConfigBuilder.py#L995
I am wondering how many cases consistency will be broken....

**Comment by christopheralanwest** [comment]
Thanks for your comments.

> @christopheralanwest thanks for this.
> I have few comments:
> 
>     * indeed there is no RelVal wf which runs `auto:run2_mc_l1stage1` but there is one `addOn` test which consumes it: https://github.com/cms-sw/cmssw/blob/0d3768d63689ca8b98c9a08c206566e5eebf2bdb/Utilities/ReleaseScripts/scripts/addOnTests.py#L92
>         As the vertex smearing there is `NominalCollision2015` which in turn points to : https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L47
>        i.e. https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py#L459-L468
>        I am wondering if that should not be changed as well. Maybe @Martin-Grunewald can clarify what is the preference on the TSG side.

In this case, I think that I should revert the change to the auto:run2_mc_l1stage1 GT but I will wait for a reply from @Martin-Grunewald.

> 
>     * as for `auto:run2_design` (as it is also not exercised in any RelVal) we might take the occasion to move it to consume a really ideal BeamSpot as it is already done for the upgrade 2017 and 2018 workflows which point to `Ideal_Centered_SLHC_v3`. The dump is the following:
>       image
> 

OK. I will make this change, unless there are any objections.

>     * the vertex smearing `Realistic50ns13TeVCollision` is used in combination with the autoCond key `run2_mc` in at least one unit test (Tau embedding):  https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/TauAnalysis/MCEmbeddingTools/test/runtests.sh#L37

It looks like this is purely a unit test and so could be changed to use the `Realistic25ns13TeV2016Collision` vertex smearing for consistency with the other 2016 workflows. @isobelojalvo @mbluj Would that be OK?

>        After this update the consistency in that test will be broken. I am wondering if there are other cases in cmssw.
> 
>     * last but not the least, the `Realistic50ns13TeVCollision` is used as default key https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L68
>        which in my understanding is used in a workflwow by the ConfigBuilder in case the Beam Spot is **NOT** specified, see https://github.com/cms-sw/cmssw/blob/7e27750861f9d80a2254a83af0d1f9f94f7f803f/Configuration/Applications/python/ConfigBuilder.py#L995
>       
>       I am wondering how many cases consistency will be broken....

Using a 2015 beamspot does not seem to be a very sensible default from a physics standpoint but if the beamspot is not specified explicitly (hopefully) that means that the choice of beamspot is not particularly relevant for that workflow and only consistency is needed. I will defer to PdmV experts on whether or not the default beamspot should be changed.

**Comment by mbluj** [comment]
> > ```
> > * the vertex smearing `Realistic50ns13TeVCollision` is used in combination with the autoCond key `run2_mc` in at least one unit test (Tau embedding):  https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/TauAnalysis/MCEmbeddingTools/test/runtests.sh#L37
> > ```
> 
> It looks like this is purely a unit test and so could be changed to use the `Realistic25ns13TeV2016Collision` vertex smearing for consistency with the other 2016 workflows. @isobelojalvo @mbluj Would that be OK?

I think that it is OK. @janekbechtel , could you confirm as embedding expert, please?

**Comment by janekbechtel** [comment]
Yes, this should be okay

**Comment by Martin-Grunewald** [comment]
Hi,

That specific addOnTest is a fastsim test, so you need to check with fastsim people...

**Comment by fabiocos** [comment]
@christopheralanwest @srimanob @pgunnell do I understand correctly that this PR is needed for the UL reprocessing? So it should be backported into 10_6_X before the final patch is made?

**Comment by christopheralanwest** [comment]
> Hi,
> 
> That specific addOnTest is a fastsim test, so you need to check with fastsim people...

@sbein @ssekmen There is a fastsim addOn test that uses the `auto:run2_mc_l1stage1` GT, which is supposed to represent late-2015 data after the L1 Stage-1 upgrade was installed. (Actually, it has a mix of 2015 and 2016 conditions). This PR initially updated the beamspot and vertex smearing for the late-2015 workflows to use the 2016 beamspot but comment https://github.com/cms-sw/cmssw/pull/28624#issuecomment-565704469 suggested that this update was inappropriate. I intend to revert the change to this workflow unless you suggest otherwise, but please comment.

**Comment by christopheralanwest** [comment]
> @christopheralanwest @srimanob @pgunnell do I understand correctly that this PR is needed for the UL reprocessing? So it should be backported into 10_6_X before the final patch is made?

Technically, I think that the GT and vertex smearing could be specified by hand, though I think that's error-prone. So it's probably better to have it backported.

There is another update, a tracker MC APE update for the 2016 pre-VFP era that was approved at the [AlCa meeting yesterday](https://indico.cern.ch/event/869999/#3-updated-tracker-mc-ape-for-t). Shall I add the APE update to this PR as otherwise the APE update would conflict with changes in this PR? Since the beamspot has been changed, the PR comparison tests are not particularly useful in any case.

**Comment by christopheralanwest** [comment]
> > 
> > * last but not the least, the `Realistic50ns13TeVCollision` is used as default key https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L68
> >    which in my understanding is used in a workflwow by the ConfigBuilder in case the Beam Spot is **NOT** specified, see https://github.com/cms-sw/cmssw/blob/7e27750861f9d80a2254a83af0d1f9f94f7f803f/Configuration/Applications/python/ConfigBuilder.py#L995
> >   
> >   I am wondering how many cases consistency will be broken....
> > ```
> 
> Using a 2015 beamspot does not seem to be a very sensible default from a physics standpoint but if the beamspot is not specified explicitly (hopefully) that means that the choice of beamspot is not particularly relevant for that workflow and only consistency is needed. I will defer to PdmV experts on whether or not the default beamspot should be changed.

@chayanit, @pgunnell @zhenhu Could you comment on whether or not the default vertex smearing should be changed as well?

**Comment by chayanit** [comment]
> > > * last but not the least, the `Realistic50ns13TeVCollision` is used as default key https://github.com/cms-sw/cmssw/blob/001ecd07d2fceae0f173a3ea169831f3171b03bb/Configuration/StandardSequences/python/VtxSmeared.py#L68
> > >   
> > >   which in my understanding is used in a workflwow by the ConfigBuilder in case the Beam Spot is **NOT** specified, see https://github.com/cms-sw/cmssw/blob/7e27750861f9d80a2254a83af0d1f9f94f7f803f/Configuration/Applications/python/ConfigBuilder.py#L995
> > >   
> > >   I am wondering how many cases consistency will be broken....
> > 
> > 
> > Using a 2015 beamspot does not seem to be a very sensible default from a physics standpoint but if the beamspot is not specified explicitly (hopefully) that means that the choice of beamspot is not particularly relevant for that workflow and only consistency is needed. I will defer to PdmV experts on whether or not the default beamspot should be changed.
> 
> @chayanit, @pgunnell @zhenhu Could you comment on whether or not the default vertex smearing should be changed as well?

@christopheralanwest , I would leave the default as it is (not part of our development) and we modify corresponding beamspot for UL2016 inside relval code.

**Comment by kpedro88** [comment]
I agree with @chayanit that it's best to isolate this kind of change to where it will be needed and used in practice (i.e. UL).

**Comment by christopheralanwest** [comment]
The changes in the last update are as follows:

- fe3f449: Revert the change to `auto:run2_mc_l1stage1`, as suggested at https://github.com/cms-sw/cmssw/pull/28624#issuecomment-565704469.
- 02a5e97: Update tau test as agreed at https://github.com/cms-sw/cmssw/pull/28624#issuecomment-565974290 and following discussion
- 7a0d99e: Use ideal beamspot for design scenario, as suggested at https://github.com/cms-sw/cmssw/pull/28624#issuecomment-565704469.
- a1be73e: Update tracker alignment for 2016 pre-VFP era. This is unrelated to the main content of this PR but since the change affects only one line and would conflict with this PR, I have included it here. I will update the title of the PR accordingly.

**Comment by christopheralanwest** [comment]
please test workflow 7.22

**Comment by christopheralanwest** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
