### PR TITLE
Castor geometry update

### PR DESCRIPTION
**Pull request by meliache**
Overlap fixes and update for castor geometry.

### CODE REVIEW

**Comment by ianna** [comment]
@davidlange6 - do we want 2015 dev scenario back-ported to 73x?

**Comment by davidlange6** [comment]
no need to, no.

**Comment by cbaus** [comment]
@davidlange6 @ianna 
I am a bit confused about the status of this pull request now. Our aim was to end up in the GEN-SIM production for 2015. To my understanding this is already ongoing in 7_1 but I also heard, that more events will be simulated within a new production with updated conditions. In which CMSSW version does this have to be included for the new production?

@elimik31 
Did you ever put this PR (since the one here is closed) on top of #6631 ? Is this still needed for what we want?

**Comment by davidlange6** [comment]
On Jan 7, 2015, at 3:31 PM, cbaus <notifications@github.com>
 wrote:

> @davidlange6 @ianna 
> I am a bit confused about the status of this pull request now. Our aim was to end up in the GEN-SIM production for 2015. To my understanding this is already ongoing in 7_1 but I also heard, that more events will be simulated within a new production with updated conditions. In which CMSSW version does this have to be included for the new production?

the plan is to use 71x for the foreseeable future. Deadlines for geometry updates were nominally in ~April, so at this point there is a 'dev' geometry that we are including changes in case there is an opportunity to update it (and to also facilitate validation of alternative geometries needed for specific samples).

**Comment by ianna** [comment]
@cbaus - unfortunately, this PR came too late to be included in GEN-SIM production geometry which is frozen for now. I've included the changes to 2015 dev scenario in a new PR #7061

**Comment by cbaus** [comment]
OK. Thanks for both answers and for making the new pull request. Hope the error that showed up in the tests can be resolved elsewhere.

**Pull request closed without merging**
