### PR TITLE
Stacktrace handler revisited

### PR DESCRIPTION
**Pull request by bbockelm**
This is the second version of the improved stacktrace.  The first version had improper handling around forked processes (the helper thread would communicate with the wrong process).
- Ran unit tests in FWCore/Modules successfully (these failed in the first round).
- Verified stack traces are printed appropriately on SIGSEGV.
- Verified detached thread causes no problem for the non-failure case.
- Managed to send a SIGSEGV while one thread was holding the jemalloc lock; process did not deadlock.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@bbockelm did you test when forking that a crash in a child process would give a traceback?

**Comment by bbockelm** [comment]
Just tested this.  stacktrace printer works fine in the child process.

*However*, it seems that the parent gets wedged in Xrootd-land when the child SEGV's.  Doesn't appear to be related to this, however.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
