### PR TITLE
TkAlignment PV Validation tool: miscellaneous improvements

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR introduces few fixes / improvements to the Tracker Alignment PV Validation tool:
  * allow to run on remotely located files via `xrootd`
  * allow to use input files subscribed to different DAS instances than global (e.g. privately produced samples a `prod/phys03`)
  * fix few miscellaneous inconsistencies (use 48bins analysis by default, use `cms.untracked.string` for labeled records etc.)
  * allow for splitting of statistics into multiple jobs when running on data without run-based selections 
  * support 2D "thermal" maps for Layer 1 residuals and implement loosened consistency check in case of `hadd`-ed files

#### PR validation:

Relies on the existing unit tests + extensive private validation.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
Kind reminder @cms-sw/alca-l2

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
