### PR TITLE
Added isUsingModifier to Process

### PR DESCRIPTION
**Pull request by Dr15Jones**
This replaces the deprecated call to Modifier.isChosen. This interface can be supported by future improvements to the code (where Modifier.isChosen can not be).

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failure is not related to this pull request.

**Comment by Dr15Jones** [comment]
Please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
