### PR TITLE
Backport of SiPixel quality harvester for Ultra legacy

### PR DESCRIPTION
**Pull request by tocheng**
#### PR description:

The PR is to update pixel quality harvester for Run-2 ultra legacy

#### PR validation:

The PR update the bad ROC tagging by

-  using per-layer for Bpix / per-ring for Fpix average digi occupancy instead of average occupancy over the full detector
-  using layer/ring dependent fraction threshold to apply the optimized pixel quality tagging
-  further reduce redundant payloads

Pixel quality tagging are optimized with layer/ring dependent thresholds with pixel offline group.

No effect on CMSSW standard workflows.

#### if this PR is a backport please specify the original PR:

This is backport of PR #27050 

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by tocheng** [comment]
backport #27050

**Comment by tocheng** [comment]
@cmsbuild please test workflow 1001.2, 1040

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
