### PR TITLE
Fix alcareco 74x

### PR DESCRIPTION
**Pull request by shervin86**
Porting of PR 8306 to CMSSW_7_4_X
Need it asap for alcareco production for low PU runs

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test
@shervin86 please put in the description this is the backport in 7.4.X of #8306

**Comment by shervin86** [comment]
ping

**Comment by mmusich** [comment]
+1 
@boudoul @franzoni @srimanob @davidlange6 can you please review as well and sign?
P.s.: let's merge this before #8677 to avoid mege conflicts (the latter one should be rebased then)

**Comment by shervin86** [comment]
@boudoul @franzoni  @srimanob @davidlange6 
this is the backport in 7.4.X of #8306
can you please review and sign? it is very urgent now, this alcareco has to be in production for first collisions

**Comment by davidlange6** [comment]
Hi Shervin
First we need to see 750pre5 relvals with this AlCa succeeding.

**Comment by franzoni** [comment]
ping ???
pong !

**Comment by franzoni** [comment]
+1
subject to the outcome of 8306
(when something is so very urgent, feel free to make a phone call. The rate of PR's vs PdmV brain-power, as I've told you verbally, is such that pointing out can help)

**Comment by shervin86** [comment]
This PR is the porting to 74X of PR #8306 
After it has been merged in 75X the SelectedElectronFEDListProducer is not compiled as plugin any more.
The fix for 75X is in  #9256 
As discussed with AlCa I have ported the fix to this PR such that the problem is  cured. The SelectedElectronFEDListProducer has been moved from src to the plugins directory, the include of the header has been fixed accordingly and also the BuildFile.

The +1 should be straightforward :-)

**Comment by mmusich** [comment]
Hi @shervin86 can we have #9284 (from 7.5.X) also here for convenience?

**Comment by shervin86** [comment]
I will do it!

-- 
 							Shervin

**Comment by shervin86** [comment]
#9284 commit cherry-picked here as requested, there is another fix for RelVal mc that I have to do in 75X.

**Comment by mmusich** [comment]
please test

**Comment by shervin86** [comment]
I have rebased in order to solve the conflict due to another merge done in the meantime.
This PR now incudes the following:
 - porting of #8306 
 - porting of #9256  
 - porting of #9284 
 - porting of #9298 
Comments from @davidlange6 to PR #9256 can be also integrated if requested, but I would like to ask the integration of this PR as soon as possible in order to put ElectronStream and ALCARECO in production.
Eventual code fixes can be done in another PR.

**Comment by franzoni** [comment]
please test

**Comment by shervin86** [comment]
We were waiting for RelVals in 75X, are they ready? Can this be signed and merged?

**Comment by mmusich** [comment]
+1

**Comment by shervin86** [comment]
Removed the "catch" in the SelectedElectronFEDListProducer.cc as requested by David.
There are maybe still many improvements in the coding, I will consider them for another PR. Please merge and sign this PR

**Comment by mmusich** [comment]
please test

**Comment by shervin86** [comment]
Test approved, pending signatures

**Comment by mmusich** [comment]
@shervin86 do you plan to PR also the new commits (https://github.com/shervin86/cmssw/commit/a3d96c2ba3629f7c1fdf15d44f3e0e5697f9f5e2, https://github.com/shervin86/cmssw/commit/358166ed1d083751c7d2412ee3c42f74aca267fe, https://github.com/shervin86/cmssw/commit/5bb55ac7307040e5ca126ab6275767a7f95cdfcc ) in 7.5.X?

**Comment by shervin86** [comment]
yes

**Comment by diguida** [comment]
+1
Back port of the following PR:
#8306 
#9256 
#9284 
#9298 
To be moved to 75X too:
* removing `try...catch` blocks as requested in https://github.com/cms-sw/cmssw/pull/9256#issuecomment-110047905 https://github.com/shervin86/cmssw/commit/358166ed1d083751c7d2412ee3c42f74aca267fe
* consumes interface migration for `AlCaElectronsTest` https://github.com/shervin86/cmssw/commit/a3d96c2ba3629f7c1fdf15d44f3e0e5697f9f5e2
* changes in the AlCaReco event content: https://github.com/shervin86/cmssw/commit/5bb55ac7307040e5ca126ab6275767a7f95cdfcc

**Comment by shervin86** [comment]
I will do the PRs tomorrow
Can pdmv and orp sign?

**Comment by shervin86** [comment]
still pending signatures, please merge it

**Comment by davidlange6** [comment]
yelling in git won't help much - but as discussed in the ORP, I evaluated how safe this was to backport skipping the usual procedure. I don't see issues so will merge it

**Pull request merged**
