### PR TITLE
remove message from unexpected CTP7 firmware ID

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:

This PR is just to comment out two lines to remove message from unexpected CTP7 firmware ID, which is causing hassle for debugging the ongoing collisions. Functionality is not changed.

### CODE REVIEW

**Comment by asavincms** [comment]
I am not sure if my message was clear, but the line is really obsolete , we dont need it and ask to complete this PR

Sascha

**Comment by BenjaminRS** [comment]
I have implemented suggestion [(1) from my comment](https://github.com/cms-sw/cmssw/pull/35873#issuecomment-954750836) as PR #35940

**Comment by perrotta** [comment]
> I have implemented suggestion [(1) from my comment](https://github.com/cms-sw/cmssw/pull/35873#issuecomment-954750836) as PR #35940

Thank you @BenjaminRS !
Can this PR get closed, then? (Backports with this simple and tested solution can remain, instead, to be merged only if needed)

**Comment by BenjaminRS** [comment]
Hi @perrotta -- yes I think this one can be closed and #35940 would replace it for the master branch.

**Comment by perrotta** [comment]
-1
- Superseeded by the already merged #35940
- @hftsoi please close this PR

**Pull request closed without merging**
