### PR TITLE
Remove PixelMatchStartLayers class and correct GsfElectronTools namespace to lower case

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Little cleanup proposal in EgammaElectronAlgos: removing the `PixelMatchStartLayers` class as it's slightly superfluous. I also take this opportunity to correct a namespace name which I some time ago mistakenly defined as upper case: `GsfElectronToos` to `gsfElectronTools`.

#### PR validation:

Compiles and matrix tests pass.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
Thanks Jonas. One thing though, can we hold this till https://github.com/cms-sw/cmssw/pull/26485 (or similar) is in. It should merge fine but as it touches the same files, I always get nervous.

**Comment by guitargeek** [comment]
That's right, sorry! Of course there is no rush with the cleanup PRs.

**Comment by guitargeek** [comment]
Hi @slava77, this one can be signed off now when you're ready, as Sam's remaining PR https://github.com/cms-sw/cmssw/pull/26486 does not touch the same files anymore.

**Comment by perrotta** [comment]
+1
- Cleanup implemented as planned
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
