### PR TITLE
HBHE Local reco cpu

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of #22293

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22367	0a4c02d
- the backport from https://github.com/cms-sw/cmssw/pull/22293 c857b1d is correct
- this is a somewhat technical update to reduce unnecessary/repeated computations; also some cleanup of no longer used code.
    - timing profile of the offline reco shows about 5% reduction in CPU https://github.com/cms-sw/cmssw/pull/22293#issuecomment-367789478
- jenkins tests pass and comparisons with baseline show no differences.

It seems like the timing improvement here is essential enough for TSG studies to request a backport. 

@mariadalfonso @deguio is the timing improvement more significant in the full HE phase-1 case?
The igprof was made for 2017 data

**Comment by deguio** [comment]
hi @slava77 
the improvement is ~the same for HPDs and SiPMs.
if you look at the `HBHEPhase1Reconstructor::processData` method you can distinguish HPDs (`HBHEDataFrame`) from SiPMs (`QIE11DataFrame`). I see a ~3.5% and ~3% reduction respectively.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
