### PR TITLE
Phase2-hgx333C Take care of invalid SiHits for V16 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of invalid SiHits for V16 geometry of HGCal

#### PR validation:

Use the test codes in Validation/HGCalValidation/scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by srimanob** [comment]
+Upgrade

Differences are seen in V16 HGCAL geometry.

**Comment by bsunanda** [comment]
@emanueleusai, @ahmad3213 Please approve this PR. It is needed to have the right functionality of V16 geometry of HGCal which is now used in the default Phase2 scenario

**Comment by emanueleusai** [comment]
+1

- differences in upgrade WFs as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
