### PR TITLE
HCalDQM: Fix for issue #37486 collection tag correction

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

A fix for issue #37486 by replacing hbhereco with hbheprereco for relevant tasks.

#### PR validation:

Tested okay with GPU workflows 10824.523, 10824.583 and 10824.587.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by abdoulline** [comment]
@lwang046  that's what I meant, when asked:  
did you rung regular runThematrix -l limited ?
before submitting PR.  Let's get back to e-mail thread.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
enable gpu

**Comment by abdoulline** [comment]
GPU differences appeared only for  11634.506

11634.506_TTbar_14TeV+2021_Patatrack_PixelOnlyTripletsGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano/	

And only for Pixels 
https://cmsweb.cern.ch/dqm/dev/session/x6WiPV

Both ECALonly and HCALonly wfs showed no difference on GPU.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
