### PR TITLE
Small fixes to analyzers used for phase2 tracker studies

### PR DESCRIPTION
**Pull request by emiglior**

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @emiglior, I can't seem to find you in [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts). Could you please briefly introduce yourself?

**Comment by boudoul** [comment]
@emiglior is as such not a DQM developer nor a DQM contact . He's member of CMS and therefore can contribute to the code in general - Particularly he is the convener of the upgrade  simulation of the Tracker.

**Comment by emiglior** [comment]
As @boudoul mentioned  (thx) I am proposing these changes in the framework of tracker phase2 studies.
The changes in Validation/RecoVertex is to have the correct binning in case of PU200 or higher.

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by andrius-k** [comment]
+1
@boudoul @emiglior thanks a lot for clarifications.

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
