### PR TITLE
[125X] Remove tracking MVA tags from Run-3 MC and data GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/40010/
and https://github.com/cms-sw/cmssw/pull/40011/

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/40010/ and https://github.com/cms-sw/cmssw/pull/40011/

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40010/

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40011

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/40010 and https://github.com/cms-sw/cmssw/pull/40011

**Pull request merged**
