### PR TITLE
[80X] Tracker Alignment PV Validation in all-in-one tool

### PR DESCRIPTION
**Pull request by mmusich**
Backport of #15798
The primary goal of this PR is to introduce within the framework of the `Alignment/OfflineValidation` package all-in-one meta-tool the [Alignment PV Validation](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideTkAlignmentValidationPrimaryVertex) tool  that has been developed so far on standalone branches.
Feature introduced:
- processing speed up via filtering of soft events
- integration in the all-in-one framework
- beautification of output plots
- added script for run-by-run configuration/submission of validation jobs at CAF  
- added tests for the plugin

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
