### PR TITLE
Displaying Hcal Conditions via the CondDB Browser

### PR DESCRIPTION
**Pull request by jjackson12**
Adding Hcal Conditions to the Conditions Database web browser interface (cms-conddb.cern.ch). Partially functional state ready to test on web browser.

### CODE REVIEW

**Comment by mmusich** [comment]
Hi  @jjackson12, can you be a little bit more explicit on the title of the PR: "Pi dev" is not descriptive at all.
Secondly there are certain files which look spurious:
```
ConditionValidation
HCALbtest.sh
getPayloadData.py
out.txt
```
I don't think you really want to commit these, or at least not outside any subsystem.

**Comment by jjackson12** [comment]
Hi @mmusich ,
Yes, seems I had some files unintentionally included in the commit. I removed those and also changed the PR.
Thanks,
Jake

**Comment by mmusich** [comment]
Thanks for the cleanup: this file `CondCore/HcalPlugins/interface/.__afs580D` still looks unwanted.
FYI the `getPayloadData.py` script is already available in release at https://github.com/cms-sw/cmssw/blob/master/CondCore/Utilities/scripts/getPayloadData.py. 
Unless you have to propose updates, I think this can be removed. 
Thanks.

**Comment by jjackson12** [comment]
You're right. I removed that file as well. Thanks for the FYI.

**Comment by jjackson12** [comment]
Update: Removing some other unwanted files.

**Comment by jjackson12** [comment]
Update: All should be good now. Sorry for the clumsy commits.

**Comment by mmusich** [comment]
Hi Jake, @jjackson12, thanks. The comparison looks clean now!

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@jjackson12 could you please update the code according to the code checks suggestion?

**Comment by deguio** [comment]
hi,
I'm not sure if @jjackson12 is still available to follow up on this. in case he is not @DryRun could you please take care of this?
thanks in advance!

@mariadalfonso

**Comment by pohsun** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@deguio @jjackson12 @pohsun @ggovi could you please clarify where this code is really exercised? 
Is this code used in the test workflows? I doubt, but please correct me in case

**Comment by deguio** [comment]
ciao fabio,
the code runs in the demo version of the payload inspector already:
https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod/DEMO

**Comment by fabiocos** [comment]
+1

**Pull request merged**
