### PR TITLE
Fix bool in si pixel gain calibration reject noisy and dead

### PR DESCRIPTION
**Pull request by dkotlins**
Fix bool variable in the SiPixelGainCalibrationRejectNoisyAndDead.h.
Should be int.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by boudoul** [comment]
Hi @ggovi, could you please consider reviewing this PR? It would be great that to integrate it for the next data taking - Thanks

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@mdhildreth @dkotlins - I'm not sure I follow the changes to SiPixelSimParameters_cfi (not mentioned in the PR description or title...) - would naively seem to change premixing configuration?

**Comment by dkotlins** [comment]
David,
I do not understand your comment.
What has changed are a few lines for phase1 :

1) this lines have been commented out,  so the default will be used

<     #digitizer.MissCalibrate = False
<     #digitizer.LorentzAngle_DB = False
<     #digitizer.killModules = False
<     #digitizer.useDB = False
<     #digitizer.DeadModules_DB = False

2) this lines have been added to modify the default

<     digitizer.FPix_SignalResponse_p0 = cms.double(0.00171)
<     digitizer.FPix_SignalResponse_p1 = cms.double(0.711)
<     digitizer.FPix_SignalResponse_p2 = cms.double(203.)
<     digitizer.FPix_SignalResponse_p3 = cms.double(148.)
<     digitizer.BPix_SignalResponse_p0 = cms.double(0.00171)
<     digitizer.BPix_SignalResponse_p1 = cms.double(0.711)
<     digitizer.BPix_SignalResponse_p2 = cms.double(203.)
<     digitizer.BPix_SignalResponse_p3 = cms.double(148.)

In what sense does this change the premixing? I do not get it?

Best regards,
Danek



On 16 Feb 2016, at 14:44, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


@mdhildreth<https://github.com/mdhildreth> @dkotlins<https://github.com/dkotlins> - I'm not sure I follow the changes to SiPixelSimParameters_cfi (not mentioned in the PR description or title...) - would naively seem to change premixing configuration?

**Comment by davidlange6** [comment]
I have no easy way to know these lines are just used for phase 1 and not for phase 0 (the file certainly is used in central workflows). Mike understands this all better than me, so hopefully he can comment.

**Comment by boudoul** [comment]
Looks like there is a confusion with #13300 
@dkotlins If I undertand 
- in #13239 (this one) you wanted to  fix the bool 
- in #13300 , you are modifying the phase1 customs
It ends up that both PR contain both changes....

**Comment by dkotlins** [comment]
Yes, somehow 13300 also picked what was in 13239.
I do not understand why  because I have only done
“ git add “ for the correct 2 pixels and the branch name was different.
But git does strange things!


On 16 Feb 2016, at 16:27, boudoul <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like there is a confusion with #13300<https://github.com/cms-sw/cmssw/pull/13300>
@dkotlins<https://github.com/dkotlins> If I undertand

  *   in #13239<https://github.com/cms-sw/cmssw/pull/13239> (this one) you wanted to fix the bool
  *   in #13300<https://github.com/cms-sw/cmssw/pull/13300> , you are modifying the phase1 customs It ends up that both PR contain both changes....

**Comment by makortel** [comment]
@dkotlins Did you maybe start `fix_bool_in_SiPixelGainCalibrationRejectNoisyAndDead` branch (#13300) on top of the `phase1_customs` branch (#13239) instead of the release/IB (i.e. `from-$(CMSSW_VERSION)`) branch?

**Comment by dkotlins** [comment]
Yes, indeed, the new branch was on the top of the old one.
I thought that branches are independent.
What is than the use of the “git add” command if everything is included anyway?
D.

On 16 Feb 2016, at 16:42, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:


@dkotlins<https://github.com/dkotlins> Did you maybe start fix_bool_in_SiPixelGainCalibrationRejectNoisyAndDead branch (#13300<https://github.com/cms-sw/cmssw/pull/13300>) on top of the phase1_customs branch (#13239<https://github.com/cms-sw/cmssw/pull/13239>) instead of the release/IB (i.e. from-$(CMSSW_VERSION)) branch?

**Comment by makortel** [comment]
In that case the new branch contains also all the commits of the old branch. To achieve independent branches, they should be created on top of a common base commit/tag/branch, e.g. `from-$(CMSSW_VERSION)`.

`git add` is just for adding untracked or changed files to the "staging area", where they can be committed with `git commit`. (but maybe I didn't understand the question)

**Comment by davidlange6** [comment]
closing this as its completely included in #13300 (but maybe it is better to make the simple fix its own pr)

**Pull request closed without merging**
