### PR TITLE
avoid FGbits mismatch to propagate to top shift summary

### PR DESCRIPTION
**Pull request by deguio**
this is needed as a temporary fix waiting for a fw fix

### CODE REVIEW

**Comment by dmitrijus** [comment]
hold

**Comment by dmitrijus** [comment]
Hi Federico,
the fw fix.... is it coming? 

If not, please close this PR.

**Comment by deguio** [comment]
Hi,
actually it's the other way around. this PR is needed until the FW fix is in place, but it's not yet there unfortunately.

**Comment by dmitrijus** [comment]
Still, please close this. We can still apply to online DQM, just that PRs should not be open if they aren't meant to be integrated.

**Comment by davidlange6** [comment]
what FW fix are we talking about?

**Pull request closed without merging**
