### PR TITLE
Added new attributes to FillInfo and created update script for acron schedule.

### PR DESCRIPTION
**Pull request by coder-amey**
Hello, @franzoni, @arunhep, @lpernie and @ggovi.

@ravindkv and I have made the following modifications to the FillInfo package:

- The following attributes have been added to the package by modifying FillInfo.cc, FillInfo.h and FillInfoPopConSourceHandler.cc files:
  - lumiPerBx as CMS_BEAM_COND.CMS_LHC_LUMIPERBUNCH.INSTLUMI_BUNCH (vector\<float\>)
  - delivLumi as MAX(RUNTIME_LOGGER.LUMI_SECTIONS.DELIVLUMI) (float)
  - recLumi as MAX(RUNTIME_LOGGER.LUMI_SECTIONS.LIVELUMI) (float)
- The FillInfoUpdate.sh script has been designed for acron to schedule jobs.
- FillInfoUpdate.sh script increments the previous fill numbers by a specific interval, runs the FillInfoPopConAnalyzer.py script and logs the details for every run.

Thus, we have added new variables to the package which can now be triggered with acron using the FillInfoUpdate.sh script.

I request you to kindly scrutinize our work and provide us with your valuable suggestions so that we can improve this pull request and get it merged.

Thank you for your time.

Sincerely,
Amey & Ravindra.

### CODE REVIEW

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Martin-Grunewald** [comment]
-1
proper rebase needed!

**Comment by perrotta** [comment]
-1
Please rebase

**Comment by kpedro88** [comment]
-1

**Comment by coder-amey** [comment]
Dear convenors,

We have been trying to resolve the merge issues and we regret the inconvenience and the delay caused.
A simple rebase does not seem to troubleshoot the issue and it may require rebasing to another CMSSW release.

We are trying to find a work around, and are therefore closing this unmergeable pull request.
Once we resolve the issue, another pull request will be created shortly.

Sorry for the inconvenience,
Amey & Ravindra.

**Comment by kpedro88** [comment]
@coder-amey it appears that your branch is based on 9_2_X, while the master branch now corresponds to 10_1_X. For more information about rebasing, please read: http://cms-sw.github.io/tutorial-resolve-conflicts.html
To rebase the branch, you may need to specify the `--old-base` option in `git cms-rebase-topic` (in case CMSSW_9_2_X diverged from CMSSW_10_1_X). You could also try cherry-picking your commits onto a recent IB.

**Comment by coder-amey** [comment]
Thank you very much for your suggestion, @kpedro88!

We have rebased the code to a newer CMSSW release (10_0_0_pre2) and have consequently resolved the mergeability issues.

We have now initiated a new pull request which can be found [here](https://github.com/cms-sw/cmssw/pull/21979).

**Pull request closed without merging**
