### PR TITLE
Fix bug in PVAssignment: missing abs for dxy

### PR DESCRIPTION
**Pull request by arizzi**
This fixes the bug found by  @VinInn  of missing abs in PV association

Same PR will be made for 74X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
trying one more time

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8721	17da848
this is the same topic branch/the same code change as in #8722  prepared for 74X.

See that thread for the review discussion and approval summary.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
