### PR TITLE
update premix input + time/event GEN

### PR DESCRIPTION
**Pull request by franzoni**
update premix input + time/event GEN

### CODE REVIEW

**Comment by franzoni** [comment]
+1
follow up to: https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6542/1/1.html
only relevant for production

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
upps... I swapped fields and tricked myself with tests
thanks @cmsbuild !
This further update : https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6540/1/1.html calls for further tuning, put in place.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
