### PR TITLE
Remove deprecation warnings from `Alignment` subsystem

### LINKED ISSUE #48: More TrackerAlignment ES get() calls
* `Alignment/TrackerAlignment`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/TrackerAlignment
crtl-f for `.get(` finds 12 more occurrences of deprecated ES get calls  

then going to
 * `Alignment/CommonAlignmentProducer`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/CommonAlignmentProducer
I find 8 occurrences 

* `Alignment/LaserAlignmentSimulation`
src/Alignment/LaserAlignmentSimulation/test/SimAnalyzer.cc:255:67: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<TrackerGeometry>]' is deprecated [-Wdeprecated-declarations]
   255 |   theSetup.get<TrackerDigiGeometryRecord>().get(theTrackerGeometry);

* `Alignment/SurveyAnalysis`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/SurveyAnalysis
has 16 occurrences

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says is all. Went systematically through all `CMSDEPRECATED_X` warnings for `Alignment` subsystem.
   * removed `EventSetup::get()` calls
   * migrated away from deprecated `EDModule`s API
   * put class headers of plugins in the same file as implementation 
   * modernized code
   
Resolves https://github.com/cms-AlCaDB/AlCaTools/issues/48
Part of https://github.com/cms-sw/cmssw/issues/31061

#### PR validation:

`cmssw compiles`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * tests pass, diffs in MsgLogger only

**Comment by qliphy** [comment]
+1

**Pull request merged**
