### PR TITLE
[12_4_X] Skim for Delayed Jets, MET cut instead of HT

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/37808

It was forgotten to be backportand and now the T0 replay failed because of it: https://github.com/dmwm/T0/pull/4722#issuecomment-1192769998

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/37808

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37808

**Comment by tvami** [comment]
urgent
 * needs to go to 12_4_4

**Comment by tvami** [comment]
atn @sam7k9621

**Comment by tvami** [comment]
@cmsbuild , please test
 * nothing tests this anyway....

**Comment by kskovpen** [comment]
+pdmv

**Comment by tvami** [comment]
@cms-sw/orp-l2 the master of this PR has been in IBs for a month now, everything looks good for it

**Comment by qliphy** [comment]
+1

**Pull request merged**
