### PR TITLE
Fix for workflow 140.x: Initialized mPtRecoOverGen*30_50_Cent_50_80

### PR DESCRIPTION
**Pull request by smuzaffar**
mPtRecoOverGen_30_50_Cent_50_80 were not initialized instead mPtRecoOverGen_50_80_Cent_50_80  were initialized twice

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
DQM, can you please sign it?

**Comment by smuzaffar** [comment]
@rkunnawa, does these changes looks OK to you. I want to merge this in next IB to get rid of couple of Relval failures

**Comment by rkunnawa** [comment]
@smuzaffar that looks fine! thanks a lot for the fix! 
Cheers
Raghav

**Comment by smuzaffar** [comment]
merge

**Pull request merged**
