### PR TITLE
bsunanda:Run2-alca44 Recover from 0 event selection in IsoTrack Trigger

### PR DESCRIPTION
**Pull request by bsunanda**
Backporting PR 14514 and needed to go for HLT

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fwyzard** [comment]
Dear Sunanda,

before approving this change to the HLT, I would like to see a short
description of the change, and the usual HLT rate and running studies.

Looking at some of the changes in confused. Did this ever run with the
Stage 2 L1 trigger ?

Ciao,
.Andrea

**Comment by bsunanda** [comment]
Hi Andrea

I am doing this with Sourav Dey who ran it on the recent data. I shall ask him to prepare a few slides with the changes made and corresponding rates + timing information. Regards

Sunanda

________________________________

**Comment by bsunanda** [comment]
Hi Andrea,
   Here I have attached the same slides with three different formats.

Regards,
Sourav
________________________________
From: Sunanda Banerjee
Sent: 16 May 2016 23:21
To: cms-sw/cmssw; cms-sw/cmssw
Cc: Mention; Sourav Dey
Subject: RE: [cms-sw/cmssw] bsunanda:Run2-alca44 Recover from 0 event selection in IsoTrack Trigger (#14516)

Hi Andrea

I am doing this with Sourav Dey who ran it on the recent data. I shall ask him to prepare a few slides with the changes made and corresponding rates + timing information. Regards

Sunanda

________________________________

**Comment by fwyzard** [comment]
Hi Sourav,
PDF is usually enough, but thanks.

The details in the slides are very scarce - could you elaborate a bit more on what you are trying to achieve, what are the proposed changes, what is the impact on the HLT rates and timing, and its expected evolution with pileup and/or luminosity ?

**Comment by Martin-Grunewald** [comment]
+1
Remember to file a JIRA ticket for any changes to the HLT python configuration of your paths!

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by fwyzard** [comment]
-1

Please provide enough details to understand the impact on the HLT.

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
