### PR TITLE
HCALDQM: Update DigiTask for 2018 HE (10_1_X)

### PR DESCRIPTION
**Pull request by DryRun**
Updates HCALDQM DigiTask for 2018 HE. A number of plots were not filled for HEP17 last year because it would have mixed QIE8 and QIE11 digis; QIE11-specific plots were created in QIE11Task. Now that HE==QIE11, I integrated the plots of interest from QIE11Task to DigiTask. 

I also included one small bug fix for LaserTask: with the 2018 HE, the range for the laser signal has to be increased.

Note that I based this PR on top of https://github.com/cms-sw/cmssw/pull/22595, which fixed the new digi size for 2018 in DigiTask, so that PR should be merged first.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
It looks like the failed test has the upgraded HB - is it a requirement that the code be compatible with this already (not installed until Run 3)? I can make it so if needed...

**Comment by DryRun** [comment]
OK, I fixed the issue by requiring the QIE11 digis all come from HE (`did.subdet() == HcalEndcap`). This should have been done in the first place, since calibration channels also end up in QIE11DigiCollection and can cause problems if not screened out.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@DryRun looking at the impact on the memory in the output I see that this PR moves from

2644.13 KiB      Hcal/DigiTask   

to 

4821.62 KiB      Hcal/DigiTask

so there was an ~ 80% increase in space. I understand that these plots were already available in another QIE11Task, but was this module writing its output out? I do not see other changes in the Hcal histogram output, so effectively this is not moving histograms between folders, but a net new addition, right?

**Comment by DryRun** [comment]
Hi @fabiocos - yes, that is correct, QIE11Task was indeed not run for offline DQM, so several plots are new additions. I think most of the memory comes from the `_cLETDCTimevsADC_SubdetPM` set of plots, which added 6 256x250 histograms (HB+, HB-, HE+, HE-, HO+, HO-; HF+ and HF- were already present). This fine granularity isn't necessary, so I reduced the 250 bins to 100 bins (i.e. keep the ADC granularity, but reduce the time granularity from 1 ns to 2.5 ns).

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
