### PR TITLE
Run3-hcx352B Add files to evaluate the impact of the changes made to the geometry scenarios due to SD issue in HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add files to evaluate the impact of the changes made to the geometry scenarios due to SD issue in HCAL

#### PR validation:

Made comparison with the old scenario

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
