### PR TITLE
Consolidate and simplify MTD modifiers

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Addresses part of #27450:
* merge the modifiers phase2_timing_layer and phase2_timing_layer_bar
* remove the modifier phase2_timing_layer_tile
* simplify the naming of Phase2 top-level Eras (since only Eras appended with "_timing_layer_bar" are used)

No changes in C++ code are made here; those are left to the MTD expert developers.

Additionally, the changes are propagated to the various test configs scattered throughout CMSSW. Normally I do not guarantee support for such configs, but in this case it was a one-line command to update them.

#### PR validation:

Ran workflow 20434.0 successfully.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28387	b6e659a 
- changes are essentially technical for reco configs (consolidation of phase2_timing_layer and phase2_timing_layer_bar modifiers into one)
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of central configurations is coherent with the target of the this PR

**Comment by fabiocos** [comment]
+1

@rekovic the update in L1T configuration looks straightforward

**Comment by fabiocos** [comment]
merge

**Pull request merged**
