### PR TITLE
Phase2 Tracker with 12 Pixel Disks (v. 4025)  [new WFs 2023D11] 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
This PR is introducing a new version of the phase2 tracker 
The main change is the addition of a new disk in the forward pixel .

This geometry is now defining the tracker T5 and the workflow 2023D11 has been created (clone of the 2023D4 but with the new pixel ) - Scripts and documentations have been updated accordingly in this PR

Some link describing the geometry and the changes
http://ghugo.web.cern.ch/ghugo/layouts/merge/OT365_200_IT4025/
https://indico.cern.ch/event/536862/contributions/2397837/attachments/1384630/2106411/mersi_20161207_newlayouts.pdf

How to test : 
Find the 2023D11 workflow in runthematrix , WFs  240XX

### CODE REVIEW

**Comment by boudoul** [comment]
Most of the usual watchers are already there, adding @ebrondol , @atricomi  , @delaere

**Comment by boudoul** [comment]
please test with cms-data/SLHCUpgradeSimulations-Geometry#5

**Comment by kpedro88** [comment]
please test with cms-data/SLHCUpgradeSimulations-Geometry#5

**Comment by smuzaffar** [comment]
testing only works with cmsdist PR :-) which is now available https://github.com/cms-sw/cmsdist/pull/2836

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2836

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2836

**Comment by ebrondol** [comment]
Hi @boudoul, @slava77 , please notice that I am aware that this new geometry will not run in step3 after that the PR #17547 has been integrated. But that PR was a major step for a good tracking. I will introduce another PR soon to fix the problem.

**Comment by slava77** [comment]
@cmsbuild please test
to see the impact of #17547 (integrated in 17-2300 IB, now available, but not yet for the tests already processed)

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2836
need external

**Comment by boudoul** [comment]
hold

**Comment by boudoul** [comment]
seems that I forgot a file , fixing in a few minute

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by boudoul** [comment]
thanks @kpedro88 , I have indeed updated with the missing file - so unhold from me (although I realized that I have no power on hold, unhold on github)

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
