### PR TITLE
data processing scenarios for Run2_2018_highBetaStar

### PR DESCRIPTION
**Pull request by slava77**
add pp, hcalnzs, and trackingOnly scenarios for Era_Run2_2018_highBetaStar.

I think that only pp is really necessary. I still added the hcalnzs and trackingOnly, just in case.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
+operations

tested to run and include the desired customizations with Run 314890 (LS= 500) -- for central tracking tests

dasgoclient --limit=0 --query="file dataset=/ZeroBias/Commissioning2018-v1/RAW run=314890 lumi=500"
python RunPromptReco.py --scenario=ppEra_Run2_2018_highBetaStar --reco --aod --dqmio --global-tag 101X_dataRun2_Prompt_v9 --lfn=/store/data/Commissioning2018/ZeroBias/RAW/v1/000/314/890/00000/30598593-8C46-E811-9216-FA163E48B3F0.root

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@slava77 thank you for providing the configuration, I'll prepare its backport to 10_1_X

**Pull request merged**
