### PR TITLE
Run3-hcx333 Try to address wrong SubDetId in some cases

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address wrong SubDetId in some cases for HCAL simulation. Some ID's corresponding to HB are classified as HE which are not present in the Phase2 scenarios. Once this PR is merged, the latest phase2 scenarios will be updated to have the changed HCal scenarios.

#### PR validation:

Compared the parameters read in for HCAL simulation with DDD and DD4hep using cfg's in Geometry/HcalCommonData

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

Probability of wrong detector ID is below 1%, this PR should fix this issue.

**Comment by civanch** [comment]
@bsunanda , please, put in the history info about next steps.

**Comment by bsunanda** [comment]
@civanch Added a few lines in the description part

**Comment by perrotta** [comment]
+1

**Pull request merged**
