### PR TITLE
Run2-sim18 Do the bug fix for ECal shower profile correction to 9_2_X (back porting from 9_4_X)

### PR DESCRIPTION
**Pull request by bsunanda**
Correctly calculating depth along crystal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , how you make the PR: direct copy from 9_3_X or by edition of the code? I am asking because code-checker add many useful modifications, so difficult to control real modifications.

**Comment by civanch** [comment]
+1
I believe that a copy from 9_4 should work for 9_2

**Comment by davidlange6** [comment]
+1

**Pull request merged**
