### PR TITLE
[14.0.X] Add certificates handling to Tier0Handler

### PR DESCRIPTION
**Pull request by JanChyczynski**
#### PR description:

This PR adds providing certificates for curl requests done to `https://cmsweb.cern.ch/t0wmadatasvc/prod/`.
The paths to the certificate and the key are meant to be specified in `X509_USER_CERT` and `X509_USER_KEY`. 

The certs became obligatory for accessing this API after migration of cmsweb from CC7 and this functionality is required by the conddb command and some O2Os (EcalLaser_prompt_run3, SiStripDetVOff_prompt, possibly also EcalLaser_prompt_hlt, ESGain_prompt, SIntercalibConstants_prompt, SRecHitRatioCuts_prompt, STimeSampleWeights_prompt)

The PR also introduces a way of overriding the hardcoded T0 API URL by setting the TIER0_API_URL env variable (eg. for test purposes).

#### PR validation:

Tested by running `python3 tier0.py` which is running the test for it.

#### Backport
This is the backport to CMSSW_14_0_X of the main PR: https://github.com/cms-sw/cmssw/pull/45779

FYI @perrotta @francescobrivio @PonIlya

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45779

**Comment by perrotta** [comment]
@JanChyczynski please update this PR as you did for its master and 14_1_X versions

**Comment by JanChyczynski** [comment]
Updated, ready for the tests @perrotta

**Comment by perrotta** [comment]
please test

**Comment by JanChyczynski** [comment]
@perrotta @mandrenguyen Can you take a look and sign? I ping you mandrenguyen 'cause you've signed the main PR so maybe you can sign the backport too

**Comment by mandrenguyen** [comment]
> @perrotta @mandrenguyen Can you take a look and sign? I ping you mandrenguyen 'cause you've signed the main PR so maybe you can sign the backport too

I only sign after everyone else does.  @perrotta can you have a look please?

**Comment by perrotta** [comment]
+db
- Verbatim backport of the PR merged in the master
- To be merged in the next patch so that it can be tested in the O2O machines

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
