### PR TITLE
custom nano configuration and test [Backport]

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

backporting #44263 #44425 #44399 #44087 to 14.0.X, mostly for Tier0 purpose

#### PR validation:

nano matrix

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
we'll have to deal with #44383 and the `rivetMetTable` so as to enable the DQM

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
@rbhattacharya04 is the change to custom_muon_cff.py acceptable ?

**Comment by rbhattacharya04** [comment]
Hi @vlimant , as far as I understand, the changes in the custom_muon_cff.py are fine. But please wait a little bit for the other muon pog colleagues to confirm. I am also tagging @JanFSchulte to have a look.

**Comment by vlimant** [comment]
alright, thanks

**Comment by vlimant** [comment]
@cms-sw/pdmv-l2 @cms-sw/operations-l2 @cms-sw/upgrade-l2 : can you please look into this trivial PR as backport to 14.0.X ?

**Comment by vlimant** [comment]
included also the fix #44464

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
I might add HCAL in the mix ( #43961 )

**Comment by vlimant** [comment]
+1
no need for hcal syntax here for now

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by vlimant** [comment]
@cms-sw/orp-l2 : as this PR does not change content, but only how we get to configure flavors of NANO, for the purpose of harmonized production configuration, can you please merge this in ?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
