### PR TITLE
New ME0PreDigi parameters

### PR DESCRIPTION
**Pull request by calabria**
This change will allow us to change the ME0 space and time resolution by simply re-digitizing the existing samples once they are produced. We would like to have this simple change in pre13 and son then in 810.
@kpedro88 @pietverwilligen @jshlee @mmaggi

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@calabria @kpedro88 - naively it would be best to put these change into a customize fragment for special samples - that way everyone except for the ME0 experts get the current "best estimate"

**Comment by calabria** [comment]
actually the default parameters are not the best estimate, but just some temporary but reasonable values we introduced to start the ME0 studies. We are estimating now the requirements for ME0 and for that we need this PR. The idea is to use very good spatial and time resolutions so that if big samples are produced centrally, then we will be able to change the granularity/time response simply by re-digitizing the smeared points (pseudodigis) without running again the DIGI step and the PU mixing. A customization function would be good in case we are allowed to ask the central production of specific samples (also RelVal) for the ME0 granularity studies, but I am not sure if this possibility really exists... if so, I can move to a customization function. anyway this new setting does not worsen the performance.

**Comment by davidlange6** [comment]
Hi @calabria - right "temporary but reasonable" is indeed your current best guess. If something more is needed for ME0 studies, a customize function in the release would be more appropriate. Thanks.

**Comment by mmaggi** [comment]
Hi @davidlange6, just to make sure the issue is clear.... we need centrally produced MC samples with this fragment... at the end the normal user will use ME0 with optimist performance anyhow. Not sure which is best strategy to accomplish this.

**Comment by davidlange6** [comment]
maybe I’ve missed the discussion that led to this PR? getting perfect reconstruction doesn’t seem like the right setup for normal users.

**Comment by mmaggi** [comment]
indeed, but we need to avoid facing the option to generated by our self all MC big sample to study the requirements for ME0.  keeping ME0 simhits will make the job too....

**Comment by davidlange6** [comment]
I’m certainly not proposing that you run MC samples yourself..

**Comment by pietverwilligen** [comment]
In case this release will get used for a production we would like to have these numbers as default. furthermore we would like to use RelVals to be made with these settings. Please approve. We will implement the customization in a forthcoming, but separate PR. These settings reflect anyway the situation used for the TP, so users won't get a "to good reconstruction". It would be still rather "too poor".

**Comment by davidlange6** [comment]
was the unphysical settings as a default for everyone discussed with the upgrade group? I’m happy to go along with an agreed upon plan.

**Comment by calabria** [comment]
Dear @davidlange6 , since Patrizia and Meenakshi agree, can you approve this PR? Thanks a lot.

**Comment by kpedro88** [comment]
@davidlange6 ping

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
I think, there is an issue with this PR. See: https://github.com/cms-sw/cmssw/issues/16838

**Pull request merged**
