### PR TITLE
Hlt tau validation update cmssw92 x june2017

### PR DESCRIPTION
**Pull request by slehti**
As requested in PR #18172, changed bool tagAndProbe -> tagAndProbe_
One bug fix.
Added tag&probe monitoring for the lepton legs of the lepton+tau triggers.

### CODE REVIEW

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by mtosi** [comment]
TSG google doc has been updated ;)
thanks

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @slehti - pi is either 3.14 or 3.15 in this PR - please pick one (personally I would use its true value..)

**Comment by slehti** [comment]
The 3.14 or 3.15 is only for the histogram plotting region. Changed to +-3.15.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1
even if phi really does go from -pi to pi..

**Pull request merged**
