### PR TITLE
fix propagator in SeedFromConsecutiveHitsCreator config file

### PR DESCRIPTION
**Pull request by mtosi**
the defualt setting in the SeedFromConsecutiveHitsCreator configuration was not coherent
(propagator <----> magneticField)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@mtosi 
If this is relevant for HLT, you need to file a JIRA request as we
do not use the cfi files in HLT (only for parsing, so changing
values in cfi files will not affect the older values we use in HLT).

**Comment by mtosi** [comment]
ciao Martin,
we are already using our own setting,
so it should be transparent for us 
(I'll cross check on confDB by tomorrow morning..I'm offline, now)

thanks for reminding
cheers
  mia

**Comment by mtosi** [comment]
ciao,

this PR is needed for having a coherent default setting of parameters propagator and magneticField

I've just looked @ /dev/CMSSW_7_4_0/GRun/V27
and I found the following instances
* HLTSeedFromConsecutiveHitsCreator
* HLTSeedFromConsecutiveHitsCreatorIT
* HLTSeedFromProtoTracks

all of them have already coherent setting of these parameters
HLTSeedFromConsecutiveHitsCreator.propagator = PropagatorWithMaterial
HLTSeedFromConsecutiveHitsCreator.magneticField = 

HLTSeedFromConsecutiveHitsCreatorIT.propagator = PropagatorWithMaterialParabolicMf
HLTSeedFromConsecutiveHitsCreatorIT.magneticField = ParabolicMf

HLTSeedFromProtoTracks.propagator = PropagatorWithMaterialParabolicMf
HLTSeedFromProtoTracks.magneticField = ParabolicMf

=> the HLT config does not have to be updated

**Comment by mtosi** [comment]
@cmsbuild @slava77 
ciao
is it possible to test this PR ?
I think issues we had yesterday are not really related to this bug fix ...
thanks

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Looking at jenkins tests outputs I see that this changes RECO products.
Do we have tracking (pre)validation plots for this change to decide it's OK?

**Comment by VinInn** [comment]
@slava77 
Tests were made in the old days, and THIS should had been the default.
Was lost somehow (most probably during the modification of percolation of propagators due to thread-safety)

**Comment by makortel** [comment]
Not that I'm aware of. I'll start running now.

**Comment by slava77** [comment]
I'd rather not introduce further changes to RECO at this stage.
The PropagatorWithMaterialParabolicMf is faster and is slightly less precise.
So, unless I'm missing something, this inconsistency can just stay as a feature for 74X and just go to 75X.
(open for discussion though, especially if there happen to be physics changes in other parts post-pre9).

**Comment by slava77** [comment]
-1

for https://github.com/cms-sw/cmssw/pull/8465	7ea7f23
based on comments in https://github.com/cms-sw/cmssw/pull/8465#issuecomment-86058260

I have approved the same change for 75X in #8464

**Pull request closed without merging**
