### PR TITLE
Change from numberOfMatches() to segment number in DisplacedMuonFilterProducer

### PR DESCRIPTION
**Pull request by 24LopezR**
#### PR description:

This PR intends to fix an unexpected behavior observed when validating the performance of the slimmedDisplacedMuons collection in MiniAOD samples. 
The issue consists in a bad filtering of highly displaced muons caused by the definition of muon.numberOfMatches(), which was proved to not be appropriate to effectively select displaced muons when no tracker track is reconstructed.
The fix in this PR proposes to change this variable for another one. Now, the segments of the track are counted through the reco::Track object itself, which yields a more accurate description of the standalone muon track properties. 
This issue was reported to and discussed with the MUO POG, a detailed description can be found at:
https://indico.cern.ch/event/1263952/ ("Update on displaced muon collection performance studies").

Muon number expected to increase in muons from the slimmedDisplacedMuons collection which are not .isGlobal() nor .isTracker() in high displaced signals e.g DisplacedSUSY and Cosmics. These muons are not expected to change in prompt signals except for some small fluctuations. Standard muons should not be affected in any way.

The fix has been checked to work properly in cosmics data and H->SS MC signal (higher and lower displacement). 

See attached plot for a comparison of muon $d_{xy}$ distribution for a highly displaced H->SS signal (ctau=4000mm) between the old filter (red) and the fix in this PR (blue).
HTo2LongLived_400_150_4000_h_dxy

Other authors: @CeliaFernandez  

#### PR validation:

The code changes have passed all standard runTheMatrix test workflows.
No significant increase in size of MiniAOD is expected (tested on ttbar workflow 11834.21)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We would like to have this also backported to 13_0_0.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
type muon

**Comment by CeliaFernandez** [comment]
I had a look at the failed reco comparison results. I would say these are consistent with the changes expected in prompt samples:

Affected muons are slimmedDisplacedMuons with are **only** displacedStandAloneMuons (StandAloneMuon type in the collection i.e. 00001000). These kind of muons would be the only ones for which the modified lines are executed. See for example in 10224.0 comparison:

MuonTypeAffected

The changes in the distributions arise because the number of muons is changing i.e. different muons are filtered w.r.t. reference. The proposed changes should either:

- Increase the number of SA-only displaced muons with numberOfMatches < 2: because they pass the new filter but failed the old one.
- Decrease the number of SA-only displaced muons with numberOfMatches >= 2: because they passed the old filter but now they fail the new one.

This effect can be also checked in workflow 136.793:

136p793_c_patMuons_slimmedDisplacedMuons__reRECO_obj_numberOfMatches

**Review by mandrenguyen — COMMENTED** [review]
If you moved the minPtSTA check earlier in the code, would it save you from having to calculate the number of segments when the pT threshold condition isn't met?

**Comment by 24LopezR** [comment]
I moved the minPtSTA check to avoid computing nsegments unnecessarily when the condition is not met.

I also checked that the behaviour of the filter remains the same. See attached plot of DSA muon $|d_{xy}|$ variable (both histograms overlap):

image

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test
wake up, bot!

**Comment by mandrenguyen** [comment]
+reconstruction
Changes consistent with PR description

**Comment by simonepigazzini** [comment]
+xpog

**Comment by rappoccio** [comment]
+1

While this is perfectly fine for 13_2, we need to discuss the backport to 13_0 since this changes prompt workflows already in production.

**Comment by simonepigazzini** [comment]
Since prompt is over can we backport this to 13_0? It looks like some EXO analysis could benefit from this fix to the displaced muons collection if this goes into the reMINI campaign for 2022 data/MC.

@rappoccio @antoniovilela @cms-sw/ppd-l2

**Comment by 24LopezR** [comment]
@simonepigazzini Yes, it can be backported to 13_0 (I see there is already a PR for this). Indeed, it would be very benefitial for EXO analyses.

**Pull request merged**
