### PR TITLE
Run3-gex176Z Add the scenario for 2024 with modified version for GE21 and RPC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the scenario for 2024 with a modified version for GE21 and RPC

#### PR validation:

Use the new scenario for the SIM step

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar, @srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by jordan-martins** [comment]
+1

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please merge this. I need to use the IB to prepare the payload for the new scenario

**Pull request merged**
