### PR TITLE
Adapt protection against zero weights or pt for SV producer

### PR DESCRIPTION
**Pull request by AnnikaStein**
#### PR description:

This PR applies the same protective measures introduced in https://github.com/cms-sw/cmssw/pull/40081 for another producer in the `RecoBTag/SecondaryVertex` package. While we have not seen a precedent case that yields the abort signal reported in https://github.com/cms-sw/cmssw/issues/40032 coming from this particular producer (`TemplatedSecondaryVertexProducer.cc`), the logic is essentially same, so we think we should include the fixes here for safety purposes as well.

#### PR validation:

Tests have been performed for CMSSW_12_6_0_pre4 in the following way (https://cms-sw.github.io/PRWorkflow.html):
```
cd src
scram b distclean 
git cms-checkdeps -a -A
scram b -j 8
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
```
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Planning backports to 12_4_X and 12_5_X, similar to what was discussed in related discussion in https://github.com/cms-sw/cmssw/issues/40032

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please abort

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please abort

**Comment by mandrenguyen** [comment]
please test
in the ORP i just heard that tests should work again now

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
