### PR TITLE
Implementation of the Muon Track Splitting (MTS) Validation in the new TkAl all-in-one tool

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a first attempt to integrate the Muon Track Splitting (a.k.a. MTS) tool in the *new* Tracker alignment all-in-one tool (introduced at https://github.com/cms-sw/cmssw/pull/38304), as a follow-up to https://github.com/cms-sw/cmssw/pull/43386 which removed the old (and unusable) configuration.
This PR builds on top of the previous internal PR at https://github.com/cms-trackeralign/cmssw/pull/31 and adds:
   * [merge step for MTS validation](https://github.com/cms-sw/cmssw/commit/1dddfe980e5916d613216464b248acf336df7621);
   * [implement MTS validation in unit tests](https://github.com/cms-sw/cmssw/commit/271683cfeba5237c273373142fe42dfaa694b628);
   * [update README for Muon Track Splitting](https://github.com/cms-sw/cmssw/commit/856fc050065244525f36ae7513bc9cd9c275b342);
   * finally it applies code check and code format standards;

#### PR validation:

   * `cmssw` compiles
   * `scam b runtests_MTSall` runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Unit tests succeed

**Comment by rappoccio** [comment]
+1

**Pull request merged**
