### PR TITLE
new features for offline Tk DQM scripts

### PR DESCRIPTION
**Pull request by vdutta**

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 for https://github.com/vdutta/cmssw/commit/7765474f68f53b449713a71fb5e31b56b555ece5

**Comment by deguio** [comment]
-1
rebase needed

**Comment by vdutta** [comment]
Sorry, it's my first time trying a rebase so I'm not sure if I messed up the history. Please let me know if I should close this PR and open a new one instead.

**Comment by Martin-Grunewald** [comment]
-1
Please rebase properly!

**Comment by mmusich** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by diguida** [comment]
+1
backport of #10759 (already approved once, then forgot to re-approve)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
