### PR TITLE
Rebased full L1T O2O for 80X

### PR DESCRIPTION
**Pull request by kkotov**
Moved PR https://github.com/cms-sw/cmssw/pull/15814 here

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by kkotov** [comment]
Clang tests for 80X? Ok, cherry-picking the fix from 81X ...

**Comment by mmusich** [comment]
please test

**Comment by kkotov** [comment]
Pushed it to the end: say no to Clang test warnings. Triggering tests just in time :0)

**Comment by kkotov** [comment]
@smuzaffar, hmm, I have no slightest idea about the code that generates the error. Could it be because of the rebasing? If so, which branch I should have targeted?

**Comment by smuzaffar** [comment]
@kkotov , looks like 80X IB is broken due to new llvm in it. We shall fix the llvm error first.
I am working on it

**Comment by smuzaffar** [comment]
Utilities/StaticAnalyzers errors should be fixed by https://github.com/cms-sw/cmssw/pull/15858
Next IB (23h00) should be used to test this Pr again

**Comment by mmusich** [comment]
@cmsbuild, please test
retrying (hopefully with the new IB)

**Comment by smuzaffar** [comment]
its is bit early to start the tests as 23h00 IB is not fully available (base line for comparison is missing). I will restart the tests once 23h00 is available.

**Comment by mmusich** [comment]
@smuzaffar thanks a lot.
For my own education where shall I get this information? 
From https://cmssdt.cern.ch/SDT/html/showIB.html 

`CMSSW_8_1_X_2016-09-14-2300`

seems to be available, though there is no corresponding version in: 

`/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/`

**Comment by smuzaffar** [comment]
Yes on https://cmssdt.cern.ch/SDT/html/showIB.html (select the correct release cycle i.e CMSSW_8_0_X in this case) and then see if ```Comparison Baseline``` is available or not (in case it is available there should be hyperlink otherwise just a flat text)

**Comment by kkotov** [comment]
This funny error teaches us how bad it is to have global macros with some generic names. It seems like our harmless code is now suffering from "VERSION" macro defined somewhere in CLHEP. The only mystery is that neither L1Trigger/L1TGlobal/interface/PrescalesVetosHelper.h includes any of CLHEP library files, nor can I find where it may be used in conjunction with CLHEP from some 3rd party package. I'm really puzzled now!

**Comment by davidlange6** [comment]
> On Sep 15, 2016, at 5:26 PM, kkotov <notifications@github.com> wrote:
> 
> This funny error teaches us how bad it is to have global macros with some generic names. It seems like our harmless code is now suffering from "VERSION" macro defined somewhere in CLHEP. The only mystery is that neither L1Trigger/L1TGlobal/interface/PrescalesVetosHelper.h includes any of CLHEP library files, nor can I find where it may be used in conjunction with CLHEP from some 3rd party package. I'm really puzzled now!
> 

is there a using namespace l1t floating around in a header that shouldn’t be? naively being in the namespace should have prevented this (or reduced its chance substantially)

in 81x there is
src/DQM/L1TMonitor/interface/L1TdeStage2CaloLayer1.h: using namespace l1t;

**Comment by kkotov** [comment]
@davidlange6 , it turned out that most of the errors were generated due to simultaneous inclusion of
*DataFormats/TrackReco/interface/Track.h*
(that needs CLHEP) and
*CommonTools/TriggerUtils/interface/PrescaleWeightProvider.h* that in turn includes
*HLTrigger/HLTcore/interface/HLTPrescaleProvider.h* that includes
*L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h* that _now_ also includes
*L1Trigger/L1TGlobal/interface/PrescalesVetosHelper.h*

I'm now investigating why Mike introduced dependency of L1TGlobalUtil on the new PrescalesVetosHelper in his "post rebase cleanup" commit:
https://github.com/kkotov/cmssw/commit/f93c7dc6d1ca6acaa1d281df3b7c40d3ba83d56e#diff-149cd77299f8a5730010712d4cdf2ca3
But I hope to get away simply reverting this single chage as I don't need this and Vladimir's latest greatest PR doesn't have it either.

As of using namespaces, although this would generally be a good practice in this case, I don't see how it would save us from the similarly named macro defined elsewhere and then accidentally included with our unlucky class.

**Comment by kkotov** [comment]
Realizing that the L1TGlobalUtil is beyond the scope of my competency, I decided to fix the problem by simply changing VERSION -> VERSION_ in the PrescalesVetosHelper.{h,cc}. That seems fixing the problem for now. I only hope that I won't need to do a similar change to all other our classes in CondFormats and their corresponding helpers under L1Trigger.

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by kkotov** [comment]
Well, after I removed the uGT static xml configs, this test attempt had no other choice but to fail:
-------------------------------------------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESProducer: class=L1TGlobalPrescalesVetosESProducer label='L1TGlobalPrescalesVetos'
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_PRESCALES_v10.xml anywhere in the search path.

**Comment by rekovic** [comment]
@kkotov As I commented https://github.com/cms-sw/cmssw/pull/15842#issuecomment-247560405 , please repeat the tests after the 2300 IB is built and the externals are available for PR testings.  Do it probably tomorrow morning to be safe.

**Comment by mulhearn** [comment]
please test

**Comment by kkotov** [comment]
I see the same error re-appearing again:

----- Begin Fatal Exception 17-Sep-2016 12:32:56 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESProducer: class=L1TGlobalPrescalesVetosESProducer label='L1TGlobalPrescalesVetos'
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_PRESCALES_v10.xml anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH

I see the relevant files are neither in
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-09-16-2300/src/L1Trigger/L1TGlobal/data/Luminosity/startup/
nor in
/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/data-L1Trigger-L1TGlobal/

**Comment by kkotov** [comment]
@smuzaffar do you know if the policy of updating the cms-data in IBs for 81X differ from IBs for 80X? Looks like PR https://github.com/cms-sw/cmssw/pull/15842 passed the tests (meaning that UGT*xml files made it there), but this PR failed. The files are clearly present in 81X:
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-16-2300/external/slc6_amd64_gcc530/data/L1Trigger/L1TGlobal/data/Luminosity/startup/
but nowhere to be found in 80X:
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-09-16-2300/external/slc6_amd64_gcc530/data/L1Trigger/L1TGlobal/data/Luminosity/startup/

**Comment by smuzaffar** [comment]
normally externals go to in development release (i.e. 81X) and then explicitly requested to include in production releases e.g. 80X .
I am including the data external for 80X now.

**Comment by kkotov** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
Following the discussion in https://github.com/cms-sw/cmssw/pull/15842#issuecomment-248128266 I'll remove the data files from this PR as well ...

**Comment by rekovic** [comment]
please test

Now that data files are removed from the PR, restarting tests.

**Comment by rekovic** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
apologies I did not mean to merge this PR - need to revert for the moment. will re-revert (though maybe it has caused a problem in our release build)

**Comment by davidlange6** [comment]
Hi @kkotov @rekovic  - maybe this explains it - can you provide a fix for this?

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc600/CMSSW_8_1_X_2016-09-22-0900/L1TriggerConfig/Utilities

**Comment by kkotov** [comment]
@davidlange6 I'm a bit confused. This is a PR for 80X, but you are pointing to the compilation errors in 81X (CMSSW_8_1_X_2016-09-22-0900). The error is fairly easy to fix, but should I commit it to 80X branch, or 81X, or both?

**Comment by davidlange6** [comment]
Right - because of my mistake I guess we are discovering the same issue in 80x and 81x..
please fix in both (I guess you will need to start a new branch)

**Comment by rekovic** [comment]
@davidlange6  Do you still plan to revert the merging of this PR? Or simply wait for the fix from @kkotov and merge that without reverting this merge?

I am asking because of my L1T 80x PRs which had to be rebased due to merging of this PR here.

**Comment by davidlange6** [comment]
i reverted it already…

**Comment by koskot77** [comment]
@davidlange6 , I was wondering if we plan to have a new release by Friday (with this PR) in order to have it at p5 before this MD ends?

**Comment by davidlange6** [comment]
Given the troubles with the full l1 package (maybe just resolved today) that this pr is tied to, it seems unlikely.

Cheers,
David


On 6 Oct 2016, at 19:25, KK <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , I was wondering if we plan to have a new release by Friday (with this PR) in order to have it at p5 before this MD ends?

**Pull request merged**
