### PR TITLE
[92X] Revert "review SiStripGains PCL configuration due to re-organization of classes in CalibTracker/SiStripChannelGain"

### PR DESCRIPTION
**Pull request by mmusich**
This reverts commit efdd57403ce6ace836e4f71bdf0d0bd0b5af78d3.
As per report at https://github.com/cms-sw/cmssw/pull/18363#issuecomment-301009755, this should bring back the peak RSS consumption of step3 in wf 1001.0 to acceptable levels.
Will revert once an affordable solution to usage of stream DQM modules will be found.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
Hi @franzoni, I was too quick in rebasing after #18753 was merged. 
Now `runTheMatrix.py -l 1001.0` runs to completion.
I profit of this PR to remove also two files that were left over in the #18753, but have no reason to remain at this point.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@mmusich I guess you checked the reduced RSS after this PR's changes?

**Comment by mmusich** [comment]
Hi @ghellwig yes, that's what you see here: https://github.com/cms-sw/cmssw/pull/18531#issuecomment-301449683 (well before the rebases...)

**Comment by ghellwig** [comment]
but the plots don't show a reduced RSS, but rather a different run time, or am I missing something?

**Comment by mmusich** [comment]
you should compare the top plot (what is currently in release), with the bottom plot (what I am proposing, and was already there in `CMSSW_9_1_0_pre2`. The peak RSS is halved (from 9GB to ~ 4.5GB)

**Comment by mmusich** [comment]
to make it more clear, after the detour of going through #18363 and going back form here, the net change in the bottom plot is what you would expect after https://github.com/cms-sw/cmssw/pull/18531 and this PR are merged.

**Comment by ghellwig** [comment]
ok, understood now :)
thank you, Marco!

**Comment by ghellwig** [comment]
+1

**Comment by franzoni** [comment]
@davidlange6 what are the pending issues with this PR - we'll be happy to address them.

Otherwise may we please get this merged ?
Thanks!

**Comment by davidlange6** [comment]
i haven't had time to fully investigate. but I believe this PR is worse (reintroducing histogram access not via the correct method) than the current situation. Better to stay as we are.

**Comment by mmusich** [comment]
Closing based on the previous comments. The useful commit https://github.com/cms-sw/cmssw/pull/18776/commits/30037acdd50f002572160292a21ef2394c12761f is re-proposed here https://github.com/cms-sw/cmssw/pull/19075

**Comment by franzoni** [comment]
At the ORP meeting of Tue May 30th, 2017
consensus was reached around:
. Tier0 is currently running AlcaSkimming single threaded
. Tier0 will continue doing so for the foreseeable future
. therefore this PR is not to be considered

**Comment by mmusich** [comment]
@franzoni, this PR was closed yesterday. OTOH there is a commit that you might want to consider at #19075

**Comment by davidlange6** [comment]
> On Jun 2, 2017, at 8:33 AM, Giovanni Franzoni <notifications@github.com> wrote:
> 
> At the ORP meeting of Tue May 30th, 2017
> consensus was reached around:
> . Tier0 is currently running AlcaSkimming single threaded
> . Tier0 will continue doing so for the foreseeable future
> . therefore this PR is not to be considered
> 

and : current solution has a safe (if memory consuming) behavior in multithreaded application, whereas the one in this PR does not.

**Comment by franzoni** [comment]
Thanks @mmusich I've taken note of that.
I wanted to keep memory here of the choice made. Removing the stale files is also good.

**Pull request closed without merging**
