### PR TITLE
Run2-hcx139 Update geometry access for Hcal cells

### PR DESCRIPTION
**Pull request by bsunanda**
In view of collapsed depths in Plan 1 reconstruction

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
eff_globaltighthalo2016
eff_globalsupertighthalo2016
These two plots of efficiency demonstrate that the modified code improve the efficiency (the earlier version gives much lower efficiency particularly for the tight version)

**Comment by slava77** [comment]
On 7/26/17 7:47 AM, bsunanda wrote:
> These two plots of efficiency demonstrate that the modified code improve
> the efficiency (the earlier version gives much lower efficiency
> particularly for the tight version)

please post plots for efficiency before the change to actually be able
to compare.

Thank you.

**Comment by dvannerom** [comment]
Dear Slava,

Here are the same plots but with the bugged version of the code. You can see the very low efficiency of the tight version, while the supertight is ok.

[eff_globalsupertighthalo2016_bug.pdf](https://github.com/cms-sw/cmssw/files/1177533/eff_globalsupertighthalo2016_bug.pdf)
[eff_globaltighthalo2016_bug.pdf](https://github.com/cms-sw/cmssw/files/1177532/eff_globaltighthalo2016_bug.pdf)



Cheers,
David

**Comment by slava77** [comment]
IIUC, there is no DQM for these quantities.
Why not?

I will add GlobalTightHaloId2016 and GlobalSuperTightHaloId2016 to reco fwlite-based monitoring

**Comment by mariadalfonso** [comment]
@slava77 
If I recall correctly these (or an older version of these) were part of the METfilters DQM suites

In this specific case some of the HEP17 merged hits, w/o this fix get assigned and unphysical position at eta,phi=0,0

**Comment by slava77** [comment]
On 7/27/17 1:49 PM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77>
> If I recall correctly these (or an older version of these) were part of
> the METfilters DQM suites


I ran on 2017B workflows from the matrix
136.781,136.782,136.783,136.784,136.788
200 events each and none of them showed any differences.
My fwlite based plots clearly show there is a change in these workflows
in BeamHaloSummary.GlobalTightHaloId2016
So, my conclusion is it is not in DQM

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19910	1bb9470
- ``` HcalHaloAlgo::getPosition(const DetId &id ``` now uses HcalGeometry to get the cell position, instead of CaloGeometry directly, which apparently doesn't return the right value for HEP17
- jenkins tests pass and comparisons show no differences (monitoring is apparently lacking)
- local test with 2017 data workflows and added monitoring of the halo id variable shows expected behavior with much smaller tag rate; e.g. in 136.783 
all_sign947vsorig_runjetht2017b136p783c_recobeamhalosummary_beamhalosummary__rereco_obj_globaltighthaloid2016

**Comment by mariadalfonso** [comment]
@slava77 
These are the list of METfilters in DQM and indeed the latest version of the Halo is not up to date
https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/DQMOffline/JetMET/python/metDQMConfig_cfi.py#L108-L116

@ramankhurana will take care of updating in a separate PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
