### PR TITLE
MTD Validation: Characterization of PU contribution in vertices

### PR DESCRIPTION
**Pull request by rdelliga**
PR description:

Plots added to Primary4DVertexValidation.cc to monitor the impact of Pileup in order to compare different vertex reconstruction algorithms. For details see the presentation at https://indico.cern.ch/event/1390639/contributions/5846174/attachments/2816069/4924070/MTD_DPG_March_DelliGatti.pdf
Furthermore, EDM_ML_DEBUG from MtdTracksValidation.cc, integrated with pull request #43741, was removed.

PR validation:

Code compilation and production of plots.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 any comment?

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
