### PR TITLE
Revert "CSJet update for fastjet-contrib 1.044"

### PR DESCRIPTION
**Pull request by silviodonato**
Reverts cms-sw/cmssw#30590

See https://github.com/cms-sw/cmssw/issues/30836

### CODE REVIEW

**Comment by perrotta** [comment]
It is strange: the error reported in https://github.com/cms-sw/cmssw/pull/30838#issuecomment-661098586 says that there is one extra argument in RecoJets/JetProducers/plugins/CSJetProducer.cc:117 (the "true" argument).
But #30590 exactly removed that extra argument! How can it be supposed to be still there?

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
tests with  cms-sw/cmsdist#6103 are ok

**Comment by jfernan2** [comment]
+1

**Pull request merged**
