### PR TITLE
drop type specs in RecoMuon

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: Update the safer syntax for existing parameter
Instead of modifying parameters with full type specs, which can be interpreted as an insertion of a new parameter, it is a safer way to protect from parameter name mistakes and will also help in possible parameter migrations.
(The references were [PR#29979](https://github.com/cms-sw/cmssw/pull/29979), [PR#30147](https://github.com/cms-sw/cmssw/pull/30147).)

RecoMuon/{GlobalMuonProducer, StandAloneMuonProducer, MuonIdentification, MuonSeedGenerator, L2MuonSeedGenerator, TrackerSeedGenerator} were considered in this PR.

RecoMuon/Configuration can found in previous [PR#30270](https://github.com/cms-sw/cmssw/pull/30270).

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Type specification in cloned /modified python configs dropped as planned
- Jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
