### PR TITLE
AlCaReco matrix update

### PR DESCRIPTION
**Pull request by tocheng**
Update the AlCaReco matrix in the release (autoAlCa.py) to match the AlCaReco matrix twiki https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#25_ns_2e34_collisions_13_TeV
and Tier-0 configuration 
http://cmst1.web.cern.ch/CMST1/tier0/ProdOfflineConfiguration.py

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@tocheng and I agreed on the fix: leave all keys of datasets already present in the alcareco matrix, and add keys for datasets which are specific to 2017

in second iteration, add AAG and corresponding update of alcarecotriggerbits in GT

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
