### PR TITLE
Cleanup of dependencies from CondDBv1 code

### PR DESCRIPTION
**Pull request by ggovi**
The changes of PR #13108 have been re-built in a new branch cherry-picking the commits from the original branch and applying them on the last IB:
- Clean up from CondDBv1: removed dependencies from packages: CondCore/DBCommon, CondCore/ORA, CondCore/MetaDataService, CondCore/TagCollection, in particular in Configuration/StandardSequences/python/FrontierConditions_GlobalTag_cfi.py used by cmsDriver to set up condition access.
- Added TagLog functionality
- Added the possibility to configure Frontier connection in order to request the server sends digital signatures on every response. This is done by setting a string data member in ConnectionPool or the corresponding parameter in a ParameterSet. An unit test has been added. The default is "", so the current behaviour is kept.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by diguida** [comment]
@ggovi the failure in `runtestSimCalorimetryHGCalSimProducers` is not related to this PR: indeed I was able to reproduce it on vanilla IB, and it also appears on [CMSSW_8_0_X_2016-01-28-2300 unit tests](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-01-28-2300/unitTestLogs/SimCalorimetry/HGCalSimProducers), even if is marked as OK in the [IB summary page](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/thu/8.0-thu-23/CMSSW_8_0_X_2016-01-28-2300). It looks like the HCal QIE condition in the upgrade MC GT is not compatible with the HGCal geometry, but this should be clarified with experts.

The other one, in fact, is related to che changes in `RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py`. In the test configuration [`PhysicsTools/PatAlgos/test/patTuple_PF2PAT_cfg.py`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/test/patTuple_PF2PAT_cfg.py) there is a [call](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/test/patTuple_PF2PAT_cfg.py#L12) to the function [`usePF2PAT`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/python/tools/pfTools.py#L402). This function [loads the PAT sequences applying a postfix to the module labels](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/python/tools/pfTools.py#L413) using the function [`loadWithPostfix`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/python/tools/helpers.py#L18).
The module `RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py` is included in [the PAT sequence fragment](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/python/patSequences_cff.py) via subsequent imports: `RecoTauTag/Configuration/python/HPSPFTaus_cff.py -> PhysicsTools/PatAlgos/python/recoLayer0/tauDiscriminators_cff.py -> PhysicsTools/PatAlgos/python/producersLayer1/tauProducer_cff.py -> PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py -> PhysicsTools/PatAlgos/python/patSequences_cff.py`
The `PoolDBESSource` instance labelled `loadRecoTauTagMVAsFromPrepDB` is therefore visible in the PAT sequences namespace, and is relabelled with the `PFlow` postfix. But, the module `RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py` in this new version has also the "original" `PoolDBESSource` labelled `GlobalTag` which is later cloned. So, also this one is relabelled with the `PFlow` postfix. Given that the `ESSource` named `GlobalTag` is anyhow present in the process configuration, loaded from [`Configuration/StandardSequences/python/FrontierConditions_GlobalTag_cff.py`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Configuration/StandardSequences/python/FrontierConditions_GlobalTag_cff.py#L3), we yield an `ESSource` conflict.

The fix is to define the `PoolDBESSource` instance in the `RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py` module, not importing and cloning it from the original `cfi`.

**Comment by diguida** [comment]
@ggovi the fix is https://github.com/cms-sw/diguida/commit/61fbbe4c3311686f460c554b7037bc8c5bfa30ee

**Comment by diguida** [comment]
@ggovi the fix is https://github.com/diguida/cmssw/commit/61fbbe4c3311686f460c554b7037bc8c5bfa30ee

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@mmusich @franzoni @mulhearn 
same changes as before, re-packaged in a new PR... please take action

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
@mulhearn 
Could you please take action?

**Comment by davidlange6** [comment]
lets hope that the 3rd time is the charm...

**Pull request merged**
