### PR TITLE
Add TEveGeoShape header

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Adds header for TEveGeoShape type after the yet another ROOT cleanup
to the files that uses the type. 

#### PR validation:

Bulilds without complain from cmssw compilation

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/5952

**Comment by mrodozov** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by smuzaffar** [comment]
@civanch, @mdhildreth can you please sign this for simulation. It only adds a missing header of `vector` in one of simulation related file.

**Comment by civanch** [comment]
+1

hope, that unit tests will be fixed soon

**Comment by smuzaffar** [comment]
@silviodonato , can you please merge this for next IB so that we can update root for ROOT6 IBs.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
