### PR TITLE
Phase2-hgx201 Provide Corner Centric Geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

A new geometry version for HGCal is provided. The v11 version will have the wafer centric geometry for the EE part (same as in V10) and corner centric geometry for the HE wafers

#### PR validation:

Tested the workflows of the earlier geometry versions (V8, V9, V10). Reconstruction geometry is to be tested to make a meaningful workflow for V11

#### if this PR is a backport please specify the original PR:

No back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
