### PR TITLE
Second tuning of Pixel cluster shape cut for Phase 2

### PR DESCRIPTION
**Pull request by ebrondol**
After the PR #16943 where the parameters of SiPixel local reco have been changed to match the specs of the phase2 read-out chip, a second tuning of the pixel cluster shape cut for Phase 2 has been done.
Few changes in performance - but nothing drastic - are expected.

informing @delaere @atricomi @boudoul

### CODE REVIEW

**Comment by ebrondol** [comment]
@slava77 since this PR is going to change some performance, while the PR I submit yesterday (#17106) is just updating the documentation, I would prefer to keep them separate. Let me know if you have any problem with that..

**Comment by slava77** [comment]
@cmsbuild please test

@ebrondol 
no problem with having two separate PRs, they are covering different features

Have you run some tests with PU200 to see that timing stays under control?

Do you have any visual representation of the changes in the cluster shape at the lower level (e.g. cut value vs cluster size or something natural wrt definition of the cut)?

**Comment by slava77** [comment]
@ebrondol 
please clarify from which workflow are your plots in the PR description

**Comment by slava77** [comment]
I observe virtually no differences after running in CMSSW_9_0_0_pre2
- 500 events 10 mu E 0 to 200 without PU (20011.0,22811.0,23611.0 or D7, D4Timing and D9)
- 100 events ttbar with PU200 D4Timing (wf 23034) 

The efficiency plot from 22811 "/DQMData/Run 1/Tracking/Run summary/Track/generalPt09_trackingParticleRecoAsssociation/effic" with this PR shows a plot similar to what was posted in the PR description in red
general_eff_vs_eta_min075


Is something missing in this PR (is the .par file change all that's needed) ?

**Comment by ebrondol** [comment]
Hi @slava77 , yes, the file .par is the only change needed in principle. I have used 1k events coming from RelValSingleMuPt10Extended with 0PU (wf 21218).

**Comment by slava77** [comment]
On 1/9/17 2:42 AM, ebrondol wrote:
> Hi @slava77 <https://github.com/slava77> , yes, the file .par is the
> only change needed in principle. I have used 1k events coming from
> RelValSingleMuPt10Extended with 0PU (wf 21218).
> 

In this case, I should see the changes in the tenmu samples,
but I don't.
I will check on the same sample, just to be sure.

Which release did you use?
It might be worth to double-check that the correct file was pushed to
the PR.

**Comment by ebrondol** [comment]
Hi @slava77 , I am also double checking in CMSSW_9_0_X_2017-01-08-2300 with the WF #21218.0. I will post the results before the end of the day.

**Comment by ebrondol** [comment]
With the same statistic, I see what you also reported: http://ebrondol.web.cern.ch/ebrondol/Phase2Tracking/PR17110/SingleMuPt10Extended/plots_ootb/effandfake1.pdf
no difference between with or without the PR. This is very strange..

**Comment by slava77** [comment]
@ebrondol 
did you happen to gain some better understanding of the issue in this PR of the lack of changes in more recent tests compared to the tests done before the PR submission?

Since you were able to reproduce the lack of changes, maybe it is still possible to go back to the setup that had desired changes and compare/debug.

**Comment by ebrondol** [comment]
@slava77 After some test, I think that the lost of efficiency is due to another problem and cannot be solved with this re-tuning. Said so, probably would be good to put this PR in release to keep consistency between the geometry/digitization and the tuning (with no changes on the performance).

**Comment by slava77** [comment]
On 1/13/17 1:24 AM, ebrondol wrote:
> @slava77 <https://github.com/slava77> After some test, I think that the
> lost of efficiency is due to another problem and cannot be solved with
> this re-tuning. 

> Said so, probably would be good to put this PR in
> release to keep consistency between the geometry/digitization and the
> tuning (with no changes on the performance).

OK.
Please update the PR description to match the expected little impact on
performance (it now has the plots suggesting significant improvements in
efficiency)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17110	5c1751c
- pixelShape_Phase2Tk.par update for consistency with the new tracker response parameters
- jenkins tests pass and comparisons show only small changes
- local tests on larger samples confirm that changes are small as noted earlier in the thread

**Comment by davidlange6** [comment]
+1

**Pull request merged**
