### PR TITLE
Make Geometry/CaloEventSetup package compile with C++20

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all.

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by iarspider** [comment]
type bug-fix

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Failed unit test occasionally fails in IBs as well (supposedly grid proxy file gets overwritten by another test running on the same machine)

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
please abort
(tests were already succesfull, no need to waste resources by relaunching them)

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
