### PR TITLE
Fixing the seed formation check in CA iterations of FastSim -- backport to 10_2_X

### PR DESCRIPTION
**Pull request by ssekmen**
backport of #25758

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
please test workflow 2017.1

**Comment by fabiocos** [comment]
hold

from @franzoni @srimanob : this is not needed by SUSY production so far in 10_2_X

**Comment by fabiocos** [comment]
@ssekmen @sbein as agreed I close this PR

**Pull request closed without merging**
