### PR TITLE
 Change SiPixel LA PCL naming in autoPCL file [12.1.X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/36182

#### PR description:

Inspired by the mistake in dmwm/T0#4635 (review)
We propose to rename this mapping to be consistent with the wf name. It is necessary in order for the ALCAHarvesting step to succeed, see https://github.com/dmwm/T0/pull/4635#discussion_r753606998 as `autoPCL` is used in the `ConfigBuilder`

https://github.com/cms-sw/cmssw/blob/06f15e3ce91f53b005847b384d4027117598a9d7/Configuration/Applications/python/ConfigBuilder.py#L2071
#### PR validation:

Tried to run
`runTheMatrix.py -l 1001.2`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/36182 necessary in order to run a replay with this release.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by malbouis** [comment]
+alca

- changes inline with the description
- needed in 121 release for testing the Pixel LA PCL workflow in a Tier0 replay with that release.

**Comment by srimanob** [comment]
+Upgrade

Backport.

**Comment by bbilin** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
