### PR TITLE
EGamma Scale & Smearing For Re-miniAOD : 94X

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All,

This is the backport of https://github.com/cms-sw/cmssw/pull/22531 with 94X specific fixes (mainly to do with defaultModule labels in fill descriptions)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #22531

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22623	4932e82
- this introduces scale and smearing userFloats in pat electrons and photons (which appear in the slimmedElectrons and slimmedPhotons collections). The feature is enables only in run2_miniAOD_94XFall17 context. 
- the backport from the master version is correct (consistent with https://github.com/cms-sw/cmssw/pull/22531	e0525c8); some differences in implementation are present due to somewhat unrelated differences between 94X and master.
- jenkins tests pass and comparisons with the baseline show differences only in 2017 reMINIAOD workflow 136.8311

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
