### PR TITLE
Reduce Alpaka event synchronization calls via EDMetadata [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport #44841 by @makortel to CMSSW 14.0.x:

> Prompted by [#44769 (comment)](https://github.com/cms-sw/cmssw/issues/44769#issuecomment-2067257800) this PR reduces the amount of blocking `alpaka::wait()` calls (leading to `cudaEventSynchronize()` on NVIDIA GPU) via the EDMetadata destructor. To check the impact I used the reproducer #44769 (even if it eventually leads to an assertion failure). Initially the reproducer lead to 2470 calls to `cudaEventSynchronize()`.
> 
> The first commit avoids calling `alpaka::wait()` in `EDProducer::produce()` when no asynchronous work was launched (possible async work is identified by the use of `device::Event::queue()` in any way, including consuming a device side data product). In this case there is no need to synchronize the device and host. This commit reduced the number of `cudaEventSynchronize()` calls to 2284 (-7.5 %).
> 
> The second commit caches the alpaka::Event completion, so that `alpaka::wait()` does not need to be called again on an already-completed alpaka Event. This commit reduced the number of `cudaEventSynchronize()` calls to 2019 (-18 % wrt the starting point).
> 
> The third commit avoids calling `alpaka::wait()` on the destructor of an `EDMetadata` when the Queue of the `EDMetadata` object has been re-used by another `EDMetadata` (in an `EDProducer::produce()` that consumed the device-side data product holding the first `EDMetadata` object). Since the only purpose of the `alpaka::wait()` in the `~EDMetadata()` is to ensure all asynchronous work of an edm::Event has completed before the edm::Stream moves to the next edm::Event, for any Queue it is enough to `wait()` on the alpaka::Event that was last recorded on that Queue. This commit reduced the number of `cudaEventSynchronize()` calls to 1462 (-40 % wrt the starting point).
> 
> There is one case left (on purpose) where the `EDProducer::produce()` still calls `alpaka::wait()`. This happens when the `produce()` launches asynchronous work (i.e. calls `device::Event::queue()`), but does not produce any device-side data products. I can't imagine a good use case for such an EDProducer (except maybe a DQM-style module, but that would need a separate module base class in any case that could then deal with the necessary edm::Event-level synchronization
> 
> I don't expect a huge impact from the reduction of these calls, as in the present cases in HLT the alpaka::Events should have completed by the time the `alpaka::wait()` is called. The stack traces in [#44769 (comment)](https://github.com/cms-sw/cmssw/issues/44769#issuecomment-2066613569) nevertheless show the `cudaEventSynchronize()` acquiring a lock even when the CUDA event was complete at the time the event was recorded, so at least this PR should reduce the contention on that lock.
> 
> Resolves [cms-sw/framework-team#902](https://github.com/cms-sw/framework-team/issues/902)

#### PR validation:

`HeterogeneousCore/Alpaka{Core,Test}` unit tests pass.

Test with a recent HLT menu on top of `CMSSW_14_0_5_patch2` shows a minor improvement in throughout:
  - `CMSSW_14_0_5_patch2`: 670.5 ± 1.9 ev/s
  - with these changes: 673.0 ± 2.0 ev/s

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44841 to CMSSW 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #44841

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

**Pull request merged**
