### PR TITLE
DNN-based Tau-Id discrimians (94X) - Squashed version of PR 25385

### PR DESCRIPTION
**Pull request by fabiocos**
This PR is the squashed version of #25385 , kept to preserve the review history.
The unwanted addition/deletion of very large files is here removed.
A direct comparison with the merge of the original code on top of CMSSW_9_4_X shows no difference.

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
@mbluj FYI

**Comment by perrotta** [comment]
please test
(external cms-sw/cmsdist#4580 is already merged now)

**Comment by perrotta** [comment]
@fabiocos : if there are no other counter-indications, could you please merge this PR in 94 at your earliest convenience, so that @mbluj can go on with the update of #25488? Thx

**Comment by fabiocos** [comment]
see my comment https://github.com/cms-sw/cmssw/pull/25385#issuecomment-453479804 the problem does not appear in the code-checks of #25385 even if the code is identical (tested comparing the produced patches, and comparing branches after merging separately the PRs).

**Comment by perrotta** [comment]
+1
- This is identical to #25385, which was already signed by reco in https://github.com/cms-sw/cmssw/pull/25385#issuecomment-444165043:
  - New DNN-based Tau-Id discriminants are made available for analyses: they don't run in official central workflows
  - (Same comment as in #25016) Memory footprint is still rather large (O(100MB/evt)) , but nonetheless deemed acceptable for the usage this code is intended to: if and when it will be requested to be included in some central sequence meant to production some further assessment and study should be performed, as well as some deeper investigation of the timing performance (which from the first results does not seem to be a concern, anyhow)
  - Since central sequences used in production are not touched by this PR, its possible backport has no counterindications
  - Jenkins tests pass and show no differences
- Signing this one just in case we want to follow the suggestion of @fabiocos in https://github.com/cms-sw/cmssw/pull/25385#issuecomment-453499390 (which I endorse)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
