### PR TITLE
HCAL: update(psm) of DPGAnalysis/HcalTools  for Run3 

### PR DESCRIPTION
**Pull request by zhokin2**
- new directories are added to provide Phi-Symmetry Monitoring
for different Global(!) runs with aim of preparation of
hcal calibration by Iteration method and
Method of Moments (calibration group);

talk of Olga Kodolova, which can clarify Method of Moments:
https://indico.cern.ch/event/1099868/contributions/4627590/attachments/2353777/4016084/phi_symmetry_mm_26112021.pdf

my talk on HCAL DPG Workshop (14-15 Oct) 2021. See p.8-10 to clarify PSM implementation:
https://indico.cern.ch/event/1082970/contributions/4565247/attachments/2328302/3966806/HCAL-DPG-Workshop2021.pdf

 - macros corrected for use TFileservice

 - updates and bugs fixed in some scripts 
            regarding CMT and RMT

 last talk on DPG meeting:
https://indico.cern.ch/event/1099868/contributions/4629402/attachments/2353858/4016211/zzzhcal72.pdf

#### PR validation:
1)
scram build code-checks
scram build code-format
scram b

2)
the CMT, RMT and PSM tests  were done locally and with use of cms-sites :
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/AMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/RMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/CMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/GlobalRMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/GlobalPSM
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/ALCARECOPSM
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/IMPSM

### CODE REVIEW

**Comment by abdoulline** [comment]
@zhokin2  Sasha, could you, please, edit your PR name to make less cryptic and more meaningful (self-explanatory) -
something like  
"HCAL:  update of  DPGAnalysis/HcalTools"

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
@zhokin2 @abdoulline all this code looks like private HCAL code, not meant for any centrally run workflow: can you please confirm?

Also the `CMTRawAnalyzer` plugin seems to be meant only to some local HCAL monitoring. see
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_3_X_2022-03-03-2300&_filestring=&_string=CMTRawAnalyzer&_casesensitive=1

If so, we can fully rely on your evaluation and review for assessing the usefulness of this update in the centrally managed software, and merge it based on it (without inspecting in detail the 90k+ modified lines of code)

Please let us know.

**Comment by abdoulline** [comment]
@perrotta  ( and @zhokin2)  
yes, this is a set of proprietary HCAL tools, not meant to run in any central wf.

**Comment by perrotta** [comment]
+1
- (Thank you Salavat for confirmation)

**Pull request merged**
