### PR TITLE
[DD4hep] Introduce FilteredView nextChild

### PR DESCRIPTION
**Pull request by ianna**
This allows to dramatically improve performance by cutting the iteration over the rest of the tree

* FilteredView `nextChild()` will stop iteration when a level set by a `firstChild()` is reached
```c++  
  fview.firstChild();
  do {
    // do something here
   ...
   } while (fview.nextChild());
```
See `DDFilteredView.firstChild.cppunit.cc` unit test

@bsunanda, @fabiocos, @slomeo, @vargasa, @ghugo83  - FYI

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
The unit test failure doesn't seem related to this PR:
```
===== Test "materialBudgetHGCalPlots" ====
+ geom=Extended2026D62
+ VGEO_DIR=/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry
+ TEST_DIR=/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/materialBudgetHGCalPlots
+ '[' -d /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/materialBudgetHGCalPlots ']'
+ mkdir /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/materialBudgetHGCalPlots
+ cd /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/materialBudgetHGCalPlots
+ cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/single_neutrino_cfg.py nEvents=1
+ python /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-08-1100/src/Validation/Geometry/test/runP_HGCal_cfg.py geom=Extended2026D62 label=HGCal

---> test materialBudgetHGCalPlots had ERRORS

```

**Comment by cvuosalo** [comment]
Is there documentation explaining how to use the `DDFilteredView` methods like `firstChild`, `nextSibling`, `goTo`, `level`, and so on? It seems like they have subtle behavior that developers need to know to use them correctly.

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
