### PR TITLE
Concurrent Path Processing

### PR DESCRIPTION
**Pull request by Dr15Jones**
Allow Paths and EndPaths to run concurrently within one Event.
This change properly handles dependencies between modules on different paths (a module on one path will wait until a module on another path has finished). In addition unscheduled modules can now safely depend on scheduled modules.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar the tests actually aborted by CMS-bot didn't seem to notice

**Comment by smuzaffar** [comment]
@Dr15Jones , tests were aborted after 15 hours. Though I have restarted the tests but I am afraid it will again abort as I see workflows are hanging. I see runTheMatrix timeout after 3 hours.

**Comment by Dr15Jones** [comment]
Hanging is a possibility with this code change. Guess I'll have to re-compile the world myself since I don't want DEVEL that broken :).

**Comment by Dr15Jones** [comment]
I brought in more of the changes from #15740

**Comment by smuzaffar** [comment]
please test
(I abort the previous test)

**Comment by Dr15Jones** [comment]
@smuzaffar this fixes a case where the framework would get stuck during RelVal processing. I don't know if this is the last of them though.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar Is this using a different version of ROOT which has a change in header?

**Comment by smuzaffar** [comment]
@Dr15Jones , no root version is exactly the same. Both IBs
  - CMSSW_8_1_DEVEL_X_2016-09-19-2300 where compilation failed
  - CMSSW_8_1_DEVEL_X_2016-09-19-1100 where compilation worked but tests were stuck
are using the exactly the same version of root i.e. /cvmfs/cms-ib.cern.ch/2016-39/slc6_amd64_gcc530/lcg/root/6.06.08

**Comment by Dr15Jones** [comment]
@smuzaffar But was the package `PhysicsTools/MVAComputer` built the first time? I bet my change to `FastTimerService` might have triggered the system to build `PhysicsTools/MVAComputer` but this is the first time that package has been built since you changed ROOT. It looks like all _DEVEL builds since you change ROOT have been patch builds which could have missed this problem.

**Comment by smuzaffar** [comment]
@Dr15Jones , no package ```PhysicsTools/MVAComputer``` was also built for CMSSW_8_1_DEVEL_X_2016-09-19-1100. 
After the root update, there is first a full build i.e. CMSSW_8_1_DEVEL_X_2016-09-18-0000 where ```PhysicsTools/MVAComputer``` was built too

**Comment by Dr15Jones** [comment]
I used this pull request with CMSSW_8_1_X_2016-09-18-2300 yesterday and it did rebuild PhysicsTools/MVAComputer without any problem.

**Comment by smuzaffar** [comment]
I am testing it locally to see why it works for 1100 and not for 2300

**Comment by smuzaffar** [comment]
@Dr15Jones , looks like cvmfs cache on vocms0302 (where compilation failed twice) is corrupted. I see this warning in the build logs
```
/var/build/muz/CMSSW_8_1_DEVEL_X_2016-09-19-2300/src/PhysicsTools/MVAComputer/src/TreeReader.cc:11:19: warning: /cvmfs/cms-ib.cern.ch/2016-39/slc6_amd64_gcc530/lcg/root/6.06.08/include/TLeaf.h is shorter than expected
```

compilation works on other build machines. I am restarting the tests now in jenkins

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones,  tests again timed out. Should we merge this a get at least one IB based on it?
By the way there are merge conflicts now.

**Comment by Dr15Jones** [comment]
@smuzaffar I rebased on top of CMSSW_8_1_X but it didn't complain about any conflicts. Weird. Assuming the rebase did avoid the merge problems I think we are at the point where we should just put this into CMSSW_8_1_DEVEL_X. If it breaks it, we just back it out.

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
Ok, I am merging it for next IB.

**Comment by Dr15Jones** [comment]
This build failure is not from this pull request and will show up in the next IB. The problem is #15096 is not compatible with #15897.

**Pull request merged**
