### PR TITLE
EMTF Emulator Update to Add Displaced Muon pT & Dxy Assignment

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR is a resubmission of #32641 which was reported to have thread safety issues in cms-sw/cmsdist/issues/6618. The thread safety issues are fixed by removing the 'static' calls in `PtAssignmentEngineDxy`.

This PR updates EMTF emulator by adding a new class (`PtAssignmentEngineDxy`) that handles vertex unconstrained pT and Dxy assignment. The changes should not affect anything for prompt muons. The main changes are:

- Added `PtAssignmentEngineDxy` and necessary changes to the EMTF algorithm to support it.
- Added setters and getters for vertex unconstrained pT and Dxy to `EMTFTrack`

The backport of this PR to 11_2_X (#32642 ) is already updated/

#### PR validation:

Validated with:

- scram b runtests
- runTheMatrix.py -l limited -i all --ibeos

Notifications: @jiafulow

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by eyigitba** [comment]
This PR once again depends on the data file at: https://github.com/cms-data/L1Trigger-L1TMuon/pull/19. Should I resubmit that PR as well?

**Comment by silviodonato** [comment]
test parameters:
- pull_request = cms-data/L1Trigger-L1TMuon#19

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2 (@duartej @rekovic )

**Comment by duartej** [comment]
> kind reminder @cms-sw/l1-l2 (@duartej @rekovic )

I think you mean @jmduarte :)

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
Seems that this PR could be causing segfaults in ROOT master IBs, see #32894 for more details. (it is very much unclear to me why the crashes are specific to ROOT master)

**Comment by eyigitba** [comment]
Hi @makortel , thanks for letting me know. I have no idea why this might be. I'll investigate.

**Pull request merged**
