### PR TITLE
uTCA-related HCAL DQM Changes

### PR DESCRIPTION
**Pull request by vkhristenko**
@elaird 
@abdoulline

Will submit for 74X next

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
I've checked the output of the test. There I found something I haven't
expected.
would it possible for me to introduce a change/do another commit(I will do
that for 75,74,73) and then retest it again???
Thanks!

VK

**Comment by abdoulline** [comment]
Viktor, if you have found something to be fixed, I'd suggest you to do it on your branch directly, in this case it's    vkhristenko:CMSSW_7_5_X_HCALDQMuTCA).  
Then the test will be re-run...

**Comment by abdoulline** [comment]
Is  there any chance to have it in 7_5_0_pre3? 
This stuff is *urgently* needed for data taking (with 7_3_X) so we need to have it in 7_3_X right after it's approved here in 7_5_X.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
ok, it was tested already..   :)

**Comment by abdoulline** [comment]
My impression is that the test failures are not related to the PR itself...

**Comment by vkhristenko** [comment]
That is the impression I get. On top, previous test didn't catch that and I
didn't change anything related to something what throws this exception.

**Pull request merged**
