### PR TITLE
MTD geometry and reco: code cleaning

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses some (minor) pending comments on MTD code tracked in #24452 and references therein. 

#### PR validation:

Code compiles, geometry local tests show no differences on both scenario D50 and D73.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Simple cleanup
- Jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
