### PR TITLE
Remove ROOT dictionary provided now by latest ROOT 6

### PR DESCRIPTION
**Pull request by smuzaffar**
(cherry picked from commit 12ddef952f1c87037bddefe010996704e2998970)
this should be tested with cms-sw/cmsdist#3145

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3145

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#3145

**Comment by slava77** [comment]
I thought a compile error like in ``` using ::fenv_t; ``` is an indication of a transient build problem; but then this one seems reproducible.
@smuzaffar 
any ideas?

**Comment by smuzaffar** [comment]
@slava77 , I also thought that this was transient but looks like it is not. Changes here are already in ROOT6 IBs (both cmssw and cmsdist). So I would just merge it for 23h00 IBs to get an IB build based on.

**Comment by smuzaffar** [comment]
@cmsbuild please test with cms-sw/cmsdist#3145
one last try. I have fixed cmsdist PR testing script to move away the local gcc install directory to so that root only see gcc from cvmfs. I hope this shoudl fix this build error.

**Pull request merged**
