### PR TITLE
Import NanoAOD-tools postoprocessor to CMSSW [13.0.X]

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

Plain backport of #42323 (addressing #43379).

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by vlimant** [comment]
is this good to sign @clelange @lenzip ?

**Comment by clelange** [comment]
> is this good to sign @clelange @lenzip ?

Yes, thanks for checking!

**Comment by vlimant** [comment]
+1

**Pull request merged**
