### PR TITLE
Pr93x L1T new emtf emulator

### PR DESCRIPTION
**Pull request by rekovic**
PR 93x New (2017) EMTF emulator

- faster (10x)
- better fw/emul agrrement
- allows for emulation of RPC use in EMTF
- needs new EMTF LUTs
- removes old EMTF emulator

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3127

**Comment by davidlange6** [comment]
-1
too big to review - please divide into several (10?) prs.

**Comment by rekovic** [comment]
@davidlange6 
> too big to review - please divide into several (10?) prs.

Indeed.

**Comment by rekovic** [comment]
@davidlange6  
(cc @abrinke1 )

This PR is going to be subdivided in a few PRs.
As the changes include the DataFormat, Unpacker, DQM, Emulator and CondFormats, the idea is
that individual PRs contain and adress the following:

PR 1) Changes in DataFormats so to not disrupt running of modules of current Unpacker, DQM, Emulator
PR 2) Changes in Unpacker so to not disrupt modules of current DQM, Emulator
PR 3) Changes in DQM to use new unpacker and new DataFormat
PR 4) Changes in Emulator to use new DataFormat. 
PR 5) Changes in DQM to use the new Emulator
PR 6) Changes in CondFormats and O2O

Maybe some of these PRs can be combined (example PR1 and PR2, or PR4 and PR5), but will decide
depending on number of files that require changes.

**Comment by abrinke1** [comment]
@rekovic Thanks for opening this.  @rekovic @davidlange6 : I'll be starting from code that's currently in l1t-integration-CMSSW_9_2_5_patch2, but since I'll be making the changes file-by-file for each PR, I can start from any "bare" CMSSW release.  Should I make the PR into cms-sw:master, or somewhere else?  Which bare CMSSW release should I build on top of?

Thanks,
Andrew

**Comment by rekovic** [comment]
@abrinke1 
If going to start from a stable release, and hope the relevant packages don't change underneath, 
I would suggest to use the latest stable release, i.e. CMSSW_9_2_6, which came out 2 days ago. 
PRs should to into cms-sw:master.

**Comment by abrinke1** [comment]
Starting with PR #19741

**Pull request closed without merging**
