### PR TITLE
Properly setup meta data in LHESource

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The branch list related meta data is now properly set.

#### PR validation:

Code compiles and problem seen in #43713 also corrected.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cms-sw/generators-l2 Could you please review? It would be great to have this in CMSSW_14_0_0_pre3.

**Comment by makortel** [comment]
urgent

**Comment by menglu21** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
