### PR TITLE
fix syntax error in TTStub.h

### PR DESCRIPTION
**Pull request by VinInn**
I fixed it w/o making a issue.
Too trivial to discuss.

found while compiling with clang 19

### CODE REVIEW

**Comment by VinInn** [comment]
As usual with template functions: do not ask how it compiled this now

**Comment by VinInn** [comment]
@cmsbuild : please test

**Comment by VinInn** [comment]
DO not understand
code check just removed that tab!

I do not have time to fight against this things. 
please fix . (whoever feels responsible)

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
