### PR TITLE
Backport from ExoValDev_75X_PR1

### PR DESCRIPTION
**Pull request by ryonamin**
The changes are same as #7908

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
looks like this is crashing the IBs

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_4_X_2015-03-09-1400/pyRelValMatrixLogs/run/1312.0_ZpMM_13+ZpMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15/step3_ZpMM_13+ZpMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15.log

will revert for now.

**Comment by ryonamin** [comment]
I become to doubt something related to accessing beamspot. In order to investigate the cause, which input sample should I use to reproduce the problem? It doesn't happen for the sample I use, so I think I need a proper sample to reproduce the problem. Thank you for your help in advance!

**Comment by davidlange6** [comment]
runTheMatrix.py -l 1312 -i all

in a recent 74x integration build should reproduce the crash

seems more like that a null monitor element is being accessed…

**Comment by ryonamin** [comment]
Thank you for your instruction. I have just noticed that the problem is caused by a bug that was already fixed in #8058 (for 75X). So I would like to backport the changes to 74X. Do I need just to create a new PR now or should I do this after reverting?

**Comment by deguio** [comment]
please create a new PR and add some comment about the crash being fixed.
thanks,
F.

**Comment by ryonamin** [comment]
I have just made a new PR ( #8178 ). Thank you in advance.

**Pull request merged**
