### PR TITLE
[JMENano] Update taggers for AK4 Puppi and CHS

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR updates the taggers for AK4 Puppi and CHS jets in JMENano production. All the relevant taggers for AK4 Puppi jets are set to be computed for the newly reclustered collection and only one tagger is made available for AK4 CHS jets (since it is a backup collection). The updates did not make it in time for #42728.

#### PR validation:
- passes the standard runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

#### If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 13_2_X for 2022 & 2023 JMENano samples production campaign. Probably can be included in #42887 once this PR is merged?

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

@nurfikri89 please add this to https://github.com/cms-sw/cmssw/pull/42887 if needed for the upcoming production

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
