### PR TITLE
Fix DQM warnings from FSQ client during cosmics workflows

### PR DESCRIPTION
**Pull request by fruboes**

### CODE REVIEW

**Comment by ktf** [comment]
@cmsbuild please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
thanks @fruboes 
why don't you remove the fsq module from:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DQMOffline/Configuration/python/DQMOfflineCosmics_SecondStep_cff.py

instead from
 Configuration/StandardSequences/python/HarvestingCosmics_cff.py
?

in this way we don't spread the sequence definition all around CMSSW.

sounds good?
thanks,
F.

**Comment by ktf** [comment]
@degano what happened to the tests?

**Comment by degano** [comment]
@ktf this PR is suffering from the missing refs bug. I restarted the tests pointing to the branch instead.

**Comment by fruboes** [comment]
Dear @deguio,

 sorry for a late reply. I should be able to look at this again early next week

Cheers,
  Tomasz

**Comment by ktf** [comment]
Any updates on this?

**Comment by fruboes** [comment]
should be ready soom, apologies for a very late followup

**Comment by fruboes** [comment]
Created a new PR: https://github.com/cms-sw/cmssw/pull/7570

**Comment by ktf** [comment]
Please close this one.

**Pull request closed without merging**
