### PR TITLE
MTD validation : update modules' names

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The name of MTD validation modules is updated by adding the suffix "Valid" to allow them to be better identified within the stack of executed plugins.

#### PR validation:

Test workflow 35007.0 runs succesfully.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@gsorrentino18 FYI

**Comment by fabiocos** [comment]
The failures in DQM comparison look unrelated to this PR (and I see them mentioned in other discussions in Mattermost)

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
