### PR TITLE
Run3-hcx377 Backport the changes made to the HcalTopolog class and additional hcalRecoNumbering constants from #46357, #46369, #46374

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the changes made to the HcalTopolog class and additional hcalRecoNumbering constants from #46357, #46369, #46374

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport #46357, #46369, #46374

### CODE REVIEW

**Comment by bsunanda** [comment]
backport

**Comment by bsunanda** [comment]
urgent

**Comment by bsunanda** [comment]
Type backport

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
