### PR TITLE
HLT menu development for `12_3_X`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`. Includes the integration of the following JIRA tickets:

 - [CMSHLT-2187](https://its.cern.ch/jira/browse/CMSHLT-2187): updates for Run-3 tracking, incl. CPU part of new heterogeneous pixel local reco, and pixel tracking+vertexing
 - [CMSHLT-2206](https://its.cern.ch/jira/browse/CMSHLT-2206): addition of paths `Status_OnCPU` and `Status_OnGPU`
 - [CMSHLT-2207](https://its.cern.ch/jira/browse/CMSHLT-2207): CPU part of heterogeneous ECAL local reco
 - [CMSHLT-2208](https://its.cern.ch/jira/browse/CMSHLT-2208): CPU part of heterogeneous HCAL local reco

The PR also includes a syntax improvement suggested in https://github.com/cms-sw/cmssw/pull/36536#discussion_r772528120 (credits: @perrotta).

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Why 'enable gpu' ?

**Comment by missirol** [comment]
> Why 'enable gpu' ?

To test the `GRun` menu in conjuction with the Patatrack customisation. In my understanding, that happens in wf `11634.506`, which can be included with "enable gpu".

**Comment by missirol** [comment]
> In my understanding, that happens in wf 11634.506, which can be included with "enable gpu".

Just to be more precise: as far as I know, the workflows included by "enable gpu" in the PR tests are listed [here (`11634.{506,512,522}`)](https://github.com/cms-sw/cms-bot/blob/a85ee5cb0b563f3eaa6dceb7d4ced88cf5554fc3/cmssw-pr-test-config#L2), and in all 3 of them the GPU (Patatrack) customisation is applied to the HLT menu [here](https://github.com/cms-sw/cmssw/blob/1d3499ad1b75471d95460bfe1d676295dbe88842/HLTrigger/Configuration/python/customizeHLTforCMSSW.py#L152) via the `gpu` process modifier (e.g. [from here](https://github.com/cms-sw/cmssw/blob/1d3499ad1b75471d95460bfe1d676295dbe88842/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L575)).

**Comment by missirol** [comment]
The outputs of the PR tests look okay, but I have to finish checking a few more things before signing.

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1
- There are several changes in trigger related DQM plots for Run3 wfs, vaidated by the HLT signature here

**Pull request merged**
