### PR TITLE
Added firstLuminosityBlockForEachRun to ProducerSourceBase

### PR DESCRIPTION
**Pull request by Dr15Jones**
Using firstLuminosityBlockForEachRun allows one to trigger a new Run with a specific Run number to be started if a LuminosityBlock of a certain LuminosityBlock number is generated.
This is intended to be used by the Run dependent MC.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
ping

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

the compilation warnings were unrelated to this PR

**Pull request merged**
