### PR TITLE
L1 filters using P2GT for tau paths

### PR DESCRIPTION
**Pull request by agrubercms**
#### PR description:

This PR adds an L1 filter based on the L1P2GT for the Phase-2 tau HLT paths. 
As reported in [HLT Upgrade](https://indico.cern.ch/event/1424038/#sc-2-5-taus), we see lower efficiency upon including the L1 filter, but it achieves a great speed-up in the HLT menu timing, and an L1 filter will be needed eventually in any case (Also, the integration of new L1 tau seeds, once available, will be straightforward after this PR).

### CODE REVIEW

**Comment by mmusich** [comment]
enable hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@agrubercms please remove the Draft label from this PR.

**Comment by agrubercms** [comment]
Hi @rovere,
I should be able to produce results this week still - however, I'm afraid that they will show a significant impact on the efficiencies of the tau paths, which should probably be discussed before merging this PR. 
I could aim to present results in next week's HLT Upgrade meeting for a discussion, would that work for you?

**Comment by mmusich** [comment]
hold
   * pending clarifications on https://github.com/cms-sw/cmssw/pull/45041#issuecomment-2133083677

**Comment by rovere** [comment]
> Hi @rovere, I should be able to produce results this week still - however, I'm afraid that they will show a significant impact on the efficiencies of the tau paths, which should probably be discussed before merging this PR. I could aim to present results in next week's HLT Upgrade meeting for a discussion, would that work for you?

That would be a surprise: in all slides presented by L1T, the turn-on for taus is quite sharp and the plateau is at 90+% or so [see here, page 19](https://indico.cern.ch/event/1344917/contributions/5661250/attachments/2801385/4887361/Phase2L1T-HLTUpgrade_15022024.pdf).

Let's wait for your studies. Next week at the HLT Upgrade meeting is ok.
Thanks.

**Comment by artlbv** [comment]
Hi there, just saw this (from the tsg slides).
Do I understand correctly, that you haven’t used any L1 decision to seed this path previously? It would be odd but I would like to clarify..

**Comment by artlbv** [comment]
@rovere while you are right about the higher efficiency in the plateau, note that for low pt taus the efficiency is not that high. And from these HLT paths it seems the thresholds are below the expected gen pt plateau (52 GeV as in the L1 seed name).

**Comment by agrubercms** [comment]
Hi @artlbv, 
That's correct - the HLT tau paths for Phase-2 do not use any L1 seed yet (that's also why there's such a big improvement in timing by a rather small change)

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/45041#issuecomment-2149171684

**Comment by rappoccio** [comment]
+1

**Pull request merged**
