### PR TITLE
fix broken DQM tests

### PR DESCRIPTION
**Pull request by deguio**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@nclopezo  there must be something wrong with the tests here..
could you please restart them?
thanks,
F.

**Comment by nclopezo** [comment]
Hi @deguio,
There was a glitch in Jenkins. I restarted them.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
