### PR TITLE
Adding E, R and Z ranges to CloseByParticleGun generator

### PR DESCRIPTION
**Pull request by tonydp03**
#### PR description:

This pull request is made because we want to introduce a range in Energy, R and Z in the CloseByParticleGunProducer Workflow. Now in the configuration file the energy, R and Z ranges must be specified, while the ParticleGun will select a random Energy, R and Z in those ranges.
In addition, a working snippet is added in the Generators folder.

@felicepantaleo
@rovere

### CODE REVIEW

**Comment by tonydp03** [comment]
The possibility to produce particle in a given window (in R and phi) has been added (now it's possible to have particles overlapping). The snippet has been modified properly has well.

**Comment by alberto-sanchez** [comment]
please test

**Comment by tonydp03** [comment]
The energy smearing was moved inside the for loop over the particles of the same event (particles produced in a given event won't have necessarily the same energy now).

**Comment by civanch** [comment]
please test

**Comment by alberto-sanchez** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
