### PR TITLE
Added dependency on py2-sqlalchemy

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR adds py2-sqlalchemy dependency for unit tests to make sure it is run when py2-sqlalchemy is updated.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5023

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5023

**Comment by smuzaffar** [comment]
ping bot

**Comment by fabiocos** [comment]
@ggovi this looks quite straightforward to me, could you please check and sign or comment?

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
