### PR TITLE
Added generated HT (genHT) EDFilter module

### PR DESCRIPTION
**Pull request by mzarucki**
EDFilter module which takes a GenJet collection as input, calculates the generated HT (genHT) based on a HT definition (GenJet pt and GenJet eta cuts as input parameters) and returns a boolean based on whether the genHT passes the genHT cut (also input parameter).

### CODE REVIEW

**Comment by vciulli** [comment]
I think GenJets collection includes isolated leptons and photons. 
The filter will not distinguish between a hadron jet and a high pT muon from a W decay
Is it the intended behaviour? 

Vitaliano

**Comment by mzarucki** [comment]
Dear Vitaliano,

Yes, this is true. However, this way of filtering is conservative: it might result in a smaller reduction rate, however, efficiency is not lost. Moreover, the effect is very small for our low-lepton-pt samples.

Therefore, we would propose to leave the script unchanged.

Best regards,
Mateusz Zarucki

**Comment by covarell** [comment]
We do not need this in 7.6.x, which is only used for RECO.
Please make PRs for 8.0.x and 7.1.x

**Comment by covarell** [comment]
-1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
