### PR TITLE
bsunanda:Run2-hcx52 Remove obsolete instantiations of HcalTopology in some test jobs

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@ggovi @davidlange6 Please take a look. We plan to remove the older constructor of HcalTopology at the earliest
________________________________

**Comment by bsunanda** [comment]
Could you please take a look to see if it can be integrated
________________________________
From: Sunanda Banerjee
Sent: 18 November 2015 12:30
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-hcx52 Remove obsolete instantiations of HcalTopology in some test jobs (#12447)

@ggovi @davidlange6 Please take a look. We plan to remove the older constructor of HcalTopology at the earliest
________________________________

**Comment by ggovi** [comment]
+1

**Pull request merged**
