### PR TITLE
[DQM] Fix copy-constructor warnings reported in DEVEL IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Hello,

This PR solves the DEVEL warnings on deprecated copy-constructors present in the IBs on some DQM modules.

Thanks,
Andrea

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by aandvalenzuela** [comment]
I need to rethink those changes, maybe in favor to explicitly define the missing components

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

- After further discussion, I changed the approach to define the missing parts

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
