### PR TITLE
Restore v0 validation  

### PR DESCRIPTION
**Pull request by rovere**
This PR will put back in place a bare minimal, working, V0 Validation package. The package can be expanded at will, depending on man-power availability. This very same package will have to be tuned so that we can run it also on real data. To be discussed with current DQM L2.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11653	4f34bac
- the only change in reco-related is in  Validation/Configuration/python/postValidation_cff.py 
with addition of the postProcessorV0.
- jenkins tests pass and comparisons with baseline show no differences, in particular in Validation/DQM output comparisons for MC (where the modified v0Validator is running)

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@rovere - looks like this is throwing exceptions in the IBs - please fix (or I can revert, as you prefer)

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-10-19-1100/pyRelValMatrixLogs/run/25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT/step3_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT.log

**Comment by rovere** [comment]
I already submitted #11972 to fix the triggered assertion (which did its job in finding a genuine bug). There was a thread last night w/ @slava77

**Pull request merged**
