### PR TITLE
Backport of #9532: More All-In-One tool improvements

### PR DESCRIPTION
**Pull request by hroskes**
The primary addition here is "preexisting" validations, which make it possible to configure the All In One tool to include validations that were already run into plots, without running them again.

This is independent of running validations on 74X data.  I separated that in #9551 because its purpose is different.

This is orthogonal to #9536 and #9551, they should merge together without a problem.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
failures unrelated to this PR

**Comment by diguida** [comment]
please test

**Comment by hroskes** [comment]
@cmsbuild I'm sorry

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild please test
trying again....

**Comment by hroskes** [comment]
I think @cmsbuild is confused

**Comment by mmusich** [comment]
please test 
trying still another time...

**Comment by hroskes** [comment]
@mmusich I just did commit --amend and then push -f, maybe @cmsbuild will reset now that there's a new commit.  (I didn't actually change anything)

**Comment by mmusich** [comment]
pleaset test

**Comment by hroskes** [comment]
Thanks for your repeated support!

> pleaset test

I think we still need one more iteration without the extra t

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
