### PR TITLE
Hlt tau validation conditional plotting2

### PR DESCRIPTION
**Pull request by slehti**
Same as  HLTTauDQM: conditional plotting #30243

Removed problematic merge and continued with this new branch HLTTauValidation_ConditionalPlotting2

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@slehti sorry, but still Static check errors:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-57469a/7967/llvm-analysis/runStaticChecks.log

**Comment by jfernan2** [comment]
Same comments as in previous PR #30243 
https://github.com/cms-sw/cmssw/pull/30243#issuecomment-656852675

**Comment by perrotta** [comment]
-1
Please rebase to get rid of unrelated commits

**Comment by slehti** [comment]
Did not manage to rebase. Cherry-picked, refused to be added in this branch. Closing, and continuing in branch HLTTauValidation_ConditionalPlotting3.

**Pull request closed without merging**
