### PR TITLE
Phase2-gex28 Add a new cff for simulation - useful for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new cff for simulation - useful for dd4hep

#### PR validation:

Tested using the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
