### PR TITLE
Fix gcc10 warning in KDTreeLinkerAlgo

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Switched to using bitwise operation instead of multiplication.

I did not decide to switch to the boolean operation (&&) because of the comment in the code a few lines above the change.

#### PR validation:
The code compiles without a warning using gcc 10.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
