### PR TITLE
add track hit eff monitoring vs inst. lumi

### PR DESCRIPTION
**Pull request by mtosi**
back port of PR https://github.com/cms-sw/cmssw/pull/14857

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
lumiScalers.isValid() was not enough to avoid missing / not valid input collection
I've just added the check on the size of the lumiScalers collection
I ran runTheMatrix and it seems to be fine, now

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
I see that you are closing this, thanks

I'm very interesting on understanding why a fully signed PR was not integrated (as many others)....
I think this is a real waste of resources and time (of many people)

I do not want to make a case, of course
but I hope we can improve this in the near future
I cannot think it will continue like this

have a nice day
@VinInn @rovere @fwyzard @gennai @dmitrijus @vanbesien @cerminar @klute @davidlange6

**Comment by davidlange6** [comment]
I don’t believe it has been merge-able  for a few months now (and DQM never brought it up to the release meeting as far as I see)

**Comment by makortel** [comment]
Could cms-bot maybe be extended notify when there a merge conflict appears?

**Comment by davidlange6** [comment]
it has that functionality at least to some extent. not sure its easy to generalize without getting a bunch of spam from PRs that stay with a merge conflict, but will bring up the question @smuzaffar

**Comment by makortel** [comment]
Ok (in that case my personal preference would be to avoid spam).

**Comment by davidlange6** [comment]
yes, definitely

**Pull request closed without merging**
