### PR TITLE
Add track selection MVA plots to tracking DQM (92X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #19481. Original description:

> This PR adds distributions and profiles vs. pT and eta of the track selection MVA output for each tracking iteration with an MVA track selection. For the cases where an iteration makes use of multiple MVA selectors (as in phase0), a similar logic is used as in MultiTrackValidator, i.e.
> - For the first MVA there is one histogram called "MVA1"
> - For the second MVA there are two histograms
>   * "MVA2" for tracks not selected as loose by the first MVA
>   * "MVA2HP" for tracks not selected as highPurity by the first MVA
> - Same for third MVA (and possibly onwards)
> 
> I also removed two obsolete configuration parameters (OutputMEsInRootFile and OutputFileName) to not hit the 255 parameter limit (and needing to modify the entire TrackingMonitor_cfi).
> 
> Tested in CMSSW_9_2_3. Expecting new histograms in phase0 and phase1, and no changes in phase2.
> 

@rovere @VinInn @mtosi @hajohajo

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Same as #19481 in the master
- Modifications are in DQM, no reco quantities affected

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
