### PR TITLE
UL remini updates: fix running PUPPI, add egamma scale and smearing

### LINKED ISSUE #29823: REMINIAOD workflows crash
The following workflows are crashing since CMSSW_11_1_X_2020-05-13-1100
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_1/2020-05-13-1100?selectedArchs=slc7_amd64_gcc820&selectedFlavors=X&selectedStatus=failed

```
136.76111 RunJetHT2016E_reminiaodUL+REMINIAOD_data2016UL_HIPM+HARVESTDR2_REMINIAOD_data2016UL_HIPM
136.88811 RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL
1325.516 TTbar_13_reminiaod2016UL_preVFP_INPUT+REMINIAOD_mc2016UL_preVFP+HARVESTDR2_REMINIAOD_mc2016UL_preVFP
1325.5161 TTbar_13_reminiaod2016UL_postVFP_INPUT+REMINIAOD_mc2016UL_postVFP+HARVESTDR2_REMINIAOD_mc2016UL_postVFP 

```
with the error
```
----- Begin Fatal Exception 13-May-2020 14:12:45 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 18 event: 1707 stream: 0
   [1] Prefetching for module PFCandidateDQMAnalyzer/'ElectronValidation1'
   [2] Prefetching for module PATElectronSlimmer/'slimmedElectrons'
   [3] Prefetching for module PATElectronSelector/'selectedPatElectrons'
   [4] Prefetching for module PATElectronProducer/'patElectrons'
   [5] Prefetching for module CITKPFIsolationSumProducerForPUPPI/'egmElectronPUPPIIsolation'
   [6] Calling method for module PATPackedCandidateProducer/'packedPFCandidates'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap&lt;float&gt;
Looking for module label: puppi
Looking for productInstanceName: 

----- End Fatal Exception -------------------------------------------------
%MSG-w MemoryCheck:  PATPackedCandidateProducer:packedPFCandidates  13-May-2020 14:12:45 CEST Run: 1 Event:
```
The workflows were added by #29756

Workflows 1325.517 and 1325.518 are crashing as well with a DAS error, but I think this was expected (see https://github.com/cms-sw/cmssw/pull/29756#issuecomment-625238866)

### PR DESCRIPTION
**Pull request by slava77**
- fix running PUPPI, add egamma scale and smearing : 
    - this resolves #29823 (a catchup to #29769 merged in 05-10-0000)
- add egamma scale and smearing, as expected to be used in reminiAOD
    - this is a catch-up to #29526  (merged 05-10-0000)

tested on 136.88811

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29826	6e23152 
- the wf 136.88811 now runs OK
- based on no differences in comparisons, the other existing workflows are not affected as expected

**Comment by slava77** [comment]
@silviodonato 
it looks like the fix in this PR worked.
Regarding other PR tests failing due to 136.88811, they could be retested with this PR if necessary.

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
