### PR TITLE
Updates for GE1/1-ME1/1 and GE2/1-ME2/1 integrated trigger

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR updates the GE1/1-ME1/1 and GE2/1-ME2/1 trigger. 

#### PR validation:

Performance plots (for the Phase-2 L1T TDR) can be found here:
https://indico.cern.ch/event/860248/contributions/3623026/attachments/1935792/3207809/L1T_PlotsForApproval_GEMCSC_SD_20191024.pdf

#### if this PR is a backport please specify the original PR:

N/A

@davignon @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
This PR is needed in preparation for the upcoming Run-3 MC production.

**Comment by fabiocos** [comment]
please test

**Comment by dildick** [comment]
I removed the unused variable.

**Comment by fabiocos** [comment]
please test

**Comment by dildick** [comment]
@rekovic Can you please sign this PR? Thanks.

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
