### PR TITLE
[HGCAL trigger] Apply code-format

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:

Apply code-format to:
- DataFormats/L1THGCal
- L1Trigger/L1THGCal
- L1Trigger/L1THGCalUtilities

#### PR validation:

No validation done.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
