### PR TITLE
update track candidate DQM code

### PR DESCRIPTION
**Pull request by mtosi**
backport PR https://github.com/cms-sw/cmssw/pull/10125

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mtosi** [comment]
any news on this ?
thanks

**Comment by mtosi** [comment]
as for https://github.com/cms-sw/cmssw/pull/10125,
the customization for run1 has been updated

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
@rovere Marco, does the latest change make  sense?

**Comment by rovere** [comment]
@slava, yes it does.

**Comment by deguio** [comment]
+1
equivalent of #10373 + #10126

**Comment by cvuosalo** [comment]
+1

For #10127 ae90f533ba260074477190270199b4bbef9644c9

Adding some tracking DQM plots. There should be no change in other monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-08-02-2300 show no significant differences, as expected. Checking T0 configs shows the new code doesn't introduce any configuration problems.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
