### PR TITLE
Move L1TMuonPhase2/Constants.h to L1TMuonPhase2 dataformat package

### PR DESCRIPTION
**Pull request by smuzaffar**
This Pr moves `L1Trigger/Phase2L1GMT/interface/Constants.h` header to `DataFormats/L1TMuonPhase2/interface/Constants.h` to avoid dataformats dependency on `L1Trigger/Phase2L1GMT` package. This should fix the FWLite build errors too.

This is just a technical update and can be merged as soon as the build part is done ( no need to wait for full addon, relvals and comparison tests).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
@smuzaffar tests succeed. I don't know about the fwlite build, but I imagine you already tested it.
I would be tempted to merge it without waiting for the @cms-sw/l1-l2 and @cms-sw/dqm-l2 signatures: do you see any counterindication?

**Comment by smuzaffar** [comment]
@perrotta I would suggest to go ahead and merge it. I can trigger an IB now if needed

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
