### PR TITLE
[12_3_X] Do not fetch PixelClusterCountsInEvent when the handle is not valid

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/37712

#### PR validation:

test parameters:
  - workflows = 1001.2,1020

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/37712

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 1001.2,1020

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37712

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by perrotta** [comment]
@tvami thank you for the fix!
I'd give your signature for granted, now that tests succeed also in 12_3. But I'll let you have the chance to look once again at it in the next hour or so, before force merging in time to have this included in the 1100 IB.

**Comment by mmusich** [comment]
> But I'll let you have the chance to look once again

I think Tamas is currently on US Eastern time, so there are slim chances he'll we awake in the next hour or so. 
Perhaps @francescobrivio could sign instead?

**Comment by perrotta** [comment]
> > But I'll let you have the chance to look once again
> 
> I think Tamas is currently on US Eastern time, so there are slim chances he'll be awake in the next hour or so. Perhaps @francescobrivio could sign instead?

Good point. Let force merge it now, then.
Tamas, you'll have time to complain (if you want so...) when you wake up,  and in any case before when we start building the new release :-)

**Comment by perrotta** [comment]
+1
- Fix for https://github.com/cms-sw/cmssw/pull/37671

**Comment by perrotta** [comment]
merge

**Comment by tvami** [comment]
Haha no complains. Indeed, just woke up :)

**Comment by tvami** [comment]
+alca
 * for the record

**Pull request merged**
