### PR TITLE
[DQM] Update `compareDQMOutput.py`

### PR DESCRIPTION
**Pull request by nothingface0**
#### PR description:

Add a `-u`/`--dqmgui-url` argument, which allows specifying the DQMGUI url to upload the results to.  Defaults to `https://cmsweb.cern.ch/dqm/dev/`

This is so that the script can be used decoupled from the specific DQMGUI, and can be used on private machines as well.

#### PR validation:

None, will be done through the cmsbuild tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be 
Not a backport.

### CODE REVIEW

**Comment by rseidita** [comment]
please test

**Comment by rseidita** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
