### PR TITLE
Phase2-hgx335Q Add tests to investigate non-zero cassette shift in HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add tests to investigate non-zero cassette shift in HGCal geometry

#### PR validation:

Use the new test code for investigating non-zero cassette 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
