### PR TITLE
multithreading fix for 74x: E/Gamma HLT modules

### PR DESCRIPTION
**Pull request by fwyzard**
EgammaHLTNxNClusterProducer: change into a stream::EDProducer
HLTRegionalEcalResonanceFilter: change into a edm::stream::EDFilter

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at ##11317

**Comment by fwyzard** [comment]
backport #10955 / #10967 to 74x

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
