### PR TITLE
Run4-hgx289 Update the validation scripts for HGCal to test the V16 version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the validation scripts for HGCal to test the V16 version

#### PR validation:

Use the scripts in the Validation/HGCalValidation/test/python to validate 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @qliphy @silviodonato @perrotta The unit failure is not linked with this PR. It is in the current IB against which it is tested. Could care be taken for that?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @qliphy @silviodonato @perrotta @jefran2 The unit failure is not linked with this PR. I am not sure what is causing this. I only updated a few test script files which are used to validate HGCal geometry in this PR. Please suggest what could be the cause of this

**Comment by qliphy** [comment]
@bsunanda  should be related to https://github.com/cms-sw/cmssw/issues/34520 
there is a fix to be merged soon: https://github.com/cms-sw/cmssw/pull/34532

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
