### PR TITLE
Prescale access for stage-2 environment (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Prescale access for stage-2 environment (80X).
Backport of 81X PR #14312

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
assign dqm

similar to #14312 , this PR inadvertently breaks some EWK DQM

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14336	7b75fce
- changes in RECO-related code are only to pass stage2-related input tags in PhysicsTools/PatAlgos/python/triggerLayer1/triggerProducer_cfi.py . This PR has the same changes as in #14312
- jenkins tests pass and comparisons with baseline show no reco-related differences related to this PR.
    - some of the EWK monitoring is broken, e.g.
wf134911_ewkdqm_etaleadjet
this is to be handled or followed up by DQM L2

**Comment by Martin-Grunewald** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14336	2f2eaab
- there was no change related to reco since the last signoff at 7b75fce; the changes are the same as in https://github.com/cms-sw/cmssw/pull/14312	1737d36
- jenkins tests pass; the /Ewk DQM plots mentioned earlier are still empty

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@rekovic @mulhearn
Please sign asap as well!

**Comment by rekovic** [comment]
+1

**Comment by gpetruc** [comment]
Tested on the run and lumisection reported in https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3469.html : miniAODs produced with 8_0_8 + this PR give the right HLT prescale values (while 8_0_8 out of the box does does not).

However, L1 prescales are still reported to be all equal to 1

**Comment by Martin-Grunewald** [comment]
For L1T some separate CondDb / GT work is still needed.

**Comment by Martin-Grunewald** [comment]
@dmitrijus
Can you please now sign this PR?
Thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Who signs for "analysis" these days?
Could you please do so asap?
Thanks!

**Comment by davidlange6** [comment]
no one - we’ll merge once we can retest on the new IB. presumably that is this afternoon. Cheers

**Pull request merged**
