### PR TITLE
Add B physics wfs to release validation

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Adds BuToJPsiPrimeKToJPsiPiPiK and Psi2SToJPsiPiPi to the list of the upgrade wfs used in the release validation studies.

#### PR validation:

Tested on 11715.0 and 11716.0.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
test parameters:
workflows = 11715.0,11716.0

**Comment by kskovpen** [comment]
please test

**Comment by AdrianoDee** [comment]
+upgrade
- adding wfs for B Physics in the release

**Comment by perrotta** [comment]
+1

**Pull request merged**
