### PR TITLE
change of the argument definition of some reco::Muon functions 

### PR DESCRIPTION
**Pull request by Fedespring**
#### PR description:
This would be a more clean fix to the issue described in this PR
https://github.com/cms-sw/cmssw/issues/23057

#### PR validation:
No changes are expected from this PR. The main check is to be sure that this doesn't break anything. All the integration tests have been successfully done, those failed (which are 25) are failing the step0 (no das input file).

### CODE REVIEW

**Comment by slava77** [comment]
@Fedespring 
please edit the PR title to be clear of the subject of changes you are proposing.
Some more explicit description would be nice as well.
Thank you.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- More proper way of resolving the issue #23057 that the previos pr #23599: if type returns to be a reco::Muon::ArbitrationType there is no need any more of the check that it does not exceed 7
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
