### PR TITLE
Hcal relval update 9_X_Y digi amplitude

### PR DESCRIPTION
**Pull request by bcmcms**
“Updated digi amplitude plots to support the phase1 upgrade digis' expanded ranges.”

### CODE REVIEW

**Comment by abdoulline** [comment]
@kmaeshima, @vanbesien, @vazzolini, @dmitrijus can you please review it and eventually sign? Thanks.

**Comment by abdoulline** [comment]
@bcmcms - please, don't hesitate to remind reviewers that the PR stays idle for quite some time.

**Comment by bcmcms** [comment]
Thanks!

Yes, hopefully this PR can be signed off soon.

**Comment by abdoulline** [comment]
@kmaeshima, @vanbesien, @vazzolini, @dmitrijus   ping...

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
