### PR TITLE
HCALDQM: same as 18618 for 9_1_X

### PR DESCRIPTION
**Pull request by DryRun**
Same as 18618 for 9_1_X. Includes important fix for a crash in RecHitTask.

### CODE REVIEW

**Comment by dmitrijus** [comment]
backport of #18618

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
The runTheMatrix failures were due to the use of HFPreRecHits to determine the HF dual anode asymmetry (since they don't exist in old data). I have reverted the commits involving HFPreRecHits.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
