### PR TITLE
Fix string quoting for CLI.

### PR DESCRIPTION
**Pull request by bbockelm**
Previously, the quoting of the CPU model output did not obey ClassAd rules for a string.  This implements a reasonable subset (throwing out the difficult parts; if a CPU model contains a double-quote character, we'll lose it).

This is the 8_2_X equivalent to PR #17316

### CODE REVIEW

**Comment by Dr15Jones** [comment]
backport #17316

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
@bbockelm what is driving the need for a backport?

**Comment by bbockelm** [comment]
We're already getting some monitoring information for the `CPUModels` attribute from `PhaseI*` workflows, but it's currently dropped due to the incorrect quoting.  I'd like to actually get this performance data so we can feed it forward to the WLCG performance monitoring group.

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
there is not 8_2_X release cycle? Do we need this PR here?

**Comment by bbockelm** [comment]
This needs to go into whatever release cycle current PhaseII GEN-SIM is on...

**Pull request closed without merging**
