### PR TITLE
Migrate DQMOffline/Alignment and CondTools/DQM to esConsumes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.
   * migrated to `esConsumes`  subsystem `DQMOffline/Alignment` 
   * migrated to `esConsumes`  subsystem `CondTools/DQM`
   * analyzers in `CondTools/DQM` have been modernized

Part of https://github.com/cms-sw/cmssw/issues/31061

#### PR validation:

Compiles + run `scramv1 b runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport is needed.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
