### PR TITLE
BTagCalibrationReader: move to RecoBTag/PerformanceDB, interface updates.

### PR DESCRIPTION
**Pull request by HeinerTholen**
- The BTagCalibrationReader class is moved from CondFormats/BTauObjects to RecoBTag/PerformanceDB. The reason is that it is not stored into the database and maintenance needs only to be signed off by the btag conveners.
- The current implementation of BTagCalibrationReader assumes that there is only one measurementType for all jet-flavors, where, in the 50ns scale factors, we have "mujets" for B- and C-flavor and "comb" for UDSG. => Interface change.
- In the analysis one needs to know min- and max-pt for a given jet-flavor, eta and discr value, in order to handle the uncertainty if it's out of bounds. A function for returning the pt-bounds is added, so that the user does not need to hardcode values for that.

### CODE REVIEW

**Comment by HeinerTholen** [comment]
This PR is intended for user analysis. Should I create pull requests for all subsequent releases as well (CMSSW_7_5_X, _7_6_X, _8_0_X)?

**Comment by slava77** [comment]
The code modified here performs manipulations of objects defined in CondFormats/BTauObjects and nothing else. I think it should stay there in Cond* area (maybe to decouple the format defined in CondFormats/BTauObjects from the tools interpreting these objects it's better to have it in CondTools/BTau).
Reco* is meant for algorithms/code manipulating  with (collision) event data.

**Comment by HeinerTholen** [comment]
Hi Slava, thanks for your reply. 
CondTools/BTau does not yet exist, but I'll happily create it. 
There are a couple more files in RecoBTag/PerformanceDB that only concern the manipulation of database objects. Can I move them all at once?

**Comment by slava77** [comment]
@mmusich @diguida 
please comment.
My long-standing preference (mentioned earlier in the thread) is to have code manipulating purely with objects from CondFormats to be in Cond* area.
What's your opinion?
Is CondTools a good place?

**Comment by mmusich** [comment]
@slava77 I share your opinion. I let @diguida comment more if needed.

**Comment by slava77** [comment]
@HeinerTholen 
ping

**Comment by slava77** [comment]
-1 
based on earlier comments

**Comment by HeinerTholen** [comment]
@slava77 How should we proceed here? Should I go on and move the code into CondTools/BTau? Does @diguida agree?

**Comment by slava77** [comment]
Hi 
yes.
I think https://github.com/cms-sw/cmssw/pull/12469#issuecomment-158423834 was the note of action.

**Comment by ferencek** [comment]
@HeinerTholen, to answer one of your earlier questions, yes, we also want these changes in the subsequent release cycles. 75X might be an exception, though, since it won't be used for the pp data.

**Comment by diguida** [comment]
@HeinerTholen, all
sorry to chime in so late...
I would propose the following:
1. move all your reader code for condition objects for b-tagging into the new package `CondTools/BTau`: this means moving, `BTagCalibrationReader` definition and implementation (`classes.h` and `classes_def.xml` are needed only for reflection, so you can safely ignore them in the move), along with the tests
2. keep the changes in `RecoBTag/PerformanceDB` as a consequence of the re-shuffling in the code
3. open a PR in 80X, with back ports into 76X and 74X: the former is for 2015 re-reco, the latter is for prompt and MC (you can re-sue this branch, if needed).

HTH

**Comment by ggovi** [comment]
-1
Already rejected, please update or close it.

**Comment by HeinerTholen** [comment]
Hi. Sorry for the long silence, I was very involved in an analysis for Moriond. I'll work on this in the next two weeks and will prepare a pull request with 81X.

**Pull request closed without merging**
