### PR TITLE
Add --nStreams option in runTheMatrix

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Enable "--nStreams" option to runTheMatrix, and add "EventStreams" to the relvals workflow.

#### PR validation:
Test with runTheMatrix command, the workflow looks OK.
runTheMatrix.py --what upgrade -l 23234.21 -t 8 -m 5400 --nStreams 0 --wm init
runTheMatrix.py --what upgrade -l 23234.21 -t 8 -m 5400 --nStreams 4 --wm init
runTheMatrix.py --what upgrade -l 23234.21 -t 8 -m 5400 --wm init

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Maybe 11_1, but we can use dirty fix for prod-like HLTTDR relvals for now (as urgent need)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
