### PR TITLE
LowPtElectrons: updates for nano v10

### PR DESCRIPTION
**Pull request by bainbrid**
#### PR description:

Small devs aimed at low-pT electrons in the future nano v10 production in CMSSW_12_4_X cycle.

- adds a new LowPtElectron_electronIdx branch that 'cross links' low-pT and PF electrons
- remove unnecessary tasks (Ereg and ID) for nano v10, while preserving nano v9 functionality

#### PR validation:

Tested with wfs:
- 1325.81 (MC, TTbar, 2017) for nano v8 
- 136.8523 (data, RunJetHT2018C) for nano v9
- 11834.21 (MC, TTbar, 2021) for nano v10

@mariadalfonso @gouskos

### CODE REVIEW

**Comment by bainbrid** [comment]
The "cross linking" functionality is achieved through a deltaR matching, performed [here](https://github.com/cms-sw/cmssw/pull/37137/files?show-viewed-files=true&file-filters%5B%5D=#diff-50ab5d45ffbbe54e11837e953a1142177fa00cb9c51c8f919f6123178c046782R186-R187). 

The tight cut of deltaR < 0.001 is motivated by the attached plot, which shows (y-axis) the ratio of pT values from the low-pT electrons and PF electrons vs (x-axis) the log10(deltaR) between the low-pT electron and the closest PF electron, as obtained from several thousand events in MINIAOD format from the wf 136.8523. Good pT matching is achieved for a population in which the deltaR matching is essentially exact, whereas a broad distribution is obtained for larger deltaR values, peaking at a ratio of ~0 for log10(deltaR) > -0.5 (i.e. deltaR > ~0.3). Arguably a tighter cut could be used, but 0.001 seems adequate. 

image

**Comment by mariadalfonso** [comment]
please test

**Comment by clacaputo** [comment]
I wasn't able to reproduce the error. WF `136.8522` runs without problem. I'll trigger the test again

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
Hi @bainbrid , all wf for `run2_miniAOD_80XLegacy, run2_nanoAOD_94XMiniAODv1, run2_nanoAOD_94XMiniAODv2, run2_nanoAOD_102Xv1, run2_nanoAOD_106Xv1` are failing with this error:

```bash
Calling method for module PATObjectCrossLinker/'linkedObjects'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: pat::Electron
Looking for module label: finalLowPtElectrons
```

Are you looking into this? Thanks

**Comment by bainbrid** [comment]
Hi @clacaputo, I was ... and then I was stalled (by other things). I will try to get back to this next week ...

**Comment by clacaputo** [comment]
Hi @bainbrid in which release do you plan to integrate this development? If it's CMSSW_12_3_X, could be useful to know that 12_3_0 is due by April 8th and a backport of this PR should be prepared

**Comment by gouskos** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- no reco changes expected

**Comment by bainbrid** [comment]
Do I need to do anything else here?

**Comment by mariadalfonso** [comment]
> Do I need to do anything else here?

As agreed over skipe
- test cross linking
- check small diffs, due to removing Ereg and ID? 
- remove DQM for v8 / earlier

**Comment by mariadalfonso** [comment]
please test workflow 136.72412, 136.72413

**Comment by qliphy** [comment]
> > Do I need to do anything else here?
> 
> As agreed over skipe
> 
>     * test cross linking
> 
>     * check small diffs, due to removing Ereg and ID?
> 
>     * remove DQM for v8 / earlier

@bainbrid   Any updates on above?

**Comment by gouskos** [comment]
Hi @bainbrid - gentle ping :)

**Comment by mariadalfonso** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- re-sign

**Comment by gouskos** [comment]
+xpog 
modifications inline with the PR description.
To be followed up: https://github.com/cms-nanoAOD/cmssw/issues/557#issuecomment-1123806798

**Comment by perrotta** [comment]
+1
- @bainbrid @cms-sw/xpog-l2 I imagine that a backport to 12_4_X is also needed

**Comment by bainbrid** [comment]
Ah yes ... will try to do it this week.

**Pull request merged**
