### PR TITLE
Do not apply DT vdrift correction (that accounts for field in phi SLs…

### PR DESCRIPTION
**Pull request by namapane**
… of wheels+-2 of MB1) when B=0.
This only affects reconstruction at B=0; effect on overall reconstruction is very small.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by namapane** [comment]
? this has nothing to do with CaloGeometryBuilder.

**Comment by nclopezo** [comment]
@namapane yes, the error is in the IB and is not related to this PR.

**Comment by slava77** [comment]
@cmsbuild please test 
the IB should be OK now (CMSSW_7_5_X_2015-05-28-2300 )

**Comment by slava77** [comment]
... it looks like jenkins is busy

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9314	bd7772d
- the same code changes as in the 74X equivalent (tested and signed off) https://github.com/cms-sw/cmssw/pull/9319	d138f91

**Pull request merged**
