### PR TITLE
Do not build/run cuda tests if cuda does not support gcc version

### PR DESCRIPTION
**Pull request by smuzaffar**
This make use of new cuda-gcc-support tool to build/run unit tests based in cuda gcc support. This should allow us to build error free GCC 820 IBs and releases.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4449

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4449

**Comment by makortel** [comment]
What should be (eventually) done for plugins that have `.cu` files? Something along
```xml
<iftool name="cuda-gcc-support">
  <library file="*.cc *.cu" name="FooPlugins">
    <flags EDM_PLUGIN="1"/>
  <library/>
<else/>
  <library file="*.cc" name="FooPlugins">
    <flags EDM_PLUGIN="1"/>
  <library/>  
</iftool>
```
(or can we do better)?

@fwyzard

**Comment by fwyzard** [comment]
@makortel do you mean to prevent building the .cu files ?

Long term, I am optimistic we will be able to build .cu files on all supported architectures: x86_64, ARM (Nvidia released CUDA 10 for Xavier's ARMv8), and POWER.

Clang is also making good progress in compiling CUDA code, and I hope they/we can write a drop-in replacement for nvcc based on clang itself.

Short term, we let them fail...

In fact, I am not sure building without the .cu files would actually work. The code in the .cc files may call some host functions implemented in the .cu files, so we would get a link error by simply excluding the .cu files.

**Comment by fwyzard** [comment]
@smuzaffar would it make sense to replace `<architecture match="_amd64_">` with `<iftool name="cuda-gcc-support">`, instead of using them both ?

**Comment by makortel** [comment]
@fwyzard I'm just wondering out loud what is the impact of this PR to the (future) plugins with CUDA code.

But yes, you're right, simply ignoring the `.cu` files will likely not work.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4449

**Comment by smuzaffar** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos  can we get this in? This should fix build time errors for gcc82

**Comment by fabiocos** [comment]
+1

**Pull request merged**
