### PR TITLE
Use common track-TP association in track and vertex validation

### PR DESCRIPTION
**Pull request by makortel**
Previously tracks and TrackingParticles were associated to each other separately in track (all tracks + once for each iteration, and x2 for high purity tracks) and in vertex validation. In this PR the production of these track-TP associations is consolidated (the gain in time is, however, small as making the track-TP association in the presence of ClusterTPAssociationProducer is relatively fast).

In order to continue to support the per-iteration efficiency plots, a generic helper function (`associationMapFilterValues`) is implemented to enable filtering key-value pairs from `AssociationMap` based on the value. This allows to do the track-TP associations once with full collections, and then for iteration-specific easily restrict the TP-track association to the tracks of that iteration.

The configuration interface of MultiTrackValidator is slightly modified to use the same parameter for delivering the InputTags for associations/associators. The flag `UseAssociators` dictates whether the associators (True) are used or the associations (False). All other uses than validation for pp (as found with `git grep`) are migrated.

In addition, I propagated the change from iteration numbers to names (#5807) to the labels of the iteration-specific track selectors. Since the names of the MTV histogram directories change anyway in this PR, this way we get these two renames of the directories into a single validation cycle (for sure).

Tested in CMSSW_7_5_X_2015-04-12-2300, but rebased on top of CMSSW_7_5_X_2015-04-21-2300 due to new configuration files in FastSim/Validation that had to be migrated. No changes expected in histogram contents.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
I have here https://mkortela.web.cern.ch/mkortela/tracking/pr8888/compareValHists.C a version of `compareValHists.C` used in alternative-comparisons properly mapping the old and new directory names so that the histograms can be compared (although manually).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
I realized only now that I had forgotten to update the "new" iteration names in the actual script files for plotting. The update has no effect on standard workflows (and tests).

**Comment by deguio** [comment]
ciao @makortel 
do you have an estimate on how much time is saved with the new code for the RECO+Validation step?
thanks,
F.

**Comment by slava77** [comment]
@cmsbuild the comparisons are still marked as "Queued"
could you please check what happened.

**Comment by nclopezo** [comment]
Hi Slava, 
I restarted the tests.

**Comment by makortel** [comment]
@deguio Good you asked (I hadn't measured it yet). It turns out that the performance gain is actually negligible (smaller than variance between single test jobs). The reason for why I initially thought that there should be improvement came from a profile of a job without ClusterTPAssociationProducer, in which case QuickTrackAssociatorByHits silently falls back to a significantly slower method
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/SimTracker/TrackAssociatorProducers/plugins/QuickTrackAssociatorByHitsProducer.cc#L166
(this is actually the second time I fell in this "fallback trap" while preparing this PR...)

We nevertheless think that this consolidation of the track-TP association between track and vertex validation is useful. (I'll update the PR description accordingly)

On a related matter, the igprof profiles did show that MultiTrackValidator itself is behaving badly (taking roughly half of the time of a RAW2DIGI,RECO,VALIDATION,DQM job on TTbar+35PU@25ns events). By quick look it should be easy to significantly reduce the timing, I'll follow this up in a subsequent PR.

**Comment by makortel** [comment]
I have the result.pdf's for alternative-comparisons (for simulation wfs) produced with `compareValHists.C` that maps the current and new directory names (https://github.com/cms-sw/cmssw/pull/8888#issuecomment-96693697) here
https://mkortela.web.cern.ch/mkortela/tracking/pr8888/

Quite a lot of "Mean" and "Sigma" histograms have small changes (due to numerical inaccuracies or something?). These histograms are produced in the HARVESTING step from gaussian fits in DQMGenericClient, and their input histograms (produced in VALIDATION step) are identical.

**Comment by cvuosalo** [comment]
+1

For #8888 1b94ce4fcd7d18d0812245231e419c5fe65ae5d5

This PR consolidates track and tracking particle association in track and vertex validation.

The code changes are satisfactory, as are the Jenkins test results. Extended tests were performed against baseline CMSSW_7_5_0_pre3, and the developer also performed [comparisons](https://mkortela.web.cern.ch/mkortela/tracking/pr8888/). The results from Jenkins, the extended tests, and the developer tests show several small DQM differences, but none are significant. Timing measurements do not show significant differences in reco times between the PR and the baseline.

**Comment by lveldere** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @makortel 

is this PR a likely cause of this new error?

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_5_X_2015-05-07-1100/pyRelValMatrixLogs/run/500207.0_NuGun_UP15+NuGun_UP15INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50+MINIAODMCUP1550/step3_NuGun_UP15+NuGun_UP15INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50+MINIAODMCUP1550.log

**Comment by davidlange6** [comment]
[which seems to be for events with nothing in the hard scatter event]

**Comment by makortel** [comment]
Likely yes, I'll take a look.

**Comment by makortel** [comment]
@davidlange6 Fix is in #9000.

**Pull request merged**
