### PR TITLE
Update the (pre|post)Source(Lumi|Run) signals

### PR DESCRIPTION
**Pull request by fwyzard**
Update the signals to pass
  - the `LuminosityBlockIndex` to the `(pre|post)SourceLumi` signals;
  - the `RunIndex` to the `(pre|post)SourceRun` signals.

Update the FastTimerService to make use of the updated signals to account for the time spent in the Source transitions.

Update the other clients code to ignore the new parameters.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

Hi @fwyzard, have you tested this DQM's Standalone.h shim?
If not, it is not much of an issue, just a bit more work for whoever compiles the gui.

**Comment by fwyzard** [comment]
It builds, of course.
I haven't run any other tests (now know how).

**Comment by Dr15Jones** [comment]
The one add on test I looked at crashed with
```
#5  0x00007fc48ffff642 in edm::ErrorObj& edm::ErrorObj::opltlt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_0_X_2018-01-16-2300/lib/slc6_amd64_gcc630/pluginL1TriggerL1TGlobalPlugins.so
#6  0x00007fc48fff73ad in L1TGlobalSummary::endRun(edm::Run const&, edm::EventSetup const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_0_X_2018-01-16-2300/lib/slc6_amd64_gcc630/pluginL1TriggerL1TGlobalPlugins.so
#7  0x00007fc4a3ff48ab in edm::one::EDAnalyzerBase::doEndRun(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_0_X_2018-01-16-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
```

**Comment by fwyzard** [comment]
The error looks reasonably unrelated to this PR.
If it persists I'll have a look on top of pre4.

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@fwyzard @Dr15Jones 
Well, the most recent IB CMSSW_10_0_X_2018-01-17-2300 which does NOT contain this PR,
does show the same errors in the slc7_amd64_gcc630 addONTests: so something is still wrong with 100X somewhere!

**Comment by Martin-Grunewald** [comment]
It seems to be not very reproducible. 
Going through recent IBs and testing myself, CMSSW_10_0_X_2018-01-17-1100 shows the problem for me, while the standard addOn IB tests of that IB run just fine (slc6_amd64_gcc630).

**Comment by fwyzard** [comment]
I've just tried locally with the latest IB without any PRs, and I got
```
$ addOnTests.py 
Running in 4 thread(s)
...
 33 tests passed, 14 failed 
```
and at least 10 failed with
```
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
```

**Comment by Martin-Grunewald** [comment]
Well, there are two different crashes: the ones you observe - in these 10 tests:
```
OnLine_HLT_Fake2_DATA.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_Fake2_MC.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_GRun_DATA.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_GRun_MC.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_HIon_DATA.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_HIon_MC.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_PIon_DATA.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_PIon_MC.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_PRef_DATA.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
OnLine_HLT_PRef_MC.log:Module: L1TGlobalSummary:hltL1TGlobalSummary (crashed)
```
and then in the L1T legacy (Run-I) and L1T stage-1 tests, called Fake and Fake1 tests, again in both data and MC (ie, 4 failing tests) but they look different:

```
----- Begin Fatal Exception 18-Jan-2018 07:19:37 CET-----------------------
An exception of category 'DQMStore' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything af\
ter beginJob and before endJob)
Exception Message:
Monitor element path name 'Running on Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz w\
ith 4 streams on 4 threads' uses unacceptable characters
----- End Fatal Exception -------------------------------------------------
```

**Comment by fwyzard** [comment]
Ah... OK, I broke the last one with a different PR, I'll fix that first.

**Comment by fwyzard** [comment]
OK, the DQM issue should be fixed by #21886 .

**Comment by fwyzard** [comment]
And the `L1TGlobalSummary` should be fixed by #21888 .

**Comment by fwyzard** [comment]
@cmsbuild, please test with #21886 #21888

**Comment by Martin-Grunewald** [comment]
Thanks a lot, Andrea!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
