### PR TITLE
Added missing link to TauJetCorrectorExample

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Need to link with JetMETCorrections/JetCorrector to fix UBSAN build.

#### PR validation:

Compiles and links using the CMSSW_11_0_UBSAN_X_2019-06-21-2300 IB.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
