### PR TITLE
Convert CandPtrProjector from legacy producer to global

### PR DESCRIPTION
**Pull request by knoepfel**
Per request from Lindsey Gray.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@knoepfel Thanks! Could you also change the std::set that's used here to std::unordered_set?

**Comment by knoepfel** [comment]
@lgray Using an `std::unordered_set` requires defining a hash for `edm::Ptr<reco::Candidate>`.  I would not pursue that option until you're sure that switching from a legacy producer to a global one is insufficient.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17514	a8a020a
- technical update, as described
- jenkins tests pass and comparisons show no differences

**Comment by Dr15Jones** [comment]
@lgray

**Pull request merged**
