### PR TITLE
MTD clusters and rechits in Fireworks

### PR DESCRIPTION
**Pull request by casarsa**
This PR introduces the following changes to the Fireworks package:
- addition of the MTD geometry (by @fabiocos) and topology;
- visualization of the BTL and ETL detectors in the 3D, Rho-Phi, and Rho-Z views;
- implementation of the ProxyBuilder plugins to display the MTD rechits and clusters. 

The new code has been tested with TTbar and SingleMuPt10 events simulated in the scenario 2026D96. Two examples:

mtd_display_1

mtd_display_2

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
@casarsa @alja @cms-sw/orp-l2 Do we prefer to have a separate package for MTD visualisation, or this can enter into the Tracks package? The question is related to the limited content of this package in terms of classes

**Comment by fabiocos** [comment]
if preferred, I can prepare the PR for cms-bot, but before I would like to hear the advice of release managers

**Comment by perrotta** [comment]
> if preferred, I can prepare the PR for cms-bot, but before I would like to hear the advice of release managers

@fabiocos I personally find that having a dedicated package, as implemented here, can be cleaner. However, I'd let @alja the last word about it (even if with the @cms-sw/visualization-l2 signature I think that this was already kind of approved...)

**Comment by fabiocos** [comment]
In case I have prepare the update https://github.com/cms-sw/cms-bot/pull/1934

**Comment by perrotta** [comment]
ping bot

**Pull request merged**
