### PR TITLE
Fix consumes for alignment validations

### PR DESCRIPTION
**Pull request by hroskes**
and a few other assorted fixes

backport of #13814

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #13816 1b25cfe8ba21738922216a8a660aea7f8ca5fed8

Fixing consumes for alignment validations. There should be no change in monitored quantities.

#13814 and #13815 are the 81X and 80X versions of this PR, and they have both already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2016-03-21-2300 show no significant differences, as expected.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
