### PR TITLE
Remove custom sequence for PreMixing Reco

### PR DESCRIPTION
**Pull request by mdhildreth**
Take out mods for bypassing CSC Raw2Digi in Reco step.  They aren't needed anymore.

### CODE REVIEW

**Comment by mdhildreth** [comment]
+1

**Comment by franzoni** [comment]
hello @mdhildreth , "They aren't needed anymore." 
does that imply that postLS1CustomsPreMixing can be taken out of the release, altogether (it's only used in the file you've modified, as far as I Can see..)?

**Comment by davidlange6** [comment]
@franzoni - it should still be needed in the step of making premixed events. (@mdhildreth can correct me) - I will merge this as in any case premixing is not working in the IBs.

**Comment by franzoni** [comment]
@davidlange6 hi, https://hypernews.cern.ch/HyperNews/CMS/get/swReleases/4174/2/1.html
cheers.
g.

**Pull request merged**
