### PR TITLE
Fix crashing bug  in reco when run with XML geometry

### PR DESCRIPTION
**Pull request by cvuosalo**
When reco for the Extended2021 scenario was run with geometry from XML instead of the DB, it was crashing due to missing GEM super chambers. The validation code was referencing GEM super chambers even if they didn't exist, thus causing the crash.

This bug fix adds protection in the validation code to make sure that null or empty objects are not dereferenced.

The issue of the missing GEM super chambers requires further investigation. This PR is just a first step that allows reco to run to completion without crashing. The next step is to examine the plots derived from reco to try to understand what is missing from the GEMs.

#### PR validation:

The 11634.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2021 reco step was tested using XML geometry and a second time with DB geometry, and it ran successfully.

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
type bugfix

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@ianna FYI. I found out that GEM super chambers are missing because reco was crashing when I ran it using XML geometry. This PR prevents the crash but does not address the missing super chambers.

**Comment by ianna** [comment]
@dildick - FYI

**Comment by dildick** [comment]
@jshlee Do you know why GEM superchambers are missing? Is it picking up the slice test configuration?

**Comment by jfernan2** [comment]
+1
Only the random L1T known changes

**Comment by silviodonato** [comment]
+1

**Pull request merged**
