### PR TITLE
bsunanda:Run2-hcx91 Change TriggerMode definition

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you approve this?

**Comment by bsunanda** [comment]
@ianna Could you approve this

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
