### PR TITLE
Convert all remaining RECO & MiniAOD modules that are executed to threaded FW (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11140

@Dr15Jones 74X has an older version of tbb so I had to use insert rather than emplace. It seems like the return value is exactly the same as for emplace, so the code change is trivial.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I think this PR should be merged only after all currently pending re-miniAOD PRs are merged.
Please check if this PR merges on top of #10649 
Thanks.

**Comment by lgray** [comment]
@slava77 indeed for now this does not merge with #10649. Looks like PATCandidateProducer is getting updated to the version in 75/76. I'll leave the PR here as a placeholder, we can return to it once the dust is settled.

**Comment by lgray** [comment]
@slaba77 looking at the changes that come, it's not 75/76 changes but some other new addition. Anyway it is a straightforward adaptation.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

previous errors were DAS errors...

**Comment by lgray** [comment]
@cmsbuild please test

DAS.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
since #10598 is already signed. I will rebase this PR ontop of it to fix the conflicts.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
@gpetruc - lets save this PR for after #10649 is done rather than including it thee (and hopefully just for 75x in the end)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@monttj @mulhearn please resign this PR. Thanks!

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
@mulhearn please sign, thanks.

**Comment by cvuosalo** [comment]
+1

For #10673 e5f214cedb789d0418bf47ac1ce95c14d009a4aa

Convert remaining legacy modules in RECO to support multi-threading. There should be no change in monitored quantities. #11140 is the 76X version of this PR, and it has already been merged. #10671 is the 75X version, and it has already been approved by Reco.

Jenkins tests against baseline CMSSW_7_4_X_2015-09-08-2300 show no significant differences, as expected. See #10806 for information about the performance of this PR.

**Comment by lgray** [comment]
@mulhearn please sign. thanks!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
