### PR TITLE
NanoAOD updates to use  MiniAODV2 information

### PR DESCRIPTION
**Pull request by arizzi**
This uses the new content of MiniAODV2 for NanaAOD processing and fixes few things

Needed for NanoAOD production chained with MiniAOD V2

needs: https://github.com/cms-sw/cmsdist/pull/3873
@gpetruc

### CODE REVIEW

**Comment by arizzi** [comment]
please test with cms-sw/cmsdist#3873

**Comment by arizzi** [comment]
contains also #22679 that isn't merged (while it is in the master)

**Comment by arizzi** [comment]
are the tests stuck?

**Comment by smuzaffar** [comment]
@arizzi , Tests failed as you are trying to test 94X cmssw PR with 10.1.X cmsdist. This is not supported.
For 94X , cmsdist PR is https://github.com/cms-sw/cmsdist/pull/3875

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3875

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@arizzi @gpetruc after the backport of 9_4_5_cand1 into 9_4_X I do not see the reason not to move also this code into the main 9_4_X branch, for the time being it is ok to test it here in parallel to the master

**Pull request merged**
