### PR TITLE
ECAL energy corrections, update for 80X.

### PR DESCRIPTION
**Pull request by emanueledimarco**
Same as PR #15276 for 81X.
Needed for ICHEP dataset.

@fcouderc @shervin86 @paramatti please also follow.

### CODE REVIEW

**Comment by emanueledimarco** [comment]
any news on the merge of this pull-request?

**Comment by davidlange6** [comment]
Hi @emanueledimarco - its waiting on the 81x version which needs feedback from you.

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by emanueledimarco** [comment]
Since #15276 has been merged, can we merge also this? Thanks. 
@fcouderc also interested

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
