### PR TITLE
Phase2-hgx212 Rearrange Geometry/HGCalCommonData in view of DD4Hep transition

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Move the HGCal algorithms for dd4hep in Geometry/HGCalCommonData and rearrange the test code in view of the transitions of other HGCal DD-algorithms

#### PR validation:

Tested using the test codes in Geometry/HGCalCommonData/test

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Review by ianna — CHANGES_REQUESTED** [review]
@bsunanda - please, move all test python configurations to a  test/python directory: 
```
Geometry/HGCalCommonData/test/python/testHGCal*_cfg.py
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
