### PR TITLE
fix CAHitNtupletGeneratorOnGPU in case of no hits

### PR DESCRIPTION
**Pull request by mmusich**
solves https://github.com/cms-sw/cmssw/issues/34659.

#### PR description:

Implementation follows @makortel comment https://github.com/cms-sw/cmssw/issues/34659#issuecomment-888602939.

#### PR validation:

run successfully:
```bash
cmsDriver.py step3 --conditions auto:run3_hlt -s RAW2DIGI:RawToDigi_pixelOnly,RECO:reconstruction_pixelTrackingOnly,DQM:@pixelTrackingOnlyDQM --process reRECO --data --era Run3 --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --procModifiers pixelNtupletFit,gpu --scenario pp --datatier RECO,MINIAOD,DQMIO --filein file:/eos/cms/store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/FOG/CRUZET_2021_data/run_343762.root --no_exec

cmsRun step3_RAW2DIGI_RECO_DQM.py 
```
This needs further testing in a real HLT environment.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@mmusich 
is this not affecting 12_0_X/master at all?
Please elaborate why not (sorry, I did not fully follow the messages in  #34659)

**Comment by mmusich** [comment]
@slava77 
>  is this not affecting 12_0_X/master at all?

no, the same test (done by @tsusa) as in the PR description https://github.com/cms-sw/cmssw/pull/34684#issue-699330446 succeeds in master.

> Please elaborate why not (sorry, I did not fully follow the messages in #34659)
 
My understanding from Matti's comment is that the problematic piece of code was changed in 12_0_X in #33371 (see https://github.com/cms-sw/cmssw/issues/34659#issuecomment-888633702).

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34684	fd06060
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

I suppose there is some interest to have a patch release with this fix soon.

**Comment by mmusich** [comment]
@gennai might want to comment here if this solves the issues on hilton too.

**Comment by makortel** [comment]
> My understanding from Matti's comment is that the problematic piece of code was changed in 12_0_X in #33371 (see [#34659 (comment)](https://github.com/cms-sw/cmssw/issues/34659#issuecomment-888633702)).

Right, I did not investigate any deeper what specifically in `kernel_sharedHitCleaner` causes problems for zero hits, or how #33371 would address that.

**Comment by perrotta** [comment]
+1

**Pull request merged**
