### PR TITLE
HipPy update to python3

### PR DESCRIPTION
**Pull request by lk11235**
#### PR description:

- fixing a couple lines to run with python3
- adding a submission script which will nohup and log PID for alignment jobs

#### PR validation:

- tested these modifications in a simple case on AFS
- `/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/lkang/CMSSW_12_4_9/src/Alignment/HIPAlignmentAlgorithm`
- `/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/HipPy/lkang/TESTING`

### CODE REVIEW

**Comment by tvami** [comment]
hey @lk11235 thanks for this! Can you please squash the commits into one? Also it would be nice to have a unit test that runs HipPy in CMSSW directly (on a few events) besides adding the submission script alone. That will ensure that the code works all the time with all CMSSW releases.

**Comment by lk11235** [comment]
Will do! Thanks Tamas. 

I can share a test of compiling and running HipPy with these modifications for an iteration or two. Would this suffice?

**Comment by tvami** [comment]
> Will do! Thanks Tamas.
> 
> I can share a test of compiling and running HipPy with these modifications for an iteration or two. Would this suffice?

Yeah I think a single iteration is already ensuring that the code *technically* works, which is really the idea behind the unit test. Thanks!

**Comment by lk11235** [comment]
slightly delayed because a couple additions to this PR are coming. testing all together before requesting merge.

**Comment by tvami** [comment]
@lk11235 this PR has been inactive for a while, what's the ETA for following up on the review comments?

**Comment by lk11235** [comment]
Thank you for this ping. I was going to message you. We will wrap this up this week

**Comment by tvami** [comment]
hi @lk11235 just a kind ping :)

**Comment by lk11235** [comment]
We have a new test/check running with minor changes added to this PR. Updates will be reflected here soon.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@lk11235 could you please post here a recipe for running the test and verify that it can succeed before approving this PR?

**Comment by mmusich** [comment]
related to https://github.com/cms-sw/cmssw/pull/40921#issuecomment-1757264444

> Also it would be nice to have a unit test that runs HipPy in CMSSW directly (on a few events) besides adding the submission script alone. That will ensure that the code works all the time with all CMSSW releases.

was this actually addressed? Seems not from the changeset proposed.

**Comment by lk11235** [comment]
> related to [#40921 (comment)](https://github.com/cms-sw/cmssw/pull/40921#issuecomment-1757264444)
> 
> > Also it would be nice to have a unit test that runs HipPy in CMSSW directly (on a few events) besides adding the submission script alone. That will ensure that the code works all the time with all CMSSW releases.
> 
> was this actually addressed? Seems not from the changeset proposed.

A unit test was done without the submission script at one point, but before additional edits were made. I'm running the tests again now both with and without our submission script to validate the current state of this PR without adding any more edits.

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by lk11235** [comment]
Thank you. We are currently debugging some behavior on our end when running alignment. We will share a complete test once we have good output.

**Comment by lk11235** [comment]
Sorry for the delay in updating this PR thread. We have a few alignments that were generated using this PR. 
```
/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/HipPy/lkang/mp3645/Jobs/hp3270​
/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/HipPy/lkang/mp3645/Jobs/hp3269​
/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/HipPy/lkang/mp3645/Jobs/hp3266​
```
As per the tracker alignment conveners' suggestion, we are requesting that this PR be merged and closed. Any additional improvements or changes will come in future PRs.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+alca
- The updates implemented for python 3 make sense
- The unit test that was requested (which could be really useful indeed) was not added. However, according to https://github.com/cms-sw/cmssw/pull/40921#issuecomment-1862801346:
   - There is a request from the Tracker alignment group to have this merged now
   - It apparently got tested while generating a few alignments

**Comment by rappoccio** [comment]
+1

**Pull request merged**
