### PR TITLE
Moved ErrorMatrixTag to DataFormats/Common

### PR DESCRIPTION
**Pull request by Teemperor**
This is supposed to fix the cycle: DataFormats/GeometryCommonDetAlgo → DataFormats/GeometrySurface → DataFormats/GeometryCommonDetAlgo

Open for alternatives to doing this.

More information here: https://teemperor.de/pub/cms/cycle1.cycle.html

### CODE REVIEW

**Comment by Teemperor** [comment]
Also see https://github.com/cms-sw/cmssw/issues/15248 for more information

**Comment by Dr15Jones** [comment]
-1
This should not become core responsibility

**Comment by davidlange6** [comment]
please test

**Comment by VinInn** [comment]
DataFormats/GeometryCommonDetAlgo/interface/WeightMatrixTag.h
must be moved as well.
actually none of the two belongs to DataFormats/Common: please find a different solution....

**Comment by davidlange6** [comment]
maybe @ianna should have a look at this issue?

**Comment by VinInn** [comment]
the point is that  the templated LocalErrorBaseExtended.h is just a joke
one should rename it LocalErrorExtended and remove all the fancy (unused) templated crap

**Pull request closed without merging**
