### PR TITLE
Introduce GREAt algorithm.

### PR DESCRIPTION
**Pull request by ghellwig**
This algorithm consistently introduces the notion of randomness into the determination of tracker alignment conditions.

It simultaneously determines the parameters of the TrackerAlignmentRcd, TrackerAlignmentErrorExtendedRcd, TrackerSurfaceDeformationRcd, SiPixelLorentzAngleRcd, SiStripLorentzAngleRcd, and SiStripBackPlaneCorrectionRcd.

The algorithm is GREAt because it does not even require data. Hence it is the natural choice when predicting the alignment prior to data taking.

For the same reason it allows to disentangle the CMS and LHC schedule from the alignment expert's vacation plans because the alignment can be derived at any point in time.

In addition to the above-mentioned convenience features it also shows unprecedented performance improvements:
 - It's extremely fast! All the above-mentioned records are derived almost instantly, thereby dramatically reducing the time budget of normally 1-2 weeks.  
 - Due to its inherent GREAt-ness, validation is not required anymore. Thus the total time between the request of a new alignment and the delivery can be reduced to a few seconds.

It also solves the typical problem of conventional algorithms that have to deal with complaints about delays caused by the missing tracker alignment conditions. The first complaints about delay typically arise several days, sometimes weeks, before all inputs of the conventional algorithms are available. The extreme reduction of the required inputs for the GREAtAlgorithm fully avoids this problem in a straight forward fashion.

NOTE: The implementation of this alignment algorithm is unique as it requires no data. Thus the overhead of the AligmentProducer framework is elegantly circumvented.

attn.; @hroskes, @connorpa, @mschrode

### CODE REVIEW

**Comment by ghellwig** [comment]
assign alca

**Comment by arunhep** [comment]
@ghellwig what is the aim for this? to derive the misalignment scenario for MC ?
And is there any validation available of the alignment coming out of this algorithm with the already existing techniques.

**Comment by VinInn** [comment]
+0401

**Comment by felicepantaleo** [comment]
this is a truly revolutionary way of solving the alignment problem and will surely become a milestone in the education of future generations of scientists.

**Comment by boudoul** [comment]
GREAt will make history ! really excellent!
@ghellwig : Danke and Tchuss !!!

**Comment by ghellwig** [comment]
Dear all,
thanks for the nice feedback!
But I guess the code is not yet ready for production ;)

Best,
Gregor

**Pull request closed without merging**
