### PR TITLE
Subject main tau ID payloads to global tag control

### PR DESCRIPTION
**Pull request by swozniewski**
#### PR description:

Payload labels are changed such that payloads for current anti-electron MVA ID and the three MVA tau IDs DBoldDM, DBnewDM, DBoldDMdR03 are loaded via global tag.
This requires global tag configurations as in test global tag:

> 110X_upgrade2018_realistic_Candidate_2019_09_22_09_29_04

Deprecated PW MVA tau IDs are removed from the reco and pat workflows.
In RECO (HPSPFTaus_cff.py), no payloads are loaded directly from DB anymore.
In NanoAOD, the upper IDs are loaded via GT as well, but further IDs which shall still be producible for experimental and comparison purposes, or if a very new payload is not yet available via GT, can still be loaded directly from DB as before.

#### PR validation:

RECO+PAT step were run with test GT and outputs compared, same for NanoAOD
Matrix tests fail due to wrong GT

#### if this PR is a backport please specify the original PR:

no backport planned

### CODE REVIEW

**Comment by perrotta** [comment]
assign alca

**Comment by perrotta** [comment]
To test this appropriately we need to have the corresponding GT. What are the plans for having it available in the release?
If the one you suggest is just adding payloads, and not touching the existing ones, then it could probably be just replaced in autocond and the tests run with it.
Otherwise, a PR (even "dummy") that replaces such a GT should be prepared in order to run it together with this one for the tests.
Please decide together with alca which option is most suitable for testing this PR.

**Comment by tocheng** [comment]
> To test this appropriately we need to have the corresponding GT. What are the plans for having it available in the release?
> If the one you suggest is just adding payloads, and not touching the existing ones, then it could probably be just replaced in autocond and the tests run with it.
> Otherwise, a PR (even "dummy") that replaces such a GT should be prepared in order to run it together with this one for the tests.
> Please decide together with alca which option is most suitable for testing this PR.

I would suggest customizing GT by adding the tags (conditions) in the config files.
Once the tags are tested and this PR is merged, we could add these tags to the GTs in autoCond.

**Comment by swozniewski** [comment]
So we need a PR from the test GT if I understand correctly. @aknayak could you please take care of this?

**Comment by peruzzim** [comment]
I can see some issues potentially coming from this, they can be handled but it will have to be orchestrated well.
In NANOAOD we use e.g. the GT to read the JEC, and we want to support running on several old datasets for which we need dedicated JEC sets (e.g. one for 2016, one for 2017 etc.).
Therefore one should envisage having separate 110X_... tags, all containing the same tau payloads but different JEC, as we had in the past for 102X central productions.
Before this, we could for the moment (I think) continue using the 102X GT also in 11_0_X, because we basically use it only for JME corrections.
After merging this, if we call the producer without the payload being in the tag it will crash, right?

**Comment by swozniewski** [comment]
Right, with current official GTs CMSSW will complain that the used tags are not available.
As far as I know it is intended to add the tau payloads to several GTs as you suggest, in particular for this reason. @aknayak and @christopheralanwest had an email thread about this and figured out which GT queues to update if I remember correctly.

**Comment by peruzzim** [comment]
please include XPOG in that thread, there are several combinations of MINIAOD production version + NANOAOD code to support, and we should be sure we don't break any workflow we want to support

**Comment by perrotta** [comment]
@swozniewski is there any news about a possible GT to test this?

**Comment by tocheng** [comment]
@perrotta AlCaDB is working on it. Expect to have a PR tomorrow, then this PR can be tested.

**Comment by tocheng** [comment]
@swozniewski @perrotta PR #28134 is submitted and test is started. If no issue, this PR can be test with PR #28134

**Comment by perrotta** [comment]
please test with #28134

**Comment by swozniewski** [comment]
I currently see two issues: The tag of the old MVA ID seems broken due to incomplete string modification which I'll provide a fix shortly.
Then it's missing the label RecoTauTag_antiElectronMVA_NoEleMatch_woGwoGSF_BL
(see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1874cc/2850/runTheMatrix-results/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step3_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO.log)
which was at least included in the test GT as far as I can see from the confirmation email that Arun forwarded. @aknayak could you please double check whether this is also in the GT PR?

**Comment by aknayak** [comment]
I see that the Tag with Label "RecoTauTag_antiElectronMVA_NoEleMatch_woGwoGSF_BL" is included in GT PR, e.g.,
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v8/110X_dataRun2_v7

**Comment by swozniewski** [comment]
Thank you! Does anybody have an idea why this payload is not available in the test, however?

**Comment by christopheralanwest** [comment]
Looking at the [configuration](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1874cc/2850/runTheMatrix-results/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step3_RAW2DIGI_L1Reco_RECO_ALCA_EI_PAT_VALIDATION_DQM.py) for the workflow that crashes because the tag with label "RecoTauTag_antiElectronMVA_NoEleMatch_woGwoGSF_BL" is missing relevant GT for 2018 HI MC is auto:phase1_2018_realistic_hi. This GT was not updated in PR #28134: https://github.com/cms-sw/cmssw/pull/28134/files#diff-8cbfe6480e6018966eac475523946acdR61. 

The relevant tags were not added to the HI queues, I suppose on the assumption that pp tau ID is not used or not sensible in HI reco. Should the sequences that use these tags be run in HI reco or should they be disabled?

I will trigger the tests anyway to check that the issue with non-HI workflows is resolved with the latest fix.

**Comment by christopheralanwest** [comment]
please abort

The tests should have been triggered with #28134

**Comment by christopheralanwest** [comment]
please test with #28134

**Comment by aknayak** [comment]
The Tags were not added to HI GT queues as we think it is not sensible for HI reco, request @mbluj to clarify more. To my understanding HI reco was not supposed to run in HI reco.

**Comment by christopheralanwest** [comment]
Looking more closely at the [configuration for the failing HI test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1874cc/2877/runTheMatrix-results/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step3_RAW2DIGI_L1Reco_RECO_ALCA_EI_PAT_VALIDATION_DQM.py), the `auto:phase1_2018_realistic_hi` GT is being used with the `Run2_2018_pp_on_AA` era.

I will let @slava77 and @perrotta comment on how to proceed. Is pp-like reconstruction only used on 2018 HI data or for HI data from other years (for example, the 2017 pp reference run) as well?

From the AlCa perspective, it would be logically most straightforward to add the labeled tau payloads to any necessary HI GTs as well.

**Comment by perrotta** [comment]
> Looking more closely at the [configuration for the failing HI test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1874cc/2877/runTheMatrix-results/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECO+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step3_RAW2DIGI_L1Reco_RECO_ALCA_EI_PAT_VALIDATION_DQM.py), the `auto:phase1_2018_realistic_hi` GT is being used with the `Run2_2018_pp_on_AA` era.
> 
> I will let @slava77 and @perrotta comment on how to proceed. Is pp-like reconstruction only used on 2018 HI data or for HI data from other years (for example, the 2017 pp reference run) as well?
> 
> From the AlCa perspective, it would be logically most straightforward to add the labeled tau payloads to any necessary HI GTs as well.

"Run2_2018_pp_on_AA" era was used for 2018 HI data taking
For the 2017 reference run, "Run2_2017_ppRef" was used instead.
Lead-proton data in 2013 used a pp scenario with a "Run1_pA" era
Previous HI data taking and simulation periods used the "HeavyIons" scenario.

**Comment by swozniewski** [comment]
@christopheralanwest @perrotta So we need it for 2017 HI as well? For run1 these payloads would not make much sense (not telling for sure that this is not tried in some test or other sequence)

**Comment by aknayak** [comment]
@christopheralanwest @perrotta  Submitted tags to all 110X HI queues. New GT can be created for HI queues for test.

**Comment by christopheralanwest** [comment]
Are the reco differences expected? I thought that the this PR was intended to only rename the labels for the tags and add the labeled tags to the GT. In particular, there are some histograms in which histograms become empty after this update, for example [in one of the 2011A workflows](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-10-16-1200+ca9ac3/33841/validateJR/all_OldVSNew_RunMinBias2011Awf1000p0/all_OldVSNew_RunMinBias2011Awf1000p0c_recoPFTauDiscriminator_hpsPFTauDiscriminationByIsolationMVArun2v1PWdR03oldDMwLTraw__RECO_obj_data_.png)

**Comment by swozniewski** [comment]
Some deprecated MVA IDs were removed as mentioned in the PR description. Otherwise we would have twice as many payloads to add to GT. This concerns all IDs with 'PW' in the name as in the case that you found. Therefore this looks ok to me.

**Comment by christopheralanwest** [comment]
+1

@swozniewski Indeed, all of the differences in RECO-level comparisons involve IDs with 'PW' in the name. Thanks for the explanation.

**Comment by perrotta** [comment]
+1
- Tau Ids are taken from the GT, and a few obsolete ones are removed as written in the PR description
- Needed tau pog id payloads are added to the GTs in autoCond.py with the already merged PR #28134
- Jenkins tests only show as difference the missing removed deprecated IDs, as expected

**Comment by santocch** [comment]
+1

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

I would like to re-test NanoAOD-specific workflows, as in the meanwhile the products of previous tests have disappeared

**Comment by fabiocos** [comment]
@peruzzim so what is finally the conclusion?

**Comment by peruzzim** [comment]
+xpog

**Comment by fabiocos** [comment]
+1

**Pull request merged**
