### PR TITLE
Lock more methods of JobReport

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Production jobs were seeing scrambled job reports caused by pileup file entries.

#### PR validation:

Code compiles and framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@Dr15Jones  We also need to backport this to 12_4_X

**Pull request merged**
