### PR TITLE
Fix compilation in Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes compile failure in
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_ppc64le_gcc9/CMSSW_12_0_DBG_X_2021-05-11-1700/Validation/HGCalValidation

#### PR validation:

Builds and test run

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- release/arch = CMSSW_12_0_DBG_X/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
test parameters:
- release/arch = CMSSW_12_0_DBG_X/slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for slc7_mad64_gcc900

**Comment by mrodozov** [comment]
please test for slc7_amd64_gcc900

**Comment by mrodozov** [comment]
please test

**Comment by jfernan2** [comment]
please test
To get the DQM BinByBin results

**Comment by mrodozov** [comment]
@jfernan2 how about now is it ok ?

**Comment by jfernan2** [comment]
+1
From DQM side it is OK, I don't understand why there are some errors on the DBG/slc7_amd64_gcc900/ and DBG/slc7_ppc64le_gcc9/

**Comment by qliphy** [comment]
+1

**Pull request merged**
