### PR TITLE
Validation plots for APE and bug fixes

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:
Changes to the APE tool:
- Bug fixes: Remove lines that were previously added to prevent memory leaks, but which created errors. Also tweak some lines in test/plottingTools.
- Added a new plotting tool to allow for creation of plots with residual distributions plus some other validation plots.
- Added an option to autoSubmitter, so that APE can be more easily measured on cosmics data sets.

#### PR validation:

Ran some basic tests of the code on the most recent APE campaign to confirm that the changes work as intended.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, ping?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
This is due to github  service issue. Thing are getting back to normal now. I would suggest to restart the test

**Comment by qliphy** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tlampen** [comment]
+alca

- update to plotting tools, autoSubmitter for APE measurement, some bug fixes
- no differences found in comparisons

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@mteroerd We may also need a backport to 12_0_X?

**Pull request merged**
