### PR TITLE
sync OMTF code (as in tag omtfdev_mk20) with CMSSW_2_1_0.

### PR DESCRIPTION
**Pull request by konec**
Changes includes:
 - fix for missing CSC offset in raw to digi
 - fixed mem leaks
 - allow for emulator reconstruction in bx other than 0.
 - new omtf algorithm (sc-called v5, compatible with the one prepared for P5 running);
   the new algo is planned to be enabled by o2o with omtf algo key 'omtf_algo_base/v4';
   until then old algorithm is enabled.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
The code changes in this PR should have already been merged in the master with PR #24242

**Comment by thomreis** [comment]
+1
Changes to DQM histograms are expected.

**Comment by fabiocos** [comment]
@konec @thomreis could you please explicitly clarify of what this PR is the backport?

**Comment by thomreis** [comment]
Hi @fabiocos 
this PR is a fix for the online DQM in the first place and does not necessarily get merged since the changes should be covered by other PRs.

Parts of this PR's changes have been merged with #24242 and for the remaining changes @rekovic will make a new master PR and top up the open 10_2_x backport PR #24237 . That one needs externals and is therefore not suitable for the online DQM.

**Comment by fabiocos** [comment]
@thomreis @rekovic could we please clarify the need for this PR? And its physics backward compatibility as far as MC is concerned? I see that algorithms are updated, how does this affect MC?

**Comment by fabiocos** [comment]
@thomreis @rekovic sorry, but do we have a master version of this PR? It does not look a backport, am I correct?

**Comment by thomreis** [comment]
Hi @fabiocos 
there is no master PR for this one. The situation of my earlier comment has not changed to my knowledge. @rekovic can confirm.
This PR was for the online DQM.

**Comment by fabiocos** [comment]
@thomreis so could we please clarify the need for this PR? If it is not needed any more can we just close it? Otherwise we should go through a regular integration path...

**Comment by thomreis** [comment]
I suppose it can be closed. The DQM can still use it when it's closed.

**Comment by fabiocos** [comment]
@thomreis no sorry, DQM should in principle use an official release, the fact that there are temporary additions before a PR is validated and integrated does not mean there should be a parallel independent world. If this PR is needed by online DQM, it should be forward ported to 10_3_X, integrated there, it should be clarified whether it is physics backward compatible with the simulation in 10_2_X (especially as far as MC is concerned) and then possibly integrated in 10_2_X. This PR floating in github and which is unclear who is using where is just causing confusion... 

I interpreted your statement as if others PRs supersedes this one. If this is not the case, let's see how to manage it properly

**Comment by rekovic** [comment]
back-port  #24539

**Comment by rekovic** [comment]
backport of #24539

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@konec @rekovic the last commit should also go in the master PR.

**Comment by thomreis** [comment]
+1
DQM histogram changes are expected.

**Comment by rekovic** [comment]
@thomreis @konec 
master branch PR (#24539)  updated accordingly.

**Comment by thomreis** [comment]
Hi @konec 
since 10_2 is not used anymore this PR can probably be closed.

**Comment by fabiocos** [comment]
@konec @rekovic any explicit objection to closing this PR now that 10_2_X use for data taking has come to and end?

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
@rekovic @thomreis ping

**Comment by rekovic** [comment]
this is merged in 10_3_X.  can be closed as 10_2 will not be used in data taking.

**Pull request closed without merging**
