### PR TITLE
Fix HGCal_disableNoise customization function

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

The logic with which the parameters are parsed requires the presence of
many parameters that were not present in the customization function.

#### PR validation:

Tested on workflow 23234, with and without the customization function. The code works and the Noise is turned off with the customization active.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
