### PR TITLE
Migrate Fireworks dictionary generation to ROOT6

### PR DESCRIPTION
**Pull request by alja**

### CODE REVIEW

**Comment by alja** [comment]
+1

Don't know where are merge conflicts.

**Comment by alja** [comment]
git rebase to CMSSW_7_4_ROOT6_X  throws error in non-Fireworks code. Should I create a new PR for this ?

**Comment by wmtan** [comment]
CMSSW_7_4_ROOT6_X is dead.  The current 7_4_X branches are:
CMSSW_7_4_X (ROOT6)
CMSSW_7_4_ROOT5_X (ROOT5).
So, if these changes are intended for ROOT6, they should go into 7_4_X, unless, of course, they are already there.
PR's for CMSSW_7_4_ROOT6_X should all be closed.

**Comment by alja** [comment]
Thanks William, I will try  7_4_X and close this PR.

**Pull request closed without merging**
