### PR TITLE
Improved performance of c-hadron origin identification (7_6_X)

### PR DESCRIPTION
**Pull request by bartosik-hep**
C-hadrons performance as for b hadrons.
Example configuration extended by test of c harons.
Simpler configuration of the JetFlavour tool.

### CODE REVIEW

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
@bartosik-desy 
Do we have this PR for 74X and 75X?

**Comment by bartosik-desy** [comment]
@monttj Yes for 74X, but not for 75X. I can make a pull request for 75X if needed.

**Comment by monttj** [comment]
@bartosik-desy 
I guess we would like to have this feature in 75X as well?
By the way, I was not able find the same PR for 74X.

**Comment by bartosik-desy** [comment]
@monttj OK, I will do so. The one for 74X is here: https://github.com/cms-sw/cmssw/pull/10313

**Comment by monttj** [comment]
@bartosik-desy thank you!

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
