### PR TITLE
Define proper BS for 2018 premixing workflow if starting from scratch

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
To fix the bug of 2018 premixing wf if start from scratch. BS of 2017 was used. It seems normally, PdmV uses GS from StandardPU wf where BS is handled properly, so the issue has never been spotted.

#### PR validation:
`runTheMatrix.py --what premix -l 250200.18 --wm init`
provide proper configuration

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport will be for 10_6.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade
comparison changes limited to 2018 workflows, as expected

**Comment by smuzaffar** [comment]
code-checks
just testing a new feature of bot, so please ignore this.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
