### PR TITLE
Convert auto_ptr to unique_ptr in SimDataFormats/GeneratorProducts.

### PR DESCRIPTION
**Pull request by gartung**
Added ioread rules to allow reading old root file using pdf_=auto_ptr.

### CODE REVIEW

**Comment by gartung** [comment]
Resubmit of https://github.com/cms-sw/cmssw/pull/25192
Requires ROOT patch
https://github.com/root-project/root/pull/2960

**Comment by gartung** [comment]
Requires update to ROOT v6-14-00-patches
https://github.com/cms-sw/cmsdist/issues/4508

**Comment by gartung** [comment]
please abort 31697

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_4_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_4_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_4_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by gartung** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by Dr15Jones** [comment]
@cmsbuild please test with cms-sw/cmsdist/IB/CMSSW_10_5_X/rootnext

**Comment by smuzaffar** [comment]
@Dr15Jones , cms-bot does not know yet how to run tests against cmsdist branch. For now, we start normal tests and then i change the release directly in the jenkins job.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test with CMSSW_10_5_ROOT614_X

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test for CMSSW_10_6_ROOT614_X

**Comment by fabiocos** [comment]
@gartung as now we have moved to ROOT 6.14 is this PR ready?

**Comment by fabiocos** [comment]
please test

**Comment by gartung** [comment]
@fabiocos yes

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez might a test be done on some old GEN file with pdf info?

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez ping, might a test be done on some old GEN file with pdf info?

**Comment by efeyazgan** [comment]
@fabiocos what do you mean by old GEN file? 

@Saptaparna @gourangacole

**Comment by fabiocos** [comment]
@efeyazgan files produced with previous ROOT and PDF versions (already 10_2_X is old in this sense)

**Comment by fabiocos** [comment]
@efeyazgan @Saptaparna @gourangakole any news on this PR?

**Comment by Saptaparna** [comment]
@fabiocos I have generated a GEN-only root file in 10_2_X. Should I now use this GEN-only file to create step2 and step3 files in both 10_2_X and a higher release and compare the distributions associated with physics variables? Thanks!

**Comment by fabiocos** [comment]
@Saptaparna I think it is enough a GEN validation comparing results reading your sample in 10_2_X and 11_0_X

**Comment by fabiocos** [comment]
@Saptaparna @efeyazgan @qliphy do we finally have a conclusion? I think we need to close this story at some point

**Comment by Saptaparna** [comment]
@fabiocos I have launched the validation jobs in 10_2_6 and 11_0_0_pre2. However, there are some issues right now with logging into sl7 machines at LPC and the 11_0_0_pre2 are all in idle state. I will switch to CERN and launch those jobs.

**Comment by fabiocos** [comment]
@Saptaparna sorry, do we finally have a result? The test to be performed should be pretty minimal...

**Comment by Saptaparna** [comment]
@fabiocos I am very sorry. The last couple of weeks have been very busy (I had made some prior work commitments that needed to be met). I also had analysis deadlines that needed to be met. I am getting back to this now and will report on progress asap.

**Comment by Saptaparna** [comment]
@fabiocos Here are some comparisons between 10_2_6 and 11_0_0_pre2:

http://nuhep.northwestern.edu/~sapta/validation_10X_vs_11X/Generator_TTbar.html

for a TTbar sample. The statistics is an issue here, but that is because I had a lot of trouble producing the files in 11_X. There were lots of condor failures etc. Please let me know if you would like me to perform any other specific tests. Thanks.

**Comment by Saptaparna** [comment]
@fabiocos : I have updated the link. I noticed the other link I had could not be accessed later in the day.

**Comment by kpedro88** [comment]
@Saptaparna is the conclusion from your linked test that everything is fine?

**Comment by Saptaparna** [comment]
@kpedro88 Things look fine but I'd like to hear from @fabiocos on any further cross checks.

**Comment by gartung** [comment]
ping

**Comment by fabiocos** [comment]
For what I can see, analyzing the output of some LHE-based test wf (e.g. 514.0 or 521.0) with the DummyLHEAnalyzer, the result is the same with or without this PR. 
@qliphy @agrohsje do we have samples where the pdf section affected by this PR is touched, apart for the arrays of weights? Otherwise, unless you have further checks to propose, I would move forward with this PR.

**Comment by agrohsje** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
