### PR TITLE
Remove spurious file

### PR DESCRIPTION
**Pull request by rovere**
type bug-fix

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Old and unused configuration, presumably kept for possible backup, removed: the actual one is created by the fillDescription() method of HGCalLayerClusterProducer
 - Jenkins tests pass with no changes

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
