### PR TITLE
Adding 2 new ElecMU paths to be monitored in topHLTOfflineDQM package for 81X

### PR DESCRIPTION
**Pull request by soureek**
In response to JIRA ticket [1] , adding the following two ElecMu paths to be monitored in the topHLTOfflineDQM package. 
HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v*
HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v*

As explained in [1], these two paths will act as shadow to the following paths. HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v*
HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v*

[1] https://its.cern.ch/jira/browse/CMSHLT-961

### CODE REVIEW

**Comment by dmitrijus** [comment]
https://github.com/cms-sw/cmssw/pull/15312#discussion_r73157022

**Comment by Soureek89** [comment]
@dmitrijus: The tabs that you were mentioning in your comment have been removed. I have put all the path names (strings) one after another separated by comma in a single line instead of keeping them in multiple lines.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
