### PR TITLE
Speedup puppi [94X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #23270

intended to speed up analysis, no changes expected

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
no backports, please

**Comment by kpedro88** [comment]
why not?

**Comment by slava77** [comment]
@kpedro88 
please bring this in sync with #23270.
thank you.

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23271	ef92a19
- technical changes (not affecting the physics output) to speedup the execution
- the backport is correct (the same changes as in https://github.com/cms-sw/cmssw/pull/23270	d0482fd)
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

to be validated in parallelo to its master version in the test build for reminiAOD 2016

**Comment by fabiocos** [comment]
merge

**Pull request merged**
