### PR TITLE
Run3-hcx326 Make use of a version of EDAnalyzer to meet multithreaded application  in some HCal codes for Calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of a version of EDAnalyzer to meet multithreaded application  in some HCal codes for Calibration

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
Hi @bsunanda since you are modernizing to multithreaded applications, I'm wondering if you'd be interested in fixing the ThreadSafety bugs reported by the SA (things being non-`const`): 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-069ad3/20184/llvm-analysis/

**Comment by tvami** [comment]
@bsunanda please squash the code checks, thanks!

**Comment by bsunanda** [comment]
Screwed up during squashing. Close in favor of #35963

**Comment by tvami** [comment]
-alca
 * new PR is https://github.com/cms-sw/cmssw/pull/35963

**Pull request closed without merging**
