### PR TITLE
[HGC trigger] Review of the front-end code

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:

Complete review of the VFE code. The most notable changes are:
- Addition of LSB truncation before the floating point compression
- Propagation of recent reco calibration changes in our calibration (updated thickness response equalization, charge collection efficiency correction)
- Code cleaning and a bit of reorganization (hopefully improving the readability) 

#### PR validation:
- Code checks and code format
- Tested workflows: 23234, 27034, 28234
- Checked impact on energy reconstruction of single particles: negligible

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade
nice uses of structured bindings

**Comment by silviodonato** [comment]
Kind reminder @cms-sw/l1-l2

**Comment by silviodonato** [comment]
@cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
