### PR TITLE
O2O test setup modified to work across boost version changes [10_6_X]

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/35440
Addressing https://github.com/cms-sw/cmssw/issues/33989

### CODE REVIEW

**Comment by ggovi** [comment]
Please test

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondTools

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
Please test

**Comment by ggovi** [comment]
test parameters:

addpkg = CondTools

**Comment by tvami** [comment]
@ggovi although the tests have not finished yet, some of the unit tests are going to fail: "Some checks were not successful -- 1 errored, 1 pending, and 9 successful checks"

**Comment by perrotta** [comment]
backport of #35440
(and more...)

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
test parameters:

addpkg = CondTools

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
> backport of #35440 (and more...)

and #35472

**Comment by qliphy** [comment]
+1
now tested in master

**Comment by tvami** [comment]
Hi @ggovi if I understand https://github.com/cms-sw/cmssw/issues/28812 correctly than this should be backported to 10_2_X as well, thanks!

**Comment by tvami** [comment]
> Hi @ggovi if I understand #28812 correctly than this should be backported to 10_2_X as well, thanks!

Since this was just a backport, I did it myself: https://github.com/cms-sw/cmssw/pull/35517

**Pull request merged**
