### PR TITLE
[L1T] Fix mva ntuple variable

### PR DESCRIPTION
**Pull request by epalencia**
#### PR description:
The ntuple was filling the track mva variable with -99 as a default until the mva variable was ready to be used. We have now replaced the -99 to the actual mva variable. This is a very minor change.

- Local PR: [https://github.com/cms-l1t-offline/cmssw/pull/1046](https://github.com/cms-l1t-offline/cmssw/pull/1046)

#### PR validation:
This works correctly when running the ntuple. Basic formatting checks after the changes were made.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
Hi @epalencia 
The PR looks obvious. Just to confirm, `->trkMVA1()` always available, right?

**Comment by epalencia** [comment]
Hi @srimanob, I think so, @cgsavard could you please confirm?I

**Comment by cgsavard** [comment]
Yes, the variable trkMVA1() is always available. It is a part of the TTTrack class and has a default value even if the MVA is not run. @srimanob @epalencia

**Comment by srimanob** [comment]
+Upgrade

Thanks @cgsavard

**Comment by perrotta** [comment]
+1

**Pull request merged**
