### PR TITLE
Fixed static analyser warnings 5

### PR DESCRIPTION
**Pull request by civanch**
Fixed warnings of the static analyser, mostly trivial. Should not affect production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , please, merge this PR (it is really trivial), because a new one #15215 just appear which affect the same sub packages.

**Comment by civanch** [comment]
@davidlange6 , this PR seems to be a simple one.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
