### PR TITLE
DQM TriggerMatch Monitor to Watch the Trigger matching feature in pat::Muon

### PR DESCRIPTION
**Pull request by bmahakud**

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @bmahakud, I can't seem to find you in the [DQM Contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts), could you please shortly introduce yourself?

**Comment by folguera** [comment]
Dear @andrius-k, 
@bmahakud is our reco-muon contact, we need this PR to monitor a trigger-matching variable that we've introduced in the reco::muon object.  Please review this and let us know if it can be merged or not.  
There is no need to add Bibhu to the DQM contact list as he is normally not involved in this.

**Comment by bmahakud** [comment]
@andrius-k 
Please review the code. We have another PR which needs to be merged before this one . This PR uses a functionality that the other PR have (PR#24901). Once you review is done we will modify things if needed and wait for the other PR to be merged before it is tested.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@bmahakud could you please also run changed code through `clang-format` to make sure formatting and indentation is correct?

**Comment by bmahakud** [comment]
@andrius-k Thanks for the suggestion. Please let me take 1-2 days more. One of the error "if(patMuon.triggered(ptr))"  is because the other PR #24901 is not merged yet. This took bit more time than expected because as some root problem was going on in the IB. Mostly done(https://github.com/cms-sw/cmssw/pull/24901). I will just commit again in 1-2 days with updated code implementing your suggestions.

**Comment by andrius-k** [comment]
@bmahakud sure, no problem.

**Comment by bmahakud** [comment]
Another PR created #24988 for this . Several changes have been added wrt to this PR

**Pull request closed without merging**
