### PR TITLE
Phase2-hgx335M Update the scripts to help debug the V17 HGCal geometry with cassette shifts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts to help debug the V17 HGCal geometry with cassette shifts

#### PR validation:

Use the test scripts in Validation/HGCalValidationm/scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Update the test script. No change is seen in upgrade workflow as expected.
Note to @perrotta @rappoccio I don't know why the PR test spot the change in Run-3 DD4hep workflow. It should not relate to this PR. Do you have some clue of something is going on? Thx.

**Comment by emanueleusai** [comment]
+1

- differences in dqm plots not related to this PR

**Comment by perrotta** [comment]
please test
- I fully agree that the differences seen in the tests cannot be originated by this PR, but I also cannot understand where do they can come from. Let retest in a fresh IB and see whether those differences disappear, or they are confirmed, instead

**Comment by perrotta** [comment]
+1
- Comparisons look healthier now

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
