### PR TITLE
Fix HcalTestThreshold.cc: validId is used before declaration

### PR DESCRIPTION
**Pull request by iarspider**
Fixes the following [error](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc10/CMSSW_12_3_DBG_X_2022-01-20-2300/Calibration/HcalCalibAlgos):
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/49cdc564aa5d41cf44306c286f822fc4/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-20-2300/src/Calibration/HcalCalibAlgos/test/HcalTestThreshold.cc: In member function 'virtual void HcalTestThreshold::analyze(const edm::Event&, const edm::EventSetup&)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/49cdc564aa5d41cf44306c286f822fc4/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-20-2300/src/Calibration/HcalCalibAlgos/test/HcalTestThreshold.cc:99:57: error: 'validId' was not declared in this scope
    99 |   edm::LogVerbatim("HcalIsoTrack") << "\n\nList of " << validId.size() << " valid DetId's of EE";
      |                                                         ^~~~~~~
  gmake: *** [tmp/slc7_amd64_gcc10/src/Calibration/HcalCalibAlgos/test/CalibrationHcalCalibAlgosTest/HcalTestThreshold.cc.o] Error 1
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@iarspider can you please modify the PR title to be more descriptive of what the "update" is about? Thanks!

**Comment by iarspider** [comment]
@tvami ok now?

**Comment by tvami** [comment]
+alca
 * code change in line w PR description
 * failure in Jenkins test is known and not connected to this PR

**Comment by perrotta** [comment]
+1
- The fix applies to a DEBUG section of code in a `\test` area: as such it cannot affect the output of any workflow, and therefore it is suitable to be merged now for 12_3_0_pre4, even if that pre-release is only intended to integrate the updates/fixes to the Run3 geometry on top of pre3

**Comment by perrotta** [comment]
merge

**Pull request merged**
