### PR TITLE
Algo not found warning removed from L1TStag2uGTTiming module for the …

### PR DESCRIPTION
**Pull request by jaisatul**
#### PR description:

In response to comments on #45242
  - Algo not found warning messages removed from the L1TStage2uGTTiming for lookup in Unprescaled/Prescaled algo short list

#### PR validation:

Tested locally with 2023/2024 streamer files

### CODE REVIEW

**Comment by mmusich** [comment]
@jaisatul can you apply the code-formatting patch as requested by the bot: https://github.com/cms-sw/cmssw/pull/45290#issuecomment-2186432437.

**Comment by eyigitba** [comment]
@jaisatul @mmusich , should we actually keep these messages as LogDebug instead of removing them completely?

**Comment by mmusich** [comment]
> should we actually keep these messages as LogDebug instead of removing them completely?

that's not my call. `LogDebug` is akin to not having them as far as production is concerned.

**Comment by eyigitba** [comment]
Exactly. I was thinking this would remove the flood of messages and also keep the functionality in case we need to debug something later on. @jaisatul , then I suggest you move these to `LogDebug` instead of removing them

**Comment by jaisatul** [comment]
@tjavaid ,
Hi, do I need to make some specific tests?

**Comment by tjavaid** [comment]
please test

- triggering for fresh output

**Comment by mmusich** [comment]
I think that when https://github.com/cms-sw/cmssw/pull/45242 is merged, this PR has no reason to be merged.

**Comment by eyigitba** [comment]
I think we can close this PR since it's not necessary after the recently merged PRs

**Comment by tjavaid** [comment]
> I think we can close this PR since it's not necessary after the recently merged PRs

@jaisatul ping.

**Pull request closed without merging**
