### PR TITLE
Use unique_ptr constructor for PluginFactory plugin in HGCalLayerClusterProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a preparatory step to change PluginFactory to return `std::unique_ptr`.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26902	081d6b5
- technical 
- jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
