### PR TITLE
adding stage1 specific run keys for online dqm in 74x

### PR DESCRIPTION
**Pull request by danduggan**
Creating two new run keys needed for customizations within online DQM configurations during the l1stage1 tests. A few other minor fixes are also included.

### CODE REVIEW

**Comment by deguio** [comment]
ciao @danduggan,
do you need to add more commits to this one?
ciao,
F.

**Comment by danduggan** [comment]
hey @deguio, yep. thanks for the ping. i'll push those today, submit for
75+76 and approve.

**Comment by deguio** [comment]
yeah. thanks.

**Comment by deguio** [comment]
+1
this is already in use and can go it. the online only is affected.
@danduggan please remember to port it to 75 and 76
thanks,
F.

**Comment by slava77** [comment]
@smuzaffar @degano 
I see this repetitiveness still happens.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
