### PR TITLE
Run4-hgx258 Try to address the issue reported in #31059

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address the issue reported in #31059

#### PR validation:

Tested using the runTheMatrix.py workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Looks good. Hope it fixes the problem.

**Comment by kpedro88** [comment]
@bsunanda did you manage to test this in the UBSAN IB?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
I used the following steps:
cmsrel CMSSW_11_2_ASAN_X_2020-08-05-2300
cd CMSSW_11_2_ASAN_X_2020-08-05-2300/src
cmsenv
git cms-init
git cms-merge-topic bsunanda:Run4-hgx258
scram b 
and then ran
cmsDriver.py -l 29034.0
I no longer get any crash in step1. All 10 events were created:
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 on stream 0 at 08-Aug-2020 01:25:18.837 CEST
 PYTHIA Warning in SimpleSpaceShower::pT2nextQCD: weight above unity  
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 on stream 0 at 08-Aug-2020 01:27:03.027 CEST
Begin processing the 4th record. Run 1, Event 4, LumiSection 1 on stream 0 at 08-Aug-2020 01:29:25.095 CEST
Begin processing the 5th record. Run 1, Event 5, LumiSection 1 on stream 0 at 08-Aug-2020 01:31:08.125 CEST
Begin processing the 6th record. Run 1, Event 6, LumiSection 1 on stream 0 at 08-Aug-2020 01:32:54.144 CEST
Begin processing the 7th record. Run 1, Event 7, LumiSection 1 on stream 0 at 08-Aug-2020 01:34:18.721 CEST
Begin processing the 8th record. Run 1, Event 8, LumiSection 1 on stream 0 at 08-Aug-2020 01:36:36.405 CEST
Begin processing the 9th record. Run 1, Event 9, LumiSection 1 on stream 0 at 08-Aug-2020 01:37:09.021 CEST
Begin processing the 10th record. Run 1, Event 10, LumiSection 1 on stream 0 at 08-Aug-2020 01:38:54.285 CEST

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
