### PR TITLE
get rid of compiler warnings in GEMGeometry

### PR DESCRIPTION
**Pull request by dildick**

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
not clear what type of warnings is fixed - both codes before and after are OK

**Comment by dildick** [comment]
Fixing things such as 
<PRE>
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-17-2300/src/Geometry/GEMGeometry/interface/GEMGeometry.h:16:0,
                 from /afs/cern.ch/work/d/dildick/public/GEM/CSCTriggerThreadSafe/CMSSW_9_1_X_2017-04-17-2300/src/L1Trigger/CSCTriggerPrimitives/src/CSCMotherboardME21GEM.cc:4:
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-17-2300/src/Geometry/GEMGeometry/interface/GEMRing.h:18:7: warning: 'class GEMRing' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
 class GEMRing
<\PRE>

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
