### PR TITLE
Shorten the names of two ALCARECOStreams in order to fit into DBS database schema limitations

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It was pointed out in https://cms-talk.web.cern.ch/t/alcaprompt-datasets-not-loaded-in-dbs/11146/1 that, quoting:

> Since the last update of the alcareco matrix, two new producers were added to ExpressPhysics:
>    * `PromptCalibProdSiPixelLorentzAngle`
>    * `PromptCalibProdSiStripHitEfficiency`
>    while the resulting (harvested) ROOT files are regularly displayed in the DQM, the corresponding ALCAPROMPT datasets in DAS are missing.
>
> The names of the datasets expected are:
>
>    /StreamExpress/Run2022A-PromptCalibProdSiStripHitEfficiency-Express-v1/ALCAPROMPT
>    /StreamExpress/Run2022A-PromptCalibProdSiPixelLorentzAngle-Express-v1/ALCAPROMPT
>
> According to Tier0 experts the problem is related to the name of the dataset, which is too long to be accepted, and the WMAgent software at present is not signalling this but keeps trying the upload. While probably a better handling of this issue should be thought for future, we need to fix the cause of the problem by shortening the names.

This PR performs such shortening:
   * `ALCARECOPromptCalibProdSiPixelLorentzAngle` is renamed `ALCARECOPromptCalibProdSiPixelLA`
   * `ALCARECOStreamPromptCalibProdSiStripHitEfficiency` is renamed `ALCARECOStreamPromptCalibProdSiStripHitEff`

#### PR validation:

Run the following commands:
```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiPixelLA --conditions 123X_dataRun3_Express_v6 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 10000 --dasquery='file dataset=/StreamExpress/Run2022A-SiPixelCalSingleMuon-Express-v1/ALCARECO run=352572' --customise_commands='process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.TriggerResultsTag = cms.InputTag ( "TriggerResults","","HLT" ) ; process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.HLTPaths = ["*"]' --nThreads=4

cmsDriver.py stepHarvest -s ALCAHARVEST:SiPixelLA --conditions 123X_dataRun3_Express_v6  --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiPixelLA.root -n -1
```

and

```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Run2018D-SiStripCalMinBias-Express-v1/ALCARECO run=325172' --nThreads=4

msDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiStripHitEff.root -n -1 
```

Also exercised successfully the two `runTheMatrix` workflows running the PCL workflows:
   * `runTheMatrix.py -l 1001,1001.2` 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but needs to be backported to 12.4.X and 12.3.X

### CODE REVIEW

**Comment by mmusich** [comment]
@fabiocos FYI

**Comment by tvami** [comment]
> this is not a bug-fix, but just an adaptation to the inadequacies of the CMS offline tools.

Ok, I edited my comment, the bugfix label should be gone soon

**Comment by mmusich** [comment]
For the record, as per https://cms-talk.web.cern.ch/t/alcaprompt-datasets-not-loaded-in-dbs/11146/2 the `output_module_label` name should not be longer than 45 chars:

```console
$ echo ALCARECOStreamPromptCalibProdSiStripHitEfficiency | wc -c
50
$ echo ALCARECOStreamPromptCalibProdSiStripHitEff | wc -c
43
$ echo ALCARECOStreamPromptCalibProdSiPixelLorentzAngle | wc -c
49
$ echo ALCARECOStreamPromptCalibProdSiPixelLA | wc -c
39
```

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1001.2

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca
 * tests pass

**Comment by tvami** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 given the urgency, can you please sign this asap?

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

purely technical pr to manage dataset nane.

**Comment by tvami** [comment]
@cms-sw/orp-l2 this is essentially fully signed :)

**Comment by mmusich** [comment]
@malbouis 

>  sorry to jump in a bit late, but I was wondering if there wouldn't have to be an update also for autoPCL.

yes. forgot about that. Will update soon.

**Comment by mmusich** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Resign

**Comment by kskovpen** [comment]
+pdmv

**Comment by tvami** [comment]
@cms-sw/orp-l2 we are fully signed (again :D )

**Comment by perrotta** [comment]
+1

**Pull request merged**
