### PR TITLE
Fix Pedestal EB RMS threshold. Add chi2 cut on DQM timing.

### PR DESCRIPTION
**Pull request by mbandrews**
Fix Pedestal RMS threshold for EB to ( G1:1.0, G6:1.2, G12:2.0 ) ADC.

Add chi2 cut on rechits for DQM Timing.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by mbandrews** [comment]
Will this still be merged?

**Comment by deguio** [comment]
not sure this is needed in 74. I will ask for merging in 75

**Comment by deguio** [comment]
+1
anyway

**Pull request closed without merging**
