### PR TITLE
RecoLocalMuon/CSCRecHitD:replace auto_ptr removed in strict std=c++17 

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by perrotta** [comment]
@gartung : following your convention, the title of this PR should be "RecoLocalMuon/CSCRecHitD: replace bind1st removed from strict implementations of std=c++17 with equivalent lambda"

**Comment by fabiocos** [comment]
+1

**Pull request merged**
