### PR TITLE
New electron WP and other updates for HLT

### PR DESCRIPTION
**Pull request by perrotta**
This PR updates the HLT menus in CMSSW with the newly defined electron working points, the switch to HCAL method 3 in the 25ns menu, plus other fixes and adjournments.
It also defines the new frozen menus to be used in the rate measurements.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
