### PR TITLE
Run2-176 Backport PR # 23134 to update AlCaReco o/p collection

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
@arunhep, @lpernie 
Could you, please, approve it?

**Comment by arunhep** [comment]
+1
look for the discussion here : https://github.com/cms-sw/cmssw/pull/23134#issuecomment-387375165

**Comment by fabiocos** [comment]
+1

**Pull request merged**
