### PR TITLE
[Backport to 11_2_X] Change DBS url to cmsweb-prod in MatrixInjector

### PR DESCRIPTION
**Pull request by justinasr**
#### PR description:

Use cmsweb-prod.cern.ch for "DbsUrl" attribute in the dictionary that is submitted to ReqMgr2 by MatrixInjector.

Relevant ticket on gitlab: https://gitlab.cern.ch/cms-http-group/doc/-/issues/256 

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/33209
Backport because 11_2_X is still used in production.

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
