### PR TITLE
use `std::vector<DetId>` as data format of SiStrip `DetId`s with FED errors [`13_2_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #42662

#### PR description:

From the description of #42662:

>This PR changes the data format of the collection used for the DetIds of SiStrip modules with FED errors (this collection is used to mask said modules during the event reconstruction).
>
>#42475 showed that this information needs to be added to the RawPrime event content (see that PR for details).
>
>The current data format for this is `DetIdCollection`, and concerns were raised (see https://github.com/cms-sw/cmssw/pull/42495#issuecomment-1674956299 and replies) on the forward-compatibility of this data format in view of possibly adding it to the RAW data tier (which is expected to be backward- and forward-compatible across release cycles).
>
>Following the discussion in https://github.com/cms-sw/cmssw/pull/42495#issuecomment-1674956299, this PR tries to implement a solution replacing `DetIdCollection` (== `edm::EDCollection<DetId>`) with `DetIdVector` (== `std::vector<DetId>`) in the SiStrip unpacker and related clients/utilities, such that the data format added to RAW(Prime) would be a `std::vector<DetId>` rather than a `edm::EDCollection<DetId>`.
>
>Merely technical. No changes expected.
>
>Thanks to @mmusich for help with preparing this PR.

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42662

Data-format change suggested in view of 2023 HIon data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - workflows = 1001.2, 1001.3

**Comment by missirol** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by emanueleusai** [comment]
+1

**Comment by civanch** [comment]
+1

**Review by Gdakgdak22 — APPROVED** [review]

**Comment by makortel** [comment]
+core

**Review by Gdakgdak22 — APPROVED** [review]

**Comment by perrotta** [comment]
+alca

**Comment by perrotta** [comment]
+operations

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
