### PR TITLE
Remove dead assignments and simplify HLTmumutkFilter

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

As the title says
Dead assignments were reported by the static analyzer

#### PR validation:

It builds
No changes expected

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Hi @perrotta , thanks for the PR. Just for my education, where do I find the static-analyzer reports you mentioned?

**Comment by perrotta** [comment]
> Hi @perrotta , thanks for the PR. Just for my education, where do I find the static-analyzer reports you mentioned?

I hit it while reviewing one of the latest PRs that touched this package, I don't remember by heart which one now...
Anyhow, all SA reports for all packages can be inspected from the IB pages, e.g. https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_3_X

**Comment by missirol** [comment]
Thanks, found it:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4d72fb/22374/llvm-analysis/runStaticChecks.log
```sh
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-11-2300/src/HLTrigger/btau/plugins/HLTmumutkFilter.cc:186:9: warning: Value stored to 'track1Matched' is never read [deadcode.DeadStores]
        track1Matched = true;
        ^               ~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-11-2300/src/HLTrigger/btau/plugins/HLTmumutkFilter.cc:192:9: warning: Value stored to 'track2Matched' is never read [deadcode.DeadStores]
        track2Matched = true;
        ^               ~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-11-2300/src/HLTrigger/btau/plugins/HLTmumutkFilter.cc:198:9: warning: Value stored to 'track3Matched' is never read [deadcode.DeadStores]
        track3Matched = true;
        ^               ~~~~
3 warnings generated.
```

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
