### PR TITLE
Set hierarchy constraints as default in Millepede

### PR DESCRIPTION
**Pull request by mschrode**
Backport of #9713

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
hold
requires:
* approval of #9713 
* backport of `pede` external to >=rev137 in `cmsdist`
* full build of externals for this release cycle.

**Comment by mmusich** [comment]
-1 not for this release cycle anymore

**Comment by mmusich** [comment]
@diguida  would you please unhold that one?
as far as I can tell we should have by now MP rev 148 in place for 74X: https://github.com/cms-sw/cmsdist/pull/2108

**Comment by diguida** [comment]
unhold

**Comment by mmusich** [comment]
+1

**Comment by diguida** [comment]
@mmusich thanks for the heads-up.
Indeed, this PR was put on hold as the first Pede revision with the hierarchy constraint fix, namely `v140 --> V04-03-00` was included as external only for 76X (https://github.com/cms-sw/cmsdist/pull/1648); 75X PR (https://github.com/cms-sw/cmsdist/pull/1649) was closed at some point, while 74X was not considered at all. Now all 7XY cycles share the latest Pede.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
