### PR TITLE
[10.3.X] Customize Tracker AlCas for pp_on_AA_2018

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
as the processing scenario preferred for the 2018 PbPb run is `pp_on_AA_2018`, this means that the standard pp-flavored Tracker AlCaRecos will be run in production. 
With the current setup the pp configuration is going to run _tout-court_  and this is not optimal in the HI environment.
In this PR, era modifiers are used to change parameters for the `pp_on_AA_2018` and `pp_on_XeXe_2017` eras such that the pp-flavored ALCARECO producer is configured as if it was the corresponding HI one.
I also profited to change the `eventSetupPathKey` to point to the HI-flavored one as we don't want to pollute the regular pp keys with HI trigger paths.
To exercise this works I added AlCa steps to the wf 158, which (to my knowledge) is the baseline for testing the 2018 PbPb configuration.
Side note, due to to the current trigger bits in GT no events are selected from the ALCARECO producers, but I decided not to change them here, as there is another pending PR which changes the input GT to this wf (#24537)
@icali @mandrenguyen FYI
Probably there is more work to be done in this sense for the other TkAl ALCARECO producers, I adjusted only `TkAlMinBias` which is workhorse for previous HI alignments. @connorpa @hroskes.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by mmusich** [comment]
The last commit is a cherry-pick from @tocheng about doing a similar change for the `SiPixelCalZeroBias` producer. The `AlCaRecoTriggerBit` for `SiPixelCalZeroBias` still need to be split from the one for `SiStripCalZeroBias`, though this can be done in a follow-up PR (Needs changes in GT)

**Comment by davidlange6** [comment]
please test

**Comment by tocheng** [comment]
please test workflow 158

**Comment by tocheng** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
