### PR TITLE
Add HIZeroBias Trigger in Strip DQM

### PR DESCRIPTION
**Pull request by fioriNTU**

### CODE REVIEW

**Comment by fioriNTU** [comment]
@davidlange6 it would be great to have this merged in a coming patch release for HI, if possible

**Comment by fioriNTU** [comment]
@deguio @davidlange6 @slava77 sorry to insist, but this is a very basic fix, not touching any c++ code and it will cure the unreasonable high number of reconstructed tracks that show up in Offline DQM plots. Please let me know if it can be merged before HI collisions are over

**Comment by davidlange6** [comment]
@deguio (and most others) typically gets to things quickly but not always within 1 working day.

**Comment by slava77** [comment]
@cmsbuild please test
could help to get things moving

**Comment by deguio** [comment]
+1
in a period during which we receive only urgent request, the urgency mode is the new normality.
don't be surprised if this or some other urgent PR miss the release
cheers,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
