### PR TITLE
Fix Memory Leak in JetCorrectorParametersHelper

### PR DESCRIPTION
**Pull request by aperloff**
This PR fixes the issue discussed at https://github.com/cms-sw/cmssw/issues/18160. There are new conditions checks and unit tests added to the package and a memory leak was fixed. None of this should affect the underlying behavior of the code nor its speed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
As far as I can tell, this doesn't fix a memory leak, but instead avoids an out-of-memory-bounds read.

**Comment by aperloff** [comment]
@Dr15Jones, yes, you are right.

**Comment by aperloff** [comment]
Looks to me like all the checks passed. Only the DQM-TimerService has some small differences.

**Comment by aperloff** [comment]
@Dr15Jones Just checking in to see if we can merge this PR. Didn't want it to fall by the wayside.

**Comment by Dr15Jones** [comment]
@aperloff I'm afraid this change is not under my L2 area so I have no say as to it being merged. This requires signatures from analysis and db L2 areas.

**Comment by aperloff** [comment]
@Dr15Jones Who are the analysis and db L2 contacts that I need to ping?

**Comment by Dr15Jones** [comment]
The second comment in this thread lists the people responsible. It was this sentence:
> @ggovi, @cmsbuild, @monttj, @davidlange6 can you please review it and eventually sign?

davidlange6 just signs for ops and cmsbuild is just the test system. That leaves @ggovi and @monttj who are the L2s who have to sign.

**Comment by kpedro88** [comment]
@ggovi @monttj please review/sign

**Comment by davidlange6** [comment]
hi @aperloff - the 14 MB file needs to be removed - can it be automatically generated as part of the unit test?

**Comment by aperloff** [comment]
@davidlange6 Whoops, I didn't notice that the file was so large. Unfortunately the file takes a long time to generate and can't be made on the fly. Does CMSSW have some sort of large file storage like https://git-lfs.github.com/? Alternatively, can the file be hosted in CERNBox and then downloaded during the test? A third, but less pleasing, option would be to remove some lines from the file, but this would limit it's usefulness during the testing.

**Comment by aperloff** [comment]
@davidlange6 So @kpedro88 just told me about the cms-data repository in which there is a CondFormats-JetMETObjects folder. I assume I can store the really large file there using a separate PR and remove it from this PR. Would that be okay? Since I use edm::FileInPath will it pick up these files from the other repo? Is there a way for cmsbot to test both PR at once?

**Comment by davidlange6** [comment]
sure we do - but the the question is if its worth the effort to carry around this file long term? Another way to ask the question is what functionality does this unit test give up if you had 10x fewer pt bins, eta bins, and rho bins?

**Comment by aperloff** [comment]
@davidlange6 I've slimmed down the large file about as much as I can (rebin eta by 2 and rho by 5). It is now 1.03MB, but still takes somewhere around 3 minutes to generate. I am assuming this is too long for a unit test which is supposed to take around 1 second. This will give the file roughly the same utility while still keeping the size in check. Any smaller and it starts to lose its usefulness. Should the file still be moved to the cms-data repository? I can do that PR fairly quickly.

**Comment by aperloff** [comment]
@davidlange6 @kpedro88 I have now merged the creation of the text files for testing with the unit test. The reason it is so fast now (less than 1 second) is that this is toy binning. The previous file used more realistic binning. Upon further consideration I think this solution should be adequate. So this PR no longer stores large text files. 

I have run the unit tests myself using ''scram b runtests' and everything worked fine for me. Could the tests please be triggered to check this PR?

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@aperloff actually, just a commit doing `git rm` on the 15MB file is not sufficient to remove it from the history, so it would still increase the size of the official-cmssw repo if this PR were merged as is.

The easiest way to fix this now would be to use interactive rebase to combine 7220d1c4cfb281df258b5fee20f10895e3de9cf1, 6a9e6d8868bde0af7c65b11d4a7b614b8f633ed6, and 8dadee84fb271a39336f7913b6d523dc67ebf437 into one commit, so the large files will no longer be present anywhere in the history. I can show you how to do this.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@ggovi @monttj please sign

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@aperloff - thanks - but please fix the tab vs 3-space indentation issues introduced in this PR via a followup PR.

**Pull request merged**
