### PR TITLE
Bph reco refactored 12 4 x

### PR DESCRIPTION
**Pull request by ronchese**
#### PR description:

The BPH reconstruction package (doc. in https://twiki.cern.ch/twiki/bin/view/CMS/BPHReco_V2 , to be updated with new features)
in HeavyFlavorAnalysis/RecoDecay and HeavyFlavorAnalysis/SpecificDecay has been redesigned using templated interfaces for common decay patterns.

#### PR validation:

Tested on a UL MINIAOD file (Charmonium dataset), same output as previous code.
All test in runtheMatrix passed.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 12_4 of PR 38524 for 12_5
Needed to include BPH reconstruction plots in offline DQM

### CODE REVIEW

**Comment by tvami** [comment]
-1
 * seems like the branch is for 12_4_X

**Comment by ronchese** [comment]
This IS a branch for 12_4_X, checked out from CMSSW_12_4_X_2022-06-26-2300, backporting PR 38524.
Did I do something wrong?

**Comment by tvami** [comment]
> Did I do something wrong?

Yes, that this is the 12_5_X target
Screen Shot 2022-06-28 at 09 08 34

**Comment by tvami** [comment]
-1
 * the PR is closed

**Pull request closed without merging**
