### PR TITLE
fixing HI workflows for Phase 1 and 92X

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR is the equivalent of #20496 for 9_2_X, it should fix HI recontruction in DQM.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
why is it smaller than the original PR?

**Comment by fioriNTU** [comment]
It is not smaller, it is bigger. I had to chenge here also the TrackCluster plugin to permit to read the vertext type by the configuration.

**Comment by fioriNTU** [comment]
the failure is due to the HLT monitoring of the Pixel detector, now it should be fixed

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
