### PR TITLE
Finalising esConsumes migration of HLTrigger/

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is a follow-up of #33260, to finalise the `esConsumes` migration (see #31061) of `HLTrigger/`, based on this [recent IB report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_11_3_X_2021-04-06-2300/slc7_amd64_gcc900/reports/eventsetuprecord-get.yaml) (see mentions of `HLTrigger/`).

It requires a non-entirely-trivial update of `EcalReadoutTools`, for which I loosely followed part of what was done in #31892.

#### PR validation:

None (other than compiling).

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33362	d9b5911
- code changes are in line with the PR description: `EcalReadoutTools` use esConsumes via `EcalReadoutTools::ESGetTokens`.
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
    - some of CMS Clang-Tidy warnings appearing in the test summary are addressed in #33367

**Comment by yuanchao** [comment]
+1
* WF matrix tests and unit tests passed
* CLang tidy and static build warnings (esConsumes migration) are both from PFClusterEMEnergyCorrector.cc though not the modified parts of this PR.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
