### PR TITLE
DD Core Cleanup

### PR DESCRIPTION
**Pull request by ianna**
- Use auto for simplicity
- Use range-based for loops
- Remove commented out code
- Use enum class for operations
- Clean up unneeded typedefs

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by diguida** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
@danduggan, @cerminar, @deguio, @mmusich - could you please review the changes and sign?

**Comment by mmusich** [comment]
+1 
minimal changes in AlCa packages

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
