### PR TITLE
Remove duplicate dependency from L1Trigger/CSCTriggerPrimitives BuildFile.xml

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Remove duplicate
```xml
<use name="Geometry/CSCGeometry"/>
```
entry from `L1Trigger/CSCTriggerPrimitives/BuildFile.xml`.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1
- Duplicate line removed
- Jenkins tests pass

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
