### PR TITLE
Create PythiaCP5TuneUpSettings_cfi.py

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by fabiocos** [comment]
+code-checks

**Comment by fabiocos** [comment]
@smuzaffar also here the cms-bot looks stuck

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
