### PR TITLE
Modify tau sequences to not pull payloads from outside GT

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR addresses a longstanding issue with tau modules pulling payloads from outside GT (https://github.com/cms-sw/cmssw/issues/43797). 
The issue at the AOD and miniAOD steps is solved since CMSSW 12 series, so this PR fixes it at the nanoAOD step and it is believed that it closes the issue with current CMSSW series. 
Changes introduced by this PR are purely technical and do not change produced samples.

#### PR validation:

Validated locally with nano configurations for `Run3` and `Run2,run2_nanoAOD_106Xv2` eras with and without access to frontier (the latter with GTs dumped to sqlite files), and with (limited set of) matrix tests (`runTheMatrix.py -l limited -i all --ibeos`).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR can be easily backported to 14_0 series if needed - please let me know.
Backport to 10_6 will require some effort as it will require also modifications at AOD and miniAOD steps and preparation of a set of new GTs therefore I would like to avoid this.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
type tau

**Comment by mbluj** [comment]
I was able to reproduce failure in PhysicsTools/PatAlgos tests (namely in `patTuple_PF2PAT_cfg.py`), but I am not sure if it is related ti this PR. I am trying to check it also with plain 14_1_X IB.
In meantime I added two minor fixes to tests in RecoTauTag which still used payloads from outside of GT.

**Comment by hqucms** [comment]
please test

**Comment by mbluj** [comment]
I checked that this test does not work in (plain) IBs down to CMSSW_14_1_X_2024-04-03-2300. I do not know what was introduced later which makes the test crashing with stack dump (I am not able to find reason in it), but it is not related to this PR. The test is successful also when this PR is merged on top of CMSSW_14_1_X_2024-04-03-2300

**Comment by mbluj** [comment]
> > I was able to reproduce failure in PhysicsTools/PatAlgos tests (namely in `patTuple_PF2PAT_cfg.py`), but I am not sure if it is related ti this PR. I am trying to check it also with plain 14_1_X IB. In meantime I added two minor fixes to tests in RecoTauTag which still used payloads from outside of GT.
> 
> The failure in the unit test is also in the plain IB. It seems to be caused by #44590.

OK, thanks for confirmation.

**Comment by hqucms** [comment]
+1

Failure in the unittest is also in the plain IB and not related to this PR.

**Comment by mbluj** [comment]
> @mbluj Could you please make a backport to 14_0_X? Thanks!

Sure, I'll do it.

**Comment by mbluj** [comment]
> > @mbluj Could you please make a backport to 14_0_X? Thanks!
> 
> Sure, I'll do it.

Just a warning: there are several PRs ongoing which are potentially in conflict with this development because of changes in nano configs. This will require rebasing and conflict solving.

**Comment by antoniovilela** [comment]
ignore tests-rejected with ib-faliure

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
