### PR TITLE
Improve Score Definition and EM Trackster Reconstruction

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

This PR is mainly fixing long-standing issues related to `LayerClusters` and `Tracksters` validation. A quick summary of the improvements in this regard:

   * Fix the score definition that was wrong in both cases. In particular, changes to the overall normalization were needed.
   * Fix the computation of the fraction of the shared energy between a `Trackster` and its linked `CaloParticles`
   * Review the definitions of _merge_, _duplicate_ and _fake_ rate for the `Trackster` validation. Once this PR will be merged, the accompanying documentation at [this link](https://hgcal.web.cern.ch) will be updated.
   * Add the possibility to run the validation on several `Tracksters` collections in a more or less transparent way. **More changes are foreseen for the future** (in separate PRs), namely:
      * separate the _association code_ from the _validation code_, creating ad-hoc `EDProducers` for that purpose;
      * improve the overall `python` definition of parameters and the accompanying `C++` code;
      * improve the python plotting capabilities.
   * The improved `Trackster` validation, when tested on closeby samples, allowed for better tuning of the cuts of the electromagnetic `TICL` iteration.

We expect differences in `Tracksters`' output for the electromagnetic iteration and, also, changes in few histograms (binning and naming)

#### PR validation:

Tested with:
   * `runTheMatrix.py -l limited -i all --ibeos`
   * `runTheMatrix.py -w upgrade -l 20493.51,20493.52`

### CODE REVIEW

**Comment by rovere** [comment]
please test workflow 20493.52

**Comment by rovere** [comment]
please test workflow 20493.52

**Comment by jfernan2** [comment]
@rovere besides the changes you describe, the PR is removing ~270 histograms from HGCAL/HGCalValidator/hgcalMultiClusters
Is that expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-10-24-2300+71ccf6/33953/dqm-histo-comparison-summary.html

**Comment by rovere** [comment]
@jfernan2 yes, it is expected. The objects that were monitored are not compliant with the changes I made. But since the previous code was producing bogus results, I decided to drop them out from validation and restrict the validation to object derived from the `TICL` reconstruction. In the coming days, after this PR is merged, I'll promote `TICL` to be the default reconstruction for Phase2 and we will eventually add more plots into the validation sequence for `HGCal`.
Thanks for checking.

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- Reco changes are only in a few tuned parameters in the trackstersEM, the producer for the trackster EM iteraction: I expect that the effect of the tunings had been already evaluated by the proponents of this PR
- No other changes are visible in reco outputs for the non TICL workflows, while the changes in the DQM plots is discussed above in this thread

**Comment by fabiocos** [comment]
@rovere @schneiml @jfernan2 this PR is conflicting with #28092 if that is merged on top of this one:

```
10:50 cmsdev25 1094> git cms-merge-topic 28092
From .
 * [new ref]                            -> merge-attempt
remote: Enumerating objects: 188, done.
remote: Counting objects: 100% (188/188), done.
remote: Total 228 (delta 188), reused 188 (delta 188), pack-reused 40
Receiving objects: 100% (228/228), 41.20 KiB | 715.00 KiB/s, done.
Resolving deltas: 100% (200/200), completed with 99 local objects.
From https://github.com/cms-sw/cmssw
 * [new ref]                 refs/pull/28092/head -> cms-sw/refs/pull/28092/head
Switched to branch 'merge-attempt'
Auto-merging Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
CONFLICT (content): Merge conflict in Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc
Auto-merging Validation/HGCalValidation/plugins/HGCalValidator.cc
Auto-merging Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
CONFLICT (content): Merge conflict in Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h
Removing DQMServices/Core/test/DQMTestStandaloneBuildOfDQMStore.cc
Removing DQMServices/Core/interface/ConcurrentMonitorElement.h
Automatic merge failed; fix conflicts and then commit the result.
Unable to merge branch refs/pull/28092/head from repository cms-sw.
```

Given the different status of maturity I would move forward with #28265 just to let you all know about it

**Comment by schneiml** [comment]
@fabiocos yes, I am aware that #28092 conflicts all the time (due to those `DQMGobalEDAnalyzer` based modules being under active development...). I am fine with rebasing it another time, but that is why I'd like it to get in soon.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
