### PR TITLE
Fastsim triplet seed selection branch

### PR DESCRIPTION
**Pull request by a-kapoor**
This branch implements hit triplet check in FastSim.

The validation plots are here:
http://test-folders.web.cern.ch/test-Folders/plots_14May/

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by slava77** [comment]
just to note that most of this code is an iteration over previously closed #14083

**Comment by lveldere** [comment]
Thanks @slava77 

This is indeed  #14083 with on top a refactoring of the FastSim SeedFinder and the FastSim TrajectorySeedProducer.

**Comment by lveldere** [comment]
+1

changes observed in fastsim are expected

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14554	c6ff376
- changes in reco code look OK: some refactoring, splitting out some code to ::hitTriplets  methods in various multi-hit generators.
- jenkins tests pass and comparisons with baseline show changes only in fastsim workflows, as expected

**Pull request merged**
