### PR TITLE
Fix using unscheduled execution with a SubProcess

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixed the case where a module from a parent process is triggered by
a data request from a module in a SubProcess.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please abort

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The unit test failure is unrelated to this pull request.

**Comment by davidlange6** [comment]
merge




On 17 Dec 2016, at 15:36, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


The unit test failure is unrelated to this pull request.

**Pull request merged**
