### PR TITLE
backporting of the Online ESProducer code for next MWGR

### PR DESCRIPTION
**Pull request by gennai**
#### PR description:

This is a back porting of the code needed to test the ESProducer introduced in 11_2_x for the Run3 online beamspot workflow.

#### PR validation:
I have checked using the readOnlineBeamSpotFromDB.py under RecoVertex/BeamSpotProducer/test that I can read the payload created from the past MWGR as well as reading those in the GT after having converted them.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
original PR was: #30965 
(already merged)

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by gennai** [comment]
my bad, I will fix it when back from holidays

**Comment by gennai** [comment]
This latest commit has reverted the online producers (which should not have touched, I did it by mistake). 
Now the file modified are the same as the original PR

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by silviodonato** [comment]
@cms-sw/alca-l2 @cms-sw/db-l2 @cms-sw/reconstruction-l2 this PR is needed for the next MWGR

**Comment by tlampen** [comment]
+1

**Comment by jpata** [comment]
+1

- tests pass
- is a backport of https://github.com/cms-sw/cmssw/pull/30965 and brings in only the needed changes

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
