### PR TITLE
Run3-gem68 Take care of deprecated codes in Geometry/CSCGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of deprecated codes in Geometry/CSCGeometry

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ptcox** [comment]
Thanks for making these updates!

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
