### PR TITLE
Run3-alca192A Utilize edm::LogVerbatim instead of cout in a number of classes of Calibration/IsolatedParticles

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Utilize edm::LogVerbatim instead of cout in a number of classes of Calibration/IsolatedParticles

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@yuanchao @pohsun @francescobrivio Please approve this PR

**Comment by francescobrivio** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
