### PR TITLE
[SIMULATION-UPGRADE] Changes suggested by new llvm18 clang-format

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR applies clang-format changes suggested by new llvm18 ( see https://github.com/cms-sw/cmssw/issues/45870 )

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
