### PR TITLE
Run2-hcx143 Make codes compatible with current HCAL geometry (Calibration/Tools)

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Can you review and approve this PR?

**Comment by lpernie** [comment]
Hi @bsunanda , these changes seems minimal. Should this PR go together with https://github.com/cms-sw/cmssw/pull/20124 and https://github.com/cms-sw/cmssw/pull/20130 ?

**Comment by bsunanda** [comment]
@lepernie I am trying to go through packages one by one. Kindly approve this. It is better for me if I can group the packages more logically

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
