### PR TITLE
GEM Geometry Builders Remove const_cast

### PR DESCRIPTION
**Pull request by ianna**
* Based on https://github.com/cms-sw/cmssw/pull/20260 and fixes const castness in DB builder.

@davidlange6 - I suggest accept @jshlee's PRs as a bugfix and backport.

Note, the builder from DDD is not used in production.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
