### PR TITLE
Fix PR #38437 to disable mkFit in pixelLessStep

### PR DESCRIPTION
**Pull request by mmasciov**
### PR description:

This PR offers a fix to PR #38437, that disables mkFit for pixelLessStep, so that the new era is fully recognized.

### PR validation:

Standard MTV for SoftQCD (PU=0) sample:
http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/SoftQCD/MTV_SoftQCD_PRFix/

Denominator (blue): default Run3 era
`cmsDriver.py step3 --conditions auto:phase1_2022_realistic -s RAW2DIGI,RECO:reconstruction_trackingOnly,VALIDATION:@trackingOnlyValidation,DQM:@trackingOnlyDQM --datatier DQMIO -n 5000 --geometry DB:Extended --era Run3 --eventcontent DQM --no_exec --filein file:/data2/mmasciov/SoftQCD/CMSSW_12_4_0_pre4/src/step2.root --fileout step3_SoftQCD_default.root --python_filename step3_SoftQCD_default.py --nThreads 8`

Numerator (red): Run3_ckfPixelLessSttep era
`cmsDrivery.py step3 --conditions auto:phase1_2022_realistic -s RAW2DIGI,RECO:reconstruction_trackingOnly,VALIDATION:@trackingOnlyValidation,DQM:@trackingOnlyDQM --datatier DQMIO -n 5000 --geometry DB:Extended --era Run3_ckfPixelLessStep --eventcontent DQM --no_exec --filein file:/data2/mmasciov/SoftQCD/CMSSW_12_4_0_pre4/src/step2.root --fileout step3_SoftQCD_ckfPixelLess.root --python_filename step3_SoftQCD_ckfPixelLess.py --nThreads 8`

### CODE REVIEW

**Comment by mmusich** [comment]
duplicate of https://github.com/cms-sw/cmssw/pull/38563

**Comment by mmusich** [comment]
@mmasciov please add a wf to runTheMatrix so that it can tested. 
Thanks.

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
type bugfix

**Comment by mmasciov** [comment]
@mmusich, just added a commit with this. Sorry for the delay.

**Comment by mmusich** [comment]
test parameters:
    * workflows = 11634.71,11634.72

**Comment by mmusich** [comment]
Can we bypass upgrade here? It has nothing to do with it.

**Comment by AdrianoDee** [comment]
+1
(Just to remove the label, this actually has nothing to do with upgrade)

**Comment by mmusich** [comment]
@perrotta 

> while looking at the logs I noticed the following warning (unrelated to this fix) that you may be interested in

See https://github.com/cms-sw/cmssw/issues/34476. In short, wontfix.

**Pull request merged**
