### PR TITLE
Adding PNET scores to offline HLT DQM

### PR DESCRIPTION
**Pull request by aniketkhanal**
**PR Description**

This PR aims to replace ParticleNet(PNET) as the default offline HLT b-tagging algorithm updating [#42937 ](https://github.com/cms-sw/cmssw/pull/42937), while creating new folders for each path inside HLT/BTV to keep the current DeepJet histograms for groups that still use it. 

It also updates the titles and x-axis labels for the b-tagging efficiency histograms (currently mislabeled as CSV). 

The expected changes are as follows: 
1. The already existing folders inside HLT/BTV will contain PNET input plots instead of DeepJet.
2. For each path, we now have a separate '*_DeepJet' folder that contains plots with DeepJet inputs (note: some paths malfunction with PNET, so they only contain DeepJet folders)
3. The histograms with name effic_bjetCSV now have appropriate titles and x-axis labels for both PNET and DeepJet. 

**PR Validation**

The changes pass the basic tests suggested in https://cms-sw.github.io/PRWorkflow.html. 
12834.0 workflow runs without error and all the changes are visible in local GUI.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
Hi @aniketkhanal , could you please confirm whether the [warnings](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c8339d/38902/llvm-analysis/runStaticChecks.log) e.g. for potential memory leaks are safe?
`src/DQMOffline/Trigger/src/HLTMuonMatchAndPlot.cc:463:1: warning: Potential leak of memory pointed to by 'edgesX' [cplusplus.NewDeleteLeaks]
  463 | }
      | ^
src/DQMOffline/Trigger/src/HLTMuonMatchAndPlot.cc:463:1: warning: Potential leak of memory pointed to by 'edgesY' [cplusplus.NewDeleteLeaks]
2 warnings generated.`

Thanks!

**Comment by mmusich** [comment]
@tjavaid 

> could you please confirm whether the [warnings](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c8339d/38902/llvm-analysis/runStaticChecks.log) e.g. for potential memory leaks are safe?

Sorry, but isn't this already present in the IB static analyzer logs: https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_1_X_2024-04-29-1100/el8_amd64_gcc12/llvm-analysis/report-0bf3b2.html#EndPath ?

Why is this blocking this particular PR? as far as I can tell this has nothing to do with it.

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
@aniketkhanal do you plan a 14.0.x backport for the current data-taking?

**Comment by Martin-Grunewald** [comment]
It seems this PR creates problems for HIon tests in TSG:
```
----- Begin Fatal Exception 02-May-2024 09:40:49 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 606 stream: 0
   [1] Running path 'dqmoffline_step'
   [2] Prefetching for module TopMonitor/'BTagMu_AK8Jet300_Mu5'
   [3] Prefetching for module BTagProbabilityToDiscriminator/'pfMassDecorrelatedParticleNetDiscriminatorsJetTags'
   [4] Prefetching for module BoostedJetONNXJetTagsProducer/'pfMassDecorrelatedParticleNetJetTags'
   [5] Calling method for module DeepBoostedJetTagInfoProducer/'pfParticleNetTagInfos'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Jet
Looking for module label: ak8PFJetsPuppi
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
Now also in an issue https://github.com/cms-sw/cmssw/issues/44899

**Comment by aniketkhanal** [comment]
> @aniketkhanal do you plan a 14.0.x backport for the current data-taking?

@mmusich Yes we do

**Comment by mmusich** [comment]
>  Yes we do

Ok. But then you also need to backport https://github.com/cms-sw/cmssw/pull/44926 together to avoid relval failures.

**Pull request merged**
