### PR TITLE
Run3-alca237 Modify most of the scripts needed to get IsoTrack calibration of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify most of the scripts needed to get IsoTrack calibration of HCAL

#### PR validation:

Applies to a sample of data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
Can the change in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_1_X_2023-02-28-2300+481ac1/55782/11634.7_TTbar_14TeV+2021_trackingMkFit/EgammaV_ConversionValidator_ConversionInfo.html come from this PR?

**Comment by tvami** [comment]
i.e. are these macros used at all in CMSSW?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
> i.e. are these macros used at all in CMSSW?

I never got an answer to this question

**Comment by bsunanda** [comment]
@malbouis, @yuanchao, @ChrisMisan, @tvam Please approve this PR

**Comment by bsunanda** [comment]
@tvami They are used in analysing AlCaReco files by the HCAL calibration team.

**Comment by tvami** [comment]
+alca
 * code is used privately, relying on author's private tests

**Comment by perrotta** [comment]
+1

**Pull request merged**
