### PR TITLE
Validation/Geometry: Tracker Air Categorization

### PR DESCRIPTION
**Pull request by vargasa**
Logs were showing that Air was being sent to 'Other' Category:

`MaterialBudgetData: Material forced to 'Other': Air in volume Tracker`

Air itself is not part of the tracker maps ([x0](https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/data/trackerMaterials.x0), [x1](https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/data/trackerMaterials.l0)), and it may be related with a previous issue https://github.com/cms-sw/cmssw/issues/23734 in which Air category histograms were rendering empty.

 This PR addresses this issue as well as make independent Tracker/HGCal building maps process and some cleaning. @apsallid confirmed none of these changes affect HGCal work

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by cvuosalo** [comment]
+geometry

**Comment by cvuosalo** [comment]
+1
Trying to approve for geometry again

**Comment by fabiocos** [comment]
@vargasa this PR removes several LogInfo dumping information about the material. Are they not considered any more interesting?

**Comment by vargasa** [comment]
@fabiocos none of the removed code was being executed as stated in the commit description

**Comment by fabiocos** [comment]
@vargasa ok, thanks for the clarification. I am not sure why the matTable was empty (could you please clarify ?), but of course if this is the case it makes sense.

**Comment by fabiocos** [comment]
+1

**Comment by vargasa** [comment]
@fabiocos The map for the categorization process that is being used is created in a [later stage](https://github.com/cms-sw/cmssw/pull/25231/commits/9e0e957e0ff0146593d541c11a3d09e7c103d19c#diff-34fc15cf1f91ebd0aaa54f040a6a0e4dL126), this `matSize==0` is the [default size](https://github.com/cms-sw/cmssw/pull/25231/commits/9e0e957e0ff0146593d541c11a3d09e7c103d19c#diff-34fc15cf1f91ebd0aaa54f040a6a0e4dL31) for the table `G4Material::GetMaterialTable()` [check fIndexTable](http://www.apc.univ-paris7.fr/~franco/g4doxy/html/G4Material_8cc-source.html#l00219). It is hard to see why or how this logic was used in the past as there is no history beyond [Snapshot of CMSSW_6_2_0_pre8](https://github.com/cms-sw/cmssw/commits/master/Validation/Geometry/src/MaterialBudgetCategorizer.cc)

**Pull request merged**
