### PR TITLE
MTD geometry: add proton ProdCuts to active MTD scenarios

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Addressing issue #27343 for MTD scenarios available in master but not yet adjusted (D73 is already ok). xml files referring to older scenarios removed in master are untouched (and should likely be removed at some point).

#### PR validation:

Code compiles, wf 23234.0 runs smoothly.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
