### PR TITLE
NANO: rework for Prompt (part2)

### PR DESCRIPTION
**Pull request by mariadalfonso**
part1 was in #34661

part2 migrate ele,lowPtEle,photon from Sequence to Task
no changes expected in any of the modifiers

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

(previously RelVals-INPUT error)

**Comment by mariadalfonso** [comment]
+xpog

technical changes, no change in the quantities

**Comment by mariadalfonso** [comment]
would be great if we can merge this in this morning IB so that I can proceed with part3

**Comment by qliphy** [comment]
+1

**Pull request merged**
