### PR TITLE
Fix errors from Clang 4.0.0

### PR DESCRIPTION
**Pull request by davidlt**
The following errors are fixed:

    error: bool literal returned from 'main'
    error: ordered comparison between pointer and zero

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by davidlt** [comment]
We don't have yet CMSSW_9_2_X release, thus tests will not work.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
Technical

**Pull request merged**
