### PR TITLE
[12.2.X] Enhance PixelTrack SoA DQM monitoring 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a combined backport of https://github.com/cms-sw/cmssw/pull/36392 and https://github.com/cms-sw/cmssw/pull/36432.
Restructuring SiPixelPhase1MonitorTrackSoA to use the pixel track quality information, number of layers and profiles of # hits, # layers and chi2 vs track eta/phi;.
   * 9458a7bccc77ed380aef1a794aaf057efe83492f : adds PixelTrack quality monitoring to SiPixelPhase1MonitorTrackSoA
   * b3de8efbac7a5a0b05459c8478ac93a6ac891b33 : SiPixelPhase1MonitorTrackSoA: restructure PixelTrack monitoring to filter for loose and above track quality
   * 81258c8210c91fdf6e3c3f530a080b439ab745dc : adds n. layers histogram to `SiPixelPhase1MonitorTrackSoA` (as suggested at https://github.com/cms-sw/cmssw/pull/36392#issuecomment-988678177);
   * 32c3b356b1a4b369873d63078cd599a06f5d462f : adds profiles of # hits, # layers and chi2 vs track eta/phi;
   
#### PR validation:

Run `runTheMatrix.py --what gpu -l 11634.506` on a `lxplus-gpu` node.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This backport is needed for eventual submission of large scale RelVals for GPU vs CPU reconstruction checks in this cycle.

### CODE REVIEW

**Comment by mmusich** [comment]
backport of #36392 and #36432

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
