### PR TITLE
Enable Geant4 options to speed-up FullSim

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
To speed-up FullSim for 2-3% two new options available with Geant4 11.1 are enabled:

1) Enable combined process of transportation with multiple scattering. This combined process speed-up Run3 FullSim for ~2%, for Phase-2 for ~8%.

2) Enable cut on photoelectric process below K-shell. This speed-up simulation for ~1%.

Simulation histories will be changed, so we do not expect regression.

#### PR validation:
Test beam 2006 results (https://test-civanch.web.cern.ch/test-civanch/run_matrix/tbeam2006CMSSW_13_2_X_2023-05-11-1100/ ) show good statistical agreement for ECAL and HCAL energy depositions.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
It seems problem not in this PR.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

Simulation histories are changed, because less number of calls  random number generator.  Regression is not expected but physics should not be affected. One example of validation (blue points - this PR):

image

**Comment by rappoccio** [comment]
+1

**Pull request merged**
