### PR TITLE
Correcting index in getAntiDecayTable

### PR DESCRIPTION
**Pull request by aehart**
This is a commit from @mmasciov that we would like in CMSSW_9_4_X as we need it to generate one of our signal models (for the search for disappearing tracks) with 2017 conditions.

### CODE REVIEW

**Comment by civanch** [comment]
@aehart ,  @mmasciov, sorry, I miss this PR completely. Please, clarify, in which CMSSW you identify the problem. As I can see in the development version and in CMSSW_9_4_3 this place is already correct.

**Comment by aehart** [comment]
I just downloaded the latest CMSSW_9_4_X IB (CMSSW_9_4_X_2018-12-06-1100) and CMSSW_9_4_3, and they both have the wrong index for the `name` vector in `getAntiDecayTable`, which is what this commit fixes. I also see the wrong index in the CMSSW_9_4_X branch on GitHub.

We discovered this bug when trying to generate MC in CMSSW_9_4_0_patch1, where if more than four decay channels are included, the incorrect index causes a seg-fault. We noticed this was fixed by the commit from @mmasciov in the master branch, and would like it back-ported to CMSSW_9_4_X.

**Comment by civanch** [comment]
@aehart , my problem is that we back-ported fixes to CMSSW_9_3_X, which is the official 2017 SIM production version and do not do the same for CMSSW_9_4_X. I suspect, that we need to back-port more lines of code for exotic simulation, not only this particular fix and may be extra known fixes for main simulation. Can you make GEN-SIM step in 9_3_X and remaining steps in 9_4_X?

**Comment by civanch** [comment]
@aehart , does usage of CMSSW_9_3_X resolves the issue? If yes, can you close this PR?

**Comment by aehart** [comment]
Sorry I forgot about this PR, @civanch 

We see now that the central GEN-SIM is done in 9_3_X, not 9_4_X as we originally thought. That was our mistake. So there is not problem for us, and I'll close the PR.

Thanks for your help and patience!

**Pull request closed without merging**
