### PR TITLE
Back-port L1T OfflineDQM fixes to 12_5_X

### PR DESCRIPTION
**Pull request by abrinke1**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Back-port https://github.com/cms-sw/cmssw/pull/39691

Needed to run L1T OfflineDQM for data certification.  @cecilecaillol and @epalencia , please check.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by emanueleusai** [comment]
+1

- difference in DQM plots in Tracking/TrackBuilding/pixelPairStep_quickAssociatorByHits are definitely not caused by this PR

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39691

**Comment by perrotta** [comment]
+1

**Pull request merged**
