### PR TITLE
Added support of Authorization for Tag access (back-port)

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Adding the ability to protect the DB-access on Tag:

for IOV updating.
for concurrent update (lock)
The support of the new feature will be connected with a new version of the DB key certificate.
No change is expected in the access of existing, not upgraded databases (central CMS servers or sqlite files ) . Also, the sqlite files produced with this change are fully forward compatible.

#### PR validation:

unit tests and integration tests

####  Backport of https://github.com/cms-sw/cmssw/pull/32732

The features are required in the 11_2 branch, for the operation of online workflows running at P5

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by christopheralanwest** [comment]
backport #32732

**Comment by christopheralanwest** [comment]
+alca

**Comment by yuanchao** [comment]
+1
* backport of #32732
* WF tests and unit tests all passed
* static build warnings are not part of the modifications

**Comment by silviodonato** [comment]
we will merge this shortly after the MWGR

**Comment by qliphy** [comment]
+1

**Pull request merged**
