### PR TITLE
New PCL Alignment Threshold object and record for HG PCL Alignment [12.4.X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/38195, https://github.com/cms-sw/cmssw/pull/38286 ,  https://github.com/cms-sw/cmssw/pull/38273 and https://github.com/cms-sw/cmssw/pull/38367 

#### PR description:

This is a combined backport of PRs https://github.com/cms-sw/cmssw/pull/38195, https://github.com/cms-sw/cmssw/pull/38286 ,  https://github.com/cms-sw/cmssw/pull/38273 and https://github.com/cms-sw/cmssw/pull/38367 in order to lay down the necessary infrastructural changes to be able to run the Hight Granularity PCL workflow at Tier-0 for the 2022 pp collisions.
See the respective PRs for more details.

#### PR validation:

`cmssw` compiles, relies on the validation done for the master PRs.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a verbatim backport of https://github.com/cms-sw/cmssw/pull/38195, https://github.com/cms-sw/cmssw/pull/38286 ,  https://github.com/cms-sw/cmssw/pull/38273 and https://github.com/cms-sw/cmssw/pull/38367

### CODE REVIEW

**Comment by mmusich** [comment]
urgent
   * as I am not sure that introducing new `CondFormat`s will be accepted once 12_4_0 will be cut. To the attention of @cms-sw/alca-l2 .

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
The conclusion at ORP was that it's fine to add a new CondFormat later on, so this PR should aim for 12_4_1 (i.e not urgent for 12_4_0)

**Comment by tvami** [comment]
+1
 * master PRs tested in IBs

**Comment by perrotta** [comment]
@mmusich could you please check the file CondFormats/PCLConfig/test/AlignPCLThresholdsWriter_cfg.py?
If I am not wrong, it is the only one which is not a verbatim backport of the PRs https://github.com/cms-sw/cmssw/pull/38195, https://github.com/cms-sw/cmssw/pull/38286 , https://github.com/cms-sw/cmssw/pull/38273 and https://github.com/cms-sw/cmssw/pull/38367 that you are mentioning in the description.  Simply to confirm that it is really what you wanted, and nothing got escaped.

**Comment by perrotta** [comment]
+1
- For CMSSW_12_4_0

**Pull request merged**
