### PR TITLE
[14_0_X] Add check on PATLeptonTimeLifeInfoProducer closestState valid state

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Combined backport of #44864 and #44875 
While waiting on feedback from experts on the master PR (#44864), I'm opening this backport in the hope of speeding up the whole process.

#### PR validation:
See master PR for validation.

#### Backport:
Backport of #44864 and #44875

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #44864

**Comment by francescobrivio** [comment]
urgent

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
type tau

**Comment by fwyzard** [comment]
How does the code that called `produceAndFillIPInfo()` know that the values stored in `info` are not valid ?

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
please reply to https://github.com/cms-sw/cmssw/pull/44869#issuecomment-2083694866:





> How does the code that called `produceAndFillIPInfo()` know that the values stored in `info` are not valid ?

**Comment by francescobrivio** [comment]
> please reply to [#44869 (comment)](https://github.com/cms-sw/cmssw/pull/44869#issuecomment-2083694866):
> 
> > How does the code that called `produceAndFillIPInfo()` know that the values stored in `info` are not valid ?

Ciao Andrea, I'm very sorry I completely missed your original post!

Could you expand a bit on your question? I'm not sure I fully get it...from what I understood here is the track (from the `lepton`) that is the problematic object, not the `info` that instead is populated with data from the track.

**Comment by mandrenguyen** [comment]
In that case calls like the following will return zero:
`info.ipLength().value()`
`info.ipLength().error()`
`info.pca().mag()`
`info.ipVector().mag()`

Perhaps @cms-sw/xpog-l2  or @mbluj  can comment on whether a additional function similar to `hasTrack()` should be added to query whether this information is stored or whether simply returning zero is acceptable.

**Comment by francescobrivio** [comment]
Ok understood! Thanks for the explanation!

The quickest (naive) solution that comes to my mind is to move
```
info.setTrack(track);
info.setBField_z(...);
```
at the end of the `if` (i.e. after the `isValid()` check), when the rest of the PCA data is stored in `info`. In this way maybe the `hasTrack()` method will be able to catch the fact that the track was not valid...

**Comment by mandrenguyen** [comment]
> Ok understood! Thanks for the explanation!
> 
> The quickest (naive) solution that comes to my mind is to move
> 
> ```
> info.setTrack(track);
> info.setBField_z(...);
> ```
> 
> at the end of the `if` (i.e. after the `isValid()` check), when the rest of the PCA data is stored in `info`. In this way maybe the `hasTrack()` method will be able to catch the fact that the track was not valid...

That would be a nice solution, but we should still hear from XPOG or the original author what the desired behavior should be in this particular case where there is a track, but this propagation fails.

**Comment by hqucms** [comment]
> > Ok understood! Thanks for the explanation!
> > The quickest (naive) solution that comes to my mind is to move
> > ```
> > info.setTrack(track);
> > info.setBField_z(...);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > at the end of the `if` (i.e. after the `isValid()` check), when the rest of the PCA data is stored in `info`. In this way maybe the `hasTrack()` method will be able to catch the fact that the track was not valid...
> 
> That would be a nice solution, but we should still hear from XPOG or the original author what the desired behavior should be in this particular case where there is a track, but this propagation fails.

I think that is a good solution too. Unless @mbluj or @cms-sw/tau-pog-l2 has a better proposal.

**Comment by francescobrivio** [comment]
Ok I quickly tested it with a simple cout.
With this current PR I get:
```
%MSG-e PATLeptonTimeLifeInfoProducer:   PATElectronTimeLifeInfoProducer:electronTimeLifeInfos  30-Apr-2024 11:24:34 CEST Run: 369998 Event: 31680062
closestState not valid!
...
---------------> info.hasTrack(): 1
```
while moving the `setTrack` at the end of `produceAndFillIPInfo` I get:
```
%MSG-e PATLeptonTimeLifeInfoProducer:   PATElectronTimeLifeInfoProducer:electronTimeLifeInfos  30-Apr-2024 11:30:47 CEST Run: 369998 Event: 31680062
closestState not valid!
...
---------------> info.hasTrack(): 0
```
so this change should propagate downstream that the track had a "non valid state".

If you all agree (@fwyzard @mandrenguyen @hqucms @mbluj @cms-sw/tau-pog-l2 ) I can open a small PR to master to include this change and backport it here ?

**Comment by mandrenguyen** [comment]
fine for me, for what it's worth.

**Comment by fwyzard** [comment]
I'm fine with the proposed change, as it at least makes it clear that the information associated to the track are invalid or incomplete.

Still, it would be nice to hear from the author or XPOG what is the expected behaviour of the code under this circumstance.

**Comment by hqucms** [comment]
Fine from the XPOG perspective too.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
unhold

**Comment by francescobrivio** [comment]
backport of #44875

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by francescobrivio** [comment]
@rappoccio @antoniovilela this is also fully signed, can we merge it and when you deem appropriate start the build of CMSSW_14_0_6_patch1?
Thanks!
Francesco

**Comment by antoniovilela** [comment]
+1
   - Will build patch release and upload only after next IB passes.

**Pull request merged**
