### PR TITLE
Move HGCal and MTD event content customizations to SimCalorimetry and SimFastTiming

### PR DESCRIPTION
**Pull request by makortel**
This PR suggests to move HGCal and MTD event content customizations from SimGeneral to SimCalorimetry and SimFastTiming, respectively, as a follow-up to https://github.com/cms-sw/cmssw/pull/24184#pullrequestreview-143639140.

Tested in 10_3_0_pre6, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

reorganization of the code with no functional change

**Comment by fabiocos** [comment]
+1

**Pull request merged**
