### PR TITLE
Migrate EDModules in RecoPixelVertexing/PixelTrackFitting to esConsumes

### LINKED ISSUE #271: Migrate modules in RecoPixelVertexing/PixelTrackFitting to esConsumes
Done in https://github.com/cms-sw/cmssw/pull/35300

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of https://github.com/cms-sw/cmssw/issues/31061.

Resolves https://github.com/makortel/framework/issues/271

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jpata** [comment]
+reconstruction
- technical, no relevant reco changes (usual ONNX AVX/AVX2 differences)

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
