### PR TITLE
[8_0_X] Add CMSSW version to StatisticsSenderService

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/37220.

#### PR validation:

Unit tests pass

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
This is the last backport

**Comment by makortel** [comment]
The unit test failure is
```
A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.
```
so maybe a timeout?

**Comment by makortel** [comment]
@cmsbuild, please test

Lots of comparison failures (also in other workflows than 140.53), let's try once more.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

Differences were actually because of the TimerService (except in 5.1, but those can not be caused by this PR)

**Comment by qliphy** [comment]
+1

**Pull request merged**
