### PR TITLE
Add missing newlines in DQM modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
DQM/DataScouting
DQM/HcalTasks
DQM/Integration
DQM/L1TMonitorClient
DQM/Physics
DQM/SiPixelMonitorClient
DQM/SiStripMonitorClient
DQM/SiStripMonitorSummary
DQM/TrackerCommon
DQM/TrackerRemapper
DQM/TrackingMonitorSource
DQMOffline/Configuration
DQMOffline/EGamma
DQMOffline/L1Trigger
DQMOffline/Lumi
DQMOffline/MuonDPG
DQMServices/FileIO
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
