### PR TITLE
Update test to use logical file name

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR update test to use logical file name as requested in https://github.com/cms-sw/cmssw/pull/44422#discussion_r1536560712

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This fix has been propagated to backport PRs:  https://github.com/cms-sw/cmssw/pull/44474 and https://github.com/cms-sw/cmssw/pull/44475

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
type bug-fix

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
