### PR TITLE
Towards first hlt menu for 2016 (81X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Towards first hlt menu for 2016 (81X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Uaahh great - base IB has same errors (simL1)

**Comment by davidlange6** [comment]
yes - (two in a row with different L1 errors) - hopefully the 1100 is better.

**Comment by perrotta** [comment]
Closing, and replace with #14324

**Comment by perrotta** [comment]
-1
(Martin: you must close it...)

**Pull request closed without merging**
