### PR TITLE
`TriggerRatesMonitor`: monitor all HLT Paths, but not per PD [`14_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of of https://github.com/cms-sw/cmssw/pull/46522

#### PR description:

From the description of #46522.

(Note: this branch is based on `14_1_4_patch2` and could also be used to build a new patch release on top of `14_1_4_patch2`.)

>This PR suggests an update of the plugin `TriggerRatesMonitor`, a DQM plugin used inside the HLT menu to produce histograms counting the number of events accepted by a given trigger (L1T or HLT), Primary Dataset (PD) and stream.
>
>The current implementation creates a subdirectory named `HLT/` which in turn contains a subdirectory for every PD; in each PD subdirectory, there are 5 histograms for each Path assigned to said PD.
>
>If a Path is assigned to _N_ PDs, each of its 5 histograms will be created and filled _N_ times, leading to duplicate information. Such a duplication is particularly visible in the case of trigger menus such as the PbPb one,
where there is a large number of PDs split in a round robin, with each PD having the same content in terms of trigger Paths. In addition, the current approach ignores trigger Paths which are not assigned to any PD (such Paths exist, they are normally used for monitoring purposes, to compute the result of a given trigger Path without writing out the events it accepts).
>
>This PR removes the per-PD structure in the `HLT/` directory created by `TriggerRatesMonitor`, simply filling the latter directory with 5 histograms for every Path in the trigger menu (with 1 subdirectory per Path, each with 5 histograms), ignoring its relation to any PDs (information on the Primary Datasets is already provided in the `Datasets/` directory created by this same plugin).
>
>On Oct-27 in run-387440, while using the 2024 PbPb menu in a commissioning run (no stable beams), a large delay in the macro-merging of the `DQMHistograms` pb files was observed, and the current suspicion is that the large size of these files in the PbPb menu might be part of the problem; this led to this attempt to reduce the number of histograms.

#### PR validation:

None beyond the validation done for #46522 (which was done in 14_1_X).

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#46522

Backported to `CMSSW_14_1_X` for data-taking purposes (used at HLT).

### CODE REVIEW

**Comment by mmusich** [comment]
backport of of https://github.com/cms-sw/cmssw/pull/46522

**Comment by mmusich** [comment]
urgent

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
