### PR TITLE
[14.1.X] Remove legacy L1T digis dependencies in Online DQM

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46716

#### PR description:

In the ticket [CMSALCAFAST-94](https://its.cern.ch/jira/browse/CMSALCAFAST-94), while testing a new Global Tag candidate meant for a general cleaning of unused / previous runs unmaintained records, few online DQM clients (`dt4ml`, `dt`, `ecal`, and `hlt`) encountered issues and failed.
The reason of these failures was analyzed as unnecessary dependencies of the current DQM clients on the legacy L1T digis.
This is fixed / worked around in this PR.
   * 759b8ca9f4649a91c8f31e517cbafcfd5bbfd690 removes the dependency in `HLTSiStripMonitorCluster` by means of re-configuring the few instances of `GenericTriggerEventFlag` class to use the stage 2 gt digis in presence of the `stage2L1Trigger` modifier.
   * 6e2e276785bb78ad96f98cc06295aa215c3cec36 replaces the legacy gt digis with the stage2 ones in presence of the `stage2L1Trigger` modifier
   * 1e37edbf29789c7b2199b22555f844f8cfe8d1ef works around the fact that the `DQM/EcalMonitorTasks/src/ClusterTask.cc` natively doesn't support the stage2 L1T setup but requires products from the legacy L1T (this is followed up also at https://github.com/cms-sw/cmssw/issues/46715) 

#### PR validation:

The following commands work with this branch,

```
scram b runtests_TestDQMOnlineClient-hlt_dqm_sourceclient use-ibeos
scram b runtests_TestDQMOnlineClient-dt_dqm_sourceclient use-ibeos
scram b runtests_TestDQMOnlineClient-dt4ml_dqm_sourceclient use-ibeos
scram b runtests_TestDQMOnlineClient-ecal_dqm_sourceclient use-ibeos
```

when tested by using the Global Tag proposed at  [CMSALCAFAST-94](https://its.cern.ch/jira/browse/CMSALCAFAST-94).

```diff
diff --git a/DQM/Integration/python/config/FrontierCondition_GT_cfi.py b/DQM/Integration/python/config/FrontierCondition_GT_cfi.py
index 5845afa34bb..a91ce205422 100644
--- a/DQM/Integration/python/config/FrontierCondition_GT_cfi.py
+++ b/DQM/Integration/python/config/FrontierCondition_GT_cfi.py
@@ -1,7 +1,7 @@
 import FWCore.ParameterSet.Config as cms
 from Configuration.StandardSequences.FrontierConditions_GlobalTag_cff import *
 from Configuration.AlCa.autoCond import autoCond
-GlobalTag.globaltag = autoCond['run3_hlt']
+GlobalTag.globaltag = "141X_dataRun3_HLT_Candidate_2024_11_15_CleaningOfRecords"  #autoCond['run3_hlt']
 
 #############################################
 #
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/46716 to the last 2024 data-taking release.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovagnerini** [comment]
+1

**Comment by mmusich** [comment]
@cms-sw/orp-l2 what's preventing merge here?

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
