### PR TITLE
Improve TrackingNtuple, add optional SeedStopReason to CkfTrackCandidateMaker

### PR DESCRIPTION
**Pull request by makortel**
This PR updates the `TrackingNtuple` as follows
- Fix TrackingVertex->TrackingParticle links
- Added information
  * about TrackingParticles
     * GenParticle pdgId and flag telling if the TP originates from a B hadron
     * TrackingParticle->seed links
  * about seeds
     * starting state
     * SeedStopReason
- Ntuple python library
  * Classes to provide "default" printouts for seeds, tracks, and TrackingParticles
     * Includes parsing of DetId (currently in a hardcoded/copy-paste way, to be improved in the near future)
  * Split the library to multiple files as it had become enormous
- Two new scripts (in `$PATH`)
  * `printTrackingNtuple.py` to print information on a track/seed/TrackingParticle/hit
  * `diffTrackingNtuple.py` to produce a diff à la "unified diff" of two ntuples (assumed to have the same hits and TrackingParticles)
     * possibility to diff only a single event, or a single track
     * tracks between the ntuples are matched first by their TrackingParticle matches, and that failing, by hits they share (the overall machinery evolved to be quite complex)

The SeedStopReason is added as an optional product of `CkfTrackCandidateMaker` (disabled by default) to provide details of why a seed did not make a track.

Tested in 9_0_0_pre5, should have no effect on standard workflows.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

Apologies for insufficient testing...

**Comment by makortel** [comment]
@cmsbuild, please test

* changed `enum SeedStopReason` to `struct SeedStopReason { enum ...` to not pollute the global name space (in this case I feel the implicit conversion to int too convenient to not use `enum class`)
* fixed a printout for phase2 OT hits
* fixed the previously added phase2 era customize

**Comment by Martin-Grunewald** [comment]
@makortel 
There are now merge conflicts....

**Comment by makortel** [comment]
@cmsbuild, please test

Rebased on top of CMSSW_9_1_X_2017-03-12-2300 (thanks @Martin-Grunewald), and added additional fix to `customiseTrackingNtuple.py` (53fdfb2).

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17792	53fdfb2
- changes are in line with the description; no impact on reco in the default configuration(the additional product is not produced by default)
- jenkins tests pass and comparisons with baseline show no differences

@makortel there are about 10 issues in the TrackingNtuple.cc reported by the static analyzer in the old code. It may be worth checking if all are benign and maybe fix.

**Comment by makortel** [comment]
>  there are about 10 issues in the TrackingNtuple.cc reported by the static analyzer in the old code. It may be worth checking if all are benign and maybe fix.

Thanks @slava77. I'll take a look and follow up in a subsequent PR.

**Comment by makortel** [comment]
At least some of the "dead assignments" are for variables given to LogTrace. I wonder if there is a way to tell that to the static analyzer, or if it's preferred to protect/clutter the code with `#ifdef EDM_ML_DEBUG`'s (given that this piece does not have to reach the ultimate computation performance).

**Comment by makortel** [comment]
A bit irritating feature of the `#ifdef` approach is that apparently I have to put also the LogTrace's inside `#ifdef` as the following seems to give a compilation error
```
#ifdef EDM_ML_DEBUG
  int foo = 2;
#endif
  ...
  LogTrace("Foo") << "foo " << foo;
```

**Comment by franzoni** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
