### PR TITLE
Validation double counting fix

### PR DESCRIPTION
**Pull request by inugent**
Pull request to fix double counting problem + update axis labels.

### CODE REVIEW

**Comment by inugent** [comment]
replaces 8136 which is now closed.

**Comment by deguio** [comment]
@nclopezo 
could the DQM tests be triggered also for this package? I see that they didn't run. not sure what the reason is.
thanks,
F.

**Comment by nclopezo** [comment]
Hi @deguio,
There were some issues with the comparisons of other PRs, so I restarted manually some tests telling it to run only the relvals. And that is why it didn't  trigger the DQM tests for this PR. I restarted them for this PR making sure that now they will run the other tests.

**Comment by deguio** [comment]
-1
ciao @inugent 
I believe that all the comments made by @davidlange6 in #8136 still have to be addressed.
moreover the title doesn't match the content of the PR.
thanks for fixing,
F.

**Comment by inugent** [comment]
Will have to rebase...

**Pull request closed without merging**
