### PR TITLE
Geom: Remove legacy files

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* The TrackerMapDDDtoID class is not used in CMSSW nor there are any unit tests of it. Remove it in order to reduce the amount of code needed to be ported to DD4hep.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@slava77 - Could you, please confirm that the reco differences found in the comparisons are unrelated? Thanks

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna @slava77 to me these are the usual reco differences we observe in tests with PU

@ianna it would be good to adjust https://cmssdt.cern.ch/lxr/source/SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc#0035
The rest seems just some legacy MessageLogger configuration

**Comment by ianna** [comment]
@fabiocos - yes, it's just a wrong legacy(?) message. It has nothing to do with the TrackerMapDDDtoID class. The number of components produced by a GeomDet producer should be correct though. I'll update this in a separate PR.

**Pull request merged**
