### PR TITLE
Remove check on TrackingParticle::numberOfHits()==0 from QuickTrackAssociatorByHits

### PR DESCRIPTION
**Pull request by makortel**
Currently `QuickTrackAssociatorByHits` ignores TrackingParticles with `numberOHits()==0` from track-TrackingParticle association. While this seems like a nice performance optimization, it does cause some track-TrackingParticle pairs to not be associated because of how the `numberOfHits()` is calculated in `TrackingTruthAccumulator`:

1. only SimHits with the same `particleType` as the `SimTrack`'s `pdgId` and the same `particleType` and `processType` as the "first hit" are counted
2. the definition of "first hit" is not robust (or very counter-intuitive if that is the intention; I'll give more details  in another PR ~~fixing that issue~~ improving the situation, the PR is #17382).

Because of 1, I propose to include also TrackingParticles with `numberOfHits()==0` in the track-TrackingParticle association, because the association is (effectively) done with **all** SimHits of a TrackingParticle (via the Pixel/StripDigiSimLinks).

"Accidentally", this PR also fixes the problem caused of 2.

Here are MTV plots in CMSSW_9_0_X_2017-01-23-1100 for ttbar+35PU for phase0, phase1, and phase1 with CA seeding, and CMSSW_9_0_0_pre2 for phase2 (D4) ttbar+PU200
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_9_0_X_phase2debug/
and here for phase2 (D4) ttbar noPU in CMSSW_9_0_X_2017-01-23-1100 (thanks to @ebrondol)
http://ebrondol.web.cern.ch/ebrondol/Phase2Tracking/fixFakes/20170125_TTbar/

The effect on efficiency in phase0, phase1, phase2 PU200 is tiny; phase2 noPU shows few percent increase in |eta| 2-3. The effect on fake rate in phase0, phase1, phase2 PU200 is a 1-2 % overall decrease (can be more in specific phase space regions); phase2 noPU shows ~40 % overall decrease.

Tested in CMSSW_9_0_X_2017-01-23-1100 and CMSSW_9_0_0_pre2, expecting changes like above in the track-TrackingParticle association (no change expected e.g. on RECO itself).

@VinInn @rovere @ebrondol @slava77

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Not sure if the `TrackAssociatorByHits` should be fixed as well
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/SimTracker/TrackAssociatorProducers/plugins/TrackAssociatorByHitsImpl.cc#L497

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by makortel** [comment]
The "another PR" mentioned in the PR description is #17382.

**Pull request merged**
