### PR TITLE
bsunanda:Run2-hcx118 Backport bug fix (as in PR 17773)

### PR DESCRIPTION
**Pull request by bsunanda**
Issue of ieta=29 in Plan 1 or Phase I HE geoemtry

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
urgent

**Comment by kpedro88** [comment]
attn: @deguio

**Comment by bsunanda** [comment]
@ianna Please approve this

**Comment by deguio** [comment]
thanks @bsunanda and @kpedro88

**Comment by franzoni** [comment]
Hello all, does this fix need to enter the conditions update  of 90 https://github.com/cms-sw/cmssw/pull/17886 as well as 91 https://github.com/cms-sw/cmssw/pull/17975  ?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Hi @franzoni - this looks to be only code changes, I presume no GT update is needed. but @ianna is best to confirm

**Comment by davidlange6** [comment]
+1

**Pull request merged**
