### PR TITLE
Phase2-hgx333 Bug fix for invalid DetID declaration for SimHits n V16/V17 geometry versions of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix for invalid DetID declaration for SimHits n V16/V17 geometry versions of HGCal

#### PR validation:

Use test scripts in #40168 to verify that the new validity checks pass all SimHit ID's of V16 and V17 geometries of HGCal. This is the best possible validation of the correction made to the code. Running the code testHGCalSimSingleMuonPt100_cfg.py from Validation/HGCalValidation/scripts after activating the  printout option yielded 2218 | 542 cells with validity flag 0 for V16 | V17 geometries in the original version and after the correction, both the geometries yielded 0 such cells indicating that all SimHit cells now pass the validity tests 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need to be back ported to earlier CMSSW versions

### CODE REVIEW

**Comment by bsunanda** [comment]
type bug-fix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by AdrianoDee** [comment]
please test
(`CMSSW_13_0_X_2022-12-01-1100` is out)

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by srimanob** [comment]
Hi @bsunanda 

Thx for making the fix.

I'm making a sample with and without the PR to make comparison, to see the first order of fixing through the DQM that we spotted the issue at first, and see if there is no additional unexpected impact from this fix. 

I would prefer PR comes with some plots to show, and better description of issue you've discovered. Do you present it somewhere, i.e. HGCAL DPG meeting? @cms-sw/hgcal-dpg-l2

**Comment by bsunanda** [comment]
The plots do not show anything. The old DQM plots were a wrong comparison both red and blue curves were wrong. I gave 2 presentations in HGCal DPG meeting and finally discussed the last change in the HGCal week meeting. If needed I can say a few words in today's SIM meeting.

**Comment by srimanob** [comment]
I think it is better to have those information to the PR description, include a link to the presentation. I give a difficult time to review with only bug-fix in the description. It will be more easily to follow up with material you made. Thanks.

**Comment by bsunanda** [comment]
@srimanob @perrotta @rappoccio Please approve this PR and let it be integrated. We cannot proceed for correcting the remaining bugs till it gets integrated.

**Comment by srimanob** [comment]
+Upgrade

This PR fix the invalid DetID for HGCAL simhits in V16/V17. Validation is done with the test script as mentioned in the PR description. FYI @cms-sw/hgcal-dpg-l2 , in case you have additional comments.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
