### PR TITLE
Printouts r2

### PR DESCRIPTION
**Pull request by deguio**
same as #8010

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by diguida** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #8045 dcc47f7bf784b17f6c75caf03011c0ee216fcab8

This PR eliminates some unnecessary diagnostic outputs. It is the same as #8010, which is for 74X.

The code changes are satisfactory. Jenkins [tests] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8045/6388/summary.html) against baseline CMSSW_7_5_X_2015-03-03-1400 are OK and confirm the reduction in the unneeded warning messages.

**Comment by diguida** [comment]
+1
Forward port of #8010

**Comment by civanch** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request merged**
