### PR TITLE
Tracker Geometry Error Messages with More Details

### PR DESCRIPTION
**Pull request by ianna**
* Improve error message when TrackerGeometry is asked for non-existent DetId
* Move a prototype structure from TrackerGeometry to an analyzer where it is used
* Migrate to multi-threaded analyzers
* Add test python configuration
* Add missing direct dependency
* Remove extra dependency which was already declared to remove a warning

@slava77 - Should there be an Exception thrown? Most of the downstream code does not check DetId validity any more to improve performance. I'd prefer it to crashing. It's your call.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by slava77** [comment]
```
Should there be an Exception thrown? 
Most of the downstream code does not check DetId validity any more to improve performance. I'd prefer it to crashing. 
It's your call.
```

seems OK to crash for the cases here

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - is this IB broken?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18182	62bc0f0
- technical changes in the reco packages, affecting only /test files; the upstream geomtery updates are OK
- jenkins tests pass and comparisons show no differences

**Pull request merged**
