### PR TITLE
Fixing bug in HLTriggerJSONMonitoring L1 and prescale module idenfication : 12_4_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

HLTriggerJSONMonitoring is how the HLT reports path rates to OMS. It was updated in Jun (https://github.com/cms-sw/cmssw/pull/38418) to better support DatasetPaths.

In doing so a bug was introduced in that if a path is after a dataset path, the wrong L1 and prescale module will be identified.

Additionally the logic was improved to only consider the first seed module and also to disregard ignored modules. This fixes problems in some paths which have additional L1 seed modules which are ignored as they want to use this data later in the path.

Credit goes to Adelina Lintuluoto (@alintulu) for spotting this issue in the hilton tests.

#### PR validation:

as in https://github.com/cms-sw/cmssw/pull/39779

backport of https://github.com/cms-sw/cmssw/pull/39779, needed to fix bug in online data monitoring

### CODE REVIEW

**Comment by Sam-Harper** [comment]
please test

**Comment by missirol** [comment]
backport of #39779

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
