### PR TITLE
A fix for missing SelectEvents configuration option

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

A fix for the crash in the second instance of the Event Display when SelectEvents property might be missing.

#### PR validation:

PR was validated locally.

#### if this PR is a backport please specify the original PR:

Backport of #28208. Replaces #27530

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k is this in view of next MWGR?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
