### PR TITLE
Migrate RegressionHelper class in EgammaElectronAlgos to ESGetTokens

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Migrate RegressionHelper class in EgammaElectronAlgos to ESGetTokens.

#### PR validation:

CMSSW compiles and local matrix tests pass.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by guitargeek** [comment]
Please test?

**Comment by qliphy** [comment]
please test

**Comment by jpata** [comment]
+reconstruction

- technical, migrates RegressionHelper to ESGetTokens
- no differences expected or observed

**Comment by silviodonato** [comment]
+1

**Pull request merged**
