### PR TITLE
Move SoA collections ROOT read rules to classes.cc [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Technical, no changes expected.

Move the ROOT read rules of the SoA host collections for the ECAL digis, uncalibrated rechits, and PF rechits from classes_def.xml to classes.cc.

#### PR validation:

None.

#### Backport status

Backport of #44021 to 14.0.x for 2024 data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #44021

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
FYI @thomreis @hatakeyamak @jsamudio @waredjeb

**Comment by fwyzard** [comment]
type ecal

**Comment by fwyzard** [comment]
type pf

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
