### PR TITLE
Enable GEM trigger clusters from EMTF in GEM L1T DQM

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Data vs emulation for GEM TPs in GEM L1T DQM. The purpose of this PR is not to figure out the differences, but rather update the L1T GEM DQM for Run-3. Basically, ```valMuonGEMPadDigiClusters``` is replaced with ```emtfStage2Digis``` since we now have GEM trigger data arriving at the EMTF. The data is not necessarily good, and I think  it shows in the data-vs-emulation plots. 

#### PR validation:

Tested on 10k events of RAW Run-3 data, run 344064. There are many differences, to be discussed at GEM-CSC meetings.

[GEM_dataVsEmul_CMS_Run_344064.pdf](https://github.com/cms-sw/cmssw/files/7342279/GEM_dataVsEmul_CMS_Run_344064.pdf)

Instructions to reproduce the slides on lxplus:
```
## unpack+re-emulate+dqm
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py l1GEM=True mc=False dqmGEM=True \
inputFiles=root:///eos/cms/store/data/Commissioning2021/Cosmics/RAW/v1/000/344/064/00000/dade01f7-bc85-491f-9c9c-7457af399849.root \
maxEvents=10000 dqm=True unpack=True unpackGEM=True l1=True useEmtfGEM=True

## dqm client
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCL1TDQMClient_cfg.py useGEMs=True

## validation report
cmsRun L1Trigger/L1TGEM/test/runGEMTriggerPrimitiveAnalyzer_cfg.py dataVsEmulation=True runNumber=344064 \
dataVsEmulationFile=file:DQM_V0001_R000344064__Global__CMSSW_X_Y_Z__RECO.root
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by jfernan2** [comment]
@dildick please check that everything looks as expected:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-14-1100+c7f842/46177/dqm-histo-comparison-summary.html

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
@rekovic Can you sign off, please? There is no updated to emulation, just a test L1T configuration.

**Comment by qliphy** [comment]
ping @cms-sw/l1-l2

**Pull request merged**
