### PR TITLE
update 2023 geometries for hgcal and muon test configs

### PR DESCRIPTION
**Pull request by kpedro88**
attn: @ianna

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15592 69756b2670aab0272ac11e493755c25f816ea211

Updating Phase 2 HGCal and muon tests to latest geometry scenario. There should be no change in monitored quantities.

The code changes are satisfactory. The Phase 2 unit tests are successful with the new geometry. Jenkins tests against baseline CMSSW_8_1_X_2016-08-24-1100 show no significant differences, as expected.

**Pull request merged**
