### PR TITLE
B-charge tagger improved and retrained

### PR DESCRIPTION
**Pull request by aboletti**
Optimization of the ChargeTagger MVA.

Redefinition of one input variable (jet-charge) and tighter selections on the secondary vertices that are considered for the "sv_ch" input variable.
The MVA weights have been retrained.

### CODE REVIEW

**Comment by slava77** [comment]
... need to wait for the files to show  up in IB.
https://github.com/cms-sw/cmsdist/issues/2492 to be resolved

**Comment by smuzaffar** [comment]
Today's 11h00 IB should have it
https://github.com/cms-sw/cmsdist/pull/2495

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
hopefully this was a transient  problem with DAS

**Comment by cvuosalo** [comment]
I noticed what might be an old bug that probably should be fixed in CandidateChargeBTagComputer.cc:
```
    if ( n_ip_info>0 ) {
      float jet_pt = ip_info.jet()->pt();
      pt_ratio1_ch = pt_ratio1_ch / jet_pt;
      pt_ratio2_ch = pt_ratio1_ch / jet_pt;
      pt_ratio3_ch = pt_ratio1_ch / jet_pt;
    }
```
It looks like `pt_ratio1_ch` should be replaced by `pt_ratio2_ch` and `pt_ratio3_ch` on the last two lines. Otherwise, just assign `pt_ratio3_ch = pt_ratio2_ch = pt_ratio1_ch;`. Secondly, for protection against division by zero, check `jet_pt` > 0 before dividing by it.

**Comment by cvuosalo** [comment]
@aboletti: Is this candidate charge b tagger used in any standard workflows? I can't find any that call it.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by imarches** [comment]
A note before merging: Alessio is still planning an update to this PR, to include the tagger in the b tagging workflow.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15730 4feca0c1fcdc41ab96114dc556e19b77e77aa279

Revision of the charge tagger MVA and addition of this tagger to RECO event content. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-08-2300 show no significant differences, as expected. A test of workflow 136.731_RunSinglePh2016B with 20 events against baseline CMSSW_8_1_X_2016-09-08-2300 also shows no significant differences, and the added tagger does appear in RECO event content:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
      0.0 ->       253.9        254     NEWO   0.02     recoJetedmRefToBaseProdTofloatsAssociationVector_pfChargeBJetTags__reRECO.
-------------------------------------------------------------
  1306376 ->     1306632        256             0.0     ALL BRANCHES
```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
