### PR TITLE
[12_4_X] Add GEM ChMap to all GTs and rename `phase1_2021*`to `phase1_2022*`

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38252 and https://github.com/cms-sw/cmssw/pull/38090

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38252 and https://github.com/cms-sw/cmssw/pull/38090

### CODE REVIEW

**Comment by tvami** [comment]
type gem

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38090

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38252

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

**Comment by missirol** [comment]
+hlt

**Comment by civanch** [comment]
+1

**Comment by missirol** [comment]
Hi @cms-sw/alca-l2 , what's the plan to backport https://github.com/cms-sw/cmssw/pull/38283 to `12_4_X`? (it is needed by #38242)

Could that backport be added to this PR? (maybe that's faster)

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

backport pr

**Comment by bbilin** [comment]
+1

**Comment by missirol** [comment]
@tvami

> I think the plan is to have this merged today, while having https://github.com/cms-sw/cmssw/pull/38242 and https://github.com/cms-sw/cmssw/pull/38283 merged today. So then we can submit the backport of them tomorrow, have them merged by Friday.

Okay. To be clear, https://github.com/cms-sw/cmssw/pull/38283 goes hand-in-hand with #38241 (not #38242).

Anyways, if we'll have a 12_4_X backport of #38283 tomorrow (to help #38242), I think it will be okay. Thanks for clarifying.

**Comment by tvami** [comment]
@qliphy 
can we aim to have this merged for 2300 IB ?

**Comment by qliphy** [comment]
+1

**Pull request merged**
