### PR TITLE
Made L1TStage1Layer2Producer a stream module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The module is used in integration build release validation test and was preventing the use of concurrent LuminosityBlock processing.

As part of this change, also improved const correctness of related classes as well as a few code modernizations of L1TStage1Layer2Producer.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
prompted by #25090

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
This is a technical PR. @benkrikler @rekovic Do you have any objections?

**Comment by silviodonato** [comment]
merge
In case you have any comments, please let me know

**Pull request merged**
