### PR TITLE
Run 2 format of PCC ntupler - version 1

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by slava77** [comment]
Hi Chris,

Why is the run2 development going to 53X release?

**Comment by capalmer85** [comment]
Hi Slava,

It was validated on 8 TeV data to give the same results at the previous
version.  I wanted them both to be in some official place, then port to
74X.  This is what I said I was going to do in 6962.

Is this alright?

Cheers,
Chris

**Comment by slava77** [comment]
The 53X is on a monthly (or less frequent) schedule, and this kind of developments will not trigger a new release by themselves.
This needs to be kept in mind for additions to 53X.

**Comment by capalmer85** [comment]
That's ok.  As long as it is in the queue, I won't worry about it and move
forward.

Thanks,
Chris

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8446	f366ce7

changes are in the analysis-level ntuple code in RecoLuminosity/LumiProducer/test/analysis
the code compiles and runs with the provided test config.
Standard workflows are not affected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
