### PR TITLE
bsunanda:Run2-alca6   Make the last changes for AlCaReco producer and tests for IsoTrack trigg..

### PR DESCRIPTION
**Pull request by bsunanda**
Renamed some of the methods according to cms standard. Added DQM monitor for IsoTrackHB/HE triggers

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
When I ran runTheMatrix.py I get the following results:
10 10 9 7 6 tests passed, 0 0 0 0 0 failed
I built the branch on top of CMSSW_7_5_X_2015-03-17-0200
________________________________

**Comment by nclopezo** [comment]
Hi @bsunanda,
The error is in the baseline (IB) and not in this pull request. The comparisons now run even if there are errors in the IB baseline. The message is to note that the comparison used a baseline in which there were errors. 
See for example https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc481/CMSSW_7_5_X_2015-03-17-1400/pyRelValMatrixLogs/run/401.0_TTbarNewMix+TTbarFSPU+HARVESTFS+MINIAODMCUP15FS/step1_TTbarNewMix+TTbarFSPU+HARVESTFS+MINIAODMCUP15FS.log

**Comment by cvuosalo** [comment]
+1

For #8347 e915271ee48d1f12eb1506733d9f37ee242fac43

This PR change the AlCaReco producer and does some small code clean-up of Reco code requested in previous PR threads. The Reco code changes only involve naming changes and should not have run-time effects.
The Reco code changes bring the code in compliance with CMS naming conventions (thank you  @bsunanda). The Jenkins test [results] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8347/7157/summary.html) against baseline CMSSW_7_5_X_2015-03-18-0200 are satisfactory and show no significant differences. The baseline contains some errors not related to this PR, which prevented some of the Jenkins comparisons from completing. But for the very minor Reco changes in this PR, the available Jenkins results are adequate.

**Comment by deguio** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #8347 be097eaa7a6961527c1db6e7fabcd6a96dd25b2b

A small change was made to non-reco code after Reco approval of this PR. The new Jenkins tests were run on a baseline that is too recent and produced lots of differences unrelated to this PR. As a check, short matrix tests were run against baseline CMSSW_7_5_X_2015-03-17-0200, and they show no significant differences, as expected.

**Comment by mmusich** [comment]
@bsunanda if this is superseded by #8649 can you please close it?

**Pull request closed without merging**
