### PR TITLE
[12.5.X] use ibeos protocol for DQM/Integration unit tests (online DQM unit tests)

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/39669#

#### PR description:

Title says it all, from suggestion at https://github.com/cms-sw/cmssw/issues/39669#issuecomment-1287484400

#### PR validation:

Run successfully `scram b runtests use-ibeos` with the fix

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported to at least 12.4.X

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent
   * please @cms-sw/dqm-l2 have a look (IBs are still broken)

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
