### PR TITLE
Removing CSV+SL and adding SL taggers to the default PAT jet configuration

### PR DESCRIPTION
**Pull request by ferencek**
Given the fact that the CombinedMVA tagger uses SL tagger discriminators as input, it would be beneficial to also have SL taggers stored in MiniAOD to speed up and simplify any future retrainings of ''supercombined" taggers.

@pvmulder @imarches @acaudron

### CODE REVIEW

**Comment by monttj** [comment]
@ferencek 
I am just curious that we are not using "pfCombinedSecondaryVertexSoftLeptonBJetTags" tagger at the analysis level ?

**Comment by monttj** [comment]
please test

**Comment by ferencek** [comment]
@monttj, studies of the performance of CSV+SL indicated there are some not fully understood features in its training (@pvmulder can confirm) and that in the end better performance is obtained from `pfCombinedMVABJetTags`. The main difference between the two is that CSV+SL takes as input all of the input variables of the CSVv2 tagger and the soft lepton (SL) taggers while `pfCombinedMVABJetTags` takes as input the output disciminators from the JP, CSVv2, and SL taggers.

**Comment by monttj** [comment]
+1

**Comment by monttj** [comment]
@ferencek thank you!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
