### PR TITLE
Run3-sim33 Add testing tool for Geant4/GeantV compatibility

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Analyzer to analyze hits produced by a special hit producer in Geant4 and GeantV applications

#### PR validation:

Tested with privately produced files with GeantV application

#### if this PR is a backport please specify the original PR:

tested with 2018 geometry configuration and no back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda fine for me to integrate this tool, still it looks like a Validation package, just based on bare ROOT instead of ME...

**Comment by bsunanda** [comment]
@fabiocos This is specially used for comparing Geant4 and GeantV results. So it is not a standard validation tool and that is why didn't use MonitorElement. Kindly integrate this

**Comment by fabiocos** [comment]
+1

**Pull request merged**
