### PR TITLE
[Backport to 133X] Adding Two Secondary Datasets for JME POG

### PR DESCRIPTION
**Pull request by jordan-martins**
Hi,

Backport of #43538 43534

Thanks,
Jordan

### CODE REVIEW

**Comment by jordan-martins** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43534

**Comment by jordan-martins** [comment]
Ciao @AdrianoDee, please check if it is the way. Thanks, Jordan :)

**Comment by AdrianoDee** [comment]
> Ciao @AdrianoDee, please check if it is the way. Thanks, Jordan :)

Perfect thanks (:

**Comment by rappoccio** [comment]
+1

**Pull request merged**
