### PR TITLE
Phase2-hgx333E Remove reference of V15 from Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference of V15 from Geometry/HGCalCommonData

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Clean up PR for V15 HGCal.

**Comment by perrotta** [comment]
+1

**Pull request merged**
