### PR TITLE
Clean BuildFiles in GeneratorInterface

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/30679).

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by silviodonato** [comment]
@guitargeek there is a conflict

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/generators-l2 any objections?

**Comment by guitargeek** [comment]
Hi @alberto-sanchez, @qliphy, are these changes fine for you? This PR is just touching BuildFiles.

**Comment by qliphy** [comment]
+generators

**Comment by silviodonato** [comment]
merge

**Pull request merged**
