### PR TITLE
Use correct accessors for RegionalMuonShower data type

### LINKED ISSUE #36433: Master (next IB) is broken (two inconsistent PR were merged independently)
Somehow the master is broken due to DQM/L1TMonitor #36396 which, in its own PR was fine. BUT not with #35627 .
Please revert one of the two.

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This is a cleanup PR after #36435 was used to fix #36433. Here I remove the (re)added accessors and modify both the DQM and L1TNtuple code that still used them. There should be no functional difference.

#### PR validation:

Ran `scram build code-checks && scram build code-format`, but skipped `runTheMatrix.py -l limited -i all --ibeos` as the code change is minor.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
+1
- It follows from a discussion originally in #36435

**Pull request merged**
