### PR TITLE
Added new histograms and changed z-window width for the vertex search

### PR DESCRIPTION
**Pull request by dinardo**
- I've added three new histograms to monitor the "gaussianity" of the vertex x, y, z distributions.
- I changed the z-window width for the vertex search because the z distribution of the vertex z-position had sharp cuts both on the left and on right-hand sides.

Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
I was wondering whether this PR can move forward.
I would like to avoid to the re-base it in the future.
Many thanks,
- Mauro.

**Comment by dinardo** [comment]
I was wondering whether this PR can move forward.
I would like to avoid to the re-base it in the future.
Many thanks,

- Mauro.

**Comment by dmitrijus** [comment]
This PR is to 9_2_X branch. Unless it is merged into the master first, this will not get merged.

**Comment by dinardo** [comment]
This PR corresponds to: PR# 19758 and PR# 19763 to CMSSW_9_3_X
- Mauro.

**Comment by dinardo** [comment]
Dear Experts,
can you please tell me what shall I do with this PR ?
Shall I close it ?
Many thanks,
- Mauro.

**Comment by dinardo** [comment]
Many thanks for your kind reply.
I'll close this PR.
Regards,
- Mauro.

**Pull request closed without merging**
