### PR TITLE
Removed inappropriate use of SerialTaskQueue from ClusterShapeLazyGetter

### PR DESCRIPTION
**Pull request by Dr15Jones**
A SerialTaskQueue was added to ClusterShapeLazyGetter in an attempt
to make it thread safe. Unfortunately, the implementation was not safe
since the internals of SiPixelClusterShapeCache could be changed
while another thread was reading the data outside of the queue.
In addition, performance measurements done using VTune showed
the fequent calls to SerialTaskQueue were causing a heavy CPU load
when run with 8 threads.
The thread safety of SiPixelClusterShapeCache will have to be handled
in a different way in the future once we start using more than one
thread per Event.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
@Dr15Jones:
Is there a "not" missing from the description? Please revise it.
"Unfortunately, the implementation was safe"

**Comment by cvuosalo** [comment]
+1

For #11562 5cbb937df912c6ccde0f48e49e771ab0e00ab800

Reversing an attempt to make SiPixelClusterShapeCacheProducer thread-safe, because the attempt didn't really work and had a performance cost. Some other approach will have to be used. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11562/8491/summary.html) against baseline CMSSW_7_6_X_2015-09-29-1100 show no significant differences, as expected.

**Comment by Dr15Jones** [comment]
Missing not added

**Comment by davidlange6** [comment]
+1

**Pull request merged**
