### PR TITLE
EGamma NanoAOD: Backport of removal of Fall17v1 variables from electron Table

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #33701. Additional condition to preserve nano v8 feature has been added on top of what was there in 33701. 
#### PR validation:
Validated with wf - 
- 136.8523: nanov9 wf - the Fall17V1 branches are dropped 
- 136.8522: nanov8 wf - the  Fall17V1 branches are kept.

cc @jainshilpi @mariadalfonso @gouskos

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

changes inline with master, run2_nanoAOD_106Xv1 uncharged for the "v8 nano"

**Comment by silviodonato** [comment]
@mariadalfonso I see there are changes in 136.8523 and 10824.0 . Are they ok?

**Comment by sroychow** [comment]
@silviodonato 136.9523 is the nanoV9 workflow. So we should expect changes. The Fall17v1 variables are dropped from the electron table.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
