### PR TITLE
Update HiggsMonitoring_cff.py

### PR DESCRIPTION
**Pull request by kauraman02**
**PR description:**
This PR contains updates for Run3, small fixes to the trigger DQM codes for the Dileptonic and TriLeptonic paths within Higgs Monitoring module.

[Slide 38,39](https://indico.cern.ch/event/1196192/contributions/5037333/attachments/2505075/4304046/20220908_HIG_Trigger_performance_summary.pdf)

**PR validation:**

Successful tests:

- CMSSW_12_4_0: Test performed with 100 events from the TTbar sample, in which folders/histograms were correctly produced and filled with events:

    followed the instruction from twiki : [HLTValidationAndDQM](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTValidationAndDQM#Testing_Run_3_work_in_progress)

- Basic tests:

    scram b distclean
    git cms-checkdeps -a -A
    scram b -j 8
    scram b runtests
    scram build code-checks
    scram build code-format
    runTheMatrix.py -l 11634.0

**If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:**

No backport

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type bug

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
