### PR TITLE
Renamed new methods in PoolDBOutputService

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

The new methods - recently introduced - for writing, creating, appending IOVs supporting Payload objects by reference, have been renamed, to clearly distinguish them from the corresponding, existing methods taking pointers as input parameters.

The aim is avoid template instantiation with unintended types.
#### PR validation:

Unit and integration tests

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Review by jpata — COMMENTED** [review]
+reconstruction
- technical, minimal for reco
  - createNewIOV->createOneIOV in RecoHI/JiJetAlgos/UETableProducer
- no reco changes expected/observed

**Comment by perrotta** [comment]
+1
- Technical
- I take for good the "+reconstruction" in https://github.com/cms-sw/cmssw/pull/35556#pullrequestreview-775555292, even if bot did not react (yet?) by swithing the status to "reconstruction-approved"

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35556	9446aac 
- code changes are technical for reco, following the renaming of the interface in CondCore
- jenkins tests pass

**Comment by smuzaffar** [comment]
@slava77 , @jpata comment was not a normal comment that is why bot did not see it. It was a review comment which bot is not monitoring

**Pull request merged**
