### PR TITLE
small fix to integrationTests

### PR DESCRIPTION
**Pull request by Sam-Harper**
Co-authored-by: Marino Missiroli 

#### PR description:

This is a  small fix to the hltIntegrationTests as spotted by Marino in https://github.com/cms-sw/cmssw/pull/36051

https://github.com/cms-sw/cmssw/pull/35987 had already merged so this is just a PR on top of that

### CODE REVIEW

**Comment by missirol** [comment]
please test

thanks, Sam!

**Comment by missirol** [comment]
please abort

another PR is needed to fix unrelated issues with some of the PR tests..

**Comment by missirol** [comment]
please test with #36021

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
+hlt

 - this PR is a follow-up to #35987 (fixes a small mistake in the latter PR); these updates only have to do with some of the scripts for HLT development and testing; no 'central' workflow is affected

 - the label `requires-external` should be ignored (another PR was required for testing due to unrelated reasons)

**Comment by perrotta** [comment]
+1

**Pull request merged**
