### PR TITLE
Step 3: Simulation Clang tidy code-checks-all

### PR DESCRIPTION
**Pull request by ianna**
* Split #20511 as suggested by @civanch here #20511 (comment)

Step 3. SimGeneral

* This PR is based on https://github.com/cms-sw/cmssw/pull/20527, https://github.com/cms-sw/cmssw/pull/20525, #20524, #20514
It will be rebased if needed after they are subsequently merged.

@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
@civanch - there are no conflicts after step 2 is merged, this PR can also go in an IB

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - would you like me to retrigger tests?

**Pull request closed without merging**
