### PR TITLE
Send printouts to stderr, not stdout

### PR DESCRIPTION
**Pull request by rovere**
Usually, those printouts are in the way while using, e.g., ```edmConfigDump```. Sending them to the standard error allows to have a working and clean python.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
Trivial update, no hidden issues spot by jenkins tests

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
dev/null is even better:)

**Pull request merged**
