### PR TITLE
Fix failing test on ARM by rounding small values to 0

### PR DESCRIPTION
**Pull request by cvuosalo**
Certain units tests are failing on the ARM architecture because tiny floating-point values near 0 are slightly different than on the standard CPU, as described in issue #29036.

To fix this problem, the printed values used for comparison will be rounded to 0 if they are less than 1e-7. The internal values will not be changed, only the printed values used to compare the test results and the baseline reference file, which is being updated.

This change means the DT Geometry unit test will be less sensitive to small differences in norm vector values near zero, which could possibly mean it might miss a real problem, but the current test is too sensitive in failing because of 1e-16 fluctuations. I think the version of the test in this PR is sufficiently sensitive to catch real errors while avoiding false positives.

This PR adds a new utility file `Rounding.h`. I looked to see if a function to round values near 0 already exists, but I couldn't find one, so I added this new file. If there is already such a rounding function, or if I put the new file in the wrong place, this PR can be revised.

#### PR validation:

The unit test should now be platform-independent. I hope this PR can be tested against the ARM IB because I have not be able to test the code change on an ARM machine.

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cvuosalo please, remove `Geometry/DTGeometryBuilder/test/dtGeometry.log.org` from this PR and generate it for testing on the fly in a temporary test area.

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
please test for slc7_aarch64_gcc820

**Comment by ianna** [comment]
+1

**Comment by cvuosalo** [comment]
@ianna It looks like you changed your mind about generating the reference file on-the-fly. Could you please delete your comment about it, or add a comment saying so? I wouldn't want any reviewers to be confused.

**Comment by ianna** [comment]
@cvuosalo - IMHO, the reference file should be generated on the fly, but ultimately, it's your decision how high this is on the priority list.

**Comment by cvuosalo** [comment]
type bugfix

**Comment by cvuosalo** [comment]
@ianna I will leave the PR as it is for now. I think on-the-fly generation of the reference file is lower priority than other issues I need to work on.

**Comment by perrotta** [comment]
+1
- A new function is added ti DataFormats/Math to round up to zero small values (default below 10-7)
- That function is used in some DT Geometry unit tests, whose reference file I'd let the Geometry conveners to decide whether has to be generated on the fly, or not
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
