### PR TITLE
Phase2-hgx197 Test geometry for HFNose and also TB setups

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Test geometry loaded for HFNose and also dumping of TB geometry

#### PR validation:

Some tests are added and would not affect any workflow

#### if this PR is a backport please specify the original PR:

No relation to back porting

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
