### PR TITLE
DQM for 2016 pPb Flow HLT

### PR DESCRIPTION
**Pull request by zc11**
This PR is for HLT DQM for 2016 pPb run for HI Flow group

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by zc11** [comment]
I believe the test should not be running on a HI sample since it has different eventcontent. Thanks.

**Comment by zc11** [comment]
Fix has been made for the offlineprimaryvertex issue

**Comment by dmitrijus** [comment]
+1

**Comment by silviodonato** [comment]
@zc11, did you open a PR for 81X?

**Comment by zc11** [comment]
@silviodonato, yes, [here](https://github.com/cms-sw/cmssw/pull/15678). PR# also provided in [JIRA](https://its.cern.ch/jira/browse/CMSHLT-1000).

**Comment by zc11** [comment]
Modification of DQM following STEAM suggestion

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@zc11 ,  do you have the PR for 81X?
@dmitrijus , just a reminder that everything is in place for this PR.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
backport of these two pull requests: https://github.com/cms-sw/cmssw/pull/15678 + https://github.com/cms-sw/cmssw/pull/15721

**Comment by davidlange6** [comment]
+1

**Pull request merged**
