### PR TITLE
cppcheck: some fixes for 4 modules

### PR DESCRIPTION
**Pull request by serval2412**
I focused on "Prefer prefix ++/-- operators for non-primitive types"
Since I haven't found any makefile to build, I only visually checked, hope it's ok

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@cmsbuild please test

**Comment by serval2412** [comment]
How to take a look to the logs without registering to CERN?

**Comment by davidlt** [comment]
@serval2412 the failures are unrelated to the changes in this PR. The integration build on top of which it [this PR] was tested is broken.

**Comment by serval2412** [comment]
davidlt: thank you for your feedback, I thought I had missed something again. Hope it'll be quickly merged :-) There's still lots of reports! :-)

**Comment by davidlt** [comment]
The software is open source and our repositories are also public, thus technically you can install it and do compilation tests.

**Comment by serval2412** [comment]
Reading http://cms-sw.github.io/build-release.html, it's very different from soft like LibreOffice, Gimp and others. I'm more accustomed to something straightforward like:
git clone <project>
./autogen.sh or ./configure
make

**Comment by serval2412** [comment]
Also, I know very few about git but if adding upstream then fetch upstream is ok, merge gives this:
merge: upstream/master - not something we can merge
I suppose there's a reason and so a solution, but it's a pity to search in docs whereas this simple way works in other projects.

**Comment by davidlt** [comment]
The above instructions are for packaging and doing a full build. There is a simpler options, but would require a VM with RHEL/Scientific Linux/CentOS 6 or 7. We have our own package and source management system (SCRAM), which generates Makefiles for all CMSSW packages before compiling. Once you install a release it's more-or-less straight forward to compile.

**Comment by mmusich** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Pull request merged**
