### PR TITLE
Fix required by the L1T O2O.

### PR DESCRIPTION
**Pull request by ggovi**
Added explicit start of Transaction. The commit can be done with the postEndJob. Otherwise, the transaction will be rolled back.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@mmusich @diguida ping!

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
