### PR TITLE
Fix MeasurementTrackerEvent configuration of some TrackingRegionProducers

### PR DESCRIPTION
**Pull request by makortel**
This PR addresses the segfault reported in https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1562.html
and supersedes the first attempt #11155.

These TrackingRegionProducers have inconsistent default configuration for the use of MeasurementTrackerEvent. They set the usage mode to `kForSiStrips`, but do not read MTE, leading to a segfault if anybody uses these for strip hits (the case in the HN thread). In all current uses in the release, the default configuration is used only for pixel hits (i.e. MTE is not used).

Following the FIXME items added in #3105, the parameters `howToUseMeasurementTracker`/`whereToUseMeasurementTracker` and `measurementTrackerName` are made mandatory (latter only if the former is not `kNever`), and their types are changed to `string` and `InputTag`, respectively. The default mode is kept as `kForSiStrips` and the `measurementTrackerName` is set to some value (so in the HN case the user would get ProductNotFound exception in case of error instead of segfault), except for TrackingRegionsFromBeamSpotAndL2Tau, whose default mode is changed to `kNever` (there was only one use in the release, and it was clearly pixel-only, so this way we can avoid guessing the proper value for `measurementTrackerName`).

All uses of these TrackingRegionProducers are supposed to be migrated to the new configuration (i.e something missing is an error).

Tested in CMSSW_7_6_X_2015-09-06-2300 (with full matrix), no changes expected in results.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

- no objections against the changes in the FastSim code
- no impact on FastSim comparisons

**Comment by cvuosalo** [comment]
+1

For #11183 74b13f26bc253367749c51f4d3a1195ff1b8098f

Fixing a segmentation fault by changing the MeasurementTrackerEvent configuration of some TrackingRegionProducers. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11183/7955/summary.html) against baseline CMSSW_7_6_X_2015-09-07-2300  show no significant differences, as expected.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
