### PR TITLE
Implement mkFit customization in initialStep with a Modifier

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

As found in https://github.com/cms-sw/cmssw/pull/28678#issuecomment-574375403 the customize function turned out to be too fragile. 

#### PR validation:

Workflow 11634.7 runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test workflow 11634.7

**Comment by silviodonato** [comment]
+operations

**Comment by perrotta** [comment]
+1
- It reproduces with a Modifier what was previously coded with a customization
- This fixes the issue obsereved in the IB since the integration of #28678, and now wf 11634.7 is set up correctly and can run to conclusion
- Jenkins tests pass

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge
(@kpedro88 please have a look)

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
