### PR TITLE
Update tracking MC validation scripts

### PR DESCRIPTION
**Pull request by makortel**
This PR updates the campaign information to the latest 10_0_0_pre3 for tracking MC validation scripts. I'm making a PR (already) now as part of transferring the validation task to @hajohajo.

Tested in 10_0_0_pre3, no changes expected.

@VinInn @hajohajo

### CODE REVIEW

**Comment by makortel** [comment]
I'll make a small update shortly, closing in the mean time (I'd like to avoid a second PR).

**Comment by makortel** [comment]
@cmsbuild, please test

Did the update (by squashing to the last commit)

**Comment by dmitrijus** [comment]
+1

**Comment by makortel** [comment]
Could this PR be merged?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
