### PR TITLE
Hgcal v6 hesci geometry modif

### PR DESCRIPTION
**Pull request by vandreev11**
@bsunanda, @pfs, @lgray To modify HGCAL V6 HEscintillator dimensions to be in agreement with TC drawings, on top of  V6 HEsilicon geometry modification

### CODE REVIEW

**Comment by ktf** [comment]
please test

**Comment by pfs** [comment]
@vandreev11 Just to confirm : HEsil is the HErebuild version introduced by @bsunanda?

**Comment by vandreev11** [comment]
@pfs Yes, it is V6 HEsil, means HErebuild introduced by @bsunanda.

**Comment by vandreev11** [comment]
@pfs, @bsunanda Once more, to be precise. It is V6 HEsci as HErebuild, while V6 HEsil is modified V5 HEsil to have flat end for cooling manifolds. Two subdetectors have been modified.

**Comment by mark-grimes** [comment]
Is Geometry/HcalCommonData/data/PhaseII/HGCal/hcalendcapalgo.xml only used by V6?

**Comment by vandreev11** [comment]
@mark-grimes Yes, it is.

**Comment by mark-grimes** [comment]
merge

**Pull request merged**
