### PR TITLE
Run3-alca157 New analyzer for studying forward muons using tracker and calo information

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Analyzer to study forward muons with no muon information but utilizing tracker and calorimeter information

#### PR validation:

Tested privately using low luminosity data and MC samples

#### if this PR is a backport please specify the original PR:

No back porting required

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@bsunanda the code is practically not tested in this PR check, I understand you tested it privately. This is not supposed to enter into production configurations, am I correct?

@christopheralanwest @pohsun any comment?

**Comment by bsunanda** [comment]
@fabiocos Yes it is only with my private test. They will be used for calibrating HCAL with muons

**Comment by bsunanda** [comment]
@christopheralanwest @pohsun Please approve

**Comment by fabiocos** [comment]
@christopheralanwest @pohsun unless you have some objection I would like to move forward with this PR

**Comment by tlampen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
