### PR TITLE
Migration of HLT to stage-2 L1T (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to stage-2 L1T (80X)
Backport of https://github.com/cms-sw/cmssw/pull/13701
Same caveats as posted there apply, and in addition this PR would need prior integration of
https://github.com/cms-sw/cmssw/pull/13558 # HLTrigger/Egamma RecoEgamma/EgammaHLTProducers
https://github.com/cms-sw/cmssw/pull/13572 # stage-2 L1 for muon modules
https://github.com/cms-sw/cmssw/pull/13596 # Hcal Iso Track migration
https://github.com/cms-sw/cmssw/pull/13621 # HLTL1TSeed extra SaveTags removal and fillDescriptions update
https://github.com/cms-sw/cmssw/pull/13702 # HLTL1TSeed update 80X
(these 5 PRs are NOT included here - but they are now integrated in 80X).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Jenkins error will disappear when #13740 is included!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones, @boudoul, @franzoni, @hengne, @mulhearn
Please review and sign - this is the backport of #13701 already signed.

**Comment by hengne** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mulhearn @Dr15Jones  
please sign.

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mulhearn  @rekovic 
Can you please sign this PR for L1?
Thanks!

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Closing as being superseeded by #13862

**Pull request closed without merging**
