### PR TITLE
Clean BuildFiles in DetectorDescription

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/31590).

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by ianna** [comment]
@guitargeek - Thanks! The changes for DD and Geometry look good to me :-)

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by guitargeek** [comment]
The bot is asleep?

**Comment by makortel** [comment]
The bot is waiting for @cms-sw/analysis-l2 to sign

**Comment by makortel** [comment]
Wait no, explicit `merge` should merge, nevermind.

**Comment by santocch** [comment]
+1

**Pull request merged**
