### PR TITLE
Phase2-hgx336A Correct the nonzzero cassette shift scenario for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the nonzero cassette shift scenario for HGCal. This PR only enhances the testing of nonzero case.

#### PR validation:

Tested using scripts in Validation/HGCalValidation

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
