### PR TITLE
Flavor bugfix in jetTools.py (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #11501

**Update (Oct. 1, 2015):** Included backport of #11612

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
@monttj, could you please sign this PR. Thanks

**Comment by ferencek** [comment]
Now that there are no active MiniAOD campaigns in 74X, I suggest this PR gets merged.

**Comment by slava77** [comment]
@ferencek MC requests are still coming and being processed (so far with older release);
there is also a 0T reprocessing campaign about to start.
So, 74X is still pretty active.

**Comment by slava77** [comment]
@cmsbuild please test
(at least to have a record of the tests results)

**Comment by ferencek** [comment]
@slava77, thanks for the info. MC requests should be unaffected but MiniAOD for 0T reprocessing, on the other hand, would be affected. So I guess it is best to wait until all MiniAOD campaigns are completed.

**Comment by slava77** [comment]
sorry, 0T is in 76X.
MC injections are still ongoing though.

**Comment by slava77** [comment]
I think further plans for 74X can be discussed in the ORP (no more changes is still an easier choice).
IMO, if we let changes to happen, it will be more than just this PR.

**Comment by ferencek** [comment]
In that case, there is no problem with merging this PR since the only data tier it affects is MiniAOD. This and possibly other 74X PR would still be useful for some analysis-level work until a complete migration to 76X is made.

**Comment by ferencek** [comment]
No longer relevant after 76X re-reco. Closing

**Pull request closed without merging**
