### PR TITLE
Improve `Phase2TrackerMonitorDigi`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

PR in response to https://github.com/cms-sw/cmssw/issues/46510
 
Improve `Phase2TrackerMonitorDigi`
- merge header file in the plugin implementation
- const correctness of input parameter
- `LogInfo` -> `LogDebug` (to avoid large amount of allocations)

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type performance-improvements

**Comment by mmusich** [comment]
@emiglior @suchandradutta @henriettepetersen FYI

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
