### PR TITLE
Sign change for translations in the Geometry Comparison Tool

### PR DESCRIPTION
**Pull request by cardinia**
@hroskes @connorpa  as requested I'm tagging you to this commit

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@cardinia @lpernie sorry, where was this discussed and tested, for my information? The PR tests look insensitive to it

**Comment by lpernie** [comment]
I let @cardinia and @connorpa  comment more  on that.

**Comment by fabiocos** [comment]
hold

pending a clarification from authors and/or AlCa

**Comment by mmusich** [comment]
@fabiocos, this change affects exclusively code used for Tracker Alignment internal validations. Is not part of any test suite used in PR tests and doesn't affect any central workflow.
I think it was internally tested by the alignment people: [link to presentation](https://indico.cern.ch/event/688868/contributions/3062651/attachments/1679731/2698146/GCtool.pdf)

**Comment by fabiocos** [comment]
unhold

@mmusich thank you for the clarification

**Comment by fabiocos** [comment]
+1

**Comment by hroskes** [comment]
Thanks @mmusich for stepping in!  Yes, this is just to reverse the y axis on plots.  This has been a source of confusion to us for several years.  I think this is the 4th time we've flipped the sign.  It's correct now.

@fabiocos - what's the recommended procedure for testing in CMSSW?  Obviously we have to test things before committing them, but are there formal guidelines for putting everything into the unit tests?

**Comment by fabiocos** [comment]
@hroskes you may check https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDevelopersGuide for the suggestions about unit tests. If it is possible to have them in a simple way it sounds useful. In general, if some piece of code is not affecting regular production workflows, it is advisable to clarify whether any kind of standalone test was done and whether it was documented in some way.

**Comment by hroskes** [comment]
@fabiocos Thanks!  We'll keep it in mind.

**Pull request merged**
