### PR TITLE
updated path to EDM file for TSG tests on Run-3 Data [`12_2_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #37283

#### PR description:

Partial backport of #37283. With respect to the original PR, this backport includes only the fix to the path of the EDM file used for TSG tests on Run-3 Data.

#### PR validation:

Relies on the tests done for the original PR.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37283

This partial backport is needed to fix a problem with file access in the "HLT-Validation" tests of the IBs.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

This is meant to fix the failure of the "HLT-Validation" tests in recent 12_2_X IBs, e.g. [`CMSSW_12_2_X_2022-03-20-0000`](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_2_X_2022-03-20-0000/slc7_amd64_gcc900/RelVal_L1RePack_GRun_DATA.log).

**Comment by missirol** [comment]
+hlt

Signing in advance. This file does not get tested in PR tests, and the signature should anyway trigger the tests (I want to check if it does).

**Comment by Martin-Grunewald** [comment]
This stil does not work for me, presumably because I need grid access to run this as the file is not at cern.

This may be a performance problem, and so far I did not need to set up grid access to run the TSG tests.
Unfortunatley, running ```voms-proxy-init -voms cms -rfc``` gves me:
```voms-proxy-init: Command not found.```

**Comment by missirol** [comment]
Should we then simply keep this EDM file in the TSG area on EOS?

**Comment by Martin-Grunewald** [comment]
Yes, that would be better indeed! Sorry for going back to your original.

**Comment by Martin-Grunewald** [comment]
Then actually we should update the addOnHLT tests to use the eos location as well.

**Comment by missirol** [comment]
Okay, will do (in both/all PRs).

**Comment by missirol** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need a 12_3 PR as well...

**Comment by missirol** [comment]
For `12_3_X` we need a full backport of #37283, and I first wanted to see if there were changes needed to the latter. I'm planning to open the `12_3_X` backport today.

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
please test

> Then actually we should update the addOnHLT tests to use the eos location as well.

I had forgotten the update of the file-path in the `addOnTests`. Will propagate that to the PRs in `12_3_X` and `12_4_X`.

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
