### PR TITLE
Remove unused variable use_preshower from PFECALSuperClusterProducer

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

The variable `use_preshower` in `PFECALSuperClusterProducer.cc` is not used anywhere, but just creates confusion. It seems like setting it to true/false would lead to using/not using preshower energy for superclustering; while that is not the case. This variable has no effect anywhere and should just be removed to avoid further confusion.

This PR is just meant for code cleanup. No change in physics is expected.

#### PR validation:
`cmsDriver.py --filein /store/relval/CMSSW_12_4_0_pre3/RelValZpToEE_m6000_14TeV/GEN-SIM-DIGI-RAW/123X_mcRun3_2021_realistic_v14-v1/2580000/42d345d9-79a2-4006-8d6b-b4241a553f42.root  --fileout file:AOD.root --mc --eventcontent AODSIM --runUnscheduled --customise Configuration/DataProcessing/Utils.addMonitoring --datatier AODSIM --conditions 123X_mcRun3_2021_realistic_v14  --step RAW2DIGI,RECO --geometry DB:Extended --era Run3 --python_filename aod_cfg.py --beamspot Run3RoundOptics25ns13TeVLowSigmaZ --no_exec -n 200`
then 
`cmsRun aod_cfg.py`
It ran fine.

This PR is not a backport. 
Backport not necessary.

### CODE REVIEW

**Comment by missirol** [comment]
@swagata87, thanks for the cleanup.

We also need to add a customisation for the Phase-1 HLT menus, e.g.
```diff
diff --git a/HLTrigger/Configuration/python/customizeHLTforCMSSW.py b/HLTrigger/Configuration/python/customizeHLTforCMSSW.py
index 23820895fc2..72e70bc3651 100644
--- a/HLTrigger/Configuration/python/customizeHLTforCMSSW.py
+++ b/HLTrigger/Configuration/python/customizeHLTforCMSSW.py
@@ -172,6 +172,16 @@ def customiseFor37231(process):
 
     return process
 
+def customiseFor37756(process):
+    """https://github.com/cms-sw/cmssw/pull/37756
+    Removal of use_preshower parameter from PFECALSuperClusterProducer
+    """
+    for prod in producers_by_type(process, 'PFECALSuperClusterProducer'):
+        if hasattr(prod, 'use_preshower'):
+            delattr(prod, 'use_preshower')
+
+    return process
+
 
 def customiseForOffline(process):
 #   https://its.cern.ch/jira/browse/CMSHLT-2271
@@ -192,5 +202,6 @@ def customizeHLTforCMSSW(process, menuType="GRun"):
     # process = customiseFor12718(process)
 
     process = customiseFor37231(process)
+    process = customiseFor37756(process)
 
     return process
```

**Comment by swagata87** [comment]
thanks Marino. I will include it soon.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
#37646 is already fully signed, and might get merged before this PR. Since both modify `customizeHLTforCMSSW` in a similar way, this PR will likely run into a merge-conflict if #37646 is merged first, and will thus need to be rebased.

**Comment by missirol** [comment]
> This branch has conflicts that must be resolved

Unfortunately, we now have a merge-conflict, as expected after the integration of #37646.

@swagata87 , this PR should be rebased on `CMSSW_12_4_X_2022-05-03-2300`, or later IBs (you can just cherry-pick the commits and fix the conflicts manually, I think).

**Comment by swagata87** [comment]
Thanks Marino, I rebased on `CMSSW_12_4_X_2022-05-03-2300`

**Comment by perrotta** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
