### PR TITLE
eg hlt filter threshold reduction to 15 \GeV from 20\GeV

### PR DESCRIPTION
**Pull request by Soumyatifr**
This is backport PR to CMSSW_13_0_X.
It is already merged in master  branch: PR: 40909

Adding @swagata87 @lfinco & @swertz .

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by swertz** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40909

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
