### PR TITLE
HLT menu migration to 11_2_0_pre11 template

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu migration to 11_2_0_pre11 template
Based on CMSSW_11_2_0_pre11

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
@Martin-Grunewald do you have the PR for the master branch too?

**Comment by Martin-Grunewald** [comment]
@silviodonato 
This PR does not apply to the 113x master as it has diverged already. There will be one to migrate the menus to 1130pre1 for 113x.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
