### PR TITLE
Added mayConsume to SiStripESProducers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Now that mayConsume exists, this finishes the migration to consumes for this package.
Also added fillDescriptions.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Part of #26748.

**Comment by fabiocos** [comment]
@christopheralanwest @pohsun please have a look, this is a technical update

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
