### PR TITLE
Calo l1 last20 mismatches axis fix

### PR DESCRIPTION
**Pull request by aloeliger**
#### PR description:

This PR modifies the function of the last20Mismatches monitoring element to not include duplicate event mismatch reports on the Y-axis, instead just updating the types of mismatches seen for a given combination of Run, Lumi, and Event. As well, empty Y-axis labels are now simply given their corresponding bin number, to prevent empty string labels causing issues as seen before in #32250. This PR fixes the issue first spotted on this hypernews thread: https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2192.html

#### PR validation:

All code compiles, and produces expected plots as seen when using `runTheMatrix.py`. Using @silviodonato 's method to test the DQM merging step, this code eliminates the merging error seen.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport. However, it does need to be forward port-ed to 11_3_X and master.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by aloeliger** [comment]
Hello all, I have opened the PR for the fix we discussed in the hypernews thread here, however, it was mentioned that a forwardport to master (11_3_X) needs to be opened as well. I looked at opening a pull request to master, however, it was trying to merge ~76 commits that were not mine there and it would not have allowed it to automatically merge as well. I am afraid I don't know the exact process then for just opening a forward port of this specific set of commits to the master branch. How can I do that?

**Comment by silviodonato** [comment]
urgent
for the MWGR

**Comment by silviodonato** [comment]
@aloeliger  you can follow these recipes https://cms-sw.github.io/tutorial-resolve-conflicts.html
(the latest release is CMSSW_11_3_X_2021-02-03-2300).

Since you PR is rather easy, perhaps it is quicker to redo the same PR starting from scratch in CMSSW_11_3_X.

**Comment by davidlange6** [comment]
out of curiousity - why do this complex caching at all and not just fill the histogram directly?

**Comment by aloeliger** [comment]
> out of curiousity - why do this complex caching at all and not just fill the histogram directly?

@davidlange6 It is a thread/stream safety measure to be able to properly count the error values and maximum of error values across multiple streams. I think I asked about this in the original pull request that moved the module into global format (#32004) and the histogram filling is itself not thread safe enough to be able to do this.

**Comment by silviodonato** [comment]
@aloeliger please have a look at https://tinyurl.com/y4qkyw6b
image

**Comment by silviodonato** [comment]
The baseline plot is 
https://tinyurl.com/y5a8bu6u
image

The plot obtained including the PR is
https://tinyurl.com/y4qkyw6b
image

**Comment by aloeliger** [comment]
> @aloeliger please have a look at https://tinyurl.com/y4qkyw6b
> image

The axis numbering seems to functioning as intended here. There are no empty string labels, and duplicate event reporting has been removed, but it should be showing event 10 with both Et and feature bit mismatches at least. Sorry, but I need a few minutes to investigate this. This is workflow 25202.0 right?

**Comment by silviodonato** [comment]
This was 25202.0, but there are similar changes also in other workflows https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2021-02-03-2300+160888/41099/dqm-histo-comparison-summary.html

**Comment by silviodonato** [comment]
merge
we need this PR for the MWGR. 
I keep https://github.com/cms-sw/cmssw/pull/32816 open, @aloeliger please comment on that PR when you have understood the changes observed

**Comment by jfernan2** [comment]
+1
For the records: this PR is being complemented with https://github.com/cms-sw/cmssw/pull/32828

**Pull request merged**
