### PR TITLE
CMSSW_7_4_X DQM updates for AlphaT HLT paths (v2)

### PR DESCRIPTION
**Pull request by MarkBaber**
Addition of DQM monitoring to new AlphaT path, supersedes https://github.com/cms-sw/cmssw/pull/10705. 

Addition of DQM monitoring for the following HLT paths:
- HLT_PFHT200_PFAlphaT0p51_v
- HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v
- HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v
- HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v
- HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v
- HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v

Remove number of monitoring histograms

### CODE REVIEW

**Comment by danduggan** [comment]
please test
@MarkBaber, thanks for reducing this usage

**Comment by danduggan** [comment]
+1
@MarkBaber, the difference in bins is much more manageable now. See #10878 for the cleanup comment.

**Comment by MarkBaber** [comment]
https://github.com/cms-sw/cmssw/pull/10877 has been merged, can we also merge this?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
