### PR TITLE
Add combined workflow for new HGCal + MTD geometries

### PR DESCRIPTION
**Pull request by kpedro88**
This PR introduces 2023D35, which combines MTD I5 (LYSO bars along z) and HGCal C4 (v9 geometry). The corresponding Era is `Phase2C4_timing_layer_new`.

The short matrix is updated to remove the 2023D19 workflow (old timing layer) and add a new 2023D35 workflow.

attn: @fabiocos @lgray @pmeridian @rovere

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by prebello** [comment]
+1

2023D35 (27434.0) tested and approved

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+operations

the new test is correctly executed. The update to Eras is coherent with the purpose of the PR

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
