### PR TITLE
Change Herwig7Interface to be consistent with Herwig 7.2.0

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
#### PR description:

Update of Herwig 7 interface to allow update of Herwig 7.1.4->7.2.0. 

#### PR validation:

Has been tested with runTheMatrix workflow 535, and the test commands on the Herwig twiki

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5765

**Comment by qliphy** [comment]
please test workflow 511.0, 535.0 with cms-sw/cmsdist#5765

**Comment by qliphy** [comment]
@Dominic-Stafford   As you can see above "comparisons for the following workflows were not done due to missing matrix map:",  so would you please some checks locally, similar as done previously? : 
https://github.com/cms-sw/cmssw/pull/26905#issuecomment-496233771

**Comment by Dominic-Stafford** [comment]
Hi @qliphy - I have ran the above checks for CMSSW_9_3_18, _10_2_18 and _10_6_12, and they all seem to have run successfully. The comparison for runTheMatrix workflow 535 in CMSSW_10_6_12 is at: /afs/cern.ch/work/d/dstaffor/public/Herdev_10_6/validation_Herwig7.2_vs_Herwig7.1.4/Generator.html

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
this broke the gcc9 IB and also a clang PR  failed somehow.  
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_1_X_2020-04-21-2300/GeneratorInterface/Herwig7Interface

**Comment by smuzaffar** [comment]
gcc9 and cxxmodule IB failed because cmsdist changes for cms-sw/cmsdist#5765 were not forward ported. This is now fixed and should be good for next IB.

[a]
https://cmssdt.cern.ch/jenkins/job/auto-forward-port-branch/3046/console
https://cmssdt.cern.ch/jenkins/job/auto-forward-port-branch/3047/console

**Pull request merged**
