### PR TITLE
add scouting track collection (10_1_X)

### PR DESCRIPTION
**Pull request by swagata87**
These changes are meant for scouting event content only. The dimuon calo scouting HLT paths produce a track collection in order to compute track-isolation of muons, that track collection can be saved in event content, and can be used in analyses. This PR is related to  #22401, which was in 10_0_X.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
This doesn't change any existing data objects so from Core it is fine.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
