### PR TITLE
Update PhotonMonitoring for DQM

### PR DESCRIPTION
**Pull request by sudhaahuja**
Some minor changes in the DQMOffline/Trigger/python/PhotonMonitoring_cff

### CODE REVIEW

**Comment by sudhaahuja** [comment]
I see some conflicts and many other commits being added along with this PR. Do I need to rebase to some particular release ?

**Comment by kpedro88** [comment]
@sudhaahuja it looks like the base of your branch is 9_4_X, while the development branch (master) now corresponds to 10_0_x

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Martin-Grunewald** [comment]
-1
rebase needed

**Comment by perrotta** [comment]
-1

**Comment by ghellwig** [comment]
-1

**Comment by sudhaahuja** [comment]
Hi, I tried to rebase the first time to 10_0_X, it worked (see log below) but I still see conflicts here. Can you please let me know if anything else needs to be done.

log ------------------
[sudha@lxplus080 python]$ git rebase --onto official-cmssw/CMSSW_10_0_X official-cmssw/CMSSW_9_4_X EXOdqmUpdate
First, rewinding head to replay your work on top of it...
Applying: minor changes in Photon monitoring
----------------------

**Comment by kpedro88** [comment]
@sudhaahuja please read http://cms-sw.github.io/tutorial-resolve-conflicts.html

(in this case, it might just be easier to cherry-pick your commit to a new clean 10_0_X IB and then force push to overwrite this branch)

**Comment by sudhaahuja** [comment]
Sorry for the confusion but I have created a new PR directly from base branch 10_0_X (#21270). I am closing this PR.

**Pull request closed without merging**
