### PR TITLE
[Backport] HGCAL trigger updates

### PR DESCRIPTION
**Pull request by jbsauvan**
This is the backport in 93X of #21728

### CODE REVIEW

**Comment by kpedro88** [comment]
please test
@jbsauvan @rekovic this is for the L1T studies?

**Comment by kpedro88** [comment]
backport of #21728

**Comment by jbsauvan** [comment]
Hi @kpedro88 , yes this is for the L1T production and studies.

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by rekovic** [comment]
@fabiocos 
Can we please merge this in 93x. Thx

**Comment by fabiocos** [comment]
+1

**Pull request merged**
