### PR TITLE
Fed vector hf upgrade fix

### PR DESCRIPTION
**Pull request by mulhearn**
Updates the RCT producer (&DQM for RCT) for backwards compatibility for changes in HF (it should work both on data and in MC).

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
This is 74X version of #9731

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
