### PR TITLE
Remove obsolete header MultiTrajectoryStateCombiner.h

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19380	bd578f3
- technical cleanup
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
