### PR TITLE
update hltGetConfiguration for ConfDB v2 (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
hltGetConfiguration:
- send errors to stderr instead of stdout
- add support fo ConfDB v2
- move default to ConfDB v2 for online and adg

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #10181 to CMSSW 7.5.x

**Comment by fwyzard** [comment]
@Martin-Grunewald , @perrotta , I've run some tests to check that the more common commands work as intended.
Can you check that I didn't break any of the STORM workflows, and sign ?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
