### PR TITLE
New set of RelVal GT with updated conditions for Run2 MC DIGI-RECO

### PR DESCRIPTION
**Pull request by diguida**
This is the final set of GT for next pre-release: 
- Updated new conditions for Run2 MC DIGI-RECO campaign.
- Added Egamma PF Cluster corrections in all scenarios (so removed the ESPrefer in `RecoParticleFlow/PFClusterProducer/python/particleFlowClusterECAL_cfi.py`);
- Updated hadron PF calibrations for Run2 MC, and new IOV appended to the HLT and re-reco GT;
- Removed unused records for old 3x3 APE in all the GT;
- Removed unsupported SIM geometry scenarios;
- Use the correct key for HI Run2 MC (as in #7704).

### CODE REVIEW

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@slava77 Interesting result from my local tests after fixing the "offender" payload. Workflow `135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS` is the only one failing:

````
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/5818/w/tmp/BUILDROOT/5f439a1a6b48a87797e08350af41ad82/opt/cmssw/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/src/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h:83: void CaloTDigitizer<Traits>::run(CaloTDigitizer<Traits>::DigiCollection&, CLHEP::HepRandomEngine*) [with Traits = HODigitizerTraits; CaloTDigitizer<Traits>::DigiCollection = edm::SortedCollection<HODataFrame>]: Assertion `theDetIds->size() != 0' failed.
````
IIUC, the SIM step is failing...

**Comment by slava77** [comment]
I got it too.
This is fastsim .. gdb ...

```
#4  0x00007fffce8383d5 in CaloTDigitizer<HODigitizerTraits>::run(edm::SortedCollection<HODataFrame, edm::StrictWeakOrdering<HODataFrame> >&, CLHEP::HepRandomEngine*) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#5  0x00007fffce82ba16 in HcalDigitizer::finalizeEvent(edm::Event&, edm::EventSetup const&, CLHEP::HepRandomEngine*) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#6  0x00007fffce824c44 in HcalDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#7  0x00007fffce8b550b in edm::MixingModule::finalizeEvent(edm::Event&, edm::EventSetup const&) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/pluginSimGeneralMixingModulePlugins.so
#8  0x00007fffce7986eb in edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) ()


```

**Comment by diguida** [comment]
`gdb` gives me a hint:

````
#3  0x0000003ceb02b810 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffce1383d5 in CaloTDigitizer<HODigitizerTraits>::run(edm::SortedCollection<HODataFrame, edm::StrictWeakOrdering<HODataFrame> >&, CLHEP::HepRandomEngine*) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#5  0x00007fffce12ba16 in HcalDigitizer::finalizeEvent(edm::Event&, edm::EventSetup const&, CLHEP::HepRandomEngine*) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#6  0x00007fffce124c44 in HcalDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libSimCalorimetryHcalSimProducers.so
#7  0x00007fffce1b550b in edm::MixingModule::finalizeEvent(edm::Event&, edm::EventSetup const&) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/pluginSimGeneralMixingModulePlugins.so
#8  0x00007fffce25c6eb in edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) ()
   from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-02-12-0200/lib/slc6_amd64_gcc491/libMixingBase.so
````
It is a problem with HO digis.
By looking at https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc#L645 it seems that there are no `DetId`s sent to the HO digitizer, so the assertion fails. This seems related to the `HcalMCParams` used there.

**Comment by slava77** [comment]
Did it get affected by these changes:
HcalMCParamsRcd	-	HcalMCParams_v3.0_mc	HcalMCParams_v4.0_mc
HcalRecoParamsRcd	-	HcalRecoParams_v8.0_mc	HcalRecoParams_v9.0_mc
?

**Comment by slava77** [comment]
@lveldere 
This looks like a bug in fastsim: the ZEE*.py file in this workflow has
process.mix.digitizers.hcal.ho.siPMCode = 2
it should be 1 for postLS1, apparently the customization functions didn't detect this piece in fastsim.

**Comment by slava77** [comment]
... and I'm guessing the HPD payloads were removed from the updated GT records

**Comment by slava77** [comment]
notes for 
for https://github.com/cms-sw/cmssw/pull/7707	 a0cde1f
tested in CMSSW_7_4_X_2015-02-12-0200 /test area sign518/

https://cms-conddb-dev.cern.ch/browser/#diff/Prod/gts/MCRUN2_74_V5/MCRUN2_74_V7

As expected, changes are only in run2 scenario.
- physics performance varies quite a bit. At a somewhat cursory look at DQM comparisons, reco objects seem to be OK. Changes are consistent with the changes in the payloads (at least by the area): 
    - tracking: there is a moderate increase in tracking efficiency and ~5-10% reduction in the fake rate in the TTBar PU35@25ns sample; dedx scale increases by ~10-20%
    - high-et jet response is about the same as after #7692 
- technical performance is about the same, within the jitter introduced by changes/variations in the objects

- to address: 
    - comments from #7692 
    - get a fix in fastsim

**Comment by lveldere** [comment]
@slava77 

Hi Slava

I'd need a bit more info to understand what needs change in FastSim.
Can you point me to some lines in the code?

Thanks

Lukas

**Comment by diguida** [comment]
@lveldere 
As I wrote on https://github.com/cms-sw/cmssw/pull/7707#issuecomment-74149720 and https://github.com/cms-sw/cmssw/pull/7707#issuecomment-74167578 the problem is a failing assertion in `CaloTDigitizer<HODigitizerTraits>::run`, because of 0 `DetIds` from HO being available: https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h
This function is called by `HcalDigitizer::finalizeEvent`:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc#L624
So, the HO digitizer has empty `DetId`s. The initial list of HO `DetId`s is created by consuming the RECO geometry:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc#L615, but then they are set for DIGI production in `HcalDigitizer::buildHOSiPMCells`. In this function, there is a test on `theHOSiPMCode`, passed from a `PSet`:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SimCalorimetry/HcalSimProducers/src/HcalDigitizer.cc#L645
As @slava77 points out, the code is set to 2: as a consequence, both HOHPD and HOSiPM digitizers are instantiated. Also, in `HcalDigitizer::buildHOSiPMCells`, the `HcalMCParams` payload is loaded in order to get the signal shape of each DetId. Then there is a test on the signal shape. In this context, no valid `DetId`s are found, and the vector size is 0 for one of the two digitizers.
I am now checking the new payload: if the HPD DetIds are removed, this means that there is an inconsistency between FastSim configuration and the GT contents.

HTH

**Comment by davidlange6** [comment]
the issue is that there is no digitisation_step declared in the fastsim - so the customize fragments for it are missed.

**Comment by slava77** [comment]
The target is to have ho.siPMCode =1. Nothing else.
The means are to get postLs1 customs function to do it for you.  It detects
based on a presence of a name;  just add the famos sequence name containing
mix to the conditions of the customs function

**Comment by davidlange6** [comment]
i think a fix is

diff --git a/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py b/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py
index 891b7c5..5c85f22 100644
--- a/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py
+++ b/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py
@@ -19,7 +19,7 @@ def customisePostLS1_Common(process):
         process = customise_RawToDigi(process)
     if hasattr(process,'reconstruction'):
         process = customise_Reco(process)
-    if hasattr(process,'digitisation_step'):
+    if hasattr(process,'digitisation_step') or ( hasattr(process,'mix') and hasattr(process.mix,'digitizers')):
         process = customise_Digi_Common(process)
     if hasattr(process,'HLTSchedule'):
         process = customise_HLT(process)



note that with or without my fix (or the GT) we have this in fastsim..
%MSG
%MSG-w ProductNotFound:  TriggerResultsFilter:hltBtagTriggerSelection  13-Feb-2015 12:20:30 CET Run: 1 Event: 1
An exception of category 'ProductNotFound' occurred.
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: L1GlobalTriggerReadoutRecord
Looking for module label: gtDigis
Looking for productInstanceName:

**Comment by davidlange6** [comment]
ok, no this is not sufficient.. i'm not sure why

**Comment by davidlange6** [comment]
ah - interfering changes in the customize functions. looking at a fix.

**Comment by davidlange6** [comment]
i just made a new PR _ it should include this PR.. #7726

**Comment by diguida** [comment]
-1
Superseded by #7726

**Pull request closed without merging**
