### PR TITLE
Absorb CSCCommonTrigger into CSCTriggerPrimitives

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

CSCCommonTrigger contains a number of unused files: `vmac.h`, `vlib.h`, `vlib.cc`, `CSCFrontRearLUT.h` with sole function `getFRBit`. I don't see `getFRBit` in the index anywhere. `CSCPatternLUT.h` should actually be in CSCTriggerPrimitives (in `CSCPatternBank.h`). If you remove the unused files and move CSCPatternLUT you realize that this package really only contains a single python file with the MPC LCT BX accept window, which might as well be in CSCTriggerPrimitives/python. I propose to absorb CSCCommonTrigger in CSCTriggerPrimitives.

See also #31505 that mentions unused headers in CSCCommonTrigger.

#### PR validation:

Code compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
@Dr15Jones Are you ok with this proposal? I need a core member to sign off on this PR.

**Comment by makortel** [comment]
+core

Thanks for the reminder.

**Comment by dildick** [comment]
@rekovic Do you have any comments or questions?

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
There is a conflict after having merged https://github.com/cms-sw/cmssw/pull/31548. Could you solve the conflict? Please ping me as a reminder

**Comment by dildick** [comment]
@silviodonato It should be resolved. I'm compiling it now.

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
Something to do with an hgcal data file
```
----- Begin Fatal Exception 25-Sep-2020 16:53:05 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_DIGI_L1TrackTrigger_L1_DIGI2RAW_HLT.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1THGCal/data/panel_mapping_V11_decentralized_march20_2.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-24-2300/poison:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-24-2300/src:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-24-2300/external/slc7_amd64_gcc820/data:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/poison:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/src:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/external/slc7_amd64_gcc820/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/runTheMatrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal


At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Types.py(808): insertInto
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Mixins.py(373): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Types.py(889): insertContentsInto
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Types.py(882): insertInto
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Config.py(1088): _insertInto
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-09-24-2300/python/FWCore/ParameterSet/Config.py(1302): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
`L1Trigger/L1THGCal/data/panel_mapping_V11_decentralized_march20_2.txt` was pointed by https://github.com/cms-sw/cmssw/pull/31524 and added with cms-data/L1Trigger-L1THGCal#20.
Probably, the test included #31524 without including the external cms-data/L1Trigger-L1THGCal#20.
Let's try again

**Comment by silviodonato** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by silviodonato** [comment]
merge
@rekovic already signed an older version

**Pull request merged**
