### PR TITLE
Removal of hardcoded testing L1T tag and move it to GT

### LINKED ISSUE #27393: Developers overriding production location for retrieving conditions in configurations
Breaks centrally determined location for retrieving conditions (which of course can change even if it rarely does). All of these should rely on the global tag to determine from where the conditions are to be taken (or they should not be loaded into production workflows)

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/L1Trigger/L1TMuon/python/simGmtStage2Digis_cfi.py#L23

https://github.com/cms-sw/cmssw/blob/82c4a527471bca6fc4897fd4feb3f7d7fcb73928/RecoTauTag/RecoTau/python/tools/runTauIdMVA.py#L41

https://github.com/cms-sw/cmssw/blob/8587c76d0a2ee041152b0c0ac289d851a13ef247/L1Trigger/L1TCalorimeter/python/simDigis_cff.py#L49

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Instead of https://github.com/cms-sw/cmssw/pull/35554

Also resolves https://github.com/cms-sw/cmssw/issues/27393

Original description
"This PR removes part of the configuration of L1T Calo which retrieves conditions from a specific location (instead of via GT) and which is deprecated for a while (non-used since we moved away from hacking conditions)."

Extra in this PR is the addition of this tag to the GT.

For the future:
 * This tag is for testing purposes, thus it should be fed to the code via a test python cfg file and not hardcoded in the cpp code nor really read from the GT

Here is the list of diffs wrt to the queue:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_design_Queue/123X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_realistic_Queue/123X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_HeavyIon_Queue/123X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_startup_Queue/123X_mcRun2_startup_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_l1stage1_Queue/123X_mcRun2_asymptotic_l1stage1_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_design_Queue/123X_mcRun2_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_preVFP_Queue/123X_mcRun2_asymptotic_preVFP_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_Queue/123X_mcRun2_asymptotic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2cosmics_asymptotic_deco_Queue/123X_mcRun2cosmics_asymptotic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_HeavyIon_Queue/123X_mcRun2_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_pA_Queue/123X_mcRun2_pA_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun2_Queue/123X_dataRun2_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun2_HEfail_Queue/123X_dataRun2_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun2_relval_Queue/123X_dataRun2_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun2_PromptLike_HI_Queue/123X_dataRun2_PromptLike_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_Queue/123X_dataRun3_HLT_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun2_HLT_relval_Queue/123X_dataRun2_HLT_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Express_Queue/123X_dataRun3_Express_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Prompt_Queue/123X_dataRun3_Prompt_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Queue/123X_dataRun3_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017_design_Queue/123X_mc2017_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017_realistic_Queue/123X_mc2017_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017cosmics_realistic_deco_Queue/123X_mc2017cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017cosmics_realistic_peak_Queue/123X_mc2017cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_design_Queue/123X_upgrade2018_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_Queue/123X_upgrade2018_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_RD_Queue/123X_upgrade2018_realistic_RD_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_HI_Queue/123X_upgrade2018_realistic_HI_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_HEfail_Queue/123X_upgrade2018_realistic_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018cosmics_realistic_deco_Queue/123X_upgrade2018cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018cosmics_realistic_peak_Queue/123X_upgrade2018cosmics_realistic_peak_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_Queue/123X_mcRun3_2021_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_Queue/123X_mcRun3_2021_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_Queue/123X_mcRun3_2021cosmics_realistic_deco_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_Queue/123X_mcRun3_2021_realistic_HI_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_Queue/123X_mcRun3_2023_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_Queue/123X_mcRun3_2024_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun4_realistic_Queue/123X_mcRun4_realistic_v2

#### PR validation:

Previously failing addOnTest pass
```
addOnTests.py -j 8
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
@smuzaffar tests are taking more than 11 hours, is there something wrong with the bot? Thanks!

**Comment by tvami** [comment]
> @smuzaffar tests are taking more than 11 hours, is there something wrong with the bot? Thanks!

Same thing is happening in https://github.com/cms-sw/cmssw/pull/36409

**Comment by smuzaffar** [comment]
all resources to test are busy, I am afraid you have to wait.

**Comment by tvami** [comment]
> Input file file:RelVal_Raw_Fake2_DATA.root could not be opened.

I guess we should just test again? @smuzaffar

**Comment by mmusich** [comment]
> I guess we should just test again? @smuzaffar

There's a tonne of segfaults in `L1TStage2Layer2Producer:simCaloStage2Digis` (see e.g. [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d73f32/21085/runTheMatrixINPUT-results/136.721_RunHLTPhy2016B+RunHLTPhy2016B+HLTDR2_2016+RECODR2_2016reHLT_HIPM+HARVESTDR2/step2_RunHLTPhy2016B+RunHLTPhy2016B+HLTDR2_2016+RECODR2_2016reHLT_HIPM+HARVESTDR2.log)). I doubt that will go away re-testing.
FWIW, I still think the right thing to do is to add instead the payloads to GlobalTag: https://github.com/cms-sw/cmssw/pull/35554#issuecomment-947814537

**Comment by tvami** [comment]
> 
> There's a tonne of segfaults in `L1TStage2Layer2Producer:simCaloStage2Digis` (see e.g. [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d73f32/21085/runTheMatrixINPUT-results/136.721_RunHLTPhy2016B+RunHLTPhy2016B+HLTDR2_2016+RECODR2_2016reHLT_HIPM+HARVESTDR2/step2_RunHLTPhy2016B+RunHLTPhy2016B+HLTDR2_2016+RECODR2_2016reHLT_HIPM+HARVESTDR2.log)). I doubt that will go away re-testing.

But this means that the HLT menu has `m_useStaticConfig` on `True`, right? It should not be, see "use static config for fw testing"

**Comment by mmusich** [comment]
> But this means that the HLT menu has m_useStaticConfig on True, right?

I don't see what the HLT menu has anything to do with it. That's in the configuration of `L1TStage2Layer2Producer` which should be run in the L1REPACK step.

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/36423

**Comment by tvami** [comment]
@cmsbuild , please test with #36423

**Comment by tvami** [comment]
So it is needed in MC after all :( I'll provide those GTs too

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/36549

**Comment by tvami** [comment]
@cmsbuild , please test with #36549

**Comment by tvami** [comment]
+alca
 * finally we see what's expected: no changes at all

**Comment by cecilecaillol** [comment]
+l1

**Comment by tvami** [comment]
Hi @perrotta @qliphy this doesnt actually require the external PR, please feel to merge it any time. Thanks!

**Comment by perrotta** [comment]
@tvami which are the unit tests that were failing? And which is the unit test to look at in order to get assurance that the new tags are correctly picked up?

**Comment by tvami** [comment]
Hi @perrotta the unit test failure comes from outside of this PR, that is due to some geometry changes.

The orignal PR https://github.com/cms-sw/cmssw/pull/35554 has failed both the addOnTests and several RelVal workflows. By adding the condition to the GT all of that is resolved. You can be assured that it's correct by seeing that there are no diffs in the RelVal comparisons (in any of them)

Speaking of the original PR, when merging this, can you please close https://github.com/cms-sw/cmssw/pull/35554  ?

**Comment by perrotta** [comment]
@tvami I read in the PR description "This tag is for testing purposes, thus it should be fed to the code via a test python cfg file and not hardcoded in the cpp code nor really read from the GT".
I wonder where is that "python config" which can test the newly inserted tags? Or do you plan to let them unattended, and have them tested at the first occasion anyone needs them?

**Comment by tvami** [comment]
@perrotta the issue is that this "testing purposes tag" has been in CMSSW from forever... (specifically from 9_2_X) and it was read directly from the DB instead of reading it from the GT. This is not allowed, and this is what https://github.com/cms-sw/cmssw/issues/27393 is about. Now I first tried to get rid of this fully, and deleted all the code that reference the flag that switches this test tag usage on... Having very little knowledge of the L1T code, this lead to a segfault. So I went to the alternative no-op solution to feed the tag through the GT. 

As for the longer term, the L1T experts should rewrite the code so there is a test python config that ESPrefers this tag if it's really needed, or just get rid of it all if it's not needed. Then we can remove it from the GT too. So what you see in this PR is a solution to a problem that can be done from the AlCa point of view. Everything else would need the L1T experts knowledge. Since https://github.com/cms-sw/cmssw/pull/35554 has not converged in the last 2 month, I did this PR.

**Comment by perrotta** [comment]
+1
- Take conditions from the GT instead of hardcoding the tag in L1Trigger/L1TCalorimeter/python/simDigis_cff.py 
- @cms-sw/alca-l2 and  @cms-sw/l1-l2 will take care of adapting the code in order to get rid of the tag if not needed

**Pull request merged**
