### PR TITLE
Cleanup suggested by scram b code-checks

### PR DESCRIPTION
**Pull request by wddgit**
Replaced virtual with override where appropriate, use nullptr
instead of 0, and use empty instead of size.

Needed to manually fix the indentation in multiple places, the
rest of the changes were automated.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
The code-checks script missed some places that needed the same fixes in related classes in the same package so I added those by hand as well. I am presuming they were missed because they are template classes only used in tests in another package.

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by wddgit** [comment]
The unit test failure is not related to this PR.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
