### PR TITLE
Add DQM Matrix to RelVals

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Following the recent discussions on the use of DQM Matrix in Run 3 wfs (https://indico.cern.ch/event/1084340/contributions/4558962/attachments/2328015/3966321/21-10-14_News_PPD.pdf, slide 8), this PR attempts at introducing similar modifications to the existing Run 2 DQM steps, as well as preserving the current code structure. 

Any feedback/criticism is highly appreciated. The current version of this PR is meant to be treated as a draft to collect feedback. Depending on the outcome, the updates can be further propagated to the rest of the wfs.

#### PR validation:

The currently modified workflows refer to 2018A. An example of one of the updated workflows can be produced by e.g.:

runTheMatrix.py --what standard -l 136.850 -t 8 --wm init

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

not a backport

### CODE REVIEW

**Comment by kskovpen** [comment]
please test workflow 136.850

**Comment by kskovpen** [comment]
please test workflow 136.850

**Comment by kskovpen** [comment]
abort

**Comment by kskovpen** [comment]
please test workflow 136.850

**Comment by kskovpen** [comment]
assign dqm

**Comment by kskovpen** [comment]
third try is a charm
@cmsbuild please test

**Comment by kskovpen** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
wf 136.874  gets time after time different input files, but it seems this is only happening in this PR...
@smuzaffar @qliphy @perrotta any idea why?
We would like to test that wf explicitely in the Jenkins compasion

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@kskovpen apart from the particular comparison of wf 136.874, do you plan to do the same as in this PR for every RelVal wf? Thanks

**Comment by kskovpen** [comment]
please test

**Comment by jfernan2** [comment]
@kskovpen the changes in the comparison do not appear, I do not know why...
However RelMon declares removal of MEs in 136.874, which apparently you did not touch in this PR.... I am puzzled....

**Comment by kskovpen** [comment]
@jfernan2 136.874 previously had "DQM:@standardDQMFakeHLT+@miniAODDQM+@L1TEgamma", now it has "DQM:@common+@ecal+@egamma+@L1TEgamma", so things seem to work :)

**Comment by jfernan2** [comment]
OK, but in that case, shouldn't we use @commonFakeHLT  to avoid messages in logs due to non-existing menus?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-182572/20516/runTheMatrix-results/136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/step4_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM.log

Thanks

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
@jfernan2 added a new harvesting DQM configuration to be used in relval harvesting, avoiding invoking DQMMessageLoggerClient. Please let me know, if this is fine.

**Comment by jfernan2** [comment]
Hi @kskovpen 
I am sorry but I am afraid it is not fine. Why do you need that?

Let me explain the logic behind https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Configuration/python/autoDQM.py

Every entry has 3 items: first is production, second is always PostDQMOffline (needed for internal purpouses) and third one is harvesting

So, invoking DQM:@commonFakeHLT is calling first line, but HARVEST:@commonFakeHLT is calling the third one.

What you found was a typo in autoDQM.py

Please rename DQMMessageLoggerClient to DQMMessageLogger in @commonFakeHLT   instead

Thanks!

**Comment by kskovpen** [comment]
All clear - will update next.

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
@jfernan2 updated :)

**Comment by jfernan2** [comment]
Thanks @kskovpen 
Do you plan to modify any other wf or we can go ahead?
The reduction according to RelMon is patent (e.g. wf 136.874 = ~50MB less of MEs)

**Comment by kskovpen** [comment]
> Thanks @kskovpen
> Do you plan to modify any other wf or we can go ahead?
> The reduction according to RelMon is patent (e.g. wf 136.874 = ~50MB less of MEs)

Thanks @jfernan2 ! The ballpark of Run2 wfs is now updated, and the next step should be to apply a consistent schema to the upcoming Run3 processing (once available). This said, I would say that we don't plan any further Run2 updates for now.

**Comment by jfernan2** [comment]
+1

**Comment by kskovpen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR updates the DQM matrix used in relvals, as agreed between PdmV and DQM. PR test runs fine, with reduction of the histogram as expected.

**Comment by perrotta** [comment]
+1
- It results in a clean up of the DQM histograms produced, as planned
- Verified and blessed by Pdmv and DQM (among others)

**Pull request merged**
