### PR TITLE
PPS: direct simulation update A

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

Several updates to the "direct" simulation of PPS have been presented in the PPS General Meeting:
  https://indico.cern.ch/event/927936/contributions/3909004/attachments/2057769/3451230/kaspar_GM_direct_simu.pdf
This PR contains a first part of them (thus the A in the name). Others will follow once the Run3 geometry and RP layout are in place, cf. #30252.

This PR contains the following updates
  * simulation of timing RPs (diamonds)
  * the previously single 2018 profile (settings) is replaced with 3 profiles, each reflecting one position of the pixel RPs (moved vertically during TS1 and TS2)
  * the latest optical functions are used (those foreseen for the Run2 re-miniAOD), cf. https://github.com/cms-data/CalibPPS-ESProducers/pull/3

The "direct" simulation is not used in any central workflow, thus no change in these WFs is expected.

#### PR validation:

Several validation plots are available in the PPS GM talk linked in the beginning.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by tlampen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jan-kaspar** [comment]
@davidlange6, @fabiocos, @franzoni, @silviodonato: could you please check (and possibly sign off) the small change in ``Era_Run3_cff.py``? It simply replaces the inapplicable ``ctpps_2018`` (Run2) with more appropriate ``ctpps_2021``. Many thanks in advance!

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
