### PR TITLE
Run2-hcx128: adjust the depth assignments in HB for all PhaseI and PhaseII scenario

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
hi @bsunanda - is there a talk explaining the impact/motivation of this change?

**Comment by bsunanda** [comment]
@davidlange6 This is a decision of the HCAL hardware group. I do not think there was a complete study of the change using MC samples. What type of presentation you are looking for. This is a decision and transmitted to us by the Project Management team (PM, deputy PM, DPG convenors, ...)

**Comment by davidlange6** [comment]
I think you've answered the concern

**Pull request merged**
