### PR TITLE
PPS lhcInfo split: per fill and per LS PopCon (discarted)

### PR DESCRIPTION
**Pull request by JanChyczynski**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by tvami** [comment]
-1
 * until an update on the PR, let's remove it from the alca/db queues

**Comment by perrotta** [comment]
@JanChyczynski @cms-sw/ctpps-dpg-l2 this draft PR is dormient since four months, and evidently unattended: can it get closed then, to clean up the queue?

**Comment by JanChyczynski** [comment]
This feature is now submitted in a new PR:

https://github.com/cms-sw/cmssw/pull/40817

**Comment by JanChyczynski** [comment]
This feature is now submitted in a new PR:

https://github.com/cms-sw/cmssw/pull/40817

**Pull request closed without merging**
