### PR TITLE
Add GEM to muon alignment module

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

- Add GEM to AlignableMuon
- Other submodules (DB converters) will be done later 
- To test and develop muon alignment include GEM, we need to update the MuonAlignment module first

#### PR validation:

- Muon scenario builder created the GEM SQLite DB file correctly

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@ianna Do you think the changes to `GeometryAligner.h ` in this PR will slow performance unacceptably? The `applyAlignments` function is called by many of the geometry builders.

**Comment by cvuosalo** [comment]
ping @ianna Do you think the changes to GeometryAligner.h in this PR will slow performance unacceptably? There is a change from picking the element out of a sorted list to repeatedly searching the list for each desired element. The applyAlignments function is called by many of the geometry builders.

**Comment by cvuosalo** [comment]
@slava77 This PR is changing `GeometryAligner::applyAlignments` in `Geometry/CommonTopologies/interface/GeometryAligner.h`, which is used by the muon detectors, Tracker, and MTD. It is replacing sequential access to sorted elements with repeated searches through the elements (see changes to `GeometryAligner.h`. Do you think this change could cause significant performance costs?

**Comment by slava77** [comment]
enable profiling

in response to 

> @slava77 This PR is changing `GeometryAligner::applyAlignments` in `Geometry/CommonTopologies/interface/GeometryAligner.h`, which is used by the muon detectors, Tracker, and MTD. It is replacing sequential access to sorted elements with repeated searches through the elements (see changes to `GeometryAligner.h`. Do you think this change could cause significant performance costs?

**Comment by slava77** [comment]
@cmsbuild please test

to get the profiling results

**Comment by slava77** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7e5b29/9786/profiling/23434.21/RES_CPU_compare_23434.21.txt

has some fairly significant differences in the totals of track building (CkfTrackCandidates) or even seeding, but I do not see anything obvious at lower lever related to geometry in 
baseline https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-10-07-1100/slc7_amd64_gcc820/profiling/23434.21/igprofCPU_step3/self
vs this PR
https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-10-07-1100/slc7_amd64_gcc820/profiling/23434.21/PR-7e5b29/9786/igprofCPU_step3/self
So, I'm more tempted to blame the difference on timing reproducibility (e.g. due to a change on what else is running on the testing node) than on this PR.

**Comment by makortel** [comment]
Does the workflow 23434.21 apply alignments on geometry?

**Comment by makortel** [comment]
> Does the workflow 23434.21 apply alignments on geometry?

Judging from no calls to `applyAlignment()` in https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-10-07-1100/slc7_amd64_gcc820/profiling/23434.21/igprofCPU_step3/2090 I'm tempted to say "no", and if that is really the case, that profile does not answer to the question https://github.com/cms-sw/cmssw/pull/31634#issuecomment-705130652.

**Comment by hyunyong** [comment]
Indeed, this `applyAlignment ()` change is not necessary for the muonAlingment module.
Since the `applyAlignment ()` changed to get `const C* geometry`, I think the GEM geometry map is not sorted in `applyAlignment ()`.
So, we don't need to change this `applyAlignment ()` but need to make a detID sorted GEM geometry builder.
Btw, the current `applyAlignment ()` function seems to have a sorting problem potentially.

**Comment by yuanchao** [comment]
@hyunyong There are some build warnings found in the static build tests regarding the access of config data. The use of "get" method without token is deprecated. Could you follow this twiki page and modify accordingly? https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES It would be nice that other newly introduced warnings could also be fixed. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7e5b29/9786/llvm-analysis/

Thank you very much.

**Comment by hyunyong** [comment]
> @hyunyong There are some build warnings found in the static build tests regarding the access of config data. The use of "get" method without token is deprecated. Could you follow this twiki page and modify accordingly? https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES It would be nice that other newly introduced warnings could also be fixed. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7e5b29/9786/llvm-analysis/
> 
> Thank you very much.

@yuanchao I tried to understand what you point, but I can't find the exact code and line. 
could you point them?
Also, most warnings are outside the scope of this PR.
Yes, if I can fix all of them it should be good, but the time is limited.

**Comment by christopheralanwest** [comment]
> > @hyunyong There are some build warnings found in the static build tests regarding the access of config data. The use of "get" method without token is deprecated. Could you follow this twiki page and modify accordingly? https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES It would be nice that other newly introduced warnings could also be fixed. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7e5b29/9786/llvm-analysis/
> > Thank you very much.
> 
> @yuanchao I tried to understand what you point, but I can't find the exact code and line.
> could you point them?
> Also, most warnings are outside the scope of this PR.
> Yes, if I can fix all of them it should be good, but the time is limited.

The specific section of the twiki above that is relevant is https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit. So, for example, lines such as these that use the deprecated method should be migrated: https://github.com/cms-sw/cmssw/pull/31634/files#diff-3632fca8483145a39d35cfa6b6cc214f18370478ab80d01671efc2f5835601bdR140

**Comment by silviodonato** [comment]
@hyunyong what is the status of this PR?

**Comment by hyunyong** [comment]
> @hyunyong what is the status of this PR?

I'm changing the ```get``` method to ```getHandle```.
There is a bunch of ```get``` method usages, so it takes time.
Also, I'm trying to remove the ```applyAlignment()``` function changes.
It seems to need another PR for the GEM geometry.

**Comment by hyunyong** [comment]
> > > @hyunyong There are some build warnings found in the static build tests regarding the access of config data. The use of "get" method without token is deprecated. Could you follow this twiki page and modify accordingly? https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES It would be nice that other newly introduced warnings could also be fixed. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7e5b29/9786/llvm-analysis/
> > > Thank you very much.
> > 
> > 
> > @yuanchao I tried to understand what you point, but I can't find the exact code and line.
> > could you point them?
> > Also, most warnings are outside the scope of this PR.
> > Yes, if I can fix all of them it should be good, but the time is limited.
> 
> The specific section of the twiki above that is relevant is https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit. So, for example, lines such as these that use the deprecated method should be migrated: https://github.com/cms-sw/cmssw/pull/31634/files#diff-3632fca8483145a39d35cfa6b6cc214f18370478ab80d01671efc2f5835601bdR140

@christopheralanwest ,@yuanchao I tried to change the ```get``` method to use ```token```, but it is difficult to get the ```ESInputTag``` with ```esConsumes```.
Some of them are not an ED module and ```esConsumes``` is not declared.
So, I have no idea how to get the geometry label.
Do you have any suggestions?

**Comment by makortel** [comment]
> Some of them are not an ED module and `esConsumes` is not declared.

The `edm::ConsumesCollector` can be passed to the constructors of the helper objects (from the constructor of the EDModule) that can be used to collect EventSetup consumption information similar to Event Data consumption information.

Written that, for now I'd suggest to refrain from migrating code that is used by `AlignmentProducer`, because we don't yet have a mechanism for an `edm::EDLooper` to declare the ES/ED product consumption (#31745).

**Comment by silviodonato** [comment]
@hyunyong have you tried with Matti's suggestion? You can find more information here https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent and https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES

**Comment by hyunyong** [comment]
> @hyunyong have you tried with Matti's suggestion? You can find more information here https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent and https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES

Yes, I've tried to apply that suggestion, but the change propagates many other codes, and a bit tricky to fix all of them.
It seems to take more time.

**Comment by makortel** [comment]
> Yes, I've tried to apply that suggestion, but the change propagates many other codes, and a bit tricky to fix all of them.

In such case it is certainly better to do the migration in a separate PR.

(and to repeat myself, additional challenge for alignment-related code is that currently `AlignmentProducer`, or any other EDLooper,  can not be migrated)

**Comment by christopheralanwest** [comment]
please test

**Comment by hyunyong** [comment]
Since we removed ```GeometryAligner.h``` change, ```test_MuonGeometryDBConverter.sh``` has a problem (GEM geometry is not sorted by DetID).
Do we need GEM geometry PR first, or just remove the DB converter test for this PR?

**Comment by christopheralanwest** [comment]
> Since we removed `GeometryAligner.h` change, `test_MuonGeometryDBConverter.sh` has a problem (GEM geometry is not sorted by DetID).
> Do we need GEM geometry PR first, or just remove the DB converter test for this PR?

Do I understand correctly that in order to get the unit tests to pass, you will need to update the GT specified at https://github.com/cms-sw/cmssw/blob/master/Alignment/MuonAlignment/test/muonGeometryDBConverter_cfg.py#L121 with a new SIM geometry payload? If that's the case, I suppose that you will want to make the GEM geometry PR first, but that's really up to the @cms-sw/geometry-l2 experts. I don't want to remove a unit test because of a temporary inconvenience.

**Comment by cvuosalo** [comment]
@hyunyong @christopheralanwest What GEM geometry change is needed?

**Comment by hyunyong** [comment]
> @hyunyong @christopheralanwest What GEM geometry change is needed?

GEM geometry is not sorted by rawID order, so it has a problem with ```GeometryAligner::applyAlignments```

**Comment by cvuosalo** [comment]
Yes, it is fine to submit a PR that sorts the GEM geometry by rawID. Such a change should affect only GEM geometry and not other sub-detectors.

**Comment by christopheralanwest** [comment]
> Yes, it is fine to submit a PR that sorts the GEM geometry by rawID. Such a change should affect only GEM geometry and not other sub-detectors.

Will this change require an update to the SIM geometry payload in 11_3_X and would such a change be allowed for 11_2_X?

**Comment by cvuosalo** [comment]
@christopheralanwest As I understand it, there is an in-memory list of GEM geometry rawIDs. They are not sorted but `GeometryAligner::applyAlignments` expects them to be sorted to work correctly. It would seem simple to sort this list in memory. There would be no impact on the DB. But I'm only guessing here. I have suggested that a PR addressing this issue be submitted. When we see that PR, we can evaluate its impact.

**Comment by hyunyong** [comment]
> addressing this issue be submitted. When we see that PR, we can evaluate its impact.

@cvuosalo @christopheralanwest Yes, it just needs to sort in memory just before the GEM geometry builder returns the GEM geometry. So, it doesn't need any GT update.
However, I don't understand why the GEM geometry is not sorted by rawID.
The easy solution is adding a sorting function to the GEM geometry builder.

**Comment by cvuosalo** [comment]
@hyunyong 
> However, I don't understand why the GEM geometry is not sorted by rawID.
> The easy solution is adding a sorting function to the GEM geometry builder.

Wouldn't this question be one for the GEM group to answer?

@slomeo Do you have any ideas about sorting the GEM geometry?

**Comment by slomeo** [comment]
> @slomeo Do you have any ideas about sorting the GEM geometry?

@cvuosalo @hyunyong : No, I don't, probably you can ask to @bsunanda

**Comment by christopheralanwest** [comment]
> > @slomeo Do you have any ideas about sorting the GEM geometry?
> 
> @cvuosalo @hyunyong : No, I don't, probably you can ask to @bsunanda

@bsunanda I think that input from you is needed here.

**Comment by cvuosalo** [comment]
@hyunyong @bsunanda Could the two of you please coordinate about creating a PR to sort the GEM geometry by raw ID?

**Comment by hyunyong** [comment]
> @hyunyong @bsunanda Could the two of you please coordinate about creating a PR to sort the GEM geometry by raw ID?

I've tested an alignment DB file that created with an updated muon misalignment scenario builder.
It is working without any mismatched rawId problem now.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by hyunyong** [comment]
> @hyunyong The PR description says:
> We need to change the applyAlignments function at GeometryAligner.h (The geometry map and alignment container detID order is not the same even after sorting. Changed the loop; geometry map -> alignment container.)
> 
> I think this statement is no longer true. If no change in `applyAlignments` is needed, please revise the PR description.

Yes, I deleted that PR description.

**Comment by cvuosalo** [comment]
I think this PR no longer presents any issues for Geometry.

**Comment by hyunyong** [comment]
Is there more issue to merge?

**Comment by silviodonato** [comment]
> Is there more issue to merge?

@cms-sw/alca-l2

**Comment by yuanchao** [comment]
+1
As previously mentioned, getting a record from EventSetup without token is deprecated. Though many parts of the codes have been rewritten to comply. Still several parts the deprecated code remain. (iSetup.get<MuonGeometryRecord>().get(gemGeometry);) As those involve with the alignment function calls, we don't insist to complete a full migration here. Just that the migration will be needed in the future and it is up to the core software manager to enforce the migration.

**Comment by qliphy** [comment]
+1

**Pull request merged**
