### PR TITLE
[12.4.X] introduce `DiMuonMassBiasMonitor` and `DiMuonMassBiasClient` 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39148 and https://github.com/cms-sw/cmssw/pull/39128

#### PR description:

The purpose of this PR is to expand on the concept introduced at https://github.com/cms-sw/cmssw/pull/38425, about adding the DQM monitoring for the `ALCARECOTkAlDiMuonAndVertex` stream and adds a new DQM Analyzer (`DiMuonMassBiasMonitor`) to monitor the bias of the di-muon mass system as a function of the component track kinematics.
In addition it adds a client `DQMEDHarvester` to create profiles of the mass bias vs track kinematics, based on the 2D `MonitorElements` introduced.

#### PR validation:

Run the (augmented) unit tests of this package and also run manually on 2022C data obtaining the fits at this [link](http://musich.web.cern.ch/musich/display/mergedFitsData.pdf).
The resulting DQM file has been uploaded to a private GUI that is available by:

```
 ssh -NL 8060:localhost:8060 <USER>@lxplus724.cern.ch
```

and visiting:

https://tinyurl.com/2pwdox97

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/39148 and https://github.com/cms-sw/cmssw/pull/39128

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, new-feature

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@mmusich given that this is the DQM part, I assume it's not needed for the ReReco (of 2022A/2022B). Is that correct?

**Comment by tvami** [comment]
I guess I should also ask, independently of https://github.com/cms-sw/cmssw/pull/39166#issuecomment-1225608517 would you like this to be part of the next 12_4_X that is supposed to be cut today/tomorrow?

**Comment by mmusich** [comment]
> would you like this to be part of the next 12_4_X that is supposed to be cut today/tomorrow? 

yes.

**Comment by tvami** [comment]
urgent
 * see https://github.com/cms-sw/cmssw/pull/39166#issuecomment-1225610506
 * atn @perrotta @qliphy

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
[e03333c](https://github.com/cms-sw/cmssw/pull/39166/commits/e03333cdd9bf894c4eca9b348e2538d6c195c89d) should  resolve the problem with the unit test.
   * it's a commit missing in master that I'll have to forward-port

**Comment by perrotta** [comment]
@tvami @mmusich the release for the re-reco is basically ready to go. Waiting for this PR would imply a 1 day delay, at least (last fix was just submitted to the master in https://github.com/cms-sw/cmssw/pull/39173).
DQM updates as usual can be applied also on top of the existing online releases.

Because of that: do you really think that we should wait building 12_4_8 because of this PR? And, if so, why?

**Comment by mmusich** [comment]
> Because of that: do you really think that we should wait building 12_4_8 because of this PR? And, if so, why?

It's not needed for re-reco, but it will be useful to get it for the upcoming Prompt Reco of the rest of 2022 data.
So if it's in the plans to use 12_4_8 at Tier-0 it would be great to have.

**Comment by perrotta** [comment]
> It's not needed for re-reco, but it will be useful to get it for the upcoming Prompt Reco of the rest of 2022 data. So if it's in the plans to use 12_4_8 at Tier-0 it would be great to have.

Given the pause in the LHC runs, we will still have several days (weeks?) without beam. Let build the release for the re-reco now, as planned, then. Another 12_4_X release for the MC production will follow. If this (and possibly additional) PRs will be needed at T0 before that, we can still make a patch release with them,

**Comment by tvami** [comment]
+alca
 * tests pass
 * PR according to describtion

**Comment by mmusich** [comment]
enable threading

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
[last IB relvals](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_5/2022-08-25-1100?selectedArchs=el8_amd64_gcc10&selectedFlavors=X&selectedStatus=failed) look clean after the last bugfix was pushed in master.  Any residual objection to merge this PR @cms-sw/orp-l2 ?

**Comment by perrotta** [comment]
+1
- backport of https://github.com/cms-sw/cmssw/pull/39148 , https://github.com/cms-sw/cmssw/pull/39128 and https://github.com/cms-sw/cmssw/pull/39173

**Pull request merged**
