### PR TITLE
[13_2_X] Add option to sort candidates by pT in Unified Particle Transformer

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/45843

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by jfernan2** [comment]
This PR is not identical to the other backport  https://github.com/cms-sw/cmssw/pull/45847/files and does not emulate https://github.com/cms-sw/cmssw/pull/45843
Why fix_lt_sorting is not included here?

**Comment by stahlleiton** [comment]
> This PR is not identical to the other backport  https://github.com/cms-sw/cmssw/pull/45847/files and does not emulate https://github.com/cms-sw/cmssw/pull/45843
> Why fix_lt_sorting is not included here?

It is identical to the backport made to 14_1_X. It is not identical to the backport to 14_0_X because that one contains two PRs.

**Comment by stahlleiton** [comment]
> > This PR is not identical to the other backport  https://github.com/cms-sw/cmssw/pull/45847/files and does not emulate https://github.com/cms-sw/cmssw/pull/45843
> > Why fix_lt_sorting is not included here?
> 
> It is identical to the backport made to 14_1_X. It is not identical to the backport to 14_0_X because that one contains two PRs.
> 
> And regarding the fix, it has already been backported directly (without a flag) to 13_2_X since there were no models trained yet with the bug (the models for pp were trained for 14_0_X).

The fix of the sorting index was ported to 13_2_X in this PR: https://github.com/cms-sw/cmssw/pull/45700

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Pull request merged**
