### PR TITLE
Update 106X global tags in data and 2021/2023 MC

### LINKED ISSUE #24795: add/update highBetaStar 2018 workflows with a physics data run
I would like to ask for an update or addition of workflows with 2018 highBeta star configuration to include a physics data run.
Currently available workflows 136.8561 and 136.8562  use runs from April 2018 (314890 and 314276, respectively), which did not have a final PPS detector setup.

From the discussion in #24683, it looks like 319176 or 319270 can be used.

@nminafra @jan-kaspar @forthommel

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates offline, prompt-like and 2021 MC global tags in 10_6_X.

**Run I and Run II data**

Update of PPS conditions [1], HCAL response corrections [2], pixel/tracker conditions [3] for 2017 UL reprocessing.

Diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v11/106X_dataRun2_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v10/106X_dataRun2_relval_v9

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4136.html
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4132/1.html
[3] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4117/1.html

**Prompt-like Data**

Update of PPS conditions [1].

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4136.html

Diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v7/106X_dataRun2_PromptLike_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v7/106X_dataRun2_PromptLike_HI_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v6/106X_dataRun2_PromptLike_HEfail_v5

**2021 MC**

2021 MC is based on the best 2018 conditions available (106X_upgrade2018_realistic_v4), but with several other changes:

- Modified HCAL tags to incorporate updated geometry, including updated energy scale for upgraded HB
- Updated beam spot (round optics, high sigmaZ)
- Ideal CSC and pixel conditions

[1] 

Diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_design_v1/106X_postLS2_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v4/106X_postLS2_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021cosmics_realistic_deco_v2/106X_upgrade2021cosmics_realistic_deco_v1

#### PR validation:

Please see the links inline above for details of the validation. In addition, this PR includes a GT update that should resolve https://github.com/cms-sw/cmssw/issues/24795#issuecomment-490533983.

A dedicated [RelVal campaign for the 2021 realistic MC GT](https://cms-pdmv.cern.ch/valdb/?selected=10_6_0_pre4_2021&Reconstruction=true&RFull=true&PAGs=true&PFull=true) is underway.

Matrix tests have also been performed:
```
runTheMatrix.py -l limited -i all --ibeos
```

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by tocheng** [comment]
@christopheralanwest 
As master moves to 11_0_X, this PR needs backport to 10_6.
Thanks.

**Comment by mmusich** [comment]
@christopheralanwest @tocheng is there any showstopper with this PR? 
Please clarify

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The 2023 realistic GT has been updated by the request of the ECAL group: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4129.html The v2 GT had a mix of Run 2 and Phase 2 tags and was therefore wrong.

The data GTs do not yet have a fully consistent set of 2017 UL tags but @franzoni has requested to integrate the existing PR because such a set will likely become available after 10_6_1 closes.

I will sign off on this PR once the PR integration tests finish successfully.

**Comment by christopheralanwest** [comment]
+1

Changes are seen and expected in comparison tests for

- PPS quantities only in 2018 RECO (136.85) and 2017 re-MINIAOD (136.8311)
- 2017 data RECO (136.788)
- 2021 (11624.0) and 2023 (21234.0, 27434.0, and 29034.0) MC 

No changes are seen in other workflows.

**Comment by mmusich** [comment]
This needs now to be rebased. Also it would probably hep changing the title to say this is for 11.0.X rather than 10.6.X

**Comment by christopheralanwest** [comment]
The conflict was trivial: PR #26828 did not update the strings to remove the phrase "postLS2" from the comments (that is, it wasn't really a cherry-pick of the relevant commit from this PR), but the GTs were the same.

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

The only differences in the comparison tests are seen in the 2021 scenario, which differs because the recently merged PR #26828 changes the default 2021 MC SIM beamspot from `Realistic25ns13TeVEarly2017Collision` to `Run3RoundOptics25ns13TeVHighSigmaZ`.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
