### PR TITLE
fix Bu_D0Pi_KPiPi.dec

### PR DESCRIPTION
**Pull request by taweiXcms**
change line 12 from 
1.000      anti-D0  pi+                        PHSP;
to
1.000      Myanti-D0  pi+                        PHSP;

@mandrenguyen, @yenjie, @ginnocen

### CODE REVIEW

**Comment by covarell** [comment]
sorry, what is this fix for? The samples have already been produced... @vmariani

**Comment by taweiXcms** [comment]
Dear contacts,

This PR is just a small fix on the EvtGen file of B to D0p.
Same fix had been PRed to 8XX and signed by many.
Since the next 71X will be out very soon.
Would you please have a quick look at this PR and proceed if possible.
We sincerely appreciate your help on this matter.

Regards
Ta-Wei

**Comment by taweiXcms** [comment]
Heavy-Ion group is also planning to produce this sample in PbPb collision.
The previous EvtGen file does not require the D0 from B to decay to Kpi which its likely to be a typo.
And this will result in a low filter efficiency if we are trying to filter on this decay.
The already produced sample is totally fine since it just required more events to be generated at the beginning.
We just like this to be fixed if possible so that we don't have to generated many events for PbPb collision sample as well.

**Comment by covarell** [comment]
OK, but please make a PR for 75X if you want to use the same in HI

**Comment by covarell** [comment]
+1

**Comment by taweiXcms** [comment]
Thank you very much.
This fix is already in 758patch3.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
