### PR TITLE
Move dictionaries (and some classes) defined in `SimTracker/TrackTriggerAssociation` and `SimGeneral/TrackingAnalysis` to more proper packages

### LINKED ISSUE #968: Move dictionaries (and some classes) defined in `SimTracker/TrackTriggerAssociation` and `SimGeneral/TrackingAnalysis` to more proper packages

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

https://github.com/cms-sw/cmssw/pull/45423#issuecomment-2226416814 pointed to potential issues in dictionaries defined in `SimTracker/TrackTriggerAssociation` and `SimGeneral/TrackingAnalysis`. This PR
* Moves dictionary of `map<string, unsigned long long>` to `DataFormats/StdDictionaries`
* Removes dictionary of `map<int, int>` from `SimTracker/TrackTriggerAssociation` because it is already defined in `DataFormats/StdDictionaries`
* Removes dictionaries of `map<int, HepMC...>` from `SimTracker/TrackTriggerAssociation` because they are already defined in `SimDataFormats/GeneratorProducts`
* Removes TrackingParticle-only dictionaries from `SimTracker/TrackTriggerAssociation` because they are already defined in `SimDataFormats/TrackingAnalysis`
* Moves `TT{Cluster,Stub,Track}AssociationMap` classes and their dictionaries from `SimTracker/TrackTriggerAssociation` to `SimDataFormats/Associations`.
  * I saw in IB RelVal framework job reports these classes are persisted, and therefore they must be defined in a data format package. `SimDataFormats/Associations` seemed like a reasonable placement.
* Marks `tt::StubAssociation` as transient
  * I did not see it being persisted at the moment, and the dependence on `tt::Setup` (defined in `L1Trigger/TrackTrigger`) implies it (in its present form) can not be moved to a data format package, and therefore it must not be persisted
*  Moves dictionaries of `std::pair`s of `Ptr<TTTrack>` and `Ptr<TrackingParticle>` from `SimGeneral/TrackingAnalysis` to `SimDataFormats/Associations`
  * These seem to be related to the `std::map`s already defined there (by an earlier commit in this PR)
* Moves dictionaries of `std::pair<TrackingParticleRef, TrackPSimHitRef>` etc from `SimGeneral/TrackingAnalysis` to `SimDataFormats/Associations`
  * I saw these are persisted, and therefore the dictionaries must be defined in a data format package. `SimDataFormats/Associations` seemed like a reasonable placement.

I am a little bit concerned though that the `SimDataFormats/Associations` package has become a kitchen sink, which means that some jobs may end up loading more shared libraries than necessary. 

Resolves https://github.com/cms-sw/framework-team/issues/968

#### PR validation:

The modified packages compiled in 14_1_0_pre5 (I had to rebase afterwards but the conflict looked simple enough).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type -changes-dataformats

**Comment by makortel** [comment]
I updated the `duplicateReflexLibrarySearch.py` for the new placement of `TT{Cluster,Stub,Track}AssociationMap` (and also improved a little bit of the warnings printouts of the scipt). This should silence the warnings
```
./SimDataFormats/Associations/src/classes_def.xml
  TrackTriggerAssociation : edm::RefProd< TTClusterAssociationMap< edm::Ref< edm::DetSetVector< Phase2TrackerDigi >, Phase2TrackerDigi, edm::refhelper::FindForDetSetVector< Phase2TrackerDigi > > > >
  ...
```
in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-256413/40640/dupDict/lostDefs.txt

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by aloeliger** [comment]
+l1
- technical PR

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by Martin-Grunewald** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by tjavaid** [comment]
@makortel , I see several [duplication of the dictionaries](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-256413/40681/dupDict/dup.txt). Do those need a fix ?

**Comment by makortel** [comment]
> I see several [duplication of the dictionaries](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-256413/40681/dupDict/dup.txt). Do those need a fix ?

@tjavaid Those are false positives caused by a deficiency of the checker script. Because the `SimGeneral/TrackingAnalysis/src/classes_def.xml` is removed in this PR, the checker falls back to finding the file from the release area, and then reports the duplication. These warnings will disappear in a full IB build.

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable `WFs: 12434.7, 12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
