### PR TITLE
Do modern exceptions after conflicts resolved

### PR DESCRIPTION
**Pull request by ericvaandering**
Updated version of #12039. This should apply cleanly.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by ericvaandering** [comment]
From the log "error: unable to create file RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py (Disk quota exceeded)
"

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
(to retry after disk quota problem)

**Comment by slava77** [comment]
.. the tests are running 
details are in 
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/9455/console

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
the last attempt to run tests failed
```
...

./run-pr-tests: line 461: /tmp/cmsbuild/workspace/ib-any-integration/cms-bot/report-pull-request-results: No such file or directory
Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE

```

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12204	3975ea7
- code changes look in line with the PR description (technical updates in py config files)
- jenkins tests pass and comparisons with baseline show now differences

**Pull request merged**
