### PR TITLE
remove redundant HGCal unit test

### PR DESCRIPTION
**Pull request by kpedro88**
This HGCal unit test became redundant now that we have working Phase2 matrix tests. Rather than maintain an extra, unneeded configuration, we opt just to delete the whole thing.

attn: @civanch, @lgray

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@kpedro88 @boudoul @hengne 
do we have a workflow number that can be picked up by jenkins?
I think 10600.0 can be enough for a start.
For simplicity, we need to make it known to non-upgrade workflow list (so that one list/job submission is done)

**Comment by kpedro88** [comment]
10600.0 runs up through tracking reco with tilted tracker. Do we want to make that the baseline, or the flat tracker (11000.0 for local reco, 11200.0 for tracking reco)?

@boudoul will have to comment about making it known to the non-upgrade workflow list, I don't know how those communicate.

**Comment by slava77** [comment]
On 5/26/16 1:50 PM, Kevin Pedro wrote:
> 10600.0 runs up through tracking reco with tilted tracker. Do we want to
> make that the baseline, or the flat tracker (11000.0 for local reco,
> 11200.0 for tracking reco)?
> 

BTW,
LReco workflows are known to non-upgrade matrix.

**Comment by kpedro88** [comment]
@civanch - if you can sign this, hopefully @davidlang6 can merge it and then we can test/merge #14640...

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
