### PR TITLE
bsunanda:Run2-hcx116 back port PR 17948 for treatment of ND filter

### PR DESCRIPTION
**Pull request by bsunanda**
This is needed for correcting GEN-SIM step as well

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

Note: in some cases depth == 0 becomes depth == 1

**Comment by civanch** [comment]
@bsunanda , all 2017 WFs demonstrate substantial differences, is this PR a bug fix? I would extend description writing that explicitly, ideally  describing what means depth 0, 1, 2

There are 3 identical peaces of the code : lines 639-644, 959-961, 1022-1027:
if (numberingFromDDD) {
      HcalNumberingFromDDD::HcalID tmp = numberingFromDDD->unitID(det,etaR,phi,depth,1);
      modifyDepth(tmp);
      if (numberingScheme) unitID = numberingScheme->getUnitID(tmp);
 }

I would change this to 

if(numberingFromDDD && numberingScheme) {
      HcalNumberingFromDDD::HcalID tmp = numberingFromDDD->unitID(det,etaR,phi,depth,1);
      modifyDepth(tmp);
      unitID = numberingScheme->getUnitID(tmp);
}
or include this block into modifyDepth(det,etaR,phi,depth,1) to avoid code duplication.

There another block lines 1100-1145, where 'numberingScheme' flag is not check. Is this done for purpose?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by abdoulline** [comment]
Quick check with 2017 ("Plan1") single-pion gun :

(1)  without this PR: an issue of HcalRecHits scale (expected SimHits change isn't compensated downstream)
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/900pre6_Plan1_vs_900pre6_SinglePi/

(2) with this PR:  HcalRecHits become OK
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/900pre6_Plan1fix_vs_900pre6_SinglePi/

**Comment by civanch** [comment]
@bsunanda , @abdoulline , I am ready to sign but do not understand the a minor thing: line 1106 of the SD code: here you modify depth without checking 'numberingScheme' flag. In all other places both 'numberingScheme' and 'numberingFromDDD' are checked before "modify". Is this intended?

**Comment by bsunanda** [comment]
@civanch We have the option of giving layer weights based on some measurements from source scan results. This is done through files which provide eta, phi, depth indices and they are saved by packing using testNumberingScheme within HCalSD code and this is used while storing hits. So for this we know which packing is required. That is why there is no test of packing scheme is made there.

**Comment by bsunanda** [comment]
@civanch Please approve this. We need this for 2017 SIM step

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
