### PR TITLE
Improved muon track validation (new code + customization)

### PR DESCRIPTION
**Pull request by abbiendi**
This PR superseded #16646, which had been automatically ported to 90X from the previous PR #15153  (let's hope this time it will make through swiftly !!)

-- Summary description

This PR contains new code and configuration files, introduced alongside with the current code and cfgs. The new code is not yet used in the standard workflows, i.e. nothing should change anywhere.

A customization function will allow the new and the default code to run (both) for a given prerelease cycle in few selected muon RelVals. This will allow for a smooth transition between the current and the new validation code. The plan foresees to deploy the new validation at the prerelease following the one with duplicate validations. At that point the old code should be possibly removed.

The new code and configuration has been flagged by a prefix "New" in filenames, class/module names, when it is a duplicate of the current production code.

Features of the initial PR:

- much clearer code, easier maintenance and developments, some technical improvements
- new plots for performance vs PU, charge misid ...
- removal of a few unused plots
- improved settings of the histogram binning/ranges for different types of muons. All such settings contained in a cfg file "histoParameters_cff.py".
- better choice of names for histograms, corrected labels etc...
- better use of selectors to clean up the cfgs
- slimmed/clearer cfgs as a consequence of the above changes
- kept legacy configurations for use of TrackAssociatorByPosition in separate files, avoiding to clutter the main cfgs as in the current version
- new default setting of the MuonAssociatorByHits to flag as fakes global muons with tracker and muon hits matched to different particles: this will produce sensible fake rates (much higher than what is obtained currently). Side note: the current configuration has always lived for historical reasons.

Added features to the current PR:
- removed the pointer to DQMStore (as requested)
- synchronized the New validation code to the current code, after parallel developments in the last few months (for upgrades)
- customization function to activate the New validation for the temporary period of coexistence with the old one (thanks to Carlo Battilana)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@abbiendi , can you comment on WF 136.731 differences?

**Comment by abbiendi** [comment]
@civanch : where should I find that ?

**Comment by civanch** [comment]
@abbiendi , it is linked to this PR: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-10-1100+17489/18286/ 

There are regression problems in WF 136.731 and several others with data

**Comment by abbiendi** [comment]
I don't see why there should be consequences on workflows with real data, given that none of the changes should affect it. Please suggest ideas on what could it be or what should I further do

**Comment by abbiendi** [comment]
(this PR is all about MC validation)

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@abbiendi , I resubmit the test

**Comment by abbiendi** [comment]
@civanch  thanks ! hope this was unrelated to the PR

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by abbiendi** [comment]
Please, can we move on with this PR *in 900* ?
The basic signatures have been given 2 weeks ago, what are we waiting now ?
It is important to have it in 900.
(also we were hoping to have it earlier in 81X, don't let us miss again the release)
thanks,  Giovanni

**Comment by abbiendi** [comment]
@davidlange6  @franzoni   :   

Hi this PR is waiting to be merged, not to be shifted again to the new cycle, or we'll never end.
It is ready and necessary in 900. I wasted already a significant amount of time moving it from 81X to 900. thanks.

**Comment by abbiendi** [comment]
Hi all, the corresponding PR has been merged in 91X. Now we would need to have it backported in 90X, with this PR. It is necessary to proceed with the validation of the validation code which we will do in 90X (stable release) to have a firm reference for moving on safely. thanks.

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
