### PR TITLE
Fix GCC 7 errors and convert to UNIX format

### PR DESCRIPTION
**Pull request by davidlt**
There is no need to use TString, thus remove and simplify. Increase
buffers were needed and use snprintf to make sure we are not overflowing
on stack. In number of cases sprintf was used and according to compiler
we were overflowing the buffer (e.g. writing terminating nul after
buffer).

I have also noticed that some files container DOS formatting. Thus converted
files to UNIX format. Thus for review I suggest just looking at the first commit.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17423	c3b8af5
- technical changes
- jenkins tests pass and comparisons show no differences

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
