### PR TITLE
UL scale and smearing for nanoAOD photons and electrons (2017 and 2018)

### PR DESCRIPTION
**Pull request by jainshilpi**
This PR updates the UL2017 and 2018 scale and smearing corrections for nanoAOD. A few updates to:
(1) nano_cff.py
(2) photon_cff.py
(3) electron_cff.py

All runTheMatrix runs fine. Also tested on 136.8522 which was not included in the limited runTheMatrix.py. 

@mariadalfonso

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
seems that we need to wait for the 
https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/9
to appear in a new build 

`edm::FileInPath unable to find file EgammaAnalysis/ElectronTools/data/ScalesSmearings/Run2018_29Sep2020_RunFineEtaR9Gain_scales.dat anywhere in the search path.`

**Comment by mariadalfonso** [comment]
please test workflow 1325.6,1325.7,1325.8,136.7952, 1329.1, 136.7722, 136.8521, 10826.0 , 1325.61, 1325.81, 136.8522

**Comment by mariadalfonso** [comment]
Electron

**Comment by mariadalfonso** [comment]
+xpog
scale and smearing applied to electron and photon for UL 16-18, size of the effect shown in https://github.com/cms-sw/cmssw/pull/31974#issuecomment-719067241
nano from previous mini (94X.. and 102X) are untouched

**Comment by mariadalfonso** [comment]
@jainshilpi
can you make the backport to 10_6 of this PR, thanks

**Comment by silviodonato** [comment]
merge
@santocch please have a look

**Comment by jainshilpi** [comment]
> @jainshilpi
> can you make the backport to 10_6 of this PR, thanks

@mariadalfonso its on the way - will create a PR soon.

**Comment by santocch** [comment]
+1

**Pull request merged**
