### PR TITLE
[LLVM 10] Adjust Utilities/StaticAnalyzers for new clang

### PR DESCRIPTION
**Pull request by smuzaffar**
Backport of #29391
Changes needed to go with LLVM 10 .

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test cms-sw/cmsdist#5849

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by smuzaffar** [comment]
+core

**Comment by silviodonato** [comment]
+1

**Pull request merged**
