### PR TITLE
HGCal v9 fixes for egamma

### PR DESCRIPTION
**Pull request by kpedro88**
@hatakeyamak noticed an occasional crash in `RecoEcal/EgammaCoreTools/plugins/EcalClusterCrackCorrection.cc`. I found that it ultimately occurred because the exclusion of HGCal cells from some parts of the egamma algorithms had not been updated for the new geometry and DetIds. I had previously made a simple function to do this for `GEDPhotonProducer`. I have now moved that function into `EcalTools` and propagated it to every instance I could find.

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by kpedro88** [comment]
+upgrade

**Comment by hatakeyamak** [comment]
Just wanted to mention that I tested this PR on the RECO step where I discovered a non-negligible rate of crash (25% of jobs, 250 events for each job).
With this PR merged, this crash rate went done to zero, so it's a good sign. I cannot comment on the performance of egamma after this fix.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23987	9652c3e
- mostly a technical update to appropriately pick up all cases of HGCAL detector elements
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Pull request merged**
