### PR TITLE
COCOA: Remove Dependency on DD

### PR DESCRIPTION
**Pull request by ianna**
* There are no xml files in the CMSSW which define COCOA SpecPars. The analyzer cannot be tested, hence it is removed.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@lpernie - I wonder if the whole package ought to be removed

**Comment by pohsun** [comment]
@lpernie @tocheng
I don't see explicit dependency on `Alignment/CocoaApplication` except for [`Utilities/ReleaseScripts/scripts/git-publish`](https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/git-publish).
Should be safe to remove the package.

**Comment by ianna** [comment]
@lpernie @tocheng - perhaps this PR could be merged and the package removed as a subsequent PR?

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@pohsun wait, in this Alignment/CocoaApplication package there is more than what removed by @ianna , are all the tools in bin and test unused and obsolete?

**Comment by pohsun** [comment]
@fabiocos By searching the keyword "cocoaapplication", there's no explicit dependency on this package. The binary 'cocoa' is not called in other package. Should be safe to delete.

**Comment by boudoul** [comment]
Hello @pohsun , if you look on indico , you will find that COCOA seems to be still used for alignment purpose till this year- You may want to talk to the muon laser alignment people before removing their package . Thanks .

**Comment by fabiocos** [comment]
@pohsun yes, please cross check with them and let us know. I will punt temporarily on hold this PR pending a final clarification

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
@pohsun there was a clarification about the other utilities in this package?

**Comment by ianna** [comment]
@fabiocos - no, but the DD dependency has to be removed asap.

**Comment by pohsun** [comment]
@fabiocos @ianna As I receive no response from the relevant contact person so far. How about we merge the PR first?

**Comment by fabiocos** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - I think, the merge is waiting for unhold from you.

**Comment by fabiocos** [comment]
unhold

@ianna right...

**Comment by pohsun** [comment]
The expert, Zoltan Szillasi, suggests to keep the package.

**Pull request merged**
