### PR TITLE
[10.6.X] Python2to3 fixes

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the python3 compilation errors https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/python3/slc7_amd64_gcc700/CMSSW_10_6_X_2019-03-03-2300/python3.log
```
*** Error compiling 'src/Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py'...
Sorry: TabError: inconsistent use of tabs and spaces in indentation (betterConfigParser.py, line 162)
```
```
*** Error compiling 'src/RecoTracker/IterativeTracking/python/customise_MVAPhase1_cfi.py'...
Sorry: TabError: inconsistent use of tabs and spaces in indentation (customise_MVAPhase1_cfi.py, line 27)
```
```
*** Error compiling 'src/SimPPS/PPSSimTrackProducer/python/SimTrackProducerForFastSim_cff.py'...
Sorry: TabError: inconsistent use of tabs and spaces in indentation (SimTrackProducerForFastSim_cff.py, line 34)
```
```
*** Error compiling 'src/RecoTauTag/RecoTau/python/tools/runTauIdMVA.py'...
  File "src/RecoTauTag/RecoTau/python/tools/runTauIdMVA.py", line 53
    if debug: print "get_cmssw_version:", cmssw_version
                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(if debug: print "get_cmssw_version:", cmssw_version)?
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @perrotta @slava77 the fix looks quite technical and straightforward to me

**Comment by pohsun** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26057	396112a
- technical. code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
