### PR TITLE
Detector Description Graph Cleanup

### PR DESCRIPTION
**Pull request by ianna**
* Use cms naming convention for class
* Use alias using
* Use auto range for loops where appropriate
* Use emplace_back
* Add Graph class test

### CODE REVIEW

**Comment by ianna** [comment]
@Dr15Jones - FYI, tested in CLANG IB

**Comment by ianna** [comment]
please test

**Comment by Dr15Jones** [comment]
Did you intend to also change `graphwalker` to `GraphWalker`?

**Comment by ianna** [comment]
@Dr15Jones - yes, but it needs more debugging work. It looks like the crash comes from the graphwalker which returns nullptr as DDPosPart even though it is set explicitly.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
the relval error does not seem to be related to the PR:
```
%MSG-e L1T:  L1TRawToDigi:hltGtStage2Digis 25-Jul-2017 09:09:40 CEST  Run: 1 Event: 1
Cannot unpack: no FEDRawDataCollection found
%MSG
----- Begin Fatal Exception 25-Jul-2017 09:09:40 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'digitisation_step'
   [2] Calling method for module MixingModule/'mix'
   [3] Rethrowing an exception that happened on a different thread.
   [4] Reading branch PSimHits_g4SimHits_TrackerHitsTIDHighTof_SIM.
   Additional Info:
      [a] Fatal Root Error: @SUB=TStorageFactoryFile::ReadBuffer
read from Storage::xread returned 0

----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@slava77, @Dr15Jones - I was surprised to see dependency on DetectorDescription in Reco. However, if it is indeed needed, I'd suggest to move the Graph classes to FWCore or other common place.

**Comment by ianna** [comment]
@slava77, @Dr15Jones - or Reco could move to use Boost Graph (from CMSSW tools)

**Comment by slava77** [comment]
On 7/26/17 5:14 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77>, @Dr15Jones
> <https://github.com/dr15jones> - or Reco could move to use Boost Graph
> (from CMSSW tools)

I would need some more details.
- which files are affected
- what changes (a pattern; with an example) should be made

**Comment by ianna** [comment]
@slava77 - it's  RecoVertex/KinematicFitPrimitives/interface/KinematicTree.h in this PR

**Comment by slava77** [comment]
On 7/26/17 6:36 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - it's
> RecoVertex/KinematicFitPrimitives/interface/KinematicTree.h in this PR

does Boost Graph provide the same or similar interface?

It makes sense to move to a more common place (probably not FWCore
CommonTools/Utils seems like suitably named and still not too large to
fit some more

**Comment by slava77** [comment]
@ianna 
please move the Graph in this PR, unless there are other considerations and it should be done later

**Comment by ianna** [comment]
@slava77 - ok, will do

**Comment by ianna** [comment]
See https://github.com/cms-sw/cmssw/pull/19952

**Pull request closed without merging**
