### PR TITLE
Dynamic strip reco v2

### PR DESCRIPTION
**Pull request by andrewj314**
Rebasing of branch DynamicStripReco_v2 into 7_5_X

### CODE REVIEW

**Comment by cvuosalo** [comment]
@andrewj314: Please add details to this PR's description explaining its purpose. How does it change monitored quantities?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
if this code is changing products in standard workflows, it will have to go to 76X first.
From the code changes, it looks like a new feature (not a bug fix of sorts)

**Comment by slava77** [comment]
-1

there was an update in this PR.
AJ, it looks like you reused the same branch for 76X.
This PR should be closed in this case.

**Comment by deguio** [comment]
-1

**Comment by slava77** [comment]
-1
can't use the same branch for 75X and 76X at this point

**Comment by mmusich** [comment]
-1

**Comment by slava77** [comment]
-1
@andrewj314 
AJ please close this 75X PR

**Pull request closed without merging**
