### PR TITLE
Modified conditions to fix incorrect HLT JEC

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

Negative HLT jet energies [have been reported](https://groups.cern.ch/group/cms-hlt/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fcms%2Dhlt%2FLists%2FArchive%2FNegative%20jet%20energies%20in%20HLT%20PF%20corrected%20jets%20for%20Run%203%20MC&FolderCTID=0x012002005CF9F426540B9C4D8205911CC3985E98) in Run-3 samples. The problem has been traced to the fact that Run-3 GTs currently load the 2016 HLT JECs, while it should actually make use of the 2017 HLT JECs.

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v1/112X_mcRun3_2021_design_v2

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v1/112X_mcRun3_2021_realistic_v2

**2021 cosmic (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v1/112X_mcRun3_2021cosmics_realistic_deco_v2

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v1/112X_mcRun3_2021_realistic_HI_v2

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v1/112X_mcRun3_2023_realistic_v2

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v1/112X_mcRun3_2024_realistic_v2

#### PR validation:

Tests were performed with a candidate GT to ensure that the fix behaves as expected.

See the following presentations for details:

https://indico.cern.ch/event/915728/contributions/3850261/subcontributions/305633/attachments/2045906/3431055/200527_jme_hltJECs.pdf
https://cernbox.cern.ch/index.php/s/L6Sxh48hsyhq2m0

In addition, a technical test is performed:

`runTheMatrix.py -l limited,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but will be backported to 11_1_X and 11_0_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 7.23,159.0,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Changes validated in local tests
- Comparison tests show differences only in expected workflows (11634.0 and 12434.0) and only in the expected histograms (HLT histograms only)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
