### PR TITLE
Run3 alca216 Bug fix to Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Calibration/HcalCalibAlgos/plugins/HcalHBHEMuonAnalyzer.cc

#### PR validation:

Tested with 900 GeV test run data

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
Type bug-fix

**Comment by tvami** [comment]
Hi @bsunanda there are 5 commits in this PR for a simple bugfix. Please squash them. Thanks

**Comment by bsunanda** [comment]
@tvami There are only 2 commits

**Comment by tvami** [comment]
Screen Shot 2022-01-27 at 16 17 36
That's not what I see

**Comment by bsunanda** [comment]
@tvami I made a mistake - I was working with a merged version which I used for some other purpose. It is better to close this PR and open something fresh for the bug fix

**Pull request closed without merging**
