### PR TITLE
[12_4_X] Use singularity for gridpack generation

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/44900

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by bbilin** [comment]
test parameters:

- workflow = 180.1,181.1

**Comment by bbilin** [comment]
please test for slc7_amd64_gcc12

**Comment by bbilin** [comment]
please test

**Comment by bbilin** [comment]
different scram arch for gridpack was already tested in the initial branch, triggered the tests in native archs for these CMSSW versions.

**Comment by bbilin** [comment]
@stahlleiton just warned me that these two relvals do not exist in this CMSSW version. We need to revert the test with parameter. Sorry for missing this.

**Comment by mandrenguyen** [comment]
test parameters

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44900

**Comment by mandrenguyen** [comment]
please test

**Comment by stahlleiton** [comment]
Is there something pending to get this PR merged?

**Pull request closed without merging**
