### PR TITLE
Comphep single top filter pythia8 cmssw9

### PR DESCRIPTION
**Pull request by alexeybaskakov**
Update of edm::Handle, new method getByToken is used
And update to SealModule.cc to include new filter

### CODE REVIEW

**Comment by perrozzi** [comment]
please test
@alexeybaskakov can you please cross-reference the same PR in the various branches?

**Comment by alexeybaskakov** [comment]
Dear @perrozzi Yes, sure. Can you please explain in more detailes  how to do it in a right way?

**Comment by perrozzi** [comment]
just use links to PR. for instance, you can say that this PR https://github.com/cms-sw/cmssw/pull/17522 is the backport to 71X (and state there that this PR is the commit to HEAD)

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
