### PR TITLE
Adjust Method 2 code to allow one pulse fit for high ampl > 500 fC

### PR DESCRIPTION
**Pull request by lihux25**
Validation shows the kink around 100 GeV is mostly gone. Tail difference beyond (1.5 TeV) needs further understanding but it's rare case in real physics:
http://hep.baylor.edu/cmshcal/Validation/MC/731p1_Fix_MCRUN2_73_V7-v1_vs_730_MCRUN2_73_V7-v1_RelVal/HighPtQCD/RecHits/RecHits_energy_HB.gif

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the code change looks as expected

I started higher stat tests including 3 TeV dijet

**Comment by davidlange6** [comment]
please test




On Jan 21, 2015, at 9:59 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


A new Pull Request was created by @lihux25<https://github.com/lihux25> (Hongxuan Liu) for CMSSW_7_3_X.

Adjust Method 2 code to allow one pulse fit for high ampl > 500 fC

It involves the following packages:

RecoLocalCalo/HcalRecAlgos

@cmsbuild<https://github.com/cmsbuild>, @cvuosalo<https://github.com/cvuosalo>, @nclopezo<https://github.com/nclopezo>, @slava77<https://github.com/slava77> can you please review it and eventually sign? Thanks.
@argiro<https://github.com/argiro> this is something you requested to watch as well.
You can sign-off by replying to this message having '+1' in the first line of your reply.
You can reject by replying to this message having '-1' in the first line of your reply.
If you are a L2 or a release manager you can ask for tests by saying 'please test' in the first line of a comment.
@nclopezo<https://github.com/nclopezo> you are the release manager for this.
You can merge this pull request by typing 'merge' in the first line of your comment.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7314 f36ceaa
tested in CMSSW_7_3_0_patch1 (test area sign730p1a)
based on CMSSW_7_3_0_patch1 + (cherry-pick) of just this change in the PR:

A summary for QCD-3TeV sample

- the change in the hbhe hit energy is in the expected place. The discontinuity is smaller (the last few bins in red are more smooth than the black /old distribution/)
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10hbherechitssorted_reducedhcalrechits_hbhereco_reco_obj_obj_energy

- this in turn reduces the jet response that the high end:
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recocalojets_ak4calojets__reco_obj_et
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfjets_ak4pfjetschs__reco_obj_et
- response plot also shows a reduction (this sample is biased to more central high-pt jets, so the discontinuity below ~3 (TeV) is  a sample bias  feature)
wf1313_ak4pfresp_vs_et
- (only here using QCD flat-pt plot) the distribution is more continuous
wf38_ak4pfresp_vs_et


- pf neutral hadrons also shift down in response
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50
- MET sumet is lower
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfmets_pfmet__reco_obj_sumet

- MET looks a bit reduced 
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recocalomets_calomet__reco_obj_et
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfmets_pfmet__reco_obj_pt

- hcal hit time is more narrow (muons in this sample are a good area for the narrower jet, proximity to jet core where punchthroughs are more likely)
all_sign730p1avsorig_qcd13tevpt3ts3t5wf1313p0c_recomuons_muons__reco_obj_calenergy_hcal_time
- the timing in fact has a different kind of shape now (it was much smoother around 100 GeV before:
this, I suppose is a feature of the switch from 3-pulse to 1 pulse); while this is  a large diff, the variable  shouldn't affect anything:
wf1313_hbtower_time_vs_e
wf1313_hbtower_timeprofile_vs_e


Technical performance, timing is essentially unchanged (since the switch affects only a small fraction of fits)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
