### PR TITLE
[DQM-HLT] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixed set but unused warnings from clang-16 in CLANG IBs

### CODE REVIEW

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
@cms-sw/dqm-l2 , please have a look. This PR is very simple.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
