### PR TITLE
[13_3_X] Add SimBeamSpotObject record to Run-1/2/3 MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #43197 

This PR adds the `SimBeamSpotObject` tags to all Run-1/2/3 MC GTs. See master PR for more details.

#### PR validation:
See master PR

#### Backport:
Backport of #43197

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #43197

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+alca
- Same as #43197

**Comment by rappoccio** [comment]
+1

**Pull request merged**
