### PR TITLE
Fixes for Muon Alignment

### PR DESCRIPTION
**Pull request by lpernie**
Added 2 parameters for Muon alignemnt:
   createLayerNtupleDT = cms.bool(False),
   createLayerNtupleCSC = cms.bool(False)

In 3 files:
Alignment/CommonAlignmentMonitor/python/AlignmentMonitorMuonSystemMap1D_cfi.py
Alignment/CommonAlignmentMonitor/python/AlignmentMonitorMuonVsCurvature_cfi.py
Alignment/CommonAlignmentMonitor/python/AlignmentMonitorSegmentDifferences_cfi.py

### CODE REVIEW

**Comment by lpernie** [comment]
@ghellwig Here the PR in 90X.
Should I do it also in 91X?

**Comment by ghellwig** [comment]
@lpernie yes, please!
Since 91X is the development release it anyways needs to go in first there.

**Comment by boudoul** [comment]
Hi @lpernie , probably you know, but just in case, to queue in the development release , you should make a PR to the default developement release called 'master ' which is the default queue when making a PR (and therefore don't  choose 91X )

**Comment by ghellwig** [comment]
Shouldn't the parameters be used in the C++ code?
For example, [here](https://github.com/lpernie/cmssw/blob/6161e250a64f4a9a3721deb97c050694fca8af86/Alignment/CommonAlignmentMonitor/plugins/AlignmentMonitorMuonSystemMap1D.cc#L164) is not modified according to your config change.

**Comment by ghellwig** [comment]
@boudoul thanks for pointing out!

**Comment by lpernie** [comment]
Oh, I'm sorry for that.
Looking into the usage of those parameters, they are used in our "personal" version of "MuonAlignmentAlgorithms", not in CommonAlignmentMonitor!
Someone added them also to CommonAlignmentMonitor in the past, and I assumed they were used.
I think we can discard this PR! Sorry for that!

**Comment by ghellwig** [comment]
@lpernie can you then close it?
In case you want to revive it, you can either reopen or make a new PR.

**Comment by lpernie** [comment]
Sure, sorry again and thanks!

**Comment by ghellwig** [comment]
thank you!

**Pull request closed without merging**
