### PR TITLE
Remove vestigial (and huge) GBRForest when running with PFEGAlgo (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10315

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 I think the cmsbuild job died here. Probably need to start a new one.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try again

**Comment by cvuosalo** [comment]
Memory usage test in progress...

**Comment by lgray** [comment]
@slava77 @cvuosalo Hi guys, I don't see this queued in jenkins. May want to ask again for tests.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
tests are running now

**Comment by cvuosalo** [comment]
+1

For #10319 48af6ea410edbe7640a505ad95c7f72f96061c44

Removing unneeded GBRForest when running with PFEGAlgo. As seen for the 76X version of this PR, #10315, there should be about a 100 MB reduction in memory use. Otherwise, there should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10319/6635/summary.html) against baseline CMSSW_7_4_X_2015-07-24-2300 show no significant differences, as expected. A test of workflow 25202.0_TTbar_13 with 70 events against baseline  CMSSW_7_4_X_2015-07-21-2300 also shows no significant differences, and memory measurement shows about a 60 MB drop in RSS:

Baseline
Max VSIZ 3791.49 on evt 54 ; max RSS 3174.82 on evt 45
Time av 82.9808 s/evt   max 117.11 s on evt 34

PR 10319
Max VSIZ 3701.99 on evt 38 ; max RSS 3116.48 on evt 45
Time av 86.5668 s/evt   max 116.874 s on evt 20

**Comment by davidlange6** [comment]
+1

**Pull request merged**
