### PR TITLE
Fix DQM Matrix relval wfs

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Addresses #36188 and #36190 from the latest IBs relevant to 136.XXX wfs

#### PR validation:

Tested on 136.761, 136.829, 136.886, 136.8861, 136.8862, 136.829.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by perrotta** [comment]
test parameters:
- workflow = 136.829, 136.886, 136.8861, 136.8862, 136.761, 136.762, 136.783, 136.819, 136.82

**Comment by perrotta** [comment]
please test

**Comment by kskovpen** [comment]
These wfs fail because of the hcal trigger DQM harvesting step. @jfernan2, do you know what is the difference between the available hcal and hcal2 DQM options?

**Comment by kskovpen** [comment]
assign dqm

**Comment by kskovpen** [comment]
test parameters:

- workflow = 136.829, 136.886, 136.8861, 136.8862, 136.761, 136.762, 136.783, 136.819, 136.82

**Comment by kskovpen** [comment]
please test

**Comment by jfernan2** [comment]
> These wfs fail because of the hcal trigger DQM step. @jfernan2, do you know what is the difference between the available hcal and hcal2 DQM options?

The difference is, hcal:
https://github.com/cms-sw/cmssw/blob/e7263ecc5153bb4ad866ed694346bc75f34d260d/DQM/HcalTasks/python/OfflineSourceSequence_pp.py#L24
vs

hcal2:
https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMOffline/Hcal/python/HcalDQMOfflineSequence_cff.py#L16

The crash is due to the fact that @L1TMon should go with @hcal hand by hand. The solution you adopted with hcalOnly is perfectly fine. Thanks

**Comment by kskovpen** [comment]
> > These wfs fail because of the hcal trigger DQM step. @jfernan2, do you know what is the difference between the available hcal and hcal2 DQM options?
> 
> The difference is, hcal:
> 
> https://github.com/cms-sw/cmssw/blob/e7263ecc5153bb4ad866ed694346bc75f34d260d/DQM/HcalTasks/python/OfflineSourceSequence_pp.py#L24
> 
> 
> vs
> hcal2:
> 
> https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMOffline/Hcal/python/HcalDQMOfflineSequence_cff.py#L16
> 
> The crash is due to the fact that @L1TMon should go with @hcal hand by hand. The solution you adopted with hcalOnly is perfectly fine. Thanks

Thanks for clarifying @jfernan2 !

**Comment by qliphy** [comment]
type bugfix

**Comment by kskovpen** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
Thank you @kskovpen for having provided the fix.

It is not clear to me why a @cms-sw/upgrade-l2 signature is needed here... In any case @AdrianoDee, @srimanob if you have any comment please post them, otherwise we'll try to merge anyhow in time for the 1100 IBs, so that the RelVal errors can be cleaned in the IBs.

**Comment by srimanob** [comment]
+Upgrade

Bugfix on DQM & Harvesting sequence of relvals.

**Comment by perrotta** [comment]
+1

**Pull request merged**
