### PR TITLE
short name also in the final report

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

remove the step list from the final matrix report, as requested in #40106

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by smuzaffar** [comment]
> I imagine the tests had been relaunched by hand
yes, I restarted the failed RelVal INPUT test directly in Jenkins

**Comment by smuzaffar** [comment]
@perrotta, @rappoccio can we get this in for next IB. This should fix the IB Relval log issue reported [here](https://github.com/cms-sw/cmssw/pull/40106#issuecomment-1336366557)

**Comment by smuzaffar** [comment]
@perrotta, @rappoccio can we merge this please. This fixes the IB dashboard issue with load relvals logs

**Comment by rappoccio** [comment]
+1

**Pull request merged**
