### PR TITLE
cmsCodeRules fixes

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

* cppCommentSkipper: do not fail if line doesn't end with newline character
* cppFunctionSkipper, cmsCodeRulesChecker: don't fail if non-UTF8 characters are present in source files

#### PR validation:

Local tests

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by mbluj** [comment]
Are required deepTau model files already part of cms-data? Corresponding PR is already merged (https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/8), but could it be that it is not propagated to IB, yet?

**Comment by smuzaffar** [comment]
yes @mbluj , https://github.com/cms-sw/cmsdist/pull/7876 has been merged for last night IB (12.5.X  23h00)

**Comment by smuzaffar** [comment]
+core

**Comment by perrotta** [comment]
+1

**Comment by iarspider** [comment]
please test

**Pull request merged**
