### PR TITLE
Run3-sim97X Make use of ESGetToken in SimTracker/TrackerHitAssociation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in SimTracker/TrackerHitAssociation

#### PR validation:

Make use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
please test with #36021

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
