### PR TITLE
HLT menu development for `13_2_X` (3/N) [`13_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_2_X`.

This is the PR for the `master` branch, which will then be backported down to `13_2_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This version of the HIon HLT menu corresponds to the "V1.0" menu for the 2023 heavy-ion data-taking period (the corresponding frozen menu is not added to the release, as not needed by any central wf).

In addition, the following changes are included.
 - fb41033e7d3 fixes HLT customisations used to run on 2018 data (introducing SCAL digis for beamspot, adjusting parameters used in the pixel local reconstruction). These customisations became relevant again when trying to use 2018 HIon data to estimate rates and timings of the 2023 HIon menu. After the 2023 data-taking, these customisations could likely be removed.
 - d56c46e715e updates the HLT-Validation and HLT-addon tests involving the HIon menu to use the `Run3_pp_on_PbPb_2023` era
 - ccf345275d9 and f4f9b87cc15 update the GTs used in TSG tests to use the latest 2023 L1T menus for "pp-ref" ([`L1Menu_CollisionsPPRef2023_v1_1_1_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsPPRef2023_v1_1_1_xml)) and HIon ([`L1Menu_CollisionsHeavyIons2023_v1_1_1_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsHeavyIons2023_v1_1_1_xml)).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2882](https://its.cern.ch/jira/browse/CMSHLT-2882): [HIN] core of 2023 HIon menu
 - [CMSHLT-2885](https://its.cern.ch/jira/browse/CMSHLT-2885): [HIN,AlCa] AlCa requests for 2023 HIon menu
 - [CMSHLT-2904](https://its.cern.ch/jira/browse/CMSHLT-2904): [HIN] split `PPRefDoubleMuon`, `PPRefSingleMuon` and `PPRefHardProbes` PDs and streams
 - [CMSHLT-2905](https://its.cern.ch/jira/browse/CMSHLT-2905): [HIN] add D-meson triggers for 2023 HIon menu
 - [CMSHLT-2906](https://its.cern.ch/jira/browse/CMSHLT-2906): [HIN] add Mu+EG/Jet cross triggers for 2023 HIon menu
 - [CMSHLT-2907](https://its.cern.ch/jira/browse/CMSHLT-2907): [HIN] add `CommissioningRawPrime` PD to PRef menu
 - [CMSHLT-2913](https://its.cern.ch/jira/browse/CMSHLT-2913): [HIN] split `HIForward`, `HIMinimumBias` and `HIPhysicsRawPrime` PDs and streams of HIon menu
 - [CMSHLT-2914](https://its.cern.ch/jira/browse/CMSHLT-2914): [HIN] minimum-bias triggers of 2023 HIon menu
 - [CMSHLT-2915](https://its.cern.ch/jira/browse/CMSHLT-2915): [TSG] add `HIEphemeral*` PDs to HIon menu

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_2_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt
 - Outputs of PR tests are in line with the update of the HLT menus (GRun and "fake" menus). Differences in DQM plots are only technical (e.g. names of menus and Paths, because of change in Path-version numbers of GRun), as there are no physics changes for those menus (the HIon menu has several physics changes, and the only PR tests for that menu are in the `addOnTests`).

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping to review this PR.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
