### PR TITLE
DTValidation migration to ESConsume

### PR DESCRIPTION
**Pull request by jfernan2**
PR description:
Following https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module

Fixes DT Validation modules for issue #31061

PR validation:
runTheMatrix.py -l limited -i all --ibeos

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
