### PR TITLE
Fall17V2  Electron IDs and Isolations saved only in Run2

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

This PR is for  saving only Fall17V2  Electron IDs and isolations in Run2. Same thing has been done for photons in PR #42255.
 

#### PR validation:
runTheMatrix tests have been successfully run for the following workflow :

- runTheMatrix.py -l 12434.0

#### PR backport 
As pointed out by  Cross-POG convenors in the PR #42255 , we need backport to 13_0_X  for 2022 and 2023 data/MC processing.

Tagging EGM convenors @a-kapoor , @RSalvatico

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by Prasant1993** [comment]
Okay. I am rebasing the branch with the latest CMSSW_13_3_X_2023-09-05-1100 and trying to resolve the conflicts.

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by simonepigazzini** [comment]
Hi @Prasant1993, please open the backport to 13_0 as well

**Comment by Prasant1993** [comment]
> Hi @Prasant1993, please open the backport to 13_0 as well

Yes, I will do that. Thanks.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
