### PR TITLE
Mini aod substructure pieces overhaul, rebase of #7659 : Port to 75x

### PR DESCRIPTION
**Pull request by rappoccio**
Forward port of #8175

### CODE REVIEW

**Comment by monttj** [comment]
+1

**Comment by ferencek** [comment]
@rappoccio, it seems that this one can now be closed since the necessary code changes got propagated through #8357.

**Comment by rappoccio** [comment]
@ferencek I don't know how everyone wants to handle this, the other PR is still not merged. I don't have a strong opinion on whichever gets closed.

**Comment by ferencek** [comment]
@rappoccio, #8357 is already merged which is why I posted my previous message. But now I see that #8357 has some failed tests after being merged so I'm not sure how that will be handled. So for now maybe it is better to keep this one open. Not sure.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
