### PR TITLE
missing-, inactive-, valid-hits and clusterChargePerCm TkMaps

### PR DESCRIPTION
**Pull request by rrabadan**
valid, missing and inactive recHit TrackerHistoMaps added.
inclusiveClusterCharge, ClusterChargePerCMfromOrigin and ClusterChargePerCMfromTrack TkHistoMaps also added.
inclusiveClusterCharge and ClusterChargePerCMfromTrack configurable.
SiStripDQM_OfflineTkMap_Template_cfg_DB.py updated to create the corresponding new TkMaps

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by rrabadan** [comment]
what conflicts?

**Comment by deguio** [comment]
this one doesn't merge anymore. not sure you want it in 74 though.

**Comment by dmitrijus** [comment]
please close this PR

**Comment by dmitrijus** [comment]
-1

**Pull request closed without merging**
