### PR TITLE
DQMStore avoids using 0 as invalid module ID

### LINKED ISSUE #43711: Assertion failure in `testAlcaBeamMonitor`
Starting from [CMSSW_14_0_X_2024-01-12-2300](https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_X_2024-01-12-1100...CMSSW_14_0_X_2024-01-12-2300) `testAlcaBeamMonitor` 

https://github.com/cms-sw/cmssw/blob/e8154a2ff2a04ce4431ed5ed83d6ae84913c90c3/DQM/BeamMonitor/test/testAlcaBeamMonitor.cc#L17

 is failing in every IB (in all architectures) with an assertion:

```
===== Test "testAlcaBeamMonitor" ====
testAlcaBeamMonitor: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/50a1a8dffdd0aca0b3b5e055c82a1c18/opt/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2024-01-12-2300/src/DQMServices/Core/interface/DQMStore.h:687: dqm::implementation::DQMStore::bookTransaction(iFunc, uint64_t, bool)::ModuleIdScope::ModuleIdScope(dqm::implementation::IBooker&, uint64_t, MonitorElementData::Scope, edm::LuminosityBlockID) [with iFunc = DQMOneEDAnalyzer<edm::LuminosityBlockCache<alcabeammonitor::BeamSpotInfo> >::beginRun(const edm::Run&, const edm::EventSetup&)::<lambda(dqm::legacy::DQMStore::IBooker&)>; uint64_t = long unsigned int]: Assertion `newid != 0 || !"moduleID must be set for normal booking transaction"' failed.
```

see e.g. 

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-14-0000/unitTestLogs/DQM/BeamMonitor#/3

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The framework allows 0 as a valid ID.

#### PR validation:

Code compiles. Failing unit test now passes.

fixes #43711

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 `testAlCaBeamMonitor` now succeeds: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-970afb/36863/unitTests/src/DQM/BeamMonitor/test/testAlcaBeamMonitor/testing.log. Can you please sign?

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12434.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
