### PR TITLE
Photon monitoring in 92x release

### PR DESCRIPTION
**Pull request by gomber**
@fwyzard , @mtosi Here is the PR for the single photon paths corresponding to #18971 in CMSSW_9_2_X release

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by gomber** [comment]
@davidlange6  it is the same code as #18971 but in CMSSW_9_2_X, since that is merged, could you please take care of this too?

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
@gomber can you check if this PR is included #19961 ?

**Comment by gomber** [comment]
@fwyzard as you know, I am away, so checking mails now.
If my answer is still needed, I just checked this PR is already included in the 19961.

**Comment by fwyzard** [comment]
Thanks - can you close this PR, when you have a chance ?

**Pull request closed without merging**
