### PR TITLE
simple change to the merge configuration to allow the merging of NANOAOD

### PR DESCRIPTION
**Pull request by vlimant**
The configuration for merging in central production is taken from DataProcessing and we need this change to allow for the nanoaod merging using NanoAODOutputModule.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
assign core

**Comment by Dr15Jones** [comment]
Wouldn't `writeNANO` be a more descriptive name since you are not actually merging NANOAOD formated files together? Instead you are writing NANOAOD format based on EDM formatted files.

**Comment by davidlange6** [comment]
hi all - is this pr obsolete?
@arizzi @fabozzi

**Comment by arizzi** [comment]
I thought this was even deployed...

**Comment by davidlange6** [comment]
maybe some other mechanism was found?

**Comment by arizzi** [comment]
@vlimant  ?

**Comment by davidlange6** [comment]
apparently no longer needed

**Comment by arizzi** [comment]
@vlimant jean roch can you comment?

**Comment by arizzi** [comment]
concerning @Dr15Jones comment I guess the parameter name has been already propagated on the prod infrastructure side (to actually set a value for it) ... so changing it at this point would be disruptive for weak reasons (i.e. yes it does "write" nano but also it "merges" files so both are equally ok) @vlimant can confirm

Let's reopen this and propagate it to 94X too.

**Comment by davidlange6** [comment]
good we all wake up on the need for this PR - lets try to improve after the holidays...

**Comment by davidlange6** [comment]
merge

**Pull request merged**
