### PR TITLE
[10_6_X] Add ParticleNetAK4 to JME custom NanoAOD.

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmssw/pull/31714.

> #### PR description:
> 
> This PR adds the ParticleNetAK4 tagger scores to the JME custom NanoAOD. The tagger is added to both AK4 CHS and Puppi jets.
> 
> #### PR validation:
> 
> Tested NANO step on a UL17 ttbar sample w/ `--customise PhysicsTools/NanoAOD/custom_jme_cff.PrepJMECustomNanoAOD_MC`, and the tagger scores are correctly added.
> 

FYI @camclean @alefisico

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 25202.15,10224.15,11024.15

those are JME nano

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
please test
I solved I trivial conflict

**Comment by silviodonato** [comment]
@cms-sw/xpog-l2 do you have any comments on this PR?

**Comment by mariadalfonso** [comment]
please test workflow 25202.15,10224.15,11024.15

**Comment by mariadalfonso** [comment]
+xpog

changes inline with master
only JMEnano are updated

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
