### PR TITLE
Run2-hcx87 Fix a bug for Hcal geometry which affeted Phase2 operation

### PR DESCRIPTION
**Pull request by bsunanda**
Correct the bug which used to set all depth=4 as HO

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@ianna please approve when you can, simple bug fix for Phase2

**Comment by kpedro88** [comment]
@ianna ping

**Comment by bsunanda** [comment]
@ianna Could you review and approve this?

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
