### PR TITLE
Phase2-hgx360D Replace cout with logvervatim

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace cout with logvervatim

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
I guess the PR test failures are caused by the merge of https://github.com/cms-sw/cmssw/pull/46114

**Comment by smuzaffar** [comment]
please test 

there was bug in cms-bot which is fix now

**Comment by bsunanda** [comment]
+geometry

**Comment by Moanwar** [comment]
+Upgrade

**Pull request merged**
