### PR TITLE
Remove unnecessary open e/gamma paths from Phase2 HLT menu

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
This PR removes the following open paths:
`MC_Ele5_WP70_Open_Unseeded`
`MC_Ele5_WP70_Open_L1Seeded`
`MC_Photon100_Open_Unseeded`
`MC_Photon100EB_TightID_TightIso_Open_Unseeded`
`MC_Photon100_Open_L1Seeded`
`MC_Photon100EB_TightID_TightIso_Open_L1Seeded`

These paths are neither part of the actual simplified menu, nor needed for e/gamma menu development. 
To ease development, e/gamma needs two open paths, 
`MC_Ele5_Open_Unseeded`, and `MC_Ele5_Open_L1Seeded`. They are kept in the menu. 
The filters of `MC_Ele5_Open_L1Seeded` are now ignored as the path is open. 

#### PR validation:

After these changes, phase2 HLT menu runs fine.

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
