### PR TITLE
added esConsumes to modules in GeneratorInterface/HiGenCommon

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 2 modules
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by silviodonato** [comment]
do you have any comments  @alberto-sanchez @agrohsje @efeyazgan @mkirsano @qliphy @SiewYan ?

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
