### PR TITLE
Correction for HCAL iterative phi symmetry calibration AlCaReco

### PR DESCRIPTION
**Pull request by diguida**
Adding new AlCaReco definition for HCal iterative phi symmetry calibration.
Only python files were added or modified, no new producers added.
Originally in #8286

### CODE REVIEW

**Comment by mmusich** [comment]
@nilina @kodolova 
something you might want to watch as well

**Comment by diguida** [comment]
@abdoulline this is something you might want to watch as well.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
Let's fix it...

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
# Information on the Data Size

## Test Setup
* Test run on simulated `PhotonJets_Pt_10` in the Run2 scenario for RelVal;
* Input data tier: GEN-SIM-RECO
* Number of events: 3000

## Output Collections

````
Type                                  Module                     Label     Process
-------------------------------------------------------------------------------------
edm::TriggerResults                   "TriggerResults"           ""        "HLT"
edm::Association<vector<reco::Vertex> >    "offlinePrimaryVertices"   ""        "RECO"
edm::SortedCollection<HBHERecHit,edm::StrictWeakOrdering<HBHERecHit> >    "hbhereco"                 ""        "RECO"
edm::SortedCollection<HFRecHit,edm::StrictWeakOrdering<HFRecHit> >    "hfreco"                   ""        "RECO"
edm::SortedCollection<HORecHit,edm::StrictWeakOrdering<HORecHit> >    "horeco"                   ""        "RECO"
edm::ValueMap<int>                    "offlinePrimaryVertices"   ""        "RECO"
vector<reco::Vertex>                  "offlinePrimaryVertices"   ""        "RECO"
````

consistently with the output commands

````
"keep *_horeco_*_*",
"keep *_hfreco_*_*",
"keep *_hbhereco_*_*",
"keep *_offlinePrimaryVertices_*_*",
"keep edmTriggerResults_*_*_HLT"
````

## Event size

Total average uncompressed size: 32.572 kB/event
Total average uncompressed size: 13.704 kB/event

````
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event)
HBHERecHitsSorted_hbhereco__RECO. 16694.3 6615.54
HFRecHitsSorted_hfreco__RECO. 7262.06 3413.81
HORecHitsSorted_horeco__RECO. 3519.16 1668.79
EventProductProvenance 2116.74 1572.11
recoVertexs_offlinePrimaryVertices__RECO. 1572.95 228.806
intedmValueMap_offlinePrimaryVertices__RECO. 244.748 51.39
recoVertexsedmAssociation_offlinePrimaryVertices__RECO. 264.199 43.308
EventAuxiliary 148.984 41.5613
edmTriggerResults_TriggerResults__HLT. 623.62 40.672
EventSelections 100.305 21.7453
BranchListIndexes 25.0413 5.77267
````

## Data rate

@nilina @kodolova please comment further, based on the expected rate for your stream and PD.

**Comment by nilina** [comment]
It was assumed that the events size for the stream would be ~50kB.

**Comment by diguida** [comment]
@nilina thanks.
This AlCaReco should run on which stream/PD? Do I remember correctly that the stream (and the PD) is `AlCaHcalPhiSymmetry`? What is the expected event rate?

**Comment by nilina** [comment]
The stream is HcalCalIterativePhiSym and event rate is 10Hz.

**Comment by nilina** [comment]
and PD: EGamma, Muons

**Comment by diguida** [comment]
@nilina @kodolova
This AlCaReco is currently configured to run on PD not fed by stream A; indeed, the sequence definition is included into the `AlCaReco_Specials_cff.py`. This is in agreement with what you reported, i.e. this AlCaReco should run on `HcalCalIterativePhiSym` stream and corresponding PD.
Do you plan to run this also for stream A based PD, like EGamma, Muons?

**Comment by diguida** [comment]
+1
The AlCaReco implementation is ok.
The event size is small, as expected. If run on `HcalCalIterativePhiSym` stream, the rate is under control.
To be further discussed: implementation on other PD, and inclusion in the matrix: anyhow, this will require a further PR.

**Comment by mmusich** [comment]
@nilina @kodolova once this is merged in 7.5.X will need backport in 7.4.X as well. Will you take care?

**Comment by nilina** [comment]
OK, thank you.

**Comment by mmusich** [comment]
@diguida since this is meant to run on stream A PDs, please move the `AlCaReco` definition from `Configuration/StandardSequences/python/AlCaRecoStream_Specials_cff.py` to `Configuration/StandardSequences/python/AlCaRecoStream_cff.py `

**Comment by davidlange6** [comment]
@diguida - could you also add this to the relval matrix of alcas? (eg, to test it in relval)

**Comment by mmusich** [comment]
@davidlange6 that's possible of course but we need input from the developers about which datasets to use

**Comment by davidlange6** [comment]
maybe its good to get that input and modify the PR. Seems a more natural place for testing than the Tier0 :)

**Comment by mmusich** [comment]
@davidlange6, agreed, but as long as we don't touch the AlCaReco Matrix in `Configuration/Alca/python/autoAlCa.py` Tier-0 won't notice any change. In general we don't plan to make it aware until it's fully tested (cf. [AlCa/DB meeting 18.05](https://indico.cern.ch/event/368340/contribution/0/material/slides/0.pdf) )

**Comment by davidlange6** [comment]
@mmusich - ok thanks. I'll wait for the request you have to @diguida to be done and then will merge

**Comment by diguida** [comment]
@mmusich @davidlange6 done.

**Comment by diguida** [comment]
@nilina @kodolova @abdoulline
Given the outcome of [this presentation by DDT](https://indico.cern.ch/event/387806/session/12/contribution/114/material/slides/0.pdf) please choose the PD where you want to run your AlCaReco, and be careful with the HLT path selection. https://github.com/cms-sw/cmssw/pull/9075#issuecomment-101798619 and https://github.com/cms-sw/cmssw/pull/9075#issuecomment-101799257 only point out that the AlCaReco should run on PD from stream A. Also, please make sure the the requested 10 Hz are consistent with the rate of the HLT paths in the PD.

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by nilina** [comment]
@diguida Could you please advise where I can find some information about rates of the HLT paths in the PD? Is there any table on twiki?
Do we have the limits in quantity of the PD where we want to run this AlCaReco?
Thank you!

**Comment by diguida** [comment]
@nilina Sorry for late reply.
HLT Rates and Paths are taken care by TSG. Our contact @jmduarte will be glad to help you figure out these quantities.
For first collisions, please refer to the latest announcement [here](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/985.html).

Let me know if you need further assistance.

**Comment by jmduarte** [comment]
Actually, to clarify, the PDs are

HcalNZS
Commissioning
SingleMu
ZeroBias1
ZeroBias2
...
ZeroBias8

These PDs are composed of HLT paths that are essentially L1 pass-throughs. In terms of rates, things are a little uncertain, but these are some of the expected rates for tomorrow's first collisions (lumi 1.5E30/bunch)

Commissioning:
SingleEG5 ~ 39 Hz
SingleEG20 ~ 37 Hz
SingleJet36 ~ 30 Hz
SingleJet68 ~ 2 Hz

Commissioning and SingleMu:
SingleMuOpen ~ 2.5 Hz
SingleMu3p5 ~ 52 Hz

ZeroBiasN:
ZeroBiasN ~ 125 Hz

Note that each ZeroBiasN PD will get ~ 125 Hz

I am not sure if there are any Tier0 limitations as to how many PDs an AlCaReco can run in.

**Pull request merged**
