### PR TITLE
Preparing to include Method 3 result into HBHERecHit

### PR DESCRIPTION
**Pull request by igv4321**
Making space for storing "method 3" energy in HBHERecHit,
at the request of "Early 2015 Physics Commissioning" group.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11213	9cae790
- code changes are in line with the previous change for the rawEnergy. I wanted to suggest something simpler, but ended up retracing to a similar result. 
- the increase in rechit size on disk will stay in RECO tier, which shouldn't be a big deal considering its short lifetime.
- jenkins tests pass and comparisons with the baseline show no difference as expected (the new methods are not used yet)

**Comment by slava77** [comment]
Somewhat more compact version is the following.
You can add the method detection flags to just one single helper (no need to introduce a separate helper for that.
The example is detecting presence of a method ```float a() ```

```c++
template<typename T> struct AHelper {
  template<typename B> static int  test(decltype(B().a()) );
  template<typename B> static char test(...);
  static bool constexpr hasIt = std::is_same<decltype(AHelper::test<T>(0)), int>::value;
};

template<typename T, bool> struct AGetter {
  inline static float get_a(T const& a, float xx)  {return xx;}
};

template<typename T> struct AGetter<T, true> {
  inline static float get_a(T const& a,  float xx)  {return a.a();}
};

template<typename T>
float get_a(T const& a, float xx = -1e21) {return AGetter<T, AHelper<T>::hasIt >::get_a(a,xx); }
```

**Comment by abdoulline** [comment]
May we get it merged for Igor to proceed with making Method 3 permanently running (as Method 0 does) ?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
