### PR TITLE
Avoid illegal import from PhysicsTools/PatAlgos/plugins in MuonAnalysis

### PR DESCRIPTION
**Pull request by guitargeek**
PATTriggerMatchSelector is a dummy class that does nothing more than inheriting from StringCutObjectSelector anyway.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34232	dcea548
- code changes are technical
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

Considering that the code is templated, the design eventually allows more flexibility, which is not used here though. If eventually the need arises, the PATTriggerMatchSelector.h can be moved some place else.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
