### PR TITLE
Run4-hgx283x Second step for V15 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Second step for V15 geometry of HGCal. Adding algorithms to define a full silicon module

#### PR validation:

Tested using runTheMatrix test workflow 32634.0 and using test cfg's within Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Is this PR totally independent with https://github.com/cms-sw/cmssw/pull/32611/?
I see that you still keep
hgcalcell/v9/hgcalcell.xml
instead of v15

**Comment by bsunanda** [comment]
At the moment it is independent of #32611. I am slowly adding ingredients for v15 geometry of HGCal and the testing is done with v9 cells. Once #32611 is integrated we can later move to v14 HGCalCells. But I have not built a full scenario of v15 geometry yet. There are lots of new ingredients which need to come together

**Comment by srimanob** [comment]
Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
