### PR TITLE
Alignment geometry upgrade 80X (backport of #13976)

### PR DESCRIPTION
**Pull request by vbotta**
Upgraded alignment framework to cope with Phase1 geometry.
- including changes by Max Stark (@DirtyDan88)
- applied minimal fixes to restore full functionality of the alignment framework
- tested full alignment workflow incl. full module level alignment with multiple IOVs.

backport of #13976

### CODE REVIEW

**Comment by mmusich** [comment]
@vbotta why 80X as well? I understand this is needed for phase-1 only

**Comment by ghellwig** [comment]
@mmusich, we run the test alignment in 80X and have checked there that it does not break anything if using the run1-geometry. This would also allow us to use 80X for our tests.

Or can we use the 76X samples also in 81X? Probably yes, but could you confirm, please?

Btw., it's needed for 81X, but it's main intention is to be more geometry-independent, which is a valuable feature anyways.

**Comment by mmusich** [comment]
@ghellwig 

> Or can we use the 76X samples also in 81X? Probably yes, but could you confirm, please?

I think you can use 76X AlCaReco also in 80X

> it's main intention is to be more geometry-independent, which is a valuable feature anyways.

I tend to agree, but do we have a real use case for this feature this year? 80X is sort of closed...

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
>>Or can we use the 76X samples also in 81X? Probably yes, but could you confirm, please?

> I think you can use 76X AlCaReco also in 80X

Was that a typo? I really meant to say: Is it possible in 81X (not 80X)?


>>    it's main intention is to be more geometry-independent, which is a valuable feature anyways.

> I tend to agree, but do we have a real use case for this feature this year? 80X is sort of closed... 

It would make our life easier for development, I think. But if we can use all the 76X samples in 81X, we might be fine.

**Comment by mmusich** [comment]
@ghellwig don't forget you'll get large stat alcareco samples of all flavours from the `RunIISpring16DR80` campaign

**Comment by ghellwig** [comment]
@tlampen, @mschrode, @vbotta, @ShevchenkoRostyslav 
Do you agree with me, that we should then continue in 81X with the development and close this PR?
For the run1-geometry there is no difference in the configuration of the alignments, i.e. it is kind of independent from other developments in alignment.

**Comment by mschrode** [comment]
@ghellwig Yes, I agree, we do not necessarily need this PR for 80X. It is fine to continue the development entirely in 81X and higher.

**Comment by mmusich** [comment]
@mschrode @ghellwig I would -1 this if you are confident you don't need it here.

**Comment by ghellwig** [comment]
-1
I just run an alignment in 81X using 76X samples w/o problems

**Pull request closed without merging**
