### PR TITLE
GT Updates for L1T conditions needed for emulator

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## RunII simulation 
 
   * **RunII Asymptotic scenario** : [93X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v2) as [93X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_asymptotic_v2/93X_mcRun2_asymptotic_v1): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII CRAFT scenario** : [93X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2cosmics_startup_deco_v1) as [93X_mcRun2cosmics_startup_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2cosmics_startup_deco_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2cosmics_startup_deco_v1/93X_mcRun2cosmics_startup_deco_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Heavy Ions scenario** : [93X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v1) as [93X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_HeavyIon_v1/93X_mcRun2_HeavyIon_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Ideal scenario** : [93X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_design_v1) as [93X_mcRun2_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_design_v1/93X_mcRun2_design_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Proton-Lead scenario** : [93X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_pA_v1) as [93X_mcRun2_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_pA_v1/93X_mcRun2_pA_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Startup scenario** : [93X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_startup_v1) as [93X_mcRun2_startup_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_startup_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_startup_v1/93X_mcRun2_startup_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
attn. @kkotov @rekovic

**Comment by rekovic** [comment]
hmmm...AddOn tests “fastsim” and “fastsim1” fail, but "hlt_mc_Fake1" pass.

**Comment by arunhep** [comment]
please test

**Pull request merged**
