### PR TITLE
allow to ask for a mother ID in MCMultiParticleFilter

### PR DESCRIPTION
**Pull request by peiffer**
We need this filter for a B2G signal sample including two Higgs bosons in the final state. We want to filter on events with exactly one Higgs boson to decay into photons, the second Higgs boson can have any other decay mode.

The new version of the filter now allows to check for a mother-ID, in our case we want to look for two photons with a Higgs boson as mother.

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi- what is the 81x version of this PR?

**Comment by peiffer** [comment]
Hi, I haven't created a pull request for 81X yet because the GEN-SIM production is still taking place in 71X.
Should I open a new pull request for 81X, in principle the same version could be integrated into 81X too.

**Comment by davidlange6** [comment]
yes - all developments start in 81x.

**Comment by peiffer** [comment]
okay, see #16270

**Comment by davidlange6** [comment]
+1

**Pull request merged**
