### PR TITLE
Fix includes/forward declarations in FWCore/Framework

### PR DESCRIPTION
**Pull request by Teemperor**
Multiple headers in FWCore/Framework currently don't compile. This PR fixes this by correcting typos, including the relevant headers and adding the relevant forward declarations.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work to solve the issue https://github.com/cms-sw/cmssw/issues/15248

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
