### PR TITLE
Add new L1T stage-2 Menus

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Add ppRef 5TeV L1T stage-2 Menu
PR based on CMSSW_8_0_X_2016-02-16-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
needs to go to a data external

**Comment by Martin-Grunewald** [comment]
@davidlange6 

Please make an exception: there are already a few xml files in that directory, and they will disappear
(as last year) as soon as O2O for that part is ready...

**Comment by davidlange6** [comment]
but there will be 5 more in the meanwhile (that then we are stuck with in the git history)
@degano - could you just package up all the xml in L1Trigger/L1TGlobal/data+plus this PR and make a data external
Thanks!

**Comment by fwyzard** [comment]
@davidlange6 does this mean there will be a CMSSW 8.0.1 with the new external ?

**Comment by davidlange6** [comment]
Are you worried that we will never make a second 80x release?
________________________________________

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@davidlange6 @degano 
How can we proceed here? The idea was to move the L1T xml files to an external?!

**Comment by smuzaffar** [comment]
I am working on it  ( @degano is away today).

**Comment by smuzaffar** [comment]
@davidlange6 , do you only want to move xml files or other .xsd files too?

**Comment by davidlange6** [comment]
the xml files are sufficient - (now I see this PR has 4 new ones)

**Comment by smuzaffar** [comment]
cms-sw/cmsdist#2155 should add an external  data-L1Trigger-L1TGlobal with all the L1Trigger/L1TGlobal/data/**.xml files.

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
How is that accessed? Ie, what do I need to do to get those files?
Will it be copied into the original directory when checking out the package?
What path should be specified?

**Comment by smuzaffar** [comment]
I am going to make a PR for CMSSW L1Trigger/L1TGlobal where all the xml files will be dropped.
Both cmsdist and new cmssw PR should go in together.

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Sorry, what I meant was: once PR and external are in, where do the files show up
and how should the user access them?
Which file path should one use? The original one pointing to
the location in the package and they are somehow copied or linked?
IOW, how does the  'external' mechanism work once the files are in the 'external'?

**Comment by smuzaffar** [comment]
The files will show up in CMSSW_SEARCH_PATH (path type env variable used by edm::FileInPath mechanisum). So if you are using FileInPath mechanisum e.g.
edm::FileInPath("L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_CaloSliceTest_2015.xml");
then you do not have to change any thing.  Otherwise I would suggest to start using FileInPath :-)

**Comment by Martin-Grunewald** [comment]
Great! Two more questions (sorry):
1) will that automatically be in 81X as well? ie, are external automatically for all CMSSW release series?
2) How can one inspect the content of the 'external' itself at any time later?
Thanks a lot!

**Comment by smuzaffar** [comment]
1) yes, once approved for 80X they should automatically merge in 81X.
2) For each data external there is github.com/cms-data/data-* repository e.g. https://github.com/cms-data/L1Trigger-L1TGlobal . You can find out the tag used from cmsdist/data-L1Trigger-L1TGlobal.spec. Any future changes for these data files should be made via PRs to the cms-data/data-* repos

**Comment by Martin-Grunewald** [comment]
Closing this PR as being replaced by https://github.com/cms-sw/cmssw/pull/13425

**Pull request closed without merging**
