### PR TITLE
Phase2-hgx320 Try a fix for V17 HGCal geometry to treat orientation index correctly

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try a fix for V17 HGCal geometry to treat orientation index correctly

#### PR validation:

Use test codes in Geometry/HGcalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
The issue for HGCal V17 geometry was reported in the HGCal DPG meeting. Please see.  https://indico.cern.ch/event/1177257/contributions/4950980/attachments/2476127/4249471/Phase2-Talk129.pdf

This PR has cured the issue for V17. Please see the attached picture:

over_l1_v17_2_n

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
