### PR TITLE
Cleanup redundant edm ParameterSet exist in JetMETCorrections

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:  
(Technical PR) Optimization of the module configurations: Improve maintainability by cleaning up redundant cases of edm::ParameterSet calls to `existAs` or `exist` for tracked parameters, where redundancy is based on the value being already defined by `fillDescriptions`.

As follow the previous [PR36746](https://github.com/cms-sw/cmssw/pull/36746),  [PR36989](https://github.com/cms-sw/cmssw/pull/36989), [PR37313](https://github.com/cms-sw/cmssw/pull/37313), [PR37314](https://github.com/cms-sw/cmssw/pull/37314), [PR37548](https://github.com/cms-sw/cmssw/pull/37548), and [PR37772](https://github.com/cms-sw/cmssw/pull/37772).

The list of all calls of `existAs` or `exist` are automatically available in the Static Analyzer report. (Bug: CMS code rules)
It is accessible from IB page. https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/
For this task consider only modules or tools used by the modules that define `fillDescriptions`.

In this PR, 1 file was changed.  
JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h

Here, the "offsetCorrLabel", "jetCorrEtaMax" parameters were provided in a `fillDescription`.

cfipython : [cfipython/JetMETCorrections/Type1MET/pfJetMETcorrInputProducerTRecoPFJetJetCorrExtractorTRecoPFJet_cfi.py](https://cmssdt.cern.ch/lxr/source/cfipython/JetMETCorrections/Type1MET/pfJetMETcorrInputProducerTRecoPFJetJetCorrExtractorTRecoPFJet_cfi.py)

#### PR validation:
Tested in CMSSW_12_4_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@jeongeun the original code would need quite several cleanups and optimizations.
I don't ask you to apply all them here (even if it would be welcome). Could you please at least take care of what is actually related to the updates you applied in this PR? That is:
- Remove `offsetCorrLabel_` from the class initialization list (it could be eventually replaced by the initialization which is now at [line 85](https://github.com/cms-sw/cmssw/blob/4dedfedf94cfc8b7836bccaf2967394cddc81807/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h#L85)
- `moduleLabel_` variable is not used anywhere: please remove

**Comment by qliphy** [comment]
ping @jeongeun  Please address above comments

**Comment by qliphy** [comment]
ping @jeongeun

**Comment by qliphy** [comment]
> @jeongeun the original code would need quite several cleanups and optimizations. I don't ask you to apply all them here (even if it would be welcome). Could you please at least take care of what is actually related to the updates you applied in this PR? That is:
> 
>     * Remove `offsetCorrLabel_` from the class initialization list (it could be eventually replaced by the initialization which is now at [line 85](https://github.com/cms-sw/cmssw/blob/4dedfedf94cfc8b7836bccaf2967394cddc81807/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h#L85)
> 
>     * `moduleLabel_` variable is not used anywhere: please remove

@jeongeun  Please have a look at above comments.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
unhold
(issues that were raised had been finally addressed)

**Comment by perrotta** [comment]
+1

**Pull request merged**
