### PR TITLE
CTPPS 3d pixel detid

### PR DESCRIPTION
**Pull request by fabferro**
Added class CTPPSPixelDetId for 3d pixel tracker of CTPPS.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by fabferro** [comment]
@cmsbuild, @civanch, @mdhildreth, @davidlange6, @slava77, @smuzaffar
checks look successful, should I do more to go on? Please, let me know...

**Comment by davidlange6** [comment]
@slava77 fyi.

**Comment by slava77** [comment]
On 1/15/17 4:27 AM, David Lange wrote:
> @slava77 <https://github.com/slava77> fyi.

thanks
I do not have any significant comments here.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
