### PR TITLE
LST algorithm developments accumulated during integration PR

### PR DESCRIPTION
**Pull request by ariostas**
This PR integrates accumulated LST algorithm developments held back during the review of the LST integration (cms-sw/cmssw#45117). The full list of PRs that are included here can be found in https://github.com/SegmentLinking/cmssw/issues/117. This is our first step in our list of follow-up tasks (https://github.com/cms-sw/cmssw/issues/46746).

The changes include bug fixes and algorithmic improvements, but they also start to address follow-up comments from the integration PR. Here are some highlights.

- Improved support of minimal pt for track reconstruction (expanding also to 0.6 GeV) and made it configurable at runtime (addressing https://github.com/cms-sw/cmssw/pull/45117#discussion_r1749245650).
- Several updates to T5 DNN selection now replacing most of the algorithmic/rectangular cuts including Jupyter notebooks for documentation.
- Helix-based chi2 in rz improvement for pT5 and introduction for T3 objects.
- Other improvements and fixes, including developments in the standalone code.
- Addressed some follow-up comments from the integration PR (https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681737544, https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681741075, first bullet point of https://github.com/cms-sw/cmssw/pull/45117#issuecomment-2479912047)

Most of these were described in [TRK POG presentation on Sep 9](https://indico.cern.ch/event/1443183/#49-line-segment-tracking-statu)

Here is a plot showing the impact from these changes on the performance.

image

@slava77 @VourMa

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- enable_tests = gpu
- workflows_gpu = 24834.704
- workflows = 24834.703
- relvals_opt = -w upgrade,standard
- relvals_opt_gpu = -w upgrade,standard

**Comment by slava77** [comment]
> * relvals_opt = -w upgrade,standard
> * relvals_opt_gpu = -w upgrade,standard
I'm not sure the `,standard` is actually needed, but an extra shouldn't harm, I hope.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
