### PR TITLE
Lumi-based status plots, backport to CMSSW_12_3_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
A new type of status plots are added; lumi-based status plots. It displays the change of statuses of chambers as a function of lumi-blocks (=time).

This is a backport to CMSSW_12_3_X of #37135.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters:

- addpkg = DQM/Integration

**Comment by perrotta** [comment]
backport of #37135

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Backport PR in 12_2_X Tested successfully in Online DQM at P5

**Comment by perrotta** [comment]
+1
- Master version succesfully merged in CMSSW_12_4_X_2022-03-14-1100

**Pull request merged**
