### PR TITLE
Changed StubAssociator to a global module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed from steam to global module
- Also modernized some of the framework calls

This is part of the framework change which will require stream modules to explicitly register the use of Run/LuminosityBlock transitions.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
