### PR TITLE
[11_1_X] improving performance of PuppiProducer

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Backport of #31164 with the exception of one commit (e0f02d3) which would introduce small numerical changes in the outputs (see discussion in the original PR); the omission of said commit does not change the improvement in terms of computational performance.

No changes in the outputs are expected.

#### PR validation:

Checked that the PUPPI weights of all PF candidates are unchanged for 10 events of a Phase-2 workflow, for both `puppi` (used for jets) and `puppiNoLep` (used for MET).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #31164; useful for Phase-2 HLT TDR studies in `11_1_X`.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #31164

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31241	444f651
- code changes are in line with the PR description. The backport of #31164 is as expected in the context of no-change policy, limited to just the technical changes which do not change the numerical results https://github.com/cms-sw/cmssw/compare/3bc16a80c710b17f30c6e1164c5ca7e7f6f137c2...a49a3379f019731de8dfbe82c6a07bc5f285dd1e
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
