### PR TITLE
shared_ptr has arrived to the standard. NFC

### PR DESCRIPTION
**Pull request by vgvassilev**
We replace the CPP11_shared_ptr macro with its actual expansion to
std::shared_ptr nowadays.

We replace the inclusion of <CPP11_shared_ptr.hh> with <memory> and order
the includes from less generic to generic ones where applicable.

Depends on: #27626

cc @davidlange6

### CODE REVIEW

**Comment by vgvassilev** [comment]
I do not think it makes sense to apply what the bot proposed.

**Comment by davidlange6** [comment]
@fabiocos  - is it possible that clang-format has not been run on Alignment/Geners/interface/ArchiveRecord.hh? (which does not follow the right naming convention)

**Comment by davidlange6** [comment]
never mind - I realize its easy to answer my own question - clang-format has indeed not been run on this file for some reason (perhaps its name).  @vgvassilev - the patch is basically orthogonal to your work, its just that you touched a file that eluded the clang-format migration

**Comment by smuzaffar** [comment]
@davidlange6 , code-format was not run on this file as this file is not used by any thing. @vgvassilev I would suggest to just drop this file.

**Comment by vgvassilev** [comment]
Done.

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
@vgvassilev There are two errors in header check raised from removal of `Alignment/Geners/interface/ArchiveRecord.hh`. Could you check if `Alignment/Geners/interface/Record.hh` and `Alignment/Geners/interface/ArrayRecord.hh` are not used anymore? If it were true, we could also delete the two redundant files.

**Comment by vgvassilev** [comment]
Done.

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

@santocch the PR looks ok to me, please have a look

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
