### PR TITLE
Technical optimizations of PuppiContainer

### PR DESCRIPTION
**Pull request by lgray**
Use a kd-tree to speed up the searches of nearest neighbors for pf candidates in puppi.

Overall a factor 5-6 improvement.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Hmm apparently not so technical. Back to the drawing board.

**Comment by lgray** [comment]
@cmsbuild please test

Looks OK now at least locally.

**Comment by lgray** [comment]
@cmsbuild please abort

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Jenkins is showing numerous small differences in Run 2 and Phase 2 workflows for jets and Puppi. My PU 200 test is also showing numerous jet differences. I thought that this PR would merely improve performance by caching and not change any behavior. It looks to me like something is wrong.
Here are a couple of examples of difference plots from my PU 200 test with 200 events (red is PR, black is baseline; left is baseline and right is PR):

threshold
occup

**Comment by cvuosalo** [comment]
My PU 200 test of PAT does show improved performance, though with the issues discussed above.
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -1.192997      -3.29%      5346.61 ms/ev ->      1351.31 ms/ev puppi
   -1.191023      -3.27%      5321.55 ms/ev ->      1349.10 ms/ev puppiNoLep
  ---------- ------------     --------                  ----       ------------
Job total:  121.422 s/ev ==> 118.086 s/ev
```

**Comment by lgray** [comment]
Hmmm, ok, I'll try to take a close look at it tomorrow.

**Comment by cvuosalo** [comment]
My code review of this PR finds no problems, with the minor exception I noted above (https://github.com/cms-sw/cmssw/pull/17043#pullrequestreview-13638012).

**Comment by lgray** [comment]
@cvuosalo I have found the physics issue. Committing that now.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cvuosalo Found now hopefully the last physics difference... Needed to pad the kd-tree search region and found another instance of using reco::deltaR wrong.

**Comment by lgray** [comment]
@cvuosalo Commits coming momentarily

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
New Jenkins results are still showing widespread differences as before.

**Comment by lgray** [comment]
Ugh. I'll figure this out next year.

**Comment by lgray** [comment]
Hmmm going to try to get to the bottom of this... It is bugging me.

**Pull request closed without merging**
