### PR TITLE
Phase2-hgx341C Second step to go toward the V18 version of HGCal geometry which involve nonzero cassette shifts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The second step to go toward the V18 version of HGCal geometry which involve nonzero cassette shifts

#### PR validation:

Tested using scripts inside Geometry/HGCalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
