### PR TITLE
fix preexisting tracker alignment validation

### PR DESCRIPTION
**Pull request by hroskes**
backport of #22799

Fixing a stupid mistake.  The default behavior is setting this parameter to "true" which doesn't work with int.  I missed this one place in 297cb18bf0610f3184fb2ce9b4466b6ebddc6c05.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
I assume this PR need to be opened also in master

**Comment by fabiocos** [comment]
+1

**Pull request merged**
