### PR TITLE
[12_3_X] bugfix XML for PPS strips mapping

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

PR fixes a wrong comment tag in the XML mapping for the PPS silicon strips
Only now we could run the DAQ on the PPS detectors with silicon strips, so we couldn't spot it before,

#### PR validation:

relvals 136.793

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/37498

### CODE REVIEW

**Comment by tvami** [comment]
@grzanka please change the title so that is says [12_3_X]

**Comment by tvami** [comment]
type bugfix

**Comment by grzanka** [comment]
@tvami I see a complaint on github that there is a conflict which seems a bit weird. Can you cross-check on your side if this PR is mergeable?

image

**Comment by grzanka** [comment]
> I dont have merge rights :D What is the conflict by? If you click to the "resolve conflict" button?

It is due to that change:
image

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by grzanka** [comment]
> Hmm, I think this might happen if you didnt use a 12_3_X IB to submit the PR. Anyway, you could rebase, or just resolve the conflicts. I dont think @cms-sw/orp-l2 like to merge PR where there is a conflict (even if the changes are good as they are)

I've resolved the conflict, it was quite easy

**Comment by tvami** [comment]
> > Hmm, I think this might happen if you didnt use a 12_3_X IB to submit the PR. Anyway, you could rebase, or just resolve the conflicts. I dont think @cms-sw/orp-l2 like to merge PR where there is a conflict (even if the changes are good as they are)
> 
> I've resolved the conflict, it was quite easy

Thanks, I triggered tests

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
