### PR TITLE
Clean BuildFiles in L1Trigger

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/31532).

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by dildick** [comment]
Hi Jonas, there a few packages that I maintain within the L1-trigger. What prevents `scram b code-checks` from picking up the missing buildfiles?

**Comment by guitargeek** [comment]
Hello Sven! I would like to give you an answer, but I don't really understand the question. Are you wondering why the changes that I suggest in this PR are not just suggested by the code checks?

All I can say is that I intended to improve the modularity of CMSSW with these PRs. My original motivation was that I wanted to build parts of CMSSW independently of the rest, and on the way I wrote a script that removes unused dependencies from the BuildFiles. In the last year, I occasionally made PRs for different subsystems after running the script, and L1Trigger is actually the only remaining subsystem for which I didn't make a PR so far.

However, when you automatically remove the unused dependencies like that, you occasionally break packages that didn't declare all their dependencies but relied on the unused dependency declarations in packages further up in the dependency hierarchy that are now removed. That's why this PR also adds a few lines.

**Comment by dildick** [comment]
I think you largely answered my question. Thanks! 

In the future though, if someone were to (accidentally) remove a `<use name >` statement in a buildfile that you previously fixed, would `scram b code-checks` prevent that from happening? Or would your script have to be interfaced with `scram`?

**Comment by guitargeek** [comment]
If someone would accidentally remove a `<use name >` that I added, it will just not compile. The "worst" that can happen is that someone accidentally puts back a unused dependency that I removed, but this can be very easily spotted in PR reviews.

My script is too inefficient and not flexible enough to consider using it with scram; it's really more of a one-shot thing to get rid of a massive amount of unused dependencies that have accumulated over the years.

**Comment by dildick** [comment]
Ok. Thanks.

**Comment by silviodonato** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
