### PR TITLE
Remove FWLite dependency from PhysicsTools/UtilAlgos

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

By moving the header FWLiteAnalyzerWrapper.h to PhysicsTools/FWLite we break the dependency of PhysicsTools/UtilAlgos on PhysicsTools/FWLite. In addition to better dependency management, this will also avoid loading unneeded shared libraries during cmsRun processing.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
thanks @dr15jones - this will help - I think I can know tomorrow if this removes DataFormats/FWLite from any library/plugin used in runTheMatrix jobs or not.

**Comment by Dr15Jones** [comment]
ping @cms-sw/analysis-l2 this change would have avoided the linking problems seen in last nights CXXMODULES build.

**Comment by Dr15Jones** [comment]
ping @cms-sw/analysis-l2

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
