### PR TITLE
Prepare for concurrent IOVs, HcalDbProducer 

### PR DESCRIPTION
**Pull request by wddgit**
Note this PR contains 2 commits. The first commit just changes the line endings of HcalDbService from DOS to UNIX. The second commit contains the more substantive changes. Only 2 lines changed in HcalDbService, removing an unused constructor argument. Almost all the substantive changes are in HcalDbProducer. The intent is that it should behave identically when there is only one IOV processed at a time and its behavior is changed so that it will work also with concurrent IOVs.

I tested by turning on the debug print option for the many different callbacks and compared the output with and without my changes and it was identical. This is enabled with the "dump" configuration parameter of the HcalDbProducer. With one exception, for LutMetadata the debug print option throws a fatal exception both before and after my changes. I didn't fix this, but I didn't break it either.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

@Dr15Jones Can you check that this really resolves the concurrency issues as we discussed?

**Comment by Dr15Jones** [comment]
@wddgit From a quick look, this appears to be what we discussed.

**Comment by wddgit** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
