### PR TITLE
 Updated HI config file

### PR DESCRIPTION
**Pull request by dinardo**
I've updated the HI config file for the incoming HI run

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by dinardo** [comment]
Sorry for the spam,
I was simply wondering why this PR is still open.
Many thanks,
- Mauro.

**Comment by deguio** [comment]
76x will be used only for the end of the year rereco.
no data taking is foreseen with this release cycle. only the needed PRs are being merged.
ciao,
F.

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
