### PR TITLE
Multi-threading for some HLTcore plugins

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Multi-threading for some HLTcore plugins:
HLTEventAnalyzerAOD.h
HLTEventAnalyzerRAW.h
TriggerSummaryAnalyzerAOD.h
TriggerSummaryAnalyzerRAW.h
and
TriggerSummaryProducerRAW.h
Still missing: more complicated TriggerSummaryProducerAOD.h as it needs a non-trivial GlobalCache

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
-1
Need to check whether it should instead be a ONE module in case of the analyzers which do
printouts!

**Comment by Dr15Jones** [comment]
@Martin-Grunewald you will want to avoid ONE modules in the HLT since they cause synchronization. They also can in the future inhibit the framework from being able to process multiple Runs and Lumis simultaneously.

**Comment by Martin-Grunewald** [comment]
Hi Chris,

These are analysers not running in the HLT but printout per event.
This I think they must be ONE modules.
But I can't get it to work - shouldn't I just do:
class HLTEventAnalyzerAOD : public edm::one::EDAnalyzer<edm::one::WatchRuns> {
?

**Comment by Dr15Jones** [comment]
If you just get rid of the couts and use MessageLogger then these could actually be global modules.
Using cout in a threaded program is just going to cause your output to be garbled.

**Comment by fwyzard** [comment]
The printouts should be in the *global*  endLumi / endRun methods, so they
would not add any synchronisation issues - would they ?

.A

**Comment by Martin-Grunewald** [comment]
No no no. These are user-analysers printing info out for each event.

**Comment by fwyzard** [comment]
On 12 January 2015 at 16:27, Martin Grunewald <notifications@github.com>
wrote:

> These are analysers not running in the HLT but printout per event.
> This I think they must be ONE modules.
> But I can't get it to work - shouldn't I just do:
> class HLTEventAnalyzerAOD : public edm:[image: :one:]:EDAnalyzeredm:[image:
> :one:]:WatchRuns {
>


Ah sorry, I was thinking about the summaries.

If they are per-event, the Messagelogger should work, something like

{
edm::LogInfo message("Summary");
message << ...;
message << ...;
message << ...;
}

.A

**Comment by Martin-Grunewald** [comment]
Why should the message logger avoid garbelling the print lines from different streams?

**Comment by Martin-Grunewald** [comment]
Anyway, I do not undertsnad this error in the SealModule.cc which calls the FW macro:

```
Reading cached build data
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Entering Package HLTrigger/HLTcore
>> Creating project symlinks
>> Compiling edm plugin /data/CMS0/CMSSW_7_4_X_2015-01-12-0200/src/HLTrigger/HLTcore/plugins/SealModule.cc 
In file included from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/interface/stream/EDAnalyzerAdaptor.h:32:0,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/interface/stream/EDAnalyzerBase.h:26,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/interface/stream/EDAnalyzer.h:28,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:37,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFillerPluginFactory.h:25,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/ServiceRegistry/interface/ServiceMaker.h:22,
                 from /data/CMS0/CMSSW_7_4_X_2015-01-12-0200/src/HLTrigger/HLTcore/plugins/SealModule.cc:1:
/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/src/MakeModuleHelper.h: In instantiation of 'static std::unique_ptr<T> edm::MakeModuleHelper<Base>::makeModule(const edm::ParameterSet&) [with T = HLTEventAnalyzerAOD; Base = edm::one::EDAnalyzerBase]':
/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/src/WorkerMaker.h:85:149:   required from 'std::shared_ptr<edm::maker::ModuleHolder> edm::WorkerMaker<T>::makeModule(const edm::ParameterSet&) const [with T = HLTEventAnalyzerAOD]'
/data/CMS0/CMSSW_7_4_X_2015-01-12-0200/src/HLTrigger/HLTcore/plugins/SealModule.cc:24:39:   required from here
/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc481/cms/cmssw-patch/CMSSW_7_4_X_2015-01-12-0200/src/FWCore/Framework/src/MakeModuleHelper.h:39:44: error: cannot allocate an object of abstract type 'HLTEventAnalyzerAOD'
       std::unique_ptr<T> module{new T(pset)};

```

**Comment by Dr15Jones** [comment]
Because the message logger is specifically built to not garble messages. It queues the messages from all streams and makes sure only one is being output at a time.

**Comment by Dr15Jones** [comment]
The error is saying you are missing an override of a virtual function from the base class.

**Comment by Martin-Grunewald** [comment]
How is the buffering done?

Can I issue only one (BIG) MessageLogger statement per event in each stream module,
or several? Ie, how does the ML buffer internally? Collecting all messages for a given
Event/Lumi/Run number and then putting that out in order? Or only one message,
and then the ML jumps to the next which may come from a different stream?

**Comment by fwyzard** [comment]
On 12 January 2015 at 16:58, Martin Grunewald <notifications@github.com>
wrote:

> Can I issue only one (BIG) MessageLogger statement per event in each
> stream module,
> or several? Ie, how does the ML buffer internally? Collecting all messages
> for a given
> Event/Lumi/Run number and then putting that out in order? Or only one
> message,
> and then the ML jumps to the next which may come from a different stream?
>
I would suggest one big message per stream per event, this way you get only
one set of %MSG delimiters, and you should be guaranteed that the messages
do not interfere with each other.

If I understand correctly how it works, you do not need to buffer the
message yourself: just create an edm::LogInfo object, << everything into
it, and the message will be printed once the object goes out of scope.

.A

**Comment by Dr15Jones** [comment]
> If I understand correctly how it works, you do not need to buffer the message yourself: just create an edm::LogInfo object, << everything into it, and the message will be printed once the object goes out of scope.

That is correct.

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
