### PR TITLE
Add new configuration options to CloseByParticleGun

### PR DESCRIPTION
**Pull request by OzAmram**
This PR adds new functionality to the CloseByParticleGun, specifically the ability to logarithmically space the energy distribution and to specify the particle location based on R and eta. These developments are done in support of upcoming sample generation of HGCal simulations for ML4Sim R&D

 Also promoted previous LogErrors related to inconsistencies of the configuration parameters into exceptions 

@kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
@cms-sw/generators-l2 please check and sign

**Comment by kpedro88** [comment]
ping @cms-sw/generators-l2. this PR is needed for an upcoming MC production request.

**Comment by bbilin** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
