### PR TITLE
Reco material phaseI

### PR DESCRIPTION
**Pull request by rovere**
This PR will bring in the new recoMaterial tuning on top of the development/changes that have been added in #16338.
I locally merged it and started on top: I'm not sure what is the recommended/best procedure to follow in order to have both PRs integrated with the least possible conflicts.
Results of the tuning are ok, neither dramatic nor stricking, mostly because the material was already tuned in pre9. 
You can find the usual MTV like plots for SingleMuon, Pt 10,5 here [1](https://roverepublic.web.cern.ch/roverepublic/temp_images/PhaseI/Post16338/Tuning/PixFwd/MTV_SingleMuPt10/) and [2](https://roverepublic.web.cern.ch/roverepublic/temp_images/PhaseI/Post16338/Tuning/PixFwd/MTV_SingleMuPt5/), respectively.
In general we could conclude that the Chi2 is somehow flattish, the number of missing outer hits decreases and the overall duplicate tracks go down (even if it's hard to judge on single muon samples).

The PR will also bring in all the mandatory C++ changes to the scripts used to derive the tuning: these are mandatory mostly for PhaseII, but since these code changes **are not part of any workflow**, I judged as ok to have them here. If Offline has problems with this approach, I formatted the history so that a single commit has all the required changes to the reconstruction material description: in case we could cherrypick only that one (in a separate PR).

Further testing on other samples is welcome in this case, to see if unforeseen changes will show up.

### CODE REVIEW

**Comment by rovere** [comment]
FYI @friccita, @schneiml @veszpv @boudoul

**Comment by davidlange6** [comment]
please test

**Comment by ianna** [comment]
@rovere - please rebase it. It will be easier to see your changes. Thanks.

**Comment by rovere** [comment]
@ianna Geometry/TrackerRecoData/data/PhaseI/trackerRecoMaterial.xml
that's the only file interesting

**Comment by ianna** [comment]
@rovere - that's what I'd like to see, not changes to pixel geometry.

**Comment by ianna** [comment]
+1

From local merge with recent IB there is only one xml geometry file changed. IB tests and comparisons for Phase 1 run on geometry from DB, no differences should be seen.

```
You are on branch from-CMSSW_8_1_X_2016-10-31-1100
From .
 * [new ref]                    -> merge-attempt
remote: Counting objects: 154, done.
remote: Total 154 (delta 99), reused 99 (delta 99), pack-reused 55
Receiving objects: 100% (154/154), 37.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (122/122), completed with 32 local objects.
From https://github.com/rovere/cmssw
 * [new branch]      RecoMaterialPhaseI -> rovere/RecoMaterialPhaseI
Switched to branch 'merge-attempt'
Removing Validation/Geometry/test/varParser.py
Removing SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseII.py
Removing SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseI.py
Removing SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_cff.py
Removing SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseI_cff.py
Removing SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseII_cff.py
Merge made by the 'recursive' strategy.
 Geometry/TrackerRecoData/data/PhaseI/trackerRecoMaterial.xml                                | 999 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------
 SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseI.xml                | 795 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
 SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII_D4.xml            | 552 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 SimTracker/TrackerMaterialAnalysis/plugins/ListGroups.cc                                    |   5 +-
 SimTracker/TrackerMaterialAnalysis/plugins/ListGroupsMaterialDifference.h                   | 180 +++++++++++++++++++----------------
 SimTracker/TrackerMaterialAnalysis/plugins/MaterialAccountingGroup.cc                       |   2 +
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cff.py        |   4 -
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cfi.py        |  60 +++++-------
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseI_cff.py         |   4 -
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseI_cfi.py         |  22 +++--
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseII_cff.py          |   7 --
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseI_cff.py           |   7 --
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_cff.py                     |   7 --
 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialVarParsing.py                     |  21 ++++
 SimTracker/TrackerMaterialAnalysis/test/dumpFullXML.py                                      |  13 +--
 SimTracker/TrackerMaterialAnalysis/test/listGroups.py                                       |  22 ++++-
 SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseI.py                             |  17 ----
 SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseII.py                            |  17 ----
 SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseI.py                                   |   6 +-
 SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py                                  |  10 +-
 SimTracker/TrackerMaterialAnalysis/test/trackerRecoMaterial.xml                             | 958 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------
 SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser.py                         |   2 +
 SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseI.py               |   7 +-
 SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py              |  15 +--
 SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseI.py  |   2 +-
 SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseII.py |   6 +-
 Validation/Geometry/python/customiseForDumpMaterialAnalyser_ForPhaseII.py                   |   5 +
 Validation/Geometry/src/TrackingRecoMaterialAnalyser.cc                                     |   2 +-
 Validation/Geometry/test/MaterialBudget.C                                                   | 250 +++++++++++++++---------------------------------
 Validation/Geometry/test/MaterialBudget_Simul_vs_Reco.C                                     | 512 +++++++++++++++++++++++++++++---------------------------------------------------------------------
 Validation/Geometry/test/MaterialBudget_Simul_vs_Reco_PhaseIID4.C                           | 583 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 Validation/Geometry/test/runMaterialDumpAnalyser_PhaseI.sh                                  |  26 ++---
 Validation/Geometry/test/runMaterialDumpAnalyser_PhaseII_D4.sh                              | 154 ++++++++++++++++++++++++++++++
 Validation/Geometry/test/runP_Tracker_cfg.py                                                |  25 ++---
 Validation/Geometry/test/varParser.py                                                       |  13 ---
 35 files changed, 4240 insertions(+), 1070 deletions(-)
 create mode 100644 SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseII_D4.xml
 delete mode 100644 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseII_cff.py
 delete mode 100644 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseI_cff.py
 delete mode 100644 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_cff.py
 create mode 100644 SimTracker/TrackerMaterialAnalysis/python/trackingMaterialVarParsing.py
 delete mode 100755 SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseI.py
 delete mode 100755 SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseII.py
 create mode 100644 Validation/Geometry/python/customiseForDumpMaterialAnalyser_ForPhaseII.py
 create mode 100644 Validation/Geometry/test/MaterialBudget_Simul_vs_Reco_PhaseIID4.C
 create mode 100755 Validation/Geometry/test/runMaterialDumpAnalyser_PhaseII_D4.sh
 delete mode 100644 Validation/Geometry/test/varParser.py
Switched to branch 'from-CMSSW_8_1_X_2016-10-31-1100'
>> Checking Geometry/TrackerRecoData CMSSW_8_1_X_2016-10-31-1100
   x Geometry/TrackerRecoData/data/PhaseI/trackerRecoMaterial.xml
>> Checking SimTracker/TrackerMaterialAnalysis CMSSW_8_1_X_2016-10-31-1100
   - SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseII_cff.py
   - SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseI_cff.py
   - SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_cff.py
   - SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseI.py
   - SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseII.py
   x SimTracker/TrackerMaterialAnalysis/data/trackingMaterialGroups_ForPhaseI.xml
   x SimTracker/TrackerMaterialAnalysis/plugins/ListGroups.cc
   x SimTracker/TrackerMaterialAnalysis/plugins/ListGroupsMaterialDifference.h
   x SimTracker/TrackerMaterialAnalysis/plugins/MaterialAccountingGroup.cc
   x SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cff.py
   x SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cfi.py
   x SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseI_cff.py
   x SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseI_cfi.py
   x SimTracker/TrackerMaterialAnalysis/test/dumpFullXML.py
   x SimTracker/TrackerMaterialAnalysis/test/listGroups.py
   x SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseI.py
   x SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py
   x SimTracker/TrackerMaterialAnalysis/test/trackerRecoMaterial.xml
   x SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser.py
   x SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseI.py
   x SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py
   x SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseI.py
   x SimTracker/TrackerMaterialAnalysis/test/trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
>> Checking Validation/Geometry CMSSW_8_1_X_2016-10-31-1100
   - Validation/Geometry/test/varParser.py
   x Validation/Geometry/src/TrackingRecoMaterialAnalyser.cc
   x Validation/Geometry/test/MaterialBudget.C
   x Validation/Geometry/test/MaterialBudget_Simul_vs_Reco.C
   x Validation/Geometry/test/runMaterialDumpAnalyser_PhaseI.sh
   x Validation/Geometry/test/runP_Tracker_cfg.py
>> Creating dummy files under /build/yana/TKDB/CMSSW_8_1_X_2016-10-31-1100/poison directory.
   SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseII_cff.py
   SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_ForPhaseI_cff.py
   SimTracker/TrackerMaterialAnalysis/python/trackingMaterialGroups_cff.py
   SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseI.py
   SimTracker/TrackerMaterialAnalysis/test/listGroups_ForPhaseII.py
   Validation/Geometry/test/varParser.py
Checking out these packages: 0
```

**Comment by rovere** [comment]
Not sure the error is related in any way to this PR.
Has ProtocolBuffer been updated as an external recently?

**Comment by rovere** [comment]
And, even more, why is it trying to compile stuff from DQMServices/Core??

**Comment by davidlange6** [comment]
please test
seems something got corrupted- - lets try again

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
