### PR TITLE
Drop PROOF tests (as discussed in #43975)

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all. PROOF is a deprecated feature, and not used by CMSSW.

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

(even if tests are somewhat pointless for this PR)

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
