### PR TITLE
[14_0_X] Adding GEM onlineDQM trigger primitive plots

### PR DESCRIPTION
**Pull request by Dongwoon77**
#### PR description:

In this PR, GEM onlineDQM plots for trigger primitive have been implemented.

This is a backport of #45489 to 14_0_X.

#### PR validation:

Tests are done with cmsRun $CMSSW_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True runNumber=379866 dataset=/ExpressPhysics/Run2024C-Express-v1/FEVT minLumi=20 maxLumi=30 eventsPerLumi=50000 and runTheMatrix.py -l limited -i all --ibeos since it makes effects on P5.

@jshlee @watson-ij @quark2 @hcai0520 @giovanni-mocellin

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #45489

**Comment by tjavaid** [comment]
@cmsbuild , please test

**Comment by tjavaid** [comment]
+1

- P5 tests OK. (thanks @antoniovagnerini )
- spurious differences seen from unstable `WF 12834.7` (open issue #39803 )
- @Dongwoon77 , do you want us to deploy this online now for data-taking ?

**Comment by Dongwoon77** [comment]
> +1
> 
> * P5 tests OK. (thanks @antoniovagnerini )
> * spurious differences seen from unstable `WF 12834.7` (open issue [spurious differences in outputs of Run-3 wfs `*.7` #39803](https://github.com/cms-sw/cmssw/issues/39803) )
> * @Dongwoon77 , do you want us to deploy this online now for data-taking ?

Hi @tjavaid.

Yes, we want to deploy.

Thank you.
Dongwoon.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
