### PR TITLE
Fix HLT Validation tests [121X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix HLT Validation tests [121X]

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Partial backport of #36878
Needed to make HLT Validation tests work after confdb update

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #36878

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
