### PR TITLE
[12_4_X] Release dependent modules only after the worker has finished for scheduled modules

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of #39245. Fixes a rare scheduling bug that was observed at the HLT in https://github.com/cms-sw/cmssw/issues/39064 (that was first mitigated in https://github.com/cms-sw/cmssw/pull/39211).

#### PR validation:

Original development. The reproducer I mentioned in https://github.com/cms-sw/cmssw/issues/39064#issuecomment-1228755900 succeeds with this change. Framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
enable threading

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
All the comparison differences are in 9.0.

**Comment by makortel** [comment]
test parameters:

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The failure in 138.5 was
```
23-Sep-2022 18:59:01 CEST  Closed file file:step2.root

...

Thread 1 (Thread 0x2b0b95aba1c0 (LWP 26318) "cmsRun"):
#3  0x00002b0b9d249a0b in sig_dostack_then_abort () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b0b92f28615 in TBufferIO::Reset() () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libRIO.so
#6  0x00002b0b929d543b in TBasket::WriteReset() () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#7  0x00002b0b929e2f58 in TBranch::WriteBasketImpl(TBasket*, int, ROOT::Internal::TBranchIMTHelper*) () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#8  0x00002b0b929e3bf6 in TBranch::FlushBaskets() () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#9  0x00002b0b92a526a2 in TTree::FlushBasketsImpl() const::{lambda()#1}::operator()() const () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#10 0x00002b0b95035084 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned int>, tbb::detail::d1::parallel_for_body_wrapper<std::function<void (unsigned int)>, unsigned int>, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libImt.so
#11 0x00002b0b93de5bec in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x2b0bea8f3a00, this=0x2b0b967ec900) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/task_dispatcher.h:322
#12 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x2b0b967ec900) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/task_dispatcher.h:463
#13 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/task_dispatcher.cpp:168
#14 0x00002b0b95032f27 in tbb::detail::d1::task_arena_function<ROOT::TThreadExecutor::ParallelFor(unsigned int, unsigned int, unsigned int, std::function<void (unsigned int)> const&)::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libImt.so
#15 0x00002b0b93dd495e in operator() (__closure=<optimized out>) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/arena.cpp:771
#16 tbb::detail::d0::try_call_proxy<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> >::on_completion<tbb::detail::r1::isolate_within_arena(tbb::detail::d1::delegate_base&, intptr_t)::<lambda()> > (on_completion_body=..., this=<optimized out>) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/../../include/oneapi/tbb/detail/_template_helpers.h:230
#17 tbb::detail::r1::isolate_within_arena (d=..., isolation=<optimized out>) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/arena.cpp:772
#18 0x00002b0b95032cb3 in tbb::detail::d1::task_arena_function<ROOT::TThreadExecutor::ParallelFor(unsigned int, unsigned int, unsigned int, std::function<void (unsigned int)> const&)::{lambda()#1}, void>::operator()() const () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libImt.so
#19 0x00002b0b93dd40eb in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...) at /data/cmsbld/jenkins/workspace/jenkins-test-bootstrap/toolconf/BUILD/el8_amd64_gcc10/external/tbb/v2021.5.0-e966a5acb1e4d5fd7605074bafbb079c/tbb-v2021.5.0/src/tbb/arena.cpp:698
#20 0x00002b0b9503466d in ROOT::TThreadExecutor::ParallelFor(unsigned int, unsigned int, unsigned int, std::function<void (unsigned int)> const&) () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libImt.so
#21 0x00002b0b92a53a10 in TTree::FlushBasketsImpl() const () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#22 0x00002b0b92a548db in TTree::AutoSave(char const*) () from /cvmfs/cms-ib.cern.ch/nweek-02751/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_4_X_2022-09-23-1100/external/el8_amd64_gcc10/lib/libTree.so
#23 0x00002b0bf2af3a3c in edm::RootOutputFile::finishEndFile() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libIOPoolOutput.so
#24 0x00002b0bf2ad1085 in edm::PoolOutputModule::finishEndFile() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libIOPoolOutput.so
#25 0x00002b0bf2ad136b in edm::PoolOutputModule::reallyCloseFile() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libIOPoolOutput.so
#26 0x00002b0b925dc1a5 in edm::Schedule::closeOutputFiles() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libFWCoreFramework.so
#27 0x00002b0b925032dd in edm::EventProcessor::closeOutputFiles() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libFWCoreFramework.so
#28 0x00002b0b925113e2 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/39484/27751/CMSSW_12_4_X_2022-09-23-1100/lib/el8_amd64_gcc10/libFWCoreFramework.so
```
Maybe a glitch?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@smuzaffar Are the tests stuck or does the machinery have lot's of load?

**Comment by smuzaffar** [comment]
@makortel , there is bug in bot that if a test was previously run ( in this case theading) and then removed for later run the bot keeps the `commit status check` pending. It is on my to do list to fix this issue. For now I force set the status and PR results should be available now

**Comment by makortel** [comment]
+1

Comparisons are clean in single-threaded tests.

**Comment by smuzaffar** [comment]
> @makortel , there is bug in bot that if a test was previously run ( in this case theading) and then removed for later run the bot keeps the `commit status check` pending. It is on my to do list to fix this issue. For now I force set the status and PR results should be available now

@makortel , bot has been fixed to properly set the commit status checks.

**Comment by perrotta** [comment]
+1

**Pull request merged**
