### PR TITLE
Have Geometry/DTGeometryBuilder test ignore irrelevant diffs

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

When doing the diff, ignore any framework or irrelevant module outputs.

#### PR validation:

The changed unit test passes and no longer reports any differences.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This unit test is causing a false positive for #30144

**Comment by ianna** [comment]
@Dr15Jones - I think, it was fixed in https://github.com/cms-sw/cmssw/pull/30093

**Comment by smuzaffar** [comment]
@ianna , this is still failing in DEVEL IBs where we have https://github.com/cms-sw/cmssw/pull/30145 from @Dr15Jones

**Comment by ianna** [comment]
@smuzaffar - does DEVEL IB include #30093?

**Comment by Dr15Jones** [comment]
> @smuzaffar - does DEVEL IB include #30093?

Yes, it is. If I understand the change in that pull request, it just upped the number of differences that were being tolerated. My change actually drops the differences to 0. With my change, we could require that no changes are seen and then catch all problems.

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @ianna sorry, the solution I had adopted for MTD was to simply drop the MessageLogger statistics printout in the comparison used by the unit test. Do you see any drawback in this approach?

**Pull request merged**
