### PR TITLE
Towards first hlt menu for 2016 (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Towards first hlt menu for 2016 (80X)
Backport of #14226

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need to wait until #14281 (GTs) is integrated!

**Comment by perrotta** [comment]
Please do not waste your time inspecting this PR: this is meant to be signed by HLT only, and it actually only updates 19 files in our package. However, the commands I normally use to rebase it (to CMSSW_8_0_6, in this case) fail: just wait that I understand why, and the request of your signature will disappear from here...

**Comment by perrotta** [comment]
Please @Martin-Grunewald : close, as it is replaced by #14325

**Comment by perrotta** [comment]
-1

**Pull request closed without merging**
