### PR TITLE
CTPPS: updated DQM for 2018 data taking

### PR DESCRIPTION
**Pull request by nminafra**
This PR updates the DQM:
- Tomography is now using pixel detectors instead of strip (not installed anymore)
- Efficiency of diamond channels wrt to other diamonds and wrt to pixel detectors
- Increased flexibility of hitmaps: the horizontal position of diamond (horizontalShiftOfDiamond_) is retrieved from the geometry and this value is subtracted such that the hitmaps are always starting from x=0. In a similar way, the offset with pixel detectors is used to properly display the tomography. 
- Updated tests to cope with PR 22264

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by nminafra** [comment]
The errors are due to the fact that in those runs the pixel detectors were not included yet in 2016. 
I've updated the PR with a "try/catch" that should never happen: pixel detectors are installed now.
Moreover, it is in dqmBeginRun (it is needed to find the offset between pixel and timing, to optimize how the tomography is displayed), so in case pixel disappear from the geometry, it will be called only once and it won't impact too much on the performance.
At the same time I've removed any reference to the strip detectors to avoid similar problems in the future.

Please, let me know if this solution is fine or if there is a better way to deal with this.
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
hold

waiting for the comment to be addressed

**Comment by nminafra** [comment]
@fabiocos Sorry Fabio: which comment?

**Comment by fabiocos** [comment]
@nminafra please see above, the use of try - catch is violating the code rules, could you refactor the code?

**Comment by nminafra** [comment]
@fabiocos Thanks, the problem with it is that the exception is thrown by:
https://github.com/cms-sw/cmssw/blob/b8df08c90e304af46c7b7da507fdf2b9072d7eae/Geometry/VeryForwardGeometryBuilder/src/CTPPSGeometry.cc#L92

What I propose is to:
1) modify to catch only cms::Exception
2) modify CTPPSGeometry
3) use a parameter from DQM/CTPPS/python/ctppsDiamondDQMSource_cfi.py

Which one works best for you?

**Comment by fabiocos** [comment]
@nminafra if you are trying to access a sensor that is not in the map in the geometry you get an exception, and that is correct. But why having a try-catch construct on the DQM side? Are you expecting to ask systematically for a non existing sensor and use try-catch instead of a correct map?

**Comment by nminafra** [comment]
@fabiocos You are correct, that's why I didn't bother too much about the try catch: the error was on a run from 2016. Since 2017 we have the pixel installed, therefore this exception will never be risen in the online DQM, as pointed out in previous comments.
Thanks

**Comment by nminafra** [comment]
@fabiocos I removed the try catch and now I check that the run number is > 300 000.
As said, for the DQM online this condition will always be true, but it will avoid asking for pixel geometry before mid 2017.
I hope this solution is better.
Thanks a lot!

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
DQM experts are fine with the new version of the code.

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+1

**Pull request merged**
