### PR TITLE
Update DQM beam clients playback machine type check

### PR DESCRIPTION
**Pull request by pmandrik**
#### PR description:

update DQM beam* clients to use available config data to check if machine is playback or production instead of path to the CMSSW folder (which is unsafe).

#### PR validation:

Tested at P5 playback DQM

### CODE REVIEW

**Comment by pmandrik** [comment]
please test

**Comment by francescobrivio** [comment]
Hi @pmandrik,
Thanks a lot for this!
I have only two questions/comments:
- Question: what happens when running locally (e.g. on lxplus)?
- Comment: you will also need a 12_4_X backport right? Deadline for 12_4_0 is next Tuesday. I can help opening the 12_4_Xbackport if needed, just let me know!

**Comment by pmandrik** [comment]
Hi, @francescobrivio , locally at the lxplus process.isDqmPlayback.value is False and process.isDqmProduction.value should be False too. Thank you for the reminder, I'll create backport for 12_4_X when this one will be approved. Backport for 12_3_X is just requred for testing and ongoing operations.

**Comment by francescobrivio** [comment]
> Hi, @francescobrivio , locally at the lxplus process.isDqmPlayback.value is False and process.isDqmProduction.value should be False too. 

Perfect thanks Petr! Then I'm fine with the changes proposed in this PR!

> Thank you for the reminder, I'll create backport for 12_4_X when this one will be approved. Backport for 12_3_X is just requred for testing and ongoing operations.

When are you planning to test this in P5?

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@pmandrik please also backport this to 12_4_X

**Comment by francescobrivio** [comment]
> @pmandrik please also backport this to 12_4_X

@qliphy @pmandrik please see #38312

**Comment by pmandrik** [comment]
> > @pmandrik please also backport this to 12_4_X
> 
> @qliphy @pmandrik please see #38312

Hi, thank you for the help!

**Pull request merged**
