### PR TITLE
Run3-gex105D Make use of ESGetToken in DetectorDescription/OfflineDBLoader

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in DetectorDescription/OfflineDBLoader

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda To test the changes in`OutputDDToDDL.cc`, do:
```
cmsRun CondTools/Geometry/test/writehelpers/geometryExtended2021_writer.py
```
A big XML file should result.

Note that neither `runTheMatrix` nor the PR tests exercise any of the code changed in this PR.

**Comment by bsunanda** [comment]
@cvuosalo I believe it needs the big xml file and makes myfile.db. It runs OK

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
