### PR TITLE
Backport of #14179: Speed up Jet Producer for HLT

### PR DESCRIPTION
**Pull request by makortel**
This PR backports #14179 from CMSSW_8_1_X to CMSSW_8_0_X. Original description by @VinInn:

> factor 2 speed up mostly by inlining area computation.
> Solid 0.6% total speedup of HLT at PU22.
> The JetProducer is in the need of more cleanup
> (and tower revertexing is still utterly slow)
> A more serious speedup could be obtained applying a cutoff to the jet energy...
> 
> No regression expected offline as the code in question runs only at HLT...

Tested in CMSSW_8_0_14, no changes expected in RECO quantities in there either.

@fwyzard @gennai @VinInn @slava77

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Timing tests are in progress...

**Comment by fwyzard** [comment]
tracked at #15151

**Comment by cvuosalo** [comment]
HLT/RECO timing tests in progress...

**Comment by cvuosalo** [comment]
An HLT timing test was performed using a config provided by TSG and run on file /store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/Timing/run276935/HLTPhysics_Run276935_LS80-220.root. The PR was compared to baseline CMSSW_8_0_14.

CPU time shrank by  about 1%. The Jet Producer showed improvement:
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -0.526124      -0.16%         7.77 ms/ev ->         4.53 ms/ev hltAK4PFJetsForTaus
   -0.520573      -0.16%         7.96 ms/ev ->         4.67 ms/ev hltAK4PFJets
   -0.377638      -0.07%         4.37 ms/ev ->         2.98 ms/ev hltAK4CaloJets
  ---------- ------------     --------                  ----       ------------
Job total:  2.02722 s/ev ==> 2.00935 s/ev
```
Another measure of the mean time to process an event also shows a 1% improvement:

[HLT_Validation_Plot.pdf](https://github.com/cms-sw/cmssw/files/379170/HLT_Validation_Plot.pdf)

**Comment by slava77** [comment]
On 7/22/16 3:29 PM, Carl Vuosalo wrote:
> An HLT timing test was performed using a config provided by TSG and run
> on file
> /store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/Timing/run276935/HLTPhysics_Run276935_LS80-220.root.
> The PR was compared to baseline CMSSW_8_0_14.
> 
> CPU time shrank by about 1%. The Jet Producer showed improvement:
> 
> |delta/mean delta/orJob original new module name
>  ---------- ------------
> -------- ---- ------------ 
> -0.526124 -0.16% 7.77 ms/ev -> 4.53 ms/ev hltAK4PFJetsForTaus
> -0.520573 -0.16% 7.96 ms/ev -> 4.67 ms/ev  hltAK4PFJets 
> -0.377638 -0.07% 4.37 ms/ev -> 2.98 ms/ev hltAK4CaloJets
> ---------- ------------ -------- ---- ------------ 

> Job total: 2.02722
> s/ev ==> 2.00935 s/ev |


This looks like a count per running module.
Could you please get the numbers per event.
(jet clustering doesn't have any massive initialization. So, just the
job report totals would suffice).

Thank you.

**Comment by cvuosalo** [comment]
+1

For #15226 c7a2488539e4fe99a20ffbe5b638046d1c16c351

Speeding up the jet producer for HLT. There should be no change in monitored quantities. 

#14179 is the 81X version of this PR , and it was included 810pre4.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-07-17-2300 show no significant differences, as expected. A test of workflow 25202.0_TTbar_13 with 70 events against baseline CMSSW_8_0_14 also shows no significant differences. An HLT timing test described above shows about a 1% improvement in timing. Corrected per-module timing measurements (compared to those shown above) also show an overall 1% improvement:

```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -0.520574      -0.21%         0.85 ms/ev ->         0.50 ms/ev hltAK4PFJets
   -0.377634      -0.23%         1.19 ms/ev ->         0.81 ms/ev hltAK4CaloJets
  ---------- ------------     --------                  ----       ------------
Job total:  0.162549 s/ev ==> 0.161243 s/ev
```

**Comment by slava77** [comment]
@cvuosalo 
how do we get an overall 1% improvement from the two modules time change?
They show 0.35 +0.38 ms/ev gain, compared to the total time of 0.16 s/ev, it is just under 0.5%

**Comment by cvuosalo** [comment]
@slava77: Yes, the total of the per-module times show a 0.4% improvement in timing. The overall times (including in this plot https://github.com/cms-sw/cmssw/files/379170/HLT_Validation_Plot.pdf) show about a 1% improvement, but the bulk of that might just be noise.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
