### PR TITLE
L1T DQM migrate modules to DQMGlobalEDAnalyzer - part2

### PR DESCRIPTION
**Pull request by thomreis**
Migrate L1T DQM modules to DQMGlobalEDAnalyzer.
- L1TStage2EMTF
- L1TdeStage2EMTF
- L1TStage2CaloLayer2
- L1TdeStage2CaloLayer2

Part 1 is in PR #21844

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
hold

We need to migrate a few modules to new DQM... Otherwise, this might cause crashes.
See issue: https://github.com/cms-sw/cmssw/issues/21880

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

The error seems unrelated.

**Comment by thomreis** [comment]
please test

Errors were two file open errors.

**Comment by thomreis** [comment]
please test

Again two FallbackFileOpenErrors.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
@thomreis @dmitrijus could you please clarify the status of this PR?

**Comment by thomreis** [comment]
This PR can be closed as it is currently not needed anymore. In case some of the L1 DQM is going to run at the HLT level we can reopen it.

**Pull request closed without merging**
