### PR TITLE
bsunanda:Phase2-hgx26

### PR DESCRIPTION
**Pull request by bsunanda**
Rebuild changes for HGCal

### CODE REVIEW

**Comment by pfs** [comment]
@vandreev11 @pfs @lgray Watch this important update from Sunanda

**Comment by fratnikov** [comment]
I am getting plenty of messages like:

%MSG-w CaloHitResponse:  MixingModule:mix 29-Jan-2015 18:55:21 CET  Run: 1 Event: 9
No Calo cell found for ID1158694960 so no time-of-flight subtraction will be done

on DIGI step. Looks like some inconsistency. Is it?

**Comment by lgray** [comment]
In the past this has always been indicative of geometry bugs... @bsunanda please give a look?
@fratnikov could you please provide him some example events?

**Comment by fratnikov** [comment]
on RECO step:

----- Begin Fatal Exception 29-Jan-2015 18:58:28 CET-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing run: 1 luminosityBlock: 1
   [1] Running path 'reconstruction_step'
   [2] Calling beginLuminosityBlock for module PFClusterProducer/'particleFlowClusterHGCEE'
Exception Message:
No data of type "HGCalGeometry" with label "HGCalHEScintillatorSensitive" in record "IdealGeometryRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------

This is surprising, as naively "particleFlowClusterHGCEE" module should
not care of "HGCalHEScintillatorSensitive" geometry.

@lgray Is this expected, and corresponding PF modifications will follow in another PR?

**Comment by lgray** [comment]
@fratnikov This is expected in RECO step for now. I'll produce a patch over the weekend.

**Comment by fratnikov** [comment]
@bsunanda The test is "runTheMatrix.py -w upgrade -l 13261"

**Comment by lgray** [comment]
@fratnikov Unless there is some standardization of random number seeds across machines, please provide the files and event numbers.

**Comment by fratnikov** [comment]
hcalupgradedataframessorted_simhcalunsuppresseddigis_hbheupgradedigicollection_digi2raw obj obj id ieta
This is iEta distribution of produced HBHE digis. HE-rebuild digis are supposed to be here, but they are not. Are HE digis supposed to be produced in V6?

**Comment by fratnikov** [comment]
@lgray the "No Calo cell" message is in 7 of 10 produced single pion events, so any random seed should reproduce this message.

@bsunanda The output contains a lot of debugging stuff, e.g. more than 5K per 10 events like 

getHCID: input 1:4:47:3:6 output 4:47:3
getHCID: input 1:4:47:3:6 output 4:47:3

Could this be cleaned up?

**Comment by fratnikov** [comment]
@bsunanda @pfs @lgray What's the plan? Is this PR going to be repaired?
I guess it is a show stopper for GEN-SIM production with v6 HGC geometry

**Comment by pfs** [comment]
This PR has high priority and should be cleared asap. SimHits are produced for HErebuild so in principle this is on the right path for a GEN-SIM production, but we need to be fully sure that the next steps will be ok as well: i.e. hits align geometrically, DIGIs and RecHits are produced.
@bsunanda Could you take some time to remove the debugging stuff?
@fratnikov  Is the DIGI failing due to some mismatch of the DetIds? Do you know who's the HCAL expert who could help us on this front?
@vandreev11 @lgray

**Comment by fratnikov** [comment]
@pfs @bsunanda 
Digitizer doesn't find cell id in the geometry, though it looks to be a legitimate HE cell id. I'd speculate that the entire HE geometry is not loaded and thus available on DIGI step. If this is a geometry configuration
problem indeed, then Sunanda is the expert.

**Comment by mark-grimes** [comment]
I've lost track of this pull request.  Is it still required or has it been superseded?

**Comment by vandreev11** [comment]
@mark-grimes I believe it is superseded, but it is better if Sunanda @bsunanda confirms

**Comment by bsunanda** [comment]
Hi Mark, Let me check the content of Phase2-hgx26 and see if they has been superseded. I shall let you know.
________________________________

**Comment by fratnikov** [comment]
@bsunanda I guess this PR may be safely closed. Should it be?

**Comment by ktf** [comment]
Closing. Complain / reopen if not ok.

**Pull request closed without merging**
