### PR TITLE
remove errant Eras.py imports

### PR DESCRIPTION
**Pull request by kpedro88**
Modifiers should be implemented from their own cff files, not from `Configuration.StandardSequences.Eras` (to reduce unnecessary dependencies). See #14895.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19732	e183ad7
- technical
- jenkins tests pass

@smuzaffar @kpedro88 is there a way to implement a code rule that would prevent direct ```from Configuration.StandardSequences.Eras import eras``` ?

**Comment by kpedro88** [comment]
@slava77 I don't know of a way in Python to prevent imports, but there's some ongoing discussion in #14895 about permanent ways to avoid this problem in the future

**Comment by slava77** [comment]
On 7/17/17 11:42 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> I don't know of a way in Python to
> prevent imports, but there's some ongoing discussion in #14895
> <https://github.com/cms-sw/cmssw/issues/14895> about permanent ways to
> avoid this problem in the future

we have QA scripts that parse parts of the code.
While the import can not be prevented at execution level,
it can still be noted by jenkins in the code rules or in a similar QA check.

**Comment by davidlange6** [comment]
merge
one can always write a script to check for anything..but then you have to debug and maintain the script:)

**Pull request merged**
