### PR TITLE
HGCal L1 Trigger Framework

### PR DESCRIPTION
**Pull request by lgray**
This pull request defines packages for and implements much of the basic functionality for the HGCal L1 trigger emulator.

I will issue pull requests to CMS bot to add the packages to the watchlists.

@jbsauvan @amarini @mulhearn

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Unit test failures not related to PR. Waiting for IB to update.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild wake up!

**Comment by lgray** [comment]
@mulhearn @civanch please take a look, the code as-is is ready for review. Some of the test scripts need to be resurrected in 80X. Unless you require it for this one, that will come in a later PR.

**Comment by civanch** [comment]
+1

**Comment by mulhearn** [comment]
I think this might needs some re-factorization to reduce the amount complexity, at least at top level.  The DataFormats, which are the *primary* *interface* to the rest of CMSSW, appear to be way too complicated.  The L1T design guideline for the upgrade suggests that DataFormats should be "stupid", with no built-in unpacking features.  I think the flexibility that is currently in your Data Formats is better put elsewhere, either in an unpacking role, or a firmware algorithm emulation role, all of which can be versioned to handle different cases.  But its quite possible I don't quite understand what you are trying to accomplish, so maybe best to discuss in person.

**Comment by lgray** [comment]
Thanks for having a look! Happy to talk in person. The main problem we have
to overcome, leading to the complication of the dataformats is that we do
not have a set firmware algorithm yet for encoding/decoding, and so need a
dataformat that simply represents a bit stream and the packing/unpacking is
provided to it. I've just landed in GVA, and I'm happy to meet once at cern.

(Sent from my Nexus 6)

**Comment by lgray** [comment]
@mulhearn Pursuant to our discussion yesterday, we came to the agreement that the present code provides a smooth way to eventually move to "unpacked" dataformats for the digis once we know the nature of them. 

This is because a "concrete" data format is used within the present very abstract code.
An example of this can be seen in https://github.com/lgray/cmssw/blob/hgc_trigger_fwk_80X/L1Trigger/L1THGCal/interface/fe_codecs/HGCalBestChoiceCodecImpl.h.

Over time, these implementations can be turned into real dataformats, and an evolution of the digi schema can follow from that.

For now, given that the setup of the trigger is relatively unknown, keeping an abstract interface is very beneficial to the project, and that it is OK to keep it for now. 

A +1 would be appreciated! Thanks. :-)

**Comment by mulhearn** [comment]
Noting that we also discussed the need to avoid the abstract version of the DataFormat, or the supporting CodeEx's, gaining any additional functionality that then becomes used throughout the code, making it difficult to revert to a simple concrete instance when things settle down.

**Comment by mulhearn** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 would appreciate that this is integrated for next week. Thanks!

**Comment by davidlange6** [comment]
@lgray @degano 
could you move cellsToTriggerCellsMap.txt to a data external. Thanks!

**Comment by lgray** [comment]
@davidlange6 Will get to it today.

**Comment by smuzaffar** [comment]
@degano , can you please take care of the cellsToTriggerCellsMap.txt data file?

**Comment by lgray** [comment]
Hi Guys, finally have some time to work on this.
I'll take care of the externals request.

**Comment by lgray** [comment]
@degano can you make an externals repository for L1Trigger/L1THGCal? Thanks!

**Comment by smuzaffar** [comment]
@lgray ,L1Trigger/L1THGCal is available here https://github.com/cms-data/L1Trigger-L1THGCal 
If you send me the  cellsToTriggerCellsMap.txt  data file then I cam dump that in it and update the cmsdist to include this data external

**Comment by smuzaffar** [comment]
@lgray , any idea where is cellsToTriggerCellsMap.txt?

**Comment by lgray** [comment]
It's in afs at the moment. I'll make a pull request to the new external
repo later this morning (Chicago time).

-L

**Pull request closed without merging**
