### PR TITLE
Combined updates for SiStrip Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
Several updates to the SiStrip Payload Inspector:
   * add the zero pedestals fraction plot to SiStrip pedestals; 
   * add the Payload inspector class for the `SiStripConfObject` `CondFormat`;
   * add auxiliary class to store averaged conditions per APV and Module; 
   * add value and comparison plots averaged per Strip, APV and Module for Pedestals and Noise;
   * update `README` and unit tests.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
The error in the add-on test in the previous round of tests, looks spurious as there is a segfault ending in nowhere: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22969/27511/addOnTests/fastsim2/cmsDriver.py_TTbar_13TeV_TuneCUETP8M1_cfi_--conditions_auto:run2_mc_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,RECOBEFMI.log 

The proposed changes are not meant to affect any workflow, so I just rebased on top of the latest `CMSSW_10_2_X` IB to remove the state of error.

Please @ggovi re-trigger the tests.

**Comment by mmusich** [comment]
... and again:
```
%MSG
%MSG-e MissingProduct:  HybridClusterProducer:uncleanedHybridSuperClusters  19-Apr-2018 12:03:44 CEST Run: 1 Event: 53
could not get a handle on the EcalRecHitCollection!
%MSG
----- Begin Fatal Exception 19-Apr-2018 12:03:44 CEST-----------------------
An exception of category 'fastsim::ParticleManager' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 53 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
unknown pdg id: 9010221
----- End Fatal Exception -------------------------------------------------
```

@fabiocos @smuzaffar can something be done for this recurring error? It has nothing to do with the proposed changes...

**Comment by mmusich** [comment]
sorry for being insistent, but is there any hope of getting this tested?

**Comment by fabiocos** [comment]
@mmusich the crash is an annoying long-standing "feature" of fastsim that has nothing to do with this PR as far as I can see. For my understanding: in which test workflow if any is this code supposed to run, apart for the standalone test code in the PR itself?

**Comment by mmusich** [comment]
> For my understanding: in which test workflow if any is this code supposed to run, apart for the standalone test code in the PR itself?

@fabiocos: indeed no other workflow is involved

**Comment by fabiocos** [comment]
@ggovi could you please check and sign in case? The addOn failure has nothing to do with this PR

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
