### PR TITLE
[125X] Improve unprotected areas of GSF code to avoid segfault

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/40084

Addresses https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1316832648

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by swagata87** [comment]
@cmsbuild please test

last time it failed as tests timed out..

**Comment by perrotta** [comment]
+1
- This is a verbatim backport of #40084, which was already signed by @cms-sw/reconstruction-l2 
- Let have it merged, assuming that reco would also sign it, so that it can enter in the 1100 IBs

**Comment by perrotta** [comment]
merge

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
