### PR TITLE
PPS Dump to SQLite only one record (mask or mapping)

### PR DESCRIPTION
**Pull request by brzozia**
#### PR description:

This PR is makes a small addition to work started in PR  #42471 concerning migration of all PPS detectors' mappings from XML to CondDB.

In this PR are updates of: 

- plugin which creates SQLite files based on XML files ([CondTools/CTPPS/plugins/WriteCTPPSTotemDAQMappingMask.cc](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:mapping-dump-update?expand=1#diff-140c17cd5e469a3e3692f7f3e397d10512b8b9e95d1038ac986f3737902f8475))
- plugin which reads SQLite/XML file and dumps data to text file ([CalibPPS/ESProducers/plugins/WriteTotemDAQMapping.cc](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:mapping-dump-update?expand=1#diff-276299009e7ad4e9336945c66d7cfcb5b6ec85d7835707bcd3096bcfb382c7dc))
- configs/scripts used for tests

Previously both AnalysisMask and DAQMapping were read from XML files.
Based on that TotemReadoutRcd and AnalysisMaskRcd records were created and dumped to one SQLite file.

**This PR makes possible to dump only one record to SQLite file (using WriteCTPPSTotemDAQMappingMask plugin).**
Also  adds option to read and dump only one record from SQLite/XML files (using WriteTotemDAQMapping plugin).

#### PR validation:

To validate this PR I used a test I made for PR  #42471 ([CondTools/CTPPS/test/test_XML_to_SQLite_mapping.sh](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:mapping-dump-update?expand=1#diff-1dba015306a25198f8fc530bec2f491c24af99f0b3fafb31d66dba92e8df90cd)).

In the test firstly SQLite files are created based on XML files. In each SQLite file is only one type of record (TotemReadoutRcd or AnalysisMaskRcd).
Then data is read from SQLite files and dumped to text files.
Then data is read from XML files and dumped to text files.
Then corresponding text files are compared.

The results show that the data is the same in XML and SQLite, so the migration from XML to SQLite was successful.

---
@grzanka for your attention

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by rsreds** [comment]
I tested the PR on IB and run the same script you linked. Results are the same for me.

Small note on WriteCTPPSTotemDAQMappingMask.cc, as a possible future improvement (since it's not from this PR):
I would remove
https://github.com/cms-sw/cmssw/blob/0f65a00011e9530a6673418532c3ecaf71ef8588/CondTools/CTPPS/plugins/WriteCTPPSTotemDAQMappingMask.cc#L46-L47
this should require only to change the following lines
https://github.com/cms-sw/cmssw/blob/0f65a00011e9530a6673418532c3ecaf71ef8588/CondTools/CTPPS/plugins/WriteCTPPSTotemDAQMappingMask.cc#L51-L55
by changing `string` to `std::string` (I tested it on my work area)

**Comment by perrotta** [comment]
+1
- Based on the checks made by @rsreds reported in https://github.com/cms-sw/cmssw/pull/42879#issuecomment-1746288968

**Comment by rappoccio** [comment]
+1

**Pull request merged**
