### PR TITLE
Diamond sampic dqm

### PR DESCRIPTION
**Pull request by ChrisMisan**
**Overview:**
Goal of this PR is to deliver a new DQM module for the diamond sampic flow. Said module contains offline and online dqm plots which are switched using configuration parameter. 
Existing pixel dqm was serving as a reference for online/offline switch: 
https://github.com/cms-sw/cmssw/blob/master/DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc

Commented plots in DQM module might be re-activated in the future and therefore were not deleted.

**Testing**
Due to lack of data (see #34759) automatic testing of this code is not possible. Manual test  is available at **RecoPPS/test** directory.

**Memory performance**
This is memory consumption for cmsRun process running the DQM module.
image

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @ChrisMisan 
In order to keep track of the DQM developers, can you please add yourself along with your github username to the appropiated e-group here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#CT_PPS
?
Thanks in advance

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by vavati** [comment]
Hi, as specified in the description

Testing
Due to lack of data (see #34759) automatic testing of this code is not possible. Manual test is available at RecoPPS/test directory.

I guess that no RelVal can work

**Comment by slava77** [comment]
> Hi, as specified in the description
> 
> Testing Due to lack of data (see #34759) automatic testing of this code is not possible. Manual test is available at RecoPPS/test directory.
> 
> I guess that no RelVal can work

the error is in the 2016 fastsim workflow due to missing `totemTimingRawToDigi`; is sampic code really supposed to handle the 2016 parts? perhaps some fastsim era modifier is missing?

**Comment by jfernan2** [comment]
The crashes are at step1, before DQM which indeed is not Run for CTPPS.
However there are severla warnings related to the DQM modules:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3cf7ab/19218/llvm-analysis/esrget-sa.txt

**Comment by jan-kaspar** [comment]
Thanks @jfernan2 !

@ChrisMisan Could you please switch to the "token" mechanism, please? Here's an example that you can follow:
  https://github.com/cms-sw/cmssw/blob/master/DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc#L106

**Comment by jpata** [comment]
I was not able to trace down the reason in the available time, but for sure the workflow 135.4 should not be allowed to fail after this PR is merged. @ChrisMisan can you check the CTPPS sequences and try to understand what is going on?

**Comment by ChrisMisan** [comment]
> Thanks @jfernan2 !
> 
> @ChrisMisan Could you please switch to the "token" mechanism, please? Here's an example that you can follow: https://github.com/cms-sw/cmssw/blob/master/DQM/CTPPS/plugins/CTPPSDiamondDQMSource.cc#L106

Sure, already done, if you don't mind, I'll wait with the push until we have some solution for those fails.

**Comment by ChrisMisan** [comment]
>I was not able to trace down the reason in the available time, but for sure the workflow 135.4 should not be allowed to fail after this PR is merged. @ChrisMisan can you check the CTPPS sequences and try to understand what is going on?

This should solve the issue with failed fastSim tests.

**Comment by jfernan2** [comment]
It seems that now you have removed 2261 plots from ALL MC workflows.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-04-1300+3cf7ab/45939/dqm-histo-comparison-summary.html

**Comment by ChrisMisan** [comment]
@jfernan2 seems like a desired outcome of the changes, we did remove a lot of histograms from offline dqm.

**Comment by jfernan2** [comment]
OK @ChrisMisan , I just commented asking for confirmation since you removed them from data workflows too

**Comment by jpata** [comment]
@cms-sw/ctpps-dpg-l2 just to check explicitly: on the reco side it's minimal, totemTimingLocalReco sequences are replaced with diamondSampicLocalReco. Consequently, the totem timing info disappeared from the reco outputs. Is this expected & fine for you?

**Comment by vavati** [comment]
@jpata : yes you are right. The "totem timing" info referred to a special configuration of detectors which was used only for a special run in 2018. Now the DiamondSampic info will be available for any run (assuming that the corresponding read-out works of course)

**Comment by slava77** [comment]
> @cms-sw/ctpps-dpg-l2 just to check explicitly: on the reco side it's minimal, totemTimingLocalReco sequences are replaced with diamondSampicLocalReco. Consequently, the totem timing info disappeared from the reco outputs. Is this expected & fine for you?

To be more specific, the change in the products is
> ROOTFileChecks: Some differences in event products or their sizes found
`    Product missing TotemTimingLocalTrackedmDetSetVector_totemTimingLocalTracks__RECO.`

was there a replacement to `totemTimingLocalTracks` and our reco comparisons just missed the update?
@vavati 
What is the new collection name?

**Comment by vavati** [comment]
It should be "diamondSampicLocalTracks" (as defined in PR34759)
But as there are no suitable data I assume you can't see any track

**Comment by slava77** [comment]
> @jpata : yes you are right. The "totem timing" info referred to a special configuration of detectors which was used only for a special run in 2018. Now the DiamondSampic info will be available for any run (assuming that the corresponding read-out works of course)

which run was it? Or was it a set of runs in a fill.
We have 314276 (matrix wf 136.8562) and 314890 (matrix wf 136.8561) in the IB tests; 314276 is marked as for the RP system.
Does the removal of the `totemTimingLocalTracks` mean that the data reconstruction for that run is incomplete? We usually try to maintain valid configurations for the past physics data, including special configurations.

**Comment by vavati** [comment]
TotemTiming real raw data are available in this range: 319099-319311 
For other runs that collection is empty (no detectors in data taking)
In PR34759 it was defined a confiuration to switch from TotemTiming to DiamondSampic in case old data are needed.
In all runs in RelVal DiamondSampic data are not present (new installation for Run3) so i guess the correposnding collection is not created

**Comment by slava77** [comment]
>  In all runs in RelVal DiamondSampic data are not present (new installation for Run3) so i guess the correposnding collection is not created

the producer should still make an empty collection.
I don't see any info about new products in #34759 tests. 
Also, in that PR I do not see any `keep ` statements in the python files to indicate that the new products should be saved.
If producer names have changed (and if some other PR didn't update the event content), it looks like we may have a bug.

**Comment by ChrisMisan** [comment]
> was there a replacement to totemTimingLocalTracks and our reco comparisons just missed the update?

@slava77 there was no update in terms of data format nor collection name for totemTimingLocalTracks. The only update made in #34759 was to generalize reco code to work with diamonds, outputs remained exactly the same.

**Comment by slava77** [comment]
I'm confused by the two messages about the event content above 

> It should be "diamondSampicLocalTracks" (as defined in PR34759)


> @slava77 there was no update in terms of data format nor collection name for totemTimingLocalTracks. The only update made in #34759 was to generalize reco code to work with diamonds, outputs remained exactly the same.

Note that this PR removes `totemTimingLocalTracks`

**Comment by ChrisMisan** [comment]
> I'm confused by the two messages about the event content above
> 
> > It should be "diamondSampicLocalTracks" (as defined in PR34759)
> 
> > @slava77 there was no update in terms of data format nor collection name for totemTimingLocalTracks. The only update made in #34759 was to generalize reco code to work with diamonds, outputs remained exactly the same.
> 
> Note that this PR removes `totemTimingLocalTracks`

Sorry, I'll try to explain as I understand the issue:

- #34759 didn't remove totemTimingLocalTracks - this is what I was relating to

- #34759 introduced new producer - diamondSampicLocalTracks but didn't change the ctppsReco

- current PR changed the ctppsReco to diamondSampicLocalTracks and hence the names mismatch in: 
https://github.com/ChrisMisan/cmssw/blob/cea1d1bc4aa7b376b68eb70a34cfb4c7184f438b/RecoPPS/Configuration/python/RecoCTPPS_EventContent_cff.py#L27

**Comment by slava77** [comment]
>     * current PR changed the ctppsReco to diamondSampicLocalTracks and hence the names mismatch in:
>       https://github.com/ChrisMisan/cmssw/blob/cea1d1bc4aa7b376b68eb70a34cfb4c7184f438b/RecoPPS/Configuration/python/RecoCTPPS_EventContent_cff.py#L27

OK, so it sounds like the new product `keep ` should be added

**Comment by jan-kaspar** [comment]
> > ```
> > * current PR changed the ctppsReco to diamondSampicLocalTracks and hence the names mismatch in:
> >   https://github.com/ChrisMisan/cmssw/blob/cea1d1bc4aa7b376b68eb70a34cfb4c7184f438b/RecoPPS/Configuration/python/RecoCTPPS_EventContent_cff.py#L27
> > ```
> 
> OK, so it sounds like the new product `keep ` should be added

Thanks @slava77 for pointing this out! We add the keep statements for the new products from the SAMPIC readout. On the other hand, I'd like to remove the keep statements for the TOTEM timing products - AFAIK these detectors were only used for a special run in 2018 and are not planned for (routine) use in Run3. Would this removal make sense to you?

**Comment by jan-kaspar** [comment]
> > Thanks @slava77 for pointing this out! We add the keep statements for the new products from the SAMPIC readout. On the other hand, I'd like to remove the keep statements for the TOTEM timing products - AFAIK these detectors were only used for a special run in 2018 and are not planned for (routine) use in Run3. Would this removal make sense to you?
> 
> The question remains a bit confusing to me still. As I clarified in [#35445 (comment)](https://github.com/cms-sw/cmssw/pull/35445#issuecomment-934478209) we still have a workflow (and an underlying assumption that a larger rereco can possibly be needed in the future) to reprocess the 2018 run data. So, as such, the 2018 run data rereco should still be supported. That's unless PPS and PRO groups can clarify/confirm that that data will never be needed for a rereco or some other checks.

Thanks @slava77 , I guess I see your point. So what about the following:
  * we keep the "TOTEM timing" keep statements in EventContent file (they actually don't hurt)
  * we use the Run2_2018 era modifier to keep the "TOTEM timing" modules in the PPS reco sequence?

**Comment by slava77** [comment]
> Thanks @slava77 , I guess I see your point. So what about the following:
> 
>     * we keep the "TOTEM timing" keep statements in EventContent file (they actually don't hurt)
> 
>     * we use the Run2_2018 era modifier to keep the "TOTEM timing" modules in the PPS reco sequence?

@jan-kaspar 
this sounds reasonable to me.
(the era name is likely going to be `ctpps_2018`)
Thank you.

**Comment by jan-kaspar** [comment]
> @jan-kaspar this sounds reasonable to me. (the era name is likely going to be `ctpps_2018`) Thank you.

Yes, you're right, many thanks!

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
This is what we currently observe in 1330.0/step3.root edmDumpEventContents. `totemTimingLocalTracks` are removed and `diamondSampicLocalTracks` are added.

```diff
< edm::DetSetVector<TotemTimingLocalTrack>    "totemTimingLocalTracks"    ""                "RECO"    
---
> edm::DetSetVector<TotemTimingLocalTrack>    "diamondSampicLocalTracks"   ""                "RECO"    
```

**Comment by ChrisMisan** [comment]
I wasn't able to run 136.8562 due to data load error but from what I've seen it was running with ctpps_2018 modifier where diamond sampic should be removed so I hope last commit solved this issue.

**Comment by slava77** [comment]
> I wasn't able to run 136.8562 due to data load error but from what I've seen it was running with ctpps_2018 modifier where diamond sampic should be removed so I hope last commit solved this issue.

did you run on lxplus with `--ibeos` option?
http://cms-sw.github.io/PRWorkflow#before-making-your-pull-request

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- totemTiming replaced with diamondSampic in recoCTPPSTask, corresponding keep statement added
- in reco, we see the totemTimingLocalTracks collection disappear, and diamondSampicLocalTracks appear
- additional workflows for ctpps 136.8562, 136.8561 were also checked and run successfully

**Pull request merged**
