### PR TITLE
HLT menu development for `12_4_X` (6/N) [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2412](https://its.cern.ch/jira/browse/CMSHLT-2412): [PPS] separate Stream+PD for AlCaPPS Express and Prompt
  - [CMSHLT-2414](https://its.cern.ch/jira/browse/CMSHLT-2414): [TRK] increased size of the PixelDigis buffer (GPU reco)
  - [CMSHLT-2409](https://its.cern.ch/jira/browse/CMSHLT-2409): [TSG] increased smart-PS of Scouting Path in ScoutingPFMonitor PD to 1000
  - [CMSHLT-2416](https://its.cern.ch/jira/browse/CMSHLT-2416): [BPH] split ParkingSingleMuon PD and Stream by 3
  - [CMSHLT-2422](https://its.cern.ch/jira/browse/CMSHLT-2422): [TSG] add missing `*TrackPacker` product to `hltEventContentParkingScoutingMonitor`
  - [CMSHLT-2424](https://its.cern.ch/jira/browse/CMSHLT-2424): [HIG] uniform prescales for PNET control triggers
  - [CMSHLT-2417](https://its.cern.ch/jira/browse/CMSHLT-2417): [L1T] added L1T cross-seeds with lower MET thresholds
  - [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250): [PFlow] use depth-based Phase-1 thresholds for HBHE PFRecHits
  - [CMSHLT-2312](https://its.cern.ch/jira/browse/CMSHLT-2312) (part 1): [MUO] update of muon HCAL-isolation working-point
  - [CMSHLT-2418](https://its.cern.ch/jira/browse/CMSHLT-2418) (part 1): [EXO] disabled `HLT_PFMET110_PFJet100_v` (PS=0)

This latest GRun menu requires the latest L1T menu, i.e. [`L1Menu_Collisions2022_v1_3_0`](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/550121d3ea20a0c3d29222304836f10aabb3d3cc/development/L1Menu_Collisions2022_v1_3_0/L1Menu_Collisions2022_v1_3_0.html). It also includes a fix to the ParticleFlow reconstruction, which required an update of the HLT Jet/MET calibrations (see #38916).

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

`12_4_X`

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - enable_tests = gpu
  - pull_requests = #38916

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
At the moment, I can't see the usual DQM bin-by-bin comparison plots, for example at "11634.0 overlay GUI" in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-08-04-2300+0fa187/51986/dqm-histo-comparison-summary.html

I have tried checking other PRs, and I see the same issue (an empty DQM page).

@qliphy (or others), is this a known issue? (or a problem on my end?)

**Comment by missirol** [comment]
Kindly asking @makortel to have a look (I am not sure where/whom to ask).

Re https://github.com/cms-sw/cmssw/pull/38971#issuecomment-1206457795 , is it just me not seeing DQM bin-by-bin plots, or is it an actual issue?

**Comment by makortel** [comment]
@missirol I see an empty DQM GUI page as well. Could you open a separate issue about it? (seems non-trivial-enough to be easier to follow up there than in a "random" PR)

**Comment by missirol** [comment]
Since #38980 isn't solved yet, I checked "by hand" the comparisons for the wfs with most differences, e.g. `11834.0`, and I could not see any particular issue. Differences are rather small, and appear consistent with the change in [CMSHLT-2250](https://its.cern.ch/jira/browse/CMSHLT-2250)+[2312](https://its.cern.ch/jira/browse/CMSHLT-2312), and the update of the HLT PF-hadron calibrations and jet-energy scale corrections in #38916 (more detailed physics validation of these changes was, or will be, done offline by the JME-POG and TSG).

**Comment by missirol** [comment]
+hlt

 - differences in outputs of PR tests are consistent with updates to the `GRun` HLT menu (see [#38971 (comment)](https://github.com/cms-sw/cmssw/pull/38971#issuecomment-1208299230))
 - @cms-sw/orp-l2 , this PR depends on [#38916](https://github.com/cms-sw/cmssw/pull/38916) due to the update of the L1T menu; [#38916](https://github.com/cms-sw/cmssw/pull/38916) should be merged before this PR (and ideally they should be both included in the next IB)

**Comment by qliphy** [comment]
+1

**Pull request merged**
