### PR TITLE
Alpaka-related updates [13.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Various Alpaka-related updates:
  - move `HeterogeneousCore/AlpakaCore/interface/MakerMacros.h` under `alpaka/`
  - rename `alpaka_hip_async` to `alpaka_rocm_async`
  - adopt the "alternative module loading" approach in the Alpaka test

#### PR validation:

All unit tests should pass.

#### PR backport:

Backport of #40771 to CMSSW_13_0_X for 2023 data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #40771

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
