### PR TITLE
JetMET DQM and MET Validation unscheduled mode fix

### PR DESCRIPTION
**Pull request by webermat**
equivalent to 75X PR https://github.com/cms-sw/cmssw/pull/9938
Fix the issues observed in the unscheduled modes for MET Validation and JetMET DQM by cloning modules which are modified later on. As consequence the type1 MET folders will be renamed. Updated the PUJetID producers to the latest version (training still based on 53X though).

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
ciao @webermat 
could you please rebase this one please?

**Comment by deguio** [comment]
ciao @webermat 
could you please rebase this one please?

**Comment by webermat** [comment]
superseeded by PR #10289

**Pull request closed without merging**
