### PR TITLE
Fix GEM chamber mapping inside EMTF unpacker.

### PR DESCRIPTION
**Pull request by tahuang1991**
With this fix, EMTF unpacker could correctly unpacker GEM trigger data and EMTF could correctly use them if GEM data is enabled for usage.

#### PR description:
1. change the GEM chamber mapping in EMTF packer when 
the unpacker unpacks the GEM trigger data readout by EMTF (EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockGEM.cc and EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFUnpackerTools.cc)
3. in GEM part of EMTF unpacker, GEM layer for the GEM trigger data is derived from GEM cluster ID: 0-3 and 8-11 are for layer 1 while 4-7 and 12-15 are for layer 2

#### PR validation:
Patrick did intense studies to verify the GEM chamber mapping in EMTF unpacker with the fix.  As GEM sends the trigger data to both CSC OTMB and EMTF, and the GEM-CSC are linked by one to one pair,  Patrick compared the GEM trigger data unpacked form CSC OTMB data and from EMTF unpacker. The comparison would check the GEM chamber number and layer for the same GEM clusters found in CSC OTMB data and EMTF data. 

[Patrick_gemchambermatching617.pdf](https://github.com/user-attachments/files/15922165/Patrick_gemchambermatching617.pdf)

The GEM chamber mapping based on the GEM-EMTF linking system is provided by GEM experts:
https://docs.google.com/spreadsheets/d/1bWUo22-ukRrHlQgXDRnll3qRam2v46FjfmIOsgamgHk/edit?gid=0#gid=0

### CODE REVIEW

**Comment by epalencia** [comment]
please test

**Comment by aloeliger** [comment]
@tahuang1991 Is this a new mapping, or a bugfix for an existing one?

**Comment by tahuang1991** [comment]
> @tahuang1991 Is this a new mapping, or a bugfix for an existing one?

It is a bugfix.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
