### PR TITLE
mkFit updates aiming to improve pixelLess iteration and related

### PR DESCRIPTION
**Pull request by slava77**
Motivated by observed inefficiency in the pixelLess iteration track building for low-pt displaced tracks, several features/bugs were fixed and improvements to the algorithm were added:
- consistently sort seeds in iterations without seed merging
- fix handling of candidates with overlapping hits
- make sure that Kalman updates in the barrel stay on the update plane
- fix a propagation condition check bug in propagation to radius  calculation of several Jacobian elements
- fix functions to count the number of matched hits and layers (used in pixelLess and detachedTriplet trajectory filtering)
- explicitly account for the layer thickness in the endcap to determine the phi window to preselect hits (active only for the pixelLess iteration now)
- relax the number of hit requirement for displaced track candidate filter in the pixelLess (endcaps only)
- disable track candidate DNN selection in the pixelLess iteration
- modify seed merging logic for the lowPtQuad iteration for the future developments (this iteration is not yet in the mkFit defaul production setup)

MTV plots, including timing, are available for ttbar relval with pileup  [for the standard DQM selections](https://slava77.web.cern.ch/slava77/mic/CMSSW_12_5_0_pre4-pixmkf /RelValTTbar_14TeV/mtv-mkf5-mkf6-orig-Aug15POG-tr102-08be050) (signal tracks have pt>0.9 GeV in the efficiency plots)  and separately [for signal simtracks selected with pt<0.9 GeV](https://slava77.web.cern.ch/slava77/mic/CMSSW_12_5_0_pre4-pixmkf/RelValTTbar_14TeV/mtv-mkf5-mkf6-orig-Aug15POG-tr102-08be050-lopt for low-pt) 

Expectations:
- slightly longer tracks in all mkFit iterations
- a significant increase in efficiency of reconstructing displaced tracks in the pixelLess iteration
- tracking time goes up by about 3% mainly from longer track fitting time downstream of mkFit, a large fraction of which is from disabling of the candidate DNN selection in the pixelLess iteration

Incremental comparisons are available in https://github.com/trackreco/cmssw/pull/102

Presentation in the Aug 15 TRK POG meeting https://indico.cern.ch/event/1189133/#3-mkfit-updates

Please consider for 12_5_0_pre5

### CODE REVIEW

**Comment by slava77** [comment]
type tracking

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cms-sw/tracking-pog-l2 were there any outstanding questions you would like to be addressed from the meeting yesterday? (I did not have that impression, but just to check)

**Comment by mmusich** [comment]
> were there any outstanding questions you would like to be addressed from the meeting yesterday? 

I don't think there was any specific objection to let this PR be integrated, provided it wasn't reactivating mkFit on the pixelLess iteration by default (that would lead more work). Having said that, I haven't yet looked at the code changes if that's a review that is requested.

**Comment by jpata** [comment]
Thanks. It was more of a generic question than a request for review (which is of course always welcome).

**Comment by jpata** [comment]
+reconstruction
- bugfixes for mkFit
- consequently, changes in tracks and downstream quantities (see the slides in the description for details)
- a slowdown of ~3% in tracking is expected from this

**Comment by perrotta** [comment]
+1
- Modifications in tracking related quantities have been approved

**Pull request merged**
