### PR TITLE
Remove obsolete struct SimDataFormats_Associations

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses the comment https://github.com/cms-sw/cmssw/pull/43913#discussion_r1507913911 by @makortel about ```struct SimDataFormats_Associations``` being obsolete and removable.

#### PR validation:

Code compiles and test wf 24834.0 runs smoothly.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
