### PR TITLE
ZEEMM_13

### PR DESCRIPTION
**Pull request by BetterWang**
ZEEMM_13 for HeavyIon electron/muon validation workflow

### CODE REVIEW

**Comment by bendavid** [comment]
PP relvals have been migrated to pythia8 recently. Perhaps the same should be done for the relevant HI workflows?

**Comment by BetterWang** [comment]
Hi, @bendavid 
This PR is only to test if the HeavyIon muon/electron tracking is working or not.
No precise physics is expected from the generator.
Quan

**Comment by bendavid** [comment]
Yes that's fine, but better to avoid/reduce the use of older tools which are being deprecated...

**Comment by franzoni** [comment]
Hello Quan, I second Josh's comment.
Why don't you take the existing pythia8 zee/zmm gen card :

https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/Configuration/Generator/python/ZEE_13TeV_TuneCUETP8M1_cfi.py
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/Configuration/Generator/python/ZMM_13TeV_TuneCUETP8M1_cfi.py

and add  your zmmee based on those ?
Cheers,
g.

**Comment by BetterWang** [comment]
Dear @franzoni ,
As mentioned earlier, we don't care too much about the physics.
As long as there are electron and muon signals from the generator, it will be fine.
Honestly, I don't know how to turn on both electron and muon and control branching ratio in Pythia8.
We would like to have the current PR in 74X for relval production.
Meanwhile, we will test Pythia8 and update the workflow in the following pre-release.

Thanks,
Quan

**Comment by franzoni** [comment]
Hello @BetterWang

what about starting from : 

/afs/cern.ch/user/f/franzoni/public/4wang/ZEEMM_13TeV_TuneCUETP8M1_cfi_GEN_SIM.py

@bendavid has offered to take a look at give feedback.

**Comment by bendavid** [comment]
Yes indeed, the correct syntax to set Z decays to electrons and muons is
            '23:onMode = off', 
            '23:onIfAny = 11 13',

**Comment by BetterWang** [comment]
Hi @bendavid and @franzoni ,

Thanks for the pythia8 help.
I tested the ZEEMM workflow with pythia8 generator of 100 events.
I got 170 muons and 458 electrons.
Update is committed.
Thanks,

**Comment by franzoni** [comment]
hello @BetterWang, will take a look at the details later.
The expectation is getting 100 per lepton flavour. How have you counted " I got 170 muons and 458 electrons. " ? Which collection are you looking at ?

**Comment by BetterWang** [comment]
Hi @franzoni ,

We need only muon and electrons for relval, and this update confirms both are turned on in Pythia8.
However, ZMM and ZEE branching ratios are different.
So, out of 100 events, I observe 170 muons and 457 electrons in recoGenParticles_hiGenParticles__SIM.obj.pdgId().

Quan

**Comment by bendavid** [comment]
You should count only status 1 electrons and muons, but I agree that if both are there it's probably ok.

(Likely there are more intermediate electrons because there are differences in QED FSR)

**Comment by BetterWang** [comment]
Hi @bendavid ,

Yes, if requiring status()==1, I have 93 muons and 310 electrons.

Quan

**Comment by bendavid** [comment]
Ok, evidently there are electrons not from the Z decay.  Not critical to understand at this moment...

**Comment by bendavid** [comment]
+1

**Comment by franzoni** [comment]
+1
the proposed change is sane. The relevant workflow 140.4 fails in IB for unrelated reason.
140.4 works fine in 7_4_0_pre5+this_PR.

An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'generation_step'
   [2] Calling event method for module GenParticleProducer/'hiGenParticles'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generator

**Comment by franzoni** [comment]
the failures are unrelated to this PR

**Comment by davidlange6** [comment]
please test

**Comment by BetterWang** [comment]
Hi @davidlange6 , what do I have to test?

**Comment by franzoni** [comment]
Hi Quang, David is triggering the 'bot' infrastructure used for release
integration build to re run test jobs, rebasing your commit on top of a
revised commit.  That's a key word. Think you can just wait for Now.

**Pull request merged**
