### PR TITLE
[10.2.X] Fix SiStrip payload inspector classes 

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
this PR fixes two issues introduced unintentionally in https://github.com/cms-sw/cmssw/pull/23316:

1. removes the warning in compilation in `CondCore/SiStripPlugins/plugins/SiStripLatency_PayloadInspector.cc`
2. removes the duplication in the registration of the `SiStripNoiseComparator*ByRegion` classes that is triggering a python warning when invoking the `getPayloadData.py` script:

```shell
$ getPayloadData.py --plugin pluginSiStripNoises_PayloadInspector --plot plot_SiStripNoiseMaxByRegion --tag SiStripNoise_v2_prompt --time_type Run --iovs '{"start_iov": "303420", "end_iov": "303420"}' --db Prod --test ;                                                                                                                                                                      /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/lib/python2.7/importlib/__init__.py:37: RuntimeWarning: to-Python converter for (anonymous namespace)::SiStripNoiseComparatorByRegion<(SiStripPI::estimator)2> already registered; second conversion method ignored.
  __import__(name)
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/lib/python2.7/importlib/__init__.py:37: RuntimeWarning: to-Python converter for (anonymous namespace)::SiStripNoiseComparatorByRegion<(SiStripPI::estimator)0> already registered; second conversion method ignored.
  __import__(name)
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/lib/python2.7/importlib/__init__.py:37: RuntimeWarning: to-Python converter for (anonymous namespace)::SiStripNoiseComparatorByRegion<(SiStripPI::estimator)1> already registered; second conversion method ignored.
  __import__(name)
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/lib/python2.7/importlib/__init__.py:37: RuntimeWarning: to-Python converter for (anonymous namespace)::SiStripNoiseComparatorByRegion<(SiStripPI::estimator)3> already registered; second conversion method ignored.
  __import__(name)
```

I also include a test for the class that is giving python registration issues.
@jpriscia FYI

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi ping

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
