### PR TITLE
[12_0_X] Improve DQM beamspot clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Updates to the Legacy and HLT BeamSpot DQM clients:
 - fixed the names of the output DQM folder so that the DQM is more clear:
   - 1 folder for BeamMonitorLegacy
   - 1 folder for BeamMonitorLHT
   - previous BeamMonitor folder is removed
- Added the offline <-> online beamspot swap same as in express and HLT
 - In the BeamSpot Legacy clients I also fixed the `pixelTracksTrackingRegions` parameters to remove the 2018 HI customization that was left there (thanks @mmusich!). Overall this should increase the number of tracks reconstructed by the Legacy client so that it can fit PVs and eventually the Beamspot.
 - Fixed a typo in the name of the Legacy BeamSpotOnline tag

#### PR validation:
Should be validated with playback system in P5, run 346373.

#### Backport
Not a backport. A forward port to master and 12_1_X will be provided after the playback test.

FYI @mtosi @gennai @vmariani @dzuolo

### CODE REVIEW

**Comment by francescobrivio** [comment]
urgent

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
From the online playback I can see that:
 - the BeamMonitorHLT and BeamMonitorLegacy directories are now correctly split as they should be
 - the legacy BS client now seems to have enought trks and PVs to produce a fit

@pmandrik @ahmad3213 if the playback was succesful from your side please sign this PR and deploy it  before the StableBeams today.

**Comment by ahmad3213** [comment]
+1

**Comment by qliphy** [comment]
+1
A forward port to master and 12_1_X will be provided after the playback test.

**Comment by francescobrivio** [comment]
Just for completeness this is the DQM plot that proves both Beamspot DQM clients were producing converging BeamSpot fits and thus validating this PR:

Schermata 2021-11-01 alle 10 52 47

**Comment by mmusich** [comment]
Also here logs from the conddb: https://cms-conddb.cern.ch/cmsDbBrowser/logs/show_O2O_log/Prod/BeamSpotOnlineLegacy/2021-11-01%2003:00:28.830625

**Comment by francescobrivio** [comment]
backport of #35932

**Pull request merged**
