### PR TITLE
FastSim premixing workflows and matrix cleanup [14_1_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #46007
(which got moved to 14_2_X)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by kpedro88** [comment]
@cms-sw/upgrade-l2 please sign

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
