### PR TITLE
Noisy_ElectronSeedProducer_Correction_V1 : plugins part

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

Finish the transition from infinity() to max()
Description: Solves the problem reported [here](https://github.com/cms-sw/cmssw/issues/45658).
The printouts were triggered because a mixed usage of max() and infinity() 

#### PR validation:

compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine
41 40 39 34 17 1 1 1 1 1 1 tests passed, 2 0 0 0 0 0 0 0 0 0 0 failed
the 2 errors are DAS error (see runall-report-step123-.log).
runall-report-step123-.logation is OK, basics tests (scram b runtests or local tests) are OK too.
[runall-report-step123-.log](https://github.com/user-attachments/files/17777697/runall-report-step123-.log)

@beaudett

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by mmusich** [comment]
type egamma, bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
