### PR TITLE
Fix crash in CorrelationConditions uGT emulator

### PR DESCRIPTION
**Pull request by rekovic**
Missing instantiation of candEtSumVec.  Also added checks of types.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
unrelated error

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
