### PR TITLE
HBHE: HLT Run3 configuration

### PR DESCRIPTION
**Pull request by mariadalfonso**
Update of HCAL@HLT for Run3 are into ConfDB & the HLT menus.

this PR contains two customization functions to run on the 2018 data to remove depth collapsing: the HLT is now identical to the Offline, both HB and HE are phase1 upgrade and update Mahi: following the Run2-legacy/Run3 offline setup

The two options are provided to start from the Run3 menu or from the Run2 menu.
(note in 2018 HB is still phase0 w/QIE8 and only one depth) 

A number of duplicates were identified and suggested to remove for Run3.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
N.B. unrelated to the HCAL changes, all the modules below look duplicated to me.
It seems a left over from the early Run2 when HCAL was running the M3 for all rechits and M2 only around electron and muon.
If regional pf-rechits are not needed consider cleaning these sequences.

#-------

fragment.hltParticleFlowClusterHBHE = cms.EDProducer( "PFClusterProducer",
fragment.hltParticleFlowClusterHBHEForEgamma = cms.EDProducer( "PFClusterProducer",
fragment.hltParticleFlowClusterHBHERegForMuons = cms.EDProducer( "PFClusterProducer",
fragment.hltParticleFlowClusterHBHEForEgammaUnseeded = cms.EDProducer( "PFClusterProducer",
fragment.hltParticleFlowClusterHBHEForMuons = cms.EDProducer( "PFClusterProducer",
fragment.hltParticleFlowClusterHBHERegForTkMuons = cms.EDProducer( "PFClusterProducer",

#-------

fragment.hltParticleFlowClusterHCAL = cms.EDProducer( "PFMultiDepthClusterProducer",
fragment.hltParticleFlowClusterHCALForEgamma = cms.EDProducer( "PFMultiDepthClusterProducer",
fragment.hltParticleFlowClusterHCALRegForMuons = cms.EDProducer( "PFMultiDepthClusterProducer",
fragment.hltParticleFlowClusterHCALForEgammaUnseeded = cms.EDProducer( "PFMultiDepthClusterProducer",
fragment.hltParticleFlowClusterHCALForMuons = cms.EDProducer( "PFMultiDepthClusterProducer",
fragment.hltParticleFlowClusterHCALRegForTkMuons = cms.EDProducer( "PFMultiDepthClusterProducer",

#-------

fragment.hltParticleFlowRecHitHBHE = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHBHEForEgamma = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHBHERegForMuons = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHBHEForEgammaUnseeded = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHFForEgammaUnseeded = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHBHEForMuons = cms.EDProducer( "PFRecHitProducer",
fragment.hltParticleFlowRecHitHBHERegForTkMuons = cms.EDProducer( "PFRecHitProducer",

**Comment by fabiocos** [comment]
please test

**Comment by mariadalfonso** [comment]
before the PR I test the runTheMatrix on the Run3 scenario 11634.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2021_GenSimFull+DigiFull_2021+RecoFull_2021+HARVESTFull_2021+ALCAFull_2021 and seemed working

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mariadalfonso** [comment]
@Martin-Grunewald 
I added commit 02a36304b69e1d99ad92789fd11241aed6724b6b to finalize the Run3 customization

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Here it is (check your git client):

You do:
```
process.HLTDoLocalHcalSequence      = cms.Sequence( process.hltHcalDigis + process.hltHbhereco + process.hltHfprereco + process.hltHfreco + process.hltHoreco )
process.HLTStoppedHSCPLocalHcalReco = cms.Sequence( process.hltHcalDigis + process.hltHbhereco )
```
Should something similar also be applied to HLTDoLocalHcalWithTowerSequence (see master table) or not? I would think so....?

**Comment by mariadalfonso** [comment]
> Here it is (check your git client):
> 
> You do:
> 
> ```
> process.HLTDoLocalHcalSequence      = cms.Sequence( process.hltHcalDigis + process.hltHbhereco + process.hltHfprereco + process.hltHfreco + process.hltHoreco )
> process.HLTStoppedHSCPLocalHcalReco = cms.Sequence( process.hltHcalDigis + process.hltHbhereco )
> ```
> 
> Should something similar also be applied to HLTDoLocalHcalWithTowerSequence (see master table) or not? I would think so....?

@ Martin-Grunewald 
I updated the customization removing the collapsing from the HLTDoLocalHcalWithTowerSequence as well. It's now technically correct, but not sure why we need the duplicated calorimenter sequence since the new recHits collection is a subset of the full one. I suggest to review those HLTDoLocalHcalSequence and HLTDoLocalHcalWithTowerSequence together with the suggested cleaning in the pf-sequences mentioned in https://github.com/cms-sw/cmssw/pull/28163#issuecomment-541418907

**Comment by mariadalfonso** [comment]
@Martin-Grunewald 
I note here some extra hlt module downstream to HCAL that should be dropped from Run3.

fragment.HLTHBHENoiseCleanerSequence = cms.Sequence( fragment.hltHcalNoiseInfoProducer + fragment.hltHcalTowerNoiseCleanerWithrechit )

and the fragment.hltMetClean  and  fragment.hltMETCleanXYZ can be safetly removed.

Those modules were designed for the old electronics that is already replaced in P5 for Run3 (in both HB and HE).

**Comment by Martin-Grunewald** [comment]
@mariadalfonso 
Can you please file a separate JIRA request for this? Also, I assume the products of these modules are used, so the modules using them in turn must be updated to use some other pre-clean products.

**Comment by mariadalfonso** [comment]
@Martin-Grunewald 
jetMET will be in a better position to adapt the cleanMET to the MET and they can post a new JIRA on the removal of the cleanMET.
This investigation started prompted by @lathomas

I can only say that the 
fragment.HLTHBHENoiseCleanerSequence should be dropped, or should be dummy. If in Run3 scenario the cleanMET and the MET are different then the module is  mis-configured.

**Comment by mariadalfonso** [comment]
We have difference instance of CaloTowersCreator they slightly differ in the parameters that are send, but not sure is real or is just something not updated in the past or just cloned.

fragment.hltTowerMakerForAll = cms.EDProducer( "CaloTowersCreator",
fragment.hltTowerMakerForECALMF = cms.EDProducer( "CaloTowersCreator",
fragment.hltTowerMakerForHCAL = cms.EDProducer( "CaloTowersCreator",
fragment.hltStoppedHSCPTowerMakerForAll = cms.EDProducer( "CaloTowersCreator",
fragment.hltTowerMakerForAllBeamHaloCleaned = cms.EDProducer( "CaloTowersCreator",
fragment.hltTowerMakerEcal = cms.EDProducer( "CaloTowersCreator",

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@Martin-Grunewald @mariadalfonso do I correctly understand that this PR is now effectively embedded in #28233 which has been already integrated? Is see pieces of this update in the other, I would like to be sure that this PR is no more needed, in which case let's just close it

**Comment by mariadalfonso** [comment]
@fabiocos 

It's correct that the Run3-menu has been updated by Martin, and we do not need anymore the synchornizeHCALHLTofflineRun3.
We still need a function that bring back the sw changes in the Run3-menu to the hw of the Run2-2018-data, so that tests such as the timing can be done.
I will update this PR later today.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@mariadalfonso this code is overlapping with #28110 and needs now to be rebased

**Comment by Martin-Grunewald** [comment]
@mariadalfonso 
Could you please update the PR, and especially remove the actual calls to the customisation functions?
We discussed in today's TSG meeting that the expert users would call the remaining routine explicitely, but that per default it is not called.
Further, spelling: synchornise => synchronise

**Comment by mariadalfonso** [comment]
@Martin-Grunewald resolved conflicts and removed the call of the customization

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

DQM changes are unrelated to this PR

**Pull request merged**
