### PR TITLE
Remove trigger evaluation in ExoticaDQM module and related variables

### PR DESCRIPTION
**Pull request by CeliaFernandez**
#### PR description:

This PR removes the requirement of the Offline EXO PAG validation code for the events to pass the selected triggers. Currently a set of HLT paths was evaluated and the histograms were filled only if the events passed at least one of them.

Phase-2 HLT menu development (see https://github.com/cms-sw/cmssw/pull/40412) would reduce the statistics in the EXO DQM histograms as shown in [1]. To avoid this decrease and provided that trigger evaluation do not provide significant insight into the validation of offline objects, we have converged into removing the trigger requirement.

Impact in Phase-2 can be studied by testing together with https://github.com/cms-sw/cmssw/pull/40412 
@srimanob

[1] https://indico.cern.ch/event/1243344/

#### PR validation:

This PR passed all unit tests and the full standard battery of runTheMatrix workflows:
runTheMatrix.py -l limited -i all --ibeos

It was checked that the current HLT menu let all the events of the relval samples pass and fill the histograms. No changes are expected in the validation plots with respect to the previous EXO DQM configuration. The number of events that fired these triggers is shown in the attached plots for three different relval samples that are often used in EXO validation:

trigger_triggeredEvents_QCD
trigger_triggeredEvents_SingleMu
trigger_triggeredEvents_ZEE

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

It is not a backport

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/40412
- workflow = 23634.0

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
This PR should be good to go with https://github.com/cms-sw/cmssw/pull/40412

**Comment by emanueleusai** [comment]
@srimanob thank you very much for the explanation of the differences, but I am still confused.

WFs 13234.0,13434.0,135.4,2018.1,20834.76,5.1 present differences in Physics/Exotica, as expected from your explanation above.

However I also see differences in WFs 20834.0,20834.75,20896.0,20900.0,21034.999,23634.0 in Egamma/Electrons/Ele1_General/ele6_triggers that i cannot explain from the modified code. 
I would assume this is coming from the IB, but the fact that an "ele6_triggers" plot (and only that) makes me suspicious.

Do you have an idea of what might be going on here?

**Comment by srimanob** [comment]
Thanks @emanueleusai 
I don't expect that change, I will need to have a look.

**Comment by perrotta** [comment]
@cmsbuild please test
- @srimanob @emanueleusai let retest this and compare with an IB which includes already #40412

**Comment by perrotta** [comment]
> Thanks @perrotta But it is possible that the PR that we merge effect this? So we don't see difference when we use baseline that [PR](https://github.com/cms-sw/cmssw/pull/40412) is merged. We don't see difference now in ele trigger.

@srimanob I am not sure that I understand what you mean...

Anyhow:
- in the [first comparison](https://github.com/cms-sw/cmssw/pull/40665#issuecomment-1412660322) we compared the combined effect of this PR and #40412 with respect to a baseline which did not contain any of them
- In the [second comparison](https://github.com/cms-sw/cmssw/pull/40665#issuecomment-1415683966) we compared the effect of this PR only with respect to a baseline which does not contain it

Therefore, the previous extra differences are expected to come from the already merged #40412

**Comment by emanueleusai** [comment]
ah yes I see the ele6_trigger differences in https://github.com/cms-sw/cmssw/pull/40412

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
Thanks @emanueleusai @perrotta 
I've opened the git issue to follow up the change in ele_trigger at https://github.com/cms-sw/cmssw/issues/40700 (not from this PR, but from https://github.com/cms-sw/cmssw/pull/40412)

**Pull request merged**
