### PR TITLE
Streamer output modules ported to one::OutputModule (74X)

### PR DESCRIPTION
**Pull request by smorovic**
Migrates EvFOutputModule (DAQ) and EventStreamFileWriter from legacy to one::OutputModule interface
Backport of #11115 and #11116 in 76X and 75X

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by emeschi** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #11254 caed04f869c49b376c3cb40fce0ed4eb0a5fd42d

Migrating streamer output modules to one::OutputModule to support multi-threading. There should be no change in monitored quantities. #11115 and #11116 are the 76X and 75X versions of this PR, and they have both been merged.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-09-13-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
tracked at #11317

**Pull request merged**
