### PR TITLE
Improve initialization of EgHLTOfflineSource

### PR DESCRIPTION
**Pull request by davidlange6**
by reducing redundant calls to expensive code

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test
(looks like a real das glitch)

**Comment by slava77** [comment]
number 3 on my list in DQMEDAnalyzer::beginRun (this is 8-core case for  "DQM:@standardDQM+@miniAODDQM" in run 274199 )
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_8_1_X_2016-08-18-1100-test-speedEGHLT-2ffc7da.274199.JetHT.step3.mt8.ne8.pp/33
This is almost x30 faster than the original version.

**Comment by dmitrijus** [comment]
+1

thanks

**Pull request merged**
