### PR TITLE
Initialize vars to nullptr in HTXSRivetProducer, fix #31474

### LINKED ISSUE #31474: New rivet version fails ASAN relvals with sygsegv
After rivet was moved to version 3.1.2 in https://github.com/cms-sw/cmsdist/pull/6209
a number of ASAN workflows started failing:
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_2/2020-09-14-2300?selectedArchs=slc7_amd64_gcc820&selectedFlavors=ASAN_X&selectedStatus=failed
and the failing relvals can be seen in kibana right after the pr was merged:
https://tinyurl.com/y4ag6e7f

I ran it under gdb and for now I got that it fails somewhere in PhysicsTools/NanoAOD with this:

```

%MSG
%MSG-w LogicError:  GenWeightsTableProducer:genWeightsTable@beginRun  15-Sep-2020 21:22:51 CEST Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'source'.
The specified productInstanceName was ''.

%MSG
Begin processing the 1st record. Run 1, Event 5002, LumiSection 101 on stream 0 at 15-Sep-2020 21:22:51.992 CEST

Thread 1 "cmsRun" received signal SIGSEGV, Segmentation fault.
0x00007fffab3082bc in Rivet::ProjectionApplier::getProjHandler (this=0xbebebebebebebebe)
    at /build/mrodozov/rivet_fails/build_rivet/slc7_amd64_gcc820/external/rivet/3.1.2/include/Rivet/ProjectionApplier.hh:142
142	      return _projhandler;
```

@intrepid42

### PR DESCRIPTION
**Pull request by mrodozov**
Resolves: #31474

#### PR description:

Fixes relvals failure (hopefully) in ASAN, see #31474 

#### PR validation:

relvals running withot sigsegv

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by agrohsje** [comment]
Thanks @Dr15Jones and @mrodozov for the fix.

**Comment by agrohsje** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
