### PR TITLE
CTPPS: new EventFilter for raw-to-digi conversion of TOTEM RP data - backport of PR #13839

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #13839 from CMSSW 81X

Validation config file using TOTEM-standalone data:

`EventFilter/TotemRawToDigi/test/totem_standalone_raw_data_test.py`

with the expected output:

`EventFilter/TotemRawToDigi/test/totem_standalone_raw_data_test.reference_output`

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
this needs #14579 to be merged first

**Comment by slava77** [comment]
@grzanka 
there is a merge conflict here.
Please rebase on top of CMSSW_8_0_X_2016-05-24-2300
... strange that I haven't noticed the reported merge conflicts earlier (after #14579 was merged but before the IB appeared).

**Comment by grzanka** [comment]
@slava77 thanks for notice, will take care of it

**Comment by grzanka** [comment]
@slava77 I've rebased on the top of CMSSW_8_0_X and hope its correct now.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
woops, too early to test.
I thought that condFormats PR was in already

**Comment by slava77** [comment]
#14600 is needed in 80X before this can move on

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@grzanka 
I have just noticed the following:
-  #13839 had +2,047 −13 changes in 26 files
- this PR as of c5d7967 has +3,107 −9 in 29 files
The backport should be identical 
Please review the changes and remove what should not be here.

**Comment by grzanka** [comment]
@slava77 isn't that related with the fact that original PR had merge commits ?

**Comment by slava77** [comment]
possibly: those merge commits were removing files already in the release.
This PR apparently has the same problem as the early version of #13839 (backports made out of order of integration in the release or the same code changes were included in multiple PRs).

Check of the backport correctness is much easier if changes are the same in 80X and 81X.

**Comment by grzanka** [comment]
@slava77 I understand. Better to avoid merge commits and duplicate changes. I'll fix it on Monday by adding additional commit.

**Comment by grzanka** [comment]
@slava77 I rebased again this branch on the top of CMSSW_8_0_X to include changes in recently merged #14600

**Comment by grzanka** [comment]
@slava77 Now this PR looks identical to #13839

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14603	a02b12a
- backport of raw2digi from 81X. The same changes as in https://github.com/cms-sw/cmssw/pull/13839	4160777, which was included in 81X for more than 4 weeks now
- jenkins tests pass (compilation etc; the new code is not executed in the tested workflows, so there are no changes with respect to the baseline)

**Pull request merged**
