### PR TITLE
Replace CPP11_auto_ptr with std::unique_ptr 

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

This is part of a campaign to remove std::auto_ptr.

CPP11_auto_ptr was #defined as std::unique_ptr in Alignment/Geners/interface/CPP11_auto_ptr.hh, so the change is completely transparent

#### PR validation:

Bot tests, no changes are expected.

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8847

**Comment by smuzaffar** [comment]
please test

new IB is available

**Comment by perrotta** [comment]
+alca
- Tests show quite several differences in DQM for ParticleFlow JetCorrections. That was suspicious, at the beginning. Then I realized that this is a common "feature" of the latest PR tests in the IB (se for example the completely unrelated #43451), and therefore this PR can be signed.
- The issue of those spurious differences is worth being investigated.

**Comment by tvami** [comment]
+analysis

**Pull request merged**
