### PR TITLE
Move slimmedAddPileupInfo to miniAOD_customizeMC (76X)

### PR DESCRIPTION
**Pull request by lgray**
Move slimmed pileup info out of common customize for MiniAOD.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77

**Comment by lgray** [comment]
@cmsbuild please test

may as well...

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
