### PR TITLE
New Run3 era for updated HB thresholds in 2023

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
Creating a new era to update HB thresholds. 
This PR is essentially doing similar things as done in https://github.com/cms-sw/cmssw/pull/40689 and https://github.com/cms-sw/cmssw/pull/40756 for 12_6_X. 

#### PR validation:
Checked with `12434.0`

This PR needs to be back-ported to data-taking release 13_0_X.

FYI @cms-sw/hcal-dpg-l2 @cms-sw/pf-l2 @francescobrivio @davidlange6

### CODE REVIEW

**Comment by francescobrivio** [comment]
FYI also
PPD: @jordan-martins
ORMs: @saumyaphor4252 @malbouis

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by swagata87** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/41319

**Comment by malbouis** [comment]
@swagata87 I was able to test this new scenario using the DataProcessing tools (Configuration/DataProcessing/test/RunPromptReco.py) and it ran successfully (without any crashes). 
I also verified the right thresholds were included in the PromptReco configuration file ( `recHitEThresholdHB = cms.vdouble(0.4, 0.3, 0.3, 0.3) `)

Recipe:

1 - Repack with release 12_4_9:
    `python3 Configuration/DataProcessing/test/RunRepack.py --lfn file:/eos/cms/store/t0streamer/Data/PhysicsJetMET/000/359/762/run359762_ls0136_streamPhysicsJetMET_StorageManager.dat`

2 - Run RunPromptReco.py in the latest 13_1_X IB, using the output file from 1:
     `python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario ppEra_Run3_2023 --reco --aod --global-tag 130X_dataRun3_Prompt_v2 --lfn file:write_PrimDS2_RAW.root --alcareco TkAlMinBias+SiStripCalMinBias"

**Comment by swagata87** [comment]
> @swagata87 I was able to test this new scenario using the DataProcessing tools 

awesome, thanks Helena

**Comment by srimanob** [comment]
I am wondering if we should do this way, but not in the opposite way?

Should we not make the change to default Run3, and make modification for Run3_2022 instead? With this way, default is the most recent one.

**Comment by mmusich** [comment]
> Should we not make the change to default Run3, and make modification for Run3_2022 instead? With this way, default is the most recent one.

aren't we always building the most recent years on the older ones?

Run3 inherits from 2018 

https://github.com/cms-sw/cmssw/blob/0b8122584479054ab6ccdee6d5010676bd315f1b/Configuration/Eras/python/Era_Run3_cff.py#L18

which inherits from 2017

https://github.com/cms-sw/cmssw/blob/0b8122584479054ab6ccdee6d5010676bd315f1b/Configuration/Eras/python/Era_Run2_2018_cff.py#L24

which inherits from 2016

https://github.com/cms-sw/cmssw/blob/0b8122584479054ab6ccdee6d5010676bd315f1b/Configuration/Eras/python/Era_Run2_2017_cff.py#L28

**Comment by srimanob** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/41319
- workflows = 12402.0,12434.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
I agree with @makortel 
That is maybe a good thing to make a clear on Era. Maybe this PR and https://github.com/cms-sw/cmssw/pull/41319 can be merged first, and we come with a new PR to arrange this setting.

**Comment by mandrenguyen** [comment]
+reconstruction
Latest test show differences in the expected places in wfs 12402 and 12434.
This demonstrates that the changes to the HB thresholds are having the desired effect. 

As mentioned here https://github.com/cms-sw/cmssw/pull/41271#issuecomment-1507146557
there needs to be subsequent PR to clean up the way the run 3 eras are dealt with.

**Comment by swagata87** [comment]
thanks, so I will prepare a backport to data-taking release (13_0_X)

**Pull request merged**
