### PR TITLE
DD4hep: Tracker Geometry Description

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Tracker geometry configuration and its test script

This PR is based on #26371 and #26373

#### PR validation:

```
cmsRun Geometry/TrackerGeometryBuilder/test/python/testTrackerGeometry.py
```
The error is due to a missing **track:DDTrackerRingAlgo** algorithm implementation and should be ignored for now.
```
DD4CMS                 +++ Start executing algorithm DDCMS_track_DDTrackerRingAlgo....
DD4CMS           ERROR ++ FAILED  NOT ADDING SUBDETECTOR 00000000 = track:DDTrackerRingAlgo
```
#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@fabiocos and @smuzaffar - the same error here unrelated to this PR:
```
GEN,SIM,DIGI,DIGI2RAW,RAW2DIGI,L1Reco,RECO,EI,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Step: GEN Spec: 
Loading generator fragment from Configuration.Generator.SingleElectronE120EHCAL_pythia8_cfi
Step: SIM Spec: 
Step: DIGI Spec: 
Step: DIGI2RAW Spec: 
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: EI Spec: 
Step: ENDJOB Spec: 
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-04-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-04-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-04-2300/python/Configuration/Applications/ConfigBuilder.py", line 2251, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-04-2300/python/Configuration/Applications/ConfigBuilder.py", line 860, in addCustomise
    raise Exception("cannot specify twice "+fcn+" as a customisation method") 
Exception: cannot specify twice customise as a customisation method
```

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
please test
cms-bot PR https://github.com/cms-sw/cms-bot/pull/1115 should fix this

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna and this is the incremental continuation of your previous PRs... In principle this embed #26371 and #26373, am I correct?

**Comment by fabiocos** [comment]
@ianna as for MTD, the ECAL test geometry is stored under EcalCommonData, could you please clarify the choice?

**Comment by ianna** [comment]
> @ianna and this is the incremental continuation of your previous PRs... In principle this embed #26371 and #26373, am I correct?

yes, because it needs changes integrated in the first PR

**Comment by ianna** [comment]
> @ianna as for MTD, the ECAL test geometry is stored under EcalCommonData, could you please clarify the choice?

This is a sub-detector geometry, hence the choice of the package.

**Comment by fabiocos** [comment]
@kpedro88 comments?

**Comment by fabiocos** [comment]
@ianna could you please rebase this PR after the merge of #26371? The additions do not enter any production workflow, so I do not see how they could break anything

**Pull request merged**
