### PR TITLE
Back-port of a set of fixes for the conddb core

### PR DESCRIPTION
**Pull request by ggovi**
Fixes back-ported:
- remove of Root based serialization
- addition of CMSSW and boost serialization version information as payload metadata
- improved handling of exception in serialization/deserialization
- fix for condition overriding with toGet: support of '@' characters in sqlite file names (!)

### CODE REVIEW

**Comment by ggovi** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@davidlange6 
Hello David, this PR has been mentioned at the ORP last week. Is this ok for the approval?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
