### PR TITLE
Dqm 81 x test pf candidate after rebase

### PR DESCRIPTION
**Pull request by webermat**
this PR is the rebased version of the PR in 
https://github.com/cms-sw/cmssw/pull/13587

### CODE REVIEW

**Comment by webermat** [comment]
if this PR could be tested

**Comment by dmitrijus** [comment]
please test

**Comment by webermat** [comment]
comparisons are fine

+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
looks like this broke phase2 workflows.
The last time this PR was tested was June 8.
Things changed since then.

@gpetruc please check and suggest what to put here or in the miniAOD tools to let this pass
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-09-02-1100/pyRelValMatrixLogs/run/11224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2023D3_GenSimFull+DigiFull_2023D3+RecoFullGlobal_2023D3+HARVESTFullGlobal_2023D3/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2023D3_GenSimFull+DigiFull_2023D3+RecoFullGlobal_2023D3+HARVESTFullGlobal_2023D3.log

**Comment by slava77** [comment]
@davidlange6 
if there is no quick fix in a day or so, may I suggest to revert this PR

**Comment by slava77** [comment]
actually, on a more complete build many more workflows fail

```
The plugin 'PFCandidateAnalyzer' is found in multiple files 
 '"pluginDQMOfflineJetMET.so"'
 '"pluginPFCandidateAnalyzer.so"'

```

@davidlange6 please revert this ASAP

**Comment by davidlange6** [comment]
Done. Thanks for the confirmation of what I had hoped to check this am..

**Pull request merged**
