### PR TITLE
Removed time cut in calorimeters for neutron background simulation

### PR DESCRIPTION
**Pull request by civanch**
Removed forgotten time cut on hits inside calorimeters. Tracking of neutrons was not suppressed but only hits. Make time cut defined in one variable of the fragment.

Removed obsolete custom fragment

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@pietverwilligen ,

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@civanch could you clean also the usages of this customize fragment. Thanks

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@davidlange6 , you mean this update?

**Comment by davidlange6** [comment]
yes - thanks

**Pull request merged**
