### PR TITLE
follow-up to #43094, remove HLT tracking and vertexing validation harvesting from phase-2 modifier

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, address https://github.com/cms-sw/cmssw/issues/39362#issuecomment-1818476705

#### PR validation:

`runTheMatrix.py -l 24834.0 -t 4 -j 8 --ibeos` runs fine

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but might be backported to 13.1.X if there is interest from the Upgrade community.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type tracking

**Comment by rovere** [comment]
Removing from an exclusion list is equivalent to an addition 😄  I was confused by the title of the PR.
No need to update it: I looked into the code and everything is clear!

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 please review. Thank you

**Comment by tjavaid** [comment]
+1

- with spurious changes coming from unstable WF `12434.7` ( #39803 )

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
