### PR TITLE
Fix clang warnings in L1TriggerConfig/L1GtConfigProducers

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@nsmith- @rekovic please review

**Comment by fabiocos** [comment]
@rekovic this looks a pretty simple technical fix, please check and sign or comment in case

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
