### PR TITLE
[RPC] Bug fix DQM/RPCMonitorClient crash due to type conversion -1 to unsigned int

### PR DESCRIPTION
**Pull request by Somhammer**
#### PR description:

It follows up the PR #33017.

#### PR validation:
scram b -j 10

@jhgoh @jfernan2 @silviodonato

### CODE REVIEW

**Comment by Somhammer** [comment]
@silviodonato I modified the code but this pr is based on @jhgoh's repository. So I made PR in @jhgoh's repository. But if you have any good solution more than this, please let me know.

**Comment by qliphy** [comment]
@Somhammer   As mentioned by @silviodonato ,  would you please follow the suggestion to apply the patch?
"code-format:
https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-33115/21457/code-format.patch
e.g. curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-33115/21457/code-format.patch | patch -p1
You can also run scram build code-format to apply code format directly"

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
