### PR TITLE
[DQM] nanoDQMIO change in V0.1

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Naive change to bring in sincro master version with last minute change from PR https://github.com/cms-sw/cmssw/pull/36308

An extra ME for DTs is being added to the nanoDQMIO config file

### CODE REVIEW

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
