### PR TITLE
Phase2-hgx315 Modify the cfg's in Validation/HGCalValidation to accommodate V17 version of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the cfg's in Validation/HGCalValidation to accommodate V17 version of HGCal geometry

#### PR validation:

Use the cfg's to validate geometry

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
