### PR TITLE
Drop tracker geometry T29 (last with bricked pixels)

### PR DESCRIPTION
**Pull request by emiglior**
**PR description**:

This PR concerns Upgrade. 

This PR removes the phase-2 Tracker geometry T29 (last geometry left featuring bricked pixels) definitively discarded after the choice of the Inner Tracker layout (see also PR #37874).
 
The PR removes both the geometry files and the corresponding workflows.

The file
Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
is also changed in order to preserve the workflow numbers.

No changes are expected in the output for the geometries/workflows which are kept.

**PR validation:**

The PR was validated with runTheMatrix checking that

-  w/f numbers for geometries from 2026D88 to 2026D91 did not change
- running explicitly the w/f 39400.0 (2026D88) 40600.0 (2026D91) 
    
**if this PR is a backport please specify the original PR and why you need to backport that PR:**

This PR is not a backport

@adewit @connorpa @franzglessgen @mmusich @tsusa @tvami  FYI

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 39400.0,40600.0

**Comment by cvuosalo** [comment]
+1

**Comment by tvami** [comment]
+alca

**Comment by mmusich** [comment]
given that the bricked pixels are removed for good from the supported geometries, I am wondering if the corresponding local reco code could be removed as well,  thus addressing https://github.com/cms-sw/cmssw/issues/35519 as well.

**Comment by emiglior** [comment]
could you please proceed with the sign-off of the PR so that we can address this issue?

https://github.com/cms-sw/cmssw/issues/35519

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 any objections?
Thank you.

**Pull request merged**
