### PR TITLE
[Heppy] drop unnecessary dependency on rootpy

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Cleanup Heppy BuildFiles and remove  unnecessary dependency on rootpy

#### PR validation:

Local build is successful.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
> Comparison is ready
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-dfe16d/5568/summary.html
> 
> Comparison Summary:
> 
>     * No significant changes to the logs found
> 
>     * Reco comparison results: 43 differences found in the comparisons
> 
>     * DQMHistoTests: Total files compared: 34
> 
>     * DQMHistoTests: Total histograms compared: 2692110
> 
>     * DQMHistoTests: Total failures: 12
> 
>     * DQMHistoTests: Total nulls: 0
> 
>     * DQMHistoTests: Total successes: 2691779
> 
>     * DQMHistoTests: Total skipped: 319
> 
>     * DQMHistoTests: Total Missing objects: 0
> 
>     * DQMHistoSizes: Histogram memory added: 0.0 KiB( 33 files compared)
> 
>     * Checked 147 log files, 16 edm output root files, 34 DQM output files

another good example of fake failures due to #29398

**Comment by silviodonato** [comment]
+1

**Pull request merged**
