### PR TITLE
Migrating from Xerces-C++ 2.8.0 to Xerces-C++ 3.x

### PR DESCRIPTION
**Pull request by ianna**
Xerces-C++ 3.0.0 is a major release and includes a number of application-breaking interface changes compared to Xerces-C++ 2 series.
- A number of DOM interfaces (DOMLSInput, DOMLSOuput, DOMLSParser, DOMLSSerializer, DOMConfiguration, etc.) were added as part of the the final DOM Level 3 specification conformance work
- Many public interfaces that used int/long types to represent memory-related sizes, counts, indexes, etc., have been modified to use the 64-bit safe XMLSize_t type instead
- All APIs marked as deprecated in Xerces-C++ 2 series have been removed in this release. In particular deprecated DOM (depdom) as well as COM support have been removed.

Furthermore, a number of DOM interfaces (DOMBuilder, DOMWriter, DOMInputSource, etc.) were replaced as part of the the final DOM Level 3 specification conformance work.

### CODE REVIEW

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by ianna** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by ianna** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by cvuosalo** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

Jenkins failed. Maybe another try will work.

**Comment by slava77** [comment]
this PR is made for CMSSW_8_1_ROOT64_X
probably no need for signoff here .. and testing is apparently not feasible

**Comment by ianna** [comment]
@smuzaffar - it looks like unrelated error:
```
An exception of category 'FatalRootError' occurred while
   [0] Constructing service of type InitRootHandlers
   Additional Info:
      [a] Fatal Root Error: @SUB=TInterpreter::ReadRootmapFile
class  edm::Ref<edmNew::DetSetVector<Phase2TrackerCluster1D>,Phase2TrackerCluster1D,edmNew::DetSetVector<Phase2TrackerCluster1D>::FindForDetSetVector> found in libDataFormatsPhase2TrackerCluster.so  is already in libDataFormatsTrackerRecHit2D.so 

```

**Comment by ianna** [comment]
@smuzaffar - in my local area full matrix results were:
```
373 354 332 226 20 2 1 tests passed, 4 1 0 0 0 0 0 failed
```
Four workflows had  DAS_ERROR:
```
4.57_ZElSkim2012B+ZElSkim2012B+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri May 27 11:57:49 2016-date Fri May 27 11:56:25 2016; exit: 1 0 0 0
4.77_ZElSkim2012D+ZElSkim2012D+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri May 27 12:54:57 2016-date Fri May 27 12:53:52 2016; exit: 1 0 0 0
4.78_WElSkim2012D+WElSkim2012D+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri May 27 12:55:08 2016-date Fri May 27 12:54:35 2016; exit: 1 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Sat May 28 05:18:06 2016-date Sat May 28 05:18:05 2016; exit: 1 0 0 0 0
```
One failed:
```
4.76_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Fri May 27 12:53:45 2016-date Fri May 27 12:52:18 2016; exit: 0 21760 0 0

Begin processing the 1st record. Run 208307, Event 56580952, LumiSection 34 at 27-May-2016 12:53:42.749 CEST
----- Begin Fatal Exception 27-May-2016 12:53:42 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing run: 208307 lumi: 34 event: 56580952
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Calling event method for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Rethrowing an exception that happened on a different thread.
   [4] Reading branch EcalRecHitsSorted_ecalPreshowerRecHit_EcalRecHitsES_reRECO.
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::CheckByteCount
object of class vector<EcalRecHit> read too few bytes: 43898 instead of 94058

----- End Fatal Exception -------------------------------------------------

```

**Comment by smuzaffar** [comment]
@ianna , this looks good now. WF 4.76 and unit tests are also failing in IB. So this looks good to go in to DEVEL IB.

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by smuzaffar** [comment]
Jenkins failed to build as it was not able to download the  Xerces-C sources for 3.1.3 (which are not available under normal download path. @iahmad-khan , please update the source url to http://www-us.apache.org/dist//xerces/c/3/sources/xerces-c-3.1.3.tar.gz

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2305

**Comment by ianna** [comment]
This one seems unrelated:
```
----- Begin Fatal Exception 02-Jun-2016 02:20:56 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbuild/jenkins-workarea/workspace/cmsdist-cmssw-test-pr/CMSSW_8_1_DEVEL_X_2016-06-01-1100/src/RecoLocalCalo/HGCalRecProducers/test/testHGCalRecoLocal_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named GeometryExtended2023LRecoReco_cff
----- End Fatal Exception -------------------------------------------------
Failure using testHGCalRecoLocal_cfg.py: status 90
status = 23040

---> test runtestRecoLocalCaloHGCalRecProducers had ERRORS
 
```

**Comment by smuzaffar** [comment]
yes that unit test is failing IBs too.
@davidlange6 , Comparison results are now available. Note that comparison was done using CMSSW_8_1_X_2016-06-01-1100 IB (for which we had the baseline available)

**Comment by ianna** [comment]
The first test runs fine locally:
```
===== Test "TestFWCoreIntegrationStandalone" ====
Running .02-Jun-2016 13:14:59 CEST  Initiating request to open file file:testStandalone.root
02-Jun-2016 13:14:59 CEST  Successfully opened file file:testStandalone.root
02-Jun-2016 13:14:59 CEST  Closed file file:testStandalone.root


OK (1)

---> test TestFWCoreIntegrationStandalone succeeded
 
^^^^ End Test TestFWCoreIntegrationStandalone ^^^^

```

**Comment by davidlange6** [comment]
Interestingly there are lots of differences in the MC workflows.

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2324

**Pull request merged**
