### PR TITLE
Calotower phase-out from PF code

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

To address https://github.com/cms-sw/cmssw/issues/43264. 
In `SuperClusterImporter.cc`, the value of H/E from old method (calotower-based) and new method (rechit-based) were same. (This is checked for a few events).  

Offline reco config and Phase2 HLT config were accordingly modified. Note that for Run3 HLT config, no change is needed, because Run3 HLT does not use SuperClusterImporter. 

#### PR validation:

Checked with `12434.0_TTbar_14TeV+2023`

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hi @swagata87 
I see there are differences (eg, reco comparisons), while according to the PR description, you seem to assume there should not be any differences. Could you please comment?

**Comment by mmusich** [comment]
>  I see there are differences (eg, reco comparisons), while according to the PR description, you seem to assume there should not be any differences. Could you please comment?

hello @swagata87 (happy new year!). Do you have any new input on the question above from Martin?
Thank you.

**Comment by swagata87** [comment]
hey Marco, Martin, all,
Happy New year! 
My new year was going very happily until you reminded me of calotowers :-D :-D 
I will get back to this soon, hopefully by the end of this week. Maybe a re-test of the PR will be useful to be sure that the differences we see are not transient. In any case, I will check these soon.
Cheers,
Swagata

**Comment by Martin-Grunewald** [comment]
please test

**Comment by swagata87** [comment]
So there are some changes in reco, which can happen due to calotower->rechit migration. In the past myself and others had made this migration for H/E variable (and other variables) in egamma code-base. We observed at that time that H/E value can be slightly different when it is made from HCAL rechit compared to when it is made from calotowers. This is probably because the eta/phi of the calotower is the weighted average of the (ECAL+HCAL), but for HCAL recHit it's just the rechit eta/phi. This creates a minor difference in variables. For example we saw differences in the past in the following cases (see PR descriptions) ->  
for rho https://github.com/cms-sw/cmssw/pull/36157
for H/E in phase2 HLT https://github.com/cms-sw/cmssw/pull/40525
for H/E in run3 HLT https://github.com/cms-sw/cmssw/pull/35049

In this PR we saw reco changes in `136.731_RunSinglePh2016B` and `140.56_RunHI2018`. 
They look okay to me. For the 2nd one, ie for the HI case, may be its better to have the opinion of Matt as I'm not an HI expert but I had to touch that HI config file to keep things consistent among pp and HI.

**Comment by mandrenguyen** [comment]
thanks @swagata87
Differences seem to be focused at the very end of the endcap:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-01-02-2300+8bc232/60455/validateJR/140.56_RunHI2018/all_reRECO_step2/c_recoSuperClusters_particleFlowEGamma__reRECO_obj_eta.png

Is that understood/expected?

**Comment by swagata87** [comment]
The supercluster eta distribution itself is very skewed. There are very little entries in barrel and a lot more entries in the endcaps, specially in the very end of endcaps. We've a higher chance of finding a discrepancy in that area where there are more statistics.

Also, looking at the calotower code, it looks like they handled HE and HB a bit differently. This is probably because, in the beginning when calotower code was written, CMS had 1 depth for HB but 2-3 depths for HE. So different treatment was needed; see here for example https://github.com/cms-sw/cmssw/blob/9fca027cd9b380c6d9f4244b56f3e2c9ef2899db/DataFormats/CaloTowers/interface/CaloTower.h#L183-L185
and its usage here:
https://github.com/cms-sw/cmssw/blob/9fca027cd9b380c6d9f4244b56f3e2c9ef2899db/RecoEgamma/EgammaIsolationAlgos/src/EgammaHadTower.cc#L73-L77
that different treatment of HB/HE remained same in calotower code even now when HB and HE both has multiple depths. But in the recHit approach, HB and HE are treated in same manner. This might give rise to HE-specific discrepancy.

**Comment by mandrenguyen** [comment]
+reconstruction
PR leads to modest differences in the reconstruction, mostly at large eta.
 According to https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1876603381
these differences are understood and are unavoidable, if we want to remove caloTowers as an intermediate step between rechits and PF

**Comment by mmusich** [comment]
+hlt
   * changes in the phase-2 HLT menu in line with the PR description.

**Comment by swagata87** [comment]
type pf

**Comment by swagata87** [comment]
FYI @bellan

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
@swagata87,
after merging this PR (in `CMSSW_14_0_X_2024-01-08-2300`) there are widespread failures in IB relvals, with exceptions of the type:

```
---- Begin Fatal Exception 09-Jan-2024 03:22:17 CET-----------------------
An exception of category 'Conditions mismatch' occurred while
   [0] Processing  Event run: 301998 lumi: 76 event: 77970383 stream: 0
   [1] Running path 'dqmoffline_9_step'
   [2] Prefetching for module SMPDQM/'SMPDQM'
   [3] Prefetching for module MuonProducer/'muons'
   [4] Prefetching for module PFProducer/'particleFlowTmp'
   [5] Calling method for module PFBlockProducer/'particleFlowBlock'
Exception Message:
Requested conditions of type HcalPFCuts for cell (0x4538403f) (HE 16,63,3) got conditions for cell (0x0) 
----- End Fatal Exception ------------------------------------------------- 
```
See e.g. [here](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_14_0/2024-01-08-2300?selectedArchs=el8_amd64_gcc12&selectedFlavors=X&selectedStatus=failed)
curiously, as far as I can tell all affected workflows are for 2017, perhaps there is a condition problem in the relevant IoV or the `run2_data` GT? (tagging @cms-sw/alca-l2).

**Comment by swagata87** [comment]
ok I will check shortly. Probably we can use it only for Run3 and Phase2 by using a era, and keep things as before for Run2/Run1.

**Comment by swagata87** [comment]
it's not clear to me how to reproduce the crash. 
if someone can share a recipe to reproduce it, then it will be easier to look into the problem.
thanks!

**Comment by mmusich** [comment]
> it's not clear to me how to reproduce the crash.

```
cmsrel CMSSW_14_0_X_2024-01-08-2300
cd CMSSW_14_0_X_2024-01-08-2300/src
cmsenv
runTheMatrix.py -l 136.8 -t 4 -j 8 --ibeos
```

reproduced for me.

**Comment by abdoulline** [comment]
> Previously we always used this for Run3 and Phase2 only. So the issue was not uncovered. This time I did not use the Era.

OK, thanks.  At the moment I cannot exclude that  Run1,2 may need to avoid using the HCalCutsFromDB feature. 
I mean if there is a deficiency for 2017 IOVs in all the earlier produced conditions,  it would mean quite massive GTs reshuffling (remaking HCAL tags and then producing new GTs)...

**Comment by mmusich** [comment]
> I mean if there is a deficiency for 2017 IOVs in all the earlier produced conditions, it would mean quite massive GTs reshuffling (remaking HCAL tags and then producing new GTs)...
 
 if it's confirmed there's a deficiency in the GTs, it's IMHO better to remove bugged conditions in the long run. Sweeping the dust under the carpet will certainly lead to a time bomb.

**Comment by abdoulline** [comment]
@mmusich 
Don't get me wrong, I meant "short-term" removal of Run1/2 from conditions usage as a simplest option, so that in longer-term GTs could be "repaired" and then reconsidered once again. 

I've added to the previous comment that I don't see conditions problem at the moment...

**Comment by mmusich** [comment]
> I've added to the previous comment that I don't see conditions problem at the moment...

> > At the moment I can only say that in 2017 Geometry (IOV in question 287446 - 309054)
the readout/cell (HE 16,63,3) doesn't exist in any HCAL conditions, only (HE 16,63,2) and (HE 16,63,4)

@abdoulline, if it helps, there are also failures in MC (wf 25215.17: `GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17`) in which the missing cell is not 16,63,3:
```
---- Begin Fatal Exception 09-Jan-2024 05:37:03 CET-----------------------
An exception of category 'Conditions mismatch' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 1
   [1] Running path 'dqmofflineOnPAT_1_step'
   [2] Prefetching for module SingleTopTChannelLeptonDQM_miniAOD/'singleTopElectronMediumDQM_miniAOD'
   [3] Prefetching for module PATMuonSlimmer/'slimmedMuons'
   [4] Prefetching for module PATMuonSelector/'selectedPatMuons'
   [5] Prefetching for module PATMuonProducer/'patMuons'
   [6] Prefetching for module MuonProducer/'muons'
   [7] Prefetching for module PFProducer/'particleFlowTmp'
   [8] Calling method for module PFBlockProducer/'particleFlowBlock'
Exception Message:
Requested conditions of type HcalPFCuts for cell (0x45184440) (HE 17,64,1) got conditions for cell (0x0) 
----- End Fatal Exception -------------------------------------------------
``` 

see e.g. [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-08-2300/pyRelValMatrixLogs/run/25215.17_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17/step4_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17.log#/134-134)

**Comment by mmusich** [comment]
@abdoulline thank you for the detailed analysis.

> So, I suppose that 2016 PFCuts would work for 2017. I'll try to check it next days (by the end of the week), but unfortunately after Xmas break there appeared several urgent issues requiring my attention...

do you mean using the 2016 PFCuts *tout-court* ?
I tried to do that, by adding the following snipped:

```python
process.GlobalTag.toGet = cms.VPSet(
    cms.PSet(record = cms.string("HcalPFCutsRcd"),
             tag = cms.string("HcalPFCuts_2016_v1.0_mc"),
             connect = cms.string("frontier://FrontierProd/CMS_CONDITIONS")
             )
)
```
(this should make the job consume the payload with hash `fae877e66505ad86ecd01daa103b79a97c144b16`, which also corresponds to the [IOV 1-287446] of the data tag `HcalPFCuts_v1.0_offline`)

to the configuration resulting from running the step3 of wf 136.8 (as in https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1882610297), but that immediately fails with:

```
----- Begin Fatal Exception 09-Jan-2024 12:39:21 CET-----------------------
An exception of category 'Conditions mismatch' occurred while
   [0] Processing  Event run: 301998 lumi: 76 event: 78030333 stream: 1
   [1] Running path 'dqmoffline_9_step'
   [2] Prefetching for module SMPDQM/'SMPDQM'
   [3] Prefetching for module MuonProducer/'muons'
   [4] Prefetching for module PFProducer/'particleFlowTmp'
   [5] Calling method for module PFBlockProducer/'particleFlowBlock'
Exception Message:
Requested conditions of type HcalPFCuts for cell (0x43183815) (HB 14,21,1) got conditions for cell (0x43101423) (HB -5,35,1)
----- End Fatal Exception -------------------------------------------------
```

**Comment by abdoulline** [comment]
Thanks for a quick check, Marco !
Yes, I thought the way you've tried it would work, but  I forgot about the "dense index"(for given DetId) stored in the DB. And which is different for the same physics (HB, HE) channel  ieta/iphi/depth in 2016 and 2017. 
Now it  seems to be more complicated, I don't have an immediate solution...

**Comment by abdoulline** [comment]
> maybe I am missing something trivial, but could it not be populated using the existing 2017 payload, but adding more "fake" cells for the special HEP17 module included all the ietas from 16 to 29 (and iphi = 63-66) ?

DB array is populated _sequentially_ using **dense index** (sequential one caculated by Geometry methods for given detector topology with **given number of channels**), so  
for 2017 Geometry the cell in question (HE 16,63,3) doesn't exist (illegal) to convert it to the dense index... 
So added "fake" cells will not be properly parsed to store them into DB.

**Comment by swagata87** [comment]
tried to put in a fix here: https://github.com/cms-sw/cmssw/pull/43681

**Pull request merged**
