### PR TITLE
cppcheck: some fixes for 9 modules

### PR DESCRIPTION
**Pull request by serval2412**
I changed a bit the regexp for the replace, hope it'll be ok.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by serval2412** [comment]
Argh, another case I had not taken into account with the regexp, so I must abandon the patch :-(

**Comment by davidlt** [comment]
@serval2412 I would suggest doing a visual inspection before submitting. If you want I can prep instructions (e.g. using _vagrant_ CentOS box) how to setup CMSSW for local compilation test also.

**Comment by serval2412** [comment]
@davidlt I had done an inspection partly but there were lots of changes. Even if I had left throught the whole of it, I could have missed it anyway.
Don't bother about prep instructions, I've been talked about it, it seems quite complicated compared to a "configure or autogen.sh" followed by a "make".

**Comment by serval2412** [comment]
Contributing to LibreOffice, I had created a doc for cppcheck (https://wiki.documentfoundation.org/Development/Cppcheck)
But it can be even more simple :
To build this soft, just 3 steps : 
1) git clone git://github.com/danmar/cppcheck.git
2) cd cppcheck
3) make
Then to launch : 
<cppcheck directory>/cppcheck --enable=all <directory of sources to analyze> >2 cppcheck_reports.txt

**Comment by davidlt** [comment]
Here it's more like (just an example). I could make some instructions based on vagrant or docker as you need CentOS.
```
# Checks that required system packages are installed and install APT-GET

curl -L -s -S -k -o ./bootstrap.sh http://cmsrep.cern.ch/cmssw/cms/bootstrap.sh
chmod +x ./bootstrap.sh
sh -ex ./bootstrap.sh -arch slc6_amd64_gcc493 -path $PWD/cmsinst -assume-yes -debug -only-once setup
. $PWD/cmsinst/slc6_amd64_gcc491/external/apt/*/etc/profile.d/init.sh

# Instal CMSSW and all externals packages from CMS repositories
# These are never installed as root and always on relocatable paths, quite flexible

apt-get update
apt-cache search CMSSW # find wanted release
apt-get install cms+cmssw+CMSSW_7_2_0_pre6

# Setup environment, this will get you SCRAM
# SCRAM manages packages, build software, etc.

. $PWD/cmsinst/cmsset_default.sh

scram p <name_of_cmssw>
cd <name_of_cmssw>
cmsenv

# Now you are in CMSSW environment of particular release
# git cms-addpkg <Subsystem/Package> to add something
# All source code lands in ./src directory

# Compile

scram b -v -k -j 8 2>&1 | tee b.log

# -v -- verbose
# -k -- keep going even if something fails
# -j N -- how many threads to use
```

**Comment by serval2412** [comment]
I'll give it a try(and update to CMSSW_8_0_X)

**Comment by davidlt** [comment]
There are no CMSSW_8_0_X releases yet, one IB (integration builds), but those are on separate alternating repositories. As I said, I could write a proper docker/vagrant instructions thus making it more trivial.

**Comment by serval2412** [comment]
Ok, for 8_0, will stick to your example.
For the rest, the easiest the build instructions are, the more people may involve.

Another point too, when I git fetch upstream then want to merge, it doesn't work (I don't have the error message in mind and am not at home to check), any idea why? (I haven't found it on FAQ)

**Comment by serval2412** [comment]
. $PWD/cmsinst/slc6_amd64_gcc491/external/apt/*/etc/profile.d/init.sh
gives:
/home/julien/projects/lhc/cmsinst/slc6_amd64_gcc491/external/apt/*/etc/profile.d/init.sh: No such file or directory
I've got cmsinst/slc6_amd64_gcc493 which contains var directory

**Pull request closed without merging**
