### PR TITLE
Revert "Cleanup Geant4 user actions 2"

### PR DESCRIPTION
**Pull request by lgray**
Reverts cms-sw/cmssw#15926

Comments as to why in the original PR.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1
fix of the problem will follow

**Comment by lgray** [comment]
@davidlange6 Any possibility of merging this so it gets in an IB?

**Comment by civanch** [comment]
@lgray , can you, please, check #16069 ? it should fix the issue.

**Comment by lgray** [comment]
Yep! Already checking.

**Comment by lgray** [comment]
@civanch OK - it seems things are working again with this fix in place. I am producing clusters for all particle types.

**Comment by lgray** [comment]
Closing this PR.

**Pull request closed without merging**
