### PR TITLE
[12_5_X] Fix try/catch in Vx3DHLTAnalyzer

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #39285
Fix the `try/catch` statement added in the DQM client `Vx3DHLTAnalyzer` to protect the client against Minuit2 FatalRootError.

#### PR validation:
The crash observed online is solved when applying this PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Backport of #39285

FYI @dinardo

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #39285

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
test parameters:

 - addpkg = DQM/Integration

**Comment by francescobrivio** [comment]
+db

 - 12_4_X backport tested succesfully in P5, see https://github.com/cms-sw/cmssw/pull/39341#issuecomment-1240473782

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
