### PR TITLE
Update GEN-SIM strings relval 106X

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:

Update GEN-SIM strings for Relval 106X

#### PR validation:

All the strings are taken from relvals submission in 10_6_0 release and tested locally. These strings correspond to existing input datasets on DAS, for example
2016 FullSim
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-106X_mcRun2_asymptotic_v3-v1%2FGEN-SIM
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-PU25ns_106X_mcRun2_asymptotic_v3-v1%2FPREMIX*
2017 FullSim
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-106X_mc2017_realistic_v3-v1%2FGEN-SIM
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-PU25ns_106X_mc2017_realistic_v3-v1%2FPREMIX*
2018 FullSim
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1%2FGEN-SIM
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2F*%2FCMSSW_10_6_0-PU25ns_106X_upgrade2018_realistic_v4-v1%2FPREMIX*

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@pgunnell, @zhenhu, @prebello, @chayanit many of the required samples are missing, causing massive failures in the IB tests: https://cmssdt.cern.ch/SDT/html/showIB.html.

Please try to produce all samples ASAP (and transfer them to CERN), otherwise I will have to revert this to make the IB useful.

**Comment by prebello** [comment]
@kpedro88 validation managers are taking a look on it. I guess that @Chayanit has changed more strings than actually needed because of the inputs from 10-4-0-pre1, 10-0-0-pre2 and 10-4-0

**Comment by zhenhu** [comment]
Hi Kevin, the failures are due to several different reasons. Some of the 2017 and 2018 GENSIMs are not available at CERN, for example, https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FRelValSMS-T1tttt_mGl-1500_mLSP-100_13%2FCMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1%2FGEN-SIM. 
Some of the pLHE strings shared by other workflows. 
So I want to suggest to revert this PR for now. 
We will commit a new one when all these issues are solved .

**Comment by prebello** [comment]
@kpedro88 for my education, could you use -ibeos command to avoid transferring files to CERN?

**Comment by kpedro88** [comment]
@prebello that's a question for @smuzaffar, but in general I think we don't want to run a lot of IB tests over AAA twice a day

**Comment by smuzaffar** [comment]
@prebello , @kpedro88 : --ibeos only works when we already have cached the data files at cern. This will happen once DAS knows about new data sets. Currently DAS does not return any thing so we can not cache or use AAA.

**Comment by kpedro88** [comment]
revert submitted here: #26995

**Comment by prebello** [comment]
Hi @fabiocos @kpedro88 
the problem detected and the missing relvals were injected today. (we had the same issue in 10-5-0-pre1)
In principle, no problems with this PR wrt GS strings. May we still use it instead of make a new PR?
 
Please let us know if you can test the IB properly when the relvals are available. Thank you

FYI @chayanit @zhenhu

**Comment by fabiocos** [comment]
@prebello @zhenhu @chayanit I think that the issues found can be prevented by a systematic check about the availability of the samples for all the standard IB tests. Running all the tests is possible but long, and not really needed in my opinion. With ```runTheMatrix.py -i all --dryRun``` you may extract all the ```dasgoclient``` queries that need to be satisfied, and test them one by one without actually running the complete list of tests (that is better done within an IB).

**Comment by zhenhu** [comment]
Hi @fabiocos , thank you, this seems a good solution. We will run this test when we update the strings next time.

**Comment by fabiocos** [comment]
@zhenhu @prebello having played myself with this, what really matters is not whether the query suceeed, as you ask for the files to be present on T2_CH_CERN, and normally they are not at the beginning. You should more extract datasets and check whether there is at least one site where they are present (i.e. whether they exist at all in DAS/DBS). If they exist the bot normally copy and cache them at CERN within a few IBs...

**Comment by prebello** [comment]
Hi @fabiocos I have sent information about the ready relvals and other strings that should have changed in principle to @zhenhu in skype that will follow it. (For instance, the official 2021 relvals should come with Run3RoundOptics25ns13TeVLowSigmaZ scenario and then 106X_upgrade2021_realistic_v4_LowSigmaZ-v1.) Thank you.

**Comment by chayanit** [comment]
@prebello , @fabiocos , I have updated 2021 string to LowSigmaZ under this PR #26875. I hope it is fine

**Pull request merged**
