### PR TITLE
Phase2-hgx107 Add a new shape for hexgonal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
This is the hexagonal geometry as would be used for HGCal silicon cells/wafers

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , as I understand this is work in progress, later this shape will be included in unit tests.

**Comment by bsunanda** [comment]
@civanch Yes it is work in progress. I have to get the access of information of geometry information to make reconstruction geometry. I can add a unit test later on

**Comment by bsunanda** [comment]
@fabiocos I shall add a useful unit test later on. I am right now working on reecho geometry and for this it is needed

**Comment by bsunanda** [comment]
@fabiocos I did some private test before committing this to repository

**Comment by fabiocos** [comment]
+1

**Pull request merged**
