### PR TITLE
[123X] Change ALCALUMIPIXELSEXPRESS to ALCALumiPixelsCountsExpress in autoAlCa.py

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/37306

#### PR validation:

N/A

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/37306

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37306

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+1

 - clean test results

**Pull request merged**
