### PR TITLE
Revert back to chi-square fit instead of likelihood fit

### PR DESCRIPTION
**Pull request by smuzaffar**
Revert to chi-square fit (see https://github.com/cms-sw/cmssw/issues/43722)
Revert of #43106 
Revert of #43170
Revert of #43490

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
urgent

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 , can you pllease review this? This is backport of https://github.com/cms-sw/cmssw/pull/43106 and the DQM comparison differences are expected as were for https://github.com/cms-sw/cmssw/pull/43106#issuecomment-1780900842

**Comment by tjavaid** [comment]
backport of #43106

**Comment by tjavaid** [comment]
+1

**Pull request merged**
