### PR TITLE
Restore PR 20657 with fix for wrong schedule order

### PR DESCRIPTION
**Pull request by fabiocos**
Reload of #20657 with the fix of the problem discussed in #21859

### CODE REVIEW

**Comment by fabiocos** [comment]
@mohsinwaseem @Dr15Jones This should restore PR 20657 and fix the problem causing the crash

**Comment by fabiocos** [comment]
please test workflow 136.7802

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
