### PR TITLE
HLT menu migration to 12_2_0_pre3

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu migration to 12_2_0_pre3

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #36374
HLT menu migration to 12_2_0_pre3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
backport of #36374

(just to add the label)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- HLT menu migration, ok for backport

**Pull request merged**
