### PR TITLE
Add HZZ electron ID for Run3

### PR DESCRIPTION
**Pull request by apetkovi1**
This PR is to add HZZ electron ID for Run 3. It has been tested with runTheMatrix (logs are in (1,2,3,4,5)). Also it has been tested with 2016 workflow since previously Run2 tests caused failure (log is in (6)) Additionally it has been tested privately to check if the sig. and bkg. efficiency correspond to the ones I got when testing during the training phase. Comparison is in (7). Essentially I ran testElectronMVARun3 and calculated sig and bkg efficiency in every region. Now, as you can see, testing with testElectronMVARun3 gave slightly better performance (higher sig and lower bkg eff) then test during the training phase. This is because I ran testElectronMVARun3 on a dataset which also partially includes the one which I used for training. This is because during the training phase I made random test/train splitting and did not save the test dataset. This is why I do not have completely unbiased testing sample  when I use testElectronMVARun3. However, when we take into account the fact that part of this dataset was used for training, the results are expected. Please test this PR together with this [one](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28/commits/c330c30df068d31247f2e752f2ae61645c70df2d). ID presentation is in (8).

(1) [step1_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526939/step1_TTbar_14TeV%2B2023.log)
(2) [step2_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526940/step2_TTbar_14TeV%2B2023.log)
(3) [step3_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526941/step3_TTbar_14TeV%2B2023.log)
(4) [step4_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526942/step4_TTbar_14TeV%2B2023.log)
(5) [step5_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526943/step5_TTbar_14TeV%2B2023.log)
(6) [step5_TTbar_13.log](https://github.com/cms-sw/cmssw/files/13527069/step5_TTbar_13.log)
(7) [MVAcomparison.pdf](https://github.com/cms-sw/cmssw/files/13526931/MVAcomparison.pdf)
(8) [ElectronID_EGamma_v2.pdf](https://github.com/cms-sw/cmssw/files/13545706/ElectronID_EGamma_v2.pdf)

### CODE REVIEW

**Comment by a-kapoor** [comment]
@apetkovi1 I just closed https://github.com/cms-sw/cmssw/pull/43369

**Comment by a-kapoor** [comment]
enable nano

**Comment by a-kapoor** [comment]
please test with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28

**Comment by apetkovi1** [comment]
Hi @a-kapoor, @Prasant1993 I am not sure why this fails - locally I was able to run runTheMatrix

**Comment by a-kapoor** [comment]
> Hi @a-kapoor, @Prasant1993 I am not sure why this fails - locally I was able to run runTheMatrix. Locally I do not have these logs (the ones where we can see error here).

Hi @apetkovi1 Can you check if you are able to run https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f7b9c7/36162/runTheMatrix-results/25202.0_TTbar_13/cmdLog

**Comment by apetkovi1** [comment]
Hi @a-kapoor I have updated runTheMatrix output dir with outpouts from these new tests [here](https://cernbox.cern.ch/s/6u8zUpW43lubAYI). When using your commands I recreate some of these errors (check step1,2,3,4,5_TTbar_13.log). Any idea what could cause them ?

**Comment by Prasant1993** [comment]
Hi @apetkovi1,

I am just trying to understand here a bit more.

About this HZZ ID in the past in Run2 UL16, I see you have only one variable (float) defined in the NanoAOD here : 

https://github.com/apetkovi1/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py#L244. 

(run2_egamma_2016).toModify(
    slimmedElectronsWithUserData.userFloats,
    mvaHZZIso = "electronMVAValueMapProducer:ElectronMVAEstimatorRun2Summer16ULIdIsoValues"
)
(run2_egamma_2017).toModify(
    slimmedElectronsWithUserData.userFloats,
    mvaHZZIso = "electronMVAValueMapProducer:ElectronMVAEstimatorRun2Summer17ULIdIsoValues"
)
(run2_egamma_2018).toModify(
    slimmedElectronsWithUserData.userFloats,
    mvaHZZIso = "electronMVAValueMapProducer:ElectronMVAEstimatorRun2Summer18ULIdIsoValues"
)

But for Run3 case,  you have 2 variables here. One is float and the other is int.
1) mvaHZZIso = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Winter22HZZV1Values") 
2) mvaIso_WPHZZ = cms.InputTag("egmGsfElectronIDs:mvaEleID-Winter22-HZZ-V1")

Do you really need these two in Run3 ? 

The above workflow is a Run2 workflow. So it doesn't find the second int variable for Run2. 
May be you can add the following :
"mvaIso_WPHZZ = None" here for Run2 : https://github.com/apetkovi1/cmssw/blob/Run3_HZZelectronID_V1p3/PhysicsTools/NanoAOD/python/electrons_cff.py#L222

Try to test again.

**Comment by apetkovi1** [comment]
Hi @Prasant1993 @a-kapoor, I added what you said but the message stays the same (not sure what could cause this since wpHZZ is sucesfully added to nano when running runTheMatrix). Now, if I would remove WPHZZ part from electrons_cff, working point would be added to miniAOD but not to nanoAOD ? (I still have HZZ working point defined in RecoEgamma/ElectronIdentification/python/FWLite.py)

**Comment by Prasant1993** [comment]
> Hi @Prasant1993 @a-kapoor, I added what you said but the message stays the same (not sure what could cause this since wpHZZ is sucesfully added to nano when running runTheMatrix, proably some conflict with Run2 since wpHZZ was not added to nano back then). Now, if I would remove WPHZZ part from electrons_cff, working point would be added to miniAOD but not to nanoAOD ? (I still have HZZ working point defined in RecoEgamma/ElectronIdentification/python/FWLite.py)

@apetkovi1, can you paste the error that you have got after did the necessary change for Run2 :  "mvaIso_WPHZZ = None" ?

**Comment by apetkovi1** [comment]
Hi @Prasant1993 - this is my command:

cmsDriver.py step5  -s NANO -n 10 --mc  --eventcontent NANOEDMAODSIM --datatier NANOAODSIM --conditions auto:run2_mc --era Run2_2016 --filein file:step3_inMINIAODSIM.root --nThreads 2  --customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport  --fileout file:step5.root  --suffix "-j JobReport5.xml "  > step5_TTbar_13.log  2>&1

This is the log:

NANO,ENDJOB
entry file:step3_inMINIAODSIM.root
Step: NANO Spec: 
in prepare_nano nanoSequenceMC
Step: ENDJOB Spec: 
customising the process with customiseWithTimeMemoryJobReport from Validation/Performance/TimeMemoryJobReport
customising the process with nanoAOD_customizeCommon from PhysicsTools/NanoAOD/nano_cff
Starting  cmsRun -j JobReport5.xml  step5_NANO.py
%MSG-i ThreadStreamSetup:  (NoModuleName) 30-Nov-2023 13:56:41 CET pre-events
setting # threads 2
setting # streams 2
%MSG
30-Nov-2023 13:56:48 CET  Initiating request to open file file:step3_inMINIAODSIM.root
30-Nov-2023 13:56:50 CET  Successfully opened file file:step3_inMINIAODSIM.root
                         : Booking "electronMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/el_BDTG_2016.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/el_BDTG_2016.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "electronMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/el_BDTG_2016.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/el_BDTG_2016.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "muonMVALowPt" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "muonMVALowPt" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "muonMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_2016.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_2016.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "muonMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_2016.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02813/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2023-11-28-2300/external/slc7_amd64_gcc12/data/PhysicsTools/NanoAOD/data/mu_BDTG_2016.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
%MSG-w LogicError:  GenWeightsTableProducer:genWeightsTable@beginRun  30-Nov-2023 13:57:04 CET Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'externalLHEProducer'.
The specified productInstanceName was ''.

%MSG
%MSG-w LogicError:  HTXSRivetProducer:rivetProducerHTXS@beginRun  30-Nov-2023 13:57:04 CET Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'externalLHEProducer'.
The specified productInstanceName was ''.

%MSG
%MSG-w LogicError:  GenWeightsTableProducer:genWeightsTable@beginRun  30-Nov-2023 13:57:04 CET Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'source'.
The specified productInstanceName was ''.

%MSG
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 1 at 30-Nov-2023 13:57:04.847 CET
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 on stream 0 at 30-Nov-2023 13:57:04.848 CET
#--------------------------------------------------------------------------
#                         FastJet release 3.4.1
#                 M. Cacciari, G.P. Salam and G. Soyez                  
#     A software package for jet finding and analysis at colliders      
#                           http://fastjet.fr                           
#	                                                                      
# Please cite EPJC72(2012)1896 [arXiv:1111.6097] if you use this package
# for scientific work and optionally PLB641(2006)57 [hep-ph/0512210].   
#                                                                       
# FastJet is provided without warranty under the GNU GPL v2 or higher.  
# It uses T. Chan's closest pair algorithm, S. Fortune's Voronoi code
# and 3rd party plugin jet algorithms. See COPYING file for details.
#--------------------------------------------------------------------------
%MSG-w LHETablesProducer:  GenWeightsTableProducer:genWeightsTable  30-Nov-2023 13:57:06 CET Run: 1 Event: 1
No LHEEventProduct, so there will be no LHE Tables

%MSG
Rivet.AnalysisHandler: INFO  Using named weights
==============================================================
========     HiggsTemplateCrossSections Initialization     =========
==============================================================
Rivet.Analysis.HiggsTemplateCrossSections: WARN  No HIGGSPRODMODE shell variable found. Needed when running Rivet stand-alone.
==============================================================
========             Higgs prod mode 0              =========
========          Sucessful Initialization           =========
==============================================================
Rivet.Analysis.HiggsTemplateCrossSections: WARN  Unkown Higgs production mechanism. Cannot classify event. Classification for all events will most likely fail.
Rivet.AnalysisHandler: INFO  Using named weights
Rivet.Analysis.HiggsTemplateCrossSections: WARN  Unkown Higgs production mechanism. Cannot classify event. Classification for all events will most likely fail.
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 on stream 0 at 30-Nov-2023 13:57:25.886 CET
Begin processing the 4th record. Run 1, Event 4, LumiSection 1 on stream 1 at 30-Nov-2023 13:57:25.895 CET
Rivet.Analysis.HiggsTemplateCrossSections: WARN  Unkown Higgs production mechanism. Cannot classify event. Classification for all events will most likely fail.
                         : Rebuilding Dataset Default
                         : Rebuilding Dataset Default
                         : Rebuilding Dataset Default
----- Begin Fatal Exception 30-Nov-2023 13:57:26 CET-----------------------
An exception of category 'UnknownUserInt' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 0
   [1] Running path 'NANOEDMAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'NANOEDMAODSIMoutput'
   [3] Calling method for module SimpleCandidateFlatTableProducer/'electronTable'
Exception Message:
Requested UserInt mvaIso_WPHZZ is not available! Possible UserInts are: 
ElectronMVAEstimatorRun2Fall17IsoV1Categories ElectronMVAEstimatorRun2Fall17IsoV2Categories ElectronMVAEstimatorRun2Fall17NoIsoV1Categories ElectronMVAEstimatorRun2Fall17NoIsoV2Categories ElectronMVAEstimatorRun2RunIIIWinter22IsoV1Categories ElectronMVAEstimatorRun2RunIIIWinter22NoIsoV1Categories ElectronMVAEstimatorRun2Spring16GeneralPurposeV1Categories ElectronMVAEstimatorRun2Spring16HZZV1Categories ElectronMVAEstimatorRun2Summer18ULIdIsoCategories ElectronMVAEstimatorRun2Winter22HZZV1Categories VIDNestedWPBitmapHEEP VIDNestedWPBitmap_Fall17V2 cutBasedElectronID-Fall17-94X-V1-loose cutBasedElectronID-Fall17-94X-V1-medium cutBasedElectronID-Fall17-94X-V1-tight cutBasedElectronID-Fall17-94X-V1-veto cutBasedElectronID-Fall17-94X-V2-loose cutBasedElectronID-Fall17-94X-V2-medium cutBasedElectronID-Fall17-94X-V2-tight cutBasedElectronID-Fall17-94X-V2-veto cutBasedElectronID-RunIIIWinter22-V1-loose cutBasedElectronID-RunIIIWinter22-V1-medium cutBasedElectronID-RunIIIWinter22-V1-tight cutBasedElectronID-RunIIIWinter22-V1-veto cutBasedElectronID-Summer16-80X-V1-loose cutBasedElectronID-Summer16-80X-V1-medium cutBasedElectronID-Summer16-80X-V1-tight cutBasedElectronID-Summer16-80X-V1-veto cutBasedID_Fall17V2_loose cutBasedID_Fall17V2_medium cutBasedID_Fall17V2_tight cutBasedID_Fall17V2_veto cutBasedID_HEEP heepElectronID-HEEPV70 heepElectronID-HEEPV71 mvaIso_Fall17V2_WP80 mvaIso_Fall17V2_WP90 mvaIso_Fall17V2_WPL mvaNoIso_Fall17V2_WP80 mvaNoIso_Fall17V2_WP90 mvaNoIso_Fall17V2_WPL seedGain 
----- End Fatal Exception -------------------------------------------------
Rivet.Analysis.HiggsTemplateCrossSections: WARN  Unkown Higgs production mechanism. Cannot classify event. Classification for all events will most likely fail.
Rivet.Analysis.HiggsTemplateCrossSections: INFO   ====================================================== 
Rivet.Analysis.HiggsTemplateCrossSections: INFO        Higgs Template X-Sec Categorization Tool          
Rivet.Analysis.HiggsTemplateCrossSections: INFO                  Status Code Summary                     
Rivet.Analysis.HiggsTemplateCrossSections: INFO   ====================================================== 
Rivet.Analysis.HiggsTemplateCrossSections: INFO       >>>> All 0 events successfully categorized!
Rivet.Analysis.HiggsTemplateCrossSections: INFO   ====================================================== 
Rivet.Analysis.HiggsTemplateCrossSections: INFO   ====================================================== 
30-Nov-2023 13:57:27 CET  Closed file file:step3_inMINIAODSIM.root

The MCnet usage guidelines apply to Rivet: see http://www.montecarlonet.org/GUIDELINES
Please acknowledge Rivet in results made using it, and cite https://arxiv.org/abs/1912.05451

This is era 2016 and it seems it is trying to find wpHZZ among Run 2 working points

**Comment by Prasant1993** [comment]
Can you try adding the following specifically for run2 2016 and test it again.

(run2_egamma_2016).toModify(
slimmedElectronsWithUserData.userIntFromBools,
mvaIso_WPHZZ = None
)

**Comment by Prasant1993** [comment]
Okay then. remove this one that changed specifically for run2_egamma_2016.

But keep the change you made for run2_egamma: here: "mvaIso_WPHZZ = None" here : https://github.com/apetkovi1/cmssw/blob/Run3_HZZelectronID_V1p3/PhysicsTools/NanoAOD/python/electrons_cff.py#L222

Commit your changes again to your branch. The pull request will be automatically updated. Let cmsbuild run a test again to see if we have the errors or not. It's difficult to figure it out  the test results from your local branch in your machine.

**Comment by apetkovi1** [comment]
Hi @Prasant1993, I updated PR - someone has to authorize tests

**Comment by a-kapoor** [comment]
> Hi @Prasant1993, I updated PR - someone has to authorize tests

Hi @apetkovi1 Did it pas the tests now?

**Comment by apetkovi1** [comment]
> Okay then. remove this one that changed specifically for run2_egamma_2016.
> 
> But keep the change you made for run2_egamma: here: "mvaIso_WPHZZ = None" here : https://github.com/apetkovi1/cmssw/blob/Run3_HZZelectronID_V1p3/PhysicsTools/NanoAOD/python/electrons_cff.py#L222
> 
> Commit your changes again to your branch. The pull request will be automatically updated. Let cmsbuild run a test again to see if we have the errors or not. It's difficult to figure it out the test results from your local branch in your machine.

Hi @a-kapoor

**Comment by vlimant** [comment]
Hi Everyone, I don't think that using cmsbot test is the best way to debug this. the matrix test are runable locally, so please do this to make sure things are running properly ; all this for the sake of not wasting your time

**Comment by a-kapoor** [comment]
@Prasant1993 @apetkovi1 Let us take the discussions here https://gitlab.cern.ch/cms-egamma/egamma-coordination/-/issues/6

**Comment by Prasant1993** [comment]
The reason I asked is it's not clear exactly what is going wrong in the workflow in local tests. But I agree we can discuss this in the gitlab issue that you created  and come back here after this is fixed.

**Comment by Prasant1993** [comment]
Hi @vlimant, the issue is fixed. We can now go ahead and trigger the test.

**Comment by apetkovi1** [comment]
Hi @a-kapoor, the PR is updated now with the fix

**Comment by a-kapoor** [comment]
please test with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28

**Comment by apetkovi1** [comment]
> @apetkovi1 I understand these messages are expected, right? %MSG-w IdInformation: VersionedGsfElectronIdProducer:egmGsfElectronIDs@ctor DATETIME CET pre-events Instantiated ID: mvaEleID-Winter22-HZZ-V1 with MD5 hash: This ID is not POG approved and likely under development!!! Please make sure to report your progress with this ID at the next relevant POG meeting. Thanks

Hi @jfernan2, yes, it is setted in this [line ](https://github.com/apetkovi1/cmssw/blob/5e83772f24275fe9f95d4cb3b47fb497b787b21c/RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Winter22_HZZ_V1_cff.py#L49)

**Comment by a-kapoor** [comment]
> > @apetkovi1 I understand these messages are expected, right? %MSG-w IdInformation: VersionedGsfElectronIdProducer:egmGsfElectronIDs@ctor DATETIME CET pre-events Instantiated ID: mvaEleID-Winter22-HZZ-V1 with MD5 hash: This ID is not POG approved and likely under development!!! Please make sure to report your progress with this ID at the next relevant POG meeting. Thanks
> 
> Hi @jfernan2, yes, it is setted in this [line ](https://github.com/apetkovi1/cmssw/blob/5e83772f24275fe9f95d4cb3b47fb497b787b21c/RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Winter22_HZZ_V1_cff.py#L49)

Hi @apetkovi1 Has there been any changes with respect to the last presentation that was shared with EGM? We would like to mark this as approved before merging this PR.

**Comment by apetkovi1** [comment]
Hi @a-kapoor, only one thing - I changed from particle isolations in training to cluster

**Comment by jfernan2** [comment]
+1

**Comment by apetkovi1** [comment]
> > Hi @a-kapoor, only one thing - I changed from particle isolations in training to cluster
> 
> Can you attach the updated slides to the description ? We will circulate those internally and if all looks good, we will tell you to change the isPOGApproved flag to True.Then we are all set.

Hi @a-kapoor, ok, I'll update slides and add them to description

**Comment by apetkovi1** [comment]
> This PR is to add HZZ electron ID for Run 3. It has been tested with runTheMatrix (logs are in (1,2,3,4,5)). Also it has been tested with 2016 workflow since previously Run2 tests caused failure (log is in (6)) Additionally it has been tested privately to check if the sig. and bkg. efficiency correspond to the ones I got when testing during the training phase. Comparison is in (7). Essentially I ran testElectronMVARun3 and calculated sig and bkg efficiency in every region. Now, as you can see, testing with testElectronMVARun3 gave slightly better performance (higher sig and lower bkg eff) then test during the training phase. This is because I ran testElectronMVARun3 on a dataset which also partially includes the one which I used for training. This is because during the training phase I made random test/train splitting and did not save the test dataset. This is why I do not have completely unbiased testing sample when I use testElectronMVARun3. However, when we take into account the fact that part of this dataset was used for training, the results are expected. Please test this PR together with this [one](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28/commits/c330c30df068d31247f2e752f2ae61645c70df2d). ID presentation is in (8).
> 
> (1) [step1_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526939/step1_TTbar_14TeV%2B2023.log) (2) [step2_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526940/step2_TTbar_14TeV%2B2023.log) (3) [step3_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526941/step3_TTbar_14TeV%2B2023.log) (4) [step4_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526942/step4_TTbar_14TeV%2B2023.log) (5) [step5_TTbar_14TeV+2023.log](https://github.com/cms-sw/cmssw/files/13526943/step5_TTbar_14TeV%2B2023.log) (6) [step5_TTbar_13.log](https://github.com/cms-sw/cmssw/files/13527069/step5_TTbar_13.log) (7) [MVAcomparison.pdf](https://github.com/cms-sw/cmssw/files/13526931/MVAcomparison.pdf) (8) [ElectronID_EGamma_v2.pdf](https://github.com/cms-sw/cmssw/files/13545706/ElectronID_EGamma_v2.pdf)

Hi @a-kapoor, I have added updated presentation

**Comment by a-kapoor** [comment]
@apetkovi1 Please change the POG approved flag to True

**Comment by apetkovi1** [comment]
> @apetkovi1 Please change the POG approved flag to True

Hi @a-kapoor, done.

**Comment by a-kapoor** [comment]
enable nano

**Comment by a-kapoor** [comment]
please test with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28

**Comment by RSalvatico** [comment]
type egamma

**Comment by vlimant** [comment]
can you please verify that the plots in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_0_X_2023-12-06-1100+f7b9c7/60182/validateJR.html are what you would expect to see ?

**Comment by apetkovi1** [comment]
> > > can you please verify that the plots in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_0_X_2023-12-06-1100+f7b9c7/60182/validateJR.html are what you would expect to see ?
> > 
> > 
> > Hi @vlimant, if this has been ran on TTbar then I cannot validate since my BDT is trained on DY.
> 
> Hi @apetkovi1 That is not the right approach here. On a physics point of view, are those plots expected? Hi @vlimant Can you help me with what the new and ref is here? This ID is added for Run 3 for the first time.

Hi @a-kapoor, looking at the distribution, it is hard to tell does it make sense. Can you specify the name of the dataset this has been ran on ? I can try following things:

- check the HZZ ID distribution for Run2 version of that sample, if it's close to this one then we are probably fine
- circulate these plots within HZZ

**Comment by a-kapoor** [comment]
> > > > can you please verify that the plots in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_0_X_2023-12-06-1100+f7b9c7/60182/validateJR.html are what you would expect to see ?
> > > 
> > > 
> > > Hi @vlimant, if this has been ran on TTbar then I cannot validate since my BDT is trained on DY.
> > 
> > 
> > Hi @apetkovi1 That is not the right approach here. On a physics point of view, are those plots expected? Hi @vlimant Can you help me with what the new and ref is here? This ID is added for Run 3 for the first time.
> 
> Hi @a-kapoor, looking at the distribution, it is hard to tell does it make sense. Can you specify the name of the dataset this has been ran on ? I can try following things:
> 
>     * check the HZZ ID distribution for Run2 version of that sample, if it's close to this one then we are probably fine
> 
>     * circulate these plots within HZZ

I think let's wait for @vlimant to help us understand what are these. I am also confused what is the ref. Are these Run2 vs Run3 or older nano vs newer nano. Maybe we might be able to answer the question here itself.

**Comment by vlimant** [comment]
hello, you will find relevant information within https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f7b9c7/36352/runTheMatrixNANO-results/ 
in particular 2500.1 is running on /TTToSemiLeptonic_TuneCP5_13p6TeV-powheg-pythia8/Run3Winter22MiniAOD-FlatPU0to70_122X_mcRun3_2021_realistic_v9-v2/MINIAODSIM and showing this 

 where Electron mvaHZZIso is modified when running form old MINI input.
Same is also present for more recent input
If the change is only relevant for run3, the old ID might have to be kept around for run2 MC/data through the relevant modifiers

**Comment by Prasant1993** [comment]
Hi @vlimant,

The old ID "mvaHZZIso" is already present for Run2 data/MC for 2016, 2017 and 2018 through era modifiers here : https://github.com/apetkovi1/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py#L244

We are not keeping the Run2 IDs in Run3 NANOAOD anymore.
Also Run3 IDS are not kept in Run2 NANOAOD. 
The current PR is only to store the Run3 "mvaHZZIso" ID in Run3 NANOAOD.
I guess this answers your query.

**Comment by apetkovi1** [comment]
Hi @vlimant, are there any showstoppers regarding this PR ?

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
there was something fishy on Dec 8, and no change ever since, so I don't think this can move on

**Comment by a-kapoor** [comment]
@apetkovi1 Let's wait for results from these tests and start the discussions again.

**Comment by apetkovi1** [comment]
Hi @a-kapoor, @Prasant1993 can you reopen the gitlab issue - we can take the discussion there ?

**Comment by apetkovi1** [comment]
I see now in error log that test fails to find MVA weights, is the PR tested together with this [one](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28/commits/c330c30df068d31247f2e752f2ae61645c70df2d) ?

**Comment by Prasant1993** [comment]
Hi @vlimant  Please issue the test command with the PR https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28/

The weight files PR is not merged yet.

**Comment by a-kapoor** [comment]
Hi @vlimant 
So a new ID has been 
So the older values in Run3 Nanos were using :
https://github.com/cms-sw/cmssw/blob/e8154a2ff2a04ce4431ed5ed83d6ae84913c90c3/PhysicsTools/NanoAOD/python/electrons_cff.py#L158

Which has now changed to 

https://github.com/cms-sw/cmssw/blob/9eeb80d581089ac4d883b1cc6fff952df83e5f94/PhysicsTools/NanoAOD/python/electrons_cff.py#L159

This is now the default.
 
The differences in this https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_0_X_2024-01-10-2300+f7b9c7/60552/validateJR.html make sense since the new ID are not extremely different, but just a "Run 3" fine-tuned version. The "Run 2" version was used for Run 3 as well till Nanov13 since the new trained ID was not available at that point.

It makes sense here that the new ID for ttbar tells us there is more background:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsNANO/CMSSW_14_0_X_2023-12-06-1100+f7b9c7/60182/validateJR/2500.21_NANOdata124Xrun3/all_NANO_step2/c_Electron_mvaHZZIso.png
because most of ttbar is background anyway. The new ID does what it should do.  

Even for Mini, It makes sense that the size of userfloat and userints change by "1":
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-01-10-2300+f7b9c7/60553/validateJR/25.0_TTbar/all_mini_RECO_step3_inMINIAODSIM/c_patElectrons_slimmedElectrons__RECO_obj_userInts_AT_size.png
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-01-10-2300+f7b9c7/60553/validateJR/25.0_TTbar/all_mini_RECO_step3_inMINIAODSIM/c_patElectrons_slimmedElectrons__RECO_obj_userFloats_AT_size.png
, which is what causes the differences in reco.

Overall, the changes are expected.

Tests are all passed, and it would be awesome if this could go ahead. Let me know.

Tagging @RSalvatico @apetkovi1 @Prasant1993

**Comment by vlimant** [comment]
got it

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
