### PR TITLE
[130X] Pileup 2023 august

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

Backport of PR #42474 

#### PR validation:

I didn't run any validation.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of #42474 .

### CODE REVIEW

**Comment by malbouis** [comment]
please test

**Comment by malbouis** [comment]
@cms-sw/simulation-l2  , would you please sign this backport, in case you agree? Thanks!

**Comment by civanch** [comment]
+1

DAS error has nothing to do with this PR

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
