### PR TITLE
Update Alpaka to version 1.1.0 [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the CMSSW utilities for Alpaka v1.1.0.

This is required to go together with https://github.com/cms-sw/cmsdist/pull/9010 .

#### PR validation:

Unit tests pass.

#### Backport status

Backport of #43772 from the same branch.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #43772

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#9010

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by fwyzard** [comment]
urgent

for CMSSW_14_0_0, as discussed at the ORP on 2024/02/13

**Pull request merged**
