### PR TITLE
SiPixelQuality backport for CMSSW 10_1_X: bugfix and memory cost mitigation

### PR DESCRIPTION
**Pull request by tocheng**
Backport of PR #22853  to CMSSW_10_1_X:

fix the bug and mitigate the memory cost in PCL harvester for SiPixelQuality payload production

### CODE REVIEW

**Comment by tocheng** [comment]
Hello, @tvami, @tsusa, @veszpv, this is something you want to follow.
Hello, @boudoul , this is something you may want to follow.
Thanks.

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
