### PR TITLE
MTD validation: update standalone test configuration to scenario D76, use up-to-date fragments

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Update of the standalone test configuration in ```Validation/MtdValidation/test``` to use geometry scenario D76, the more modern definition of geometry fragments, and newly introduced flags for expert checks.

#### PR validation:

The cfg correctly runs on the output of wf 34634.0 and provides the desired output.

### CODE REVIEW

**Comment by fabiocos** [comment]
@gsorrentino18 @casarsa FYI

**Comment by fabiocos** [comment]
please test

merely formal, the updated cfg is not probed by PR test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
