### PR TITLE
Correct one filterBit name in EGMNano and add one more

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

Make the final filter of `HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoV` consistent with the new naming convention, as pointed out by @missirol in https://github.com/cms-sw/cmssw/pull/44524#discussion_r1536670975. The name had already been changed in 140X.

Moreover, I have added another filterBit for `HLT_Ele115_CaloIdVT_GsfTrkIdT`.

#### PR validation:

Nothing special to validate besides what was already done in #44496 and #44524.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by hqucms** [comment]
> Moreover, I have added another filterBit for HLT_Ele115_CaloIdVT_GsfTrkIdT.

@RSalvatico This was not in 14_0_X, right? I suppose you would want a backport?

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by RSalvatico** [comment]
> > Moreover, I have added another filterBit for HLT_Ele115_CaloIdVT_GsfTrkIdT.
> 
> @RSalvatico This was not in 14_0_X, right? I suppose you would want a backport?

I didn't think it was still possible, but if it is then I'll make it!

**Comment by hqucms** [comment]
> > > Moreover, I have added another filterBit for HLT_Ele115_CaloIdVT_GsfTrkIdT.
> > 
> > 
> > @RSalvatico This was not in 14_0_X, right? I suppose you would want a backport?
> 
> I didn't think it was still possible, but if it is then I'll make it!

@RSalvatico Please make one and we will see at today's ORP.

**Comment by RSalvatico** [comment]
> > > > Moreover, I have added another filterBit for HLT_Ele115_CaloIdVT_GsfTrkIdT.
> > > 
> > > 
> > > @RSalvatico This was not in 14_0_X, right? I suppose you would want a backport?
> > 
> > 
> > I didn't think it was still possible, but if it is then I'll make it!
> 
> @RSalvatico Please make one and we will see at today's ORP.

Done, thanks. #44812

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
