### PR TITLE
ComphepSingletopFilterPy8 input tag bug fix for CMSSW_7_1_X

### PR DESCRIPTION
**Pull request by alexeybaskakov**

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
ah, I forgot: can you please add the InputTag in the example python file?

**Comment by davidlange6** [comment]
is the last comment still to be addressed?

**Comment by perrozzi** [comment]
@alexeybaskakov can you please take action?
"can you please add the InputTag in the example python file?"

**Comment by alexeybaskakov** [comment]
Dear @perrozzi sorry for the delay, I didn't understand first comment correctly. 
Is now everything right with InputTag?

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
