### PR TITLE
Use esConsumes with SiPixelStatusProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- added use of esConsumes
- regenerate SiPixelTopoFinder on each Run boundary rather than  try to allow reuse to simplify code and decouple from use of  SerialTaskQueue. This should have no performance effect as concurrent Runs are not yet supported in the framework and when they are implemented very, very few workflows will ever cross Run boundaries.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
