### PR TITLE
Updates to Tau and Jet calibration LUTs, and emulation algorithm fixe…

### PR DESCRIPTION
**Pull request by mulhearn**
Updates to Tau and Jet LUTs, and emulator fixes to improve agreement with firmware.  Requires a cms-data PR.

### CODE REVIEW

**Comment by mulhearn** [comment]
Actually, seems the cms-data PR was already done...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
