### PR TITLE
[L1] Protect from "Called C++ object pointer is null" warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Analysis reports: [1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-063a6b.html#EndPath), [2](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-0a75c8.html#EndPath), [3](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-25404a.html#EndPath)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
