### PR TITLE
Remove static pointer holding Pandora

### PR DESCRIPTION
**Pull request by lgray**
An attempt at fixing an issue where rechits provided to pandora would not point back to PFRecHits original provided in memory. Best guess is that putting the rather sneaky circumventions of const-correctness within pandora did not play nicely with being pointed to by a static pointer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
What is the plan for making this thread friendly?

**Comment by Dr15Jones** [comment]
Sorry, I missed that this was SLHC.

**Comment by lgray** [comment]
@Dr15Jones I need to speak with John Marshall and Mark Thompson about this. Their framework is inherently not threadsafe.

**Comment by mark-grimes** [comment]
merge

**Pull request merged**
