### PR TITLE
Skim on NoBPTX primary dataset for EXO (92X)

### PR DESCRIPTION
**Pull request by jalimena**
backport of #19521 . 
This PR creates a skim on the the NoBPTX dataset for EXO-16-004, EXO-17-004, and HCal DPG noise studies. No event selection criteria are applied, but the event content is greatly reduced from RECO. Furthermore, this skim need only be applied to the NoBPTX dataset, which is already quite small.
The approval talk in the PPD meeting is here: https://indico.cern.ch/event/651440/contributions/2651033/attachments/1489030/2313761/NoBPTXExoSkim_PPDMeeting_6July2017.pdf

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
please test workflow 136.735

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by jalimena** [comment]
hi all, @davidlange6 , this PR has been sitting around for a week, although I think it should be ready to be merged... just making sure it's not forgotten. thanks!

**Comment by fabozzi** [comment]
@jalimena 
Do you need the skim to be run in next round of 2016 legacy re-reco with 80X? If so, please provide a 80X backport

**Comment by jalimena** [comment]
no, we should be all set, @fabozzi

**Comment by davidlange6** [comment]
+1

**Pull request merged**
