### PR TITLE
Hcal qie extension for74x

### PR DESCRIPTION
**Pull request by clemencia**
New class, QIEDataExtended, adding two new columns to QIEData: QIEbarcode and QIEchannel to allow bookeeping.

The code will break RelVal tests unless a tag is included in prep DB, which was agreed with CondDB experts they'd upload when the new class is in an IB or pre-release.

### CODE REVIEW

**Comment by clemencia** [comment]
Hi,

This is because both chicken and egg need to exist for these tests:) In order for the object to exist in the (prep) DB the code has to exist in an IB or pre-release.  

I have made a local sqlite and DIGI tests run fine with it.

Cheers,
Clemencia

**Comment by davidlange6** [comment]
I suggest making a PR for the CondFormat - getting that accepted and populated and then later things that depend on it can be considered.

**Comment by abdoulline** [comment]
Could you, please, elaborate on PR for CondFormat way of submission, David?
This is not a new DB object which can be first committed without being put in action, and then later activated at a convenient moment. This is a replacement of the actually used object / DB record...

**Comment by davidlange6** [comment]
i'm not sure I understand the concept of a replacement that apparently cannot coexist with the thing it is replacing - but in any case, you should talk to AlCa.

**Comment by abdoulline** [comment]
I'd think replacement it not something unusual in the development...
Obviously when a completely new DB object is introduced (instead 
configurables, for instance) - it's simpler, of course.

We are talking to AlCaDB. Here is a quote from Andreas:
<...>
check with the DB experts again once the development is stable (i.e. just 
before you make the PR) who then can manually upload the sqlite file to 
the “prep” DB from where it can then be used by the IBs and the next 
pre-release. Once your new code is in a pre-release, you’ll have to tell 
the DB experts again so they can switch the dropbox machinery to use that 
pre-release so that you can upload the conditions also to the production 
DB.
<...>

But we've decided to submit PR a bit in advance (it stayed too long as a 
private branch) both for announcing and testing purposes.
Right now there are some issues in the dropbox for 74X, making Andreas at 
al. busy (as he has kindly informed us yesterday).

**Comment by davidlange6** [comment]
Sounds like the right things are happening then.

But in any case, the stuff in CondFormats looks new to me. so I'm not sure what the issue is with just getting a PR with that in now.

**Comment by abdoulline** [comment]
This PR needs new conditions record, and while it has been tested 
successfully in a private Digitization (when reading new conditions from 
sql file), to be merged it would need a new DB record, which doesn't exist 
(yet) so it will crash runTheMatrix...

**Comment by davidlange6** [comment]
yes, I understand that the PR as it stands news the new conditions record, which you can't have until you have the PR.. I'm suggesting a way out:)

**Comment by abdoulline** [comment]
Ah, I see now... I should have understood your yesterday's suggestion 
right away. 
Let me check with the actual developer(s) how to 
better factor out CondFormat stuff, removing it's actual usage.
Thank you!

**Comment by clemencia** [comment]
I will try to decouple CondFormats/DataRecord and CondFormats/HcalObjects from the rest  for a new PR today.
Thanks!

**Comment by clemencia** [comment]
Following your suggestion I've made a new PR #7597 with only the CondFormats packages.

**Pull request closed without merging**
