### PR TITLE
Boosted double SV tagger (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #9120 

@cvernier

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@ferencek  Were the externals actually updated in 74X as well?
The code is not running in the jenkins workflows, so the tests will pass.

**Comment by ferencek** [comment]
@slava77, starting with CMSSW_7_4_X_2015-05-18-1100, the externals have been included in 74X as well
```bash
ll /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-05-18-1100/external/slc6_amd64_gcc491/data/RecoBTag/

total 2
lrwxr-xr-x. 1 cmsbuild zh 89 May 18 19:54 SecondaryVertex -> ../../../../../../../cms/data-RecoBTag-SecondaryVertex/V02-00-00/RecoBTag/SecondaryVertex
lrwxr-xr-x. 1 cmsbuild zh 79 May 18 19:54 SoftLepton -> ../../../../../../../cms/data-RecoBTag-SoftLepton/V01-00-01/RecoBTag/SoftLepton
```

**Comment by ferencek** [comment]
Also, PAT tests should be running the new code (namely, PhysicsTools/PatAlgos/test/patTuple_addBTagging_cfg.py) so any problems with missing externals should crash some of the PAT tests.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9150	231fd77
- same code was signed off for 75X in 9120
- the new taggers are not a part of RECO or miniAOD workflows; so, no changes expected there

**Comment by slava77** [comment]
@monttj please check this PR and comment if there are remaining issues with an AT signature, or sign otherwise.
Thank you very much.

**Comment by monttj** [comment]
+1

**Comment by ferencek** [comment]
Can we push this one into the next 74X release?

**Comment by davidlange6** [comment]
@ferencek - has been on my list - but is there an easy way to confirm that this does not change miniAOD?

**Comment by slava77** [comment]
@davidlange6 
https://github.com/cms-sw/cmssw/pull/9150#issuecomment-103694091 
More explicit, from tests logs in #9120 
```
step5 in 25202, reusing input from CMSSW_7_5_X_2015-05-16-1100:
- timing is about the same 
- no new modules called
```

**Comment by davidlange6** [comment]
Good - this is a subset of the requirements for not changing mini-aod:)

**Comment by ferencek** [comment]
@davidlange6, the intention was to leave MiniAOD intact which Slava's logs confirm.

**Comment by davidlange6** [comment]
@ferencek - ok thanks - i fear little that gets tested confirms this so I was looking for confirmation on the intent of the PR

**Pull request merged**
