### PR TITLE
DQM: new DQMGlobalEDAnalyzer

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:
This PR imports more features from the "new DQMStore" project:

- A new `DQMEDAnalyzer` base class, now based on `EDProducer`, like all the other DQM module base classes. This is to make sure that everything that _produces_ DQM histograms actually is known to the EDM framework as a _Producer_, even if the data still flows through the `DQMStore`; otherwise, we have no guarantees that modules will run in the correct order.

- Some cleanup removing unused declarations in `DQMStore.h`, including `fastmatch`. The previous cleanup PRs left these unused.

Update: some things went into #28612, removed here now.

#### PR validation:

The challenge with this PR is that `DQMGlobalEDAnalyzer`s are primarily used in HLT, and I am not sure how to test them there. For now, HLT configs should reliably crash due to the incorrect module type used in the auto-generated configs; I am not sure how to change this part of the code. Also `FastTimerService` and `ThroughputService` need to be checked. Let's see if any of that is picked up in the PR tests, else I'll have to defer that to the HLT experts.

### CODE REVIEW

**Comment by schneiml** [comment]
please test

Mostly to see if there is a workflow that blows up due to incorrect configuration, and if the `DQMGlobalEDAnalyzer` MEs  still end up in the output.

**Comment by schneiml** [comment]
There seem to be no additional changes on top of  #28379. Good.

**Comment by schneiml** [comment]
please test

The results should be identical to  #28379.

**Comment by schneiml** [comment]
The results here are a bit inconclusive: the RelMon comparison finds some changes around the message logger, but I can't really tell if we have more or less warnings now. Some changes are similar to #28379, but there are clearly more here. 

But then the DQMHistoSizes reports a size change at `Tracking/TrackParameters` that is not visible in RelMon. Maybe I'll try to download the result files and run the bin-to-bin tool myself to make sense of that.

**Comment by schneiml** [comment]
I produced a local comparison *versus #28379* here: https://mschneid.web.cern.ch/mschneid/dqm-histo-comparison-summary.html

It seems we have a systematic change regarding the MessageLogger, not sure what causes that.

**Comment by schneiml** [comment]
please test

This should be clean apart from whatever MessageLogger difference we had before.

**Comment by schneiml** [comment]
Not sure what is going on here. I'll investigate.

**Comment by smuzaffar** [comment]
please test

**Comment by schneiml** [comment]
please test

Let's see if these new tests actually work...

**Comment by schneiml** [comment]
please test

These changes where tested many times and should be fine.

**Comment by schneiml** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

**Comment by fabiocos** [comment]
@schneiml @Martin-Grunewald with reference to the comments in the initial PR discussion about validation: can we consider the PR test exhaustive enough, or do you consider anything more should be tested, before this PR is integrated?

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Please see this comment:
```
The challenge with this PR is that DQMGlobalEDAnalyzers are primarily used in HLT, and I am not sure how to test them there. For now, HLT configs should reliably crash due to the incorrect module type used in the auto-generated configs; I am not sure how to change this part of the code. Also FastTimerService and ThroughputService need to be checked. Let's see if any of that is picked up in the PR tests, else I'll have to defer that to the HLT experts.
```

**Comment by schneiml** [comment]
@fabiocos @Martin-Grunewald @fwyzard I don't have any concrete fear directly related to `DQMGlobalEDAnalyzer`: some modules based on it are used in the PR tests and work.

My main concern here is if the HLT configuration machinery can handle the fact that the DQM modules are now `EDProducer`s, which usually requires a change to the config files.

(Also there might be problems due to the new edm dependencies, but if these are a problem, things are most likely broken today.)

**Comment by fwyzard** [comment]
Do the matrix workflows that include the HLT run without problems ?

**Comment by fwyzard** [comment]
> The challenge with this PR is that `DQMGlobalEDAnalyzer`s are primarily used in HLT, and I am not sure how to test them there.

Running `HLTrigger/Configuration/test/OnLine_HLT_GRun.py`¹ over 2018 data should be a reasonable validation step.

----
¹ possibly minus the customisation near the end
```
# add specific customizations
_customInfo = {}
_customInfo['menuType'  ]= "GRun"
_customInfo['globalTags']= {}
_customInfo['globalTags'][True ] = "auto:run2_hlt_GRun"
_customInfo['globalTags'][False] = "auto:run2_mc_GRun"
_customInfo['inputFiles']={}
_customInfo['inputFiles'][True]  = "file:RelVal_Raw_GRun_DATA.root"
_customInfo['inputFiles'][False] = "file:RelVal_Raw_GRun_MC.root"
_customInfo['maxEvents' ]=  100
_customInfo['globalTag' ]= "auto:run2_hlt_GRun"
_customInfo['inputFile' ]=  ['file:RelVal_Raw_GRun_DATA.root']
_customInfo['realData'  ]=  True
from HLTrigger.Configuration.customizeHLTforALL import customizeHLTforAll
process = customizeHLTforAll(process,"GRun",_customInfo)
```

**Comment by schneiml** [comment]
@fwyzard any recommendations for workflows beyond the short matrix? PR tests are fine, obviously.

For `OnLine_HLT_GRun.py`: I can give that a try tomorrow. However, if that is the full serialized configuration, it will 100% crash, since the module type of the DQM modules changed.

**Comment by fwyzard** [comment]
Yes,  that is the full configuration, and yes, that is the most relevant workflow that needs to work.

You could add a customisation fragment in [`HLTrigger/Configuration/python/customizeHLTforCMSSW.py`](https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/customizeHLTforCMSSW.py) to make the necessary changes to the python configuration.

Then, once the PR is merged, the same changes can be imported in the master configuration in the database.

**Comment by Martin-Grunewald** [comment]
The addONTests (run as part of the automatic PR testing) do run HLTrigger/Configuration/test/OnLine_HLT_GRun.py and since it does not crash, somehow the module is not in that config, or is not excercised or the old version still exists???

**Comment by Martin-Grunewald** [comment]
@fwyzard 
I think the worry was more about FastTimerService and ThroughputService...

**Comment by schneiml** [comment]
@fwyzard @Martin-Grunewald  `HLTrigger/Configuration/test/OnLine_HLT_GRun.py` does indeed not seem to load any DQM modules:
```
grep -E 'PSMonitor|DaqTestHistograms|LumiMonitor|TriggerBxVsOrbitMonitor|TriggerBxMonitor|TriggerRatesMonitor' HLTrigger/Configuration/test/OnLine_HLT_GRun.py
<no results>
```

`FastTimerService` seems to be loaded, but I did not actually run the config so far. But `FastTimerService` also runs offline, as far as I know?

**Comment by schneiml** [comment]
For the record: Fully signed, but waiting for a confirmation from HLT.

**Comment by schneiml** [comment]
Still waiting, not sure if anybody at HLT is aware that we are waiting?

Might be something that @missirol could also test once the setup for #28588 works.

**Comment by Martin-Grunewald** [comment]
Please proceed!

**Comment by silviodonato** [comment]
@schneiml shall we wait for #28588 before merging this PR?

**Comment by schneiml** [comment]
@silviodonato no, these two should be completely independent, either can go first.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
