### PR TITLE
Extra members in CSCCorrelatedLCTDigi to determine its original components

### PR DESCRIPTION
**Pull request by dildick**
When CSCCorrelatedLCTDigis are constructed, some information of the original CSCALCTDigi and CSCCLCTDigi gets lots. As a result is not easy to determine which ALCT and CLCT where involved in the LCT construction. In particular in Phase-2 scenarios where GEMPadDigis are combined with CSCALCTDigi and/or CSCCLCTDigi it becomes even more complicated to determine where the CSCCorrelatedLCTDigis came from. This pull request will make the task of debugging the emulator much easier.

I added a member `type_` which can be 
* CLCT-ALCT (classic case)
* ALCT-CLCT (upgrade case for MEX/1)
* ALCT-CLCT-1GEM (1 GEM pad)
* ALCT-CLCT-2GEM (GEM coincidence pad)
* ALCT-2GEM (substitute CLCT for GEM coincidence pad)
* CLCT-2GEM (substitute ALCT for GEM coincidence pad)

In addition I added members to get the original CSCALCTDigi, CSCCLCTDigi and GEMPadDigi. 

Finally I deleted two implementations of `constructLCTs`, one in CSCMotherBoardME11, one in CSCMotherBoardME11GEM. Both were unused in the algorithm.

@Dr15Jones Referring to the discussion on the Framework and Edm Development HN, I find this implementation much more straightforward and easier to implement. Which is why I opted not to use edm::Ref. 

@tahuang1991

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
I updated the class version of `csctf::TrackStub`

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
Hi, are there more comments on this pull request?

**Comment by dildick** [comment]
@rekovic Do you have any comments on this PR?

**Comment by dildick** [comment]
@mulhearn @rekovic could you please review and sign?

**Comment by dildick** [comment]
@mulhearn @rekovic please sign

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
