### PR TITLE
DQM for HLT_Ele27_WPLoose_Gsf_WHbbBoost_v1 - 74X

### PR DESCRIPTION
**Pull request by silviodonato**
This PR add the validation cod for the trigger HLT_Ele27_WPLoose_Gsf_WHbbBoost_v1 (https://its.cern.ch/jira/browse/CMSHLT-343)

PR in 75X: #9438
First attempt in 74X: https://github.com/cms-sw/cmssw/pull/9439

### CODE REVIEW

**Comment by silviodonato** [comment]
Ok, this time it seems ok!

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
