### PR TITLE
[12_4 Bug Fix] Remove GenFilter when pgen_smear is used

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/43561

#### PR validation:
-

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
-

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
type urgent

Need for production.

**Comment by srimanob** [comment]
@cms-sw/orp-l2 

We just fix this. Would it be possible to merge it when PR passes the test (both master and here), and make new release for 12_4? This will need for production.
FYI @drkovalskyi

**Comment by drkovalskyi** [comment]
We would like to get it into production asap so that we can use the holiday break to process a special background sample that is need for the new muon identification, used in Run3 analysis aiming Winter conferences.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
