### PR TITLE
Integration of the new Lumi PCC workflow in PCL and Prompt-Reco: backport to 10.0

### PR DESCRIPTION
**Pull request by cerminar**
This is the backport of #22590.

The following features have been added:
1. PCL workflow for PCC correction computation on dedicated ALCARAW
2. Prompt workflow for consumption of the corrections computed by PCL and creation of a new ALCARECO
3. RelVal tests for all of the above (modified existing workflow 1020).
4. ConfigDP scenario to run 1 and 2 @ Tier0
5. equip ConfigDP tests to check the new workflow creation

### CODE REVIEW

**Comment by cerminar** [comment]
I need FWK expert advice on the last commit of this PR:
the ALCARECO RawPCCProducer, which sequence is defined in: 
https://github.com/cerminar/cmssw/blob/e6b2e8da7550bc327707dcb55039491071d1868f/Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py

depends on the products of the ALCARECO AlCaPCCZeroBias.
The only way to enforce the dependency I could find is to duplicate the full sequence of the second in the definition of the first. Looking at the Tracer it looks like the modules are actually executed only once.

Most likely this is needed also in 10.1 where the ConfigBuilder schedules the 2 alcarecos in different order not exposing the problem....

**Comment by cerminar** [comment]
please test

**Comment by makortel** [comment]
@cerminar 

> depends on the products of the ALCARECO AlCaPCCZeroBias.
> The only way to enforce the dependency I could find is to duplicate the full sequence of the second in the definition of the first.

I agree, if there is nothing outside `ALCARECORawPCCProducer_cff.py` that would guarantee it and `ALCARECOAlCaPCCZeroBias_cff` to be always loaded in the same job, it is best to declare the dependency explicitly in `ALCARECORawPCCProducer_cff.py`.

But you can avoid copy-pasting the contents of `ALCARECOAlCaPCCZeroBias_cff.seqALCARECOAlCaPCCZeroBias` sequence to 
`ALCARECORawPCCProducer_cff.seqALCARECORawPCCProducer` sequence with
```python
from Calibration.LumiAlCaRecoProducers.ALCARECOAlCaPCCZeroBias_cff import ...,seqALCARECOAlCaPCCZeroBias
...
seqALCARECORawPCCProducer = cms.Sequence(seqALCARECOAlCaPCCZeroBias,ALCARECORawPCCProd)
```

>  Looking at the Tracer it looks like the modules are actually executed only once.

This is true, framework takes care of running modules exactly(/at most) once even if they're included in multiple sequences.

**Comment by cerminar** [comment]
@makortel thanks for the confirmation. I will have to apply the same trick in the 10.1 PR

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
@kpedro88 can you please take a look and sign?

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
