### PR TITLE
Bugfix in SiStrip Calibration Code

### PR DESCRIPTION
**Pull request by suchandradutta**
Bug Fix : When removing the SiStripDetID dependence  from the SiStripDepRecords in [PR #8668669](https://github.com/cms-sw/cmssw/pull/8669) the records were produced incorrectly. In particular, the FakeESSources should be dependent on the TrackerTopologyRcd and not the IdealGeometryRcd. Furthermore, these records are now of the type DependentRecordImplementation instead of EventSetupRecordImplementation. Now the records  correctly defined and getting filled properly.
(corresponding code is not used in any production workflow)
@boudoul @jlagram @dimattia @nickmccoll @venturia

### CODE REVIEW

**Comment by mmusich** [comment]
@suchandradutta do you have an 81x version as well?

**Comment by suchandradutta** [comment]
no. I have not prepared for 81X as it was agreed with @davidlange6 that this package will be re-organized to avoid  'service' to create EventSetup objects @mmusich

**Comment by mmusich** [comment]
@cmsbuild please test
thanks, that was indeed my question

**Comment by boudoul** [comment]
hi @suchandradutta , In my opinion, it doesn't prevent to have this bug fix first in 81X (as any other PR) - The reorganization you are mentioning are getting there (was presented today at our local reco meeting - needs some validation before going into prodcution) but the policy of having anything first in 81X (and then backported in 80X ) remains , in my opinion

**Comment by suchandradutta** [comment]
But in that case what should I put in 81X? The new service (FEDError one PR #13888) + the bug fix Or just this bug fix? I was told that the content of PR # 13888 should not be there in 81X and only the new code (without service) should be there. Let me know accordingly I shall create a PR for 81X @boudoul

**Comment by mmusich** [comment]
@suchandradutta the 81X version of #13888 i.e. #13900 is already merged.

**Comment by boudoul** [comment]
Right the fed-error was kindly accepted to be in 81X (with the PR as pointed out by Marco) under the agreement that we will reorganize the package - so 81X and 80X are still in synch . So you just need to put the bug fix to still continue to keep everything in synch

**Comment by suchandradutta** [comment]
no the FED error stuff is only in 80X.  So to make 81X in synch  with 80X I shall have to put both changes in 81X. Do you agree ? @boudoul

**Comment by suchandradutta** [comment]
Sorry!! I am wrong! Fed error part is in there in 81X. Missed the comment by @mmusich

**Comment by mmusich** [comment]
@boudoul will the "re-organiz(ation) to avoid 'service' to create EventSetup objects" happen in time for the last open pre-release of 81x (nominally: CMSSW_8_1_0_pre12: 12 September 2016)? @suchandradutta will you provide just this fix for 81x?

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/15692

**Comment by boudoul** [comment]
Hi @mmusich  this is a very good point, and indeed pre12 should be a target, I'll try to (hopefully) make it happen - Thanks for reminding me the timescale, time is always going faster than we think :)

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1
backport of https://github.com/cms-sw/cmssw/pull/15692

**Comment by davidlange6** [comment]
+1

**Pull request merged**
