### PR TITLE
boosted cleaning fix for 74x

### PR DESCRIPTION
**Pull request by dsrankin**
Fixing const_cast issue.
Please approve as soon as possible, needed for data taking.
Backport of PR #10012 
@rappoccio @isando3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by drankincms** [comment]
I did not realize that these two paths would be part of the required checks. Indeed the change to this module involves changing the output type, so the two paths that are failing need to be updated (and it is fully expected that they crash). What would be the proper way to proceed?

**Comment by Martin-Grunewald** [comment]
Hmm, it is better to just fix only the bug (eg, make a local copy of the jets and modify those),
rather than to rewrite also the product produced, requiring updates to the frozen menus
configuration used for MC production.

**Comment by rappoccio** [comment]
If there is a higher degree of complexity to test without the copy, then let's just make the copy.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by drankincms** [comment]
Apologies for my ignorance, but how long are the relevant tests expected to take? It seems like they are taking quite a while. Thanks.

**Comment by Martin-Grunewald** [comment]
@degano 
can you please check what happend to the jenkins tests?

**Comment by Martin-Grunewald** [comment]
@cmsbuild @cmsbot wake up

**Comment by smuzaffar** [comment]
I have re-triggered the tests in jenkins

**Comment by Martin-Grunewald** [comment]
Error unrelated to this PR.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
