### PR TITLE
New set of RelVal GT with updated conditions for Run2 MC DIGI-RECO and new PF calibrations; fix of Hcal digis for fastsim; switching on CSV+SL tagger

### PR DESCRIPTION
**Pull request by diguida**
This is the final set of GT for next pre-release (originally in #7707): 
- Added Egamma PF Cluster corrections in all scenarios (so removed the ESPrefer in `RecoParticleFlow/PFClusterProducer/python/particleFlowClusterECAL_cfi.py`);
- Updated hadron PF calibrations for all scenarios;
- Updated new conditions for Run2 MC DIGI-RECO campaign;
- Removed unused records for old 3x3 APE in all the GT;
- Removed unsupported SIM geometry scenarios;
- Use the correct key for HI Run2 MC (as in #7704).

In addition - current fastim configs miss the run2 setup for digitizers in fastsim. This PR takes care of that (will be more robust once we get eras working), originally in #7726 

Finally, now that the new GT are made available, a new b-tagger can be switched on without crashing the reco sequence, this was also discussed in the merged #7542.
Note that the change in `PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py` will be crashing some of the PAT tests, because the new tagger is not yet included in the RelVals (a similar issue was discussed in #7678); originally in #7697

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
So, compared to what was already signed in #7697 + #7726 this has
only the following
```
DESRUN1_74_V3/DESRUN1_74_V4
	PFCalibrationRcd	-	PFCalibration_v0_mc	PFCalibration_v1_mc
MCRUN1_74_V3/MCRUN1_74_V4
	as above
MCHI1_74_V3/MCHI1_74_V4
	as above
MCPA1_74_V3/MCPA1_74_V4
	as above
GR_R_74_V6A/GR_R_74_V8A
	PFCalibrationRcd	-	PFCalibration_v0_offline	PFCalibration_v1_mc
GR_R_74_V7A/GR_R_74_V9A
	PFCalibrationRcd	-	PFCalibration_v0_offline	PFCalibration_v1_mc

```

this is expected for MC .. and also, as I understand, for data as well.
I'll wait for jenkins results  ... ugh
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7732/2594/summary.html ==> 404. 

let's see what I get locally at least for the data

**Comment by diguida** [comment]
@slava77 That's correct. As the reconstruction is the same, the new PF hadron calibration is applied in all scenarios.
BTW, as promised you can see the full set of changes [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/RelValGT)

**Comment by slava77** [comment]
Salvatore, thank you.
The twiki looks good.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7732	6f46b43
tested in CMSSW_7_4_X_2015-02-13-1400 (test area sign518b; comparing 74X+7726+7697 as a baseline with 74X+7732 as "new")

Changes appear in run1 workflows as expected.
The changes in run1 data are fairly similar to what is seen in MC (just to "confirm" the applicability of the mc PFCalibration payload)

Here are a few plots from 4.57 (ZEl skim from Run2012B)
the low-energy photon cut-off
all_sign518b-481-newvssign518b-481-ref_zelskim2012bwf4p57c_log10recopfcandidates_particleflow__rereco_obj_p42

the neutral hadron "regularization"
all_sign518b-481-newvssign518b-481-ref_zelskim2012bwf4p57c_log10recopfcandidates_particleflow__rereco_obj_p52

pfMet is OK
all_sign518b-481-newvssign518b-481-ref_zelskim2012bwf4p57c_log10recopfmets_pfmet__rereco_obj_pt

**Pull request merged**
