### PR TITLE
CTPPS: DQM fix

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR brings two fixes and an improvement for CTPPS DQM:
 * ctpps_2016 era declared in relevant configs
 * added anti-diagonal plots - important for the upcoming 90m run
 * corrected module names in log messages

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

changes look unrelated to this PR, concentrated in wf 250202.181, check once more

**Comment by fabiocos** [comment]
+1

**Pull request merged**
