### PR TITLE
Phase2-TB70X Try to make an example to run the setup used for investigating radiation damage studies of HGCal module

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to make an example to run the setup used for investigating radiation damage studies of HGCal module. Also, introduce some easily debug printouts in the IOMC package

#### PR validation:

Use the test script in SimG4CMS/HGCalTestBeam/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test

Refresh a test after a week.

**Comment by menglu21** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
