### PR TITLE
Move EDProducers to Task from electron MiniAOD validation sequence

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR reverts a commit https://github.com/cms-sw/cmssw/pull/29630/commits/afd436e21c41fc34678c93a528691b78d27993d2 of #29630 because moving the `photonValidationMiniAOD` to a Task was
* not the correct fix for "unrunnable schedule" error (many 1325.X workflows are failing in IBs with `ProductNotFound` exception (*))
* Accumulator EDProducers should be kept in a Sequence if it is possible that the Sequence is used in conjunction with EDFilters
  * understanding whether that is the case here would require complete understanding of all DQM and validation sequences in all possible use cases

This PR proposes to move the (non-Accumulator) EDProducers in without ix`electronValidationSequenceMiniAOD` to a Task instead. Then they can be run in any order (respecting data dependencies) without constraints from the Sequence ordering (fixing "unrunnable schedule), and not run if there are no consumers (fixing `ProductNotFound` errors in 1325.X).

(*)
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 19 event: 1802 stream: 1
   [1] Running path 'prevalidation_step'
   [2] Calling method for module CITKPFIsolationSumProducer/'egmElectronIsolationCITK'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Candidate
Looking for module label: gedGsfElectronsTmp
Looking for productInstanceName: 
```

#### PR validation:

Limited matrix and workflows `1325.5,1325.51,1325.516,1325.5161,1325.517,1325.518` run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type bug-fix

**Comment by makortel** [comment]
urgent

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test workflow 1325.5

One of the failing 1325.X workflows is hopefully sufficient

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
