### PR TITLE
Fix compiling PlotAlignmentValidation

### PR DESCRIPTION
**Pull request by hroskes**

### CODE REVIEW

**Comment by hroskes** [comment]
What releases are being used for backports at the moment?  I haven't been following so closely.

**Comment by lpernie** [comment]
Since 93X is only used for the MCV2 GENSIM production, the 92X is the one to be used.

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
@hroskes is this PR relevant for the data-taking ? if not, then no backports are needed.
92X is only to include features required for data-taking.

**Comment by hroskes** [comment]
@arunhelp well it's required if we want to run alignment validations in 92X, I'm not sure what you mean by "required".  The actual data taking will be fine.

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
