### PR TITLE
[81X] enable fetching of phase-I geometry from DB

### PR DESCRIPTION
**Pull request by mmusich**
This PR re-introduces in the 2017 phase-I workflows the fetching of the geometry from DB.
It should contain the state of the art of the tags for geometry description of the detector. 
Current status (as of Oct 27th) of the changes:
# Summary of changes in Global Tags
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v20](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v20) as [81X_upgrade2017_realistic_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v19) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v20/81X_upgrade2017_realistic_v19): 
  - updated Phase-I geometry: fixes the problem with CutTubs observed in GeometryFileRcd (81YV11) as well as a problem with mixing vector content in an Hcal reco schema (relevant code changes are already in pre13) and aligns sim geometry and Tracker reco geometry to a current one built from xml. 
  - updated Tracker alignment (ideal Pixel + asymptotic misalignment scenario for Strips) consistently with Tracker geometry
- **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v4) as [81X_upgrade2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v4/81X_upgrade2017_design_IdealBS_v3): 
  - updated Phase-I geometry: fixes the problem with CutTubs observed in GeometryFileRcd (81YV11) as well as a problem with mixing vector content in an Hcal reco schema (relevant code changes are already in pre13) and aligns sim geometry and Tracker reco geometry to a current one built from xml. 
  - updated Tracker alignment (ideal Pixel + ideal Strips) consistently with Tracker geometry

Tracker alignment payloads are from @ghellwig
This PR also re-activates the alignment on top of the geometry in case it is fetched via XML. 
@makortel you might want to follow this PR in its current state

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ianna** [comment]
@mmusich - looks good to me, thanks.

**Comment by mmusich** [comment]
@ianna, updating the GT with those updated geometry configuration results in segfault in the simulation step:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16301/15878/runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step1_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

could you please have a look?

**Comment by ianna** [comment]
@mmusich - ok, I'm checking

**Comment by ianna** [comment]
@mmusich - it looks like the DB tag is fine, I can access it and dump it:
```
cmsRun GeometryReaders/XMLIdealGeometryESSource/test/testReadXMLFromGTDB.py 
```
I'm checking the XML parser.

**Comment by ianna** [comment]
@mmusich - FYI, a bugfix is on the way. I'll update the tags. Please, close this PR.

**Comment by mmusich** [comment]
@ianna, thanks for the update. I'll update the autoCond with new GTs when we have the new tags at hand. Thanks.

**Comment by ianna** [comment]
@mmusich - please, take a new tag for GeometryFileRcd:
```
XMLFILE_Geometry_81YV12_Extended2017new_mc
```
The rest of the new tags in this GT queue are ok.

**Comment by mmusich** [comment]
@ianna, just rebased.
Thanks for the new tag. I'll update the Global Tags as well.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@ianna I've taken the new payload and rebased on the state of the art of 81x (i.e. including the changes of https://github.com/cms-sw/cmssw/pull/16339 and https://github.com/cms-sw/cmssw/pull/16326).
I'll cut full-fledged GTs one we see it passing the tests + adding the alignment

**Comment by ianna** [comment]
@smuzaffar - the unit test errors seem unrelated to this PR.
```
===== Test "testJetMETCorrectionsType1MET" ====
argument 0: testJetMETCorrectionsType1MET
argument 1: /bin/bash
argument 2: JetMETCorrections/Type1MET/test
argument 3: runtests.sh
shell is: /bin/bash
Current directory is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100
topdir is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100
testdir is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/src/JetMETCorrections/Type1MET/test
tmpdir is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/tmp/slc6_amd64_gcc530
testbin is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/test/slc6_amd64_gcc530
Running script: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/src/JetMETCorrections/Type1MET/test/runtests.sh
----- Begin Fatal Exception 26-Oct-2016 00:33:56 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/src/JetMETCorrections/Type1MET/test/corrMET_pfMet_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.KeyError'>
'mongo_query'
----- End Fatal Exception -------------------------------------------------
Failure using corrMET_pfMet_cfg.py: status 90
status = 23040

---> test testJetMETCorrectionsType1MET had ERRORS
 
^^^^ End Test testJetMETCorrectionsType1MET ^^^^
```
Here is one which fails, but repots a success:
```
----- Begin Fatal Exception 26-Oct-2016 00:25:05 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-10-25-1100/src/CalibTracker/SiStripCommon/test/test_all_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.SystemExit'>
1
----- End Fatal Exception -------------------------------------------------
... SUCCESSFUL!
status = 0

---> test testCalibTrackerSiStripCommon succeeded
```

**Comment by ianna** [comment]
@mmusich - I'm checking this - 10021.0 step1 and 10024.0 step1:
```
----- Begin Fatal Exception 26-Oct-2016 04:33:07 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 1
   [1] Calling global beginRun for module OscarMTProducer/'g4SimHits'
   [2] Using EventSetup component XMLIdealGeometryESProducer/'XMLFromDBSource' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
A std::exception was thrown.
basic_string::_S_construct null not valid
----- End Fatal Exception -------------------------------------------------
```
The rest of workflows fail due to DAS errors.
25202.0 step3:
```
----- Begin Fatal Exception 26-Oct-2016 05:24:37 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```

**Comment by mmusich** [comment]
@ianna among the spurious failures there is also a real error due to conditions. Phase-I wfs fail with:
```
Fatal Error at file 
%MSG
----- Begin Fatal Exception 26-Oct-2016 04:33:38 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 1
   [1] Calling global beginRun for module OscarMTProducer/'g4SimHits'
   [2] Using EventSetup component XMLIdealGeometryESProducer/'XMLFromDBSource' to make data DDCompactView/'' in record IdealGeometryRecord
Exception Message:
A std::exception was thrown.
basic_string::_S_construct null not valid
```

**Comment by ianna** [comment]
@mmusich - I'm afraid I've uploaded an old tag version - entirely my fault, sorry, I should not have rushed before the meeting yesterday. I've uploaded the new tag and will send a request after thorough testing:
```
XMLFILE_Geometry_81YV13_Extended2017new_mc
```

**Comment by ianna** [comment]
@mmusich - the 2017 workflows run fine with:
```
process.XMLFromDBSource = cms.ESProducer("XMLIdealGeometryESProducer",
    label = cms.string(''),
    rootDDName = cms.string('cms:OCMS')
)
```
and
```
    connect = cms.string('frontier://FrontierProd/CMS_CONDITIONS'),
    globaltag = cms.string('81X_upgrade2017_realistic_Candidate_2016_10_25_16_48_57'),
    pfnPostfix = cms.untracked.string(''),
    pfnPrefix = cms.untracked.string(''),
    snapshotTime = cms.string(''),
    toGet = cms.VPSet(
          cms.PSet(record = cms.string('GeometryFileRcd'),
                   tag = cms.string('XMLFILE_Geometry_81YV13_Extended2017new_mc'),
                   connect = cms.string('frontier://FrontierProd/CMS_CONDITIONS')
                   )
          )
)
```

**Comment by ianna** [comment]
@mmusich - just saw Giovanni's message: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2709.html
The tag is already in DB - shall I request the GT update?

**Comment by mmusich** [comment]
@ianna,GIovanni's message is not an issue, as far as MC is concerned. Please go ahead with the request, I am already building the GT. Thanks

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ianna** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by mmusich** [comment]
+1
comparison with baseline show changes across the board in 2017 workflows, but I am unable to find instances of huge issues in the plots in:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-26-2300+16301/16591/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/

**Comment by kpedro88** [comment]
@mmusich changes could be due to random number fluctuations from loading DB vs XML geometries

**Comment by mmusich** [comment]
@kpedro88 yep, was trying also to look if switch the alignment back on is causing issues - it appears like it's not the case (on the limited PR relval stats)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
