### PR TITLE
HcalDQM - Separating HO and HB in depth plots (11_1_X backport)

### PR DESCRIPTION
**Pull request by lwang046**
Backport of PR #31473. This update is supposed to be used in next MWGRs.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@lwang046  since this PR is to be used in the upcoming MWGR, @andrius-k tested it in Online DQM playback with run 337235 and it seems to work fine, however hcalcalib client is NOT processing any events despite Calibration stream files are there
My understanding is that this PR affects both hcalcalib and hcalreco Online Clients, but it would be nice if you could confirm or comment before proceeding

**Comment by lwang046** [comment]
Hi @jfernan2, from the code this PR will inflict those same changes to hcalcalib and hcalreco, since there are hcal tasks in those clients that have depth plots. Is the hcalcalib not processed due to the changes in this PR? I can't see how this could cause that immediately.

**Comment by jfernan2** [comment]
>  Is the hcalcalib not processed due to the changes in this PR?

No we don't think that either, we are just wondering if the calib does not process events due to the run number used or something else....

**Comment by lwang046** [comment]
>hcalcalib client is NOT processing any events despite Calibration stream files are there

I'm not familiar with the calibration stream files, the hcalcalib client indeed runs on separate events from the normal DQM streams and handles raw data with input tag "hltHcalCalibrationRaw". It is a collection of hcal diagnostic tasks.

**Comment by jfernan2** [comment]
Thanks @lwang046 
We switched to another run and all went fine

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
