### PR TITLE
Add DQM event by event comparison plots summarising CALOL2 outputs and uGT inputs

### PR DESCRIPTION
**Pull request by ashtipliyski**
PR adds comparisons between the outputs of CALOL2 and inputs of uGT for the purpose of identifying issues with data links or corruption in the unpacking of data at uGT. Functionality is currently restricted to a single module under L1T/L1TStage2uGT folder and produces three plots: one summarising number of problems found, another for keeping track of absolute number of objects and their ratio.

### CODE REVIEW

**Comment by dmitrijus** [comment]
This needs to go into the master branch first.
Please link it if it exists.

Otherwise, I don't see anything wrong with this code. It adds ~30 new bins.

**Comment by ashtipliyski** [comment]
Hi @dmitrijus,

I have a branch for creating a PR against master but was waiting for this to be validated in playback before I create it. I expect this to happen later today and once done will update both this PR and create the appropriate link to a PR for master.

Thanks

**Comment by dmitrijus** [comment]
Asking/Forcing you to make and merge a PR to master is a part of our validation :)

We should not merge or run the pull requests are not in master yet,
running those is an 'exception' we do and we are punished for it...

**Comment by ashtipliyski** [comment]
I completely see your point and in hindsight agree with it.

Here is the PR to master: #20951

**Comment by thomreis** [comment]
Hi @dmitrijus @jfernan2
could you take a look at this PR as well please?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
backport https://github.com/cms-sw/cmssw/pull/20951

**Comment by thomreis** [comment]
Hi @ashtipliyski 
Data taking with 92x has finished. This can be closed.

**Comment by ashtipliyski** [comment]
Thanks for the update Thomas, closing.

**Pull request closed without merging**
