### PR TITLE
remove unused L1 includes and members of the class

### PR DESCRIPTION
**Pull request by kirschen**

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
Fastsim issue not realted to this PR. It should have been fixed in latest CMSSW_8_1_X_2016-02-26-0800. Let retest it and see wether the latest IB is already picked by jenkins

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
