### PR TITLE
Premix cleaning - finish proto-era migration

### PR DESCRIPTION
**Pull request by franzoni**
-         complete migration to 3 proto-eras using custom; notably add customisePostLS1_50ns where necessary; see prior discussion at #7579 
-         premix: upgradePLS150ns => run2_mc_50ns; same phy processes as classi mix; include miniaod

### CODE REVIEW

**Comment by franzoni** [comment]
+1
tested all locally with -ne

**Comment by franzoni** [comment]
SLHCUpgradeSimulations/Configuration/python/postLS1CustomsPreMixing.py was broken when customise_csc_hlt was removed from muonCustomsPreMixing. I propose an obvious fix, @mdhildreth can you please comment.


@fwyzard @mdhildreth  : to handle the DIGI step of the 50ns premixing workflows consistently, we would need a 50ns version of postLS1CustomsPreMixing 
(note the two dictionaries digiPremixUp2015Defaults25ns and digiPremixUp2015Defaults50ns in relval_steps.py).
For the sake of running the workflows, I leave postLS1CustomsPreMixing also for the 50ns.

**Comment by franzoni** [comment]
With the commits to this point, all the cmsDriver of the premixing workflows are composed correctly, the input datasets found happily.

Tests fail at run time in the DIGI step with : 

/cms/cmssw/CMSSW_7_4_0_pre7/src/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h:83: void CaloTDigitizer<Traits>::run(CaloTDigitizer<Traits>::DigiCollection&, CLHEP::HepRandomEngine*) [with Traits = HODigitizerTraits; CaloTDigitizer<Traits>::DigiCollection = edm::SortedCollection<HODataFrame>]: Assertion `theDetIds->size() != 0' failed.

See the full log here:
/afs/cern.ch/user/f/franzoni/public/4mikeH/step2_ZEE_13+ZEE_13INPUT+DIGIPRMXUP15_PU25+RECOPRMXUP15_PU25+HARVESTUP15+MINIAODMCUP15.log
errors can be reproduced with:
runTheMatrix.py --what premix --command='-n 2' -i all
using this request on top of CMSSW_7_4_0_pre7.

**Comment by franzoni** [comment]
premix workflows are correctly built in the matrix. Re-enable their running in the IB.

**Comment by franzoni** [comment]
+1
the workflows are correctly built and the GEN-SIM input available.
run-time failures are detailed above.

**Comment by davidlange6** [comment]
Thanks! @franzoni

**Pull request merged**
