### PR TITLE
Fixes and updates for BTV

### PR DESCRIPTION
**Pull request by defranchis**
backport to 92X: https://github.com/cms-sw/cmssw/pull/19616

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by defranchis** [comment]
@mtosi can we please test again?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@defranchis 
please, summarise the list of triggers monitored by this PR
thanks

**Comment by mtosi** [comment]
and please, point to the 92x back port
is it still #19603 ?
I'm kind of lost :(

**Comment by defranchis** [comment]
@mtosi the backport is https://github.com/cms-sw/cmssw/pull/19616

**Comment by defranchis** [comment]
@davidlange6 I fixed the code according to your comments

**Comment by defranchis** [comment]
@mtosi @dmitrijus @davidlange6 can someone help me in finding the problem? that's pretty weird, in https://github.com/cms-sw/cmssw/pull/19616#issuecomment-314178971 all tests passed. It is the same code, backported to 92X

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
are these related to this PR ?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6 this PR is signed by DQM, and I think all comments have been addressed.

Do you have any objections if I include it in a second "merged" PR to fix the various conflicts ?

**Comment by defranchis** [comment]
@davidlange6 @fwyzard is there anything else I should do for this PR to be merged?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
