### PR TITLE
Make default Phase2 HLT thresholds from config file the same as in Run3

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

PR #43164 introduced the capability to read HCAL PF thresholds used in EGM modules from DB rather than from config file. For HLT, such thresholds can only now be read from DB thanks to the bug fix in #43819.

The Phase2 HLT thresholds vary depending on the ageing scenario, and those hardcoded in the relevant config files correspond to 1000 fb-1. Nevertheless, when running standard workflows and not specifying any ageing, the thresholds picked from the DB correspond to the current Run3 ageing scenario, and are therefore different from the config ones. For a matter of consistency, this PR changes the default thresholds in the Phase2 HLT config files to be the same as for Run3 (similarly to what was done in #43025.). Note that, unless differently specified, Phase2 HLT now reads thresholds from DB just like Run3 HLT. 

#### PR validation:

Phase2 workflows showed no difference in the HCAL PF thresholds read from DB and from config, when no ageing scenario was specified.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Comparisons show the usual spurious changes:
   * https://github.com/cms-sw/cmssw/issues/39803
   * https://github.com/cms-sw/cmssw/issues/43293
   * https://github.com/cms-sw/cmssw/issues/43790

**Comment by mmusich** [comment]
+hlt
   * no changes expected, none observed (expected known non- reproducibilities, see https://github.com/cms-sw/cmssw/pull/43822#issuecomment-1925419874)

**Pull request merged**
