### PR TITLE
Remove use of TSG internal GTs

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Remove use of TSG internal GTs
(as exposed by #29357)

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test workflow 503.0,561.0

**Comment by silviodonato** [comment]
pdmv:  @chayanit @pgunnell @zhenhu
upgrade:  @kpedro88

If you have no objections, I'm going to merge this PR before the morning IB because it fixes many failing workflows.

**Comment by chayanit** [comment]
+1 
no objection

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
