### PR TITLE
Fixed RP IDs in the PPS alignment harvester

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

Currently, the alignment harvester saves an SQLite file with short RP IDs (3, 23, 103, 123). Other reproduction modules ([CTPPSGeometryESModule](https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc)) expect long 32-bit IDs. This pull request fixes this issue by updating PPSAlignmentHarvester.

#### PR validation:

- Reproduce the results in CalibPPS/AlignmentGlobal/test.
- Run the whole reconstruction which now can retrieve the data from the alignment SQLite file.

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
@grzanka I believe this is intended for data taking, thus should be backported to 12_5_X and 12_4_X?

**Comment by francescobrivio** [comment]
type ctpps

**Comment by MatiXOfficial** [comment]
> @grzanka I believe this is intended for data taking, thus should be backported to 12_5_X and 12_4_X?

Yes, backports will be submitted soon.

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 1043

**Comment by francescobrivio** [comment]
test parameters:

 - workflow = 1045

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
test parameters:
  - workflows = 1042,1045

**Comment by tvami** [comment]
@cmsbuild , please test
 * now making sure that it will work for Run-2 too

**Comment by tvami** [comment]
urgent
 * backport so go into the next 12_4_X

**Comment by ChrisMisan** [comment]
+alca

- tests pass
- harvester is producing results

**Comment by perrotta** [comment]
+1

**Pull request merged**
