### PR TITLE
Add fillDescriptions to MeasurementTrackerEventProducer

### PR DESCRIPTION
**Pull request by makortel**
This PR addresses the "POG code review comments" of #20151, main changes:
* add `fillDescriptions` to `MeasurementTrackerEventProducer`
* replace `vector<unique_ptr<...>>` with `unordered_map`
  * I tested run 300811 comparing `vector`, `map`, and `unordered_map`, and `unordered_map` was faster than `map` and took less memory than either `map` or `vector` (although numbers are totally insignificant wrt. tracking total, or even a single iteration)
* some cleanup

Tested in CMSSW_9_4_X_2017-10-03-0000, no changes expected.

@VinInn

### CODE REVIEW

**Comment by makortel** [comment]
Addresses issue #20703.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
please test

**Comment by makortel** [comment]
1000.0 step3 failure is not from this PR

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test
(the latest IB, CMSSW_9_4_X_2017-10-11-2300, should finally contain the fix for the issue in the RelVal wf 1000)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20891	d054070
- somewhat technical updates, in line with the PR description
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
