### PR TITLE
Fix noisy HLT BTV DQM

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
As mentioned in https://github.com/cms-sw/cmssw/issues/42342, I found that the noisy does not come from TOP, but from HLT BTV. It reuses TopMonitor. The fix in this PR just updates `btagAlgo` as done in https://github.com/cms-sw/cmssw/pull/28067 for TOP.

This should confirm with @cms-sw/hlt-l2 if btagAlgo used in this PR is set properly. FYI @missirol 

#### PR validation:
Try to run workflow 12434.0 and check DQM. I don't see noisy complain anymore, and DQM is filled.
Before this PR, BTV HLT is empty: https://tinyurl.com/ynfp3xj6
With this PR, histograms are filled: https://tinyurl.com/ymxs5emx

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> You potentially removed 208 lines from the logs

just to notice that as expected the logs are cleaner now, see [diff](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-18-1100+95e72d/58910/validateJR/logRootQA-events.log)

e.g.

```
33 Lines only in /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/CMSSW_13_3_X_2023-09-18-1100/12434.0_TTbar_14TeV+2023/step3_TTbar_14TeV+2023.log
   2023-09-18 13:41:50.643017: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: UNKNOWN ERROR (34)
   2023-09-18 13:41:50.670014: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 1
   B-Jet handle not valid, will skip event
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 1
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 2
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 2
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 3
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 3
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 4
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 4
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 5
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 5
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 6
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 6
   %MSG-w TopMonitor:  TopMonitor:BTagMu_AK4DiJet70_Mu5 CEST  Run: 1 Event: 6
   %MSG-w TopMonitor:  TopMonitor:BTagMu_AK4DiJet40_Mu5 CEST  Run: 1 Event: 6
   %MSG-w TopMonitor:  TopMonitor:BTagMu_AK4DiJet20_Mu5 CEST  Run: 1 Event: 6
   %MSG-w TopMonitor:  TopMonitor:AK8PFJet40 CEST  Run: 1 Event: 7
   %MSG-w TopMonitor:  TopMonitor:PFJet40 CEST Run: 1 Event: 7
   ```

**Comment by srimanob** [comment]
Change in PR test is expected. The failure in PR test comparison coming from HLT/BTV where histograms are filled now.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cms-sw/dqm-l2 @cms-sw/orp-l2 Could you please consider this bug fix? Thx.

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
type btv

**Comment by rappoccio** [comment]
+1

* Changes are expected in DQM plots.

**Pull request merged**
