### PR TITLE
fixed bug in UL16 PU profile

### PR DESCRIPTION
**Pull request by gkrintir**
**PR description**:

This fixes the pileup scenario for the 2016 ultra legacy (periods B-H), i.e.,

"2016_25ns_UltraLegacy_PoissonOOTPU"

forward port from cms-sw:CMSSW_10_6_X https://github.com/cms-sw/cmssw/pull/29431

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
