### PR TITLE
Extended 2018 Geometry Scenario Update

### PR DESCRIPTION
**Pull request by ianna**
* Add Extended 2018 geometry scenario payload scripts
* Update 2018 geometry scenario to pick up newest changes added to 2017
* Remove obsolete comment from 2017 scenario description

### CODE REVIEW

**Comment by ianna** [comment]
hold

I'll rebase it when everything else is merged to IBs

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - I've merged all geometry PRs here and re-based it this morning. If you think, it's easier to pick up just one PR. Otherwise, you can take PRs one by one and I'll keep re-basing this one.

The tags for both upgrade2017 and upgrade2018 GT queues are up-to-date (== all geometry changes here) 

@franzoni - FYI

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
I’ll merge things one by one - but for the record, which PRs have you included here and in the geometry payloads?

**Comment by ianna** [comment]
@davidlange6: Bundled together #17198 + #17099 + #17192 + #17156 + #17199 + #17130 + #17131 + #17115 + #17245 +  #17280 + #17261 + there is a fresh commit in this PR

**Comment by davidlange6** [comment]
Hi @ianna  - thanks - I have most of them merged in now. (some comments on the others). Please also rebase this when you have a moment. Thanks

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
```
===== Test "TestFWCorePythonFrameworkDriver" ====
argument 0: TestFWCorePythonFrameworkDriver
argument 1: /bin/bash
argument 2: FWCore/PythonFramework/test
argument 3: runPythonTests.sh
shell is: /bin/bash
Current directory is: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300
topdir is: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300
testdir is: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300/src/FWCore/PythonFramework/test
tmpdir is: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300/tmp/slc6_amd64_gcc530
testbin is: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300/test/slc6_amd64_gcc530
Running script: /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300/src/FWCore/PythonFramework/test/runPythonTests.sh


Traceback helper thread failed to read from parent: Bad file descriptor
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-01-30-2300/src/FWCore/PythonFramework/test/runPythonTests.sh: line 6: 80829 Aborted                 python "$file"
unit tests for CmsRun.py failed: status 134
status = 34304

---> test TestFWCorePythonFrameworkDriver had ERRORS
 
^^^^ End Test TestFWCorePythonFrameworkDriver ^^^^

```

**Comment by ianna** [comment]
please test

**Pull request merged**
