### PR TITLE
Phase2-hgx193 Add more testing code for HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a few more testing code for HGCal geometry

#### PR validation:

The added codes are meant for validating HGCal geometry

#### if this PR is a backport please specify the original PR:

No back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
please test
(to check if extra log lines are spurious)

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
