### PR TITLE
[GT Update] HCAL Response Correction update for HE Scale change

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags
 
## 2018_MC
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v8) as [100X_upgrade2018cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v8/100X_upgrade2018cosmics_realistic_deco_v7): 

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v6) as [100X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v6/100X_upgrade2018_design_IdealBS_v5): 

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v10) as [100X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v10/100X_upgrade2018_realistic_v9): 

      * HCAL response correction update to take into account the energy scale change for HE. 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3483.html
 https://indico.cern.ch/event/701241/contributions/2887035/attachments/1595810/2527619/IsoTrackN59.pdf

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Seems to me the error was just because one file were temporary missing:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22137/25932/unitTests.log
I re-triggered the tests

**Comment by fabiocos** [comment]
please test

**Comment by arunhep** [comment]
the unit test failure seems to be because of this

```
dropped waiting message count 0
stat: cannot stat `dqm_empty.root': No such file or directory
read_missing_file_cfg.py ------------------------------------------------------------
06-Feb-2018 23:14:26 CET  Initiating request to open file file:dqm_missing.root
----- Begin Fatal Exception 06-Feb-2018 23:14:27 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
   [2] Calling StorageFactory::open()
   [3] Calling File::sysopen()
Exception Message:
Failed to open the file 'dqm_missing.root'
Input file file:dqm_missing.root was not found, could not be opened, or is corrupted.
   Additional Info:
      [a] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------

=============================================
```
this looks unrelated to the conditions change. @lpernie has retriggered the tests.

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
