### PR TITLE
Make skeletons generate stream or one types

### PR DESCRIPTION
**Pull request by wddgit**
Modify the skeleton module generator mkedanlzr
to make a "one" type EDAnalyzer declaring a
shared resource of the TFileService. Modify
mkedfltr and mkedprod to generate a "stream"
type EDFilter or EDProducer. Previously these
generated "legacy" type modules.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please change stream ones to have beginStream and endStream rather than removing beginJob and endJob.

**Comment by wddgit** [comment]
Done. I added the beginStream and endStream methods for the stream modules.

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by wddgit** [comment]
The test failure looks unrelated to my changes.

I only modified the templates for the python functions that generate
the skeleton module classes that people can use as a starting point
when writing a real module. I suspect there are no tests for that and
that running the jenkins tests is a waste of time.

**Pull request merged**
