### PR TITLE
Remove FWCore TestHelper utility

### PR DESCRIPTION
**Pull request by smuzaffar**
- Remove FWCore TestHelper utility (FWCore/Utilities/interface/TestHelper.h)
- Update all tests to not use FWCore/Utilities/interface/TestHelper.h and instead make use of `<test command="....."/>`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with #41269

**Comment by makortel** [comment]
Comparison differences in 12434.0	are related to #41200

**Comment by makortel** [comment]
+core

@cms-sw/orp-l2 This PR depends on https://github.com/cms-sw/cmssw/pull/41269, I'm not sure if you want to merge that one first or both of these together.

**Comment by smuzaffar** [comment]
this PR should be merge with or after https://github.com/cms-sw/cmssw/pull/41269

**Comment by perrotta** [comment]
> this PR should be merge with or after #41269

Let do it together, as it was already tested as such

**Comment by perrotta** [comment]
+1

**Pull request merged**
