### PR TITLE
Backport of PR #19089 to 92X

### PR DESCRIPTION
**Pull request by mandrenguyen**
First of several 93X -> 92X backports.
There will shortly be a pilot run of XeXe collisions, which may require us to use the heavy-ion reconstruction sequence for prompt reco. 
The Phase I version of the HI reco has some updated that went into 93X, but not 92X, hence the backporting.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #19089

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
please use a more descriptive PR title

**Comment by mandrenguyen** [comment]
Superseded by #20681 20681

**Pull request closed without merging**
