### PR TITLE
Fix L1T EG Phase2 Track match

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

The PR addresses a minor problem in the matching of L1 tracks & EG standalone objects (see [Jack Li talk @ EG L1 P2 meeting ](https://indico.cern.ch/event/933640/contributions/3923081/attachments/2066176/3467521/EgammaMeeting_30Jun.pdf) for details).

This is a "minimalistic" backport of https://github.com/cms-sw/cmssw/pull/31235 (stripping down EG validation code).

#### PR validation:

See the original PR for validation plots.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
