### PR TITLE
GEM onlineDQM trigger primitive with CMSSW_14_1_0_pre5

### PR DESCRIPTION
**Pull request by Dongwoon77**
#### PR description:

In this PR, GEM onlineDQM plots for trigger primitive have been implemented

#### PR validation:

Tests are done with `cmsRun $CMSSW_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True runNumber=379866 dataset=/ExpressPhysics/Run2024C-Express-v1/FEVT minLumi=20 maxLumi=40 eventsPerLumi=50000` and `runTheMatrix.py -l limited -i all --ibeos` since it makes effects on P5

@jshlee @watson-ij @quark2 @hcai0520 @giovanni-mocellin

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
@Dongwoon77 , we are testing this PR on our playback machines using `CMSSW_14_0_11` with `run 382626`. Could you please have a look at the [plots](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=GEM;size=M;root=GEM/PadDigiCluster;focus=;zoom=no;) and see whether new plots seems as expected to you ? Could you please also make its backport PR to `14_0_X` ?

**Comment by quark2** [comment]
Hi @tjavaid, 

Thanks for your management. I'm one of GEM DQM developers, and me and @Dongwoon77 found that many plots are missing. Not only the new plots but also most of the existing plots are being displayed with "not available" message, while they appear in the central onlineDQM as well. The change in the codes does not affect the existing ones. Even, as I understand, if the plots are not made, then they should not appear at all in the folders (not in the "layouts" area), not displaying "not available" message.

I wonder what happens on the original ROOT DQM file, but I have no idea how to retrieve it. Is there a way to download it? Also, how can I reproduce the playback result by myself?

**Comment by tjavaid** [comment]
> Hi @tjavaid,
> 
> Thanks for your management. I'm one of GEM DQM developers, and me and @Dongwoon77 found that many plots are missing. Not only the new plots but also most of the existing plots are being displayed with "not available" message, while they appear in the central onlineDQM as well. The change in the codes does not affect the existing ones. Even, as I understand, if the plots are not made, then they should not appear at all in the folders (not in the "layouts" area), not displaying "not available" message.
> 
> I wonder what happens on the original ROOT DQM file, but I have no idea how to retrieve it. Is there a way to download it? Also, how can I reproduce the playback result by myself?

Hi @quark2 , @Dongwoon77 , could you please have a look now on the [GUI plots](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=GEM;size=M;root=GEM/PadDigiCluster;focus=;zoom=no;) ? The histograms seem being populated now. (We just restarted the run at playback. Perhaps GEM client was crashing in previous iteration)
Let us know.

**Comment by quark2** [comment]
Hi @tjavaid, 

Thanks a lot! I've checked that the new plots are all available. We still need to check whether they are all sensible, though. We will notice if we have something else.

Best regards, 
Byeonghak Ko

**Comment by Dongwoon77** [comment]
Hi @tjavaid.

I've checked the GUI plots, I think that is look good.

Thank you.
Dongwoon.

**Comment by tjavaid** [comment]
> Hi @tjavaid.
> 
> I've checked the GUI plots, I think that is look good.
> 
> Thank you. Dongwoon.

Hi @Dongwoon77 , thanks for the cross check. Could you please make its backport PR to`14_0_X` for data-taking release? Thanks

**Comment by tjavaid** [comment]
+1

- P5 tests OK.

**Comment by rappoccio** [comment]
+1

**Comment by Dongwoon77** [comment]
Hi @tjavaid.

I made the backport PR for CMSSW_14_0_X version.
you can check the PR at below link.

backport PR Link : https://github.com/cms-sw/cmssw/pull/45541

Thank you.
Dongwoon.

**Pull request merged**
