### PR TITLE
First version of nanoDQMIO content [12_1_X]

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/36275   since ReReco of Pilot Test Runs taken in Autumn 2021 will be most likely done in 12_1_X

First version of nanoDQMIO data-Tier with a preliminary content based on requests from subsystems interested in doing ML4DC/DQM with the upcoming ReReco of Pilot Test Runs taken in Autumn 2021

Tested with: runTheMatrix.py -l limited -i all --ibeos --command '--procModifiers=dqmPerLSsaving --customise_commands="process.DQMStore.saveByLumi = cms.untracked.bool(True)"'

up to Harvesting step (excluded) since Harvesting is not defined with perLS saving

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by francescobrivio** [comment]
urgent

 - needed for re-reco of PilotBeam 2021 data

**Comment by francescobrivio** [comment]
@qliphy @perrotta this is another PR needed for the new 12_1_X release for re-reco. It's fully signed and the master PR is merged already.

**Comment by perrotta** [comment]
> @qliphy @perrotta this is another PR needed for the new 12_1_X release for re-reco. It's fully signed and the master PR is merged already.

This is an identical backport of #36275, and quite likely already good for being backported.
As usual, let it be tested in at least one master IB, and if there are no issue also the backport will get merged

**Comment by francescobrivio** [comment]
> > @qliphy @perrotta this is another PR needed for the new 12_1_X release for re-reco. It's fully signed and the master PR is merged already.
> 
> This is an identical backport of #36275, and quite likely already good for being backported. As usual, let it be tested in at least one master IB, and if there are no issue also the backport will get merged

sounds a good plan! thanks a lot @perrotta!

**Comment by jfernan2** [comment]
@perrotta since this PR has not been merged yet, would it be possible to add a naive extra line in the configuration file of Monitor Elements to be saved? Tracker has just requested an additional histogram to be saved in the nanoDQMIO data-Tier, the change is innocent, I can update the master version too if needed.
Thanks

**Comment by perrotta** [comment]
> @perrotta since this PR has not been merged yet, would it be possible to add a naive extra line in the configuration file of Monitor Elements to be saved? Tracker has just requested an additional histogram to be saved in the nanoDQMIO data-Tier, the change is innocent, I can update the master version too if needed. Thanks

@jfernan2 yes, please updatesboth this PR and the master

**Comment by jfernan2** [comment]
Thanks @perrotta 
I have updated this PR, I don't think it makes sense to retrigger the tests since the change won't affect them in any way
For master, since the PR has already been merged, I will create a tiny PR with this minor change
Thank you!

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
For the records: master PR to sincronyze with last minute addition on this PR
https://github.com/cms-sw/cmssw/pull/36331

**Comment by perrotta** [comment]
+1
- Backport of #36275 and  #36331, succesfully merged in master since CMSSW_12_2_X_2021-12-02-2300

**Pull request merged**
