### PR TITLE
[12_4_X] Add Run-3 JECs to Run-3 MCs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38567

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38567

### CODE REVIEW

**Comment by tvami** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/38567

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

- tests pass
- all failures consistent with jec changes.

**Comment by perrotta** [comment]
+1

**Pull request merged**
