### PR TITLE
Phase2-hgx309 Add possibility of adding shift due to cassette positioning

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add possibility of adding shift due to cassette positioning

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Could you sin this - we are slowly building up V17 geometry for HGCal and this is an important ingredient for that

**Comment by srimanob** [comment]
+Upgrade

This PR introduce the way to add shifting in HGCAL. No change is expected for this PR as it does not use in the current workflow.

**Comment by qliphy** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
