### PR TITLE
[JME] Set up Pileup Jet ID for AK4 Puppi V18 jets

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR sets up the Pileup Jet ID for AK4 Puppi V18 jets for MiniAODv5/NanoAODv15 reMini-reNano campaign. The training was performed by by Jihoon Shin (@jshin96) and presented in a JMAR [meeting](https://indico.cern.ch/event/1429230/#3-run3-pileup-jet-id-training). In this PR, the Pileup Jet ID is set up to be calculated at the PAT step and stored for `slimmedJetsPuppi`. A separate PR will soon follow to add the Pileup Jet ID branch for the NANO step.

This PR should be tested with the training weights in this cms-data/RecoJets-JetProducers PR:  https://github.com/cms-data/RecoJets-JetProducers/pull/14

FYI JMAR convenors (@fiemmi @colizz @wajidalikhan)

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes MiniAOD workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`

### CODE REVIEW

**Comment by hqucms** [comment]
test parameters:
 - pull_requests = https://github.com/cms-data/RecoJets-JetProducers/pull/14

**Comment by hqucms** [comment]
Hi @nurfikri89 -- Shouldn't we add this to NanoAOD too?

**Comment by hqucms** [comment]
> Hi @nurfikri89 -- Shouldn't we add this to NanoAOD too?

Nevermind -- I see you plan to do it in a follow-up PR.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

The large number of unrelated diffs are due to the inclusion of https://github.com/cms-sw/cmssw/pull/46124.

**Comment by jfernan2** [comment]
+1

**Pull request merged**
