### PR TITLE
Update the .gitignore rules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the `.gitignore` rules:
  - ignore files under the top level $CMSSW_BASE/src directory, but not its subdirectories
  - ignore partially applied patches and their backup

#### PR validation:
Before:
```bash
$ touch x
$ git status
On branch CMSSW_12_4_X
Your branch is up to date with 'cmssw/CMSSW_12_4_X'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        x

nothing added to commit but untracked files present (use "git add" to track)
```

After:
```bash
$ touch x
$ git status
On branch CMSSW_12_4_X_update_gitignore
Your branch is up to date with 'fwyzard/CMSSW_12_4_X_update_gitignore'.

nothing to commit, working tree clean
```

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Looks ok to me, @smuzaffar what do you think?

**Comment by smuzaffar** [comment]
looks good to me too

**Comment by makortel** [comment]
+core

**Comment by qliphy** [comment]
+1

**Pull request merged**
