### PR TITLE
Run3-gem59 Update the unit sequences in MuonCommonData algorithms

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the unit sequences in MuonCommonData algorithms

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Thanks for the clean-up.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
