### PR TITLE
[Payload Inspector] Miscellaneous improvements for `RunInfo` and `SiStripLatency`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
Added tools to retrieve list of Strip Tracker peak mode runs;

   * adds `RunInfoDetHistory` in `RunInfo_PayloadInspector` to create history plot of given subdetector presence in a run;
   * adds ` SiStripIsPeakModeHistory` in `SiStripLatency_PayloadInspector` to create historic trend plot of mode as a function of the run;
   * adds script to create list of Strip Tracker peak mode runs;

#### PR validation:

Private

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
