### PR TITLE
[94X] [L1T] [DQM] Updating range for vertex histogram

### PR DESCRIPTION
**Pull request by kreczko**
Fixes issue https://its.cern.ch/jira/browse/CMSLITDPG-328:
increased the max nVertex value from 40 to 100.

Backport of #21615.

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #21615

**Comment by thomreis** [comment]
+1

**Comment by kreczko** [comment]
PR has been synced with its 10X version (#21615)

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
The DQM has moved to 10_0_X. This PR can be closed.

**Comment by thomreis** [comment]
Hi @kreczko 
Since the DQM is not going to use 9_4 release anymore this PR can be closed.

**Comment by fabiocos** [comment]
@thomreis thank you for checking, I close the PR

**Pull request closed without merging**
