### PR TITLE
Adding decay files for UpsilonXS [10_6_X]

### PR DESCRIPTION
**Pull request by michael-pitt**
This is a backport from https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/24

### CODE REVIEW

**Comment by bbilin** [comment]
@cmsbuild please test

**Comment by bbilin** [comment]
+1. the changes are tested locally and the files are needed for the ul branch.

**Comment by michael-pitt** [comment]
Dear release team (@sextonkennedy, @antoniovilela, @rappoccio), can you check this PR? it is a bit urgent. The PR is an addition of a few files to the data folder, required by new simulations. 
NOTE: There is no validation for master, as these files are available in [cms-data](https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/24)

**Comment by rappoccio** [comment]
+1

**Comment by antoniovilela** [comment]
@michael-pitt @cms-sw/generators-l2 

Michael, Meng,

Going back to this, don't you need to backport https://github.com/cms-sw/cmsdist/pull/8946, that is changing the tag that will be fetched from the GeneratorInterface/EvtGenInterface data repository corresponding to https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/24 ?

I am not sure if this PR (#43812) does the job. I ask @iarspider @aandvalenzuela

In any case backporting the tag in cmsdist is the usual way of achieving this.

**Comment by antoniovilela** [comment]
> Hello @antoniovilela,
> I think bot only updates the tag automatically for the base branch, so we would need to backport it.
> 
> In any case, I was about to open the backport manually but I realized the tag is already different in cmsdist 10_6_X branch. For example, branch `IB/CMSSW_10_6_X/gcc700` has `GeneratorInterface-EvtGenInterface=V02-09-00` (See https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/data/cmsswdata.txt#L8). Should I go ahead and backport it anyways?
> 
> Thanks!
> Andrea

Hi Andrea,

Many thanks for checking and sorry for the noise. It was backported and I had forgotten: https://github.com/cms-sw/cmsdist/pull/9012

I got confused looking at this PR.

Thanks again.

**Pull request merged**
