### PR TITLE
Fix import in Phase1L1TJetProducer_cfi for python 3

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is now python 2 and 3 compatible.

#### PR validation:

import under python 3 now works.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR for PY2-PY3 compatible.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
