### PR TITLE
breing back "Run modules concurrently during global begin transitions"

### PR DESCRIPTION
**Pull request by Dr15Jones**
This reverts commit e26292386353ecdbf44ff6042e3bace69ecb08d8.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 would you like this in CMSSW_9_2_X or CMSSW_9_2_DEVEL_X? I believe I've fixed all the thread-safety items found in the first try, but there could be others.

**Comment by davidlange6** [comment]
92x is ok for me

**Comment by Dr15Jones** [comment]
The unit test failure is unrelated to this pull request.

**Comment by davidlange6** [comment]
ready to sign this @Dr15Jones ?

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
