### PR TITLE
small modification to get the output of skimming 

### PR DESCRIPTION
**Pull request by Moanwar**
#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
-1
Tests are not allowed to read from personal eos areas.

**Comment by kpedro88** [comment]
@Moanwar what is the status of this PR?

**Comment by Moanwar** [comment]
Hi @kpedro88 indeed i have made anther PR with the same file after the command from Chris , so is there a way to disable this thread ?

**Comment by kpedro88** [comment]
please close

**Pull request closed without merging**
