### PR TITLE
Run2-sim17 Backport PR #19478 for fixing bug of ECAL

### PR DESCRIPTION
**Pull request by bsunanda**
Required for analysis of high precision measurements using electrons and photons

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 @civanch The unit test makes use of a private GEN-SIM file produced with some earlier version and complains that a non-existing Geometry cfg is not there. This unit test should be removed or its results should be ignored. Please advise

**Comment by civanch** [comment]
+1
still, may understanding, that 8_0_X should not be used for SIM production without extra validation efforts.

**Comment by davidlange6** [comment]
we concluded Friday this was not needed....

**Comment by bsunanda** [comment]
I am not so sure about that conclusion. My understanding was that they may still need this.

**Comment by davidlange6** [comment]
hi @bsunanda  @civanch - please include also the needed customize function to activating things

**Comment by civanch** [comment]
Hi @davidlange6 , #20093 is proposed

**Comment by bsunanda** [comment]
@civanch @davidlange6 Please merge this PR

**Pull request merged**
