### PR TITLE
Fast sim wf lukas

### PR DESCRIPTION
**Pull request by franzoni**
Hello Lukas,
- " 10 and ave 20 in-time only workflows for one or a few" => ok
- since we don't have the output of 135.8, we cannot commit now the workflows which depend on the files you've placed in afs. I've commented all of those out (otherwise we deliberately include in the IB several workflows which will stay broken for at least a week). We'll have to run 135.8 in pre7; once we have its output, update the matrix
- there were 3 other modifications necessary (miniaod of pu full sim, recycly of gen-sim) cheers, g.

### CODE REVIEW

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
+1

**Comment by lveldere** [comment]
+1 

thanks Giovanni!

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@nclopezo @degano - could you check on the status of the tests?

**Comment by nclopezo** [comment]
@davidlange6 they had failed because the disk of the Jenkins node was full, but I cleaned it up and restarted the tests again.

**Pull request merged**
