### PR TITLE
Fix dqm-* scripts for python3.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Fix `dqm-access`, `dqm-ls` and `dqm-grep` scripts to work with python3.

#### PR validation:

Locally tested the scripts.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@rovere thanks for this! Are there plans to backport (e.g. to 13.0.X)?

**Comment by rovere** [comment]
@mmusich probably a backport could be as easy as applying the same patch on top of that branch...?

**Pull request merged**
