### PR TITLE
HLT object monitoring for HI Run in DQMOffline

### PR DESCRIPTION
**Pull request by goni-zz**
Update for HLT path related 2018 PbPb run.
@stahlleiton

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by tocheng** [comment]
+1

**Comment by mmusich** [comment]
shouldn't this PR be rebased?
this commit https://github.com/cms-sw/cmssw/pull/25033/commits/b2cc2fdd03e454195130ba778cd223609e44911c is already in master.

**Comment by goni** [comment]
> shouldn't this PR be rebased?
> this commit [b2cc2fd](https://github.com/cms-sw/cmssw/commit/b2cc2fdd03e454195130ba778cd223609e44911c) is already in master.

Hi, then should I commit again without that?

**Comment by boudoul** [comment]
Hi @goni, you should rebase with a recent IB (e.g CMSSW_10_4_X_2018-10-30-2300 
)

**Comment by boudoul** [comment]
sorry this is for 10_3_X so a recent iB in 10_3_X  to rebase is CMSSW_10_3_X_2018-10-31-1100

**Comment by goni** [comment]
> sorry this is for 10_3_X so a recent iB in 10_3_X to rebase is CMSSW_10_3_X_2018-10-31-1100

Hi @boudoul I'm familiar with rebase. it's not working correctly.
Could you let me know how to do that?

**Comment by mmusich** [comment]
@goni you can try in your local area:
   *  `git rebase -i  CMSSW_10_3_X_2018-10-31-1100`
   * fix conflicts in case there is any, git will show you how to deal with that
   * `git push my-cmssw +HEAD:PR_DQMOffline_HI_10_3_X`

otherwise you can have a look here: http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by goni** [comment]
> * PR_DQMOffline_HI_10_3_X

@mmusich and @boudoul sorry I make a mistake. I just make new PR #25076 instead of using rebase.
Please have a look the PR

**Pull request closed without merging**
