### PR TITLE
speedup of trackValidatorJetCore and TrackAssociatorByChi2

### PR DESCRIPTION
**Pull request by slava77**
trackValidatorJetCore is currently enabled only with seedingDeepCore; which is not in production yet.
Compared to other tracking validation cases, this one is using association by chi2.
As clarified in https://github.com/cms-sw/cmssw/pull/33531#issuecomment-840686662
`The trackAssociatorByChi2 is needed to have a "fair" performance estimation with DeepCore. DeepCore uses pixel-less seed [1], thus the associator by hits is not optimal in this case.`

A problem in timing was observed while testing #33531 , as described in https://github.com/cms-sw/cmssw/pull/33531#issuecomment-840663161 (and related messages). There are two components to resolve the problem:
- reduce the set of tracking particles to only the in-time ones (BX = 0)
- improve computational implementation of TrackAssociatorByChi2 by reducing unnecessary computations done in a nested double-loop (nTrack * nTrackingParticles )

In the test setup based on 11834.0 with `seedingDeepCore` modifier, the time in `trackValidatorJetCore` is reduced from around 5400 s/event  (averaged over the first 9 events) to 3.4 s/evt (averaged over 200 events).

Updates were tested on wf 11651 with `seedingDeepCore` (only in-time particles) to confirm that there are no changes in the DQM plots after the speedup implemented in `TrackAssociatorByChi2`

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 11723.17

**Comment by mtosi** [comment]
thanks A LOT @slava77  !!!!!!!!!

**Comment by slava77** [comment]
> In the test setup based on 11834.0 with `seedingDeepCore` modifier, the time in `trackValidatorJetCore` is reduced from around 5400 s/event (averaged over the first 9 events) to 3.4 s/evt (averaged over 200 events).

sadly, while running this on top of #33531 trackValidatorJetCore is still extremely slow, investigating.

**Comment by slava77** [comment]
> sadly, while running this on top of #33531 trackValidatorJetCore is still extremely slow, investigating.

that was a false alarm, I didn't run the right thing. 
I confirm that the timing speedup is present on top of #33531  as well

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
