### PR TITLE
Run3-gem58 Remove reference to CLHEP

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to CLHEP

#### PR validation:

Tested using runTheMatrix test workflow

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Thanks for the clean-up.

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
