### PR TITLE
Make Geant4 geometry exception to be just a warning

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In mass production just running with 12_0_2 there are number of rare exceptions due to problem in Geant4 navigation at boundaries of some volumes. In this PR these exceptions are converted to warnings.  

Handling of Geant4 exception is changed: for each exception a dump of track parameters is added. This is needed, because not in all Geant4 exceptions G4Track information is given, or is given incomplete.

Introduce a new energy threshold. If a particle has kinetic energy blow the GeomNav0003 exceptions become JustWarning, track is killed, simulation continues.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@qliphy , this is a current solution of #35582. Overnight I manage to get locally one case and this job was running smoothly.

**Comment by davidlange6** [comment]
Perhaps its worth only ignoring this error in case of understood particle kinematics? (Eg, when the energy is below some threshold?

**Comment by civanch** [comment]
@davidlange6 , in the class there is no information about the track, so such cannot be applied. Moreover, in this GeomNav0003 there are several cases - warning printouts have full information in part of cases only. In all cases, when full information is available, energy of a particle is below 100 keV. 

I am thinking also about another solution - use the Helix stepper in magnetic field for low-energy particles. This may also reduce number of cases of stack tracks at the boundary of volumes.

**Comment by srimanob** [comment]
Should we hold this PR a bit until further discussion? I think it is not urgent. We may wait until the pilot productions are done.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
The energy threshold is introduced. The default value is 10 MeV.

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
There is a question at 
https://cms-talk.web.cern.ch/t/simg4coreapplication-exception-in-generation-of-event/7251/6
if this PR should be backported to UL release. @tvami @civanch

**Pull request merged**
