### PR TITLE
Fix bug affecting boosted tau isolation

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR fixes a bug affecting indexing jet-constituent-maps. In the result of the bug constituents of a subjet nearby a considered tau - a seed of a nearby tau candidate - are not excluded from particles used to compute isolation of the tau, which breaks the boosted tau algorithm. The bug has been introduced in #17087 (for 90X) speeding up boosted tau seed producer code. Unfortunately the bug was discovered only recently by users (*).
In addition to the bug fix, in this PR we remove remnants of previous implementation changed by #17087.

Expected changes: boosted taus (in MiniAOD), especially those with other tau candidate within R<0.5, are more isolated. This will recover states from before #17087 as shown in the attached figure.

BoostedH

We intend to backport the fix to 11_1_X (using current dev branch) and 10_6_X for analyses based on those releases, i.e. respectively preparation to Run3 and Run2 legacy analyses.

(*) Unfortunately, developers and users of boosted taus prepared their analyses with 80X samples and then changed interests or even left CMS. In addition the code resides beyond tau packages and the change has not been consulted with Tau POG... This suggest need of more focus on monitoring boosted Taus, but this requires DQM based on miniAOD objects not present for taus, yet.

#### PR validation:

Tested with the standard miniAOD workflow.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
> The bug has been introduced in #17087 (for 90X) speeding up boosted tau seed producer code.

what is the impact of this fix on the CPU time?
Please check and update the PR description.

> but this requires DQM based on miniAOD objects not present for taus, yet.

What is missing in the miniAOD jobs to allow for the DQM to run?

**Comment by mbluj** [comment]
> 
> 
> > The bug has been introduced in #17087 (for 90X) speeding up boosted tau seed producer code.
> 
> what is the impact of this fix on the CPU time?
> Please check and update the PR description.
> 
> > but this requires DQM based on miniAOD objects not present for taus, yet.
> 
> What is missing in the miniAOD jobs to allow for the DQM to run?



> 
> 
> > The bug has been introduced in #17087 (for 90X) speeding up boosted tau seed producer code.
> 
> what is the impact of this fix on the CPU time?
> Please check and update the PR description.

No, should not affect CPU time. It is as it does not change algorithmic improvements introduced by #17087 (replacement of looping over jet constituents by search of a key stored in unordered_set), but just fixes indexes of maps used (2nd map is used in 1st call of affected function and 2nd in 1st rather than 1st index in 1st call and 2nd in 2nd). The following tau modules are run in the same way as before the fix and should not be affected by reverted indexes or even work a bit faster thanks to a smaller number of isolation candidates.  
> 
> > but this requires DQM based on miniAOD objects not present for taus, yet.
> 
> What is missing in the miniAOD jobs to allow for the DQM to run?

I think that nothing is missing, it is just a lack of standard monitoring workflow for taus in miniAOD. As far as I know it is foreseen, but not present, yet. One should also find a good set of samples to monitor boosted taus as I am affraid that standard relvals used for tau monitoring (ZTT, qqHTT) do not cover relevant phase-space. Regardless, the comment is meant to inform that we note the lack of boosted taus monitoring and need to fix it.

**Comment by mbluj** [comment]
Adding @abdollah110 who found the bug.

**Comment by perrotta** [comment]
@mbluj 
The jenkins tests outputs show differences only for boosted taus in miniAOD, as expected.
Where can I find a map of the TauID content in miniAOD, just to get a quick idea about the differences shown, e.g., in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-06-01-1100+51d92b/36739/validateJR/all_OldVSNew_RunJetHT2017FreMINIAODwf136p8311/ ?

**Comment by mbluj** [comment]
TauID list as in recent 11_2_X IB attached
[tauID_list_11_2_X.txt](https://github.com/cms-sw/cmssw/files/4722404/tauID_list_11_2_X.txt)
I hope it helps. In general, I expect some changes in a number of tauIDs as many of them examine activity around tau ("isolation").

**Comment by slava77** [comment]
a manual check can be done with 
compare_patTaus_IDs from https://github.com/slava77/cms-reco-tools/blob/master/printFWLite.C#L219
with smth like
```
.L ~/tools/printFWLite.C++
std::string fNameRef = "ref.root"
std::string fNameNew = "new.root"
compare_patTaus_IDs(fNameRef, fNameNew, "slimmedTaus");
```
it should print the ID re-index from the first event and show if there are differences in existing IDs

**Comment by perrotta** [comment]
+1
- The fix acts as it should, following the PR description and the intention behind the original code
- Jenkins tests pass and only show differences in the boosted tau id objects in miniAOD, as expected

**Comment by silviodonato** [comment]
+1

**Pull request merged**
