### PR TITLE
Adding Two Secondary Datasets for JME POG

### PR DESCRIPTION
**Pull request by jordan-martins**
Hi,

This PR addresses the ongoing effort within JME POG to understand the highPt Jets tail highlighted by the dijet analysis. The idea is to provide two SDs from Muon (Z+jets) and EGamma (Photon+jets) PDs streamed by specific HLT paths. 

In this PR we offer the following:
- PDWG_EGMJME_SD_cff.py: This file filters the HLT path for the EGamma PD
- PDWG_MUOJME_SD_cff.py: This file filters the HLT path for the Muon PD
- Skims_PDWG_cff.py: This is updated with the event content to be requested. We have set up RAW-RECO (not just RAW because we have experienced troubles with RAW as SD within T0; see ReseverDMu example)
- autoSkim.py: This is updated for two purposes: 
1- in the scope of this PR, 2022 has Muon and EGamma, and 2023 has EGamma[0,1] and Muon[0,1]
2- given that a full ReRECO of 2022 and 2023 is on the horizon, 2022 PDs have been allowed (removed the #) so that PdmV can ask for the Skims as a whole for all the PDs.

There will be a backport to 13_3_X and 13_0_X. 

Thanks,
PPD

### CODE REVIEW

**Comment by jordan-martins** [comment]
please test

**Comment by youyingli** [comment]
Hi @jordan-martins , following the full ReReco 2022/2023 based on CMSSW_14_0_X, is it necessary to backport to 13_3_X and 13_0_X? Or will JME POG have special production under those cmssw versions?

On the other hand, the HLTs for some skims are different between 2022 and 2023. I will put both years' HLTs together for these skims to synchronize 2022 and 2023 full ReReco skim after this PR is merged.

**Comment by jordan-martins** [comment]
Hi @youyingli,

We will have a special production for the JETMET for 2022 and 2023 plus the Muon and EGamma 22FG PDs. For that, we will use the 130X. At some point, it was unclear if we wanted to move to 133X, mainly because of the nanov13 (yet to be concluded at 133X), hence why the backport for that as well, and not 132X or 131X. 

Thanks for checking the HLTs skims, indeed, as you highlighted, we will do a full ReRECO of 2022 and 2023 in 140X that will require not only Skims but AlCa outputs to be available for those years based on the PDs (as some had naming changes :) ).

Is it clear?

Thanks,
PPD

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
