### PR TITLE
update EXO NoBPTX trigger paths validation for 2017 pp collisions

### PR DESCRIPTION
**Pull request by jalimena**
This PR updates the trigger path names in the exotica offline validation, for the NoBPTX triggers, for the 2017 pp collision menu.

### CODE REVIEW

**Comment by jalimena** [comment]
TSG approval presentation: https://indico.cern.ch/event/637425/contributions/2586884/attachments/1457334/2249380/NoBPTXTriggersFor2017_10May2017.pdf
And corresponding JIRA ticket: https://its.cern.ch/jira/browse/CMSHLT-1252

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
thanks !
what about https://github.com/cms-sw/cmssw/pull/18950 ?

**Comment by fwyzard** [comment]
tracked by #19142

**Pull request merged**
