### PR TITLE
Muon CITK fix

### PR DESCRIPTION
**Pull request by jhgoh**
This PR includes fix of configuration files + minor changes in example code.

The veto cone sizes in the CITK configuration was set incorrectly thus giving inconsistent isolation value to the standard isodeposit one.
After the fix, all muon candidate shows no difference to the standard one.

Also the analyzer module in PatExample is updated to read from pat muons for convenience and consistency.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9964 cb488b349751619b3dbee8e343cd8b1ec6cee540

Small fix for CITK muon isolation cone size.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9964/8440/summary.html) against baseline CMSSW_7_6_X_2015-06-29-2300 show no significant differences.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
