### PR TITLE
Update Hcal in Extended 2017 Scenario to 2016a

### PR DESCRIPTION
**Pull request by ianna**
- Update Hcal numbering from 2015 to 2016a

Note: Corresponding payloads in DB referenced by upgrade2017 GT defined here: https://github.com/cms-sw/cmssw/pull/14748

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@ggovi reminder...

**Pull request merged**
