### PR TITLE
added 13 and 14 TeV configs for sibyll, epos and qgsjet

### PR DESCRIPTION
**Pull request by cbaus**
not very urgent but these are the config fragments for upcoming energies
might be good for the users to have these

### CODE REVIEW

**Comment by bendavid** [comment]
Generator fragments normally go in Configuration/Generator/python, but even there only if they really need to be in the release.

Can these simply go in genproductions?

**Comment by cbaus** [comment]
OK sure, I can add them to there. Thanks for the comment.
FSQ group plans to make requests for 13 TeV with these generators so they actually are needed. I can leave out the 14 TeV ones for now. You may close this PR then.

**Comment by bendavid** [comment]
-1
Ok, (actually only you or the release managers can close it.)

Production requests can still be made from fragments in genproductions, so even the 13TeV ones are not needed in cmssw necessarily.

**Comment by cbaus** [comment]
I meant that I will add the 13 TeV ones into GenProduction.
Let me try to close it.
Cheers.

**Pull request closed without merging**
