### PR TITLE
Support phase-2 IT tags in pixel Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to support the visualization of conditions for the phase-2 Inner Tracker with the Pixel Payload Inspector. The class `PixelRegionContainers` is modified in order to allow the display of conditions for the Phase-2 Pixel. In order to do that an auxiliary struct `PhaseInfo` is introduced and used where necessary. Usages of that class outside of `CondCore/SiPixelPlugins` (namely in ` Alignment/OfflineValidation`) are adjusted accordingly.
I profit of this PR to migrate to the new class templates introduced in #29622 where not yet done.

#### PR validation:

Relies on the existing unit tests.
Example of plot obtainable with Phase-2 LA tags:

B55E4E1E-EE68-104E-9738-85EB6CB036B7

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, and no backport is needed.
cc: @tvami

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tlampen** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
