### PR TITLE
Restructure validation scripts

### PR DESCRIPTION
**Pull request by rovere**

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@rovere @ianna , looks like this PR broke the Material Budget IB tests https://cmssdt.cern.ch/jenkins/job/ib-run-material-budget/681/console 
Running locally I see
```
cmsRun /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-04-29-1100/src/Validation/Geometry/test/runP_Tracker_cfg.py
----- Begin Fatal Exception 02-May-2017 14:56:50 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-04-29-1100/src/Validation/Geometry/test/runP_Tracker_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named plot_utils
----- End Fatal Exception -------------------------------------------------
```
reason is that the plot_utils.py is not in PYTHONPATH. @rovere , may be move Validation/Geometry/test/plot_utils.py to Validation/Geometry/python/plot_utils.py

**Comment by rovere** [comment]
I'll make a separate PR soonish. Thanks for reporting.

**Comment by smuzaffar** [comment]
@rovere , looks like Validation/Geometry/test/MaterialBudget.C is also needed by material budget tests

**Comment by rovere** [comment]
@ianna @smuzaffar 
May I suggest having exact instructions about what is actually run at PR integration? Otherwise, we can go back and forth forever, wasting time uselessly.
Exact commands, environments, etc, would be really appreciated. It could also be the case that those commands have to be updated....

**Comment by smuzaffar** [comment]
this is what we run https://github.com/cms-sw/cms-bot/blob/master/run-material-budget
just create a CMSSW 91X dev area , set the env and run the above script.

For comparison we run https://github.com/cms-sw/cms-bot/blob/master/compare-material-budget

**Comment by rovere** [comment]
@smuzaffar @ianna 
Hopefully this https://github.com/cms-sw/cms-bot/pull/839 will fix all issues.

**Comment by smuzaffar** [comment]
thanks @rovere . cms-bot changes worked.

**Pull request merged**
