### PR TITLE
Run3-TB55 Remove direct access to DDCompactView in the SIM code for HCAL TB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove direct access to DDCompactView in the SIM code for HCAL TB application

#### PR validation:

Tested using cfg files in SimG4CMS/HcalTestBeam/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
