### PR TITLE
Backport bugfix to 74X from PR 7950

### PR DESCRIPTION
**Pull request by lihux25**
Backport four bug fixes from PR #7950 to 74X.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I see quite a few changes in the hcal digi monitoring plots.

Are these all expected from the fix or do they reveal a different problem now that the channels IDs are handled correctly on unpacking side?

These are from jenkins 1306 (muon pt=1, mainly "noise" in Run-2 setup)
wf1306_gooddigioccupancy

wf1306_htrvsdcc_corruption

This is for Run1 no-PU TTBar setup (25.0 workflow)
wf25_he_overthresh

**Comment by lihux25** [comment]
@agude @jmmans and @abdoulline, please take a look at what Slava showed to see if they are expected or not. Thanks!
P.S., as in the title, I back ported the bug fixes in the original PR #7950 to 74X.

**Comment by agude** [comment]
@slava77, @lihux25

We're taking a look!

**Comment by agude** [comment]
@slava77

So I can rerun 1306 with `runTheMatrix.py -l 1306`, but I can't generate the comparison using my files and the code in this script: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-27-0200+7972/6298/command-1306.0

I get an error where it can't find the "....Utilities/RelMon/data/blacklist.txt" file. Do you know of a way to run the comparison?

**Comment by slava77** [comment]
Hi Alex,

You can follow
https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Compare_outputs_DQM_style

With these specific instructions you are better off testing workflow 25.0
(instructions for it should work out of the box).

I ran our RECO tests with some extra statistics
My observations here are the following:
- all tests show that the monitored RECO (or HLT) quantities are the
same, except
for reported changes in DQM DigiMonitor_Hcal RawDataMonitor_Hcal and
HcalInfo histograms
- outputs from data workflows are unchanged (there is no full
raw->digi->raw repacking in these workflow, only for the trigger-related
digis)
- both run1 and run2 MC workflows have changes and they look the same
for run1 and run2
-- changes in MC without pileup are fairly large  (*1313*ps.gz file
attached for Run-2 QCD dijet )
-- changes in MC with pileup are pretty small  (*25202*ps.gz attached
for Run-2 TTbar with PU)

I hope these details can help.

Cheers

		--slava


On 3/3/15 8:09 AM, Alexander Gude wrote:
> @slava77 <https://github.com/slava77>
> 
> So I can rerun 1306 with |runTheMatrix.py -l 1306|, but I can't generate
> the comparison using my files and the code in this script:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-27-0200+7972/6298/command-1306.0
> 
> I get an error where it can't find the
> "....Utilities/RelMon/data/blacklist.txt" file. Do you know of a way to
> run the comparison?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7972#issuecomment-76951413>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by davidlange6** [comment]
@lihux25 - please give this PR a descriptive title for the release notes. Thanks.

**Comment by agude** [comment]
@lihux25 -- @jmmans and I have debugged the issues that @slava77 raised above and have fixed them on our local branch: https://github.com/UMN-CMS/cmssw/commits/jeremy_changes

Specifically these commits:

- 7986328626333c4b5600144a351a00ec8ca6712d
- 3fcd056a278a07b4488b138a5072fe3276cb27d1
- 86cefac3ff246c22e644f935f80a8681cf7f1c97
- edfb8ea6476ef0d0e9ce4952854872499181bf2f

However, as @slava77 noted in #8013 (https://github.com/cms-sw/cmssw/pull/8013#issuecomment-77261372) since we need the ability to unpack the uHTRs in 7_3, we'll need the same commits in 7_4. So perhaps it is best to close this PR and I can push our full set of commits? Otherwise you can rebase your branch and push it. I don't have a preference, so whichever seems best to you.

**Comment by agude** [comment]
@lihux25 told me in email he'd prefer it if I would submit a new PR instead of having him update this one (as discussed in https://github.com/cms-sw/cmssw/pull/8013#issuecomment-77347545), so I've opened #8103.

This PR can be closed without action.

**Comment by slava77** [comment]
-1

superseded by #8103

**Comment by lihux25** [comment]
Yes. thanks Alex!

**Pull request closed without merging**
