### PR TITLE
L1T phase-2: Update to histogram (Phase-1 like) jets

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

    Modifications to jet finder to improve the agreement with the corresponding firmware.

    Add option for trimmed jets, which improve the 9x9 jet finding performance for nearby/close to merging jets

    Add python configuration for 9x9 and trimmed 9x9 jets, in addition to the default 7x7 (perhaps 9x9 should now be made the default configuration)

    Add calculation of MET to the jet producer, and add a new producer that calculates HT and MHT from the jets

#### PR validation:

    The presentation at the Correlator meeting was based on this version of the emulator, albeit using CMSSW_10_X_Y. The features have been ported to CMSSW_11_1_7.

    I double checked the emulator in CMSSW_11_1_7 still gives the same level of agreement with the HLS code over 10k ttbar+200PU events

    The efficiency turn on curves also look the same.

Rebase of https://github.com/cms-l1t-offline/cmssw/pull/883

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Rebase of https://github.com/cms-l1t-offline/cmssw/pull/883

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
@EmyrClement @rekovic Can you please check this PR (rebasing of https://github.com/cms-l1t-offline/cmssw/pull/883) is ok from your side?

**Comment by cecilecaillol** [comment]
+l1

**Comment by EmyrClement** [comment]
@cecilecaillol This looks ok from my side, I get the same output before/after the rebase.

**Comment by srimanob** [comment]
+Upgrade

**Comment by mrodozov** [comment]
Hello there,

after this was merged yesterday 11 unit tests started failing in our python3 IBs, in DEVEL and PY3 IB:

https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/tue/12.0.PY3-tue-23/CMSSW_12_0_PY3_X_2021-05-11-2300?utests

https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/tue/12.0.DEVEL-tue-23/CMSSW_12_0_DEVEL_X_2021-05-11-2300?utests

I didn't investigated much just enough to see 
https://github.com/cms-sw/cmssw/pull/33606/files#diff-75c61e837f10b2ee77ba43a4d660d39177424ff6a69a5930b52badbe8e3f39bdR4

which is what this builds complain about. 
@cecilecaillol one can setup this IBs with 
`scram p CMSSW_12_0_DEVEL_X_2021-05-11-2300`
and then add this packages to try fix the missing module :)

**Comment by srimanob** [comment]
Thanks, @mrodozov for reporting.

Do yu think that we will see the same issue if we do the PR-test in python3? How can we start to do PR-test with python-3 during the transition period? @smuzaffar @davidlange6

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_12_0_PY3_X_2021-05-10-2300

**Comment by mrodozov** [comment]
so one get the latest PY3 or DEVEL release before the change and tests against it
it's not enabled by default but that's why we have the testing by bot in such cases

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort
i forgot to add a pkg with unit tests failing

**Comment by mrodozov** [comment]
test parameters:
- release = CMSSW_12_0_PY3_X_2021-05-10-2300
- addpkg = DQMOffline/Configuration

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
> Thanks, @mrodozov for reporting.
> 
> Do yu think that we will see the same issue if we do the PR-test in python3? How can we start to do PR-test with python-3 during the transition period? @smuzaffar @davidlange6

to answer how to do it if you are suspecting there might be a problem you can use the 
`please test for CMSSW_12_0_PY3_X` but in this case there was not guarantee you'll catch anything because the unit tests are within the L1Trigger/L1CaloTrigger domain for this PR
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bd2a58/14801/unitTests/log.txt
- and the failing one are in other packages.

**Comment by mrodozov** [comment]
voila, the DQM tests failed :)

**Pull request merged**
