### PR TITLE
GEMDPhi for CMSSW 74X

### PR DESCRIPTION
**Pull request by dildick**

### CODE REVIEW

**Comment by civanch** [comment]
@dildick , in CSCCorrelatedLCTDigi.h a new member is added
uint16_t gemDPhiBits;
which is not initialized in the constructor, is not cleaned in clean(), not used in copy constructor

**Comment by davidlange6** [comment]
Is there a summary of what this development is that I can look at? I'm naively worried about putting together GEM and CSC at the data format level.

**Comment by dildick** [comment]
Hi @davidlange6 We need the GEMDPhi to build the GEM-CSC integrated local trigger in the simulation. I can send you some slides about the studies.

**Comment by dildick** [comment]
It would be better to discuss this offline first. I'll close this one and the 75X PR

**Comment by ptcox** [comment]
I second David's reluctance to couple CSC and GEM at DataFormat level. Looks nasty. Surely better to create a new GEM format?

**Pull request closed without merging**
