### PR TITLE
Fix in PF reconstruction for the  spike at MET=0.0 - 76X version 

### PR DESCRIPTION
**Pull request by bachtis**
See detailed info in #11280

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I ran on some run2 data files with PromptReco setup:
```
python $CMSSW_RELEASE_BASE/src/Configuration/DataProcessing/test/RunPromptReco.py \
  --scenario ppRun2 --global-tag  76X_dataRun2_v1 --lfn fileName --reco --miniaod \
--aod --dqmio --alcarecos \
TkAlMuonIsolated+HcalCalIterativePhiSym+DtCalib+MuAlCalIsolatedMu+MuAlOverlaps+MuAlZMuMu\
 --dqmSeq @standardDQM+@miniAODDQM+@common
```

using 200 events from run=251721 lumi=21, run=254790 lumi=100 from each of the following 
```
/store/data/Run2015C/DoubleMuon/RAW/v1/000/254/790/00000/50BB1C89-2E48-E511-84D3-02163E01464A.root
/store/data/Run2015B/DoubleMuon/RAW/v1/000/251/721/00000/44C77595-412A-E511-930E-02163E012A2C.root
/store/data/Run2015B/DoubleEG/RAW/v1/000/251/721/00000/6AF9A34A-332A-E511-8E37-02163E013770.root
```

The net effect is 6 events with changes in MET:
```
run    * lumi   * event    *   pfMet new   * pfMet baseline
*    254790 *       100 * 104791575 * 5.8952417 * 0.6262028 *
*    254790 *       100 * 103843044 * 12.843196 * 3.9511876 *
*    254790 *       100 * 104315500 * 20.552207 * 7.8147110 *
*    254790 *       100 * 103942788 * 11.001174 * 5.0808033 *
*    251721 *        21 *  22728842 * 17.854732 * 11.107346 *
*    251721 *        21 *  22491614 * 63.105297 * 17.330709 *
```

For the last event, there were two PFCandidates with baseline, which are now gone:
```
* pt    * eta *  phi  * pdgId *
* 28.116415 * 3.5896961 * -0.438245 *         2 *
* 20.984685 * 3.6114101 * -0.438245 *         1 *
```

- only the first event has the MET somewhat close to 0. The rest has larger values. Please confirm that this should be happening to higher MET values as well (it's hard for me to actually see how there will always be enough hits in HF to pull them back in in the ::checkCleaning and make MET of ~ 0)
- For some reason, I have expected that MET deltas are small. Please confirm that large shifts are possible.

**Comment by slava77** [comment]
Two more events with changes of MET in data show up in run1 pp data inputs, a part of the short matrix workflow (the same 760pre5 as baseline + this PR [cherry picked]).
Here, each workflow test has 100 events.

```
workflow 4.29:  * run * lumi * event * pfMet new * pfMet baseline *
*    177719 *       223 * 235482262 * 15.151011 * 9.7629365 *
... baseline pf cand removed: 	      pt * eta * phi * pdgId
       * 6.2923164 * -3.057779 * -1.484268 *         2 *
workflow  4.53: * run * lumi * event * pfMet new * pfMet baseline *
*    194533 *       329 * 461715364 * 49.957996 * 41.831752 *
... baseline pf cand removed: 		      
       * 9.8277549 * 3.0802521 * -3.053809 *         1 *

```

So, the primary effect of the PR appears to be a recovery or increase of MET by "forgetting"  PF candidates in HF. The rate of the effect is 
-  about ~0.5% in 50 ns data (4 events out of 800 processed)
-  about 2% in 25 ns data
- small (no events appeared in about 1K events) in no-PU MC; and possibly small (only ~200 events tested) in pp MC with PU

**Comment by slava77** [comment]
... I'll run on more events from 254790 to see if any pfMet ~0 show up.

**Comment by slava77** [comment]
So, after running on 5.9K events, the pfMet~0 (<100 MeV) contribution is visible statistically significant with about 1/3 of all events with changing pfMets.
- 2.2% of events have a different pfMet as a result of this PR
    - 0.8% had pfMet < 100 MeV and now have it around 5-10 GeV higher. *essentially all of this pfMet has phi ~ 1*
    - 0.3% have an epsilon (<<100 MeV) change in pfMet with sizeable (>>1) original and new values 
    - remaining (about a half of all with changes) had the original pfMet generally  >>1 GeV and the new pfMet values also >>1 GeV higher than the original.

I'm running on more events in MC with 25ns PU to see if there is a significant effect there (the claim is that here the fraction is much smaller)

@davidlange6 , if it's urgent to build 75X in the next few hours, then #11283 could be merged preemptively. Otherwise, I'm expecting results early PM

**Comment by slava77** [comment]
I finished with 2K events (all we had as of the start of the tests in /RelValZMM_13/CMSSW_7_6_0_pre5-PU25ns_76X_mcRun2_asymptotic_v1-v1/GEN-SIM-DIGI-RAW-HLTDEBUG):
- There are only 8 events with changes in pfMET (0.4%)
- all changes in pfMet in this case are with an "epsilon" change (incidentally, about the same rate as in data).

Attempting to conclude here:
-  HF noise or other kind of not-so-good-for-pf hits  with fairly large ET is a much bigger problem in data (by at least 5-10 times)

**Comment by davidlange6** [comment]
Hi Slava

Could you then sign the 75x pr and I'll start that build.



On Sep 18, 2015, at 2:23 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:


I finished with 2K events (all we had as of the start of the tests in /RelValZMM_13/CMSSW_7_6_0_pre5-PU25ns_76X_mcRun2_asymptotic_v1-v1/GEN-SIM-DIGI-RAW-HLTDEBUG):

  *   There are only 8 events with changes in pfMET (0.4%)
  *   all changes in pfMet in this case are with an "epsilon" change (incidentally, about the same rate as in data).

Attempting to conclude here:

  *   HF noise or other kind of not-so-good-for-pf hits with fairly large ET is a much bigger problem in data (by at least 5-10 times)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11284	e91e222
- HF hits are no longer put back into the list of PF candidates based on their effect on MET (checkCleaning)
    - in data, this removes a component with occasionally large ET hits pushing MET down and also removes MET~0 bump near phi~1
    - small (epsilon size) changes in MET are present as a result of this PR at ~0.3-0.5% level in both data and MC with 25 ns PU
- jenkins tests pass and comparisons with baseline show single-event changes as expected from the higher statistics test

**Pull request merged**
