### PR TITLE
Include the staggered GE21 geometry in M2

### PR DESCRIPTION
**Pull request by pietverwilligen**
inclusion of the staggered gap geometry for ge21 in M2
continuation of PR #17970  #17970

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
Now #17995 is merged (starting in IB `CMSSW_9_1_X_2017-03-23-1100`), so this needs to be updated again for D13...

**Comment by ianna** [comment]
@kpedro88 - I wonder why unit test does not fail?

**Comment by kpedro88** [comment]
Tests ran on `CMSSW_9_1_X_2017-03-22-2300`, before the PR was merged.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by calabria** [comment]
@pietverwilligen can you please update this PR?

**Comment by kpedro88** [comment]
-1
until 2023 geometries are synchronized

**Comment by kpedro88** [comment]
-1
needs rebase

**Comment by pietverwilligen** [comment]
rebase to which IB? I lost the original IB, so I checked out my branch in CMSSW_9_1_X_2017-03-31-1100 and I pushed from there. Should I rebase to the original IB in which I created the PR = CMSSW_9_1_X_2017-03-23-1100?
Thanks

**Comment by ianna** [comment]
git rebase CMSSW_9_1_X

**Comment by kpedro88** [comment]
Merging is never the right strategy to update a PR that has conflicts. `git cms-merge-topic` can be useful to recreate a working area by checking out the appropriate packages automatically, but whenever you merge a branch from an old IB into a new IB and then push, you will get this result (100s of duplicated commits added to the PR). Instead, you should follow the instructions which I link frequently: https://twiki.cern.ch/twiki/bin/view/CMS/CMSGitTutorial#CMSSW_rebasing_recipe.

By "lost the original IB", do you mean you lost your working directory? You can rebase your branch without having the working directory, because the branch just lives in Git. But now the branch contains the result of an improper merge. There are ways to fix this, but it is much better not to do it in the first place. It would probably be easiest just to cherry-pick your few changes into a clean branch at this point.

**Comment by kpedro88** [comment]
-1
nope

**Comment by pietverwilligen** [comment]
ok i like the clean branch idea

**Comment by pietverwilligen** [comment]
with "lost my original IB", I meant really "lost the working directory". 
for my education, i should have taken a new (est) IB and rebase to the old IB, which I remember was CMSSW_9_1_X_2017-03-23-1100?

**Comment by ianna** [comment]
@pietverwilligen - no, you should not rebase from the new IB to the old IB. Please, follow the tutorial: http://cms-sw.github.io/tutorial-forward-port.html

**Comment by kpedro88** [comment]
Actually, please don't follow that tutorial, as it instructs you to do a merge, which is precisely the problem. (We should remove that part...)

You can do something like this.
Step 1:
```
cmsrel NEW_IB
cd NEW_IB/src
cmsenv
git cms-init
git checkout -b my-branch remotes/my-cmssw/my-branch
git rebase --onto NEW_IB OLD_IB my-branch
```
Step 2:
```
git push -f my-cmssw my-branch
git checkout from-NEW_IB
git cms-merge-topic user:my-branch
git checkout my-branch
```

The contents of `my-branch` live in Git. `git cms-init` imports all of the branches from your fork, so all you need to do is checkout a local copy of the branch and rebase it. There's no need to do any merging, since during the rebase you will be at most editing code (not compiling or running). In step 2, you're just fixing your working area so you can actually compile and run workflows (you get the packages and dependencies for the now-rebased branch, and then re-checkout a local copy of that branch to remove the unnecessary merge commit from `git cms-merge-topic`).

**Comment by pietverwilligen** [comment]
great! thanks a lot. I ll print it and hang it above my bed ;-)

**Pull request closed without merging**
