### PR TITLE
Updated the alphaT paths for the DQM modules

### PR DESCRIPTION
**Pull request by aelwood**
In line with a JIRA ticket currently being submitted for changes to the alphaT trigger paths.

### CODE REVIEW

**Comment by deguio** [comment]
@aelwood please submit to 75x first

**Comment by aelwood** [comment]
@deguio I've made a PR for 75x https://github.com/cms-sw/cmssw/pull/8945

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
