### PR TITLE
[ALCA][DB] Fix copy-constructor warnings reported in DEVEL IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Hello,

This PR solves the DEVEL warnings on deprecated copy-constructors present in the IBs on some ALCA-DB modules.

Thanks,
Andrea

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by perrotta** [comment]
+1
- Implementation looks correct, i.e. removed constructors can be replaced by the default ones

**Pull request merged**
