### PR TITLE
Refactor RecoTrackSelector and RecoTrackRefSelector

### PR DESCRIPTION
**Pull request by makortel**
This PR refactors the commonalities of RecoTrackSelector and RecoTrackRefSelector to a new base class (RecoTrackSelectorBase; as suggested by a comment in RecoTrackRefSelector). I'm planning to add a third variant (reading tracks through View), and without the refactoring the code would become even more messy. I also took the opportunity to do a similar refactoring of the configuration parameters. I took this separate from the other developments in the hope of smoother integration for purely technical changes.

Tested in CMSSW_7_5_X_2015-06-14-2300, no changes expected in results.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
(hoping for no DAS errors this time)

**Comment by cvuosalo** [comment]
+1

For #9658 b969345f4f0d2d027c96f428b265d814f29f0cf4

Refactoring RecoTrackSelector and RecoTrackRefSelector code. There should be no change in run-time behavior.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9658/2592/summary.html) against baseline CMSSW_7_5_X_2015-06-19-1100 show no significant differences, as expected.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
