### PR TITLE
[MultiTrackValidator] Fix #35225

### LINKED ISSUE #35225: makeTrackValidationPlots.py crashes in CMSSW_12_1_0_pre2
Hi,

I encountered a crash when running the command `makeTrackValidationPlots.py DQM_RelValTTbar_D76PU200_14TeV_12_0_0_pre6.root DQM_RelValTTbar_D76PU200_14TeV_12_1_0_pre2.root --ptcut --extended --html-sample TTbar_D76PU200_12_0_0_pre6_vs_12_1_0_pre2 --html-validation-name TTbar_D76PU200_12_0_0_pre6_vs_12_1_0_pre2
` in CMSSW_12_1_0_pre2, which works properly in CMSSW_12_0_0_pre6.

The complete log is attached here [makeTrackValidationPlots.log](https://github.com/cms-sw/cmssw/files/7140180/makeTrackValidationPlots.log)

I also noticed with #34954, ` Validation/RecoTrack/python/plotting/validation.py` will start a large number of subprocesses simultaneously. Will it be better to add some args to limit the max number of the subprocesses?

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR fixes a bug introduced with #34954: in case of an empty `PlotterFolder`, the return value of the `SimpleValidation._doPlots` function was different and caused the raise of an Exception.
The warning for a missing object in the `PlotterFolder` is now always printed (not only with the `verbose` option).

#### PR validation:

`makeHGCalValidationPlots.py` and `makeTrackValidationPlots.py`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
Could the title of the PR be changed to something more self explanatory (e.g. mention at least MultiTrackValidator)? It would help with the release validation procedure

**Comment by qliphy** [comment]
+1

**Pull request merged**
