### PR TITLE
Fix sigstack printer.

### PR DESCRIPTION
**Pull request by bbockelm**
We observed that, when CLONE_VFORK is used, gdb sometimes did not
print out the thread associated with the calling process.  As this
is the thread which caused the SEGV in the first place, it made the
sigstack printer less-than-useful.

We were not able to identify why it worked with the CLONE_VFORK in
some cases.

Further, we observed that instances exiting with SEGV/BUS/ILL always
returned exit status 134 (SIGABRT).  This rethrows the signal in
order to get the correct exit status.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
We also need ports to 7_5 to 7_6.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
