### PR TITLE
[13_3_X] Adapt PF code to read Hcal thresholds from GT

### PR DESCRIPTION
**Pull request by swagata87**
Verbatim backport of https://github.com/cms-sw/cmssw/pull/43025

Technical PR. No change in physics should be there; except: 
- some changes in Phase2 HLT, the cause of which is understood -> https://github.com/cms-sw/cmssw/pull/43025#issuecomment-1814590349 ). 
- some non-reproducibility issues https://github.com/cms-sw/cmssw/issues/43293

This PR allows HCal thresholds to be read from GT, so that during data-taking the thresholds can be updated more easily, w/o the overhead of needing a new CMSSW release every time there is a threshold update.

If this can enter 13_3_X then a proper validation with high-stat will be possible, which can be useful to gain more confidence before using it for 2024 data-taking.

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
@swagata87 

> Moreover, https://github.com/cms-sw/cmssw/pull/43171 is not backported to 13_3_X, that will also give rise to differences in phase2 HLT WFs.

this appears to not be correct. I think #43171 was still merged within 13_3_X (at least I see the commit https://github.com/cms-sw/cmssw/commit/58e9d75bf966230e33809ab4f01a10128a5dbb34  in the 13_3_X branch history). Please amend the PR description.

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43025

**Comment by mmusich** [comment]
type pf

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/43025;
   * see https://github.com/cms-sw/cmssw/pull/43025#issuecomment-1815844471 for more detailed analysis.

**Comment by swagata87** [comment]
> this appears to not be correct. I think #43171 was still merged within 13_3_X (at least I see the commit [58e9d75](https://github.com/cms-sw/cmssw/commit/58e9d75bf966230e33809ab4f01a10128a5dbb34) in the 13_3_X branch history). Please amend the PR description.

ah okay, now the PR description is fixed

**Comment by swagata87** [comment]
I received a notification from PPD that this development is mainly for 14_0 cycle. I guess this backport is not needed in that case. If I understood the plans correctly, I can probably just close this PR.

**Comment by antoniovilela** [comment]
hold
   - Let's avoid merging the backport, at least for now.

**Pull request closed without merging**
