### PR TITLE
PAT fix for boosted taus

### PR DESCRIPTION
**Pull request by ferencek**
Backport of the first two commits from #14639

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
Overlooked that the second commit from #14639 fixes a typo. Now I included that second commit and the unit tests should no longer fail.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15413 49983118caa086ac132011e589cd7adb72ddaf50

Fix to remove MC matching in PAT for boosted taus. There should be no change in monitored quantities.

Partial backport of #14639.

The code change matches part of changes in #14639, and Jenkins tests against baseline CMSSW_8_0_X_2016-08-11-1100 show no significant differences, as expected. A comparison of expanded RECO configs for workflow 25202.0_TTbar_13 shows no differences against baseline CMSSW_8_0_17. The 25202.0 config includes Mini-AOD production. This check shows this PR does not alter RECO or Mini-AOD.

**Pull request merged**
