### PR TITLE
hltConfigFromDB: increase the thread stack size

### PR DESCRIPTION
**Pull request by fwyzard**
increase the java thread stack size from the default (1 MB) to 32 MB, to work around java.lang.StackOverflowError errors

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild please test

(even though this script is not used by production workflows)

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
