### PR TITLE
Phase2-hgx261 Fix HGCal geometry code for V14 and masking

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix HGCal geometry code for V14 and masking

#### PR validation:

Use runTheMatrix.py workflows for testing

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
