### PR TITLE
(DAQ) Revert to untracked parameters and new configuration

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
Reverting to untracked parameters in EvFDaqDirector as discussed in #28151
Including also these changes:
- new parameter is added to control if fileBrokeHost parameter can be changed within the process by looking at hltd configuration (which is current behavior).
- default value is removed from fileBrokerHost, so it must always be present for the configuration to run successfully.
- other parameters in the service have also been regrouped, and one was renamed.

#### PR validation:

Tested in DAQ "VM" test cluster with several relevant combinations of parameters. RunBUFU.sh in EventFilter/Utilities/test also runs fine.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@smorovic 
On this issue:
```
default value is removed from fileBrokerHost, so it must always be present for the configuration to run successfully.
```
please do NOT do this: parameters without a default will not be written to the fillDescriptions generated cfi file (as the code does not know which value to put).
In turn, ConfDB parsing the cfi file will never know about this parameter.
So you will never be able to set it to any value in ConfDB!
Please revert and give a value, even is it is a value of "InValid" or so, and you check the string being "InValid" and issue an error message then!

**Comment by smorovic** [comment]
Well, maybe "addUntracked" (or even "add") function without default should then be removed, unless there is use case I don't see.

It has now been changed to InValid as default.

**Comment by Martin-Grunewald** [comment]
Thanks.
People not using ConfDB GUI are able to use the feature, but ConfDB uses cfi files to discover the parameters, so for that use case all parameters must appear in the cfi file.

**Comment by smorovic** [comment]
Yes, that makes sense if they want description (and/or at least something in the generated cfi file), but no defaults.
Cheers,
Srecko

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28359	1749535 
- reco code is not affected

**Comment by fabiocos** [comment]
@mommsen comments?

**Comment by mommsen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
