### PR TITLE
HLT menu development for `14_1_X` (3/N) [`14_2_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_1_X` (branch `CMSSW_14_2_X`): 
   * This is the PR for the master branch, which will then be backported down to 14_1_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

These updates correspond to the changes accumulated in the `14_1_X` release cycle for the "**HIon V1.0**" menu: first menu for the 2024 Pb-Pb data-taking period.

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3331](https://its.cern.ch/jira/browse/CMSHLT-3331) [TSG/Scouting] Removal of `HLT_*` from ScoutingPFMonitor
- [CMSHLT-3336](https://its.cern.ch/jira/browse/CMSHLT-3336) [TSG/Scouting] Removal of `DST_PFScouting_DatasetMuon`
- [CMSHLT-3364](https://its.cern.ch/jira/browse/CMSHLT-3364) [AlCa/Tracker] Integration of paths running cosmic tracking in the Special table
- [CMSHLT-3365](https://its.cern.ch/jira/browse/CMSHLT-3365) [HIon] Review Forward/UPC Paths of `HIon` table (follow-up of CMSHLT-3350)
- [CMSHLT-3369](https://its.cern.ch/jira/browse/CMSHLT-3369) [HIon] Splitting level of PDs and streams in the 2024 PbPb menu
- [CMSHLT-3370](https://its.cern.ch/jira/browse/CMSHLT-3370) [HIon] Review of prescales of the UPC paths in the HIon table
- [CMSHLT-3372](https://its.cern.ch/jira/browse/CMSHLT-3372) [EXO,TSG] PS changes for the "`2p0E34_NoL1CICADA"` column
- [CMSHLT-3373](https://its.cern.ch/jira/browse/CMSHLT-3373) [HIon] Splitting level of PDs and streams in the 2024 ppRef menu
- [CMSHLT-3374](https://its.cern.ch/jira/browse/CMSHLT-3374) [AlCa,BRIL] Change EventContent of `ALCALumiPixelsCountsGated` stream
- [CMSHLT-3377](https://its.cern.ch/jira/browse/CMSHLT-3377) [HIon] Fix `HLT_HIUPC_MinPixelThrust0p8_MaxPixelCluster10000_v` for 2024 HIon run
- [CMSHLT-3378](https://its.cern.ch/jira/browse/CMSHLT-3378) [HIon] PPRef2024 - L1T seed change for 5 EG paths
- [CMSHLT-3379](https://its.cern.ch/jira/browse/CMSHLT-3379) [HIon] Adding a UPC single EG4 L1 passthrough trigger in HLT PbPb table

In this PR we also have the following commits:
   * 4e595751f837b61e419da0e38809bcef5a71be1a: Update `hltPathOwners.json` with the content of the HIon 2024-V1.0 menu

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_1_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
test parameters:
   * workflows = 161, 161.02, 161.03, 161.1, 161.2, 161.3, 161.4, 180.0, 180.1, 181, 181.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
