### PR TITLE
silence static analyzer warning about `std::isnan / std::isinf` in `PackedCandidate`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, addresses https://github.com/cms-sw/cmssw/pull/40555#discussion_r1085638442

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by swertz** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
