### PR TITLE
Add D76 prod-like to relval_2026

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to add D76 prod-like workflows to relval_2026. One of them, 34834.32 is expected to be used for profiling.

#### PR validation:
runTheMatrix.py --what 2026 -l 34634.21,34834.21,34834.9921 --wm init

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport, and no need for backport.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:

- workflows = 34634.21, 34834.21, 34834.9921

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
It seems we need to have [1] /RelValTTbar_14TeV/CMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v1/GEN-SIM at CERN. It is currently at T1_IT_CNAF_Disk only [2]. Do we need to make a request for a transfer?

[1]
` dasgoclient --limit 0 --query 'file dataset=/RelValTTbar_14TeV/CMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v1/GEN-SIM site=T2_CH_CERN' | ibeos-lfn-sort -u > step1_dasquery.log  2>&1`

[2]
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FRelValTTbar_14TeV%2FCMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v1%2FGEN-SIM

@qliphy

**Comment by qliphy** [comment]
> It seems we need to have [1] /RelValTTbar_14TeV/CMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v1/GEN-SIM at CERN. It is currently at T1_IT_CNAF_Disk only [2]. Do we need to make a request for a transfer?

@srimanob   Yes, we should.  @cms-sw/pdmv-l2  Would you please help on the transfer? Thanks!

**Comment by chayanit** [comment]
Ugh this is gonna be a problem... Now we are running all RelVals at FNAL and store them there, only HI Relvals are running at CERN (we are revisiting the requirement of data placement with PnR see https://github.com/dmwm/WMCore/issues/10106). Do we need to make such transfer to CERN every time for IB test? I think we need to come with some good plan for this.

**Comment by qliphy** [comment]
@chayanit  thanks.  @srimanob can comment, but I think for this PR we only need to transfer /RelValTTbar_14TeV/CMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v1/GEN-SIM  right?

**Comment by chayanit** [comment]
Hi @qliphy I understand but I'm now concerning more for the long run though.

**Comment by srimanob** [comment]
Hi @qliphy @chayanit 

I don't think we need to transfer all the time. Maybe, this is needed because I update
`defaultDataSets['2026D76']='CMSSW_12_0_0_pre3-113X_mcRun4_realistic_v7_2026D76noPU-v'`
to the most recent one. We don't update it since pre3, and I think PdmV don't ask to transfer for all releases.

But it seems we have the way to copy some needed files for test, @smuzaffar 
I see that this work without relvals at CERN:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8cf757/16331/runTheMatrixINPUT-results/34634.0_TTbar_14TeV+2026D76+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal/cmdLog
(of course, it calls to `CMSSW_11_3_0_pre3-113X_mcRun4_realistic_v3_2026D76noPU-v` which is the line I change).

**Comment by chayanit** [comment]
Hello @srimanob , we haven't updated all GENSIM in 12_0_X yet and we are going to do them sometime soon i.e. pre4 or pre5. Do you really need it to be updated in this PR?

**Comment by srimanob** [comment]
Please test

**Comment by makortel** [comment]
>  Do we need to make such transfer to CERN every time for IB test?

IB tests cache input files automatically independently of Rucio, so as long as the file is available somewhere on disk, the IB test will (eventually) work without explicit ttansfers.

**Comment by srimanob** [comment]
+Upgrade

All Phase-2 prod-like workflows run fine. What fails in comparison is not Phase-2 workflow.

**Comment by qliphy** [comment]
@srimanob   You may update the "PR description" to remove "In addition, the MinBias GS is updated to the 12_0_0_pre3 relvals".

@cms-sw/pdmv-l2   Do you have any comment?

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
> @srimanob You may update the "PR description" to remove "In addition, the MinBias GS is updated to the 12_0_0_pre3 relvals".
Done, thx.

**Comment by qliphy** [comment]
+1

**Pull request merged**
