### PR TITLE
Backport Changed CorrPCCProducer from EDProducer to DQMEDAnalyzer for LumiPOG

### PR DESCRIPTION
**Pull request by samhiggie**
Backport for PR: https://github.com/cms-sw/cmssw/pull/22868 
Please visit that thread for discussion.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by capalmer85** [comment]
"The relvals timed out after 2 hours." Doesn't seem related to the PR.  I don't think it started running any relevant part of the matrix.

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
