### PR TITLE
improve implementation of `HLTJetTag<T>` plugin template [`13_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #41351

#### PR description:

From the description of #41351 :

>This PR aims to improve the plugin template `HLTJetTag<T>` as follows.
>
> 1. Add option to match jets by delta-R (the plugin uses two jet collections: the first one is a simple jet collection, the second one is the "key" of a `JetTagCollection` whose values as the jet b-tagging scores).
> 2. If delta-R matching is not used (not using delta-R matching remains the default behaviour), the (b-)tag value of the jet is accessed via the method `edm::AssociationVector::operator[]`. This requires that the input jet collection is the same as the "key" collection of the `JetTagCollection`. If this is not the case, the plugin will throw an exception at runtime.
>
>The limits of the current implementation of `HLTJetTag<T>` were discussed in #41045.

#### PR validation:

None beyond the checks done for #41351.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41351

Backport of an HLT-related update to the release cycle used for 2023 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
Please do not start the tests yet, unless you want to see them fail.

 - The 2023 HLT menu first has to be fixed.
 - The frozen 2022 HLT menu has to be removed from CMSSW, otherwise any wf with it would fail at runtime with this PR.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
