### PR TITLE
[RFC] Add RNTuple NanoAOD output module

### PR DESCRIPTION
**Pull request by mxxo**
#### PR description:
This PR adds a new output module that generates ROOT RNTuple NanoAODs. The new 
module is based on the existing `TTree` output module class `NanoAODOutputModule`. 

Because of the RNTuple dependency, the module will likely only be functional
in the ROOT6 master integration branches.

The new module is a prototype and is missing some features. In particular, backfilling, 
(creating new branches as required and adding them to the output file) is not yet 
supported. The new module also requires unit tests. Some preliminary verification tests have
been conducted against the existing output module comparing `Events` tree output data.

We have tried to adhere as much as possible to the TTree module conventions 
but there are some differences. For example, collections are a first-class concept 
in RNTuple. Instead of requiring the user to define a separate branch `nElectron` 
for the Electron collection, and having branches named `Electron_charge`, the RNTuple
analogue is to create an Electron collection directly and access fields through dot
notation (`Electron.charge`). An alias mechanism for branch name discrepancies is 
envisioned to avoid disrupting analysis workflows.

Note: RNTuple currently prints a stability warning when writing to disk, which was treated
as a fatal error when running `cmsRun` configuration scripts. The current workaround is to 
disable the ROOT error handler in the configuration script:
```python
process.add_(cms.Service("InitRootHandlers", ResetRootErrHandler = cms.untracked.bool(False))) 
```

There is more information about this project here: 
https://iris-hep.org/assets/pdf/Max_Orok_proposal.pdf
Review comments are greatly appreciated.

cc @jblomer, @dan131riley

### CODE REVIEW

**Comment by mariadalfonso** [comment]
This PR definitively requires definitively a presentation at the XPOG meeting, first possible occasion if the 16 Jun 2021.

**Comment by arizzi** [comment]
Electron.charge in principle exists also in good old TTree but we decided not to use such syntax so that extending objects is as easy as adding a column with same prefix and proper length. Is this possible in RNtuple ? 
Backfilling is a needed feature, is there a plan to get it supported?

**Comment by mxxo** [comment]
> Electron.charge in principle exists also in good old TTree but we decided not to use such syntax so that extending objects is as easy as adding a column with same prefix and proper length. Is this possible in RNtuple ?

Yes, this is possible, you can still define a `nElectron` field and a number of `std::vector<T>` `Electron_X` fields for the data. However, there will likely be an increased storage cost compared to a "real" RNTuple collection because of the redundant index columns. I just did a quick comparison between an RNTuple collection, an adhoc RNTuple collection with a size field, and a TTree collection with max LZMA compression (there are likely other confounding factors present, this may not be representative of real data etc.) for a collection with three subfields and 100,000 entries:

```
-rw-r--r-- 1 max max 197K May 25 12:44 collection_rntuple_adhoc.root # compression ratio 17.53
-rw-r--r-- 1 max max  81K May 25 12:44 collection_rntuple.root       # compression ratio 28.46
-rw-r--r-- 1 max max 268K May 25 12:44 collection_ttree.root         # compression ratio 12.72 
```

<details>
  <summary> The comparison script for reference </summary>

```cpp
// g++ -Wall -g -O2 -std=c++1z -I${ROOTSYS}/include -o collection_cmp collection_cmp.cxx -L${ROOTSYS}/lib -lCore -lRIO -lTree -lROOTNTuple

#include <TFile.h>
#include <TTree.h>

#include <ROOT/RNTuple.hxx>

#include <cstdint>

using ROOT::Experimental::RNTupleModel;
using ROOT::Experimental::RNTupleReader;
using ROOT::Experimental::RNTupleWriter;
using ROOT::Experimental::RNTupleWriteOptions;

void makeRNTupleCollection() {
   auto filename = "collection_rntuple.root";
   auto electronModel = RNTupleModel::Create();
   auto charge = electronModel->MakeField<int>({"charge", "electric charge"});
   auto cleanmask = electronModel->MakeField<std::uint8_t>({"cleanmask", "simple cleaning mask with priority to leptons"});
   auto convVeto = electronModel->MakeField<bool>({"convVeto", "pass conversion veto"});

   auto model = RNTupleModel::Create();
   auto electron = model->MakeCollection("Electron", std::move(electronModel));

   {
      RNTupleWriteOptions opt;
      opt.SetCompression(209);
      auto ntuple = RNTupleWriter::Recreate(std::move(model), "collection", filename, opt);
      for (int i = 0; i < 100'000; i++) {
         for (int j = 0; j < 3; j++) {
            *charge = -1;
            *cleanmask = static_cast<std::uint8_t>(i);
            *convVeto = i % 2 == 0;
            electron->Fill();
         }
         ntuple->Fill();
      }
   }
   auto ntuple = RNTupleReader::Open("collection", filename);
   ntuple->PrintInfo(ROOT::Experimental::ENTupleInfo::kStorageDetails);
}

void makeAdhocCollection() {
   auto filename = "collection_rntuple_adhoc.root";
   auto electronModel = RNTupleModel::Create();
   auto size = electronModel->MakeField<std::uint32_t>({"nElectron", "slimmedElectrons after basic selection (pt > 5 )"});
   auto charge = electronModel->MakeField<std::vector<int>>({"Electron_charge", "electric charge"});
   auto cleanmask = electronModel->MakeField<std::vector<std::uint8_t>>({"Electron_cleanmask", "simple cleaning mask with priority to leptons"});
   auto convVeto = electronModel->MakeField<std::vector<bool>>({"Electron_convVeto", "pass conversion veto"});
   {
      RNTupleWriteOptions opt;
      opt.SetCompression(209);
      auto ntuple = RNTupleWriter::Recreate(std::move(electronModel), "collection", filename, opt);
      for (int i = 0; i < 100'000; i++) {
         *size = 3;
         *charge = std::vector<int>(3, -1);
         *cleanmask = std::vector<std::uint8_t>(3, static_cast<std::uint8_t>(i));
         *convVeto = std::vector<bool>(3, i % 2 == 0);
         ntuple->Fill();
      }
   }
   auto ntuple = RNTupleReader::Open("collection", filename);
   ntuple->PrintInfo(ROOT::Experimental::ENTupleInfo::kStorageDetails);
}

void makeTTreeCollection() {
   auto filename = "collection_ttree.root";
   {
      auto file = std::make_unique<TFile>(filename, "RECREATE", "", 209);
      auto tree = std::make_unique<TTree>("collection", "collection");
      std::uint32_t size;
      tree->Branch("nElectron", &size, "nElectron/i");
      std::array<int, 3> charge;
      std::array<std::uint8_t, 3> cleanmask;
      std::array<bool, 3> convVeto;
      tree->Branch("Electron_charge", charge.data(), "Electron_charge[nElectron]/I");
      tree->Branch("Electron_cleanmask", cleanmask.data(), "Electron_cleanmask[nElectron]/b");
      tree->Branch("Electron_convVeto", convVeto.data(), "Electron_convVeto[nElectron]/O");
      for (int i = 0; i < 100'000; i++) {
         size = 3;
         charge = {-1, -1, -1};
         auto bi = static_cast<std::uint8_t>(i);
         cleanmask = {bi, bi, bi};
         auto isEven = i % 2 == 0;
         convVeto = {isEven, isEven, isEven};
         tree->Fill();
      }
      file->Write();
      file->Close();
      tree.release();
   }
   std::unique_ptr<TFile> f(TFile::Open(filename));
   assert(f && ! f->IsZombie());
   auto tree = f->Get<TTree>("collection");
   tree->Print();
   tree->Print("clusters");
}

int main() {
   makeRNTupleCollection();
   makeAdhocCollection();
   makeTTreeCollection();
}
```
</details>

> Backfilling is a needed feature, is there a plan to get it supported?

Yes, the plan is to use the RNTuple "friends" API to write out backfill columns as friend files and then combine them into a single file at the end.

**Comment by jblomer** [comment]
> > Backfilling is a needed feature, is there a plan to get it supported?
> 
> Yes, the plan is to use the RNTuple "friends" API to write out backfill columns as friend files and then combine them into a single file at the end.

This is our workaround for the time being.  For backfilling within a single file, we first need the implementation of the [version 1 specification of RNTuple](https://github.com/jblomer/root/blob/ntuple-binary-format-v1/tree/ntuple/v7/doc/specifications.md), which is currently in the works. As a side note, backfilling will necessarily come with a performance impact when reading the backfilled columns, because they are at a different physical location than their peers and thus require seeking in the file.

**Comment by mariadalfonso** [comment]
please test

**Comment by dan131riley** [comment]
This needs to be tested with ROOT6 master IBs, CMSSW_12_0_ROOT6_X_2021-06-28-2300 or later.  I've asked Max to make sure it builds on older versions, but it will only be fully functional with ROOT 6.26, as Max and Jakob have added a lot of new functionality to accommodate the CMS use case.

**Comment by makortel** [comment]
> it will only be fully functional with ROOT 6.26, as Max and Jakob have added a lot of new functionality to accommodate the CMS use case.

Should we consider eventually merging this PR into ROOT6 branch, or keep the PR open until we've moved `master` to 6.26? @smuzaffar

**Comment by dan131riley** [comment]
> Should we consider eventually merging this PR into ROOT6 branch, or keep the PR open until we've moved `master` to 6.26? @smuzaffar

6.26 is far enough off that I think we should aim for merging this into the ROOT6 branch once it has some unit tests and wf's such that it would be worthwhile running tests.

**Comment by smuzaffar** [comment]
code-checks with cms.week1.PR_cadae698/46.0-2c0e2d5910666bc8fb96a896cf4beffc

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_ROOT6_X

**Comment by smuzaffar** [comment]
looks good to go in the ROOT6 IBs. Before we merge it, please replace 
```
<lib name="ROOTNTuple"/>
```
with
```
<use name="rootntuple"/>
```

**Comment by dan131riley** [comment]
> looks good to go in the ROOT6 IBs. Before we merge it, please replace

Hi @smuzaffar let's go ahead with merging this into the ROOT6 IBs, and I'll followup with some unit tests and workflows once it is merged.

**Comment by smuzaffar** [comment]
updated the branch to CMSSW_12_0_ROOT6_X and merging it

**Comment by smuzaffar** [comment]
@dan131riley this is now merged and should be available in tonight's ROOT6 IB

**Comment by smuzaffar** [comment]
I think we can now move this to master branch ( which is already using root 6.26 ). I will open a PR for master branch after local testing

**Pull request merged**
