### PR TITLE
Trivial adjustment of comments after clang-format to have a better readability

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Manual adjustment of the code to circumvent some oddities of the clang-format splitting

#### PR validation:

minimal move of a comment, the code compiles.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fabiocos** [comment]
@slava77 this should be the fix to the issue you raised...

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
