### PR TITLE
add PV monitoring @HLT

### PR DESCRIPTION
**Pull request by mtosi**
we were missing some vertex collection in the validation
and the monitoring for all collection (both online and offline)

this PR adds the validation and monitoring for vertex @HLT

there is a missing collection in the HLT output modules (hltVerticesPFFilter)
I opened the [JIRA ticket #1201](https://its.cern.ch/jira/browse/CMSHLT-1201) for adding it

I'm currently running runTheMatrix -l limited

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
it works, now
to be noticed that because we are still missing one collection of vertices in the output module of the HLT job,
we have the corresponding plots empty, but there are not crashes due to this missing collection

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
:(
when I ran `runTheMatrix -l limited`, these 2 tests failed but either on step1 or step2,
while other tests were fine, so I thought there were no more issues related to this PR ... sorry !

I've just tried to re-reun 1330.0 and 1306.0,
but I'm still failing and I'm getting the error [1] on step2 of 1306.0
any suggestions ?
thanks !

[1]
L1Trigger/L1TGlobal/python/StableParameters_cff.py is deprecated, please use GlobalParameters_cff.py instead.
L1Trigger/L1TGlobal/python/StableParameters_cff.py is deprecated, please use GlobalParameters_cff.py instead.
 #####################################################################
 # WARNING: the module CondCore.DBCommon.CondDBCommon is deprecated. #
 # Please import CondCore.CondDB.CondDB_cfi                          #
 #####################################################################
L1TCalorimeter Sequence configured for Stage-2 (2016) trigger.
L1TMuon Sequence configured for Stage-2 (2016) trigger.
L1TGlobal Sequence configured for Stage-2 (2016) trigger.
L1TCalorimeter Conditions configured for Stage-2 (2016) trigger.
L1TMuon Conditions configured for Stage-2 (2016) trigger.
L1TGlobal Conditions configured for Stage-2 (2016) trigger.
L1TDigiToRaw Sequence configured for Stage-2 (2016) trigger.
----- Begin Fatal Exception 02-Mar-2017 12:44:39 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
A std::exception was thrown.
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 653 on chan 1 failed at Thu Mar  2 12:44:39 2017: -8 [fn-htclient.c:438]: server error (HTTP/1.1 503 Service Unavailable) proxy=cmsbproxy.fnal.gov[131.225.205.133] server=cmsfrontier4.cern.ch) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )
----- End Fatal Exception -------------------------------------------------

**Comment by davidlange6** [comment]
Hi @mtosi - that should have been a transient failure to contact the conditions database. Try again, or perhaps try a different node.

**Comment by mtosi** [comment]
I see, I'm trying ..
thanks

**Comment by mtosi** [comment]
I'm still not be able to run neither 1330 nor 1306 workflows,
because of the issue w/ frontier, I guess [1]
so, I have to wait for having a working workflow for debugging :(

sorry for the inconvinience

[1]
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
A std::exception was thrown.
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 759 on chan 1 failed at Thu Mar  2 20:27:22 2017: -8 [fn-htclient.c:438]: server error (HTTP/1.1 503 Service Unavailable) proxy=cmsbproxy.fnal.gov[131.225.205.134] server=cmsfrontier4.cern.ch) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )

**Comment by davidlange6** [comment]
Yep. Everyone is stuck

Cheers,
David


On 2 Mar 2017, at 21:32, mia tosi <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm still not be able to run neither 1330 nor 1306 workflows,
because of the issue w/ frontier, I guess [1]
so, I have to wait for having a working workflow for debugging :(

sorry for the inconvinience

[1]
An exception of category 'StdException' occurred while
[0] Constructing the EventProcessor
[1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
A std::exception was thrown.
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 759 on chan 1 failed at Thu Mar 2 20:27:22 2017: -8 [fn-htclient.c:438]: server error (HTTP/1.1 503 Service Unavailable) proxy=cmsbproxy.fnal.gov<http://cmsbproxy.fnal.gov>[131.225.205.134] server=cmsfrontier4.cern.ch<http://cmsfrontier4.cern.ch>) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )

**Comment by Martin-Grunewald** [comment]
@mtosi 
Either fix or close this PR

**Comment by mtosi** [comment]
sorry the delay, but the issue w/ frontier and the weekend prevented to fix it sooner

there was a bug in the original PV monitoring code,
which is fixed, now

hope this PR is fine, now

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
:(
looking at the log I see [1]
I'm confused, it should be related to strip AlCa workflow
and I'm not sure how I touched it

the `validation_step` is `validationNoHLT`,
and it is defined in [Configuration/StandardSequences/python/Validation_cff.py](https://github.com/mtosi/cmssw/blob/2d33991e5e75ba013c222317b68259eb9a3f9802/Configuration/StandardSequences/python/Validation_cff.py#L46) as 
validationNoHLT = cms.Sequence(
                               genvalid_all
                               *globaldigisanalyze
                               *globalhitsanalyze
                               *globalrechitsanalyze
                               *globalValidation)

to be noticed that the standard sequence `validation` is simply the above one plus the `hltvalidation`
validation = cms.Sequence(validationNoHLT
                         *hltvalidation)

does it mean that strip AlCa workflow depends on hltvalidation sequence ?
or simply, I'm missing something

any help is really really welcome !
thanks and sorry for this "mess" :(
[1]
----- Begin Fatal Exception 15-Mar-2017 23:51:09 CET-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'validation_step'
   [2] Calling method for module SiStripMonitorCondData/'condDataValidation'
Exception Message:
No data of type "SiStripLorentzAngle" with label "" in record "SiStripLorentzAngleRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------

**Comment by mtosi** [comment]
dumping the whole config, I find that indeed the "offending" module pops up from this chain

process.validationNoHLT = cms.Sequence( .. + process.globalValidation)
process.globalValidation = cms.Sequence( .. + process.trackerRecHitsValidation + .. )
process.trackerRecHitsValidation = cms.Sequence( .. + process.condDataValidation)
process.condDataValidation = cms.EDAnalyzer("SiStripMonitorCondData"

I'm really confused :(

**Comment by mmusich** [comment]
ciao @mtosi, are you sure this piece of code was run before? Looks new to me. 
Also in the output of say wf. n 25.0 there are lots of plots I never seen before in PR tests [example](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17667/18463/runTheMatrix-results/25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/CumulativeSummary_NoiseFromCondDB__TEC__side__1__wheel__1.png).
In any case the error you report looks like the configuration of the `SiStripMonitorCondData` module is wrong. The Strip Lorentz angle conditions comes in two flavours (`peak` and `deconvolution`), there is no such thing as `SiStripLorentzAngle` with label ""  (i.e. empty) in Global Tag. 
You can easily convince yourself by checking the 90x `auto:run1_mc` Global Tag [1]:

```
$ conddb list 90X_mcRun1_realistic_v4 | grep SiStripLorentzAngleRcd
[2017-03-16 09:49:52,109] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
SiStripLorentzAngleRcd                                  deconvolution                                    SiStripLorentzAngleDeco_StartUp_31X_v2  
```

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Configuration/AlCa/python/autoCond.py#L7

**Comment by slava77** [comment]
what's happening in the test directory?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17667/18463/runTheMatrix-results/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/

baseline looks clean
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_9_1_X_2017-03-15-1100/slc6_amd64_gcc530/-GenuineIntel/matrix-results/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
I started from scratch, by using one recent IB (CMSSW_9_0_X_2017-03-17-1100)
and I copied by hand only files I want to update
and then I ran `runTheMatrix.py -l 9.0`

I still have this issue w/ `condDataValidation`

but any of the files I changed/updated modify have `condDataValidation`
I check by doing
grep -r condDataValidation *
and I find only
`Validation/Configuration/python/ValidationHI_cff.py:validationHI.remove(condDataValidation)`

this issue seems to be triggered by my changes in 
`Configuration/PyReleaseValidation/python/relval_steps.py` :(

I have to postpone the debugging to Monday, I'm afraid :(

**Comment by silviodonato** [comment]
please test

**Comment by mtosi** [comment]
I think the error in the log of step4 is due to the usage of the standard HARVESTING step, instead of the one w/o HLT validation harvesting and dqm harvesting
this should be fixed by my last commit https://github.com/cms-sw/cmssw/pull/17667/commits/0653acba857b37e215123152cab1fc2ceedade8d

local test gives me no error neither on workflow 9.0 nor on 25.0

cross the fingers

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
good, please remember to fix (rebase) #17693

**Comment by mtosi** [comment]
I'm really sorry if it took so long
it would be great if it can be integrated in the upcoming 900
thanks

**Comment by fabozzi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by perrotta** [comment]
+1
(Mostly DQM, it only touches Reco through Validation)

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
error still
```
----- Begin Fatal Exception 24-Mar-2017 21:18:19 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 3 event: 101
   [1] Running path 'prevalidation_step'
   [2] Prefetching for module PrimaryVertexAnalyzer4PUSlimmed/'hltPVanalysis'
   [3] Calling method for module VertexAssociatorByPositionAndTracksProducer/'v\
ertexAssociatorByPositionAndTracks4pixelTracks'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::AssociationMap<edm::OneToManyWithQualityGeneric<std::vec\
tor<TrackingParticle>,edm::View<reco::Track>,double,unsigned int,edm::RefProd<s\
td::vector<TrackingParticle> >,edm::RefToBaseProd<reco::Track>,edm::Ref<std::ve\
ctor<TrackingParticle>,TrackingParticle,edm::refhelper::FindUsingAdvance<std::v\
ector<TrackingParticle>,TrackingParticle> >,edm::RefToBase<reco::Track> > >
Looking for module label: tpToHLTpixelTrackAssociation
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exc\
eption,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSe\
t in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
-1

**Comment by Martin-Grunewald** [comment]
@mtosi 
either update or close this PR!

**Comment by davidlange6** [comment]
for 91x

**Comment by mtosi** [comment]
PR for 91x is already done, and --finally-- it is almost ready to be merged
only this morning I had the chance of updating this branch (in order to be
in synch w/ the 91x PR)
I'm still running both runTheMatrix and ./runAll all
I was going to update this branch
ok, I'll open a new PR

 mia

**Pull request closed without merging**
