### PR TITLE
Phase2-hgx295A Small correction to on HGCal validation code and remove several obsolete scripts in Geometry/CaloTopology and Validation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Small correction to on HGCal validation code and remove several obsolete scripts in Geometry/CaloTopology and Validation

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild please test with #36021

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
