### PR TITLE
Improve various Patatrack Kernels

### PR DESCRIPTION
**Pull request by VinInn**
Simplify and improve the logic of various Kernels.
Some maths have been sync with CPU version.
Fixed and improved the statistics collection and printing (off by default).

Technical.
No regression observed: math has changed so some regression cannot be excluded (even in CPU wf).

### CODE REVIEW

**Comment by VinInn** [comment]
enable gpu

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
Tried to reproduce runTheMatrix crashes by itself though

```
[innocent@patatrack02 matrix]$ runTheMatrix.py -l 10824.502
processing relval_standard
processing relval_highstats
processing relval_pileup
processing relval_generator
processing relval_extendedgen
processing relval_production
processing relval_ged
ignoring relval_upgrade from default matrix
ignoring relval_cleanedupgrade from default matrix
ignoring relval_gpu from default matrix
processing relval_2017
processing relval_2026
ignoring relval_identity from default matrix
processing relval_machine
processing relval_premix
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02701/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-10-04-2300/bin/slc7_amd64_gcc900/runTheMatrix.py", line 596, in <module>
    ret = runSelected(opt)
  File "/cvmfs/cms-ib.cern.ch/nweek-02701/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_X_2021-10-04-2300/bin/slc7_amd64_gcc900/runTheMatrix.py", line 31, in runSelected
    if len(undefSet)>0: raise ValueError('Undefined workflows: '+', '.join(map(str,list(undefSet))))
ValueError: Undefined workflows: 10824.502
[innocent@patatrack02 matrix]$ echo $CMSS
CMSSW_BASE                CMSSW_DATA_PATH           CMSSW_FULL_RELEASE_BASE   CMSSW_FWLITE_INCLUDE_PATH CMSSW_GIT_HASH            CMSSW_RELEASE_BASE        CMSSW_SEARCH_PATH         CMSSW_VERSION
[innocent@patatrack02 matrix]$ echo $CMSSW_BASE/
/home/innocent/FixClus/CMSSW_12_1_X_2021-10-05-1100/
```

**Comment by VinInn** [comment]
ok. reproduced on MC using a hlt menu of my own...
Will investigate

**Comment by VinInn** [comment]
uhhh...
do not really understand I was sure I did  "checkdeps -a".
anyhow. once done and compiled these three additional packages
```
Checking out these packages: 3
CondCore/SiPixelPlugins (header)
CondCore/Utilities (header)
CondTools/SiPixel (header)
```
the error is gone...

now testing in a fresh release area....

**Comment by VinInn** [comment]
do not understand how the gpu only was producing good clusters and tracks (in sync with CPU!) while transferring to CPU causes havoc...
anyhow rolled back changes

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * changes in AlCa packages are minimal
 * Jenkins tests pass, diffs in CPU wf are in MsgLogger only and for the GPU it is known that tests are not reproducible

**Comment by VinInn** [comment]
as said do nort exclude small regressions due to the change in fp computation

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
btw: I cannot access the histograms as I get
image

**Comment by tvami** [comment]
This is the error msg it fails with
```
----- Begin Fatal Exception 15-Oct-2021 18:52:41 UTC-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_DIGI_L1_DIGI2RAW_HLT.py
Exception Message:
 unknown python problem occurred.
RuntimeError: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
```

**Comment by slava77** [comment]
> Failed Tests: RelVals-GPU

> May I understand how removing a character in a comment make relval to fails?

there was a switch in 10-14-xxxx  IB from 2018 workflows  to 2021 workflows cms-sw/cms-bot#1648
```diff
- PR_TEST_MATRIX_EXTRAS_GPU=10824.502,10824.512,10824.522
+ PR_TEST_MATRIX_EXTRAS_GPU=11634.506,11634.512,11634.522
```

the related discussion is in #35624

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by slava77** [comment]
> @cmsbuild , please test with #35722

but IIUC, there will be no baseline still.
We need the results in the IB artifacts first.

**Comment by tvami** [comment]
@cmsbuild , please test
 * now it should be fine with the latest IB, right?

**Pull request closed without merging**
