### PR TITLE
address high-pt efficiency drop in EB EG objects - fix hardcoding

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Backport from 11_3_X to fix the efficiency drop in the L1 EGamma reconstruction phase-2, caused by hit saturation.

#### PR validation:

This PR was already validated for 11_3_X and does not interfere with other files.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/32697/
Backport needed by EGamma group @Sam-Harper

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by cecilecaillol** [comment]
I have just fixed the compilation error and checked everything is ok in the new commit, sorry about that!

**Comment by silviodonato** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
