### PR TITLE
Step 7: Simulation Clang tidy code-checks-all 

### PR DESCRIPTION
**Pull request by ianna**
* Split #20511 as suggested by @civanch here #20511 (comment)

Step 7. SimCalorimetry

* This PR is based on https://github.com/cms-sw/cmssw/pull/20531, #20530, #20529, #20528, #20527, #20525, #20524, #20514 
It will be rebased if needed after they are subsequently merged.

@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
Note, https://github.com/cms-sw/cmssw/pull/20530 relval 10042 test has failed previously, but it passed fine here.

**Comment by davidlange6** [comment]
hi @civanch - please object to merging this PR in the next hours, It looks straightforward.

**Comment by civanch** [comment]
+1

**Pull request closed without merging**
