### PR TITLE
UnHardWire Plugins for HLT 74X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
UnHardWire Plugins for HLT 74X

This PR also contains #7698 #8367 and content of #8378 (8378 itself conflicted with 7698),
plus the required HLT modifications.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by cvuosalo** [comment]
@Martin-Grunewald:

Jenkins alternative-comparisons for workflow 1306.0_SingleMuPt1_UP15+SingleMuPt1 show some small [differences] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-03-18-2300+8390/3622/alternative-comparisons/1306.0-result.ps.gz) for HLT, the biggest shown below. Are these differences expected for this PR, or do they indicate a problem? #8393 shows these same differences.


1306_select

**Comment by fwyzard** [comment]
I don't know how to read this plot, but this PR does include few changes to the HLT paths - mostly the removal of HLT_Ele35_eta2p1_WP85_Gsf_v1 from the menu.

**Comment by cvuosalo** [comment]
+1

For #8390 897e46181766686ed171c6a75e9fbb423690918d

Fixes for the HLT configuration.

The code changes are satisfactory, and Jenkins test [results] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8390/3610/summary.html) against baseline CMSSW_7_4_X_2015-03-18-2300 show no significant differences, except for minor differences in some HLT plots (see above) that are expected as a result of this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
