### PR TITLE
Fix compilation issue with clang

### PR DESCRIPTION
**Pull request by VinInn**
see https://github.com/cms-sw/cmssw/pull/44834#discussion_r1587271339

### CODE REVIEW

**Comment by VinInn** [comment]
@cms-bot please test

**Comment by smuzaffar** [comment]
@cmsbuild, please test

> cms-bot please test

cms-bot is wrong user :-)

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

lets test for clang IB too

**Comment by VinInn** [comment]
@cmsbuild  please test

**Comment by smuzaffar** [comment]
clang build and tests look good now.

**Comment by mandrenguyen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
