### PR TITLE
HLT migration to 10_0_3 template (10_0_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT migration to 10_0_3 template (10_0_X)
Based on CMSSW_10_0_3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald this PR is effectively changing the event content for step2, was this expected?

**Comment by Martin-Grunewald** [comment]
Not explicitly (ie, no change to HLT-related keep sequences in the EventContent definition); at most
indirectly due to changes in the menu (more or less instances of the same persistent classes).

**Pull request merged**
