### PR TITLE
Phase2-hgx196 Handle the current issues of validation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct small bugs in HGCalSimHitValidation, HGCalHitStudy and HGCalHitCalibration codes

#### PR validation:

Tested with standard runTheMatrix

#### if this PR is a backport please specify the original PR:

No back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
@bsunanda Your PR is only adding 4 plots on Workflows 
27434.0 
29034.0 
Is this intended?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-15-1100+498e57/31702/dqm-histo-comparison-summary.html

**Comment by bsunanda** [comment]
Yes. The issues in the validation code were discussed in the DPG meeting. The issues were small: change of silicon thickness in one and empty histograms in some of the standalone code. So it will change minimally in the output - some plots will be filled up in the calibration part and that is all.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
