### PR TITLE
Moving condition DB tools to python3

### PR DESCRIPTION
**Pull request by ggovi**
Moving to python3:
- conddb tools
- conddb_version_mgr
- o2o tools

Local integration tests are ok.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg =CondCore,CondTools,Alignment

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * addpkg =CondCore, CondTools, Alignment/OfflineValidation

**Comment by mmusich** [comment]
removing from the time being `Alignment/TrackerAlignment` test as it is still broken (see https://github.com/cms-sw/cmssw/issues/34223)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
