### PR TITLE
MTD reconstruction and validation: validation and debugging information for track - MTD matching studies

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is a follow-up of #42178 , it adds a few histograms to MTD validation and improves several debugging printouts, to analyse in detail events where the ```TrackExtenderWithMTD``` fails to find MTD hits, that are found in a cone around a simple track extrapolation to BTL surface.

#### PR validation:

Code compiles, runs, and provide detailed debugging printout being actively use for investigation. A few added prolts are shown in https://indico.cern.ch/event/1306288/contributions/5493532/attachments/2683819/4656070/MTDDPG-BTLmatching_20230714.pdf slide 13.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR adds few more histograms for MTD, and update debugging printout as mention in the PR description. No change is expected on simulation and reconstruction.

**Comment by fabiocos** [comment]
@cms-sw/reconstruction-l2 could you please comment or sign? The changes in the reco area are quite trivial, and not affecting regular processing

**Comment by clacaputo** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
