### PR TITLE
(Partial) Cleaning of unused CommonTools/CandAlgos classes

### PR DESCRIPTION
**Pull request by davidlange6**
Much of CommonTools/CandAlgos appears to be unused and unchanged in many years. This pr is a partial removal of those things. If accepted, I would then reevaluate remaining components (as tools to find dependencies deal more easily with an IB than with local changes)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by jpata** [comment]
It looks like at least some modules are used in private codes, including CMSDAS exercises: https://github.com/search?l=Python&q=CandViewShallowCloneProducer&type=Code

Is there a particular/strong reason to remove these modules?

**Comment by davidlange6** [comment]
Trying to avoid spending time (and the time of newcomers) tracing through unused code when looking at use cases for code modernization. Maybe you can add some tests for these if they are indeed used and thus needed to be kept around?

**Comment by jpata** [comment]
We could perhaps replace the test file in this package with something like the following and run it as part of `scram b runtests`:
```python
#This file is meant to test legacy modules that may still be used by some analyses
from FWCore.ParameterSet.Config import *

process = Process("CandSelectorTest")

process.maxEvents = untracked.PSet( input = untracked.int32(10) )

process.source = Source("PoolSource",
  fileNames = untracked.vstring("root://cms-xrd-global.cern.ch//store/relval/CMSSW_12_2_0_pre2/RelValZMM_14/GEN-SIM-RECO/122X_mcRun4_realistic_v1_2026D77noPU-v1/2580000/0b2a54b1-7710-4e3f-9130-85cdc3d07ced.root")
)

process.genmuons = EDFilter("CandViewShallowCloneProducer",
  src = InputTag("genParticles"),
  cut = string("abs(pdgId)==13")
)

process.Ztomumu = EDProducer("CandViewCombiner",
    decay = string("genmuons@+ genmuons@-"),
    cut = string("0.0 < mass < 200.0")
)

process.out = OutputModule("PoolOutputModule",
    fileName = untracked.string("test2.root"),
    outputCommands = untracked.vstring(
        'drop *',
        'keep *_Ztomumu_*_*'
    )
)

task = Task(process.genmuons,process.Ztomumu)
process.path = Path(task)
process.endpath = EndPath(process.out)
```

to test the modules which seem to be referred to in various private codes on github. On the other hand, maybe it's fine also to just remove them to guide future users away from legacy functionality. Legacy users can use an older release, and in case of need, request this functionality to be restored.

**Comment by slava77** [comment]
why would `CandViewShallowCloneProducer` be considered legacy?
Is there an alternative that does the same?

**Comment by jpata** [comment]
The only real-life uses I've seen so far are still several years old and look like CMSDAS exercises on how to select a particular particle from an EDM collection, or private ntuplizer configurations. I understand nowadays this is not the suggested way to do analysis.

(side note: when I first got involved in CMS ~10 years ago, I was indeed confused myself and thought that every analysis must be written using these EDM modules as building blocks. Only later did I find out that in practice everyone writes their own ntuplizer)

**Comment by davidlange6** [comment]
What should be the path forward? I did the GitHub search exercise for other modules in this PR without finding users of them (unless I missed a module in my check, only one had one user from 2013). 

Should I adjust the PR to keep CandView* and add the unit test proposed by @jpata ?

**Comment by jpata** [comment]
From the discussion with Slava I understand this should be OK. Perhaps it makes sense to change the test file to reMINIAOD inputs, to make sure it's available in the future.


```python
#This file is meant to test legacy modules that may still be used by some analyses
from FWCore.ParameterSet.Config import *

process = Process("CandSelectorTest")

process.maxEvents = untracked.PSet( input = untracked.int32(10) )

process.source = Source("PoolSource",
  fileNames = untracked.vstring("/store/data/Run2018C/JetHT/MINIAOD/UL2018_MiniAODv2-v1/00000/9F030B27-DBB0-EE46-A8FB-64FE0C417EE9.root")
)

process.genmuons = EDFilter("CandViewShallowCloneProducer",
  src = InputTag("packedPFCandidates"),
  cut = string("abs(pdgId)==13")
)

process.Ztomumu = EDProducer("CandViewCombiner",
    decay = string("genmuons@+ genmuons@-"),
    cut = string("0.0 < mass < 200.0")
)

process.out = OutputModule("PoolOutputModule",
    fileName = untracked.string("test.root"),
    outputCommands = untracked.vstring(
        'drop *',
        'keep *_Ztomumu_*_*'
    )
)

task = Task(process.genmuons,process.Ztomumu)
process.path = Path(task)
process.endpath = EndPath(process.out)

```

**Comment by jpata** [comment]
kind ping on this

**Comment by davidlange6** [comment]
please test

**Comment by jpata** [comment]
these failures do not look related to the PR

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- removes some unused/outdated code
- implements a test for CandViewCombiner, CandViewShallowCloneProducer that seem to be used in some DAS exercises (the test relies on the file `/store/data/Run2018C/JetHT/MINIAOD/UL2018_MiniAODv2-v1/00000/9F030B27-DBB0-EE46-A8FB-64FE0C417EE9.root`)

**Comment by qliphy** [comment]
+1

**Pull request merged**
