### PR TITLE
Bug fix FormulaEvaluator

### PR DESCRIPTION
**Pull request by Dr15Jones**
Bug fixes for new FormulaEvaluator back ported from CMSSW_7_6. These are needed before we can use the new class.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This code isn't being used in CMSSW_7_4 yet so it is safe to incorporate.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11723	 30ac3b4
- based on post-merge diff between CMSSW_7_4_X_2015-10-12-2300+#11723 and CMSSW_7_6_X_2015-10-11-2300, the parts of CommonTools/Utils related to the formula evaluator are now the same
- jenkins tests pass (compilation and unit tests); no changes can appear in running workflows since this code not being used yet in the release

**Comment by slava77** [comment]
@davidlange6 
I think that this PR can be closed
Even if we do something with 2015, it will be 76X.

**Pull request closed without merging**
