### PR TITLE
Revert "Merge pull request #26953 from chayanit/String106X"

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This reverts commit 5b62bf9f89f2df1e899a0d5c813efe6c1c5b35e5, reversing changes made to 480b0901e3dffaf158b6cd9a9b024bbe720a86dc.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by fabiocos** [comment]
@kpedro88 @prebello @zhenhu @chayanit caching files at CERN within a couple of IBs is not a big problem, the issue is with samples not yet produced, and there are a few not yet in DAS, at least as of this morning. Does PdmV know how many of them are missing?

**Comment by fabiocos** [comment]
@kpedro88 @prebello @zhenhu @chayanit as I haven't seen a follow up to this discussion, I temporarily revert the update to avoid having 57 broken workflows. We need to clarify how to move forward and get the new samples

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by zhenhu** [comment]
> @kpedro88 @prebello @zhenhu @chayanit as I haven't seen a follow up to this discussion, I temporarily revert the update to avoid having 57 broken workflows. We need to clarify how to move forward and get the new samples

Hi Fabio, a new PR will be created later with newly added strings for pLHE workflows, to avoid sharing strings with other workflows.

**Pull request merged**
