### PR TITLE
adding decay file for longlived stable - 71x

### PR DESCRIPTION
**Pull request by alberto-sanchez**
back port of  PR-13661 to 71x

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@degano - could you back port the data files from 81x to 71x that correspond to this PR? Thanks!
@smuzaffar

**Comment by degano** [comment]
@davidlange6 Sure, I'm into it!

**Comment by degano** [comment]
@davidlange6 The PR is ready @ cms-sw/cmsdist#2218

**Pull request closed without merging**
