### PR TITLE
 backporting of updated online BS fake client configuration 

### PR DESCRIPTION
**Pull request by gennai**
#### PR description:

updated configurations and added a 48 seconds latency when running in live mode

#### PR validation:

Just run the client scripts with unitTests=True

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backporting of #31965 needed for next MWGR

### CODE REVIEW

**Comment by gennai** [comment]
@boudoul @francescobrivio @ggovi @amassiro

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Tested sucessfully at Online DQM playback

**Comment by gennai** [comment]
Hi, can you tell me which run did you use? In principle I should see a new payload appear unless you used unitTest=True
 option

**Comment by jfernan2** [comment]
Hi @gennai 
we used  337881 in DQM Online playback
We can test with other run. We used default settings, so no UnitTest

**Comment by silviodonato** [comment]
+1

**Pull request merged**
