### PR TITLE
OnlineDQM : Remove unneeded histograms from uGMT

### PR DESCRIPTION
**Pull request by stahlleiton**
Solves the JIRA Ticket:  https://its.cern.ch/jira/browse/CMSLITDPG-322

Description:

- Remove some muon AtVtx plots and rename the BXvsProcessor plots used in the uGMT L1T Online DQM workspace.

- Add a boolean flag to create or not the muon AtVtx plots for the Intermediate muons in the uGMT L1T Online DQM workspace.

### CODE REVIEW

**Comment by thomreis** [comment]
Hi @jfernan2 could you launch the tests for this PR please? The backport is already tested and deployed at P5.

**Comment by dmitrijus** [comment]
please test

**Comment by thomreis** [comment]
Hi @dmitrijus ,
This PR removes unneeded MEs. How can the histogram memory increase?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
the dqm script (or cmsbots interoperation of its output) seems to have a gitter at the 1kb level. if this PR really changes only online dqm, then 0 change is expected..

**Comment by davidlange6** [comment]
merge

**Pull request merged**
