### PR TITLE
HGCal - use calibrated energy for candidates from neutral hadrons

### PR DESCRIPTION
**Pull request by felicepantaleo**
This PR fixes the energy association to a PFCandidate coming from a neutral hadron. 
Previously the non-calibrated energy was used. 

@ahinzmann @rovere

### CODE REVIEW

**Comment by felicepantaleo** [comment]
type bugfix

**Comment by felicepantaleo** [comment]
attaching presentation by Irene Zoi and Andreas Hinzmann showing negligible impact on jet substructure.
[NeutralHadronsCalibration.pdf](https://github.com/cms-sw/cmssw/files/1685607/NeutralHadronsCalibration.pdf)

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
assign upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22071	93c9c4d
- the change is as described and affects only RecoParticleFlow/PFSimProducer/plugins/SimPFProducer.cc
- jenkins tests pass and comparisons with the baseline show differences only in 2023 workflows, as expected.

e.g. in 20034 there is a slight shift in neutral hadron momentum (while pf candidate eta is unchanged)
all_oldvsnew_ttbar14tev2023d17wf20034p0c_log10recopfcandidates_particleflow__reco_obj_pt74

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@fabiocos 
please clarify if this can be merged soon.
Thank you.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
