### PR TITLE
Extended 2017 Plan1 Scenario Scripts

### PR DESCRIPTION
**Pull request by ianna**
* Add scripts to create 2017 Plan 1 scenario payloads

### CODE REVIEW

**Comment by ianna** [comment]
hold

wait until https://github.com/cms-sw/cmssw/pull/17581 is merged, then rebase

**Comment by slava77** [comment]
-1

to be rebased/updated, at which point it should not need reco signature.

160K line file CondTools/Geometry/test/geSingleBigFile.xml  should probably not be in the release if it's not really human readable and if it's auto-generated and becomes obsolete quickly.

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@bsunanda and @kpedro88 - it looks like Plan 1 reco geometry is identical to Plan 0. Is there some setting missing in Plan1Reco python configuration or the phi slice in the display should be different (currently at X plane)? Thanks.
screenshot 2017-02-22 10 55 33
screenshot 2017-02-22 10 55 44

**Comment by bsunanda** [comment]
@ianna Please look at the # of valid detId;s in plan 0 and plan 1. There will be more in plan 1. Unless you go to iphi=63..68 in HE+, you will not see any difference between plan 0 and plan 1. It is better to be seen in list of valid DetId's for HE

**Comment by kpedro88** [comment]
@bsunanda isn't that for the simulation geometry? I thought the reco geometry should indeed be identical for Plan0 and Plan1 (we merge the Plan1 hits to have the same depth segmentation as Plan0).

**Comment by ianna** [comment]
@bsunanda - could you, please, run your tests on the tags from DB:
```
XMLFILE_Geometry_90YV10_Extended2017Plan1_mc
HCALRECO_Geometry_90YV10
HCALParameters_Geometry_90YV10
```
you can pick them up as follows:

```
process.GlobalTag.toGet = cms.VPSet( cms.PSet( record = cms.string('GeometryFileRcd'),
                                                                           tag = cms.string('XMLFILE_Geometry_90YV10_Extended2017Plan1_mc')
                                                                          ),
                                                            cms.PSet( record = cms.string('PHcalRcd'),
                                                                            tag = cms.string('HCALRECO_Geometry_90YV10')
                                                                         ),
                                                            cms.PSet( record = cms.string('HcalParametersRcd'),
                                                                            tag = cms.string('HCALParameters_Geometry_90YV10')
                                                                         )
                                                           )
```
Thanks.

**Comment by ianna** [comment]
@bsunanda and @kpedro88 - ok, HE reco geometry is not identical:
screenshot 2017-02-22 18 14 34

**Comment by ianna** [comment]
@bsunanda and @kpedro88 - unfortunately, here is what I get and it does not look right. Green color applied to ieta -16 and blue to ieta 16. It could be just visualization issue...
screenshot 2017-02-22 18 28 57

**Comment by kpedro88** [comment]
That is quite strange-looking... @bsunanda, can this be caused by changing depth indices?

**Comment by bsunanda** [comment]
I am getting this error message which I do not understand
TimeModule> 1 1 hpa HcalRecNumberingTester 6.55822
----- Begin Fatal Exception 22-Feb-2017 21:04:47 CET-----------------------
An exception of category 'DDException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'p1'
   [2] Calling method for module HcalRecNumberingTester/'hpa'
   [3] Using EventSetup component HcalDDDRecConstantsESModule/'hcalDDDRecConstants' to make data HcalDDDRecConstants/'' in record HcalRecNumberingRecord
   [4] Using EventSetup component HcalParametersESModule/'hcalParameters' to make data HcalParameters/'' in record HcalParametersRcd
Exception Message:
DDVectorGetter: vectors are empty, cannot get array phioff
----- End Fatal Exception -------------------------------------------------

I do not get this error while running from xml.

**Comment by ianna** [comment]
@bsunanda - I think, I missed "connect" in the fragment:

```
process.GlobalTag.toGet = cms.VPSet(
        cms.PSet(record = cms.string("GeometryFileRcd"),
                 tag = cms.string("XMLFILE_Geometry_90YV10_Extended2017Plan1_mc"),
                 connect = cms.string("frontier://FrontierProd/CMS_COND_GEOMETRY")
                 )
        )
```

**Comment by ianna** [comment]
@ggovi - ping

**Comment by ianna** [comment]
@ggovi - please, review this PR.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
