### PR TITLE
Adding 1x1 HF trigger primitives in Hcal Geometry tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v6) as [80X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v6/80X_mcRun2_design_v5): 
  - updated HcalParameters and Sim geometry to handle 1x1 HF TPs
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v4) as [80X_mcRun2cosmics_startup_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v4/80X_mcRun2cosmics_startup_peak_v5): 
  - updated HcalParameters and Sim geometry to handle 1x1 HF TPs
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v6) as [80X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v6/80X_mcRun2_asymptotic_v5): 
  - updated HcalParameters and Sim geometry to handle 1x1 HF TPs
- **RunII Startup scenario** : [80X_mcRun2_startup_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v6) as [80X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v6/80X_mcRun2_startup_v5): 
  - updated HcalParameters and Sim geometry to handle 1x1 HF TPs
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v5) as [80X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v5/80X_mcRun2_HeavyIon_v4): 
  - updated HcalParameters and Sim geometry to handle 1x1 HF TPs
## RunII data
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v6) as [80X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v6/80X_dataRun2_HLTHI_frozen_v3): 
  - updated HcalParameters to handle 1x1 HF TPs
  - updated Hcal e-maps (unlabeled and full) for unpacking of uTCA FEDs in HBHE
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v3) as [80X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v3/80X_dataRun2_HLT_relval_v1): 
  - updated HcalParameters to handle 1x1 HF TPs
  - udated Hcal e-maps (unlabeled and full) for unpacking of uTCA FEDs in HBHE
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v6) as [80X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v6/80X_dataRun2_HLT_frozen_v3): 
  - updated HcalParameters to handle 1x1 HF TPs
  - udated Hcal e-maps (unlabeled and full) for unpacking of uTCA FEDs in HBHE
- **RunII Offline processing** : [80X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v8) as [80X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v8/80X_dataRun2_v6): 
  - updated HcalParameters to handle 1x1 HF TPs
- **RunII Offline relval processing** : [80X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v3) as [80X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v3/80X_dataRun2_relval_v1): 
  - updated HcalParameters to handle 1x1 HF TPs

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@davidlange6 these are the GTs we've been promising during the Operations meeting today
@hengne, please notice that I had to update the `autoCond` file. The phase-I didn't receive further updates (waiting for #13516 to be merged)

**Comment by davidlange6** [comment]
this probably needs to use a more recent IB. (as Slava already noticed jenkins is behind)

#5  0x00007f24fac06796 in CaloTPGTranscoderULUT::hcalCompress(HcalTrigTowerDetId const&, unsigned int, bool) const () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libCalibCalorimetryCaloTPG.so
#6  0x00007f24fac0052e in HcalTPGCompressor::compress(IntegerCaloSamples const&, std::vector<bool, std::allocator<bool> > const&, HcalTriggerPrimitiveDigi&) const () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libCalibFormatsCaloTPG.so
#7  0x00007f24c3c4afaf in HcalTriggerPrimitiveAlgo::analyzeHFV1(IntegerCaloSamples const&, HcalTriggerPrimitiveDigi&, int, HcalFeatureBit const*) () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libSimCalorimetryHcalTrigPrimAlgos.so
#8  0x00007f24c3c4e144 in HcalTriggerPrimitiveAlgo::run(HcalTPGCoder const*, HcalTPGCompressor const*, edm::SortedCollection<HBHEDataFrame, edm::StrictWeakOrdering<HBHEDataFrame> > const&, edm::SortedCollection<HFDataFrame, edm::StrictWeakOrdering<HFDataFrame> > const&, edm::SortedCollection<HcalTriggerPrimitiveDigi, edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> >&, HcalTrigTowerGeometry const*, float, HcalFeatureBit const*) () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libSimCalorimetryHcalTrigPrimAlgos.so
#9  0x00007f24c366c8a2 in HcalTrigPrimDigiProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/pluginSimCalorimetryHcalTrigPrimProducers.so
#10 0x00007f2512bdd9c8 in edm::EDProducer::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#11 0x00007f2512ccd69f in edm::WorkerT<edm::EDProducer>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/2016-10/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-28-0000/lib/slc6_amd64_gcc493/libFWCoreFramework.so

**Comment by mmusich** [comment]
@davidlange6 thanks, shall we wait tonight for re-launching the tests?

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
seems i was wrong. @kpedro88 @ianna @bsunanda, please help

**Comment by davidlange6** [comment]
ah - seems related to #13252 which was just fixed yesterday:(

**Comment by davidlange6** [comment]
@mmusich - what IOV is given to the new geometry in the data GTs? It seems we are using it for run 1 data workflows (which is not desired)

**Comment by mmusich** [comment]
@davidlange6 indeed it is 1-inf. From @ianna's message here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2245.html it's not clear if this was not desired. In any case also 134.911 fails (Run2015D, i.e. Run2).

**Comment by abdoulline** [comment]
using this geometry on Run1/2015 data should be avoided somehow (one way 
or another)...

**Comment by mmusich** [comment]
Shall we just give for all the data GTs an IOV in the future, so that no existing data falls in it?

**Comment by mmusich** [comment]
@abdoulline can you suggest a suitable run number for the boundary? First run of MWGR-I? 
By the way the non -IOVed tag was queued as is.... 
screenshot 2016-03-04 10 11 20






Some more advance understanding would be appreciated.

**Comment by abdoulline** [comment]
The problem/dilemma is (possibly, to me) that
(1) kind of OK that the job crashes when mismatch of conditions
(Run 1 / 2015) with geometry (2016) occurs
(2) bad that RelVals (jenkins) fail...
I'd (personally) suggest to assign 2016 IOV 263798[*] to this Geometry.

[*]
We have fixed  HcalLutMetadata _v1.01_hlt at this point...

**Comment by mmusich** [comment]
@davidlange6 @abdoulline @ianna I prepared a tag with an IOV at run 263798. 

https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/HCALParameters_Geometry_RunI_RunII_81YV1

redoing the GTs...

**Comment by mmusich** [comment]
to be sure, I'll use this tag as well for the next HLT, Express and Prompt GTs for the next data-taking period. I am assuming it will run fine.

**Comment by mmusich** [comment]
For MC my understanding is that this work because GEN-SIM are re-done in the PR test, right? What happens when they are recycled from previous releases?

**Comment by davidlange6** [comment]
I do not think the pr tests redo gen-sim in all workflows. I can run a small test to be sure

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by abdoulline** [comment]
(sryy for non-instant answer, I've been at a working meeting)
No, it shouln't be related GEN-SIM.
I presume MC is using right HcalLutMetadata tag  HcalLutMetadata _v4.00_mc

    Salavat

**Comment by mmusich** [comment]
locally passing the tests:
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Mar  4 11:23:44 2016-date Fri Mar  4 11:18:17 2016; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Fri Mar  4 11:23:06 2016-date Fri Mar  4 11:18:18 2016; exit: 0 0
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Mar  4 11:25:06 2016-date Fri Mar  4 11:18:21 2016; exit: 0 0 0 0 0
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Mar  4 11:33:00 2016-date Fri Mar  4 11:18:26 2016; exit: 0 0 0 0 0
134.911_RunSinglePh2015D+RunSinglePh2015D+HLTDR2_25ns+RECODR2_25nsreHLT+HARVESTDR2_25nsreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Mar  4 11:42:27 2016-date Fri Mar  4 11:23:09 2016; exit: 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Fri Mar  4 11:35:38 2016-date Fri Mar  4 11:23:52 2016; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Fri Mar  4 11:34:14 2016-date Fri Mar  4 11:25:13 2016; exit: 0 0 0
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Mar  4 11:43:19 2016-date Fri Mar  4 11:33:05 2016; exit: 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Mar  4 11:45:51 2016-date Fri Mar  4 11:34:20 2016; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED  - time date Fri Mar  4 11:46:56 2016-date Fri Mar  4 11:35:40 2016; exit: 0 0 0 0 0 0 0
10 10 9 7 5 1 1 tests passed, 0 0 0 0 0 0 0 failed
```

**Comment by mmusich** [comment]
@abdoulline I confirm all MC workflows use the `HcalLutMetadata _v4.00_mc` tag.

**Comment by abdoulline** [comment]
Thank you for prompt (issue-resolving) action, Marco.

**Comment by davidlange6** [comment]
looks like the comparisons show no changes as expected.

**Comment by mmusich** [comment]
+1 
for the record

**Pull request merged**
