### PR TITLE
make gpu Pixel Cluster Charge Cut consistent with legacy cpu version

### PR DESCRIPTION
**Pull request by VinInn**
Trivial.

Small regression observed.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/35493

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35525	f3aa72d
- the code change is in line with the PR description. the update is now apparently consistent with the CPU version
https://github.com/cms-sw/cmssw/blob/a993d69542c44e0fe07a2d7f21376cba1e379541/RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc#L165
as discussed in https://hypernews.cern.ch/HyperNews/CMS/get/pixelOfflineSW/1587/2/1/1/1/1/1.html
- jenkins tests pass and comparisons with the baseline show no (relevant) differences: there are small differences in the pixel GPU wf 10824.502, which look more like a case of incomplete repeatability of the result rather than from the small change in the cut introduced by this PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
