### PR TITLE
Fix for the reconnect-each-run policy in CondDBESSource

### PR DESCRIPTION
**Pull request by ggovi**
The fix consists in reverting back the previous fix in PayloadProxy::reload

### CODE REVIEW

**Comment by ggovi** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@mmusich @franzoni to watch

**Comment by mmusich** [comment]
@diguida @ggovi thanks. Are 7.6.X and 8.0.X safe?

**Comment by diguida** [comment]
@mmusich seems so...

**Comment by mmusich** [comment]
am I misreading? https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/CondCore/CondDB/src/PayloadProxy.cc#L34 (looks like it has the same bug as 75X). Or is it handled in a deeper way?

**Comment by diguida** [comment]
@mmusich seems so = seems it is buggy!

**Comment by diguida** [comment]
PR coming...

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
Could someone summarize what changed since 74x to set off this "bug"?

**Comment by ggovi** [comment]
Hi David,
the package CondCore/CondDB (and the concerned function in particular) in 75X and 76X diverged from 74X for the introduction of the IOV sequence snapshot.
Here is the PR:
https://github.com/cms-sw/cmssw/pull/9124/
This is also contain the 'bad' fix which we are reverting here...

**Pull request merged**
