### PR TITLE
[10_3_X] Pythia8 photon flux

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

backport of https://github.com/cms-sw/cmssw/pull/43840

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

@hjbossi

### CODE REVIEW

**Comment by stahlleiton** [comment]
please test

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by stahlleiton** [comment]
Why did the test failed?

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
@rappoccio, @antoniovilela, @sextonkennedy, what does the error "Unable to find CMSSW IB for CMSSW_10_3_X" mean in the checks

**Pull request closed without merging**
