### PR TITLE
ECAL - Set correct CC tag labels for ECAL RecHit producer - 133x

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

While the ECAL uncalibrated RecHit producer is set up to use the timing calibrations and offsets from the `CC` labelled records in the GT for Run 3 and beyond (because the cross correlation timing algorithm is used in the time reconstruction), the RecHit producer has until now not picked the calibrations from the record with those labels. This mismatch in conditions used for the two producers is fixed with this PR.
The RecHit producer needs to use the conditions matching the reconstruction algorithm running in the uncalibrated REcHit producer.

In the online DQM the ratio timing is used and the record labels are explicitly set to be empty.

#### PR validation:

Passes the limited matrix tests.

Backport of #43795

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
type bugfix

**Comment by thomreis** [comment]
backport of #43795

**Comment by thomreis** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by thomreis** [comment]
Thanks for signing this PR @mandrenguyen . Can you please sign the master PR https://github.com/cms-sw/cmssw/pull/43795 as well?

**Comment by mandrenguyen** [comment]
@thomreis  It appears to me that I had also signed the PR to the master, but let me know if I'm hallucinating :-)

**Comment by thomreis** [comment]
> @thomreis It appears to me that I had also signed the PR to the master, but let me know if I'm hallucinating :-)

You did, but it my open tab for that PR had been outdated. Sorry about that.

**Comment by thomreis** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
