### PR TITLE
Update HLT to V3.6 (103X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update HLT to V3.6 (103X)
Based on CMSSW_10_3_X_2018-09-24-1100

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Dr15Jones** [comment]
@Martin-Grunewald should I review this code now or wait once you have released the hold?

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Please wait as an update commit is still to be done.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Please sign for addOnTests

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
