### PR TITLE
Fix saveTags() and abs() use in HLTEgammaL1TMatchFilterRegional (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix saveTags() and abs() use in HLTEgammaL1TMatchFilterRegional (93X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by Sam-Harper** [comment]
Many thanks Martin for this!

**Pull request merged**
