### PR TITLE
Jet ID update to the Run2017 prescription

### PR DESCRIPTION
**Pull request by knash**
Update of the jetID criterion to the Run2017 prescription (TIGHT operating point).
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017

The LOOSE operating point is no longer supported, so this PR would give a warning and switch to TIGHT.  

THIS PR only updates the PFJetIDSelectionFunctor.h and pfJetIDSelector_cfi.py defaults to define and select the "WINTER17" version.  In theory there are other files that reference these operating points 
(https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=WINTER16&type=) that this PR could also update, but I am not sure if this is appropriate.

The new prescription does not require the definition of a Charged EM Fraction (CEF) cut for the operating point here, so this has been taken out of the jetid definition.  The other options would be to keep it and set the CEF cut to at >=1 or set ignoreCut(indexCEF_).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
This code looks like being pure analysis code
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_10_1_X_2018-02-27-2300&_filestring=&_string=pfJetIDSelector

It does not affect reco production, and therefore I refrain from proposing code optimization, even though the two almost fully identically copy/pasted constructor could be better factorized, for the sake of avoiding possible future mistakes.

Was the change agreed with or notified to the analyses affected, or at least endorsed by JetMET POG?
(Adding @rappoccio @ahinzmann @jdolen , the Jet POG contacts, for confirmation)
Do you have any presentation that showed its effect?

**Comment by ahinzmann** [comment]
Hi! I would suggest to split into TIGHT and TIGHT_LEP_VETO as for the recommendation, including and excluding and including the electron/muon fraction cuts. It his way analyzers have the same options as we recommend on the TWiki.

**Comment by perrotta** [comment]
This PR now has conflicts with PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
Please fix them

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test
(With a new IB as baseline we will likely get rid of the differences in the reco tests, if due to the extra commits that were tested together)

**Comment by perrotta** [comment]
+1
- This is analysis code
- No effect expected on reco/miniAOD outputs, none observed

**Comment by perrotta** [comment]
@knash : do you plan a 94X backport for it?

**Comment by fabiocos** [comment]
@knash I assume this is first of all needed for the 2017 analysis, so I consider natural a backport to 94X, where such a work is supposed to happen.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by knash** [comment]
Hello, yes a 94X backport would make sense here

**Comment by knash** [comment]
sure, so this would just be merging with the 9_4_X branch instead of master?

**Comment by perrotta** [comment]
@knash, please make and submit an identical PR for 9_4_X

knash <notifications@github.com> ha scritto:

**Comment by arizzi** [comment]
it seems the backport to 94X wasn't made yet. Can you create it and link it here ?

**Comment by knash** [comment]
Hello,  I have created the backport here: https://github.com/cms-sw/cmssw/pull/22671

Thanks,
Kevin

**Pull request merged**
