### PR TITLE
Tau HLT: revised L2.5 isolation

### PR DESCRIPTION
**Pull request by rmanzoni**
Move from counting-based to ΣpT based isolation.
JIRA ticket with updated configuration will follow and be referenced here.

presentation to TSG
https://indico.cern.ch/event/492285/contribution/1/6/attachments/1222254/1787558/tsg_l2p5iso_3_2_2016.pdf

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
This would change the physics outcome. You'd need to have a (new) flag to decide which algorithm to use, with the default setting of the flag to use the old calculation.

**Comment by rmanzoni** [comment]
ok @Martin-Grunewald will do, sorry for forgetting this

**Comment by Martin-Grunewald** [comment]
Together with your requested HLT py config update (JIRA ticket), also request to flip the flag
value in the JIRA ticket.

**Comment by fwyzard** [comment]
Hi Martin, all,
we are not guaranteeing any kind of physics compatibility of the HLT in
8.0.x, so from my point of view this can go ahead without the extra
parameters.

.A

**Comment by Martin-Grunewald** [comment]
But we DQM and validate pre6 which may use new code with old config....

**Comment by fwyzard** [comment]
I thought this would already be late for pre6 ?
If it makes it for pre6, it would be nice to also have the accompanying
configuration changes.

.A

**Comment by Martin-Grunewald** [comment]
pre6 is fuzzy (not there yet, some outstanding prs, but should arrive before the weekend)

**Comment by rmanzoni** [comment]
that's not completely clear to me: shall I update the PR or not?

**Comment by Martin-Grunewald** [comment]
close the 76 PR. update the 80 PR.

**Comment by perrotta** [comment]
In this particular case, the algo currently in CMSSW is
-        if (dr2 >= m_isoCone2Min && dr2 <= m_isoCone2Max) iso += 1.;
and the filter rejects the event whenever iso > MaxTag = cms.double( 0. )

With the algo proposed in this PR
+        if (dr2 >= m_isoCone2Min && dr2 <= m_isoCone2Max) iso += (*tr)->pt();

Provided the old MaxTag remains "0." in the python config, then the result of the filter is exactly the same with either the new or the old code.

Therefore, even if the modified code is merged in CMSSW_8_0_0_pre6, the result of the filter will not change if MaxTag=0. The only difference will be for the modified config, which we will eventually merge in ConfDB following the expected jira ticket.

If @Martin-Grunewald agrees, I would keep this pull request untouched and I would try to merge it as quickly as possible.

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
OK, it is for a pre.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6
please also consider this for pre6.

**Comment by rmanzoni** [comment]
JIRA ticket
https://its.cern.ch/jira/browse/CMSHLT-695

**Pull request merged**
