### PR TITLE
[Backport] Turning on GE21 digis to be unpacked for monitoring [12_4_X]

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:
* GE 21 demonstrator has installed in P5. And GEM group wants to monitor the demonstrator with DQM using digis.
* GEM packer and unpacker are updated for using GEMChMap to unpack the data from GE21 demonstrator.
* Generating RecHits with GE21 is turned off, so the demonstrator doesn't affect muons upstream.

#### PR validation:
* The code format has applied with `scram build code-format` and `scram build code-checks`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
* This PR is backport of #38062 and #38119

@jshlee @watson-ij

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38062

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38119

**Comment by tvami** [comment]
type gem

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/38265

**Comment by tvami** [comment]
+db

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
urgent
 * should be merged by Tuesday

**Comment by emanueleusai** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- backport of https://github.com/cms-sw/cmssw/pull/38062, https://github.com/cms-sw/cmssw/pull/38119
- support for new GEM dataformats
- no impact on existing reco

**Pull request merged**
