### PR TITLE
Backport of luminibble unpacker74X

### PR DESCRIPTION
**Pull request by capalmer85**
Backport of https://github.com/cms-sw/cmssw/pull/9394

### CODE REVIEW

**Comment by capalmer85** [comment]
@davidlange6 @slava77 Once this is merged, in which edition of CMSSW should I except this to become available?

**Comment by slava77** [comment]
some of the next 74X (maybe a patch of 746 or a 747)

**Comment by capalmer85** [comment]
Where does that need to be deployed for me to have this in the event content of alcareco?

**Comment by capalmer85** [comment]
Hi @mommsen, @cmsbuild, @franzoni, @emeschi, @davidlange6.  Can someone sign-off please?

**Comment by mommsen** [comment]
+1

**Comment by davidlange6** [comment]
@slava77, @cvuosalo - would be good to include this asap in case of the vd scan next week...

**Comment by slava77** [comment]
I'll take a look. The reco signature showed up here only earlier today.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9728	aa85897
- the same code change as in 75X version
- jenkins tests ran OK (no crashes); there is nothing to compare in the outputs (new objects are not monitored)

**Pull request merged**
