### PR TITLE
Fix EMTF unpacker crash by changing GEM station assignment [11_3_X]

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:
As reported in https://github.com/cms-sw/cmssw/pull/33679 and https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2219.html the EMTF unpacker is causing a crash after a firmware update to include GEM inputs in EMTF DAQ output. The crash is due to the invalid station assignment and this PR fixes it. 

Since we want to keep this firmware for the next MWGR we want to get this in CMSSW as soon as possible also with a backport to 11_3_X.

#### PR validation:

Validated with:

- scram b runtests
- runTheMatrix.py -l limited -i all --ibeos

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of https://github.com/cms-sw/cmssw/pull/33808.

FYI: @jiafulow @dildick @silviodonato

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
type bugfix
see https://github.com/cms-sw/cmssw/pull/33679#issuecomment-845471011

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
