### PR TITLE
Replacing HLT Scouting trigger paths by new Run3 Scouting trigger path (11_2_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Replacing HLT Scouting trigger paths by new Run3 Scouting trigger path
Based on CMSSW_11_2_1

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #32797 

Needed for Scouting MC production

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #32797

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
