### PR TITLE
Deepvertex and DeepJet+DeepVertex combination backport to 10_6_x

### PR DESCRIPTION
**Pull request by leonardogiannini**
#### PR description:

This PR is a backport of:

-  PR  [#31988](https://github.com/cms-sw/cmssw/pull/31988)   -->  ONNX implementation of DeepVertex and DeepVertex+DeepJet combined taggers 

- PR  [#26088](https://github.com/cms-sw/cmssw/pull/26088)   --> Features and first version of DeepJet (only the features are now relevant)

no changes are made to the standard workflow. b tagging algorithms are added for a b-tag scale factor campaign

#### PR validation:

- an extensive validation has been performed when merging  PR [#31988](https://github.com/cms-sw/cmssw/pull/31988) 

- a comparison of the results in 10_6_x and 11_2_x has also been made: running the test configuration [test_deep_vertexcomb_cfg.py](https://github.com/cms-sw/cmssw/blob/master/RecoBTag/ONNXRuntime/test/test_deep_vertexcomb_cfg.py) (with the relevant switches set to True), no differences in deepVertex and negligible differences (10^-5) for the deepJet and the combined discriminator are found

see below a sample of the diff: 
image

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by jpata** [comment]
Backport looks equivalent to the two original PRs and I see no issues in the tests. I made an inline comment about something that should be cleaned up separately.

Before I sign, could someone from BTV (cc @emilbols) confirm the plan to backport and run this in 10_6_X? Is it going to be included in the next round of MINIAOD? Thanks!

**Comment by smoortga** [comment]
> Backport looks equivalent to the two original PRs and I see no issues in the tests. I made an inline comment about something that should be cleaned up separately.
> 
> Before I sign, could someone from BTV (cc @emilbols) confirm the plan to backport and run this in 10_6_X? Is it going to be included in the next round of MINIAOD? Thanks!

We plan to do a private production of ntuples (rerunning this on miniAOD) for a commissioning campaign (using the UltraLegacy2018 setup) in 10_6_X. We need to validate these taggers after which we will perhaps include them in a central production (not yet decided when, depends on the outcome of the validation)

**Comment by jpata** [comment]
@leonardogiannini can you confirm that the code runs and produces a reasonable output in 10_6_X? Just to be sure that the test was run :)

**Comment by leonardogiannini** [comment]
Running the test configuration https://github.com/cms-sw/cmssw/blob/master/RecoBTag/ONNXRuntime/test/test_deep_vertexcomb_cfg.py (with relevant switches set to True) in 10_6_x and 11_2_x, I found no difference in deepVertex and negligible differences (10^-5) for the deepJet and the combined discriminator. It looks ok to me.

**Comment by jpata** [comment]
Thanks for the test @leonardogiannini! Can you please edit the PR description, to fix the URL and mention this test?

We will need to update the cms-data tag in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc700/data/cmsswdata.txt#L9 with the data files introduced in https://github.com/cms-data/RecoBTag-Combined/pull/37.

@mrodozov can you confirm the procedure, should Leonardo open a PR against https://github.com/cms-data/RecoBTag-Combined/releases/tag/V01-07-00 with the weight files, or can the tag for 10_6_X be upgraded?

**Comment by jpata** [comment]
test parameters:
- pull_requests: cms-data/RecoBTag-Combined#40

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please abort

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- backport of #31988, #26088
- jenkins tests are fine (code is not enabled in a workflow)
- per private tests, the expected output is there and correct
- requires the data PR https://github.com/cms-data/RecoBTag-Combined/pull/40

**Comment by qliphy** [comment]
+1

**Pull request merged**
