### PR TITLE
Clamp the number of pixel tracks to the capacity of the SoA [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The data structure used to store the pixel tracks currently has a fixed size of 32768, which was found to be adequate based on MC studies.
While running over collisions data a small fraction of events has been found to have a larger number of tracks, leading to assertion failures or memory access errors.

This PR clamps the number of pixel tracks to the capacity of the SoA, and adds a warning like
```
%MSG-w PixelTracks:  PixelTrackSoAFromCUDA:hltPixelTracksFromGPU  30-Jul-2022 09:16:12 CEST Run: 356071 Event: 46424286
Unsorted reconstructed pixel tracks truncated to 32767 candidates
%MSG
```

#### PR validation:

Running over an event with > 33k pixel tracks no longer causes assertion failures.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. 

Backport of #38883 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #38883

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by qliphy** [comment]
hold
as in the master https://github.com/cms-sw/cmssw/pull/38883#issuecomment-1199187697

**Comment by fwyzard** [comment]
unhold
as in the master https://github.com/cms-sw/cmssw/pull/38883#issuecomment-1200108673

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by fwyzard** [comment]
urgent

**Comment by qliphy** [comment]
unhold

**Comment by qliphy** [comment]
+1

**Pull request merged**
