### PR TITLE
[HGCAL] 11_1_X backport of CLUE with regional em factors

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

This is the backport of PR #31730 . This is the first time I am doing a backport. I used the latest 
11_1_X integration build (CMSSW_11_1_X_2020-10-27-1100). If I am missing something please let me know.  

#### PR validation:

No conflict while rebasing. All validation tests in the original PR. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

A backport of this PR was agreed with the HLT upgrade conveners @fwyzard @trtomei

@rovere @cseez @felicepantaleo @lecriste @pfs @franzoni @mariadalfonso

### CODE REVIEW

**Comment by slava77** [comment]
-1

wrong target branch (master).
chances are that clicking "Edit" should allow to change the target branch 11_1_X

**Comment by slava77** [comment]
> -code-checks
> 
> ERROR: Build errors found during clang-tidy run.
> 
> ```
> CommonTools/PileupAlgos/src/PuppiContainer.cc:10:10: error: 'fastjet/PseudoJet.hh' file not found [clang-diagnostic-error]
> #include "fastjet/PseudoJet.hh"
>          ^
> ```

@smuzaffar @mrodozov 
instead of the full dump as in https://github.com/cms-sw/cmssw/pull/31959#issuecomment-717482041 above
it would be nice to truncate the message and add a link to the full error.
Thank you in advance.

**Comment by apsallid** [comment]
@slava77 Thanks a lot, it worked!

**Comment by rovere** [comment]
This PR is buggy, and I already alerted @apsallid 
I'm not sure why he opened it. 
I'd suggest closing this PR, preparing a proper fix for the bug that has been introduced also in `11_2`, testing and verifying that the bug is fixed, and only after submitting a `backport` with the fix included.
Please, close this PR.

**Pull request closed without merging**
