### PR TITLE
MTD Reco geometry: minor technical cleaning

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

- remove useless ```GeometricTimingDet``` header in digitization and local reconstruction code;

- avoid copy in range based loops inside ```MTDGeometry``` following #29002 (but no big gain expected)

#### PR validation:

The test code in ```Geometry/MTDGeometryBuilder``` provides unchanged description of scenario D50.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
+1
- Simple technical changes
- Jenkins tests pass and show no differences

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
