### PR TITLE
Fix `base_wf_number_2022` (should be `base_wf`)

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Small fix prompted by https://github.com/cms-sw/cmssw/pull/46610#issuecomment-2476858257.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,Run4,data_highstats

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
@cms-sw/upgrade-l2 sorry to bother, if you could have a look at this I would like to try to have this included before pre4 is closed ( if @cms-sw/orp-l2 agree ).

**Comment by AdrianoDee** [comment]
Thanks @Moanwar !

**Comment by smuzaffar** [comment]
@AdrianoDee , for `relvals_opt` (under `test  parameters` ) one needs to provide the workflow/relval number too. I suggest to restart the tests by add `relvals = <wf_num>` in https://github.com/cms-sw/cmssw/pull/46701#issuecomment-2476879707

**Comment by AdrianoDee** [comment]
@smuzaffar in this specific case I didn't really wanted to test any wf but just check that the matrix tests were not failing anymore with

```
ignoring non-requested file relval_premix
ignoring non-requested file relval_nano
processing relval_data_highstats
ERROR importing file  relval_data_highstats name 'base_wf_number_2022' is not defined
ignoring non-requested file relval_standard
```

and [they don't](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b0be0a/42867/unitTests/log.txt)

```
ignoring non-requested file relval_premix
ignoring non-requested file relval_nano
processing relval_data_highstats
ignoring non-requested file relval_standard
ignoring non-requested file relval_highstats
```

I'll resend them with a dummy wf.

**Comment by AdrianoDee** [comment]
test parameters:
- relvals = 2024.101001
- relvals_opt = --what data_highstats

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:
- relvals = 2024.101005
- relvals_opt = --what data_highstats

**Comment by AdrianoDee** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
