### PR TITLE
add track hit eff monitoring vs BX

### PR DESCRIPTION
**Pull request by mtosi**
this PR is needed for monitoring the track hit efficiency vs BX
new plots will be created only when running TrackingDQMSourceTier0MinBias sequence
(which should be only on ZeroBias PD)

### CODE REVIEW

**Comment by mtosi** [comment]
@rovere @VinInn @deguio

**Comment by VinInn** [comment]
will this be backported in 80X and deployed in production?
any ETA?

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
the idea is to have it in 80x as well
but I have to wait for its 81x integration, first
many PRs have been stacked recently :( ...

**Comment by dmitrijus** [comment]
+1
(assuming the tests are okay)

**Comment by rovere** [comment]
I'm not quite sure the code is "correct". If you run both monitoring at the same time, i.e. _vsPU and _vsBX, you need to have a way to disentangle the two, which means you have to code the kind of monitoring you are doing in the KeyHasher, otherwise you are out of luck, in the sense that you'll have unnecessary collisions, which spoil the whole idea of hashing.

-1 (without any power .. ;) )

**Comment by dmitrijus** [comment]
Marco is right - please update KeyHasher ( https://github.com/mtosi/cmssw/blob/f7de06e42add53c2977e75941614a59738aaef91/DQM/TrackingMonitor/interface/TrackAnalyzer.h#L386 ) to include the k.monitoring.

I guess something trivial,such as `return k.det*200+k.subdet*2 + k.monitoring;`

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
I've just created PR https://github.com/cms-sw/cmssw/pull/14448 for the back port in 80x
hope it is fine
thanks

**Pull request merged**
