### PR TITLE
Add hcal fraction to packed candidates (76X)

### PR DESCRIPTION
**Pull request by gpetruc**
Save hcal energy fraction for pf candidates corresponding to neutral hadrons in the tracker (pdgId 130) or in the HF (pdgId 1). 
The energy fraction is packed with an absolute precision of 1%. We will evaluate later if the precision can be reduced for `CMSSW_8_0_X`, depending on what we'll learn in `CMSSW_7_6_X`.
From @mariadalfonso after discussion with @arizzi and @bachtis 

The branch merges cleanly also in `CMSSW_8_0_X`, if you need a separate PR it can be made.

### CODE REVIEW

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
The variable needs to be assigned in the copy and move constructors and the assignment operators.

**Comment by Dr15Jones** [comment]
Hold

**Comment by gpetruc** [comment]
Updated copy and move constructors and assignment operators.
Sorry I hadn't even realized that those methods had been added in the 76X
version of this class

 Giovanni

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Pull request merged**
