### PR TITLE
MTD geometry: fix BTL numbering scheme for scenario v3, input by Geant4, move unit tests to D110 scenario

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Fix of BTL numbering scheme for the latest geometry scenario v3, when DD4hep input is passed by Geant4. Addresses the failure reported in https://github.com/cms-sw/cmssw/pull/45175#issuecomment-2155832315 .

The whole set of unit tests for MTD geometry is updated to scenario I17 / D110, a corresponding update of the cms-data reference https://github.com/cms-data/Geometry-TestReference/pull/14 is required.

#### PR validation:

Code checked both with standalone test code (not failing anyway even before) and test workflows 24834.0, 24834.911, 29634.0, 29634.911 .

### CODE REVIEW

**Comment by fabiocos** [comment]
type bugfix

**Comment by fabiocos** [comment]
test parameters:

- workflows = 29634.0,29634.911
- relvals_opt = --what upgrade

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@srimanob as far as I can see, the residual crash is related to HGCAL, the MTD problem is solved. I will update the standalone geometry tests to bring them to D110 as default, but the problem anyway was not present there, it is the way Geant4 is passing the information that causes the issue. I need to check whether I can update the test to catch that.

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/14

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
The workflow 29634.911 is success now, thanks @fabiocos 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17a93c/39885/runTheMatrix-results/29634.911_TTbar_14TeV+2026D110_DD4hep/

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@cms-sw/orp-l2 this PR requires to be merged together with https://github.com/cms-data/Geometry-TestReference/pull/14 , otherwise several unit tests will fail.

**Comment by rappoccio** [comment]
+1

**Comment by aandvalenzuela** [comment]
Hi @fabiocos,

Unit test `RecoMTDDetLayersTestDriver` fails in aarch64 with:
```
>  L/W/T   :     118.869904 /     237.800034 /       0.005005
201367c201367
<  rmax    :     118.900063
---
>  rmax    :     118.900070
Failure in comparison for mtdDetLayerGeometry.log: status 255

---> test RecoMTDDetLayersTestDriver had ERRORS
TestTime:69
^^^^ End Test RecoMTDDetLayersTestDriver ^^^^
```
I think the failure might be related with this PR. See full log in [CMSSW_14_1_X_2024-06-17-2300](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc12/CMSSW_14_1_X_2024-06-20-2300/unitTestLogs/RecoMTD/DetLayers#/144-144).

Thanks,
Andrea

**Comment by fabiocos** [comment]
@aandvalenzuela thanks for warning me. We are running this test since years now, and this is the first issue of this type as far as I recall. It looks like a problem with numerical rounding on aarch64 vs amd64 that was not so far exposed. Apart that I have no  easy direct way to test on aarch64, I do not see really what I could do, apart for reducing the number of significant digits to be checked, reproduce the reference and hoping for the best. Essentially, the message from the failure above is that we are unable to rely on geometrical calculations at better than 1 micron (the values causing issues are positions expressed in cm).

**Comment by fwyzard** [comment]
@fabiocos you can use `lxplus-arm` to run tests on aarch64.

**Pull request merged**
