### PR TITLE
correct cfi files to link to latest PPS geometry

### PR DESCRIPTION
**Pull request by diemort**
#### PR description:

Given the corrected material introduced in #35961, this PR is meant to correct the cfi files (2021 and 2022) to point to the latest PPS geometry with the corrected material. No major changes are proposed. One dd4hep cfi file is updated to contain a link to the latest dd4hep geometry (now v4).

#### PR validation:

Geometry dump script confirms no error related to the reco geometry. PPS direct simulation confirms no change in the geometry. Script to produce DB payload for DDD and dd4hep used to confirm no issues with the list of XML files. More details [here](https://twiki.cern.ch/twiki/bin/view/CMS/PPSGeometryFix122X) 

Basic checks passed.
Code checks passed.
Matrix test passed 42 41 40 30 18 4 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 failed

FYI @fabferro @jan-kaspar @wpcarvalho

### CODE REVIEW

**Comment by civanch** [comment]
@cvuosalo , @bsunanda , please, comment on this PR.

**Comment by bsunanda** [comment]
@civanch @cvuosalo @diemort We normally create a new version of xml files but not a cfi file. We correct the existing cfi file to include the correct set of xml files.

**Comment by diemort** [comment]
@bsunanda @civanch @cvuosalo We usually keep the different versions to allow comparison between the geometries and keep track of the changes with time. Would you prefer to remove the versions and keep the latest one only?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

was discussed at SIM meeting https://indico.cern.ch/event/1093855/contributions/4600355/attachments/2340526/3990179/20211105.pdf

**Comment by qliphy** [comment]
+1

**Pull request merged**
