### PR TITLE
Remove obsolete tracking configuration files

### PR DESCRIPTION
**Pull request by makortel**
This PR suggests to remove all the now-obsolete `*Phase1PU70*`, `*Phase1PU140*`, `*Phase2PU140*`, and `*LowPU*` tracking configuration files, and a couple of others I encountered/remembered lately.

Tested in CMSSW_9_0_X_2016-11-17-2300, no changes expected.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by ebrondol** [comment]
Thanks @makortel

**Comment by cvuosalo** [comment]
+1

For #16698 991f1af8ac8a4cefbb0c2a1595fa0b5a81c027a6

Deleting obsolete tracking config files. There should be no change in monitored quantities.

Jenkins tests against baseline CMSSW_9_0_X_2016-11-20-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
