### PR TITLE
Update EDProducer and EDAnalyzer skeletons and edmPythonConfigToCppValidation to show addWithDefaultLabel() in their examples

### LINKED ISSUE #32282: update mkedprod and co with newer fillDescriptions
Currently, mkedprod & co generate a skeleton which uses `descriptions.addDefault(desc);` and thus does not generate the cfi files. 

We had some confusion on the PR https://github.com/cms-sw/cmssw/pull/32222/files/b91d4a5dba8db0c252d8093a7c7c9cc84716138f#r530326611 that the template does not allow auto-generation of the cfi, which I understand is the current suggestion.

Perhaps it's a good occasion to update the template to use `addWithDefaultLabel` to make sure that people start with a good baseline for their new modules?

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

The EDProducer and EDAnalyzer skeletons used `ConfigurationDescriptions::add()` as an example in the `fillDescriptions()`, that leads to `cfi` fragment file to not to be generated. Following a suggestion in #32282 this PR updates the skeletons to show `addWithDefaultLabel()`. This PR updates also `edmPythonConfigToCppValidation` to show `addWithDefaultLabel()` but leaves the decision of whether to use it or not to the caller of the script.

Resolves https://github.com/cms-sw/cmssw/issues/32282.

#### PR validation:

Ran `edmPythonConfigToCppValidation` on one `cfi` file and inspected the output visually.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by Dr15Jones** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
