### PR TITLE
HLT menu development for `12_3_X` (Patatrack GPU modules) [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

This is the PR for the `master` branch, which will then be backported to `12_3_X` (which is currently the release used for HLT-menu development for Run 3).

~~_The backport to `12_3_X` will be opened once #37755 is merged._~~ (done in #37793.)

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2288](https://its.cern.ch/jira/browse/CMSHLT-2288): [TSG] Introduction of Patatrack GPU modules in the HLT combined table.

This update introduces in the offline HLT menus the modules for GPU offloading developed so far as part of the Patatrack project (Pixel local reco, Pixel tracking/vertexing, ECAL and HCAL local recos). Effectively, it incorporates the customisation [`customizeHLTforPatatrackTriplets`](https://github.com/cms-sw/cmssw/blob/CMSSW_12_4_0_pre3/HLTrigger/Configuration/python/customizeHLTforPatatrack.py#L844) into the HLT menus maintained by TSG. This also coincides with the introduction of "Tasks" in the offline HLT menus. Following the discussion in #36938, it is expected that in the near future `cms.Task` will be replaced by `cms.ConditionalTask` in HLT configs (likely in `12_4_X`).

This PR also includes small changes to the TSG tests to ensure that those tests continue to work even when they are executed on a machine with a GPU.

  - A customisation to HLT+RECO tests is added to remove GPU EventSetup modules from Tasks that are not included in the Schedule; this is needed to make said ES modules available to HLT producers when the test runs on a GPU machine. More details can be found [here (CMSHLT-2288)](https://its.cern.ch/jira/browse/CMSHLT-2288?focusedCommentId=4326483&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4326483).

  - The HLT-integration tests are forced, for now, to run on CPU even if the machine has a GPU. This avoids tests failing due to the current limits in reproducibility of HLT outputs when using GPUs.

Both changes are workarounds in a way, and they could/should be improved in the future.

A small fix in `customizeHLTforPatatrack.py` is also included.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

To check wfs that apply the `Patatrack` customisation on top of the `GRun` menu, and run on a machine with a GPU.

**Comment by missirol** [comment]
@smuzaffar , the bot seems unresponsive. Any suggestions?

**Comment by smuzaffar** [comment]
@missirol , looks like since 18h00 today there is issue with CERN network that is why requests are not reaching jenkins.

**Comment by missirol** [comment]
@smuzaffar , okay, thanks. For my understanding: do we have to ping the bot later on, or will it "see" the comments/requests on its own, eventually?

**Comment by missirol** [comment]
okay, thank you!

**Comment by smuzaffar** [comment]
> enable gpu
> 
> To check wfs that apply the `Patatrack` customisation on top of the `GRun` menu, and run on a machine with a GPU.

looks like this comment was not recognized by bot

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by smuzaffar** [comment]
looks good now

**Comment by missirol** [comment]
> looks like this comment was not recognized by bot

Thanks, @smuzaffar . The GPU tests are not strictly necessary, but I tried to enable it again.

> looks good now

Was the syntax in the 1st try wrong because of the extra comment in the 2nd line? And out of curiosity, how do you check that the 2nd try went well?

**Comment by smuzaffar** [comment]
I basically checked the jenkins job parameters ( https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/24422/parameters/ ) and I see that now it has `ENABLE_BOT_TESTS=GPU` . I will update bot to `thumbs up` `enable test-name` comments too

**Comment by missirol** [comment]
Outputs of PR tests look okay (iiuc, the outputs of wf `11634.506` are known to be not-fully-reproducible).

I'm still trying to understand the differences reported for "TriggerResults" (done via `hltDiff`), for example

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-03-1100+865cde/50020/triggerResults/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/HLT.log
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-03-1100+865cde/50020/triggerResults/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/HLT.json

It looks like the difference is not in the number of events accepted/rejected, but in module-IDs (or rather, modules-indices, `"m"`) of the modules in the Path (as given by `hltDiff`, which internally uses `HLTConfigData`). For `HLTriggerFirstPath`, I think this comes from the removal of `hltGetConditions`. For other Paths, this might also be related to the introduction of Tasks. I tag @fwyzard in case he has a better understanding of this.

This might have to be followed up, but I think this PR could proceed as is.

**Comment by missirol** [comment]
> For other Paths, this might also be related to the introduction of Tasks.

I don't know if this fully explains the `hltDiff` outputs discussed in https://github.com/cms-sw/cmssw/pull/37783#issuecomment-1116981811, but indeed the modules in Tasks are not listed as "Modules in the Path", at least in the `TrigReport` outputs.

Below [*] is an example of `TrigReport` outputs for 1 Path comparing `GRun/V77` (no Tasks) to `GRun/V78` (with Tasks).

This is the current behaviour of the framework, and there is nothing in particular to change in this PR.

I'm inclined to sign off on this PR as is, and investigate this more offline (it might also be interesting to check how `ConditionalTasks` behave in this respect).

[*]

`GRun/V77` (no Tasks):
```
TrigReport ---------- Modules in Path: HLT_AK8PFJet380_TrimMass30_v11 ------------
TrigReport  Trig Bit#    Visited     Passed     Failed      Error Name
TrigReport     1    0        100        100          0          0 hltTriggerType
TrigReport     1    1        100        100          0          0 hltGtStage2Digis
TrigReport     1    2        100        100          0          0 hltGtStage2ObjectMap
TrigReport     1    3        100        100          0          0 hltScalersRawToDigi
TrigReport     1    4        100        100          0          0 hltOnlineMetaDataDigis
TrigReport     1    5        100        100          0          0 hltOnlineBeamSpot
TrigReport     1    6        100          5         95          0 hltL1sSingleJet180
TrigReport     1    7          5          5          0          0 hltPreAK8PFJet380TrimMass30
TrigReport     1    8          5          5          0          0 hltEcalDigisLegacy
TrigReport     1    9          5          5          0          0 hltEcalDigis
TrigReport     1   10          5          5          0          0 hltEcalUncalibRecHit
TrigReport     1   11          5          5          0          0 hltEcalDetIdToBeRecovered
TrigReport     1   12          5          5          0          0 hltEcalRecHit
TrigReport     1   13          5          5          0          0 hltHcalDigis
TrigReport     1   14          5          5          0          0 hltHbhereco
TrigReport     1   15          5          5          0          0 hltHfprereco
TrigReport     1   16          5          5          0          0 hltHfreco
TrigReport     1   17          5          5          0          0 hltHoreco
TrigReport     1   18          5          5          0          0 hltTowerMakerForAll
TrigReport     1   19          5          5          0          0 hltAK8CaloJets
TrigReport     1   20          5          5          0          0 hltAK8CaloJetsIDPassed
TrigReport     1   21          5          5          0          0 hltFixedGridRhoFastjetAllCalo
TrigReport     1   22          5          5          0          0 hltAK8CaloFastJetCorrector
TrigReport     1   23          5          5          0          0 hltAK8CaloRelativeCorrector
TrigReport     1   24          5          5          0          0 hltAK8CaloAbsoluteCorrector
TrigReport     1   25          5          5          0          0 hltAK8CaloResidualCorrector
TrigReport     1   26          5          5          0          0 hltAK8CaloCorrector
TrigReport     1   27          5          5          0          0 hltAK8CaloJetsCorrected
TrigReport     1   28          5          5          0          0 hltAK8CaloJetsCorrectedIDPassed
TrigReport     1   29          5          0          5          0 hltAK8SingleCaloJet280
TrigReport     1   30          0          0          0          0 hltEcalDigisLegacy
TrigReport     1   31          0          0          0          0 hltEcalDigis
TrigReport     1   32          0          0          0          0 hltEcalUncalibRecHit
TrigReport     1   33          0          0          0          0 hltEcalDetIdToBeRecovered
TrigReport     1   34          0          0          0          0 hltEcalRecHit
TrigReport     1   35          0          0          0          0 hltHcalDigis
TrigReport     1   36          0          0          0          0 hltHbhereco
TrigReport     1   37          0          0          0          0 hltHfprereco
TrigReport     1   38          0          0          0          0 hltHfreco
TrigReport     1   39          0          0          0          0 hltHoreco
TrigReport     1   40          0          0          0          0 hltTowerMakerForAll
TrigReport     1   41          0          0          0          0 hltAK8CaloJetsPF
TrigReport     1   42          0          0          0          0 hltAK4CaloJetsPF
TrigReport     1   43          0          0          0          0 hltAK8CaloJetsPFEt5
TrigReport     1   44          0          0          0          0 hltAK4CaloJetsPFEt5
TrigReport     1   45          0          0          0          0 hltMuonDTDigis
TrigReport     1   46          0          0          0          0 hltDt1DRecHits
TrigReport     1   47          0          0          0          0 hltDt4DSegments
TrigReport     1   48          0          0          0          0 hltMuonCSCDigis
TrigReport     1   49          0          0          0          0 hltCsc2DRecHits
TrigReport     1   50          0          0          0          0 hltCscSegments
TrigReport     1   51          0          0          0          0 hltMuonRPCDigis
TrigReport     1   52          0          0          0          0 hltRpcRecHits
TrigReport     1   53          0          0          0          0 hltMuonGEMDigis
TrigReport     1   54          0          0          0          0 hltGemRecHits
TrigReport     1   55          0          0          0          0 hltGemSegments
TrigReport     1   56          0          0          0          0 hltL2OfflineMuonSeeds
TrigReport     1   57          0          0          0          0 hltL2MuonSeeds
TrigReport     1   58          0          0          0          0 hltL2Muons
TrigReport     1   59          0          0          0          0 hltL2MuonCandidates
TrigReport     1   60          0          0          0          0 hltSiPixelDigisLegacy
TrigReport     1   61          0          0          0          0 hltSiPixelDigis
TrigReport     1   62          0          0          0          0 hltSiPixelClustersLegacy
TrigReport     1   63          0          0          0          0 hltSiPixelClusters
TrigReport     1   64          0          0          0          0 hltSiPixelClustersCache
TrigReport     1   65          0          0          0          0 hltSiPixelRecHitSoA
TrigReport     1   66          0          0          0          0 hltSiPixelRecHits
TrigReport     1   67          0          0          0          0 hltSiStripExcludedFEDListProducer
TrigReport     1   68          0          0          0          0 hltSiStripRawToClustersFacility
TrigReport     1   69          0          0          0          0 hltSiStripClusters
TrigReport     1   70          0          0          0          0 hltIterL3OISeedsFromL2Muons
TrigReport     1   71          0          0          0          0 hltIterL3OITrackCandidates
TrigReport     1   72          0          0          0          0 hltIterL3OIMuCtfWithMaterialTracks
TrigReport     1   73          0          0          0          0 hltIterL3OIMuonTrackCutClassifier
TrigReport     1   74          0          0          0          0 hltIterL3OIMuonTrackSelectionHighPurity
TrigReport     1   75          0          0          0          0 hltL3MuonsIterL3OI
TrigReport     1   76          0          0          0          0 hltIterL3OIL3MuonsLinksCombination
TrigReport     1   77          0          0          0          0 hltIterL3OIL3Muons
TrigReport     1   78          0          0          0          0 hltIterL3OIL3MuonCandidates
TrigReport     1   79          0          0          0          0 hltL2SelectorForL3IO
TrigReport     1   80          0          0          0          0 hltPixelTracksFitter
TrigReport     1   81          0          0          0          0 hltPixelTracksFilter
TrigReport     1   82          0          0          0          0 hltPixelTracksTrackingRegions
TrigReport     1   83          0          0          0          0 hltPixelTracksSoA
TrigReport     1   84          0          0          0          0 hltPixelTracks
TrigReport     1   85          0          0          0          0 hltPixelVerticesSoA
TrigReport     1   86          0          0          0          0 hltPixelVertices
TrigReport     1   87          0          0          0          0 hltTrimmedPixelVertices
TrigReport     1   88          0          0          0          0 hltIterL3MuonPixelTracksTrackingRegions
TrigReport     1   89          0          0          0          0 hltPixelTracksInRegionL2
TrigReport     1   90          0          0          0          0 hltIter0IterL3MuonPixelSeedsFromPixelTracks
TrigReport     1   91          0          0          0          0 hltIter0IterL3MuonPixelSeedsFromPixelTracksFiltered
TrigReport     1   92          0          0          0          0 hltIter0IterL3MuonCkfTrackCandidates
TrigReport     1   93          0          0          0          0 hltIter0IterL3MuonCtfWithMaterialTracks
TrigReport     1   94          0          0          0          0 hltIter0IterL3MuonTrackCutClassifier
TrigReport     1   95          0          0          0          0 hltIter0IterL3MuonTrackSelectionHighPurity
TrigReport     1   96          0          0          0          0 hltL3MuonsIterL3IO
TrigReport     1   97          0          0          0          0 hltIterL3MuonsFromL2LinksCombination
TrigReport     1   98          0          0          0          0 hltL1MuonsPt0
TrigReport     1   99          0          0          0          0 hltPixelTracksFitter
TrigReport     1  100          0          0          0          0 hltPixelTracksFilter
TrigReport     1  101          0          0          0          0 hltPixelTracksTrackingRegions
TrigReport     1  102          0          0          0          0 hltPixelTracksSoA
TrigReport     1  103          0          0          0          0 hltPixelTracks
TrigReport     1  104          0          0          0          0 hltPixelVerticesSoA
TrigReport     1  105          0          0          0          0 hltPixelVertices
TrigReport     1  106          0          0          0          0 hltTrimmedPixelVertices
TrigReport     1  107          0          0          0          0 hltIterL3FromL1MuonPixelTracksTrackingRegions
TrigReport     1  108          0          0          0          0 hltPixelTracksInRegionL1
TrigReport     1  109          0          0          0          0 hltIter0IterL3FromL1MuonPixelSeedsFromPixelTracks
TrigReport     1  110          0          0          0          0 hltIter0IterL3FromL1MuonPixelSeedsFromPixelTracksFiltered
TrigReport     1  111          0          0          0          0 hltIter0IterL3FromL1MuonCkfTrackCandidates
TrigReport     1  112          0          0          0          0 hltIter0IterL3FromL1MuonCtfWithMaterialTracks
TrigReport     1  113          0          0          0          0 hltIter0IterL3FromL1MuonTrackCutClassifier
TrigReport     1  114          0          0          0          0 hltIter0IterL3FromL1MuonTrackSelectionHighPurity
TrigReport     1  115          0          0          0          0 hltIterL3MuonMerged
TrigReport     1  116          0          0          0          0 hltIterL3MuonAndMuonFromL1Merged
TrigReport     1  117          0          0          0          0 hltIterL3GlbMuon
TrigReport     1  118          0          0          0          0 hltIterL3MuonsNoID
TrigReport     1  119          0          0          0          0 hltIterL3Muons
TrigReport     1  120          0          0          0          0 hltL3MuonsIterL3Links
TrigReport     1  121          0          0          0          0 hltIterL3MuonTracks
TrigReport     1  122          0          0          0          0 hltIterL3MuonCandidates
TrigReport     1  123          0          0          0          0 hltSiPixelDigisLegacy
TrigReport     1  124          0          0          0          0 hltSiPixelDigis
TrigReport     1  125          0          0          0          0 hltSiPixelClustersLegacy
TrigReport     1  126          0          0          0          0 hltSiPixelClusters
TrigReport     1  127          0          0          0          0 hltSiPixelClustersCache
TrigReport     1  128          0          0          0          0 hltSiPixelRecHitSoA
TrigReport     1  129          0          0          0          0 hltSiPixelRecHits
TrigReport     1  130          0          0          0          0 hltPixelTracksFitter
TrigReport     1  131          0          0          0          0 hltPixelTracksFilter
TrigReport     1  132          0          0          0          0 hltPixelTracksTrackingRegions
TrigReport     1  133          0          0          0          0 hltPixelTracksSoA
TrigReport     1  134          0          0          0          0 hltPixelTracks
TrigReport     1  135          0          0          0          0 hltPixelVerticesSoA
TrigReport     1  136          0          0          0          0 hltPixelVertices
TrigReport     1  137          0          0          0          0 hltTrimmedPixelVertices
TrigReport     1  138          0          0          0          0 hltSiStripExcludedFEDListProducer
TrigReport     1  139          0          0          0          0 hltSiStripRawToClustersFacility
TrigReport     1  140          0          0          0          0 hltSiStripClusters
TrigReport     1  141          0          0          0          0 hltIter0PFLowPixelSeedsFromPixelTracks
TrigReport     1  142          0          0          0          0 hltIter0PFlowCkfTrackCandidates
TrigReport     1  143          0          0          0          0 hltIter0PFlowCtfWithMaterialTracks
TrigReport     1  144          0          0          0          0 hltIter0PFlowTrackCutClassifier
TrigReport     1  145          0          0          0          0 hltMergedTracks
TrigReport     1  146          0          0          0          0 hltPFMuonMerging
TrigReport     1  147          0          0          0          0 hltMuonLinks
TrigReport     1  148          0          0          0          0 hltMuons
TrigReport     1  149          0          0          0          0 hltEcalPreshowerDigis
TrigReport     1  150          0          0          0          0 hltEcalPreshowerRecHit
TrigReport     1  151          0          0          0          0 hltParticleFlowRecHitECALUnseeded
TrigReport     1  152          0          0          0          0 hltParticleFlowRecHitHBHE
TrigReport     1  153          0          0          0          0 hltParticleFlowRecHitHF
TrigReport     1  154          0          0          0          0 hltParticleFlowRecHitPSUnseeded
TrigReport     1  155          0          0          0          0 hltParticleFlowClusterECALUncorrectedUnseeded
TrigReport     1  156          0          0          0          0 hltParticleFlowClusterPSUnseeded
TrigReport     1  157          0          0          0          0 hltParticleFlowClusterECALUnseeded
TrigReport     1  158          0          0          0          0 hltParticleFlowClusterHBHE
TrigReport     1  159          0          0          0          0 hltParticleFlowClusterHCAL
TrigReport     1  160          0          0          0          0 hltParticleFlowClusterHF
TrigReport     1  161          0          0          0          0 hltLightPFTracks
TrigReport     1  162          0          0          0          0 hltParticleFlowBlock
TrigReport     1  163          0          0          0          0 hltParticleFlow
TrigReport     1  164          0          0          0          0 hltAK8PFJets
TrigReport     1  165          0          0          0          0 hltAK8PFJetsLooseID
TrigReport     1  166          0          0          0          0 hltAK8PFJetsTightID
TrigReport     1  167          0          0          0          0 hltFixedGridRhoFastjetAll
TrigReport     1  168          0          0          0          0 hltAK8PFFastJetCorrector
TrigReport     1  169          0          0          0          0 hltAK8PFRelativeCorrector
TrigReport     1  170          0          0          0          0 hltAK8PFAbsoluteCorrector
TrigReport     1  171          0          0          0          0 hltAK8PFResidualCorrector
TrigReport     1  172          0          0          0          0 hltAK8PFCorrector
TrigReport     1  173          0          0          0          0 hltAK8PFJetsCorrected
TrigReport     1  174          0          0          0          0 hltAK8PFJetsLooseIDCorrected
TrigReport     1  175          0          0          0          0 hltAK8PFJetsTightIDCorrected
TrigReport     1  176          0          0          0          0 hltAK8PFJetsCorrectedMatchedToCaloJets280
TrigReport     1  177          0          0          0          0 hltAK8SinglePFJet380
TrigReport     1  178          0          0          0          0 hltAK8TrimModJets
TrigReport     1  179          0          0          0          0 hltAK8SinglePFJetTrimModMass30
TrigReport     1  180          0          0          0          0 hltBoolEnd
```

`GRun/V78` (with Tasks):
```
TrigReport ---------- Modules in Path: HLT_AK8PFJet380_TrimMass30_v11 ------------
TrigReport  Trig Bit#    Visited     Passed     Failed      Error Name
TrigReport     1    0        100        100          0          0 hltTriggerType
TrigReport     1    1        100        100          0          0 hltGtStage2Digis
TrigReport     1    2        100        100          0          0 hltGtStage2ObjectMap
TrigReport     1    3        100        100          0          0 hltScalersRawToDigi
TrigReport     1    4        100        100          0          0 hltOnlineMetaDataDigis
TrigReport     1    5        100        100          0          0 hltOnlineBeamSpot
TrigReport     1    6        100          5         95          0 hltL1sSingleJet180
TrigReport     1    7          5          5          0          0 hltPreAK8PFJet380TrimMass30
TrigReport     1    8          5          5          0          0 hltTowerMakerForAll
TrigReport     1    9          5          5          0          0 hltAK8CaloJets
TrigReport     1   10          5          5          0          0 hltAK8CaloJetsIDPassed
TrigReport     1   11          5          5          0          0 hltFixedGridRhoFastjetAllCalo
TrigReport     1   12          5          5          0          0 hltAK8CaloFastJetCorrector
TrigReport     1   13          5          5          0          0 hltAK8CaloRelativeCorrector
TrigReport     1   14          5          5          0          0 hltAK8CaloAbsoluteCorrector
TrigReport     1   15          5          5          0          0 hltAK8CaloResidualCorrector
TrigReport     1   16          5          5          0          0 hltAK8CaloCorrector
TrigReport     1   17          5          5          0          0 hltAK8CaloJetsCorrected
TrigReport     1   18          5          5          0          0 hltAK8CaloJetsCorrectedIDPassed
TrigReport     1   19          5          0          5          0 hltAK8SingleCaloJet280
TrigReport     1   20          0          0          0          0 hltTowerMakerForAll
TrigReport     1   21          0          0          0          0 hltAK8CaloJetsPF
TrigReport     1   22          0          0          0          0 hltAK4CaloJetsPF
TrigReport     1   23          0          0          0          0 hltAK8CaloJetsPFEt5
TrigReport     1   24          0          0          0          0 hltAK4CaloJetsPFEt5
TrigReport     1   25          0          0          0          0 hltMuonDTDigis
TrigReport     1   26          0          0          0          0 hltDt1DRecHits
TrigReport     1   27          0          0          0          0 hltDt4DSegments
TrigReport     1   28          0          0          0          0 hltMuonCSCDigis
TrigReport     1   29          0          0          0          0 hltCsc2DRecHits
TrigReport     1   30          0          0          0          0 hltCscSegments
TrigReport     1   31          0          0          0          0 hltMuonRPCDigis
TrigReport     1   32          0          0          0          0 hltRpcRecHits
TrigReport     1   33          0          0          0          0 hltMuonGEMDigis
TrigReport     1   34          0          0          0          0 hltGemRecHits
TrigReport     1   35          0          0          0          0 hltGemSegments
TrigReport     1   36          0          0          0          0 hltL2OfflineMuonSeeds
TrigReport     1   37          0          0          0          0 hltL2MuonSeeds
TrigReport     1   38          0          0          0          0 hltL2Muons
TrigReport     1   39          0          0          0          0 hltL2MuonCandidates
TrigReport     1   40          0          0          0          0 hltSiStripExcludedFEDListProducer
TrigReport     1   41          0          0          0          0 hltSiStripRawToClustersFacility
TrigReport     1   42          0          0          0          0 hltSiStripClusters
TrigReport     1   43          0          0          0          0 hltIterL3OISeedsFromL2Muons
TrigReport     1   44          0          0          0          0 hltIterL3OITrackCandidates
TrigReport     1   45          0          0          0          0 hltIterL3OIMuCtfWithMaterialTracks
TrigReport     1   46          0          0          0          0 hltIterL3OIMuonTrackCutClassifier
TrigReport     1   47          0          0          0          0 hltIterL3OIMuonTrackSelectionHighPurity
TrigReport     1   48          0          0          0          0 hltL3MuonsIterL3OI
TrigReport     1   49          0          0          0          0 hltIterL3OIL3MuonsLinksCombination
TrigReport     1   50          0          0          0          0 hltIterL3OIL3Muons
TrigReport     1   51          0          0          0          0 hltIterL3OIL3MuonCandidates
TrigReport     1   52          0          0          0          0 hltL2SelectorForL3IO
TrigReport     1   53          0          0          0          0 hltPixelTracksFitter
TrigReport     1   54          0          0          0          0 hltPixelTracksFilter
TrigReport     1   55          0          0          0          0 hltIterL3MuonPixelTracksTrackingRegions
TrigReport     1   56          0          0          0          0 hltPixelTracksInRegionL2
TrigReport     1   57          0          0          0          0 hltIter0IterL3MuonPixelSeedsFromPixelTracks
TrigReport     1   58          0          0          0          0 hltIter0IterL3MuonPixelSeedsFromPixelTracksFiltered
TrigReport     1   59          0          0          0          0 hltIter0IterL3MuonCkfTrackCandidates
TrigReport     1   60          0          0          0          0 hltIter0IterL3MuonCtfWithMaterialTracks
TrigReport     1   61          0          0          0          0 hltIter0IterL3MuonTrackCutClassifier
TrigReport     1   62          0          0          0          0 hltIter0IterL3MuonTrackSelectionHighPurity
TrigReport     1   63          0          0          0          0 hltL3MuonsIterL3IO
TrigReport     1   64          0          0          0          0 hltIterL3MuonsFromL2LinksCombination
TrigReport     1   65          0          0          0          0 hltL1MuonsPt0
TrigReport     1   66          0          0          0          0 hltPixelTracksFitter
TrigReport     1   67          0          0          0          0 hltPixelTracksFilter
TrigReport     1   68          0          0          0          0 hltIterL3FromL1MuonPixelTracksTrackingRegions
TrigReport     1   69          0          0          0          0 hltPixelTracksInRegionL1
TrigReport     1   70          0          0          0          0 hltIter0IterL3FromL1MuonPixelSeedsFromPixelTracks
TrigReport     1   71          0          0          0          0 hltIter0IterL3FromL1MuonPixelSeedsFromPixelTracksFiltered
TrigReport     1   72          0          0          0          0 hltIter0IterL3FromL1MuonCkfTrackCandidates
TrigReport     1   73          0          0          0          0 hltIter0IterL3FromL1MuonCtfWithMaterialTracks
TrigReport     1   74          0          0          0          0 hltIter0IterL3FromL1MuonTrackCutClassifier
TrigReport     1   75          0          0          0          0 hltIter0IterL3FromL1MuonTrackSelectionHighPurity
TrigReport     1   76          0          0          0          0 hltIterL3MuonMerged
TrigReport     1   77          0          0          0          0 hltIterL3MuonAndMuonFromL1Merged
TrigReport     1   78          0          0          0          0 hltIterL3GlbMuon
TrigReport     1   79          0          0          0          0 hltIterL3MuonsNoID
TrigReport     1   80          0          0          0          0 hltIterL3Muons
TrigReport     1   81          0          0          0          0 hltL3MuonsIterL3Links
TrigReport     1   82          0          0          0          0 hltIterL3MuonTracks
TrigReport     1   83          0          0          0          0 hltIterL3MuonCandidates
TrigReport     1   84          0          0          0          0 hltPixelTracksFitter
TrigReport     1   85          0          0          0          0 hltPixelTracksFilter
TrigReport     1   86          0          0          0          0 hltSiStripExcludedFEDListProducer
TrigReport     1   87          0          0          0          0 hltSiStripRawToClustersFacility
TrigReport     1   88          0          0          0          0 hltSiStripClusters
TrigReport     1   89          0          0          0          0 hltIter0PFLowPixelSeedsFromPixelTracks
TrigReport     1   90          0          0          0          0 hltIter0PFlowCkfTrackCandidates
TrigReport     1   91          0          0          0          0 hltIter0PFlowCtfWithMaterialTracks
TrigReport     1   92          0          0          0          0 hltIter0PFlowTrackCutClassifier
TrigReport     1   93          0          0          0          0 hltMergedTracks
TrigReport     1   94          0          0          0          0 hltPFMuonMerging
TrigReport     1   95          0          0          0          0 hltMuonLinks
TrigReport     1   96          0          0          0          0 hltMuons
TrigReport     1   97          0          0          0          0 hltParticleFlowRecHitECALUnseeded
TrigReport     1   98          0          0          0          0 hltParticleFlowRecHitHBHE
TrigReport     1   99          0          0          0          0 hltParticleFlowRecHitHF
TrigReport     1  100          0          0          0          0 hltParticleFlowRecHitPSUnseeded
TrigReport     1  101          0          0          0          0 hltParticleFlowClusterECALUncorrectedUnseeded
TrigReport     1  102          0          0          0          0 hltParticleFlowClusterPSUnseeded
TrigReport     1  103          0          0          0          0 hltParticleFlowClusterECALUnseeded
TrigReport     1  104          0          0          0          0 hltParticleFlowClusterHBHE
TrigReport     1  105          0          0          0          0 hltParticleFlowClusterHCAL
TrigReport     1  106          0          0          0          0 hltParticleFlowClusterHF
TrigReport     1  107          0          0          0          0 hltLightPFTracks
TrigReport     1  108          0          0          0          0 hltParticleFlowBlock
TrigReport     1  109          0          0          0          0 hltParticleFlow
TrigReport     1  110          0          0          0          0 hltAK8PFJets
TrigReport     1  111          0          0          0          0 hltAK8PFJetsLooseID
TrigReport     1  112          0          0          0          0 hltAK8PFJetsTightID
TrigReport     1  113          0          0          0          0 hltFixedGridRhoFastjetAll
TrigReport     1  114          0          0          0          0 hltAK8PFFastJetCorrector
TrigReport     1  115          0          0          0          0 hltAK8PFRelativeCorrector
TrigReport     1  116          0          0          0          0 hltAK8PFAbsoluteCorrector
TrigReport     1  117          0          0          0          0 hltAK8PFResidualCorrector
TrigReport     1  118          0          0          0          0 hltAK8PFCorrector
TrigReport     1  119          0          0          0          0 hltAK8PFJetsCorrected
TrigReport     1  120          0          0          0          0 hltAK8PFJetsLooseIDCorrected
TrigReport     1  121          0          0          0          0 hltAK8PFJetsTightIDCorrected
TrigReport     1  122          0          0          0          0 hltAK8PFJetsCorrectedMatchedToCaloJets280
TrigReport     1  123          0          0          0          0 hltAK8SinglePFJet380
TrigReport     1  124          0          0          0          0 hltAK8TrimModJets
TrigReport     1  125          0          0          0          0 hltAK8SinglePFJetTrimModMass30
TrigReport     1  126          0          0          0          0 hltBoolEnd
```

**Comment by missirol** [comment]
+hlt

 - differences in PR outputs are in line with updates to the GRun menu
 - noted that the introduction of Tasks affects the list of "Modules in Paths" reported by the Framework (to be checked if this has any consequences for other HLT utilities, and how `ConditionalTask`s behave in this respect)

**Comment by perrotta** [comment]
+1

**Pull request merged**
