### PR TITLE
Making Puppi optional for PATPackedCandidate producer : 80X

### PR DESCRIPTION
**Pull request by Sam-Harper**
This commit makes puppi inputs optional for PATPackedCandidateProducer. If the puppi related input tags are both empty, it disables accessing puppi. If the input tags not empty, the behaviour is identical to before, thereby protecting against simple typos. 

This is helpful to remake the PFPackedCandidates without running all of miniAOD. The use case which prompts this is the new HEEP V7.0 uses PFPackedCandidates for tracker isolation and therefore needs to produce these in AOD. 

81X and 90X PRs following shortly.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16776 6f803773ce28f741883dc6144babed70d0091499

Provide the option to run the PAT PackedCandidate producer without PUPPI. Default behavior does not change. There should be no change in monitored quantities.

#16777 and #16778 are the 90X and 81X versions of this PR, and the former has been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-12-07-0000 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
