### PR TITLE
E2E NNVtx: A Phase 2 L1T Vertexing algorithm using End to End NN 

### PR DESCRIPTION
**Pull request by BenjaminRS**
#### PR description:

This PR holds the E2E NNVtx code for P2 L1T Primary Vertex Reconstruction. The work has been presented many times over the years including in:
https://cds.cern.ch/record/2792619?ln=en
https://cds.cern.ch/record/2814727?ln=en
And most recently: https://indico.cern.ch/event/1356822/#58-update-on-e2e-nnvtx

The L1T Integration branch version is here: https://github.com/cms-l1t-offline/cmssw/pull/1216
The model files needed by this NN are in the following PRs: https://github.com/cms-data/L1Trigger-VertexFinder/pull/1 and https://github.com/cms-data/L1Trigger-L1TTrackMatch/pull/1 

#### PR validation:

Previously under https://github.com/cms-l1t-offline/cmssw/pull/1191 the following validations were performed:
This PR passes the following checks: 
 scram b
scram b code-format 
scram b code-checks
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
time cmsRun L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py

### CODE REVIEW

**Comment by epalencia** [comment]
test parameters:
- pull_request = https://github.com/cms-data/L1Trigger-L1TTrackMatch/pull/1
- pull_request = https://github.com/cms-data/L1Trigger-VertexFinder/pull/1

**Comment by epalencia** [comment]
please test

**Comment by fwyzard** [comment]
> +code-checks
> 
> Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-44315/39335
> 
>     * This PR adds an extra 88KB to repository
> 
>     * Found files with invalid states:
>       
>       * L1Trigger/VertexFinder/data/Quantised_model_prune_iteration_9_weightModelgraph.pb:
>         
>         * Added: [d6364e8](https://github.com/cms-sw/cmssw/commit/d6364e86d7e655457796816c1259fa465d17b533)
>         * Deleted: [4231a75](https://github.com/cms-sw/cmssw/commit/4231a7504ef68b12536ef6245f83c3602d0b8b82)
>       * L1Trigger/L1TTrackMatch/data/Quantised_model_prune_iteration_9_associationModelgraph.pb:
>         
>         * Added: [d6364e8](https://github.com/cms-sw/cmssw/commit/d6364e86d7e655457796816c1259fa465d17b533)
>         * Deleted: [4231a75](https://github.com/cms-sw/cmssw/commit/4231a7504ef68b12536ef6245f83c3602d0b8b82)
>       * L1Trigger/VertexFinder/data/Quantised_model_prune_iteration_9_patternModelgraph.pb:
>         
>         * Added: [d6364e8](https://github.com/cms-sw/cmssw/commit/d6364e86d7e655457796816c1259fa465d17b533)
>         * Deleted: [4231a75](https://github.com/cms-sw/cmssw/commit/4231a7504ef68b12536ef6245f83c3602d0b8b82)
> 
>     * There are other open Pull requests which might conflict with changes you have proposed:
>       
>       * File  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py  modified in PR(s): [Triplet emulator 14 0 0 pre3 #43998](https://github.com/cms-sw/cmssw/pull/43998)

Please squash the commits, so that files are not added and removed.

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

- Reviewed by L1 in https://github.com/cms-l1t-offline/cmssw/pull/1191 & https://github.com/cms-l1t-offline/cmssw/pull/1216

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
