### PR TITLE
Remove MessageLoggerHeader from SimDataFormats headers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Removed the use of FWCore/MessageLogger/interface/MessageLogger.h from SimDataFormats headers. Only one of the headers actually used MessageLogger and for that one it was actually more consistent to throw an exception instead.

#### PR validation:

The code and all of its dependencies compile.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/analysis-l2 @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
