### PR TITLE
Dark SUSY and displaced lepton monitoring

### PR DESCRIPTION
**Pull request by gomber**
Hi All, 

Here is the PR same as #19499 but in CMSSW_92X release as requested by @mtosi .

Regards
Bhawna

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by gomber** [comment]
@davidlange6 nbins used by this code : there are 12 histograms which takes 5961 bins and then there are 11 instances of it, so in total this code has 65571 bins. With this, I guess I provided all the information, if so could you please merge the PR?

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
@gomber can you check if this PR is included #19961 ?

**Comment by gomber** [comment]
@fwyzard even this PR is also included in 19961, as I can see the MuonMonitor.cc and .h file as the files committed too.  It's just in the first message in 19961 thread, the PR number is not included.

**Comment by fwyzard** [comment]
OK, thanks.

Can you close this PR then ?

**Pull request closed without merging**
