### PR TITLE
CMT/RMT preparation for Run3

### PR DESCRIPTION
**Pull request by zhokin2**
#### PR description:
CMT: new plots regarding GlobalRMT added; 
tiny update of some titles;
update of condor related scripts;

RMT: update on scripts to run crontab using local runs;
psm-plots added: update on macros;
general cc-code was changed with energy-eraw exchange for HBHE;

#### PR validation:
I've used the commands:

scram build code-checks
scram build code-format
scram b

and testing all scripts on real data

### CODE REVIEW

**Comment by zhokin2** [comment]
code-format done for 4 files

**Comment by jfernan2** [comment]
@zhokin2 can you please add a meaningful title to the PR?

**Comment by jfernan2** [comment]
Thanks @abdoulline 
However, this should be mentioned in the description along with a proper title name, Moreover, it would be good to squash the 61 commits into a single one for tidiness

**Comment by abdoulline** [comment]
@jfernan2    I meant that many PR suffer from the very same issue, so rewievers request 36021...

I agree, all these tens of commits better go in one.
And the title to be edited to give some meningful form...

**Comment by abdoulline** [comment]
@zhokin2 
http://cms-sw.github.io/faq.html
Chapter "How do I collapse multiple commits into one?"

**Comment by zhokin2** [comment]
in BuildFile the following lines were added:

"CondFormats/HcalObjects"/>
"CondFormats/DataRecord"/>
"DataFormats/L1GlobalTrigger"/>
"Geometry/Records"/>
"Geometry/CaloTopology"/>
"Geometry/HcalTowerAlgo"/>

to overcome RelVals Exception Message:
Unable to find plugin 'EcalBarrelGeometryEPdd4hep'

**Comment by zhokin2** [comment]
> @zhokin2 http://cms-sw.github.io/faq.html Chapter "How do I collapse multiple commits into one?"

thanks for link. It's better to do that after almost all commits will be done.

**Comment by zhokin2** [comment]
updates on use of TFileService: rmt/cmr scripts were corrected

**Comment by zhokin2** [comment]
sorry, I forgot to apply code-format check to plugins/CMTRawAnalyzer.cc

**Comment by zhokin2** [comment]
Tiny update on 2 txt files, and
I've tried to rewrite very often history of commits using:
git reset --soft da3cbc6a8d528e98f9a8c86e45967a2f6eb09901
git commit --amend

**Comment by jfernan2** [comment]
@zhokin2 if you are done with commits, could you squash them into a single one please?

**Comment by zhokin2** [comment]
> 
> 
> @zhokin2 if you are done with commits, could you squash them into a single one please?

I did that 4 days ago as:
git reset --soft da3cbc6
git commit --amend

**Comment by jfernan2** [comment]
I am sorry but git declares 85 commits for this PR....

**Comment by abdoulline** [comment]
@zhokin2   did you edit the txt file opened by 
    git commit --amend

It opens a txt file with your editor, containig the commented info and a list of all the (85) commits, so you have to add some meaningful comment at the beginning of the file before the following lines: 
 
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# 
#
<...>

**Comment by zhokin2** [comment]
someting was wrong from my side - thanks , now it's corrected for sure: git log do not show 85 commits

________________________________

**Comment by abdoulline** [comment]
Well,  I don't see anything changed on the github... 
https://github.com/cms-sw/cmssw/compare/master...zhokin2:12_2_0_pre1_CMTforRun3?expand=1

A naive questions: did you "push" the changes:
 git push my-cmssw 12_2_0_pre1_CMTforRun3

**Comment by zhokin2** [comment]
Sorry, now git push done as well
________________________________

**Pull request closed without merging**
