### PR TITLE
Phase2 hgx352A: Add possibilities of more scenarios in some of the checks of G4 Components

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add possibilities of more scenarios in some of the checks of G4 Components

#### PR validation:

Tested with existing scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob @subirsarkar Please approve this PR

**Comment by srimanob** [comment]
Note to @civanch @bartosik-hep 

Not related to this PR, but should be fixed if it is a real issue. There are two points where potential memory leak are reported.

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2024-01-30-1100/src/Geometry/TrackerCommonData/plugins/DDPixFwdRotation.cc:130:9: warning: Potential leak of memory pointed to by 'rpCN' [cplusplus.NewDeleteLeaks]
  130 |   DDrot(DDName(rotNameNippleToCover_, rotNS_),
on `DDName(rotNameNippleToCover_, rotNS_`

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2024-01-30-1100/src/SimG4Core/PrintGeomInfo/plugins/PrintMaterialBudgetInfo.cc:109:14: warning: Potential memory leak [cplusplus.NewDeleteLeaks]
  109 |   theTopPV = G4TransportationManager::GetTransportationManager()->GetNavigatorForTracking()->GetWorldVolume();
  on `G4TransportationManager::GetTransportationManager()`

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Kindly integrate this

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
@bsunanda 

I think this PR is causing unit test errors, as seen in https://github.com/cms-sw/cmssw/pull/43856#issuecomment-1925423119
After mergin locally this PR on top of `CMSSW_14_0_X_2024-02-02-2300` results in:

```
$ scram b runtests_test2026Geometry
>> Local Products Rules ..... started
>> Local Products Rules ..... done
Creating test log file logs/el9_amd64_gcc12/testing.log
Fail    0s ... Configuration/Geometry/test2026Geometry
```

**Comment by bsunanda** [comment]
Thanks Marco. I have provided a fix in the PR #43862
________________________________

**Pull request merged**
