### PR TITLE
Run3-hcx279 Use ESGetToken and utilize more advised computing styles

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken and utilize more advised computing styles

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@bsunanda  Thank you!

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
