### PR TITLE
Phase2-gex177 Make a new PR to have the geometry scenario ExtendedGeometry2026D110 which represents T35+C18+M11+I17+O9+F8

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a new PR to have the geometry scenario ExtendedGeometry2026D110 which represents T35+C18+M11+I17+O9+F8. 

#### PR validation:

Tested with the workflow 29634.0 in runTheMatrix where this scenario is used

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backported to CMSSW version 14_0_X using #44494

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@sunilUIET Please approve this PR

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
It seems there is unit test failure with the new workflow test in master. Test is on-going, I don't see the detail of failure yet.
I propose to wait until the master PR is merged first.

**Comment by civanch** [comment]
@srimanob , if you mean #44497 , there is a DAS problem. This PR seems to be clean.

**Comment by srimanob** [comment]
Hi @civanch 
I just wait until the test of https://github.com/cms-sw/cmssw/pull/44494 done, and see result.

**Comment by srimanob** [comment]
@cmsbuild please test workflow 29634.0

Just to complete the test. The master PR is signed already.

**Comment by srimanob** [comment]
+Upgrade

New workflow runs fine.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
