### PR TITLE
Lhe producer update - DYToll and WTolNu

### PR DESCRIPTION
**Pull request by joonblee**
DYToll and WjetsTolNu(LO) samples have no event. Thanks to Alexander, it needs some updates on LHEProducer.

### CODE REVIEW

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by joonblee** [comment]
Hi David,

Thanks for your comment! In fact this is the first time, I use the cms pull request. It makes the mistake.

If I want to pull request on CMSSW_9_4_0, then I need to choose a base as CMSSW_9_4_0. Is it right?

Best regards,
Joonbin

________________________________
보낸 사람: David Lange [notifications@github.com]
보낸 날짜: 2017년 11월 23일 목요일 오후 2:48
받는 사람: cms-sw/cmssw
참조: Joon Bin Lee; Mention
제목: Re: [cms-sw/cmssw] Lhe producer update - DYToll and WTolNu (#21441)


Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by agrohsje** [comment]
Dear Joonbin,

please just change the 4 lines in these 2 files: 
Configuration/Generator/python/DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py
Configuration/Generator/python/WTolNu01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff.py

Cheers, Alexander.

**Comment by perrozzi** [comment]
the master is now 10_0_X, you can probably use CMSSW_10_0_0_pre1

**Comment by perrotta** [comment]
-1
(Just to remove this from the reco list)

**Comment by kpedro88** [comment]
-1

**Comment by Martin-Grunewald** [comment]
-1

**Pull request closed without merging**
