### PR TITLE
Logging service for Condition Workflows - port to 11_1_X

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:
 We are adding a new service to provide recollection of log messages, with the aim to store them in the database, related to the condition data stored in the same context.

The target and main use case for this implementation are the workflows providing the lumi-based conditions for HLT.

#### PR validation:

A dedicate unit tests validates the base Logger. Two integration tests are exercising the use case with an Oracle db destination.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Port of #31667 to 11_1_X branch, to allow the integration in the online operation during MWGR

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by christopheralanwest** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
