### PR TITLE
EventFilter/CSCRawToDigi: Cleanup for the following clang warnings. Remove ununsed function.

### PR DESCRIPTION
**Pull request by gartung**
Reverts cms-sw/cmssw#22468

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
@gartung did you want to do the revert so that we get the clang warning in order to remind us to do a proper fix in the future?

**Comment by gartung** [comment]
Yes. DXR reports that this function is never called by any of the subclasses.

**Comment by Dr15Jones** [comment]
Then how about just removing it all together?

**Comment by gartung** [comment]
Will do that now.

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22513	e93a52f
- removal of unused function.
- jenkins tests pass (compilation is enough)

@gartung please edit the PR title to be more representative of the change

**Comment by fabiocos** [comment]
+1

**Pull request merged**
