### PR TITLE
New Calibration for D11 Geometry

### PR DESCRIPTION
**Pull request by atricomi**
New cluster shape calibrations have been produced to take into account of the axis orientation in the T5 Tracker Geometry (barrel pixel geometry)

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
assign upgrade

**Comment by slava77** [comment]
@atricomi 
does this new shape calibration work OK with T3?

I think that we need both efficiency/fake plots and timing estimates on PU200 before this can be signed off.

**Comment by boudoul** [comment]
hello @slava77 - T3 is going to be deprecated  - We just discuss this at the UPSG meeting - Therefore we should focus our attention to T5 now (cleaning of the T3 to make it deprecated will come in a separated PR) - Thanks

**Comment by slava77** [comment]
On 5/10/17 5:45 AM, boudoul wrote:
> hello @slava77 <https://github.com/slava77> - T3 is going to be
> deprecated - We just discuss this at the UPSG meeting - Therefore we
> should focus our attention to T5 now (cleaning of the T3 to make it
> deprecated will come in a separated PR) - Thanks

Do we have relvals already made and signed off with T5?
Please confirm.
Thank you.

**Comment by atricomi** [comment]
T3 will be deprecated soon @boudul to confirm
PU samples are not yet available in RelVal as soon as they will be available I will produce plots.

You can have a look at 
https://atricomi.web.cern.ch/atricomi/910pre3_NewClusterShape/SingleMuPt10/ <https://atricomi.web.cern.ch/atricomi/910pre3_NewClusterShape/SingleMuPt10/>
and
https://atricomi.web.cern.ch/atricomi/910pre3_NewClusterShape/TTBar/ <https://atricomi.web.cern.ch/atricomi/910pre3_NewClusterShape/TTBar/>

for validation wo PU

**Comment by VinInn** [comment]
I hope that T5 RelVal are NOT signed off... for pre3

**Comment by slava77** [comment]
@atricomi 
now I also notice that this is a 91X PR.
Do you and UPSG want to delay 91X release and have this PR included in the TDR release?

**Comment by slava77** [comment]
in any case, please create a PR for 92X, since integration starts there.

**Comment by VinInn** [comment]
Please submit it to master as well!

**Comment by boudoul** [comment]
ok good point for 91X, I don't know but will inquire/ discuss with UPSG
In any case, please @atricomi , create a PR for master (I also missed that this one was for 91X)

**Comment by ebrondol** [comment]
We put the plots [here](https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_1_0_pre3_PR18658) and we will update the page when the pu sample are ready.

**Comment by kpedro88** [comment]
@boudoul will deprecation of T3 imply deprecation of T4 also? Will there be a need for T6 = T4 w/ extra disk?

**Comment by boudoul** [comment]
hi @kpedro88 , this is a good question - the main usage of T4 is related to the flat tracker for track trigger purpose (and therefore the config of the pixel is not relevant, since the track trigger occurs only in the outer part ) - so for sure no need for T6 as you are suggesting. Now the question of the removal of T4 should be adressed- I know that there will be discussion during the tracker week (next week) where presumably we will get answer to this question

**Comment by VinInn** [comment]
Has this been submitted to master (sorry cannot find it)?
what the plan to merge in master?: clearly any development base on D11 requires this PR...

**Comment by atricomi** [comment]
Hi Vincenzo

PR #18663 should be the one in the master.

**Comment by slava77** [comment]
I was waiting for tests with PU.

**Comment by atricomi** [comment]
Hi Slava
we are waiting for the PU samples. They are arriving. Asap we will let you know

**Comment by slava77** [comment]
@kpedro88 is this development still needed for 91X?
Please clarify.
Thank you.
I guess we'll know better on Tuesday in the release planning.

**Comment by kpedro88** [comment]
I am also wondering that. I asked the UPS coordinators for their input.

**Comment by slava77** [comment]
@kpedro88 
one related question: was it intentional still to not have T5 in the jenkins PR tests?
Currently running D4, D8, D12, and D15 are all T3

**Comment by kpedro88** [comment]
@slava77 at the time I updated the matrix tests, the T3 vs T5 decision hadn't been made yet. Now apparently it has (in favor of T5), so the set of tests could be updated again. But maybe this can wait until T3 is officially deprecated.

**Comment by ebrondol** [comment]
I have produced the comparison for 10 events with ttbar+PU200: [link](https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_1_0_pre3_PR18658/)
The efficiency increase. Also does the fake, but not in the HP part: [link](https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_1_0_pre3_PR18658/TTbar_PU200/plots_highPurity/effandfake1.pdf)
where the effect is almost negligible. 
It can be double-checked later, the overall effect of this PR is very good and needed for any production with 910 release.

**Comment by slava77** [comment]
The following is based on 910pre3:
- Looking at muon gun events: increase in efficiency for T3 (D12 in plots below) appears to be more significant than for T5 (D14). In both cases the final eff is pretty close to 100%

T3/D12
wf24411d12tenmu_generalpt09_eff_eta

T5/D14
wf26211d14tenmu_generalpt09_eff_eta

For T5/D14 with PU200:
- efficiency increases  more significantly for "inclusive" tracks (this is quite similar to the no-PU sample posted here earlier in https://github.com/cms-sw/cmssw/pull/18658#issuecomment-300471229)
wf26434d14pu200_generalalltp_eff_eta

Fake rate is up somewhat moderately (well, it nearly doubles in eta ~0.8 region)
wf26434d14pu200_generalpt09_fake_eta

high purity is much more stable
wf26434d14pu200_hp_fake_eta

At higher level:
- electronGsfTracks yield is down by 14% , based on MTV plots it is all from fakes (efficiency plot is almost unchanged)
wf26434d14pu200_gsf_fake_eta

There is somewhat noticeable improvement in b-tagging performance (MVA v2 change is less impressive; so a part of this may be a fluctuation)
wf26434d14pu200_csvv2_lvb_roc

CPU time in PU200 is up overall by about 3%; 
- most of it is in iterative tracking which is up by about 10% (building steps are slower by 40% for pixelPair and by 15-20% for triplet steps and low-pt and detached quadruplet steps). This looks OK given the efficiency increase.
- electron tracking module times are down in total by about 10% (with no apparent loss in efficiency. Good.).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18658	7dafeac
- update in the pixel cluster shape files for phase-2
- jenkins tests pass and comparisons show differences only in phase-2 workflows
- local tested confirm expected behavior without bad side-effects for high-level reco, including improvements even for the T3 tracker which was not the main target of this update.
    - CPU time is up by 3% in PU200

**Comment by kpedro88** [comment]
+1
thanks to @slava77 for the careful review
todo: address deprecation of T3

**Comment by boudoul** [comment]
thanks @kpedro88 and @slava77 for the review, the deprecation of T3 is going to happen within a few days (for master ) , I delayed my homework a bit due to the ongoing tracker week

**Comment by davidlange6** [comment]
+1

**Pull request merged**
