### PR TITLE
update isSoftMuon( ) to use new soft muon Id 

### PR DESCRIPTION
**Pull request by dayongwang**
Update isSoftMuon( ) to use new soft muon Id . The changes affect only analyses and not RECO or data format.  This can be included whenever convenient.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Is the old isSoftMuon used by any Run1 analysis (published or ongoing)? it was added in spring of 2013, so, probably still a "standard Run1" selection until recently.
If so, maybe a different solution (a new function) would be better than just updating the old function.
make it isSoftMuonFroRun2 or smth like that.

**Comment by dayongwang** [comment]
@slava77 BPH is the main user of this function. The new soft ID has been the standard one since early 2014. Any new analyses are recommended use this since then. This has been communicated with and got approvals from Carlo and Daniele.

**Comment by battibass** [comment]
Hi @slava77 , just to confirm this: the "new" soft ID is the presently recommended version for Run-I analyses as well:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMuonId#Soft_Muon
The backport to 53X was done in agreement and with the supporto of BPH (@dayongwang is our BPH muon object expert).
The linked TWIKI points to a presentation of the "new" ID performance.

**Comment by slava77** [comment]
Carlo,
thanks for the confirmation.
It wasn't obvious if anyone else outside BPH is using this function (for vetoes or preselections or what not).

A plain search for "soft muon" in HN returns several entries in SMP, HIG, and SUS.
It's not clear from the context there if the MuonSelector functions were used or not and if the latest ones or the older one is still used.

**Comment by slava77** [comment]
(I care less about 7X at this point for this purpose)

**Comment by slava77** [comment]
@cmsbuild @nclopezo 
please check why the comparisons never completed.
Thanks.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8761	5fca1b9

changes in the code are consistent with that went to 7X cycle.
There are no changes from this code change in monitored quantities based on jenkins tests comparisons, which is expected (no DQM/Validateion  modules testing isSofMuon)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
