### PR TITLE
Fixes for the pMSSMFilter

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The PR #28201 has added a new GenFilter module, introducing anyway a problem in the IB CMSSW_11_1_X_2019-12-09-2300 as the module was erroneously places in the src directory, while now all the modules have been moved into the plugins directory.

I've taken the opportunity to turn the module into global as suggested by @makortel and fix a few coding style issues violating our rules.

#### PR validation:

The code now compiles correctly. Other changes are technical, an output validation should be performed by @mmrowietz and supervised by the GEN group @qliphy @agrohsje

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@mmrowietz @qliphy @agrohsje please have a look, I want to integrate this asap to fix the IB

**Comment by mmrowietz** [comment]
@fabiocos I have tested the filter output and it seems reasonable.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by qliphy** [comment]
+1

**Pull request merged**
