### PR TITLE
Standalone version of beamspot DIP client [12_3_X]

### PR DESCRIPTION
**Pull request by sikler**
#### PR description:

The DQM client version was alive only for the duration of the run, and DIP consumers want a steady presence of the beamspot product. This way, the client is now transfered back to a standalone executable, running forever, polling every second some beamspot and tracker status txt files on /nfshome0. To be placed likely in the startup of a local P5 machine, from where both the CMS-related DIP machine (cmsdimns1.cern.ch, cmsdimns2.cern.ch) and /nfshome0 are both visible and accessible.

#### PR validation:

Tested successfully on fu-c2f11-11-03, by looking at DIP-related pages to check proper placement of publications:
https://cmsonline.cern.ch/webcenter/portal/cmsonline/pages_common/dcs/dipbrowser [under dip/CMS/...]
https://ccde.cern.ch/nxcals/device/313400?subscriptionId=29210033
https://ccde.cern.ch/nxcals/device/1731503?subscriptionId=29407975
https://timber.cern.ch/query?tab=Visualization&configuration=38326

#### PR issues:

The process is polling two files:
 /nfshome0/dqmpro/BeamMonitorDQM/BeamFitResults.txt
 /nfshome0/dqmpro/BeamMonitorDQM/BeamFitResults_TkStatus.txt
where the latter has a very old timestamp (from 2018), so very likely the file related to tracker status is not written by any client. Any ideas?

### CODE REVIEW

**Comment by pmandrik** [comment]
Hi, @sikler ,

the only place of *TkStatus.txt files creation I found is [0] called by beam client [1]  where DIPFileName is 'BeamFitResultsOld.txt' at the moment. Probably beamhlt process workflow (where 'BeamFitResults.txt' is used) is needed to be updated with cms.EDAnalyzer("TKStatus").

[0] https://github.com/cms-sw/cmssw/blob/master/DQM/BeamMonitor/plugins/TKStatus.cc
[1] https://github.com/cms-sw/cmssw/blob/d30234439f449909c211a85d5e5c8b5554a0f7f7/DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py#L240

**Comment by emanueleusai** [comment]
please test

**Comment by smuzaffar** [comment]
@sikler , is it already in 12.4.X/master Ib?

**Comment by sikler** [comment]
> @sikler , is it already in 12.4.X/master Ib?

Hi, there is now a forward port to master at https://github.com/cms-sw/cmssw/pull/37835.

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37835

**Comment by emanueleusai** [comment]
testing at P5

**Comment by francescobrivio** [comment]
Hi Ferenc (@sikler) could you add an `.sh` script to be used to steer this code (if you have it available already of course)? Maybe something similar to the old java application in https://github.com/cms-sw/cmssw/blob/master/DQM/BeamMonitor/test/dip/runtest.sh ?

**Comment by sikler** [comment]
> Hi Ferenc (@sikler) could you add an `.sh` script to be used to steer this code (if you have it available already of course)? Maybe something similar to the old java application in https://github.com/cms-sw/cmssw/blob/master/DQM/BeamMonitor/test/dip/runtest.sh ?

Hi @francescobrivio , runtest.sh added to this and to master. Now possible to pass parameters.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
