### PR TITLE
Run3-gex113A Remove compilation warnings in CaloOnlineTools/EcalTools

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove compilation warnings in CaloOnlineTools/EcalTools

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * modernize `EcalTools` package
 * tests pass -- expect for the known issues

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
