### PR TITLE
Fix in PopCon worklow for empy files + DBOuputService clean up: back-port

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:
This fix follows the recent changes in DbOutputService, that have removed the implicit schema creation. Since no db is created when no IOV insertion is requested, the PopCon workflow requires now an explicit call. In any case, non-emtpy files with 0 IOVs are still ignored.

We are also removing commented code and printouts left over.

#### PR validation:

Package Unit and Integration tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

#30006 
#30090

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
