### PR TITLE
Run3-sim108 Use of the modifier run3_geomOld to use GT's with old geometry versions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use of the modifier run3_geomOld to use GT's with old geometry versions

#### PR validation:

Use the new cfg's to test old and new geometries from DB

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta @civanch @cvuosalo Here are examples of using old and new geometries with those from DB. Just wondering if such examples be there for the CMSSW version 12_2_X?

**Comment by perrotta** [comment]
Thank you @bsunanda 
Yes, I think that something that certifies the possibility of running with the "old" geometry also in 12_2 can be useful. 
Looking at the examples, I have the impression that it is not as simple as switching a modifier: did I understand something wrong, that the old geometry should have been enabled by a modifier?

**Comment by bsunanda** [comment]
Essentially it is a combination of adding the modifier and asking for the right GT. I changed something more so that I can compare the new and old GT's at the same time

**Comment by bsunanda** [comment]
I am adding a modifier so that one can use a cmsexec command to create the workflow

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
I think that an argument to backport may be following: the "old" geometry was used for high statistic validations of DD4hep migration, having an opportunity to compare "old"/final geometries for possible investigation in an emergency situation may be needed.

**Comment by perrotta** [comment]
@bsunanda @civanch maybe it's me, but I am confused about the purpose of this PR.
In my expectation, I would like to be able to process a given workflow, for example with runTheMatrix, and the same workflow use either the updated or the "old" Run3 geometry depending on whether the `run3_geomOld` modifier is included or not.

If we are not able to do so we cannot say that with one switch we can change all workflows from using either one geometry or the other.

I don't think this PR goes in that direction, and it makes me even doubt that we can actually use that modifier to make a simple switch.

When I asked at the meeting, the answer was that we can switch between the "old" and the "new" run3 geometry with a modifier. Could you please show us that it is actually the case? I.e. that the very same workflow can be run with either the "old" and the "new" geometry? After that, the outputs of the two jobs can also be compared to check for the differences,

**Comment by bsunanda** [comment]
I shall close this
________________________________

**Comment by bsunanda** [comment]
Running with the old geometry is no longer required for any validation work. So this PR is not  necessary

**Pull request closed without merging**
