### PR TITLE
Phase2 tracking validation and DQM in 81X 

### PR DESCRIPTION
**Pull request by ebrondol**
This is an update and rebase of the PR #14735 .
I have tested it on top of the PR #14756 .

@boudoul @makortel please have a look again at the final changes.
@delaere @VinInn @rovere @kpedro88

### CODE REVIEW

**Comment by makortel** [comment]
@ebrondol Looks good to me, thanks.

**Comment by cvuosalo** [comment]
Running upgrade workflow 10600.0_FourMuPt1_200 with 10 events against baseline CMSSW_8_1_X_2016-06-09-1100 (which contains #14756) shows a difference in RECO event content. l1extraParticles and edmConditions get removed, as shown below.

Are these changes intended?

```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
    255.0 ->         0.0       -255     OLDO  -0.09     edmConditionsInEventBlock_conditionsInEdm__RECO.
    261.0 ->         0.0       -261     OLDO  -0.09     l1extraL1JetParticles_l1extraParticles_IsoTau_RECO.
    249.4 ->         0.0       -249     OLDO  -0.09     l1extraL1HFRingss_l1extraParticles__RECO.
    259.0 ->         0.0       -259     OLDO  -0.09     L1GlobalTriggerObjectMaps_l1L1GtObjectMap__RECO.
    280.3 ->         0.0       -280     OLDO  -0.10     l1extraL1EtMissParticles_l1extraParticles_MET_RECO.
    262.4 ->         0.0       -262     OLDO  -0.09     l1extraL1JetParticles_l1extraParticles_Forward_RECO.
    273.4 ->         0.0       -273     OLDO  -0.10     l1extraL1EtMissParticles_l1extraParticles_MHT_RECO.
    266.2 ->         0.0       -266     OLDO  -0.09     l1extraL1EmParticles_l1extraParticles_NonIsolated_RECO.
    262.4 ->         0.0       -262     OLDO  -0.09     l1extraL1JetParticles_l1extraParticles_Central_RECO.
    371.8 ->         0.0       -372     OLDO  -0.13     l1extraL1MuonParticles_l1extraParticles__RECO.
    271.0 ->         0.0       -271     OLDO  -0.10     l1extraL1EmParticles_l1extraParticles_Isolated_RECO.
    264.6 ->         0.0       -265     OLDO  -0.09     l1extraL1JetParticles_l1extraParticles_Tau_RECO.
-------------------------------------------------------------
   285032 ->      281762      -3271            -1.1     ALL BRANCHES
```

**Comment by Martin-Grunewald** [comment]
l1extra particles do no longer exist in the stage-2 L1T.

**Comment by cvuosalo** [comment]
+1

For #14827 b1e7e5b51b8723c028aa402d40a2ad071cfd5f86

Adding DQM and validation for Phase 2 tracking. There should be no change in standard workflows.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-06-09-1100 show no significant differences, as expected. A test of upgrade workflow 10600.0_FourMuPt1_200 with 10 events against baseline CMSSW_8_1_X_2016-06-09-1100 (which contains #14756) shows that the DQM/validation step now runs successfully and that there are no significant differences in RECO quantitiies, except for the expected loss of some obsolete data elements as discussed above.

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@hengne @davidlange6 - please review and sign ASAP, we would like to get this into pre7

**Pull request merged**
