### PR TITLE
PostLS2 beampipe for Phase2

### PR DESCRIPTION
**Pull request by kpedro88**
This PR uses the postLS2 beampipe introduced in #15693 for the Phase2 geometries. Correspondingly, Castor and Totem are removed from the geometries. The removal of Castor requires several customizations, which are added to the `phase2_common` Era.

I also did a bit of reorganization in `Configuration/Geometry` based on an earlier comment from @ianna.

Unfortunately, I could not figure out a nice way to get Eras to remove EDAlias modules, so the deprecated `isChosen` feature is used for now.

@boudoul, this will conflict with #15662, so one of us will have to rebase at some point.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 @Dr15Jones let me know if you have a better way to remove an EDAlias with Eras

**Comment by kpedro88** [comment]
also @civanch can you check if Castor needs to be disabled manually in the SIM step, even when the sensitive volume is removed?

**Comment by davidlange6** [comment]
@kpedro88 - no answer from @civanch it seems - I think your change to the digi step is sufficient here (and there are no complaints in the log). Will merge and let @civanch catch up if needed.

**Comment by kpedro88** [comment]
@boudoul FYI, now that this is merged (should show up in 2300 IB), #15662 needs to be rebased - make sure you regenerate the D4 geometry file from the script so it picks up the changes here.

**Comment by boudoul** [comment]
Thanks . I about to take a plane so probably not before tomorrow. ..

-------- Original message --------

**Comment by kpedro88** [comment]
@boudoul that's okay, there may be another conflicting PR by then :)

**Comment by boudoul** [comment]
Yeah I know ☺ no problem.

-------- Original message --------

**Pull request merged**
