### PR TITLE
Changes from clang format on Core DataFormats packages

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

The first commit includes only changes from scram build code-format-all (clang format) and nothing else. This PR includes all the packages in the DataFormats subsystem managed by the Core group.

There were a few addition changes that showed up in code-checks in the second commit.

#### PR validation:

The only test I performed was checking that the revised packages compile and build.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
