### PR TITLE
unit test of `L1TGlobalProducer` and small technical updates to `GlobalBoard`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is a follow-up of #39464. It adds a unit test for the `L1TGlobalProducer` plugin, and applies small technical updates to the class `GlobalBoard`, including the ones discussed in #39817.

Because of the new unit test, this PR is tied to a `cms-data` update: https://github.com/cms-data/L1Trigger-L1TGlobal/pull/13.

Merely technical. No changes expected in the outputs of PR tests.

Attn: @elfontan 

#### PR validation:

The new unit test passes in local tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - pull_requests = https://github.com/cms-data/L1Trigger-L1TGlobal/pull/13

**Comment by missirol** [comment]
please test

**Review by missirol — COMMENTED** [review]
I added comments inline to guide the review.

**Comment by rappoccio** [comment]
@cecilecaillol can you also sign the cms-data PR? https://github.com/cms-data/L1Trigger-L1TGlobal/pull/13 

Thanks!
Sal

**Comment by rappoccio** [comment]
+1

* Discussed at ORP, can go into pre4.

**Pull request merged**
