### PR TITLE
[L1T] Backport - L1T modules/sequences/tasks renaming

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/39244

Addressing item 1 of https://github.com/cms-sw/cmssw/issues/39194: change L1 modules to start with l1t, sequences and tasks with L1T
Also addressing item 2 of the same issue: Fix hltTriggerSummaryAOD
Also addressing item 5 of the same issue: Verify the PSet cutset in L1TrackSelectionProducerExtended

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39244

**Comment by mandrenguyen** [comment]
please test

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by emanueleusai** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by missirol** [comment]
+hlt

 - verbatim backport

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
