### PR TITLE
DQMOffline/Lumi zcounting backport of PR #40815 [CMSSW_13_0_X]

### PR DESCRIPTION
**Pull request by davidwalter2**
This is a backport of PR #40815
The backport is needed because we want the changes in DQMOffline to be active in the upcoming data taking period in 2023

### CODE REVIEW

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40815

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
relvals timed out. Let's retest

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
@emanueleusai those RelVal-Input relvals will keep failing, as they do in the IBs, until https://github.com/cms-sw/cmssw/issues/40889 is not fixed.
Please make your review based on the other tests and comparisons for te time being

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
