### PR TITLE
Phase2-gex173 Make 2 changes: eta sizes for GE21; Size of Tracker volume to touch CALO and BeamPipe volumes on either side

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make 2 changes: eta sizes for GE21 and size of Tracker volume to touch CALO and BeamPipe volumes on either side. Modify the scenarios 2026D100 and 2026D101; rename them as 2026D102 and 2026D103. Modify the scenarios 2026D98 and 2026D99 with the changes in muon and tracker region and name them 2026D100 and 2026D101. Also, provide the workflows for all these new scenarios. 

#### PR validation:

Checked the overlaps in the new 4 scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special. Only new scenarios are added - the workflows are not yet defined

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

problem of 4.76 not connected with this PR.

**Comment by civanch** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
test parameters:
- workflows = 25634.0,26034.0,26434.0,26834.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
FYI
@emiglior for new trackers
@fabiocos for updating MTD
@cms-sw/muon-dpg-l2 for updating muon geometry

**Comment by fabiocos** [comment]
@bsunanda @srimanob concerning the Geant4 navigation behaviour, #43142 takes care of this possible change. On top of this, I realize that I've never paid attention to the default valuie for a given geometry, for FastTiming it would be better to set it to 16 in https://github.com/cms-sw/cmssw/blob/a4206ebcbc639fc784614bf1cc2b0007c97e2310/Configuration/Geometry/python/dict2026Geometry.py#L873 

It could be done in this PR, or I can do it afterwards.

**Comment by emiglior** [comment]
@bsunanda just to be sure: could you confirm that the only CMS geometry with 3D split sensors left in CMSSW will be T35/D102?
@bartonaz @Raffaella07

**Comment by bsunanda** [comment]
@Srimanob please sign this

**Comment by bsunanda** [comment]
@emiglior @bartonaz @Raffaella07 Yes it is the only one. The earlier D100 is moved to D102 and D101 is moved to D103. This is to allow D98 to become D100 with the correction and D99 to become D101.

**Comment by srimanob** [comment]
+Upgrade

New/adjusted workflows run fine.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
