### PR TITLE
2018 HLT HIon menu V1.1

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
New 2018 HLT HIon menu V1.1
Based on CMSSW_10_3_0_pre6.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #25166

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
For addOnTests.py

**Comment by Martin-Grunewald** [comment]
Yes, correct!

**Pull request merged**
