### PR TITLE
7_4_X_alcarecostream_nophisym

### PR DESCRIPTION
**Pull request by bmarzocc**
Fix the ALCARECOstream workflow removing AlCaEcalCalPhiSym. The reconstruction will be done privately during the phisymmetry calibration step.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by bmarzocc** [comment]
Same changes for 75X in PR #8678 have already been merged, do we need dedicated discussion for 74X merging?

**Comment by mmusich** [comment]
+1

**Comment by franzoni** [comment]
+1
in the matrix, removing the EcalCalPhiSym cannot harm, if so ECAL+Alca want

**Comment by davidlange6** [comment]
+1

**Pull request merged**
