### PR TITLE
[14_0] CICADA-uGT emulator additions

### PR DESCRIPTION
**Pull request by aloeliger**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/44222

Also backports elements of https://github.com/cms-sw/cmssw/pull/43799 (already merged) necessary to get the aforementioned working. 

This is being backported to because it may be necessary for online running on the next menu

Original description:

> This PR adds the uGT half of the CICADA -> uGT emulator chain. It adds all the pieces needed to parse and compare the new CICADA condition added in uTM v 0.12.0. This is being opened in draft because no unpacker/packer combo is available yet, but will be added after I have had the chance to speak to experts about reading the CICADA record.
> 
> Depends on utm version 0.12.0

Note that the unpacker **_has_** been added to this PR however.

#### PR validation:

All code has been validated in the original production release

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport meant for CMSSW_14_0 for online running

### CODE REVIEW

**Comment by aloeliger** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/44222

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
assign HLT
- They probably want to sign here as with the original PR.

**Comment by aloeliger** [comment]
assign hlt

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
urgent

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
