### PR TITLE
PPS: preparation for 2022 conditions

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR contains three updates:
   1) 2022 settings for "direct" simulation of forward protons in PPS, in particular the updated LHC optics estimate from https://github.com/cms-data/CalibPPS-ESProducers/pull/5
   2) For easier maintenance, all optics settings are grouped in one single python config ``CalibPPS/ESProducers/python/ctppsOpticalFunctions_non_DB_cff.py`` - also useful for workflows which do not consume conditions from DB.
   3) The alignment file ``Validation/CTPPS/alignment/alignment_2022.xml``, wrt. the 2021 version, contains constants adjusted to counteract a shift recently induced by the new Run3 geometry.

#### PR validation:

The plots below compare results before (blue solid) and after this PR (red dashed):
  * for Run2 data reco: [reco_cmp.pdf](https://github.com/cms-sw/cmssw/files/7121409/reco_cmp.pdf) -- no difference as expected
  * for direct simulation: [dirsim_cmp.pdf](https://github.com/cms-sw/cmssw/files/7121407/dirsim_cmp.pdf) -- no difference for 2021 and older, new curves (thus only in red dashed) for 2022 - as expected

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-data/CalibPPS-ESProducers/pull/5

**Comment by smuzaffar** [comment]
looks like a bugin filename checking part of bot. I will fix it and re-run the check here soon

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
Hi @jan-kaspar,

> 1. 2022 settings for "direct" simulation of forward protons in PPS, in particular the updated LHC optics estimate from [optics for Run3 (prelim.) cms-data/CalibPPS-ESProducers#5](https://github.com/cms-data/CalibPPS-ESProducers/pull/5)
> 2. For easier maintenance, all optics settings are grouped in one single python config `CalibPPS/ESProducers/python/ctppsOpticalFunctions_non_DB_cff.py` - also useful for workflows which do not consume conditions from DB.

do I understand that correctly that they conditions are not expected to change and that's why you choose them to be external root files?

> 3. The alignment file `Validation/CTPPS/alignment/alignment_2022.xml`, wrt. the 2021 version, contains constants adjusted to counteract a shift recently induced by the new Run3 geometry.

Kind of the same question: won't the alignment of PPS change over time and so it should not be read from an xml file?

**Comment by jan-kaspar** [comment]
Hi @tvami ,

the optics and alignment related to this PR reflect the current forecast for Run3 and are intended for preparatory simulations. It is almost clear that in reality both the optics and alignment will be different. These conditions will be deduced from real data and will go to DB for the use in reconstruction. Drawing from the Run2 experience, the optics is expected to be stable (for a year or so) while the alignment may evolve a little fill by fill.

For the (direct) simulation, in Run2, we had to prepare a limited number of profiles (2 or 3 per year) which could reasonably reproduce the data. Given the small number of profiles we kept the optics files in the external repo and the alignment files in CMSSW. If preferable, both can be stored in DB for Run3. In Run2 we rarely (if ever) updated these conditions.

**Comment by tvami** [comment]
Hi @jan-kaspar if there are ~3 updates per year, I'd say it's already a good motivation to move to the DB. What do you @francescobrivio @malbouis think?

**Comment by jan-kaspar** [comment]
> Hi @jan-kaspar thanks for the explanation! If there are ~3 updates per year, I'd say it's already a good motivation to move to the DB. What do you @francescobrivio @malbouis think?

OK, thanks! I will pass your recommendation to those who will take over from me next year.

**Comment by jfernan2** [comment]
+dqm

**Comment by mrodozov** [comment]
you'll need https://github.com/cms-sw/cmsdist/pull/7282 merged before this

**Comment by tvami** [comment]
+alca

 * agreed to move the files to the DB for the future

**Comment by qliphy** [comment]
+1

**Pull request merged**
