### PR TITLE
Cosmic muon validation

### PR DESCRIPTION
**Pull request by abbiendi**
This PR adds a complete validation of muon tracks for cosmics reco plus a few fixes to the general muon validation.

For cosmics an equivalent code has been used to obtain the validation plots attached to the PR #7044 https://github.com/cms-sw/cmssw/pull/7044

The cosmics validation sequence could be used to implement a standard validation on cosmics processes in runTheMatrix (7.0, 1307.0 - this is left open)

Backport to 74X (straightforward) should follow this PR

Some details:
- for cosmics validation some changes to common tools with TRK are necessary. This does not break anything as currently there is no validation for cosmics in CMSSW.
- some fixes to muon validation has been added:
- validation plots of reco quantities only for signal-matched muons (useful to remove contamination from PU to the interesting quantities, and to validate samples produced with premixing)
- technical improvements (still only a first set, more to come) reducing the cpu footprint of muon validation
- fix the indentation in MuonTrackValidator (broken since 620 !)
- minor fixes to log messages

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
@abbiendi:

The Jenkins tests "Comparison with the baseline" alternative-comparisons show a lot of differences. It seems that numerous muon tracks have disappeared. From the description of this PR, one would not expect it to change muon reconstruction. It looks like the only reco change is to add more log messages. 

Could you please look at the following plots and say whether these changes are expected for this PR?

For workflow 5.1_TTbar+TTbar, it apears that 148 of 152 muon probeTrks have been lost:
5 1-select

For workflow 25.0_TTbar+TTbar, 4 of 9 muon displacedTrks have disappeared:



25 0_select9
For the same workflow, 2 of 6 standalone muons have disappeared:
25 0_select426
25 0_select679

**Comment by abbiendi** [comment]
Hi Carl,

this is expected, due to the change at line:
https://github.com/abbiendi/cmssw/blob/cosmicMuonValidation/Validation/RecoMuon/plugins/MuonTrackValidator.cc#L680

The tpSelector added to the matching condition says that only reco tracks that are matched to a selected TrackingParticle are included in the plots of reco quantities. Among other things the selected TP have to be muons (pdgid=+/-13) and have to come from signal events (not PU). The probe tracks are just generalTracks with only kinematical selections (pt>4...) but no muon id, then many of them do not pass the condition.
The same can happen to true muons coming from PU.

I have indicated this change in the description of the PR
"validation plots of reco quantities only for signal-matched muons (useful to remove contamination from PU to the interesting quantities, and to validate samples produced with premixing)"
although I had in mind more the PU muons than the probe tracks.
Anyway it is an intended change. I will have a look to workflows relevant for muons at next usable validation cycle.
It is expected to solve one problem in validation of events made with premixing, where the PU particles have no TP in the event.

   Giovanni


On Mar 15, 2015, at 10:49 PM, Carl Vuosalo wrote:


@abbiendi<https://github.com/abbiendi>:

The Jenkins tests "Comparison with the baseline" alternative-comparisons show a lot of differences. It seems that numerous muon tracks have disappeared. From the description of this PR, one would not expect it to change muon reconstruction. It looks like the only reco change is to add more log messages.

Could you please look at the following plots and say whether these changes are expected for this PR?

For workflow 5.1_TTbar+TTbar, it apears that 148 of 152 muon probeTrks have been lost:
[5 1-select]<https://cloud.githubusercontent.com/assets/5736159/6658280/5593060a-cb64-11e4-8587-be6385921730.png>

For workflow 25.0_TTbar+TTbar, 4 of 9 muon displacedTrks have disappeared:

[25 0_select9]<https://cloud.githubusercontent.com/assets/5736159/6658296/ca84520c-cb64-11e4-804d-6eef5320bb02.png>
For the same workflow, 2 of 6 standalone muons have disappeared:
[25 0_select426]<https://cloud.githubusercontent.com/assets/5736159/6658303/1e364130-cb65-11e4-8724-cfb71bcea817.png>
[25 0_select679]<https://cloud.githubusercontent.com/assets/5736159/6658305/22218db8-cb65-11e4-8659-e23e25d26ef1.png>

**Comment by cvuosalo** [comment]
+1

For #8199 accc3ff5301709efb620f27f408d5d5e22c749f2

This PR enhances cosmic muon validation. It also removes low-quality, unmatched muon tracks from validation plots since such tracks are often from PU or fake muons.

The code changes are satisfactory, as are the Jenkins test [results] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8199/2215/summary.html). The Jenkins comparison with baseline CMSSW_7_5_X_2015-03-11-1400 shows no significant differences except for the expected loss of unmatched muon tracks from the validation plots, as shown and discussed in comments above.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
