### PR TITLE
[Backport of] HCAL: Bugfix of PFA1' Trigger Primitive algo by removing peak-finder

### PR DESCRIPTION
**Pull request by Michael-Krohn**
#### PR description:

Removing the peak-finder when the FIR filter, PFA1', is running to reconstruct the TP energy. This is to match what is in the firmware on detector. Also, on detector the peak-finder is only run when PFA2 is enabled, which has been implemented in this modification.

#### PR validation:

A basic technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of PR https://github.com/cms-sw/cmssw/pull/38488 to 124X, in order to make s/w match f/w.

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by perrotta** [comment]
@cecilecaillol @epalencia please consider signing if you want this in 12_4_1: I think this should be included in the MC production release 12_4_1

**Comment by perrotta** [comment]
urgent

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
backport of PR https://github.com/cms-sw/cmssw/pull/38488

**Comment by perrotta** [comment]
+1
- It can be merged, as it shouldn’t affect the PU libraries, as confirmed by PPD in a e-mail thread

**Pull request merged**
