### PR TITLE
Next HLT menu candidate (online and MC production) - 81X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Next HLT menu candidate (online and MC production) - 81X.
Adds a "frozen" (25ns10e33_v2) menu, separate from development HLT menus, for MC production.
In 81X, @relval2016 and @frozen2016 point to GRun.
Based on CMSSW_8_1_0_pre6.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
(DAS errors should be filtered out!)

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test
(DAS errors)

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Could you please integrate this 81X PR as it is different from its 80X twin already integrated there,
and would thus show merge conflicts once the auotmatic forward port kicks in.
Thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
