### PR TITLE
[L1T] remove ::All from Cond DB version

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Follow-up on https://github.com/cms-sw/cmssw/pull/37726#discussion_r861556841 ("the ::All here are relics from Cond DB version")

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by perrotta** [comment]
@mmusich @cms-sw/alca-l2 FYI

**Comment by mmusich** [comment]
there are more files touched in https://github.com/cms-sw/cmssw/pull/37726 that have the same issue.

**Comment by cecilecaillol** [comment]
please test

**Comment by tvami** [comment]
These GTs are very old, which I guess also means that these configs are not run very often... I was wondering that instead of having specific GTs, one should uses the autoCond keys (which will ensure that the GTs are always up to date). But given my first sentence, this might be less relevant...

**Comment by perrotta** [comment]
+1
- All these scripts are quite old, probably not even used any more. If and when they'll have to be put to work once again I imagine that several other adjustments will be needed, besides what suggested in https://github.com/cms-sw/cmssw/pull/37735#issuecomment-1113301906.
- Let therefore merge this PR as it is, with only the formal fix it was intended for

**Pull request merged**
