### PR TITLE
[BTV] Disable pT cut for AK4 Puppi ParticleNet and UParT taggers inference

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR makes several changes related to BTV:

- Lower jet pT cut to 0 for AK4 Puppi ParticleNet and UParT jet taggers. The jet abs(eta) range for ParticleNet is also extended to 5. This is to ensure that the taggers provide pT regression values for low pt jets. Very small timing impact on PAT step ([XPOG 4/9](https://indico.cern.ch/event/1450394/#11-jme-pt-threshold-for-pt-reg)). 
- Remove hardcoded jet pT and eta selection in `UnifiedParticleTransformerAK4TagInfoProducer.cc`.
- Puppi weight is now retrieved from ValueMap in `ParticleNetFeatureEvaluator.cc`.
- Simplify setup of `packedpuppi` module in `setupBTagging()` function.

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes MiniAOD workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
enable profiling

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
enable profiling,nano

**Comment by hqucms** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
