### PR TITLE
Run2-hcx169 Add a version of 2018 description which allows collapsing of HE depths in reconstruction (backport #21784)

### PR DESCRIPTION
**Pull request by bsunanda**
The new geometry is needed to do the reco step for the production needed for TSG studies

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Can you approve this?

**Comment by kpedro88** [comment]
+1

**Comment by bsunanda** [comment]
No need for bakporting

**Pull request closed without merging**
