### PR TITLE
Removal of hardcoded plot paths, addition to CMSLITDPG-318

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Changing hard coded directory paths in order to make them configurable.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @vukasinmilosevic I guess two PRs from someone else sneaked in. Please check and eventually rebase.

**Comment by perrotta** [comment]
-1
(It won't require the reco signature once rebased)

**Comment by thomreis** [comment]
@vukasinmilosevic please close this PR now that #22044 was made.

**Pull request closed without merging**
