### PR TITLE
Remove ESProducers for ECAL Mustache parameters from configuration

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Since the records should now be provided with the GT this PR removes the ESSource and ESProducers for EcalMustacheSCParameters and EcalSCDynamicDPhiParameters from the default configuration.

#### PR validation:

Passes the limited matrix tests.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
>
> * Reco comparison results: 14470 differences found in the comparisons
>

It doesn't seem they were so unused...

**Comment by thomreis** [comment]
Not unused but fixed to one specific set of parameters. The ESProducer produced parameters for Run 3 for all WFs. Now with the records coming from the GT there are also the Run 2 parameters used for certain WFs. There I would expect some differences. I need to verify though that the WFs with differences use tags with Run 2 parameters.

**Comment by thomreis** [comment]
I have checked all WFs with failing comparisons and they all use tags with Run 2 parameters, apart from WF 312.0, which has only failed comparisons in the MessageLogger.

**Comment by perrotta** [comment]
+1
-  It removes the ESSource and ESProducers for EcalMustacheSCParameters and EcalSCDynamicDPhiParameters, so that those parameters are now taken from the official tag in the DB
- With this change, those run2 (and run1) parameters are used in run2 (and run1) workflows, and not the run3 ones which were used before in all cases: this originates the differences visible in the outputs of the jenkins tests for all workflows previous to run3

**Comment by silviodonato** [comment]
+1
related to https://github.com/cms-sw/cmssw/pull/32997 and https://github.com/cms-sw/cmssw/pull/32959

**Comment by slava77** [comment]
>  Now with the records coming from the GT there are also the Run 2 parameters used for certain WFs. There I would expect some differences.

this was discussed in the ORP earlier today.
The comparisons show that the changes are not from numerical precision. So, the change is significant.
Is there an intended difference between the GT and the hardcoded parameters for Run 2?

@christopheralanwest

**Comment by thomreis** [comment]
The hardcoded parameters that the ESProducer used were the ones for Run 3 for all WFs. Now with the parameters coming from the GT the parameters can be either the Run 2 or the Run 3 ones depending on the WF. All WFs that show differences get the Run 2 parameters from the GT now instead of the previously hardcoded Run 3 ones.

**Comment by christopheralanwest** [comment]
> The hardcoded parameters that the ESProducer used were the ones for Run 3 for all WFs. Now with the parameters coming from the GT the parameters can be either the Run 2 or the Run 3 ones depending on the WF. All WFs that show differences get the Run 2 parameters from the GT now instead of the previously hardcoded Run 3 ones.

If this is the case, why were there no comparison test differences in the (non-DD4HEP) comparison tests for PR #32066 (see https://github.com/cms-sw/cmssw/pull/32066#issuecomment-733885247)? The absence of any differences when these ESProducers were introduced is what convinced me that this was a purely technical change.

**Comment by thomreis** [comment]
Because the change from hardcoded Run 2 parameters to hardcoded Run 3 parameters was already done before #32066 with PR #31823. And there are differences observed and discussed in that PR.

**Comment by christopheralanwest** [comment]
So is it fair to say that PR #31823 renders Run 2 workflows sub-optimal by an amount that was seen as acceptable at the time but this PR restores the original behavior?

**Comment by thomreis** [comment]
I think that can be said for Run 2 WFs, yes.

**Pull request merged**
