### PR TITLE
76X hlt25ns round5 plus updated frozenv4

### PR DESCRIPTION
**Pull request by perrotta**
This pull request is based on #11334, and it simply adds to it the update of the v4 25 frozen HLT menu from V2 to V3 (last commit in this PR). We want to merge it in 76X only if the corresponding 75X pull request ( #11484) can be merged in that queue, so that the menus dumped in the 75X and 76X queues can remain synchronized: see the description of that 75X PR for the details. Otherwise we will close this PR.
Based on CMSSW_7_6_X_2015-09-24-2300

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_7_6_X to solve merge conflict

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
