### PR TITLE
add decay files for BPH tranche-3 and tranche-4 production

### PR DESCRIPTION
**Pull request by heppye**
add decay files for BPH tranche-3 and tranche-4 production

### CODE REVIEW

**Comment by covarell** [comment]
@davidlange6 @heppye I am sorry, but do we still need such PRs even in 7.1.X? I understood that for that release the migration of .dec files to an external "data" repository is already in place...

**Comment by covarell** [comment]
ok, I read the email thrwad now, so I am leaving it on hold for now

**Comment by perrozzi** [comment]
@heppye please comment on this PR. it should probably closed, isn't it?

**Comment by oozcelik** [comment]
@perrozzi please see my mail.

**Comment by heppye** [comment]
same PR as https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/6/files, close it now as it is decided to merge from the external repository.

**Pull request closed without merging**
