### PR TITLE
NanoAOD: add flag to keep all PS weights

### LINKED ISSUE #538: Bug for MC genweight vector of size 1
Dear all,
there is a bug in this line:
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L438
double w0 = weights.at(1);
The number of elements in GEN weight vector needs to be checked first. There can be events with single-entry weight vector, see e.g. these requests [1].
Cheers, Alexander.
[1] https://its.cern.ch/jira/browse/CMSCOMPPR-16642#add-comment

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

- Add a flag (default false) to keep all the available PS weights instead of the regular 4 (ISR/FSR x up/down), as asked by JME for their custom ntuple production. If set to true, the whole PS weight array is kept, apart from the first two entries (these correspond to either `[XWGTUP * PSweight * match_eff, XWGTUP * PSweight]` or `[PSweight * match_eff, PSweight]`, so they'll be equal to 1 most of the time after normalizing the weights by the second entry, see https://github.com/cms-nanoAOD/cmssw/pull/506). 

- The flag is set to true for the nanoGEN format

- Add the PS weights to nanoDQM

- Fix the PS weight normalization in the case where the weights are parsed according to the lumi header (see https://github.com/cms-nanoAOD/cmssw/pull/441): the PS weights should be normalized by the `Baseline` weight (assumed to be the first PS weight seen).

- Add a protection for the case of empty weight arrays - fixes https://github.com/cms-nanoAOD/cmssw/issues/538

Note: was originally https://github.com/cms-nanoAOD/cmssw/pull/542
FYI  @camclean @alefisico

#### PR validation:

Tested in 106X: produced nanoAOD files for TTToSemiLeptonic (2016 and 2018) and for one of the parameter scan files mentioned in https://github.com/cms-nanoAOD/cmssw/pull/441 [1].

[1] /store/mc/RunIIAutumn18MiniAOD/SMS-TChiWZ_ZToLL_mZMin-0p1_mC1-325to1000_TuneCP2_13TeV-madgraphMLM-pythia8/MINIAODSIM/GridpackScan_102X_upgrade2018_realistic_v15-v1/70000/FFE78E85-6F7A-9441-8963-980A38403D1F.root

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by mariadalfonso** [comment]
@agrohsje 
let me know if this is ok for you

**Comment by agrohsje** [comment]
Hi @mariadalfonso , it looks to me like the bug can still happen, no : 
https://github.com/cms-sw/cmssw/blob/50bf2c332187ba71c9936c4deb5dbffaf9ff8d62/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L453 ?

**Comment by mariadalfonso** [comment]
@swertz @agrohsje 
you are referring to this issues reported here.
https://github.com/cms-nanoAOD/cmssw/issues/538

indeed this PR doesn't fix this, but is a good idea on adding here to complete the PS weights.

**Comment by mariadalfonso** [comment]
assign generators

**Comment by swertz** [comment]
@mariadalfonso @agrohsje 

I've added a protection for the case of empty arrays. 

Fixes https://github.com/cms-nanoAOD/cmssw/issues/538

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
> @mariadalfonso @agrohsje
> 
> I've added a protection for the case of empty arrays.
> 
> Fixes [cms-nanoAOD#538](https://github.com/cms-nanoAOD/cmssw/issues/538)

great thanks you
worth to add this comment in the PR description

**Comment by mariadalfonso** [comment]
@swertz 
we have now conflict with the nano_cff because of the genNANO update https://github.com/cms-sw/cmssw/pull/30306

While in the central nano we want to keep the keepAllPSWeights = cms.bool(False),
we can take the opportunity to to set to True for the genNano configuration
@kdlong please suggest

**Comment by kdlong** [comment]
@mariadalfonso yes it's a good idea to have keepAllPSWeights = True for NanoGEN. I think the merge conflict comes from the fact that I moved the genWeightsTable to its own file.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog
extended the PSweight and fixed a couple of isses as outlined in the description
no effect to central nano

**Comment by agrohsje** [comment]
Hi @mariadalfonso @swertz . Thanks again for this useful PR. I see that Sebastien tested Pohweg + Pythia 8. Would it make sense to perform additional checks. I.e. test a MG5 LO sample with additional partons, a MG5_aMC@NLO FxFx sample and a pure P8 one with and without PS weights. The PR looks good and the tests ran fine, however, I don't think that we test anything that was modified. Please let me know what you think.

**Comment by santocch** [comment]
+1

**Comment by swertz** [comment]
> Would it make sense to perform additional checks. I.e. test a MG5 LO sample with additional partons, a MG5_aMC@NLO FxFx sample and a pure P8 one with and without PS weights. 

I can run some quick tests but it would help if you could provide an example dataset of each case you mentioned.

**Comment by agrohsje** [comment]
Should I provide the mini-aod, like: 
/DYJetsToMuMu_M-50_TuneCP5_13TeV-madgraphMLM_pdfwgt_F-pythia8/RunIISummer19UL18MiniAOD-PUForMUOVal_106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM ?

**Comment by swertz** [comment]
Yes, that's perfect!

**Comment by agrohsje** [comment]
As you tested Powheg, I would propose to check the weight tables here: 
MLM: /DYJetsToMuMu_M-50_TuneCP5_13TeV-madgraphMLM_pdfwgt_F-pythia8/RunIISummer19UL18MiniAOD-PUForMUOVal_106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM
FxFx : /TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15_ext2-v1/MINIAODSIM 
P8 w/ weights : /WWTo2L2Nu_TuneCP5_DoubleScattering_13TeV-pythia8/RunIISummer19UL17MiniAOD-106X_mc2017_realistic_v6-v1/MINIAODSIM
P8 w/o weights: /QCD_Pt_50to80_TuneCP5_13TeV_pythia8/RunIISummer19UL17MiniAOD-106X_mc2017_realistic_v6-v2/MINIAODSIM

**Comment by swertz** [comment]
Thanks a lot!

Unfortunately I don't manage to run the tests on master, I get:
```
Calling method for module PATTauDiscriminationByMVAIsolationRun2/'patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw'
Exception Message:
No data of type "GBRForest" with label "RecoTauTag_tauIdMVAIsoDBoldDMwLT" in record "GBRWrapperRcd"
```
Am I overlooking something obvious? mariadalfonso what era/modifiers should be used when running on master...?

In any case I can rebase on 106X (will be needed anyway for the backport) and test there.

**Comment by kdlong** [comment]
IF you're just testing the PS weights, NanoGEN should be fine, and you won't have to worry about non-gen aspects of the config. You could run this cmsDriver command: https://github.com/kdlong/WMassNanoGen/blob/master/runCmsDriverGenericMiniToNanoGen.sh

**Comment by mariadalfonso** [comment]
> Thanks a lot!
> 
> Unfortunately I don't manage to run the tests on master, I get:
> 
> ```
> Calling method for module PATTauDiscriminationByMVAIsolationRun2/'patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw'
> Exception Message:
> No data of type "GBRForest" with label "RecoTauTag_tauIdMVAIsoDBoldDMwLT" in record "GBRWrapperRcd"
> ```
> 
> Am I overlooking something obvious? @mariadalfonso what era/modifiers should be used when running on master...?
> 

The nano-eras depends no the miniAOD type. you can look here for the different cases 
https://github.com/cms-nanoAOD/cmssw/issues/533#issuecomment-672971478

**Comment by swertz** [comment]
Thanks @kdlong , that's very useful.

I wasn't careful enough before and only checked the length of the weight arrays, not the contents. There was a small bug, now fixed.

Here's what I now get:

- Default:
  - TT powheg: 4 entries
  - SMS MG5 w/ parameter scan: 4 entries
  - DYJets MG5 MLM*: 4 entries
  - TTJets MG5 FxFx: 4 entries
  - WW P8: 4 entries
  - QCD P8 w/o weights: 1 entry (=1)

- With all weights stored:
  - TT powheg: 44 entries
  - SMS MG5 w/ parameter scan: 44 entries
  - DYJets MG5 MLM*: 44 entries
  - TTJets MG5 FxFx: 44 entries
  - WW P8: 44 entries
  - QCD P8 w/o weights: 1 entry (=1)

The 4 default entries correspond, as expected, to entries 4-7 in the full arrays ("Def" variations).

(*) I used `/DYJetsToLL_M-5to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM` instead as I could not open any file from the suggested one. I'm also a bit surprised that some of those events have all their PS weights equal to 1..

> The nano-eras depends on the miniAOD type. you can look here for the different cases cms-nanoAOD#533 (comment)

Yes, I used `run2_nanoAOD_102Xv1` but that resulted in the above crash. To be discussed elsewhere?

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
> 
> (*) I used `/DYJetsToLL_M-5to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM` instead as I could not open any file from the suggested one. I'm also a bit surprised that some of those events have all their PS weights equal to 1..
> 
> > The nano-eras depends on the miniAOD type. you can look here for the different cases [cms-nanoAOD#533](https://github.com/cms-nanoAOD/cmssw/issues/533) (comment)
> 
> Yes, I used `run2_nanoAOD_102Xv1` but that resulted in the above crash. To be discussed elsewhere?

uhm
--era Run2_2018,run2_nanoAOD_102Xv1 
did you have specified both? (Run2_2018 contains one or the reco tau modifiers and seems your local test had problem in the taus)

**Comment by kdlong** [comment]
> Here's what I now get:
> 
> * Default:
>   
>   * TT powheg: 4 entries
>   * SMS MG5 w/ parameter scan: 4 entries
>   * DYJets MG5 MLM*: 4 entries
>   * TTJets MG5 FxFx: 4 entries
>   * WW P8: 4 entries
>   * QCD P8 w/o weights: 1 entry (=1)
> * With all weights stored:
>   
>   * TT powheg: 44 entries
>   * SMS MG5 w/ parameter scan: 44 entries
>   * DYJets MG5 MLM*: 44 entries
>   * TTJets MG5 FxFx: 44 entries
>   * WW P8: 44 entries
>   * QCD P8 w/o weights: 1 entry (=1)

Do we really want to fill the table with 1 entry when there are no PS weights? Note that this is exactly the genWeight (genEventInfo->weights()[0])

**Comment by swertz** [comment]
> Do we really want to fill the table with 1 entry when there are no PS weights? Note that this is exactly the genWeight (genEventInfo->weights()[0])

This was the default behaviour before, I didn't change it (and in fact in that case it's just filled with a dummy `1`). But I don't see why we couldn't simply have an empty `PSWeight` array in that case... Any strong opinion on that?

> uhm
> --era Run2_2018,run2_nanoAOD_102Xv1
> did you have specified both? (Run2_2018 contains one or the reco tau modifiers and seems your local test had problem in the taus)

I ran with:
```
cmsDriver.py NANO -s NANO --mc --conditions 102X_upgrade2018_realistic_v21 --era Run2_2018,run2_nanoAOD_102Xv1 --eventcontent NANOAODSIM --datatier NANOAODSIM -n -1 --no_exec
```
And got the aforementioned exception.

**Comment by mariadalfonso** [comment]
let's finalise the weight storage for the cases  w/o weights: 
do we want 1 dummy entry with 1 or we leave it empty ?
@agrohsje  ?

**Comment by agrohsje** [comment]
@kdlong what would be your concern with 1? I would naively assume that from a technical analysis point of view 1 is a good choice. You see a problem in people not being aware that there is no info?

**Comment by qliphy** [comment]
@kdlong @agrohsje @GurpreetSinghChahal  Any conclusion?

**Comment by kdlong** [comment]
Hi, I see no real problem with 1, it's just that the info really doesn't exist, so I would kind of expect it to be empty. Wouldn't the LHEScaleWeight or LHEPdfWeight be empty or not produced in cases where they don't exist?

**Comment by swertz** [comment]
> Wouldn't the LHEScaleWeight or LHEPdfWeight be empty or not produced in cases where they don't exist?

Indeed, so it would be more consistent to also leave the PSWeight array empty if there are no weights.

**Comment by agrohsje** [comment]
My concern was not so much consistency, but more being stable for users. I would prefer keeping the current implementation.

**Comment by mariadalfonso** [comment]
+xpog
changes are inline with the PR description.

If activated by the flag, the PS weights appear as listed here
https://github.com/cms-sw/cmssw/pull/31276#issuecomment-691290392

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Comment by mariadalfonso** [comment]
@swertz 
consider back-porting this PR in 10_6

**Comment by agrohsje** [comment]
@mariadalfonso  What about 10_2 and 9_4? Can one backport?

**Comment by mariadalfonso** [comment]
@agrohsje 
Master or 10_6 can perfectly run on EOY miniAOD make with 10_2 and 94X.
for the moment we are back porting all the nano only to 10_6 for the UL reprocessing.
Is there any particular reason to backport the GEN nano-fixes to previous releases ?

Note: NanoGen is only available in 11_2

**Comment by agrohsje** [comment]
v7 is currently using 10_2:
https://cms-pdmv.cern.ch/mcm/campaigns?prepid=Run*NanoAODv7
Will we move to 10_6 also for these?

**Comment by mariadalfonso** [comment]
> v7 is currently using 10_2:
> https://cms-pdmv.cern.ch/mcm/campaigns?prepid=Run*NanoAODv7
> Will we move to 10_6 also for these?

We will not be making anymore V7 centrally, and we didn't get requests on fixing older releases for private renano of the V7.

**Comment by agrohsje** [comment]
Hi @mariadalfonso . The problem is that we had failing HIG requests due to the bug. So they would need to resubmit nano-aod. I assume for this it might be easiest to update v7?

**Comment by mariadalfonso** [comment]
> Hi @mariadalfonso . The problem is that we had failing HIG requests due to the bug. So they would need to resubmit nano-aod. I assume for this it might be easiest to update v7?

ok, we will follow up with the PC group, so that's will be clear what are the requests for the EOY and 10_2 and how to best help the private reprocessing. There are other bug-fixes besides this one among the [](https://github.com/cms-nanoAOD/cmssw/issues/533)

For the time being let's complete the 10_6

**Comment by santocch** [comment]
+1

**Pull request merged**
