### PR TITLE
bsunanda:Phase2-hgx49 Bug fix for RECO geometry of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
Allow single layer partition till the last layer

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @civanch Please sign this

**Comment by bsunanda** [comment]
@ianna @civanch Could you please sign this PR

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
