### PR TITLE
[Phase-2 L1T] calibrated GCT calo jets and taus

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:
- reviewed by L1T offline conveners https://github.com/cms-l1t-offline/cmssw/pull/1189
- updates to l1tp2::Phase2L1CaloJetCollection
- the endcap and forward region tower energies are calibrated using values used in Phase-2 L1T TDR https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1CaloTrigger/plugins/L1TowerCalibrator.cc
- this improves the jet pT resolution (and therefore the rates) significantly in endcap and forward regions when used together with custom_towers_energySplit in HGCal implemented in https://github.com/cms-sw/cmssw/pull/42246
- the jet and tau energy calibration is derived on top of the above
- not a backport

@aloeliger @epalencia

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1
- Reviewed and approved by L1 in https://github.com/cms-l1t-offline/cmssw/pull/1189

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
