### PR TITLE
Transform couts to LogDebug/LogTrace in MultiHitGeneratorFromChi2

### PR DESCRIPTION
**Pull request by makortel**
Following @cvuosalo's comment https://github.com/cms-sw/cmssw/pull/10016#discussion_r33873186, this PR transforms all couts in MultiHitGeneratorFromChi2 to LogDebug/LogTrace. In order to be able to compile with `-DEDM_ML_DEBUG`, I had to first fix bunch of errors within LogDebugs in Conv4HitsReco.

Tested in CMSSW_7_6_X_2015-07-10-1100, no changes expected in results.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10231	0fd96a8
- couts are removed ... the heavy use of ifdefs doesn't look the most elegant though.
- jenkins tests passed and comparisons with the baseline show no differences

**Comment by makortel** [comment]
@slava77 Fully agree on the ifdefs (they just were the simplest-to-write solution to preserve existing debug-print behaviour). Thinking now, probably with some macro(s) the ifdefs could be removed from the function bodies, I could give a try if deemed useful.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
