### PR TITLE
Ape parallel features

### PR DESCRIPTION
**Pull request by mteroerd**
All of the updated and newly added code incorporates the python print migration.

This PR consists of three commits:
1. 92b8f88 fixes a small typo in one of the rarely used macros for validation plots.

2. 9072dbb consists of an update to the SkimProducer and AlignmentTrackSelector on one hand to ease the configuration of skims. On the other hand, a new python script startSkim.py was created to use alternatively to skimProducer.bash. This new script enables parallel execution of skims as well as automatic renaming of the output files (from *00N.root to *_(N+1).root which is the input name format needed for the APE measurements) and moving of the skimmed files to a target directory.

3. 7323657 adds additional optional input parameters to the central _cfg.py files used for a measurement. When using the standard workflow, these parameters are unused and nothing changes. However, the commit also includes a new folder autoSubmitter which includes a script to configure and submit multiple measurements at the same time in order to be able to do multiple measurements at once using only one CMSSW-environment. 
All changes allow for the use of the old workflow which is detailed in the TWiki ( https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAlignmentPositionErrorEstimator ), however now APE objects are no long written to and read from hists/apeObjects but instead hists/workingArea/apeObjects (see 2dcad6d and 1d45893 ).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@davidlange6 do we have a way of checking the python3 compatibility of new code, so as not to spoil your migration work?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
