### PR TITLE
Modernize MuonTrackProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR does several modernizations for `MuonTrackProducer`, started by addressing this warning from GCC10
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/6bfeb1b59c2a9e14c52cd5c5d0709cec/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_11_2_X_2020-07-24-2300/src/SimMuon/MCTruth/plugins/MuonTrackProducer.cc: In member function 'virtual void MuonTrackProducer::produce(edm::Event&, const edm::EventSetup&)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/6bfeb1b59c2a9e14c52cd5c5d0709cec/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_11_2_X_2020-07-24-2300/src/SimMuon/MCTruth/plugins/MuonTrackProducer.cc:144:22: warning: '*' in boolean context, suggest '&&' instead [-Wint-in-bool-context]
   144 |         isGoodResult *= isGood[index];
      |        
```

The commits should be self-explanatory on what was done.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
