### PR TITLE
Phase2-hgx354B First attempt to prepare components of XML file for the scintillator components in the mixed layers of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

First attempt to prepare components of XML file for the scintillator components in the mixed layers of HGCal

#### PR validation:

Extraction of the components works and now to be inserted into new XML files for the V19 version of HGCal geometry

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please merge this PR. Need the merged IB for future work

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
