### PR TITLE
DT DQM fixes for PoA

### PR DESCRIPTION
**Pull request by jfernan2**
Needs to follow PR #13399

### CODE REVIEW

**Comment by deguio** [comment]
ciao @jfernan2
this PR removes >100 files. is this what you meant to do? could you please elaborate more on the goal of this PR?
moreover it would be nice to test this PR in 81x first. please submit new developments there.
thanks,
F.

**Comment by jfernan2** [comment]
ciao @deguio , I'm sorry, I only meant to change code on DQM/DTMonitorModule package, I understand now that this PR involves other packages so I have submitted them untouched...
My apologies.
The code is necessary for DT Prompt Offline Package to work properly. Should I then push it in 81X as an new independent PR? I'm sorry for the incovenience. Thanks

**Comment by deguio** [comment]
ciao @jfernan2 
I see O(100) files removed in the  DQM/DTMonitorClient. could you elaborate on what you want to do with this PR? I will look into more details since the change is too big to be visualized in github.
thanks,
F.

**Comment by deguio** [comment]
and yes. you need to push an independent PR to 81x.
thanks,
F.

**Comment by jfernan2** [comment]
Hi, deletion of files in DQM/DTMonitorClient were by accident, please ignore this PR, I'm sorry for the incovenience. I have create a new PR inn 81X with only the changes in DQM/DTMonitorModule
https://github.com/cms-sw/cmssw/pull/13539 
Thanks

**Comment by deguio** [comment]
-1
sounds good.
thanks,
F.

**Comment by mmusich** [comment]
-1

**Pull request closed without merging**
