### PR TITLE
Move DDUnits.h out of DetectorDescription for general use

### PR DESCRIPTION
**Pull request by cvuosalo**
Prepare for migration of CMMSW files from CLHEP units to user-defined literal units. Move `DetectorDescription/Core/interface/DDUnits.h` to `DataFormats/Math/interface/GeantUnits.h` so it can be used throughout CMSSW. Delete redundant `DetectorDescription/DDCMS/interface/DDUnits.h`. Change the `CONVERT_TO` and `ConvertTo` macros to specific functions with names that note what units are converted to what.

This PR should have no run-time effects.

### CODE REVIEW

**Comment by cvuosalo** [comment]
please test

**Comment by makortel** [comment]
Umm, it looks to me that the conventions here for distance and energy are millimeter and MeV, respectively. The [CMSConventions](https://twiki.cern.ch/twiki/bin/view/CMS/CMSConventions#CMS_units) says that the CMS conventions are centimeter and GeV (respectively). I'm afraid that a unit header file in `DataFormats/Math` defining a namespace `cms_units` with a convention different from [CMSConventions](https://twiki.cern.ch/twiki/bin/view/CMS/CMSConventions#CMS_units) will lead to confusion.

Maybe the unit definition file should be placed (or at least renamed) such that it is clear to be used in only those parts of the codebase that must use the mm/MeV convention?

**Comment by cvuosalo** [comment]
@makortel: How about calling the header file `CMSGeantUnits.h` and the namespace `cms_geant_units`? These units are based upon the Geant4 conventions, but the file was created by us and is part of CMSSW, not Geant4, so it needs the CMS prefix.

**Comment by makortel** [comment]
@cvuosalo I think that is already much better. Is there any less general package than `DataFormats/Math` that would work?

**Comment by cvuosalo** [comment]
@makortel: The units header file will be needed by Alignment, Geometry, Reco, Sim, and Validation. I don't know of a more specific location for it instead of `DataFormats/Math`. Can you suggest one?

**Comment by fabiocos** [comment]
@makortel @cvuosalo this improved version of the code (thanks to Carl) is effectively meant to replace the CLHEP system of units used by Geant4 but also by several packages of CMSSW (mostly in geometry and simulation, but not only). I agree with Matti that having conflicting definitions might sound confusing, and the proposal of Carl looks good to me. As fra as the location is concerned, I suggested DataFormats/Math as this is a general utility that can be used in many places, and we have already other similar definitions there (e.g. numerical constants are defined within https://cmssdt.cern.ch/lxr/source/DataFormats/Math/interface/FastMath.h ). An alternative possible location that came to my mind would be https://cmssdt.cern.ch/lxr/source/CommonTools/Utils/interface/  .
I do not have a very strong feeling about this choice, although I am not sure what is wrong in having this in a general package provided it is clear the kind of convention it is adopting. 

I would avoid to create another package just for this header (and may be another one where we redefine physics constants now taken from CLHEP https://gitlab.cern.ch/CLHEP/CLHEP/blob/master/Units/Units/PhysicalConstants.h used in some 180 files https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_10_5_X_2019-02-18-2300&_filestring=&_string=PhysicalConstant )

**Comment by makortel** [comment]
@cvuosalo If the need it is that widespread, I agree the `DataFormats/Math` is a good (enough) place.

**Comment by cvuosalo** [comment]
I'm going to change `CMS_CONVERT_TO` to `CONVERT_UNITS_TO` because the CMS prefix could create confusion about which units convention is being used.

**Comment by cvuosalo** [comment]
please test

**Comment by cvuosalo** [comment]
please test

**Comment by cvuosalo** [comment]
I think the 3 differences in the Comparison results are not significant.

**Comment by cvuosalo** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
Changes are done. I think this PR is now in final form and ready for review.

**Comment by cvuosalo** [comment]
@perrotta, @slava77: Could you please review this PR? There is only one Reco file to look at: `DataFormats/Math/interface/GeantUnits.h`.
Thanks.

**Comment by slava77** [comment]
On 2/22/19 7:36 AM, Carl Vuosalo wrote:
> @perrotta, @slava77: Could you please review this PR? There is only
one Reco file to look at: DataFormats/Math/interface/GeantUnits.h.
Thanks.

Please comment on apparent violations of the CMSSW coding rules in this
file.
http://cms-sw.github.io/cms_coding_rules.html
2.12 Do not use special characters, except for “_” where allowed.
	related to e.g. long double operator "" _eV( long double energy )  using "
2.13 Do not use “_” as ﬁrst character. Only use it as the last character
for class data member names, not local variable names.
	long double _pi(M_PI);
4.14  Do not use function-like macros.
	in #define CONVERT_UNITS_TO(_x, _y) (_x)/(1.0_##_y)

**Comment by slava77** [comment]
... also, the include guard does not conform to 4.1.

**Comment by cvuosalo** [comment]
@slava77: Thanks. I have been working with this file long enough that I was overlooking these obvious problems. And now is a very good opportunity to fix them.

**Comment by cvuosalo** [comment]
-1

Have to fix coding rules violations

**Comment by cvuosalo** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25967	15fd04d
- code changes are in line with the PR description and the follow up review. Reco is affected only via a new file DataFormats/Math/interface/GeantUnits.h 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by ianna** [comment]
> Umm, it looks to me that the conventions here for distance and energy are millimeter and MeV, respectively. The [CMSConventions](https://twiki.cern.ch/twiki/bin/view/CMS/CMSConventions#CMS_units) says that the CMS conventions are centimeter and GeV (respectively). I'm afraid that a unit header file in `DataFormats/Math` defining a namespace `cms_units` with a convention different from [CMSConventions](https://twiki.cern.ch/twiki/bin/view/CMS/CMSConventions#CMS_units) will lead to confusion.
> 
> Maybe the unit definition file should be placed (or at least renamed) such that it is clear to be used in only those parts of the codebase that must use the mm/MeV convention?

Hmm... Geometry definition in XML uses mm as a default. And yes, there was a confusion when a new sub-detector was defined. Now I understand the reason :-)

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
