### PR TITLE
CMSSW_7_6_X_DQMfix for HI

### PR DESCRIPTION
**Pull request by goni-zz**
modifying mass region, bins for Heavy Ions.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please rename this PR to something meaningful

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
