### PR TITLE
avoid repeating computations when initializing HcalPulseShapes

### LINKED ISSUE #22913: HcalHitReconstructor Initialization
In an igprof performance profile of test 25.0 step 3, HcalHitReconstructor shows up using roughly 0.25 seconds times the number of streams to initialize. Of the modules that scale as a function of stream, this is third highest in the profile (there are recent PRs already to improve the two higher cases).

Almost all the time is spent in the two similar lines that are calling the convolve function:

http://cmslxr.fnal.gov/source/CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc#0386
http://cmslxr.fnal.gov/source/CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc#0405

This time is all in evaluation of a math expression. There is a double loop that does a calculation every time including evaluation of log and exponential terms. Because of the number of iterations this expression is evaluated 10s of thousands of times. The output of the calculation is a vector with a few hundred elements.

The issue is that the output of the calculation is always the same for every stream, every module, and every process. This becomes more significant as we move to larger numbers of streams. I am currently working on how to improve this and have a few ideas (a GlobalCache, the EventSetup using a function to calculate it, put it in a database and use the EventSetup to read it, hard code the output vector values).

@slava77 @Dr15Jones  Any suggestions on how to proceed? How is this type of problem usually handled in RECO? I also have a choice to put as much of the related code as I can in this new cache or just deal with the minimal part of it that is taking almost all the time.

### PR DESCRIPTION
**Pull request by kpedro88**
Resolves #22913, though better code design (e.g. ESProduct) would be preferable for long-term maintainability. I also made a few very minor optimizations and cleanups while making the major change (using magic statics).

attn: @abdoulline @wddgit @Dr15Jones @slava77

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by abdoulline** [comment]
@kpedro88  thank you for bringing this improvement!

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
