### PR TITLE
MillePedeAlignmentAlgorithm: update for new GBL version

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Update MillePedeAlignmentAlgorithm to cope with API changes in GBL (see https://github.com/cms-sw/cmsdist/pull/7638).

#### PR validation:

Tested in CMSDIST PR

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks with cms.week1.PR_63647d92/52.0-f31bcba2421d66544c8f93406ffdb32c

**Comment by tvami** [comment]
test parameters:
  - addpkg = Alignment/TrackerAlignment

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmsdist/pull/7638

**Comment by tvami** [comment]
+alca
 * we need https://github.com/cms-sw/cmsdist/pull/7638 to go in first

**Comment by qliphy** [comment]
+1

**Pull request merged**
