### PR TITLE
Fastsim New CFG structure (preparations for premixing)

### PR DESCRIPTION
**Pull request by lveldere**
This PR superseeds #8414

The FastSim cfg structure was altered,
to better resemble the standard cfg structure.
This will increase maintainability on long term,
and on short term it is a necessary step in the preparation for premixing.
### Changes
- **cmsDriver**: the FASTSIM, deprecated since a long time, is removed from ConfigBuilder
- **cmsDriver & runTheMatrix**:  FastSim has now the following steps in cmsDriver GEN,SIM,RECOBEFMIX,DIGI,L1,L1Reco,RECO,EI,HLT:@frozen25ns,VALIDATION all FastSim runTheMatrix workflows are migrated accordingly
- **HLT**:  L1 and L1Reco step are moved outside the HLT step and are now separate steps in FastSim
- **HLT**: clones of collections are replaced with EDAliases
- **HLT DQM / Validation**: to avoid crahses in runTheMatrix workflows the inputlabel for SimVertices consumed by HLTriggerOffline/Btag is made configurable
- **L1/DIGI**: packing and unpacking of calorimeter digis is removed and in order not to change any of the default InputTags, EDAliases are used to mimic the presense of post pack/unpack digi collections
- **FASTSIM**: unnecessary dependence of FamosProducer on BeamSpot is removed 
- **unit tests**: outdated fastsim unit tests are removed from addOnTest.py
- **Mixing**: reco track accumulator includes MVA values in mixing 
- **Mixing**: firstStepPrimaryVertices including PU tracks is emulated by reconstructing it from all  
  generalTracks since after mixing no initialStepTrack collection is available.
- **MIxing**: DataMixingModule can be configured to use RecoTrackAccumulator to mix tracker information
### TODO after this PR
- **HLT** cfg needs a more permanent solution which does not require to import the menu inside a wrapper in FastSimulation/Configuration (see e.g. FastSimulation/Configuration/python/HLT_GRun_Famos_cff.py)
  discussion initiated in #8414
- **HLT** rare segfualt in L2muons
- **tracking** Perhaps a cleaner solution is needed on long term to delete the modules from full iteratitve tracking from the Reconstrion cfg
- **FASTSIM** Remove all FastSim cfg and other code that has become obsolete
### Tests
- runTheMatrix.py -l 5.1,135.1,135.8,25400
- wf 135.1 with 1000 events, sanity checks for distributions of main physics objects
- detailed comparison of old dumped cfg vs new dumped cfg

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
Strange.
This works in my area.
I'm trying to test from scratch, but it takes a while to compile all the new stuff that got merged between now and the latest IB (march 19 it seems)

**Comment by Martin-Grunewald** [comment]
HLT has changed, you better use 740pre9 or CMSSW_7_4_X_2015-03-21-2300

**Comment by lveldere** [comment]
Thanks Martin

@davidlange6 
Is there any chance for an IB to fix these kind of issues before the first pre release?

**Comment by davidlange6** [comment]
@lveldere - the more recent 75x IBs are available on cvmfs (just not AFS given quota filling issues)

**Comment by lveldere** [comment]
Thanks David

could anyone tell me how I setup my environment to use IBs on cvmfs?

**Comment by davidlange6** [comment]
at least for lxplus:

https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2265/1/1/1/1/1.html

**Comment by lveldere** [comment]
I think I fixed it, but something makes it incredably slow to run cmssw on lxplus and cmsdev...
So I can't test properly.

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@civanch, @Dr15Jones, @danduggan, @boudoul, @mdhildreth, @cmsbuild, @srimanob, @nclopezo, @deguio, @franzoni, @ktf, @davidlange6

Dear All

Could you please start the review of this pr?
I would appreciate it a lot if you could treat this pr with priority.

A few notes to the different areas:

core: you can skipp this pr: I think your signature is no longer required 
(I undid the changes in addOnTest.py) but the bot needs to update the labels...

dqm: you can skip this pr: I made a separate pr for the changes that require the dqm signature, #8489, and will rebase once merged. 

simulation: you can skip this pr: I made a separte pr for the changes that require the simulation signature, #8490, and will rebase once merged.

pdmv, operations: it is impossible to disentangle the changes specific for your areas from the main part of this pr. This is nothing but splitting up the monolitical FastSim cfg into smaller steps. 

Cheers

Lukas

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@cmsbuild 

Can you let me know how I reproduce this error?
I have troubles understanding the logs of the unittests.
I cannot even determine whether this is FastSim related or not.

Thanks

**Comment by lveldere** [comment]
Near zero impact observed, near zero impact expected.
I strongly encourage to sign off this PR,
to make it easier solving the pending issues.

**Comment by nclopezo** [comment]
Hi @lveldere,
@cmsbuild does 
<pre>
scram project CMSSW_7_5_X_2015-03-24-2300
git cms-merge-topic -u 8455
git cms-checkdeps -A -a
scram b -k -j 12
</pre>
And the command used to run the unit tests is 
<pre>
scram b -k -j 12 runtests
</pre>

**Comment by davidlange6** [comment]
but i think this error is in the IB already.. I need to approve the fix..

**Comment by nclopezo** [comment]
Hi, yes, sorry I hadn't realized, the error is currently in the IBs :https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_5_X_2015-03-24-2300/unitTestLogs/PhysicsTools/PatAlgos

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@ktf 
is there a way to trigger labels (e.g. dqm-pending, simulation-pending,..) to be updated?
in principle my pr should no longer require signatures from simulation and dqm.

**Comment by lveldere** [comment]
+1

errors of tests not related to pr
zero effect on FullSim predictions, negligible effect on FastSim predictions, as expected

**Comment by lveldere** [comment]
@nclopezo, @boudoul @srimanob, @franzoni, @davidlange6
Can we please move on with this one?
This is pending since a very long time, and now it even has merge conflicts..
If there are good reasons for this to pend I'd like to hear about it.

**Comment by lveldere** [comment]
rebased and tested
runTheMatrix.py -l 5.1,135.1,135.8,25400

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
failures in test are not related to this pr
as expected:
- zero regression observed for FullSim tests
- negligible regression observed for FastSim

**Comment by lveldere** [comment]
merge-conflicts resolved

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
error in tests are not related to this pr...

**Comment by lveldere** [comment]
please test

the error is not present when working on top of more recent IBs

**Comment by lveldere** [comment]
Gentle reminder
This pr is ready since 8 days and is very important for FastSim.
Please review and sign or make complaints.

 @civanch, @nclopezo, @lveldere, @boudoul, @ssekmen, @mdhildreth, @cmsbuild, @srimanob, @franzoni, @davidlange6

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1
I am ok with the logic of the chances to relval_steps
pushing this forward, upon request of Lukas @lveldere . 
Have had not time to dig deep into the changes to Configuration/Applications/python/ConfigBuilder.py . Note: it's possible that my +1 will be received as a signature for operations, too. 

@lveldere : since there's now a digi step, would it make sense adding the DQM (besides VALIDATION) ? Can you give that thought / try (in perspective, not for this PR)

**Comment by lveldere** [comment]
@franzoni 

thanks a lot

adding the DQM step is one of the things I have in mind for the future.

**Pull request merged**
