### PR TITLE
[13.2.X] Put back wf 140.6 in the relval matrix 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/42600

#### PR description:

https://github.com/cms-sw/cmssw/pull/42545 removed `140.60` from the relval  matrix. This PR recreates it, but using instead full 2022 RAW data format, emulate the RAW' and then reconstruct using the approximated clusters workflow (as discussed in https://github.com/cms-sw/cmssw/pull/42495#issuecomment-1683134955)

#### PR validation:

`runTheMatrix.py -l 140.58,140.60 -t 4 -j 8 --ibeos` runs fine

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/42600 to 13.2.X for 2023 heavy ion testing purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test workflow 140.6

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 this PR would be useful for testing possible further bug-fixes needed for the 2023 HI run, please take a look.

**Comment by perrotta** [comment]
+operations

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
