### PR TITLE
HLT HIon menu V1.5 (103X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT HIon menu V1.5 (103X)
CMSSW_10_3_X_2018-11-16-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #25268

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Martin-Grunewald** [comment]
Superseeded by #25342

**Pull request closed without merging**
