### PR TITLE
Removing sLAY array from TrackingRecoMaterialAnalyser

### PR DESCRIPTION
**Pull request by ebrondol**
It is not needed and it makes the code not flexible for other geometry. This should fix the RECO step with the new geometry introduced in #17551.

@rovere please test it and give your +1.

### CODE REVIEW

**Comment by rovere** [comment]
@ebrondol inline with what we discussed, fine with me.

**Comment by ebrondol** [comment]
@boudoul please, test the new geometry including this PR.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
