### PR TITLE
Update path names and binnings.

### PR DESCRIPTION
**Pull request by ryonamin**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@ryonamin - please also address the memory leak in this analyzer as part of this PR (presumably that will be made worse by this pull request. Thanks

https://hypernews.cern.ch/HyperNews/CMS/get/relval/3565/1/1/1/1/1.html

**Comment by davidlange6** [comment]
+1

**Pull request merged**
