### PR TITLE
added snippet files for tune uncertainties

### PR DESCRIPTION
**Pull request by pgunnell**
Added snippet files for tune uncertainties (should be correct now)

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by covarell** [comment]
@pgunnell , this needs still backport to 71X in order to be used in official production.
Or did I just miss the PR?

**Comment by pgunnell** [comment]
Yes, it should be backported..do you need the request from me for that?

**Pull request merged**
