### PR TITLE
Bug fix pat::TriggerObjectStandAlone

### PR DESCRIPTION
**Pull request by Dr15Jones**
The pat::TriggerObjectStandAlone was directly calling the ParameterSet registry assuming that a
previous call would fill the registry. That assumption was incorrect. Now the class calls the method
EventBase::parameterSet which will do the necessary up dating of the registry behind the scenes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This fixes the problem reported here:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3546/1/1.html

**Comment by perrotta** [comment]
The error in the unit test is unrelated:

stat: cannot stat `dqm_empty.root': No such file or directory
read_missing_file_cfg.py ------------------------------------------------------------
27-Jul-2017 19:24:27 CEST  Initiating request to open file file:dqm_missing.root
27-Jul-2017 19:24:28 CEST  Successfully opened file file:dqm_missing.root
----- Begin Fatal Exception 27-Jul-2017 19:24:28 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
Exception Message:
Input file file:dqm_missing.root appears to be corrupted since it does not have the proper internal structure.
 Check to see if the file was closed properly.
----- End Fatal Exception -------------------------------------------------

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The failures of the tests are unrelated to this pull request (i.e. they are already present in the IB).
This time through the unit tests passed which means the original failure was an unrelated glitch.

**Comment by perrotta** [comment]
please test
(let try once again: tests should now avoid the latest, broken IB...)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19942	217e542
- changes are in line with the description/resolution of the issue
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
