### PR TITLE
[10.3.X][Update GTs] new JEC MC TAGs + 2D Pixel Templates + EcalSimPulseShape + L1 menu

### PR DESCRIPTION
**Pull request by tocheng**
### RunI simulation 
 
   * **RunI Heavy Ions scenario** : [103X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun1_HeavyIon_v1) as [102X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun1_HeavyIon_v1/102X_mcRun1_HeavyIon_v1): 

   * **RunI Ideal scenario** : [103X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun1_design_v1) as [102X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun1_design_v1/102X_mcRun1_design_v1): 

   * **RunI Proton-Lead scenario** : [103X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun1_pA_v2) as [102X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun1_pA_v2/102X_mcRun1_pA_v1): 

   * **RunI Realistic scenario** : [103X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun1_realistic_v1) as [102X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun1_realistic_v1/102X_mcRun1_realistic_v1): 

### RunII simulation 
 
   * **RunII Asymptotic scenario** : [103X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2_asymptotic_v1) as [102X_mcRun2_asymptotic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_asymptotic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2_asymptotic_v1/102X_mcRun2_asymptotic_v3): 

   * **RunII CRAFT scenario** : [103X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2cosmics_startup_deco_v1) as [102X_mcRun2cosmics_startup_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2cosmics_startup_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2cosmics_startup_deco_v1/102X_mcRun2cosmics_startup_deco_v2): 

   * **RunII Heavy Ions scenario** : [103X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2_HeavyIon_v1) as [102X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2_HeavyIon_v1/102X_mcRun2_HeavyIon_v2): 

   * **RunII Ideal scenario** : [103X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2_design_v1) as [102X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2_design_v1/102X_mcRun2_design_v2): 

   * **RunII Proton-Lead scenario** : [103X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2_pA_v1) as [102X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2_pA_v1/102X_mcRun2_pA_v2): 

   * **RunII Startup scenario** : [103X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_mcRun2_startup_v1) as [102X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_mcRun2_startup_v1/102X_mcRun2_startup_v2): 

### Upgrade 
 
   * **PhaseII realistic scenario** : [103X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2023_realistic_v2) as [103X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2023_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2023_realistic_v2/103X_upgrade2023_realistic_v1): 

   * **PostLS2 design scenario** : [103X_postLS2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_postLS2_design_v2) as [103X_postLS2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_postLS2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_postLS2_design_v2/103X_postLS2_design_v1): 

   * **PostLS2 realistic scenario** : [103X_postLS2_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_postLS2_realistic_v2) as [103X_postLS2_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_postLS2_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_postLS2_realistic_v2/103X_postLS2_realistic_v1): 

### 2017_MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [103X_upgrade2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2017cosmics_realistic_peak_v1) as [102X_upgrade2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2017cosmics_realistic_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2017cosmics_realistic_peak_v1/102X_upgrade2017cosmics_realistic_peak_v3): 

   * **PhaseI 2017 cosmics scenario** : [103X_upgrade2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2017cosmics_realistic_deco_v1) as [102X_upgrade2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2017cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2017cosmics_realistic_deco_v1/102X_upgrade2017cosmics_realistic_deco_v3): 

   * **PhaseI 2017 design scenario** : [103X_upgrade2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2017_design_IdealBS_v1) as [102X_upgrade2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2017_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2017_design_IdealBS_v1/102X_upgrade2017_design_IdealBS_v3): 

   * **PhaseI 2017 realistic scenario** : [103X_upgrade2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_upgrade2017_realistic_v1) as [102X_upgrade2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2017_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2017_realistic_v1/102X_upgrade2017_realistic_v3): 

### RunII data 
 
   * **RunII HLT relval processing** : [103X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_HLT_relval_v3) as [103X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_v3/103X_dataRun2_HLT_relval_v1): 

**Added EcalSimPulseShape, Pixel2DTemplate and correct CTPPS geometry to the following **data GTs****

### RunI data 
 
   * **RunI Offline processing** : [103X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_v2) as [102X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_v2/102X_dataRun2_v3): 

### RunII data 

   * **RunII Offline processing** : [103X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_v2) as [102X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_v2/102X_dataRun2_v3): 

   * **RunII Prompt processing** : [103X_dataRun2_PromptLike_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_PromptLike_v3) as [102X_dataRun2_PromptLike_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_PromptLike_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_PromptLike_v3/102X_dataRun2_PromptLike_v4): 

### RunII data 

   * **RunII Offline relval processing** : [103X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_relval_v4) as [103X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/103X_dataRun2_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_relval_v4/103X_dataRun2_relval_v2):

### CODE REVIEW

**Comment by tocheng** [comment]
please test

**Comment by tocheng** [comment]
please test

**Comment by tocheng** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
