### PR TITLE
Trends by Lumiblock for Offline

### PR DESCRIPTION
**Pull request by folguera**
This duplicates some sequences for online/offline to make the trends vs Lumisection for online and vs Lumiblock for offline. 

I'd like some feedback from @fioriNTU and @hdelanno on this proposal before merging this.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @folguera - i'm confused by the title and the PR contents - the title suggests offline, but all the modules refer to "online"

**Comment by folguera** [comment]
Hi all, please do not merge this PR yet, we would like to do a couple more checks.

**Comment by folguera** [comment]
We would like to propose a different solution to this PR: #20386, which should be cleaner than the one asked for merging here.

**Pull request closed without merging**
