### PR TITLE
bsunanda:Run2-hcx41 HcalTopology depends only on HcalDDDRecConstants

### PR DESCRIPTION
**Pull request by bsunanda**
No need to have separate cfi files for HcalTopology producer for LHC and SLHC mode.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild @ianna Please start tests

**Comment by bsunanda** [comment]
@cmsbuild Please test
________________________________

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@bsunanda - please, remove also http://cmslxr.fnal.gov/source/Geometry/HcalEventSetup/python/hcalTopologyConstants_cfi.py?v=CMSSW_7_6_X_2015-10-13-2300

**Comment by bsunanda** [comment]
I have made the changes and removed all references to hcalTopologyConstants_cfi from other parts of the code. Hope this is OK.
@cmsbuild Please test
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test
________________________________

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
-1
No direct modification of HLT menu dumps.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Resolved conflicts and took suggestions from Martin for HLT related cfg files.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @lgray I want to rebase it by cherrypicking the relevant commits. I cannot do that. I get into a complaint when I tried to pick43a24059e6a080d7a73ec7555a07befbcd174125. Here is my list:
git cherry-pick 68bc298507dd74240244c0d0d11692fd099d2d94
git cherry-pick 95786e06d02ebb1a8016c2bd1dcfe55239a0c9fe
git cherry-pick 704bcab68b984d36743ec80fecfc0f20e4f2eb53
git cherry-pick 43a24059e6a080d7a73ec7555a07befbcd174125
git cherry-pick 5fc25cbe814f5bd0b19f85ccf3c5fdb63ec0c21f
git cherry-pick 987644c65e0a765431876ea063e7c24e2ad00f68
git cherry-pick 4d592caae5487af98313ea5686cf04b7a2143ada
git cherry-pick c03c0aa6bc17092e47a7f4e30ab91b3a31139fd8 
git cherry-pick fb7ebdc87da1eef489a6d6859608f8f410e294cc 
Please suggest what else can be done for this.

**Comment by lgray** [comment]
Hi Sunanda, if there's a complaint you have to fix the commit conflict.
It's not a show stopper.

**Comment by slava77** [comment]
-1
rebase needed

**Comment by bsunanda** [comment]
@ianna @lgray It complains about
error: addinfo_cache failed for path 'RecoLuminosity/LumiProducer/src/classes.h'
error: addinfo_cache failed for path 'MuonAnalysis/MomentumScaleCalibration/src/classes.h'
error: addinfo_cache failed for path 'GeneratorInterface/ExternalDecays/data/Bd_JpsiKPi.dec'
error: addinfo_cache failed for path 'Configuration/Generator/python/H125GGgluonfusion_13TeV_TuneCUETP8M1_cfi.py'
error: addinfo_cache failed for path 'CalibCalorimetry/EcalLaserAnalyzer/src/classes.h'
error: addinfo_cache failed for path 'CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/classes.h'
error: could not apply 43a2405... Remove all reference to HcalTopology_cfi.py
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
But removing the paths and committing does not help. If I want to trace back from the last commits at several places there are 2 mothers and the whole thing becomes a mess.
________________________________

**Comment by lgray** [comment]
Did you fix something in a merge commit?
That can cause major problems for this particular workflow.

**Comment by bsunanda** [comment]
Yes I did that. May be it could be better to start from scratch again.
________________________________

**Comment by bsunanda** [comment]
Close this and resubmit a new PR with similar changes (12143)

**Pull request closed without merging**
