### PR TITLE
Update hi mixing RelVal

### PR DESCRIPTION
**Pull request by mandrenguyen**
Updating the HI mixing workflows in RelVal to use new scheme based on the pp mixing module.
 As agreed upon with @franzoni

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
(errors are probably intermittent)

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1
the logic is ok as proposed by @mandrenguyen . Subject to ongoing tests.

**Comment by franzoni** [comment]
test ok => all good.

**Comment by davidlange6** [comment]
@mandrenguyen - this PR does not merge. Please rebase it

**Comment by mandrenguyen** [comment]
@davidlange6 
I resolved the conflicts with #8981 
Can someone please trigger a retest
@wouf, please double check that the merge looks ok

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
