### PR TITLE
Remove obsolete Validation/RecoEgamma test configuration

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Following the discussion https://github.com/cms-sw/cmssw/pull/28184#pullrequestreview-302666971 .

#### PR validation:

The code was unchanged since the CVS migration (at least) and seems definitely unused, no reason to maintain it if not needed

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
