### PR TITLE
Phase2-hgx348B Take care of handling both HGCal and HFNose access to Geometry and Topology classes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of handling both HGCal and HFNose access to Geometry and Topology classes. Takes care of invalid. DetId issue for the workflow 23234.0

#### PR validation:

Tested using the workflow 23234.0 in debug mode

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not special. Maybe the bug fix to be back ported for some earlier release which needs phase2 23234.0 for validation

### CODE REVIEW

**Comment by bsunanda** [comment]
type Bugfix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

regression problems only in MkFit WF

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
