### PR TITLE
L1t stage1 unpacker 76x

### PR DESCRIPTION
**Pull request by mulhearn**
This is the 76X version of PR #9908.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Hi @mulhearn 

Concerning the change to HLTrigger, I see that it is "just" the remove of these two parameters:
```
-    FWId = cms.untracked.int32( 2 ),
-    FedId = cms.int32( 1352 ),
```
from the (single) instance of the module:
```
process.hltCaloStage1Digis = cms.EDProducer( "L1TRawToDigi",
```
In that case, please do not edit the HLT menu dumps directly, but rather put it into
our CMSSW customisation file
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/HLTrigger/Configuration/python/customizeHLTforCMSSW.py
see there on how this is done for other PRs.
We add for 76X, then for 75X, and eventually when your PR is in 74X,
we update the dumps and remove the customisation.

**Comment by davidlange6** [comment]
@cmsbuild, looks like there is a commit here

**Comment by Martin-Grunewald** [comment]
@mulhearn 
Please address HLT as indicated above.

**Comment by mulhearn** [comment]
OK, will update PR today.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
I received a message that #9981 was merged. This is NOT ok for HLT; I did not sign nor did anyone else from HLT. Please revert asap!

**Comment by davidlange6** [comment]
i must have messed up.. will check

**Comment by davidlange6** [comment]
so i’m confused. 
I did merge #10163, which is the approved #10087 minus the data files. 

I see that #9981 is simply #10087 without two commits. 

So - unless you have a problem with #10087 despite signing it, we are ok. 

Anyway, let me know

**Comment by Martin-Grunewald** [comment]
OK, #10087 is fine!
(So I wonder why #9981 is labelled as merged as it is not quite #10087 ).

**Comment by Martin-Grunewald** [comment]
#9981 is not simply #10087 - the HLTrigger/Configuration change is different between the two.

**Comment by davidlange6** [comment]
i guess because its completely contained in 10087… but i’m guessing

**Pull request merged**
