### PR TITLE
New relvals workflows for JME customized nanoaod

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This adds workflows need to test JME customised NanoAOD.

Workflows: 25202.01 

More to come in this PR, this is just a quick version so JME can test.

#### PR validation:
Local test with https://github.com/cms-sw/cmssw/pull/28854 works well.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by chayanit** [comment]
please test workflow 25202.01

**Comment by srimanob** [comment]
@chayanit 
You need to test the workflow with https://github.com/cms-sw/cmssw/pull/28854

**Comment by chayanit** [comment]
please test workflow 25202.01 with #28854

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
@silviodonato 
If https://github.com/cms-sw/cmssw/pull/28854 is ready, please feel free to merge this. I think I will spend sometimes to make workflows in 2017/2018 by avoiding more complicated update in relval upgrade files.

**Comment by silviodonato** [comment]
@srimanob ok, I will integrate this as soon as #28854 is ready

**Comment by silviodonato** [comment]
hold
waiting for  #28854

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
+1

**Pull request merged**
