### PR TITLE
Fix for Ecal O2O test

### PR DESCRIPTION
**Pull request by ggovi**
Removed execution of EcalIntercalib_update_test since it requires specific input file

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi as far as I understand this is not solving the issue, just hiding it, right? Isn't this file available? I understand we are missing the test for a possible operation workflow in this way.

**Comment by ggovi** [comment]
@fabiocos 
yes, I expect the Ecal experts ( @depasse ) will comment and hopefully fix this

**Comment by ggovi** [comment]
+1

**Comment by depasse** [comment]
Hi,

I don't know what you want I comment.  If this must be suppressed, suppress it..
________________________________

**Comment by ggovi** [comment]
@depasse 
The comment we expect concern the possibility to have this test working, since it requires an xml input file to behave properly. I guess you know what input file it expects. 
Obviously we have the option to suppress it, but this will leave this workflow untested - as commented by Fabio.

**Comment by depasse** [comment]
The xml  files are the dumps of ADCToGeV and Intercalib tags (like the Bon/Boff....xml you suppressed online).  There is no workflow. As already said, it is used only to create a sqlite file from a xml file.
I can keep it private if needed.
________________________________

**Comment by ggovi** [comment]
@depasse we had already this discussion on a private thread. There 2 possibilities:
1. The command is calling CMSSW software that is no longer used
2. The command involves CMSSW software that is used to produce payloads for production.
In case 1, we can happily drop the test. In case 2, we need a test exercising the corresponding code.  As you may have noticed, I've added a test for all the part of the Ecal online code that I know is involved in the O2O. To my understanding, this one is used to produce the payload for the InterCalib tags. If this is the case, can you please make the concerned test working, since I'm unable, given that I'm not an Ecal experts. Hope this clarifies.

**Comment by jeanfay** [comment]
The proposition 1 from Giacomo is true :
The command is calling CMSSW software that is no longer used
We will upload a new version EcalIntercalibHandler.cc which reflects this fact

**Comment by ggovi** [comment]
@fabiocos 
ok I think this can be merged, the failing test is no longer required

**Comment by fabiocos** [comment]
@ggovi @jeanfay if the code is obsolete I agree. But it would be good to get rid of obsolete unused code, that just makes maintenance cumbersome in a useless way.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
