### PR TITLE
Faster setup of EventPrincipal

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Several optimizations to make the call to fillEventPrincipal more efficient. 

#### PR validation:

Framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The comparison failures are only from LogError harvester. I'm pretty confident the unit test failure is not related to this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical, jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@qliphy @agrohsje the change in the generator area is quite limited and technical, please have a look, I will integrate this PR in next IB

**Comment by fabiocos** [comment]
there is no real conflict with #28551

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
