### PR TITLE
Pr91x L1T calo, muon, uGT for 2017 (v93.6 minus v93.3,v92.24)

### PR DESCRIPTION
**Pull request by rekovic**
This is exactly the same code as the PR #18622.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
