### PR TITLE
[130X]: Add run3_miniAOD_12X modifier 

### PR DESCRIPTION
**Pull request by simonepigazzini**
#### PR description:

backport of #42740.

Modifier needed for reMINI campaign of 2022 (data/MC) and 2023 (data).

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
@rappoccio @antoniovilela backport to 131X and 132X will come in the next days.

**Comment by simonepigazzini** [comment]
image
image

Same checks as for the PR to the master, same results. All as expected

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+operations

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
