### PR TITLE
EMTF DQM plot updates

### PR DESCRIPTION
**Pull request by abrinke1**
Improvements to CSC LCT and RPC hit occupancy plots in EMTF Online DQM.

Taken from development code by @chadfreer which includes new quality tests: still in validation phase, to be added in a separate pull request soon-ish.

https://github.com/chadfreer/cmssw/tree/pull_ready_10_0_0_pre1

### CODE REVIEW

**Comment by abrinke1** [comment]
I don't know if anyone will be automatically pinged about this ... but @thomreis and @rekovic at least should be aware of it: and maybe give a +1 at some point?

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
Hi @abrinke1 
I do not have the right to give +1s. Anyway, this PR does not need a +1 from L1 since it only concerns DQM code. Please check and use a consistent indentation.

**Comment by abrinke1** [comment]
Hi @thomreis 
Thanks for looking at it.  I've fixed up the anomalous indents.  
 
To whom it may concern ( @vazzolini, @kmaeshima, @dmitrijus, @cmsbuild, @jfernan2, @vanbesien, @davidlange6, @slava77, @rekovic ), the L1T DPG (myself and Alex Zabi) would like to officially request that @thomreis get "+1" permissions for L1T code -- even if it's not relevant for this PR  -- since he is now our DQM and offline performance coordinator.  I'm not sure who sets these permissions, but let us know if there's anything preventing this.

Thanks much,
Andrew

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@abrinke1 Sorry, we cannot put over the shoulders of @thomreis the responsability of signing DQM PRs. Of course we are happy to have his opinion and advice in this and other PRs.
If this PR needs to be implement in Online DQM asap, please use the DQMP5TagCollector[1] and instructions therein. More about this and other matters in[2]

[1] https://twiki.cern.ch/twiki/bin/view/CMS/DQMP5TagCollector
[2] https://twiki.cern.ch/twiki/bin/view/CMS/DQMSequences

**Comment by abrinke1** [comment]
Hi @jfernan2 
Sorry for the confusion - I didn't mean for signing DQM PRs specifically (like this one).  I meant L1T software PRs.  I just figured that this list / audience might contain someone who knew how to do that.

This particular PR is not urgently needed for use online right now.

Best,
Andrew

**Comment by abrinke1** [comment]
Are there any comments or objections to this PR?  It's a very simple update.  Of course I know it's CMS week, as well ...
An ETA on merging this would be nice, since we're planning to build further improvements on top of it.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by abrinke1** [comment]
Thanks!

**Pull request merged**
