### PR TITLE
[12_4_X] Fix PPSDiamondDQM histogram of rechits in the last lumisection

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
PR fixes the the rechits plot which is suppose to represent the last lumisection. Before the fix plot was being filled with all the lumisections.

#### PR validation:
standard tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of #39076

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type bug-fix, ctpps

**Comment by ChrisMisan** [comment]
backport of #39076

**Comment by ChrisMisan** [comment]
please test

**Comment by emanueleusai** [comment]
@ChrisMisan do you need this deployed online?

**Comment by ChrisMisan** [comment]
> @ChrisMisan do you need this deployed online?

yes, it'd be good to have it online, also, we have another few corrections to this dqm coming in the next days.

**Comment by ChrisMisan** [comment]
@emanueleusai kind reminder

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
test completed and deployed at P5

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
