### PR TITLE
new MC pPb wf based on EposLHC_4080_4080GeV

### PR DESCRIPTION
**Pull request by fabozzi**
new pPb MC wf for HI
- gen fragment EposLHC_4080_4080GeV
- GT: auto:run2_mc_pa
- beamspot Run2PPbBoost
- customise RecoHI/Configuration/customise_PPwithHI.customisePPrecoforPPb
- AODSIM as output

### CODE REVIEW

**Comment by fabozzi** [comment]
@mandrenguyen @mmusich 
you are interested to this wf due to #16109

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
