### PR TITLE
Run3-gex62z Update PrintGeomInfo to give statistics for touchables

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update PrintGeomInfo to give statistics for touchables

#### PR validation:

Use scripts in SimG4Core/PrintGeomInfo/test/python 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
