### PR TITLE
Including now monitoring for 0 Tesla paths.

### PR DESCRIPTION
**Pull request by parbol**
This pull request adds the monitoring for two 0 tesla paths HT+MET and Photon+HT

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @parbol 
the code looks ok, but I am wondering about the 0T paths you want to monitor. I guess the are only available in the 0T HLT menu right? if yes doesn't make much sense to monitor them all the time.
can you please clarify?
thanks,
F.

**Comment by parbol** [comment]
Hi Federico,

Yes, that's right, we only need this monitored for the 0 Tesla menu, however we are not allowed to have the triggers in in the menu until the PR is approved.

**Comment by deguio** [comment]
ciao @parbol 
from what I see the modules you added run only in the validation sequence (i.e. on RelVals only and not at the T0). I checked with PdmV and there are no workflows that run the 0T HLT menu. in summary the 0T paths you added will never fire.
F.

**Comment by deguio** [comment]
how do we proceed with this?
F.

**Comment by deguio** [comment]
-1
needs clarification

**Pull request closed without merging**
