### PR TITLE
New Global Tags with fixes and new features for Run1 and Run2

### PR DESCRIPTION
**Pull request by mmusich**
Several new features included for Run1, Run2 DATA and MC Global Tags. Complete description available at [RelValGT](https://twiki.cern.ch/twiki/bin/viewauth/CMS/RelValGT#CMSSW_7_5_0_pre5).

### CODE REVIEW

**Comment by mmusich** [comment]
running locally `runTheMatrix.py -l limited` yields
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 18:55:54 2015-date Wed May 27 18:43:42 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 19:16:10 2015-date Wed May 27 18:43:44 2015; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed May 27 18:55:08 2015-date Wed May 27 18:43:49 2015; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 18:57:21 2015-date Wed May 27 18:43:50 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECO+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 19:23:20 2015-date Wed May 27 18:55:14 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed May 27 19:15:42 2015-date Wed May 27 18:55:57 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed May 27 19:13:14 2015-date Wed May 27 18:57:31 2015; exit: 0 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 19:31:38 2015-date Wed May 27 19:13:23 2015; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 19:27:31 2015-date Wed May 27 19:15:47 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed May 27 19:24:09 2015-date Wed May 27 19:16:10 2015; exit: 0 0 0 0
10 10 9 7 6 tests passed, 0 0 0 0 0 failed
```

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
@mmusich - is the documentation of whats changing in the GT still in progress or do I just miss it?

**Comment by mmusich** [comment]
@davidlange6 I am in course of documenting them. I spotted a problem in the MC global Tags MagField configuaration that entered the GTs. We are fixing it. A commit for that is coming soon.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test failures are unrelated to the PR

**Comment by mmusich** [comment]
Failures are expected, given removal of the old `MVASelectorIter{0..6}_13TeV_v0` label. This PR needs to be merged together with #9119

**Comment by slava77** [comment]
Hi Marco and Salvatore

Smoother transitions would be greatly appreciated at least for incremental
testing.
Maybe we can privately get minor versions of gt with just one set of
payloads. This one combines changes both in tracking and pf .. and probably
more

**Comment by diguida** [comment]
@slava77 
The feature you want is the GT queue. Once a request by a DPG is approved, it goes to an "open" Global Tag that can be tested. Current Global Tags will become "snapshots" of the queue. Audrius is completing the transition on the DB backend now.

For this particular case, we can offer you 3 sets of Global Tags:

* the maximal ones, i.e. the one in this PR;
* PF calibration only, i.e. pre4 GT with the updated PF hadron calibration
* MVA selectors only, i.e. pre4 GT with the new labels for updated MVA track selectors, removing the old labels (so that we can check if there are missing updates in the configuration).

Does it sound reasonable?

**Comment by slava77** [comment]
On 5/28/15 4:33 AM, Salvatore Di Guida wrote:
> @slava77 <https://github.com/slava77>
> The feature you want is the GT queue. Once a request by a DPG is
> approved, it goes to an "open" Global Tag that can be tested. Current
> Global Tags will become "snapshots" of the queue. Audrius is completing
> the transition on the DB backend now.
> 
> For this particular case, we can offer you 3 sets of Global Tags:
> 
>   * the maximal ones, i.e. the one in this PR;
>   * PF calibration only, i.e. pre4 GT with the updated PF hadron calibration
>   * MVA selectors only, i.e. pre4 GT with the new labels for updated MVA
>     track selectors, removing the old labels (so that we can check if
>     there are missing updates in the configuration).
> 
> Does it sound reasonable?


Hi Salvatore,

This will be perfect.


		--slava

**Comment by cerminar** [comment]
Hi @slava77  
I just discussed the situation with @mmusich and @diguida and I don't think that they will be able to deliver the set of GTs that you requested to break-down the changes in a timely fashion given the priority on the preparation of the conditions for the data of next week.

This might cost further delay for this (open) pre-release. 
Cheers,
G

**Comment by slava77** [comment]
ok, I'll test all combined.
Hopefully features can be decoupled visually.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@igv4321 as we discussed in today's AlCa meeting this commit has been cherry-picked by #9119 through https://github.com/mhwalker/cmssw/commit/f2ee2cd85f89dcb86a5ab5e774cbbeab2442b7f7 so the new GTs including the negative energy filter payload are already available in the HEAD version of the release.

**Comment by slava77** [comment]
@mmusich 
Marco, shouldn't you just close this PR since the code is already in 75X?

**Pull request closed without merging**
