### PR TITLE
Fix bug spoling PV sorting on W' and Z'. Override default ptMax cut

### PR DESCRIPTION
**Pull request by arizzi**
tested on 30 W' events, events with PV of 3rd genparticls vs reconstructed PV[0] separated by more than 2mm.

before:

```
************************
*    Row   * recoGenPa *
************************
*        3 * -1.504770 *
*       13 * 1.1502714 *
*       17 * 3.9613052 *
*       20 * 13.721727 *
*       21 * 11.256953 *
*       24 *   9.19751 *
*       25 * -0.218671 *
************************

after:

************************
*    Row   * recoGenPa *
************************
*        3 * -1.504770 *
*       17 * 3.9613052 *
*       21 * 11.256953 *
*       25 * -0.218671 *

```

### CODE REVIEW

**Comment by arizzi** [comment]
@slava77  @gpetruc there are still 4 events with wrong PV... figuring out what's going on

**Comment by arizzi** [comment]
for example in the second event I see pt,pterr
 1727.7861 , 470.70268 
so we need a more complex bug fix trying to take into account the error that is kind of unknown to the Candidate interface.

The fix is not trivial because we need to
- flag the fastjet input with indices to be able to retrieve them
- sum in quadrature the pt-errors
- compute a per-jet error instead of the fixed 20% uncertainty
- remove the ptError cut in the input selector
- validate against all samples (not just W' at this point)
I can try to implement the above tomorrow.

An intermediate solution is to tune the ptError cut but we risk fakes in all other events.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
now with pt error changes... I guess those are wrong also in 72X sorting
```
************************
*    Row   * recoGenPa *
************************
*        3 * -1.504770 *
*       25 * -0.218671 *
************************
```

**Comment by arizzi** [comment]
just to confirm that the original PV are also wrong for those events (below: originalPV, genPart[2].vz, sortedPV)

```
************************************************
*    Row   * recoVerte * recoGenPa * recoVerte *
************************************************
*        3 * 0.2486938 * -1.256076 * 0.2486938 *
*       25 * 5.2059893 * 4.9873180 * 5.2059893 *
************************************************

```

**Comment by slava77** [comment]
Hi Andrea, unless there's a clear need from current tests to make an update, may I suggest to make no updates here.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Here are some notes from comparisons with CMSSW_7_5_0_pre5 as a baseline (test area sign565)

- In min-bias like events there are occasional changes, similar vertices change order

- in more jetty events, ttbar run1 (PU~20) and ttbar run2 (PU=35) several events have a different PV[0]

- events with high-pt muons (Wprime M=5600 GeV with PU=35) look as expected: 
    - only pf lepton isolation changes; detector-based is unchanged
    - about 20% more tight muons (vertex dZ cut at 0.2 cm)
wf1314m5600_tightmuid_vs_pt
    - tracks with pt above 500 GeV are now close to the primary vertex
wpm13m5600puwf1314_pass-1356a01-orig-generaltracks_pv0_dz_lt01_vs_pt_hp
    - these are all in line with the PV validation: the true PV is back in place at index 0
wf1314m5600_truepv

Exotica muon selections in MonoMuon DQM appear to have significant dependence on PV selection and is also using the PV association for PFMET
wf1314m5600_monomuon_pt
wf1314m5600_monomuon_pfmet

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9654	1356a01
- tested in CMSSW_7_5_0_pre5 /test area sign565/
- additional 200 events are included in tests for Wprime to munu M=5600 GeV with PU=35 
- behavior is as expected: 
    - recovery of correct primary for events with pt above 500 GeV is the main effect; 
    - small changes for events without tracks above 500 GeV are in line with the added subtraction of the pt error from the sum used in the score of the vertex (occasional change expected)

@bachtis

**Comment by davidlange6** [comment]
+1

**Comment by arizzi** [comment]
is the change on ttbar going in the right direction? ttbar has 99% correct
assignment eff usually are the changes spoiling it
Il 18/giu/2015 19:17, "Slava Krutelyov" <notifications@github.com> ha
scritto:

**Comment by slava77** [comment]
I didn't look in detail in the ttbar (the changes were from a single event change in both 202 and 25202):
truePV DQM plots  didn't change; so, I concluded that the change was on one of the minbias-related vertices.

**Pull request merged**
