### PR TITLE
Run2-alca142 Update correction to scripts for IsoTrack calibration

### PR DESCRIPTION
**Pull request by bsunanda**
In view of using non-MIP tracks in ECAL

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@tocheng @lpernie Can you approve this PR?

**Comment by bsunanda** [comment]
@tocheng @lpernie Ping again

**Comment by fabiocos** [comment]
@tocheng @lpernie @pohsun could someone please check this PR?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
