### PR TITLE
Add a `zeroInitialise()` method to portable objects and collections

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a `zeroInitialise()` method to the `PortableObject` and `PortableCollection` templates that erases the data in the `Buffer` by writing zeros (bytes containing `'\0'`) to it:

  - on the host, `zeroInitialise()` can be called without arguments to execute immediately, or with a queue to be run asynchronously;

  - on the device, `zeroInitialise()` requires a queue and can only be run asynchronously.

Extend the tests in `DataFormats/PortableTestObjects` and `HeterogeneousCore/AlpakaTest` to validate the new functionality. 

#### PR validation:

The update unit tests pass on CPU and NVIDIA GPUs.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Review by makortel — COMMENTED** [review]
Looks good to me

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
