### PR TITLE
73 Calo Tower presentation for AOD and miniAOD data

### PR DESCRIPTION
**Pull request by alja**
- new pat::PackedCandidate CaloTower presetation
- new reco::PFCandidate Calo Tower presentation
- new miniaod configuration file

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by alja** [comment]
'merge'

**Comment by ktf** [comment]
@alja you have no rights to merge. You need to say "+1". I'll bypass for this time.

**Pull request merged**
