### PR TITLE
Modernize some EGamma Reco modules

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- added remaining esConsumes calls.
- updated helper classes to use ConsumesCollector.
- Applied some code modernization
- reworked LowPtGsfElectronIDProducer to be more efficient

#### PR validation:

Code compiles. None of the changes are meant to change behavior.

### CODE REVIEW

**Comment by slava77** [comment]
abort test

30hrs since the last request doesn't look healthy

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Ping @cms-sw/reconstruction-l2

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35021	d73e61c
- code changes are technical, in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
