### PR TITLE
Implemented new cumulative histograms and made independent from any …

### PR DESCRIPTION
**Pull request by dinardo**
…previous(old) beamspot values

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
online only

**Comment by dinardo** [comment]
Hi, I was wondering why this is still open.
Were you able to merge ?
Many thanks,
- Mauro.

**Comment by deguio** [comment]
we are focusing mostly on 75 for now.
this PR an others will be merged in one of the coming 76x builds.
ciao,
F.

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
