### PR TITLE
Several updates to SiPixel LA PCL workflow

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Miscellanea updates and bug-fixes to the SiPixel LA PCL workflow that are built on top of the replay at https://github.com/dmwm/T0/pull/4635: 
   * made the processing much faster by calling `SiPixelTemplate::pushfile` in `dqmBeginRun`  instead of the `analyze` method;
   * add basic accepted tracks monitoring;
   * adding plot titles;
   * re-organize folders to have subfolders: (Top) / (BPix) / etc. ..;
   * actually *do* write to DB the values for the "new" modules when they are fit;
   * change the default cut value on the fit probability for writing out the payload from 0.5 to 0.1;
   * fix a bug that was causing populating the lists of "new" modules and modules attached to a given "sector" multiple times (this was triggering several warnings in the harvesting step when populating the DB about multiple `put`s, see https://github.com/cms-sw/cmssw/pull/36535);
  
#### PR validation:

Run:

```
 cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiPixelLorentzAngle --conditions 121X_dataRun3_Express_TIER0_REPLAY_Run2_v1 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100 --dasquery='file dataset=/StreamExpress/Tier0_REPLAY_2021-SiPixelCalSingleMuon-Express-v1/ALCARECO' --customise_commands='process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.TriggerResultsTag = cms.InputTag ( "TriggerResults","","HLT" ) ; process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.HLTPaths = ["*"]' --nThreads=4 
```

followed by:

```
 cmsDriver.py stepHarvest -s ALCAHARVEST:SiPixelLA --conditions 121X_dataRun3_Express_TIER0_REPLAY_Run2_v1 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiPixelLorentzAngle.root -n -1
```

the results are uploaded to a private DQM GUI at  https://tinyurl.com/y4dm6s98:
   * necessitates tunneling (`ssh -NL 8060:localhost:8060 <USER>@lxplus723.cern.ch`). 
   
An example of the result is link to the companion PR to `dmwm`: https://github.com/dmwm/deployment/pull/1118

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but might be backported

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1001.2

**Comment by mmusich** [comment]
While running the debugging I noticed that the module `SiPixelLorentzAnglePCLWorker` was extremely slow.
This was due to calling `SiPixelTemplate::pushfile` in the `analyze` method at each event.
Moving it to `dqmBeginRun`  in the last commit (47a4146) there's a significant speed-up of the amount of time passed in `SiPixelLorentzAnglePCLWorker`.

   * Baseline:  http://musich.web.cern.ch/musich/cgi-bin/igprof-navigator/ig_SiPixelLA/9
image

   * This PR: http://musich.web.cern.ch/musich/cgi-bin/igprof-navigator/ig_SiPixelLA_new/199
image

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
With the last update the memory usage is under control (or at least at the same level of before), and the timing much improved, as reported at https://github.com/cms-sw/cmssw/pull/36538#issuecomment-996839642:
memory

for reference here also for 100k events:
memory_target

There are certainly more improvements needed in the module `SiPixelLorentzAnglePCLWorker` to further reduce the memory footprint (e.g. it can become a `DQMGlobalEDAnalyzer`), but I leave those for a follow-up PR (attn: @wweiphy)
Also some more work is foreseen in the `SiPixelLorentzAnglePCLHarvester` to improve on the monitoring of the output payload.
I am switching this PR to ready for review.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * tests pass, diffs in MsgLogger only
 * code changes are in line with the PR description
 * I think we should do a backport to 12_1_X, @mmusich

**Comment by mmusich** [comment]
@tvami 

> I think we should do a backport to 12_1_X

sure, though we might want to wait for the rest of the developments suggested at https://github.com/cms-sw/cmssw/pull/36538#issuecomment-997267225 to land to avoid multiple backports.
Also, since in my understanding 12_2_0 should be available in a few weeks (beginning of 2022 IIU), if the intention is to make the updates available for further Tier-0 replays, wouldn't suffice to backport to 12_2_X instead?

**Comment by tvami** [comment]
> wouldn't suffice to backport to 12_2_X instead?

Yes, you are right, that's indeed sufficient

**Comment by mmusich** [comment]
@cms-sw/orp-l2 is there anything holding up this PR?

**Comment by perrotta** [comment]
@mmusich , as there is no need to  affix any sort of `endl` to the LogMessages [1], would you mind cleaning the code in SiPixelLorentzAnglePCLHarvester.cc from them? (They are likely remnants of when those messages were `cout`'s)

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger

**Comment by mmusich** [comment]
@perrotta 

> as there is no need to affix any sort of endl to the LogMessages [1], would you mind cleaning the code in SiPixelLorentzAnglePCLHarvester.cc from them? (They are likely remnants of when those messages were cout's)

As far as I can tell there's no functional difference in having them or not, so I take your comment is purely aesthetical (matter of taste).
In any case, can it be done in a follow-up PR?
This one delivers a rather major performance improvement and there is more to come soon.

**Comment by perrotta** [comment]
> As far as I can tell there's no functional difference in having them or not, so I take your comment is purely aesthetical (matter of taste). In any case, can it be done in a follow-up PR? This one delivers a rather major performance improvement and there is more to come soon.

Yes, aestetical (even not just "matter of taste", since clean code is always easier to read and maintain): "would you mind" in my message was exactly referring to that.
I agree that this PR can be also merged as such, and I also don't urge to have those updates done.

**Comment by perrotta** [comment]
+1

**Pull request merged**
