### PR TITLE
Move Cosmics During Collisions Reconstruction to ALCARECO 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is two-fold:
   * move the CDC (Cosmics During Collisions) reconstruction out of the standard (p-p) reconstruction sequence and include it into the `TkAlCosmicsInCollisions` ALCARECO. This in turn allows to freely change the parameters in order to optimize for efficiency / acceptance at the cost of increase of timing, as the ALCARECO will be run only on the `NoBPTX` dataset and not in dense events where the seeding and candidate building explodes.
   *  thanks to the first point, the seeding and track building parameters have been optimized. Optimization has been done in order to increase the reconstruction efficiency of real interfill cosmics tracks undergoing the CDC reco.

#### PR validation:

The results of the parameter optimization have been presented [here](https://indico.cern.ch/event/879451/contributions/3873497/attachments/2045049/3425922/FollowUp_Cosmics_during_Collisions.pdf). The setup chosen here is corresponding to `TEST13`.
Detailed timing studies on the various setups have been produced by @mtosi and are collected in this [spreadsheet](https://docs.google.com/spreadsheets/d/1j4X3wbI6CbgSVHQKl8CU-ToU2gyZLaZcnT86hRR79uI/edit#gid=0).

This branch has also been technically tested by running the following command.
```
cmsDriver.py stepTest --conditions auto:run2_data -s RAW2DIGI,L1Reco,RECO,ALCA:TkAlCosmicsInCollisions --process reRECO --data --era Run2_2018 --eventcontent RECO,ALCARECO --scenario pp --datatier RECO,ALCARECO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2018 -n 10000 --dasquery='file dataset=/NoBPTX/Run2018B-v1/RAW site=T2_CH_CERN' --nThreads=8 --no_exec
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.
cc:
@mtosi, @connorpa @vbotta

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test workflow 136.735, 136.803, 136.894

**Comment by mtosi** [comment]
CPU timing measurement on CDC events from run 324897 gives the following
- cosmicDCSeeds : 8.2 ms
- cosmicDCCkfTrackCandidates : 9.1 ms
- cosmicDCTracks : 0.5 ms

**Comment by pohsun** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30248 c885a6e
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show differences only related to the move/removal of cosmicDCTracks producer/products

**Comment by silviodonato** [comment]
+1

**Pull request merged**
