### PR TITLE
BTV HLT monitoring: exclude paths requiring `pfMassDecorrelatedParticleNetDiscriminatorsJetTags` when `pp_on_PbPb_run3` is active

### LINKED ISSUE #44899: ProductNotFound exception in workflow 142.0
Workflow 142.0 step 3 fails with
```
----- Begin Fatal Exception 03-May-2024 08:02:39 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 375491 lumi: 100 event: 98282466 stream: 1
   [1] Running path 'dqmoffline_step'
   [2] Prefetching for module TopMonitor/'BTagMu_AK8Jet300_Mu5'
   [3] Prefetching for module BTagProbabilityToDiscriminator/'pfMassDecorrelatedParticleNetDiscriminatorsJetTags'
   [4] Prefetching for module BoostedJetONNXJetTagsProducer/'pfMassDecorrelatedParticleNetJetTags'
   [5] Calling method for module DeepBoostedJetTagInfoProducer/'pfParticleNetTagInfos'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Jet
Looking for module label: ak8PFJetsPuppi
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-05-02-2300/pyRelValMatrixLogs/run/142.0_RunHIPhysicsRawPrime2023A/step3_RunHIPhysicsRawPrime2023A.log#/

since CMSSW_14_1_X_2024-05-01-2300

### PR DESCRIPTION
**Pull request by mmusich**
fixes https://github.com/cms-sw/cmssw/issues/44899

#### PR description:

Title says it all, for description see https://github.com/cms-sw/cmssw/issues/44899.

#### PR validation:

```
runTheMatrix.py -l 142.0 -t 4 -j 8 --ibeos
```

now runs

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 142.0

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovilela** [comment]
ping @cms-sw/dqm-l2

**Comment by rappoccio** [comment]
+1

Bypassing DQM signatures.

**Comment by tjavaid** [comment]
+1

**Pull request merged**
