### PR TITLE
Central bunch spacing producer for 76x

### PR DESCRIPTION
**Pull request by davidlange6**
#11544 but for 76x.

### CODE REVIEW

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by deguio** [comment]
please test

**Comment by smuzaffar** [comment]
pelase test

**Comment by slava77** [comment]
I checked this locally including run2 relval 2015B and 2015C data workflows and confirm no differences.
The only problem is the cout.

**Comment by civanch** [comment]
@davidlange6 , in BunchSpacingProducer uncontrolled std::cout is left...

**Comment by davidlange6** [comment]
yes, I’m aware

**Comment by smuzaffar** [comment]
Could this be the PR due to which we have unit test failing IBs?
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-10-15-2300/unitTestLogs/RecoMET/METProducers

**Pull request merged**
