### PR TITLE
Option to use old CPE error if charge exceeds one MIP

### PR DESCRIPTION
**Pull request by wmtford**
If useLegacyCPE is false and a positive value is given for maxChgOneMIP, ignore the merged status of the cluster and set the CPE error to the new value if chargePerCM is < maxChgOneMIP, else set the old value.  This cut is more robust against pileup than the sensor occupancy cut used to flag a cluster as merged.  We set the cut to -6000 in the config, where 6000 is a reasonable choice to turn on this selection.

### CODE REVIEW

**Comment by mtosi** [comment]
ciao,
is it possible to back port this PR to 73x ?
it would be really useful in order to synch offline and HLT, indeed
(HLT developments are still done in 73x)

thanks much
@perrotta @Martin-Grunewald @wmtford @VinInn @rovere

**Comment by wmtford** [comment]
Hi Mia,

I can make a PR for this.  Do we want the default to be UseLegacyError 
True?  With a customization to turn on the new CPE if 1 MIP?

Bill

**Comment by Martin-Grunewald** [comment]
Yes, the defaults should be sucgh that they do not change the physics behavior compared
to not having this PR!

**Comment by Martin-Grunewald** [comment]
Can you make the PR really asap (ie, NOW)- then we can try to get it in 731 which should
be built today. Thanks!

**Comment by mtosi** [comment]
as Martin wrote, yes please
the default configuration should guarantee the old behaviour

thanks a lot !

**Comment by wmtford** [comment]
Done, PR #7241.

Sorry for the delay; I'm 8 time zones behind.

Bill

**Comment by mtosi** [comment]
thanks much !!!!!

**Pull request merged**
