### PR TITLE
Histograms for L1T Stage1

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by deguio** [comment]
ciao @jingyucms 
can you submit to 75 first? we want to test and merge there before backporting to 74.
thanks,
F.

**Comment by jingyucms** [comment]
Thanks @deguio 
Done submit to 75, please review.

**Comment by ktf** [comment]
@deguio What's the status on this?

**Comment by deguio** [comment]
+1

**Comment by jingyucms** [comment]
@ktf Can this be merged?

**Comment by ktf** [comment]
needs @davidlange6 approval

**Comment by davidlange6** [comment]
+1

**Pull request merged**
