### PR TITLE
fix for #19290

### PR DESCRIPTION
**Pull request by fwyzard**
Make sure each SUSY Ele+Jet path is monitored in a separate DQM folder

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
This should fix the exception introduced by #19290 (via #19891)

**Comment by fwyzard** [comment]
@parbol can you check that this gives the intended behaviour ?

**Comment by fwyzard** [comment]
OK, this works fine locally:
```
Preparing to run 136.784 RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017

# in: /data/user/fwyzard/CMSSW_9_3_X_2017-07-25-1100/matrix going to execute cd 136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017
 echo '{
"297227" : [[1, 45]]
}' > step1_lumiRanges.log  2>&1
 

# in: /data/user/fwyzard/CMSSW_9_3_X_2017-07-25-1100/matrix going to execute cd 136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017
 (das_client --limit 0 --query 'lumi,file dataset=/MET/Run2017B-v1/RAW run=297227' --format json | das-selected-lumis.py 1,45 ) | sort -u > step1_dasquery.log  2>&1
 
---

# in: /data/user/fwyzard/CMSSW_9_3_X_2017-07-25-1100/matrix going to execute cd 136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017
 cmsDriver.py step2  --datatier FEVTDEBUGHLT --conditions auto:run2_hlt_relval -s L1REPACK:Full,HLT:@relval2017 --process reHLT --data  --era Run2_2017 --eventcontent FEVTDEBUGHLT -n 100  --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root  > step2_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017.log  2>&1
 

# in: /data/user/fwyzard/CMSSW_9_3_X_2017-07-25-1100/matrix going to execute cd 136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017
 cmsDriver.py step3  --conditions auto:run2_data_promptlike -s RAW2DIGI,L1Reco,RECO,SKIM:HighMET+EXOMONOPOLE,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQM+@miniAODDQM --runUnscheduled  --process reRECO --data  --era Run2_2017 --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp --datatier RECO,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2017 -n 100  --filein file:step2.root  --fileout file:step3.root  > step3_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017.log  2>&1
 

# in: /data/user/fwyzard/CMSSW_9_3_X_2017-07-25-1100/matrix going to execute cd 136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017
 cmsDriver.py step4  --conditions auto:run2_data_promptlike -s HARVESTING:@standardDQM+@miniAODDQM --scenario pp --filetype DQM --data  --era Run2_2017 -n 100  --filein file:step3_inDQM.root --fileout file:step4.root  > step4_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017.log  2>&1
 
136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jul 26 00:14:25 2017-date Tue Jul 25 23:59:26 2017; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by parbol** [comment]
Hi Andrea,

Thank you very much for taking care of this. I've been away for a few days and couldn't follow this up. I'm a bit lost with the whole thing, and I see there are still failures, but I'm not sure I understand them. Can you tell me your vision on what's going on and I take it over? 

Thanks

Pablo

**Pull request merged**
