### PR TITLE
Update BasicGenValidation_cff.py

### PR DESCRIPTION
**Pull request by menglu21**
add sequence for higgs/ttbar separate validation

#### PR description:
The changes made are for the sample validation using McM, people can now choose higgs/dy/top/w/qcd process to be validated. The top/higgs parts are added by imitating the existing dy/qcd... In the output rootfile, there will be additional branch for VALIDATIONS. The slides are https://indico.cern.ch/event/878706/contributions/3761830/attachments/1993587/3324981/GENvalidation.pdf

#### PR validation:
Validation done by following steps:
1. cmsrel CMSSW_7_1_45_patch3
2. cd src & cmsenv
3. git add-cmspkg Validation/EventGenerator & modify the BasicGenValidation_cff.py
4. cd ../../
5. ./aa
where aa is https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/SMP-RunIISummer15wmLHEGS-00378, the request is set to run 'higgs' content validation.

The output is:
`...
LHE,GEN,SIM,VALIDATION:genvalid_higgs
Step: LHE Spec: 
Loading lhe fragment from Configuration.GenProduction.SMP-RunIISummer15wmLHEGS-00378-fragment
Step: GEN Spec: 
Loading generator fragment from Configuration.GenProduction.SMP-RunIISummer15wmLHEGS-00378-fragment
Step: SIM Spec: 
**Step: VALIDATION Spec: ['genvalid_higgs']
genvalid_higgs in preparing validation**
customising the process with addMonitoring from Configuration/DataProcessing/Utils
customising the process with customisePostLS1 from SLHCUpgradeSimulations/Configuration/postLS1Customs
customising the process with setCrossingFrameOn from SimGeneral/MixingModule/fullMixCustomize_cff
Config file SMP-RunIISummer15wmLHEGS-00378_1_cfg.py created
==> using COND/Services/RelationalAuthenticationService for auth, sys 1
==> using COND/Services/RelationalAuthenticationService for auth, sys 1
   ______________________________________     
         Running Generic Tarball/Gridpack     
   ______________________________________     
gridpack tarball path = /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.2.2/dyellell012j_5f_NLO_FXFX_M100to200/v1/dyellell012j_5f_NLO_FXFX_M100to200_tarball.tar.xz
%MSG-MG5 number of events requested = 98
%MSG-MG5 random seed used for the run = 52
%MSG-MG5 thread count requested = 1
%MSG-MG5 residual/optional arguments =
...`

From the log, the genvalidation_higgs is compiled successfully, and a rootfile is obtained eventually.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
@menglu21 have you performed some test/validation over this change? If so, can you please post your results along with some description in the PR header as requested? Thanks

**Comment by menglu21** [comment]
> @menglu21 have you performed some test/validation over this change? If so, can you please post your results along with some description in the PR header as requested? Thanks

Hi, i updated the PR header with the validation step and results, the log is not full but only with the important parts.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by srimanob** [comment]
@menglu21 
Does this PR should be backported to 10_6 at least?

@qliphy @pgunnell

**Comment by pgunnell** [comment]
yes, we provided @menglu21  with the list of relevant releases for production

**Comment by menglu21** [comment]
Hi all,
Sorry for the delay, i'll do the backporting.

**Pull request merged**
