### PR TITLE
Low pT electrons (up to GsfTracks) for 10_5_X

### PR DESCRIPTION
**Pull request by bainbrid**
This PR is equivalent to the open [#25455](https://github.com/cms-sw/cmssw/pull/25455) PR, but rebased to 10_5_X using a very recent IB.

This PR was opened in response to [this](https://github.com/cms-sw/cmssw/pull/25455#issuecomment-454719227) instruction.

### CODE REVIEW

**Comment by bainbrid** [comment]
This PR depends on the BDT models included in cms-data/RecoEgamma-ElectronIdentification#10

**Comment by bainbrid** [comment]
@mverzett @nancymarinelli @gkaratha

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- This is identical to #25455, while rebased to a newer IB: I sign both versions, so that @fabiocos will chose what to merge if and when it will get merged by everybody. I'm also repeating here the same comments as in #25455, for the record
- New gsf electrons, with higher efficiency expected at low pt, are defined here to be used in the reco-ing of the parked b dataset
- The extra product will be just added to the Event, but it is not used to build any further higher level object (e.g PF) at the moment
- The lose working point to be used for the parked dataset implies a rather heavy usage of cpu (it amounts to ~12.4% time of the overall reco + miniAOD time). For the normal workflows a tighter working point was defined, whose cpu usage corresponds to ~4.3% of the total reco + miniAOD processing time: the efficiency for low pt photons get reduced by some 25% with respect to the looser working point, though.
- The tests show that only the new objects are added in output, while nothing else show differences in reco or miniAOD: jenkins tests report about 12 differences in the reco comparisons from the Phase2 workflows, and they all correspond to the additional warning messages issued by the PFTrackProducer:lowPtGsfElePfTracks module in step3 on top of the same warnings coming from the already existing PFTrackProducer:pfTrack and PFTrackProducer:uncleanedOnlyPfTrack, already present also in the baseline.

**Comment by fabiocos** [comment]
@ssekmen could you please review and comment this PR for the fastsim part?

**Comment by fabiocos** [comment]
+operations

the StandardSequences and Era updates are coherent with the purpose of the PR

**Comment by perrotta** [comment]
@bainbrid , could you please remind me why ```lowPtGsfElectronSequence``` is included directly at the end of the ```highlevelreco``` sequence in ```Configuration/StandardSequences/python/Reconstruction_cff.py```, instead of including it in the ```egammaHighLevelRecoPrePF``` sequence in ```RecoEgamma/Configuration/python/RecoEgamma_cff.py```? (I think we discussed it already, but I managed to forget it...)

**Comment by bainbrid** [comment]
@perrotta The ```LowPtGsfElectronSeedProducer``` consumes the ```reducedEcalRecHitsEB``` and ```reducedEcalRecHitsEB``` collections, which are produced as part of the ```reducedRecHits``` sequences, which is scheduled late in the ```highlevelreco``` sequence. It was suggested by you or Slava to move the ```lowPtGsfElectronSequence``` here.

**Comment by fabiocos** [comment]
@ssekmen this development is important for the B parking reprocessing and analysis, could you please review it?

**Comment by slava77** [comment]
On 1/19/19 3:03 AM, bainbrid wrote:
> @perrotta
> The |LowPtGsfElectronSeedProducer| consumes the |reducedEcalRecHitsEB|
> and |reducedEcalRecHitsEB| collections, which are produced as part of
> the |reducedRecHits| sequences, which is scheduled late in the
> |highlevelreco| sequence. It was suggested by you or Slava to move the
> |lowPtGsfElectronSequence| here.
> 
> —

I can't recall suggesting that.
What is the reason the reduced hits are used?
The reduced collection is technically meant to hold hits which were used
to reconstruct lower level objects.
I would naively think that the low-pt electron reco should avoid this bias.

**Comment by perrotta** [comment]
I removed the "+1" while waiting verification of the usage of reducedEcalRecHits instead of full ecalRecHits

**Comment by ssekmen** [comment]
+1

**Comment by perrotta** [comment]
Please @bainbrid and/or @mverzett verify the usage of reducedEcalRecHits instead of full ecalRecHits and report here (or at least provide an estimate about when it can be done)

**Comment by bainbrid** [comment]
@perrotta, we can and will switch to the full ECAL RecHits collection - I'll try to do this (and check it) this evening.

**Comment by bainbrid** [comment]
@perrotta ```LowPtGsfElectronSeedProducer``` now consumes uses the full ```ecalRecHit``` collections, instead of the ```reducedEcalRecHits``` collections, commit [here](
https://github.com/cms-sw/cmssw/pull/25679/commits/2a1ad40a6cdc091c5660a1a8b353313d42426f89). The effect on the BDT output is minimal (which will anyway be retrained using 10.2 MC) and the effect on CPU has been checked and is negligible.  

I've also moved the ```lowPtGsfElectronSequence``` from ```highlevelreco``` to ```egammaHighLevelRecoPrePF```, as suggested above. 

If this is ok with you, I will propagate these changes to all other relevant PRs.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Changes since https://github.com/cms-sw/cmssw/pull/25679#issuecomment-455161723 only consist in using the full ecal recHits, instead of the reduced ones in the config
- New gsf electrons, with higher efficiency expected at low pt, are defined here to be used in the reco-ing of the parked b dataset
- The extra product will be just added to the Event, but it is not used to build any further higher level object (e.g PF) at the moment
- According to https://github.com/cms-sw/cmssw/pull/25679#issuecomment-456193194 the same comments on performance as reported in https://github.com/cms-sw/cmssw/pull/25679#issuecomment-455161723, and are copied here for convenience:
  - The lose working point to be used for the parked dataset implies a rather heavy usage of cpu (it amounts to ~12.4% time of the overall reco + miniAOD time). For the normal workflows a tighter working point was defined, whose cpu usage corresponds to ~4.3% of the total reco + miniAOD processing time: the efficiency for low pt photons get reduced by some 25% with respect to the looser working point, though.
  - The tests show that only the new objects are added in output, while nothing else show differences in reco or miniAOD: jenkins tests report about 12 differences in the reco comparisons from the Phase2 workflows, and they all correspond to the additional warning messages issued by the PFTrackProducer:lowPtGsfElePfTracks module in step3 on top of the same warnings coming from the already existing PFTrackProducer:pfTrack and PFTrackProducer:uncleanedOnlyPfTrack, already present also in the baseline.

**Comment by fabiocos** [comment]
+operations

confirming previous signature

**Comment by fabiocos** [comment]
@ssekmen the update posterior to your signature looks transparent to fastsim to me, could you please verify and sign it again or comment in case?

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
