### PR TITLE
[12_3_X] Backport of 37617 + 37798

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

In order to run properly, a backport to `12_3_X` of #37860 would need backports of #37798 and #37617. This PR is the combination of those backports.

#### PR validation:

Running `39434.501`, `39434.502` and `11634.x` , with x=`501`, `502` and `503`.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503, 11634.502, 39434.502
- workflows = 11634.501, 39434.501, 11634.502
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by AdrianoDee** [comment]
type trk

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
tested successfully at P5

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by qliphy** [comment]
+1

**Comment by missirol** [comment]
I suspect this PR is related to a crash seen on HLT GPU nodes earlier today at P5. Preliminary checks suggest that there is a missing protection against nHits==0 in https://github.com/cms-sw/cmssw/pull/37933/files#diff-b8e0330eedf2567c3939e81b38dfc9dc2c62758e891e27cd10d5324b56d0d6bbR83

Could experts please have a look?

@AdrianoDee 

FYI: @fwyzard @zarucki @Sam-Harper

**Comment by AdrianoDee** [comment]
Hi @missirol, is there a log for the crash?

**Comment by AdrianoDee** [comment]
Anyway there's a protection against `nHits==0`[here](https://github.com/cms-sw/cmssw/pull/37933/files#diff-b8e0330eedf2567c3939e81b38dfc9dc2c62758e891e27cd10d5324b56d0d6bbR75).

**Comment by AdrianoDee** [comment]
I see what you mean, let me add the safeguard anyway.

**Comment by fwyzard** [comment]
@missirol I think your patch would leave uninitialised data in `hmsp`, which later gets put in the event for the `hostPutToken_` collection.

**Comment by fwyzard** [comment]
the collection that goes to `hitsPutTokenCPU_` has an internal protection for the case with 0 hits

**Comment by fwyzard** [comment]
OK, I admit I'm lost about whether `std::make_unique<uint32_t[]>(size)` will initialise the elements (to `0`) or not :-/

If it does, the proposed fix is fine.
If it doesn't, we can initialise it explicitly:
```diff
diff --git a/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromCUDA.cc b/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromCUDA.cc
index fda418320e7..2af4588f92f 100644
--- a/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromCUDA.cc
+++ b/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromCUDA.cc
@@ -82,7 +82,11 @@ void SiPixelRecHitSoAFromCUDA::acquire(edm::Event const& iEvent,
 
 void SiPixelRecHitSoAFromCUDA::produce(edm::Event& iEvent, edm::EventSetup const& es) {
   auto hmsp = std::make_unique<uint32_t[]>(nMaxModules_ + 1);
-  std::copy(hitsModuleStart_.get(), hitsModuleStart_.get() + nMaxModules_ + 1, hmsp.get());
+  if (nHits_ > 0) {
+    std::copy(hitsModuleStart_.get(), hitsModuleStart_.get() + nMaxModules_ + 1, hmsp.get());
+  } else {
+    std::fill(hmsp.get(), hmsp.get() + nMaxModules_ + 1, 0u);
+  }
 
   iEvent.emplace(hostPutToken_, std::move(hmsp));
   iEvent.emplace(hitsPutTokenCPU_, store32_.get(), store16_.get(), hitsModuleStart_.get(), nHits_);
```

**Comment by missirol** [comment]
Thanks for following up, @AdrianoDee !

@fwyzard , thanks for the comments. 

> the collection that goes to `hitsPutTokenCPU_` has an internal protection for the case with 0 hits

Interesting, I think I see it now [here](https://github.com/cms-sw/cmssw/blob/300b12d68ec9bc410996462947b71dc76f5b6974/CUDADataFormats/TrackingRecHit/interface/TrackingRecHit2DHeterogeneous.h#L218).

> OK, I admit I'm lost about whether std::make_unique<uint32_t[]>(size) will initialise the elements (to 0) or not :-/

I was not sure either, all I did was to test and see no crash. :)

**Comment by makortel** [comment]
> OK, I admit I'm lost about whether `std::make_unique<uint32_t[]>(size)` will initialise the elements (to `0`) or not :-/

AFAICT it should.
* https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique says "The array elements are value-initialized"
* https://en.cppreference.com/w/cpp/language/value_initialization says for type that is not class or array type "the object is zero-initialized"
* https://en.cppreference.com/w/cpp/language/zero_initialization says "If T is a scalar type, the object's initial value is the integral constant zero explicitly converted to T."

**Pull request merged**
