### PR TITLE
Xerces 3 port 81x

### PR DESCRIPTION
**Pull request by smuzaffar**
Identical to #14622 but it is for 81X branch so that test and comparison can be run against the same IB

### CODE REVIEW

**Comment by smuzaffar** [comment]
cmsbuild, please test with cms-sw/cmsdist#2324

**Comment by smuzaffar** [comment]
@davidlange6 , now tests and comparisons are run based on CMSSW_8_1_X. Do you still see differences in comparison ?

**Comment by cvuosalo** [comment]
@smuzaffar: There are no differences in the Jenkins comparisons, but not all workflows were run. Eight workflows are missing: 9.0, 101.0, 1003.0, 1306.0, 10021.0, 10024.0, 25202.0, and 50202.0. Why didn't these workflows run?

**Comment by smuzaffar** [comment]
@cvuosalo , thanks for noticing this. Looks like the extra workflows are not running for cmsdist based tests. I have fixed it and restarted the tests.

**Comment by cvuosalo** [comment]
+1

For #14796 ba54b9dc25a473b222ea465e2714bf9d30c11a62

Migration to Xerces 3. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-06-08-2300 show no significant differences, as expected.

**Comment by smuzaffar** [comment]
@davidlange6 , if you agree we can put it in devel IBs?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@smuzaffar - sounds good to me. but we should push it back to the mainstream for pre8

**Comment by davidlange6** [comment]
Hi all - please make any further comments by tomorrow. The PR is already in the DEVEL IBs

**Pull request merged**
