### PR TITLE
Fix calculation of TrackingParticle::numberOfHits()

### PR DESCRIPTION
**Pull request by makortel**
The `TrackingParticle::numberOfHits()` (and the two other "number of hits") is calculated in a loop over the SimHits of a SimTrack, where only SimHits with the same `particleType` as the SimTrack's `pdgId` and the same `particleType` and `processType` as the "first hit" (or that's how the intention looks like). The purpose seems to be to ignore hits from e.g. delta rays or decays where the same SimTrack is reused.

I agree with the intention, but the definition of "first hit" is flawed. When iterating over the `multimap` from SimTrack id to an index in a `vector<const PSimHit*>` in
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_0_pre2/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L637-L674
the SimHits of a SimTracks are iterated in the order they get inserted in the `multimap` in
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_0_pre2/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L563-L566
The order of SimHits originates from
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_0_pre2/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L515-L530
and
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_0_pre2/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L306-L314
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_0_pre2/SimGeneral/MixingModule/python/trackingTruthProducer_cfi.py#L11-L27
i.e. first muon detectors, then pixel, and last (strip) tracker. If the "first hit" (according to the current logic) has `particleType` different from the SimTrack's `pdgId`, the resulting `numberOfHits` is zero. In phase0/1 this can happen if a non-muon particle decays to a muon resulting hit(s) in muon detectors. In phase2 the problem is exacerbated because also outer tracker SimHits are stored in the "pixel hit" collections, and for some reason for some SimTracks the OT SimHits have smaller index than pixel SimHits (typically leading to `numberOfHits()` being 0).

The proposed fix is to sort the SimHits by their `timeOfFlight()` before being inserted to the `multimap`, and ignore SimHits having `particleType` different from TrackingParticle `pdgId` from the "first hit" `particleType`+`processType` deduction (they are anyway ignored from the `numberOfHits` calculation already now).

But even this is not perfect, as there are cases where e.g. all SimHits have `particleType` different from TrackingParticle `pdgId`. So some further thought is still needed, but I think this PR is nevertheless an improvement. Similar fix is applied to `TrackingParticleNumberOfHits` as well.

Given that prior #17338 the TrackingParticles with `numberOfHits()==0` were ignored in `QuickTrackAssociatorByHits`, this bug caused some legitimate track-TrackingParticle pairs to not be associated. Already alone this PR would give almost the same changes in track true/fake classification as #17338 (there are cases where all SimHits of a TrackingParticle have a different `particleType` from the TrackingParticle `pdgId`, so #17338 was anyway needed). On top of #17338, the plots showing the number of hits or layers are expected to show small changes.

Tested in CMSSW_9_0_X_2017-01-22-2300 (on top of #17338), expected changes in validation plots are described above. No changes are expected in reco quantities.

@rovere @VinInn @ebrondol @slava77

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@makortel 
with the sort and an extra loop, I'm curious if the CPU time remains roughly unchanged.
Could you please confirm

Thanks

**Comment by makortel** [comment]
@slava77 I must admit that I have not checked the impact on timing.

In `TrackingTruthAccumulator` the added sort will certainly have an effect, but, on the other hand, I'd expect the `trackIdToHitIndex_.upper_bound()` being called only once per SimTrack (instead of each iteration over the SimTrack SimHits) to compensate (both are `O(n log(n))` with `n` being the number of SimHits).

In `TrackingParticleNumberOfLayers` there is already a sort, only the comparison function is made more complex. The added `for` does not add additional iteration over the SimHits, it is just to move the starting point of the main loop to the first SimHit with `particleType` equal to TrackingParticle's `pdgId`. Also here I'd expect CPU time to remain roughly the same.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
