### PR TITLE
Backport: Including jetId criteria for UL16 

### PR DESCRIPTION
**Pull request by alefisico**
#### PR description:

- This is a backport of #33826 
- We need this for nanoAODv9.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
backport of #33826

**Comment by mariadalfonso** [comment]
failure are unrelated to the PR
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8c374c/15316/unitTests/src/PhysicsTools/UtilAlgos/test/runtestUtilAlgos/testing.log

```
dropped waiting message count 0
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/relval/CMSSW_7_2_0_pre5/RelValProdTTbar/GEN-SIM-RECO/START72_V1-v1/00000/022350A9-AC30-E411-B225-0025905A6076.root; No such file or directory
```

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
+1
- Selectors are identical to the one in the master version of this PR
- nanoAOD customizations looks safeguarded by the `run2_miniAOD_devel` flag (but I'd let @cms-sw/xpog-l2 to evaluate it more computely)
- Jenkins tests pass and show no relevant differences: the error in PhysicsTools/UtilAlgos/test/runtestUtilAlgos although not being present in the IB looks pretty independent from this PR

**Comment by mariadalfonso** [comment]
please test

(not clear why we have test-rejected)

**Comment by mariadalfonso** [comment]
failures in unit test are still related to the rel-val availability

**Comment by qliphy** [comment]
please test with #33899

**Comment by mariadalfonso** [comment]
+xpog

code changes inline with master
no changes applied to nanoV8 currently in production

**Comment by qliphy** [comment]
+1

**Pull request merged**
