### PR TITLE
[12_4_X] PPS reco patch for bad pot

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

This PR provides a patch to be able to produce tracks inside PPS roman pot 45-220-fr that has only 2 planes working out of 6 (as to the current date). The code creates tracks using two hits (one per plane) drawing a straight line between them. The track is required to be isolated and horizontal. The goal is to recover at least some proton tracks for alignment/debugging purposes.
The patch is enabled by means of a runtime flag. Run2 processes are protected via Era mechanism.

#### PR validation:

Run2 data show no difference. Preliminary run3 data show recovered tracks as expected.

This PR is a backport of PR#38553.

@jpata @grzanka @AndreaBellora

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by jpata** [comment]
@fabferro there are no reco changes detected by the bot (CTPPS stuff maybe not tracked?), but does this change Run3 MC in any way? Does it need to be protected with a modifier?

**Comment by fabferro** [comment]
> @fabferro there are no reco changes detected by the bot (CTPPS stuff maybe not tracked?), but does this change Run3 MC in any way? Does it need to be protected with a modifier?

Run3 MC are effected in the sense that if the Simulation simulates PPS with all working planes, then unneeded 2-hit tracks will be added in the track collection. They can be easily identified and taken care of at analysis level. 
That said, the scope of this change is limited to data reconstruction till HW repair can be done.
So, in principle, this patch should not enabled when reconstructiong MC. 
Can this distinction (MC vs Data) be done via Eras?

**Comment by qliphy** [comment]
backport of #38553

**Comment by jpata** [comment]
> Can this distinction (MC vs Data) be done via Eras?

It doesn't seem like this is supported. Perhaps it would be better to create a new era that is only enabled when data is processed? Note that this has to be done in both the master version and this backport.

**Comment by fabferro** [comment]
> > Can this distinction (MC vs Data) be done via Eras?
> 
> It doesn't seem like this is supported. Perhaps it would be better to create a new era that is only enabled when data is processed? Note that this has to be done in both the master version and this backport.

If it's not supported, I'd say that PPS simulation can live with this patch unitl the detectors are repaired and the patch definitely disabled. The 2-hit tracks that are created reconstructing simulated data can be easily recognized and dealt with at analysis level.

**Comment by perrotta** [comment]
@fabferro I think that the actual (time dependent) detector configuration should be available in the DB, and the reconstruction should act according to that configuration, irrespectfully of being real data or MC. Hybrid cases as "I have a description in the DB, but I let my reconstruction operate as if it was different" are only expected to lead to confusion and possible mistakes.

**Comment by tvami** [comment]
cmsDriver can do `isMC`
https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/cmsDriverOptions.py#L210
couldnt that be used?

**Comment by davidlange6** [comment]
> On Jul 6, 2022, at 12:35 PM, Fabrizio Ferro ***@***.***> wrote:
> 
> 
> 
> Another way not to disrupt the recostruction of simulated data would be put if(run==1) isBadPot = false; somewhere. A bit rough but probably effective. It would disappear once that the patch is not needed anymore.
> 

Eg, you will instead have if (run>x and run<y)?

**Comment by fabferro** [comment]
> On Jul 6, 2022, at 12:35 PM, Fabrizio Ferro ***@***.***> wrote: Another way not to disrupt the recostruction of simulated data would be put if(run==1) isBadPot = false; somewhere. A bit rough but probably effective. It would disappear once that the patch is not needed anymore.
> Eg, you will instead have if (run>x and run<y)?

@davidlange6 you mean something like if(run>first.run3.run && run<99999999) isBadPot=true; ?
It can work as well. Then 999999999 will be replaced with last.run3.run.with.bad.pot once we have repaired the pot.

**Comment by fabferro** [comment]
> Why dont we just do the tag update? In that way we are independent of the release schedule. For example I understand that 12_4_X is to be cut today, and this PR will not be in it... (given that it's master is not merged yet)
@tvami PR#38606 has been merged and we will update tags as soon as also PR#38607 is. Without this bug fix a new mask would disrupt reconstruction. We are anyway putting the tags in Prep DB.  

@wpcarvalho

**Comment by tvami** [comment]
Well, this is not under `alca` ... but I dont see how this fits the plans of the collaboration. 12_4_2 was cut yesterday, there is no plan for 12_4_3 in the near future, so please bring this up with PPD / ORP

**Comment by jpata** [comment]
Folks, I'm not sure what is the plan here now. @fabferro can you enable/disable this via the conditions? Can you ask to cut a new release once this feature is ready for deployment?

Sorry, I'm on vacation and can't be of big help right now. Maybe @clacaputo can step in too.

**Comment by fabferro** [comment]
> On Jul 6, 2022, at 2:24 PM, Fabrizio Ferro ***@***.***> wrote: On Jul 6, 2022, at 12:35 PM, Fabrizio Ferro @.***> wrote: Another way not to disrupt the recostruction of simulated data would be put if(run==1) isBadPot = false; somewhere. A bit rough but probably effective. It would disappear once that the patch is not needed anymore. Eg, you will instead have if (run>x and run<y)? @davidlange6 you mean something like if(run>first.run3.run && run<99999999) isBadPot=true; ? It can work as well. Then 999999999 will be replaced with last.run3.run.with.bad.pot once we have repaired the pot.
> No, I mean that you won't remove anything, you will keep it forever... (eg, its a condition with an iov and should be in the conditions database)
> […](#)
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

@davidlange6 @tvami @perrotta If I understand your comments (and reactions) you would suggest to have isBadPot flag in the DB. Correct? That would mean to add a new condition in the DB. Which means a new CondFormats. Which is something that can't be done in a patch release and so probably not before September. Do I get it right?

**Comment by davidlange6** [comment]
> On Jul 7, 2022, at 7:56 PM, Joosep Pata ***@***.***> wrote:
> 
> 
> you would suggest to have isBadPot flag in the DB. Correct? That would mean to add a new condition in the DB.
> 
> this is my understanding.
> 
> Which means a new CondFormats. Which is something that can't be done in a patch release and so probably not before September.
> 
> I'm not aware of such a limitation or distinction between a patch / full release, but it maybe just my ignorance...

It can't be done in a patch release. Right. (See recent ops meetings discussions and orp proposal)

But I don't follow the jump to September... everyone is going on holidays for 7 weeks?

**Comment by tvami** [comment]
@fabferro can you reuse an existing CondFormat? Like you could have a tag with a label, for example the masked channels, and use it for this purpose?

**Comment by tvami** [comment]
@fabferro the new strat looks good to me, although I'm still not among the people who sign this PR. On the other hand again, it seems we'll have to cut 12_4_2, so this is your window of opportunity

**Comment by tvami** [comment]
urgent

**Comment by perrotta** [comment]
> @fabferro the new strat looks good to me, although I'm still not among the people who sign this PR. On the other hand again, it seems we'll have to cut 12_4_2, so this is your window of opportunity

Ahem... CMSSW_12_4_2-was cut two days ago, see e.g. https://cms-talk.web.cern.ch/t/production-release-cmssw-12-4-2-now-available/12579

**Comment by tvami** [comment]
typo, I meant 12_4_3, I actually said that this is too late for 12_4_2 here: https://github.com/cms-sw/cmssw/pull/38581#issuecomment-1177886079

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
@fabferro please let some pps people join the tomorrow ORP meeting (https://indico.cern.ch/event/1179450), where we will discuss about the possible backport of those PRs that can modify reconstructed or simulated objects.

**Comment by tvami** [comment]
type bugfix,ctpss

**Comment by clacaputo** [comment]
+reconstruction

- backport of #38553, the backport is in line with the original

**Comment by fabferro** [comment]
@perrotta is this being merged?

**Comment by qliphy** [comment]
> @perrotta is this being merged?

@fabferro  The PR is master was just merged. Once the IB test passes without any problem, we can merge this one.  In the meantime, you can also work on the further cleanups as suggested in the master PR.

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
