### PR TITLE
2023 Scenario and Workflow with Detailed Cavern

### PR DESCRIPTION
**Pull request by ianna**
* Integrate detailed cavern description in 2023D12 scenario
* Add 24434.0 relval workflow to test it
* Correct exception message from DDG4Builder
* Remove overlaps which were introduced by a detailed cavern inclusion

It is based on https://github.com/cms-sw/cmssw/pull/17942

@kpedro88, @calabria, @pietverwilligen - FYI

Note: The Air mother volume changes and cable re-parenting were introduced in M2. Sensitive volumes are not affected.

Fixed here: <strike>Another note: there are serious overlaps present (unrelated to cavern description and file restructuring). Probably, the most offensive is 133.2 cm extrusion</strike>:
```
mf:ME0RingP extruded by: mf:ME0RingP/mfshield:ShieldingAntinomyLead_1_ME0_1 ovlp=133.2
```
screen shot 2017-03-15 at 14 58 29

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
It looks like it was a typo in the following commit: the width of ShieldingAntinomyLead_1_ME0 was changed from 15 cm to 148 cm. I guess, it should have been 14.8 cm.
https://github.com/cms-sw/cmssw/commit/64ce91a02b13da7a59b631ad3f27a406596bc265#diff-b218f83d63f4e7c62b854be6f6e7c449

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
locally run relval workflow finishes fine:
```
runTheMatrix.py -l 24434.0 -w upgrade
```
```
24434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D12_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D12+RecoFullGlobal_2023D12+HARVESTFullGlobal_2023D12 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Mar 15 17:21:33 2017-date Wed Mar 15 17:00:57 2017; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by kpedro88** [comment]
xrootd error, looks transient

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@kpedro88 and @slava77 - I would expect to see some differences in all 2023 workflow comparisons since there was a big slab of steel (1,5 m) removed (a ME0 shield is ~15 cm now). Please, verify the plots.

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
@ianna 
10 ttbar events in jenkins is not enough to understand if anything is particularly wrong
[most ME0 hits/digis are noise and drive the occupancy in simple plots; segments appear to be OK at the 6-hit length https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-15-1100+17944/18813/validateJR/all_OldVSNew_TTbar14TeV2023D8wf23234p0/all_OldVSNew_TTbar14TeV2023D8wf23234p0c_ME0DetIdME0SegmentsOwnedRangeMap_me0Segments__RECO_obj_collection__data__degreesOfFreedom.png .. anything beyond that can be checked either with more events @jshlee @calabria you may want to check
and then with the relvals

**Comment by kpedro88** [comment]
I agree that higher stats validation can be done. But the change affecting existing workflows is an obvious bug fix and a random survey of the comparison plots looks fine to me (changes appear to be mostly statistical fluctuations).

**Comment by ianna** [comment]
@civanch - there are overlaps in all 2023 scenarios, I'll work on them after this PR is merged in an IB.

**Comment by civanch** [comment]
+1
OK, let us read them up later

**Comment by ianna** [comment]
@fabozzi and @davidlange6 - please review

**Comment by ianna** [comment]
urgent

**Comment by davidlange6** [comment]
Hi @ianna lets save the definition of a 2017dev scenario until its need is discussed/understood. otherwise this looks good to me

**Comment by ianna** [comment]
@davidlange6 - we can discuss it today at sim meeting

**Comment by ianna** [comment]
@davidlange6 - I've removed the file in question. The rest is unchanged. We can wait to re-collect the signatures or you can accept it as is.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Pull request merged**
