### PR TITLE
Pixel fed errors 74x

### PR DESCRIPTION
**Pull request by danduggan**
Patch for code to propagate pixel fed errors for monitoring, same as #7835

### CODE REVIEW

**Comment by danduggan** [comment]
@cmsbuild please test

**Comment by danduggan** [comment]
+1

**Comment by deguio** [comment]
need to have this in 75 as well.
thanks,
F.

**Comment by deguio** [comment]
ok, already there:  #7837 
ciao,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
