### PR TITLE
DQM module fixes for SUSY JetIdCleaned paths (CMSHLT-482:Reopened)

### PR DESCRIPTION
**Pull request by mrcarver**

### CODE REVIEW

**Comment by slava77** [comment]
it looks like the branch is wrong (to be submitted to 7412patchx or this should be properly ported to 74X)
```
#go back to the common point first
git rebase --onto=`git merge-base CMSSW_7_4_X CMSSW_7_4_12_patchX` CMSSW_7_4_12_patchX
#this may be not necessary if your changes don't have overlapping commits since 7_4_12
# with no overlapping changes, the same mrcarver:Fix74 after rebase can work for both 7412patchX and 74X
git rebase CMSSW_7_4_X
#then push again to mrcarver:Fix74 with --force flag
```
otherwise, just redo the changes in CMSSW_7_4_X_2015-09-24-2300

**Comment by mrcarver** [comment]
Hi Slava,

I've done what you've asked and pushed again to Fix74. Can you please let me know if this has worked for you? 

Thanks,
Matt

**Comment by slava77** [comment]
you still have  RecoEgamma/ElectronIdentification/plugins/ElectronMVAEstimatorRun2Spring15NonTrig.cc 
Did it come up as a conflict during rebase and you just picked the other version?
It would be the best to not have this commit  758cc90 in this PR

**Comment by mrcarver** [comment]
Sorry I didn't catch that. It has no bearing on what I meant to change so I've deleted it and pushed the branch again.

**Comment by slava77** [comment]
@mrcarver 
could you please instead ``` git rebase -i CMSSW_7_4_X_2015-09-24-2300 ```
and then remove the ecal commits when the editor pops up; then push --force.
this way they will be completely gone

**Comment by mrcarver** [comment]
@slava77 
I've tried to do this but get the error 

fatal: Needed a single revision
invalid upstream CMSSW_7_4_X_2015-09-24-2300

do you know of a reason for this?

Thanks for all your help

**Comment by slava77** [comment]
``` git fetch official-cmssw CMSSW_7_4_X_2015-09-24-2300:CMSSW_7_4_X_2015-09-24-2300 ```

**Comment by mrcarver** [comment]
@slava77 Ok, I was able to remove the 758cc90 commit and pushed the update with the --force flag

**Comment by slava77** [comment]
sorry, this is worse now, the last commit a8e0f95 should not be here in the history
the same " rebase -i" ?

**Comment by mrcarver** [comment]
@slava77 Ok, I tried to rebase -i again and remvoed the a8e0f95 commit then push --force right after so hopefully it was removed properly

**Comment by slava77** [comment]
@cmsbuild please test

nice. this worked out, eventually ... no more changes in reco code, not more attention needed from me

**Comment by mrcarver** [comment]
Hi, just checking in to see if the fixes I implemented worked?

**Comment by deguio** [comment]
please test

**Pull request closed without merging**
