### PR TITLE
HGC ToT Digitization Implementation (and corresponding RECO updates)

### PR DESCRIPTION
**Pull request by lgray**
This PR implements the HGCal Time-Over-Threshold digitization in CMSSW 76X.

The HGCal RecHit producers are accordingly updated.

The digitization and reconstruction chain can be tested with:
`cmsRun RecoLocalCalo/HGCalRecProducers/test/testHGCalRecoLocal_cfg.py`

There are a few small bugfixes to the CaloTowerHardcodeGeometryLoader to allow it to work with upgrade geometries. 

New customizations are introduced to handle the HGCal. (@bsunanda please double check this)

Rechit energy and time distributions look healthy (35 gev electron gun):
screen shot 2015-10-16 at 14 23 26
screen shot 2015-10-16 at 14 22 59

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray
I see #11679 and #11801 PRs merged here
- 11801 was merged already and can be taken out of the history here with a rebase
- 11679 was fully signed for 6 days already, but not merged. Is there an issue with that PR?

**Comment by lgray** [comment]
@slava77 not sure if there is a problem with #11679
@davidlange6 Mind seeing if there is any show stopper?

**Comment by lgray** [comment]
@slava77 Will rebase when both the PRs are merged.

**Comment by bsunanda** [comment]
@davidlange6 There is no issue for 11679. I wonder why it is not integrated. Same true for 11711.
________________________________

**Comment by davidlange6** [comment]
11711 was signed last night. I’m catching up with those this afternoon. 11679 needs a followup from me that I mentioned in the sim meeting last week

**Comment by lgray** [comment]
@boudoul FYI

**Comment by bsunanda** [comment]
@davidlange6 I wonder what was the concern for 11679.
________________________________

**Comment by lgray** [comment]
Failure reason:
```
IOError: [Errno 28] No space left on device
Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE
```

**Comment by lgray** [comment]
Hmm this passed locally. Must have forgotten a change...

**Comment by lgray** [comment]
Right, this one is also waiting on #11784. (which is why I thought I fixed the problem that happened)

I will wait until that gets merged in and then rebase.

**Comment by slava77** [comment]
@lgray  there are merge conflicts here now

What is the plan for #11679  ?

Unless there is a big reason to have this in 760, please close this PR and let's continue in 80X cycle.

**Comment by lgray** [comment]
@slava77 Yes, let's continue this in 80X.

**Pull request closed without merging**
