### PR TITLE
10.2.X Added links from LowPtGsf to PackedCandidates and LostTracks in MiniAOD

### PR DESCRIPTION
**Pull request by mverzett**
Verbatim backport of #26031

@bainbrid is interested in following this

### CODE REVIEW

**Comment by perrotta** [comment]
Please synchronize the changes in this backport with the latest additions in #26031

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Exact backport of #26031, now merged in the master
- The new maps only add up to the miniAOD output when the bParking era is set: jenkins tests pass and show no differences
- As in the master, there is a check to be done on the lowPtElectron code which jumps from time to time on some all 0 parameters tracks: this is independent from this PR, however, which can be therefore integrated while that issue is getting dedugged

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
