### PR TITLE
L1T Left Shift Error

### PR DESCRIPTION
**Pull request by ryanm124**
#### PR description:

Addressing part of issue #35010 where UBSAN reported left-shift of negative value in L1Trigger files. Introduced bitShift helper function which makes number positive before bit shifting and then reintroduces the original sign. Replaced left shifts in problem files with helper function. 

#### PR validation:

Ran prompt and displaced tracking using default cms-L1TK repository and modified cms-L1TK repository with proposed bitShift changes in PR to problem files in TrackFindingTracklet and made comparison efficiency and eta resolution plots. Results are identical between two versions. Left shift errors no longer appear in UBSAN log when compiling.
D76_TTbarPrompt_PU200_BitShiftComparison_eff_z0
D76_TTbarPrompt_PU200_BitShiftComparison_eff_d0
D76_TTbar_PU200_BitShiftComparison_resVsEta_phi
D76_TTbar_PU200_BitShiftComparison_resVsEta_eta
D76_TTbar_PU200_BitShiftComparison_resVsEta_z0
D76_TTbar_PU200_BitShiftComparison_resVsEta_d0
D76_TTbar_PU200_BitShiftComparison_resVsEta_ptRel
D76_TTbar_PU200_BitShiftComparison_eff_phi_sector
D76_TTbar_PU200_BitShiftComparison_eff_phi
D76_TTbar_PU200_BitShiftComparison_eff_eta
D76_TTbar_PU200_BitShiftComparison_eff_z0
D76_TTbar_PU200_BitShiftComparison_eff_d0
D76_TTbarPrompt_PU200_BitShiftComparison_resVsEta_phi
D76_TTbarPrompt_PU200_BitShiftComparison_resVsEta_eta
D76_TTbarPrompt_PU200_BitShiftComparison_resVsEta_z0
D76_TTbarPrompt_PU200_BitShiftComparison_resVsEta_d0
D76_TTbarPrompt_PU200_BitShiftComparison_resVsEta_ptRel
D76_TTbarPrompt_PU200_BitShiftComparison_eff_phi_sector
D76_TTbarPrompt_PU200_BitShiftComparison_eff_phi
D76_TTbarPrompt_PU200_BitShiftComparison_eff_eta

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by perrotta** [comment]
The inlined function `bitShift` is repeated identically in several classes.
To avoid all the hassles due to code duplication, I'd suggest to code it only once in a utility file, for example in L1Trigger/L1TCommon/interface (but perhaps @cms-sw/l1-l2 can suggest a more convenient location for it), and call it in all other classes

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
