### PR TITLE
remove inexistent pythia8 parameter from config

### PR DESCRIPTION
**Pull request by mkirsano**
#### PR description:

Remove pythia8 parameter which is redundant in the version 302 and inexistent in 303 causing error

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
@mkirsano   

There is  a releated UnitTests failure:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-64e270/9791/unitTests.log
 PYTHIA Error: input string not found in settings databases::
   SLHA:keepSM = on
----- Begin Fatal Exception 07-Oct-2020 23:47:03 CEST-----------------------
An exception of category 'PythiaError' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module Pythia8GeneratorFilter/'generator'
Exception Message:
Pythia 8 did not accept "SLHA:keepSM = on".
----- End Fatal Exception -------------------------------------------------

Can you fix also here?: https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/EvtGenInterface/test/Py8_bplus_evtgen1_cfg.py#L122

**Comment by mkirsano** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
