### PR TITLE
[14_1_X] Adding unbiased superclusters to miniAOD and EGM nano

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/46423

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
enable nano

**Comment by mandrenguyen** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
