### PR TITLE
New Run3 pileup scenario: 10h fill, 2h leveling

### PR DESCRIPTION
**Pull request by knollejo**
New pileup scenario for Run 3. Details about the expected LHC conditions and the effects that have been considered have been presented in the PPD meeting [here](https://indico.cern.ch/event/1045566/#36-update-of-pu-profile-for-ru). To build the scenario, we have simulated an LHC fill of 10h with an initial 2h leveling period. This has to be understood as an optimistic average of all 2022 fills which are planned to converge to 6h leveling periods at the end of 2022. The fraction of events with a given average pileup is weighted by the instantaneous luminosity.

Scenario10h2h_lw

We tested running cmsDriver with `--pileup 2022_LHC_Simulation_10h_2h` by hand and found no problems.

### CODE REVIEW

**Comment by mmusich** [comment]
@knollejo I was under the impression the target leveling for 2022 is more 6h:

image

Also are there plans to make this the default RelVal scenario ?
@rappoccio (I don't have Andreas gitHub tag)

**Comment by rappoccio** [comment]
Hi, @mmusich , all. Let's discuss at the PPD Coordination meeting tomorrow. We'll present the proposal from LUM and we can discuss if it is sufficient. We intend to make it default for relvals *and* Run 3 MC production.

**Comment by davidlange6** [comment]
This graphic is the end of the 2022 running goal for leveling not what is expected for the overall 2022 run. LPC suggests the average PU is 35 in 2022 (averaged over what is not totally clear)

**Comment by cschwick** [comment]
The graphics shown by @mmusich is the best possible scenario towards the end of 2022 calculated by the LHC experts. It for sure does not represent how the fills in 2022 look like ON AVERAGE. The pileup distribution derived from our proposed fill has larger contributions at lower pileup which makes reweighing the MonteCarlo possible in a larger pileup range (as I have understood). I still think it is an optimistic scenario. If I am wrong we will have a fantastic high integrated lumi year in 2022 :-)

**Comment by mmusich** [comment]
> This graphic is the end of the 2022 running goal for leveling not what is expected for the overall 2022 run. LPC suggests the average PU is 35 in 2022 (averaged over what is not totally clear)

Thanks, this makes sense. It would be perhaps convenient to post the target PU profile plot directly in the gitHub thread for future reference.

**Comment by mmusich** [comment]
> It for sure does not represent how the fills in 2022 look like ON AVERAGE.

I think the average makes sense for large MC productions, while for relval perhaps and optimistic luminosity (PU) (pessimistic in terms of the detector performance) scenario would be useful to test algorithm robustness in the "worst case scenario".  I am not proposing that, though, as this is already vastly better than the current totally irrealistic relval profile.

**Comment by cschwick** [comment]
HI @davidlange6 , thanks for the LPC guess of the average pileup. The average pileup of the distribution we propose is by the way 36. So a pretty compatible guess from that perspective.

**Comment by cschwick** [comment]
And here comes the pileup distribution we propose:
newplot (14)

**Comment by VinInn** [comment]
why the plot above does not corresponds to this (slide 14)
image

and is instead very similar to the 16h fill? (slide 16 of https://indico.cern.ch/event/1045566/contributions/4392196/attachments/2261950/3839554/PileupGuessing.pdf)

**Comment by knollejo** [comment]
> why the plot above does not corresponds to this (slide 14)
> and is instead very similar to the 16h fill? (slide 16 of https://indico.cern.ch/event/1045566/contributions/4392196/attachments/2261950/3839554/PileupGuessing.pdf)

For the plots in the presentation, the events are weighted by luminosity. The plots in this thread, which correspond to the numbers in the pull request, just gives the number of events. That's why higher-pileup peaks are larger in the presentation than in this thread.

**Comment by VinInn** [comment]
Thanks, understood. I overlooked the scale on the left.

**Comment by knollejo** [comment]
Scenario10h2hLumiWeights
This is the proposed scenario but weighted with the luminosity. It is very similar to the distribution on slide 14 of that presentation.

**Comment by VinInn** [comment]
Ok. So this is the pileup distribution we should expect for signal events, isn't it?

**Comment by cschwick** [comment]
Not sure what you mean with "signal events", Vincenzo. This is the pileup distribution for all bunch crossings in CMS (before triggering or anything). And without Poisson as Joscha mentioned (and lumi weighted).

**Comment by VinInn** [comment]
That when CMSSW had to sample PU to add it to a "signal event" the distribution (before poisson?) should be lumi-weighed.
(maybe after poisson after all).

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by knollejo** [comment]
After continuing the discussion here on other channels to clear some confusion about what exactly is needed as an input, we have updated the scenario to have the fraction of events weighted by the instantaneous luminosity, which was not the case originally.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Pull request merged**
