### PR TITLE
Pr113x L1T Fractional Prescales implemented with Global Trigger

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:
Master branch PR of the 11_2_X PR https://github.com/cms-sw/cmssw/pull/32377 which is needed for MWGR Feb 2021.

11_3_X:  Use of fractional prescales in uGT emulator, by switching from legacy (int based) to new (double based) prescales.  The new Conditions format is available in CondDB as `L1TGlobalPrescalesVetosFractRcd`, in the `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt` tag.

Supplemented by changes in `HLTrigger/HLTcore` package
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by christopheralanwest** [comment]
I've encountered a problem in trying to prepare the GTs and I need advice from @cms-sw/hlt-l2 regarding how to proceed. Some of the addOnTests use the `run2_hlt_relval` and `run2_hlt_relval_hi` GTs defined at https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCond.py#L43-L44. These GT are based on the 10_3_X release and so I can't add payloads of type `L1TGlobalPrescalesVetosFractRcd` both because the 10_3_X CMSSW release does not contain the relevant record and because the boost version used by the CMSSW in which `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt` was serialized (1.72) is newer than that used by 10_3_X (1.63.0).

Should the `run2_hlt_relval` and `run2_hlt_relval_hi` GTs be updated to use a GT from a release series that is currently used by the HLT (11_2_X), or is intended that these GTs are nominally frozen as some sort of means of ensuring compatibility between the HLT actually run at P5 and newer releases? If there is any documentation somewhere that describes how the addOnTests are used in general, that would be very helpful.

**Comment by Martin-Grunewald** [comment]
Can one make compatible GTs by re-serialising the record with the different boost?

**Comment by Martin-Grunewald** [comment]
The addOnTests are to test that everything is in working order at PR test time. They are supposed to reflect any physics/MC production in/for that release.

**Comment by Martin-Grunewald** [comment]
IOW, if the GTs can be updated (without changing the physics content), then this should be OK and also future proof.

**Comment by christopheralanwest** [comment]
I've created the autoCond PR #32758 and have triggered the tests of that PR together with this one.

**Comment by christopheralanwest** [comment]
The autoCond PR #32741 has been successfully tested with this PR. Does everything in that PR look OK to you? If so, I sign off on #32741 and backport the PR to 11_2_X.

**Comment by christopheralanwest** [comment]
@rekovic @hjkwon260 In PR #32741, now already merged, I used the tag name `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt` as mentioned in the introduction to this PR. But in a private e-mail thread "Re: Question regarding L1T new fractional prescale tag", dated November 13, 2020, there is the following comment:

"I think we'll use this tag ‘L1TGlobalPrescalesVetosFract_Stage2v1_hlt’ for o2o during next week MWGR and afterwards. Therefore this tag would be integrated into GT eventually. (Rather than ‘L1TGlobalPrescalesVetosFract_Stage2_v2_hlt’ which would be redundant now)"

Which is the correct tag to use for data? The two tags are different:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/L1TGlobalPrescalesVetosFract_Stage2_v2_hlt/L1TGlobalPrescalesVetosFract_Stage2v1_hlt

**Comment by hjkwon260** [comment]
Dear @christopheralanwest,  please use `L1TGlobalPrescalesVetosFract_Stage2v1_hlt` for data GTs. We used this tag in the last MWGR, so it has 2 more payloads (which were append via O2O) than `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt`

**Comment by silviodonato** [comment]
urgent
for the MWGR

**Comment by christopheralanwest** [comment]
> Dear @christopheralanwest, please use `L1TGlobalPrescalesVetosFract_Stage2v1_hlt` for data GTs. We used this tag in the last MWGR, so it has 2 more payloads (which were append via O2O) than `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt`

Thanks. I will prepare a fix for the 113X autoCond in parallel with the 112X autoCond backport. While the data GTs do need to be corrected, the only difference between the two is in the IOV range [338724, 338750):

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/L1TGlobalPrescalesVetosFract_Stage2_v2_hlt/L1TGlobalPrescalesVetosFract_Stage2v1_hlt

This difference should not be relevant for integration tests for this PR.

**Comment by jfernan2** [comment]
+1
Based on the changes at the DQM packages by this PR

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
@cms-sw/hlt-l2 do you have further comments?

**Comment by Martin-Grunewald** [comment]
There is still a flag 'tests-rejected'
??

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rerun tests....

**Comment by christopheralanwest** [comment]
> There is still a flag 'tests-rejected'
> ??

This PR was successfully tested with PR #32758 but apparently the bot was changed recently so that when two PRs are tested together, notifications are sent only to the PR in which the test command was issued, and similarly for the status labels. I don't know if this was a design decision or if it is a bug. @smuzaffar Could you comment?

**Comment by fwyzard** [comment]
please test with #32758

**Comment by smuzaffar** [comment]
@christopheralanwest , it is design decision. Each PR needs to be tested explicitly

**Comment by silviodonato** [comment]
please test with #32758
It seems there was a glitch during the test https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/41047/console

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
This PR likely broke two unit tests in `DQM/Integration`, see #32796.

**Pull request merged**
