### PR TITLE
fix ES unpacker when the 2nd OptoRX is diabled, but the 1t and 3rd Op…

### PR DESCRIPTION
**Pull request by cmkuo**
This is to fix the problem when the second ES OptoRX is disabled, but the first and third OptoRX are enabled in the ES unpacker. The problem would cause the data in third OptoRX are not unpacked.

### CODE REVIEW

**Comment by smuzaffar** [comment]
ignore this comment

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11615 676c423f7a82bf6a37bd2e48df4bf8260f695d39

Fixing an ES unpacker bug where the third OptoRX is missed in certain cases. #11613 and #11614 are the 74X and 76X versions of this PR, and they have already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-10-01-2300 show no significant differences. Test results in #11613 show the expected changes from this fix.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11615	9a87049
- same changes since the last sign off of this PR were added as in 76X update #11693  : https://github.com/cms-sw/cmssw/compare/676c423f...9a87049
- jenkins tests pass and comparisons with the baseline show no difference

@cvuosalo is offline today, I took the liberty to sign off in case there is an early 75X build

**Comment by davidlange6** [comment]
+1

**Pull request merged**
