### PR TITLE
drop type specifications in RecoJets

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Update the safer syntax for existing parameter :
- drop type specifications where the original parameter exists.
- move all parameter inside the clone/modifier

Instead of modifying parameters with full type specs, which can be interpreted as an insertion of a new parameter, it is a safer way to protect from parameter name mistakes and will also help in possible parameter migrations.
(submitted PR for RecoJets is [PR#31162](https://github.com/cms-sw/cmssw/pull/31162). )

In this PR, a total of 5 files changed. 

RecoJets/Configuration 1 file
RecoJets/JetPlusTracks 1 file
RecoJets/JetProducers 3 file

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, following the intention declared in the PR title and description
- Jenkins tests pass, with no differences in output (while two RelVals-INPUT workflows fail because of a DAS error)
- (The two failing RelVals have a DAS error, which is completely unrelated from this purely technical PR: I don't think it is worth wasting resources to re-run the tests hoping for the DAS glitch being resolved, but I'll let the release managers to consider doing it, if they think so)

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
