### PR TITLE
[12_4_X] update BeamSpot HLT client to use correct raw data from TCDS

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38110.
See description and links in master PR.

#### PR validation:
The 12_3_X backport (https://github.com/cms-sw/cmssw/pull/38103) has already been deployed in production and the results are as expected, see comment in https://github.com/cms-sw/cmssw/pull/38103#issuecomment-1140193579

#### Backport:
Backport of #38110

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #38110

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db

**Comment by tvami** [comment]
type bugfix

**Comment by francescobrivio** [comment]
@cms-sw/dqm-l2 a kind ping for signing this PR, the 12_3_X is already deployed online in P5 (see https://github.com/cms-sw/cmssw/pull/38103#issuecomment-1140193579).

**Comment by pmandrik** [comment]
+1

**Comment by qliphy** [comment]
hold
see https://github.com/cms-sw/cmssw/pull/38110#issuecomment-1141326513

**Comment by francescobrivio** [comment]
@cmsbuild pelease test

**Comment by francescobrivio** [comment]
> hold see [#38110 (comment)](https://github.com/cms-sw/cmssw/pull/38110#issuecomment-1141326513)

@qliphy I have updated the label following suggestion in https://github.com/cms-sw/cmssw/pull/38110#issuecomment-1142295049, could you unhold?

**Comment by tvami** [comment]
unhold

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
