### PR TITLE
Added SimSequential option

### PR DESCRIPTION
**Pull request by civanch**
Added a possibility to switch to Geant4 sequential instead of multi-threaded.

This modification does not affect any of normal workflows but may be useful for special test applications and few unit tests.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@fabozzi , @davidlange6, this PR is a simple one.

**Comment by davidlange6** [comment]
@civanch - here is what I suggest as a simpler solution

add a Configuration/StandardSequences/python/SimSequentialMode_cff.py

import FWCore.ParameterSet.Config as cms

from Configuration.StandardSequences.SimExtended_cff import *

from SimG4Core.Application.g4SimHits_cfi import *
g4SimHits.__dict__['_TypedParameterizable__type'] = "OscarProducer"

then your cms driver command becomes

cmsDriver.py SingleMuPt1_pythia8_cfi  --conditions auto:run2_mc -n 10 --era Run2_2016 --eventcontent FEVTDEBUG --relval 25000,1000 -s GEN,SIM:Configuration/Stan
dardSequences/SimSequentialMode_cff.psim --datatier GEN-SIM --beamspot Realistic50ns13TeVCollision --fileout file:step1.root


[and btw- could you look into removing Configuration/StandardSequences/python/Simulation_cff.py?] 

Thanks

**Comment by civanch** [comment]
@davidlange6 , my problem: in the current cmsDriver SimExtended_cff  is not always used but there are alternatives (may be obsolete)...

**Comment by davidlange6** [comment]
@civanch -yes, seems more a corner case - (as its a special case of a developer special case)

**Comment by civanch** [comment]
Substituted by #15582

**Pull request closed without merging**
