### PR TITLE
fix headers in RecoEgamma/EgammaTools

### PR DESCRIPTION
**Pull request by mrodozov**
Add missing headers for passing check-headers scram check

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by perrotta** [comment]
+1
- The fix is technical, and it makes sense
- No effect in jenkins tests, as it should

**Comment by perrotta** [comment]
@mrodozov : out of curiosity, what is the check-headers test that you run?

**Comment by fabiocos** [comment]
+1

**Comment by mrodozov** [comment]
https://github.com/cms-sw/cmssw/pull/21614

**Pull request merged**
