### PR TITLE
[Backport] [GEM] Unpacker update for the vfat masking information [12_4_X]

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

* GEM Unpacker and data formats are updated to save the vfat masking information
* Minor bugfix for the VFATStatus (Positional information)
* The results of this update has approved in GEM DPG meeting ([link](https://indico.cern.ch/event/1202028/contributions/5054418/attachments/2511952/4317915/Masking_status_20_Sep.pdf))
* Backport to `CMSSW_12_5_X` and `CMSSW_12_4_X` are needed.

#### PR validation:

* The code format has applied with `scram build code-format` and tested with `scram build code-checks`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

* The original PR is #39487

### CODE REVIEW

**Comment by mandrenguyen** [comment]
What is the argument for backporting this into 12_4_X?
12_4_X is a closed release that is already being used in data taking.

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
> What is the argument for backporting this into 12_4_X? 12_4_X is a closed release that is already being used in data taking.

@mandrenguyen we can add one or more PRs to DQM machines at P5 on top of the current release used online in order to fix issues that would otherwise affect data taking and DQM operations.

@yeckang can you please confirm you need this PR deployed in online DQM machines?

**Comment by clacaputo** [comment]
> @yeckang can you please confirm you _only_ need this 12_4 backport for deployment to online DQM machines?

Hi @yeckang , could you please clarify this point? Thanks

**Comment by emanueleusai** [comment]
tests at P5 completed successfully, everything looks fine with collision run 357900.
We are approving the DQM part of this PR, but we will not deploy the PR on our machines at P5 until the discussion around the data format/reco part is resolved.
Adding this PR on top of the current release on our machines at P5 should be relatively safe, because the DQM GUI is the end user of our stream, but having a stray PR (i.e. not planned to be part of a future 12_4 release) in our machines should be avoided.

**Comment by emanueleusai** [comment]
+1

- P5 test completed successfully
- approving the DQM part of this PR

**Comment by mandrenguyen** [comment]
please close
As agreed in today's reco meeting, this PR will only be deployed in the online DQM in 12_4_X, and will be incorporated into cmssw for >=125X
Of course, if GEM experts need to revisit that decision we can reopen.

**Comment by perrotta** [comment]
Technical question: wouldn't it be preferable to keep it open (maybe on hold) so that GEM and/or DQM can more easily merge it further, and keep it up to date as well, if some newer 12_4_X version will be installed online in the future?

**Comment by mandrenguyen** [comment]
please open
(not sure that command actually works)
@perrotta  you know better than me.  For sure we can simply put it on hold for a while.

**Comment by mandrenguyen** [comment]
please hold
(good bot!)

**Comment by perrotta** [comment]
> please hold (good bot!)

you are too much polite: "hold" alone will work here

**Comment by perrotta** [comment]
hold

**Comment by emanueleusai** [comment]
@perrotta yes it is easier for us to have an actual PR, even if it won't be part of an official 12_4 release. Thanks for bringing this up.

**Comment by emanueleusai** [comment]
Given the resolution of the matter at the reco meeting (thanks @mandrenguyen for the update) we will deploy the PR soon to our online machines.

**Comment by srimanob** [comment]
If this PR is no need, can we close @yeckang ? Thx.

**Pull request closed without merging**
