### PR TITLE
Added tensorflow initialization to TSGForOIDNN

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Measurements of HLT job timing showed that the first calls to tensflow take a long time and hold a mutex for that entire time. This lead to poor thread efficiency during the start of event processing.

#### PR validation:

Code compiles. Running an HLT job shows substantially better startup of the event processing.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@valsdav Can you comment if this change makes sense from the ML group perspective? Do you know if Tensorflow would have a better API for the initialization?

I suppose the initialization pattern should be replicated to all modules that use Tensorflow.

**Comment by valsdav** [comment]
About the initialization: as far as I understand TF allocates memory at the first call of the inference. From a quick look I haven't found a initialization function to enforce a different behaviour. The approach followed in the PR seems fine to me. We can automatize it looking at the graph definition for the input shapes and add this in the common TensorFlow package (I will open an issue to track that). 

More in general: I gave a quick look at the producer `RecoMuon/TrackerSeedGenerator/plugins/TSGForOIDNN.cc` and it seems it escaped the changes we made https://github.com/cms-sw/cmssw/issues/40248, where we moved all the graphs and TF sessions to the GlobalCache.   This can save a lot of memory by having a single Graph and Session instead of one for each thread. I can open a separate PR for that.

**Comment by valsdav** [comment]
> More in general: I gave a quick look at the producer `RecoMuon/TrackerSeedGenerator/plugins/TSGForOIDNN.cc` and it seems it escaped the changes we made #40248, where we moved all the graphs and TF sessions to the GlobalCache. This can save a lot of memory by having a single Graph and Session instead of one for each thread. I can open a separate PR for that.

Sorry, I read too quickly. It is an `edm::global` producer, so those changes does not apply in this case.

**Comment by mandrenguyen** [comment]
type performance_improvements

**Comment by mandrenguyen** [comment]
+reconstruction
technical, no changes to comparisons
@cms-sw/hlt-l2 FYI

**Comment by rappoccio** [comment]
+1

**Pull request merged**
