### PR TITLE
[81X] modernize configuration file for centering tracker geometries

### PR DESCRIPTION
**Pull request by mmusich**
Configuration file used to force centering of tracker alignment, relying on the geometry comparison tool.
- moved to CondDBv2
- modernized includes

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig any objection on this one?

**Comment by ghellwig** [comment]
@mmusich no objections, just one questions:
Why do you create additional `ESSource` objects instead of just overriding the alignment payloads in the existing one (`process.GlobalTag`)?

**Comment by mmusich** [comment]
@ghellwig: mostly to have in release an example of how to do it correctly with condDBv2.

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
