### PR TITLE
DD4Hep Migration: Parse CMS XML Files

### PR DESCRIPTION
**Pull request by ianna**
* Proof of principle example

this test parses CMS XML files for run 1 Tracker.

To run the test:
```
cmsRun DetectorDescription/DDCMS/python/dump.py
```
This PR replaces https://github.com/cms-sw/cmssw/pull/21945.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
@ianna as far as I can see this is a completely new package without any impact on existing code/workflow, I understand that this is a place for development and test in view of the future move to DD4Hep in production without interfering with the production setup. Am I correct?

**Comment by ianna** [comment]
@fabiocos - yes, correct

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I will do a PR to cms-bot to add this package to the geometry category

**Comment by ianna** [comment]
+1

**Pull request merged**
