### PR TITLE
[Backport of PR #40230] Electron MVA-based ID for Run3 from EGamma POG

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

Backport of PR https://github.com/cms-sw/cmssw/pull/40230, see description there

#### PR validation:

Same as https://github.com/cms-sw/cmssw/pull/40230

runTheMatrix.py --what nano --site "" -l 2500.312,2500.501

This PR needs to be tested with the PR https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/27

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport required for nanoAODv11 production in 12_6_X.

### CODE REVIEW

**Comment by swertz** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40230

**Comment by swertz** [comment]
type egamma

**Comment by swertz** [comment]
please test with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/27

**Comment by swertz** [comment]
+1

Same changes as in https://github.com/cms-sw/cmssw/pull/40230

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
Will merge this when the IBs clear in the main branch.

**Comment by rappoccio** [comment]
+1

IBs have cleared. Once this PR is tested in the next IBs we can cut 12_6, probably Monday.

**Pull request merged**
