### PR TITLE
[HCAL][backport] Make sure that trigger towers with abs(ieta)=16 are processed with QIE8 settings in 2018.

### PR DESCRIPTION
**Pull request by matz-e**
Backport of #22077.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
@thomreis this is requested by HCAL for 10_0_2, could you please scrutinise it?

**Comment by thomreis** [comment]
This falls more in the field of expertise of @rekovic .

**Comment by fabiocos** [comment]
@rekovic could you please check? I would like if possible to get it in 10_0_2

**Comment by thomreis** [comment]
+1

Why is this not labelled as a backport?

**Comment by matz-e** [comment]
@thomreis by @cmsbuild? I filed the original PR with the same branch, this was developed on 10_0_0… maybe @cmsbuild does not recognize "backports" from the same development branch?

**Comment by thomreis** [comment]
I think cmsbuild just checks if the comment first line matches patterns. Perhaps it had trouble with the "." at the end.

**Comment by thomreis** [comment]
Backport of #22077 

Let's try again.

**Comment by matz-e** [comment]
Hm… that should be an easy fix of a regexp in @cmsbuild…

**Comment by fabiocos** [comment]
@thomreis thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
