### PR TITLE
Me0 digitizer constand phi smearing 800

### PR DESCRIPTION
**Pull request by pietverwilligen**
Make configuration file of ME0Digitizer configurable such that one can choose between constant phi smearing in local coordinates (e.g. 500um everywhere) or constant phi smearing in radians 0.019\* (=3.3E-4 rad) everywhere.

at R=62cm, a smearing of 500um corresponds to 0.046\* = 8.1E-4 rad
at R=150cm, a smearing of 500um corresponds to 0.019\* = 3.3E-4 rad

### CODE REVIEW

**Comment by civanch** [comment]
@pietverwilligen , now you need to move it to 8_1_X

**Comment by pietverwilligen** [comment]
done it is #13478

**Comment by civanch** [comment]
@pietverwilligen , do we still need this PR?

**Comment by pietverwilligen** [comment]
i closed it.

**Pull request closed without merging**
