### PR TITLE
add DQM Validation plots for MSSM Hbb bTag Monitor Trigges.

### PR DESCRIPTION
**Pull request by heppye**
add DQM Validation plots for MSSM Hbb bTag Monitor Triggers.

### CODE REVIEW

**Comment by deguio** [comment]
this seems not mergeable.. @heppye could you please try a rebase?
thanks,
F.

**Comment by heppye** [comment]
@deguio, thanks for your reponse. I see a new PR was made by cmsbuild already. I also made a new PR based on file in CMSSW_8_1_X. https://github.com/cms-sw/cmssw/pull/13385. I leave the decision to you which PR should be used. Thanks,  Ye

**Comment by heppye** [comment]
@deguio , PR to CMSSW_8_0_X,  https://github.com/cms-sw/cmssw/pull/13388.

**Comment by deguio** [comment]
-1
superseded by #13388

**Pull request closed without merging**
