### PR TITLE
Run3-sim136 Extend the testing of wrong cell assignments in HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend the testing of wrong cell assignments in HCAL

#### PR validation:

Use the scripts to test workflows for different run periods.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , what is a bit worrying me that the test now become mixed with production in HCalSD, for example, in production we call
 
if (testNumber) {

for normal hits. Ideally debugging and tests should be maximally disentangle from ordinary computations. I would even add extra methods to the class and 
within ifdef only call these methods. Inside these new methods may be LogVerbatim, filling of arrays, printouts. When everything mix together the probability of bugs increases. I also do not understand why you have different key to enable debugging. I  would left ML_DEBUG for all type of debugs and do not add printdebug, because the level of printout is defined by configuration. You will not have extra printout if you do not want.

**Comment by civanch** [comment]
These my comments mainly to run time methods.

**Comment by civanch** [comment]
At least, in HCalSD there are lines 456 and 473, where test is mixed with normal processing.

**Comment by bsunanda** [comment]
@civanch testNumber is used to include layer # in the unitID and not the Set (which is used for run 1 simulation) - there were cases when no neutral density filter was used (most of Run2 and all Run3/Run4 configuration). But it was used for legacy code . So we had to have this test. This is not for any testing of the code. I think the name "testNumberingScheme"  is a bit misleading. I used initially for doing the test and some people found it useful when Run2 started and asked to utilise the feature

**Comment by bsunanda** [comment]
@civanch All tests are protected by EDM_ML_DEBUG, plotDebug or printDebug. testNumber is not a test - it is  a switch which is used to distinguish Run1 and part of Run2 with tthe most of Run2 and beyond.

**Comment by civanch** [comment]
+1

@bsunanda , the name is really misleading - let us not find better name in this PR, because it only includes "printdebug"

**Comment by bsunanda** [comment]
Hi Vladimir

I am planning to change the name HcalTestNumbering to something like HcalExtendedNumbering - not to confuse for future versions. I shall do that in view of 13_0_X. People need not use my memory for future HCAL versions. Regards

Sunanda
________________________________

**Comment by civanch** [comment]
Hi Sunanda, It is also possible to include "Run2" or year in the new name.

**Pull request merged**
