### PR TITLE
Run3-alca163 Modify the code for IsoTrack analysis to get it adapted for 2017 data

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Special treatment in IsoTrack analysis for 2017 data 

#### PR validation:

Tested by processing 2017 data

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@pohsun, @christopheralanwest, @tocheng, @tlampen Can one of you sign this please?

**Comment by bsunanda** [comment]
@silviodonato, @dpiparo Please try to have it integrated

**Comment by silviodonato** [comment]
can we merge this alca: ( @pohsun @tlampen @tocheng @christopheralanwest ) ?

**Comment by tocheng** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
