### PR TITLE
Revert "Add Unpacker for L1T Calo Layer 1 to unpack CICADA"

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmssw#45037

A re-revert will be needed to go with https://github.com/cms-sw/cmssw/pull/44222

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
+l1

in case that matters.

**Comment by smuzaffar** [comment]
thanks @aloeliger , I will merge it before 11h00. 
I can open a re-revert of this but then you might not be able to provide any changes there (if needed). Do you prefer to open a re-revert yourself or may be add re-revert changes directly in https://github.com/cms-sw/cmssw/pull/44222 ?

**Comment by aloeliger** [comment]
@smuzaffar I think the simplest would just be to package it together with https://github.com/cms-sw/cmssw/pull/44222, but it gets ever so slightly worse, because there are backports open as https://github.com/cms-sw/cmssw/pull/45293 & https://github.com/cms-sw/cmssw/pull/45294, so I don't know what's preferable from a history-of-cmssw perspective and the versioning. I can manipulate the commits as needed to get @fwyzard's simplifications in the proper places, it's jsut whatever you think would be most organized.

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2  , I am merging this for 11h00 IB now. Build errors are fixed, unit tests and add-on tests have run successfully.

**Pull request merged**
