### PR TITLE
More dependencies needed for UBSAN builds

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

Followup to #33933, this fixes two more missing dependencies in UBSAN builds,
```
CalibTrackerSiStripHitEfficiency/HitEff.cc.o:(.data.rel+0x3d18): undefined reference to `typeinfo for LumiScalers'
```
and
```
DQMDTMonitorModule/DTScalerInfoTask.cc.o:(.data.rel+0x3bd8): undefined reference to `typeinfo for LumiScalers'
```
This also adds comments for the two entries here and the ones in #33933 to document why the dependency is needed.

#### PR validation:

Trivial technical fix, compiles in CMSSW_12_0_UBSAN_X_2021-06-11-2300.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by francescobrivio** [comment]
+alca

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
