### PR TITLE
Phase 2 GT: Add missing GMTTkMuons instance name

### PR DESCRIPTION
**Pull request by HaarigerHarald**
#### PR description:

The muon collection `l1tTkMuonsGmtLowPtFix` got an instance name of the same name with a1fe4adffbee8f6192e50b5bb6f323aa9f500223 which we unfortunately missed. This PR should fix that.

### CODE REVIEW

**Comment by aloeliger** [comment]
@HaarigerHarald Thanks for this. I think I noticed this issue when I was messing around with cmsDriver and menu modifications.

**Comment by aloeliger** [comment]
please test

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test before signing. Sorry for very late.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
