### PR TITLE
New Heterogeneous Memory Pool

### PR DESCRIPTION
**Pull request by VinInn**
This PR replaces the old "notcub" cache allocator with a memory pool featuring
   * lockfree operations
   * backend agnostic implementation
The data interface is based on a simple ```Buffer``` that is completely  backend agnostic
The allocation interface (```makeBuffer```) currently depends on ```cudaStream_t``` that can be easily hidden behind ```void *``` or a light opaque ```struct```
A new feature is a "Bundle deleter": buffers can be bundle together and then freed in just one operation: this reduces the number of cuda calls.

All previous users of the cache allocator (at least for Pixel wf) have been migrated.

Tests passes: it is not slower than previous implementation. Need a free machine to make definitive tests.

Some cleanup is still required to remove debug statements.

Purely technical no regression expected.

Draft Slides for a possible presentation available @ https://cernbox.cern.ch/index.php/s/Ax4NHYGLHbG8N1C

### CODE REVIEW

**Comment by slava77** [comment]
@VinInn 
does this also provide performance benefits, like speedup in existing workflows/tests?
Please clarify.
Thanks.

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable GPU

**Comment by VinInn** [comment]
ah good catch! will remove the debug output  (and/or protect against missing devices?)

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
ok, needs rebase
I suspect will close it and open a new one...

**Pull request closed without merging**
