### PR TITLE
Add additional Error log messages

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added error log messages to the vector read code to help track down the cause of FileReadErrors in the integration builds.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@bbockelm please take a look

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please abort

**Comment by Dr15Jones** [comment]
I just couldn't live with using a printf style formatting.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Review by bbockelm — COMMENTED** [review]
We use the CMS exception hierarchy in other parts of this file.  Why use the ROOT-based mechanism in this PR instead?

Given that the CMS approach tends to provide more flexible feedback, I'd rather do that here...

**Comment by Dr15Jones** [comment]
@bbockelm all of problem reporting already in the `::Read*` functions only use `Error` and not a CMS exception. My addition just follows the already used pattern.

**Comment by bbockelm** [comment]
Yeah - I was looking at `::open`.

It's fine for now.  We should just make them all consistent later.  The `XrdAdaptor`, for example, provides nice additional information about the open file.  It would be useful if the logic migrated upward in the stack.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
merge


On 21 Jul 2017, at 22:03, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


+1
Tested at: 54dba8e<https://github.com/cms-sw/cmssw/commit/54dba8ef4b7b8fa6b0c8ea0fb66485f8955a92fa>
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19860/21677/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic:
4fa79e5<https://github.com/cms-sw/cmssw/commit/4fa79e5f0bc0baa954914eda20a9a163cbd95d6d>
0e08eae<https://github.com/cms-sw/cmssw/commit/0e08eaec20efd60a0776984bc93084617e380a2a>
7ed5e21<https://github.com/cms-sw/cmssw/commit/7ed5e210a34cc0896590a622bd75aabebdd9b03d>
be34a0d<https://github.com/cms-sw/cmssw/commit/be34a0d30fe1d87a53013f71e5faa9a1327715ac>
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19860/21677/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19860/21677/git-merge-result

**Pull request merged**
