### PR TITLE
Initialize all variables in GlobalCondition

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This should fix an UBSAN warning.

#### PR validation:

Compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
