### PR TITLE
CMSSW_7_6_X DQM updates for AlphaT HLT paths

### PR DESCRIPTION
**Pull request by MarkBaber**
Addition of DQM monitoring for the following HLT paths:
- HLT_PFHT200_PFAlphaT0p51_v
- HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v
- HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v
- HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v
- HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v
- HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @MarkBaber
this PR adds > 58k bins and removes 0. are you sure that all the monitored paths are needed? aren't there paths that can be removed?

thanks,
F.

**Comment by MarkBaber** [comment]
HLT_PFHT200_PFAlphaT0p51_v is a new trigger that requires monitoring.

I can remove monitoring for the following triggers if required:
HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v
HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v
HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v
HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v
HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v

We have two sets of triggers: the primary triggers (above) that we want to be the main triggers in Run2 and backup triggers with higher thresholds (that already have monitoring) in case the rates in data are not sustainable. There is uncertianty due to data/MC discrepancies whether we can utilise all the primary triggers but the backup triggers will definitely be in. Would you rather we remove the addition of monitoring of the primary triggers?

**Comment by Martin-Grunewald** [comment]
Triggers must all be monitored! Cut down on what you monitor per trigger.

**Comment by danduggan** [comment]
-1
for now until the suggestions from @Martin-Grunewald for reducing histos per trigger are implemented

**Comment by MarkBaber** [comment]
I have reduced the number of monitoring histograms for the all our triggers, the new request can be found here: https://github.com/cms-sw/cmssw/pull/10877

Should we close this and continue in the new PR?

**Comment by MarkBaber** [comment]
Closing and continuing in: https://github.com/cms-sw/cmssw/pull/10877

**Pull request closed without merging**
