### PR TITLE
Add dictionaries for std::pair<(GEM,ME0)DetId, std::vector<T>> that were missing

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

These were noticed in https://github.com/cms-sw/cmssw/pull/31261#issuecomment-682278106.

#### PR validation:

The test in https://github.com/cms-sw/cmssw/pull/31261#issuecomment-682278106 succeeds (with gcc10).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
