### PR TITLE
Changes to ECAL TTF4 DQM plots (for P5 production)

### PR DESCRIPTION
**Pull request by tanmaymudholkar**
This PR builds on top of changes that have already been introduced previously to CMSSW master to avoid conflicts with merging. This PR is a backport of [PR#23087](https://github.com/cms-sw/cmssw/pull/23087) to CMSSW master.

The new changes introduced are:
(1) Added alarm to trigger primitives quality summary plot -- the plot now turns RED when the fraction of towers in a given SM that have TTF4 flag set is greater than a threshold fraction which is currently set to 0.1.

(2) Added trend plots for the total number of towers in EB and EE with TTF4 flag set.

(3) COKE in the endcaps can mask on the strip level, not just the tower level; the ttFlag container now has meaningful values above 4 for situations where not all strip in a tower are masked. This requires the following changes to the DQM code:
    (3.1) TTF4 occupancy now counts all towers with ttF >= 4, not just ttF == 4
    (3.2) Flag mismatch for low interest, medium interest regions: only perform check if ttF == 1 or ttF == 3
    (3.3) For data/emulator comparisons, ignore towers with ttF > 4

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
Why is different from https://github.com/cms-sw/cmssw/pull/23087 ?
(number of changed lines)

**Comment by dmitrijus** [comment]
But now #22688 is closed - so this commit is not in master.

The policy is that we only merge production pull requests if code changes have already been merged into master.

So if you add additional commits - I can only sign if they are merged in master.

**Comment by tanmaymudholkar** [comment]
Hi @dmitrijus : the PR #22688 (which as you mention is closed) was made to 10_0_X, not to master. The corresponding PR to master was #22689 , which was merged.

So compare: [diff from this commit](https://github.com/cms-sw/cmssw/commit/49bc5005b857ad14eb05cfa3a737d50bd1e5eebf.diff) with [diff from 22689](https://patch-diff.githubusercontent.com/raw/cms-sw/cmssw/pull/22689.diff).

**Comment by jfernan2** [comment]
Successfully test and integrated in the Online DQM at P5.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
