### PR TITLE
Remove redundant unique_ptr constructor call from DDAlgorithmHandler

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Cleanup follow-up to #27097.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
File open error.

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
