### PR TITLE
Update BasicGenValidation_cff.py

### PR DESCRIPTION
**Pull request by menglu21**
#### PR description:
Backport from #29146

#### PR validation:
Procedure:
scram project CMSSW_10_2_21 & cmsenv
git cms-rebase-topic --old-base CMSSW_11_1_0_pre5 menglu21:master
git branch -m portFrom111XTo102X_genvalidation
then do the same things with original PR

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Original PR is #29146

### CODE REVIEW

**Comment by jfernan2** [comment]
backport

**Comment by jfernan2** [comment]
backport of #29146

**Comment by jfernan2** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by jfernan2** [comment]
+1
There is a dictionary duplicated error, I believe that unrelated to this PR:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-84983a/5459/dupDict/dup.txt

**Comment by silviodonato** [comment]
+1

**Pull request merged**
