### PR TITLE
Refactor SiPixel Charge Reweighting code

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

* Refactoring Charge Reweighting code so it can be used in a follow-up PR in the Phase-2 simulations.
* Changes to obey some of the coding rules that I came accross in these codes, like 2.7 and 4.1, 6.1
* Ran code-checks and code-format
For now this should lead to no changes.

#### PR validation:

Tested a Phase-1 and a Phase-2 wf:
```
12034.0_TTbar_14TeV+2021Design Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec 16 18:51:23 2022-date Fri Dec 16 18:36:24 2022; exit: 0 0 0 0
20834.0_TTbar_14TeV+2026D88 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Dec 16 18:59:10 2022-date Fri Dec 16 18:36:25 2022; exit: 0 0 0 0 0
2 2 2 2 1 tests passed, 0 0 0 0 0 failed
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport and no backport is needed

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hmm I did not get this error locally...

**Comment by tvami** [comment]
> Hmm I did not get this error locally...

Note to self: `scram build -k -j 16 check-headers` does the job

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Nice, differences in MsgLogger only
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-18-0000+4ce99d/54725/validateJR.html

**Comment by mmusich** [comment]
test parameters:
   * enable_test = threading
   * workflows_threading = 250202.182, 250202.184

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type trk

**Comment by tvami** [comment]
hi @cms-sw/upgrade-l2 @cms-sw/simulation-l2 @cms-sw/orp-l2 is there a chance we could merge this before the winter break? In the end it's a very technical PR that doesnt change the physics output, but I'd need it for a follow-up PR

**Comment by civanch** [comment]
+1

updates are technical mostly

**Comment by srimanob** [comment]
+Upgrade

Technical PR, change is not expected. Failure in comparison does not come from this PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
