### PR TITLE
Payload generator 7 6 x

### PR DESCRIPTION
**Pull request by andrewj314**
Made the fixes per Slava's request - the TFormula and TGraph tools are now in CondFormats/PhysicsToolsObjects/test, and the RecoTauTag/RecoTau/data file with all the rootfiles is now gone (I think - I deleted it in CMSSW but git didn't seem to track the change...)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
looks like in a misconfiguration error in the IB.

**Comment by slava77** [comment]
@cmsbuild please test
CMSSW_7_6_X_2015-06-28-2300 has a fix to the PR tests issue in the run2 workflows

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9945	cf2e034
- event processing workflows are not affected, confirmed by jenkins (no differences in comparisons)

**Comment by ggovi** [comment]
+1

**Pull request merged**
