### PR TITLE
Pixel Phase 1 summary maps [90X]

### PR DESCRIPTION
**Pull request by leggat**
Including the new summary maps for the phase 1 pixel detector in the 90X release.

### CODE REVIEW

**Comment by boudoul** [comment]
For the record, this is a backport of the master (already merged) PR :   #17880

**Comment by dmitrijus** [comment]
+1

**Comment by vanbesien** [comment]
Hey,
For the 9_0 which we are currently installing for Online, we got requests from tracker to manually put PR18028 and PR18017 on top of what was merged in 9_0.
If you want this PR on Online as well _before_ it is merged in 9_0, please follow the normal procedure: Tag collector + contact us.

**Comment by fioriNTU** [comment]
@leggat please take the @vanbesien suggestion, we need this online

**Comment by dmitrijus** [comment]
Hi, if this is a backport from the master branch, please make sure it has the same commits as the PR to that master branch. This PR contains 50 lines less than the one in master.

**Comment by leggat** [comment]
Hi @dmitrijus - in fact this PR is more up-to-date than the merged one because of the bug fix introduced. I tried to make a new PR for 91X (https://github.com/cms-sw/cmssw/pull/18146) to bring the merged code in line with this one, but it appears that 91X is now closed. How should I go about updating the already merged code?

**Comment by boudoul** [comment]
hi @leggat , 91X is not closed, it is just that it is the devlopment release and therefore you should make a PR to the default developement release called 'master '  which is the default queue when making a PR  (and not choose  91X )

**Comment by leggat** [comment]
Ah sorry. Please find the new PR at https://github.com/cms-sw/cmssw/pull/18148

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
