### PR TITLE
OnlineClients

### PR DESCRIPTION
**Pull request by fioriNTU**
Adjusting the online client to run on live and introducing a special client that may be ran to ease the time alignment of the new detector

Also removed two ROC level plots.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
If want us to run pixel_timingScan_dqm_sourceclient-live_cfg.py  you will have email the core team and ask us to enable it.

**Comment by fioriNTU** [comment]
I already had some discussion with Broen about it. Atm we don't know if it is worth to run this client privately or in production, would be great if we get some time to test it ;-)
However this is something that will become important at the time of first collisions, for the moment I wanted just to put it in a "public" place

**Comment by fioriNTU** [comment]
@dmitrijus The error says that "TrackingMonitor" crashed, but there is no Tracking stuff in my clients. Maybe is the IB used to be broken?

**Comment by dmitrijus** [comment]
I have seen this error before, looks unrelated. Will restart the tests just in case.

**Comment by dmitrijus** [comment]
please test

**Comment by fioriNTU** [comment]
@dmitrijus so the crash is gone?!? How is that possible?

**Comment by davidlange6** [comment]
was a bug in the integration build fixed yesterday

**Comment by davidlange6** [comment]
+1

**Comment by dmitrijus** [comment]
@fioriNTU 

Please make a backport to 90x and 84x, since this is what we run and will run online.

**Comment by fioriNTU** [comment]
@ Dmitrijus, 90X is closed as far as I know, shall I back-port the same?

**Comment by dmitrijus** [comment]
@fioriNTU It's not closed for developments, not the backports. And yes, you should backport it to 90x.

**Pull request merged**
