### PR TITLE
HLT Offline DQM: add HLT_Ele30_WPTight_Gsf and change E/gamma IDs [`13_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #42049
backport of #42294

#### PR description:

Verbatim backport of #42049 and #42294 by @RSalvatico. From the descriptions of the two PRs:

> The purpose of this PR is to:
> 
>   * add `HLT_Ele30_WPTight_Gsf` to the OfflineDQM among the monitored paths in `HLT/EGM/TagAndProbeEffs`, as requested by TSG in [CMSHLT-2810](https://its.cern.ch/jira/browse/CMSHLT-2810);
> 
>   * change the offline electron and photon IDs for EGM to the newest Run3 ones ([electrons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Winter22_122X_V1_cff.py), [photons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_RunIIIWinter22_122X_V1_cff.py));
> 
>   * clean up, removing HEM/HEP plots (which were relevant in 2017) and removing trigger paths which are no longer in the menu.

and

> This PR is a follow up of #42049 . In the latter, the update of the `egmGsfElectronIDsForDQM` module to include (via VID) only new Run3 electron IDs had created issues to non-EGM DQM, such as TOP, B2G and ParticleNet. In order to address this, the current PR updates the electron IDs used by non-EGM DQM too. Other POGs and PAGs have been informed and have followed up on [CMSHLT-2876](https://its.cern.ch/jira/browse/CMSHLT-2876).

FYI: @cms-sw/egamma-pog-l2

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42049
#42294

Update of EGM-HLT offline DQM relevant to 2023 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by RSalvatico** [comment]
Thanks for the backports, @missirol!

**Comment by perrotta** [comment]
Thank you for noticing @missirol , and apologize for not having taken care of it myself when merging the master version of this PR.

There are a huge amount of messages like
```
%MSG-w TopMonitor:  TopMonitor:topElecMuonHLTMonitor_Mu23Ele12_ref  08-Jul-2023 18:21:25 CEST Run: 346512 Event: 243042266
Electron ID handle not valid 
```

@RSalvatico they must be fixed in the master first, and then the fix should be included in these backports

**Comment by missirol** [comment]
For what I understand, the changes below removed old electron IDs from a module used in DQM.
https://github.com/cms-sw/cmssw/pull/42049/files#diff-6e31c5da031ccb91cbed539cec1d6bc3a0d8582ea3452f82f7e260d93990c6b6L983

.. but the many clients of that module were not updated accordingly, e.g.
https://github.com/cms-sw/cmssw/blob/c2ba821b30ab0102f400191e81b2f008cd59adcf/DQMOffline/Trigger/python/TopMonitor_cfi.py#L89

In `master`, I guess one should move the clients to the new ID [1]. The same could be done in `13_(0|1)_X`, but maybe this will complicate comparing to older runs (where DQM clients used the old ID). For the backports, the alternative is to keep the old IDs included in `egmGsfElectronIDsForDQM` [2].

@cms-sw/egamma-pog-l2, please suggest how to update the backports.

[1] This could be sufficient to update the clients (to be confirmed by experts).
```
for foo in cutBasedElectronID-Summer16-80X-V1 cutBasedElectronID-Fall17-94X-V1 cutBasedElectronID-Fall17-94X-V2 ; do
  sed -i "s|${foo}|cutBasedElectronID-RunIIIWinter22-V1|g" DQMOffline/Trigger/*/*.*
done
```

[2] Doing the following on top of the current backports.
```diff
-my_id_modules = ['RecoEgamma.ElectronIdentification.Identification.cutBasedElectronID_Winter22_122X_V1_cff']
+my_id_modules = ['RecoEgamma.ElectronIdentification.Identification.cutBasedElectronID_Summer16_80X_V1_cff',
+                 'RecoEgamma.ElectronIdentification.Identification.cutBasedElectronID_Fall17_94X_V1_cff',
+                 'RecoEgamma.ElectronIdentification.Identification.cutBasedElectronID_Winter22_122X_V1_cff']
```

**Comment by RSalvatico** [comment]
Thanks a lot for checking, I am looking into it. I was planning to interfere the least possible with other group's DQMs so I don't dislike the option of keeping the old IDs available for other clients, but let me quickly discuss this.

**Comment by RSalvatico** [comment]
Follow up: I don't think it was my changes that generated the log messages that @perrotta mentioned, or at least not entirely. I see the same when testing for example the `TopMonitor` in 13_1_0 out of the box. And adding back the old ID modules to `egmGsfElectronIDsForDQM` in my PR makes no difference. The reason why the `TopMonitor` (and I guess others too) don't find a valid electron ID is not clear yet, but I'm digging.

 Forgive my ignorance, is there a clear way to see which lines are being added to the logs wrt before?

**Comment by missirol** [comment]
> I see the same when testing for example the TopMonitor in 13_1_0 out of the box. And adding back the old ID modules to egmGsfElectronIDsForDQM in my PR makes no difference.

I do not understand that. The IBs show the warnings in `CMSSW_13_2_X_2023-07-10-2300` [1] and not in `CMSSW_13_1_X_2023-07-10-2300` [2]. It may not be the full story, but it is consistent with the integration of #42049.

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_13_2_X_2023-07-10-2300/el8_amd64_gcc11/-GenuineIntel/matrix-results/12434.0_TTbar_14TeV+2023/step3_TTbar_14TeV+2023.log

[2] https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_13_1_X_2023-07-10-2300/el8_amd64_gcc11/-GenuineIntel/matrix-results/12434.0_TTbar_14TeV+2023/step3_TTbar_14TeV+2023.log

**Comment by RSalvatico** [comment]
Yes, my bad. I have just realized what the problem was in my testing setup: I was running the TopMonitoring sequences without running the EGM ones first - hence the required electron IDs were not produced and hence the warnings. 

Following the discussion we had today in the TSG meeting, I will wait one week to collect possible feedback from other PAGs and POGs. If no objections are received, I will proceed with updating the electron IDs used by other groups too.

**Comment by missirol** [comment]
> Following the discussion we had today in the TSG meeting, I will wait one week to collect possible feedback from other PAGs and POGs.

@RSalvatico , I would suggest to open a JIRA ticket in CMSHLT describing briefly this change. We can then ask explicit feedback from the relevant groups without waiting one week. We should be able to converge by Monday at the latest.

**Comment by RSalvatico** [comment]
Link to the JIRA ticket [CMSHLT-2876](https://its.cern.ch/jira/browse/CMSHLT-2876).

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
unhold

Including the backport of #42294 fixed the issue causing log warnings, as expected.

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
