### PR TITLE
VID Feature Requests for 75X (76X forward port)

### PR DESCRIPTION
**Pull request by lgray**
This pull request implements the following requested features in VID:
- Validation tool to yield a checksum that validates the expected ID performance, in addition to the    checksumming of configurations
- A lightweight and straightforward tool for manipulating the bitmap output of the cuts (so that cuts can be masked on the fly in code)
- Output of the values cut upon in addition to the cut results
- Use of ExpressionEvaluator
- The middle two points are implemented as "vid::CutFlowResult" which is a digest that implements a masking and value-retrieval interface.

This pull request now also implements "MINIAODfromMINIAOD" data reprocessing and VID-by-value, which only functions for objects with all necessary information embedded in some way (except for vertices, etc which are always in the event).

@ikrav @cmkuo @gpetruc

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray please pick up the commit from #9950 here.
Thanks

**Comment by slava77** [comment]
jenkins is "sick"
the last requested build has failed ... and it looks like some intervention will be needed

**Comment by lgray** [comment]
What do you mean by 'some intervention'?

(Sent from my Nexus 6)

**Comment by smuzaffar** [comment]
One of the jenkins builders node (vocms0315) has AFS cache issues and it 
was not able to find any cmssw releases from AFS. Due to this issue many 
PR tests did not start. I have fixed the AFs cache issue on this machine 
and restarted many failed PRs.

**Comment by slava77** [comment]
Shahzad,
There was also a problem with ib. The latest available was 07-04-23 before
your fix to the unit test. Is that fixed too?

**Comment by smuzaffar** [comment]
@slava77 , unit test issue should still be there but not all the PR will be triggering it

**Comment by slava77** [comment]
the unit test error is present in the IB as well
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc491/CMSSW_7_6_X_2015-07-05-1100/unitTestLogs/PhysicsTools/PatAlgos

The rest of the test passed

**Comment by lgray** [comment]
fixed a bug, please test again

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10059	 336e225
- same code as #9659	156b815
- no changes in jenkins tests comparisons with the baseline

**Comment by monttj** [comment]
+1
It is adding new features to VID.
no issues from AT side.

**Comment by lgray** [comment]
@Dr15Jones , @franzoni Could you please take a look here and +1 if you find things agreeable? Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
will have suggestions to consider for the next round..

**Pull request merged**
