### PR TITLE
[TEST-ONLY] Turn on concurrentLumis

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

This PR switches on always concurrentLumis, using nCurrentLumis = 2. Taken from #31369. 
It will be used to test #31689 and #31678 with concurrentLumis on.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test with  #31689, #31678

**Comment by jfernan2** [comment]
@silviodonato  thanks a lot for this test!
However, is my understanding correct that Jenkins test use a Single Core? So, we will actually see concurrent LS in such scenario?

**Comment by silviodonato** [comment]
please test with #31689, #31678

**Comment by jfernan2** [comment]
@silviodonato with the last settings, the system complains about almost every DQM module with:
"The following modules require synchronizing on LuminosityBlock boundaries"
:-0

**Comment by makortel** [comment]
I suspect the concurrent lumis should not be turned on for harvesting.

**Comment by silviodonato** [comment]
> I suspect the concurrent lumis should not be turned on for harvesting.

yes, indeed. All errors are due to 
```
----- Begin Fatal Exception 19-Oct-2020 17:48:45 CEST-----------------------
An exception of category 'iGetter Error' occurred while
   [0] Processing global end LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module SiPixelCertification/'sipixelCertification'
Exception Message:
ME Pixel/EventInfo/DCSSummary was requested but not found.
----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
please test with #31689, #31678, #31829

**Pull request closed without merging**
