### PR TITLE
New PR for Top and BTV - backport to 92X

### PR DESCRIPTION
**Pull request by defranchis**
Backport of https://github.com/cms-sw/cmssw/pull/19119 and https://github.com/cms-sw/cmssw/pull/19641

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by defranchis** [comment]
@mtosi can we please test?

**Comment by mtosi** [comment]
@cmsbuild, please test

On Mon, Jul 10, 2017 at 5:57 PM, Matteo Defranchis <notifications@github.com

**Comment by dmitrijus** [comment]
+1

**Comment by defranchis** [comment]
@davidlange6 this PR is the backport of https://github.com/cms-sw/cmssw/pull/19119 and https://github.com/cms-sw/cmssw/pull/19641(both merged). What should we do with this PR? Should it be merged as well? Thanks

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
@defranchis can you check if this PR is included #19961 ?

**Comment by defranchis** [comment]
@fwyzard yes, it seems that it's included

**Comment by fwyzard** [comment]
Thanks. Can you close this PR then ?

**Comment by defranchis** [comment]
sure

**Pull request closed without merging**
