### PR TITLE
Phase2-hgx98 Correct DetId usage for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
Only HGCalDetId is the correct DetId function for HGCal at this moment

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21922	737f17f
- technical change, relevant only for phase-2 HGCAL
- jenkins tests pass and comparisons show no differences (ignoring messageLog differences due to file i/o messages)

**Comment by bsunanda** [comment]
@nsmith-, @rekovic, @thomreis Please approve this PR

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
