### PR TITLE
Add postprocess-scan-build.py to Utilities/StaticAnalyzers

### PR DESCRIPTION
**Pull request by gartung**
This will filter duplicate entires in scan-build report

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
please abort 31288

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
+1
@fabiocos , this is new script to remove the duplicates from the static analyzer results.

**Comment by smuzaffar** [comment]
@fabiocos , can we get this. This should reduce the static analyzer output.

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@slava77 , after integration of this PR, Static Analyzer page does not contain duplicates and should be loadable. Can you please check it for latest IBs and report if it works for you?

**Comment by slava77** [comment]
On 10/31/18 9:56 AM, Malik Shahzad Muzaffar wrote:
> @slava77
> , after integration of this PR, Static Analyzer page does not contain
> duplicates and should be loadable. Can you please check it for latest
> IBs and report if it works for you?
> 


I assume that this PR made it before the CMSSW_10_4_X_2018-10-30-1100
build started


I see "All Bugs" 110152
this is dominated by "mutable member if accessed via const pointer" with
83972 counts
However, with this category checkmarked, I count only 484 cases actually
displayed.

Shouldn't the total for "mutable member if accessed via const pointer"
be displayed as 484?

**Pull request merged**
