### PR TITLE
Add missing newlines in Simulation modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
SimCalorimetry/EcalTrigPrimProducers
SimCalorimetry/HcalTrigPrimProducers
SimG4CMS/Calo
SimG4CMS/HcalTestBeam
SimMuon/MCTruth
SimMuon/RPCDigitizer
SimTracker/TrackTriggerAssociation
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
