### PR TITLE
Run2-sim12 Backport PR #19478 for fixing bug of ECAL simulation

### PR DESCRIPTION
**Pull request by bsunanda**
Fixes the bug in the calculation of the distance of the hit point to the readout unit

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @davidlange6 This correction is critical for Higgs analysis. It was discussed in ECAL DPG and there is a request to have this incorporated in 8_0_X.

**Comment by davidlange6** [comment]
80x isn't a very interesting release for full sim. perhaps you mean 71x? Anyway, the sim group should discuss and make a proposal. From the release side, we'd need a backwards compatibility option (_enabled_ by default) given the billions of MC already generated

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
I would think we can backport this fix in easy way to any release except 7_1_X. For 7_1_X we need to make more complicate thing adding extra flag, which by default produce the same result but may enable the fix.

**Comment by davidlange6** [comment]
but its essentially interesting for 93x and 71x at this point...(unless you propose to stop the 92x MC to wait)

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
Please remove the change to file ```HLTrigger/special/src/SealModule.cc``` - it does not belong here.

**Comment by bsunanda** [comment]
@Martin-Grunewald You are right - soon after the push I realized it - I am correcting it right now. Please wait for a few mins.

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
-1
Don't use cms-merge-topic
Please follow http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by bsunanda** [comment]
Made a mess - close this and make a fresh PR

**Comment by slava77** [comment]
-1

**Pull request closed without merging**
