### PR TITLE
update conddb tool to improve handling/showing of time-types/time-stamps

### PR DESCRIPTION
**Pull request by apfeiffer1**
Convert time stamps to UTC when printing, also add "raw" timestamp to output to ease comparisons.
Insertion time still shown in local time.
"De-mangle" run-lumi based timestamps, show run and lumi separate plus "raw" timestamp.
Update table-header info accordingly.

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by apfeiffer1** [comment]
On Friday, June 5, 2015, cmsbuild <notifications@github.com> wrote:

>  -1
> Tested at: add3003
> <https://github.com/cms-sw/cmssw/commit/add3003ba0fde1dcb43f1bdd871d8ef43d96f114>
> When I ran the RelVals I found an error in the following worklfows:
> 25202.0 step2
>
> runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+MINIAODMCUP15/step2_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+MINIAODMCUP15.log
>
>
> you can see the results of the tests here:
>
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9467/5337/summary.html
>
>
>
this failure can not be related to _anything_ in the PR ...

please ignore.



-- 
Thanks,
       cheers, andreas

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
