### PR TITLE
[13_0_X] Update L1T Menu tag for 2023/2024/Run4 in MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #41485

This PR updates the L1T Menu tag in the MC GTs for 2023/2024/Run4 to the latest available tag, i.e. `L1Menu_Collisions2023_v1_1_0-v2_xml`, as requested in [this CMSTalk message](https://cms-talk.web.cern.ch/t/update-of-the-2023-l1-menu-tag-l1menu-collisions2023-v1-1-0/23386/3).

In addition, the `run3_[data|hlt]_relval` symbolic GTs are updated as well with the same tag via the autoCondModifier `L1TUtmTriggerMenuForRelValForRun3`.

As per @missirol's request I also updated the same tag in `Configuration/HLT/python/autoCondHLT.py`

*EDIT:*
Following the request in [this CMSTalk post](https://cms-talk.web.cern.ch/t/request-for-new-run3-hi-mc-gt-with-updated-l1-menu-for-130x/23559) we have also updated the HI MC GTs for 2022 and 2023 with the correct L1Menu tag (`L1Menu_CollisionsHeavyIons2022_v1_1_0-d1_xml`)

FYI @caruta

The GT differences are:
- **2022 realistic HI**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_HI_v4/130X_mcRun3_2022_realistic_HI_v5
 - **2023 design**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_design_v5/130X_mcRun3_2023_design_v6
 - **2023 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_v7/130X_mcRun3_2023_realistic_v8
 - **2023 cosmic realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_realistic_deco_v6/130X_mcRun3_2023cosmics_realistic_deco_v7
 - **2023 cosmic design**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_design_deco_v5/130X_mcRun3_2023cosmics_design_deco_v6
 - **2023 realistic HI**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_HI_v12/130X_mcRun3_2023_realistic_HI_v14
 - **2024 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2024_realistic_v5/130X_mcRun3_2024_realistic_v6
 - **Phase2 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun4_realistic_v3/130X_mcRun4_realistic_v7

#### PR validation:
See master PR for the validation

#### Backport:
Backport of #41485

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #41485

**Comment by francescobrivio** [comment]
test parameters:

- workflows = 140.001,12434.0,12834.0,23234.0

**Comment by missirol** [comment]
+hlt

See https://github.com/cms-sw/cmssw/pull/41485#issuecomment-1532202297 (modulo the fact that, in the latter comment, the point about the HIon GT does not apply to `130X` GTs).

The RelVals-INPUT error is assumed to be unrelated to this PR.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by saumyaphor4252** [comment]
+ alca
- workflows testing the GTs pass
- diffs in reco comparisons only for MsgLogger

**Comment by missirol** [comment]
+hlt

 - The HLT changes are okay (and thanks for updating `autoCondHLT.py`).

 - This PR is a prerequisite for integrating the next version of the 2023 HLT menu in a future PR in the next days (as that new HLT menu will require the L1T menu included here, i.e. `2023-v1_1_0`).

**Comment by missirol** [comment]
@saumyaphor4252 , just a reminder that HLT would also need a backport of this PR to `13_1_X` if `master` moves to `13_2_X` before #41485 is merged.

**Comment by saumyaphor4252** [comment]
> just a reminder that HLT would also need a backport of https://github.com/cms-sw/cmssw/pull/41485 to 13_1_X if master moves to 13_2_X before https://github.com/cms-sw/cmssw/pull/41485 is merged.

Thanks @missirol Duly Noted. The backport will be needed from AlCa POV too, in that case.

**Comment by perrotta** [comment]
- The tag versions in Confdb.py are newer (let say: higher version number) in this backport PR than in the master version of it: is it intended?
- The HI MC GTs for 2022 and 2023 where merged in master in some other PR? Please add the link in the PR description if so

**Comment by missirol** [comment]
@cms-sw/alca-l2 , any chance we could converge on this PR ? HLT needs it to integrate the next HLT menu.

**Comment by francescobrivio** [comment]
Sorry Marino the "confdb" (instead of "conddb") in the comment confused me so I forgot about it! I'll take a look immediately!

**Comment by francescobrivio** [comment]
Ciao Andrea,

> * The tag versions in Confdb.py are newer (let say: higher version number) in this backport PR than in the master version of it: is it intended?

Yes, because here we are updating the 130X GTs, while in master we were updating the 131X GTs - so you can't really compare the version number of two different cycles. So this is a backport in the sense that we introduced the same conditions, but the autoCond file itself is different by construction because of the different GT names :)

> 
>     * The HI MC GTs for 2022 and 2023 where merged in master in some other PR? Please add the link in the PR description if so

The HI MC GTs are being frequently updated following the requests from the HI group - there have a been a few updates that so far we included only in 125X and 131X (due to MC production plans), but now HI group requested to update also the 130X version of the GTs (the request is linked in the "_EDIT_" section of this PR description)

**Comment by perrotta** [comment]
Thank you @francescobrivio 

So, the HI MC tags where already there in master (brought there by #41327). Let me point out that master was further updated for these GTs with #41437: is that something  that we should also backport to 13_0_X?

**Comment by francescobrivio** [comment]
> Let me point out that master was further updated for these GTs with #41437: is that something that we should also backport to 13_0_X?

Thanks Andrea for this! We'll inquire with HI experts if it's needed or not.
For the moment it's definitely not urgent - so I suggest we merge this PR which is indeed urgent for HLT and we can eventually followup with another PR for HI only if needed.

**Comment by perrotta** [comment]
+1
- Backport of https://github.com/cms-sw/cmssw/pull/41485 and https://github.com/cms-sw/cmssw/pull/41327
- https://github.com/cms-sw/cmssw/pull/41437 still needs to be backported (if ever needed)

**Comment by saumyaphor4252** [comment]
image
The backport is done in https://github.com/cms-sw/cmssw/pull/41567 and https://github.com/cms-sw/cmssw/pull/41440.

**Pull request merged**
