### PR TITLE
Tracker Alignment: Backport Multi-IOV and condor submission tools

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/27623  
(+ https://github.com/cms-sw/cmssw/pull/28739 and https://github.com/cms-sw/cmssw/pull/26999 and https://github.com/cms-sw/cmssw/pull/28767/commits/a3779a94bbf78a8c39fb909efe89ae1bfed1a309)

#### PR description:

As part of the Tracker Alignment preparation work for Run3 is expected to happen in the 10.6.X cycle, as the latest and greatest Data and MC samples for 2018 data will be available within the Run2 Ultra-Legacy production, we think it is advisable to have the possibility to submit alignment validation jobs from a 10.6.X release.  
This - at the moment - is not possible as the migration to the condor submission system has happened only in the 11.0.X cycle (via PR https://github.com/cms-sw/cmssw/pull/27623) and the tool in 10.6.X is still relying on the (decommmissioned) LSF submission system. 
This PR introduces that commit (eb3a91953da958250b41556fd16855194b4b1123) *verbatim* into 10.6.X.
We also profit of this PR to backport some other utilities such as the unit tests for the validation package (introduced at https://github.com/cms-sw/cmssw/pull/28739) and a fix to one of the example initialization files in commit https://github.com/cms-sw/cmssw/commit/3f35f199c9e70287da261ac9f7872c05dc64377d.

#### PR validation:
Relies on the unit tests introduced in this PR

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/27623  + https://github.com/cms-sw/cmssw/pull/26999 + https://github.com/cms-sw/cmssw/pull/28739 and https://github.com/cms-sw/cmssw/pull/28767/commits/a3779a94bbf78a8c39fb909efe89ae1bfed1a309

cc: 
@connorpa @vbotta @adewit @henriettepetersen

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
I can't reproduce the error in the tests in my local setup:
```
cmsrel CMSSW_10_6_X_2020-03-05-1100
cd CMSSW_10_6_X_2020-03-05-1100/src/
git cms-merge-topic 29117
scramv1 b -j 8
cmsenv
voms-proxy-init -voms cms
scramv1 b runtests
```

results in :

```
...
Requesting file information for '/MinimumBias/Run2017A-TkAlMinBias-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting file information for '/Cosmics/Run2017A-TkAlCosmics0T-PromptReco-v1/ALCARECO' from DAS... Done.
Requesting run information for '/DoubleMuon/Run2017A-TkAlZMuMu-PromptReco-v3/ALCARECO' from DAS... Done.
[3B/3B][100%][==================================================][3B/s]  o-v3/ALCARECO' from DAS... 
Done.
TkAlOfflineValidation.validation_MinBias.prompt would run: TkAlOfflineValidation.validation_MinBias.prompt.sh
TkAlOfflineValidation.validation_MinBias.express would run: TkAlOfflineValidation.validation_MinBias.express.sh
TkAlOfflineValidation.validation_cosmics.prompt would run: TkAlOfflineValidation.validation_cosmics.prompt.sh
TkAlOfflineValidation.validation_cosmics.express would run: TkAlOfflineValidation.validation_cosmics.express.sh
TkAlGeomCompare.Tracker.prompt_run278819_vs_express_run278819 would run: TkAlGeomCompare.Tracker.prompt_run278819_vs_express_run278819.sh
TkAlZMuMuValidation.some_zmumu_validation.prompt would run: TkAlZMuMuValidation.some_zmumu_validation.prompt.sh
TkAlZMuMuValidation.some_zmumu_validation.express would run: TkAlZMuMuValidation.some_zmumu_validation.express.sh
TkAlTrackSplitting.some_split_validation.prompt would run: TkAlTrackSplitting.some_split_validation.prompt.sh
TkAlTrackSplitting.some_split_validation.express would run: TkAlTrackSplitting.some_split_validation.express.sh
status = 0

---> test testAlignmentOfflineValidation succeeded
```

@christopheralanwest can tests be invoked again?

@smuzaffar do you have any idea if this problem:

```
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-03-05-1100/bin/slc7_amd64_gcc700/validateAlignments.py", line 22, in <module>
    import Alignment.OfflineValidation.TkAlAllInOneTool.crabWrapper as crabWrapper
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-03-05-1100/python/Alignment/OfflineValidation/TkAlAllInOneTool/crabWrapper.py", line 24, in <module>
    crabFile = open('/'.join([os.environ["CRABPYTHON"],'crab']))
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2020-03-05-1100/external/slc7_amd64_gcc700/bin/../../../../../../../slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CRABPYTHON'
Failure running all-in-one test: status 1
```

which seems to be related to this environment variable `CRABPYTHON` not set might be due to some transient glitch?

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
@mmusich I suspect the issue is that the PR tests do not have access to afs:
```
bash: /afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env.sh: No such file or directory
bash: /afs/cern.ch/cms/ccs/wm/scripts/Crab/crab.sh: No such file or directory
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-03-06-1100/bin/slc7_amd64_gcc700/validateAlignments.py", line 22, in <module>
    import Alignment.OfflineValidation.TkAlAllInOneTool.crabWrapper as crabWrapper
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-03-06-1100/python/Alignment/OfflineValidation/TkAlAllInOneTool/crabWrapper.py", line 24, in <module>
    crabFile = open('/'.join([os.environ["CRABPYTHON"],'crab']))
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2020-03-06-1100/external/slc7_amd64_gcc700/bin/../../../../../../../slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CRABPYTHON'
Failure running all-in-one test: status 1
```

**Comment by mmusich** [comment]
> @mmusich I suspect the issue is that the PR tests do not have access to afs:

@christopheralanwest the very same code ([link](https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/python/TkAlAllInOneTool/crabWrapper.py#L9)) runs in the master IB unit tests without apparent issues, see [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-03-07-1100/unitTestLogs/Alignment/OfflineValidation#/367)

**Comment by mmusich** [comment]
OK we need to backport also this PR https://github.com/cms-sw/cmssw/pull/26999, in order to pass the unit test.

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
