### PR TITLE
Moving GBRForestWriter to CommonTools/Utils: 75X

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10575

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10754 6caed4378c1323a3880132e4d1f4c159d3893853

Moving GBRForestWriter, a fairly general utility, to a more common and more appropriate location. There should be no change in run-time behavior.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10754/7296/summary.html) against baseline CMSSW_7_5_X_2015-08-14-1100 show no significant differences, as expected.

**Comment by cvuosalo** [comment]
As an issue for a future PR, in GBRForestWriter.h, class GBRForestWriter inherits from edm::EDAnalyzer, which is not thread-safe, as flagged by the static analyzer. The inheritance should be changed to the appropriate thread-safe version.

**Pull request merged**
