### PR TITLE
Update to HLT menu V2.1 - Minotaur (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update to HLT menu V2.1 - Minotaur (92X)
Based on CMSSW_9_2_7

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19502

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Test failures are due to new L1T menu ```L1Menu_Collisions2017_dev_r6_woCDC_m6_xml``` needed for the V2 HLT menu in the standard 92X GT keys.

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need ```L1Menu_Collisions2017_v2_m6_full_xml``` in GTs.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Current status as I understand it: need ```L1Menu_Collisions2017_v2_m6_full_xml``` in 92X GTs - but GT updates #19723 need to be integrated first, before making the next set of GTs with the new L1T menu.

**Comment by davidlange6** [comment]
> On Jul 18, 2017, at 9:53 AM, Martin Grunewald <notifications@github.com> wrote:
> 
> Current status as I understand it: need L1Menu_Collisions2017_v2_m6_full_xml in 92X GTs - but GT updates #19723 need to be integrated first, before making the next set of GTs with the new L1T menu.

and 19723 needs validation of 930pre1 to be complete....

**Comment by Martin-Grunewald** [comment]
@arunhep @franzoni 
Now that #19723 is merged, what it the timeline to add the L1T menu (and possibly the psfecal payloads) to the next set of 92X GTs?

**Comment by arunhep** [comment]
@Martin-Grunewald please wait until new release is built for the V1 MC production. current L1T menu which is now in 9_2_X is the one which is validated by 9_3_0_pre1 validation and presented today in PPD general meeting. Most likely it will be the one which will be used for V1 production. I will send you the GTs then.

@davidlange6 what is the ETA of having the release for V1 MC production? @franzoni @cerminar

**Comment by davidlange6** [comment]
> On Jul 20, 2017, at 9:42 PM, Arun Kumar <notifications@github.com> wrote:
> 
> @Martin-Grunewald please wait until new release is built for the V1 MC production. current L1T menu which is now in 9_2_X is the one which is validated by 9_3_0_pre1 validation and presented today in PPD general meeting. Most likely it will be the one which will be used for V1 production. I will send you the GTs then.
> 
> @davidlange6 what is the ETA of having the release for V1 MC production? @franzoni @cerminar

you mean with a failed L1 validation? I think we decided to understand the trigger issues and decide tomorrow, no?

**Comment by arunhep** [comment]
>@davidlange6 what is the ETA of having the release for V1 MC production? @franzoni @cerminar
you mean with a failed L1 validation? I think we decided to understand the trigger issues and decide tomorrow, no?

i dont think so. we should have the release and then anyways this release will also be validated. trigger issues (if they are really the issues or expected deviations) can be understood in parallel.

**Comment by davidlange6** [comment]
We agreed in something else already. Anyway putting things thought to be wrong by the experts into production is not the way to go.

Cheers,
David


On 20 Jul 2017, at 21:53, Arun Kumar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> what is the ETA of having the release for V1 MC production? @franzoni<https://github.com/franzoni> @cerminar<https://github.com/cerminar>
you mean with a failed L1 validation? I think we decided to understand the trigger issues and decide tomorrow, no?

i dont think so. we should have the release and then anyways this release will also be validated. trigger issues (if they are really the issues or expected deviations) can be understood in parallel.

**Comment by fwyzard** [comment]
I am on holiday, so I have no idea what people "agreed".

Unless such agreement is to include the L1 menu "2017 v2" and the HLT menu
v2.0 or v2.1, whoever "agreed" made the wrong call.

As far as I know it is up to Trigger Coordination to decide the L1 and HLT
menus for v data taking and MC production, and we definitely request to
include the v2 L1 and HLT menus in the upcoming MC production.

Finally, any such discussion should *not* happen on GitHub, but on the
relevant e-group or (sigh) hypernews.

.Andrea (on holidays) for Trigger Coordination

**Comment by Martin-Grunewald** [comment]
Hmmm... Please elaborate what is though wrong by which experts - I am not aware something / anything /bugs/crashes/ need to be fixed. Now, what needs to be fixed in the sense of having something on the HLT side useful is integration of this PR followed by a backport of the most recent 93X PR. That's why we need the GTs with the new L1T menu.

**Comment by arunhep** [comment]
@Martin-Grunewald please cherry-pick the following commit https://github.com/arunhep/cmssw/commit/00e35646c14c7b2ba1ec2f661badd6b9190fa878
which includes the new L1T menu. 
I am not able to make PR to your branch as recommended by David.

**Comment by Martin-Grunewald** [comment]
What the hell? Why is this PR closed?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@arunhep 
Done, thanks a lot - testing

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
@arunhep @franzoni @Dr15Jones 
please check and sign.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by arunhep** [comment]
@Martin-Grunewald 
checking wf10024 : 2017 ttbar MC
many changes in different directories which are expected because of change of L1 and HLT menu.
could not understand this directory : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-07-24-1100+19503/21523/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/TrackerHitsV_TrackerHit.html
where for some of the distributions, reference had 0 entries and with new menu we got entries like here.
it needs more investigation.
@makortel @fioriNTU can you please help in getting more information about these quantities?

no change in data wf 136.731 as expected.
no change in wf 1001 which is express-like

**Comment by franzoni** [comment]
@arunhep 

there are indications for the 2017 Full sim that the simhits have changed 

(see for instance [HCAL](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-07-24-1100+19503/21523/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HcalHitsV_HcalSimHitsTask.html) and ECAL), a plausible consequence of the changes in `GeometryFileRcd/Extended` and  ( [see details of the tag changes between GT's](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v7/92X_upgrade2017_realistic_v8)  ) which are known to affect the reproducibility of the pseudo-random nunber sequence

The tracker related difference you report , @arunhep  , are largely in plots with ~1 entry where hits go from 0 to 1 or viceversa.

> no change in data wf 136.731 as expected.
> no change in wf 1001 which is express-like

Confirm the picture.

**Comment by franzoni** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Chris, please sign (for addOnTests.py)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
