### PR TITLE
Phase2-hgx346Z Modify the tester for parameter and a few scripts to test HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the tester for parameter and a few scripts to test HGCal geometry

#### PR validation:

Use the test code to dump parameters

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
