### PR TITLE
Tune snippets in 93x

### PR DESCRIPTION
**Pull request by perrozzi**
backport of #20319

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@smuzaffar - the back port ok flag didn't work here?

**Comment by smuzaffar** [comment]
@davidlange6 , i think issue was that the comment 'backport of ...' had the full url instead of #PR that is why cms-bot did not picked it up. I fixed the comment and now bot did its work. I will update the bot to recognize full PR url too

**Comment by perrozzi** [comment]
Hi, it seems like we might have a problem.
The snippet folder starts with a number and the line
`from Configuration.Generator.2017MCTunes.PythiaCP5Settings_cfi import *`
crashes in my tests...

**Comment by govoni** [comment]
If the case, I suggest MMXVII_MCTunes :-)

P

**Comment by perrozzi** [comment]
Sorry to disappoint you, I picked up MCTunes2017 (#20571, #20572)
:-)

**Pull request merged**
