### PR TITLE
Use hasattr to check process.DQMStore in ConfigBuilder.py (Fix of #28920)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR is a fix proposed by @makortel in https://github.com/cms-sw/cmssw/pull/28920#discussion_r393013181 to fix #28920

### CODE REVIEW

**Comment by silviodonato** [comment]
please test workflow 1002.0, 1370.17, 25215.18, 1361.181

**Comment by silviodonato** [comment]
cc: @schneiml

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Comment by schneiml** [comment]
thanks @silviodonato , @makortel for the quick fix!

**Pull request merged**
