### PR TITLE
Update L1T to l1t-tsg-v7-cand performance (81x)

### PR DESCRIPTION
**Pull request by mulhearn**
Brings L1T up-to-date with l1t-tsg-v7-cand.

Most notably, updates to Muon TF emulations that improve agreement with hardware, plus updates to BMTF and EMTF unpackers.  Minor updates to improve agreement in other modules.

This version has new large files removed (even from history).  It will not pass tests until external request 
https://github.com/cms-data/L1Trigger-L1TMuon/pull/5 is in the IB.  For testing, a PR with these data files added locally is here:  #14565.

### CODE REVIEW

**Comment by slava77** [comment]
since when is it OK to have code like L1Trigger/L1TMuonEndCap/interface/PhThLUT_Neighbor.h
in the release source

**Comment by mulhearn** [comment]
I don't have time to answer philosophical questions right now...

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
yea, we need to change PhThLUT_Neighbor.h into a simple header and a reader from an external data file...

**Comment by mulhearn** [comment]
It is going to be a proper CondFormat eventually, can't we please leave it as is until then?  This is already a temporary solution, I hate to implement yet another temporary solution: I'll never get to the proper fix.  Note that the more complicated part of the fix for EMTF conditions is already here:  319e3eb84e363345a97c8622029fcd2e0552bc9e

**Comment by davidlange6** [comment]
maybe we can reduce the size of this file by 4x by removing the whitespace? Still a disaster - in a class and changed to constexprs it could be less of a disaster.

**Comment by slava77** [comment]
temporary huge files still stay in git history pack files for a while after you delete them, until there is a rewrite of the history.

**Comment by mulhearn** [comment]
I'll just write a throw-away parser.  It will take a few hours tops.  But I sincerely think this is a poor optimization.  I'd rather just wait for my proper fix, which is already in works.  There are tons of huge files already in CMSSW:  they still enter even if they are not in final PR diff wrt head.  If that is a non-academic performance concern than we should write a filter that removes orphaned large files via git filter-tree or such.

**Comment by fwyzard** [comment]
{quote}since when is it OK to have code like L1Trigger/L1TMuonEndCap/interface/PhThLUT_Neighbor.h in the release source{quote}

Purely from a performance point of view, it's hard to beat a static array... in fact, we could use more of those and less runtime parsing. From a *maintenance* point of view, for tracking configuration changes, ensuring reproducibility of the online decisions, etc - I agree it's a bad solution,  but using a binary blob will be just as bad. If an EventSetup-based solution is already in the works, either you decide to delay the integration until that is available and validated, or we go ahead with this in the meantime.

If you are worried about the size of the blobs, that file compresses down to 4 kb, which is quite negligible.

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
argh - but that will fail - ok. sorry for the noise

**Comment by mulhearn** [comment]
Actually, it might even pass, but the results will be garbage...

**Pull request merged**
