### PR TITLE
Minigen 93x

### PR DESCRIPTION
**Pull request by perrozzi**
backport of #19853

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
seems unrelated, trying again

**Comment by perrozzi** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20485	0783294
- backport of the minigen PR already merged in 94X/master yesterday https://github.com/cms-sw/cmssw/pull/19853	3781f11. Code changes are identical (modulo one empty line change)
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
