### PR TITLE
GeneratorProducts: Changes required to compile with Apple Clang 9.1 strict enforcement 

### PR DESCRIPTION
**Pull request by gartung**
GeneratorProducts: Changes required to compile with Apple Clang 9.1 strict enforcement of c++17 std deprecated function removal.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by gartung** [comment]
The failure might be caused by a ROOT bug
[https://root-forum.cern.ch/t/dictionary-generation-for-std-unique-ptr-error-root-6-12-07/30716](url)

**Comment by gartung** [comment]
@Dr15Jones The error seems to be related to using std::move(std::unique_ptr)

 `Running script: /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100/src/GeneratorInterface/LHEInterface/test/testMerging.sh
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100/tmp/slc6_amd64_gcc700 /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100
18-Sep-2018 08:14:46 CEST  Initiating request to open LHE file file:/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100/src/GeneratorInterface/LHEInterface/test/ttbar.lhe
18-Sep-2018 08:14:46 CEST  Successfully opened LHE file file:/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100/src/GeneratorInterface/LHEInterface/test/ttbar.lhe
----- Begin Fatal Exception 18-Sep-2018 08:14:48 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Calling ProductRegistry::initializeLookupTables
Exception Message:
No data dictionary found for the following classes:

  __uniq_ptr_impl<gen::PdfInfo,default_delete<gen::PdfInfo> >
  default_delete<gen::PdfInfo>
  tuple<gen::PdfInfo*,default_delete<gen::PdfInfo> >
  unique_ptr<gen::PdfInfo,default_delete<gen::PdfInfo> >

Most likely each dictionary was never generated, but it may
be that it was generated in the wrong package. Please add
(or move) the specification '<class name="whatever"/>' to
the appropriate classes_def.xml file along with any other
information needed there. For example, if this class has any
transient members, you need to specify them in classes_def.xml.
Also include the class header in classes.h

A type listed above might or might not be the same as a
type stored in the Event (or Lumi or Run). Instead it might
be the type of a data member, base class, wrapped type, or
other object needed by a stored type. Below is some additional
information which lists the stored types associated with the
types whose dictionaries were not found:

  LHEEventProduct (read from input)

Missing dictionaries are associated with these branch names:

  LHEEventProduct_source__LHEFile.

If you do not need these branches and they are not produced
in the current process, an alternate solution to adding
dictionaries is to drop these branches on input using the
inputCommands parameter of the PoolSource.
----- End Fatal Exception -------------------------------------------------
Failure using /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-17-1100/src/GeneratorInterface/LHEInterface/test/testMerge_cfg.py: status 71
status = 18176

---> test TestGeneratorInterfaceLHEInterfaceFileReading had ERRORS
 
^^^^ End Test TestGeneratorInterfaceLHEInterfaceFileReading ^^^^`

**Comment by efeyazgan** [comment]
please test

**Comment by gartung** [comment]
This is broken until we get a patch from ROOT for dictionary generation for std::unique_ptr.

**Comment by gartung** [comment]
Note the change to classes_def.xml requires a patch for root 6.12.x so that unique_ptr is added to dictionary generation.
see https://sft.its.cern.ch/jira/browse/ROOT-9698 for the patch needed

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4387

**Comment by gartung** [comment]
hold
Waiting on backwards compatibility patch from Root.

**Comment by Dr15Jones** [comment]
hold
Looks like Patrick can't do the 'hold'

**Comment by fabiocos** [comment]
please test

**Comment by gartung** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Pull request closed without merging**
