### PR TITLE
uploadConditions: service can be chosen via metadata

### PR DESCRIPTION
**Pull request by franzoni**
- service can be chosen via metadata
- only impacts uploadConditions

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@smuzaffar the test seems stuck (actually there is nothing to test)

**Comment by franzoni** [comment]
will be soon superseeded by a similar PR with few more updates by @ggovi 

closing

**Pull request closed without merging**
