### PR TITLE
backport HLT DQM for menu v3.0 to CMSSW 9.2.x + HLTDQM : fix memory issue (part1) + add offlineHLTSourceOnAODextra sequence

### PR DESCRIPTION
**Pull request by mtosi**
many PRs for the HLT DQM did not enter 92x, yet 
because the corresponding ones in 93x showed a big issue in memory,
as reported in [1] and discussed during (and after) the DQM meeting

they are --mainly-- 
- #19961
- #19873
- #19888
- #20167
- #20166
- #20212

the memory issue seems --at least partially-- addressed by PR #20439 
here there is its backport in 92x, which should make the above PRs fine in 92x as well
this is the 1st --low level-- round, in which

1. I disable the tracking cumulative hit efficiency vs PU, lumi and BX almost everywhere
2. reduce the #bins in the JetMET directories
    - disabling some not really useful plots
       (like the 2D in the HEM and HEP slices, which are simply a zoom of the full eta-phi map)
    - reducing the bin width in the eta plot [from 50 to 20 bins (from 0.2 to 0.5 resolution) ]
       the best would be to move to variable binning
    - dropping plots vs LS done per partitions

in this occasion, I also clean / re-organize the directories structure
==> **the comparison plot by plot will fail**

[1]
in https://indico.cern.ch/event/658725/contributions/2685778/attachments/1505407/2345690/dqm_memory.pdf

finally (?), as discussed at the recent XC
it would be probably safer to have a dedicated `cms.Sequence` for testing new DQM code for HLT
which is meant to be used in the HLT validation workflow, but not necessarily at Tier0

new DQM code should be integrated in the offlineHLTSourceOnAODextra sequence
and then it could be ported in the standard offlineHLTSourceOnAOD one (which is run at Tier0)

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@Martin-Grunewald @silviodonato

**Comment by Martin-Grunewald** [comment]
What is/are the corresponding 94X PRs?

**Comment by mtosi** [comment]
memory issue handling: https://github.com/cms-sw/cmssw/pull/20439
offlineHLTSourceOnAODextra sequence https://github.com/cms-sw/cmssw/pull/20540

**Comment by Martin-Grunewald** [comment]
#20439 is not yet merged in 94, which needs to come first (before any 92X integration).

**Comment by Martin-Grunewald** [comment]
94X PRs are now integrated, DQM, please sign this 92X PR.

**Comment by Martin-Grunewald** [comment]
@dmitrijus

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mtosi 
Comment from ORP:
Issues are the impact on tier0 memory. can we estimate? what PDs and increased RSS (assuming 8 cores)

**Comment by mtosi** [comment]
@Martin-Grunewald 
what I did, following the recommendations and instructions I received by DQM core, 
is evaluating the impact in terms of size of the DQM file

I do not know how to check / estimate the impact as 
"what PDs and increased RSS (assuming 8 cores)"

if anybody ( @fwyzard @davidlange6 ) gives me clear instructions, I will do it
(even if it is not clear to me if such task really belongs to the STEAM group, and myself in particular)

**Comment by fwyzard** [comment]
@davidlange6 can you give clear instructions on what is needed to have this PR integrated ?

As far as I have understood, the memory usage has been reduced with respect to the original implementation; whether or not it can fit in the Tier-0 workflows is not something that we can evaluate, since it is apparently impossible to find instructions to reproduce those workflows in the first place.

If there are specific issues, please point them out.
Otherwise please merge the PR.

**Comment by fwyzard** [comment]
@dmitrijus maeshima@fnal.gov can you please follow up on this as well ?

**Comment by davidlange6** [comment]
Yes - i asked exactly that in the ORP - what is the increase in memory in each Tier0 workflow. the DQM group (who I gather knows how the DQM is configured for the Tier0) said they would summarize.

**Comment by mtosi** [comment]
ciao
any news on this ?
can we please proceed w/ the integration ?
we have other developments in queue ...

thanks

**Comment by mtosi** [comment]
@fwyzard @Martin-Grunewald @davidlange6 @dmitrijus

**Comment by davidlange6** [comment]
I have no news, no

**Comment by mtosi** [comment]
the second "no" refers to the possibility of merging this PR ?

**Comment by davidlange6** [comment]
no - I mean that I have not gotten any answer from DQM on this topic (which indeed is needed before going further)

**Comment by mtosi** [comment]
speechless :(

**Comment by mtosi** [comment]
just fixed a conflict which was spotted by the system

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
as state in the last commit
@dmitrijus @davidlange6 @fwyzard 
I'm expecting some help/push in having the new HLT plots run on tier0 as well !!!!!

otherwise, "mi sento presa un po' per il culo"

in addition, PdmV ( @fabozzi ) will need to update the relval matrix (sorry for this)

**Comment by mtosi** [comment]
if any of you have any suggestions, they are really welcome, of course
possibly in the timeline of few weeks, because then I'll start my maternity leave ...

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@davidlange6 @dmitrijus @fwyzard @fabozzi 

because we saw some "friction" in integrating this PR, 
mainly because it seems that tier0 is not able to digest the extra memory (!?!??!!?)
we decide to put the new plots in the dedicated sequence meant to *not* be run at tier0,
but only by the validation workflows
(to be noticed that this is not the case in 94x)

I --really-- hope this is fine

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
I've just prepared the PR for 94x [1]
w/ the last "feature" of disabling plots for helping @tier0
as requested at the Join Opt Meeting [2]

I'm expecting this PR to be integrated soon, right ?

[1]
https://github.com/cms-sw/cmssw/pull/20980

[2]
https://docs.google.com/document/d/1lG7r2OCBWz7dVl7aaUczNT4DvGQJlmOy-ciS2lBhZvw/edit#heading=h.7oamqr4y3fpf

**Comment by mtosi** [comment]
@davidlange6 @fwyzard @dmitrijus

**Comment by dmitrijus** [comment]
Hi all, I finally managed to make some tests here, sorry for the delay.

I have picked up a random sequence with a description made the most sense to me (136.78)
and then simply replaced the DQM sequence in with "common".
The release is 9_2_13. Stats done by `dqmMemoryStats.py -d 1 -x --summary -i step3_inDQM.root`

```
base (@common, before PR):
52.23 MiB        AlCaReco
21.89 MiB        PixelPhase1
18.82 MiB        L1T
17.77 MiB        HLT
15.16 MiB        Tracking
Total bytes: 153.20 MiB

after (@common, after merging this PR):
52.23 MiB        AlCaReco
21.89 MiB        PixelPhase1
18.82 MiB        L1T
15.16 MiB        Tracking
14.83 MiB        HLT
Total bytes: 150.52 MiB
```

To test other sequences, muon, hcal, I use "allForPrompt" shortcut, which includes common and several others.

```
base (@allForPrompt, before PR):
52.23 MiB        AlCaReco
21.89 MiB        PixelPhase1
18.82 MiB        L1T
17.77 MiB        HLT
15.16 MiB        Tracking
Total bytes: 189.68 MiB

after (@allForPrompt, after merging this PR):
52.23 MiB        AlCaReco
21.89 MiB        PixelPhase1
18.82 MiB        L1T
15.16 MiB        Tracking
14.83 MiB        HLT
Total bytes: 186.74 MiB
```

Please ignore the first AlCa result, they use their own sequence (ALCA). I did not touch it and left as is. It might be something which is extra to this workflow. I will ask AlCa about it.

This PR should be merged. As far as I see, there's a small, but a definite improvement.
In the meantime, I will go poke the 3 other offenders on this list.

For "standardDQM" sequence, HLT change is 77.43 MiB -> 46.62 MiB.

Have a nice weekend all.

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
image

image

image

taking DQMIO files from tier0 for run 305044 [1]
python DQMServices/FileIO/scripts/dqmMemoryStats.py -x -d 1 --summary -i run305044_SingleMuon.root
********************************************************************************
************************* DQM level 1 folder breakdown *************************
* Size cutoff: 512.00 KiB                                                      *
********************************************************************************
67.54 MiB        AlCaReco
21.89 MiB        PixelPhase1
18.82 MiB        L1T
17.77 MiB        HLT
15.16 MiB        Tracking
12.94 MiB        L1TEMU
10.93 MiB        SiStrip
6.56 MiB         ZCounting
5.01 MiB         RPC
4.83 MiB         CSC
4.14 MiB         Muons
1.70 MiB         RecoTauV
1.60 MiB         Physics
1.14 MiB         DT
Total bytes: 190.71 MiB

python DQMServices/FileIO/scripts/dqmMemoryStats.py -x -d 1 --summary -i run305044_ZeroBias.root
********************************************************************************
************************* DQM level 1 folder breakdown *************************
* Size cutoff: 512.00 KiB                                                      *
********************************************************************************
52.23 MiB        AlCaReco
41.30 MiB        Tracking
21.89 MiB        PixelPhase1
18.82 MiB        L1T
17.77 MiB        HLT
12.94 MiB        L1TEMU
10.99 MiB        SiStrip
6.99 MiB         EcalBarrel
6.44 MiB         Hcal
5.04 MiB         EcalEndcap
5.01 MiB         RPC
4.83 MiB         CSC
4.14 MiB         Muons
1.70 MiB         RecoTauV
1.60 MiB         Physics
1.14 MiB         DT

python DQMServices/FileIO/scripts/dqmMemoryStats.py -x -d 1 --summary -i run305044_SingleElectron.root
********************************************************************************
************************* DQM level 1 folder breakdown *************************
* Size cutoff: 512.00 KiB                                                      *
********************************************************************************
21.89 MiB        PixelPhase1
18.82 MiB        L1T
17.77 MiB        HLT
15.16 MiB        Tracking
12.94 MiB        L1TEMU
10.93 MiB        SiStrip
6.99 MiB         EcalBarrel
5.67 MiB         Egamma
5.04 MiB         EcalEndcap
1.70 MiB         RecoTauV
1.60 MiB         Physics

[1]
run305044_ZeroBias.root -> /eos/cms/tier0/store/data/Run2017F/ZeroBias/DQMIO/PromptReco-v1/000/305/044/00000/76C61B7C-1CB2-E711-B603-02163E01382E.root

run305044_SingleMuon.root -> /eos/cms/tier0/store/data/Run2017F/SingleMuon/DQMIO/PromptReco-v1/000/305/044/00000/986BE0C1-27B2-E711-9859-02163E01A1B9.root

run305044_SingleElectron.root -> /eos/cms/tier0/store/data/Run2017F/SingleElectron/DQMIO/PromptReco-v1/000/305/044/00000/427D40FB-3BB2-E711-B816-02163E01372F.root

**Comment by mtosi** [comment]
for completeness, the memory usage w/ all HLT plots enable is roughly 60MB .....
which is roughly 1/3 of the total

is it too much ?
I do not think so, we can for sure try to squeeze it further, 
but that is the order of magnitude for monitoring 500 paths

==> the mentioned work on the DQM framework is really important, I guess

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
some fixes to be discussed for 94x once I write my suggestions up - but ok for 92x.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
