### PR TITLE
Calo Layer 2 Update HI offline config *10_3_X backport*

### PR DESCRIPTION
**Pull request by bundocka**
Update to offline caloParams file for HI
Bugfix for conversion script
Added 1 line bugfix to MET PUS

Backport of #25205

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @bundocka 
Are the failing histograms for the taus expected/unrelated?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-11-15-2300+25206/29425/validateJR.html

**Comment by bundocka** [comment]
There are no changes that should affect taus here, the update to the HI caloParams isn't used in any standard WFs.

**Comment by thomreis** [comment]
+1

failing comparisons are unrelated

**Comment by fabiocos** [comment]
+1

**Pull request merged**
