### PR TITLE
Fixing code of tau embedding (TauAnalysis/MCEmbeddingTools) for run2 needs part2

### PR DESCRIPTION
**Pull request by swayand**
This PR contains only the cleanup of the old embedding code as it was requested in the original PR:

https://github.com/cms-sw/cmssw/pull/16271

Two files need updates to keep it compile and compatible to initial PR. So please comment there.

### CODE REVIEW

**Comment by slava77** [comment]
On 11/1/16 4:48 PM, swayand wrote:
> This PR contains only the cleanup of the old embedding code as it was
> requested in the original PR:
> 
> #16271 <https://github.com/cms-sw/cmssw/pull/16271>
> 
> Two files need updates to keep it compile and compatible to initial PR.
> So please comment there.
> 

Do you mean that this PR would not compile as is?
If so, it will stay on hold until 16271 is ready and merged.

**Comment by swayand** [comment]
Sorry it means with the few files which are edited (with the same changes as in the https://github.com/cms-sw/cmssw/pull/16271 ) it compiles.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
