### PR TITLE
[Backport] Modify CaloLayer1 DQM for 5BX needed for Ecal

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:

Modifications are made to add DQM CaloLayer1 monitoring elements for 5BX, which are needed for ECAL: two 5-bin 1D plots for TPs averages vs BX (with or without Et-weighted), and five 2D TPs occupancy plots. Unpacker is modified to point to the proper sample when filling the 5BX histograms (the middle BX is the "standard").

#### PR validation:

For testing, the unpacker is modified to fill 5 times the EcalDigisBx for 5BX inside the "if(N_BX==1)" since now we always get BX=1, so the 5BX histograms can get filled for testing (this modification is for our own testing purpose so is not included in this PR). The codes can be compiled and are tested with an offline DQM workflow "runTheMatrix.py -l 10823.0", the 5BX histograms show up in the DQM root files and are properly filled.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #33510 to 11_3_X needed for MWGR.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@hftsoi Any idea why the added histograms appear empty for all workflows?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-06-09-2300+a198c8/43380/dqm-histo-comparison-summary.html

**Comment by hftsoi** [comment]
> @hftsoi Any idea why the added histograms appear empty for all workflows?
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-06-09-2300+a198c8/43380/dqm-histo-comparison-summary.html

@jfernan2 As I understood this is expected since the firmware is still under test and does not have the correct packing with respect to the unpacker for 5BX (in the unpacker file it's getting N_BX==1 instead of N_BX==5). I've done a local test by filling for N_BX==1 and the plots are looking fine.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
