### PR TITLE
[11_3_X] Protect storage accounting UDP messages from NaN, and Use StatisticsSenderService for all framework files

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a combined backport of #35362 and #35505, following requests in #29412 and #36349. Includes also #36379 and #36403 as further fix and cleanup.

#### PR validation:

Unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
backport

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
hold

**Comment by makortel** [comment]
Now including #36379 and #36403 too.

**Comment by makortel** [comment]
unhold

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
