### PR TITLE
Drop-box metadata management: updates and introduce AAG, BSHP, EcalPed

### PR DESCRIPTION
**Pull request by franzoni**
Updating the tools used to construct DropBoxMetadata payloads,
as explained here: https://twiki.cern.ch/twiki/bin/view/CMS/AlCaDBPCL#Drop_box_metadata_management

Specifically:
. introduce comments in the tools
. update existing workflows to the content of https://cms-conddb.cern.ch/cmsDbBrowser/search/Prod/f422b9d9589e65175b255acc01700f9103842a6e
. add the AAG workflow with the same content as AfterAbortGap
. modify the destination of the geometry objects produced by the pixelAli PCL workflow, as agreed with the tracker DPG
. introduce metadata for BeamstpoHP and EcalPEdestals (soon to be included in the PCL)

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
no changes to 10024.0_TTbar_13 136.731_RunSinglePh2016B
as expected since no changes included in the standard sequences

**Comment by franzoni** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
