### PR TITLE
add hltTracksMerged monitoring (both DQM and Validation)

### PR DESCRIPTION
**Pull request by mtosi**
back-port of https://github.com/cms-sw/cmssw/pull/19591

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by JanFSchulte** [comment]
The HLT menu introducing this new track collection will go online on Monday (hopefully). So it would be good if this could be merged quickly.

**Comment by Martin-Grunewald** [comment]
backport of #19591

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test
(tests are too old to see why this adds 1000 lines of printout)

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Hi,

Could you please have a look at the reporting of the above addOnTests error? The above message is not very helpful in indicating which of the addOnTests has failed - this used to be indicated in the past.
Also, as before, running all addOntests in my area I do not find any error.

**Comment by smuzaffar** [comment]
@Martin-Grunewald , looking athttps://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19594/21600/addOnTests.log , I see that it is not complete which means the addOnTests were timed out after 1.5 hours. This test ran on a large machine (24 cores and 48GB ram) so I guess there was some slowness in reading/accessing data.

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Since this seems to happens more often lately, could you please perhaps increase the timeout to 2 h?

**Comment by davidlange6** [comment]
1.5*24 cpus is already too much for PR tests

**Comment by davidlange6** [comment]
its odd as all the timestamps I see are within 15 minutes.. there is this crash - is it then hanging - perhaps the add-on test scripts need some better exit code and time to process reporting?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19594/21600/addOnTests/hlt_data_PRef/cmsDriver.py_RelVal_-s_HLT:PRef,RAW2DIGI,L1Reco,RECO_--data_--scenario=pp_-n_10_--conditions_auto:run2_data_PRef_--relval_9000,50_--datatier_RAW-HLT-.log

**Comment by Martin-Grunewald** [comment]
The full machine for one PR - or shared with other PR tests?

**Comment by Martin-Grunewald** [comment]
I do not buy that stack trace as a run-time error, as I can not reproduce it offline. I rather think this is the stack trace due to the external signal cutting when the time goes above 1.5h.

**Comment by davidlange6** [comment]
1 machine 1.5 hours 24 cores for add-on tests of one PR. Then of course there are the other tests run for each PR in addition, but those are separate and in addition to the 36 core hours here....

**Comment by Martin-Grunewald** [comment]
Hmm ok - but are all cpus fully used? Ie, how many addOnTests are done in parallel? It can be at most
21 - the number of addOnTests, and some are much shorter than others. The steps within a single addOn test can not be parallelised as they need to run sequential - output of one feeding input of next.

**Comment by smuzaffar** [comment]
@Martin-Grunewald , when a PR test starts then it occupy full machine. We run N parallel jobs where N is cores available on that machine.

**Comment by davidlange6** [comment]
it might be. as indeed this job ran for >1 hour on 4 cores.. seems like the problem.

**Comment by davidlange6** [comment]
hi @smuzaffar - the addontests seem to have their own choice of ncores=4. You might want to reduce the N parallel jobs to N/4 if you can. (its not the issue causing the problems however)

**Comment by smuzaffar** [comment]
@davidlange6 , if you are referring to https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/addOnTests.py#L265 then do not worry about that as we run ```addOnTests.py -j N```
and I do not think each addOn job run in threaded mode so we should be fine by running N jobs.

**Comment by davidlange6** [comment]
> On Jul 19, 2017, at 3:23 PM, Malik Shahzad Muzaffar <notifications@github.com> wrote:
> 
> @davidlange6 , if you are referring to https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/addOnTests.py#L265 then do not worry about that as we run addOnTests.py -j N
> and I do not think each addOn job run in threaded mode so we should be fine by running N jobs.
> 

from looking through the logs, most are running 4 threads... (maybe all)

**Comment by smuzaffar** [comment]
@davidlange6 , I see that now.
I do not think all release cycles use 4 threads for addOn tests so just blindly running N/4 process will under utilize the resources.

**Comment by davidlange6** [comment]
true - yes... anyway, its not really a problem here I think.

**Comment by davidlange6** [comment]
merge

**Comment by JanFSchulte** [comment]
Thanks for merging this! One question: When do we plan to have a new 9_2_X release? Without this PR, we are not able to monitor the HLT tracking in the data we are taking right now.

**Pull request merged**
