### PR TITLE
Switch HLT menus for 110X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

The PR let's the existing HLT key @relval2018 point to the Fake2 menu (instead of GRun) for relvals, and adds and uses the new HLT key @relval2021 pointing to the GRun menu in 2021 Run-3 relvals.

#### PR validation:

TSG tests and short matrix tests all pass

#### if this PR is a backport please specify the original PR:

Not a backport, CMSSW_11 only, no backport to 10_6 or earlier foreseen.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by prebello** [comment]
@Martin-Grunewald could you please let us know about proper HLT menu for Run-3/2023 and 2024 relvals (to be validated soon)?

**Comment by prebello** [comment]
please test

**Comment by prebello** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@prebello, @zhenhu, @kpedro88, @pgunnell, can you please check and sign?
Thanks!

**Comment by kpedro88** [comment]
I am concerned about this:
> You potentially added 647 lines to the logs

According to the detailed comparisons, it comes from here:
> You added 452 to /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/JR-comparison/PR-31f27a/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step4_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25.log

There are a lot of messages in [that log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-31f27a/1142/runTheMatrix-results/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step4_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25.log) about HLT modules. These should be checked to ensure there are no regressions.

**Comment by Martin-Grunewald** [comment]
@kpedro88 
This is expected in 2018 workflows as there is now only a stripped-down HLT menu used which runs only a few basic paths, so many hlt modules from advanced HLT paths are simply not included.

**Comment by kpedro88** [comment]
@Martin-Grunewald what is the purpose of this change? Will we just have this slew of messages printed in 2018 workflows forever?

**Comment by Martin-Grunewald** [comment]
@kpedro88 

Date: Thu, 20 Jun 2019 09:47:41
From: Martin Gruenewald <Martin.Grunewald@cern.ch>
To: Norraphat Srimanobhas <srimanob@mail.cern.ch>,
    Giovanni Franzoni <giovanni.franzoni@cern.ch>,
    Fabio Cossutti <fabio.cossutti@cern.ch>,
    Simone Gennai <Simone.Gennai@cern.ch>, Marco.Pieri@cern.ch
Subject: HLT menu changes in CMSSW_11 and relvals

Dear colleagues

TSG would like to make the following changes in CMSSW_11 ONLY
(ie, NO changes for CMSSW_10_6 [such as UL] or earlier):

HLT menu for the 2018 relval workflows: currently HLT:@relval2018
points to HLT:GRun, which is the 2018 pp menu migrated to
CMSSW_11. We would like to change HLT:@relval2018 (defined in
Configuration/HLT) to point to HLT:Fake2 (the same what we did
over a year ago with @relval2017): HLT:Fake2 is a very basic
placeholder HLT menu with just a few dummy HLT paths.

HLT:GRun will change to incorporate Run-3 developments in CMSSW_11.

For the Run-3/2021 relval workflows, we will add a key
HLT:@relval2021 to point to the HLT pp menu migrated from the
2018 pp menu but including current and future Run3 developments.
We add the @relval2021 key as usual in Configuration/HLT, and
would like to have all Run-3 relvals to use HLT:@relval2021,
rather than currently HLT:Fake2. 
How can one identify the Run3 relvals to make this change of HLT
menu? Do you have separate relvals for the Run-3 years
20201/2022/2023?

Please let us know.

Thanks and best regards

Martin

**Comment by Martin-Grunewald** [comment]
It simply means DQM and whoever should move to 2021 workflows.
We can not keep 2018 in CMSSW_11.

**Comment by kpedro88** [comment]
@Martin-Grunewald thanks, this is what I was looking for:
> HLT:GRun will change to incorporate Run-3 developments in CMSSW_11.

Can you post an issue reminding us to move the PR tests etc. to 2021 workflows?

**Comment by davidlange6** [comment]
surely we will want to continue running 2018 (and earlier) workflows in 11x... But right, the usual fake hlt menu that can be integrated in workflows once dqm et al adjusts to it.

**Comment by kpedro88** [comment]
+upgrade

**Comment by Martin-Grunewald** [comment]
@kpedro88 

Issue created here: https://github.com/cms-sw/cmssw/issues/27372

**Comment by fabiocos** [comment]
As you may see by comparing the output of step3 of 136.85, there are a few DQM modules firing systematically because of missing input collections:
```
=============================================                                           =============================================

MessageLogger Summary                                                                   MessageLogger Summary

 type     category        sev    module        subroutine        count    total          type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----          ---- -------------------- -- ---------------- ----------------  -----    -----
    1 Configuration        -w HLTHighLevel:ALC                       2        2             1 Configuration        -w HLTHighLevel:ALC                       2        2
    2 EMTF                 -w L1TRawToDigi:emt                       2        2             2 EMTF                 -w L1TRawToDigi:emt                       2        2
    3 EcalDQM              -w EcalDQMonitorTas                     100      100             3 EcalDQM              -w EcalDQMonitorTas                     100      100
    4 L1T                  -w L1TRawToDigi:emt                       2        2             4 L1T                  -w L1TRawToDigi:emt                       2        2
    5 PrimaryVertexMonitor -w PrimaryVertexMon                     100      100       |     5 SiPixelPhase1TrackCl -w SiPixelPhase1Tra                     100      100
    6 PrimaryVertexMonitor -w PrimaryVertexMon                     100      100       |     6 HLTConfigProvider    -e DQMPFCandidateAn                       2        2
    7 PrimaryVertexMonitor -w PrimaryVertexMon                     100      100       |     7 HLTConfigProvider    -e METAnalyzer:pfMe                       2        2
    8 SiPixelPhase1TrackCl -w SiPixelPhase1Tra                     100      100       |     8 HLTConfigProvider    -e METAnalyzer:pfPu                       2        2
    9 HLTConfigProvider    -e DQMPFCandidateAn                       2        2       |     9 HLTPrescaleProvider  -e PATTriggerProduc                       2        2
   10 HLTConfigProvider    -e METAnalyzer:pfMe                       2        2       |    10 hltPrescaleTable     -e PATTriggerProduc                       1        1
   11 HLTConfigProvider    -e METAnalyzer:pfPu                       2        2       |    11 fileAction           -s file_close                             1        1
   12 SiStripMonitorTrack  -e SiStripMonitorTr                     100      100       |    12 fileAction           -s file_open                              2        2
   13 TrackRefitter        -e TrackRefitter:hl                     100      100       <
   14 hltPrescaleTable     -e PATTriggerProduc                       1        1       <
   15 fileAction           -s file_close                             1        1       <
   16 fileAction           -s file_open                              2        2       <
```

in particular the PrimaryVertexMonitor. 
The change in event content is due for step2 (based on FEVTDEBUGHLT) to the different menu, and for step3 I assume to some modules not run with the simplified menu:
```
16:13 cmsdev25 1163> diff -b CMSSW_11_0_X_2019-06-26-2300/work/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/cont3 std/CMSSW_11_0_X_2019-06-26-2300/work/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/cont3 
5a6
> FEDRawDataCollection                  "hltFEDSelectorL1"          ""                "reHLT"    
6a8,13
> double                                "hltScoutingCaloPacker"     "caloMetPhi"      "reHLT"    
> double                                "hltScoutingCaloPacker"     "caloMetPt"       "reHLT"    
> double                                "hltScoutingPFPacker"       "pfMetPhi"        "reHLT"    
> double                                "hltScoutingPFPacker"       "pfMetPt"         "reHLT"    
> double                                "hltScoutingCaloPacker"     "rho"             "reHLT"    
> double                                "hltScoutingPFPacker"       "rho"             "reHLT"    
8a16,27
> vector<ScoutingCaloJet>               "hltScoutingCaloPacker"     ""                "reHLT"    
> vector<ScoutingElectron>              "hltScoutingEgammaPacker"   ""                "reHLT"    
> vector<ScoutingMuon>                  "hltScoutingMuonPacker"     ""                "reHLT"    
> vector<ScoutingMuon>                  "hltScoutingMuonPackerCalo"   ""                "reHLT"    
> vector<ScoutingPFJet>                 "hltScoutingPFPacker"       ""                "reHLT"    
> vector<ScoutingParticle>              "hltScoutingPFPacker"       ""                "reHLT"    
> vector<ScoutingPhoton>                "hltScoutingEgammaPacker"   ""                "reHLT"    
> vector<ScoutingTrack>                 "hltScoutingTrackPacker"    ""                "reHLT"    
> vector<ScoutingVertex>                "hltScoutingMuonPacker"     "displacedVtx"    "reHLT"    
> vector<ScoutingVertex>                "hltScoutingMuonPackerCalo"   "displacedVtx"    "reHLT"    
> vector<ScoutingVertex>                "hltScoutingPrimaryVertexPacker"   "primaryVtx"      "reHLT"    
> vector<ScoutingVertex>                "hltScoutingPrimaryVertexPackerCaloMuon"   "primaryVtx"      "reHLT"    
```

**Comment by fabiocos** [comment]
@prebello @pgunnell what are the PdmV plans wrt to this PR and adapting test workflows to 2021?

**Comment by prebello** [comment]
@fabiocos Run3 relvals have been prepared on 10-6-1 for the MC production and soon in 11-0-0-pre2 (postponed because of 10-6-1 urgency). which sort of test wfs do you mean? 

@Martin-Grunewald in pre2 we have used 'relval2018' : 'GRun' then, by changing it to Fake2, would we expect any change for DQM modules that could interfere in DQMIO? 
How will HLT validate 11-0-X pre releases based on the Fake menu in 2018 relvals (or HLT will not validate 2018 relvals anymore?) 
I would follow the @davidlange6 suggestion.

**Comment by Martin-Grunewald** [comment]
@prebello @fabiocos
I am not an expert in DQM nor DQMIO. HLT validation in CMSSW_11 must switch to using 2021 workflows as mentioned here: https://github.com/cms-sw/cmssw/issues/27372. (No backport to CMSSW_10 etc., so there things are unchanged re HLT.)
This is nothing else than we did about a year(?) ago when @relval2017 was moved from GRun to Fake2. Anything other than HLT will of course still work in CMSSW_11 and 2018. HLT as used in data taking of one year, however, was never kept alive in (much) later releases, as that would simply be impossible (code changes nor preserving the old behaviour, maintenance person power, etc.)
So I am afraid we need to bite this bullet and get on with it.

**Comment by fabiocos** [comment]
@prebello @Martin-Grunewald in my understanding the corresponding update last year was simply done in http://github.com/cms-sw/cmssw/pull/21815 without any action on the DQM sequence. And this is likely why we have tests on previous years plenty of warning messages. 

Concerning DQM @jfernan2 @andrius-k @schneiml @fioriNTU : I think we should envisage to use a simplified HLT DQM sequence for tests on past samples with a Fake2 menu. What I expect will happen in pre3 when we merge this PR is to get a slightly different event selection for tests were reHLT  is done (e.g. 136.85) and therefore some changes in the output of tests. Anyway the UL and Run3 validations are being performed primarily in 10_6_X, so I do not think this is a major problem. Still we should try to avoid running useless tests. But this can be handled in a different PR (although I would like it quite soon).

**Comment by prebello** [comment]
+1

ok @fabiocos @Martin-Grunewald no problem from PdmV side

**Comment by fabiocos** [comment]
+1

**Pull request merged**
