### PR TITLE
RivetInterface updates

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Framework improvements:
* Support concurrent LumiBlocks, as discussed in https://github.com/cms-sw/cmssw/issues/41957
* Remove SharedRessources requirement -> Rivet, HTXS, and ParticleLevelProducer can run in parallel now. See https://gitlab.com/hepcedar/rivet/-/issues/84 for Rivet thread-safety, may be converted to `stream` modules later.
* Removed obsolete DQM code (mostly commented out anyway already)
* Adapted GenEventInfoProduct ioread to process Run1 samples

Rivet improvements:
* Assign generic LHE weight names if they are not stored in the edm file (necessary for example [here](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FTTJets_TuneCP5_13TeV-madgraphMLM-pythia8%2FRunIIFall18wmLHEGS-102X_upgrade2018_realistic_v11-v1%2FLHE&instance=prod/global))
* Allow option to ignore beam requirements (needed for some Higgs samples)

#### PR validation:

Ran test job on 10 streams over 1000 ttbar events using 
```
cms.Path(process.mergedGenParticles*process.genParticles2HepMC*process.particleLevel*process.rivetProducerHTXS*process.rivetAnalyzer)
```

(also included in NanoAod workflows, except rivetAnalyzer)

### CODE REVIEW

**Comment by menglu21** [comment]
please test

**Comment by menglu21** [comment]
please test

**Comment by menglu21** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
