### PR TITLE
Update the ADC->fC table, simplify the charge reconstruction algorithm

### PR DESCRIPTION
**Pull request by deguio**
backport of #22974

@jkunkle @mariadalfonso

### CODE REVIEW

**Comment by perrotta** [comment]
@deguio @jkunkle @mariadalfonso

Is this backport to 10_1_X still needed/requested? (Also considering that the PR in the master still has to be merged and validated in RelVals before any backport can be taken into account, and the expected date for the release of 10_2_0 is not that far away)

If so, please update and put it in synchro with the version in the master.

If not, then you can probably close this pull request

**Comment by deguio** [comment]
hi @perrotta 
I think it still makes sense to include this PR in 10_1_x so that we can start using it before 10_2 is deployed.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #22974, merged in the master since May 26
- Enable the HCAL laser monitoring (plus some tuning of the laser MET filter, and some code cleaning)
- It potentially affects real data runs with HCAL laser on
- No effect is visible on usual MC and data workflows, but the expected behavior of the filter had been confirmed during the review of the version submitted in the master by running it on commissioning data taken with the laser firing

**Comment by fabiocos** [comment]
@perrotta @deguio I understand that this PR is back-ward compatible as far as the MC physics content is concerned, and it affects the laser monitoring during data taking only, please correct me if this is not true

**Comment by perrotta** [comment]
@fabiocos : it affects the HcalNoiseInfoProducer, which fills the HcalNoiseSummary and feeds the MET filters. The test outputs show no effect on standard samples whenever the HCAL laser is off; however I don't see any explicit shield that avoids it being propagated also to the MC output. The laser filtering threshold was also increased (from 1000 to 5000).

@deguio may comment whether possible large stat tests done in the DPG showed any tiny effect even in other cases, in particular in MC.

**Comment by deguio** [comment]
hi @perrotta 
the laserMon system is something that exists only at p5 and the corresponding channels do not exist in MC. so I would expect the totalLaserMon charge to be -1 accordingly to:
https://github.com/deguio/cmssw/blob/ea810fb98d32301e7c5426d68cb312bce36408c0/RecoMET/METProducers/src/HcalNoiseInfoProducer.cc#L761

does this answer your question?

**Comment by deguio** [comment]
two commits pushed to add PR #23597 as well to the 10_1_x queue

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Since previous reco signature in #23637: [muon] updated mva weights and tuned the default values (SK), the last update jusr add the content of PR #23597 to this backport
- Therefore this PR implements the overall backport of #23597 and #22974 from the master to 10_1_X

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
