### PR TITLE
Esmaeel dqm2016 stage2

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by EsmaeelEskandari** [comment]
I want to make the mGMT and Calo DQM modules to work with online production.
This is my fisrt time and I don't know the following cfg file works or not i.e.
DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py
Would you please take a look at this cfg file and guide me for any missing part?

**Comment by EsmaeelEskandari** [comment]
People need the Calo and uGMT DQM for online production of MWGR2 this Wednesday.

**Comment by EsmaeelEskandari** [comment]
Sorry I made a mistake. MWGR2 is on 24-26 Feb.
Anyway please guide me about the cfg file.
Is there any other file to be modified to make DQM Calo and mGMT work with online production?

**Comment by deguio** [comment]
please test
will have a look. but for a complete testing I believe you will need to have some real data with the stage2 l1t running.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @EsmaeelEskandari 
I think the changes are fine. we could have the stage2 code tested for real once we switch to 80x in preparation for MWGR2.
only one comment. do you mind cleaning up the config l1tstage2_dqm_sourceclient-live_cfg.py
it looks messy right now. please remove the commented lines.

thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi @EsmaeelEskandari 
It seems this PR is causing the following problem when processing real data:
```
 ################################################################### 
 # WARNING: this module is deprecated.                             # 
 # Please use CondCore.CondDB.CondDB_cfi.py                        # 
 ################################################################### 
L1TRawToDigi Sequence configured for Stage-1 (2015) trigger. 
L1TReco Sequence configured for Stage-1 (2015) trigger. 
WARNING:  L1Trigger/L1TCommon/python/caloStage1LegacyFormatDigis_cfi.py has been deprecated...
WARNING:  please use L1Trigger/L1TCalorimeter/python/caloStage1LegacyFormatDigis_cfi.py
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
16-Feb-2016 15:24:45 CET  Initiating request to open file file:RelVal_HLT_GRun_DATA.root
16-Feb-2016 15:24:46 CET  Successfully opened file file:RelVal_HLT_GRun_DATA.root
disableME1a = 0
%MSG-e TkDetLayers:   ConversionTrackCandidateProducer:conversionTrackCandidates@streamBeginRun  16-Feb-2016 15:25:10 CET Run: 256677
 ForwardDiskSectorBuilderFromDet: Trying to build Petal Wedge from Dets at different z positions !! Delta_z = 0.800217
%MSG
Begin processing the 1st record. Run 256677, Event 397024298, LumiSection 380 at 16-Feb-2016 15:25:15.621 CET
----- Begin Fatal Exception 16-Feb-2016 15:25:26 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 256677 lumi: 380 event: 397024298
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module L1TCaloRCTToUpgradeConverter/'valRctUpgradeFormatDigis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<L1CaloEmCand>
Looking for module label: gctDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Could you please have a look?

This is a cmsDriver generated workflow:
```
# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: RelVal --step=RAW2DIGI,L1Reco,RECO,DQM --conditions=auto:run2_data_GRun --filein=file:RelVal_HLT_GRun_DATA.root --custom_conditions= --fileout=RelVal_RECO_GRun_DATA.root --number=100 --data --no_exec --datatier SIM-RAW-HLT-RECO --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.Base --era=Run2_25ns --customise= --scenario=pp --python_filename=RelVal_RECO_GRun_DATA.py --processName=RECO1
```

**Comment by Martin-Grunewald** [comment]
@EsmaeelEskandari 
never mind... (false alarm)

**Pull request merged**
