### PR TITLE
Adding DQM plots for Calo CSV paths

### PR DESCRIPTION
**Pull request by HeinerTholen**
Adding DQM plots for Calo CSV HLT paths, as mentioned in #22647 .

Here's the last presentation on the topic:
https://indico.cern.ch/event/700252/#3-trigger-dqm-update

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
