### PR TITLE
CTPPS Pixel DQM: protection against RP ID corruption

### PR DESCRIPTION
**Pull request by popovvp**

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@popovvp where is the effect of this fix supposed to be seen? Could you please explain the problem?
I understand that the status arrays were incorrectly sized.

**Comment by popovvp** [comment]
status array's size were set correctly as we can have only 6 RP. But length of RP number is 3 bits, so in case of data corruption incorrect number 7 and 8  can be produced.

**Comment by fabiocos** [comment]
@popovvp ok, thanks, I understand that this protection is sufficient for the problems observed so far

**Comment by fabiocos** [comment]
+1

**Pull request merged**
