### PR TITLE
Code format to avoid recursive formatting

### PR DESCRIPTION
**Pull request by smuzaffar**
There are some extra characters in comments which confuses clang-format and clang-format keeps on suggesting changes. https://github.com/cms-sw/cmssw/commit/3f1e190d840203f218aaf98251d32d00e4e4d339 fixes these.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fabiocos , can we get this in ? Most of the changes are in comments (cleaning up tabs and extra lines) 
https://github.com/cms-sw/cmssw/pull/26605/files?w=1

getting this in will allow clean running of clang-format.

**Comment by pohsun** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by perrotta** [comment]
+1
- It just deals with insertion/deletion of spaces, realignment, etc.
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
@smuzaffar I will merge it at next IB

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
