### PR TITLE
[NanoAOD] Backport of #44479 (Add number of B & C hadrons for GenJetAK8 and GenJet) to 14_0_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport of #44479 

#### Original PR description:

This PR adds the number of B/C-hadrons branches for `GenJetAK8` and `GenJet` tables . The same branches are removed from the `FatJet` table.  Addresses the Issue [here](https://gitlab.cern.ch/cms-nanoAOD/xpog-coordination/-/issues/68).

#### PR validation:

passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
hold

* Since this is technically a data formats change and a new feature to the stable branch, this should be discussed at the ORP and needs sign-off from PPD.

**Comment by antoniovilela** [comment]
unhold

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
