### PR TITLE
Clean BuildFiles in RecoMuon and RecoParticleFlow

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick round of automatic BuildFile.xml cleaning like in https://github.com/cms-sw/cmssw/pull/28779 to improve the modularity of CMSSW.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical update which removes unneeded dependencies in the BuildFiles
- Everything runs, jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
