### PR TITLE
Phase2-hgx93 Clean up all the validation classes and unused cfi(cfff) files

### PR DESCRIPTION
**Pull request by bsunanda**
In view of removing unused HGCal codes

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
@bsunanda can you also suppress the message "No PHGCalInfo"? That one is still present in the matrix logs from this PR.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21734	ab1bd1a
- this is rather tangential to reco, only via Validation/Configuration
- jenkins tests pass and comparisons with baseline show no relevant changes in reco quantities (ignoring the randomness from HCAL M3); there is also a significant reduction in the number of LogWarnings

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
