### PR TITLE
MINIAOD: sorting of packedPFcandidates and PV association information - 74X same as #8132

### PR DESCRIPTION
**Pull request by arizzi**
The information about which PV is matched to a candidate is added and the existing bits (fromPV) used for different definitions of CHS are improved to carry more information and allow change-of-PV from miniAOD.

In addition a sorting of the candidates is provided to improve the zlib compression (put similar things sequentially).

Unused ifdef'ed code is also removed.

Overall, this PR reduces the miniaod size by  2Kb/ev.
http://arizzi.web.cern.ch/arizzi/3bits.html (this PR)
vs
http://arizzi.web.cern.ch/arizzi/refib.html (original)

Legacy behaviour of  PackedCandidate::fromPV() is implemented and gives 99.95% the same result (remaining difference can probably be fixed, if needed, by further tuning the accessor)

74X version of #8132

@gpetruc

### CODE REVIEW

**Comment by davidlange6** [comment]
@arizzi- this doesn't merge now....

**Comment by arizzi** [comment]
I'll rebase

**Comment by arizzi** [comment]
@davidlange6  rather than rebasing I changed one line to avoid the conflict so that both this and #8132 are mergable

**Comment by monttj** [comment]
+1

**Comment by arizzi** [comment]
can this be merged? (as it twin #8132 was)

**Comment by arizzi** [comment]
@davidlange6 can we get in sync with 75X? otherwise it is a mess to keep new PRs in sync..

**Comment by davidlange6** [comment]
@arizzi - would be better to develop in 75x and then port in chunks... 74x will tend to be behind 75x.

**Comment by davidlange6** [comment]
+1

**Comment by arizzi** [comment]
this PR is already integrated in 75X... other people are developing on 74X

**Comment by arizzi** [comment]
(closed by mistake)

**Pull request merged**
