### PR TITLE
more cleanup of RecoLocalMuon/RPCRecHit

### PR DESCRIPTION
**Pull request by fwyzard**
- pass collections by const T\* instead of by edm::Handle<T>
- return values as std::unique_ptr<T> instead of T*
- remove unused function parameters

### CODE REVIEW

**Comment by fwyzard** [comment]
this is a follow up to #10936 , and is tracked at #10964

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11000	d2fa10a
- code changes look OK
- there are no changes in DQM plots based on jenkins (only HLT DQM can have any possible differences)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
