### PR TITLE
[12_3_X] Incorporate PiZeroAnalyzer code into ECAL DQM

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

ECAL DPG requested to have the offline DQM plots ([example offline GUI](https://tinyurl.com/2ykhlsat)) from `PiZeroAnalyzer` in `DQMOffline/EGamma` available in online DQM as well. 
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/plugins/PiZeroAnalyzer.h
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/plugins/PiZeroAnalyzer.cc
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/python/piZeroAnalyzer_cfi.py

In order to do this, we have migrated the code above into a new ECAL DQM module `PiZeroTask` in `DQM/EcalMonitorTasks`, which can then create plots both online and offline.

This new code is functionally the same as the old analyzer but after discussing with DPG, we decided to leave the old analyzer code in to not break anything. Open to discussion.

Complimentary PR to dmwm/deployment:
- https://github.com/dmwm/deployment/pull/1155

#### PR validation:

Online DQM client run on test data. Offline DQM tested on relval WF 11634.511 (`runTheMatrix.py -w upgrade -l 11634.511`). In both cases, the new plots were created successfully and matched the features of the old plots.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38561 to have for first 13.6 TeV stable collisions

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
backport of #38561

**Comment by emanueleusai** [comment]
testing at P5

**Comment by qliphy** [comment]
@emanueleusai  Any news on P5 test with this PR?

**Comment by micsucmed** [comment]
@qliphy I changed the run to 353701, let me know if it's better and if we can deploy.

**Comment by abhih1** [comment]
@micsucmed That run only has 26 lumisections. Could you try to load the run 354588?

**Comment by abhih1** [comment]
@micsucmed that run only has 26 lumisections. Could you please load the run 354507?

**Comment by abhih1** [comment]
@micsucmed In the current run 354787 the plots are not filled at all!

**Comment by micsucmed** [comment]
@abhih1 unfortunately this runs are not available at ramdisk anymore do you know of any more recent runs that could be used?

**Comment by abhih1** [comment]
> @abhih1 unfortunately this runs are not available at ramdisk anymore do you know of any more recent runs that could be used?

How about this run? 354787.

**Comment by micsucmed** [comment]
@

> @micsucmed In the current run 354787 the plots are not filled at all!

I tried this one, but plots where empty.

**Comment by alejands** [comment]
@micsucmed Could you try run 354552? This has 500 LS according to OMS

**Comment by micsucmed** [comment]
@alejands the run is not available at Ramdisk either. How about 353689 or 354054 that are on DQM playback files?

**Comment by alejands** [comment]
@micsucmed Okay could you please try 354054?

**Comment by micsucmed** [comment]
@alejands running

**Comment by alejands** [comment]
@micsucmed The plots are now on playback and everything appears to be running as expected

**Comment by alejands** [comment]
We would like to have this deployed as soon as possible to have it in time for collisions tomorrow

**Comment by emanueleusai** [comment]
great! @micsucmed thank you for all the testing, please go forward and deploy as soon as you can

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
