### PR TITLE
Backport of final DQM plot updates for Totem T2 run 25.6 (PR #41922)

### PR DESCRIPTION
**Pull request by oljemark**
#### PR description:

For the TOTEM special foreseen on 25.6.2023, the new T2 telescope will be used (and removed after the run) to measure inelastic rate and veto diffractive p+p collisions, when measuring the elastic p+p cross section.
This PR is for a special TOTEM release to be ready for testing start of next week (https://github.com/cms-sw/cmssw/pull/41859#issuecomment-1584370879), which is now this week. 

This PR backports the DQM fixes in PR #41922 , and rebases that branch on top of the PR #41916, that backports recent TOTEM T2 code development into 13_0_X. This PR is the final one needed for testing a special 13_0_X release for TOTEM, or possibly to be backported to 13_1_X too, see https://github.com/cms-sw/cmssw/pull/41916#issuecomment-1585592026 . The PR being backported here hasn't yet had testing start, so if any problems should be found, their solution will be added here too.

#### PR validation:

The code compiles & running the totemt2_dqm_test_common_cfg.py  test file gives the expected histograms out, as does the T2 unit test from PR #41916 . 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR proposes to backport PR #41922 to 13_0_X for a special TOTEM release, or testing such, and also maybe to 13_1_X, see discussion above.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type ctpps

**Comment by mandrenguyen** [comment]
backport of #41922

**Comment by mandrenguyen** [comment]
please test

**Comment by perrotta** [comment]
urgent
(DAS input errors are unrelated)

**Comment by rappoccio** [comment]
This PR will need a "backport" to https://github.com/cms-sw/cmssw/tree/CMSSW_13_0_7_TOTEM_X before we create the release.

**Comment by mandrenguyen** [comment]
+reconstruction
Indeed DAS errors are unrelated
@oljemark do you think you or someone else can present the a summary of the developments for the high beta* run at the reco meeting this Friday at 15:30 CEST ?

**Comment by tvami** [comment]
Thanks Andrea! Indeed after I saw that you moved to `CMSSW_13_0_7_TOTEM_X` it made sense. 
@oljemark since you have to rebase anyway, would you mind squashing the activity on June 11? thanks!

**Comment by aloeliger** [comment]
Sorry, this just showed up in my inbox and seems to contain multiple duplicate L1 commits. Were these intended?

**Comment by perrotta** [comment]
@oljemark this PR includes also all commits from #41916: Is it intended?

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_0_X

**Comment by oljemark** [comment]
Hi, @perrotta . That was because I wasn't sure if this PR & #41916 could be automerged or if this PR would even compiled if I rebased both on top of 13_0_X, since this PR depends on the T2 code in PR #41916. If you think I can rebase both on top of CMSSW_13_0_7_TOTEM_X, then I'll do that.

**Comment by perrotta** [comment]
please abort

**Comment by tvami** [comment]
+1
 * tests pass

**Comment by emanueleusai** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
