### PR TITLE
[L1T] fix improper casting

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Addressing improper casting mentioned in issue https://github.com/cms-sw/cmssw/issues/37691

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
