### PR TITLE
Use thread safe module types in PhysicsTools/JetMCAlgos

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Swtiched to one or global module type
- Also added esConsumes when needed.

This fixes all the CMS deprecated warnings in the package.

#### PR validation:

Code compiles and no longer issues the deprecated warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
FYI @makortel

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Bypassing analysis signature

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
