### PR TITLE
[12_4_X Backport] ECAL DQM GpuTask add 2D comparison histograms and enable GPU validation on online DQM

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

The following additions are made to the ECAL DQM GPU validation module:

- Add in 2D histograms for comparing CPU and GPU generated values of ECAL digis, uncalibrated rec hits, and rec hits
- Create separate subdirectories for each ECAL object (digis, uncalibrated rec hits, rec hits) to reduce clutter with too many plots in one place
- Create more flags to be able to better customize what plots to make when running the module. Eg. for digis, `enableDigi` toggles running over GPU and CPU digi collections (creates CPU value 1D distribution and 1D GPU-CPU value difference by default), `digi1D` enables GPU value 1D distribution, and `digi2D` enables the 2D plots plots mentioned above
- Create separate dedicated client for GPU validation on ECAL online DQM

This PR addresses the remaining outstanding tasks in this issue: https://github.com/cms-sw/cmssw/issues/37025

#### PR validation:

Online DQM configuration tested on test file provided by DQM-DC containing the new HLT collections. Offline DQM configuration tested on CPU-only and GPU WFs (`runTheMatrix.py -w upgrade -l 11634.511,11634.512,11634.513`).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of https://github.com/cms-sw/cmssw/pull/38427 to use in data taking

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #38427

**Comment by fwyzard** [comment]
type new-feature

**Comment by fwyzard** [comment]
type ecal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
