### PR TITLE
bsunanda:Run2-hcx24 Changes to Hcal reconstruction geometry and topology

### PR DESCRIPTION
**Pull request by bsunanda**
This works on top of PR 10247. Together with the geometry in the DB this may be tried for the tests in the matrix. Some more adaptation is needed in the code for usage of this in parts of the reconstruction and digitization code.

### CODE REVIEW

**Comment by ianna** [comment]
This PR should go in IBs together with #10247 and a new GT

**Comment by mark-grimes** [comment]
Because `hcalTopologyConstants` is taken out of `fillDescriptions()` ([Geometry/HcalEventSetup/src/HcalTopologyIdealEP.cc#L80](https://github.com/cms-sw/cmssw/pull/10312/files#diff-8c86c646a0db9ed69ece271295b66b34L80)), it also has to be taken out of the python fragments.  E.g.

    runTheMatrix.py -l 1325 --command "--geometry Extended2015"

will fail in step1 with:

    ----- Begin Fatal Exception 24-Jul-2015 14:17:54 CEST-----------------------
    An exception of category 'Configuration' occurred while
       [0] Constructing the EventProcessor
       [1] Validating configuration of ESProducer or ESSource of type HcalTopologyIdealEP with label: 'hcalTopologyIdeal'
    Exception Message:
    Illegal parameter found in configuration.  The parameter is named:
     'hcalTopologyConstants'
    You could be trying to use a parameter name that is not
    allowed for this plugin or it could be misspelled.
    ----- End Fatal Exception -------------------------------------------------

To fix that: https://github.com/bsunanda/cmssw/compare/Run2-hcx24...mark-grimes:fix_10312.  I would put it in on a PR on Sunanda's branch but I'm not sure if taking it out is the desired end result, since this PR also includes a new python file which has a `hcalTopologyConstants` parameter: [Geometry/CaloTopology/test/python/testHcalTopology_cfg_dump.py#L181](https://github.com/cms-sw/cmssw/pull/10312/files#diff-b73fc54e1cdc19c6cb4d1e904e284387R181).  If the parameter is still required I think it needs to be set to an empty PSet in `fillDescriptions()` rather than taken out?

After applying the patch mentioned above, step 1 runs but there is still a failure in step 2:

    ----- Begin Fatal Exception 24-Jul-2015 19:16:49 CEST-----------------------
    An exception of category 'NoProxyException' occurred while
       [0] Processing run: 1
       [1] Calling global beginRun for module MixingModule/'mix'
       [2] Using EventSetup component CaloGeometryBuilder/'' to make data CaloGeometry/'' in record CaloGeometryRecord
       [3] Using EventSetup component HcalHardcodeGeometryEP/'' to make data CaloSubdetectorGeometry/'HCAL' in record HcalGeometryRecord
       [4] Using EventSetup component HcalTopologyIdealEP/'hcalTopologyIdeal' to make data HcalTopology/'' in record HcalRecNumberingRecord
    Exception Message:
    No data of type "HcalDDDRecConstants" with label "" in record "HcalRecNumberingRecord"
     Please add an ESSource or ESProducer to your job which can deliver this data.
    ----- End Fatal Exception -------------------------------------------------

I guess that can be fixed in another PR though.  Note that I tested on CMSSW_7_6_X_2015-07-22-2300 plus this PR since CMSSW_7_6_X_2015-07-23-2300 has an unrelated error.

@boudoul, this PR plus patch above also fixes the Phase 1 workflow up to GEN-SIM.  Same failure in DIGI.

**Comment by bsunanda** [comment]
I have put a new PR (10353) on top of this. This enables the job to run beyond GEN-SIM. It has done DIGI-RECO and also past the DQM stage. But the real fix is to remove all HcalTopology initiation using maxdepth and topology mode arguments.
________________________________

**Comment by civanch** [comment]
@bsunanda , may be only 10353 should be left and this one can be closed?

**Comment by bsunanda** [comment]
I put in the changes in 3 steps thinking I shall   get the IB at the end of each step. I think 10353 has all the changes in the 2 previous steps. So you are right - but I shall close them once 10353 is integrated.
________________________________

**Pull request closed without merging**
