### PR TITLE
New Global Tags for 74X: data Run2 reprocessing + taxonomy changes 

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes
## Run I simulation
- **Ideal scenario** : [74X_mcRun1_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_design_v2) as [74X_mcRun1_design_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_design_v1/74X_mcRun1_design_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Realistic scenario** : [74X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_realistic_v2) as [74X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_realistic_v1/74X_mcRun1_realistic_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Heavy Ions** : [74X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_HeavyIon_v2) as [74X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_HeavyIon_v1/74X_mcRun1_HeavyIon_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Proton-Lead** : [74X_mcRun1_pA_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_pA_v2) as [74X_mcRun1_pA_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_pA_v1/74X_mcRun1_pA_v2): 
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
## Run II simulation
- **Asymptotic scenario** : [74X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_asymptotic_v4) as [74X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_asymptotic_v2/74X_mcRun2_asymptotic_v4):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario
  - updated Jet energy corrections for 25 ns.
- **Ideal scenario** : [74X_mcRun2_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_design_v4) as [74X_mcRun2_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_design_v2/74X_mcRun2_design_v4):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario
  - updated Jet energy corrections for 25 ns.
- **Startup scenario** : [74X_mcRun2_startup_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_startup_v3) as [74X_mcRun2_startup_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_startup_v2/74X_mcRun2_startup_v3):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS.
- **Heavy Ion** : [74X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_HeavyIon_v3) as [74X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_HeavyIon_v2/74X_mcRun2_HeavyIon_v3):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario.
## Run II data
- **HLT processing** : [74X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_HLT_frozen_v3) as [74X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_HLT_frozen_v2) (snapshot time set to 2015-10-14 10:09:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_HLT_frozen_v2/74X_dataRun2_HLT_frozen_v3):
  - taxonomy changes (removing account names from tags or separating MC and data tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping, Tracker and Castor reconstruction geometry, L1 RPC Hardware configuration, DT and CSC APE.
- **Offline processing** : [74X_dataRun2_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v5) as [74X_dataRun2_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_v3/74X_dataRun2_v5):
  - all changes intended for Run2015A+B+C re-reco
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
  - removing unused b-tagging working point records 
  - new set of tags covering the update of JEC for the 25ns data taking period. L2L3Residuals and uncertainties for 25ns have been updated.
## Run I data
- **HLT processing** : [74X_dataRun1_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_HLT_frozen_v3) as [74X_dataRun1_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_HLT_frozen_v2) (snapshot time set to 2015-10-14 10:09:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_HLT_frozen_v2/74X_dataRun1_HLT_frozen_v3):
  - taxonomy changes (removing account names from tags or separating MC and data tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping, Tracker and Castor reconstruction geometry, L1 RPC Hardware configuration, DT and CSC APE.
- **Offline processing** :  [74X_dataRun1_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v4) as [74X_dataRun1_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v3) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_v3/74X_dataRun1_v4):
  - all changes intended for Run2015A+B+C re-reco
  - taxonomy changes to avoid fully qualified account names in the tag name for several records

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@hengne this PR contains the new offline GTs for 2015 B/C re-reco that we should validate.

**Comment by diguida** [comment]
+1
for data: new GT containing updated conditions for Re-reco of 2015B-C
for Run1 MC: technical changes and compatibility additions
for Run2 MC: technical changes and compatibility additions and backport of MC conditions describing the configuration of the detector as of Run2015D.

**Comment by diguida** [comment]
@davidlange6 this is the set of GT used in the recent re-reco campaign. Unfortunately, yesterday we could not come to the ORP meeting and ask for its inclusion (you'd like to see the RelVal results first).

We suggest therefore to supersede this one and consider #12022 for merging, once the RelVal tests are ok. That's why the original PR #11989 is now superseded.

**Comment by mmusich** [comment]
please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Pull request closed without merging**
