### PR TITLE
removing Pv from MINIAOSIM, the PVs are actually not stored

### PR DESCRIPTION
**Pull request by perrozzi**
backport of https://github.com/cms-sw/cmssw/pull/18083

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by slava77** [comment]
backport of #18083

somehow cmsbot does not recognize this in the PR description to set a label.
@smuzaffar is it possible to check the description as well to assign the label?

**Comment by smuzaffar** [comment]
@slava77 , it does recognize the PR description but one should use ```backport of #NNNN``` 
for this PR the description is ```backport of https://github.com/cms-sw/cmssw/pull/18083```
anyway, I will fix the bot to recognize full PR url too

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19822	aeab001
- technical update to allow runnig PATPackedGenParticleProducer from GEN; no changes to existing workflows
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
merge

**Pull request merged**
