### PR TITLE
APE tool updated to PhaseI geometry (same as PR #18406 but for 90X)

### PR DESCRIPTION
**Pull request by cschomak**
- Geometry updates for the APE tool to use the new PhaseI geometry

- Modernized TrackerTreeGenerator

- Removed unused variables

- Small updates in config scripts in test folder (samples, objects, GTs...)

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@cschomak could you push the commits from #18406 also here, please?

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by davidlange6** [comment]
+1

**Pull request merged**
