### PR TITLE
[13.0.X] Misceallaneous Tracker Alignment validation updates for 2023 data-taking 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a combined backport of https://github.com/cms-sw/cmssw/pull/41378 and https://github.com/cms-sw/cmssw/pull/41393
I add a generic vertex analyzer to be used for the Tracker Alignment alcareco monitoring. I profit of this PR to add some more histograms concerning the Beam Spot monitoring to an existing analyzer and to improve the unit test suite.
In addition it fixes some miscellaneous problems in the Tracker alignment di-muon validation code:
   * do not use range-based loops to create the candidate, which duplicated the entries in the histograms;
   * fix the pseudo-rapidity range for creating the input histograms
   * fix the inclusion of the auto-generated cfi file in the validation configuration file 

#### PR validation:

Private tests, plus run successfully the augmented unit tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a combined backport of https://github.com/cms-sw/cmssw/pull/41378 and https://github.com/cms-sw/cmssw/pull/41393 meant for analysis of the 2023 data from the Tracker Alignment group.

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41378

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41393

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
