### PR TITLE
CT-PPS Pixel local track reconstruction patch

### PR DESCRIPTION
**Pull request by fravera**
https://github.com/cms-sw/cmssw/pull/21107#issuecomment-341399443

### CODE REVIEW

**Comment by fravera** [comment]
@fabferro

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
backport of #21107

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21133	250b40a
- bugfixes in selections of CTPPS pixel reco; the same update as in 10_0_X (the same topic branch and commit ID); the master branch version is merged already
- jenkins tests pass

This is needed for 2017 data (re)reco.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
