### PR TITLE
Run2-hcx167 Add a version of 2018 description which allows collapsing of HE depths in reconstruction

### PR DESCRIPTION
**Pull request by bsunanda**
Default 2018 geometry uses the collapsing scenario while 2018Plan36 geometry gives full fledged HE sceanrio

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1
use of combined depths for RecHits will further need to be activated with an Era (PR forthcoming once this is merged)
question: should we make a separate 2018Plan36 workflow for development?

**Comment by kpedro88** [comment]
also, 2018 workflow uses DB geometry, so GTs should be updated (depending on how the workflows will be organized)

**Comment by ianna** [comment]
+1

@kpedro88 - ok, I'll provide the payloads and request GT update for 2018.

**Comment by deguio** [comment]
Hello @ianna 
are the payload and the GT available already? is anything required on our side?
thanks and cheers,
F.

**Pull request merged**
