### PR TITLE
fix typos in HLT validation directories (#21092 backport)

### PR DESCRIPTION
**Pull request by mtosi**
backport of https://github.com/cms-sw/cmssw/pull/21092 (and https://github.com/cms-sw/cmssw/pull/21093)

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
backport of #21092

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mtosi 
Is this still relevant for legacy studies with 92X and/or mid-week global runs in case they will be done with 92X?

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
