### PR TITLE
Adding distributions over eta and phi

### PR DESCRIPTION
**Pull request by natalia-korneeva**
Following last discussions with btagging@HLT conveners the distributions over eta and phi are to be added to the DQM validation chain.

### CODE REVIEW

**Comment by heppye** [comment]
green light from BTV@HLT.

**Comment by mtosi** [comment]
this code runs in the VALIDATION step, why are you not adding such code to your module run in the DQM step ?

in addition, I would suggest to make use of the GenericTriggerEventFlag

please, make use of configurable parameters for handling the histogram axis range

**Comment by mtosi** [comment]
in addition, please do the PR for the master (91x)

**Comment by natalia-korneeva** [comment]
Thanks for the comments, it seems to me that they concern mostly the whole HLTriggerOffline/BTag code, and not adding eta/phi distributions itself, that is a minor modification, based on the current version of the code. 
Could you comment more on the first and second proposals? Concerning the parameters of axis ranges they are fixed as the eta (phi) ranges are always the same. It doesn't make sense for the direct HEP17 region monitoring, since it requires other code modifications.
I will do the PR for the master, thanks.

**Comment by mtosi** [comment]
eta acceptance for instance is not fixed, in phase1 and phase2 I think it should become 3 and 4 (or even larger)

on GenericTriggerEventFlag, please look at 
https://github.com/natalia-korneeva/cmssw/blob/4900dd424f33f192f8420dd9b0dec46acd49b6e9/DQMOffline/Trigger/plugins/METMonitor.cc
and 
https://github.com/natalia-korneeva/cmssw/blob/4900dd424f33f192f8420dd9b0dec46acd49b6e9/DQMOffline/Trigger/python/METMonitor_cff.py
for its configuration

the GenericTriggerEventFlag is useful for selecting events based on HVON of the different sub-detectors

on moving the whole code to the DQM step,
I did not look into all details of this module, and therefore I cannot comment as now

my point is that such development should go into the DQM step as well
because we have to monitor the performance in the HEP17 on data

in addition, for the HEP17 I think you should add some plots done only in the HEP17 region
and in HEM17 one and/or other slice in HEP for doing the comparison

**Comment by heppye** [comment]
@mtosi,@natalia-korneeva, to be added, for HEP17, as being discussed during the tsg meeting today, it could be further studied with local validations in the relevent regions with available high statistics RelVal. And we could discuss later for adding 2D plots to future campaigns in case statistics could be allowed. This PR is a first step of starting to add interesting BTV@HLT distributions which are not in Validation/DQM yet. @natalia-korneeva , please re-base or re-make your PR to CMSSW_9_1_X as being suggested. Thanks.

**Comment by mtosi** [comment]
for doing studies on high stat samples
you do not need this PR to be merged

I would prefer having plots on high stat samples
and in parallel fix this PR

in my previous message, I'm not talking about having 2D plots
I'm saying that a simple distribution vs phi and vs eta is not enough for
studying the effect of HEP17
you should have a distribution vs eta after having selected a specific
range in phi
and a distribution vs phi after having selected a specific range in eta

right ?

**Comment by heppye** [comment]
@mtosi,  yes. However we should add eta/phi dimension's monitoring to validation/DQM for future campaigns. Thanks.

**Comment by natalia-korneeva** [comment]
PR moved to 91X
https://github.com/cms-sw/cmssw/pull/18413

**Pull request closed without merging**
