### PR TITLE
Hcal phase1 fastsim update and run2 hcx178 : backport to 94X

### PR DESCRIPTION
**Pull request by ssekmen**
Backports of 
#22990 : HCAL phase1 fastsim updates
#23631 : Run2-hcx178 Usage of the correct Hcal geometry in FastSim

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by ssekmen** [comment]
backport of #22990 and #23631

**Comment by andrius-k** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by ssekmen** [comment]
@kpedro88 , can you please merge this?  Thanks.

**Comment by kpedro88** [comment]
+1

**Pull request merged**
