### PR TITLE
EGM-certified electron IDs for 2016 data: cut-based and MVA

### PR DESCRIPTION
**Pull request by ikrav**
This PR contains EGM certified cut-based and MVA electron IDs tuned on 80X samples. They are intended to be used on 2016 data. The electron MVA contains the HZZ MVA used for ICHEP16 and the presently recommended general purpose MVA tuned for better performance given features of a more complete 2016 dataset.

This code is being submitted to 80X, 81X, and 90X. The 90X PR is already merged, the changes that came up during merge are also introduced into this one.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #16979

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17191	4d6f513
- backport of #16979 already merged in 90X a few weeks ago; the same changes are applied. New files that implement new ID are added. The IDs are included in the process.electronMVAValueMapProducer running in the standard workflow, but the transient products made there are not saved or consumed in what can lead to changes in persisted products or monitoring results. So, the change is good to go as analysis-only.
- jenkins tests pass and comparisons with baseline show no differences
- local test, as a cross-check, confirms lack of changes in persisted products

**Comment by davidlange6** [comment]
+1

**Pull request merged**
