### PR TITLE
Add cfi file for CandPtrSelector

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Add cfi file for CandPtrSelector

To make ConfDb parsing happy

#### PR validation:

scram compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@cms-sw/reconstruction-l2 please sign

**Comment by mmusich** [comment]
type hlt-int

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
