### PR TITLE
GenJetFlavourInfos in MiniAOD and Change in JetFlavour of LightJets to physicsPartons in CMSSW 80X

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Backport of #19048

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

it looks like this PR changes miniAOD content.
It will not be merged until re-miniAOD v2 campaign release is to be built (and the current plan is to do it in 9X)

**Comment by Andrej-CMS** [comment]
@slava77 Should I then prepare another PR for 90X, or will the 92X PR be backported to 90X?

**Comment by slava77** [comment]
On 5/31/17 2:30 PM, Andrej-CMS wrote:
> @slava77 <https://github.com/slava77> Should I then prepare another PR
> for 90X, or will the 92X PR be backported to 90X?
> 

#19048
is the 9X PR.
No more porting is needed,

**Comment by slava77** [comment]
-1

#19048 has been merged. please match the content of this PR to that.
The comment in https://github.com/cms-sw/cmssw/pull/19049#issuecomment-305294016 still holds.
So, once the content is updated to be in sync with master, we'll proceed as with other similar PRs: sign off and put on hold until possibly later future when all current 80X campaigns are over and we can have an analysis release.

**Comment by fabiocos** [comment]
@Andrej-CMS @slava77 given the amount of time during which this PR is pending, could we just close it? I guess it is definitely obsolete

**Comment by slava77** [comment]
fine with me to close.
If it still needed, it can be reopened.
Anyways, if needed, the code will need to be updated for a consistent backport.

**Pull request closed without merging**
