### PR TITLE
[14.0.X] Backport - Refactor scatterer addition in aGblPoint to explicitly specify type for scatPrecision.inverse()

### PR DESCRIPTION
**Pull request by sroychow**
Backport of #44340. (thanks to @mmusich )

#### PR description:
Code compiles.

### CODE REVIEW

**Comment by sroychow** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/9057
- addpkg = Alignment/TrackerAlignment, Alignment/OfflineValidation
- workflows = 1001.0, 1001.2, 1001.3, 1001.4, 1002.4

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
test parameters:

- pull_request = https://github.com/cms-sw/cmsdist/pull/9057
- addpkg = Alignment/TrackerAlignment, Alignment/OfflineValidation
- workflows = 1001.0, 1001.2, 1001.3, 1002.4

**Comment by perrotta** [comment]
Workflow 1001.4 is not defined in 14_0_X

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44340

**Comment by sroychow** [comment]
urgent
- need a 140X to run alignment campaigns for rereco + 2024 conditions

**Pull request merged**
