### PR TITLE
L1T offline emulator DQM config upgrades - 102x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #24290 

Contains also PR #24239 to avoid conflicts in 10_2_X.

This PR activates the offline emulator DQM for the L1T.

Since the calo layer2 emulator needs the data of validation events it cannot run in the offline DQM from unpacked calo layer2 digis. Instead we run the calo layer1 + layer2 emulator chain to get the emulated caloLayer2 objects without the need for unpacked layer2 inputs (https://its.cern.ch/jira/browse/CMSLITDPG-418).

In addition the emulated L1T objects offline DQM (efficiency and resolution) is added.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
+1
This PR adds previously not generated plots for the offline L1T emulator monitoring.

**Comment by thomreis** [comment]
+1
conflict resolved

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@thomreis this needs to be rebased

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
conflict fixed.
@andrius-k please sign again.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by thomreis** [comment]
please test workflow 136.867

**Pull request merged**
