### PR TITLE
Cleaning runthematrix76 x

### PR DESCRIPTION
**Pull request by boudoul**
This PR is intended to synchronize runthematrix with 75X  (see PR #10558)
It removes the option magfield added by mistake by @srimanob
Some check should be further done with the baseDataSetRelease but testing already as it is now

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by boudoul** [comment]
removed duplicate

**Comment by boudoul** [comment]
please test

**Comment by srimanob** [comment]
Sorry, I don't follow up the comment that "It removes the option magfield added by mistake by me."
@boudoul , why don't we need magField for FastSim?
However, this line is proposed by FastSim group,
https://github.com/lveldere/cmssw/blob/8dd97e3968c6b2bdd0047e3b8a16c556c4a2d388/Configuration/PyReleaseValidation/python/relval_steps.py#L613

@lveldere Could you please comment?

**Comment by boudoul** [comment]
@srimanob and @lveldere : from CMSSW_7_4_3 and CMSSW_7_5_0_pre5 : the magfield is read from the GT and not anymore from xml, see here (*) for reference - If it is also in runthematrix74X also we should remove it from there too.

(*) https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3214.html

**Comment by srimanob** [comment]
OK, Thanks. I will fix 74X.

**Pull request merged**
