### PR TITLE
HLT menu development for `14_0_X` (9/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/45548

#### PR description:

Development of HLT menus for CMSSW_14_0_X.
   * This is the PR for the 14.0.X branch (this is the release cycle currently used for Run-3 HLT-menu development).
   * This version of the GRun HLT menu corresponds to the list of updates to the **"V1.4"** (last) menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
   * [CMSHLT-3224](https://its.cern.ch/jira/browse/CMSHLT-3224) [CSC] Update configuration of CSC-RecHit builder (Run2024)
   * [CMSHLT-3237](https://its.cern.ch/jira/browse/CMSHLT-3237) [ECAL] Remove hltGtStage2Digis from EvenContent of ALCAP0 and ALCAPHISYM streams
   * [CMSHLT-3238](https://its.cern.ch/jira/browse/CMSHLT-3238) [RPC] Remove digi/reco products from EvenContent of RPCMON stream
   * [CMSHLT-3239](https://its.cern.ch/jira/browse/CMSHLT-3239) [RPC] Unpack RPC from TwinMux+OMTF+CPPF FEDs
   * [CMSHLT-3241](https://its.cern.ch/jira/browse/CMSHLT-3241) [TSG] Remove "source" from EventContents of the HLT combined table
   * [CMSHLT-3245](https://its.cern.ch/jira/browse/CMSHLT-3245) [TAU] Fixing L2 Cut in VBF DiTau Monitoring Trigger
   * [CMSHLT-3264](https://its.cern.ch/jira/browse/CMSHLT-3264) [EXO,JME,SUS] Set PS=0 for HLT_PFMETNoMu110_PFMHTNoMu110_IDTight_FilterHF_v
   * [CMSHLT-3268](https://its.cern.ch/jira/browse/CMSHLT-3268) [DQM] DQMEventDisplay: replace HLT_ZeroBias_v with HLT_Physics_v
   * [CMSHLT-3269](https://its.cern.ch/jira/browse/CMSHLT-3269) [TSG] Split streams and datasets of SpecialHLTPhysics by 20
   * [CMSHLT-3270](https://its.cern.ch/jira/browse/CMSHLT-3270) [TRK] Set "SiStripClusterChargeCut" to "Loose" for tracks with pT<15 GeV (non-HIon menus)
   * [CMSHLT-3273](https://its.cern.ch/jira/browse/CMSHLT-3273) [L1T] Integration of CICADA Pass-Through Triggers
   * [CMSHLT-3274](https://its.cern.ch/jira/browse/CMSHLT-3274) [DQM] Update EventContent of DQM stream (post Run2024F)
   * [CMSHLT-3275](https://its.cern.ch/jira/browse/CMSHLT-3275) [DQM] Cleanup of EventContent of HLTMonitor stream (post Run2024F)
   * [CMSHLT-3276](https://its.cern.ch/jira/browse/CMSHLT-3276) [BPH] Increase splitting of ParkingSingleMuon PDs and streams from 8 to 12
   * [CMSHLT-3277](https://its.cern.ch/jira/browse/CMSHLT-3277) [MUO] Relaxed Muon Tracker Isolation cut
   * [CMSHLT-3278](https://its.cern.ch/jira/browse/CMSHLT-3278) [DQM] Use  general DQM modules for pixel rechits, tracks and vertices added in cmssw#45302
   * [CMSHLT-3280](https://its.cern.ch/jira/browse/CMSHLT-3280) [L1T] L1TGlobalProducer: new CICADA InputTag
   * [CMSHLT-3281](https://its.cern.ch/jira/browse/CMSHLT-3281) [HCAL] ALPAKA implementation of HCAL local reconstruction
   * [CMSHLT-3285](https://its.cern.ch/jira/browse/CMSHLT-3285) [Scouting] Set PS=0 for DST_PFScouting_SinglePhotonEB_v in "2p0E34_NoScouting" column
   * [CMSHLT-3288](https://its.cern.ch/jira/browse/CMSHLT-3288) [TRK] Update pixel doublet recovery iteration following the FPix1- issue
   * [CMSHLT-3289](https://its.cern.ch/jira/browse/CMSHLT-3289) [TSG] Adjust PSs for Ephemeral in "2p0E34+ZeroBias+HLTPhysics" column (2024F)
  * [CMSHLT-3292](https://its.cern.ch/jira/browse/CMSHLT-3292) [TSG] Prescale HLT_L1AXOVTight_v (L1T-2024_v1_3_0)
  
In addition, the following changes are included:
   * 6e0db1d0a95893010b4172e4d30fc54cc47dd4f7 : update of L1T FULL,GRun,2024v14,Special menus in TSG GTs to `L1Menu_Collisions2024_v1_3_0_xml`
   * ec12c1da2aca1fb0c80256bae3612698e7ba4c23 : Preparation for next version of Special menus
   * 3bdc23a4fe63b49f1d601cd261714455b6827697 : update of `hltPathOwners.json` for menu V1.4 (as per recent TSG survey)
   * f52b8ae3609dbefd517a8a84f8cdd36797304bc0 : Introduce 2024v1.4 frozen menu and remove 2024v1.3
   * d44b95c064338f288e3f65c5dd03f76a00b73df3: make `@relval2024` autoHLT key point to the `2024v14` frozen menu
  
#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/45548 to the 2024 production cycle (`CMSSW_14_0_X`)

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@cms-sw/orp-l2 kind ping.
As far as I can tell the master version of this PR (https://github.com/cms-sw/cmssw/pull/45548) didn't cause any issue in the IBs (we had already several tested).

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
