### PR TITLE
Fixes for DeepDoubleX [12_4_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #39184

attn: @mariadalfonso

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- backport of https://github.com/cms-sw/cmssw/pull/39184

**Comment by perrotta** [comment]
@kpedro88 would you mind submitting also a 12_5_X backport, to ensure continuity between the release cycles?

**Comment by kpedro88** [comment]
Sure, I didn't realize the milestone was changed before #39184 was merged.

**Comment by perrotta** [comment]
+1

**Pull request merged**
