### PR TITLE
Pr80x l1t-tsg-v9 for Sept 2016 MC production 

### PR DESCRIPTION
**Pull request by rekovic**
This the 80x PR for L1T emulation software tagged as tsg-v9.

This is an improved version of the PR #15661 in memory consumption and timing.  
- The changes are in EMTF emulator, where  4D vectors are replaced by typedef struct's containing arrays. The improvement is in the EMTF emulator memory consumption (by ~75%) and time performance (~50%).  The l1t emulation is bitwise identical before and after these changes, as expected. 

This is the version of the L1T  software intended for MC production. 
- It is identical to the l1t-integration-v85.1 tag of the L1T Software.  Included features of the tags up to this latest one are tracked on the [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev#Status_of_Integration)

Some remarks:
- Fixes in high pT muons in EMTF and the use of 2nd earliest arriving LCT are included.
- BMTF emulator uses RPCs although not present in data.  The firmware will be changed soon to use the RPCs as well. 
- Old calorimeter calibration constants are used. The derivation of the new ones is still ongoing, and 
  is not to be used in the MC production.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
81x version of this PR is in preparations.

**Comment by davidlange6** [comment]
@rekovic @mulhearn  - what is the status of the 81x pr? is #15661 now obsolete? [getting late...]

**Comment by rekovic** [comment]
@davidlange6 81x PR is #15732.
Will close now #15661 as it is obsolete.

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
The last set of update commis are the commits made after the review process of merged 81x PRs #15745, #15757, #15823, which are  Part 1, Part 2 (rebased), and Part 3 (rebased).

This should be all the commits needed for this 80x.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
rebased and merged.
Closing this one now.

**Pull request closed without merging**
