### PR TITLE
Fix a race condition in splitVertices [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add
```c++
alpaka::syncBlockThreads(acc);
```
at the end of the loop on the vertices to ensure that all threads are properly synchronised before resetting the shared memory.

Clean up the kernel to use the SoA accessors and the `cms::alpakatools` utilities.

#### PR validation:

Running the HLT with `compute-sanitizer --tool=racecheck` without this PR warns about a potential race condition in `splitVertices()`.
This PR fixes the warning: see https://github.com/cms-sw/cmssw/issues/44923#issuecomment-2271803296.

Running the current online HLT menu over 20k events on top of CMSSW 14.0.13-patch2 does not result in any changes to the HLT results (see https://github.com/cms-sw/cmssw/pull/45656#issuecomment-2274337336) and performance on GPU (see https://github.com/cms-sw/cmssw/pull/45656#issuecomment-2274492410).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #45656 to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
@mmusich @AdrianoDee @missirol FYI, but also can you double check this ?

**Comment by fwyzard** [comment]
backport #45656

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by AdrianoDee** [comment]
All the changes looks good to me

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
