### PR TITLE
[14.0.X] Generalize warp size in pixel clustering kernel

### PR DESCRIPTION
**Pull request by AuroraPerego**
#### PR description:

In the `FindClus` kernel there was an assumption on the warp size being equal to 32, which is true for NVIDIA GPUs, but not always for AMD GPUs. Now the warp size is taken from the `__AMDGCN_WAVEFRONT_SIZE` macro for HIP and uses 32 for CUDA.
Note that `alpaka::warp::getSize(acc)` cannot be used because it's evaluated at runtime.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of #46426 

FYI @fwyzard

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by fwyzard** [comment]
backport #46426

**Comment by jfernan2** [comment]
+1

**Pull request merged**
