### PR TITLE
Beam Halo Filter update 80X

### PR DESCRIPTION
**Pull request by lathomas**
Beam Halo Filter update. This is a copy of https://github.com/cms-sw/cmssw/pull/13926 for CMSSW 80X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@lathomas 
is this version changing anything in the standard outputs of 80X RECO/miniAOD?
Is any of it needed in MC?

**Comment by lathomas** [comment]
@slava77 The changes are the same as for the 81X. Here's a recap: 

RECO: 
-Ecal/HcalHaloData now contains a vector of haloclusters cands
-GlobalHaloData now contains the list of calohits associated to beam halo tagged clusters and information about CSC-calo matching/presence of halo pattern in the calorimeters. 
-CSCHaloData has the same content as before.
-BeamHaloSummary contains two new working points. 

AOD: BeamHaloSummary, CSCHaloData and GlobalHaloData are saved in AOD

MiniAOD: two flags added to the met filters.

It would be nice to have the two filters (globaltighthalo2016 and globalsupertighthalo2016) in Monte Carlo for mistag studies.

**Comment by gpetruc** [comment]
Hi @lathomas,
For much of the 80X MC, the AOD are already being produced without this PR. 
What happens when making MiniAODs with this PR starting from old AODs? do you still learn something about mistagging or not? 
(it's extremely late now to ask for something to go in miniAOD v2, it should have been done weeks ago)
@arizzi

**Comment by lathomas** [comment]
Hi @gpetruc , 
Indeed, this PR doesn't bring any new information if AOD is not rerun. 
So it's probably better to keep things as they are and not include this PR for MC production.

**Comment by slava77** [comment]
@lathomas 
please get this in sync with your #13926 in 81X
Thanks.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14023	ea797df
- code changes are in line with description, presentation in a reco meeting; the code is the same as in 81X version in https://github.com/cms-sw/cmssw/pull/13926	8ed4b41
- jenkins tests pass and comparisons with baseline show differences in halo variables as in #13926, as expected

**Pull request merged**
