### PR TITLE
Add a LowPU version of the HP Beam Spot workflow for PCL

### PR DESCRIPTION
**Pull request by cerminar**
A new PCL workflow is defined targeting the Beam-Spot computation in LowPU environment.
This is defining `PromptCalibProdBeamSpotHPLowPU` and the corresponding AlCaHarvesting steps.

Backport of #23558

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
backport of #23558

**Comment by lpernie** [comment]
please test

**Comment by cerminar** [comment]
please test

**Comment by arunhep** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test workflow 1030

testing also the dedicated addition by Gianluca

**Comment by cerminar** [comment]
please test workflow 1030

**Comment by fabiocos** [comment]
Running 1030 on 1000 events see comments in https://github.com/cms-sw/cmssw/pull/23558#issuecomment-396963392

**Comment by fabiocos** [comment]
+operations

**Comment by kpedro88** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

PdmV changes are working (wf 1030 used for this validation), the comparison was ok, and wf 1030 is not used in comparisons

**Comment by fabiocos** [comment]
merge

**Pull request merged**
