### PR TITLE
l1nano import location

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

trivial move of the import

#### PR validation:

nano matrix

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
@lathomas please have a look

**Comment by vlimant** [comment]
can we please have the remaining signatures to this ? @cms-sw/operations-l2 @cms-sw/upgrade-l2

**Comment by vlimant** [comment]
I honestly don’t know what turn over we can expect for signatures, but I have the feeling it’s taking much too much time for trivial things …

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
N.B `git cms-rebase-topic vlimant:l1nano_include` gives me all sorts of conflicts that are not detected here, therefore I cannot test anything locally and going blind

**Comment by AdrianoDee** [comment]
+pdmv
- re-sign

**Comment by vlimant** [comment]
could we bypass the operations signature to merge this in ?

**Comment by antoniovilela** [comment]
> N.B `git cms-rebase-topic vlimant:l1nano_include` gives me all sorts of conflicts that are not detected here, therefore I cannot test anything locally and going blind

@vlimant 
Is it working locally now?

**Comment by antoniovilela** [comment]
> could we bypass the operations signature to merge this in ?

@vlimant 
Do not worry about the @cms-sw/operations-l2 signature. ORP signs for operations, and usually we will sign and merge simultaneously, after the other signatures are cleared (as previously mentioned, you can raise PRs in the weekly meeting requesting missing signatures).

**Comment by vlimant** [comment]
all good on testing

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
