### PR TITLE
[12_4_X] HeavyFlavor DQM fixes

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

This is a collection of small fixes for the recently merged HeavyFlavorDQM.
It also adds a customiser to allow running the DQM module from miniAOD instead of AOD

#### PR validation:

Fixes tested on the workflow 1366.0 which uses this module. Customisation tested on Early Run3 miniAOD data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38791

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38791

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1347, 1349, 1350, 1364, 1365, 1366, 136.884, 136.896, 136.860, 136.898
   * relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

**Comment by emanueleusai** [comment]
+1

- changes caused by change in label/range of the plots

**Comment by tvami** [comment]
urgent
 * I understand that this should go into the next 12_4_X as well

**Pull request merged**
