### PR TITLE
Changed headers based on IWYU recommendations

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar these were the changes I thought were reasonable out of the items from here: 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/iwyu/slc6_amd64_gcc530/CMSSW_9_1_X_2017-03-26-0000/DataFormats/Common/index.html

I did skip items in `test` since many of those appeared more to do with items that should come from the classes they are using.

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , I am updating IWYU to get the latest changes in (currently we are using a year old version of it).

**Comment by davidlange6** [comment]
+1

**Pull request merged**
