### PR TITLE
L1T muon unpacker fix for crash with corrupt uGT RO record - 94x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #21665 

This addresses the issue https://github.com/cms-l1t-offline/cmssw/issues/642 
The L1T muon unpacker was crashing when encountering an event with a corrupt uGT readout record.
Throwing an exception if a corrupt RO record is encountered since this data should not be used.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
type bugfix

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
backport of #21665 

The bot seems to have not noticed that #21665 has been merged by now.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
