### PR TITLE
Restore fix for the segmentation violation in Phase2 workflow with darkening

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR restores the fix in #26964 then undone in #26966 as discussed by @deguio and @bsunanda.

#### PR validation:

The same fix was already integrated in CMSSW in May, and code compiles.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@bsunanda from private communication I understand that this PR is not needed and that the code present in CMSSW is the right one, could you please confirm/ If yes I will of course close this PR.

**Comment by bsunanda** [comment]
The code in the current master is the correct one. So this PR is not needed.

**Comment by fabiocos** [comment]
@bsunanda thank you for the confirmation

@deguio so I consider this issue as closed.

**Pull request closed without merging**
