### PR TITLE
Fix imaging algo for post tdr geometries

### PR DESCRIPTION
**Pull request by rovere**
In the ImagingAlgo code there were a few references to specific geometry layers that were lost while adopting the post TDR geometry.  This PR will make the code as geometry-independent as possible.

I'd expect no regression on workflows that use the TDR geometry and some regression on workflows that use the post TDR ones.

### CODE REVIEW

**Comment by rovere** [comment]
type bug-fix

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
@rovere @kpedro88 
regarding
> This PR will make the code as geometry-independent as possible.

does this refer to lastLayerFH not being specific to the underlying detector sensitive material?
The HGCalImagingAlgo implementation still has a few places depending on lastLayerFH.
Are these going to be cleaned up as well eventually?

**Comment by rovere** [comment]
@slava77 
The remaining references to lastLayerFH will likely remain since they are setting different critical distances in the different parts of the HGCAL due to the different material used as absorbers. Some further tuning of the clustering parameters will come soon, but they will likely keep this distinction.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24507	514fe1f
- code changes are in line with the PR description; the remaining dependence on lastLayerFH is not specific to the sensitive material according to https://github.com/cms-sw/cmssw/pull/24507#issuecomment-420903929
- jenkins tests pass and comparisons with the baseline show no differences as expected for the tests with the "old" geometry.

@kpedro88 
when should we expect a workflow with the new geometry to become the standard part of the jenkins tests?

**Comment by kpedro88** [comment]
@slava77 it's in the IB tests already. I have been waiting to add it to PR tests until all the known bugs were ironed out. Hopefully we're almost there.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
