### PR TITLE
Raw ADC value computation efficiency fix

### PR DESCRIPTION
**Pull request by yimuchen**
Originally the `getByToken` call for the digi collection when analyzing the on track clusters was listed in the `RecHitInfo` method. Since this is called per track, this makes the plugin very slow. 
This change proposes to move the `getByToken` call up in the stack to `trackStudy` method. For subsequent function calls, a `const edm::DetSetVector<SiStripDigis>&` is passed down the stack. 

Another proposed (but not implemented) change is to removed the methods `trackStudyFromTrack` and `hitStudy`, since these methods are never called.

### CODE REVIEW

**Comment by threus** [comment]
@enochnotsocool this PR is crashing the online DQM HLT client in 9_2_0. Could you please test it locally and fix the problem asap? I don't have the power to -1 it.

**Comment by davidlange6** [comment]
as to save people a mess - will this also crash the tier0?

**Comment by fioriNTU** [comment]
@enochnotsocool you pushed more than 250 commits :-) please rebase or use a more recent release

**Review by yimuchen — COMMENTED** [review]
Added control flow to use dummy (empty) digi list in case default collection doesn't exist. This was what was causing the crash in the HLT client, though a better solution might be to make the HLT client load the correct sequence?

**Comment by mtosi** [comment]
the HLT config needs to be updated as well,
because it is using a parameter which has been drop by this PR
please, add that fix as well, thanks

**Comment by enochnotsocool** [comment]
Done changing the HLT config file

**Comment by mtosi** [comment]
thanks

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
