### PR TITLE
Remove obsolete MessageLogger configuration options

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed obsolete fwkJobReports parameter
- removed deprecated messageIDs parameter
- removed obsolete FwkJob category

#### PR validation:

Code compiles and relevant framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
hold

This first requires #31856 #31864  and #31874  be merged before this can be merged

**Comment by Dr15Jones** [comment]
unhold

The remaining pull requests related to MesageLogger are configurations in test/ directories, but non of those configurations are used in any unit tests so should have no effect on this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
