### PR TITLE
Better Tau failure messages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Let the framework report and data product get errors.
- Change reporting problem with charge to use MessageLogger
- Fixed an argument dependent lookup problem with operator<<

The charge messages were showing up in the RelVal but were hard to spot.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
