### PR TITLE
[L1-O2O] make WriterProxyT to use ESGetToken

### PR DESCRIPTION
**Pull request by panoskatsoulis**
#### PR description:
Required modifications in the L1 O2O for making it work under 12_3 (and afterwards)
This PR contains the code structural related commits from https://github.com/cms-sw/cmssw/pull/37602 and drops the unit tests that will be implemented in separate PR
Also, it squashes some of the commits about code-checks

#### PR validation:
This is tested locally using the file
`L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-local.sh`
and also the sqlite included in the externals
https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/1
Test commands
```
./runL1-O2O-iov.sh -k uGT,uGTrs -d uGMT,EMTF,OMTF,BMTF,CALO 500000 l1_trg_cosmics2022/v43 l1_trg_rs_cosmics2020/v23
./runL1-O2O-iov.sh -d uGT,uGTrs -k uGMT,EMTF,OMTF,BMTF,CALO 600000 l1_trg_collisions2021/v6 l1_trg_rs_collisions2021/v22
```

### CODE REVIEW

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
@panoskatsoulis given that this is going well (1 pending and 10 successful checks), can you please prepare the backport PR? Or modify https://github.com/cms-sw/cmssw/pull/37601 so it doesnt have the tests? Thanks!

**Comment by panoskatsoulis** [comment]
@tvami yes, I'll start preparing it now
However, I thing after the latest changes the unit tests in the https://github.com/cms-sw/cmssw/pull/37602 will succeed now
if so, we might consider merge that one (and it ready backport)?
as it includes everything and we could eventually close this issue

**Comment by tvami** [comment]
+db
 * Jenkins test pass
 * this was tested locally, and the unit test testing is ongoing in CMSSW as well

**Comment by tvami** [comment]
@cms-sw/orp-l2 shall we bypass the L1T signature, given that the PR is from the L1T team?

**Comment by epalencia** [comment]
+l1

**Comment by panoskatsoulis** [comment]
the unit tests in https://github.com/cms-sw/cmssw/pull/37602 have succeed eventually and we were thinking to go with that one that was including the unit tests

now we will have conflicts I think

**Comment by perrotta** [comment]
@qliphy @panoskatsoulis : would you agree reverting this one and merging the "complete" PR instead, as soon as the tests succeed?

**Comment by perrotta** [comment]
> If you all agree in this plan I will force push update the other long PR with the final commits

Please go ahead with it now anyhow

**Comment by perrotta** [comment]
@panoskatsoulis I prepared a PR to revert this one in https://github.com/cms-sw/cmssw/pull/37692
However, there are no conflicts even if this one is merged, as you can see in #37602: in fact
- The "main" part is identical in this #37692 and in #37602, and therefore the don't conflict
- This #37692 has the additional test L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-local.sh
-  #37602 has the additional test L1TriggerConfig/L1TConfigProducers/scripts/runL1-O2O-scramTests.sh

Then, from the point of view of github there will be no conflict, even if we can still revert this one, with the only practical consequence that there will be no a L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-local.sh test any more.

Could you please remind me what was  that L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-local.sh meant for, and why it is not included any more in #37602?

**Comment by panoskatsoulis** [comment]
@perrotta 
`L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-local.sh` was moved to 
`L1TriggerConfig/L1TConfigProducers/scripts/runL1-O2O-scramTests.sh`

it's actually the same file, but an old version of it that was not being used for the unit tests yet

**Pull request merged**
