### PR TITLE
Run2-hcx158 Remove casting of some collections which was causing memory leaks

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
type bugfix
(for the already merged #20410, see discussion therein)

**Comment by bsunanda** [comment]
@smuzaffar @davidlange6 @slava77 The failure is not due to this PR. Please advise

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test
(the latest IB, CMSSW_9_4_X_2017-10-11-2300, should finally contain the fix for the issue in the RelVal wf 1000)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
