### PR TITLE
Add PRs with fixes in view of a possible CMSSW_13_0_3_patch2 release

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Following github issue https://github.com/cms-sw/cmssw/issues/41489
This PR backports in the CMSSW_13_0_3_patchHLT branch the following PRs, already merged in the HEAD of CMSSW_13_0_X:
- https://github.com/cms-sw/cmssw/pull/41454
- https://github.com/cms-sw/cmssw/pull/41473
- https://github.com/cms-sw/cmssw/pull/41484
- https://github.com/cms-sw/cmssw/pull/41402
- https://github.com/cms-sw/cmssw/pull/41368
- https://github.com/cms-sw/cmssw/pull/41400

The other PRs listed in that issue cannot, in my opinion, be considered that urgent; or alternatively they imply some larger updates than what is supposed for a quick fix that allows running at P5 during the (hopefully) few days needed to find a solution for the so far blocking issue https://github.com/cms-sw/cmssw/issues/41457

Before building 13_0_3_patch2 we can reconsider whether some additional PR could be further added here.

#### PR validation:

It builds
All PRs included here have been already successfully merged in the HEAD of CMSSW_13_0_X

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- release = CMSSW_13_0_3_patch1

**Comment by smuzaffar** [comment]
@perrotta , I am trying to setup an IB for this special build but for now you can test this PR using the last release/patch-release of 13.0.3. you can do it by either setting test parameters `release = CMSSW_13_0_3_patch1` or using `please test for CMSSW_13_0_3_patch1`

**Comment by perrotta** [comment]
please test
(it should work with https://github.com/cms-sw/cmssw/pull/41497#issuecomment-1532790371...)

**Comment by perrotta** [comment]
> @perrotta , I am trying to setup an IB for this special build but for now you can test this PR using the last release/patch-release of 13.0.3. you can do it by either setting test parameters `release = CMSSW_13_0_3_patch1` or using `please test for CMSSW_13_0_3_patch1`

Yes, it seems to work! Thank you @smuzaffar

**Comment by tvami** [comment]
+alca

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
Added also #41368: in the end, it only defines a new era, but it does not switch to it yet. It will be up to the users to decide whether to use it or not.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Further added #41400, see discussion in https://github.com/cms-sw/cmssw/issues/41489#issuecomment-1533467992 and before

**Comment by perrotta** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
https://github.com/cms-sw/cmssw/issues/41457 was found to be a non-issue.
This branch is therefore not needed any more: let continue the data taking releasce on the HEAD of the CMSSW_3_0_X cycle.
Closing this, then

**Pull request closed without merging**
