### PR TITLE
Update L1TCaloParams in 2022 and 2023 HI MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR updates the 2022 and 2023 realsitic HI MC GTs with the following latest `L1TCaloParams` tags, respectively:

- `L1TCaloParams_static_HI_2022_v0_05_mc_v1`
- `L1TCaloParams_static_HI_2022_v0_06_mc_v1` 
 
as requested in this [CMS Talk post](https://cms-talk.web.cern.ch/t/request-for-new-hi-mc-gts-with-updated-l1-parameters-for-heavy-ions-for-125x-and-131x/23153) [1]. 

[1] https://cms-talk.web.cern.ch/t/request-for-new-hi-mc-gts-with-updated-l1-parameters-for-heavy-ions-for-125x-and-131x/23153

**GT Differences with the last ones are here**:

- **Phase1 2022 realistic HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v5/131X_mcRun3_2022_realistic_HI_v7

- **Phase1 2023 realistic HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v7/131X_mcRun3_2023_realistic_HI_v9

#### PR validation:
GTs tested locally with `runTheMatrix.py -l 159.1,160.1 -j 10 --ibeos` which consume `auto:phase1_2022_realistic_hi` and `auto:phase1_2023_realistic_hi` keys

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport. A backport will be followed up in 130X for 2023 HI MC GT.

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
The errors in the tests are due to the fact that the new tags for MC don't have the correct IOV (i.e. `IOV != 1`), see:
 - https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloParams_static_HI_2022_v0_06_mc
 - https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloParams_static_HI_2022_v0_05_mc

We need to remake the tags with the proper IOV.

**Comment by francescobrivio** [comment]
@cmsbuild please abort

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+1

 - A few differences in the `L1T` directories of `312.0` which is the HI 2022 workflow - so I'd say that's expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
