### PR TITLE
Run3-sim97 Make use of ESGetToken in examples for SimG4CMS/Calo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in examples for SimG4CMS/Calo

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , the same question: is it thread safe or the test should work only in 1 thread?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Pull request merged**
