### PR TITLE
Enable Partial Sim/Reco Geometry Dump

### PR DESCRIPTION
**Pull request by ianna**
- Allow partial sim/reco geometry dump in TGeo and root formats. Useul for testbeam tests
- Add flags for Muon, Calo and Tracker dumps
- Ceanup obsolete geometry dump
- Add testbeam geometries
- Use appropriate conditions

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1
(if this is a new cmsbot feature, could it also remove the comparison-pending flag? @smuzaffar

**Comment by smuzaffar** [comment]
It should have properly updated the labels (i.e. removed comparison-pending lebal and add comparison notrun label), which I think it did (just re-tested :-) )

Not running matrix and comparison for Fireworks only PR is an old feature but now bot properly update the PR to inform why/what was not run

**Pull request merged**
