### PR TITLE
Add number of events, beginLumi's, and beginRun's to JobReport

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
One thing I noticed while testing this PR is that the Timing service (both before this PR and with this PR) does not work properly with SubProcesses. But even if we decide this problem is worth the development time to fix, I think that should be a separate pull request.

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
