### PR TITLE
Minor improvements for 2023 geometry dumping

### PR DESCRIPTION
**Pull request by kpedro88**
* update dumpRecoGeometry_cfg.py to specify 2023 version separately (already done in dumpSimGeometry_cfg.py)
* simplify printed list of 2023 versions
* fix typos

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by rovere** [comment]
With this PR + #24398 and #24397 the command:

```py
cmsRun Fireworks/Geometry/python/dumpRecoGeometry_cfg.py tag=2023 version=D28
```

still crashes(also with D19). I'd suggest to fix it and also to put some sort of tests for Fireworks only changes, since we had a bugged release since quite some times now.
cmsShowFF is also broken using D28 or D19 geometry, for the very same crash.

**Comment by kpedro88** [comment]
This PR is just to make the scripts more usable for Phase2. Whatever fixes are needed probably belong in #24398. (I haven't had time yet to test it.)

**Comment by alja** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
