### PR TITLE
Handling of @currentProcess at HLT (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Handling of @currentProcess at HLT (93X)
Based on CMSSW_9_3_X_2017-08-04-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
