### PR TITLE
Do not use a Task with SiPixelTemplateStoreESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The use of a Task at this time causes to much disruption. Moving ES modules to Tasks should wait till a dedicated campaign.

#### PR validation:

Ran unit tests for all packages changed plus all packages which had unit test failures in the IB. All tests now pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Alignment/CommonAlignmentMonitor, CalibTracker/SiStripChannelGain, CalibTracker/SiStripCommon, CalibTracker/SiStripHitEfficiency, CalibTracker/SiStripHitResolution, DQM/Integration, TrackPropagation/Geant4e

**Comment by Dr15Jones** [comment]
With these changes, the workflows 136.899, 138.1, and 138.2 now succeed.

**Comment by mmusich** [comment]
fwiw, with https://github.com/mmusich/cmssw/commit/d8dda074006eead43ac5a480722331acd41ec6ca all the unit tests that failed in [CMSSW_13_3_X_2023-08-17-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc11/www/thu/13.3-thu-11/CMSSW_13_3_X_2023-08-17-1100?utests) do succeed:

<details>
  <summary>Summary</summary>
  
```console
Pass  109s ... CalibTracker/SiStripCommon/testCalibTrackerSiStripCommon
Pass  133s ... CalibTracker/SiStripHitResolution/testSiStripHitResolution
Pass  117s ... CalibTracker/SiStripHitEfficiency/testSiStripHitEfficiency
Pass  138s ... CalibTracker/SiStripChannelGain/testSSTGainPCL_fromRECO
Pass    1s ... CalibTracker/SiStripChannelGain/checkMultiRunHarvestingOutput
Pass  233s ... CalibTracker/SiStripChannelGain/testSSTGainPCL_fromCalibTree
Pass   58s ... Alignment/CommonAlignmentMonitor/testAlignmentStats
Pass   52s ... Calibration/TkAlCaRecoProducers/testAlCaHarvesting
Pass  142s ... Calibration/TkAlCaRecoProducers/testBeamSpotWorkflow
Pass   71s ... DQM/Integration/TestDQMOnlineClient-beam_dqm_sourceclient
Pass   10s ... DQM/Integration/TestDQMOnlineClient-beamhlt_dqm_sourceclient
Pass   68s ... DQM/Integration/TestDQMOnlineClient-beampixel_dqm_sourceclient
Pass   66s ... DQM/Integration/TestDQMOnlineClient-csc_dqm_sourceclient
Pass   45s ... DQM/Integration/TestDQMOnlineClient-ctpps_dqm_sourceclient
Pass   53s ... DQM/Integration/TestDQMOnlineClient-dt4ml_dqm_sourceclient
Pass   50s ... DQM/Integration/TestDQMOnlineClient-dt_dqm_sourceclient
Pass   77s ... DQM/Integration/TestDQMOnlineClient-ecal_dqm_sourceclient
Pass   12s ... DQM/Integration/TestDQMOnlineClient-ecalgpu_dqm_sourceclient
Pass   44s ... DQM/Integration/TestDQMOnlineClient-es_dqm_sourceclient
Pass   52s ... DQM/Integration/TestDQMOnlineClient-fed_dqm_sourceclient
Pass   54s ... DQM/Integration/TestDQMOnlineClient-gem_dqm_sourceclient
Pass   64s ... DQM/Integration/TestDQMOnlineClient-hcal_dqm_sourceclient
Pass   12s ... DQM/Integration/TestDQMOnlineClient-hcalgpu_dqm_sourceclient
Pass   50s ... DQM/Integration/TestDQMOnlineClient-hcalreco_dqm_sourceclient
Pass   32s ... DQM/Integration/TestDQMOnlineClient-hlt_dqm_clientPB
Pass   55s ... DQM/Integration/TestDQMOnlineClient-hlt_dqm_sourceclient
Pass   40s ... DQM/Integration/TestDQMOnlineClient-info_dqm_sourceclient
Pass   54s ... DQM/Integration/TestDQMOnlineClient-l1tstage2_dqm_sourceclient
Pass   60s ... DQM/Integration/TestDQMOnlineClient-l1tstage2emulator_dqm_sourceclient
Pass   51s ... DQM/Integration/TestDQMOnlineClient-mutracking_dqm_sourceclient
Pass    8s ... DQM/Integration/TestDQMOnlineClient-onlinebeammonitor_dqm_sourceclient
Pass  202s ... DQM/Integration/TestDQMOnlineClient-pixel_dqm_sourceclient
Pass    9s ... DQM/Integration/TestDQMOnlineClient-pixelgpu_dqm_sourceclient
Pass   47s ... DQM/Integration/TestDQMOnlineClient-pixellumi_dqm_sourceclient
Pass   40s ... DQM/Integration/TestDQMOnlineClient-rpc_dqm_sourceclient
Pass   35s ... DQM/Integration/TestDQMOnlineClient-scal_dqm_sourceclient
Pass  118s ... DQM/Integration/TestDQMOnlineClient-sistrip_dqm_sourceclient
Pass  141s ... DQM/Integration/TestDQMOnlineClient-visualization
Pass  137s ... DQM/Integration/TestDQMOnlineClient-visualization_secondInstance
Pass   46s ... TrackPropagation/Geant4e/testG4PropagatorAnalyzer
Pass   54s ... TrackPropagation/Geant4e/testG4Refitter
Pass   40s ... TrackPropagation/Geant4e/testG4SimplePropagator
```

</details>

**Comment by mandrenguyen** [comment]
+1

**Comment by tvami** [comment]
I'd prefer to do https://github.com/mmusich/cmssw/commit/d8dda074006eead43ac5a480722331acd41ec6ca personally. Is there any disadvantage of doing that?

**Comment by Dr15Jones** [comment]
The HLT can't use the Task mechanism so this makes everything consistent. Plus this is the only place in CMSSW beyond the framework tests that uses Tasks for EsProducers.

**Comment by Dr15Jones** [comment]
This also fixed the failing RwlVal tests as well.

**Comment by emanueleusai** [comment]
+1

- also ok with https://github.com/mmusich/cmssw/commit/d8dda074006eead43ac5a480722331acd41ec6ca

**Comment by mmusich** [comment]
> Plus this is the only place in CMSSW beyond the framework tests that uses Tasks for EsProducers.

I am confused by the somewhat contradictory statement of this with respect to [this](https://github.com/cms-sw/cmssw/issues/40544#issuecomment-1670094796).

> The HLT can't use the Task mechanism so this makes everything consistent. 

if that's the case, can't at least the unit tests (standalone configuration files) maintain the `Task`?

**Comment by perrotta** [comment]
please test workflow 136.899,138.1,138.2

**Comment by Dr15Jones** [comment]
@mmusich 

> if that's the case, can't at least the unit tests (standalone configuration files) maintain the Task?

They certainly can. The difficulty is when I put the Task into the central configurations. The way the system works is if an ES module appears in at least one Task in the Process, then the ES module will only be added to the job _if and only if_ that Task is on a Path (directly or indirectly) which is used in the Schedule. This change showed that there are a number of configurations in CMSSW which do not use the central configuration Sequences and instead just assemble the tracking ED modules by hand. Those configuration still loaded the central configuration to get the module definitions. It is that combination of loading the central configuration but hand building paths which leads to the problems being seen.

I only removed the use of Tasks in the unit tests so that the SiPixelTemplateStoreESProducer would be treated like every other ESProducer in the job.

**Comment by mmusich** [comment]
> I only removed the use of Tasks in the unit tests so that the SiPixelTemplateStoreESProducer would be treated like every other ESProducer in the job.

OK. I will follow-up on https://github.com/cms-sw/cmssw/pull/42592 once this PR is merged.

**Comment by tvami** [comment]
+alca

**Comment by Dr15Jones** [comment]
ping

these changes fix the problems seen in the IB.

**Comment by perrotta** [comment]
+1
- Needed to fix the IBs: let merge
- Please @cms-sw/fastsim-l2 complain if you don't agree with the changes in FastSimulation/Configuration/python/Reconstruction_BefMix_cff.py

**Comment by perrotta** [comment]
merge

**Pull request merged**
