### PR TITLE
Add nConstituents to fat jets.

### PR DESCRIPTION
**Pull request by laurenhay**
#### PR description:
For use with AK8 PF Candidate jet tables.

#### PR validation:
Trivial inspection. See jetTable.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

#32927
In case Heavy Ion workflows need this variable.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@laurenhay please update this according to master

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by qliphy** [comment]
+1

**Pull request merged**
