### PR TITLE
Add run3 PCL pps alignment relval

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

This PR adds run3 relval for PCL pps alignment calibration.

#### PR validation:

relval 1045

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 12_4 will follow.

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type new-feature, pps

**Comment by ChrisMisan** [comment]
test parameters:

- workflows=1045

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
@cms-sw/upgrade-l2 do you have any comments about this?

**Comment by srimanob** [comment]
+Upgrade

New workflow 1045 runs fine.

Questions: I look on the log file of workflow 1045, and see the following message sometimes:
```
%MSG-e CTPPSPixelDataFormatter:   CTPPSPixelRawToDigi:ctppsPixelDigisAlCaRecoProducer 15-Aug-2022 14:25:23 CEST  Run: 355207 Event: 106498
 unphysical col and/or row  nllink=12 nroc=2 adc=0 col=8 row=80
%MSG
```
Is it known issue, normal?

**Comment by bbilin** [comment]
+pdmv

**Comment by perrotta** [comment]
> +Upgrade
> 
> New workflow 1045 runs fine.
> 
> Questions: I look on the log file of workflow 1045, and see the following message sometimes:
> 
> ```
> %MSG-e CTPPSPixelDataFormatter:   CTPPSPixelRawToDigi:ctppsPixelDigisAlCaRecoProducer 15-Aug-2022 14:25:23 CEST  Run: 355207 Event: 106498
>  unphysical col and/or row  nllink=12 nroc=2 adc=0 col=8 row=80
> %MSG
> ```
> 
> Is it known issue, normal?

@ChrisMisan @cms-sw/ctpps-dpg-l2 : could someone investigate and answer this question, before we merge this PR and it gets forgotten?

**Comment by ChrisMisan** [comment]
@perrotta Question was relayed to the PPS experts but I don't have any conclusive answer at this moment. I'll try to follow up on this possible issue on Monday.

**Comment by tvami** [comment]
@perrotta I agree that it should be followed up. On the other hand this PR is just what revels the problem, it's not caused by it or will be fixed in it, so I'd suggest to merge this and possibly make an issue out of the msg (although given that the PPS experts know about it, that might even be unnecessary )

**Comment by perrotta** [comment]
+1
- Opened issue https://github.com/cms-sw/cmssw/issues/39124 to keep track of the resolution of the issue reported in https://github.com/cms-sw/cmssw/pull/39059#issuecomment-1219743725

**Pull request merged**
