### PR TITLE
Manage PluginFactory plugins with smart pointers in Fireworks

### PR DESCRIPTION
**Pull request by makortel**
This PR is preparatory work to change the PluginFactory to return a `std::unique_ptr`.

Tested in CMSSW_10_5_X_2019-01-23-1100, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
@makortel the headers checker shows that unique_ptr is not declared:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25810/32919/headers_chks.log

so in FWDetailViewBase an "#include <memory>" should be added to fix this I would say

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@makortel the issue with that check is that it gives from time to time false positives due to crashes of the tool, so I understand that @smuzaffar was reluctant to use it too strictly. Anyway if you inspect the test results page the presence of errors is reported

**Comment by fabiocos** [comment]
@alja I would assume this is still ok for you, the fix was minimal and technical

**Comment by fabiocos** [comment]
@alja could you please sign it again or comment in case?

**Comment by fabiocos** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
