### PR TITLE
o2o tools fixes and improvements for python3

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

- Fix for python3 handling of workflow output
- Various improvements in the supported functions

#### PR validation:

Local testing
Integration tests

Backport of https://github.com/cms-sw/cmssw/pull/34848
Required to operate online workflows

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
@ggovi could you please remind me what's the purpose for this backport? There is no python3 enforcement in 12_0_X. is this fixing anything in 12_0_X? The new tests script added could be useful for possible future online runs with 12_0_X?

**Comment by qliphy** [comment]
@ggovi  Would you please address above comments?

**Comment by ggovi** [comment]
@perrotta To my knowledge, the python3 migration happened in 120X.  And in fact, several functions of the concerned script are currently broken in 120X. In addition, the new functions will be desirable for the online operations, which will presumably be carried out with 120X in the near future...

**Comment by perrotta** [comment]
+1
- Updated/new scripts and functions will be used in future online operations with 12_0_X

**Pull request merged**
