### PR TITLE
Fastsim: cleanup HLT configuration

### PR DESCRIPTION
**Pull request by lveldere**
Remove a bunch of files and modules that are no longer used.
Change a few filenames and module names to make clear they belong to hlt.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by Martin-Grunewald** [comment]
-1

Error in FastSim:

```
----- Begin Fatal Exception 22-Jan-2016 13:00:13 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 7
   [1] Running path 'HLT_Mu7p5_Track2_Jpsi_v2'
   [2] Calling event method for module PixelVertexProducer/'hltPixelVerticesL3Muon'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Track>
Looking for module label: hltPixelTracks
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by lveldere** [comment]
Weird, I thought I fixed that.
Can you send me the cmsDriver command?

**Comment by Martin-Grunewald** [comment]
800pre5 + PR + 
```
# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: TTbar_Tauola_13TeV_cfi --step=GEN,SIM,RECOBEFMIX,DIGI,L1,L1Reco,RECO,HLT:GRun --fast --conditions=auto:run2_mc_GRun --custom_conditions= --fileout=FastSim_GenToHLT_GRun_MC.root --number=100 --mc --no_exec --datatier GEN-SIM-DIGI-RECO --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --era=Run2_25ns --customise= --scenario=pp --python_filename=FastSim_GenToHLT_GRun_MC.py --processName=HLT
```

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
