### PR TITLE
Qualified make_shared in GaussianSumUtilities.icc

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
title does not match code change...

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass
. Indeed, title should rather be something like "Qualified make_shared in GaussianSumUtilities.icc"

**Comment by davidlange6** [comment]
hi @Teemperor - please update the title as suggested

**Comment by davidlange6** [comment]
-1
pending requested changes

**Comment by perrotta** [comment]
@davidlange6 : maybe we don't need to waste resources and relaunch the tests, given that only the title got changed...

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical

**Comment by davidlange6** [comment]
merge

**Pull request merged**
