### PR TITLE
Run3-sum105 Add a utility function to print all solids with their shape type

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a utility function (PrintGeomSolids) in SimG4Core/PrintGeomInfo to print all solids with their shape type

#### PR validation:

Use the test cfg's in SimG4Core/PrintGeomInfo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by perrotta** [comment]
> @perrotta Please merge this PR and I shall clean it up by moving all classes which are plugins to move to plugins directory

@bsunanda and why not profiting of this PR to make that (presumably simple) move? Or at least to already create a \plugin area so far missing in the package and start populating it with this plugin: as such the possible forthcoming PR with the migration will be even more straightforward

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
