### PR TITLE
DD Extruded Polygone

### PR DESCRIPTION
**Pull request by ianna**
* Implement DDL Extruded Polygone which is defined in XML as follows:
```
    <ExtrudedPolygon name="extrudedpgon">
      <XYPoint x="-30*cm" y="-30*cm"/>
      <XYPoint x="-30*cm" y=" 30*cm"/>
      <XYPoint x=" 30*cm" y=" 30*cm"/>
      <XYPoint x=" 30*cm" y="-30*cm"/>
      <XYPoint x=" 15*cm" y="-30*cm"/>
      <XYPoint x=" 15*cm" y=" 15*cm"/>
      <XYPoint x="-15*cm" y=" 15*cm"/>
      <XYPoint x="-15*cm" y="-30*cm"/>
      <ZXYSection z="-60*cm" x="0*cm" y="30*cm" scale="0.8*cm"/>
      <ZXYSection z="-15*cm" x="0*cm" y="-30*cm" scale="1.*cm"/>
      <ZXYSection z="10*cm" x="0*cm" y="0*cm" scale="0.6*cm"/>
      <ZXYSection z="60*cm" x="0*cm" y="30*cm" scale="1.2*cm"/>
    </ExtrudedPolygon>
```

@bsunanda - FYI, please comment. The interface to G4ExtrudedSolid will come in a separate PR.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - the error looks unrelated to this PR:
```
----- Begin Fatal Exception 02-May-2017 18:56:18 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PrimaryVertexValidation label='PVValidation'
Exception Message:
MissingParameter: Parameter 'Tpurge' not found.
----- End Fatal Exception -------------------------------------------------

```

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@ianna What is the "scale" variable for zxy section

**Comment by ianna** [comment]
@bsunanda - it's a scale applied to each z section:
Extruded Polygon:

The extrusion of an arbitrary polygon (extruded solid) with fixed outline in the defined Z sections can be defined as follows (in a general way, or as special construct with two Z sections):

  
   G4ExtrudedSolid(const G4String& pName,
        std::vector<G4TwoVector> polygon,
           std::vector<ZSection> zsections)

   G4ExtrudedSolid(const G4String& pName,
        std::vector<G4TwoVector> polygon,
                          G4double     hz,
        G4TwoVector off1, G4double scale1,
        G4TwoVector off2, G4double scale2)
    

	
[Rotate the Picture]
In the picture:
image

poligon = {-30,-30},{-30,30},{30,30},{30,-30}, {15,-30},{15,15},{-15,15},{-15,-30}

zsections = [-60,{0,30},0.8], [-15, {0,-30},1.], [10,{0,0},0.6], [60,{0,30},1.2]

The z-sides of the solid are the scaled versions of the same polygon.
polygon 	the vertices of the outlined polygon defined in clock-wise order
zsections 	the z-sections defined by z position in increasing order
hz 	Half length in Z
off1, off2 	Offset of the side in -hz and +hz respectively
scale1, scale2 	Scale of the side in -hz and +hz respectively

**Pull request merged**
