### PR TITLE
Migrate `DiMuonMassBiasClient` mass bias histograms to profiles

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to migrate the underlying ROOT type of the di-muon mass bias ME produced by `DiMuonMassBiasClient` from being `TH1`-s to `TProfile`-s. This would solve the visualization issues when displaying these in the GUI overlaid with a previous run. 
I leave the possibility to produce histograms instead via a dedicated configuration flag, since that might be useful when run in standalone mode. Additionally I restrict the range of the &mu;&mu; pair  &Delta;&eta; for the Z→&mu;&mu; case.

#### PR validation:

I've run successfully the unit tests  of this packages via `scram b runtests_testDiMuonVertexMonitor use-ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but a backport to the data-taking release will be needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
I was trying to track down where the extra log lines came from given you just moved and duplicated the edm::LogPrint for the TH1 and TProfile cases so I would not expect any difference... Probably just spurious.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
