### PR TITLE
Fix the `ThroughputService` and `FastTimerService` DQM folders [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Include the information about whether Simultaneous Multi Threading (SMT) is enabled or disabled after the processor model name.

Fix the DQM folder used by the `ThroughputService` to take into account the processor model name (and the SMT status) if the corresponding flag is enabled.

#### PR validation:

The processor model name and the SMT status not appear correctly in the DQM folder names for the `FastTimerService` and `ThroughputService`:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40062 to 12.4.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #40062

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
urgent

Labelling this like the other PRs targeting the next 12_4_X release (this PR is relevant to online ops).
`CMSSW_12_6_X_2022-11-16-1100` includes this update, and doesn't show any issue related to it.

**Comment by perrotta** [comment]
+1

**Pull request merged**
