### PR TITLE
[CommonTools] move public header to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `CommonTools`

```
      1 src/CommonTools/RecoAlgos/src/TrackToRefCandidate.h
     51 src/CommonTools/Utils/src/ExpressionBase.h
     51 src/CommonTools/Utils/src/ExpressionPtr.h
      6 src/CommonTools/Utils/src/Grammar.h
    115 src/CommonTools/Utils/src/SelectorBase.h
     51 src/CommonTools/Utils/src/SelectorPtr.h
      1 src/CommonTools/Utils/src/returnType.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34729	22e8a34
- code changes are technical, in line with the PR description

**Comment by perrotta** [comment]
+1
- @cms-sw/analysis-l2 changes are technical, and jenkins tests report no differences

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
