### PR TITLE
nano test scripts in CMSSW

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

as discussed in #39452 the testing script for nano are being put in CMSSW to enable testing in PR integration

#### PR validation:

ran 
`runTheMatrix.py --what nano -l 2500.601 --site "" --job-reports
./inspectNanoFile.py 2500.311_mc106Xul17v2+TTbarMINIAOD10.6_UL17v2+NANO_mc10.6ul17v2+HRV_NANO_mc/step2.root -j 2500.311-size.json
./inspectNanoFile.py 2500.601_mc126X+TTBarMINIAOD12.6+NANO_mc12.6+HRV_NANO_mc/step2.root -j 2500.601-size.json

./get_timing_from_jobreport.py 2500.311_mc106Xul17v2+TTbarMINIAOD10.6_UL17v2+NANO_mc10.6ul17v2+HRV_NANO_mc/JobReport2.xml 2500.311-timing.json
./get_timing_from_jobreport.py 2500.601_mc126X+TTBarMINIAOD12.6+NANO_mc12.6+HRV_NANO_mc/JobReport2.xml 2500.601-timing.json

./compare_sizes_json.py -H -f md 2500.601 2500.311 --ref "./" --base "{}-size.json,{}-timing.json" >> NANO_report.md`

to get a markdown print out that should be displayed in the summary.
N.B: `--ref` should point to a directory where we have reference files for comparison

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @vlimant , I will update bot to run these and include the results in PR summary.

**Comment by smuzaffar** [comment]
@vlimant , if `PhysicsTools/NanoAOD/test/runtests.sh` is not needed then please also remove `PhysicsTools/NanoAOD/test/BuildFile.xml` ( which is using this `runtests.sh` script) and `PhysicsTools/NanoAOD/test/runtestPhysicsToolsNanoAOD.cpp`

**Comment by smuzaffar** [comment]
@vlimant , looks like `PhysicsTools/NanoAOD/test/dqmQualityTests.xml` file is needed see [cms-bot PR test results]( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-74a38f/28357/runTheMatrixNANO-results/2500.0_mc80X+TTbarMINIAOD8.0+NANO_mc8.0+HRV_NANO_mc/step3_mc80X+TTbarMINIAOD8.0+NANO_mc8.0+HRV_NANO_mc.log)

```
----- Begin Fatal Exception 19-Oct-2022 12:50:50 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=QualityTester label='nanoDQMQTester'
Exception Message:
A std::exception was thrown.
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cms-bot/1867/28357/CMSSW_12_6_X_2022-10-18-2300/poison/PhysicsTools/NanoAOD/test/dqmQualityTests.xml(1): expected <
----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
test parameters:
- enable = nano
- pull_request = cms-sw/cms-bot#1867

**Comment by vlimant** [comment]
+1
excellent ! many thanks @smuzaffar

**Comment by perrotta** [comment]
@vlimant @smuzaffar do I understand correctly that this PR can get merged even before https://github.com/cms-sw/cms-bot/pull/1867 is finalized? (I see there are still ongoing discussions in it)

**Comment by smuzaffar** [comment]
yes @perrotta

**Comment by vlimant** [comment]
from the scipts POV in this PR, things are final indeed.

**Comment by perrotta** [comment]
+1

**Pull request merged**
