### PR TITLE
Add 15GeV cut to electron seeds for HI workflow

### PR DESCRIPTION
**Pull request by harmonicoscillator**
Heavy Ions has seen some fake PF jets which have most of the their energy coming from a single PF electron candidate. Usually this candidate had a low Et ecal seed and a high-pt (fake) track. While this did not seem to hurt our jet energy resolution, it does mess up spectra measurements, where high pT fake jets really change the measurement.

@doanhien has been studying ways to reduce these fake PF electrons, and an easy cut we can add is a 15GeV cut on electron seeds. This significantly reduces the number of fake jets without significantly changing analysis-level electrons.

This PR should not change any pp workflows at all, only HI workflows. It will be followed up by a backport to 75X as well.

The cuts added to ecalDrivenGsfElectrons and gedGsfElectronsTmp are simply to silence a warning about inconsistent cuts at seed and ElectronProducer level, and make no physics difference in addition to the ecalDrivenElectronSeeds cut.

Some further plots and cross-checks:
1) Robustness of JER to cuts: https://twiki.cern.ch/twiki/pub/CMS/PhotonAnalyses2015/JERJES_pT80_PbPb_PFElecComp.pdf

2) Reduction of fake jets with this cut: https://hypernews.cern.ch/HyperNews/CMS/get/hi-general/2248/1/1.html

3) Analysis-level effects of these cuts: https://twiki.cern.ch/twiki/bin/view/CMS/PhotonAnalyses2015#2015_07_21_13_30_CET

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by richard-cms** [comment]
I tried to find the errorlog, but the step1 log for 4.53 is empty. Maybe just a DAS timeout?

**Comment by richard-cms** [comment]
The backport branch passes all tests (#10505) so I think this is probably a transient error.

**Comment by richard-cms** [comment]
Is there a way we can re-start the tests in this case?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10504 ffed6f2e401c12addeaac34ddb03d2f5dc53976f

Adding 15 GeV cut to electron seeds for HI to reduce fake rate for jets. There should be no change for pp workflows. The 75X version of this PR is #10505, which has already been approved by Reco. 

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-08-03-1600 show no significant differences for pp workflows. For the HI workflow 140.53, electron GSF tracks disappear, which, as discussed for #10505, is the desired and intended effect. Otherwise there are very small differences as expected from the reduction in fake electrons and jets. See #10505 for further discussion and plots of the effects of this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
