### PR TITLE
bsunanda:Run2-gem10 Changes due to absent short chambers in GE21

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please start test

**Comment by bsunanda** [comment]
@cmsbuild Please test
________________________________

**Comment by smuzaffar** [comment]
@cmsbuild please test
@bsunanda , looks like you are not allow to start tests. So I have requested it

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
