### PR TITLE
10_2_X backport of PF HEM mitigation

### PR DESCRIPTION
**Pull request by gpetruc**
Backport of #24212 + #24367 + #24320
As said in the RECO meeting, we I don't know if we want to integrate this backport or not, but it's useful to have the PR in case we do.

### CODE REVIEW

**Comment by gpetruc** [comment]
type backport

**Comment by gpetruc** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24407	25d771d
- the joint backport is correct: changes are the same as a combination of #24212 + #24367 + #24320
- jenkins tests pass and comparisons with the baseline show no differences

@fabiocos @kpedro88 
This PR has additions in the data formats which fill hcal validity  booleans in electrons and photons.
Addition of a value was usually acceptable in the past as an exception for the policy for production releases.
We will need to change the prompt reco output version if a release with this PR is deployed at T0.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
