### PR TITLE
Add missing newlines in Conditions modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
CondCore/CTPPSPlugins
CondCore/EcalPlugins
CondCore/PhysicsToolsPlugins
CondCore/RunInfoPlugins
CondCore/SiPixelPlugins
CondCore/Utilities
CondFormats/BeamSpotObjects
CondFormats/DataRecord
CondFormats/EcalObjects
CondFormats/JetMETObjects
CondFormats/PPSObjects
CondFormats/RunInfo
CondFormats/SerializationHelper
CondFormats/SiPixelObjects
CondTools/BeamSpot
CondTools/CTPPS
CondTools/DT
CondTools/Ecal
CondTools/HLT
CondTools/L1Trigger
CondTools/RunInfo
CondTools/SiPixel
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by francescobrivio** [comment]
+db

**Comment by perrotta** [comment]
+1
- Technical, whitespace-only changes (+ code-checks adjustments)

**Comment by mmusich** [comment]
+hlt
   * only one README file changed in `CondTools/HLT`

**Comment by tvami** [comment]
+1

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
