### PR TITLE
Use auto generated `cfi` files in tracker alignment all-in-one validation tool

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR addresses the discussion at https://github.com/cms-sw/cmssw/pull/40677#issuecomment-1415295070 by providing `fillDescriptions` methods for all the plugins used in the tracker alignment all-in-one validation meta-tool and propagating the auto generated `cfi` files generated in this way to the various configuration files used in `cmssw`.

#### PR validation:

Relies on the existing unit tests.
Run successfully `scram b runtests use-ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * relevant unit tests pass

**Comment by perrotta** [comment]
+1

**Pull request merged**
