### PR TITLE
Added Residuals plots and fix monitoring plots for Pixel ClusterRepairs (backport)

### PR DESCRIPTION
**Pull request by arossi83**
#### PR description:

Some additional DQM plots to monitor Pixel ClusterRepairs (introduced in #26263) and small fix to already present ones (introduced in #26326)

#### PR validation:

Standard runTheMatrix sequence

#### if this PR is a backport please specify the original PR:

Backport of #26430

### CODE REVIEW

**Comment by fioriNTU** [comment]
@arossi83 are you sure this backport is needed at all?

**Comment by fioriNTU** [comment]
please test

**Comment by fioriNTU** [comment]
+1

**Comment by tocheng** [comment]
+1
Not sure whether the backport is needed. But the PR itself is fine for AlCa

**Comment by tocheng** [comment]
Not sure whether the backport is needed. But the PR itself is fine for AlCa

**Comment by fabiocos** [comment]
@arossi83 as agreed at last ORP this PR is no more needed and can be closed

**Pull request closed without merging**
