### PR TITLE
CTPPS: small corrections in the diamond DQM

### PR DESCRIPTION
**Pull request by forthommel**
backport of #18966
Small modifications in several plots of the diamond DQM source after first data.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by forthommel** [comment]
There might be a slight issue with the triggering of the integration tests, isn't it?

**Comment by dmitrijus** [comment]
please abort

**Comment by dmitrijus** [comment]
please test

**Comment by forthommel** [comment]
Just out of curiosity: is there still any plan to merge it at some point? :) Or is it preferable to close it?

**Comment by dmitrijus** [comment]
It should be merged. I don't know why it isn't.

**Comment by dmitrijus** [comment]
Ah, I do know now. It needs to target the 9_2_X branch.

**Comment by forthommel** [comment]
Hi @dmitrijus,
Actually, this PR was already merged in the `9_2_X` branch (#18966). However we were requested to open a `9_2_0_patchX` PR to ease its integration on the online DQM releases.
Maybe that this PR can be closed now?

**Comment by dmitrijus** [comment]
@forthommel If it is only for DQM online and is not supposed to be merged, please close it immediately after you open it. There is no need for me or the core to review it.

**Comment by davidlange6** [comment]
Again. Sorry, but no. Please use some other repo or make a request for a service you need.

**Comment by forthommel** [comment]
Thanks, @dmitrijus.
@davidlange6 I will get in touch with the online DQM experts to have a safer recipe for these integrations in the future.

**Pull request closed without merging**
