### PR TITLE
[106X] Cleanup lost dictionaries errors

### LINKED ISSUE #26222: Dictionary duplication
#26116 was supposed to fix a problem of dictionary duplication, but caused failures in a list of unit tests. The fix #26213 proposed by @smuzaffar was rejected as it was implying to have the definition of a type in one package and the corresponding dictionary in another one, following the comment by @slava77 : 

_"It also looks pretty bad to have a Wrapper dictionary defined in SimDataFormats/TrackingAnalysis while the underlying object stays defined here in DataFormats/RecoCandidate."_

This issue is meant to keep track of the problem and agree on an alternative solution.

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:
Resolves #26222

- Fix pat::UserHolder association for PatCandidates. In IBs we get dict lost definition errors like
```
Math : pat::UserHolder< ROOT::Math::SVector< double, 2 > >
Math : pat::UserHolder< ROOT::Math::SVector< double, 2u > >
```
- Moved `Phase2TrackerDigi` dictionaries in to DataFormats/Phase2TrackerDigi package
- Allow `edm::Wrapper.+edm::AssociationMap.+TrackingParticle` type dicts be in RecoCandidate instead of TrackingAnalysis

#### PR validation:

Build and run all unit tests which were failed in IB after the merge of #26116
```
---> test testmat succeeded
---> test testDDCompactView succeeded
---> test dumpDDCompactView succeeded
---> test dumpDDExpandedView succeeded
---> test edmCatalogFileLocator_t succeeded
---> test TestFWCoreIntegrationStandalone succeeded
---> test unitTestsGroup_1 succeeded
---> test unitTestsGroup_4 succeeded
---> test runtestPhysicsToolsPatAlgos succeeded
```

duplicate dict checkers also runs fine without any errors
```
> duplicateReflexLibrarySearch.py --lostDef
Searching for 'classes_def.xml' in '/build/muz/clean/CMSSW_10_6_X_2019-03-19-2300/src'.
**** SKIPPING './CondCore/Utilities/src/classes_def.xml' - Doesn't seem to have proper information.
```

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26224	f705f58
- technical; looks in line with the changes in #26116, taking into account the ensuing issues and review in the followup attempt in #26213
- jenkins tests pass

**Comment by fabiocos** [comment]
@rekovic @kpedro88 @Dr15Jones this version should circumvent previous problems

**Comment by kpedro88** [comment]
+upgrade

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@rekovic can you please sign it for L1?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@rekovic please sign it for future reference or comment for possible updates

**Comment by rekovic** [comment]
+1

**Pull request merged**
