### PR TITLE
from 768 to 512 strips for ME0 geometry

### PR DESCRIPTION
**Pull request by pietverwilligen**
change number of strips in ME0Geometry
to 512, the default for Muon TDR sample prod

### CODE REVIEW

**Comment by kpedro88** [comment]
@pietverwilligen do I understand correctly that this changes both M1 and M2? It might be preferable to make a separate instance of GEMSpecs.xml and change only M2...

**Comment by pietverwilligen** [comment]
No this is transparent to M1, since in M1 we use a PseudoDigitizer that does not read this number of strips.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1
No changes observed in comparisons (2023 PR test workflows all use M1)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
