### PR TITLE
Removal of unused DT DQM Online plots and LS label fixing

### PR DESCRIPTION
**Pull request by jfernan2**
- Remove unused folder 04-LocalTrigger-DDU in Online DQM
- Fix and remove no longer valid plots on DT / FEDIntegrity_EvF in Online DQM
- Fix LS labels in AverageEventLenght plots vs LS in Online DQM

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by boudoul** [comment]
hi @jfernan2 , could you please mention that it is for DT (as far as I can see) in the title of this PR (and the backport) , otherwise it's pretty hard to guess and keep track from the release notes , thank you

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
________________________________________

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
________________________________________

**Comment by jfernan2** [comment]
Backport was Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by fabiocos** [comment]
+1

**Pull request merged**
