### PR TITLE
Fixes for the neutron background simulation with GEANT

### PR DESCRIPTION
**Pull request by calabria**
@kpedro88 @pietverwilligen @jshlee @bapavlov

### CODE REVIEW

**Comment by kpedro88** [comment]
are the RPC fixes not needed in 91X?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by calabria** [comment]
@kpedro88 that fix is needed also in 91X but since there is a PR open for the RPC LinkBoard https://github.com/cms-sw/cmssw/pull/18578 I expect @bapavlov can update it accordingly.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
