### PR TITLE
Tracker Phase2Digitizer updated  memory leak

### PR DESCRIPTION
**Pull request by suchandradutta**
Memory leak reported in

 https://its.cern.ch/jira/browse/CMSTRACK-152 

DigitizerUtility::Amplitude is updated 

@boudoul @delaere @venturia

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@suchandradutta @civanch - this looks good to me - but has someone explicitly confirmed this fixes the memory leak identified by @slava77 ?

**Comment by slava77** [comment]
BTW, is there a PR for 82X?

**Comment by boudoul** [comment]
Hi @slava77 , I do not see the 82X queue on github ...

**Comment by slava77** [comment]
@boudoul there is a CMSSW_8_2_X branch https://github.com/cms-sw/cmssw/tree/CMSSW_8_2_X/  
What do you mean by the queue? Just IBs?

I started the job where I first have found the leak
vlimant_ACDC2_task_PPD-PhaseIIFall16GS82-00006__v1_T_170109_212702_4754/WMTaskSpace/logCollect1/0407b83c-d6b9-11e6-a223-001e67abef8c-0-0-logArchive
After 20 events processed in 900pre2+commit from this PR, the memory peak is 1GB smaller than it was at about the same time during processing in the baseline 820 release,
which is roughly consistent with removal of the average of 70MB/event leak I saw in 820.
So, this fix seems to be working.

**Comment by slava77** [comment]
.. after 90 events the difference in the mem peak is now 6.1GB, to reaffirm the impact of the fix.

**Pull request merged**
