### PR TITLE
Validation/Geometry: Tracker/HGCal Material Budget 'Other' Category fix [Backport]

### PR DESCRIPTION
**Pull request by vargasa**
Backport of https://github.com/cms-sw/cmssw/pull/25072

* This has been build on top of https://github.com/cms-sw/cmssw/pull/25139

Please note that commits: https://github.com/cms-sw/cmssw/pull/25072/commits/e7ccffaebc74eded01f9d313f834a3f27c6ef469, https://github.com/cms-sw/cmssw/pull/25072/commits/8c61b57e909e70969222dfd59d6ade6d45d026d5, and https://github.com/cms-sw/cmssw/pull/25072/commits/84d970869f4a9da395db725de112d2e55c6b9b24 were not included as it is better not to touch the file structure of the release as twiki documentation may relay on it

For details please check:
* https://github.com/cms-sw/cmssw/commit/24b5920d0dd9603af9b8f27a648d9fec7a368c6f#r31034588
* https://github.com/cms-sw/cmssw/pull/25072

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @vargasa, the changes between this PR and the forward-port seem to be different. The number of commits also don't match. Could you please take a look at it?

**Comment by vargasa** [comment]
@andrius-k as I pointed out in the description: Please note that commits: e7ccffa, 8c61b57, and 84d9708 were not included as it is better not to touch the file structure of the release as twiki documentation may relay on it

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi @vargasa, the back-port has 11 commits and the original PR has 7, out of which 3 were not back-ported. That means that only 4 commits in the back-port come from original PR. Where do the others come from? Maybe this is a back-port of few PRs?

**Comment by vargasa** [comment]
Hi @andrius-k. This is because this PR was written on top of another backport https://github.com/cms-sw/cmssw/pull/25139 which has not been merged yet (it is missing geometry and orp approval). There should be no problem with that. Maybe @cvuosalo could give us a hand approving #25139 if everything looks fine from his side

**Comment by andrius-k** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by vargasa** [comment]
@fabiocos Please check https://github.com/cms-sw/cmssw/commit/24b5920d0dd9603af9b8f27a648d9fec7a368c6f#r31034588.

FYI @andrius-k

**Comment by vargasa** [comment]
@kpedro88 this is needed. Again please check https://github.com/cms-sw/cmssw/commit/24b5920d0dd9603af9b8f27a648d9fec7a368c6f#r31034588 Or am I missing something?

It was also suggested by @andrius-k  https://github.com/cms-sw/cmssw/pull/25072#issuecomment-434826218

**Comment by kpedro88** [comment]
@vargasa so this is needed to fix a bug in the tracker material budget analysis? That analysis definitely needs to proceed with 10_3_X rather than 10_4_X?

**Comment by vargasa** [comment]
> @vargasa so this is needed to fix a bug in the tracker material budget analysis? 

Yes.

> That analysis definitely needs to proceed with 10_3_X rather than 10_4_X?

It is up to you guys to include it. Just keep in mind that if someone uses `Validation/Geometry/src/MaterialBudgetData.cc` as it is in 10_3_X they will be getting wrong results

**Comment by vargasa** [comment]
@fabiocos Could you please merge this as well? https://github.com/cms-sw/cmssw/pull/25139#issuecomment-437676829 also applies here

**Comment by fabiocos** [comment]
+1

**Pull request merged**
