### PR TITLE
Phase2-hgx342A Extend the muon tomography test code for dd4hep usage

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend the muon tomography test code for dd4hep usage

#### PR validation:

Use the scripts to do muon tomography test of HGCal using dd4hep version

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Update the test code, no change is expected from this PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
