### PR TITLE
Bug fixes to co-ordinate 90X and 91X pixel phase 1 summary maps

### PR DESCRIPTION
**Pull request by leggat**
Adding in a bug fix (summary maps crashed when expected MEs didn't exist) and removing an unnecessary file to bring PR https://github.com/cms-sw/cmssw/pull/17880 (91X, previously merged) in line with the 90X backport (https://github.com/cms-sw/cmssw/pull/18035) that is still pending.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
can someone merge this PR please?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
