### PR TITLE
Replacing adler32 with CRC32-C in FRD (raw data format) v5 - 75X

### PR DESCRIPTION
**Pull request by smorovic**
- correct unlock in input source at the end of the run
- "Failsafe" is set as JSON stream destination field in case of unsucessful determination with HLT menu and selected transfermode
- renamed reserved TCDS FED header variable to triggerTypeFlags
- support for Intel acceleration of CRC-32C with new FRD v5 (replaces adler32)

### CODE REVIEW

**Comment by mommsen** [comment]
+1

**Comment by Dr15Jones** [comment]
We already have a CRC algorithm in CMSSW, FWCore/Utilities/interface/CRC32Calculator.h. Is there a particular reason you can't use that one?

**Comment by mommsen** [comment]
@Dr15Jones Yes. We need to be able to calculate a checksum very efficiently on the builder unit. The most efficient way is to use the hardware implementation (SSE42) available in recent Intel Xeon CPUs.

**Comment by smorovic** [comment]
Also it is a different checksum. Intel supports CRC-32C which uses a different polynomial than "standard" CRC-32.

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
