### PR TITLE
DQM: migrate modules to esConsumes

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Part of #31061. This PR addresses some of the DQM modules mentioned in the static analyzer report of CMSSW_12_0_X_2021-06-20-2300.
#### PR validation:
Compiles and local static analyzer checks do not show Event setup get warnings.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA

### CODE REVIEW

**Comment by qliphy** [comment]
allow @sroychow test rights

**Comment by jfernan2** [comment]
Thanks for this PR @sroychow 
I see you are migrating several subsystem packages in this smae PR, could you please introduce your name and PR number in the spreadsheet to avoid duplication of work?
https://docs.google.com/spreadsheets/d/1cUypk2EK4xVcEpFGtaNqXrWZEoFz_E9l4gNN3YoBQH4/edit#gid=0
Thanks!

**Comment by sroychow** [comment]
@jfernan2 sure I plan to update the spreadsheet. I am working on a couple of more and then I will update it. Thanks!

**Comment by sroychow** [comment]
@cmsbuild  please test

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
@sroychow do you plan to add more changes?

**Comment by sroychow** [comment]
@jfernan2 no. I plan to follow up others in separate PRs.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
