### PR TITLE
Run4-hgx286X Accommodate a new parameter in the XML files for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Accommodate a new parameter in the XML files for hgcal geometry - needed for future version

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @sim

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Could you check and approve this PR at your earliest convenience?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Can you please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
