### PR TITLE
Followup request for TopMonitor

### PR DESCRIPTION
**Pull request by defranchis**
TopMonitor now inherits from the base class TriggerDQMBase. The output is restricted to relevant histograms based on the offline selection

### CODE REVIEW

**Comment by defranchis** [comment]
@fwyzard this should address all your comments. please let me know if you find any other issue

**Comment by defranchis** [comment]
@mtosi can we please test?

**Comment by mtosi** [comment]
thanks !
did you change the # bins ?
can you please summarize the effect of this PR in terms of # bins ?
(in addition, it would be really nice if you could briefly summarize the updates/developments you did in this PR)

btw, did you fix the small issue we saw this morning ?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by defranchis** [comment]
@mtosi yes I fixed it. The number of bins should be reduced now, I can make a more precise estimate if needed. I added a brief summary in the description

**Comment by mtosi** [comment]
please, please, quantify ;)
thanks !

**Comment by dmitrijus** [comment]
+1
any reduction is a good reduction :)

**Comment by defranchis** [comment]
@mtosi @fwyzard @dmitrijus I get no errors when I run on local. Can we please test again?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by defranchis** [comment]
@davidlange6 can you please review and sign?

**Comment by defranchis** [comment]
@davidlange6 can you please review?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
