### PR TITLE
Fix crash due to invalid track status

### PR DESCRIPTION
**Pull request by jhgoh**
There were some errors during cosmic muon reconstruction, division by zero.
Track propagation is skipped if the initial momentum of propagation is invalid in this PR.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@jhgoh please make PRs for 75X and 76X

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10867	80e0be1
- this, somewhat a stop-gap fix to protect against bad/nan tracks
    -  resolves the crash in run: 254306 lumi: 63 event: 46657536 reported in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1380 (I checked it locally as well)
    - a similar crash in run: 254332 lumi: 576 event: 621204229 in PromptReco_Run254332_JetHT  is also fixed
- jenkins tests pass and comparisons with baseline show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
