### PR TITLE
updates to consider DCS information

### PR DESCRIPTION
**Pull request by threus**
SiStripMonitorCluster will fill the cluster trend plots even if the DCS flag is false.
Added DCS filter to TrackingMonitor.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@threus - contrary to what was said in the 80x build, the error in workflow 1001 is certainly related to this PR:

#3  0x00007fd01925b02b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-29-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007fcfeac1d509 in SiStripMonitorCluster::analyze(edm::Event const&, edm::EventSetup const&) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-04-29-2300/lib/slc6_amd64_gcc530/pluginDQMSiStripMonitorCluster.so
#6  0x00007fd01d91f2ea in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-04-29-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so

**Comment by davidlange6** [comment]
@threus - should we close this PR while you are looking into the problem?

**Pull request closed without merging**
