### PR TITLE
fix headers in RecoBTag/DeepFlavour

### PR DESCRIPTION
**Pull request by mrodozov**
Fix headers related to #15248

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
hold

this will interfere with two more PRs changing these files and my request to move/rename the package

**Comment by slava77** [comment]
@mrodozov 
you can see the changes in #23033

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
@mrodozov : please rebase, taking into account the modifications introduced by #23033

**Comment by slava77** [comment]
unhold

**Comment by slava77** [comment]
-1

needs rebase/update

**Comment by smuzaffar** [comment]
@mrodozov , can you please rebase this?

**Comment by mrodozov** [comment]
this PR https://github.com/cms-sw/cmssw/pull/23518 has all the changes needed for RecoBTag now, closing this

**Pull request closed without merging**
