### PR TITLE
[124X] Fix double counting in HepMC to G4 handoff

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39427

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39427

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39427

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
hold
- Pending the validation campaign in master described in https://its.cern.ch/jira/browse/PDMVRELVALS-165

**Comment by perrotta** [comment]
unhold

According to the discussion in https://its.cern.ch/jira/browse/PDMVRELVALS-165 I plan to:
- merge this #39440 in 12_4_X (SIM, not affecting data taking)
- build CMSSW_12_4_9_patch1 (to be used for data taking)
- revert #39440 in the head of 12_4_X
so that pdmv can prepare the samples to validate #39440.

**Comment by perrotta** [comment]
+1

**Pull request merged**
