### PR TITLE
bsunanda:Run2-hcx61 Make the 2023Dev Geometry configuration for the HGCal V7 version

### PR DESCRIPTION
**Pull request by bsunanda**
This should work on top of bsunanda:Run2-hcx60

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda - looks like this breaks the unit tests in RecoLocalCalo/HGCalRecProducers and SimCalorimetry/HGCalSimProducers

Running script: /build/dlange/CMSSW_8_0_X_2016-01-03-1100/src/SimCalorimetry/HGCalSimProducers/test/runtests.sh
----- Begin Fatal Exception 04-Jan-2016 13:33:11 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/dlange/CMSSW_8_0_X_2016-01-03-1100/src/SimCalorimetry/HGCalSimProducers/test/testHGCalDigi_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named hgcalV6ParametersInitialization_cfi

**Comment by ianna** [comment]
@davidlange6 - this PR should be taken after #12862 is in. This will fix the problem.

**Comment by davidlange6** [comment]
lets add 12862 to this PR then..

**Comment by ianna** [comment]
@davidlange6 - I can only do the opposite, e.g. ad this one to 12862 - Sunanda will be back in a couple of weeks. Or, we can wait until 12862 is in and then integrate this one.

**Comment by ianna** [comment]
@lgray - shall I rebase it or you'd wait for Sunanda to do it?

**Comment by lgray** [comment]
It's two commits, please go ahead and rebase.

**Comment by ianna** [comment]
@davidlange6 and @bsunanda - Please, close this PR and use #12908 with fixed conflict instead.

**Comment by ianna** [comment]
-1

**Pull request closed without merging**
