### PR TITLE
Run3-sim85 Change HF ShowerLibrary Producer by Lev

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Change HF ShowerLibrary Producer by Lev

#### PR validation:

Use runTheMatrix test workflow 11634

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
A **tiny** difference appeared in HF in many workflows, which may not be a problem per se.

**Comment by civanch** [comment]
@bsunanda , I am confused: a) these classes are not used in mainstream simulation, so regression should 100%; b) there are somewhere hidden symbols - in truth number of differences is much less.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by davidlange6** [comment]
is the reason for all the whitespace changes understood?

**Comment by bsunanda** [comment]
I believe the files concerned are unchanged files for a long time before application of any code check. That might have left lots of white spaces. I have no other explanation.

**Comment by civanch** [comment]
@bsunanda , in past I faced the same problem when take a file from e-mail - it is identical but diff shows differences in each line.

**Comment by makortel** [comment]
Could it be different line endings, DOS (`\r\n`) vs Unix (`\n`)?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
Thank you, Sunanda! 👍🏻

**Comment by civanch** [comment]
> 
> 
> Could it be different line endings, DOS (`\r\n`) vs Unix (`\n`)?

I think so.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
