### PR TITLE
Use FormulaEvaluator for JER

### PR DESCRIPTION
**Pull request by kpedro88**
Brief history lesson:
* #11584: custom (stateless, thread-safe and -efficient) `FormulaEvaluator` used for JECs
* #16283: static warning fixed in JER use of `TFormula`: required copying `TFormula` each time `JME::JetResolutionObject::evaluateFormula()` is called

It turns out copying `TFormula` objects is really slow. Using a stateless evaluator should be much faster.

I modified the `JetResolutionObject` to use `FormulaEvaluator` (preserving `TFormula` for the "standalone" case). I had to add support for `sqrt` and `abs` functions in the parser.

I tested this in my ntuple code and observed a 100x speedup in the `evaluateFormula()` function, with no changes in JER-related quantities in 5000 ttbar events.

Before:
```
            8.5  .........      45.81 / 399.31       edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) [14]
[30]        8.5      45.81       0.00 / 45.81      @{pluginPhysicsToolsPatUtils_plugins.so+813138}
            8.4  .........      45.17 / 52.64        JME::JetResolutionObject::evaluateFormula(JME::JetResolutionObject::Record const&, JME::JetParameters const&) const [27]
            0.1  .........       0.64 / 0.76         JME::JetResolution::getResolution(JME::JetParameters const&) const [1106]
```

After:
```
            0.2  .........       0.88 / 329.62       edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) [14]
[975]       0.2       0.88       0.00 / 0.88       @{pluginPhysicsToolsPatUtils_plugins.so+813138}
            0.1  .........       0.50 / 0.55         JME::JetResolution::getResolution(JME::JetParameters const&) const [1230]
            0.1  .........       0.37 / 0.40         JME::JetResolutionObject::evaluateFormula(JME::JetResolutionObject::Record const&, JME::JetParameters const&) const [1483]
```

This PR will be backported to 94X for analysis use.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
On 5/1/18 2:52 PM, Kevin Pedro wrote:
> I tested this in my ntuple code and observed a 100x speedup in the
> |evaluateFormula()| function, with no changes in JER-related quantities
> in 5000 ttbar events.
> 

Faster is good.
Does this cover all JER parameterizations on the market?
The other history lesson is that there was a lot of grief caused by
issues using the FormulaEvaluator due to either missing method coverage
or incorrect parsing of particularly creative formulae.

**Comment by slava77** [comment]
On 5/1/18 3:23 PM, Kevin Pedro wrote:
> Yes, I recall those difficulties.
> 
> The only formula in |Spring16_25nsV6_MC.db| that gave trouble was:
> |'sqrt([0]*abs([0])/(x*x)+[1]*[1]*pow(x,[3])+[2]*[2])'|. I updated the
> parser to handle it (second commit here).
> 
> I looked through all the text files in
> https://github.com/cms-jet/JRDatabase and these are the unique headers:
> 
> |{1 JetEta 1 JetPt sqrt([0]*[0]/(x*x)+[1]*[1]/x+[2]*[2]) phi_resolution}
> {2 JetEta Rho 1 JetPt [0]+[1]*exp(-x/[2]) Resolution} {2 JetEta Rho 1
> JetPt sqrt([0]*abs([0])/(x*x)+[1]*[1]*pow(x,[3])+[2]*[2]) Resolution} {2
> JetEta Rho 1 JetPt sqrt([0]*abs([0])/(x*x)+[1]*[1]*pow(x,[3])+[2]*[2])
> resolution} |
> 
> (the last two are the same formula, just different binning)
> 
> I can add unit tests for these several varieties of formulas to ensure
> they're supported.
> 

does this cover the 2016 legacy JES sown last week in ppd?

**Comment by kpedro88** [comment]
Yes, `Summer16_25nsV1_MC` is in JRDatabase.

**Comment by kpedro88** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23106	4a4479a
- changes in the reco category are rather transparent: additions to handle sqrt and abs methods
- jenkins tests pass and comparisons show no differences (ignoring random diffs)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
