### PR TITLE
[XPOG] [CLANG] Fix warnings reported by clang-16

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes unqualified call warning in CLANG IBs for xpog.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please abort

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+xpog

**Comment by perrotta** [comment]
+1

**Pull request merged**
