### PR TITLE
Run3-gex75 Backport 3 PR's to remove overlaps for preshower using assemblies

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport 3 PR's #33735, #33788 and #33840 to remove overlaps for preshower using assemblies

#### PR validation:

Use the runTheMatrix test workflow 11634.911

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport #33735, #33788 and #33840 which are integrated with the master branch

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch Tested the 2 PR's in the master branch. It looks good and I can summarize them in the next simulation meeting. So I have submitted the backport

**Comment by cvuosalo** [comment]
@bsunanda #33735 that added the assemblies was not backported yet. Please revise the title and text of this PR to say that three PRs are being backported here, and check that all of #33735 is included.

**Comment by bsunanda** [comment]
@cvuosalo One also was removed in #33735 which I did not at first. Now I have. The other changes in #33735 was the use of assembly and that was already there in the earlier porting

**Comment by cvuosalo** [comment]
@bsunanda Please update the PR title and mention assemblies in the title.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
