### PR TITLE
Turning on channel quality fetching from db

### PR DESCRIPTION
**Pull request by igv4321**
Turning on database access in HF reco for the channel quality table

### CODE REVIEW

**Comment by igv4321** [comment]
backport of #18778

**Comment by perrotta** [comment]
@igv4321 : CMSSW_9_1_X is for muon TDR upgrade changes only (while CMSSW_9_2_X for data taking)
Do you really need this backport?

**Comment by igv4321** [comment]
In this case, not really.
How do I figure out which release is used for data taking?

**Comment by davidlange6** [comment]
most recent update was here:

https://hypernews.cern.ch/HyperNews/CMS/get/relAnnounce/1817.html

(which I notice was forwarded to hcal performance hn)

**Comment by igv4321** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/relAnnounce/1817.html
refers to CMSSW_9_1_X. Andrea instead says that CMSSW_9_2_X is for data taking. Who is right?

**Comment by davidlange6** [comment]
did you actually read the post? or is this somehow needed for the CTPPS run that was supposed to happen tonight?

**Comment by igv4321** [comment]
OK, thanks, all is clear now

**Pull request closed without merging**
