### PR TITLE
Update of the Zmumu validation tool, pull request to master branch

### PR DESCRIPTION
**Pull request by cardinia**
This pull request was originally made to a wrong branch by mistake (https://github.com/cms-sw/cmssw/pull/25159). The current version takes into account the comments and suggestions received in the discussion regarding the previous pull request.

Description:
@connorpa @adewit 
Implemented features:
2D plots Mass vs EtaPhi of muon (plus or minus)
Plotting options regarding the Y axis range in 1D histograms

Features presented in:
https://indico.cern.ch/event/768246/#72-latest-developments-of-vali
https://indico.cern.ch/event/688851/#sc-28-2-improvement-of-z-valid

### CODE REVIEW

**Comment by pohsun** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
