### PR TITLE
add CDC Tracks to TkAlCosmics0T ALCARECO

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In view of upcoming work foreseen on the Cosmics During Collisions (CDC) reconstruction, we add to the regular Tracker Alignment cosmics AlcaReco `TkAlCosmics0T` these tracks in order to have them produced during standard interfill, so that these can be used as "standard candle" for reconstruction optimization.
We provide also additional DQM monitoring for the newly added track collection.

#### PR validation:

This branch has been extensively used for privare re-recos of 2018 Data (see presentations from @skeshri [here](https://indico.cern.ch/event/879451/contributions/3873497/attachments/2045049/3425922/FollowUp_Cosmics_during_Collisions.pdf) and [here](https://indico.cern.ch/event/879450/contributions/3858868/attachments/2036865/3410575/CosmicsduringCollisionsDev.pdf) ) and also has gone through more technical validation via:

```
runTheMatrix.py -l 7.0,7.1,7.2,7.21,7.22,7.23,7.3,7.4 --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, but these changes will be backported to 11_1_0.
cc:
@mtosi @connorpa @vbotta

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test workflow 7.0,7.1,7.2,7.21,7.22,7.23,7.3,7.4

**Comment by jfernan2** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
