### PR TITLE
Get rid of unused variables in reco particle flow pf tracking

### PR DESCRIPTION
**Pull request by perrotta**
This PR addresses a couple of issues spot by the static analyzer in the RecoParticleFlow/PFTracking package, where some bool variable was computed but never used in the code flow afterwards.

While doing so, I also cleaned a bit the touched code in the PFElecTkProducer.cc

The code should work exactly the same as before: therefore any difference in output with respect to the baseline release must be seen as a bug in this implementation.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
No differences at all in jenkins tests (as expected)
@bachtis

**Comment by perrotta** [comment]
+1
- It removes unused variables, and makes some little adjustment likely able to save a few cpu cycles in the same places
- No differences in any of the jenkins tests (as expected)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
