### PR TITLE
new beamhlt dqm client

### PR DESCRIPTION
**Pull request by sikler**
New beamhlt_dqm_sourceclient-live_cfg.py.

It uses the stream is streamDQMOnlineBeamspot and consumes the objects from 
HLT: tracks are hltPFMuonMerging, vertices are hltVerticesPFFilter. Since HLT
provides no digis, only dqmBeamMonitor runs. The client is a much slimmed-down
version of the original beam_dqm_sourceclient-live_cfg.py.

There is a new DQM folder called BeaMonitorHLT, the client outputs folders Fit
and PrimaryVertex.

The client was tested on run several runs for proper functioning and timing
(4-5 per fits at the end of blocks with 10 LSs).

For further info please check:
https://twiki.cern.ch/twiki/bin/view/CMS/OnlineBeamSpot#23_June_2017_check_the_new_DQMOn

### CODE REVIEW

**Comment by sikler** [comment]
Marco tells me that BeamFitResultsHLT.txt as filename would work better for lines 63,64,67,69.

**Comment by sikler** [comment]
Broen proposes to choose different names
- folder: "TrackingBeamspotStream"
- application name: "trackingbeamspotstream"

**Comment by fwyzard** [comment]
Please review, in case comment, sign, and eventually deploy at P5.

**Comment by vanbesien** [comment]
It is already deployed at P5.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

B

**Comment by fwyzard** [comment]
Thanks !
I'll move further comments back on the email thread...

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
