### PR TITLE
VertexDQM: recenter y_vtx, increase range for nvtx

### PR DESCRIPTION
**Pull request by VinInn**
update for 2017 run conditions

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
xroot error...

@cmsbuild, please test

**Comment by davidlange6** [comment]
please test

indeed eos problems at cern...

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
