### PR TITLE
narrower anode time window switched to True

### PR DESCRIPTION
**Pull request by nvoytish**
Use a narrower anode time window to build CSC recHits.
The flag CSCUseReducedWireTimeWindow switched to True.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@ptcox @nvoytish 
please provide a link to slides or other documentation on the size of changes to expect from this PR.

**Comment by ptcox** [comment]
Reference for this mod is https://twiki.cern.ch/twiki/bin/viewauth/CMS/UFCSCLocalRecoStudy

**Comment by slava77** [comment]
On 2/15/17 6:58 AM, ptcox wrote:
> Reference for this mod is
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/UFCSCLocalRecoStudy

Thank you for the reference.
Does this configuration update propagate to cosmics modules as well?
If not, OK.
If yes, it probably shouldn't.

**Comment by ptcox** [comment]
No, it's OK for cosmics too. The detector is only ~2BX 'wide': if we 
trigger on cosmics in the bottom half of the CSCs then there are two 
time peaks - one at 0 from the hits in the bottom that trigger, and one 
at -50 ns from hits in the top, i.e that appear 2BX early.


Slava Krutelyov wrote:

**Comment by slava77** [comment]
Looking at the jenkins tests comparisons, I see no differences.
Do we expect any (over a few hundred MC and data events, not all with muons)?

The twiki is suggestive of some changes.

Looking in detail:
the twiki says ```  Use narrower wire time window for reconstruction, proposed wire time window is from 6-10  ```
The configuration currently in the code is 
```
    CSCWireTimeWindowLow = cms.int32(0),
     CSCWireTimeWindowHigh = cms.int32(15),
```

It looks like this PR is incomplete.

@nvoytish @ptcox 
please check and follow up

Thank you.

**Comment by ptcox** [comment]
That's pretty funny! Those UF people! They fooled me (us).
Well, looking on the bright side it confirms that with the window set as the original there are no differences.
Nikolay, could you change those 0, 15 to 6, 10 below?

Thanks,

Tim
________________________________

**Comment by nvoytish** [comment]
I changed the anode window to 6-10. 

Nikolay

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17521	33a3a20
- change is as described: to use smaller CSC hit wire time window
- jenkins tests pass and comparisons with baseline show small differences starting from CSC hits or segments and propagating to downstream quantities
- higher statistics tests roughly confirm the expected behavior described in https://twiki.cern.ch/twiki/bin/viewauth/CMS/UFCSCLocalRecoStudy
    - muon gun samples show about o(0.1%) reduction in muon reconstruction efficiency
    - ZMM with PU35 test shows no visible reduction in muon efficiency but shows a reduction in the number of fakes
    - other samples with pileup show reduction in muon fakes as well
    - data samples show decrease in CSC segment counts similar to what's seen in MC with pileup
- CSC segments become generally shorter with this PR, which is recovered by the changes in #17543 

On the technical side, as seen in ttbar PU35 sample (10224), there is on average 10% decrease in CPU time of muon reconstruction modules (standalone reco times are down by 30%) for a total of about 1% decrease in the full reco time.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
