### PR TITLE
HLT development for `12_3_X` + migration to `12_3_0_pre3` template

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

Includes the migration of all HLT configurations to the `12_3_0_pre3` template, and the integration of the following JIRA tickets:

 - [CMSHLT-2205](https://its.cern.ch/jira/browse/CMSHLT-2205): [MUO] GEMs in L2-muon producers
 - [CMSHLT-2209](https://its.cern.ch/jira/browse/CMSHLT-2209): [TAU] new TAU paths for Run-3 startup
 - [CMSHLT-2213](https://its.cern.ch/jira/browse/CMSHLT-2213): [BPH] removal of `HLTIterativeTrackingIteration1` sequence from BPH paths
 - [CMSHLT-2216](https://its.cern.ch/jira/browse/CMSHLT-2216): [BTV] update of `BTagMu` paths

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The bot reports an error for `relvals/input` which looks unrelated to this PR (looks like a file-access issue for 1 wf).

**Comment by missirol** [comment]
Modulo the unrelated problem with wf `4.76`, tests look okay and the comparisons appear consistent with the changes in the `GRun` menu.

The tests could be re-launched once the issue with wf `4.76` is solved.

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are compatible with changes in the HLT `GRun` menu;
 - the label `tests-rejected` is due to one unrelated problem with the inputs of wf `4.76` (if the latter is fixed, the tests could be restarted without resetting this signature; I sign because I do not anticipate changes to this PR).

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1
Relvals-INPUT failure unrelated to this PR.

**Comment by qliphy** [comment]
merge

**Pull request merged**
