### PR TITLE
seeding with Gem and ME0 Segments

### PR DESCRIPTION
**Pull request by jshlee**
same as #18625.

 * MuonSeedOrcaPatternRecognition - GEM and ME0 segments are added like CSC Segments for the seeding
 * MuonDetLayerMeasurements changed to give GEMRecHits or GEMSegments depending on input layer (chamber or superChamber)
   * Changes in MuonDetLayerMeasurements led to slight mods to other files

link to talk with performance (page 6)
https://indico.cern.ch/event/614702/contributions/2514657/attachments/1430929/2197998/muonReco_20170321.pdf

@calabria @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
from the ORP: this PR will have to be explicitly requested by the upgrade representatives to be included in 91X.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
445 lines is a large addition to the logs. I notice a number of these messages that do not appear in the baseline:
```
%MSG-w GEMHitAssociator:  MuonAssociatorEDProducer:tpToStaUpdMuonAssociation  12-May-2017 19:59:04 CEST Run: 1 Event: 1
*** WARNING in GEMHitAssociator::associateRecHit, null dynamic_cast !
```
@jshlee can you check on this?

**Comment by slava77** [comment]
On 5/12/17 2:12 PM, Kevin Pedro wrote:
> 445 lines is a large addition to the logs. I notice a number of these
> messages that do not appear in the baseline:
> 
> |%MSG-w GEMHitAssociator:
> MuonAssociatorEDProducer:tpToStaUpdMuonAssociation 12-May-2017 19:59:04
> CEST Run: 1 Event: 1 *** WARNING in GEMHitAssociator::associateRecHit,
> null dynamic_cast ! |
> 
> @jshlee <https://github.com/jshlee> can you check on this?

Thank you for noticing this.
It is an additional issue to be resolved before the PR can go in.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Comment by slava77** [comment]
On 5/17/17 2:33 AM, David Lange wrote:
> Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only
> (CMSSW_9_2_X for data taking)
> 

This was on the list of PRs for the muon TDR.

**Comment by kpedro88** [comment]
Originally it was, but then it seemed like it wouldn't converge in time.

It still might be wanted as a patch for a later round of production, but I don't know what release cycle would be used for that.

**Comment by davidlange6** [comment]
Right, its not on the list of yesterday. Anyway, sounds like we don't have a definite list yet (contrary to what was said yesterday). Lets revisit when we have one.

**Pull request closed without merging**
