### PR TITLE
The return values of gSystem->Load(library) can be 0 or 1.

### PR DESCRIPTION
**Pull request by gartung**
The current check for 0 causes an error when the return code is 1.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar @davidlt @davidlange6

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
are the exit codes documented someplace? (e.g., there are really no bad exit codes >1)

**Comment by gartung** [comment]
https://root.cern.ch/root/html604/TSystem.html#TSystem:Load

**Comment by Dr15Jones** [comment]
It does look like ROOT is using negative values for failures

**Comment by davidlange6** [comment]
+1
thanks

**Pull request merged**
