### PR TITLE
fix `SiPixelCompareTrackSoA` after portable data-format migration

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, address  https://github.com/cms-sw/cmssw/pull/40465#discussion_r1197560060 and https://github.com/cms-sw/cmssw/pull/40465#discussion_r1197561303.

#### PR validation:

`cmssw` compiles.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, to be backported to 13.0.X for data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by AdrianoDee** [comment]
Thanks Marco

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 12634.507, 12434.587, 12634.597 
- relvals_opt_gpu = -w upgrade,gpu,standard

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu

**Comment by AdrianoDee** [comment]
please test

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 can you sign urgently this simple bug-fix?

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
