### PR TITLE
Introduce `AlignmentTracksFromVertexCompositeCandidate` and new alca flavour `TkAlV0s`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

For alignment and momentum scale studies purposes, it would be interesting to have a distilled data-tier contain the information necessary to refit tracks from V0 decays. 
This PR add a new class `AlignmentTracksFromVertexCompositeCandidateSelectorModule` which allows to isolate and save the tracks and the associated rechits used to build a `VertexCompositeCandidate`.
This is consequently used to define a new ALCARECO data-tier called `TkAlV0s` which contains the tracks and associated clusters, etc. from $K^0_s$→ππ  and Λ→pπ decays. 
The canonical central files for running the production of this new producer at Tier0 (target dataset `HLTPhysics`) as well as provided dedicated DQM.
A stub analyzer is also provided to study the content of the output files. 

#### PR validation:

Tested with:

```
cmsDriver.py stepReAlCa --conditions 133X_mcRun3_2023_realistic_v3 -s ALCAPRODUCER:TkAlV0s,DQM:ALCARECOTkAlKShortTracksDQM+ALCARECOTkAlLambdaTracksDQM --datatier ALCARECO,DQMIO --eventcontent ALCARECO,DQM --mc --process REALCA --era Run3_2023 --scenario pp -n -1 --filein /store/relval/CMSSW_14_0_0_pre2/RelValTTbar_14TeV/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_RecoOnly-v2/2590000/085c6ebb-a997-4459-bd88-7308b6f66e3a.root --fileout file:outoput.root
```

followed by:

```
cmsDriver.py step4 -s HARVESTING:DQMNone --era Run3_2023 --conditions 133X_mcRun3_2023_realistic_v3 --mc --filetype DQM --scenario pp --filein file:outoput_inDQM.root -n -1
```

and studied the DQM output.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/alca-l2 @cms-sw/dqm-l2 this would be nice to have in CMSSW_14_0_0, can you have a look?

**Comment by perrotta** [comment]
+alca
- The effect of the addition of the new ALCARECO data-tier to the HLTPhysics dataset (rates, etc.) will be evaluated with the first T0 replay, expectedly with the forthcoming 14_0_0_pre3

**Comment by tjavaid** [comment]
+1

**Comment by perrotta** [comment]
urgent

**Comment by rappoccio** [comment]
+1

**Pull request merged**
