### PR TITLE
Addition of CaloSummary (CICADA) to L1 Emulation Sequences and Ntuples

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

This PR introduces the CaloSummary (CICADA) emualtion into L1 standard sequences by adding it to the L1TCalorimeter `simDigis` task. This is being done in preparation of integrating CICADA into the uGT (and uGT emulator) and in preparation for menu studies next year.

In addition, basic L1Ntuples infrastructure for looking at CICADA input and output have been added to the L1Ntuples as an emulator tree, taking by default it's input from the CaloL1Emulation, and the CICADA output by default from the CICADA emulation. Later, if desired, an non-emulator version of this tree could be run off an unpacked CICADA score and genuine tower regions in the raw data.

Some more slight tidying of the CaloSummary emulator has been down to remove ambiguity from other anomaly detection techniques by renaming variables/outputs from "anomaly" to "CICADA".

### PR validation:

All code compiles, passes tests, and has had code formatting applied. In addition, the addition of the CaloSummary to standard Sequences has been tested by running the standard L1 sequences `L1TReEmulFromRAW` (from `L1Trigger/Configuration/customiseReEmul`) and then the Ntuplization sequence `L1NtupleRAWEMU` (from `L1Trigger/L1TNtuples/customiseL1Ntuple`) on a file with RAW info available. This ran successfully, and an Ntuple with sensible information was produced.

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport and a backport will only be needed if L1/HLT trigger studies are performed on an earlier version of the emulator.

### CODE REVIEW

**Comment by aloeliger** [comment]
thought I checked this anyways...

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@epalencia It's probably bad form for me to sign my own stuff, for our developments, modifying central L1 sequences without you at least being informed. We're just starting to move the CICADA emulator into production here by adding it to the Calorimeter tasks for re-emulation, and we've added it into the emulator L1Ntuples for examination later. Anything you want us to hold on?

**Comment by epalencia** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
