### PR TITLE
Make BasicTrajectoryState thread safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
Modified BasicTrajectoryState so that it would be thread safe. This is needed because the class is used in Event data products.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I ran step 3 of 1325.1 in CMSSW_8_1_X_2016-10-10-2300 before and after making this change and did timing measurements. Doing module by module comparisons seems to show this made the code slightly faster. The modules with more than a 10^-5 second per event speed change are shown below:
```
detachedTripletStepTrackCandidates -0.00019 -1.24256%
displacedStandAloneMuons -0.000441 -4.86943%
earlyMuons -0.001622 -2.86583%
ecalMultiFitUncalibRecHit -0.000906 -2.67036%
ecalRecHit 0.000193 1.87297%
hbheprereco 0.000314 0.727003%
hcalDigis -0.000216 -5.29023%
hfreco 0.000112 3.28349%
initialStepTrackCandidates -0.000605 -1.24556%
initialStepTrackCandidatesPreSplitting -0.000638 -1.2669%
jetCoreRegionalStepTrackCandidates -0.001135 -3.96777%
pixelLessStepTrackCandidates -0.000268 -2.28688%
refittedStandAloneMuons -0.000195 -2.91676%
siPixelClustersPreSplitting -0.002649 -14.1374%
siPixelRecHitsPreSplitting -0.001423 -5.87495%
siStripClusters -0.000136 -2.68722%
siStripZeroSuppression -0.000149 -4.86849%
standAloneMuons -0.000155 -3.28494%
tobTecStepTrackCandidates -0.000285 -2.48117%
totemRPUVPatternFinder -0.000558 -15.9657%
tpClusterProducer 0.00012 1.93767%
trackExtrapolator -0.00039 -3.20724%
trackValidatorAllTPEfficStandalone -0.000849 -6.05801%
trackValidatorBuildingTrackingOnly -0.000554 -3.30076%
trackValidatorFromPVAllTPStandalone -0.00032 -1.84715%
trackValidatorFromPVStandalone -0.00133 -5.36225%
trackValidatorSeedingTrackingOnly -0.001125 -4.65212%
trackValidatorTrackingOnly -0.00351 -4.55886%
trackingParticleRecoTrackAsssociation -0.000119 -1.21101%
trackingParticlesSignal -0.000196 -6.51812%
```

**Comment by Dr15Jones** [comment]
please test

**Comment by VinInn** [comment]
-1
There is no evidence that this is needed.
This is relevant to HLT as well.
HLT timing has to be performed first.
Making TSOS and FTS able to be created w/o error was a non negligible improvements in timing

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@Dr15Jones @VinInn 
I'm waiting for a resolution of "-1" in https://github.com/cms-sw/cmssw/pull/16229#issuecomment-254123960
Please comment on your current understanding of needs of this PR
- should this solution go in
- is there an alternative solution
- is this PR needed at all

**Comment by Dr15Jones** [comment]
There is still discussion needed to determine the best way to solve the problem.

**Comment by VinInn** [comment]
did at least "fixed" the crash on KNL?

**Comment by slava77** [comment]
@Dr15Jones could you please confirm if this has fixed the problem on KNL.
Thank you.

**Comment by Dr15Jones** [comment]
We've been unable to reproduce the problem on the KNL system. Therefore we didn't apply the change to re-teste. Such is the life when trying to debug rare race-conditions.

**Comment by Dr15Jones** [comment]
I had done some timing measurements on this change:

Comparing RECO step for original and pull request:
```
Original
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 1.054108
TimeReport      event loop Real/event = 0.352345
TimeReport     sum Streams Real/event = 1.102154
TimeReport efficiency CPU/Real/thread = 0.747924
```

```
Pull request
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 1.033391
TimeReport      event loop Real/event = 0.349661
TimeReport     sum Streams Real/event = 1.076485
TimeReport efficiency CPU/Real/thread = 0.738851
```

So for RECO the pull request is actually faster. A module by module comparison shows the following largest changes in timing:
```
module label | timing change in seconds | fractional change
detachedTripletStepTrackCandidates -0.00019 -1.24256%
displacedStandAloneMuons -0.000441 -4.86943%
earlyMuons -0.001622 -2.86583%
ecalMultiFitUncalibRecHit -0.000906 -2.67036%
ecalRecHit 0.000193 1.87297%
hbheprereco 0.000314 0.727003%
hcalDigis -0.000216 -5.29023%
hfreco 0.000112 3.28349%
initialStepTrackCandidates -0.000605 -1.24556%
initialStepTrackCandidatesPreSplitting -0.000638 -1.2669%
jetCoreRegionalStepTrackCandidates -0.001135 -3.96777%
pixelLessStepTrackCandidates -0.000268 -2.28688%
refittedStandAloneMuons -0.000195 -2.91676%
siPixelClustersPreSplitting -0.002649 -14.1374%
siPixelRecHitsPreSplitting -0.001423 -5.87495%
siStripClusters -0.000136 -2.68722%
siStripZeroSuppression -0.000149 -4.86849%
standAloneMuons -0.000155 -3.28494%
tobTecStepTrackCandidates -0.000285 -2.48117%
totemRPUVPatternFinder -0.000558 -15.9657%
tpClusterProducer 0.00012 1.93767%
trackExtrapolator -0.00039 -3.20724%
trackValidatorAllTPEfficStandalone -0.000849 -6.05801%
trackValidatorBuildingTrackingOnly -0.000554 -3.30076%
trackValidatorFromPVAllTPStandalone -0.00032 -1.84715%
trackValidatorFromPVStandalone -0.00133 -5.36225%
trackValidatorSeedingTrackingOnly -0.001125 -4.65212%
trackValidatorTrackingOnly -0.00351 -4.55886%
trackingParticleRecoTrackAsssociation -0.000119 -1.21101%
trackingParticlesSignal -0.000196 -6.51812%
```

**Comment by Dr15Jones** [comment]
I also did measurement on an HLT step
```
Original 
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 3.791560
TimeReport      event loop Real/event = 1.047407
TimeReport     sum Streams Real/event = 3.778836
TimeReport efficiency CPU/Real/thread = 0.904988
```
```
Pull request
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 3.852293
TimeReport      event loop Real/event = 1.060482
TimeReport     sum Streams Real/event = 3.833574
TimeReport efficiency CPU/Real/thread = 0.908146
```
So about 1.3% slower.

The modules with the largest time shift
```
module label | time difference (sec) | fractional change
hltBLifetimeTagInfosPF 0.000289 13.8709%
hltDisplacedhltIter4PFlowCkfTrackCandidates 0.000261 13.9535%
hltEcalPreshowerRecHit 0.000487 69.7208%
hltEgammaElectronPixelSeeds -0.000147 -3.31118%
hltEgammaElectronPixelSeedsUnseeded 0.000272 3.00685%
hltEgammaGsfElectronsUnseeded -0.000157 -9.79108%
hltEgammaGsfTracks -0.000162 -1.47932%
hltEgammaGsfTracksUnseeded -0.00137 -3.85297%
hltGlbDiTrkMuons -0.00044 -2.06234%
hltGlbTrkMuons -0.000192 -1.17059%
hltGlbTrkMuonsNoVtx -0.000109 -0.483338%
hltHbherecoMethod2L1EGSeeded 0.000119 3.98593%
hltHbherecoMethod2L1EGUnseeded 0.000122 1.96521%
hltHighEtaEle20Selector -0.000149 -17.1166%
hltHighPtTkMuons -0.002365 -58.4167%
hltImpactParameterTagInfos 0.000282 13.7628%
hltInclusiveVertexFinder -0.000175 -2.17675%
hltInclusiveVertexFinderPF -0.000117 -1.03894%
hltIter0ElectronsCkfTrackCandidates 0.000164 1.82384%
hltIter0ElectronsCtfWithMaterialTracks 0.000138 2.58379%
hltIter0GlbDiTrkMuonCkfTrackCandidates 0.000117 5.52538%
hltIter0PFlowCkfTrackCandidates 0.000255 1.31793%
hltIter0PFlowCkfTrackCandidatesForPhotons 0.000196 1.28281%
hltIter0PFlowCtfWithMaterialTracks 0.000224 2.24922%
hltIter0PFlowCtfWithMaterialTracksForPhotons 0.000166 1.77502%
hltIter1DisplacedTau3muCkfTrackCandidates 0.000124 31.7949%
hltIter1GlbDiTrkMuonCkfTrackCandidates 0.000247 29.3175%
hltIter1GlbTrkMuonCkfTrackCandidates 0.000166 19.3248%
hltIter2ElectronsCkfTrackCandidates 0.000128 3.68982%
hltIter2GlbDiTrkMuonCkfTrackCandidates 0.000162 24.6575%
hltIter2GlbTrkMuonCkfTrackCandidates 0.000126 17.284%
hltL3DisplacedJets50FilteredFullTracksJetTagPro -0.000323 -108.208%
hltL3TrackCandidateFromL2OIStateNoVtx 0.000147 1.60999%
hltMuCkfTrackCandidates 0.000133 3.78971%
hltMuonsReg -0.000247 -1.03928%
hltPAIter0CkfTrackCandidates 0.000449 0.828666%
hltPAIter0CtfWithMaterialTracks 0.000334 1.27876%
hltPAIter1CtfWithMaterialTracks 0.000159 1.65496%
hltPAIter2CtfWithMaterialTracks 0.000112 2.05807%
hltPAIter3CtfWithMaterialTracks 0.000123 2.38441%
hltPAIter5CkfTrackCandidates 0.000297 2.0124%
hltPAJetsForCoreTracking 0.000166 112.162%
hltPAOnlinePrimaryVertices -0.000146 -1.05529%
hltParticleFlowBlock -0.000101 -2.1878%
hltParticleFlowBlockForTaus -0.000108 -2.31959%
hltSiStripMatchedRecHits -0.001496 -20.6174%
hltTrackVertexArbitratorPF 0.000227 10.7762%
hltVerticesPF -0.000201 -1.80552%
hltcorrPFMETTypeOne -0.000298 -15.1269%
mix -0.009998 -0.816732%
simBmtfDigis 0.000105 0.253406%
simCscTriggerPrimitiveDigis -0.00022 -5.98314%
simEcalDigis -0.000338 -2.42555%
simEcalTriggerPrimitiveDigis -0.001213 -2.74214%
simEmtfDigis -0.000142 -0.19856%
simHcalTriggerPrimitiveDigis -0.000393 -2.4287%
simMuonRPCDigis -0.009527 -9.35244%
simOmtfDigis 0.00055 7.33333%
```

**Comment by Dr15Jones** [comment]
The timing measurements were done using CMSSW_8_1_X_2016-10-10-2300 and step2 and step3 of workflow 1325.1_TTbar_13+TTbar_13+DIGIUP15+RECOUP15_trackingOnly+HARVESTUP15_trackingOnly

**Comment by VinInn** [comment]
@fwyzard , @mtosi

**Comment by fwyzard** [comment]
Thanks for the heads up.
I think I would need a bit more context to comment about it from the HLT side, though.

**Comment by Dr15Jones** [comment]
@fwyzard The BasicTrajectoryState code isn't thread safe since it updates internal caches in non-thread safe ways. Since we now can have multiple threads working on one Event we need to do something about this.

The change in this pull request does fix the thread-safety issues but may not be sufficiently performant. I have a new-to-CMS temporary worker who I plan on having look at alternative fixes for this class. However, I really could use some standard timing benchmark from you (Vincenzo pointed me to worfklow 1325.1 from his end) that we should run to check that any changes would not adversely affect HLT timing.

**Comment by slava77** [comment]
@fwyzard 
I'm currently holding signoff of this PR until the potential performance issue is resolved.
Please confirm that the tests reported earlier https://github.com/cms-sw/cmssw/pull/16229#issuecomment-258271102 are enough for HLT or suggest alternative checks.
Thank you.

**Comment by Dr15Jones** [comment]
hold

**Comment by Dr15Jones** [comment]
We should wait to evaluate what solution to use after my other person has a chance to try alternative implementations.

**Comment by fwyzard** [comment]
@slava77 the checks done above are good enough to spot the performance issue.
As for the configuration that should be used, `HLTrigger/Configuration/test/OnLine_HLT_25ns15e33_v4.py` or equivalently `cmsDriver.py test -s HLT:25ns15e33_v4 --data --conditions 80X_dataRun2_HLT_v12` should be fine, if run over some recent Run2016H high-ish pileup data.

**Comment by slava77** [comment]
@Dr15Jones 
please let me know if you are planning to check timing of this as suggested in https://github.com/cms-sw/cmssw/pull/16229#issuecomment-259677234

As long as this is on hold from your side, I do not see a need to check it in detail

**Comment by Dr15Jones** [comment]
@slava77 There isn't a need for you to do any detailed checking at this time. We will use the timing suggestions from Andrea when we start comparing alternate implementations.

**Comment by slava77** [comment]
On 11/14/16 11:24 AM, Chris Jones wrote:
> @slava77 <https://github.com/slava77> There isn't a need for you to do
> any detailed checking at this time. We will use the timing suggestions
> from Andrea when we start comparing alternate implementations.

OK, I'll wait until hold is removed.

**Comment by davidlange6** [comment]
for 90x

**Comment by Dr15Jones** [comment]
@fwyzard If you could get an appropriate Run2016H from mass storage and point us to it (where you picked an appropriate primary dataset) it would really help. I'm afraid my ability to find and retrieve files is nonexistent.

**Comment by fwyzard** [comment]
for example
/store/data/Run2016H/HLTPhysics/RAW/v1/000/283/408/00000/D85D53C2-DB95-E611-AEC4-02163E014331.root
which is on disk at CERN as
root://eoscms.cern.ch//store/data/Run2016H/HLTPhysics/RAW/v1/000/283/408/00000/D85D53C2-DB95-E611-AEC4-02163E014331.root
and should also be available on disk at FNAL - but I don't know the physical file name there.

**Comment by Dr15Jones** [comment]
@fwyzard Thanks! The AAA version appears to be accessible via
  root://cmsxrootd.fnal.gov///store/data/Run2016H/HLTPhysics/RAW/v1/000/283/408/00000/D85D53C2-DB95-E611-AEC4-02163E014331.root

**Comment by sabasehrish** [comment]
@fwyzard Chris and I are trying to run the command 

```cmsDriver.py test -s HLT:25ns15e33_v4 --data --conditions 80X_dataRun2_HLT_v12 --filein file:/uscms_data/d1/cdj/saba/D85D53C2-DB95-E611-AEC4-02163E014331.root
```
We are using CMSSW_9_0_0_pre1. Unfortunately the job failed with the following exception. 

```
----- Begin Fatal Exception 05-Dec-2016 13:13:35 CST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 283408
   [1] Running path 'HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v8'
   [2] Calling beginRun for module HcalHitReconstructor/'hltHbherecoMethod2L1EGSeeded'
Exception Message:
No "HcalFrontEndMapRcd" record found in the EventSetup for synchronization value
Run: 283408 LuminosityBlock: 0 Event: 0 Time: 6342562734978905856
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
Are you sure the job is using the right global tag?

**Comment by fwyzard** [comment]
Well, no, `80X_dataRun2_HLT_v12` was the global tag for 8.0.x.

In principle this should work:
`cmsDriver.py test -s HLT:25ns15e33_v4 --processName=reHLT --data --conditions auto:run2_hlt_25ns15
e33_v4 --filein /store/data/Run2016H/HLTPhysics/RAW/v1/000/283/408/00000/D85D53C2-DB95-E611-AEC4-02163E014331.root -n 100`

In practice it dies with
```
An exception of category 'LogicError' occurred while
   [0] Processing run: 283408 lumi: 29 event: 35440381
   [1] Running path 'MC_LooseIsoPFTau20_v5'
   [2] Calling event method for module CSCRecHitDProducer/'hltCsc2DRecHits'
   [3] Calling method for unscheduled module CSCRecHitDProducer/'hltCsc2DRecHits'
Exception Message:
trying to insert duplicate entry 
```

and I have no idea why is that...

**Comment by Dr15Jones** [comment]
I was able to get a working configuration using
```
cmsDriver.py test -s HLT:25ns15e33_v4 --era Run2_2016 --processName=reHLT --data --conditions auto:run2_hlt_25ns15e33_v4 --filein /store/data/Run2016H/HLTPhysics/RAW/v1/000/283/408/00000/D85D53C2-DB95-E611-AEC4-02163E014331.root -n 100
```

**Comment by sabasehrish** [comment]
My following configuration results in Error: 
```
cmsDriver.py test -s HLT:25ns15e33_v4 --era Run2_2016 --processName=resHLT --data --conditions auto:run2_hlt_25ns15e33_v4 --filein file:/uscms_data/d1/cdj/saba/D85D53C2-DB95-E611-AEC4-02163E014331.root
```
output 
```
06-Dec-2016 10:24:03 CST  Initiating request to open file file:/uscms_data/d1/cdj/saba/D85D53C2-DB95-E611-AEC4-02163E014331.root
06-Dec-2016 10:24:03 CST  Successfully opened file file:/uscms_data/d1/cdj/saba/D85D53C2-DB95-E611-AEC4-02163E014331.root
%MSG-e TkDetLayers:  TSGFromL2Muon:hltL3TrajSeedOIHit@streamBeginRun  06-Dec-2016 10:24:37 CST Run: 283408
 ForwardDiskSectorBuilderFromDet: Trying to build Petal Wedge from Dets at different z positions !! Delta_z = 0.800217
%MSG
Begin processing the 1st record. Run 283408, Event 35786526, LumiSection 29 at 06-Dec-2016 10:24:41.304 CST
Begin processing the 2nd record. Run 283408, Event 35644858, LumiSection 29 at 06-Dec-2016 10:24:48.722 CST
Begin processing the 3rd record. Run 283408, Event 35440381, LumiSection 29 at 06-Dec-2016 10:24:50.499 CST
Begin processing the 4th record. Run 283408, Event 35829754, LumiSection 29 at 06-Dec-2016 10:24:51.410 CST
Begin processing the 5th record. Run 283408, Event 35518705, LumiSection 29 at 06-Dec-2016 10:24:52.413 CST
Begin processing the 6th record. Run 283408, Event 35992180, LumiSection 29 at 06-Dec-2016 10:24:52.770 CST
Begin processing the 7th record. Run 283408, Event 35895559, LumiSection 29 at 06-Dec-2016 10:24:55.621 CST
Begin processing the 8th record. Run 283408, Event 35841417, LumiSection 29 at 06-Dec-2016 10:24:56.506 CST
Begin processing the 9th record. Run 283408, Event 35694720, LumiSection 29 at 06-Dec-2016 10:24:56.617 CST
Begin processing the 10th record. Run 283408, Event 35777538, LumiSection 29 at 06-Dec-2016 10:24:57.230 CST
06-Dec-2016 10:24:58 CST  Closed file file:/uscms_data/d1/cdj/saba/D85D53C2-DB95-E611-AEC4-02163E014331.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 TkDetLayers          -e TSGFromL2Muon:hl                       1        1
    2 fileAction           -s file_close                             1        1
    3 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 TkDetLayers          Run: 283408                       
    2 fileAction           PostEndRun                        
    3 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Error                   1                   1
System                  3                   3
```

**Comment by Dr15Jones** [comment]
@sabasehrish Actually, that job finishes just fine. Unfortunately, developers often report an Error in the log when in fact it isn't an error.

**Comment by sabasehrish** [comment]
@Dr15Jones Okay, and when I turn on the timing, I see non zero values. 
But how do I differentiate between an actual error and an Error in the log when intact it isn't an error?

**Comment by Dr15Jones** [comment]
If cmsRun returns a non 0 value, there was an error.

**Comment by sabasehrish** [comment]
Okay Thank you

**Pull request closed without merging**
