### PR TITLE
Camiielle/debug post rebase branch

### PR DESCRIPTION
**Pull request by camiielle**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mmusich** [comment]
is this PR needed / meant for central integration? Looks like it's starting from the wrong base branch (also there are merge conflicts).

**Comment by mmusich** [comment]
-hlt
   * to remove it from the list

**Comment by camiielle** [comment]
Hi! I opened the PR by mistake. My apologies!

**Comment by camiielle** [comment]
Hello, I opened the PR by mistake. My apologies!

**Pull request closed without merging**
