### PR TITLE
[DQMOffline/Trigger] [HLTriggerOffline/Top] cleanup of HLT-DQM sequences for Top

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR implements the cleanup of the HLT-DQM and HLT-Validation sequences for the Top PAG,
based on feedback received from the relevant contacts and validators.

The main sequences affected by this cleanup are `offlineHLTSourceOnAODextra` (DQM) and `hltvalidationWithMC` (Validation).

Two plugins are removed from `DQMOffline/Trigger` (DQM sequences), and the package `HLTriggerOffline/Top` (meant to cover HLT-Validation tools for Top) is removed as well.

The monitoring tools in `HLTriggerOffline/Top` do not provide any monitoring based on GEN objects,
and they do not bring additional information with respect to what is currently being monitored with the `TopMonitor` plugin in `DQMOffline/Trigger`. Even though this PR does not include a better validation plugin (for example, to provide monitoring with respect to GEN objects), I think it would already be good to start with this cleanup. A future (generic) validation plugin for HLT-Top can go under `HLTriggerOffline/Common/`, and I think there would be no need to keep a separate package (like the current `HLTriggerOffline/Top/`).

Two HLT-DQM modules of B2G were based on one of the plugins removed in this PR; these monitors have been updated to use a different plugin (`TopMonitor`); this maintains (and improves) the monitoring of those paths for B2G; the corresponding harvesting clients were updated accordingly.

Changes in the comparisons are expected from the removal of the HLT-Top folders listed in [1], and the aforementioned B2G updates (two sub-folders under `HLT/B2G/Dileptonic/*`).

[1]

`HLT/TOP/DiElectron/`
`HLT/TOP/DiMuon/`
`HLT/TOP/ElecMuon/`
`HLT/TOP/SemiElectronic/`
`HLT/TOP/SemiMuonic/`
`HLT/TOP/SingleTop/`
`HLT/TopHLTValidation/`

#### PR validation:

Tested with `runTheMatrix.py -l 11634.0`

#### if this PR is a backport please specify the original PR:

Not a backport, and no backport of this is planned.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by missirol** [comment]
@jfernan2 for what is worth, i checked the comparisons and didn't find anything unexpected

**Comment by jfernan2** [comment]
+1
Thanks @missirol for the confirmation, and yes I agree changes look consistent with your PR description

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar the core signature is required by the update of the release utility script

**Comment by smuzaffar** [comment]
+core

**Comment by fabiocos** [comment]
+1

**Pull request merged**
