### PR TITLE
Bugfix for MakeSherpaLibs and update of example cards

### PR DESCRIPTION
**Pull request by pmillet**
- fixed wrong naming of tarball when using -o LIBS in MakeSherpaLibs.sh
- this option is needed when using integration results from standalone Sherpa
- replaced deprecated example runcards with recent examples

### CODE REVIEW

**Comment by pmillet** [comment]
@cmsbuild, @govoni, @perrozzi, @thuer, @davidlange6 can you please review it and eventually sign?
Thanks.

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@pmillet can you confirm that this is all you need to complete the backport of sherpa 2.2.2 ?

**Comment by pmillet** [comment]
This fixes one naming issue when reusing results from standalone Sherpa. It is mainly needed for simplifying the instructions and independent of Sherpa 2.2.2.

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
can you please merge this PR and include it in the forthcoming 71X? thanks

**Comment by davidlange6** [comment]
Hi
what is the master branch PR for this?

**Comment by davidlange6** [comment]
ok, so we need a integrated/validated PR in the development release before this will be integrated

**Comment by pmillet** [comment]
see https://github.com/cms-sw/cmssw/pull/17887

**Comment by davidlange6** [comment]
that looks to be for 90x (which is not needed afaik)

**Comment by pmillet** [comment]
Ah ok. I thought that is what you meant. Where should I make a pull request then?

**Comment by davidlange6** [comment]
to the master branch (which is the default when you make a pull request to cmssw)

**Comment by pmillet** [comment]
https://github.com/cms-sw/cmssw/pull/17888

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
release-note:
fixed wrong naming of tarball when using -o LIBS in MakeSherpaLibs.sh
this option is needed when using integration results from standalone Sherpa
replaced deprecated example runcards with recent examples

**Pull request merged**
