### PR TITLE
Thread safe piliup histogram for mixing

### PR DESCRIPTION
**Pull request by civanch**
Addressing issue #21972 , implemented as suggested by @Dr15Jones .

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by Dr15Jones** [comment]
To avoid future problems, it would be nice to
   - change PileUp's constructor to take a `std::shared_ptr<const PileUpConfig>`
   - change PileUpConfig to hold a `std::shared_ptr<const TH1F>`

That will keep anyone from begin able to call a non-const function of the TH1F without first copying the histogram.

**Comment by fabiocos** [comment]
@civanch thank you for adjusting the PR, as it was already signed I take it.

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@Dr15Jones @civanch I have merged this PR as urgent fix, but I ask the simulation group to look at the further suggestions by Chris and propose an integration

**Comment by davidlange6** [comment]
one could imagine changing the constructor to take either the const array of PDF values from the PSet or the CDF that is actually used. There is really no need to have used a TH1* in the PileUp class (other than the desire to dump out a root file containing that histogram with each job we run in production...) as the usage is actually not of the histogram but of its CDF.

**Pull request merged**
