### PR TITLE
[13_1_x] PPS Pixel DQM: assign errors to right plots

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

This PR is a bug fix in filling the plots in PPS Pixel DQM. Using the DAQ map, errors coming from pixels are assigned to the right detector plane instead of being put in a unidentified-detector plot, unless strictly necessary.

#### PR validation:

With matrix wfs 138.4 (run3) and 136.874 (run2) and with brand new 2023 data. Errors are now put inside the right plots.

This fix is needed for the data taking asap.

This is a backport of PR #41649

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41649

**Comment by emanueleusai** [comment]
type ctpps

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
