### PR TITLE
Templated BVertex plugins (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #11381

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11411	 0842cbe
- the same technical change as in https://github.com/cms-sw/cmssw/pull/11381	d61c1f2
 to reimplement BVertex plugin as a template for future algorithm developments at analysis level 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by ferencek** [comment]
@davidlange6, this one missed several recent 74X releases. Please consider it for the next 74X release since it has no impact on either the standard reco or MiniAOD. The same is true for #11410. Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
