### PR TITLE
Remove the process name dependence for HCAL DPG skims (80X)

### PR DESCRIPTION
**Pull request by kfjack**
The process name was hard coded in the HCAL DPG skims (JetHTJetPlusHOFilter / PhotonJetPlusHOFilter). Remove this dependence. Back port from #18384.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
backport of #18384

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @kfjack @fabozzi - no one has brought it up so I'm assuming this is not important for the rereco. Please correct me if not the case.

**Comment by kfjack** [comment]
Hi @davidlange6 , there is a thread checking with the skim contacts if they really need the full re-reco data set with these two skims. Still under communication.

**Comment by davidlange6** [comment]
is a more difficult question than I expected - will merge this as its a simple change

**Pull request merged**
