### PR TITLE
[SIM] improved initialisation

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR is an attempt to fix issue #45747 , where both Geant4 warnings/exceptions and generator exceptions are reported. This PR making instantion of the main Geant4 singletons in the fix order, so less dependent on architecture. This update does not change CPU at initialisation and does not affect run time. The main effect avoid misleading printouts if there is a problem in a WF.

#### PR validation:
short matrix

### CODE REVIEW

**Comment by civanch** [comment]
@iarspider, @smuzaffar , please, try to test this PR at ASNEEDED_X. If G4 warnings will be gone I will add full description of this PR.

**Comment by iarspider** [comment]
@cmsbuild please test workflow 132.0,148.0,158.0,159.0 for CMSSW_14_2_ASNEEDED_X

**Comment by civanch** [comment]
@cmsbuild please test workflow 132.0 for CMSSW_14_2_ASNEEDED_X

**Comment by civanch** [comment]
@cmsbuild please test workflow 132.0 for CMSSW_14_2_ASNEEDED_X

**Comment by civanch** [comment]
Now Geant4 warnings/exceptions gone, it become clear that the problem is in generators.

**Comment by civanch** [comment]
please test

I would guess more tests in ASNEEDED not needed anymore.

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
