### PR TITLE
optimize some hotspot use cases of deltaR and polar in reco/miniAOD

### PR DESCRIPTION
**Pull request by slava77**
this was somewhat motivated by the report today in https://indico.cern.ch/event/921063/
More details followed from phase-2 PAT step CPU profiling https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/igprofCPU_CMSSW_11_1_0_pre6PAT/21

tested on data wf 136.88811 (re-miniAOD from UL) and rereco wf 136.888, showing no differences

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
time changes on 100 events in 136.88811
```
138.06 ms/ev ->         9.41 ms/ev patPFMet
138.61 ms/ev ->         9.66 ms/ev patMETs
50.22 ms/ev ->         3.64 ms/ev patPFMetPuppi
50.41 ms/ev ->         3.68 ms/ev patMETsPuppi
2.10 ms/ev ->         0.76 ms/ev patElectrons
64.01 ms/ev ->        29.74 ms/ev isolatedTracks
11.91 ms/ev ->         5.74 ms/ev patMuons
```

**Comment by slava77** [comment]
> time changes on 100 events in 136.88811
> 
> ```
> 138.06 ms/ev ->         9.41 ms/ev patPFMet
> 138.61 ms/ev ->         9.66 ms/ev patMETs
> 50.22 ms/ev ->         3.64 ms/ev patPFMetPuppi
> 50.41 ms/ev ->         3.68 ms/ev patMETsPuppi
> 2.10 ms/ev ->         0.76 ms/ev patElectrons
> 64.01 ms/ev ->        29.74 ms/ev isolatedTracks
> 11.91 ms/ev ->         5.74 ms/ev patMuons
> ```

the cost in MET is new, it was introduced after 11_1_0_pre5; the rest was around for a while.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29918	569cecc 
- jenkins tests passed with no differences

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
