### PR TITLE
Remove Track trigger from 2023D20  [93X]

### PR DESCRIPTION
**Pull request by boudoul**
Track trigger step no longer run on the 2023D20 (old flat phase2 tracker) 
Backport of #20687

### CODE REVIEW

**Comment by kpedro88** [comment]
@boudoul since #20492 is only in 94X, do we need this in 93X?

**Comment by boudoul** [comment]
A 93X backport of #20492 was made in #20592

-------- Original message --------

**Comment by kpedro88** [comment]
Ah, forgot about that.

**Comment by kpedro88** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
