### PR TITLE
tracking and strip DQM : trigger selection via DB + stage2 L1 handling in GenericTriggerEventFlag

### PR DESCRIPTION
**Pull request by mtosi**
back-port of https://github.com/cms-sw/cmssw/pull/14659
@fioriNTU @VinInn @rovere @slava77 @mmusich

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
please test

**Comment by mtosi** [comment]
sorry, the file DQM/TrackingMonitor/python/TrackingMonitor_cfi.py
got an update which is already merged in 81x, 
but it is still waiting for being integrated in 80x ...

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
I see that apparently there are some conflicts,
but I've just done

cmsrel CMSSW_8_0_X_2016-05-29-0000
cd CMSSW_8_0_X_2016-05-29-0000/src/
cmsenv
git cms-merge-topic 14660
scram b -j24

and it seems to work smoothly ... what am I missing ?

**Comment by makortel** [comment]
@mtosi The latest IB (CMSSW_8_0_X_2016-05-29-2300, also CMSSW_8_0_9) includes #14568, which by eye seems to conflict with this one.

**Comment by slava77** [comment]
-1
merge conflicts should be resolved

**Comment by mtosi** [comment]
close this PR,
the conflict should be fixed in the new PR https://github.com/cms-sw/cmssw/pull/14693
(I still not get why my last commit did not fix the issue, though)

**Pull request closed without merging**
