### PR TITLE
Responding to PR 24183 (Updating gridpacks for GEN related Rel-Val failures)

### PR DESCRIPTION
**Pull request by Saptaparna**
Updated to CMSSW master and includes my changes.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test workflow 562.0, 25210.0, 1360.0

**Comment by alberto-sanchez** [comment]
@Saptaparna looks like 25210 have some issues:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24268/29782/runTheMatrix-results/25210.0_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step1_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

**Comment by Saptaparna** [comment]
@alberto-sanchez Indeed, I also see the problem when testing interactively. The problem is with the ttbar gridpack and hence affects workflows 25210.0 and 1360.0.

Updating the gridpack to an ever more recent one (MG5 260) seems to solve the problem. Running local tests now.

**Comment by Saptaparna** [comment]
please test workflow 25210.0, 1360.0

**Comment by alberto-sanchez** [comment]
please test workflow 562.0, 25210.0, 1360.0

**Comment by Saptaparna** [comment]
@alberto-sanchez The tests are failing but I cannot seem to see what the error is. Are the errors still in the same workflows?

**Comment by alberto-sanchez** [comment]
@Saptaparna Yes both failed again. The problem seems related with the compiler see:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24268/29787/runTheMatrix-results/25210.0_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step1_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

**Comment by Saptaparna** [comment]
@alberto-sanchez I see that the old gridpack is being used again: /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.4.2/tt012j_5f_ckm_NLO_FXFX/v5/tt012j_5f_ckm_NLO_FXFX_tarball.tar.xz This explains what the errors were the same. Let me see what went wrong and why the gridpack was not updated.

**Comment by Saptaparna** [comment]
@alberto-sanchez It looks like the following commit was disregarded for this run:

https://github.com/cms-sw/cmssw/pull/24268/commits/b5edae7cf45d0b73ffae83c075d998304cdfc17a

Is there something I can do to fix this?

**Comment by alberto-sanchez** [comment]
@Saptaparna Looks like you need to modify Configuration/Generator/python/TTbar012Jets_5f_NLO_FXFX_Madgraph_LHE_13TeV_cfi.py
as well.

**Comment by Saptaparna** [comment]
@alberto-sanchez Thanks! I had a similar suspicion.

**Comment by alberto-sanchez** [comment]
please test workflow 562.0, 25210.0, 1360.0

**Comment by Saptaparna** [comment]
@alberto-sanchez Does this mean the PR can be merged?

**Comment by boudoul** [comment]
Dear @Saptaparna , please make an explicit title an better explanation,- we can't guess from this title if you are talking about HCAL , Tracker, Trigger, Generator, and what you changed .... Thank you

**Comment by Saptaparna** [comment]
@boudoul This PR is a response to some requests in  https://github.com/cms-sw/cmssw/pull/24183 and refers to workflows 562.0, 25210.0, 1360.0 that failed at the generator step. The problem was due to the presence of old gridpacks. The paths of the gridpacks have been updated and based on the last code check do not lead to crashes during Rel-Val production.

**Comment by boudoul** [comment]
I know , but we can't guess from  the title 'Responding to PR 24183', if you are talking about HCAL , Tracker, Trigger, Generator . 

The title of PRS are *very* important because intensively used by validators (for example) or to easily keep track of what is entering in a given release: it is what will appear in the release notes and we should know what is the topic of a PR by just reading it . 

So please edit the title [you can keep 'Responding to PR 24183' if you want in it]  but please add something more explicit in addition- The edit button is next to the title

**Comment by alberto-sanchez** [comment]
+1

**Comment by alberto-sanchez** [comment]
errors went away

**Comment by fabiocos** [comment]
@Saptaparna hmm, not really looking at the name: BulkGraviton_ZZ_inclu_narrow_M1200_slc6_amd64_gcc481_CMSSW_7_1_30_tarball

**Comment by fabiocos** [comment]
@Saptaparna @alberto-sanchez could you please clarify how these new gridpacks are solving the problem? I am pleased of the solution of the issue, but I would like to understand the sgtrategy behind. At some point we will need to discuss a global strategy valid in general

**Comment by Saptaparna** [comment]
@fabiocos Apologies for the slow response. The problematic gridpacks were the ones that did not include some of the new features in the runcmsgrid script (https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L20ToL42). The updated gridpacks were produced with newer versions of MadGraph (2.2.2 vs 2.4.2) and a new version for script referred to above. One thing to note is that even with MadGraph 2.4.2, the ttbar workflow repeatedly failed (investigating as why this happened, possibly that gridpack was corrupted for some reason). Updating the ttbar workflow to a MG5 2.6.0 gridpack fixed the problem. It maybe worth digging deeper to understand what worked in 260 that didn't work in 242. However, given the recent push to upgrade genproductions to 260 (branch 260 has existed for many months, but now 260 will be upgraded to master) in general may mean that soon 242 gridpacks may have only limited use.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
