### PR TITLE
[GCC13] Temporary convert array-bounds errors into warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

In order to start testing gcc13 IBs, temporary convert array-bounds errors into warnings. See also https://github.com/cms-sw/cmssw/issues/44582. 

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el9_amd64_gcc13

**Comment by iarspider** [comment]
please test for el9_amd64_gcc13

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
ignore tests-rejected with ib-failure

**Comment by iarspider** [comment]
`---> test runtestPhysicsToolsPatAlgos had ERRORS` - fails in IB, see https://github.com/cms-sw/cmssw/issues/33084

Build failres for gcc13 are unrelated, some of them are fixed by other PRs.

**Comment by aloeliger** [comment]
+l1
- technical PR

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
+1

**Comment by iarspider** [comment]
@cms-sw/dqm-l2 gentle ping

**Comment by rappoccio** [comment]
+1

Failures are unrelated to this PR

**Pull request merged**
