### PR TITLE
HLT menu development for `12_4_X` (9/N) [`12_6_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_5_X` and `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2471](https://its.cern.ch/jira/browse/CMSHLT-2471): [HIon] update of triggers for ultra-peripheral collisions (`HIForward` PD, still placeholders for L1T seeds)
  - [CMSHLT-2474](https://its.cern.ch/jira/browse/CMSHLT-2474): [TSG] fixes to PS values of 5 triggers (e.g. `HLT_ZeroBias_Alignment_v*`) 
  - [CMSHLT-2486](https://its.cern.ch/jira/browse/CMSHLT-2486): [BPH] new triggers with _dz_ requirement for double-electron parking
  - [CMSHLT-2487](https://its.cern.ch/jira/browse/CMSHLT-2487): [BPH] single-electron control trigger for double-electron parking triggers (currectly disabled, PS=0)
  - [CMSHLT-2488](https://its.cern.ch/jira/browse/CMSHLT-2488): [BPH] another single-electron control trigger for double-electron parking triggers (currectly disabled, PS=0)
  - [CMSHLT-2494](https://its.cern.ch/jira/browse/CMSHLT-2494): [EXO] fix to inclusive delayed-jet control trigger

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_12_4_X`
`CMSSW_12_5_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please abort

[All 3 GPU wfs](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a8a6c5/28120/runTheMatrixGPU-results/) failed with the following error:
```
----- Begin Fatal Exception 08-Oct-2022 08:11:31 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing service of type CUDAService
Exception Message:
A std::exception was thrown.

/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c1203ad0f844b94e556a08cd3c870f28/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_X_2022-10-04-2300/src/HeterogeneousCore/CUDAServices/src/CUDAService.cc, line 151:
nvmlCheck(nvmlInitWithFlags(NVML_INIT_FLAG_NO_GPUS | NVML_INIT_FLAG_NO_ATTACH));
NVML Error 18: Driver/library version mismatch
----- End Fatal Exception -------------------------------------------------
```
I'll try to restart the tests, in case it is a transient issue (I'd say it is clearly unrelated to this PR).

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - differences in the outputs of PR tests are in line with updates to the HLT GRun menu

**Comment by perrotta** [comment]
+1

**Pull request merged**
