### PR TITLE
[HeaderCheck][DB] Cleanup headers to avoid header inconsistency errors

### PR DESCRIPTION
**Pull request by smuzaffar**
Removed unused/unmaintained headers

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar not sure to understand your comment, could you please clarify?

**Comment by smuzaffar** [comment]
@fabiocos , sorry it was typo. I wanted to write `Removed unused/unmaintained headers`

**Comment by fabiocos** [comment]
+1

**Pull request merged**
