### PR TITLE
[GEM] bugfix - BC and OrbitCounter in AMC13 - backport

### PR DESCRIPTION
**Pull request by jshlee**
backport of #37340

### CODE REVIEW

**Comment by jshlee** [comment]
please test

**Comment by jshlee** [comment]
looks like a das error, can we test again please

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

The is a backport PR. Failure seen in comparison come from the message logger.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/37340

**Pull request merged**
