### PR TITLE
Phase2-gex13 Add a scenario where ME0 is replaced by GE0

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a scenario 2026D67 where ME0 is replaced with GE0. This however needs changes in the configuration for muon digitization and local reconstruction to eliminate usage of ME0

#### PR validation:

Partially tested runTheMatrix new workflow 31034.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Need additional fixes before utilizing this workflow in regular test

### CODE REVIEW

**Comment by bsunanda** [comment]
@watson-ij @dildick Please use the scenario 31034.0 to prepare Phase2 without ME0. Currently it looks for ME0ReDigiProducer in step2. Most likely you have to make a new ERA and integrate which eliminate that. Once you have that please let me know

**Comment by dildick** [comment]
@bsunanda Thanks for letting me know. I'll take care of this.

**Comment by dildick** [comment]
This may be a starting point https://github.com/dildick/cmssw/commit/86080c1bd224ae2996df189c6cb40a4a472fbd74

**Comment by bsunanda** [comment]
@dildick How can I merge my PR with this branch?

**Comment by dildick** [comment]
So I still need to test that. I think we also need a new era, like this:
```
+import FWCore.ParameterSet.Config as cms
+
+from Configuration.Eras.Era_Phase2_cff import Phase2
+from Configuration.Eras.Modifier_phase2_GE0_cff import phase2_GE0
+
+Phase2M9 = cms.ModifierChain(Phase2, phase2_GE0)
```

**Comment by kpedro88** [comment]
@dildick the top-level Era would need to start from `Phase2C11`

**Comment by dildick** [comment]
Right, so something like this ```Phase2M9 = cms.ModifierChain(Phase2C11, phase2_GE0)```. Sunanda, I can try to commit what I have. You can then cherry-pick the relevant commits and test it.

**Comment by kpedro88** [comment]
I suggest keeping all relevant info in the name, i.e. `Phase2C11M9`, in case somebody later wants to combine M9 with a different calorimeter

**Comment by dildick** [comment]
@bsunanda This is what I have so far: https://github.com/cms-sw/cmssw/compare/master...dildick:from-CMSSW_11_2_X_2020-09-22-1100-GE0-era?expand=1

**Comment by bsunanda** [comment]
@dildick @kpedro88 Sven could you make that PR and Kevin can you request a test the workflow by combining the 2 PR's?

**Comment by dildick** [comment]
See https://github.com/cms-sw/cmssw/pull/31542. Let's see if this works...

**Comment by kpedro88** [comment]
test parameters
pull_request = #31542

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please abort

**Comment by kpedro88** [comment]
test parameters
pull_request = #31542
workflow = 31034.0

**Comment by kpedro88** [comment]
please test

**Comment by dildick** [comment]
This should remove the pseudo ME0 digis and stubs. But I notice that we need to switch off the ME0 local reco sequence `me0LocalReco_cff`

**Comment by dildick** [comment]
That modification would have to be done here most likely https://github.com/cms-sw/cmssw/blob/master/RecoLocalMuon/Configuration/python/RecoLocalMuon_cff.py

**Comment by kpedro88** [comment]
please test

**Comment by dildick** [comment]
@bsunanda You may need to replace ME0 with GE0 hits in the mixing module for phase2_GE0 scenarios. Or should I do that?

```
----- Begin Fatal Exception 23-Sep-2020 03:08:26 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<PSimHit>
Looking for module label: g4SimHits
Looking for productInstanceName: MuonME0Hits

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by watson-ij** [comment]
My #31309 shows whats needed to turn off to run step2 and step3, its basically a brute force shut down of the ME0 entirely, and allows the step2 + local reco in step3 to run. As I noted there though, the workflow will probably still crash in the muon reco due to finding gem hits it can't associate with the internal muon reco geometry (from memory). In the other PR, @kpedro suggested adding the geometry this PR gives with the workflow turned off until the full chain works.

**Comment by bsunanda** [comment]
@dildick @kpedro88 Need to modify SimGeneral/​MixingModule/​python/​mixObjects_cfi.py to exclude ME0 hits

**Comment by dildick** [comment]
@watson-ij Correct. #31309 and #31542 need to be merged. If you incorporate the new era definition `Configuration/Eras/python/Era_Phase2C11M9_cff.py ` and the change in `Configuration/StandardSequences/python/Eras.py` then we can close #31542.

**Comment by bsunanda** [comment]
@watson-ij @dildick @kpedro88 Yes it is good to merge #31309 and #31542 and suggest which should be added as external to #31541

**Comment by watson-ij** [comment]
> [](https://github.com/cms-sw/cmssw/pull/31309).

Yep, I'll do that, just give me a little bit of time, I have a couple of other tasks at the moment, but can try to merge them before the end of the day (Seoul time).

**Comment by watson-ij** [comment]
I adapted #31309 to use Sven's modifiers and force pushed onto that branch. That PR and this one together can run steps 1 and 2 of the new 31034.0 workflow.

**Comment by bsunanda** [comment]
@kpedro88 @watson-ij @dildick Could one start the testing with #31309 rather than with #31542 which is now closed

**Comment by kpedro88** [comment]
test parameters
pull_request = #31309
workflow = 31034.0

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
@dildick @watson-ij Next step is to correct the RECHit producer looking for ME0 Digis

**Comment by dildick** [comment]
@watson-ij Probably you want to turn off the ME0 local RECO. Also, can you turn off ME0 validation in https://github.com/cms-sw/cmssw/blob/master/Validation/Configuration/python/globalValidation_cff.py?

**Comment by dildick** [comment]
And also turn off the postvalidation https://github.com/cms-sw/cmssw/blob/acf9623a7368ca0bf1200b7411291b4dbf9c2483/Validation/Configuration/python/postValidation_cff.py#L84-L85

**Comment by kpedro88** [comment]
At this point, please don't update PRs until the workflow is actually working. Testing in-progress developments via the official CI system is not preferred.

**Comment by watson-ij** [comment]
> At this point, please don't update PRs until the workflow is actually working. Testing in-progress developments via the official CI system is not preferred.

Yep, I just checked and the commit I just pushed to #31309 has enough switches flipped that the workflow completes successfully locally.

**Comment by bsunanda** [comment]
@watson-ij @kpedro88 @dildick There are many messages in step4:
MuonME0DigisHarvestor:me0DigiHarvesting@endProcessBlock  24-Sep-2020 14:24:59 CEST post-events Can not find histograms: ....
So the ME0 harvester should be inhibited as well. Could this be taken care of

**Comment by watson-ij** [comment]
> @watson-ij @kpedro88 @dildick There are many messages in step4:
> MuonME0DigisHarvestor:me0DigiHarvesting@endProcessBlock 24-Sep-2020 14:24:59 CEST post-events Can not find histograms: ....
> So the ME0 harvester should be inhibited as well. Could this be taken care of

The new commit fixes this, there is still some Tracking/HcalDigis messages, but I don't think this is coming from my changes.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
in 31034.0 step 2, I still see messages like this:
```
%MSG-e GEMPadDigiProducer:  GEMPadDigiProducer:simMuonGEMPadDigis  25-Sep-2020 16:07:26 CEST Run: 1 Event: 1
GE2/1 geometry (8 partition) appears corrupted
%MSG
```
I thought these were already fixed?

**Comment by dildick** [comment]
I've been waiting a week to get https://github.com/cms-sw/cmssw/pull/31507 merged...

**Comment by kpedro88** [comment]
test parameters
pull_requests = #31309,#31507 
workflow = 31034.0

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
The failure in the unit test seems to e unrelated to this PR nor #31507

**Comment by kpedro88** [comment]
+upgrade
new workflow runs to completion with no additional error or warning messages
(unit test failure is in the IB)

**Comment by bsunanda** [comment]
@cvuosalo @chayanit Can you approve this PR to be integrated!

**Comment by cvuosalo** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
to be merged with #31309

**Comment by kpedro88** [comment]
@silviodonato please merge this ASAP

**Comment by silviodonato** [comment]
test parameters
pull_request =

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
test parameters

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
The workflow added to default matrix, 31034.0, is failing with
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02648/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-02-2300/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02648/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-02-2300/bin/slc7_amd64_gcc820/cmsDriver.py", line 12, in run
    options = OptionsFromCommandLine()
  File "/cvmfs/cms-ib.cern.ch/nweek-02648/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-02-2300/python/Configuration/Applications/cmsDriverOptions.py", line 37, in OptionsFromCommandLine
    options=OptionsFromItems(sys.argv[1:])
  File "/cvmfs/cms-ib.cern.ch/nweek-02648/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-02-2300/python/Configuration/Applications/cmsDriverOptions.py", line 262, in OptionsFromItems
    raise Exception( "'%s' is not a valid option for '--era'. Valid options are %s." % (eraName, validOptions) )
Exception: 'Phase2C11M9' is not a valid option for '--era'. Valid options are 'tracker_apv_vfp30_2016', 'Run2_25ns', 'trackingPhase2PU140', 'Run2_2016_trackingLowPU', 'run2_HLTconditions_2016', 'run2_HF_2017', 'stage2L1Trigger_2021', 'phase2_trigger', 'Run1_pA', 'peripheralPbPb', 'Run1_peripheralPbPb', 'Phase2', 'run3_GEM', 'Run2_HI', 'Phase2C10_dd4hep', 'run2_HCAL_2017', 'run2_nanoAOD_94XMiniAODv1', 'run2_nanoAOD_94XMiniAODv2', 'Run2_25ns_HIPM', 'run2_nanoAOD_92X', 'fastSim', 'Run2_2017_FastSim', 'run2_HEPlan1_2017', 'Run2_2016_pA', 'run2_nanoAOD_106Xv1', 'run2_GEM_2017', 'Phase2C12', 'Phase2C10', 'Phase2C11', 'run2_miniAOD_devel', 'Run2_50ns_HIPM', 'phase2_ecal', 'run2_nanoAOD_94X2016', 'run2_HLTconditions_2018', 'phase2_tracker', 'run2_HLTconditions_2017', 'Run2_2018_pp_on_AA', 'Run2_2017_trackingLowPU', 'Run2_2018_highBetaStar', 'run2_CSC_2018', 'Run2_2018_FastSim', 'highBetaStar_2018', 'run2_miniAOD_80XLegacy', 'trackingLowPU', 'run2_miniAOD_94XFall17', 'run2_HE_2018', 'run2_HI_specific', 'Run2_2018_pp_on_AA_noHCALmitigation', 'run2_HE_2017', 'Phase2C9_dd4hep', 'phase2_hfnose', 'phase1Pixel', 'run2_nanoAOD_102Xv1', 'run3_RPC', 'Run3_pp_on_PbPb', 'Run2_2017_pp_on_XeXe', 'phase2_hgcalV10', 'stage2L1Trigger', 'Run2_2017_ppRef', 'trackingPhase1', 'run2_50ns_specific', 'stage2L1Trigger_2018', 'hcalSkipPacker', 'phase2_timing_layer', 'Run2_2017_trackingRun2', 'phase2_timing', 'pA_2016', 'Phase2C11_dd4hep', 'run2_25ns_specific', 'phase2_muon', 'run3_common', 'phase2_common', 'Run2_2018', 'Run2_2016', 'Run2_2017', 'Run3', 'Phase2C12_dd4hep', 'stage1L1Trigger', 'ctpps_2021', 'pf_badHcalMitigation', 'run3_HB', 'Run2_25ns_peripheralPbPb', 'bParking', 'phase2_hgcal', 'run2_HB_2018', 'Run2_50ns', 'stage2L1Trigger_2017', 'Phase2C9', 'phase2_hgcalV11', 'Run3_dd4hep', 'phase2_hgcalV12', 'hcalHardcodeConditions', 'ctpps_2016', 'ctpps_2017', 'Run2_2016_HIPM', 'phase2_hcal', 'ctpps_2018', 'run2_2017_noTrackingModifier', 'run2_common'.
```

**Comment by bsunanda** [comment]
@makortel @kpedro88 This PR needs #31034 - i wonder why that PR is not merged and closed by @silviodonato

**Comment by makortel** [comment]
#31034 is an issue to build CMSSW_11_2_patch3. Which PR did you mean?

**Comment by qliphy** [comment]
@bsunanda   Do you mean #31309?

**Comment by bsunanda** [comment]
@makortel @kpedro88 @silviodonato Sorry it is #31309, The other one #31507 is already integrated

**Pull request merged**
