### PR TITLE
Update nano relval matrix

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Updated NANO relval matrix:
 - updated workflows to 140X
 - added Run2UL reMINI + reNANO workflows
 - moved NANOGEN from relval_generator to relval_nano

Also added the support for NANOGEN with the autoNANO syntax:
 - from GEN inputs: `-s NANO:@GEN --eventcontent NANOAOD`
 - from MiniAOD: `-s NANO:@GENFromMini --eventcontent NANOAOD`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by vlimant** [comment]
N.B : should we update ConfigBulder to hard remove NANOGEN since you include the support here ?

**Comment by hqucms** [comment]
> N.B : should we update ConfigBulder to hard remove NANOGEN since you include the support here ?

Done in https://github.com/cms-sw/cmssw/pull/45419/commits/e1932498b0768eda6573702ebb0e747fb000f69c now.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

The differences in wf `29634.911` look unrelated to this PR. 
The errors in NANO comparison are due to changes in the NANO workflows introduced in this PR.

**Comment by hqucms** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 @cms-sw/operations-l2
Could you please review and sign? We would like to get this in asap. Thanks!

**Comment by srimanob** [comment]
Hi @hqucms 
As you change the way to call NanoGEN, would it be useful to add a workflow on it? I see you only remove the workflow of NanoGEN, but no new workflow on the new way. Thx.

**Comment by srimanob** [comment]
> @srimanob The NanoGEN workflows are moved from `relval_generator` to `relval_nano` now so we can test them with all other nano workflows together.

Is it moved in this PR? Thx.

**Comment by hqucms** [comment]
> > @srimanob The NanoGEN workflows are moved from `relval_generator` to `relval_nano` now so we can test them with all other nano workflows together.
> 
> Is it moved in this PR? Thx.

Yes - in these lines: https://github.com/cms-sw/cmssw/pull/45419/files#diff-aaca4437268e5c684a1042abc90e2cdd651a08b8c35f03cdd32060e8918f41e5R359-R367

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by vlimant** [comment]
@cms-sw/operations-l2 please sign

**Comment by rappoccio** [comment]
+1

**Comment by hqucms** [comment]
@cms-sw/core-l2 I noticed that the updated wf 2500.245 is [failing](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-07-24-1100/pyRelValMatrixLogs/run/2500.245_hcalDPGCalibNANO140Xrun3/step2_hcalDPGCalibNANO140Xrun3.log#/) because the input file [1] has disappeared from disk (now only on tape). 

I would expect it to be automatically cached by ibeos but it seems no? How is the ibeos caching supposed to work for new input files?

[1] /store/user/cmsbuild/store/data/Run2024F/TestEnablesEcalHcal/RAW/Express-v1/000/383/173/00000/1088fbe0-c256-4752-992c-0e535b804bef.root

**Comment by makortel** [comment]
(@smuzaffar please correct me) I believe the ibeos caching works automatically for files that are on disk. I don't think we have any automated way to recall a file from tape (but I believe we could shovel the file to the cache by hand if that's what is needed).

In any case someone has to recall the file from tape. If the recall is done such that the file is visible e.g. via the xrootd redirectors (e.g. for a week or two), I'd expect the automatic caching to pick the file from there.

**Comment by smuzaffar** [comment]
`/store/data/Run2024F/TestEnablesEcalHcal/RAW/Express-v1/000/383/173/00000/1088fbe0-c256-4752-992c-0e535b804bef.root` is now in ibeos cache

**Comment by hqucms** [comment]
Thanks a lot @smuzaffar @makortel !

**Comment by vlimant** [comment]
one caveat that I noticed is that TTbar_13_reminiaod2016UL_preVFP_INPUT is not the UL MINIv2  while TTbarMINIAOD10.6_UL16v2 is ; so I wonder what NANOmcUL16APVreMINI is actually testing

**Comment by vlimant** [comment]
in particular, looking at all procmodifiers it invoques run2_miniAOD_UL_preSummer20 instead of run2_miniAOD_UL ; the second one bing more relevant IMO

**Pull request merged**
