### PR TITLE
Print function migration for TopQuarkAnalysis_TopPairBSM

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by perrotta** [comment]
+1
- Reco content identical to the already signed #23868

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

changes look technical and simple enough

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
@fabiocos - seems cmsbot is ignoring this one. i just merged it

**Comment by fabiocos** [comment]
@davidlange6 good, I see cmsbot took it now

**Pull request merged**
