### PR TITLE
71X update for 2015 BS and default Run1 geometry

### PR DESCRIPTION
**Pull request by diguida**
This branch has:
- a modified version of `Configuration/PyReleaseValidation/python/relval_steps.py` for using the gen-sim produced in `CMSSW_7_1_14` and for using by default the BS for nominal collisions 2015 (originally in #7904 with a fix); 
- a modified version of `Configuration/AlCa/python/autoCond.py` for using the GTs for Run2 simulations in 25 and 50 ns with the new BS (originally in #7904);
- a modified version of `Configuration/AlCa/python/autoCond.py` for using the GTs for Run1 simulations with more realistic tracker material budget SIM geometry;
- a modified version of `Configuration/StandardSequences/python/VtxSmeared.py` for using the `VtxSmearedDefaultKey` for `NominalCollisions2015` (originally in #7904).

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by Dr15Jones** [comment]
Test failure is unrelated to this pull request. The failure ears to happen because the machine has lost its security credentials.

**Comment by diguida** [comment]
@Dr15Jones thanks for the explanation!

**Comment by diguida** [comment]
@degano do you know how to fix the security issues in the unit tests?
Thanks

**Comment by diguida** [comment]
@cmsbuild please test
Let's re-try

**Comment by franzoni** [comment]
hello @diguida ,

does the change to:
 'run1_mc'           :   'MCRUN1_71_V0::All',
affect anything else other than the material budget ?

We have run1 workflow in the matrix, for which GEN-SIM are recycled in the IB. Can we guarantee that the RECO conditions of this new GT are consistent the existing GEN-SIM ? 

Cheers, g.

**Comment by diguida** [comment]
@franzoni 
You can see the changes [here](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/START71_V8/MCRUN1_71_V0): the only changes are in the SIM geometry, no other changes in conditions.
Given that the material budget only affects non active parts of the detector, neither the RECO geometry nor other conditions like alignment are affected.

**Comment by diguida** [comment]
@franzoni 
As agreed, I have reverted the Run1 MC global tags to the current values, in order not to break consistency between the release validation matrix and the GEN-SIM samples.

**Comment by diguida** [comment]
please test

**Comment by franzoni** [comment]
+1
the whole standard set run ok on top of CMSSW_7_1_X_2015-02-22-0200
ADDMonoJet => https://hypernews.cern.ch/HyperNews/CMS/get/relval/3413/1/1.html
RelValJpsiMM_13 => GEN-SIM is in the making
The two HIN previously failing workflows are not addressed, here.
Thanks @diguida @nancymarinelli

**Comment by franzoni** [comment]
What is the reason why 

 test runtestPhysicsToolsPatAlgos had ERRORS

uses /RelValProdTTbar/CMSSW_7_1_0_pre9-START71_V5-v1/AODSIM ? https://cmsweb.cern.ch/das/request?input=site%20dataset%3D/RelValProdTTbar/CMSSW_7_1_0_pre9-START71_V5-v1/AODSIM&instance=prod/global&idx=0&limit=10

Such failure is un-related to this PR, which is MC only.

**Comment by franzoni** [comment]
@diguida @ktf @davidlange6 @nancymarinelli 
hello, can we try and move along with this PR ?
The test which blocked the approval was unclear / unexplained to me.
In oder to test 74x DR with with 71x GEN-SIM input, we need to have these changes in a 71x releas.
Cheers,
g.

**Comment by diguida** [comment]
@franzoni 
No issue on my side... As I said, I tested this privately and is ok.
I sign it and launch tests again

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1
Test failures unrelated to this PR (tested OK privately)

**Comment by franzoni** [comment]
Tried to make a phedex transfer of /RelValProdTTbar/CMSSW_7_1_0_pre9-START71_V5-v1/AODSIM and stumbled on "Error retrieving preview data".

**Comment by franzoni** [comment]
transfer of the missing input placed:
https://cmsweb.cern.ch/phedex/prod/Request::Admin?request=435605

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
can this PR please be merged ? 
I tried to re-trigger the tests, which was unsuccessful. 
This is essential to have 71x GEN-SIM in input to the 74 validation 
(we'll need migration of the matrix to pythia8, too)

**Pull request merged**
