### PR TITLE
Cleanup Geant4 physics sub-libraries for version 10.7 and beyond

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR include clean-up SimG4Core sub-libraries for Geant4 10.7 and next versions:
  1) removed obsolete classes
  2) improved comments and documentation
  3) reestablish EMN configuration for HGCal
  4) reestablish hadronic configuration for QGSP_FTFP_BERT
  5) should compile against Geant4 11.0
  6) baseline simulation should not be affected

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport
no backport

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , this PR introducing new EMN and should make compatible with new Geant4.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
