### PR TITLE
Phase2-hgx360O Replace 2026 wth Run4 in some scripts of Alignment/MillePedeAlignmentAlgorithm and CalibCalorimetry/EBPhase2TPGTools

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace 2026 wth Run4 in some scripts of Alignment/MillePedeAlignmentAlgorithm and CalibCalorimetry/EBPhase2TPGTools

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+alca

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
