### PR TITLE
Updating phase2 Tracker Geometry (T3) - 2023D4 scenario

### PR DESCRIPTION
**Pull request by boudoul**
Greetings  - This PR is putting in place the xmls prepared by @ghugo83 -
This is the version (internal tracker version : OT365+ Pixel4026)  of the Tracker from Tklayout superseeding the previous version  (OT362 + Pixel4021) - updating materials and inner + outer modules position 

This was presented here : https://indico.cern.ch/event/536862/contributions/2390748/attachments/1382904/2103143/mersi_20161205_newlayouts.pdf with the corresponding mat budget plots 

Affecting only 2023D4 scenario 

At the same time I updated the recomaterial analyzer to deal with the new material (and cleaned obsolete customize function in them ) 

adding usual watchers : @delaere , @ atricomi , @rovere , @VinInn @makortel @ebrondol @venturia

Tested  with WF# 21210

### CODE REVIEW

**Comment by boudoul** [comment]
Adding for real @atricomi [typo in the description above ]

**Comment by boudoul** [comment]
Adding @kpedro88

**Comment by ghugo83** [comment]
@boudoul Ah just a very very minor thing : 
In : SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py 
pixel:tkLayout_SenSi    doesn't exist,
materials = cms.untracked.vstring("materials:Silicon", "tracker:tkLayout_SenSi"),
would be enough

**Comment by boudoul** [comment]
@ghugo83 , thanks, good catch, just fixed this in my last commit

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@boudoul , in pixelProdCuts.xml in line 18 
 <Parameter name="ProdCutsForGamma" value="10*cm"/>

10 cm better to substitute to 1 mm.

**Comment by ghugo83** [comment]
Thanks @civanch :) In trackerProdCuts.xml you mean ?
And what about the other values in pixel/tracker ProdCuts.xml, are they ok ?
Once this is checked one can also remove the "warning" line in the XML :)

**Comment by civanch** [comment]
@boudoul , other values are fine to me. I have checked trackerProdCuts.xml and pixelProdCuts.xml

**Comment by ianna** [comment]
+1

**Comment by boudoul** [comment]
ok thanks @civanch , I moved 10cm to 1mm in ProdCutsForGamma in my last commit

**Comment by civanch** [comment]
please test

**Comment by ghugo83** [comment]
Hi @boudoul,
Naive question : why are pixfwdCylinder.xml and pixfwdMaterials.xml added to TiltedTracker4021 ?
They do not correspond to the Phase 2 Pixel description, which is fully automated from tkLayout (one can say the "Tracker" volume itself is fully independent volume, only trackerbar.xml and trackerfwd.xml are needed).

If these files correspond to another subdetector / sth else than Phase 2, why not placing them directly into the corresponding directories ?

**Comment by ghugo83** [comment]
Please note this has no impact on the Phase 2 Tracker though, since the logical volumes described in pixfwdCylinder.xml and pixfwdMaterials.xml : 
- are not appearing on Fireworks.
- their materials are not added when i look at the sim material budget of the Phase 2 Tracker.
- looking at the internal logics of the XMLs, these volumes are not plugged to the Phase 2 Tracker mother volume.

Though, since these files are not associated to the Phase 2 Tracker, why are they put here ?

**Comment by boudoul** [comment]
pixfwdcylinder is needed to compute this line : https://github.com/cms-sw/cmssw/blob/56b1a4ae6bc89d26fe7d31afb7fd588b5eaecf4b/Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4026/pixfwd.xml#L19

then since you need pixfwdcylinder , then you need pixfwdMaterials.xml (otherwise you cannot compute these lines  :  https://github.com/cms-sw/cmssw/blob/56b1a4ae6bc89d26fe7d31afb7fd588b5eaecf4b/Geometry/TrackerCommonData/data/PhaseII/TiltedTracker4026/pixfwdCylinder.xml#L147)

**Comment by ghugo83** [comment]
Ah ok.
The thing is RootHalfLength and RootEndZ are not used for the Phase 2 Tracker.
Shall we simply remove or comment these lines, and remove pixfwdCylinder.xml and pixfwdMaterials.xml ?
NB : Not urgent though, since unused anyway, but to be clean :)

**Comment by boudoul** [comment]
the cleaner the better :) thanks for having noticed, I removed but whhops I forgot to use Kevin's script and update it, next commit in a few minutes will address this

**Comment by boudoul** [comment]
voila, this time i'm done with the proposed changes, thanks

**Comment by ghugo83** [comment]
Just as a comment, following fixes / cross-checks have been done : 
- 0 overlap within Tracker volume, both with Fireworks and Geant4 tools.
- Sim Material Budget as expected with respect to tkLayout (will provide MB plots after i am finished with the flat tracker baby)

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
On 12/8/16 9:20 AM, boudoul wrote:
> the cleaner the better :) thanks for having noticed, I removed but
> whhops I forgot to use Kevin's script and update it, next commit in a
> few minutes will address this

Kevin,

Can you add a unit test to check consistency between the dict script and
what's expected as its output in the release.
It will be executed every time this package is rebuilt by jenkins (in a
PR test or in the IBs)

Thanks

	--slava

**Comment by kpedro88** [comment]
@slava77 that's a good idea. I need to think about exactly how it should work. Are there any similar examples elsewhere in CMSSW?

**Comment by slava77** [comment]
On 12/8/16 10:08 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> that's a good idea. I need to
> think about exactly how it should work. Are there any similar examples
> elsewhere in CMSSW?

It can be as free-form as a script that generates the files in a temp
and then checks against the $CMSSW_BASE/src

look at RecoMET/METProducers/test/BuildFile.xml
how to set up a script as a unit test

**Comment by ebrondol** [comment]
I have checked the eff/fake performance of this PR on the global tracking reconstruction. The test have been done with ttbar tkOnly workflows with the IB CMSSW_9_0_X_2016-12-07-1100 @ the commit 78a9963. No PU included.
The results are consistent with "small changes" in the reconstruction. Here reported some important plots:
16896_eff
16896_hits

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by ghugo83** [comment]
As promised, comparison of the CMSSW Sim Material Budget with tkLayout MB (was done quickly on the fly after creating the XMLs, proper plots now :) )
This is the MB within Full Tracker volume (Beam Pipe excluded). 10000 tracks.
4026_comparison

**Pull request merged**
