### PR TITLE
[MISC2] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by civanch** [comment]
+1

**Comment by lviliani** [comment]
+1

**Comment by smuzaffar** [comment]
@makortel @Dr15Jones @alja can you please sign it for `visualization` ?

**Comment by alja** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
