### PR TITLE
Change ECAL Presample RMS threshold [13_0_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR changes the RMS threshold in ECAL Presample quality and removes the many red spots in the plot.

#### PR validation:

PR validated by running the Ecal dqm client and the plot looks as expected.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of the Master PR: https://github.com/cms-sw/cmssw/pull/41438

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41438

**Comment by syuvivida** [comment]
Tested at p5 with run 366533 and compared with the default release without this PR, the ECAL summary plots do seem less noisier.

**Comment by syuvivida** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
