### PR TITLE
[Phase-2] Fixed L1 quality mask requirement in L1TkEmSingle51Filter

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

Fixed L1 quality mask requirement in `L1TkEmSingle51Filter`.
Egamma validator @skeshri is checking the impact of the fix.
13_1_X backport: https://github.com/cms-sw/cmssw/pull/42897

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix, egamma

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@SohamBhattacharya 

> [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-27-1100+a8f94d/59049/triggerResults): found differences in 3 / 48 workflows

I gather [this sort of changes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-27-1100+a8f94d/59049/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.log) are expected:

```
Found 10 matching events, out of which 1 have different HLT results

      Events    Accepted      Gained        Lost       Other  Trigger
          10           3          +1           -           -  L1T_TkEm51
          10           1           -           -          ~1  HLT_Ele32_WPTight_Unseeded
          10           1           -           -          ~1  HLT_Ele26_WP70_Unseeded
          10           0           -           -          ~1  HLT_Photon108EB_TightID_TightIso_Unseeded
          10           0           -           -          ~1  HLT_Photon187_Unseeded
          10           1           -           -          ~1  HLT_Ele32_WPTight_L1Seeded
          10           0           -           -          ~1  HLT_Ele115_NonIso_L1Seeded
          10           1           -           -          ~1  HLT_Ele26_WP70_L1Seeded
          10           0           -           -          ~1  HLT_Photon108EB_TightID_TightIso_L1Seeded
          10           0           -           -          ~1  HLT_Photon187_L1Seeded
Created the following JSON files:
 /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/upload/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.json
```

since you mention the egamma validator is explicitly checking the impact, I will wait explicit sign-off before signing this (and the backport).

**Comment by SohamBhattacharya** [comment]
> @SohamBhattacharya
> 
> > [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-27-1100+a8f94d/59049/triggerResults): found differences in 3 / 48 workflows
> 
> I gather [this sort of changes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-27-1100+a8f94d/59049/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.log) are expected:
> 
> ```
> Found 10 matching events, out of which 1 have different HLT results
> 
>       Events    Accepted      Gained        Lost       Other  Trigger
>           10           3          +1           -           -  L1T_TkEm51
>           10           1           -           -          ~1  HLT_Ele32_WPTight_Unseeded
>           10           1           -           -          ~1  HLT_Ele26_WP70_Unseeded
>           10           0           -           -          ~1  HLT_Photon108EB_TightID_TightIso_Unseeded
>           10           0           -           -          ~1  HLT_Photon187_Unseeded
>           10           1           -           -          ~1  HLT_Ele32_WPTight_L1Seeded
>           10           0           -           -          ~1  HLT_Ele115_NonIso_L1Seeded
>           10           1           -           -          ~1  HLT_Ele26_WP70_L1Seeded
>           10           0           -           -          ~1  HLT_Photon108EB_TightID_TightIso_L1Seeded
>           10           0           -           -          ~1  HLT_Photon187_L1Seeded
> Created the following JSON files:
>  /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/upload/triggerResults/25034.999_TTbar_14TeV+2026D98PU_PMXS1S2PR/HLT.json
> ```
> 
> since you mention the egamma validator is explicitly checking the impact, I will wait explicit sign-off before signing this (and the backport).

Thanks for the check.
Yes, `L1T_TkEm51` increases as expected.

**Comment by mmusich** [comment]
@SohamBhattacharya @skeshri do you have any follow-up to this:

>  Egamma validator is checking the impact of the fix.

Thanks

**Comment by skeshri** [comment]
> @SohamBhattacharya @skeshri do you have any follow-up to this:
> 
> > Egamma validator is checking the impact of the fix.
> 
> Thanks

Hello @mmusich and @SohamBhattacharya,

Sorry for the delay. I was on vacation just came back today. I will do it by tonight.

**Comment by skeshri** [comment]
Hello @mmusich and @SohamBhattacharya 

I have checked the efficiency in the endcaps of the filter L1TkEmSingle51Filter. You can clearly see that it recovered in the endcaps after fixing the bug.
Thanks for your patience. 


eta_l1tTkEmSingle51Filter

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/42896#issuecomment-1746214450

**Comment by rappoccio** [comment]
+1

**Pull request merged**
