### PR TITLE
[Backport] Adding the new muon track finder index and three eta cuts features in the GT emulator

### PR DESCRIPTION
**Pull request by elfontan**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/41312.
These updates are needed for the deployment of the Run L1 menu [L1Menu_Collisions2023_v1_0_1](https://github.com/cms-l1-dpg/L1MenuRun3/tree/master/development/L1Menu_Collisions2023_v1_0_1) in view of the first stable beams at 13.6 TeV or soon after.

This PR includes two updates of the GT emulator accorging to the latest version of the utm library v0.11.2 (see details in [CMSLITDPG-1104](https://its.cern.ch/jira/browse/CMSLITDPG-1104)) and developments of the L1 menu for Run 3:
* Usage of three eta cuts (up to five cuts are allowed) in the design of the muon algorithms with the upt requirement. The check on the eta range is now implemented as a function checking a vector of eta windows to handle the five cuts in a easier way.
* New track finder index feature for muons in the uGT emulator needed for the update of the 2023 L1 menu as detailed in [CMSLITDPG-1075](https://its.cern.ch/jira/browse/CMSLITDPG-1075)). Note that the missing muon index data is also included in the GtRecordDumper, needed to produce a test vector as input to the firmware validation. The bits assigned to muon index in the muon object are 36..42 (see Table 6 in the uGT firmware documentation - [scales_inputs_2_ugt.pdf](https://github.com/cms-l1-globaltrigger/mp7_ugt_legacy/blob/master/doc/scales_inputs_2_ugt/pdf/scales_inputs_2_ugt.pdf)). Thank you @arnobaer and Herbert for the work!

#### PR validation:
Basic tests performed successfully starting from CMSSW_13_0_X_2023-04-06-1100
> cmsrel CMSSW_13_0_X_2023-04-06-1100
> cd CMSSW_13_0_X_2023-04-06-1100/src
> cmsenv
> git cms-addpkg L1Trigger/L1TGlobal 
> git cms-addpkg L1Trigger/Configuration
> scram b distclean 
> git cms-checkdeps -a -A
> scram b -j 8
> scram b runtests 
> scram build code-checks
> scram build code-format

A cross-check of the countings of each trigger bit in the new firmware and in the updated emulator showed a perfect match.

Basic cmsDriver command for L1Ntuple production successfully tested:
> cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=test.py -n 1000 --no_output --era=Run3 --data --conditions=124X_dataRun3_Prompt_v4  --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --filein=/store/data/Run2022F/EphemeralZeroBias0/RAW/v1/000/361/468/00000/52351179-2329-47d8-bffc-a01833bb1704.root --fileout=L1Ntuple.root

Note that the temporary release CMSSW_13_0_X_2023-04-06-1100 is not available anymore, so that final tests have been performed in CMSSW_13_0_X_2023-04-15-1100.

### CODE REVIEW

**Comment by francescobrivio** [comment]
> These updates are needed for the first deployment of the Run L1 menu in preparation of the first stable beams at 13.6 TeV.

Ciao @elfontan according to the latest news we should expect 13.6 TeV SB towards the end of the next week (> 20 April).
Is this PR urgently needed? (I guess only in HLT?)

FYI @tyjyang @fabiocos

**Comment by aloeliger** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/41312

**Comment by francescobrivio** [comment]
Thanks Elisa, makes sense! Please keep us updated on the developments because if we need a new release with this before the 13.6 TeV we don't have mich time! 😄

**Comment by aloeliger** [comment]
please test

**Comment by tyjyang** [comment]
Tests for the commit are all passed, are we ready to backport?

**Comment by elfontan** [comment]
Hello @tyjyang, we are still in the process of validating the behaviour of the current status of the software wit the uGT firmware. We would like to wait for this step before moving to the review and integration.
(We are also working on a plan B for the deployment of the new menu in case we are late with the integration for a patch release. This means that we hope to have it done very soon, but it is not highly critical anymore for next week. We will keep you updated.)

Thank you,
--Elisa

**Comment by tyjyang** [comment]
Thanks Elisa!

**Comment by elfontan** [comment]
Dear all,
after a first round of validation of the GT firmware and emulator behaviour with @arnobaer, the PR has been updated to fix some mismatches in the L1_SingleJet*HE countings caused by the updated checkRangeEta code. While investigating this issue, the code has been improved to implement the check on the eta range as a function that checks a vector of eta windows. In this way, the possibility to have up to five eta cuts is handled in an easier way.

In parallel, an issue with the firmware related to the BMTF muon monitoring seeds based on the usage of the new muon TF index feature has been spotted. We wait for the fix before moving to another round of validation and for now we keep this PR on hold.

We'll keep you posted. Thank you,
--Elisa

**Comment by elfontan** [comment]
Hello @aloeliger @epalencia all,
I am moving the PR to Ready for review given that the firmare bug was fixed and the firmware-emulator agreement was validated (see [CMSLITDPG-1102](https://its.cern.ch/jira/browse/CMSLITDPG-1102)).
Is any action needed on the commit history to proceed?

Cheers,
--Elisa

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

- last commit removes debug output

**Comment by elfontan** [comment]
Hello @perrotta, 
the point is that the TriggerMenuParser was updated in master to use a new logic (as general approach) to read the information from the utm library, but there was the choice to not backport that PR to 13_0_X. @aloeliger can comment more. So I couldn't simply include the changes with a cherry-pick or similar because of the many differences in the basic file. I included the changes manually to reproduce the same results. @aloeliger can probably comment more on this. 
Thank you!

Cheers,
Elisa

**Comment by aloeliger** [comment]
@elfontan Are these changes related to the changes I introduced with #41036? If so the changes in that PR were to move from the firmware `es` types to more CMSSW native `uTM` types and present in CMSSW_13_1_X onwards. Those types should be basically the same however. Where was significant work-around needed for these objects in both PRs?

**Comment by aloeliger** [comment]
If significant changes in behavior are seen with the `es` to `utm` type change, this needs to be addressed immediately.

**Comment by elfontan** [comment]
Hi @aloeliger, 
as I answered above, the behaviour is the same as in 13_1_X (= the trigger results when running the emulator in the two different releases to produce test vectors are exactly the same).
I just needed to update "manually" the code of the TriggerMenuParser because the original file was very different between the two releases. I understand that Andrea was referring to this kind of differences.

Elisa

**Comment by elfontan** [comment]
Good morning @perrotta (and @aloeliger), 
any follow up here? Was your question referred to the differences explained above?
Thank you in advance.
Cheers,
--Elisa

**Comment by aloeliger** [comment]
@elfontan I took another look comparing to the original PR. As far as I am concerned these seem reasonable differences to accommodate for changes to the trigger menu parser between CMSSW_13_0 and CMSSW_13_1.

**Comment by rappoccio** [comment]
+1

Thanks @elfontan, this makes sense.

**Pull request merged**
