### PR TITLE
Update RPC time resolution parameters

### PR DESCRIPTION
**Pull request by jhgoh**
This PR updates the RPC time resolution parameter for the link board upgrade scenario in Phase-II.

The intrinsic time resolution of already installed chambers are known to be ~1.5ns, therefore the default parameters for the LB upgrade should be consistent with it.
There are other changes in the default parameter set (timeJitter and timeResolution), but they are not used in the actual simulation with precise timing, but we update them to avoid unnecessary confusions.

@bapavlov

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1
a few changes in RPC digi and RecHit quantities in Phase2 workflows, as expected

**Comment by davidlange6** [comment]
+1

**Pull request merged**
