### PR TITLE
Reshape RunI-like tracking customization snippet. 

### PR DESCRIPTION
**Pull request by rovere**
Back-port of #8691 into 74X. Could be extremely useful also for the 0T scenario.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Hi Marco, just making a blind comparison of the number of lines, this PR doesn't match #8691 
what are the changes?

**Comment by rovere** [comment]
@slava77 you are right, I might have missed 1 commit from #8691 
I'll update this PR accordingly.
Thanks for noticing.

**Comment by slava77** [comment]
ah, ok, good that I checked.
At brief inspection, it looks like the changes in tracking parameters in the *iteration*cff are missing

**Comment by rovere** [comment]
Here they are.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@davidlange6 
David, is this going to be needed in Prompt and Express or should we leave it for a rereco?

**Comment by VinInn** [comment]
TRK-POG propose this  for Prompt and Express for next round of T0 data

**Comment by slava77** [comment]
this means that T0 processing scenarios need to be defined.
Just having a customize function is not enough (new PR, I suppose)

**Comment by VinInn** [comment]
Sure, and I bet a new release will be needed.
Do you not expect other detectors to provide new code as well, do you?

**Comment by slava77** [comment]
@VinInn 
yes, we are collecting inputs.
you are the first to have a solution for your area.

**Comment by franzoni** [comment]
@VinInn @rovere  can you please circulate to hn instructions to activate these changes ?
(I notice that all what you've modified are runI python, which I doubut are part of the default RECO)
Thanks.

**Comment by rovere** [comment]
@franzoni Ciao Giovanni,
detailed instructions have been provided and attached to #8691 
Before circulating them "publicly" over HN maybe  it's better to see the performances over some RelVal sample@0T (yes, privately re-reco'd with the customise, unless you can offer a central re-reco w/ this customise on)

**Comment by slava77** [comment]
summary for https://github.com/cms-sw/cmssw/pull/9296	86fe202
- tested locally in CMSSW_7_4_3 /test area sign743b/
- the main test is based on run 200781 lumi=80 (~PU=30 with 0 T from 2012C)  /store/data/Run2012C/MinimumBias/RAW/v1/000/200/781/7ED5DB39-DDE4-E111-9386-003048F118D2.root , using 1000.0 configuration otherwise. 100 events in the test.
- technical performance seems comparable: processing time up from 10.6 to 13.7 s/evt (peak moves from 29.4 to 35.8 s/evt), both excluding the first event dominated by conditions fetch.

Some object comparisons notes
- most tracks don't have MVA value assigned
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_floatedmvaluemap_generaltracks_mvavals_reco_obj_values_
- there are 50% more tracks (from the following distributions they appear to be "better" tracks)
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_recotracks_generaltracks__reco_obj_pt

all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_minrecotracks_generaltracks__reco_obj_normalizedchi2 29
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_recotracks_generaltracks__reco_obj_algo
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_recotracks_generaltracks__reco_obj_eta
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_recotracks_generaltracks__reco_obj_found

- more electron gsf tracks as well
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recogsftracks_electrongsftracks__reco_obj_pt
- but fewer PF egamma objects (more tracks probably kill some of them in the preselection)
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recopfcandidates_particleflowegamma__reco_obj_pt

- calo jets change a bit (likely due to the track->hbhe cleaning step)
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recocalojets_ak4calojets__reco_obj_et

PF reco is not quite trivial to understand (do we even know that it works OK?)
- about 30% less charged hadrons (opposite to 50% more tracks .. looks like PF RECO doesn't like these tracks.)
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recopfcandidates_particleflow__reco_obj_pt10
- similar decrease in electrons (this should follow what happens in the egamma objects; since the sample is mostly fakes, the meaning of decrease is unclear)
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recopfcandidates_particleflow__reco_obj_pt20

- muons are ~unchanged
- photons are ~unchanged
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recopfcandidates_particleflow__reco_obj_pt40
- ~15% more neutral hadrons
all_sign743b-200781vsorig-200781_runminbias2011awf1000p0c_log10recopfcandidates_particleflow__reco_obj_pt50


Overall, there are indications that tracking is indeed better, but higher level reco downstream (PF, specifically) maybe just not well adjusted to the 0T input track properties.
MC with truth matching would help to understand what's happening.

**Comment by slava77** [comment]
@bachtis Michalis, do you have any high expectations for PF reco with 0 T?
@lgray what about egamma?

**Comment by bachtis** [comment]
Hi Slava ,
I have discussed with PC . There are many ideas that are configurable and could be done at PF @0T
Examples: 
[Run PF without tracks ~ 20% improvement for jet resolution wrt CaloJets] 
Link tracks and Calo deposits and create PF candidates with Calo energy and track direction [and try to associate to PV]

Now the request from PC was to not invest in that direction for the high level reconstruction for now since we are looking at a middle term solution.
just for my education: @rovere  @VinInn  what is the pt of the tracks at 0 T    and the error that you give?

**Comment by VinInn** [comment]
Seeds starts with 5GeV and some sort of large error.
than KalmanFilter is free to adjust most probably taking into account multiple-scattering...

**Comment by bachtis** [comment]
OK then PF will give random results since it assumes ~5 GeV track energy. Unless the error is very very large so that it will prefer the calo measurement. Ideal configuration for PF to run out of the box would be : track pt   = 0.0 +- 100 TeV

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9296	86fe202
- the new configuration can be enabled with ``` --customise RecoTracker/Configuration/customiseForRunI.customiseForRunI ```
- some performance notes were posted earlier in the thread

**Comment by davidlange6** [comment]
+1

**Pull request merged**
