### PR TITLE
Run3-ft25 Fix overlap for run3 geometry - backport #29953

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fixes overlap in the run3 scenario

#### PR validation:

Tested using overlap checking tools

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport #29953

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
