### PR TITLE
Return TrackingRegions by unique_ptr in TrackingRegionProducer

### PR DESCRIPTION
**Pull request by makortel**
Title says it all.

Tested in CMSSW_7_6_X_2015-07-21-1100, no changes expected in results.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #10306 da8be9ffc5374a734cbe36983d75fd1310650c34

Conversion of bare pointers to unique_ptr in TrackingRegionProducer code. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10306/79/summary.html) against baseline CMSSW_7_6_X_2015-07-21-2300 show no significant differences, as expected. Extended tests of workflow 25202.0_TTbar_13 with 70 events also show no significant differences. Memory use for RECO with no DQM or Validation shows no significant change:

Baseline
Max VSIZ 2079.66 on evt 28 ; max RSS 1823.14 on evt 28
Time av 14.6037 s/evt   max 46.7523 s on evt 28

PR 10306
Max VSIZ 2079.65 on evt 28 ; max RSS 1822.32 on evt 28
Time av 14.6768 s/evt   max 45.6144 s on evt 28

**Pull request merged**
