### PR TITLE
fix ExtVec for clang

### PR DESCRIPTION
**Pull request by VinInn**
The length of the vector was wrong for clang.
clang support GCC vector extension syntax: no reason to use OpenCL one.

The effect is only visible in explicit tests and for clang build on ARM or Power
(I expect some workflow should have failed)

### CODE REVIEW

**Comment by VinInn** [comment]
fixes  #41707

**Comment by smuzaffar** [comment]
please test for CMSSW_13_2_CLANG_X

**Comment by smuzaffar** [comment]
please test

use latest IB for default PR tests

**Comment by mandrenguyen** [comment]
Is it expected that the reco comparison tests shows so many differences (even if they look quite small)?

**Comment by VinInn** [comment]
try the clang build on a different PR

**Comment by davidlange6** [comment]
you can see the baseline is a gcc build, so seems normal to me.

**Comment by mandrenguyen** [comment]
+1
Tiny reco diffs are from building on a different compiler

**Comment by perrotta** [comment]
+1

**Pull request merged**
