### PR TITLE
Fix Tracker Alignment Payload writing 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to fix a bug inadvertently introduced at https://github.com/cms-sw/cmssw/pull/36076 (aimed to migrate Alignment codes to new `PoolDBOutputService` methods).
Moving to usage of instances instead of pointers led to the `GeometryAligner::removeGlobalTransform` call (to remove global roto-translations after computation of the alignment corrections) to be ineffective. This in turn lead to large spurious rotations and shifts of the alignment output geometry with respect to the input one.
This is fixed here in commit e5a18da8858d8d42858db32bcbde2806b58b4873.
I profit of this PR to refresh the inputs for the `testPedeCampaign` unit test (at 0460fec0ecd56b86298237ac2e17a2e42ce9e973) and introduce a new unit test to check the sanity of the output payload against large roto-translations (at 7818525b328440829f8b3c1bd67ae638c1c48f5e)

#### PR validation:

Run the unit tests introduced here and compared the output payloads with respect to the input one. Results (obtained from the payload inspector) are collected:
   * [here](http://musich.web.cern.ch/musich/display/comparison_PromptVsAlignmentCRAFT22/old/): before the fix
   * [here](http://musich.web.cern.ch/musich/display/comparison_PromptVsAlignmentCRAFT22/fixed/): after the fix
   
Here is a couple of plots selected from the folders above (**notice the scale**).   

| Before the fix | After the fix |
| ------------- | ------------- |
|  image | image |

  
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but a backport will be needed to all production cycles after 12_2_X.

cc:
@consuegs @antoniovagnerini @connorpa

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
+1
- The author and the AlCa experts have verified that the output posted in the PR description actually corresponds to what expected after the bug fix

**Pull request merged**
