### PR TITLE
Fixes for RunInfo O2O and cleanup of PopCon interface (80X)

### PR DESCRIPTION
**Pull request by diguida**
The RunInfo O2O has been modified: 
- Make the tag population in synch with the `CondDBv2` tag policy. In https://github.com/diguida/cmssw/blob/fix_RunInfo_and_PopCon/CondCore/CondDB/src/IOVEditor.cc#L189-L201, as specified in the comment too, if the tag has synchronisation `ANY` or `VALIDATION`, IOV insertion in the past or overriding are allowed, while they are forbidden (an exception is thrown) for "production" tags. The RunInfo code is now protected so that it first tests the input run number against the last IOV of the target tag: if the new run number is smaller than or equal to the latest IOV in the target tag, the job exits, and no new IOVs are added irrespectively of the synchronisation;
- Use `CondCore` API as defined in `ConnectionPool` in order to authenticate `Oracle` access via roles, instead of the `CORAL` API in `RelationalAccess`;
- Improve queries by performing joins on PK-FK (query time improved by factor 2);
- Throw exceptions in case CORAL fails to execute a query;
- Improve logging messages;
- Improve code style;
- Review the configuration file to be fully complaint with the O2O online framework.

Removed a dead data member in PopCon.

Added a comment in `CondCore/CondDB/src/IOVEditor.cc` clarifying the tag update policy w.r.t. tag synchronisation.

Back port of #14420 with one difference: use `boost::shared_ptr` instead of `std::shared_ptr` in https://github.com/cms-sw/cmssw/compare/CMSSW_8_0_X...diguida:fix_RunInfo_and_PopCon_80X#diff-d0d2d7d67286c9941ff28996f956d33cR71 due to smart pointer `boost -> std` migration in `CMSSW_8_1_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
The failures are unrelated to this PR, and the tests done on top of `CMSSW_8_0_7` with `git cms-checkdeps -a` were ok:

````
$ git cms-checkdeps -a
>> Checking CondCore/CondDB CMSSW_8_0_7
   x CondCore/CondDB/src/IOVEditor.cc
>> Checking CondCore/PopCon CMSSW_8_0_7
   x CondCore/PopCon/interface/PopCon.h
   x CondCore/PopCon/src/PopCon.cc
>> Checking CondTools/RunInfo CMSSW_8_0_7
   x CondTools/RunInfo/interface/RunInfoHandler.h
   x CondTools/RunInfo/interface/RunInfoRead.h
   x CondTools/RunInfo/src/RunInfoHandler.cc
   x CondTools/RunInfo/src/RunInfoRead.cc
   x CondTools/RunInfo/test/RunInfoPopConAnalyzer.py
Checking out these packages: 12
CalibMuon/CSCCalibration (header)
CondTools/DQM (header)
CondTools/DT (header)
CondTools/Ecal (header)
CondTools/Hcal (header)
CondTools/RPC (header)
CondTools/SiPixel (header)
DQM/SiStripHistoricInfoClient (header)
DQMOffline/CalibTracker (header)
DQMServices/Diagnostic (header)
OnlineDB/CSCCondDB (header)
OnlineDB/SiStripO2O (header)
$ scram b -r -j 32
````
Let's have a look to the warnings:
````
In file included from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleReader.cc:1:0:
/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-05-08-0000/src/CondFormats/SiPixelObjects/interface/SiPixelQuality.h:1:1: warning: null character(s) ignored
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 ^
...
In file included from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SealModules.cc:14:0:
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.h:10:65: warning: /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-05-08-0000/src/CondFormats/SiPixelObjects/interface/SiPixelQuality.h is shorter than expected
...
In file included from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.cc:1:0:
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.h:10:65: warning: /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-05-08-0000/src/CondFormats/SiPixelObjects/interface/SiPixelQuality.h is shorter than expected
````
these ones are not visible in the [base build](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_0_X_2016-05-08-0000/CondTools/SiPixel)

````
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelGainCalibrationRejectNoisyAndDead.cc: In member function 'void SiPixelGainCalibrationRejectNoisyAndDead::fillDatabase(const edm::EventSetup&)':
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelGainCalibrationRejectNoisyAndDead.cc:236:32: warning: comparison of constant '2' with boolean expression is always false [-Wbool-compare]
  else if(insertnoisypixelsindb_==2){
                                ^
````
This one is visible in the [base build](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_0_X_2016-05-08-0000/CondTools/SiPixel)

The errors are:
````
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleReader.cc: In member function 'virtual void SiPixelBadModuleReader::analyze(const edm::Event&, const edm::EventSetup&)':
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleReader.cc:43:17: error: 'SiPixelQuality' was not declared in this scope
   edm::ESHandle<SiPixelQuality> SiPixelBadModule_;
                 ^
[plus all the chain]
...
In file included from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.cc:1:0:
/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-05-08-0000/src/CondTools/SiPixel/test/SiPixelBadModuleByHandBuilder.h:16:64: error: 'SiPixelQuality' was not declared in this scope
 class SiPixelBadModuleByHandBuilder : public ConditionDBWriter<SiPixelQuality> {
                                                                ^
[plus all the chain]
````

Running now on top of `CMSSW_8_0_X_2016-05-08-0000` with `git cms-merge-topic` to try to reproduce the issue.

**Comment by smuzaffar** [comment]
please test
looks like it was CVMFS issue on vocms0302

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
