### PR TITLE
Egm id 747 v1

### PR DESCRIPTION
**Pull request by skyriacoCMS**
Hello Ilya, 

Please take a look. Especially on the Cuts them selves. Now we have pt scaling in the nEutral hadron end cap too. 

-Savvas

### CODE REVIEW

**Comment by slava77** [comment]
-1
doesn't merge and needs a rebase .. or submitted to a wrong development branch (went to 76X)

**Comment by diguida** [comment]
-1
74X branch requested to merge a 76X vanilla.

**Comment by lgray** [comment]
@skyriacoCMS Please close this pull request and make a pull request directly to @ikrav's branch. We will release it to CMSSW later.

**Comment by lgray** [comment]
@slava77 This branch was not meant to be distributed in this way.

**Comment by skyriacoCMS** [comment]
Hello All,

I think I totaly messed up the PR.
I will indeed make a pull request to @ikrav directly.


-Savvas

**Comment by lgray** [comment]
@skyriacoCMS Can you please click the "close pull request" button at the bottom of the webpage? :-)

**Pull request closed without merging**
