### PR TITLE
clang check modernize-loop-convert

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check modernize-loop-convert does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by VinInn** [comment]
good luck...

**Comment by slava77** [comment]
-1
good thing, but there are apparently failure modes and inspection on the web is not trivial due to the size of this PR

**Comment by ianna** [comment]
-1

just to take of my list

**Pull request closed without merging**
