### PR TITLE
Run3-trk08 Make sure the dd4hep algorithms provide the namespace to all created solids/volumes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make sure the dd4hep algorithms provide the namespace to all created solids/volumes

#### PR validation:

Used one of the scripts from standard test workflows for run3

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
This PR is a large perturbation of the names used in the DD4hep geometry. It is, in general, a good idea to add namespaces to the names to ensure uniqueness, but, at this late stage, there are dangers. There may be code we are not noticing that includes hard-coded references to particular names that this PR is changing.

The duplicate name problem is limited to the following solid names:

TECModule0Hybrid
TECModule0SideFrameLeft
TECModule0SideFrameRight
TECModule1Hybrid
TECModule1SideFrameLeft
TECModule1SideFrameRight
TECModule4Hybrid
TECModule4SideFrameLeft
TECModule4SideFrameRight

I suggest adding the namespace to these names only to avoid possible unforeseen consequences from a more comprehensive change.

**Comment by bsunanda** [comment]
All codes which depend on names get rid of namespace if it is a dd4hep. We have to revalidate all dd4hep workflows. I am starting with basic geometry comparisons which have found more issues than the detailed validation runs

**Comment by civanch** [comment]
@bsunanda , @cvuosalo , are there the same problems when we run from XML without DB?

**Comment by civanch** [comment]
+1

after discussion at https://indico.cern.ch/event/992973/?showDate=all&showSession=2 we decide merge this PR, which provides correct efficiency in tracker. @cvuosalo, other problems may be fixed on top of it.

**Comment by perrotta** [comment]
+1

**Pull request merged**
