### PR TITLE
extend the static analysis for the 'modules to thread unsafe statics'…

### PR DESCRIPTION
**Pull request by gartung**
… to also include the following additional member functions of modules

	streamBeginRun
	streamBeginLuminosityBlock
	streamEndRun
	streamEndLuminosityBlock

	globalBeginRun
	globalEndRun
	globalBeginLuminosityBlock
	globalEndLuminosityBlock

	endRun
	endLuminosityBlock

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
