### PR TITLE
Updated IVF vertex arbitration

### PR DESCRIPTION
**Pull request by ferencek**
This PR updates the arbitration step in the IVF secondary vertex reconstruction by requiring all vertices to have at least two tracks with weight>0.5. This change ensures we do not end up with any single-candidate vertices (when vertices are candidate-based, i.e. stored as `reco::VertexCompositePtrCandidate`, only vertex tracks with weight>0.5 are kept. Hence, for vertices consisting of two tracks where one track has weight<0.5 a single-track vertex is produced).

This PR also affects secondary vertices stored as `reco::Vertex`. The difference here is that, in contrast to `reco::VertexCompositePtrCandidate`, `reco::Vertex` actually stores the track weights so vertices consisting of two tracks where one track has weight<0.5 are still kept as two-track vertices. However, since in track counting and computing the vertex kinematics only tracks with w>0.5 are taken into account, it is better to apply the same requirement also to secondary vertices stored as `reco::Vertex`. In this way both types of secondary vertices are treated in the same way.

This PR is expected to produce small changes in the size of the IVF secondary vertex collection. However, the IVF-based b-tag discriminators are expected to remain unchanged since they already require secondary vertices with at least two tracks with weight>0.5.

@arizzi

### CODE REVIEW

**Comment by ferencek** [comment]
@arizzi, please express if you are happy with this implementation.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
ok with me

**Comment by cvuosalo** [comment]
+1

For #13140 d9a6d9b6e57e9a12850233d0d20d74901448f286

Require secondary vertices to have two good tracks, instead of only one that was allowed previously.

The code changes are satisfactory. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13140/10906/summary.html) against baseline CMSSW_8_0_X_2016-02-01-1100 show no significant differences except for the expected loss of a few secondary vertices, at the level of a few percent.

**Pull request merged**
