### PR TITLE
Replace auto_ptr with unique_ptr in CloneProducer.h

### PR DESCRIPTION
**Pull request by Teemperor**
The Event class doesn't accept auto_ptrs anymore, but instead
unique_ptrs, so we need to change this type.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by Dr15Jones** [comment]
line 56 should be changed to
```
evt.put( std::move(coll) );
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19276	8024b50
- technical
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
