### PR TITLE
New GT for PF corrections plus fixes for Run2 MC production.

### PR DESCRIPTION
**Pull request by diguida**
New Global Tags including updated set of PF corrections for E-gamma and hadrons, and a couple of fixes for Run2 MC production.

### CODE REVIEW

**Comment by davidlange6** [comment]
@diguida - could you remind me what the need for this GT update was?

< L1RCTParametersRcd L1RCTParameters L1RCTParameters_Collisions_NewEmax_v0_mc
---
> L1RCTParametersRcd L1RCTParameters L1RCTParameters_Collisions_NewHoeEic_v0_mc

**Comment by diguida** [comment]
@davidlange6 this was announced on AlCa hn: it is a bug fix for the RCT parameters in order to reproduce the behaviour of the firmware in the L1T emulator.

Hope this clarifies

**Comment by franzoni** [comment]
Only for info, what was the decision about the castor gain?

**Comment by diguida** [comment]
@franzoni as discussed during the PPD meeting and finalised with PPD coordination, we decided to add the CASTOR gains, as they can be considered as bug fixes (avoid saturation of CASTOR digis).
I am finishing the documentation, I will explain it there and put a link to the CASTOR presentation.

**Comment by franzoni** [comment]
Thanks for info

**Comment by davidlange6** [comment]
@diguida - Thanks - as I don't see anything in that thread indicating that we should expect large changes, I'll ask there for confirmation.

**Pull request closed without merging**
