### PR TITLE
removed assert

### PR DESCRIPTION
**Pull request by shervin86**
backport of #17955 
Removed assert

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by franzoni** [comment]
Thanks @shervin86
Should the check rather be updated, instead of removed?

**Comment by franzoni** [comment]
Some description in pr opening is always welcome

**Comment by franzoni** [comment]
😀

**Comment by shervin86** [comment]
Dear Giovanni, I did not put any comment because I consider that removal of asserts should always be a good thing. In my modest opinion asserts can be only used at development stage, like in this case, but should be removed when put in production. This plugin has been used for 1 year as part of the AlCaElectron Stream run by the HLT and hence it's evident that the assert is completely useless.  I suspect it was copied from some test analyzer of the tracker/pixel group and included in this pluging when developing.
Regards,

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
