### PR TITLE
Run3-hcx375 Extend the topology modes to accommodate different scenarios during the Run2 period

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend the topology modes to accommodate different scenarios during the Run2 period

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
