### PR TITLE
[CPP20][GEOMETRY] Replace some enums with constexpr ints

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Replace some enums with constexpr ints to avoid deprecated enum arithmetics. Replaces https://github.com/cms-sw/cmssw/pull/44488 following @makortel's suggestion.

#### PR validation:

Bot tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by iarspider** [comment]
RelVal failures are unrelated.

**Comment by iarspider** [comment]
please test
let's retrigger to get clean tests

**Comment by bsunanda** [comment]
+geometry

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
