### PR TITLE
L1t updates 74x v2

### PR DESCRIPTION
**Pull request by mulhearn**
This is a rebase of #7511 . This is the main updates for L1T software aimed at release 74X. In includes updates to algorithms, unpackers, and parameters.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
bypassing given that whitespace changes have added a number of signatures

**Comment by davidlange6** [comment]
@mulhearn - I would suggest that the constructs involving std::vector<blah> blah should all be replaced by std::vector<blah> var as to be more maintainable. I don't see any reason to new and delete these constantly (hoping that everyone remembers the delete part..)

**Pull request merged**
