### PR TITLE
[13_0 backport] Add 2023 DD4hep XML wf

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/40881
This PR needs to test with https://github.com/cms-sw/cmssw/pull/40866

#### PR validation:
Configuration dump of 12434.911

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This is a backport PR.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflow = 12434.911
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano,gpu
- pull_request = https://github.com/cms-sw/cmssw/pull/40866

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Backport PR. The 12434.911 (Run3 2023 DD4hep XML) runs fine.

**Comment by rappoccio** [comment]
@cms-sw/pdmv-l2 any objections to merge this one? Please approve at your earliest convenience.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40881

**Pull request merged**
