### PR TITLE
Backport of "Fix for FastSim decays of exotic-descendent SM particles decaying outside pipe" to 9_4_X

### PR DESCRIPTION
**Pull request by cericeci**
#### PR description:

Backport of  #36122 and #36324 for preUL 2017 FastSim production. Full functionality of both, without the code formatting. Please check #36352 (backport to UL branch) first

This fixes a bug which would invalidate simulation for long-lived and a fraction of prompt signals (and luckily was introduced very recently, so most of the previous production is safe). Our understanding is that this case doesn't go against the no-change policy.

Original PR description: Jaebak found that some b- and d-mesons produced in the decays of exotic particles, which cross the beam pipe radius, have their decay performed twice, with sim hits created for each copy. This causes problems for some high-pT b-jets, as well as the MET in events that contain such jets. A few lines are added to ParticleManager.cc which results in FastSim deciding to not decay such particles further, and rather take only the original generator-determined decay trees. FastSim will still propagate these particles and create secondaries/material interactions, but it won't decay them.

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

#36122 and #36324, needed for preUL 2017 MC production (most notably pMSSM scan)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
-1
This PR is "fully signed", but it misses the necessary customization with the modifiers if it wants to be backported in a closed production release. In order not to merge it "by mistake" let have it orp-rejected by now. The flag will be overwritten if and when a modification will be implemented in the PR

**Comment by cericeci** [comment]
Same as https://github.com/cms-sw/cmssw/pull/36353, but checked on CMSSW_9_4_X_2022-01-09-0000 instead

**Comment by perrotta** [comment]
please test

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by cericeci** [comment]
Hi @perrotta, thanks for merging this one. What is the policy/estimated time for this to make it into a new release? As I said at the start this would be needed for a few lingering preUL samples (namely pMSSM scan, that involves already finished analysis that used preUL). Should we bring this discussion to PPD instead?

**Comment by perrotta** [comment]
> Hi @perrotta, thanks for merging this one. What is the policy/estimated time for this to make it into a new release? As I said at the start this would be needed for a few lingering preUL samples (namely pMSSM scan, that involves already finished analysis that used preUL). Should we bring this discussion to PPD instead?

@cericeci I've started building CMSSW_9_4_21_patch1 and CMSSW_10_2_28 with these fixes in
They will become available either by this evening or tomorrow

**Comment by cericeci** [comment]
Many thanks @perrotta  !

**Comment by perrotta** [comment]
Even faster that I could imagine:
https://github.com/cms-sw/cmssw/releases/CMSSW_9_4_21_patch1

**Pull request merged**
