### PR TITLE
Addition of postEE Wfs [12_6_X]

### PR DESCRIPTION
**Pull request by sunilUIET**
#### PR description:

This is a backport of #40151 to add post-EE WFs
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of #40151 to add post-EE WFs

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40151

**Comment by perrotta** [comment]
test parameters:
- workflow = 13634.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by perrotta** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
