### PR TITLE
Prefetch for EDLoopers

### LINKED ISSUE #34223: test_PixelBaryCentreTool test fails
The `test_PixelBaryCentreTool` test started to fail in CMSSW_12_0_X_2021-06-22-2300 following the merge of #33583 (as reported in the PR)
```
' looking for alignment labels ''.
Finds tag HCAL : 1
%MSG-i HCAL:  (NoModuleName) 23-Jun-2021 08:40:36 CEST pre-events
CaloTowerTopologyEP::CaloTowerTopologyEP
%MSG
' looking for alignment labels ''.
%MSG-i Alignments:  (NoModuleName) FakeAlignmentProducer()  23-Jun-2021 08:40:37 CEST pre-events
Providing data with label 'fakeForIdeal'.
%MSG
GEMGeometryESModule::initailized with flags 1:0
%MSG-i SiPixelQualityESProducer::SiPixelQualityESProducer:  (NoModuleName)  23-Jun-2021 08:40:37 CEST pre-events

%MSG
%MSG-i SiStripBackPlaneCorrectionDepESProducer:  (NoModuleName)  23-Jun-2021 08:40:37 CEST pre-events
ctor
%MSG
%MSG-i SiStripLorentzAngleDepESProducer:  (NoModuleName)  23-Jun-2021 08:40:37 CEST pre-events
ctor
%MSG
%MSG-i SiStripQualityESProducer:  (NoModuleName) 23-Jun-2021 08:40:37 CEST  pre-events
ctor
%MSG
%MSG-i Geometry:  (NoModuleName) TrackerDigiGeometryESModule()  23-Jun-2021 08:40:37 CEST pre-events
Label 'idealForDigi' IGNORING alignment labels 'fakeForIdeal'.
%MSG
%MSG-i TRACKER:  (NoModuleName) 23-Jun-2021 08:40:38 CEST pre-events
TrackerTopologyEP::TrackerTopologyEP
%MSG
----- Begin Fatal Exception 23-Jun-2021 08:40:41 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing Looper: class=AlignmentProducer label='@main_looper'
Exception Message:
A module declared it consumes an EventSetup product after its constructor.
This must be done in the contructor
The product type was: TrackerTopology in record TrackerTopologyRcd
and ESInputTag was Module label:  Data label:
----- End Fatal Exception -------------------------------------------------
```

The #33583 was the first(?) PR to declare EventSetup consumes in EDLoopers after that was allowed by #33337.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Do asynchronous prefetching for EDLoopers. This is needed to support the ESGetToken usage.

#### PR validation:

The framework unit tests run and the unit test failing in the IB where the auto-generated test file 
```
tmp/PixelBaryCentreTool/alignment_forGeomComp_auto:run2_data_TrackerAlignment_2009_v1_express_r272011_1.py
```
was failing now works.

fixes #34223

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/alca-l2 please review so we can fix the failing unit tests in the IB.

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
