### PR TITLE
Remove IgProfModule as obsolete

### LINKED ISSUE #207: Remove IgProfModule as obsolete
Done in https://github.com/cms-sw/cmssw/pull/34653

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR suggests to remove `IgProfModule`. From history in https://github.com/cms-cvs-history/IgTools-IgProf this seems to have been replaced with `IgProfService` long time ago. Also twiki searches show nothing on `IgProfModule`, while `IgProfService` gets hits.

Resolves https://github.com/makortel/framework/issues/207

#### PR validation:

None

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Differences are in 140.53 that had different input files compared to the baseline.

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical, no changes in outputs

**Pull request merged**
