### PR TITLE
More ICC cleanups

### PR DESCRIPTION
**Pull request by ktf**
This PR does two things:
- Comments out unused method arguments, which ICC complains about.
- Disables our "intrinsics" based math for ICC, and leaves to the compiler the task of optimising things.

`gcc` version should be completely unaffected by these changes.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7501	8069c4f
code diff is visually ok, jenkins managed to compile this and run as well
(comparisons are still not around though :( )

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@ktf, @Dr15Jones  - are you happy with this PR? (You made it..)

**Comment by ktf** [comment]
+1

**Pull request merged**
