### PR TITLE
l1To2o fixes in EMTF and BMTF - 101x - v2

### PR DESCRIPTION
**Pull request by thomreis**
backport of #22716 

PR 101X
This PR contains:

 - PR #20939
 - PR #22669
 - A small change in fakeEmtfParams_cff.py that allows running on conddb machines at P5.

### CODE REVIEW

**Comment by thomreis** [comment]
+1

**Comment by rekovic** [comment]
@ggovi please sign.  This has been running at P5 and is part of 10_2_0_pre1.
We would like it as part of the centrally ran O2O.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
