### PR TITLE
[LLVM10] Fix compilation warnings for L1/DQM/Upgrade packages

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

- Fixed loop variable copy warning generated in CLANG IBs

#### PR validation:

Local build for both CLANG and normal IBs look good

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
merge
FYI @rekovic @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
