### PR TITLE
80X HLT July 29th train

### PR DESCRIPTION
**Pull request by perrotta**
Update the HLT menu up to master table /dev/CMSSW_8_0_0/HLT/V453, i.e. pp menus
- /frozen/2016/25ns15e33/v3.1/HLT/V3
- /online/collisions/2016/25ns15e33/v3.1HLT/V6

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test
(DAS error)

**Comment by Martin-Grunewald** [comment]
@perrotta @davidlange6 
Why is this PR not being integrated? Please do so!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_8_0_17 and another test file update

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
