### PR TITLE
Rewrite tracking MC validation scripts

### PR DESCRIPTION
**Pull request by makortel**
This PR contains a rewrite of the tracking validation scripts. Main new features are
- implemented completely in python (it is also faster)
- separate script for vertex plots, using the same infrastructure
- the required DQM files are downloaded semi-automatically
- allows to produce plots for a single validation campaign by running the script only once
  - earlier one had to run the script many times toggling various variables back and forth to cover all samples
- easier to maintain (both for new campaigns and new plots)

I have been using the script for tracking validation since 72X, so this is mainly to get it integrated for easier use by others.

Should not have any effect on standard workflows.

@rovere @VinInn

### CODE REVIEW

**Comment by deguio** [comment]
@makortel are the old script leaving in release?
in case can they be removed?

thanks,
F.

**Comment by makortel** [comment]
@deguio When I started the rewrite I thought to keep the old stuff for some time in case somebody would still like to use them. But I agree now that its probably better to just remove them (e.g. to avoid confusion). They can anyway be taken from old releases/git history if someone's private workflow depends on them.

**Comment by makortel** [comment]
Fixed the merge conflicts by not removing the `_cfg.py` files (didn't want to rebase as having the branch based on 740pre1 has some value).

**Comment by deguio** [comment]
+1
thanks @makortel

**Comment by davidlange6** [comment]
+1

**Pull request merged**
