### PR TITLE
Fixed Non Planar Trapezoids

### PR DESCRIPTION
**Pull request by slomeo**
#### PR description:

see closed PR #31837 : in this PR only muonYoke.xml has been modified.

#### PR validation:

see closed PR #31837 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

nothing special

### CODE REVIEW

**Comment by slomeo** [comment]
please @civanch, @cvuosalo, @ianna , @bsunanda, @etcherniaev perform a "please test"

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

was discussed with geometry group

**Comment by qliphy** [comment]
+1

**Pull request merged**
