### PR TITLE
[TkAl] miscellaneous updates related to analysis of μμ + vertex events (13.2.X)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/42459
backport of https://github.com/cms-sw/cmssw/pull/42971

#### PR description:

See initial descriptions in master PRs.

#### PR validation:

`cmssw` compiles 
 
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/42459 and https://github.com/cms-sw/cmssw/pull/42971 to the last 2023 data-taking release.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
The apparent failure in [TestDQMOfflineConfigurationGotAll](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-090931/35108/unitTests/src/DQMOffline/Configuration/test/TestDQMOfflineConfigurationGotAll/testing.log) is a pre-existing issue (documented at https://github.com/cms-sw/cmssw/issues/42831).

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42971
(let the "backport" status depend on the more recent, and by now not yet merged, PR)

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cms-sw/alca-l2 and @cms-sw/dqm-l2 let not the unrelated failure slow down the review!

**Comment by mmusich** [comment]
please test with https://github.com/cms-sw/cmssw/pull/42983

**Comment by perrotta** [comment]
+alca
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/42459 and https://github.com/cms-sw/cmssw/pull/42971

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
