### PR TITLE
[81X] update SiPMCharacteristics for phase-I Global Tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v18) as [81X_upgrade2017_realistic_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v18/81X_upgrade2017_realistic_v17): 
  - update non-linearity parameters in `SiPMCharacteristics`
- **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v2) as [81X_upgrade2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v2/81X_upgrade2017_design_IdealBS_v1): 
  - update non-linearity parameters in `SiPMCharacteristics`

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
no changes foreseen until #16315 is merged

**Comment by kpedro88** [comment]
@mmusich thanks!

@davidlange6 @slava77 as soon as this is in an IB, we can do a full test of #16315

**Comment by davidlange6** [comment]
+1

**Pull request merged**
