### PR TITLE
CTPPS Geometry Payload Default Label

### PR DESCRIPTION
**Pull request by ianna**
* CTPPS geometry payload in a DB has a "CTPPS" label. Set is as a default in python configuration fragment.

@fabferro  - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by fabferro** [comment]
@ianna 

Shouldn't the producer name be XMLIdealGeometryESProducer?
XMLIdealCTPPSGeometryESProducer seems wrong to me...

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
