### PR TITLE
MTD validation: add histograms for particle identification monitoring

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR proposes and extension of the MTD validation code, primarily in the ```Primary4DVertexValidation``` class, adding a set of plots to study the particle identification performances based on the 4D vertex reconstruction. This code has been used as an input to AN-22-060.

The memory impact of this addition is of the order of 10 kB, as provided by ```dqmMemoryStats.py```:

```
158d157
< 38.23 KiB        MTD/Vertices
166a166
> 28.86 KiB        MTD/Vertices
361c361
< Total bytes: 412461.59 KiB
---
> Total bytes: 412452.22 KiB
```

#### PR validation:

Phase 2 test workflows  compile and run, providing the desired output. Private samples of O(50k) events with PU have been produced with these updates.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
