### PR TITLE
HCAL DQM update for 8_4_X

### PR DESCRIPTION
**Pull request by DryRun**
Some updates for HCAL DQM:

- Inconsistency between emap and RecHits after collapsing resulted in missing channels in ieta-iphi plots. Removed a hard check on the channels, so missing channels should appear.
- Add QIE11 digis (aka HEP17) to DigiTask.
- Remove QIE10Task (redundant with DigiTask, QIE10==HF now) and ZDCTask.
- Fixed crashing hcalcalib (GeometryIdeal --> GeometryRecoDB).

@vkhristenko @deguio

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
I just committed a patch to fix a crash in RecHitTask - removing the requirement that channels be present in the emap led to attempts to fill electronics channel plots with nonexistent electronics channels (i.e. eid==0). I reintroduced the consistency check for these histograms only.

Also, I see that some tests failed with the following error, which doesn't look like a problem with the PR itself:

----- Begin Fatal Exception 13-Mar-2017 12:08:42 CET-----------------------
An exception of category 'FormatIncompatibility' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
The release you are using, "CMSSW_8_4_0_patch2" , predates
a release ("CMSSW_9_0_0_pre4") used in writing the input file, root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_0_0_pre4/RelValMinBias_13/GEN-SIM/90X_mcRun2_asymptotic_v1-v1/10000/80A7D7A4-65EA-E611-9F23-0CC47A4D765E.root.
Forward compatibility cannot be supported.
----- End Fatal Exception -------------------------------------------------

**Comment by dmitrijus** [comment]
You need to commit this change into development branch, or 91x (master branch). Tests should not fail there.

**Comment by DryRun** [comment]
OK, thank you, I will do that.

**Comment by slava77** [comment]
-1

from the context, it looks like updates are only to  DQM/HcalTasks/plugins/RecHitTask.cc 
and the other signatures are dragged in by an inappropriate merge

**Pull request closed without merging**
