### PR TITLE
DQM perLS in one shot (part 2)

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Continuation of PR https://github.com/cms-sw/cmssw/pull/41196 following comment by @makortel  on 

https://github.com/cms-sw/cmssw/pull/41196/files#r1165933719

#### PR validation:

Same as in https://github.com/cms-sw/cmssw/pull/41196 , the changes in this PR are purely technical

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by jfernan2** [comment]
I believe this PR is good to go.
Thanks

**Comment by jfernan2** [comment]
ping @cms-sw/dqm-l2

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
