### PR TITLE
PPS fix to comply to EDModule rules

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

Fix in two PPS files to comply to EDModule rules.
Removed inclusion of unneeded deprecated EDProducer headers.

#### PR validation:

It compiles and works/

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * diffs in MsgLogger only

**Comment by qliphy** [comment]
+1

**Pull request merged**
