### PR TITLE
Handling of FOG special HLT menus [141X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Handling of FOG special HLT menus [141X]

https://its.cern.ch/jira/browse/CMSHLT-3092 : Completion of the offline "Special" table and lists of paths for individual special menus

See also discussion here:
https://docs.google.com/document/d/1XxsH3qXt7ZO4LIuwQg-I-Lp5rekkWsxSEG_Mwv1nh0Q/edit#heading=h.p0nxi1qdtn0t

#### PR validation:

Executing scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_0

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
@Martin-Grunewald we need to update this file:

https://github.com/cms-sw/cmssw/blob/d94472d244ac7f8842e84c708d26e5ca0d7457b2/HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh#L70-L75

with

```diff
diff --git a/HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh b/HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh
index ec10cbfdf10..73a9e19e2e6 100755
--- a/HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh
+++ b/HLTrigger/Configuration/test/test_OnlineVsDevTablesConsistency.sh
@@ -70,6 +70,13 @@ TABLES_AREA="$CMSSW_BASE/src/HLTrigger/Configuration/tables"
 compare_files $TABLES_AREA/online_pion.txt $TABLES_AREA/PIon.txt || die "Failure comparing online_pion and PIon" $?
 compare_files $TABLES_AREA/online_hion.txt $TABLES_AREA/HIon.txt  || die "Failure comparing online_hion and HIon" $?
 compare_files $TABLES_AREA/online_pref.txt $TABLES_AREA/PRef.txt  || die "Failure comparing online_pref and PRef" $?
-compare_files $TABLES_AREA/online_cosmics.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_cosmics and Special" $?
-compare_files $TABLES_AREA/online_special.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_special and Special" $?
+compare_files $TABLES_AREA/online_Circulating.txt  $TABLES_AREA/Special.txt  || die "Failure comparing online_Circulating and Special" $?
+compare_files $TABLES_AREA/online_PPS.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_PPS and Special" $?
+compare_files $TABLES_AREA/online_LumiScan.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_LumiScan and Special" $?
+compare_files $TABLES_AREA/online_FirstCollisions.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_FirstCollisions and Special" $?
+compare_files $TABLES_AREA/online_ECALTiming.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_ECALTiming and Special" $?
+compare_files $TABLES_AREA/online_Cosmics.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_Cosmics and Special" $?
+compare_files $TABLES_AREA/online_TrackerVR.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_TrackerVR and Special" $?
+compare_files $TABLES_AREA/online_Splashes.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_Splashes and Special" $?
+compare_files $TABLES_AREA/online_Special.txt $TABLES_AREA/Special.txt  || die "Failure comparing online_Special and Special" $?
 compare_files $TABLES_AREA/online_grun.txt $TABLES_AREA/GRun.txt  || die "Failure comparing online_grun and GRun" $?
```

**Comment by Martin-Grunewald** [comment]
OK...

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
@cms-sw/hlt-l2 
Are these also automatically generated?
Are there corresponding JIRA tickets?

**Comment by Martin-Grunewald** [comment]
@antoniovilela 
I have updated the description of the PR with the single JIRA ticket.
The added files are used to create online menus for special running conditions (aka special menus) by containing the list of desired paths. These txt files are maintained by hand. The check is that the created menus contain the required paths.

**Comment by antoniovilela** [comment]
> @antoniovilela I have updated the description of the PR with the single JIRA ticket. The added files are used to create online menus for special running conditions (aka special menus) by containing the list of desired paths. These txt files are maintained by hand. The check is that the created menus contain the required paths.

Thanks.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
