### PR TITLE
Remove trackingMaterialGroups_ForPhaseII.xml from T25/T26 dict

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This removes an XML for material budget analysis from two recent tracker geometries (T25, T26; incorporated in D80 and D81). The file is not compatible with these geometries and leads to a few warnings in the standard workflows (not picked up when originally integrating these geometries). While the actual results of the workflows are not affected, it's best to remove these files to avoid triggering the warnings.

@emiglior fyi

#### PR validation:

Compared figures (IT, OT, tracking) in the DQM output  wf 36634.0 with and without trackingMaterialGroups_ForPhaseII included to ensure the results are the same. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

### CODE REVIEW

**Comment by mmusich** [comment]
@adewit out of curiosity, what messages was it giving?
This sounds related to this https://github.com/cms-sw/cmssw/pull/31112#discussion_r472855933

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by adewit** [comment]
> @adewit out of curiosity, what messages was it giving?
> This sounds related to this [#31112 (comment)](https://github.com/cms-sw/cmssw/pull/31112#discussion_r472855933)

@mmusich it's exactly the same issue (so e.g.
```
%MSG
%MSG-e Specific:  AfterModGlobalBeginRun 12-Apr-2021 17:47:57 CEST Run: 1
Could not process q-name of a DDLogicalPart, reason:
No regex-match for namespace=  name=ITLayer1R2BModuleInnerPixelActive
```
)

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
