### PR TITLE
[13_2_X] Include ECAL Timing CC labelled tags in Run3 data and MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:

See master PR for details https://github.com/cms-sw/cmssw/pull/42958. The PR is complementary to https://github.com/cms-sw/cmssw/pull/42946 

An additional change with respect to the master PR
- 2023 HI MC GT updated 
   - to bring it upto date with 2023 postBPIx MC conditions (except the HI specific) ([Diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_HI_v2/132X_mcRun3_2023_realistic_HI_v3)) See CMS Talk post [1]. 
   - Add new L1T HI menu tag `L1Menu_CollisionsHeavyIons2022_v1_1_0-d1_xml` requested in [2] ([See diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_HI_v4/132X_mcRun3_2023_realistic_HI_v5))

For the master, a separate PR will be opened to update these changes

[1] https://cms-talk.web.cern.ch/t/call-for-conditions-for-2023-heavy-ion-mc/30455
[2] https://cms-talk.web.cern.ch/t/request-to-include-the-hi-l1-menu-in-the-run3-hi-mc-gt/21665

**GT Differences**
- **Run3 data HLT** : No change, just updated snapshot time
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_HLT_frozen_v2/132X_dataRun3_HLT_frozen_v1
  - Diff from current 132X HLT GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_HLT_frozen_v2/132X_dataRun3_HLT_v2
  
- **Run3 data Express** : Includes Ecal Timing CC labelled tags and updates it to sync with current Express GT with new snapshot time 
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Express_frozen_v2/132X_dataRun3_Express_frozen_v1
  - Diff from current 132X Express GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Express_frozen_v2/132X_dataRun3_Express_v4 

- **Run3 data Prompt** : Includes Ecal Timing CC labelled tags and updates it to sync with current Express GT with new snapshot time 
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Prompt_frozen_v2/132X_dataRun3_Prompt_frozen_v1
  - Diff from current 132X Prompt GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Prompt_frozen_v2/132X_dataRun3_Prompt_v4 

- **Run3 data Offline** : Includes Ecal Timing CC labelled tags and updates the ES Channel status tag to ESChannelStatus_V05_offline to fix the wrong IOV upload 375472 instead of 374572
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_v2/132X_dataRun3_v1

- **Phase1 2022 design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022_design_v2/132X_mcRun3_2022_design_v1

- **Phase1 2022 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022_realistic_v3/132X_mcRun3_2022_realistic_v2

- **Phase1 2022 realistic postEE** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022_realistic_postEE_v3/132X_mcRun3_2022_realistic_postEE_v2

- **Phase1 2022 cosmics** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022cosmics_realistic_deco_v3/132X_mcRun3_2022cosmics_realistic_deco_v2

- **Phase1 2022 cosmics design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022cosmics_design_deco_v2/132X_mcRun3_2022cosmics_design_deco_v1

- **Phase1 2022 realistic hi** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2022_realistic_HI_v2/132X_mcRun3_2022_realistic_HI_v1

- **Phase1 2023 design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_design_v2/132X_mcRun3_2023_design_v1

- **Phase1 2023 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_v5/132X_mcRun3_2023_realistic_v4

- **Phase1 2023 realistic postBPix** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_postBPix_v4/132X_mcRun3_2023_realistic_postBPix_v3

- **Phase1 2023 cosmics reaslistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023cosmics_realistic_deco_v4/132X_mcRun3_2023cosmics_realistic_deco_v3

- **Phase1 2023 cosmics design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023cosmics_design_deco_v2/132X_mcRun3_2023cosmics_design_deco_v1

- **Phase1 2023 realistic hi** : Includes Ecal Timing CC labelled tags and update of 2023 MC conditions (See above)
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_HI_v5/132X_mcRun3_2023_realistic_HI_v2

- **Phase1 2024 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2024_realistic_v3/132X_mcRun3_2024_realistic_v2

- **Phase2** : Includes Ecal Timing CC labelled tags 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun4_realistic_v9_0/131X_mcRun4_realistic_v6

#### PR validation:

Tested successfully with 
- `runTheMatrix.py -l 138.2,138.4,138.5,139.001,141.002,141.003,159.1,160.1,312.0,12034.0,12434.0,12834.0,11601.0,23234.0 -j10 --ibeos` 
- `runTheMatrix.py -l 12430.0,12440.0 --what upgrade -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/42958

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/42958

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@cmsbuild, please test

**Comment by AdrianoDee** [comment]
please test

**Comment by saumyaphor4252** [comment]
+alca
- Restores status quo by fixing the compatible ECAL timing calibrations for @ HLT reconstruction in Run3 MC by switching back to Ratio algorithm conditions
- Changes expected due to the revert of
   - https://github.com/cms-sw/cmssw/pull/42789
   - https://github.com/cms-sw/cmssw/pull/42702
- Positive feedback from the Egamma group for the validations in 13_3_X release cycle  (See https://github.com/cms-sw/cmssw/pull/42946#issuecomment-1860125886)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
