### PR TITLE
Displaced muon with new parameters for the Phase2 L1 tracker studies

### PR DESCRIPTION
**Pull request by rgoldouz**
Hello,

The parameters in the following gen card is not appropriate for our studies in phase2 L1 track triggers. 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/FlatRandomPtAndDxyGunProducer_cfi.py 

In order to be used in relval sample production, I have made a new card with proper parameters. My relval request is in 
https://its.cern.ch/jira/browse/PDMVRELVALS-116

Please merge this card into the CMSSW to be used for the official relval sample generation.

Thanks,
Reza

### CODE REVIEW

**Comment by agrohsje** [comment]
hi @rgoldouz . thanks for the pr. one question: is there a reason you changed the order of the settings compared to: 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/FlatRandomPtAndDxyGunProducer_cfi.py
keeping the order would be nice for an easy comparison. 
can you comment on the name of the file? What does it mean?

**Comment by rgoldouz** [comment]
Hello @agrohsje,

I just reordered input parameters the same as the original file. Do you see the recent one? or I should make another request?

Thanks,
Reza

**Comment by rgoldouz** [comment]
Hello,

Based on relval request, I added two more fragment file,
SingleMuFlatPt1p5To8_cfi.py
SingleElectronFlatPt1p5To8_cfi.py

Do you see them in my pull request? or maybe I should wait for the previous PR to be merged first. Then I send my new PR.
If these two files are also merged into the CMSSW, our sample requests will be easy for them to be submitted.

Please let me know if you have any question.

Thanks,
Reza

**Comment by agrohsje** [comment]
Thanks @rgoldouz . All commits are visible. Can you comment on the fragment name. What means PtDMu. My main point is just to distinguish from the original with the looser cuts.

**Comment by tomalin** [comment]
> Thanks @rgoldouz . All commits are visible. Can you comment on the fragment name. What means PtDMu. My main point is just to distinguish from the original with the looser cuts.

Presumably, in the name "FlatRandomPtDMuProducer_cfi.py", the "D" is short for "Displaced" (meaning that the muons don't originate at the beam-line). Perhaps it should be renamed to FlatRandomPtDisplacedMuProducer_cfi.py?

**Comment by agrohsje** [comment]
The same is true for this one: 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/FlatRandomPtAndDxyGunProducer_cfi.py
Hence my proposal to distinguish them a bit better. Dispalced muon and flat pt is also done by the other, so that isn't useful to distinguish.

**Comment by tomalin** [comment]
> The same is true for this one:
> https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/FlatRandomPtAndDxyGunProducer_cfi.py
> Hence my proposal to distinguish them a bit better. Dispalced muon and flat pt is also done by the other, so that isn't useful to distinguish.

The new file FlatRandomPtDMuProducer_cfi.py and the old one FlatRandomPtAndDxyGunProducer_cfi.py use the same generator, so should have similar names. The main difference between them is the Pt range & Dxy range they use. So how about naming the new one FlatRandomPt1.5To8Dxy100GunProducer_cfi.py? Ideally the old one should then be remained FlatRandomPt2To50Dxy500GunProducer_cfi.py, but that may break existing work flows.

**Comment by rgoldouz** [comment]
Hi @agrohsje and @tomalin ,

For the displaced muon card I can change it to 'FlatRandomPt1p5To8Dxy100GunProducer_cfi.py' if @agrohsje also agrees. I need also to add 'FlatRandomPt2To100Dxy100GunProducer_cfi.py' file.

For the 
SingleMuFlatPt1p5To8_cfi.py and SingleElectronFlatPt1p5To8_cfi.py cards,I am checking for the eta cut with @chayanit  who made SingleMuFlatPt2To100_cfi.py and SingleElectronFlatPt2To100_cfi.py cards. I am going to change the eta cut from 2.85 to 2.6 in order not to lose statistics.

I will make a PR after making sure about the card's name and eta cut.

Thanks a lot,
Reza

**Comment by agrohsje** [comment]
A proposal similar to what @tomalin made was what I had in mind. This looks good. @rgoldouz you should still remove the old one from the PR. 
One more question. You call the others Single, but as you enable the antiparticle flag, doesn't that mean you get particle and anti-particle. Or was I always misinterpreting this setting?

**Comment by rgoldouz** [comment]
Hi @agrohsje 

I just deleted the old file. 
I used similar names to the previous samples 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleMuFlatPt2To100_cfi.py
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleElectronFlatPt2To100_cfi.py

Although names are confusing but having anti-particle is useful since  it increases the statistics in our studies.

Please let me know if there is any comment. 
Relval people will submit our request after these files are merged.

Thanks a lot,
Reza

**Comment by agrohsje** [comment]
I think instead of SingleElectron you should just call it DoubleElectron. See e.g. this example:
https://cms-pdmv.cern.ch/mcm/requests?prepid=EGM-MultiValidationUL17GEN-00006
My understanding is that most people follow the convention of SingleElectron when anti particle is false and DoubleElectron when true. Let me add @qliphy to check if he knows more about a possible convention.

**Comment by qliphy** [comment]
@agrohsje Currently there are many similar files named "Single"
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleElectronPt35_pythia8_cfi.py
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleMuPt10_pythia8_cfi.py
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleElectronE120EHCAL_pythia8_cfi.py
...

**Comment by agrohsje** [comment]
Hi @qliphy, I know. I find it a bit unfortunate as indeed there is no consistency in names and it would be useful if the name would tell us what is inside. I have a small preference to do this correct now and at some point also fix the old files but I leave it up to @rgoldouz. If you fix the name, you should also update psethack. Let me know.

**Comment by rgoldouz** [comment]
Hi @agrohsje 

Names are fixed. Please let me know if you have any other comment?

Thanks,
Reza

**Comment by agrohsje** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
