### PR TITLE
Fix clang warnings in EventFilter/SiPixelRawToDigi

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
@Dr15Jones : after the merging of #25748 the conflict already pointed out by Slava inhttps://github.com/cms-sw/cmssw/pull/25805#discussion_r252767589 becomes explicit
Since in that PR the same fix that you propose here was already implemented, you can resolve the conflict by simply reverting your commit 1999bdb here

**Comment by Dr15Jones** [comment]
@perrotta all I had to do was rebase onto master and git automatically dropped the one commit I had that was conflicting with what is now in master.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
