### PR TITLE
Rename external tool herwigpp to herwig7

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
#### PR description:

Rename external library herwigpp to herwig7 for consistency with pull request https://github.com/cms-sw/cmsdist/pull/6499. 

#### PR validation:

Tested with runTheMatrix workflow 535 and test command from Herwig twiki.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#6499

**Comment by agrohsje** [comment]
Thanks Dominic.
+1

**Comment by agrohsje** [comment]
+generators

**Comment by silviodonato** [comment]
> please test with [cms-sw/cmsdist#6499](https://github.com/cms-sw/cmsdist/pull/6499)

@smuzaffar the tag `external-pending` is missing

**Comment by smuzaffar** [comment]
@silviodonato , you are right, I wiull check.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
