### PR TITLE
Fix ONNX model file version in the unittest

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Needed by the ONNXRuntime update:
https://github.com/cms-sw/cmsdist/pull/5743

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#5743

**Comment by slava77** [comment]
abort

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#5743,cms-sw/cmssw#29486

**Comment by slava77** [comment]
@cmsbuild please test

to check that this runs by itself

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29510	5ec6fd0 
- this apparently fixes the problem in the unit test appearing in tests of  cms-sw/cmsdist#5743. The testONNXRuntime works with this PR by itself as well.

**Comment by silviodonato** [comment]
do you have any comments @santocch?

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
