### PR TITLE
[Backport 141X] DQM: restore Muon POG sequence (and CSC Monitor), revert #46297

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Effective backport of https://github.com/cms-sw/cmssw/pull/46297 to 141X.

#### PR validation:

Simple revert of previous to previously running code.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
urgent

**Comment by fabiocos** [comment]
bug-fix

**Comment by fabiocos** [comment]
type bugfix

**Comment by antoniovagnerini** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
