### PR TITLE
71 x update for2015 bs nm

### PR DESCRIPTION
**Pull request by nancymarinelli**
This branch has a modified version of Configuration/PyReleaseValidation/python/relval_steps.py for using the gen-sim produced 7_1_14  and for using by default the BS for nominal collisions 2015 + a modified version of  Configuration/AlCa/python/autoCond.py for using the GTs for 23 and 50 ns with the new BS + a modified version of Configuration/StandardSequences/python/VtxSmeared.py for using the VtxSmearedDefaultKey for NominalCollisions2015

### CODE REVIEW

**Comment by mmusich** [comment]
@nancymarinelli @franzoni
As we noticed with @diguida the current  `run2_design` key points to `DESIGN71_V6` which still contains the old BS tag `Realistic8TeVCollisions_START50_V13_v1_mc`. Are you interested in getting that one consistent too?

**Comment by nancymarinelli** [comment]
Hello
I have looked at the error in the log. I am afraid the error has nothing to do with what I did for this PR.

I am at a loss.
 Nancy
______________________________________

Nancy Marinelli

Research Associate Professor
University of Notre Dame, IN, US

CERN, Bdg 40/3-A01, 1211 Geneva,

SWITZERLAND

Phone +41-22-76-70809, fax +41-22-76-78940

**Comment by franzoni** [comment]
hello @mmusich,
while run2_design is at the moment nowhere used in the matrix, there's value in having all the run2 flavors of autocond:GT refer to the same scenario. Can you point us to the GT, please ?

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by nancymarinelli** [comment]
Hello,
And I give you the same reply I gave yesterday. The error I see in the log is not related to any change I made in the PR.
Nor I know of any test I can run. There must be something else in the whole branch (not m PR) which causes the error.

  Nancy
______________________________________

Nancy Marinelli

Research Associate Professor
University of Notre Dame, IN, US

CERN, Bdg 40/3-A01, 1211 Geneva,

SWITZERLAND

Phone +41-22-76-70809, fax +41-22-76-78940

**Comment by diguida** [comment]
@nancymarinelli @franzoni 
I have assembled a new PR which fixes also the Run2 design GT, and also adds the new Run1 SIM geometry in the corresponding GT: this way, you have a 71X branch with al the ingredients for GEN-SIM production. It is #7962 

HTH

**Comment by diguida** [comment]
-1
Superseded by #7962

**Comment by nancymarinelli** [comment]
Thanks a lot!.
N.
______________________________________

Nancy Marinelli

Research Associate Professor
University of Notre Dame, IN, US

CERN, Bdg 40/3-A01, 1211 Geneva,

SWITZERLAND

Phone +41-22-76-70809, fax +41-22-76-78940

**Pull request closed without merging**
