### PR TITLE
report summary map

### PR DESCRIPTION
**Pull request by popovvp**
CASTOR report summary map for shifters

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please submit the same for 81x as well.
thanks,
F.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
It has no 81x port - it won't be included :(

**Comment by davidlange6** [comment]
so why +1 it? now its confusing.
@popovvp - is there a 81x PR?

**Pull request closed without merging**
