### PR TITLE
Phase2Digitizer package updated

### PR DESCRIPTION
**Pull request by suchandradutta**
Updated DigitizerUtility::Amplitude object to store the EncodedEventId properly for individual SimHit contributions to the Digi. There was a subtle bug that only the first EncodedEventId was stored. Another bug has also been fixed where the fraction of individual contribution to the digi was calculated wrongly. A few new histograms are added in the validation suite and a few minor bugs corrected.

Detailed description of the update reported in Tracker Phase2 Simulation meeting can be found here
https://indico.cern.ch/event/536892/contributions/2385404/attachments/1379749/2096939/DigiStudy_Status_Nov29_2016.pdf

@delaere @atricomi @boudoul @emiglior

### CODE REVIEW

**Comment by davidlange6** [comment]
@smuzaffar @iahmad-khan - seems this pull request did not get picked up by cmsbuild. can you have a look?

**Comment by davidlange6** [comment]
ok, seems I just needed to comment on the PR..

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Should there be a 90X version of this PR?

**Comment by boudoul** [comment]
Hi @kpedro88 , right, we discussed this today during our tracker meeting, I was thinking that it was part of the one auto forward ported but likely it came after the auto forward port [was lost with my calendar, I thought it was in the 81X queue earlier] 
@suchandradutta , could you please make the equivelent for 90X ?  likely it is just for 90X actually

**Comment by davidlange6** [comment]
not needed in 81x. (phase2 dev will evolve in 90x)

**Pull request closed without merging**
