### PR TITLE
Code added to Produce SiStrip trends of number of channel errors per …

### PR DESCRIPTION
**Pull request by Wilsker**
…fed id per LS

Plots added to SiStripMonitorHardware FEDHistograms package and filled in SiStripFEDMonitor.cc. Plot is TProfile2D so added classes to HistogramBase to get and fill such histrograms. Added argument to FEDErrors fillBadChannelList method to count channel errors per fed id (previously only cumulative numbers available). 

Modified packages beneath.
	modified:   DQM/SiStripMonitorHardware/interface/FEDErrors.hh
	modified:   DQM/SiStripMonitorHardware/interface/FEDHistograms.hh
	modified:   DQM/SiStripMonitorHardware/interface/HistogramBase.hh
	modified:   DQM/SiStripMonitorHardware/python/siStripFEDMonitor_cfi.py
	modified:   DQM/SiStripMonitorHardware/src/FEDErrors.cc
	modified:   DQM/SiStripMonitorHardware/src/FEDHistograms.cc
	modified:   DQM/SiStripMonitorHardware/src/HistogramBase.cc
	modified:   DQM/SiStripMonitorHardware/src/SiStripFEDMonitor.cc

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
-1
adds a flood of printouts. Please fix before further review

**Comment by davidlange6** [comment]
please test

(just to recover them)

**Comment by fioriNTU** [comment]
@davidlange6 could you please inform us about the content of the printouts once available, this PR should do basically nothing in Offline.

**Comment by davidlange6** [comment]
hi @fioriNTU - are you sure that DQM/SiStripMonitorHardware/src/SiStripFEDMonitor.cc is not used offline - it seems to be

**Comment by fioriNTU** [comment]
@davidlange6 I confirm the module is used Offline, what I meant is that the particular plot added in this PR by @Wilsker should not be even booked Offline.

**Comment by Wilsker** [comment]
Hi, I see I accidently left two cout statements in DQM/SiStripMonitorHardware/src/FEDHistograms.cc (https://github.com/cms-sw/cmssw/pull/21355/files#diff-68f304f3f7740f819f03bb33c8cf98dcR255), one of which is before the global online switch. I believe this is what you are referring to?

**Comment by Wilsker** [comment]
Annoyingly, the CMSSW nightly I was using for this PR is no longer available. What is the protocol for essentially checking out this PR so I can edit the lines in question?

Cheers

**Comment by dmitrijus** [comment]
@Wilsker

 ```
cmsrel/scram <latest IB>
git cms-merge-topic <this pr>
```

**Comment by Wilsker** [comment]
@dmitrijus Thanks a lot for that. I removed the offending lines and committed the edit.

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
