### PR TITLE
Update to pp_on_AA_2018 era track selection with new MVAs

### PR DESCRIPTION
**Pull request by abaty**
This PR aims to significantly reduce the fake rate of tracks in the 2018 HI reconstruction by tightening MVA thresholds, and also replacing the existing pp-trained MVA selectors with HI-trained ones for the first 6 tracking iterations.  A new GT has been prepared by AlCa, and we have slightly edited relval workflow 158.0 to pick up this new GT so testing will still function.

We find that the reconstruction timing and event content size go down only very slightly, while we see a massive reduction in fake rate at the cost of a small efficiency loss.  More information on the performance and strategy can be found at [1].

[1] https://indico.cern.ch/event/754818/contributions/3127986/attachments/1709774/2768010/MVA_PR_Sept13_2018.pdf

@mandrenguyen

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@abaty Will these new MVA selectors also be consumed in HLT/Express/Prompt in data?
Thanks.

**Comment by abaty** [comment]
@tocheng 

This was discussed today in the Heavy Ion PAG.  Yes, we will want these MVA selections in HLT, Express, and Prompt.

**Comment by tocheng** [comment]
> @tocheng
> 
> This was discussed today in the Heavy Ion PAG. Yes, we will want these MVA selections in HLT, Express, and Prompt.

Thanks a lot! Will data and MC use the same MVA selector conditions? Will these condition be constant or they maybe change at different runs?

**Comment by abaty** [comment]
@tocheng 

Data and MC will use the same selector, yes.  The condition should be the same for all the runs that fall under the scope of the 2018_pp_on_AA era (essentially the Heavy Ion run for this year).

**Comment by slava77** [comment]
Looking at the GTs, I see that there are more differences than just the MVAs
https://cms-conddb-prod.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_v4/103X_upgrade2018_realistic_HI_v2

- GeometryFileRcd  Extended  XMLFILE_Geometry_101YV4_Extended2018_mc -> XMLFILE_Geometry_103YV1_Extended2018_mc
- PCastorRcd CASTORRECO_Geometry_2015_71YV3 -> CASTORRECO_Geometry_103YV1
- PZdcRcd ZDCRECO_Geometry_61YV4 -> ZDCRECO_Geometry_103YV1

At least from the version names, it sounds like the realistic_HI GT is more correct. OTOH, this looks like the GEN-SIM and perhaps even digi are not going to be the same between the two

**Comment by tocheng** [comment]
Hello @slava77 ,
this GT should be compared with 103X_upgrade2018_realistic_HI_v1
which has been merged in  #24451 
https://github.com/cms-sw/cmssw/pull/24451/files

**Comment by slava77** [comment]
> Hello @slava77 ,
> the GT in this PR should be compared with 103X_upgrade2018_realistic_HI_v1
> which has been merged in #24451
> https://github.com/cms-sw/cmssw/pull/24451/files

right, but I was asking in the context of the ppReco workflow 158.0. 
The updates made in this PR give:
- step1 (GEN-SIM) made with auto:phase1_2018_realistic
- step2 and 3 ( digi and reco ) made with auto:phase1_2018_realistic_hi

Are the geometry differences between phase1_2018_realistic and phase1_2018_realistic_hi transparent enough that the mix of the two GTs will still give a sensible result?

**Comment by slava77** [comment]
>  -> In the eventuality they are not present, the code will crash? If so the MVA selectors will have to be added to all data GT too no?

right, the HI data GT will need these payloads to work.

**Comment by slava77** [comment]
here are some plots using the HI filtered minbias (with the cut of 3000 [I forgot the unit of the cut]).
This PR is in red.

there are about 5% fewer tracks
all_sign1042vsorig_hinpbpbmbfilter3000c_log10recotracks_generaltracks__reco_obj_pt
The increase/decrease in the counts varies by iteration
all_sign1042vsorig_hinpbpbmbfilter3000c_recotracks_generaltracks__reco_obj_originalalgo
all_sign1042vsorig_hinpbpbmbfilter3000c_recotracks_generaltracks__reco_obj_qualitymask


There is a fairly significant reduction in PF candidates [likely expected; note that the fractional drop is much larger than just the number of tracks, due to the track quality changes (plot above)]
all_sign1042vsorig_hinpbpbmbfilter3000c_log10recopfcandidates_particleflow__reco_obj_pt48

a fraction of this is rebalanced by an increase in the photons and neutral hadrons
all_sign1042vsorig_hinpbpbmbfilter3000c_log10recopfcandidates_particleflow__reco_obj_pt76



further downstream it's seen as a drop in higher ET end of the jet spectrum (this seems somewhat specific to this jet collection)
all_sign1042vsorig_hinpbpbmbfilter3000c_log10recopfjets_ak4pfjets__reco_obj_et

CS jets are somewhat similar before/after, but are also losing some on the high ET end
all_sign1042vsorig_hinpbpbmbfilter3000c_log10recopfjets_akcs4pfjets__reco_obj_et

There is also a loss in HI pixel tracks
all_sign1042vsorig_hinpbpbmbfilter3000c_recotracks_hiconformalpixeltracks__reco_obj_eta
My guess is that this is via the connection to offlinePrimaryVertices and some reduction of the fake vertices.

There is a moderate increase in the generalTracks efficiency and some significant decrease of the fake rate.
For filtered-3000 events:
wfhi3000_gen_eff_pt
wfhi3000_gen_fr_pt

Similarly, for wf 158.0 (inclusive minbias)
wf158 0_gen_eff_pt
wf158 0_gen_fr_pt

compare this to Ztautau with PU (black), ttbar (blue) and QCD 80-120 (orange) from the regular pp
wfttzttq80pre3_gen_eff_pt
wfttzttq80pre3_gen_fr_pt

Here it already looks like the fake rate suppression is somewhat tighter in HI than in pp.
However, compared to the baseline, the pp_on_AA still shows an overall improvement.

For the highPurity selection:
filtered-3000
wfhi3000_hp_eff_pt
wfhi3000_hp_fr_pt

similar for 158.0
wf158 0_hp_eff_pt
wf158 0_hp_fr_pt

compared to the regular pp
wfttzttq80pre3_hp_eff_pt
wfttzttq80pre3_hp_fr_pt

given a considerable loss of efficiency and FR somewhat generally smaller than the regular pp, I'd say that the highPurity selections seem over-tuned.
It's all OK in a context of pure tracking applications: as mentioned in p3 of the slides linked with the PR description ```If analyzers want a higher efficiency than provided by 'highPurity' tracks (at the cost of an increased fake rate), they can use the 'tight' track selection instead```.
This approach will not work with the PF objects, which can not be remade at analysis step.
Based on the limi

My limited tests are not really enough to guess the overall impact, but it seems like there are no particularly large bad effects expected 
- the default b-tagging (using pf cands) may be affected, but this can be mitigated by using track-based taggers. DQM plots for b-tagging with HI inputs are apparently not setup well, but a limited set of what still seems to work doesn't show a significant degradation
- jet resolution may be a bit degraded, but this is probably a tiny effect.
- MET may not work as well, but apparently HI does not care about MET at least in its default form (recent updates effectively disabled it).

OTOH, it seems like tracks are still of generally higher importance in HI analyses still, compared to PF. Still, have you reviewed the impact of the highPurity operating point on the high level objects (mostly PF-related)?

**Comment by slava77** [comment]
On 9/18/18 7:21 PM, Matthew Nguyen wrote:
> As I understand it, we've tuned the highPurity bit to give the same
> rejection power as our previous MVA calibrations in the now-deprecated
> heavy-ion scenario, which is in turn approximately the same as the
> heavy-ion cut-based selections from Run 1.

do we have a setup for 2018 that is expected to have this performance in
the --scenario HeavyIons?
Would the setup in 150.0 be expected to have it?

**Comment by mandrenguyen** [comment]
@slava77 For 150 we switched to the pp GTs, so there is no dedicated track selection.  This is the first time we derive calibrations for the new 4-layer detector. 
For wf 145, the one that corresponds to the 2015 reconstruction, you should get MVA calibrations derived by the HIN PAG that were appropriate for the 2015 detector.

**Comment by slava77** [comment]
OK.
Perhaps all material/comparisons is available somewhere.
It just didn't come across in the slides provided with the PR description https://indico.cern.ch/event/754818/contributions/3127986/attachments/1709774/2768010/MVA_PR_Sept13_2018.pdf
The only reference there is 158.0 itself, using inclusive minbias (not focused on more central events and no comparison to Run-1 or phase-0/2015 performance plots).
If such plots/slides are available, please add them to the PR description.

**Comment by mandrenguyen** [comment]
@abaty do you have a plot of the track efficiency and fake rate from 2015 compared to what we have after this PR?  If we have this for central events even better.

**Comment by slava77** [comment]
I tried to remake the 2015 equivalent of the ncoll.gt.3000 sample for 2018, but Geant decided to crash half-way. So, I'd give up on this "quick" and more equivalent check.

Instead, I picked something (hopefully not completely random and broken) from the past relvals 
 https://goo.gl/Q7DpYJ /RelValHydjetQ_MinBias_5020GeV/CMSSW_9_0_0-90X_mcRun2_HeavyIon_v4-v1/DQMIO

This should have somewhat better eff and FR than my ncoll.gt.3000 filtered sample events.
(Since the normalization is per track, the average over the inclusive MB sample is probably not that far from the ncoll.gt.3000.)

"general track"
wfmb15v900_reco_eff_pt
wfmb15v900_reco_fr_pt

high-purity
wfmb15v900_reco_eff_pt
wfmb15v900_hp_fr_pt

- with highpurity:
    - '15MB: eff \~75%, fr\~5%
    - '18 hi3K: eff \~75%, fr \~ 5%
- with "general tracks" (assuming equivalence of the hi scenario and pp generalTracks)
    - '15MB: eff\~80%, fr \~35%
    - '18 hi3K HP: eff \~81%, fr \~ 25%

Based on https://github.com/cms-sw/cmssw/pull/24537#issuecomment-422625356 it looks like the eff/fr points that I see are in a fairly good agreement with the goals of having roughly the same FR.

**Comment by lpernie** [comment]
Concerning the addition of the MVA selectors to Data GTs: They are already queued in HLT/Express and prompt Queues.
I will updated the 8 data GTs in autocond (since for pp era they are an harmless addition).
I PR will follow (I can push the changes here, or in a separate PR where also HI MC conditions are updated).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24537	693aa75
- code changes are in line with the PR description and the follow up discussion/notes.
- jenkins tests pass and comparisons with the baseline show differences only in the pp_on_AA workflow 158.0
- local tests with more events from 158.0 and from a filtered minbias HI sample confirm roughly expected behavior described in the slides provided with the PR description 
    - see also https://github.com/cms-sw/cmssw/pull/24537#issuecomment-422597984
    - in processing of the ncoll.gt.3000 sample in a production setup (running only RECO, and \@standardDQM, writing AOD) : 
        - CPU use in is decreased by about 6%: the total in the iterative tracking is up by 2%, while the total of other modules time is reduced by \~20%.
        - AODSIM output is down by \~3%, dominated by the fractional 15% reduction in the particleFlow candidates and 5% in the generalTracks.
        - peak memory use in 8-thread job is up from 10.0GiB to 10.4 GiB. I did not investigate which fraction of this is possibly from the new payloads or if this is possibly just a fluctuation.

**Comment by zhenhu** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by abaty** [comment]
@mandrenguyen @slava77 
If you look at the blue boxes on slide 3 of [1], you can find a study of eff/fake rate we did in October, 2015 just before the last PbPb run.  Looking at a few pt values:

Efficiency at 1 GeV: 0.6 (2015) vs 0.65 (2018)
Efficiency at 5 GeV: 0.75 (2015) vs 0.75 (2018)
Fake at 1 GeV: 0.12 (2015) vs 0.08 (2018)
Fake at 5 GeV: 0.03 (2015) vs 0.1 (2018)

I think the lower fake rate in 2015 at 5 GeV is because that sample is Pythia+Hydjet, so the relative fraction of high-pt (true) tracks is artificially enhanced as compared to regular MB Hydjet; lowering the fake rate.  Otherwise it seems like we are doing as good as the 2015 reco, if not a bit better around 1 GeV.  As Slava said, these plots are nTrk-weighted, so we are already looking at the performance of a fairly central sample.  
               
As Matt also mentioned, all of my interaction with the heavy ion high-pt group (the main consumers of Particle Flow in heavy ions) have indicated that they would like to err on the side of having tighter selections, rather than a looser working point, because of worries about fake contamination in central events.  We know from XeXe that using the current pp selections in central events renders the PF jet collections extremely contaminated.

[1] https://indico.cern.ch/event/452386/contributions/1116524/attachments/1167562/1683886/2015_10_08_trackingmeeting.pdf

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
