### PR TITLE
Update of DeepTauID to ver. 2017v2 (backport for UL)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR updates DeepTauID to version 2017v2. The new version, thanks to revised structure of used DNN, fixes issues of version 2017v1 that is a size of training files and memory consumption are greatly reduced. Possibility to run previous version is maintained.

DeepTauID (2017v2) is added to the tau sequence in the standard MiniAOD workflow.

Performance with 1k ttbar events:
* size of three training files: 2.9+0.85+0.85=4.6MiB (was 21MiB in 2017v1);
* memory consumption: on top of DeepJet: 6.4MiB or 21.5 MiB standalone. The difference between the two comes mainly from executing pat::PackedCandidate::dzError() method which triggers unpacking of track covariance matrix and at smaller extend from initialization of TensorFlow. Full information on memory usage from IGProf can be accessed at this link: http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_memory_usage/;
* CPU timing:
   * Full timing of a simple test workflow is 0.11s/event with DeepTauId::getPredictions 0.088s/event; details at at http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTauCPU_TT;
   * Full timing of miniAOD workflow is 1.06s/event with DeepTauId::getPredictions 0.082s/event; details at http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_MiniAOD.

In addition the new v2 training overperforms (physics-result-wise) old v1 one as well as other TauIDs, details in slides:
* https://indico.cern.ch/event/816162/contributions/3408556/attachments/1835352/3007877/2019-04-29_DeepTau_ID_v2_developments.pdf
* https://indico.cern.ch/event/818643/contributions/3422014/attachments/1839253/3014630/2019-05-06_DeepTau_ID_v2_WP.pdf

Note 1: this PR is backport of #26796 to 10_6_X for UL processing
Note 2: this PR is completed by cms-data/RecoTauTag-TrainingFiles#3 which needs to be propagated to cms-dist.

#### PR validation:

Validated with matrix tests; requires cms-data/RecoTauTag-TrainingFiles#3 for unit tests

#### if this PR is a backport please specify the original PR:

This is port of #26796 for UL (rebased to CMSSW_10_6_X as for 7 June 2019)

### CODE REVIEW

**Comment by perrotta** [comment]
please test with  cms-data/RecoTauTag-TrainingFiles#3

**Comment by perrotta** [comment]
backport of #26796

**Comment by perrotta** [comment]
@smuzaffar , cmsbuild did not test with cms-data/RecoTauTag-TrainingFiles#3

Should a similar cms-data pull request get prepared also for 10_6_X (i.e., is the problem due to the fact that I tried to run with an external submitted in master)?

Since that PR only includes new files, maybe a similar PR than https://github.com/cms-sw/cmsdist/pull/5026 could be merged since now also in 10_6_X: what do you think?

**Comment by perrotta** [comment]
In the tests there is a failing comparison for the HLT DQM histo ```hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter_gsfEle_passFilter_HLTphi_eb``` for wf 136.85 RunEGamma2018A: this looks completely un-related to me, still maybe worth being looked at by DQM in order to understand the reason for such a non-reproducibility (attn @andrius-k, @kmaeshima, @schneiml, @jfernan2, @fioriNTU)

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/5027
@perrotta , https://github.com/cms-sw/cmsdist/pull/5027 should be used for 10.6.X

**Comment by perrotta** [comment]
> please test with [cms-sw/cmsdist#5027](https://github.com/cms-sw/cmsdist/pull/5027)
> @perrotta , [cms-sw/cmsdist#5027](https://github.com/cms-sw/cmsdist/pull/5027) should be used for 10.6.X

Thank you @smuzaffar

**Comment by perrotta** [comment]
+1
- Identical backport of #26796
- Jenkins tests show the additional IDs in miniAOD outputs as only differences
- It needs  cms-sw/cmsdist#5027

**Comment by fabiocos** [comment]
@civanch @santocch I think this should be ok for you as well, as we want to have it in the UL release

**Comment by mbluj** [comment]
The most recent commit fixes issue related to the fact that DeepTauID is trained with samples produced before `pat::PackedCandidate::hcalFraction()` was redefined in #26506 (for >=CMSSW_10_6_X). This fix is similar to one for `RecoBTag/FeatureTools/plugins/DeepBoostedJetTagInfoProducer.cc` from #26506. 

This fixes differences wrt DeepTauID with 10_2_X mentioned in https://github.com/cms-sw/cmssw/pull/27148#issuecomment-500777004

**This commit is backport of** #27173

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#5027

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#5027
(By the way, the tests launched yesterday seem to be still stuck somewhere: hope I'll have better luck now...)

**Comment by mbluj** [comment]
Recent commit replaces `std::isnan` (which does not work when fast-math is used) by `edm::isNotFinite` as suggested by the static analyzer.

**This commit is backported from** #27173

**Comment by smuzaffar** [comment]
please test
cms-sw/cmsdist#5027 is already in 10.6.X

**Comment by jfernan2** [comment]
> In the tests there is a failing comparison for the HLT DQM histo `hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter_gsfEle_passFilter_HLTphi_eb` for wf 136.85 RunEGamma2018A: this looks completely un-related to me, still maybe worth being looked at by DQM in order to understand the reason for such a non-reproducibility (attn @andrius-k, @kmaeshima, @schneiml, @jfernan2, @fioriNTU)

@perrotta I don't see the failing comparison in that workflow (in the original Jenkins test), can you point me to it please?

**Comment by perrotta** [comment]
> > In the tests there is a failing comparison for the HLT DQM histo `hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter_gsfEle_passFilter_HLTphi_eb` for wf 136.85 RunEGamma2018A: this looks completely un-related to me, still maybe worth being looked at by DQM in order to understand the reason for such a non-reproducibility (attn @andrius-k, @kmaeshima, @schneiml, @jfernan2, @fioriNTU)
> 
> @perrotta I don't see the failing comparison in that workflow (in the original Jenkins test), can you point me to it please?

@jfernan2 you are absolutely correct, and sorry for the mistake, I supposed I had written that comment to the 10_2_X version of this PR, see #27148 (while the tests weren't yet run here when I wrote it)
I have now moved that comment at its correct place, see https://github.com/cms-sw/cmssw/pull/27148#issuecomment-501330958, and I will remove it from this PR thread.

**Comment by perrotta** [comment]
please test
(AddOn test error is due to a missing input file and unrelated to this PR)

**Comment by perrotta** [comment]
+1
- Since the latest reco signature in https://github.com/cms-sw/cmssw/pull/27146#issuecomment-500722440 only the commits that backport the bug fix implemented in #27173 have been added
- Modifications of the DeepTauID have been checked and approved by Tau POG
- Needed external is already merged in 10_6

**Comment by fabiocos** [comment]
@santocch @civanch could you please check this PR?

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

apart for clang-formatting the backport is identical to master. The addition of the fix in #27189 will follow separately

**Comment by mbluj** [comment]
Hello, 
I have a question: now when this PR is merged it makes sense to store the DeepTauID also in NanoAOD - should we modify the tau table producer in NanoAOD? If so, can it go directly to CMSSW or via NanoAOD repository (technically it is quite trivial change)?

**Comment by perrotta** [comment]
> Hello,
> I have a question: now when this PR is merged it makes sense to store the DeepTauID also in NanoAOD - should we modify the tau table producer in NanoAOD? If so, can it go directly to CMSSW or via NanoAOD repository (technically it is quite trivial change)?

@mbluj , the final remarks for the PR signed off in the master were (see https://github.com/cms-sw/cmssw/pull/26796#issuecomment-499439391, which summarizes the discussions that went on in the github thread) "[cpu time] is probably still acceptable for miniAOD production, but a bit too much for routine nanoAOD production: some further reduction should be attempted if that ID will have to be recomputed in the nanoAOD campaigns: github issue #27119 has been opened to keep track of the future improvements in cpu performance"

**Comment by mbluj** [comment]
> > Hello,
> > I have a question: now when this PR is merged it makes sense to store the DeepTauID also in NanoAOD - should we modify the tau table producer in NanoAOD? If so, can it go directly to CMSSW or via NanoAOD repository (technically it is quite trivial change)?
> 
> @mbluj , the final remarks for the PR signed off in the master were (see [#26796 (comment)](https://github.com/cms-sw/cmssw/pull/26796#issuecomment-499439391), which summarizes the discussions that went on in the github thread) "[cpu time] is probably still acceptable for miniAOD production, but a bit too much for routine nanoAOD production: some further reduction should be attempted if that ID will have to be recomputed in the nanoAOD campaigns: github issue #27119 has been opened to keep track of the future improvements in cpu performance"

I understand this, but my question is different - I want to add DeepTau to tau table in NanoAOD, i.e. read it from Mini to write to Nano without running it at Nano step.

**Comment by perrotta** [comment]
> > > Hello,
> > > I have a question: now when this PR is merged it makes sense to store the DeepTauID also in NanoAOD - should we modify the tau table producer in NanoAOD? If so, can it go directly to CMSSW or via NanoAOD repository (technically it is quite trivial change)?
> > 
> > 
> > @mbluj , the final remarks for the PR signed off in the master were (see [#26796 (comment)](https://github.com/cms-sw/cmssw/pull/26796#issuecomment-499439391), which summarizes the discussions that went on in the github thread) "[cpu time] is probably still acceptable for miniAOD production, but a bit too much for routine nanoAOD production: some further reduction should be attempted if that ID will have to be recomputed in the nanoAOD campaigns: github issue #27119 has been opened to keep track of the future improvements in cpu performance"
> 
> I understand this, but my question is different - I want to add DeepTau to tau table in NanoAOD, i.e. read it from Mini to write to Nano without running it at Nano step.

Ah, ok. This will have to follow a forthcoming re-miniAOD campaign in 10_2_X, then (for which I don't know the plans). 
That question should then get addressed to xpog (@fgolf,@peruzzim)

**Comment by santocch** [comment]
+1

**Comment by peruzzim** [comment]
@mbluj it would be better to have the addition done in the cms-nanoAOD repository, thanks

**Comment by peruzzim** [comment]
Ok, I had a discussion with @steggema. It would not be nice to have the new tagger in MiniAOD UL, and not in Nano.
For this time only, we can add it directly in the cmssw repository, in the interest of a faster integration, but only if the code changes are really minimal.

It should be added in such a way that it just gets copied from MiniAOD when running without modifiers, and is deactivated when running with any of the following modifiers: run2_miniAOD_80XLegacy, run2_nanoAOD_94X2016, run2_nanoAOD_94XMiniAODv1, run2_nanoAOD_94XMiniAODv2, run2_nanoAOD_102Xv1.

You can add it to the tau table, and then do something like:
`
(run2_miniAOD_80XLegacy | run2_nanoAOD_94X2016 | run2_nanoAOD_94XMiniAODv1 | run2_nanoAOD_94XMiniAODv2 | run2_nanoAOD_102Xv1).toModify(tauTable.variables, newID = None)
`
to avoid trying to store it when you run on older MiniAOD.

I hope you realize how late this comes...

**Comment by mbluj** [comment]
> Ok, I had a discussion with @steggema. It would not be nice to have the new tagger in MiniAOD UL, and not in Nano.
> For this time only, we can add it directly in the cmssw repository, in the interest of a faster integration, but only if the code changes are really minimal.
 
Yes, sure thing.

> It should be added in such a way that it just gets copied from MiniAOD when running without modifiers, and is deactivated when running with any of the following modifiers: run2_miniAOD_80XLegacy, run2_nanoAOD_94X2016, run2_nanoAOD_94XMiniAODv1, run2_nanoAOD_94XMiniAODv2, run2_nanoAOD_102Xv1.

OK, will be done.

> You can add it to the tau table, and then do something like:
> `(run2_miniAOD_80XLegacy | run2_nanoAOD_94X2016 | run2_nanoAOD_94XMiniAODv1 | run2_nanoAOD_94XMiniAODv2 | run2_nanoAOD_102Xv1).toModify(tauTable.variables, newID = None)`
> to avoid trying to store it when you run on older MiniAOD.
> 
OK, thank you for this hint

> I hope you realize how late this comes...

**Comment by fabiocos** [comment]
@mbluj @peruzzim we are discussing of an update to nanoAOD targeting 10_6_X . Let's discuss at next ORP meeting, but this seems late for CMSSW_10_6_1, if we do not want to delay it further

**Comment by mbluj** [comment]
> @mbluj @peruzzim we are discussing of an update to nanoAOD targeting 10_6_X . Let's discuss at next ORP meeting, but this seems late for CMSSW_10_6_1, if we do not want to delay it further

I think to be ready with a PR today or early tomorrow - it is a small addition. But sure, final decision in your hands.

**Pull request merged**
