### PR TITLE
add Z+Jets final state and new monitoring histograms, enable comparis…

### PR DESCRIPTION
**Pull request by webermat**
…on with MiniAOD

Added monitoring of the Z+Jets final state selection of interest both for MET resolution and JEC determination, moved quark gluon tagger histograms to dijet selection. Additional fix to avoid accidental double booking of histograms. Enable jetmet miniaod sequences and comparisons of RECO and MiniAOD histograms.

Development started and tested in 7_4_1.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@webermat 
could you rebase this one please?
ciao,
F.

**Comment by webermat** [comment]
seems the conflict was only present in one file concerning the hwwanalyzer. I hope rebase and a subsequent pull should have solved the issue.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@webermat 
please rebase this one so that can be merged
thanks,
F.

**Comment by webermat** [comment]
topic should have been merged on release 7_4_6 with git cms-topic-merged. In addition the 75X fix for the METPhi histograms has been applied: we fill the METPhi histograms for each PFCandidate species now only after a check if this species is indeed present in the event. This prevents artificial peaks at 0 (e.g. for 0T this can be the case for barrel ChargedHadrons)

**Comment by slava77** [comment]
-1
needs a rebase

**Comment by mmusich** [comment]
-1

**Comment by deguio** [comment]
-1
ciao @webermat 
maybe submitting a new PR containing only your changes is the best way to go.
thanks in advance,
F.

**Pull request closed without merging**
