### PR TITLE
[12_3_X] Added muon-tau-jet OvRm Filter

### PR DESCRIPTION
**Pull request by jaimeleonh**
#### PR description:

Backport of  #37424

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37424

This PR adds a producer for HLT which not presently used in any wfs nor HLT menus. It is added in case the producer turns out to be needed for HLT menus running in 12_3_X at the start of Run 3.

**Comment by missirol** [comment]
+hlt

 - see https://github.com/cms-sw/cmssw/pull/37424#issuecomment-1085509393
 
 @jaimeleonh , please add "[`12_3_X`]" (or similar) to the title of this backport PR.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
