### PR TITLE
Update DQMServices for protobuf 3.6.1.2 and tensorflow interfaces for TF 1.13.1 (copy of 25889)

### PR DESCRIPTION
**Pull request by mrodozov**
- Copy of #25889 to DEVEL

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @mrodozov .
@fabiocos , I am merging this in DEVEL IBs to test tensorflow update.

**Comment by fabiocos** [comment]
As agreed at the ORP 2019/05/07

**Comment by mrodozov** [comment]
@smuzaffar the cms pr from the last update

**Comment by jfernan2** [comment]
+1
For the records

**Comment by jfernan2** [comment]
+1

**Pull request merged**
