### PR TITLE
add D15,D16,D17 versions for 2023, reduce # of IB workflows, fix D14

### PR DESCRIPTION
**Pull request by kpedro88**
This PR is based on a very late request to use HGCal v8 in the muon/barrel TDR baseline geometry.

Since decisions about T3 vs. T5 (pixel extra disk) and O1 vs. O2 (detailed cavern) still have not been made, we get to add three more geometries and corresponding workflows!

D15 = T3+C3+M2+I1+O2+F2 (D12 w/ C3)
D16 = T5+C3+M2+I1+O1+F1 (D13 w/ T5)
D17 = T5+C3+M2+I1+O2+F2 (D14 w/ C3)

I also reduced the number of IB workflows for 2023, so every geometry only runs ttbar (w/ and w/out the Timing variation). D15 is added to the PR tests (that makes 4 tests for 2023, but only temporarily; once we have final decisions for the next TDR production, 1 or 2 of those can be removed).

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@Dr15Jones @boudoul this update should fix the failure in D14 and prevent failures in similar WFs introduced in this PR

**Comment by kpedro88** [comment]
please test workflow 26234.0,26634.0,27034.0,7434.0

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Pull request merged**
