### PR TITLE
edmPickEvent: print the actual das output instead of json parsing error

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/cms-sw/cmssw/pull/37255 should have fixed the edmPickEvent unit test but looks like dasgoclient still fails during IB tests. This PR prints the actual dasgoclient output in case of json parse errors.

Note this change does not fix the unit test itself but just to have more verbose output of edmPickEvent (in case of failures)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by qliphy** [comment]
please test
there are some differences which should not be related to this PR

**Comment by smuzaffar** [comment]
comparison differences are not related to this change.

**Comment by perrotta** [comment]
+1
-  have more verbose output of edmPickEvent (in case of failures)

**Comment by perrotta** [comment]
merge
(to bypass analysis signature)

**Comment by santocch** [comment]
+1

**Pull request merged**
