### PR TITLE
Bin L1 track quality MVA variable

### PR DESCRIPTION
**Pull request by cgsavard**
#### PR description:

This is the same PR that has been accepted in the L1TK repository [here](https://github.com/cms-L1TK/cmssw/pull/272) with squashed commits. This bins the track quality variable between a 0-1 range where the binning is set in the TTTrack_Word class in DataFormats. These changes do not affect anything in the current code and is just structural.

#### PR validation:

Checks have been done to ensure the code is working as expected and that the new structure is not affecting anything. The typical code checks and formatting has also been done.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
