### PR TITLE
Fix crash of ECAL GPU reco when ECAL is out of the run.

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Fixes a crash of the EcalUncalibRecHitProducerGPU module when the ECAL is not in the run. The reason for the crash is that the number of channels is not properly initialised to zero in the EcalRawToDigiGPU when there are no FEDs to unpack.
Also improved error message that helped to find the origin of the problem.

#### PR validation:

HLT configuration detailed in https://github.com/cms-sw/cmssw/issues/34197#issuecomment-891987459 runs to completion now.

### CODE REVIEW

**Comment by thomreis** [comment]
type bug-fix

**Comment by perrotta** [comment]
urgent

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34765	2245ffb 
- code changes are in line with the PR description (and related discussion up to https://github.com/cms-sw/cmssw/issues/34197#issuecomment-892479195)
- jenkins tests pass and comparisons with the baseline show no relevant differences (small differences in 10824.502 are unrelated to ECAL)

**Comment by perrotta** [comment]
+1

**Pull request merged**
