### PR TITLE
add scouting collections to MINIAODSIM Event Content

### PR DESCRIPTION
**Pull request by dsperka**
#### PR description:

This PR is to include Run 3 data scouting collections by default in MINIAODSIM event content. This will facilitate much wider usage of data scouting in CMS given the availability of the collections in all officially produced MC samples. I am not sure if this is the correct branch to merge into, but the change is very simple so I can prepare the PR in a different release without any problem

#### PR validation:

The change was checked to correctly include the collections in the MINIAODSIM event content. In a small sample it was checked that this would increase the event size of MINIAOD by about 4%.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
>  I am not sure if this is the correct branch to merge into, but the change is very simple so I can prepare the PR in a different release without any problem

Indeed @dsperka the PR should be submitted to the master branch first (or even "only": what's the purpose of having it in 11_2?)

Let also xpog evaluate the additions to the miniAOD event content:

assign xpog

**Comment by perrotta** [comment]
assign xpog
(perhaps it has to be written at the beginning...)

**Comment by mariadalfonso** [comment]
@dsperka
I understood that the Scouting avoid PAT and miniAOD format; 
so your insertion here is only an opportunistic addition to facilitate the analysis (although this can't be a general rule for all Run3 development i.e. skims)

**Comment by mariadalfonso** [comment]
enable profiling

**Comment by mariadalfonso** [comment]
please test

(to check the size increase)

**Comment by mariadalfonso** [comment]
If I read correctly the profiling, the relative size increase is 12%
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-07e5cd/17360/profiling/11834.21/products_miniAOD_sizes_compare_11834.21.txt

The most offending branches are (as expected related to pf-articles and tracks)  Run3ScoutingParticles_hltScoutingPFPacker__HLT Run3ScoutingTracks_hltScoutingTrackPacker__HLT.

**Comment by mariadalfonso** [comment]
@dsperka was this discussed somewhere ?
12% on top of the mini is too much for everysample.
What about customise the content ? so that dedicated signal samples will have this ?

**Comment by dsperka** [comment]
@mariadalfonso I don't know if it has been discussed but would be happy to do so in whatever meeting is appropriate. We would want this not only for dedicated signal samples but also for large background samples.

**Comment by mariadalfonso** [comment]
@dsperka @fwyzard @Sam-Harper 
may I ask which reconstruction is used at the moment for the tracks  Run3ScoutingTracks_hltScoutingTrackPacker__HLT. ?
I understand that the final scouting should happen with the patatrack reconstruction or at least not the "Run2-legacy": the switch already happened ?
This will help to understand if this 12% is a final upper limit

**Comment by dsperka** [comment]
I asked this in a recent TSG meeting and this is the answer I received:

Question: What version of HLT tracking is being used to produce MC? I.e. is it running the latest version?
answer: run2018 tracking except for V0 scouting which were pixel tracking
updating improves timing but not physics performance

@mmasciov may be able to provide more details.

Anyway I don't think the version of reco. will effect the event size. @jsalfeld told me that the variables in the Run3ScoutingTracks were to be studied and maybe some of them would be dropped, so I think this 12% would probably go down.

In any case, I don't think we want to be making decisions on the scouting event content itself based on whether or not we can store it in the MINIAOD. 

I can explain better how accessing scouting info in MC was done in the past: scouting event content is stored in AOD, and people would run on AOD to get the info they need and store in a private ntuple. Because AOD is not stored on disk, this means staging huge datasets to access only a few collections. Also at this stage you could also access things like the generator level variables as well, but you would not have access to MINIAOD level info (essentially PF objects). If this PR were merged it would be much faster (no waiting for staging) and simpler (could have a single code framework for storing scouting and stanard objects in the same ntuple).

I think the tradeoff here is semi permanently increasing the disk usage of MINIAOD by ~10% vs. transiently increasing the disk usage of AOD (when the dataset needs to get staged) by some unknown amount, depending on how many datasets people need, how often they run, and how many people need to run.

**Comment by mariadalfonso** [comment]
@dsperka
it's clear that this is opportunistic, but we cannot accommodate in miniAOD everything (i.e. scouting, long lived particle low level collections,BPH ... ) otherwise the size blow easily.
The alternative is to make skim of AOD: once you have the AOD sim, the campaign produce two outputs: standard mini and ScoutingSkim (and all the other skims needed ). Clearly doesn't make sense to keep in AOD only since those will not stay on Disk in Run3.

For tracks, I understand that there is some work ahead, and would be good to sort things soon, so that we do not add by mistake 50% to the Run3 mini.

**Comment by dsperka** [comment]
@mariadalfonso Maybe this is a question for computing, but would the skim stay on disk? If so and if we were to skim all samples then it is equivalent to this request. Doing it for only select samples would be reasonable and should save some disk space, however there is one point:

- Would the two file solution work for the skim and the parent AOD or the MINIAOD? If not, then we would lose the possibility to easily access the MINIAOD info for event by event comparisons (e.g. deriving object corrections by using the MINIAOD objects). Also for a skim of AOD, it would be good to include then the GEN event content also in the skim, and this would create some duplication since the same collection would also be in the MINIAOD version of the sample.

**Comment by perrotta** [comment]
@dsperka realizing now, while discussing it at the ORP, that this PR is submitted for 11_2: please move it to master, and close this PR (no further updates are foreseen for 11_2)

**Comment by qliphy** [comment]
Closing this PR as IB 11_2_X is closed now.

**Pull request closed without merging**
