### PR TITLE
move DataRecord includes to HBHERecHitProducerGPU

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

This PR fixes a problem with the includes made visible to nvcc in RecoLocalCalo/HcalRecProducers.  nvcc is normally not supposed to be exposed to EventSetup records.  In this case, this is leading to compilation errors in the gcc13 IBs where nvcc does not support all the intrinsic builtins used by gcc13.  Details in #44583.

This PR simply moves some DataRecord includes to a narrower scope where nvcc won't be exposed.

#### PR validation:

Compiles with gcc13.  Purely technical fix.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc13

though build will fail due to other errors in gcc13 IBs but lets just check if nvcc build errors are gone

**Comment by smuzaffar** [comment]
`nvcc` build errors for gcc13 are [fixed]( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-61f0a0/38567/build-logs/RecoLocalCalo/HcalRecProducers/log.html )

**Comment by antoniovilela** [comment]
+1

**Comment by makortel** [comment]
@kakwok FYI (although should not really impact the Alpaka porting)

**Pull request merged**
