### PR TITLE
Phase2-hgx269 Make use of ESGetToken and remove usage of HCAL (in one app)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken and remove usage of HCAL (in one app)

#### PR validation:

Tested using the runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@cvuosalo Please approve this

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
