### PR TITLE
Updates to precision timing integration in reconstruction and miniaod [93x]

### PR DESCRIPTION
**Pull request by bendavid**
Backport of https://github.com/cms-sw/cmssw/pull/20338 (will update when the review of that one is completed)

This supercedes https://github.com/cms-sw/cmssw/pull/20489

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by civanch** [comment]
please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by bendavid** [comment]
(just for the record, this is currently in sync with https://github.com/cms-sw/cmssw/pull/20338)

**Comment by bendavid** [comment]
Keeping in sync with https://github.com/cms-sw/cmssw/pull/20338

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20535	f47aad5 
- consistent backport of #20338 (modulo a few clang-tidy related lines in SimTracker/TrackAssociation/plugins/TrackTimeValueMapProducer.cc )
- jenkins tests pass and show the same number of differences as the tests in master as of https://github.com/cms-sw/cmssw/pull/20338	213e0b3

**Comment by lgray** [comment]
Can everyone please sign? This needs to go in!

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
