### PR TITLE
Phase2-hgx337C Backport the bugfix from #41380 to CMSSW_13_0_X in Geometry/HGcalCommonData to take care of the segmentation fault for 25234.911

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the bugfix from #41380 to CMSSW_13_0_X in Geometry/HGcalCommonData to take care of the segmentation fault for 25234.911

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

It is a (partial) backport (relevant for the bug fix) of #41380

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41380
(partial backport)

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- There is no plan yet for Phase2 productions with 13_0_X, but let backport this fix anyhow

**Pull request merged**
