### PR TITLE
MTD: update ETLDetId to accomodate larger module numbers

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is an update of #30557 . 

The future ETL v5 (to be implemented in a following PR) introduces D-shaped sectors, instead of the quarters used in ETL v4. The new, D-shaped sectors comprise more than 512 modules, which is the maximum number of modules that can be accommodated using the bits presently allocated in ETLDetId. ETLDetId.h has been modified to fix this issue, by adding 2 bits. The new ETLDetId is backward compatible with the older versions, thanks to a dedicated compatibility code implemented, and active in all relevant constructors.

#### PR validation:

The dedicated geometry tests provide the desired ETL det id, test wf 23234.0 and 23434.999 complete successfully. See discussion in #30557 for earlier checks.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with cms-data/Geometry-TestReference#4

**Comment by cvuosalo** [comment]
From the PR description, it is not clear to me why this PR should create comparison differences. Is the cause of the differences understood?

**Comment by kpedro88** [comment]
@fabiocos changes in phase 2 workflows seem to arise from fluctuations in the FTL RecHit time value:
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_FTLRecHitsSorted_mtdRecHits_FTLEndcap_RECO_obj_obj_time
is this expected?

**Comment by fabiocos** [comment]
@cvuosalo @kpedro88 this issue was already noticed in the scrutiny of previous PR #30557 and explained by @casarsa in https://github.com/cms-sw/cmssw/pull/30557#issuecomment-668659214 : the ETLDetId defines the order in which the SimHits are processed within the digitization, and the random fluctuations applied to the different physical quantities. We may repeat the test of running without smearing, and convince ourselves again that this is the only cause for the changes.

**Comment by casarsa** [comment]
@cvuosalo @kpedro88 @fabiocos 
I've redone the comparison for WF 23234.0 with the time smearing of the ETL DIGIs switched off:
CMSSW_11_2_X_2020-09-22-1100 vs CMSSW_11_2_X_2020-09-22-1100 + 31511

ETL_LocalReco_EtlHitTimeZneg

**Comment by kpedro88** [comment]
thanks @casarsa !

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
