### PR TITLE
Fix throwing CapacityExausted

### PR DESCRIPTION
**Pull request by VinInn**
catch "buffer full" before insertion (as in pre-threadSafe version).
print LogError (as in pre-threadSafe version).
tested with runTheMatrix and addOnTests.py -t hlt_data_GRun reducing the capacity to 10K...

will recompile the universe

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@fwyzard , @mtosi, @rovere  FYI

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15529 29a097f
- change is in line with description
- jenkins tests pass and comparisons with baseline show no difference
- the unit test failure is unrelated to this PR

**Pull request merged**
