### PR TITLE
/validation/RecoEgamma/ # bins and ranges histos modifications.

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

The range and binning of a few histograms have been made configurable so that they can be adjusted for the Phase2 validation through an Era modifier.  

Modifications are made in plugins folder (ElectronMcSignalValidatior.cc/h and ElectronMcFakeValidator.cc/h) and into the python folder (ElectronMcSignalValidator_gedGsfElectrons_cfi.py, ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py, ElectronMcFakeValidator_gedGsfElectrons_cfi.py).
hard coded values have been replaced with named values which can be modified into python files, and the values are adjusted for PHASE2 validation via an era modifier.

comp-before-after
links : 
before modifications : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU2/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/
after modifications : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU4/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/

special tests : 
before : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU2/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/gifs/h_recOfflineVertices.gif
after : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU4/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/gifs/h_recOfflineVertices.gif

before : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU2/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/gifs/h_scl_EoEtrueVsrecOfflineVertices_barrel_pfx.gif
after : http://cms-egamma.web.cern.ch/cms-egamma/validation/Electrons/Dev/TEST_FOLDER/GedvsGed_TEST_FOLDER_PU4/Fullgedvsged_RelValZEE_14_gedGsfE_Startup/gifs/h_scl_EoEtrueVsrecOfflineVertices_barrel_pfx.gif

#### PR validation:

compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine (34 33 32 24 16 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch -> OK.
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html) -> OK.
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html) -> OK.

@beaudett

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
HI @archiron 
I believe the changes you described are in line with what we get in the WF validation, but it would be nice if you can confirm:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-09-02-2300+bf10a2/38624/dqm-histo-comparison-summary.html
Thanks

**Comment by archiron** [comment]
Sorry, but do you say with "WF validation". It is the fisrt time I read that.
is it the name for CMS DQM GUI ?
Arnaud

@beaudett

**Comment by jfernan2** [comment]
WF = Workflow Flow
I was asking mainly for a confirmation if the changes we get in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-09-02-2300+bf10a2/38624/dqm-histo-comparison-summary.html
are what you expect
Thanks

**Comment by archiron** [comment]
It seems all is OK. Sorry for the delay, I looked over all histograms and all is as we expect.
thanks.
Arnaud

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
