### PR TITLE
Add explicit raw collection label for L1TRawToDigi

### PR DESCRIPTION
**Pull request by mandrenguyen**
The --repacked command tells the driver to grab raw data with the remapped label.
It does this by invoking the following:
from Configuration.Applications.ConfigBuilder import MassReplaceInputTag
MassReplaceInputTag(process, new="rawDataMapperByLabel", old="rawDataCollector")

The problem is that this doesn't seem to get picked up when this is set in the fillDescriptions, as in EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc

This PR makes the InputTag explicit, such that it's picked up by MassReplaceInputTag

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 140.56,140.57

**Comment by fabiocos** [comment]
this workaround looks to solve the problem #25177 . @Dr15Jones is this supposed to be the expected behaviour of https://cmssdt.cern.ch/lxr/source/FWCore/ParameterSet/python/MassReplace.py ? 
I see that the InputTag parameter is set as tracked in the fillDescription function of L1TRawToDigi but then it is never mentioned in all the cfi files built using this module in the python area. I would like to understand whether this is to be considered as a bug (which is fixed by this PR), regadless of the behaviour of MassReplace....

**Comment by fabiocos** [comment]
@rekovic @thomreis please see this fix, at present L1T is not correctly working for HI workflows

**Comment by Dr15Jones** [comment]
@fabiocos the python code can't see stuff that is only in C++. That being said, it actually isn't that the value is defined in `fillDescription` that causes the problem. The problem is there is a hand written `cfi.py` file for the module which takes precedence over the `cfi.py` file that `fillDescription` generates. The auto generated `cfi.py` would have had the `InputLabel` parameter exposed to python and therefore would have been changed by the call to `MassReplace`.

**Comment by fabiocos** [comment]
merge

**Comment by rekovic** [comment]
+1

**Pull request merged**
