### PR TITLE
add `SiStripBadStripFromHitEffRcd` to `DropBoxMetaData` for Tier-0 replays

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, in relation of need at https://github.com/dmwm/T0/pull/4674.
Related to PR https://github.com/cms-sw/cmssw/pull/37530.

#### PR validation:

Run the producer and the reader successfully.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> -1

failure is unrelated (relvals input time-out seen also in other PRs recently)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+1
 * tests pass, the payload created with this is already in a T0 replay

**Comment by qliphy** [comment]
+1

**Pull request merged**
