### PR TITLE
sync up with #32372: remove unnecessary include in PhysicsTools/PatAlgos slimmedLowPtElectrons_cff.py

### PR DESCRIPTION
**Pull request by slava77**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32426	e76077e
- technical/trivial

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
