### PR TITLE
Synchronisation of HCal Config for HLT_75E33 menu (Phase2)

### PR DESCRIPTION
**Pull request by beaucero**
#### PR description:

Synchronisation of HCal Configuration for HLT_75E33 menu, the tiny changes in the config are not changing physics results

#### PR validation:

Running HLT_Simplified_menu Phase2 with the new configuration is successful.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
 - workflows = 20834.76
 - relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by missirol** [comment]
@beaucero, shouldn't the same update be applied to [`HLT_75e33/modules/hbhereco_cfi.py`](https://github.com/cms-sw/cmssw/blob/4a6a52fa6fe319f6afb7afaef14d6c02668f9cec/HLTrigger/Configuration/python/HLT_75e33/modules/hbhereco_cfi.py), too? 

What is the plan to resolve these duplications, and use only the modules named `hlt*` in the HLT Phase-2 menu?

**Comment by abdoulline** [comment]
Actually I don't see here one more suggested/considered (back in September) "saving time" change:

<         nMaxItersMin = cms.int32(500),
---
>         nMaxItersMin = cms.int32(50),

(as it's in HLTrigger/Configuration/python/HLT_2022v14_cff.py)

**Comment by beaucero** [comment]
@missirol Sorry for the delay, loking further indeed, there are quite some duplications of modules which should be removed etc. But we are currently busy with the Annual Review, so cleaning will come later on. Looks likethe second file should be also modified (until it disappears) @abdoulline Sorry for missing the suggestions.
If I understood everything well, a new commit has just been made...

**Comment by missirol** [comment]
@beaucero , okay, thanks. It looks okay now. For updates like this to the HLT Phase-2 menu, what is currently the target release? This PR updates 12_6_X; for 12_5_X or lower, separate PRs would be needed (after this one is integrated).

**Comment by beaucero** [comment]
@missirol, no real target as the above changes are not really changing the results of the HLT. I was simply a mis-synchronisation of files which was not nice to carry on propagating. So what is easier to go, we should go for this one. (Same thing when we will do the cleaning, there will be no real release target etc)

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
