### PR TITLE
Initial implementation of PathStatus and EndPathStatus products

### PR DESCRIPTION
**Pull request by wddgit**
The producers for these products are run automatically after
a Path or EndPath completes. They will be useful in a
multithreaded context as they allow creating a dependence
between a module and a path in a way similar to how
a consumes declaration creates a dependence between
two modules.

### CODE REVIEW

**Comment by wddgit** [comment]
This is a duplicate of the pull request submitted to CMSSW_9_2_X

**Comment by wddgit** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
port from master of #19052

**Comment by Dr15Jones** [comment]
backport #19052

**Comment by Dr15Jones** [comment]
@wddgit my change to async global end transitions appears to have caused a conflict. Please fix so @davidlange6 can merge this into _DEVEL.

**Comment by wddgit** [comment]
@Dr15Jones I take a look and resolve the conflicts and update this.

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
I rebased and fixed the conflict. The conflict was only in a reference log file used in a test. No other changes.

**Comment by Dr15Jones** [comment]
@davidlange6 ping

**Comment by davidlange6** [comment]
merge

**Comment by Dr15Jones** [comment]
+1
So it is removed from my pending list

**Pull request merged**
