### PR TITLE
HLT menu development for `13_0_X` (5/N) [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

It includes the integration of the following JIRA tickets.

  - [CMSHLT-2587](https://its.cern.ch/jira/browse/CMSHLT-2587): [HCAL,CSC,GEM] sync `hcalRecAlgos` and `muonDetIdAssociator` ES modules with Run-3 offline reco
  - [CMSHLT-2635](https://its.cern.ch/jira/browse/CMSHLT-2635): [BPH] use pixel-triplet matching in low-mass di-electron triggers
  - [CMSHLT-2637](https://its.cern.ch/jira/browse/CMSHLT-2637): [BPH] use pixel-triplet matching in `HLT_SingleEle*` control triggers
  - [CMSHLT-2651](https://its.cern.ch/jira/browse/CMSHLT-2651): [DAQ] changed compression settings of all OutputModules to (algorithm = "ZSTD", level = 3)
  - [CMSHLT-2684](https://its.cern.ch/jira/browse/CMSHLT-2684): [HIG] triggers for HH4b in semi-resolved topology
  - [CMSHLT-2685](https://its.cern.ch/jira/browse/CMSHLT-2685): [HIG] added PNet-based VBF HToCC triggers
  - [CMSHLT-2688](https://its.cern.ch/jira/browse/CMSHLT-2688): [BPH] added 2023 L1T seeds to BsMuMu triggers (part 2)
  - [CMSHLT-2689](https://its.cern.ch/jira/browse/CMSHLT-2689): [JME] halved PSs of `HLT_PFJetFwd80` and `HLT_AK8PFJetFwd80` (part 2)
  - [CMSHLT-2694](https://its.cern.ch/jira/browse/CMSHLT-2694): [B2G] added backups of `AK8(Di,)PFJet*_MassSD(30,50)` triggers
  - [CMSHLT-2696](https://its.cern.ch/jira/browse/CMSHLT-2696): [TSG] store unseeded E/gamma in Scouting, and use separate L1EG-seeded Scouting triggers
  - [CMSHLT-2698](https://its.cern.ch/jira/browse/CMSHLT-2698): [BPH] removal of four `Dimuon0_Upsilon` triggers from GRun (combined table unchanged)
  - [CMSHLT-2701](https://its.cern.ch/jira/browse/CMSHLT-2701): [JME] additional `HLT_Photon*EB_TightID_TightIso` triggers
  - [CMSHLT-2707](https://its.cern.ch/jira/browse/CMSHLT-2707): [EXO] moved MuShower-seeded DT/CSC-cluster triggers to Muon PD
  - [CMSHLT-2721](https://its.cern.ch/jira/browse/CMSHLT-2721): [BPH] set PS=0 for `HLT_Mu12_IP6_v` and remove `ParkingSingleMuon*` streams/PDs from GRun
  - [CMSHLT-2724](https://its.cern.ch/jira/browse/CMSHLT-2724): [EXO] added HLT-HT cut to L1_Mu6HT240-seeded displaced-jets triggers
  - [CMSHLT-2726](https://its.cern.ch/jira/browse/CMSHLT-2726): [EGM] removed `*ForBParking*` Sequences from `MC_Egamma_Open*` triggers, and add `MC_Egamma_Open*` to GRun menu

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - workflows = 139.004,140.003,140.023,140.043,140.063,12634.0,12634.99,12834.0,13034.0,13034.99

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Wf `4.67` [failed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c04d34/31470/runTheMatrixINPUT-results/4.67_ZElSkim2012C/step2_ZElSkim2012C.log) with [1], but the file is present in the cmsbot cache as usual, and I can access it locally. This looks like a transient issue, unrelated to this PR.

[1]
```
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/data/Run2012C/DoubleElectron/RAW-RECO/ZElectron-22Jan2013-v1/20000/02C8CD56-BF68-E211-9057-003048679182.root?xrdcl.requuid=d1ff2322-8f6c-4313-a65b-5f9937f06c24.
```

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by missirol** [comment]
After this PR was merged, the HLT-Validation tests of the `CMSSW_13_1_X_2023-03-21-2300` IB failed [[1]](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_13_1_X_2023-03-21-2300/el8_amd64_gcc11/runIB.log).

On the other hand, the errors [[2]](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_13_1_X_2023-03-21-2300/el8_amd64_gcc11/RelVal_DigiL1RawHLT_PIon_MC.log) [[3]](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_13_1_X_2023-03-21-2300/el8_amd64_gcc11/RelVal_DigiL1RawHLT_PRef_MC.log) seem unrelated to the PR; they look like transient failures in accessing files:
```
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_3_0_pre6/RelValTTbar_14TeV/GEN-SIM/123X_mcRun3_2021_realistic_v11-v1/10000/29297788-21c3-4bf2-afe0-5382f08fbcd5.root?tried=&xrdcl.requuid=0265148c-57ad-495d-bec6-cc74de8bebf1.

[..]

Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_3_0_pre6/RelValTTbar_14TeV/GEN-SIM/123X_mcRun3_2021_realistic_v11-v1/10000/29297788-21c3-4bf2-afe0-5382f08fbcd5.root?tried=&xrdcl.requuid=c98b28a9-0272-41d9-926d-658d7acd9418.
```

This is somewhat similar to the transient errors seen during the tests of this PR, see https://github.com/cms-sw/cmssw/pull/41113#issuecomment-1477956374.

(The errors happen to come from the PRef- and PIon-menu tests, and one can see that this PR changed those menus minimally; the same menus passed the "addOnTests" during the PR tests.)

I conclude that this PR is okay, and the backport can be merged (#41114).

**Pull request merged**
