### PR TITLE
Phase2-hgx280 Check SIM step for V15 Geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Check SIM step for V15 Geometry of HGCal

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@civanch @srimanob Could you review and approve this PR?

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by rovere** [comment]
In future, can we please have some more descriptive text in the PR message? I saw mainly changes protected by `#ifdef EDM_ML_DEBUG`, but others, instead, are non-protected and, at a first glance, fix bugs or extend functionalities. 
Reading the comments it's impossible to guess what's happening.

**Pull request merged**
