### PR TITLE
Improving HGCal validation 

### PR DESCRIPTION
**Pull request by ebrondol**
#### PR description:

* Enable the option `--collection all` to produce a list of collection with respective plots, while keeping the single collection option also available
* Improve the visualisation of the validation for each collection with the creation of tables of plots  
* If `--separate` option is enable, each entry in the table will be converted to a link to a webpage which will displayed all plots separately. In order to do this, I have created `SeparateValidation` which is enable in the `makeHGCalValidationPlots.py` script. 

#### PR validation:

* I have verified that the code is still working in case the `SimpleValidation` is used with the `--separate` option.
* Two examples of my development can be found in [this folder](http://ebrondol.web.cern.ch/ebrondol/HGCal/fixValidation_all/20201111_all_no_separate/) using only the flag `--collection all` and in [this other folder](http://ebrondol.web.cern.ch/ebrondol/HGCal/fixValidation_all/20201111_allTiclMultiClusters_separate/) using `--separate --collection allTiclMultiClusters`

### CODE REVIEW

**Comment by ebrondol** [comment]
@apsallid @rovere @felicepantaleo

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
