### PR TITLE
Phase2-hgx360I Change names from 2026 to Run4 in several scripts of Geometry (CaloTopology|ForwardCommonData|GEMGeometry|MTDCommonData|MuonNumbering|TrackerCommonData|TrackerGeometryBuilder)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change names from 2026 to Run4 in several scripts of Geometry (CaloTopology|ForwardCommonData|GEMGeometry|MTDCommonData|MuonNumbering|TrackerCommonData|TrackerGeometryBuilder)

#### PR validation:

Tested the modified scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
Hi @bsunanda 
Thanks for the PR. Do you have PRs to come on updating name, on configuration and filenames? So I can recheck again after this PR is merged. For geometry XMLs and folders under Geometry, I will not touch.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , @srimanob , do I understand correctly that the schema will be following: most python scripts will have "Run4" inside instead of year. Some geometry directories will migrate to 2026 -> 2030. In past, having files corresponding to years was useful but knowing in advance what year will run4 start/changed/ likely impossible. Should we still use year or we can everywhere migrate to "Run4"?

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar,  @srimanob, @subirsarkar Please approve this PR

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
