### PR TITLE
Add QCD muon-enriched for upgrade relvals

### PR DESCRIPTION
**Pull request by bendavid**
Adding gen fragment + python bits so qcd muon enriched can be added to upgrade/timing relvals.

Gen fragment is from BTV-RunIISummer15GS-00001

### CODE REVIEW

**Comment by bendavid** [comment]
@lgray

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by hengne** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by kpedro88** [comment]
hold

**Comment by davidlange6** [comment]
merged via #16535

**Pull request closed without merging**
