### PR TITLE
Adapt RivetInterface for Rivet 2.7.2

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Update RivetInterface for Rivet Core change https://bitbucket.org/heprivet/rivet/commits/6ae4b32acee01c19b4fc064fa168e1083a61621c

#### PR validation:

RivetInterface runs successfully with new Rivet release 2.7.2

**Needs https://github.com/cms-sw/cmsdist/pull/5005**

### CODE REVIEW

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@intrepid42 could you please clarify what is the interface change that needs adaptation? I see essentially a slightly modified loop for AnaHandle...

**Comment by intrepid42** [comment]
Hi Fabio

* `CmpAnaHandle` was deleted in Rivet core
* `Rivet::AnalysisHandler::analyses()` changed from `const std::set<AnaHandle, CmpAnaHandle>& analyses() const` to `std::vector<AnaHandle> analyses() const` so that we had to get rid of CmpAnaHandle
* Switched to range-based for loop in addition (like it is done in Rivet core also)

**Comment by fabiocos** [comment]
@intrepid42 thanks for the clarification, so it is effectively a small adjustment, although a needed one

**Comment by fabiocos** [comment]
+1

**Pull request merged**
