### PR TITLE
Phase2-hgx302B Use MessageLogger for cout in the second set of Analyzers in HGCalGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use MessageLogger for cout in the second set of Analyzers in HGCalGeometry

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
@cmsbuild please test

Just to see if we can get rid of failure comparison.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Technial PR to handle message logger.

**Comment by srimanob** [comment]
@cmsbuild please test

To clean up unexpected failure comparison.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
