### PR TITLE
Pf validation update

### PR DESCRIPTION
**Pull request by chosila**
**PR description:**

This PR introduces more types of jets under ParticleFlow in the DQM root files. This adds AK4 CHS and PUPPI, both with and without jet energy correction to DQM files. This change can be seen in the DQM files under ParticleFlow/Run summary/JetResponse. Before, JetResponse will contain the histograms of 1 type of jet, but in this PR it will contain slimmedJets/JEC, slimmedJets/noJEC, slimmedJetsPuppi/JEC, and slimmedJetsPuppi/noJEC. Histograms of jets without energy correction will have "Raw" in the title to distinguish them from ones with jet energy correction. 

test/compare.py was also changed to accommodate the folder structure changes. 

**PR validation:**

[http://hep.baylor.edu/chosila/PFVal/plots_fixedName/test_pf.html](http://hep.baylor.edu/chosila/PFVal/plots_fixedName/test_pf.html)

Shows the histograms made with compare.py and the DQM files made using the modified scrips in this PR. The sampled used in the plots were the same QCD sample, so it looks like only 1 sample is visible.  

> nohup runTheMatrix.py -l 11634.0 -j 8 &>11634.0.log &
> nohup runTheMatrix.py -l 23234.0 -j 8 &>23234.0.log &

were also ran in addition to the QCD samples, and it produces the same expected outputs. 
[http://hep.baylor.edu/chosila/PFVal/plots_TTbar/TTbar_pf.html](http://hep.baylor.edu/chosila/PFVal/plots_TTbar/TTbar_pf.html) shows the plots made with compare.py using the DQM files made with the above runTheMatrix.py 

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

This PR is not a backport. 

@hatakeyamak @bendavid @juska

### CODE REVIEW

**Comment by jfernan2** [comment]
@chosila can you please add yourself to the PF DQM Validation developers e-group in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Particle_Flow_PF

**Comment by chosila** [comment]
> @chosila can you please add yourself to the PF DQM Validation developers e-group in:
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Particle_Flow_PF

Yes, i put in the subscription request and currently waiting for approval.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@chosila the number of changs introduced by the PR is important as expected. Can you please check that everything is as you wish?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-03-02-2300+6408fd/35309/dqm-histo-comparison-summary.html
In particular, the binning of preso and presponse  seems too large and some reso distributions are empty probably due to low stats in the test wf

**Comment by chosila** [comment]
> @chosila the number of changes introduced by the PR is important as expected. Can you please check that everything is as you wish?
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-03-02-2300+6408fd/35309/dqm-histo-comparison-summary.html
> In particular, the binning of preso and presponse seems too large and some reso distributions are empty probably due to low stats in the test wf

We can try to add the capability to drop high pt plots in the forward region in future iterations, since it will be complicated (adding checks in all stages, analyzer, harvester, plotter). For now, I think I've added what we need.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
@chosila this PR reduces by a factor of 2 the entries in ParticleFlow / GenJets. 
Was it expected? Is it a bug fix?
Example:
image

**Comment by chosila** [comment]
> @chosila this PR reduces by a factor of 2 the entries in ParticleFlow / GenJets.
> Was it expected? Is it a bug fix?
> Example:
> image

This is not expected. Thank you for pointing that out. I am currently working on fixing it.

**Comment by silviodonato** [comment]
> > @chosila this PR reduces by a factor of 2 the entries in ParticleFlow / GenJets.
> > Was it expected? Is it a bug fix?
> > Example:
> > image
> 
> This is not expected. Thank you for pointing that out. I am currently working on fixing it.

@chosila have you found the reason of the difference? Perhaps the previous version was bugged (ie. scaled by a factor 2) and the current version is ok

**Comment by silviodonato** [comment]
please test
to check if the latest commit solves the problem

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
The errors in the unit test look like a timeout since no real error is reported

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
> -1
> 
> Tested at: [a0f8a79](https://github.com/cms-sw/cmssw/commit/a0f8a7924836e42f6e4b7736bbf6bb649db3babe)
> 
> CMSSW: CMSSW_11_1_X_2020-03-16-2300
> SCRAM_ARCH: slc7_amd64_gcc820
> You can see the results of the tests here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6408fd/5211/summary.html
> 
> I found follow errors while testing this PR
> 
> **Failed tests: UnitTests**
> 
>     * **Unit Tests**:
> 
> 
> I found errors in the following unit tests:
> 
> ---> test TestDQMOfflineConfiguration150 had ERRORS
> ---> test TestDQMOfflineConfiguration50 had ERRORS

@schneiml Could you have a look to this error? Does the test take too much time?

**Pull request merged**
