### PR TITLE
[91X] Replace TMatrix by Eigen matrices and various fixes in MillePede workflow

### PR DESCRIPTION
**Pull request by ghellwig**
This PR introduces the Eigen-based version of GBL and removes further usage of TMatrix from th MillePede workflow.
The runtime of the Mille step is reduced by  approx. 30% without loss of generality and without changing the functionality.
Further changes only improve user-friendliness by adding better examples, protections and examples.

The changes of this PR are based on #18138.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
please test

**Comment by arunhep** [comment]
please test
comparisons are no longer available

**Comment by ghellwig** [comment]
please test
failure due to (transient?) xrootd problems

**Comment by arunhep** [comment]
+1
the tests failed because of xrood/eos errors. but they have passed in earlier runs.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
