### PR TITLE
Add import test for professor2

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Add import test for "professor2" mc tool

### CODE REVIEW

**Comment by iarspider** [comment]
please test with cms-sw/cmsdist#7777

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7783

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
