### PR TITLE
New E/g HLT Pixel Matching : 91X (really for 91X this time)

### PR DESCRIPTION
**Pull request by Sam-Harper**
This is the 91X flavour of https://github.com/cms-sw/cmssw/pull/18541 which ended up going for 92X.

This PR is unfortunately necessary to be able to run the E/gamma HLT  efficiently with the phaseI pixels and as such needs to be 91X.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1
Identical to #18541, already approved for the master

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1
but lets try to identify such low level changes needed before making the last open release next time. Thanks

**Pull request merged**
