### PR TITLE
Add a DDFilteredView test in DetectorDescription/DDCMS

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Addition of a test example for DDFilteredView built using a filter in ```DetectorDescription/DDCMS``` , developed while debugging an issue in the migration of ```MTDNumberingBuilder``` to DD4hep (```fv.printFilter()``` apparently not found, likely an issue with templates).

#### PR validation:

```scram b runtest``` runs correctly, and the output of the test ```ddfilteredview``` looks the expected one.

### CODE REVIEW

**Comment by fabiocos** [comment]
@ianna FYI

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
I am updating it to provide further example

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
These failures are present in the IB and have clearly nothing to do with this PR and its latest update. The added unit test runs successfully.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
