### PR TITLE
Remove false dependency to TrackingTools/PatternTools.

### PR DESCRIPTION
**Pull request by alja**
I noticed this when building cmsShow tarball.

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16220 9f4a4a260ac9e3a8ce16b24783b4f64796d4e715

Removing false dependency from DataFormats/EgammaTrackReco BuildFile.xml. There should be no change in compiled output.

Jenkins tests against baseline CMSSW_8_1_X_2016-10-14-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
