### PR TITLE
<update of #19487> updated Displaced Jet Paths DQM for 9.3.x

### PR DESCRIPTION
**Pull request by jingyuluo**
This PR is based on PR #19685 and #19487 , I merged the PR #19685 and then add the implementation of Displaced Jet Path DQM (#19487) on the top of it.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by jingyuluo** [comment]
Seems I missed the latest commit ("remove multiple definition of the same modules") from #19685... I'll merge again and resolve the conflict.

**Comment by dmitrijus** [comment]
I will check it once #19685 is merged.

**Comment by jingyuluo** [comment]
Hi @dmitrijus , it seems that #19685 is merged, would it be okay to check this PR?

Thanks,
Jingyu

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
tracked by #19142

**Comment by fwyzard** [comment]
@mtosi @dmitrijus can you confirm that the change in DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py is OK ?

**Comment by fwyzard** [comment]
I have resolved the conflicts in #19916.
Please DO NOT TOUCH this PR/branch, and leave it open.

**Comment by mtosi** [comment]
@fwyzard 
yes,
https://github.com/cms-sw/cmssw/pull/19694/files#diff-8660299b2ade38cf3638eb31ccb685f6R64
it is needed in order to have the hit efficiency plots
(the corresponding parts are created by https://github.com/cms-sw/cmssw/pull/19694/files#diff-9efda7ea2a6f4ed4928aed59e313bd6dR8)

@jingyuluo 
I would have used
trackingForDisplacedJetMonitorClientHLT
rather than
trackingforDisplacedJetEffFromHitPatternHLT
but, it should not be a big issue

**Comment by fwyzard** [comment]
Make a separate PR (on top of #19916) to change it...

**Comment by jingyuluo** [comment]
Hi @fwyzard and @mtosi , here is the new PR #19923 , I merged #19916 , and changed to "trackingForDisplacedJetMonitorClientHLT"

**Comment by dmitrijus** [comment]
@fwyzard The change to DQMOffline_SecondStep_cff looks fine.

**Pull request merged**
