### PR TITLE
Allow to preset timeout for connection on coral-supported Databases - back-port for 12_0_X

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Back-port of https://github.com/cms-sw/cmssw/pull/35406

Required to operate in online workflows.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by tvami** [comment]
@ggovi can you please include [12_0_X] in the PR title? Just to be obvious that this is a backport. Also is this a "must" for the the beam tests, i.e. should we make it urgent?

**Comment by ggovi** [comment]
@tvami that's correct, pretty urgent as we need it for the beam test...

**Comment by francescobrivio** [comment]
ugent

**Comment by francescobrivio** [comment]
+db

 - test succesful, master PR merged already, needed for test beam

**Comment by perrotta** [comment]
backport of #35406

**Comment by perrotta** [comment]
+1
- needed for online data taking

**Pull request merged**
