### PR TITLE
Added esConsumes to modules in RecoMuon/MuonIdentification

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- updated helper classes to support esConsumes

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by jpata** [comment]
+reconstruction
- technical, no reco changes expected/observed

**Comment by perrotta** [comment]
+1

**Pull request merged**
