### PR TITLE
Introducing PU WFs for phase2

### PR DESCRIPTION
**Pull request by boudoul**
As requested by @slava77 , I have introduced the PU workflows (PU_35) in runthematrix for the following ones : 
2023tilted with PU :   runTheMatrix.py --what upgrade -l 114xx
2023GReco with PU  :   runTheMatrix.py --what upgrade -l 116xx

Please note that the WFs can be used for testing as long as there is no change in the geometry which can break them ( and in that case, a new minbias should then be generated)  - 
I would appreciate if PdmV can keep the minbias PU dataset for phase2 up to date  in runthematrix each time fresh relvals are generated.
@ebrondol , @VinInn , @rovere  :  FYI

### CODE REVIEW

**Comment by boudoul** [comment]
@kpedro88 FYI

**Comment by kpedro88** [comment]
@boudoul looks good to me

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ebrondol** [comment]
Hi @boudoul , a probably näive question: why did you choose a PU_35 instead of an higher one (for example PU_140 which should be the baseline for HL-LHC)?

**Comment by boudoul** [comment]
that's a good question - There is no fundamental reason - It's more to start with a resonnable value first and also to have a comparison (physics performance and resources) with what is done with the same release with run2/phase1 -

**Comment by ebrondol** [comment]
Ok, I see. It is a good point. So I expect another update of the WF with higher PU in the next days/months?

**Comment by boudoul** [comment]
lets see how it goes for PU35 , but in any case one can always run the same WFs at your desired PU . It's like the number of events, it's by default 10, but you can run on you favorite number of events by adding to the runthematrix the --command option - 
Just to give an example of a combined change of the number of events and pile up : 
runTheMatrix.py --what upgrade -l 11400 --command "-n 1 --pileup AVE_140_BX_25ns"

**Comment by slava77** [comment]
PU140 should probably use premixing
or have a smaller BX coverage to have smaller impact on IO.

**Comment by davidlange6** [comment]
actually 35PU should have worse I/O than 140PU since reco time is nonlinear with pileup (and the I/O is)

**Comment by slava77** [comment]
@davidlange6 
I'm not sure I understand.
I guess your comment is for a multi-job setup when RECO and digi/mixing steps are running randomly weighted.
My comment was for a single relval job as in jenkins or local.

**Comment by davidlange6** [comment]
> On May 24, 2016, at 3:59 PM, Slava Krutelyov <notifications@github.com> wrote:
> 
> @davidlange6 
> I'm not sure I understand.
> I guess your comment is for a multi-job setup when RECO and digi/mixing steps are running randomly weighted.
> My comment was for a single relval job as in jenkins or local.

my comment assumes an equal number of digi and reco (with tracking) events processed, yes.

**Comment by kpedro88** [comment]
@mdhildreth is working on premixing for the phase 2 tracker and HGCal. Until this is ready, using a lower PU number for relvals is probably better.

**Comment by boudoul** [comment]
on the other hand, we already routinely made plenty (but really plenty) of relvals with PU140 (even PU 200) at the time of 62XSLHC

**Comment by kpedro88** [comment]
@hengne can you sign? just a minor change to add some PU workflows for Phase2

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
