### PR TITLE
JetMETCorrections/Modules: Change return type of EDProducers.

### PR DESCRIPTION
**Pull request by gartung**
Remove class member not needed.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones 
accidentally force pushed this branch and closed the previous PR>

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Those workflows are failing in the IB.

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21991	1ae065a
- technical 
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
