### PR TITLE
`getPayloadData.py`: fix `--suppress-output` and `--image_plot` options for Py3

### PR DESCRIPTION
**Pull request by mmusich**
solves #34193

#### PR description:

Addresses https://github.com/cms-sw/cmssw/pull/34298#issuecomment-877796208.

#### PR validation:

Testing the script with options `--suppress-output` and `--image_plot` now succeeds, while before it wasn't.
Also passes the augmented unit tests with `scram b runtests`. 
It should be also checked in the production environment.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

NA

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Seems this quite help:
```python
/afs/cern.ch/user/c/condbpro/public/BROWSER_PI/loadData.py  --plugin pluginBeamSpot_PayloadInspector --plot plot_BeamSpotParameters --tag BeamSpotObjects_0TdNdEtaCollision2015_v0_mc --input_params '{}' --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --suppress-output --image_plot
[2021-07-12 16:25:40,356] [/data/services/cmsDbBrowser/app/payload_inspector/pi_utils.py:32] - ERROR: [PI] error: b'{\n    "version": "1.0",\n    "annotations": {\n        "payload_type": "BeamSpotObjects",\n        "title": "Display of BeamSpot parameters",\n        "type": "Image"\n    },\n    "file": "c0445e1d-9be0-4112-a849-cca2cf2f81ac.png"\n}'
[2021-07-12 16:25:40,357] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:56] - INFO: [PI] Getting image : <_io.BytesIO object at 0x7f801c0fcaf0>
[2021-07-12 16:25:40,357] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:59] - INFO: [PI] Closing ssh connection
[2021-07-12 16:25:40,358] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:64] - INFO: [PI] mine : <class 'magic.Magic'> <magic.Magic object at 0x7f801be1d4a8>
[2021-07-12 16:25:40,358] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:66] - INFO: [PI] type image : <class 'str'> application/x-empty
[2021-07-12 16:25:40,358] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:68] - INFO: [PI]  image obj : <_io.BytesIO object at 0x7f801c0fcaf0>
[2021-07-12 16:25:40,358] [/data/services/cmsDbBrowser/app/payload_inspector/image_plot.py:72] - ERROR: Unsupported format: application/x-empty
188.185.84.85 - - [12/Jul/2021 16:25:40] "GET /cmsDbBrowser/payload_inspector/image_plot/Prod/CMSSW_12_0_0_pre4/eyJwbG90cyI6MSwicGxvdDEiOnsidGFnIjoiQmVhbVNwb3RPYmplY3RzXzBUZE5kRXRhQ29sbGlzaW9uMjAxNV92MF9tYyIsInBsb3QiOiJwbG90X0JlYW1TcG90UGFyYW1ldGVycyIsInBsdWdpbiI6InBsdWdpbkJlYW1TcG90X1BheWxvYWRJbnNwZWN0b3IiLCJ0eXBlIjoiSW1hZ2UiLCJpbnB1dF9wYXJhbXMiOnt9LCJpb3ZzIjp7InN0YXJ0X2lvdiI6IjEiLCJlbmRfaW92IjoiMSJ9fX0=?imageNum=0 HTTP/1.1" 500 -
```
see [log](https://cms-conddb.cern.ch/admin/tail?service=cmsDbBrowser)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
in the last push I've taken the version implemented by @Dres90 at:
` /afs/cern.ch/user/c/condbpro/public/BROWSER_PI/loadData.py `
which is currently working in [the DB broswer](https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod/CMSSW_12_0_0_pre4/eyJwbG90cyI6MSwicGxvdDEiOnsidGFnIjoiU2lQaXhlbEdlbkVycm9yREJPYmplY3RfcGhhc2UyX0lUX3Y2LjEuNV81MHg1MF92Ml9tYyIsInBsb3QiOiJwbG90X1NpUGl4ZWxUZW1wbGF0ZUhlYWRlclRhYmxlIiwicGx1Z2luIjoicGx1Z2luU2lQaXhlbFRlbXBsYXRlREJPYmplY3RfUGF5bG9hZEluc3BlY3RvciIsInR5cGUiOiJJbWFnZSIsImlucHV0X3BhcmFtcyI6e30sImlvdnMiOnsic3RhcnRfaW92IjoiMSIsImVuZF9pb3YiOiIxIn19fQ==):

image

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
@mmusich looks like `--suppress-output` is not working. In IBs logs and local runs, I still see binary image data ( https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc9/CMSSW_12_1_X_2021-08-09-2300/unitTestLogs/CondCore/Utilities#/258 ) . Can we avoid this printed on stdout which `--suppress-output` is used?

**Comment by mmusich** [comment]
@smuzaffar no, that's how it is supposed to look like as far as I can tell

**Comment by smuzaffar** [comment]
so may be you can add an option to write it in to a file to avoid it being printed on screen or for this specific test just redirect the output to a file? All I see after running is something like 

getpayload

**Comment by mmusich** [comment]
@smuzaffar What's the problem with it being printed to screen?

**Comment by smuzaffar** [comment]
It prints some binary data which messes up my shell :-)

**Pull request merged**
