### PR TITLE
Run3-TB48 Add a new beam line definition for October TB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The new beam line definition comes from the xl file who made a detailed simulation of the beam line from the secondary target to the front of HGCal

#### PR validation:

Tested with the cfg file in Geometry/HGCalCommonData/test/python

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
Kind reminder to simulation @civanch @mdhildreth ?

**Comment by bsunanda** [comment]
@civanch Please sign this

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
