### PR TITLE
Move `FitWithRooFit` out of `bin` folder to make it available for `DiMuonMassBiasClient`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all: 
   * Move the `FitWithRooFit` class out of `Alignment/OfflineValidation/bin` such that there is a header file publicly available for other classes to use (commit c55d87cf8e48fd98214579c4239d2a3700ecedde)
   * use it to introduce a new method in `DiMuonMassBiasClient` to use one of the models available in  `FitWithRooFit`, though the options is for now not active by default (commit 267ef5a0869551ed6ebcb620e95aeb522d24c573)
   
No changes expected.

#### PR validation:

`scram b runtests use-ibeos` runs fine. 
Also I've privately run the tests configuration files in `DQMOffline/Alignment` to run on 2023C data and obtained the fits available [here](http://musich.web.cern.ch/musich/display/combinedBWtimesCB_data.pdf) .

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, possibly to be backported for 2023 data-taking

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/alca-l2 @cms-sw/dqm-l2 a kind ping on this one

**Comment by francescobrivio** [comment]
+1

- PR according to description
- tests clean

**Comment by perrotta** [comment]
+1

**Pull request merged**
