### PR TITLE
HCAL Fb DQM monitoring at layer1

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:

This PR includes additional calolayer1 DQM monitoring elements for HCAL LLP trigger feature bits. Added elements are the 6 fine grain bits occupancy readout at uHTR/layer1 and their comparison, and the single LLP feature bit output expected vs emulated.

#### PR validation:

Validated by running offline DQM on past commissioning runs, expected plots are produced. It has also been included in the online DQM production release based on 12_6_3 (https://github.com/cms-sw/cmssw/pull/40737) and tested online during MWGR on 9 Feb. Test went fine, so this PR to master is to make it permanent.

### CODE REVIEW

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- Differences in L1T CaloLayer DQM plot as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
