### PR TITLE
Develop validation post processor

### PR DESCRIPTION
**Pull request by webermat**
Backport code to 74X. The PR has been merged into 75X already previously.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

@ktf @davidlange6 
Is there an ETA for the resolution of these timeouts?

**Comment by webermat** [comment]
comparisons look fine

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1
backport needed for miniAOD validation

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8504	 a71cf7f
- the  count of changes and the changed files are as in the 75X version #7948
- jenkins tests run OK
- there are no differences in the jenkins comparisons

**Comment by davidlange6** [comment]
breaks unscheduled validation. I will back out for now. You  can reproduce the problems via

runTheMatrix.py -l 11325 -i all

**Pull request merged**
