### PR TITLE
add centrality bin to HI miniAOD

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

This PR add the centrality bin producer to the HI miniAOD workflow.
This producer has long been in cmssw, and was once part of the reconstruction. 
It consumes the tag that was added in #30930 

#### PR validation:

Tested with workflow 158.01

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@mandrenguyen 
please provide some event size estimates for the added product(s).
unless the product is optimally compressible, some assessment of possible reduction in size would be useful (reduced precision or unused variables).

**Comment by slava77** [comment]
please remind the reason why centralityBin was removed from reco in #18684 . Was there a problem with the producer at run time (if so, was it removed)?

**Comment by mandrenguyen** [comment]
> please remind the reason why centralityBin was removed from reco in #18684 . Was there a problem with the producer at run time (if so, was it removed)?

The centrality bin was originally in the reconstruction.  However, since one needs to see the full data to have the corresponding calibration, we always ended up overwriting the produced centrality bins.   At some point we were running HI reco using pp GTs, and the code was crashing since the tag was not available.   So we simply removed it.  For miniAOD, we think we'll often be running in such a way that the calibrations can be added to the GT for production.

**Comment by mandrenguyen** [comment]
I just added a single integer per event, which is the actual output to this module.  The previously added collection is the input, which we would like to keep as well.
To answer Slava's question, these two collections amount to 0.2% of the miniAOD size for wf 158.01.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@mandrenguyen It was noticed that the `CentralityBinProducer`[1] is an old-style EDProducer. Could we profit from this PR and update it to `edm::global::EDProducer`?

[1] https://github.com/cms-sw/cmssw/blob/master/RecoHI/HiCentralityAlgos/plugins/CentralityBinProducer.cc#L46

**Comment by mandrenguyen** [comment]
> @mandrenguyen It was noticed that the `CentralityBinProducer`[1] is an old-style EDProducer. Could we profit from this PR and update it to `edm::global::EDProducer`?
> 
> [1] https://github.com/cms-sw/cmssw/blob/master/RecoHI/HiCentralityAlgos/plugins/CentralityBinProducer.cc#L46

@jpata   I played around this a bit, but I'm not able to get it to work.  Simply changing to edm::global::EDProducer (and adding edm::StreamID as the first argument) causes compiler errors .  By trial and error I was able to suppress those but this gave a segFault.  Perhaps this could be handled by someone a bit more expert than me?

**Comment by mandrenguyen** [comment]
> > @mandrenguyen It was noticed that the `CentralityBinProducer`[1] is an old-style EDProducer. Could we profit from this PR and update it to `edm::global::EDProducer`?
> > [1] https://github.com/cms-sw/cmssw/blob/master/RecoHI/HiCentralityAlgos/plugins/CentralityBinProducer.cc#L46
> 
> @jpata I played around this a bit, but I'm not able to get it to work. Simply changing to edm::global::EDProducer (and adding edm::StreamID as the first argument) causes compiler errors . By trial and error I was able to suppress those but this gave a segFault. Perhaps this could be handled by someone a bit more expert than me?

I guess some change is necessary to the beginRun function to use the new style EDProducer, but I'm not sure exactly what.

**Comment by slava77** [comment]
if edm::stream is simpler/more familiar, I think that it can be acceptable

**Comment by mandrenguyen** [comment]
> if edm::stream is simpler/more familiar, I think that it can be acceptable

That was easier, thanks!

**Comment by mandrenguyen** [comment]
Can someone give me a 'please test', please?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+1

- tests pass
- adds a single int to HI miniAOD workflows
- output is filled with meaningful values
- technical update to CentralityBinProducer from `edm::EDProducer -> edm::stream::EDProducer` as requested

**Comment by silviodonato** [comment]
merge
@santocch

**Comment by santocch** [comment]
+1

**Pull request merged**
