### PR TITLE
Merge of  #11786 on top of #11989

### PR DESCRIPTION
**Pull request by mmusich**
Porting the changes from #11989 
The connection strings pointing to v1 have been replaced to the single V2 connection string.
In addition, the fixes for handling of cfg params in CondCore/ESSources have been ported.

In addition, new GTS:
# Summary of changes
## Run I simulation
- **Ideal scenario** : [74X_mcRun1_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_design_v2) as [74X_mcRun1_design_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_design_v1/74X_mcRun1_design_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Realistic scenario** : [74X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_realistic_v2) as [74X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_realistic_v1/74X_mcRun1_realistic_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Heavy Ions** : [74X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_HeavyIon_v2) as [74X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_HeavyIon_v1/74X_mcRun1_HeavyIon_v2):
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
- **Proton-Lead** : [74X_mcRun1_pA_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_pA_v2) as [74X_mcRun1_pA_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_pA_v1/74X_mcRun1_pA_v2): 
  - adding new b-tag GBRForest payloads  
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
## Run II simulation
- **Asymptotic scenario** : [74X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_asymptotic_v4) as [74X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_asymptotic_v4/74X_mcRun2_asymptotic_v2):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario
  - updated Jet energy corrections for 25 ns.
- **Ideal scenario** : [74X_mcRun2_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_design_v4) as [74X_mcRun2_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_design_v4/74X_mcRun2_design_v2):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario
  - updated Jet energy corrections for 25 ns.
- **Startup scenario** : [74X_mcRun2_startup_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_startup_v3) as [74X_mcRun2_startup_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_startup_v2/74X_mcRun2_startup_v3):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS.
- **Heavy Ion** : [74X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_HeavyIon_v3) as [74X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_HeavyIon_v2/74X_mcRun2_HeavyIon_v3):
  - taxonomy changes (removing account names from tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping
  - added new label for BDT MVA discriminators for Btagging
  - updated Pixel bad channel map as at the beginning of Run2015D
  - updated HCAL ZS threshold in order to read-out HF as fully NZS
  - updated Jet probability calibration as a result of Spring15 campaign in asymptotic scenario.
## Run II data
- **HLT processing** : [74X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_HLT_frozen_v3) as [74X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_HLT_frozen_v2) (snapshot time set to 2015-10-14 10:09:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_HLT_frozen_v2/74X_dataRun2_HLT_frozen_v3):
  - taxonomy changes (removing account names from tags or separating MC and data tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping, Tracker and Castor reconstruction geometry, L1 RPC Hardware configuration, DT and CSC APE.
- **Offline processing** : [74X_dataRun2_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v4) as [74X_dataRun2_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_v5/74X_dataRun2_v3):
  - all changes intended for Run2015A+B+C re-reco
  - taxonomy changes to avoid fully qualified account names in the tag name for several records
  - removing unused b-tagging working point records 
  - new set of tags covering the update of JEC for the 25ns data taking period. L2L3Residuals and uncertainties for 25ns have been updated.
## Run I data
- **HLT processing** : [74X_dataRun1_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_HLT_frozen_v3) as [74X_dataRun1_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_HLT_frozen_v2) (snapshot time set to 2015-10-14 10:09:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_HLT_frozen_v2/74X_dataRun1_HLT_frozen_v3):
  - taxonomy changes (removing account names from tags or separating MC and data tags) for DT reconstruction uncertainties, ECAL intercalibration errors, ECAL electronic mapping, Tracker and Castor reconstruction geometry, L1 RPC Hardware configuration, DT and CSC APE.
- **Offline processing** :  [74X_dataRun1_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v4) as [74X_dataRun1_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v3) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_v3/74X_dataRun1_v4):
  - all changes intended for Run2015A+B+C re-reco
  - taxonomy changes to avoid fully qualified account names in the tag name for several records

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@ggovi ping! I believe you're fine with your changes :)

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@ggovi can you please sign this again? I just updated one of the autoCond GTs to take the latest version. Thanks

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@davidlange6 I have been asked to update the 7.4.X Global Tags including the latest JEC for miniAOD analysis. Would it be possible to merge this PR or even only #11786 to have a set to start with?
Thanks

**Comment by mmusich** [comment]
please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by diguida** [comment]
@ggovi ping :-)

**Comment by ggovi** [comment]
+1

**Pull request closed without merging**
