### PR TITLE
Fix reading prescale values during miniAOD production (94X)

### PR DESCRIPTION
**Pull request by gpetruc**
Fix reading prescale values during miniAOD production by setting ReadPrescalesFromFile = False, to get the proper PS column
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3572/1/1.html

backport of #22131

@arizzi @rekovic

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
backport of #22131

@smuzaffar : maybe cms-bot could also grep for this patterns into the text of the PR; same goes for `type bugfix`?

**Comment by slava77** [comment]
hold

apparently we will integrate this into something other than 94X. The "hold" is added to indicate this.

**Comment by slava77** [comment]
assign l1

we need feedback from L1 on correctness of using the configuration parameters

**Comment by rekovic** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22132	63915f4
- switch to reading prescales from DB in miniAOD
    - the backport is correct
- jenkins tests pass and comparisons show no differences

**Comment by perrotta** [comment]
Unless a more proper solution is found in the meanwhile, the same patch as in #22239 shold be backported also here

**Comment by slava77** [comment]
unhold

at about the same time I have also removed the "+1" because this needs a fix for reading 80X MC

**Comment by slava77** [comment]
@gpetruc 
@apana 
do we have a resolution for this PR now regarding the 80XLegacy?

**Comment by gpetruc** [comment]
I think it would be good if L1 people could check what is the correct
solution to read L1 prescales in 2016 data and MC - it's not really up to
me to do it.

**Comment by apana** [comment]
Hi Slava, Giovanni,

I am working on it.  Didn't have a chance to do much over the weekend, but
I have the time now. I hope to have a fix shortly.

-Len

**Comment by slava77** [comment]
@apana 
Please update on the status of the resolution to the issue of reading 80X MC.
Feb 26 target is approaching.
Thank you.

**Comment by apana** [comment]
Hi Slava,

I have found the problem that caused the crash in the 80X MC workflow.
In the early uGT MC (before we put the prescales in the db), the
prescale factors were extracted from the tables using a different
indexing convention for the columns. This index was then written into
the GlobalAlgBlk product. In this 80x MC workflow, we get the index
from the original GlobalAlgBlk product, but since the indexing
convention has changed, the program crashes due to an out-of-bounds
exception. This shouldn't cause any problems for data reprocessing or
in MC workflows where we re-emulate the L1 trigger.

I have a solution for this in PR  #22314.  Please have a look and let
me know if you think it's OK.  Also, the PR is for 10_1_X.  Please let
me know what other releases need the fix.

Cheers,
Len

**Comment by perrotta** [comment]
@apana : a backport of your fix for this CMSSW_9_4_MAOD_X cycle is certainly needed, so that this PR can get merged

**Comment by apana** [comment]
@perrotta : Hi Andrea. OK, I will make the PR for CMSSW_9_4_MAOD_X.  However, the workflow doesn't crash in this release because the change that triggered the crash, setting ReadPrescalesFromFile to False in triggerProducer_cfi.py, wasn't implemented. Should I additionally update the value to True or leave it as is?

**Comment by slava77** [comment]
On 2/22/18 9:38 PM, Leonard Apanasvich wrote:
> Hi Slava,
> 
> I have found the problem that caused the crash in the 80X MC workflow.
> In the early uGT MC (before we put the prescales in the db), the
> prescale factors were extracted from the tables using a different
> indexing convention for the columns. This index was then written into
> the GlobalAlgBlk product. In this 80x MC workflow, we get the index
> from the original GlobalAlgBlk product, but since the indexing
> convention has changed, the program crashes due to an out-of-bounds
> exception. This shouldn't cause any problems for data reprocessing or
> in MC workflows where we re-emulate the L1 trigger.
> 
> I have a solution for this in PR #22314. Please have a look and let
> me know if you think it's OK. Also, the PR is for 10_1_X. Please let
> me know what other releases need the fix.

Hi Len,

The change looks fine to me.
We will need a port to 94X as Andrea already mentioned.

		--slava

> 
> Cheers,
> Len
> 
> On Thu, Feb 22, 2018 at 7:47 AM, Slava Krutelyov

**Comment by perrotta** [comment]
What about adding here the commit with the fix prepared by @apana, and merging all at once in 94?
@gpetruc

**Comment by apana** [comment]
The corresponding PR for CMSSW_9_4_MAOD_X is #22332.  I left triggerProducer_cfi.py as is for now.

**Comment by fabiocos** [comment]
@slava77 @perrotta  #22332 has been merged, so I assume this can now move forward as well

**Comment by slava77** [comment]
+1

see more details in https://github.com/cms-sw/cmssw/pull/22132#issuecomment-364958710

**Comment by slava77** [comment]
I have removed the reco +1 again, until the problems with patTrigger time per event are resolved

**Comment by slava77** [comment]
@cmsbuild please test
to confirm the timing issues in 94X as well

**Comment by apana** [comment]
Hi Slava,

I have identified the source of the timing problems you discovered. In L1TGlobalUtil::retrieveL1Event we have some code that does some manipulations of the BX mask data record to put the info in a more user friendly container and those manipulations are pretty expensive.  Here is the relevant block of code:  

https://github.com/apana/cmssw/blob/5c4d67ca8d223b3d770578ea0b99afeff77027a9/L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc#L180-L205

This code is meant to be run once per event and in some rough timing tests I ran, it costs about 0.1 sec to run. Since the BX masks do not change very frequently, this block can probably be updated so we don't do these manipulations on every event. 

However the real problem is in PATTriggerProducer, where instead of calling retrieveL1Event once per event, it calls it for every trigger in the event.  This is where you get the ~50sec/event.

I will look into fixing both retrieveL1Event and PATTriggerProducer, but it may take a few days (I don't know much about PATTriggerProducer). In case you are wondering, this doesn't show up when ReadPrescalesFromFile is set to true because we do no BX masking in this case.  It also may not have shown up in 2017 workflows since, at least in the run I checked, there was no BX masking done. But I will have to check with our run ops guys to see how often that is true.

Sorry for the long message.

**Comment by slava77** [comment]
On 2/28/18 4:27 PM, Leonard Apanasvich wrote:
> Hi Slava,
> 
> I have identified the source of the timing problems you discovered. In
> L1TGlobalUtil::retrieveL1Event we have some code that does some
> manipulations of the BX mask data record to put the info in a more user
> friendly container and those manipulations are pretty expensive. Here is
> the relevant block of code:
> 
> https://github.com/apana/cmssw/blob/5c4d67ca8d223b3d770578ea0b99afeff77027a9/L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc#L180-L205
> 
> This code is meant to be run once per event and in some rough timing
> tests I ran, it costs about 0.1 sec to run. Since the BX masks do not
> change very frequently, this block can probably be updated so we don't
> do these manipulations on every event.
> 
> However the real problem is in PATTriggerProducer, where instead of
> calling retrieveL1Event once per event, it calls it for every trigger in
> the event. This is where you get the ~50sec/event.
> 
> I will look into fixing both retrieveL1Event and PATTriggerProducer, but
> it may take a few days (I don't know much about PATTriggerProducer). In
> case you are wondering, this doesn't show up when ReadPrescalesFromFile
> is set to true because we do no BX masking in this case. It also may not
> have shown up in 2017 workflows since, at least in the run I checked,
> there was no BX masking done. But I will have to check with our run ops
> guys to see how often that is true.
> 
> Sorry for the long message.
> 

Hi Len,

Thank you for the thorough investigation.
Perhaps Giovanni can aid with PATTriggerProducer.


I'm a bit puzzled why this timing problem is visible only while reading
AOD data reconstructed in 80X.
Shouldn't the same problem be happening in e.g. workflow 136.8311
which is using
/store/data/Run2017F/JetHT/AOD/17Nov2017-v1/70000/0054D144-36DF-E711-B074-02163E01A47B.root
Run 305064.
This workflow is available now only in 10_1_X, e.g. in  a recent
CMSSW_10_1_X_2018-02-27-1100 that I have used for tests already and I
know that in this IB the 80X input job is slow while the 136.8311 is
fast (~50 ms/ev in patTrigger)

**Comment by slava77** [comment]
@apana 
please clarify if you have more information about the bx masking of the algorithms.
This is actually relevant for 2016, 2017, and now for 2018.

Is there a flag that can be checked at run time so that the slow code does not get executed (at least until it is fixed)?

Depending on the situation, we may need to revert #22131 in the master as well.

**Comment by slava77** [comment]
Hi Len,

On 3/7/18 3:53 PM, Leonard Apanasvich wrote:
> Hi Slava,
> 
> Sorry for the delay. The code block that is causing the long execution
> times can simply be commented out or removed. The bx masks cannot change
> during a run, so we only need to fill/update the mask arrays when the
> run is changed, and this is already done in
> L1TGlobalUtil::retrieveL1Setup. The superfluous code is in
> L1TGlobalUtil::retrieveL1Event and can be removed.
> 
> Can you let me know which branches I need to submit PR's for? Are they
> 9_4_MAOD_X and 10_1_X?

yes, these two are enough.

Thank you.


> 
> (FYI: The code block I pointed to earlier was wrong. The block that can
> be removed is
> https://github.com/apana/cmssw/blob/5c4d67ca8d223b3d770578ea0b99afeff77027a9/L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc#L261-L286)
>

**Comment by apana** [comment]
The PRs have been made. #22519 is for the master branch, while #22520 is for 9_4_MAOD_X. 

I think it would be good to see if it is possible to clean up PATTriggerProducer as well, so if nobody is looking into that, I will give it a try.  But this is not critical for the current release cycle.

**Comment by slava77** [comment]
@cmsbuild please test with #22520

the hope is to see that the 80X miniAOD wf is fast again

**Comment by slava77** [comment]
Based on the latest tests in 136.7611 (miniAOD on 80XLegacy) , the time for 100 events is down to 3 min, which looks acceptable (better than 1h it took before)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22132	63915f4

- reinstating reco signature (previously provided but then taken away in https://github.com/cms-sw/cmssw/pull/22132#issuecomment-364958710). This PR can now proceed after the side issue solved in #22520 was merged earlier today.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
