### PR TITLE
Add Pixel MergedDeadROCOccupancy Maps to TkMap script and FPix panel  bug patch (backport to 10_1_X of #23339)

### PR DESCRIPTION
**Pull request by arossi83**
Changes only on Offline Shifter tools, no changes on production workflow

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
backport of #23339

**Comment by dmitrijus** [comment]
Welcome @arossi83 

Why does this PR have more changes than the one in master?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

merged in master, affecting only online tools

**Pull request merged**
