### PR TITLE
Phase2-hgx258 Correct V14 geometry for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct V14 geometry for dd4hep

#### PR validation:

Tested using private cfg files in the test areas of Geometry/HGCalCommonData

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
