### PR TITLE
add onlineBeamSpotESProducer to BeamSpot_cfi: fix general Online BS swap case

### LINKED ISSUE #35634: Crash in `visualization` DQM clients during SPLASH test
A crash in the vizualization DQM clients was reported by @pmandrik during the SPLASH test. The clients crashing are:
[visualization-live_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live_cfg.py)
[visualization-live-secondInstance_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py)
And the crash error is:
```
----- Begin Fatal Exception 12-Oct-2021 16:07:52 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 345570 lumi: 1 event: 4035 stream: 2
   [1] Running path 'FEVToutput_step'
   [2] Prefetching for module JsonWritingTimeoutPoolOutputModule/'FEVToutput'
   [3] Prefetching for module ReducedRecHitCollectionProducer/'reducedEcalRecHitsEB'
   [4] Prefetching for module InterestingDetIdCollectionProducer/'interestingEcalDetIdPFEB'
   [5] Prefetching for module PFECALSuperClusterProducer/'particleFlowSuperClusterECAL'
   [6] Calling method for module BeamSpotOnlineProducer/'offlineBeamSpot'
Exception Message:
No "BeamSpotTransientObjectsRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
The crash can be easily riproduced by running the unitTest:
```
cmsrel CMSSW_12_0_2_patch1
cd CMSSW_12_0_2_patch1/src
cmsenv
git cms-addpkg DQM/Integration
cmsRun DQM/Integration/python/clients/visualization-live_cfg.py unitTest=True
```
DQM online experts can also reproduce the crash in their playback system at P5.

This crash happens **only** when running with the scenario `ppEra_Run3` and **don't crash** when running with scenario `cosmicsEra_Run3`. 
IIUC this is because the reco requence in the two cases is different and in in the `pp` case the beamspot is required.
Looking into the configuration I can see that the offlineBeamSpot has been swapped with the onlineBeamSpot:
```
(Pdb) process.offlineBeamSpot
cms.EDProducer("BeamSpotOnlineProducer",
    changeToCMSCoordinates = cms.bool(False),
    gtEvmLabel = cms.InputTag("gtEvmDigis"),
    maxRadius = cms.double(2),
    maxZ = cms.double(40),
    setSigmaZ = cms.double(-1),
    src = cms.InputTag("scalersRawToDigi"),
    useTransientRecord = cms.bool(True)
)
``` 
and the only place this swapping happens is in: https://github.com/cms-sw/cmssw/blob/922a36d28f367fe6a5a7feb4f000d7e460b5c43a/Configuration/DataProcessing/python/RecoTLR.py#L7-L15
which is used to customize the express processing. So now the sequence will look for a `BeamSpotTransientObjectsRcd` but apparently that is not provided by any Source and this is not clear to me because the express customization automatically adds the BeamSpotESProducer.

A quick solution would then be to add the ESProducer to the DQM clients:
```
process.load("CondCore.CondDB.CondDB_cfi")
process.BeamSpotESProducer = cms.ESProducer("OnlineBeamSpotESProducer")
```
But I'm not sure if that is the correct way of doing it or if it's better to understand how the customization of the `visualizationProcessing` works and eventually modify it?

[EDIT]
The quick solution to add the ESProducer to the DQM clients was already somehow used in https://github.com/cms-sw/cmssw/pull/35373

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/35634

#### PR description:

In PR https://github.com/cms-sw/cmssw/pull/35373 the general case for the online <-> offline BS swap done via modifiers was missed, leading to issues in the visualization DQM clients. 
This PR supplies the `onlineBeamSpotESProducer` to `BeamSpot_cfi` as a general case fix-up.

#### PR validation:

Run `cmsRun DQM/Integration/python/clients/visualization-live_cfg.py unitTest=True`
that before was crashing with: 

```
...
Exception Message:
No "BeamSpotTransientObjectsRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

while now crashes differently with:

```
----- Begin Fatal Exception 13-Oct-2021 10:41:57 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 334393 lumi: 1 event: 16132 stream: 1
   [1] Running path 'FEVToutput_step'
   [2] Prefetching for module JsonWritingTimeoutPoolOutputModule/'FEVToutput'
   [3] Prefetching for module ReducedRecHitCollectionProducer/'reducedEcalRecHitsEB'
   [4] Prefetching for module EleIsoDetIdCollectionProducer/'interestingGedEleIsoDetIdEB'
   [5] Calling method for module GEDGsfElectronFinalizer/'gedGsfElectrons'
Exception Message:
No data of type "GBRForestD" with label "electron_eb_ecalOnly_1To300_0p2To2_mean" in record "GBRDWrapperRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but should be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by gennai** [comment]
I am not even sure it would work for importing the beamspotProducer in the menu. I do not know if confDB can ignore the part not related to the module description, @Sam-Harper may know better than I do.

**Comment by Martin-Grunewald** [comment]
What is the actual question?

The beam spot producer currently in 12_1 HLT menus is the ```BeamSpotOnlineProducer``` configured like this
```
hltOnlineBeamSpot = cms.EDProducer( "BeamSpotOnlineProducer",
    changeToCMSCoordinates = cms.bool( False ),
    maxZ = cms.double( 40.0 ),
    setSigmaZ = cms.double( 0.0 ),
    beamMode = cms.untracked.uint32( 11 ),
    src = cms.InputTag( "hltScalersRawToDigi" ),
    gtEvmLabel = cms.InputTag( "" ),
    maxRadius = cms.double( 2.0 ),
    useTransientRecord = cms.bool( False )
)
```
There is no parameter called ```timeThreshold``` so this would be set via fillDescriptions, or lead to a crash if not.

**Comment by mmusich** [comment]
Indeed it is:

> There is no parameter called timeThreshold so this would be set via fillDescriptions, or lead to a crash if not.

https://github.com/cms-sw/cmssw/blob/master/RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc#L61

and that's what we want for HLT, no? @gennai @francescobrivio

**Comment by tvami** [comment]
+alca

**Comment by slava77** [comment]
abort test

**Comment by slava77** [comment]
test parameters:
- addpkg = DQM/Integration,Configuration/DataProcessing
- pull_request = #35642

**Comment by perrotta** [comment]
merge

**Pull request merged**
