### PR TITLE
Bugfix for hlt iso mu24 eta2p1

### PR DESCRIPTION
**Pull request by rockybala**
DQM folder corresponding to HLT_IsoMu24_eta2p1 has no filled histograms. The reason was that no trigger by this name is available in the trigger menu. In order to remove this issue, the name of the trigger has been changed from HLT_IsoMu24_eta2p1 to HLT_IsoMu21_eta2p1. The changes has been done in the files in python and test directories.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by rockybala** [comment]
Dear All,

I tried to rebase it but could not do so. Can you please tell me all the steps to follow, in case I am missing something?

Also, I can not open the URL about the log for git cms-merge-topic. It is showing the error: "The requested URL can not be found on this server".

Thanks
rocky

________________________________

**Comment by ferencek** [comment]
@rockybala, in what release did you start this development? I tried to rebase your branch to CMSSW_8_1_0_pre9 but was getting some merge conflicts which suggested to me that most likely your developments were not initially done in the 81X release cycle. In any case, here are the steps I followed:
```bash
cmsrel CMSSW_8_1_0_pre9
cd CMSSW_8_1_0_pre9/src
cmsenv

setenv CMSSW_GIT_REFERENCE /cvmfs/cms.cern.ch/cmssw.git.daily

git cms-addpkg HLTriggerOffline/Btag/

git remote add btv-cmssw git@github.com:cms-btv-pog/cmssw.git
git remote add rockybala-cmssw git@github.com:rockybala/cmssw.git

git checkout -b Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9
git fetch rockybala-cmssw Bugfix-for-HLT_IsoMu24_eta2p1:Bugfix-for-HLT_IsoMu24_eta2p1

git cherry-pick 08a162df28a7c64927f0e3f11a27867e52df0cfd
```
Had to resolve conflict in `HLTriggerOffline/Btag/test/testSequences.py` and then ran `git commit -a`
```bash
git cherry-pick bdfd1f084033657a3eec9cb697522358e17291c4
git cherry-pick c122d6da1bc891e886298ad99cc0208427f8c62b
```
Had to resolve conflict in `HLTriggerOffline/Btag/python/HltBtagValidation_cff.py` and then ran `git commit -a`
```
git cherry-pick eae95a3e64ab0baa06731f73bb5b1b1f8001551a
```
Had to resolve conflict in `HLTriggerOffline/Btag/python/HltBtagPostValidation_cff.py` and then ran `git commit -a`
```
git push btv-cmssw Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9
```
Have a look at the final result at the following link
https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...cms-btv-pog:Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9

If these are the changes you want, you can pick them up and push to this PR by following the following steps in your CMSSW working area (note that this will overwrite the branch currently used for this PR)
``` 
git remote add btv-cmssw git@github.com:cms-btv-pog/cmssw.git

git fetch btv-cmssw Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9:Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9
git push --force my-cmssw Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9:Bugfix-for-HLT_IsoMu24_eta2p1
```
That should be it. Let me know if you have any questions.

**Comment by silviodonato** [comment]
Hi @ferencek ,
your link is not working. Could you send it to us again?
Thanks!

**Comment by ferencek** [comment]
@silviodonato, you mean the branch comparison link in https://github.com/cms-sw/cmssw/pull/15297#issuecomment-236054219? It works for me just fine.

**Comment by silviodonato** [comment]
Yes, I was meaning:

> 
> Have a look at the final result at the following link
> CMSSW_8_1_X...cms-btv-pog:Bugfix-for-HLT_IsoMu24_eta2p1-PR_from-CMSSW_8_1_0_pre9

@rockybala  please try the code suggested by @ferencek 
Thanks.

**Comment by ferencek** [comment]
@silviodonato, thanks for the clarification. The link works for me so maybe there was some temporary problem opening it. Also, I think Rocky already followed my recipe since the merge conflicts, which were present at the time of creating of this PR, are now gone.

**Comment by silviodonato** [comment]
Ok, great! So the problem was already solved

**Comment by ferencek** [comment]
@silviodonato, in addition, the diff for this PR and the branch comparison link show identical code changes so I would say the problem is solved. Nevertheless, Rocky should confirm she is happy with the code changes.

As I said in my original comment, it was not entirely clear to me on top of what release the code changes were made and in order to resolve the merge conflicts, an electron trigger name also had to be changed. That looked strange to me since the PR was only referring to a muon trigger and that's why as I asked Rocky to take a look the rebased branch and see if these are the changes she wants. So all I did was to rebase the branch and resolve merge conflicts but the electron trigger part remained a bit of a mystery to me.

**Comment by rockybala** [comment]
Hi Dinko,

I have done all the steps that you suggested.
I am also ok with the changes that appear in the comparison section.

Let me know if any thing else is required

Thanks
rocky
________________________________

**Comment by ferencek** [comment]
Thanks, Rocky, for the confirmation.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
@rockybala : does it exist a 80X backport of this pull request? If you want this fix applied on the DQM for this year data taking you need to provide it!

**Pull request merged**
