### PR TITLE
GenParticles2HepMCConverter null pointer protection

### PR DESCRIPTION
**Pull request by jhgoh**
GenParticles2HepMCConverter is crashing during the NanoAOD production, for particle gun samples.
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4965.html

PDF and incident beams are absent in the particle gun samples, but the module is written assuming their existence in the event.
This PR protects crashing by checking null pointer, and add incident dummy proton pair if incident partons could not be catched.

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by arizzi** [comment]
@fabiocos please consider this for the 9_4_5: even if not strictly needed for MINIAOD we will likely use the same release also for NANO. Should the base branch of this PR be moved to the MAOD branch?
Otherwise we  will take it in the AN release, but I guess it is cleaner to just have it in 9_4_5

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@arizzi I am including the two NanoAOD related PRs into 9_4_X, they have been already merged into the master and they are clearly affecting identified portions of code.

**Pull request merged**
