### PR TITLE
Update ResonanceDecayFilterHook.cc

### PR DESCRIPTION
**Pull request by OlivierBondu**
Forward-port of https://github.com/cms-sw/cmssw/pull/14555

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by bendavid** [comment]
Btw, I think this should be backported to 80x as well, since it may be needed for some of the SUSY fastsim samples.

**Comment by OlivierBondu** [comment]
@bendavid: 80X forward port ready: https://github.com/cms-sw/cmssw/pull/14566

any idea why the tests failed ?

**Comment by davidlange6** [comment]
the error is unrelated

**Pull request merged**
