### PR TITLE
HI O2O update: add new parameters and tidy up **103X BACKPORT**

### PR DESCRIPTION
**Pull request by bundocka**
Backport to 103X

- Add required parameters for Heavy Ion running to CaloParamsHelperO2O.h
- Add required functions to L1TCaloParamsOnlineProd.cc
- Add demux LUTs to convertParamsToOnlineFormat.py (not specific to HI)
- Tidy up code so that parameter comparison between files is clearer

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #24867

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
