### PR TITLE
Phase2-hgx350C Steps to create a scenario of B18 Geometry of HGCal where no innecr cell straucture of full wafers are not created atin Geant4 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Steps to create a scenario of B18 Geometry of HGCal where no innecr cell straucture of full wafers are not created atin Geant4 geometry

#### PR validation:

Madea test with overlap check

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

No change is expected from this PR.

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
