### PR TITLE
decouple EventContent_cff load from general purpose use of Merge.py

### LINKED ISSUE #22933: Checking Express event content in Configuration/DataProcessing
While checking #22796 to verify the changes in the event content, I tried to check not only the usual RelVals (in wf 10824 the new totemTiming digi collection is added to the AODSIM event) but also what would happen in express. 

To do this, after having merged #22796 in my work area and added Configuration/DataProcessing, I produced in the test area of this package the express configuration with the command

python RunExpressProcessing.py --scenario ppEra_Run2_2018 --global-tag GLOBALTAG --lfn /store/whatever --fevt --dqmio --alcarecos=TkAlMinBias+SiStripCalZeroBias

and then expanded it with edmConfigDump.

The various process.RecoCTPPSFEVT , AOD etc. PSets for outputCommands are visible, but the event content in the OutputModule is not containing them, while this is not the case when I expand the configuration for step3 of 10824.

Of course the input file, GT above are dummy and I do not expect the configuration to run, but I would expect its content is correct from the python point of view.

What is wrong with this test? In a similar way also muonGEMDigis are absent from the OutputModule.

### PR DESCRIPTION
**Pull request by slava77**
This should resolve #22933 
The immediate problem is for Configuration/DataProcessing/python/Scenario.py, which defines the T0 config driver for production workflows:
- the Merge.py is needed for file merging functionality of the Scenario.py
- the EventContent_cff has to be also loaded for RECO or similar workflows and is normally supposed to be loaded only after the cms.Process object with a relevant era is created (done in the ConfigBuilder.py)
- In the current state the EventContent_cff is loaded in Merge.py for RECO and similar workflows before  cms.Process object is defined. This is a bug.

This fix simply restricts loading of the EventContent_cff in the Merge.py only in merging context for NANO AOD purposes.

Tests:
``` python $CMSSW_BASE/src/Configuration/DataProcessing/test/RunMerge.py  --input-files file:a.root --output-file file:b.root --mergeNANO```
and then config dump to see that the result is as expected. The RunMerge is also made aware of mergeNANO.

```python $CMSSW_BASE/src/Configuration/DataProcessing/test/RunPromptReco.py --scenario ppEra_Run2_2017_pp_on_XeXe --reco --aod --miniaod --dqmio --global-tag 92X_dataRun2_Express_v7 --lfn=file:raw.root```
and then dump to see that _hiCentrality name  actually shows up in the keep statements

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
@slava77 indeed repeating the test of #22933 with this fix, the CTPPS and GEM event contents, that are added through modifiers, are now present in the regular outputCommands where they are expected to be.

**Comment by slava77** [comment]
@fabiocos 
thank you for checking on your side.
I guess we are good to go with this and #22937

**Comment by fabiocos** [comment]
@slava77 yes, the Express configuration produced now is identical to the one with the version obtained removing the update to Merge.py that caused the problem. I do not see other possible validations without putting this code in production.

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
