### PR TITLE
Code maintenance and preparation for Run III in the DQMOffline ZCount…

### PR DESCRIPTION
**Pull request by ThOliveira23**
#### PR description:

This PR is a backport of #37981 for the release 12_4_X.

At the python configuration file there are some modifications in the values for pT, mass range and PU and the change of the trigger (from HLT_IsoMu_27 to HLT_IsoMu_24), concerning the preparation for Run3.

At the plugins, the definition of a Custom Tight ID for the muon, with no consideration of the primary vertices quantities. Also a bug fixing.

#### PR validation:

Compilation of the cmssw

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of #37981 for the release 12_4_X, in order to have the DQM Offline maintenance ready for the July data taking.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type lumi

**Comment by emanueleusai** [comment]
backport of #37981

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
