### PR TITLE
Phase2-hgx245 New support structure for HGCal dated February 2020

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

New support structure for HGCal dated February 2020

#### PR validation:

Tested overlap for this combination. To be integrated to a new scenario after revision of beam pipe and forward shielding

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not needed

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
