### PR TITLE
add CosmicsSPLoose_UP17 to the short matrix to capture failures sooner than full IB

### PR DESCRIPTION
**Pull request by slava77**
we had a few failures in the 2017 cosmic wf in the past few weeks.
It seems like a good time to add it to the PR checkout steps.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

this will actually fail in the latest IB CMSSW_9_3_X_2017-07-20-1100

**Comment by davidlange6** [comment]
this won't test anything in PRs as long as we regenerate gen-sim and use 10 events...

**Comment by slava77** [comment]
On 7/20/17 11:18 AM, David Lange wrote:
> this won't test anything in PRs as long as we regenerate gen-sim and use
> 10 events...

The default workflow regenerates 2000 events (I set it up so that we get
something passing
https://github.com/cms-sw/cmssw/pull/17758

At least one recent failure was in configuration.


Given this, does your comment "this won't test anything" still apply?



>

**Comment by davidlange6** [comment]
nope - i missed that change

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
