### PR TITLE
add V0 monitoring

### PR DESCRIPTION
**Pull request by mtosi**
as requested by the tracking POG
this update is meant to have a new monitoring: the Ks and Lambda monitoring
it is particular important to monitor the hip effect on the tracking as well
@rovere @VinInn @dmitrijus @vanbesien

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
ciao
sorry, but the segmentation fault has anything to do w/ this pr?
looking to the message it is not that clear to me :(
thanks

**Comment by VinInn** [comment]
yes
```
#4  <signal handler called>
#5  0x00007f355343d1f8 in V0Monitor::analyze(edm::Event const&, edm::EventSetup const&) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-06-30-1100/lib/slc6_amd64_gcc530/pluginDQMTrackingMonitor.so
```

136.731is 2016B real data...
please try to reproduce (compile with -g as well)

**Comment by mtosi** [comment]
thanks
I'll do

**Comment by mtosi** [comment]
it should be fixed, now
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT+HARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Jul  1 10:08:37 2016-date Fri Jul  1 09:46:28 2016; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

the issue was related to the access to a nullptr .... 
I'm very sorry, in tests I did it didn't happen and I did not realize it

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
those should not really be related to this pr....

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
/DQMData/Run 1/Tracking/Run summary/V0Monitoring
plots v0_Lxy_normalized have NaNs

e.g. 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-07-06-2300+14837/14838/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/Tracking_V0Monitoring_Ks.html

The downside is that this triggers a failure in comparisons of otherwise identical plots.
Please investigate and fix
(for now I will just ignore these plots in comparisons)

@cvuosalo you'll probably notice these as well

**Comment by slava77** [comment]
@mtosi 
did you have a chance to follow up on https://github.com/cms-sw/cmssw/pull/15090#issuecomment-231073310
Please let me know.
Thank you.

**Comment by slava77** [comment]
@mtosi 
did you have a chance to follow up on https://github.com/cms-sw/cmssw/pull/15090#issuecomment-231073310
Please let me know.
Thank you.

as of CMSSW_8_1_X_2016-08-15-1100, I still see the same problem with the plots

**Pull request merged**
