### PR TITLE
Add energy correlation functions to jet tools 74

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #11028 

The energy correlations functions are currently the default algorithm for W-tagging in ATLAS.
They are not run in RECO/AOD/MiniAOD, but added them to CMSSW for cross check analyses.
They can be tested with:
RecoJets/JetProducers/test/testJetTools_cfg.py

### CODE REVIEW

**Comment by slava77** [comment]
-1 
@ahinzmann 
please resolve conflicts and update

**Comment by ahinzmann** [comment]
In CMSSW_7_4_11 from this morning and also in CMSSW_7_4_X_2015-09-02-2300 I get no conflicts.
Is cmsbuild using something else? Can it recheck?

**Comment by slava77** [comment]
@smuzaffar @degano could you please check what's happening on the bot/git side?
Using our cms-merge-topic I don't get any conflicts either

**Comment by smuzaffar** [comment]
@slava77 , the conflict message is added by github.  It could be that in this PR 
RecoJets/JetProducers/test/jettoolbox_cfg.py is renamed to RecoJets/JetProducers/test/testJetTools_cfg.py along with some changes which are different than default branch CMSSW_7_6_X.

**Comment by slava77** [comment]
On 9/3/15 10:48 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , the conflict message is added by
> github. It could be that in this PR
> RecoJets/JetProducers/test/jettoolbox_cfg.py is renamed to
> RecoJets/JetProducers/test/testJetTools_cfg.py along with some changes
> which are different than default branch CMSSW_7_6_X.

Shahzad,

Do you know if there is a sequence of command-line commands to run
locally to get to the conclusion of github about mergeability?

**Comment by smuzaffar** [comment]
@slava77 and @ahinzmann , I have recreated the PR #11117 which github thinks is merge able. I ran these commands locally to do it
```scram p CMSSW_7_4_X_2015-09-02-2300
cd CMSSW_7_4_X_2015-09-02-2300
cmsenv
git cms-addpkg RecoJets/JetProducers
git remote add ahinzmann git://github.com/ahinzmann/cmssw.git
git fetch ahinzmann ecf_74:ecf_74
git merge -X ours ecf_74
git push my-cmssw from-CMSSW_7_4_X_2015-09-02-2300```
if #1117 looks good then may be we can test that and close this one.

**Comment by ahinzmann** [comment]
ok, let's go with #11117

**Comment by davidlt** [comment]
Double check that content didn't change as `-x ours` was used. It automatically solve merge conflict, by keeping an old version (before merge) of conflicting chunk. Thus double check that all intended code changes are in PR.

**Comment by ahinzmann** [comment]
I confirm that the code changes displayed by github are exactly the same.

**Pull request closed without merging**
