### PR TITLE
Revert "GT Updates: 92X offline, relval, promptLike, and HLT_frozen GT updated to make the release self-consistent with the data taken with it "

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#20984

### CODE REVIEW

**Comment by davidlange6** [comment]
please test workflow 136.77

**Comment by arunhep** [comment]
@davidlange6 what is the reason to revert this?

**Comment by davidlange6** [comment]
Broken 2017h workflows in the ib. Not clear if this is the reason but seems most likely

Cheers,
David


On 27 Oct 2017, at 21:56, Arun Kumar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> what is the reason to revert this?

**Comment by arunhep** [comment]
what is 2017h workflow? can you point us to the error message?
why this problem did not appear in 94X.

**Comment by davidlange6** [comment]
Typo 2016h

https://cms-sw.github.io/relvalLogDetail.html#slc7_amd64_gcc630;CMSSW_9_2_X_2017-10-27-1100

Cheers,
David


On 27 Oct 2017, at 22:37, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:

Broken 2017h workflows in the ib. Not clear if this is the reason but seems most likely

Cheers,
David


On 27 Oct 2017, at 21:56, Arun Kumar <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> what is the reason to revert this?

**Comment by arunhep** [comment]
@davidlange6 
this PR https://github.com/cms-sw/cmssw/pull/21056 should fix the issue.
Please close this revert PR
Thanks.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by arunhep** [comment]
@davidlange6 this PR should be closed. And this is not mine but your PR ;-)

**Comment by kpedro88** [comment]
@davidlange6 should this be closed?

**Comment by lpernie** [comment]
yes

**Comment by arunhep** [comment]
-1
to remove it from the pending list

**Pull request closed without merging**
