### PR TITLE
Run3-hcx224 Convert one of the HE algorithms to DD4Hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Move one of the DDD algorithms (used for HE) to DD4Hep world

#### PR validation:

Tested with a cfg file in Geometry/HcalAlgo/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

the provided test cfg run smoothly

**Pull request merged**
