### PR TITLE
Run3-gex68 Check in more detail the contents of the geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Check in more detail the contents of the geometry

#### PR validation:

Use tests in SimG4Core/PrintGeomInfo/test to compare DDD vs DD4Hep for run3 scenario

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
