### PR TITLE
Run2-gex131 Try to factorize a ddalgorithm used for forward pixel which can help in adopting legacy scenario to dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to modify a ddalgorithm used for forward pixel which can help in adopting legacy scenario to dd4hep. Creation of a few rotation matrices was necessary in a separate step so that dd4hep workflow can work and this was the limitation why DDPixfwdBlade was not modified for dd4hep application. This change followed by the adoptation of this code for dd4hep will allow run1 and some of the run2 scenarios to be defined for dd4hep.

#### PR validation:

Tested by dumping the old and new scenario of forward pixel 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , let us discuss this PR today.

**Comment by bsunanda** [comment]
@cmsbuild Please Test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
> @bsunanda , let us discuss this PR today.

@bsunanda @civanch maybe I know a different definition of "factorize", but at a first glance I would say that if you add 1781 lines of code and remove only 11 you are not "factorizing" out anything. You are talking about a discussion: do you have a link to some slide or minutes of that discussion, so that we can have an idea of what are you actually doing here? Or maybe, could you just add a few more informative lines to the PR description?

Moreover, mostly out of curiosity: why are you moving your debug messages from LogDebug to LogVerbatim?

**Comment by bsunanda** [comment]
@perrrotta I take out only one activity of the earlier code which need to be done prior to analyze pixelfwdnipple.xml so that it can be adopted to dd4hep. The original code of DDPixfwdBlades could not be adopted for dd4hep because of this. Factorization may be a wrong word. I have not looked into compacticiation of the code at that time. The use of LogVerbatim helps me to get an easy access to log file without recompiling the code. I tried to explain this in the description. Please le me know a suitable title and I shall change that too.

**Comment by bsunanda** [comment]
In the SIM meeting all the discussion happened orally - I ddi not prepare slides for that. The slides were for 2017, 2018 scenarios. Even the final conclusions for those were not in the original slides. Let me modify the slides to introduce them.

**Pull request merged**
