### PR TITLE
Dt extended data format

### PR DESCRIPTION
**Pull request by NTrevisani**
#### PR description:

The main target of this pull request is to include additional information in the DT DataFormat for phase2, both for phi and theta. The user can decide whether to save the additional information or not. In the latter case, no changes are expected.
The extended DataFormat inherits from the original one and includes:
- local position and slope;
- global coordinates obtained using CMSSW (instead of FW-like LUTs)
- hit wire information (ID, TDC, and laterality).

The PR also updates some aspects of the pseudo-bayes grouping algorithm for trigger primitives generation.

#### PR validation:

Run the DT phase2 emulator with new DataFormat using the cfg file at: L1Trigger/DTTriggerPhase2/test/test_primitivesPhase2Prod_DEBUG_Grouping_cfg.py, obtaining the same results as before.

Also produce DT ntuples and checked that efficiencies and resolutions are left unchanged.

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by NTrevisani** [comment]
Dear @cecilecaillol,

I see the only test that did not pass (10006.0), failed due to a DAS Error and the corresponding workflow should not be affected by this PR. I also tried running the corresponding runTheMatrix workflow in local and -  modulo fixing the input files names by hand - I saw no problems. May I ask you to trigger the test again?

Kind regards,
Nicolò

**Comment by srimanob** [comment]
Please abort

**Comment by srimanob** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
@NTrevisani 
Do I understand correctly that the additional information of the DT DataFormat will be used mostly by experts, no need to have a switch on/off for most/all relvals/production.

**Comment by NTrevisani** [comment]
@srimanob 
Exactly, the usual Data Format should be enough in those cases.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
@NTrevisani  Please check the code rule warning:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-05ce32/15874/codeRules/cmsCodeRule1.txt
and
https://github.com/cms-sw/cms-sw.github.io/issues/94
" SF.7: Don’t write using namespace at global scope in a header file"

**Comment by srimanob** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
