### PR TITLE
Introduce Run 3 cosmics workflow using express GT

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR adds a Run 3 cosmics workflow identical to that in PR #27341 but using the express rather than the prompt global tag. This is done to ensure that the express GT is properly maintained between MWGRs.

In addition, the prompt GT has been updated to the GT used in the second 2020 MWGR.

Attn: @boudoul @mmusich 

#### PR validation:

`runTheMatrix.py -l 138.1,138.2 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and I do not foresee a use case for a backport.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 138.1,138.2

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
