### PR TITLE
[12_3_X] Update DQM beam clients playback machine type check

### PR DESCRIPTION
**Pull request by pmandrik**
#### PR description:

update DQM beam* clients to use available config data to check if machine is playback or production instead of the path to the CMSSW folder (which is unsafe).

#### PR validation:

Tested at P5 DQM playback

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38262

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by pmandrik** [comment]
Unit test crash line:
https://github.com/cms-sw/cmssw/blob/02a77eae19c80ae8bf5126b91df0cb875c6f4051/DQM/Integration/python/config/unittestinputsource_cfi.py#L107
probably, no events returned from query to DAS because of net problem:
`Error in <TNetXNGFile::Open>: [ERROR] Operation expired`
not related to the PR

**Comment by pmandrik** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
