### PR TITLE
make TrackExtra fully persistent because of FastSimPU

### PR DESCRIPTION
**Pull request by VinInn**
Fix an issue observed after #17098 was merged
To fix FastSim wf with PU (such as 25400) a new library need to be generated

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
so nothing we run will test this... will try to restart IBs with this change included

**Comment by davidlange6** [comment]
@slava77 - please comment if you have concerns (I guess knowing the RECO size change is the one concern i can think of)

**Comment by slava77** [comment]
On 2/1/17 11:31 AM, David Lange wrote:
> @slava77 <https://github.com/slava77> - please comment if you have
> concerns (I guess knowing the RECO size change is the one concern i can
> think of)

just the event size

**Comment by VinInn** [comment]
we can also remove the assert: after all these tracks were not accompanied by neither Trajectories  nor by filled rechits, so they cannot be used to do any real reconstruction nor any analysis (DQM etc) that was relying on Trajectory or hits...

**Comment by slava77** [comment]
On 2/1/17 11:44 AM, Vincenzo Innocente wrote:
> we can also remove the assert: after all these tracks were not
> accompanied by neither Trajectories nor by filled rechits, so they
> cannot be used to do any real reconstruction nor any analysis (DQM etc)
> that was relying on Trajectory or hits...
> 

even better.
if garbage input can be detected/removed at the source even better

**Comment by davidlange6** [comment]
yes, definitely.

**Comment by VinInn** [comment]
So, what is the decision? revert this and remove the assert and propagate "garbage" as FastSim tracks are garbage anyhow?

**Comment by slava77** [comment]
The TrackExtras size goes up by a factor of ~1.8 in my 2016E JetHT test (136.761).
This is a net increase of about 10% in RECO file size.
we better fix this [or drop TrackExtra from data RECO tier].

@ssekmen

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17238	68c1696
- as described
- jenkins tests passed
- there is a ~10% increase in RECO side which better be reduced soon https://github.com/cms-sw/cmssw/issues/17372

**Pull request merged**
