### PR TITLE
using HLT:@relval2016 for phase1 relvals (retry)

### PR DESCRIPTION
**Pull request by mmusich**
@silviodonato @fabozzi
retrying here PR #16384, taking @makortel's https://github.com/cms-sw/cmssw/pull/16384#issuecomment-256996737, which unfortunately is not enough.
Namely CMSSW_8_1_X_2016-10-28-1100 +https://github.com/cms-sw/cmssw/commit/32d46dc06c200233eea89b911434c03dffc70b46 + https://github.com/cms-sw/cmssw/commit/505028c0ee905da1a3e03c1a21614e4ede8cec86
still results in 

```
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/5807ca27a61cace36698b4e41c6310d3/opt/cmssw/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-
10-28-1100/src/Geometry/HcalTowerAlgo/src/HcalGeometry.cc:127: virtual DetId HcalGeometry::getClosestCell(const GlobalPoint&) const: Assertion `bestId != HcalDetId()' failed.

```

removing HcalCalHBHEMuonFilter from the sequence (i.e. https://github.com/cms-sw/cmssw/commit/35e0543597dade2d7f88e4785f0418ee7d5e18cb) seems to work in local tests. @bsunanda can you have a look?

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by bsunanda** [comment]
Hi Marco

Could you tell me which test fails the filter?

Sunanda
________________________________

**Comment by mmusich** [comment]
Hi @bsunanda, you can reproduce it merging #16384 onto the last IB and running wf 10021. It fails step4 (AlCa)

**Comment by mmusich** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
Hi @mmusich - please add a key 

https://github.com/cms-AlCaDB/cmssw/blob/35e0543597dade2d7f88e4785f0418ee7d5e18cb/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L62

(and in the corresponding 2023 workflows) instead of an if statement for the hlt menu

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
Hello @davidlange6 is https://github.com/cms-AlCaDB/cmssw/commit/822f6af030dab9d90db1214824a23d88484a7c8d OK w.r.t your https://github.com/cms-sw/cmssw/pull/16386#issuecomment-257262763 ? Thanks

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
thanks

**Comment by davidlange6** [comment]
@smuzaffar - fwiw, we missed a +1 from @fabozzi here - was around the same time as other issues we talked about..

**Comment by smuzaffar** [comment]
yes @davidlange6 , look like this PR was also not visible at that time.
I have run cms-bot to process last 12hours PR now and looks like it did not miss any thing else. So only things it had missed were PR 16420, 16423 and +1 of @fabozzi for this PR. Looks like something to do with @fabozzi  user itself as three of these belong to him :-)

**Comment by fabozzi** [comment]
HI, this morning I had issue with git, saying that my profile was hidded from the public because their spam-detecting robots... not sure if that was the cause, anyway 
it should be solved now

**Pull request merged**
