### PR TITLE
bsunanda:Run2-hcx96 Add scenario for 2017 when HF is upgraded and not HE

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 since this still has not been merged, I'm just going to absorb it into my forthcoming PR to use Phase0 HE in the 2017 config

but in the future let's not leave these things to sit around for a month

**Comment by kpedro88** [comment]
hold

**Pull request closed without merging**
