### PR TITLE
Revert "adding David Lange's comments built on rebase of ValidationDo…

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#9765

### CODE REVIEW

**Comment by inugent** [comment]
To Whom it may concern,
  My apologies, I am no longer on CMS. Therefore I am not in a position
were I can sign off or reject pull request.  Best regards,
Ian

**Comment by bendavid** [comment]
Hi @davidlange6, this is a bit unfortunate, since it reverts a major set of critical fixes to the generator validation (critical in the sense that without it many of the validation plots are not usable)

Couldn't we try to have a more minimal fix?
(Since Ian has left CMS we'll have to do the revert revert a bit blindly to start and then try to fix the offending part starting from there...)

**Comment by bendavid** [comment]
Also do we understand why it look a month for the problem to be spotted after this was merged?

**Comment by davidlange6** [comment]
@bendavid - you are really complaining about a PR that took several months to get a generators +1?

I'm sure a more minimal solution is possible just by going back to the original PR, finding the fix for the infinite loop and pushing it in. But thats for the experts. As for why so long - we never managed to reliably run some of the generator workflows given the source downloading they do - so when that changed to an infinite loop, I guess it wasn't easily noticable.

**Comment by bendavid** [comment]
Indeed, the main problem is that the expert has left in the meantime...

(And sorry what are you referring to by "source downloading"?)

**Comment by davidlange6** [comment]
> On Sep 2, 2015, at 7:01 PM, Josh Bendavid <notifications@github.com> wrote:
> 
> Indeed, the main problem is that the expert has left in the meantime...
> 
> (And sorry what are you referring to by "source downloading”?)

i haven’t managed to investigate - but I repeatedly found that running 8 gen workflows on a machine seems to be a real killer for the disk of that machine…(maybe not with the infinite loop though:) )

**Pull request merged**
