### PR TITLE
Getting the L1T O2O ready for data taking of 2017

### PR DESCRIPTION
**Pull request by kkotov**
1) Parser for the new XML format of Prescales-Masks has been implemented and tested at p5
2) Removing leading and railing whitespaces from the column names
3) Making CaloParams online producer fault-safe against a problem of inconsistency in some of the calo XMLs.
(in place of closed https://github.com/cms-sw/cmssw/pull/18492)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic , could you trigger the tests again?

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic are we ready to sign off this most crucial PR yet?

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@kkotov  We need 91X backport of this.

**Comment by rekovic** [comment]
@kkotov The online XML formats changed, so need this PR to be able to parse them. 
Without this PR in, CMSSW_910 O2O will crash online.

**Comment by davidlange6** [comment]
+1
nice, a pr essential for data taking pending for 2 weeks...

**Pull request merged**
