### PR TITLE
[GEOMETRY-UPGRADE] clang-tidy Performance inefficient vector operation suggestion applied

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar thanks for the fix, as far as I can see the errors have nothing to do with the PR itself

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
