### PR TITLE
Setting up properly peak and deco (strip tracker config) 2017 cosmic WFs 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings, 
I believe the title is explicite enough for a good description .

Please note before being merged , this PR needs to be updated with a deco GT 
(see line 45 in AutoCond)

### CODE REVIEW

**Comment by franzoni** [comment]
hello @boudoul 
as agreed verbally, here https://github.com/cms-sw/cmssw/pull/17886 the ingredients from AlCa/Db you wanted for this PR

**Comment by boudoul** [comment]
now that #17905 has been merged, this PR is now in synch with it, can someone trigger the test ? (@fabozzi?)  thanks

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @boudoul - just to clarify - no reco changes (even the gt) are needed?

**Comment by boudoul** [comment]
Hi @davidlange6 , your comment made me realize that indeed the digi and reco step where not consistent - Thanks for the catch -  Fixed in my last commit

**Comment by davidlange6** [comment]
please test

**Pull request merged**
