### PR TITLE
Fix maybe-uninitialized warning in MeasurementTrackerImpl::addPhase2Det

### LINKED ISSUE #42625: [CPP20] maybe-uninitialized warning in MeasurementTrackerImpl::addPhase2Det
```
In member function '__ct ',
    inlined from 'construct_at' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_construct.h:97:14,
    inlined from 'construct' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/alloc_traits.h:518:21,
    inlined from '_M_realloc_insert' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/vector.tcc:462:28,
    inlined from 'emplace_back' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/vector.tcc:123:21,
    inlined from 'push_back' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1294:21,
    inlined from 'addPhase2Det' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/bde6290197b40a7abece5e0ce6f36880/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-21-1100/src/RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc:286:28,
    inlined from 'addDets' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/bde6290197b40a7abece5e0ce6f36880/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-21-1100/src/RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc:236:23:
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/bde6290197b40a7abece5e0ce6f36880/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-21-1100/src/RecoTracker/MeasurementDet/plugins/TkPhase2OTMeasurementDet.h:16:18: warning: 'MEM <unsigned long> [(unsigned int *)&D.14013 + 48B]' may be used uninitialized [-Wmaybe-uninitialized]
    16 | class dso_hidden TkPhase2OTMeasurementDet final : public MeasurementDet {
      |                  ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/bde6290197b40a7abece5e0ce6f36880/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-21-1100/src/RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc: In member function 'addDets':
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/bde6290197b40a7abece5e0ce6f36880/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_CPP20_X_2023-08-21-1100/src/RecoTracker/MeasurementDet/plugins/MeasurementTrackerImpl.cc:286:80: note: '<anonymous>' declared here
  286 |     thePhase2Dets.push_back(TkPhase2OTMeasurementDet(gd, thePhase2DetConditions));
      |                                                                                ^
Leaving library rule at src/RecoTracker/MeasurementDet/plugins
```

Full log: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_CPP20_X_2023-08-21-1100/RecoTracker/MeasurementDet

### PR DESCRIPTION
**Pull request by iarspider**
Closes #42625 

#### PR description:

Fixes maybe-uninitialized warning in MeasurementTrackerImpl::addPhase2Det  as suggested by @makortel in https://github.com/cms-sw/cmssw/issues/42625#issuecomment-1688340530 . 

#### PR validation:

Local build

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_13_3_CPP20_X

**Comment by iarspider** [comment]
please test for CMSSW_13_3_CPP20_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_13_3_CPP20_X

**Comment by iarspider** [comment]
For CPP20, [the failure](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9007a4/34931/unitTests/src/DataFormats/SiStripCluster/test/TestSiStripApproximateClusterCollection/testing.log) also happens [in IBs](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9007a4/34931/unitTests/src/DataFormats/SiStripCluster/test/TestSiStripApproximateClusterCollection/testing.log) and doesn't seem to be related to this PR.

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
