### PR TITLE
Phase2-hgx297E Update the test configuration in Geometry/HGCalGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the test configuration in Geometry/HGCalGeometry

#### PR validation:

Use test workflows in Geometry/HGCalGeometry/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to update the HGCAL geometry test configuration. No change is expected from the PR test.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
