### PR TITLE
[DD4hep] Filtered View is not a Shape

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Shape type check is performed on a FilteredView current shape rather then on a View itself

Replaces https://github.com/cms-sw/cmssw/pull/31603

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by namapane** [comment]
@ianna, if I understand correctly this also fixes the need of [this hack](https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054) as discussed in https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054, right? 
If so it would be a good idea to update that line as well in this PR (otherwise I can make another PR later on, but for just 1 line... )

**Comment by ianna** [comment]
> @ianna, if I understand correctly this also fixes the need of [this hack](https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054) as discussed in [#29781 (comment)](https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054), right?
> If so it would be a good idea to update that line as well in this PR (otherwise I can make another PR later on, but for just 1 line... )

@namapane - thanks! I'd need to test it. One line PR would be fine as well :-)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
