### PR TITLE
Backport of new files for PPS geometry

### PR DESCRIPTION
**Pull request by diemort**
#### PR description:

This is a complementary PR to previous backport #35391 related to new files reported in #35399.

#### PR validation:

Basic PR workflow tests passed. The same tests done in #35391 were done, just the rebase to the IB release missed a few files that should be merged.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

#35391 related to #35399

FYI @fabferro @jan-kaspar

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by perrotta** [comment]
backport of #35399

**Comment by perrotta** [comment]
+1
- Backporting the same xml geometry configs merged in the master

**Pull request merged**
