### PR TITLE
SiStripMonitorCluster & SiStripMonitorDigi - Fix the FED digi/cluster plots ranges and error [Backport for 10_1_X of #23307]

### PR DESCRIPTION
**Pull request by hbecerri**
Fix ranges in the x-axis and errors for NumberOfClustersinFED_v_FEDID and NumberOfDigisinFED_v_FEDID

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This needs to be rebased so it only includes the commits actually needed.

**Comment by perrotta** [comment]
-1
rebase needed

**Comment by kpedro88** [comment]
-1
please follow http://cms-sw.github.io/tutorial-resolve-conflicts.html#backporting-a-pr to backport your PR correctly

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by arunhep** [comment]
-1

**Comment by ianna** [comment]
-1

**Comment by boudoul** [comment]
please @hbecerri , close this PR   !  
  [the backport is actually here #23329 ]

**Pull request closed without merging**
