### PR TITLE
More All-In-One tool improvements

### PR DESCRIPTION
**Pull request by hroskes**
The primary addition here is "preexisting" validations, which make it possible to configure the All In One tool to include validations that were already run into plots, without running them again.

This PR is independent of the upgrade to 75X (it's mostly in the python scripts) and all of the fixes that need to go with validations using data in the most recent releases.  I hope that this will be merged relatively soon so that this PR and fixes for 75X data don't interfere with each other.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@hroskes once merged do you plan it for 7.4.X too?

**Comment by hroskes** [comment]
@mmusich 
Yes, I haven't been very responsible about backports recently but I want to change that.  At this point how far back should I go with backports beyond 74?

**Comment by mmusich** [comment]
@hroskes since both MC and data are now processed in 74X there is no urgency to backport improvements upstream than that.

**Comment by hroskes** [comment]
@mmusich Thanks, great!  That makes it easier for me.

**Comment by hroskes** [comment]
@cmsbuild I'm sorry

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
