### PR TITLE
Phase2-hgx347 Make hits for Calibration cells in the coming HGCal version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make hits for Calibration cells in the coming HGCal version

#### PR validation:

Tested using a cfg file in SimG4CMS/Calo/test/python for existing and new scenario of Phase2

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , it seems that having 2 constructors for CaloSD, SensitiveDetector, SensitiveCaloDetector is the overhead. May be add an extra parameter to the end const std::string& newdet="" ?

Having more than 1 nearly the same constructor never make code simpler for understanding and potentially is more error prong.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
differences only in 24834.911, in other WFs and in previous test there were full regression. May be we should resubmit the test?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@rappoccio,  @antoniovilela Please integrate this PR

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela This will help the next step for the new HGCal geometry version

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
