### PR TITLE
migrate away from commands in das utility

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

The python module 'commands' is deprecated in python2.7 and removed from python3. Replace it

#### PR validation:

checked unit tests using das utility work ok

### CODE REVIEW

**Comment by davidlange6** [comment]
i think my test doesn't actually test my change... investigating more

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
