### PR TITLE
Add SimBeamSpotObject record to Run-1/2/3 MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
With the agreement of the @cms-sw/alca-l2 conveners, I'm adding the `SimBeamSpotObject` tags to all Run-1/2/3 MC GTs, following (my own) request in [this CMSTalk post](https://cms-talk.web.cern.ch/t/mc-new-simbeamspotobjectsrcd-tags-for-run1-2-3-mc-gts/31292).
The CMS talk post contains all the details about the tags and the different scenarios used.

*GT differences:*
- `run1_design`                    : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_design_v2/131X_mcRun1_design_v3
- `run1_mc`                        : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_realistic_v2/131X_mcRun1_realistic_v3
- `run1_mc_hi`                     : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_HeavyIon_v2/131X_mcRun1_HeavyIon_v3
- `run2_mc_50ns`                   : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_startup_v2/131X_mcRun2_startup_v3
- `run2_mc_l1stage1`               : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_l1stage1_v2/131X_mcRun2_asymptotic_l1stage1_v3
- `run2_design`                    : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_design_v2/131X_mcRun2_design_v3
- `run2_mc_pre_vfp`                : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_preVFP_v2/131X_mcRun2_asymptotic_preVFP_v3
- `run2_mc`                        : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_v2/131X_mcRun2_asymptotic_v3
- `run2_mc_cosmics`                : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2cosmics_asymptotic_deco_v2/131X_mcRun2cosmics_asymptotic_deco_v3
- `run2_mc_hi`                     : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_HeavyIon_v2/131X_mcRun2_HeavyIon_v3
- `run2_mc_pa`                     : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_pA_v2/131X_mcRun2_pA_v3
- `phase1_2017_design`             : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017_design_v2/131X_mc2017_design_v3
- `phase1_2017_realistic`          : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017_realistic_v2/131X_mc2017_realistic_v3
- `phase1_2017_cosmics`            : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017cosmics_realistic_deco_v2/131X_mc2017cosmics_realistic_deco_v3
- `phase1_2017_cosmics_peak`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017cosmics_realistic_peak_v2/131X_mc2017cosmics_realistic_peak_v3
- `phase1_2018_design`             : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_design_v2/131X_upgrade2018_design_v3
- `phase1_2018_realistic`          : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_v2/131X_upgrade2018_realistic_v3
- `phase1_2018_realistic_rd`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_RD_v2/131X_upgrade2018_realistic_RD_v3
- `phase1_2018_realistic_hi`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_HI_v2/131X_upgrade2018_realistic_HI_v3
- `phase1_2018_realistic_HEfail`   : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_HEfail_v3/131X_upgrade2018_realistic_HEfail_v4
- `phase1_2018_cosmics`            : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018cosmics_realistic_deco_v2/131X_upgrade2018cosmics_realistic_deco_v3
- `phase1_2018_cosmics_peak`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018cosmics_realistic_peak_v3/131X_upgrade2018cosmics_realistic_peak_v4
- `phase1_2022_design`             : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_design_v2/133X_mcRun3_2022_design_v3
- `phase1_2022_realistic`          : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_v2/133X_mcRun3_2022_realistic_v3
- `phase1_2022_realistic_postEE`   : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_postEE_v3/133X_mcRun3_2022_realistic_postEE_v4
- `phase1_2022_cosmics`            : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022cosmics_realistic_deco_v2/133X_mcRun3_2022cosmics_realistic_deco_v3
- `phase1_2022_cosmics_design`     : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022cosmics_design_deco_v2/133X_mcRun3_2022cosmics_design_deco_v3   
- `phase1_2022_realistic_hi`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_HI_v2/133X_mcRun3_2022_realistic_HI_v3         
- `phase1_2023_design`             : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_design_v2/133X_mcRun3_2023_design_v3               
- `phase1_2023_realistic`          : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_v2/133X_mcRun3_2023_realistic_v3            
- `phase1_2023_realistic_postBPix` : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_postBPix_v2/133X_mcRun3_2023_realistic_postBPix_v3   
- `phase1_2023_cosmics`            : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023cosmics_realistic_deco_v2/133X_mcRun3_2023cosmics_realistic_deco_v3
- `phase1_2023_cosmics_design`     : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023cosmics_design_deco_v2/133X_mcRun3_2023cosmics_design_deco_v3   
- `phase1_2023_realistic_hi`       : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_HI_v6/133X_mcRun3_2023_realistic_HI_v7
- `phase1_2024_realistic`          : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2024_realistic_v4/133X_mcRun3_2024_realistic_v5

#### PR validation:
Ran successfully the limited matrix workflows.

#### Backport:
Not a backport, no backport needed.

### CODE REVIEW

**Comment by francescobrivio** [comment]
Differences in `12434.7` are known from https://github.com/cms-sw/cmssw/issues/39803

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by perrotta** [comment]
Thank you @francescobrivio for having provided the SimBeamSpotObject tags to all Run-1/2/3 MC GTs,

For the sake of documentations, these are the tags for the SimBeamSpotObjectsRcd updated by this PR in the different GTs:
```
run1_design : SimBeamSpot_Realistic8TeVCollisionVtxSmearingParameters_v2_mc
run1_mc :     SimBeamSpot_Realistic8TeVCollisionVtxSmearingParameters_v2_mc
run1_mc_hi :  SimBeamSpot_RealisticHIpPb2013CollisionVtxSmearingParameters_v2_mc
run2_mc_50ns : SimBeamSpot_Realistic50ns13TeVCollisionVtxSmearingParameters_v2_mc
run2_mc_l1stage1 : SimBeamSpot_Realistic50ns13TeVCollisionVtxSmearingParameters_v2_mc
run2_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
run2_mc_pre_vfp : SimBeamSpot_Realistic25ns13TeV2016CollisionVtxSmearingParameters_v2_mc
run2_mc :         SimBeamSpot_Realistic25ns13TeV2016CollisionVtxSmearingParameters_v2_mc
run2_mc_cosmics : SimBeamSpot_Realistic25ns13TeV2016CollisionVtxSmearingParameters_v2_mc
run2_mc_hi : SimBeamSpot_RealisticHICollisionFixZ2015VtxSmearingParameters_v2_mc
run2_mc_pa : SimBeamSpot_Realistic8TeVPACollision2016VtxSmearingParameters_v2_mc
phase1_2017_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
phase1_2017_realistic : SimBeamSpot_Realistic25ns13TeVEarly2017CollisionVtxSmearingParameters_v2_mc
phase1_2017_cosmics : SimBeamSpot_Realistic25ns13TeVEarly2017CollisionVtxSmearingParameters_v2_mc
phase1_2017_cosmics_peak : SimBeamSpot_Realistic25ns13TeVEarly2017CollisionVtxSmearingParameters_v2_mc
phase1_2018_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
phase1_2018_realistic : SimBeamSpot_Realistic25ns13TeVEarly2018CollisionVtxSmearingParameters_v2_mc
phase1_2018_realistic_rd : SimBeamSpot_Realistic25ns13TeVEarly2018CollisionVtxSmearingParameters_v2_mc
phase1_2018_realistic_hi : SimBeamSpot_RealisticPbPbCollision2018VtxSmearingParameters_v2_mc
phase1_2018_realistic_HEfail : SimBeamSpot_Realistic25ns13TeVEarly2018CollisionVtxSmearingParameters_v2_mc
phase1_2018_cosmics : SimBeamSpot_Realistic25ns13TeVEarly2018CollisionVtxSmearingParameters_v2_mc
phase1_2018_cosmics_peak : SimBeamSpot_Realistic25ns13TeVEarly2018CollisionVtxSmearingParameters_v2_mc
phase1_2022_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc 
phase1_2022_realistic : SimBeamSpot_Realistic25ns13p6TeVEOY2022CollisionVtxSmearingParameters_v2_mc
phase1_2022_realistic_postEE : SimBeamSpot_Realistic25ns13p6TeVEOY2022CollisionVtxSmearingParameters_v2_mc
phase1_2022_cosmics : SimBeamSpot_Realistic25ns13p6TeVEOY2022CollisionVtxSmearingParameters_v2_mc
phase1_2022_cosmics_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
phase1_2022_realistic_hi : SimBeamSpot_Realistic2022PbPbCollisionVtxSmearingParameters_v2_mc
phase1_2023_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
phase1_2023_realistic : SimBeamSpot_Realistic25ns13p6TeVEarly2023CollisionVtxSmearingParameters_v2_mc
phase1_2023_realistic_postBPix : SimBeamSpot_Realistic25ns13p6TeVEarly2023CollisionVtxSmearingParameters_v2_mc
phase1_2023_cosmics : SimBeamSpot_Realistic25ns13p6TeVEarly2023CollisionVtxSmearingParameters_v2_mc
phase1_2023_cosmics_design : SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc
phase1_2023_realistic_hi : SimBeamSpot_Realistic2022PbPbCollisionVtxSmearingParameters_v2_mc
phase1_2024_realistic : SimBeamSpot_Realistic25ns13p6TeVEarly2023CollisionVtxSmearingParameters_v2_mc
```

They look mostly all reasonable to me, but I have a doubt on the very first one in this list: all other "design" GTs use the `SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc` tag, while "run1_design" stick on a "realistic" SimBeamSpot tag.

Could you please check?

**Comment by mmusich** [comment]
> They look mostly all reasonable to me, but I have a doubt on the very first one in this list: all other "design" GTs use the `SimBeamSpot_GaussVtxSigmaZ4cmSmearingParameters_v2_mc` tag, while "run1_design" stick on a "realistic" SimBeamSpot tag.
> Could you please check?

Allow me to chime in, as I was suggesting that [here](https://github.com/cms-AlCaDB/AlCaTools/issues/86#issuecomment-1694356173). The reason is rather mundane. There is no python configuration for an ideal Run-1 beamspot in the file https://github.com/cms-sw/cmssw/blob/master/IOMC/EventVertexGenerators/python/VtxSmearedParameters_cfi.py. 

In any case as far as I can see [from DXR](https://cmssdt.cern.ch/dxr/CMSSW/search?q=run1_design&case=true) there is no client of the autoCond key `run1_design` at all, so it's somehow a moot point (actually you might even decide to remove the key from `autoCond`.

**Comment by francescobrivio** [comment]
Ciao Andrea, thanks for checking!

This choice was made based on how the Run 1 MC matrix relvals are set up currently, i.e. using conditions `auto:run1_mc` and beamspot `Realistic8TeVCollision`, and we want to maintain the same configuration.
For example if you take a look at some of them (e.g. `5.1`, `9.0`, `25.0`,...) you'll see that Step 1 is configured as:
- 5.1: 
```cmsDriver.py TTbar_8TeV_TuneCUETP8M1_cfi  --relval 100000,1000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,VALIDATION:@standardValidation,DQM:@standardDQMFS -n 10 --conditions auto:run1_mc --beamspot Realistic8TeVCollision --datatier GEN-SIM-DIGI-RECO,DQMIO --eventcontent FEVTDEBUGHLT,DQM --fast```
- 9.0:
```cmsDriver.py H200ChargedTaus_Tauola_8TeV_cfi  --relval 9000,100 -s GEN,SIM -n 10 --conditions auto:run1_mc --beamspot Realistic8TeVCollision --datatier GEN-SIM --eventcontent RAWSIM```
- 25.0:
```cmsDriver.py TTbar_8TeV_TuneCUETP8M1_cfi  --relval 9000,100 -s GEN,SIM -n 10 --conditions auto:run1_mc --beamspot Realistic8TeVCollision --datatier GEN-SIM --eventcontent RAWSIM```
- ...

**Comment by francescobrivio** [comment]
@cms-sw/alca-l2 btw this PR has been moved by default to 14_0_X, do you want me to open a 13_3_X backport as well? 
i.e. is there a planned MC production in 13_3_X that might benefit from this development?

**Comment by perrotta** [comment]
+alca
- Thank you @francescobrivio and @mmusich for the clarifications

**Comment by perrotta** [comment]
@rappoccio @antoniovilela can this PR get merged?
There are other GT updates (e.g. #43226) which are waiting for this one being included in the IB

**Comment by francescobrivio** [comment]
A kind ping @cms-sw/orp-l2

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
