### PR TITLE
Cleanup G4 User actions

### PR DESCRIPTION
**Pull request by civanch**
A general clean-up of Geant4 User action classes:
  1) trying to reduce number of instructions (number of order of "if") in run time;
  2) few simple methods inlined;
  3) removed unnecessary headers;
  4) use some c++11 keywords;
  5) by default, kill primary neutrinos;
  6) removed code implementing Russian roulette for protons (not useful).
Results should be not affected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
We started seeing these crashes:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-09-08-0900/pyRelValMatrixLogs/run/25210.0_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step1_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-09-08-0900/pyRelValMatrixLogs/run/1360.0_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15+RECOUP15+HARVESTUP15/step1_TTbar012Jets_NLO_Mad_py8_Evt_13+TTbar012Jets_NLO_Mad_py8_Evt_13+DIGIUP15+RECOUP15+HARVESTUP15.log

the first IB containing this pull request.

**Comment by Dr15Jones** [comment]
The same crashes happen in CMSSW_8_1_NONTHREADED_X IBs.

**Comment by davidlange6** [comment]
ok - reverting it then. @civanch can have a look when not busy with the g4 collaboration meeting

**Pull request merged**
