### PR TITLE
L1T Muon Offline DQM - Resolution plots & bug fixes - 92x

### PR DESCRIPTION
**Pull request by astakia**
backport of #20649 

-fixing in tag muons counting
-adding of resolution plots

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic could you launch the tests for this please?

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@dmitrijus ping

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @davidlange6 I think this was requested in this weeks orp meeting and is now fully signed. Can it be merged please?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
