### PR TITLE
Improve calo particle debugging

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Improve `CaloParticle` debugging code by adding barcode information.
Remove useless eta-sorting and use the original one.

#### PR validation:

Tested locally by running the corresponding Python snippet in the `test` directory.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1


Errors are spurious.

**Pull request merged**
