### PR TITLE
Fix HLT path selection and BaselineValidator module addition for HI (same as #2582 but for master)

### PR DESCRIPTION
**Pull request by arossi83**
SiStrip Online DQM client setup for HI. All the changes affect only online (the SiStripBaselineValidator plugin is used only online). 

Same as #25082 but for master

### CODE REVIEW

**Comment by arossi83** [comment]
Sorry, wrong reference number on title!

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
