### PR TITLE
HLT menu development for `12_3_X`

### PR DESCRIPTION
**Pull request by missirol**
backport of #37754

#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

Includes the integration of the following JIRA tickets.

  - Part of [CMSHLT-2261](https://its.cern.ch/jira/browse/CMSHLT-2261): [BPH] Update of low-mass dimuon triggers for Run 3.
  - [CMSHLT-2286](https://its.cern.ch/jira/browse/CMSHLT-2286): [EGM] Removal of "caloTowers" from E/Gamma reconstruction at HLT.
  - [CMSHLT-2293](https://its.cern.ch/jira/browse/CMSHLT-2293): [EGM] Update for Run-3 E/Gamma supercluster energy regression.

The configurations were created with [`V03-03-00` of ConfDB](https://github.com/cms-sw/hlt-confdb/releases/tag/V03-03-00), which introduces support for `ProcessAcceleratorCUDA`.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37754

Development of HLT menus for Run-3 startup.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The large reduction of DQM outputs in `HLT/HLTEgammaValidation` is related to the changes in this PR to E/Gamma triggers. It requires a follow-up from EGM and/or DQM experts. More details can be found in https://github.com/cms-sw/cmssw/pull/37754#issuecomment-1114186404.

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are in line with changes to the HLT GRun menu.
 - https://github.com/cms-sw/cmssw/pull/37755#issuecomment-1114186541 requires a follow-up related to the HLT-EGM Validation sequences.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
As per [ORP's suggestion](https://github.com/cms-sw/cmssw/pull/37754#issuecomment-1114194257), the DQM module was updated in this PR already. Based on the outputs of the PR tests, this worked as expected (no unexpected differences).

@cms-sw/dqm-l2 , this PR now requires your signature.

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are in line with changes to the HLT GRun menu.
 - includes a related update to a DQM/Validation plugin.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping

**Pull request merged**
