### PR TITLE
convert L1TkMuon to stream producer [11_1_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #31098

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@slava77 did the matrix map changes get applied to 11_1_X? I think we want to keep the OldDigi test here

**Comment by kpedro88** [comment]
+upgrade

**Comment by srimanob** [comment]
Hi @kpedro88 
As current production is ongoing without this PR, do you see any issue?

**Comment by kpedro88** [comment]
If production jobs aren't encountering the issue #31097, then this PR doesn't need to be merged. We can leave it here in case the issue does arise.

**Comment by rekovic** [comment]
+1

in any case

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
> If production jobs aren't encountering the issue #31097, then this PR doesn't need to be merged. We can leave it here in case the issue does arise.

I'm converting this PR as a draft just to remove this from the ORP spreadsheet. Of course feel free to open it back if needed.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
