### PR TITLE
[12_3_X] Add new GEM electronics map to all GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38090
Diffs for GTs that are different wrt to 38090

**phase1_2018_cosmics_peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018cosmics_realistic_peak_v1/123X_upgrade2018cosmics_realistic_peak_v2

**phase1_2021_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2021_design_v14/123X_mcRun3_2021_design_v15

**phase1_2021_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2021_realistic_v14/123X_mcRun3_2021_realistic_v15

**phase1_2021_cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2021cosmics_realistic_deco_v15/123X_mcRun3_2021cosmics_realistic_deco_v16

**phase1_2021_cosmics_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2021cosmics_design_deco_v1/123X_mcRun3_2021cosmics_design_deco_v2

**phase1_2021_realistic_hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2021_realistic_HI_v14/123X_mcRun3_2021_realistic_HI_v15

**phase1_2023_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2023_realistic_v14/123X_mcRun3_2023_realistic_v15

**phase1_2024_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun3_2024_realistic_v15/123X_mcRun3_2024_realistic_v16

**phase2_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mcRun4_realistic_v11/123X_mcRun4_realistic_v14

**run3_hlt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_v7/123X_dataRun3_HLT_v11

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_frozen_v2/123X_dataRun3_HLT_frozen_v6

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38090

### CODE REVIEW

**Comment by tvami** [comment]
type gem,ecal

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38090

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

- failures are known. Other than that, no changes, as expected.

**Comment by qliphy** [comment]
+1

**Pull request merged**
