### PR TITLE
update of Strip hit efficiency code

### PR DESCRIPTION
**Pull request by jlagram**
Only 2 files have been modified to improve the functionalities of the hit efficiency analysis: 
- new cluster matching methods
- more flexibility in the way results are shown (for disks/rings, endcaps merged)
- results as a function of bx
- possibility to exclude some bad modules
- more plots stored in the root file

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@jlagram are the changes proposed in this PR final?

**Comment by mmusich** [comment]
+1

**Comment by jlagram** [comment]
Sorry I missed your question Marco. Yes it is final.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
