### PR TITLE
[13_0_X] Move dictionary declarations of Alpaka serial backend data products to the host classes_def.xml

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR backports #40792. Original PR description

> This PR moves the dictionary declarations of Alpaka serial backend data products to the host `classes_def.xml`. The "serial" data products are intended to be consumable by non-Alpaka EDModules as well, so having all of their definitions in the main library is more consistent. See more discussion in https://github.com/cms-sw/cmssw/pull/40690#discussion_r1096102877 .

#### PR validation:

None beyond #40792.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40792 (with the same commit)

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
backport of #40792

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
hold
- Wait for a full build in master, see https://github.com/cms-sw/cmssw/pull/40792#issuecomment-1438675167

**Comment by fwyzard** [comment]
@perrotta the latest 13.1.x IBs is still a patch :-(
Is there a way to force building a full release ?
Or, do you consider `CMSSW_13_1_ROOT626_X_2023-02-21-2300` a valid test (see https://github.com/cms-sw/cmssw/issues/40844#issuecomment-1439502410) ?

**Comment by perrotta** [comment]
unhold
- CMSSW_13_1_ROOT626_X_2023-02-21-2300 is a full build, and in fact the unit test errors do not show up there any more, as anticipated by @makortel

**Comment by perrotta** [comment]
+1

**Pull request merged**
