### PR TITLE
New GT for all supported scenarios

### PR DESCRIPTION
**Pull request by ianna**
- Salvatore's commit for a new GT including updated Sim geometry scenarios

Isolate it from #10353 to test baseline comparison.

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
please test

**Comment by ianna** [comment]
As I expected, the new GT cannot be separated from #10353.

**Comment by mmusich** [comment]
@ianna is there any combination of tags that might help? let me know.

**Pull request closed without merging**
