### PR TITLE
Use std::lower_bound to add/search for userFloats/Ints/Cands/KinResolutions (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11574.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 @cvuosalo FYI

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
xrootd error it seems... retesting.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@smuzaffar @slava77 Can someone please investigate these the above failure? (seems like MinBias dataset can't be reached...)

**Comment by slava77** [comment]
it looks like the same workflows are failing in IBs as well.
The subscription should be renewed, I suppose.
I haven't done this before: which *CERN* should be requested for this case?
the dataset in this case is /RelValMinBias_13/CMSSW_7_5_0-75X_mcRun2_asymptotic_v1-v1/GEN-SIM
I think Shahzad did this before

**Comment by smuzaffar** [comment]
@davidlt , can you please request this dataset?

**Comment by davidlt** [comment]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=491139

I guess it was auto garbage collected or something. Only available in T0 and T1 FNAL Disk cache.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by davidlt** [comment]
18 days and no progress. Is this one still alive?

**Comment by davidlange6** [comment]
@davidlt - actually its an empty area, so maybe the answer to your question is no.... but in any case, these changes aren't very important for 75x at this point given its scope- I presume they are already in 76x?

**Comment by lgray** [comment]
Yes they are in 76X, 80X.

-L

(Sent from my Nexus 6)

**Comment by davidlt** [comment]
Should we close this one?

**Comment by davidlt** [comment]
ping

**Comment by davidlange6** [comment]
instead I'll merge - we will do a bit of HI pp prompt reco with 75x (hopefully)

**Pull request merged**
