### PR TITLE
Fastsim new wf digirecomix

### PR DESCRIPTION
**Pull request by lveldere**
Hi all

4 new workflows are introduced,
FS PU steps got keys that are easier to read.

I only checked runTheMatrix -e -n for these new workflows.
I will run them tomorrow or the day after (traveling),
but I make the pr already now to keep the discussion going.
# What's new:

25207: fullsim neutrino gun, PU25
25400.1 fastsim ttbar 13 TeV, AVE10 no OOT PU, digi-reco mixing
25402: fastsim ttbar 13TeV, PU25, digi-reco mixing
25407: fastsim neutrino gun UP15, PU25, digi-reco mixing
# Older relevant workflows

25202: fullsim ttbar 13 TeV, PU25
25400: fastsim ttbar 13 TeV, AVE10, no OOT PU
# Comparisons for validation

I propose the following comparisons:

25202  vs 25402  
25207 vs 25407
(ie. nu-gun/ttbar, PU25 fast vs full)

25400 vs 25400.1
(ie fastsim ttbar, AVE10 no OOT PU, digireco mixing vs gen-mxing)

### CODE REVIEW

**Comment by lveldere** [comment]
@pdmv

All affected workflows run.
(25707,25400,25400.1,254001,254002,254007)
The filename of the fastsim minbias file for pu has to be set in an appropriate way,
but for that I'll need instructions from you I believe.

Can you let me know what further actions are needed from my side?

Thanks 

Lukas

**Comment by lveldere** [comment]
+1

**Comment by franzoni** [comment]
Hello Lukas,
a few observations, also related to the email correspondence we've had in preparation of this PR, and questions:

+ for the full sim, there's other 'customers' (e.g. tracking,calo) which need nu gun; since we're at it, we want both the pu scenarios and the 0pu;

+ we should not have pile up scenarios which are specific to fast sim; while for development one may need diverse / many options, for performance evaluation I had suggested we'd used for fast sim ave==35, to compare fast to full; to my understanding, fast sim central workflow which don't have a full sim equivalent are of little use (this would imply changing the ave10, ave20, in-time-only)

+ FS_PU_INPUT_13TEV : can you please remind me the nature of this input ? Is this a fast-sim specific format, in the new fast sim mixing ? Which workflow would produce such input ?

Cheers,
g.

**Comment by lveldere** [comment]
@franzoni , @ssekmen

Hi Giovani

I will add a neutrino gun for the 50ns and 0pU scenarios.
Is there also need for run1 workflows with neutrino guns?

About the FastSim specific pu scenarios.
I follow your view, but would like to propose a temporary compromise:
- We keep the ave 10 and ave 20 in-time only workflows for one or a few releases as back-up
- I add corresponding ave 35 in time only workflows
- FastSim PU RelVals all switch to AVE 35 workflows, 
  but if the production with the old mixing scheme crashes (memory) we use the back-up to allow validation of the new against the old mixing scheme

The minbias files needed by the new-mixing scheme are produced with worfklow 135.8

Is that all reasonable?

Cheers

Lukas

**Comment by lveldere** [comment]
@franzoni 

My last commit includes the additional wfs you proposed,
and the ones I mentioned in the compromise I suggested.

Cheers

Lukas

**Comment by lveldere** [comment]
+1

**Comment by franzoni** [comment]
hello @lveldere , please take a look at #7716 which updates this one

**Pull request closed without merging**
