### PR TITLE
[80X backport] Allow a boost on particles in MCParticlePairFilter

### PR DESCRIPTION
**Pull request by echapon**
80X backport of #16425

### CODE REVIEW

**Comment by perrozzi** [comment]
waiting for https://github.com/cms-sw/cmssw/pull/16425 to be updated

**Comment by echapon** [comment]
@perrozzi @davidlange6 #16425 was not updated because it was considered fine, and was merged as is.

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
