### PR TITLE
New TuneM2 fragments

### PR DESCRIPTION
**Pull request by pgunnell**

### CODE REVIEW

**Comment by govoni** [comment]
+1

**Comment by davidlange6** [comment]
hi @pgunnell - a belated question - nominally the reason these should be in the release is for relvals. What is the plan in that regard for these cffs?

**Comment by pgunnell** [comment]
I think they should also go to relvals, since they will be used (most probably) for central production. But perhaps others would like to comment @govoni @perrozzi

**Comment by davidlange6** [comment]
all 5 cffs?

**Comment by pgunnell** [comment]
Yes, one is for the nominal tune, the others for the different hadronizers of higher-order matrix elements.

**Comment by davidlange6** [comment]
Interesting - maybe its easier for me to picture when the relval matrix changes are made. Are those in progress?

**Comment by perrozzi** [comment]
it might be worth keeping all these cfg in the release both for relvals and reference as there might be some cmssw dependence. what do you think?

**Comment by davidlange6** [comment]
I'd rather have a coherent policy for these (which currently is Cffs for relvals in cmssw, others in genproduction - we of course can discuss how to change this policy). It sounds like we may be planning relvals for all of these but it can be most clear with the corresponding PyReleaseValidation changes.

**Comment by perrozzi** [comment]
I am very much in favor of such a policy.
If I understand correctly your statement, this PR is ok to be merged.
we will then open (or ask to open) another PR as starting point to cleanup the cfg repository

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
