### PR TITLE
update list of paths monitored by the Higgs HLT DQM

### PR DESCRIPTION
**Pull request by mplaner**
Also, adjust the RECO selection criteria for HLT diphoton for Hgg to match the trigger and offline preselection.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@mplaner - this PR does not merge now - could you rebase it. Thanks

**Comment by mplaner** [comment]
I have rebased the branch.  Does it work now, or is there something else that I need to do?

@davidlange6

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
