### PR TITLE
[GCC11] Fix compiler warnings for CalibPPS

### PR DESCRIPTION
**Pull request by smuzaffar**
This fixes the GCC11 compilation warnings from CalibPPS/ESProducers/plugins/PPSAssociationCutsESSource.cc 
```
  CalibPPS/ESProducers/plugins/PPSAssociationCutsESSource.cc:119:27: warning: loop variable 'sector' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Wrange-loop-construct]
   119 |   for (const std::string &sector : {"45", "56"}) {
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
FYI @sgrzegorz

**Comment by tvami** [comment]
@smuzaffar do you understand why there are msg logger failures in a PR which is this technical?

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
> @smuzaffar do you understand why there are msg logger failures in a PR which is this technical?

@tvami , I really do not know the details but @slava77 can help you understand the reason behind ML comparison diffs

**Pull request merged**
