### PR TITLE
Muon SIM filter

### PR DESCRIPTION
**Pull request by kskovpen**
Add a muon filter at G4 level for production of Muon-enriched QCD MC samples

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@davidlange6 , we have discussed where to put this new code and decided to have a new sub-directory equivalent to SimGeneral/TrackingAnalysis and SimGeneral/caloAnalysis.

**Comment by davidlange6** [comment]
Hi @civanch - i'd prefer SimG4CMS/Muon or SimMuon/MCTruth unless there are plans to grow this package. (but the benefit of such a filter seems rather limited - the majority of CPU is already spent at this point)

**Comment by kskovpen** [comment]
@davidlange6 Yes, there is a significant amount of CPU spent at this point already. This filter is necessary to avoid bias introduced at generator level and also to reduce disk space needed to store final samples. @civanch Could you please let me know if I should modify the existing PR or I have to submit a new one with a different package name ?

**Comment by civanch** [comment]
@kskovpen , if you agree to move to SimMuon/MCTruth an integration will be faster.

**Comment by davidlange6** [comment]
Yes, I remember the issues with the gen filters. What is the selection rate of the filter? (eg, to understand what is the benefit of applying the filter vs having a bigger but more general purpose sample available)

**Comment by kskovpen** [comment]
@davidlange6 The filter efficiencies could be found here (https://indico.cern.ch/event/579787/contributions/2349956/attachments/1361189/2061022/kskovpenBTV20161026.pdf), they were additionally optimized to meet the maximal budget possible for our MC production.

@civanch OK, I will move things then.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , it seems that it is fine to merge this PR.

**Comment by davidlange6** [comment]
+1
Probably the use of this filter should be discussed - it can be most useful if used at the input to the digi step..

**Pull request merged**
