### PR TITLE
modernize DQMDaqInfo 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of https://github.com/cms-sw/cmssw/issues/31061
Migrated `DQMDaqInfo` to `esCosumes`. 
Profited of the PR to make it an `edm::one` `EDmodule` instead of a legacy one.

#### PR validation:

`runTheMatrix.py -l limited --ibeos` runs without errors.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
Thank you @mmusich 
This issue really scape my attention

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
