### PR TITLE
Phase2-hgx120 Improve post TDR geometry definition of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
Also removes some of the bugs in the numbering code

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by bsunanda** [comment]
@nsmith- @fabiocos The change in L1 is just addition of an include hear in HGCal trigger code to avoid compilation issue. Please approve this and include it the master

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @kpedro88 Could you approve this once again - I made a small correction in one validDetId code for the scintillator part

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

affecting only Phase2 HGCal code

**Pull request merged**
