### PR TITLE
remove incorrect dependencies on boost_python and an obsolete build file

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

direct boost_python dependencies are not needed.

#### PR validation:

unit tests work.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by davidlange6** [comment]
now i'm done making updates I think

**Comment by davidlange6** [comment]
please abort test

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi @Martin-Grunewald this looks technical, please check and sign

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald the only change affecting also HLT looks purely technical, I will move forward with integration. Please have a look when possible

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
