### PR TITLE
ProdLike workflow for premixing 

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

A premixing production-like workflow is added for profiling purposes.

#### PR validation:

Ran new workflow 23434.9921 successfully.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters:
workflow = 23434.9921

**Comment by kpedro88** [comment]
please test

**Comment by chayanit** [comment]
@kpedro88 , @srimanob 
Since the classes in upgrade become larger and larger (https://github.com/cms-sw/cmssw/blob/d6cab1dc12d9893d8fe14713d4a9874add36627f/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L150-L1078), do we have any rules for the offset on each class? I would like to bring back what @srimanob proposed a few weeks ago about the documentation #32869 and convention. Could you consider this?

**Comment by kpedro88** [comment]
@chayanit the offsets in this PR are just a concatenation of the offsets of the component workflows. I agree it would be good to have more documentation. As a start, we could add a README.md in Configuration/PyReleaseValidation, much as we previously did for Configuration/Geometry.

**Comment by chayanit** [comment]
> @chayanit the offsets in this PR are just a concatenation of the offsets of the component workflows. I agree it would be good to have more documentation. As a start, we could add a README.md in Configuration/PyReleaseValidation, much as we previously did for Configuration/Geometry.

Cool thanks for your reply. Would you be able to help on this README?

**Comment by kpedro88** [comment]
@chayanit I will add it to my todo list.

**Comment by chayanit** [comment]
Thanks a lot @kpedro88!

**Comment by srimanob** [comment]
Hi @kpedro88 @chayanit 
I've added the list of offset in README.md together with updating DD4Hep workflow in
https://github.com/cms-sw/cmssw/pull/33087
Please feel free to comment on what you think should be mentioned. Thanks.

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
@srimanob I added some more generic info to the new readme here as well.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@slava77 we actually need the matrix map for 34634.0 and 34834.999

**Comment by kpedro88** [comment]
It should be CMSSW_11_3_X_2021-03-04-1800, which includes #33007

**Comment by slava77** [comment]
> It should be CMSSW_11_3_X_2021-03-04-1800, which includes #33007

looking back in my inbox; indeed, it's been a while. I guess I managed to filter these out mentally.
Thanks for the ping. I'll update today.

**Comment by slava77** [comment]
> I'll update today.

cms-sw/cms-bot#1500

**Comment by srimanob** [comment]
+Upgrade

This PR is to add Prod-like Premixing workflow, and update README.

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by srimanob** [comment]
By the way, @kpedro88 
Is this expected to use pdigi_valid for prod-like workflow?
I think we use it for L1T campaign, however, not in general. Or now, ppl needs this information in general MC campaign?

Sorry for late response. Thanks.

**Comment by kpedro88** [comment]
@srimanob the most recent TDR campaign uses pdigi_valid: https://twiki.cern.ch/twiki/bin/view/CMS/Phase2HLTTDRWinter20DR

**Comment by srimanob** [comment]
@kpedro88 
It is in that way because when I constructed cmsDriver from testing, I forget to change it. Not sure if we need MC truth information in that campaign, no one complained because it is there.

**Pull request merged**
