### PR TITLE
Update beampixel_dqm_sourceclient-live_cfg.py

### PR DESCRIPTION
**Pull request by dinardo**
Re-establish configuration simular to Run-1: distinguishing between pp and HI collisions.
I don't know why it was modified in the way it is. Maybe there is as good reason but as I don't know it.

### CODE REVIEW

**Comment by deguio** [comment]
could you submit this same PR to 73 as well?
thanks,
F.

**Comment by deguio** [comment]
could you also submit to 75 as well?
we are in the transition to that release.
thanks again,
F.

**Comment by deguio** [comment]
@dinardo 
please submit to 73x by today 2PM if you want to have this online next monday
thanks,
F.

**Comment by deguio** [comment]
btw,
the last change to this config comes from you: #5924

**Comment by deguio** [comment]
-1
ok. understand now. you are looking at the wrong file.
please refer to:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DQM/Integration/python/test/beampixel_dqm_sourceclient-live_cfg.py

this is the one we run.
rejecting this one.
ciao,
F.

**Comment by dinardo** [comment]
Ah OK.
If that's what we run, then there there is no need for my pull request.
Many thanks.
- Mauro.

**Pull request closed without merging**
