### PR TITLE
Utilities/StaticAnalyzers: update the EventSetupRecord::get warning with links to wiki

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test with #33215

**Comment by makortel** [comment]
@gartung Should the change of this PR be visible in the static analyzer report of this PR?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-96d500/13755/llvm-analysis/

**Comment by makortel** [comment]
> @gartung Should the change of this PR be visible in the static analyzer report of this PR?
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-96d500/13755/llvm-analysis/

Or is this PR intended for the warnings tested in https://github.com/cms-sw/cms-bot/pull/1514#issuecomment-806536044 ?

**Comment by gartung** [comment]
The only change would be the extended warning which you can see if you click on one of the warnings in the static checks report.

**Comment by gartung** [comment]
Correct you need to look at the logs for the cms-bot PR.

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
@makortel this needs core approval

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by gartung** [comment]
please test with https://github.com/cms-sw/cms-bot/pull/1527

**Pull request merged**
