### PR TITLE
Phase2 Tracker  T6 : New raddii of Inner Pixel Barrel layers

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
this PR is introducing the T6 phase2 Tracker geometry following some mechanics studies towards a more realistic description of the inner Pixel Barrel (changing radii of the inner pixel barrel layers).
Internal reference : phase2 tilted tracker : v6.1.3 / phase 2 pixel : v4.0.4  

Following the comments received in the original PR#20988 , I did create a new scenario in runthematrix, This is the natural evolution of T5 , but I have understood that T5 (used in TDRs) should be kept frozen for some time, therefore T6 has been created, leaving T5 untouched.
The geometry xml files  are exactly the sames as the original PR #20988 .

Please note that since the number of modules is changed in those layers (due to the radius change) , the list of detids should also be taken into account by including this file (external) , see :
https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/pull/9
please do not launch a test without this external file

RunThematrix should be fully in place (hopefully) , workflow for 2023D21 (=2023D17 but with T6) : 212XX  

Modifications:  the raddii of three out of four inner pixel barrel layers 
Before (T5)
r | 29.000 | 70.146 | 117.753 | 157.388 |  
in his geometry (T6)
r | 29.000 | 60.000 | 100.000 | 140.000 |  

all work done by @ghugo83

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
please abort
(need associated external for testing)

**Comment by kpedro88** [comment]
@smuzaffar can we test with https://github.com/cms-sw/cmsdist/issues/3552 or does it need to be the actual cmsdist PR?

**Comment by ianna** [comment]
@kpedro88 - which one?

**Comment by kpedro88** [comment]
@ianna:
>Please note that since the number of modules is changed in those layers (due to the radius change) , the list of detids should also be taken into account by including this file (external) , see :
cms-data/SLHCUpgradeSimulations-Geometry#9
please do not launch a test without this external file

**Comment by smuzaffar** [comment]
@kpedro88 , it needs a Pr which I am going to make now

**Comment by smuzaffar** [comment]
cmsdist PR https://github.com/cms-sw/cmsdist/pull/3553 is available for testing

**Comment by kpedro88** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/3553

@smuzaffar thanks

**Comment by ianna** [comment]
@smuzaffar - I do not see any action

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#3553

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
