### PR TITLE
[RECONSTRUCTION-UPGRADE] [LLVM14] Apply code checks

### PR DESCRIPTION
**Pull request by smuzaffar**
Applying code checks changes suggested by LLVM 14 ( which we want to integrate in cmssw once fully testing in CLANG IBs).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
technical

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
