### PR TITLE
Run3-gex126B Try to resolve compilation warnings in RecoParticleFlow/Configuration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to resolve compilation warnings in RecoParticleFlow/Configuration

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jpata** [comment]
Similar comment about the /test/ code being abandoned here as in https://github.com/cms-sw/cmssw/pull/37399.

**Comment by bsunanda** [comment]
@jpata I came across this compilation warning while I was editing a Geometry package and did checkdeps and build. It is annoying to see compilation warning. So I fixed it so that the warning goes away. I did not bother to test its functionality. Just ran the standard tests which may or may not cover this. If you think these corrections are redundant I can delete those classes. But I thought it is safer to remove the warnings and let others decide about its retainment or removal.

**Comment by bsunanda** [comment]
@jpata @laurenhay @hatakeyamak So instead of fixing the two classes, let me then delete them in this PR. Hope you agree

**Comment by bsunanda** [comment]
@jpata Can I delete the affected classes from the repository as done in #37399? Please confirm

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jpata** [comment]
@cms-sw/pf-l2 please note the removal of the test code here.

**Comment by jpata** [comment]
+reconstruction
- technical unused code cleanup in PF tests
- follow-ups may be useful

**Comment by perrotta** [comment]
+1

**Pull request merged**
