### PR TITLE
[RECO] Fix DEVEL warnings on deprecated copy-constructors

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by jfernan2** [comment]
@aandvalenzuela could you please add a minimal description even if it just says these constructors are deprecated and which tests have you performed to check everything works as expected?
Thanks in advance

**Comment by iarspider** [comment]
> @aandvalenzuela could you please add a minimal description even if it just says these constructors are deprecated and which tests have you performed to check everything works as expected? Thanks in advance

@jfernan2 this PR fixes violation of ["rule of three"](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)): if a class defines any of these three special funcitons - destructor, copy constructor, copy assignment operator - it should define all three, or none. In this (and similar) PRs we remove trivial versions of these functions, letting compiler generate them for us.

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
