### PR TITLE
Comphep single top filter pythia8

### PR DESCRIPTION
**Pull request by alexeybaskakov**
Update of edm::Handle, new method getByToken is used
And update to SealModule.cc to include new filter

### CODE REVIEW

**Comment by govoni** [comment]
plese test

**Comment by perrozzi** [comment]
please test
(there was a typo :) )

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
can this PR be merged and included in the next 71X please?

**Comment by davidlange6** [comment]
+1

**Comment by perrozzi** [comment]
Hi, is not completely clear to me whether from this line
https://github.com/cms-sw/cmssw/pull/17522/files#diff-f6f21528f835486327cca6d0e0bd1da1R38
if the collection withouth "unsmeared" label can be accessed with this PR in 71X.
I am afraid not, in which case another PR should be done to fix this.
Can anybody please comment?
Thanks Luca

**Pull request merged**
