### PR TITLE
Fixing collection for producing unprefirable bit in NANO (master)

### PR DESCRIPTION
**Pull request by lathomas**
#### PR description:

The L1 unprefirable bit ("L1_UnprefireableEvent") is currently always false in NANOAOD. This is found to be due to the wrong input collection being provided to the dedicated producer.

This PR corrects this.

#### PR validation:
 

Ran on a few unprefirable data events previously identified and checked that the boolean is now true. 
Checked that MC is not affected.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by gouskos** [comment]
please test

**Comment by lathomas** [comment]
kind ping @gouskos @mariadalfonso. We then need a backport to 106X, would appreciate if someone else can take care of it ! 
FYI @rekovic @BenjaminRS

**Comment by lathomas** [comment]
Kind ping. @mariadalfonso @gouskos

**Comment by mariadalfonso** [comment]
please test

(re-running with recent release, ready to merge)

**Comment by mariadalfonso** [comment]
+xpog

**Comment by perrotta** [comment]
+1

**Pull request merged**
