### PR TITLE
bsunanda:Run2-TB02 HGCal Test Beam

### PR DESCRIPTION
**Pull request by bsunanda**
Adding 16 module description for July TB scenario

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @civanch Could you see this and approve this?

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
