### PR TITLE
Add a Phase2 HLT tracking DQM monitoring (13.1.X)

### PR DESCRIPTION
**Pull request by mmusich**
backport of #42783

#### PR description:

Minimal set of changes needed to the Tracking @ HLT DQM monitoring sequence for the Phase-2 setup.
This relies on the current naming of the tracking collections for the phase-2 HLT:
   * `generalTracks` (somewhat copied from offline)
   * `hltPhase2PixelTracks` (pixel tracks)
   * `hltPhase2PixelVertices` (pixel vertices)

The latter two were introduced in https://github.com/cms-sw/cmssw/pull/42512 but the name change was not percolated to the `FEVTDEBUGHLTEventContent`, so it becomes necessary to include them in the list of collections to be persisted.
Changes for making the Phase-2 HLT Validation are more extensive and will be addressed with another PR at a later time.

#### PR validation:

Run successfully `runTheMatrix.py -l 20834.0 -t 4 -j 8` (and checked that the HLT tracking plots are full).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of #42783

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
@mmusich is this supposed to be promoted from a draft now?

**Comment by mmusich** [comment]
@rappoccio 

> is this supposed to be promoted from a draft now?

unfortunately not yet. The plots were added but they are all empty: https://tinyurl.com/27qslwcs.
I haven't had yet time to investigate why. I'll come back to this as soon as I can.

**Comment by mmusich** [comment]
> The plots were added but they are all empty: https://tinyurl.com/27qslwcs.

OK, I had some time to look at this and reason why wf 23234.0 plots are empty is rather mundane.
Wf 23234.0 employs geometry D94:

https://github.com/cms-sw/cmssw/blob/15594bf0fdc28c609d1a2c54b516287f6c8f0390/Configuration/PyReleaseValidation/python/relval_2026.py#L27

and for that geometry we run the fake menu:

https://github.com/cms-sw/cmssw/blob/15594bf0fdc28c609d1a2c54b516287f6c8f0390/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L2583-L2589

so, of course there aren't HLT products available for DQM.
I privately re-run `runTheMatrix.py -l 20834.0 -t 4 -j 8` which uses D88 instead:

https://github.com/cms-sw/cmssw/blob/15594bf0fdc28c609d1a2c54b516287f6c8f0390/Configuration/PyReleaseValidation/python/relval_2026.py#L18

(which runs the real phase-2 menu)

https://github.com/cms-sw/cmssw/blob/15594bf0fdc28c609d1a2c54b516287f6c8f0390/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L2555-L2561

and I see filled plots. So I think we can go ahead with this PR.

**Comment by mmusich** [comment]
test parameters:
   * workflow = 20834.0, 23634.0
   * relvals_opt= -w upgrade

**Comment by mmusich** [comment]
@cmsbuild, please test
   * tests are bit stale by now.

**Comment by rovere** [comment]
@mmusich do you think it makes sense to integrate this in 13_1? The Review is over, there's P2UG coming, but I'm not sure.

**Comment by mmusich** [comment]
@rovere 

>  do you think it makes sense to integrate this in 13_1? 

well, why not. If there's more PRs that you want to integrated in [the queue](https://github.com/cms-sw/cmssw/pulls?q=is%3Aopen+is%3Apr+label%3Ahlt-approved+milestone%3ACMSSW_13_1_X) this one might enter as well.

**Comment by rappoccio** [comment]
+1

**Comment by slava77** [comment]
type tracking

**Pull request merged**
