### PR TITLE
Migrate Geometry/HGCalCommonData to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates all ES and ED modules in Geometry/HGCalCommonData to EventSetup consumes (#26584).

In addition
- Fix a use-after-delete in `HGCalNumberingInitialization` in case of an IOV change
- Move away from `edm::ESTransientHandle` in `HGCGeometryTester::analyze()`, because the transient handle should be used only after IOV changes, not for every event

#### PR validation:

Limited matrix runs

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@bsunanda FYI

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
