### PR TITLE
Various fixes for pixel clustering on GPU

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Various fixes for pixel clustering on GPU:
  - when building in debug mode (`g++ -DGPU_DEBUG`) synchronise only the current stream instead of the whole device after each operation;
  - size the kernel grid based on the correct number of pixel modules for Phase-1;
  - remove obsolete debug statement that does not compile any more.

#### PR validation:

None.

#### If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW 12.4.x for data taking at HLT.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@AdrianoDee FYI

**Comment by fwyzard** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- bugfixes and cleanup
- no differences in reco tests
- as far as I understand, if there are any differences, it should be in HLT and a bugfix (i.e. fixing something that was not correct)

**Comment by fwyzard** [comment]
urgent

I would like to have the backport in 12.4.x in order to simplify further debugging

**Comment by qliphy** [comment]
+1

**Pull request merged**
