### PR TITLE
allow running the steps L1 and DQM in one job

### PR DESCRIPTION
**Pull request by lveldere**
FastSim would like to run the steps L1 and DQM in one job.
However, changing parameters of simRctUpgradeFormatDigis in ValL1Emulator_cff.py
causes issues when running the L1 and DQM steps in one job.
Therefore I replace simRctUpgradeFormatDigis with a clone in ValL1Emulator_cff.py

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by mulhearn** [comment]
Just noting that we have some config changes in the pipeline for 80x which may collide with this one.

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
