### PR TITLE
Removed ShiftFillLast because it generates confusion in shifters

### PR DESCRIPTION
**Pull request by dinardo**
A DQM shifter pointer me to a feature of the layout that might be misunderstood,
therefore I decided to simplify the histograms: I removed the ShiftFillLast and I
made all plots with a fixed X axis range that span over 20h of uninterrupted running
- Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
Hi,
I'm not sure why it says that this PR involves "RecoEgamma" stuff.
I've tested it in "CMSSW_7_4_12_patch4" and it involves only "DQM/BeamMonitor"
So, please forget about "RecoEgamma".
Many thanks,
- Mauro.

**Comment by lgray** [comment]
You might want to fix the typo in the PR title... :-)

**Comment by lgray** [comment]
You're picking up PRs from EGM because you based off of a 7_4_12 patch release (which is on a different branch at the moment from 74X mainline). Just rebase your commits to CMSSW_7_4_X instead of CMSSW_7_4_12_patchX.

**Comment by dinardo** [comment]
Hi Lindsey,
ops, I fixed the title of course. Sorry about that.
Concerning the re-base.
Can you please tell me how to do it ?
Many thanks,
- Mauro.

**Comment by lgray** [comment]
It looks like your commits are only the last two, so you'd do something like this:
```
git fetch my-cmssw CMSSW_7_4_X:CMSSW_7_4_X
git rebase -i --onto CMSSW_7_4_X my-new-feature_74~2 my-new-feature_74
git push my-cmssw my-new-feature_74 -f  #only do this when you are sure everything works after the rebase :-)
```

**Comment by dinardo** [comment]
Hi Lindsey,
many thanks for your patience.
I've tied your commands but already at the first one I have a problem:
[dinardo@lxplus0098 src]$ git fetch my-cmssw CMSSW_7_4_X:CMSSW_7_4_X
From https://github.com/dinardo/cmssw
 ! [rejected]        CMSSW_7_4_X -> CMSSW_7_4_X  (non-fast-forward)
Any suggestion ?
I'm also willing to checkout a new fresh CMSSW version and push my modifications from there, but which CMSSW version shall I use now? I'm confused.
Many thanks,
- Mauro.

**Comment by lgray** [comment]
Hi Mauro, sorry I made a typo. Please try:
```
git fetch official-cmssw CMSSW_7_4_X:CMSSW_7_4_X
git rebase -i --onto CMSSW_7_4_X my-new-feature_74~2 my-new-feature_74
git push my-cmssw my-new-feature_74 -f  #only do this when you are sure everything works after the rebase :-)
```

**Comment by dinardo** [comment]
Many thanks !
OK done. Now it should be ok.
Cheers,
- Mauro.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
ciao mauro,
unfortunately I have to ask you something else.
you have recently submitted 2 PRs which are not yet merged in 74:
https://github.com/cms-sw/cmssw/pull/10844
and https://github.com/cms-sw/cmssw/pull/11386 (this one)

the two conflict with each other. could you just merge these or rebase 11386 on top of the other?
at the moment we cannot test both on the playback at the same time on top of 7_4_12_patch4
thanks,
F.

**Pull request closed without merging**
