### PR TITLE
Add possibility for partial ECAL digitization (towards working HGCAL)

### PR DESCRIPTION
**Pull request by lgray**
Add in options to turn off EB/EE/ES in ECAL digitizer, default all on.
Also, some modernization of code.

This change is technical in nature.

### CODE REVIEW

**Comment by lgray** [comment]
@vandreev11 @pfs @cseez @kpedro88 @sethzenz FYI

**Comment by civanch** [comment]
please test

**Comment by lgray** [comment]
@civanch FYI IBs are broken right now, tests will fail.

**Comment by lgray** [comment]
Ah, good a whole bunch of clang errors to fix. Will do that.

**Comment by argiro** [comment]
@lgray,

I believe this is just adding the possibility to switch EE/EB/ES digitization on/off, right ? 
If not , it would be great if you could you tell us ECAL-ers a bit more about this PR.

thanks, S.

**Comment by lgray** [comment]
@argiro Yes, correct, it just adds this switching capability. It changes bare pointers to use std::unique_ptr where appropriate. Nothing more.

**Comment by smuzaffar** [comment]
pleas test

**Comment by lgray** [comment]
Will fix up tomorrow.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by lgray** [comment]
Would be nice to get this one in here or in 80X. Either is fine. Thanks!

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@lgray , could this PR be the reason of following failure in IBs relval tests
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2015-10-20-1100/pyRelValMatrixLogs/run/250407.0_NUGUN_UP15+FS_NuGun_UP15_PRMXUP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS/step1_NUGUN_UP15+FS_NuGun_UP15_PRMXUP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS.log
MissingParameter: Parameter 'doEB' not found.
```

**Comment by lgray** [comment]
@smuzaffar Yes, that's related to this IB. It's really weird that the other fastsim workflows function... I'll take a look and provide a fix.

**Pull request merged**
