### PR TITLE
Replace Geometry_cff with GeometryDB_cff in MuonAnalysis

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, MuonAnalysis configuration files 6 files are fixed.
```
        modified:   MuonAnalysis/MuonAssociators/test/L1MuonMatcher/test.py
        modified:   MuonAnalysis/MuonAssociators/test/L1MuonMatcher/testAnyBX.py
        modified:   MuonAnalysis/MuonAssociators/test/L1MuonMatcher/testCRAFT.py
        modified:   MuonAnalysis/MuonAssociators/test/L1MuonMatcher/testCRAFTCosmic.py
        modified:   MuonAnalysis/MuonAssociators/test/testL1MuonMatcherExt.py
        modified:   MuonAnalysis/MuonAssociators/test/testL1MuonMatcherExt_JPsi.py

```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
@cms-sw/muon-pog-l2  @cms-sw/muon-dpg-l2  : these test configs are probally old and not used since a while. If they are not needed any more a better oprion could be to remove them at all, rather than to spend time in maintaining them every some while. Please let us know.

**Comment by perrotta** [comment]
https://github.com/orgs/cms-sw/teams/muon-pog-l2 https://github.com/orgs/cms-sw/teams/muon-dpg-l2 : ping!

**Comment by CeliaFernandez** [comment]
> https://github.com/orgs/cms-sw/teams/muon-pog-l2 https://github.com/orgs/cms-sw/teams/muon-dpg-l2 : ping!

Hi @perrotta, thanks a lot and sorry for the late reply, we are looking into it. From what I see most of these files are useless as they are e.g. they read very old non-existing files. I'm studying if we can just remove them or if it would make sense to prepare an updated version, at least for some of them. We will come back with an answer very soon.

**Comment by mileva** [comment]
Hi @perrotta 
Further to the brief discussion we had within muon dpg, 
we don't use the muon associators for dpg analysys.
About the geometry - muon alignment group uses the DB-based config, as well.
So, I think we are fine with this  PR.
Thank you for pinging us!
Roumyana
for Muon DPGs

**Comment by perrotta** [comment]
> Hi @perrotta Further to the brief discussion we had within muon dpg, we don't use the muon associators for dpg analysys. About the geometry - muon alignment group uses the DB-based config, as well. So, I think we are fine with this PR. Thank you for pinging us! Roumyana for Muon DPGs

Thank you @mileva 
Just to understand: are you fine with this PR as it is (i.e. updating and keeping maintained the code touched here) or are you fine with the proposal of removing these test configs, as you claim that they are not used any more?

**Comment by mileva** [comment]
Hi @perrotta 
We are fine if you remove them - we don't use them for muon dpg studies.
Roumyana

**Comment by perrotta** [comment]
> Hi @perrotta We are fine if you remove them - we don't use them for muon dpg studies. Roumyana

Thank you Roumiyana.

@jeongeun could you then please take care of modifying this PR by removing all the modules config that you were modifying here? Thank you!

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
