### PR TITLE
[12_6_X] update input dataset and fix step

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

a couple of fixes to the nano workflows

### CODE REVIEW

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
lots of changes since the input dataset was changed

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
another signature from you please @cms-sw/pdmv-l2 @cms-sw/upgrade-l2

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
backport of #40211

**Comment by rappoccio** [comment]
+1

**Pull request merged**
