### PR TITLE
Phase2-hgx350Y Protection against segentation violation for V18 version of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Protection against segentation violation for V18 version of HGCal

#### PR validation:

Use the runTheMatrix test workflow 27234.0 with 100 events

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@srimanob Please approve this. Ivan has specified the correction

**Comment by bsunanda** [comment]
type bugfix

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
