### PR TITLE
MultiTrackValidator cleanup

### PR DESCRIPTION
**Pull request by makortel**
This PR does some cleanup on MultiTrackValidator, main changes
- Remove MTVHistoProducerAlgo base class (and the factory) as unnecessary (there is only one concrete class inheriting from it)
- Use inique_ptr for TrackingParticle/GenParticle selectors
- Initialize certain variables only if `EDM_ML_DEBUG` is defined to suppress "dead store" warnings from static analyzer

Tested in CMSSW_7_6_X_2015-08-10-2300, no changes expected in results.

@rovere @VinInn

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
thanks for the cleanup. looks good.

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
