### PR TITLE
improve logging of `addOnTests`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is alternative to #36423.

The issue is that different "addon" tests can produce log files with the same basename. When one of these tests fails, the `cmsbuild` bot has trouble identifying which test failed (see https://github.com/cms-sw/cmssw/pull/40011#issuecomment-1306810543 for an example).

The (potential) fix in #36423 is minimal but fragile. This PR is more invasive, and changes the names of the `addOnTests` logs in order to make them unique by construction.

With this PR, a "addon" test `XYZ` with N steps creates log files named `XYZ/step{1,..,N}.log`. In addition, a text file named `cmdLog` with the list of steps is added to every addon sub-directory `XYZ`. Lines in the main log file of the `addOnTests` have the following format
```
[hlt_data_PRef:1] cmsDriver.py RelVal -s L1REPACK:Full --data --scenario=pp -n 10 --conditions auto:run3_hlt_PRef --relval 9000,50 --datatier "RAW" --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run3 --eventcontent RAW --fileout file:RelVal_Raw_PRef_DATA.root --filein root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/STORM/RAW/Run2022B_HLTPhysics0_run355558/cd851cf4-0fca-4d76-b80e-1d33e1371929.root : PASSED - elapsed time: 26 sec (ended on Tue Nov  8 23:34:13 2022) - exit: 0

[hlt_data_PRef:2] cmsRun /work/missiroli_m/test/tsg/storm/devel_addOnTestsLogFileName/CMSSW_12_6_0_pre4/src/HLTrigger/Configuration/test/OnLine_HLT_PRef.py realData=True globalTag=@ inputFiles=@ : PASSED - elapsed time: 56 sec (ended on Tue Nov  8 23:35:10 2022) - exit: 0

[hlt_data_PRef:3] cmsDriver.py RelVal -s HLT:PRef,RAW2DIGI,L1Reco,RECO --data --scenario=pp -n 10 --conditions auto:run3_data_PRef --relval 9000,50 --datatier "RAW-HLT-RECO" --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --customise=HLTrigger/Configuration/CustomConfigs.HLTRECO --customise=HLTrigger/Configuration/CustomConfigs.customiseGlobalTagForOnlineBeamSpot --era Run3 --processName=HLTRECO --filein file:RelVal_Raw_PRef_DATA.root --fileout file:RelVal_Raw_PRef_DATA_HLT_RECO.root : PASSED - elapsed time: 84 sec (ended on Tue Nov  8 23:36:35 2022) - exit: 0
```
The first bit, i.e. `[test:N]`, is added for clarity, and to allow the bot to find the correct log file without ambiguities.

The way elapsed time is reported for every given addon test is also updated.

This PR requires https://github.com/cms-sw/cms-bot/pull/1879.

#### PR validation:

`addOnTests.py` passed.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
 - pull_requests = https://github.com/cms-sw/cms-bot/pull/1879

**Comment by missirol** [comment]
please test with https://github.com/cms-sw/cmssw/pull/40011

https://github.com/cms-sw/cmssw/pull/40011 will make this fail. If this PR works, the bot should point to the failed addon test.

**Comment by missirol** [comment]
test parameters:
 - pull_requests = https://github.com/cms-sw/cms-bot/pull/1879, #40011

**Comment by missirol** [comment]
please test

It didn't really work yet (see https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1308226999); my only guess is that https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1307973078 overwrote https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1307972261 (instead of combining them, which was my naive expectation). Let me retry.

**Comment by missirol** [comment]
test parameters:
 - pull_requests = https://github.com/cms-sw/cms-bot/pull/1879

**Comment by missirol** [comment]
please test

https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1308559851 shows the expected output (okay, it does not say which step failed, but that was already the case, and it requires a couple more tweaks on the cmsbot side, I would postpone it).

Now rerunning tests to see them pass.

**Comment by missirol** [comment]
(The ongoing tests here with "https://github.com/cms-sw/cmssw/pull/40018 + https://github.com/cms-sw/cms-bot/pull/1879" should pass, as they already passed in https://github.com/cms-sw/cms-bot/pull/1879#issuecomment-1308604397, modulo the unrelated RelVal-INPUT error.)

As far as I can see, https://github.com/cms-sw/cmssw/pull/40018 and https://github.com/cms-sw/cms-bot/pull/1879 are working as intended: they give the bot a way to find the failed addon test without ambiguities (example in https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1308559851).

@smuzaffar @makortel,

what do you think? Is it okay to (slightly) change the naming of the addon logs this way?

Are there any other 'clients' of these logs (for example, when making the IB pages) that would need to be updated?

**Comment by missirol** [comment]
I updated this PR to start numbering steps from `1` rather than `0`; this follows what is displayed on the IB webpage [[example]](https://cmssdt.cern.ch/SDT/cgi-bin//showAddOnLogs.py/el8_amd64_gcc10/www/sat/12.6-sat-11/CMSSW_12_6_X_2022-11-12-1100/addOnTests/) (i.e. `step1, step2, step3`):
https://github.com/cms-sw/cmssw/compare/cf4126824f49c1e91c259e9e38b166938d2ee7c9..463cc22f8ba10f80a9a4f9167803da646bbeb72c

https://github.com/cms-sw/cms-bot/pull/1879 does not need to be updated for this.

https://github.com/cms-sw/cmssdt-web/pull/7 contains the corresponding `cmssdt` update discussed in https://github.com/cms-sw/cmssw/pull/40018#issuecomment-1309492110.

**Comment by missirol** [comment]
please test

**Comment by makortel** [comment]
Looks ok to me. @smuzaffar, what do you think?

**Comment by smuzaffar** [comment]
+core
looks good, both bot and cmssdt-web PR required for this change are already merged.

**Comment by perrotta** [comment]
+1

**Pull request merged**
