### PR TITLE
Remove references to standalone keras

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Keras is now part of Tensorflow so we remove all references to standalone Keras

### CODE REVIEW

**Comment by iarspider** [comment]
The RelVal failure is known (#36029) and not related to this PR.

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/36021

**Comment by tvami** [comment]
+alca 
 * technical PR 
 * diffs only in MsgLogger

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
