### PR TITLE
Allow stacktrace handler to timeout.

### PR DESCRIPTION
**Pull request by bbockelm**
This corrects a few issues:
- Stacktrace handler thread will set the SIGABRT and friends handler
  to SIG_DFL.  Avoids a potential deadlock.
- Primary signal handler will timeout after 5 minutes of waiting for
  the stacktrace handler thread to return (timeout hardcoded for now).
- Do NOT call execv: libsnoopy at CERN replaces the async-signal-safe
  POSIX function with a non-async-signal-safe variant which can cause
  deadlocks.  Instead, invoke the syscall directly (only on Linux).

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by bbockelm** [comment]
@Dr15Jones - I assume a backport is reasonable for 7.4 and 7.5 if this passes IBs with flying colors?

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
@bbockelm  Which ever releases we switch out the ROOT handler for your new one we will need back porch this change to as well.

**Pull request merged**
