### PR TITLE
Refactor ProductResolvers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Removed put interfaces from base class and use ProductPutterBase abstract class instead
- Separated InputProductResolver into DelayedReader* and PutOnRead* variants
- BranchDescription::onDemand is also true for case of DelayedReader being used by source
- putOrMerge on ProductResolvers was not being used so was removed.

#### PR validation:

- code compiles
- framework related unit tests all pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test with #33274

**Comment by agrohsje** [comment]
no objection to the gen part.
+generators

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
> no objection to the gen part.
> +generators

Not sure why the signature doesn't work.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by agrohsje** [comment]
+generators

**Pull request merged**
