### PR TITLE
[New GT][2018 realistic and cosmic realistic] 2018 GEM,HCAL geom + ECAL thresholds for 2018

### PR DESCRIPTION
**Pull request by lpernie**
CHANGES:
**2018 realistic: 100X_upgrade2018_realistic_v6**
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v6/100X_upgrade2018_realistic_v4
-> 2018 GEM and HCAL geom. + New ECAL thresholds

**2018 realistic cosmics: 100X_upgrade2018cosmics_realistic_deco_v5** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v5/100X_upgrade2018cosmics_realistic_deco_v3
-> 2018 GEM and HCAL geom. + New ECAL thresholds + HCAL  Channel Quality, LUTCorrs. RespCorrs, ZSThresholds,  QIEData

**2018 ideal: 100X_upgrade2018_design_IdealBS_v4** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v4/100X_upgrade2018_design_IdealBS_v3
-> 2018 GEM and HCAL geom. + HCAL Channel Quality, LUTCorrs. RespCorrs, ZSThresholds, QIEData
NOTES:
. The new conditions will be signed off during the PPD meeting on Jan 18

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
In the Unit tests I see:
config/SCRAM/GMake/Makefile.rules:2081: recipe for target 'unittests_runTheWhiteRabbit' failed
gmake: *** [unittests_runTheWhiteRabbit] Terminated

Maybe a glitch? I will submit tests again

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie (and @deguio @crovelli ) Is there any dependency between this tag and the pending PRs for HCAL and ECAL? At latest ORP I understood that the affected geometry will be the reco one (so GEN-SIM will be unaffected), is it correct? And I see other parameters affected (e.g. ECAL thresholds...)

**Comment by crovelli** [comment]
adding @amassiro

The ECAL changes in the global tag are unrelated to the reco PR.
The updates in the GT are related to noise, transparency loss and DAQ
thresholds for 2018. The updates in reco are related to rechits and
clustering thresholds.

**Comment by deguio** [comment]
Hi @fabiocos 
correct. for hcal the affected geometry will be the reco one. this GT makes possible to run the collapsed 2018 scenario using #21842

**Comment by abdoulline** [comment]
Federico, main goal is collapsed 2018 HE for HLT, right?

**Comment by deguio** [comment]
yes. and the collapsed 2018 validation with pre4

**Comment by fabiocos** [comment]
+1

**Pull request merged**
