### PR TITLE
EcalPedestals management

### PR DESCRIPTION
**Pull request by depasse**
EcalPedestals tools  + management (by splitting) of tags with thousands IOVs + old DBv1 pythons upgraded.

Replace PR #18880

### CODE REVIEW

**Comment by depasse** [comment]
Hi,

any news on this ?  Are there pb ?
Thanks.
________________________________

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
