### PR TITLE
Run3-gex112X Correction to the MuonOffsets for the new Run3 scenario (due to Ian)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correction to the MuonOffsets for the new Run3 scenario (due to Ian)

#### PR validation:

Tested separately for Run3 and Phase2 scenarios

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta @qliphy @civanch @cvuosalo The failures are due to wrong Run3 geometry is in the DB. It will be better to inhibit these 3 workflows till we finalize Run3 geometry

**Comment by civanch** [comment]
@bsunanda , may be this PR should be the last and for now be on hold?

**Comment by perrotta** [comment]
> @perrotta @qliphy @civanch @cvuosalo The failures are due to wrong Run3 geometry is in the DB. It will be better to inhibit these 3 workflows till we finalize Run3 geometry

Hi @bsunanda 
The workflows that fail in tests are six, by the way, not three...
I suggest to fix the geometry first, and then continue with the developments based on it.

**Comment by civanch** [comment]
urgent

**Comment by civanch** [comment]
I mark PRs as urgent to compile a correct geometry for Run3

**Comment by perrotta** [comment]
@cmsbuild please test with #36755,#36654,#36750,#36765,#36766

**Comment by cvuosalo** [comment]
Tests look OK considering that the geometry has changed.

**Comment by perrotta** [comment]
+1
- Merging together #36679 #36654 #36750 #36765 #36766 for pre4

**Comment by perrotta** [comment]
merge

**Pull request merged**
