### PR TITLE
Allow ECAL pfrechit thresholds eta dependent in all regions, disregarding if ZS of FR

### PR DESCRIPTION
**Pull request by amassiro**
Allow ECAL pfrechit thresholds eta dependent in all regions, disregarding if they have been read in Zero Suppression (ZS) of Full Readout (FR).

In the previous version we could activate these thresholds only in ZS regions, or de-activate the application of the thresholds everywhere.

With this PR we can activate the thresholds everywhere, by means of the boolean: "applySelectionsToAllCrystals"

### CODE REVIEW

**Comment by kpedro88** [comment]
-1
wrong branch or needs rebase

**Comment by slava77** [comment]
-1

it looks like a wrong branch

**Comment by amassiro** [comment]
Sorry, I confirm wrong branch!
Sorry for the noise.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
-1
@amassiro please rebase, move it to the correct branch or whatever
As such the PR is unmergeable

**Comment by Martin-Grunewald** [comment]
-1
please close this PR of fix it

**Comment by perrotta** [comment]
@amassiro : you should probably close this one, now that you opened #22265 ...

**Pull request closed without merging**
