### PR TITLE
[126X] The Lorentz Angle Prompt Calibration Loop for Pixel Forward Phase 1 detector 

### PR DESCRIPTION
**Pull request by tsusa**
#### PR description:

This PR introduces the Lorentz Angle (LA) Prompt Calibration Loop for the Pixel Forward Phase 1 detector (FPIX). In FPIX, LA is measured using the Minimal Cluster Size method.
The SiPixelLorentzAnglePCLWorker creates 16 2D cluster size x/y vs cot(alpha/beta) histograms and 8x3 magnetic field components histograms. In SiPixelLorentzAnglePCHarvesterMCS the cluster size x/y vs cot(alpha/beta) histograms are used to generate 1D profiles (average cluster size x/y vs cot(alpha/beta)) which are then fit and the values of the cot (alpha/beta) for which the cluster sizes are minimal are determined. The obtained cot(alpha/beta)_min value for z- and z+ side are used to perform fit to determine muH for different rings and panels of the Pixel Forward Phase 1 detector using the formulas:

cot(alpha)_min = vx/vz = (muHBy + muH^2xBzBx)/(1+muH^2Bz^2)
cot(beta)_min = vy/vz = -(muHBx - muH^2xBzBx)/(1+muH^2Bz^2)

#### PR validation:

runTheMatrix for the new wfs 1052, 1052.1

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of the PR https://github.com/cms-sw/cmssw/pull/40664. 
Backport is needed for cosmics data taking.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1052.0,1052.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
backport of #40664

**Comment by tvami** [comment]
+1
 * tests pass, master PR is in the IBs

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 kind ping for a review of this ~ verbatim backport of https://github.com/cms-sw/cmssw/pull/40664. 
The only differences are due to the fact that https://github.com/cms-sw/cmssw/pull/40664 piggy-backed on https://github.com/cms-sw/cmssw/pull/40661 for some of the new workflow steps, while here they are included directly in the commits proposed. 
Please let us know if you agree (as a reminder this would be great to have integrated in time for the CRAFT data-taking later on this year).

**Comment by kskovpen** [comment]
+pdmv

**Comment by tvami** [comment]
@cms-sw/orp-l2 we are essentially fully signed

**Comment by perrotta** [comment]
The following lines are missing from #40661:
- https://github.com/cms-sw/cmssw/pull/40661/files#diff-f75558c662010a045624d46bdaf1f6de6af770742496c79146d0b81455117588R23-R24 (definition of the wf 1005.0)
- https://github.com/cms-sw/cmssw/pull/40661/files#diff-b0dce787f15ea8526a7b5585e797ba4b9e17ba829550c8283b5b5f97cba58b04R3131-R3132

Could you please comment about those differences?

**Comment by mmusich** [comment]
> Could you please comment about those differences?

See https://github.com/cms-sw/cmssw/pull/40734#issuecomment-1425535709

**Comment by perrotta** [comment]
+1
- Backport of https://github.com/cms-sw/cmssw/pull/40664 and most of the workflows steps from https://github.com/cms-sw/cmssw/pull/40661

**Pull request merged**
