### PR TITLE
Alter VID tools to check for already existing ID Definitions when being switched on (75X)

### PR DESCRIPTION
**Pull request by lgray**
Forward port of #10434

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
please test

Trying again now since other tests seem to be passing...

**Comment by lgray** [comment]
ok... tests died here... resubmitting...

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
hmmm...

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
