### PR TITLE
added esConsumes to modules in EventFilter/CastorRawToDigi

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 2 modules

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
These changes were made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Review by slava77 — COMMENTED** [review]
as in #30153
please merge contents of the header files into the .cc

- EventFilter/CastorRawToDigi/plugins/CastorDigiToRaw.h into EventFilter/CastorRawToDigi/plugins/CastorDigiToRaw.cc
- EventFilter/CastorRawToDigi/plugins/CastorRawToDigi.h to EventFilter/CastorRawToDigi/plugins/CastorRawToDigi.cc

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30162	a1724fd 
- code changes are in line with the PR title/description 
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by silviodonato** [comment]
+1

**Pull request merged**
