### PR TITLE
Fix Wnan-infinity-disabled warnings in RecoTracker/PixelSeeding

### LINKED ISSUE #45524: [CLANG] Use of NaN is undefined behavior in RecoTracker/PixelSeeding
CLANG complains about usage of `std::isnan` in RecoTracker/PixelSeeding due to the code being compiler with `-ffast-math`:

```
In file included from src/RecoTracker/PixelSeeding/plugins/CAHitNtupletGeneratorKernels.cc:3:
  src/RecoTracker/PixelSeeding/plugins/CAHitNtupletGeneratorKernelsImpl.h:485:18: warning: use of NaN is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
   485 |         isNaN |= std::isnan(tracks_view[it].state()(i));
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/RecoTracker/PixelSeeding/plugins/CAHitNtupletGeneratorKernels.cc:152:3: note: in instantiation of function template specialization 'caHitNtupletGeneratorKernels::kernel_classifyTracks<pixelTopology::Phase1>' requested here
  152 |   kernel_classifyTracks<TrackerTraits>(tracks_view, this->params_.qualityCuts_);
      |   ^
```

```
In file included from src/RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGeneratorKernels.dev.cc:20:
  src/RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGeneratorKernelsImpl.h:525:20: warning: use of NaN is undefined behavior due to the currently enabled floating-point options [-Wnan-infinity-disabled]
   525 |           isNaN |= std::isnan(tracks_view[it].state()(i));
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/invoke.h:61:14: note: in instantiation of function template specialization 'alpaka_serial_sync::caHitNtupletGeneratorKernels::Kernel_classifyTracks<pixelTopology::Phase1>::operator()<alpaka::AccCpuSerial<std::integral_constant<unsigned long, 1>, unsigned int>, void>' requested here
   61 |     { return std::forward<_Fn>(__f)(std::forward<_Args>(__args)...); }
      |              ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/alpaka/1.1.0-0a6641b4bfdf883c8da5b9e8620be504/include/alpaka/queue/QueueGenericThreadsBlocking.hpp:135:17: note: in instantiation of member function 'alpaka::TaskKernelCpuSerial<std::integral_constant<unsigned long, 1>, unsigned int, alpaka_serial_sync::caHitNtupletGeneratorKernels::Kernel_classifyTracks<pixelTopology::Phase1>, reco::TrackSoA<pixelTopology::Phase1>::Layout<>::ViewTemplateFreeParams<128, false, true, true> &, const pixelTrack::QualityCutsT<pixelTopology::Phase1> &>::operator()' requested here
  135 |                 task();
      |                 ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/alpaka/1.1.0-0a6641b4bfdf883c8da5b9e8620be504/include/alpaka/queue/Traits.hpp:49:54: note: in instantiation of member function 'alpaka::trait::Enqueue<alpaka::QueueGenericThreadsBlocking<alpaka::DevCpu>, alpaka::TaskKernelCpuSerial<std::integral_constant<unsigned long, 1>, unsigned int, alpaka_serial_sync::caHitNtupletGeneratorKernels::Kernel_classifyTracks<pixelTopology::Phase1>, reco::TrackSoA<pixelTopology::Phase1>::Layout<>::ViewTemplateFreeParams<128, false, true, true> &, const pixelTrack::QualityCutsT<pixelTopology::Phase1> &>>::enqueue' requested here
   49 |         trait::Enqueue<TQueue, std::decay_t<TTask>>::enqueue(queue, std::forward<TTask>(task));
      |                                                      ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/alpaka/1.1.0-0a6641b4bfdf883c8da5b9e8620be504/include/alpaka/kernel/Traits.hpp:312:9: note: in instantiation of function template specialization 'alpaka::enqueue<alpaka::QueueGenericThreadsBlocking<alpaka::DevCpu>, alpaka::TaskKernelCpuSerial<std::integral_constant<unsigned long, 1>, unsigned int, alpaka_serial_sync::caHitNtupletGeneratorKernels::Kernel_classifyTracks<pixelTopology::Phase1>, reco::TrackSoA<pixelTopology::Phase1>::Layout<>::ViewTemplateFreeParams<128, false, true, true> &, const pixelTrack::QualityCutsT<pixelTopology::Phase1> &>>' requested here
  312 |         enqueue(queue, createTaskKernel<TAcc>(workDiv, kernelFnObj, std::forward<TArgs>(args)...));
      |         ^
src/RecoTracker/PixelSeeding/plugins/alpaka/CAHitNtupletGeneratorKernels.dev.cc:378:13: note: in instantiation of function template specialization 'alpaka::exec<alpaka::AccCpuSerial<std::integral_constant<unsigned long, 1>, unsigned int>, alpaka::QueueGenericThreadsBlocking<alpaka::DevCpu>, alpaka::WorkDivMembers<std::integral_constant<unsigned long, 1>, unsigned int>, alpaka_serial_sync::caHitNtupletGeneratorKernels::Kernel_classifyTracks<pixelTopology::Phase1>, reco::TrackSoA<pixelTopology::Phase1>::Layout<>::ViewTemplateFreeParams<128, false, true, true> &, const pixelTrack::QualityCutsT<pixelTopology::Phase1> &>' requested here
  378 |     alpaka::exec<Acc1D>(
      |             ^
```

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:
Fixes https://github.com/cms-sw/cmssw/issues/45524 as suggested by @makortel in https://github.com/cms-sw/cmssw/issues/45524#issuecomment-2243055894

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test

run standard tests too

**Comment by jfernan2** [comment]
Even if unrelated, I'd like to know the origin of the RECO changes seen in the results and all the lines introduced in the logs. I am digging into the details, but if somebody has an explanation is welcomed

**Comment by smuzaffar** [comment]
@jfernan2 , you might be looking  at the [CLANG vs Default IB reco changes](https://github.com/cms-sw/cmssw/pull/45542#issuecomment-2248668171). These are expected as we are comparing GCC12 vs llvm 18 buildof cmssw. Standard Comparison here https://github.com/cms-sw/cmssw/pull/45542#issuecomment-2248434146 looks good ... right?

**Comment by jfernan2** [comment]
All right, thanks @smuzaffar  my bad. Thank you

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
ignore tests-rejected with external-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
