### PR TITLE
Phase2 workflow updates (add D14, D12 in short matrix, new OOT PU settings, Timing)

### PR DESCRIPTION
**Pull request by davidlange6**
#18373 plus move the if (timing) into the place where the workflow details are defined.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test
(not sure I understand this one)

**Comment by kpedro88** [comment]
-1
@davidlange6 this definitely does not accomplish what I was trying to accomplish. Let me see if I can use this as a starting point to come up with something acceptable to both of us.

**Comment by davidlange6** [comment]
ok, let me know if I can help - i thought I had successfully gotten the same output of runTheMatrix.py -w upgrade -l all -ne 
(aside from some extra workflows)

**Pull request closed without merging**
