### PR TITLE
[94X] Fix thread safety warnings in 'Alignment/MillePedeAlignmentAlgorithm'.

### PR DESCRIPTION
**Pull request by ghellwig**
Should fix all thread-safety warnings issued by the static analyzer in this package.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
hold
will add a fix tomorrow for a forgotten warning in this package

**Comment by ghellwig** [comment]
unhold

**Comment by ghellwig** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
