### PR TITLE
add `hltPrintMenuVersions` and utilities for HLT-menu spreadsheets

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR adds a few utilities related to the maintenance of the HLT menus.

 - `hltPrintMenuVersions` is a modified version of a script shared by @silviodonato to print to stdout metadata ("save comment" and "release template") of each version of a given HLT menu in ConfDB. I have added some command-line options to it using `argparse` (see `--help` for more info). Some examples below.
   ```bash
   hltPrintMenuVersions /dev/CMSSW_13_2_0/Fake2 -c 'cms_hlt_v3_r/convertMe!@cmsr'
   hltPrintMenuVersions /dev/CMSSW_13_2_0/Fake2 --db run3                        
   hltPrintMenuVersions /dev/CMSSW_10_0_0/Fake2 --db run2
   hltPrintMenuVersions /cdaq/special/PilotBeamTest2021/Circulating --db adg                        
   ```

 - Upon the release of a new HLT menu for data-taking (or MC production), TSG produces a spreadsheet which contains information on the content of the menu. The tools used to create this spreadsheet are added in this PR to `HLTrigger/Configuration/scripts/utils` (see the readme file in `scripts/utils` for further details).

Unit tests for `hltPrintMenuVersions` and `hltMenuContentToCSVs` are included. (These new tests rely on connecting to ConfDB, so I fear they might occasionally fail due to connection glitches, based on what I remember from https://github.com/cms-sw/cmssw/issues/37598#issuecomment-1326628334.)

#### PR validation:

Manual tests (and the new unit tests pass).

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

A backport is not necessary, but this PR could be backported down to the release cycle used for HLT-menu development (i.e. `13_2_X`) if it is useful.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * this PR adds few utils needed from STORM for day-to-day work. They don't affect any production workflow in any way.
   * thanks @missirol !

**Comment by aandvalenzuela** [comment]
Hello,

The newly introduced test `test_hltPrintMenuVersions` is failing in `aarch64` ([CMSSW_13_3_X_2023-10-09-2300](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc11/CMSSW_13_3_X_2023-10-09-2300/unitTestLogs/HLTrigger/Configuration#/136-136)) due to:
```
Failure 'hltPrintMenuVersions /dev/CMSSW_13_0_0/Fake2': status 1
=== Log File ==========
HLT Configuration: /dev/CMSSW_13_0_0/Fake2 (database = "run3")

Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02806/el8_aarch64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-10-09-2300/bin/el8_aarch64_gcc11/hltPrintMenuVersions", line 130, in <module>
    hltMenuVersions = getHLTMenuVersions(
  File "/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02806/el8_aarch64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-10-09-2300/bin/el8_aarch64_gcc11/hltPrintMenuVersions", line 10, in getHLTMenuVersions
    conn = cx_Oracle.connect(connect_string)
cx_Oracle.DatabaseError: DPI-1072: the Oracle Client library version is unsupported
=== End of Log File ===
```
If I am not mistaken, oracle version for `aarch64` is different from `amd64` and it is defined at https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/oracle.spec#L6.
Could you please have a look at the issue?

Many thanks,
Andrea.

**Comment by mmusich** [comment]
>  Could you please have a look at the issue?

is it acceptable to skip the unit test under this architecture? These scripts are used only from STORM during menu integration and we certainly won't run them in "exotic" architectures. Also tagging @cms-sw/core-l2 for an opinion.

**Comment by missirol** [comment]
>  Could you please have a look at the issue?

Thanks, @aandvalenzuela . I had a look, but I didn't find the solution. I opened #42975 to follow up.

**Comment by makortel** [comment]
> > Could you please have a look at the issue?
> 
> is it acceptable to skip the unit test under this architecture? These scripts are used only from STORM during menu integration and we certainly won't run them in "exotic" architectures. Also tagging @cms-sw/core-l2 for an opinion.

If HLT considers the functionality being tested as not necessary for ARM (or non-x86) CPUs, feel free to disable the test.

**Pull request merged**
