### PR TITLE
Strip hit eff lumi

### PR DESCRIPTION
**Pull request by jlagram**
Updates in the CalibTracker/SiStripHitEfficiency module. It is mainly to allow producing efficiency results as a function of the instantaneous luminosity.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
the error:
```
----- Begin Fatal Exception 10-Nov-2016 10:37:34 CET-----------------------
An exception of category 'DatabaseError ' occurred while
   [0] Processing run: 160960
   [1] Calling global beginRun for module LumiProducer/'lumiProducer'
Exception Message:
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 83 on chan 2 failed at Thu Nov 10 10:37:34 2016: -8 [payload.c:101]: Server signalled payload error 1: LumiProd java.sql.SQLException: ORA-00942: table or view does not exist at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:456)) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )
----- End Fatal Exception -------------------------------------------------
```

is unrelated to this PR (see [this thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2735.html) )

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
