### PR TITLE
increase tollerance to make space for shifted FPIX

### PR DESCRIPTION
**Pull request by VinInn**
took the opportunity to upgrade to c++11

### CODE REVIEW

**Comment by VinInn** [comment]
Have not run tests...
if ok, we will port to 74x and 75x

**Comment by VinInn** [comment]
@cmsbuild , please test
when done it should be forward ported.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@VinInn 
thanks for the fix!
@frmeier @tlampen this is something interesting for FPIX alignment

**Comment by frmeier** [comment]
@VinInn 
thanks for the fix. Wouldn't it be worth to have the limits configurable, default would be 1 and 2 cm, respectively? Or too much overload? Your are in a better position to judge.
@diguida, @mmusich thanks for pointing us to it.

**Comment by VinInn** [comment]
difficult to percolate a config in this place.
If we need to fix, we simply have to build left and right independently.
Easy to do, long to debug and validate...

**Comment by davidlange6** [comment]
@nclopezo - could you restart these tests? They seem stuck

**Comment by nclopezo** [comment]
ok, I restarted them.

**Comment by VinInn** [comment]
the above error is spurious

**Comment by slava77** [comment]
@cmsbuild please test
trying to get rid of the spurious error by rerunning

**Comment by slava77** [comment]
I'm testing this locally

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8174	 3c7c54f

tested in CMSSW_7_4_0_pre8 /test area sign527, with a cherry-pick/
with higher statistics samples comparisons show no differences in monitored quantities (expected result for the MC/data used in the tests)

**Pull request merged**
