### PR TITLE
PR for adding the cfi of HITrackClusterRemover.cc for ConfDB use in 74

### PR DESCRIPTION
**Pull request by ginnocen**
Hello, 

We would ask to PR the following modification in order to be able to use the HITrackClusterRemover
in ConfDB for HLT tracking. The PR consist of the corresponding cfi file and a small modification in the producer as a protection in case of null string in the oldClusterRemovalInfo.

Thanks, Cheers, Gian Michele

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1
we do not expect any changes needed for HI algorithms in 74X.
HI data and MC processing will happen in 75X (both online and offline).

complain if there is a need for 74X

**Comment by cvuosalo** [comment]
+1

For #12220 c2d44edce0de7a7263f58ec7480380350dcff436

Adding Python cfi for HITrackClusterRemover.cc for ConfDB use. There should be no change in monitored quantities. #12221 and #12222 are the 75X and 76X versions of this PR, and the latter has been approved by Reco.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-10-31-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
