### PR TITLE
2017 Dev Scenario with Detailed Cavern 

### PR DESCRIPTION
**Pull request by ianna**
This is a first attempt to introduce more detailed cavern description from Fluka. Eventually, it will be integrated in a new Phase 2 scenario for neutron background simulation for the Muon TDR.

* Add cavern description from Fluka by Alice Magnani
* Fix major overlaps

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by davidlange6** [comment]
Hi @ianna
I propose that this development stay in phase2 scenarios for now (maybe even a new phase2 scenario)

**Comment by ianna** [comment]
@davidlange6 - It's just easier to do it this way. The changes are introduced in new files, hence it does not matter which scenario&name is used.

Next step will be its migration to 2023:
* existing dictionary file will have to modified
* a new scenario generated and introduced in configurations for workflows - to be discussed
* overlaps in 2023 checked and if exist fixed 
* workflows added - to be discussed

I'll do it myself while @amagani will continue in parallel starting from this PR.

**Comment by kpedro88** [comment]
There is a "common" dict for 2023 geometry generation - a new version of this could be made, with a corresponding new workflow. (The "common" dict should also be added in the README in Configuration/Geometry - I hadn't included it because so far it has no alternate versions.)

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - yep, thanks!

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
superseded by https://github.com/cms-sw/cmssw/pull/17674

**Pull request closed without merging**
