### PR TITLE
73X add pT hat and eventID info to pileup summary

### PR DESCRIPTION
**Pull request by mdhildreth**
Backport of similar changes from 74X, requested by TSG.

### CODE REVIEW

**Comment by mdhildreth** [comment]
Needs a couple FastSim mods still - I forgot...

**Comment by mdhildreth** [comment]
+1

**Comment by mdhildreth** [comment]
@cmsbuild please retest

**Comment by mdhildreth** [comment]
test failures seem to have nothing to do with code modifications. (2011 minbias crashing?)  Many tests marked as failed don't seem to have failed either... ???

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
