### PR TITLE
First integration of Pixel Alignment of large structures in PCL - updated (76X) 

### PR DESCRIPTION
**Pull request by cerminar**
This updates and supersedes PR #10449 migrating all the newly introduced modules to consumes and getByToken.

This PR integrates the alignment of the pixel large structures as a
new PCL workflow for Tier0.
There is no code change to any production workflow, only the alca
configurations are affected by the changes.

The new workflow has been integrated in the relval 1001 (which now has
one more step).

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1
as https://github.com/cms-sw/cmssw/pull/10449 fixing consumes

**Comment by ggovi** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
@cerminar  - looks like this PR now has merge conflicts - could you rebase (then I can merge)

**Comment by cerminar** [comment]
@davidlange6 done!
Thanks.

**Comment by cerminar** [comment]
Do we actually need to go though the full list of signatures given the fact that this was just a rebase of a fully signed PR?

**Comment by mmusich** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
