### PR TITLE
Replace LinkDef file witl XML selection file in PhysicsTools/TagAndProbe

### PR DESCRIPTION
**Pull request by wmtan**
It has been decided to replace LinkDef files with XML selection files.
This PR does this for the LinkDef files that were in PhysicsTools/TagAndProbe

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by wmtan** [comment]
@cmsbuild The three failing add-on tests fail in the base IB, so the failures are not caused by this PR.
Please mark the tests as approved.

**Comment by wmtan** [comment]
@please test

**Comment by wmtan** [comment]
@vadler, @monttj
Please sign or provide a reason for not signing.

**Pull request merged**
