### PR TITLE
DDAngular: Minor bug fix of a debug message

### PR DESCRIPTION
**Pull request by cvuosalo**
#### PR description:

Minor debug message bug fix. The message was being incorrectly triggered because the index of an array rather than the array value was being checked. This PR puts in the correct check.

#### PR validation:

Test config was run to show the message no longer inappropriately appears.

No backport.

### CODE REVIEW

**Comment by cvuosalo** [comment]
type bugfix

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
