### PR TITLE
Fix undefined references

### PR DESCRIPTION
**Pull request by davidlt**
The latest UBSAN IB revealed a couple more packages failing with missing dependencies.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21484	4ce9bf0
- technical buildfile updates
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
merge

**Pull request merged**
