### PR TITLE
Prescale access for stage-2 environment (81X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Prescale access for stage-2 environment (81X)
It makes L1TGlobalUtil (stage-2) similar to L1GtUtils (legacy/stage-1) incl. helper class etc.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
Looking at jenkins logs:

134.911 (2015) generates new errors (below) is this a problem with the DQM module configuration?
```
%MSG-e HLTPrescaleProvider:  EwkMuDQM:ewkMuDQM 03-May-2016 11:22:51 CEST  Run: 256677 Event: 436229045
 Using processName 'HLT': Error in determining HLT prescale set index from L1 data using L1GtUtils: Tech/Phys error = 210110/210110 Tech/Phys psfsi = -1/-1
```

**Comment by Martin-Grunewald** [comment]
Yes, sort of: this is originally stage-1 data which gets process through L1REPACK+reHLT and reRECO, while the DQM modules look for the original HLT process, but the corresponding unpackers are not run as the L1REPACK/reHLT/reRECO are stage-2. So either the DQM modules should be configured to look at the processes with name reHLT/reRECO, or some stage-1 unpacking would still needed to be added (which is technically impossible of course, as the unpacking is already
there but of course stage-2).

**Comment by slava77** [comment]
(being superficial, not looking at details of the implementation)
Is this error message a result of the new feature added that doesn't work (yet) for 2015 data?
Or is this a result of this PR breaking something that was working in the baseline?

**Comment by Martin-Grunewald** [comment]
It will never work and it was silently failing so far! At least now you get an error message.
The issue is that you need to configure DQM based on BOTH the stuff you are running (2016
setup) and the original data source (here 2015 versus 2016). If you want the same config, the DQM
part should use "HLT" if the data is 2016, and "reHLT" if it has been run through L1REPACK to make it look like 2016 (where reHLT is the processName of HLT run on the L1REPACKed data).
If DQM shoudl really look at the original 2015 HLT process (then why reHLT/reRECO??), then you
should run a 2015 25ns workflow on the file.

**Comment by slava77** [comment]
@vanbesien please take a note

**Comment by Martin-Grunewald** [comment]
BTW, there are some ither complainst about use of 'RECO' as process name: as the input file
is RAW, RECO (presumably meant to be the original RECO process) has not run on that as it comes after RAW, so it also a wrong DQM configuration for this case.

**Comment by slava77** [comment]
For the RECO process not found, it could be silenced: the code tries both RECO and reRECO
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_0_pre3/DQMOffline/JetMET/src/METAnalyzer.cc#L1741
```python
    FilterResultsLabelMiniAOD = cms.InputTag("TriggerResults","","RECO"),
    FilterResultsLabelMiniAOD2 = cms.InputTag("TriggerResults","","reRECO"),
```

**Comment by Martin-Grunewald** [comment]
How? The ConfigProvider does not know that you'll try another version.
So I can not remove the message in the ConfigProvider as that would affect true misconfigs which do not retry a 2nd alternative.

**Comment by slava77** [comment]
is there a way to construct it in a less noisy state, so that it doesn't issue the logError?

**Comment by davidlange6** [comment]
without looking at this code, I could suggest that one could either a) provide a list of process names or b) use error codes to allow the failure and printout into separate functions (so the user could call a error code interpreter after exhausting the possibilities that they have)

**Comment by slava77** [comment]
looking at jenkins:
- run 1 workflows 1000 (pp) and 140.53 (HI) have changes in particleFlowBlock (and propagate downstream). This looks random ... looks like recent updates pulled in some undefined variables  @lgray  (an equivalent PR test in 80X doesn't show any differences in jenkins in PF) https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-05-02-2300+14312/13776/validateJR/all_OldVSNew_RunMinBias2011Awf1000p0/

- EWK DQM plots are actually broken
wf134911_ewkdqm_ele_detain
I think that this should be fixed before this PR can go in.

**Comment by Martin-Grunewald** [comment]
Well, this is not really possible as then internally I'd have to call every function available first to see whether there is an error, and for which function. Also, calling it with RECO or HLT may be perfectly fine and correct if (later) you do NOT want the prescales.

**Comment by Martin-Grunewald** [comment]
```
I think that this should be fixed before this PR can go in.
```
Are you talking to me? Hopefully not because I am not a DQM expert.

**Comment by Martin-Grunewald** [comment]
The proper way is to configure the processName correctly, depending on workflow, rather than
just trying two and going with the one that somehow works.

**Comment by slava77** [comment]
assign dqm

the new feature introduced in this PR has broken functionality of EWK DQM.
So, DQM signature will be needed.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14312	ec3a942
- changes in RECO-related code are only to pass stage2-related input tags in PhysicsTools/PatAlgos/python/triggerLayer1/triggerProducer_cfi.py
- jenkins tests pass and comparisons with baseline show no reco-related differences related to this PR
    - brief note on changes unrelated to reco is at https://github.com/cms-sw/cmssw/pull/14312#issuecomment-216552894

**Comment by Martin-Grunewald** [comment]
There are two other issues: this workflow runs UnScheduled, and it  does contain the gtDigis and the gtStage2Digis module (the stage1 and stage2 unpacker), the latter is in itself weird: Either the RAW data is stage-1 or stage-2, one can not think of it as being both!
And then it depends on whether the gtDigis module is run before or after the ewkMu/ElecDQM modules. If the gtDigis is run after, then the product needed to find the prescales is not there
and you get the prescaler error message.

**Comment by slava77** [comment]
both stage1 and stage2 products required may be a result of incomplete era setup/switchover in the DQM modules.

**Comment by fwyzard** [comment]
@davidlange6 
> I could suggest that one could either a) provide a list of process names or b) use error codes to allow the failure and printout into separate functions (so the user could call a error code interpreter after exhausting the possibilities that they have)

@Martin-Grunewald 
> The proper way is to configure the processName correctly, depending on workflow, rather than
just trying two and going with the one that somehow works.

I completely agree with Martin. In fact this
`
    FilterResultsLabelMiniAOD = cms.InputTag("TriggerResults","","RECO"),
    FilterResultsLabelMiniAOD2 = cms.InputTag("TriggerResults","","reRECO"),
`
is not a very smart way of configuring things.

**Comment by davidlange6** [comment]
Sounds good. Getting the appropriate process name is certainly a better solution.


On 03 May 2016, at 18:21, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6>

I could suggest that one could either a) provide a list of process names or b) use error codes to allow the failure and printout into separate functions (so the user could call a error code interpreter after exhausting the possibilities that they have)

@Martin-Grunewald<https://github.com/Martin-Grunewald>

The proper way is to configure the processName correctly, depending on workflow, rather than
just trying two and going with the one that somehow works.

I completely agree with Martin. In fact this

FilterResultsLabelMiniAOD = cms.InputTag("TriggerResults","","RECO"),
FilterResultsLabelMiniAOD2 = cms.InputTag("TriggerResults","","reRECO"),

is not a very smart way of configuring things.

**Comment by vanbesien** [comment]
@dmitrijus 
Seems something was broken and DQM plots are not showing up anymore. Can you look into this and figure out where it goes wrong?

**Comment by slava77** [comment]
@Martin-Grunewald 
are there going to be more changes to this PR?
(there was a commit pushed, but you haven't triggered tests)

**Comment by Martin-Grunewald** [comment]
yes...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@slava77 
This will not fix the DQM issue.... that has to be fixed on the DQM side.

**Comment by slava77** [comment]
On 5/5/16 12:25 PM, Martin Grunewald wrote:
> @slava77 <https://github.com/slava77>
> This will not fix the DQM issue.... that has to be fixed on the DQM side.

OK, with the dqm signature needed for this PR, I'm leaving it to DQM to
decide what to do.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14312	1737d36
- there was no change related to reco since the last signoff at ec3a942
- jenkins tests pass; the /Ewk DQM plots mentioned earlier are still empty

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@rekovic @mulhearn 
Please sign asap!

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@dmitrijus
Can you please now sign this PR as well?
Thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Who signs for "analysis" these days?
Could you please do so asap?
Thanks!

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@Martin-Grunewald - is @gpetruc aware of what changes are apparently needed in PatTriggerProducer due to this PR? (given the new error messages introduced)

**Comment by gpetruc** [comment]
Hi,
I tested the 80X version of this (#14336) on 2016 data and it was ok, it was getting the proper prescales for HLT unlike what's currently in the release.
Giovanni

**Comment by Martin-Grunewald** [comment]
@davidlange6 @gpetruc 
Yes - I just forwarded you an e-mail exchange.

**Comment by Martin-Grunewald** [comment]
For the record
```
 Subject: Re: PatTriggerProducer adapt to stage2

Hi,

Please have a look at:
80X: https://github.com/cms-sw/cmssw/pull/14336
81X: https://github.com/cms-sw/cmssw/pull/14312
and PhysicsTools/PatAlgos/python/triggerLayer1/triggerProducer_cfi.py
in there.

What needs to be done further:

PATTriggerProducer is calling L1GtUtils (stage-1/legacy).
For stage-2 this is replaced by L1TGlobalUtil instead,
which has a different interface to the user/client.

legact/stage-1 vs stage-2 should become configurable, and/or
one could use the new accessor "l1tType()" of the
HLTConfigProvider/HLTPrescaleProvider (in the above PRs) 
to find out what it is: 0=unknown, 1=legacy/stage-1, 2=stage-2.
This requires that the processName used is the correct one
for the process you want to analyse.

And there I think is a general problem: typically the processName
is "HLT" but it should be "reHLT" if one had been rerunning the
HLT and wants to run PATTriggerProducer on that HLT (use case of
data taken in 2015 with "HLT" stage-1 25ns, reprocessed through
the 2016 HLT using stage-2 L1T re-emulation). I believe this is
not really switched properly at all in relvals.

Relvals using HLT:@relval2016 and era Run2_2016 are configured
to use stage-2 L1T and corresponding HLT.

Best regards

Martin

On Wed, 11 May 2016, Slava Krutelyov wrote:

> Hi Giovanni,
> 
> On 5/11/16 12:11 PM, Giovanni Petrucciani wrote:
> > Hi,
> > 
> > I can check it for miniAOD production,
> 
> Thank you.
> 
> > 
> > My assumptions would be that we have to deal with 4 scenarios:
> > 1) MC with --era Run2_25ns : as in 2015
> > 2) MC with --era Run2_2016 : stage2
> > 3) 2016 Data prompt: stage 2
> > 4) 2016 Data re-reco: stage 2
> > 5) 2015 Data : as in 2015
> > 
> > Is it ok?
> > Can somebody provide a 80X MC file of scenario (2) with non-empty
> > trigger? (for testing (1) I suppose I could use 76X MC)
> 
> I think the latest 80X and/or 81X run2 workflows in MC are running
> stage2 emulator,
> but I'm not sure what's done at HLT.
> 
> > IMHO the important cases to check are (2) and (3, 4) since (1) and (5)
> > will only kick in if we'll use 80X on 2015 data.
> > Will data re-reco use eras as in MC?
> > 
> 
> These updates should at least not break the older workflows,
> they should keep running.
> It's a part of relval matrix.
> 
>               --slava
> 
> 
> > Giovanni
> > 
> > 
> > On Wed, May 11, 2016 at 11:42 AM, Slava Krutelyov <slava77@fnal.gov
> > <mailto:slava77@fnal.gov>> wrote:
> > 
> >     Hi Giovanni,
> > 
> >     Martin mentioned in the ORP yesterday that the PatTriggerProducer
> >     should be updated to appropriately pick up stage1 or stage2 or older
> >     run1 trigger objects.
> >     I understand that different options, stage2 more timely, has a
different
> >     class and interface to read the information from.
> >     Different values/options can be configured with eras to pick up the
> >     correct ones.
> >     Are you available to check what needs to be done and implement the
> >     changes?
> > 
> >     Please let me know.
> > 
> >     Thank you.
> > 
> >                     --slava
> > 
> > 
> > 
> >     --
```

**Comment by davidlange6** [comment]
i mean specifically 

%MSG-e HLTPrescaleProvider:  PATTriggerProducer:patTrigger  19-May-2016 20:50:36 CEST Run: 1 Event: 1
 Error in determining L1T prescale for HLT path: 'HLT_Mu3_PFJet40_v1' has multiple L1TSeed modules, 2, with L1T seeds: 'L1_SingleMu3' * 'L1_SingleJet35'. (Note: at most one L1TSeed module is allowed for a proper determination of the L1T prescale!)

**Comment by Martin-Grunewald** [comment]
This message is limited to at most 2 per instance. It is up to the client (PATTriggerProducer)
to properly check first and call the code for these special cases of triggers having several L1T seed modules.

**Comment by gpetruc** [comment]
Yeah.

Funny enough, I'm even the one who coded that HLT path.

The prescale code at the moment can't understand that the  L1_SingleJet35
instance used in the HLT_Mu3_PFJet40_v1 is taken from the object map and
not from the GT digis, and so it's bypassing masks and prescales.
In principle, it could do it by looking at the input tag used by the
HLTL1TSeed module (though that would mean putting the name of the digis
collection in the code, not a particularly nice solution).

In any case, all this affects the L1 prescales, which are currently not
available anyway because the corresponding data is not yet in conddb.
When the proper developments to access L1 prescales in CMSSW will be done,
we can fix this.

Ciao,

Giovanni

**Comment by davidlange6** [comment]
ok, good enough for 81x

**Comment by davidlange6** [comment]
@mulhearn @gpetruc - I am reminded that for MC there is no "fix" needed to proceed as we want prescales=1. So, in order to get the MC release in shape, lets not couple the prescales from L1 with this fix. Thanks!

**Pull request merged**
