### PR TITLE
EMTF 2017 PR #3 - 2017 Unpacker

### PR DESCRIPTION
**Pull request by abrinke1**
Part 3 of set of PRs following PR #19743

Updated EMTF unpacker including several major improvements:
  * Input link monitoring in EMTFBlockCounters.cc
  * Unpack CPPF output in EMTFBlockRPC.cc
  * Significantly improved hit-to-track matching in EMTFBlockSP.cc

Still outputs empty collections of EMTFHit2016 and EMTFTrack2016 so we don't break the DQM sequences.

Changes grouped as follows:
DataFormats/L1TMuon/interface/EMTF/*.h
  * Updated unpacked objects to mirror changes in RAW EMTF DAQ output

EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockX.cc
  * Updated unpacking functions

EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockX.h
  * All deleted, not needed; match convention used by other unpacker

L1Trigger/L1TMuonEndCap/interface/TrackTools.X
  * New helper functions

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by abrinke1** [comment]
Just added a commit to (hopefully) fix the un-initialized EMTFPtLut.  I say "hopefully" because it didn't cause a compile error or warning on lxplus in the first place.  @rekovic @davidlange6 do you know if the cmsbuild test will be triggered again automatically, or does someone need to manually restart the tests?

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by davidlange6** [comment]
hi @abrinke1 @rekovic - please rebase this to use CMSSW_9_3_X_2017-07-24-1100 where your step2 PR is merged. Thanks

**Comment by perrotta** [comment]
-1
wrong rebase

**Comment by abrinke1** [comment]
Yes, indeed ... the rebase did not do what I intended, working on a follow-up.

**Comment by kpedro88** [comment]
-1
http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by kpedro88** [comment]
@abrinke1 for my curiosity, could you tell me *exactly* what sequence of commands you entered which led to this state?

**Comment by abrinke1** [comment]
@kpedro88 Sorry, I'm not sure I recorded it exactly.  I *think* what I did was the following:

cmsrel CMSSW_9_3_0_pre1
cd CMSSW_9_3_X_2017-07-24-2300/src
cmsenv
git cms-init
git remote add cms-sw git@github.com:cms-sw/cmssw.git
git fetch cms-sw

git remote add abrinke1 git@github.com:abrinke1/cmssw.git
git fetch abrinke1
git cms-merge-topic -u abrinke1:EMTF_PR_2017_93X_part3

But I'm honestly not 100% positive ... I tried a few different things, and whatever the last thing I did was the worst :)

I'll probably just make a new branch and PR from there - I'm actually tweaking a couple of things in the code first, though.

**Comment by davidlange6** [comment]
seems this is obsolete?

**Comment by abrinke1** [comment]
Yes - moved on to PR #20006

**Pull request closed without merging**
