### PR TITLE
Fixing 75X HI AlCa 

### PR DESCRIPTION
**Pull request by mmusich**
As in #12213 fixing the AlCaRecoTriggerBits for HI2010.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
just to confirm this solves the issue reported in https://github.com/cms-sw/cmssw/pull/12213#issuecomment-153751819.
```
cmsrel CMSSW_7_5_X_2015-11-05-2300
cd CMSSW_7_5_X_2015-11-05-2300/src/
git cms-merge-topic 12259
cmsenv
runTheMatrix.py -l 140.51
```
yields:
```
140.51_RunHI2010+RunHI2010+REPACKHID+RECOHID11St3+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Nov  6 11:26:19 2015-date Fri Nov  6 11:15:14 2015; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

```

**Comment by fabozzi** [comment]
+1

**Comment by BetterWang** [comment]
Hi @deguio , what's the status of this PR? Thanks.

**Comment by deguio** [comment]
+1

**Pull request merged**
