### PR TITLE
boosted cleaning fix for 76x

### PR DESCRIPTION
**Pull request by dsrankin**
Fixing const_cast issue.
Please approve as soon as possible, needed for data taking.
@rappoccio @isando3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Also here: Could you please have a look at the jenkins tests of this PR - why they seem stuck?
Thanks!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
