### PR TITLE
Make stop/sbottom R-hadrons use the cloud model

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

This PR fixes a bug, namely that the stop/sbottom R-hadrons were not added in CustomPhysicsList from CMSSW_8_0_X, so they do not use the cloud model. Fix can be easily done by renaming is_Rhadron() to s_isgluinoHadron to reflect what the code is really doing and add the stop and sbottom to the CustomPhysicsList.
More details
https://indico.cern.ch/event/1012481/contributions/4248900/attachments/2198166/3716919/SlidesMCTests20210226.pdf
and
https://indico.cern.ch/event/963050/contributions/4051179/attachments/2116681/3565085/SlidesMCDebug20201006.pdf

#### PR validation:

Code compiles, physics validation done in the talks linked above

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This is not a backport, but a backport is planned

cc: @tadams16 @carolinecollard

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild, please abort test
* there will be failures in DQM timing reported in https://github.com/cms-sw/cmssw/issues/34445

**Comment by tvami** [comment]
@cmsbuild, please test with #34464

**Comment by tvami** [comment]
The addOn test failure doesn't seem to be connected to this PR, hlt_mc_HIon has nothing to do with R-hadron simulation.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
