### PR TITLE
[DD4hep] DDFilteredView current volume path and its copy numbers

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add an iterator accessor ```path``` that returns a path to a current node. Please, use it sparingly.
*  Add an iterator accessor ```copyNos``` that returns a vector of the volumes copy numbers along the path. The vector index indicates the volume level, e.g. an index 0 refers to the current volume copy number, an index 1 refers to the current volume's parent copy number and so on.

as requested by @bsunanda 

Note: none of the above is needed if the xml selection parts specified in more details.

#### PR validation:

See  ```DetectorDescription/DDCMS/test/DDFilteredView.cppunit.cc```

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@ianna @cvuosalo @silviodonato Can this PR be merged soon because calorimetric codes depend on this PR

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
