### PR TITLE
Change FEStatus flag labels in ECAL DQM [14_0_X]

### PR DESCRIPTION
**Pull request by kyungminparkdrums**
#### PR description:

This PR changes the flag labels of the FE Status plots in the ECAL DQM plot

*   FIFOFULL -> FORCEDFULLSUPP
*   FULLL1ADESYNC -> FIFOFULL

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is the backport to `14_0_X`, which is used in production at the moment. Master PR is #44402

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )
- P5 tests OK.

**Comment by antoniovilela** [comment]
> +1
> 
> * spurious differences seen from unstable WF `12834.7` (open issue [spurious differences in outputs of wf `12434.7` (was `11634.7`) #39803](https://github.com/cms-sw/cmssw/issues/39803) )
> * P5 tests OK.

Please always sign the master before the backport.
Thanks.

**Comment by antoniovilela** [comment]
The master PR is not yet signed.

**Comment by tjavaid** [comment]
> > +1
> > 
> > * spurious differences seen from unstable WF `12834.7` (open issue [spurious differences in outputs of wf `12434.7` (was `11634.7`) #39803](https://github.com/cms-sw/cmssw/issues/39803) )
> > * P5 tests OK.
> 
> Please always sign the master before the backport. Thanks.

Just signed. Thanks!

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
