### PR TITLE
[12_4_X] Introduce AlCaPPS_Run3 scenario

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38388

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38388

### CODE REVIEW

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
type ctpps

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38388

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+alca

**Pull request merged**
