### PR TITLE
implement a tracking particle associator with TrackCandidate and add trackCandidate branches in trackingNtuple

### PR DESCRIPTION
**Pull request by slava77**
- SimDataFormats/Associations: 
    - add alias template to simplify definition of `SimToRecoCollection*` and `RecoToSimCollection*` and removed its partial duplicate definition in TrackToTrackingParticleAssociator.h to keep everything just in TrackAssociation.h. The fully defined types should be the same, so no update should be necessary in the `classes*` files for the dictionaries. There are no use cases at this point for placing `SimToRecoCollectionTCandidate` and `RecoToSimCollectionTCandidate` in `edm::Event`; so, no dictionary is added for this.
    - changed `TrackToTrackingParticleAssociator::associateRecoToSim` arguments/interface from `Handle<TrackingParticleCollection` to `RefVector<TrackingParticleCollection` to be more in common with existing use cases for `reco::Tracks`
- SimTracker/TrackAssociatorProducers: improve templated methods in `QuickTrackAssociatorByHitsImpl` so that `reco::Track` and `TrackCandidate` have maximal overlap in implementation and minimize copy-pasted code
- Validation/RecoTrack: trackingNtuple updates
    - add `tcand_*` branches to provide access to `TrackCandidate` details (optional, enabled for extendedContent custom option). This should allow more straightforward debugging of track pattern recognition, in particular in mkFit. This data can also be used to train track candidate classification and allow removing candidates from the following final fit step (and save computation)
    - refactor mergeIters case (where built tracks are used as inputs) to provide access to per-iteration MVAs
    - add (global) hit positions for rechits as computed with the track-trajectory corrected CPEs to allow for hit position and residual analysis
    - cleanup the outdated use of `TransientTrackingRecHitBuilder` and use tracking hits directly. This is in a sense a somewhat late follow-up to #3344 

No changes are expected in the standard workflows.
If that is confirmed, there may be a backport to an older release (12_2_X where the TRK-Run3Winter22 are made, in case it's not practical to run on those inputs in 12_4_X)

### CODE REVIEW

**Comment by slava77** [comment]
@smuzaffar @makortel 
is `scramb code-checks-all` now supposed to cover everything including code-checks and code-format? or do I need to run those separately?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@slava77 , `scram b code-checks` runs `clang-tidy` for changed files while `code-checks-all` runs `clang-tidy` on all checkedout files. There are `code-format` and `code-format-all` to run the `clang-format`

**Comment by slava77** [comment]
> `scram b code-checks` runs `clang-tidy` for changed files

OK. In the end I have probably just missed the error when I ran code-checks locally.

**Comment by slava77** [comment]
> * Reco comparison results: 6 differences found in the comparisons
> * DQMHistoTests: Total failures: 14

as expected there are no relevant differences (apart for a few false-positives from the warning messages in PU workflows).

**Comment by emanueleusai** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
