### PR TITLE
Phase2-hgx358D Correct the XML file for scintillators in the V19 description of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the XML file for scintillators in the V19 description of HGCal geometry

#### PR validation:

Use the corrected version of the conversion code. The final checks will be made when the geometry codes are ready

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
