### PR TITLE
[Tracker Alignment] Miscellaneaneous updates to `Alignment/OfflineValidation` package [12_1_X]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This contains the combined backports of PRs #36236, https://github.com/cms-sw/cmssw/pull/36178, https://github.com/cms-sw/cmssw/pull/35983 and https://github.com/cms-sw/cmssw/pull/36017.
It would be very nice to have for the post-processing of the Fall 2021 LHC pilot beam data re-reco [PDMVRERECO-49](https://its.cern.ch/jira/browse/PDMVRERECO-49).

#### PR validation:

Private.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of #36236, https://github.com/cms-sw/cmssw/pull/36178, https://github.com/cms-sw/cmssw/pull/35983 and https://github.com/cms-sw/cmssw/pull/36017.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36236
backport of https://github.com/cms-sw/cmssw/pull/36178
backport of https://github.com/cms-sw/cmssw/pull/35983
backport of https://github.com/cms-sw/cmssw/pull/36017

**Comment by tvami** [comment]
+alca
 * diffs in MsgLogger only

**Comment by qliphy** [comment]
+1

**Pull request merged**
