### PR TITLE
remove evtgen plugin in Pythia8Interface 53X

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by mkirsano** [comment]
To be built against cmsdist #1926

**Comment by mkirsano** [comment]
There was this email:

There was an issue with git-cms-merge-topic you can see the log here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12189/5/git-merge-result

Is there a problem?
By the way, I have no access to the logs like above.

**Comment by degano** [comment]
@mkirsano I know, I'm using this PR to test also a new feature. The error was unrelated with the content of your PR.

**Comment by degano** [comment]
+1
I think we can ignore the above tests for this release.
The other tests where fine. The correct URL is this one:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12189/9/summary.html

**Comment by davidlange6** [comment]
@degano - could you go ahead and do the consistent merge?

**Comment by degano** [comment]
@davidlange6 Done here and here: cms-sw/cmsdist#1937

**Pull request merged**
