### PR TITLE
Hit assoc for phase2

### PR DESCRIPTION
**Pull request by wmtford**

### CODE REVIEW

**Comment by wmtford** [comment]
Modify TracerkHitAssociator to work with Phase 2 simHit collections.  Specifically, allow a collection to contain simHits from more than one subdetector.  SimHits are extracted from a map whose value is the vector of simHits and whose key is the collection index.  Previously the key was a pair (subDet, TofBin), which in Phase 2 is no longer one-to-one with the collection.  Now an additional map with this key points to the collection index.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
