### PR TITLE
Update L1 uGT menu to v5 and add payloads for GBRWrapperRcd for tracking MVA 

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v12) as [80X_mcRun2_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v12/80X_mcRun2_design_v11): 
  - update L1 uGT menu to v5 (dev_v5)
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v12) as [80X_mcRun2cosmics_startup_peak_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v12/80X_mcRun2cosmics_startup_peak_v11): 
  - update L1 uGT menu to v5 (dev_v5)
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v12) as [80X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v12/80X_mcRun2_asymptotic_v11): 
  - update L1 uGT menu to v5 (dev_v5)
- **RunII Startup scenario** : [80X_mcRun2_startup_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v12) as [80X_mcRun2_startup_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v12/80X_mcRun2_startup_v11): 
  - update L1 uGT menu to v5 (dev_v5)
## RunII data
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v8) as [80X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v8/80X_dataRun2_HLT_relval_v6): 
  - Adding 7 payloads for GBRWrapperRcd for tracking MVA 
  - update L1 uGT menu to v5 (dev_v5)
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v11) as [80X_dataRun2_HLT_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v11/80X_dataRun2_HLT_frozen_v10): 
  - Adding 7 payloads for GBRWrapperRcd for tracking MVA 
  - update L1 uGT menu to v5 (dev_v5)
- **RunII Offline relval processing** : [80X_dataRun2_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v7) as [80X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v7/80X_dataRun2_relval_v6): 
  - update L1 uGT menu to v5 (dev_v5)
## Upgrade
- **PhaseI design scenario** : [80X_upgrade2017_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v11) as [80X_upgrade2017_design_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v11/80X_upgrade2017_design_v10): 
  - update L1 uGT menu to v5 (dev_v5)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Changing the L1T menu from v4 to v5 requires an HLT update.

**Comment by mmusich** [comment]
@Martin-Grunewald I assume the new v5 menu is not compatible with the current HLT in release, namely few seeds available in v4 disappeared. Is my understanding correct?

**Comment by Martin-Grunewald** [comment]
Maybe this PR should stay at L1T v4 and a new PR for L1T v5?

**Comment by Martin-Grunewald** [comment]
Yes - so how to deal with this? Separate PRs - one including the other?

**Comment by mmusich** [comment]
@Martin-Grunewald in the end shouldn't everything be wrapped up in the same global tags? 
I understood from today's operations meeting that we need this to be in by today or so... @fwyzard

**Comment by mmusich** [comment]
@Martin-Grunewald I suggest you cherry-pick my commits to combine the GTs and the HLT menu. Does it sound a good option?

**Comment by Martin-Grunewald** [comment]
@mmusich - OK, fine with me, will do so with the HLT updated to v5!

**Comment by mmusich** [comment]
-1
superseded by #14099

**Pull request closed without merging**
