### PR TITLE
[13_0_x] PPS Pixel DQM: assign errors to right plots

### PR DESCRIPTION
**Pull request by fabferro**
**PR description:**

This PR is a bug fix in filling the plots in PPS Pixel DQM. Using the DAQ map, errors coming from pixels are assigned to the right detector plane instead of being put in a unidentified-detector plot, unless strictly necessary.

**PR validation:**

With matrix wfs 138.4 (run3) and 136.874 (run2) and with brand new 2023 data. Errors are now put inside the right plots.

This fix is needed for the data taking asap.

This is a backport of PR https://github.com/cms-sw/cmssw/pull/41649

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41649

**Comment by emanueleusai** [comment]
type ctpps

**Comment by emanueleusai** [comment]
please test

**Comment by syuvivida** [comment]
@fabferro @francescobrivio 
 Just to add more information, we tested this PR at p5 machines with the 13_0_X Global tag: 130X_dataRun3_HLT_v2 and jobs were running fine without crashes at the playback. You could also take a look at the [playback DQMGUI here](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=TrackingPixel;size=M;root=CTPPS/TrackingPixel;focus=;zoom=no;)

**Comment by francescobrivio** [comment]
Btw the discussion is actually ongoing in the master PR https://github.com/cms-sw/cmssw/pull/41649

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
