### PR TITLE
All In One tool update

### PR DESCRIPTION
**Pull request by hroskes**
Backport of #18749

Restructuring of the All In One validation tool

* Use the common track selection and refitting sequence
  * For offline validation and track splitting
  * Explicitly checked that process.dumpPython() is essentially unchanged from how it was before
* Extend the mechanism to create latex slides:
  * works for track splitting validation in addition to offline
  * include a summary table of important track quantities
  * more general mechanism to extend to other validations (but leave that for the next iteration)
* Several options that were useful for phase 1 startup
  * option to disable pixel quality flag, proxy forwarding, ...
* Large rearrangement of code to reduce duplication

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agreed

**Comment by ghellwig** [comment]
please test

**Comment by arunhep** [comment]
@hroskes 90X is closed for updates. 
please close this PR

**Pull request closed without merging**
