### PR TITLE
backport from 93X to 92X: - for neutral non-detectable exotics - send…

### PR DESCRIPTION
**Pull request by zhangzc11**
… their daughters to Geant4

### CODE REVIEW

**Comment by zhangzc11** [comment]
from 93X PR: https://github.com/cms-sw/cmssw/pull/20083

**Comment by zhangzc11** [comment]
@civanch could you please review and eventually approve this backport to 92X as well? we need this for the 2017 MC production.

**Comment by zhangzc11** [comment]
@civanch Dear Vladimir, could you please approve this backport to 93X asap? Thanks a lot!

**Comment by kmcdermo** [comment]
ping on this PR

**Comment by kmcdermo** [comment]
@civanch @davidlange6 any news on this backport?  Ideally this would be approved before the start of Part2 of the 2017 MC production...

**Comment by civanch** [comment]
@zhangzc11 , probably this PR may be closed because production is performed in 9_3_X releases, where the fix should be in.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
