### PR TITLE
deleting RivetHarvesting

### PR DESCRIPTION
**Pull request by efeyazgan**
Deleting RivetHarvesting not followed up after 2013.

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan this PR needs to be rebased

**Comment by slava77** [comment]
-1

 changes in EventFilter/SiStripRawToDigi/src/SiStripFEDBufferComponents.cc 
do not belong in this PR.

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
