### PR TITLE
ThePEGInterface: Changed HepMCConverter to original Herwig++ 2.7.1 ve…

### PR DESCRIPTION
**Pull request by mharrend**
…rsion to fix problems with b jet multiplicity

### CODE REVIEW

**Comment by bendavid** [comment]
Hi Marco,
Do we need to even keep a copy of the HepMCConvertor in the cmssw repository?  Can't we just directly call the class inside the herwig++/thepeg code?

**Comment by bendavid** [comment]
Also, since this pull request doesn't include any of the config changes, I guess you plan to either update
https://github.com/cms-sw/cmssw/pull/8696
or open a new pull request which replace that one?

**Comment by mharrend** [comment]
I am checking at the moment, if we really need a patched version of the
HepMC converter by creating a new sample with a removed HepMCConverter

I was thinking yes, since there was this additional part in the
HepMCConverter, which I also included in the modified original version:

> 	template<> struct HepMCTraits<HepMC::GenEvent> :
> public HepMCTraitsBase<
> HepMC::GenEvent, HepMC::GenParticle,
> HepMC::GenVertex, HepMC::Polarization,
> HepMC::PdfInfo> {};

Do you have any clue if we need this part?





Marco A. Harrendorf
KIT - IEKP

**Comment by bendavid** [comment]
I don't see any reason why this should be needed.  We should try to avoid copying any herwig code into cmssw (and it's unfortunate that this was done in the past)

**Comment by mkirsano** [comment]
I had to perform a similar update of this file in the past, so that it 
matches the one in herwig++.
  I did not get into the details of implementation in CMSSW then.

**Comment by bendavid** [comment]
Yes, I suspect the original motivation for doing this was to provide pythia6-like status codes.  (And as all previous attempts, this has resulted in problems later on.)

**Comment by mharrend** [comment]
Okay, I made a short check and could confirm that if I am completly removing the HepMCConverter.h and HepMCConverter.cc file, I still get the same results as with the repatched version.

Have a look here: https://mharrend.web.cern.ch/mharrend/comparison-herwig271-cmssw-patched-unpatched/

Thus, I will remove the two files.

**Comment by bendavid** [comment]
Wouldn't the include statement at 
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc#L40

also have to be modified to include the header directly from herwig++ instead of from cmssw?

**Comment by mharrend** [comment]
Thanks for pointing to the include statement. 
Fixing this resulted in the creation of an additional template header file required for the HepMC 2 ROOT conversion

**Comment by bendavid** [comment]
Thanks,
This looks good now.
Do you want us to merge this one as is and take care of the config changes in a separate pull request?

**Comment by mharrend** [comment]
Yes, this was what I had in mind.
Just merge this one first.

I will update the other pull request thread and give you a notice if you can merge it also.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
