### PR TITLE
Time event + avoid premix dataset collision 

### PR DESCRIPTION
**Pull request by franzoni**
- time per event for GEN
- assure no GEN-SIM collisions for prod-like premixing workflows

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
This further update : https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6540/1/1.html calls for further tuning, put in place.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
