### PR TITLE
[12.4.X] Fix to "Update SiStrip and TkAlignment ALCARECO event content for Run3"

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/38590

#### PR description:

Unfortunately PR #38416 aimed to update the event content of the input `ALCARECO` event contents to use S/W FED 1023 information instead of SCAL for all the relevant SiStrip and TkAlignment alcas contained two bugs:
   * in python, when a variable `A` is assigned to another variable `B`, if an operation is done on `B`, the attributes of `A` are changed as well. This has resulted in applying the removal of the content of the  `_run3_common_removedCommands` list even for eras <= Run2.
   * the `ConfigBuilder` uses the `*_noDrop` version of the `ALCARECO` event content to build the list of products to keep, so the instructions gated via the `run3_common` modifier were not effective.
   
   https://github.com/cms-sw/cmssw/blob/36d3f6f602d7f3c2864fdb47505d745598545de8/Configuration/Applications/python/ConfigBuilder.py#L1298

As a result of the two bugs, the list of event products to be kept is now wrong for all eras.
This PR resolves the issue.

#### PR validation:

Test running:
```console
runTheMatrix.py -l 1000.0, 136.874, 138.4 --ibeos
```
and checked the event content of the `SiStripCalMinBias` ALCARECO file, in order to test the Run1, Run2 and Run3 eras.
In addition I've also produced ALCARECO data, starting from RAW and the ConfigDP machinery using the command:

```console
python3 Configuration/DataProcessing/test/RunExpressProcessing.py --nThreads 8 --scenario ppEra_Run3 --global-tag 124X_dataRun3_Express_v3 --lfn root://eoscms.cern.ch//eos/cms/tier0/store/data//Run2022A/MinimumBias/RAW/v1/000/352/929/00000/18df5589-67c8-45e5-ac84-7fd2472de50a.root --fevt --dqmio --alcarecos SiStripCalMinBias
```

and obtained the right event content:

```console
File output_inALCARECO.root Events 13
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
SiStripClusteredmNewDetSetVector_siStripClusters__RECO. 51212.1 13165.5
SiPixelClusteredmNewDetSetVector_siPixelClusters__RECO. 16359.7 6596.46
recoTrackExtras_ALCARECOSiStripCalMinBias__RECO. 1641.15 1066.77
SiStripClusteredmNewDetSetVector_ALCARECOSiStripCalMinBias__RECO. 3236.77 871.923
TrackingRecHitsOwned_ALCARECOSiStripCalMinBias__RECO. 4918.23 813.692
recoTracks_ALCARECOSiStripCalMinBias__RECO. 1793.77 800.615
SiPixelClusteredmNewDetSetVector_ALCARECOSiStripCalMinBias__RECO. 1216.54 559.385
DetIdedmEDCollection_siStripDigis__RECO. 2081.62 280.231
edmTriggerResults_TriggerResults__HLT. 1847.85 245.231
OnlineLuminosityRecord_onlineMetaDataDigis__RECO. 230.538 210.846
L1AcceptBunchCrossings_scalersRawToDigi__RECO. 209.769 198.462
L1GlobalTriggerReadoutRecord_gtDigis__RECO. 261.923 196.385
edmTriggerResults_TriggerResults__RECO. 263.846 191.846
DCSRecord_onlineMetaDataDigis__RECO. 278.538 184.077
EventProductProvenance 2428.31 162
EventAuxiliary 160.385 43.4615
EventSelections 120.769 17.6154
BranchListIndexes 68.5385 12.2308
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/38590

### CODE REVIEW

**Comment by mmusich** [comment]
type trk,bugfix

**Comment by mmusich** [comment]
urgent

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * test pass, the event content is correct now

**Comment by perrotta** [comment]
+1

**Pull request merged**
