### PR TITLE
Migrate remaining 2017 reco customizations to era

### PR DESCRIPTION
**Pull request by makortel**
This PR completes the migration of 2017 reconstruction customizations from `phase1TkCustoms` to `phase1Pixel`/`trackingPhase1` eras that was started in #13477. The produced configurations before and after this PR are not exactly the same. Functionally they are, with the exception that with this PR the castor reconstruction modules are run (following #13591).

The only non-straightforward part was the treatment of non-splitted `siPixelClusters` for the `Phase1PU70` tracking. The issue was discussed in #13381 and in March 3 RECO meeting https://indico.cern.ch/event/505422/contribution/5/attachments/1237476/1817746/slides_trk_phase1_era.pdf, and the impelemented way is to use both `siPixelClustersPreSplitting` and `siPixelClusters` for non-splitted clusters for `Phase1PU70`.

Next step is to switch the default 2017 tracking to the one in #13149 (`Phase1PU70` will be left as a reference that can be switched on with `Run2_2017_trackingPhase1PU70` era).

Tested in CMSSW_8_1_X_2016-03-08-2300 (`runTheMatrix.py -i all -l limited,25202.0,10024.0,10224.0`), no changes expected in monitored quantities.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
It seems that we still don't have any 2017 workflows in the PR tests, right?

**Comment by slava77** [comment]
The old 2017 workflow number set is still requested in jenkins.
I have missed that #13516 removed the older 2017 workflows to replace them with new ones.
I will need to make updates to get them picked up.
I will do.

**Comment by makortel** [comment]
Thanks @slava77.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13666	ed86e3d
- changes are in line with the description
- jenkins tests pass and comparisons with baseline show no difference 
    - the 2017 workflows fell off the jenkins list due to changes in the workflow numbers: cms-bot will pick up the new ones once https://github.com/cms-sw/cms-bot/pull/648 is merged
- tested locally in CMSSW_8_1_0_pre1 with 10021.0,10024.0,10025.0,10026.0,10023.0,10224.0,10225.0 workfows
    - castor reco objects now appear in the outputs as expected 
    - reorganisation of siPixelClusters to use siPixelClustersPreSplitting and PixelLayerTriplets to be PixelLayerTripletsPreSplitting is visible runtime
    - monitored quantities are unchanged

**Pull request merged**
