### PR TITLE
Allow to take DCS Status from software FED, when SCAL is not available

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In case the DCS status from SCAL is not available, fall back to `DCSRecord` data provided by the software FED n. 1022. The logic is modified in two classes: `SiStripDCSStatus` and `DetStatus`. 
Both classes are used to select events in different ALCARECO workflows, while `SiStripDCSStatus`
is also used to filter events in several Tracker and Tracking DQM modules.
No differences are expected in Run1 and Run2 workflows. For Run3 data the ALCARECO selectors now work correctly.

#### PR validation:

Tested with `runTheMatrix.py -l 1001.0,138.1` and checked that in runs with SCAL there are no differences, while with recent MWGR 2020 cosmic data the events are filtered correctly.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, but a backport will be proposed in 11.0.X to be used for the next MWGR.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
> DQMHistoTests: Total failures: 32963

The simulation workflows are not being treated correctly. I'll fix in the next commit.

**Comment by mmusich** [comment]
can test be restarted here, please?

**Comment by christopheralanwest** [comment]
test parameters
workflow = 138.1

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
ping  @pgunnell, @chayanit, @christopheralanwest, @tocheng,  @tlampen, @pohsun

This PR is eventually needed for the Run3 data-taking and a backport is in order for the next MGWR (whenever that'll be). Can you please take a look?

**Comment by chayanit** [comment]
+1

**Comment by tocheng** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
