### PR TITLE
Change EventSetupRecords to be transient objects

### PR DESCRIPTION
**Pull request by Dr15Jones**
Internally, the EventSetup now uses a generic EventSetupRecordImpl
class to manage the work needed for a Record. All classes that inherit
from EventSetupRecord are now just temporary 'facade' objects (similar to
the edm::Event).
This reduces the number of template classes that need to be instantiated and
will be needed to allow enforcement of 'consumes' within the EventSetup system.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@wddgit @makortel please review

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by wddgit** [comment]
I read through it and it looks like an improvement to me. The only thing I noticed is the comment before the tryToGet function could be revised because it does not return a pointer anymore.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
