### PR TITLE
Fixes in PSetBlobProducer functionality for use in HLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fixes in PSetBlobProducer functionality for use in HLT

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
abort test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29998	514b10b
- reco signature is formally needed for EventFilter/Utilities/src/EvFOutputModule.cc, a part of the shared package usually reviewed by DAQ

**Comment by silviodonato** [comment]
+1

**Pull request merged**
