### PR TITLE
Adding HI MEs to per-LS scope in JetMET offline DQM

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Adding the following MEs to the per-LS scope:

```
JetMET/HIJetValidation/akCs4PFJets/SumPFPt
JetMET/HIJetValidation/akCs4PFJets/NJets
JetMET/HIJetValidation/akCs4PFJets/NPFpart
JetMET/HIJetValidation/akPu4CaloJets/SumCaloPt
JetMET/HIJetValidation/akPu4CaloJets/NCalopart
JetMET/HIJetValidation/akPu4CaloJets/NJets
```

#### PR validation:

Tested running the `@jetmet` sequence on run 375703 HIMinimumBias0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will be backported to 14_1_X

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
please test

**Comment by mandrenguyen** [comment]
please abort

**Comment by mandrenguyen** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46559

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Pull request merged**
