### PR TITLE
[backport] Modification to PythiaFilterMotherSister

### PR DESCRIPTION
**Pull request by mgratti**
This PR is a backport of #33806 

Needed for an MC production with B-parking conditions.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by mgratti** [comment]
Hi, please, hold on this PR, because the original PR (#33806) is not yet merged.
Sorry for the confusion.

**Comment by mgratti** [comment]
Hi, I went through the logs where errors were signalled [1], but there is no sign that something went wrong there

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5763f2/15251/dupDict/

**Comment by qliphy** [comment]
The Duplicate Dictionaries error is not related to this PR, and has been also mentioned in below:
https://github.com/cms-sw/cmssw/pull/33752#issuecomment-843281463

**Comment by silviodonato** [comment]
@mgratti please consider to have a backport also to 10_6_X for a possible future b-parking ultralegacy

**Comment by agrohsje** [comment]
Just to say: the original one is still to be updated: #33806.

**Comment by mgratti** [comment]
the PR was updated to follow the modifications done in the master, see #33806

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
@silviodonato @qliphy  i am puzzled that there are 2084 failures in workflow: 140.53  https://cmssdt.cern.ch/lxr/source/Configuration/PyReleaseValidation/python/relval_standard.py?v=CMSSW_12_0_X_2021-06-01-2300 . shouldn't be related to this pr.

**Comment by qliphy** [comment]
@agrohsje  It is a known due to the fact  "140.53 have different files in step1_dasquery.log than the ones found in the baseline"  You can ignore these differences from 140.53.

**Comment by agrohsje** [comment]
Thanks @qliphy for clarifying.

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
