### PR TITLE
CT-PPS DQM: Minor bug fix and improved readability

### PR DESCRIPTION
**Pull request by AndreaBellora**
Since rocf represents the number of planes in which ROC 'i' fired, the name has been changed to planesFiredAtROC and its range has been fixed to be NROCsMAX. This bug has not produced any issues up to now, because the maximum number of ROCs has always been equal to the number of planes, although it's better to have it fixed for the future.

### CODE REVIEW

**Comment by jfernan2** [comment]
@AndreaBellora  please include the name of the subsystem (CT-PPS) in the PR title
Thanks

**Comment by jan-kaspar** [comment]
Could some trigger tests, please?

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
