### PR TITLE
adding embedding of user.dec for evtgen in the cfg 

### PR DESCRIPTION
**Pull request by alberto-sanchez**
This new feature should add the ability to put the user dec file in the cfg file.
This is an important feature that should go into production asap.
It resolve the problem of having a new release for every user.dec change.

please review and approve.

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
