### PR TITLE
Initial PR for SiStrip Control View DQM Plots

### PR DESCRIPTION
**Pull request by gouskos**

### CODE REVIEW

**Comment by fioriNTU** [comment]
@gouskos this PR looks strange, you have more than 250 commits, but at the end only 3 files are changed ... mmmm. I would close it and resubmit on a fresh IB. 

However the DataFormats/Math/src/classes_def.xml has not been changed by you right?

**Comment by gouskos** [comment]
Hi @fioriNTU ; this is my second PR/try and I see the same thing [I started from a fresh IB]. I only changed the 2 files which are included in this commit: https://github.com/cms-sw/cmssw/pull/19202/commits/20eaed2255f9484051877a67011fe9ebdf518168

**Comment by boudoul** [comment]
which IB are you using ?

**Comment by gouskos** [comment]
I am using: CMSSW_9_2_ROOT6_X_2017-06-12-2300 [I tried CMSSW_9_2_0_patch3 before this PR but I saw the same thing]

**Comment by boudoul** [comment]
ah voila you should not use a root6 IB but a standard one : please use CMSSW_9_2_X_2017-06-12-2300

**Comment by gouskos** [comment]
Thank you. I will close it and make a new one in the IB you suggest

**Comment by gouskos** [comment]
Thank you. I will close it and make a new one in the IB you suggest

**Pull request closed without merging**
