### PR TITLE
Move "hybrid" tau production from nano to mini step

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR moves production of hybrid-taus, i.e. collection of tau candidates reconstructed by the HPS algorithm and jet tagged by unified jet taggers as tau-like but not reconstructed by HPS, from nanoAOD to miniAOD step. This movement unfies tau information available in both mini and nano data tiers. 

#### PR validation:

Tested with custom re-mini+nano and with nano workflows.
Matrix tests (limited) successful.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport is not planned.

### CODE REVIEW

**Comment by hqucms** [comment]
Hi @mbluj -- Can you rebase as https://github.com/cms-sw/cmssw/pull/46066 has already been merged? Thanks!

**Comment by hqucms** [comment]
enable nano

**Comment by mbluj** [comment]
> Hi @mbluj -- Can you rebase as #46066 has already been merged? Thanks!

In meantime I have found an unexpected issue when running matrix tests - I will fix it and then rebase.

**Comment by mbluj** [comment]
Tests concluded, fixes included and then development branch rebased to the most recent IB => PR ready for tests

**Comment by hqucms** [comment]
please test

**Comment by mbluj** [comment]
The failing unit tests are in tau-embedding code which seems using not-updated cmsDriver commands. I will try to fix the tests soon, but please note that those are not used in standard production workflows.
Are there other issues with this developments?

**Comment by mbluj** [comment]
FYI, nothing really changed, it was just a routine rebasing to the current IB.

**Comment by mbluj** [comment]
Last commits should fix issues with unit tests

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by antoniovagnerini** [comment]
+1

**Comment by hqucms** [comment]
ping @cms-sw/simulation-l2

**Comment by kpedro88** [comment]
+simulation

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
