### PR TITLE
HGCAL trigger fixes, optimizations and cleaning

### PR DESCRIPTION
**Pull request by jbsauvan**
* Bug fixes in the trigger cell calibration and in the 3D cluster linking
* Code optimization reducing by a factor 2 to 4 the processing time of the HGCAL trigger primitive generation
* Add a cluster-level global calibration to put the EM response around 1 (some small dependency with eta and pT remains)
* Cleaning of config files and updates of the default parameters

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
