### PR TITLE
remove MuonHOAcceptance

### PR DESCRIPTION
**Pull request by slava77**
the code was not used since the initial commit in June 2010. It can not really be used as is without major rewrite to remove use of statics and perhaps making it in a service.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@folguera, @drkovalskyi 
please confirm that this code is not needed in some imminent development.
If we need to go back to it, there is always a github history to bring it back.
(As I mentioned in the description, as is it can not run in standard production code and needs to be rewritten anyways).

**Comment by folguera** [comment]
Hi @slava77, we have both check this PR and indeed this is not used and it is certainly not needed in some imminent development. Thanks.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21823	f686d9c
- removal is OK for muon POG
- jenkins tests passed

**Comment by fabiocos** [comment]
+1

**Pull request merged**
