### PR TITLE
bsunanda:Run2-hcx77 Bug fix for relabelling eta/phi index

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@civanch this should solve the `HcalDDDRecConstants::getHCID()` valgrind problem from #14110

**Comment by bsunanda** [comment]
@davidlange6 This PR fix bugs which could screw up any Phase2 simulation. If possible it to be included in pre3

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
