### PR TITLE
Add caloParams v0_1 for 2024 HI run

### PR DESCRIPTION
**Pull request by rohitcms**
PR description:
Add L1T calo configs for the heavy ion with updated centrality trigger thresholds based on studies during the ramp-up fills.

PR validation:
These files represent L1 configuration to be stored centrally, and are not involved in any central workflows.

If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport. Will need to backport to CMSSW_14_1_X.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
-orp

**Comment by antoniovilela** [comment]
@rohitcms @aloeliger 
Could you please look at the conflicts?
Thanks.

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
