### PR TITLE
Add ONNXruntime python test

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:
Add a test for onnxruntime python interface we added here:
https://github.com/cms-sw/cmsdist/pull/5668
Taken from this examples: 
https://github.com/microsoft/onnxruntime/tree/master/docs/python/examples
uses example model from onnxruntime datasets folder 
#### PR validation:

The test runs

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/5668

**Comment by smuzaffar** [comment]
hold
we need to fix onnxruntime python for aarch64

**Comment by slava77** [comment]
> hold
> we need to fix onnxruntime python for aarch64

@smuzaffar is this hold still active ?

**Comment by smuzaffar** [comment]
unhold

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29246	ee1d704 
- looks as described
- the set up seems somewhat questionable to me, because we are adding a unit test that's supposed to be testing an external itself rather than anything in CMSSW. Shouldn't this be a part of a test of the external?

**Comment by smuzaffar** [comment]
> the set up seems somewhat questionable to me, because we are adding a unit test that's supposed to be testing an external itself rather than anything in CMSSW. Shouldn't this be a part of a test of the external?

@slava77 , you are right but having unit test in cmssw also makes sure that environment of the tool is properly setup within cmssw.

**Comment by silviodonato** [comment]
merge
@santocch this PR is adding a unit test

**Comment by santocch** [comment]
+1

**Pull request merged**
