### PR TITLE
Backport ConcurrentGeneratorFilter to 106X

### PR DESCRIPTION
**Pull request by PhyM73**
#### PR description:

**This PR is a backport of #33883.** 

It implements a thread-safe module `ConcurrentGeneratorFilter` for GEN workflows. This module replicates the Generator for each stream in order to run them concurrently and only works for thread-friendly hadronizers, decayers, and filters. It also provides a concurrent module of the Pythia8 generator, `Pythia8ConcurrentGeneratorFilter`. More detailed explanation and validation can be found in [these slides](https://indico.cern.ch/event/1045566/contributions/4392194/attachments/2261959/3839785/21.06.10_PPD_Concurrent%20GEN%20processing.pdf)(thanks to @colizz).

#### PR validation:

This PR is validated on multiple datasets, by replacing `Pythia8GeneratorFilter` with `Pythia8ConcurrentGeneratorFilter` in the GEN step configuration(see page 7 and 9 of above slides). Below is a quick test on [BTV-RunIISummer20UL17GEN-00002](https://cms-pdmv.cern.ch/mcm/requests?prepid=BTV-RunIISummer20UL17GEN-00002&page=0&shown=127) with 4 threads. There is also a unittest, `GeneratorInterface/Pythia8Interface/test/test_Pythia8ConcurrentGeneratorFilter_WZ_TuneCP5_13TeV-pythia8.sh`.

```bash
cmsrel CMSSW_10_6_X_2021-06-16-2300
cd CMSSW_10_6_X_2021-06-16-2300/src/
cmsenv
git cms-merge-topic PhyM73:bp-feature-ConcurrentGeneratorFilter
curl -s -k https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-RunIISummer20UL17GEN-00002 --retry 3 --create-dirs -o Configuration/GenProduction/python/BTV-RunIISummer20UL17GEN-00002-fragment.py
scram b -j 8
cd ../..
cmsDriver.py Configuration/GenProduction/python/BTV-RunIISummer20UL17GEN-00002-fragment.py --python_filename BTV-RunIISummer20UL17GEN-00002_1_cfg.py --eventcontent RAWSIM --customise Configuration/DataProcessing/Utils.addMonitoring --datatier GEN --fileout file:BTV-RunIISummer20UL17GEN-00002.root --conditions 106X_mc2017_realistic_v6 --beamspot Realistic25ns13TeVEarly2017Collision --customise_commands process.source.numberEventsInLuminosityBlock="cms.untracked.uint32(10)" --step GEN --geometry DB:Extended --era Run2_2017 --no_exec --mc -n 100 --nThreads 4 --nConcurrentLumis 0

sed -i "s/Pythia8GeneratorFilter/Pythia8ConcurrentGeneratorFilter/g" BTV-RunIISummer20UL17GEN-00002_1_cfg.py
cmsRun -e -j BTV-RunIISummer20UL17GEN-00002_report.xml BTV-RunIISummer20UL17GEN-00002_1_cfg.py
```

### CODE REVIEW

**Comment by srimanob** [comment]
please test

**Comment by smuzaffar** [comment]
@PhyM73 , please update this PR to avoid running `scram b`, see https://github.com/cms-sw/cmssw/pull/34185

**Comment by srimanob** [comment]
Please test

**Comment by qliphy** [comment]
There is a DAS query error although all the tests passes.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3e6e8e/16114/runTheMatrixINPUT-results/matrixTestsINPUT.log
"Preparing to run 4.36 WElSkim2011B+WElSkim2011B+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT
2021/06/19 15:59:11 ERROR DAS QL ERROR, query=file block = /SingleMu/Run2011A-WMu-08Nov2011-v1/RAW-RECO#388c2990-0de6-11e1-bb7e-00221959e72f run = 165121 site = T2_CH_CERN, idx=0, msg=unable to parse DAS query"

**Comment by qliphy** [comment]
please test

**Comment by smuzaffar** [comment]
unhold

**Comment by smuzaffar** [comment]
@PhyM73 , please see https://github.com/cms-sw/cmssw/pull/34200 . Lets wait for #34200 to be merged and tested in IB before backporting it here.

**Comment by PhyM73** [comment]
I see. @smuzaffar Thanks! 😄

**Comment by qliphy** [comment]
@https://github.com/cms-sw/cmssw/pull/34200 is now merged and IB tests look good.
@PhyM73 please make a backport here.

**Comment by qliphy** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
