### PR TITLE
Phase2 HLT pixel modules duplicate removal

### PR DESCRIPTION
**Pull request by lguzzi**
#### PR description:

This PR removes some duplicated modules in the phase2 HLT menu and renames some of the pixel modules. See [here](https://indico.cern.ch/event/1259059/contributions/5288699/attachments/2601695/4492493/SB_RemovalDuplicate27Feb2023.pdf) for more details.

Details of the PR:
- hltPhase2L3MuonPixelFitterByHelixProjections and hltPhase2L3MuonPixelTracksFitter are removed in favour of pixelFitterByHelixProjections. These modules are fully duplicated and no change is expected.
- pixelFitterByHelixProjections is renamed to hltPhase2PixelFitterByHelixProjections
- hltPhase2L3MuonPixelTrackFilterByKinematics and hltPhase2L3MuonPixelTracksFilter are removed in favour of pixelTrackFilterByKinematics. These modules are fully duplicated and no change is expected.
- pixelTrackFilterByKinematics is renamed to hltPhase2PixelTrackFilterByKinematics
- caloTowerForTrk is removed in favour of hltTowerMakerForAll. No change is expected, more info [here](https://indico.cern.ch/event/1310813/contributions/5514248/subcontributions/436544/attachments/2689992/4667838/duplicates.pdf)
- hltTowerMakerForAll is renamed to hltPhase2TowerMakerForAll
- highPtTripletStepTrackingRegions is removed in favour of pixelTracksTrackingRegions. No change is expected, more info [here](https://indico.cern.ch/event/1310813/contributions/5514248/subcontributions/436544/attachments/2689992/4667838/duplicates.pdf)
- pixelTracksTrackingRegions is renamed to hltPhase2PixelTracksAndHighPtStepTrackingRegions
- pixelTracksHitDoublets is renamed to hltPhase2PixelTracksHitDoublets
- pixelTracksHitSeeds is renamed to hltPhase2PixelTracksHitSeeds
- pixelTracksSeedLayers is renamed to hltPhase2PixelTracksSeedLayers
- pixelTracks is renamed to hltPhase2PixelTracks
- pixelVertices is renamed to hltPhase2PixelVertices
- pixelTracksTask is renamed to hltPhase2PixelTracksTask

No change is expected.

#### PR validation:

Tested the commits privately running 
```bash
cmsDriver.py Phase2 -s HLT:75e33 --processName=HLTX \
  --conditions auto:phase2_realistic_T21 \
  --geometry Extended2026D95 \
  --era Phase2C17I13M9 \
  --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
  --eventcontent FEVTDEBUGHLT \
  --filein /store/relval/CMSSW_13_2_0_pre3/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/131X_mcRun4_realistic_v6_2026D98noPU-v1/2580000/01b21771-37d5-41c2-b0ea-97bfce125a9a.root \
  -n 10 --nThreads 4
```
on 13_3_X as from the [phase2 HLT twiki](https://twiki.cern.ch/twiki/bin/view/CMS/HighLevelTriggerPhase2#Timing_calculations). Output: [result on 133X](https://lguzzi.web.cern.ch/lguzzi/Tracking/Phase2/duplicates/PR_test/duplicates_test_133X.txt) ([baseline result](https://lguzzi.web.cern.ch/lguzzi/Tracking/Phase2/duplicates/PR_test/duplicates_test_133X_baseline.txt) run on c2e865adc2671fa7d91832fbdab21b90db967572 for reference)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

not a backport. To be backported to 13_1_X and 13_2_X for the phase2 hlt menu.

### CODE REVIEW

**Comment by slava77** [comment]
type tracking

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@lguzzi 

> Reco comparison results: 133 differences found in the comparisons

Are these expected?

**Comment by lguzzi** [comment]
@mmusich ,
I am not familiar with these tests, but if I read this right,
within the trk phase2 upgrade group we decided to rename the phase 2 modules and collections from pixel[...] to hltPhase2Pixel[...] n(see [here](https://indico.cern.ch/event/1310813/contributions/5514248/subcontributions/436544/attachments/2689992/4667838/duplicates.pdf)), this includes also pixelTracks_cfi and pixelVertices_cfi.
From the summary I see that the failing tests refer all to pixel tracks and vertices quantitie. The test seems to fail to collect any information for those collections. I believe this is expected because these collections are now hltPhase2Pixel[Tracks/Vertices].
Within the HLT_75e33 menu, all paths/tasks/modules are up to date with the new naming scheme.

**Comment by mmusich** [comment]
> From the summary I see that the failing tests refer all to pixel tracks and vertices quantities. The test seems to fail to collect any information for those collections.

I am wondering if it is accidental that the `Reco comparison` is capturing these events products (since the name they have matched somewhat the offline nomenclature). In any case in lack of an appropriate Phase-2 DQM @ HLT (https://github.com/cms-sw/cmssw/issues/39362), I guess this doubled back as additional check. Not sure if the script should be updated using the new names.

**Comment by missirol** [comment]
@beaucero @SohamBhattacharya @rovere , do you have any comments on this PR ? If not, I can sign it.

**Comment by SohamBhattacharya** [comment]
> @beaucero @SohamBhattacharya @rovere , do you have any comments on this PR ? If not, I can sign it.

No comments from me. Thanks.

**Comment by missirol** [comment]
+hlt
 - "Reco comparison" differences are due to the changes to the Phase-2 HLT menu (seen from the process name "HLT" in the name of the plots).
 - Probably, those HLT collections were previously picked up in those DQM plots because named as their offline counterparts.
 - This accidental monitoring is now lost, and clearly https://github.com/cms-sw/cmssw/issues/39362 is not ready to be closed.

**Pull request merged**
