### PR TITLE
[10_1_X] SiStrip (un)packer: fixes and support for nonstandard ZS(lite) modes

### PR DESCRIPTION
**Pull request by pieterdavid**
backport of https://github.com/cms-sw/cmssw/pull/23417
(as discussed in last Friday's reco meeting (see [this contribution](https://indico.cern.ch/event/736002/#129-sistrip-unpacker-updates)))

No changes in the tests are expected, except (as in the 10_2 PR) for warnings:
 - in 140.53 (repacked 2011 HI data) about an invalid packet code (0 for non-lite zero-suppressed data), which is due to a pre-2015 packer bug that is worked around in the unpacker
 - about missing data from FED 87 for 1000.0 and 1001.0 (2011 minimum bias, run 165121), and from FEDs 87, 135 and 137 for the 4.22 test (2011 cosmics, run 160960). These were silenced before, and are all understood and not related to the changes done here.

CC: @alesaggio @OlivierBondu @vidalm @mmusich @echabert @erikbutz

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- This is identical commit-wise and code wise to #23417, now merged in the master
- SiStrip unpacker adapted for non-standard ZS modes as described: user tests show that the unpacked data reproduce the input ones
- No effect is visible in standard workflows, where those non-standard ZS modes are not at work
- Warning messages have also been reorganized and improved: this generates an extra warning (once per job) in the 2011 pp workflows. It was investigated, but it remains outside the scope of this PR

**Comment by civanch** [comment]
+1

**Comment by boudoul** [comment]
Dear @fabiocos - Would it be possible to get this integrated in the next 10_1_X in order to make it available for operation ? Thanks

**Comment by slava77** [comment]
@fabiocos 
please clarify the plans for this PR, if it will be added to 10_1_X soon.
Thank you.

**Comment by mmusich** [comment]
@fabiocos may I ask if there is at this point any plan to include this PR in the 10_1_X cycle or shall we just have in post-TS2 data in 10_2_X? This is somehow a nuisance for continuing tests on the HW side at P5.

**Comment by fabiocos** [comment]
@mmusich @boudoul what is the outcome of the tracker validation in pre6? I was monitoring that to integrate this asap, but I did not see any report in valDB so far

**Comment by mmusich** [comment]
@fabiocos, indeed the data report is missing (which is a pity) and the report from @boudoul on simulation (https://hypernews.cern.ch/HyperNews/CMS/get/relval/10839.html) is indeed still open (likely because of many changes introduced in the pixel detector) but a quick look at  Strip workspace pointed in the "work in progress" report (https://goo.gl/ThZvmN) makes me conclude that the outcome is positive (I do not see catastrophically wrong changes). 
Also, all the other subsystem that depend on the Strip Tracker (such as Tracking) have signed off the data campaign (https://hypernews.cern.ch/HyperNews/CMS/get/relval/10815/6.html), but I agree it would be better to get the Tracker data report (as it is clean from other changes in conditions that have happened in simulation).

**Comment by fabiocos** [comment]
+operations

backport from master

**Comment by fabiocos** [comment]
+1

Tracker validation of CMSSW_10_2_0_pre6 is reported ok

**Comment by boudoul** [comment]
Thanks @fabiocos , do you have an estimate when 10_1_9 will come ? In our case the earlier , the better

**Pull request merged**
