### PR TITLE
Bugfix for EMTF DQM module

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR addresses https://github.com/cms-sw/cmssw/issues/46182 

I verified that GEM layer always takes values 1 or 2 and also verified this with GEM experts. The solution is to subtract 1 from `layer` while filling the histograms. 

#### PR validation:

Validated by running DQM on recent data. The plots are filled correctly for layers 1 and 2 after the fix.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We can backport this to 14_1_X to fix the problem during the HI run as well.

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
please test

**Comment by smuzaffar** [comment]
please test

lets use latest IBs ( to avoid input relvals errors)

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
