### PR TITLE
add heavy-ion Run 3 data RelVal workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

RelVal workflows 140.60 and 140.61 now run reconstruction on raw and rawprime input from the HI test run.  140.60 replaces a placeholder workflow that used pp data as input. 

#### PR validation:

140.60 and 140.61 were tested. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport will be needed.

Question maybe for @cms-sw/pdmv-l2 :  How do I ensure that the raw input data stays staged on disk?

@prebello

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 140.60,140.61

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
please test
Runs fine offline, should really work.

**Comment by srimanob** [comment]
It's an input error. Not sure if the first test can trigger the transfer already.

**Comment by mandrenguyen** [comment]
@srimanob I'm reading the input files fine from T2_US_Vanderbilt.  Do they need to be transferred somewhere else?

**Comment by srimanob** [comment]
+Upgrade

New workflows run fine.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
