### PR TITLE
Calo Layer 2 saturation fixes **10_3_X BACKPORT**

### PR DESCRIPTION
**Pull request by bundocka**
- Fix saturation handling for HI centrality and asymmetry algorithms
- Update centrality classes in HI caloParams config 
- Fix MP & Demux jet saturation handling
- Fix Demux MET & MHT saturation handling
- Correct buffer unpacker to use same demux latency convention as online

Apart from the HI specific changes, the rest are edge cases in saturation handling that were discovered by running events with many high energy towers through the MP firmware and checking MP & demux output vs. emulator.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #24883

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
