### PR TITLE
Remove penalty on unganged ME11A

### PR DESCRIPTION
**Pull request by jhgoh**
A penalty have been applied in the muon seeding for the segments from ME11A to account ganged CSCs.
With this PR, penalty is not applied for un-ganged ones in ME11A.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@jhgoh 
John, the PR description doesn't quite match the code change: what is done is to apply penalty only to ganged ME11A (run1) and not apply it for unganged one (run2 and later).
So, "remove penalty on unganged ME11A" or similar is a more appropriate subject (you can edit it by clicking "Edit" button on the upper right of your PR).

**Comment by jhgoh** [comment]
@slava77 thank you. title is changed :-)

**Comment by cvuosalo** [comment]
+1

For #11305 613298dc8dd36a96b3019169df23038daaaa9a97

From Run 1 to Run 2, CSC ME11A chambers have become unganged. ME11A chambers were given a muon seeding penalty in Run 1. This change applies the penalty only to ganged chambers (Run 1), not the refurbished ME11A chambers for Run 2.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11305/8169/summary.html) against baseline CMSSW_7_6_X_2015-09-16-2300 show no significant differences, as expected. An extended test of workflow 25206.0_ZMM_13 with 100 events against baseline CMSSW_7_6_X_2015-09-16-2300 also shows no significant differences. There are a few small changes, like the following example.
eff
Note the "Run1" label on the plot does not refer to conditions. This plot is based upon run2_mc conditions with ME11A unganged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
