### PR TITLE
Enable standard digitisation and reconstruction on simulation HCALECAL geometry 

### PR DESCRIPTION
**Pull request by lveldere**
- wrote a producer of empty PSimHit and PCaloHit collections
- wrote a customisation function that adds empty PSimHit and PCaloHit collections to the event for those detector parts that are not include in the HCALECAL geometry
- wrote some cfg to test this setup

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
@lveldere - please move the new plugin into an already existing package. Thanks

**Comment by lveldere** [comment]
please test

@davidlange6 
moved to FastSimulation/Validation

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
