### PR TITLE
Backport NanoAOD 2016 PR from master to 10_2_X

### PR DESCRIPTION
**Pull request by gpetruc**
backport of #24214 to 10_2_X branch in order to keep them aligned.
done from the same branch of the PR already merged in master

### CODE REVIEW

**Comment by gpetruc** [comment]
backport #24214

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1
same as #24214

**Comment by fabiocos** [comment]
+operations

synchronyzation of nanAOD for 2016 with master and 94X

**Comment by fabiocos** [comment]
+1

**Pull request merged**
