### PR TITLE
allowing E/g HLT to be seeded by L1 jets (74X edition)

### PR DESCRIPTION
**Pull request by Sam-Harper**
This is the 74X edition of a change to the E/g HLT to allow it to be seeded by L1 jets. It is discussed in  https://github.com/cms-sw/cmssw/pull/8804.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Actually, this is kind of bad as it does not allow to reproduce the old behaviour:
it seems jets are now always used, rather than switched on.
Perhaps the default for the new InputTag should be empty,
and the new logic gets activated only when it is non-empty.

**Comment by Sam-Harper** [comment]
So yes you are strictly correct, for all possible configs, this does not reproduce the old behavior. However for any sensible HLT config it will do. If the L1GtSeed is not a Jet, looking for the jets will have zero effect as they are not there. Only if you're requested a Jet seed in your L1 seeding module will the jet collection be filled. And no E/gamma path did this because it would fail at this matching step. Now it will pass. The idea was that this module automatically accepts whatever seeds was specified by the L1 seeding module. Otherwise you have to enable it both in this module (ie allow jets) and the seed module (seed with a jet module). I'll double check i've understood the logic correctly though.

**Comment by Martin-Grunewald** [comment]
Ah yes, you are correct!

**Pull request merged**
