### PR TITLE
Fix incorrect hadronic shower packing and enable global shower unpacking for both uGMT and uGT

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This PR groups a few fixes (please let me know if I should split it into one PR per fix):
- A check to make sure that we weren't overwriting muon information with the shower bits was watching the wrong bitfield.
- We were also off by one in selecting the correct payload word for the regional muon showers.
- Run-2 debug information from EMTF was still being written to the fields now foreseen for hadronic showers and displaced info. We now only do this for Run-2 data and for Run-3 set those data to zero to avoid a crash in the ntuplizers.
- Unpacking of global hadronic showers (i.e. the uGMT output) has been enabled both for uGMT and the uGT input unpacker/

Two mostly aesthetic fixes:
- We now only pack and unpack regional showers when they are actually filled (i.e. valid).
- The `MuonShower` data format was made a bit more descriptive:
  -  The private members storing the bits that are already defined for Run-3 have been named descriptively.
  - Accessors for those members have been added.

#### PR validation:

Ran on sample with hadronic showers[1] and confirmed that they appear at the output of the uGMT both in the EDM file and L1TNtuple.

[1] `cmsDriver.py  l1Ntuple  --python_filename mc.py  -s L1REPACK:FullMC,RAW2DIGI  --mc -n -1 --conditions auto:phase1_2021_realistic --era Run3 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU  
--customise=L1Trigger/Configuration/customiseUtils.L1TGlobalMenuXML --filein /store/mc/Run3Summer21DRPremix/HTo2LongLivedTo4b_MH-1000_MFF-450_CTau-100000mm_TuneCP5_14TeV-pythia8/GEN-SIM-DIGI-RAW/120X_mcRun3_2021_realistic_v6
-v2/2550000/e28c777d-10fd-4100-b230-c42b0160ad8a.root`

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by dinyar** [comment]
Looked through the DQM plots and while I'm not surprised that we see the changes we see I'll have a quick look offline.

**Comment by dinyar** [comment]
Ok, stared at this for a while and I believe this is compatible with what was changed, however it looks to me like EMTF still isn't unpacking displacement information (and also doesn't have them as DQM plots). Can you confirm that, @eyigitba?

**Comment by eyigitba** [comment]
@dinyar we still haven't put in the unpacker changes and displaced pT + dxy DQM plots in CMSSW. I was hoping to put them in this week, but I still need some information from Alex. I expect to put them in as soon as possible.

**Comment by dinyar** [comment]
Hi Efe,

Ok, no problem. Do you think it's worth waiting for your changes with this PR to make sure things are fine? If you think it might take a bit too long we can also go ahead with this and then just make sure we check for mismatches once you make your PR..

Cheers,
Dinyar

**Comment by eyigitba** [comment]
Hi Dinyar,

I think it's ok to merge this. It shouldn't take long for me the submit the PR, but I don't think it's a reason to wait :). We can check for mismatches once we get there.

**Comment by dinyar** [comment]
Great, sounds good thanks for the quick answer! @cecilecaillol or @epalencia, could you check this PR and sign if it's fine with you?

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1
- Changes in the DQM outputs have been evaluated and approved by the relevant experts

**Pull request merged**
