### PR TITLE
Updating Phase2 Digitizer configuration for Inner Pixel

### PR DESCRIPTION
**Pull request by suchandradutta**
This PR concerns Phase2: revert to null the inter-pixel cross-talk of InnerTracker for 25x100 um^2 pixels
since local reco still does not deal correctly with this configuration. Inter-pixel cross-talk (phase2) was introduced with PR #25134 and was mainly intended to study the effect at the digi level.

@emiglior 
@jalimena

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by jalimena** [comment]
Here is some evidence that this PR works as expected. The plot below shows the efficiency of high purity tracks as a function of eta, for the configuration with cross talk implemented (blue) and a test with the cross talk removed (red). Despite the fact that there is much less events in the test (red), one can see that the efficiency is higher with the cross talk removed than with it implemented, which is consistent with our expectations.
image

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Comment by boudoul** [comment]
Hello @jalimena thank you for the plot - Given the importance of this fix which will be included for a big MC production for the MTD TDR  , may I ask you to produce a plot comparing  the performance after the fix but comparing this time with the performance *before* #25134  ?  I believe you had relvals if I'm not wrong for reference- 
In practice with this comparison, the performance plots (eff - fake rate..) should be superimposed and this is what I would like to x-check- Would it be possible to get this? Thank you .
(@kpedro88 @ fabiocos - this is related to the discussion we had today at the simulation meeting)

**Comment by jalimena** [comment]
Hi @boudoul , sure. #25134  was introduced in 10_4_0_pre2 (https://github.com/cms-sw/cmssw/releases/CMSSW_10_4_0_pre2), so I looked for a ttbar no PU relval of 2023D1 before that. The latest one is from 10_2_0_pre5. So I compare that one (in blue) with my same test of 100 ttbar no PU events containing the configuration in this PR (in red):
image
It seems that these two configurations are identical within uncertainties, as we expect (and want).
The rest of the plots are here, if you want to check:
https://jalimena.web.cern.ch/jalimena/plots/track_validation_plots_TTbar_2023D21_before25134_crossTalkTest/plots/
The cross talk didn't have an effect on the fake rate.

**Comment by boudoul** [comment]
Thank you very  much ! Appreciated

**Comment by fabiocos** [comment]
@jalimena thanks for the documentation

**Pull request merged**
