### PR TITLE
[L1TMuonBarrel] KMTF fixes on propagation coefficients (CMSSW_11_2_X)

### PR DESCRIPTION
**Pull request by Tyler-Lam**
#### PR description:

New version of KMTF algorithm as discussed in https://indico.cern.ch/event/1012620/contributions/4250430/attachments/2200192/3721090/Run3_KMTF.pdf

#### PR validation:

Nominal tests with just KMTF algorithm. No core changes, just incremental changes to KMTF

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of #33078 , requested by the L1 Trigger group

@rekovic copied from #33078 -  the LUTs in L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs.root are usually in the https://github.com/cms-l1t-offline/L1Trigger-L1TMuon.git repository. They have to be moved but I do not have access

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by smuzaffar** [comment]
hold
please see the issue https://github.com/cms-sw/cmssw/issues/33303 . @Tyler-Lam  please cleanup this PR and remove the root file.  Please remove the file from the history so that we do not get it in repo.  I have open https://github.com/cms-data/L1Trigger-L1TMuon/pull/20 which can be integrated in 11.2.X to include your new root file

**Comment by smuzaffar** [comment]
test parameters:
 - pull_request = hcms-sw/cmsdist#6773

**Comment by smuzaffar** [comment]
@Tyler-Lam , cms-sw/cmsdist#6773 should  include the updated root file

**Comment by smuzaffar** [comment]
@rekovic , for 11.3.X , I have already opened the PR https://github.com/cms-sw/cmssw/pull/33304 .
For 11.2.X, yes, please update this PR . I would suggest to delete the root file and force push changes so that the root file does not appear in the history

**Comment by smuzaffar** [comment]
@Tyler-Lam , push a new commit to remove file is fine but in order to reduce the 11.2.X branch size can you please locally squash the two commits https://www.internalpointers.com/post/squash-commits-into-one-git . This way the binary root file will not be part of 11.2.X branch history and will keep its size small.

**Comment by smuzaffar** [comment]
thanks a lot @Tyler-Lam

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unhold

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@cms-sw/externals-l2 @qliphy 
I've made a mistake in the morning IB
11_2_X: https://github.com/cms-sw/cmsdist/pull/6773 needed for https://github.com/cms-sw/cmssw/pull/33281
11_3_X: https://github.com/cms-sw/cmsdist/pull/6772 needed for https://github.com/cms-sw/cmssw/pull/33304

I merged https://github.com/cms-sw/cmsdist/pull/6773 + https://github.com/cms-sw/cmssw/pull/33304 in the morning IB, so I think we will get error in `CMSSW_11_2_X_2021-04-02-1100`. It should be fixed in `CMSSW_11_2_X_2021-04-02-2300`

**Comment by smuzaffar** [comment]
I am starting 11.2.X B now ( just to have a clean IB , in case someone wants to use it)

**Pull request merged**
