### PR TITLE
Change L1 2023 Relval Single Jet Bits to Current Menu Bits

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

This PR is part of a (hopefully) two part series (with endcap muon fixes) to remove L1 log spam warnings. This removes old unused prescaled bits [seen missing in 2023 relvals](https://github.com/cms-sw/cmssw/pull/41629#issuecomment-1585546537), and [replaces them with L1 DPG/Menu group suggested bits](https://github.com/cms-l1t-offline/cmssw/issues/1136#issuecomment-1590925682)

In theory, this should close L1T issue tracker https://github.com/cms-l1t-offline/cmssw/issues/1136

### PR validation:

Workflow 141.008 was run and step 3 logs no longer complain about missing single jet bits.

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport, and will likely not need backporting.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- diffs in HLT/SiStrip appears to be unrelated to this PR
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-15-1100+bb7d2f/57514/12434.0_TTbar_14TeV+2023/HLT_SiStrip_ControlView.html
- null comparison in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-15-1100+bb7d2f/57514/138.5_ExpressCollisions2021/L1T_L1TStage2uGT_timing_aux.html is spurious and caused by change in trigger paths

**Comment by missirol** [comment]
Not all warnings are removed in 2023 wfs, e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bb7d2f/33181/runTheMatrix-results/12434.0_TTbar_14TeV+2023/step3_TTbar_14TeV+2023.log).
```
%MSG-w L1TStage2uGTTiming:   L1TStage2uGTTiming:l1tStage2uGTTiming@streamBeginRun 15-Jun-2023 15:50:21 CEST  Run: 1 Stream: 0
Algo "L1_ETT1200" not found in the trigger menu L1Menu_Collisions2023_v1_2_0. Could not retrieve algo bit number.
%MSG
```

In addition, new warnings are introduced in 2022 wfs, e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bb7d2f/33181/runTheMatrix-results/11634.0_TTbar_14TeV+2021/step3_TTbar_14TeV+2021.log).
```
%MSG-w L1TStage2uGTTiming:   L1TStage2uGTTiming:l1tStage2uGTTiming@streamBeginRun 15-Jun-2023 15:46:42 CEST  Run: 1 Stream: 0
Algo "L1_SingleJet35_FWD2p5" not found in the trigger menu L1Menu_Collisions2022_v1_4_0. Could not retrieve algo bit number.
%MSG
```

**Comment by aloeliger** [comment]
> Not all warnings are removed in 2023 wfs, e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bb7d2f/33181/runTheMatrix-results/12434.0_TTbar_14TeV+2023/step3_TTbar_14TeV+2023.log).
> 
> ```
> %MSG-w L1TStage2uGTTiming:   L1TStage2uGTTiming:l1tStage2uGTTiming@streamBeginRun 15-Jun-2023 15:50:21 CEST  Run: 1 Stream: 0
> Algo "L1_ETT1200" not found in the trigger menu L1Menu_Collisions2023_v1_2_0. Could not retrieve algo bit number.
> %MSG
> ```
> 
> In addition, new warnings are introduced in 2022 wfs, e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-bb7d2f/33181/runTheMatrix-results/11634.0_TTbar_14TeV+2021/step3_TTbar_14TeV+2021.log).
> 
> ```
> %MSG-w L1TStage2uGTTiming:   L1TStage2uGTTiming:l1tStage2uGTTiming@streamBeginRun 15-Jun-2023 15:46:42 CEST  Run: 1 Stream: 0
> Algo "L1_SingleJet35_FWD2p5" not found in the trigger menu L1Menu_Collisions2022_v1_4_0. Could not retrieve algo bit number.
> %MSG
> ```

`ETT1200` Can likely be replaced with something else, I can ask the Menu team and DPG again. Trying to maintain perfect consistency between 2022 and 2023 is going to be a little harder.

**Comment by aloeliger** [comment]
[According to the menu group,](https://github.com/cms-l1t-offline/cmssw/issues/1136#issuecomment-1594263551) we can probably replace `ETT1200` with `ETT1600`. I can make that change quickly.

**Comment by missirol** [comment]
> Trying to maintain perfect consistency between 2022 and 2023 is going to be a little harder.

It's understood that the L1T menu can change from year to year. I'm just pointing out that the approach in this PR can fix the 2023 wfs, but it does not really address the issue, because the same exact DQM module continues to run in wfs with different L1T menus (2022, 2023, etc). Suggestions to improve this were mentioned in https://github.com/cms-sw/cmssw/pull/41629#issuecomment-1585546537 and https://github.com/cms-sw/cmssw/pull/41629#issuecomment-1585578945.

**Comment by aloeliger** [comment]
> > Trying to maintain perfect consistency between 2022 and 2023 is going to be a little harder.
> 
> It's understood that the L1T menu can change from year to year. I'm just pointing out that the approach in this PR can fix the 2023 wfs, but it does not really address the issue, because the same exact DQM module continues to run in wfs with different L1T menus (2022, 2023, etc). Suggestions to improve this were mentioned in [#41629 (comment)](https://github.com/cms-sw/cmssw/pull/41629#issuecomment-1585546537) and [#41629 (comment)](https://github.com/cms-sw/cmssw/pull/41629#issuecomment-1585578945).

Alright, understood. In the meanwhile, this is available to clean the 2023 relval logs if desired. I just removed `ETT1200` for `ETT1600` as well.

**Comment by aloeliger** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
