### PR TITLE
multithreading fix for 74x: CorrectedJetProducer

### PR DESCRIPTION
**Pull request by fwyzard**
change all specialisations of `CorrectedJetProducer` into
`global::EDProducer` modules:
- `CorrectedCaloJetProducer`
- `CorrectedPFJetProducer`
- `CorrectedJPTJetProducer`
- `CorrectedTrackJetProducer`
- `CorrectedGenJetProducer`

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #11301 to 74x

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by monttj** [comment]
+1

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
