### PR TITLE
Add missing newlines in Configuration modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
Configuration/DataProcessing
Configuration/EventContent
Configuration/Generator
Configuration/PyReleaseValidation
Configuration/Skimming
Configuration/StandardSequences
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by AdrianoDee** [comment]
+1

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Comment by menglu21** [comment]
+1

**Pull request merged**
