### PR TITLE
Phase2-hgx359Z Update the scripts in Validation/HGCalValidation for the changes in Configuration/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts in Validation/HGCalValidation for the changes in Configuration/Geometry

#### PR validation:

Tested all the modified scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
