### PR TITLE
Run4-hcx253 Match the current parameter drawing for V14 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Match the current parameter drawing for V14 geometry of HGCal

#### PR validation:

Use runTheMatrix test workflows and overlap test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

The scenario and workflow will be created later

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
