### PR TITLE
Update uGT unpacker to pick up new HI centrality values

### PR DESCRIPTION
**Pull request by apana**
Update uGT unpacker to pick up new HI centrality values

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@apana @thomreis how was this really tested?

**Comment by apana** [comment]
Hi Fabio,

I ran the uGT emulator on the recent data taken during the HI test and saw that it was working fine.  The code I added to GTSetup.cc is essentially the same as the code that is already in the Layer2 Calo emulator, https://github.com/cms-sw/cmssw/blob/master/EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloSetup.cc#L75-L77, except for the different firmware version numbers, so I didn't think it needed to go through the full runTheMatrix tests.  Did some problem come up?

Cheers,
Len

On Thu, Oct 25, 2018 at 11:06 AM Fabio Cossutti <notifications@github.com<mailto:notifications@github.com>> wrote:

@apana<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_apana&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=LKR94F1PZIW0sxVhhMIc_w&m=MdIhnnbEl8ef35xyQhElh5Lyiu43dkWCK_IUg4U3ImM&s=LBIZJWkxFOhkYldG53yN-kxEKfk9VJLDtqtRMzgJcl4&e=> @thomreis<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_thomreis&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=LKR94F1PZIW0sxVhhMIc_w&m=MdIhnnbEl8ef35xyQhElh5Lyiu43dkWCK_IUg4U3ImM&s=aOEqFMe25ZvSRipon_9Ca8xRZMxNDH-DtfMRvRwGER4&e=> how was this really tested?

**Comment by fabiocos** [comment]
@apana thank you

**Comment by fabiocos** [comment]
+1

**Pull request merged**
