### PR TITLE
Merged KDTreeLinkerAlgo and KDTreeLinkerAlgoT

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

As noted in https://github.com/cms-sw/cmssw/pull/26534, there are several implementations of KDTrees in CMSSW.

The original one is not in the current release anymore:
https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_X/RecoParticleFlow/PFProducer/interface/KDTreeLinkerAlgo.h

This  code got "forked" two times:

1. https://github.com/cms-sw/cmssw/blob/master/CommonTools/RecoAlgos/interface/KDTreeLinkerAlgo.h
2. https://github.com/cms-sw/cmssw/blob/master/RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerAlgoT.h

Unfortunately the forks diverged. The first one has the same functionality but  is more optimized (i.e. by arranging the node info in structure of array style, see https://github.com/cms-sw/cmssw/pull/772), and the second one is just the generalization of the original code to n dimensions.

I suggest to implement the generalization to n dimension also in the CommonTools version, so the diverging fork can be removed and the faster CommonTools version used instead.

Maybe at a later point one could replace the merged KDTreeLinkerAlgo with another implementation of the KDTree:
https://github.com/cms-sw/cmssw/blob/master/CommonTools/RecoAlgos/interface/FKDTree.h

The FKDTree has also the improvement with the SOA data structures which the KDTreeLinkerAlgo now has as well. I guess the FKDTree will still be a bit faster because it does not use recursion. However, the replacement should probably not be done without profiling. In any case that would be a more involved migration than what I suggest in this PR.

#### PR validation:

CMSSW compiles, local matrix tests pass and the new KDTreeLinkerAlgo seems to work according to my little validation script:
https://gist.github.com/guitargeek/0adc2dac708c7bf7c31c553249622197

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
@perrotta 
there are some overlapping edits here and in #27026 
Unless this one is urgent, perhaps we can wait for #27026 to go in first

**Comment by perrotta** [comment]
hold

**Comment by guitargeek** [comment]
Just my 2 cents: I checked how the edits overlap, and it seems #27026 is just clang-formatting the code that gets deleted here. Given that it's not really useful to format code which gets deleted just afterwards, and #27026 has to solve conflicts anyway, I would suggest to merge this PR here first as it saves a rebase and subsequent bot test. But in the end, it does not really matter :)

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
@guitargeek , this now needs a rebase...

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- KDTreeLinkerAlgo and KDTreeLinkerAlgoT are unified here, which allows for a better maintenance of the code
- Jenkins tests show no difference, as expected
- cpu performance is unaffected, at the first order, for both Phase1 workflows, and for Phase2 ones (where HGCal used the now removed "T" version of the code in the clustering)

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@perrotta @slava77 according to my tests, there are the following overlaps of this PR with others:

```
Testing PR #  27049  for branch  master
File  RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h  modified in PRs #  ['27128', '27160', '27049']
File  RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerAlgoT.h  modified in PRs #  ['27160', '27049']
File  RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerToolsT.h  modified in PRs #  ['27160', '27049']
File  RecoLocalCalo/HGCalRecAlgos/src/HGCal3DClustering.cc  modified in PRs #  ['27128', '27160', '27049']
File  RecoLocalCalo/HGCalRecProducers/interface/HGCalImagingAlgo.h  modified in PRs #  ['27128', '27049']
File  RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc  modified in PRs #  ['27128', '27049']
File  RecoPixelVertexing/PixelTriplets/plugins/PixelTripletHLTGenerator.cc  modified in PRs #  ['27049', '27194']
```

The overlap with #27128 (@clelange FYI) does not seem a problem, I manage to merge it on top of this one. The overlap with #27160 is a problem (@rovere FYI), merging on top of this PR:
```
17:27 cmsdev25 5421> git cms-merge-topic 27160
From .
 * [new ref]                            -> merge-attempt
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Total 156 (delta 76), reused 76 (delta 76), pack-reused 80
Receiving objects: 100% (156/156), 43.01 KiB | 256.00 KiB/s, done.
Resolving deltas: 100% (101/101), completed with 37 local objects.
From https://github.com/cms-sw/cmssw
 * [new ref]                 refs/pull/27160/head -> cms-sw/refs/pull/27160/head
Switched to branch 'merge-attempt'
Auto-merging RecoLocalCalo/HGCalRecAlgos/src/HGCal3DClustering.cc
CONFLICT (content): Merge conflict in RecoLocalCalo/HGCalRecAlgos/src/HGCal3DClustering.cc
CONFLICT (modify/delete): RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerToolsT.h deleted in HEAD and modified in cms-sw/refs/pull/27160/head. Version cms-sw/refs/pull/27160/head of RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerToolsT.h left in tree.
CONFLICT (modify/delete): RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerAlgoT.h deleted in HEAD and modified in cms-sw/refs/pull/27160/head. Version cms-sw/refs/pull/27160/head of RecoLocalCalo/HGCalRecAlgos/interface/KDTreeLinkerAlgoT.h left in tree.
Auto-merging RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
CONFLICT (content): Merge conflict in RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h
Removing RecoHGCal/TICL/src/classes_def.xml
Removing RecoHGCal/TICL/src/classes.h
Removing RecoHGCal/TICL/src/BuildFile.xml
Removing RecoHGCal/TICL/plugins/PatternRecognitionbyCAConstants.h
Removing RecoHGCal/TICL/BuildFile.xml
Automatic merge failed; fix conflicts and then commit the result.
Unable to merge branch refs/pull/27160/head from repository cms-sw.
```
From a test these conflicts are not just simply "clang-format" related. 

Finally looking at 27194 by @makortel I see no real conflict (the merge is successful). 

So the only real problem is with #27160

**Comment by perrotta** [comment]
@fabiocos we already agreed with @rovere (since the last reco meeting) that #27160 will be rebased as soon as these other pr's will get merged.
As it is now, they will keep blocked each other, and one of them must go first: #27160 still needs some little development, let go these other one first then. As soon as TICL will be ready to go, we will held the other still pending hgcal prs for it. Whatever we can merge till then will reduce future troubles.

**Comment by fabiocos** [comment]
@perrotta ok, I just wanted to have everybody on board, this PR will move forward in next IB.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
