### PR TITLE
bsunanda:Run2-TB23 Add the new AHCal for 2017 HGCal TB

### PR DESCRIPTION
**Pull request by bsunanda**
This is a preparatory setup for 2017 HGCal TB at CERN

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda can this one can be closed? (91X version is merged)

**Comment by bsunanda** [comment]
It is transferred to 9_1_X queue and integrated there

**Pull request closed without merging**
