### PR TITLE
Fix L1T MuonShowers for HLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix L1T MuonShowers for HLT
Change in uGT repack file fixes issue https://github.com/cms-sw/cmssw/issues/37482

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@fabiocos, @davidlange6 please sign for operations

**Comment by perrotta** [comment]
+1

**Pull request merged**
