### PR TITLE
Run3-hcx203 Add detId2denseId for some new calibration channels

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend detId2denseId for new calibration types HBX and HEX and also provide the corresponding dense index to hcalcalibdetid 

#### PR validation:

Made a test with runTheMatrix.py and also added a private test to verify the two added methods

#### if this PR is a backport please specify the original PR:

No back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda I understand that the added test configuration has been run and its result was correct

**Comment by fabiocos** [comment]
+1

**Pull request merged**
