### PR TITLE
Migrate ESProducers in L1Trigger from setConsumes() to type-deducing consumes()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates `setConsumes()` calls to the simpler consumes introduced in #31223.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
Kind reminder @cms-sw/l1-l2

**Comment by makortel** [comment]
@cms-sw/l1-l2 Please review and sign.

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
