### PR TITLE
bsunanda:Run2-hcx119 Testing Plan1 grouping

### PR DESCRIPTION
**Pull request by bsunanda**
Also update a few cfi files in view of change in the file structure

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @davidlange6 These failures are not due to this PR. Could you check them sometime

**Comment by ianna** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - FYI, you've re-triggered the tests which were running for about 2 hours

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
