### PR TITLE
Fix mismatched array bounds in tracklet displaced calculator function signature

### LINKED ISSUE #41677: [L1] [CLANG] `mismatched bound arrays` warnings
Hello,

CLANG IBs started showing some warnings reporting mismatched bound arrays (`-Warray-parameter`) as of the update to llvm16.
In concrete, for the l1 module `L1Trigger/TrackFindingTracklet`:

```
>> Compiling  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/VMStubME.cc
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/llvm/16.0.3-5d1904f3c7b5c53b7522ba0858baec44/bin/clang++ -c -DGNU_GCC -D_GNU_SOURCE -DEIGEN_DONT_PARALLELIZE -DTBB_USE_GLIBCXX_VERSION=110201 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DDD4HEP_USE_GEANT4_UNITS=1 -DCMSSW_GIT_HASH='CMSSW_13_2_CLANG_X_2023-05-14-2300' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_13_2_CLANG_X_2023-05-14-2300' -I/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/dd4hep/v01-23x-bcfacc58574f84cec0342afa8ebf093b/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/onnxruntime/1.14.1-faed734daf6d33498ce2b6a718e8d1e6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/cudnn/8.8.0.121-b23c2965df51d1d7d2c350639d9473d9/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/pcre/8.43-5dcc901acc02f624b22dd9840b2357e8/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/boost/1.80.0-7f4aeae1bffcf24aa4723f09435633c2/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/bz2lib/1.0.6-2c1f18484cb66c30aba7929f2be5e7d4/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/clhep/2.4.6.0-a4e46555f840df7cd8747ba64c6e914f/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/cuda/11.5.2-66a9473808e7d5863d5bbec0824e2c4a/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gsl/2.6-fcf47bcbedd800ca8386c7e2920fa474/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/hepmc/2.06.10-8d052e96205063f65fddfc4cbf40f506/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/libuuid/2.34-0451b31e1b9a58c6aeefab41c18eea34/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/protobuf/3.15.1-afbf0e4e62db8d179f85b9eef7a9fbab/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/lcg/root/6.26.11-9720c7273eac1c892ddadde973cf1965/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/cms/vdt/0.4.3-b2ab7c000c16e419f85e9fb6284d3681/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/xerces-c/3.1.3-96261f23c7d6fbfb7d59be544bd882f3/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/xz/5.2.5-83d0a00b575efd1701e07bedf7977343/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/zlib/1.2.11-3dfb2715f3608466b74431b80eb9d788/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-9ac4aed18ac60d0189693c592862694d/include/eigen3 -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/fmt/8.0.1-43b841663c2a0d6622910a1ad66d228d/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/hepmc3/3.2.5-a8c3d3d81a1b670617f2caa48c1801ef/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/md5/1.0.0-e68283f2de2e2e709a0db99db3b53205/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/OpenBLAS/0.3.15-26c67b8b638762cfd2e2bcfc936e3ec7/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/re2/2021-06-01-bd9694d6b7214964900dc18f8d290757/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/tinyxml2/6.2.0-c2bad61e58f94d6db8f640afbd739be2/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Werror=array-bounds -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-c99-extensions -Wno-c++11-narrowing -D__STRICT_ANSI__ -Wno-unused-private-field -Wno-unknown-pragmas -Wno-unused-command-line-argument -Wno-unknown-warning-option -ftemplate-depth=512 -Wno-error=potentially-evaluated-expression -Wno-tautological-type-limit-compare -fsized-deallocation --gcc-toolchain=/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161 -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -DUSEHYBRID  -fPIC    -MMD -MF tmp/el8_amd64_gcc11/src/L1Trigger/TrackFindingTracklet/src/L1TriggerTrackFindingTracklet/VMStubME.cc.d /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/VMStubME.cc -o tmp/el8_amd64_gcc11/src/L1Trigger/TrackFindingTracklet/src/L1TriggerTrackFindingTracklet/VMStubME.cc.o
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/TrackletCalculatorDisplaced.cc:1665:56: warning: argument 'phiproj' of type 'double[5]' with mismatched bound [-Warray-parameter]
                                                 double phiproj[N_DISK],
                                                       ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/interface/TrackletCalculatorDisplaced.h:98:31: note: previously declared as 'double[4]' here
                       double phiproj[N_LAYER - 2],
                              ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/TrackletCalculatorDisplaced.cc:1666:56: warning: argument 'zproj' of type 'double[5]' with mismatched bound [-Warray-parameter]
                                                 double zproj[N_DISK],
                                                       ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/interface/TrackletCalculatorDisplaced.h:99:31: note: previously declared as 'double[4]' here
                       double zproj[N_LAYER - 2],
                              ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/TrackletCalculatorDisplaced.cc:1669:56: warning: argument 'phider' of type 'double[5]' with mismatched bound [-Warray-parameter]
                                                 double phider[N_DISK],
                                                       ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/interface/TrackletCalculatorDisplaced.h:102:31: note: previously declared as 'double[4]' here
                       double phider[N_LAYER - 2],
                              ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/src/TrackletCalculatorDisplaced.cc:1670:56: warning: argument 'zder' of type 'double[5]' with mismatched bound [-Warray-parameter]
                                                 double zder[N_DISK],
                                                       ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/8e5a30963b3e8e52e9fcfe21847b5d52/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-14-2300/src/L1Trigger/TrackFindingTracklet/interface/TrackletCalculatorDisplaced.h:103:31: note: previously declared as 'double[4]' here
                       double zder[N_LAYER - 2],
```
Could you please have a look? We would like to integrate llvm 16 in cmssw master IBs as soon as possible.

Many thanks,
Andrea.

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

This PR fixes mismatched array sizes in [TrackletCalculatorDisplaced.cc](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/TrackFindingTracklet/src/TrackletCalculatorDisplaced.cc) and [TrackletCalculatorDisplaced.h](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/TrackFindingTracklet/interface/TrackletCalculatorDisplaced.h) for the `TrackletCalculatorDisplaced::exacttracklet` function signature. Not having original knowledge of this function, I have replaced the implementation array sizes with the header declared sizes. @skinnari you are listed as the original author of these lines, would you please confirm that this is okay with you.

This PR (in theory) closes https://github.com/cms-sw/cmssw/issues/41677. @aandvalenzuela I figured you might like to be informed.

### PR validation:

All code builds, has had formatting applied, and passes existing code checks.

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
Thanks @aloeliger!

**Comment by aloeliger** [comment]
please test

**Comment by skinnari** [comment]
indeed, this seems like a straight out bug that somehow has not been caught before! thank you for fixing @aloeliger 

FYI @tomalin @gershtein

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
