### PR TITLE
[HGCal] Add unit test for HGCal material budget plots

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

Include a unit test for HGCal material budget plots in order for reviewers to inspect the regularly updated/created geometries. 

Running locally on lxplus the script according to time command took: 

real	17m39.955s
user 15m21.406s
sys	1m41.116s

The single_neutrino_cfg.py, which is used identically by the Tracker, is run in the glimpse of an eye, so instead of mixing this unit test with the Tracker one (essentially messing it up) I think it is better to create a new one. 

I hope the running time isn’t an issue. 

@vargasa : Thanks a lot for the suggestion and the help. 

#### PR validation:

Will check if the unit test runs fine in this PR. Locally, there wasn't any issue. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport. 

@rovere @felicepantaleo @ebrondol @vargasa

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by apsallid** [comment]
Could you please tell me how you add the last line in the test page here
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e3c092/9538/summary.html
that gives the link to the material budget plot? 

For the moment I am just changing the name in the address. It looks ok: 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e3c092/9538/materialBudgetHGCalPlots/

**Comment by vargasa** [comment]
> that gives the link to the material budget plot?

As I understand, it won't be shown until the new `BuildFile.xml` gets integrated. I.e it will be shown from the next PRs. You can check with @smuzaffar if that's the case

> For the moment I am just changing the name in the address. It looks ok:

The test works great!

**Comment by jfernan2** [comment]
+dqm

**Comment by cvuosalo** [comment]
I don't think we should be adding a 17-minute test to the unit tests. Who suggested adding this test?

**Comment by vargasa** [comment]
Hi @cvuosalo, I suggested the addition in an [earlier PR](https://github.com/cms-sw/cmssw/pull/31504). There's a similar test being performed for the Tracker, implemented last year (I never measured the execution time tho). @apsallid one of the things that can be done is to reuse the `single_neutrino....root` file that's generated for the Tracker, that may save help us saving some time. They way I see it is that is cheaper x minutes of machine time than hours from a scientist's time trying to figure out a problem that could have been spotted earlier :)

**Comment by rovere** [comment]
Ciao @cvuosalo thanks for checking the timing.
Since the aim of this test at PR level is to be sure that the machinery is alive and working, and not to validate the geometry every single time (please correct me if I'm wrong), I'm pretty sure some more sensible parameters could be found to run the test in a reasonable amount of time.

**Comment by apsallid** [comment]
@cvuosalo @rovere This is the most basic test that can be performed that proves if scripts are running normally. It takes 4 minutes. 

real	4m13.209s
user 2m47.140s
sys	0m40.569s

If 4 minutes is not acceptable then there is no reason to keep this unit test.  I can add it in our usual 
RelVal campaign validation workflow, but this will prove if it works in a specific prerelease and not the specific IB.

**Comment by cvuosalo** [comment]
I suppose four minutes for the test is acceptable.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
