### PR TITLE
Backport fixes for gen weights in NanoAOD (#31680, #31982, #31946, #31939, #32071)

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:
Backport of #31680, #31982, #31946, #31939, #32071. Fixes to Gen weight storage in NanoAOD

#### PR validation:

Tests in progress

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

#31680, #31982, #31946, #31939, #32071

Needed for Nano v8 production in 106X

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

changes inline with master.
(Size increase of about 2.5% in MC due to the PDF change (33-->103 weights))

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
