### PR TITLE
Remove EventSetup use from PdtEntry

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Users of the PdtEntry::setup method must now pass the ParticleDataTable they obtained from the EventSetup. All such cases were migrated to use esConsumes.

#### PR validation:

Code compiles after doing `git cms-checkdeps -a`.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

to get a cleaner test setup

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34581	ed39726
- code changes are in line with the PR description, to adapt to the interface changes in SimGeneral/HepPDTRecord/interface/PdtEntry
- jenkins tests pass and comparisons with the baseline show  no (relevant) differences

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
