### PR TITLE
Run2-alca84 Update Calibration Codes for Hcal using isolated tracks

### PR DESCRIPTION
**Pull request by bsunanda**
Added a few more parameters needed to estimate efficiency/purity of the trigger and the corresponding changes in the analysis macros

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@franzoni @arunhep Please approve this PR

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
