### PR TITLE
 L1TGlobalSummary and update of L1TGlobalUtils

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
L1TGlobalSummary and update of L1TGlobalUtils
updating #13416 for L1T summary report

@mulhearn

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Based on CMSSW_8_0_X_2016-02-28-1100
Compiles locally, but needs more testing for functionality...

**Comment by mulhearn** [comment]
Thank you!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
