### PR TITLE
Clean Up for Pixel Tracks - Follow-up to #41632

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This is a follow-up to #41632 taking into account the un-resolved comments (see [here](https://github.com/cms-sw/cmssw/pull/41632#issuecomment-1637005874)). 

I took the chance also to apply the changes in the cuts suggested by @CesarBernardes (see slide 5 [here](https://indico.cern.ch/event/1300029/contributions/5465602/attachments/2680232/4649242/pixelTracking_patatrackStudies_05062023_v3.pdf)). This is not strictly needed since all those parameters are tunable from the config, but I would take the chance to push it anyway here.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 14950.502, 160.502
- workflows = 12434.501, 14950.501, 160.501
- relvals_opt = -w upgrade,gpu,standard 
- relvals_opt_gpu = -w upgrade,gpu,standard

**Comment by AdrianoDee** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in GPU are spurious

**Comment by clacaputo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
