### PR TITLE
remove obsolete header (long ago moved to another spot)

### PR DESCRIPTION
**Pull request by davidlange6**
I don't see any remaining usage so lets finish the migration started in 2009

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test


On Jul 23, 2020, at 1:43 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



Pull request #30878<https://github.com/cms-sw/cmssw/pull/30878> was updated. @cmsbuild<https://github.com/cmsbuild>, @santocch<https://github.com/santocch> can you please check and sign again.

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
