### PR TITLE
Comphep singletop filter pythia8

### PR DESCRIPTION
**Pull request by alexeybaskakov**
Comphep Single Top Filter for Pythia 8.

### CODE REVIEW

**Comment by bendavid** [comment]
Has this already been merged and/or is there already a pull request for 75x/76x

**Comment by alexeybaskakov** [comment]
I'm not sure how to check if this request has been merged or not.  
I've tried to merge pull request by myself for 75x https://github.com/alexeybaskakov/cmssw/pull/2

**Comment by covarell** [comment]
Is this still of any use? I see the thread idle since a few months.

If so, you first still to make this PR for 76X

**Comment by alexeybaskakov** [comment]
Dear Roberto,

I'm not very familiar with git hub and may be something was done not
correctly.
In general I need to include singletop filter for pythia8 in CMSSW version
for future use.

Sincerely,
Alexey Baskakov


2015-10-15 11:26 GMT+03:00 Roberto Covarelli <notifications@github.com>:

**Pull request closed without merging**
