### PR TITLE
DD4hep: Augment tested features and enable runing the tests without disabling biglibs

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add G4 production cuts testing, assure their repeatability
* Make sure the tests are run without disabling biglibs
* Move a new DDDWorld in a cms namespace

#### PR validation:

Automatically tested in IB integration by ```scram b runtests```

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@civanch, @Dr15Jones please, review.

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones could you please have a look?

@ianna for my understanding, what is the rationale behind the move of DDDWorld inside the cms namespace?

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
