### PR TITLE
phase2 Tracker XMLs in 8X (flat and Tilted)  and WFs cleaning

### PR DESCRIPTION
**Pull request by boudoul**
This PR is introducing the xml files for the two supported version of the Phase2 Tracker : the Flat and Tilted cases .
I took the opportunity to remove old phase2 xmls from the past to start 8X with clean area.

Note that at this stage the phase2 Tracker(s) are not included in any phase2 workflow yet and will be done at the next iteration (to avoid to have a confusing big PR to review while the WFs are still being defined within the simulation group) .

At the same time I  created a placeholder for phase2 WFs in runTheMatrix , to be ready once they are completely defined (and removed all the old ones from the SLHC past...) 

@delaere FYI

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild, please test

**Comment by davidlt** [comment]
Why file per commit? Squash the commits with the same message into a single one. Also a more detailed description message would not hurt.

https://wiki.openstack.org/wiki/GitCommitMessages

**Comment by boudoul** [comment]
@davilt : that is definitely a good point - I can definitely make something better here , so I will let the test go (to already see if I screwed up something ) and meanwhile prepare a better PR with your recommendations .

**Comment by boudoul** [comment]
not clear why the test tests failed (the matrix outputs seem happy) - Anyway closing this PR for a one a bit better organized --> superseeded by PR 12913

**Pull request closed without merging**
