### PR TITLE
Puppi into mini aod

### PR DESCRIPTION
**Pull request by jshlee**
added puppi jet collection and puppi met into miniAODs

added jet charge, btagging, secondary vertex info and daughter links for puppi jets

added puppi weights as packed 8 bit into packcandidates

removed labels in puppi producer since only three different types of objects are produced

fixed the packing for liblogintpack, negative values were being lost

updated PackedCandidate ClassVersion to 17

added new iputs to PATPackedCandidateProducer, (PuppiWeight, PuppiCandsMap and PuppiCands) to save puppi weights into packcandidates and ValueMap for puppi to be able to map back to the puppi candidates from puppi jets to packcandidates

### CODE REVIEW

**Comment by slava77** [comment]
Jason,
please add a bit longer description for this change (at the top of this thread, by editing the first message), maybe add a link to slides or other details if they exist.
Thanks

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
please note that @gpetruc just spotted that the daughters rekeying is actually broken (running but refs point a bit random)... we will provide a fix asap

**Comment by gpetruc** [comment]
I have committed some fixes here https://github.com/jshlee/cmssw/pull/296
(it should be enough for Jason to merge it to update also this PR)

**Comment by monttj** [comment]
Yes, it would be better to have more description for this update.
Thank you,
Taejeong

**Comment by arizzi** [comment]
hi taejeong, please see #8122 for more details on this PR

**Comment by monttj** [comment]
+1
Thank you for the details.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Starting matrix tests since Jenkins results are incomplete.

**Comment by cvuosalo** [comment]
+1

For #8249 ad33789565d002dd3328a2a67c065cd4c894f831

This PR adds PUPPI (pile-up per particle ID) weights to MiniAOD. The simple addition of new content to MiniAOD should not change the calculation of reco quantities.

The Reco code change is satisfactory. Jenkins tests are OK, except that the comparison against the baseline did not complete. Short matrix tests against baseline  CMSSW_7_4_X_2015-03-13-1400 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
