### PR TITLE
Modernize TriggerNames

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Use more memory efficient data structure
- Avoid storing duplicate information to ROOT files
- Avoid a problem with std::vector::size_type on some compilers by just using std::size_t
- Added unit test

#### PR validation:

Code compiles and new unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
(for future reference)

> * Avoid a problem with std::vector::size_type on some compilers by just using std::size_t

Works around https://github.com/cms-sw/cmssw/issues/32497.

**Comment by makortel** [comment]
I'm fine with the changes, but would like to see cleaner comparisons with the next IB (and hence not restarting the tests yet).

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

Reported differences are in messages

**Comment by qliphy** [comment]
+1

**Pull request merged**
