### PR TITLE
Moved modules in L1Trigger/TextToDigi to be thread friendly

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the CMS deprecation warnings.

#### PR validation:

Code compiles without CMS deprecation warnings

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please abort
(trying to recover resources for the tests of more urgent PRs)

**Comment by aandvalenzuela** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
