### PR TITLE
Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1.

### PR DESCRIPTION
**Pull request by sifuluo**
#### PR description:

Duplicated for master merge.

Original PR at:
https://github.com/cms-sw/cmssw/pull/37179

### CODE REVIEW

**Comment by perrotta** [comment]
@sifuluo please apply code-format, as explained in https://github.com/cms-sw/cmssw/pull/37188#issuecomment-1063363289, so that tests can start

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
Now the master branch has moved to 12_4_X
Since you have already a backport to 12_2, please also prepare a backport for the intermediate 12_3 cycle, which will be used online after 12_2

**Comment by perrotta** [comment]
+1

**Pull request merged**
