### PR TITLE
Fixing logic for evaluating trajectory parameters

### PR DESCRIPTION
**Pull request by ArturAkh**
#### PR description:

Fixing logic of ConversionHitChecker, as discussed in issue https://github.com/cms-sw/cmssw/issues/41813

#### PR validation:

As discussed in https://github.com/cms-sw/cmssw/issues/41813 the introduced fix should restore the behaviour which was originally introduced to the class.

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by swagata87** [comment]
type bugfix

**Comment by mandrenguyen** [comment]
please test

**Comment by ArturAkh** [comment]
Seems like the failed tests are related to access problems at eoscms.cern.ch

**Comment by mandrenguyen** [comment]
@ArturAkh I don't see any differences in the comparisons.  Is that expected?

**Comment by ArturAkh** [comment]
Hi @mandrenguyen,

As far as I understand, the case that `closest > 0` is rare, but it exists, such that the evaluation would required to be done on a larger scale.  I suppose the tests are run on too small sets of exemplary events. As pointed out in the corresponding issue, this pull request is meant to restore originally introduced behaviour.

Cheers,

Artur

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
