### PR TITLE
PPS: removal of obsolete alignment data

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

Two obsolete and unused packages containing Roman-Pot alignment data are removed.

(CT)PPS now uses DB for storing alignment corrections, thus no need for the removed packages is expected in the future.

Since the removed packages are not used, no change in test results is expected with this PR.

#### PR validation:

``runTheMatrix.py --ibeos -l limited`` gave ``35 34 33 25 17 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed``

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2

**Comment by silviodonato** [comment]
@mrodozov could you remove the two packages?

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
@mrodozov it is sufficient https://github.com/cms-sw/cms-bot/pull/1400, isn't it?

**Pull request merged**
