### PR TITLE
FSQ DQM update for 7_4 series

### PR DESCRIPTION
**Pull request by fruboes**
Contains the following changes:
- All development from https://github.com/cms-sw/cmssw/pull/6942 (reverted PR)
- Fixes from https://github.com/cms-sw/cmssw/pull/7108 (reverted PR)
- Fix for a crash in HI workflow (missing products needed to apply JEC). Fix disables corrected jets production and most of FSQ trigger DQM histograms. The only histograms left (or planned to be added in the future in FSQ trigger DQM) for the HI workflow are for minbias like paths (currently ZeroBias+ single pixel track trigger)

Testing was done in a normall (non-HI) workflow with edm file missing the same product as in HI case.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @fruboes 
it seems to me that the HI workflow is still failing. have a look at:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7267/1994/DQMTestsResults/DQMTestsResults/12/

where you can find config file and log.
how did you test your changes?

thanks,
F.

**Comment by fruboes** [comment]
Hi @deguio,

 sorry, I thought I tested the fix in an equvalent environment, but it looks like I was wrong and  bitten by some python subtleness. The fix to fix removes the DQMOffline_Trigger_HI_cff file and implements the changes inside DQMOfflineHeavyIons_cff (similarly to HI specific changes from other systems). This time properly tested by running driver12a.sh from HI tests.

 sorry for inconvienience,
    Tomasz

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
many thanks @fruboes

**Comment by ktf** [comment]
Looks like we still have a few LogError related to this:

```
%MSG-e DQMGenericClient:  DQMGenericClient:fsqClient@endJob  21-Jan-2015 09:46:35 CET PostEndRun DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/FSQ !!!
```

for example in step 5 of:

- 8.0
- 7.0
- 4.22	 
- 1308.0	 
- 1307.0

@fruboes can you have a look?

**Comment by fruboes** [comment]
Dear @ktf,

 could you give me a more beginner friendly explanation of the part starting with "for example"  of your message :) ?

 When it comes to error messages - is this only for HI workflow? If yes, this most likely comes from the fact that minbias like triggers are not yet in HI menu (but still I need to look, now I dont know where to find them/how to reproduce)

 cheers,
  Tomasz

**Comment by deguio** [comment]
ciao @fruboes 
the number mentioned by @ktf are the reference to the runTheMatrix workflow.
you can run them and reproduce the error with

runTheMatrix -l 8.0

you should be able to find the same errors in the log saved locally.

**Comment by deguio** [comment]
it is what is run automatically in the jenkins tests. you can access the logs at:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7267/2004/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step5_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

**Comment by deguio** [comment]
and no... it comes for other WF as well. the ones run automatically are accessible at:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7267/2004/runTheMatrix-results/

ciao,
F.

**Comment by ktf** [comment]
Thank you Fede for all the explanations and sorry to @fruboes for the cryptic message.

**Comment by fruboes** [comment]
Thanks for the explanation! It looks like the problem is visible only for cosmics workflows. In step3 DQMOffline/Configuration/python/DQMOfflineCosmics_cff.py file is used, where there is no FSQ dqm source module included (which is correct I guess). Than in step5 fsq client module is included from StandardSequences/python/HarvestingCosmics_cff.py (through HLTriggerOffline.Common.HLTValidationHarvest_cff).

 I guess the correct fix would be to modify the HarvestingCosmics_cff.py in such way the FSQ client module doesnt get called. Please confirm, that this is the right way to go, if so I'll make the fix,

Cheers,
  Tomasz

**Comment by deguio** [comment]
hello @fruboes 
what you wrote makes sense.
since this PR has been merged, the changes will have to be submitted with a new one.
thanks,
F.

**Comment by fruboes** [comment]
Done - see https://github.com/cms-sw/cmssw/pull/7321  

Tomasz

**Comment by ktf** [comment]
@cmsbuild please test

**Pull request merged**
