### PR TITLE
Timing, Laser and Hot cell quality plots adjustments  [12_4_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR does the following in ECAL DQM plots:
 1. Changes the threshold in Timing quality summary to reduce the false positives in Ecal Endcaps
 2. Changes the amplitude threshold in laser quality for the forward region of Ecal Endcaps
 3. Disables the condition for setting entire FED to RED in Hot Cell quality as it's creating false alarms in the presence of single hot towers.
 
#### PR validation:
Validated by running the standard online Ecal DQM configuration and checking the output on a test DQM GUI. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of master PR: https://github.com/cms-sw/cmssw/pull/39161. Backport is done to have the changes available in 12_4_X which is currently used in production.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at P5

**Comment by micsucmed** [comment]
please test

**Comment by emanueleusai** [comment]
re-testing after update

**Comment by micsucmed** [comment]
Hi @abhih1, would you mind checking the DQM playback GUI for the changes made in this PR? Let me know if everything seems ok. Thanks!

**Comment by abhih1** [comment]
Looks good. Thanks!

**Comment by emanueleusai** [comment]
tests at P5 ok

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39161

**Comment by perrotta** [comment]
> This is a backport of master PR: #39161. Backport is done to have the changes available in 12_4_X which is currently used in production.

... and 12_5_X will be used in production next
Please provide also a 12_5_X backport of whatever you plan to backport to 12_4

**Comment by abhih1** [comment]
> > This is a backport of master PR: #39161. Backport is done to have the changes available in 12_4_X which is currently used in production.
> 
> ... and 12_5_X will be used in production next Please provide also a 12_5_X backport of whatever you plan to backport to 12_4

Hi @perrotta Here is the backport to 12_5_X. https://github.com/cms-sw/cmssw/pull/39327

**Comment by perrotta** [comment]
Thank you @abhih1 !

**Comment by perrotta** [comment]
+1

**Pull request merged**
