### PR TITLE
Run3-sim151 Modify the run script for the SIM step to get hits in the ZDC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the run script for the SIM step to get hits in the ZDC

#### PR validation:

Ran using test script in SimG4CMS/Calo/test/python to run with the standard and new ZDC XML file

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

@bsunanda , likely this PR should be backported to 13_3_X?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
