### PR TITLE
exclude channels with unstable pedesta

### PR DESCRIPTION
**Pull request by argiro**
With weight reconstruction the pedestal was calculated online. The multifit method uses pedestals from the database. Certain categories of channels have unstable pedestal settings, this PR excludes these channels from reconstruction

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@argiro , should we expect changes only in data or in MC tests as well?

**Comment by argiro** [comment]
> On 18 Dec 2015, at 14:09, Slava Krutelyov <notifications@github.com> wrote:
> 
> @cmsbuild please test
> 
> @argiro , should we expect changes only in data or in MC tests as well?
> 

only data
S.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Hoping previous error was transient

**Comment by cvuosalo** [comment]
Extended test in progress...

**Comment by cvuosalo** [comment]
@argiro: Why do you say that MC won't be changed? ttbar MC workflows are showing a number of tiny changes in ECAL rec hit quantities in the results from the Jenkins tests:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-17-1100+12824/11865/validateJR/all_OldVSNew_TTbarFSwf5p1/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-17-1100+12824/11865/validateJR/all_OldVSNew_TTbarPUwf25202p0/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-17-1100+12824/11865/validateJR/all_OldVSNew_TTbarPUwf50202p0/

**Comment by cvuosalo** [comment]
The results of an extended test of workflow 134.805_RunMET2015C with 200 events against baseline CMSSW_8_0_0_pre4 show a number of very tiny, insignificant differences related to the expected changes in ECAL rec hits but do not show any significant differences.

Reco is ready to approve this PR once the issue of the MC differences is resolved.

**Comment by argiro** [comment]
Hi, I thought the MC payload did not include the flag for channels with stuck pedestal DAC, but evidently it does.
From my side the PR is good to go

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12824	c05665e
- changes in the code are as described
- jenkins tests pass and comparisons with baseline show small differences starting from EB and EE rechits reduction (about 1 in 10K, depending on the sample) and propagated downstream. There doesn't seem to be any particular correlation with other activity in the event.

**Pull request merged**
