### PR TITLE
bug fix for NoBPTX EXO trigger prompt monitoring

### PR DESCRIPTION
**Pull request by jalimena**
Fix a minor bug for NoBPTX EXO trigger prompt monitoring.

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbulid, please test

**Comment by jalimena** [comment]
The tests have not run, possibly because @mtosi made a typo in her request... I don't think I have the power...

**Comment by jalimena** [comment]
@cmsbuild please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
