### PR TITLE
Phase2-gex166 Add files to investigate differences between DDD and DD4hep geometries in 2026D98 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add files to investigate differences between DDD and DD4hep geometries in 2026D98 scenario

#### PR validation:

Use the scripts inside Validation/Geometry/test and SimG4Core/PrintGeomInfo

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
