### PR TITLE
migrate `PixelVTXMonitor` to `DQMEDAnalyzer`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all. Part of the migration at https://github.com/cms-sw/cmssw/issues/36404.
Besides removing the legacy type, modernized the code: 
   * merged implementation with header;
   * removed unused methods;
   * range-based loops
   * modernized event data access;

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

-----
##### Note to reviewers, there are other modules needing to be migrated in this package, but they do require substantially more work in order to guarantee thread safety. Those will be addressed at a second time.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:

 - addpkg = DQM/Integration

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db
 * unit tests pass
 * code changes are according to the PR description 
 * note: SA noticed some further possible clean-ups (dead assignments, legacy modules in `BeamMonitorBx`, `AlcaBeamMonitorClient`, `BeamConditionsMonitor`, and thread safety related fixes):
 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-968b3d/24697/llvm-analysis/

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
