### PR TITLE
MTD validation: update cluster histograms

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Addition of histograms for better monitoring of cluster characteristics and position.

#### PR validation:

On workflow 35034.0 the observed ```dqmMemoryStat``` memory increase in normal conditions (without activating flag for dedicated studies) is of about 3 kB:

```
71c71
< 1136.00 KiB      MTD/ETL
---
> 1135.12 KiB      MTD/ETL
123c123
< 243.73 KiB       MTD/BTL
---
> 241.82 KiB       MTD/BTL
411c411
< Total bytes: 413140.61 KiB
---
> Total bytes: 413137.82 KiB
```

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
Hi @fabiocos 
I guess the binning in the plots for the unmatched cluster energy is expecting larger energies from more statistics, right?

https://tinyurl.com/y8p9er6t
Thanks

**Comment by fabiocos** [comment]
@jfernan2 in principle there should be no unmatched cluster. I've already removed plots for time and eta of these cases, the binning is matching that for the regular clusters. I may reduce the number of bins by just plotting the log10 of the energy

**Comment by jfernan2** [comment]
It is fine. I was just wondering why the energy was accumulating in the left side of the plot, I thought it was due to the reduced stats of the Jenkins test. You are adding less than 3KB of new MEs, this is definitely not a problem

**Comment by fabiocos** [comment]
@jfernan2 we are speaking just of 1 kB, nevertheless I believe that log10 would ok for this purpose (slightly more than a counter). In case a problem is observed, amore detailed analysis will be needed anyway

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
