### PR TITLE
Utilities/StaticAnalyzers: Remove the dependence on py2-dablooms package.

### PR DESCRIPTION
**Pull request by gartung**
This requires an executable based on the dablooms C library to generate bloom.bin from classnames.txt.
Updated classname-blmflt.py to remove pydablooms calls. Moved bloom.bin generation to run_class_dumper.sh.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by gartung** [comment]
Requires https://github.com/cms-sw/cmsdist/pull/5315

**Comment by Dr15Jones** [comment]
What is the purpose of bloom.bin ?

**Comment by gartung** [comment]
It is loaded by CmsSupport to determine if a class is one that should be examined.

**Comment by smuzaffar** [comment]
@gartung , how is this file generated? how often we have to update it?

**Comment by gartung** [comment]
It is regenerated and used whenever run_class_dumper.sh is run. Otherwise the default bloom.bin from scripts is used.

**Comment by gartung** [comment]
Every time cms-bot/run_clang_static_analysis is run in a Jenkins job, a new classnames.txt and a new bloom.bin is generated. This is used for all static analysis checks in that job.

**Comment by gartung** [comment]
I removed bloom.bin from the PR but then I put it back because it has not been updated since 2016,

**Comment by Dr15Jones** [comment]
What is the purpose of classname-blmflt.py  now?

**Comment by gartung** [comment]
It is still needed to extract the class names from the classes.txt file producer by the class-dumper clang compiler module. It can be renamed.

**Comment by gartung** [comment]
@smuzaffar has network been tested with python3. It is also used in the StaticAnalyzers scripts. NetworkX 2.4 was just released this month and claims python3 compatibility,

**Comment by gartung** [comment]
Please test with cms-sw/cmsdist#5315

**Comment by smuzaffar** [comment]
@gartung , we have Network2.3 ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/master/pip/requirements.txt#L133 ) for python3 and simple test 'import networkx' works for bopth python2 and 3

**Comment by gartung** [comment]
@smuzaffar how can I trigger a build that runs the static analyzer job.

**Comment by smuzaffar** [comment]
yes you need to run  cms-bot/run_clang_static_analysis locally. It is post IB job which can not be run for PR tests.

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar the cms-bot/run_clang_static_analysis script completed without any failure.

**Comment by smuzaffar** [comment]
and did it generate reasonable web pages. Can you compare the results with https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_11_0_X_2019-10-30-2300/slc7_amd64_gcc820/llvm-analysis/index.html

**Comment by fabiocos** [comment]
@gartung @smuzaffar as expected this clashes with the update #28314 and needs to be rebased

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5315

**Comment by gartung** [comment]
The number look similar. Once the personal website creation completes the report should be available at https://cern.ch/gartung/2019-10-31-222708-8166-1/index.html

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
