### PR TITLE
Move CSC local trigger patterns to pattern bank

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR moves the ALCT/CLCT trigger patterns defined in `CSCAnodeLCTProcessor` and `CSCCathodeLCTProcessor` to a new class `CSCPatternBank`. It is done in preparation for changes to the CLCT trigger patterns which is anticipated to happen sometime during Run-3. This PR should be integrated after https://github.com/cms-sw/cmssw/pull/27956. The relevant commit is in fact https://github.com/cms-sw/cmssw/commit/46c1fe3bed502ff8d301cac85ff156440fbb62a3. 

Edit: The key wire offsets were separated from the `alct_pattern_envelope` in an additional commit. Historically, both the ALCT envelope and the offsets were contained in an array of size `CSCConstants::NUM_ALCT_PATTERNS`, which happens to be conveniently 3. However, the number ALCT patterns is independent of the pattern envelope or the key wire offsets. In fact, adding an extra ALCT pattern (for displaced muons for instance) would end up breaking the old `alct_pattern_envelope` array. 

Edit: `pattern2007_offset` and 'pattern2007' names were changed to `clct_pattern_offset` and `clct_pattern`. 

#### PR validation:

I ran the matrix test 20434.0 successfully.

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
At some point I will have a closer look at https://github.com/cms-sw/cmssw/blob/master/L1Trigger/CSCTriggerPrimitives/python/cscTriggerPrimitiveDigis_cfi.py#L57-L60. The ALCT trigger has been in "trigger mode" (`alctTrigMode`) since 2008, so that really only a single pattern is used to build ALCTs. Accelerator patterns are not used. So it wouldn't be a bad idea to remove or modernize old patterns and old functions such as https://github.com/cms-sw/cmssw/blob/master/L1Trigger/CSCTriggerPrimitives/interface/CSCAnodeLCTProcessor.h#L195-L211. @valuev What do you think?

**Comment by fabiocos** [comment]
please test

**Comment by dildick** [comment]
@rekovic Can you rerun the tests, please?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic could you please have a look?

**Comment by dildick** [comment]
@rekovic

**Comment by rekovic** [comment]
@dildick 
Have we checked what effect it has on the Phase-II EMTF++ reconstruction (not integrated here)

Otherwise
+1

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
@rekovic Perhaps @jiafulow can check this.

**Comment by jiafulow** [comment]
Hi Sven,

I think you should check your own code changes and make sure they don't break EMTF, before you ask someone else to check it for you. I'm not a continuous integration bot.

Jia Fu

**Comment by dildick** [comment]
@rekovic I don't see any changes in the validation tests. Let me point out that this PR does not change any of the patterns. What I do is put the patterns in a dedicated pattern bank, as opposed to having them in the processors.

**Comment by dildick** [comment]
Rebased branch

**Comment by dildick** [comment]
Matrix test  20434.0 runs fine. Let me try this out on a PU200 sample I'm studying for the L1T TDR.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic @benkrikler could you please check the latest update?

**Comment by rekovic** [comment]
@dildick 
> Matrix test 20434.0 runs fine. Let me try this out on a PU200 sample I'm studying for the L1T TDR.

What are the results here ?

**Comment by rekovic** [comment]
It would be good to hear back about the study mentioned above and to know how it effect the reconstruction down stream. 

Otherwise +1.

**Comment by dildick** [comment]
@rekovic My apologies. I will send you the results asap.

**Comment by dildick** [comment]
@rekovic The more recent plots can be found here: https://indico.cern.ch/event/858823/contributions/3616449/attachments/1933478/3203155/L1T_PlotsForApproval_GEMCSC_SD_20191024.pdf. They are similar to what I sent you last week, although it also includes PU0 and PU300. Could you proceed and approve this pull request?

**Comment by fabiocos** [comment]
@rekovic do you confirm your "Otherwise +1"?

**Comment by fabiocos** [comment]
@rekovic I understand that technically you are ok with this PR, that is pending since quite sometime. I would be inclined to integrate it in next IB, and let you follow with @dildick on the results for a possible further update

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@fabiocos 

> @rekovic I understand that technically you are ok with this PR, that is pending since quite sometime. I would be inclined to integrate it in next IB, and let you follow with @dildick on the results for a possible further update

Yes. That is fine.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
