### PR TITLE
HeavyIon: Add E/p cut to electrons and extend event content for electron collections.

### PR DESCRIPTION
**Pull request by harmonicoscillator**
This PR adds an E/p cut of <2 to the Heavy Ion electron reconstructions chain. The reason for this cut is to remove fake jets which arise from low-pt (very-curved) tracks attached to high pt ecal clusters. Theses "electrons" are then included in jets, but since the track is very curved the ecal cluster is not actually inside the jet.
Please see motivation slides here:
https://twiki.cern.ch/twiki/pub/CMS/PhotonAnalyses2015/20150825_fakerate.pdf
Additional documentation can be provided on request.

Additionally, this PR includes two additions to the Heavy Ion Event Content for electron-related quantities.

This PR should not affect pp workflows in any way.
Matrices 5.1 and 140.53 worked locally for me.

This will also be backported to 7_5_X.

This PR supersedes @doanhien PRs #11193 and #11191, both of those should be closed.

### CODE REVIEW

**Comment by richard-cms** [comment]
75X backport PR is #11224

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11223 b7020189667b06cdaced40934d46139c29888e18

For Heavy Ions, adding E/p cut to electrons.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11223/7995/summary.html) against baseline CMSSW_7_6_X_2015-09-09-2300 show no significant differences. An extended test with 70 events of workflow 140.53_RunHI2011 against baseline CMSSW_7_6_0_pre4 also shows no significant differences. CPU timing and product sizes also did not change significantly.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
