### PR TITLE
CMSSW_7_6_X DQM updates for AlphaT HLT paths (v2)

### PR DESCRIPTION
**Pull request by MarkBaber**
Addition of DQM monitoring to new AlphaT path, supersedes https://github.com/cms-sw/cmssw/pull/10703

Addition of DQM monitoring for the following HLT paths:
- HLT_PFHT200_PFAlphaT0p51_v
- HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v
- HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v
- HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v
- HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v
- HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v

Remove number of monitoring histograms

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by MarkBaber** [comment]
Unfortunately I can't interpret  this output, could you describe what you think the problem is?

It says the error is from 'runtestPhysicsToolsPatAlgos', could this be affected by changes to the DQM? The tests for https://github.com/cms-sw/cmssw/pull/10878 https://github.com/cms-sw/cmssw/pull/10879 finished fine without error.

**Comment by danduggan** [comment]
@MarkBaber I believe this is unrelated, we can test with the next IB.

**Comment by MarkBaber** [comment]
Hi Dan,

If the next IB is ready could we test again? There is a trigger JIRA request that has been waiting for this PR to be concluded.

Many thanks!

**Comment by danduggan** [comment]
@MarkBaber, I'll retrigger this in ~1hr when the next IB is ready (from what I saw this morning things were still broken).

**Comment by MarkBaber** [comment]
Hi Dan, do you think it's ready to run the tests again?

**Comment by danduggan** [comment]
Hey Mark, unfortunately not - the latest IB still has this issue, so we'll
have to wait until things are working again.

**Comment by MarkBaber** [comment]
Hi Dan, do you know if the IB issue been fixed yet?

**Comment by danduggan** [comment]
please test
@MarkBaber I believe as of this morning the IB is fixed.

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
+1

**Pull request merged**
