### PR TITLE
JetMET validation for Phase2 full reco

### PR DESCRIPTION
**Pull request by jdamgov**
JetMet validation (w/o DQM portion) for the Phase2 full reco.
This is only a temporary solution until all other sub-systems are prepared for running the standard validation

Supersedes PR15407

@kpedro88

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15466 95d520753e9764e68d755386f7f67a4b9a525b3c

Temporary Jet-MET validation for Phase 2 without DQM.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-16-1100 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
