### PR TITLE
[101X] [New GTs] Updated conditions for 2018,7,6 MC scenarios, and for Data (CTPPS geometry added)

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI data

   * **RunI HLT processing** : [100X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_frozen_v1) as [101X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_frozen_v1/101X_dataRun2_HLT_frozen_v1):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

   * **RunI Offline processing** : [100X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_v1) as [101X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_v1/101X_dataRun2_v3):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

## RunII data

   * **RunII HLTHI processing** : [100X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLTHI_frozen_v1) as [101X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLTHI_frozen_v1/101X_dataRun2_HLTHI_frozen_v2):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

   * **RunII HLT relval processing** : [100X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_relval_v1) as [101X_dataRun2_HLT_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_relval_v1/101X_dataRun2_HLT_relval_v2):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

   * **RunII Offline processing** : [100X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_v1) as [101X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_v1/101X_dataRun2_v3):
      * CTPPS_Geometry
      * SiPixelGainCalibrationHLT
      * JEC data
      * EcalPFRecHitThresholds

   * **RunII Offline relval processing** : [100X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_relval_v1) as [101X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_relval_v1/101X_dataRun2_relval_v3):
      * CTPPS_Geometry
      * SiPixelGainCalibrationHLT
      * JEC data
      * EcalPFRecHitThresholds

   * **RunII Prompt processing** : [100X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_PromptLike_v1) as [101X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_PromptLike_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_PromptLike_v1/101X_dataRun2_PromptLike_v1):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

   * **RunI HLT processing** : [100X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_frozen_v1) as [101X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_frozen_v1/101X_dataRun2_HLT_frozen_v1):
      * CTPPS_Geometry
      * EcalPFRecHitThresholds

## RunI simulation
Added EcalPFRecHitThresholds in all GTs

## RunII simulation

   * **RunII Asymptotic scenario** : [100X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_asymptotic_v2) as [101X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_asymptotic_v2/101X_mcRun2_asymptotic_v1):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

   * **RunII CRAFT scenario** : [100X_mcRun2cosmics_startup_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2cosmics_startup_deco_v2) as [101X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2cosmics_startup_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2cosmics_startup_deco_v2/101X_mcRun2cosmics_startup_deco_v1):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

   * **RunII Heavy Ions scenario** : [100X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_HeavyIon_v3) as [101X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_HeavyIon_v3/101X_mcRun2_HeavyIon_v2):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

   * **RunII Ideal scenario** : [100X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_design_v2) as [101X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_design_v2/101X_mcRun2_design_v1):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

   * **RunII Proton-Lead scenario** : [100X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_pA_v2) as [101X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_pA_v2/101X_mcRun2_pA_v1):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

   * **RunII Startup scenario** : [100X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_startup_v2) as [101X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_startup_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_startup_v2/101X_mcRun2_startup_v1):
      * CTPPS_Geometry_2016
      * EcalPFRecHitThresholds

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [100X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v3) as [101X_mc2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_peak_v3/101X_mc2017cosmics_realistic_peak_v2):
      * CTPPS_Geometry_101YV2
      * PixelGain DAQ AnalysisMask
      * JEC 2017
      * EcalPFRecHitThresholds

   * **PhaseI 2017 cosmics scenario** : [100X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v3) as [101X_mc2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_deco_v3/101X_mc2017cosmics_realistic_deco_v2):
      * CTPPS_Geometry_101YV2
      * PixelGain DAQ AnalysisMask
      * JEC 2017
      * EcalPFRecHitThresholds

   * **PhaseI 2017 design scenario** : [100X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v3) as [101X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_design_IdealBS_v3/101X_mc2017_design_IdealBS_v2):
      * CTPPS_Geometry_101YV2
      * PixelGain DAQ AnalysisMask
      * JEC 2017
      * EcalPFRecHitThresholds

   * **PhaseI 2017 realistic scenario** : [100X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v3) as [101X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_realistic_v3/101X_mc2017_realistic_v2):
      * CTPPS_Geometry_101YV2
      * PixelGain DAQ AnalysisMask
      * JEC 2017
      * EcalPFRecHitThresholds

## 2018

   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v9) as [101X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v9/101X_upgrade2018cosmics_realistic_deco_v3):
      * SiPixelQuality
      * HcalChannelQuality HcalGains HcalSiPMParameters
      * ZeroMaterial
      * CTPPS_Geometry_2018
      * PixelGain DAQ AnalysisMask
      * EcalPFRecHitThresholds

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v7) as [101X_upgrade2018_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v7/101X_upgrade2018_design_v3):
      * HcalChannelQuality HcalGains HcalSiPMParameters
      * ZeroMaterial
      * CTPPS_Geometry_2018
      * PixelGain DAQ AnalysisMask
      * EcalPFRecHitThresholds

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v11) as [101X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v11/101X_upgrade2018_realistic_v2):
      * SiPixelQuality HcalGains HcalSiPMParameters
      * HcalChannelQuality
      * ZeroMaterial
      * CTPPS_Geometry_2018
      * PixelGain DAQ AnalysisMask
      * EcalPFRecHitThresholds

## Upgrade
   
   * **PhaseII realistic scenario** : [100X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2023_realistic_v1) as [101X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2023_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2023_realistic_v1/101X_upgrade2023_realistic_v1):
      * CTPPS_Geometry_2018
      * CTPPSPixelGain
      * CTPPSPixelDAQCTPPSPixelAnalysisMask
      * SiPixelQuality
      * EcalPFRecHitThresholds

   * **postLS2 realistic scenario** : [100X_postLS2_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_realistic_v2) as [101X_postLS2_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_realistic_v2/101X_postLS2_realistic_v1):
      * CTPPS_Geometry_2018
      * EcalPFRecHitThresholds

   * **postLS2 design scenario** : [100X_postLS2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_realistic_v2) as [101X_postLS2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_design_v2/101X_postLS2_design_v1):
      * CTPPS_Geometry_2018
      * EcalPFRecHitThresholds

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I think the root cause for the HIon failures is this:
```
%MSG
----- Begin Fatal Exception 22-Feb-2018 06:27:17 CET-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------
```
ie, payload provided by the HIon MC GT not updated?

**Comment by ianna** [comment]
@Martin-Grunewald - FYI, the #22264 which needs this PR will switch to consume its geometry from DB. Their default python configuration fragment will change. I think, it is possible that some HLT configurations should change as well.

**Comment by ianna** [comment]
@lpernie - this PR also updates 2019 and 2023 GTs. Please, update the description.

**Comment by Martin-Grunewald** [comment]
@ianna 
We seem not to use CTPPS yet at HLT...

**Comment by lpernie** [comment]
Hi @Martin-Grunewald , @rekovic 
For the mcRun2 HeavyIon this is the difference wrt the baseline:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_HeavyIon_v3/101X_mcRun2_HeavyIon_v1

The Tag we are using is: L1TCaloParams_collisions_HI_v1_mc
I remember an old email exchange you had with Arun on this (wf 145.0 failing in 94X), maybe the fail is related?

**Comment by Martin-Grunewald** [comment]
Why did the mc HI GT need the L1T update? The L1T code in CMSSW_10_1_X so far works fine with the old payload... ??

**Comment by Martin-Grunewald** [comment]
Are you referring to the long saga of the no-hack condition PR which went throgh several revisions was reverted and re-reverted and fixed  - https://github.com/cms-sw/cmssw/pull/20957 ?

**Comment by lpernie** [comment]
Hi @Martin-Grunewald ,
yes I now see the problem.
Please confirm this is the correct reasoning:
. L1TCaloParams_collisions_HI_v1_mc is to be used in mcRun2_HeavyIon GT.
. In the past this TAG has been provided to the GT 100X_mcRun2_HeavyIon_v3, but not approved in the 100X_mcRun2_HeavyIon_Queue.
. So now that I made the new TAG from the old queue I missed it.

If so the correct action is use L1TCaloParams_collisions_HI_v1_mc instead than L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET in mcRun2_HeavyIon

**Comment by lpernie** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Indeed this is my understanding.
Perhaps just update the initial description pointing to the v2 HIon mc GT now.

**Comment by lpernie** [comment]
Yes, done.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
At the beginning I though it was a glitch. It fails, but I it doesn't not print any hint. I will check tomorrow since is quite late now.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
I rerun the test assuming this was a temporary problem:
# in: /build/cmsbld/jenkins/workspace/ib-any-integration/runTheMatrix-results going to execute cd 10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU
 cmsDriver.py step4  --conditions auto:phase1_2017_realistic -s HARVESTING:@standardValidation+@standardDQM+@ExtraHLT+@miniAODValidation+@miniAODDQM --pileup_input das:/RelValMinBias_13/CMSSW_10_0_0_pre2-100X_mc2017_realistic_v1-v1/GEN-SIM -n 10 --era Run2_2017 --filein file:step3_inDQM.root --scenario pp --pileup AVE_35_BX_25ns --filetype DQM --geometry DB:Extended --mc  --fileout file:step4.root  --suffix "-j JobReport4.x------------
ERROR TIMEOUT

**Comment by lpernie** [comment]
The problem is explained:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22290/26396/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step2_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT.log

Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012B/SinglePhoton/RAW/v1/000/194/533/1084D9DA-AEA2-E111-B3AB-001D09F24DA8.root'

Once again I think this is just a temporary problem, even if now this is happening very often.

Re-triggering the tests.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
