### PR TITLE
Don't recluster jets in HI miniAOD for Run 3 

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Jets were being reclustered in the PAT step for heavy ions, as the jet algorithm had been updated between the time the last data were reconstructed (2018), and the first miniAOD campaign (2020). 
For the upcoming data (era=pp_on_PbPb_run3), the miniAOD will be done concurrently with the reconstruction such that this is no longer necessary. 
This PR removes the reclustering for that era, as well as legacy b-tagging, which is no longer needed.  DeepCSV is activated in its place.  Finally, an electron fix for 2018 reMiniAOD is also removed that is no longer necessary. 

#### PR validation:

Tested 159, 140.5611 and 158.01

### CODE REVIEW

**Comment by clacaputo** [comment]
Hi @mandrenguyen did you do any performance comparisons in `159`? Naively, I'd expect a reduction in timing

**Comment by mandrenguyen** [comment]
Hi @clacaputo We should see a large speedup of PAT, but that will not be super evident when it's run concurrently with reco (as in 159).  The best place to see this would be in a stand-alone re-miniAOD workflow like 158.01.  That wf is for 2018 though, where the reclustering is necessary, unless the 2018 PbPb data is re-reco'd.  For Run 3, we don't yet have a re-miniAOD MC RelVal wf.   How about I add a 159.01 to this PR for that purpose?
  
For reasons that are a bit complicated to explain here, we plan to produce miniAOD at the HI T2 (not together with prompt reco), such that the PAT timing is an important consideration. 

Note also that without this PR, Run 3 HI re-miniAOD (i.e., not concurrently with reco) doesn't even run due to a collection label issue.  I was actually trying to solve that issue when I realized that we should really remove the reclustering.

**Comment by clacaputo** [comment]
> How about I add a 159.01 to this PR for that purpose?

I think it's a good idea

**Comment by mandrenguyen** [comment]
The new 159.01 is taking 0.5 sec/ev, but most of that is in the gen particle validation.
Unfortunately, I didn't manage to evaluate the effect of this PR, as the re-miniAOD wasn't working prior.  I tried to compare to 158.01, which still has the reclustering, but the input files seem inaccessible.

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Hi @mandrenguyen 
I'm not I understand the strategy of the PR test here. The goal seems to be MiniAOD that comes together with reconstruction, not reminiaod. Why do we have reminiaod here for the PR test, instead of updating HI Run3 workflow? Do I miss something from the PR description? Thanks.

**Comment by srimanob** [comment]
OK, this is more clear now. Thanks @mandrenguyen 

Just my 2 cents: 
(1) I don't see 159.01 is triggered in the PR test. Should we do it here?

(2) One thing that HI workflow does not reflect is the real production. I assume in the real situation, you will start from AOD, not GEN-SIM-RECO. I don't expect any issues, i.e. broken of MiniAOD when start from AOD. But it is quite simple to make it happen also in relvals. I let's you and PdmV decide on this. I am happy to sign this PR anyways (just after the trigger of 159.01 if needed).

**Comment by mandrenguyen** [comment]
Yes, someone please trigger 159.1 :-)

Regarding AOD as input, there is currently not a suitable dataset produced in relval.   When the real 2022 PbPb data arrives, we will add a workflow like 140.5611, which tests AOD --> mAOD for 2018 data.  In the meantime, I'm fairly confident that if it works from RECO, it will work from AOD, but we will test this manually prior to the data taking.

**Comment by clacaputo** [comment]
test parameters:

- workflow = 159.1

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by clacaputo** [comment]
+reconstruction

- jets reclustering disabled for Run3 HI miniAOD
- new wf `159.01` added for checking HI re-miniAOD performances

**Comment by bbilin** [comment]
+pdmv

**Comment by perrotta** [comment]
+1
- I assume that the pairDiscriVector being empty for slimmedJets in wf 312 is an expected consequence of this PR. While we merge it for the nightly IB, please confirm

**Pull request merged**
