### PR TITLE
Improvements for Tracker Alignment `DiMuonValidation`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to inject in release few improvements for Tracker Alignment `DiMuonValidation` setup.
These are:
   * adding 3D histograms of di-muon mass vs η, φ for derivation of 2D bias maps: b4be42bcf8363c5e47642264f39206eaed7a25e0
   * improve the titles of some of the monitoring histograms in bins of muon pseudo-rapidity: 795c78ceab3c77fa742f47251b6ecc51151ea5a6 , 682c03d6439164f9825314e1a4df4ffca23e686a
   * finally, introduce a new C++ macro to perform fits of the mass bias in bins of track η, φ (commits https://github.com/cms-sw/cmssw/pull/44994/commits/5ad5c286e186bce78685f7eea04b6dfbf4e9a691, https://github.com/cms-sw/cmssw/pull/44994/commits/498746870ba25549b4ace589a90903fc93a9ee40, https://github.com/cms-sw/cmssw/pull/44994/commits/4dcf990579b4307b7f9dfaa53fd419c0f686a61f)  . 
   This is foreseen in the longer term to replace the existing [`Zmumumerge.cc`](https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/bin/Zmumumerge.cc) class which is currently used by the so-called "all-in-one" tool. The new plotting script fixes several issues with the final plotting currently provided by the all-in-one; however, the replacement is not done in this PR and will have to be done at a second time.  

#### PR validation:

Private validation was carried out using this branch and operating the new plotting macros. 
The plots at this [link](http://musich.web.cern.ch/musich/display/ZmmRevised/) were obtained. . For a comparison with the output of the current code, see please [here](http://musich.web.cern.ch/musich/display/ZmmRevised/control/). 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, will be backported to 14.0.X

Cc: @henriettepetersen @TomasKello

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
I am looking at the plots you posted from the private validation. Out of curiosity, could you explain what originates the differences observed between prompt and mp3747 (by the way: what does it mean?)

**Comment by mmusich** [comment]
@perrotta 

> Out of curiosity, could you explain what originates the differences observed between prompt and mp3747 (by the way: what does it mean?)
 
`mp3747` is the internal MillePede numbering identifier for a manual alignment campaign (the 3747-th produced using the [MillePede Production System](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMillepedeProductionSystem) or `mps` for short).
According to the internal record it's:
```
mp3747    hpeterse    2023-09-18 CMSSW_13_2_3 (mod.)               data             clone of mp3746 and use as SG, without CRUZET and with zmumu
```
basically it's a early prototype version of an alignment for the 2023 re-reco.

**Comment by mmusich** [comment]
> And why the phases are so different between prompt and mp3747?

I can't tell for sure,  I guess different track topologies usend in Prompt reco (mainly plain charged hadrons) vs ReReco (adding cosmics and muons from resonances) are affecting systematic deformations in different ways. The goal of the rereco is of course to minimize the amplitude of such deformations. I would not pay too much attention to the actual results shown in the link, it's just a semirandom combination I chose to illustrate the features introduced in this PR. Speaking of which what has all this discussion have to do with the PR itself?

**Comment by perrotta** [comment]
> Speaking of which what has all this discussion have to do with the PR itself?

Maybe to check whether those discrepancies can witness possible issues in the code that are not easily realized by just glacing at the code itself?

**Comment by mmusich** [comment]
> Maybe to check whether those discrepancies can witness possible issues in the code that are not easily realized by just glacing at the code itself?

I can't see how is that even possible. Can you please elaborate?

**Comment by perrotta** [comment]
> I can't see how is that even possible. Can you please elaborate?

Wrong code can give wrong results (can you understand it?).
That's why I'm asking you if the results look correct to you (supposedly the expert).
If you confirm that you don't see issues in the results, I don't have other suggestions that the code is potentially wrong and I can sign this paper

**Comment by TomasKello** [comment]
Hi @perrotta I can confirm there is nth to be worried of the actual content of the plots. We do have a working version of the dimuon mass validation tool which produces identical plots in terms of content. Marco's version is adding some new features, plot types and fixes style of the existing plots, etc. Indeed mp3747 is supposed to mitigate strong bias observed for Alignment in prompt. For even better example: here you find comparison of the Alignment in Prompt and final ReReco22 object: https://tkello2.web.cern.ch/gallery_ReReco22_EFG_Zmumu_v2.html

**Comment by perrotta** [comment]
+1
- Of course this PR can be signed. I only find a bit funny that someone complains when we ask to confirm the correctness of some curious result that sorts out of the comparisons used to test it :-)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
