### PR TITLE
Run3-gex34 Make xml files with +-5% and +-10% variation of material budget for 2017

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make xml files with +-5% and +-10% variation of material budget for 2017

#### PR validation:

Checked the validity of the xml files using these files in a scenario

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
The new file `Geometry/TrackerCommonData/python/trackGeometry2017XML_cfi.py` seems to contain the +-5% variation scenario. But its name is a very generic "Geometry2017". Should this file have a more specific name that indicates it is only for the +-5% scenario?

**Comment by cvuosalo** [comment]
What else will be needed to create DB payloads for these material variation scenarios?

**Comment by bsunanda** [comment]
@cvuosalo @ianna I needed a python script to test the goodness of all xml files. Once the xml files are approved, I shall define the 4 scenarios in Geometry/CMSCommonData and the cff files in Configuration/Geometry to complete this work. First I check the goodness of the xml files and for that I introduced the cfi file in Geometry/TrackerCommonData. Could you approve this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
