### PR TITLE
Modernize ESProducers in TrackingTools/GsfTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Pull out parameters in constructor
- Wrote fillDescriptions
- Use edm::ESGetToken

#### PR validation:

The code compiles. This is a refactoring and should not change any results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27502	8ca12ab
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
