### PR TITLE
Migrate module config in RecoTracker to use default seedingLayersEDProducer in cfipython v2

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. This is a follow-up PR from [PR#35194](https://github.com/cms-sw/cmssw/pull/35194).
This is the 2nd version. (1st version is [PR#35549](https://github.com/cms-sw/cmssw/pull/35549) ) 
[As commented from slava in this PR#35194,](https://github.com/cms-sw/cmssw/pull/35194#issuecomment-925954770) we replaced "cms.PSet" in module "seedingLayersEDProducer" with "dict".

In this PR, 8 files changed.  
        modified:   RecoTracker/ConversionSeedGenerators/python/ConversionStep2_cff.py
        modified:   RecoTracker/ConversionSeedGenerators/python/ConversionStep_cff.py
        modified:   RecoTracker/IterativeTracking/python/ElectronSeeds_cff.py
        modified:   RecoTracker/IterativeTracking/python/JetCoreRegionalStep_cff.py
        modified:   RecoTracker/IterativeTracking/python/PixelLessStep_cff.py
        modified:   RecoTracker/IterativeTracking/python/PixelPairStep_cff.py
        modified:   RecoTracker/IterativeTracking/python/TobTecStep_cff.py
        modified:   RecoTracker/SpecialSeedGenerators/python/CombinatorialSeedGeneratorForCosmicsP5_cff.py

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_1_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Review by jpata — COMMENTED** [review]
No reco changes, good. A minor question inline.

**Comment by jpata** [comment]
I did a diff between the config dump from 11834.21/step3 before & after this PR and saw no change, as expected.

**Comment by jpata** [comment]
+reconstruction
- technical python config cleanup
- no reco changes, no changes in the configdump

**Comment by perrotta** [comment]
+1

**Pull request merged**
