### PR TITLE
Conddb: move to upper-case table names, ignore non-existing GT table in sqlite

### PR DESCRIPTION
**Pull request by apfeiffer1**
- move table names to upper case for compatibility with CORAL/Oracle

This PR includes the changes from #9312, so if you agree for both, you can use this and close the other.
For reference, here is the comment from 9312:
- add check to ignore non-existing GT table when reading sqlite files which were created by a C++ tool

### CODE REVIEW

**Comment by apfeiffer1** [comment]
the latest update fixes an issue with build paths when running dump in subdirs of $CMSSW_BASE/src/ as reported by Jean Fay.

**Comment by apfeiffer1** [comment]
please test

On Saturday, May 30, 2015, cmsbuild <notifications@github.com> wrote:

>  -1
> Tested at: 5e303c5
> <https://github.com/cms-sw/cmssw/commit/5e303c538eb32a7fc0c61b3afefdbce4c560f291>
> The relvals timed out after 2 hours.
>
> you can see the results of the tests here:
>
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9316/9819/summary.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9316#issuecomment-106976889>.
>


-- 
Thanks,
       cheers, andreas

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
