### PR TITLE
DD4hep: get a current node SpecPar value by name

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Compare a full path to the node with the SpecPar selection paths to avoid false positive when a node name matches a regular expression in a different path

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@ianna sorry, how was this validated?

**Comment by ianna** [comment]
@fabiocos - this code is required by the RPC geometry builder to get the "nStrips" which is not in the CMSSW yet. @slomeo has checked that it gives the identical to DD results as expected. The validation test will be part of the RPC package.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
