### PR TITLE
HGCal noise and aging cleanup

### PR DESCRIPTION
**Pull request by kpedro88**
* avoid calling random number generation if relevant noise parameter is 0
* add customize function to disable HGCal noise
* clean up customization functions that no longer need the digitizer module
* add comment that noise is already disabled for premixing
* simplify initialization of some vector parameters

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
