### PR TITLE
Fix for LHCInfo O2O

### PR DESCRIPTION
**Pull request by ggovi**
Fix for handling properly the start/end of O2O job

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by fabiocos** [comment]
please test

@mrodozov tests look stuck here

**Comment by mrodozov** [comment]
@fabiocos now it's fine. It time outed trying to clone the repo (I think the webhook call failed but didn't recovered/retried) https://cmssdt.cern.ch/jenkins/view/All/job/ib-any-integration/29639/console.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
