### PR TITLE
Run3-hcx353 Backport from #46033 new definition of 2024 Geometry Scenario of CMS

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport from #46033 new definition of 2024 Geometry Scenario of CMS

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46033 to redefine 2024 Geometry of CMS

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46033

**Comment by mandrenguyen** [comment]
urgent
IIUC this is the last ZDC related PR needed for 14_1_0 (conditions updates aside).
@bsunanda @hjbossi @abdoullin correct me if that's a wrong statement 
Otherwise, I'll be building the release once this goes thru an IB.

**Comment by mmusich** [comment]
+hlt

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
