### PR TITLE
Fix logic error in `FinalPath` checks

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

If an `EDProducer` or `EDFilter` is inserted in a `FinalPath`, the job fails with a cryptic error:
```
----- Begin Fatal Exception 03-Oct-2023 15:42:41 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
AttributeError: 'str' object has no attribute 'label_'

At:
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1292): <listcomp>
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1292): _insertPaths
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1490): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

With these changes, the error is more meaningful:
```
----- Begin Fatal Exception 03-Oct-2023 15:46:00 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
RuntimeError: FinalPath HLTriggerFinalPath has non OutputModules HLTBool,TriggerSummaryProducerRAW

At:
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1290): _insertPaths
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1487): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

Implement the python checks to notify that also `EDAnalyzer`s are not supported on `FinalPath`s.

The unit tests are extended to catch the error.

#### PR validation:

The extended unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@cmsbuild, please abort

**Comment by fwyzard** [comment]
wrong cherry-pick...

**Comment by fwyzard** [comment]
please test

**Comment by Dr15Jones** [comment]
Would it be possible to add a unit test to trigger the problem? It would just be an extension of the test at the bottom of the Config.py file.

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
@fwyzard Would it be possible to add the unit test @Dr15Jones mentioned [above](https://github.com/cms-sw/cmssw/pull/42936#issuecomment-1745088510)?

**Comment by fwyzard** [comment]
it's on my low priority to do list...

**Comment by fwyzard** [comment]
I've added the tests, for `EDAnalyzer`, `EDProducer`, `EDFilter`, `OutputModule`.

Without the fix, I get the error
```
$ python3 -m FWCore.ParameterSet.Config
......E.............................
======================================================================
ERROR: testFinalPath (__main__.TestModuleCommand)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/user/fwyzard/CMSSW_14_0_0_pre0/src/FWCore/ParameterSet/python/Config.py", line 3360, in testFinalPath
    self.assertRaises(RuntimeError, p.fillProcessDesc, pset)
  File "/data/cmssw/el8_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/unittest/case.py", line 739, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/data/cmssw/el8_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/unittest/case.py", line 201, in handle
    callable_obj(*args, **kwargs)
  File "/data/user/fwyzard/CMSSW_14_0_0_pre0/src/FWCore/ParameterSet/python/Config.py", line 1488, in fillProcessDesc
    self._insertPaths(adaptor, nodeVisitor)
  File "/data/user/fwyzard/CMSSW_14_0_0_pre0/src/FWCore/ParameterSet/python/Config.py", line 1290, in _insertPaths
    names.extend( [p.label_ for p in finalpathValidator.producersOnFinalpaths])
  File "/data/user/fwyzard/CMSSW_14_0_0_pre0/src/FWCore/ParameterSet/python/Config.py", line 1290, in <listcomp>
    names.extend( [p.label_ for p in finalpathValidator.producersOnFinalpaths])
AttributeError: 'str' object has no attribute 'label_'

----------------------------------------------------------------------
Ran 36 tests in 0.150s

FAILED (errors=1)
```

With the fix:
```
$ python3 -m FWCore.ParameterSet.Config
....................................
----------------------------------------------------------------------
Ran 36 tests in 0.148s

OK
```

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
The error seems unrelated.

**Comment by makortel** [comment]
Comparisons show https://github.com/cms-sw/cmssw/issues/43415

**Comment by makortel** [comment]
+core

Thanks @fwyzard!

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
