### PR TITLE
L1T uGT: Three body invariant mass for muons backport

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

This is a backport of https://github.com/cms-sw/cmssw/pull/33911, needed for CRUZET so urgent! (sorry!)

Development of a new condition class to deal with a three-body correlation condition (starting from CorrCondition and CorrWithOverlapRemovalCondition as a model): CorrThreeBodyCondition and CorrelationThreeBodyTemplate.
Based on the version of the UTM libraries utm_0.8.1: https://gitlab.cern.ch/cms-l1t-utm/utm/-/tree/utm_0.8.1.
New parseCorrelation function needed in the TriggerMenuParser. Minor changes needed in the L1TGlobalProducer, GlobalBoard, TruggerMenu, GlobalCondition, GlobalDefinitions.

#### PR validation:

    Tests performed by producing test vectors using a dedicated L1 Menu with four algorithms requiring three muons with different pT cuts and a threshold on the three-muon invariant mass: successful comparison with triggers from the firmware.
    CMSSW release used for tests: CMSSW_12_0_X_2021-05-24-2300.
    Test at the HLT level to verify that the correct information about the objects that caused the decision is correctly saved and used: a generic triple muon HLT path can be seeded by L1 triggers with a three-body invariant mass requirement.
    STEPS:
    - Private production of a small RAW-DIGI ZZTo4Mu sample (100 events) using Run 3 conditions
    - Production of a dedicated HLT menu in ConfDB including FirstPath, FinalPath, and a generic TripleMu seed (HLT_TripleMu_10_5_5_DZ_v10) with modified L1 seeds as Logical Expression:
    /users/elfontan/ThreeMuInvMassTest/TriMuInvarianMass1120/V4
    - HLT configuration and uGT emulator run with a dedicated L1 test menu:
    [... --l1-emulator uGT --mc --l1Xml L1Menu_test_mass_3_body_reduced_v2.xml"]
    Some final checks:
    - scram build code-format #Ensure that the code conforms to CMSSW standards
    - scram b -j8
    - runTheMatrix.py -l 11634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/33911

@elfontan For you to be updated
@qliphy @silviodonato This is the backport we urgently need for CRUZET I was mentioning at the ORP meeting, sorry about the late notice!

### CODE REVIEW

**Comment by cecilecaillol** [comment]
urgent

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
