### PR TITLE
Removed unused fwkJobReports from MessageLogger in SLHCUpgradeSimulations Subsystem

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The parameter fwkJobReports is an obsolete parameter which has had no functionality for many years.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
