### PR TITLE
Modernize python code in 9_0

### PR DESCRIPTION
**Pull request by ericvaandering**
Done with

```futurize -1 -nw -x print_with_import .```

to get code to match 2.7 constructs and maximum portability to python 3

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Review by Dr15Jones — APPROVED** [review]
+1

**Comment by fwyzard** [comment]
+1

**Comment by Dr15Jones** [comment]
The unit test failures are unrelated to this pull request.

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
