### PR TITLE
[Tracker Alignment] Introduce ALCARECOTkAlDiMuonAndVertex

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a follow-up of PR https://github.com/cms-sw/cmssw/pull/33709.
In order to perform the checks discussed [here](https://indico.cern.ch/event/992964/contributions/4340538/) and [here](https://indico.cern.ch/event/1025492/contributions/4343121/attachments/2235708/3789275/mm_ZMMVertex_PPDGeneral_29Apr2021.pdf), it has been necessary to use `RECO` data-tier to have the necessary event products to be able to refit at the same time the di-lepton tracks and the tracks making up the primary vertex.
Given the relative scarcity of `RECO` files to perform these kind of checks as a mandatory step during the Tracker Alignment procedure we devise here a new ALCARECO flavor called `ALCARECOTkAlDiMuonAndVertex` which saves into its event content both the two inner tracks of a muon building a Z candidate (`ALCARECOTkAlDiMuon`) and the tracks used to be build the hardest Primary Vertex in the event (along with the pixel and strip clusters associated to them to be able to run the track refit, `ALCARECOTkAlDiMuonVertexTracks`).
This is achieved by using a new `ObjectSelectorStream` called `AlignmentTracksFromVertexSelector` capable of selecting the tracks associated to a given PV (its order in the list can be passed as configuration parameter) or by automatically finding the closest one in 3D distance to the transient vertex built with the di-muon tracks.
This selector could be used in principle in future also to save tracks from peripheral events (@connorpa).

#### PR validation:

Private tests with the following command.

```bash
 cmsDriver.py -s RAW2DIGI,RECO,ALCA:TkAlDiMuonAndVertex \
    --conditions auto:run2_data \
    --eventcontent=ALCARECO \
    --datatier ALCARECO \
    -n 1000 \
    --era Run2_2018 \
    --python_filename=TkAlDiMuonAndVertex_2018B.py \ 
    --filein=root://cms-xrd-global.cern.ch//store/data/Run2018B/DoubleMuon/RAW/v1/000/318/816/00000/3E73C278-597A-E811-8717-FA163E16A836.root \
    --nThreads=8
```
The event content is as follows:

```bash
File TkAlDiMuonAndVertex.root Events 110
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
recoTrackExtras_ALCARECOTkAlDiMuonVertexTracks__RECO. 6291.6 5025.35
recoVertexs_offlinePrimaryVertices__RECO. 23379.5 4396.91
TrackingRecHitsOwned_ALCARECOTkAlDiMuonVertexTracks__RECO. 25440.5 3447.66
recoTracks_ALCARECOTkAlDiMuonVertexTracks__RECO. 8630.86 3343.08
SiStripClusteredmNewDetSetVector_ALCARECOTkAlDiMuonVertexTracks__RECO. 6872.22 3021
SiPixelClusteredmNewDetSetVector_ALCARECOTkAlDiMuonVertexTracks__RECO. 3951.76 1712.9
EventProductProvenance 4019.22 1595.84
recoVertexsedmAssociation_offlinePrimaryVertices__RECO. 3054.23 936.5
recoTrackExtras_ALCARECOTkAlDiMuon__RECO. 798.1 650.655
recoTracks_ALCARECOTkAlDiMuon__RECO. 975.818 539.791
SiStripClusteredmNewDetSetVector_ALCARECOTkAlDiMuon__RECO. 838.036 441.891
SiPixelClusteredmNewDetSetVector_ALCARECOTkAlDiMuon__RECO. 577.909 388.164
TrackingRecHitsOwned_ALCARECOTkAlDiMuon__RECO. 2304.71 358.964
intedmValueMap_offlinePrimaryVertices__RECO. 2883.53 272.082
floatedmValueMap_offlinePrimaryVertices__RECO. 240.891 183.155
DcsStatuss_scalersRawToDigi__RECO. 195.282 129.391
L1AcceptBunchCrossings_scalersRawToDigi__RECO. 210.173 90.0909
edmTriggerResults_TriggerResults__HLT. 1435.2 88.8
EventAuxiliary 139.427 39.6091
L1GlobalTriggerReadoutRecord_gtDigis__RECO. 95.3273 26.0091
edmTriggerResults_TriggerResults__RECO. 101.491 25.5
EventSelections 78.6455 4.77273
BranchListIndexes 27.7364 3.71818
```
On 1000 event of input taken from 2018B RAW data, the output size is measured to be of about 41kB / event.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.
cc:
@vbotta @antoniovagnerini

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
Should this PR test trigger with DiMuon workflow?

**Comment by mmusich** [comment]
@srimanob 

> Should this PR test trigger with DiMuon workflow?

what do you mean?
The code was tested in the PR integration tests for:
- MC: [workflow 10042.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-246402/15173/runTheMatrix-results/10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano/)
- Data: [workflow 1000.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-246402/15173/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/)

Do you want me to add it more explicitly to some of the Run2 DiMuon workflows?

**Comment by yuanchao** [comment]
+1
* add ALCARECOTkAlDiMuonAndVertex & ALCARECOTkAlDiMuonVertexTracks
* matrix tests and unit tests passed
* no related build warnings/errors

**Comment by srimanob** [comment]
> @srimanob
> 
> > Should this PR test trigger with DiMuon workflow?
> 
> what do you mean?
> The code was tested in the PR integration tests for:
> 
> * MC: [workflow 10042.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-246402/15173/runTheMatrix-results/10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano/)
> * Data: [workflow 1000.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-246402/15173/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/)
> 
> Do you want me to add it more explicitly to some of the Run2 DiMuon workflows?

Ah, I miss that it is included in relvals_step also. I just look on DiMuon AutoAlca. Then this is fine.

**Comment by srimanob** [comment]
+Upgrade

Adding new AlcaReco. With the short matrix workflow tests, new modules run fine.

**Comment by mmusich** [comment]
@silviodonato @qliphy do you have any comment from the operations point of view?

**Comment by qliphy** [comment]
+1

**Pull request merged**
