### PR TITLE
Backport to 102X: MET EE noise mitigation in 2017 data

### PR DESCRIPTION
**Pull request by eioannou**
Backport of #24876 and #25129 
The latter PR was created to complement the former PR, where 4c2621a#diff-496fcf98e9a0901abbe07acea8ebda40  got  lost during a rebase.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Faithful backport of #24876 and #25129
- A new filter is made available for users. 
  - If the parameters in ```PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py``` are kept at their default value the newly added filter is disabled, and therefore no effect can be propagated to the standard workflows (and no effect is seen in the results of the jenkins tests, in fact)
  - As such, the pull request can be merged without modifying the default behaviour, and it is therefore suitable for being backported

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

requested for NanoAOD reprocessing, no change in default MC production

**Pull request merged**
