### PR TITLE
Phase2-hgx307X Change xml file in view of changed algorithms in PR's #37505 and #37510

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change xml file in view of changed algorithms in PR's #37505 and #37510

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
