### PR TITLE
Detector Description Include What You Use 

### PR DESCRIPTION
**Pull request by ianna**
- Auto-fix includes with iwyu as follows:

```
cmsrel CMSSW_8_1_DEVEL_X_2016-05-09-2300
cd CMSSW_8_1_DEVEL_X_2016-05-09-2300/src
cmsenv
git cms-addpkg DetectorDescription
scram b COMPILER=iwyu -k > & log.log
python /cvmfs/cms-ib.cern.ch/2016-20/slc6_amd64_gcc530/external/llvm/3.8.0/bin/fix_includes.py < log.log
```

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@shazad and @Dr15Jones - FYI, this one is fully automated processing by iwyu tool

**Comment by davidlt** [comment]
Be careful with it! This tool does not guarantee that what it suggest is correct. It's highly advisable to manually review it.

**Comment by ianna** [comment]
@davidlt - yes, thanks, I noticed it. I'm planning to review and correct it. There are a few places which I do not like.

**Comment by ianna** [comment]
Fix compilation errors

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
