### PR TITLE
 Adding Number of RecHits plot for SiStrip stereo modules (backport to 13_1_X)

### PR DESCRIPTION
**Pull request by mascioti**
#### PR description:

Adding Number of RecHits on Strip Stereo Modules on the Tracker DQM

#### PR validation:

runTheMatrix.py -l 12434

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #41725

### CODE REVIEW

**Comment by mmusich** [comment]
This branch does not pass the code quality standards.
Please run: `scram b code-format` and `scram b code-checks` and then push the resulting changes. 
Thanks you.

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41725

**Comment by emanueleusai** [comment]
please test

**Comment by arossi83** [comment]
Wrong target branch, this should be targeting 13_1_X. Close the PR and create a new one on correct branch

**Pull request closed without merging**
