### PR TITLE
fix collection names for premixing

### PR DESCRIPTION
**Pull request by deguio**
backport of #20221

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by abdoulline** [comment]
@slava77 
Slava, do you suggest to add the content (7 lines) of Matthas'  PR  
https://github.com/cms-sw/cmssw/pull/20243 
(backport to 92X) 

to this one?

**Comment by slava77** [comment]
On 8/23/17 5:56 AM, Salavat Abdullin wrote:
> @slava77 <https://github.com/slava77>
> Slava, do you suggest to add the content (7 lines) of Matthas' PR
> #20243 <https://github.com/cms-sw/cmssw/pull/20243>
> (backport to 92X)
> 
> to this one?


yes

**Comment by abdoulline** [comment]
We've just discussed the situation with PRs #20221 and #20222 with 
Federico in person, so he'll take some action(s) soon to move towards a 
combined solution, possibly for 93X first (to find a fix for fastsim).

**Comment by deguio** [comment]
closing while we decide what's the best solution to implement

**Pull request closed without merging**
