### PR TITLE
Fix bit value checks in HcalNoiseInfoProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Comparison like `(value & (1<<shift)) == 1` for `shift > 1` will always return `false`. Assuming that the intention was to check with `== 1` that the corresponding bit was set, and with `== 0 ` that it was not set, this PR suggests to replace the explicit bit operations with calls to `HcalChannelStatus::isBitSet()`. These were found by GCC 9.

#### PR validation:

The code compiles without warnings with GCC 9.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@jkunkle @igv4321 @abdoulline @deguio @mariadalfonso @eioannou : could any of you please check and confirm?

**Comment by abdoulline** [comment]
@perrotta 

Andrea, just to let you know - Josh (jkunkle) and Federico (deguio) aren't  involved (at least directly) in HCAL business anymore. 
Yesterday I've asked Jae (@jaehyeok) and new HCAL Noise group convener  Chandiprasad Kar
to evaluate possible effect of this fix...

**Comment by perrotta** [comment]
> @perrotta
> 
> Andrea, just to let you know - Josh (jkunkle) and Federico (deguio) aren't involved (at least directly) in HCAL business anymore.
> Yesterday I've asked Jae (@jaehyeok) and new HCAL Noise group convener Chandiprasad Kar
> to evaluate possible effect of this fix...

Thank you Salavat! I'm waiting for some feedback from the group then, just to confirm that the original intention of the authors are correctly mirrored in this PR

**Comment by igv4321** [comment]
Just by eyeballing the changes in the code, this fix definitely looks like a step in the right direction. But, of course, the HCAL Noise group will provide more informative feedback...

**Comment by perrotta** [comment]
type bugfix

**Comment by perrotta** [comment]
@abdoulline @jaehyeok : did you already evaluate the possible effects of this fix? As the code changes look quite reasonable, it is just a matter of getting confirmation from your side that there are no unwanted side effects, and then this PR can be accepted for the integration: it wold be nice doing it before the pre5 deadline of tomorrow.

**Comment by jaehyeok** [comment]
Hi @perrotta, 

Let me check with the guy who has been working on it. I will get back to you soon.

**Comment by cpkar** [comment]
Hi @abdoulline and @jaehyeok ,
I have made a comparison plot of the noise variables before and after the code fix. 
Initially, I have taken 2500 events from MET data set[1] and looked at
the noise variables before and after the fix in the code, the plots are
matching well with each other[2]. similar conclusion is also drawn from the
SingleMuon dataset.

Thanks


[1] file:/eos/cms/store/data/Run2018A/MET/RAW/v1/000/316/995/00000/CC6B1013-4462-E811-B884-FA163EE3010D.root
[2] [hbhe.pdf](https://github.com/cms-sw/cmssw/files/3150905/hbhe.pdf)

**Comment by perrotta** [comment]
> Hi @abdoulline and @jaehyeok ,
> I have made a comparison plot of the noise variables before and after the code fix.
> Initially, I have taken 2500 events from MET data set[1] and looked at
> the noise variables before and after the fix in the code, the plots are
> matching well with each other[2]. similar conclusion is also drawn from the
> SingleMuon dataset.
> 
> Thanks
> 
> [1] file:/eos/cms/store/data/Run2018A/MET/RAW/v1/000/316/995/00000/CC6B1013-4462-E811-B884-FA163EE3010D.root
> [2] [hbhe.pdf](https://github.com/cms-sw/cmssw/files/3150905/hbhe.pdf)

Thank you @cpkar 
Are you meaning that the fix is uneffective, then?

**Comment by abdoulline** [comment]
(better late than never...) Sorry for the late reply. 
Now, after discussing with Jae in HCAL thread :

as far as I can see, the fix is applied to the HCAL Channel status bits, which aren't set in DB. 
I.e. these bits are reserved/enumerated
https://cmssdt.cern.ch/lxr/source/CondFormats/HcalObjects/interface/HcalChannelStatus.h#0019
 but not actually used, e.g. last 2018 IOV of HcalCannelQuality 
https://twiki.cern.ch/twiki/pub/CMS/HcalChannelQualityTags2011/HcalChannelQuality_2018_v4.1_data.txt
Only dead cells are explicitly listed (if not 0).

That's why there is no difference in Chandi's test.

**Comment by perrotta** [comment]
+1
- A ill formed set of instructions in the code of HcalNoiseInfoProducer is fixed here
- According to the result of the investigations done by the HCAL experts (https://github.com/cms-sw/cmssw/pull/26556#issuecomment-490009357), that part of code is not actually used: that's why no difference are visible in the tests outputs
- It is worth to fix the code anyhow

**Comment by fabiocos** [comment]
+1

**Pull request merged**
