### PR TITLE
Updated nano matrix 13.2

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

this updates the NANO matrix with relevant workflows. A partial back port to 13.0.X is expected

#### PR validation:

`runTheMatrix.py --what nano --nEvents 10` ran successfully

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
@smuzaffar : there are new input files here. Is there anything to be done to get them staged to IB IOS space?

**Comment by vlimant** [comment]
please test

**Comment by srimanob** [comment]
Hi @vlimant 
Should you also update https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L85

I don't see 12.6 wf anymore, maybe you need to pick another version instead,
```
2500.0 TTbarMINIAOD10.6_UL16v2+NANO_mc10.6ul16v2+HRV_NANO_mc 
2500.001 TTbarMINIAOD10.6_UL17v2+NANO_mc10.6ul17v2+HRV_NANO_mc 
2500.002 TTbarMINIAOD10.6_UL18v2+NANO_mc10.6ul18v2+HRV_NANO_mc 
2500.01 MuonEG2016MINIAOD10.6v2+NANO_data10.6ul16v2+HRV_NANO_data 
2500.011 MuonEG2017MINIAOD10.6v2+NANO_data10.6ul17v2+HRV_NANO_data 
2500.012 MuonEG2018MINIAOD10.6v2+NANO_data10.6ul18v2+HRV_NANO_data 
2500.1 TTbarMINIAOD12.2+NANO_mc12.2+HRV_NANO_mc 
2500.2 TTbarMINIAOD12.4+NANO_mc12.4+HRV_NANO_mc 
2500.21 MuonEG2022MINIAOD12.4+NANO_data12.4+HRV_NANO_data 
2500.211 MuonEG2022MINIAOD12.4+NANO_data12.4_prompt+HRV_NANO_data 
2500.3 TTBarMINIAOD13.0+NANO_mc13.0+HRV_NANO_mc 
2500.31 MuonEG2023MINIAOD13.0+NANO_data13.0+HRV_NANO_data 
2500.311 MuonEG2023MINIAOD13.0+NANO_data13.0_prompt+HRV_NANO_data 
2500.4 TTBarMINIAOD13.2+NANO_mc13.2+HRV_NANO_mc 
```

**Comment by vlimant** [comment]
good point @srimanob

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
I assume this PR is ready to go, right @vlimant ?
Kindly ping @cms-sw/pdmv-l2 to review. Thanks.

**Comment by kskovpen** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
