### PR TITLE
Make DTRecoConditions thread safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
The delayed caching of the formula results has been changed to be
thread safe.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
@cerminar @diguida @mmusich @ggovi  @davidlange6 It's been a week

**Comment by diguida** [comment]
+1

**Pull request merged**
