### PR TITLE
Histogram for L1T Stage1

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by jingyucms** [comment]
@cmsbuild Please try again

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @jingyucms 
could you please add some description about the content of this PR?
it is not fully clear to me and it is a relatively big change.
we might want to invite you to one of the next DQM meetings to illustrate the changes.

thanks,
F.

**Comment by jingyucms** [comment]
Hi Fede:

This is basically for the 2015 trigger upgrade. I basically add histograms
for new isolated tau object. And there is also some change in the HF ring
sums and HT miss algorithm side. I can definitely make some slides to
describe it in the next DQM meeting. You can just put in the agenda.

Cheers
Jingyu

**Comment by deguio** [comment]
the details of this change were reported yesterday at the DQM meeting:
https://indico.cern.ch/event/371149/contribution/0/material/slides/0.pdf

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
