### PR TITLE
possibility of configuring the OMTF emulator directly from XMLs

### PR DESCRIPTION
**Pull request by kbunkow**
#### PR description:

This PR adds the possibility of configuring the OMTF emulator directly from the config XML, without using the L1TMuonOverlapPhase1ParamsESProducer. It should allow to avoid problems with the OMTF emulator that appeared in the https://github.com/cms-sw/cmssw/pull/44498 - as discussed in the https://github.com/cms-sw/cmssw/pull/44498#issuecomment-2126564586.

#### PR validation:
The PR was validated with the workflow 141.044 (`runTheMatrix.py -l 141.044 -i all --ibeos`). The OMTF plots look good.

This PR is not a backport.

#### Details of changes:

OMTFReconstruction.h and OMTFReconstruction.cc
The possibility of configuring the OMTF emulator directly from the config XML is added. When both patternsXMLFile and configXMLFile are given from the python config of the simOmtfDigis or simOmtfPhase2Digis, the L1TMuonOverlapParams are read directly from these files, and the L1TMuonOverlapPhase1ParamsESProducer is not needed. Otherwise, the L1TMuonOverlapParams are obtained from the eventSetup (so from the DB, or from the L1TMuonOverlapPhase1ParamsESProducer - if it is defined).

L1Trigger/L1TMuonOverlapPhase2/python/fakeOmtfParamsPhase2_cff.py is removed, as when it is used, the L1TMuonOverlapPhase1 gets this config as well.

L1Trigger/L1TMuonOverlapPhase2/python/simOmtfPhase2Digis_extrapol_cfi.py is moved to
simOmtfPhase2Digis_cfi.py, as this is the default configuration (besides, there should be only one cfi for a given module).

L1Trigger/L1TMuonOverlapPhase1/src/Omtf/OMTFProcessor.cc line
trackAddr[3] = myCand->getGpResultUnconstr().getPdfSumUnconstr(); is removed, as uGMT expects 3 entries in the TrackAddress (when there were 4, uGMT was generating a warning).

L1Trigger/L1TMuonOverlapPhase2/test - runMuonOverlap*.py are corrected

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by artlbv** [comment]
Interestingly, this PR now also shows some differences in the Run3 `OMTFoutput_vs_uGMTinput` DQM, even though when tested alone this PR does not add the new Phase-2 OMTF into the L1 sequence yet. 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-24-1100+6a0d5a/62881/141.046_RunEGamma2023D/L1T_L1TStage2uGMT_OMTFoutput_vs_uGMTinput.html

Is this expected? @kbunkow @mbluj

**Comment by kbunkow** [comment]
> Interestingly, this PR now also shows some differences in the Run3 `OMTFoutput_vs_uGMTinput` DQM, even though when tested alone this PR does not add the new Phase-2 OMTF into the L1 sequence yet.
> 
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-24-1100+6a0d5a/62881/141.046_RunEGamma2023D/L1T_L1TStage2uGMT_OMTFoutput_vs_uGMTinput.html
> 
> Is this expected? @kbunkow @mbluj

The difference in the L1T_L1TStage2uGMT_OMTFoutput_vs_uGMTinput plots is due to a change in the 
[L1Trigger/L1TMuonOverlapPhase1/src/Omtf/OMTFProcessor.cc](https://github.com/cms-sw/cmssw/pull/45032/files#diff-2847b216c35e24caeadd086b53da9a2631a450ab8bf9ca885667b1403791ea0a), i.e. removed line
`trackAddr[3] = myCand->getGpResultUnconstr().getPdfSumUnconstr();`

This line was added by #43687, but it turned out it is not needed, and moreover, uGMT was generating this warning message when the fourth trackAddr was added:
```
OMTF muon track address map contains 4 instead of the expected 3 subaddresses. Check the data format. Setting track address to 0
```
The track address map is checked only by the plots L1T_L1TStage2uGMT_OMTFoutput_vs_uGMTinput , therefore the differences are visible only in these plots.

So the fix in this PR in the OMTFProcessor.cc is OK, as well as the changes in the L1T_L1TStage2uGMT_OMTFoutput_vs_uGMTinput plots.

Karol

**Comment by srimanob** [comment]
Note to @cms-sw/l1-l2 for later fix PR

src/L1Trigger/L1TMuonOverlapPhase1/src/Tools/CandidateSimMuonMatcher.cc:444:12: warning: Value stored to 'treshold' during its initialization is never read [deadcode.DeadStores]
  444 |     double treshold = 6. * sigma;
      |            ^~~~~~~~   ~~~~~~~~~~
src/L1Trigger/L1TMuonOverlapPhase1/src/Tools/CandidateSimMuonMatcher.cc:446:7: warning: Value stored to 'treshold' is never read [deadcode.DeadStores]
  446 |       treshold = 7. * sigma;
      |       ^          ~~~~~~~~~~
src/L1Trigger/L1TMuonOverlapPhase1/src/Tools/CandidateSimMuonMatcher.cc:448:7: warning: Value stored to 'treshold' is never read [deadcode.DeadStores]
  448 |       treshold = 20. * sigma;
      |       ^          ~~~~~~~~~~~
3 warnings generated.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Comment by antoniovilela** [comment]
ping bot

**Pull request merged**
