### PR TITLE
HLT Calibration Event Type Filter for HCAL

### PR DESCRIPTION
**Pull request by vkhristenko**
#15638

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #15638

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15639 d929067
- reco is minimally affected (new accessor in HcalUHTRData); the same code changes as in 81X version #15638 
- jenkins tests pass and comparisons with baseline show no difference

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
