### PR TITLE
Add flag to configure production of DDU-based trigger synch plots [10_2_X]

### PR DESCRIPTION
**Pull request by battibass**
This PR is intended to fix the T0 issue related to pathALCARECODtCalib reported in [this HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1862/1.html).

What it does is making the production of a few plots (hence the access to some products) configurable and disables them in the 2018 era.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@battibass from your private communication I understand that this PR (actually its 10_1_X back-port) has been verified to solve one of the crash reported:

On 26 Apr 2018, at 18:22, Carlo Battilana <Carlo.Battilana@cern.ch> wrote:

Dear All,
	please find in [1] and [2] two PRs aimed at fixing the issue reported in this thread. 
[1] has been tested using the tarball in [3] to confirm that the error disappears. 

Please note that it is not possible to fix the crash with a simple configuration change, as the collection that was used as input is not produced anymore (the workflow also looks at local trigger primitives produced with a different format, that keep being produced).

We apologise for the issue that got unnoticed during the transition to the uROS unpacker.

Best,

Carlo for DT

[1] https://github.com/cms-sw/cmssw/pull/23072
[2] https://github.com/cms-sw/cmssw/pull/23071
[3] /store/unmerged/express/logs/prod/2018/4/25/Express_Run315104_StreamExpress/Express/0000/3/Express-008f0a70-c1f2-417b-b694-2f3f6a7884d9-3-logArchive.tar.gz

**Comment by battibass** [comment]
Correct, after the fix I see:
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 315104 lumi: 93 event: 34403445 stream: 2
   [1] Running path 'pathALCARECODtCalib'
   [2] Calling method for module DTLocalTriggerSynchTask/'dtTriggerSynchMonitor'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: MuonDigiCollection<DTChamberId,DTLocalTrigger>
Looking for module label: muonDTDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```
disappear.

**Comment by jfernan2** [comment]
the crash from AddOn seems unrelated, I launch the test again
please test

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 the crash is in fastsim and has nothing to do with this PR, and it does not look reproducible when running a standalone cross check

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 could you please check and sign it in case? I would like to get it in asap and build pre2

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
