### PR TITLE
Let PFClusterEMEnergyCorrector run without SRB inputs

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Let the `PFClusterEMEnergyCorrector` run also in the absence of the ECAL selective bit readout collections.

If these collections are not present (or empty) the `PFClusterEMEnergyCorrector` will assume all hits to have been read with "full readout", without any zero suppression.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by silviodonato** [comment]
This PR is necessary to resolve the GPU-CPU difference we observed in PF ECAL (details in https://its.cern.ch/jira/browse/CMSHLT-2315).
cc @cms-sw/hlt-l2

**Comment by jpata** [comment]
assign hlt

**Comment by jpata** [comment]
assign hlt

**Comment by jpata** [comment]
+reconstruction
- bugfix for HLT (no reco effect)

**Comment by jpata** [comment]
+reconstruction
- bugfix for HLT (no reco effect)

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
let's see if the relvas input tets work...

**Comment by missirol** [comment]
+hlt
 - effectively downgrades an exception to a LogInfo
 - needed as part of [CMSHLT-2315](https://its.cern.ch/jira/browse/CMSHLT-2315), to reduce CPU-GPU discrepancies related to ECAL
 - no differences in PR-tests outputs expected, nor observed

**Comment by qliphy** [comment]
+1

**Pull request merged**
