### PR TITLE
Replacing adler32 with CRC32-C in FRD (raw data format) v5 - 74X

### PR DESCRIPTION
**Pull request by smorovic**
- correct unlock in input source at the end of the run
- "Failsafe" is set as JSON stream destination field in case of unsucessful determination with HLT menu and selected transfermode
- renamed reserved TCDS FED header variable to triggerTypeFlags
- support for Intel acceleration of CRC-32C with new FRD v5 (replaces adler32)

### CODE REVIEW

**Comment by smorovic** [comment]
This is 74X pull request of commits in (75X) #8907

**Comment by mommsen** [comment]
+1

**Comment by smorovic** [comment]
@cmsbuild please test
(it seems that the last commit didn't trigger the usual chain of events)

**Comment by mommsen** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
