### PR TITLE
[HGCal] Material budget from vertex up to in front of muon stations

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

The new V10 HGCal geometry in D41 scenario introduces significant reduction of material budget from V9 (~1.5λ). Motivated by the strong interest in how is this change effecting the Muon system, we estimated (@felicepantaleo , @rovere ) the total thickness, in nuclear interaction lengths, in front of Muon Stations versus eta, starting from the vertex. 

In this PR, we add the relevant changes that are necessary to perform the above study. Special care was taken so that the existing HGCal material budget study is not effected, so that someone can easily run both tasks without any conflict. 

#### PR validation:

The results of this work has been presented in the HGCal DPG [1] and we have checked that the standard HGCal material budget study presented previously [2] is not effected and the two can be run side by side. 

Detailed instructions on running the standard HGCal material budget study has been written in the HGCal webpage [3] while more instructions on the current study will be added in the same place. 

#### if this PR is a backport please specify the original PR:

This is not a backport. 

[1] https://indico.cern.ch/event/820095/contributions/3428509/attachments/1844946/3026574/MatBudInFrontofMuonStations_15May19.pdf

[2] https://indico.cern.ch/event/813555/contributions/3400815/attachments/1831509/2999507/Psallidas-MaterialBudgetV10.pdf

[3] http://hgcal.web.cern.ch/hgcal/MaterialBudget/MaterialBudget/

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
