### PR TITLE
Subdirectories for GEM-CSC LUTs

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

GEM-CSC LUTs are being organized into subdirectories
   * CoordinateConversion (already filled): coordinate GEM strip and eta partition number to CSC half-strip and wiregroup
   * SlopeCorrection (coming in next PR): for finding accurate GEM trigger matches
   * BendingAngle (coming in next PR): for assigning the bending angle to be used in the Run-3 EMTF.

This should fix the issue in https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/8

#### PR validation:

Code compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
Hi @cecilecaillol. Sorry I should have clarified. Could you test again with cms-data/L1Trigger-CSCTriggerPrimitives#8?

**Comment by qliphy** [comment]
@cms-sw/l1-l2  please also check and sign https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/8

**Comment by silviodonato** [comment]
+1

**Pull request merged**
