### PR TITLE
ME0ReDigitizer not using roll==0 to distinguish between M1 and M2 geometry

### PR DESCRIPTION
**Pull request by pietverwilligen**
This PR provides a bugfix for PR #17175. The inclusion of a request to change the numbering starting from 1 broke the ME0Digi chain and resulted in bad rechits.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by slava77** [comment]
the crash is apparently related to the updates made here
```
#5  0x00007f4b14cec5f8 in ME0SegmentAlgorithm::buildSegments(std::pair<ME0Chamber const*, std::map<unsigned int, ME0EtaPartition const*, std::less<unsigned int>, std::allocator<std::pair<unsigned in
t const, ME0EtaPartition const*> > > > const&, std::vector<ME0RecHit const*, std::allocator<ME0RecHit const*> > const&, std::vector<ME0Segment, std::allocator<ME0Segment> >&) () from pluginRecoLocalMuonGEMSegmentAuto.so
#6  0x00007f4b14cee528 in ME0SegmentAlgorithm::run(std::pair<ME0Chamber const*, std::map<unsigned int, ME0EtaPartition const*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, M
E0EtaPartition const*> > > > const&, std::vector<ME0RecHit const*, std::allocator<ME0RecHit const*> > const&) () from pluginRecoLocalMuonGEMSegmentAuto.so
#7  0x00007f4b14cf7cd4 in ME0SegmentBuilder::build(edm::RangeMap<ME0DetId, edm::OwnVector<ME0RecHit, edm::ClonePolicy<ME0RecHit> >, edm::ClonePolicy<ME0RecHit> > const*, edm::RangeMap<ME0DetId, edm:
:OwnVector<ME0Segment, edm::ClonePolicy<ME0Segment> >, edm::ClonePolicy<ME0Segment> >&) () from /pluginRecoLocalMuonGEMSegmentAuto.so
#8  0x00007f4b14cdbd69 in ME0SegmentProducer::produce(edm::Event&, edm::EventSetup const&) () from pluginRecoLocalMuonGEMSegmentAuto.so

```

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @pietverwilligen - please update the title of the PR to describe the change made. Thanks

**Comment by davidlange6** [comment]
Ping @pietverwilligen

**Comment by pietverwilligen** [comment]
done

**Comment by davidlange6** [comment]
+1

**Pull request merged**
