### PR TITLE
Phase2-hgx327F Modify more scripts in Geometry/HGCalCommonData/test/python to retain minimum number of scripts useful for V16, V17 and TB setups

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify more scripts in Geometry/HGCalCommonData/test/python to retain minimum number of scripts useful for V16, V17 and TB setups

#### PR validation:

Test by running the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
@bsunanda we have some Phase 2 HCAL geometry problems [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-10-31-2300/pyRelValMatrixLogs/run/20834.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2/step2_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2.log#/), will this fix the issue (or at least be orthogonal)?

**Comment by perrotta** [comment]
> @bsunanda we have some Phase 2 HCAL geometry problems [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-10-31-2300/pyRelValMatrixLogs/run/20834.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2/step2_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2.log#/), will this fix the issue (or at least be orthogonal)?

Uhm, I was supposing that #39920 should have already fixed the issue pointed out by Sal, but it was evidently not the case.
Could you please comment about it @bsunanda ?

As usual, some more information in the PR description fields would help better understanding what the PR is actually intended for. For exemple here it is written "modify more scripts in Geometry/HGCalCommonData/test/python", but looking at the files touched there is clearly much more than a few test scripts.

**Comment by srimanob** [comment]
Hi @perrotta @bsunanda @rappoccio 
I am not sure why https://github.com/cms-sw/cmssw/pull/39920 plays the game here. From comment in the PR,
https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296568646, it seems that it is not a bug fix. It uses to protect wrong PU file, which I understand that it should not happen it you use the proper PU file. That what I tried to summarize in https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296594157. Something beyond that?

**Comment by perrotta** [comment]
> Hi @perrotta @bsunanda @rappoccio I am not sure why #39920 plays the game here. From comment in the PR, [#39920 (comment)](https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296568646), it seems that it is not a bug fix. It uses to protect wrong PU file, which I understand that it should not happen it you use the proper PU file. That what I tried to summarize in [#39920 (comment)](https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296594157). Something beyond that?

Ok, got it: thank you @srimanob 
So the error pointed out here above will stay there until the correct files for mixing events are used instead.

Still, the question to @bsunanda remains: please update the PR description, because  here it is written "modify more scripts in Geometry/HGCalCommonData/test/python", but looking at the files touched there is clearly much more than a few test scripts.

**Comment by makortel** [comment]
> > Hi @perrotta @bsunanda @rappoccio I am not sure why #39920 plays the game here. From comment in the PR, [#39920 (comment)](https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296568646), it seems that it is not a bug fix. It uses to protect wrong PU file, which I understand that it should not happen it you use the proper PU file. That what I tried to summarize in [#39920 (comment)](https://github.com/cms-sw/cmssw/pull/39920#issuecomment-1296594157). Something beyond that?
> 
> Ok, got it: thank you @srimanob So the error pointed out here above will stay there until the correct files for mixing events are used instead.

The root cause of these failures is the same as in issues https://github.com/cms-sw/cmssw/issues/39480 and https://github.com/cms-sw/cmssw/issues/39445. #39920 made the inconsistency (wherever it comes from) more visible by always throwing an exception instead of random crashes. The cause can not be caused by pileup, because the failing workflow(s) do not use any pileup.

**Comment by bsunanda** [comment]
Sorry - I am a bit confused in all this. The PR's #39920 and #39921 (backport to 12_5_X) came because of a na observation by Chris that in some workflow, there is some crash because some limits are violated - now this happens in cases where a cell which is valid in run2 or 3 appears ina geometry setup of run4. This can happen either for signal or for pileup files (the second case is more likely). The best is to protect the code with an exit statement - tis is certainly a configuration error of some sort. The current PR is a clean up of HGCal test scripts which never apears in any production scenario.
________________________________

**Comment by srimanob** [comment]
I would propose to have a clarification of https://github.com/cms-sw/cmssw/pull/39920 in git issue. If it is clear later, we can just close the issue. Sorry to say this, the PR description is not align with what is mentioned here now.

**Comment by perrotta** [comment]
+1
- Latest issue discussed here were not about this PR

**Pull request merged**
