### PR TITLE
added missing dependency; header cleanup

### PR DESCRIPTION
**Pull request by smuzaffar**
Adding missing dependency on `DataFormats/EcalDigi` which is used by [a]. Although it is header only dependency but by definition we should have it in BuildFile too.
Cleanup unused include header too.

[a]
```
CondFormats/EcalObjects/src/EcalSampleMask.cc:#include "DataFormats/EcalDigi/interface/EcalDataFrame.h"
CondFormats/EcalObjects/src/EcalSampleMask.cc:  sampleMaskEB_ = pow(2, EcalDataFrame::MAXSAMPLES) - 1;
CondFormats/EcalObjects/src/EcalSampleMask.cc:  sampleMaskEE_ = pow(2, EcalDataFrame::MAXSAMPLES) - 1;
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
merge
@ggovi please let me know if you have any objections

**Pull request merged**
