### PR TITLE
[14_0_X SIM] Improved initialisation of sensitive detectors

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR is created to address #42986. For each type of Run it is possible to customize the list of SD classes and the list of produced hit collections. It is not expected to have a visible CPU or memory reduction but this will allow to increase clarity of the configuration. If a new detector and an extra hit collection will appears it would be easy to add to the g4SimHits configuration file. No change in any WF is expected. 
 
#### PR validation:
short matrix + private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
Was my suggestion in https://github.com/cms-sw/cmssw/issues/42986#issuecomment-1760344988? My feeling is that would be easier to maintain (as the point of `produces()` calls and the `event.put()` calls would be closer) than a completely separate list of product instance names.

**Comment by civanch** [comment]
@makortel , we discussed the issue with @bsunanda  and come to conclusion that this hardcoded list of produced hit collection is a simple and transparent solution. Difficulty to do things differently connect with the fact that SD objects are created much later than we have to report, which hit collection will be produced. Because of that in past we declare all possible hit collection in the constructor of OscarMTProducer, now we define the list corresponding to the era.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
Because this PR is too big, it is substituted by #43477.

**Pull request closed without merging**
