### PR TITLE
Run3-hcx281 Make showerlibrary producer work

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make showerlibrary producer work and also add some protection in debug mode

#### PR validation:

Tested using test scripts in SimG4CMS/ShowerLibratyProducer/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@silviodonato @qliphy Can this PR be integrated?

**Comment by silviodonato** [comment]
merge
@cms-sw/core-l2 please double check

**Pull request merged**
