### PR TITLE
Cleaning of Configuration/StandardSequences/python/Analysis_cff.py and FastSimulation/Calorimetry/python/TreeWriterForEcalCorrection_cfg.py

### PR DESCRIPTION
**Pull request by silviodonato**
It looks like `Configuration/StandardSequences/python/Analysis_cff.py` is used only in `FastSimulation/Calorimetry/python/TreeWriterForEcalCorrection_cfg.py`.

`python/TreeWriterForEcalCorrection_cfg.py` requires a not existing `python.fastFileList`

`TreeWriterForEcalCorrection_cfg` seems a trivial configuration file, which has not modified since 2015.

This PR removes both `Configuration/StandardSequences/python/Analysis_cff.py` and `FastSimulation/Calorimetry/python/TreeWriterForEcalCorrection_cfg.py`

@kkiesel this file was added with #10596 (#11045). Please note I'm removing only the cfg file.

This PR is related to the cleaning of the Analysis packages (#32917)

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
The error is not related to this PR
```
----- Begin Fatal Exception 15-Feb-2021 13:15:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.�
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=&xrdcl.requuid=6bf4650c-fe39-4d9b-b4d0-51868268f097
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
@cms-sw/fastsim-l2 do you have any reason to keep `FastSimulation/Calorimetry/python/TreeWriterForEcalCorrection_cfg.py` ?

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
do you have any objections @cms-sw/fastsim-l2 ?
The failure of 4.76 is not related to this PR

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/fastsim-l2

**Comment by silviodonato** [comment]
@mdhildreth @sbein @ssekmen @lveldere @civanch

**Comment by silviodonato** [comment]
unhold

**Comment by civanch** [comment]
+1

if these files are needed for some private work they can be easily restored from legacy releases.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
