### PR TITLE
[Backport] Discard Beamspot fit results when d0-phi fit status is unknown

### PR DESCRIPTION
**Pull request by sarafiorendi**
Backport of #25319

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by perrotta** [comment]
type bugfix

**Comment by perrotta** [comment]
Is this extra accepted trigger path in RunJetHT2017FreMINIAOD wf 136p8311 depending on this fix?

image

**Comment by davidlange6** [comment]
note that this workflow doesn't rerun the HLT..

**Comment by perrotta** [comment]
Good point, thank you @davidlange6 : then I am puzzled...

**Comment by tocheng** [comment]
+1

**Comment by perrotta** [comment]
+1
- The fix prevents returning NaN's from the offline beamspot parameters
- Jenkins tests pass, and standard workflows are unaffected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
