### PR TITLE
Add superclusterEta of photon in NANOAOD

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:
This PR is to add the superclusterEta of photon in NanoAOD. 
In case of electron "deltaEtaSC" is stored in NanoAOD from which we can get the supercluster Eta easily.
Such a variable was never stored for photon  before in NanoAOD. 
Photon supercluster eta is w.r.t  0,0,0, while photon eta is w.r.t primary vertex. 
Currently this variable is being calculated from photon eta in NanoAOD using the code provided by EGM POG : https://swmukher.web.cern.ch/swmukher/scEtaPhoNanoAOD.C
However, we see non-negligible differences for this computed variable and the direct supercluster Eta from MiniAOD.  The difference is more in EB than EE.
 EGM report here : https://indico.cern.ch/event/1340058/contributions/5641368/attachments/2742887/4771900/Photon_scEta_difference.pdf
From Hgg analysis team, similar difference in the supercluster Eta has also been seen. 
Hgg report here[Slide 8] : https://indico.cern.ch/event/1233738/contributions/5474144/attachments/2675923/4640510/2023_LMComparions_UL18_Hgg.pdf
Since it is an important variable, we think it may be stored in NanoAOD.

#### PR validation:
runTheMatrix tests have been successfully run for the following workflow :

- runTheMatrix.py -l 12434.0

#### Backport
We target this to go in Nano V13 for now. backport might be  required if the Nano production happens in the earlier CMSSW release.

Tagging EGM L2 convenors @a-kapoor and @RSalvatico 
Hgg convenors @lfinco , @fcouderc, @JaLuka98

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by RSalvatico** [comment]
type egamma

**Pull request merged**
