### PR TITLE
Migrate tracker local reconstruction to Tasks

### PR DESCRIPTION
**Pull request by makortel**
Title says it all. I migrated all downstream configurations I managed to find with `git grep`.

Tested in CMSSW_10_4_X_2018-11-05-1100, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 135.13,10024.1,10024.5

**Comment by andrius-k** [comment]
Hi @makortel, are you planning to test this PR in playback?

**Comment by makortel** [comment]
@andrius-k Umm, I'm not (I have no idea how to do that), but I don't mind if someone else tests.

**Comment by boudoul** [comment]
My two cents : This is a pure 10_4_X developments, and will be (assuming success of the review) part of a 10_4_X release at some point - I do not see the point of a playback - 10_4_X release will be used in the online DQM (and therefore part of a playback)  in ... a year > 2018

**Comment by makortel** [comment]
On the other hand I do agree that testing the online clients (as part of PRs and/or in IBs) would be beneficial, as otherwise it is very easy to accidentally break them in technical migrations like here (as has happened many times in the past). Otherwise we may end up in testing them next time in spring 2021 or so.

**Comment by andrius-k** [comment]
@makortel, as @boudoul mentioned I didn't realise, that this is for 10_4_X so playback testing doesn't make sense.

**Comment by mmusich** [comment]
@andrius-k @boudoul @makortel, 
as far as I know it is possible to test the client using past RAW data (which is not as good as testing the code in the playback, but for sure it's better than nothing).
My modest proposal is to ask @jandrea and @arossi83 to re-run the client on some past data with these changes to make sure it doens't break the online client (though seems hard to believe it might do so, as offline there is no apparent change)

**Comment by slava77** [comment]
```git grep -l -w trackerlocalreco | grep -c py$``` returns 49 hits.
I see only 8 files modified here with trackerlocalreco.

One set of cases is a different definition of trackerlocalreco in e.g. RecoLocalTracker/Configuration/python/RecoLocalTrackerHeavyIons_cff.py and RecoLocalTracker/Configuration/python/RecoLocalTracker_Cosmics_cff.py. Where these not migrated on purpose?


Ignoring /test, /clients, /doc directories, and commented out lines, it looks like everything coming out of RecoLocalTracker/Configuration/python/RecoLocalTracker_cff.py was migrated. Good.

Looking at /test e.g.  DQM/BeamMonitor/test/beam_dqm_sourceclient-file_cfg.py and a few similar examples pick the trackerlocalreco from  Configuration/StandardSequences/python/Reconstruction_cff.py and then use \* or \+ syntax to add it to a Sequence type. 
IIUC, configurations like these will be broken.
So, this PR is incomplete in the context of the python configs available in the release.

A somewhat less invasive migration already used in the past is to define a trackerlocalrecoTask and instantiate a trackerlocalreco cms.Sequence from it and then explicitly change to trackerlocalrecoTask where it is relevant.

**Comment by makortel** [comment]
@slava77 Thanks, so my grepping has become really rusty... 

> A somewhat less invasive migration already used in the past is to define a trackerlocalrecoTask and instantiate a trackerlocalreco cms.Sequence from it and then explicitly change to trackerlocalrecoTask where it is relevant.

Yeah, that might be a good idea (maybe for #25110 as well). I did think of that, but recalling my past irritation with e.g. the task+sequence approach in iterative tracking configuration wanted to try to do the full migration as well, but then didn't (naively) realize how cumbersome it would really be. Maybe we then need to have (nearly) all standard sequences migrated to tasks first before removing the then-empty sequences.

**Comment by slava77** [comment]
On 11/7/18 3:06 PM, Matti Kortelainen wrote:
> @slava77
> Thanks, so my grepping has become really rusty...
> 
>     A somewhat less invasive migration already used in the past is to
>     define a trackerlocalrecoTask and instantiate a trackerlocalreco
>     cms.Sequence from it and then explicitly change to
>     trackerlocalrecoTask where it is relevant.
> 
> Yeah, that might be a good idea (maybe for #25110
> as well). I did think of that, but recalling my past irritation with
> e.g. the task+sequence approach in iterative tracking configuration
> wanted to try to do the full migration as well, but then didn't
> (naively) realize how cumbersome it would really be. Maybe we then need
> to have (nearly) all standard sequences migrated to tasks first before
> removing the then-empty sequences.
> 

Now that I've looked more carefully, I see that my signoff of #25110 was
premature.
The xyzTask option can lead to quite a bit of duplication.
What are the dangers of making the * or + on tasks in sequences/paths to
be treated as .associate ?

**Comment by makortel** [comment]
> The xyzTask option can lead to quite a bit of duplication.

That was exactly the part I didn't like in it. On the other hand the duplication is limited to Sequence/Task objects (i.e. for each current Sequence there would be a Task as well), but the contents of a Task(/Sequence) would be defined only once, and the Sequence is defined just as `foo = Sequence(fooTask)` (which could still be tolerable).

**Comment by makortel** [comment]
@slava77 

> What are the dangers of making the * or + on tasks in sequences/paths to
be treated as .associate ?

They would introduce the wrong mental model. For example, with `Sequence` a `Path(fooFilter + fooSequence)` it is clear that `fooSequence` will be run for an event only if `fooFilter` returned `true`. With a `Task`, if a similar construct `Path(fooFilter + fooTask)` would be allowed, it could be mis-interpreted to have the same logic (especially when the `Task` would not have a "Task" in its name).

**Comment by makortel** [comment]
Superseded by #25163 (that avoids a massive migration, sorry for the noise).

**Pull request closed without merging**
