### PR TITLE
Fixes to TkMap script

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR fixes a crash in the Tracker Map production script in the case the DQM Online file for Pixels is not available and prevent to Draw a misleading legend on empty Tracker Maps.

No interference with any production sequences, the code is only used Offline by Tracker shifters.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by perrotta** [comment]
+1
- This PR is mostly for DQM (used by Tracker shifters, as pointed out in the description)
- The modification in CommonTools/TrackerMap/src/TrackerMap.cc just prevents drawing a misleading legend in a plot when there are empty Tracker Maps
- No change expected in reco, and no effect is visible in the output of jenkins tests

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
