### PR TITLE
EP pcombination protection

### PR DESCRIPTION
**Pull request by rafaellopesdesa**
Same PR as https://github.com/cms-sw/cmssw/pull/13279, but for 76X.

att: @fcouderc  @matteosan1

### CODE REVIEW

**Comment by slava77** [comment]
@rafaellopesdesa 
Is this part of the code used only in analysis?
If it is running in standard miniAOD/reco workflows, we can not make changes in 76X.

**Comment by rafaellopesdesa** [comment]
Hi Slava,

It is run in both: miniAOD/reco workflow and analysis (for the final
data/MC smearing). What do you recommend as a course of action?

Thanks,
-- Rafael.

**Comment by slava77** [comment]
The policy is to have no significant physics change in reco/miniAOD outputs in production releases
(exceptions are rather minimal and are limited to a set of otherwise failing/crashing events).

You can make the change configurable so that it can be picked up in analysis job on demand.

So, 76X and 74X PRs will either need to be modified or closed.

**Comment by rafaellopesdesa** [comment]
Hi Slava,

Since the users will still need for analysis (as explained above), I will
propose a configurable solution for 76 and 74 this night. I will update
them (probably close the 76X and make another one, since they use the same
branch as the 80X, but the 74X will just be updated).

Is that a good plan?
-- Rafael.

**Comment by slava77** [comment]
Hi Rafael,

this sounds good.

Slava

**Comment by rafaellopesdesa** [comment]
I am closing this PR. I will redo with a branch just for 76X in which this correction is optional. I will leave this branch just for 80X.

**Comment by slava77** [comment]
Hi Rafael,

Based on git grep, I see that this code is used only in CalibratedElectronProducer and CalibratedPatElectronProducer.
I do not see either of these producers running in standard workflows.
If it is the case (standard workflows are not running it) then this qualifies as analysis code and the same change can be applied in 76X/74X as in 80X.

Please check, just in case the fix is not applied to all needed places.

**Comment by rafaellopesdesa** [comment]
Hi Slava,

I am checking if the Ep combination is not used somewhere else in the code.
I will confirm as soon as I am done.

Thanks for the input,
-- Rafael.

**Pull request closed without merging**
