### PR TITLE
increase track length w/o increasing fake rate

### PR DESCRIPTION
**Pull request by VinInn**
It has been reported several time that the tracking hit-efficiency  seems to dramatically decrease with track length . It is easy to track this down to the score used to select the "best candiate" among all those spurring from the same seed. It's current tuning is clearly adjusted to reduce fake-rate in particular for "low pt" tracks.  Waiting for a clever score (ML based?) here we try to mitigate the effect increasing the weight of the number of hits w/r/t the chi2 for tracks with pt>0.9GeV (which seems to be a magic number in the whole history of CMS tracker).
 
Some evidence
SingleMuon 4GeV (PhaseI 810pre16) hit efficiency
black 810 out of the box
blue same w/o muon-seeding iterations
orange same + the proposed mitigation
effmu4pt

here for real data JetHT Run 279685
black out of the box
blue proposed mitigation

effrealdata

here is MTV for usual ttbar25ns PU35 phase0
https://innocent.web.cern.ch/innocent/RelVal/pu35_81_16f10pt/plots_highPurity/effandfake1.pdf

and in case you wonder, that's what happens if the pt cut is NOT applied
https://innocent.web.cern.ch/innocent/RelVal/pu35_81_16f10d/plots_highPurity/effandfake1.pdf
a future technical PR will try to optimize and  factorize code (it will most probably recompile half tracking and tracking dependent code)

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@arizzi @makortel

**Comment by VinInn** [comment]
@venturia @boudoul

**Comment by slava77** [comment]
@VinInn 
90X PR was auto-created #16593 
please close this

**Pull request closed without merging**
