### PR TITLE
[14.1.X] Fix HLT Phase2 timing script.

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46185

#### PR description:

This should fix the script and profit of the new features added to the underlying benchmark script.

#### PR validation:

successfully tested in master 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/46185 to CMSSW_14_1_X.

### CODE REVIEW

**Comment by mmusich** [comment]
enable hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by rovere** [comment]
@mmusich thanks for the backport!!

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
