### PR TITLE
Cleanup, RecoJets/JetAnalyzers, Motivated by JetCorrector Migration

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Cleanup in RecoJets/JetAnalyzers. Removes archaic example modules. This only deletes files.

The Core group is attempting to complete a migration started in 2014 that moves from using the old ::JetCorrector class to using the reco::JetCorrector class. We are trying to centrally complete this migration. In RecoJets, the old JetCorrector class is only used in the example modules deleted by this PR. This PR is one of many PRs related to this migration. At this point, there are PRs submitted removing all usage of the old JetCorrector. Four of these PRs are still under review (including this one) and the rest already merged. This is related to the consumes migration and multi-threading performance.

All of the deleted example modules are 10 to 15 years old and so full of deprecated non-functional code that it would be harmful for someone to read as an example. 10 to 15 years ago these might have been useful, but at this point deleting them is a positive thing independent of the JetCorrector migration. We should not be using resources to distribute, build, and maintain code like this.

Note that if someone believes these examples are valuable, the code could be restored from the git history and fully updated at some point in the future.

I'll also note that I only looked at code using the deprecated JetCorrector class. There is more code that could be updated or deleted in this package.

Some of the problems:

- Don't call consumes and use getByLabel (fails).
- Use deprecated JetCorrector (fails).
- No unit tests or relVal tests.
- Nothing references any of these other than test configs also deleted
- Configs load cff files that no longer exist
- Use corrections that no longer exist
- Ancient input files that probably no longer exist
- There is nothing deep and useful that really needs saving

#### PR validation:

Only deletions. Nothing to test. Nothing could be using them because they don't work anymore.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by clacaputo** [comment]
Hi @wddgit , could you please update the PR title? IIUC there is no "migration" but a clean-up. I suppose the removal as been discussed with @cms-sw/jetmet-pog-l2

**Comment by wddgit** [comment]
@clacaputo I modified the title and the description at the top. Hopefully that is more clear.

This has not been discussed recently at the jetmet pog. There are a few reasons that shouldn't be necessary. First, the JetCorrection migration was discussed long ago and has been approved for years. Almost all reconstruction code has already been migrated to use the new JetCorrector and not use the old JetCorrector. Second, I am a core developer and I've been doing this migration work in many different packages across CMSSW. If I gave a presentation for each package, it would take me a very long time to get it done. Third, there is no new functionality here. This PR just deletes dead code. There is not much to present or discuss.

If it is necessary, could you take care of presenting this to the pog? I know very little about jet or met reconstruction code or how it is documented and what examples exist...

Note that if the deleted example files are actually useful, then when it is convenient someone could restore them from git history and update them to be good examples of modern code.

**Comment by wddgit** [comment]
New info related to this: The PR that deletes the deprecated header file (JetCorrector.h) was submitted, https://github.com/cms-sw/cmssw/pull/39953. I tested it on top of this PR (and 3 other similar ones), all PR tests pass. Further, I ran runTheMatrix.py (the full version with all 1000+ tests) and that passes. It successfully compiles and builds.

@clacaputo I saw your thumbs up to my last response. Are we waiting on the jet-met pog before approving this PR? When does that occur? Are there any other questions?

**Comment by clacaputo** [comment]
please test

just refreshing the test results

**Comment by wddgit** [comment]
please test

Try again. The latest failures don't appear related to the PR. Note this PR was included when I tested #39953 on Saturday and that passed.

**Comment by wddgit** [comment]
please test

Try again, timeouts in the RelVals this time, is there any way to avoid those? Is it just too many things trying to run on our build machines at the same time? This appears unrelated to the PR.

Note that the PR tests have passed twice since the last time the code was modified. Given this is 100% file deletions, it is unlikely some underlying code change could break something. The only possibility would be someone adding a new test or adding to an existing so that it uses one of the deleted modules... And that wouldn't be a timeout.

**Comment by wddgit** [comment]
Hooray! Third time is the charm. Tests are green again.

**Comment by clacaputo** [comment]
+ reconstruction

- the PR remove unused code
- no reco changes are introduced

**Comment by perrotta** [comment]
+1

**Pull request merged**
