### PR TITLE
[12_3_X] Update final L1T menu tag for Run 3 start up

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #37442.
This PR updates the final L1T menu tag for Run 3 start up, as requested in [this CMSTalk post](https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-l1-menu-tag-v1-0-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/8895), for Run3 MC GTs and the Run3 relval GTs used for TSG tests.
The new L1T tag is `L1Menu_Collisions2022_v1_0_0_xml`.

GT differences:

**Run 3 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_relval_v2/123X_dataRun3_HLT_relval_v3

**Run 3 data RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_relval_v2/123X_dataRun3_relval_v3

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v12/123X_mcRun3_2021_design_v13

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v12/123X_mcRun3_2021_realistic_v13

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v12/123X_mcRun3_2021cosmics_realistic_deco_v13

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v12/123X_mcRun3_2021_realistic_HI_v13

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v12/123X_mcRun3_2023_realistic_v13

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v12/123X_mcRun3_2024_realistic_v13

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun4_realistic_v9/123X_mcRun4_realistic_v10

#### PR validation:
Tested with:
`runTheMatrix.py -l 12034.0,11634.0,7.23,159.0,12434.0,12834.0 --ibeos -j16`

#### Backport:
Backport of #37442

FYI @elfontan @Martin-Grunewald

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #37442

**Comment by francescobrivio** [comment]
test parameters:

 - workflows=12034.0,7.23,159.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * results consistent with the results seen in master

**Comment by qliphy** [comment]
+1

**Pull request merged**
