### PR TITLE
Store DeepTauID in NanoAOD (backport for UL)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR is to store novel DeepTauIDs computed at MiniAOD step to NanoAOD tables.
It can be seen as an follow up action announced here: https://github.com/cms-sw/cmssw/pull/27146#issuecomment-502048728

Expected changes: six new variables are added to tau table in NanoAOD - three raw values (float numbers) of tau discriminants against jets, electrons and muons misidentified as taus, and three integer numbers encoding corresponding WPs.
NanoAOD for old eras should not be modified and should work on top of corresponding MiniAOD inputs not containing DeepTauID variables.

This PR is backport of  #27226 to 10_6_X for UL.

#### PR validation:

NanoAOD workflows were tested.

#### if this PR is a backport please specify the original PR:

Backport of #27226.

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

**Comment by peruzzim** [comment]
+xpog

as in https://github.com/cms-sw/cmssw/pull/27226#issuecomment-504349250

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

as agreed with XPOG and PPD

**Pull request merged**
