### PR TITLE
Remove muon isolation filter for TkAlZMuMuHI and TkAlUpsilonMuMuHI.  …

### PR DESCRIPTION
**Pull request by jrcastle**
…Experience with 2015 data shows that these filters kill yields in heavy ions

### CODE REVIEW

**Comment by jrcastle** [comment]
Hi,

For more information, when the old common alignment producer was run over the 2015 PbPb data, a total of 300 Z events survived the skim.  Other analyses from heavy ions have shown yields of around 4000.  Cuts were comparable between the two approaches, however the common alignment producer was using a muon isolation filter.  Removal of this filter increased the number of Zs by a factor of 10.  Since the Z yield for heavy ions is so low already, this change is implemented to get as many as possible for alignment efforts.

**Comment by tlampen** [comment]
This is a good finding!! -Tapio

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
