### PR TITLE
HCAL Method2 BX fix and timing adjustment

### PR DESCRIPTION
**Pull request by kfiekas**
Small bug in BX calculation in Method2 has been fixed. In addition, the returned time from Method2 has been changed to real time and is now synchronized with Method0 timing.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

I will also run larger stat tests locally

**Comment by slava77** [comment]
@kfiekas 
please submit a matching PR to 74X

**Comment by slava77** [comment]
unlike in the last update in Method2, the auto-forward port will not work (the changes here are in parts of the code that was changed between 73X and 74X).

**Comment by slava77** [comment]
@bachtis @ahinzmann @abdoulline @violatingcp
please check/confirm that these changes are what was expected from the Friday meeting (or is there more change necessary)
Thank you.

Some plots with this PR would be helpful as well to document what to expect

**Comment by slava77** [comment]
Looking at the time distribution, it's unclear if what we got is an improvement:
(the plots are in the jenkins test comparisons)

4.53 (photon PD 2012B) looks like getting worse

wf4p53_hbhe_time_pr7492
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-01-29-1400+7492/5827/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/

wf 25.0  ttbar MC no PU (run1 configuration) looks like it's getting better
wf25_hbhe_time_pr7492
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-01-29-1400+7492/5827/validateJR/all_OldVSNew_TTbarResimwf25p0/

Do we want this kind of "improvement" ?
Based on this, already, before I can sign off, I will need someone from HCAL DPG (Salavat?) to confirm this is the change we need.

**Comment by abdoulline** [comment]
(adding Hongxuan)

Here is a comparison of High Pt QCD relval sample using 731p1 with the 
method 2 with updated rereco, 
compared to the default 730 relval results (GT MCRUN2_73_V7 in both cases).

http://hep.baylor.edu/cmshcal/Validation/MC/731p1_Method2TimingFix_MCRUN2_73_V7-v1_vs_730_
MCRUN2_73_V7-v1_RelVal/

I'll take a closer look at other resuts early tomorrow (CET).

**Comment by abdoulline** [comment]
Timing has been changed to avoid (timing) disruption betwnen Method 0 and Method 2.
So it's not about "better or worse", but rather about timing re-adjustment. HBHERecHit timing is not used by downstream consumers (even PFlow), so it's more "self-consistency" update than real change in local reco. 
When Method 2 has been first implemented, we have both MC and data timing ("measured", reflecting TimSlew amplitude dependence) quite different wrt Method 0  ("aligned", TimeSlew dependence (mostly) accounted for)
 https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/730_MCRUN2_73_V7-v1_vs_730pre1_PRE_LS172_V15-v1_RelVal/TTbar/RecHits/HB_Timing_vs_Energy.gif
Now this difference should be (almost) removed.

Actually the main purpose of this update (PR) is to address "peak 0" issue (~15% of all RecHits above ZS level for TTbar PU35@23ns) . So that it wouldn't contain anymore rather rare real (non-negligible energy) "lost" hits, but only some very low-energy "rubbish" from the vicinity of noise peak.

**Comment by slava77** [comment]
time is used in PF clustering to select hits

**Comment by bachtis** [comment]
Hi @slava77 . Not in 74X . The last discussion with HCAL was that time cuts are applied intrinsically on the method II in form of constraints therefore we have de-activated timing cuts at hit/cluster levels

**Comment by slava77** [comment]
thanks for clarification.
It seems like time becomes a magic variable that has to be computed right but not used.

**Comment by slava77** [comment]
Some plots towards sign-off:

in 25202 (ttbar with PU35@25ns) the rechit energies changed slightly (the number of hits stays the same at 211303)
there is a substantial reduction in the zero peak
wf25202_hbhe_energy_zoom_sign731p2a

new.vs.old energy (assuming the same ordering) shows that there is some population that was near zero before, now moving to nonzero values)
wf25202_hbhe_energy_old_vs_new_sign731p2a
wf25202_hbhe_energy_old_vs_new_zoom_sign731p2a


1313 (qcd 3 TeV sample)
the energy doesn't change much, slightly moving down.
all_sign731p2avsorig_qcd13tevpt3ts3t5wf1313p0c_log10calotowerssorted_towermaker__reco_obj_obj_energy

jet et shifts slightly to lower values (this is a bit odd, I thought the update was supposed to fix some of the real non-zero hits reported previously at zero)
all_sign731p2avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recocalojets_ak4calojets__reco_obj_et
all_sign731p2avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfjets_ak4pfjetschs__reco_obj_et


neutral hadron pt variations seem small
all_sign731p2avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50

hcal cluster energies move slightly
all_sign731p2avsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfclusters_particleflowclusterhcal__reco_obj_energy

... to be continued

**Comment by bachtis** [comment]
Hi all, I thought this would have impact only on time . Can somebody explain why there is change in energy?

**Comment by abdoulline** [comment]
Slava,  for 25202 (ttbar with PU35@25ns) I could only find 10 ev in runTheMatrix for RECO
(to analyze myself) 
Where did you get bigger (100 ev) stat?

**Comment by slava77** [comment]
Salavat, 
you can pass arguments and ask for more events
``` runTheMatrix.py -l 25202.0 --useInput all --command=" -n 100" ```

**Comment by slava77** [comment]
Looking at Photon2012B 1K events, it seems like this code is generating some extra MET
wf453_pfmet_new_vs_old_sign731p2a
the stats are low, but still:  two events have MET significantly higher

**Comment by abdoulline** [comment]
You mean on the vertical axis -  "new", while on the horizontal one - "reference"? 
Could it be the other way around (means lower now than before)?

**Comment by slava77** [comment]
Yes, the vertical axis is new and the horizontal is the reference.
I double-checked.

On 2/2/15 8:05 AM, abdoulline wrote:
> You mean on the vertical axis - "new", while on the horizontal one -
> "reference"?
> Could it be the other way around (means lower now than before)?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7492#issuecomment-72462402>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by slava77** [comment]
in the 3TeV MC sample (wf 1313), MET moves about, possibly slightly to the increase as well
(the plot is metNew - metReference (y axis) vs metReference (x axis), the last bins include overflows)
wf1313_diff_pfmet_new_vs_old_sign731p2a


the same for flat-pt dijet QCD (wf 38.0)
MET shifts slightly to lower values, but there are still cases with ~zero MET in the reference promoted to higher values.
wf38_diff_pfmet_new_vs_old_sign731p2a

**Comment by slava77** [comment]
What are the variables to look at to see that the changes in the code are making things better on the physics side?

https://cloud.githubusercontent.com/assets/4676718/6000075/d75760c8-aa9e-11e4-99ed-f775f9d15afa.png was suggestive of an improvement at the zero energy being promoted to non-zero; but then looking at MET, it seems like these zeroes are going both ways, occasionally generating extra MET.

**Comment by slava77** [comment]
If my memory is right, the plan was to build a special release with this PR
to be able to get a thorough JetMET evaluation.
On just technical side, this PR is fine and can be used for that special release.

It's quite not obvious though if it should go into the main release trunk.
@davidlange6 David, what should be the procedure here?

**Comment by slava77** [comment]
DQM plots follow:

3 TeV dijet sample
hcal time vs energy is more flat now
wf1313_tower_time_vs_e_low
wf1313_tower_time_vs_e_low_he
wf1313_tower_time_vs_e_low_profile

Jet response is a bit lower:
wf1313_ptrecoovergen

looking at the profile in flat-pt sample (wf 38), the response is more or less unchanged (a larger variation is visible only in endcap)
wf38_ptrecoovergen_endcap

**Comment by slava77** [comment]
Here are a few more plots of time vs energy, this time from data: this clarifies the second component.
The bump remaining at zero is primarily from low-energy hits in the barrel.

The events are 1K events from wflow 4.53
wf453_hb_time_vs_energy_low_scatter
wf453_he_time_vs_energy_low_scatter

wf453_hb_time_vs_energy_low
wf453_he_time_vs_energy_low

**Comment by slava77** [comment]
I'm done checking the plots.
- this looks like a +1 for the MC HCAL time ; not so clear for data
- a fraction of rechits previously appearing with zero energy now have non-zero energy. This sometimes generates extra MET (visible only in event-by-event comparisons)
- the bulk of hcal hit energies shifts around a bit without a significant impact downstream, there's maybe a ~1% level drop in response of higher ET central jets.

I need more expert opinion to justify this PR to go to the release now.
I'd propose to descope this for 75X.

**Comment by abdoulline** [comment]
Slava, previous (version) might not serve as a (good) reference...
In this fix there is certainly _improved_ time slices assignment, which 
brings some hits back to real energy from peak 0 (which is not a problem 
per se, especially at high PU, where bigger signal just comes from OOT PU).
MET change is being investigated, but a priori one cannot say it became 
worse.

**Comment by abdoulline** [comment]
I've sent an announcement/query to JetMET colleagues (to try it for PFlow (re-)calibration)

**Comment by abdoulline** [comment]
There are some results of crutiny on how well are treated TTbar hits at high PU35@25ns (100 ev). No issues found in this particular domain by eye-balling all "peak 0" entries with non-negligible energy in TS4.  

peak0_731px_ttbar_pu35_25ns_pr7492_100ev_ts4

Plotting TS3 vs TS4 (for energy ~0 and TS4>5 GeV): 

peak0_731px_ttbar_pu35_25ns_pr7492_100ev_ts4s3

**Comment by slava77** [comment]
Hi Salavat,
should I interpret the last plot
https://cloud.githubusercontent.com/assets/5010650/6018830/2cb13138-ab9a-11e4-8ac9-4587f05abf61.gif
 as a case with TS3 > TS4 and the "in-time hit" is reconstructed at ~zero energy?
I think it's an "OK" case to have E~0 in-time (what's the MC truth info for this one?) 
[maybe I misunderstood and this is actually an example where the MC truth energy is high, but the hit is consumed by the large overlapping PU in TS3]

Note that my plots in https://github.com/cms-sw/cmssw/pull/7492#issuecomment-72463077
were in samples with 0 PU and here the changes in the code were occasionally generating MET.
Can they still be from cases with TS3 > TS4?
The Run 194533 plots are for 50 ns data, so, again, probably not with this particular condition.

**Comment by abdoulline** [comment]
Actually the last plot has no constraints on TS3, some of the points are TS3~TS4 or TS3<TS4. It was an assumtion that in some cases high OOT pulse (TS3) just induces TS4 content in the absence of real signal in TS4. This is obviously the case for an"outsanding" point TS3=175, TS4=32 GeV. 
But then (I have the full log for 80 entries) there are high TS5 cases, aftecting TS4 or similar-height TS2/TS3/TS4, which eventualy end up with the fit yielding OOT pulse and ~0 IT.

In 3-3.5 TeV QCD after the current _TS borders assignment fix_ is applied,  there might be some "bringing back" of real hits (from peak 0), so some differents wrt previous case can be expected.

**Comment by davidlange6** [comment]
@abdoulline  - could you add me+@slava77 to the cc list of your jet met query. Thanks

**Comment by slava77** [comment]
I looked a bit in detail at what's happening in cases with large changes in hit energy.
- the most significant conclusion is that I didn't find a strong correlation between the large pfMet changes and large changes in hit energies (my plots above were pfMet). So, this is good.
- the migration of hits from 0 to some value above 1 compared to the other way is about 5:1 (167 hits went from ~0 to > 1, compared to 34 the other way around)

Before signing off, please confirm (Salavat or Stephanie or Katharina?) that these changes make sense:
the first two is just root tree indices; then there are 4 ints with raw ADC and the capId from the hits, the new energy, the old energy, ieta, depth, and new and old caloMETs.
I selected these from the QCD flat-pt dijet sample with a deltaE threshold of 20 GeV .

```
* eventInd *   hitInd *   ADC1    *    ADC2   *    ADC3   *    ADC4   *    CAPID  * E new     *    E old  *    iEta   *   depth   * calMETnew * calMETold *
*       28 *      447 *         4 *         4 *         1 *         5 *         0 * 23.184209 * 1.125e-06 *        19 *         2 * 15.830185 * 17.149618 *
*      133 *      488 *         3 *         2 *         5 *         9 *         3 * 52.381126 * 14.513108 *        28 *         2 * 14.894344 * 17.204561 *
*      404 *      451 *         3 *         2 *         3 *        17 *         2 * 156.48962 * 120.68462 *       -21 *         1 * 48.499824 * 54.593601 *
*      407 *      495 *         2 *         3 *         3 *         4 *         1 * 21.472896 * 0.6769155 *       -27 *         3 * 13.523726 * 12.239128 *

```

**Comment by slava77** [comment]
One of these helped me to understand better: I selected hits with a change in energy which have exactly the same ADC values in 3,4,5,6 as the one that had a large change from previously large value to now small value.
The second hit below could've probably been picked up as in-time with extra convincing of the fit that it's really a no-pileup (or even 50 ns); with an assumption that this is 25 ns spaced hits, then the new value of zero also makes sense.

```
*      385 *      364 *         3 *         2 *         4 *         2 *         2 *        17 *        13 *         8 * 3.821e-12 * 1.968e-08 *       -16 *         2 * 18.777298 * 22.045057 *
*      548 *      267 *         3 *         3 *         4 *         2 *         2 *        17 *         7 *         5 * 4.049e-08 * 5.4289159 *        11 *         1 * 5.7206263 * 9.6728849 *


```

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7492	 a52b42a

tested in CMSSW_7_3_1_patch2 /test area sign731p2a/
signed based on the discussion above

**Comment by abdoulline** [comment]
Thank you for the detailed scrutiny, Slava.

Yesterday night wasn't able to look at the things. Just would like to 
mention we have 8 TS (Digi) stored for RecHits in 2 aux.words and I was 
looking at every suspicious rechit's digi array. 
In addition: Katharina and I, we don't observe (anymore) rare 
big-good-shape signals falling into "peak 0". This was a primary goal of 
this fix.

    Salavat

**Comment by slava77** [comment]
Salavat,

For me, in this scrutiny the "deal maker" was the confirmation of
small/no correlation between the large diff in HCAL hit energy and the
pfMet values which bothered me the most.

The details of the fit values vs TS ADC values was more educational.

Slava



On 2/4/15 11:43 PM, abdoulline wrote:
> 
> Thank you for the detailed scrutiny, Slava.
> 
> Yesterday night wasn't able to look at the things. Just would like to
> mention we have 8 TS (Digi) stored for RecHits in 2 aux.words and I was
> looking at every suspicious rechit's digi array.
> In addition: Katharina and I, we don't observe (anymore) rare
> big-good-shape signals falling into "peak 0". This was a primary goal of
> this fix.
> 
> Salavat
> 
> 
> On Thu, 5 Feb 2015, Slava Krutelyov wrote:
> 
>> 
>> One of these helped me to understand better: I selected hits with a change in energy which have exactly the same ADC
>> values in 3,4,5,6 as the one that had a large change from previously large value to now small value.
>> The second hit below could've probably been picked up as in-time with extra convincing of the fit that it's really a
>> no-pileup (or even 50 ns); with an assumption that this is 25 ns spaced hits, then the new value of zero also makes
>> sense.
>> 
>> *      385 *      364 *         3 *         2 *         4 *         2 *         2 *        17 *        13 * 
>> 8 * 3.821e-12 * 1.968e-08 *       -16 *         2 * 18.777298 * 22.045057 *
>> *      548 *      267 *         3 *         3 *         4 *         2 *         2 *        17 *         7 * 
>> 5 * 4.049e-08 * 5.4289159 *        11 *         1 * 5.7206263 * 9.6728849 *
>> 
>> 
>> —
>> Reply to this email directly or view it on GitHub.[AEx02iz2ZY1YyIVPCntdMfiTvigqb0LVks5norEDgaJpZM4DaFF8.gif]
>> 
>> 
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7492#issuecomment-72997546>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by davidlange6** [comment]
+1

**Pull request merged**
