### PR TITLE
[12_5_X] Add production-like Run 3 HI MC workflow to relval

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #39284

We would like to profile 12_5_0, so a backport of this PR is needed.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by srimanob** [comment]
test parameters:
- workflows = 158.5,159.0,159.02,159.03
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 Can you please sign backport, too, when you have moment?

**Comment by srimanob** [comment]
+Upgrade

Backport PR.

**Comment by kskovpen** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
