### PR TITLE
Phase2-hgx277 Add other components of hgcal xml for V15 version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add other components of hgcal xml for V15 version of HGCal Geometry

#### PR validation:

Tested using runTheMatrix.py for v14 scenario of HGCal 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
