### PR TITLE
drop type spec in TrackingTools RecoMuon

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Update the safer syntax for existing parameter :
- drop type specifications where the original parameter exists.
- move all parameter inside the clone

Instead of modifying parameters with full type specs, which can be interpreted as an insertion of a new parameter, it is a safer way to protect from parameter name mistakes and will also help in possible parameter migrations.
(The previous PR for RecoHI is [PR#32031](https://github.com/cms-sw/cmssw/pull/32031), [PR#32386](https://github.com/cms-sw/cmssw/pull/32386))

In this PR, total 23 files changed. 

- RecoMuon/Configuration : 1 file
- RecoMuon/L2MuonProducer : 1 file

- TrackingTools/GeomPropagators : 2 files
- TrackingTools/GsfTracking            : 9 files
- TrackingTools/MaterialEffects       : 2 files
- TrackingTools/Producers              : 1 file
- TrackingTools/TrackFitters            : 4 files
- TrackingTools/TrackRefitter          : 3 files

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Type specification in reco python configs dropped as intended
- Jenkins tests pass, with no differences wrt the baseline

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
