### PR TITLE
Fix for large number of efficiency_strings in HLT harvesting

### PR DESCRIPTION
**Pull request by DryRun**
Following up on https://github.com/cms-sw/cmssw/pull/21239, this PR reduces the large number of efficiency strings generated by the HLT harvesting configurations (Exotica, Higgs, and SMP). The large number corresponds to:
[all analyses] * [all triggers] * [all object types] * [all plot types]

I reduced the strings by only using the actual analysis-trigger combinations, rather than compiling all of the triggers into a single giant list. I also moved the creation of the postprocessors to functions, e.g. `make_exo_postprocessor()`.

For Exotica and SMP, the changes were relatively trivial, but hltHiggsPostProcessors_cff.py was much more involved... the lists used in the `for` loops were repeated re-initialized and appended to at random points in the code, making it very difficult to figure out what was going on. I ran some runTheMatrix tests to make sure I didn't accidentally remove any plots, but this might merit more scrutiny. Feedback would be welcome, if anyone has a suggestion for how to do this systematically.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @DryRun - are the differences seen in hlt monitoring histograms expected?

**Comment by DryRun** [comment]
Hi @davidlange6 - sorry, I should have commented on that earlier. One of the HLT Higgs validators did a diff of the histogram outputs and spotted a few classes of histograms that were dropped by mistake. I assume that these are the differences observed - I'll try to commit a fix tonight.

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @DryRun - it doesn't seem that your fix worked? Or maybe there are more problems?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-11-27-2300+21387/23984/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HLT.html

**Comment by davidlange6** [comment]
-1
pending updates

**Comment by DryRun** [comment]
@davidlange6 Sorry again for the slow reply, I've been at a workshop. Indeed, my fixes seem not to have worked. I'll spend some more time investigating.

**Comment by DryRun** [comment]
OK, I found the problem after some poking around. The majority of the failures are due to the fact that the bin order in these globalEfficiencies histograms corresponds to the order of the efficiency_strings. This order was not respected when I made my changes to remove the majority of the ~30K unnecessary strings, and I don't think it's feasible to maintain the order. 

I checked bin-by-bin, and most of the bins with the same label have the same content. One difference is that I actually added five histograms for Higgs/ZnnHbb:

HLT/Higgs/ZnnHbb/EffSummaryPaths_ZnnHbb_gen
HLT/Higgs/ZnnHbb/Eff_recPFMETEta_HLT_PFMET110_PFMHT110_IDTight
HLT/Higgs/ZnnHbb/Eff_genPFMETPhi_HLT_PFMET110_PFMHT110_IDTight
HLT/Higgs/ZnnHbb/Eff_genPFMETEta_HLT_PFMET110_PFMHT110_IDTight
HLT/Higgs/ZnnHbb/Eff_genPFMETMaxPt1_HLT_PFMET110_PFMHT110_IDTight

I see no reason why these histograms shouldn't exist (the 30K strings somehow didn't contain these combinations of words), so I think the difference is OK.

**Comment by dmitrijus** [comment]
@davidlange6 @fabozzi Can this get merged?

Without this, release validation is completely broken.
If not, I will make a PR disabling the module entirely.

**Comment by davidlange6** [comment]
i'm not a big fan of breaking users code - have you contacted them so that they know its happening?

**Comment by fabozzi** [comment]
@davidlange6 
currently, without any fix in the release, validation is broken and we cannot stay in this situation for another pre-release. 
If the fix from the developers is delayed, I see only two possibilities: 
- disable the modules
- deploy the patch that we are applying to make things work
https://github.com/cms-sw/cmssw/pull/21239
(it was decided not to deploy in release because a better fix was supposed to come soon)

Whatever option above is OK to me.

**Comment by davidlange6** [comment]
so " have you contacted them so that they know its happening? "

**Comment by DryRun** [comment]
Hi, I'm in contact with the Higgs trigger validators to check if this is OK. I'll post again when I have an answer.

**Comment by DryRun** [comment]
I'll also point out that it seems to me that this comparison is a bit flawed. The x-axis of these summary histograms is a list of efficiency histograms in the folder, so adding or removing a single histogram (e.g. if an analysis adds a trigger) will mix up the bins and break the comparison. It looks like some of the comparisons are flagged as OK because the bin contents are often 0 or 1, so shuffling the order of bins sometimes doesn't change the bin-by-bin contents (the bin labels will be different, but the comparison doesn't look at those, I guess?).

**Comment by DryRun** [comment]
OK, I have checked with the Higgs validators and trigger contacts. They have approved the changes, and are OK with the globalEfficiencies histograms being flagged for now. @davidlange6

**Comment by davidlange6** [comment]
Thanks!

**Comment by davidlange6** [comment]
merge

**Pull request merged**
