### PR TITLE
Fixes for RunInfo O2O and cleanup of PopCon interface

### PR DESCRIPTION
**Pull request by diguida**
The RunInfo O2O has been modified: 
- Make the tag population in synch with the `CondDBv2` tag policy. In https://github.com/diguida/cmssw/blob/fix_RunInfo_and_PopCon/CondCore/CondDB/src/IOVEditor.cc#L189-L201, as specified in the comment too, if the tag has synchronisation `ANY` or `VALIDATION`, IOV insertion in the past or overriding are allowed, while they are forbidden (an exception is thrown) for "production" tags. The RunInfo code is now protected so that it first tests the input run number against the last IOV of the target tag: if the new run number is smaller than or equal to the latest IOV in the target tag, the job exits, and no new IOVs are added irrespectively of the synchronisation;
- Use `CondCore` API as defined in `ConnectionPool` in order to authenticate `Oracle` access via roles, instead of the `CORAL` API in `RelationalAccess`;
- Improve queries by performing joins on PK-FK (query time improved by factor 2);
- Throw exceptions in case CORAL fails to execute a query;
- Improve logging messages;
- Improve code style;
- Review the configuration file to be fully complaint with the O2O online framework.

Removed a dead data member in PopCon.

Added a comment in `CondCore/CondDB/src/IOVEditor.cc` clarifying the tag update policy w.r.t. tag synchronisation.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
Few changes to make code comments more clear

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
