### PR TITLE
80 x add 2016 summer mc pileup scenario v3

### PR DESCRIPTION
**Pull request by jsalfeld**

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
@jsalfeld - please make a 81x pull request as well. thanks

**Comment by jsalfeld** [comment]
@davidlange6 ok done. #15754

**Comment by davidlange6** [comment]
now that I look at the changes - we really want to provide 3 scenarios? (eg, they are not already obsolete?) If so, please add some documentation of what they are. (V1,V2,V3 are not self-describing).
@jsalfeld 
thanks

**Comment by jsalfeld** [comment]
@davidlange6 
V3 is the one for this campaign.
V2,V1 are obsolete (the scenarios changed after better understanding of data-taking conditions for the rest of the year)

**Comment by mdhildreth** [comment]
It might be best to just delete V1 and V2, then?

**Comment by jsalfeld** [comment]
@davidlange6 @mdhildreth made new PR #15796. Improved naming of PU ScenarioV3, deleted obsolete ones. (automatic merging seems to have conflicts)

**Pull request closed without merging**
