### PR TITLE
Revert "Have embedded root files send close reports"

### PR DESCRIPTION
**Pull request by makortel**
Reverts cms-sw/cmssw#35074. ASAN pointed out problems with this PR, see https://github.com/cms-sw/cmssw/issues/34873#issuecomment-916136092 for more details.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
> ```
> ---> test TestCTPPSDirectProtonSimulation had ERRORS
> ```

The log does not add much.
```
Running script: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-08-2300/src/Validation/CTPPS/test/simu/run_multiple
status = 256

---> test TestCTPPSDirectProtonSimulation had ERRORS
``

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try again with a new IB

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
