### PR TITLE
HLT menu development for `12_4_X` (10/N): HLT V1.5 of 2022

### PR DESCRIPTION
**Pull request by missirol**
backport of #39924

#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This version of the `GRun` HLT menu corresponds to "HLT V1.5" for 2022 pp data-taking.

Additionally, the HIon L1T menu used in HLT-specific tests is updated to the candidate L1T menu for the HIon 2022 test run ([CMSLITDPG-1015](https://its.cern.ch/jira/browse/CMSLITDPG-1015)): [`L1Menu_CollisionsHeavyIons2022_v1_1_0`](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/021c669a6f736f6278ae4ebe7b91701119cd83a7/development/L1Menu_CollisionsHeavyIons2022_v1_1_0/L1Menu_CollisionsHeavyIons2022_v1_1_0.html) ([tag in `CondDB`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsHeavyIons2022_v1_1_0-d1_xml)).

Due to the update of the `HIon` menu, the `DIGIHI2018PPRECO` RelVal step is moved to the `Fake2` HLT menu (like other Run-2 wfs); this affects wfs `158.{0,1,2,3,5}`, whose DQM sequences already expect a "fake" HLT. These wfs were using the `HIon` HLT menu, which, after this PR, is not compatible anymore with the L1T menu in `auto:phase1_2018_realistic_hi`.

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2366](https://its.cern.ch/jira/browse/CMSHLT-2366): [BTV] disable DeepCSV triggers of GRun
  - [CMSHLT-2476](https://its.cern.ch/jira/browse/CMSHLT-2476): [TSG] seed of `HLT_EphemeralZeroBias` changed to `L1_ZeroBias_copy`
  - [CMSHLT-2478](https://its.cern.ch/jira/browse/CMSHLT-2478): [MUO] removed some HLT-muon modules from `suppressWarning` list
  - [CMSHLT-2491](https://its.cern.ch/jira/browse/CMSHLT-2491): [TSG] update PSs of `HLT_HT300_Beamspot` trigger
  - [CMSHLT-2495](https://its.cern.ch/jira/browse/CMSHLT-2495): [TSG] update PSs of Ephemeral triggers
  - [CMSHLT-2497](https://its.cern.ch/jira/browse/CMSHLT-2497): [TSG] added L1T seed to `HLT_EphemeralPhysics` (L1A Physics "masking" `L1_ZeroBias_copy`)
  - [CMSHLT-2499](https://its.cern.ch/jira/browse/CMSHLT-2499): [TSG] added `L1_SingleTau130er2p1` to L1T seeds using `L1_SingleTau120er2p1`
  - [CMSHLT-2501](https://its.cern.ch/jira/browse/CMSHLT-2501): [EXO] added L1Tau-seeded delayed-jet triggers
  - [CMSHLT-2514](https://its.cern.ch/jira/browse/CMSHLT-2514): [TSG] disable two displaced-dijet and two PNET triggers
  - [CMSHLT-2518](https://its.cern.ch/jira/browse/CMSHLT-2518): [HIG] update of 1 L1T seed and 2 PSs of MSSM-Hbb control triggers
  - [CMSHLT-2519](https://its.cern.ch/jira/browse/CMSHLT-2519): [TSG] disable 4 fatjet softdrop-mass triggers plus other PS changes
  - [CMSHLT-2520](https://its.cern.ch/jira/browse/CMSHLT-2520): [BTV] updated PSs of `BTagMu` triggers
  - [CMSHLT-2521](https://its.cern.ch/jira/browse/CMSHLT-2521): [HIN] update of HIon sequences for RawPrime repacking
  - [CMSHLT-2523](https://its.cern.ch/jira/browse/CMSHLT-2523): [HIN] removed outdated HIon triggers
  - [CMSHLT-2527](https://its.cern.ch/jira/browse/CMSHLT-2527): [EXO] updated L1T seed of `SingleLLPJet` triggers
  - [CMSHLT-2532](https://its.cern.ch/jira/browse/CMSHLT-2532): [HIN] update of Streams/PDs/EventContents for HIon 2022 test run
  - [CMSHLT-2534](https://its.cern.ch/jira/browse/CMSHLT-2534): [JME] doubled PS of `AlCa_*PFJet*` triggers
  - [CMSHLT-2535](https://its.cern.ch/jira/browse/CMSHLT-2535): [HIN] updated L1T seeds of HIUPC triggers
  - [CMSHLT-2537](https://its.cern.ch/jira/browse/CMSHLT-2537): [TSG] sync PSs of offline menu with V1.4.5 online menu
  - [CMSHLT-2539](https://its.cern.ch/jira/browse/CMSHLT-2539): [TSG] use common PF-scouting sequence in `MC_Run3_PFScoutingPixelTracking_v` Path

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39924

Development of HLT menus for 2022 data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

The `DIGIHI2018PPRECO` RelVal step is moved to the Fake2 HLT menu (like other Run-2 wfs); this affects wfs `158.{0,1,2,3,5}`, whose DQM sequences already expect a "fake" HLT. These wfs were using the `HIon` HLT menu, which, after this PR, is not compatible anymore with the L1T menu in `auto:phase1_2018_realistic_hi`. This now requires the signature of @cms-sw/pdmv-l2 and @cms-sw/upgrade-l2.

**Comment by missirol** [comment]
+hlt

**Comment by srimanob** [comment]
+Upgrade

Backport PR.

**Comment by missirol** [comment]
@cms-sw/pdmv-l2 , this backport is only missing your signature. Please have a loook.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
