### PR TITLE
Change PluginFactory to return unique_ptr

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR changes the `PluginFactory`'s `create()` and `tryToCreate` to return `std::unique_ptr<Plugin>` instead of a raw `Pointer *`. This change makes the ownership of the returned plugin clear (caller owns). 

The client code has been already migrated to constructs that work with either `unique_ptr` or raw pointer. After this PR is merged, I'll clean up all then-unnecessary calls to `unique_ptr` constructor.

#### PR validation:

Code compiles (after `git cms-checkdeps -a`).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test with #27118

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
