### PR TITLE
[JMENano] Fix GenJetIdx for AK4 jets matched to low pt genjets

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR fixes an issue with the `GenJetIdx` of AK4 reco jets for JMENano. Due to PR #41039, AK4 reco jets that are matched to AK4 Gen jets with `pt < 10 GeV` have `GenJetIdx` value set to `-1`. For JMENano, the AK4 Gen jet collection is rebuilt with a pt cut of `5 GeV` (at the clustering level) so this PR removes the Gen jet `pt > 10 GeV` requirement for the `GenJetIdx` of AK4 reco jets.

#### PR validation:
- passes the standard runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by nurfikri89** [comment]
Hi @simonepigazzini @vlimant, can you please trigger the test for this PR?

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
