### PR TITLE
[DQM] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
please abort

**Comment by smuzaffar** [comment]
@antoniovagnerini , `TestDQMOfflineConfigurationGotAll` tests is failing in IBs . https://github.com/cms-sw/cmssw/pull/46791 should fix that unit test. Running tests for this PR without https://github.com/cms-sw/cmssw/pull/46791 will still cause  `TestDQMOfflineConfigurationGotAll`  to fail

**Comment by antoniovagnerini** [comment]
yes this is why I aborted and was going to resubmit the tests in conjuction with https://github.com/cms-sw/cmssw/pull/46791

**Comment by antoniovagnerini** [comment]
please test with #46791

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
