### PR TITLE
Run3-gem66 Update the production cut files for run3 muon system

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the production cut files for run3 muon system. The file versions in this PR have not yet been uploaded to the DB. So it is safe to modify the files without creating new versions.

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Please add to the PR description that the file versions in this PR have not yet been uploaded to the DB, so it is safe to modify them without creating new versions (if that is true).

**Comment by bsunanda** [comment]
@cvuosalo Added in the description.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , please, clarify situation with cuts for protons. In this PR you removing cuts for proton from sub-regions. I am not sure if this is optimal.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch ProdCutsForProtons were not defined in many of the earlier production cut file for muon. Now I have added 10 mm for Muon region and 1mm for all the subregions

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
