### PR TITLE
Global Tag updates for 81x: introducing new L1 uGT stage-II menu and MC updates for Digi-Reco 

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v9) as [80X_mcRun2_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v9/80X_mcRun2_design_v6): 
  - updated ES ChannelStatus start 2016 : (2x32) sensors dead
  - updated ES pedestal/noise 137216 channels with (2x32) sensors out : ADC mean = 1300, RMS = 3.
  - updated Hcal channel quality for MC (copy from the last approved condition on Fev/2016)
  - updated Hcal QIE data post LS1 
  - added first L1T stage-2 uGT menu
  - updated SiPixel Dynamic inefficiency for 2016 (based on 2015 measurements)
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v8) as [80X_mcRun2cosmics_startup_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v8/80X_mcRun2cosmics_startup_peak_v4): 
  - updated ES ChannelStatus start 2016 : (2x32) sensors dead
  - updated ES pedestal/noise 137216 channels with (2x32) sensors out : ADC mean = 1300, RMS = 3.
  - updated Hcal channel quality for MC (copy from the last approved condition on Fev/2016)
  - updated Hcal QIE data post LS1 
  - added first L1T stage-2 uGT menu
  - updated HLT JEC to payloads with L2/L3 residuals to allow integrtation of new paths in menu
  - updated SiPixel Dynamic inefficiency for 2016 (based on 2015 measurements)
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v9) as [80X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v9/80X_mcRun2_asymptotic_v6): 
  - updated ES ChannelStatus start 2016 : (2x32) sensors dead
  - updated ES pedestal/noise 137216 channels with (2x32) sensors out : ADC mean = 1300, RMS = 3.
  - updated Hcal channel quality for MC (copy from the last approved condition on Fev/2016)
  - updated Hcal QIE data post LS1 
  - added first L1T stage-2 uGT menu
  - updated non-zero muon DT alignment uncertainties defined by the comparison of asymptotic and ideal MC geometries (quadratic sum of RMS and mean shifts on homogeneous sets of chambers).
  - updated non-zero muon CSC alignment uncertainties defined by the comparison of asymptotic and ideal MC geometries (quadratic sum of RMS and mean shifts on homogeneous sets of chambers).
  - updated Ecal laser transparency: as start 2016 + 15/fb prediction
  - updated Ecal noise: 2015 + 15/fb prediction
  - updated Ecal tuning of the thresholds of the zero-suppression (ZS tag), to safely run with a PU up to ~ 40-50.
  - updated Ecal tuning of the thresholds of the selective-readout (TPG tag), to safely run with a PU up to ~ 40-50.
  - updated SiStrip bad channels payload for 2016 MC campaigns. Computed using Run 260627. This considers optimistic scenario where the active channels have been defined using Fed Cabling payload.
  - updated SiPixel Dynamic inefficiency for 2016 (based on 2015 measurements)
- **RunII Startup scenario** : [80X_mcRun2_startup_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v8) as [80X_mcRun2_startup_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v9/80X_mcRun2_startup_v6): 
  - updated ES ChannelStatus start 2016 : (2x32) sensors dead
  - updated ES pedestal/noise 137216 channels with (2x32) sensors out : ADC mean = 1300, RMS = 3.
  - updated Hcal channel quality for MC (copy from the last approved condition on Fev/2016)
  - updated Hcal QIE data post LS1 
  - added first L1T stage-2 uGT menu
  - updated SiPixel Dynamic inefficiency for 2016 (based on 2015 measurements)
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v7) as [80X_mcRun2_HeavyIon_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v7/80X_mcRun2_HeavyIon_v5): 
  - updated Hcal QIEData mc tag to reflect situation in data (2016)
  - updated ES ChannelStatus start 2016 : (2x32) sensors dead
  - updated ES pedestal/noise 137216 channels with (2x32) sensors out : ADC mean = 1300, RMS = 3.
  - updated Hcal channel quality for MC (copy from the last approved condition on Fev/2016)
  - updated Hcal QIE data post LS1 
  - added first Heavy Ions L1T stage-2 uGT menu
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v9) as [80X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v9/80X_dataRun2_v8): 
  - updated AlCaReco trigger bit to allow new SiStripAfterAbortGap AlcaRecos in the matrix
  - updared CSC Xtalk payload to fix the incorrect values for ME-2/1/03.
  - introducing "all-uTCA" HBHE Electronics Map 
  - adding Stage2 uGT L1T menu
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v7) as [80X_dataRun2_HLTHI_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v7/80X_dataRun2_HLTHI_frozen_v6): 
  - introducing HI Stage-II L1T menu for Release validation
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v4) as [80X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v4/80X_dataRun2_HLT_relval_v3): 
  - introducing Stage-II L1T menu for Release validation
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v8) as [80X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v8/80X_dataRun2_HLT_frozen_v6): 
  - better name for O2O tag for Stage 2 L1T menu.
- **RunII Offline relval processing** : [80X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v4) as [80X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v4/80X_dataRun2_relval_v3): 
  - updated AlCaReco trigger bit to allow new SiStripAfterAbortGap AlcaRecos in the matrix
  - updared CSC Xtalk payload to fix the incorrect values for ME-2/1/03.
  - introducing "all-uTCA" HBHE Electronics Map 
  - adding Stage2 uGT L1T menu
## Upgrade
- **PhaseI design scenario** : [80X_upgrade2017_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v6) as [80X_upgrade2017_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v6/80X_upgrade2017_design_v4): 
  - updated Hcal QIE data post LS1 
  - added Pixel Dynamic inefficiency for phase-I

### CODE REVIEW

**Comment by mmusich** [comment]
hold 
mc workflows are expected to fail with:

----- Begin Fatal Exception 14-Mar-2016 13:06:30 CET-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
Unavailable Conditions of type HcalQIEData for cell (0x54000051) (ZDC+ EM 1,1)
----- End Fatal Exception -------------------------------------------------

will fix as soon as new tag is made available

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by mmusich** [comment]
Hi @davidlange6, the GTs as they are will fail for two different reasons:
   * as pointed out in https://github.com/cms-sw/cmssw/pull/13709#issuecomment-196308333 there is an issue with the new Hcal QIEData, we have the tag correcting for that: [message in AlCa HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2263/1/1/1/1/1.html)
   * we still miss a fix for the CSC tags update that causes the issue reported in [RelVal HN](https://hypernews.cern.ch/HyperNews/CMS/get/relval/4577/1/1/1/1/2/1/1.html) affecting the GT for MC Digi-Reco as well.

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
mmh, in a fresh IB it works for me:
```
cmsrel CMSSW_8_1_X_2016-03-15-1100
cd CMSSW_8_1_X_2016-03-15-1100/src/
git cms-merge-topic 13709
scramv1 b 
cmsenv
runTheMatrix.py -l limited
````
yields:
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Mar 16 10:46:28 2016-date Wed Mar 16 10:40:10 2016; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Mar 16 10:46:49 2016-date Wed Mar 16 10:40:14 2016; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Mar 16 10:46:47 2016-date Wed Mar 16 10:40:17 2016; exit: 0 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Mar 16 11:00:39 2016-date Wed Mar 16 10:40:20 2016; exit: 0 0 0 0 0
134.911_RunSinglePh2015D+RunSinglePh2015D+HLTDR2_25ns+RECODR2_25nsreHLT+HARVESTDR2_25nsreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Mar 16 11:08:58 2016-date Wed Mar 16 10:46:32 2016; exit: 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Mar 16 11:02:02 2016-date Wed Mar 16 10:46:55 2016; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Mar 16 10:56:44 2016-date Wed Mar 16 10:46:56 2016; exit: 0 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Mar 16 11:16:03 2016-date Wed Mar 16 10:56:47 2016; exit: 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Mar 16 11:14:10 2016-date Wed Mar 16 11:00:43 2016; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED  - time date Wed Mar 16 11:14:25 2016-date Wed Mar 16 11:02:08 2016; exit: 0 0 0 0 0 0 0
10 10 9 7 5 1 1 tests passed, 0 0 0 0 0 0 0 failed
```

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
got it. `25202` is not run in the shor matrix.

```
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/896e72a0ee77a49d967357cd143c91a7/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-03-14-1100/src/SimCalorimetry/EcalSimAlgos/src/ESElectronicsSimFast.cc:87: void ESElectronicsSimFast::analogToDigital(CLHEP::HepRandomEngine*, ESElectronicsSimFast::ESSamples&, ESDataFrame&, bool) const: Assertion `0 < adc' failed.
```
looks like we have another issue in the pre-shower conditions. 
@shervin86 @emanueledimarco @cmkuo

Incidentally, reverting the new ES pedestals with the GT:
`80X_mcRun2_asymptotic_Candidate_2016_03_16_12_24_32` ( [diff in the browser](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v8/80X_mcRun2_asymptotic_Candidate_2016_03_16_12_24_32) )
I don't observe issues.
Can you please have a look?
Thanks,

**Comment by davidlange6** [comment]
@musich - maybe you should add the failing workflow to your tests to see if it runs locally for you?

**Comment by cmkuo** [comment]
@mmusich 

can you please tell me how to reproduce the errors ?

**Comment by mmusich** [comment]
@davidlange6 indeed it fails also locally for me.

@cmkuo:
```
cmsrel CMSSW_8_1_X_2016-03-15-1100
cd CMSSW_8_1_X_2016-03-15-1100/src/
git cms-merge-topic 13709
scramv1 b 
cmsenv
runTheMatrix.py -l 25202.0
```
will give you the error

**Comment by mmusich** [comment]
@cmkuo thanks for the fix.
 The new ES pedestals tag locally runs fine. Let's give a further try.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@hengne @fabozzi I removed some relic dependency in `relval_steps.py` of the `run2_data` key which has the O2O tag for the L1 menu (hence not good for the HLT step in relvals). 
Can you please review and sign?

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi @mmusich 

The GT for 2017 also needs the new L1 menu (there are workflows with L1T):
```
https://cmssdt.cern.ch/lxr/source/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py?v=CMSSW_8_1_X_2016-03-18-2300#0023
```
so one needs:
```
autoCond['phase1_2017_design'] = ( autoCond['phase1_2017_design'],) + l1Menus['GRun']
```
Can you add this for 81X and also to the 80X PR?

**Comment by mmusich** [comment]
Hi @Martin-Grunewald. Will do.
M.

**Pull request merged**
