### PR TITLE
bsunanda:Run2-hcx104 Correct for missing depths

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Please take a look and approve

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by bsunanda** [comment]
@ianna Please one more time

**Pull request merged**
