### PR TITLE
Make available a custom function for uncollapsed HE depths at HLT

### PR DESCRIPTION
**Pull request by deguio**
this PR doesn't impact any central workflow.
a custom function to switch on and off the HCAL depth collapsing at HLT is made available.

- the current default configuration at HLT is `COLLAPSED`
- the `UNCOLLAPSED` configuration can be generated via `cmsDriver` adding the following customize:

```--customise HLTrigger/Configuration/customizeHLTforCMSSW.customiseForUncollapsed```

@mariadalfonso @silviodonato @abdoulline

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

not affecting central workflows, mke available a functionality for HLT

**Pull request merged**
