### PR TITLE
HLT Tau DQM from MiniAOD

### PR DESCRIPTION
**Pull request by slehti**
#### PR description:
Adding support for running HLT Tau DQM on MiniAOD (PAT) samples so that a larger set of tau discriminators is available for the reference object selection.

#### PR validation:
Checked that the reference objects are the same for RECO and MiniAOD input.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
@slehti there's several differences in the DQM plots in JetMET/METValidation and JetValidation that do not seem compatible with the description of the PR. Do you understand where those differences are coming from?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-10-2300+863b3b/53314/39500.0_CloseByPGun_CE_H_Coarse_Scint+2026D88+CE_H_Coarse_Scint_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal/JetMET_JetValidation_ak4PFJets.html

**Comment by makortel** [comment]
> there's several differences in the DQM plots in JetMET/METValidation and JetValidation that do not seem compatible with the description of the PR. Do you understand where those differences are coming from?

Unexpected differences in `JetMET/{Jet,MET}Validation` in phase2 workflows are seen in some other PRs as well, see issue https://github.com/cms-sw/cmssw/issues/39754.

**Comment by slehti** [comment]
The HLT Tau DQM should not affect JetMET/METValidation and JetValidation in any way. Changes if any should only be in the HLT Tau DQM plots.
I do not understand those differences, and the PR is not touching JetMET/METValidation or JetValidation code.

**Pull request closed without merging**
