### PR TITLE
Revised binning for L1T Tau DQM efficiency turn-ons (9_4_X backport)

### PR DESCRIPTION
**Pull request by davignon**
This is the backport to 94X of #21318.
Updated tauEfficiencyBins with new binning for L1T Tau DQM efficiency turn-ons.
This relates to https://its.cern.ch/jira/browse/CMSLITDPG-385
Please consider for merging.
Cheers,
Olivier

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
backport of #21318

**Comment by davignon** [comment]
I was told by @thomreis I can close this one.

**Pull request closed without merging**
