### PR TITLE
Update of BTagCalibrationReader and code move to CondTools/BTau

### PR DESCRIPTION
**Pull request by HeinerTholen**
The update of BTagCalibrationReader contains two new methods for users: `min_max_pt` and `eval_auto_bounds`. The interface and src files are still left in CondFormats/BTauObjects. The reason is that I found it a bit unnecessary to create a complete new library for just one class. Also, there would be a need for separate classes_def.xml and classes.h files, since we would like to have the BTagCalibrationReader accessible from python.

Furthermore, all files in RecoBTag/PerformanceDB that are connected to BTagCalibration (new format) are moved into CondTools/BTau, which is a new Package. It seems to me that everything that is left in RecoBTag/PerformanceDB belongs to the old b tag scale factor format, but I can't say for sure.

### CODE REVIEW

**Comment by HeinerTholen** [comment]
@cerminar, @cmsbuild, @franzoni, @ggovi, @mmusich, @davidlange6 
If you could please check this pull request, that would be very nice.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
sorry @HeinerTholen, for some reason even though the bot requested my attention, this message never reached my inbox.

**Comment by HeinerTholen** [comment]
@mmusich, I don't understand the issue the build bot has with git-cms-merge-topic. Is it something I have to fix?

**Comment by mmusich** [comment]
@HeinerTholen I don't think so, but to be extra sure, let me run the tests again.

**Comment by mmusich** [comment]
please test

**Comment by HeinerTholen** [comment]
@cerminar, @cmsbuild, @franzoni, @ggovi, @mmusich, @davidlange6,
if you could let me know if there's more work to do, that would be nice. =)

**Comment by mmusich** [comment]
+1
@ggovi please have a look. thanks

**Comment by ggovi** [comment]
@HeinerTholen 
sorry for the late action on this
You are drastically changing the shape of BTagCalibrationReader
I guess this class is not used for the persistency ( also based on the name )
But then I'm wondering if a CondTools package would be a more appropriate place for it.
Anyhow, since you are waiting since long time, I have no objection on the PR if the class is not used for the db storage. In this case, you can consider at some point to create a CondTools/Btag package.

**Comment by ggovi** [comment]
Sorry, I've just noticed what I suggest is actually indicated in the PR title. But I don't see changes in this direction? I might have missed something?

**Comment by HeinerTholen** [comment]
@ggovi 

I'm creating CondTools/BTau in accordance to CondFormats/BTau. Tools from RecoBTag/PerformanceDB are moved there, because the the latter package should ideally only contain reco code, not db code. The rest of that package can be cleaned later, I think, I'm just moving the important bits away from there.

From my first message above: "The interface and src files [of BTagCalibrationReader] are still left in CondFormats/BTauObjects. The reason is that I found it a bit unnecessary to create a complete new library for just one class. Also, there would be a need for separate classes_def.xml and classes.h files, since we would like to have the BTagCalibrationReader accessible from python."

**Comment by ggovi** [comment]
@HeinerTholen 
Ok thanks for the clarification.

**Comment by ggovi** [comment]
+1

**Comment by HeinerTholen** [comment]
Thanks a lot!

@cerminar, @franzoni, @davidlange6
If you could please check this pull request, that would be very nice.

**Comment by mmusich** [comment]
@smuzaffar there is a new package here: `CondTools/BTau` can you please assign it to the `db` category?

**Comment by davidlange6** [comment]
a package just for a 20 line plugin doesn’t seem optimal. What dependency suggests this is not appopriate for CondCore/BTauPlugins?

**Comment by HeinerTholen** [comment]
During my last PR it was discussed that I should open CondTools/BTau. I can also move this to CondCore/BTauPlugins, if everybody agrees.

@cerminar, @franzoni, @ggovi, @mmusich, @davidlange6, @ghellwig, @apfeiffer1, @imarches, @acaudron, @tocheng, @ferencek, @pvmulder,
Sorry for spamming all of you, but I would like to be sure that everybody is fine with moving the auxiliary b-tag code to CondCore/BTauPlugins.

**Comment by ggovi** [comment]
In general, the CondCore/[Subsystem]Plugins packages contain the declaration of the mapping Record=>CondFormat, more or less exclusively.
I guess there is no technical reason to prevent to use them also to define specific services ( like this Reader ), but it will be most likely an unprecedented exception.

**Comment by HeinerTholen** [comment]
So it means that CondTools/BTau would actually the best choice for the code in question?
(Actually I would like the reader to stay where it is, also because those 3 classes, BTagEntry, BTagCalibration and BTagCalibrationReader build on each other and form a unity, kind of...)

**Comment by davidlange6** [comment]
it was easy to find a CondCore package with a plugins directory hosting a number of plugins.. Maybe I got lucky..

**Comment by ggovi** [comment]
Well, plugins are actually foreseen to be there... Would a plugin be ok in this case?

Anyhow, as I said there is no real reason to prevent to have an interface folder and entries in src... If this is preferred with respect to the new package creation.

**Comment by davidlange6** [comment]
it is a plugin in this new package? I'm not sure I understand your question @ggovi

**Comment by ggovi** [comment]
I was just wondering if this class would fit in a plugin (in this case it will go in the CondCore/BTauPlugins/plugin folder )... 
But it does not matter much, as I said I would consider also ok to 
use src/ and interface/ for the full class, if this solution is preferred to the one requiring a new package.

**Comment by HeinerTholen** [comment]
Which class are we talking about?
 - BTagCalibrationDbCreator is a CMSSW plugin and afaik it must reside in a plugin folder (or not?).
 - The BTagEntry/Calibration(/Reader) classes are classes and part of the cond. format and must be put into interface and src folders in CondFormats/BTau (or not?).

**Comment by ggovi** [comment]
Ok, let me summarise. If we want to be aligned with the 'practice' adopted until now by the rest of the systems:

BTagCalibrationDbCreator  in CondTools/BTau/plugins
BTagCalibrationReader.h in CondTools/BTau/interface
BTagCalibrationReader.cc in CondTools/BTau/src

This requires a new package. If we want to avoid to introduce a new package, I guess we could ignore this practice, and go for a similar structure in CondCore/BTauPlugins.

**Comment by HeinerTholen** [comment]
@davidlange6 @ggovi
As I said before, I'd rather leave BTagCalibrationReader under CondFormats/BTau, but I'll move it as you wish. So which one is the prefered option?

**Comment by mmusich** [comment]
please test

**Comment by HeinerTholen** [comment]
I undertook some minor improvements to the code BTagCalibration[Reader] code and moved BTagCalibrationReader to CondTools/BTau. As BTagCalibrationReader needs to be available from python, classes_def.xml and others were added here as well.

If this is not the preferred solution in the end, then of course I'll move everything to CondCore/BTauPlugins. I just wanted to get things going, and hope that I shot for the right solution..

**Comment by HeinerTholen** [comment]
@cerminar, @franzoni, @ggovi, @mmusich, @davidlange6, @ghellwig, @apfeiffer1, @imarches, @acaudron, @tocheng, @ferencek, @pvmulder, @slava77 

Changes to this PR were pushed and we need your confirmation again.

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by HeinerTholen** [comment]
@davidlange6 @slava77
Would you please review this PR?

**Comment by HeinerTholen** [comment]
@davidlange6 @slava77 
If you could kindly review this PR.

**Comment by slava77** [comment]
@HeinerTholen I'm not a category manager for this package
@davidlange6 If there are still issues, please comment.

**Comment by HeinerTholen** [comment]
Dear all, do I need to give a presentation about this PR in the ORP meeting?

**Comment by mmusich** [comment]
@HeinerTholen we required this to be included in the next 81X release at the last ORP: [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/OfflineComputingPlanningMeeting20160531#Status_of_CMSSW_8_1_X)
We'll remind about it at the next meeting.

**Comment by HeinerTholen** [comment]
Ok, I saw the entry on the twiki. So I assume, I don't have to present anything but it will be handled in the next meeting.

**Comment by davidlange6** [comment]
+1
sorry for the delay!!

**Pull request merged**
