### PR TITLE
restore functionality of removeMCMatching in PAT coreTools.py

### PR DESCRIPTION
**Pull request by roger-wolf**
Due to the introduction of the section for boosted taus in a former PR this function was broken for cases where there are now boosted taus in the sequences. The functionality has been restored with this single commit and an additional printout is being made to inform the user of what is being done and why. This is a change of a high level AT configuration tool, which is transparent for the user and with no correlation to any other package.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by roger-wolf** [comment]
@slava77 
Sorry I spotted a typo in the last commit last minute. Did not realize that you are working from Californian time and therefore are still in business :-)... I've also used this PR as a tail catcher for another request on PAT stuff you made some time ago (*). 

(*)
https://github.com/cms-sw/cmssw/pull/14055#discussion_r59730460

**Comment by roger-wolf** [comment]
Hi, this is exactly what I have fixed above. See one but last line in the log: there was a stupid typo, that has now been fixed. Matrix tests that I did went fine.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #14639 38dd031f52cc01f10cc614d77665ad22a986fa65

Fix to remove MC matching in PAT for boosted taus. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-05-26-1100 show no significant differences, as expected. A comparison of expanded RECO configs for workflows 9.0_Higgs200ChargedTaus and 25202.0_TTbar_13 shows no differences against baseline CMSSW_8_1_X_2016-05-23-2300. The 25202.0 config includes Mini-AOD production. These checks show this PR does not alter RECO or Mini-AOD.

**Pull request merged**
