### PR TITLE
[12_0_X] Fix customisePixelLocalReconstruction() customize function

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/35722. Description of original PR
>  This PR adds explicit manipulation of `HLTSchedule` when the Paths whose customization was added in https://github.com/cms-sw/cmssw/pull/35566 are replaced in `ProcessFragment`. Fixes https://github.com/cms-sw/cmssw/issues/35624.

#### PR validation:

None here in 12_0_X, relying on tests of #35722.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
backport of #35722

**Comment by perrotta** [comment]
+1
- Succesfully merged in master, and tested in the CMSSW_12_1_X_2021-10-21-1100 IB

**Pull request merged**
