### PR TITLE
TkAl: making mille job submission via condor possible

### PR DESCRIPTION
**Pull request by adewit**
This adds the functionality to submit all parts of the MillePede alignment algorithm to condor (in preparation of LSF-CAF decommissioning). For now LSF submission is still the default, but condor submission is fully supported.
Note that the submission could be made more efficient, as at the moment now we submit one job per cluster - submitting multiple jobs per cluster requires some overhaul of the current workflow. I have some ideas but this will take a bit more time to get right, and so will follow later.

### CODE REVIEW

**Comment by pohsun** [comment]
+1
@adewit Thank you for the clarification.

**Comment by fabiocos** [comment]
@adewit this is not breaking anything in the release as far as I can see, but was it tested?

**Comment by adewit** [comment]
@fabiocos Yes, it was tested and has the expected behaviour.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
