### PR TITLE
Small corrections to the calo to uGT comparison plots

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Backport to #21350

### CODE REVIEW

**Comment by thomreis** [comment]
Hi @vukasinmilosevic this also contains the backport #20947 of #20951 by @ashtipliyski ?
I guess to avoid conflicts since #20947 is not merged yet.

**Comment by ashtipliyski** [comment]
Hi @thomreis,

#20947 has been deployed into production and #20951 has been merged into master so we thought that this would be the cleanest way of bringing the bug fixes in. Considering that Production DQM will eventually move to 10_0_X, I doubt that either this PR or #20947 will ever be merged into 9_2_x. 

Please let us know if you have specific suggestions for bringing these changes into production.

Thanks

**Comment by thomreis** [comment]
Hi @ashtipliyski 
yes you are right. Just let the DQM people know that they can in principle remove #20947 when they merge this one.

**Comment by thomreis** [comment]
backport of #21350

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @vukasinmilosevic 
Data taking with 92x has finished. This can be closed.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
