### PR TITLE
remove empty `BuildFile` in  `DQM/SiPixelPhase1Track`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Casually noticed that this file (`DQM/SiPixelPhase1Track/BuildFile.xml`) is empty, so I remove it.

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild please test
   * failures are unrelated

**Comment by emanueleusai** [comment]
+1

- unrelated changes in DQM plots

**Comment by perrotta** [comment]
+1

**Pull request merged**
