### PR TITLE
Phase2 Fast CPE Template Error Fix

### PR DESCRIPTION
**Pull request by AdrianoDee**
This PR proposes a trivial fix for the Fast CPE error calculations. As is now only `qBin==0` is taken into account and should not be like this. Additionally with https://github.com/cms-sw/cmssw/pull/44813 this ends up in an infinite loop (that is also how I spotted it). 

Being the original author I honestly don't remember why this was like this in the first place. One of the hypotheses is that the template for Phase 2 pixels was not available at the time of the CUDA port. But I haven't done all the proper archeology. 

Fixes for both for Alpaka and CUDA.

Will produce the pixel local reco validation plots and append them here.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
assign @cms-sw/trk-dpg-l2 
I would ask for DPG experts opinion on this.

**Comment by AdrianoDee** [comment]
type tracker

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Note: just a first round of tests.

**Comment by mmusich** [comment]
@emiglior FYI

**Comment by AdrianoDee** [comment]
please test

**Comment by fwyzard** [comment]
Thanks @AdrianoDee .
As usual, please make a backport to 14.0.x for the Phase 2 HLT studies :-)

**Comment by AdrianoDee** [comment]
Sure, done here https://github.com/cms-sw/cmssw/pull/44919

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
