### PR TITLE
Phase2-gex08 Rearrange the sequencing of the xml files for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange the sequencing of the xml files for dd4hep

#### PR validation:

Tested using the runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - this looks terribly familiar and identical to https://github.com/cms-sw/cmssw/pull/30963
How did it happen that the same rearrangement is needed again?

**Comment by kpedro88** [comment]
@ianna #30963 did not fix all of the common/muon variations

**Comment by bsunanda** [comment]
@Ianna @kpedro88 #30963 fixed O5 while this fixes O6, O7 as well as M6, M7. I did not touch M4, M5 because they were used in D49. But these changes do not affect DDD - only DD4HEP. So if you think it is OK I can fix D4, D5

**Comment by ianna** [comment]
> @ianna @kpedro88 #30963 fixed O5 while this fixes O6, O7 as well as M6, M7. I did not touch M4, M5 because they were used in D49. But these changes do not affect DDD - only DD4HEP. So if you think it is OK I can fix D4, D5

Thanks, @bsunanda - it would be good to fix all of them :-)

**Comment by kpedro88** [comment]
@bsunanda if it doesn't affect the DDD results, maybe it's okay to modify D49. I guess this may show up in future Phase 2 DDD vs DD4hep comparisons, though.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
