### PR TITLE
fixing bug for cut-based jet pu ID

### PR DESCRIPTION
**Pull request by jbrands**
This PR uses the new weight names from cms-data/RecoJets-JetProducers#6 to fix the bug for cut based pu ID. The names of offline and online pu ID are now the same. Nevertheless,this PR targets mainly the offline pu ID. The fix includes that cut-based variables have the same name as MVA variables as well as including the pull variable in the offline pu ID. The code was tested and gives reasonable values for all variables (online and offline) before running the MVA.

### CODE REVIEW

**Comment by slava77** [comment]
@jbrands 
please click edit on the upper right and change the PR subject/title to something more descriptive.
(same thing for the 76X PR)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12054	832c2c0
- bugfixes (mostly) in jet pu ID
- the same code as in 76X https://github.com/cms-sw/cmssw/pull/12053	832c2c0
- jenkins tests pass and comparisons with baseline show differences in expected places: jet PU ID DQM variables

**Comment by davidlange6** [comment]
+1

**Pull request merged**
