### PR TITLE
Run3-sim126 Try to adress complaints from static analyser for SimG4CMS/Calo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to avoid complaints from static analyser for SimG4CMS/Calo

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
Curiously enough, this causes differences in the efficiencies for Phase2 muons
I'll try to understand why, but not earlier than next week...

**Comment by thomreis** [comment]
I do not think that the Phase 2 L1T muons discrepancies have anything to do with this PR. They also show in other PRs, like e.g. #39193 .

**Comment by perrotta** [comment]
> I do not think that the Phase 2 L1T muons discrepancies have anything to do with this PR. They also show in other PRs, like e.g. #39193 .

@thomreis thank you for pointing it out.
It could be another one of the unwanted features added by the merging of #38442...
Attn. @cms-sw/l1-l2

**Comment by perrotta** [comment]
+1

**Pull request merged**
