### PR TITLE
Properly handle file open for Streamer based sources

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
If the ProductRegistry can be modified upon opening a new file, the framework must be notified of the new file before the registry is updated. The streamer based sources were not following that rule.

#### PR validation:

The code compiles and the old and new unit tests all pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by perrotta** [comment]
+1
- FOr reco: FedRawDataInputSource in EventFilter updated to comply with the new handling of file opening in RawInputSource
- Jenkins tests pass and show no differences

**Comment by mommsen** [comment]
The changes look fine to me. But @smorovic should have a look at it, too.

**Comment by smorovic** [comment]
The changes look fine.

New unit tests cover changes in the Streamer source code. I ran a few tests with the FedRawDataInputSource. With scripts included with the code it runs fine. There is one small difference: if source issued "newLumi" twice for same lumisection (which it avoids, so it would be a bug) it would result in IsStop being with the old RawInoutSource version (premature and silent end of Run). In the new version this will trigger assert (due to no cached event) which is a better behavior.

**Comment by Dr15Jones** [comment]
ping

**Comment by mommsen** [comment]
+1
Thanks for the ping. It fell off my radar. Remi

**Comment by silviodonato** [comment]
+1
@christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng 
please have a look

**Comment by silviodonato** [comment]
merge

**Pull request merged**
