### PR TITLE
Unsch RECO together mini aod (aka PAT) step - retry2

### PR DESCRIPTION
**Pull request by franzoni**
copy of #9915

++ data and full sim (noPU, PU, premix) => Unsch RECO together mini aod

. astSim not migrated to unscheduled
. full standard+PU tests are ok, the crashes (the 3 prod workflows) are known (dqmAk4PFL1FastL2L3ResidualCorrector) and being worked on by DQM 
=> now addressed by #9943 
. double url for DQM gui upload

++ the parent of #9915 has been used for 3 full sets of relvals submissions

https://hypernews.cern.ch/HyperNews/CMS/get/relval/3823.html (FileReadErrors)
https://hypernews.cern.ch/HyperNews/CMS/get/relval/3830.html (dqmAk4PFL1FastL2L3ResidualCorrector)
https://hypernews.cern.ch/HyperNews/CMS/get/relval/3832.html (RSS)

which completed with errors not ascribable to unscheduled.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
Snap, Cosmics! Fix may be simple, will do asap. G

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
hello  @davidlange6, @degano, @smuzaffar
would it be possible considering this PR for a forthcoming 74 release ?
Is there a showstopper ?
Thanks,
g

**Comment by franzoni** [comment]
hello @davidlange6, @degano, @smuzaffar
would it be possible considering this PR for a forthcoming 74 release ?
Is there a showstopper ?
Thanks,
g

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@franzoni - ciao - in what IB was this tested? I'm trying to track through all the possible changes, as this PR is creating a bunch of problems in the current IB
(and partly I see that the set of alcas changed, but seems unrelated to the actual errors).

**Comment by Dr15Jones** [comment]
@davidlange6 on the test results page generated by Jenkins

**Comment by franzoni** [comment]
Hello David,

my local tests were on CMSSW_7_4_X_2015-07-09-2300 .

The bot tested in this thread on top of CMSSW_7_4_X_2015-07-09-2300, the same.

Cheers, G.

**Comment by davidlange6** [comment]
need to revert this as no one has had time to understand the troubles it seems to cause in the IBs

**Pull request merged**
