### PR TITLE
Added consumes to DTConfigDBProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Required change to DTKeyedConfigCache to not get `cond::persistency::KeyList` itself but instead have the object passed to it.
- Changed DTConfigDBProducer and DTKeyedConfigDump to use ESGetTokens.

#### PR validation:

runTheMatrix.py tests using the ESProducer still run.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Additional issues found with `cond::persistency::KeyList` are described here: #28203 .

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This does NOT depend on #28223 so the `requires-external` label is incorrect.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The test failures are from #28223  not this pull request.

**Comment by Dr15Jones** [comment]
ping

**Comment by fabiocos** [comment]
@ggovi @rekovic could you please check this PR?

**Comment by Dr15Jones** [comment]
Please review this pull request. It is needed for waiting framework changes.

**Comment by Dr15Jones** [comment]
The only change with respect to the previous test run is I moved a comment to a different line.

**Comment by Dr15Jones** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by Dr15Jones** [comment]
please review  @rekovic, @benkrikler This pull request is needed for more changes that are waiting.

**Comment by fabiocos** [comment]
@rekovic @benkrikler this has been pending since quite sometime, please have a look, I will integrate it after pre11 is built

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
