### PR TITLE
Fix CMS deprecated warnings in L1Trigger/GlobalTriggerAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- convert to using thread-friendly modules
- use esConsumes

#### PR validation:

Code compiles in DEPRECATED release without warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Review by perrotta — COMMENTED** [review]
If @Dr15Jones and @cecilecaillol agree, I can remove these two lines and merge, without retriggering the tests and signatures

**Comment by cecilecaillol** [comment]
> If @Dr15Jones and @cecilecaillol agree, I can remove these two lines and merge, without retriggering the tests and signatures

Fine with me

**Comment by perrotta** [comment]
merge
(see https://github.com/cms-sw/cmssw/pull/38523#pullrequestreview-1021284949)

**Pull request merged**
