### PR TITLE
Fix mismatch between EB and EE recHits in Phase2 supercluster producer configs

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

Several Phase2 HLT modules using the `PFECALSuperClusterProducer` are taking as input the `EcalRecHitsEE` as barrelRecHits and `EcalRecHitsEB` as endcapRecHits. These are not used in the building of the moustache supercluster, which is the only supercluster algorithm used online at the moment, also for Phase2. Nevertheless, this is still a nasty bug and could cause problems in the future - they are in fact used for example for the DNN supercluster in [PFECALSuperClusterAlgo](https://github.com/cms-sw/cmssw/blob/631818abebaf8c4665619acbadc8ebd9e8a9d80e/RecoEcal/EgammaClusterAlgos/src/PFECALSuperClusterAlgo.cc#L142-L144).

I have not found offline modules with the same issue - I think they are all created by the fillDescription of the [PFECALSuperClusterProducer](https://github.com/cms-sw/cmssw/blob/631818abebaf8c4665619acbadc8ebd9e8a9d80e/RecoEcal/EgammaClusterProducers/src/PFECALSuperClusterProducer.cc#L383-L384), which is correct.

On the other hand, note that the modules `hltParticleFlowSuperClusterECALL1Seeded` and `hltParticleFlowSuperClusterECALUnseeded` in ConfDB present the same issue and should be fixed as well.

#### PR validation:

As explained above, I would not expect to see differences.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
type egamma, bug-fix

**Comment by mmusich** [comment]
@RSalvatico 

> On the other hand, note that the modules hltParticleFlowSuperClusterECALL1Seeded and hltParticleFlowSuperClusterECALUnseeded in ConfDB present the same issue and should be fixed as well.

Please open a CMSHLT JIRA ticket for this.

**Comment by RSalvatico** [comment]
> @RSalvatico
> 
> > On the other hand, note that the modules hltParticleFlowSuperClusterECALL1Seeded and hltParticleFlowSuperClusterECALUnseeded in ConfDB present the same issue and should be fixed as well.
> 
> Please open a CMSHLT JIRA ticket for this.

For the records:
https://its.cern.ch/jira/browse/CMSHLT-3329

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
