### PR TITLE
Extending tracking ntuples for phase2

### PR DESCRIPTION
**Pull request by ebrondol**
Main changes:
- Introducing a new HitType (Phase2OT)
- Adapting the code to get phase2 OT clusters
- Removing chargeFraction for phase2 because not supported

This PR has been tested in CMSSW_9_0_X_2017-02-06-1100 for Phase2 workflow - it should be compatible with Phase1. @makortel can you maybe confirm?

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Thanks @ebrondol!

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
