### PR TITLE
dumpSimGeometry_cfg.py bugfix

### PR DESCRIPTION
**Pull request by friccita**
In dumpSimGeometry_cfg.py, the _cfi.py file specified to be loaded for the PhaseIPixel geometry tag was incorrect. I have changed it to the correct file (Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_cfi.py).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
wrong release or rebase needed

**Comment by slava77** [comment]
-1
I see that the parent of only relevant commit points to CMSSW_7_5_X_2015-10-27-2300 (parent commit is the merge of https://github.com/cms-sw/cmssw/pull/12033).
So, this suggests a wrong release was used.
Remake in 80X (may be easier than just asking for a rebase).

**Comment by friccita** [comment]
Ok, I will remake this pull request in 80X. (When I do, will the change be backported to 7XX as well?)

**Comment by ianna** [comment]
@friccita - Please, try to resubmit the branch with an appropriate base (7_6_X, not 8_0_X) if you need it as a bug fix in 7xx.

**Pull request closed without merging**
