### PR TITLE
Phase2-hgx143 Make a standalone test for SimHits

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by kpedro88** [comment]
The differences and added log lines seem unrelated to this PR.

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
please test
(to get a clean result)

**Comment by kpedro88** [comment]
+1

**Pull request merged**
