### PR TITLE
HLT menu development for `14_1_X` (1/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46139

#### PR description:

Development of HLT menus for `CMSSW_14_1_X`
   * This is the PR for the 14_1_X branch which is the release cycle currently used for Run-3 HLT-menu development.
  
This update includes the integration of the following changes (6e09c53827778d50c8034ef8ab665d9893d8eb81):
- migration of the combined HLT table and related subtables to the CMSSW_14_1_0 confDB template;
- removal of now useless customization functions related to CMSSW_14_1_X developments;

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/46139 to the 2024 HIon production cycle (`CMSSW_14_1_X`)

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
+hlt

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
