### PR TITLE
Removed use of tbb::task_arena in EventSetup

### LINKED ISSUE #336: Clean up EventSetup tbb::task_arena
Not needed anymore that prefetching is enforced in EventSetup

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Now that all EventSetup data products are prefetched, there is no longer a need to isolate ES module calls in their own task_arena.

#### PR validation:

Code compiles and all framework unit tests pass.

resolves makortel/framework#336

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The previous unit tests failures were because the order in which EDAnalyzers were run in the test changed which caused the diff of the logs to be different. As the order of running modules (which have no data inter-dependencies) is not guaranteed by the framework, these tests were fragile. I changed them to explicitly require the modules to be run in the specific order.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

DD4Hep workflow again

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36507	a9d1392 
- code changes in the reco category are only in RecoMTD/DetLayers/test/mtd_cfg.py (it would be nice to leave a note in the PR description about the purpose of this change; currently it's a bit hidden in https://github.com/cms-sw/cmssw/pull/36507#issuecomment-995945556)
- jenkins tests pass and comparisons with the baseline show no relevant differences (a few workflows show repeated differences appearing in DIGI or earlier steps and appear in a few other PR tests)

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by srimanob** [comment]
please test with https://github.com/cms-sw/cmssw/pull/36549

**Comment by makortel** [comment]
+1

The comparisons show a difference in patMETs_slimmedMETsNoHF that is occurring also in other PR tests (#36552), so I believe it is unlikely caused by this PR (also it was not visible in earlier tests that had other issues).

**Comment by Dr15Jones** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
