### PR TITLE
Switch Voronoi subtraction from equalization based recovery of negative fluctuation to ghost-particle based clustering and energy resumming

### PR DESCRIPTION
**Pull request by yslai**
This patch addresses the Voronoi subtraction performance issues. Previously, the negative fluctuation are recovered by equalization. This pull request switches to a postive energy-only clustering, where the negative fluctuation are propagated through the clustering as ghost particles, and then resummed.

The expected performance difference is a deterioration of 0.5 GeV/c or 1% energy scale difference for 50 GeV jets in the 2.76 TeV PbPb system, due to the effect of ECAL zero suppression on the underlying event  - which is not handled in this implementation, as opposed to the previous equalization method.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@yslai: Please add to the description of this PR an explanation of its expected impact on monitored physics quantities. What differences will this PR create?

**Comment by yslai** [comment]
@cvuosalo Updated. A performance deterioration of 0.5 GeV/c or 1% energy scale difference for 50 GeV jets in the 2.76 TeV PbPb system was found previously, and was the effect of ECAL zero suppression on the underlying event. This causes a small nonlinearity that was corrected by the previous equalization method, but not this simpler method.

**Comment by mandrenguyen** [comment]
@cvuosalo
The "HF/Voronoi" method subtracts the UE contribution PF candidate by PF candidate.  The question is then what to do with particles with negative energy.  The previous 'equalization' approach shared energy amongst neighboring particles (Voronoi cells, technically) until there was no (or few?) negative energy cells left.  This approach turned out to be rather time consuming.  The jet reconstruction was approaching the timing of the tracking, which is clearly undesirable.  A simpler approach was suggested, which is to sum the negative energy of all cells and subtract it from the clustered jet energy.  The particles corresponding to zeroed cells are treated as ghosts, if I understood correctly.   As it turns out the change to the energy and angular resolution are slight.  We expect rather sizeable timing improvements.  @yslai please feel free to correct any errors in my statement.

**Comment by cvuosalo** [comment]
@yslai, @mandrenguyen:
Testing shows large differences in physics quantities for workflow 140.53_RunHI2011. From your descriptions, I would expect only small changes at the 1% level. You can see some of the changes in the Jenkins comparison [results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_5_X_2015-05-12-2300+9039/4637/validateJR/), and I include here plots from a test with wf 140.53 using 100 events and compared to baseline CMSSW_7_5_X_2015-05-10-2300. The plots shown are just a sample of the changes; there are dozens more changes large and small.

Please explain whether these large changes should be expected or whether there is a problem with the PR.

all_testpr9039vsorig_runhi2011wf140p53c_recopfjets_akvs4pfjets__rereco_obj_photonenergyfraction
all_testpr9039vsorig_runhi2011wf140p53c_log10recopfjets_akvs4pfjets__rereco_obj_energy

jetenergy
plot1
plot2
plot3
plot4
plot5

**Comment by slava77** [comment]
@cvuosalo please post numbers on the CPU/timing changes.

**Comment by cvuosalo** [comment]
Timing measurements were made with wf 140.53 using 100 events against baseline CMSSW_7_5_X_2015-05-10-2300. Overall, there appears to be about a 20% reduction in CPU time.

Memory & time for baseline
Max VSIZ 3762.24 on evt 38 ; max RSS 2902.85 on evt 96
Time av 56.95 s/evt   max 720.242 s on evt 33

Memory & time for PR
Max VSIZ 3455.26 on evt 85 ; max RSS 2875.64 on evt 96
Time av 45.6901 s/evt   max 524.32 s on evt 33

Baseline vs. PR comparison by module
        offlineBeamSpot          0.181961 ms/ev -> 0.224838 ms/ev
        siPixelClusters          101.746 ms/ev -> 116.497 ms/ev
        siStripZeroSuppression   28.0321 ms/ev -> 24.9452 ms/ev
        siStripClusters          82.2808 ms/ev -> 69.2376 ms/ev
        siStripMatchedRecHits    277.469 ms/ev -> 317.826 ms/ev
        clusterSummaryProducerNoSplitting        10.8968 ms/ev -> 9.52667 ms/ev
        siPixelClusterShapeCache         21.4904 ms/ev -> 12.9787 ms/ev
        csc2DRecHits     10.2939 ms/ev -> 16.5261 ms/ev
        cscSegments      0.735826 ms/ev -> 2.12942 ms/ev
        ecalDetIdToBeRecovered   1.60762 ms/ev -> 3.79822 ms/ev
        ecalRecHit       27.395 ms/ev -> 15.6307 ms/ev
        ecalPreshowerRecHit      6.24914 ms/ev -> 7.78174 ms/ev
        hbhereco         304.466 ms/ev -> 220.446 ms/ev
        hfreco   3.87611 ms/ev -> 4.92146 ms/ev
        horeco   3.04464 ms/ev -> 1.78651 ms/ev
        PixelLayerTriplets       0.752283 ms/ev -> 3.73935 ms/ev
        hiPixel3ProtoTracks      21.747 ms/ev -> 27.5749 ms/ev
        hiPrimTrackCandidates    1566.07 ms/ev -> 1659.43 ms/ev
        hiInitialStepSelector    5.13522 ms/ev -> 3.93348 ms/ev
        hiDetachedTripletStepPixelTracks         465.12 ms/ev -> 310.979 ms/ev
        hiDetachedTripletStepSeeds       137.765 ms/ev -> 36.9692 ms/ev
        hiDetachedTripletStepTrackCandidates     1087.73 ms/ev -> 837.64 ms/ev
        hiDetachedTripletStepTracks      271.9 ms/ev -> 401.386 ms/ev
        hiLowPtTripletStepTracks         795.86 ms/ev -> 850.813 ms/ev
        hiPixelPairTrackCandidates       596.215 ms/ev -> 452.899 ms/ev
        hiPixelPairGlobalPrimTracks      62.5621 ms/ev -> 47.8136 ms/ev
        hiPixelPairStepSelector          70.1741 ms/ev -> 0.370751 ms/ev
        ancientMuonSeed          0.644252 ms/ev -> 1.63513 ms/ev
        hiRegitMuInitialStepSelector     1.44754 ms/ev -> 1.2871 ms/ev
        hiRegitMuDetachedTripletStepClusters     0.239709 ms/ev -> 0.36626 ms/ev
        hiRegitMuDetachedTripletStepSeedLayers   1.96542 ms/ev -> 1.40175 ms/ev
        hiRegitMuLowPtTripletStepClusters        0.647847 ms/ev -> 0.760428 ms/ev
        hiRegitMuLowPtTripletStepSelector        0.751617 ms/ev -> 0.878842 ms/ev
        hiRegitMuMixedTripletStepClusters        0.644824 ms/ev -> 1.06915 ms/ev
        hiRegitMuPixelLessStepSeedLayers         41.7532 ms/ev -> 27.2896 ms/ev
        hiRegitMuPixelLessStepSeeds      17.7752 ms/ev -> 20.658 ms/ev
        hiRegitMuPixelLessStepTracks     2.60389 ms/ev -> 2.08247 ms/ev
        hiRegitMuTobTecStepClusters      4.32107 ms/ev -> 0.651082 ms/ev
        hiRegitMuTobTecStepSeedLayersTripl       12.9109 ms/ev -> 5.25382 ms/ev
        hiRegitMuTobTecStepSeedLayersPair        16.9389 ms/ev -> 7.42556 ms/ev
        hiRegitMuTobTecStepTrackCandidates       2.79702 ms/ev -> 1.44278 ms/ev
        hiRegitMuTobTecStepSelector      0.546966 ms/ev -> 1.01518 ms/ev
        hiGeneralTracks          449.838 ms/ev -> 400.192 ms/ev
        particleFlowClusterECAL          918.238 ms/ev -> 662.054 ms/ev
        particleFlowRecHitHF     13.9183 ms/ev -> 12.3242 ms/ev
        particleFlowClusterHF    68.7923 ms/ev -> 53.3463 ms/ev
        islandSuperClusters      233.107 ms/ev -> 251.023 ms/ev
        correctedIslandBarrelSuperClusters       2.31515 ms/ev -> 4.1001 ms/ev
        correctedIslandEndcapSuperClusters       4.55674 ms/ev -> 3.40518 ms/ev
        cleanedHybridSuperClusters       9.18399 ms/ev -> 8.19067 ms/ev
        uncleanedHybridSuperClusters     8.87158 ms/ev -> 14.9507 ms/ev
        hybridSuperClusters      0.749168 ms/ev -> 1.66812 ms/ev
        correctedHybridSuperClusters     1.31514 ms/ev -> 5.28911 ms/ev
        uncleanedOnlyCorrectedHybridSuperClusters        0.292728 ms/ev -> 1.37812 ms/ev
        multi5x5BasicClustersCleaned     18.4507 ms/ev -> 21.3177 ms/ev
        multi5x5SuperClustersUncleaned   2.96721 ms/ev -> 2.59171 ms/ev
        multi5x5SuperClusters    3.75544 ms/ev -> 2.69633 ms/ev
        multi5x5SuperClustersWithPreshower       835.086 ms/ev -> 677.639 ms/ev
        correctedMulti5x5SuperClustersWithPreshower      5.55229 ms/ev -> 2.65463 ms/ev
        uncleanedOnlyCorrectedMulti5x5SuperClustersWithPreshower         0.170123 ms/ev -> 0.152803 ms/ev
        preshowerClusterShape    4.35641 ms/ev -> 3.23667 ms/ev
        iterativeConePu5CaloJets         545.785 ms/ev -> 420.42 ms/ev
        akPu3CaloJets    57.2029 ms/ev -> 51.3735 ms/ev
        akPu4CaloJets    95.1914 ms/ev -> 66.529 ms/ev
        akPu5CaloJets    181.534 ms/ev -> 88.5472 ms/ev
        voronoiBackgroundCalo    8433.62 ms/ev -> 185.147 ms/ev
        akVs2CaloJets    12.112 ms/ev -> 5.58694 ms/ev
        akVs3CaloJets    7.31346 ms/ev -> 6.5464 ms/ev
        globalMuons      10.6369 ms/ev -> 16.1683 ms/ev
        calomuons        0.331481 ms/ev -> 0.906483 ms/ev
        muonEcalDetIds   1.18197 ms/ev -> 2.4977 ms/ev
        ecalDrivenElectronSeeds          443.337 ms/ev -> 567.213 ms/ev
        electronCkfTrackCandidates       367.768 ms/ev -> 296.528 ms/ev
        electronGsfTracks        701.29 ms/ev -> 631.737 ms/ev
        pfTrack          75.4879 ms/ev -> 33.41 ms/ev
        pfTrackElec      833.999 ms/ev -> 685.557 ms/ev
        ecalDrivenGsfElectronCores       43.6861 ms/ev -> 57.2784 ms/ev
        ecalDrivenGsfElectrons   168.956 ms/ev -> 266.527 ms/ev
        photonCore       1.64247 ms/ev -> 0.296234 ms/ev
        photons          181.951 ms/ev -> 126.199 ms/ev
        electronsWithPresel      1.118 ms/ev -> 4.30709 ms/ev
        mvaElectrons     0.473955 ms/ev -> 0.607487 ms/ev
        particleFlowEGamma       6757.57 ms/ev -> 8148.78 ms/ev
        gedGsfElectronCores      25.4477 ms/ev -> 51.6409 ms/ev
        gedGsfElectronsTmp       249.769 ms/ev -> 509.37 ms/ev
        gedPhotonCore    0.233037 ms/ev -> 0.270644 ms/ev
        particleFlowTmp          1031.64 ms/ev -> 1149.79 ms/ev
        voronoiBackgroundPF      4712.96 ms/ev -> 322.564 ms/ev
        hiCentrality     10.5498 ms/ev -> 8.74387 ms/ev
        hiEvtPlane       3.0233 ms/ev -> 5.1797 ms/ev
        hcalnoise        15.7338 ms/ev -> 19.4595 ms/ev
        ak5CastorJets    0.666107 ms/ev -> 0.273049 ms/ev
         Total in detailed printout:     33620.5 ms/ev -> 21388.7 ms/ev          delta: -12231.8
 Total times: 53658.1 ms/ev -> 41783.5 ms/ev     delta: -11874.6

**Comment by yslai** [comment]
@cvuosalo Since the RelVal sample has virtually no hard processes, this behavior is expected. This is the pT of the "eq" = equalization vs. "neg" = negative recovery using the 140.53, and you can see mostly low pT UE fluctuation with weak jet contribution.

relval-pt

I am trying to identify CERN user-accessible triggered RAW to perform a better check.

**Comment by slava77** [comment]
would a check with L2DoubleMu3Skim be more meaningful?
E.g. file
/store/results/hin/StoreResults/HIDiMuon/USER/L2DoubleMu3Skim_v10_38dff9fa051006d6e895e3c1df676d76-v1/40000/001FA005-07D0-E411-A6C2-0026B95A4D42.root


On 5/19/15 5:19 AM, yslai wrote:
> @cvuosalo <https://github.com/cvuosalo> Since the RelVal sample has
> virtually no hard processes, this behavior is expected. This is the pT
> of the "eq" = equalization vs. "neg" = negative recovery using the
> 140.53, and you can see mostly low pT UE fluctuation with weak jet
> contribution.
> 
> relval-pt
> <https://cloud.githubusercontent.com/assets/1032767/7700738/118ac674-fe21-11e4-827a-1f2c3f73b0c4.png>
> 
> I am trying to identify CERN user-accessible triggered RAW to perform a
> better check.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9039#issuecomment-103428212>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by mandrenguyen** [comment]
better would be, e.g.,
/store/hidata/HIRun2011/HIHighPt/RAW/v1/000/181/688/02ACCF7A-380F-E111-B93E-BCAEC518FF54.root

**Comment by yslai** [comment]
This plot is made with /store/hidata/HIRun2011/HIHighPt/RAW/v1/000/181/777/069253FF-EA0F-E111-8F9A-003048F024FE.root and a tightened Delta R < 0.2 matching to reduce the jets from combinatorical UE:

neg-eq-ratio

The subtraction or accounting for the negative particles appears to be working properly, but the ability of the UE to produce jets is noticeably different.

**Comment by cvuosalo** [comment]
@ yslai: Is the conclusion now that this PR is performing correctly and that all the changes observed are acceptable and appropriate?

**Comment by yslai** [comment]
@cvuosalo Yes, the performance is as intended, and acceptable.

**Comment by cvuosalo** [comment]
+1

For #9039 f5bf76334e32fca79b01e57c9e08e7e06786cd48

For Heavy Ions, changing Voronoi subtraction related to negative fluctuations.

The code changes are satisfactory, as are Jenkins results. Additional tests showed significant differences, as seen above, but, these differences are the intended results of this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
