### PR TITLE
Run3-hcx354X Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future (backport of #43200)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future (backport of #43200)

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43200

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
@bsunanda with your latest commit you inhibited a unit test that did not succeed: aren't you hiding possible problems, as such?
If the new output of that test is the one that must be expected, wouldn't it be preferable to modify also the reference txt file, so that the test can succeed, instead of removing the check?

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@perrotta Please sign the db part to allow the back porting

**Comment by perrotta** [comment]
+db
- verbatim backport of #43200 and #43220

**Comment by rappoccio** [comment]
+1

**Pull request merged**
