### PR TITLE
CorrectedJetProducer: change into a global::EDProducer (76x)

### PR DESCRIPTION
**Pull request by fwyzard**
change all specialisations of `CorrectedJetProducer` into
`global::EDProducer` modules:
- `CorrectedCaloJetProducer`
- `CorrectedPFJetProducer`
- `CorrectedJPTJetProducer`
- `CorrectedTrackJetProducer`
- `CorrectedGenJetProducer`

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #10964

**Comment by fwyzard** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
