### PR TITLE
addition to Join Opt Meeting 2017.10.20 action item : rollback HLTDQM

### PR DESCRIPTION
**Pull request by davidlange6**
Arrange changes in #20980 so that the extra hlt histograms can be enabled also in workflows not running the "standard dqm"

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
hi @mtosi - this broke one workflow

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_0_X_2017-11-09-2300/pyRelValMatrixLogs/run/136.7802_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017.log

could you have a look?

**Comment by Dr15Jones** [comment]
I'm pretty sure this pull request broke the IB RelVal workflow 136.7802. See
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_10_0_X_2017-11-09-2300/pyRelValMatrixLogs/run/136.7802_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017.log

The problem boiled down to
```
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
egmGsfElectronIDsForDQM after VBFSUSYmonitoring [path dqmoffline_step],
...{all the other modules on path dqmoffline_step}...
 SinglePhoton300_monitoring after B2GegHLTDQMOfflineTnPSource [path dqmoffline_step],
 B2GegHLTDQMOfflineTnPSource consumes egmGsfElectronIDsForDQM
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```

The file containing B2GegHLTDQMOfflineTnPSource was modified by this pull request.

**Comment by davidlange6** [comment]
Yes - I reported it above to @mtosi

**Comment by makortel** [comment]
I think we should (in addition) move DQM modules from EndPath to Path as much as possible (also for many other reasons than creating so easily unrunnable schedule).

**Comment by Dr15Jones** [comment]
@makortel I've been thinking about adding another path type such as `ParallelPath` (or `AsyncPath`) which works like an `EndPath` (i.e. filtering is ignored) but all modules are started simultaneously. This would help the framework schedule efficiently but still allow people to group modules they want to run together in a job.

**Comment by davidlange6** [comment]
Yes, I agree - the dqm seems not to support this philosophy unfortunately...

**Comment by dmitrijus** [comment]
> @makortel I've been thinking about adding another path type such as ParallelPath (or AsyncPath) which works like an EndPath (i.e. filtering is ignored) but all modules are started simultaneously. This would help the framework schedule efficiently but still allow people to group modules they want to run together in a job.

Yes, YES!

@Dr15Jones Would it be possible to have a chat with you, let's say, tomorrow, skype/vidyo/real life?

> Yes, I agree - the dqm seems not to support this philosophy unfortunately...
 
I personally support that fully.

**Pull request merged**
