### PR TITLE
Modernized MuonTransientTrackingRecHitBuilderESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

-Added consumes and ESGetToken
-Added fillDescriptions
-Consolidated header and source to single file
-Removed SealModule.cc

#### PR validation:

The code compiles.
The changes are technical and should not changes any results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
