### PR TITLE
[Do not merge] Testing cms-bot deprecated warnings change

### PR DESCRIPTION
**Pull request by smuzaffar**
do not merge/sign this PR, it is just to test https://github.com/cms-sw/cms-bot/pull/1660

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondTools/L1Trigger

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/36021

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
-alca
 * PR was just a test

**Pull request closed without merging**
