### PR TITLE
[GCC13] Add include of cstdint in more places

### PR DESCRIPTION
**Pull request by iarspider**
Added missing cstdint includes to fix the GCC build errors about

error: 'uint32_t' does not name a type

This is a technical update

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
ping

this is just a technical PR to fix missing include for GCC 13 builds

**Comment by civanch** [comment]
+1

**Comment by francescobrivio** [comment]
+1

 - technical
 - all tests ok

**Comment by iarspider** [comment]
@cms-sw/reconstruction-l2 gentle ping

**Comment by perrotta** [comment]
+1

**Pull request merged**
