### PR TITLE
Remove PoolDBESSource from cfi file

### PR DESCRIPTION
**Pull request by tomcornelis**
Removing the PoolDBESSource from the QGTagger_cfi file, will move this to GT

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by UAEDF-tomc** [comment]
Ok, so we probably have to first get the needed Rcd into the GT, before moving on with this pull request

**Comment by slava77** [comment]
Please post a note in this PR thread once the payload makes it to the GT.

**Comment by slava77** [comment]
ping
@deguio @mmusich please clarify if the global tag creation for this PR is in progress

**Comment by slava77** [comment]
@deguio Sorry, I didn't pick the right completion, the message was to Salvatore.

**Comment by mmusich** [comment]
@slava77 thanks for pinging. We have been contacted by Tom about this, but we were not aware that there was a PR open. It's not straightforward to create the GTs containing the desired tag because of a buggy feature in the GTC that needs to be fixed first. We'll come back to you once this is ready.

**Comment by mmusich** [comment]
@UAEDF-tomc we are going to build the GT, can you please clarify which scenarios we should take into account? run2, run1, data, mc, express, prompt, hlt ?

**Comment by UAEDF-tomc** [comment]
@mmusich 
The four scenarios are:
AK4PFchs (recommended, default)
AK4PF
AK4PFchs_antib (slightly different training on request of analysis groups who use it in combination with a b-tagger)
AK4PF_antib

Those are all optimised for run2, 13TeV pp collisions with the standard PU20bx25 scenario, though still based on CSA14 samples. In the near future we will retrain on the RunIISpring15DR74X binned QCD samples. Those samples are in production now (so expect another update in a few weeks).

The same records are used for mc/data.

As you can see from above, it is also used in DQM, so I guess they should be included in express.

**Comment by mmusich** [comment]
@UAEDF-tomc from the crashes above it looks like you are consuming these tags/labels in run1 data and mc relvals workflows. I'll submit for those too.

**Comment by diguida** [comment]
@UAEDF-tomc @slava77 we have just deployed the new Global Tag Manager, as presented by Audrius at the AlCaDB meeting. We have included your tags in the Global Tag Queues. As the name says, they are Global Tags, but are supposed to change in time.
If you want, you can try to rerun locally one of the wf in the matrix (e.g. 25.0) by using the following customisation:

````
runTheMatrix.py -l 25.0 --command='--conditions 75X_mcRun1_realistic_Queue'
````

Of course, the queue should be chosen according to the scenario you want to test. You can see the queues maintained by AlCa coordinators [here](https://cms-conddb.cern.ch/browser/#search/Prod/Queue) and inspect the already quoted queue [75X_mcRun1_realistic_Queue](https://cms-conddb-int.cern.ch/browser/#list/Prod/gts/75X_mcRun1_realistic_Queue) as well as [comparing with the baseline in autoCond](https://cms-conddb-int.cern.ch/browser/#diff/Prod/gts/75X_mcRun1_realistic_Queue/MCRUN1_75_V2).

@mmusich is currently running the `25.0 wf` to check that everything is ok.

**Comment by diguida** [comment]
The tests made by @mmusich are ok. We are including the record and the labels in the GT targeting this pre-release.

**Comment by slava77** [comment]
-1
superseded by #9679

**Comment by mmusich** [comment]
@slava77 @davidlange6 should this be backported to 7.4.X too? We need to know to plan next Prompt/Express GTs

**Comment by slava77** [comment]
Hi Marco
I think it can be backported.
It requires a corresponding set of global tags in 74X with this QGL payload (data and MC).
The reasons to backport, as far as I understand, are driven by GT maintenance issues and access to the other database if any of it is to be run at P5.

**Pull request closed without merging**
