### PR TITLE
Removing work in progress

### PR DESCRIPTION
**Pull request by ebrondol**
As requested and discussed in #17594.

@kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
@ebrondol 
please clarify if this changes anything other than that printout?

**Comment by ebrondol** [comment]
@slava77 yes, printout and cleaning up.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17652		5ca39ef
- removed unused  (and partly broken) code in RecoTracker/TkDetLayers/src/GeometricSearchTrackerBuilder.cc ; this removes a caught exception at the start of the job in upgrade workflows
- jenkins tests pass 
    - comparisons with baseline show no differences
    - (as an example) wf 10021.0  step3 log file shows no exception anymore, compared to the baseline which has
```
in filling An exception of category 'InvalidReference' occurred.
Exception Message:
Trie::insert called with a key already in collection;
key value: ^A

304091140 1
```

**Comment by davidlange6** [comment]
+1
thanks!

**Pull request merged**
