### PR TITLE
Switch off the signal scaling for the HGC CEH_Sci sector

### PR DESCRIPTION
**Pull request by deguio**
this PR contains two changes:

- switches off the flags that take care of scaling the signal in the CEH_Sci sector according to the tile and the sipm areas. while this will be eventually turned on again, at the moment there isn't yet a mechanism that re-applies the same factors at recHit level to ensure a calibrated response. Therefore prefer to keep this scaling off until such a mechanism is available.

- adds a protection to the CloseByParticleGun to avoid un-physical cases

@cseez @rovere @apsallid @pfs @franzoni

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade
changes isolated to 2026 workflows, as expected
HGC HEF and HEB hit distributions are affected:
HGC HEF hits
HGC HEB hits

**Comment by fabiocos** [comment]
@qliphy @agrohsje @alberto-sanchez please check, the generator part of this PR is a simple protection, I will integrate it after pre11 is built

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
