### PR TITLE
add a specific duplicateMerge algorithm

### PR DESCRIPTION
**Pull request by VinInn**
duplicate-Merged tracks were inheriting the algorithm of the innermost piece.
This was causing confusion at many levels (besides the difficulties in validating and analyzing these tracks)

Here we assign them their own algo flag.

purely technical change.  Track migration form previous algo to the new one expected.
see https://innocent.web.cern.ch/innocent/RelVal/pu15_80_dma/
If physics change, there is a bug downstream, most probably in code other than tracker.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@makortel, TMV will need an update

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Do you want to pick MTV update here or shall I do a separate PR?

Btw, shouldn't this
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/DataFormats/TrackReco/src/TrackBase.cc#L12
be changed too?

**Comment by VinInn** [comment]
@makortel , yes forgot L12... wil fix here
I think MTV update better in a separate PR... (hope TrackBase.cc#L12 is last place rs is quoted...)
I am afraid more places that select 4<algo<12 or similar....
in any case your new phaseI algo may be affected by this type of code...

**Comment by makortel** [comment]
There shouldn't be any of relative comparisons of algos left after #8315 (unless something has creeped in).

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I'm (again) confused by the comparison. Alternative-comparisons show differences in histograms where relmon gives green (so relmon has some threshold for marking histograms different?). But even alternative-comparisons is inconsistent with itself: from differences in certain (MTV) histograms I'd except differences in other (MTV) histograms, but I don't see them (so alternative-comparisons has also some threshold?). These make it a bit difficult in certain occasions to judge if the changes are as expected, and also difficult to trust that histograms flagged as "no changes" would actually be unchanged. &lt;/rant&gt;

Anyway, there is pile of changes in e.g. electrons and taus, and also increase in "PackedCandidates/lostTracks". Apparently we need further migration. In fact, e.g. `git grep ::initialStep` reveals a bunch of files (many inside PF) that are not changed in this PR that could, naively thinking, lead to changes downstream.

**Comment by VinInn** [comment]
@bachtis, @arizzi
This is a mess, I wonder how the upgrade has been managed....
we cannot go around and grep for all possible way people decide is good for them to check "iteration"
Also because the definition of the iteration may change, we are not bound to be backward compatible with whatever we decide to call initialStep: if they want to make sure the track has pixel hits or a given distance to the BS please verify that non the iteration
PF SHALL fix the use of Track iterations before the relase of 8_0_0

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
On 11/27/15 12:05 AM, Matti Kortelainen wrote:
> I'm (again) confused by the comparison. Alternative-comparisons show
> differences in histograms where relmon gives green (so relmon has some
> threshold for marking histograms different?). But even
> alternative-comparisons is inconsistent with itself: from differences in
> certain (MTV) histograms I'd except differences in other (MTV)
> histograms, but I don't see them (so alternative-comparisons has also
> some threshold?). These make it a bit difficult in certain occasions to
> judge if the changes are as expected, and also difficult to trust that
> histograms flagged as "no changes" would actually be unchanged. </rant>


Yes, there are thresholds for both relmon and alternative-comparisons
based on the number of differences found in validateJR.

Without thresholds outputs will take too long to generate and will
take a noticeable fraction of GB.

You can rerun either relmon or alternative-comparisons locally (DQM
files are available)

**Comment by VinInn** [comment]
Still differences in PF...

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
Definetively better!
I think this is ready

**Comment by slava77** [comment]
@VinInn 
What's the reason for changes in outputs? are they all unavoidable?

**Comment by slava77** [comment]
eg. 25202 in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-27-1100+12577/11563/validateJR/all_OldVSNew_TTbarPUwf25202p0/

**Comment by VinInn** [comment]
I verified several time if anywhere else algo is explicitely used. One possibility for those differences is that a track with algo not-pixel (algo NOT oriAlgo) now is duplicateMerge and is threated differently.   Any logic based on explicit algo is intrinsically weak. They have to veirify track quality of some sort...

**Comment by slava77** [comment]
``` git grep "case[^$]*initialStep" ```
suggests the following are missing:
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/RecoParticleFlow/Benchmark/src/PFJetBenchmark.cc
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/RecoParticleFlow/PFProducer/src/PFEGammaFilters.cc#L367
    - this seems to be doing something active
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/RecoParticleFlow/Configuration/test/PFChargedHadronAnalyzer.cc#L232
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/PhysicsTools/UtilAlgos/interface/AdHocNTupler.h#L1000
    - unclear if update is needed
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/RecoParticleFlow/PFProducer/src/PFElectronAlgo.cc#L2677
    - needed

More places of interest could be
Alignment/CommonAlignmentProducer/src/AlignmentTrackSelector.cc 
``` if (track->algo()==(trkSteps_[i])) { ```

Alignment/HIPAlignmentAlgorithm/src/LhcTrackAnalyzer.cc
relies on local remapping of algos 

maybes
Calibration/TkAlCaRecoProducers/python/AlcaBeamSpotProducer_cfi.py
DQM/BeamMonitor/python/BeamMonitor_MC_cff.py
RecoVertex/BeamSpotProducer/python/d0_phi_analyzer_cff.py
these will start loosing good tracks from inputs; unclear if it matters

probably not very important (there are plans for this to be removed)
RecoMET/METProducers/python/TCMET_cfi.py
RecoMET/METProducers/python/MuonTCMETValueMapProducer_cff.py

**Comment by slava77** [comment]
from the comparisons, it looks like most (all?) changes are coming from PF charged hadrons and may in fact be expected: sometimes higher iteration tracks end up in the  duplicateMerge algo, which triggers different selections to the track itself and may affect its assignment as a charged hadron.

@bachtis @schoef  do you have a skim of events with large or suspicious  PF MET?

**Comment by VinInn** [comment]
I think Alignment should be notified, this track are far from perfect (Chi2 is usually higher)
do not understand how I missed more in RecoParticleFlow: I grep all possible iteration name and .algo() ...

**Comment by VinInn** [comment]
@makortel : I hope you are taking note for PhaseI !

**Comment by VinInn** [comment]
PF is full of copy/paste code. IT SHOULD BE factorize out!
@bachtis , @arizzi, hope it will be done in 8_0_0.
Forget trk-POG to take care of this mess for PhaseI

**Comment by VinInn** [comment]
in anycase many of the above are missing
```
  case TrackBase::jetCoreRegionalStep:
  case TrackBase::muonSeededStepInOut:
  case TrackBase::muonSeededStepOutIn:
```

and I WILL NOT add them
@bachtis , @arizzi
please review your code

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@VinInn Noted, although with Phase1 we have slightly (but only slightly) different situation, because the behaviour in PF (and others) got changed already by #5807 (something I learned only last week and wish would have realized earlier...), and thus "the current behaviour" in PF for Phase1 is probably already not what we want.

**Comment by makortel** [comment]
Regarding my earlier comment https://github.com/cms-sw/cmssw/pull/12577#issuecomment-159923954, I stand corrected. There are still less/greater than comparisons of the algo enumerators (e.g. here
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc#L1409
) that I did not fix in #8315 (maybe I missed them, maybe I had a reason, can't remember).

Before making use of the #12458-introduced Phase1 enumerators (that's how I encountered the case above), maybe it would be best to make a PR  replacing the remaining less/greater than comparisons with explicit lists of enumerators (I won't create a PR before this one gets merged to avoid conflicts)? Or are there better suggestions?

**Comment by VinInn** [comment]
@makortel , and all
I think we should meet with PF and find out a way to factorize out all those algo based selections
and eventually substitute them with a more physics-based quality criteria
We cannot continue to edit the very same codelet in a gazzillion+1 files  
(phaseII integration is foreseen in the very same timescale...)

**Comment by makortel** [comment]
@VinInn, agreed, that would indeed help (so I will not start yet https://github.com/cms-sw/cmssw/pull/12577#issuecomment-161252469)

**Comment by VinInn** [comment]
admittingly this time regressions are absent...

**Comment by slava77** [comment]
No regressions are much better and easier.
Also, good to know that they have been apparently triggered by missing fixes.

**Comment by slava77** [comment]
well, it's a "less changes", actually. Not "none at all"

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-01-2300+12577/11630/validateJR/all_OldVSNew_RunMinBias2011Awf1000p0/

there are many more in the DQM plots including MTV plots for /general tracks
e.g. 25202
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-01-2300+12577/11630/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/Tracking_TrackFromPV_generalFromPV_trackingParticleRecoAsssociationSignal.html

the less selective /general MTV plots are cleaner
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-01-2300+12577/11630/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/Tracking_Track_general_trackingParticleRecoAsssociation.html

while the generalProperties plots are unchanged as seen from fwlite plots as well
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-12-01-2300+12577/11630/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/Tracking_TrackParameters_generalTracks_GeneralProperties.html

I was expecting that the generalTracks validation would be unchanged

**Comment by VinInn** [comment]
FromPV... @makortel any idea/comment?

**Comment by makortel** [comment]
The FromPV ones (@slava77's second link) are all but one the `_Mean` or `_Sigma` that are produced by fits in DQMGenericClient (that to my understanding can be caused by ~any difference in earlier fits). The one exception is `h_algo`, where differences are expected. The situation is actually the same in the full generalTracks (third link).

**Comment by slava77** [comment]
On 12/2/15 12:10 PM, Matti Kortelainen wrote:
> The FromPV ones (@slava77 <https://github.com/slava77>'s second link)
> are all but one the |_Mean| or |_Sigma| that are produced by fits in
> DQMGenericClient (that to my understanding can be caused by ~any
> difference in earlier fits). The one exception is |h_algo|, where
> differences are expected. The situation is actually the same in the full
> generalTracks (third link).
> 

Are the tracks filled somehow in a different order?
This would explain differences in fits and numerical precision level
changes in the histograms.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12577	259fd1a
- changes in the code are in line with the description. Since the changes introduce a new high quality type iteration to which a fraction of tracks migrate, there can still be observable impact for the code relying on specific list of iterations at analysis level or similar.
- jenkins tests pass
    - in fwlite comparisons, of all workflows, only in one (1000.0) there is one charged hadron (13342 -> 13343) extra. A small change can be expected due to reassignment sometimes of a track from pixelless or tobtec after a merge to become a duplicateMerge: this will trigger different selection logic.
    - in DQM, workflows without changes in fwlite show a large number of discrepancies, which can be categorized and explained as follows
        - algo or algo-driven plot change
        - fits (plot post-processing) to track or vertex parameter plots have differences at numerical precision level. This can happen for Minuit due to changes in fit results of previously fit plots with actual differences and some memory of the past fit state.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
