### PR TITLE
Run3-gex49 Correct the spellings in the scripts in CondTools/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the spellings in the scripts in CondTools/Geometry

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo Please check this

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda The PR description says these scripts were tested with `runTheMatrix.py`. That test does not touch these scripts. They have to be run individually. For example:
```
cd  CondTools/Geometry/test
/bin/cp writehelpers/* .
./createExtended2017Plan1Payloads.sh 113YV99
```

**Comment by cvuosalo** [comment]
@bsunanda Search for "Perecent" in `createExtended2017Plan1Payloads.sh`. There are three misspellings that need to be corrected. Also, `TrackerGeometricDetESModule` has to be deleted from `CondTools/Geometry/test/writehelpers/geometryExtended2017_writer.py` and `CondTools/Geometry/test/writehelpers/geometryExtended2018_writer.py`. 

`createExtended2017Plan1Payloads.sh` and `createExtended2018Payloads.sh` have not been used for quite some time, and they are currently non-functional, so you are opening a can of worms by touching them. They would be used to create new geometry DB payloads for Run 2, but there is currently no use case for this task.

You might want to drop `createExtended2017Plan1Payloads.sh` and `createExtended2018Payloads.sh` from this PR, and instead write an issue describing the problems with them that need to be fixed (what I mentioned above). If you keep them in this PR, you will need to debug and test them.

**Comment by cvuosalo** [comment]
@bsunanda `createExtended2021Payloads.sh` looks good to me. It can stay in this PR. You should test it yourself to verify that it is working.

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
please test

> +1
> 
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-535b11/12551/summary.html
> **COMMIT**: [4d259b6](https://github.com/cms-sw/cmssw/commit/4d259b6022af638aab34b64e01fb2a1c090b0576)
> **CMSSW**: CMSSW_11_3_X_2021-01-26-1100/slc7_amd64_gcc900
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/32745/12551/install.sh` to create a dev area with all the needed externals and cmssw changes.
> ## Comparison Summary
> 
> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons
> 
> **Summary**:
> 
>     * No significant changes to the logs found
> 
>     * Reco comparison results: 1096 differences found in the comparisons
> 
>     * DQMHistoTests: Total files compared: 37
> 
>     * DQMHistoTests: Total histograms compared: 2716596
> 
>     * DQMHistoTests: Total failures: 3611
> 
>     * DQMHistoTests: Total nulls: 19
> 
>     * DQMHistoTests: Total successes: 2712944
> 
>     * DQMHistoTests: Total skipped: 22
> 
>     * DQMHistoTests: Total Missing objects: 0
> 
>     * DQMHistoSizes: Histogram memory added: -45.703 KiB( 36 files compared)
> 
>     * DQMHistoSizes: changed ( 140.53 ): -44.531 KiB      Hcal/DigiRunHarvesting
> 
>     * DQMHistoSizes: changed ( 140.53 ): -1.172 KiB       RPC/DCSInfo
> 
>     * Checked 156 log files, 37 edm output root files, 37 DQM output files

I'm surprised to see so many changes in `140.53 RunHI2011+RECOHID11+HARVESTDHI`.
@bsunanda @cvuosalo @ggovi did you expect it? Perhaps it is uncorrelated to this PR therefore I started the test again

**Comment by cvuosalo** [comment]
@silviodonato The scripts in this PR are not exercised by any PR test, so the PR comparison differences have nothing to do with this PR.
In fact, two scripts in this PR are not even working:
```
CondTools/Geometry/test/writehelpers/createExtended2017Plan1Payloads.sh
CondTools/Geometry/test/writehelpers/createExtended2018Payloads.sh
```
I don't think it is recommended practice to approve PRs with non-working scripts. At the very least, prominent "FIXME" comments should be added to the two scripts.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@smuzaffar are the tests running? I see " cms/32745/slc7_amd64_gcc900/comparison Pending — Waiting for tests to start "

**Comment by smuzaffar** [comment]
@silviodonato , yes tests are running, jenkins is still under heavy load after yesterday's network issues.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
