### PR TITLE
Updating MssmHbb and Trigger Btagging Monitor with DeepCSV algo

### PR DESCRIPTION
**Pull request by antoniovagnerini**

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@antoniovagnerini @dmitrijus the test workflow log files are full of messages like:

%MSG-w TopMonitor:  TopMonitor:hltMssmHbbmonitoringAL100  03-May-2018 21:26:41 CEST Run: 1 Event: 3
B-Jet handle not valid 

%MSG

This does not sound very healthy, could you please comment?

**Comment by antoniovagnerini** [comment]
hi @defranchis since you developed the TopMonitoring modules can I ask you to check if the offline btagging input tag is the correct one ? 
offlineBtag = cms.InputTag("pfDeepCSVJetTags")

Could it be that we need to switch to "pfDeepCSVDiscriminatorsJetTags" in 10_1_X ?

**Comment by defranchis** [comment]
Hi @antoniovagnerini, all

the correct input tag should be "pfDeepCSVDiscriminatorsJetTags:BvsAll". You can give it a try and let me know if it works

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@antoniovagnerini @dmitrijus @jfernan2 sorry to insist, but my question has not yet been addressed, as it appears from the summary:

You potentially added 2651 lines to the logs

**Comment by fabiocos** [comment]
@antoniovagnerini @dmitrijus @jfernan2 dea all, is there any reaction to my question? We are trying to minimize the amount of warnings in the output, and this PR is adding a good number of new ones...

**Comment by antoniovagnerini** [comment]
I think this warning message is coming from the Top Monitoring, maybe @defranchis can comment on that

**Comment by fabiocos** [comment]
@antoniovagnerini any news about this PR?

**Comment by fabiocos** [comment]
hold 

pending reactions from the authors

**Comment by antoniovagnerini** [comment]
I updated the btagalgo name as suggested by Matteo by switching to  
  offlineBtag = cms.InputTag("pfDeepCSVJetTags:probb + pfDeepCSVJetTags:probbb"),
I hoper this fixes the issue.

**Comment by fabiocos** [comment]
please test

**Comment by antoniovagnerini** [comment]
since it appears that there is no deepCSV btagalgo at reco level , I reverted the changes of the Offline BTag monitoring

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

log files now should be clean, anyway the problems looks solved

**Comment by fabiocos** [comment]
unhold

the problem that triggered the "hold" action seems to be solved. @jfernan2 @dmitrijus could you please check and sign this in case?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
