### PR TITLE
Minor revisions to Run 3 simulation geometry

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the DB payloads for the Run 3 simulation geometry. Details of the changes can be found in the [HyperNews thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4352.html).

The GT diffs are identical for all six scenarios:

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v10/112X_mcRun3_2021_design_v11

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v10/112X_mcRun3_2021_realistic_v11

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v10/112X_mcRun3_2021cosmics_realistic_deco_v11

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v12/112X_mcRun3_2021_realistic_HI_v13

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v10/112X_mcRun3_2023_realistic_v11

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v10/112X_mcRun3_2024_realistic_v11

#### PR validation:

Please see the [AlCa HyperNews thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4352.html) for details. In addition, a technical test was performed:

`runTheMatrix.py -l limited,12024.0,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is anticipated.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 12024.0,7.23,159.0,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by cvuosalo** [comment]
The comparison differences are what is expected when comparing two independently generated MC samples of 10 events each. There are no obvious problems, and the differences are just statistical fluctuations from a very small sample.
I think this PR can be merged.
+1

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
