### PR TITLE
Fixing compiler warnings after updating to fastjet 3.3.0. 

### PR DESCRIPTION
**Pull request by rappoccio**
Responding to #22297, here are a few updates:

1. Changing to use selectors instead of range definition. 
2. Removing fastjet 2 ghost placement. 
3. Removing unused test-large-voronoi-area.cc. 
4. Removing range definition entirely from the PileUpSubtractor, it is unused. 

The second change will induce small but expected changes in the jet areas.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rappoccio** [comment]
The comparisons look as expected. There are a few small changes due to the ghost placement change.

**Comment by perrotta** [comment]
@rappoccio : trying to find some documentation which explains your point 2 I ended up jumping on
http://fastjet.fr/repo/doxygen-3.3.0/classfastjet_1_1GhostedAreaSpec.html#a8c9d4cac9f2fe977a2a750f045387432

According to that manual, set_fj2_placement is deprecated in FastJet 3 and simply avoiding setting it to true let the code stick on the FJ3 ghost placement.

All this seems good!

I have one question for you: based on what the comparisons "look as expected"? The changes in shape
look minor, but from what can you deduce that there was an improvement in them? Do you have any study for it that you can point out, or do you consider it better simply because it follow now the recommandations of the authors of that code? (Which is not wrong, in principle, by the way!)

**Comment by rappoccio** [comment]
@perrotta Right. The changes were minor. We shouldn't see very much improvement (very slight improvement in resolution of area). We are now just following their recommendations.

**Comment by perrotta** [comment]
Modifications in pat::jet are visible in the miniAOD outputs of the jenkins tests, with effect propagated to the correlated quantities. Curiously enough, the only workflows run in the automatic tests in which there is some effect also on reco::jet's are the HeavyIons ones:

- 150.0_HydjetQ_B12_5020GeV_2018, e.g.
image

-  140.53_RunHI2011, e.g.
image

For the standard workflows, I ran some slightly larger stats (400 events) with two potenzially affected workflows, i.e. TTbar with PU and highPt QCD. The differences wrt baseline are in line with what observed with lower statistics in the automaticjenkins tests:

- QCD13TeVPt3Ts3T5in2018 wf 10859:

all_mini_testpr22305vsorig_qcd13tevpt3ts3t5in2018wf10859p0c_log10patjets_slimmedjets__reco_obj_energy
image

- TTbar13TeVPU2017 wf 10224:

image
image

**Comment by perrotta** [comment]
+1
- This PR addresses the warnings that appeared after the move to the new 3.3.0 fastjet version (see also issue #22297). To do so it complies to the recommendation of the authors of fastjet of replacing deprecated methods and ghost placement with the updated and preferred ones
- The move from FJ2 to FJ3 ghost placement has some expected effect on the jet outputs and all related variables. There are however no visible drawbacks in the move, which goes in the direction of getting fully compliant with the last version of fastjet (already implemented in CMSSW)

**Comment by rappoccio** [comment]
Indeed the jet corrections are only ever applied at the MINIAOD level for pp collisions.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
