### PR TITLE
Validation plots for APE and bug fixes: Backport of #34828

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

Changes to the APE tool:

-Bug fixes: Remove lines that were previously added to prevent memory leaks, but which created errors. Also tweak some lines in test/plottingTools.
-Added a new plotting tool to allow for creation of plots with residual distributions plus some other validation plots.
-Added an option to autoSubmitter, so that APE can be more easily measured on cosmics data sets.

#### PR validation:

Ran some basic tests of the code on the most recent APE campaign to confirm that the changes work as intended.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34828

As I understand it, this is the CMSSW version currently used for data taking, so it's important to have the bug fixes and other features included in this and later CMSSW versions.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by tlampen** [comment]
+alca

**Comment by qliphy** [comment]
@mteroerd  We may also need a backport to 12_0_X?

**Comment by qliphy** [comment]
+1

**Pull request merged**
