### PR TITLE
Fix typo in Types.py

### PR DESCRIPTION
**Pull request by makortel**
While debugging something else, I encountered this obvious typo. In the end it was not the cause of my problem (I was trying to do `cms.bool("False")` instead of `cms.bool(False)` and noticed it only afterwards), here is anyway a fix.

Tested in CMSSW_8_1_0_pre1, no changes expected.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Good catch. How was this found?

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Can you expand the unit test for this file to show the problem is solved?

**Comment by makortel** [comment]
@Dr15Jones Here is a unit test that fails without the fix (although I'm not sure about the robustness of the test).

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Thanks for the test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
