### PR TITLE
[DQM] Fix hcal calib 

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fix for last round of pyhton3 changes

Testing it at Online DQM

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters:

- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test

**Comment by tvami** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1
Tested in Online DQM at P5

**Comment by perrotta** [comment]
+1
- It was merged right now in the master, and therefore I am not waiting for an IB to verify that it works. On the other hand, this is a rather simple fix, and it has been already [tested](https://github.com/cms-sw/cmssw/pull/35535#issuecomment-934499801) in P5: let have it merged also for the next 12_0_X patch release

**Pull request merged**
