### PR TITLE
Disable D88 PU wfs

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to fix IB issue of D88 PU wfs, https://github.com/cms-sw/cmssw/pull/36833#issuecomment-1028546775
In addition, this PR also disable D88 dd4hep wf, and update README.

#### PR validation:
- Test with 39434.21,39634.21,39634.9921,39634.99,39634.999

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
- No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to disable D88 PU workflows until the migration is complete.

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 do you agree in temporarily disabling the D88 PU wfs, thus avoiding the errors in the IB tests until minbias events for the PU can be produced in pre5?

**Comment by kskovpen** [comment]
OK, so this would mean performing the D88 validation in noPU wfs in pre5 and, once D88 PU wfs are enabled in post-pre5 release, validate D88 once again (noPU and PU). This should be fine, unless @bbilin and @jmartinb have a different opinion.

**Comment by srimanob** [comment]
Hi @kskovpen 
You can validate classical PU mixing in pre5 also. I just need an updated MinBias dataset, to define what will be used for MinBias in the short matrix and IB.

**Comment by srimanob** [comment]
Or if needed, I can enable PU using 12_2_0_pre3 D88 for now, then update later.
/RelValMinBias_14TeV/CMSSW_12_2_0_pre3-122X_mcRun4_realistic_v4_2026D88noPU-v1/GEN-SIM
(maybe in PR that will not be merged, just to prove a thing is doing right)

**Comment by kskovpen** [comment]
> Hi @kskovpen
> You can validate classical PU mixing in pre5 also. I just need an updated MinBias dataset, to define what will be used for MinBias in the short matrix and IB.

OK, let's follow this way.

**Comment by srimanob** [comment]
test parameters:
- workflows = 39434.21,39634.21,39634.9921,39634.99,39634.999

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@perrotta @qliphy @cms-sw/pdmv-l2 

From the last test, 
- all D88 PU workflows (39434.21,39634.21,39634.9921,39634.99,39634.999) run fine using 12_2_0_pre3 MinBias as PU, https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1902b4/22245/runTheMatrix-results/
- It seems relvals input test tries to find CloseByPGun sample in 12_2_0_pre3 (reported as relvals input error with 39496.0DAS Error, 39500.0DAS Error) and then error. It seems to relate to the enable of D88 in relvals_step (which is needed to define PU dataset),
https://github.com/cms-sw/cmssw/blob/c050e871f9e693ffec644f48de876a221f741a6c/Configuration/PyReleaseValidation/python/relval_steps.py#L3467
Since we didn't produce it, failure is expected. I think this will cause another issue in IB if we enable D88 dataset setting.

We have 2 options here to get rid of failure in the next IB:
- Disable D88 datasets for now. We then need to disable PU wfs also.
- Produce CloseByPGun in 12_2_0_pre3, then merge this PR later
What do you think? I am fine in both options.

**Comment by perrotta** [comment]
Please @cms-sw/pdmv-l2 advise about https://github.com/cms-sw/cmssw/pull/36871#issuecomment-1030722709

**Comment by perrotta** [comment]
urgent

**Comment by srimanob** [comment]
Maybe disable D88 input dataset for now, to avoid another relval input error. Then we make a complete set in 12_3_0_pre5. We will run only NoPU from scratch in the short-matrix and IB for the next 2 weeks.

Classical mixing is working from the test, so no worry about that. I can open another PR to test mixing if needed, but don't merge.

**Comment by kskovpen** [comment]
> Maybe disable D88 input dataset for now, to avoid another relval input error. Then we make a complete set in 12_3_0_pre5. We will run only NoPU from scratch in the short-matrix and IB for the next 2 weeks.
> 
> Classical mixing is working from the test, so no worry about that. I can open another PR to test mixing if needed, but don't merge.

Agreed.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please abort

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
I think the PR is ready as we agreed @kskovpen

**Comment by kskovpen** [comment]
+1

**Comment by perrotta** [comment]
+1
- (To be re-enabed as soon as the minbias samples for PU will become available in pre5)

**Pull request merged**
