### PR TITLE
Integration of the new Lumi PCC workflow in PCL and Prompt-Reco

### PR DESCRIPTION
**Pull request by cerminar**
This PR integrates (and supersedes)  #22439

The following features have been added:
1. PCL workflow for PCC correction computation on dedicated ALCARAW
2. Prompt workflow for consumption of the corrections computed by PCL and creation of a new ALCARECO
3. RelVal tests for all of the above (modified existing workflow 1020).
4. ConfigDP scenario to run 1 and 2 @ Tier0
5. equip ConfigDP tests to check the new workflow creation

Still outstanding (but not a showstopper for integration) is the modification of the class https://github.com/cerminar/cmssw/blob/4ccc1b642378fb41911793a1f06a716d9d8c174f/Calibration/LumiAlCaRecoProducers/plugins/CorrPCCProducer.cc 
to produce DQM MEs. @samhiggie @capalmer85 this will need your action to be addressed.

### CODE REVIEW

**Comment by cerminar** [comment]
Not sure I understand the origin of the conflict. I guess I don't understand how codechecks work...

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
+1

**Comment by prebello** [comment]
please test workflow 1020

**Comment by prebello** [comment]
+1

**Comment by arunhep** [comment]
@fabiocos it will be great if we can have it in 10.1.X pre3
we then will prepare a backport to 10.0.X so that it can be tested before data taking.
thanks a lot.

@kpedro88 can you please have a look and sign?
thanks.

**Comment by kpedro88** [comment]
+1

**Comment by samhiggie** [comment]
Hello All, 

A point that @cerminar has mentioned in the beginning of this PR, is the modification of the class https://github.com/cerminar/cmssw/blob/4ccc1b642378fb41911793a1f06a716d9d8c174f/Calibration/LumiAlCaRecoProducers/plugins/CorrPCCProducer.cc
to produce DQM MEs. @capalmer85  and I would just like to save our histograms and TGraphs. We need them for lumi validation. Is this the easiest path to do that? We are happy to move forward with the path of least resistance. 

--Sam

**Comment by fabiocos** [comment]
@cerminar is the output of 1020 ok according to the expectations?

**Comment by cerminar** [comment]
@fabiocos yes I confirm that the output of 1020 is ok.
I just added one commit that should be transparent: as discussed in the backport PR #22617 this enforces the right scheduling.
In this case, since WF 1020 was succeeding, this is completely transparent and the tests should yeld exactly the same results as before.
As far as I am concerned this is ready for intergration.

**Comment by cerminar** [comment]
please test

**Comment by arunhep** [comment]
+1
although in the last iteration of tests 1020 was not run but as @cerminar said, we don't expect any changes.

**Comment by prebello** [comment]
Conflicting file: Configuration/AlCa/python/autoCond.py 
Could you please confirm?

**Comment by arunhep** [comment]
@cerminar  in the meantime this PR https://github.com/cms-sw/cmssw/pull/22642 was merged and hence the conflict.
Please rebase this PR to master and then you don't need autoCond update of this PR.

**Comment by cerminar** [comment]
please test

**Comment by arunhep** [comment]
+1
(provided jenkins agree)

**Comment by arunhep** [comment]
@kpedro88 @prebello can you please check and sign?

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
I am concerned that in the latest round of comparisons, we have:
> Reco comparison results: 7891 differences found in the comparisons

Is this expected, or maybe caused by the build picking up additional merge commits?

**Comment by arunhep** [comment]
@kpedro88 this PR can't change RECO so it has to be with other commits.

**Comment by kpedro88** [comment]
Ah, it must be "GT Updates with GEM electronics map, hadronic PF calibrations, JECs for 2017 MC"

**Comment by arunhep** [comment]
@kpedro88 infact here they are
https://github.com/cms-sw/cmssw/commit/0d170b59287b96631a61b0210ccdc9db24e34728
https://github.com/cms-sw/cmssw/commit/88fd5cd162e6570b73b633ddf54c37cf3fb758b9

changing the global tags and hadronic pf calibrations.

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@cerminar before moving with the integration, could you please clarify the implication of moving the harvesting from AlCaTestEnable.py to AlCa.py and the refactoring of the expressProcessing? What does this imply from the Tier0 point of view?

**Comment by cerminar** [comment]
@fabiocos This is just to avoid code duplication: we now have 2 scenarios inheriting from AlCa and implementing the PCL functionality:
   * `AlCaTestEnable` https://github.com/cerminar/cmssw/blob/879073cf9fd1949db8122b8f33cba0373d98117f/Configuration/DataProcessing/python/Impl/AlCaTestEnable.py.
   * `AlCaLumiPixels` https://github.com/cerminar/cmssw/blob/879073cf9fd1949db8122b8f33cba0373d98117f/Configuration/DataProcessing/python/Impl/AlCaLumiPixels.py

For the other scenarios derived from the `AlCa` base-class the change should be totally transparent.

Note that ~nothing changed for `AlCaTestEnable` where the additional lines w.r.t to the base-class are only there to ensure that the alcareco used to secure the RAW of the stream is always in the configuration thus protecting it against mishandling on the Tier0 side (but this has always been there...and would not make sense to be implemented by the baseclass).
Hope this clarifies.

**Comment by cerminar** [comment]
@fabiocos BTW, this is probably the main reason to test all this asap: we need to make sure that the mechanism to have the RAW saved for `AlCaTestEnable` is still functional since a mistake there would imply loosing data potentially forever.

**Comment by fabiocos** [comment]
@cerminar thanks for the clarification

**Comment by fabiocos** [comment]
+1

**Pull request merged**
