### PR TITLE
Use thread friendly modules in L1Trigger/L1TNtuples

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted to edm::one::EDAnalyzer

#### PR validation:

Code compiles without CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
