### PR TITLE
Update showerParams.py in L1Trigger/CSCTriggerPrimitives

### PR DESCRIPTION
**Pull request by fmanteca**
#### PR description:

Update Muon Shower Trigger **loose** thresholds to match the thresholds in firmware deployed at p5 on June 23rd: https://its.cern.ch/jira/browse/CMSLITDPG-1169

#### PR validation:

https://its.cern.ch/jira/browse/CMSLITDPG-1087

https://its.cern.ch/jira/browse/CMSHLT-2871

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
