### PR TITLE
Backport of PR#18159

### PR DESCRIPTION
**Pull request by kencall**
Validation plots are added for HcalRecHits, HcalDigis, and HcalSimhits to support Hcal Plan1 configuration. Behavior is controlled through eras customization.

### CODE REVIEW

**Comment by hatakeyamak** [comment]
We are hoping to have this in 901, as we want to use this update to validate the HEP17 performance.

**Comment by dmitrijus** [comment]
+1

**Comment by hatakeyamak** [comment]
The last update is just propagated from PR18159 and should allow jenkins tests pass...

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
