### PR TITLE
Updated Geant4 sensitive detector code for low-energy gflash method

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Update Geant4 sensitive detector code:
1) trigger low-energy GFlash only inside ECAL crystals and not in pre-shower or absorber;
2) GFlash spots should be inside crystals, not other materials
3) fixed minor numerical problems in low-energy GFlash method

If GFlash is not enabled results should not be affected.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , FYI

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
