### PR TITLE
reimplementation of Track classifiers and Track Collection mergers

### PR DESCRIPTION
**Pull request by VinInn**
I have fully reimplemented track selectors and merger.
Separated all concerns:
one class to use mva,
one class to use cuts (mimics mva output)
one class to merge selectors
one class to merge collections.
to be done
re-implement duplicate identification and merging
port to HLT

do not esclude that some non-main-stream use-cases are not covered yet.
some more cleanup and optimization is surely required.

I have also implemented a macro to instantiate a sort of DynArray as C++14 does not support anymore
dynamical array.

Full backward compatibility is not maintained.
1) 
The vertex identification uses only delta-z and not the track-vertex association:
the latter (besides being utterly show to verify with the current implementation) it is only working
for Iter0:  tracks from all other iterations are not associated to any vertex
2)
quality  looseSetWithPV and  highPuritySetWithPV is not set (nobody is using it)
and does not make much sense when using MVA anyhow (it can mark if the mva is prompt or detached, maybe.  TBD)
3) Iter5 and 6 are MVA only

In my opinion it requires still a couple of weeks of work.
I will not work for the next two weeks, so I prefer to submit this PR for reference and to collect feedback.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
requesting a test blindly at this point

This PR will roll to 76X once it becomes available.

**Comment by slava77** [comment]
There are problems in HI and fastsim workflows related to this PR.
Both are similar.

HI problems:
```
RecoHI/HiMuonAlgos/hiMuonIterativeTk_cff.py", line 3, in <module>
    from RecoHI.HiMuonAlgos.HiRegitMuonInitialStep_cff import *
  File "RecoHI/HiMuonAlgos/HiRegitMuonInitialStep_cff.py", line 64, in <module>
    hiRegitMuInitialStepSelector               = RecoTracker.IterativeTracking.InitialStep_cff.initialStepSelector.clone( 
AttributeError: 'module' object has no attribute 'initialStepSelector'

```

fastsim problem:
```
FastSimulation/Tracking/iterativeTk_cff.py", line 8, in <module>
    from FastSimulation.Tracking.InitialStep_cff import *
  File "FastSimulation/Tracking/InitialStep_cff.py", line 38, in <module>
    initialStepSelector = RecoTracker.IterativeTracking.InitialStep_cff.initialStepSelector.clone()
AttributeError: 'module' object has no attribute 'initialStepSelector'

```

**Comment by VinInn** [comment]
ok, more work needed.
in addition i suspect that muonseeding is not correcly classified..
leave it pending.
if it looses 75X train, will wait for next

**Comment by slava77** [comment]
-1
moving to 76X.
The new PR to follow is #9810. It is based on the same topic branch VinInn:TrackClassifiers

**Pull request closed without merging**
