### PR TITLE
Removed unused HITSiStripRawToClustersRoI

### PR DESCRIPTION
**Pull request by Dr15Jones**
HITSiStripRawToClustersRoI is not used anywhere in CMSSW and it
depends on getting data in the form of an edm::LazyGetter<> but no
present modules create that type. We are removing all remaining
uses of edm::LazyGetter<> since that class is not thread-safe.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Doing ```git grep HITSiStripRawToClustersRoI``` at the top level of CMSSW only finds the files that I have removed.

**Comment by Dr15Jones** [comment]
please test

**Comment by diguida** [comment]
+1
removal of unused class `HITSiStripRawToClustersRoI` using non-thread safe `edm::LazyGetter<>` interface to get data collections.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
