### PR TITLE
Run3-376Y Modify the testing code of HcalTopology

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code of HcalTopology

#### PR validation:

Ran the testing script for a number of scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Dr15Jones** [comment]
Please make this into an actual automated test. This is accomplished by
1. creating a shell script which runs cmsRun with the script, captures the output and compares it to expected output
2. add to the test/BuildFile.xml a line to execute the script

An example of such can be seen 
https://github.com/cms-sw/cmssw/blob/master/FWCore/Integration/test/CatchCmsExceptiontest.sh
https://github.com/cms-sw/cmssw/blob/32c7e17f2eba543e6ca5f8544cadad81c30c4780/FWCore/Integration/test/BuildFile.xml#L41

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Comment by makortel** [comment]
I second Chris' request that these tests should really be made automatically run (to e.g. catch cases like https://github.com/cms-sw/cmssw/issues/46290 earlier)

**Comment by bsunanda** [comment]
I agree with Chris and you. Before it is made automatic, I want to make sure that the test is good and does not have flaws.
________________________________

**Pull request merged**
