### PR TITLE
L1T: Add jet quality and eg/tau isolation data vs. emu comparisons and ignore object index [12_6_X]

### PR DESCRIPTION
**Pull request by bundocka**
Backport of #40511 

#### PR description:

- Adds jet quality and eg/tau isolation to the CaloL2 data vs emulator plots in the online DQM
- Bug fix to ignore the ordering of CaloL2 objects for data vs emulator comparisons

#### PR validation:

- Ran locally on lxplus with recent ExpressPhysics data and checked histogram outputs are as expected
- Ran unit tests with `cmsRun DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py unitTest=True`

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
hold

* Explicit hold to ensure no accidental merging, the master branch has not converged.

**Comment by emanueleusai** [comment]
type l1t

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
unhold
- Signatures have been reset, both here and in the master version #40511, of which this PR is a verbatim backport

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by emanueleusai** [comment]
@bundocka do you need this deployed online?

**Pull request merged**
