### PR TITLE
Run2-sim25 Attempt to change warning and important energy for G4Trasportation

### PR DESCRIPTION
**Pull request by bsunanda**
This is an attempt to control this for e-/e+. Vladimir - please take a look if it can be improved. Also this needs geant4.10.5.beta or original for a missing method in existing geant4.10.4

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
@bsunanda ,  sorry, my initial advice to use EM physics constructors  was not optimal. I would propose to close this PR. It is possible to add this feature without touching many classes. I am sure, that this can be done in g4SimHits + only in one extra place. There is no need to touch 16 classes and change class signatures for this study, which itself may be useful only for a limited time.

**Comment by civanch** [comment]
@bsunanda , I have provided #24446 which do the same thing in a simple way, names of new parameters are the same as in this PR.

**Comment by bsunanda** [comment]
The same goal is achieved in a better way in #24446.

**Pull request closed without merging**
