### PR TITLE
Adding new razor triggers to SUSY DQM

### PR DESCRIPTION
**Pull request by jaylawhorn**
Adding SUSY DQM modules for new Razor Hbb triggers.

### CODE REVIEW

**Comment by perrotta** [comment]
Please @jaylawhorn : prepare also a 81X version of this pull request

**Comment by perrotta** [comment]
please test

**Comment by jaylawhorn** [comment]
https://github.com/cms-sw/cmssw/pull/15220 is 81X version

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
