### PR TITLE
Cellular Automaton Quadruplet seeding

### PR DESCRIPTION
**Pull request by felicepantaleo**
Phase 1 quadruplet seeding using Cellular automaton, disabled by default.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
@felicepantaleo 
please add a link to a talk in tracking POG or some other further documentation.

Please post a (set of) commands how to check the code run time.

**Comment by felicepantaleo** [comment]
@slava77 
You can find the talk here:
https://indico.cern.ch/event/542270/

You can enable it in a specific iterative tracking step by passing useCellularAutomaton = cms.bool(True) in the CombinedHitQuadrupletGenerator's PSet. 
See below:
```
CombinedHitQuadrupletGenerator::CombinedHitQuadrupletGenerator(const edm::ParameterSet& cfg, edm::ConsumesCollector& iC):
  theSeedingLayerToken(iC.consumes<SeedingLayerSetsHits>(cfg.getParameter<edm::InputTag>("SeedingLayers")))
{
  if(cfg.exists("useCellularAutomaton")) 
  {
    useCellularAutomaton = cfg.getParameter<bool>("useCellularAutomaton");
  }
```

**Comment by makortel** [comment]
Thanks @felicepantaleo for the prototype. (I think we already discussed this but let me repeat) Since the current `PixelQuadrupletGenerator` and the CA version need very different interfaces, it would be much cleaner to have fully separate implementations. Also the way the current seeding framework uses different seeding algorithms is via different helper plugins.

Therefore I'd suggest to leave `PixelQuadrupletGenerator`, `HitQuadrupletGeneratorFromTripletAndLayers`, and `CombinedHitQuadrupletGenerator` untouched by this PR, and create a new (e.g.) `PixelQuadrupletGeneratorCA` that contains all the new stuff. The new class could derive directly from `HitQuadrupletGenerator` (as `CombinedHitQuadrupletGenerator` does) and have the implementation of actual quadruplet generation (as `PixelQuadrupletGenerator` does). This way the CA quadruplets would get plugged in the seeding framework as any other seeding algorithm. I know this is a bit more complex than what is in this PR, but it would be consistent with rest of the system.

I agree that the current use of three classes `PixelQuadrupletGenerator`, `HitQuadrupletGeneratorFromTripletAndLayers`, and `CombinedHitQuadrupletGenerator` is a bit overengineered (but following the structure of existing triplet structure), and could be (probably will be) simplified at some point (as many other over-abstractions in seeding...).

For testing, I'd suggest to create a customise function that just e.g. switches all iterations currently using  `PixelQuadrupletGenerator` to CA, like https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/RecoTracker/Configuration/python/customiseForQuadrupletsByPropagation.py did for changing all `QuadrupletSeedMerger`'s to `PixelQuadrupletGenerator` (this customise is actually a bit obsolete now and probably should be removed or updated, but I hope it is good enough to make the point). The configurations don't have to be optimized (if e.g. different iterations need different parameters), important is that the new code gets run and there is an example of how to configure the new algo.

**Comment by felicepantaleo** [comment]
thanks @makortel 
I'm implementing your suggestions.

**Pull request closed without merging**
