### PR TITLE
Add objects to allow possibility of storing energy deposit information in passive material

### PR DESCRIPTION
**Pull request by bsunanda**
Useful to study energy weight factor in new calorimeters

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi @bsunanda @civanch - did you consider if the string volume name could be represented instead as an int or something more data storage friendly?

**Comment by civanch** [comment]
@davidlange6, Volume name is not the best what can be proposed as an identificator of the passive material volume, because is run time & memory penalty. However, I do not see how to do this more efficiently. At least, this analysis should be done once and in normal production such hits should not be created.

**Comment by bsunanda** [comment]
@davidlange6 Could not find anything more suitable. This is only useful for very special cases (not standard production) and for evaluating weight factors in calorimeters

**Comment by davidlange6** [comment]
+1
ok, lets see the next step - one can easily think of a (long) int that allows a lookup table to a one-time-stored (or better even created from a geometry...) lookup table .

**Pull request merged**
