### PR TITLE
Ignoring calibration channels in the dataframes

### PR DESCRIPTION
**Pull request by igv4321**
Backport of PR #17777

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@igv4321 please edit the PR title to include explicit description of the change
The fact that this is a backport can be added as a label by posting "backport of #17777" message for the cms-bot

**Comment by igv4321** [comment]
OK. By the way, what is a good base release to use so that this fix gets into the 8_4_0 and, eventually, online?

**Comment by slava77** [comment]
On 3/5/17 1:02 PM, Igor Volobouev wrote:
> OK. By the way, what is a good base release to use so that this fix gets
> into the 8_4_0 and, eventually, online?

CMSSW_8_4_X

**Comment by igv4321** [comment]
OK, thanks. That backport is now submitted as PR #17781.

**Comment by perrotta** [comment]
+1
The problem observed has been reproduced (in 84X), and I could verify that it gets fixed by this PR.
There is no sign of regression in jenkins outputs, and reco can sign it off.
(See #17777 for the discussion)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
