### PR TITLE
Fixes for low-level alpaka based utilities [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Fix various low-level alpaka based utilities that were inadvertently mixing host and device code.

Required to build with alpaka in GPU-only mode.

#### PR validation:

Unit tests pass.

No impact on the HLT performance, as expected.
`CMSSW_14_0_4`:
```
Running 4 times over all events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   514.3 ±   0.4 ev/s (11800 events, 99.8% overlap)
   533.3 ±   0.5 ev/s (11800 events, 99.7% overlap)
   523.0 ±   0.6 ev/s (11800 events, 100.0% overlap)
   514.8 ±   0.6 ev/s (11800 events, 99.3% overlap)
 --------------------
   521.3 ±   8.9 ev/s
```

`CMSSW_14_0_4` with #44650:
```
Running 4 times over all events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   520.0 ±   0.5 ev/s (11800 events, 99.8% overlap)
   505.8 ±   0.4 ev/s (11800 events, 99.8% overlap)
   559.7 ±   0.5 ev/s (11800 events, 99.8% overlap)
   514.0 ±   0.5 ev/s (11800 events, 99.9% overlap)
 --------------------
   524.9 ±  23.9 ev/s
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44640 to CMSSW 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #44640

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
