### PR TITLE
User plugin ParameterSet validation

### PR DESCRIPTION
**Pull request by Dr15Jones**
Extended the ParameterSet validation system to be able to validate user plugins used by modules. See FWCore/ParameterSet/interface/PluginDescription.h for full documentation.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
please test

@Dr15Jones I doubt that differences observed in DQM have anything to do with this PR, but just to verify

**Comment by Dr15Jones** [comment]
@fabiocos the histograms failures all appear to be from the L1 histograms which are known to not be reliably reproducible.

**Comment by Dr15Jones** [comment]
@fabiocos could we get this into the release soon? A reconstruction based pull request is waiting for this to be in the release so they can update their pull request to use it.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar I notice in the test report https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24622/30568/headers_chks.log problems reported with headers

**Comment by Dr15Jones** [comment]
@smuzaffar It looks like the error pointed out by David shows that we need to change the order the build runs edmWriteConfigs and registration of plugins. This new feature requires that edmWriteConfigs must be able to load plugins some of the times.

**Comment by Dr15Jones** [comment]
@fabiocos I can't see how my change could possibly have lead to the header file problem. Non of the new headerfiles I added are included in those other headers. The one existing header I modified was just me cut-n-paste then change a name on two macros, neither macro being used by files outside of this pull request.

I think you only noticed the header check failing because this pull request caused large number of packages to be checked out and recompiled and therefore also checked.

**Comment by Dr15Jones** [comment]
@smuzaffar I think it is different than that. The user plugin being referenced in the cfi file does not have to come from the plugin holding the module. Therefore edmWriteConfigs can only be run once the edmplugincache file has been merged since we have no other way to know where to look for the user plugin.

**Comment by Dr15Jones** [comment]
@fabiocos @davidlange6 I will have a workaround for the IB problem coming in the next few minutes.

@smuzaffar Unfortunately, I have no way to really test the change since it requires the lack of .edmplugincache from being found.

**Comment by Dr15Jones** [comment]
@smuzaffar I was able to devise a way to test my change. It does avoid the problem in the IB.

**Comment by Dr15Jones** [comment]
#24656 fixes the problem in the IB.

**Pull request merged**
