### PR TITLE
[DQM] Fixed bug in folder which had been renamed 12_3_X

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fixed bug in folder which had been renamed, the bug was affecting Online DQM only

Tested privately in Online mode

Backport of https://github.com/cms-sw/cmssw/pull/38802

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38802

**Comment by jfernan2** [comment]
please test

**Comment by emanueleusai** [comment]
type bug

**Comment by emanueleusai** [comment]
type muon

**Comment by emanueleusai** [comment]
backport of #38802

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
Why do you keep submitting in 12_3_X?
I'd suggest to close this, in order to clean up the queue

**Pull request closed without merging**
