### PR TITLE
[9.4.X] Update GT: Update all L1T tags

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI data

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v4):
      * Add All L1Tag

   * **RunI Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v3):
      * Add All L1 Tag

## RunII data

   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v2) as [94X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v2/94X_dataRun2_HLTHI_frozen_v3):
      * Add All L1 Tag

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v5) as [94X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v5/94X_dataRun2_HLT_relval_v6):
      * Add All L1 Tag

   * **RunII Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v3):
      * Add All L1 Tag

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v5) as [94X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v5/94X_dataRun2_relval_v6):
      * Add All L1 Tag

   * **RunII Prompt processing** : [94X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v5) as [94X_dataRun2_PromptLike_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v5/94X_dataRun2_PromptLike_v6):
      * Add All L1 Tag

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v4):
      * Add All L1 Tag

## Upgrade

   * **PhaseII realistic scenario** : [94X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v2) as [94X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2023_realistic_v2/94X_upgrade2023_realistic_v3):
      * Add All L1 Tag

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4) as [94X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4/94X_upgrade2018cosmics_realistic_deco_v5):
      * Add All L1 Tag

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v5) as [94X_upgrade2018_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v5/94X_upgrade2018_design_IdealBS_v6):
      * Add All L1 Tag

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v5) as [94X_upgrade2018_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v5/94X_upgrade2018_realistic_v6):
      * Add All L1 Tag

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v4) as [94X_mc2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v4/94X_mc2017cosmics_realistic_peak_v5):
      * Add All L1 Tag

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v4) as [94X_mc2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v4/94X_mc2017cosmics_realistic_deco_v5):
      * Add All L1 Tag

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v5) as [94X_mc2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v5/94X_mc2017_design_IdealBS_v6):
      * Add All L1 Tag

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v5) as [94X_mc2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v5/94X_mc2017_realistic_v6):
      * Add All L1 Tag

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of #21137

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
@davidlange6 It is normal tests takes so long?

**Comment by arunhep** [comment]
please abort

**Comment by arunhep** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
@kkotov @rekovic It passed the tests. Let's see if this os the same in 10X

**Comment by lpernie** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by arunhep** [comment]
@jfernan2 can you also please sign this?
Thanks !

**Comment by jfernan2** [comment]
+1

**Comment by arunhep** [comment]
@davidlange6 am surprised that this PR did not make it to 940_patch1. 
Can you please let us know what else needs to be done to merge it?

**Comment by kkotov** [comment]
After #21137 was reviewed by all parties and merged, this PR should follow.

**Comment by davidlange6** [comment]
hi-
please make the changes to L1Trigger/Configuration/python/SimL1Emulator_cff.py in a separate PR (94x is now feature frozen)

**Comment by arunhep** [comment]
thinking more about the changes this PR will bring to 94X, it will be quite hard to handle in terms of global tags. Because the GTs which are being used for the MC V2 production will no longer be compatible with 94X if this is merged.
IMHO its better to keep loading EMTF forest tag from  L1Trigger/Configuration/python/SimL1Emulator_cff.py and we leave 94X with that. 
MC GTs will need to be updated in that case in this PR but this will be the cleanest.

in 10.0.X the PR is already merged and since we have separate GT queues for that, so these EMTF forest tag will be provided by GT.
I will ask @lpernie to make changes in this PR and then it can be merged.

**Comment by arunhep** [comment]
hold

**Comment by davidlange6** [comment]
is that to say this change is _not_ in the GTs under validation for the 94x productions?

**Comment by arunhep** [comment]
> is that to say this change is _not_ in the GTs under validation for the 94x productions?

2017 MC relvals are using a GT much more recent than what is in this PR so they are consuming the latest and greatest conditions from every subsystem including L1T.

data relvals are not using latest L1T conditions. PdmV and L1T DPG are aware of it and they will need to have special validation for data relvals.

**Comment by davidlange6** [comment]
if this GT change is in the 94x MC and data production GTs, then I guess I don't understand this "GTs which are being used for the MC V2 production will no longer be compatible with 94X"?

**Comment by arunhep** [comment]
> if this GT change is in the 94x MC and data production GTs, then I guess I don't understand this "GTs which are being used for the MC V2 production will no longer be compatible with 94X"?

look at this diff : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v10/94X_mc2017_realistic_v6

**94X_mc2017_realistic_v10** is the GT being used for the relvals for 940 and also for MC V2 and is fully compatible with CMSSW_9.4.0 and also with patch1.

**94X_mc2017_realistic_v6** is the GT in this PR. 
If you look at this diff, you see a tag corresponding to the record `L1TMuonEndCapForestRcd` which is present in v6 GT but not in v10 GT.
If this PR is merged along with the changes in 

- L1Trigger/Configuration/python/SimL1Emulator_cff.py
- DQMOffline/L1Trigger/python/L1TriggerDqmOffline_cff.py
- DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py

then one can not use v10 GT with 9.4.X > 9.4.0_patch1. Because this tag `L1TMuonEndCapForest_static_Sq_20170613_v7_mc` currently in 9.4.0 and 9.4.0.patch1 is provided by loading from python configuration.

**Comment by davidlange6** [comment]
sounds like a mess - and I would instead argue that the latest and greatest L1 changes are not in the 94x MC and data production GTs (as the feature in this PR is not there). 

So anyway, this PR does not go into 94x as the DB content change has missed the validation train.

**Comment by arunhep** [comment]
>sounds like a mess - and I would instead argue that the latest and greatest L1 changes are not in the 94x MC and data production GTs (as the feature in this PR is not there).

I am sorry but what feature are you talking about? V10 GT contains the latest and greatest condition for MC V2 including L1T conditions needed for emulation configuration and everything is consistent there. 
For data relvals, indeed updated GTs from this PR are required to perform the validation. This is being followed up with L1T DPG and PdmV.

So anyway, this PR does not go into 94x as the DB content change has missed the validation train.

a changed version of this PR can still go in. Let me coordinate with @lpernie when he will wake up and we will include MC V2 conditions in this along with the changes I mentioned in my previous comments.

**Comment by davidlange6** [comment]
> On Nov 21, 2017, at 1:27 PM, Arun Kumar <notifications@github.com> wrote:
> 
> sounds like a mess - and I would instead argue that the latest and greatest L1 changes are not in the 94x MC and data production GTs (as the feature in this PR is not there).
> 
> I am sorry but what feature are you talking about? V10 GT contains the latest and greatest condition for MC V2 including L1T conditions needed for emulation configuration and everything is consistent there.
> For data relvals, indeed updated GTs from this PR are required to perform the validation. This is being followed up with L1T DPG and PdmV.
> 

you stated that "you see a tag corresponding to the record L1TMuonEndCapForestRcd which is present in v6 GT but not in v10 GT."

**Comment by arunhep** [comment]
>you stated that "you see a tag corresponding to the record L1TMuonEndCapForestRcd which is present in v6 GT but not in v10 GT."

yes but still L1T emulator is consuming this condition from individual loading of tag from python configuration. See this : https://github.com/cms-sw/cmssw/blob/b3b7d360de5cea2df9e92677ef6cc28ef0124188/L1Trigger/L1TMuonEndCap/python/fakeEmtfParams_2017_MC_cff.py#L43
We can't have same tag from same record loading from two different sources. Thats why we need to remove it from V10.

**Comment by davidlange6** [comment]
anyway, the GTs for the 94x release should be exactly what is being used in production. Anything newer can just go into 10x (until updates for miniaod reprocessing are understood)

**Comment by arunhep** [comment]
>anyway, the GTs for the 94x release should be exactly what is being used in production. Anything newer can just go into 10x (until updates for miniaod reprocessing are understood)

exactly. this is what we will do with one commit from @lpernie and then I will unhold it.

**Comment by lpernie** [comment]
hold

**Comment by arunhep** [comment]
@lpernie will open a fresh PR in 94X

**Pull request closed without merging**
