### PR TITLE
adding HoE Tower based for photons

### PR DESCRIPTION
**Pull request by TizianoBevilacqua**
PR description:

With this pull request I added the two versions of Photon HoE calculation to the nAOD variable output. Previously for run 3 the HoE dumped was calo based while for run 2 it was Tower based. Both are needed in both cases for H(gg) analyses.

PR validation:

To test I've created a nAOD starting from Run2 data samples and checked that both version of HoE are dumped correctly

@lfinco @fcouderc

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
