### PR TITLE
DAQ output module: demote LogWarning to LogDebug

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Why does this need a RECO signature ?

@mommsen, @emeschi, can you sign or comment ?

**Comment by mommsen** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
@fwyzard - this package has plugins used in raw->digi which is why at some point a reco signature was added - your code change is not in that part of the package

**Pull request merged**
