### PR TITLE
Use std:: functions instead of TMath:: functions in RecoEgamma

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

I think the standard library math functions should be used unless there is a specific reason to use something else.

RecoEgamma already uses the standard library functions for the most part, this PR is replacing the remaining TMath functions.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport indended.

### CODE REVIEW

**Comment by guitargeek** [comment]
Any idea why the code checks didn't get triggered again?

**Comment by smuzaffar** [comment]
code-checks

no idea, may be you pushed a commit with timestamp in past?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
maybe also
Double_t -> double
Bool_t -> bool
?

**Comment by slava77** [comment]
> maybe also
> Double_t -> double
> Bool_t -> bool
> ?

@guitargeek 
please apply these type name changes as well.
Thank you.

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34325	0670d7a 
- code changes are technical, they are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
