### PR TITLE
[HGC trigger] Clean deprecated files

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
- Remove unused old files
- Remove unused shape object in cluster class

#### PR validation:
Standard tests with different worflows have been run:
```
 runTheMatrix.py -w upgrade -l 20034.0 --maxSteps=2
 runTheMatrix.py -w upgrade -l 20434.0 --maxSteps=2
 runTheMatrix.py -w upgrade -l 22034.0 --maxSteps=2
 runTheMatrix.py -w upgrade -l 22434.0 --maxSteps=2
 runTheMatrix.py -w upgrade -l 27034.0 --maxSteps=2
```

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
thanks @jbsauvan, I very much appreciate the cleanup efforts

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
