### PR TITLE
Phase 2 Trackers. Remove T7 and T8 (IT large pixels study). Add T14 (New OT envelope + Numerous updates in IT).

### PR DESCRIPTION
**Pull request by ghugo83**
This PR adds Tracker T14, and its associated workflows.
This Tracker has a reduced OT envelope + numerous changes in IT. More details in [1].

Full Tracker description is accessible at: http://ghugo.web.cern.ch/ghugo/layouts/T14/OT616_200_IT613/info.html 

Geometry scenario is: 2023D40.
Workflows are: 286xx (no PU), 288xx (PU).

This Tracker should be compared with T12 (2023D36 scenario).

This PR also removes the Trackers which were used for large pixel studies (T7 and T8 + their associated workflows).

**NB 1:** The DetIds are different (since major geometry changes, notably changes in number of modules).
The list of the new DetIds is in PixelSkimmedGeometryT14.txt (external).
See https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/pull/11.
**Please do not launch any test without this external file.**

**NB 2:** As discussed with @emiglior , all changes are put in one Tracker here.
It can be potentially split in 2 Trackers with 'OT changes only' and 'IT changes only' respectively if ever needed.

**NB 3:** Further changes to come (not included in this PR):
- Skewed TBPX.
- Significant MB updates.

**[1] Tracker changes in this PR (versus T12 description):**
**Outer Tracker:**
Reduced OT envelope, to leave space for BTL + IT insertion.
This notably leads to:
 - TB2S:
L3: radius -27 mm (OT envelope shrink) + 2 mm (smaller no-go zone between TB2S and BTL). numRods: -2 rods.
- TEDD:
All radii are changed, following the compression from the innermost and outermost rings (intermediate rings were adjusted accordingly).
Number of modules: 4 modules less in Ring 7 and 4 modules less in Ring 14 in TEDD_2.
- TBPS:
L1: +2 mm in last 5 rings radii.
- Off-topic:
Also increased disk separation in TEDD + Adjusted planck thickness, flipped alternation of outer / inner radii in TBPS.

**Inner Tracker:**
New chip size everywhere.
Adjustments in radii.
New ring paradigm in TEPX (tested on CMMSW by Arash Jofrehei).
2x2 modules in TEPX inner rings.

FYI:  @boudoul (Credits here, happily took ideas from your PRs :)) @alkemyst @pwittich

### CODE REVIEW

**Comment by ghugo83** [comment]
I think I understood the logics behind the magic numbers in https://github.com/cms-sw/cmssw/pull/25988/files#diff-0b98ab5f4c0e35c17624487441dbab08R66 to avoid a shift  in workflow numbering.
Actually I checked and should be fine, but let me know if anyth :)

**Comment by kpedro88** [comment]
thanks @ghugo83! (Net reduction of 1, at least...)

**Comment by boudoul** [comment]
Hello @kpedro88 what is the plan for the geometries for the L1 TDR - What is the scenario intended to be used ?

**Comment by emiglior** [comment]
@jalimena this is of interest for you as well

**Comment by kpedro88** [comment]
@boudoul I think we will start from D35 (used for MTD TDR) and attempt to incorporate some upcoming HGCal geometry updates, if they are ready in time
@rekovic do you have anything to add?

**Comment by civanch** [comment]
please test

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4723

**Comment by ghugo83** [comment]
I do not think this issue is related to this PR. It happens without the commits from this PR ;p

**Comment by fabiocos** [comment]
@ghugo83 it affects also other PRs, it looks a temporary problem accessing a PU file:

----- Begin Fatal Exception 22-Feb-2019 12:11:54 CET-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'digitisation_step'
   [2] Calling method for module MixingModule/'mix'
   [3] Calling RootFileSequenceBase::initTheFile()
   [4] Calling StorageFactory::open()
   [5] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root; No such file or directory
' (errno=3011, code=400). No additional data servers were found.
      [b] Last URL tried: root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root?tried=
      [c] Problematic data server: eoscms.cern.ch:1094
      [d] Disabled source: eoscms.cern.ch:1094
      [e] Input file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root could not be opened.
Fallback Input file root://cms-xrd-global.cern.ch//store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [f] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root', flags=0x10, permissions=0660) => error '[ERROR] Operation expired' (errno=0, code=206). No additional data servers were found.
      [g] Last URL tried: root://cmsdcadisk01.fnal.gov:1095//store/relval/CMSSW_10_5_0_pre1/RelValMinBias_13/GEN-SIM/103X_mc2017_realistic_v2-v1/20000/ACB3CEC8-09F0-174B-AD93-84BA32EED0C5.root?tried=
      [h] Problematic data server: cmsdcadisk01.fnal.gov:1095
      [i] Disabled source: cmsdcadisk01.fnal.gov:1095
----- End Fatal Exception -------------------------------------------------

**Comment by emiglior** [comment]
Hi, is there any news on the problem in accessing the PU file mentioned above by Fabio?

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#4723

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test workflow 28634.0 with cms-sw/cmsdist#4723

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@ghugo83 @emiglior @boudoul @kpedro88 I understand that the removed scenarios were just test ones not used in any production, am I correct?

**Comment by fabiocos** [comment]
+operations

the updated to Configuration is coherent with the purpose of the PR

**Comment by emiglior** [comment]
> @ghugo83 @emiglior @boudoul @kpedro88 I understand that the removed scenarios were just test ones not used in any production, am I correct?

@fabiocos Indeed T7 and T8 were used for only tests.
To my recollection the tracker geometries used for productions are:
- T5 -> phase2 Tracker TDR
- T6 -> MTD TDR

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by boudoul** [comment]
> @boudoul I think we will start from D35 (used for MTD TDR) and attempt to incorporate some upcoming HGCal geometry updates, if they are ready in time
> @rekovic do you have anything to add?

Dear @kpedro88 we just discuss at the XEB that the scenario with the new HGCAL preapred by @bsunanda should include the tracker T14 for the L1 TDR prod , so this scenario should be prepared... I'm adding @fabiocos to inform him prior the ORP (that I may missed today ) -
@venturia , thank you  for providing the name of the tracker to be used.

**Comment by kpedro88** [comment]
@boudoul thanks for the update, let me open an issue to keep track

**Comment by kpedro88** [comment]
see #26071

**Comment by boudoul** [comment]
Perfect , thanks @kpedro88 !

**Pull request merged**
