### PR TITLE
Updates to the Phase-2 DT Trigger primitive generation code

### PR DESCRIPTION
**Pull request by folguera**
#### PR description:

Updates to the analitical method for DT Trigger Primitive generation to keep the code in sync with the FW. Also added Theta Dataformat for future developments.

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by kpedro88** [comment]
Please change the title of this PR to something that clearly describes the proposed changes.

**Comment by srimanob** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
@folguera 
Since I am not sure the status of Phase-2 L1 DQM, Could you please clarify if no change is expected from this PR, or not?
If change is expected, please provide details.

Thanks.

**Comment by folguera** [comment]
@srimanob no changes on the DQM are expected.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
