### PR TITLE
[backport] Improve handling of TF CUDA tests for 14_0_X

### PR DESCRIPTION
**Pull request by valsdav**
#### PR description:

This PR improves the handling of CUDA unit tests for the TensorFlow package, using a new `tf_cuda_support` tool from scram , which checks if the GPU support is enabled in TensorFlow compilation. 

The PR also makes the TF cuda tests more strict by checking explicitely if a CUDA device is visible to TF and not only to cmssw.  

The test `testTFVisibleDevicesCUDA` is in fact run by the framework as a CUDA device is registered, but then TF does not recognize the device and the test fails.   The other `testTF*CUDA` tests were passing silently using the CPU to run the test.  After this PR all the TF sessions using  `tf::backend::cuda` , but  not finding a GPU will fail explicitly. 

- This PR is needed to continue the integration of CUDA 12.4 in https://github.com/cms-sw/cmsdist/pull/9046. 
- This PR needs https://github.com/cms-sw/cmsdist/pull/9066 (thanks to @smuzaffar https://github.com/cms-sw/cmssw/pull/44376#issuecomment-1992693414)
- This PR is a backport of https://github.com/cms-sw/cmssw/pull/44376

### CODE REVIEW

**Comment by valsdav** [comment]
enable gpu

**Comment by valsdav** [comment]
please test

**Comment by valsdav** [comment]
+ml

technical. Avoid running cuda tests if tensorflow is not compiled for Cuda.  
Making sure cuda tests fail if TF does not recognize the card.

**Comment by fwyzard** [comment]
> hold
> 
>     * As discussed at ORP.

@antoniovilela I don't remember any more why this was put on hold.

Do you think we can proceed with it ?
It seems to be blocking #45143.

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
> Do you think we can proceed with it ? It seems to be blocking #45143.

Just to mention that #45143 was merged a few days ago, but this backport is still on hold.

**Comment by antoniovilela** [comment]
unhold

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
