### PR TITLE
Fix for warning from clang static analyzer.

### PR DESCRIPTION
**Pull request by gartung**
Move using namespace directives from header file scope into function/constructor scope

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
[not really necessary, but still, better be in green]

**Comment by gartung** [comment]
Failure is a NOTRUN error

1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Aug 26 22:21:13 2015-date Wed Aug 26 22:21:08 2015; exit: 1 0 0
15 14 13 11 5 1 tests passed, 1 0 0 0 0 0 failed

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10959	6873b0c
- static code analysis by jenkins confirms the issue with "using" directives is gone
- jenkins tests OK for this: compilation and no runtime failure in most of the workflows is enough

**Pull request merged**
