### PR TITLE
Merge CMSSW_9_4_9_cand1 content into 9_4_X (for reminiAOD 2016 reprocessing)

### PR DESCRIPTION
**Pull request by fabiocos**
This PR is the backport into the base CMSSW_9_4_X branch of the additions in the CMSSW_9_4_MAOD_X branch used to build the CMSSW_9_4_9_cand1 build, to be used for the validation of the code for the reminiAOD 2016.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.7611,136.7721

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@fabiocos 
based on comments you made in the release meeting, I understood that this PR will be redone.
Since it's apparently purely technical wrt what is already tested/merged in 9_4_MAOD_X, please do not wait for a reco signature.

**Comment by fabiocos** [comment]
@slava77 you are correct, let me clean the situation now

**Comment by fabiocos** [comment]
replaced by #23474

**Pull request closed without merging**
