### PR TITLE
HLT updates on top of 746 (74X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT updates on top of 746 (74X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need to include #9850 (new L1T menus) here as HLT now uses them.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@cmsbuild @smuzaffar 
please explain to me what jenkins tests failed how in this PR.

**Comment by davidlange6** [comment]
looks like a das error in 1001. you can just look at the log in cases where the scripts fail to retrieve the information for you

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebase to 7_4_7

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@davidlange6 
David, I have no clue about these jenkins errors - they can't be related to this PR,
so what is going on?

**Comment by Martin-Grunewald** [comment]
Now that #10345 is in, let's try again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1
Also this one ready to go (74X) - please sign as well.

**Comment by Martin-Grunewald** [comment]
@mulhearn @civanch 
Please sign this PR for 74X.
Thanks!

**Comment by Martin-Grunewald** [comment]
@mulhearn @civanch
Could you please sign this PR for 74X?
Thanks!

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Sorry, traveling yesterday!

**Comment by Martin-Grunewald** [comment]
@civanch
Could you please sign this PR or let me know why you can't do so?
Thanks!

**Pull request merged**
