### PR TITLE
Removed deprecation warnings in EventFilter/DTRawToDigi

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed to thread-friendly module types
- removed unnecessary use of deprecated headers

#### PR validation:

Deprecation warnings are now gone when compiling.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
