### PR TITLE
[RecoTracker] Move public headers to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `RecoTracker`
```
      1 src/RecoTracker/FinalTrackSelectors/plugins/getBestVertex.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34868	3b2a195 
- technical; the addition of cross-package include from /plugins originally happened in 2017 in #19281

**Comment by qliphy** [comment]
+1

**Pull request merged**
