### PR TITLE
[DD4hep]  DDPixFwdBlades legacy algorithm port

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

porting requested by @bsunanda 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cvuosalo** [comment]
As a basis of discussion, it might be helpful to have a bit more context and motivation for this PR, perhaps in the PR description.

**Comment by ianna** [comment]
> As a basis of discussion, it might be helpful to have a bit more context and motivation for this PR, perhaps in the PR description.

@cvuosalo - I let @bsunanda comment on it

**Comment by bsunanda** [comment]
We converted all ddd algorithms to dd4hep counterpart. One was missing. So I requested Yana to take care of that.

**Comment by bsunanda** [comment]
@ianna Could you do the code check. I can try to see if this works for the SIM step

**Comment by ianna** [comment]
> @ianna Could you do the code check. I can try to see if this works for the SIM step

@bsunanda - it will not work because the rotations produced by this algorithms are needed earlier than its invocation. I could propose a couple of workarounds - I think we need to discuss it.

**Comment by bsunanda** [comment]
@ianna @cvuosalo Can we restart discussing about this PR?

**Comment by ianna** [comment]
@bsunanda - Yes, we can discuss it, but, I think, someone else would have to work on this - as my time is reduced to 5% for geometry support next year. That is about 2 hours per week.

**Pull request closed without merging**
