### PR TITLE
Fixes for online beamspot, heavy-ion run in 2018 (10_3_X)

### PR DESCRIPTION
**Pull request by sikler**
The HI reconstruction now uses the same labels as pp, changes are inherited via eras.
The code for the legacy client (beam_*) was cleaned and straigthened out, better readability and similar or same cuts for pp and HI running.
The code for HLT-based client (beamhlt_*) still needs a proper track and vertex collection for the HI run.
Documentation and background is at
https://twiki.cern.ch/twiki/bin/viewauth/CMS/OnlineBeamSpot#Sep_2018_legacy_and_or_HLT_based

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi @sikler, could you please make sure that there is the name of the subsystem in the title of the PR?

**Comment by sikler** [comment]
Hi @andrius-k: title changed, and have asked Tomas to edit the contact list.

**Comment by andrius-k** [comment]
@sikler thanks a lot! I added your Github username myself. I thought I can't do that and only the member of the group that is being edited has write access, but it worked. Soon the changes should be reflected in the page.

**Comment by sikler** [comment]
Updating labels and collection names for the heavy-ion HLT-based (beamhlt) with fresh heavy-ion related infos, as
      process.source.streamLabel = cms.untracked.string('streamHIDQMOnlineBeamspot')
      ...
      process.dqmBeamMonitor.BeamFitter.TrackCollection = 'hltPFMuonMergingPPOnAA'
      process.dqmBeamMonitor.primaryVertex              = 'hltVerticesPFFilterPPOnAA'
      process.dqmBeamMonitor.PVFitter.VertexCollection  = 'hltVerticesPFFilterPPOnAA'

**Comment by andrius-k** [comment]
please test

**Comment by schneiml** [comment]
Note: the change in `SiStrip/MechanicalView` reported by the bot is most likely spurious, this PR can't really affect anything there. But I am very surprised to see such a change, there were apparently no other PRs in the test?

**Comment by threus** [comment]
@sikler , comment on the dedicated HI stream - this morning we discussed with the HI/HLT/DAQ and Run coordination that the online DQM streams might keep the standard names, instead of adding HI to them. To be confirmed in the coming days.

**Comment by sikler** [comment]
@threus I got this information from Yi Chen on Monday on stream names:
"During the TSG integration of the menu last Friday, we discovered a conflict with the pp menu, and renamed the dataset and stream name from DQMOnlineBeamspot to HIDQMOnlineBeamspot.  Could you propagate the name change to the setup?"

Please let me know if I should change the stream names back to usual pp ones.

**Comment by threus** [comment]
@sikler ok, I will investigate around and come back here with the answer.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@andrius-k please sign it in case for reference, as you have already signed the master version

**Comment by andrius-k** [comment]
+1

**Pull request merged**
