### PR TITLE
recreate HcalDDD{Rec,Sim}Constants and HcaluLUTTPGCoder in their ESProducers

### PR DESCRIPTION
**Pull request by slava77**
this came up in tests of running on two well-separated 2017 runs (297557,305064) in one cmsRun.
The produced data should not be cached in ESProducers because it is not owned by the producers
and a repeated call means a new ES product is needed, while the earlier created one was destroyed by the framework.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

to get rid of random differences which are now expected to go away

**Comment by slava77** [comment]
ping
alca, geometry, and l1 signatures are still missing.
This PR will allow running RECO over well-separated run/IOV boundaries in one job.

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
