### PR TITLE
StoppedParticles Bug Fix

### PR DESCRIPTION
**Pull request by jalimena**
The purpose of this PR is to:
- Fix a bug for the StoppedParticles created in the RHStopTracer. Before, the tracks coming from the antiparticles were not looked at, to see if the antiparticles stop in the detector. This is fixed with the one line change in Exotica_HSCP_SIM_cfi.py.
- To better debug this type of problem in the future, more debug statements were added to RHStopTracer.

### CODE REVIEW

**Comment by civanch** [comment]
@jalimena , is it possible to substitute std::cout by LogVerbatum() ?
Also I am not sure if it is optimal to identify particles by name and not pdg code.

**Comment by jalimena** [comment]
The couts are within the if(mDebug) statement, but if you prefer for me to change this to LogVerbatum() or LogDebug(), I can do that.

Identifying the particles by pdg code would be nice, although I'm not sure how practical it is, given that some of the models considered make RHadrons and thus a fairly long list of particles are considered. What I did was to fix the code in the same way it was written, in order to make it work for the antiparticles. However, I can try to change the code to identify them by pdgId, if that's best.

Let me know.

**Comment by civanch** [comment]
@jalimena , let us substitute std::cout in this PR, this does not require any rethinking on the code. Method of particle identification can be updated next time if a good solution will be proposed.

**Comment by jalimena** [comment]
Ok sounds good, done. Thanks!

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
