### PR TITLE
Run4-hgx285 Update some of the remaining validation classes in Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update some of the remaining validation classes in Validation/HGCalValidation

#### PR validation:

Use scripts in Validation/HGCalValidation/test/python to test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @silviodonato @qliphy This PR affects validation of Phase2 geometries. I wonder how the tests unrelated to Phase2 are failing. I believe the failures have no relation to this PR. Please check

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

Plot HGCAL/HGCalSimHitsV/HitValidation/hebEnRec  now gets entries, e.g.:
https://tinyurl.com/yhx3tkep

**Comment by qliphy** [comment]
+1

**Pull request merged**
