### PR TITLE
Seed TICL by L1 & other timing considerations for EGM HLT: backport to 11_1

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

This is a backport of #32978 to 11_1_X, needed for HLT TDR. For more details, see the PR description of original PR made to master (11_3_X).

#### PR validation:
runTheMatrix.py -l 23234.0 #2026D49 ttbar (HLT TDR baseline w/ HGCal v11)
Also validated by running EGM phase2 HLT setup in 11_1_7.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Sam-Harper** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- exact backport of #32978 (two minor formatting differences from clang-format are ignored)
- no differences in the tests (none are expected)
- needed for the HLT TDR

**Comment by srimanob** [comment]
+Upgrade

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
