### PR TITLE
[GEOMETRY-UPGRADE] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Use full path to package e.g `$CMSSW_BASE/src` instead of `src`. This change will allow us to run unit tests from their own individual test directories.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
