### PR TITLE
Removed CMS deprecated warnings from RecoTracker/NuclearSeedGenerator

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Removed framework code dependencies from NuclearInteractionFinder  and SeedFromNuclearInteraction.
- Moved away from legacy module type
- Added esConsumes

#### PR validation:

Code compiles and no longer generates the warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36583	ae3c0a6 
- code changes are technical, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
