### PR TITLE
Update L1 tracking for HL-LHC

### PR DESCRIPTION
**Pull request by skinnari**
#### PR description:

This PR includes updates to the L1 tracking for HL-LHC: 
- use DTC emulation (L1Trigger/TrackerDTC), the step between the Tracker and the L1 tracking system, along with associated, necessary changes to the L1 tracking code 
- algorithm updates to match HLS-based version (i.e. firmware)
- code cleanup (removal of obsolete code, general code improvements)

Note:
- this PR must be coupled with an associated update to: https://github.com/cms-data/L1Trigger-TrackFindingTracklet

#### PR validation:

Validated via L1 tracking performance studies on ttbar PU=200 samples. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport.

### CODE REVIEW

**Comment by skinnari** [comment]
FYI @tomalin @aryd

**Comment by mrodozov** [comment]
please test with  cms-data/L1Trigger-TrackFindingTracklet#3

**Comment by silviodonato** [comment]
@skinnari please make a PR to master

**Comment by tomalin** [comment]
The missing file L1Trigger/TrackFindingTracklet/data/memorymodules_hourglass.dat is provided in the separate PR https://github.com/cms-data/L1Trigger-TrackFindingTracklet/pull/3/files

**Comment by skinnari** [comment]
Just to clarify that this is not the issue as the PRs are being tested jointly. The problem is understood and will be fixed along with updated to make the PR to master branch instead.

**Comment by skinnari** [comment]
I have now opened a new PR to master branch instead (#34028) so I am closing this one.

**Pull request closed without merging**
