### PR TITLE
use das_client wrapper instead of das_client python module

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the unit test

```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-08-15-2300/unitTestLogs/JetMETCorrections/Type1MET
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
urgent

**Comment by davidlange6** [comment]
Hi @smuzaffar - it doesn't seem your new labels make it onto the milestone summary pages (eg, list of 81x PRs) - without that they won't be noticed..

**Comment by cvuosalo** [comment]
+1

For #15481 4f0537112ba99fb43e4f889340e9e284955f5c66

Fix a Type1MET unit test by using new das_client. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-15-2300 show no significant differences, as expected. The fixed unit test now succeeds.

**Comment by smuzaffar** [comment]
urgent

**Comment by smuzaffar** [comment]
@davidlange6 , that is because labels were remove (I was only doing the test)  but now I have asked for the urgent label and that should be visible on the milestone page

**Comment by davidlange6** [comment]
ah - thanks!

**Pull request merged**
