### PR TITLE
Adding Cross Trigger Support to E/gamma TnP DQM

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All,

This PR adds cross trigger support to the E/gamma TnP DQM which is used by HLT_Ele28_HighEta_SC20_Mass55  . It also extends the monitoring to the following paths:

HLT_Ele28_HighEta_SC20_Mass55 (both legs)
HLT_Ele50_CaloIdVT_GsfTrkIdT_PFJet165 (electron leg)
HLT_Ele115_CaloIdVT_GsfTrkIdT
HLT_Ele135_CaloIdVT_GsfTrkIdT
HLT_Ele145_CaloIdVT_GsfTrkIdT
HLT_Ele200_CaloIdVT_GsfTrkIdT
HLT_Ele250_CaloIdVT_GsfTrkIdT
HLT_Ele300_CaloIdVT_GsfTrkIdT

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by mtosi** [comment]
I do not see HLT_Ele50_CaloIdVT_GsfTrkIdT_PFJet165 in the list of paths in the silvio google doc ...

**Pull request merged**
