### PR TITLE
Negative and positive C-tagger in 80X

### PR DESCRIPTION
**Pull request by kovitang**
Backport the 81X PR ([#14449](https://github.com/cms-sw/cmssw/pull/14449)) for the signed taggers to 80X.

@mverzett and @imarches are interested in following this

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@kovitang the changes do not affect miniAOD and AOD, right? (I haven't noticed any changes in tests of the 81X version, just double-checking)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14642	e9e910a
- backport of https://github.com/cms-sw/cmssw/pull/14449	f6d59e6 which was integrated in 81X for about a week; the configuration changes are used only in analysis workflows (not in miniAOD or reco)
- jenkins tests pass and comparisons with baseline show no difference

**Comment by kovitang** [comment]
@slava77 The changes do not affect miniAOD and AOD.

**Comment by imarches** [comment]
@kovitang @mverzett some non-related commits have been also pushed to the PR together with the intended fixes, could you please correct this? Thanks

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14642	a4a2d34
- since the last approval, the code was updated https://github.com/cms-sw/cmssw/compare/e9e910a...a4a2d346851a0211d6f9d163c95bc99ab47e08c0 to change selection in pfInclusiveSecondaryVertexFinderNegativeCvsLTagInfos. Code changes in this PR do not affect standard sequences (reco or miniAOD).
- jenkins tests pass and comparisons show no differences

**Pull request merged**
