### PR TITLE
remove 11624.911, #2021 DD4hep from short matrix (until it runs reliably)

### PR DESCRIPTION
**Pull request by slava77**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cvuosalo @civanch

**Comment by silviodonato** [comment]
I agree, I see many fake errors
https://github.com/cms-sw/cmssw/pull/32311#issuecomment-734845434
https://github.com/cms-sw/cmssw/pull/32310#issuecomment-734818210
https://github.com/cms-sw/cmssw/pull/32259#issuecomment-734783602
https://github.com/cms-sw/cmssw/pull/32307#issuecomment-734753972
https://github.com/cms-sw/cmssw/pull/29553#issuecomment-734684492
https://github.com/cms-sw/cmssw/pull/32302#issuecomment-734457165
https://github.com/cms-sw/cmssw/pull/31719#issuecomment-734355338

**Comment by slava77** [comment]
we are still exercising this workflow in IBs twice a day.
So, we are not going to be ignoring the DD4HEP workflows.

**Comment by silviodonato** [comment]
please test

**Comment by smuzaffar** [comment]
please test with #32307
we need to get https://github.com/cms-sw/cmssw/pull/32307 in to fix the clang errors.

**Comment by silviodonato** [comment]
merge

**Pull request merged**
