### PR TITLE
ES DQM fix to the number of good rechits 

### PR DESCRIPTION
**Pull request by cmkuo**
this is to fix a bug when counting the number of good ES rechits

### CODE REVIEW

**Comment by lgray** [comment]
@cmkuo this PR doesn't depend on the MiniAOD changes. Please do something like:
```
git rebase -i --onto CMSSW_7_4_X_2015-08-16-2300 mydev_74x_ESDQM~1 mydev_74x_ESDQM
git push my-cmssw mydev_74x_ESDQM -f
```

To separate this pull request from the MiniAOD changes.
Also, please make forward ports (after you rebase) to 75X and 76X.

Thanks!

**Comment by slava77** [comment]
-1
please rebase as suggested, the reco signature will not be needed after that

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmkuo please make forward ports of this to CMSSW_7_5_X and CMSSW_7_6_X

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
@cmkuo could you also push this change to 75 and 76x?

**Comment by lgray** [comment]
@cmkuo Can you please forward port this change to 75 and 76x? Thanks!

**Comment by danduggan** [comment]
please test

**Comment by lgray** [comment]
@danduggan DAS is being spammed right now as far as I can tell. Tests likely to fail, might be better a few hours from now.

**Comment by danduggan** [comment]
thanks @lgray for the head's up, i'll refrain from triggering tests for now

**Comment by danduggan** [comment]
please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmkuo Backports?

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
