### PR TITLE
Implement framework modules for EventID-related tests

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement additional framework modules used to test and validate the behaviour of the MPI-based modules developed in #32632:
  - `EmptySourceFromEventIDs` is a variation of the `EmptySource` that creates runs, lumis and events (containing no products) based on the list of `EventID`s provided in the configuration;
  - `edmtest::EventIDProducer` reads the `EventID` from the current event and copies it into the `Event` as a data product;
  - `edmtest::EventIDValidator` reads the `EventID` from the current event and compares it to a data product read from the `Event`.

`EmptySourceFromEventIDs` can be used to test how a module reacts to arbitrary transitions.

`EventIDProducer` and `EventIDValidator` can be used to validate that an object produced in a given event is being read back in the same event.

#### PR validation:

The unit tests for the new modules pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Ops, a file seems to be missing.

**Comment by fwyzard** [comment]
`FWCore/Framework/interface/GenericProduct.h` is still a draft, suggestions are welcome.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@makortel I removed the code about generic products.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803 and https://github.com/cms-sw/cmssw/issues/46416

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
