### PR TITLE
Phase2-sim145 Study the difference in SD's between DDD and DD4hep for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Study the difference in SD's between DDD and DD4hep for Phase2 scenarios

#### PR validation:

Compare the CDs and Touchables between DDD and DD4hep using the scripts in SimG4Core/PrintGeomInfo

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@perrotta @rappoccio Please merge this PR

**Comment by perrotta** [comment]
@bsunanda what about moving the txt data into a cms-data repository instead? They are about 160 kB overall...

**Comment by makortel** [comment]
> what about moving the txt data into a cms-data repository instead? They are about 160 kB overall...

Are they needed in a repository at all? (or conversely, can they be easily regenerated?) Their use is not immediately clear from the code.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
> * Found files with invalid states

@bsunanda if you squash all commits you can get rid of files with invalid state, and clean up the history

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

This is an addition of extra test

**Comment by perrotta** [comment]
+1

**Pull request merged**
