### PR TITLE
Use esConsumes in TTClusterAssociator and TTClusterBuilder

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061.

#### PR validation:

Matrix workflows `23234.0,35034.0,28234.0,23234.21,23234.103,23234.9,23434.21,34634.0,34634.21,34834.21,35034.21,35034.0,35234.21` succeed when run with https://github.com/cms-sw/cmssw/pull/35588.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Migration to esConsumes PR. No change is expected. PR test runs fine.

**Comment by makortel** [comment]
Ping @cms-sw/l1-l2

**Comment by makortel** [comment]
Ping @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
