### PR TITLE
Phase2-TB76A Enable the TB script to produce meaningful results

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Enable the TB script to produce meaningful results

#### PR validation:

Use the script to get hit results

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Fail workflows do not relate to this PR.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
