### PR TITLE
Phase2-hgx303 Rearrange some of the parameters in the proper class in view of V17 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange some of the parameters in the proper class in view of V17 geometry

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

I assume from the PR test result and PR description, no change is expected from this PR.

**Comment by bsunanda** [comment]
@perrotta, @dpiparo, @qliphy Could you integrate this? This is needed for a second PR already in queue

**Comment by qliphy** [comment]
+1

**Pull request merged**
