### PR TITLE
Enable additional code checks

### PR DESCRIPTION
**Pull request by fwyzard**
### `performance-faster-string-find`:
Optimize calls to std::string::find() and friends when the needle passed is a single character string literal.

### `performance-for-range-copy`:
Finds C++11 for ranges where the loop variable is copied in each iteration but it would suffice to obtain it by const reference.

### `performance-implicit-conversion-in-loop`:
This warning appears in a range-based loop with a loop variable of const ref type where the type of the variable does not match the one returned by the iterator. This means that an implicit conversion happens, which can for example result in expensive deep copies.

### `performance-inefficient-algorithm`:
Warns on inefficient use of STL algorithms on associative containers.

### `performance-inefficient-vector-operation`:
Finds possible inefficient std::vector operations (e.g. push_back, emplace_back) that may cause unnecessary memory reallocations.

### `performance-move-const-arg`:
Warn about inefficient use of std::move, and suggest a fix that removes it.

### `performance-unnecessary-copy-initialization`:
Finds local variable declarations that are initialized using the copy constructor of a non-trivially-copyable type, where it would suffice to obtain a const reference.

### `performance-unnecessary-value-param`:
Flags value parameter declarations of expensive to copy types that are copied for each invocation, where it would suffice to pass them by const reference.

### `modernize-make-unique`:
Finds the creation of std::unique_ptr objects explicitly calling a new expression, and replaces it with a call to std::make_unique.

### `modernize-loop-convert`:
This check converts for(...; ...; ...) loops to use the new range-based loops in C++11.
The `MinConfidence` option was already set to "reasonable".

### `modernize-use-auto`:
Use the auto type specifier for variable declarations to improve code readability and maintainability.
The `MinTypeNameLength` option is set to 16 characters.

### `modernize-use-emplace`:
The check flags insertions to an STL-style container done by calling the push_back method with an explicitly-constructed temporary of the container element type. In this case, the corresponding emplace_back method results in less verbose and potentially more efficient code.

### CODE REVIEW

**Comment by fwyzard** [comment]
This was spurred by the review of the L1 track trigger code, where some of these checks should really be automated.

I assume some checks will be more controversial than others, and/or run into false positives in our code base, but let's start having a look ...

**Comment by fwyzard** [comment]
@smuzaffar is there a way to make the bot run the code checks using the modified .clang-tidy file ?

**Comment by slava77** [comment]
> I assume some checks will be more controversial than others, and/or run into false positives in our code base, but let's start having a look ...

as in the past, it may be more effective to make a PR with code changes for some selected "representative" package or subsystem so that others could comment.

**Comment by fwyzard** [comment]
Indeed - `clang-tidy` has been working on it for a while now...

**Comment by fwyzard** [comment]
#29863 shows all the code changes from these additions, generated with
```bash
scram b -j`nproc` llvm-ccdb
cat $CMSSW_BASE/compile_commands.json | grep '"file"' | cut -d'"' -f4 | xargs $(scram tool tag llvm LLVM_BASE)/share/clang/run-clang-tidy.py -header-filter "$CMSSW_BASE/src/.*" -j`nproc` -fix -format
```

I can generate smaller change sets (e.g. for a single package or subsystem, or only some of the options) if needed.

**Comment by makortel** [comment]
Thanks @fwyzard, by quick look on random files in #29863 the new options look pretty good to me. 

For deployment I would nevertheless consider to split the set of options into two: straightforward ones, and the ones where the output is more subjective. To me `modernize-loop-convert` and `modernize-use-auto` are in the latter category (not all loops that by eye could be converted to range-for are converted, and the `MinTypeNameLength` may rise some discussion). The "straightforward options" could be deployed "immediately" (expecting trivial review), and the less-straightforward ones in a second pass (with possibly less trivial review).

We could anyway discuss this in the next core software meeting.

**Comment by fwyzard** [comment]
> We could anyway discuss this in the next core software meeting.

I agree... also, the PR as is now is pretty huge, I might split the commits by option and/or by package.

**Comment by makortel** [comment]
> > We could anyway discuss this in the next core software meeting.
> 
> I agree... also, the PR as is now is pretty huge, I might split the commits by option and/or by package.

Right, at least for deployment it needs to be split up (perhaps with the aid of @cmsbuild? at least for the "straightforward options").

**Comment by fwyzard** [comment]
Here are the PRs for the individual additions:
  - [#29926](https://github.com/cms-sw/cmssw/pull/29926): [`performance-faster-string-find`](https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html)
  - [#29927](https://github.com/cms-sw/cmssw/pull/29927): [`performance-for-range-copy`](https://clang.llvm.org/extra/clang-tidy/checks/performance-for-range-copy.html)
  - [#29928](https://github.com/cms-sw/cmssw/pull/29928): [`performance-implicit-conversion-in-loop`](https://clang.llvm.org/extra/clang-tidy/checks/performance-implicit-conversion-in-loop.html)
  - [#29929](https://github.com/cms-sw/cmssw/pull/29929): [`performance-inefficient-algorithm`](https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-algorithm.html)
  - [#29930](https://github.com/cms-sw/cmssw/pull/29930): [`performance-inefficient-vector-operation`](https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-vector-operation.html)
  - [#29931](https://github.com/cms-sw/cmssw/pull/29931): [`performance-move-const-arg`](https://clang.llvm.org/extra/clang-tidy/checks/performance-move-const-arg.html)
  - [#29932](https://github.com/cms-sw/cmssw/pull/29932): [`performance-unnecessary-copy-initialization`](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-copy-initialization.html)
  - [#29933](https://github.com/cms-sw/cmssw/pull/29933): [`performance-unnecessary-value-param`](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html)
  - [#29934](https://github.com/cms-sw/cmssw/pull/29934): [`modernize-make-unique`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html)
  - [#29935](https://github.com/cms-sw/cmssw/pull/29935): [`modernize-loop-convert`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html)
  - [#29936](https://github.com/cms-sw/cmssw/pull/29936): [`modernize-use-auto`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html)
  - [#29937](https://github.com/cms-sw/cmssw/pull/29937): [`modernize-use-emplace`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)

**Comment by kpedro88** [comment]
For posterity: in a future update, it would also be nice to include https://reviews.llvm.org/D54943 (const correctness, still in development) once it's finished, approved, and validated/stable.

**Pull request closed without merging**
