### PR TITLE
Run2-hcx179 Fix a bug for HcalDetId which affects DQM of calibration channels

### PR DESCRIPTION
**Pull request by bsunanda**
Back port from PR bsunanda:Run2-hcx173 which is integrated with 10_2_X Master

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , why some differences in DQM exist in run-1 and FastSim WFs?

**Comment by bsunanda** [comment]
I do not know what is the issue for FastSim. For DQM it might cause some changes because the problem was detected for DQM jobs for real data

**Comment by bsunanda** [comment]
@civanch Could you please approve this? Any way this is indeed a bug fix and it is useful for some processing of low lump data

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @civanch @kpedro88 this is the fist commit for 8_0_X I think I see since the beginning of the year. What is the use case for it? In any case this looks to change in a backward incompatible change the HCAL DetId behaviour

**Comment by bsunanda** [comment]
Salavat can justify this. There was a bug in the DetId code for Hcal which causes issues in the treatment of special data. This affected processing of run H and some of the luminosity blocks were skipped to avoid this. It certainly changes behavior - but in the right way. It does not affect the standard detector cells like HB, HE, HO and HF.

**Comment by abdoulline** [comment]
Indeed, this is a fix to get correct treatment of calibration channels 
(only, no physics readouts affected).
At the moment we agreed with production people to remove crash (HCAL 
DQM) causing LS by hand from 80X re-processing of 2016H, but better to have 
this fix in place...

**Comment by bsunanda** [comment]
This does not affect simulation because simulation is not supposed to create calibration channels for HCAL

**Comment by fabiocos** [comment]
+1

**Pull request merged**
