### PR TITLE
80X HLT update after-MD3 train

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
80X HLT update after-MD3 train

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@rekovic @mulhearn 
I really can't understand why I can NOT get rid of the change to L1Trigger/L1TGlobal/data,
to avoid needing your signature.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@rekovic @mulhearn 
Can you please sign this PR for L1?

Thanks!

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Can this be merged asap please?
Production workflows are unaffected by construction!
Thanks
Martin

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Recreated based on 8_0_21.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
