### PR TITLE
Replace Geometry_cff with GeometryDB_cff in RecoHI

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoHI configuration 2 files are fixed.
```
RecoHI/HiEgammaAlgos/test/testSpike_cfg.py
RecoHI/HiJetAlgos/test/testRegionalJetTracking_cfg.py
```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@mandrenguyen do you think these configs can be deleted?

**Comment by mandrenguyen** [comment]
@jpata  Yes, I believe these can safely be deleted.

**Comment by jpata** [comment]
> Yes, I believe these can safely be deleted.

@jeongeun maybe you can update this PR to delete this configs, instead. Thanks!

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- delete outdated files

**Comment by perrotta** [comment]
+1

**Pull request merged**
