### PR TITLE
[14_1_X] Add WF for 2024 PbPb skim

### PR DESCRIPTION
**Pull request by youyingli**
backport of #46589

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflows 143.201,143.202
What happened here?  The backport was merged already last week.

**Comment by youyingli** [comment]
> please test workflows 143.201,143.202 What happened here? The backport was merged already last week.

If I remember correctly, the WF should only be added in 14_2_X. Here is the backport to 14_1_X.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
