### PR TITLE
migrate modules used by the HLT menu to multithreading (L1) (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
backport #10956 to 75x

### CODE REVIEW

**Comment by fwyzard** [comment]
tracked at #10965

**Comment by Dr15Jones** [comment]
please test

**Comment by fwyzard** [comment]
hi @mulhearn , is there anything holding this up ?

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
