### PR TITLE
synch heavy-ion customizations with 80X

### PR DESCRIPTION
**Pull request by mandrenguyen**
Synchonize w/ PR #15048 , as requested by @slava77

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
Sorry about the failed test... trying to do too many things at once.  Should be ok now

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15056	a6384fb
- renames customisePPwithHI to customisePPrecoForPeripheralPbPb and introduces customisePPrecoforPPb, which doesn't have the modifyClusterLimits call; the method is to be used on top of pp scenario configs for different types of inputs. These functions are not used in standard workflows.
- jenkins tests pass
- the new method was tested already in 75X

**Comment by davidlange6** [comment]
+1

**Pull request merged**
