### PR TITLE
[14_0] Add L1TCaloLayer1Summary and necessary changes to emulator

### PR DESCRIPTION
**Pull request by max-zhao0**
#### PR description:

Backport of [45605](https://github.com/cms-sw/cmssw/pull/45605) for use on online release.

#### PR validation:

Validated locally on CMSSW_14_0_12, running DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py modified for testing on lxplus. Validated also with online DQM playback test.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [45605](https://github.com/cms-sw/cmssw/pull/45605). Backporting is necessary for running on online release.

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #45605

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by max-zhao0** [comment]
@antoniovagnerini, @epalencia, @nothingface0, @rvenditti, @syuvivida. All tests are passing now, and the PR has been validated with an online DQM playback test. Please review this PR and [45605](https://github.com/cms-sw/cmssw/pull/45605), with the same changes, when you get a chance. Thank you.

**Comment by syuvivida** [comment]
+1

**Comment by tjavaid** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
