### PR TITLE
Update doc string for Ele and Pho cutBased

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

Minor (but useful) change in the documentation of the `Electron_cutBased`  and `Photon_cutBased` variables to document the usage of the nested IDs cutBased variables more clearly. 

#### PR validation:

No validation needed.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport needed - targeting Nano v15. Sorry for the delay!

### CODE REVIEW

**Comment by afiqaize** [comment]
enable nano

**Comment by afiqaize** [comment]
please test

**Comment by afiqaize** [comment]
type egamma

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
