### PR TITLE
Add `--nEvents` option to `runTheMatrix.py`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR proposes a solution for those as lazy as me that would like to produce more than `10` events with `runTheMatrix.py` without having to manually edit the configs or use `--command="-n 100"`. It adds a `--nEvents` option for the script to overwrite the standard number of events. It's not really needed , given the `--command` option, but it's slightly cleaner (no double `-n` in the `cmsDriver.py`) and since I had already spent the time needed to have it working I'm making it public to be reviewed. 

#### PR validation:

Tested with a random workflow `runTheMatrix.py -l 12540.0 -w upgrade -t12 --dryRun --nEvents 100` that outputs:

```
Preparing to run 12540.0 Psi2SToJPsiPiPi_14TeV+2023

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py Psi2SToJPsiPiPi_14TeV_TuneCP5_pythia8_cfi  -s GEN,SIM -n 100 --conditions auto:phase1_2023_realistic --beamspot Realistic25ns13p6TeVEarly2022Collision --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 45000,500 --fileout file:step1.root  --nThreads 12 > step1_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step2  -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2023 --conditions auto:phase1_2023_realistic --datatier GEN-SIM-DIGI-RAW -n 100 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --filein  file:step1.root  --fileout file:step2.root  --nThreads 12 > step2_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2023_realistic --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO -n 100 --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --geometry DB:Extended --era Run3 --filein  file:step2.root  --fileout file:step3.root  --nThreads 12 > step3_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step4  -s HARVESTING:@standardValidation+@standardDQM+@ExtraHLT+@miniAODValidation+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2023_realistic --mc  --geometry DB:Extended --scenario pp --filetype DQM --era Run3 -n 100  --filein file:step3_inDQM.root --fileout file:step4.root  > step4_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step5  -s ALCA:SiPixelCalSingleMuonLoose+SiPixelCalSingleMuonTight+TkAlMuonIsolated+TkAlMinBias+MuAlOverlaps+EcalESAlign+TkAlZMuMu+TkAlDiMuonAndVertex+HcalCalHBHEMuonProducerFilter+TkAlUpsilonMuMu+TkAlJpsiMuMu+SiStripCalMinBias --conditions auto:phase1_2023_realistic --datatier ALCARECO -n 100 --eventcontent ALCARECO --geometry DB:Extended --filein file:step3.root --era Run3 --fileout file:step5.root  --nThreads 12 > step5_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 
12540.0_Psi2SToJPsiPiPi_14TeV+2023 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Tue Apr  4 09:23:58 2023-date Tue Apr  4 09:23:58 2023; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

```

while the original `runTheMatrix.py -l 12540.0 -w upgrade -t12 --dryRun` is untouched:

```
Preparing to run 12540.0 Psi2SToJPsiPiPi_14TeV+2023

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py Psi2SToJPsiPiPi_14TeV_TuneCP5_pythia8_cfi  -s GEN,SIM -n 10 --conditions auto:phase1_2023_realistic --beamspot Realistic25ns13p6TeVEarly2022Collision --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 45000,500 --fileout file:step1.root  --nThreads 12 > step1_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step2  -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2023 --conditions auto:phase1_2023_realistic --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --filein  file:step1.root  --fileout file:step2.root  --nThreads 12 > step2_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2023_realistic --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO -n 10 --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --geometry DB:Extended --era Run3 --filein  file:step2.root  --fileout file:step3.root  --nThreads 12 > step3_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step4  -s HARVESTING:@standardValidation+@standardDQM+@ExtraHLT+@miniAODValidation+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2023_realistic --mc  --geometry DB:Extended --scenario pp --filetype DQM --era Run3 -n 100  --filein file:step3_inDQM.root --fileout file:step4.root  > step4_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Matrix_Events/cmssw/src dryRun for 'cd 12540.0_Psi2SToJPsiPiPi_14TeV+2023
 cmsDriver.py step5  -s ALCA:SiPixelCalSingleMuonLoose+SiPixelCalSingleMuonTight+TkAlMuonIsolated+TkAlMinBias+MuAlOverlaps+EcalESAlign+TkAlZMuMu+TkAlDiMuonAndVertex+HcalCalHBHEMuonProducerFilter+TkAlUpsilonMuMu+TkAlJpsiMuMu+SiStripCalMinBias --conditions auto:phase1_2023_realistic --datatier ALCARECO -n 10 --eventcontent ALCARECO --geometry DB:Extended --filein file:step3.root --era Run3 --fileout file:step5.root  --nThreads 12 > step5_Psi2SToJPsiPiPi_14TeV+2023.log  2>&1
 
12540.0_Psi2SToJPsiPiPi_14TeV+2023 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Tue Apr  4 09:25:20 2023-date Tue Apr  4 09:25:20 2023; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- relvals_opts = -w upgrade,  --nEvents 11

**Comment by AdrianoDee** [comment]
test parameters:
- relvals_opts = --nEvents 11

**Comment by mmusich** [comment]
this looks a very useful addition. @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 please review.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
