### PR TITLE
fix ipython and pylint unit tests

### PR DESCRIPTION
**Pull request by smuzaffar**
With new py3 version of ipython and pylint, the executables are bash scripts [a] which run itself under python. Running it with `python3 $(shell which ipython3) -h` works as in this case python3 correctly runs the tool but running it with ` ipython3 -h` fails due to relocation issues. https://github.com/cms-sw/cmsdist/pull/6673 should fix the relocation issue and we should be able to directly run `ipython3`.

[a]
```
#!/bin/sh
'''exec' /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_3_0_pre3-slc7_amd64_gcc900/build/CMSSW_11_3_0_pre3-build/slc7_amd64_gcc900/external/python3/3.8.2-bcolbf/bin/python3 "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from IPython import start_ipython
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with  cms-sw/cmsdist#6673

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6673

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy can we merge this
FYI @cms-sw/analysis-l2

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
