### PR TITLE
Update of Exotica HLT validation monitored paths and removal of l1MET from code

### PR DESCRIPTION
**Pull request by borzari**
#### PR description:

Updated the Exotica HLT validation monitored paths based on more recent information from EXO/LLP claimed HLT paths for Run 3 as described in [EXOTICATriggerValidation](https://twiki.cern.ch/twiki/bin/view/CMS/EXOTICATriggerValidation#Updates_on_the_Exotica_HLT_valid) , and modified some of the generated histograms binning to fit the updated paths. Deleted very outdated paths that were commented to clean the code. Histograms related to paths not claimed are not created anymore, and histograms related to paths that were claimed but were not being monitored will be added.

Completely removed variable l1MET from the code, as it was not used in the validation (since it was not being produced as described in #36916), and, after the changes in #36916, configuration file [hltExoticaValidator_cfg.py](https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Exotica/test/hltExoticaValidator_cfg.py) could not be executed due to the usage of a non existing label `l1METLabel` in [hltExoticaMETplusTrack_cff.py](https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Exotica/python/analyses/hltExoticaMETplusTrack_cff.py).

#### PR validation:

Checked removed and added paths histograms using RelVal datasets, and everything is as expected.

When commented label `l1METLabel` in [hltExoticaMETplusTrack_cff.py](https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Exotica/python/analyses/hltExoticaMETplusTrack_cff.py), the configuration file [hltExoticaValidator_cfg.py](https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Exotica/test/hltExoticaValidator_cfg.py) worked normally again, but the execution of command `runTheMatrix.py -l limited -i all --ibeos -t 8` for validation, exhibited several failing workflows as shown in [1]. Upon removing l1MET from code, execution of `runTheMatrix.py -l limited -i all --ibeos -t 8` exhibit a failure in workflow 2018.1 with ret= 35072 (is this a memory issue only?) [2]. After running command `runTheMatrix.py -l 2018.1 -t 8`, got no failures [3].

### CODE REVIEW

**Comment by borzari** [comment]
Adding `runTheMatrix.py` logs that are not in the first comment:

[1] [runall-report-step123-all_commentedl1METlabel.log](https://github.com/cms-sw/cmssw/files/8223229/runall-report-step123-all_commentedl1METlabel.log)
[2] [runall-report-step123-all.log](https://github.com/cms-sw/cmssw/files/8223228/runall-report-step123-all.log)
[3] [runall-report-step123-2018p1.log](https://github.com/cms-sw/cmssw/files/8223227/runall-report-step123-2018p1.log)

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@borzari  can you please check if the changes are as expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-10-1100+40cf77/48858/dqm-histo-comparison-summary.html
Thanks

**Comment by borzari** [comment]
@jfernan2 in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-10-1100+40cf77/48858/dqm-histo-comparison-summary.html I see that there are some categories of the validation that are not there. Could this be expected due to the small number of events in these workflows? In my local tests I have all the categories/histograms that are expected after the changes, even some that have no monitored paths inside.

**Comment by jfernan2** [comment]
That link only shows the differences in the DQM GUI at the DQM output from the changes of your PR w.r.t. baseline
For the full DQM root output you should look into:
Baseline: https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_12_3_X_2022-03-10-1100/slc7_amd64_gcc10/-GenuineIntel/matrix-results/
Baseline+PR: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-40cf77/23016/runTheMatrix-results

**Comment by borzari** [comment]
@jfernan2, sure. Sorry for not seeing it at first. I am going to check to see if everything is as expected. Thanks!

**Comment by borzari** [comment]
@jfernan2 everything is fine. There is only one path in the DiPhoton category that is in my changes, but that doesn't exist anymore in [HLT_GRun_cff.py](https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/HLT_GRun_cff.py). Should I do a commit to remove it from the code now?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
