### PR TITLE
Add filter for intermediate resonance particles [12_4_X] 

### PR DESCRIPTION
**Pull request by jieunyoo**
add filter for intermediate resonance particles

backport of https://github.com/cms-sw/cmssw/pull/40254 to CMSSW_12_4_X

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40254

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/generators-l2 is there anything that prevents you reviewing this PR? Could you please comment in any case, telling what you are waiting for, or when do you plan to review? (Please take into account that RelValInout errors are unrelated to this PR)

**Comment by Saptaparna** [comment]
Yes, we need to understand the memory issues that the analyst has reported, following their presentation at the GEN meeting, regarding this PR.

**Comment by perrotta** [comment]
> Yes, we need to understand the memory issues that the analyst has reported, following their presentation at the GEN meeting, regarding this PR.

Thank you @Saptaparna 
@jieunyoo could you please link the presentation at the GEN meeting in the PR description: it is always a useful souce of information. And please keep everybody informed of the updates in this thread

**Comment by jieunyoo** [comment]
Also, example of log of recent successful production with asking for 10 events: [here](https://cmsweb.cern.ch:8443/scheddmon/0155/jiyoo/221219_184237:jiyoo_crab_boostedHWWfragmentDec19_1/job_out.1.0.txt)

**Comment by menglu21** [comment]
please test

**Comment by menglu21** [comment]
> @cms-sw/generators-l2 is there anything that prevents you reviewing this PR? Could you please comment in any case, telling what you are waiting for, or when do you plan to review? (Please take into account that RelValInout errors are unrelated to this PR)

if the error is not related to this PR it's fine to let it go

**Comment by menglu21** [comment]
+1

**Comment by perrotta** [comment]
+1
- New filter added as a plugin
- This backport in 12_4_X assumes that this wilter is not needed in the intermediate release cycles 12_5_X and 12_6_X

**Pull request merged**
