### PR TITLE
[CondFormat][clang-tidy] Fix readability-container-size-empty warnings

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR should fix the clang-tidy readability-container-size-empty  warnings [a] which are not automatically fixed by clang-tidy as the code is in a macro.

```
CondFormats/EcalObjects/src/EcalSRSettings.cc:48:3: warning: the 'empty' method should be used to check for emptiness instead of 'size' [readability-container-size-empty]
  SR_VPRINT(deltaEta);
  ^
CondFormats/EcalObjects/src/EcalSRSettings.cc:19:7: note: expanded from macro 'SR_VPRINT'
  if (val.a##_.size())                            \
      ^
gcc/9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/stl_vector.h:1004:7: note: method 'vector'::empty() defined here
      empty() const _GLIBCXX_NOEXCEPT
      ^

```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
+alca

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
