### PR TITLE
Winter16 jetID update to include lepton veto - backport to 102X

### PR DESCRIPTION
**Pull request by knash**
Backport of #25306 to 10_2_X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@knash , please update the title of this PR with something more meaningful

**Comment by slava77** [comment]
backport of #25306

to add a label
looks like capitalization matters for the bot

**Comment by slava77** [comment]
> @knash , please update the title of this PR with something more meaningful

ping

there is an "Edit" button at the top of the page in  the web interface

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25608	103e4d5
- changes are the same as in the master branch version ( https://github.com/cms-sw/cmssw/pull/25306 87c06cc), which was merged In Nov '18.
- from notes in #25306 
    - fixes are provided for existing features in non-standard configurations
    - new WINTER16 TIGHTLEPVETO ID is introduced
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by fabiocos** [comment]
@peruzzim @fgolf as agreed we are going to merge this

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
