### PR TITLE
Short Matrix Update And Documentation

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Having checked with experts, this PR proposes to change the wfs we run in the short matrix. 

__Additions__

-  Run3 (2023) ZEE MC;
- Run2023D ZeroBias and EGamma data;
- Run2022B/C/D ZeroBias data.

__Removals__: 
- 2021 express and prompt 2021;
- X.914 (since DB is already the default);
- X.911 (mostly for XML checks, could be run in the IB tests only). 

This is just a first round of changes. Iteratively I will check if we can remove/add other wfs. 

I took the chance to a table in the `runTheMatrix.py` README as a form of documentation of what we run. And some comments in `runTheMatrix.py`  itself.

#### PR validation:

None

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by makortel** [comment]
Should something from 2021 data be kept? Or is 139.001 enough? (not sure what "offline with HLT step" means exactly)

I don't see anything for 2022 data, maybe it would be worth to have one re-reco workflow for 2022 data?

Just to note that after removing 11634.911 we can pretty much close https://github.com/cms-sw/cmssw/issues/35109 (without finding the cause, but I'm not against removing it).

**Comment by AdrianoDee** [comment]
> I don't see anything for 2022 data, maybe it would be worth to have one re-reco workflow for 2022 data?

Yes indeed for 2022 would makes sense to have something. For 2021 there's not much in the release in general. The `Express` I removed I don't know how much is useful for PR testing. The only extra one I would consider is `139.002` that is 2021 `ZeroBias`.

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Thanks Phat,

> By the way, could you please elaborate more on a motivation to add Run3 (2023) ZEE in the short matrix?

I have the feeling that this could have helped spotting at PR level the whole ECAL cc timing ... problem.

**Comment by AdrianoDee** [comment]
> OK. I am not sure we should spend more time on PR test with this workflows. But you and ECAL knows better if we should test it in every workflows. We can always enable it and the comparison will be made.

Let's see how longer it takes with the extra workflow. It this is not that much I would keep the new ones. @cms-sw/core-l2 do you have any suggestion/feeling on that?

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
