### PR TITLE
[106X] NanoAOD: add flag to keep all PS weights

### PR DESCRIPTION
**Pull request by swertz**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #31276 for nanoAOD productions in 106X

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

backport inline with master version

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by mariadalfonso** [comment]
@swertz 
can you backport this also to 10_2 ?
this is functional to restart the [NMSSM_XToYHTo4b](https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIIFall17NanoAODv7-0*&dataset_name=*NMSSM_XToYHTo4b_MX-*_TuneCP5_13TeV-madgraph-pythia8*&page=0&shown=4294967423 )currently crushing

thanks
@agrohsje

**Comment by swertz** [comment]
Ok sure!

**Pull request merged**
