### PR TITLE
Backport of #11022: Make surface deformation plots much faster

### PR DESCRIPTION
**Pull request by hroskes**
The time it takes to run the validation itself does not change noticeably. The time it takes to make the plots decreases by a lot (<1 minute per curve, down from >~10 minutes per curve). The plots themselves are identical to before.

Also some cleanup of unused templates in alternateValidationTemplates, without losing any functionality.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hroskes** [comment]
@cmsbuild sorry, I found a bug

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@hroskes can we adress the removal of the templates in a separate PR? otherwise we this can be approved.

**Comment by hroskes** [comment]
ok, I can make a separate PR... but it's already approved in 75 and 76

**Comment by mmusich** [comment]
ah! nevermind, @diguida approved it...

**Comment by mmusich** [comment]
+1

**Pull request merged**
