### PR TITLE
Modernize `CondCore/DBOutputService` test stubs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

* Part of the campaign for https://github.com/cms-AlCaDB/AlCaTools/issues/28
* Also included the header files in the cc files
* Moved everything to a `one` module

Everything uses `cout`... and there is a lot of commented out code...  but it's under test and also I'm not the owner of the code, so I didn't remove any commented code.

#### PR validation:

Code compiles and `scramv1 b runtests runs` fine

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ggovi** [comment]
+db

**Comment by francescobrivio** [comment]
+alca

 - in line with PR description
 - jenkins tests pass fine

**Comment by qliphy** [comment]
+1

**Pull request merged**
