### PR TITLE
preparing the datamixer for track mixing

### PR DESCRIPTION
**Pull request by lveldere**
use the plugin already in use in the MixingModule to mix tracks in the DataMixingModule 

replaces #8150,
takes out the change in the simulation from #8455

### CODE REVIEW

**Comment by lveldere** [comment]
please test

replaces #8150

**Comment by lveldere** [comment]
error is not related to my pr

**Comment by lveldere** [comment]
please test

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
