### PR TITLE
Bugfix and clean-up of frozen HLT menus (91X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Bugfix and clean-up of frozen HLT menus (91X)
Based on CMSSW_9_1_X_2017-03-15-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
bugfix

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Please integrate for 910pre1.
Thanks!

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Please integrate for 900.
Thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
