### PR TITLE
`CondTools/SiStrip` unit tests: introduce gain rescaler tool in unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, introduce SiStrip APV gain rescaler tool in `CondTools/SiStrip` unit tests, now that issue https://github.com/cms-sw/cmssw/issues/36319 is solved by PR #36533.

#### PR validation:

Run package unit tests with: `scramv1 b runtests_testCondToolsSiStripBuildersReaders`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by tvami** [comment]
Hi @mmusich since https://github.com/cms-sw/cmssw/pull/36490 is merged, shall this one be closed?

**Comment by mmusich** [comment]
>  shall this one be closed?

we could, but this might come in handy for other cases as #36490 in case #36533 doesn't solve the problem.

**Comment by mmusich** [comment]
I have not seen further failures of the unit tests after #36533 was integrated.
I'll profit of this branch to make some further changes (integrate the last test that was postponed since the previous ones were failing).

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
kindly pinging @cms-sw/db-l2

**Comment by francescobrivio** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
