### PR TITLE
Phase2-gex05 Bug fix to Phase2 geometries D49 and higher versions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to Phase2 geometries D49 and higher versions (backport from PR #30579)

#### PR validation:

Tested using runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Back port from #30579

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
