### PR TITLE
Phase2-ft26 Try to define Phase2 scenarios with dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Testing Phase2 scenario with dd4hep

#### PR validation:

Try to test with a cfg file in SimG4Core/Configuration/test. Test is not successful but can be used for debugging dd4hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1
cc: @kpedro88

**Pull request merged**
