### PR TITLE
Avoid use after move in EventProcessor::globalEndLumiAsync()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This was found by the static analyzer.

#### PR validation:

Framework unit tests succeed.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by Dr15Jones** [comment]
+1

This worked before this change because the move operation on our `WaitingTaskHolder` does not reset the `tbb::task_group` pointer it holds, it only resets the task pointer. However, being dependent upon that exact behavior of move is brittle so better to get the address earlier.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
Sorry I signed before the test gets finished. Let's wait for the test results out though.

**Pull request merged**
