### PR TITLE
Run3-gem44 Add a test code which investigates ID issue for GEM

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a test code which investigates ID issue for GEM

#### PR validation:

Ran the test code to verify GEMDetId definition

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@dildick This is the PR which I used to investigate what you reported in #30644

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
