### PR TITLE
HLT menu update to V1.2 (Kerberos) - 92X 

### PR DESCRIPTION
**Pull request by silviodonato**
Backport of #19444 

This is an update of the HLT menu to v1.2 (Kerberos).
It is based on master table: /dev/CMSSW_9_2_0/HLT/V83

This PR has been done on top of #19431

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Based on CMSSW_9_2_4

**Comment by Martin-Grunewald** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
Closing this PR as being superseded by #19468

**Comment by Martin-Grunewald** [comment]
@silviodonato 
As you make this PR, can you please close it (superseded by #19468)?
Thanks!

**Pull request closed without merging**
