### PR TITLE
No vfp30 mitigation in Tracking

### PR DESCRIPTION
**Pull request by VinInn**
This PR restores the performance of Tracking for 25ns and High PU to its design (7_6 like).
CCC back to Loose for iter0 and iter2 Tight elsewhere
No Mitigation of "vfp=30" setting given the new setting to zero 
(
see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiStripHitEffLoss#Preamp_Feedback_Voltage_Bias_VFP
)
This shall be the default for 2017 sim and reco and any performance-driven reco of >=2016G reco.
What to do for 2016-setup given the legacy MC reconstructed with CCC mitigation
to be discussed (customize I suppose)

see performance for usual TTBAR PU35 25ns compared to 810_pre8
http://innocent.home.cern.ch/innocent/RelVal/pu35_81_NoMitigation/plots_highPurity/effandfake1.pdf

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
I'd prefer we make this change in performance after ~1/fb or so collected with the new settings and some more complete feedback provided on the impact.

- if we stay with old (810pre9/pre10) settings we have good enough reco for all data collected so far and expected future. There is a cost of a slight increase in fakes.
- if we switch to the new settings, other periods of data taking will need special settings. (this PR does not provide a solution for the older data).

Given run-dependence, the appropriate adjustments to the tracking selection logic has to be done with condDB. Manual customizations are not an appropriate solution.

**Comment by VinInn** [comment]
the rerun will be with 80X.
The current 81X is a clear worsening of the performance of the tracker for all SetUps.
TRK-POG has clearly stated that. TRK-POG opposes to any further production with current 81X.
TRK_POG ask this PR to be integrated ASAP to start serious studies for 2017.
Any delay will further delay good physics in CMS.

**Comment by davidlange6** [comment]
seems unlikely to me that the last ever processing of these data are with 80x.

In any case we’l need this to be era driven (also ~urgently for 80x) as to deal with the first 20fb-1 and hopefully the last 20fb-1 of 2016 data, so that might be a good place to start. I propose that I add a “Run2_2016_PostTrkAPVUpdate” era that can be used to (along with the existing 2017 eras.

On Aug 15, 2016, at 8:50 AM, Vincenzo Innocente <notifications@github.com<mailto:notifications@github.com>> wrote:


the rerun will be with 80X.
The current 81X is a clear worsening of the performance of the tracker for all SetUps.
TRK-POG has clearly stated that. TRK-POG opposes to any further production with current 81X.
TRK_POG ask this PR to be integrated ASAP to start serious studies for 2017.
Any delay will further delay good physics in CMS.

**Comment by makortel** [comment]
@davidlange6 The changes can certainly be made era-driven, but I have some questions first.

First 81X. Should `Run2_2016` continue with the HIP mitigation, and `Run2_2016_PostTrkAPVUpdate` disable the mitigation and tighten the CCC as in this PR?

What about 80X? Should `Run2_2016` stay unchanged? Do we continue to enable the "HIP mitigation" with the customize? Or we make `Run2_2016_PreTrkAPVUpdate` (or something) era for the first 20/fb that enables the mitigation?

I'm also thinking the actual sub-era to be added. Do we need/want to customize anything else than tracking with the era (like enabling the HIP simulation)?

Which part of 2016 do we want to flag with the sub-era? First (e.g. sub-era `tracker_apv_vfp30_2016`) or latter (e.g. `tracker_apv_vfp0_2016`)? Of course we can then combine either of these to the `Run2_2016_...` era whichever way, but the choice affects heavily what we keep/put as defaults in the configurations. E.g. `tracker_apv_vfp30_2016` would minimize the knock-on effects on phase1 and phase2 customizations.

Will you do the changes to `Eras.py` first? (in principle it would be nice to be decoupled due to the large number packages depending on `Eras.py`)

**Comment by davidlange6** [comment]
On Aug 15, 2016, at 10:40 AM, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> The changes can certainly be made era-driven, but I have some questions first.

First 81X. Should Run2_2016 continue with the HIP mitigation, and Run2_2016_PostTrkAPVUpdate disable the mitigation and tighten the CCC as in this PR?

What about 80X? Should Run2_2016 stay unchanged? Do we continue to enable the "HIP mitigation" with the customize? Or we make Run2_2016_PreTrkAPVUpdate (or something) era for the first 20/fb that enables the mitigation?

I'm also thinking the actual sub-era to be added. Do we need/want to customize anything else than tracking with the era (like enabling the HIP simulation)?


Yes (not sure it will be needed in the end) - indeed, for the MC there is an interesting decision to take about what configuration(s) to use..

Which part of 2016 do we want to flag with the sub-era? First (e.g. sub-era tracker_apv_vfp30_2016) or latter (e.g. tracker_apv_vfp0_2016)? Of course we can then combine either of these to the Run2_2016_... era whichever way, but the choice affects heavily what we keep/put as defaults in the configurations. E.g. tracker_apv_vfp30_2016 would minimize the knock-on effects on phase1 and phase2 customizations.


I would rather keep the eras we’ve used to take data so far unchanged.

Not sure I follow about the “defaults” - that can be whatever you prefer...

Will you do the changes to Eras.py first? (in principle it would be nice to be decoupled due to the large number packages depending on Eras.py)

let me try to finish that today, yes

**Comment by makortel** [comment]
@davidlange6 

> I would rather keep the eras we’ve used to take data so far unchanged.
> 
> Not sure I follow about the “defaults” - that can be whatever you prefer...

My suggestion for `Eras.py` in 81X would then be along
```
self.tracker_apv_vfp30_2016 = cms.Modifier()
....
self.Run2_2016_PostTrkAPVUpdate = cms.ModifierChain( <previous contents of Run2_2016> )
self.Run2_2016 = cms.ModifierChain( self.Run2_2016_PostTrkAPVUpdate, self.tracker_apv_vfp30_2016)
self.Run2_2017 = cms.ModifierChain( self.Run2_2016_PostTrkAPVUpdate, ...)
self.Run2_2016_trackingLowPU = cms.ModifierChain(self.Run2_2016_PostTrkAPVUpdate, self.trackingLowPU)
```

Point is that (let me try to rephase), that we want to have the contents of this PR as the defaults for tracking, and then customize for the vfp30-mitigation with era.

> let me try to finish that today, yes

That would be good, thanks.

**Comment by VinInn** [comment]
```
Point is that (let me try to rephase), that we want to have the contents of this PR as the defaults for tracking, and then customize for the vfp30-mitigation with era.
```
+1
I do not exclude that we may change the default of "maxCCCLostHits" to "1" to recover localized inefficiency for instance and eventually implement more clever logic now that the single layer efficiency is above 90%.
Still the baseline is 7_6 and we have to restart from that (with two years delay).
The SiStrip will stay in CMS for another 10 years or so.
So step1: restore tracking as we (used to) know it.

**Comment by slava77** [comment]
On 8/15/16 2:38 AM, Matti Kortelainen wrote:
> @davidlange6 <https://github.com/davidlange6>
> 
>     I would rather keep the eras we’ve used to take data so far unchanged.

Better be explicit for the special settings.
We didn't take any data with the 810pre9/10 version of Run2_2016.
So, better not make it a default Run2_2016 for the rest of 81X and later
releases
and make a Run2_2016_HIPM.
I suppose that for rerecos of pre-2016G data in 2016 we will use the
Run2_2016_HIPM.


Also, may I suggest shorter names in the eras.
There is some informal coupling with T0 data processing settings,
which have a limited number of chars to save the configuration scenario
name.
(e.g. Run2_2016_PostAPV or Run2_2016_noHIP )


Please provide some plots supporting that HIP issue in data is now
completely at the level of MC (none at all) and doesn't need to be
mitigated or simulated.

**Comment by davidlange6** [comment]
On Aug 15, 2016, at 2:45 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:

On 8/15/16 2:38 AM, Matti Kortelainen wrote:
> @davidlange6 <https://github.com/davidlange6>
>
> I would rather keep the eras we’ve used to take data so far unchanged.

Better be explicit for the special settings.
We didn't take any data with the 810pre9/10 version of Run2_2016.
So, better not make it a default Run2_2016 for the rest of 81X and later
releases
and make a Run2_2016_HIPM.
I suppose that for rerecos of pre-2016G data in 2016 we will use the
Run2_2016_HIPM.


thats what I suggested, yes.


Also, may I suggest shorter names in the eras.
There is some informal coupling with T0 data processing settings,
which have a limited number of chars to save the configuration scenario
name.
(e.g. Run2_2016_PostAPV or Run2_2016_noHIP )


Please provide some plots supporting that HIP issue in data is now
completely at the level of MC (none at all) and doesn't need to be
mitigated or simulated.

the most definite so far is
https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1633.html

more to come presumably once prompt is fully available for some runs.

**Comment by slava77** [comment]
On 8/15/16 5:49 AM, David Lange wrote:
> Please provide some plots supporting that HIP issue in data is now
> completely at the level of MC (none at all) and doesn't need to be
> mitigated or simulated.
> 
> the most definite so far is
> https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1633.html
> 
> more to come presumably once prompt is fully available for some runs.
> 

The only link with MC is in this part of the message
""
> Agreement with old-good-MC seems to be excellent. 
> https://goo.gl/mqWSQc
> 
""
but it points to a set of plots without a reference.
So, it doesn't let me compare easily.
Maybe there is another link?

**Comment by VinInn** [comment]
Untill we do not get new relval with 2016G easy comparison directly in DQM is not possible.
Kuntal will make a report as soon as Prompt is ready.
you can compare with 2012 (5_3?) as done by Francesco Fiori...
or just compare LS at different InstLumi, or different BX
If there is something to mitigate it has nothing to do with what we have observed so far...

**Comment by slava77** [comment]
On 8/14/16 10:52 AM, Vincenzo Innocente wrote:
> see performance for usual TTBAR PU35 25ns compared to 810_pre8
> http://innocent.home.cern.ch/innocent/RelVal/pu35_81_NoMitigation/plots_highPurity/effandfake1.pdf
> 
> ------------------------------------------------------------------------


Is the plot vs eta made with any pt cut?
(at some point I thought that the plots vs.not-pt are made for pt>0.9 GeV)
The plot vs pt suggests that all increase in fakes is below pt ~ 0.7 GeV.
Is this correct?

The impact of fakes is then pretty limited.

**Comment by makortel** [comment]
@slava77 

> Is the plot vs eta made with any pt cut?

The fake rate (and duplicate and pileup) plots are without any cuts on tracks (or TrackingParticles).

> (at some point I thought that the plots vs.not-pt are made for pt>0.9 GeV)

This is correct for **efficiencies** vs. something-else-than-pT (and the cut is on TrackingParticles).

**Comment by VinInn** [comment]
and it is most probably a migration from eff to fake due to additional hits...
In any case my point is that we should restore first  the state where we were and start from scratch.
Each decision should be taken with a clear objective in mind given the current status of the detector, not because was introduced to solve an obsolete issue and we leave it there because damage is pretended to be limited...
We can then (re-)start discussion about CCC, MC vs Data, value of low-pt, detached-vertices, etc
 on clear ground and possibly clear objective (including timing and memory at PU=50).

**Comment by slava77** [comment]
It's clear to me that we should go back to the state of pre8 (essentially what we are running now in 80X for data taking and all MC).
That's somewhat trivial.

Undoing the looser CCC settings made in 76X is a less trivial step, maybe partly due to the state of it being validated and that we are at the end of the release cycle.
Also, it looks like we better wait for prompt reco to see consistent picture and be able to compare with MC.
Starting from scratch in pre11 doesn't sound good (especially considering that the effects of looser CCC on fakes are rather tiny for most of the pt range and even for lower pt they may be an artifact of the fake definition logic).

**Comment by VinInn** [comment]
Sorry @slava77 , not sure what you are talking about: declaring inactive TOB1 if no his are found for candidate trajectory having a local pt>0.9 is a pure random nonsense that need to be evicted from the code asap. It is pure panic code, with no justification but "sorry we do not understand how our detector work"!

**Comment by slava77** [comment]
On 8/15/16 10:49 AM, Vincenzo Innocente wrote:
> Sorry @slava77 <https://github.com/slava77> , not sure what you are
> talking about: declaring inactive TOB1 if no his are found for candidate
> trajectory having a local pt>0.9 is a pure random nonsense that need to
> be evicted from the code asap. It is pure panic code, with no
> justification but "sorry we do not understand how our detector work"!


Not all of the HIP mitigation is for TOB1.

If there is no support to keep this somewhat awkward but more robust
setup in,
we can go ahead with what was discussed in this thread earlier.
New customization to set processing with HIPM and corresponding eras are
to be defined
so that the 2016 and 2015 relvals are reconstructed appropriately.
It should be a part of this PR (or a replacement PR).

**Comment by slava77** [comment]
@VinInn 
is this change from "&&" to "||" still considered a bugfix 
https://github.com/cms-sw/cmssw/pull/15114/commits/d5168db349792cf8631723bdfcb924d55d81e6b9
or is it a part of mitigation that should be disabled?

If it's a bugfix, is it essential enough to put it in 80X?
If, instead, it's a part of ad hoc mitigation, then it should probably be reverted with this PR as well.

**Comment by VinInn** [comment]
I think I was very clear in my previous PRs: it is a bugfix.

**Comment by slava77** [comment]
On 8/18/16 12:06 AM, Vincenzo Innocente wrote:
> I think I was very clear in my previous PRs: it is a bugfix.

Do we have MTV plots for this alone?
I think the case without HIP is enough.

If the effect is small, 80X version without HIP mitigation can remain
unchanged.

**Comment by VinInn** [comment]
is in the 80X PR itself

**Comment by slava77** [comment]
On 8/18/16 5:34 AM, Vincenzo Innocente wrote:
> is in the 80X PR itself

Indeed
https://github.com/cms-sw/cmssw/pull/15251#issuecomment-234536844
" On (ttbar) MC the effect of || -> && at 99281a9 was negligible. "

Looking at the summary
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_8_0_14_pr15251/ttbar_pu_summary.html
the efficiency is epsilon lower and the fake rate is epsilon higher.
Sounds like the effect is negligible, but it shows a negligible degradation.
If I interpreted the numbers right, this bugfix is not needed in 80X.

**Comment by slava77** [comment]
@VinInn @davidlange6 @makortel 
was there any progress in VPF30 era definition?
This PR can not proceed until tracking settings  for data with VPF30  are defined.

**Comment by makortel** [comment]
I had the impression that @davidlange6 would introduce the new era. On the other hand, given the recent changes in `Eras.py` removing the dependencies on it, I could actually just go a head (with `Run2_2016_HIPM` as suggested in https://github.com/cms-sw/cmssw/pull/15464#issuecomment-239793094, unless somebody comes up with a better name).

**Comment by davidlange6** [comment]
@makortel - please go ahead with adding your Era. Thanks!

**Comment by makortel** [comment]
This PR + era can be found from #15590.

**Comment by slava77** [comment]
-1
superseded by #15590

**Pull request closed without merging**
