### PR TITLE
[HGCAL trigger] Bugfixes

### PR DESCRIPTION
**Pull request by jbsauvan**
The following HGCAL TPG bug fixes are included in this PR:
  * Fix of a regression in trigger towers affecting their position (all towers produced on the positive side)
  * 3D cone clustering fix (minor impact, see comparison [slides](https://github.com/PFCal-dev/cmssw/files/2256960/18.08.01.3D.clustering.fix.pdf))
  * Fix wrong wafer type of cells retrieved from trigger cells

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
