### PR TITLE
Phase2-gex149 Correct the order of Tracker files in some of the scenarios which is relevant for DD4hep application

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the order of Tracker files in some of the scenarios which is relevant for DD4hep application

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
