### PR TITLE
Fix consumes for phase2 premixing and reduce code duplication in EcalDigiProducer

### PR DESCRIPTION
**Pull request by makortel**
The `consumes` for EB/EE/ES `PCaloHit`s is controlled with `doEB`/`doEE`/`doES`, but the `getByLabel()` for signal and pileup events were called for all EB/EE/ES regardless of the `doEX` flags. In phase2 premixing stage2 (in `DataMixingModule`/`PreMixingModule`) these would lead to "get products without calling consumes" exception (I don't know why the regular mixing works), so this PR calls `getByLabel()` only for the enabled subdetectors.

In addition I use the occasion to reduce the duplicated code in the constructors by removing almost everything from one of them and calling the other one from it. This change also fixes a bug in APD simulation that was fixed in #17300 for classical mixing for premixing (I presume this effect won't be seen in PR tests quoting from #17300 "the code that's not used in the standard sequences" (needed only if one wants to simulate ECAL barrel "spike" noise)".

Tested in CMSSW_10_1_X_2018-03-05-2300, no changes expected.

@mdhildreth @kpedro88

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
@makortel , if fix the Producer why not to use GetByToken ?

**Comment by makortel** [comment]
@civanch I'd prefer to leave that to the code authors.

**Comment by kpedro88** [comment]
@civanch I think there's some reason for this having to do with pileup mixing, but don't remember exactly.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
> I think there's some reason for this having to do with pileup mixing, but don't remember exactly.

AFAIK `getByToken()` could be done for the signal `Event`, but not for the pileup `PileUpEventPrincipal` (actually wouldn't make much sense for the latter as the `*MixingModule` owns the source of them so there can't be any other clients).

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
