### PR TITLE
miscellaneous code improvements from review of #42683

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, addresses https://github.com/cms-sw/cmssw/pull/42683#pullrequestreview-1604281578

#### PR validation:

`cmssw` compiles.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1005.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- Given the modifications applied here to the code, the differences wrt baseline for wf 12434.7 look like another incarnation of https://github.com/cms-sw/cmssw/issues/3980

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
