### PR TITLE
EventSetup consumes migration 1 GEM module and 1 L1T module

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

EventSetup consumes migration for 2 modules,
GEMRawToDigiModule and
L1TMuonOverlapTrackProducer

Also migrated helper classes used by L1TMuonOverlapTrackProducer.

Also a little cleanup related to the includes and forward declarations.
Also cleanup, removed a data member containing an unnecessary
copy of the module's ParameterSet.

#### PR validation:

Should not change output. Relies on existing tests.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
please test
(to refresh them)

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass and show no (relevant) differences

**Comment by silviodonato** [comment]
+1

**Pull request merged**
