### PR TITLE
remove unsupported 2023 geometries

### PR DESCRIPTION
**Pull request by kpedro88**
Several 2023 geometries are no longer supported:
- 2023
- 2023Dev
- 2023Muon

The associated configs have been deleted. Some unit tests may need to be updated correspondingly to use supported geometries, so failures in the first round of tests will not be a surprise.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@bsunanda @calabria - there are a bunch of muon and HGC test configs that load these geometries:
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023_cff
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023Reco_cff
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023Dev_cff
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023DevReco_cff
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023Muon_cff
http://cmslxr.fnal.gov/search?v=CMSSW_8_1_0_pre6&_string=2023MuonReco_cff

It appears that none of these correspond to unit tests, so I am not planning to update them with supported geometries in this PR. If any of them are essential, please let me know.

**Comment by ianna** [comment]
@kpedro88 - please, update CondTools/Geometry. These configurations are used to produce DB payloads.

**Comment by kpedro88** [comment]
@ianna - updated all the ones I could find to use 2023sim, let me know if this is acceptable.

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@ggovi @franzoni please review and sign

**Comment by smuzaffar** [comment]
@kpedro88 , one unit test is referring to these 2023 geometry configurations. Can you please fix those too?
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-06-13-2300/unitTestLogs/RecoLocalCalo/HGCalRecProducers

https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=GeometryExtended2023LRecoReco_cff

**Comment by kpedro88** [comment]
@smuzaffar The 2023LReco geometry was not touched in this PR. That geometry was removed (redundant with 2023sim at the moment) a while ago, I guess the unit test had never been run until now. checkdeps doesn't seem to pick up geometry - unit test config dependencies, so it's difficult to track them down.

**Comment by smuzaffar** [comment]
ah right ... sorry I should have looked closely. GeometryExtended2023**LRecoReco**_cff is not part of files which were touched in this PR.

**Pull request merged**
