### PR TITLE
Add wfs for JetMET PD

### PR DESCRIPTION
**Pull request by sam7k9621**
#### PR description:

Add Run3 skims to the standard relval wfs: 140.119

#### PR validation:

Should be tested on 140.119

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

None

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test workflow 140.119

**Comment by sam7k9621** [comment]
Hi @kskovpen @srimanob    
It seems that it fails because of timeout, could we only test on the used wfs instead?
Something like:
workflows = 140.119
relvals_opt = -w standard

**Comment by srimanob** [comment]
We can just see that the new workflow runs fine,
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1424b1/27576/runTheMatrix-results/140.119_RunJetMET2022D+RunJetMET2022D+HLTRUN3+RECONANORUN3+SKIMJETMETRUN3/

**Comment by srimanob** [comment]
test parameters:
- workflow = 140.119
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by sam7k9621** [comment]
Hi @srimanob , thank you for the quick reply.
We found that only the EXOHighMET skim could not be found under JetMET PD in RunD (can be found under MET in RunC).
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2FRun2022*EXOHighMET*%2F*
However other skims seem to be fine (EXODelayedJetMET, JetHTJetPlusHOFilter).
The 140.119 wfs should report the bug, but it seems to produce the JetMET files successfully.
Could you please let me know what might be wrong?

**Comment by srimanob** [comment]
Hi @sam7k9621 

> We found that only the EXOHighMET skim could not be found under JetMET PD in RunD (can be found under MET in RunC).

This is because Tier-0 configuration does not contain EXOHighMET
https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=357538

```
{
  "run": 357538, 
  "write_miniaod": true, 
  "scram_arch": "el8_amd64_gcc10", 
  "write_aod": true, 
  "write_reco": false, 
  "alca_skim": "HcalCalIsoTrkProducerFilter,TkAlJetHT,HcalCalNoise", 
  "cmssw": "CMSSW_12_4_6", 
  "physics_skim": "EXODelayedJetMET,JetHTJetPlusHOFilter,LogError,LogErrorMonitor", 
  "write_dqm": true, 
  "scenario": "ppEra_Run3", 
  "global_tag": "124X_dataRun3_Prompt_v4", 
  "multicore": 8, 
  "dqm_seq": "@common,@jetmet,@L1TMon,@hcal", 
  "primary_dataset": "JetMET"
}
```

You need to ask Tier-0 team on what happened.

**Comment by sam7k9621** [comment]
@srimanob  thanks a lot, I will contact with them

**Comment by srimanob** [comment]
Do we still need this PR, as the issue happened in the Tier-0 configuration side? @sam7k9621

**Pull request closed without merging**
