### PR TITLE
Remove deprecated Openssl functions SHA1*

### PR DESCRIPTION
**Pull request by smuzaffar**
These chanegs should fix the remaining OpenSSL warnings
```
L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:84:17: warning: 'int SHA1_Init(SHA_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    84 |   if (!SHA1_Init(&ctx))
L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:87:19: warning: 'int SHA1_Update(SHA_CTX*, const void*, size_t)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    87 |   if (!SHA1_Update(&ctx, buf, len))
L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:91:18: warning: 'int SHA1_Final(unsigned char*, SHA_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    91 |   if (!SHA1_Final(hash, &ctx))
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
