### PR TITLE
Add AlCaLumiPixels_Run3 scenario

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

AlCaLumiPixels scenario was never moved to Run-3, so this PR does that.

#### PR validation:

`scram b runtests` runs fine with the modified unit test. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Probably we need it in 12_3_X

### CODE REVIEW

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
attn @cms-sw/alca-l2 @benitezj

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
So this is an `operations-l2` only signature, @cms-sw/orp-l2 do you have any comments?

**Comment by perrotta** [comment]
@tvami this is just the configuration that allows addiing that scenario: where it is actually implemented?

**Comment by tvami** [comment]
> @tvami this is just the configuration that allows addiing that scenario: where it is actually implemented?

Hi @perrotta , nowhere yet, it will be here: 
https://github.com/dmwm/T0/blob/5f7a3489851455d8bd6faa04288f36ce04d2eba5/etc/ReplayOfflineConfiguration.py#L117
once we have a new CMSSW out (I guess at this point I can also say that we'll need a new 12_3_X CMSSW to finally test this)

**Comment by perrotta** [comment]
Thank you @tvami 
Then, how are we supposed to validate this config? Was it ever tried at T0? Or should we just wait for that possible future CMSSW release to be run at T0?

**Comment by tvami** [comment]
This is a long ongoing issue, that we can't test stuff at T0 w/o having a pre-(or full)release. The T0 team is working on having some workaround for a while now, but I don't think there is anything yet. 

This PR
https://github.com/dmwm/T0/pull/4650
was testing with the `AlCaLumiPixels` scenario, when we have a new CMSSW I'll change that to `AlCaLumiPixels_Run3` scenario

**Comment by davidlange6** [comment]
why does the t0 needed for testing ? The unit tests of Config/DataProcessing ought to do the initial sanity test that the configuration is sane and runs.

**Comment by tvami** [comment]
> The unit tests of Config/DataProcessing ought to do the initial sanity test that the configuration is sane and runs.

OK then, that did pass, right?

**Comment by davidlange6** [comment]
it of course has to be tweaked for the specific change introduced...

**Comment by tvami** [comment]
Hi @davidlange6 is this what you had in mind:
https://github.com/tvami/cmssw/commit/f401eb3d8abb829c84e9c199ff9cb707b8d1ae67
?

**Comment by perrotta** [comment]
Thank you @davidlange6 for the suggestion, and @tvami for the implementation!

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@perrotta ok the unit test seems to be working fine:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a4c6ff/23643/unitTests/src/Configuration/DataProcessing/test/TestConfigDP/testing.log

**Comment by perrotta** [comment]
+1

**Pull request merged**
