### PR TITLE
Add parameter for treatment of charged high eta in PUPPI [10_6_X backport]

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #28735

PR description:

This is a followup of #28558, introducing a parameter to steer the eta-range for the treatment of charged particles not associated to vertices. This is to optimize PUPPI with phase-1 tracking. The performance was discussed here:
https://indico.cern.ch/event/876142/#5-update-on-puppi-tuning

This PR implements the necessary switches without changing the current behavior of the algorithm, i.e. no changes to RECO+MiniAOD are expected from this PR.

PR validation:

runtests

Backports

We would like to have these options backported to 10_6_X, to introduce a new PUPPI configuration for UL MiniAOD-v2 and for JMEcustomNanoAODs as soon as the PR is merged.

### CODE REVIEW

**Comment by perrotta** [comment]
-1
Please update as in #28735
(Just avoid resetting the initial values of "PtMaxCharged" and "PtMaxPhotons" to "-1", so that the same code as it is now in 10_6 is identically reproduced)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Backport of #28735, now merged in master
- A new parameter added in PuppiProducer to select charged particle up to a give pseudorapidity
- The default value set for it identically reproduces the behavior of the producer without it
- Jenkins tests pass and show no differences, as expected

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
+1

**Pull request merged**
