### PR TITLE
[13_1_X] APE measurement tool: Resolved python3 compatibility issues, added unit test functionality, removed dependency on other package: Backport of #42012

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

autoSubmitter.py did not run on recent CMSSW releases since ROOT does not work with python2, while python3 execution would throw an error from using the output of "check_output" without decode().

Some additional small changes to remove redundancies were applied, as well as a change to the disk space requested by condor jobs (the target input file size is 350MB, but files can be larger than 400MB anyway) and some formatting changes. Also, the method names now adhere to the CMS naming rules. 

Additionally, added unit test functionality and removed the need to add the package Alignment/TrackerAlignment whenever a measurement is to be performed.

#### PR validation:

I executed the program with an example configuration and made sure it ran as expected. All changes should be transparent.
Also, a unit test can now be run to validate the PR.

#### Backport

Backport of #42012

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42085

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
+1

 - tests clean and new unitTest successful
 - small caveat (left for future PR) detailed in https://github.com/cms-sw/cmssw/pull/42085#issuecomment-1610906226

**Comment by perrotta** [comment]
+1

**Pull request merged**
