### PR TITLE
Move LCTContainer to separate file

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR simply moves `LCTContainer` from inside `CSCUpgradeMotherboard` to a separate class definition `LCTContainer.h`. It is part of my ongoing mission to make the CSC local trigger as simple as possible to understand.

#### PR validation:

FYI @tahuang1991 @nickmccoll

### CODE REVIEW

**Comment by dildick** [comment]
@rekovic can you run the tests, please?

**Comment by fabiocos** [comment]
please test

**Comment by dildick** [comment]
@fabiocos @rekovic Do you have any more comments on this PR?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
