### PR TITLE
hltIntegrationTests: increase the cmsRun stack size for multithreading

### PR DESCRIPTION
**Pull request by fwyzard**
backport #7431 to 7.3.x

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please skip the usual tests, if possible, since this script is not used by any of the standard worklflows

**Comment by perrotta** [comment]
Ciao Andrea.
This PR is supposed to be for 73X, but you re-submitted it to 74X instead.
As a result, you overwrote #7431 in 74X (not a problem, since the commits are identical in these two PR's); but the fix for 73X seems to be still missing...

**Comment by fwyzard** [comment]
No, rokie mistake !

I'll make a 7.3.x PR... #7442 .

.A

**Pull request merged**
