### PR TITLE
Using dasgoclient for das queries in runTheMatrix

### PR DESCRIPTION
**Pull request by fabozzi**
As suggested here:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3279/1/1/1/1/1/1/1.html

we use dasgoclient to make das queries in runTheMatrix

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @fabozzi - we need a 10x version of this.

otherwise, please also update ConfigBuilder.py

**Comment by davidlange6** [comment]
err- ok, this is the 10x version of the PR - somehow I was confused earlier.

**Comment by fabozzi** [comment]
@davidlange6 
it seems it has been moved to 10_0_X milestones (yesterday it was 9_4_X). Let me know if I should take any action on this.

**Comment by slava77** [comment]
@smuzaffar @davidlange6 
do we need some matching updates on the cms-bot side?

**Comment by smuzaffar** [comment]
@slave77, no updates needed for cms-bot .

**Comment by davidlange6** [comment]
Hi @ yes, please apply the same change in ConfigBuilder.py. Thanks

**Comment by fabozzi** [comment]
@davidlange6 
OK, applied also to ConfigBuilder

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
