### PR TITLE
Update HLT menu

### PR DESCRIPTION
**Pull request by silviodonato**
Update HLT menu with master table /dev/CMSSW_10_0_0/V25.
This contains the CMSHLT-1710 with the propagation of the deactivation of SR@PF (#21846) to HLT.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
What about online_grun.txt ?

**Comment by Martin-Grunewald** [comment]
added and rebased to CMSSW_10_1_X_2018-01-25-2300

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
