### PR TITLE
Include L1 track finding algorithm (for HL-LHC upgrade)

### PR DESCRIPTION
**Pull request by skinnari**
#### PR description:

This PR is to include the L1 tracking algorithm (hybrid emulation) into central CMSSW. It is needed for the Phase-2 HLT TDR. It adds the following new packages: 

L1Trigger/TrackFindingTracklet/
L1Trigger/TrackFindingTMTT/

#### PR validation:

This PR is not currently part of any official workflow.

### CODE REVIEW

**Comment by rekovic** [comment]
Thanks @skinnari !

Most of these 911 files are "data" files in ```L1Trigger/TrackFindingTracklet/data/```.
We need to move all these data files in externals. @mrodozov can you please assist with this?

**Comment by rekovic** [comment]
More detailed accounting
- 577 files in ```data/```
- 118 files in ```test/```

This leaves about 220 files mostly in  ```L1Trigger/TrackFindingTracklet/```  and ```L1Trigger/TrackFindingTMTT/```.
This is still a large number of files, and very difficult to review.

Since the two ```Tracklet``` and ```TMTT``` modules go in that order, I would suggest to split this PR into two PRs, each without ```data/``` and ```test/``` files which would have about 100 files each, roughly.   We can then start the review of the two PRs in parallel, and then merge them in the order above.

**Comment by mrodozov** [comment]
@rekovic certainly, but can I also ask that you remove the .gitignore , Doxyfile , etc redundancies 
I'll collect whatever there is new within /data dirs but I also see there are .txt files within /test which probably should be moved in /data

**Comment by mrodozov** [comment]
@smuzaffar we need two new data repos to be created 
L1Trigger/TrackFindingTracklet/
L1Trigger/TrackFindingTMTT/
to host the data
Also when I open some of the .txt files I see .root files in /opt or in /store which judging by the number of files I'm not sure can be hosted on github 
for example - should we get keep
https://github.com/cms-sw/cmssw/pull/29284/files#diff-19bdd2a64c4e9fb2cf183e89a4303fb4
in the data repos itself ?

**Comment by smuzaffar** [comment]
@mrodozov , https://github.com/cms-data/L1Trigger-TrackFindingTracklet is now available. I do not see any data files for L1Trigger/TrackFindingTMTT though.

@skinnari , I see that you have some scripts in L1Trigger/TrackFindingTracklet/data directory. Note that data directory is not available via PATH env so you will not be able to run these scripts. In case you want to run these scripts then please move these to L1Trigger/TrackFindingTracklet/scripts directory.

**Comment by mrodozov** [comment]
there are, but the files are in the /test directory 
https://github.com/cms-sw/cmssw/pull/29284/files#diff-7f56264139d62f042eb28c5a75fbee98
@skinnari you'll have to remove all the Doxyfile , .gitignore I also see .png files

**Comment by smuzaffar** [comment]
@mrodozov , these are not data files and should be removed or kept if really needed. data files are those files which are under package/data directory

**Comment by skinnari** [comment]
hi all, thanks for the feedback so far. as suggested, we will close this PR and re-submit it as two separate PRs for the two separate packages to simplify the review. please note however that the two are required jointly for running the L1 track algorithm.

**Comment by skinnari** [comment]
@smuzaffar @mrodozov how can data files in this separate repository be accessed? do people have to check this out in addition to the cms-sw? i didn't even know this "cms-data" existed (!) so if there are any references for how to use it that would be very helpful. thanks!

**Comment by smuzaffar** [comment]
@skinnari , for local testing you can 
- clone cms-data/Subsystem-Package repository
- Copy your CMSSW/src/Subsystem/Package/data in to Subsystem-Package
- create a symlink CMSSW/src/Subsystem/Package/data pointing to Subsystem-Package
You access the data files the same way you are already doing. Once you are done with your changes then make two PRs , one for cmssw and one for cms-data/Subsystem-Package. Please note that do not add/commit CMSSW/src/Subsystem/Package/data symlink in cmssw repo.
Please make sure that you keep on valid data files in the data repo. Currently I see there are many data files with zero size, do you need all those?

**Comment by skinnari** [comment]
@smuzaffar OK, thanks! so this procedure is for local testing -- how does it work ones the PRs are merged? then CMSSW "automatically" knows about the files w/o needing to go through creating symlinks etc?

**Comment by smuzaffar** [comment]
Yes, cmssw look for data files under CMSSW_SEARCH_PATH env variable. Once data external is merged and availble in IB then its path will be added to CMSSW_SEARCH_PATH.

**Comment by skinnari** [comment]
@smuzaffar ah OK, understood. thanks a lot for clarifying!

**Comment by rekovic** [comment]
It makes sense to separate this PR into 2 PRs, as I was saying earlier.

Package ```L1Trigger/TrackFindingTMTT/ ``` does not at all depend on ```L1Trigger/TrackFindingTracklet/``` .  The reverse is not the case.   So if we have the two PRs as:

- PR#1 L1Trigger/TrackFindingTMTT/
- PR#2 L1Trigger/TrackFindingTracklet/

Then the testing would proceed with 
- test PR#1 (standalone)
- test PR#2 with PR#1

Discussed with @skinnari to proceed with the split and making of two PRs.

**Comment by tomalin** [comment]
> @mrodozov , https://github.com/cms-data/L1Trigger-TrackFindingTracklet is now available. I do not see any data files for L1Trigger/TrackFindingTMTT though.

We also need cms-data/L1Trigger-TrackFindingTMTT, to contain the data files previously stored in L1Trigger/TrackFindingTMTT/test/MCsamples/ . Mircho, are you able to add this for us?

**Comment by mrodozov** [comment]
@smuzaffar can you create the repo for this and I can add the files

**Comment by smuzaffar** [comment]
@mrodozov , L1Trigger-TrackFindingTMTT is now available

**Comment by mrodozov** [comment]
@tomalin could you please check the PR if this is what you need

**Comment by tomalin** [comment]
Yes, I've made pull request to add the TMTT data files to cms-data/L1Trigger-TrackFindingTMTT , so I can now delete them from the TMTT algo pull request expected today.

**Pull request closed without merging**
