### PR TITLE
Conditions needed to introduce pedestal correlation coefficient for HB and HE channels and update pedestal widths for 2023/2024

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the `HcalSiPMParametersRcd` tag for Run-3 MC scenarios to introduce a pedestal correlation coefficient for adjacent time slices for HB and HE channels. The motivation and impact on the HBHE reconstruction are given in [presentation by Taeun Kwon](https://indico.cern.ch/event/936151/contributions/3933432/attachments/2070567/3476700/pedestal.pdf). A separate, currently unused field in `HcalSiPMParametersRcd` is used to implement these changes but the corresponding code changes have not been made. Therefore, at this point, no changes are expected in standard workflows.

In addition, the HCAL pedestal widths are updated for 2023 and 2024 scenarios, following [the request in the AlCaDB HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4319/1/1/2/1.html).

The global tag diffs are as follows:

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v5/112X_mcRun3_2021_design_v6

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v5/112X_mcRun3_2021_realistic_v6

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v5/112X_mcRun3_2021cosmics_realistic_deco_v6

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v6/112X_mcRun3_2021_realistic_HI_v7

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v4/112X_mcRun3_2023_realistic_v6

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v4/112X_mcRun3_2024_realistic_v6

#### PR validation:

See the [AlCa HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4319.html) and references therein for details. In addition, a technical test was performed: `runTheMatrix.py -l limited,12024.0,7.23,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and should not be backported.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 12024.0,7.23,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by abdoulline** [comment]
We don't  expect any changes at this step,  as the code, which is supposed to active correlation factors in MAHI fit (local HCAL reco)  is not yet submitted....  
To be clarified.

**Comment by abdoulline** [comment]
I see now: not only noise corr.factors added (wrt baseline), but also DarkCurrent (DC) values changed...
(while effective peds and ped.widths stay unchanged).
I've initiated discussion within HCAL DPG.

**Comment by christopheralanwest** [comment]
please test

**Comment by abdoulline** [comment]
Tags-content-wise, this is what HCAL DPG asked for...

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
