### PR TITLE
refactor PFAlgo::processblock usePFPhotons part

### PR DESCRIPTION
**Pull request by jpata**
#### PR description:

Proposal to start refactoring the `PFAlgo::processBlock`, which is a single function of several thousand lines, into smaller independent subfunctions, based on physics functionality. As the original code is laid out quite clearly, simply in a long stream of consciousness, it is easy to factorize for example the part processing photons into a separate function. In a future iteration, we can factorize also the rest of the `processBlock` function. 
This can be followed by sanitizing the inputs and outputs of the functions and making sure they rely less on a global state.

#### PR validation:

We do not change the functionality of the PFAlgo code, we have validated by re-running the RECO sequence on 10k events and observed exactly the same PF reconstruction output. The full test matrix is running, I will report back with the output, I expect no new failures.

#### if this PR is a backport please specify the original PR:

This is a partial port of the original proposal PR in https://github.com/jpata/cmssw/pull/44.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
Added the preliminary slides describing this here: https://indico.cern.ch/event/818739/#2-pfalgo-refactoring
@hatakeyamak @bendavid @guitargeek

**Comment by perrotta** [comment]
-1
- Given that the part of the PFAlgo modified by this PR was completely removed by #26813, this PR is not necessary any more: please @jpata close it

**Comment by jpata** [comment]
ok @perrotta. Should I go forward with the rest of the PFAlgo::processBlock refactoring or is it not needed?

**Comment by perrotta** [comment]
> ok @perrotta. Should I go forward with the rest of the PFAlgo::processBlock refactoring or is it not needed?

Sure, please go ahead as planned in the last PF meeting!
Simply PFPhotonAlgo and PFElectronAlgo were removed from the code in CMSSW, and there is no point in updating them any more.

**Comment by jpata** [comment]
thx for clarifying!

**Pull request closed without merging**
