### PR TITLE
ECAL PayloadInspector : bug correction

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:
ECAL PayloadInspector :  in EcalSimComponentShape_PayloadInspector.cc and EcalSimPulseShape_PayloadInspector.cc, the time_interval between successive points was not taken into account, leading to wrong pulse shape plots in case of time_interval <> 1 ns.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

./getPayloadData.py --plugin pluginEcalSimPulseShape_PayloadInspector --plot plot_EcalSimPulseShapeProfile --tag EcalSimPulseShapePhaseI --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --test

./getPayloadData.py --plugin pluginEcalSimPulseShape_PayloadInspector --plot plot_EcalSimPulseShapeProfile --tag EcalSimPulseShapePhaseII --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --test

./getPayloadData.py --plugin pluginEcalSimComponentShape_PayloadInspector --plot plot_EcalSimComponentShapeProfile --tag EcalSimComponentShape_PhaseI --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --test

./getPayloadData.py --plugin pluginEcalSimComponentShape_PayloadInspector --plot plot_EcalSimComponentShapeProfile --tag EcalSimComponentShape_PhaseII --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --test

give the correct plots, for Phase I and Phase II..

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
type bugfix

**Comment by perrotta** [comment]
+db

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
