### PR TITLE
Remove DataFormats/TrackingSeed as obsolete

### PR DESCRIPTION
**Pull request by makortel**
I came across `DataFormats/TrackingSeed` package while searching for something else. According to git history the last non-technical-migration commit appears to be from 2006, and the package is not used by anybody, i.e. it looks like a (very) old remnant. This PR removes the package.

Tested in 8_1_0_pre9, no changes expected in monitored quantities.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15414 ef680d63f01b0bcafd4291a030b94fea3d9ffa6b

Deleting the obsolete and unused package DataFormats/TrackingSeed. There should be no change in compiled output.

Jenkins tests against baseline CMSSW_8_1_X_2016-08-10-1100 show no significant differences, as expected.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
