### PR TITLE
add missing dependency to SimDataFormats/GEMDigiSimLink

### PR DESCRIPTION
**Pull request by davidlange6**
Missing package dependency as shown by modules build.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test


On Jun 12, 2020, at 4:03 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for master.

It involves the following packages:

SimDataFormats/GEMDigiSimLink

@cmsbuild<https://github.com/cmsbuild>, @civanch<https://github.com/civanch>, @kpedro88<https://github.com/kpedro88>, @mdhildreth<https://github.com/mdhildreth> can you please review it and eventually sign? Thanks.
@apsallid<https://github.com/apsallid>, @rovere<https://github.com/rovere>, @fabiocos<https://github.com/fabiocos>, @lecriste<https://github.com/lecriste> this is something you requested to watch as well.
@silviodonato<https://github.com/silviodonato>, @dpiparo<https://github.com/dpiparo> you are the release manager for this.

cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-cmds.html>

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
