### PR TITLE
Remove call to alpaka::getDev() in test code when allocating TestDeviceCollection

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

I don't remember why I used alpaka::getDev(), and I can't now think of any good reason for that. Thanks to @fwyzard for noticing.

#### PR validation:

Unit tests pass (on a machine without GPU)

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
