### PR TITLE
Remove noisy missing collection warnings coming from EcalDQMonitorTask

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

Addresses issue https://github.com/cms-sw/cmssw/issues/42720 dealing with multiple missing collection warnings per event coming from the `EcalDQMonitorTask` module using the `ecalMonitorTaskEcalOnly` config in offline relval WFs. The collections fell into one of three groups with each group having a separate reason or set of reasons for the warnings.

---

The `GpuRecHit` collections do not exist (as far as I know this is still the case). RecHit monitoring was switched off for online GPU validation in https://github.com/cms-sw/cmssw/pull/39393, but this was not propagated to offline since RecHits were [enabled by default](https://github.com/cms-sw/cmssw/blob/93e2e3051588c8f931cb559201d76f9edafdb9ec/DQM/EcalMonitorTasks/python/ecalGpuTask_cfi.py#L13) in the ECAL GPU validation module. With this PR, the RecHits will now be switched off by default. The assumed [RecHit input tags](https://github.com/cms-sw/cmssw/blob/93e2e3051588c8f931cb559201d76f9edafdb9ec/DQM/EcalMonitorTasks/python/CollectionTags_cfi.py#L56-L59) are already in place for when the collections are implemented. 

In addition, there was an oversight of mine in https://github.com/cms-sw/cmssw/pull/39371 while implementing these collection-level switches to be used in exactly this kind of context. This is now corrected in this PR, and unused collections for GPU monitoring are no longer consumed. 

---

The `TrigPrimEmulDigi` and `ReducedRecHit` collections are straightforward to explain. They are not being produced in offline DQM `EcalOnly` workflows, and there are already flags in place to switch off running over these collections. The emulated digis were already switched off in the general offline config, but the same was not done for the `EcalOnly` config, as the collection is switched off _after_ cloning the original config. This PR switches these collections off for the offline `EcalOnly` config.

---

`EcalRawData` is the trickiest to switch off on the ECAL DQM side since it's used by several modules. This issue is now resolved in https://github.com/cms-sw/cmssw/pull/42844. 

However, we simultaneously implemented a bandaid solution on the ECAL DQM side. We added a parameter to `EcalDQMonitorTask` called `skipCollections` that takes in the names of collections to be explicitly removed from the list of collections being run by the ECAL DQM module. 

The skipping is done as barebones as possible and we decided to purposefully not remove any dependencies that might cause a problem if a collection is not present. This way we can prevent potentially undefined behavior from slipping through the cracks and leaving little to no trace of something being wrong. 

Skipping a collection will lead to the same behavior as having a missing collection if there is a further issue. The difference is that a skipped collection will not be consumed and the ECAL DQM module will not attempt to access the data. This could be useful in the future and not necessarily in the context of a missing collection.

The other PR is the ideal solution to the current issue so this isn't going to be used right now, but it doesn't hurt to have the extra customizability option in our toolkit. 

---

#### PR validation:

Tested with both workflows brought up in issue https://github.com/cms-sw/cmssw/issues/42720. The workflows ran successfully with no warnings.

```
runTheMatrix.py --what gpu -l 141.008583
runTheMatrix.py --what gpu -l 11634.511
```

Adding `EcalRawData` to the new `skipCollections` parameter works as intended. The warning and exception paths added also run as intended in their relevant scenarios.

---

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

A backport can be made if needed.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = gpu
   * workflows_gpu = 141.008583, 160.03502
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by alejands** [comment]
The remaining `EcalRawData` warnings (shown below) for WF `141.008583` in [step2_Run3-2023_JetMET2023B_GPUValidation.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e6c161/34874/runTheMatrixGPU-results/141.008583_Run3-2023_JetMET2023B_GPUValidation/step2_Run3-2023_JetMET2023B_GPUValidation.log) should be resolved by https://github.com/cms-sw/cmssw/pull/42844.

```
Begin processing the 1st record. Run 366727, Event 132255498, LumiSection 89 on stream 0 at 24-Sep-2023 15:27:02.391 CEST
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTaskEcalOnly  24-Sep-2023 15:27:04 CEST Run: 366727 Event: 132255498
EcalRawDataCollection does not exist. No event-type filtering will be applied
%MSG
 on gpu found: 3258 on cpu found: 105
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTaskEcalOnly  24-Sep-2023 15:27:04 CEST Run: 366727 Event: 132255498
Ecal Monitor Source::runOnCollection: EcalRawData does not exist
%MSG
```

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/42844.

**Comment by thomreis** [comment]
please test with #42844

**Comment by alejands** [comment]
The remaining warnings are gone now https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e6c161/34894/runTheMatrixGPU-results/141.008583_Run3-2023_JetMET2023B_GPUValidation/step2_Run3-2023_JetMET2023B_GPUValidation.log

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
