### PR TITLE
rename 2017MCTunes folder to MCTunes2017 to avoid import * problems

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@smuzaffar would it make sense to add this (i.e. no folders and filenames starting with numerical values) in the code-checks?

**Comment by perrozzi** [comment]
restore usual convention for PSet naming as old tune https://github.com/cms-sw/cmssw/blob/CMSSW_9_3_0/Configuration/Generator/python/Pythia8CUEP8M1Settings_cfi.py
fixed CP1star to CP2 naming

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
