### PR TITLE
Phase2-gex179 Make a new scenario 2026D115 and workflow 32034.0 for a setup with HFNose and V17 geometry version of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a new scenario 2026D115 and workflow 32034.0 for a setup with HFNose and V17 geometry version of HGCal

#### PR validation:

Tested using runTheMatrix.py for the new workflow

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
test parameters:
- workflow = 32034.0

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Hi @bsunanda @civanch 
This is what I mentioned in the meeting about the failure of DD4hep workflow which I can't reproduce it yet. If I take step1.root from [PR test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-60f063/40260/runTheMatrix-results/29634.911_TTbar_14TeV+2026D110_DD4hep/) and try to run step2 on lxplus, it works.

@smuzaffar 
Do you know the spec of machine of PR test, i.e. intel, amd? I would like to try to do in the same environment. Thx.

**Comment by srimanob** [comment]
@cmsbuild please test

Re-trigger the test

**Comment by srimanob** [comment]
> Hi @bsunanda @civanch This is what I mentioned in the meeting about the failure of DD4hep workflow which I can't reproduce it yet. If I take step1.root from [PR test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-60f063/40260/runTheMatrix-results/29634.911_TTbar_14TeV+2026D110_DD4hep/) and try to run step2 on lxplus, it works.
> 
> @smuzaffar Do you know the spec of machine of PR test, i.e. intel, amd? I would like to try to do in the same environment. Thx.

Answer my self, it runs on
<PerformanceSummary Metric="SystemCPU">
<Metric Name="CPUModels" Value="Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz"/>
<Metric Name="averageCoreSpeed" Value="2095.146000"/>
<Metric Name="cpusetCount" Value="16"/>
<Metric Name="totalCPUs" Value="16"/>
</PerformanceSummary>

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

The failure in DD4hep workflow has been reported for a while in 
- https://github.com/cms-sw/cmssw/issues/41451
- https://github.com/cms-sw/cmssw/issues/41927
- https://github.com/cms-sw/cmssw/issues/42470

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@sunilUIET Please approve this PR

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by bsunanda** [comment]
@antoniovilela @rappoccio Please approve and integrate this PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
