### PR TITLE
Adding the correction structure to all electrons 

### PR DESCRIPTION
**Pull request by jainshilpi**
In the context of low pT GED electrons for UL, in order to make the
regression work on GED electrons below 5 GeV,
dropCorrections = cms.string(" pt < 5") needs to be removed and made
available for all the electrons here:
https://cmssdt.cern.ch/lxr/source/PhysicsTools/PatAlgos/python/slimming/slimmedElectrons_cfi.py#0003

If this is not done, then the H/E and E/p take result in wrong results since they need to access
correction structure when the electron is regressed.

By removing this condition, we tested on a 136.88811 WF (JetHT - same as used by @bainbrid  for low pT electrons), the sample size increase is 0.04%.

### CODE REVIEW

**Comment by jainshilpi** [comment]
It was just pointed out by Francesca Cavallari that we need additional (small) update in order to make the regression work on miniAOD for low pT electrons: https://cmssdt.cern.ch/lxr/source/RecoEgamma/EgammaTools/plugins/EGRegressionModifierV3.cc 
I am doing the checks and will update the PR

**Comment by jainshilpi** [comment]
Just talked to @bainbrid - for a speedy review, the update I mentioned in my last comment will come in his PR. So we can stay with the current changes we have in this PR. Once this is merged, I can do the backport.

**Comment by mariadalfonso** [comment]
@mbluj @kandrosov 
this PR change a bit the slimmedTaus - tauID; any chance that for those event where we see a change, the RECO from AOD and from MINIAOD get the same ?

**Comment by slava77** [comment]
assign xpog

**Comment by mbluj** [comment]
> @mbluj @kandrosov
> this PR change a bit the slimmedTaus - tauID; any chance that for those event where we see a change, the RECO from AOD and from MINIAOD get the same ?

Could you clairfy if It does change slimmedTaus itself (4-momentum) or a particular tauID(s), please?  Could you point us to relevant plots, please? Thanks!

**Comment by mariadalfonso** [comment]
> > @mbluj @kandrosov
> > this PR change a bit the slimmedTaus - tauID; any chance that for those event where we see a change, the RECO from AOD and from MINIAOD get the same ?
> 
> @mariadalfonso Could you clarify if It does change slimmedTaus itself (4-momentum) or a particular tauID(s), please? Could you point us to relevant plots, please? Thanks!

@mbluj 
it's a (minimal) change on the tauID (no change on the p4); see plots here 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-05-18-2300+08e56e/42862/validateJR.html

**Comment by mbluj** [comment]
> > > @mbluj @kandrosov
> > > this PR change a bit the slimmedTaus - tauID; any chance that for those event where we see a change, the RECO from AOD and from MINIAOD get the same ?
> > 
> > 
> > @mariadalfonso Could you clarify if It does change slimmedTaus itself (4-momentum) or a particular tauID(s), please? Could you point us to relevant plots, please? Thanks!
> 
> @mbluj
> it's a (minimal) change on the tauID (no change on the p4); see plots here
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-05-18-2300+08e56e/42862/validateJR.html

Thank you for the link. There are indeed small changes in the deepTauID scores for some samples. It is difficult to estimate their impact providing small statistics, but it is probably minor. Regardless, the change of deepTauID scores is inducted by a change of pat::Electrons (`slimmedElectons` collection) and should affect in the same way deepTauID for taus build with AOD and miniAOD inputs. It is as deepTauId itself is always evaluated using miniAOD inputs, for instance slimmedElectrons and slimmedTaus. The difference between taus (and their IDs) reconstruced on top of AOD and miniAOD must originate from some differences in a way in which taus are built from `reco::PFCandidates` (at AOD) and from `pat::PactedCandidates` (at miniAOD).

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33776	6171749 
- code changes are in line with the PR description and the follow up discussion
- jenkins tests pass and comparisons with the baseline show differences in miniAOD starting from slimmedElectrons now having non-zero/non-default values for caloEnergy, correctedEcalEnergy and related uncertainties; some of these variables are apparently used in the deepTau and now non-zero values trigger some relatively minor differences.

**Comment by mariadalfonso** [comment]
+xpog

**Comment by silviodonato** [comment]
+1

**Pull request merged**
