### PR TITLE
Fix additional memory issues in EcnaAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Changed all pointers to automatically memory managed classes, e.g.  std::unique_ptr and std::array.
#### PR validation:

The code compiles using gcc 12 without issuing the warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I had missed the other PR which was also fixing the gcc12 warning. Since my changes had additional improvements, I decided to keep those additional changes.

**Comment by Dr15Jones** [comment]
please test

**Comment by iarspider** [comment]
@Dr15Jones thanks!

**Comment by francescobrivio** [comment]
+1

 - technical
 - tests clean

**Comment by perrotta** [comment]
+1

**Pull request merged**
