### PR TITLE
[14_0_X] Allow using fake pixels from the digi morphing algorithm as cluster seeds but drop them from final clusters

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46813 to CMSSW_14_0_X

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
hold 
pending 14_2_X backport

**Comment by antoniovilela** [comment]
unhold

**Comment by mandrenguyen** [comment]
unhold

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
