### PR TITLE
Puppi into mini aod 74 x

### PR DESCRIPTION
**Pull request by jshlee**

### CODE REVIEW

**Comment by slava77** [comment]
Hi Jason,
this should be in sync with #8122 , right?

**Comment by jshlee** [comment]
Hi Slava,
Yes it would be nice to be in sync but I couldn't rebase both at the same point due to recent merges in 74X.

**Comment by jshlee** [comment]
I will close this rebase #8122

**Comment by slava77** [comment]
I suppose a replacement is coming any moment for 74X

**Pull request closed without merging**
