### PR TITLE
[MuonHLT]: BugFix for TSGforOI in 93X

### PR DESCRIPTION
**Pull request by folguera**
This fixes a couple of bugs discovered that were affecting the efficiency specially in the overlap region:

- Added error-rescaling for hit-based seeds.
- Correct reseting of the number of made seeds (affecting the overlap region)
- Add a configuration parameter to chose the name of the propagator in the config file (it was previously hard-coded)

This only affects the outside-in component of the Muon HLT reconstruction. This includes the same changes as #20393

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@folguera : please also apply the suggestions from the code check

**Comment by perrotta** [comment]
abort test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
git master branch is now 94X. Should this be in 93X you'd need to make a 93X PR as well.

**Comment by slava77** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20396	8b05427
- changes are visually in line with the PR description, all are in HLT-related code (not affecting reco products).
- jenkins tests pass and comparisons with baseline show some changes in HLT plots for quantities related to muons (e.g. pt HLT vs reco resolution plots)  and in downstream PF; there are no changes in reco product monitoring.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
