### PR TITLE
Phase2-hgx350 Make modifications for the HGCal version V18 in the case of mouse bite, guard rings, ...

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make modifications for the HGCal version V18 in the case of mouse bite, guard rings, ...

#### PR validation:

Using the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

Just to re-trigger the test, to see if we can get clean result on unrelated workflows.

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Note to @bsunanda @civanch 

Not relate to this PR, but please consider to issue reported by static check.

```
/pool/condor/dir_62157/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/SimG4CMS/Calo/src/CaloSD.cc:220:13: warning: const_cast was used, this may result in thread-unsafe code [threadsafety.ConstCast]
  220 |             const_cast<G4Track*>(tk)->SetTrackStatus(fStopAndKill);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
/pool/condor/dir_62157/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/SimG4CMS/Calo/src/CaloSD.cc:422:102: warning: Called C++ object pointer is null [core.CallAndMessage]
  422 |       edm::LogVerbatim("CaloSim") << "CaloSD: EndofEvent entered for container " << k << " with " << theHC[0]->entries()
      |               
```

**Comment by civanch** [comment]
@srimanob , here const_cast is thread safe. Geant4 design expect that  SD class or SteppingAction cannot change G4Track status, only physics process should do this. In reality this rule will bring a small overhead, so we use that for the purpose. At the same time, your comment is valid, because it is acceptable if SteppingAction may kill a track, why CaloSD is doing this to me not clear. I would think that responsibility for MC truth and to change track status should not be spread between several places - they should be in one place.

**Pull request merged**
