### PR TITLE
update relval recycling string for 10_3_X

### PR DESCRIPTION
**Pull request by zhenhu**

### CODE REVIEW

**Comment by kpedro88** [comment]
@smuzaffar the bot missed this one, can you check?

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@zhenhu in order to avoid perturbing other validations, I would keep this PR for the last IB before pre5 is built

**Comment by fabiocos** [comment]
+1

close to 10_3_0_pre5 build, let's merge it

**Pull request merged**
