### PR TITLE
Add orbitNumber to NanoAOD

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Add orbitNumber to NanoAOD as requested by ECAL for selecting BXs after calibration triggers.

#### PR validation:

Tested with `runTheMatrix.py -l 2500 --ibeos`.

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
