### PR TITLE
Secondary Dataset backport 130X

### PR DESCRIPTION
**Pull request by jordan-martins**
This is a backport of #42065

### CODE REVIEW

**Comment by jordan-martins** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42065

**Comment by perrotta** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by malbouis** [comment]
@cms-sw/pdmv-l2 would you please sign this PR?

**Comment by perrotta** [comment]
+1
- Verbatim backport of #42065
- These changes will not be effective until explicitly switched on at Tier0. Therefore, they are not dangerous for data taking even if merged in parallel with the master version

**Pull request merged**
