### PR TITLE
TTHFGenFilter

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Filter that can be used to produce a tt+bb sample, that is filtered from an inclusive tt+jets sample on Gen-Sim-Level.
The tool is based on the GenHFHadronMatcher. 
Has been discussed, e.g. at:
https://indico.cern.ch/event/535804/contributions/2248021/attachments/1311031/1961746/TTbbFIlterProposal_180716_AndrejSaibel.pdf

https://indico.cern.ch/event/524148/contributions/2154898/attachments/1266760/1875475/CombinationOfTTbarandTTbb_AndrejSaibel.pdf

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by monttj** [comment]
@Andrej-CMS 
Hi Andrej Saibel,

As discussed during the meeting, I would second the opinion to remove the condition requiring b hadron is only from Hard process as there are other analyses measure the ttbb inclusively and the condition of having only Hard process would introduce the MC modeling systematic uncertainties.

And it would be also great if we can have this filter for systematic samples because the systematic samples, e.g. PS scale is the area where we suffer a lot due to lack of statistics. 

Best regards,
Taejeong

**Comment by Andrej-CMS** [comment]
Hello Taejeong,


I have rewritten the Filter,such that it has now a flag 
"OnlyHardProcessBHadrons", which does what you have asked, if set to 
"False".
I also tested it with the Gen-Sim-File, with which I usually test my 
filter mentioned in the presentation in TopModGen meeting today. The 
filter runs the way it is supposed to.
New commit was already pushed to my 81x repository. I will soon also 
push the 71X version

Kind regards,

Andrej

**Comment by monttj** [comment]
Hi Andrej, 

Thank you, 

I guess the flag "OnlyHardProcessBHadrons" is still to be committed in this PR?
Because I don't see the flag in the filter above yet.

Taejeong

**Comment by Andrej-CMS** [comment]
Hello Taejeong,

It's now also commited to this PR

Kind regards,
Andrej

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
please test
(that is strange)

On Aug 5, 2016, at 6:34 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


-1

Tested at: f2b66b8<https://github.com/cms-sw/cmssw/commit/f2b66b8fa44c4d36ddc58df2e89a6f774364b622>

You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15301/14386/summary.html

I found follow errors while testing this PR

Failed tests: Build

  *   Build:

I found an error when building:


gmake[1]: Target 'PostBuild' not remade because of errors.

gmake[1]: Leaving directory '/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-08-05-1100'

config/SCRAM/GMake/Makefile.rules:1935: recipe for target 'src' failed

gmake: *** [src] Error 2

gmake: Target 'all' not remade because of errors.

gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@Andrej-CMS - I checked this PR locally - there is a real error that you need to address. Can you have a look.. Thanks

>> Compiling python modules src/PhysicsTools/JetMCAlgos/python
Compiling src/PhysicsTools/JetMCAlgos/python/ttHFGenFilter_cfi.py ...
  File "src/PhysicsTools/JetMCAlgos/python/ttHFGenFilter_cfi.py", line 10
    genBHadIndex = cms.InputTag("matchGenBHadron", "genBHadIndex"),.
                                                                   ^
SyntaxError: invalid syntax

config/SCRAM/GMake/Makefile.rules:2167: recipe for target 'CompilePython' failed

**Comment by Andrej-CMS** [comment]
Fixed the typo in ttHFGenFilter_cfi.py

**Comment by davidlange6** [comment]
please test

thanks

On Aug 8, 2016, at 10:12 AM, Andrej-CMS <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed the typo in ttHFGenFilter_cfi.py

**Comment by davidlange6** [comment]
+1

On Aug 8, 2016, at 11:35 AM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


+1
Tested at: 8a190b7<https://github.com/cms-sw/cmssw/commit/8a190b7245035a4f8360e7a3a966986a92bcf9e0>
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15301/14411/summary.html

**Pull request merged**
