### PR TITLE
Phase2-hgx302A Use MessageLogger instead of cout in a number of analyzers in HGCalGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use MessageLogger instead of cout in a number of analyzers in HGCalGeometry

#### PR validation:

Use runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Technical PR to handle message logger.

**Comment by srimanob** [comment]
@cmsbuild please test

To clean up the unexpected failure in comparison from DD4hep phase-2 wfs.

**Comment by perrotta** [comment]
+1

**Pull request merged**
