### PR TITLE
Adding a vertex smearing configution for pp at 5 TeV

### PR DESCRIPTION
**Pull request by mandrenguyen**
Expected beam conditions for the pp run at 5 TeV that will take place in about 4 weeks.
71X version of #12040

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by mmusich** [comment]
@diguida @jrcastle

**Comment by diguida** [comment]
@mmusich thanks for the ping. I saw the 71X version reported by @mandrenguyen in his mail.

**Comment by diguida** [comment]
@mandrenguyen I am not convinced about the centroid position. From the first pp fills, we know that X and Y are not in 0. The latest exercise was done on Run2015B collision (fill 4008), and we have

````
Centroid absolute positions
X =  0.07798 cm
Y =  0.09714 cm
Z = -1.610 cm

BPIX absolute position extracted from PCL-like alignment run after magnet ramp-up:
X = -0.026837  cm
Y = -0.0715252 cm
Z = -0.511453  cm

Vertex smearing parameters
X0 = 0.10482 cm
Y0 = 0.16867 cm
Z0 = -1.0985 cm
````

Now, we know for sure that, in Run2015D the Z is back in 0, while X and Y are still away.
I'd rather suggest to use the "realistic" values.

If, instead, you have already the GEN-SIM for the `NominalHICollision2015VtxSmearingParameters`, I can argue you want to keep the same centroid position.

**Comment by mandrenguyen** [comment]
@diguida 
Indeed when we set the HI beam position we still thought the beam would be at the origin, and we chose not to stop the GEN-SIM to move the beam beam.  You can see we added an improved guess: UpdatedHICollision2015VtxSmearingParameters
but this hasn't been used yet.

Now if you tell me that the beam position is pretty stable and we don't think it will move then I should update the centroid positions accordingly.  
Just to be sure, your recommendation is:

Vertex smearing parameters
X0 = 0.10482 cm
Y0 = 0.16867 cm
Z0 = -1.0985 cm

Thanks!

**Comment by diguida** [comment]
@mandrenguyen 
thanks for the feedback on the updated vertex parameters.

The change in Z position happened during Run2015D (with a LHC time shift, more details on BeamSpot hn), while the X and Y position are quite stable in this era, as you can see in the latest report by BeamSpot operation team at the [AlCaDB meeting](https://indico.cern.ch/event/368361/contribution/3/attachments/1168867/1686536/bs_alca_12_10_2015.pdf).

Concerning X, do not use the 0T value: the centroid position in x depends on the B field (horizontal crossing angle) and we do see movements ~120 um, confirmed by LHC-OPS team.

I'd suggest some values taken from the latest fills in Run2015D (4393), looking at the plots in the presentation:

````
X = 0.0760 cm
Y = 0.0935 cm
Z = 0.0 cm
````

Beware: you should sum algebraically the pixel barycentre of the alignment used to compute that BS, as in the vertex smearing parameters you should refer to the pixels. This is an exercise done within the tracker alignment group. Assuming this is the same as the previous computation (this is typically *not* the case):

````
X_p = -0.026837  cm
Y_p = -0.0715252 cm
Z_p = -0.511453  cm
````

you get:

````
X0 = 0.1028 cm
Y0 = 0.1650 cm
Z0 = 0.5115 cm
````

Please do not consider those numbers as correct, but take them as a straw-man example. We can provide you the new pixel barycentre position, if worth.

**Comment by mandrenguyen** [comment]
@diguida I'm slightly confused by your recommendation.  Is the suggestion that the tracker alignment group should provide us with a prediction or that we just use the numbers from Run2015D.  Specifically, who is qualified to make this call:  "We can provide you the new pixel barycentre position, if worth"  ?

**Comment by mmusich** [comment]
@mandrenguyen your understanding is correct.
The tracker alignment group should provide you with a best guees, that since we don't have a crystal ball would be the current numbers from Run2015D. 
Since @jrcastle is also currently in charge of the pixel alignment in pp right now, he's in an excellent position to derive these numbers.

**Comment by diguida** [comment]
@mandrenguyen @mmusich we have also some numbers for a recent BS computed on top of the new pixel large-structure alignment for its validation: `BeamSpotObjects_run258742_v1_promptvalidation`. After a quick check, I propose these parameters for the centroid position:

````
x =  0.0769 cm
y = 0.0936 cm
z = 0.1543 cm
````

BS experts will cross-check those values, but I am pretty confident...

**Comment by mandrenguyen** [comment]
@mmusich @diguida 
We will update shortly.
 thank you very much!

**Comment by mandrenguyen** [comment]
@mmusich @diguida @franzoni  
The PR has been updated according to the latest recommendation of the centroid from@jrcastle.
The corresponding PRs for the other releases will follow.  I append the details of his derivation below.

**********
Beam fit from Salvatore on Run 258742

x = 0.0769 cm
y = 0.0936 cm
z = 0.1543 cm

BPIX and PIXEL locations estimated from a high level alignment to the pixel detector from the same run (x2, y2, z2):
====================================================
BPIX:
====================================================
x1 x2: -0.0278442 -0.0275148
y1 y2: -0.0734346 -0.0740016
z1 z2: -0.515565 -0.516435
Delta(x,y,z) = 2-1 = (3.29357,-5.66995,-8.69968) mum
====================================================
Pixel:
====================================================
x1 x2: -0.041651 -0.0415103
y1 y2 -0.199279 -0.199526
z1 z2: -0.565093 -0.566091
Delta(x,y,z) = 2-1 = (1.40686,-2.47002,-9.97731) mum
|  | *treeFile_74X_dataRun2_Express_v3_TrackerAlignment_2009_v1_express_r258742.root* || *treeFile_74X_dataRun2_Express_v3_testTag_r258742.root*||
| *Position* |  *BPIX* | *Full Pixel* | *BPIX* | *Full Pixel* |
|  x  | -0.0278442 | -0.041651 | -0.0275148 | -0.0415103 |
|  y  | -0.0734346 | -0.199279 | -0.0740016 | -0.199526 |
|  z  | -0.515565 | -0.565093 | -0.516435 | -0.566091 |

====================================================
====================================================
====================================================

Taking the BPIX values as the barycenter, then the values for the smearing parameters are:

x0 = 0.1044 cm
y0 = 0.1676 cm
z0 = 0.6707 cm

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
@civanch Can you sign for simulation, please?

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
