### PR TITLE
[12_3_X]Fix for hardcoded subdetector id in PPS reconstruction code

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
This PR is a backport, original PR: https://github.com/cms-sw/cmssw/pull/38208

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix,ctpps

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38208

**Comment by tvami** [comment]
urgent 
 * needs to be in the release that's used on June 13

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by civanch** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- backport of https://github.com/cms-sw/cmssw/pull/38208
- no reco changes

**Comment by qliphy** [comment]
An https://github.com/cms-sw/cmssw/issues/38268 is opened: 136.8562 is failing in master IB.

**Comment by qliphy** [comment]
+1
as discussed at this week's ORP, this PR can be merged.  The failing workflow is for Run-2 is to be fixed in a following PR https://github.com/cms-sw/cmssw/issues/38268

**Pull request merged**
