### PR TITLE
Migrate TkDetMapESProducer to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates TkDetMapESProducer to EventSetup consumes as part of #26748.

#### PR validation:

Code compiles, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by pohsun** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
