### PR TITLE
Run2-hcx54 Transfer the geometry parameters in a separate class so that they can be accessed from DB as well as XML

### PR DESCRIPTION
**Pull request by bsunanda**
Introduce geometry version to handle square as well as hexagonal cell

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 The unit test failure is not due to this. It was there in the IB and there is a fix in PR 12438. Please merge the PR12438. All developments for HGCAL are now stuck

**Comment by ggovi** [comment]
@bsunanda 
for a new CondFormats you should follow a guideline you can find in:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCondSystemLayout#Guideline_for_creating_new_packa
Namely, here you are missing the entries in   CondCore/GeometryPlugins and the ones in CondCore/Utilities as explained in the table.

Thanks.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by lgray** [comment]
@bsunanda If this is part of the chain of pull requests that need to go in. Could you rebase this on top of the latest CMSSW?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
This PR is messed up and a new PR with the basic content of this plus correction is no submitted bsunanda:Run2-hcx57 (12721). So closing this PR

**Pull request closed without merging**
