### PR TITLE
Add missing newlines in PhysicsTools modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
PhysicsTools/PatAlgos
PhysicsTools/TagAndProbe
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by tvami** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
