### PR TITLE
Fix one paramenter in the hltPAGoodFullTracks module

### PR DESCRIPTION
**Pull request by perrotta**
Fix one paramenter in the hltPAGoodFullTracks module of the PPref HLT menu (only HLT menu affected)
This is needed in view of the MC production, see https://its.cern.ch/jira/browse/CMSHLT-693

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please  test

**Comment by perrotta** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi @perrotta 
It seems you updated only the development menus, but not the frozen menus (ppRef and HIon).
I think both should be updated.

**Comment by perrotta** [comment]
@Martin-Grunewald : the frozen ppref menu was updated (see the last commit in this PR). I did not update the frozen HIon menu, instead, because there was nothing to update in it.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
