### PR TITLE
Run3-hcx200 dump specific collections

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Examine the contents of 3 types of collections (SimHit, Digi, RecHit) of Hcal to verify the contents

#### PR validation:

Used to test the effect of some corrections of Hcal geometry

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
@bsunanda this PR is not adding or modifying any HCAL histogram, is this expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-14-2300+4e0f52/31694/dqm-histo-comparison-summary.html

**Comment by bsunanda** [comment]
This PR just provides a tool for dumping some files to evaluate if we can compare o/p's from SIM/DIGI/LocalRECO results without trying the standard DQM results. So it does not add any new plots nor modifies the content of any plot

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
