### PR TITLE
backport of CASTOR rechitcorrector and noise simulation fixes

### PR DESCRIPTION
**Pull request by hvanhaev**
This is a back port of changes already included in the master, as discussed in PR: https://github.com/cms-sw/cmssw/pull/22424 

This contains a fix in the CASTOR noise simulation, and updates in the rechitcorrector module.
It would be good to have these too in CMSSW_76X for analyses with 2015 data.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@slava77 , correct we do not have 76X IBs running. 
@fabiocos if this is needed then should we enable 76X IBs for a week?

**Comment by slava77** [comment]
@smuzaffar @fabiocos 
can we revive a 76X IB?
I suppose that only one will be needed to run the tests for this PR (even if the tests are started or remade a few days after that IB is made)

**Comment by perrotta** [comment]
backport of #22424

**Comment by perrotta** [comment]
@hvanhaev : in case you want to proceed with this proposed backport, the same adjustments that guarantee the preservation of the current behaviour as in #23894 should be also ported here

**Comment by hvanhaev** [comment]
Ok thanks, I can update this PR too yes, should be ok.

Cheers,
Hans

On 28 Aug 2018, at 15:14, perrotta <notifications@github.com<mailto:notifications@github.com>> wrote:


@hvanhaev<https://github.com/hvanhaev> : in case you want to proceed with this proposed backport, the same adjustments that guarantee the preservation of the current behaviour as in #23894<https://github.com/cms-sw/cmssw/pull/23894> should be also ported here

**Comment by perrotta** [comment]
@cmsbuild please test
(@smuzaffar : thank you for setting up the 76X IB!)

**Comment by smuzaffar** [comment]
@perrotta , please note that 76X for production architecture is not yet finished. Looks like it is taking too much time in extracting the debug symbols, we are looking at it. Once the IB is available we will start the tests for this PR.

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
There are differences in the comparisons.

They were already there also before the last revert, see https://github.com/cms-sw/cmssw/pull/23895#issuecomment-417158657: my fault having overlooked them.

They must be explained before we can proceed with the backport. And one should also investigate why those difference show up only here in 76X (quite a lot of workflows) and not in 80X.

Please @hvanhaev have a look

**Comment by hvanhaev** [comment]
Hi Andrea,

Is there a twiki page or so where I can figure out to what comparison to look at?
If I click on “Comparison with the baseline” I get a very cryptic list of directories and I have no idea where to look at.
If I open one random directory, e.g. 25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/
I see that there are e.f. a lot of failures in DQM, but none in Castor…
If someone can point me to a manual on how to interpret all this that would help me a lot.

Thanks,
Hans

On 10 Sep 2018, at 12:32, perrotta <notifications@github.com<mailto:notifications@github.com>> wrote:


There are differences in the comparisons.

They were already there also before the last revert, see #23895 (comment)<https://github.com/cms-sw/cmssw/pull/23895#issuecomment-417158657>: my fault having overlooked them.

They must be explained before we can proceed with the backport. And one should also investigate why those difference show up only here in 76X (quite a lot of workflows) and not in 80X.

Please @hvanhaev<https://github.com/hvanhaev> have a look

**Comment by perrotta** [comment]
@hvanhaev @fabiocos 

Slava reminded me this old issue that was fixed since 8_0_X, but never backported to 7_6_X:
https://github.com/cms-sw/cmssw/pull/13506

What we see here in the jenkins comparisons exactly corresponds to what was observed at the time, and has nothing to do with Castor in any case. That is therefore the origin of the (kind of random) differences observed, and it is confirmed that this pull request do not change the outputs with the default config which is implemented.

**Comment by hvanhaev** [comment]
Dear Andrea,

Thanks a lot for the information regarding the comparisons (now I know where to look at) and the actual reason for the differences.

Cheers,
Hans

On 10 Sep 2018, at 16:21, perrotta <notifications@github.com<mailto:notifications@github.com>> wrote:


+1

  *   Correct backport of the code needed to apply fixes for the analysis and reprocessings of Castor data, which do not change the previous behaviour in its default configuration: the last addition since previous reco signature just reinforced it.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@civanch you already signed, now the behaviour is fully backward compatible, in case please sign it again for reference

**Pull request merged**
