### PR TITLE
DbOutputService: Clean up of commented out code and printouts

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Following the recent refurbishment, here we are removing commented code and printouts left over.

#### PR validation:

Package Unit and Integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
@ggovi Shall we proceed with the merge?

**Comment by ggovi** [comment]
@silviodonato sure, thanks a lot!

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
