### PR TITLE
NanoAOD developments, 29Nov2018 version [104X]

### PR DESCRIPTION
**Pull request by peruzzim**
As #25368, for the master branch.

This one does not depend on any other PR that is not merged yet.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@peruzzim @fgolf ping

**Comment by peruzzim** [comment]
@fabiocos I'm sorry I don't have a lot of experience with interpreting the outcome of comparisons...
Could you please confirm that only nanoAOD products are changing?
I also see some comparisons showing difference in logErrorHarvester which I cannot interpret.

**Comment by fabiocos** [comment]
@peruzzim looking at the summary of failing comparisons, following the link above, https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-11-30-1100+25373/29585/validateJR.html

I see differences in workflows 1325.7 (NanoAOD) and in wf 8, which is seen in other comparisons and looks unrelated to this PR. The failure in logErrorHarvester for wf 25202 should depend on the event processing order I believe and it is not very significant.

**Comment by peruzzim** [comment]
+1

Thanks, we cannot accurately check the differences in NanoAOD within this setup, but we have done that while preparing the PR and will do it again during the validation of the campaign.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
