### PR TITLE
Added handling of corrupted orbit ID and timestamp;Added support for file path convention of DAQ 2

### PR DESCRIPTION
**Pull request by grasph**
Added handling of corrupted orbit ID and timestamp
Added support for file path convention of DAQ 2

Code used in P5 for ECAL laser monitoring system.

### CODE REVIEW

**Comment by grasph** [comment]
Why did the pull go to CMSSW_7_4_X and not CMSSW_7_3_X? I started from cmsrel CMSSW_7_3_1_patch2 and used  git-cms-addpkg.
This commit must be included in all releases > CMSSW_7_3_1_patch2.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
looking at DQM differences:
DT FedIntegrity entries disappeared
wf8_fedintegrity

(the plot is from jenkins test for 8.0; to reproduce with ``` runTheMatrix.py -l 8.0 ```
@deguio @danduggan  have you seen these plots change for no apparent reason?

**Comment by grasph** [comment]
I've corrected issues reported in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7565/2378/llvm-analysis/. For EventFilter/EcalRawToDigi I've only corrected the code I've modified or code that I know. 
I don't know how to fix:
ThreadSafety    inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule       EventFilter /EcalRawToDigi /interface /MatacqProducer.h MatacqProducer 45 1 View Report
ThreadSafety    inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule       CalibCalorimetry /EcalLaserSorting /interface /LaserSorter.h           LaserSorter 44 1 View Report
ThreadSafety    inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule       EventFilter /EcalRawToDigi /interface /EcalDumpRaw.h                   EcalDumpRaw 32 1 View Report

I've made a git push my-cmssw from-CMSSW_7_3_1_patch2:EcalLaserSortingUpdate

but I don't know how to make the new pull request: I don't have the green pull request I had the first time.

Philippe.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
@slava77 
I didn't notice this before. from:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-04-1400+7565/5921/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/FED.html

everything seems consistent to me though.
F.

**Comment by slava77** [comment]
I don't think RelMon is configured properly

In RelMon logs:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-04-1400+7565/5921/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOSRelMonComp-8.0.log

Studying directory FED, 11/24
Bin 771bin: bindiff 10.0
Bin 772bin: bindiff 10.0
Bin 773bin: bindiff 10.0
Bin 774bin: bindiff 10.0
Bin 775bin: bindiff 10.0
Bin 776bin: bindiff 10.0
Bin 777bin: bindiff 10.0
Bin 778bin: bindiff 10.0
Bin 779bin: bindiff 10.0
Bin 780bin: bindiff 10.0
Histogram FedEntries differs: nok: 843.0 ntot: 851

So, the histogram is different (it's exactly the same histogram as the
one I posted,
just parsed with another script).



On 2/5/15 8:22 AM, deguio wrote:
> @slava77 <https://github.com/slava77>
> I didn't notice this before. from:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-04-1400+7565/5921/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/FED.html
> 
> everything seems consistent to me though.
> F.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7565#issuecomment-73053241>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by slava77** [comment]
@nclopezo @degano @ktf 
Could you please check the settings of the RelMon running in jenkins.
Why does it not display differences.
The specific case in https://github.com/cms-sw/cmssw/pull/7565#issuecomment-73055393
can be used as a reference example.

**Comment by deguio** [comment]
ciao @slava77 
the difference could be due to a huge PR merged recently for DTs. I will check.
thanks for noticing,
F.

**Comment by slava77** [comment]
+1

https://github.com/cms-sw/cmssw/pull/7565	 0e013fa
reco code is minimally affected, getByToken/consumes is done is very good;  (and the other parts make some reasonable sense)
jenkins is OK
there are no differences this time.
So, probably that DT FED plot was just a result of jenkins tests including something else along the way.

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
