### PR TITLE
Updating Pixel Local Reco calibrations for 2017 Upgrade simulation

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in GT
## Upgrade
- **PhaseI design scenario** : [75X_upgrade2017_design_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_upgrade2017_design_v6) as [75X_upgrade2017_design_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_upgrade2017_design_v5) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_upgrade2017_design_v6/75X_upgrade2017_design_v5): 
  - New Pixel SIM LA for Phase-I
  - New Pixel LA for Phase-I 
  - New Pixel templates for Phase-I 
  - New Pixel SIM gains for Phase-I
  - New Pixel GenErrors for Phase-I
  - New Pixel gains for Phase-I
  - New Pixel quality for Phase-I

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@mmusich should this be closed as superseded by #12475 ?

**Comment by mmusich** [comment]
@slava77 yes, correct. Let me close it.

**Comment by mmusich** [comment]
-1
superseded by #12475.

**Pull request closed without merging**
