### PR TITLE
Changes to HLT online DQM monitoring code for HI run in 81X

### PR DESCRIPTION
**Pull request by varuns23**
The PR is made using CMSSW_8_1_X_2016-10-25-1100

@mtosi @vanbesien @diguida @dmitrijus @silviodonato

### CODE REVIEW

**Comment by stahlleiton** [comment]
Hi @varuns23 , could you also add the dimuon mass plots for L1/L2/L3 PADoubleMuon10, included in the following 81X PR https://github.com/cms-sw/cmssw/pull/15759 for pPb. Thanks!

**Comment by varuns23** [comment]
Just confirming if the tests already started for this PR?

@mtosi @diguida @dmitrijus @vanbesien @silviodonato

**Comment by silviodonato** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
