### PR TITLE
Tracker Alignment Payload Inspector: migration to new class templates

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is purely technical. It consists of two commits:
   * f25417d migrates the Tracker Alignment Payload Inspector classes to new `PayloadInspector` class interfaces introduced in PR #29622
   * ef0897d  makes use of the namespace `cond::payloadInspector` in all `CondCore/AlignmentPlugins` plugins avoiding heavy repetitions in the code.

#### PR validation:

Relies on existing unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, not backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@ggovi ping?

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
