### PR TITLE
Revert  PR 25975 "Change devel build to use pybind11 for cmsRun"

### PR DESCRIPTION
**Pull request by fabiocos**
This reverts commit fcf7e7029a1421d4c8e96cea619e0806b22c01e7.

#### PR description:

This PR replaces #26291 , updating in the same spirit 10_6_DEVEL_X to bring it in sync with 10_6_X, before merging #26278 .

#### PR validation:

This revert just make 10_6_X and 10_6_DEVEL_X branches coincide.

### CODE REVIEW

**Comment by fabiocos** [comment]
@davidlange6 I think that what you really mean with #26291 is now this. I cross checked that #26278 merges smoothly on top of this.

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
thanks - i don't think there is much point in figuring out how to test this..

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
