### PR TITLE
Increase SiPixel L1 cluster threshold from 2000 to 4000e, synchronize channel threshold between HTL and offline

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Increase the SiPixel L1 cluster threshold from 2000 to 4000e making it the same as all other layers.
With the new L1 detector the lower thresholds should not be needed anymore as there is a clear separation between real clusters and junk (see the attached plot). The change will affect the cluster charge distribution for L1, the lower edge will shift from 2000
to 4000e.

Cluster_charge

In addition, the PR sets the `SiPixelClusterProducer` `ChannelThreshold` at the HLT to 10 to make it in sync with the offline reconstruction.

This is a resubmission of https://github.com/cms-sw/cmssw/pull/35506 with the additional Run 3 modifiers for the GPU code and the related HLT modifiers.

#### PR validation:

Run RECO on raw data from the cosmic run 344420.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport needed.

@dkotlins @mmusich

### CODE REVIEW

**Comment by mmusich** [comment]
Hi @ferencek, I think also the "legacy" HLT configuration should be updated at
`HLTrigger/Configuration/python/customizeHLTforCMSSW.py`

**Comment by VinInn** [comment]
Take also the opportunity to lower the ChannelThreshold to 10?
MInd: there are at least 4 clusterizers in HLT config that I know...

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by mmusich** [comment]
> MInd: there are at least 4 clusterizers in HLT config that I know...

I think there's a way to reconfigure them all:
```python
def customiseForXXXX(process): 
   for producer in producers_by_type(process, "SiPixelClusterProducer"): 
      producer.ChannelThreshold = cms.int32(10)
   return process 
```

**Comment by tsusa** [comment]
> > MInd: there are at least 4 clusterizers in HLT config that I know...
> 
> I think there's a way to reconfigure them all:
> 
> ```python
> def customiseForXXXX(process): 
>    for producer in producers_by_type(process, "SiPixelClusterProducer"): 
>       producer.ChannelThreshold = cms.int32(10)
>    return process 
> ```

I am preparing PR for this part

**Comment by ferencek** [comment]
@tsusa, so you will take care of lowering the ChannelThreshold to 10 in a separate PR, right?

**Comment by tsusa** [comment]
> @tsusa, so you will take care of lowering the ChannelThreshold to 10 in a separate PR, right?
rigth

**Comment by tsusa** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
@ferencek could the title and description of the PR changed to reflect this is dealing with **SiPixel** Layer1?

**Comment by mmusich** [comment]
@cmsbuild, please test with #35493

**Comment by missirol** [comment]
@ferencek (@tsusa , @mmusich)

for the HLT update, I checked with @Martin-Grunewald , and I understood that the preferred method is to file a JIRA ticket
(see this [example](https://its.cern.ch/jira/browse/CMSHLT-2136)). The main reason is to have a reference on JIRA for HLT changes that are not just technical.

It could be a single JIRA for both parameter changes (`ClusterThreshold_L1` and `ChannelThreshold`), unless Martin objects.
Once the ticket is closed, the next time the menus are updated in CMSSW, they will contain these changes. This means `customiseFor35518` is not needed in this PR.

The customisation for 2018 should stay, of course. I would suggest to change the name `customizePixelL1ClusterThreshold` to `customisePixelL1ClusterThresholdForRun2Input` or similar (to be consistent with the naming of other similar functions in that file).

**Comment by ferencek** [comment]
Thanks, @missirol, for the comment. Your suggestions should now be implemented. A JIRA ticket could be created once @tsusa  creates a separate PR changing `ChannelThreshold`.

**Comment by mmusich** [comment]
> The main reason is to have a reference on JIRA for HLT changes that are not just technical.

This means offline and GPU-based reco will go out-of-synch with HLT reco until the table is updated (I guess that will be made available only at the next pre-release).

**Comment by tsusa** [comment]
> Thanks, @missirol, for the comment. Your suggestions should now be implemented. A JIRA ticket could be created once @tsusa creates a separate PR changing `ChannelThreshold`.

@missirol 
do we need a PR for ChannelThreshold, if JIRA ticket will be made?

**Comment by missirol** [comment]
> @missirol do we need a PR for ChannelThreshold, if JIRA ticket will be made?

If the only goal is to change a parameter value in the HLT config, then the JIRA is enough. Obviously, if a customisation for Run-2 is needed (like here for `ClusterThreshold_L1`), then that one still needs to enter CMSSW via a PR.

**Comment by missirol** [comment]
> > The main reason is to have a reference on JIRA for HLT changes that are not just technical.
> 
> This means offline and GPU-based reco will go out-of-synch with HLT reco until the table is updated (I guess that will be made available only at the next pre-release).

True, and I don't know if there is a better way. I guess one could consider having a change like this enter via CMSSW (iow, the customisation numbered by PR), and file a JIRA that simply documents it. But I don't know if there are downsides to that. Martin can comment, if needed.

**Comment by missirol** [comment]
please test

**Comment by tsusa** [comment]
here is a link to the JIRA ticket https://its.cern.ch/jira/browse/CMSHLT-2165

**Comment by Martin-Grunewald** [comment]
If it is required to be in sync then it is better to leave the customisation in the file, but still have the JIRA ticket.
Likewise, if the two parameters need to be changed together, it should be in one PR and one JIRA.

**Comment by ferencek** [comment]
`customiseFor35518(process)` is now reintroduced into the PR

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
I see that in the reco comparisons the differences are in the Run-3 workflows (expected); they start from the number of clusters and then occasionally propagate downstream to tracking and further higher level quantities.

- In 2021 workflows (no PU) the number of clusters goes down by around 0.02%, which I guess is negligibly small
- In the 2023 workflow 12434.0 (also no PU) there are 0.3% fewer clusters and 1.7% in BPIX1 
image
are these noise clusters or is this going to lead to efficiency losses?

@cms-sw/trk-dpg-l2  please check/comment.
Thank you.

**Comment by tsusa** [comment]
image

@slava77, from the on-track cluster plot for the same wf (12434.0), which show the difference in 1/486 entries, it seems that those are mostly noise clusters

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35518	29b167f
- code changes in the reco code are in line with the PR description
- jenkins tests pass and comparisons with the baseline show expected rather small differences in the run3 workflows as described in https://github.com/cms-sw/cmssw/pull/35518#issuecomment-934918548; the larger differences in the 2023 workflow was confirmed to be from noise hits
    - there are also some unrelated small differences in 1325.81  (2017 nano) and  136.731 (2016 data reco) visible for ML inference, which is known to be not exactly reproducible on different architectures (`SSE4.1 SSE4.2 AVX AVX2 FMA` in the baseline vs `SSE4.1 SSE4.2 AVX` in this PR tests)

**Comment by missirol** [comment]
+hlt

* non-technical updates

* these two parameter changes will enter the next HLT menus in 12.1.X (once the menus are recreated and PR'd; until then, the changes are done via a customisation):
  - `ChannelThreshold = 10` is a fix which resyncs HLT to Offline (see [HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/pixelOfflineSW/1587/1/2.html))
  - `ClusterThreshold_L1 = 4000` is an update for the new Layer-1 of BPIX
  - both changes apply to all instances of `SiPixelClusterProducer` at HLT

* documented in [CMSHLT-2165](https://its.cern.ch/jira/browse/CMSHLT-2165)

**Comment by fwyzard** [comment]
Please note that this PR should be merged at the same time as https://github.com/cms-sw/cmssw/pull/35570 , to make sure the GPU customisation of the HLT remains coherent with the changes introduced here.

**Pull request merged**
