### PR TITLE
L1T Phase2 NNTau reconstruction based on PF and Puppi (11_1_X backport)

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:
11_1_X:  L1T Phase2 NNTau reconstruction based on PF and Puppi
 - producers (PF and Puppi) and configurations
 - included in L1T Phase2 sequence
 - included in FEVTDEBUG Phase2 EventContent

all review comments from  #31601 applied ( #32506 ).
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport to  #31601 +  #32506

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test abort

**Comment by rekovic** [comment]
don't see that the tests are started. so will abort and restart the testing

**Comment by rekovic** [comment]
please abort test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by silviodonato** [comment]
@rekovic please update the PR description specifying that this is a backport of  #31601 + #32460 .
PR #31600 is close

**Comment by silviodonato** [comment]
urgent
for the HLT TDR release (11_1_X)

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
