### PR TITLE
backport all fixes to 75X (for HI quarkonia and b-jet)

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by covarell** [comment]
@alberto-sanchez , can you please check I did the backport correctly? (i.e. it synchronized with the HEAD)

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by alberto-sanchez** [comment]
@covarell  All changes are there.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
