### PR TITLE
[12_5_X] Fix Pixel Clusters for Phase2 HLT Menu

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

A simple fix to `siPixelClusters` constants. Backport to `12_5_X` of #39323.

#### PR validation:

See #39323. Tracking efficiency recovered.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 39434.75
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by AdrianoDee** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39323

**Comment by perrotta** [comment]
+1

**Pull request merged**
