### PR TITLE
Added new categories (DSTJets,DSTMuons) for scouting triggers.

### PR DESCRIPTION
**Pull request by ryonamin**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by duanders** [comment]
Hi @deguio , can we have a re-test?

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by ryonamin** [comment]
Do you think the failure is related to this PR?

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
