### PR TITLE
HLT menu development for `12_6_X` (2/N) [`13_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_6_X`.

This is the PR for the `master` branch, which will then be backported to `12_6_X` (the latter is the release cycle used for HLT-menu development for Run 3).

It includes the migration of the "Fake*" and non-frozen menus to the `ConfDB` template for `CMSSW_12_6_0`. The frozen "V1.5" menu is also updated with technical changes, and migrated to a new release template.

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2583](https://its.cern.ch/jira/browse/CMSHLT-2583): [TSG] Review of PS columns in the combined HLT menu
  - [CMSHLT-2586](https://its.cern.ch/jira/browse/CMSHLT-2586): [TSG] Move seed of `DST_HLTMuon_Run3_PFScoutingPixelTracking` before HLT prescale
  - [CMSHLT-2589](https://its.cern.ch/jira/browse/CMSHLT-2589): [JME] Add HLT PFMET collections to `ReleaseValidation` EventContent
  - [CMSHLT-2590](https://its.cern.ch/jira/browse/CMSHLT-2590): [B2G] Removal of AK8Jet+TrimMass and AK8PFHT+TrimMass triggers from the combined menu

In addition, the real-data EDM input of the HLT-HIon tests is updated to use events from HIRun2022A (standard HIon Raw, not RawPrime), see https://github.com/cms-sw/cmssw/pull/40339#issuecomment-1354606056.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_12_6_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
5e384ffe94821d3f509fc54b57030563ba783ec7 adds the minimal change to update the real-data EDM input of the HLT-HIon tests, to use events from `HIRun2022A` (standard HIon Raw, not RawPrime).

The logic of how/when `rawDataCollector` is replaced with `rawDataRepacker` seems convoluted [1], and it will be possibly improved in a separate PR [2].

[1]
https://github.com/cms-sw/cmssw/blob/313882e5e642400489929bcae78886a3d98ad63d/HLTrigger/Configuration/python/Tools/confdb.py#L247-L251
https://github.com/cms-sw/cmssw/blob/313882e5e642400489929bcae78886a3d98ad63d/HLTrigger/Configuration/python/customizeHLTforALL.py#L54-L66

[2] As an example, the config-dump of `OnLine_HLT_HIon.py` currently gives
```py
rawPrimeDataRepacker = cms.EDProducer("EvFFEDExcluder",
  src = cms.InputTag("rawDataCollector")
  ...
```
which seems in general incorrect, as it should rather be
```py
rawPrimeDataRepacker = cms.EDProducer("EvFFEDExcluder",
  src = cms.InputTag("rawDataRepacker")
  ...
```

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - differences in outputs of PR tests are in line with the updates to the HLT GRun menu, and the change in name of the "Fake*" menus

**Comment by perrotta** [comment]
+1

**Pull request merged**
