### PR TITLE
Phase2-hgx241 Complete masking for all types of partial wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Complete masking for all types of partial wafers. Now one can get the partial wafer type and the rotation position from the layer number, u, v values

#### PR validation:

Use runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
