### PR TITLE
Clang-format example for FWCore/Framework (v1)

### PR DESCRIPTION
**Pull request by davidlange6**
same settings as in #25893

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by makortel** [comment]
It seems that the `interface` directory was omitted? (I was trying to look examples of template definitions)

**Comment by makortel** [comment]
> It seems that the `interface` directory was omitted? (I was trying to look examples of template definitions)

Actually there seems to no header files even from `src`.

**Comment by davidlange6** [comment]
hum, not intentionally. but yes, thats right. let me fix that

**Pull request closed without merging**
