### PR TITLE
AssociatonByHits with GEMs: porting to 76X

### PR DESCRIPTION
**Pull request by calabria**
This PR contains the new module needed to associate the GEM tracking recHits (GEMHitAssociator) and the all the changes needed in the AssociatorByHits to make it associate also GEM tracking recHits. The association of GEM hits is disabled by default to avoid problems when the GEM detectors are not present in the geometry scenario. Moreover a new plot representing the averange number of GEM tracking recHits vs eta hs been added in the MuonTrackValidator. It is not filled by default, it has to be switched on when GEM detectors are present in the simulation. I checked the code with the following runTheMatrix command and all tests ended successfully: runTheMatrix.py -l limited -i all (with the use of GEM disabled, but I tested it also with GEM hits present and GEM association enabled without problems).

### CODE REVIEW

**Comment by abbiendi** [comment]
Hi Cesare,
in Validation/RecoMuon/plugins/MuonTrackValidator.cc
you should use "useGEMs_" also to the booking steps, not only to the filling, otherwise it is not much useful (as histograms will be created anyway and will take room in memory)
   Giovanni

**Comment by calabria** [comment]
Ciao Giovanni ( @abbiendi ), ok done.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
