### PR TITLE
Move to steady_clock in the framework

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

For all duration measurements, switch to using the steady_clock.

#### PR validation:

All framework tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
This PR addresses https://github.com/cms-sw/cmssw/issues/41199 fully, right?

**Comment by Dr15Jones** [comment]
I hope so.

**Comment by makortel** [comment]
+core

RelVal-INPUT timeout should be unrelated (and maybe not worth of repeating the tests).

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
