### PR TITLE
Prevent too many chunks from being added per function call.

### PR DESCRIPTION
**Pull request by bbockelm**
We have a limit of 1,024 chunks per IO vector and stop adding new
chunks once we hit 1,000.  However, the consumeChunk\* calls previously
were able to add an unlimited number of new chunks - meaning that we
could go past the limit in a single loop iteration.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please also make versions for 7_5 and 7_6.

**Comment by bbockelm** [comment]
@cmsbuild @Dr15Jones - what happened to the jenkins tests?

I was planning on cherry picking to 7_5 / 7_6 once the tests passed.

**Comment by Dr15Jones** [comment]
@smuzaffar Were the tests stuck?

**Comment by bbockelm** [comment]
@smuzaffar any updates on the jenkins tests for this one?

**Comment by smuzaffar** [comment]
please test
I can not find any histosy of this OPRin jenkins tests, so triggering it again

**Comment by bbockelm** [comment]
@smuzaffar - are we just unlucky for this PR?

**Comment by davidlange6** [comment]
@cmsbuild please test

should be better now

**Comment by smuzaffar** [comment]
I thought that adding "please test" will trigger the tests but looks 
like it does not. I guess one needs to remove the "test started" label too.
Anyway, I have force the tests in jenkins now

**Comment by smuzaffar** [comment]
@davidlange6 , do we want to add in 74X without testit in 75X/76X?

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@davidlange6 How do you want to proceed with actual large scale test of this? Shahzad asked if this really should be in 7_5 or 7_6 first. Or did I miss a related pull request?

**Comment by bbockelm** [comment]
@davidlange6 - What's the strategy on this one?

**Comment by davidlange6** [comment]
@bbockelm -good point - is not there not a 75x or 76x version of this?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
