### PR TITLE
Skip invalid channels in the GPU HCAL RecHit producer

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR consistes of two parts:
  - the GPU code now marks as invalid (setting chi² = -9999.) the HCAL channels for which it cannot determine the SOI;
  - the CPU code that converts from SoA to legacy format now skips all invalid channels.

See h#39693 for a discussion on the underlying issues.

#### PR validation:

Tested on top of CMSSW_12_4_10 over the events that caused the HLT to crash in runs 357898, 359998, and 360295.
Without these changes the original crash can be reproduced in multiple files:
```
----- Begin Fatal Exception 14-Oct-2022 20:27:30 CEST-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 360295 lumi: 174 event: 264575349 stream: 7
   [1] Running path 'Path'
   [2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
Exception Message:
Unavailable Conditions of type HcalChannelQuality for cell (0x0) 
----- End Fatal Exception -------------------------------------------------
```

With these changes the HLT jobs run to completion on almost all those files (barring one that is affected by a different, ECAL-related crash).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW 12.4.x and 12.5.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
assign hcal-dpg

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
urgent

Relatively urgent, as the 12.4.x backport should be deployed online ASAP.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@cms-sw/hlt-l2 FYI

**Comment by mandrenguyen** [comment]
In the GPU comparisons, do we expect this kind of change in the raw energy distribution of HBHE rechits?
[all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522c_log10HBHERecHitsSorted_hbhereco__RECO_obj_obj_eraw16](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_6_X_2022-10-14-1100+683156/53413/validateJR/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522c_log10HBHERecHitsSorted_hbhereco__RECO_obj_obj_eraw16.png)

It's not obvious to me why skipping invalid channels would have such an effect.

**Comment by mariadalfonso** [comment]
@mandrenguyen 

It's not only the raw energy that changes, it's also the energy after the ootfit

see energy 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_6_X_2022-10-14-1100+683156/53413/validateJR/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522c_log10HBHERecHitsSorted_hbhereco__RECO_obj_obj_energy2.png

see chi2 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_6_X_2022-10-14-1100+683156/53413/validateJR/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522/all_OldVSNew_TTbar14TeV2021hcalGPUwf11634p522c_log10HBHERecHitsSorted_hbhereco__RECO_obj_obj_chi210.png
before is identical 0 now it's a number, so that fit runs.

I suspect that is triggered by the initialisation of the soi to -1

**Comment by fwyzard** [comment]
Are there plots for the GPU vs CPU comparison of the energy, chi², etc. ?

**Comment by mandrenguyen** [comment]
@fwyzard At least I don't find such plots.  I can only see that there are no significant differences in CPU comparisons, but that this one particular GPU workflow is showing non-trivial differences.

**Comment by fwyzard** [comment]
test parameters:
  - enable_tests = gpu
  - workflows_gpu = 11634.523

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
`11634.523` should include the GPU vs CPU comparison plots

**Comment by fwyzard** [comment]
in fact, if it works we should probably replace `11634.522` with `11634.523` in the GPU tests, _etc._

**Comment by missirol** [comment]
@cms-sw/hcal-dpg-l2 , what is your take on this PR?

It would be good to converge soon, to fix the HLT crashes reported in #39693.

**Comment by clacaputo** [comment]
> Are there plots for the GPU vs CPU comparison of the energy, chi², etc. ?

The GPU vs CPU energy comparisons show some differences in HE at low energy [1], but it could be just an effect of the different number of entries [2]. From [2], there should be also differences in HB, but they are not visible in [1]

[1] https://tinyurl.com/2ky3szdr
[2] https://tinyurl.com/2gwd4hcg

**Comment by fwyzard** [comment]
@cms-sw/hcal-dpg-l2, are there any plots that show the rechits reconstructed only on CPU or only on GPU ?

Also, did the `11634.523` workflow produce all the plots that came with `11634.522` ?

**Comment by mariadalfonso** [comment]
> @cms-sw/hcal-dpg-l2, are there any plots that show the rechits reconstructed only on CPU or only on GPU ?
> 
> Also, did the `11634.523` workflow produce all the plots that came with `11634.522` ?

Investigating now.
There are two separate issues: 
1) addressing the crash due to wrong SOI and NumTS (scope of this PR)
2) resolve the CPU-GPU discrepancy (seen especially on HE, less in HB) seen also in some standard DQM

**Comment by mariadalfonso** [comment]
@fwyzard  @clacaputo @missirol
We can merge these PRs.


I did a (standalone) comparison of the CPU-GPU reco in the MC-ttbar events wf 11634.0 (starting from the same digi).
I confirm that I get equality. There is only about a 7% reduction of entries, due to non copying those that fails the channel quality.

Screen Shot 2022-10-17 at 23 10 03
Screen Shot 2022-10-17 at 23 08 28

So in the good cases where the soi and TS are well defined (always true in MC), this PR doesn't introduce any change.
From the sw point of view this just add some protection that was found useful based on Run1-Run2 experience.

From hw post of view, wrong soi and wrong #TS should not happen and the OPS team at P5 is looking into it.
I will look separately the data, as in addition to the crash was also seen some outlier.

359699_HBHE
359998_HB
359998_HE

**Comment by missirol** [comment]
@cms-sw/hcal-dpg-l2 , just a reminder that your signature is required in this PR.

**Comment by fwyzard** [comment]
@mariadalfonso can I ask you a couple of things? I'm sorry but I don't know where to look myself :-(
  - the differences that you pointed out in https://github.com/cms-sw/cmssw/pull/39738#issuecomment-1279695517, are they understood ? do they appear also in your standalone comparison ?
  - does the [11634.523 workflow](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_6_X_2022-10-15-1100+683156/53428/dqm-histo-comparison-summary.html) produce those plots ?

**Comment by rappoccio** [comment]
@mariadalfonso can you explicitly say "+1" so the bot picks up your approval?

**Comment by missirol** [comment]
(.. I think the signature needs to come from a member of https://github.com/orgs/cms-sw/teams/hcal-dpg-l2/members .)

**Comment by wang-hui** [comment]
+1

**Comment by rappoccio** [comment]
+1 

- Once IBs finalize with this, will merge the back ports and cut new 12_4 and 12_5 releases.

**Pull request merged**
