### PR TITLE
update Method3 with new time slew parametrization and response correction for data and MC

### PR DESCRIPTION
**Pull request by fwyzard**
- update Method3 with new time slew parametrization and response correction for data and MC
- customise the HLT for the updates to HCAL method 3

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
I've checked that the parameters are added to the HLT configuration only for Monte Carlo.
For data, the correct values should be taken from fillDescriptions().

**Comment by fwyzard** [comment]
rebased

**Comment by fwyzard** [comment]
+1

**Comment by slava77** [comment]
@cmsbuuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11100 c4b0590
- changes in the code are visually OK (in line with planned modifications)
- changes affect only HLT products/plots, confirmed by jenkins tests

**Comment by slava77** [comment]
... HLT plots change only in workflows with Method3 in place (MC workflows only in jenkins tests with running comparisons)

**Comment by abdoulline** [comment]
NB: updated part of MC Method 3 is based on new HcalTimeSlewSim. So the two should go (be activated) in sync...

**Comment by davidlange6** [comment]
@abdoulline - right, we need to get all of this in sync (either on or off) (plus we need a rebase)

**Comment by slava77** [comment]
ping
@fwyzard this doesn't merge

**Comment by fwyzard** [comment]
rebased

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by slava77** [comment]
will there be another rebase?

**Comment by fwyzard** [comment]
rebased on top of the latest CMSSW_7_6_X, which includes merging the 75x backport of this PR, #11101 .

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Is this still active?

**Comment by fwyzard** [comment]
I honestly do not know...

.A

**Comment by davidlange6** [comment]
It's waiting on validation of a fully consistent calibrations for all new hcal changes (happening in 75x)



On Oct 6, 2015, at 12:35 PM, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:

I honestly do not know...

.A

**Comment by davidlange6** [comment]
this should be fully included already in 76x.

**Pull request closed without merging**
