### PR TITLE
Updating Puppi Photon to ignore photons with large eta and to add back candidates

### PR DESCRIPTION
**Pull request by violatingcp**
Adds missing photon candidates with an eta cut to remove reconstruction issues at eta 3. These two features are needed to keep good performance in Puppi MET. Also, the test is script is updated with the actual computation of Puppi MET that should be used provided the weights are stored correctly.

### CODE REVIEW

**Comment by slava77** [comment]
@violatingcp 
please make a PR for 81X.
We will not review 80X until there is 81X version.

**Comment by slava77** [comment]
@cmsbuild please test

@violatingcp please add a link to a presentation in a JME meeting in  the PR description (edit the top block https://github.com/cms-sw/cmssw/pull/15429#issue-170659896)

**Comment by slava77** [comment]
The errors are related to this PR
e.g. in wf 136.731
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15429/14516/runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT+HARVESTDR2.log
```
----- Begin Fatal Exception 13-Aug-2016 03:00:16 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PuppiPhoton label='puppiForMET'
Exception Message:
MissingParameter: Parameter 'eta' not found.
----- End Fatal Exception -------------------------------------------------

```

**Comment by cvuosalo** [comment]
@violatingcp: When will the problems in this PR be addressed? When will the 81X version be created?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@violatingcp: The 81X version of this PR is still needed before this one can be approved. Where is it?

**Comment by violatingcp** [comment]
Pull request for 81X is added here #15562

**Comment by cvuosalo** [comment]
+1

For #15429 072976e69bc6169a293061a92b0943e6ea9b533a

Puppi photon revisions.

#15526 is the 81X version of this PR, and it has already been approved by Reco.  This PR and #15562 are identical except for slight differences in the original files in 80X and 81X.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-08-20-1100 show only small changes in Puppi jets and MET, as expected. An example of the small changes comes from Jenkins workflow 50202.0_TTbar_13, and it shows a slight decrease in low-pT jets, which were probably related to PU:
numthr

**Comment by slava77** [comment]
hold

added a formal hold label to denote that this is to be merged only once the rereco release is to be built

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1
"superseded" by #15772

**Comment by slava77** [comment]
@mariadalfonso 
should we expect imminent changes here following 
https://github.com/cms-sw/cmssw/pull/15669#issuecomment-245640402
?
Please clarify at your earliest.
Thank you.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
given no feedback here yet, it looks like we will default to pick #15772 and this PR will be dropped

**Comment by mariadalfonso** [comment]
@slava77 the idea is that we want to pursue still this PR
only as fall back we keep the #15772

**Comment by slava77** [comment]
On 9/8/16 1:24 PM, mariadalfonso wrote:
> @slava77 <https://github.com/slava77> the idea is that we want to pursue
> still this PR
> only as fall back we keep the #15772
> <https://github.com/cms-sw/cmssw/pull/15772>

Do you want to pursue this PR unchanged?

**Comment by mariadalfonso** [comment]
@slava77 we have the update commit with the DR in the 80X already just before the both started the test https://github.com/cms-sw/cmssw/pull/15429/commits/0b8cf5069f232e9e93e2f40e68452df1d23e7219

same we have in the 81X
https://github.com/cms-sw/cmssw/pull/15669/commits/b92cdaa9576520851f31b6a3d25d48026e478d4e

what I'm missing ?

**Comment by violatingcp** [comment]
After discussion with @mariadalfonso we have decided #15669 contains all the fixes we would like. The proposal of two additional steps would require a larger re-engineering and consequently we stay with the current #15429 for the 80X release and #15669 for the 81X provided the checks come back with the expected good performance.

**Comment by slava77** [comment]
@cvuosalo 
I ran tests using the same set up as earlier for #15772

... timing looks about the same (unclear if this is surprising or just a good thing)

Compared to results of #15772 (black) this PR shows even better MET performance
all_sign761b-patvssign761a-pat_relvalzee_13pu25nsc_patmets_slimmedmetspuppi__pat_obj_pt
all_sign761b-patvssign761a-pat_relvalzee_13pu25nsc_patmets_slimmedmetspuppi__pat_obj_significance

**Comment by cvuosalo** [comment]
+1

For #15429 0b8cf5069f232e9e93e2f40e68452df1d23e7219

Provisional approval to allow inclusion in imminent 80X release build.
Puppi changes to fix problems with photon candidates at high eta and to better handle PU.

This PR is related to #15562, #15669, and #15772 .

The code changes are satisfactory. Jenkins tests results seem not be accessible at the moment, but comparisons were successful. Extended tests results described above show the desired changes with no serious problems. When Jenkins and other test results become available, they will be reported in this thread.

**Comment by degano** [comment]
+1

**Comment by slava77** [comment]
unhold

merging or rereco PRs is now almost done.
The hold was to highlight that the PR was just for the rereco release.

**Comment by cvuosalo** [comment]
Jenkins test results show numerous small differences, all of them either expected or too tiny to be of concern. Two examples are shown below.

From workflow 1330.0_ZMM_13, the elimination of high-eta photons can be seen:

meteta

A plot from workflow 136.731_RunSinglePh2016B shows the increase in the photon Et fraction for MET:

photonet136

**Comment by cvuosalo** [comment]
A test of workflow 25200.0_ZEE_13 with 500 events against baseline CMSSW_8_0_X_2016-08-30-1100 shows numerous differences, most of them small, that are expected for this PR. Some examples are shown below.
all_mini_testpr15429vsorig_zeepuwf25200p0c_log10patjets_slimmedjetspuppi__reco_obj_energy
all_mini_testpr15429vsorig_zeepuwf25200p0c_log10patjets_slimmedjetspuppi__reco_obj_et
all_mini_testpr15429vsorig_zeepuwf25200p0c_patjets_slimmedjetspuppi__reco_obj_eta
all_mini_testpr15429vsorig_zeepuwf25200p0c_patjets_slimmedjetspuppi__reco_obj_hfhadronenergyfraction

**Comment by cvuosalo** [comment]
More results from the Z->ee test described in the previous entry.


metcl
metlog
sumet
metdiff
neuthadfrac
hfhadfrac
chhadfrac
effeta

**Pull request merged**
