### PR TITLE
Added new HLT Collections (muon validation)

### PR DESCRIPTION
**Pull request by cedricpri**
Added new HLT Collections to be considered for the muon validation

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi,

tests failed on the same two workflows both times. Apparently a collection `tpToL3FromL1TkMuonAssociation ` is not found. 

These are the log files for both failing workflows: [10824.0 step3](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24371/30032/runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018.log) [250202.181 step4](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24371/30032/runTheMatrix-results/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step4_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25.log)

**Comment by cedricpri** [comment]
Thanks for reporting. There was indeed an issue that has now been fixed, We are looking into it and will submit a new PR soon, in the mean time I close this one.

**Pull request closed without merging**
