### PR TITLE
Adding missing scripts for ECAL TPG double weights + unit tests

### PR DESCRIPTION
**Pull request by valsdav**
Two scripts were missing in the CondDB utilities for the ECAL TPG double weights code

- `updateTPGOddWeightIdMap.py` 
- `updateTPGOddWeightGroup.py` 

The scripts are used to convert ECAL TPG txt config files to CondDB tags to be used in the emulator for private studies or uploaded in the global tag. 

Added unit tests for Ecal TPG weights mapping scripts. 

This PR has no side effects.

### CODE REVIEW

**Comment by francescobrivio** [comment]
@valsdav I understand these files are run manually to create the tags from the txt config files, but are there any unitTests already in place that test these scripts?

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
>  but are there any unitTests already in place that test these scripts?

If none, can you please make them?

**Comment by tvami** [comment]
@valsdav just to clarify: we are waiting for the introduction of the unit tests before merging this PR

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
the unit tests are failing
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5dc18/26503/unitTests/src/CondTools/Ecal/test/EcalTPG_updateOddWeightIdMap_test/testing.log

and
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5dc18/26503/unitTests/src/CondTools/Ecal/test/EcalTPG_updateWeightIdMap_test/testing.log

**Comment by tvami** [comment]
@cmsbuild , please abort
 * given that the unit tests are already failing there is no point in running the relvals

**Comment by valsdav** [comment]
I'm sorry there was a typo in the BuildFile. All the scripts now run correctly when I tested them manually.

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * newly introduced unit tests pass https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b5dc18/26591/unitTests/success.html

**Comment by qliphy** [comment]
+1

**Comment by makortel** [comment]
The EcalTPG_updateWeightGroup_test and EcalTPG_updateWeightIdMap_tests fail randomly in IBs, see #38964

**Pull request merged**
