### PR TITLE
update JetMET DQM to enable MiniAOD running, introduce PFCandidate maps ...

### PR DESCRIPTION
**Pull request by webermat**
This update includes additional 2D plots in eta and phi of PFCandidates, we monitor now variables used in quark gluon jet tagging and the PUJetID pass fraction. We enable running on MiniAOD. We switched to the threadsafe version of the JetCorrector. 
In addition we changed the structure of our monitoring plots. We have two categories of plots: 
an uncleaned category: here we don't filter by DCS flags and primary vertex cuts, no JetID is applied -> not to hide problems due to these cuts
a cleaned category: here we apply DCS flags, primary vertex cuts and JetID cuts.

we removed the uncleaned category for CaloMET and CaloJets
we added the cleaned category plots for type 1 corrected MET and charged hadron subtracted jets (to have a 1 to 1 comparison vs collections inside MiniAOD.

### CODE REVIEW

**Comment by deguio** [comment]
ciao @webermat 
sorry if I reply only now..

I have a couple of questions:
- I noticed that the number of bins used for the JetMet folder has increased by a factor of 7 even if the number of booked histos went up by a factor of 2 "only". I didn't check the details for every histo, but is there a way to optimize it? this would save memory.
- when you say that you enabled miniAOD, what do you mean? I see the miniAOD sequences are defined, but not run by default anywhere.  is this wanted? an option is to have them included in the DQM matrix.

thanks,
F.

**Comment by webermat** [comment]
Hi Federico,

we added a lot of 2D histograms for monitoring PFCandidates, both for all events and for a selection to get a handle on Out of time pileup. For OOT pileup we need to get our information from technical trigger bits, so we need to double the number of histograms there to take into account both bunch spacings. At least right now we have all possible histograms in the MET group had on its biggest wish list. We have already thought about possible alternatives if this prooves to be too memory expensive. We could also discuss shortly or after the PPD meeting if you have any suggestion of what to keep and what might be good to remove or how we could possibly reduce the memory consumption in a smart way.

For the MiniAOD: we implemented all changes to be able to run on MiniAOD. We though did not yet update the Harvesting modules, which could check if MiniAOD and full RECO give the same answers. We thought it might be good to wait until those are ready. But we could optionally still include it already by now in the DQM matrix.

Best,
Matthias
________________________________

**Comment by deguio** [comment]
just for the record. me and @webermat discussed in person. he, in contact with the validators, will try to reduce/optimize the histo/bin number. keeping on hold for now.
F.

**Comment by webermat** [comment]
We removed now the 2D PF candidate maps for the selections where we deem them not necessary. Some of the 2D maps have been removed altogether. We added instead 1D histograms which should enable us to spot possible problems and outliers in a similar manner. Hopefully this reduces the number of bins by quite a bit, so that we don't hit a critical point.

**Comment by deguio** [comment]
please test

**Comment by webermat** [comment]
Add one more flag to avoiding a duplication of PFCandidate histograms for two level of PfMet corrections (PFCandidates are the same for both MET types). I checked the workflows mentioned above locally (using CMSSW_7_4_0_pre1). At least then both workflows finish successfully. I suspect at least the JetMET DQM modules themselves are not responsible for the failure. For example workflow
 25.0_TTbar+TTbar+DIGI+RECO+HARVEST+ALCATT produced an output file as expected. The sequence itself has not been changed since late December. It worked back then, so I would guess it is not one of the producers called before the DQMAnalyzers are called (e.g. the HBHENoiseFilterResultProducer).

**Comment by degano** [comment]
@cmsbuild please test

**Comment by webermat** [comment]
More JET and MET OOT pileup diagnostics histograms were added as requested by the JetMET group today. Test results are not announced as successful or failed since the last update of the PR, thus I decided to rather update already now instead of next week.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1
thanks @webermat , the amount of resources used seems now reasonable.
F.

**Pull request merged**
