### PR TITLE
Fixed codes which causes memory issue by GEM onlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
There is an issue with GEM onlineDQM (#38666), which is due to the wrong way to keep the geometry information of GEM chambers. (See [this line](https://github.com/cms-sw/cmssw/pull/38908/files#diff-211b3bdbc65bb043eb340a211fdf6ea24c2e2b17d7cdeb26c535d197be5cee65).) It has been fixed by adapting a safer and lighter method.

#### PR validation:
Test are done with `cmsRun $CMSSW_RELEASE_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True`

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by francescobrivio** [comment]
Backported in #38694

**Pull request merged**
