### PR TITLE
MuonSegFit bugfix

### PR DESCRIPTION
**Pull request by jshlee**
this is a fix for the issue reported in https://github.com/cms-sw/cmssw/issues/14803

### CODE REVIEW

**Comment by jshlee** [comment]
@Dr15Jones - i changed std::vector<const TrackingRecHit*> to std::vector<std::shared_ptr<const TrackingRecHit>>

**Comment by slava77** [comment]
@cmsbuild please test

@jshlee did you check with valgrind that the issue is gone?
There were a few more similar issues, are they fixed with this as well?

**Comment by jshlee** [comment]
@slava77 - yes I did and they are gone.

**Comment by cvuosalo** [comment]
+1

For #14825 e3006edf967bb1a58c1849fae2c1ed90fe677c77

Bug fix for a memory management error in ME0 segment code. There should be no change in monitored quantities.

The code fix is satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-06-09-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
