### PR TITLE
https://github.com/cms-sw/cmssw/pull/7880 in 75X

### PR DESCRIPTION
**Pull request by silviodonato**
https://github.com/cms-sw/cmssw/pull/7880 in 75X

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
@silviodonato - please change the title to something descriptive for the release notes. Thanks!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@davidlange6
Why do 75X PRs need to be signed by ORP? 75X is still open...

**Comment by ktf** [comment]
@Martin-Grunewald I think the correct statement is that "75X is *not yet* open", pending 740 release.

**Pull request merged**
