### PR TITLE
fix Radix Sort for size = N*256+1

### PR DESCRIPTION
**Pull request by VinInn**
As the title says.

purely technical.
no regression expected as used in production only for vertex sorting that never exceeds 100 or so.

thanks @cericeci for pointing out the failure and provide a test

### CODE REVIEW

**Comment by VinInn** [comment]
@AdrianoDee @cericeci FYI

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.502
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Thanks Vincenzo

**Comment by fwyzard** [comment]
+heterogeneous

Sorry for the delay, I missed it while I was away.

**Comment by fwyzard** [comment]
type bugfix

**Comment by perrotta** [comment]
+1

**Pull request merged**
