### PR TITLE
Expand track information in lostTracks collection (10_6_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR expands detailed track information stored in the `lostTracks` collection (pat::PackedCandiates) in miniAOD for UL re-miniAOD processing, i.e. with `run2_miniAOD_UL`  modifier. The following changes are implemented:
* Track to PV association is preformed in a similar way as for tracks contained in `packedPFCandidates` collection (packed PF particles);
* Detailed track information is stored down to 0.5GeV instead of current 0.95GeV as done for packed PF particles (`packedPFCandidates`). Track covariance packing schemas are adapted from producer of the packed PF particle collection for more effective packing.

Note: Code was formatted with `scam b code-format` for easier backport and better comparison with master.

MiniAOD size changes were estimated with 1k of DY->LL evens with 2018 conditions and it is as follows:
* size increase of `patPackedCandidates_lostTracks__PAT`: 23%
* size increase of full miniAOD sample: 0.2%
* 1/4 of the increase comes from updated PV association information, while remaining 3/4 from lowering threshold to store detailed track info.

The changes are active only with `run2_miniAOD_UL`  modifier.

#### PR validation:

Tested with standard miniAOD workflow  with `run2_miniAOD_UL`  modifier.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

It is backport of #32242, needed for UL re-miniAOD production as agreed with XPOG.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #32242

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Backport ok: the extra information is only added when the `run2_miniAOD_UL` modifier is enabled
- Jenkins tests pass and show no differences wrt the baseline in the standard workflows: the only differences are in the 136.88811 re-miniAOD workflow, as expected

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
