### PR TITLE
Performance improvements for DQM startup

### LINKED ISSUE #215: Decrease startup time for DQM code
Profile checks (done to check #210) showed 30% of a short job was in 2 DQM functions.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Profiling workflow 1004.0 step2 showed > 30% of the short job time (just 10 events) was spent in two DQM routines
- MonitorElementData::Path::set
- DQMStore::findME<MonitorElementData::Path>

In both cases, the routines were creating and destroying a very large number of temporary strings.

#### PR validation:

Code compiles and workflow 1004.0 step2 appears to run fine. The newly creates unit test for MonitorElementData::Path::set passes.

fixes makortel/framework#215

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test 

I think the previous failures were from slow loading of the pileup files.

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Pull request merged**
