### PR TITLE
Fixes and modifications on GEM TnP efficiency plots

### PR DESCRIPTION
**Pull request by jo100sun**
#### PR description:
This PR introduces fixes and modifications to the GEM TnP efficiency plots.
The GEM TnP efficiency plots needed some fixes since they have inconsistent legends, overlapping stations and the wrong number of entries in some plots.

Changes:
Station Separation: GE11 and GE21 were overlapping on certain plots. These plots have been separated for each station for clarity.
Bugfix for Residual Plots: The residual plots are being filled even when there was no hit on the GEM to match the track to. This misrepresented the actual entry number. With this PR, filling occurs only when a hit is present.
Code Cleanup: Removed unnecessary parts of the code.
Legend Update: Legends have been updated for better clarity.

Bugfix on the trapezoid width calculation at the propagation of a Trackermuon.

#### PR validation:
Validation was performed using the command runTheMatrix.py -l 24450.0 -w upgrade. We verified that the plots after the PR reflect all the changes listed above.

@jshlee @watson-ij

### CODE REVIEW

**Comment by watson-ij** [comment]
please test

**Comment by watson-ij** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in DQM muon TnP-related plots (fake rates, etc) as expected

**Comment by mandrenguyen** [comment]
I see plenty of differences in the Phase 2 muon comparisons, e.g., [c_recoMuons_muons__RECO_obj_numberOfChambers](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-23-2300+14a12f/58582/validateJR/11634.914_TTbar_14TeV+2021_DDDDB/all_RECO_step3/c_recoMuons_muons__RECO_obj_numberOfChambers.png)

I was not expecting these kinds of changes based on the PR description.  I suppose these changes are coming from `TrackingTools/TrackAssociator/src/TrackDetectorAssociator.cc`

Can you explain if this intended?

**Comment by jo100sun** [comment]
@mandrenguyen Yes, it has a bugfix for my previous PR [#40554](https://github.com/cms-sw/cmssw/pull/40554).
It was assuming y origin of localPosition of GEM chamber is at the bottom of a chamber, but in fact it is at the center of a chamber. It was resulting in smaller trapezoid width along x axis, excludes matches too close to edge.

With the fix in this PR, it calculates the correct edge distance which is slightly larger than previous version. As a result, it adds more GEM matches to Trackermuons.

**Comment by jo100sun** [comment]
@emanueleusai
We want to test at p5, and add changes to the next run. What are the backport versions we need to PR?

**Comment by emanueleusai** [comment]
@jo100sun we need 13_0, 13_1, and 13_2

**Comment by mandrenguyen** [comment]
+reconstruction
Changes in reco are due to a buxfix as explained in https://github.com/cms-sw/cmssw/pull/42639#issuecomment-1696900318

**Comment by rappoccio** [comment]
+1

**Comment by mandrenguyen** [comment]
type muon

**Comment by mandrenguyen** [comment]
type bug-fix

**Pull request merged**
