### PR TITLE
Delete legacy OutputModule base class

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Delete the legacy output module base class and all references to it. Already, nothing was inheriting from it anymore. A few classes were still using its fillDescription function, but I moved them to use the corresponding function from the one::OutputModule and with the changes included here that function should be doing exactly the same thing.

#### PR validation:

Existing Core unit tests pass. There is no new functionality. Nothing should change. There will just be less code to maintain.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
Interesting discovery about the `fillDescriptions` calling non-base class versions!

**Comment by makortel** [comment]
Is this the real error in the unit test?
```
Waiting for stacktrace completion failed: timed out waiting for GDB to complete.
```
I.e. strack trace generation took too long in the zombie killer test?

**Comment by makortel** [comment]
@cmsbuil, please test

Let's try again

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by wddgit** [comment]
The failure looks unrelated to the PR. I think I saw similar failure on another PR...

Is this test stuck? Should I be more patient or restart?

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try again

**Comment by makortel** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by peruzzim** [comment]
+xpog

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
