### PR TITLE
Update electron IDs in OfflineDQM

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

This PR is a follow up of #42049 . In the latter, the update of the `egmGsfElectronIDsForDQM` module to include (via VID) only new Run3 electron IDs had created issues to non-EGM DQM, such as TOP, B2G and ParticleNet. In order to address this, the current PR updates the electron IDs used by non-EGM DQM too. Other POGs and PAGs have been informed and have followed up on [CMSHLT-2876](https://its.cern.ch/jira/browse/CMSHLT-2876).

#### PR validation:

runTheMatrix.py -l 12434.0

This did not show the issues that were there in #42049, #42216, #42217, where for example the TopMonitoring was unable to get a handle of the electron ID.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- many DQM differences in HLT PAG plots as expected

**Comment by rappoccio** [comment]
+1

**Pull request merged**
