### PR TITLE
Add histograms vs. track reference point to MultiTrackValidator

### PR DESCRIPTION
**Pull request by makortel**
This PR adds the following histograms to MultiTrackValidator
- fake, duplicate, and pileup rate vs. track reference point xy and z
  - to complement efficiency vs. TrackingParticle vertex xy and z
- duplicate rate vs. DeltaR
  - to make the set of plots vs. DeltaR complete (efficiency, fake rate, and pileup rate are already there)

~~In addition the tracking validation plot script is updated to include these plots.~~ (included now in #12893)

Tested in 800pre4, no changes expected in existing plots.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Since there has been ~no progress on the review, I took the opportunity and moved the plot script update (commit 86cabd3) to #12893 to avoid conflicts. The remaining two commits in this branch are untouched.

**Comment by makortel** [comment]
Could DQM (@deguio, @vanbesien) please review and sign? Thanks.

Do we need another round of tests because I removed the last, tested commit? (the bot seems to think the tests have been started but I doubt that)

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
