### PR TITLE
Run3-hcx216 allow to use HcalSimulationParameters

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

First step to utilize HcalSimulationParameters in the simulation software of HCAL. Some of the changes are withheld in view of conflicts with some unmerged PR's

#### PR validation:

Tested with the standard workflows in the matrix

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , it seems, there are too many duplication propagated via this PR. The most obvious:

from Geometry.HcalCommonData.hcalParameters_cfi import *
from Geometry.HcalCommonData.hcalSimulationParameters_cfi import *
from Geometry.HcalCommonData.hcalDDDSimConstants_cfi import *

Why we need 3 separate python files? I would instead make one and include these three inside or include two into   hcalParameters_cfi.py, this type of modification should located in one place and we should not each time modify many python files scattered over CMSSW.

Concerning code changes: it is a great improvement.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@This unit test failure is expected. Can be fixed only after PR #27665 is merged

**Comment by jfernan2** [comment]
@bsunanda this PR is modifying many (~83k) histograms across many subsystems.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-08-12-1100+a86493/33068/dqm-histo-comparison-summary.html
Is this expected? I understand HCAL simulation can affect many objects, but for example DT plots are changed. I am not sure if the test comparison is being run properly though...

**Comment by ianna** [comment]
@bsunanda - the unit test indicates that the 2026 scenarios were not regenerated, but edited by hand:

```
===== Test "test2026Geometry" ====
argument 0: test2026Geometry
argument 1: /bin/bash
argument 2: Configuration/Geometry/test
argument 3: runtests.sh
shell is: /bin/bash
Current directory is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100
topdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100
testdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100/src/Configuration/Geometry/test
tmpdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100/tmp/slc7_amd64_gcc700
testbin is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100/test/slc7_amd64_gcc700
Running script: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-12-1100/src/Configuration/Geometry/test/runtests.sh
GeometryExtended2026D46_cff.py differs
GeometryExtended2026D45_cff.py differs
GeometryExtended2026D44_cff.py differs
GeometryExtended2026D35_cff.py differs
GeometryExtended2026D43_cff.py differs
GeometryExtended2026D41_cff.py differs
status = 256

---> test test2026Geometry had ERRORS
 
^^^^ End Test test2026Geometry ^^^^
>> Tests for package Configuration/Geometry ran.
```

**Comment by bsunanda** [comment]
@ianna @kpedro88 I am aware of the difference. I did not change some of the files so that #27665 gets integrated first and then shall change dict2026.py and recreate these scenarios

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda I am surprised by the large number of comparison differences. Is this PR changing simulation histories?

**Comment by kpedro88** [comment]
@bsunanda ping

**Comment by fabiocos** [comment]
@bsunanda this PR is potentially affecting everything, could you please clarify its backward compatibility and the reason for so many differences in comparisons, as noted by @kpedro88 ?

**Comment by bsunanda** [comment]
@kpedro88 @fabiocos I am investigating. I have not done much because of some Geant4 work at the moment. I understand part of the reason - but why this is happening I have to find that out

**Comment by civanch** [comment]
@bsunanda , may split this PR in 2-3 smaller PRs?

**Comment by fabiocos** [comment]
@bsunanda any news about this PR?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please Test

**Comment by jfernan2** [comment]
+1
No changes from DQM point of view

**Comment by bsunanda** [comment]
@sbein @cvuosalo @civanch @ianna @kpedro88 @fabiocos Hope the comparisons are ok now. Could this be moved - have to go to next step after this

**Comment by civanch** [comment]
@sbein @cvuosalo @civanch @ianna , please review this PR. Because this is only design change the regression test provide good evidence , that the PR is correct.

**Comment by kpedro88** [comment]
+upgrade
configuration changes correctly propagated through Phase 2 geometries
no regressions observed

**Comment by bsunanda** [comment]
@sbein @cvuosalo @civanch @ianna Could you review and sign this PR. It is a step toward doing to dd4hep transition

**Comment by ianna** [comment]
+1

Please, remove .get() and use make_unique in the next iteration

**Comment by bsunanda** [comment]
@civanch @sbein @fabiocos Could you approve this PR and integrate this at the earliest - need to proceed with the next steps

**Comment by civanch** [comment]
+1

**Comment by sbein** [comment]
+1

**Comment by fabiocos** [comment]
+1

@bsunanda please take not of the requests of @ianna

**Pull request merged**
