### PR TITLE
Add HLT_FullTrack DQM for low PU

### PR DESCRIPTION
**Pull request by zc11**
This is to add DQM for HLT_FullTrack triggers for pp low PU run to the main HI DQM sequence.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
Since data taking (and corresponding validation) is actually done with 74X, does it exist (or do you foresee) a 74X counterpart of this pull request?

**Comment by cfmcginn** [comment]
I believe it already is in progress:
https://github.com/cms-sw/cmssw/pull/9707/files

**Pull request merged**
