### PR TITLE
Fix pixelTracks imports

### PR DESCRIPTION
**Pull request by makortel**
This PR is a follow-up to #17438 adding a `pixelTracks_cfi` that imports from descriptions-generated `pixelTracksDefault_cfi`, and changing all affected files to import from `pixelTracks_cfi. This should have been done already in #17170, but somehow I missed it.

The `PixelTracksL2Tau_cfi` (*) referenced `TrackingRegionsFromBeamSpotAndL2Tau` (in pre-#17170 way), so I added `TrackingRegionsFromBeamSpotAndL2TauEDProducer` to produce the `TrackingRegion`s to event as required by the new seeding framework. I'm not sure how useful `PixelTracksL2Tau_cfi` is anymore though, as now it has just a clone of `PixelTracksProducer` and a `TrackingRegionsFromBeamSpotAndL2TauEDProducer` module via import (i.e. hit doublet/triplet/quadruplet producers and filter+fitter+cleaner are missing).

(*) I guess this is being used for ConfDB parsing since it was modified in #17438. 

Tested in 9_0_0_pre3, no changes expected.

@rovere @VinInn @Martin-Grunewald

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
+1

**Comment by slava77** [comment]
for https://github.com/cms-sw/cmssw/pull/17470	47a7493
- mainly a technical update
- jenkins tests pass and comparisons with baseline show no differences

**Comment by slava77** [comment]
+1
missed originally in the https://github.com/cms-sw/cmssw/pull/17470#issuecomment-279019397

**Comment by davidlange6** [comment]
+1

**Pull request merged**
