### PR TITLE
`SiStripHitEfficiencyWorker`: adding consecutive missing hits recovery when one of the two hits is in an inactive module

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is apply the correction introduced in PR https://github.com/cms-sw/cmssw/pull/44858 to the `SiStripHitEfficiencyWorker` module which is run as part of the `PromptCalibProdSiStripHitEff` Prompt Calibration Loop workflows.
Features introduced (as per https://github.com/cms-sw/cmssw/pull/44858#issue-2267074701):
   * Improvement of the missing hits recovery within the strips, to take into account two consecutive missing hits when one is located in an inactive modules;
   * Expected output is a slight change in the hit efficiency per layer, as shown in the slides presented during the Strip calibration and local reconstruction meeting [here](https://indico.cern.ch/event/1396784/#b-556867-strip-calibration-loc) ( Recovery of consecutive missing hits )

#### PR validation:

I've run the following script with and without this PR:

```bash
#!/bin/bash -ex

# CMSSW_14_1_X_2024-05-20-2300
# voms-proxy-init -voms cms

cmsDriver.py stepReAlCa \
	     -s ALCA:PromptCalibProdSiStripHitEff \
	     --conditions 130X_dataRun3_Express_v2 \
	     --scenario pp \
	     --data \
	     --era Run3 \
	     --datatier ALCARECO \
	     --eventcontent ALCARECO \
	     --processName=ReAlCa \
	     -n 100000 \
	     --dasquery='file dataset=/StreamExpress/Run2023C-SiStripCalMinBias-Express-v4/ALCARECO run=368724' \
	     --nThreads=4

cmsDriver.py stepHarvest \
	     -s ALCAHARVEST:SiStripHitEff \
	     --conditions 130X_dataRun3_Express_v2 \
	     --scenario pp \
	     --data \
	     --era Run3 \
	     --filein file:PromptCalibProdSiStripHitEff.root \
	     -n -1
```

and compared the ouptut:
   * for good modules only:
   
superimposed_histograms_good

   * for all modules:
superimposed_histograms

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported together with https://github.com/cms-sw/cmssw/pull/44858 to `CMSSW_14_0_X` for data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1001, 1001.2, 1001.3, 1001.4, 1002.3

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- The updates are identical to those already merged (in another class) with https://github.com/cms-sw/cmssw/pull/44858
- No issue are visible in the PR tests

**Comment by rappoccio** [comment]
+1

**Pull request merged**
