### PR TITLE
Run3-hcx306 Bug fix to get back the same hit energy distribution for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to get back the same hit energy distribution for HCAL

#### PR validation:

Tested using the script inside SimG4CMS/Calo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing to be back ported

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
bugfix

**Comment by civanch** [comment]
+bugfix

**Comment by civanch** [comment]
type bugfix

**Comment by abdoulline** [comment]
@bsunanda  thank you for the fix.
 I'm running my usual test, will be ready soon. 
 Some DQM files (out of the total test bunch) start coming out of the Condor. 
 I can see that their size corresponds to the "nominal" (e.g. 12_0_0_pre4) one.

**Comment by abdoulline** [comment]
@civanch  and @bsunanda 
I guess, once successfully tested, it needs to be backported to 12_0_X?

**Comment by abdoulline** [comment]
Pion gun "CaloScan" test of 
(i)  CMSSW_12_1_X_2021-08-02-2300  + this PR 
vs 
(ii) CMSSW_12_0_0_pre5 
shows good agreement for SimHits sums (within stat.errors) in the barrel/endcaps.  
NB: HF change comes (as expected) from old SL -> new SL change (in 12_0_0_pre5).

http://cern.ch/go/m7qD

**Comment by civanch** [comment]
@bsunanda , thanks for this critical fix and @abdoulline , thank for the prompt analysis.

This PR should be backported to 12_0_X. 12_0_0_pre5 is broken and this fix recover HCAL hits.

**Comment by civanch** [comment]
+1

@silviodonato, @dpiparo, @qliphy, @perrotta ,  this fix recover 12_0_0_pre5 HCAL problem.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@bsunanda (or anyone else) please prepare a backport for 12_0_X

**Comment by perrotta** [comment]
merge

**Pull request merged**
