### PR TITLE
Run3-Sim95 Collapse .h and .cc files if possible in SimG4CMS/Calo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Collapse .h and .cc files if possible in SimG4CMS/Calo

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch We address SimWatcher/SimProducer accessing objects from EventSetup in later versions

**Comment by civanch** [comment]
+1

Yes, I have this in mind start to work on Watchers the next week.

**Comment by qliphy** [comment]
+1

**Pull request merged**
