### PR TITLE
Remove wrong "tracked".

### PR DESCRIPTION
**Pull request by geonmo**
Remove "tracked" for tracked valuable.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by geonmo** [comment]
@civanch Could you re-test for this PR? The errors came from "DAS" service.

**Comment by davidlange6** [comment]
these parameters are now tracked. what error suggests to you that they should be untracked again?
@geonmo  [maybe this you are using cond-db1?

**Comment by geonmo** [comment]
@davidlange6 As you know, these parameters are "tracked".However, "cms.tracked" is an wrong syntax. "cms.string" means "tracked" parameters.
```bash
Traceback (most recent call last):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-08-09-1100/bin/slc6_amd64_gcc491/cmsDriver.py", line 43, in <module>
    run()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-08-09-1100/bin/slc6_amd64_gcc491/cmsDriver.py", line 15, in run
    configBuilder.prepare()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-08-12-1100/python/Configuration/Applications/ConfigBuilder.py", line 2224, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-08-12-1100/python/Configuration/Applications/ConfigBuilder.py", line 895, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/afs/cern.ch/work/g/geonmo/CMSSW_7_5_X_2015-08-12-1100/python/SLHCUpgradeSimulations/Configuration/fixMissingUpgradeGTPayloads.py", line 10, in fixRPCConditions
    connect = cms.tracked.string("frontier://FrontierProd/CMS_COND_31X_RPC")
AttributeError: 'module' object has no attribute 'tracked'
```

**Comment by davidlange6** [comment]
ah... Thanks!

**Pull request merged**
