### PR TITLE
Clean up DD Axes

### PR DESCRIPTION
**Pull request by ianna**
- Use strongly-typed enum
- Use range-based for loop
- Remove index

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by ianna** [comment]
@cmsbuild - the error is in DAS - unrelated to this PR.

**Comment by ianna** [comment]
@cmsbuild - ok, the unit test fails due to another reason. Though, I can fix it in this PR.

**Comment by ianna** [comment]
@cmsbuild - the error is fixed in #8849

**Pull request merged**
