### PR TITLE
Run3-gex176C Backport the PR's 44006 and 44052 for the 2024 scenario definition with additional chambers for GE21 and iRPC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the PRs 44006 and 44052 for the 2024 scenario definition with additional chambers for GE21 and iRPC

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backports of #44006 and #44052

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela Could you please merge this PR?

**Comment by rappoccio** [comment]
@bsunanda maybe we don't need a ping on a PR you signed 30 seconds earlier and well before the tests are even completed? Just a thought.

**Comment by rappoccio** [comment]
hold

**Comment by rappoccio** [comment]
I'll put this on hold until tests complete, just to be sure we don't accidentally merge it prematurely.

**Comment by bsunanda** [comment]
@rappoccio @antoniovilela Please uphold this PR and merge this to 14_0_X

**Comment by rappoccio** [comment]
+1

**Pull request merged**
