### PR TITLE
Do not include EventSetup record definitions in device code [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport of #44682 by @iarspider:

> As suggested in [#44645 (comment)](https://github.com/cms-sw/cmssw/issues/44645#issuecomment-2045554062)

Includes the following clean up from #44870.

#### PR validation:

Unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #44682 and #44870 to CMSSW 14.0.x to keep the alpaka code consistent.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #44682

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
