### PR TITLE
[12_5_X] L1T DQM: Adding the uGT timing sequence back and updating the relevant algo list - backport

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
L1T DQM update:

Putting the uGT timing sequence back into the workflow
Updating relevant triggers to match the Run 3 menu (L1Menu_Collisions2022_v1_0_1)

Backport of #38840 to be included in the online L1T DQM workflow.

12_4_X backport: #39734

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38840

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
hmm something's wrong with the IB?

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
failed comparisons not caused by this PR

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

* The differences here look spurious .

**Pull request merged**
