### PR TITLE
Backport of #13959: SpeedUp ParticleFlow for HLT; and #14070: remove memory fence

### PR DESCRIPTION
**Pull request by makortel**
This PR backports #13959 and #14070 from CMSSW_8_1_X to CMSSW_8_0_X. Original descriptions by @VinInn 
#13959

> Technical mods to ParticleFlow (and some core classes) to speedup creation for PFRecHIt and PFClusters.
> Most of it is trivial.
> I did not observe any regression on TTBAR PU35 reco.
> Includes contribution by @lgray
> 
> added major speedup in ES geometry and EcalRecHit creation
> 
> p.s. shrink_to_fit is still calling RefCore copy constructor instead of moving as it should....
#14070

> avoid stalls due to memory fence.

The first commit (7cf0c3b) is actually from #13831. It is included here because #13959 depends on it, and the dependence is only a single commit whose intention is not to change any behaviour. The entire #13831 is not backported at this time because it causes tiny regressions due to numerics.
#14070 is included because it depends on #13959, and causes no changes in RECO quantities.

Tested in CMSSW_8_0_14, no changes expected in RECO quantities in here either.

@fwyzard @gennai @slava77 @VinInn @lgray

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
tracked at #15151

**Comment by makortel** [comment]
Added #14070 on top of #13959 (commit 0b11d86), as discussed in #15151.

**Comment by ianna** [comment]
@kpedro88 - I don't see how this PR can trigger configuration error in HGCal tests:
```
----- Begin Fatal Exception 20-Jul-2016 21:51:12 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_0_X_2016-07-19-2300/src/SimCalorimetry/HGCalSimProducers/test/testHGCalDigi_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.AttributeError'>
'ESSource' object has no attribute 'HcalReLabel'
----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
@ianna The HGCal tests are failing in the base IB https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc530/www/tue/8.0-tue-23/CMSSW_8_0_X_2016-07-19-2300 (actually all the 4 failing unit tests fail in the base IB).

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15240	0b11d86
- backport of a fraction of #13831  80d27d6 (technical), and entirety of #13959 and #14070 as described. Expected gains for HLT are significant, while for RECO they are rather small (pre-signoff tests of #13959 showed ~0.3% reduction in RECO CPU total).
- jenkins tests pass and comparisons with baseline show no difference
- local tests with HLTPhysics_Run276935_LS80-220.root and hlt_v3p0V3_full.py  (prepared by @clint-richardson ) show expected improvements on a 10K events test: the per-event total goes down by almost 9%, which primarily comes out from an average reduction of 30% in execution of hltParticleFlowCluster\* and hltParticleFlowRecHit\* modules.

Here is the per-event average of the modules with the most significant differences per event (the first call of each module is not counted)
```
self-change   perJob-change   baseline              thisPR
-0.74328         -1.35%             8.36 ms/ev ->             3.83 ms/ev    hltParticleFlowClusterECALUnseeded
-0.69367         -0.57%             3.73 ms/ev ->             1.81 ms/ev    hltParticleFlowRecHitPSL1Seeded
-0.66013         -1.76%            11.93 ms/ev ->             6.01 ms/ev    hltParticleFlowRecHitPSUnseeded
-0.52413         -1.04%             8.46 ms/ev ->             4.95 ms/ev    hltParticleFlowClusterPSUnseeded
-0.42295         -0.31%             3.01 ms/ev ->             1.96 ms/ev    hltParticleFlowRecHitECALUnseeded
-0.39992         -0.15%             1.50 ms/ev ->             1.00 ms/ev    hltParticleFlowClusterECALL1Seeded
-0.37105         -0.18%             1.93 ms/ev ->             1.32 ms/ev    hltParticleFlowRecHitECALL1Seeded
-0.34098         -0.24%             2.77 ms/ev ->             1.96 ms/ev    hltEcalPreshowerRecHit
-0.29562         -0.12%             1.56 ms/ev ->             1.16 ms/ev    hltParticleFlowRecHitHBHE
-0.28056         -0.21%             2.84 ms/ev ->             2.14 ms/ev    hltParticleFlowRecHitHF
-0.25535         -0.12%             1.84 ms/ev ->             1.43 ms/ev    hltRechitInRegionsES
-0.24576         -0.80%            12.27 ms/ev ->             9.58 ms/ev    hltParticleFlowClusterHF
-0.22727         -0.19%             3.05 ms/ev ->             2.43 ms/ev    hltParticleFlowRecHitHCAL
-0.21915         -0.11%             1.94 ms/ev ->             1.56 ms/ev    hltParticleFlowClusterPSL1Seeded
-0.19149         -0.11%             2.21 ms/ev ->             1.82 ms/ev    hltParticleFlowClusterECALUncorrectedUnseeded
```

**Comment by fwyzard** [comment]
From a test over 1k events, I see
  - no changes in the trigger results
  - a 6% reduction in cpu usage / 6% increase in throughput

```
Found 1000 matching events, out of which 0 have different HLT results
```

```
Performance for reference
average from 42 tests:
        throughput:   60.9 +/-  0.6 ev/s
        event time:  348.2 +/-  2.8 ms

Performance for backport_13959
average from 42 tests:
        throughput:   64.4 +/-  0.6 ev/s
        event time:  327.3 +/-  2.6 ms
```

**Comment by slava77** [comment]
@fwyzard 
which input and table did you check for your test?

**Comment by fwyzard** [comment]
I'm running over pileup ~40 data from run 277069
```
/store/data/Run2016E/HLTPhysics0/RAW/v2/000/277/069/00000/1497C220-EB4D-E611-B289-02163E01351C.root
/store/data/Run2016E/HLTPhysics0/RAW/v2/000/277/069/00000/2AC115D3-DC4D-E611-8D85-02163E0145C5.root
/store/data/Run2016E/HLTPhysics0/RAW/v2/000/277/069/00000/38187B86-DC4D-E611-BB67-02163E0128B6.root
/store/data/Run2016E/HLTPhysics1/RAW/v2/000/277/069/00000/449CACB1-EA4D-E611-814B-02163E011C75.root 
/store/data/Run2016E/HLTPhysics1/RAW/v2/000/277/069/00000/5A4BADBE-EA4D-E611-8546-FA163E453E65.root
/store/data/Run2016E/HLTPhysics1/RAW/v2/000/277/069/00000/D21C5EAD-DE4D-E611-899E-FA163E7C13F5.root
```
with the release and HLT menu used online to collect them, CMSSW_8_0_14 and with `/cdaq/physics/Run2016/25ns15e33/v3.0.1/HLT/V1`

**Comment by slava77** [comment]
@fwyzard 
thanks for the details.
It looks like the fraction of paths with PF has changed to a smaller value since the version we were using for tests provided by @clint-richardson

**Comment by slava77** [comment]
@Dr15Jones @civanch your signature is needed here

@davidlange6 It would help to merge this soon to avoid overlapping backports.

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
