### PR TITLE
Nano: restore Run2/3 consistency between electron/photon IDs; remove scale+smearing correction for Run3

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

1. The electron cutBased and photon cutBased and MVA IDs (and new EA corrections for isolation) added in https://github.com/cms-sw/cmssw/pull/39963, https://github.com/cms-sw/cmssw/pull/39927, https://github.com/cms-sw/cmssw/pull/40045 did not follow the same convention for Run2 and Run3. This restores consistency by:
   - Run2: only provide Fall17V2-based IDs and isos with the "default" names (`cutBased`/`mvaID`/...)
   - Run3: provide the Winter22V1-based IDs with the "default" names (`cutBased`/`mvaID`/...), but keep the Fall17V2 variables with a `_Fall17V2` suffix as backup, as desired by @cms-sw/egamma-pog-l2  . Those should be dropped at some point later.
3. The electron+photon scale+smearing corrections are not available yet for Run3; the Run2 ones should not be applied for Run3 eras but the energy should be left uncorrected; Run3 corrections will be made available later with correctionlib.
   - This required excluding the `run2_egamma_2018` modifier from the `Run3` era, since it was carried over there from the `Run2_2018` era. From a quick search it seems this should not have unexpected effects elsewhere. (note: I must say I also don't understand the reason for having a `run3_egamma` modifier, since I would assume Run3 to be the "default" configuration in 130X or 126X)

#### PR validation:

`runTheMatrix.py --what nano --site "" -l 2500.312,2500.501`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will require backport to 12_6_X for nanoV11 production.

FYI @cms-sw/egamma-pog-l2

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
type egamma

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

Error looking spurious, retrying...

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

**Comment by swagata87** [comment]
Hi Sebastian, 
Answering some of the questions asked above.. 
About `H/E`, the situation is that the `Fall17V2` Cutbased phoID uses `hadTowOverEm()` and the Run3 ID uses `hadronicOverEm()`. We made this change in Run3, because `hadronicOverEm()` has more discrimination power than `hadTowOverEm()`. Assuming people will use Run3 ID from now on, it's safe to keep only `hadronicOverEm()`. But, if for some reason, people use Fall17V2 Cutbased phoID for Run3 and want to access the corresponding H/E, then we have a problem. 

S+S question seems to be resolved already by you. 

About Phase2 nano, I agree with you, we can probably ignore it for now and come back to it later.

**Comment by swertz** [comment]
+1

Expected changes in Nano.

Thanks for the clarification @swagata87 ! (I found it strange because `hadronicOverEm()` is what was there originally, then it was switched to `hadTowOverEm()` for Run2, and now we're back with hadronicOverEm()` for Run3.)

I will prepare the backport for 12_6 now. You're welcome to prepare the eleMVAID PR on top of these commits.

**Comment by perrotta** [comment]
+1

**Pull request merged**
