### PR TITLE
Fix --timing option in confdb.py (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix --timing option in confdb.py (93X)
Based on CMSSW_9_3_0_pre1

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
won't this break the case of a configuration without the HLTriggerFirstPath ?

.A

**Comment by Martin-Grunewald** [comment]
Hmm well, all configs should have it or take/import it from the master.
(I never liked that we recreate paths inside confdb.py which are identically in the menu).

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
