### PR TITLE
SiStripDQM : number of cluster trend in wheel/layer, number of cluster per ring and per layer

### PR DESCRIPTION
**Pull request by boudoul**
Implementation of several plots in SiStripMonitorCluster package: number of cluster trend in wheel/layer, number of cluster per ring and per layer. Change in apv charge median plot switch in SiStripMonitorDigi package

Backport of the same code from the already merged PR in 90X : #17304 

Would be great to have for the legacy Re-reco

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
backport https://github.com/cms-sw/cmssw/pull/17304

**Comment by boudoul** [comment]
@dmitrijus , please add this PR in the dedicated list requested by the ORP for the rereco

**Comment by davidlange6** [comment]
+1

**Pull request merged**
