### PR TITLE
Replace LinkDef files with XML selextion files.in CalibCalorimetry/EcalLaserAnalyzer

### PR DESCRIPTION
**Pull request by wmtan**
It has been decided to replace LinkDef files with XML selection files.
This PR does this for the LinkDef files that were in CalibCalorimetry/EcalLaserAnalyzer.
A reorganization of existing files was needed because XML selection files are not allowed in plugins.
LinkDef files should not be in plugins, either, but that was never enforced.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@cmsbuild
These three add-on tests fail in the base IB, so are not caused by this PR. Please mark the tests as approved.

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@diguida, @franzoni, @cerminar
Please sign or provide a reason for not signing

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
@wmtan I see build failures in CalibCalorimetry/EcalLaserAnalyzer package in CMSSW_7_6_DEVEL_X_2015-10-12-2300 (ROOT 6.04).

```
Error in <PulseFitWithFunction>: PulseFitWithFunction inherits from TObject but does not have its own ClassDef
Error in <PulseFitWithShape>: PulseFitWithShape inherits from TObject but does not have its own ClassDef
Error in <TFParams>: TFParams inherits from TObject but does not have its own ClassDef
Error in <TMarkov>: TMarkov inherits from TObject but does not have its own ClassDef
Error in <TMatacq>: TMatacq inherits from TObject but does not have its own ClassDef
Error in <TPNFit>: TPNFit inherits from TObject but does not have its own ClassDef
Error in <TPNCor>: TPNCor inherits from TObject but does not have its own ClassDef
Error in <TSFit>: TSFit inherits from TObject but does not have its own ClassDef
Error in <TShapeAnalysis>: TShapeAnalysis inherits from TObject but does not have its own ClassDef
Error in <TMom>: TMom inherits from TObject but does not have its own ClassDef
Error in <TAPDPulse>: TAPDPulse inherits from TObject but does not have its own ClassDef
Error in <TPNPulse>: TPNPulse inherits from TObject but does not have its own ClassDef
Error in <TMem>: TMem inherits from TObject but does not have its own ClassDef
```

**Comment by wmtan** [comment]
@davidlt Those messages are non-fatal, and where already there with the LinkDef file, so they were not introduced by this PR.

**Comment by davidlt** [comment]
It's fixed in ROOT 6.04 and they are fatal. A number of these classes contain commented out ClassDef lines, which are required. I can make a PR tomorrow.

**Comment by davidlt** [comment]
RFC: #11787

**Pull request merged**
