### PR TITLE
[HeaderCheck][GenIfc] GeneratorInterface/EvtGenInterface

### PR DESCRIPTION
**Pull request by mrodozov**
- Add dep on evtgen external
- Change header path

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@qliphy, @perrozzi, @efeyazgan  looks like the header file (  GeneratorInterface/EvtGenInterface/interface/EvtGenLHCInterface.h) is not used any where in cmssw. I would suggest that instead of fixing and maintaining unused code we should delete it.

**Comment by alberto-sanchez** [comment]
Indeed it is a left over of the previous implementation of EvtGen interface.
I can work on this later today.

**Pull request merged**
