### PR TITLE
Critical revision of the CASTOR monitor package and migration to the new DQM interface

### PR DESCRIPTION
**Pull request by popovvp**
critical revision of the CASTOR monitor packages and migration to the new DQM interface

### CODE REVIEW

**Comment by davidlange6** [comment]
Please give this PR a meaningful title for the release notes.

**Comment by popovvp** [comment]
Dear Experts

  Now only 10 files are in the new CASTOR dqm software package:
    CastorBaseMonitor.cc,h
    CastorDigiMonitor.cc,h
    CastorMonitorModule.cc,h
    CastorLEDMonitor.cc,h
    CastorRecHitMonitor.cc,h
-------------------------------------------
  All others (CastorChannelQualityMonitor.cc,h
             CastorDataIntegrityMonitor.cc,h
             CastorHIMonitor.cc,h
 	    CastorPSMonitor.cc,h
             CastorTowerJetMonitor.cc,h
 	    CastorBunch.h)
  are obsolete and not in use any more. Could you please remove them.

  Thanks,
    Vladimir

**Comment by davidlange6** [comment]
you can remove obsolete files in your pull request. Just do git rm in your local area on the files you want to remove, then git commit and push your changes to your branch.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
errors not related

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
superseded by #7365 
thanks @vanbesien @popovvp

**Pull request closed without merging**
