### PR TITLE
(Backport) PFlow in the HF region for phase2

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

This PR introduces the first attempt of track-HF cluster matching in PFAlgo for phase 2. It shouldn't impact Run2 and Run3 reconstruction, but improves phase2 reconstruction. Before this PR, tracks and HF clusters in |eta|=3-4 region have been heavily double-counting charged particles in this region, which will be largely remedied in this PR. This PR introduces kdtree-based linking between tracks and HF clusters, and links are utilized in mostly createCandidatesHF of PFAlgo.

Also, the propagator is fixed to make the track propagation to HF to work for particles with pt<3 GeV also (which was broken in the past, as it didn't matter).

Also, the HF face is updated to be in agreement with the actual geometry.

#### PR validation:

See the original PR #28442 

#### if this PR is a backport please specify the original PR:

This is a backport of #28442

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #28442

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28650	b07fda1 
- this is identical to #28442 (the same topic branch is used); changes affect only phase-2 PF reco
- jenkins tests pass and comparisons with the baseline show differences only in the phase-2 workflows
- see signoff comments in the master branch version https://github.com/cms-sw/cmssw/pull/28442#issuecomment-566821931

**Comment by fabiocos** [comment]
@sbein @Martin-Grunewald as discussed I plan to integrate this PR to allow tests in 11_0_0 in view of its use in te HLT TDR production. @Martin-Grunewald you mentioned that this would require a further update of the HLT menu, could you please clarify?

**Comment by Martin-Grunewald** [comment]
This PR contains a HLT menu customisation which works offline. Such customisations are not used online, so there the menu itself has to contain everything and to work out of the box. Thus a menu update is needed once the PR is integrated, at least for MWGR usage.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald ok, I see what you mean, thanks for the clarification. This means that there is no show-stopper in making 11_0_0 for HLT TDR studies, but then we will need a further update on your side in view of MWGR in February

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
