### PR TITLE
Reorganise alpaka kernel loop functions [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Reorganise the implementation of the Alpaka-based kernel loop functions.

Rename the implementation classes to `CamelCase` and move them to the `detail` namespace:
  - rename `uniform_elements_along` to `detail::UniformElementsAlong`
  - rename `uniform_groups_along` to `detail::UniformGroupsAlong`
  - rename `uniform_group_elements_along` to `detail::UniformGroupElementsAlong`
  - rename `uniform_elements_nd` to `detail::UniformElementsND`
  - rename `independent_groups_along` to `detail::IndependentGroupsAlong`
  - rename `independent_group_elements_along` to `detail::IndependentGroupElementsAlong`

Replace legacy loop names with the more explicit ones, in the `cms::alpakatools` namespace:
  - replace `elements_with_stride(...)` with `uniform_elements(...)`
  - replace `blocks_with_stride(...)` with `uniform_groups(...)`
  - replace `elements_in_block(...)` with `uniform_group_elements(...)`

Rename legacy function with the new names.

#### PR validation:

None.

#### Backport status:

Backport of #44712 to CMSSW 14.0.x.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #44712

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@cms-sw/orp-l2 could you merge this for the next CMSSW 14.0.x release ?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
