### PR TITLE
change python2 to python3 in a few unit tests

### PR DESCRIPTION
**Pull request by davidlange6**
As noticed in cms-sw/cmsdist#6990

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
ping

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy this is technical update for py3. please merge this for next IB

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
