### PR TITLE
Added new categories (DSTJets,DSTMuons) for scouting triggers.

### PR DESCRIPTION
**Pull request by ryonamin**
alternative PR to #11695

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
#11616  needs to be merged first to avoid conflicts
waiting before approving

**Comment by davidlange6** [comment]
is there some need to worry about scouting in heavy ions?

**Comment by deguio** [comment]
nope. we can probably just close this one.

**Pull request closed without merging**
