### PR TITLE
Adding HTXS stage 1.2 classification (102x backport)

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

Adds HTXS stage 1.2 classification (stage 1.1, 1 and 0 stay available)

#### PR validation:

Verified to run correctly using runRivetHTXS_cfg.py 

#### if this PR is a backport please specify the original PR:

Backport of #28444 for use with nanoAOD

### CODE REVIEW

**Comment by qliphy** [comment]
Adding @intrepid42 @xjanssen

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
