### PR TITLE
RecoEgamma/ElectronIdentification cleanup

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

This is one of the occasional PRs that removes old electron IDs as the goal is still to have only the VIDs and other currently used IDs left in the release. This time, I remove the old Likelihood based IDs and some old cut based IDs. One working point is still used in PF, so I move it there.

@Sam-Harper

#### PR validation:

CMSSW compiles and local matrix tests pass.

#### if this PR is a backport please specify the original PR:

No backport intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
thank you @guitargeek ! This is much appreciated!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27370	cf7390b
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
