### PR TITLE
bsunanda:Run2-hcx76 Remove obsolete parameter definitions for relabelling at DIGI step

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda, in the workflow 8.0 one plot is not identical for Hcal. Can you, please, have a look.

**Comment by bsunanda** [comment]
I took a look and cannot understand what could cause any difference in the RawTask for HCal. All changes made here are removing some of the parameters which are never read in by the code and are simply legacy parameters. The difference is ertainly not due to changes made in the PR.
________________________________

**Comment by Dr15Jones** [comment]
Is it possible that you have an uninitialized variable? If so, removing member data could move the location of that memory to somewhere with a different value.

**Comment by bsunanda** [comment]
Hi Chris - all the changes are in the cfi/cff files. The only change in code is theRelabeller=new HcalHitRelabeller(ps0.getUntrackedParameter<edm::ParameterSet>("RelabelRules"));
replaced with
theRelabeller=new HcalHitRelabeller(ps0);
and HcalHitRelabller does not use the parameterset. So should I investigate the code where this change is made for uninitialized variable. But this is digitizer code and the complaint comes from RAW part. I am at a loss.
________________________________

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
in the new test all workflows are OK. I would think that Chris probably right but this is not related to this PR.

**Pull request merged**
