### PR TITLE
Migration to CMSSW_10_5_0_pre2 code base in ConfDB

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration to CMSSW_10_5_0_pre2 code base in ConfDB
Based on CMSSW_10_5_0_pre2

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #25999

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald could you please clarify the purpose/target of this backport?

**Comment by Martin-Grunewald** [comment]
It moves some HLT-menu customisation code directly into the HLT menu itself.
This is required to make ConfDb menus run out of the box.
It will be mandatory once 10_5 is used for some MWGR.
The change is purely technical and does not affect the HLT physics decisions.

**Comment by fabiocos** [comment]
@Martin-Grunewald @boudoul given the move of MWGR activities to 10_6_X, I believe this PR is obsolete and may be just closed, please comment otherwise

**Comment by fabiocos** [comment]
In case of need (I do not what anyway) we may reopen it.

**Pull request closed without merging**
