### PR TITLE
[13_2_X] Adding ZDC Unpacker to L1RawtoDigi

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #42733

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by antoniovilela** [comment]
@matt2275 @aloeliger @mandrenguyen 
Could we quickly re-run the validation here?

**Comment by matt2275** [comment]
I tested this branch and had no issues with producing an output with the zdc unpacker identical to the previous tests. 

Procedure:

        cmsrel CMSSW_13_2_X_2023-09-15-1100
        cd  CMSSW_13_2_X_2023-09-15-1100/src
        cmsenv
        
        Then I added the EventFilter/L1TRawtoDigi directory from here (https://github.com/mandrenguyen/cmssw/tree/ZDCUnpacker_132X/EventFilter/L1TRawToDigi) 
        
        scram b -j 8

There were no compiler issues.

To test the zdc unpacker. I ran this program ( https://github.com/cms-sw/cmssw/blob/master/EventFilter/L1TRawToDigi/utils/unpackData-CaloStage2.py#L156) with this command ( nb, to fix an error you need to change token to label in the line I  marked)  :

      cmsRun unpackData-CaloStage2.py inputFiles=file:/eos/cms/store/t0streamer/Data/PhysicsCommissioning/000/373/425/run373425_ls0050_streamPhysicsCommissioning_StorageManager.dat streamer=True skipEvents=0 maxEvents=1000 valEvents=False debug=False dumpRaw=True dumpDigis=True histos=True edm=True
      
The program ran correctly and made an edm file identical to one I made previously to test the original PR

**Comment by aloeliger** [comment]
@antoniovilela will that suffice, or do you need @matt2275 to produce identical files to what was shown before?

**Comment by antoniovilela** [comment]
> @antoniovilela will that suffice, or do you need @matt2275 to produce identical files to what was shown before?

I understand one could reproduce the tests from
https://github.com/cms-sw/cmssw/pull/42733#issuecomment-1720841194

If you are happy,, please sign this PR.

**Comment by aloeliger** [comment]
+l1
- Likely necessary in production as quickly as possible

**Comment by aloeliger** [comment]
urgent

- I guess I should mark it with this

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
