### PR TITLE
Add a function to iterate over all modules of the given type(s)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a function to iterate over all modules of the given type(s)

#### PR validation:

Tested in a private HLT customisation, not used by any production workflow (yet).

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
@Martin-Grunewald @fwyzard can we merge this PR?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
