### PR TITLE
make hcal digitization changes the default

### PR DESCRIPTION
**Pull request by davidlange6**
time slew parameters and hf1 sampling factors now the default - consistent with GT in 76x already

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@slava77 - the customizeHLTforMC function is not touched in this PR - I think it can be removed though.

**Comment by slava77** [comment]
On 10/8/15 1:00 AM, David Lange wrote:
> @slava77 <https://github.com/slava77> - the customizeHLTforMC function
> is not touched in this PR - I think it can be removed though.

OK.
But this also means that this PR modifies only DIGI step in a noticeable
way.

**Comment by davidlange6** [comment]
> On Oct 8, 2015, at 8:09 AM, Slava Krutelyov <notifications@github.com> wrote:
> 
> On 10/8/15 1:00 AM, David Lange wrote:
> > @slava77 <https://github.com/slava77> - the customizeHLTforMC function
> > is not touched in this PR - I think it can be removed though.
> 
> OK.
> But this also means that this PR modifies only DIGI step in a noticeable
> way.

ah - sorry - indeed, I need to update that. Thanks!

**Pull request merged**
