### PR TITLE
Bunch spacing producer

### PR DESCRIPTION
**Pull request by davidlange6**
centralize bunch spacing via run number calculation

### CODE REVIEW

**Comment by lgray** [comment]
@davidlange6 Please make sure the bunch spacing is saved in MiniAOD (otherwise can't apply regressions on the fly).

**Comment by slava77** [comment]
@davidlange6 is it possible to have a clean PR with just the feature declared? (parts of 7412patchX not in 74X show up in the diffs)
... maybe it wasn't submitted to the right branch though, unclear to me.

**Comment by davidlange6** [comment]
i can try to manage  (but its strange as I thought I had everything in 74x that is in 7412patchX)

**Comment by slava77** [comment]
github on the web sometimes shows fake diffs because they have a different commit id, even if they would not change anything during merge

**Comment by slava77** [comment]
@davidlange6 I understood from last Thursday that there will be an update to this.
Please clarify.

**Comment by davidlange6** [comment]
@slava77 - I will open a new PR with small additional changes

**Pull request closed without merging**
