### PR TITLE
L1T offine DQM changes for pp reference run - part2

### PR DESCRIPTION
**Pull request by thomreis**
To make the L1T offline DQM work for the pp reference run the trigger paths used must be adapted for the pp reference run HLT menu.

Part 2: L1T EG and L1T Jets

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
Hi @dmitrijus can you sign this one and its backports please? We would like to use it in the pp reference run.

**Comment by jfernan2** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
