### PR TITLE
Extending E/gamma HLT Debug to phaseII and adding rec-hit counts: 11_1_X 

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR adds the phase-II HLT E/gamma debug producer by introducing a new class EgammaHLTPhaseIIExtraProducer which handles the Phase-II specific things such as HGCAL and L1 tracks so it doesnt have to be exposed to the standard EgammaHLTExtraProducer.

It also introduces a new track trigger dataformat, L1TrackTruthPair which makes it easier to deal with the L1 tracks and truth matching, particularly in FWLite

#### PR validation:

Used extensively for E/g HLT phase-II development. Test shows this produces the expected output

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/32911

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
ping @cms-sw/l1-l2

**Comment by cecilecaillol** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
