### PR TITLE
backporting skims to 74x

### PR DESCRIPTION
**Pull request by alkaloge**

### CODE REVIEW

**Comment by alkaloge** [comment]
Please hold this PR as we will are waiting from feedback from muon POG to the Zmu skim

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
Hello @alkaloge ,
are TopMuEG MuTau two PD's ? 
The matrix has keys which need to match PD's.
This is the most recent list of PD's I have for Hermine    http://hermine.web.cern.ch/hermine/CMS/PATH_DS_50ns_v2.list

Once we've clarified this, I suggest we go ahead and test+merge. "feedback from muon POG for the Zmu skim" , unless due in ~1d, can go on to.

Cheers. g.

**Comment by alkaloge** [comment]
PD are given here https://docs.google.com/spreadsheets/d/1OicL4b3jFUXalsk92GM9qLbNNAVklAGb7bf1T5BwZrY/edit#gid=0 - Skim naming does not in principle follow PD that need to run -

**Comment by battibass** [comment]
@franzoni , @alkaloge, we don't plan any change of the ZMu skim in the timescale of ~ a day (unless the skim does not skim enough, which should not be the case).
As @alkaloge has request us some cross checks of his results, @HuguesBrun and @BenjaminRS are having a look at the skim efficiency. 
They will report here as they are done.

**Comment by HuguesBrun** [comment]
Hello 
After few checks we think that the ZMu is working as expected
Few details: 
- we checked the ZMu skim on the data relval (SingleMuRelVal_mu2012A) and we find ~3.5% of the events passing which is a similar to number previously reported (see [here](https://indico.cern.ch/event/345449/session/8/contribution/24/material/slides/0.pdf))
- it is also 90% efficient on the ZMuMu Relval.

Benjamin and Hugues

**Comment by franzoni** [comment]
ciao @alkaloge, I've placed a comment to https://github.com/cms-sw/cmssw/pull/9567 which applies also here.
Thanks! g.

**Comment by franzoni** [comment]
+1

labelling of matrix is to be updated and will need follow up - the core of the chancges are wanted and valid.

**Comment by davidlange6** [comment]
+1

**Comment by franzoni** [comment]
@alkaloge , could you please look into re-basing this PR ?

**Comment by franzoni** [comment]
here's the list of datasets we currently have : 
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1019/1/1.html

**Comment by franzoni** [comment]
hi Alexis @alkaloge , can you please close this PR ?
Cheers, G.

**Pull request closed without merging**
