### PR TITLE
Updates on GEM onlineDQM due to the updates of DAQ dataformat, backport to CMSSW_11_3_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
Since lots of stuffs in DAQ dataformat have been changed in https://github.com/cms-sw/cmssw/pull/34504 (and #34585, the backport), the GEM onlineDQM has to be changed to adjust it. This PR is for it.

Also many of plots are rearranged, and new plots are added, which are plots of the average cluster sizes, etc..

This is the backport of #34614 to CMSSW_11_3_X.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
To CMSSW_11_3_X to be deployed on current cosmic runs (i.e., CRUZET)

@jshlee @watson-ij @hyunyong

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #34614

**Comment by perrotta** [comment]
please test with #34585

**Comment by perrotta** [comment]
@quark2 @cms-sw/dqm-l2 please specify whether this is needed for the release to be run in the last days of cruzet

**Comment by quark2** [comment]
Hi @perrotta, 

as #34585, it is also needed for the release.

**Comment by perrotta** [comment]
urgent

**Comment by francescobrivio** [comment]
@jfernan2 can you have a look at this? it would be nice to include it in the new build for CRUZET! Thanks!

**Comment by ahmad3213** [comment]
+1

**Comment by francescobrivio** [comment]
For completeness: 
this PR was also tested live in the DQM playback system in P5 by the DQM team and no cashes were observed.

**Comment by perrotta** [comment]
@quark2 out of curiosity, why did you split the plugins in DQM/GEM into a header and an implementation file? The suggestion is to move in the opposite direction (only one file in the \plugin area), and you were already there...

**Comment by perrotta** [comment]
+1
- Expected to be included in the release for the last days of Cruzet

**Comment by quark2** [comment]
Hi @perrotta, I expected the module (or, especially, its inherited version) would be used in future, so I split them. But I'm not pretty sure if they will be used...

**Comment by perrotta** [comment]
> Hi @perrotta, I expected the module (or, especially, its inherited version) would be used in future, so I split them. But I'm not pretty sure if they will be used...

plugin modules should only act as plugins, remain local to the \plugin area, and they shouldn't be included from anywhere else.
My fault, I didn't notice it when I approved the PR in the master.

Not a big issue, anyhow: those plugin headers are never included from somewhere else. Anyhow, with no urgency, I'd suggest to revert the split in the master version of this PR, so that possible future developments will be based on it.

**Comment by quark2** [comment]
@perrotta Okay, I'll merge them in the next updates. Thanks for your advice!

**Pull request merged**
