### PR TITLE
backport of bugfix in vertex selection for the L2TauTagNNProducer

### PR DESCRIPTION
**Pull request by valeriadamante**
#### PR description:
Doing tests on GPU, some issues in L2NNTag produced outputs have been reported: running twice the L2NNTag producer, it gave different results on the same events/taus. The problem has been addressed to the filling of the CNN inputs : PatatrackPtSumWithVertex and PatatrackSizeWithVertex.
The reason is the following: to fill the aforementioned variables while looping on tracks, a match between the vertex associated to the track (*) is required by associating the observable idv (which is the vertex index related to the patatrack) to be the same of the sortInd (**) which is the vertex index sorted by the vertex observable ptv2 .
If you want to give a look to the vertex related observables, they are described [here](https://github.com/cms-sw/cmssw/blob/master/CUDADataFormats/Vertex/interface/ZVertexSoA.h).

This match is not correct: indeed, the idv has to be compared with the vertex index.

(*) all tracks with vertex index -1 are not considered, since this means that they are not associated to any vertex
(**) the sortInd is of a subset of all vertices, since they are required to pass some quality cuts described in the function SelectGoodVertices. Also in this function there is a similar matching requirement and also in that case it has been changed.

In this PR, this bug is fixed.
 
#### PR validation:

This bug was spotted because while looping multiple times on GPU, results were not consistent among each other.
With the aforementioned change, some preliminar tests on GPU and CPU have been carried on, selecting specific bugged events and from those preliminar tests there are no more differences.

With CPUs there were no difference both before and after the bugfix. So integrating this PR CPU results should be kept unchanged (in terms of efficiencies and rates).
#### if this PR is a backport please specify the original PR and why you need to backport that PR:
 This is the backport of the PR [cmssw-37291](https://github.com/cms-sw/cmssw/pull/37291#event-6316402847)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
backport of #37291

@valeriadamante , please add "L2TauTagNNProducer" to the title of this PR.

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
+hlt

 - bugfix PR for HLT by TAU POG, exact of backport of #37291

@valeriadamante , please don't forget the following
> add "L2TauTagNNProducer" to the title of this PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
