### PR TITLE
First implementation of edm::soa::Table

### PR DESCRIPTION
**Pull request by Dr15Jones**
First implementation of a 'structure of arrays' object which uses a spreadsheet like metaphor.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
