### PR TITLE
Added full support for spectator variables in the TMVAEvaluator class: 74X

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10204

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10206	c98841b
- code changes are the same as in the 76X PR https://github.com/cms-sw/cmssw/pull/10204	8275b0d
-  this extends the functionality of the TMVAEvaluator, the default behavior is unchanged
- jenkins tests pass and comparisons with the baseline show no difference as expected
- this should simplify developments at the analysis level (including analysis processing recipes) so, inclusion in 74X is justifiable

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
