### PR TITLE
Remove hydjet (1.9.1) interface

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Drop HydjetInterface (for hydjet 1.9.1) due to removal of legacy MC generators (https://github.com/cms-sw/cmsdist/pull/7763).

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by stahlleiton** [comment]
Hi @iarspider ,
The HIN PAG still heavily use Hydjet 1.9 generator (see the minimum bias request for 2018 PbPb in https://cms-pdmv.cern.ch/mcm/requests?prepid=HIN-HINPbPbAutumn18GS-00033&page=0&shown=127) to produce PbPb minbias samples, which are crucial for analysis and run preparation. We plan to start the transition to Hydjet++ soon, but we still need the old generator to prepare samples for the Run 3 PbPb data taking. So please do not remove it yet.
@mandrenguyen

**Comment by iarspider** [comment]
Hi @stahlleiton,

we will keep hydjet 1.9 based on your request.

**Pull request closed without merging**
