### PR TITLE
Reduce the ECAL and HCAL GPU memory usage [12.5.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:
    
Allocate memory buffers based on the actual number of events, instead of always allocating the maximum size.

Update the HLT menus to remove the obsolete parameters, if they are present.

Reduces the total GPU memory from running the HLT with 4 jobs with 32 threads and 32 streams by about 25%:

release | total | reserved | used | free
-- | -- | -- | -- | --
CMSSW_12_4_9 | 15360 MB | 449 MB | 10678 - 10090 MB | 4231 - 4819 MB
with #39580 | 15360 MB | 449 MB | 7366 - 8056 MB | 7543 - 6853 MB

Thanks to @VinInn for finding the issue and for the changes.

#### PR validation:

The full HLT menu runs on GPU (with 12.4.9 plus #39580) without issues.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39577.

### CODE REVIEW

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
backport of #39577

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
