### PR TITLE
Follow-up to HLT HG Combined PCL workflow

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a quick follow-up to https://github.com/cms-sw/cmssw/pull/46888 which introduced a new High Granularity Tracker Alignment Prompt Calibration Loop using both MinumumBias and Z → µµ data ("HG Combined alignment"), aiming to provide alignment conditions for the High Level Triggers (HLT).
   * dd23ea9120921e09615c92ea08bd5de0c36b457b: fetch HLT ESproducers directly from the HLT menu, to guarantee they stay in synch
   * daea152844e156e1b506f8a3076e676aaa25855f: add SiPixelAli HG Combined workflows to testPCLAlCaHarvesting
   * 581a19f552d4d649f82d328e37aae691cfcd2564: add json files for HG combined SiPixel @ HLT worfklow and update DropBoxMetaData writer and reader configurations

#### PR validation:

The following unit tests runs correctly:
   * `scram b runtests_testAlCaHarvesting`
   * `scram b runtests_testDropboxMetadataDB`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

Cc: @phnattla

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- There are quite several warning messages in the "testAlCaHarvesting": it would be probably worth to address them at some point to make that test more effective, but those warnings are not caused by this PR.

**Comment by mmusich** [comment]
> There are quite several warning messages in the "testAlCaHarvesting": it would be probably worth to address them at some point to make that test more effective, but those warnings are not caused by this PR.

they are **intended** as the test runs without any data. The point of the test is to demonstrate we can safely run the alcaharvesting without crashing on missing input ;)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
