### PR TITLE
Fix improper forward type in ConvBremSeedProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
This fixes a clang warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
Is ```transformer_``` useful at all? Shouldn't it better removed from the class members, as well as the line that you modified?

**Comment by Dr15Jones** [comment]
@perrotta I was just doing th bare minimum to fix the compiler warning. It’s great if my change triggers others to improve the code more.

**Comment by perrotta** [comment]
-1
(Superseeded by #25750)

**Pull request closed without merging**
