### PR TITLE
Fixed compilation problems for Geant4 10.3

### PR DESCRIPTION
**Pull request by civanch**
When compile Geant4 10.3 few problems appears in files which used rarely. Trivial fixes should resolve these issues.

No effect on SIM or FastSIM production or on alignment.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@franzoni, @mmusich, this PR is really trivial and only provides compilation for few files.

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
