### PR TITLE
[nT2] zero-initialisation of TotemT2Digi members

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

This PR ensures all members of the TotemT2Digi object are zero-initialised, following the discussion in #38986 for equivalent rechits.

#### PR validation:

Code compiles and runs.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: N/A

### CODE REVIEW

**Comment by forthommel** [comment]
As this PR is purely technical and could prevent some unassigned values and memory corruption, can we aim at a fast merge?

**Comment by perrotta** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- bugfix for uninitialized values

**Comment by perrotta** [comment]
+1

**Pull request merged**
