### PR TITLE
Step 8: Simulation Clang tidy code-checks-all 

### PR DESCRIPTION
**Pull request by ianna**
* Split #20511 as suggested by @civanch here #20511 (comment)

Step 8. SimDataFormats

* This PR is based on https://github.com/cms-sw/cmssw/pull/20532, #20531, #20530, #20529, #20528, #20527, #20525, #20524, #20514
It will be rebased if needed after they are subsequently merged.

@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
Note, the number of files in total is 716 ( there were 706 in https://github.com/cms-sw/cmssw/pull/20511) due to SimRomanPot package added in Step 1.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - FYI, this PR is more complete then https://github.com/cms-sw/cmssw/pull/20511

**Comment by ianna** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
