### PR TITLE
CSCDigitizer cout to MessageLogger and updates

### PR DESCRIPTION
**Pull request by ptcox**
Attempted to fix the multithreading incompatibilities in CSCDigitizer as listed by Chris Jones in 2014, Just about all these are replacing cout by LogVerbatim. At the same time I updated sample config files, and reorganized the debugging output of CSCGasCollisions (ready for studies of those simhits which do not lead to CSC digis - mainly low energy electrons that do not cross a CSC gas layer.) As part of this updating I also had to remove cout in the CSC Digis themselves - that pull request has already been accepted in 75X. I have thoroughly tested these updates in 732 but I have not been successful in running in a 75X IB - assert failure in calorimeter digitization, which of course has nothing to do with this pull request.

### CODE REVIEW

**Comment by civanch** [comment]
@ptcox , in  SimMuon/CSCDigitizer/python/muonCSCDigis_cfi.py  you take out bunch time offsets for run-2. Does this means that default values should work fine both for run-1 and run-2?

**Comment by civanch** [comment]
please test

**Comment by ptcox** [comment]
Hi Vladimir,

I didn't intend to change anything there. But I now see that horrid 'eras' stuff has been inserted and I have accidentally removed it. I'll put it back in.

Tim

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
