### PR TITLE
Roll-back to old configuration to fix issue in VID

### PR DESCRIPTION
**Pull request by matteosan1**
Revert the configuration to the old one to avoid VID problems.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@matteosan1 The fix looks fine. Back port as necessary.

**Comment by cvuosalo** [comment]
@matteosan1: For the record, could you please add an explanation to the PR description of the problem you're fixing and how it changes reco?

**Comment by cvuosalo** [comment]
+1

For #11126 f37d13ccef34ae18ff35afd6fe3786243ef9714e

Rolling back to old e/gamma configuration for Mini-AOD to fix issue in VID.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11126/7895/summary.html) against baseline CMSSW_7_4_X_2015-09-03-2300 show no significant differences.

**Pull request merged**
