### PR TITLE
[13_2_X] Add WFs for 2023D

### PR DESCRIPTION
**Pull request by sunilUIET**
Backport of https://github.com/cms-sw/cmssw/pull/42413

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:
relvals_opt= -w standard
workflows = 141.039,141.041,141.041,141.043,141.044,141.045,141.046,141.047,141.048,141.049

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by sunilUIET** [comment]
test parameters:
relvals_opt= -w standard
workflows = 141.039,141.041,141.041,141.043,141.044,141.045,141.046,141.047,141.048,141.049
pull_request=https://github.com/cms-sw/cmssw/pull/42371

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
please abort

**Comment by sunilUIET** [comment]
test parameters:
relvals_opt= -w standard
workflows = 141.039,141.041,141.042,141.043,141.044,141.045,141.046,141.047,141.048,141.049
pull_request=https://github.com/cms-sw/cmssw/pull/42371

**Comment by sunilUIET** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Good to go when https://github.com/cms-sw/cmssw/pull/42371 is merged.

**Comment by perrotta** [comment]
+1

**Pull request merged**
