### PR TITLE
Move edmStreamStallGrapher.py from bin to scripts so that it gets found automatically from $PATH

### PR DESCRIPTION
**Pull request by makortel**
Title says it all.

Tested in CMSSW_10_1_X_2018-03-15-2300, no changes expected.

@Dr15Jones @wddgit

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failures have nothing to do with this pull request. They come from failures in the IB.

**Comment by fabiocos** [comment]
+1

emd utility moved to another directory

**Comment by fabiocos** [comment]
merge

**Pull request merged**
