### PR TITLE
Hcallogicalmap

### PR DESCRIPTION
**Pull request by weihuacern**
Hcal Logical map update, including 
CondFormats/HcalObjects/interface/HcalLogicalMap.h
CondFormats/HcalObjects/src/HcalLogicalMap.cc
CondFormats/HcalObjects/interface/HcalMappingEntry.h
CondFormats/HcalObjects/src/HcalMappingEntry.cc
CalibCalorimetry/HcalAlgos/src/HcalLogicalMapGenerator.cc
CalibCalorimetry/HcalAlgos/interface/HcalLogicalMapGenerator.h
CalibCalorimetry/HcalAlgos/test/MapTester.cc
CalibCalorimetry/HcalAlgos/test/maptester_cfg.py

And also
CalibCalorimetry/HcalAlgos/data/
DB_HBHEHOHF_Calib.txt

HOremap_Feb2015_crate13.txt

HOremap_Feb2015_crate6.txt

QIE_FNAL_normal.txt

DB_HBHEHOHF_Normal.txt

HOremap_Feb2015_crate3.txt

HOremap_Feb2015_crate7.txt

RBX_RM_QIE.txt

### CODE REVIEW

**Comment by weihua19900704** [comment]
PR for 7_3_X

**Comment by davidlange6** [comment]
lets discuss how to integrate this PR in 75x first. Please open a pull request there if not done already.

**Comment by diguida** [comment]
@davidlange6 the 75X is #8545 but I cannot find the one for 74X

**Comment by davidlange6** [comment]
we’ll need changes, so lets concentrate on 75x for now…

**Pull request closed without merging**
