### PR TITLE
adding edm::stream::EDProducer friend for multithread

### PR DESCRIPTION
**Pull request by amassiro**
Backporting of 75X PR:    https://github.com/cms-sw/cmssw/pull/9717

### CODE REVIEW

**Comment by mmusich** [comment]
pleae test

**Comment by mmusich** [comment]
@cmsbuild tests seem stuck... what should we do?

**Comment by mmusich** [comment]
@davidlange6 we need this change to allow introduction of the ElectronStream for the 50ns HLT menu. Can we move forward with the tests?

**Comment by degano** [comment]
@mmusich @davidlange6 I have no idea where the tests sunk, I've restarted them now.

**Comment by mmusich** [comment]
@degano any news?

**Comment by davidlange6** [comment]
As the pr doesn't merge no tests will run



On Jun 25, 2015, at 6:56 PM, Marco Musich <notifications@github.com<mailto:notifications@github.com>> wrote:


@degano<https://github.com/degano> any news?

**Comment by amassiro** [comment]
This PR should be queued to 74X, while in the test I see that it's trying to merge it in 75X.

The 75X release PR is: https://github.com/cms-sw/cmssw/pull/9717

**Comment by mmusich** [comment]
@davidlange6 how am I supposed to trust the bot log? It says it's trying to merge to 7.5.X and it's stuck since two days

**Comment by mmusich** [comment]
```
cmsrel CMSSW_7_4_X_2015-06-24-2300
cd CMSSW_7_4_X_2015-06-24-2300/src/
cmsenv
git cms-merge-topic 9720
scramv1 b -j 8
```
works fine for me

**Comment by diguida** [comment]
@davidlange6 the bot is trying to merge this branch (starting from `CMSSW_7_4_X` branch) into the `CMSSW_7_5_X` branch, hence the conflict:

````
+ git cms-merge-topic -u 9720
No release tags specified, using default CMSSW_7_5_X_2015-06-24-2300.
You are on branch CMSSW_7_5_X
````

I assume this was also blocking the tests.

OTOH, the github GUI says that the branch is mergeable in `CMSSW_7_4_X` branch, and I checked this too:

````
cmsrel CMSSW_7_4_X_2015-06-24-2300
cd CMSSW_7_4_X_2015-06-24-2300/src/
cmsenv
git cms-merge-topic -u 9720
scram b -r -j 16
````

**Comment by slava77** [comment]
from the logs it seems like the jenkins tests were started manually (not by the bot)

**Comment by davidlange6** [comment]
CmsBuild please test

Maybe it will work now



On Jun 25, 2015, at 8:06 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:


from the logs it seems like the jenkins tests were started manually (not by the bot)

**Comment by diguida** [comment]
@slava77 I cannot see this in the logs folder...

**Comment by slava77** [comment]
I started a build that went with 74X.

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1
(indeed, not used offline as @Martin-Grunewald said)

**Pull request merged**
