### PR TITLE
[121X] Modify calculations for the Lorentz angle

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See describtion at https://github.com/cms-sw/cmssw/pull/36241

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/36241

Needed for the T0 replay

### CODE REVIEW

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36241

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+alca

 - leads to the same (expected) result (https://tinyurl.com/y47aco4t) as observed in the master PR (https://github.com/cms-sw/cmssw/pull/36241#issuecomment-979299817)

**Comment by qliphy** [comment]
+1
tested in master IB

**Pull request merged**
