### PR TITLE
re-miniAOD workflows on 94X input datasets (94X)

### PR DESCRIPTION
**Pull request by fabozzi**
Adding re-miniAOD workflows on 94X MINIAOD inputs (data and MC).

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of #22200

**Comment by fabozzi** [comment]
please test workflow 1325.51

**Comment by fabiocos** [comment]
@fabozzi I see that this PR has also been queued in 9_4_MAOD_X, so I assume this one is not needed...

**Comment by fabozzi** [comment]
I was not sure... so please approve what is needed (one of them or both)

**Comment by kpedro88** [comment]
@fabozzi should this be closed?

**Comment by fabozzi** [comment]
I think so, this has proceeded in 9_4_MAOD branch

**Pull request closed without merging**
