### PR TITLE
Add esConsumes to modules that inherit from TrackProducerBase

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- refactored TrackProducerBase to allow use of esConsumes.
- added some explicit esConsumes calls in modules.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35145	beac003 
- code changes are technical in line with the PR description 
    - `es.get` calls are still present in DAFTrackProducer.cc:76,81,84 and GsfTrackRefitter.cc:74, but neither of these are executed in runTheMatrix workflows. So, it should be OK to leave it for a later update.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
