### PR TITLE
[12_4_X] Safeguard for nHits==0

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Backport to 12_4_X of #38159 

Following discussion in #37933

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type trk

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by perrotta** [comment]
@AdrianoDee could you please give a more descriptive title to the PR, for example the same of the backported one?

**Comment by AdrianoDee** [comment]
> @AdrianoDee could you please give a more descriptive title to the PR, for example the same of the backported one?

Sure, moved to the original PR title

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38159

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by jpata** [comment]
+reconstruction
- backport of https://github.com/cms-sw/cmssw/pull/38159
- bugfix for HLT

**Pull request merged**
