### PR TITLE
Add weight to HCAL output LUT and add all input tags to trigger key

### PR DESCRIPTION
**Pull request by ak427**
#### PR description:

  -  add a WEIGHT in the output LUT to be loaded in uHTRs, as discussed with @JHiltbrand and @jmmans 
  -  add all input tags used for TPG LUT generation explicitly in the corresponding trigger key to aid O2O
  - The changes should not affect any offline workflow
  

#### PR validation:

  - New test LUT and trigger key have been generated successfully

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by yuanchao** [comment]
+1
* added WEIGHT in the output LUT and all input tags used for TPG LUT
* passed WF matrix tests and unit tests
* Static build warnings are not part of the PR

**Comment by cecilecaillol** [comment]
+l1

**Comment by boudoul** [comment]
Hi @ak427 , do you have an interest of testing this code during the next MWGR ? Thanks

**Comment by akhukhun** [comment]
> Hi @ak427 , do you have an interest of testing this code during the next MWGR ? Thanks

The code itself is kind of tested in a sense that it generates the trigger key and output LUT with desired content. 
In terms of seeing them in the action, we will probably be able to test some O2O functionality, at least that's the plan. For the TP part, it's probably unlikely that we will be ready for this in the coming MWGR. We will see...

**Comment by boudoul** [comment]
alright, thanks @ak427 for the clarification .

(@amassiro FYI)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
