### PR TITLE
[master] Drop references to legacy generators

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:
Drop references to legacy generators. Forward port of PRs opened for DEVEL_X branch.

Original PRs: #37610, #37611, #37612, #37616;
cmsdist PR: https://github.com/cms-sw/cmsdist/pull/7844

#### PR validation:

Validated in the original PRs and in DEVEL IBs

### CODE REVIEW

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7844

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7844

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , any idea why there are a lot of dqm comparison differences for workflow [9.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-05-2300+a3762f/50088/validateJR.html) ?

**Comment by makortel** [comment]
> any idea why there are a lot of dqm comparison differences for workflow [9.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-05-2300+a3762f/50088/validateJR.html) ?

These occurred also in https://github.com/cms-sw/cmssw/pull/37592#issuecomment-1112925145 (which was purely technical). I guessed (without any investigation) it might be related to https://github.com/cms-sw/cmssw/issues/34448, but given the affected workflow was always 9.0, maybe it could be related to the generator setup of that workflow.

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 @cms-sw/analysis-l2  can you please review this? This has been integrated in DELVEL IBs and all workflows run fine.  This update should allow us to drop the legacy generators packages from cmssw distribution

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
