### PR TITLE
Changes for L1DQM configuration

### PR DESCRIPTION
**Pull request by jingyucms**
76x version for part of PR11617 (https://github.com/cms-sw/cmssw/pull/11617), where 11617 is used as production.

### CODE REVIEW

**Comment by jingyucms** [comment]
@deguio @mulhearn Please test this one.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
is #11617 now final?

**Comment by jingyucms** [comment]
@deguio I maybe need #11617 to keep. There maybe something to be update for heavy ion run. But I don't know the details yet.

**Comment by smuzaffar** [comment]
please test

**Comment by deguio** [comment]
needs a rebase

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@jingyucms 
also this one needs updates
thanks!
F.

**Comment by jingyucms** [comment]
working on PR12443

**Pull request closed without merging**
