### PR TITLE
Phase2-hgx310C Add in line documentation to some service methods in Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add in line documentation to some service methods in Geometry/HGCalCommonData

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Inline documentation. No code changes.

**Comment by perrotta** [comment]
+1

**Pull request merged**
