### PR TITLE
FastSim premixing workflows and matrix cleanup [14_0_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #46007

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by kpedro88** [comment]
@cms-sw/upgrade-l2 please sign

**Comment by srimanob** [comment]
Kindly ping @cms-sw/upgrade-l2

**Comment by mandrenguyen** [comment]
hold 
is this needed for 14_0_X at this point?

**Comment by kpedro88** [comment]
Yes, this is needed in 14_0_X:
1. This workflow in this release was used for the CDR profiling. It should be reproducible in the future without manually merging branches/PRs.
2. We anticipate possible Run 3 FastSim production in this release.

**Comment by antoniovilela** [comment]
unhold

**Comment by antoniovilela** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
