### PR TITLE
DQM for SMP PAG status

### PR DESCRIPTION
**Pull request by sasharma6**
Problem :- SMP DQM validation (which at the moment is broken) i.e. Empty Plots
in SMP PPD DQM codes (Electron & Muon DQM) in MiniAOD framework.

Solution implemented:-  wrote an analyzer and run manually on the relval samples () to perform validation. Codes are made independent to Trigger and checked.

Things to do: To approve the code and check whether it is properly merged"

### CODE REVIEW

**Comment by dmitrijus** [comment]
Hi, you also need to enable these modules to be run centrally.

https://github.com/cms-sw/cmssw/blob/master/DQM/Physics/python/DQMPhysics_cff.py#L22

**Comment by sasharma6** [comment]
Hi Dmitrijus, i am unable to get this thing. Can you please explain me what to do and procedure for this.

**Comment by fabozzi** [comment]
@sasharma6 
I think @dmitrijus is asking you to uncomment the lines he highlighted in the link he provided, make a commit of the changes and then push again in the git repository (this will update your PR with the changes)

@fabozzi

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
The module which causes the error above is because you duplicated the "plugin" declaration.

They are normally declared in,
https://github.com/sasharma6/cmssw/blob/460d1b0fafc5eb3321a2f3c2bc55ef00be43e0f3/DQM/Physics/src/plugins.cc

But for some reason, you actually re-declared them inside EwkMuDQM.cc

Before pushing another commit, please run:
`runTheMatrix.py -l 4.22 `
and make sure it does not crash.

Then make sure that `runTheMatrix.py -l limited` does not crash either.

**Comment by sasharma6** [comment]
@dmitrijus : I have removed the redeclared "EwkMuDQM.h" from EWKMuDQM.cc as it is already declared in plugins.cc as you have mentioned.
Then i run the 
runTheMatrix.py -l 4.22  after seeting voms-proxy

which leads to following result

Preparing to run 4.22 RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
cleaning up  4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC  in  /afs/cern.ch/work/s/sasharma/demo/CMSSW_9_1_0_pre1/src/cmssw/DQM/Physics/src

# in: /afs/cern.ch/work/s/sasharma/demo/CMSSW_9_1_0_pre1/src/cmssw/DQM/Physics/src going to execute cd 4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
 echo '{
"160960":[[1,268435455]]
}' > step1_lumiRanges.log  2>&1
 

# in: /afs/cern.ch/work/s/sasharma/demo/CMSSW_9_1_0_pre1/src/cmssw/DQM/Physics/src going to execute cd 4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
 (das_client --limit 0 --query 'file dataset=/Cosmics/Run2011A-v1/RAW run=160960 site=T2_CH_CERN') | sort -u > step1_dasquery.log  2>&1
 
---
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Tue May  2 08:04:53 2017-date Tue May  2 08:02:19 2017; exit: 1 0 0 0 0
0 0 0 0 0 tests passed, 1 0 0 0 0 failed

**Comment by fabozzi** [comment]
@sasharma6 

This appears as a DAS error.
Can you remove site=T2_CH_CERN
in the following lines of code:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/MatrixUtil.py#L178-L181

and retry?

**Comment by sasharma6** [comment]
@fabozzi Yes i tried it by commenting the lines (#L 178-181.) of MatrixUtil.py  but same error is still there.

**Comment by fabozzi** [comment]
@sasharma6 
I didn't suggest to comment. I asked to remove only
"site=T2_CH_CERN" so that the search is not only
restricted to dataset being at cern.
After that you re-compile and retry.

**Comment by sasharma6** [comment]
@fabozzi yes i got your point, error  in this case is still same. Even after removing "site = T2_CH_CERN". It is still picking "das_client --limit 0 --query 'file dataset=/Cosmics/Run2011A-v1/RAW run=160960 site=T2_CH_CERN'" while running runThematrix.py

I am mentioning  file changes and error both

changes in MatrixUtil.py file :
" if len(self.run) is not 0:
            return ["file {0}={1} run={2} ".format(query_by, query_source, query_run) for query_run in self.run]
            #return ["file {0}={1} run={2} ".format(query_by, query_source, query_run) for query_run in self.run]
        else:
            return ["file {0}={1} ".format(query_by, query_source)]
            #return ["file {0}={1} ".format(query_by, query_source)]"

Error : "# in: /afs/cern.ch/work/s/sasharma/demo/CMSSW_9_1_0_pre1/src/cmssw/DQM/Physics/src going to execute cd 4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
 echo '{
"160960":[[1,268435455]]
}' > step1_lumiRanges.log  2>&1
 

# in: /afs/cern.ch/work/s/sasharma/demo/CMSSW_9_1_0_pre1/src/cmssw/DQM/Physics/src going to execute cd 4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
 (das_client --limit 0 --query 'file dataset=/Cosmics/Run2011A-v1/RAW run=160960 site=T2_CH_CERN') | sort -u > step1_dasquery.log  2>&1
 
---
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Tue May  2 15:23:42 2017-date Tue May  2 15:23:07 2017; exit: 1 0 0 0 0
0 0 0 0 0 tests passed, 1 0 0 0 0 failed"

**Comment by prebello** [comment]
Hi Sandeep

did you "scram b" after changing?

Cheers Patricia
________________________________

**Comment by sasharma6** [comment]
@prebello yes i did scram b after the changes

**Comment by fabozzi** [comment]
@sasharma6 

As you write down:

(das_client --limit 0 --query 'file dataset=/Cosmics/Run2011A-v1/RAW run=160960 site=T2_CH_CERN') | sort -u > step1_dasquery.log 2>&1

so the DAS command is still asking site=T2_CH_CERN.

Therefore we think you did not re-compile after your change.

**Comment by fabozzi** [comment]
@sasharma6 
in case the issue is not yet understood, please put your working area
in a public area and we will give a look

**Comment by davidlange6** [comment]
any further plans to update this PR?

**Pull request closed without merging**
