### PR TITLE
PCL new workflow for High Perf Beamspot, 2017B relval, 2017B HPBS relval (backport)

### PR DESCRIPTION
**Pull request by franzoni**
backport of https://github.com/cms-sw/cmssw/pull/19427

### CODE REVIEW

**Comment by franzoni** [comment]
backport of https://github.com/cms-sw/cmssw/pull/19427

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@franzoni 
this update didn't work here. Either a rebase or something is needed.

**Comment by davidlange6** [comment]
please test

**Comment by franzoni** [comment]
closing and replacing with https://github.com/cms-sw/cmssw/pull/19669

**Pull request closed without merging**
