### PR TITLE
Renewed PF validation 

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

Renewed PF validation version 1. We would like to include this in the regular validation/DQM sequence, but we also intend to use them to run on the fly to test planned PF optimization/development. The currently added histograms are for evaluation jet response, resolution, and offset distributions.

#### PR validation:

The example plots look like:
2018 MC: http://hep.baylor.edu/hatake/PFval/val_10_6_0_test1/
Phase 2: http://hep.baylor.edu/hatake/PFval/val_10_6_0_phase2/
Also they were tested with various matrix tests:
10024.0
10824.0
136.888
2018.1
29034.0

#### if this PR is a backport please specify the original PR:

Not applicable.

@jpata @juska @bendavid

### CODE REVIEW

**Comment by hatakeyamak** [comment]
@jpata @juska @bendavid

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by hatakeyamak** [comment]
I would like to update README somewhat based on some feedback we received, so can you wait a bit before "please test"?

**Comment by hatakeyamak** [comment]
From my point of view, now this is ready for further jenkins tests...

**Comment by hatakeyamak** [comment]
Well, there may be some unnecessary files which we can clean up from this PR. Checking.

**Comment by hatakeyamak** [comment]
We did some cleanup of this PR, and we think this is ready for further jenkins test.
Thanks @juska @jpata

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@hatakeyamak  This PR is adding ~1.6k histograms into DQM (number is variable since it depends in the PU/npv). Can you please do a last check that the distributions make sense? E.g.
http://tinyurl.com/y3sy6hlt

**Comment by hatakeyamak** [comment]
Thank you @jfernan2 . Plots look as I expect from low stat samples.
@juska maybe you can have another look as well?

**Comment by juska** [comment]
Hi,

I also took a look. They look as good as they can with the tiny data sample. So all good.

Juska



________________________________________

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@hatakeyamak @jfernan2 I have looked at this PR, it looks basically ok to me, but I have a couple of minor remarks:

- I would prefer to avoid proliferating top level non-conventional subdirectories in Validation/RecoParticleFlow . "crab" could be just a subdirectory of "test", or its content could just sit in test (or possibly in bin, they are standalone python scripts);

- similarly tmp could be moved inside test (as it is just a repository of files used there). I am not sure whether hardcoding file lists in CMSSW is the best approach, this list will likely become quickly obsolete.  Would not be better to have the corresponding dasgoclient query (as in PyReleaseValidation)?

- we have other examples of MakeFile within packages, even in the top level directory, @smuzaffar I understand this is not interfering in any way with scram

**Comment by smuzaffar** [comment]
@fabiocos , yes Makefile will not interfere with scram

**Comment by makortel** [comment]
> * I would prefer to avoid proliferating top level non-conventional subdirectories in Validation/RecoParticleFlow . "crab" could be just a subdirectory of "test", or its content could just sit in test (or possibly in bin, they are standalone python scripts);

In case of `bin`, `multicrab.py` and `multicrab_phase2.py` sound rather general names to me to be put on everyones `$PATH`. (ok, on the other hand IIRC from `bin` they would not be placed in `$PATH` unless explicitly specified in `BuildFile.xml`)

**Comment by hatakeyamak** [comment]
> * I would prefer to avoid proliferating top level non-conventional subdirectories in Validation/RecoParticleFlow . "crab" could be just a subdirectory of "test", or its content could just sit in test (or possibly in bin, they are standalone python scripts);

Probably ok to move "crab" and "tmp" under test. Let us see if it can cause some unwanted effects.

> * similarly tmp could be moved inside test (as it is just a repository of files used there). I am not sure whether hardcoding file lists in CMSSW is the best approach, this list will likely become quickly obsolete.  Would not be better to have the corresponding dasgoclient query (as in PyReleaseValidation)?

Same as above. Actually there is already a python script to make filelists ( Validation/RecoParticleFlow/test/datasets.py), so they can be removed. We just have to update the on-the-fly operation's readme to reflect that we have to run this script to make the filelist always.

> * we have other examples of MakeFile within packages, even in the top level directory, @smuzaffar I understand this is not interfering in any way with scram

I understand that this is ok, right?

@juska do you think you can take over the suggested work above?

**Comment by juska** [comment]
Sure, I'll try moving the directories and test the code with the changes later this week.

**Comment by fabiocos** [comment]
hold

just to mark that there is still work in progress

**Comment by hatakeyamak** [comment]
I think @juska addressed suggestions from @fabio and this PR is good to go again.

**Comment by juska** [comment]
I confirm what @hatakeyamak said; I moved tmp/ and crab/ directories under test and updated the README for creating input file lists every time for manual running and a suggestion to check input datasets in the case of CRAB running.
I decided to leave the now fine file lists files to the repository, they will get overridden whenever a user creates new file lists.

**Comment by fabiocos** [comment]
@juska @hatakeyamak thank you for following my suggestion, but apparently this was done just in the script, I still see the directories proposed in this PR:
```
15:42 cmsdev25 795> git log --topo-order --graph --pretty=oneline | head -n 6
*   e3ae9be8a585941f8ba80086a07733203b808efb Merged refs/pull/27048/head from repository cms-sw with cms-merge-topic
|\  
| * 2b4f92d35f5b2b8c4f53bd3041b0b798d36651e5 Apply automatic code formattingÃ
| * c78731744254044163c942cc40e9c96d50aabc78 Save only miniAOD files. Add plotting options to Makefile. Extend and polish README.
| * 22d5cb0f011dbd1266f2f7f2a5bd2c9357ac3c36 Disable fraction pseudorapidity plotting cuts
| * f504abae6445b0a8cb11d14670df67dc4b57bb38 Move tmp/ and crab/ under test/ and update code accordingly
15:42 cmsdev25 796> git diff --name-only CMSSW_11_0_X
DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
DQMOffline/Configuration/python/DQMOffline_cff.py
DQMOffline/Configuration/python/autoDQM.py
Validation/RecoParticleFlow/Makefile
Validation/RecoParticleFlow/README.md
Validation/RecoParticleFlow/bin/BuildFile.xml
Validation/RecoParticleFlow/bin/offsetStack.cc
Validation/RecoParticleFlow/crab/multicrab.py
Validation/RecoParticleFlow/crab/multicrab_phase2.py
Validation/RecoParticleFlow/plugins/BuildFile.xml
Validation/RecoParticleFlow/plugins/OffsetAnalyzerDQM.cc
Validation/RecoParticleFlow/plugins/OffsetDQMPostProcessor.cc
Validation/RecoParticleFlow/plugins/PFJetAnalyzerDQM.cc
Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc
Validation/RecoParticleFlow/python/DQMForPF_MiniAOD_cff.py
Validation/RecoParticleFlow/python/defaults_cfi.py
Validation/RecoParticleFlow/python/offsetAnalyzerDQM_cff.py
Validation/RecoParticleFlow/python/particleFlowDQM_cff.py
Validation/RecoParticleFlow/test/MinBias.jdl
Validation/RecoParticleFlow/test/QCD.jdl
Validation/RecoParticleFlow/test/QCDPU.jdl
Validation/RecoParticleFlow/test/ZMM.jdl
Validation/RecoParticleFlow/test/compare.py
Validation/RecoParticleFlow/test/datasets.py
Validation/RecoParticleFlow/test/filelist_QCD.txt
Validation/RecoParticleFlow/test/getHists.py
Validation/RecoParticleFlow/test/offsetStack.py
Validation/RecoParticleFlow/test/run_relval.sh
Validation/RecoParticleFlow/test/setup_cmssw.sh
Validation/RecoParticleFlow/tmp/das_cache/MinBias.txt
Validation/RecoParticleFlow/tmp/das_cache/NuGun_PU.txt
Validation/RecoParticleFlow/tmp/das_cache/QCD_PU.txt
Validation/RecoParticleFlow/tmp/das_cache/QCD_noPU.txt
Validation/RecoParticleFlow/tmp/das_cache/ZMM.txt
Validation/RecoTrack/python/plotting/html.py
Validation/RecoTrack/python/plotting/plotting.py
```

**Comment by juska** [comment]
Thanks @fabiocos for pointing this out. I did move the directories under 'test/' with 'git mv', but apparently this was not sufficient. I try to see what's wrong. Maybe I need to make a more exhaustive commit for really moving the directories.

**Comment by fabiocos** [comment]
@juska @hatakeyamak now it looks ok, thank you. As far as I am concerned this PR may move forward

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
