### PR TITLE
SIM: optimisation of initialisation

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Few minor modifications are added for SIM initialisation:
1) do not store full OscarMTProducer data set in the master thread RunManager.
2) moved dump of gdml geometry file to the first worker thread with sensitive detector mark attached to sensitive volumes.
3) improved few debug printouts

DO not expected any change in any WF.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
¨please test

**Comment by rappoccio** [comment]
+1

**Comment by hahnjo** [comment]
Hi @civanch, moving the GDML writing to `RunManagerMTWorker` unfortunately broke this functionality because `G4GDMLParser` has a check for `IsMaster()`. I understand this was needed for getting the sensitive detector code in the exported file and I don't have an idea how to make this work, but can we restore a basic working solution in the mean time?

**Pull request merged**
