### PR TITLE
Apply code formatting to FWCore/Framework

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Apply code formatting to FWCore/Framework.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
please test

just to have a clean reference to compare with, I do not expect differences are due to this PR

**Comment by fabiocos** [comment]
@Dr15Jones my conclusion is that both the DQM differences and the unit test failure (not present earlier) are unrelated to this PR

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by Dr15Jones** [comment]
@fabiocos I agree that the failures are unrelated.

**Pull request merged**
