### PR TITLE
Use concepts in Ref

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Discover proper comparator using concepts.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
ignore tests-rejected with ib-failure

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
