### PR TITLE
manually moving files for GeneratorInterface/EvtGenInterface/ from inuge...

### PR DESCRIPTION
**Pull request by inugent**
...nt:BSTomumu_Patch3 to new branch Replaces pull 8563.

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
This is also needed urgently for 71X

**Comment by inugent** [comment]
Hello,
   Which time slot due you want me to give the present for this pull request? Best regards,
Ian

**Comment by davidlange6** [comment]
+1

**Pull request merged**
