### PR TITLE
Add more histograms and track selections to MultiTrackValidator, remove standalone mode

### PR DESCRIPTION
**Pull request by makortel**
This PR makes several updates to tracking validation
- Add monitoring for BTV-like track selection
- Add monitoring for tracks used in AK4 PFJets whose corrected pT > 10 GeV
  - Add JetTracksAssociationToTrackRefs EDProducer to pick the Refs to tracks
- Add histograms for pileup track rate (fraction of tracks matched to TrackingParticles) from pileup)
- Add histograms for number of tracker layers, pixel layers, and 3D layers (=pixel+strip mono&stereo)
  - Add TrackingParticleNumberOfLayers class to calculate them from TrackingParticles
    - TP does not have a count of pixel nor strip mono&stereo layers
    - The number of tracker layers is in TP, but the calculation in TrackingTruthAccumulator is slightly misleading
      - It calculates the number of layer transitions when moving along the SimTrack inside out
      - This is incorrect at least for loopers, and for TPs with multiple SimTracks having SimHits in same layers
    - Eventually we should probably move to use HitPattern (either as a member of TP or as a ValueMap), but that is left for future development
- Add fake rate vs. track chi2
- Add summary plots for efficiency and fake rate per input track collection
- Add "standalone" sequences so that MTV-only validation configuration can be generated with cmsDriver
- Add configuration flags controlling which sets of histograms are booked and filled
  - Not employed in this PR, but will be used in subsequent development
- Remove the obsolete standalone-mode of MultiTrackValidator
  - This mode allowed to produce efficiencies etc. in the same job as histograms were filled, but this can not work anymore due to MT DQM, and our recommendation has been already a while to run a separate harvesting step. Getting rid of obsolete code now to ease maintenance.

Tested in CMSSW_7_5_X_2015-05-12-2300. No changes expected in existing histograms.

@rovere @VinInn

### CODE REVIEW

**Comment by lveldere** [comment]
@makortel 

Hi Matti

Will MTV-standalone via cmsDriver also work for FastSim?

Lukas

**Comment by makortel** [comment]
Hi Lukas,

Following the current construction, it would (in principle) need a separate sequence (in order to avoid tpClusterProducer in FastSim). 

On the other hand, now that we explicitly set `quickTrackAssociatorByHits.useClusterTPAssociation = False` in `TrackValidation_fastsim_cff.py`, having tpClusterProducer in the sequences for FastSim should not alter the results (just wastes some CPU), so using the same sequence as in FullSim should work in practice too. If you want to try out, use `...,VALIDATION:tracksValidationStandalone,...` in cmsDriver.

Anyway, now that you wrote it, if it doesn't work for FastSim already, I think it should be made to work.

**Comment by lveldere** [comment]
Now that I think about it, it's probably a (tiny) bit harder than that.
In any case, I'll get back to this when FastSim production is running.
I have some changes in mind for the FastSim Validation configuration that
should make these kind of things much easier.
Cheers
Lukas

On Thu, May 21, 2015 at 1:45 PM, Matti Kortelainen <notifications@github.com

**Comment by slava77** [comment]
@cmsbuild please test
(even if it's preemptive)

**Comment by makortel** [comment]
Hmm, short matrix passed in my tests. Investigating...

**Comment by makortel** [comment]
This one fixes the record when retrieving TrackerTopology, now the short matrix succeeds in CMSSW_7_5_X_2015-05-20-2300 (maybe something had changed in between).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by makortel** [comment]
I don't understand the comparisons. All RelMon, alternative, and validateJR show a lot of differences (also in data workflows). Most of the should be unrelated to the changes here (or, I can't figure out how my changes could have such effects).

I'll see if I can reproduce locally (using the same IB CMSSW_7_5_X_2015-05-20-2300).

**Comment by slava77** [comment]
@cmsbuild please test
new IB CMSSW_7_5_X_2015-05-23-1100 is in and seems ok at least on the build side
comparisons were likely affected by the temporary GT inconsistency

**Comment by cvuosalo** [comment]
Jenkins alternative-comparisons are still showing numerous differences. Some are known to be spurious, but are all of them? I will run matrix tests for comparison.

**Comment by slava77** [comment]
all differences are in the DQM, related to the particle matching.
validateJR appear to be clean

**Comment by makortel** [comment]
Differences in "global efficiency" histograms are due to added efficiency-like plots (pileup track rate). Differences in "*Mean" and "*Sigma" histograms are tiny, and since these histograms are produced by DQMGenericClient in the harvesting step and the source histograms are unchanged, I'd say they are ok (I don't know why it happens though).

This leaves a bunch of "HLT_IsoTkMu*" histograms in wfs 1330.0 and 50202.0 that have changed. For these I don't have an explanation. I can try to take a look on Tuesday (if still relevant then).

**Comment by slava77** [comment]
IsoTkMu had single-bin changes were happening randomly in run2 MC
validation comparisons
for about a week in various unrelated  PRs.
So, this can be ignored for now.

**Comment by cvuosalo** [comment]
+1

For #9201 428b85d404d9dbb7b63fb4f3703a1c36261e8754

Histograms and track selections added to MultiTrackValidator. Apart from the additions, monitored quantities should not change.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9201/7809/summary.html) against baseline CMSSW_7_5_X_2015-05-23-1100 show only the expected differences in global efficiencies plots and minor differences unrelated to this PR. Matrix tests against baseline  CMSSW_7_5_X_2015-05-20-2300 give the same results.

**Comment by makortel** [comment]
@slava77 Thanks, good to know that it is "safe" to ignore also IsoTkMu.

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
ping

**Comment by slava77** [comment]
@monttj@deguio, @danduggan please check this PR and comment if there are remaining issues on the DQM or analysis side and sign otherwise.
Thank you very much.

**Comment by monttj** [comment]
+1

**Comment by deguio** [comment]
ciao @makortel 
sorry for the delay. the PR looks ok to me, but I have two questions:
- do you have a rough estimate of the number of histograms/bins added by this? unfortunately the tests results are not available anymore.
- not sure I understand the use of cms.ignore in the trackValidationSelector sequence

thanks,
F.

**Comment by makortel** [comment]
@deguio (Just inferring from the code) the histograms/bins question can be divided to two parts
* 28 new histograms (967 bins) / track collection
* 2 new track collections (on top of the 33 already existing, if I managed to count them correctly from a configuration dump)

I have actually code almost ready for a PR (also depending on getting this one merged) that would decrease the total size of the booked histograms of MTV by ~40 % (from ~60 MB to ~36 MB). On the other hand, I have further developments again increasing the size (by 2-3x), so I guess I should try to pursue further memory savings too (they're possible, but need more effort).

The selectors in `trackValidationSelectors` are EDFilters, so in principle (by misconfiguration or something) they could reject events. Using `cms.ignore` makes it explicit that we are not interested of the filtering decisions of these selectors. More practical reason is that if one now generates a "standalone" configuration by `cmsDriver.py ... -s...,VALIDATION:tracksValidationStandalone ...", framework stops complaining from non-ignored EDFilters in an EndPath.

**Comment by deguio** [comment]
+1
thanks for the details. about the second point I guess I was asking why those selectors are EDFilters and not EDAnalyzers or EDProducers since the decision is anyway ignored.

**Comment by makortel** [comment]
@deguio Good question. RecoTrackRefSelector is defined here
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/CommonTools/RecoAlgos/plugins/RecoTrackRefSelector.cc
as a typedef of ObjectSelector, which by default inherits from EDFilter. Sure it is possible to change the definition (of RecoTrackRefSelector) to be EDProducer, but I don't know if anybody is using the current filtering functionality.

The RecoTrackSelector, that was used before #8888, on the contrary is and EDProducer
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/CommonTools/RecoAlgos/plugins/RecoTrackSelector.cc
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/CommonTools/RecoAlgos/interface/TrackFullCloneSelectorBase.h

**Comment by Dr15Jones** [comment]
Leaving these as filters is bad for the framework. Filters which are not meant to filter mess up the unscheduled system.

**Comment by venturia** [comment]
I thought it was a pillar of CMSSW that an EDFilter is also an EDProducer. Most of the object selectors are also EDFilters which are activated with a configuration flag.


On Jun 5, 2015, at 14:19 , Chris Jones <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Leaving these as filters is bad for the framework. Filters which are not meant to filter mess up the unscheduled system.

**Comment by makortel** [comment]
Quick `git grep` indicates that nobody is currently using RecoTrackRefSelector as a filter in CMSSW, so in principle we could switch it to EDProducer without braking any current behaviour. On the other hand, it is used in HLT (hltBSoftMuonMu5L3, but only as an object selector), which brings it's own twist to the integration. Or we can create a new "RecoTrackRefSelectorProducer" inheriting from EDProducer and use that here. I'm ok with anything (I only want to select here a subset of tracks as Refs, and I don't care how I do it ;) ). 

Anyway, I would prefer to leave any further development on this side to a subsequent PR.

**Comment by Dr15Jones** [comment]
@venturia On the question of filters being allowed to put products in the event. The history is originally filters were not allowed to products to the event. Then there was a request from HLT for a special case where they wanted to record why a filter chose to discard an event. So it was for that reason and only that reason that filters were allowed to put diagnostic information into the event. Unfortunately, that special case wasn't explained to others well and so people started making modules filters instead of producers.

**Comment by venturia** [comment]
I trust you. I found all the families of object selectors (vertices, tracks, …) well established (templates, base classes,…) in CMSSW already in 2009 or earlier and I thought there was a plan behind it!

On Jun 5, 2015, at 16:05 , Chris Jones <notifications@github.com<mailto:notifications@github.com>>
 wrote:


@venturia<https://github.com/venturia> On the question of filters being allowed to put products in the event. The history is originally filters were not allowed to products to the event. Then there was a request from HLT for a special case where they wanted to record why a filter chose to discard an event. So it was for that reason and only that reason that filters were allowed to put diagnostic information into the event. Unfortunately, that special case wasn't explained to others well and so people started making modules filters instead of producers.

**Comment by davidlange6** [comment]
+1

**Comment by makortel** [comment]
(Just thinking out loud) Should we then envision a massive migration campaign to transform e.g. all/most instantiations of ObjectSelector from EDFilter to EDProducer?

**Pull request merged**
