### PR TITLE
Remove GEM StripDigiSimLinks, only use GEMDigiSimLink

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Currently, there are two collections of SimLinks for GEM, GEMStripDigiSimLink and GEMDigiSimLink, which as far as I can see simply duplicate functionality. GEMStripDigiSimLink was only used in the GEMHitAssociator, but is easily replaced by GEMDigiSimLink which is used elsewhere in the codebase.

@jshlee @dildick 

#### PR validation:

Checked the a phase 2 workflow runs to completion with no errors.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@watson-ij Sounds good. AFAICT GEMStripDigiSimLink is not as useful as GEMDigiSimLink.

**Comment by dildick** [comment]
You can probably do the same for ME0DigiProducer (even if it will be phased out in due time)

**Comment by civanch** [comment]
+1

**Comment by watson-ij** [comment]
> You can probably do the same for ME0DigiProducer (even if it will be phased out in due time)

Yes, thats a good point. I added a commit which also removed the additional SimLink from ME0

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
