### PR TITLE
add missing dependency for TauAnalysis/MCEmbeddingTools/plugins

### PR DESCRIPTION
**Pull request by davidlange6**
(error in IB does not show up locally..)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@davidlange6 @smuzaffar 
is there a way to improve our jenkins build tests based on this?

**Comment by davidlange6** [comment]
maybe - not sure how to reproduce the problem at this point.

**Comment by civanch** [comment]
+1

**Pull request merged**
