### PR TITLE
pileup profile 2025_LHC_Simulation_fill12p5h_levelling9h_nb2340_xSec80mb_il2p23

### PR DESCRIPTION
**Pull request by romeof**
#### PR description:
pileup profile 2025_LHC_Simulation_fill12p5h_levelling9h_nb2340_xSec80mb_il2p23
more info on this talk 
https://docs.google.com/presentation/d/1ZUWK_crXtVI3aVU6z0uG0Xmy3926jrDN2ZK1WS3dqhs/edit?usp=sharing

Thanks a

#### PR validation:
Tested on cmssw

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
Hi @romeof  
I'm wondering if there are some supporting materials (plots/slides) to refer to ? 🤔
I mean when HCAL will be soon using this profile in the assessment of cuts/parameters in the context of Run3Winter25 preparations.

**Comment by civanch** [comment]
please test

**Comment by romeof** [comment]
Hi @abdoulline 
yes, there are slides as each request is a process that involves PPD/PC/RC. 

They are here https://docs.google.com/presentation/d/1ZUWK_crXtVI3aVU6z0uG0Xmy3926jrDN2ZK1WS3dqhs/edit?usp=sharing 

Thanks and best regards,
Francesco

**Comment by abdoulline** [comment]
Thanks @romeof !

**Comment by civanch** [comment]
@romeof , better to add the link to the PR description: you can edit it - this will not trigger extra testing or anything extra.

**Comment by romeof** [comment]
Good idea. Done. Thanks.

**Comment by civanch** [comment]
+1

**Comment by vlimant** [comment]
urgent

**Comment by vlimant** [comment]
assign ppd

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
