### PR TITLE
Added Consumes to SteppingHelixPropagatorESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
Added consumes to SteppingHelixPropagatorESProducer.
Switched to using ESGetTokens.
Ran the code formatting tool. 

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
> DQMHistoTests: Total failures: 21427

I was expecting no differences.
It looks like something random is happening in the workflows with mixing.

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26994	bc835cd 
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
