### PR TITLE
Run3-hcx240 Clean up two HCal endcap algorithms for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Clean up 2 more dd4hep algorithms for hadron calorimeter

#### PR validation:

Tested using the cfg files in Geometry/HcalAlgo/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
