### PR TITLE
unscheduled + 2015B relvals

### PR DESCRIPTION
**Pull request by franzoni**
- for the unscheduled fundamenals, this PR gets the two commits from #10403 , thaks @davidlange6 
- for the unscheduled relval part, this PR inherits from #10440 (merged in 74x)
- full simr run2   and   realdata workflows are unscheduled 
  (except cosmics; not fast sim)
- new real data workflows added for 2015
- tools to select RAW data input based on lumi-section; factorization away from relval_steps into MatrixUtil
- 2015 golded json added and used to filter 2015B relval input

### CODE REVIEW

**Comment by franzoni** [comment]
please test

(running extended local tests in parallel)

**Comment by franzoni** [comment]
please test

(running further extended local tests in parallel)

**Comment by franzoni** [comment]
both failures are related to a specific ALCA producer, HcalCalMinBias.
All other relvals tested (bot + local: run1 data, run2 data, noPU full sim, PU fullsim) are ok .


 
 runTheMatrix.py --what standard -l 4.17,4.4,4.41,4.23,4.24,4.25,4.26,4.27,4.28,4.5,4.6,4.76,4.77,4.78 --noCaf --command='-n 2' -i all -j 1 >& data.1.log &


  runTheMatrix.py --what pileup -l 25200,50202,25203,50203,25204,50204,25206,50206  -i all --noCaf --command='-n 1' -i all -j 1  >& PU.1.log &


  runTheMatrix.py --what standard -l 1.0,2.0,1301.0,1302.0,1303.0,1306.0,1308,1347,1348,1349,1350,1351,1352,1353,1354 -i all --noCaf --command='-n 3' -j 1 >& noPU.1.log &


  runTheMatrix.py --what standard -l 134.71,134.72,134.73,134.74,134.75,134.76,134.77 --command='-n 10' -j 2 >& data.run2.1.log  &

**Comment by davidlange6** [comment]
@franzoni - I think this is a cff problem that has come in to 75x/76x . I can debug later today.

**Comment by franzoni** [comment]
@davidlange6  great

**Comment by franzoni** [comment]
@boudoul this is what we're taking about

**Comment by davidlange6** [comment]
Hi @franzoni

 One AlCa is changing the configs of another

Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalPedestal_cff.py is changing modules without cloning them (thereby changing the behavior of other modules in the config).

hcalDigiAlCaMB.InputLabel = 'hltHcalCalibrationRaw'

Scheduled mode would crash the moment hcalDigiAlCaMB would get exercised in the application. In the nominal 100 event tests, it is not because of a filter in front of it. In unscheduled, it seems we trigger the problem sooner, likely because of something in the RECO output that I do not yet see (as the output products are the same in scheduled and unscheduled).

For the moment I will comment out the offending line so we can make progress and ask the alca experts to fix their configs (which I fear are too intermingled for me to unwind quickly).

David

**Comment by davidlange6** [comment]
this is superceded by #10476

**Pull request closed without merging**
