### PR TITLE
Code format fixes after CMSSW_11_0_X_2019-06-04-1100

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Trivial code format fixes based on the scrutiny of PRs integrated in CMSSW_11_0_X_2019-06-04-1100

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
hold

@slava77 this should address all your comments, I need an update after the integration of #27069

**Comment by slava77** [comment]
> @slava77 this should address all your comments, I need an update after the integration of #27069

@fabiocos 
Thank you.

It's good to see that so far we did not have more cases where one line gets split into more than 2 just because of the trailing endline comment.

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
unhold

@slava77 @perrotta @jfernan2 @andrius-k @ianna @cvuosalo @kpedro88 @alberto-sanchez @efeyazgan @qliphy these are minore fixes on top of the clang-format migration, where I formatted also some further updates. I would like to move forward with this soon unless you have compelling comments

**Comment by qliphy** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
the update is merely formal, addressing similar requests, I will take the previous signatures as valid (@perrotta @slava77 this should address one of your comments)

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
