### PR TITLE
Fix NanoGen with Rivet4

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Fixes https://github.com/cms-sw/cmssw/pull/44603#issuecomment-2210853524
- Need to convert HepMC2 -> GenParticles -> HepMC3

#### PR validation:

```
% runTheMatrix.py -l 546.0 --ibeos -t 4
...
1 1 tests passed, 0 0 failed
```

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test workflow 546.0,547.0,548.0

**Comment by hqucms** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
