### PR TITLE
Replace Geometry_cff with GeometryDB_cff in PhysicsTools

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, PhysicsTools configuration files 21 files are fixed.
```
        modified:   PhysicsTools/HepMCCandAlgos/test/testFlavorHistoryProducer.py
        modified:   PhysicsTools/PatAlgos/test/btag-from-packedPat.py
        modified:   PhysicsTools/PatAlgos/test/miniAOD/example_addJet.py
        modified:   PhysicsTools/PatAlgos/test/miniAOD/example_ei.py
        modified:   PhysicsTools/PatAlgos/test/miniAOD/example_jet_and_met.py
        modified:   PhysicsTools/PatAlgos/test/private/patLayer1_fromAOD-minimal.cfg.py
        modified:   PhysicsTools/PatAlgos/test/private/testPATUserDataExternal.py
        modified:   PhysicsTools/PatExamples/test/MuonAnalyzer_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatAnalysisTasks_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatBJetTags_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatBJetTracks_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatBJetVertex_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatBTag_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatElectron_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatTau_fromAOD_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatTau_fromPatTuple_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatTracks_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatTrigger_onTheFly_cfg.py
        modified:   PhysicsTools/PatExamples/test/analyzePatVertex_cfg.py
        modified:   PhysicsTools/TagAndProbe/test/Electron_TagProbeTreeProducer_cfg.py
        modified:   PhysicsTools/TagAndProbe/test/testTagProbeFitTreeProducer_JPsi.py
```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
+reconstruction

- technical PR
- no reco changes

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
