### PR TITLE
HLT menu development for `13_0_X` (2/N) [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2592](https://its.cern.ch/jira/browse/CMSHLT-2592): [TSG] removal of deprecated GRun Paths post Run2022 (combined table unchanged)
  - [CMSHLT-2593](https://its.cern.ch/jira/browse/CMSHLT-2593): [TSG] remove unused Paths from HLT combined menu (post Run2022)
  - [CMSHLT-2596](https://its.cern.ch/jira/browse/CMSHLT-2596): [TSG] split EGamma,JetMET,Muon datasets and streams by 2
  - [CMSHLT-2605](https://its.cern.ch/jira/browse/CMSHLT-2605): [GEM] extend RPCMON stream to GEM
  - [CMSHLT-2607](https://its.cern.ch/jira/browse/CMSHLT-2607): [PPS] extend list of CT-PPS FEDs
  - [CMSHLT-2613](https://its.cern.ch/jira/browse/CMSHLT-2613): [EGM] added two MC_Egamma_Open Paths (only to combined table)
  - [CMSHLT-2633](https://its.cern.ch/jira/browse/CMSHLT-2633): [EXO] update of displaced Photon+PFHT trigger and addition of backups

It also includes the migration of the HLT menus ("Fake*", frozen, and development ones) to the `ConfDB` template for `CMSSW_13_0_0_pre4`.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

The RelVals-INPUT error in #40791 is not a time-out. It's probably transient and unrelated to these HLT changes, but to be extra-safe the tests are restarted.

**Comment by missirol** [comment]
+hlt
 - changes in the outputs of PR tests are in line with updates to the HLT GRun menu, and the change in name of the frozen/fake HLT menus

**Comment by perrotta** [comment]
+1

**Pull request merged**
