### PR TITLE
Phase2-hgx239 Adding version 12 of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Adding the modified version of HGCal geometry in view of the changes in the Engineering Drawing of endcap region dated October, 2019. A new scenario will be created once other checks with simulation and reconstructions are tested. It also affects muon system (namely ME0 or GE0)

#### PR validation:

Doing the standard tests using runTheMatrix and also checked overlaps

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
