### PR TITLE
two liner to make AlignmentTrackSelectorModule multi-threaded friendly

### PR DESCRIPTION
**Pull request by davidlange6**
Picking up bug fix from Marco.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@davidlange6 thanks. I was unable yesterday to test the PromptProd due to DAS issues

**Comment by mmusich** [comment]
Added additional fixes in other selection modules affected.

**Comment by mmusich** [comment]
The StripGains PCL workflow has been tested (successfully) through:
```
cmsDriver.py step1 --conditions auto:com10 -s RAW2DIGI,L1Reco,RECO,ALCAPRODUCER:@allForExpress+SiStripCalMinBias+SiStripPCLHistos,DQM,ENDJOB --process RECO --data --eventcontent ALCARECO,DQM --scenario pp --datatier ALCARECO,DQM --customise Configuration/DataProcessing/RecoTLR.customiseExpress -n 100 --dasquery="file dataset = /MinimumBias/Run2012D-v1/RAW run=208307" --fileout file:step1.root --no_exec
cmsRun step1_RAW2DIGI_L1Reco_RECO_ALCAPRODUCER_DQM_ENDJOB.py
cmsDriver.py step2 --datatier ALCARECO --conditions auto:com10 -s ALCA:PromptCalibProdSiStripGains --eventcontent ALCARECO -n 100 --filein file:step1.root --no_exec
cmsRun step2_ALCA.py
cmsDriver.py step3 --data --conditions auto:com10 --scenario pp -s ALCAHARVEST:SiStripGains --filein file:PromptCalibProdSiStripGains.root -n -1

```

**Comment by diguida** [comment]
@cmsbuild please acknowledge changes

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
+1
for AlCa, provided jenkins agrees (modulo DAS issues ...)
Tested locally through:
`runTheMatrix.py -l limited -j 4`
yields:
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 11:41:58 2015-date Fri Jun 26 11:35:08 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 11:56:27 2015-date Fri Jun 26 11:35:11 2015; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Fri Jun 26 11:41:23 2015-date Fri Jun 26 11:35:13 2015; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 11:41:35 2015-date Fri Jun 26 11:35:14 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaEle+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 12:01:42 2015-date Fri Jun 26 11:41:28 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Fri Jun 26 11:54:49 2015-date Fri Jun 26 11:41:40 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Fri Jun 26 11:54:39 2015-date Fri Jun 26 11:42:02 2015; exit: 0 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 12:11:36 2015-date Fri Jun 26 11:54:43 2015; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jun 26 12:06:54 2015-date Fri Jun 26 11:54:55 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Jun 26 12:04:42 2015-date Fri Jun 26 11:56:28 2015; exit: 0 0 0 0
10 10 9 7 6 tests passed, 0 0 0 0 0 failed
```

**Comment by mmusich** [comment]
Changes are also FWD ported to 7.5.X (in #9909) and in 7.6.X (in #9910)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
