### PR TITLE
PPS: update of association cuts (backport of #27440)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This is a backport of #27440.

As shown below, identical results are obtained with this PR and the original one:
make_cmp png-000001

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #27440

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical backport of #27440
 - This will update proton reconstruction for all 2016, 2017 and 2018: if it will be merged in the UL release after the re-reco of 2017 data/MC, then some protection that prevents modifying 2017 samples should be probably added (@fabiocos)
- Small changes with respect to the previous common default are shown in the PR description : jenkins tests pass and show no other differences besides the low-stat reflection of those changes.

**Comment by slava77** [comment]
>     * if it will be merged in the UL release after the re-reco of 2017 data/MC, then some protection that prevents modifying 2017 samples should be probably added (@fabiocos)

this apparently violates the no-change policy and should not have been signed.

**Comment by fabiocos** [comment]
@franzoni @srimanob the question related to this PR is whether the pilot of 2017 production has been already submitted already. PPS is to some extent unrelated to all the rest, but of course we cannot change behaviour during a production. So with @slava77 and @perrotta we would like to understand whether changes for this bit special part can still be considered at this point, or for 2017 the code needs to be reverted to the previous behaviour.

**Comment by srimanob** [comment]
Following up with @jan-kaspar on https://indico.cern.ch/event/832270/contributions/3487106/attachments/1872773/3082425/jan_kaspar_pps.pdf

It's not clear to me the lost with the original cut, the reference in the above slide can't be seen.  Can this be somehow mitigated at the analysis level?

**Comment by franzoni** [comment]
hello @fabiocos 

> changes for this bit special part can still be considered at this point, or for 2017 the code needs to > be reverted to the previous behaviour.

as Phat said, we  need help from Jan and Valentia to understand wether this PR is a "desirable better" or a "must be feature without which PPS reco makes no sense" for 2017. 

It makes sense that RECO sequence for 2017 bears the same performance in 11_0 as it does in 10_6 (which is the legacy release for run-2)

**Comment by fabferro** [comment]
@franzoni : ciao Giovanni. As Valentina just replied by email, these changes are not strictly needed for 2017 but are very desirable for 2018. The effect for 2018 data is remarkable while for 2017 is just minimal.

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
my summary of the discussion of @franzoni and @srimanob with PPS experts is that for 2017 the situation is frozen, and PPS experts seem to confirm that the proposed update is not mandatory. Therefore it is necessary to update this PR so as to let 2017 unchanged. For consistency we should likely update the master version (in any case 2017 data will be analyzed using the UL release). The optimised settings might possibly stay available, be not be applied in production, i.e. ```ctpps_2017.toModify(ctppsProtons, apply2017Settings)``` is not present.

**Comment by perrotta** [comment]
> my summary of the discussion of @franzoni and @srimanob with PPS experts is that for 2017 the situation is frozen, and PPS experts seem to confirm that the proposed update is not mandatory. Therefore it is necessary to update this PR so as to let 2017 unchanged. For consistency we should likely update the master version (in any case 2017 data will be analyzed using the UL release). The optimised settings might possibly stay available, be not be applied in production, i.e. `ctpps_2017.toModify(ctppsProtons, apply2017Settings)` is not present.

To reproduce the old behaviour, one should also keep removing the 2016 ("new default") settings for 2017; and adapt the 2018 to include the full set of parameters (because now it is modifying the "new" default, which is what setup by ctpps_2016)

**Comment by fabferro** [comment]
@perrotta @slava77 @fabiocos : please let us know what action you want us to take. The situation is already a bit "messy" and I don't want to introduce more "entropy" starting modifying things...

**Comment by perrotta** [comment]
@fabferro , my personal suggestion would be to maintain the PR as it is now, even if it only allow some moderate improvement with respect to the current setting, because the 2017 re-reco production did not start yet and proton reconstruction lives on its own and doesn't propagate to anything else.

HOWEVER, the decision taken by PPD conveners and @fabiocos and stated in https://github.com/cms-sw/cmssw/pull/27475#issuecomment-511456582 requires to revert the settings to the old ones for 2017, and they ask to do so also for the master version of this PR. If such a decision is confirmed, please do so.

**Comment by slava77** [comment]
On 7/16/19 2:05 AM, perrotta wrote:
> and they ask to do so also for the master version of this PR.

Why is this needed in master?
Is it to generate a commit that makes a change and then another one that
reverts it back?

**Comment by perrotta** [comment]
@fabferro @jan-kaspar @fabiocos : what was the final decision taken about this backport PR? Should the 2017 config reported to the old one. I fear that if we still delay taking actions here we risk missing also the windows for the re-reco of 2018 data...

**Comment by fabferro** [comment]
> 
> 
> @fabferro @jan-kaspar @fabiocos : what was the final decision taken about this backport PR? Should the 2017 config reported to the old one. I fear that if we still delay taking actions here we risk missing also the windows for the re-reco of 2018 data...

@perrotta @fabiocos : for PPS it's important to have these new cuts for 2018 while it was almost negligible for 2017. I'm still waiting for your decision!

**Comment by perrotta** [comment]
@fabferro , by reading what posted in this github thread I think a decision was already taken one week ago, see https://github.com/cms-sw/cmssw/pull/27475#issuecomment-511456582

Please, either modify this PR by letting 2017 at its previous default, or report here about any possible different decision taken since then (and act accordingly)

**Comment by fabferro** [comment]
@perrotta : it did not seem to me that there was consensus about what to do, therefore I waited. Anyway, I now have modified the code in order to leave 2017 settings unchanged but applying the changes for 2016 and 2018. If it's ok I can then open a PR to revert also the master, if you think it's the correct policy.

**Comment by perrotta** [comment]
> @perrotta : it did not seem to me that there was consensus about what to do, therefore I waited. Anyway, I now have modified the code in order to leave 2017 settings unchanged but applying the changes for 2016 and 2018. If it's ok I can then open a PR to revert also the master, if you think it's the correct policy.

Thank you @fabferro 
I was not at the last ORP, but I was told that it was agreed there that we don't need to modify the settings in the master (something that I also agree with): therefore, please let unchanged the PR in the master, for now.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Since the previous reco signature in https://github.com/cms-sw/cmssw/pull/27475#issuecomment-510382459, now only proton recon configurations for 2016 and 2018 are modified with respect the previous default config: 2017 one remains unchanged

**Comment by fabferro** [comment]
Shall we un-hold this?

**Comment by fabiocos** [comment]
@fabferro @perrotta @jan-kaspar indeed at the last ORP it was decided to leave 2017 unchanged in 10_6_X, while the update will stay in master, and get it active for 2018.

**Comment by perrotta** [comment]
> @fabferro @perrotta @jan-kaspar indeed at the last ORP it was decided to leave 2017 unchanged in 10_6_X, while the update will stay in master, and get it active for 2018.

Thank you for the confirmation @fabiocos : this is exactly what this "not identical" backport PR is implementing now.

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+operations

the update of Eras is coherent with the purpose of the PR as in master, the 2017 specific update is meant to keep the scenario unchanged

**Comment by fabiocos** [comment]
+1

**Comment by fabferro** [comment]
@fabiocos : can you confirm that this PR will be released and used for 2018 UL rereco? Thanks

**Comment by fabiocos** [comment]
@fabferro this PR has been merged for next 10_6_X versions to be used for 2018 and 2016. Apparently even 2017 should be restarted, so there is a chance to get the best values even for 2017, see #27709

**Pull request merged**
