### PR TITLE
fixing memory leak in EgammaHLTNxNClusterProducer :74X 

### PR DESCRIPTION
**Pull request by Sam-Harper**
This is the 74X flavour of #10530

This pull request fixes a memory leak in EgammaHLTNxNClusterProducer and is considered by the TSG an absolutely urgent and necessary fix for 25ns data taking.

### CODE REVIEW

**Comment by lgray** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
