### PR TITLE
Update of the HLT menu (101X)

### PR DESCRIPTION
**Pull request by silviodonato**
Update of the HLT menu to /dev/CMSSW_10_0_0/HLT/V140
based on L1Menu_Collisions2018_v0_0_1.

(base release: CMSSW_10_1_0_pre3)

100X: #22562

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
Of course it is failing because of the new L1 menu:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22561/26749/runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018.log

We'll contact AlCa to prepare a GT with the new L1 menu

**Comment by Martin-Grunewald** [comment]
We should be sure this is the "final" L1T menu.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
This  HLT menu is compatible with both L1Menu_Collisions2017_v4 and L1Menu_Collisions2018_v0_0_0_xml, and so it should pass the tests.
This should also make life simple updating the L1 menu in GT.
I keep "hold" because this PR will be updated soon to include other JIRA tickets and the migration to 10_0_4.

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_10_0_4.

**Comment by silviodonato** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
