### PR TITLE
HLT update for 25ns (76X) plus new GT

### PR DESCRIPTION
**Pull request by diguida**
#10531 plus #10790

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@diguida 
There is a problem with these GTs for FastSim, please see the thread here:

https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3249/1.html

**Comment by mmusich** [comment]
@Martin-Grunewald  see please the thread here https://github.com/cms-sw/cmssw/pull/10353

**Comment by Martin-Grunewald** [comment]
@mmusich 
Hmm well, the error message for FamosProducer is however different...

**Comment by mmusich** [comment]
```
135.4 step1

runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

----- Begin Fatal Exception 12-Aug-2015 17:26:03 CEST-----------------------

An exception of category 'DDException' occurred while

   [0] Processing run: 1

   [1] Running path 'simulation_step'

   [2] Calling beginRun for module FamosProducer/'famosSimHits'

Exception Message:

DDVectorGetter: vectors are empty, cannot get array phioff

----- End Fatal Exception -------------------------------------------------
```
looks the same to me

**Comment by Martin-Grunewald** [comment]
@mmusich 
My problem is, in addition to the jenkins errors above, also this one:
```
> %MSG
> %MSG-e HFShower:  FamosProducer:famosSimHits@streamBeginRun  14-Aug-2015 07:26:3\
> 7 CEST Run: 1
> HFShowerLibrary : cannot get array rTable
> %MSG
> ----- Begin Fatal Exception 14-Aug-2015 07:26:37 CEST-----------------------
> An exception of category 'Unknown' occurred while
>    [0] Processing run: 1
>    [1] Running path 'simulation_step'
>    [2] Calling beginRun for module FamosProducer/'famosSimHits'
> Exception Message:
> HFShowerLibrary cannot get array rTable
> ----- End Fatal Exception -------------------------------------------------
> 
> in a cmsDriver generated workflow:
```
see here: https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3249/1.html

**Comment by diguida** [comment]
@Martin-Grunewald @mmusich your error in https://github.com/cms-sw/cmssw/pull/10753#issuecomment-131010746 is reproduced in e.g. https://github.com/cms-sw/cmssw/pull/10753#issuecomment-130808090

**Comment by mmusich** [comment]
actually I meant  https://github.com/cms-sw/cmssw/pull/10353#issuecomment-130342729 wfs: 5.1 and 135.4

**Comment by diguida** [comment]
@mmusich right, that one too...
Mh, as explained you on chat, I am sure there is an inconsistency in detector description. At this point, better to separate the concerns. Let's make HLT go in with a minimal GT, geometry needs more understanding.

**Comment by diguida** [comment]
@cmsbuild please notice the change

**Comment by diguida** [comment]
@Martin-Grunewald this is #10531 with:

1. rebase to latest IB
1. removed https://github.com/cms-tsg-storm/cmssw/commit/698c4573a2a7d07ce896fc66db28a26445b42829
1. cherry-picked https://github.com/diguida/cmssw/commit/eb570c2a716bbe0b845b0d16d0eff01ea4da89c9

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
the failure of the test seems unrelated.

**Comment by diguida** [comment]
OTOH, baseline tests look ok:
[1330.0 step3](http://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-08-14-1100/pyRelValMatrixLogs/run/1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15/step3_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15.log)
[50202.0 step3](http://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-08-14-1100/pyRelValMatrixLogs/run/50202.0_TTbar_13+TTbar_13INPUT+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/step3_TTbar_13+TTbar_13INPUT+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50.log)
[25202.0 step3](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-08-14-1100/pyRelValMatrixLogs/run/25202.0_TTbar_13+TTbar_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_TTbar_13+TTbar_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log)

**Comment by Martin-Grunewald** [comment]
@diguida 
Please close this PR, and sign #10531 and #10534 instead.
Thanks!

**Pull request closed without merging**
