### PR TITLE
[14.0.X] re-organize workflows exercising the `SiPixelHGCombined` workflow

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43810

#### PR description:

Better usage of relval resources: exercise the new `PromptCalibProdSiPixelAliHGComb` workflow introduced at https://github.com/cms-sw/cmssw/pull/43721 only on di-muon resonant data in the newly added workflow 1001.4 , while it is removed on the existing ones 1001.2 and 1001.3 which run over ZeroBias and SingleMuon data.

#### PR validation:

`runTheMatrix.py -l 1001.2,1001.3,1001.4 -t 4 -j 8 --ibeos` runs

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/43810 to CMSSW_14_0_X (data-taking release of 2024).

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1001.2, 1001.3, 1001.4

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 any objections for this backport? Would make testing in the datataking release a tad easier.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
@cms-sw/orp-l2 can you consider this for the next patch release?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
