### PR TITLE
Hotline DQM module for 74X

### PR DESCRIPTION
**Pull request by duanders**
Backport of https://github.com/cms-sw/cmssw/pull/9141 to 74X for the Hotline trigger DQM.

https://its.cern.ch/jira/browse/CMSHLT-312

### CODE REVIEW

**Comment by deguio** [comment]
-1
please see comments at
https://github.com/cms-sw/cmssw/pull/9141
thanks,
F.

**Comment by duanders** [comment]
Updated this PR to incorporate the changes in https://github.com/cms-sw/cmssw/pull/9141

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
