### PR TITLE
Put LCT related enums in CSCConstants

### PR DESCRIPTION
**Pull request by dildick**
Enums `MAX_CLCT_BINS`, `MAX_ALCT_BINS` and `MAX_LCT_BINS` were defined in 3 different places. This PR puts all three in the common class `CSCConstants`. 

Additional enums were created in `CSCConstants`: 
* `MAX_CFEBS`
* `NUM_DISTRIPS_PER_CFEB`, `NUM_STRIPS_PER_CFEB`, `NUM_HALF_STRIPS_PER_CFEB`
* `NUM_PATTERN_WIRES`, `NUM_PATTERN_STRIPS`, `NUM_PATTERN_HALFSTRIPS`
* `MAX_CLCTS_PER_PROCESSOR`, `MAX_ALCTS_PER_PROCESSOR`
* `MAX_HALF_STRIP_ME1A_GANGED`, `MAX_HALF_STRIP_ME1A_UNGANGED`, `MAX_HALF_STRIP_ME1B`
* `CLCT_FPGA_LATENCY`, `ALCT_FPGA_LATENCY`
* `MAX_NUM_WIRES_ME11`.

EDIT:

<PRE>
MAX_CLCT_BINS -> MAX_CLCT_TBINS
MAX_ALCT_BINS -> MAX_ALCT_TBINS
MAX_LCT_BINS -> MAX_LCT_TBINS
NUM_PATTERN_WIRES -> MAX_WIRES_IN_PATTERN
NUM_PATTERN_STRIPS -> MAX_STRIPS_IN_PATTERN
NUM_PATTERN_HALFSTRIPS -> MAX_HALFSTRIPS_IN_PATTERN
MAX_NUM_WIRES_ME11 -> MAX_WIRES_ME11
_LATENCY -> _EMUL_TIME_OFFSET
</PRE>

This PR is part of an effort to document the "magic" numbers in the CSC local trigger. There should be no change in performance.

@tahuang1991

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
Additional enums were either transferred from the ALCT/CLCT processor to CSCConstants, or defined for the first time. This is to make the CSC local trigger code more transparent.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
I have no more additions for this PR.

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
Please wait with the integration of this PR. Some CSC folks would like to change some enum names.

**Comment by dildick** [comment]
I implemented following changes after feedback from UCLA folks
<PRE>
MAX_CLCT_BINS -> MAX_CLCT_TBINS
MAX_ALCT_BINS -> MAX_ALCT_TBINS
MAX_LCT_BINS -> MAX_LCT_TBINS
NUM_PATTERN_WIRES -> MAX_WIRES_IN_PATTERN
NUM_PATTERN_STRIPS -> MAX_STRIPS_IN_PATTERN
NUM_PATTERN_HALFSTRIPS -> MAX_HALFSTRIPS_IN_PATTERN
MAX_NUM_WIRES_ME11 -> MAX_WIRES_ME11
_LATENCY -> _EMUL_TIME_OFFSET
</PRE>

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
@rekovic could you please sign?

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
