### PR TITLE
Run3-hcx257 Update material budget studies for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update material budget studies for HCAL

#### PR validation:

Tested with the cfg's in the test area of the package

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
