### PR TITLE
Use strtok_r in testUCTUnpacker.cpp

### PR DESCRIPTION
**Pull request by Dr15Jones**
Replace the thread-hostile strtok with strtok_r.
[This is a standalone executable but still best not to leave any
bad examples.]

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic could you please check and sign?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
