### PR TITLE
L1TStage2uGT Update: Algorithm bit vs global BX fix

### PR DESCRIPTION
**Pull request by mzarucki**
Fix for algorithm bit vs global BX number plot

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by vanbesien** [comment]
please close (replaced by #14634)

**Comment by perrotta** [comment]
What about 81X version (#14624)?

**Comment by vanbesien** [comment]
@perrotta : #14624 (81X) is just fine. #14625 (80X) was just replaced by a rebased #14634 (80X) so that it could be merged in the online DQM.

**Pull request closed without merging**
