### PR TITLE
Turnon L1T TrackTrigger, TrackMatch, PF, update TestOldDigiWorkflow, add objects in FEVTDEBUG (11_1_X backport)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR solves the conflict between #30520 #30519 #30517.
This backports to 11_1_X:
- Update of TestOldDigi workflow (#30484)
- Add Phase2 L1T objects to FEVTDEBUG EventContent (#30498)
- Turn on L1 track trigger in Phase2C8 and later (#30479)
- Turn on the ParticleFlow and TrackMatch (#30482, #30363)

Require the L1T PF package #30523

### CODE REVIEW

**Comment by silviodonato** [comment]
please test with  #30523

**Comment by silviodonato** [comment]
please test with #30523

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test with #30523, #30511

**Comment by silviodonato** [comment]
please test with  #30523

**Comment by silviodonato** [comment]
merge

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1
For the records

**Comment by chayanit** [comment]
+1

**Pull request merged**
