### PR TITLE
Initialize array to prevent warning

### PR DESCRIPTION
**Pull request by mrodozov**
Fix for this comp warnings https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc700/CMSSW_10_1_X_2018-02-27-1100/FWCore/Integration

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
This is a bit slow, but should not matter

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
