### PR TITLE
updates for electrons stream

### PR DESCRIPTION
**Pull request by rgerosa**
Update of electron stream code :
1) work with electrons selected from more than one HLT path
2) dump more than one electron for each event in order to commission it also with Zee events

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by perrotta** [comment]
Please provide also a backport to 74X if you even want it used in the HLT for 2015 data taking

**Comment by mmusich** [comment]
@perrotta, this was adressed first in 7.4.X through #9111. We asked to move to 7.5.X and after this is merge re-open the backport

**Comment by perrotta** [comment]
Ah, ok, thank you @mmusich 
It wouldn't be bad if companion pull requests are always linked as reference in the comment fields, in order to ease bookkeeping and evaluation: well, now the link to the 74X counterpart of this PR is there :-)

**Comment by rgerosa** [comment]
What is the status of the this PR? we would like to have a fast back port to 74X

**Comment by diguida** [comment]
@rgerosa I am looking into it. Busy days now...

**Comment by diguida** [comment]
-1
superseded by #9256

**Comment by diguida** [comment]
@rgerosa your commit has been merged into #9256 
The changes you did are fine for us, but, as reported in https://github.com/cms-sw/cmssw/pull/5772#issuecomment-62876733 there are still some optimisations to be done. I will point you to the code sections where the changes should be made.

**Pull request closed without merging**
