### PR TITLE
HcalDQM: Add Hcal to DQM FED report summary map

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:
Adding a new class `HcalFEDIntegrityTask` to enable HCAL to be included into the DQM FED report summary map. 
fedFatal histogram contains feds that: 1, are listed as problematic from the HcalUnpackerReport; 2, have severe mismatches in event info comparing to uHTR data, same as the `RawTask` summary map.

#### PR validation:

Testes and verified with actual data from recent Run#352567 using `cmsRun fed_dqm_sourceclient-live_cfg.py inputFiles=xxx`

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
@lwang046 are you preparing a backport of this?

**Comment by perrotta** [comment]
+1

**Comment by lwang046** [comment]
> @lwang046 are you preparing a backport of this?

Okay I'll prepare a back port for use at p5.

**Comment by qliphy** [comment]
@lwang046  Please also back port it to 12_4_X.

**Pull request merged**
