### PR TITLE
Backport GEM offline DQM update to CMSSW_11_3_X for MWGR#4

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport #33773 to CMSSW_11_3_X for MWGR#4.

@jshlee, @szaleski

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
@seungjin-yang I wonder why some chamber efficiency plots now (left) lose their entries w.r.t.  baseline (right):
https://tinyurl.com/yhumqvjr
Thanks

**Comment by seungjin-yang** [comment]
> @seungjin-yang I wonder why some chamber efficiency plots now (left) lose their entries w.r.t. baseline (right):
> https://tinyurl.com/yhumqvjr
> Thanks

The definition of the GE11 surface, on which the muon propagates, was updated. The GE11 consists of two different types of chambers, whose global z locations are also different. The previous analyzer used the mean z position as the plane into propagate. The updated version use distinguishes between two types of chambers.
Cheers

**Comment by jfernan2** [comment]
+1
Tested succesfully in Online DQM at P5

**Comment by qliphy** [comment]
+1

**Pull request merged**
