### PR TITLE
[do not merge] Squash all Patatrack developments on top of CMSSW_10_6_X

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR contains all the development from he CMSSW_10_6_X_Patatrack branch, squashed as a single commit.

It is intended only for review, testing and for collecting comments. The actual merge will be done with a series of smaller PRs.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
@smuzaffar the GPU workflows we should test are 10824.5 (reference), 10824.51, 10824.52, 10824.53

**Comment by fwyzard** [comment]
@makortel can you check this ?

**Comment by makortel** [comment]
@fwyzard It is caused by #26138 that was merged in for 10_6_0_pre3.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Thanks for the fix. I will keep it as a separate commit for the time being, and squash once the Patatrack "master" moves to CMSSW_10_6_0_pre3 or later.

**Pull request closed without merging**
