### PR TITLE
[ALCA-RECONSTRUCTION] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
- Convert unit tests to use `<test ...command="cmd"/>` instead of using `FW unit tests driver`
- Make sure that test can run from its dedicated test directory.

### CODE REVIEW

**Comment by tvami** [comment]
+1

Screen Shot 2023-03-23 at 10 37 16

**Comment by perrotta** [comment]
+1
- Just to relieve the reviewers from the review of such technical and all-identical PRs, let have them merged even bypassing the missing signatures

**Comment by perrotta** [comment]
merge

**Comment by jfernan2** [comment]
+1 (for the records)

**Pull request merged**
