### PR TITLE
Run3-gex48 Remove elementary materials from PPS material file

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove elementary materials from PPS material file

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Thanks for fixing this.

**Comment by cvuosalo** [comment]
Comparison differences due to generation of different events between reference and PR because of the XML change. There are no significant differences.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
urgent

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
