### PR TITLE
backport from 93X to 71X - for neutral non-detectable exotic  - send their daughters to Geant4

### PR DESCRIPTION
**Pull request by zhangzc11**
PR in 93X: https://github.com/cms-sw/cmssw/pull/20083

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by zhangzc11** [comment]
@davidlange6 could you please approve this backport to 71X? we need this for 2016 MC production.

**Comment by zhangzc11** [comment]
@davidlange6 Dear David, could you please approve this backport  PR asap? Thanks a lot!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
