### PR TITLE
Change VtxSmearing for pPb to fix a failing IB test

### PR DESCRIPTION
**Pull request by kkrajczar**
Workflow 280.0 is failing in the IB tests both in 74X and in 75X with the error "KeyError: 'Realistic8TeVCollisionPPbBoost'". Indeed, Realistic8TeVCollisionPPbBoost is no longer defined in https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/Configuration/StandardSequences/python/VtxSmeared.py. After discussing the issue with @yetkinyilmaz we understand that the vtx smearing should be changed to Realistic5TeVPPbBoost; which is the purpose of this PR.

The proposed change was tested to fix workflow 280.0.

@BetterWang, @yetkinyilmaz, @mandrenguyen

### CODE REVIEW

**Comment by kkrajczar** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
hello @kkrajcza, 
The workflow 280 runs the proton-proton DIGI and RECO, which was a deliberate choice;
is the reco beamspot provided by the GT auto:run1_mc consistent with the SIM beamspot Realistic5TeVPPbBoost ?
Cheers. G.

**Comment by mandrenguyen** [comment]
Hi Giovanni,

Good catch, the answer is no.
This is a pPb workflow and pPb beam conditions are not currently being 
maintained in 74X.
We probably want to maintain this workflow, as we will eventually have 
pPb collisions again, and reprocessing of the 2013 data is possible 
(although not currently scheduled).
Maintaining the corresponding pPb GTs in 74X  is probably not essential 
though, given the other priorities at the moment for all involved.

A stop-gap solution would be to simply use the pp beamspot corresponding 
to run1_mc.
This means that we would be running unboosted pPb, which is not what we 
record, but would at least maintain the technical viability of running 
the workflow (although not the boost tool).
Another solution would be to add a customize fragment to switch the 
beamspot.
Maybe you have a better suggestion.

Cheers,
Matt



On 3/3/15 11:18 AM, Giovanni Franzoni wrote:
>
> hello @kkrajcza,
> The workflow 280 runs the proton-proton DIGI and RECO, which was a 
> deliberate choice;
> is the reco beamspot provided by the GT auto:run1_mc consistent with 
> the SIM beamspot Realistic5TeVPPbBoost ?
> Cheers. G.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7927#issuecomment-76920093>.
>


-- 
-----------------------
Matthew Nguyen
Chargé de Recherche
LLR-Ecole Polytechnique
91128 Palaiseau FRANCE
+33 1 69 33 55 65
-----------------------

**Comment by franzoni** [comment]
hello @mandrenguyen,
the complete solution is measuring the RECO BS consistent with Realistic5TeVPPbBoost, deploy it in a GT and have the consistent pA scenario in place.
The solution you suggest (revert to pp) is a lesser-work-for-lesser-benefit solution.
I think you as HIN convenor are best placed to choose what is best doing now.
cheers, g.

**Comment by mandrenguyen** [comment]
@franzoni 
Given that we and the alcaDB folks are quite busy now, I propose to switch to --beamspot Realistic8TeVCollision, which at least gives a self-consistent workflow, even if it's lacking the boost.
We can request a proper pPb GT when pPb (re)processing becomes relevant again.  Since it's vanilla pp reco being run anyway, I'm not sure anyone will seriously scrutinize this workflow until that point anyway. 
If you agree we can PR that.

**Comment by davidlange6** [comment]
could we move forward with this PR ? Would be nice to reduce the failing HI workflows in the IBs by one....

**Comment by franzoni** [comment]
@mandrenguyen
sounds reasonable.

**Comment by mandrenguyen** [comment]
@kkrajcza
Please update the PR to use the 8 TeV (i.e., no boost) vertex smearing and until we have for proper pPb global tags and workflows.

**Comment by kkrajczar** [comment]
HI all,

VtxSmearing was changed to Realistic8TeVCollision as suggested Matt.

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
(such that the "failed checks" should go away)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
