### PR TITLE
use dedicated calibrations at HLT

### PR DESCRIPTION
**Pull request by fwyzard**
- modify the GenericMVAJetTagComputers adding a label to choose calibrations
- customise the CombinedSecondaryVertexESProducer to read b-tagging calibrations with the "HLT" label
- customise the PFProducer to read the PF calibrations with the "HLT" label

### CODE REVIEW

**Comment by fwyzard** [comment]
This pull request updates #12044 and #12062 to actually pick up the calibrations with the "HLT" label

**Comment by slava77** [comment]
can this be added to #12062 instead?
otherwise, #12062 should be closed

**Comment by slava77** [comment]
@fwyzard 
Andrea, since you are still updating this PR, please trigger tests when you are done.

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@slava77 , my preliminary tests pass, I think you can double check that I didn't break anything.

**Comment by mmusich** [comment]
@pvmulder @diguida

**Comment by fwyzard** [comment]
FYI, as of eb202c2cf4fa6a637a39d85d810e77f913355a95 , `runTheMatrix.py -l limited -j 8` passes all tests:
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Oct 26 18:17:46 2015-date Mon Oct 26 18:14:32 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Oct 26 18:26:22 2015-date Mon Oct 26 18:14:34 2015; exit: 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Mon Oct 26 18:17:29 2015-date Mon Oct 26 18:14:36 2015; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Oct 26 18:17:53 2015-date Mon Oct 26 18:14:41 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Oct 26 18:25:56 2015-date Mon Oct 26 18:14:43 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Mon Oct 26 18:21:32 2015-date Mon Oct 26 18:14:47 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Mon Oct 26 18:21:36 2015-date Mon Oct 26 18:14:52 2015; exit: 0 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Oct 26 18:25:12 2015-date Mon Oct 26 18:14:53 2015; exit: 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Oct 26 18:24:43 2015-date Mon Oct 26 18:17:34 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED  - time date Mon Oct 26 18:24:19 2015-date Mon Oct 26 18:17:55 2015; exit: 0 0 0 0 0 0 0
10 10 9 7 5 1 1 tests passed, 0 0 0 0 0 0 0 failed
```

**Comment by pvmulder** [comment]
@mmusich @fwyzard I don't see any obvious mistakes or files that were forgotten, thanks!

**Comment by fwyzard** [comment]
@mmusich @diguida @franzoni 
looks like we need an update to the global tag for offline processing of Run II data:  76X_dataRun2_v9 does not have the online PFCalibrations with the HLT label.

**Comment by mmusich** [comment]
@fwyzard I am confused by the procedure. We can for sure add the label "HLT" in the RECO Global tags (the ones `76X_dataRun2_v*`), but wouldn't make more sense to make the step:
`-s HLT:50nsGRun` consume the HLT conditions through the HLT GT (`76X_dataRun2_HLT_v*`) and the following steps the RECO GT?

**Comment by fwyzard** [comment]
Hi Marco,
the failures come from jobs that are running both the HLT and RECO steps in
a single job - as far as I know we cannot use different conditions in
different steps (yet?).

Ciao,
.Andrea

**Comment by mmusich** [comment]
@fwyzard that's my understanding too. The question is indeed why the job cannot be split into two cmsDriver commands. As it is now, the job doesn't probe conditions meant for HLT at all. @franzoni

**Comment by diguida** [comment]
@fwyzard just for my understanding: can the addOn tests run in 2 steps, as the "vanilla" RelVal? See e.g.

````
134.801 RunHLTPhy2015C+HLTDR225ns+RECODR225nsreHLT+HARVESTDR225nsreHLT [1]: input from: /HLTPhysics/Run2015C-v1/RAW with run []
                                           [2]: cmsDriver.py step2  --datatier FEVTDEBUGHLT --conditions auto:run2_hlt_25ns14e33_v4 -s L1REPACK:GT2,HLT:@relval25ns --process reHLT --data  --era Run2_25ns --eventcontent FEVTDEBUGHLT -n 100
                                           [3]: cmsDriver.py step3  --conditions auto:run2_data_25ns14e33_v4 -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias,DQM:@standardDQM+@miniAODDQM --runUnscheduled  --process reRECO --data  --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp --datatier RECO,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customiseDataRun2Common_25ns -n 100
                                           [4]: cmsDriver.py step4  --data  --filetype DQM --conditions auto:run2_data_25ns14e33_v4 -s HARVESTING:@standardDQM+@miniAODDQM --scenario pp -n 100
````

Can the steps be split in two jobs, the former running HLT with its corresponding GT, the latter running digitisation and reconstruction, as Tier0?

**Comment by Martin-Grunewald** [comment]
These tests are there to actually TEST HLT+RECO!

**Comment by mmusich** [comment]
@Martin-Grunewald agreed, but my naive understanding is that if the HLT conditions come from the RECO GT, the procedure is not really testing what is supposed to be testing (or is it?)

**Comment by diguida** [comment]
@Martin-Grunewald thanks for the clarification.
Then my next question is: is it fine for HLT to consume conditions for RECO? We know at least few cases where this does not hold.
Unless you want only to have the possibility to run HLT and RECO together, not caring too much about conditions...

**Comment by Martin-Grunewald** [comment]
The idea was to eventually reach a consistent HLT+RECO (consistent with RECO alone and HLT alone). For this as a first milestone, HLT+RECO has to work (technically) in the same cmsRun step (which we achieved some time ago), and the tests are there to maintain that feature. Then would come as a next milestone the picking of the correct conditions HLT vs RECO.

**Comment by fwyzard** [comment]
Hi Salvatore,
conditions (and EventSetup in general) is indeed the main reason why
running HLT and RECO in the same step is not supported (which means: it
runs but you are not guaranteed to get the right results).
Separating out the HLT specific tags with a different label goes in the
right direction.
Using subprocesses could also help here, in the CMSSW 8.x time scale.

Ciao,
.Andrea

**Comment by diguida** [comment]
@fwyzard we have prepared a new set of data GT:
76X_dataRun1_v10:
As 76X_dataRun1_v9 with the following changes:
- added a label for PF hadron calibration specific for HLT usage.

76X_dataRun2_v10:
As 76X_dataRun2_v9 with the following changes:
- added a label for PF hadron calibration specific for HLT usage

**Comment by mmusich** [comment]
@fwyzard @Martin-Grunewald we've cut the new data (run1 and run2) GT with the desired label:
Please cherry-pick from here:  #12109.
Though we are bit concerned the way all the procedure is handled. Can we organize to touch base about it (even offline?). I will start a thread on this.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
assuming it will pick up #12109 now that it has been merged

**Comment by fwyzard** [comment]
ah, it will not, because #12109 is for 8.0.x :-(

**Comment by fwyzard** [comment]
Anyway, I confirm that after cherry-picking the commit from #12109 all add on tests pass:
```
 34 tests passed, 0 failed 
```

**Comment by mmusich** [comment]
@fwyzard you can cherry-pick the commit form #12114 (for 76X). I have no problem to sign the changes here :)

**Comment by fwyzard** [comment]
Cherry-picked ...

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by diguida** [comment]
+1
Same changes as #121114
The new label is now consumed by HLT in the addOn tests

**Comment by diguida** [comment]
@fwyzard in #12114 we have added the new MC GT.
If you want the latest state of the art, please cherry pick https://github.com/mmusich/cmssw/commit/bee66c2e63f42f434e9cd95740d37c49a7e6ffef

**Comment by slava77** [comment]
@cmsbuild please test
maybe no timeout this time

**Comment by davidlange6** [comment]
cmsbuild, please test
trying again..

**Comment by slava77** [comment]
@cmsbuild please test
maybe this works

**Comment by fwyzard** [comment]
@davidlange6 just let me know if I should rebase this on top of CMSSW_7_6_X and/or update it to #12114 .

**Comment by slava77** [comment]
(tests restarted manually from jenkins interface)

**Comment by davidlange6** [comment]
which they already had been… lets see if something is successful...

**Comment by slava77** [comment]
indeed, I see https://cmssdt.cern.ch/jenkins/job/ib-any-integration/9261 was started from ib-any-integration task by Alessandro and looks like it will finish soon.
I usually submit from ib-schedule-pr-tests

**Comment by davidlange6** [comment]
no effect on reco quantities - (minimal changes to hlt histograms)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12100	 cb1273c
confirming the diffs are in HLT only

**Pull request merged**
