### PR TITLE
New l1 track trigger stub window tune

### PR DESCRIPTION
**Pull request by rgoldouz**
I have performed various studies related to the stub rate and stub reconstruction efficiencies. As a results I have made a new stub window tune. All details are documented in the following detector note (CMS DN-2020/005 -- The L1 Track Trigger Upgrade: Properties, Efficiencies, and Rates for Track Stubs)
the only updated file is the following: L1Trigger/TrackTrigger/python/TTStubAlgorithmRegister_cfi.py

### CODE REVIEW

**Comment by aloeliger** [comment]
@artlbv & @mcepeda Do you need to be informed on this one for physics changes?

**Comment by aloeliger** [comment]
please test

**Comment by artlbv** [comment]
> @artlbv & @mcepeda Do you need to be informed on this one for physics changes?

thanks for referencing us! If I understand correctly, this change affects all the objects relying on the TrackTrigger?
Thus it is actually more general than menu only, and e.g. @EmyrClement @cerminar @folguera as object contacts need to be aware? @mcepeda what is the procedure for validating these changes from the DPG side?

I looked at the DN and I see it contains some measurements for "Electrons" and "Muons", though I am not sure which exact objects were used. @rgoldouz could you clarify?

**Comment by rgoldouz** [comment]
> > @artlbv & @mcepeda Do you need to be informed on this one for physics changes?
> 
> thanks for referencing us! If I understand correctly, this change affects all the objects relying on the TrackTrigger? Thus it is actually more general than menu only, and e.g. @EmyrClement @cerminar @folguera as object contacts need to be aware? @mcepeda what is the procedure for validating these changes from the DPG side?
> 
> I looked at the DN and I see it contains some measurements for "Electrons" and "Muons", though I am not sure which exact objects were used. @rgoldouz could you clarify?

Hi @artlbv (let's add @mdhildreth to the loop), 

we have developed this new tune based on the stub properties in ttbar, single electron and single muon samples with PU200 (rate, efficiencies,...) and then tested its effect on the electron, muon, displaced muon, and general track efficiency. The previous and new tunes have similar efficiencies/features for track reconstruction while the new tune leads to lower stub rate.

please let me know if you have any further question. I have attached our updated version of note that will be appear on ICMS soon.

Thanks,
Reza

[DN-20-005_temp.pdf](https://github.com/cms-sw/cmssw/files/13364723/DN-20-005_temp.pdf)

**Comment by aloeliger** [comment]
@mcepeda @EmyrClement @cerminar @folguera as far as I am concerned, this is fine from a software perspective, I would like to hear one of you comment on this from a physics one before it is signed on.

**Comment by rgoldouz** [comment]
Hi @mcepeda @EmyrClement @cerminar @folguera @aloeliger @skinnari @tomalin ,
I have attached my slides for comparison of the track efficiencies between the old and new tunes using cmssw13.
[Reza_7NoV2023.pdf](https://github.com/cms-sw/cmssw/files/13396504/Reza_7NoV2023.pdf)

More comparison plots can be found in the following link
https://rgoldouz.web.cern.ch/rgoldouz/MyPlots/L1tracker/2023-11-12/

Thanks,
Reza

**Comment by cerminar** [comment]
@rgoldouz thanks for the plots! In general the electron eff. seems to be ok. 
Any reason why you only compared the PU0 electrons? Also, do you have the eff. vs pt separately for barrel and endcap?
Thanks!

**Comment by EmyrClement** [comment]
@rgoldouz thanks for the comparison - can I just check that the tracker geometry in the D76 geometry this stub window tune was derived on is the same as what's in D88/D95, which is the geometry we use in most of the L1T samples?

**Comment by rgoldouz** [comment]
Hi [cerminar](https://github.com/cerminar),
It is just for simplicity since its faster to run on the PU0 samples. But in our studies we showed that the PU200 does not change the electron/muon stub efficiencies. For the plots, I use the official code for generating trk efficiency plot (L1TrackNtuplePlot.C) and all plots can be found in https://rgoldouz.web.cern.ch/rgoldouz/MyPlots/L1tracker/2023-11-12/ where only eta distribution can show what you want. But in our AN you can find stub efficiencies for barrel and endcap in detail.

Hi @EmyrClement , As you mentioned we have developed/tested/validated the new tun using D76 geometry. In order to make sure that it works in D88, I reran the L1trk efficiency code and I found consistent results https://rgoldouz.web.cern.ch/rgoldouz/MyPlots/L1tracker/2023-11-12/. I have not tested it for D95. 

Thanks,
-Reza

**Comment by aloeliger** [comment]
@EmyrClement & @cerminar I am leaving this PR until you are satisfied by it, otherwise the changes seem trivial enough to me. Let me know if when you think it is ready.

**Comment by cerminar** [comment]
@aloeliger, as far as I can tell, I see no showstoppers for electrons.

**Comment by EmyrClement** [comment]
This if fine from my side.  Just to confirm what @rgoldouz reported on the geometries, digging through the versions [here](https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry) and for an older CMSSW release [here](https://github.com/cms-sw/cmssw/tree/CMSSW_12_5_X/Configuration/Geometry), I see the D76/88/95 geometries used the T21/24/31 tracker geometry, which correspond to identical layouts (from the descriptions of those geometries).

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
@rgoldouz 
The current baseline is D98, have you check it? The change is from T31 to T32. Thx.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
