### PR TITLE
Clean up of CondDB interface

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

This PR follows the changes introduced by https://github.com/cms-sw/cmssw/pull/29152

The IOV range selection is now accessible from the IOVProxy interface. Tag description is now loaded only on explicit request.  

#### PR validation:

A unit test has been modified to exercise the new behaviour concerning the Tag description.
The rest of unit tests run as expected.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@silviodonato is the matrix error really related to this PR?

**Comment by silviodonato** [comment]
please test
I've just merged the fix (see #29823)

**Comment by silviodonato** [comment]
please test
(the error was not related to this PR)

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
