### PR TITLE
fix rct HF FED vector and ungang csc ME1/a

### PR DESCRIPTION
**Pull request by jingyucms**
ciao @deguio 
small urgent changes for RCT and CSC

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
@davidlange6 also this PR is needed for the data taking. it would be nice to have it included in the next 74x build. this change is already included in 75x in #9143
thanks,
F.

**Comment by davidlange6** [comment]
@jingyucms Please change the title of this PR to be descriptive of the changes. THanks

**Comment by deguio** [comment]
+1

**Comment by jingyucms** [comment]
Ciao @deguio
I just updated this with also some fix of DTTF plots. Can you please grab this PR into online production in advance it merge? This seems very important to them (and also RCT and CSCTF).
Thanks and Cheers

**Comment by danduggan** [comment]
hi @jingyucms - this is in my list of packages to be deployed tonight with 744 for the online world, so it will be included.

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
