### PR TITLE
Monitoring VBF jets for VBF + 2 Taus HLT paths

### PR DESCRIPTION
**Pull request by albertdow**
This PR is for adding an initial monitoring strategy for the VBF jets of three new paths:

HLT_VBF_DoubleLooseChargedIsoPFTau20_Trk1_eta2p1_Reg_v*
HLT_VBF_DoubleMediumChargedIsoPFTau20_Trk1_eta2p1_Reg_v*
HLT_VBF_DoubleTightChargedIsoPFTau20_Trk1_eta2p1_Reg_v*

It is based on the framework developed for HLT VBF+MET paths in PR #19294 (backport #19561).

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by albertdow** [comment]
please test again, I just ran runTheMatrix.py and everything seems to have passed
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
tracked by #19142

**Comment by davidlange6** [comment]
hi @albertdow @fwyzard it looks like this PR has introduced some problems - could you provide a fix today/tomorrow?

(runTheMatrix.py -l 10026 -i all)

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_9_3_X_2017-07-26-2300/pyRelValMatrixLogs/run/10026.0_QCD_Pt_600_800_13+QCD_Pt_600_800_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step5_QCD_Pt_600_800_13+QCD_Pt_600_800_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

**Comment by fwyzard** [comment]
Hi David,
the error is caused by both "jet1etaVsLS_numerator" and "jet1etaVsLS_denominator" having negative values, while the DQMGenericClient is not protected against it.

I can add the protection if this is what you or @dmitrijus prefer, but I guess the numerator and denominator plots should actually be fixed anyway. @albertdow can you check them ASAP ?

.A

**Comment by fwyzard** [comment]
The "technical" fix is #19933 .

**Comment by davidlange6** [comment]
yea - unless i'm mistaken this makes no sense to use to compute efficiencies 

bookME(ibooker,jet1etaVsLS_,histname,histtitle,ls_binning_.nbins, ls_binning_.xmin, ls_binning_.xmax,jeteta_binning_.xmin, jeteta_binning_.xmax);

means two TProfiles , not two TH2Fs.. (one numerator, one denominator)

**Comment by davidlange6** [comment]
now that I think about it - this construct is used in many places in the HLT pRs.... I maybe the ratio of the mean of eta before/after selection vs LS is indeed whats intended, but thats not something I understand the meaning of.  (its done for met, pt, etc etc in TopMonitor for example)

**Comment by mtosi** [comment]
using the etaVsLS does not make too much sense, indeed ....

**Pull request merged**
