### PR TITLE
Top trigger names for 25 ns 74X

### PR DESCRIPTION
**Pull request by ebouvier**
This PR aims to change Top trigger path names accordingly to the CMSHLT-566 JIRA ticket, both in DQM offline and validation codes. See #11034 for the 75X IB.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by ebouvier** [comment]
Dear all,
I've propagated the same changes as in #11035.
Cheers.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
