### PR TITLE
[10.2.X] Bug fixed in SiStripBadComponentInfo

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
this PR implements a bug-fix in SiStripBadComponentInfo.cc where the bad fiber histogram never got filled (same a proposed in  #23491).
In addition for what concerns the addition of bad components from FED errors, this PR is implements a fix via cloning the `siStripQualityESProducer` and then modifying the attributes instead of just changing the attributes from the imported module.
Tested against the regular workflow (non-DQM based) and found perfect agreement.
@suchandradutta  @fioriNTU @jandrea @arossi83

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@mmusich I see that the differences are affecting the SiStrip histograms, are they what is expected?

**Comment by mmusich** [comment]
@fabiocos, as the histograms touched by this PR are located in `SiStrip/Run summary/EventInfo/BadComponentContents/` it is expected that the differences show up in this folder as it is the case e.g. for:
   * real data: wf [136.85](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-06-10-2300+23554/27044/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/SiStrip_EventInfo_BadComponentContents.html) 
  * MC: wf [10042.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-06-10-2300+23554/27044/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017/SiStrip_EventInfo_BadComponentContents.html)

I also checked that the numbers obtained in the DQM plots (e.g. for worfklow 10042.0) are the same as the ones obtained using the "classical" bad components merging (see cfg [here](https://gist.github.com/mmusich/2914f07b5f3dc8828e8c458416518cc6)):

```bash
-----------------
Global Info
-----------------
BadComponent 	   Modules 	Fibers 	Apvs	Strips
----------------------------------------------------------------
Tracker:		508	1307	2654	358119

TIB:			222	557	1123	147140
TID:			39	116	237	30519
TOB:			122	291	586	78385
TEC:			125	343	708	102075

TIB Layer 1 :		55	168	337	43709
TIB Layer 2 :		48	147	295	38346
TIB Layer 3 :		47	96	195	25693
TIB Layer 4 :		72	146	296	39392

TID+ Disk 1 :		3	9	18	2308
TID+ Disk 2 :		6	16	34	4353
TID+ Disk 3 :		1	3	7	898
TID- Disk 1 :		7	21	43	5549
TID- Disk 2 :		22	67	134	17281
TID- Disk 3 :		0	0	1	130

TOB Layer 1 :		12	26	52	7192
TOB Layer 2 :		18	41	83	11120
TOB Layer 3 :		24	56	112	14579
TOB Layer 4 :		48	97	194	25727
TOB Layer 5 :		13	45	91	12233
TOB Layer 6 :		7	26	54	7534

TEC+ Disk 1 :		16	41	84	11860
TEC+ Disk 2 :		2	6	12	2947
TEC+ Disk 3 :		4	8	18	3136
TEC+ Disk 4 :		3	9	19	3163
TEC+ Disk 5 :		7	22	45	6241
TEC+ Disk 6 :		12	34	68	8963
TEC+ Disk 7 :		17	44	89	11621
TEC+ Disk 8 :		11	23	47	6519
TEC+ Disk 9 :		6	13	26	3921
TEC- Disk 1 :		1	6	14	2633
TEC- Disk 2 :		10	31	66	8904
TEC- Disk 3 :		2	5	10	2760
TEC- Disk 4 :		0	3	9	1623
TEC- Disk 5 :		1	6	13	2059
TEC- Disk 6 :		9	29	60	8429
TEC- Disk 7 :		15	40	81	10680
TEC- Disk 8 :		4	11	22	2999
TEC- Disk 9 :		5	12	25	3617

----------------------------------------------------------------
```

To be compared with:  

badapv
badfiber
badstrip

**Comment by fabiocos** [comment]
@mmusich thanks for the confirmation

**Comment by fabiocos** [comment]
+1

**Pull request merged**
