### PR TITLE
add extra initialization checks for VirtualJetProducer with empty inputs

### PR DESCRIPTION
**Pull request by slava77**
add extra initialization checks for short-cirquited cases with no inputs (effects not accounted in PR 11902 and 11820 in 76X)

Solves the HI job failures reported in 
https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1419.html

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
jenkins got stuck in file copy step

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13152	54d9ed9
- changes affect only the logical branch that would otherwise crash
- jenkins tests pass and comparisons show no differences
- crash "status 139" reported  in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1419.html is gone based on tests CMSSW_8_0_0_pre5 done with the PR topic branch (before the PR submission)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
