### PR TITLE
Phase2-hgx283x Correct earlier versions for orientations of the depleted layers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct earlier versions for orientations of the depleted layers

#### PR validation:

Tested using the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Are the numerous comparison differences due to the HGCal changes and statistical fluctuations?

**Comment by bsunanda** [comment]
These are due to changes in HGCal geometry definition. There were issues in the earlier geometry definition.

**Comment by srimanob** [comment]
@bsunanda 
Would you mind to point to the material/presentation that shows the issue found in the earlier version? Just to complete the information on this PR. Thanks a lot.

**Comment by bsunanda** [comment]
EDMS 2051653 is the bible for longitudinal segmentation. You could see the sequence there is
MotherBoard-Connector-PCB-Glue-Silicon-Glue-Kapton-Glue-Kapton-Glue-BasePlate for EE and similarly for HE. In earlier version silicon was placed next to baseplate which was incorrect.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
