### PR TITLE
Fix for Tracker Maps and Shifter Summary

### PR DESCRIPTION
**Pull request by fioriNTU**
Fix in SiStripUtility to take into account the new IsolatedBunches directory in SiStrip workspace
Taking the opportunity to update the tk map script and add a template cfg to be used by Tracker Offline Shifters

### CODE REVIEW

**Comment by fioriNTU** [comment]
If possible this should go in the first patch realese for production, it fixes the Top Summary for shifters that at the moment in Offline DQM shows a fake status of 100% green

**Comment by davidlange6** [comment]
@fioriNTU - needs to be in 81x first - is there a PR?

**Comment by boudoul** [comment]
yes it was already referenced in the conversation : I can remind it here : PR #15517

**Comment by fioriNTU** [comment]
yes, here https://github.com/cms-sw/cmssw/pull/15517 sorry for not linking

Il 19/08/2016 10.48, David Lange ha scritto:

**Comment by davidlange6** [comment]
thanks - I just missed it

**Comment by venturia** [comment]
when we (Tracker) change the DQM code we should check the impact up to the shifter Tracker map production. I don't think this can be included in any (semi-)automatic validation procedure

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
