### PR TITLE
Added transform info to Tracer Log

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Modified ModuleCallingContext so transform calls start with id 1. Trace log now contains callID for module and requesting module Fixed a phase numbering error from previous changes

#### PR validation:

Code compiles. Tested using a modified form of the framework transform test.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try to have cleaner comparisons.

**Comment by makortel** [comment]
Usual set of
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43456
* https://github.com/cms-sw/cmssw/issues/43293

**Comment by rappoccio** [comment]
+1

**Pull request merged**
