### PR TITLE
Update on the muon shower trigger for startup Run-3 (HadronicShowerTrigger-7)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

For startup Run-3 we aim to have 2 trigger modes for muon shower: (1) >=1 nominal shower (main trigger for physics analysis) and (2) >=1 tight shower (backup trigger for physics analysis). 
- This PR introduces the tight showers in the EMTF and uGMT. 
- It also removes the out-of-time trigger option (something that needs more study during Run-3). 
- The >=2 loose showers option is disabled since we're not considering that for Run-3 either (also needs more study). 
- The anode and cathode thresholds were updated following optimization studies with Zerobias samples for rate and MC signal samples for efficiency. 
- A layer requirement of >=5 layers was added to the cathode and anode showers to reduce the trigger rate. 
- Finally, the shower trigger in the motherboard requires by default the presence of an anode shower and a cathode shower (also reduces the trigger rate).

Relevant presentation here: https://indico.cern.ch/event/1090753/contributions/4585330/attachments/2335554/3980792/CSCShower_SD_20211027.pdf

#### PR validation:

Code compiles. Tested with Run-2 ZeroBias and Run-3 MC samples.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991 @Nik-Menendez

### CODE REVIEW

**Comment by dildick** [comment]
WF 11634.0 seems to work in CMSSW_12_2_X_2021-11-02-1100

**Comment by dildick** [comment]
Can someone initiate the tests, please?

**Comment by qliphy** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
@dildick , even if it is not in the part of the code that you modified, since it is in one file that you modified, could you please take care of the static analyzer [warning](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b544f6/20210/llvm-analysis/report-ab9be9.html#EndPath)  which points out to an uncorrect usage of variable `debugTimeBins` in L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc ?

The same static analyzer report also points out a few other rather obvious mistakes/bugs in the code that should be better addressed, in a different PR but possibly rather soon. For example:
- [this](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b544f6/20210/llvm-analysis/report-00d877.html#EndPath) shows that the slope computed in the first part of CSCGEMMatcher::calculateGEMCSCBending is actually never used
- [this](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b544f6/20210/llvm-analysis/report-4bbf9a.html#EndPath) shows the same issue with `debugTimeBins` in L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc

**Comment by dildick** [comment]
@perrotta For the static analyzer, do you have an example solution that would not throw static warnings? I suppose I could just remove the ```debugTimeBins``` flag and have the (very unlikely) warning print for every event it is relevant.

**Comment by dildick** [comment]
The ```calculateGEMCSCBending``` is a work in progress. It will be used soon.

**Comment by perrotta** [comment]
> @perrotta For the static analyzer, do you have an example solution that would not throw static warnings? I suppose I could just remove the `debugTimeBins` flag and have the (very unlikely) warning print for every event it is relevant.

Yes, I would do exactly the same (possibly for both files here, since you are there) . By the way, having hardcoded the value of `true` for it does exactly the same

**Comment by perrotta** [comment]
> The `calculateGEMCSCBending` is a work in progress. It will be used soon.

... and this is a good reason to remove/fix obvious flaws since now (not in this PR, though)

**Comment by dildick** [comment]
@perrotta I'll open up a separate PR for the static warnings. For the ```calculateGEMCSCBending``` function, I'll need to check with a coworker what the status is.

**Pull request merged**
