### PR TITLE
GT Updates : Deploying Legacy2016 and Early2017 ReReco Conditions in offline GTs

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## RunI data

   * **RunI Offline processing** : [94X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v1) as [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v1/94X_dataRun2_v0):
      * Update of all ECAL local reco conditions
      * Update of Pixel local reco conditions
      * Update of SiStrip G2
      * Update of Tracker Alignment package
      * Update of all HCAL local reco conditions
      * Update of Muon Alignments and GPR
      * Update of BeamSpot

## RunII data

   * **RunII Offline processing** : [94X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v1) as [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v1/94X_dataRun2_v0):
     * Update of all ECAL local reco conditions
      * Update of Pixel local reco conditions
      * Update of SiStrip G2
      * Update of Tracker Alignment package
      * Update of all HCAL local reco conditions
      * Update of Muon Alignments and GPR
      * Update of BeamSpot

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v1) as [94X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v1/94X_dataRun2_relval_v0):
     * Update of all ECAL local reco conditions
      * Update of Pixel local reco conditions
      * Update of SiStrip G2
      * Update of Tracker Alignment package
      * Update of all HCAL local reco conditions
      * Update of Muon Alignments and GPR
      * Update of BeamSpot

Validation Campaigns for Leagcy 2016 and Early re-reco 2017 are given below : 

Legacy 2016 : https://cms-pdmv.cern.ch/valdb/?srch=LegRP&selected=AlCa_LegRP_2016C,AlCa_LegRP_2016E,AlCa_LegRP_2016G,AlCa_LegRP_2016H&Reconstruction=true&RData=true&RFull=true&RFast=true&HLT=true&HData=true&HFull=true&HFast=true&PAGs=true&PData=true&PFull=true&PFast=true

Early Re-Reco 2017 : https://cms-pdmv.cern.ch/valdb/?srch=Alca&selected=AlCa-ReReco17-297656,AlCa-ReReco17-297227,AlCa-ReReco17-300401&RData=true&RFull=true&RFast=true&PAGs=true&PData=true&PFull=true&PFast=true&Reconstruction=true

### CODE REVIEW

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
@davidlange6 @smuzaffar the error in all the workflows is same and seems like related to IB.
Can you please check?

>> CTPPSIncludeAlignments::PrepareSequence(Measured)
>> CTPPSIncludeAlignments::PrepareSequence(Real)
----- Begin Fatal Exception 01-Oct-2017 19:17:09 CEST-----------------------
An exception of category 'RPAlignmentCorrectionsDataSequence' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=CTPPSIncludeAlignments label='ctppsIncludeAlignments'
Exception Message:
Cannot parse file `/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-10-01-0000/src/Alignment/CTPPS/data/RPixGeometryCorrections.xml' (xmlDoc = NULL).
----- End Fatal Exception -------------------------------------------------

for example : 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20707/23344/runTheMatrix-results/101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL/step1_SingleElectronE120EHCAL+SingleElectronE120EHCAL.log

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20707/23344/runTheMatrix-results/5.1_TTbar+TTbarFS+HARVESTFS/step1_TTbar+TTbarFS+HARVESTFS.log

**Comment by smuzaffar** [comment]
why this file is being searched in to local path (/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-10-01-0000/src/Alignment/CTPPS/data/RPixGeometryCorrections.xml ) it should be picked up from release area via FileInPath. 
#20438 added this file, could it be the this file is search in $CMSSW_BASE instead of making use of FileInPath

**Comment by slava77** [comment]
On 10/1/17 12:34 PM, Malik Shahzad Muzaffar wrote:
> why this file is being searched in to local path
> (/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-10-01-0000/src/Alignment/CTPPS/data/RPixGeometryCorrections.xml
> ) it should be picked up from release area via FileInPath.
> #20438 <https://github.com/cms-sw/cmssw/pull/20438> added this file,
> could it be the this file is search in $CMSSW_BASE instead of making use
> of FileInPath

that indeed appears to be the problem

**Comment by arunhep** [comment]
@smuzaffar please let me know when I can restart the tests

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
thanks @smuzaffar

**Comment by arunhep** [comment]
file-open error.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20707/23354/addOnTests/hlt_data_2e34v31/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run2_hlt_2e34v31_--relval_9000,50_--datatier_RAW_--eventcontent_RA.log

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1
changes are at right places and conditions are already validated in dedicated campaigns.

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@arunhep , one workflow 1010.0 start failing with following error message. Did we miss something in new GT?
```
An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 299149 stream: 2
   [1] Calling method for module ECALpedestalPCLworker/'ALCARECOEcalPedestals'
Exception Message:
No "EcalPedestalsRcd" record found in the EventSetup for synchronization value
Run: 299149 LuminosityBlock: 0 Event: 0 Time: 6443215847611025920
 Please add an ESSource or ESProducer that delivers such a record.
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_4_X_2017-10-02-2300/pyRelValMatrixLogs/run/1010.0_TestEnableEcalHCAL2017B+TestEnableEcalHCAL2017B+TIER0EXPTE+ALCAEXPTE+ALCAHARVDTE/step3_TestEnableEcalHCAL2017B+TestEnableEcalHCAL2017B+TIER0EXPTE+ALCAEXPTE+ALCAHARVDTE.log

**Comment by arunhep** [comment]
@smuzaffar checking

**Comment by arunhep** [comment]
@smuzaffar  this PR https://github.com/cms-sw/cmssw/pull/20736 should fix the issue.

**Pull request merged**
