### PR TITLE
Run2-alca120 Update codes for SPR studies

### PR DESCRIPTION
**Pull request by bsunanda**
Enable to extend studies of single particle response to higher energies

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie Can you please approve this PR

**Comment by bsunanda** [comment]
@arunhep @lpernie Can you approve this PR?

**Comment by lpernie** [comment]
+1

**Pull request merged**
