### PR TITLE
Migrate ESProducers in reconstruction from setConsumes() to type-deducing consumes()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates `setConsumes()` calls to the simpler consumes introduced in #31223.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by jpata** [comment]
+reconstruction

- technical, no changes to reco output
- migrates to the new simpler consumes interface

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
