### PR TITLE
followup fixes after enabling seedingDeepCore displacedRegionalTracking in #43472

### LINKED ISSUE #43495: ProductNotFound error in module MultiTrackValidator/'trackValidatorJetCoreSeedingTrackingOnly'
In CMSSW_14_0_X_2023-12-04-2300, RelVals 2017.13, 2018.13, 10024.3 fail with ProductNotFound exception:

```
----- Begin Fatal Exception 05-Dec-2023 07:19:29 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 6 stream: 0
   [1] Running path 'prevalidation_step'
   [2] Calling method for module MultiTrackValidator/'trackValidatorJetCoreSeedingTrackingOnly'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Track
Looking for module label: seedTracksjetCoreRegionalStepSeedsBarrel
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Examples of logs: [1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/2017.13_TTbarFS_13_UP17/step1_TTbarFS_13_UP17.log#/1141-1141), [2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/2018.13_TTbarFS_13_UP18/step1_TTbarFS_13_UP18.log#/1141-1141), [3](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/10024.3_TTbar_13+2017_trackingOnlyRun2/step3_TTbar_13+2017_trackingOnlyRun2.log#/92-92), [4](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/10024.4_TTbar_13+2017_trackingLowPU/step3_TTbar_13+2017_trackingLowPU.log#/75-75).

### PR DESCRIPTION
**Pull request by slava77**
to resolve #43495

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 2017.13,2018.13,10024.3,10024.4

**Comment by slava77** [comment]
> ROOTFileChecks: Some differences in event products or their sizes found

these are related to now fixed workflows 10024.3,10024.4 according to the [logRootQA-events.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-12-13-2300+b313da/60274/validateJR/logRootQA-events.log)

**Comment by tjavaid** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test workflow 2017.13,2018.13,10024.3,10024.4

**Comment by tjavaid** [comment]
+1

- spurious differences observed from unstable WF `12434.7` (open issue #39803 )

**Comment by iarspider** [comment]
@cms-sw/operations-l2 gentle ping

**Comment by iarspider** [comment]
@cms-sw/operations-l2 gentle ping

**Comment by mmusich** [comment]
urgent
   * fixes residual IB relval failures

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
