### PR TITLE
re-enable the kOutOfTime filtering in PF-rechits 

### PR DESCRIPTION
**Pull request by emanueledimarco**
1) kOutOfTime filtering is needed to complete the ECAL spike rejection together with the topological cuts

2) enable the usage of the ECAL rechits recovered in case of dead trigger towers (new algorithm for the recovery is in place)

@mariadalfonso @bachtis @argiro @cerminar @bendavid please also look at this

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I'm looking at our tests comparisons and so far, the change in 2) (the dead tower recovery) dominates the physics level changes.
I wish that this late we were receiving only changes that were identified and discussed as a follow up to validation.
Maybe I missed the part for the change for item 2).

@bachtis 
?

**Comment by bachtis** [comment]
Hi, Which hits go into the selection is something we trust the DPG on.  Now if we have a high level plot that shows worse behavior we can togther with them decide that we dont want thoise hits in..I understood  it is a zero level change...Can someone tell me here what exactly those hits are ?

**Comment by bendavid** [comment]
Hi,
I would like to point out that TT recovery hits were also skipped even in 71x before the multifit went in.  So this is an orthogonal change at least.
https://github.com/cms-sw/cmssw/blob/CMSSW_7_1_X/RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitECAL_cfi.py

**Comment by slava77** [comment]
I will post a few plots shortly.
Maybe I misinterpreted what's coming from 1) and 2).

**Comment by slava77** [comment]
it would've been much better to see some prevalidation (expected physics changes) plots from the authors, together with the PR.

**Comment by argiro** [comment]
I propose that the two points 

1) re-enable kOutOfTime and
2) use recovered channels

are separated,  so that 1) can go in right away, and we can think a bit more about 2).

S

**Comment by slava77** [comment]
It appears that most of the visible changes appear in the samples without pileup in MC,
and quite a few increase the number of pf/egamma objects, which is why I attribute the effect to 2) (adds hits) rather than 1) (removes hits) prompt 
Please take a look at the plots below.


- Run1, 2 single-muon gun muon pt 1TeV: particleFlowRecHitECAL_Cleaned are now essentially empty; other variables are essentially unchanged
all_sign528vsorig_singlemu13pt1000wf1322p0c_log10recopfrechits_particleflowrechitecal_cleaned_reco_obj_energy
- photon gun pt35 run1 setup
    - the particleFlowRecHitECAL_Cleaned is ~empty here as well
    - some increase in particleFlowSuperClusterECAL  with a matching increase in particleFlowEgamma candidates (there's some (matching?) increase in allConversions; the gedGsfElectrons are essentially unchanged)
all_sign528vsorig_singlegammapt35wf19p0c_recocaloclusters_particleflowsuperclusterecal_particleflowbasicclusterecalbarrel_reco_obj_phi
wf19_photonsbadchannels
wf19_photons_frac_w_dead

    - reduction in MET tail corresponding to the sim electron pt (this and above is supposedly from the recovered hits; not from OOT removal)
all_sign528vsorig_singlegammapt35wf19p0c_log10recopfmets_pfmet__reco_obj_pt
- photon gun pt35 run1 setup
    - there is some, but much smaller increase in ECAL pf superclusters (and a smaller effect in MET). Is the fraction of dead trigger towers much smaller?
- electron gun 1 TeV has more pronounced increase in PF gammas at pt around 10-50 GeV
all_sign528vsorig_singleelectronpt1000wf16p0c_log10recopfcandidates_particleflow__reco_obj_pt40
- the same electron gun pt35 now in run2 setup has probably the same effect in the intermediate energy range, but the scale at low-pt makes it harder to compare
all_sign528vsorig_singleelectron13pt1000wf1316p0c_log10recopfcandidates_particleflow__reco_obj_pt40
- jet samples without pileup have smaller changes fractionally in the same kind of variables


ttbar with PU35@25ns doesn't show any noticeable change expcept for the cleaned hits
all_sign528vsorig_ttbarpuwf25202p0c_recopfrechits_particleflowrechitecal_cleaned_reco_obj_position_eta



- data run2011A (~no PU)
cleaned hits go down only only on vey low-pt side, there is some visible increase of them 
all_sign528vsorig_runminbias2011awf1000p0c_log10recopfrechits_particleflowrechitecal_cleaned_reco_obj_energy
all_sign528vsorig_runminbias2011awf1000p0c_recopfrechits_particleflowrechitecal_cleaned_reco_obj_position_eta

- data run2012B (some PU)
the yields of egamma pf superclusters reduces (oot removal?), with matching decrease in other ecal/egamma pf objects
all_sign528vsorig_runphoton2012bwf4p53c_log10recocaloclusters_particleflowsuperclusterecal_particleflowbasicclusterecalbarrel_rereco_obj_energy

**Comment by emanueledimarco** [comment]
@argiro and @slava77 Yes. 1. and 2. are separated. 
The followup to the PPD report is just 1. 
Let mw know if you want that I update the PR (both 7.4.X and 7.5.X) to only enable 1.

**Comment by slava77** [comment]
Hi Emanuele,

Please make a separate one with 1. only.
This is the required minimum.

based on Q&A on this thread so far it sounds like 1+2 may make sense as
well, but it's not clear to me at this point.

Regarding the plots I posted, I suppose the changes in the Cleaned hits
is as expected from this PR changes as well as the appearance of the
photons with  "bad xtal" histograms.
Please confirm.



On 3/13/15 6:23 PM, Emanuele Di Marco wrote:
> @argiro <https://github.com/argiro> and @slava77
> <https://github.com/slava77> Yes. 1. and 2. are separated.
> The followup to the PPD report is just 1.
> Let mw know if you want that I update the PR (both 7.4.X and 7.5.X) to
> only enable 1.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8224#issuecomment-79156586>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by emanueledimarco** [comment]
Hi Slava, 

just done (updated PR. Will do the same for the one in 75X branch). Regarding the expected physics changes, I don't expect big changes in the bulk of the MC, since it has not the simulation of the spikes enabled (it may clean some rechit though). The changes may be visible in the tails of the MET for real data. Indeed the effect is for example to clean the events reported at one recent PPD meeting. The study of the effect on those events is reported in yesterday ECAL DPG talk:

https://indico.cern.ch/event/380955/contribution/2/material/slides/0.pdf

and proposal for re-instantiating 1. in:

https://indico.cern.ch/event/380955/contribution/3/material/slides/0.pdf

I confirm the changes that you saw from the previous PR

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Emanule, thank you for the pointers to the slides.
Looking at the ECAL DPG slides I missed to notice the discussion of (2) the dead trigger tower recovery hits

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8224	359d1dc
tested in CMSSW_7_4_0_pre8 /test area sign528, cherry-picked/

With only the item (1), kOutOfTime filtering, the changes are fairly minimal. Differences show up only in data workflows and in MC with pileup (MC without pileup is unchanged).

Emanuele, please update the subject of the PR so that it doesn't suggest the TT recovery is applied

- Run2012B Photon PD
There is a small reduction in the number of reduced ecal hits, corresponding to a few % reduction in the number of ECAL PF clusters, followed by a matching reduction in downstream pf/egamma objects (changes in ged photons and electrons as well as in pf candidates are small)
all_sign528pass-359d1dcvsorig_runphoton2012bwf4p53c_log10recocaloclusters_particleflowsuperclusterecal_particleflowbasicclusterecalbarrel_rereco_obj_energy
all_sign528pass-359d1dcvsorig_runphoton2012bwf4p53c_log10recopfcandidates_particleflowegamma__rereco_obj_pt

The number of Cleaned rechits goes up (expected for this change)
all_sign528pass-359d1dcvsorig_runphoton2012bwf4p53c_log10recopfrechits_particleflowrechitecal_cleaned_rereco_obj_energy

**Comment by davidlange6** [comment]
+1

**Pull request merged**
