### PR TITLE
Add L1 Upgrade Workflow: 0.78

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

This PR creates an L1 workflow that includes the recently added Phase 2 L1 GT Emulator (and related `cmsDriver` step from https://github.com/cms-sw/cmssw/pull/43210) for testing of L1 upgrade sequences and PRs. The workflow should run a modified version of the `Digi` and `DigiTrigger` steps with the GT emulator inserted, and it should be available on 2026 workflows. @srimanob This should provide the L1 testing workflow we have been discussing, please let me know if you would like/were envisioning something else.

L1 would also like to explore whether this workflow, or a similar workflow idea can be used for validation of proposed to changes to L1, especially from the physics effects/menu effects perspective.

I don't know if this is the optimal solution for the testing that has been requested from L1, or if it will fully suit other L1 uses for it, so I would like some outside input on whether this is a good solution for being able to test the L1 steps going forward versus say, something like modifying the in place `Digi`/`DigiTrigger` steps, and having these L1 steps be in place "by default". Also, this runs redundant steps from the L1 point of view... Anything past step2 is not L1, so as far as testing L1 exclusively, seems like wasted work, but I am not sure how I might change that, or if it is within my ability to do so, let alone whether it is a good idea.

I don't know if there is a policy on naming/numbering these workflows. I didn't see anything relevant in the `README.md`, so I more or less chose `.1001` at random. If this needs to be changed, no issue, it is not used in anything else that we plan to commit at the moment.

@mcepeda & @artlbv I figure you might like to be informed about this, my hope is that eventually this can serve as the basis of a way to do more automatic L1 software validation and testing. Perhaps we can discuss this at some point.

### PR validation:

This PR has been tested by running two added workflows via the commands:
- `runTheMatrix.py --what upgrade -l 20834.1001` for an older and more used geometry
- `runTheMatrix.py --what upgrade -l 26834.1001` for a more recent geometry

Both workflows manage to run through step2, with the `Digi` or `DigiTrigger` steps, but, in full disclosure, step3 fails on the RAW2DIGI step, complaining about no FEDRawData collection.

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport, and likely will not need backporting.

### CODE REVIEW

**Comment by aloeliger** [comment]
@srimanob Trying to add the HLT step into this by itself just errors out, but adding it and DIGI2RAW raw step gets all steps functioning. I have added both into the workflow.

**Comment by srimanob** [comment]
> thanks a lot for this @aloeliger and @srimanob ! Could you clarify what exactly the output of this would be? Would this be like FEVTDEBUG from which we could e.g. extract the P2GT decisions and/or the final L1 objects used as input to the P2GT? Because then we could indeed do some sort of "validation"/DQM, monitoring the object performance and rate changes. (btw, does something like this exist for phase-1?)

Hi @artlbv 
The final output is FEVTDEBUGHLT out from RECO+DQM steps (if we run full sequence).

**Comment by srimanob** [comment]
test parameters:
- workflow = 24834.78
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
> @srimanob Trying to add the HLT step into this by itself just errors out, but adding it and DIGI2RAW raw step gets all steps functioning. I have added both into the workflow.

@aloeliger 
Right, they need to come together. I just trigger the test of new workflow, let's see the result.
@artlbv 
To confirm, currently, FEVTDEBUGHLT contain all what you need right?

Thx.

**Comment by srimanob** [comment]
FYI @SohamBhattacharya @rovere 
This PR introduce a new workflow with L1P2GT in sequence.

**Comment by artlbv** [comment]
> To confirm, currently, FEVTDEBUGHLT contain all what you need right?

Well, for the menu studies we never used the FEVTDEBUG except for doing the `edmDump` for checking the new collections were produced (even though it seems that not everything is present there). 

I think our HLT experts @SohamBhattacharya and @rovere were making more use of that, though of course not using all the collections we have in the "full step-1 L1 menu".

Given that we are working on Nano for the Phase-2 L1 Menu ntuples (https://github.com/cms-l1-dpg/Phase2-L1Nano) I think we could actually check whether we could produce these from the FEVTDEBUG. Would this be a good test?

**Comment by srimanob** [comment]
Hi @aloeliger 
The PR runs fine. I think it is good to go. One last question, should the new workflow be tested when new Phase-2 L1T PRs come?

**Comment by srimanob** [comment]
+Upgrade

New workflow with L1P2GT runs fine.

**Comment by aloeliger** [comment]
> Hi @aloeliger 
> The PR runs fine. I think it is good to go. One last question, should the new workflow be tested when new Phase-2 L1T PRs come?

@srimanob Yes. There aren't any plots to check, but at the least it will make sure everything still runs correctly, which I think is not a bad thing to test for.

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2 as this PR will be useful for future Phase-2 L1T PR. Thanks.

**Comment by srimanob** [comment]
Ping again @cms-sw/pdmv-l2 
Thanks.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
