### PR TITLE
open an autoCond key for hcal dev branch (hopefully only pro-tempore)

### PR DESCRIPTION
**Pull request by mmusich**
@kpedro88 hope this helps

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1



On 16 Sep 2016, at 20:46, Marco Musich <notifications@github.com<mailto:notifications@github.com>> wrote:


+1

**Comment by ianna** [comment]
@mmusich - I was wondering if it's prudent to bump it to v2 with the following tags included for consistency:
```
XMLFILE_Geometry_81YV8_Extended2017dev_mc
HCALRECO_Geometry_81YV8
HCALParameters_Geometry_81YV8
CTRECO_Geometry_81YV8
```

**Comment by mmusich** [comment]
@ianna, will do together with the rest of the changes you requested in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2627.html and 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2628.html

**Pull request merged**
