### PR TITLE
Improve Simtrack to GEM/CSC digi and stub matching (CCLUT-4.5)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

While debugging the CCLUT algorithm (for Run-3 CSC), I noticed a few bugs:
- The CSC half-strip stagger needs to undone before saving the half-strips in the CLCT object
- Several classes under Validation/Muon* need to clear the matched hit collections before doing the simtrack-to-hit matching.
- The matching of simtrack-to-CLCT is now based on checking the number of exact half-strip matching in each layer (>= 3 in total). Previously it was purely based on the match to the key half-strip.
- The class CSCComparatorDigiFitter is redundant and can be deleted.

#### PR validation:

Tested in CMSSW_11_1_0_pre6 using events in the Run-3 MC data set `/JPsiToMuMu_Pt0to100-pythia8_TuneCP5-gun/Run3Winter20DRMiniAOD-DRFlatPU30to80_110X_mcRun3_2021_realistic_v6-v2/GEN-SIM-RAW`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test with #29826

**Comment by jfernan2** [comment]
please abort
Test got stuck

**Comment by jfernan2** [comment]
please test with #29826

**Comment by dildick** [comment]
@jfernan2 Tests got stuck again...

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
do you have any comments @rekovic ?

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
