### PR TITLE
fix usage of SeedFromConsecutiveHitsCreator w/in SeedGeneratorFromProtoTracksEDProducer

### PR DESCRIPTION
**Pull request by mtosi**
while integrating PR 7781
and after having fixed the muon and electron code [see PR https://github.com/cms-sw/cmssw/pull/8367]
I found there was still an issue w/ the HLT config

it turned out that it was due to the --wrongly-- usage of the default constructor
https://github.com/mtosi/cmssw/blob/CMSSW_7_0_X/RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc#L101

this PR is meant to fix this issue
I'm going to do the same PR in 75X as well

### CODE REVIEW

**Comment by mtosi** [comment]
@VinInn @rovere @fwyzard @Martin-Grunewald @perrotta

**Comment by mtosi** [comment]
I forgot to stress one important point

the HLT config needs to be update accordingly :(
as you can see by the fillDescription method
https://github.com/mtosi/cmssw/blob/from-CMSSW_7_4_X_2015-03-17-0200_fixSeedFromProtoTracks/RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc#L47-56

I added the needed parameters
(the default values are not the one to be used @HLT, though)
we need to have the following ones @HLT, instead
SeedCreatorPSet = cms.PSet(
   ComponentName = cms.string("SeedFromConsecutiveHitsCreator"),
   propagator            = cms.string("PropagatorWithMaterialParabolicMf"),
   SeedMomentumForBOFF = cms.double(5.0),
   OriginTransverseErrorMultiplie = cms.double(1.0),
   MinOneOverPtError = cms.double(1.0),
   magneticField = cms.string("ParabolicMf"),
   TTRHBuilder = cms.string("hltESPTTRHBuilderPixelOnly"),
   forceKinematicWithRegionDirect = cms.bool(false),
)

**Comment by Martin-Grunewald** [comment]
Great, now I have merge conflicts with the other PRs.
You should have left it uintouched!

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
Please close this PR : it conflicts with #7698 and is superseeded by #8390

**Comment by slava77** [comment]
-1

superseded by #8390

**Pull request closed without merging**
