### PR TITLE
updated parameters and model for photon XGboost MVA (HLT) [14_1_X]

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
* Latest XGBoost model in cms-data added to the unit test. Requires: https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/15
* Removed unused parameters and updating relevant parameters to the values intended for inclusion into the pp HLT menu.

#### PR validation:

Unit test added for the new model file.

### CODE REVIEW

**Comment by smorovic** [comment]
please test with https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/15

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/15

**Comment by mmusich** [comment]
@cmsbuild, please test

   * to get cleaner comparisons

**Comment by mmusich** [comment]
type egamma

**Comment by mmusich** [comment]
+hlt

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
