### PR TITLE
Run3-hcx289 Have a modified version for HO xml

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Have a modified version for HO xml to sort out the issue between Muon and HO for list of materials

#### PR validation:

Tested using cfg scripts in Geometry/HcalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
