### PR TITLE
Cleaning of PGeometricTimingDetExtra

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses issue https://github.com/cms-sw/cmssw/issues/31822 for the residual part of ```PGeometricTimingDetExtra```, never really used and now no more justified.

#### PR validation:

Code compiles, the unit tests of the two affected packages run smoothly.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by christopheralanwest** [comment]
+alca

**Comment by civanch** [comment]
+1

the issue has been discussed intensively.

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
