### PR TITLE
Migration of HLT to 1010 template (102X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to 1010 template (102X)
Based on CMSSW_10_2_X_2018-04-02-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
test missed last update also here

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
