### PR TITLE
Revised binning for L1T Tau DQM efficiency turn-ons

### PR DESCRIPTION
**Pull request by davignon**
Updated tauEfficiencyBins with new binning for L1T Tau DQM efficiency turn-ons.
This relates to https://its.cern.ch/jira/browse/CMSLITDPG-385
Please consider for merging.
Cheers,
- Olivier

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
Hi @jfernan2 @dmitrijus could you take a look at this PR as well please and let us know if it is OK for you?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
