### PR TITLE
[Tag-N-Probe] Split read mode 

### PR DESCRIPTION
**Pull request by drkovalskyi**
Added a new mode of running TagNProbe code that uses less memory by creating RooDataSet for each bin individually and reading data from the input TTree in chunks. It allows to reduce memory usage for typical fits done by Muon POG from ~20GB down to 1-2GB. The code runs significantly slower in the new mode, so it shouldn't be a default option. The change should not affect any code unless the new mode is requested explicitly and even in this case all results should be the same.

### CODE REVIEW

**Comment by drkovalskyi** [comment]
@gpetruc, @cmsbuild, @arizzi, @monttj could you please check the pull request?

**Comment by gpetruc** [comment]
At a quick read it looks ok to me, but me and @arizzi are supposed to put the +1 only on NanoAOD-related PRs, and this one is not.
Did you do a check that on a small dataset, for which the old version works, the two things give the same answer, and that it works also correctly for dynamic categories? (the one practical case I'm aware of is the fit for tracking efficency, maybe you can ask Walaa for a cfg or to do the test)

**Comment by drkovalskyi** [comment]
I have checked muon efficiency measures for Run2017 and got identical results, but I cannot test all use cases since I'm not familiar with them and I don't see any unit tests to check it. So far we started using it in Muon POG for new measurements, so it's pretty much production already.

**Comment by fabiocos** [comment]
@drkovalskyi I understand this is not running in standard production wf, is it correct? Or which are them in case?

**Comment by drkovalskyi** [comment]
It's not running in the standard production, but it's widely used by different groups.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
