### PR TITLE
Modernize modules in SUSYBSMAnalysis/HSCP

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Converted modules used in integration tests to be thread friendly.
- fixed a memory leak in UpdatedMuonInnerTrackRef

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Part of #25090

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
