### PR TITLE
Add GE1/1 detection efficiency monitor using GEMCSCSegment

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
This PR adds DQM modules to monitor GE1/1 detection efficiency using GEMCSCSegment in the online DQM. It adds 36 MonitorElements for all eras and all scenarios in the online DQM. Please see [this slides](https://indico.cern.ch/event/1136226/contributions/4767246/attachments/2404268/4112480/SYang_220308_GEMEffByGEMCSCSegment.pdf) for more details.

#### PR validation:
This PR is tested with the muon gun simulation. Please check the above slides.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
none

### CODE REVIEW

**Comment by seungjin-yang** [comment]
@jshlee @quark2

**Comment by seungjin-yang** [comment]
I checked the ORP meeting report and so I don't need a backport for April 8 collision runs, right?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@seungjin-yang  Since this PR involves Online DQM, as usual we need a backport to 12_2_X to test it at P5
FYI @pmandrik

**Comment by seungjin-yang** [comment]
I'm running the unittest locally and I'm able to report tomorrow.

**Comment by seungjin-yang** [comment]
> @seungjin-yang Since this PR involves Online DQM, as usual we need a backport to 12_2_X to test it at P5 FYI @pmandrik

Thanks @jfernan2, I will make a backport PR after fixing errors in the unittest.

**Comment by seungjin-yang** [comment]
@jfernan2 I checked that the error in the unittest has been fixed on lxplus. Also, I added 24 plots.

```bash
bash /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/37178/22948/install.sh
cd CMSSW_12_3_X_2022-03-08-1100/src
cmsenv
cmsRun ./DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True
```

**Comment by jfernan2** [comment]
please test

**Comment by seungjin-yang** [comment]
@jfernan2 Backporting this PR to 12_2_X requires a backport of PR https://github.com/cms-sw/cmssw/pull/36628, which is a technical PR to update the way to retrieve data from  `EventSetup` in `GEMCSCSegmentProducer`. is it okay to make a PR to backport https://github.com/cms-sw/cmssw/pull/36628 and then make a PR to backport this PR?

**Comment by jfernan2** [comment]
@seungjin-yang  the point is if you need this changes on the current data taking, which uses 12_2_X
If you don't need this PR in current data taking (I assumed you needed since it affects Online DQM), then a backport is not needed

**Comment by seungjin-yang** [comment]
@jfernan2, I'm sorry for the delay in responding. I added a new online DQM module and want this module to work from April, not current data taking.

**Comment by jfernan2** [comment]
Thanks @seungjin-yang 
In any case, before moving ahead, we need to test this in advance for Online DQM at P5, so please create a backport to 12_2_X to do so

**Comment by seungjin-yang** [comment]
@jfernan2 Thank you for your guidance. I created a backport PR (#37341) of #36628 first. The reason is that `GEMEffByGEMCSCSegmentSource` module uses `GEMCSCSegment` but `GEMCSCSegmentProducer` doesn't work in 12_2_X. #37341 will fix this problem.

**Comment by seungjin-yang** [comment]
@jfernan2 I realized that the milestone changed from 12_3_X to 12_4_X. can I still make a backport of this PR to 12_3_X?

**Comment by jfernan2** [comment]
@seungjin-yang  P5 is still using 12_2_X so we will need for the moment a backport to that version, and then to 12_3_X too

**Comment by jshlee** [comment]
@jfernan2 yes, we plan to backport to both

**Comment by jfernan2** [comment]
+1
@seungjin-yang @jshlee please also backport to 12_3_X

**Comment by perrotta** [comment]
please test
(28 days old test must be refreshed before proceeding)

**Comment by perrotta** [comment]
@seungjin-yang @jfernan2 could you please explain which is the difference between this master PR and the 12_2_X backport #37476 that you tested at P5 in order to approve this one? At least the number of modified lines of code is different...

**Comment by seungjin-yang** [comment]
Hi @perrotta,
As mentioned in https://github.com/cms-sw/cmssw/pull/37476#issue-1194208808, only the `GEMEffByGEMCSCSegmentSource` module has differences between the original PR and the 12_2_X backport. So, there are differences in the following two files:
- DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.h
- DQM/GEM/plugins/GEMEffByGEMCSCSegmentSource.cc

In the backport, `GEMEffByGEMCSCSegmentSource` is directly derived from `DQMEDAnalyzer`, not `GEMOffflineDQMBase`, and instead contains `GEMOffflineDQMBase`’s several methods.

So, here is a pseudo diff output for the header file between the original PR and the backport (`diff OriginalPR Backport`). 
```diff
< class GEMEffByGEMCSCSegmentSource : public GEMOfflineDQMBase {
---
> class GEMEffByGEMCSCSegmentSource : public DQMEDAnalyzer {
>   // NOTE
>   using MEMap = std::map<GEMDetId, dqm::impl::MonitorElement*>;
>   bool hasMEKey(const MEMap&, const GEMDetId&);
>   void fillME(dqm::impl::MonitorElement*, const double);
>   void fillME(MEMap& me_map, const GEMDetId& key, const double);
>   void fillMEWithinLimits(dqm::impl::MonitorElement*, const double);
>   void fillMEWithinLimits(MEMap&, const GEMDetId&, const double);
>   template <typename T>
>   inline bool checkRefs(const std::vector<T*>&);
>   inline GEMDetId getReStLaKey(const GEMDetId&);
>   const double kEps_ = std::numeric_limits<double>::epsilon();
```

Also, `diffstat` says the 86 new lines were added and 10 lines deleted.

**Comment by seungjin-yang** [comment]
I found that my PR is behind from master for `DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py`. #37101 has updated the config file but my one is outdated. Can you please let me know how to proceed?

[#37101](https://github.com/cms-sw/cmssw/pull/37101/files#diff-71db74c18546edadf46cdea99de68605ceabd20dde5a415f8088f544d91d2d88)
```diff
- from Configuration.StandardSequences.Eras import eras
- process = cms.Process('GEMDQM', eras.Run3)
+ from Configuration.Eras.Era_Run3_cff import Run3
+ process = cms.Process('GEMDQM', Run3)
```

[My PR](https://github.com/seungjin-yang/cmssw/blob/GEMEffByGEMCSCSegment__from-CMSSW_12_3_0_pre5/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py#L4-L5)
```python
from Configuration.StandardSequences.Eras import eras
process = cms.Process('GEMDQM', eras.Run3)
```

**Comment by perrotta** [comment]
+1

**Comment by seungjin-yang** [comment]
@perrotta Thank you for your kind explanation!

**Comment by perrotta** [comment]
+1
- The 12_2_X version of this PR was also tested at P5, see https://github.com/cms-sw/cmssw/pull/37476#issuecomment-1091185300

**Pull request merged**
