### PR TITLE
L1 tk primitives fix bis

### PR DESCRIPTION
**Pull request by sudhaahuja**
Branch fixed to produce stubs with the tab2013 algo

### CODE REVIEW

**Comment by boudoul** [comment]
Hi @sudhaahuja , I believe this PR is not for 81X , but for SLHCDEV....

**Comment by sudhaahuja** [comment]
@boudoul , yes I think I got the CMSSW version wrong. Can I edit it now in the same PR?

**Comment by boudoul** [comment]
you just did to make a new PR with your branch but BEFORE clicking on 'create pull request" choose the baseline: 6_2_SLHCDEV_X

**Comment by sudhaahuja** [comment]
Yes, I already did that. I closed this PR also. Thanks.

**Pull request closed without merging**
