### PR TITLE
[Backport HGC trigger] V10/V11 e/g ID + calibration and concentrator module sums

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:

- Add e/gamma identification BDT and e/gamma energy corrections for the V10 and V11 geometries (@cerminar )
- Implement module sums of unselected trigger cells in the concentrator (@echapon )

Backport of #30289

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by jbsauvan** [comment]
Somehow it didn't find in the tests the data added in cms-data/L1Trigger-L1THGCal#18

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov 
https://github.com/cms-sw/cmsdist/pull/5982 needs to be backported to the 11_1_X branch of cmsdist

**Comment by smuzaffar** [comment]
@kpedro88 , https://github.com/cms-sw/cmsdist/pull/5991 backport the changes for 11.1.X

**Comment by silviodonato** [comment]
please test with  cms-sw/cmsdist#5991

**Comment by kpedro88** [comment]
backport of #30289

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge

**Pull request merged**
