### PR TITLE
Backport of GenHTFilter

### PR DESCRIPTION
**Pull request by jfernan2**
Needed for sample production of TOP-17-019 analysis

### CODE REVIEW

**Comment by jfernan2** [comment]
@cmsbuild please test

**Comment by perrozzi** [comment]
can you point to the master commit/PR?

**Comment by jfernan2** [comment]
Sorry, but I do not know which PR introduced this code when it was integrated in 8XY. However the filter works on 7XY so the backport is identical to the existing code. Thanks
________________________________________

**Comment by alberto-sanchez** [comment]
backport of #12709

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
