### PR TITLE
Speedup expression evaluator unit test

### PR DESCRIPTION
**Pull request by VinInn**
it seems to time out in jenkins

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@cmsbuild , please test. thanks

**Comment by ktf** [comment]
@cmsbuild please test

not so smart...;)

**Comment by cvuosalo** [comment]
@VinInn:
At the beginning of the Jenkins unit [tests] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8628/2317/unitTests.log) there seems to be an error (shown below). Does this error indicate a serious problem? Is it related to this PR?

Thread model: posix
gcc version 4.9.1 (GCC) 
|

|9cbdb90202574e03851a114e3902d00c
|

|sh: notexisting: command not found

**Comment by cvuosalo** [comment]
+1

For #8628 349fe9d124cfdaa6c3ed6326739bda3215fd7e77

Fix for Jenkins time-out.

The code changes are satisfactory, and Jenkins test [results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8628/2317/summary.html) against baseline CMSSW_7_5_X_2015-04-02-1100  show no problems, other than the unit test error message mentioned above that is probably not significant.

**Comment by VinInn** [comment]
@cvuosalo: is expected. means it works correctly!  maybe I will add a comment next iteration

**Pull request merged**
