### PR TITLE
CTPPS: DQM for TOTEM RP - backport of #14034

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #14034 from CMSSW 81X

The code will not compile as it depends on many features not yet integrated in CMSSW. I'm issuing the PR so as people can start looking at the code. Compilable code is available in the CTPPS repository:
https://github.com/CTPPS/ctpps-offline.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
please align this with 81x (to make it compile-able)

**Comment by grzanka** [comment]
@dmitrijus what do you mean by aligning it with 81x ? it is an exact copy of PR which was merged in 81x.

**Comment by dmitrijus** [comment]
@grzanka Oh, sorry, you are right - these are the same commits as 81x PR.
However, it needs to compile first before it can be included.

I guess this dependency-PR (https://github.com/cms-sw/cmssw/pull/14630) is missing from 80x.

**Comment by dmitrijus** [comment]
hold

**Comment by grzanka** [comment]
@dmitrijus yes, it would be great to merge CTPPS backport PRs in 80X in the same order as they were merged in the 81X

**Comment by dmitrijus** [comment]
It's not up to me to merge them...
Can you list them here in the order you want them to be merged?
Hopefully, @davidlange6 can go over / merge them.

**Comment by grzanka** [comment]
I think all dependent tests are merged now. 
@dmitrijus @slava77 
Could you please run tests again ?

**Comment by slava77** [comment]
Is this PR affected by the QT-related discussion?
https://github.com/cms-sw/cmssw/pull/14034#issuecomment-222925352

**Comment by slava77** [comment]
@cmsbuild please test
#14630 is in CMSSW_8_0_X_2016-05-31-2300 which is available for tests now

**Comment by dmitrijus** [comment]
yes, it is

**Comment by grzanka** [comment]
@davidlange6 could you please merge it ?
original PR #14696 is already merged

**Comment by dmitrijus** [comment]
unhold

**Comment by dmitrijus** [comment]
Please merge, the QT dependency should be removed by a follow-up PR.

**Comment by davidlange6** [comment]
lets get the QT fix back port PR and then we can consider both together.
@grzanka

**Comment by grzanka** [comment]
Well, following PR (backport of #14836) contains commits with modification of the files in this PR.
In order not to mess up with moving files from one PR to another (which requires some time spend on compilation tests and verification) its better to merge them in a sequence (this one first, then backport of #14836). I can prepare backport today if this one is merged.

**Comment by davidlange6** [comment]
I'd rather not merge things into the production branch that we know have problems. Is there more to the work than cms-merge-topic-ing this PR,  cherry picking the 8 commits and seeing that they compile/run?

**Comment by grzanka** [comment]
If you mean to merge two PR (backport #14836 into one) then in fact its simpler solution. Do you agree to  cherry pick all commits from #14836 on top of this one and merge it as one backport of two PRs from 81X ?

**Comment by davidlange6** [comment]
yes. That would work for me.

**Comment by grzanka** [comment]
OK, I'll do it today.

**Comment by grzanka** [comment]
@davidlange6 @slava77  could you please cross-check ?

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
