### PR TITLE
Cleanup of HLT customization files moved into ConfDB menus (91X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Cleanup of HLT customization files moved into ConfDB menus (91X)
Based on CMSSW_9_1_X_2017-03-13-1100.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
Hi @Martin-Grunewald - please rebase. Thanks

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Rebase done!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Pull request merged**
