### PR TITLE
PUID UL18 backport to 11_2_X

### PR DESCRIPTION
**Pull request by singh-ramanpreet**
#### PR description:

- This PR is a backport to 11_2_X release.
- The original PR https://github.com/cms-sw/cmssw/pull/32418 is already merged to the master branch.

#### PR validation:

- passes basic tests
- need latest version of https://github.com/cms-data/RecoJets-JetProducers (`V05-13-00`) or for testing purposes, the PR can be used https://github.com/cms-data/RecoJets-JetProducers/pull/12

#### Re-miniAOD info

`_chsalgos_106X_UL17` is already the default.

From the discussion in 106X backport PR #32872, I have added below line, such that  `_chsalgos_106X_UL18` can be used with `run2_miniAOD_devel`. Please comment if that's not the case.

```diff
+ (run2_miniAOD_devel & (~run2_jme_2016) & (~run2_jme_2017)).toModify(pileupJetId, algos = _chsalgos_106X_UL18)
```

FYI: @alefisico @camclean @marinakolosova @mariadalfonso

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@singh-ramanpreet 

in 11_2 we do not have a miniAOD production for pp ongoing.
so I expect that the 11_2 backport is identical to the 11_3
(we do now have one for Heavy Ion that use a different modifier)

@slava77 can suggest how to proceed

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#6668

**Comment by slava77** [comment]
> @singh-ramanpreet
> 
> in 11_2 we do not have a miniAOD production for pp ongoing.
> so I expect that the 11_2 backport is identical to the 11_3
> (we do now have one for Heavy Ion that use a different modifier)
> 
> @slava77 can suggest how to proceed

this PR affects miniAOD made in production reco workflows; as I recall some of the Run3 requests are being prepared already.
So, changing the defaults will need some more justification.

I think that we can update the UL-modifier-based workflows in the same way as done in 11_3_X without falling back to the `_devel` modifier.

@qliphy @silviodonato 
do you think it's OK to change behavior of the UL remini workflows in 11_2_X?

**Comment by slava77** [comment]
> this PR affects miniAOD made in production reco workflows

I meant the 11_3/master PR does it

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> I think that we can update the UL-modifier-based workflows in the same way as done in 11_3_X without falling back to the `_devel` modifier.

@singh-ramanpreet 
@camclean @alefisico @lathomas 
are you somewhat motivated to have the UL reminiAOD workflows using the new PU ID in 11_2_X?
(If not, we could just move on with this limited backport using `run2_miniAOD_devel`)
Please clarify.

**Comment by lathomas** [comment]
@slava77  I don't think so.

**Comment by silviodonato** [comment]
> do you think it's OK to change behavior of the UL remini workflows in 11_2_X?

@slava77 no problem from my side

**Comment by perrotta** [comment]
backport of #32418

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32954	99442f1
- this is a partial backport from #32418 , staying in the constraints of the no-change policy/requirement for the production re-miniAOD setup
    - the PR is more of a forward-port of the 10_6_X #32872 than a backport of #32418 
    - cleanup of old configs is not backported 
    - more appropriate/improved 94X/80X/UL modifications are not applied to keep changes minimal
    - the new UL18 PU ID is made available via `run2_miniAOD_devel`, which can be added on top of the production miniAOD configuration for analysis or private tests
- tests pass and comparisons with the baseline show no (relevant) difference as expected

**Comment by slava77** [comment]
> @slava77 I don't think so.

Thanks for clarifying.
I've signed the PR.
I guess we can (re)consider having a UL setup in full after the 2016 variant is available as well.

**Comment by qliphy** [comment]
+1

**Pull request merged**
