### PR TITLE
[12.3.X] SiStripHitEfficiency workflow in the Prompt Calibration Loop 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a combined backport of PRs https://github.com/cms-sw/cmssw/pull/37530  and  #37708 and applies the necessary change-set to be able to run the strip hit efficiency analysis in the Prompt Calibration Loop, so that the creation of custom SiStrip calibration trees could be finally relinquished for Run-3.
I also updated various unit tests and relval workflows to be able to test the new addition.

#### PR validation:

I've run the following commands to test the `ALCAPROMPT` production:

```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiStripHitEfficiency --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Run2018D-SiStripCalMinBias-Express-v1/ALCARECO run=325172' --nThreads=4 --no_exec 
```

followed by:

```console
cmsDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiStripHitEfficiency.root -n -1 --no_exec                        
```
to test the `ALCAHARVESTING` step.
I have also run successfully:
   * `runTheMatrix.py -l 1001.0, 1001.2` 
   * `scram b runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of #37530, #37708

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable_test = threading
   * workflow_threading = 1001.0, 1001.2

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
@mmusich did the T0 replay test successfully complete? Also, are the difference in workflow 1001.0 understood?

**Comment by mmusich** [comment]
@emanueleusai 

> did the T0 replay test successfully complete

It did not happen yet, for lack of a pre-release containing the master PR (`CMSSW_12_4_0_pre3` is not yet out).

> Also, are the difference in workflow 1001.0 understood?

Yes, according to the bot:

>The workflows 1001.0 have different files in step1_dasquery.log than the ones found in the baseline

(cf https://github.com/cms-sw/cmssw/pull/37826#issuecomment-1119059603)

**Comment by francescobrivio** [comment]
@emanueleusai @mmusich I just requested the replay in https://github.com/dmwm/T0/pull/4674

**Comment by mmusich** [comment]
let me tag also @mdelcourt and @robervalwalsh

**Comment by mmusich** [comment]
> I just requested the replay in https://github.com/dmwm/T0/pull/4674

thanks Francesco.

**Comment by mmusich** [comment]
unhold
   * tested successfully at Tier-0: https://github.com/dmwm/T0/pull/4674#issuecomment-1130585919

**Comment by emanueleusai** [comment]
+1

**Comment by kskovpen** [comment]
+pdmv

**Comment by tvami** [comment]
+alca
 * test pass at T0

**Comment by francescobrivio** [comment]
@cms-sw/upgrade-l2 cuold you take a look and sign this?

@perrotta @qliphy given the last minute LHC schedule we need to build a new 12_3_X with this PR asap, maybe you can consider merging this already?

**Comment by rappoccio** [comment]
urgent

**Comment by qliphy** [comment]
+operations

@cms-sw/upgrade-l2  Do you have any comment on this urgent PR?

**Comment by boudoul** [comment]
We perhaps do not need to merge  everything in emergency before next week collisions .... we will have within the next weeks other collisions where we can just simply have another datatking releases at the right pace... Merging in emergency in data taking releases has always proven to be a bad strategy ...

**Comment by mmusich** [comment]
> we will have within the next weeks other collisions where we can just simply have another datatking releases at the right pace... 

the earlier it goes in IBs, the more test air time it takes...

**Comment by francescobrivio** [comment]
Hi @boudoul I agree is not good to rush things, but this has been tested already in tier0 and the master PR(s) were merged more than 2 weeks ago, so they have been included in the IBs since a while now.
We are kind of on schedule based on what we discussed in the past 2 weeks (before change of plan from LHC), so I don't consider this an emergency merging,  but ORP has the final word of course.

**Comment by rappoccio** [comment]
From the PPD perspective we want this in. We should be able to deploy very quickly (today+tomorrow) before the weekend.

**Comment by perrotta** [comment]
This is a verbatim backport of PRs https://github.com/cms-sw/cmssw/pull/37530 and https://github.com/cms-sw/cmssw/pull/37708, both succesfully merged in master since some while already

I would be in favour of merging them in time for the 1100 IB, so that they can be tested in the IB this afternoon

**Comment by perrotta** [comment]
merge
- if we see (unexoected) issues in the IB, we can still revert it

**Comment by rappoccio** [comment]
Yes, also, we need to install a new release regardless... either 12.3.3 or 12.3.3_patch1.

**Comment by boudoul** [comment]
what I'm always worried is when we suddenly declared things urgent because we are about to get data, which triggered a sudden burst of + 1 to enter in the data taking release usually installed in prod few days after to take data... 
I believe we should just do at the right pace, think about the best moment/opportunity to merge and deploy without using the 'emergency' button too often . That said this particular PR  is probably good to go , i'm just commenting on the overall strategy .

**Comment by perrotta** [comment]
@smuzaffar is it possible to verify whether this PR actually enters the 1100 IB, even if merged at 10:57? (I don't know how strict the IB time schedule is...)

**Comment by rappoccio** [comment]
> what I'm always worried is when we suddenly declared things urgent because we are about to get data, which triggered a sudden burst of + 1 to enter in the data taking release usually installed in prod few days after to take data...
> I believe we should just do at the right pace, think about the best moment/opportunity to merge and deploy without using the 'emergency' button too often . That said this particular PR is probably good to go , i'm just commenting on the overall strategy .

The *original* overall strategy was to have this 2 weeks before collisions, but LHC decided that despite a global pandemic, difficulties adjusting travel, understaffed operations, and a holiday weekend, they were just going to shorten the schedule. But I digress hahaha.

**Comment by perrotta** [comment]
> > @smuzaffar is it possible to verify whether this PR actually enters the 1100 IB, even if merged at 10:57? (I don't know how strict the IB time schedule is...)
> 
> @perrotta , any merge happens before the IB hour should be part of IB as bot tags the last merge commit at IB hour ( e.g. in this case at 11h00). One can confirm this by going to the IB tag (once it is created) e.g. https://github.com/cms-sw/cmssw/commits/CMSSW_12_3_X_2022-05-19-1100 (normally happens at IB + 10mins)

Thank you @smuzaffar.
According to your link, it is confirmed that this PR will be in the 1100 IB, then: good!

**Pull request merged**
