### PR TITLE
[OPERATIONS] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
ping bot: bit should not auto sign `operations` on `tests-approved` if there is only `operations` category involved

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 can you please review and sign this? This is just a technical update

**Comment by smuzaffar** [comment]
@mandrenguyen , can you please review/sign this?
Note that for this PR bot did not auto sign `operations` (and `full-signed` label) as there are no other non-orp categories involved in this PR. Forsuch PRs you have to explicitly review and sign for `operations`

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
