### PR TITLE
Safer syntax for modifying the configuration parameters in g4SimHits_cfi.py

### PR DESCRIPTION
**Pull request by perrotta**
In #36506 some partial migration to a safer syntax for modifying the configuration parameters in g4SimHits_cfi.py was started, which avoids overwriting types of those parameters or mis-naming them.

In order not to let the work half done, here are the remaining updates for the other non-migrated parameter updates in the same config

#### PR validation:

The short matrix runs without error.
Unless I made some trivial mistake in it, no changes are expected anywhere in the test outputs.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by bsunanda** [comment]
Why do you change TimeSliceUnit = 0.00 shouldn't it be TimeSliceUnit = 0.001

**Comment by perrotta** [comment]
> Why do you change TimeSliceUnit = 0.00 shouldn't it be TimeSliceUnit = 0.001

Thank you Sunanda: this is exactly what I meant for "trivial mistake" in the PR description...

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
@perrotta , thanks, I was not sure that you are on-line, so make extra PR  - it will be closed.

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Let have it merged before the 1100 IB, and see if the instabilities reported in #35109 disappear in test starting from tomorrow
- @cms-sw/ctpps-dpg-l2 please take note that LHC transport has been temporarily disabled here: it will be re-enabled once issue #36544 will have a solution

**Comment by perrotta** [comment]
merge

**Pull request merged**
