### PR TITLE
Make duplicate branch check work properly with SwitchProducer that has EDAlias case

### LINKED ISSUE #40110: Segmentation violation in all DQM online clients during HI run
We are observing DQM Online clients crashing with following segmentation violation (this is for the csc client: https://cmsweb.cern.ch/dqm/dqm-square/tmp/tmp/content_parser_productionPARSER_run362293PARSER_job28.log but all other clients show the same behavior):

Fri Nov 18 16:45:38 CET 2022
Thread 3 (Thread 0x7fbb53f1f700 (LWP 43397) "cmsRun"):
#0  0x00007fbb76b96b43 in select () from /lib64/libc.so.6
#1  0x00007fbb6f4f9a92 in lat::IOSelectSelect::wait(long) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/slc7_amd64_gcc10/lib/libclasslib.so
#2  0x00007fbb6f4fa55e in lat::IOSelector::wait(long) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/slc7_amd64_gcc10/lib/libclasslib.so
#3  0x00007fbb6f4fa318 in lat::IOSelector::dispatch(long) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/slc7_amd64_gcc10/lib/libclasslib.so
#4  0x00007fbb71379626 in DQMNet::run() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libDQMServicesCore.so
#5  0x00007fbb7137a0bc in communicate(void*) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libDQMServicesCore.so
#6  0x00007fbb76e76ea5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fbb76b9fb0d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7fbb549f5700 (LWP 43390) "cmsRun"):
#0  0x00007fbb76e7e1d9 in waitpid () from /lib64/libpthread.so.0
#1  0x00007fbb6fcd3567 in edm::service::cmssw_stacktrace_fork() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00007fbb6fcd40da in edm::service::InitRootHandlers::stacktraceHelperThread() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00007fbb77476f90 in std::execute_native_thread_routine (__p=0x7fbb704d0030) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#4  0x00007fbb76e76ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fbb76b9fb0d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7fbb74cf1740 (LWP 43345) "cmsRun"):
#0  0x00007fbb76b94ddd in poll () from /lib64/libc.so.6
#1  0x00007fbb6fcd381f in full_read.constprop () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00007fbb6fcd41ac in edm::service::InitRootHandlers::stacktraceFromThread() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00007fbb6fcd6afb in sig_dostack_then_abort () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000000000000000 in ?? ()
#6  0x00007fbb794a8347 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#7  0x00007fbb795863d6 in edm::DataManagingProductResolver::resetProductData_(bool) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#8  0x00007fbb795720a8 in edm::Principal::clearPrincipal() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#9  0x00007fbb794bcdcd in edm::EventPrincipal::clearEventPrincipal() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#10 0x00007fbb794c425e in edm::FunctorWaitingTask<edm::waiting_task::detail::WaitingTaskChain<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#4}>, edm::waiting_task::detail::Conditional<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#3}> >, edm::waiting_task::detail::Conditional<edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#2}> >, edm::waiting_task::detail::AutoExceptionHandler<edm::EventProcessor::processEventAsyncImpl(edm::WaitingTaskHolder, unsigned int)::{lambda(auto:1)#1}> >::runLast(edm::WaitingTaskHolder)::{lambda(std::__exception_ptr::exception_ptr const*)#1}>::execute() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#11 0x00007fbb794a293f in tbb::detail::d1::function_task<edm::WaitingTaskHolder::doneWaiting(std::__exception_ptr::exception_ptr)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#12 0x00007fbb77c78bec in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x7fbb74362d00, this=0x7fbb7438f700) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.h:322
#13 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x7fbb7438f700) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.h:463
#14 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/task_dispatcher.cpp:168
#15 0x00007fbb794e1ffd in edm::FinalWaitingTask::wait() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#16 0x00007fbb794cd98c in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#17 0x00007fbb794d8d53 in edm::EventProcessor::runToCompletion() () from /opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_2/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#18 0x000000000040a266 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const ()
#19 0x00007fbb77c670eb in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_5_0_pre4-slc7_amd64_gcc10/build/CMSSW_12_5_0_pre4-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.5.0-3cd580209e999b2fb4f8344347204353/tbb-v2021.5.0/src/tbb/arena.cpp:698
#20 0x000000000040b094 in main::{lambda()#1}::operator()() const ()
#21 0x000000000040971c in main ()

Current Modules:

Module: none (crashed)

A fatal system signal has occurred: segmentation violation

-- process exit: -11 --

The crash seems to be due to DQMNet, but we don't have any clue to debug it.
Could cmssw experts have a look and give us suggestions if possible?

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

#40110 demonstrated that the OutputModule's duplicate branch check for EDAliases did not work properly when  a SwitchProducer had an EDAlias case. The problem was that the SwitchProducer-EDAlias' alias-for `BranchID` was not inserted into the `trueBranchIDToKeptBranchDesc`, and therefore the check threw an exception only if the non-SwitchProducer-EDAlias duplicate entry was earlier in the map. This PR fixes the check to use the proper alias-for `BranchID` for both normal and SwitchProducer EDAliases.

The first commit consolidates some of the SwitchProducer unit test configuration files to reduce copy paste.

Resolves #40110

#### PR validation:

Framework unit tests run. The example HLT configuration throws now the proper exception.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by missirol** [comment]
Looks like this will require a change in `HLTrigger_EventContent_cff` (either to the script that creates that cff, or to the inputs it uses).
https://github.com/cms-sw/cmssw/blob/08fcc8ea316517a0efe16e71521b9bf40192032a/HLTrigger/Configuration/python/HLTrigger_EventContent_cff.py#L528-L530
(cc: @Martin-Grunewald)

**Comment by Martin-Grunewald** [comment]
Is it enough to drop ```hltHbhereco``` but keeping both ```hltHbherecoLegacy``` and ```hltHbherecoFromGPU```?

**Comment by missirol** [comment]
> Is it enough to drop `hltHbhereco` but keeping both `hltHbherecoLegacy` and `hltHbherecoFromGPU`?

I think it would solve this problem, but I think `hltHbhereco` is needed downstream, for example by DQM modules in RelVal wfs (e.g. `HcalRecHitsValidation` in `step3` of wf `11634.0`; although that client might just silently not fill histograms if the collection is missing, as opposed to throwing an exception).

On the HLT side:
 - It looks like we would have to manually `drop` some of these collections when we make the `cff` (as opposed to changing online EventContents in ConfDB, where `hltHbhereco` is required by the `DQM` stream (and others), and the other two collections are needed in the `DQMGPUvsCPU` stream). The alternative would be to [remove the `DQMGPUvsCPU` EventContent from HLTDebugRAW/FEVT](https://github.com/cms-sw/cmssw/blob/0bcb76f9a362ebc1fa23a8d3aa995a4bfe93bfc3/HLTrigger/Configuration/test/getEventContent.py#L177-L190), but I think we discussed in the past that it should be in there.

More on the sw side:

 - I don't understand why we didn't see an issue like #40110 when using `FEVTDEBUGHLT` files produced so far, where we were keeping both `hltHbhereco` and `hltHbherecoLegacy / hltHbherecoFromGPU`, e.g. `step2` of wf `11634.0`.

 - For the future, should we live with this limitation, or are improvements possible? I'm thinking about two files of one MC sample, one file produced on CPU and the other on GPU, and a user having to consume `hltHbherecoLegacy` in one case and `hltHbherecoFromGPU` in the other (assuming we have to `drop hltHbhereco`), whereas the user would just consume `hltHbhereco` instead.
 
Tagging @fwyzard in case he has opinions/suggestions/clarifications, since this involves HLT and GPUs.

**Comment by makortel** [comment]
> * I don't understand why we didn't see an issue like [Segmentation violation in all DQM online clients during HI run #40110](https://github.com/cms-sw/cmssw/issues/40110) when using `FEVTDEBUGHLT` files produced so far, where we were keeping both `hltHbhereco` and `hltHbherecoLegacy / hltHbherecoFromGPU`, e.g. `step2` of wf `11634.0`.

This is a good question. I see the step3 of workflow 11634.0 consumes only `hltHbhereco`. But also a specific test reading both `hltHbhereco` and `hltHbherecoLegacy` from a ROOT file succeeded. It could be that there is something in the ROOT output/input that allows the setup to work in some situations. 

> * For the future, should we live with this limitation, or are improvements possible? I'm thinking about two files of one MC sample, one file produced on CPU and the other on GPU, and a user having to consume `hltHbherecoLegacy` in one case and `hltHbherecoFromGPU` in the other (assuming we have to `drop hltHbhereco`), whereas the user would just consume `hltHbhereco` instead.

This limitation is intended behavior (since the introduction of EDAlias a decade ago), because otherwise we'd get to issues like seen in #40110. A high-level premise has been that it doesn't make sense to store both alias and alias-for products (what would be the point of the alias?).

It seems to me we're mixing two different use cases into one
* Portable: can be run with or without a GPU, output product has always the same label (`hltHbhereco`), downstream consumers don't (have to) care if the product was produced with or without a GPU
* Non-portable: must be run with a GPU, separate module labels for the CPU and GPU modules (`hltHbherecoLegacy` vs `hltHbherecoFromGPU`), consumers must be explicitly aware

I think it would be better to deal with these use cases separately with separate files.

**Comment by missirol** [comment]
> I think it would be better to deal with these use cases separately with separate files.

Thanks for clarifying. I would say this goes in the direction of keeping `hltHbhereco` in the existing tiers (e.g. `FEVTDEBUGHLT`), removing the `DQMGPUvsCPU` EventContent from them. If so, the update of `HLT_EventContent_cff` to unstuck this PR can be done by the end of the week.

We would then have to come up with a separate offline event content for wfs dedicated to GPU-vs-CPU comparisons. In a way, this is similar to what is already done online, where different clients are fed by different streams (e.g. `DQM` with `hltHbhereco`, and `DQMGPUvsCPU` with the explicit CPU/GPU products).

**Comment by missirol** [comment]
please test with #40153

**Comment by missirol** [comment]
> I see the step3 of workflow `11634.0` consumes only `hltHbhereco`.

Just for the record, step3 of wf `11634.0` also runs a [`GlobalRecHitsAnalyzer`](https://github.com/cms-sw/cmssw/blob/f53aee7e6564070c49a00089bc30e2811f468ee4/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc#L31) which consumed both `hltHbhereco` and `hltHbherecoLegacy` (on CPU), see https://github.com/cms-sw/cmssw/pull/40155#issuecomment-1328026871.

**Comment by makortel** [comment]
> > I see the step3 of workflow `11634.0` consumes only `hltHbhereco`.
> 
> Just for the record, step3 of wf `11634.0` also runs a [`GlobalRecHitsAnalyzer`](https://github.com/cms-sw/cmssw/blob/f53aee7e6564070c49a00089bc30e2811f468ee4/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc#L31) which consumed both `hltHbhereco` and `hltHbherecoLegacy` (on CPU), see [#40155 (comment)](https://github.com/cms-sw/cmssw/pull/40155#issuecomment-1328026871).

Thanks @missirol. I was relying on the output of `Tracer` service with `dumpPathsAndConsumes=True`, and apparently that doesn't include `consumesMany`.

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
