### PR TITLE
Phase2-hgx255A Remove magic number usage in 2 Algos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove magic number usage in 2 Algos

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
