### PR TITLE
Fix to Online Forward Pixel maps

### PR DESCRIPTION
**Pull request by arossi83**
Fix to bug which prevent to reset FPix Cluster Position maps every 10LS in Online

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@arossi83 does this code run only inn online?

**Comment by arossi83** [comment]
@andrius-k the changes made affect only online, the code run on both online and offline but on offline those particular lines are not processed.

**Comment by andrius-k** [comment]
@arossi83 ok, cool. Let's wait for this PR to be tested in playback validation.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
