### PR TITLE
limit the number of seeds, same as in CkfTrackCandidateMakerBase (backport of #38926)

### PR DESCRIPTION
**Pull request by slava77**
this is a follow up to https://cms-talk.web.cern.ch/t/high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met/13471/5

this PR introduces a limit on the number of seeds acceptable for mkFit processing at 500K (same as in CkfTrackCandidateMakerBase)

In the problematic event of the MET PD there were 2969225 seeds in the pixelLess iteration

### CODE REVIEW

**Comment by slava77** [comment]
backport of #38926

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent
   * presumably needed for the next patch of 12.4.x

**Comment by clacaputo** [comment]
+reconstruction

- backport #38926
- follow up to [high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met](https://cms-talk.web.cern.ch/t/high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met/13471/5)
- max number of seeds in MkFit limited as in CkfTrackCandidateMakerBase

**Comment by qliphy** [comment]
+1

**Pull request merged**
