### PR TITLE
Phase2-gex06 Correct the scenarios for D57/D58/D59 by removing overlaps

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the scenarios for 2026D57/D58/D59 by removing overlaps

#### PR validation:

Tested using runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@kpedro88 @cvuosalo Could you approve this?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 @silviodonato It will be nice to have it integrated soon so that I can make the new scenario for V14 geometry of HGCal

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
