### PR TITLE
[9_2_13] OnlineDQM : Tune L1T Muon QTs v4

### PR DESCRIPTION
**Pull request by stahlleiton**
CMSSW_9_2_13 Backport of https://github.com/cms-sw/cmssw/pull/21064
To be used for DQM Tag Collector

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
backport of #21064

**Comment by thomreis** [comment]
Hi @stahlleiton 
Data taking with 92x has finished. This can be closed.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
