### PR TITLE
Add Phase 2 Trackers T21 + T22 + T23 (Mechanical Update in Outer Tracker + Sensors studies in Inner Tracker)

### PR DESCRIPTION
**Pull request by ghugo83**
**PR description:**

This PR:
- Introduces a Tracker baseline, called T21. It has a Phase 2 Outer Tracker with updated TBPS (changes in Layer 1 to facilitate IT insertion) and TEDD (update sensors Z inter-spacing in all TEDD).
- Introduces T22, a Tracker based on T21, but with 50x50 um2 pixels everywhere in Inner Tracker.
- Introduces T23, a Tracker based on T21, but with 3D sensors in TBPX L1 + TBPX L2 + TFPX R1.

**T21:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T21/OT800_IT615/layoutpixel.html  
Geometry scenario: 2026D63.
Workflows: 294xx (no PU), 296xx (PU).

**T22:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T22/OT800_IT621/layoutpixel.html 
Geometry scenario: 2026D64.
Workflows: 298xx (no PU), 300xx (PU).

**T23:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T23/OT800_IT700/layoutpixel.html
Geometry scenario: 2026D65.
Workflows: 302xx (no PU), 304xx (PU).

Following comparisons should be made:
### **Validate new Outer Tracker:** 
_Compare T21 versus T20 (_2026D63 versus 2026D56_)._
Should not expect any meaningful change in the tracking performance (maybe an extremely tiny degradation).

### **Inner Tracker sensors studies:** 
Now have a common base to compare different sensors options.
Only bricked pixels sensors option is missing (I included that geometry in another private branch).

**25x100 -> 50x50:** 
_Compare T22 (50x50, planar) versus T21 (25x100, planar) (_2026D64 versus 2026D63_)._
An interesting fast sim estimate is available at:
25x100: http://ghugo.web.cern.ch/ghugo/layouts/T21/OT800_IT615/errorstracker.html 
50x50: http://ghugo.web.cern.ch/ghugo/layouts/T22/OT800_IT621/errorstracker.html 
With obviously, especially visible here at high pT, a significant degradation of pT and transverse impact parameter resolution, and an improvement of longitudinal impact parameter resolution. Of course less visible at low pT (multiple scattering).

**planar -> 3D:** 
Compare T23 (3D) versus T21 (planar) (_2026D65 versus 2026D63_).
tkLayout track parameters code fully debugged and operational in the case of 3D sensors. 
Though, would need to fix 3D local resolution parametrization used as input in tkLayout, to get meaningful fast sim results on that front as well.

**PR validation:**
Following was done for CMSSW validation:
- Checked XMLs make sense from Tracker design point of view, in concordance with Mechanics.
- 0 overlap within full **'Tracker' volume**, checked with Fireworks + Geant4 tools, for the 3 Tracker geometries.
- Checked workflow numbering.
- Checked that workflows with D63, D64, D65 scenarios run smoothly with no extra error / warning.

FYI: @dpiparo @VinInn @cvuosalo @civanch @ianna @emiglior @skinnari @mmusich  @jalimena @fabiocos @kpedro88

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
  * workflows =  29434.0, 29834.0, 30234.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
There's a segfault in tracker DQM:
```
#5  0x00002b5c58b202df in OuterTrackerMCHarvester::dqmEndJob(dqm::implementation::IBooker&, dqm::implementation::IGetter&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-07-29-2300/lib/slc7_amd64_gcc820/pluginValidationSiOuterTrackerVAuto.so
```

**Comment by ghugo83** [comment]
That s the scenario with Tracker with 3D sensors. step4 was running properly on this geo scenario on CMSSW_11_2_X_2020-07-27-1100 though, so not sure it is related to this PR.
Trying to isolate a commit since then.

**Comment by cvuosalo** [comment]
This problem might be fixed by #30963, which was recently merged.

**Comment by ghugo83** [comment]
@cvuosalo No unfortunately that is not possible, because #30963 fixes O4, while the 3 geo scenarios load O5.

**Comment by ghugo83** [comment]
This error is very tricky to solve, why would OuterTrackerMCHarvester only fail for D65, and not D62 and D63, while these 3 scenarios load the exact same Outer Tracker?
Additionally, D65 step4 run fully when both Marco and me tested it on slightly older releases.
My bet is that this issue is independent from this PR, there must have been a commit accepted into master in the last days, which somehow now makes D65 step 4 fail.

**Comment by ghugo83** [comment]
Tracking it down, the randomness of this seems to come from overlaps in CMS (notably here, MuonYoke) which introduce UB, and random crash.
This specific issue at step 4 on D65, appears with recently merged https://github.com/cms-sw/cmssw/commit/d05f8ec3ed7e1dc0ed3c25d09e9680367f77db17 . Reverting this commit makes D65 step4 to run smoothly.

**Comment by ghugo83** [comment]
Just base the 3 geo scenarios on Muon4 instead of M6, as we do not really care about M6 anyway.

In general, there seem to be major overlaps issues in other subdetectors in CMS, leading to UB and random crashes.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@bsunanda please be aware of possible overlaps in the newer muon geometries as pointed out here

**Comment by ghugo83** [comment]
On a more general note: why not having the **policy** of only accepting any new geometry (ending up in official CMSSW geometry scenario / workflow, not the ones for tests obviously) IF it has 0 overlap?

**Comment by ghugo83** [comment]
NB: While doing all these tests for tracking back the issue, it seemed to me that there might be a correlation between overlaps in CMS and issues in vertex finding of type:
```
%MSG-w TwoTrackMinimumDistance:   InclusiveCandidateVertexFinder:inclusiveCandidateVertexFinderCvsL  31-Jul-2020 19:30:28 CEST Run: 1 Event: 1
comparing track with itself!
%MSG
%MSG-w TwoTrackMinimumDistance:   InclusiveCandidateVertexFinder:inclusiveCandidateVertexFinderCvsL  31-Jul-2020 19:30:28 CEST Run: 1 Event: 1
Computation HelixHelix::CAIR failed.
%MSG
```
This appears in many existing scenarios.

**Comment by kpedro88** [comment]
@ghugo83 those errors have appeared since time immemorial, see #21718

Unfortunately I'm not sure if there's an automated way to detect 100% of overlaps. Maybe @ianna @bsunanda @cvuosalo can provide their thoughts.

**Comment by bsunanda** [comment]
Overlap matters only during simulation - so the best tool to check overlaps is the geant4 built in tool which produces points on the surface and checks if it is overlapping with other volumes in some tolerance. Now the tolerance level is the one which we should define. I believe it should be between 10 and 100 micron and not smaller. Smaller level of tolerance leads to finding overlap caused by precision of computation which happens more in rotating solids.

**Comment by kpedro88** [comment]
Would it be possible to add an overlap unit test with some moderate tolerance?

**Comment by mmusich** [comment]
> Would it be possible to add an overlap unit test with some moderate tolerance?

Shall this be rather discussed in a geometry-assigned cmssw issue?

**Comment by kpedro88** [comment]
opened #31010

**Comment by ghugo83** [comment]
> @ghugo83 those errors have appeared since time immemorial, see #21718
Yes, but now we have a plausible explanation :) The fact that these errors have been there for a while actually make it... more problematic, not less ;)

> Overlap matters only during simulation
Hmm unfortunately I don't think so. The steps downstream rely on the assumption that the geometry has no overlap. I think the overlaps can very well affect the tracking. Though should not be visible in the tracking results, as anyway the number of 'trapped' tracks should be extremely small, relatively speaking. 
But still, situation definitely not very clean as it is now ;p

>Shall this be rather discussed in a geometry-assigned cmssw issue?
Perfect, thanks @kpedro88

**Comment by cvuosalo** [comment]
Please base your `Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026*xml` files on PR #30963. The ordering of the XML files needs to be correct or else there can be XML parsing errors.

**Comment by cvuosalo** [comment]
Why are elementary materials defined in `Geometry/TrackerCommonData/data/PhaseII/OuterTracker800_2020_07/tracker.xml`? We have standardized elementary materials in `Geometry/CMSCommonData/data/materials/2021/v1/materials.xml`. Is there some reason this file can't be used?

**Comment by ghugo83** [comment]
> Please base your `Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026*xml` files on PR #30963. The ordering of the XML files needs to be correct or else there can be XML parsing errors.

Hmm but PR #30963 fixes O4 only. This PR scenarios only load O5, hence merging it has no effect here on these geo files (I had tried on my local, and it did not change anything, also in the issues). But can do if you want.

**Comment by cvuosalo** [comment]
@ghugo83 Sorry, I didn't explain my request. In the list of XML files, `cavern.xml` has to come after several other files. You need to make the ordering of the XML files in your cmsExtendedGeometry2026*xml files match the ordering in the similar files in #30963. That PR provides the template for your new files.

**Comment by ghugo83** [comment]
Ok sure. Shall I do the reordering of the O detector cavern files in O5 in the dictionary? If so, do I re-write the other geometry scenarios which load O5?

**Comment by ghugo83** [comment]
> Why are elementary materials defined in `Geometry/TrackerCommonData/data/PhaseII/OuterTracker800_2020_07/tracker.xml`? We have standardized elementary materials in `Geometry/CMSCommonData/data/materials/2021/v1/materials.xml`. Is there some reason this file can't be used?

Yes that's kind of an historical reason, more for consistency. Also because that's the list of the elementary materials as used by tkLayout for all the materials descriptions. I can see discrepancies in the densities, for example we have C density of 2.267 g/cm3 in tkLayout and of 2.0 g/cm3 in https://github.com/cms-sw/cmssw/blob/master/Geometry/CMSCommonData/data/materials/2021/v1/materials.xml.

**Comment by kpedro88** [comment]
@ianna @cvuosalo I didn't realize that the problem in #30963 also existed in other Phase 2 geometries.

@ghugo83 indeed any change to a subdetector must be propagated to all detector geometries that use that subdetector. It really should have been handled in the other PR, but if you could take care of it here, that would be great.

**Comment by cvuosalo** [comment]
For the elementary materials, if we could settle on one standardized list of the chemical elements, instead of each sub-detector having their own versions of each element, that would be good.

**Comment by cvuosalo** [comment]
@kpedro88 Anywhere there is a list of geometry XML files, where the files depend on each other, the list must be in order such that shapes are defined before they are referenced.

**Comment by ghugo83** [comment]
> For the elementary materials, if we could settle on one standardized list of the chemical elements, instead of each sub-detector having their own versions of each element, that would be good. 

I fully agree in theory. In practice, it is not that simple, as updating densities in the elementary materials in tkLayout implies cross-checking and updating several hundreds of cfg files.
That is a lot of time, for saving up a few lines on top of https://raw.githubusercontent.com/cms-sw/cmssw/3d36a2c2f6aa4a993ca61ac4f0b659b779b4ed75/Geometry/TrackerCommonData/data/PhaseII/OuterTracker800_2020_07/tracker.xml

**Comment by ghugo83** [comment]
Just did the file ordering fix on O5, propagated to all scenarios.
This is fully independent from the issue which was encountered at step4 though. The O5 fix does not fix the step4 issue, which is due to overlaps UB situation (you can check by only adding the O5 fix).
In theory, fix to O5 should also be done in O6 and O7, but in another PR, as this is going too out of scope.

**Comment by kpedro88** [comment]
> In theory, fix to O5 should also be done in O6 and O7, but in another PR, as this is going too out of scope.

@cvuosalo @ianna can geometry take responsibility for this? if not, I will try to do it next week.

**Comment by kpedro88** [comment]
please test

**Comment by fabiocos** [comment]
@ghugo83 @cvuosalo @kpedro88 concerning ETL overlaps: my G4 checks show no issue in either D49 or D60. There are indeed issues in D59 for instance:

```
%MSG-w SimG4CoreApplication:  (NoModuleName) 03-Aug-2020 10:03:36 CEST  pre-events

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with mother volume !
          Overlap is detected for volume Disc1Timing:1 (G4Tubs)
          with its mother volume EndcapTimingLayer (G4Polycone)
          at mother local point (114.859,-250.429,-13.52), overlapping by at least: 4.48703 mm 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

%MSG
%MSG-w SimG4CoreApplication:  (NoModuleName) 03-Aug-2020 10:03:46 CEST  pre-events

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with mother volume !
          Overlap is detected for volume serviceR264Z2666:1 (G4Tubs)
          with its mother volume EndcapTimingLayer (G4Polycone)
          at mother local point (170.113,-209.398,17.65), overlapping by at least: 1.02109 cm 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

%MSG
```

which are likely du to the use of the old ETL in the newer envelope. The problem is that the new ETL drawing (D53, and another one in preparation) cannot be used at tracking level because of ```RecoMTD/DetLayers```, which need to be adapted. This is my work in progress now, see https://github.com/fabiocos/cmssw/commits/fc-mtd-detlayers2

**Comment by ghugo83** [comment]
> Just base the 3 geo scenarios on Muon4 instead of M6, as we do not really care about M6 anyway for this specific study.
> 
> **In general, there seems to be major overlaps issues in CMS (several subdetectors), leading to UB and random crashes.**
> There are geo scenarios with overlaps within the ETL, caloBase, muonBase volumes...

@fabiocos Yep that the ones i mentioned here.
Yep if you could fix them asap would be great :)

**Comment by cvuosalo** [comment]
@ghugo83 Concerning the elementary materials: It sounds like enforcing a consistent properties for elementary materials is a large project on its own and out of the scope of this PR.

**Comment by cvuosalo** [comment]
@kpedro88 If you can fix O5 and O6 this week, that is probably sooner than Yana or I could get to it. Is the fix you're talking about the ordering of the XML files with regards to `cavern.xml`?

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@cvuosalo yes, that's the fix I'm talking about

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@cvuosalo @kpedro88 @ianna I can fix O5, O6

**Comment by kpedro88** [comment]
@bsunanda that would be great, thanks!

**Comment by ghugo83** [comment]
> @cvuosalo @kpedro88 @ianna I can fix O5, O6
@bsunanda O6 and O7. 
O5 files dictionary was fixed at #30963, and O6 here.

**Comment by ghugo83** [comment]
> @ghugo83 Concerning the elementary materials: It sounds like enforcing a consistent properties for elementary materials is a large project on its own and out of the scope of this PR.

Yes exactly. Also that would just save up a few lines, with risks of regressions, and that file will for sure still exist in tkLayout anyway. Time would be much better invested updating cfg files for the description itself (but that's cumbersome), impacting the Material Budget results.

**Comment by bsunanda** [comment]
@kpedro88 @ghugo83 @cvuosalo @ianna I shall wait till this PR is merged

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
do you have any comments @cms-sw/alca-l2 @cms-sw/l1-l2 ?

**Comment by tlampen** [comment]
+1

**Comment by bsunanda** [comment]
@silviodonato Can this PR be merged - I am waiting for this to update some of the Ox parts of Phase2 scenarios

**Comment by silviodonato** [comment]
merge

**Pull request merged**
