### PR TITLE
Complete the migration from PhysicsTools/CandUtils

### PR DESCRIPTION
**Pull request by perrotta**
As pointed out in the issue #22483 , nearly all classes "migrated" by https://github.com/cms-sw/cmssw/commit/60bfee78c7f19dad49a76e2511f07f3af5969aea have still a copy in PhysicsTools/CandUtils

Code in CMSSW accessed either one or the other implementation, with the same name and often also with the definition in the interface protected by an identical include guard

This PR removes all the duplicate implementations that were left in ```PhysicsTools/CandUtils```, and adapts the classes that still relied on them to use the same (identical) implementations that were migrated longtime ago in ```CommonTools/CandUtils```

@steggema @makortel @rekovic @roger-wolf @slava77

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by rekovic** [comment]
@perrotta Thanks very much for this PR. 
Would it be possible to have this PR back-ported to 9_3_X?  
We should probably do it for 10_0_X as well.

**Comment by perrotta** [comment]
Let see the comparisons in jenkins first

Ok for 93X.
I don't think it will be needed in 10_0, however: what usage you have  
in mind for it?

rekovic <notifications@github.com> ha scritto:

**Comment by rekovic** [comment]
>Ok for 93X.

Great. Thanks.

> I don't think it will be needed in 10_0, however: what usage you have
in mind for it?

Was not sure if anybody was planning to do any MC production or major Re-RECO where this would
come up.  I have to admit that the only place that I am aware of where this was causing seg faults
were Phase-II workflows.  Maybe there are others around the corner, so out of precaution thought it
would be a good idea.

**Comment by rekovic** [comment]
Jenkins comparisons show no difference.  Good!

@perrotta, @cmsbuild, @silviodonato, @fwyzard, @monttj, @Martin-Grunewald, @slava77, @gpetruc, @arizzi can you please review it and eventually sign? 

Need a backport of it asap in 93x.

**Comment by perrotta** [comment]
+1
- Duplicated classes in PhysicsTools/CandUtils are been removed, and all code in CMSSW that still accessed them gets modified accordingly
- No effect is expected in reco outputs, none is observed in jenkins tests

**Comment by perrotta** [comment]
@rekovic : backport for 93X in #22588

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by rekovic** [comment]
@perrotta, @Martin-Grunewald @fabiocos 
Thanks.

>backport for 93X in #22588

OK. Thanks.

**Pull request merged**
