### PR TITLE
fix inner outer for OutIn in 75X

### PR DESCRIPTION
**Pull request by VinInn**
backport #11089

### CODE REVIEW

**Comment by VinInn** [comment]
@arizzi @makortel 
here it is

**Comment by VinInn** [comment]
@slava77 @davidlange6 
shall we fix 74X as well or we leave it buggy but consistent with everything produced so far?

**Comment by arizzi** [comment]
I'd leave it buggy so that we can deploy a MINIAOD level fix if we
re-miniaod in 74X.

**Comment by slava77** [comment]
@cmsbuild please test

In 74X we can update only what can be (re)run from AOD.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11096	a056dae
- the same changes as in 76X
- jenkins tests pass and comparisons with baseline show only an expected difference
    - no change in the monitored reco products with fwlite script
    - small (~1/10K tracks) change in the missing hit distribution in the packed candidate in 4.53 (as observed in 76X)
- not repeating higher stat tests from #11089 here; these should have the same behavior

**Comment by davidlange6** [comment]
+1

**Pull request merged**
