### PR TITLE
[DQM] Fix for bug in DT DQM at Online

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fixed bug in folder which had been renamed, the bug was affecting Online DQM only

Tested privately in Online mode

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
type bug

**Comment by emanueleusai** [comment]
type muon

**Comment by perrotta** [comment]
+1

**Pull request merged**
