### PR TITLE
Run4-hgx256 Make scenario/workflow for V14 HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make scenario (2026D62)  and workflow (29034.0) for V14 HGCal

#### PR validation:

Use runTheMatrix test workflow

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by kpedro88** [comment]
test parameters
workflow = 29034.0

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
do you have any comments @cms-sw/pdmv-l2 ?

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
See https://github.com/cms-sw/cmssw/issues/30980 (Segmentation violation in 2026D62 workflow (29034.0) )

**Pull request merged**
