### PR TITLE
Migrate some modules in RecoTracker to esConsumes()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061. These are fairly straightforward ones, and should cover the following modules
* `SeedingLayersEDProducer`
* `PixelInactiveAreaTrackingRegionsSeedingLayersProducer`
* `DeepCoreSeedGenerator`
* `OutsideInMuonSeeder`
* `SimpleCosmicBONSeeder`
* `cms::CosmicTrackFinder`
* `MeasurementTrackerEventProducer`

#### PR validation:

~~Code compiles.~~ Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Now limited matrix runs.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34934	71633d7
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
