### PR TITLE
Switching to full pulse nonlinearity for SiPMs

### PR DESCRIPTION
**Pull request by igv4321**
Changing TS-by-TS SiPM nonlinearity calculation to estimating the nonlinearity from the charge collected in the 3 time slices (almost full pulse). This treatment is consistent with what was done for calibrating the SiPM non-linearity so far in the lab. While eventually we will need to go back to correcting nonlinearity for individual time slices, we can not do so with the existing measurements and models.

For a detailed description of the problem, see the talks by Jim Hirschauer, Federico De Guio, and Pawel De Barbaro at https://indico.cern.ch/event/640431/

Please test and integrate asap, this fix is needed for the data taking.

### CODE REVIEW

**Comment by slava77** [comment]
@igv4321 
please point to the expected before and after response plots for this proposed change.
Also, please clarify if the effect is expected to be different in data and MC.
For data, it would be good to see a reference to test and compare.

Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@slava77 there will be a similar effect in both data and MC. The MC nonlinearity simulation does not exactly match the data, but they're close enough.

**Comment by igv4321** [comment]
It became obvious with splashes that the original treatment of SiPM nonlinearity is inconsistent with the nonlinearity calibrations in the lab. The algorithm (with a slightly different implementation) has been tested by Federico, see https://indico.cern.ch/event/640431/contributions/2597635/attachments/1462296/2259023/20170517_-_joint_DPGPhase1_meeting_on_HEP17.pdf

And yes, various relevant people are aware of the upcoming change.

**Comment by slava77** [comment]
On 5/19/17 1:57 PM, Igor Volobouev wrote:
> And yes, various relevant people are aware of the upcoming change.
> 

nobody mentioned anything HCAL related in the OPS meeting at 2PM Friday.

**Comment by slava77** [comment]
IIUC, this PR is pending discussion in (Wednesday?) HCAL meeting.

**Comment by deguio** [comment]
@slava77 correct.

**Comment by perrotta** [comment]
Any outcome on the discussion at the HCal meeting? Are there slides that can be linked?

**Comment by hatakeyamak** [comment]
We had discussions on this, and we are pending the test. The plan is to test the change in this PR with also another PR that should come for sipm+qie11 pulse shape for HEP17 using the splash with method 2.

The sipm+qie11 pulse shape is being measured at low energy and we don't include any energy dependence. If this performs acceptably at very high energies as in splash, we are happy to push this change forward. If everything goes well, we may hear the outcome of this test tomorrow.

**Comment by abdoulline** [comment]
In the meantime - MC test with 1 TeV pions

(1)  pions shot specifically at HEP17 wedge (1 out of 18 in HE+) 

ietapr18866_e1000

(2) pions shot at HE+ randomly 

a) iphi distribution in HE+
iphipr18866_e1000

b) ieta distribution (over all iphi's in HE+ )
energy scale change is diluted by factor 18:1 (one wedge out of 18)

ietapr18866_e1000_he

**Comment by deguio** [comment]
hi,
as mentioned at the orp here some cross check on splash data with M0 and M2 which are both affected by this fix. For M0 the cosmics reco was used (sum all 10TS with no containment correction).

[c1.pdf](https://github.com/cms-sw/cmssw/files/1039272/c1.pdf)
[c2.pdf](https://github.com/cms-sw/cmssw/files/1039275/c2.pdf)
[c3.pdf](https://github.com/cms-sw/cmssw/files/1039274/c3.pdf)
[c4.pdf](https://github.com/cms-sw/cmssw/files/1039273/c4.pdf)

Regions outside HEP17 are not affected.

**Comment by deguio** [comment]
btw. linearity fix in the legend is this PR

**Comment by perrotta** [comment]
+1
Visual inspection of the code shows no issues.
Performance plots provided for both MC and 2017 beam splash data confirm that the modifications (also visible in low stat jenkins tests) are according to the expectations

**Comment by slava77** [comment]
@davidlange6 
what was the reason that this PR was not included in CMSSW_9_2_1?

**Comment by davidlange6** [comment]
I thought its signoff was coming in the reco
Meeting. It's now agreed to have no effect on the pf calibrations?

Cheers,
David


On 1 Jun 2017, at 21:55, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6>
what was the reason that this PR was not included in CMSSW_9_2_1?

**Comment by deguio** [comment]
Hi,
we (HCAL) think that that the effect will be completely negligible on the PFCluster calibration.
I wrote to JetMet to ask their opinion. I will make sure they are informed about the reco meeting tomorrow.
F.

**Comment by slava77** [comment]
On 6/1/17 1:07 PM, David Lange wrote:
> I thought its signoff was coming in the reco
> Meeting.

OK, this is a clear enough reason.

> It's now agreed to have no effect on the pf calibrations?

pf calibrations are symmetric in phi and eta sign.
Also, the current approach uses Gaussian fits to derive calibration
parameters.

So, any changes in HEP17 will not be visible in the PF calibrations due
to the 1/36 suppression of its contribution. (even if the response is
wrong by an order of magnitude).

> 
> Cheers,
> David
> 
> 
> On 1 Jun 2017, at 21:55, Slava Krutelyov

**Comment by davidlange6** [comment]
Let's see if the symmetric calibrations is considered a bug or feature later....

**Pull request merged**
