### PR TITLE
L1T2016EMU is renamed to L1TEMU

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by dmitrijus** [comment]
Needs to be in development release first (91x), you know the drill :)

**Comment by thomreis** [comment]
@dmitrijus I think the 91x version should be merged already with #17818 and #18352 . @EsmaeelEskandari can you confirm?

**Comment by EsmaeelEskandari** [comment]
@thomreis  @dmitrijus : yes it is already mereged with #17818  and #18352. 
Also #18409 icludes the current PR #18043 ans we can close it if #18409 is going to be merrged.

**Comment by thomreis** [comment]
@EsmaeelEskandari this can be closed since it is fully contained in #18409 that is also deployed at P5.

**Comment by EsmaeelEskandari** [comment]
@thomreis : Thanks.

**Pull request closed without merging**
