### PR TITLE
[HGCAL] LayerClusters to SimTracksters associator

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR introduces an associator between LayerClusters and TICL SimTracksters.
Together with the Trackster-to-SimTrackster associator, it will be used to assess the TICL performance in building 3D Tracksters.
A usage example of the associator is provided [here](https://github.com/lecriste/cmssw/commit/b348c0f27e580cbd9d58724617eb232e90bbff16).
No changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by lecriste** [comment]
@cms-sw/upgrade-l2 can you please review this PR?

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
