### PR TITLE
Fix of the L1MenuWriter needed for the X2O procedure + update of the L1UpgradeTfMuonShowerTreeProducer

### PR DESCRIPTION
**Pull request by elfontan**
#### PR description:
This PR includes the update of two files:
- the L1MenuWriter that it is called when running the dumpMenu.py script to manually upload a new tag to condDB via X2O procedure. It was crashing because of an exception MustUseESGetToken;
- the L1UpgradeTfMuonShowerTreeProducer, previously updated for the deprecated usage of EDAnalyzer, was missing the corresponding updates to the destructor and to the usage of the SharedResources.

#### PR validation:
Basic tests performed successfully starting from CMSSW_12_3_0_pre4. 
From CMSSW_12_3_0_pre4/src:
> scram b distclean 
> git cms-checkdeps -a -A
> scram b -j 8
> scram b runtests
> scram build code-checks
> scram build code-format
> runTheMatrix.py -l limited -i all --ibeos

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Failed test possibly related to https://github.com/cms-sw/cmssw/issues/37017

**Comment by elfontan** [comment]
Thanks @Martin-Grunewald, 
is this something that I can check in someway?
The failure was completely unclear to me.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
