### PR TITLE
Migrate EcalBasicClusterLocalContCorrection to ESTokens

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

This PR is in the previous spirit as my previous PR https://github.com/cms-sw/cmssw/pull/32498.

After https://github.com/cms-sw/cmssw/pull/32424, the ES consumes migration of RecoEgamma plugins is still on my radar. On thing that makes the migration complicated is this factory pattern with functions inheriting from the `EcalClusterFunctionBaseClass`.

But before thinking of a solution for these ECAL cluster functions, maybe this this is a good opportunity to think about where this factory pattern is really needed to reduce the complexity of the migration a bit.

I spotted the `EcalBasicClusterLocalContCorrection`, which is only used once in the `EgammaSCCorrectionMaker`. It was and is never swapped with alternative corrector functions, so the factory pattern doesn't seem really necessary.

Hence, this PR suggests to turn `EcalBasicClusterLocalContCorrection` into a usual helper class that is migrated to the ESGetTokens.

#### PR validation:

CMSSW compiles, local matrix tests pass.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> I spotted the `EcalBasicClusterLocalContCorrection`, which is only used once in the `EgammaSCCorrectionMaker`. It was and is never swapped with alternative corrector functions, so the factory pattern doesn't seem really necessary.

@argiro @thomreis 
I see that the containment correction was added in 2012 
https://github.com/cms-sw/cmssw/commit/99d56bb91e7dab5a2da549cfe8d414971b29b476#diff-696350d1fddc99dad1cbbbd821194cd1baad25d8ab799cc384b04a8a1de523ba
and the method did not really evolve since then.
Should we expect that the factory pattern flexibility will be necessary to support different correction methods (like for phase-2 cases) or is this one OK to be migrated to a concrete type case as proposed in this PR?
Please advise.
Thank you.

**Comment by slava77** [comment]
> > I spotted the `EcalBasicClusterLocalContCorrection`, which is only used once in the `EgammaSCCorrectionMaker`. It was and is never swapped with alternative corrector functions, so the factory pattern doesn't seem really necessary.
> 
> @argiro @thomreis
> I see that the containment correction was added in 2012
> [99d56bb#diff-696350d1fddc99dad1cbbbd821194cd1baad25d8ab799cc384b04a8a1de523ba](https://github.com/cms-sw/cmssw/commit/99d56bb91e7dab5a2da549cfe8d414971b29b476#diff-696350d1fddc99dad1cbbbd821194cd1baad25d8ab799cc384b04a8a1de523ba)
> and the method did not really evolve since then.
> Should we expect that the factory pattern flexibility will be necessary to support different correction methods (like for phase-2 cases) or is this one OK to be migrated to a concrete type case as proposed in this PR?
> Please advise.
> Thank you.

ping

**Comment by thomreis** [comment]
I am not familiar with this corrections. @mdonega, @fcouderc, @simonepigazzini do you know if there are changes planned for phase-2?

**Comment by fcouderc** [comment]
I don't think we use these corrections anywhere. Since the end of run1, all the containment corrections are handled by the energy regression trained by egamma.

**Comment by thomreis** [comment]
So in this case the factory could be replaced with something simpler as proposed by Jonas.

**Comment by slava77** [comment]
> I don't think we use these corrections anywhere. Since the end of run1, all the containment corrections are handled by the energy regression trained by egamma.

Thank you for clarifying.
I will then sign off this PR shortly.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32588	a4a54ed 
- code changes are in line with the PR description; the simplification was OK'd by ECAL experts.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by silviodonato** [comment]
+1

**Pull request merged**
