### PR TITLE
Migrate Alignment Validation all-in-one meta-tool to be Py3 compliant

### LINKED ISSUE #28830: ConfigParser and Python3  in Alignment/OfflineValidation
@mmusich  @christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng 

The PR #28739 added a unit test crashing in Python3 because of `import ConfigParser` in Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py.
In Python3 "ConfigParser" has been renamed to "configparser". The minimal fix is to replace `import ConfigParser` with `import configparser as ConfigParser` (that is compatible also to Python2.7) (see #28822).
Unfortunately this fix does not work with betterConfigParser.  betterConfigParser uses an hacked version of dictionary (AdaptedDict https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py#L11-L57). The idea is that if we are parsing the `[validation]` section of the INI file, we fill a list (`validationslist`) instead of using a dictionary (`collections.OrderedDict`).
This check is performed looking at the variable `__name__` inside the dictionary (`self["__name__"]=="validation"`), but unfortunately this trick cannot work in Python3 because the  special key `__name__` has been removed (see https://stackoverflow.com/questions/47200088/when-and-why-has-been-name-magic-variable-removed-from-configparser-in).

I'm afraid the best solution is to change the format of the `[validation]` section in order to avoid repetitions. You can find a working quick&dirty example at https://github.com/cms-sw/cmssw/compare/master...silviodonato:AlCaValPy3

The migration to Python3 should complete in the next months, because the maintenance of Python2 ended on Jan 1, 2020.

### PR DESCRIPTION
**Pull request by mmusich**
resolves #28830 

#### PR description:
Title says it all.

#### PR validation:

Relies on existing unit tests (introduced in https://github.com/cms-sw/cmssw/pull/28739).
Tested functional both in `CMSSW_11_1_X_2020-01-30-2300` *and* `CMSSW_11_1_PY3_X_2020-01-30-2300` (requires https://github.com/cms-sw/cmssw/pull/28822 to be merged first, though).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

It is not a backport and no backport is meant as the failing unit test exists only in this release cycle.

### CODE REVIEW

**Comment by mmusich** [comment]
@christopheralanwest, @tocheng, @tlampen, @pohsun 
would it be possible to start integration tests here (using Py3)? 
I have more changes that are awaiting this to be merged.

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by silviodonato** [comment]
please test for CMSSW_11_1_PY3_X

**Comment by mmusich** [comment]
@silviodonato 
about https://github.com/cms-sw/cmssw/pull/28838#issuecomment-581504074

as I wrote in the header of this PR 

>  (requires #28822 to be merged first, though).

**Comment by mmusich** [comment]
re-phrasing the above, can someone who "has the power" do:

please test with #28822  for CMSSW_11_1_PY3_X

?

**Comment by silviodonato** [comment]
please test with #28822 for CMSSW_11_1_PY3_X

**Comment by christopheralanwest** [comment]
please test with #28822 for CMSSW_11_1_PY3_X

**Comment by christopheralanwest** [comment]
please test with #28822

I would like to check that the changes for python3 compatibility do not break python2 functionality.

**Comment by mmusich** [comment]
> I would like to check that the changes for python3 compatibility do not break python2 functionality.

@christopheralanwest, thanks for the additional test. I followed the recommend migration pattern https://python-future.org/compatible_idioms.html and I also think I've validated it in a standard build.

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1
thanks @mmusich for the fix

**Comment by silviodonato** [comment]
This is just to confirm that the tests in CMSSW_11_1_X_2020-02-04-2300 are ok `test testAlignmentOfflineValidation succeeded` both in
Python3
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_PY3_X_2020-02-04-2300/unitTestLogs/Alignment/OfflineValidation#/
Python2
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-02-04-2300/unitTestLogs/Alignment/OfflineValidation#/

**Pull request merged**
