### PR TITLE
Run3-gex65 Update EB to adjust overlaps: work for DDD, need more work for DD4Hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update EB to adjust overlaps: work for DDD, need more work for DD4Hep

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @qliphy @cvuosalo @srimanob Can this be included in the pre6?

**Comment by ianna** [comment]
+1

@bsunanda - I see you have included the `1 mm` adjustment for the `EcalBarrel` mother volume. Thanks!

**Comment by bsunanda** [comment]
@ianna Yes - that is important for both DDD and DD4Hep. I am waiting for the fix in dd4hep to check the numbering for EcalBarrel and your new code

**Comment by srimanob** [comment]
Urgent

**Comment by srimanob** [comment]
Hi @ianna @bsunanda 
This PR makes me question how do you plan for the near future development of DDD and DD4Hep for Run-3. As of now, we are validating them, so I expect that we should update both in the same PR, to avoid confusion on which one goes to which release/GT.

**Comment by bsunanda** [comment]
When we update a xml file, it automatically updates both DDD and DD4Hep scenario. If we fix an algorithm we see that the same algorithm for the other scenario is also corrected to the best of our knowledge. So each PR takes care of both DDD and DD4Hep
________________________________

**Comment by srimanob** [comment]
Thanks for the clarification @bsunanda . Then what is "need more work for DD4Hep" in the PR title?

**Comment by bsunanda** [comment]
Yes as mentioned in the SIM meeting, we still have to work on the algorithms for DD4Hep regarding Ecal Barrel and Preshower. Ianna's changes for EB removes overlaps for EB - but has issues for numbering scheme. Ianna is working with DD4Hep team to address this issue.

**Comment by srimanob** [comment]
+Upgrade

Thanks @bsunanda for the clarification.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
