### PR TITLE
Fixes to the global and limited output modules

### PR DESCRIPTION
**Pull request by wddgit**
These types of output modules had bugs in the code
related to use of the template parameters that could
add abilities. Also made changes to make the branchIDLists
function const. And added new unit tests.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Fixes #21727

**Comment by wddgit** [comment]
@Dr15Jones It probably should be addressed in a different pull request and maybe you are already working on this, but note that the RunCacheHolder and LuminosityBlockCacheHolder will not work when we go to multiple Runs and LuminosityBlocks running simultaneously because they only hold one  item. Also, the code in the new RunCacheHolder and LuminosityBlockCacheHolder is nearly identical to the code in global/implementors.h. I copied the existing file and class organization, but we might or might not want to reorganize this to reduce the duplication ...

**Comment by fabiocos** [comment]
@Dr15Jones Given the last remark above, do you confirm your signature and want to move forward with this PR anyway?

**Comment by Dr15Jones** [comment]
I confirm my signature

**Comment by fabiocos** [comment]
+1

@Dr15Jones thanks

**Pull request merged**
