### PR TITLE
[12_3_X] Fix for printouts with special (for python) chars

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38140
Fixes the  listing functions of `conddb` from command line.

#### PR validation:
Master PR is alredy integrated in CMSSW_12_5_0_pre2 and the `conddb` command works as expected.

#### Backport:
Backport of #38140

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
backport of #38140

**Comment by francescobrivio** [comment]
test parameters:

 - addpkg = CondTools

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db
 * problem is understood and unrelated

**Comment by perrotta** [comment]
+1

**Pull request merged**
