### PR TITLE
Backport - RPD in 80X

### PR DESCRIPTION
**Pull request by cferraio**
Backport of PR #16150 for RPD integration into 80X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #16150

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
A status  update for the review:
- waiting for resolution of the discussion in #16150 (it's not obvious yet that no changes will be necessary in the code)

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by mdhildreth** [comment]
+1

**Comment by abdoulline** [comment]
@slava77,  @davidlange6

I was told HCAL is now including "dummy" (yet without new FE QIE10 cards installed, until TS3) ZDC/RPD "QIE10" (via uTCA FEDs) in RAW. So we could try/validate extended emap with 80X, provided that this PR is merged.    
Would be god to have extended emap validated and included in 80X GTs in advance, even before pA preparatory period (a ~week right after TS3).

**Comment by cferraio** [comment]
update - pr #16150, identical to this PR in 81X, has merged. 

we have been working with a data file produced by Dick and Quan at 904, and the 904 emap produced by Dick. from what we can tell, everything is unpacking fine. we're now going to write an analyzer to produce easy to read histos of time slices, charge, and ADC for each channel.

**Comment by abdoulline** [comment]
@cferraio,  @BetterWang,

HcalElectronicsMap_ZDC_RPD_QIE10 

test tag (all the regular HCAL channels + ZDC&RPD QIE10 channels) is now available for P5 can be used in any local P5 tests. 
(using the first recipe example for using it on top of any regular GT from 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HcalMixESSources).

**Comment by abdoulline** [comment]
@slava77, @davidlange6
I guess this PR will _not_ supposed to wait till it's 81X  (#16150, merged) sibling will formally go through RelVals (as there is nothing really to validate in the central workflows), otherwise it might miss pA campaign beginning. 
It's needed to be in 80X release to validate extended (+ ZDC/RPD QIE10) emap via regular AlCa procedures.

**Comment by slava77** [comment]
On 10/30/16 2:11 PM, Salavat Abdullin wrote:
> @slava77 <https://github.com/slava77>, @davidlange6
> <https://github.com/davidlange6>
> I guess this PR will /not/ supposed to wait till it's 81X (#16150
> <https://github.com/cms-sw/cmssw/pull/16150>, merged) sibling will
> formally go through RelVals (as there is nothing really to validate in
> the central workflows), otherwise it might miss pA campaign beginning.
> It's needed to be in 80X release to validate extended (+ ZDC/RPD QIE10)
> emap via regular AlCa procedures.

If I understand correctly, there is some raw data with RPD (and ZDC?) in
QIE10
which can be used as a check of this PR.
Please post (or ask someone) some copy-paste style instructions to check
it, including a test emap.

**Comment by abdoulline** [comment]
I'd expect Chris and Quan to contribute

@cferraio, @BetterWang

**Comment by BetterWang** [comment]
Hi @slava77 @abdoulline , you can find a working emap at 
/afs/cern.ch/user/q/qwang/work/public/904_runs/emap.txt
If you merge topic this PR, and run 
/afs/cern.ch/user/q/qwang/work/public/904_runs/rpd.py
you will get QIE10DataFrameHcalDataFrameContainer_hcalDigis_ZDC_RECO filled.
This works for me on 81X release, and should be working on 80X.
@cferraio can cross check.

**Comment by abdoulline** [comment]
@cferraio, @BetterWang

what about P5 "dummy" data with extended emap tag
HcalElectronicsMap_ZDC_RPD_QIE10  (mentioned 3 day ago in this thread)?

**Comment by abdoulline** [comment]
Please, lay down step-by-step ("copy-paste" as Slava has asked) recipe to 
just execute right away.

**Comment by cferraio** [comment]
Hi @abdoulline,

First (of course) set up the PR in an 80X release.

Next copy the two files Quan pointed you to.
/afs/cern.ch/user/q/qwang/work/public/904_runs/emap.txt
/afs/cern.ch/user/q/qwang/work/public/904_runs/rpd.py

Finally, run rpd.py with a "cmsRun rpd.py", open the created root file (raw.root), and inspect QIE10DataFrameHcalDataFrameContainer_hcalDigis_ZDC_RECO.

Quan has many other runs in /afs/cern.ch/user/q/qwang/work/public/ which can be analyzed by changing the run number in rpd.py.

Since I've just set up myself, you can directly copy-paste this:
cmsrel CMSSW_8_0_X_2016-10-30-0000
cd CMSSW_8_0_X_2016-10-30-0000/src/
cmsenv
git cms-addpkg CalibCalorimetry/HcalPlugins
git cms-addpkg CalibFormats/HcalObjects
git cms-addpkg CaloOnlineTools/HcalOnlineDb
git cms-addpkg CondFormats/HcalObjects
git cms-addpkg DataFormats/HcalDetId
git cms-addpkg EventFilter/HcalRawToDigi
git cms-addpkg Geometry/ForwardGeometry
git cms-addpkg RecoHI/Configuration
git cms-addpkg RecoLocalCalo/Configuration
git cms-addpkg RecoLocalCalo/HcalRecProducers
git pull https://github.com/cferraio/cmssw RPDin80X
scram b -j 20
cp /afs/cern.ch/user/q/qwang/work/public/904_runs/emap.txt .
cp /afs/cern.ch/user/q/qwang/work/public/904_runs/rpd.py .
cmsRun rpd.py 
root raw.root

-Chris

**Comment by abdoulline** [comment]
OK, thank you, Chris. I'm just a bit confused to see all those git 
commands and not a single PR of interest

git cms-merge-topic 16308

on top of 8_1_2X

**Comment by cferraio** [comment]
Ah well that seems an easier way about it than what I usually do.

Anyway, the copy/paste and cmsrun commands should work out of the box.

Sent from my iPhone

On Oct 31, 2016, at 14:51, Salavat Abdullin <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, thank you, Chris. I'm just a bit confused to see all those git
commands and not a single PR of interest

git cms-merge-topic 16308

on top of 8_1_2X

**Comment by kpedro88** [comment]
Even if a PR isn't submitted yet, you can always do:
```
git cms-merge-topic cferraio:RPDin80X
```
(add the `-u` option if you want to disable automatic checkdeps, though sometimes this can break things)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16308 a0a9d61
- backport of QIE10 unpacking code for ZDC  #16150. The ZDC digis will be unpacked only when the hcal emap is updated. Once unpacked, they remain in the even products, but there are no consumers. So, no immediate downstream effect.
- jenkins tests pass; comparisons show no differences as expected.
- tests in 81X confirmed that the new product QIE10DataFrameHcalDataFrameContainer_hcalDigis_ZDC appears and it remains empty without relevant inputs (data and emap)
- tests suggested in https://github.com/cms-sw/cmssw/pull/16308#issuecomment-257296432 run and ZDC data becomes filled with the provided emap. I ran on 100K events without problems.

@davidlange6 
this PR overlaps with #16394 
I prefer that this one goes in first.
Then #16394 will need a quick update to save the QIE10 ZDC digis, and then features from #16394 can be consistently applicable to 80X and 81X. If this PR is left pending, the 81X and 80X versions of #16394  will be inconsistent at least temporarily.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
