### PR TITLE
Phase2-gem69 Correct GE21 eta partition sizes for the Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct GE21 eta partition sizes for the Phase2 scenarios

#### PR validation:

Tested using the overlap checking tool for a possible modified 2026D99 scenario

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by rappoccio** [comment]
+1

**Pull request merged**
