### PR TITLE
add L2L3Residual as know correction level to JetCorrector[Calculator]…

### PR DESCRIPTION
**Pull request by kirschen**
…; this way, L2L3Residual txt-files can also carry L2L3Residual als correction level in their parametrization

### CODE REVIEW

**Comment by kirschen** [comment]
As discussed in 
https://its.cern.ch/jira/browse/CMSHLT-518
this is supposed to avoid unnecessary confusion about a mismatch of correction levels between the txt-file/payload and the actual content.
Added also error output where it was missing [FactorizedJetCorrectorCalculator.cc]

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test
[maybe we avoid DAS issues this time]

**Comment by mmusich** [comment]
+1

**Pull request merged**
