### PR TITLE
CLCTs are offset by 1 BX in matching

### PR DESCRIPTION
**Pull request by dildick**
Recent data vs emulator studies using 2018C data (in particular data from the ME+1/1/9 OTMB) have shown that the CLCT BX are not shifted in the ALCT-CLCT matching algorithms. They are shifted when the CLCTs are written to EDM ROOT files however. Because the ALCT-CLCT matching windows are quite wide (7BX) in the current CSC local trigger firmware and emulator, it has a negligible effect. However, it does start playing a role when the ALCT-CLCT matching window is reduced to 5BX and ultimately 3BX. That is foreseen in the "SLHC" version of the CSC local trigger.

In addition, the matching algorithm type was changed from CLCT-centric to ALCT-centric. This as always been the case in firmware. 

A redundant test TMB run function was also removed.

This PR addresses these issues.

@tahuang1991 @lpernie @ptcox

### CODE REVIEW

**Comment by tahuang1991** [comment]
around 2009, Several similar lines were added to the ALCT-CLCT matching part in CSC emulator 

if (!isSLHC) bx_alct_stop += match_trig_window_size%2;

What it did  is extend the ALCT-CLCT matching window by a half of window size and at that time, because there is 1BX offset between wire digi timing and comparator digi timing from data and it results in 1BX offset in re-emulated ALCTs and CLCTs.  I guess, as a temporary solution to this offset saw by ALCT-CLCt matching in CSC emulator, the matching window is extended in this "ulgy" way. And now when we turned on isSLCH flag, we found that the window was not extended and the issue was uncovered. What we really should do about it is to add ALCT-CLCT bx offset also in the matching part in CSC emulator.  In our previous changes about timing shift, we only shift the BX of ALCT and CLCT in read-out part, not in matching part.

As for another change, ALCT-centric is enabled because in (O)TMB fw, it is always the case.  But it may not have any visible effect on offline re-emulation and MC.  It is quite important for (O)TMB fw to use ALCT-centric because ALCT has better timing and LCT timing is referred to ALCT timing, in other word, LCT is always built and sent out with fixed latency relative to ALCT timing

**Comment by thomreis** [comment]
please test

**Comment by dildick** [comment]
@thomreis Could you sign, please? Thanks.

**Comment by thomreis** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
