### PR TITLE
Fix include in NamedCandCombiner.h.

### PR DESCRIPTION
**Pull request by Teemperor**
There is no CommonTools/Utilities, but there is a CommonTolls/Utils with
the desired header, so let's use this instead.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19277	c77bb74
- update to an apparently dead file
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
