### PR TITLE
[12_5_X] Remove hardcoded trigger bits from Lumi ALCARECOs 

### PR DESCRIPTION
**Pull request by purbita-rahman**
#### PR description:

backport of #39519

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39519

**Comment by tvami** [comment]
+alca

**Comment by rappoccio** [comment]
+1

- Rejected tests are unrelated to this PR. 
- Weird issue [here](https://github.com/cms-sw/cmssw/pull/39519#issuecomment-1282309459) not observed. 
- Otherwise verbatim backport.

**Comment by rappoccio** [comment]
merge

**Pull request merged**
