### PR TITLE
Run3-hcx374X Update the scenarios for providing the correct set of initializing cfis -- backport of #46310

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scenarios for providing the correct set of initializing cfis -- backport of #46310

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46310

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46310

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
