### PR TITLE
HLT DQM for double tkmu and aux paths, 80X

### PR DESCRIPTION
**Pull request by olivito**
This adds DQM coverage for the following new HLT paths:
HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v1 -> in Higgs DQM
HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v1 -> in Higgs DQM
HLT_TkMu17_v1 -> in SUSY DQM

81X version of this PR: #15511

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by olivito** [comment]
bumping this PR, as it's been sitting for 2 weeks now on orp-pending.

**Comment by lathomas** [comment]
@slava77 @davidlange6  
Can this PR be signed off or is there something preventing to integrate it? 
Thanks !

**Comment by lathomas** [comment]
@slava77 @smuzaffar @davidlange6  
This PR was opened one month ago. 
Please let us know if there's any reason to hold this PR. 
Thanks !

**Comment by davidlange6** [comment]
+1

**Pull request merged**
