### PR TITLE
Updating template index html

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR updates two index.html template to add a cpl of new TkMaps.
This is related only to TrackerOffline shifter operations, is changing nothing in the production code

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 any particular reason to keep this PR on hold?

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
for sure this crash is due to something else in the IB, here I am only changing two index.html which are not used in any production sequence

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
