### PR TITLE
[12.3.X] Pixel Heterogeneous DQM: add modules for Tracks and Vertices @cpu / @gpu comparisons

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/37619

#### PR description:

Title says it all.
The code is actually from @sroychow and @arossi83.

#### PR validation:

Tested running wf. `runTheMatrix.py --what gpu -l 11634.503` on `lxplus-gpu` successfully.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of https://github.com/cms-sw/cmssw/pull/37619

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable_tests = gpu
   * workflows_gpu = 11634.503, 11634.506, 11634.583, 11634.587

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by fwyzard** [comment]
urgent

We would like to have this in the next (patch) release so it can be deployed at P5.

**Comment by perrotta** [comment]
Verbatim backport of #37619
(mostly a promemoria for orp, for when this will get fully signed...)

**Comment by kskovpen** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- Backport of the identical PR successfully merged in master since CMSSW_12_4_X_2022-04-28-2300

**Comment by perrotta** [comment]
ping

**Pull request merged**
