### PR TITLE
[14_0_X] Protect against invalid trajectory state on surface in STA muon reco

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #45049

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by francescobrivio** [comment]
urgent

 - addressing a crash observed in Tier0

Francesco as ORM

**Comment by francescobrivio** [comment]
hold

- this fix isn't complete as it solves one of the crashes reported, but not all of them: see details in https://github.com/cms-sw/cmssw/issues/45035#issuecomment-2132874782

**Comment by mmusich** [comment]
> hold

what's the purpose of the hold? this still fixes something, no?

**Comment by francescobrivio** [comment]
unhold

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
