### PR TITLE
Fix PackedCandidate::dz and PhotonIDValueMapProducer

### PR DESCRIPTION
**Pull request by gpetruc**
* fix the dz(point) method of PackedCandidate to work correctly when point is not the associated PV, and the eta of the candidate is not the eta of the track. This ensures that cand.dz(point) is always the same as cand.track.dz(point) whenever the track is available (as it was already the case for dxy)
* fix the PhotonIDValueMapProducer on miniAOD to get the dxy and dz from the candidate instead of the track (dxy and dy are always available in the candidate, but they're not available in the track at low pT, and in 94X this causes an exception)

### CODE REVIEW

**Comment by gpetruc** [comment]
@arizzi @emanueledimarco @peruzzim : this is needed to get the nanoAOD prototype running in 94X

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@gpetruc : should I expect any difference in the miniAOD output with this fix? I am not able to see any...

**Comment by gpetruc** [comment]
PhotonIDValueMapProducer should be transparent.
dz should give tiny differences in rare cases but maybe the bugged version
was not used anywhere in production.

Il 20 Set 2017 10:40, "perrotta" <notifications@github.com> ha scritto:

@gpetruc <https://github.com/gpetruc> : should I expect any difference in
the miniAOD output with this fix? I am not able to see any...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/cmssw/pull/20491#issuecomment-330785485>, or mute
the thread

**Comment by perrotta** [comment]
+1
- Fix for rare cases (no effect visible in jenkins or small size private tests)
- Code changes are in line with what in the description

**Comment by davidlange6** [comment]
merge

**Pull request merged**
