### PR TITLE
[Simulation] Allow DT ageing toy model to run at the DIGI-L1T step

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

This pull request updates the _toy model_ used to account for potential DT cell inefficiencies due to aging, so that it can be applied at the digitization step. This allows for a consistent impact on simulated digis before packing and trigger-primitive generation.

#### PR validation:

To be applied, DT aging a customization function should be used, no effect is expected in standard workflows.

Local testing was performed by adding the customization function in the step2 of `runTheMatrix.py -w upgrade 12809.0` and analyzing the produced samples.Results will be presented at the [Simulation meeting](https://indico.cern.ch/event/1477739/#63-aging-of-phase2-muon-detect)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@battibass , please, have a look into https://github.com/cms-sw/cmssw/blob/master/SLHCUpgradeSimulations/Configuration/python/aging.py#L245-L257 
It seems to be the optimal place where aging for DT is enabled.

**Comment by civanch** [comment]
+1

to avoid cross-release issues it is better to merge this PR. To complete aging simulation a new PR is needed, see issue #46788

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
