### PR TITLE
Added PPS Alignment to the Prompt Calibration Loop

### PR DESCRIPTION
**Pull request by MatiXOfficial**
#### PR description:

The main purpose of this PR is to add some new files and modifications required to run the PPS alignment procedure in the PCL. The implementation is based on #33215. Note that the modifications include updating two files in `CalibPPS/TimingCalibration`.

It is important for us to be able to test it on Tier0 as soon as possible, so these changes are supposed to be included in CMSSW_12_1_0. Since the deadline for CMSSW_12_1_0_pre5 is 19/10, we kindly ask for a quick review.

This PR also improves `PPSAlignmentWorker` and `PPSAlignmentHarvester`. It applies a refactor, fixes some bugs and adds some new functionality to the code in the `CalibPPS/AlignmentGlobal` package. The main modifications are listed below:
- huge refactor in the worker and the harvester
- README update to include new parameters from the `PPSAlignmentConfiguration` conditions format
- `test` folder update
- Replaced `PPSAlignmentConfig` with `PPSAlignmentConfiguration` in the worker and the harvester.
- Added support for the new parameters from `PPSAlignmentConfiguration`.
- Now, the harvester can save an sqlite file with the alignment results.
- Updated the debug mode in the harvester to save more plots.
- Fixed odd fitting in the harvester (in the `yAlignment` method).

Apart from that, this PR adds a `RetrieveCTPPSRPAlignmentCorrectionsData` module required to properly test writing an sqlite file containing a `CTPPSRPAlignmentCorrectionsData` object.

The PR is a continuation of the strategy presented in the [AlCaDB meeting on 30 August](https://indico.cern.ch/event/1069114/). The previous PR were:
- #31728 - first version of the code responsible for the PPS alignment,
- #34844 and #34845 - bug fix with backport,
- #35174 - new, final conditions object - `PPSAlignmentConfiguration`.

There are still some smaller changes foreseen, but they have been moved to the next PR, since it is vital to merge the PCL changes as soon as possible.

This PR also changes the online GTs, by including the new tags required in this PR and also get in line with the status of the 12_0_X currently used. Here are the diffs wrt the previous 12_1_X GTs:

* [121X_dataRun3_HLT_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v6/121X_dataRun3_HLT_v5)
* [121X_dataRun3_Express_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v6/121X_dataRun3_Express_v5)
* [121X_dataRun3_Prompt_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v6/121X_dataRun3_Prompt_v5)

And the diffs wrt to the 12_0_X GTs:
* [121X_dataRun3_HLT_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v6/120X_dataRun3_HLT_v3)
* [121X_dataRun3_Express_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v6/120X_dataRun3_Express_v2)
* [121X_dataRun3_Prompt_v6](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v6/120X_dataRun3_Prompt_v2)

#### PR validation:

- The code returns correct results running on data from Run 2. Check out `CalibPPS/AlignmentGlobal/test` for an example.
- A new matrix test workflow has been added - `1042`. It does not crash, but I've observed that the harvester (4th step) does not see any plots booked by the worker (3rd step). I don't know if that's because of a faulty configuration of the relval steps or wrong command used to run it (`runTheMatrix.py -l 1042 --ibeos`). Please, let me know if you know the answer to that. If not, I can remove that matrix test from this PR. By the way, I've observed the same problem while running the workflow `1041`, which is very similar to `1042`.
- To be able to run the matrix test, a candidate GT has been created - `121X_dataRun3_Prompt_Candidate_2021_10_09_12_20_39`. For now, it is still listed as `--conditions` in `relval_steps.py`. Please, let me know if I have to replace it with `auto:run3_data_express`.
- In case they are needed, I attach the memory consumption plots acquired during running the procedure using a representative dataset from 2018.
alignment_memory_check

### CODE REVIEW

**Comment by MatiXOfficial** [comment]
Ok, thanks. I put them in `autoCond.py`.

**Comment by tvami** [comment]
@cmsbuild , please test

**Review by tvami — CHANGES_REQUESTED** [review]
@malbouis created new GTs, please change to them in the given lines in the code @MatiXOfficial

**Comment by tvami** [comment]
@MatiXOfficial 
Also please include the following in the PR description:
"This PR also changes the online GTs, by including the new tags required in this PR and also get in line with the status of the 12_0_X currently used. Here are the diffs wrt the previous 12_1_X GTs: 

 * 121X_dataRun3_HLT_v6: 
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v6/121X_dataRun3_HLT_v5
* 121X_dataRun3_Express_v6: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v6/121X_dataRun3_Express_v5
* 121X_dataRun3_Prompt_v6: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v6/121X_dataRun3_Prompt_v5

And the diffs wrt to the 12_0_X GTs:
 * 121X_dataRun3_HLT_v6: 
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v6/120X_dataRun3_HLT_v3
* 121X_dataRun3_Express_v6: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v6/120X_dataRun3_Express_v2
* 121X_dataRun3_Prompt_v6: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v6/120X_dataRun3_Prompt_v2

"

**Review by tvami — COMMENTED** [review]
Whenever you do a `new` there should be a `delete`, too, to avoid a memory leak. I found some, please look through the code if there are other occurrences

**Comment by tvami** [comment]
ok, so in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-207d6e/19721/runTheMatrix-results/1042.0_RunExpressPhy2017F+RunExpressPhy2017F+TIER0EXPPPSCAL+ALCASPLITPPSALIG+ALCAHARVDPPSALIG/step4_RunExpressPhy2017F+RunExpressPhy2017F+TIER0EXPPPSCAL+ALCASPLITPPSALIG+ALCAHARVDPPSALIG.log

I see
```
[x_alignment] R_1_F: could not load mes_test
%MSG
%MSG-w PPS:  PPSAlignmentHarvester:ALCAHARVESTPPSAlignment@endRun  18-Oct-2021 19:54:52 CEST End Run: 305064
[x_alignment_relative] sector 45: cannot load data, skipping
%MSG
%MSG-w PPS:  PPSAlignmentHarvester:ALCAHARVESTPPSAlignment@endRun  18-Oct-2021 19:54:52 CEST End Run: 305064
[x_alignment_relative] sector 56: cannot load data, skipping
%MSG
%MSG-w PPS:  PPSAlignmentHarvester:ALCAHARVESTPPSAlignment@endRun  18-Oct-2021 19:54:52 CEST End Run: 305064
[y_alignment] L_2_F: cannot load data, skipping
%MSG
```

which I guess is a good indicator on why we dont see anything in the plots or the sqlite file

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by MatiXOfficial** [comment]
Hi, please correct me if I'm wrong, but today is the deadline for the pre5 pre-release. Since it's vital to include the alignment code in the PCL and test it on Tier0 with the 12_1 release, can we please speed up the review process?

**Comment by tvami** [comment]
Hi, haha yes, we are fully aware. I'm happy to sign this any time, but this currently is not creating the plots and the sqlite content, i.e. it's not working. Do you want to merge like this?

**Comment by malbouis** [comment]
@MatiXOfficial , just so we understand it a bit more in detail, when you run your code with the local test you have in CalibPPS/AlignmentGlobal/test/run_analysis_cfg.py do you get an sqlite file with a non empty payload that contains the alignment corrections you expect?

**Comment by tvami** [comment]
urgent

**Comment by qliphy** [comment]
+1

**Pull request merged**
