### PR TITLE
phase2 Tracker XMLs in 8X (flat and Tilted) and WorkFlows cleaning

### PR DESCRIPTION
**Pull request by boudoul**
This PR is introducing the xml files for the two supported version of the Phase2 Tracker : the Flat and Tilted cases .

I took the opportunity to remove old phase2 xmls from the past to start 8X with clean area.

Note that at this stage the phase2 Tracker(s) are not included in any phase2 workflow yet and will be done at the next iteration (to avoid to have a confusing big PR to review while the WFs are still being defined within the simulation group) .

At the same time I created a placeholder for phase2 WFs in runTheMatrix , to be ready once they are completely defined (and removed all the old ones from the SLHC past...)

@delaere FYI
Same as PR #12910, but commits reorganized and labeled as suggested by @davidlt

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by ianna** [comment]
@boudoul and @davidlange6 - I think, it is rejected due to the following error:
```
processing relval_2017
10039
10046
10060
ERROR importing file  relval_2017 '2017PU'
```

**Comment by boudoul** [comment]
ahh you must be right, good catch! I will fix later today - Thanks @ianna!

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by boudoul** [comment]
@cmsbuild, please test

**Comment by boudoul** [comment]
not sure in undertand the failure (not even see failures)

**Comment by boudoul** [comment]
@cmsbuild, please test

**Comment by boudoul** [comment]
+1

**Comment by ianna** [comment]
+1

**Pull request merged**
