### PR TITLE
ngrenz Strip Validation Package Optimization

### PR DESCRIPTION
**Pull request by ngrenz**
PR of a work intended to optimize gradually the performance of tracker validation code.
Here I tried to resolve the “FIXME: vector <DetId> is Suboptimal “.
Outputs are supposed to be unchanged.

The changes are:
-   Instead of one big loop over the DetIds, we have 3 loops over rechits-rphi, -stereo and -matched
  -    We do not need the vector for DetIds and we do not need to fill this vector
  -   The compute where we are in the vector is now unnecessary
-   The computing of rechitpro and the use with fillME is now in the same loops
  -   We do not need some vectors for the value transfers

Any comments and suggestions are welcome.
More optimizations will follow.

### CODE REVIEW

**Comment by ngrenz** [comment]
@boudoul FYI

**Comment by boudoul** [comment]
Hi @ngrenz , could you please change the title "Cmssw 7 5 0 pre6 ngrenz SiStripRecHitsValid" of your PR with something like "Strip Validation Package Optimization "  (the title is what is propagated to the release notes, and help anyone understanding what is entering in a release) - Thanks

**Comment by deguio** [comment]
please test

**Comment by ngrenz** [comment]
@cmsbuild Hi, are you sure the error is from my pull request?

I tried to build it with CMSSW_7_5_0_pre6 with my changes and it workt.

Now I tried to bild CMSSW_7_6_X_2015-07-16-2300 without my changes and it work.
But after adding the modul Validation/TrackerRecHits and still without my changes the bild faild with:

<pre> 
/afs/cern.ch/cms/sw/ReleaseCandidates/volC/slc6_amd64_gcc491/external/gcc/4.9.1-cms/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.9.1/../../../../x86_64-redhat-linux-gnu/bin/ld: cannot find -lDataFormatsStdDictionaries
collect2: error: ld returned 1 exit status
gmake: *** [tmp/slc6_amd64_gcc491/src/Validation/TrackerRecHits/src/ValidationTrackerRecHits/libValidationTrackerRecHits.so] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
</pre>

**Comment by smuzaffar** [comment]
CMSSW_7_6_X_2015-07-16-2300 is broken due to latest root changes we merged. We have to wait for next 76X IB (where root changes are reverted) to do the tests again

**Comment by ngrenz** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by ngrenz** [comment]
Hi CMSSW_7_6_X_2015-07-19-1100 and CMSSW_7_6_X_2015-07-19-2300 had not made RelVals test is it possible to test this code with CMSSW_7_6_X_2015-07-18-2300 ?

**Comment by davidlange6** [comment]
indeed, a second problem came into the IBs that is not related to this request - will fix it for the next IB.sorry.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
