### PR TITLE
L1TObjectTypeInCond typedef instead of an overriding ObjectTypeInCond

### PR DESCRIPTION
**Pull request by slava77**
Globally-defined typedefs better be unique in DataFormats as they are globally known to ROOT (same typedef name should correspond to the same type; multiple definitions of the same typedef are apparently OK).
ObjectTypeInCond is defined in the legacy L1 already.

This should clear rather verbose errors in Tree::Draw with selections made from FWLite similar to 
```
In file included from DataFormatsL1GlobalTrigger_xr dictionary payload:48:
In file included from L1GlobalTrigger/interface/L1GlobalTriggerObjectMapRecord.h:23:
DataFormats/L1GlobalTrigger/interface/L1GlobalTriggerObjectMapFwd.h:34:33: error: typedef redefinition with different types ('vector<L1GtObject>' vs 'vector<l1t::GlobalObject>')
typedef std::vector<L1GtObject> ObjectTypeInCond;
                                ^
DataFormats/L1TGlobal/interface/GlobalObjectMapFwd.h:34:40: note: previous definition is here
typedef std::vector<l1t::GlobalObject> ObjectTypeInCond;
```

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@slava77 

Hmm, I'd prefer if instead of just a
```using ObjectTypeInCond=L1TObjectTypeInCond```
one is making a global search and replace of ```ObjectTypeInCond``` by ```L1TObjectTypeInCond```
where it is required.

**Comment by slava77** [comment]
On 4/22/17 11:13 PM, Martin Grunewald wrote:
> @slava77 <https://github.com/slava77>
> 
> Hmm, I'd prefer if instead of just a
> |using ObjectTypeInCond=L1TObjectTypeInCond|
> one is making a global search and replace of |ObjectTypeInCond| by
> |L1TObjectTypeInCond|
> where it is required.

OK
I will change

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
