### PR TITLE
New GT for re-reco fixing issues with HCAL and ECAL tags.

### PR DESCRIPTION
**Pull request by diguida**
# Summary of changes
## Run1 data

[74X_dataRun1_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v3): as [74X_dataRun1_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_v3/74X_dataRun1_v2):
- taxonomy change for Muon APE
- added BTV discriminators as GBRForest payloads with new labels
- updated SiStrip O2O conditions: now using prompt version. BEWARE: Noise tag must be reviewed: keeping the old offline version
- updated ECAL pulse shapes with Run2 values (Run1 value kepts as MC in the first IOV)
- updated HCAL electronic maps in order to unpack all HF FED
- updated HCAL response corrections with the latest scale computed in the Early Commissioning studies.
## Run2 data

[74X_dataRun2_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v3): as [74X_dataRun2_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_v3/74X_dataRun2_v2):
- taxonomy change for Muon APE
- added BTV discriminators as GBRForest payloads with new labels
- updated SiStrip O2O conditions: now using prompt version. BEWARE: Noise tag must be reviewed: keeping the old offline version
- updated ECAL pulse shapes with Run2 values (Run1 value kepts as MC in the first IOV)
- updated HCAL electronic maps in order to unpack all HF FED
- updated HCAL response corrections with the latest scale computed in the Early Commissioning studies.

### CODE REVIEW

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
For the record: should fix the HF unpacker issue shown in the validation report by @hengne [here](https://indico.cern.ch/event/450205/contribution/1/attachments/1162788/1674987/hengne_ppd_20150930_relval_7412miniAOD_760pre5.pdf)

**Comment by diguida** [comment]
@slava77 this is something you might want to watch as well.

**Comment by diguida** [comment]
@abdoulline this is something you might want to watch as well.

**Comment by mmusich** [comment]
+1

**Pull request merged**
