### PR TITLE
Add ability to measure time in the EventSetup

### PR DESCRIPTION
**Pull request by wddgit**
Uses the Timing Service to measure to two time totals.
First, the time while threads are blocked by the mutex in
DataProxy::get. Second, the time to run the getImpl function
to fill the data cache after the mutex lock has been obtained.

### CODE REVIEW

**Comment by wddgit** [comment]
@fwyzard  At one point you asked to be notified about new signals in the Framework. This PR adds 3 signals related to the EventSetup. You can probably safely ignore them although they might be of interest to you. The Timing service uses them (and also there is an option for the Tracer service to use them).

**Comment by wddgit** [comment]
please test

**Comment by fwyzard** [comment]
Thanks David,
as you suggested, I subscribed to get notifications about FWCore/Services
:-)

Do you think it would make sense to have a tighter integration between the
framework and the FastTimerService ?

.A

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
