### PR TITLE
Update the HLT alpaka customisation

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Customise the GPU checks to use the `AlpakaBackendFilter`:
  - customise the `Status_On{CPU|GPU}` HLT paths and the `DQM_{Ecal|Hcal|Pixel}Reconstruction_v*` HLT paths to use the `AlpakaBackendProducer` and `AlpakaBackendFilter` modules.

Delete legacy modules and tasks after defining the alpaka ones.
Clean up white space and indentation.

#### PR validation:

The online HLT menu 2024 v1 was run with and without these changes.

#### Backport status

To be backported to 14.0.x for data taking

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test with #44387

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
type hlt-integration

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
