### PR TITLE
Adding two version of the Phase2 Tracker and corresponding workflows for testing and relvals purpose 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
This PR aims to add two new version of the tracker for testing purpose.

The main feature of the Tracker (T7 and T8 ) are : 
1)  T7: Phase2 tilted tracker (v6.1.3) w/ phase 2 pixel (v4.2.0) 
--> same as T6 but 25x100 in 1x2 modules, 50x200 in 2x2 modules
2) T8: Phase2 tilted tracker (v6.1.3) w/ phase 2 pixel (v4.2.1) 
--> same as T6 but 25x100 in 1x2 modules, 100x100 in 2x2 modules

Those Tracker would benefit to get relvals for physics performance in order to guide R&Ds choice 

The corresponding Workflows for T7 and T8 are D22 (216xx) and D23 (220xx) -

### CODE REVIEW

**Comment by kpedro88** [comment]
@boudoul do we need to update CPE errors for these new trackers?

**Comment by kpedro88** [comment]
please test

**Comment by boudoul** [comment]
@emiglior FYI

**Comment by boudoul** [comment]
hello @kpedro88 , we will need eventually  but we first need  WFs to generate the events needed to derive them .

**Comment by kpedro88** [comment]
I see, I'll await the subsequent PR then

**Comment by kpedro88** [comment]
@boudoul do you want to add some of the WFs to relval_2023.py so they can be tested in the regular matrix?

**Comment by kpedro88** [comment]
please test
(seems to have gotten stuck...)

**Comment by kpedro88** [comment]
@boudoul ping (re: adding new WFs in relval_2023 for standard matrix)

**Comment by boudoul** [comment]
hi @kpedro88 , yes sorry too many meetings... will do in ~1h -  I was thinking to remove the reco steps for those WFs , because the CPE will not be ready immediately - It's not that the output of the reco is frankly wrong, it's even reasonnably good, but still with wrong CPE . On the other hand , removing the reco steps will also prevent to get some DQM plots during the PR tests ...

**Comment by kpedro88** [comment]
I think it's better to leave the RECO step at least for code testing purposes, even if not tuned completely.

**Comment by boudoul** [comment]
thanks for the prompt feedback, I will update the PR for relval_2023 soonish

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by boudoul** [comment]
Hello  @prebello,  @fabozzi, @GurpreetSinghChahal, could you please take a  look and sign this PR ? Thank you .

**Comment by prebello** [comment]
+1

**Comment by boudoul** [comment]
dear @franzoni @davidlange6 @fabiocos , could you please sign for operation ? thank you.

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
