### PR TITLE
Deleting deprecated scripts access geometry with prior-run2 GT in CondTools/SiPixel

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Following up the migration of Geometry_cff to GeometryDB_cff (https://github.com/cms-sw/cmssw/pull/35278), proper GlobalTag needs to be set in advance. We take the chance to clean up AlCa/DB related scripts that accessing with prior-run2 GT in CpmdTools/SiPixel.

#### PR validation:

Delete deprecated script that can't be tested with modern geometry.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a back port and no back port expected.

### CODE REVIEW

**Comment by tvami** [comment]
type trk

**Comment by tvami** [comment]
FYI @sanjanasekhar
I think these codes are not used, and actually the c++ plugins could be removed too. If you disagree, please provide a working config

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
to justify the hold, I think the gain reader ones can be salvaged.

**Comment by tvami** [comment]
>  I think the gain reader ones can be salvaged.

@sanjanasekhar will you deal with that?

**Comment by mmusich** [comment]
assign trk-dpg

**Comment by mmusich** [comment]
-1
   * superseded by https://github.com/cms-sw/cmssw/pull/39192

**Comment by tvami** [comment]
-db 
 * see https://github.com/cms-sw/cmssw/pull/39012#issuecomment-1227239123
 * @yuanchao please close the PR, thanks

**Comment by yuanchao** [comment]
Closed for #39192

**Pull request closed without merging**
