### PR TITLE
Kalman BMTF Emu v2.7

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is the latest BMTF emulator for the Kalman algorithm

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by panoskatsoulis** [comment]
This PR updated also wrt the changes made to PR #24855 
(Python 3 migration issue)

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

@panoskatsoulis why only comment this out and not remove it completely? Is this needed for HLS?

**Comment by thomreis** [comment]
Hi @panoskatsoulis
are the differences in the test WFs expected?

**Comment by thomreis** [comment]
Do you still need this backport?

**Comment by panoskatsoulis** [comment]
Hi @thomreis 
since this was targeting the Heavy Ions version I think it is not needed any more.

**Comment by thomreis** [comment]
In this case please close the PR.

**Pull request closed without merging**
