### PR TITLE
Fixed replace with FinalPath

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is an alternative implementation to #36932

#### PR validation:

Framework unit tests in modules FWCore.ParameterSet.Config and FWCore.ParameterSet.SequenceTypes pass.

### CODE REVIEW

**Comment by Sam-Harper** [comment]
thanks @Dr15Jones !

**Comment by Dr15Jones** [comment]
@Sam-Harper thank you for finding the problem and giving us a preliminary fix.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
type bug-fix

**Comment by qliphy** [comment]
+1

**Pull request merged**
