### PR TITLE
implemented Bessel's correction to remove bias in Time Uncrt estimati…

### PR DESCRIPTION
**Pull request by pietverwilligen**
…on of ME0Segment

### CODE REVIEW

**Comment by pietverwilligen** [comment]
please test :-)

**Comment by slava77** [comment]
@cmsbuild please test

the change looks simple

**Comment by cvuosalo** [comment]
+1

For #11460 738ca21fa566e50e53d7285c4b81acb0ce048edc

Minor adjustment to ME0 segment time estimate to remove bias. There should be no change in monitored quantities.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11460/8352/summary.html) against baseline CMSSW_7_6_X_2015-09-24-1100  show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
