### PR TITLE
update to support dual fed readout

### PR DESCRIPTION
**Pull request by deguio**
this is needed to support in DQM the dual fed readout which went to prod last week.
this is needed for HI data taking and always from now on.

### CODE REVIEW

**Comment by dmitrijus** [comment]
Hi, 81x? You know the drill :)

**Comment by deguio** [comment]
will do it soon.

**Comment by deguio** [comment]
here it is #16515

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
