### PR TITLE
[12_4_X] Add run3 alignment relval

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

This PR adds run3 relval for PCL pps alignment calibration.

#### PR validation:

relval 1045

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #39059

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type new-feature, ctpps

**Comment by ChrisMisan** [comment]
backport of #39059

**Comment by ChrisMisan** [comment]
test parameters:

- workflows=1045

**Comment by ChrisMisan** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Backport PR.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
