### PR TITLE
Pixel Palyoad Inspector: improve the Template and GenError header plots

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Improves the Pixel Template and GenErrors Header Payload Inspector plots, by adding:
   * number of Template y entries
   * number of Template y-slices of x entries
   * number of Template x-entries in each slice
   * detector type (0=BPix, 1=FPix)
   * Charge scaling to match cmssw and pixelav
   * detector bias potential in Volts

In addition, introduce a class to display the template titles stored in the header.

#### PR validation:

Run with this branch the commands:
```python
 getPayloadData.py --plugin pluginSiPixelTemplateDBObject_PayloadInspector --plot plot_SiPixelTemplateHeaderTable --tag SiPixelTemplateDBObject38Tv3_express --time_type Run --iovs '{"start_iov": "326083", "end_iov": "326083"}' --db Prod --test ;
 getPayloadData.py --plugin pluginSiPixelTemplateDBObject_PayloadInspector --plot plot_SiPixelTemplateTitles_Display --tag SiPixelTemplateDBObject38Tv3_express --time_type Run --iovs '{"start_iov": "326083", "end_iov": "326083"}' --db Prod --test ;

```

obtained the following plots:

image

---

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.
attn:
@tvami

### CODE REVIEW

**Comment by mmusich** [comment]
@please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
