### PR TITLE
[Backport 11_3] Fix prodlike workflow to use DIGI instead of DIGI:pdigi_valid

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/33847

#### PR validation:
Get proper cmsDriver(s) when use
`runTheMatrix.py --what upgrade -l 23234.0,23234.21,23434.21,23434.9921 --dryRun`

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:

- workflows = 23234.21, 23434.21, 23434.9921

**Comment by srimanob** [comment]
Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Urgent

Expect to include it in the next 11_3 release for Phase-2 production @qliphy @silviodonato

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
@qliphy @silviodonato 
I believe this is the last piece needed for the 11_3 Phase2 campaign. Thanks.

**Comment by silviodonato** [comment]
> @qliphy @silviodonato
> I believe this is the last piece needed for the 11_3 Phase2 campaign. Thanks.

thanks, it will be included in the next 11_3_X release

**Comment by silviodonato** [comment]
+1

**Pull request merged**
