### PR TITLE
B parking Skimming code update

### PR DESCRIPTION
**Pull request by gkaratha**
Dear all,

Since there was a conflicts due to merging of the BParking skimming and our need to move to low pT e both in the analysis and for skimming, I opened a new PR without conflicts. Proposed by @kfjack . If everyone agrees we can close the previous PR and continue the discussion here? Adding @bainbrid  and @mverzett . Thanks.

Best regards,
George Karathanasis

### CODE REVIEW

**Comment by gkaratha** [comment]
Dear all,

In order to be in syncc with the latest developments in low pT electrons, I changed how the BDT value is read by the code (ie first go from electron -> gsfTrack -> read value). The BDT values are the same and the change is technical only. The WP gives the same performance (Rate 5.35%) when running on the same dataset. Thanks.

Best,
George

**Comment by prebello** [comment]
please test

**Comment by fabiocos** [comment]
@gkaratha could you please modify the PR title in something more explicative and useful?

**Comment by gkaratha** [comment]
Dear @fabiocos ,

Yes sure! I think is ok now right? Thanks

Best,
George

**Comment by fabiocos** [comment]
@gkaratha indeed, thank you

**Comment by gkaratha** [comment]
Dear @fabiocos ,

No problem! The previous title was indeed a bad one. Thanks for the comment!

Best,
George

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 136.898

**Comment by fabiocos** [comment]
please test workflow 136.898

the B parking test was successfully, let's repeat just for completeness

**Comment by gkaratha** [comment]
Dear all,

Checking the logs I see that the reason of failure is due to this: Module: MixingModule:mix (crashed). Naively i would think that skimming does not actually affects mixing module. The reason is that probably the skimming will run after generation (and mixing) is finished. The other argument is that essentially the code is the same with previous time with the difference of using low pT e as input. Can we try to test without the skim or with the previous skim? I will also try to reproduce it locally. Many thanks.

Best,
george

**Comment by fabiocos** [comment]
the crash looks unrelated to this PR

**Comment by fabiocos** [comment]
please test workflow 136.898

**Comment by fabiocos** [comment]
+1

the test failure is unrelated to this PR (it originally succeeded), the test specific to the B parking skim passes smoothly

**Comment by fabiocos** [comment]
merge

**Comment by bainbrid** [comment]
@fabiocos 
Please could you clarify if this will enter 10_5_X, or just 10_6_X?

**Comment by fabiocos** [comment]
@bainbrid this is for 10_6_X, now, and I understand you are interested into a 10_2_X backport. Could you please clarify why 10_5_X would be eventually interesting for this PR?

**Comment by bainbrid** [comment]
It's not necessary, we can just go with 10_6_X.

**Pull request merged**
