### PR TITLE
condformats_serialization_generate.py: fix include paths and fail on serious issues

### PR DESCRIPTION
**Pull request by davidlt**
- The script itself uses libClang for parsing C++ source files, thus we
  must use include files as seen by Clang. Note, this still points to GNU
  C++ standard library in GCC package, but there are special headers which
  are compiler specific, those are picked up from Clang package.
- Print severity level names instead numbers.
- Fail if there are 'Error' or/and 'Fatal' level diagnotic messages.
- Remove obsolete ignore rules. They should not be triggered as long as
  include paths and arguments passed to libClang are valid.
- This should resolve issue where `get_statement` could return `None`,
  because compiler couldn't do a correct job due to missing/wrong
  include paths or/and arguments.
- Required for Clang 3.7.0.

Signed-off-by: David Abdurachmanov David.Abdurachmanov@cern.ch

### CODE REVIEW

**Comment by davidlt** [comment]
I requested some of this before. I finally bumped into this while testing Clang 3.7.0. We have to make sure that header is compilable with Clang and do not proceed if there are serious issues otherwise this has impact on translation unit. In particular case, Clang was not able to provide SourceRange, because one of SourceLocation was not valid. Because script never checks for `get_statement()` return this will cause the whole thing to crash and burn. Worked on the current Clang we have which is somewhere between 3.5.0 and 3.6.0 and Clang 3.7.0 RC2.

**Comment by davidlt** [comment]
Note, Jenkins testing is running, but it's useless because SCRAM or SCRAM generated Makefile does not check for modifications in `condformats_serialization_generate.py`, thus it does not checkout `CondFormats`. Test it locally by checking out `git cms-addpkg CondFormats`.

**Comment by davidlt** [comment]
ping^1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
