### PR TITLE
Fix include for HFStripFilter

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Catched by header checker 
Moved one include from the implementation into the class header file

#### PR validation:

It compiles

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
ping bot

**Comment by smuzaffar** [comment]
@perrotta , there are issues with github that is why bot was not able to update the status. 
Anyway, I have restarted code checks

**Comment by perrotta** [comment]
+1
- Trivial fix to shut up the Header Consistency checker
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
