### PR TITLE
PPS geometry fix for Timing detectors

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:
Fix in the numbering of PPS UFSD and double diamond detector channels for 2017 and 2018

#### PR validation:

The changes have been validated re-processing 2017 and 2018 data using CMSSW_10_6_0_pre2 release

### CODE REVIEW

**Comment by fabferro** [comment]
FYI @forthommel @ianna

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - FYI, this update needs to be put in the GT to be used for the UL re-reco

**Comment by fabiocos** [comment]
+1

@ianna @fabferro I assume there will be a corresponding DB payload to be updated, am I correct?

**Comment by fabferro** [comment]
> 
> 
> +1
> 
> @ianna @fabferro I assume there will be a corresponding DB payload to be updated, am I correct?

Yes, that's the idea. Working on it.

**Comment by fabiocos** [comment]
@fabferro @ianna well the sooner the better, otherwise we have an inconsistency between ideal description in the release the the actual payload in the DB, right?

**Comment by fabferro** [comment]
> 
> 
> @fabferro @ianna well the sooner the better, otherwise we have an inconsistency between ideal description in the release the the actual payload in the DB, right?

Yes, in fact it's definitely something we want to avoid. The db payload is not yet ready because I found some difficulties in producing/testing it. The discussion with @ianna and @cvuosalo is ongoing. I hope we can solve the issue in short time.

**Pull request merged**
