### PR TITLE
migrate Validation/DTRecHits DQM sources to concurrent DQM (10.0.x)

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #22082

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Fixed the changes at https://github.com/fwyzard/cmssw/blob/22272848740d21e4b6aaedf8c2cf0e3cff3cb095/Validation/DTRecHits/plugins/DTRecHitQuality.cc#L56_L60 .
Thanks to @battibass for reporting and debugging.

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
Looks like there is no interest in back porting these changes.

**Pull request closed without merging**
