### PR TITLE
Address warnings raised from L1T DQM for UL reco

### PR DESCRIPTION
**Pull request by benkrikler**
#### PR description:
Adds small fixes to prevent warnings from L1 DQM for the UL reco.  Namely:
* Tell CMSSW not to check the `goodPFJetsForL1T` EDFilter, which appears in an EndJob.
* Remove `l1tStage2uGTTiming` from the sequence since it doesn't have Era-dependent configuration causing several warnings.

#### PR validation:
I have confirmed that the reported warnings are no longer appearing, and the output DQM files seem as I'd expect.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@benkrikler can you forwardport this to CMSSW_11_X_Y too?

**Comment by fabiocos** [comment]
@benkrikler before considering this PR we need to have master counterpart integrated

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
