### PR TITLE
Formatting changes to remove gcc 6.0 misleading-indention warnings.

### PR DESCRIPTION
**Pull request by gartung**
There are no changes to the curly braces.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mommsen** [comment]
+1
Trivial whitespace change

**Comment by mmusich** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by cvuosalo** [comment]
@gartung: There are merge conflicts that need to be fixed.

**Comment by gartung** [comment]
@cvuosalo Merge conflict resolved. I changed the same file on two branches because I missed some warnings.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15066 bc61809677872d9d1b74a6544722db7b3a1ca270

Reformatting indentation to improve readability. There should be no change in compiled output.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-07-03-2300 show no significant differences, as expected.

**Comment by fabozzi** [comment]
+1

**Pull request merged**
