### PR TITLE
[TkAl] Further fixes to JetHT Validation

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR fixes another couple of bugs reported by @jusaviin in the context of running the JetHT validation (see report at the Tracker Alignment meeting of [7th of Feb 2023](https://indico.cern.ch/event/1243355/contributions/5249350/attachments/2589130/4467472/jussi_jetHtStatus_2023-02-07.pdf)).
These were mostly related to plotting:
   * afa5f3390e1a322395ff990d7a4c846fd006f528 undoes a part of https://github.com/cms-sw/cmssw/commit/1d2058c0829242fd5388aa490103ab79d069b166 which cause the destructor of `JDrawer` to segfault. 
   * 92f63b8527c09e67c653e6e7a5ce3334caf53d3f complies with the fact that now the input luminosity files are taken from `cms-data` (following https://github.com/cms-data/Alignment-OfflineValidation/pull/3)
   * 33b6fc0c2cf91dc2cb813d40eab1b36c86297735 fixes a mistake unintentionally introduced in PR https://github.com/cms-sw/cmssw/pull/40695 when including the auto-generated cfi 
   * eb133b4ea3422f629d1f831e6d14e6c3978885cb adds a complete set of unit tests, to avoid similar mistakes arising again in the future.

#### PR validation:

Relies on the existing (and augmented) unit tests: `scram b runtests_JetHTall`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
urgent 
   * @cms-sw/alca-l2 please consider this straightforward set of fixes for inclusion in 13.0.0.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * unit tests testing the changes have already passed

**Comment by rappoccio** [comment]
+1

**Pull request merged**
