### PR TITLE
Modification to configuration files for X(5568)

### PR DESCRIPTION
**Pull request by oozcelik**
decay and pdl files updated

### CODE REVIEW

**Comment by perrozzi** [comment]
+1

**Comment by oozcelik** [comment]
To be honest, I have no idea why this error shows up?!

**Comment by perrozzi** [comment]
as far as I know sometimes unrelated errors can appear, and this looks like one of them
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15486/14612/runTheMatrix-results/1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM/step3_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM.log
others may confirm

**Comment by oozcelik** [comment]
@perrozzi could you please make sure this PR will be discussed at the next ORP meeting?

**Comment by perrozzi** [comment]
@oozcelik once https://github.com/cms-sw/cmssw/pull/15618 is merged, is this PR still needed?

**Comment by oozcelik** [comment]
@perrozzi yes, these are updated global decay and particle list files for X(5568) decay.

**Comment by perrozzi** [comment]
please test

**Comment by oozcelik** [comment]
Any progress? The PR waiting for pending RunI request and needs to be implemented in next 53x release which will come out soon.

**Comment by davidlange6** [comment]
@oozcelik - these need to go into https://github.com/cms-data/GeneratorInterface-EvtGenInterface - please make your pull request there. Thanks!

**Comment by oozcelik** [comment]
It has been merged here https://github.com/cms-data/GeneratorInterface-EvtGenInterface/pull/8#event-780921028 
shall I close this PR?

**Pull request closed without merging**
