### PR TITLE
SIM: fixed scripts and mctruth

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Small inaccuracy in several MC python scripts are fixed. MC truth code is cleaned-up

It is not expected any change of results.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
+1

again timeout

**Comment by perrotta** [comment]
> @perrotta , @rappoccio , please, give me advice: timeout problem does not related to this PR. There may be two actions: 1) merge it neglecting this problem; 2) restart tests until they succeed. In the case 1) we save resources but likely the merge will be postponed or never happened. What is your point of view?

@civanch if it is clear that the issue with the RelVal tests is uncorrelated, and it does not hide possible problems which end up not being tested by the failing workflows, I don't see why why should keep trying and retrying to run those useless tests.
Unfortunately, those RelVals-Input timeout's are rather common, and if not relevant we can avoid loosing time and resources for it.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
