### PR TITLE
Run3-hcx378 Make 2023 Geometry scenario to accept RPD as a valid detector

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make 2023 Geometry scenario to accept RPD as a valid detector

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backported to CMSSW_14_1_X using #46468

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this

**Comment by subirsarkar** [comment]
Upgrade

**Comment by bsunanda** [comment]
@subirsarkar Please type +Upgrade rather than Upgrade

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
