### PR TITLE
Add test for (py3-)torch

### PR DESCRIPTION
**Pull request by iarspider**
This PR was made to check the build of (py-)torch. We should only merge it if CMS-ML group really want to make use of this external otherwise it will increase the maintenance for external software stack ( as it has a large dependency chain https://github.com/cms-sw/cmsdist/pull/8388/files#diff-1718ab1f6737a0d8faffa3b2914ec2f72b87d478b4e3db04828411d2878479a1R11 )

### CODE REVIEW

**Comment by iarspider** [comment]
test parameters:
- pull_request https://github.com/cms-sw/cmsdist/pull/8388

**Comment by iarspider** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/8388

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please tet

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
test parameters:
- enable gpu

**Comment by iarspider** [comment]
enable gpu

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by iarspider** [comment]
please test for el9_aarch64_gcc11
just in case, since we have IBs with this platform

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
enable gpu

**Comment by iarspider** [comment]
please test

**Comment by perrotta** [comment]
@iarspider are you done with your updates? Can this be considered for merging?
By the way: could you please add a few lines of descriptions on top of this PR (as well as on top of the other ones of yours)?

**Comment by smuzaffar** [comment]
@perrotta , this PR was made to check the build of (py-)torch. We should only merge it if CMS-ML group really want to make use of this external otherwise it will increase the maintenance for external software stack ( as it has a large dependency chain https://github.com/cms-sw/cmsdist/pull/8388/files#diff-1718ab1f6737a0d8faffa3b2914ec2f72b87d478b4e3db04828411d2878479a1R11 )

**Comment by perrotta** [comment]
Thank you @smuzaffar 
I added your short description on top of this PR, so that at least we know what it is intended for.

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by iarspider** [comment]
please abort

"tested" in https://github.com/cms-sw/cmsdist/pull/8388, the new example fails to compile due to api change in pytorch.

**Comment by iarspider** [comment]
please test

**Comment by tvami** [comment]
+analysis
 * now https://github.com/cms-sw/cmsdist/pull/8388 is merged

**Comment by rappoccio** [comment]
+1

**Pull request merged**
