### PR TITLE
Revert EI removal in TSG tests

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Revert EI removal in TSG tests
See discussion in: https://github.com/cms-sw/cmssw/issues/36514

#### PR validation:

None (revert of a PR)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- This PR reverts to the situation which was there before #36494, and no issues are expected from it in the tests
- Therefore, let have it merged now, in time for the 1100 IB, even before the PR tests finish (but they do not show issues so far)
- The intention is to convert the 1100 IB into CMSSW_12_3_0_pre2: we'll have time to check the final results of this PR tests, and the full output of CMSSW_12_3_X_2021-12-16-1100 before starting building it anyhow

**Comment by perrotta** [comment]
merge

**Pull request merged**
