### PR TITLE
New GT for all supported scenarios

### PR DESCRIPTION
**Pull request by diguida**
# Summary of changes
## Run1 simulation
- Ideal: [76X_mcRun1_design_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun1_design_v0): As [75X_mcRun1_design_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun1_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun1_design_v0/75X_mcRun1_design_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Removed unsupported Run1 SIM geometries;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
- Realistic: [76X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun1_realistic_v0): As [75X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun1_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun1_realistic_v0/75X_mcRun1_realistic_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Removed unsupported Run1 SIM geometries;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
- Heavy Ion: [76X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun1_HeavyIon_v0): As [75X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun1_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun1_HeavyIon_v0/75X_mcRun1_HeavyIon_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Removed unsupported Run1 SIM geometries;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
- Proton Lead: [76X_mcRun1_pA_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun1_pA_v0): As [75X_mcRun1_pA_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun1_pA_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun1_pA_v0/75X_mcRun1_pA_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Removed unsupported Run1 SIM geometries;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
## Run1 data
- Offline: [76X_dataRun1_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_dataRun1_v0): As [75X_dataRun1_v4](https://cms-conddb.cern.ch/browser/#list/gts/75X_dataRun1_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_dataRun1_v0/75X_dataRun1_v4):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction.
- HLT: [76X_dataRun1_HLT_frozen_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_dataRun1_HLT_frozen_v0): As [75X_dataRun1_HLT_v2], snapshot time set to 2015-08-13 15:09:30 UTC, (https://cms-conddb.cern.ch/browser/#list/gts/75X_dataRun1_HLT_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_dataRun1_HLT_v0/75X_dataRun1_HLT_v2):
  - New HCAL parameters for HCAL topology (deprecated old record).
## Run2 simulation
- Ideal: [76X_mcRun2_design_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun2_design_v0): As [75X_mcRun2_design_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun2_design_v0/75X_mcRun2_design_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included;
  - Updated L1T menu for Stage1.
- Startup: [76X_mcRun2_startup_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun2_startup_v0): As [75X_mcRun2_startup_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun2_startup_v0/75X_mcRun2_startup_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
- Asymptotic: [76X_mcRun2_asymptotic_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun2_asymptotic_v0): As [75X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun2_asymptotic_v0/75X_mcRun2_asymptotic_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included;
  - Updated L1T menu for Stage1.
- Heavy Ion: [76X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_mcRun2_HeavyIon_v0): As [75X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/gts/75X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_mcRun2_HeavyIon_v0/75X_mcRun2_HeavyIon_v2):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction;
  - Updated detector description in the SIM geometries: the geometry in these tags is unchanged, only Hcal parameters are included.
## Run2 data
- Offline: [76X_dataRun2_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_dataRun2_v0): As [75X_dataRun2_v4](https://cms-conddb.cern.ch/browser/#list/gts/75X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_dataRun2_v0/75X_dataRun2_v4):
  - New HCAL parameters for HCAL topology (deprecated old record);
  - New Egamma regressions based on ECAL multifit reconstruction.
- HLT: [76X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/browser/#list/gts/76X_dataRun1_HLT_frozen_v0): As [75X_dataRun2_HLT_v2], snapshot time set to 2015-08-13 15:09:30 UTC, (https://cms-conddb.cern.ch/browser/#list/gts/75X_dataRun2_HLT_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/gts/76X_dataRun2_HLT_v0/75X_dataRun2_HLT_v2):
  - New HCAL parameters for HCAL topology (deprecated old record).

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@lgray restarting the tests won't make the errors disappear....

**Comment by lgray** [comment]
@mmusich ah, missed those, only saw the DAS errors at the bottom.

**Comment by diguida** [comment]
This PR must be massaged... I have to add new GT removing the SIM geometry and new HCAL parameters for the topology.

**Pull request closed without merging**
