### PR TITLE
[DD4hep] do not use namespace for navigation

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Strip a namespace off in a name comparison when navigate siblings
* Introduce `cms::DDFilteredView::fullName` that will return a current node name with a namespace
* Make `cms::DDFilteredView::name` return a current node name without a namespace

@fabiocos and @silviodonato - this fixes DT geometry unit test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
 - addpkg = Geometry/DTGeometryBuilder,Geometry/MTDGeometryBuilder,Geometry/MTDNumberingBuilder,MagneticField/Engine

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
> test parameters:
> 
> * addpkg = Geometry/DTGeometryBuilder,Geometry/MTDGeometryBuilder,Geometry/MTDNumberingBuilder,MagneticField/Engine

ok, I see you want me to fix all of them :-)

**Comment by smuzaffar** [comment]
I thought this should fix all of them :-)

**Comment by ianna** [comment]
> I thought this should fix all of them :-)

I'm on it

**Comment by smuzaffar** [comment]
please test
ok lets test it for Geometry/DTGeometryBuilder then

**Comment by ianna** [comment]
test parameters:

* addpkg = Geometry/DTGeometryBuilder,Geometry/MTDGeometryBuilder,Geometry/MTDNumberingBuilder

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - `MagneticField/Engine` tests run fine as well.

**Comment by ianna** [comment]
abort

**Comment by ianna** [comment]
test parameters:

* addpkg = Geometry/DTGeometryBuilder,Geometry/MTDGeometryBuilder,Geometry/MTDNumberingBuilder,MagneticField/Engine

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @ianna

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
merge
let's get rid of the unit test failures in the morning IB 
@kpedro88 let us know if you have any objections

**Comment by fabiocos** [comment]
@ianna thank you a lot for taking care of this quick fix. I am going to make an extensive test to check that everything looks ok, the unit tests dump a stripped version of the output, I am going to compare the complete version to ensure as much as possible that there are no further surprises (anyway we should see them in the tests...)

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@ianna ok, the full dumps do not show any difference but for the paths in the MTDCommonData, where as expected the namespaces are now again present. The numbering scheme anyway should be protected against this since a while, and indeed DetIds and positions do not look to be affected.

**Pull request merged**
