### PR TITLE
XML Units Checker

### PR DESCRIPTION
**Pull request by ianna**
This is a helper script to check units consistency
as discussed during Sim meeting.
 
To run
```
python UnitsCheck.py DetectorDescription/DDCMS/data/materials.xml
```
intended output:
```
...
Line # 4661 WARNING: Numerical values without units: 
   <MaterialFraction fraction="0.2158">

_______________________________^________
 
Line # 4665 Units defined: 
  <CompositeMaterial name="LYSO" density="7.11*g/cm3" symbol=" " method="mixture by weight">

__________________________________________^__________________________________________________

...
```
@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by civanch** [comment]
Hi Ianna,

material fraction is a unitless variable.

Cheers,
Vladimir

**Comment by davidlange6** [comment]
hi @ianna - 
as you mentioned to me - the print syntax should be updated - some examples in #23825

otherwise, modulo @civanch comment - maybe you should just make a GitHub issue with the results of your script on all the geometry files in cmssw? (somehow grouped if there are lots and lots)

**Comment by ianna** [comment]
@davidlange6 and @civanch - thanks! I'll update the script to use print function and exclude some obvious cases: MaterialFraction, etc.

**Comment by fabiocos** [comment]
@ianna a bit special case perhaps:

Line # 907 WARNING: Numerical values without units: 
  <CompositeMaterial name="C6F14" density="1.76*g/cm3" symbol=" " method="mixture by weight">

______________________________^_______________________________________________________________

the script does not technically fail, but some logic protection could improve its usefulness

**Comment by ianna** [comment]
@fabiocos - thanks! I'll fix it.

**Pull request merged**
