### PR TITLE
for neutral long-live exotic particles: only send their daughters to Geant4

### PR DESCRIPTION
**Pull request by zhangzc11**
See referebce: https://indico.cern.ch/event/568875/contributions/2397935/attachments/1459125/2253274/Marshall_MC4BSM_2017.05.13.pdf

### CODE REVIEW

**Comment by civanch** [comment]
@zhangzc11 , why you submit this to 9_2_X and not to 9_3_X first?
Second question: why you rename the method isExotics()?

**Comment by zhangzc11** [comment]
@civanch i think i am submitting this to 9_2_X now... 
answer to second question: for neutral exotic particles, they don't need be sent to Geant4, otherwise Geant4 won't deal with its decay properly. The old code only send the exotic particle to geant4 and the daughters are leftout, so I made this change to only allow charged exotic particles to Geant4. And the way i do is is by changing the isExotic function and add another charge judgement inside it. So to make it better represent the meaning of this function, i renamed this function to isExoticCharged.

**Comment by zhangzc11** [comment]
oh sorry, so i understand you concern... you are saying that we need to submit this to 9_3_X first... OK i will do that.
But about the second question, do you agree that i change the name of the function? https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=isExotic&type=  this function is only used in this file, so should have zero impact

**Comment by civanch** [comment]
Neutral exotics may decay within CMS or have interaction (potentially). I do not see the reason to rename. Instead, it would be good to have the same method names for run-2 2016 and 2017.

**Comment by zhangzc11** [comment]
@civanch yes, they can decay within CMS. But the problem with the old code is that the daughters are not sent to Geant4, and Geant4 can not deal with its decay properly. So instead, what we should do is that we do the decay in generator and then send the daughter to Geant4.

**Comment by zhangzc11** [comment]
See reference (page 12): https://indico.cern.ch/event/568875/contributions/2397935/attachments/1459125/2253274/Marshall_MC4BSM_2017.05.13.pdf

**Comment by civanch** [comment]
@zhangzc11 , when you will do PR for the master, please, rename back and also , please, consider following idea: previously several type of exotic particles were allowed to be tracked by Geant4, all previous pdg id should be still available. Of course, you may add new staff but not remove already working things.

**Comment by zhangzc11** [comment]
new PP to master here: https://github.com/cms-sw/cmssw/pull/20083

**Pull request closed without merging**
