### PR TITLE
Adding relval to test offlineHLTSourceOnAODextra

### PR DESCRIPTION
**Pull request by fabozzi**
Relval to test offlineHLTSourceOnAODextra sequence defined
in PR #20540 

@mtosi

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.7802

**Comment by fabozzi** [comment]
ok, I need to wait for the next IB...

**Comment by fabozzi** [comment]
please test workflow 136.7802

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
