### PR TITLE
Muon FSR recovery for miniaod and nanoaod [102X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport #28118 

Rebase of #28118 on the 10_2_X branch
@arizzi @gpetruc

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28135	11afdac  
- the backport of #28118 is correct (the same code changes are applied).
- this PR adds new producers at the level of muon analysis, to be used in the nanoAOD  workflows (not enabled in this PR, but included in the run time tests via #28145 ). The reco category is affected only in the DataFormats/PatCandidates/src/classes_def_objects.xml file where new dictionary declarations are added
- jenkins tests pass

**Comment by slava77** [comment]
I dropped +1 to get the #28221 addressed here as well

**Comment by peruzzim** [comment]
added backport of #28221, I'm going to do a joint re-test with #28145

**Comment by peruzzim** [comment]
@perrotta @slava77 could you please add back your signature as #28221 has been backported here? Thanks

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28135	5e271e9 
- updated to include a commit already added to the master in #28221 
- jenkins tests pass; the changes only in nanoAOD, thery are due to other PRs also included in the tests

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
