### PR TITLE
Validation/Geometry: No histos ROOT file being created by configuration scripts  && CleanUp

### PR DESCRIPTION
**Pull request by vargasa**
endOfRun() Method added to MaterialBudgetFormat.

In the past, the statement to save the histograms in a ROOT file
was written in the destructors of some classes, with the later use of
Smart Pointers the ROOT file was not being written.

`endOfRun()`, which should be called explicitly from `MaterialBudgetAction.cc`
includes a call to `TestHistoMgr::save()`.

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @vargasa, I can't seem to find you in the DQM contacts list. Could you please introduce yourself briefly?

**Comment by vargasa** [comment]
Hello @Andrius. [This is 
me](https://icms.cern.ch/tools/users/profile/13728), I'm working with 
@mmusich and @tsusa for the the MB Plots. Perhaps I should have quoted 
the [reason for this 
PR](https://github.com/cms-sw/cmssw/pull/23770#discussion_r219130500), 
my bad.

**Comment by mmusich** [comment]
Hello @andrius-k I support waht @vargasa stated here. 
He's developing for Tk DPG, with main focus on the material budget validation.

**Review by ianna — CHANGES_REQUESTED** [review]
Note, using delete on pointer returned by new[] results in undefined behaviour:
https://github.com/cms-sw/cmssw/pull/24625/files#diff-9fd1dea36a1cdc03a83c520e34169b8cR20
Please, consider using std::array.

**Comment by vargasa** [comment]
@ianna Thanks for revieweing it

**Comment by vargasa** [comment]
@ianna Regarding the `std:arrays` use. That's probably the reason why crashes when setting the `TreeFile` to `not-None` value (https://github.com/cms-sw/cmssw/blob/caf482382db301fe2dd96b1ca709f47a61464d7b/Validation/Geometry/test/runP_Tracker_cfg.py#L117). I replaced them in the last commit. Probably there is a more elegant way to do this. Please let me know

**Comment by andrius-k** [comment]
Hi @vargasa, could you please add your info in [this e-group?](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Tracker_SiStrips_and_Pixels)

**Comment by ianna** [comment]
+1

**Comment by andrius-k** [comment]
@vargasa Could you please also add your Github user name as well? You can do so by typing `git: <your username>` in the comments field.

**Comment by andrius-k** [comment]
+1

**Comment by vargasa** [comment]
Hi @fabiocos, @davidlange6, @slava77. If there's no other request for this PR, can you please merge it? Thanks :)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
