### PR TITLE
HLT menu development for `12_3_X` [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

This is the PR for the `master` branch, which will then be backported to `12_3_X` (which is currently the release used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2244](https://its.cern.ch/jira/browse/CMSHLT-2244): [TSG] Replace `PFJetsMatchedToFilteredCaloJetsProducer` by `HLTPFJetsMatchedToFilteredCaloJetsProducer`.
  - [CMSHLT-2252](https://its.cern.ch/jira/browse/CMSHLT-2252): [MUO] Update of muon isolation for Run 3.
  - [CMSHLT-2259](https://its.cern.ch/jira/browse/CMSHLT-2259): [TAU,EXO] Bugfix for dxy cut in displaced-tau trigger.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - the RelVals-INPUT error must be unrelated to this PR
 - differences in outputs of Run-3 wfs are compatible with the changes to the GRun HLT menu

**Comment by perrotta** [comment]
+1
- Open file issues in the RelVals-INPUT workflows are unrelated

**Comment by missirol** [comment]
@perrotta (just for my understanding..)

Did you mean to merge this, or just sign it? Because it looks like the bot didn't merge it..

**Comment by perrotta** [comment]
merge

**Comment by missirol** [comment]
> since there is a test error, it waits for me explicitly asking to merge.

Makes sense, I learned something new :)

**Pull request merged**
