### PR TITLE
74 Port changes from 73 to 74

### PR DESCRIPTION
**Pull request by alja**
This is a merge of development in 73:
git cms-merge-topic alja:cmsShow73-2

### CODE REVIEW

**Comment by alja** [comment]
+1

Before creating the PR I save the change is not automatically mergable. Let me know if there are any problems.

**Comment by alja** [comment]
What is a test for merge ?
I have tried git cms-merge-topic and this one worked without an error.

**Comment by Martin-Grunewald** [comment]
Hi @alja 
In your PR, get rid of your changes to 
RecoEgamma/EgammaHLTProducers/src/EgammaHLTRechitInRegionsProducer.cc
these are already in 74X and thus cause (some of?) the merge conflicts (and also requires
HLT signature for your PR which should not be the case anyway).

**Comment by alja** [comment]
Thanks Martin,
I have rebased to 74 and  don't see RecoEgamma changes anymore.

+1

**Pull request merged**
