### PR TITLE
Add TaggedProton filter for analysis with tagged protons [10_6_X]

### PR DESCRIPTION
**Pull request by michael-pitt**
This is backport from PR #40083

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40083

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
+1

**Comment by perrotta** [comment]
+1
- New filter added

**Comment by perrotta** [comment]
@michael-pitt @menglu21 @Saptaparna please notice that this filter is merged in master since 13_0_X and only backported to 10_6_X here. If needed for any other intermediate release, additional backports are in order.

**Pull request merged**
