### PR TITLE
Enable TensorFlowAOT unit tests, remove dev workflow.

### PR DESCRIPTION
**Pull request by riga**
#### PR description

This PR is a continuation of https://github.com/cms-sw/cmssw/pull/43941 and should be tested with https://github.com/cms-sw/cmsdist/pull/9093.

The development workflow for AOT compiling TensorFlow models was added to the PhysicsTools/TensorFlowAOT package in the above mentioned PR. However, with the new changes to the build process and deployment via cmsdist, these files can be removed again (as done in this PR). Instructions on how to locally AOT compile and use models for development purposes will be published on pages of the ML group soon.

#### PR validation

Since the pre-compiled test models are now provided as external tools, this PR enables the unit tests of the AOT interface that were already reviewed. They perform tests of a simple f32 -> f32 model, as well as a multi-input/output model with a f32,f64 -> f32,bool signature.

@Bogdan-Wiederspan @valsdav

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#9093

**Comment by smuzaffar** [comment]
@cms-sw/ml-l2 , can you please review this? This needs to go in along with https://github.com/cms-sw/cmsdist/pull/9093

**Comment by valsdav** [comment]
+ml 

Thanks a lot @riga @smuzaffar

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
