### PR TITLE
Run3-sim50 Use EcalSimulationParameters in ECalSD

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use EcalSimulationParameters rather DDCompressedView in ECalSD and the corresponding changes in the python scripts

#### PR validation:

Tested using runTheMatrix.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda What portion of the ECal sensitive detector DD4hep migration does this PR represent?

**Comment by bsunanda** [comment]
@cvuosalo I believe for ECAL this is now complete

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
