### PR TITLE
New cluster processor for GEM-CSC trigger

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In this PR I add a GEMClusterProcessor that converts GEMPadDigiCluster to GEMInternalCluster: an interface that takes care of the GEM-to-CSC coordinate transformation and knows if it's a single cluster or a coincidence cluster. This will replace the GEMCoPadProcessor in the next PR. The CSCGEMMatcher was extended with the "COSI" (consistency of slope index) mechanism, to check that the GEM-CSC bending angle corresponds to the CSC internal slope. This will be used in the GEM-CSC matching soon. The quality assignment and quality control classes were extended to be used with GEMInternalCluster. 

There are few other minor updates.
* A function in CSCMotherboard was made pass-by-ref instead of pass by value
* LUT generators produce missing index columns and missing headers

Requires https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/10

In the next PR I should finally remove CSCUpgradeMotherboard, and absorb CSCGEMMotherboardME11 and CSCGEMMotherboardME21 into CSCGEMMotherboard. Ultimately there should be two motherboards remaining (CSCMotherboard and CSCGEMMotherboard) down from 6. I'll also remove GEMCoPadProcessor and CSCUpgradeMotherboardLUT.

#### PR validation:

Run WF 11634.0. There shouldn't be changes in any WFs.
```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Jul 15 23:04:56 2021-date Thu Jul 15 22:41:31 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by dildick** [comment]
@rathjd fyi

**Comment by cecilecaillol** [comment]
please test with https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/10

**Comment by dildick** [comment]
Thanks @cecilecaillol. Just 7 failures, 6 from messagelogger, 1 from pixel.

**Comment by dildick** [comment]
Other than that, it looks good for me.

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
@qliphy Can you sign off, please?

**Comment by qliphy** [comment]
@cms-sw/l1-l2  Please also check and sign https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/10

**Comment by qliphy** [comment]
+1

**Pull request merged**
