### PR TITLE
[9_4_X] DeepDoubleCvL and DeepDoubleCvB tagger integration

### PR DESCRIPTION
**Pull request by fabiocos**
Dummy PR to let #25371 appear in the release notes/IB report (after squash in GitHub)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

dummy

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@smuzaffar now is should be enough to use the "Merge pull request" button, given that the title is already the bot merge comment, right?

**Comment by smuzaffar** [comment]
@fabiocos , no. Title should be 
```
[9_4_X] DeepDoubleCvL and DeepDoubleCvB tagger integration
```
i.e. same as #25371 and when you merge this PR then in the merge message change the PR number tp #25371 ( by default it will be #25614)

**Comment by fabiocos** [comment]
@smuzaffar ok, thanks, I see what you mean

**Pull request merged**
