### PR TITLE
[13_3_X] Run3 era for 2023 PbPb UPC re-reco

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of [#43378](https://github.com/cms-sw/cmssw/pull/43378) which creates a new era "Run3_2023_UPC" meant for the 2023 PbPb UPC re-reco.

#### PR validation:

Relval workflow 141.901 and private (documented in [slides](https://docs.google.com/presentation/d/1nK3r-i3EwV0YvkpJQb--lPLivD1NCmBTG-XZr__Xr0o/edit?usp=sharing))

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport from master (14_0_X) to 13_3_X

### CODE REVIEW

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43378

**Comment by mandrenguyen** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Comment by smuzaffar** [comment]
same reason and it is fixed now. Bot has properly added the `fully-signed` signature

**Pull request merged**
