### PR TITLE
E/gamma HLT L1 Track Isolation Producer & TTTrack typedef: 11_1_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This is allows track isolation with L1 tracks to be produced for electrons for the E/g Phase-II HLT

#### PR validation:

Tested in phase-II workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
backport of https://github.com/cms-sw/cmssw/pull/32594

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- backport of #32594 (identical)
- no differences in jenkins tests (none expected, code was not tested here)
- validation was done by the TSG team

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
