### PR TITLE
Sequence-based simplified HLT phase2 menu.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

This (large) PR is a rewrite of the Simplified Phase2 HLT Menu using sequences and abandoning the `cms.ConditionalTask`s almost completely. The notable exceptions are the Muons paths for which more expert help is needed to perform this transition.

The `timing` variant of the menu has been updated to include the recent move to L1P2GT and converted to using sequences as well.

Some of the `pset` configurations have been included in the PR even if they contain 0 changes. This is due to how the tool `edmConfigSplit` internally dumps those `pset`s. Rather than chasing all of them one by one, I decided to let it do its job.

Unused modules have been removed. If needed, they could be extracted from git.

#### PR validation:

Run before/after this PR on some 100 events and the results are identical.

All paths have been tested one-by-one to verify that they could run alone, w/o any other paths present.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
I'm not sure why the bot is convinced that we need a new package. The file he is complaining about is part of the git history (and was needed while developing the PR), but it is not part of the _final_ set of changes of this PR.
Ideas?

**Comment by Martin-Grunewald** [comment]
Remove and force-push?

**Comment by mmusich** [comment]
> Ideas?

Do we need the whole history? Otherwise squash the commits to 1.

**Comment by rovere** [comment]
Ciao @mmusich @Martin-Grunewald I added to the git history for a reason and would rather have it in.
The history has been already rewritten via several rebases. I would be in favour of not squashing it into 1 single commit.
Besides the bot being confused, is there any other drawback in leaving it in?

**Comment by Martin-Grunewald** [comment]
Hmm, the bot should not create a ```24834.0_TTbar_14TeV+2026D98/``` even if empty.
Maybe ask @smuzaffar on what to do here so that the bot gets rid of the ```new-package-pending``` status?

**Comment by iarspider** [comment]
@rovere This PR touches 430 files, thus causing the bot to fail. If this is intentional, I think the best course of action would be to split it this PR two or more - e.g., move 1a2126e9466a9f54956de790b5bc1c72870d6928 into a separate PR and remove it from history. You can use `please test with #XYZ` syntax to make bot merge additional PRs on top of this one for testing.

**Comment by rovere** [comment]
Ciao @iarspider thanks for your reply.
Can you clarify what do you mean by "causing the bot to fail"?
I'm not willing to split a PR based on the number of files changed.


> @rovere This PR touches 430 files, thus causing the bot to fail. If this is intentional, I think the best course of action would be to split it this PR two or more - e.g., move [1a2126e](https://github.com/cms-sw/cmssw/commit/1a2126e9466a9f54956de790b5bc1c72870d6928) into a separate PR and remove it from history. You can use `please test with #XYZ` syntax to make bot merge additional PRs on top of this one for testing.

**Comment by iarspider** [comment]
@rovere In order to reduce the number of GitHub API calls used per PR, the bot keeps a cache of some information regarding the PR (list of all commits, including squashed; list of files changed in each commit; reactions). That information is stored inside a comment, and thus is limited to 65k bytes. The bot will fail, i.e. it will not process a PR, if cache size is too big to be stored.

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
@rovere the bot won't be able to run the tests until the underlying issue (changing 430 files in a single PR) is fixed.

**Comment by rovere** [comment]
@iarspider it seems to me that the bot was able to run the tests before.

**Comment by iarspider** [comment]
> @iarspider it seems to me that the bot was able to run the tests before.

Yes - the bot cache was just below the limit intially (63176/65535), and now it is over the limit (68988).

**Comment by rovere** [comment]
> > @iarspider it seems to me that the bot was able to run the tests before.
> 
> Yes - the bot cache was just below the limit initially (63176/65535), and now it is over the limit (68988).

@iarspider are we sure we want to have such kind of limitation while testing our PRs?

**Comment by iarspider** [comment]
@rovere I will let @smuzaffar comment on that (but he is on vacation, so it may take some time for him to respond).

**Comment by mmusich** [comment]
this is still not passing the code-checks

**Comment by mmusich** [comment]
though I guess we can re-test it @rovere ?

**Comment by iarspider** [comment]
@mmusich Until the PR is slimmed down, no checks (even code-checks) will run properly.

**Comment by mmusich** [comment]
@iarspider let me iterate on https://github.com/cms-sw/cmssw/pull/44025?notification_referrer_id=NT_kwDOAE2NCLI5NTM2MDI2MjA2OjUwODIzNzY#issuecomment-1954247211 .
What's the underlying reason for the limitation ? Can we lift here ?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by iarspider** [comment]
> @iarspider let me iterate on #44025 . What's the underlying reason for the limitation ? Can we lift here ?

See my explanation here: https://github.com/cms-sw/cmssw/pull/44025#issuecomment-1953947069 . 
* To avoid resetting all signatures after each push, we need to keep track of what was changed in each commit
* Getting each commit's changes uses GitHub API call (at least one, but could be more if there are many changes in commit), so we cache that information, this cache is saved inside comment (for this PR, in [this](https://github.com/cms-sw/cmssw/pull/44025#issuecomment-1953804550) comment - the actual data is hidden to avoid confusion, I can email you a link to view it). We only save commit sha, commit timestamp and list of changed files.
* However, the comment size is limited to be 65536 bytes. So, if a PR has a lot of changes, the bot won't be able to write the cache back and will break.

**Comment by smuzaffar** [comment]
> @iarspider let me iterate on #44025 . What's the underlying reason for the limitation ? Can we lift here ?

@rovere @mmusich , 65K per comment limit is imposed by github. As @iarspider mentioned , bot uses an issue comment to cache the commits, files changed and signatues information. So it fails it comment size if over 65K. I guess we can fix it will letting bot to use multiple comments.

**Comment by iarspider** [comment]
please test

**Comment by mmusich** [comment]
@rovere this branch has conficts that need to be resolved before signoff.

**Comment by Martin-Grunewald** [comment]
code-checks

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
The regression in the `TriggerResults` is due to the changes in the `ecalRecHit` definition.
In the past version, there were 2 definitions of recHits: `ecalRecHits` and `hltEcalRecHits`, and they were both used, but the definitions to create them were different.
With this PR we create only 1 collection, the `hltEcalRecHits` that is identical as far as the configuration is concerned to the old `ecalRecHits`.

**Comment by rovere** [comment]
code-checks

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@rovere 

> Run before/after this PR on some 100 events and the results are identical.

the bot sees some differences in all the phase-2 workflows (e.g. [24834.0](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf24834_0_pr/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf24834_0_base/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;), [24834.911](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf24834_911_pr/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf24834_911_base/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;), [24896.0](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf24896_0_pr/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf24896_0_base/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;), [24900.0](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf24900_0_pr/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf24900_0_base/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;), [25034.999](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf25034_999_pr/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf25034_999_base/CMSSW_14_1_X-PRcmssw_44025-61548/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;) ).
In all cases the differences are in the paths `HLT_Mu50_FromL1TkMuon` and ` HLT_Mu37_Mu27_FromL1TkMuon` can you cross-check if it is expected?

**Comment by rovere** [comment]
code-checks

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+hlt
   * no residual changes in DQM nor reco product comparisons that are not already associated to known instabilities (see. https://github.com/cms-sw/cmssw/issues/43790)
   * changes reported in the [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-06-2300+008d13/61563/triggerResults) are likely coming from re-ordering of paths (no change in events gains or lost as also reported by the proponent)

**Comment by mmusich** [comment]
hold
   * @rovere I notice only now that there are very large differences in the ECAL and HCAL rechits in the phase2 workflows (it looks like the collections are empty now), see for example [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-06-2300+008d13/61563/validateJR/24834.0_TTbar_14TeV+2026D98/all_HLT_step2/). Is it expected ?

**Comment by rovere** [comment]
Ciao @mmusich thanks for these further checks. For completeness, these are the changes I made to the collections (to try and have a uniform approach and naming convention, far from being finalized, yet):

* `ecalRecHit:EcalRecHitsEB` $\to$ `hltEcalRecHit:EcalRecHitsEB`
* `ecalRecHit:EcalRecHitsEE` $\to$ `hltEcalRecHit:EcalRecHitsEE` (useless, it's empty by definition, should be removed in the long run)
* `hfprereco` $\to$ `hltHfprereco`
* `hfreco` $\to$ `hltHfreco`
* `horeco` $\to$ `hltHoreco`

I wrote a Python script that compares the entries (and their members) of these collections before/after the PR, and they are identical.

On a side note, I just realized that the new naming convention is such that the `hltHfprereco` is not part of the `FEVTHLTDEBUG` event content, since the rule is `keep *_hfprereco_*_*`.

Should we consider this as a shower-stopper for this PR to be merged or can we have another PR to fix this?

**Comment by mmusich** [comment]
Thanks @rovere for the checks. 

> I wrote a Python script that compares the entries (and their members) of these collections before/after the PR, and they are identical.

Can you link this from here? 

> Should we consider this as a shower-stopper for this PR to be merged or can we have another PR to fix this?

Let's go ahead, but please open a bug-fix PR as soon as possible.

**Comment by mmusich** [comment]
unhold

**Comment by rovere** [comment]
It is bread and butter, but it helped quite a bit:

[link](https://rovere.web.cern.ch/rovere/Phase2_HLT/utilities/compare.py)

**Comment by antoniovilela** [comment]
Let's move on with this, but for our knowledge: what is automatically generated and what is manually maintained from the 430 files?

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
> Let's move on with this, but for our knowledge: what is automatically generated and what is manually maintained from the 430 files?

@rovere

**Comment by mmusich** [comment]
> what is automatically generated and what is manually maintained from the 430 files?

we're not using confDB (yet) for phase-2, so this is completely manual (of course I guess @rovere used scripts to adjust and cross-check the configurations) @antoniovilela

**Comment by antoniovilela** [comment]
> @antoniovilela I mentioned the script used in the PR description. It is called `edmConfigSplit` and appropriately splits a fully expanded configuration into files and folders. All the configurations should be checked and maintained by the corresponding developers.

I guess what I wanted to make sure (just because of my current hat in ORP) is that there is no risk of affecting modules that can be used outside of the Phase 2 processing. I guess so, but it does not hurt to confirm.

**Pull request merged**
