### PR TITLE
[DQM] Changes suggested by new llvm18 clang-format

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR applies clang-format changes suggested by new llvm18 ( see https://github.com/cms-sw/cmssw/issues/45870 )

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 can you please review this PR? This container trivil changes for code-formats, only [non-white space change](https://github.com/cms-sw/cmssw/pull/45916/files?w=1) 
- dropping `;` from the end of inline methods 
- added space between `){}` for inline methods

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
