### PR TITLE
clang check modernize-deprecated-headers

### PR DESCRIPTION
**Pull request by davidlange6**
for comment (and likely not mergeable - this is what clang-tidy check modernize-deprecated-headers does

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
Indeed that looks like a C file, not C++

**Comment by slava77** [comment]
-1

This looks technically OK, but this is conditional on the modified code to actually compile

https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html
```
The check in its current form can break the code ...
```

**Comment by ianna** [comment]
-1

Please, use https://github.com/cms-sw/cmssw/pull/19606 to remove the need for geometry signature

**Pull request closed without merging**
