### PR TITLE
Modernized LocalFileSystem::readFSTypes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- replace fprintf with LogError
- manage resources with std::unique_ptr

#### PR validation:

code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

Unit test failure is in the IB

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
