### PR TITLE
HLT customisations for the Phase I HCAL upgrades

### PR DESCRIPTION
**Pull request by fwyzard**
Migrate HBHE reconstruction from `HcalHitReconstructor` to `HBHEPhase1Reconstructor`.  The HLT parameters for HBHE for Method 3 are a guess, based on the 2016 parameters.
    
Migrate HF reconstruction from `HcalHitReconstructor` to `HFPreReconstructor` + `HFPhase1Reconstructor`. The HLT parameters for HF are identical to those used by RECO, despite the differences that were present in 2016.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@Martin-Grunewald , @silviodonato , can you run this through the usual STORM integration tests and eventually sign ?

**Comment by fwyzard** [comment]
I guess `HLTHcalDigisInRegionsProducer` needs to be updated to support the new QIE11 digis

**Comment by kpedro88** [comment]
@fwyzard yes, `digiLabelQIE8` and `digiLabelQIE11` should get separate collections.

However, there should still be QIE8 digis for HB in the 2017 configuration, and the exception says it can't find those:
```
----- Begin Fatal Exception 20-Jan-2017 20:52:10 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'DST_DoubleMu3_Mass10_CaloScouting_PFScouting_v7'
   [2] Calling method for module HBHEPhase1Reconstructor/'hltHbherecoMethod2L1EGSeeded'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection<HBHEDataFrame,edm::StrictWeakOrdering<HBHEDataFrame> >
Looking for module label: hltHcalDigisMethod2L1EGSeeded
Looking for productInstanceName: 
```
I'm not sure why those would be missing.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@kpedro88 probably because I messed up the customisation :-)
let's try again...

**Comment by fwyzard** [comment]
please test

**Comment by silviodonato** [comment]
Hi @fwyzard ,
I tried to run the new code with phase 1 samples and Eras. 
I see a big drop of the rate/efficiency of HLT_DiPFJetAve60_HFJEC_v8 (21 -> 5, for 200 events of TTbar).
Is it expected? 
I was expecting differences in HF, but perhaps this is too large...

**Comment by fwyzard** [comment]
Did you get anything in HF without the customisation ?

**Comment by silviodonato** [comment]
I confused the two numbers. I see an increase of the rate/efficiency from 5 -> 21 for HLT_DiPFJetAve60_HFJEC_v8 including this PR and the proper Eras. So it was expected.

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
@fwyzard - given the upgrade plans for hcal, I guess PhaseI is a poor choice of names for this. It may be limited to 2017. Please consider updating it in a followup PR. Thanks

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
> given the upgrade plans for hcal, I guess PhaseI is a poor choice of names for this. It may be limited to 2017.

The HCAL module is still called `HBHEPhase1Reconstructor`, and according to the HCAL DPG developers we should use the new module anyway, also for the old HE.

In fact a more relevant comment would be whether  the customisation should be attached also to 2018 eras, or if it they will inherit the 2017 HBHE / HF eras.

**Comment by kpedro88** [comment]
Currently I have set up the Run2_2018 Era in #17198 as a chain of Run2_2017 and run2_HE_2017.

**Comment by fwyzard** [comment]
> Currently I have set up the Run2_2018 Era in #17198 as a chain of Run2_2017 and run2_HE_2017.

Right, because from pre3 `run2_HE_2017` is no longer part of `Run2_2017`.
So I should attach the migration to the `HBHEPhase1Reconstructor` directly to `Run2_2017` rather than `run2_HE_2017` , to pick it up anyway ?

**Comment by kpedro88** [comment]
The migration to HBHEPhase1Reconstructor should be attached to run2_HCAL_2017 (common Era for HCAL changes this year). That is what I have done in #17198.

**Comment by fwyzard** [comment]
Thanks Kevin, will make the change here as well.

**Comment by fwyzard** [comment]
Done in #17284

**Pull request merged**
