### PR TITLE
Remove CMS deprecated warnings from RecoRomanPot/RecoFP420

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Reworked some helper classes to be const correct
- Removed unnecessary includes
- Moved away from legacy module types

#### PR validation:

Code compiles and does not issue warnings anymore.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36586	ef611c4 
- code changes are technical, in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
