### PR TITLE
Gemcsc segment 75 x pr v3 addendum

### PR DESCRIPTION
**Pull request by pietverwilligen**
Addendum to PR9083 for GEMCSCSegment:
- fixed a customization (no more tracked to connect to condition db)
- added Buildfile in test directory
- fixed the initialization of std::unique_ptr

ideally should be backported also to 75X, but it has rather low priority I guess.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by pietverwilligen** [comment]
I removed the compilation error, the warning is due to a header file ("DataFormats/Common/interface/RangeMap.h"). I this not something I can/have to change? 

/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_6_X_2015-07-25-2300/src/DataFormats/Common/interface/OwnVector.h:416:33: warning: unused typedef 'ref_type' [-Wunused-local-typedef]

    typedef Ref      ref_type ;

**Comment by slava77** [comment]
@pietverwilligen I suggest to leave the DataFormats/Common be, it's present in the IBs
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_6_CLANG_X_2015-07-27-2300/DataFormats/Common

**Comment by civanch** [comment]
please test

**Comment by Dr15Jones** [comment]
I've taken care of the clang warning with #10427

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10397	d0cfbd5
- code changes are OK (not affecting current pp; fixes improve code management, and also fix some bugs in configs needed for upgrade tests)
- jenkins tests pass and comparisons with the baseline show no difference as expected

**Comment by davidlange6** [comment]
+1

**Pull request merged**
