### PR TITLE
Run2-hcx161 Allow Plan1 geometry to work for standard access of getPosition

### PR DESCRIPTION
**Pull request by bsunanda**
Backport PR #20868 which is integrated to 9_4_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Please approve this

**Comment by ianna** [comment]
@bsunanda - please, see my comment on https://github.com/cms-sw/cmssw/pull/21030#pullrequestreview-72499626

**Comment by bsunanda** [comment]
@ianna I have responded - I use the base method in some test routines

**Comment by bsunanda** [comment]
@ianna Have taken care of it

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
