### PR TITLE
2018 HLT HIon menu V1.0

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
2018 HLT HIon menu V1.0
Based on CMSSW_10_3_0_pre6
Superseeding #25030

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1
for addOnTests.py

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Superseeded by #25167

**Comment by Martin-Grunewald** [comment]
Reopen this PR for integration, as backport of the menu undergoing validation in 104X.

**Comment by Martin-Grunewald** [comment]
Yes, correct!

**Pull request merged**
