### PR TITLE
Removal of "50ns" labeled SiPixelDynamicInefficiency tags

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Removal of "50ns" labeled SiPixelDynamicInefficiency tags as requested in [1] by the Pixel Offline group. In case when the simulations require 50 ns bunch spacing the previously labeled (50 ns specific) payload is used. Code changes and validation can be found in the PR34502 [2]. The differences of the new and old GTs can be found in [3].

This PR contains the removal of the  unused key run1_mc_pa as well.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4431.html
[2] https://github.com/cms-sw/cmssw/pull/34502
[3] https://docs.google.com/spreadsheets/d/1FlABJmzWOrxKaNSUD_N980GQeO9ecYj4C8xXcl4IMNE/edit?usp=sharing

#### PR validation:

runTheMatrix.py -l limited,140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24 --ibeos -j8

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport, and backport is not needed

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:

  - workflow = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24
  - pull_request = #34502

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

- The failures in the comparison plots are affecting run1_mc, only on variables that are related to tracking and vertexing (as expected).
- run1_mc_pa autoCond key does not seem to be used anywhere in CMSSW so it makes sense to remove it.

**Comment by tvami** [comment]
Hi @silviodonato, @dpiparo, @qliphy, @perrotta , this PR requires https://github.com/cms-sw/cmssw/pull/34502 as well. I'm wondering if the "requires-external" label makes it sure that this PR is not merged until the "external" is merged too? Thanks!

**Comment by davidlange6** [comment]
hi - if the "previously labeled (50 ns specific) payload" is still used for 50ns simulations why does the physics  outcome change? (eg, why is this not purely a technical change?)

**Comment by tvami** [comment]
I made a quick study about this, here is the link
https://indico.cern.ch/event/1000813/contributions/4447059/attachments/2281939/3880637/20210714_PixelMeeting_DynEffCheck.pdf

I think this is the answer to the question:
the Run-1 MC use two different conditions:
• For noPU, the bunch spacing is 450 ns and no inefficiencies are simulated
• For PU wf 50 ns bunch spacing is used with realistic inefficiencies from 2012 data

We assumed that the realistic inefficiency tag will give 100% efficiency if PU=0, and the plots in the presentation for the efficiency seem to support that. So I think we dont expect a fully technical change for Run-1 MC, but the differences should be very small.

**Comment by tvami** [comment]
With @carolinecollard we tested the two problematic wf-s, the efficiency results are plotted here

https://tvami.web.cern.ch/tvami/projects/PixelOffline/DynEffValidation/wf25/?match=ffic

https://tvami.web.cern.ch/tvami/projects/PixelOffline/DynEffValidation/wf9/?match=ffic

and show no significant changes.

**Comment by mmusich** [comment]
Shall this be closed now?

**Comment by tvami** [comment]
Included in the PR https://github.com/cms-sw/cmssw/pull/34502

**Pull request closed without merging**
