### PR TITLE
Add wf 140.56 to the short matrix as requested by RECO

### PR DESCRIPTION
**Pull request by fabiocos**
Addressing the discussion in https://github.com/cms-sw/cmssw/pull/25210#issuecomment-439061085

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 140.56 with #25210

**Comment by fabiocos** [comment]
let's take note of https://github.com/cms-sw/cmssw/pull/25210#pullrequestreview-175890718

**Comment by slava77** [comment]
140.56 here took only 90 mins (from ~19:30 to 21:00).
If I parsed the build  info correctly, this was on cmsbuild02.
I guess this machine is almost a factor of 2 faster than mine.
@smuzaffar what type of hardware is this. Do you know?

**Comment by fabiocos** [comment]
@slava77 @smuzaffar on cmsdev15 in single threaded mode I get

TimeReport> Time report complete in 5001.44 seconds
 Time Summary: 
 - Min event:   7.24736
 - Max event:   345.884
 - Avg event:   162.316
 - Total loop:  4917.85
 - Total init:  61.1077
 - Total job:   5001.44
 - EventSetup Lock:   0.000586987
 - EventSetup Get:   44.8936
 Event Throughput: 0.00610023 ev/s
 CPU Summary: 
 - Total loop:  4908.42
 - Total init:  65.3921
 - Total extra: 0
 - Total job:   4994.66
 Processing Summary: 
 - Number of Events:  30
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1

Begin processing the 1st record. Run 326479, Event 1394020, LumiSection 7 on stream 0 at 16-Nov-2018 19:51:38.832 CET
Begin processing the 30th record. Run 326479, Event 1517636, LumiSection 7 on stream 0 at 16-Nov-2018 21:09:31.770 CET

this should be enough not to give TimeOut problems, the point is how well this is representative of the typical node used @smuzaffar

**Comment by fabiocos** [comment]
after discussing with @smuzaffar I suggest to merge this in production and monitor whether we are observing issues. No problem is detected in IB, for PR tests the rules should be more stringent, but apparently we may stay within the 2 hours budget. Should this cause failures in tests we may squeeze the number of events

**Comment by davidlange6** [comment]
i'd suggest that 10-20 minutes is a good target for any short matrix workflow length..

**Comment by fabiocos** [comment]
I did a quick survey of the short matrix jobs time length, using a virtual machine of mine loaded just with a single threaded job, so one could have a reasonable relative comparison of different workflows. The absolute scale obviously depends on the machine itself. Most of them are in the 10-12 minutes range, including 140.53 with the noticeable exception of 136.85 that reaches ~ 30 minutes. So if we do not want to exceed this value (the slowest workflow should drive the maximum amount of time taken by the test according to what i understood from @smuzaffar ) we need a number of events that allows to stay in that range. On my machine 30 events for 140.56 took ~ 80 minutes, so in order to stay on the safe side one should consider 10 events.

Adding "-n 10" to RECOHID18 does the job, simultaneously reducing the number of events for 140.57, that anyway I understand is not so much interesting.

@slava77 is this meaningful for you?

**Comment by slava77** [comment]
On 11/20/18 2:21 AM, Fabio Cossutti wrote:
> Adding "-n 10" to RECOHID18 does the job, simultaneously reducing the
> number of events for 140.57, that anyway I understand is not so much
> interesting.
> 
> @slava77
> is this meaningful for you?
> 

That's fine.
Thank you for the investigation.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
In the test the wf 140.56 was executed in about 40 minutes, roughly as 136.85. I would say we can move forward and keep an eye on possible issues at this point (in a couple of weeks this test might be no more so useful)

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this is not specific for upgrade, please sign it for reference in case

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
