### PR TITLE
Phase2-gex154B Fix the issue of 2026D91 which can now work in the dd4hep version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix the issue of 2026D91 which can now work in the dd4hep version. In the earlier version, any cmdim job with this scenario and dd4hep used to crash in the very first event with
----- Begin Fatal Exception 21-Feb-2023 12:20:44 CET-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing global begin Run run: 1
   [1] Prefetching for module OscarMTProducer/'g4SimHits'
   [2] Calling method for EventSetup module TrackerGeometricDetESModule/'trackerNumberingGeometry'
Exception Message:
No data of type "DDCompactView" with label "" in record "IdealGeometryRecord"

Now the dd4hep job with that scenario runs normally

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need to be back ported to 13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
@bsunanda could you please add to the description what is the issue that this PR is fixing?
I.e. why D91 was not able to work with dd4hep, and what this PR fixes in practice to allow it?

**Comment by srimanob** [comment]
please abort

**Comment by srimanob** [comment]
test parameters:
- workflow = 22034.911

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
test parameters:
- workflow = 22034.911
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Do I misunderstand something on the workflow to test?
22034.911 is a ttbar with 2026D91_DD4hep, https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0517d/30786/runTheMatrix-results/22034.911_TTbar_14TeV+2026D91_DD4hep/

**Comment by bsunanda** [comment]
The command is pulling in a statement
process.load('Configuration.StandardSequences.GeometryRecoDB_cff')
which causes the problem. Somehow this should be avoided

**Comment by bsunanda** [comment]
I removed that line by hand and the test went through. Please fix the component in PyReleaseValidation

**Comment by srimanob** [comment]
Thanks @bsunanda 
I am looking at it.

**Comment by srimanob** [comment]
hold

Looking into an issue of the workflow, and provide PR if need.

**Comment by bsunanda** [comment]
I am making a fix and submit it in an hour. I am testing the fix now
________________________________

**Comment by srimanob** [comment]
Is this one, 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py#L267 ?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob As you see it was in GeometryConf.py

**Comment by bsunanda** [comment]
@srimanob please uphold this and put it as a bug fix. Like to backport this to 13_0

**Comment by srimanob** [comment]
unhold

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@perrotta @rappoccio Please approve and integrate this bug fix. Need to backport this to 13_0_X

**Comment by perrotta** [comment]
+1

**Pull request merged**
