### PR TITLE
Fixes to TrackInfoProducer

### PR DESCRIPTION
**Pull request by makortel**
This PR 
* removes unused variable (fixes a clang warning)
* fixes a memory leak by removing an unnecessary `new` and copy-construction

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I wonder if these classes are still useful (last non-technical commit is from 2007). If they are not, could we consider removing them?

**Comment by makortel** [comment]
The 1325.7 step2 segfaults in
```
#4  <signal handler called>
#5  0x00007f4b907b5000 in ?? ()
#6  0x00007f4be1a0172e in TFormula::DoEval(double const*, double const*) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_5_X_2019-01-28-1100/external/slc7_amd64_gcc700/lib/libHist.so
#7  0x00007f4be1a01915 in TFormula::Eval(double, double, double, double) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_5_X_2019-01-28-1100/external/slc7_amd64_gcc700/lib/libHist.so
#8  0x00007f4be19d88f4 in TF1::Eval(double, double, double, double) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_5_X_2019-01-28-1100/external/slc7_amd64_gcc700/lib/libHist.so
#9  0x00007f4bb8972194 in BTagCalibrationReader::BTagCalibrationReaderImpl::eval_auto_bounds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, BTagEntry::JetFlavor, float, float, float) const () from /cvmfs/cms-ib.cern.ch/nweek-02561/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_5_X_2019-01-27-0000/lib/slc7_amd64_gcc700/libCondToolsBTau.so
#10 0x00007f4bb8a9330a in BTagSFProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_5_X_2019-01-28-1100/lib/slc7_amd64_gcc700/pluginPhysicsToolsNanoAODPlugins.so
```
I see no references to `TrackInfo` in either `BTagCalibrationReader` or `BTagSFProducer`.

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try again.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
