### PR TITLE
Muon hlt dqm by filter

### PR DESCRIPTION
**Pull request by folguera**
Modification of the Muon HLT sequence to draw the plots at every filter step no need to monitor all paths as the modules can be shared by more than one path (i.e. removed all non-isolated paths).

### CODE REVIEW

**Comment by folguera** [comment]
@vanbesien could you please launch the tests? so we can move forwrard with this PR? Thanks!

**Comment by vanbesien** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
