### PR TITLE
Adding ZMM fragment at 14TeV pythia8

### PR DESCRIPTION
**Pull request by calabria**

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
@calabria because the upgrade workflows numbering depends on the order in the wf list, it would be better to add upgrade wfs in a order.
we see there is another PR #16497 comes earlier than this one adding new wfs, @calabria could you please merge that PR's branch to your branch so as to have a test together? 
thanks! 
best, hengne

**Comment by calabria** [comment]
@hengne the PR can not be automatically merged to my branch there are some differences. Shall I continue anyway?

**Comment by perrozzi** [comment]
+1

**Comment by hengne** [comment]
@calabria let's simple process this pr as it is now. @kpedro88 has merged your pr here and Josh's PR #16497 together with many other new workflows in PR #16535 , will solve all the conflicts there.

**Comment by hengne** [comment]
+1

**Comment by kpedro88** [comment]
hold

**Pull request closed without merging**
