### PR TITLE
Phase2-hgx194 Add new method maskCell to topology or RecHitTool

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use a method maskCell to show if the given cell is masked due to truncation of the wafer

#### PR validation:

Tested with standard workflows

#### if this PR is a backport please specify the original PR:

No backport is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- The method maskCell is implemented for HGCalTopology and HGCalRecAlgos.RecHitTools, its usage not yet being propagated to the actual code though
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
