### PR TITLE
Migration of HLT menus to 11_1_0 template (11_2_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration of HLT menus to 11_1_0 template (11_2_X)
Based on CMSSW_11_2_X_2020-07-05-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
@Martin-Grunewald I looks like an efficiency plot disappeared, see https://tinyurl.com/yapyuhcy. Is it expected?

**Comment by Martin-Grunewald** [comment]
@silviodonato 
No, it is not expected. This PR does not touch any plot generation or renames things, so it must be an unrelated (reproducubility?) issue. The backport PR jenkins does not report any changes...

**Comment by silviodonato** [comment]
please test
in any case, I will merge this in 11_2_0_pre2. I'm just curious to understand this small difference.

**Comment by missirol** [comment]
> @Martin-Grunewald I looks like an efficiency plot disappeared (effic_dev_CMSSW_11_1_0_GRun_V11), see https://tinyurl.com/yapyuhcy. Is it expected?

@silviodonato

Maybe I'm missing something, but it looks like "V11" is the plot appearing post-PR, and missing pre-PR. That would be consistent with [this change](https://github.com/cms-sw/cmssw/pull/30549/files#diff-5450916cd3da4692909c1ad6f1b28058R10); if so, I guess the same should happen in the backport.
For reference, the plot is named using `HLTConfigProvider::tableName`, [here](https://github.com/cms-sw/cmssw/blob/CMSSW_11_1_0/DQMOffline/Trigger/plugins/HLTFiltersDQMonitor.cc#L148).

**Comment by silviodonato** [comment]
+1

**Pull request merged**
