### PR TITLE
Slhc26 me0 segment time pr v2

### PR DESCRIPTION
**Pull request by pietverwilligen**
Cleaned up version of closed PR #12370. It includes:
- time in ME0Segment DataFormat
- time clustering in ME0Segment Algorithm
- rewritten version of Neutron Background simulation in ME0PreReco Digitizer
- bool to distinguish Neutron Background from Prompt Background in ME0PreReco DataFormat
- handles to reconstruct only muons, muons+prompt, muons+prompt+neutron  in ME0 RecHit

### CODE REVIEW

**Comment by pietverwilligen** [comment]
I tested it in CMSSW_6_2_SLHCDEV_X_2015-11-29-1100 with scram b clean and scram b -k -j 8
 and it compiled. Can you please test?
Thanks
Piet

**Comment by pietverwilligen** [comment]
SLHCDev branch deviates here from what we have ported to 800 (PR #12383). In 800 we removed MC Truth configuration from the RECO step, while here we maintain it for ME0 studies.

**Comment by fratnikov** [comment]
please test

**Comment by pietverwilligen** [comment]
Bugfix + addition of logdebug messages. Please test.

**Comment by fratnikov** [comment]
please test

**Comment by pietverwilligen** [comment]
Dear All

Can someone tell me whether this will be integrated in the next integration build? Are there any plans to have a SLHC28 release?
Thanks a lot
Kind regards
Piet

**Comment by fratnikov** [comment]
@pietverwilligen I see no problem of putting this into IB. @davidlange6  could comment on possible release schedule

**Comment by davidlange6** [comment]
There are no further release plans for 62xslhc*. Of course the upgrade project can bring up urgent needs via a future TP meeting.

On Dec 11, 2015, at 9:51 PM, Fedor Ratnikov <notifications@github.com<mailto:notifications@github.com>> wrote:


@pietverwilligen<https://github.com/pietverwilligen> I see no problem of putting this into IB. @davidlange6<https://github.com/davidlange6> could comment on possible release schedule

**Comment by fratnikov** [comment]
merge

**Pull request merged**
