### PR TITLE
[91X] Unify alignment producers

### PR DESCRIPTION
**Pull request by ghellwig**
Previously two parallel code infrastructures in place for offline and PCL alignment
 - Offline: `AlignmentProducer` → `edm::ESProducerLooper`
 - PCL: `PCLTrackerAlProducer` → `edm::EDAnalyzer` (legacy!)

Most of the code is just duplication with more than 1000 lines of redundant code, i.e. it is hard to maintain.
In addition, only the PCL code is routinely tested during CMSSW software integration in workflow 1001.

This PR unifies the two alignment producers by means of a common base class `AlignmentProducerBase` which provides the common implementation.
`AlignmentProducer` now inherits from `AlignmentProducerBase` and `edm::ESProducerLooper`.
`PCLTrackerAlProducer` is renamed to the more generic `AlignmentProducerAsAnalyzer` which now inherits from `AlignmentProducerBase` and `edm::one::EDAnalyzer`.

This means easier maintenance and multi-threading friendliness. The latter applies not only to the PCL workflow, but also the offline MillePede workflow which is migrated the `edm::one::EDAnalyzer` version of the alignment producer.
As a bonus, the main part of the offline alignment code is now routinely exercised during integration tests.

This changes has also been presented at the [last Tracker Alignment meeting](https://indico.cern.ch/event/607510/contributions/2533635/attachments/1436040/2208307/Alignment-UnifiedAliProducer_CMS-TkAl_20170329.pdf).

This PR includes also some minor fixes regarding the transition to phase-1.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
ok, let's wait until #18137 is merged...

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
rebased now that #18137 is merged

**Comment by arunhep** [comment]
please test
comparisons are not available now, rerunning the tests.

**Comment by ghellwig** [comment]
please test

**Comment by arunhep** [comment]
+1
the tests failed because of xrood/eos errors. but they have passed in earlier runs.

**Pull request merged**
