### PR TITLE
Add QuadJet with 3 b-tag PNet trigger to the DQM offline

### PR DESCRIPTION
**Pull request by brunolopesbr2**
#### PR description:

Added the Particle Net migrated version of the QuadJet with 3 b-tag trigger to the offline DQM. This trigger path was approved by TSG on March 13th (https://indico.cern.ch/event/1389073/).

As pointed out in the JIRA CMSHLT-3119, the validation strategy should be the same as the previous version of the path (using DeepJet), so it was copied over from the top DQM code with the necessary parameter changes. It's now important only to the Exotica PAG, so it was included in the Exotica DQM.

#### PR validation:

The DQM code was validated using a runTheMatrix workflow (modified to use the new trigger path). The resulting DQM file was uploaded to the DQM GUI at http://dqm-dev-test.cern.ch:8060/dqm/dev/ and it's a RelVal file. In particular, check that the new DQM plots are being created at the new HLT/EXO/DisplacedVertices/* folder and are populated with the passing events.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 can you please review this? It would be good to have this integrated once we deliver the next HLT menu 2024 V1.1

**Comment by tjavaid** [comment]
@brunolopesbr2 , could you please provide the link to the new DQM plots you obtained from validation studies ?

**Comment by brunolopesbr2** [comment]
Hi @tjavaid , I don't know exactly a way to get a direct link, but if you go to http://dqm-dev-test.cern.ch:8060/dqm/dev/ , click on the yellow "Run #" on the top, select the only available file and go to HLT -> EXO -> DisplacedVertices -> FullyHadronic, you can see the two folders with the new plots, one being for the signal trigger path and the other for the backup path. The distributions are not as meaningful because of the limited statistics, but the point was to actually test that the histograms are being populated correctly. It may be necessary to set up a tunnel to access the referred link from outside CERN. I can provide the original ROOT file if helpful.

**Comment by brunolopesbr2** [comment]
A more detailed description of the workflow used to validate the DQM as well as the monitoring strategy are available here: https://docs.google.com/document/d/1ffuOSalsq6zcJDVOzwivoSN4JpmdDAxPLhTF-524d9o/edit?usp=sharing

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
