### PR TITLE
add offlineHLTSourceOnAODextra sequence

### PR DESCRIPTION
**Pull request by mtosi**
as discussed at the XC meeting
it would be probably safer to have a dedicated `cms.Sequence` for testing new DQM code for HLT
which is meant to be used in the HLT validation workflow, but not necessarily at Tier0

new DQM code should be integrated in the offlineHLTSourceOnAODextra sequence
and then it could be ported in the standard offlineHLTSourceOnAOD one (which is run at Tier0)

@fwyzard @gennai @davidlange6 @franzoni

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
@fabozzi @mtosi -please also add a simple cmsDriver workflow to runTheMatrix that tests this new sequence. Thanks

**Comment by davidlange6** [comment]
ping @fabozzi?

**Comment by fabozzi** [comment]
maybe @mtosi should send around a cmsDriver for this?

**Comment by mtosi** [comment]
it is the same as last time ....
but using
offlineHLTSourceOnAODextra
instead of
offlineHLTSourceOnAOD

**Comment by fabozzi** [comment]
ok, the new relval is in this branch:
https://github.com/cms-sw/cmssw/compare/master...fabozzi:from-CMSSW_9_4_X_offlineHLTSourceOnAODextra

i.e. the commmit:
https://github.com/cms-sw/cmssw/commit/54d580c0e83f5b837ba26a5b1e73a29c0e931d32

Can you add it in this PR so that they can be tested together?

**Comment by davidlange6** [comment]
hi @fabozzi - thanks - I'll just merge this PR and let you make a separate PR.

**Comment by davidlange6** [comment]
+1

**Comment by fabozzi** [comment]
ok, thanks a lot

**Pull request merged**
