### PR TITLE
Updating HLT paths for TopMuEGSkim

### PR DESCRIPTION
**Pull request by soureek**
#### PR description:
Related to PRs [#42064](https://github.com/cms-sw/cmssw/pull/42064) and [#42057](https://github.com/cms-sw/cmssw/pull/42057/).

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by youyingli** [comment]
@cms-sw/pdmv-l2, could you please sign this PR and its backports (https://github.com/cms-sw/cmssw/pull/42064 and https://github.com/cms-sw/cmssw/pull/42057) ?

**Comment by youyingli** [comment]
@sunilUIET, could you please sign this PR?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
