### PR TITLE
[L1T] Backport: Add PF developments for L1T phase-2 

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/38230, needed for Phase-2 L1 MC production

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
I believe this error is not related to this PR, so it can be merged from our side

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
@cecilecaillol I hope you can understand that it will not be appropriate to backport this PR until a fix for the issues and cleanings that you mention in https://github.com/cms-sw/cmssw/pull/38230#issuecomment-1151550378 is available in the master, and it is also backported here. Please keep us informed about the status of those fix PRs, and their backports

**Comment by cecilecaillol** [comment]
hold

**Pull request closed without merging**
