### PR TITLE
bsunanda:Run2-hcx117 Make right treatment of neutral filter

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 @smuzaffar The failure is not due this PR. Please take a look

**Comment by ianna** [comment]
+1

Note: in some cases depth == 0 becomes depth == 1

**Comment by civanch** [comment]
@bsunanda , why the title and description of this PR is different from #17948? Se my comments there.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , sorry, may be I do not fully understand the logic of the code but why if (numberingScheme) is not applied in the block of lines 1100-1115?

Also you may copy title and description from 9_0_X PR to this PR, so they are identical.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 @smuzaffar The failure is not due to this PR. There may be something wrong for the test 101

**Comment by bsunanda** [comment]
@ianna @civanch Please approve this

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
