### PR TITLE
PR for HLT online DQM monitoring code for Proton-Lead run in 80X (upd…

### PR DESCRIPTION
**Pull request by varuns23**
…ated #16355

@mtosi @silviodonato @diguida @vanbesien @dmitrijus 

PR made using CMSSW_8_0_X_2016-11-02-1100

### CODE REVIEW

**Comment by diguida** [comment]
@varuns23 thanks for the follow-up changes. Can you please add this PR to the [DQM Twiki for 2016 pPb](https://twiki.cern.ch/twiki/bin/view/CMS/DQMHeavyIon2016)?

**Comment by varuns23** [comment]
Added

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I see you have renamed HeavyIons to ProtonLead for some files and changed them a bit.
Shoudn't one keep the original HeavyIons files around as we will have PbPb runs in the future?

**Comment by varuns23** [comment]
Yes, the code structure need some modification. But as there is limited time for Proton-Lead run, we went ahead with the present setup and renamed HeavyIon to ProtonLead as suggested by Salvatore. Moreover PbPb run is not going to happen until late 2018. So removed it to avoid any confusion.

**Comment by diguida** [comment]
@Martin-Grunewald Besides what @varuns23 just pointed out, in the current implementation of the "Heavy Ion" module, the monitored paths are specific for "Proton Lead", which looks even more confusing, IMHO.

**Comment by davidlange6** [comment]
is there an actual change to the plugin besides a cool new name?

**Comment by varuns23** [comment]
Yes, there are some changes besides name change. The important one is in the hlt_dqm_sourceclient-live_cfg.py  config file, where it now loads the protonlead module. Earlier it was set to pick module depending on the run key and we are having the same run key as pp for PA so it was not using the correct module.

**Comment by diguida** [comment]
@davidlange6 As pointed out by @varuns23 the most important change is for DQM online operations. For the rest, apart from the plugin renaming, there are two minor fixes in the plugin itself:

* load event collections whose names are provided in the configuration;
* remove the token for an event collection not used afterwards.

**Comment by davidlange6** [comment]
so keep the old name of the plugin, make the trivial functionality change (the unused token) and just make a new cfi with the cool new name. Then by doing less work you preserve the PbPb functionality and get the new pPb functionality

**Comment by varuns23** [comment]
@davidlange6 I did not get your point. You want me to revert to HLTObjectMonitorHeavyIon.cc and rename which cfi?

**Comment by davidlange6** [comment]
> On Nov 2, 2016, at 4:53 PM, varun sharma <notifications@github.com> wrote:
> 
> @davidlange6 I did not get your point. You want me to revert to HLTObjectMonitorHeavyIon.cc and rename which chi?


Right - rename nothing, make a _new_ config with your pA specific name and changes

**Comment by diguida** [comment]
@davidlange6 what you propose is the ideal fix. Even better, there should be no need to define a new plugin for HI or pA either, but just to define a new instance of the plugin with the new name and the correct configuration. BTW, it has been *never* created a plugin for PbPb, in [the version of the "Heavy Ion" module in `CMSSW_8_1_X_2016-11-02-1100`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X_2016-11-02-1100/DQM/HLTEvF/python/HLTObjectMonitorHeavyIon_cfi.py), the monitored paths are specific for "Proton Lead", which looks even more confusing, IMHO.

The joint modifications of this and #16355 PRs allow to monitor some specific pPb paths for the pPb data taking period only.

On the longer term, DQM and STEAM have discussed some ideas to completely restructure the code, in order to make the `C++` module deal with the paths defined in the HLT menu of the analysed run; as it is now, the `C++`plugin depends on the `python` configuration, which is a design flaw.

**Comment by davidlange6** [comment]
ok so its just a big mess

**Comment by diguida** [comment]
@davidlange6 practically, yes :-(

**Comment by varuns23** [comment]
@davidlange6 Yes, its a bit complicated. We have already taken suggestion from @diguida and work for a better structure setup. But I think for now it is important to monitor the present Proton-Lead run and the present setup should be able to do it.

**Comment by dmitrijus** [comment]
+1

**Comment by varuns23** [comment]
Any update from hlt or orop side?

@mtosi @silviodonato @diguida @vanbesien

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
