### PR TITLE
Miscellaneous improvements to `Alignment/MillePedeAlignmentAlgorithm` unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all:
   * minor improvements in `ZMuMuMassConstraintParameterFinder` plugin: https://github.com/cms-sw/cmssw/commit/e868d3db426c8657b5796d3f149ba318181721ea
   * improve `Alignment/MillePedeAlignmentAlgorithm/test/ZMuMuMassConstraintParameterFinder/README.md` https://github.com/cms-sw/cmssw/commit/d8e577ba75a56f0af0feb841bf6ca581e26465be
   * improve test_payload_sanity: https://github.com/cms-sw/cmssw/commit/3cc467e35f5ca04598e9a45705cc339d72dfe4a9
   * add unit tests for `ZMuMuMassConstraintParameterFinder`: https://github.com/cms-sw/cmssw/commit/3dcb4a4e149860a0443505c5442da901237f4a48

#### PR validation:

`scram b runtests` runs fine

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
