### PR TITLE
Backport of "Turn off Cluster Repair for 0T data (26940)"

### PR DESCRIPTION
**Pull request by OzAmram**
This is a backport of [PR 26940](https://github.com/cms-sw/cmssw/pull/26940). This is fix to allow running on 0T data will be needed in 10_6_X at some point. Likely for future tier 0 replays.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
backport #26940

**Comment by pohsun** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27044	db03cb9
- this is a trivial backport (of https://github.com/cms-sw/cmssw/pull/26940	db03cb9): the same topic branch is used and the same commit ID.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by slava77** [comment]
@fabiocos 
this will be needed for the data taking.
Please check and merge or comment.
Thank you.

**Comment by fabiocos** [comment]
@slava77 I know, thank you for the reminder. Depending on the timescale of next build I will merge it, in principle pre1 RelVals might run earlier (not a big test for this PR, still more extensive than the PR test itself).

**Comment by drkovalskyi** [comment]
FYI @mariadalfonso

**Comment by fabiocos** [comment]
+1

**Pull request merged**
