### PR TITLE
Removed unnecessary deprecated header in JetSignalVertexCompatibility

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Part of the cms deprecated header cleanup campaign.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by Dr15Jones** [comment]
The RelVal failure is from DAS and has no relationship to this PR. The only test that needed to pass is compilation.

**Comment by mandrenguyen** [comment]
+reconstruction
relval input failure is unfortunate, but hardly worth addressing for this one.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
