### PR TITLE
Change CandidateBoostedDoubleSecondaryVertexComputer to use GBRForest (76X)

### PR DESCRIPTION
**Pull request by lgray**
Change the TMVA evaluator in CandidateBoostedDoubleSecondaryVertexComputer to use GBRForest for internal storage rather than TMVA::Reader.

Purely technical, no changes expected/observed.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
@lgray, note that this tagger is not run in the standard reco and is expected to undergo significant changes in the coming weeks. However, since you updating the existing code, you can remove the mutex and its locking since this is now handled internally by the TMVAEvaluator.

**Comment by lgray** [comment]
@ferencek OK, thanks. Wasn't sure what I should do since it's not const threadsafe (and didn't feel like walking through the code). I'll update later.

**Comment by lgray** [comment]
@ferencek FYI here is where I found this particular instance of using TMVA::Reader. If it is changing in the future that's fine, so long as it doesn't come back!

 https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_7_6_X_2015-09-22-1500-orig.251721.DoubleEG.10evts.MEM_LIVE/565

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cvuosalo @slava77 This one shaves 3 MB off allocated memory, may see small changes in RSS but nothing earth shattering.

**Comment by ferencek** [comment]
@lgray, when updated, the plan is to use GBRForest. However, this will require a transient instance of `TMVA::Reader` to be created but that should not be a problem. Later we can also think about putting required payloads in the GT but that usually has a longer turnaround time.

**Comment by slava77** [comment]
@ferencek 
Will you be able to "rebase" the upcoming developments on top of this PR?
If not and there is unwanted interference, I'm not sure this PR should go in then.
(better be the former)

**Comment by ferencek** [comment]
@slava77, developments haven't started yet so there should be no interference.

**Comment by lgray** [comment]
@ferencek Transient instances of TMVA::Reader are fine for me.

**Comment by slava77** [comment]
@lgray  @ferencek it looks like the pfBoostedDoubleSecondary* btags are not running (it may be the secondaryVertex_cff is not loaded at the right time so that the jetTools can pick it up; but maybe it's intentional)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11607	 a03847d
- changes in the code are as expected: switch to using GBRForest for MVA evaluation runtime
    - however, there is actually no runtime call in the current workflows; the CandidateBoostedDoubleSecondaryVertexComputer constructor is still called (the corresponding ESProducer is in the list)
- jenkins tests pass and comparisons with baseline show no differences (trivial: the taggers are not called)
- local test in CMSSW_7_6_0_pre6 show about 3MB decrease in allocated memory

**Comment by ferencek** [comment]
@slava77, pfBoostedDoubleSecondary* are not included the standard reco (possibly will be in some future release) so the fact they don't run is intentional.

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
Right, I ended up looking at a wrong PAT config and confused myself that
these taggers were meant to be added.

... Why load the ES producer then? Maybe some cleanup is in order on this
side (unused jettag ES).

On Oct 6, 2015 12:01 AM, "Dinko Ferencek" <notifications@github.com> wrote:
>
> @slava77, pfBoostedDoubleSecondary* are not included the standard reco
(possibly will be in some future release) so the fact they don't run is
intentional.

**Pull request merged**
