### PR TITLE
Add esConsumes to RecoMuon/MuonIsolation

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Added esConsumes to all classes inheriting from reco::isodeposit::IsoDepositExtractor in this package

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar 
in the logs I see
> A fatal system signal has occurred: external termination request

did somebody kill this manually?

**Comment by smuzaffar** [comment]
@slava77 , I do not see any thing killing these jobs, system logs on the VM ( where the job ran) also look good. I can restart the input relval test to see how it behaves

**Comment by slava77** [comment]
> @slava77 , I do not see any thing killing these jobs, system logs on the VM ( where the job ran) also look good. I can restart the input relval test to see how it behaves

Thanks for restarting.
That's perhaps better than rerunning everything.

**Comment by Dr15Jones** [comment]
@smuzaffar about a half dozen of my PR tests run last night failed for the exact same reasons.

**Comment by smuzaffar** [comment]
@Dr15Jones , last night many relvals test jobs took over 3 hours ( https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/buildTimeTrend ) which is not normal. Normally these jobs take 60-80 mins, may be there was issue with EOS or network.

**Comment by smuzaffar** [comment]
@Dr15Jones , tests for this PR is again hanging . The jobs were timeout after 900s. You can do the following to reproduce it
```
mkdir test
cd test/
cd /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/34591/17121/CMSSW_12_0_X_2021-07-22-1700
cmsenv
cd -
LOCALRT=`pwd`
runTheMatrix.py -j 16 -i all --maxSteps=2 -l 11601.0 --ibeos
```

**Comment by Dr15Jones** [comment]
@smuzaffar I've run the test as you suggested at FNAL and it passes just fine. It does take about 15 minutes to get to the first event. I attribute that to having to read the files trans-atlantically via Russia
```
Data is served from jinr-t1.ru instead of original site US-Regional-FNAL
```

**Comment by Dr15Jones** [comment]
@makortel 
So I was wrong about where the time goes. I copied the file locally and it was still taking 20+ minutes to get to the first event. I found that it is spending all of its time looking for circular dependencies between modules! It eventually decides there aren't any.

**Comment by Dr15Jones** [comment]
So what I do not understand is this code change did NOT change any dependencies between modules as the check only looks at ED module dependencies, never ES modules.

**Comment by Dr15Jones** [comment]
@smuzaffar it looks like a problem with CMSSW_12_0_X_2021-07-22-1700. If I look at the log for wf 11601.0 for step2 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-22-1700/pyRelValMatrixLogs/run/11601.0_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log#/

I see it takes 19 minutes to get to the first event:
```
22-Jul-2021 20:54:39 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_11_3_0_pre4/RelValSingleElectronPt10/GEN-SIM/113X_mcRun3_2021_realistic_v7-v1/00000/68daad43-7280-46b8-a189-2d507531e87c.root
[2021-07-22 21:14:38.530999 +0200][Error  ][PostMaster        ] [eoscms.cern.ch:1094 #0] Forcing error on disconnect: [ERROR] Operation interrupted.
%MSG-e TkDetLayers:  TSGFromL2Muon:hltL3TrajSeedOIHit@streamBeginRun  22-Jul-2021 21:23:38 CEST Run: 1 Stream: 2
```

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34591	bae3113 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
