### PR TITLE
Add L1 Stage2 Digis to Cosmics AOD event content

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

As discussed in PPDC meeting we want to have L1 objects in Cosmics AOD event content. This PR adds required L1 stage2 digis to cosmics AOD event content.

This will make L1 displaced muon performance studies much easier to perform with cosmics data. 

#### PR validation:

Validated by running reconstruction on cosmics RAW data from 2022 using:

`cmsDriver.py reco -s RAW2DIGI,RECO --data --scenario cosmics --eventcontent AOD --filein /store/data/Run2022G/Cosmics/RAW/v1/000/362/363/00000/887de473-401c-4b6d-a9bb-66a32e35f446.root --fileout testAOD.root --conditions 124X_dataRun3_Prompt_v4 -n 1000 --era=Run3`

I verified that the required digis now exist in the event content after the changes

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be backported to 130X.

### CODE REVIEW

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
@aloeliger I imagine it is not an issue for Cosmic datasets, but still could you please report here the expected event size increase for AOD when adding the whole L1T content, at least for documentation purposes?

**Comment by aloeliger** [comment]
@perrotta It's not a great check, but a quick production would estimate about a 12% difference in the size:

```
-rw-r--r--. 1 eyigitba zh 22931955 Mar 24 13:50 cosmicAOD_wL1Obj.root
-rw-r--r--. 1 eyigitba zh 20475549 Mar 24 13:57 cosmicAOD_woL1Obj.root
```

I'll try and investigate a bit myself after the trigger readiness review monday/tuesday.

**Comment by aloeliger** [comment]
@perrotta I had a bit of spare time and was reminded of this request. I reran Efe's command with ~10,000 events each. I did some testing with `edmEventSize`, and wrote a quick script to look for only those branches added by the L1 information:

In general, this adds 75 L1 branches to AOD with the following size per event
| Uncompressed Size (bytes/Event) | Compressed Size (bytes/event) |
| --- | --- |
| 38001.53 | 2271.73 |

So, L1 information costs about 38 Kb per event uncompressed, about 2.2 Kb compressed.

If you would like (for some reason) I can give you a list of individual branches added and their sizes, but these are the top 5 branches by uncompressed event size:

| Branch | Uncompressed Size (bytes/Event) | Compressed Size (bytes/event) |
| --- | --- | --- |
| GlobalAlgBlkBXVector_gtStage2Digis__RECO | 7959.23 | 70.7549 |
| l1tEtSumBXVector_caloStage2Digis_EtSum_RECO | 5566.97 | 166.073 |
| l1tEtSumBXVector_gtStage2Digis_EtSum_RECO | 5566.84 | 165.861 |
| l1tCaloTowerBXVector_caloStage2Digis_CaloTower_RECO | 4838.77 | 23.1378 |
| l1tEtSumBXVector_caloStage2Digis_MP_RECO | 2091.19 | 83.3791 |

**Comment by perrotta** [comment]
Thank you @aloeliger 
Since this is for cosmics datasets, I imagine that we can afford that 2.2 kB increase per event.
However. just to have everybody involved, could please PPD confirm that such an increase is ok? (tagged directly because I can't find the nicks of Jordan and Kaori)

**Pull request merged**
