### PR TITLE
bsunanda:Run2-hcx50 Correct hardcoded calibration for HcalTriggerTower

### PR DESCRIPTION
**Pull request by bsunanda**
Applicable for PhaseI and PhaseII scenario

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
I enjoy changing one set of hardcoded numbers to another as much as anyone.. but maybe we can at least start to define 41, 72, 1 and 3 in some central place to make this code more understandable?

**Comment by bsunanda** [comment]
The maximum values can best be defined in the DetId class where we reserve a certain # of bits to define ieta, iphi, ... But I am waiting PR for HcalDetId changes to be accepted first before doing this.
________________________________

**Comment by bsunanda** [comment]
@diguida @mmusich Could you please take a look and approve. This restores the breaking of a few unit tests

**Comment by diguida** [comment]
+1
We second @davidlange6 proposal to avoid magic numbers and put them in a centralised place (`HcalDetId` or HCAL topology definition look suitable candidates).

**Comment by davidlange6** [comment]
@bsunanda - which pr is needed?

**Comment by bsunanda** [comment]
@davidlange6 I need #12406 which is now stuck because of issues in some heavy ion and validation stuff. I shall investigate the issue and may update the changes later. But this PR is curing some unit test  and my next HGCAL PR 12572 is stuck because of that unit test failure
________________________________

**Comment by lgray** [comment]
@bsunanda How is this PR causally linked to #12406? They seem to address different issues. I think you could proceed by merging this PR and rebasing the other ontop.

**Comment by bsunanda** [comment]
@lgray 12406 resolves the unit test failure. This PR has nothing to do with that. They are for different packages altogether and there is no need of rebasing
________________________________

**Comment by abdoulline** [comment]
@davidlange6

Dear colleagues, may we have this PR merged asap?
We have other developments in the queue depending on it...

**Comment by davidlange6** [comment]
I was expecting @bsunanda to resolve #12406 which would then let him address my comments on this PR.. (not that I really understand the coupling...)

**Comment by bsunanda** [comment]
@davidlange6 Could you approve this PR. I shall address your comments in the future. But this is holding up all work related to HGCal. This is because for PhaseII operation the HCAL trigger configuration will change and there is some limitation in the definition of trigger coefficients.  I cannot change the hardcoded # now because they are ideally defined in some other classes which is in a different PR.
________________________________

**Comment by davidlange6** [comment]
@bsunanda - then maybe a good intermediate solution is just to put these hardwired numbers into meanfull variables within these files and then you can more easily move them into a more centralized place as you start to duplicate the code.

**Comment by bsunanda** [comment]
@davidlange66 ok I shall  do it tomorrow I am traveling today


Sent from Samsung Mobile

David Lange <notifications@github.com> wrote:

@bsunanda<https://github.com/bsunanda> - then maybe a good intermediate solution is just to put these hardwired numbers into meanfull variables within these files and then you can more easily move them into a more centralized place as you start to duplicate the code.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
