### PR TITLE
Update Pixel GPU DQM online client

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR performs few simple updates of the pixel GPU DQM online client:
  * fix the pixel digi error collection names for the HIon menu ([CMSHLT-3284](https://its.cern.ch/jira/browse/CMSHLT-3284))
  * add pixel heterogeneous harvesting sequence for alpaka
  * update `pixelgpu_dqm_sourceclient-live` to add raw data input monitoring and track harvesting
  * add 2D scatter plot for track curvature and change matching deltaR from 0.2 to 0.02
  *  improvements to SoA track monitoring plugins
  *  add `alpakaValidation` modifier to .403 harvesting steps

#### PR validation:

`scram b runtests_TestDQMOnlineClient-pixelgpu_dqm_sourceclient` runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, to be backported to CMSSW_14_0_X for 2024 data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu= 12434.403, 12434.503, 12634.403

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
type tracking

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
+1

- several spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mmusich** [comment]
@cms-sw/upgrade-l2 @cms-sw/pdmv-l2 do you have any feedback?

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
