### PR TITLE
Update to evtgen 2.0

### PR DESCRIPTION
**Pull request by alberto-sanchez**
#### PR description:

Update to EvtGen 2.0.0 and cleanup of unneeded user decay models.
Tables copied from release were update, as well as fragments

it should be integrated together with cms-sw/cmsdist#6494

#### PR validation:

Py8_tt_evtgen1_cfg.py, Py8_bplus_evtgen1_cfg.py, and Py8_lambadb_evtgen1_Lb2plnuLCSR_cfg.py has sucesfully run as well as 

runTheMatrix.py -l 541.0,545.0 --command='-n 100' 

which test the BPH fragments and runTheMatrix.py -l limited -i all --ibeos

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test with  cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
a couple of libraries were missing in the toolfile of taolapp, which now are detached in the current version. This have been fixed

**Comment by alberto-sanchez** [comment]
please abort test

**Comment by alberto-sanchez** [comment]
please abort

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
please test workflow  541.0,545.0 with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
compilation errors (warnings) are not related with this PR

**Comment by alberto-sanchez** [comment]
ignore build-warnings

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
ignore build-warnings

**Comment by alberto-sanchez** [comment]
dear all, this PR has not succed. The warnings are not related to this PR, we would like to integrate it as soon as possible in order to start evaluating the new models and improvements introduced in this release.

**Comment by qliphy** [comment]
please abort

**Comment by qliphy** [comment]
please test with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
please test workflow 541.0,545.0 with cms-sw/cmsdist#6494

**Comment by alberto-sanchez** [comment]
+1

Dear @qliphy, can we proceed  with this PR?

**Comment by qliphy** [comment]
Thanks @alberto-sanchez 
Let's wait for cms-sw/cmsdist#6494 to be merged first.

**Comment by qliphy** [comment]
+1

**Pull request merged**
