### PR TITLE
Minor cleanups to avoid clang warnings

### PR DESCRIPTION
**Pull request by Dr15Jones**
-Removed an unused parameter in a lambda
-Switched a struct to be a class to be consistent with other headers
-Delcared noexcept(false) to be consistent between header and source file

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@gartung FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
