### PR TITLE
Remove duplicate header includes and redundant class definitions in CSCRawToDigi

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Title says all

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
@ptcox FYI

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Trivial: it just removes some redundancy
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
