### PR TITLE
SimDataFormats/CaloHit: fix clang warning hides overloaded virtual

### PR DESCRIPTION
**Pull request by gartung**
by adding using baseclass::function; statement

### CODE REVIEW

**Comment by civanch** [comment]
@gartung , you add one semicolon, is it OK?

**Comment by gartung** [comment]
@civanch I thought I had tested that but running the compilation revealed the typo.

**Comment by civanch** [comment]
please test

**Comment by gartung** [comment]
Because the parameter in TObject::Clear has a default value, clang warns that ::Clear() shadows it
    virtual void        Clear(Option_t * /*option*/ ="") { }

I don't know know of a correct way to tell the compiler the no parameter signature of Clear is being called. There are several other instances of this in the clang warnings.

**Comment by civanch** [comment]
@gartung , may be a staightforward method is simply to rename Clear() method of the class and propagate the change in consumer classes. Another possibility (which may not be applicable here - move inline to source).

**Comment by gartung** [comment]
Changed Clear to ClearB so that it does not shadow TObject::Clear.

**Comment by civanch** [comment]
please test

**Comment by gartung** [comment]
Something is still not correct since the compilation works whether the function called in Clear or ClearB.

**Pull request closed without merging**
