### PR TITLE
fix of Hit TkMap filling

### PR DESCRIPTION
**Pull request by fioriNTU**
Valid, Invalid and Inactive hits were normalized to the number of Tracks, while we want the integrated number on the Map

### CODE REVIEW

**Comment by fioriNTU** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by fwyzard** [comment]
please rebase on top of the latest CMSSW_8_0_X

**Comment by fioriNTU** [comment]
@fwyzard sorry, made a mistake, I will close this and open a new one

**Pull request closed without merging**
