### PR TITLE
CTPPS: update of DQM for TOTEM RP

### PR DESCRIPTION
**Pull request by jan-kaspar**
- removed plots (unused) depending on `CorrelationPlotsSelector` which consequently removes dependence on Qt, use of exit and printf.
- added `TotemRPDQMHarvester` module for calculating various histogram ratios
- `TotemRPDQMSource`
  - added few more plots
  - uses `getNumberOfClusters` from VFAT chips (following #14615)
- added config for online DQM: `DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py`
- included Totem DQM modules to the offline DQM sequence: `DQMOffline/Configuration/python/DQMOffline_cff.py`

This PR functionally depends on #14605.

### CODE REVIEW

**Comment by jan-kaspar** [comment]
@dmitrijus Is the config for online DQM OK?
  https://github.com/CTPPS/cmssw/blob/a6df7b37ae4353a21d5410924c01214a1762451b/DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py

**Comment by jan-kaspar** [comment]
@dmitrijus Is the inclusion of Totem DQM modules to the offline DQM sequence OK?
https://github.com/cms-sw/cmssw/pull/14836/commits/07555287a2e4c42bc59e05787151919f05ae28d7

**Comment by davidlange6** [comment]
please test

**Comment by jan-kaspar** [comment]
I've checked (some of) the RelVal issues and each time the problem is missing `VeryForwardRealGeometryRecord`. The corresponding ES producer is included in configs for RP reconstruction in #14605. Thus the problems should go away once #14605 is merged.

**Comment by dmitrijus** [comment]
@jan-kaspar the online config looks fine to me!

**Comment by dmitrijus** [comment]
+1

**Comment by jan-kaspar** [comment]
For the failing tests: #14605 needs to be merged first.

**Comment by jan-kaspar** [comment]
With #14605 and #14828 merged, it makes sense to restart the tests.

**Comment by davidlange6** [comment]
we need to get an IB built first… will be ready tomorrow..

**Comment by jan-kaspar** [comment]
I've run `runTheMatrix -l limited` in `CMSSW_8_1_X_2016-06-14-2300/src` and got
```
10 10 9 7 5 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed
```
Thus I'd like to ask to run the tests here.

**Comment by jan-kaspar** [comment]
@dmitrijus or anyone: There is still one question unanswered. Is the inclusion of Totem DQM modules to the offline DQM sequence (0755528) OK?

**Comment by davidlange6** [comment]
please test

**Comment by jan-kaspar** [comment]
Is there something else I can do for this PR?

**Comment by dmitrijus** [comment]
@jan-kaspar I want to discuss it with @deguio, I will let you know asap.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
