### PR TITLE
Phase2-hgx168 Introduce common behavior between HGCSiliconDetId and HFNoseDetId

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
hold
still being discussed in #25062 whether this change is desirable or not (I lean toward not)

**Comment by VinInn** [comment]
-inf

**Comment by davidlange6** [comment]
i agree with @VinInn

**Comment by bsunanda** [comment]
I really like Vincenzo's cooment. I am closing this PR
________________________________

**Comment by cvuosalo** [comment]
This code looks very nice, but this area of the code may be exercised very heavily so any loss in performance due to the use of virtual functions is not acceptable. This PR demonstrates a clearer object-oriented design, but how could it be implemented without incurring a significant performance cost?

**Comment by cvuosalo** [comment]
For reference, this PR was an attempt to implement the suggestions in issue #25062.

**Pull request closed without merging**
