### PR TITLE
TrackHistory updates

### PR DESCRIPTION
**Pull request by ferencek**
This PR includes Dominik Nowatschin's improvements to the TrackHistory package.

@imarches @dnowatsc

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@ferencek , when you introduce a new Util class what is the reason not to use existing SimG4Core/Physics/interface/G4ProcessTypeEnumerator.h ?

**Comment by ferencek** [comment]
@civanch, @dnowatsc can comment more on this point but my understanding is that this process type translation was needed to keep things backward compatible with the existing TrackHistory code.

**Comment by dnowatsc** [comment]
The reason is that the BTagAnalyzer that relies on the TrackHistory package uses the old G4 process type numbering scheme as defined here: http://cmslxr.fnal.gov/lxr/source/SimG4Core/Physics/src/ProcessTypeEnumerator.cc?v=CMSSW_5_3_20
Since ProcessTypeEnumerator does not exist anymore and I assumed the old numbering scheme is no longer used outside the TrackHistory package I put a function mapping new to old numbering scheme directly into the TrackHistory package.

**Comment by civanch** [comment]
@dnowatsc , the reason to take out of the old code was do not make any computations in run time for each hit but use static process code coming directly from G4. Ideally, it is also possible to have static translation from G4 process type to the type used in TrackingHistory. Is there a possibility to use G4 code for tracking particles but in the case of run-1 MC convert old codes into G4, which may be done via static array? 

Another moment: in your util class integer numbers are different from 5_3_X, see, for example, table from twiki:  https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMCTruth , for example, primary particle was 100 and not 2.

Final question: which processes codes are really used in TrackingHistory and which are foreseen? I would guess the most part simply are not relevant.

**Comment by dnowatsc** [comment]
1. In theory it would be possible to re-design the TrackHistory code to use the G4 scheme but that would require to re-write large parts of the TrackHistory code and I'm not sure if this is really worth the effort. As far as I know the TrackHistory code is now mainly used in the b-tagging POG so I would suggest if they are not satisfied by the performance of the code one can think about implementing your suggestions.

2. The numbering scheme actually used in the TrackHistory code is not the one from https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMCTruth but instead the one from the link in my previous message. There, e.g., "Primary" is mapped to a value of 2.

3. I can only speak for the b-tagging side which, I guess, are the main users of the TrackHistory code. There, mainly processes are of interest that can frequently cause tracks with a large impact parameter or create secondary vertices, so primarily decays (201-231 in the G4 numbering scheme) , hadronic processes (111-151), but also others.

**Comment by ferencek** [comment]
@civanch, the TrackHistory code is used for studies of some of the b-tagging systematic uncertainties and when originally written, it was built around the old CMS process type enumeration. Changing the code to the new process type enumeration would in principle make sense and might even be preferred long term but right now it would complicate direct comparison with Run 1 studies and results. So at the moment a preferred solution is to stay with the old TrackHistory code which requires a process type code translation that Dominik implemented. As far as we are aware, the TrackHistory is not used in any official workflow so in terms of the performance, only privately run jobs running the BTagAnalyzer (which resides outside the CMSSW code tree in https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements) would suffer. Nevertheless, I can try to implement a static code mapping so just give me a day or two to make this change.

**Comment by civanch** [comment]
@ferencek , it turned out that in 5_3_X we had 3 sets of enumeration: native G4, G4ProcessTypeEnumerator and ProcessTypeEnumerator. This makes confusions.

In reality, only sub-fraction of G4 processes are used in CMS and may be useful for b-tagging: primary (0) , Coulomb scattering (1), ionisation (2), bremsstrahlung(3), e+e- pair production (4), annihilation(5), hadron elastic(111), hadron inelastic(121), decay(201), external decay(206). Other G4 processes are not used in CMS at all or not related to b-tagging (photoeffect 12, Compton(13), conversion (14), neutron capture(131), stopping hadron (151)). I do not see any advantage to have several similar numbers for the same thing. Moreover, likely smaller sub-set than I have mentioned is used (one can suspect that decay is the main process of interest). What I do not understand why all hadronic processes are merged - hadron elastic and inelastic affect vertices in a different way.

**Comment by ferencek** [comment]
Hi, Vladimir,

On 03/17/2015 09:48 AM, Vladimir Ivantchenko wrote:
> @ferencek <https://github.com/ferencek> , it turned out that in 5_3_X we
> had 3 sets of enumeration: native G4, G4ProcessTypeEnumerator and
> ProcessTypeEnumerator. This makes confusions.

We agree. But as said earlier, for backward compatibility reasons, at 
the moment we prefer to stick with the old process enumeration as it was 
defined in ProcessTypeEnumerator. All we need is mapping from the native 
G4 codes to the old ones (as much as it is possible).

> In reality, only sub-fraction of G4 processes are used in CMS and may be
> useful for b-tagging: primary (0) , Coulomb scattering (1), ionisation
> (2), bremsstrahlung(3), e+e- pair production (4), annihilation(5),
> hadron elastic(111), hadron inelastic(121), decay(201), external
> decay(206). Other G4 processes are not used in CMS at all or not related
> to b-tagging (photoeffect 12, Compton(13), conversion (14), neutron
> capture(131), stopping hadron (151)). I do not see any advantage to have
> several similar numbers for the same thing. Moreover, likely smaller
> sub-set than I have mentioned is used (one can suspect that decay is the
> main process of interest). What I do not understand why all hadronic
> processes are merged - hadron elastic and inelastic affect vertices in a
> different way.

The native G4 codes have a finer granularity than the old codes used in 
the TrackHistory so collapsing more than one G4 category into just one 
category is, I'm afraid, unavoidable in some cases. Note that Dominik 
marked with 'DOUBLE-CHECK THIS' some of the mappings and this is 
something where your input would be greatly appreciated to confirm that 
these mapping are OK.

Thanks,
Dinko

**Comment by civanch** [comment]
@ferencek , the processes marked "double check" are not used, so whatever id is correct.

**Comment by civanch** [comment]
+1

**Comment by ferencek** [comment]
Please hold off with merging this until we provide a static process code mapping.

**Comment by ferencek** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by ferencek** [comment]
@davidlange6, can you please merge this PR

**Comment by ferencek** [comment]
What's the hold up here?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
