### PR TITLE
update "chrono" tests

### PR DESCRIPTION
**Pull request by fwyzard**
- print boost and tbb versions
  - add suport for boost::chrono clocks
  - add support for clock_gettime(CLOCK_BOOTTIME, ...) (Linux >= 2.6.39)
  - add support for syscall interface for clock_gettime
  - add results from Ubuntu Linux 16.04.02

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
Caused some compilation errors on AArch64: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_9_1_X_2017-04-20-1100/HLTrigger/Timer
Have not investigated further, thus don't have more details right now.

**Comment by fwyzard** [comment]
Probably due to `-std=c++1z`

**Comment by davidlt** [comment]
Both GCC 6 and GCC 7 IBs are compiled with C++17, but only GCC 7 actually implements full language support and majority of standard library.

**Comment by davidlt** [comment]
You can wait until `slc6_amd64_gcc700` IB shows up. Maybe it will have the same issue.

**Comment by davidlt** [comment]
Seems to happen only on aarch64 and ppc64le. The x86_64 + GCC 7.0.1 is fine.

**Comment by davidlt** [comment]
ping^1

**Comment by fwyzard** [comment]
I am not going to fix a presumed problem with a pre-production compiler on
an architecture I have no access to.

Feel free to make a PR, though.

Ciao,
.Andrea

**Comment by davidlt** [comment]
https://github.com/cms-sw/cmssw/pull/18458

Looks like the issue was a simple one, just one missing `#if`.

Sorry, we still don't have fully publicly open machines (e.g. similar to lxplus.cern.ch).

**Pull request merged**
