### PR TITLE
Fix PFTrackAlgoTools memory corruption [81X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #16797

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@kpedro88: Are you going to update this PR, or should it be closed?

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16798 4d6221758b616b40cc03c6a8a0934ea30c7886a6

Fixing out-of-bounds array access in PFTrackAlgoTools. This fix takes care of the original bugs but will require future tuning of the muon cut.

#16797 is the 90X version of this PR, and it has already been approved.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-12-08-1100 show no significant differences, as might be expected. An additional test described for #16797 shows no problems.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
