### PR TITLE
Phase2-hgx341A One step to resolve cassette shift issue for V18 where the shift will move the passive elements as well

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

One step to resolve the cassette shift issue for V18 where the shift will move the passive elements as well

#### PR validation:

Test using the dump tool for checking with fireworks

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , this question not to this PR but in general: I would not use #ifdef EDM_ML_DEBUG in any class constructor. At initialisation it depends how big is this the printout, in many cases LogVerbatim is enough, may be with exception of geometry algorithms. Definitely #ifdef EDM_ML_DEBUG is needed in run time method.

**Comment by civanch** [comment]
@bsunanda , please link the issue #41927  in the description.

**Comment by bsunanda** [comment]
It is not connected to that issue - it is related to movement of a part of the cassette and this will be effective in V18 only

**Comment by srimanob** [comment]
+Upgrade

DQM comparison failure comes from mkfit workflow which does not relate to this PR.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
