### PR TITLE
force the online applications to run single thread

### PR DESCRIPTION
**Pull request by deguio**
affecting the processes on the DQM cluster only.
there are use cases requiring this: the beam spot fit for example cannot be computed in parallel. the monitor element streaming to the online GUI for live mode also doesn't make much sense in parallel.

### CODE REVIEW

**Comment by deguio** [comment]
+1
affects the online only. no sequences touched.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
