### PR TITLE
L1T muon DQM upgrades part2 - 101x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #23440 

Upgrades for the L1T muon DQM

- Reduce number of bins for uGMT histograms.
- Retune quality tests.
- Move some uGMT quality tests to separate muon quality test configurations for all runs and additional tests fro collisions runs.
- Add OMTF quality tests.
- uGT data vs. emulator quality tests.
- update of L1T client.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
supersedes PR #23374

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
+1

validated in CMSSW_10_2_0_pre5

**Pull request merged**
