### PR TITLE
Fix issues in GEM packages reported by static analyzer

### PR DESCRIPTION
**Pull request by dildick**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8839	f6be10e
- changes in code  should not  change the behavior
- static analyzer report is clean
- no diffs in jenkins tests because relevant parts (GEM) are not active in tested workflows

**Comment by dildick** [comment]
@slava77 

The static analyzer also showed issues here
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc#L181-L183
and here
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc#L204-L206

Basically I can't use const_cast. Would you happen to know how to fix it?

**Comment by slava77** [comment]
I can suggest to check with other geometries.
The need for a cast here is to match the GeomDet constructor interface.


On 4/24/15 10:59 AM, Sven Dildick wrote:
> @slava77 <https://github.com/slava77>
> 
> The static analyzer also showed issues here
> https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc#L181-L183
> and here
> https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Geometry/GEMGeometryBuilder/src/GEMGeometryBuilderFromDDD.cc#L204-L206
> 
> Basically I can't use const_cast. Would you happen to know how to fix it?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8839#issuecomment-95977509>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
The fix for the ```const_cast``` would be to switch to a ```ConstReferenceCountingPointer``` and change the constructor for ```GEMEtaPartition``` to take a ```BoundPlane::ConstBoundPlanePointer```.

**Pull request merged**
