### PR TITLE
quark and gluons Py8EGun

### PR DESCRIPTION
**Pull request by vberta**
#### PR description:

Added a feature to the Py8EGun: now the gun can use also quark or gluons. This feature was already present in the Py8PtGun, but not in the EGun. 
This feature is required for the MC production for the training of DeeoCore Algorithm in forward region. see this jira ticked for details: [(https://its.cern.ch/jira/browse/PDMVRELVALS-65#add-comment)]. After the merge **this feature must be backported to CMSSW_10_2_5** for the production of the MC. 

#### PR validation:

Tested using a standard path which use the Py8Gun, properly modified to produce gluons and quarks.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by silviodonato** [comment]
@alberto-sanchez  @SiewYan  @qliphy  @efeyazgan  @mkirsano  @agrohsje please review/sign

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
