### PR TITLE
remove Trajectory in Event for GSF

### PR DESCRIPTION
**Pull request by VinInn**
reduces memory by ~1GB at PU200 with 4 threads

tested with
```
[1]    Done                          runTheMatrix.py --useInput=all --list=limited >& lim.log
[innocent@cmsco01 matrix]$ 
[innocent@cmsco01 matrix]$ cat runall-report-step123-.log 
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:15:58 2016-date Wed Dec  7 11:12:04 2016; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Dec  7 11:15:36 2016-date Wed Dec  7 11:12:05 2016; exit: 0 0
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:17:22 2016-date Wed Dec  7 11:12:08 2016; exit: 0 0 0 0 0
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:23:35 2016-date Wed Dec  7 11:12:13 2016; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Dec  7 11:26:15 2016-date Wed Dec  7 11:15:44 2016; exit: 0 0 0
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  7 11:38:08 2016-date Wed Dec  7 11:15:59 2016; exit: 0 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Dec  7 11:24:51 2016-date Wed Dec  7 11:17:25 2016; exit: 0 0 0
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  7 11:31:12 2016-date Wed Dec  7 11:23:40 2016; exit: 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:33:03 2016-date Wed Dec  7 11:24:54 2016; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED Step7-PASSED  - time date Wed Dec  7 11:33:23 2016-date Wed Dec  7 11:26:17 2016; exit: 0 0 0 0 0 0 0 0
10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:41:11 2016-date Wed Dec  7 11:31:21 2016; exit: 0 0 0 0 0
10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Dec  7 11:44:21 2016-date Wed Dec  7 11:33:03 2016; exit: 0 0 0 0 0
20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D1_GenSimHLBeamSpotFull14+DigiFull_2023D1+RecoFullGlobal_2023D1+HARVESTFullGlobal_2023D1 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  7 11:45:10 2016-date Wed Dec  7 11:33:24 2016; exit: 0 0 0 0
21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFull_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  7 12:19:32 2016-date Wed Dec  7 11:38:08 2016; exit: 0 0 0 0
23234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D5_GenSimHLBeamSpotFull14+DigiFull_2023D5+RecoFullGlobal_2023D5+HARVESTFullGlobal_2023D5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  7 12:22:39 2016-date Wed Dec  7 11:41:13 2016; exit: 0 0 0 0
15 15 14 12 7 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed
```

### CODE REVIEW

**Comment by VinInn** [comment]
@ebrondol @makortel @kpedro88 FYI

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
conversion was just silently failing I suppose as a ref to the trajectory is used here
http://cmslxr.fnal.gov/dxr/CMSSW_8_0_5/source/RecoEgamma/EgammaPhotonProducers/src/ConversionProducer.cc#493

**Comment by VinInn** [comment]
Next year I will try to add to TrackExtra some info out of Trajectory (the hits are already there)
to satisfy the needs of the Trajectory clients.
My goal is to remove Trajectory from the event for good...
For the time being we will have to survive with all this additional memory overhead (no, the current version of the product-deleter cannot delete just the trajectory, only all products of a producer)

wil lclose this PR once the comparision is ready

**Comment by VinInn** [comment]
In case you wonder the only real client in CMSSW of the GB in question is this line of code
http://cmslxr.fnal.gov/dxr/CMSSW_8_0_5/source/RecoEgamma/EgammaTools/src/ConversionTools.cc#43

**Comment by VinInn** [comment]
oh well, NO REGRESSION  (in JRValidation)!!!!
@slava77 ???
How do you want to proceed?
wait some  analysis to complain?

**Comment by slava77** [comment]
On 12/7/16 6:31 AM, Vincenzo Innocente wrote:
> oh well, NO REGRESSION (in JRValidation)!!!!
> @slava77 <https://github.com/slava77> ???
> How do you want to proceed?
> wait some analysis to complain?


There are regressions in non-phase2 workflows

e.g. 136.731

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-12-07-0000+16895/17405/validateJR/all_OldVSNew_RunSinglePh2016Bwf136p731/

these are quite a bit suspicious though, considering it's B-tags which
should give identical results on AOD.
IMO, until this interference is understood, your switch better be made
only for phase-2.

Lindsey may be able to comment on the current state of conversions.

**Comment by VinInn** [comment]
Most probably it is creeping in through some MVA variable that are not (yet) monitored by JRValidation.

In my opinion this PR is unsafe, still it shows some limitation of current (early?-)validation.

**Comment by kpedro88** [comment]
hold

**Comment by VinInn** [comment]
will come back with no more clients for Trajectory in the event...

**Pull request closed without merging**
