### PR TITLE
Remove ROSDebugUtility from DQM/DTMonitorModule.

### PR DESCRIPTION
**Pull request by dmitrijus**
ROSDebugUtility was only used to trigger thread-unsafe statics
warnings and to waste cpu time.

Also removed a few static variables from DTDataIntegrityTask,
as they too didn't make any sense.

(Fixes static warnings from #7510)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The pull requests comment made me laugh :). Thanks for the fix.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
