### PR TITLE
My

### PR DESCRIPTION
**Pull request by doanhien**
backport for 7_5_X

### CODE REVIEW

**Comment by slava77** [comment]
@doanhien please provide more detail and update the subject.
"My" looks like a somewhat random test PR.

@lgray please clarify/confirm this

**Comment by lgray** [comment]
@doanhien Please give a sensible name to this PR and resubmit. Thanks!

**Comment by lgray** [comment]
@doanhien It may also help to give a more descriptive branch name.

**Comment by slava77** [comment]
Since this PR was submitted to a correct branch (75X) and had only issues with appropriate documentation, I suggest this PR is updated as discussed in 
https://github.com/cms-sw/cmssw/pull/10349#issuecomment-125173721
- change the subject to something more descriptive
- update the PR description as was one in #10349 https://github.com/cms-sw/cmssw/pull/10349#issue-97074787

**Comment by slava77** [comment]
-1
superseded by #10405

**Pull request closed without merging**
