### PR TITLE
Modernize `CalibMuon/CSCCalibration`

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Moving modules to `one`, migrating away from es get() functions, changing to default destructor

#### PR validation:

Code compiles, runtests pass

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * technical 
 * SA warning not connected to this PR
 * test pass
 * recommendation to the test owners to exercise these test codes in unit tests

**Comment by qliphy** [comment]
+1

**Comment by Dr15Jones** [comment]
@tvami Thanks!

**Pull request merged**
