### PR TITLE
[12_3_X] Add AlCaNano and inherit AlCaPhiSymEcal_Nano from there

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/37854

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/37854

### CODE REVIEW

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
type ecal

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
@cms-sw/orp-l2 there is continuously no point in testing this, so feel free to merge this at any point. It would be actually good to have it in `12_3_4`

**Comment by perrotta** [comment]
+1
- Verbatim backport of #37854
- Not used in the usually tested workflows
- Succesfull private tests were reported in https://github.com/cms-sw/cmssw/pull/37854#issuecomment-1120263490

**Pull request merged**
