### PR TITLE
[94X] OnlineDQM : Move uGMT output to uGT input comparison histogram to the uGT directory

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/21367

This backport is done on top of https://github.com/cms-sw/cmssw/pull/21338

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @stahlleiton 
The DQM has moved to 10_0_X. This PR can be closed.

**Pull request closed without merging**
