### PR TITLE
Phase2-hgx348C Update HGCSiliconDetId in view of adding a fourth type of wafer: high density but thicker

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update HGCSiliconDetId in view of adding a fourth type of wafer: high-density but thicker. This is going to affect the future description of modules where some of the current partial wafer type will be dropped and a new wafer type will be introduced. The changes made here should not affect any existing workflows.

#### PR validation:

Tested with the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for

To be backported to 13_3_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by bsunanda** [comment]
Backported to 13_3_X using #43207

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda 
Could you please give more clear description if this PR will effect which workflow? I don't see the failure in PR test, so I assume it will not effect existing workflow, but later. Thanks.

**Comment by bsunanda** [comment]
The changes made here is more for future and not for the present workflows.

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
