### PR TITLE
Phase2-hgx360 Try to introduce the right longitudinal structure to the V10 version of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to introduce the right longitudinal structure to the V10 version of HGCal geometry

#### PR validation:

Dump the geometry to be visualized by firework 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
