### PR TITLE
Fix deadlock in XrdRequestManager

### PR DESCRIPTION
**Pull request by Dr15Jones**
If the XrdCl::File is deleted while the OpenHandler is holding its
lock it can lead to a three way deadlock with locks in xrootd.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@bbockelm Here's the stop gap measure

**Comment by bbockelm** [comment]
This is a good start; I figured out how to eliminate the need to acquire OpenHandler::m_mutex from the call to OpenHandler::open() while there's a possibility that OpenHandler::HandleResponseWithHosts is being called.  I'd still like to apply that patch as OpenHandler::HandleResponseWithHosts calls other functions which invoke the Xrootd client (and may trigger this bug in other ways).

I'll send a PR in a second to get things going, and try to make it not conflict with this one.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
