### PR TITLE
Fix PackedCandidateTrackValidator for different minima of positive and negative values of logintpack

### PR DESCRIPTION
**Pull request by makortel**
This PR is a followup to #12581 and especially to @cvuosalo's comment (https://github.com/cms-sw/cmssw/pull/12581#issuecomment-161434181). After #12581 the `logintpack` has different minimum by absolute value for positive and negative numbers. Here `PackedCandidateTrackValidator` is made aware of the different minima.

Tested in 800pre4, tiny changes expected under `Tracking/PackedCandidate` in `diffCov*Status` and `diffCov*UnderOverFlowSign` histograms for elements packed with `logintpack` (in practice should be visible in 1330.0 and 25202.0 workflows).

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
Could DQM (@deguio, @vanbesien) please review and sign, and somebody launch the tests? Thanks.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
