### PR TITLE
Removed unnecessary dependency on sigc++

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The dependency on sigc++ library was not needed in these packages.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by yuanchao** [comment]
+1

**Comment by Dr15Jones** [comment]
ping @cms-sw/db-l2

**Comment by Dr15Jones** [comment]
ping @cms-sw/db-l2

**Comment by Dr15Jones** [comment]
ping @cms-sw/db-l2

**Comment by silviodonato** [comment]
merge
@ggovi  please let us know if you have any objections

**Pull request merged**
