### PR TITLE
Fixes for online beamspot, heavy-ion run in 2018 (rebase)

### PR DESCRIPTION
**Pull request by andrius-k**
This is a rebase of the original PR: #24887, back-ported here: #24888

### CODE REVIEW

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
please test

errors cannot be due to this PR, that is just for online DQM

**Comment by fabiocos** [comment]
@jfernan2 @schneiml @andrius-k sorry, is this PR (actually its backport) really needed for 10_3_1? I would naively think we can safely merge it, as these live configurations have nothing to do with the PR tests, but I do not even see a 10_3_X version of this. 

I will move forward with the build, in case this can be added later I assume (and you have the freedom to anyway include it on the short term in the online DQM distribution).

Please comment in case

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

ok, let's pick it even if the test is being repeated, the changes in this PR cannot affect it

**Pull request merged**
