### PR TITLE
Fixes for newer Eigen: Use Eigen::placeholders::all

### PR DESCRIPTION
**Pull request by smuzaffar**
Use  `Eigen::placeholders::all` instead of `Eigen::all` which has been [removed in newer Eigen](https://gitlab.com/libeigen/eigen/-/commit/5dac0b53c94a7b36b5aef609df73453c09ee66bb ). Although `Eigen::placeholders::all` was marked as deprecated for current version of Eigen but in newer version it has been un-deprecated.

This is needed for newer [Tensorflow 2.11.0](https://github.com/cms-sw/cmsdist/pull/8258) ( which requires newer Eigen)

FYI @fwyzard

### CODE REVIEW

**Comment by fwyzard** [comment]
New stuff 🤷🏻‍♂️

**Comment by smuzaffar** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by smuzaffar** [comment]
Note that this change does generate [deprecated warnings](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1e41c7/30321/deprecated-warnings.log) [a]. So I would suggestto not merge this yet. once we have TF 2.11.0 ready to go in then we can merge this too. Any objectsion, if not than I would like to put it on hold

[a]
```
HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzer.cc
src/HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzer.cc:97:114: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
src/HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzer.cc:97:114: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
src/HeterogeneousCore/AlpakaTest/plugins/TestAlpakaAnalyzer.cc:97:114: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
HeterogeneousCore/CUDATest/plugins/TestPortableAnalyzer.cc
src/HeterogeneousCore/CUDATest/plugins/TestPortableAnalyzer.cc:74:112: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
src/HeterogeneousCore/CUDATest/plugins/TestPortableAnalyzer.cc:74:112: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
src/HeterogeneousCore/CUDATest/plugins/TestPortableAnalyzer.cc:74:112: warning: 'Eigen::placeholders::all' is deprecated [-Wdeprecated-declarations]
```

**Comment by smuzaffar** [comment]
hold
(see https://github.com/cms-sw/cmssw/pull/40645#issuecomment-1419093382 )

**Comment by smuzaffar** [comment]
closing it in favor of  #41873

**Pull request closed without merging**
