### PR TITLE
HLT updates after 740pre9

### PR DESCRIPTION
**Pull request by perrotta**
This pull request collects the updates to the HLT Run2 menus integrated after CMSSW_7_4_0_pre9, and meant for the final CMSSW_7_4_0

List of changes applied with respect to the menus merged in CMSSW_7_4_0_pre9:

=== Frozen menus as the top developments of the following

=== Add paths for MC studies of the HLT objects to both 25ns and 50ns tables

=== 50ns:
/dev/CMSSW_7_4_0/50nsHLT/V29: Fix L1 seeds for RPC AlCa, as in a late request from CMSHLT-231
/dev/CMSSW_7_4_0/50nsHLT/V26: Change of isolation cone to R=0.2 for lepton+HT+[MET,b-tag] triggers, CMSHLT-311
/dev/CMSSW_7_4_0/50nsHLT/V24: Include 4 new HLT paths for the all hadronic ttH(bb) analysis, CMSHLT-309
/dev/CMSSW_7_4_0/50nsHLT/V23: Addition and modification of SUSY lepton auxiliary triggers, CMSHLT-293
/dev/CMSSW_7_4_0/50nsHLT/V22: Fix ncand multiplicity in a few single and multiple electron filters
/dev/CMSSW_7_4_0/50nsHLT/V21: Finish integrating CMSHLT-285, with renamed PFJet paths and modules
/dev/CMSSW_7_4_0/50nsHLT/V20: Change L1 seeds for EXO triggers at 50ns, CMSHLT-293
/dev/CMSSW_7_4_0/50nsHLT/V19: Rename a few L1s modules in a more conventional way
/dev/CMSSW_7_4_0/50nsHLT/V17: Migrate to CMSSW_7_4_0_pre9

=== 25ns:
/dev/CMSSW_7_4_0/HLT/V78: Fix L1 seeds for RPC AlCa, as in a late request from CMSHLT-231
/dev/CMSSW_7_4_0/HLT/V77: Change of isolation cone to R=0.2 for lepton+HT+[MET,b-tag] triggers, CMSHLT-311
/dev/CMSSW_7_4_0/HLT/V75: Include 4 new HLT paths for the all hadronic ttH(bb) analysis, CMSHLT-309
/dev/CMSSW_7_4_0/HLT/V74: Addition and modification of SUSY lepton auxiliary triggers, CMSHLT-293
/dev/CMSSW_7_4_0/HLT/V70: Fix ncand multiplicity in a few single and multiple electron filters
/dev/CMSSW_7_4_0/HLT/V69: Rename a few L1s modules in a more conventional way
/dev/CMSSW_7_4_0/HLT/V68: Migrate to CMSSW_7_4_0_pre9

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
@perrotta - please add a summary of physics changes relative to the 50 and 25 ns menus used in the pre9 relvals to the description of this PR. Thanks.

**Comment by perrotta** [comment]
@davidlange6 : list of changes applied to the 25ns and 50ns menus added to the description

**Comment by perrotta** [comment]
Added to both 25ns and 50ns tables the paths for MC studies of the HLT objects (description of this PR updated)

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
tests seem stuck?

**Comment by Martin-Grunewald** [comment]
@nclopezo
cna you please check what happened with the tests of #8525? They seem not to run?

**Comment by nclopezo** [comment]
Hi @Martin-Grunewald,
They are in the queue. Because of the github issues the IBs also had some issues, the queue is also full of IB building jobs. Later during the afternoon they should start.

**Comment by Martin-Grunewald** [comment]
Hmm, still asleep...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@cmsbot wake up

**Pull request merged**
