### PR TITLE
Python3: Changes needed to build cmssw with python3 as default

### PR DESCRIPTION
**Pull request by smuzaffar**
These changes are needed in order to build cmssw with python3 set as default python

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi could you please check the DB part? As far as I can see the main change is the need to specify the decoding of strings (@smuzaffar do you confirm ? This looks a sizeable difference compared to python2)

**Comment by smuzaffar** [comment]
@fabiocos @govvi,  yes we have some files with special characters in comments  ( e.g files like these https://github.com/cms-sw/cmssw/blob/da232d4850c59deb4e0016a4dea376a24acbbd84/CalibFormats/SiPixelObjects/src/PixelBase64.cc#L4 ) so python3 fails to read these types of files in to string. That is why we need encoding. Note that all these special characters are in comments sections so this does not change the generated source file by condformats_serialization_generate.py .

**Comment by ggovi** [comment]
@smuzaffar thanks a lot.

**Comment by ggovi** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , any objection on these changes?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
