### PR TITLE
Run3-gex61 Add the correction to HO volume names to the scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the correction to HO volume names to the scenarios

#### PR validation:

Tested for a few Phase2 scenario and also Run3 scenario reading geometry from XML

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Changes in the geometry produce comparison differences in the DD4hep workflow 11634.911 as expected. The differences are just statistical fluctuations.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
@cms-sw/upgrade-l2 do you have any comments?

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
