### PR TITLE
HBHE: arrival time [ backport 12_4 ]

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of https://github.com/cms-sw/cmssw/pull/39227

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent
As discussed at Joint ops anything intended for the resumption of collision data should be marked as urgent.

**Comment by mandrenguyen** [comment]
Hi @rovere We are waiting for MET experts to confirm that they're ok with changes that modify the beam halo filters before approving.

**Comment by rovere** [comment]
Dear all, LHC is going very well and the plan is to have stable beams as early as next week.
We need to finalize the release for the coming data-taking by today.
Do you think you'll receive feedback from MET experts in time?
The original PR against `master` was opened 18 days ago.

**Comment by mandrenguyen** [comment]
Dear @rovere We have a presentation on this matter scheduled for the RECO meeting, which starts at 3:30PM CEST today.  I hope we can clarify the matter there.

**Comment by rovere** [comment]
Ciao @mandrenguyen thanks a lot.
We'll see how it goes.

**Comment by mandrenguyen** [comment]
+1
I'm going and signing as I cannot see how an improved HCAL timing estimate could be problematic.  Nevertheless, it should still be considered whether it's acceptable to put this change into production for the prompt reco about to start in a few days.  For that I believe we should get the ok from JetMET before proceeding.

**Comment by perrotta** [comment]
> +1 I'm going and signing as I cannot see how an improved HCAL timing estimate could be problematic. Nevertheless, it should still be considered whether it's acceptable to put this change into production for the prompt reco about to start in a few days. For that I believe we should get the ok from JetMET before proceeding.

We have to close now the release for the resuming data taking. It is unfortunate that @cms-sw/jetmet-pog-l2  did not provide yet an evaluation of the possible effect of this change into the halo filters, but now a decision has to be taken: relying on the opinions of the main HCAL experts around, and based on the reco signature, we conclude that this PR should be considered for the remaining part of the 2022 data taking, and for the related MC production, and therefore we are merging this PR also in 12_4_X. We still have a few hours ahead to revert it in case of any late motivated objection from jetmet.

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/39227, merged with the same caveat as in https://github.com/cms-sw/cmssw/pull/39227#issuecomment-1250003297

**Comment by alkaloge** [comment]
JME-MET was made aware of this discussion/PR only **two** days ago from Matthew's email (Friday late afternoon) and not from any mentions in the comments. The MET scanners team has been already notified, but if you really need to close the PR today, we should have been notified earlier. Still, we will try to reply asap, but naively I would say that we will only know once we get data with the new PR, and then the METscanners team can have a look at the impact.

**Comment by alkaloge** [comment]
The MET scanners team has been already notified. Still, the METscanner teams will try to reply asap, but naively I would say that we will only know once we get data with the new PR, and then the METscanners team can have a look at the impact.

**Comment by mandrenguyen** [comment]
@alkaloge  For info, JetMET was pinged in the PR thread 7 days ago, very shortly after the final comparisons became available.  Before that the PR itself was under evolution, so I could not evaluate what was impacted by the PR.

**Comment by alkaloge** [comment]
> @alkaloge For info, JetMET was pinged in the PR thread 7 days ago, very shortly after the final comparisons became available. Before that the PR itself was under evolution, so I could not evaluate what was impacted by the PR.

agreed, it is just that it is hard to evaluate any PR that can affect data, before collecting data and have a look on it ;)

**Pull request merged**
