### PR TITLE
Run3-alca177 Use of ESGetToken and small change in StudyCaloResponse

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use of ESGetToken and small change in StudyCaloResponse

#### PR validation:

Tested using running the code on low luminosity 2018 data set

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
The failure seems not to be related to this PR. Repeating the tests yet again

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by yuanchao** [comment]
+1
* migration to esConsumes
* static checks warnings are not part of the modification

**Comment by qliphy** [comment]
+1

**Pull request merged**
