### PR TITLE
Remove direct access to DQMStore through containers

### PR DESCRIPTION
**Pull request by knoepfel**
Direct access to the `DQMStore` is discouraged; and access through the `IBooker` and `IGetter` classes is already provided through the `HcalCommon` containers.  This commit removes the direct access to the `DQMStore`.

### CODE REVIEW

**Comment by knoepfel** [comment]
@Dr15Jones FYI

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
@knoepfel in the future please avoid making 1000s of pointless whitespace changes

**Comment by kpedro88** [comment]
+1

**Comment by knoepfel** [comment]
@kpedro88 My editor is configured to remove whitespace errors and to replace tabs with spaces.  Would you call those pointless whitespace changes?

**Comment by kpedro88** [comment]
in principle no, but in practice yes. Everyone's editor is configured differently, and so we end up with a lot of unnecessary churn. For a large legacy code base like CMSSW, it is best just to keep changes minimal, unless e.g. indentation is so terrible that the code cannot be understood.

**Comment by schneiml** [comment]
@kpedro88 Large parts of the DQM codebase have such horrible formatting that we *require* people to use auto-formatting (usually clang-fromat, but almost anything is fine) when they do larger changes. 

I did ask @knoepfel earlier to make sure that the whitespace changes are isolated in one commit, with no other changes, to make reviewing easier; and he did that in this PR as I'd expect.

**Comment by kpedro88** [comment]
Okay, I wasn't aware of this policy. Sorry for the noise.

**Pull request merged**
