### PR TITLE
Run3-gex109E Avoid compilation warnings in some Validation classes in EventGenerator, Mixing and MtdValidation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings in some Validation classes in EventGenerator, Mixing and MtdValidation

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
