### PR TITLE
Adding jet purity and efficiency plots to PFValidation package

### PR DESCRIPTION
**Pull request by garvitaa**
#### PR description:
To study the impact of EE leak on jets we wish to monitor the purity and reconstruction efficiency of jets. This update allows the PF validation package to produce these additional plots for comparison.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
Hello, it looks like there are some compilation warnings that should be addressed:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7de3e5/28725/new-build-warnings.log

Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:235:60: warning: 'h_recojet_unmatched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:231:29: warning: 'h_genjet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:235:60: warning: 'h_recojet_unmatched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:231:29: warning: 'h_genjet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:235:60: warning: 'h_recojet_unmatched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:231:29: warning: 'h_genjet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_6_X_2022-11-01-2300/src/Validation/RecoParticleFlow/plugins/PFJetDQMPostProcessor.cc:234:25: warning: 'h_recojet_matched_pt' may be used uninitialized in this function [-Wmaybe-uninitialized]

I believe initializing the pointers to null should fix the problem.

**Comment by garvitaa** [comment]
@emanueleusai
Thank you for reviewing the PR. I have updated the code and made the following 3 changes:
1. Initialized pointers to NULL
2. Made minor modifications to the plotting script
3. Updated the README instructions 

Adding @juska in the loop as he's the convenor for the PFlow group.

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
This adds about 50MB of histogram memory, adding about 220 Monitoring Elements. Are all of the plots necessary? can it be limited to only certain workflows?

**Comment by juska** [comment]
@emanueleusai, could you point us to or specify what are the added 220 Monitoring Elements?
We're a bit surprised for the sizeable increase in memory usage and monitoring elements. This PR should add only 14 new plots.
There's of course many more histograms added to the DQM step and we do see the DQM output file from this package to grow from 3MB to 5MB - but not by 50MB (or do you mean RAM usage during processing?).
Anyway we're now having a look if we could reduce the number of added DQM histograms.

We also changed the plot file format from pdf to png for a more user-friendly browsing experience (at least when using the package manually). This does increase the size of the output directory from 26 to 30MB, but I don't know if this causes bigger changes to the automated RelVal processes.

**Comment by emanueleusai** [comment]
@juska I am looking at this line from cmsbuild's comparison summary:
DQMHistoSizes: Histogram memory added: 47051.510999999984 KiB( 47 files compared)
actually the number of new plots is about 2200, I missed a 0, I see the number in the DQM bin-by-bin interface:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-11-08-2000+7de3e5/53992/dqm-histo-comparison-summary.html

**Comment by juska** [comment]
@emanueleusai thanks. I know understand that what we meant as intermediary "raw" histograms end up to the validation workflows as individual monitoring elements. We'll figure out how to combine most of the histos to reduce the number of new elements to something more sensible. Thanks a lot for raising this point, merging this PR as is would definitely clutter the validation workflow in the way we do not want.

**Comment by emanueleusai** [comment]
-1

- remove from dqm queues (will review when PR becomes active again)

**Comment by perrotta** [comment]
@garvitaa @juska this PR seems to be unattended since a while, already: can we close it?

**Comment by garvitaa** [comment]
We have a student from UB taking care of it at present. We'll update you on the status.

**Comment by swagata87** [comment]
type pf

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by rappoccio** [comment]
Closed in favor of https://github.com/cms-sw/cmssw/pull/43304

**Pull request closed without merging**
