### PR TITLE
Phase2-hgx333A Modify the test code to spot the issue for V17 Geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the test code to spot the issue for V17 Geometry of HGCal

#### PR validation:

Use this test code to spot the issue in the V17 geometry. The fix is to the geometry code will be provided later.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Technical PR for HGCAL V17 geometry testing. No change from the main reco workflow.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
