### PR TITLE
HCALDQM: Add FCDTask for FCD demonstrator (10_3_X)

### PR DESCRIPTION
**Pull request by DryRun**
Adds a new task to the online DQM HCAL application for monitoring the FCD (forward Cherenkov detector) demonstrator.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@DryRun @andrius-k as far as I can see this code is not running anywhere in the test workflows, am I correct? How was it practically tested?

**Comment by andrius-k** [comment]
@fabiocos this is a forwardport of PR #24607 which was tested in online playback.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
