### PR TITLE
Fix some of the gcc620 warnings including possibly important changes to CondTools/Ecal and RecoJets/JetAlgorithms

### PR DESCRIPTION
**Pull request by davidlange6**
Behavior changes for
 -  CondTools/Ecal/src/EcalSRPHandler.cc (clearly a bug)
 -  RecoJets/JetAlgorithms/src/HEPTopTaggerWrapperV2.cc (I believe I understood the code properly)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@davidlange6 
Please change the title of the PR to indicate areas of bugfixes ("fix some warnings" sounds too benign).

**Comment by davidlange6** [comment]
done..

**Comment by dmitrijus** [comment]
+1

**Comment by franzoni** [comment]
+1

same comments as already placed in master for the 91x Fix some of the gcc620 warnings including possibly important changes to CondTools/Ecal and RecoJets/JetAlgorithms 

 @argiro @depasse please take note

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17632	d8e7d2e
- the same changes as in the 91X version #17708 (by construction). Regular reco code is not affected (based on available configurations).
- jenkins tests pass.

**Comment by ggovi** [comment]
+1

**Pull request closed without merging**
