### PR TITLE
Low pt electron seeding: optimisation for phase2

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
Currently low pt electrons (`vector<pat::Electron>  "slimmedLowPtElectrons"`) in phase2 are reco'ed only in barrel. While trying to make tracker-driven seeds of low pt electrons, we loop over endcap tracks also, which is necessary for Phase1 but can be omitted in Phase2, because the code is setup for ECAL/HCAL only. 

This is just to speed up the Phase2 reco, and is an attempt to follow up on this issue: https://github.com/cms-sw/cmssw/issues/40231

There should be no physics change. But, in barrel/endcap transition region, some differences may show up for edge cases where the electron was in endcap tracker initially, but after a brem it bent towards barrel and the energy deposit is recorded in ECAL barrel. 

#### PR validation:
Workflow `21034.21` runs fine.

### CODE REVIEW

**Comment by swagata87** [comment]
enable profiling

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by swagata87** [comment]
From https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18d466/29453/profiling/21034.21/RES_CPU_compare_21034.21.txt
```
Rank			Total%	 		Cumulative					Delta						Symbol name
[4    -> 13  ] [3.3    -> 1.4   ]  [48.77     -> 19.71    ]         [ 19.71    /1427.89   - 48.77    /1463.87   *100% ] = [-1.95 % ]         LowPtGsfElectronSeedProducer::produce             
```
and
```
>> Total Cumulative(old->new): 1018.3799999999997 -> 987.8999999999999
```

**Comment by swagata87** [comment]
type egamma

**Comment by clacaputo** [comment]
please test

**Comment by swagata87** [comment]
Differences in physics was found in PR test which I wasn't expecting. Upon further investigation some strange behaviour was found for phase2 low pT electrons, which is briefly documented below[1]. 

[1] 
**_Description of strange reco issues in phase2 low pt electron collection._** 

For the studies I used Electron gun sample, flat pt **2-100 GeV**, D88 geometry and **noPU** scenario. Events of following gensim root file was reco'ed twice, once in base cmssw (`CMSSW_13_0_0_pre1`) and another time with base+this PR. 
`/eos/cms/store/relval/CMSSW_12_6_0_pre4/RelValSingleEFlatPt2To100/GEN-SIM-DIGI-RAW/125X_mcRun4_realistic_v2_2026D88noPU-v1/2580000/b4de50ed-6d02-4a19-bb2a-d9185e46b5fd.root`

- Plot of supercluster eta vs generated eta shows that for some low-pt electrons there are significant mismatch between supercluster eta and generated eta. This PR rejects the electrons with mis-measured supercluster eta. But we need to understand why this happens in the first place. 
Screen Shot 2023-01-10 at 10 21 51Screen Shot 2023-01-10 at 10 22 25

- Electron Gsf track eta seem to match very well with generated eta. 
Screen Shot 2023-01-10 at 10 28 19Screen Shot 2023-01-10 at 10 29 04

- The following plot is pT response plot (reco pT / gen pT). Clearly the energy regression is not optimal for phase2 scenario, as it was not retrained for phase2. Here, Red is Base, and Green is Base+PR. This PR mostly rejects the huge peak around 0. 
Screen Shot 2023-01-10 at 10 34 28

So, overall it looks like this PR rejects some electrons whose pT and eta are badly reconstructed. But this was not the original plan of the PR. It was meant just for speedup w/o any (or a negligible) reco change as mentioned in PR description. Based on these, let me know whether you prefer to proceed or not. For me it is ok to close this PR and make further studies to understand the issue.

**Comment by clacaputo** [comment]
Hi @swagata87 , thanks a lot for the plots. I would suggest closing this PR and studying a bit further what you have found

**Pull request closed without merging**
