### PR TITLE
VBFGenJetFilter has been modfied in order to select generator level Mjj

### PR DESCRIPTION
**Pull request by gmandorl**
VBFGenJetFilter.cc has been extended.
Possible requirements on the invariant mass of the two pt-leading genJets.
The considered genJets can also be asked to have a minimum DeltaR from the event charged prompt leptons.

### CODE REVIEW

**Comment by arizzi** [comment]
This is backport of a feature already integrated in master (and in older GEN-releases). It is needed to properly generate and filter  VBF-Hmumu samples.

**Comment by kpedro88** [comment]
backport of #20394

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@gmandorl at the moment is this is a not-quite-exact backport of the noted PR. Can you make it exact?

**Comment by kpedro88** [comment]
` GeneratorInterface/GenFilters/BuildFile.xml` was also updated in master

**Comment by gmandorl** [comment]
It seems to me there is no difference in BuildFile.xml

**Comment by kpedro88** [comment]
Ah, it looks like that change was already ported back to 9_3_X.

**Comment by kpedro88** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan this PR is changing the default behaviour fo the release, am I correct? I think we should keep the values that do not modify the behaviour, and modify the parameters in the generator setup required for specific samples

**Comment by clacaputo** [comment]
Dear @efeyazgan, @qliphy,  this PR is needed for ensuring the VBF filtering required in DYJetsToLL_M-105To160_VBFFilter requests that you can find [here](https://cms-pdmv.cern.ch/mcm/requests?dataset_name=DYJetsToLL_M-105To160_VBFFilter_TuneCP5_13TeV-*-pythia8&page=0&shown=274878038111).

Could this feature be approved in an ORP meeting and a new release be made on 93X cycle for this? 

Thanks.

**Comment by fabiocos** [comment]
@arizzi ok, I see that the change of the false default in cfi is in a new PSet not previously present. So backward compatibility is conserved

**Comment by fabiocos** [comment]
+1

**Pull request merged**
