### PR TITLE
DQM histogram axis range change for pPb flow HLT

### PR DESCRIPTION
**Pull request by zc11**
DQM histogram axis range change for pPb flow HLT
Also a small fix for trigger filter name

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by zc11** [comment]
Please test

**Comment by dmitrijus** [comment]
+1

**Comment by zc11** [comment]
Block of code for HighPt trigger DQM was moved by mistake, fix it now

**Comment by dmitrijus** [comment]
+1

**Comment by zc11** [comment]
Change name of DQM trigger path due to change in HLT configuration.
Sorry for many changes to this PR. This should be the last one.......

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
