### PR TITLE
DAQ - adding DCS validity bitfield for high voltage in FED 1022 (12_1_X backport)

### PR DESCRIPTION
**Pull request by smorovic**
DCS HV validity field added to the DCSRecord for discerning if information was available to the data reader.

PR validation:
Added a unittest with the FED dump containing the new format. Test was set to require status seen in the application creating the payload, and it passes.
The whole chain (input source, unpacker) was also tested on the raw file from a cosmic run (with DCS v1 only).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #36294

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
¡1

**Comment by smorovic** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- exact backport of https://github.com/cms-sw/cmssw/pull/36294 for 12_1_X
- DAQ only, no reco-relevant code changes (the code was reviewed by visual inspection)
- no reco changes expected/observed

**Comment by perrotta** [comment]
@smorovic this PR was not mentioned at the ORP meeting on Tuesday amongst the ones we should have waited for before building CMSSW_12_1_1. Therefore, I imagine it is not needed now (I would say so, since it is meant for data taking), and we can start building the release even without it. Please speak up in case you need it urgently in 12_1_1, instead (and justify it, in that case).

**Comment by smorovic** [comment]
@perotta,
it wasn't yet signed at that point. It is not urgent for the next release (I assume we need it for next year global runs), therefore please go ahead without it.

**Comment by qliphy** [comment]
+1

**Pull request merged**
