### PR TITLE
[14_1_X] Fix `maxHitsInModule` for `SiPixelRecHitFromSoAAlpaka`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46686 for HIon data taking. 

Solves https://github.com/cms-sw/cmssw/issues/46656

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by AdrianoDee** [comment]
please test

**Comment by mmusich** [comment]
urgent

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
test parameters:
- relval_opts_gpu = -w upgrade
- workflow_gpu = 14949.402, 17434.402

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46686

**Comment by mmusich** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
test parameters:
- relval_opts_gpu = -w upgrade
- workflow_gpu = 14949.402, 13034.402

**Comment by AdrianoDee** [comment]
please test

**Comment by mmusich** [comment]
as https://github.com/cms-sw/cmssw/pull/45887 was not backported, I guess the tests should pass here?

**Comment by AdrianoDee** [comment]
Yep, I tested an HIN `*.402` wf offline and it worked. Let's see the outcome of the tests.

**Comment by mmusich** [comment]
> I guess the tests should pass here?

in a plain `CMSSW_14_1_X_2024-11-12-2300`

```
runTheMatrix.py --what gpu,upgrade -l 14949.402 -t 4

[...]
 
14949.402_HydjetQMinBias_5020GeV+2022HI_Patatrack_PixelOnlyAlpaka Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Nov 13 16:40:08 2024-date Wed Nov 13 15:56:44 2024; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by mandrenguyen** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
