### PR TITLE
Bugfix: add LA and BP Records to Millepede alignment result split_MP database

### PR DESCRIPTION
**Pull request by mschrode**
Adds the Lorentz-angle and backplane correction records to the special alignments_split_MP.db output database file of the Millepede alignment algorithm. This database file has a special format of one record per IOV and is used internally in the Millepede alignment workflow.

### CODE REVIEW

**Comment by mmusich** [comment]
@mschode I believe it's time to move to condDBv2 in writing the payloads. For the moment I will let the bot validated the diff.

**Comment by mmusich** [comment]
please test

**Comment by mschrode** [comment]
@mmusich Fully agreed! Moving to condDBv2 requires some more modifications of other configs, which is under way. But for the time being, I would like to have the above fix in (it was forgotten in an earlier PR) so that it is not forgotten. Please note: this particular db file is only used internally in MP alignment workflows, so no harm to the outside world.

**Comment by mmusich** [comment]
@mschrode, sure, I see this is just for the split IOV MP payloads. On the other hand the `aligncond_split_iov` command is not currently foreseen with the new backend. Would you please remind us the needs of it and if this is a use-case that we should continue to support?

**Comment by mschrode** [comment]
@mmusich As I understand, in the current MP alignment workflow, it is not possible to load tags with several IOVs as starting conditions. Therefore, the split_MP.db format is used, where there is one tag for each IOV, and then one specifies explicitly one tag to be used. I don't have a clear understanding of the exact reason for this limitation and how much work is required to overcome it. Therefore, I would like to ask to please continue support for this feature if possible so that the alignment workflow can continue uninterrupted until we have re-structured the code.

**Comment by mmusich** [comment]
@mschrode reviewing the code with @diguida we understand this comes from [here](https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L778-L792). It's not fully clear to us the reason of this implementation choice. We might think to review it. For the time being we can provide the equivalent V2 commands to split the IOVs into different sqlite files, but it will be ugly both in terms of commands and from the backend point of view. We'll keep in mind the use case, but we would prefer if you can review the reasons of the limitation in the Event Setup handling

**Comment by mmusich** [comment]
test failures unrelated to the PR

**Comment by mmusich** [comment]
+1 
provided jenkins agrees

**Comment by mmusich** [comment]
please test

**Comment by mschrode** [comment]
@mmusich @diguida Thanks a lot for maintaining the split_IOV functionality for the time being! This is very helpful for the alignment work! (It does not matter really if it is ugly to use, will only be done within the MP workflow.) Thank you also for pointing to the relevant piece of code that rejects the usual, multi-IOV tags. We will keep in mind to figure out the original design choices and see how this can be changed in the future.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
