### PR TITLE
Condition DB modules for HLT workflow: clean up old lumi information DAQ source

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Changes for the modules serving the HLT condition workflows:
- Old DAQ http-based function to get lumisection info has been removed
- Defaults with externally-provided run number have been restored
- Integration tests modified accordingly

#### PR validation:

Integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by gennai** [comment]
@boudoul @amassiro you may want to follow this PR as well

**Comment by yuanchao** [comment]
+1
* clean up old lumi information code
* WF matrix tests and unit tests paae
* no static build warnings or errors

**Comment by qliphy** [comment]
+1

**Pull request merged**
