### PR TITLE
Expand Hcal DetId (supersedes #12829)

### PR DESCRIPTION
**Pull request by kpedro88**
This (hopefully) fixes the pileup problem observed in #12829 by enforcing the new form of the HcalDetId consistently in HcalDigitizer and the HcalDetId constructor. Also, merge conflicts were resolved.

@slava77 @bsunanda - can you start the tests?

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12883	 6c68b62
- changes in the code are OK; 
    - note that this update includes essentially a bugfix in ParticleTowerProducer: the old code was creating CaloTowers with HcalDetId and as a result used HCAL cell positions to place the towers; the updated version uses a more appropriate CaloTowerDetId construction. The positions are not exactly the same and also the ordering of towers ends up being different (both can trigger small differences in PFTower-related objects).
- jenkins tests pass and comparisons with baseline 
    - show no differences in fwlite-based comparisons
    - show no differences except for some small differences in 140.53 (HI) workflow in HIJetValidation plots akPu*. These akPu* jets are made out of PFTowers and they are expected to change slightly.

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1
@kpedro88, there are problems in FastSim WF - 5.1, 135.4

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@civanch - Thanks, I will look into it and submit a subsequent PR when I figure out the fix.

**Comment by kpedro88** [comment]
@civanch - actually, I noticed that you also see this problem in #12888, so maybe it is not caused by this PR?

**Comment by kpedro88** [comment]
@civanch - Just to confirm, when I look back at older comparisons from previous PRs (even going back into December), I see the same behavior. I think the problem must have been introduced a while ago.

**Pull request merged**
