### PR TITLE
Making miniAOD low pt tracks threshold tunable

### PR DESCRIPTION
**Pull request by AdrianoDee**
This PR make configurable the minimun pT for a track to be stored with a reduced precision covariance matrix, previously hard coded to be 0.5 GeV. In order to make also the latter configurable at run time a new variable `minPtForLowQualityTrackProperties` is defined in PATPackedCandidateProducer.  This is also added to PATLostTracks with `minPtToStoreLowQualityProps`.

The further proposal is to lower it to 0.0 GeV for PATPackedCandidateProducer. The impact on miniAOD format size is in the range of 2.5-4.5 % (depending on  PU). 

The relative size increase is checked on a a set of Run3 ttbar samples with multiple < PU >:

relative

The size per event:

sizes_ttbar

The withBS shown here refers to the addition of `offlineSlimmedPrimaryVerticesWithBS` as in  #33778

Further checks in the references below.

#### PR Validation and Further references

BPH Jamboree December 2020 [here](https://indico.cern.ch/event/979184/contributions/4148171/attachments/2163278/3650677/MiniAOD_Run3_Adriano_JamboreeDic2020.pdf)

xPOG Meeting February 2021 [here](https://indico.cern.ch/event/994581/contributions/4181429/attachments/2196037/3712976/xPOG%20Run3%20MiniAOD%20BPH%20Feb2021.pdf)

Further reference [here](https://github.com/AdrianoDee/miniaodstudies/blob/main/README.md)

For a complete documentation, trk4bph meetings: [1](https://indico.cern.ch/event/983890/), [2](https://indico.cern.ch/event/975219/), [3](https://indico.cern.ch/event/968995/) , [4](https://indico.cern.ch/event/964780/), [5](https://indico.cern.ch/event/963424/), [6](https://indico.cern.ch/event/955820/)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
assign xpog

**Comment by AdrianoDee** [comment]
@cmsbuild please test

**Comment by AdrianoDee** [comment]
@slava77 sorry pushed a wrong commit (and reverted it).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
e.g. in reminiAOD of 2018, wf 136.88811

all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811c_patPackedCandidates_lostTracks__PAT_obj_numberOfPixelHits
all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811c_patPackedCandidates_packedPFCandidates__PAT_obj_numberOfHits

presence of detailed information impacts the algorithms downstream which rely on these track details. tau ID and b-tags change in a somewhat minor way.

the miniAOD file in jenkins/bot outputs changes in size  (100 evts) : 10446585 B -> 10686017 B : 2.3% increase, consistent with the details in the PR description.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33777	0cbab0b 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show differences in miniAOD, starting from more track details; https://github.com/cms-sw/cmssw/pull/33777#issuecomment-845583418
    - the observation is based on 071f728, which has identical code changes to 0cbab0b

**Comment by mariadalfonso** [comment]
+xpog

**Comment by qliphy** [comment]
+1

**Pull request merged**
