### PR TITLE
[L1T] update in Phase 2 jet event content

### PR DESCRIPTION
**Pull request by epalencia**
**PR description:**

This PR changes with jet collections are produced in the standard L1 sequence, and are stored in the event content:
- 7x7 histogram puppi jets are removed
- 9x9trimmed histogram jets are added, 9x9 histogram jets are kept in
- Simulated seeded cone puppi jets are removed, keeping only the collection produced by emulation
- The HPS tau simulation/emulation are updated to use the 9x9trimmed jet instead of 7x7 jets.

Local PR: https://github.com/cms-l1t-offline/cmssw/pull/1062
The two commits in that original PR not ported here should be already in master.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
@trtomei We would need to change the l1t inputs to the hlt code, as you can see from the error above. Can you do it or would you like us to take care of this?

**Comment by epalencia** [comment]
I have added a couple of commits from @EmyrClement made in https://github.com/epalencia/cmssw/pull/1: 
- The first commit replaces jet sums calculated from 7x7 jets to those calculated from 9x9trimmed jets (l1tPhase1JetSumsProducer -> l1tPhase1JetSumsProducer9x9trimmed).
- The second commit updates the HLT modules to consume the 9x9trimmed jets instead of the 9x9 jets.

**Comment by epalencia** [comment]
Please test

**Comment by beaucero** [comment]
Okay for HLT-Upgrade

**Comment by cecilecaillol** [comment]
+l1

**Comment by missirol** [comment]
+hlt

I note that there is a file in the HLT Phase-2 folder which defines a module called `l1tPhase1JetCalibrator9x9` at
https://github.com/cms-sw/cmssw/blob/e7e8960dfa2bc1b6f943d14d71edd6a9e04e749b/HLTrigger/Configuration/python/HLT_75e33/modules/l1tSlwPFPuppiJetsCorrected_cfi.py#L3
, but that file is not currently used in CMSSW.

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
