### PR TITLE
Fix MultiTrackValidator seeding layers configuration for FastSim

### PR DESCRIPTION
**Pull request by makortel**
PR #20884 that changed FastSim reconstruction era based broke the seeding layers configuration logic in `Validation/RecoTrack/python/TrackValidation_cff.py`. This PR patches the logic to explicitly handle the FastSim-specific seed producer.

More details (copied from https://github.com/cms-sw/cmssw/pull/20879#issuecomment-343491440)

> The affected code is here
> https://github.com/cms-sw/cmssw/blob/62cb420784a32cbbba120519d49881c752d25ea2/Validation/RecoTrack/python/TrackValidation_cff.py#L194-L202
> Now the `<iteration name>Seeds` module in `iterativeTk_cff.py` is changed with `fastsim` modifier and therefore both of the `if` branches fail leading to `continue`. Except for initialStepPreSplitting and jetCoreRegionalStep which are not used in FastSim and the seeding module is not replaced (and therefore the code above is able to extract layer lists from there).

Tested in CMSSW_10_0_X_2017-11-09-2300, expecting more seeding layers in the MTV histograms vs. seeding layers in FastSim workflows.

@akapoorcern @angirar @slava77 @Dr15Jones

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
