### PR TITLE
Added esConsumes to DynamicTruncation

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- refactored DynamicTruncation to work with esConsumes
- changed ThrParameters to not depend on EventSetup
- GlobalMuonRefitter uses new API

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35310	b5a1b44 
- code changes are technical, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no relevant differences (ignoring the diffs in 140.53  which had a DAS glitch)

**Comment by qliphy** [comment]
+1

**Pull request merged**
