### PR TITLE
Run2-alca137 Change the code for IsoTrkFilter

### PR DESCRIPTION
**Pull request by bsunanda**
Back porting the PR #23792

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
In that case I shall bring back the constants for this PR and to the back ported one with the same values as suggested by Mariarosaria

**Comment by bsunanda** [comment]
@lpernie @arunhep @fabiocos It matches with the changes in #23792.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
+1

**Comment by mariadalfonso** [comment]
@fabiocos @lpernie @deguio 

this PR didn't make the  https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_2_3 
but it would be good to have it in the 10_2 at next occasion, as we need this updated ALCARECO earliest possible

**Comment by deguio** [comment]
hi @kpedro88 @fabiocos 
please consider this PR. it is fully signed, merged in master and was mentioned at the ORP last Tue.
it was agreed to have this one merged for the next 10_2 build and deployed at T0 at the next occasion.
thanks in advance!

@bsunanda

**Comment by kpedro88** [comment]
+1

**Comment by deguio** [comment]
thanks!

**Pull request merged**
