### PR TITLE
[RFC] Optimize MagGeoBuilder with TBB

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Avoid extra work done for provenance tracking when looking up magnetic field related files.
- Use tbb::task_group to concurrently construct interpolators

This is identical to #37934 except with the addition of TBB

#### PR validation:

When using just #37934 running a NANO job with 8 threads and 4 streams, the mag field initialization takes 7 seconds. With this change it drops to 4 seconds. That is about as fast as can be gotten with this change since 1/2 the time in #37934 is still being taken to construct the DDDetector.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by namapane** [comment]
That looks great, but I wonder what is the MF needed for in a NANO job? Shouldn't it be possible to skip it altogether?

**Comment by Dr15Jones** [comment]
@namapane so I intentionally added an exception throw to the mag field builder to see what the data request _stack_ was

```
   [1] Running path 'NANOEDMAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'NANOEDMAODSIMoutput'
   [3] Prefetching for module CandMCMatchTableProducer/'lowPtElectronMCTable'
   [4] Prefetching for module PATElectronRefSelector/'finalLowPtElectrons'
   [5] Prefetching for module PATElectronUserDataEmbedder/'updatedLowPtElectronsWithUserData'
   [6] Prefetching for module LowPtGsfElectronIDProducer/'lowPtPATElectronID'
   [7] Calling method for EventSetup module DD4hep_VolumeBasedMagneticFieldESProducerFromDB/'VolumeBasedMagneticFieldESProducer'
```

**Comment by namapane** [comment]
> @namapane so I intentionally added an exception throw to the mag field builder to see what the data request _stack_ was
> 
> ```
>    [1] Running path 'NANOEDMAODSIMoutput_step'
>    [2] Prefetching for module PoolOutputModule/'NANOEDMAODSIMoutput'
>    [3] Prefetching for module CandMCMatchTableProducer/'lowPtElectronMCTable'
>    [4] Prefetching for module PATElectronRefSelector/'finalLowPtElectrons'
>    [5] Prefetching for module PATElectronUserDataEmbedder/'updatedLowPtElectronsWithUserData'
>    [6] Prefetching for module LowPtGsfElectronIDProducer/'lowPtPATElectronID'
>    [7] Calling method for EventSetup module DD4hep_VolumeBasedMagneticFieldESProducerFromDB/'VolumeBasedMagneticFieldESProducer'
> ```

It looks like PATElectronUserDataEmbedder calls LowPtGsfElectronIDProducer which just picks the field value at (0,0,0) [[here](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoEgamma/EgammaElectronProducers/plugins/LowPtGsfElectronIDProducer.cc?from=LowPtGsfElectronIDProducer&case=true#122)]. It then takes B_z and uses it for a kind of propagation [[here](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoEgamma/EgammaElectronProducers/src/LowPtGsfElectronFeatures.cc#239)].

I'm a bit surprised that NANOAOD modules have to compute more stuff than what is already available in mini, but apart for this:

Building the full MF map just to know Bz at (0,0,0) is a huge overkill.  That could for example be taken from the simple parametrization that is used for some tracker reconstruction tasks [[cf here](https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/MagneticField_cff.py#L14-L15)], which is available with label "ParabolicMf" [1]. 
Care should be taken to avoid using this parametrization elsewhere, so a caveat comment should be added in case people do code copy/paste.
Alternatively we could expose an interface to know the nominal B value given the magnet current (which is used internally to set which field map to build) so that it can be retrieved directly, without having to build any map. 

Of course, if there are other usages of MF beyond this stack, they would need to be looked up as well.

**Comment by Dr15Jones** [comment]
@jpata 
> how would you like to proceed here, given the other PR was merged?

I have a different change that I'm working on finishing that decreases the timing to less than 2 seconds by merging the 9000+ files together into one file. I believe that change is better than this one so we can close this one.

**Comment by namapane** [comment]
> @jpata
> 
> > how would you like to proceed here, given the other PR was merged?
> 
> I have a different change that I'm working on finishing that decreases the timing to less than 2 seconds by merging the 9000+ files together into one file. I believe that change is better than this one so we can close this one.

Uhm how do you count 9000 files? Probably for all maps, at any current? Most of these will never be needed in a normal job (since we just use the 3.8T map, the other are for future emergencies). 
In any case, if you do such a change, please consider that we may need to update the maps so tools to handle files should be available and documented.

Still, I think that the best solution should be to avoiud buiding the MF **at all** for nanoAOD jobs, see above.

**Comment by Dr15Jones** [comment]
> OK could you please commit this tool somewhere under eg. MagneticField/Interpolation/test with documentation for the future? 

Yes, that has been my plan. I also want to see if I can build a unit test that runs with and without the merge files and compares values.

> Also we should check that the change does not break running at different currents (although there should be unit tests for that in principle I think).

I'll see if I can find that.

**Pull request closed without merging**
