### PR TITLE
SiPixel quality harvester for Ultra legacy

### PR DESCRIPTION
**Pull request by tocheng**
#### PR description:

The PR is to update pixel quality harvester for Run-2 ultra legacy

#### PR validation:

The PR update the bad ROC tagging by 
-  using per-layer for Bpix / per-ring for Fpix average digi occupancy instead of average occupancy over the full detector
- using layer/ring dependent fraction threshold to apply the optimized pixel quality tagging
- further reduce redundant payloads

Pixel quality tagging are optimized with layer/ring dependent thresholds with pixel offline group.

No effect on CMSSW standard workflows.

#### if this PR is a backport please specify the original PR:

Not a backport PR

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test workflow 1001.2, 1040

**Comment by tocheng** [comment]
@cmsbuild please test workflow 1001.2, 1040

**Comment by tocheng** [comment]
Can @tlampen or @pohsun take a look at the PR and sign?
Chris is busy and it is weird that I sign off the PR submitted by myself. Thanks.

**Comment by tocheng** [comment]
+1

**Comment by tocheng** [comment]
This PR doesn't affect any performance within CMSSW and it passed the workflow test built in IB and addition workflows that are used to check the PCL at Tier-0.
The plan is to have it merged in master and backport to 10_6. I will prepare the backport today.

**Comment by fabiocos** [comment]
This code will require clang-format cleaning

**Comment by tocheng** [comment]
> This code will require clang-format cleaning

@fabiocos Could you please provide some instruction how to do that?
Thanks.

**Comment by mmusich** [comment]
@tocheng

> Could you please provide some instruction how to do that?

Something like: 
  * `scram build code-checks-all`
  * `scram build code-format-all`

should work

**Comment by fabiocos** [comment]
+1

we will do it afterwards

**Pull request merged**
