### PR TITLE
Phase2-hgx336E Try to fix an error in the code for HGCal V16 Geometry and take care of the #define statement in Geometry/HGCalCommonData/src

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to fix an error in the code for HGCal V16 Geometry and take care of the #define statement in Geometry/HGCalCommonData/src

#### PR validation:

This is a simple change to reduce potential printouts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by perrotta** [comment]
Thank you @bsunanda 
Could you please profit of this otherwise trivial PR to fix also https://github.com/cms-sw/cmssw/pull/41048#pullrequestreview-1359695692 (from the same PR). It looks like being a typo, since you included explicitely an index = 48 for a vector which was dimensioned [0-47]

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
@bsunanda could you please rephrase the title of the PR so that it refers to the bug-fix, rather than to commenting out the debug flag?

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
