### PR TITLE
HIN ECAL monitoring of pulse fit fnctions

### PR DESCRIPTION
**Pull request by rkunnawa**
This is a DQMOffline module to check the chi squared of the fit functions in the ECAL. required to check during the PbPb data taking. This is the 80X version of the PR #12484.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@rkunnawa @deguio - apologies for the very generic question - why do we need a "HI" specific version of ecal  pulse shape monitoring?

**Comment by rkunnawa** [comment]
Hi @davidlange6, Since the heavy ion system doesnt have OOT PU we decided to use the "global" reco for online HLT and "multifit 50ns" for the offline reco. We did some studies on MC and run1 Data and wanted to monitor the performance of the fits in run2 data incase we have to request a re-reco with a different method. @yetkinyilmaz @mverwe @richard-cms can comment more about this.

**Comment by mverwe** [comment]
Hi, this will be discussed today still with TSG. But it looks like we will start running with multi-fit in HLT since the risk of changing last moment is considered to be too high. We however want to monitor the behaviour so that in case multi-fit leads to a large signal loss in PbPb collisions, we detect it as soon as possible.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
