### PR TITLE
[RECO_ANALYSIS] fixes needed to build cxxmodules

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Removed un-used include statement
```
DataFormats/Candidate/interface/CandidateWithRef.h:#include "DataFormats/CaloRecHit/interface/CaloRecHit.h"
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
> `DataFormats/Candidate/interface/CandidateWithRef.h:#include "DataFormats/CaloRecHit/interface/CaloRecHit.h"`

I'm not sure why this include is here.
I suggest to remove this include instead.

**Comment by slava77** [comment]
> > `DataFormats/Candidate/interface/CandidateWithRef.h:#include "DataFormats/CaloRecHit/interface/CaloRecHit.h"`
> 
> I'm not sure why this include is here.
> I suggest to remove this include instead.

@smuzaffar 
please check and update this PR or comment on an alternative action.
Thank you.

**Comment by smuzaffar** [comment]
@slava77 , you are right. This header was not needed. I have updated the PR

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26959	94bfc4a
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
