### PR TITLE
Run4-hgx267 Fix masking mechanism for partial wafer definition in HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix masking mechanism for partial wafer definition in HGCal

#### PR validation:

Tested using runTheMatrix test workflow 32634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by silviodonato** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
