### PR TITLE
Dynamic strip reco v2

### PR DESCRIPTION
**Pull request by andrewj314**
Rebase of DynamicStripReco_v2 branch to 7_6_X, with a goal to subsequently backport to 7_5_X.

This adds a new method for calculating tau isolation by dynamically altering strip size.

### CODE REVIEW

**Comment by veelken** [comment]
The dynamic strip reconstruction improves the reconstruction of low pT pi0s. 
The previous tau reconstruction did not work optimally for low pT pi0s, in case the photons produced in the pi0 decays convert within the tracker (and then bend in phi due to the magnetic field).

The tau energy reconstruction and tau ID efficiency will change by a few %, the neutral isolation pT sum of the tau may change by a few GeV too.

More details of the dynamic strip reconstruction are given in AN-15/083.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by andrewj314** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1

for abaac8e
- errors should be fixed:
   -  in miniAOD and PAT setups
e.g. in step5 or workflow 4.53
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10215/6349/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/step5_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT.log
    - in HLT setup  
```
MissingParameter: Parameter 'applyPhotonPtSumOutsideSignalConeCut' not found.
```
e.g. in workflow 1306.0 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10215/6349/runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15/step2_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15.log

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1

it looks like the errors are still there

HLT setups
```
----- Begin Fatal Exception 19-Jul-2015 16:40:27 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PFRecoTauDiscriminationByIsolation label='hltPFTauMediumAbsoluteIsolationDiscriminatorReg'
Exception Message:
MissingParameter: Parameter 'applyPhotonPtSumOutsideSignalConeCut' not found.
----- End Fatal Exception -------------------------------------------------
```

PAT setups
```
/RecoTauTag/Configuration/updateHPSPFTaus_cff.py", line 36, in <module>
    hpsPFTauDiscriminationByPhotonPtSumOutsideSignalCone*
NameError: name 'hpsPFTauChargedIsoPtSum' is not defined
```

AJ, please push to github only after you have tested at least with the minimum that we ask
``` runTheMatrix.py -s --useInput all ```

**Comment by slava77** [comment]
@cmsbuild please test
is it ready by now?

**Comment by slava77** [comment]
BTW, if you update a PR and see no action for a day or so, please be proactive and leave a note.
Here, I'm assuming the PR was not ready (even though it was updated 8 days ago)

**Comment by slava77** [comment]
As discussed in the RECO meeting today, we should try to get a working version in a few days.

**Comment by slava77** [comment]
-1
superseded by #10605

**Pull request closed without merging**
