### PR TITLE
Kalman BMTF Emu v2.7

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is the latest BMTF emulator for the Kalman algorithm

### CODE REVIEW

**Comment by panoskatsoulis** [comment]
backport of #24855 
This PR includes code of #24237

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by panoskatsoulis** [comment]
hold

**Comment by panoskatsoulis** [comment]
unhold

**Comment by thomreis** [comment]
please test

**Comment by panoskatsoulis** [comment]
This PR needs firstly the PR #24793 to be merged, 
in order to succeed on building.
If I introduce here the required changes for compilation there will be a merge conflict with the above PR.

**Comment by thomreis** [comment]
Hi @panoskatsoulis 
since 10_2 is not used anymore this PR can probably be closed.

**Comment by panoskatsoulis** [comment]
Hi @thomreis, yes this can be closed

**Pull request closed without merging**
