### PR TITLE
Added esConsumes directly in MuonCkfTrajectoryBuilder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Part of the esConsumes migration.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35256	d817891 
- code changes are technical, in line with the PR title/description
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
