### PR TITLE
Relval samples for Sherpa+Blackhat and Sherpa+OpenLoops

### PR DESCRIPTION
**Pull request by thuer**
Added two RelVal steps for Sherpa with external loop generators 
I put them to relval_generator.py, should I change them to extendgen?

I just took the next two free numbers in the generator file, is there any logic in assigning the numbers?

Has to go in after #9272 (Event production is currently broken with Sherpa)

### CODE REVIEW

**Comment by franzoni** [comment]
+1
(these are not part of the set for regular production)

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
are these tests actually confirmed to be working? I see

Matrix_Element_Handler::BuildProcesses(): Looking for processes ......................Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1tL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1tL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1ptL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1ptL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_0L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_0L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_l.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_l.so'.

>::operator:("Initialising OpenLoops Virtual for (d,db,e-,e+): ppll_eexddx_1_")
..Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1tL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1tL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1ptL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_1ptL.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_0L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_0L.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_l.so'.
Library_Loader::LoadLibrary(): Failed to load library 'libopenloops_ppll_l.so'.

**Comment by thuer** [comment]
This is the default output which you get when using Sherpa interfaced with OpenLoops. 
When we asked the openloops authors about them we got this reply
"This is nothing to worry about. The OpenLoops libraries can have different names depending on what exactly they contain. Sherpa just tries all possibilities until it finds a suitable library. The warnings will disappear in a future Sherpa version. "

**Comment by davidlange6** [comment]
+1

ok thanks - but yuck…

**Pull request merged**
