### PR TITLE
Debugged configuration file for BeamPixel

### PR DESCRIPTION
**Pull request by dinardo**
I've debugged the newly made configuration for the BeamPixel in 9_X

### CODE REVIEW

**Comment by dinardo** [comment]
Hi,
I was wondering whether there are any problems in processing this PR.
Many thanks,
- Mauro.

**Comment by dmitrijus** [comment]
Hi,
the pull request contains changes which only there to let you run on lxplus.
I told over email to replace the condition import, but it should not be in this PR - it will crash online DQM.

**Comment by dinardo** [comment]
Hi,
I kindly ask you if you can please give me more information.
Are you referring to the following lines or something else ?

If you are referring to the following lines it's weird that the work on lxplus and they don't on online DQM.

In your comment you are referring to an email which I might not have received.

Many thanks for providing more information.
Kind regards,
- Mauro.

```
process.load("RecoPixelVertexing.Configuration.RecoPixelVertexing_cff")
process.pixelVertices.TkFilterParameters.minPt = cms.double(0.9)

from RecoTracker.TkTrackingRegions.globalTrackingRegion_cfi import globalTrackingRegion
process.pixelTracksTrackingRegions = globalTrackingRegion.clone(RegionPSet = dict(originRadius = cms.double(0.4)))

from RecoTracker.TkSeedingLayers.PixelLayerTriplets_cfi import *
process.PixelLayerTriplets.BPix.HitProducer = cms.string("siPixelRecHitsPreSplitting")
process.PixelLayerTriplets.FPix.HitProducer = cms.string("siPixelRecHitsPreSplitting")

process.pixelTracksHitTriplets.SeedComparitorPSet.clusterShapeCacheSrc = cms.InputTag("siPixelClusterShapeCachePreSplitting")
```

**Comment by dinardo** [comment]
Hi,
I would kindly ask you if you can please follow this up.
Can you please answer to my previous question ?
It seems that things are stuck but I don't understand why !

Many thanks for your cooperation.
- Mauro.

**Comment by dmitrijus** [comment]
I was referring to these lines...

```
-process.load("Configuration.StandardSequences.MagneticField_AutoFromDBCurrent_cff")
+process.load("Configuration.StandardSequences.MagneticField_cff")
```

Was this an intended change?

**Comment by dinardo** [comment]
Hi,
many thanks. Now it's clear.
I guess you want me to restore the line:

`process.load("Configuration.StandardSequences.MagneticField_AutoFromDBCurrent_cff")
`

Is that correct ?
Once you give me your ok. I'll restore it so that the merging of this PR can move one.
Many thanks again.
- Mauro.

**Comment by dinardo** [comment]
Hi,
please let me know so we can close this up.

Many thanks,
- Mauro.

**Comment by dmitrijus** [comment]
I don't know which one is correct.
I assumed that whatever was before this PR was correct,
so if you make a change, you have to be able to explain it.

If you tell me the change was something you intended to do (and not just a temporary change to get it running on lxplus), I will +1 it.

**Comment by dinardo** [comment]
Dear expert,
I've revered back to:

`process.load("Configuration.StandardSequences.MagneticField_AutoFromDBCurrent_cff")
`

Now the python script should run also online.
Many thanks for pushing this forward.
Kind regards,
- Mauro.

**Comment by dinardo** [comment]
Hi,
forgive my naive comment, I might be to paranoid, but when do you think that this merging will occur ?
I just would like to avoid that it goes lost ... though I don't even know whether this can actually happen with git :-)

Cheers,
- Mauro.

**Comment by dmitrijus** [comment]
+1
It will be merged once David L. gets a chance to look at this code and everything is fine.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
