### PR TITLE
adding centrality to offline DQM/Physics for 2018 Heavy Ion run

### PR DESCRIPTION
**Pull request by BetterWang**
adding centrality to offline DQM for 2018 Heavy Ion run

### CODE REVIEW

**Comment by BetterWang** [comment]
@mandrenguyen

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@BetterWang could you please make sure that there is a name of a subsystem in the title of the PR?

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@BetterWang could you please make sure that there is a name of a subsystem in the title of the PR? Then I will be able to sign it!

**Comment by BetterWang** [comment]
Hi @andrius-k , I updated the title to DQM/Physics, hope it is clear enough.

**Comment by andrius-k** [comment]
+1

**Comment by boudoul** [comment]
Thanks @andrius-k and @BetterWang  to take care of PR titles! appreciated

**Comment by fabiocos** [comment]
+1

**Pull request merged**
