### PR TITLE
[DQM] Replace fabs with std::abs to fix clang warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all. Compilation logs: [1](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_15_0_CLANG_X_2024-12-16-2300/DPGAnalysis/HcalTools), [2](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_0_CLANG_X_2024-12-16-2300/DQM/SiStripCommissioningAnalysis), [3](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_0_CLANG_X_2024-12-16-2300/DQMOffline/CalibCalo).

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_15_0_CLANG_X

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
