### PR TITLE
Fix ParticleNetLegacy when running Nano on Run2UL samples

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

This PR fixes the running of the legacy AK8 ParticleNet mass regression in the Nano step on Run2 UL MiniAODs, which was accidentally removed in https://github.com/cms-sw/cmssw/pull/44507.

#### PR validation:

Tested with nano matrix.

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
