### PR TITLE
Phase2-hgx327E Update several scripts in Geometry/HGCalCommonData/test/python to support only v16 and V17 geometries of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update several scripts in Geometry/HGCalCommonData/test/python to support only v16 and V17 geometries of HGCal

#### PR validation:

Test the individual scripts stored

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Update on test scripts, no change is expected from SIM-RECO.

**Comment by rappoccio** [comment]
+1

- Straightforward cleanups of configs.

**Pull request merged**
