### PR TITLE
Calo Layer 2 saturation fixes

### PR DESCRIPTION
**Pull request by bundocka**
- Fix saturation handling for HI centrality and asymmetry algorithms
- Update centrality classes in HI caloParams config 
- Fix MP & Demux jet saturation handling
- Fix Demux MET & MHT saturation handling
- Correct buffer unpacker to use same demux latency convention as online

Apart from the HI specific changes, the rest are edge cases in saturation handling that were discovered by running events with many high energy towers through the MP firmware and checking MP & demux output vs. emulator.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@bundocka 
please prepare 10_3_X backport of this.

**Comment by bundocka** [comment]
@rekovic  
https://github.com/cms-sw/cmssw/pull/24885

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
There are changes in `L1TEMU/L1TStage2CaloLayer2/L1TdeStage2CaloLayer2/Problematic EG candidates` in workflows 10024.0 (2017) and 11624.0 (2019), but for some reason not 10824.0 (2018).

Is this intentional? I am not sure this PR warrants changes in 2017 workflows.

**Comment by bundocka** [comment]
This is not intentional. There is no change to code that should affect that histogram.

**Comment by kpedro88** [comment]
Maybe this is another instance of #24279. We really need to understand and fix the underlying problem there.

**Comment by fabiocos** [comment]
@kpedro88 I would say so
@bundocka @rekovic could you please confirm, so as we move forward?
Is there any investigation ongoing on this non reproducibility of parts of the L1T DQM?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
