### PR TITLE
Remove EventSetup from PixelFitterBase-derived classes

### PR DESCRIPTION
**Pull request by makortel**
Pass the `EventSetup` via `run()` arguments instead.

Tested in 10_5_0_pre1, no changes expected.

@Dr15Jones

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
This will be needed for #25783

**Comment by fabiocos** [comment]
@ssekmen the change in fastsim looks obvious and minimal, could you please check and comment or sign it?

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
