### PR TITLE
Modernized modules in CommonTools/RecoUtils

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- converted to thread friendly types
- finished fillDescriptions

#### PR validation:

Code compiles without CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
abort

**Comment by perrotta** [comment]
+1
- Successfully tested in https://github.com/cms-sw/cmssw/pull/39659

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
abort test

**Pull request merged**
