### PR TITLE
Phase2-hgx294 Update the longitudinal structure for the V16 (D86) geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the longitudinal structure for the V16 (D86) geometry of HGCal

#### PR validation:

Tested using Overlap checking tool and with the runTheMatrix for D86

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@AdrianoDee, @srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Without any plots of validation or pointer to the discussion, I only check on the effect of this PR. It affects only D86 as expected. Changes introduced in this PR is limited to XML, and log debug in the plugins.

FYI @cms-sw/hgcal-dpg-l2

**Comment by perrotta** [comment]
+1
- xml code changes for the V16 (D86) geometry of HGCal
- Differences  are visible in the corresponding workflow: as usual they are mostly due to the modified random seed sequences, and it is hard to disentangle the real effect of this PR in the automatically run validation plots

**Pull request merged**
