### PR TITLE
Migration of HLT to 10_6 for Tau changes

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration to 10_6 for Tau changes

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A (not a backport)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
