### PR TITLE
Run3-hcx213 Make HcalSimParameter class to handle simulation parameters for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Handle all simulation parameters of Hcal coming from CompactView in a geometry class so that Simulation class will not require handling CompactView

#### PR validation:

Currently it does not affect any workflow. Subsequent ones utilizing these changes will. So the changes are tested with standalone tests

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by bsunanda** [comment]
@ggovi Could you please sign this PR. With this I would be able to simplify the HCAL simulation code. Thanks

**Comment by bsunanda** [comment]
@fabiocos @kpedro88 Could this PR be merged soon?

**Comment by fabiocos** [comment]
@ggovi please have a look, this PR involves new code for CondFormats

**Comment by fabiocos** [comment]
@bsunanda from a visual inspection the code looks ok to me. I have tried your standalone test anyway, and apparently something is incorrect in the input configuration (although unrelated to this PR):

```
----- Begin Fatal Exception 08-Aug-2019 15:09:33 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=XMLIdealGeometryESSource label=''
Exception Message:
edm::FileInPath unable to find file Geometry/MuonCommonData/data/design/muonYoke.xml anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /build/fabiocos/110X/27609/CMSSW_11_0_X_2019-08-08-1100/poison:/build/fabiocos/110X/27609/CMSSW_11_0_X_2019-08-08-1100/src:/build/fabiocos/110X/27609/CMSSW_11_0_X_2019-08-08-1100/external/slc7_amd64_gcc700/data:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-08-08-1100/poison:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-08-08-1100/src:/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-08-08-1100/external/slc7_amd64_gcc700/data
Current directory is: /build/fabiocos/110X/27609/CMSSW_11_0_X_2019-08-08-1100/work
----- End Fatal Exception -------------------------------------------------
```

Which are the standalone tests you have run?

**Comment by bsunanda** [comment]
@fabiocos I used cmsRun Geometry/HcalCommonData/test/python/runHcalParametersFromDDAnalyzer_cfg.py
Now the cfi file used in the geometry might need changes due to Yana's fix. I shall look into that

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@fabiocos I updated the cfi files - the test runs fine now. This is my stand-alone test
cmsRun Geometry/HcalCommonData/test/python/runHcalParametersFromDDAnalyzer_cfg.py
I want to go to the next step of using them in simulation. Can this be integrated fast

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@bsunanda as far as I can see the PR looks ok, I will wait for the test and integrate it, @ggovi may have an expert look next week when he is back and possibly comment for further updates

**Comment by fabiocos** [comment]
@cvuosalo @pohsun given the minimal nature of the adjustment (unrelated from the code) I take your previous signature as good.
@ggovi please check at your earliest convenience

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by cvuosalo** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
