### PR TITLE
HLT Menu Migration to 11_2_0_pre2 Template

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
## PR description:
HLT Menu Migration to 11_2_0_pre2 Template
Cleanup of old "2018" style menu
Based on CMSSW_11_2_0_pre2

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
