### PR TITLE
Use edm::ProducerBase in DigiAccumulatorMixModFactory parameters

### PR DESCRIPTION
**Pull request by makortel**
This PR replaces the `edm::stream::EDProducerBase` parameter with more general `edm::ProducerBase` in `DigiAccumulatorMixModFactory`. The argument is used to call `produces<T>()`, so there is no need to restrict to `stream` producers.

Tested in 10_1_0_pre1, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+1

**Comment by Dr15Jones** [comment]
@civanch `ProducerBase` is the base class for all the different kinds of `EDProducers`. If the base class is sufficient for what needs to be called, then that is the best choice.

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@Dr15Jones , do I understand correctly, that at some moment ::stream:: will not be needed any more?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
