### PR TITLE
Fix the hcaletValue function.

### PR DESCRIPTION
**Pull request by matz-e**
As the current implementation does not work for fine granularity HF
TP, it needs the additional version parameter to give proper values
for version ==1 and allow to query |ieta| > 32.

As an alternative, the `hcaletValue` functions that take `ieta` parameters should be removed/deprecated.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by jimbrooke** [comment]
Does this PR have an impact on L1 trigger jet energy scales?

**Comment by mmusich** [comment]
please test

**Comment by matz-e** [comment]
@jimbrooke I don't think so, this is just messing with the interface, and not changing anything w.r.t. algorithms.

**Comment by matz-e** [comment]
I have actually removed the `hcaletValue(ieta, compET)` function, as adding the version makes it overlap with the signature of `hcaletValue(ieta, iphi, compET)`, and can lead to unwarranted side-effects.

I've also tried to patch up the dependencies as good as I can understand them, if someone could point me to testing procedures for those packages or look over the changes, that would be great.

**Comment by deguio** [comment]
please test

**Comment by abdoulline** [comment]
Dear reviewers, 
@diguida, @cerminar, @franzoni, @mmusich, @mulhearn, @davidlange6 
can you please review it and eventually sign? Thanks.
I'm afraid we'll not have correct L1 HF 1x1 emulation (= data L1 re-emulation) without this fix in 80X.

**Comment by matz-e** [comment]
@abdoulline, I see some differences here: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2016-02-22-1100+13252/12602/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/HcalDigisV_HcalDigiTask.html that I may have to check on. This does not directly affect 1x1 emulation, but rather the ability of dealing with 1x1 downstream.

**Comment by abdoulline** [comment]
I see, Matthias. 
So we suspend it  (till you'll be back to investigate next week)?

**Comment by matz-e** [comment]
Unless you feel comfortable merging it. I think that the differences are probably due to the code properly looking at the depth/version of the TP, and thus shifting some things between HE and HF, but I'd like to cross check the corresponding workflows.

**Comment by mulhearn** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by mmusich** [comment]
@matz-e @abdoulline shall we expect follow-ups to this comment https://github.com/cms-sw/cmssw/pull/13252#issuecomment-187859367 (sorry if it was discussed yesterday at the ORP, I could not attend)

**Comment by abdoulline** [comment]
@matz-e 
I'd expect this to be followed up asap in "HF 1x1 TP" thread?

**Comment by matz-e** [comment]
I fixed a comparison in the DQM code, in my local release areas the tests are identical now.

**Comment by mmusich** [comment]
please test

**Comment by abdoulline** [comment]
Matthias, did you run 
runTheMatrix tests after update yesterday? 
I mean the changes shouln't affect old/"regular" 2x3 HF TPs in Run1 tests?

**Comment by abdoulline** [comment]
...I was too fast... 
Jenkins test obviously show there is no problem with 2x3 HF TPs per se
(with Run1 and 2015 geometry).

**Comment by mmusich** [comment]
@abdoulline thid PR is not yet merged. Is this needed for #13581 to work properly?

**Comment by abdoulline** [comment]
No, it's not _needed_, as far I know

But David refers to it as a possible culprit in the thread
https://github.com/cms-sw/cmssw/pull/13581

**Comment by davidlange6** [comment]
is the same code... so I worry - but hcal should understand.. I'm making a merged PR so we can test on our side.

**Comment by deguio** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by matz-e** [comment]
Are there any additional requirements to get this in? [The version for 81X](https://github.com/cms-sw/cmssw/pull/13361) got merged a while ago?

**Comment by ggovi** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
