### PR TITLE
[90X] Add new style of e/gamma regressions labels in Run1 MC Global Tags

### PR DESCRIPTION
**Pull request by mmusich**
This PR completes the updates of the e/gamma regressions started in #17048, now also for Run1 simulation. This PR is necessary for integrations of  PR #17101
attn: @rafaellopesdesa

# Summary of changes in Global Tags 
 
## RunI simulation 
 
   * **RunI Ideal scenario** : [90X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_design_v1) as [90X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_design_v1/90X_mcRun1_design_v0): 
      * added additional e/gamma labels for electron / photon regressions (PR #17101)

   * **RunI Heavy Ions scenario** : [90X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_HeavyIon_v1) as [90X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_HeavyIon_v1/90X_mcRun1_HeavyIon_v0): 
      * added additional e/gamma labels for electron / photon regressions (PR #17101)

   * **RunI Realistic scenario** : [90X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_realistic_v1) as [90X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_realistic_v1/90X_mcRun1_realistic_v0): 
      * added additional e/gamma labels for electron / photon regressions (PR #17101)

   * **RunI Proton-Lead scenario** : [90X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_pA_v1) as [90X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_pA_v1/90X_mcRun1_pA_v0): 
      * added additional e/gamma labels for electron / photon regressions (PR #17101)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
#17101 integration is waiting for this PR

**Comment by slava77** [comment]
@davidlange6 
please suggest some actions here or merge this PR

Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
