### PR TITLE
Update GTs for 2023

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR updates the GTs for 2023:
 - **Data** 
    - Online, offline and relval data GTs are updated to `126X` version since (AFAIU) this will be the CMSSW release used for the cosmics data-taking (MWGR, CRUZET and CRAFT) in 2023
      - no real change in these GTs, only update in the name
 - **MC**
   - 2022, 2023, 2024 and Phase2 MC GTs are updated to `130X` version since (AFAIU) this is the release that will be used for 2023 MC
     - the MC GTs are copied from the last version in `autoCond` + a cleanup of the old/unused b-tagging tags as detailed in https://github.com/cms-AlCaDB/AlCaTools/issues/58 (this cleanup is now possible since #39808, #40043, #40058, #40100 have been merged, FYI @yuanchao)
     - I also profited of this PR to remove from `phase1_2022_realistic_postEE` some deprecated tracking MVA tags (see [this CMSTalk post](https://cms-talk.web.cern.ch/t/proposal-of-removal-of-bdt-based-gbrwrapperrcd-tags-for-tracking-selection-from-run-3-globaltags/16757)) which were not removed in #40010 (since the `postEE` key was not yet included in `autoCond` 😄)
        - I did not find any relval in the matrix that consumes the `postEE` GT, @cms-sw/pdmv-l2 is there a wf testing it?
   - Added a few keys in `autoCond` for the 2023 MC GTs
      - Namely: `phase1_2023_design`, `phase1_2023_cosmics`, `phase1_2023_cosmics_design` and `phase1_2023_realistic_hi`
      - I let @cms-sw/pdmv-l2 add the necessary matrix wfs to test these new 2023 MC GTs when the time comes, for now they are untested (but also identical to the 2022 ones, so no harm in not testing them)

GT differences:
- **Run 3 HLT** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_v7/126X_dataRun3_HLT_v1
- **Run 3 HLT frozen** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_frozen_v9/126X_dataRun3_HLT_frozen_v1
- **Run 3 HLT relval** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/125X_dataRun3_HLT_relval_v4/126X_dataRun3_HLT_relval_v1
- **Run 3 Express** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Express_v9/126X_dataRun3_Express_v1
- **Run 3 Express frozen** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Express_frozen_v9/126X_dataRun3_Express_frozen_v1
- **Run 3 Prompt** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Prompt_v10/126X_dataRun3_Prompt_v1
- **Run 3 Prompt frozen** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Prompt_frozen_v8/126X_dataRun3_Prompt_frozen_v1
- **Run 3 offline** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_v14/126X_dataRun3_v1
- **Run 3 offline relval** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/125X_dataRun3_relval_v6/126X_dataRun3_relval_v1
- **2022 design** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_design_Candidate_2023_01_07_10_08_42/130X_mcRun3_2022_design_v1
- **2022 realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_Candidate_2023_01_07_10_08_42/130X_mcRun3_2022_realistic_v1
- **2022 realistic postEE** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_postEE_Candidate_2023_01_07_14_28_36/130X_mcRun3_2022_realistic_postEE_v1
- **2022 cosmic realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_realistic_deco_Candidate_2023_01_07_10_08_42/130X_mcRun3_2022cosmics_realistic_deco_v1
- **2022 cosmic design** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_design_deco_Candidate_2023_01_07_10_08_42/130X_mcRun3_2022cosmics_design_deco_v1
- **2022 realistic HI** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_HI_Candidate_2023_01_07_10_08_42/130X_mcRun3_2022_realistic_HI_v1
- **2023 design** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_design_Candidate_2023_01_07_10_08_42/130X_mcRun3_2023_design_v1
- **2023 realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_Candidate_2023_01_07_10_08_42/130X_mcRun3_2023_realistic_v2
- **2023 cosmic realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_realistic_deco_Candidate_2023_01_07_10_08_42/130X_mcRun3_2023cosmics_realistic_deco_v1
- **2023 cosmic design** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_design_deco_Candidate_2023_01_07_10_08_42/130X_mcRun3_2023cosmics_design_deco_v1
- **2023 realistic HI** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_HI_Candidate_2023_01_07_10_08_42/130X_mcRun3_2023_realistic_HI_v1
- **2024 realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2024_realistic_Candidate_2023_01_07_10_08_42/130X_mcRun3_2024_realistic_v2
- **Phase 2 realistic** https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun4_realistic_Candidate_2023_01_07_10_08_42/130X_mcRun4_realistic_v1

#### PR validation:
Successfully tested with:
`runTheMatrix.py -l 136.731,138.5,138.4,139.001,136.899,12034.0,11634.0,7.23,312.0,12834.0,20834.0 -j10 --ibeos`

#### Backport:
Not a backport.
A backport to 12_6_X with **data GTs only** will be opened soon.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
  - workflows = 12034.0,7.23,12834.0,136.899

**Comment by missirol** [comment]
> I did not find any relval in the matrix that consumes the `postEE` GT

That should be wf `13634.0` (see https://github.com/cms-sw/cmssw/pull/40151#issuecomment-1326932896).

**Comment by francescobrivio** [comment]
> That should be wf `13634.0` (see [#40151 (comment)](https://github.com/cms-sw/cmssw/pull/40151#issuecomment-1326932896)).

Thanks Marino!
Indeed I ran `runTheMatrix.py -l 13634.0 --what upgrade -j 8` privately and it ended successfully.
@cms-sw/alca-l2 I don't think we need to re-trigger tests just for this, in case you disagree feel free to re-trigger them with the addition of this wf.

**Comment by francescobrivio** [comment]
test parameters:
*

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 12034.0,7.23,12834.0,136.899,13634.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

I realized the tests hadn't started yet, so I added the `postEE` MC wfs as well!

**Comment by missirol** [comment]
To run wf `13634.0`, I think one also needs to set `relvals_opt` like in https://github.com/cms-sw/cmssw/pull/40151#issuecomment-1326932896:
https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/28542/consoleText

>Traceback (most recent call last):
>  File "/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/40445/29826/CMSSW_13_0_X_2023-01-07-1100/bin/el8_amd64_gcc11/runTheMatrix.py", line 623, in <module>
>    ret = runSelected(opt)
>  File "/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/40445/29826/CMSSW_13_0_X_2023-01-07-1100/bin/el8_amd64_gcc11/runTheMatrix.py", line 31, in runSelected
>    if len(undefSet)>0: raise ValueError('Undefined workflows: '+', '.join(map(str,list(undefSet))))
ValueError: Undefined workflows: 13634.0

(Obviously, there are also other errors from RelVals and AddOnTests.)

**Comment by francescobrivio** [comment]
Ok based on the errors I think we still need to add Run3 era modifiers in:
- `softPFElectronComputer` (should be in [SoftLeptonByMVAComputers_cff.py](https://github.com/cms-sw/cmssw/blob/master/RecoBTag/SoftLepton/python/SoftLeptonByMVAComputers_cff.py) IIUC)
- `softPFMuonComputer` (in the same file)
- `candidateCombinedSecondaryVertexV2Computer` (should be in [candidateCombinedSecondaryVertexV2Computer_cfi.py](https://github.com/cms-sw/cmssw/blob/master/RecoBTag/SecondaryVertex/python/candidateCombinedSecondaryVertexV2Computer_cfi.py))

@yuanchao could you take a look at this ~quickly?

**Comment by yuanchao** [comment]
@francescobrivio Yes, for the first two modifications, we can try turn useCondDB off. As to candidateCombinedSecondaryVertexV2Computer, it's the one becomes deprecated in run3. We need to change it to Deep b-taggers.

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 12034.0,7.23,12834.0,136.899,13634.0
 - relvals_opt = --what upgrade
 - pull_request = #40464

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
test parameters:
   * workflows = 12034.0,7.23,12834.0,136.899,13634.0
   * relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano
   * pull_request = https://github.com/cms-sw/cmssw/pull/40464

**Comment by mmusich** [comment]
>  is this a temporary issue and I should just retrigger the tests or did I mess up something when specifying the test parameters?

let's try with https://github.com/cms-sw/cmssw/pull/40445#issuecomment-1376941056

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
by the way you can reproduce locally the failure at https://github.com/cms-sw/cmssw/pull/40445#issuecomment-1376510188

```bash
runTheMatrix.py --what upgrade -nel 12034.0,7.23,12834.0,136.899,13634.0
ignoring non-requested file relval_standard
ignoring non-requested file relval_highstats
ignoring non-requested file relval_pileup
ignoring non-requested file relval_generator
ignoring non-requested file relval_extendedgen
ignoring non-requested file relval_production
ignoring non-requested file relval_ged
processing relval_upgrade
ignoring non-requested file relval_cleanedupgrade
ignoring non-requested file relval_gpu
ignoring non-requested file relval_2017
ignoring non-requested file relval_2026
ignoring non-requested file relval_identity
ignoring non-requested file relval_machine
ignoring non-requested file relval_premix
ignoring non-requested file relval_nano
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02767/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-08-0000/bin/slc7_amd64_gcc11/runTheMatrix.py", line 623, in <module>
    ret = runSelected(opt)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02767/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-08-0000/bin/slc7_amd64_gcc11/runTheMatrix.py", line 31, in runSelected
    if len(undefSet)>0: raise ValueError('Undefined workflows: '+', '.join(map(str,list(undefSet))))
ValueError: Undefined workflows: 136.899, 7.23
```

**Comment by tvami** [comment]
+alca
 * tho it needs https://github.com/cms-sw/cmssw/pull/40464 to merge first

**Comment by perrotta** [comment]
+1
- https://github.com/cms-sw/cmssw/pull/40464 has also been merged

**Comment by perrotta** [comment]
@francescobrivio IBs show an error, so far in [wf 11634.1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_0_X_2023-01-11-2300/pyRelValMatrixLogs/run/11634.15_TTbar_14TeV+2021_JMENano/step3_TTbar_14TeV+2021_JMENano.log#/)5, likely coming from the GTs updated with this PR:
```
----- Begin Fatal Exception 12-Jan-2023 08:01:24 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 3
   [1] Running path 'dqmoffline_3_step'
   [2] Prefetching for module NanoAODDQM/'nanoDQMMC'
   [3] Prefetching for module CandMCMatchTableProducer/'boostedTauMCTable'
   [4] Prefetching for module PATObjectCrossLinker/'linkedObjects'
   [5] Prefetching for module PATJetRefSelector/'finalJetsPuppi'
   [6] Prefetching for module PATJetUserDataEmbedder/'updatedJetsPuppiWithUserData'
   [7] Prefetching for module PATJetUpdater/'updatedJetsPuppi'
   [8] Prefetching for module PATJetSelector/'selectedUpdatedPatJetsAK4PFPUPPIFinal'
   [9] Prefetching for module PATJetUpdater/'updatedPatJetsTransientCorrectedAK4PFPUPPIFinal'
   [10] Prefetching for module JetTagProducer/'pfCombinedInclusiveSecondaryVertexV2BJetTagsAK4PFPUPPIFinal'
   [11] Calling method for EventSetup module CandidateCombinedSecondaryVertexESProducer/'candidateCombinedSecondaryVertexV2Computer'
   [12] While getting dependent Record from Record JetTagComputerRecord
Exception Message:
No "BTauGenericMVAJetTagComputerRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
Could you please have a look?

**Comment by francescobrivio** [comment]
> Could you please have a look?

Yes, seems related to this PR. I'm checking it now!

**Comment by tvami** [comment]
Maybe https://github.com/cms-sw/cmssw/pull/40485#issuecomment-1380321261 will resolve this

**Comment by francescobrivio** [comment]
> Maybe [#40485 (comment)](https://github.com/cms-sw/cmssw/pull/40485#issuecomment-1380321261) will resolve this

Unfortunately I don't think so. That PR is modifying the softLepton producers, while this error comes from a jet sequence. I'm still trying to figure out exactly where it's colled so I can add the proper modifier for Run3...

**Comment by missirol** [comment]
> I'm still trying to figure out exactly where it's colled so I can add the proper modifier for Run3...

I guess it comes from (all) the lines with "CSVV2" in
https://github.com/cms-sw/cmssw/blob/ac8ac2424137e35f9ca819a219c675593475b6f6/PhysicsTools/NanoAOD/python/custom_jme_cff.py

Btw, https://github.com/cms-sw/cmssw/pull/40485#issuecomment-1380321261 can be aborted since the failing wf is not `11634.1` (it is `11634.15`).

**Comment by AnnikaStein** [comment]
Given that cross-linking between taus (mentioned for the `boostedTauMCTable` in the exception message in https://github.com/cms-sw/cmssw/pull/40445#issuecomment-1379975381) and jets is also performed in jetsAK4_Puppi_cff.py and the same for CHS, it seems a modifier to exclude CSVV2 is also necessary for the lines here https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py#L85 and here https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py#L127 

For FatJets, SubJets there is also https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jetsAK8_cff.py#L95 and https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jetsAK8_cff.py#L217

**Comment by tvami** [comment]
hi @AnnikaStein should we have this fixed in the PR40485 ?

**Comment by perrotta** [comment]
> hi @AnnikaStein should we have this fixed in the PR40485 ?

Tests with 11634.15 are currently running in #40485

**Comment by AnnikaStein** [comment]
> hi @AnnikaStein should we have this fixed in the PR40485 ?

Yes, let me try to add also the proposed changes to NanoAOD tables such that CSVV2 is only included for run2 era modifiers.

**Pull request merged**
