### PR TITLE
[13.2.X] Fix approximated SiStrip clusters workflow by saving SiStrip FED error information

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/42475
backport of https://github.com/cms-sw/cmssw/pull/42480

#### PR description:

It has been shown (see [talk](https://indico.cern.ch/event/1271490/contributions/5484101/attachments/2679179/4647438/DPG_RawPrime_20230705.pdf)) that events repacked in the RAW' data format and then reconstructed with the dedicated process modifier `approxSiStripClusters` have a different content in terms of tracks w.r.t. the standard reconstruction starting from RAW data (with full SiStrip ADC information). Part of that is expected from information loss intrinsic to the procedure, but dedicated checks showed that in some events few perfectly valid seeds lead to no track reconstructed when data is repacked with the RAW' data format.
This has been shown to depend on the fact the currently the RAW' data format is not saving the list of SiStrip FED errors (collection  `DetIdedmEDCollection_siStripDigisHLT_*_*`) which is used in the tracking setup to construct the list of inactive componets:

https://github.com/cms-sw/cmssw/blob/a5b91a1d0848665cc6f5d3ddb11be28272302e1c/RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc#L405-L417

which is then used in trajectory building.
This PR proposed to fix this issue by keeping the missing collection (32b79ff31e275defbbd3ca982d86a6cd2758f971, supposed eventually to come from the HLT) in the repack procedure and then to use it in the `MeasurementTrackerEventProducer` (4e3c70edf7e6496faa320850ebc556a1a4007522).
After that is no longer necessary to run the SiStrip unpacker `siStripDigis` in the RAW2DIGI step, therefore that's excluded from execution profiting of the process modifier (e6f3888992a7c17621d530a6c247053323b97488).
In addition since the `DetIdedmEDCollection` with the list of Strip FED errors is supposed to come from the HLT in production, the name of the collection should match the one in the [Online HLT Heavy Ion menu](https://github.com/cms-sw/cmssw/blob/f04980c79911900153373b23c402f042276160ee/HLTrigger/Configuration/test/OnLine_HLT_HIon.py#L6129) in order to consume the right collection (as it was done before for `SiStripClusters2ApproxClustersHLT` -> `hltSiStripClusters2ApproxClusters` in https://github.com/cms-sw/cmssw/pull/39863).
This is done in commit 6e38bd933cf0c29de1d6461248d1ef463bbf3719.
This final change is purely technical and it's not expected to generate further regressions.
#### PR validation:

Run successfully `runTheMatrix.py -l 140.58 -t 4 -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/42475 and https://github.com/cms-sw/cmssw/pull/42480 to CMSSW_13_2_X for the 2023 HI data-taking.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1
Differences in comparisons are unrelated to this PR

**Comment by makortel** [comment]
> +1 Differences in comparisons are unrelated to this PR

Could I ask the occurrence of "random comparison differences" to be documented in some way? On a cursory look these look like https://github.com/cms-sw/cmssw/issues/39754

**Comment by mmusich** [comment]
urgent
   * to be included in the next 13_2_X release

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
kindly pinging @cms-sw/ppd-l2

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
