### PR TITLE
[ALCA_RECONSTRUCTION] Apply code-checks/format

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw with extra misc-definitions-in-headers clang-tidy check

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34128	b7f8204
- technical
- compiles

**Comment by yuanchao** [comment]
+1
* code-checks/format (technical)

**Comment by qliphy** [comment]
+1

**Pull request merged**
