### PR TITLE
Run3-gex105C Use ESGetToken in Geometry/CMSCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in Geometry/CMSCommonData

#### PR validation:

Use cfg's in the test area of Geometry/CMSCommonData

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
