### PR TITLE
Include the staggered GE21 geometry in M2 (2023) 

### PR DESCRIPTION
**Pull request by pietverwilligen**
Staggered GE21 geometry (as described today in Simulation meeting)
to be included in the M2 geometry for 2023.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
NB, this can cause an inconsistency with #17944, which introduces another scenario (D12) that uses M2

**Comment by pietverwilligen** [comment]
I checked the modifications to dict2023Geometry.py and they do not interfere. First merging #17944, then #17970 should work fine. D9 should be regenerated afterwards.

**Comment by kpedro88** [comment]
The problem is that D12 will also have to be regenerated with the change in this PR.

**Comment by ianna** [comment]
@kpedro88 - I've removed the file which was holding #17944 integration, so that it would not be too long before it is accepted.

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@pietverwilligen since #17944 is now merged, please rebase this PR on a recent 91X IB and rerun the geometry script to update D12

**Comment by kpedro88** [comment]
-1
until this change is propagated to the new D12 configuration as instructed above

**Pull request closed without merging**
