### PR TITLE
Use of full5x5 cluster shapes to compute the MVA, read gzipped xml files

### PR DESCRIPTION
**Pull request by emanueledimarco**
Back port to 74X the pull request #8655.
@gpetruc @arizzi @cbernet  are also interested in this

### CODE REVIEW

**Comment by arizzi** [comment]
@monttj can you please comment or approve?

**Comment by monttj** [comment]
+1
this is backport to 74X.

**Comment by davidlange6** [comment]
@emanueledimarco - please give this PR a descriptive title for the release notes. Thanks!

**Comment by emanueledimarco** [comment]
@davidlange6 done

**Comment by davidlange6** [comment]
+1
thanks!

**Pull request merged**
