### PR TITLE
HcalDQM: Fix HFRaddam event type

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

This PR updates the event type assignment for HFRaddam calibration events. Affects the plots under the Hcalcalib folder. 

#### PR validation:

Passed `runTheMatrix.py -l limited -i all --ibeos`, plots show expected changes in private DQM GUI test.

### CODE REVIEW

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
