### PR TITLE
Including PPS digi into DigiCosmic_cff.py

### PR DESCRIPTION
**Pull request by mundim**
#### PR description:

This PR changes DigiCosmic_cff.py config file to include PPS in the Digi tasks ir order to solve a problem with PR #32003 as part of the process to include PPS simulation in cmssw.

#### PR validation:
All tests done sucessfully.  runTheMatrix.py --job-reports  -j 14 -l limited --ibeos
reported no issues (after running if 4 times due to timing and other problems, even in condor).
`
4.22        Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
4.53        Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
5.1         Step0-PASSED  Step1-PASSED  -             time          date          exit: 0 0
7.3         Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
8.0         Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
9.0         Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
25.0        Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
101.0       Step0-PASSED  -             time          date          Mon           exit: 0
135.4       Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
136.731     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
136.7611    Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
136.793     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
136.8311    Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
136.874     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
136.88811   Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
140.53      Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
140.56      Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
158.01      Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
312.0       Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
1000.0      Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
1001.0      Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0 0 0 0 0
1306.0      Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
1325.7      Step0-PASSED  Step1-PASSED  Step2-PASSED  -             time          exit: 0 0 0
1330.0      Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
10024.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0 0
10042.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0 0
10224.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
10824.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0 0
11634.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
12434.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
23234.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
23434.999   Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
25202.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0
28234.0     Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  -             exit: 0 0 0 0
250202.181  Step0-PASSED  Step1-PASSED  Step2-PASSED  Step3-PASSED  Step4-PASSED  exit: 0 0 0 0 0

`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by silviodonato** [comment]
please test workflow 7.23, 8.2, 11834.0, 11634.0 with #32003

**Comment by silviodonato** [comment]
please test
@mundim the PR works. I'm just checking if we can merge it also before #32003

**Comment by silviodonato** [comment]
+1

**Comment by mundim** [comment]
> please test
> @mundim the PR works. I'm just checking if we can merge it also before #32003

I'm running the tests over both PR's anyway, just to make sure there is no other wf with problems. It's a bit time consuming but should be ready soon.

**Pull request merged**
