### PR TITLE
Phase2-hgx126 Update base material for HE silicon and make code a bit more generic

### PR DESCRIPTION
**Pull request by bsunanda**
Like to use similar code for HF Nose

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
please test workflow 24034.0
(to see if it changes results from the new geometry)

**Comment by kpedro88** [comment]
@bsunanda can you fix this?
```
----- Begin Fatal Exception 13-Jul-2018 15:49:41 CEST-----------------------
An exception of category 'DDException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module OscarMTProducer/'g4SimHits'
   [3] Using EventSetup component HGCalNumberingInitialization/'hgcalHESiNumberingInitialize' to make data HGCalDDDConstants/'HGCalHESiliconSensitive' in record IdealGeometryRecord
   [4] Using EventSetup component HGCalParametersESModule/'hgcalHESiParametersInitialize' to make data HGCalParameters/'HGCalHESiliconSensitive' in record IdealGeometryRecord
Exception Message:
HGCalGeomParameters: cannot get array CellThickness
----- End Fatal Exception -------------------------------------------------
```

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by smuzaffar** [comment]
@kpedro88 , note that if PR is not fully signed then +1 from orp will not automatically merged it. In case you want a not fully signed PR to be merged then please use +merge command.

**Comment by kpedro88** [comment]
@smuzaffar nope, I just forgot to do +upgrade... I'll edit it

**Pull request merged**
