### PR TITLE
Added between Event callbacks to Tracer log file

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- The Tracer log file now contains entries for the clearing of Event and Source nextTransition times.
- Fixed an ambiguity problem with concurrent EventSetup module calls. Extended the web viewer to handle new information.
- Avoid drawing tracer info if the information is not being displayed within the vertical constraints of the window.

#### PR validation:

Code compiles and tests with various log files succeeded.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/orp-l2 please merge

**Comment by rappoccio** [comment]
+1

* Failures unrelated.

**Pull request merged**
