### PR TITLE
Add low pT electron payloads to Run 2 data/MC and Run 3 MC GTs

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR adds low pT electron payloads to Run 2 data/MC and Run 3 MC GTs as requested at https://indico.cern.ch/event/983008/#40-low-pt-electron-tags. Separate payloads are used for 2016, 2017 and 2018 MC and the 2018 MC payloads are used for Run 3. The data payloads are a composition of the 2016-2018 payloads for each IOV range. The GT diffs are as follows:

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_preVFP_v2/113X_mcRun2_asymptotic_preVFP_v1

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_v2/113X_mcRun2_asymptotic_v1

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2cosmics_asymptotic_deco_v2/113X_mcRun2cosmics_asymptotic_deco_v1

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_v7/113X_dataRun2_v1

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HEfail_v7/113X_dataRun2_HEfail_v1

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_relval_v7/113X_dataRun2_relval_v1

**Prompt-like data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_PromptLike_HI_v5/113X_dataRun2_PromptLike_HI_v1

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Prompt_v4/111X_dataRun3_Prompt_v5

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_design_v1/113X_mc2017_design_v1

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_realistic_v3/113X_mc2017_realistic_v1

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_deco_v3/113X_mc2017cosmics_realistic_deco_v1

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_peak_v3/113X_mc2017cosmics_realistic_peak_v1

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_design_v3/113X_upgrade2018_design_v1

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_v6/113X_upgrade2018_realistic_v1

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HI_v6/113X_upgrade2018_realistic_HI_v1

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HEfail_v6/113X_upgrade2018_realistic_HEfail_v1

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_deco_v6/113X_upgrade2018cosmics_realistic_deco_v1

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_peak_v6/113X_upgrade2018cosmics_realistic_peak_v1

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v11/113X_mcRun3_2021_design_v1

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v13/113X_mcRun3_2021_realistic_v1

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v13/113X_mcRun3_2021cosmics_realistic_deco_v1

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v13/113X_mcRun3_2021_realistic_HI_v1

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v13/113X_mcRun3_2023_realistic_v1

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v13/113X_mcRun3_2024_realistic_v1

#### PR validation:

See https://indico.cern.ch/event/983008/#40-low-pt-electron-tags for details.

In addition, a technical test was performed:

`runTheMatrix.py -l limited,1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but will be backported to 10_6_X for usage in an upcoming re-miniAOD.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
abort

I forgot to add PR #32391 to the tests

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811
- pull_request = 32391

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811
- pull_request = #32391

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

According to the [jenkins output](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/11434/console), the "abort" command was applied to the tests issued by the corrected command as well.

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811
- pull_request = #32391,cms-data/RecoEgamma-ElectronIdentification#16

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- tests with PR #32421 and cms-data/RecoEgamma-ElectronIdentification#16 complete successfully
- PR integration tests run locally without these additional PRs complete successfully
- PR comparison tests show changes only in low pT electron distributions, as expected
- IOVs of data tags have been verified to be correctly composed from the MC tags
- signing off prior to sign-off of PR #32421 as agreed at https://github.com/cms-sw/cmssw/pull/32391#issuecomment-741795195

**Comment by christopheralanwest** [comment]
@silviodonato, @dpiparo, @qliphy Could you please merge this PR? I have another PR that needs to be made on top of this one. Thanks.

**Comment by silviodonato** [comment]
@bainbrid @crovelli @christopheralanwest @cms-sw/reconstruction-l2
I'm a bit confused of https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/16. I see it is removing a file. Do you actually need to remove a file to add the new payloads?

**Comment by silviodonato** [comment]
> +1
> 
>     * tests with PR #32421 and [cms-data/RecoEgamma-ElectronIdentification#16](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/16) complete successfully
> 
>     * PR integration tests run locally without these additional PRs complete successfully
> 
>     * PR comparison tests show changes only in low pT electron distributions, as expected
> 
>     * IOVs of data tags have been verified to be correctly composed from the MC tags
> 
>     * signing off prior to sign-off of PR #32421 as agreed at [#32391 (comment)](https://github.com/cms-sw/cmssw/pull/32391#issuecomment-741795195)

ah! you meant #32391 and cms-data/RecoEgamma-ElectronIdentification#16

**Comment by silviodonato** [comment]
test parameters

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
to check if we can merge this PR without  #32391 and cms-data/RecoEgamma-ElectronIdentification#16

**Comment by silviodonato** [comment]
> test parameters
> 
>     * workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811
> 
>     * pull_request = #32391,[cms-data/RecoEgamma-ElectronIdentification#16](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/16)

@smuzaffar @cmsbuild did not add the `external-required` flag

**Comment by christopheralanwest** [comment]
> > test parameters
> > ```
> > * workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811
> > 
> > * pull_request = #32391,[cms-data/RecoEgamma-ElectronIdentification#16](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/16)
> > ```
> 
> @smuzaffar @cmsbuild did not add the `external-required` flag

@smuzaffar I'm not sure why this error message is produced. The `external-required` flag should no longer be needed and the tests for this PR by itself appear to be running without any issue: https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/11473/console

**Comment by silviodonato** [comment]
+1

**Pull request merged**
