### PR TITLE
Modernized EventSetup modules in Geometry/MTDGeometryBuilder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Merged header and source files for plugins
- Added EventSetup consumes calls
- Used tokens to get data

This should be a purely technical change.

#### PR validation:

- The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Associated with #26584

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
