### PR TITLE
increase beamspot alarmon thr

### PR DESCRIPTION
**Pull request by sikler**
Recently we started to have problems with the beamspot alarm at the beginning of fills when LHC does an emittance scan. Detailed analysis of such a situation can be found at
[https://twiki.cern.ch/twiki/bin/viewauth/CMS/OnlineBeamSpot#23_Aug_2017_audio_alarm_in_run_3](url)

The problem is that the beamspot moves a lot in z direction during this 10 LS-long operation (4 mins), and it is difficult to reconstruct tracks with the present cylinder of origin setting (optimized for stable beams and normal conditions).

It seems that there is no software-signal which could tell us that LHC does an emittance scan.

Since this issue persists, the only way is to increase the "limit of the number of consecutive LSs without beamspot" from 10 to 15. This disables the false alarms (an emittance scan usually lasts for just about 10 LSs, 4 minutes).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
I missed it... 

You have to make a pull request to a master branch first. This change must be in master, before it is merged into 92x.

**Comment by makortel** [comment]
@dmitrijus The master branch PR #20325 was merged 5 hours ago.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
