### PR TITLE
Add low lumi HI jet and photon triggers HLT DQM entries (backport from 75X)

### PR DESCRIPTION
**Pull request by cfmcginn**
These are HLT DQM modules meant to be used for the low-lumi PU=0.4 runs. Based in 741patch1. See pr into 75X here: https://github.com/cms-sw/cmssw/pull/9086

@richard-cms, @kkrajczar

### CODE REVIEW

**Comment by deguio** [comment]
-1
update needed. see comments in #9086
thanks,
F.

**Comment by cfmcginn** [comment]
I've updated per comment, HI Client is now appropriately included in DQMOffline_HLT_Client_cff.py (and a small fix to path name was made as well)

**Comment by cfmcginn** [comment]
Have removed "import math" from HILowLumiHLTOfflineSource_cfi.py, per request in 75X version. Quick test suggests this doesn't break anything.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
