### PR TITLE
Update CLCT thresholds for hadronic showers in CSC

### PR DESCRIPTION
**Pull request by kakwok**
#### PR description:

This PR updates CLCT thresholds for hadronic showers in the emulator. This change is to reflect the latest FW to be deployed in the old TMBs (ring 2 and 3), where the HMT bits of the CLCTs will be a simple pass-through.  CLCT thresholds for the corresponding chambers should be zeroed in the emulator.

This proposal has been presented at the CSC Trigger meeting[1] and L1 Muon DPG meeting by @Nik-Menendez

[1] [CSC Trigger meeting](https://indico.cern.ch/event/1132087/contributions/4750442/attachments/2397258/4099092/22_02_24_HMT_Changes.pdf
)
[2] [L1 Muon DPG](https://indico.cern.ch/event/1139501/contributions/4781581/attachments/2409263/4122221/22_03_16_Endcap_Shower_Trigger.pdf)

#### PR validation:

Validated the L1+HLT workflow with the hadronic shower trigger paths on signal MC samples in a private setup.
- CMSSW_12_3_0_pre5
- L1 Menu: `L1Menu_Collisions2022_v0_1_2.xml`
- HLT config: `kakwok/CSCCluster_12_3_X_signalsPath/V3`

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by kakwok** [comment]
@epalencia I didn't expect simply changing the thresholds would cause the failed tests, I also couldn't get any useful indication of the problem when the logs were available. 
Could you trigger the test again to see if it still fails?

**Comment by perrotta** [comment]
pleaase test
(Errors  were quite likely unrelated: the previous tests have anyhow become too old by now)

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1
- Changes in the emulator in view of the new Endcap Shower Trigger were discussed within the CSC Trigger group and with L1T

**Pull request merged**
