### PR TITLE
Switch on hadronFlavourHasPriority for b-tag Validation module.

### PR DESCRIPTION
**Pull request by acaudron**
backport of PR#11572

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by ferencek** [comment]
@acaudron, can you please close this PR. Thanks

**Comment by ferencek** [comment]
@davidlange6, @degano, @smuzaffar, can one of you close this PR. Thanks

**Comment by smuzaffar** [comment]
close

**Pull request closed without merging**
