### PR TITLE
Improve the DEFINE_FWK_SERVICE macros

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a macro to convert a preprocessor token to a null-terminated string. If the argument is itself a macro, it will be expanded, and the result of the expansion will be converted to a string.

Improve the `DEFINE_FWK_SERVICE` macro to support types that are themselves the result of a macro expansion.

Remove unnecessary concatenation operators from the definition of the `DEFINE_FWK_SERVICE_MAKER` macro.

#### PR validation:

Various framework services build successfully, and no changes in behaviour have been observed.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Review by makortel — COMMENTED** [review]
Thanks @fwyzard. The changes in `DEFINE_FWK_SERVICE(_MAKER)` would need accompanying unit tests (or modifications to existing tests) to ensure the macros behave as expected.

**Comment by fwyzard** [comment]
> The changes in `DEFINE_FWK_SERVICE(_MAKER)` would need accompanying unit tests (or modifications to existing tests) to ensure the macros behave as expected.

I've modified the tests for `DEFINE_FWK_SERVICE` to include a macro expansion.
The behaviour of `DEFINE_FWK_SERVICE_MAKER` should be unchanged, so the fact that the existing tests pass is already a good validation.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
>  /cvmfs/cms-ib.cern.ch/nweek-02732/slc7_amd64_gcc10/external/tkonlinesw/4.2.0-1_gcc7-a301c08bcb310e9e8de6b49167884c26/include/Fed9UUtils.hh:555: note: this is the location of the previous definition
>    555 | #define STRINGIZE(x) STRINGIZE_2(x)
>        | 


What is the best policy for dealing with external packages that define general macros without considering possible conflicts with their users' code ?
Do I just undefine the offending macro ?

**Comment by fwyzard** [comment]
The unit test failure in [SiStripDAQ_O2O_test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1c1d49/24589/unitTests/src/CondTools/SiStrip/test/SiStripDAQ_O2O_test/testing.log) is

> %MSG-e SiStripConfigDb:  (NoModuleName) 10-May-2022 21:53:27 CEST pre-events
>  Caught oracle::occi::SQLException in method usingDatabase with message: 
> ORA-12170: TNS:Connect timeout occurred
> Additional info: Failed to connect to database using parameters 'cms_trk_r/******@cms_omds_tunnel' and partitions 'TI_27-JAN-2010_2:TM_09-JUN-2009_1:TO_30-JUN-2009_1:TP_09-JUN-2009_1'
> 
> %MSG

which _seems_ unrelated to these changes ?

**Comment by makortel** [comment]
> The unit test failure in [SiStripDAQ_O2O_test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1c1d49/24589/unitTests/src/CondTools/SiStrip/test/SiStripDAQ_O2O_test/testing.log) is
> \<snip\>
> which _seems_ unrelated to these changes ?

Right, that test fails already in the IBs (#37888).

**Comment by makortel** [comment]
+core

**Comment by alja** [comment]
+1

**Comment by fwyzard** [comment]
@cms-sw/db-l2 could you sign this ?
I'd rather have it in pre4 .

**Comment by fwyzard** [comment]
urgent

**Comment by francescobrivio** [comment]
+db

**Comment by qliphy** [comment]
merge

**Pull request merged**
