### PR TITLE
GT Updates with L1T updates and tracker ideal alignment (93X)

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunII simulation

   * **RunII Asymptotic scenario** : [93X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v1) as [93X_mcRun2_asymptotic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_asymptotic_v1/93X_mcRun2_asymptotic_v0):
      * Added L1TMuonOverlapParams_static_2016_mc

## Upgrade

   * **PhaseII realistic scenario** : [93X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2023_realistic_v2) as [93X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2023_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_upgrade2023_realistic_v2/93X_upgrade2023_realistic_v1):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET + L1TGlobalPrescalesVetos_passThrough_mc

   * **PhaseI 2018 cosmics scenario** : [93X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018cosmics_realistic_deco_v2) as [93X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_upgrade2018cosmics_realistic_deco_v2/93X_upgrade2018cosmics_realistic_deco_v1):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET

   * **PhaseI 2018 design scenario** : [93X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_design_IdealBS_v2) as [93X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_design_IdealBS_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_upgrade2018_design_IdealBS_v2/93X_upgrade2018_design_IdealBS_v1):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET + TrackerAlignment_Upgrade2017_design_v4

   * **PhaseI 2018 realistic scenario** : [93X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_realistic_v2) as [93X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_upgrade2018_realistic_v2/93X_upgrade2018_realistic_v1):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [93X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_peak_v3) as [93X_mc2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mc2017cosmics_realistic_peak_v3/93X_mc2017cosmics_realistic_peak_v2):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET

   * **PhaseI 2017 cosmics scenario** : [93X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_deco_v3) as [93X_mc2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mc2017cosmics_realistic_deco_v3/93X_mc2017cosmics_realistic_deco_v2):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET

   * **PhaseI 2017 design scenario** : [93X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_design_IdealBS_v3) as [93X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mc2017_design_IdealBS_v3/93X_mc2017_design_IdealBS_v2):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET + TrackerAlignment_Upgrade2017_design_v4

   * **PhaseI 2017 realistic scenario** : [93X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_realistic_v3) as [93X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mc2017_realistic_v3/93X_mc2017_realistic_v2):
      * Added L1TCaloParams_static_CMSSW_9_2_10_2017_v1_8_2_updateHFSF_v6MET

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of https://github.com/cms-sw/cmssw/pull/20397

**Comment by ghellwig** [comment]
thanks!

**Comment by arunhep** [comment]
+1

differences here
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-09-05-2300+20397/22309/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1V.html
are not because of this PR. I have seen it in many other PRs.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
