### PR TITLE
Use script_test_many_writeTotemDAQMapping.py from release if missing locally

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR allows to use `CalibPPS/ESProducers/test/script_test_many_writeTotemDAQMapping.py` from release area if missing locally. Note that during PR tests it is not guaranteed that package `CalibPPS/ESProducer` will be checkout e.g. for PR https://github.com/cms-sw/cmsdist/pull/8764 , unit test `test_XMLToSQLiteMapping` failed due to missing `CalibPPS/ESProducer` 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ee81ff/35212/unitTests/src/CondTools/CTPPS/test/test_XMLToSQLiteMapping/testing.log
```
===== Test "test_XMLToSQLiteMapping" ====
Generated SQLite files
python3: can't open file '/pool/condor/dir_7825/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_X_2023-10-16-1100/src/CalibPPS/ESProducers/test/script_test_many_writeTotemDAQMapping.py': [Errno 2] No such file or directory
Failed in script_test_many_writeTotemDAQMapping.py: status 2

---> test test_XMLToSQLiteMapping had ERRORS
TestTime:72
^^^^ End Test test_XMLToSQLiteMapping ^^^^

```

### CODE REVIEW

**Comment by perrotta** [comment]
@smuzaffar the same kind of fix should be also implemented into CalibPPS/ESProducers/test/script_test_many_writeTotemDAQMapping.py 
where test_writeTotemDAQMapping.py is searched for under $CMSSW_BASE

**Comment by smuzaffar** [comment]
@perrotta , I have updated `script_test_many_writeTotemDAQMapping.py` to not depend on `CMSSW_BASE` instead read the `test_writeTotemDAQMapping.py` from its own directory

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by perrotta** [comment]
@smuzaffar this fix does not seem to be enough, see for example the unit test error in https://github.com/cms-sw/cmssw/pull/43079

After having merged this fix, the test is able to retrieve the file in $CMSSW_RELEASE_BASE/src/CalibPPS/ESProducers/test/script_test_many_writeTotemDAQMapping.py but then it complains when executing [this line](https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/test/test_XML_to_SQLite_mapping.sh#L16) that it is read-only:
```
===== Test "test_XMLToSQLiteMapping" ====
Generated SQLite files
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_13_3_X_2023-10-25-2300/src/CalibPPS/ESProducers/test/script_test_many_writeTotemDAQMapping.py", line 32, in <module>
    with open(test_script, 'r+') as f:
OSError: [Errno 30] Read-only file system: '/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02808/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-10-25-1100/src/CalibPPS/ESProducers/test/test_writeTotemDAQMapping.py'
Failed in script_test_many_writeTotemDAQMapping.py: status 1

---> test test_XMLToSQLiteMapping had ERRORS
```

I have no idea of possible further fixes, besides explicitly adding the package in case the $CMSSW_BASE/src/CalibPPS/ESProducers directory is not found, which looks however a quite inelegant solution to me.

Do you have any better idea?

**Comment by smuzaffar** [comment]
@perrotta , looks like unit test is reading and updating `CalibPPS/ESProducers/test/test_writeTotemDAQMapping.py` file. This is bad. I would suggest that unit tests should make a copy of `CalibPPS/ESProducers/test/test_writeTotemDAQMapping.py` and read/update that copy and run it

**Comment by antoniovilela** [comment]
> @perrotta , looks like unit test is reading and updating `CalibPPS/ESProducers/test/test_writeTotemDAQMapping.py` file. This is bad. I would suggest that unit tests should make a copy of `CalibPPS/ESProducers/test/test_writeTotemDAQMapping.py` and read/update that copy and run it. Copy should be made in current directory ( which will be readable/writable to test)

@smuzaffar @perrotta 
Hi Shahzad, Andrea,
Let's open an issue and assign to PPS, concerning this unit test?

**Comment by smuzaffar** [comment]
I will open a PR to fix this

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/43147 fixes this

**Comment by perrotta** [comment]
> #43147 fixes this

Thank you @smuzaffar !

**Pull request merged**
