### PR TITLE
Fix crash when reporting an unrunnable schedule

### LINKED ISSUE #36726: crash in edm::checkForModuleDependencyCorrectness
Instantiating a `TriggerResultsFilter` in `HLT_SomePath` that depends on the status (as in `HLTPathStatus`) of the path `HLT_SomePath` itself, causes a segmentation fault in `edm::checkForModuleDependencyCorrectness` instead of the usual nice error message about cyclic dependencies:
```
...
#4  <signal handler called>
#5  0x00002ad6ce71bf44 in void std::vector<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo, std::allocator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo> >::_M_realloc_insert<unsigned int&, unsigned int&>(__gnu_cxx::__normal_iterator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo*, std::vector<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo, std::allocator<edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool)::ProgressInfo> > >, unsigned int&, unsigned int&) [clone .constprop.0] () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#6  0x00002ad6ce720a8c in edm::checkForModuleDependencyCorrectness(edm::PathsAndConsumesOfModulesBase const&, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#7  0x00002ad6ce68c1a0 in edm::EventProcessor::beginJob() () from /cvmfs/cms-ib.cern.ch/nweek-02716/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-16-0000/lib/slc7_amd64_gcc10/libFWCoreFramework.so
...
```

To reproduce, use the PR at https://github.com/cms-sw/cmssw/pull/36725 .

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The PathStatusInserter needed to have its path name added.

#### PR validation:

Code compiles and new unit test passes.

fixes #36726

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
> I thought underscores in module names were illegal?

The underscores are a problem when generating a branch name. If module doesn't produce anything we may not be enforcing the underscore restriction.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by Dr15Jones** [comment]
type bug-fix

**Comment by Dr15Jones** [comment]
ping @cms-sw/orp-l2

**Comment by perrotta** [comment]
> ping @cms-sw/orp-l2

@Dr15Jones all these PRs of yours will get merged after pre4, to avoid any possible interference with the Run3 geometry validation which must be performed with it. 
Honestly, I am not able to judge if these PRs can affect anyhow the validation, the possible warning messages or whatever else. However, if you sign them with your blood one by one and assure that they won't affect the outputs in any possible way, and if thery are really urgently needed in the release, we can even decide to merge them now.

**Comment by Dr15Jones** [comment]
@perrotta 

> Honestly, I am not able to judge if these PRs can affect anyhow the validation, the possible warning messages or whatever else. However, if you sign them with your blood one by one and assure that they won't affect the outputs in any possible way, and if thery are really urgently needed in the release, we can even decide to merge them now.

The code associated with these changes only get called if something catestophic has happend and the job is going to fail anyway. These all either allow the system to shut down safely (as opposed to an outright crash) and/or improve the messages about the failure to make it easier to understand what happened. 

Am I confident these changes are correct and would not cause a problem in the release, absolutely. Are these changes so critical as to increase your stress level? Absolutely NOT.

I did the ping just to be sure these were not overlooked because of the dumy workflow 4.76 failures. Waiting until after pre4 is fine.

**Comment by perrotta** [comment]
merge

**Comment by fwyzard** [comment]
@Dr15Jones @perrotta would it be possible to backport this fix to 12.2.x as well ?
HLT is discussing using #36733 for the upcoming commissioning activity, and this fix would make it easier to spot any issues with the schedule dependencies.

**Comment by perrotta** [comment]
> @Dr15Jones @perrotta would it be possible to backport this fix to 12.2.x as well ? HLT is discussing using #36733 for the upcoming commissioning activity, and this fix would make it easier to spot any issues with the schedule dependencies.

No objection from ORP.
Someone has to provide the backport

**Comment by Dr15Jones** [comment]
Backport is done in #36796

**Pull request merged**
