### PR TITLE
Print function migration for EventFilter_L1TRawToDigi

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by kpedro88** [comment]
+1
(I really wish we could just delete the stupid BMTF warning)

**Comment by thomreis** [comment]
Hi @kpedro88,
that is actually in this PR if I'm not mistaken https://github.com/cms-l1t-offline/cmssw/pull/678

**Comment by rekovic** [comment]
The only file of these here used in central workflow  is EventFilter/L1TRawToDigi/python/bmtfStage2Raw_cfi.py, and a PR for removal of print statement is coming. 

The rest of files are in expert-type directories.  One is also deprecated (EventFilter/L1TRawToDigi/python/l1tRawtoDigiBMTF_cfi.py)

**Pull request merged**
