### PR TITLE
Use unique_ptr, not auto_ptr, in L1

### PR DESCRIPTION
**Pull request by wmtan**
The last use of the deprecated std::auto_ptr in the CMS framework is the "put" interface for EDProducts, which also supports std::unique:ptr. This PR changes all put calls in L1 to use std::unique_ptr instead of std::auto_ptr. Some other instances of std::auto_ptr in L1 may also have been changed to std::unique_ptr. Some (but not all) cases where auto_ptr was passed by reference (a bad practice) and ownership was not transferred were changed to pass a bare pointer instead to make it clear that ownership was not transferred.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@rekovic, @mulhearn, @davidlange6 
ping. This was submitted 10 days ago, and passed tests. How about either signing it, or suggesting changes.

**Comment by davidlange6** [comment]
@wmtan - was waiting to integrate more urgent L1 changes. Now this PR does not merge. Could you rebase it (likely the conflicting changes went into the 1100 IB today)

**Comment by wmtan** [comment]
@davidlange6 Thanks for the info. I will rebase it, most likely tomorrow (Friday).

**Comment by wmtan** [comment]
@davidlange6 This PR was just rebased

**Comment by wmtan** [comment]
@cmsbuild please test

**Pull request merged**
