### PR TITLE
avoid ambiguous option --s error for workflow 136.735

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
jenkins tests might not run workflow 136.735, so here is my local test.
```
runTheMatrix.py -i all -l 136.735
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by fabozzi** [comment]
+1

**Comment by smuzaffar** [comment]
merging it as this was just to fix a typo in RECODR2reHLTAlCaTkCosmics which is only used by wf 136.735

**Pull request merged**
