### PR TITLE
Remove PhysicsTools/ParallelAnalysis package

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

The PhysicsTools/ParallelAnalysis seems to be completely unmaintained, and I think it's also unused with all the new analysis methods that people use nowadays (e.g. ROOT RDataFrame, Python ecosystem..). Can it be removed to avoid maintenance burden in the future?

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by qliphy** [comment]
@guitargeek   Should we also remove https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py#L46 ?

**Comment by guitargeek** [comment]
Ah yes, I think we should! Thanks for spotting that.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/core-l2   Do you have further comments?

**Comment by makortel** [comment]
+1

(apologies for the delay)

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
