### PR TITLE
Run3-sim43 Expand passive hits to contain PDG Id of track and store this in CaloSteppingAction

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Expand the contents of PassiveHit class to contain PDG ID of the track causing the hit and this information is now saved in CaloSteppingAction class

#### PR validation:

Tested privately using the python script SimG4CMS/Calo/test/python/calostep_cfg.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda in my understanding this data format is not part of the regular production, and it is used for dedicated studies, am I correct?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
