### PR TITLE
Changing default values of CaloLayer2 Agreement plots

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Changing default values of CaloLayer2 Agreement plots to be zero in the edge case where the histograms are not filled.
Requested in: https://its.cern.ch/jira/browse/CMSLITDPG-770

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@vukasinmilosevic @thomreis as far as I can see the differences look those expected by the update in this PR, they are not spurious, could you please confirm?

**Comment by thomreis** [comment]
Hi @fabiocos 
Yes, those changes in L1TEMU are expected.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
