### PR TITLE
HLTmumutkVtxProducer compatible with multi-threading

### PR DESCRIPTION
**Pull request by silviodonato**
This PR makes HLTmumutkVtxProducer compatible with multi-threading, as requeisted by TSG.

cc: @fwyzard  @alebihan @lmartini

### CODE REVIEW

**Comment by perrotta** [comment]
+1
This is fine, but you must submit it also (and first, in principle...) to 75X

**Comment by fwyzard** [comment]
@perrotta if David  Lange agrees that this is a bug fix, it can enter directly 7.4.x , and be forward ported automatically to 7.5.x .

**Comment by perrotta** [comment]
@fwyzard ; fine with me, but the PR for 75X exists already: #7882

**Comment by davidlange6** [comment]
+1

**Pull request merged**
