### PR TITLE
removing ThePEGInterface interface in favor of the H7 interface

### PR DESCRIPTION
**Pull request by alberto-sanchez**
please test with #21050 cms-sw/cmsdist#3519

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by alberto-sanchez** [comment]
@Andrej-CMS seems like something is missing in 
GeneratorInterface/Herwig7Interface/BuildFile.xml

**Comment by alberto-sanchez** [comment]
@perrozzi :   You have to do 
please test with #21050 cms-sw/cmsdist#3519

**Comment by efeyazgan** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by alberto-sanchez** [comment]
@Andrej-CMS looks like some clang-tidy was not applied to all your files, that  is weird. 
Why do you try to scan the differences in the declaration of methods for the classes of 
ThePEGInterface and Herwig7Interface,  for instance
In Herwig7Interface :  https://github.com/Andrej-CMS/cmssw/blob/9eeb32e195b1c5c7200a665070d89c3a7df120ce/GeneratorInterface/Herwig7Interface/plugins/Herwig7Hadronizer.cc#L33

could be adjusted as in 

https://github.com/alberto-sanchez/cmssw/blob/master/GeneratorInterface/ThePEGInterface/plugins/ThePEGHadronizer.cc#L33

to fix the compilation problem you are seeing.

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by perrozzi** [comment]
the errors seem to be unrelated now, right?

**Comment by alberto-sanchez** [comment]
Yes it seems unrelated, nothing was touched inside GeneratorInterface/Configuration

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by perrozzi** [comment]
(let's try again and see)

**Comment by Andrej-CMS** [comment]
The release validations is failing. This seems to be related to SIM or RECO step. Maybe there is no proper reconstruction or geant4 configuration for CMSSW_10_0_X defined yet.

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by alberto-sanchez** [comment]
@Andrej-CMS the compilation goes OK, however, something is not quite right, see:

****WARNING: Invalid tool cython. Please fix gosam file.

**Comment by Andrej-CMS** [comment]
Hello @alberto-sanchez ,

I'm kind of confused. cython has its own spec-, tool-files, and seems to be properly defined. 
It is also required by gosam.spec and used in gosam-toolfile.spec . Do you have any idea what the reason could be that this warning gets printed?

Kind regards,

Andrej

**Comment by Andrej-CMS** [comment]
Nevermind, I just realized that we migrated to pip cython.

I changed the gosam files. Please check again!

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by Andrej-CMS** [comment]
are the tests still ongoing?

**Comment by perrozzi** [comment]
no, as far as I can see there was an error here
https://github.com/cms-sw/cmsdist/pull/3519#issuecomment-343445454
```
>> Compiling edm plugin /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/plugins/ThePEGLesHouchesInterface.cc 
>> Compiling  /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc 
>> Compiling  /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/RandomEngineGlue.cc 
>> Compiling  /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/Proxy.cc 
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc: In static member function 'static void ThePEGInterface::fillAuxiliary(HepMC::GenEvent*, HepMC::PdfInfo*, const EventPtr&)':
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc:251:31: error: cannot convert 'ThePEG::Units::Energy2 {aka ThePEG::Qty<0, 2, 0>}' to 'double' in initialization
  double scale = eh->lastScale();
                               ^
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_4_X_2017-11-09-2300/src/GeneratorInterface/ThePEGInterface/src/ThePEGInterface.cc:255:57: error: no matching function for call to 'HepMC::GenEvent::set_event_scale(ThePEG::Qty<0, -1, 0>)'
    hepmc->set_event_scale(std::sqrt(scale) / ThePEG::GeV);
                                                         ^

```

**Comment by Andrej-CMS** [comment]
Hello @perrozzi, @all ,

You are right, the compilation fails because the newer version of ThePEG (required for Herwig711), that I pushed to https://github.com/cms-sw/cmsdist/pull/3519 . I thought this PR here is aimed at removing ThePEGInterface from the GeneratorInterface package in favor of Herwig7Interface.

As far as I understand, the compilation and validation (runTheMatrix) shouldn't be performed with ThePEGInterface at all. These tests will always fail, unless we fix the code of ThePEGInterface.

I would be very nice if someone could make a clear statement on how to proceed with these sub-packages. This would also help to find any compilation errors for Herwig7Interface which, at least locally, compiles just fine. 

Kind regards,

Andrej

**Comment by alberto-sanchez** [comment]
@perrozzi The test seems stuck, I wonder if issuing again:

please test with #21050 cms-sw/cmsdist#3519

will help

**Comment by efeyazgan** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by alberto-sanchez** [comment]
The errors, does not seems related with these PRs. Maybe they come from 
0c297da
df93725
added to this topic.

**Comment by mharrend** [comment]
@alberto-sanchez Is there a possibility to run the checks again and finally get Herwig7 into CMSSW? What is at the moment causing the delay?

It would be really very beneficial to have Herwig7 finally available in CMSSW since it is needed to produce a ttbar sample for a Top analysis.

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by mharrend** [comment]
@alberto-sanchez  @perrozzi Looking at the test results page:
The compilation and externals compilation tests succeed, cf. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21052/24587/cmsswtoolconf.log and https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21052/24587/build.log

Thus, I see no reason why this PR cannot be merged

Therefore, I would kindly ask you to merge this PR finally since the failing check is totally unrelated to the changes of the PR and we would really need Herwig7 for an event generation.

**Comment by perrozzi** [comment]
please test with #21050 cms-sw/cmsdist#3519

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
