### PR TITLE
adding scal monitoring to online dqm

### PR DESCRIPTION
**Pull request by sachikot**
adding scal monitoring to online dqm for 75X

### CODE REVIEW

**Comment by deguio** [comment]
-1
waiting one more commit

**Comment by davidlange6** [comment]
@sachikot @deguio - should I close this PR?

**Comment by deguio** [comment]
I would wait a little more...
@sachikot please comment.
thanks,
F.

**Comment by sachikot** [comment]
Hello,

Sorry for late reply. Is it possible to wait few more days to answer if close or not?
I need to talk to my collaborator.

Thanks,
Sachiko


________________________________

**Comment by sachikot** [comment]
Hello Federico,

Thank you for waiting my response. Yes, please close it.

Thanks,
Sachiko

________________________________

**Pull request closed without merging**
