### PR TITLE
[Tracker Alignment] Split vertex resolution validation submitter

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR has three commits:
   * 9dded8b :  adds a script and template (+example) to run the per-run Alignment split vertex validation
   * 83aff3a : adds provision the code to run the PV Validation plotting macro with input luminosity from txt file, when the information is not saved in the input root file
   *  https://github.com/cms-sw/cmssw/commit/c01452eb6bf5f5f8f32faa09b4dc237cf37ccb96 :  restores the values of the  `maxD0Error` and `maxDzError`to the default (=`1.0`) in `RecoVertex.PrimaryVertexProducer.OfflinePrimaryVertices_cfi`.

#### PR validation:

Relies on existing unit tests. 
The submitter script can be tested in release via:
```bash
submitPVResolutionJobs.py -i PVResolutionExample.ini -D /JetHT/Run2018C-TkAlMinBias-12Nov2019_UL2018-v2/ALCARECO -v
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, though it might be backported later depending on the needs.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
