### PR TITLE
Added input parameter for JetCor PI

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Similar to #41529, pi_jetcorrector will take the fixed bin values through the PI interface. If no input parameters found, the default values will be used.

#### PR validation:

Local validation done with getPayloadData.py script. Done code-checks and code-format

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is not a backport and no backport expected.

### CODE REVIEW

**Comment by tvami** [comment]
+db
 * there is no unit test for this I think

**Comment by mmusich** [comment]
> there is no unit test for this I think

though they can be added. The infrastructure is there:

https://github.com/cms-sw/cmssw/blob/b9ec8e4d1657743510425e19119d78d058d05b5b/CondCore/JetMETPlugins/test/BuildFile.xml#L5-L8

**Comment by rappoccio** [comment]
hold

I'd like to see a unit test for this, please.

**Comment by tvami** [comment]
hi @rappoccio , although I agree with the sentiment of having a unit test... not having one is also not a big deal, the real test of this can only be done in an IB only, through the condDB browser. So I'd actually urge having it merged as is, and ask Yuan to follow-up with a unit test, and possible other improvements in a next PR

**Comment by rappoccio** [comment]
unhold

If this can be done in the future that's acceptable.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
