### PR TITLE
Phase2-gem35 First step to move ME0 to GE0

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

This is the first step to rename ME0 as GE0. Here the latest version of ME0 geometry is copied as GE0 geometry. In subsequent steps these xml files will be used to move all ME0 code to standard GEM code.

#### PR validation:

Tested with dumping the geometry and visualizing it along with other muon detector components (no overlap observed).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
GE0

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda @slomeo both this PR and #29497 introduce Geometry/MuonCommonData/data/mf/2026/v3/mf.xml

please decide among yourselves who has priority

**Comment by bsunanda** [comment]
@slomeo @kpedro88 I am changing it to Geometry/MuonCommonData/data/mf/2026/v4/mf.xml

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
