### PR TITLE
Run3-hcx246 Small changes to the dd4hep codes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Trying to debug the geometry access for HCAL in the dd4hep mode

#### PR validation:

Uses standard runTheMatrix.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
