### PR TITLE
Point to 50ns vtx smearing for boosted pPb and clean up (80X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
80X version of #15175

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kurtejung** [comment]
Hi all - can we please push this into the release ASAP?  We need this for MC production studies for our upcoming pPb run.  Thanks.

**Comment by perrozzi** [comment]
@mkirsano, @agrohsje, please include this PR in the next ORP agenda in case is GEN responsibility

**Comment by franzoni** [comment]
@mandrenguyen @jrcastle 

which of the four VtxSmeared scenarios do you plan to use for the MC pre-production 
(also with reference to: https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/3193.html) ?

Once this PR was in a release, prior to any production or relval refresh we'll need to have the RECO beamspot measured. Can you liaise with PdmV to ask for for that preliminary relval to be made, and @jrcastle are you available to do the measurement ?

**Comment by franzoni** [comment]
+1
tested with the recipe reported in  #15175

**Comment by jrcastle** [comment]
Yes, I can make the measurement.  Please point me to the relval once it's made.

**Comment by mandrenguyen** [comment]
@davidlange6 I'm a bit confused why this is stuck, as the 81X version was merged 3 weeks ago.  Is this waiting for the gen conveners?  Are they still @covarell and @govoni ?  Thanks!

**Comment by davidlange6** [comment]
yes, no one has signed it or brought it to my attention. Seems trivial enough.

**Pull request merged**
