### PR TITLE
GT Updates : PhaseII GT updated with the new Jet Energy Corrections

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 

## Upgrade

   * **PhaseII 2023 realistic scenario** : [93X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2023_realistic_v2) as [93X_upgrade2023_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2023_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_upgrade2023_realistic_v5/93X_upgrade2023_realistic_v2): 
      * update of Jet Energy Corrections mentioned here : https://github.com/cms-sw/cmssw/pull/21370#issuecomment-346689916

### CODE REVIEW

**Comment by arunhep** [comment]
attn @kpedro88

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@kpedro88 
this is the error on step3 related to the JECs update

Failed to propagate track: Pt = 4.89723, eta = -3.07669, phi = -0.890748 to ECAL entrance !!
%MSG
----- Begin Fatal Exception 20-Nov-2017 08:29:05 CET-----------------------
An exception of category 'InvalidInput' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'MINIAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODSIMoutput'
   [3] Prefetching for module PATMETSlimmer/'slimmedMETs'
   [4] Prefetching for module PATMETProducer/'patMETs'
   [5] Prefetching for module CorrectedPFMETProducer/'pfMetT1'
   [6] Prefetching for module PFJetMETcorrInputProducer/'corrPfMetType1'
   [7] Prefetching for module ChainedJetCorrectorProducer/'ak4PFCHSL1FastL2L3ResidualCorrector'
   [8] Calling method for module LXXXCorrectorProducer/'ak4PFCHSResidualCorrector'
Exception Message:
 cannot find key 8 in the JEC payload, this usually means you have to change the global tag
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
20-Nov-2017 08:29:08 CET  Closed file file:step2.root

**Comment by kpedro88** [comment]
@aperloff have you seen this error before?

**Comment by aperloff** [comment]
Yes, I have. It means that the L2L3Residual payload is missing from the GT (https://github.com/cms-sw/cmssw/blob/master/CondFormats/JetMETObjects/interface/JetCorrectorParameters.h#L141). Are you running on MC? The MC workflows might have that turned on because what we normally do is put in a placeholder for the L2L3Residuals which just returns a multiplicative factor of 1. It's not as s safe a workflow, but for normal JECs it works just fine. Still, I'm surprised an official workflow would take that chance. I didn't put in the dummy files for L2L3 since that hasn't, in the past, been necessary for PhaseII. Do I need to recreate the GT and re-upload?

**Comment by kpedro88** [comment]
@aperloff from the exception message, it looks like this is something for MET. Probably it doesn't need it, but if it's straightforward to remake the JEC records with dummy residual corrections, that would probably be faster than trying to debug the miniAOD configs.

**Comment by kpedro88** [comment]
Okay, I think this is actually a prefetching issue similar to #20057 - the product of `ak4PFCHSL1FastL2L3ResidualCorrector` is never actually requested because the request is behind a conditional (https://github.com/cms-sw/cmssw/blob/CMSSW_9_3_X/JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h#L169-L175), but it's still marked as a consume, so the framework attempts to prefetch it anyway in newer CMSSW versions. For now, easiest just to put in the dummy corrections.

**Comment by arunhep** [comment]
@kpedro88 @aperloff 
any chance that these dummy tags are prepared and queued to 93X, 94X and 10.0.X queues just like the other ones today?

**Comment by kpedro88** [comment]
@arunhep I asked @aperloff to remake the records, but have not heard back yet. Hopefully soon.

**Comment by aperloff** [comment]
@arunhep @kpedro88 This is next on my list. Will be done soon.

On Nov 22, 2017, at 10:43 AM, Kevin Pedro <notifications@github.com> wrote:

@arunhep
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_arunhep&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=MbFVOVKTzZNH590AiTxbVXb1HJ8EALBS1JrzOF4uZj8&m=menXhEooNtsKV9jRoHIwUbnenuUONUm6dkM2NJCvhE4&s=5FelyQzIjf0bsXayfCJGc4EM869J4VF-1qCQ2OWyUhg&e=>
I asked @aperloff
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_aperloff&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=MbFVOVKTzZNH590AiTxbVXb1HJ8EALBS1JrzOF4uZj8&m=menXhEooNtsKV9jRoHIwUbnenuUONUm6dkM2NJCvhE4&s=d8rlnOFEp_1S02LMVbb0qMN8G4ztgZn76qyiOBk89NI&e=>
to remake the records, but have not heard back yet. Hopefully soon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cms-2Dsw_cmssw_pull_21370-23issuecomment-2D346407017&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=MbFVOVKTzZNH590AiTxbVXb1HJ8EALBS1JrzOF4uZj8&m=menXhEooNtsKV9jRoHIwUbnenuUONUm6dkM2NJCvhE4&s=Su37Q1l8-E6zsd1Q1twLTsTC76fn_xztJfBbB28WJdc&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEldqlVGzZdGAgXCaXwQhy9rzEWrhVInks5s5E8PgaJpZM4QjxaG&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=MbFVOVKTzZNH590AiTxbVXb1HJ8EALBS1JrzOF4uZj8&m=menXhEooNtsKV9jRoHIwUbnenuUONUm6dkM2NJCvhE4&s=s0309LGBcaWzHB9igvsmci49zfFLqIBceNsNdPKTSBs&e=>
.

**Comment by aperloff** [comment]
@arunhep @kpedro88 I have made the new tags and uploaded them to both the production and prep databases. They are:
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK8PFPuppi
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK8PFchs
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK8PF
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK4PFPuppi
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK4PFchs
JetCorrectorParametersCollection_PhaseIIFall17_V4_MC_AK4PF
@kpedro88 I have not queued them yet, nor have I requested a GT.

**Comment by kpedro88** [comment]
@aperloff thanks
@arunhep I submitted a new request with these tags

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@kpedro88 @aperloff thanks. Just updated the GT. lets see if this works.

**Comment by kpedro88** [comment]
@aperloff now it says:
```
----- Begin Fatal Exception 23-Nov-2017 08:28:27 CET-----------------------
An exception of category 'InvalidInput' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'MINIAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODSIMoutput'
   [3] Prefetching for module PATMETSlimmer/'slimmedMETs'
   [4] Prefetching for module CorrectedPATMETProducer/'patPFMetT1JetEnUp'
   [5] Prefetching for module ShiftedParticleMETcorrInputProducer/'shiftedPatMETCorrJetEnUp'
   [6] Calling method for module ShiftedPATJetProducer/'shiftedPatJetEnUp'
Exception Message:
 cannot find key 9 in the JEC payload, this usually means you have to change the global tag
----- End Fatal Exception -------------------------------------------------
```

**Comment by aperloff** [comment]
@kpedro88 is this using the JEC uncertainties? I didn’t include those
either. Let’s try this again. Give me a couple of hours and I’ll have new
payloads for you with dummy uncertainties.

**Comment by aperloff** [comment]
New payloads uploaded (now including a copy of the uncertainties from Summer16_07Aug2017_V2_MC):
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK4PF
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK4PFchs
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK4PFPuppi
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK8PF
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK8PFchs
JetCorrectorParametersCollection_PhaseIIFall17_V5_MC_AK8PFPuppi

**Comment by kpedro88** [comment]
@arunhep can we get one more GT with the requests I submitted? It should work this time. (We're still learning about the interactions between prefetching and PAT sequences...)

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@kpedro88 done !
To avoid too many iterations, its always good to check locally by running the PhaseII wf.

**Comment by kpedro88** [comment]
Yes, this was much more tedious than I expected. I will consider posting an issue for the MET code to add some triggers so unneeded/dummy JECs can be avoided in the future.

**Comment by arunhep** [comment]
@kpedro88 @aperloff can you validate the changes observed in PhaseII workflows because of these changes in JECs? 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-11-26-0000+21370/23958/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17/

once you give me green light, I will sign this PR.

**Comment by kpedro88** [comment]
To me, the changes look consistent with the application of better JECs.

**Comment by kpedro88** [comment]
@arunhep please sign

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
hi all
coming back to loose ends - whats the plan for getting these changes into 10x. That should happen first.

**Comment by arunhep** [comment]
@davidlange6 

>hi all
coming back to loose ends - whats the plan for getting these changes into 10x. That should happen first.

here you go : https://github.com/cms-sw/cmssw/pull/21647

**Comment by davidlange6** [comment]
+1

**Pull request merged**
