### PR TITLE
APE measurement tool: Resolved python3 compatibility issues, added unit test functionality, removed dependency on other package

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

autoSubmitter.py did not run on recent CMSSW releases since ROOT does not work with python2, while python3 execution would throw an error from using the output of "check_output" without decode().

Some additional small changes to remove redundancies were applied, as well as a change to the disk space requested by condor jobs (the target input file size is 350MB, but files can be larger than 400MB anyway) and some formatting changes. Also, the method names now adhere to the CMS naming rules. 

Additionally, added unit test functionality and removed the need to add the package Alignment/TrackerAlignment whenever a measurement is to be performed.

#### PR validation:

I executed the program with an example configuration and made sure it ran as expected. All changes should be transparent.
Also, a unit test can now be run to validate the PR.

####  If this PR will be backported please specify to which release cycle the backport is meant for:
Will be backported to 13_0_X and 13_1_X

### CODE REVIEW

**Comment by mmusich** [comment]
> autoSubmitter.py did not run on recent CMSSW releases since ROOT does not work with python2, while python3 execution would throw an error from using the output of "check_output" without decode().

what about adding a unit test, to avoid this gets broken again in the future?

**Comment by mmusich** [comment]
>  But if one were to add a unit test, one would also have to include the data skimming step if it's supposed to be a meaningful test.

then please do, it should not be much effort!

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@smuzaffar 

it looks like the [unit test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ccb048/33292/unitTests/src/Alignment/APEEstimation/test/ApeTest/testing.log) is failing now because of xrootd issues. Can the input file be copied already to the cmsbuild eos user area?
```
/store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root
```

**Comment by smuzaffar** [comment]
@mmusich file is in ibeos cache now. I do not know why unit tests could not access it using global xrootd director [a] 

[a]
```
UnitTest: ----- Begin Fatal Exception 21-Jun-2023 13:13:41 CEST-----------------------
UnitTest: An exception of category 'FileOpenError' occurred while
UnitTest:    [0] Constructing the EventProcessor
UnitTest:    [1] Constructing input source of type PoolSource
UnitTest:    [2] Calling RootInputFileSequence::initTheFile()
UnitTest:    [3] Calling StorageFactory::open()
UnitTest:    [4] Calling XrdFile::open()
UnitTest: Exception Message:
UnitTest: Failed to open the file 'root://xrootd-cms.infn.it//store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root'
UnitTest:    Additional Info:
UnitTest:       [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root
UnitTest:       [b] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root
UnitTest:       [c] Input file root://xrootd-cms.infn.it//store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root could not be opened.
UnitTest:       [d] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3014] Unable to open file  /eos/cms/store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root; Network is unreachable�
UnitTest: ' (errno=3014, code=400). No additional data servers were found.
UnitTest:       [e] Last URL tried: root://eoscms.cern.ch:1094//store/mc/Run3Winter22DRPremix/WJetsToLNu_TuneCP5_13p6TeV-madgraphMLM-pythia8/ALCARECO/TkAlMuonIsolated-TRKALCADesign_design_geometry_122X_mcRun3_2021_design_v9-v2/2520000/0027e6ed-2626-4ede-97a5-f0a44164b81b.root?tried=&xrdcl.requuid=0a831a3d-2dda-4295-bca8-c4a0f01dd866
UnitTest:       [f] Problematic data server: eoscms.cern.ch:1094
UnitTest:       [g] Disabled source: eoscms.cern.ch:1094
UnitTest: ----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
IB SITECONF has been [fixed](https://github.com/cms-sw/siteconf/commit/85d64ba4fba6aac4d5cbad68e82f491a64b5ad68) now to use global xrootd redirector in case root file is not cached in ibeos area.

**Comment by mmusich** [comment]
OK, the IB is broken. Let's wait for the next one.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/alca-l2 please have a look. This needs to be backported.

**Comment by francescobrivio** [comment]
+1

 - PR according to description
 - new [unitTest](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ccb048/33329/unitTests/src/Alignment/APEEstimation/test/ApeTest/testing.log) is successful

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@mteroerd I notice that when running the APE unit tests in debug mode the following error message show up (see for example https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_2_UBSAN_X_2023-06-28-2300/unitTestLogs/Alignment/APEEstimation#/):
```
===== Test "ApeTest" ====
 TESTING data set skimming
cmsRun /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_2_UBSAN_X_2023-06-28-2300/src/Alignment/APEEstimation/test/SkimProducer/skimProducer_cfg.py sample=UnitTest
UnitTest: Input sample:  UnitTest
UnitTest: Using output name MC_UnitTest_TkAlMuonIsolated.root
UnitTest: Using global tag 131X_mcRun3_2022_design_v2
UnitTest: # MSG-i trackselectionRefitting:  g4Refitting=False
UnitTest: /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.4.1-30ebdc301ebd200f2ae0e3d880258e65/include/c++/11.4.1/future:212:62: runtime error: member call on address 0x147bad9a5560 which does not point to an object of type '_Result_base'
UnitTest: 0x147bad9a5560: note: object has invalid vptr
UnitTest:  7b 14 00 00  b8 ba ec a6 7b 14 00 00  00 00 00 00 00 00 00 00  8c 5e 19 a7 7b 14 00 00  00 00 00 00
UnitTest:               ^~~~~~~~~~~~~~~~~~~~~~~
UnitTest:               invalid vptr
UnitTest:     #0 0x147bac7c858a in std::__future_base::_Result_base::_Deleter::operator()(std::__future_base::_Result_base*) const /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.4.1-30ebdc301ebd200f2ae0e3d880258e65/include/c++/11.4.1/future:212
``` 
(etc.)

Could you please have a look?

**Comment by perrotta** [comment]
By the way, the same also happens in the normal workflows, not only in tests (still for UBSAN builds): see e.g. wfs 136.843 , 140.066 , 140.107 , 158.5 

@mmusich FYI

**Comment by mmusich** [comment]
> workflows, not only in tests (still for UBSAN builds): see e.g. wfs 136.843 , 140.066 , 140.107 , 158.5

Not clear what this has to do with the APE. Also from the log looks like a fwk problem to me.

**Comment by perrotta** [comment]
Yes, perhaps you are right @mmusich : I was misaddressed by seeing it first in the APE unit test added by this PR

**Comment by perrotta** [comment]
@cms-sw/core-l2 [this](https://github.com/cms-sw/cmssw/pull/42012#issuecomment-1612605711) is probably something you want to comment about

**Comment by perrotta** [comment]
Thank you @iarspider 
Ok, not new, nor urgent, then.

**Comment by iarspider** [comment]
Not new - yes, not urgent - I would think so, nice to fix - definitely!

**Comment by mmusich** [comment]
> https://github.com/cms-sw/cmssw/issues/35138 , https://github.com/cms-sw/cmssw/issues/37024 , https://github.com/cms-sw/cmssw/issues/35036 .

out of these three https://github.com/cms-sw/cmssw/issues/37024 looks the one closer to this discussion

**Pull request merged**
