### PR TITLE
Better GEM handling in CSCDigiToRaw

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Changed the interface so no longer have to dereference a nullptr when GEM is not being used.

This problem was discovered by the ASAN build. This also uncovered a bug in the framework where dereferencing a defaultly constructed `edm::Handle` was not causing an exception to be thrown. Once that bug is fixed, the orginal version of this code would be causing an exception to happen whenever GEM is not being used.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical: fix implemented as described in the PR description
- Without this PR, running with #30928 will throw an exception, as desired
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
