### PR TITLE
Pixel Stuck TBM simulation: check conditions in digitizer initialization

### PR DESCRIPTION
**Pull request by mmusich**
As pointed out in https://github.com/cms-sw/cmssw/pull/25524#issuecomment-455207659, the conditions used for the stuck-TBM simulation tests (wf: 10824.7,10842.7) are inconsistent as there are some non-zero probabilities (in `SiPixelStatusScenarioProbabilityRcd`) assigned to certain scenarios which are not included in the scenario DB object (`SiPixelStatusScenariosRcd`).
The new payload proposed in eb2c2ec fixes this, while commit 986a13d takes care of throwing in case of  an inconsistent sets of conditions at the pixel digitizer initialization instead that starting the job and eventually failing later randomly.
Tested in CMSSW_10_5_X_2019-01-17-1100 (architecture: `slc7_amd64_gcc700`) via:
```
dasgoclient --query 'file dataset=/RelValZMM_13/CMSSW_10_3_0_pre5-103X_upgrade2018_realistic_v7-v1/GEN-SIM' > step1_dasquery.log 
cmsDriver.py step2 --conditions auto:phase1_2018_realistic -n 100 --era Run2_2018 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2018 --datatier GEN-SIM-DIGI-RAW --customise SimTracker/SiPixelDigitizer/customiseStuckTBMSimulation.activateStuckTBMSimulation2018NoPU --geometry DB:Extended --filein filelist:step1_dasquery.log --fileout file:step2.root --nThreads 4
``` 

(as in the failing tests: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_10_5_X_2019-01-16-2300/pyRelValMatrixLogs/run/10842.7_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2018_GenSimFullINPUT+DigiFull_killStuckTBM_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/step2_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2018_GenSimFullINPUT+DigiFull_killStuckTBM_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018.log#/65-65) )

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 10824.7,10842.7

Thanks @mmusich!

**Comment by mmusich** [comment]
@civanch can you please check and eventually sign? This would be needed to have a working set of "stuck TBM" simulation relvals in IB (currently there are broken, see PR description)

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
