### PR TITLE
Phase2-TB41: Add first version of October 2018 HGCal TB setup

### PR DESCRIPTION
**Pull request by bsunanda**
In October, 2018 HGCal team made test beam runs with 3 setups. This one describes the first configuration of the setup

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda the test configuration provided runs smoothly on the proposed new geometry, is there any reason to keep its definition in the test area of the SImG4CMS package instead of the HGCal geometry area?

**Comment by civanch** [comment]
@fabiocos , we keep all other test beam software in the SimG4CMS.

**Comment by bsunanda** [comment]
@fabiocos We define the scenario in SimG4CMS area for all TB applications. Also there are some relevant analyzers which we use in many of TB applications. That is why we try to keep one example cfg file in SimG4CMS rather than in geometry - the application is simulation and geometry is one key ingredient to this

**Comment by fabiocos** [comment]
+1

**Pull request merged**
