### PR TITLE
gcc7 compilation warnings fixes in DQM, DQMOffline, DQMServices packages

### PR DESCRIPTION
**Pull request by mrodozov**
Fixes for compilation warnings when compiling with gcc7 and more flags listed here:
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc700/www/mon/9.3-mon-23/CMSSW_9_3_X_2017-07-24-2300
packages 4,5,7 and 8 comp warnings

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort test

**Comment by davidlange6** [comment]
indeed, definitely not -i'll close this,

**Comment by smuzaffar** [comment]
#19941 should cleanup this warning

**Pull request closed without merging**
