### PR TITLE
[12_0_X] Backport the fix on the workflow 537 and the mergeLHE.py script

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

Backport of 
  1. 2e7e1c0ca67865630b9aae21948cf75b6ffad0e5 in #34710 
  2. #34804

The first helps to fix the workflow 537 in the 4-thread mode. The issue is identified in https://github.com/cms-sw/cmssw/issues/34531. The error is caused by a physics issue in the generator meaning that generating merely 2 events may probabilistically cause zero x-section.

The second is a relevant fix to make the `mergeLHE.py` script more generalized (the script is called in workflow 537), as also discussed in https://github.com/cms-sw/cmssw/issues/34531.

#### PR validation:

Workflow 537 works in the 4-thread mode.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #34804
(partial) backport of #34710

**Comment by perrotta** [comment]
type bug fix

**Comment by agrohsje** [comment]
test parameters:
workflow_threading = 537.0
enable_test = threading

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
kindly ping @cms-sw/pdmv-l2 @cms-sw/upgrade-l2

**Comment by kskovpen** [comment]
+1

**Comment by qliphy** [comment]
ping @cms-sw/upgrade-l2

**Pull request merged**
