### PR TITLE
Move L1 code to use oneapi/tbb headers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The old header declarations are deprecated in TBB

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR. PR test runs fine.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
