### PR TITLE
Add validation of seeds and built tracks to trackingOnly validation

### PR DESCRIPTION
**Pull request by makortel**
This PR adds MultiTrackValidator instances for seeds and built tracks to the trackingOnly validation. Following @lveldere's comment https://github.com/cms-sw/cmssw/pull/12542#discussion_r45774848, the "slim" and validation sequences are removed (and I believe the trackingOnly validation sequences should fulfill the use-case of `TrajectorySeedValidation_cff.py`, so I removed that too).

In addition, the LogWarning in `TrackFromSeedProducer` is downgraded to LogInfo, and monitoring of the number of seeds for which the fit fails is added to MTV. Also the dqmFastTimerServiceClient is added to the trackingOnly DQM harvesting to have the FastTimerService histograms.

Tested in CMSSW_8_0_X_2015-12-09-1600, no changes expected in standard workflows.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
thanks matti!

**Comment by makortel** [comment]
Could somebody restart the tests? Thanks.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
DQM & operations, could you please review and sign? Thanks.

**Comment by deguio** [comment]
+1

**Pull request merged**
