### PR TITLE
Update L1T DQM clients to 2018 era

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign. We would like to get the open PRs into 10_1.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
