### PR TITLE
Add cluster compatibility filter to HI miniAOD

### PR DESCRIPTION
**Pull request by mandrenguyen**
Add an event selection filter needed to select hadronic interactions to HI miniAOD.
Tested on wf 140.5611
The added event content is expected to be small.

@denerslemos

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by jpata** [comment]
Thanks for this. No reco changes observed. @mandrenguyen, could you post some numbers on the event size changes? I'm currently getting xrootd errors when I try to run 140.5611.

**Comment by mandrenguyen** [comment]
@jpata 
This PR adds less than 0.1% to the output file size. 
I'm having trouble reading the input dataset as well, but we have a file copied here:
/afs/cern.ch/work/r/rbi/public/forest/HIHardProbes_HIRun2018A-PromptReco-v2_AOD.root

**Comment by jpata** [comment]
OK, thank you for confirming.

**Comment by jpata** [comment]
+reconstruction

- adds `recoClusterCompatibility_hiClusterCompatibility_*` to HI miniAOD to select hadronic interactions
- size increase is understood (0.1% in HI workflows)

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
