### PR TITLE
Switch runTheMatrix tests to use Run 2 eras

### PR DESCRIPTION
**Pull request by mark-grimes**
This changes runTheMatrix tests to use `--era Run2_25ns` instead of `--customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1` (and the 50 ns and HI equivalents).

The two forms of configuration should be functionally identical.  For various reasons there are expected differences if doing simple `diff` on dumps of the configuration files.  I've been running periodic checks to make sure the two forms haven't diverged, results are at:

http://grimes.web.cern.ch/grimes/eraProcessDiffs/

Note that I've made some assumptions when deciding a difference has no functional effect, e.g. ignoring a lot of calo config in the PAT step.  Please check that these assumptions are valid, if not let me know and I'll update the relevant era.  There should be enough information in the results linked above to describe these assumptions.  Some of the CSC configuration is actually more up to date in the era than the customisation, this I've "ignored" since this a reason to move to eras rather then stay with customisations.

I've added a deprecated warning print out to the old customisation functions as well, in case users use their old configuration files.  I could split that off into a separate PR if you prefer.

@davidlange6, @mulhearn

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by mark-grimes** [comment]
I've just added a check of CMSSW_7_6_X_2015-09-24-1100 plus this PR to the link above.  I.e.

http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-09-24-1100-PR11466.html
http://grimes.web.cern.ch/grimes/eraProcessDiffs/fileDumpDiffs-7_6_X_2015-09-24-1100-PR11466.txt

I should have pointed out that the main file is the `processDiffs-*` file which explains most.  These always list an "unexpected difference" for outputCommands because it's generally quite difficult to tell if two different outputCommands are functionally the same (in this case the statements are just in a different order).  To check these are the same I run the steps showing a difference and do a diff of the `edmDumpEventContent` result.  This is the other `fileDumpDiffs-*` file.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test
not sure why this times out - it works ok for me

@mark-grimes - I did see an error with workflow 135.4

#6  0x00007fa10bdd058a in EmDQM::analyze(edm::Event const&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-27-110
0/lib/slc6_amd64_gcc493/pluginHLTriggerOfflineEgamma.so
#7  0x00007fa1548d7d61 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /afs/ce
rn.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-27-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#8  0x00007fa1548cb64f in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/s
w/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-27-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so

**Comment by smuzaffar** [comment]
@davidlange6 , looks like the workflow  135.4 failed but did not exit that is why jenkins job killed it after 2 hours.

**Comment by davidlange6** [comment]
hum - can you reproduce that? I can not, but maybe some different behavior in the debugger on the jenkins nodes?

**Comment by smuzaffar** [comment]
I tried but also were not able to reproduce it

**Comment by davidlange6** [comment]
Ok - in any case, I need @mark-grimes to look into the error (which is reproducible..)

**Comment by mark-grimes** [comment]
Yep, checking now.

**Comment by smuzaffar** [comment]
Last PR test finished without timeout because I have killed the hanging 135.4 workflow (after 1.5 hours) so that rest of the PR testing can go normally.

**Comment by mark-grimes** [comment]
The crash is in `HLTriggerOffline/Egamma/src/EmDQM.cc` but this is because of invalid input.  Long story short, `process.l1extraParticles` is not configured correctly.  Looks like a fairly innocuous looking change I made on my checking code a while back stopped it flagging differences in InputTags, which is a pretty important thing to miss.  Currently assessing the damage but eras will need at least one more pull request before switching workflows over.

Closing until then...

**Comment by mark-grimes** [comment]
This isn't as bad as I thought, after a full fixed check only one FastSim parameter is wrong (process.l1extraParticles which caused the crash).  I've submitted #11583, once that is merged this PR can be reopened as-is.

Full check (without #11583) is at http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-09-29-1100-PR11466.html.  PR #11583 will fix the difference in `l1extraParticles`, I'm pretty sure for misalignedCSCGeometry.useGangedStripsInME1a the value in the eras are correct and wrong in the customisations.

**Comment by mark-grimes** [comment]
Reopening because #11583 has been merged which should fix the test crash.  Latest check of differences is at

http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-10-05-1838-PR11466.html

There are currently 4 differences marked as "unknown" in that file.  2 of which are in `outputCommands`, which is fine because the commands are just in different orders.  I'm about to post a diff of the output file contents proving this.  The other 2 differences are:

* `misalignedCSCGeometry.useGangedStripsInME1a` - I'm pretty sure this is correct in the era (False), and incorrect in the customisation (True).
* `muonDetIdAssociator.includeBadChambers` - was updated in #11248.  I need to submit another pull request to make this change also in the era, but it should not stop this PR being tested.  I'll note the PR number here when it's submitted.

**Comment by slava77** [comment]
``` misalignedCSCGeometry ``` appears to be present  only in the fastsim workflow.
@ianna and @lveldere could you please comment on how/why it is specific to fastsim?

**Comment by lveldere** [comment]
I cannot answer you straight away.
The muon system geometry is a corner of FastSim I haven't really visited
yet.

Here is what I know,
perhaps it helps:

The geometries used in the simulation are defined here
http://cmslxr.fnal.gov/lxr/source/FastSimulation/Configuration/python/Geometries_cff.py?v=CMSSW_7_6_X_2015-10-04-2300

Then they are used in fast simulation in the MuonSimHitProducer.
http://cmslxr.fnal.gov/lxr/source/FastSimulation/MuonSimHitProducer/src/MuonSimHitProducer.cc?v=CMSSW_7_6_X_2015-10-04-2300#0119
Here a muon system alignment needs to be used that is equivalent to the
alignment in FullSim,
and is not necessarily the alignment used in reconstruction.

**Comment by mark-grimes** [comment]
`muonDetIdAssociator` is pulled in from `HLTrigger.Configuration.HLT_25ns14e33_v3_cff` and `HLTrigger.Configuration.HLT_FULL_cff`.  These are auto generated right?  Where do these files take the configuration from?

**Comment by mark-grimes** [comment]
PR #11654 has been submitted to fix the `muonDetIdAssociator.includeBadChambers` divergence.  Ignore my comment above about the auto-generated HLT configs, the divergence is only in the reco step.

**Comment by mark-grimes** [comment]
With #11654 merged, updated diff is at http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-10-07-1710-PR11466.html.  Testing this should now give identical results, bar the `misalignedCSCGeometry` and `simCscTriggerPrimitiveDigis` differences where the era is more up to date than the customisation.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
tests all look good to me!
Thanks @mark-grimes

**Comment by mark-grimes** [comment]
As far as I can see the AddOn failures are all because of `FormulaEvaluatorParseError` exceptions, which is the consequence of another PR (right?).  In principle I suppose the AddOn tests should also be changed to use eras instead of the customisation functions, but I have no idea where to change this.

**Comment by Martin-Grunewald** [comment]
```FormulaEvaluatorParseError``` errors are fixed by #11684.
The addOn tests are defined in https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/Utilities/ReleaseScripts/scripts/addOnTests.py

**Comment by slava77** [comment]
@mark-grimes do the run2 data matrix run OK?
e.g 134.702  (50ns) and 134.802 (25ns)

**Comment by mark-grimes** [comment]
Just opened #11690 to change over the AddOn tests.
@slava77 I haven't tried before, running now.

**Comment by mark-grimes** [comment]
@slava77 both workflows fail with and without this PR (details on link below).  When running with `--no_exec` and examining the config files I get http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-10-07-2300-PR11466.html

This shows some differences but I don't *think* these matter.  Could do with expert confirmation though.

**Comment by slava77** [comment]
On 10/8/15 9:54 AM, Mark Grimes wrote:
> @slava77 <https://github.com/slava77> both workflows fail with and
> without this PR (details on link below). When running with |--no_exec|
> and examining the config files I get
> http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-10-07-2300-PR11466.html
> 
> This shows some differences but I don't /think/ these matter. Could do
> with expert confirmation though.

Mark,

134.702 should run on top of #11684 .
However, I was mostly interested in the parsed config analysis.
The notes/comments suggest it looks OK.

**Comment by hengne** [comment]
@mark-grimes @davidlange6 I will send the regular RelVal update PR with this change applied.

**Comment by mark-grimes** [comment]
Note I've submitted #11707 which makes a fix to the L1 step.  This wasn't noticed for these checks because L1 was always run with L1Reco, which has the correct includes.

**Pull request merged**
