### PR TITLE
Run-3 CLCT and LCT data formats (CCLUT-3)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This pull requests implements the CLCT and LCT data formats for Run-3 data taking. The Run-3 CSC local trigger will be notably different than then Run-1/2 trigger. CSC stubs will have a higher resolution in position (x2 to x4) and bending (x3). This is achieved by implementing a 12-bit comparator code data word (CCLUT algorithm). It is set by default to -1 for Run-1/2 CLCTs. For Run-3 it takes a value between 0 and 2^12 - 1. The halfstrip number of CLCT and LCT is given 2 extra bits, one for the 1/4 strip value and one for the 1/8 strip value. In addition, I added a new `ComparatorContainer` object to keep track of which comparators were used to build a CLCT. 

This PR is a follow-up of https://github.com/cms-sw/cmssw/pull/28846. But the code is written such that the original functions retain their original meaning for the default arguments. The actual CCLUT algorithm will be implemented in a separate PR.

More information can be found here: 
https://indico.cern.ch/event/881406/contributions/3713334/attachments/1973349/3283422/CSC_NewPatterns_SD_20200121.pdf

#### PR validation:

Tested with WF 22034.0.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@barvic @tahuang1991 @ptcox

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 23234.1001, 23434.1001

**Comment by silviodonato** [comment]
+1

**Pull request merged**
