### PR TITLE
Removal of unused DT DQM Online plots and LS label fixing

### PR DESCRIPTION
**Pull request by jfernan2**
- Remove unused folder  04-LocalTrigger-DDU in Online DQM
- Fix and remove no longer valid plots on  DT / FEDIntegrity_EvF in Online DQM
- Fix LS labels in AverageEventLenght plots vs LS in Online DQM

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of #23298

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
pleaee test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
________________________________________

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by fabiocos** [comment]
+1

validated in CMSSW_10_2_0_pre5

**Pull request merged**
