### PR TITLE
migrate modules used by the HLT menu to multithreading (Reco) (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
backport #10954 to 75x

### CODE REVIEW

**Comment by fwyzard** [comment]
tracked at #10965

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10966	89e4f38
- this is the same topic branch as in #10954 
- jenkins tests are OK, showing no diffs in outputs as expected

**Comment by davidlange6** [comment]
+1

**Pull request merged**
