### PR TITLE
Get rid of remaining tracker / tracking deprecation warnings in reco area

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, getting rid of one more deprecation warning in several tracker and tracking related subsystems, thanks to the new flagging from core s/w group (see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cfc78f/23964/build-logs/)
Technical, part of the migrations in https://github.com/cms-sw/cmssw/issues/36404.
Profited to clean-up headers, use range-based loop and merging plugin header with implementation.

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type tracking

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
> --> test test-das-selected-lumis had ERRORS

This looks unrelated.

**Comment by mmusich** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- technical code cleanup (mostly in /test/ that seems not to be run by default, even in the unit tests)
- no changes

**Comment by makortel** [comment]
Thanks @mmusich!

**Pull request merged**
