### PR TITLE
New pulse shape for HE 2017 SiPM

### PR DESCRIPTION
**Pull request by kpedro88**
This PR adds a new reco pulse shape for the HE SiPMs to be installed in 2017 (needed for Method 2 reconstruction). This pulse shape is computed using a numerical convolution of the simulated SiPM pulse shape and the Y11 wavelength shifting fiber pulse shape. For more details, see this recent presentation in the HCAL Phase 1 Software Task Force Meeting: https://indico.cern.ch/event/559519/contributions/2257748/attachments/1317836/1974957/sipm_pulse_shape_reco_MC.pdf.

Other changes in this PR:
- minor cleanup of the pulse-shape-related code
- mcShape and recoShape numbers are now configurable via Python in HcalHardcodeCalibrations

attn: @abdoulline, @mariadalfonso

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@kpedro88 , are you sure here there is no double counting of a pedestal?
value [i] = value0 + (float)CLHEP::RandGauss::shoot (value0, width.getWidth (i) / 100.);

**Comment by abdoulline** [comment]
I think it's a good catch, Vladimir... Originally (back in SLHC) that 
was kind of OK without the first value0 term.
It obviously doesn't make any noticeable difference at the end (as pedestal 
is added in DIGI, then subtracted in RECO) but better be fixed, I presume.

**Comment by kpedro88** [comment]
@cmsbuild please test

@civanch good catch, thanks

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@mmusich @cerminar @franzoni ping

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
