### PR TITLE
Convert ObjectViewCleaner from legacy producer to stream producer

### PR DESCRIPTION
**Pull request by knoepfel**
Significant changes were implemented during the conversion:

1. In the legacy version, a C-style array of Booleans was used in the determination of whether to consider a candidate "clean".  The array was necessary because of a set of nested loops that were inverted with respect to the natural logic of the module.  I removed the C-style array and placed the "candidates" loop on the outside, so that a simple `if (shouldKeep(candidate)...)` statement could be used to determine if a candidate is clean.

2. In one of the inner loops, the Boolean variable was being set to `false`, indicating that the candidate should not be considered clean.  However, instead of moving on to the next candidate, the loop continued until the entire container was traversed.  Since the `false` flag could never be turned back to `true`, this approach was inefficient.  I replaced that implementation with a function call where, if the candidate overlaps with a (e.g.) jet, instead of setting a flag, the function just returns `false`.

I would appreciate it if the maintainers can check the changes in logic.  I do not believe I have introduced errors, but that statement is based on just testing `runTheMatrix.py -l 9.0`, which may be insufficient.

### CODE REVIEW

**Comment by knoepfel** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by knoepfel** [comment]
Can this PR be merged, or are there any concerns?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
