### PR TITLE
initial support for Eras in the HLT configuration

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
```python
import FWCore.ParameterSet.Config as cms
from Configuration.StandardSequences.Eras import eras

process = cms.Process( "HLT", eras.Run2_2017 )
process.load( 'HLTrigger.Configuration.HLT_GRun_cff' )
```

gives the same python configuration as

```python
process = cms.Process( "HLT" )
process.load( 'HLTrigger.Configuration.HLT_GRun_cff' )

from HLTrigger.Configuration.customizeHLTTrackingForPhaseI2017 import customizeHLTPhaseIPixelGeom
process = customizeHLTPhaseIPixelGeom(process)

from HLTrigger.Configuration.customizeHLTTrackingForPhaseI2017 import customizeHLTForPFTrackingPhaseI2017
process = customizeHLTForPFTrackingPhaseI2017(process)
```

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by davidlange6** [comment]
Hi @fwyzard - could you make a 90x pr for this - seems like we should go in this direction (eventually the new fad of looping over all modules in the configuration is going to frustrate users waiting for our jobs to start, but thats a separate issue..)

**Comment by fwyzard** [comment]
Will do.

I'd like to hear from @Martin-Grunewald and @silviodonato if they prefer this approach (one `modify...` function per module), or the one in #16978 (few large customisation functions).

Probably something in between would be better, to avoid that each function needs to check that the new modules exist (e.g. see  [here](https://github.com/cms-sw/cmssw/blob/ea4005a12de85975bb7533b0aa50ae4241483f55/HLTrigger/Configuration/python/customizeHLTTrackingForPhaseI2017.py#L119) ).

Either way, the loops will be faster than with an old-style customisation function, because they will be applied only to the HLT fragment instead of the whole process.

**Comment by silviodonato** [comment]
Just to keep track, this PR is #17041 but in 81X.

**Comment by fwyzard** [comment]
?

#17041 is for 90x.

**Comment by silviodonato** [comment]
I wanted to say: this PR (#16977) is a 81X backport of  #17041

**Comment by fwyzard** [comment]
updated to be a backport of #17042

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
does any of the jenkins test exercise the Run2_2017 era ?

**Comment by makortel** [comment]
@fwyzard 
> does any of the jenkins test exercise the Run2_2017 era ?

Workflows 10021.0 and 10024.0 do.

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
I got different HLT results before and after #16977. The reason was that the current release does not include #16868. Indeed, I got the same HLT results using #16868 as reference (#16977 includes #16868).

**Comment by fwyzard** [comment]
replaced by #16978

**Pull request closed without merging**
