### PR TITLE
Initialize theModMEs.ClusterGain

### PR DESCRIPTION
**Pull request by davidlt**
This showed up in AArch64 GCC 5.3.0 and 7.0.1 builds.

Signed-off-by: David Abdurachmanov <davidlt@cern.ch>

### CODE REVIEW

**Comment by davidlt** [comment]
please test

**Comment by davidlt** [comment]
please abort test

**Comment by davidlt** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
