### PR TITLE
modernize configuration of SiPixelGainCalibration DB manipulation code and add unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In response of https://github.com/cms-sw/cmssw/pull/39012#issuecomment-1225713019.
Modernized the configuration of several configuration files in `CondTools/SiPixel` and added them as test units.
Profited to add `fillDescriptions` methods for modules that were lacking it.

#### PR validation:

Relies on the successful running of the test units:

```console
scram b runtests_SiPixelGainCalibrationTests
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+db
 * newly introduced unit test succeed
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ec545c/27094/unitTests/src/CondTools/SiPixel/test/SiPixelGainCalibrationTests/testing.log
 * tests pass

**Comment by perrotta** [comment]
+1

**Pull request merged**
