### PR TITLE
Run3-gex175X Backport #43876 to CMSSW version 14_0_X the changes for te 2024 version of GE21 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #43876 to CMSSW version 14_0_X the changes for te 2024 version of GE21 geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backporting #43876 from the master which is already integrated

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by antoniovilela** [comment]
hold
   - While this is further discussed.

**Comment by antoniovilela** [comment]
> @antoniovilela , there is no sense to hold this PR, because it is done only in order of consistency between GT and XML detector description. In production GT is used but if at any moment in time a test GT/XML will be needed for any reason there will be a confusion. It is why we are trying to backport XML modifications like this. Here extra chambers installed during YETS are added to geometry, this chambers will not be used for analysis of data but only to control their performance.

We have asked and are waiting for a green light from PPD, this is why it is on hold.
Thanks.

**Comment by antoniovilela** [comment]
unhold

**Comment by antoniovilela** [comment]
We can discuss this PR in the ORP meeting.

**Comment by jordan-martins** [comment]
+1

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please merge this. I need to use the IB to backport the next version (scenario definition)

**Comment by rappoccio** [comment]
+1

**Pull request merged**
