### PR TITLE
Fix extend_argparse location in HLTrigger (110X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix extend_argparse location in HLTrigger (110X)
Based on CMSSW_11_0_X_2019-11-25-1100
(This fixes the failing HLT-Validation tests)

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
