### PR TITLE
remove SET muons

### PR DESCRIPTION
**Pull request by fcavallo**
so this is the PR for DT in 81x (same as 15015 for 80x)

### CODE REVIEW

**Comment by dmitrijus** [comment]
Hi,  you have to resolve the branch conflict.

**Comment by fcavallo** [comment]
I have no idea where this conflict comes from! I started from a clean area in CMSSW81x, and just changed the 2 lines that you see, in 1 configuration file! (the muon collection to be used and the minimum number of requested hits). Unless you give me a hint of what can be wrong I'm afraid I'm stuck, And our (DT) efficiency plots will not be filled when SET muons disappear!

**Comment by davidlt** [comment]
This was merged: https://github.com/cms-sw/cmssw/commit/8c3b9286eccf66b6c8be16054ec3d727863a36b8#diff-d9361d502ba44e0e911b51820cdee69d

Where `TrackCollection` was changed. Basically you only need to change a single line now.

**Comment by fcavallo** [comment]
thank you  davidlt. So in the end all my problems were due to bad timing with other PRs!!?
Still another one: #15177. Hope this is the good and  final! ;-)

**Comment by davidlange6** [comment]
seems that this PR is now obsolete.

**Pull request closed without merging**
