### PR TITLE
RUn3-gem32 Convert DDGEMAngular to DD4Hep format

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to convert DDGEMAngular to DD4Hep 

#### PR validation:

To be tested

#### if this PR is a backport please specify the original PR:

Not to be back ported

### CODE REVIEW

**Comment by ianna** [comment]
@slomeo - FYI

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

tested privately, it works as expected.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
