### PR TITLE
GT Updates: Run1 JEC and MVA Selectors as Tracking MVA Selectors update

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI simulation

   * **RunI Heavy Ions scenario** : [94X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_HeavyIon_v0) as [93X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_HeavyIon_v0/93X_mcRun1_HeavyIon_v0):
      * Run1 Jet Corrector

   * **RunI Ideal scenario** : [94X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_design_v0) as [93X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_design_v0/93X_mcRun1_design_v0):
      * Run1 Jet Corrector

   * **RunI Proton-Lead scenario** : [94X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_pA_v0) as [93X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_pA_v0/93X_mcRun1_pA_v0):
      * Run1 Jet Corrector

   * **RunI Realistic scenario** : [94X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_realistic_v0) as [93X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_realistic_v0/93X_mcRun1_realistic_v0):
      * Run1 Jet Corrector

## RunI data

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v1) as [93X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v1/93X_dataRun2_HLT_frozen_v0):
      * MVA Selector

   * **RunI Offline processing** : [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) as [93X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v0/93X_dataRun2_v0):
      * MVA Selector

## RunII data

   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v1) as [93X_dataRun2_HLTHI_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLTHI_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v1/93X_dataRun2_HLTHI_frozen_v0):
      * MVA Selector

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v1) as [93X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v1/93X_dataRun2_HLT_relval_v1):
      * MVA Selector

   * **RunII Offline processing** : [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) as [93X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v0/93X_dataRun2_v0):
      * MVA Selector

   * **RunII PromptLike processing** : [94X_dataRun2_PromptLike_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v0) as [93X_dataRun2_PromptLike_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_PromptLike_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v0/93X_dataRun2_PromptLike_v0):
      * MVA Selector

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v0) as [93X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v0/93X_dataRun2_relval_v0):
      * MVA Selector

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v1) as [93X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v1/93X_dataRun2_HLT_frozen_v0):
      * MVA Selector

## Upgrade

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v0) as [93X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v0/93X_upgrade2018_design_IdealBS_v2):
      * MVA Selector

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v0) as [93X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v0/93X_upgrade2018_realistic_v2):
      * MVA Selector

## 2017_MC

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v0) as [93X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v0/93X_mc2017_design_IdealBS_v3):
      * MVA Selector

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v0) as [93X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v0/93X_mc2017_realistic_v3):
      * MVA Selector

### CODE REVIEW

**Comment by lpernie** [comment]
# Summary of changes in Global Tags

## RunI simulation

   * **RunI Heavy Ions scenario** : [94X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_HeavyIon_v0) as [93X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_HeavyIon_v0/93X_mcRun1_HeavyIon_v0):
      * Run1 Jet Corrector

   * **RunI Ideal scenario** : [94X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_design_v0) as [93X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_design_v0/93X_mcRun1_design_v0):
      * Run1 Jet Corrector

   * **RunI Proton-Lead scenario** : [94X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_pA_v0) as [93X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_pA_v0/93X_mcRun1_pA_v0):
      * Run1 Jet Corrector

   * **RunI Realistic scenario** : [94X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_realistic_v0) as [93X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun1_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_realistic_v0/93X_mcRun1_realistic_v0):
      * Run1 Jet Corrector

## RunI data

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v1) as [93X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v1/93X_dataRun2_HLT_frozen_v0):
      * MVA Selector

   * **RunI Offline processing** : [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) as [93X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v0/93X_dataRun2_v0):
      * MVA Selector

## RunII data

   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v1) as [93X_dataRun2_HLTHI_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLTHI_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v1/93X_dataRun2_HLTHI_frozen_v0):
      * MVA Selector

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v1) as [93X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v1/93X_dataRun2_HLT_relval_v1):
      * MVA Selector

   * **RunII Offline processing** : [94X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v0) as [93X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v0/93X_dataRun2_v0):
      * MVA Selector

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v0) as [93X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v0/93X_dataRun2_relval_v0):
      * MVA Selector

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v1) as [93X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_dataRun2_HLT_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v1/93X_dataRun2_HLT_frozen_v0):
      * MVA Selector

## Upgrade

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v0) as [93X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v0/93X_upgrade2018_design_IdealBS_v2):
      * MVA Selector

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v0) as [93X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v0/93X_upgrade2018_realistic_v2):
      * MVA Selector

## 2017_MC

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v0) as [93X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v0/93X_mc2017_design_IdealBS_v3):
      * MVA Selector

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v0) as [93X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v0/93X_mc2017_realistic_v3):
      * MVA Selector

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
The failure of step3 in wf8.0 points to the absence of MINIAODSIMEventContent. 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20568/23047/runTheMatrix-results/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/step3_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS.log
This seems to be related to this change of workflow.
@fabozzi may be you want to have a look? May be output of step2 needs to be changed so that this information can be kept.

**Comment by arunhep** [comment]
@lpernie please change the title of this PR. I think we should always start with "GT Updates" and we should specify MVA Selectors as Tracking MVA Selectors update.

**Comment by lpernie** [comment]
please test

**Comment by makortel** [comment]
FYI @slava77 @perrotta 
This GT update contains the retrained track selection MVA parameters (discussed in Sep 9 RECO meeting 
https://indico.cern.ch/event/663391/contributions/2708723/attachments/1520406/2374865/slides_reco_20170908.pdf
and requested here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3229.html).

There will be a subsequent PR to enable the phase1-trained selector for pixelPairStep, and to tune the cuts on the MVA in lowPt* iterations.

FYI also @VinInn @hajohajo

**Comment by slava77** [comment]
@makortel 
[perhaps this is an unfair comparison, but still]

In jenkins 2017 data wf 136.788 there is a fairly large change in track variables

all_oldvsnew_runsingleph2017b136p788c_log10recotracks_generaltracks__rereco_obj_pt

all_oldvsnew_runsingleph2017b136p788c_recotracks_generaltracks__rereco_obj_algo


Compared to that, in MC in ttbar wf 10024 the changes are very small
all_oldvsnew_ttbar13tev2017wf10024p0c_log10recotracks_generaltracks__reco_obj_pt

all_oldvsnew_ttbar13tev2017wf10024p0c_recotracks_generaltracks__reco_obj_algo

At PF level changes in data are pretty small 
all_oldvsnew_runsingleph2017b136p788c_log10recopfcandidates_particleflow__rereco_obj_pt46
So, most of the difference is probably from non-high-purity tracks.

Is it clear that in data we are mostly losing fakes and that the MVA training is well appropriate for data?

**Comment by slava77** [comment]
nhit distributions are suggestive that the drop in data is almost exclusively from 3-layer pixel-only tracks
wf136 788_gentracks_nlaystrip
wf136 788_gentracks_npixhit

wf136 788_gentracks_stopreason

combined with the algo plot, it all looks like lowPtTriplet and detachedTriplet MVAs now effectively require that there is a strip hit.

@makortel 
is this expected and safe for data?

**Comment by makortel** [comment]
@slava77 The decrease in generalTracks vs. pT is in the region where we see a decrease in efficiency also in MC (ttbar+PU35/50) when updating the training only. Especially for lowPtTripletStep the MVA distributions for true/fake tracks are so different that it is necessary to tune the cuts in order to restore the efficiency at low pT.

(MTV plots and comparison with data are in the making, I could also submit the PR later today so that it can be reviewed and tested with the GT update of this PR)

**Comment by slava77** [comment]
On 9/20/17 5:06 AM, Matti Kortelainen wrote:
> @slava77 <https://github.com/slava77> The decrease in generalTracks vs.
> pT is in the region where we see a decrease in efficiency also in MC
> (ttbar+PU35/50) when updating the training only. Especially for
> lowPtTripletStep the MVA distributions for true/fake tracks are so
> different that it is necessary to tune the cuts in order to restore the
> efficiency at low pT.
> 
> (MTV plots and comparison with data are in the making, I could also
> submit the PR later today so that it can be reviewed and tested with the
> GT update of this PR)

I guess this means that my comparison with the no-PU MC plots is unfair
and there is a visible effect in MC with PU in line with the one I
posted for data plots.
I remember the lowPt note from the RECO meeting.
The algo plot in data shows a drop in the detachedTriplet similar in
size to that in the lowPt iteration.
Is this also affected in MC, is it only at low pt (<0.7-0.8) or does it
extend to higher values?

**Comment by makortel** [comment]
@slava77 In detachedTripletStep MC shows only decrease in fakes for pT > 200 MeV
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_3_0_pre5_PR20568/phase1_ttbar_pu35_ByOriginalAlgo_detachedTripletStep/effandfakePtEtaPhi.pdf

Now I also submitted the PR with the tuned cuts (#20607) with the link to MTV plots (separating this PR of updating the training and #20607 updating the cuts).

(data comparison is still in the works)

**Comment by slava77** [comment]
On 9/20/17 7:38 AM, Matti Kortelainen wrote:
> @slava77 <https://github.com/slava77> In detachedTripletStep MC shows
> only decrease in fakes for pT > 200 MeV
> https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_3_0_pre5_PR20568/phase1_ttbar_pu35_ByOriginalAlgo_detachedTripletStep/effandfakePtEtaPhi.pdf
> 
> Now I also submitted the PR with the tuned cuts (#20607
> <https://github.com/cms-sw/cmssw/pull/20607>) with the link to MTV plots
> (separating this PR of updating the training and #20607
> <https://github.com/cms-sw/cmssw/pull/20607> updating the cuts).
> 
> (data comparison is still in the works)
> 

Thanks.
The detachedTripletStep/effandfakePtEtaPhi.pdf shows a 20% drop in
fakes and some increase in eff.
Good.

"+1"

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
hi @lpernie - looks like this PR causes a number of problems in the integration builds 

Exception Message:
 HLTHighLevel [instance: ALCARECOEcalESAlignHLT - path: pathALCARECOEcalESAlign]: No triggerList with key EcalESAlign in AlCaRecoTriggerBitsRcd

can you have a look and provide a quick fix. Thanks

**Comment by arunhep** [comment]
@davidlange6 the problem has been understood. we are in process of providing a new PR with GT updates. should be there in an hour or so.

**Comment by arunhep** [comment]
@davidlange6 #20622 should fix the problem.

**Comment by mrodozov** [comment]
Dears, we were after 4 relval fails namely https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc630;CMSSW_9_4_X_2017-09-24-2300 those 4000* failing with 
"number of event content arguments does not match number of datatier arguments"
because after the changes you did in the step3 defaults here https://github.com/cms-sw/cmssw/pull/20568/files#diff-819af2ec677272fddf1fef50e788a88bR1331 
those workflows are picking the option for --eventcontent from here 
https://github.com/cms-sw/cmssw/pull/20568/files#diff-819af2ec677272fddf1fef50e788a88bR1465
and here 
https://github.com/cms-sw/cmssw/pull/20568/files#diff-819af2ec677272fddf1fef50e788a88bR1535
hence the mismatch. Would you please provide the default --eventcontent option for those two (I can see it's MINIAODSIM yet i don't want to touch it over assumptions) so that we might have those wf's back. @davidlange6 @lpernie

**Comment by arunhep** [comment]
FYI @fabozzi

**Comment by fabozzi** [comment]
Hi, yes MINIAODSIM has to be added.
Can you integrate this commit in the PR to fix?

https://github.com/fabozzi/cmssw/commit/dfc3b6b86cfe4a5316f427729a90d4d6c9b51877

**Pull request merged**
