### PR TITLE
Phase2-hgx282 Prepare a simple example to test extruded polygon implementation in dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Prepare a simple example to test extruded polygon implementation in dd4hep

#### PR validation:

Prepared 2 test scripts which work with identical scenarios with ddd (works) and dd4hep (creates a G4 structure which shows wild overlaps)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
