### PR TITLE
Phase2-TB73 Update the cfg files for the old TB runs of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the cfg files for the old TB runs of HGCal

#### PR validation:

Tested together with the changes made in a forthcoming PR

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

regression problem due to MkFit, not relevant to this PR

**Comment by srimanob** [comment]
+Upgrade

Change in testbeam config, not effect to any main workflows.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
