### PR TITLE
Legacy 50ns frozen HLT menu in the release 74X

### PR DESCRIPTION
**Pull request by perrotta**
Replace the frozen version version of the 50ns HLT menu in the release: instead of the latest and greatest menu that we had included before (but at the end never used because of the problem with the solenoid) another version was chosen which is more similar to the one applied mostly during the data taking at 50ns.

It has to be merged on top of #9878: once that PR will get merged, this one will only need the HLT signature The menus used for RelVal or MC productions are not touched, even for the 50ns menu. The new frozen menu will simply stay in the release, and can be used for possible MC productions that want to compare with the 50ns data.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test 
(in hopes of getting a comparison)

**Comment by davidlange6** [comment]
@perrotta - seems the L1 changes in this PR (from the comparisons). could you investigate and fix.

**Comment by perrotta** [comment]
@davidlange6 : the L1 updates are from #9878, which is included here,
This pull request is #9878 plus c32115a98193a7408d33352011a6398994dc1a70 , and that extra commit does not have any L1 related change.

By the way, I profit for the following request: TSG was requesting right now to modify the HLT menu used for the 50ns relval into the new frozen one added by this PR: would it be possible?
It would only require modifying line 8 in Configuration/HLT/python/autoHLT.py , and if you give me the green light, I can either modify this PR, or prepare a new one with it. Just let me know.

Thank you,
Andrea

**Comment by Martin-Grunewald** [comment]
@davidlange6
The only L1 change is the removal of the xml file loading in the PostLS1 customisation.
So I can not understand why L1 would have changed at all - I suppose you compared
to 74X already using the new GTs? Then maybe a different L1 menu is in the GT than
was in the xml file? What L1 meny has changed? The 50ns L1, or the 25ns L1?

**Comment by davidlange6** [comment]
“I” (aka cmsbot) look at 74x with and without this PR.

It looks like there are no L1 changes in 25ns (but there are hlt changes) and there are L1 (maybe HLT too) in 50ns.

but just have a look at the comparison results..

**Comment by Martin-Grunewald** [comment]
The HLT changes are actual bug fixes (at least for the frozen "v1" menus). The development HLT menus are of course different. So such changes are expected. For L1, what plots are you referring to?

**Comment by davidlange6** [comment]
I don’t want changes to menus…sorry.

**Comment by Martin-Grunewald** [comment]
This is getting on my nerves! You do accept fixes all the time. What is the matter here?
If that goes on I'll ask TSG for an online release! I am fed up with having to wait weeks and weeks
for integration and then still rejected in the end. Online we can not work like this, with these types of delays. Yes, you do not want online release, but then you do have to accommodate TSG in the
main release series.

**Comment by davidlange6** [comment]
what fixes that affect physics of the MC production have I accepted?

**Comment by Martin-Grunewald** [comment]
We only agreed to keep the v1 frozen menus unchanged, not the development menus or
later frozen menus (v2, v3, ..) The v1 menus are used in the 74X MC production.
The changes to the frozen v1 menus in this PR are solely due to the "const_cast"
bug fix accepted into 74X earlier. So there is no way out to accept this change to
the v1 menus, short of reverting the 'const_cats' bug fix.

**Comment by davidlange6** [comment]
Right - we are only comparing the v1 frozen menus. (though ok, we can discuss the point of other frozen menus that unfreeze:) ) - I guess I need to go back and understand what changes came in from the const_cast fix.

**Comment by Martin-Grunewald** [comment]
For now v2,v3 are TSG internal checkpoint menus. If at one stage you/we/CMS want menus
for some new MC production, more recent than the v1 menus, we'll select and then "deep freeze" some v2 or v3 menu and really keep it fixed - such as the 50ns v3 menu corresponding to
the menu used to collect most lumi with magnet on, or the incomming 25ns menu...

**Comment by davidlange6** [comment]
so it seems we are stuck with having this inconsistently given the previous change. So we just need to clarify the L1 changes. @mulhearn

**Comment by mulhearn** [comment]
I double checked the 25 ns and 50 ns menu's and confirmed that they are the same in the GT PR and in the (now unused customizations) for 74X.  So a bit stumped...

**Comment by mulhearn** [comment]
Just to confirm:  the problematic comparison is from work flow 50202.0?  (I can't see what is different for L1 from looking at code and so I am running both versions side by side...  might take a little while.)

**Comment by fwyzard** [comment]
On 31 July 2015 at 10:31, Martin Grunewald <notifications@github.com> wrote:

> [...] for some new MC production, more recent than the v1 menus, we'll
> select and then "deep freeze" some v2 or v3 menu and really keep it fixed -
> such as the 50ns v3 menu corresponding to the menu used to collect most
> lumi with magnet on, or the incomming 25ns menu...
>

I though we (TSG) had already decided to freeze the 50ns v3.0 menu - while
keeping the v1 around for compatibility with the MC production.

I'm out of touch for what concerns a new 25ns menu.

.A

**Comment by mulhearn** [comment]
Ah, crap, its my fault.  The 50 ns config is calling stage1... I can fix...

**Pull request merged**
