### PR TITLE
Handle empty branch index lists from input

### LINKED ISSUE #43713: InvalidReference in FEVTDEBUGoutput_step: Ref has invalid (zero) product ID
Starting with CMSSW_14_0_X_2024-01-12-2300, RelVals [1370.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-12-2300/pyRelValMatrixLogs/run/1370.0_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13/step2_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13.log#/7527-7527), [1370.17](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-12-2300/pyRelValMatrixLogs/run/1370.17_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17/step2_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17.log#/8702-8702), [1370.18](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-12-2300/pyRelValMatrixLogs/run/1370.18_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP18/step2_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP18.log#/7453-7453), [25215.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-12-2300/pyRelValMatrixLogs/run/25215.0_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13/step2_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13.log#/7967-7967), [21215.17](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-12-2300/pyRelValMatrixLogs/run/25215.17_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17/step2_GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17.log#/9087-9087) are failing with `InvalidReference` exception:

```
----- Begin Fatal Exception 13-Jan-2024 04:11:52 CET-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 3
   [1] Running path 'FEVTDEBUGoutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGoutput'
   [3] Prefetching for module FastjetJetProducer/'ak4GenJets'
   [4] Prefetching for module InputGenJetsParticleSelector/'genParticlesForJets'
   [5] Calling method for module GenParticleProducer/'genParticles'
Exception Message:
Inconsistency RefCore::pushBackRefItem: Ref has invalid (zero) product ID, so it cannot be added to RefVector.id should be (0:0)
----- End Fatal Exception -------------------------------------------------
```

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Fixes a bug where an empty branch index list from the Source would cause the branch index list to not be updated at all.

#### PR validation:
New unit test passes and failing IB test also passes.

fixes #43713

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
The usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43293

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
