### PR TITLE
L1T CondFormats classes updates for UTM v_0.8.1 (v_0.8.0)

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:

Needed updates for L1T CondFormat classes for updated external library UMT v_0.8_1 or v_0.8.0.

#### PR validation:

Needs UTM v_0.8.1 installed (https://github.com/cms-sw/cmsdist/pull/6338)
Validated with locally updated UTM to v_0.8.1 and executing the workflow 136.793, which was previously failing.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#6338
@rekovic you can do the same for the 11_1 backport of this with https://github.com/cms-sw/cmsdist/pull/6340

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@christopheralanwest and @ggovi 
Can you please comment or sign. We would like this for MWGR. Thanks.

**Comment by qliphy** [comment]
urgent 
for next MWGR

**Comment by yuanchao** [comment]
+1
* with c++11 destructor
* better naming on variables

**Comment by silviodonato** [comment]
@ggovi do you have any comments?

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
