### PR TITLE
[92X] GT updates with L1T v4 menu and switch to HLTv4.0 in @relval2017 

### PR DESCRIPTION
**Pull request by arunhep**
This PR brings mainly two changes.
1. update GTs with L1T menu v4
2. switch relvals 2017 to HLT menu v4

# Summary of changes in Global Tags 
 
## RunII data 
 
   * **RunII HLT relval processing** : [92X_dataRun2_HLT_relval_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_relval_v9) as [92X_dataRun2_HLT_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_relval_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_HLT_relval_v9/92X_dataRun2_HLT_relval_v8): 
      * Update of L1T menu to V4

   * **RunII Offline relval processing** : [92X_dataRun2_relval_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_relval_v9) as [92X_dataRun2_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_relval_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_relval_v9/92X_dataRun2_relval_v8): 
      * Update of L1T menu to V4

   * **RunII Prompt processing** : [92X_dataRun2_PromptLike_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_PromptLike_v9) as [92X_dataRun2_PromptLike_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_PromptLike_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_PromptLike_v9/92X_dataRun2_PromptLike_v8): 
      * Update of L1T menu to V4

## MC 2017

   * **PhaseI 2017 cosmics peak scenario** : [92X_upgrade2017cosmics_realistic_peak_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v13) as [92X_upgrade2017cosmics_realistic_peak_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v13/92X_upgrade2017cosmics_realistic_peak_v11): 
      * Update of L1T menu to V4
      * update of L1T CaloParams

   * **PhaseI 2017 cosmics scenario** : [92X_upgrade2017cosmics_realistic_deco_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v13) as [92X_upgrade2017cosmics_realistic_deco_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v13/92X_upgrade2017cosmics_realistic_deco_v11): 
      * Update of L1T menu to V4
      * update of L1T CaloParams

   * **PhaseI 2017 design scenario** : [92X_upgrade2017_design_IdealBS_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v14) as [92X_upgrade2017_design_IdealBS_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_design_IdealBS_v14/92X_upgrade2017_design_IdealBS_v11): 
      * Update of L1T menu to V4
      * update of L1T CaloParams
      * update of ideal tracker alignment

   * **PhaseI 2017 realistic scenario** : [92X_upgrade2017_realistic_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v14) as [92X_upgrade2017_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v14/92X_upgrade2017_realistic_v11): 
      * Update of L1T menu to V4
      * update of L1T CaloParams

## Upgrade 
 
   * **PhaseII realistic scenario** : [92X_upgrade2023_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2023_realistic_v6) as [92X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2023_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2023_realistic_v6/92X_upgrade2023_realistic_v3): 
      * Update of L1T menu to V4
      * Insert L1T global prescale tag

   * **PhaseI 2018 cosmics scenario** : [92X_upgrade2018cosmics_realistic_deco_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v11) as [92X_upgrade2018cosmics_realistic_deco_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v11/92X_upgrade2018cosmics_realistic_deco_v9): 
      * Update of L1T menu to V4
      * update of L1T CaloParams

   * **PhaseI 2018 design scenario** : [92X_upgrade2018_design_IdealBS_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_design_IdealBS_v10) as [92X_upgrade2018_design_IdealBS_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_design_IdealBS_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018_design_IdealBS_v10/92X_upgrade2018_design_IdealBS_v8): 
      * Update of L1T menu to V4
      * update of L1T CaloParams
      * update of ideal tracker alignment

   * **PhaseI 2018 realistic scenario** : [92X_upgrade2018_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_realistic_v11) as [92X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_realistic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018_realistic_v11/92X_upgrade2018_realistic_v9): 
      * Update of L1T menu to V4
      * update of L1T CaloParams

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
attn @Martin-Grunewald

**Comment by Martin-Grunewald** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
