### PR TITLE
[14.0.X] Fix lostDict: Add HcalRecHitSoA for HcalRecHit package

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #45298

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = DataFormats/HcalRecHit

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , this should fix the failing lost dictionaries tests for 14.0.X

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
> @cms-sw/orp-l2 , this should fix the failing lost dictionaries tests for 14.0.X

Thanks.

**Pull request merged**
