### PR TITLE
switch to Pandora recipe with no fragment removal algorithms

### PR DESCRIPTION
**Pull request by kpedro88**
This commit adds a modified Pandora recipe with no fragment removal algorithms, and sets it as the default recipe in the python configuration. This increases the speed of Pandora in high-pileup environments with little effect on the jet resolution, see attached slides:

hgcal pandora jer nofragremoval 2
hgcal pandora jer nofragremoval 3

attn: @lgray, @vandreev11, @pfs, @boudoul

### CODE REVIEW

**Comment by mark-grimes** [comment]
Do you want this as the default for all pileup scenarios?  We could put something in the customisation that checks what pileup it is and decide which config to run.

**Comment by kpedro88** [comment]
I'm not sure what would be best at this moment.  @lgray, @vandreev11, what do you think?

**Comment by lgray** [comment]
Busy right now, back to you later tonight.

(Sent from my Nexus 6)

**Comment by vandreev11** [comment]
On my opinion it should be the same for all PU scenarios. PU0 could be a special case, but it is better to avoid that for the sake of comparisons, drawing conclusions. I believe it is temporary measure, clustering in Pandora needs to be tuned yet for high pileup case.

**Comment by lgray** [comment]
Along the same lines as Valeri, since we're going to be doing a massive
overhaul of the clustering to begin with, perhaps it is better to keep
things configured the same with the stock pandora algorithms for all PU
scenarios.

We'll likely still be using some of the linear collider algorithms even
after we've finished developing specialized clustering/ID/PF, so it's good
to keep configurations straightforward and simple.

-L

(Sent from my Nexus 6)

**Comment by mark-grimes** [comment]
merge

Okay, so that's everything for the next patch release right? Getting on a plane now, I'll put in the build request when I land.

**Comment by kpedro88** [comment]
Yes, that should be everything.

**Pull request merged**
