### PR TITLE
bsunanda:Run2-hcx46 make a fresh PR for  bsunanda:Run2-hcx41 (11767 for 7_6_X) HcalTopology depends only on HcalDDDRecContants

### PR DESCRIPTION
**Pull request by bsunanda**
Closing the PR 11767

### CODE REVIEW

**Comment by bsunanda** [comment]
Could not find conflict against CMSSW_8_0_X_2015-10-28-1100 where it merges fine.

**Comment by diguida** [comment]
@bsunanda the bot says:
This branch has conflicts that must be resolved
:-(

Rebase on the latest tip of 8.0.X branch:

````
$ cmsrel CMSSW_8_0_X_2015-10-28-1100
$ cd CMSSW_8_0_X_2015-10-28-1100/src
$ cmsenv
$ git cms-init
$ git checkout CMSSW_8_0_X
$ git pull
$ git checkout -b Run2-hcx46 my-cmssw/Run2-hcx46
$ git rebase -i CMSSW_8_0_X
# fix conflicts
$ git push my-cmssw +HEAD:Run2-hcx46
````

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1
results now are identical

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
-1
needs a rebase?
looking at the plain diff, things look reasonable
https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_8_0_X...bsunanda:Run2-hcx46

@smuzaffar @degano 
do you know what could be happening on github web side?
are the auto-merges special in some way (in this case the parent is https://github.com/cms-sw/cmssw/commit/ac102936b9c325bc7e0857067daeed9450aee9e6)

**Comment by bsunanda** [comment]
Rebasing and resolving merge conflicts always cause these huge changes. This is the second time I restarted from the beginning. The auto-merges cause these problems. Suggest a method for rebasing which avoids the accumulation of huge history
________________________________
________________________________

**Comment by slava77** [comment]
ok, I removed reco "-1"
now that it seems to be confirmed that the automerges trigger this mess.
checks (from at least reco side) will need to be done manually

**Comment by smuzaffar** [comment]
I tried to do the merge , see #12196 
@bsunanda , does that look good?

**Comment by slava77** [comment]
-1
apparently superseded by #12196 
(complain if not)

**Comment by deguio** [comment]
-1

**Comment by bsunanda** [comment]
replaced by #12196 - so close this PR

**Pull request closed without merging**
