### PR TITLE
Phase2-hgx359C Make several updates to the configuration files in Validation/HGCalValidation/test/python in view of updates of Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make several updates to the configuration files in Validation/HGCalValidation/test/python given updates of Phase2 scenarios

#### PR validation:

Tested the modified configuration files

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid  Please approve this PR

**Comment by tjavaid** [comment]
@bsunanda , do you expect a plenty of [differences e.g. ](https://tinyurl.com/2235u5wn) in `WF 29634.911` with these updates ?

**Comment by bsunanda** [comment]
These updates will not cause any difference in any workflows

**Comment by tjavaid** [comment]
+1

- The differences in `WF 29634.911` are spurious (see #42470 and #41927)

**Comment by rappoccio** [comment]
+1

**Pull request merged**
