### PR TITLE
Added a tool to list the contents of DQMIO metadata table

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

A a tool to list the contents of DQMIO metadata table.

#### PR validation:

Tool validated locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
@andrius-k the DQM difference in the test is clearly unrelated to this PR, the script runs smoothly on the output of wf 136.85 but fails on the output of 1325.7 (nanoAOD).

**Comment by andrius-k** [comment]
please test

@fabiocos Thanks for spotting this! The crash happened because I didn't take into account that ME type can be unknown. This is now fixed. And yes, the differences are clearly unrelated to this PR.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

the code has been now protected against failure in wf 1325.7

**Comment by schneiml** [comment]
@fabiocos, @andrius-k the comparison noise here is another case of #28072.

**Pull request merged**
