### PR TITLE
Use esConsumes in TTStubAssociator

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
ping @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
