### PR TITLE
DQM code for the HLT_TripleMu_5_3_3_Mass3p8to60_DCA

### PR DESCRIPTION
**Pull request by gkaratha**
Dear Experts,

This commit is the DQM code for the HLT_TripleMu_5_3_3_Mass3p8to60_DCA. No new code wis introduced. Simple replication of old code. Thanks.

### CODE REVIEW

**Comment by mtosi** [comment]
@gkaratha thanks !
please, update the title to something slightly more effective
please, quantify the increase in #bins

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by gkaratha** [comment]
Dear Mia,

Thanks for your comments! I changed the name and the number of bins that i use is ~150 for plots (not counting denominator/numerator independently). Thanks.

**Comment by mtosi** [comment]
please, quantify the total #bins
thanks

**Comment by gkaratha** [comment]
Dear Mia,

I think that the answer is ~450. (150 for numerator, 150 for denominator and 150 for efficiency). Thanks again.

Best,
George

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
@davidlange6 @dmitrijus 
can we proceed w/ the integration ?
thanks !

**Comment by davidlange6** [comment]
+1

**Pull request merged**
