### PR TITLE
Phase2 Tracker DQM: fix missing modifiers

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Fixes problem with IB reported here: https://github.com/cms-sw/cmssw/pull/28432#issuecomment-558835677

#### PR validation:

step4 of wf 20634.99 now runs.

#### if this PR is a backport please specify the original PR:

This PR is not a backport.
Cc:
@gsaha009 @sroychow

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 20634.99

**Comment by fabiocos** [comment]
@mmusich thanks!

@jfernan2 as far as I can see this PR can just affect the test wf 20634.99, as we have no other Phase2 premix tests, and that is seen to run (but we will not get any comparison for it).

**Comment by fabiocos** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
