### PR TITLE
HLT menu development for `13_0_X` (7/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #41387

#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2720](https://its.cern.ch/jira/browse/CMSHLT-2720): [TSG] seed `DQMGPUvsCPU` triggers of GRun with all L1A-Physics events
 - [CMSHLT-2733](https://its.cern.ch/jira/browse/CMSHLT-2733): [HCAL] increased HLT PSs of `IsoTrack(HB,HE)` triggers by 3
 - [CMSHLT-2736](https://its.cern.ch/jira/browse/CMSHLT-2736): [TSG] remove SCAL unpacker from Run-3 HLT menus
 - [CMSHLT-2737](https://its.cern.ch/jira/browse/CMSHLT-2737): [TSG] add `L1_SingleEG4*` seeds to single-EG Scouting trigger
 - [CMSHLT-2741](https://its.cern.ch/jira/browse/CMSHLT-2741): [ECAL] removal of `Ele36*_noEoP*` trigger
 - [CMSHLT-2746](https://its.cern.ch/jira/browse/CMSHLT-2746): [TSG] separate Scouting triggers seeded by `L1_DoubleMu` and `L1_(HTT,*Jet)`
 - [CMSHLT-2751](https://its.cern.ch/jira/browse/CMSHLT-2751): [HIG] remove MSSM-Hbb triggers using DeepCSV
 - [CMSHLT-2752](https://its.cern.ch/jira/browse/CMSHLT-2752): [TSG] updated HLT PSs of `*PFJet(140,200)` in low-lumi columns
 - [CMSHLT-2753](https://its.cern.ch/jira/browse/CMSHLT-2753): [HIG] remove `HLT_SingleJet30_Mu12_SinglePFJet40_v` trigger
 - [CMSHLT-2755](https://its.cern.ch/jira/browse/CMSHLT-2755): [TSG] added `L1_DoubleJet30er2p5_Mass_Min250_dEta_Max1p5` seed to Scouting
 - [CMSHLT-2758](https://its.cern.ch/jira/browse/CMSHLT-2758): [ECAL] remove `*LowPU` products from EventContent of ALCAP0 stream

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41387

Development of HLT menus for 2023 data-taking and Run-3 MC.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt
 - No changes in the outputs of PR tests, as expected (in this cycle, RelVals use only fake or frozen HLT menus, which are not modified by this PR).
 - DQM bin-by-bin comparisons could not be inspected because of https://github.com/cms-sw/cmssw/pull/41387#issuecomment-1519099032.

**Comment by missirol** [comment]
The parent PR tested okay in the IB `CMSSW_13_1_X_2023-04-23-2300`.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping to review this backport.

**Comment by perrotta** [comment]
+1

**Pull request merged**
