### PR TITLE
Phase2-hgx360H Change names from 2026 to Run4 in several scripts of Geometry/Hcal* and Geometry/HGCal*

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change names from 2026 to Run4 in several scripts of Geometry/Hcal* and Geometry/HGCal*

#### PR validation:

Tested by running the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@subirsarkar please approve this

**Comment by bsunanda** [comment]
@Moanwar Please approve this PR

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
