### PR TITLE
Fix geometry ordering for Phase2 Pixel

### PR DESCRIPTION
**Pull request by ebrondol**
After this fix on the order in the Forward Pixel GeometrySearch, the number of duplicates is reduced of more than a factor 10. Fakerate and efficiency are almost unchanged.
Here the result using the release CMSSW_9_0_X_2017-01-08-2300 with a sample of 1000 events of TTbar (WF#21234.1):
dupfix
This PR is considered to be quite important for future Phase2 developments and it would be great to have it in the next pre-release (from the [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/ReleaseSchedule) is not possible yet to see the developments for 90X).

Informing @delaere @atricomi @boudoul

### CODE REVIEW

**Comment by ebrondol** [comment]
I have also taken the opportunity of setting some lines of degubbing here and there that I usually need.

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17144	366fe50
- fix is as described; apparently significantly reducing the number of track splits
- jenkins tests pass and comparisons with baseline show changes only in 2023 workflows as expected (starting from tracking and propagating downstream)
- local tests (summary of comparisons follows) show improvements in performance, in line with expectations

comparisons wrt baseline  CMSSW_9_0_X_2017-01-11-2300

ten mu E < 200 GeV

D4Timing wf 22811 (similar for D7 and D9)
clearly less fake tracks, tracks are longer, about 15% fewer highPtTripletStep tracks, essentially no more tracks above p=200 GeV (beyond E range of the MC sample); all changes are for |eta|>~1.5
all_sign823-histatvsorig-histat_tenmuextendede2023d4timingwf22811p0c_recotracks_generaltracks__reco_obj_found


ttbar PU200 D4Timing wf 23034
plain yields of tracker-related objects has reduced, as would be expected from the fake reduction, essentially all change is in endcaps, and the effect is smaller the more restrictive reco selections are used to build the objects:
- 6% less generalTracks (mainly highPtTripletStep, lowPtTripletStep, and detachedQuadStep)
- 1.5% less charged hadrons
- 6% less electronGsfTracks
- 0.3% less ecalDrivenGsfElectrons

MTV plots show that the dup rate reduces by about an order of magnitude, while the fake rate goes down only slightly (this is probably the reason why the downstream higher level objects are not changed significantly if they have some duplicate removal or related cleanup selections)

in 23034 with PU200:
wf23034_general09_dup_eta
wf23034_general_fr_eta


On the technical side, based on ttbar PU200 RECO part
- CPU time is smaller by ~5% per event (essentially all from ~10% reduction in the iterative tracking)
- memory is roughly unchanged
- size of products on disk is smaller roughly at the same rate as the object yields (above); step3 (FEVT) size is down by 2%; miniAOD size is down by 1%.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
