### PR TITLE
Add L1T fractional prescale record

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR adds a fractional prescale record `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt` for data GTs and `L1TGlobalPrescalesVetosFract_passThrough_mc` for MC to accommodate the new fractional L1 prescale functionality.

The GT diffs are as follows:

**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_l1stage1_v1/113X_mcRun2_asymptotic_l1stage1_v2

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_design_v1/113X_mcRun2_design_v2

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_preVFP_v1/113X_mcRun2_asymptotic_preVFP_v2

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_v1/113X_mcRun2_asymptotic_v2

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2cosmics_asymptotic_deco_v1/113X_mcRun2cosmics_asymptotic_deco_v2

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_HeavyIon_v1/113X_mcRun2_HeavyIon_v2

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_pA_v1/113X_mcRun2_pA_v2

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_v1/113X_dataRun2_v2

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HEfail_v1/113X_dataRun2_HEfail_v2

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_relval_v1/113X_dataRun2_relval_v2

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_PromptLike_HI_v1/113X_dataRun2_PromptLike_HI_v2

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_v10/112X_dataRun2_HLT_relval_v2

**Run 2 HI HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_HI_v6/112X_dataRun2_HLT_relval_HI_v1

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Express_v4/112X_dataRun3_Express_v1

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Prompt_v5/112X_dataRun3_Prompt_v1

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017_design_v2/113X_mc2017_design_v3

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017_realistic_v2/113X_mc2017_realistic_v3

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017cosmics_realistic_deco_v2/113X_mc2017cosmics_realistic_deco_v3

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017cosmics_realistic_peak_v2/113X_mc2017cosmics_realistic_peak_v3

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_design_v2/113X_upgrade2018_design_v3

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_v2/113X_upgrade2018_realistic_v3

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_HI_v2/113X_upgrade2018_realistic_HI_v3

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_HEfail_v2/113X_upgrade2018_realistic_HEfail_v3

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018cosmics_realistic_deco_v2/113X_upgrade2018cosmics_realistic_deco_v3

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018cosmics_realistic_peak_v2/113X_upgrade2018cosmics_realistic_peak_v3

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_design_v2/113X_mcRun3_2021_design_v4

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_realistic_v3/113X_mcRun3_2021_realistic_v4

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021cosmics_realistic_deco_v4/113X_mcRun3_2021cosmics_realistic_deco_v5

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_realistic_HI_v3/113X_mcRun3_2021_realistic_HI_v4

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2023_realistic_v3/113X_mcRun3_2023_realistic_v4

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2024_realistic_v3/113X_mcRun3_2024_realistic_v4

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun4_realistic_v2/113X_mcRun4_realistic_v3

#### PR validation:

The tag for data was prepared by ensuring that the fractional prescale payload is consistent with that used for the old, legacy, integral prescales. See the following presentation for details: https://indico.cern.ch/event/974057/#35-integration-of-l1t-new-frac

In addition, technical tests were performed:

`addOnTests -j 8` and `runTheMatrix.py -l limited,1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but will be backported to 112X for use in the upcoming MWGR.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0
- pull_request = #32758

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0
- pull_request = #32741

**Comment by christopheralanwest** [comment]
please test

In the previous round of tests, I accidentally tested this PR with itself rather than PR #32741.

**Comment by smuzaffar** [comment]
@christopheralanwest , we have reached the limits for commit status for this PR. This is because we have tested the same sha too many time. I would suggest to force push a  change to this branch and restart the tests.

**Comment by christopheralanwest** [comment]
please test

**Comment by tlampen** [comment]
+alca

**Comment by silviodonato** [comment]
+1

No changes, as expected
> 

    No significant changes to the logs found
    Reco comparison results: 0 differences found in the comparisons
    DQMHistoTests: Total files compared: 37
    DQMHistoTests: Total histograms compared: 2716596
    DQMHistoTests: Total failures: 1
    DQMHistoTests: Total nulls: 0
    DQMHistoTests: Total successes: 2716573
    DQMHistoTests: Total skipped: 22
    DQMHistoTests: Total Missing objects: 0
    DQMHistoSizes: Histogram memory added: 0.0 KiB( 36 files compared)
    Checked 156 log files, 37 edm output root files, 37 DQM output files

**Pull request merged**
