### PR TITLE
Add track selection MVA and all the input variables to TrackingNtuple

### PR DESCRIPTION
**Pull request by makortel**
This PR adds the track selection MVA and all the input variables for it to the TrackingNtuple. 

A configuration flag is added to store only a boolean if a track is true or not instead of the full TrackingParticle information. This can be useful for e.g. MVA training to have a single branch telling if a track is true or fake, and to reduce the size of the ntuple.

Also an example script `analyseMVA.py` plotting the MVA and the input variables is added to serve as a starting point for further studies.

Tested in 9_1_0_pre3, no impact on standard workflows.

@rovere @VinInn @hajohajo

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please test

Apparently the first round of tests never finished or something...

**Comment by davidlange6** [comment]
+1

**Pull request merged**
