### PR TITLE
Merge TrackerLayerIdAccessor to TrackerTopology (6_2_SLHCDEV_X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #9449:

```
Migrate TrackerLayerIdAccessor to TrackerTopology by moving its functionality
to TrackerTopology.
```

Tested in CMSSW_6_2_SLHCDEV_X_2015-05-28-1100 that the FourMu workflows run, relying on #9449 on that there are no changes in results.

@rovere @VinInn @venturia @boudoul

### CODE REVIEW

**Comment by mark-grimes** [comment]
I'll start tests later.  Apparently there are DAS issues at the moment.
@boudoul, @venturia assuming there are no problems I guess you want this in?

**Comment by venturia** [comment]
Since I have asked for it my opinion does not count: we need an independent referee!

                                          Andrea

p.s. the rationale is that so far the phase 2 workflow works only in this release and thefore the only way to test changes which are at the same time applied also in 75x is to use this release.

On Jun 4, 2015, at 17:14 , Mark Grimes <notifications@github.com<mailto:notifications@github.com>>
 wrote:


I'll start tests later. Apparently there are DAS issues at the moment.
@boudoul<https://github.com/boudoul>, @venturia<https://github.com/venturia> assuming there are no problems I guess you want this in?

**Comment by boudoul** [comment]
yes keeping synchronized the two cycles (75X and 62XSLHCev)  is important at this stage- Thanks

**Comment by mark-grimes** [comment]
please test

**Comment by makortel** [comment]
I guess the errors are not related to this PR?

**Comment by mark-grimes** [comment]
No, they're for the track trigger workflow which was broken before hand.  Don't worry about those failures.

**Comment by boudoul** [comment]
the failures are  supposed to be fixed (hopefully :) ) in the next PR in the queue

**Comment by mark-grimes** [comment]
merge

**Pull request merged**
