### PR TITLE
Update global tags to use V5 JEC for 2017 data/MC and Run 3 MC and add V7b JR for 2018 data/MC

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the JEC for 2017 to the V5 version recently derived for the 2017 legacy reprocessing. In addition, the same JEC are used for Run 3 MC scenarios.

In addition, the jet resolution corrections for 2018 data and MC have been updated to match those used in the 102X series. See the [HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4309/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1.html) for details.

The GT differences are as follows:

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun2_v3/112X_dataRun2_v2

**Offline data (HE failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun2_HEfail_v3/112X_dataRun2_HEfail_v2

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun2_relval_v3/112X_dataRun2_relval_v2

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mc2017_realistic_v2/112X_mc2017_realistic_v2

**2017 realistic (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mc2017cosmics_realistic_deco_v1/112X_mc2017cosmics_realistic_deco_v2

**2017 realistic (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mc2017cosmics_realistic_peak_v1/112X_mc2017cosmics_realistic_peak_v2

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_upgrade2018_realistic_v1/112X_upgrade2018_realistic_v1

**2018 realistic (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_upgrade2018_realistic_HEfail_v1/112X_upgrade2018_realistic_HEfail_v1

**2018 realistic (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_upgrade2018cosmics_realistic_deco_v1/112X_upgrade2018cosmics_realistic_deco_v1

**2018 realistic (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_upgrade2018cosmics_realistic_peak_v1/112X_upgrade2018cosmics_realistic_peak_v1

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v2/112X_mcRun3_2021_design_v3

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v2/112X_mcRun3_2021_realistic_v3

**2021 realistic (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v2/112X_mcRun3_2021cosmics_realistic_deco_v3

**2021 realistic heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v2/112X_mcRun3_2021_realistic_HI_v3

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v2/112X_mcRun3_2023_realistic_v3

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v2/112X_mcRun3_2024_realistic_v3

The cosmic GTs are updated purely to minimize the tag difference between the pp collision and cosmic GTs. Differences in the PR comparison tests are expected only for 2017 data, 2017 MC and Run 3 scenarios.

#### PR validation:

See the threads in the [AlCaDB HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4309.html) and the [Jet Energy Scale HN](https://hypernews.cern.ch/HyperNews/CMS/get/jes/1004.html) for more details.

In addition, a technical test was performed:

`runTheMatrix.py -l limited,12024.0,7.23,159.0,12834.0,7.21 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but the 2017-specific portion (76260a5) will be backported to 10_6_X for use in the UL. There is no need to backport the portion that is specific to Run 3 (6c82887).

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
workflow = 12024.0,7.23,159.0,12834.0,7.21

**Comment by christopheralanwest** [comment]
please test

**Comment by tlampen** [comment]
+1

**Comment by christopheralanwest** [comment]
hold

I don't think that the changes to the Run2018C workflow (136.874) were expected.

**Comment by silviodonato** [comment]
@christopheralanwest do you have any news on this PR? Did you understand why it was changing `Run2018C`?

**Comment by christopheralanwest** [comment]
@silviodonato The issue is that the data tags were created assuming the Autumn18_V19 JEC for 2018 that are used in 10_2_X but the update to the Autumn18_V19 was not performed for 10_6_X or master. I hadn't noticed this when I initially created the PR. There is not yet a supported 2018 JEC for 10_6_X and master so what we do here is something of a matter of taste, but we should be consistent. The options were either to:

- revert the 2018 data JEC to Autumn18_V8
- use Autumn18_V19 JEC consistently. This option would require using the existing Autumn18_V19 JEC tags for MC but would also require creating new data tags that include the update to use the V7b jet resolution corrections. The existing 10_2_X tags cannot be used because they do not include the 2018D run period, which is covered by the 10_2_X prompt GT.

At Wednesday's PPD Coordination meeting, it was decided to use the second option.

For further details, see the thread at https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4309/2/1/1/1/1/1/1/1/1/1/1.html.

**Comment by christopheralanwest** [comment]
test parameters
workflow = 12024.0,7.23,159.0,12834.0,7.21,11024.2,7.4

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Updated 2017 UL JEC for data/MC
- Updated 2018 JEC for data/MC to [be consistent with 102X GTs](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4309/2/1/1/1/1/1/1/1/1/1/1/1/1.html)
- changes in 2017 and 2018 data/MC as well as Run-3 MC only seen in expected workflows
- pre-2017 changes only seen in slimmed Puppi MET significance (workflows 4.53, 136.731 and 136.7611). This minor change is [expected as a consequence of the extended JetPt range](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4309/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1.html).

**Comment by christopheralanwest** [comment]
unhold

**Comment by silviodonato** [comment]
+1

**Pull request merged**
