### PR TITLE
Ecal calib tools

### PR DESCRIPTION
**Pull request by ferriff**
Tools used to handle ECAL inter-calibration coefficients. Not used in any CMSSW sequence.
@shervin86 @argiro

### CODE REVIEW

**Comment by diguida** [comment]
@ferriff there is the dat file. It should go in the data repo.
@nclopezo is this correct?

**Comment by nclopezo** [comment]
I created the data repository: https://github.com/cms-data/Calibration-Tools, you can make pull requests to include more files there. 

I added the new data external: https://github.com/cms-sw/cmsdist/pull/1358. It should be available in the next IB. However the file will be available in Calibration/Tools/data so you need to update the path of the file. 

And I noticed some files in the bin directory that should not be there, right?

**Comment by ferriff** [comment]
Hi David, thanks. I am happy with the eerings.dat file that you put
there, i.e. for the moment I don't need more files. Should this require
any further action from my side?

As per the bin directory, I am not sure what you mean, can you be more
specific?

Federico

**Comment by mmusich** [comment]
@ferriff 
@nclopezo has already created for you the data repository https://github.com/cms-data/Calibration-Tools containing the `eerings.dat` as asked from @diguida . You need to remove the dat file from the `bin` directory and change the path of this file to `Calibration/Tools/data/eerings.dat`.

**Comment by ferriff** [comment]
Hi Marco, thanks for the clarification. I made the updates you suggested
but when testing prior making the new pull request I am unable to make
the directory `data' appear. How does it work? cms-addpkg does not
create data (tested in the latest IB), neither does scram b.
Thanks, Federico

**Comment by mmusich** [comment]
@ferriff , I see the `Calibration/Tools/data/` package available under the last IB release base
` /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_4_X_2015-02-11-1400/external/slc6_amd64_gcc491/data/`
There should be some environment variable that allows you to use it in your path while testing. @nclopezo can you please comment?

**Comment by nclopezo** [comment]
Hi, the file can be found in CMSSW_SEARCH_PATH
And you can use the  edm::FileInPath to access it. You can see in this PR an example of how is it used:
https://github.com/cms-sw/cmssw/pull/7512/files

**Comment by ferriff** [comment]
Hi, I am sorry but this is not clear to me. Suppose I am a generic user
of Calibration/Tools. I see from github that there is the package, I
take it with `git cms-addpkg Calibration/Tools' and the data/ directory
does not show up: how in the world I am going to guess that it exists,
how do I copy it locally, how do I keep it up-to-date, merge it with
other user's branches and so on?

I don't see instructions in the pull request you pointed me to, nor I
see a documented example of edm::FileInPath besides this line

   edm::FileInPath ueData(calibrationFile.data());

BTW, the file in Calibration/Tools/data/ is used in python scripts.

Can you please help?

Thanks,
Federico

**Comment by davidlt** [comment]
Data files (especially big ones) live as externals to CMSSW. They are build as RPMs (like GCC, Boost, CMake, GEANT4, ROOT, etc). CMSSW uses `CMSSW_SEARCH_PATH` to locate data files. First it looks into your current SCRAM dev area, then in different locations. If you create `Calibration/Tools/data/` and place your file inside. That's where `edm::FileInPath` will find it as it's on the first path in `CMSSW_SEARCH_PATH`. Otherwise from the external data package DavidM just created.

This described how it works and how you can test new data file version before asking to update in the external. Also tells you how to find it via any other language.

Do `git grep CMSSW_SEARCH_PATH` to find the examples.

For example:

`DPGAnalysis/Skims/python/muon_json_2012.py`
```
  6 def findFileInPath(theFile):
  7     for s in environ["CMSSW_SEARCH_PATH"].split(":"):
  8         attempt = join(s,theFile)
  9         if exists(attempt):
 10             return attempt
 11     return None
```

**Comment by davidlt** [comment]
Found the old documentation about it: https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEdmFileInPath

**Comment by ferriff** [comment]
Hi David, thanks, now I understand it better.

It is still unclear how to work with peers through git on files on the
data/ directory: does one need to

`git clone git://github.com/cms-data/Calibration-Tools data`

into his/her local Calibration/Tools?

Cheers,
Federico

**Comment by davidlt** [comment]
Depends.

DavidM merged it 7 days ago. This means that data file is available in `CMSSW_7_4_X` IBs for the last several days. You don't need to do anything for releases after that. It's already in and always findable via `CMSSW_SEARCH_PATH`.

You only need `Calibration/Tools/data` locally if:
- You are a testing a new version of that file. Thus you don't want to use the one in external data package.
- You want to test code in release where external data package (data-Calibration-Tools) was not included. E.g., this was only added to `CMSSW_7_4_X` 7 days ago thus it doesn't exist in in `CMSSW_7_3_X` or `CMSSW_5_3_X`, etc.

**Comment by mmusich** [comment]
@ferriff for this to move one we need the `edm::FileInPath` mechanism in place. Can you please change the scripts accordingly?

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Pull request closed without merging**
