### PR TITLE
Migrate DQM/Phase2OuterTracker to DQMEDAnalyzer

### PR DESCRIPTION
**Pull request by dmitrijus**
Fixes (at least partially) https://github.com/cms-sw/cmssw/issues/22203

Removes a lot of unused / empty code.
In can be re-added once it does something useful

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@fabiocos can you merge this as well, together with #22218 ?

**Comment by fabiocos** [comment]
+1

**Comment by boudoul** [comment]
@emacdonald16 FYI

**Pull request merged**
