### PR TITLE
Update TrackingNtuple

### PR DESCRIPTION
**Pull request by makortel**
This PR makes the following updates to the TrackingNtuple:
* add alternative track-to-TrackingParticle matchings
  * best matching TrackingParticle (also for those tracks that would be fake by the standard matching)
     * defined as the TrackingParticle with most SimHits matched to the clusters of the track, at minimum 3 hits of a track must be matched to the TP
  * best matching TrackingParticle starting from the first hit of the track
      * same definition as above but starting from the first hit of the track
* add various track-to-TrackingParticle matching scores
  * for both "best TP" and "best TP from first hit"
     * shared cluster fraction (the quantity used in `QuickTrackAssociatorByHits`; of these only this one is added for seeds)
     * shared cluster fraction with the `TrackingParticle::numberOfTrackerHits()` as the denominator
     * shared cluster fraction with the number of reco clusters matched to the TrackingParticle (as given by `ClusterTPAssociation`)
     * chi2 calculated from the track and TrackingParticle parameters and the track parameter uncertanties (as in `TrackAssociatorByChi2`)
  * for each matched TP: the chi2 (as above)
   * tracks: number of invalid hits (inside track and also "inner" and "outer"); this implied a change of branch name `trk_nInvalid` => `trk_nLost`
* include on-the-fly created matched strip hits
  * omitting these this was actually a serious bug causing memory over writes
* other additions
   * tracks and seeds: number of clusters (mostly because it is used in the track-to-TP matching)
   * TrackingParticles: `numberOfTrackerHits()`, and the number of reco clusters matched to the TP (as in `ClusterTPAssociation`)

and in addition:
* remove unused code from `TrackAssociatorByChi2Impl`

Tested in 9_4_0_pre3, no changes expected in standard workflows.

@VinInn @ebrondol @hajohajo

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
So I forgot to add the file... Included now and squashed in the commit where it should have been included.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
