### PR TITLE
Customisations and few fixes for online DQM

### PR DESCRIPTION
**Pull request by diguida**
Small set of fixes for online DQM:
- fix the name of the online playback GUI host
- new online GT for DQM
- fix temporary connection string for Tau Tag high-level calibrations (ping to @diguida - oh, it's me! - and @mmusich )

### CODE REVIEW

**Comment by mmusich** [comment]
@diguida how many tags do we have in `'sqlite_file:/home/dqmprolocal/external/RecoTauTag_MVAs_2014Jul07.db` ?

**Comment by mmusich** [comment]
For the record, the diff between the two GTs: [Link to browser](https://cms-conddb.cern.ch/browser/#diff/gts/GR_H_V58C/74X_dataRun2_HLT_v1).

**Comment by diguida** [comment]
@mmusich 150 tags!!!

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
@deguio @danduggan @mmusich I made a less painful hack: if you are online, use frontier online squids.

**Comment by deguio** [comment]
thanks @diguida for this.
can you please submit the same for 75 and 76?
ciao,
F.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10563	fc28909
- changes are specific to online DQM workflows
- jenkins tests passed and comparisons show now differences as expected

**Comment by slava77** [comment]
+1

what was wrong with the first one? https://github.com/cms-sw/cmssw/pull/10563#issuecomment-128681479

**Comment by diguida** [comment]
superseded by #10714

**Pull request closed without merging**
