### PR TITLE
Moving to 2018 Cosmic WFs and Re-adding 2016-2017 Cosmic WFs (10_3_X)

### PR DESCRIPTION
**Pull request by boudoul**
Backport of #25137
Updating runthematrix cosmic WFs with the latest and greatest 2018 Cosmic GTs
The corresponding WFs are 7.2 , 7.3, 7.4

This PR is also backporting #25249 and #25276 to be fully in synch with 10_4 X (adding 2017-2016)
The corresponding WFs are 7.21 , 7.22
Thanks @lpernie for having provided the GTs

@mmusich @tsusa FYI

### CODE REVIEW

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@prebello @zhenhu is it ok to merge for you? I think there should be no issue

**Comment by prebello** [comment]
+1

yes @fabiocos

**Comment by boudoul** [comment]
hold

**Comment by boudoul** [comment]
depending on the outcome, I can bacport this : 
https://github.com/cms-sw/cmssw/pull/25249
here

**Comment by fabiocos** [comment]
@boudoul could you please update this PR according to #25249 ?

**Comment by boudoul** [comment]
Hi @fabiocos : done - I also updated the title and the description of this PR accordingly .
Please note the 10_4_X PR #25276  I just made (the content is added in this backport to be fully in synch) - It doesn't matter for any test, IB etc, but just in case we need to submit relval we should also have matrix injector parameters defined

**Comment by fabiocos** [comment]
please test workflow 7.20,7.21,7.22

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this is not specific for upgrade, in case please sign it for reference

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
