### PR TITLE
[HETEROGENEOUS] [LLVM14] Apply clang-tidy and clang-format changes

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format changes needed due to llvm 14.0.6 integration.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
sure @fwyzard , feel free to open a new PR and reject it (and I will close it then)

**Comment by fwyzard** [comment]
See #41500 / #41501 .

**Comment by smuzaffar** [comment]
closing it in favor of https://github.com/cms-sw/cmssw/pull/41500

**Pull request closed without merging**
