### PR TITLE
AutoCond update for 2017 and 2021 cosmic GTs

### PR DESCRIPTION
**Pull request by tlampen**
#### PR description:

This PR updates the 2017 and 2021 cosmic GTs so that they have only the desired differences with respect to the collision GTs. For 2017, both PEAK and DECO cosmic GTs are updated.  For 2021, only DECO cosmic GT is updated (the PEAK version does not exist at the moment).

Desired differences with respected collision GTs are described in [1]. Updates of other cosmic GTs will follow once Ultralegacy campaigns are done.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4194.html

**GT diffs wrt. collision GTs:**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_realistic_v1/110X_mc2017cosmics_realistic_deco_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_realistic_v1/110X_mc2017cosmics_realistic_peak_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021_realistic_v2/110X_mcRun3_2021cosmics_realistic_deco_v2

#### PR validation:
A technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### if this PR is a backport please specify the original PR:
This PR is not a backport.

### CODE REVIEW

**Comment by tlampen** [comment]
please test

**Comment by christopheralanwest** [comment]
please test workflow 7.21,7.23

(cosmic workflows do not run in the standard matrix tests)

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
