### PR TITLE
Fixes and developments to improve tau veretx association

### PR DESCRIPTION
**Pull request by roger-wolf**
This is a PR that had been made by Michal on an earlier release cycle and stalled there since 90X was just in the migration to 91X. It is now migrated to 91X accordingly. It contains code clean-up work to improve the work flow of tau reconstruction as such and the maintainability of the code. This part had been split off from other technical changes since with this PR we do expect small changes in the validation workflows. I'm citing comments from Michal and refer to him to comment on further questions. 

Expected changes:
 * Small differences in outputs of all algorithms/discriminants using tau vertex position to filter PFChargedCandidates,
 * Disappearing of impact parameters and flight lengths with very (incorrect) big significance thanks to change of Algorithm in configuration of PFTauPrimaryVertexProducer from 1 (useFrontPV, i.e. veretx[0]) to 0 (useInputPV, i.e. vertex associated to tau). In a consequence some changes in output of MVAIsolation discriminant are expected with small change of performance (improvement!)

Standard tests do not reveal any problems beyond the expected changes. 

Cheers,
Roger

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
Tiny differences in the tau algorithms outputs are visible already in the plots produced by the jenkins tests, see e.g. 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-05-2300+18243/19243/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/RecoTauV_hpsPFTauProducerRealData_hpsPFTauDiscriminationByVLooseIsolationMVArun2v1DBdR03oldDMwLT.html

I think they can correspond to the expected modifications anticipated in the description part of this PR. Can you confirm, @roger-wolf ? Or, alterntively: do you have any plot, or link to a presentation made in a meeting, which shows the effect of this PR?

**Comment by roger-wolf** [comment]
@mbluj: Hi Andrea I can confirm that small changes are expected even at the level of Jenkins tests. Michal is the best one to give the final confirm. 
Cheers,
Roger

**Comment by mbluj** [comment]
Hello,

On Mon, Apr 10, 2017 at 8:52 AM, Roger Wolf <notifications@github.com>
wrote:

> @mbluj <https://github.com/mbluj>: Hi Andrea I can confirm that small
> changes are expected even at the level of Jenkins tests. Michal is the best
> one to give the final confirm.
>
I confirm, small changes as seen in Jenkins tests are expected. They should
almost disappear for taus close to PV=vetrex[0] defined as
fabs(tau.leadTauChargedHadronCandidate()->dz(PV)) < 0.1.
See e.g. distribution of MVAIsoOldDMs for taus with Pt>20GeV matched to
genTruth tau from ZTT RelVal (1k events) for old reco (red) and new (blue)
are as follow:
* w/o the |dz(PV)|<0.1 requirement

[image: Inline image 1]

* w/ the |dz(PV)|<0.1 requirement

[image: Inline image 2]


Michał

**Comment by perrotta** [comment]
+1
Small differences in the jenkins tests are in line with the expectations, as confirmed in https://github.com/cms-sw/cmssw/pull/18243#issuecomment-292928494

**Comment by davidlange6** [comment]
+1

**Pull request merged**
