### PR TITLE
Adding Number of RecHits plot for SiStrip stereo modules (backport to 13_1_X) 

### PR DESCRIPTION
**Pull request by mascioti**
#### PR description:
Adding Number of RecHits on Strip Stereo Modules on the Tracker DQM

#### PR validation:
runTheMatrix.py -l 12434

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #41725

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41725

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
> @cms-sw/dqm-l2 should the tests be re-triggered?

@sroychow I don't see why we should. Tests are succesfull.
Moreover: since this is a verbatim backport/forwardport of the PRs already signed and merged in 13_2_X and in 13_0_X, let merge this one as such in the intermediate release 13_1_X

**Comment by perrotta** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
