### PR TITLE
RCT unpacker plus DQM 75X

### PR DESCRIPTION
**Pull request by nsmith-**
Re-make of #10631
75X version of #10880

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by deguio** [comment]
+1
but needs to prove that it works fine in 76

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
@davidlange6 these have been in 76X for some time.  Can you merge please?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
