### PR TITLE
[backport 106X] Adding UL16 PUID and fixing QGL values in nanoAOD

### PR DESCRIPTION
**Pull request by alefisico**
#### PR description:

- This is the backport of #33925 targetting nanoAODv9
- This PR has to be tested with #33940 

#### PR validation:

- The PR passes the usual tests. 

FYI @camclean @singh-ramanpreet

### CODE REVIEW

**Comment by qliphy** [comment]
please test with #33940

**Comment by mariadalfonso** [comment]
please abort

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please abort

**Comment by mariadalfonso** [comment]
please test with cms-sw/cmsdist#6977

**Comment by mariadalfonso** [comment]
+xpog

* puID for the Ul 2016 updated (verified that the 106Xul16 i.e. V8nano do not change)
* general fix of the nan
* external is merged

**Comment by qliphy** [comment]
+1

**Pull request merged**
