### PR TITLE
New histos with multithreading

### PR DESCRIPTION
**Pull request by archiron**
few histos added :
new mva histos added
In the section PFlow information, the so-called calorimetric fbrem histo was added
full5x5_sigmaIetaIeta() for barrel, endcaps, barrel+endcaps

and few histos modified or removed :
*_eg histos
PF isolation plot in a separate "box"
pbms with infinity in seed histos was taken into account (no event with infinitity)

a new script (relval_gedGsfE.tcsh) added. must do the job of store_gedGsfE.tcsh, publish_gedGsfE.tcsh, finalize_gedGsfE.tcsh and analyze_gedGsfE.tcsh.
these scripts will be removed later.

### CODE REVIEW

**Comment by archiron** [comment]
very strange. When I done  : runTheMatrix.py -l 25202.0 all run fine with CMSW_7_4_0_pre2.

processing  relval_standard
request for INPUT for  None
processing  relval_highstats
request for INPUT for  None
processing  relval_pileup
request for INPUT for  None
processing  relval_generator
request for INPUT for  None
processing  relval_extendedgen
request for INPUT for  None
processing  relval_production
request for INPUT for  None
processing  relval_ged
request for INPUT for  None
ignoring relval_upgrade from default matrix
processing  relval_identity
request for INPUT for  None
processing  relval_machine
request for INPUT for  None
processing  relval_unsch
request for INPUT for  None
Running in 4 thread(s)

Preparing to run 25202.0 TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15

# in: /afs/cern.ch/work/a/archiron/private/CMSSW_7_4_0_pre2_TEST/src going to execute cd 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15
 cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi  --conditions auto:run2_mc -n 10 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 --fileout file:step1.root  > step1_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15.log  2>&1

# in: /afs/cern.ch/work/a/archiron/private/CMSSW_7_4_0_pre2_TEST/src going to execute cd 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15
 cmsDriver.py step2  --conditions auto:run2_mc --pileup_input das:/RelValMinBias_13/CMSSW_7_3_0_pre1-PRE_LS172_V15-v1/GEN-SIM -n 10 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval,RAW2DIGI,L1Reco --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --pileup AVE_35_BX_25ns --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 --filein file:step1.root  --fileout file:step2.root  > step2_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15.log  2>&1

# in: /afs/cern.ch/work/a/archiron/private/CMSSW_7_4_0_pre2_TEST/src going to execute cd 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15
 cmsDriver.py step3  --conditions auto:run2_mc --pileup_input das:/RelValMinBias_13/CMSSW_7_3_0_pre1-PRE_LS172_V15-v1/GEN-SIM -n 10 --eventcontent RECOSIM,DQM -s RAW2DIGI,L1Reco,RECO,EI,VALIDATION,DQM --datatier GEN-SIM-RECO,DQMIO --pileup AVE_35_BX_25ns --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 --filein file:step2.root  --fileout file:step3.root  > step3_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15.log  2>&1

# in: /afs/cern.ch/work/a/archiron/private/CMSSW_7_4_0_pre2_TEST/src going to execute cd 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15
 cmsDriver.py step4  --conditions auto:run2_mc -s HARVESTING:validationHarvesting+dqmHarvesting --filetype DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --mc  --magField 38T_PostLS1 -n 100  --filein file:step3_inDQM.root --fileout file:step4.root  > step4_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15.log  2>&1

# in: /afs/cern.ch/work/a/archiron/private/CMSSW_7_4_0_pre2_TEST/src going to execute cd 25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15
 cmsDriver.py step5  --conditions auto:run2_mc -n 100 --eventcontent MINIAODSIM --runUnscheduled  --filein file:step3.root -s PAT --datatier MINIAODSIM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --mc  --fileout file:step5.root  > step5_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15.log  2>&1

25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jan 16 10:21:29 2015-date Fri Jan 16 09:36:10 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

Same results with 1306.0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jan 16 10:35:41 2015-date Fri Jan 16 10:26:48 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

eror MSG is 25202.0 and 1306.0 is : 
%MSG-e FatalSystemSignal:  FSQDiJetAve:fsqHLTOfflineSource  15-Jan-2015 22:06:49 CET Run: 1 Event: 1
A fatal system signal has occurred: segmentation violation
%MSG

Arnaud

**Comment by deguio** [comment]
the errors are not related.

**Comment by archiron** [comment]
I made again tests with runTheMatrix.py -l 25202.0 and CMSSW_7_4_X_2015-01-16-0200.

25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jan 16 12:18:26 2015-date Fri Jan 16 11:25:09 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jan 16 12:38:36 2015-date Fri Jan 16 12:26:45 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

all seems OK.

**Comment by deguio** [comment]
+1
@archiron when you submit the next PR to remove the unused tcsh scripts, please remove all the commented lines from the code as well.

thank you,
F.

**Pull request merged**
