### PR TITLE
Phase2-hgx360J Add the dd4hep version of the modified code of passive material description of V19 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the dd4hep version of the modified code of passive material description of V19 geometry of HGCal

#### PR validation:

Checked with materials from #46596

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar, @srimanob, @subirsarkar Please approve this PR

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
