### PR TITLE
Introducing Stacks in CMSSW geometry

### PR DESCRIPTION
**Pull request by ebrondol**
The introduction of the Stacks is in first place made adding a new TkDDDStructure which is called either Phase2OTBarrelStack or Phase2OTEndcapStack. This contains the list of the Stack Modules (trackerStructureTopology.xml).
The new TkDDDStructure is recognized into the trk geom introducing a new GDEnumType called OTPhase2Stack (CmsTrackerStringToEnum.cc).
The CmsDetConstruction class has been modified in such a way that it can recognize when the module is a stack and configured to search for possible children: for Lower and Upper modules in a stack are fixed, following the same convention used for glued modules (+1, +2).
Finally, the README has been updated in order to include the description of the Stacks DetIds.

### CODE REVIEW

**Comment by mark-grimes** [comment]
please test

As mentioned in the phase 2 sim meeting consider us "prodded".  Test should start - if you want to add anything else to this PR go ahead, and then comment here.

**Comment by ebrondol** [comment]
@mark-grimes 
I have update the README as discuss yesterday, I will add the tkTopology changes in another PR later on. Thanks.

**Comment by mark-grimes** [comment]
I tested Extended2023Muondev since it's the only one (as far as I can tell) that uses `Geometry/TrackerCommonData/data/PhaseIIdev/Pixel10D/trackerStructureTopology.xml`; and I don't think it's in the automatic tests.  This fails in digi but on closer inspection it turns out it failed before this PR anyway, but with a different error.
So with:

    runTheMatrix.py -w upgrade -l 10800

**Before:**
```
----- Begin Fatal Exception 04-Nov-2015 15:04:25 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'L1TrackTrigger_step'
   [2] Calling event method for module TTClusterBuilder_PixelDigi_/'TTClustersFromPixelDigis'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: edm::DetSetVector<PixelDigi>
Looking for module label: simSiPixelDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
**After:**
There are 6600 occurrences of

    A L E R T! Side-Disk-Ring-Module already present!

8594 occurrences of

    A L E R T! Layer-Rod-Module already present!

Then
```
----- Begin Fatal Exception 04-Nov-2015 15:26:38 CET-----------------------
An exception of category 'StackedTrackerGeometryBuilder' occurred while
   [0] Processing run: 1
   [1] Running path 'L1TrackTrigger_step'
   [2] Calling beginRun for module TTClusterBuilder_PixelDigi_/'TTClustersFromPixelDigis'
   [3] Using EventSetup component StackedTrackerGeometryESModule/'' to make data StackedTrackerGeometry/'' in record StackedTrackerGeometryRecord
Exception Message:
Attempted to build Endcap stacks that are far apart in phi:0.314159 524292234   subdetector: 7
   BARREL: 0    LAY:  999999    ROD:  10        MOD:  1
   ENDCAP: 1    SIDE: 2 DISK: 1 RING: 1 MOD: 10

----- End Fatal Exception -------------------------------------------------
```
Is this understood?  Were the stacks meant to go into the already existing scenario?

**Comment by ebrondol** [comment]
Dear @mark-grimes ,
yes, this is understood by the SLHC Tracker group, and @boudoul can confirm it.
We are working on this issue and in the meanwhile we decide to run digi without the L1 Track Trigger process.

**Comment by mark-grimes** [comment]
Okay, that explains the error before applying this pull request.  But the error after applying it is geometry related.  Is that also understood?

**Comment by ebrondol** [comment]
Yes, also in this case, if you delete the L1TrackTrigger_step from the digi reconstruction, this should disappear.

**Comment by mark-grimes** [comment]
Okay, with

    runTheMatrix.py -w upgrade -l 10800 --command='--customise_commands="if hasattr(process,\"L1TrackTrigger_step\") : process.schedule.remove( process.L1TrackTrigger_step )"'

digitisation finishes fine but then there is a crash in reconstruction, with stack trace:
```
#4  <signal handler called>
#5  0x00007fd041b20aa6 in ForwardRingDiskBuilderFromDet::computeBounds(std::vector<GeomDet const*, std::allocator<GeomDet const*> > const&) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc472/cms/cmssw/CMSSW_6_2_SLHCDEV_X_2015-11-01-1100/lib/slc6_amd64_gcc472/libTrackingToolsDetLayers.so
#6  0x00007fd041b20e7d in ForwardRingDiskBuilderFromDet::operator()(std::vector<GeomDet const*, std::allocator<GeomDet const*> > const&) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc472/cms/cmssw/CMSSW_6_2_SLHCDEV_X_2015-11-01-1100/lib/slc6_amd64_gcc472/libTrackingToolsDetLayers.so
#7  0x00007fd03ee7739e in Phase2OTECRing::Phase2OTECRing(std::vector<GeomDet const*, std::allocator<GeomDet const*> >&, std::vector<GeomDet const*, std::allocator<GeomDet const*> >&, std::vector<GeomDet const*, std::allocator<GeomDet const*> >&, std::vector<GeomDet const*, std::allocator<GeomDet const*> >&) () from /afs/cern.ch/user/g/grimes/cmsswReleases/CMSSW_6_2_SLHCDEV_X_2015-11-03-2300/lib/slc6_amd64_gcc472/libRecoTrackerTkDetLayers.so
#8  0x00007fd03ee783e7 in Phase2OTECRingBuilder::build(GeometricDet const*, TrackerGeometry const*) () from /afs/cern.ch/user/g/grimes/cmsswReleases/CMSSW_6_2_SLHCDEV_X_2015-11-03-2300/lib/slc6_amd64_gcc472/libRecoTrackerTkDetLayers.so
#9  0x00007fd03ee7b26c in Phase2OTECRingedLayerBuilder::build(GeometricDet const*, TrackerGeometry const*) () from /afs/cern.ch/user/g/grimes/cmsswReleases/CMSSW_6_2_SLHCDEV_X_2015-11-03-2300/lib/slc6_amd64_gcc472/libRecoTrackerTkDetLayers.so
#10 0x00007fd03ee68904 in GeometricSearchTrackerBuilder::build(GeometricDet const*, TrackerGeometry const*, TrackerTopology const*) () from /afs/cern.ch/user/g/grimes/cmsswReleases/CMSSW_6_2_SLHCDEV_X_2015-11-03-2300/lib/slc6_amd64_gcc472/libRecoTrackerTkDetLayers.so
#11 0x00007fd037b6c591 in TrackerRecoGeometryESProducer::produce(TrackerRecoGeometryRecord const&) () from /afs/cern.ch/user/g/grimes/cmsswReleases/CMSSW_6_2_SLHCDEV_X_2015-11-03-2300/lib/slc6_amd64_gcc472/pluginRecoTrackerGeometryESProducerPlugin.so
<snip>
```

I guess the reconstruction and sim geometries don't match?

**Comment by mark-grimes** [comment]
merge

After private communication - the plan is to merge and allow L1 tracking development in digi.  Reconstruction will be fixed in another pull request.

**Pull request merged**
