### PR TITLE
adding DQM-only wf on AOD input for HLT validation

### PR DESCRIPTION
**Pull request by fabozzi**
Adding relval test for DQM-only sequence on AOD input introduced by PR #20322

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.7801

**Comment by fabozzi** [comment]
@mtosi @prebello 
FYI

**Comment by mtosi** [comment]
@fabozzi , thanks !
I think the HARVESTING step can be limited as well to the HLT part only
`HARVESTING:hltOfflineDQMClient`, should work

**Comment by fabozzi** [comment]
please test workflow 136.7801

**Comment by fabozzi** [comment]
@mtosi 
thanks! I have updated according to your suggestion

**Comment by davidlange6** [comment]
please test

**Comment by mtosi** [comment]
to you

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1
(not sure we want the nonstandard output file name long term)

**Pull request merged**
