### PR TITLE
use qScale in pixel cluster charge reweighting

### PR DESCRIPTION
**Pull request by mroguljic**
#### PR description:
Introducing qScale in the cluster charge reweighting as it is now different from 1 in Run 3. This change is supposed to alleviate the data/mc discrepancy in cluster charge, for example, slide 4 in backup of the following contribution https://indico.cern.ch/event/1271486/contributions/5397175/attachments/2644044/4576218/Pixel_Dynamic_Inefficiency_simulation_Validation___update2.pdf

#### PR validation:
Run the matrix tests (`runTheMatrix.py -l limited -i all --ibeos`) all passed:
 "47 46 45 35 22 4 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed"

Privately ran over ZMM GEN-SIM sample (file `/store/relval/CMSSW_12_4_12/RelValZMM_PU_13p6/GEN-SIM/PU_124X_mcRun3_2022_realistic_postEE_v1_PDMVRELVALS188_HS_2023PU-v1/00000/8501a177-d79f-4e60-9ceb-40eac7ec3371.root`) and the changes in cluster charge are as expected (red is without change, blue is with the change)
image

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 250202.184

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@mroguljic you might want to change the PR title to: "use qScale in pixel cluster charge reweighting" for clarity in the release notes.

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
> This looks like it will have a very strong low level effect that will make it hard to disentangle so we should discuss the strategy to incorporate this. What is the plan there

I guess a good proportion of the changes are due to a different random number sequence used when the digitization code is touched. 
The changes at the level of reconstructed tracks are generally small in all workflows.
On top of that there is what I guess is desidered effect to suppress the charge deposition in pixels, which shows in certain histograms. It would be nice to understand if e.g. the strong decrease of charge in pixel forward (even in run2 wfs) is expected: https://tinyurl.com/2h936kvs

**Comment by rappoccio** [comment]
> > This looks like it will have a very strong low level effect that will make it hard to disentangle so we should discuss the strategy to incorporate this. What is the plan there
> 
> I guess a good proportion of the changes are due to a different random number sequence used when the digitization code is touched. The changes at the level of reconstructed tracks are generally small in all workflows. On top of that there is what I guess is the desidered effect to suppress the charge deposition in pixels, which shows in certain histograms. It would be nice to understand if e.g. the strong decrease of charge in pixel forward (even in run2 wfs) is expected: https://tinyurl.com/2h936kvs

Yes, I would like to see if PPD+PDMV are okay with the validation plan.

**Comment by mmusich** [comment]
> Yes, I would like to see if PPD+PDMV are okay with the validation plan.

I am not sure what would be the suggestion, assuming the changes here are expected (@mroguljic @ferencek please have a look to the [DQM bin-by-bin differences](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-05-10-2300+ef9132/56999/dqm-histo-comparison-summary.html) ) .
Are you proposing to make a pre-release just for this change? I am not sure the overall magnitude of the change justifies that.

**Comment by rappoccio** [comment]
> > Yes, I would like to see if PPD+PDMV are okay with the validation plan.
> 
> I am not sure what would be the suggestion, assuming the changes here are expected (@mroguljic @ferencek please have a look to the [DQM bin-by-bin differences](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-05-10-2300+ef9132/56999/dqm-histo-comparison-summary.html) ) . Are you proposing to make a pre-release just for this change? I am not sure the overall magnitude of the change justifies that.

No, I would just like to ensure that they are happy with the plan.

**Comment by rappoccio** [comment]
+1

Discussing offline with PPD, they are happy with the plan.

**Comment by ferencek** [comment]
> > This looks like it will have a very strong low level effect that will make it hard to disentangle so we should discuss the strategy to incorporate this. What is the plan there
> 
> I guess a good proportion of the changes are due to a different random number sequence used when the digitization code is touched. The changes at the level of reconstructed tracks are generally small in all workflows. On top of that there is what I guess is the desidered effect to suppress the charge deposition in pixels, which shows in certain histograms. It would be nice to understand if e.g. the strong decrease of charge in pixel forward (even in run2 wfs) is expected: https://tinyurl.com/2h936kvs

Apologies for the slow response. The changes indeed go in the expected direction. For Run 2, though, we have to double check but based on the output it looks like the Run 2 FPix templates already had qScale<1.

**Comment by ferencek** [comment]
I can confirm that qScale for FPix in Run 2 is indeed significantly different from 1
image

For Run 3 this is the case for both BPix and FPix
image

which is what prompted this PR. So in summary, all changes are as expected.

**Comment by tvami** [comment]
hi @mroguljic I think this should be backported to the release that's used in the 2022/2023 MC production (i.e. 13_1_X)

**Pull request merged**
