### PR TITLE
Solve static check issues and bugs for reco muon tracking tools

### PR DESCRIPTION
**Pull request by perrotta**
I hit the issues addressed here while looking at the output of the static analyzer triggered in a pull request review.

The fixes in RecoMuon/GlobalTrackingTools/src/GlobalMuonRefitter.cc and RecoMuon/TrackingTools/src/MuonTrajectoryCleaner.cc are just cleaning and, they are uncontroversial. 

In RecoMuon/TrackingTools/src/MuonErrorMatrix.cc there was a real bug, instead: min/maxPt was assigned instead of min/maxEta in a couple of places. It looks like that these two places were not accessed with the standard configuration (and in fact there are no changes in reco outputs in jenkins) but they must be fixed anyhow.

@drkovalskyi @folguera

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
abort test

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
Differences in the Jenkins tests are due to the logErrorHarvester, which shows one less entry in the TTbarPU wf 25202. No hint, and not expected, that it is due to this PR, though (different sequences of MB files are included for PU wrt baseline)

**Comment by drkovalskyi** [comment]
I'm not familiar with this code, but the changes look reasonable to me.

**Comment by slava77** [comment]
On 11/14/17 5:53 PM, drkovalskyi wrote:
> I'm not familiar with this code, but the changes look reasonable to me.
> 

the change likely modifies performance of the quantities used in
analysis, if it still used.
Can the users or primary developers of this check and confirm?

**Comment by perrotta** [comment]
@slava77 : no, this PR doesn't modify anything in the "normal" configurations
You are probably referring to #21252 instead...

**Comment by slava77** [comment]
On 11/14/17 6:07 PM, perrotta wrote:
> @slava77 <https://github.com/slava77> : no, this PR doesn't modify
> anything in the "normal" configurations
> You are probably referring to #21252
> <https://github.com/cms-sw/cmssw/pull/21252> instead...

sorry, ignore my last comment then.

**Comment by perrotta** [comment]
+1
- Just bug fixes and cleanings
- No effect on the standard workfls, as the bugged part is not accessed in standard configurations

**Comment by davidlange6** [comment]
+1

**Pull request merged**
