### PR TITLE
Phase2-hgx348A Make use of constexpr in the scintillator DeId for HGCal for better processing

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of constexpr in the scintillator DeId for HGCal for better processing

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

@bsunanda , is there any expected CPU advantage if we use this variant of classes?

**Comment by bsunanda** [comment]
@srimanob Please approve

**Comment by srimanob** [comment]
+Upgrade

Technical PR

**Pull request merged**
