### PR TITLE
Set generateConcurrently to False to fix Herwig workflow issue

### LINKED ISSUE #33544: Segfault in Herwig
Workflow 535.0 step 1 crashes in CMSSW_12_0_X_2021-04-27-1100
```
27-Apr-2021 14:34:58 CEST  Successfully opened LHE file thread0/cmsgrid_final.lhe
Error: No such file or directory: cmsgrid_final.lhe
Error: The object '/Herwig/Partons/PDFSet_nnlo' was not created as another object with that name already exists.
Error: The object '/Herwig/Partons/PDFSet_lo' was not created as another object with that name already exists.
Error: The object '/Herwig/EventHandlers/LesHouchesHandler' was not created as another object with that name already exists.
Error: The object '/Herwig/Cuts/NoCuts' was not created as another object with that name already exists.
Error: The object '/Herwig/Partons/LHAPDF' was not created as another object with that name already exists.
Error: The object '/Herwig/EventHandlers/LesHouchesReader' was not created as another object with that name already exists.
Error: No such file or directory: cmsgrid_final.lhe
Herwig: EventGenerator not available.
Check if 'InterfaceMatchboxTest.run' is a valid run file.


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Tue Apr 27 14:35:01 CEST 2021
Thread 5 (Thread 0x2b989fe00700 (LWP 20760)):
#2  0x00002b9869c53720 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b985ec41d19 in syscall () from /lib64/libc.so.6
#5  0x00002b985db1ed9d in tbb::internal::futex_wait (comparand=2, futex=0x2b9865f0302c) at ../../include/tbb/machine/linux_common.h:81

Thread 4 (Thread 0x2b989ef70700 (LWP 20759)):
#2  0x00002b9869c53720 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b985ec41d19 in syscall () from /lib64/libc.so.6
#5  0x00002b985db1ed9d in tbb::internal::futex_wait (comparand=2, futex=0x2b9865f0312c) at ../../include/tbb/machine/linux_common.h:81

Thread 3 (Thread 0x2b989e56f700 (LWP 20758)):
#2  0x00002b9869c53720 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x00002b985ec41d19 in syscall () from /lib64/libc.so.6
#5  0x00002b985db1ed9d in tbb::internal::futex_wait (comparand=2, futex=0x2b9865f030ac) at ../../include/tbb/machine/linux_common.h:81

Thread 1 (Thread 0x2b9860844180 (LWP 20111)):
#2  0x00002b9869c5456c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  0x00002b9869c55922 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b98909476d0 in (anonymous namespace)::HerwigGenericRun(Herwig::HerwigUI const&, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/external/slc7_amd64_gcc900/lib/libHerwigAPI.so.2
#6  0x00002b9890949757 in Herwig::API::prepareRun(Herwig::HerwigUI const&) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/external/slc7_amd64_gcc900/lib/libHerwigAPI.so.2
#7  0x00002b9890379abd in Herwig7Interface::callHerwigGenerator() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/lib/slc7_amd64_gcc900/libGeneratorInterfaceHerwig7Interface.so
#8  0x00002b9890379cb1 in Herwig7Interface::initGenerator() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/lib/slc7_amd64_gcc900/libGeneratorInterfaceHerwig7Interface.so
#9  0x00002b98903390f4 in Herwig7Hadronizer::initializeForInternalPartons() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/lib/slc7_amd64_gcc900/pluginGeneratorInterfaceHerwig7HadronizerPlugins.so
#10 0x00002b9890346444 in edm::GeneratorFilter<Herwig7Hadronizer, gen::ExternalDecayDriver>::beginLuminosityBlockProduce(edm::LuminosityBlock&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-27-1100/lib/slc7_amd64_gcc900/pluginGeneratorInterfaceHerwig7HadronizerPlugins.so
#11 0x00002b985c488acd in edm::one::EDFilterBase::doBeginLuminosityBlock(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#12 0x00002b985c466d10 in edm::WorkerT<edm::one::EDFilterBase>::implDoBegin(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#13 0x00002b985c370e96 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#14 0x00002b985c37109d in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#15 0x00002b985c371346 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#16 0x00002b985c3718b0 in void edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&) () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#17 0x00002b985c371a61 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#18 0x00002b985c107f49 in tbb::internal::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02678/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-25-0000/lib/slc7_amd64_gcc900/libFWCoreConcurrency.so


Current Modules:
Module: Herwig7GeneratorFilter:generator (crashed)
Module: none
Module: none
Module: none
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-04-27-1100/pyRelValMatrixLogs/run/535.0_TTbar_13TeV_Pow_herwig7+TTbar_13TeV_Pow_herwig7+HARVESTGEN/step1_TTbar_13TeV_Pow_herwig7+TTbar_13TeV_Pow_herwig7+HARVESTGEN.log#/

### PR DESCRIPTION
**Pull request by qliphy**
#### PR description:

Resolves: #33544

#### PR validation:

Pass workflow 535.0

### CODE REVIEW

**Comment by qliphy** [comment]
please test workflow 511.0, 535.0

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
type bugfix

**Pull request merged**
