### PR TITLE
add verbose option to `BeamSpotRcdPrinter` and use it in the unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, in response to https://github.com/cms-sw/cmssw/pull/43265#issuecomment-1812379530

#### PR validation:

Run unit tests of the package  `scram b runtests`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
@mmusich there's a merge conflict now, can you fix? thanks.

**Comment by mmusich** [comment]
>  there's a merge conflict now, can you fix? thanks.

@rappoccio not anymore

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@perrotta you might want to sign again irrespective of the failed test (due to the broken IB). Last push just resolved the merge conflict

**Comment by perrotta** [comment]
> @perrotta you might want to sign again irrespective of the failed test (due to the broken IB). Last push just resolved the merge conflict

Indeed...
And rerunning the tests won't change their outcome, I fear

**Comment by perrotta** [comment]
The failing workflow are not identically the same as the ones failing in the IB. They certainly have the same origin, but let have a look at the new tests just launched first.

**Comment by mmusich** [comment]
> They certainly have the same origin, but let have a look at the new tests just launched first.

There is absolutely no point in that,  as the PR is not touching any code used in relvals. Why are you deliberately delaying the merge here (and many other PRs in the past)?

**Comment by perrotta** [comment]
> There is absolutely no point in that, as the PR is not touching any code used in relvals. Why are you deliberately delaying the merge here (and many other PRs in the past)?

Even if the release managers decide to keep integrating in spite of the storm of errors in the IBs after the last merging of 22 PRs all at once, I imagine that given their time zones none of them two will wake up before 11 am (CET) to integrate new ones in time for the 1100 IB. 

Since you relaunched the tests (unnecessarily, in my opinion) let them finish and have a look at their output, as I am curious to see whether the errors keeps appearing in different workflows as in the IB. (And please don't answer "the tests will finish even if you sign this PR now": I know it)

**Comment by mmusich** [comment]
> , I imagine that given their time zones none of them two will wake up before 11 am (CET) to integrate new ones in time for the 1100 IB.

that's a moot point. This PR is `orp` signed. Once the test finish (I think successfully), this PR will be automatically merged.

**Comment by perrotta** [comment]
+1

**Pull request merged**
