### PR TITLE
Adding the possibility to upload a beamspot payload only every n LS

### PR DESCRIPTION
**Pull request by gennai**
#### PR description:

This PR adds the possibility to upload a new payload only every n LS (and for any LS < n !)
The new default is n = 5, i.e. we produce a payload every 5 LS
#### PR validation:

I have run a modified version of the unitTest to test the intended behavior.

### CODE REVIEW

**Comment by gennai** [comment]
@ggovi @mmusich @francescobrivio you may want to follow this

**Comment by mmusich** [comment]
@gennai thanks, can you change the PR title to be selection explanatory?

**Comment by jfernan2** [comment]
@gennai  since I understand this is affecting Online DQM, would it make sense to test it with current data taking at P5 with a backport ot 12_0_X?
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by gennai** [comment]
> @gennai since I understand this is affecting Online DQM, would it make sense to test it with current data taking at P5 with a backport ot 12_0_X?
> Thanks

To test it properly we need collisions data, that's why I did not propose a back porting yet. In addition we still need to check that for track reconstruction having a new beamspot every 5 LS does not impact the performance (this is our assumption but has to be proven yet).

So for the moment I do not see the reason of a back port.

**Comment by francescobrivio** [comment]
@gennai I'm afraid you missed the spot where the actual upload to the DB is done:
https://github.com/cms-sw/cmssw/blob/7d65b67df69d2b0c989b9ed1cc5797d16fa46624/DQM/BeamMonitor/plugins/BeamMonitor.cc#L1434

**Comment by gennai** [comment]
> @gennai I'm afraid you missed the spot where the actual upload to the DB is done:
> 
> https://github.com/cms-sw/cmssw/blob/7d65b67df69d2b0c989b9ed1cc5797d16fa46624/DQM/BeamMonitor/plugins/BeamMonitor.cc#L1434

you are right. changing it now

**Comment by mmusich** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
Just checking: don't you need to upload the payload for the last LS, even if not multiple of `nLS_for_upload_`?

**Comment by francescobrivio** [comment]
> Just checking: don't you need to upload the payload for the last LS, even if not multiple of `nLS_for_upload_`?

I don't think that is needed, nor technically neither by this new "logic" itself. 
Is there a particular reason why you have this concern?

**Comment by perrotta** [comment]
> > Just checking: don't you need to upload the payload for the last LS, even if not multiple of `nLS_for_upload_`?
> 
> I don't think that is needed, nor technically neither by this new "logic" itself. Is there a particular reason why you have this concern?

I have no concerns, just checking with you and the author whether it was considered needed/welcome...
Let have this merged as such, then

**Comment by perrotta** [comment]
+1

**Pull request merged**
