### PR TITLE
[Phase2 3D digitizer] Fix digi links

### PR DESCRIPTION
**Pull request by duartej**
#### PR description:

A recent modification in the signature of  `DigitizerUtility::Amplitude` (https://github.com/cms-sw/cmssw/commit/158d94357e1a4ca1789f658f3b4e71f554434657,) was not properly propagated into the ```Pixel3DDigitizerAlgorithm``` class, and introduced a bug when linking the simulated energy deposits with the created digi.

Please take a look to the commit https://github.com/cms-sw/cmssw/commit/158d94357e1a4ca1789f658f3b4e71f554434657, for details about the described modifications affecting the pixel3 digi class .

This fix will assign the correct PSimHit. to the created Digi for the pixel 3d digitizer.

The PR also incorporates a fix for a missing entry in the pixel3d digitizer configuration (a fix made by  @mmusich ).

@emiglior and @skinnari as conveners of the simulation/optimisation for phase2 group are aware and agree with this PR. 
Adding @suchandradutta for the concerned modifications.

#### PR validation:
No issues has been spotted during the performed tests (following procedures from https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters
workflow = 24834.0

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
