### PR TITLE
PPSAlCaRecoProducer - minor fixes requested in #36273

### PR DESCRIPTION
**Pull request by MatiXOfficial**
#### PR description:

This PR fixes the minor issues from the discussion in https://github.com/cms-sw/cmssw/pull/36273. The changes are listed below.

- Replaced `cms.InputTag` with regular strings (inside `clone`) in `ALCARECOPPSCalMaxTracks_cff.py`.
- Deleted `hlt_out_singleRAW.py` and `setup_dev_CMSSW_12_1_0_GRun_V14_cff.py`. They were not necessary for the unit tests in the `test` folder.
- Deleted `hltEventAnalyzerAOD` from the `prompt_PPSAlCaReco_output` test. It was not necessary for that test and made the output verbose. Also, there are no `0 accepted 'L3' objects found` messages anymore.

#### PR validation:

- The unit tests pass.

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 1041, 1042

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by MatiXOfficial** [comment]
> @MatiXOfficial thanks for this, can you please modify the title to be a bit more specific?

@tvami I hope it's better now :)

**Comment by tvami** [comment]
+alca
 * fixes from prev request
 * no diffs in the Jenkins are found

**Comment by perrotta** [comment]
+1

**Pull request merged**
