### PR TITLE
Apply a "boundary condition" at the outermost pseudorapidity edges

### PR DESCRIPTION
**Pull request by yslai**
This bugfix fixes very large (but not infinite) areas that stretches outside the HF by surrounding the event with "mirror events". This is to prevent rare instances, where FastJet would cluster negative pT particles over large distances, and a large, negative particle become a jet in the opposite direction.

Also, the printf() have been converted to EDM log messages.

No performance difference is expected, except for jets either at |eta| ~ 5, or rare events that previously would have contained unreasonably large jet pTs (e.g. 10 TeV).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@yslai: I would like the static analyzer warnings taken care of, but it is not clear what is the best way to do it. If you have ideas about how to fix them, please comment. We are investigating the issues.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12463/9787/llvm-analysis/

**Comment by cvuosalo** [comment]
It looks like the static analyzer warnings can't easily be eliminated because they are caused by the interface to a legacy module. We probably have to just ignore them for now.

**Comment by cvuosalo** [comment]
+1

For #12463 cba4555f5dd20f11760311ec182e4beacbf8979e

Fix for Heavy Ions jets at the outermost pseudorapidity edges to prevent clustering of negative pT particles over large distances. #12464 is the 75X version of this PR, and it has already been merged.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_7_6_X_2015-11-15-1100 show the expected differences in jets with |eta| around 5 and the elimination of jets with negative pT of large magnitude in the comparisons for workflow 140.53_RunHI2011. See #12464 for example plots of the changes.

**Comment by slava77** [comment]
@yslai please make a PR for 80X.

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
