### PR TITLE
Code changes for Protobuf 3.21.9 and TensorFlow 2.12

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Companion PR for https://github.com/cms-sw/cmsdist/pull/8565

#### PR validation:

Tests in https://github.com/cms-sw/cmsdist/pull/8565

### CODE REVIEW

**Comment by iarspider** [comment]
code-checks with cms.week1.PR_78d7858e/57.0-3187777e8b462de4843bc3736a08b743

**Comment by iarspider** [comment]
code-checks with cms.week1.PR_78d7858e/57.0-3187777e8b462de4843bc3736a08b743

**Comment by iarspider** [comment]
code-checks with cms.week1.PR_78d7858e/57.0-3187777e8b462de4843bc3736a08b743

**Comment by iarspider** [comment]
type bugfix
@cms-sw/dqm-l2 @cms-sw/tests-l2 @cms-sw/reconstruction-l2 this is ready for review.

**Comment by emanueleusai** [comment]
please test

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8565

**Comment by emanueleusai** [comment]
+1

- DQM differences in Tracking, Btag, etc do no seem related to this PR

**Comment by iarspider** [comment]
@cms-sw/reconstruction-l2 gentle ping. This is also needed for gcc13 and cpp20 IBs.

**Comment by clacaputo** [comment]
+reconstruction

**Comment by smuzaffar** [comment]
@perrotta @rappoccio , this should go in along with https://github.com/cms-sw/cmsdist/pull/8565

**Comment by perrotta** [comment]
@cms-sw/reconstruction-l2 are differences in reco/DQM outputs understood and/or accepted?

**Comment by perrotta** [comment]
+1

**Pull request merged**
