### PR TITLE
[HeaderCheck][Reco] RecoVertex/MultiVertexFit

### PR DESCRIPTION
**Pull request by mrodozov**
- Remove unused header

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
this comes with RecoVertex/MultiVertexFit/src/LinPtFinderFromAdaptiveFitter.cc
Please remove that as well.

**Comment by mrodozov** [comment]
please test

**Comment by perrotta** [comment]
+1
- The removed files are really obsolete: they also depend on a Vertex/LinearizationPointFinders package which does not exist in CMSSW since a while
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
