### PR TITLE
[101X][L1T][DQMOffline] Tau DQM updates (CMSLITDPG-590)

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23673

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @jfernan2 @dmitrijus 
can you please sign this backport PR?

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
since the T0 has moved to the 10_2 release now this PR can be closed.

**Pull request closed without merging**
