### PR TITLE
Added esConsumes to SiPixelRecHitConverter

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
In addition, consolidated header and source file as well as some code modernization and naming consistency.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29914	afb139e 
- code changes are technical,  in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
    - differences in comparisons are from #29764 also included in the tests

**Comment by silviodonato** [comment]
+1

**Pull request merged**
