### PR TITLE
Bianca pinolini ecal reco phase2 commit unimib

### PR DESCRIPTION
**Pull request by BiancaPinolini**
The necessary files to implement the amplitude reconstruction for Ecal-Phase2 through the weights method has been added.

### CODE REVIEW

**Comment by silviodonato** [comment]
@BiancaPinolini you are making many changes (see https://github.com/cms-sw/cmssw/pull/34212/files). I suspect you made this PR starting from a wrong release. The current master branch in 12_0_X (the last integration build release is CMSSW_12_0_X_2021-06-22-1100)

**Comment by slava77** [comment]
-1

wrong target branch (or perhaps even wrong target repo)

**Comment by slava77** [comment]
-1

looks broken

**Comment by Martin-Grunewald** [comment]
-1
(to remove from HLT queue)

**Comment by slava77** [comment]
-1

looks broken

**Comment by thomreis** [comment]
Hi @BiancaPinolini I think you can close this PR in favour of #34505

**Comment by Martin-Grunewald** [comment]
-1
to remove from HLT queue - please rebase properly!

**Comment by tvami** [comment]
-1 
to remove from AlCa queue, the PR is anyway to be closed since an alternative PR exists

**Pull request closed without merging**
