### PR TITLE
Removing assert to address the issue #35668

### PR DESCRIPTION
**Pull request by tsusa**
#### PR description:

This PR comments the assert statement in order to address the issue https://github.com/cms-sw/cmssw/issues/35668.

The assert statement checks if the clusters on one detId are stored by increasing clust.originalId(). That is true for Legacy clusters coming from the Legacy Clusterizer, however if the Legacy clusters are output by SiPixelDigisClustersFromSoA that is no more true and the assert fails.

#### PR validation:

Run wfs 11634.501, 11634.502 (on CPU and GPU), 11634.506 and 
hltGetConfiguration /dev/CMSSW_12_3_0/GRun --globaltag 122X_mcRun3_2021_realistic_v5 --mc --customise HLTrigger/Configuration/customizeHLTforPatatrack.customiseCommon,HLTrigger/Configuration/customizeHLTforPatatrack.customisePixelLocalReconstruction --input file:/eos/cms/store/relval/CMSSW_12_3_0_pre2/RelValQCD_FlatPt_15_3000HS_14/GEN-SIM-DIGI-RAW/122X_mcRun3_2021_realistic_v5-v1/2580000/9681546e-e170-41e0-aca3-280a014ba2cc.root --era Run3 --output minimal --max-events 1 > hlt.py

All work fine.

### CODE REVIEW

**Comment by jpata** [comment]
perhaps remove it altogether, rather than commenting out?

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by sroychow** [comment]
enable gpu

**Comment by jpata** [comment]
+reconstruction
- technical, removes the assert, which is [known](https://github.com/cms-sw/cmssw/issues/35668#issuecomment-1063925168) not to be satisfiable

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@sroychow @tsusa does this need to be backported? 
(thinking about a possible backport of https://github.com/cms-sw/cmssw/pull/37174 which was stated targeting 12_3_X: https://github.com/cms-sw/cmssw/pull/37174#issuecomment-1061870053)

**Comment by sroychow** [comment]
@mmusich I think yes. The DQM PR is still to be merged in master. I can make backports for both these PR.

**Pull request merged**
