### PR TITLE
HLT menu development for `14_0_X` (10/N) 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46048

#### PR description:

Development of HLT menus for `CMSSW_14_0_X` (this is the release cycle currently used for Run-3 HLT-menu development).
   * These updates correspond to the changes accumulated in the 14_0_X release cycle after the "V1.4" (last) menu for the 2024 pp data-taking period was released, and target the 2024 HIon and PRef data-taking as well as the first pp menu for 2025.
   
This update includes the integration of the following JIRA tickets:

- [CMSHLT-3296](https://its.cern.ch/jira/browse/CMSHLT-3296) [TSG] Remove unused Paths of the Special table
- [CMSHLT-3298](https://its.cern.ch/jira/browse/CMSHLT-3298) [TSG] Remove suppression of warnings and errors from HLT MessageLogger for `hltOnlineBeamSpot`
- [CMSHLT-3303](https://its.cern.ch/jira/browse/CMSHLT-3303) [EXO] Add missing `hltIter2MergedForDisplaced` from HLTMonitor event content
- [CMSHLT-3310](https://its.cern.ch/jira/browse/CMSHLT-3310) [TSG] Update to 2024 eras in TSG tests
- [CMSHLT-3306](https://its.cern.ch/jira/browse/CMSHLT-3306) [HIon/DQM] Review of HIDQM EventContent (HI Run 2024)
- [CMSHLT-3307](https://its.cern.ch/jira/browse/CMSHLT-3307) [BRIL] Update "LumiScan" offline menu (post Run2024G)
- [CMSHLT-3329](https://its.cern.ch/jira/browse/CMSHLT-3329) [Egamma/PF]  Fix mismatch of EB and EE recHits in supercluster producer modules
- [CMSHLT-3284](https://its.cern.ch/jira/browse/CMSHLT-3284) [HIon/TRK] Move to Pixel-Alpaka modules in the HIon menu
- [CMSHLT-3309](https://its.cern.ch/jira/browse/CMSHLT-3309) [DQM] Update DeltaR matching cut for `hltPixelTracksSoACompareGPUvsCPU` and `hltSiPixelTracksSoACompareGPUvsCPUPPOnAA`
- [CMSHLT-3323](https://its.cern.ch/jira/browse/CMSHLT-3323) [HIon] Muon Triggers for pp Reference Run 2024
- [CMSHLT-3332](https://its.cern.ch/jira/browse/CMSHLT-3332) [DQM] Fix inconsistent module labels for `HLTDQMPixelReconstruction` vs `HLTDQMPixelReconstructionPPOnAA`

In addition, the following changes are included:
   * aa33888007db3ffbb22385ca23ace4c8c6b0f477 update of L1T PRef menu in TSG GTs to `L1Menu_CollisionsPPRef2024_v0_0_2_xml`

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/46048 to the 2024 pp production cycle (CMSSW_14_0_X)

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/45959

**Comment by mmusich** [comment]
test parameters:
   * workflow = 142.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/45959

**Comment by mmusich** [comment]
+hlt
   * changes observed in the HLT EXO DQM output (https://github.com/cms-sw/cmssw/pull/46050#issuecomment-2362402181) are due to the integration of [CMSHLT-3303](https://its.cern.ch/jira/browse/CMSHLT-3303)
   * changes observed in the HLT tracking  DQM output of wf 142.0 (https://tinyurl.com/2xjrm6zo) is due to the integration of [CMSHLT-3284](https://its.cern.ch/jira/browse/CMSHLT-3284)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
