### PR TITLE
Run4-hgx282Z Remove overlaps in the V15 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove overlaps in the V15 geometry of HGCal

#### PR validation:

Checked using the overlap tool and also with the workflow 37434.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
Please test workflow 37434.0

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
test parameters:

- workflow = 37434.0

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
I just check for the affected workflow, no issue is expected.

**Comment by srimanob** [comment]
+Upgrade

This PR is to remove overlaps in the V15 HGCal geometry. The affected workflow of D83 run successfully.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
