### PR TITLE
L1T offline DQM - Run L1T emulator sequences before the DQM modules - 102x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #24578 

The revert from PR #24552 is undone before adding the fix for the initial problem.

The L1T emulators should run before the offline L1T DQM modules that use them.
This PR places the required sequences in front of the modules.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1
Changes in the DQM are expected since new checks are added.

**Comment by andrius-k** [comment]
@thomreis The changes seem to be different between this PR and the original one. Are you it is only because of the fact that bases of these two PRs are different?

**Comment by thomreis** [comment]
This PR also contains the changes from PR #24291 that were reverted in PR #24552 .
This revert did not happen in the master branch and that is the reason for the difference.

**Comment by andrius-k** [comment]
+1
@thomreis ok, cool.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
@andrius-k please sign again.
The last commit just deals with removing warning messages.

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
Hi @thomreis, as 10_2 is no longer being used maybe this PR should be closed?

**Pull request closed without merging**
