### PR TITLE
update MC GTs with conditions validated for MC Tranche-IV and prepare for 2016 data reprocessing

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Proton-Lead scenario** : [81X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v1) as [81X_mcRun2_pA_Candidate_2016_08_30_11_39_33](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_Candidate_2016_08_30_11_39_33) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_pA_v1/81X_mcRun2_pA_Candidate_2016_08_30_11_39_33): 
  - updated Tracker misalignment scenario (after Bpix centering)
  - updated Beamspot following tracker alignment update 
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v6) as [81X_mcRun2cosmics_startup_peak_Candidate_2016_08_30_11_36_42](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_Candidate_2016_08_30_11_36_42) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v6/81X_mcRun2cosmics_startup_peak_Candidate_2016_08_30_11_36_42): 
  -  reverting spurious change of misalignment scenario (Startup scenario is needed here) introduced in #15658
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v6) as [81X_mcRun2_asymptotic_Candidate_2016_08_30_11_31_55](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_Candidate_2016_08_30_11_31_55) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v6/81X_mcRun2_asymptotic_Candidate_2016_08_30_11_31_55): 
  - updated Tracker misalignment scenario (after Bpix centering)
  - updated Beamspot following tracker alignment update 
- **RunII Startup scenario** : [81X_mcRun2_startup_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v8) as [81X_mcRun2_startup_Candidate_2016_08_30_11_37_42](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_Candidate_2016_08_30_11_37_42) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v8/81X_mcRun2_startup_Candidate_2016_08_30_11_37_42): 
  - just nomenclature change: no actual change of content
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v7) as [81X_mcRun2_HeavyIon_Candidate_2016_08_30_11_38_26](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_Candidate_2016_08_30_11_38_26) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v7/81X_mcRun2_HeavyIon_Candidate_2016_08_30_11_38_26): 
  - just nomenclature change: no actual change of content
## RunII data
- **RunII Offline processing** : [81X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v6) as [81X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v6/81X_dataRun2_v5): 
  - updated AlCaRecoTriggerBits to allow creation of Run2 version of wf 1000.0 and 1001.0 
  - fixed history of ES channel status 
  - fixed history of Hcal channel status 
  - fixed history of Strip DetVOff 
  - updated Tracker Alignment with time-dependent PCL updates on top of 2016B re-reco geometry 
- **RunII Offline relval processing** : [81X_dataRun2_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v7) as [81X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v7/81X_dataRun2_relval_v6): 
  - updated AlCaRecoTriggerBits to allow creation of Run2 version of wf 1000.0 and 1001.0 
  - fixed history of ES channel status 
  - fixed history of Hcal channel status 
  - fixed history of Strip DetVOff 
  - updated Tracker Alignment with time-dependent PCL updates on top of 2016B re-reco geometry 
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v10) as [81X_upgrade2017_realistic_Candidate_2016_08_30_11_40_18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_Candidate_2016_08_30_11_40_18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v10/81X_upgrade2017_realistic_Candidate_2016_08_30_11_40_18): 
  - just nomenclature change: no actual change of content

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
