### PR TITLE
Phase2:hgx104 Change std::vector to std::unordered_set for storing valid detId's

### PR DESCRIPTION
**Pull request by bsunanda**
This is the PR #22287 without the change in DetId class

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you include your comments for #22287 here

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
@bsunanda : any progress on fixing https://github.com/cms-sw/cmssw/pull/22673#issuecomment-374606873 ?

**Comment by civanch** [comment]
@bsunanda , is there some numbers, which demonstrate the efficiency of usage of "set" instead of "vector"?

**Comment by perrotta** [comment]
@bsunanda: this PR looks like being unattended since two weeks already. What is the status?

**Comment by bsunanda** [comment]
I am not so sure if this PR has something to do with muon reconstruction. It can only affect accessing valid ID's of calorimeter cells. So I am surprised. May be I shall make a new test to see what happens.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by drkovalskyi** [comment]
@bsunanda you are changing a low level code. You need to check out all the dependent packages and propagate the change (that would included muon reco among other packages). So far there was no justification provided for the change I hope we won't blindly accept this change since it may require non-trivial validation.

**Comment by perrotta** [comment]
Still there: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-04-02-2300+22673/25959/validateJR/all_OldVSNew_RunSinglePh2017B136p788/all_OldVSNew_RunSinglePh2017B136p788c_recoMuons_muons__reRECO_obj_eta34.png

image

**Comment by bsunanda** [comment]
@perrotta Could you let me know which example creates this?

**Comment by perrotta** [comment]
@bsunanda : as the link says, that was step3 of wf 136.788 (SinglePh2017B)

But as far as I can see, tracker muons look broken in all workflows, e.g TTbar MC 13 TeV 2017 in wf 10024:
immagine

**Comment by perrotta** [comment]
-1
In order to remove from the list of the reco pending PRs until the following points are all addressed and solved:
- A rebase is needed
- The issue with the tracker muons has to be traced and fixed
- Questions and remarks received so far in the review must be addressed; in particular it must be demonstrated the advantage of making the change

**Comment by ianna** [comment]
-1

Please, rebase and provide performance comparison plots

**Comment by arunhep** [comment]
-1

**Comment by fabiocos** [comment]
@bsunanda what is the planned activity on this PR?

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fabiocos** [comment]
@bsunanda sorry, is there a plan to update this PR?

**Comment by fabiocos** [comment]
@bsunanda could you please clarify the status and future of this PR? Should we just considered this as obsolete and to be closed?

**Comment by bsunanda** [comment]
Cannot be easily resolved. Closing for the time being. Shall relook after HGCal geometry changes are completed.

**Pull request closed without merging**
