### PR TITLE
Minor update in the CSC/GEM-CSC trigger for Run-3: split regular ALCT-CLCT off from ALCT-CLCT-GEM matching

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In this PR I put the ALCT-CLCT matching in a separate function `matchALCTCLCT`, so it can be reused in the CSCGEMMotherboard class. Reason is that the CSCGEMMotherboard builds LCTs in Run-3 according to the following priority: (1) ALCT-CLCT-2GEM (2) ALCT-CLCT-1GEM (3) ALCT-CLCT (4) CLCT-2GEM (5) ALCT-2GEM. Previously step (3) was taken together with (1) and (2), but they should be independent. This is because all options except (3) can be switched off. (3) is always on.

#### PR validation:

Tested with Run-3 single muon guns.

Also tested on 26k events of 2018D ZeroBias. 
[CSC_dataVsEmul_CMS_Run_322022_PR36046.pdf](https://github.com/cms-sw/cmssw/files/7622382/CSC_dataVsEmul_CMS_Run_322022_PR36046.pdf)

The instructions are: 
```
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py l1=True mc=False maxEvents=10000 \
run3=False dqm=True unpack=True \
inputFiles=file:A82FA3CF-86AD-E811-B097-FA163E0F0F4B.root,file:C69DD8C2-86AD-E811-BE39-FA163E8EFCB8.root,file:F87A285E-87AD-E811-89A7-FA163E0481A2.root,file:18B49402-90AE-E811-972C-FA163E3D0B36.root \
selectCSCs=True

cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCL1TDQMClient_cfg.py mc=False run3=False

RunNumberLabel="322022";
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveAnalyzer_cfg.py \
dataVsEmulation=True dataVsEmulationFile="file:DQM_V0001_R000322022__Global__CMSSW_X_Y_Z__RECO.root" runNumber=$RunNumberLabel
```
where the 4 ROOT files are 2018D EDM RAW data files from the ZeroBias dataset.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991 @giovanni-mocellin @rathjd

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
@dildick @rekovic are the differences visible in the MuonCSCDigisV/CSCDigiTask/LCT DQM outputs in accord with this PR?

See:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2021-11-17-2300+f97ae4/46917/35234.999_TTbar_14TeV+2026D77PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/MuonCSCDigisV_CSCDigiTask_LCT_Occupancy.html

**Comment by perrotta** [comment]
The static analyzer run for this PR points out to a rather obvious bug in CSCGEMMatcher::calculateGEMCSCBending
I have prepared a fix with #36216. You can also include that commit in this PR, if you think so.
But if you believe that this PR is ready to go (it depends on the answer to the [previous question](https://github.com/cms-sw/cmssw/pull/36046#issuecomment-976547076) of mine), the fix can be merged next with my #36216

**Comment by dildick** [comment]
@perrotta yes. This PR is good to go. There should be minor updates following tests with the B904 test-stand, but the design is pretty close to the firmware now for the GE1/1-ME1/1 algorithm

**Comment by perrotta** [comment]
> @perrotta yes. This PR is good to go. There should be minor updates following tests with the B904 test-stand, but the design is pretty close to the firmware now for the GE1/1-ME1/1 algorithm

Thank you @dildick 
Can you then explicitely confirm that the changes in the  MuonCSCDigisV/CSCDigiTask/LCT DQM outputs are as expected, as for example the following one?
image

**Comment by perrotta** [comment]
@dildick (just in case you have missed it): before merging this PR in the release I'm waiting for an explicit confirmation from you that the modifications that are visible in the CSC DQM plots are expected given the changes integrated here.

**Comment by qliphy** [comment]
@dildick  Can you address above comment?

**Comment by dildick** [comment]
@qliphy I recently put in this PR https://github.com/cms-sw/cmssw/pull/36224 to understand better which types of LCTs are being produced. Can you rerun the tests again?

**Comment by qliphy** [comment]
please test

**Comment by dildick** [comment]
@perrotta Some comparison plots from WF 35234.999

Screen Shot 2021-11-29 at 9 04 05 AM
Screen Shot 2021-11-29 at 9 04 21 AM
Screen Shot 2021-11-29 at 9 07 20 AM
Screen Shot 2021-11-29 at 9 07 28 AM

It seems that the number of LCTs increases after the PR. The producer is picking up additional LCTs that were missed in certain bunch crossings. But they appear all of type ALCT-CLCT (which is the regular kind) in ME1/1. LCTs of type ALCT-CLCT-GEM or ALCT-CLCT-2GEM should not necessarily have been removed from the final selection. I will look into it today.

**Comment by dildick** [comment]
Okay now I see. The `lct_type` plot is quite useful.

I added some printouts to the motherboards. In WF 35234.999 I notice that the ALCT-CLCT finding is run on those BXs in which ALCT-CLCT-GEM ILTs were found previously. So a bunch crossing mask in the `CSCMotherboard` is missing (I have this mask elsewhere already). In the printout below `matchALCTCLCT` should not be called for BX8, and `FINAL` should be the same as `matchALCTCLCTGEM`
```
Running GEMCSC ILT in ME-1/1/21
matchALCTCLCTGEM CSC LCT #1: Valid = 1 BX = 8 Pattern = 8 Quality = 14 Bend = 0
 KeyHalfStrip = 84 KeyWireGroup = 22 Type (SIM) = 3 MPC Link = 0

matchALCTCLCT CSC LCT #1: Valid = 1 BX = 8 Pattern = 8 Quality = 6 Bend = 0
 KeyHalfStrip = 84 KeyWireGroup = 22 Type (SIM) = 1 MPC Link = 0

FINAL CSC LCT #1: Valid = 1 BX = 8 Pattern = 8 Quality = 6 Bend = 0
 KeyHalfStrip = 84 KeyWireGroup = 22 Type (SIM) = 1 MPC Link = 0
```

**Comment by dildick** [comment]
What I also don't like is this: quality 6 LCTs. The low-quality CLCTs (with 3 layers) should not be selected for regular LCTs (in case no GEM-CSC ILT was found).
```
Running GEMCSC ILT in ME+1/1/25
matchALCTCLCT CSC LCT #1: Valid = 1 BX = 6 Pattern = 9 Quality = 6 Bend = 1
 KeyHalfStrip = 177 KeyWireGroup = 0 Type (SIM) = 1 MPC Link = 0

FINAL CSC LCT #1: Valid = 1 BX = 6 Pattern = 9 Quality = 6 Bend = 1
 KeyHalfStrip = 177 KeyWireGroup = 0 Type (SIM) = 1 MPC Link = 0
```

**Comment by dildick** [comment]
(update a commit message)

@perrotta I'll run the original emulator on data to show that the regular ALCT-CLCT algorithm works as expected.

**Comment by perrotta** [comment]
please test
(thank you @dildick )

**Comment by dildick** [comment]
Much better results! A few differences in WF 11634.911 and 35234.999 that can readily be explained as: removal of low-quality LCTs in emulation that should not have been produced.

A few screenshots of WF 35234.999:

Screen Shot 2021-11-29 at 7 07 51 PM
Screen Shot 2021-11-29 at 7 07 56 PM
Screen Shot 2021-11-29 at 7 08 00 PM

These quality 6 LCTs (4-layer ALCT + 3-layer CLCT) should not be produced (if no GEMs were matched). No GEMs were matched for them, since they are all of type ALCT-CLCT (the regular kind).

Screen Shot 2021-11-29 at 7 07 21 PM
Screen Shot 2021-11-29 at 7 07 27 PM
Screen Shot 2021-11-29 at 7 07 31 PM

These plots show you where in BX the low-quality LCTs were. BX8 means in-time (see LCT_CENTRAL_BX in DataFormats/CSCDigi/interface/CSCConstants.h). The LCTs in ME1/1 were removed in out-of-time BXs. In ME2/1 it concerns 1 in-time LCT.

Screen Shot 2021-11-29 at 7 07 04 PM
Screen Shot 2021-11-29 at 7 07 35 PM
Screen Shot 2021-11-29 at 7 07 40 PM

PR #36224 that plots the type of LCT in emulation was very useful. Unfortunately it's not something that is readily available in the CSC DAQ data for Run-2. In Run-3 we will have a modified LCT quality for ME1/1 that tells you what kind of LCT was made (see https://gitlab.cern.ch/tdr/notes/DN-20-016/blob/master/temp/DN-20-016_temp.pdf for details).

**Comment by dildick** [comment]
I also analyzed 26k events of Run 322022 (2018D) excluding ME+1/1/9, ME+1/1/10, ME+1/1/11 (where we had downloaded experimental CSC firmware for HL-LHC). 

Results:
[CSC_dataVsEmul_CMS_Run_322022_PR36046.pdf](https://github.com/cms-sw/cmssw/files/7622194/CSC_dataVsEmul_CMS_Run_322022_PR36046.pdf)

A few screenshots for ME1/1 (which gathers most statistics)
Screen Shot 2021-11-29 at 7 21 34 PM
Screen Shot 2021-11-29 at 7 21 47 PM
Screen Shot 2021-11-29 at 7 22 04 PM
Screen Shot 2021-11-29 at 7 22 12 PM
Screen Shot 2021-11-29 at 7 22 28 PM

**Comment by dildick** [comment]
The last commit is simply an update of the test configuration with which I made the plots. The instructions themselves are: 
```
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py l1=True mc=False maxEvents=10000 \
run3=False dqm=True unpack=True \
inputFiles=file:A82FA3CF-86AD-E811-B097-FA163E0F0F4B.root,file:C69DD8C2-86AD-E811-BE39-FA163E8EFCB8.root,file:F87A285E-87AD-E811-89A7-FA163E0481A2.root,file:18B49402-90AE-E811-972C-FA163E3D0B36.root \
selectCSCs=True

cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCL1TDQMClient_cfg.py mc=False run3=False

RunNumberLabel="322022";
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveAnalyzer_cfg.py \
dataVsEmulation=True dataVsEmulationFile="file:DQM_V0001_R000322022__Global__CMSSW_X_Y_Z__RECO.root" runNumber=$RunNumberLabel
```
where the 4 ROOT files are 2018D EDM RAW data files from the ZeroBias dataset.

**Comment by dildick** [comment]
Next, I'll cherry-pick https://github.com/cms-sw/cmssw/pull/36226 and to see if I can't get a few nice 2D data-vs-emulation plots

**Comment by dildick** [comment]
A few nice 2D plots from Run 322022 below. I did have to set the minimum value a bit higher to make the contrast. 

Screen Shot 2021-11-29 at 8 24 22 PM
Screen Shot 2021-11-29 at 8 22 38 PM
Screen Shot 2021-11-29 at 8 24 44 PM
Screen Shot 2021-11-29 at 8 24 56 PM
Screen Shot 2021-11-29 at 8 26 34 PM
Screen Shot 2021-11-29 at 8 27 21 PM

**Comment by dildick** [comment]
Closer look at ME1/1 with different minima:

* 95%
Screen Shot 2021-11-29 at 8 35 43 PM

* 99%
Screen Shot 2021-11-29 at 8 26 34 PM

* 99.9% (ME1/1 and other MEX/1 chambers fall below this threshold)
Screen Shot 2021-11-29 at 8 40 34 PM

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
Thanks @jfernan2! Differences in the WF comparisons are the same as before: the low-quality LCTs (quality 6) are intentionally removed and this shows up in WFs with pileup 11634.911 and 35234.999.

**Comment by dildick** [comment]
@rekovic Can this PR be signed off? Thanks!

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
Ready for merging. Please merge this PR and 36223.

**Comment by rekovic** [comment]
After merging the two above mentioned PRs, we can sign and merge #36018. 
Thanks.

**Comment by perrotta** [comment]
+1

**Pull request merged**
