### PR TITLE
Some more python 2to3 fixes for HLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Some more python 2to3 fixes for HLT

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
urgent

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
Failure unrelated to this PR, also in baseline IB CMSSW_12_0_X_2021-07-21-2300.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test with PR #34534

**Comment by Martin-Grunewald** [comment]
please test with #34534

**Comment by perrotta** [comment]
please test
(The "clean" CMSSW_12_0_X_2021-07-22-1700 IB should be available as baseline for tests now)

**Comment by qliphy** [comment]
please test

**Comment by Martin-Grunewald** [comment]
There must be a problem with the PR test infrastructure - this PR could not possibly create such errors in the PR tests...

**Comment by qliphy** [comment]
It is time out issue
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3026dc/17126/runTheMatrixINPUT-results/11601.0_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_SingleElectronPt10+2021+SingleElectronPt10_pythia8_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log

also appeared in the IB: CMSSW_12_0_X_2021-07-22-1700

Let's re-trigger the test with new IB

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
