### PR TITLE
fix harvesting configuration for T0

### PR DESCRIPTION
**Pull request by deguio**
not sure why the saveByLumiSection option was activated for the T0 harvesting. this is wrong and cause a crash when combined to the recent development to the DQMFileSaver class.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
looks like saveByLumiSection is there since run 1

**Comment by deguio** [comment]
ciao @davidlange6 
correct, but it is not needed. we save by lumi only on the HLT FUs.

**Pull request merged**
