### PR TITLE
Compute muon index bits using idx from dataformat

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

We currently compute the muon index within the link from the position in the vector, however this is packed densely and during cosmics the EMTF always sends muon stubs in third position (even if the second position is free), causing a mismatch in index bits. 

Therefore we now assign the muon index on the link in the uGMT unpacker and use that index if it is set. The behaviour when the `muIdx` field is not explicitly set should be identical to the current one.

#### PR validation:

Running the usual standard tests locally. (WIP until they succeed.)

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by dinyar** [comment]
Ok, for me this looks like no changes were seen in the tests which is expected. The only place we should see differences is during cosmics data taking in the data-emulator comparisons.

Once this is merged I'd like to have this in the online DQM if that's possible. @jfernan2, can you let me know if that would be fine?

Cheers,
Dinyar

**Comment by jfernan2** [comment]
Hi, yes, it is possible, but we'd better coordinate with @pmandrik @emanueleusai, @ahmad3213 @micsucmed @rvenditti   who are the DQM responsibles.
You will need to backport in a PR these changes anyway to 12_3_X which is the version used right now in Online. 
Besides, to keep the code in sync, another PR backporting to 12_4_X would be fine, to not lose the changes when Online moves to that release in a near future. Thanks

**Comment by dinyar** [comment]
> Hi, yes, it is possible, but we'd better coordinate with @pmandrik @emanueleusai, @ahmad3213 @micsucmed @rvenditti who are the DQM responsibles. You will need to backport in a PR these changes anyway to 12_3_X which is the version used right now in Online. Besides, to keep the code in sync, another PR backporting to 12_4_X would be fine, to not lose the changes when Online moves to that release in a near future. Thanks

Ok, thanks for the information. Backports made at #38116 and #38117.

**Comment by epalencia** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
