### PR TITLE
Run3-gex98B Use ESGetToken in EDAnalyzers of SimTracker/SiPhase2Digitizer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in EDAnalyzers of SimTracker/SiPhase2Digitizer

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@AdrianoDee, @srimanob Please approve this

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Technical PR on esConsumes migration. No change is expected.

**Comment by qliphy** [comment]
+1

**Pull request merged**
