### PR TITLE
Adding L1 menu and Hcal Negative energy filter in GT

### PR DESCRIPTION
**Pull request by mmusich**
## List of Changes
- Run1 ideal simulation: as `DESRUN1_74_V6` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/DESRUN1_74_V7/DESRUN1_74_V6))  with:
  - new HCAL negative energy filter.
- Run1 realistic simulation: as `MCRUN1_74_V6` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCRUN1_74_V7/MCRUN1_74_V6)) with:
  - new HCAL negative energy filter.
- Run1 Heavy Ion simulation: as `MCHI1_74_V6` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCHI1_74_V7/MCHI1_74_V6)) with:
  - new HCAL negative energy filter.
- Run1 proton-lead simulation: as`MCPA1_74_V6` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCPA1_74_V7/MCPA1_74_V6)) with:
  - new HCAL negative energy filter.
- Run2 design simulation: as `DESRUN2_74_V4` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/DESRUN2_74_V5/DESRUN2_74_V4)) with:
  - new HCAL negative energy filter.
  - updated L1T menu for 25 ns collisions: `Collisions2015_25ns_v2_L1T_Scales_20141121_Imp0_0x1030` (already in release as XML file consumed via customise function).
- Run2 startup simulation: as `MCRUN2_74_V8` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCRUN2_74_V10/MCRUN2_74_V8)) with:
  - new HCAL negative energy filter.
  - updated L1T menu for 50 ns collisions: `Collisions2015_50nsGct_v1_L1T_Scales_20141121_Imp0_0x1030` (already in release as XML file consumed via customise function).
- Run2 asymptotic simulation: as `MCRUN2_74_V9` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCRUN2_74_V11/MCRUN2_74_V9))  with:
  - new HCAL negative energy filter.
  - updated L1T menu for 25 ns collisions: `Collisions2015_25ns_v2_L1T_Scales_20141121_Imp0_0x1030` (already in release as XML file consumed via customise function).
- Run2 Heavy Ion simulation: as `MCHI2_74_V5` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/MCHI2_74_V6/MCHI2_74_V5)) with:
  - new HCAL negative energy filter.
  - updated L1T menu for Heavy Ion collisions `CollisionsHeavyIons2011_v0_nobsc_notau_centrality_q2_singletrack.v1` (already in release as XML file consumed via customise function)
- Run1 Data processing: as `GR_R_74_V12` ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/GR_R_74_V14/GR_R_74_V12)) with:
  - new HCAL negative energy filter.
- Run2 Data processing: as `GR_R_74_V13`  ([browser](https://cms-conddb.cern.ch/browser/#diff/gts/GR_R_74_V15/GR_R_74_V13)) with:
  - new HCAL negative energy filter.

---

No changes in HLT run1 and run2 data processing

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please aknowledge changes

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
What about the GTs for 75X and 76X?

**Comment by mmusich** [comment]
@Martin-Grunewald 75X is almost ok already now. We need to update the startup one. Will come together with other changes.

**Comment by Martin-Grunewald** [comment]
@mmusich 
There is a further problem in that the new HIon GT does not seem to exist:
```
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
----- Begin Fatal Exception 14-Jul-2015 16:58:11 CEST-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
Global Tag "MCHI2_74_V6" has not been found in the database. from GTProxy::load 
----- End Fatal Exception -------------------------------------------------
```
Maybe a typo?

**Comment by mmusich** [comment]
@Martin-Grunewald: no, there was indeed no GT named `MCHI2_74_V6` (forgot to migrate to condDBv2).
Now it exists: https://cms-conddb.cern.ch/browser/#list/gts/MCHI2_74_V6

**Comment by mmusich** [comment]
please test

**Comment by mulhearn** [comment]
I found the problem...

**Comment by mulhearn** [comment]
It seems the PAT tests are still using cond db v1 unlike the standard work flows.  Now I don't know why (DB expert will have to explain) but extracting the Trigger Menu in the latest GT from cond db v1 does not work.  I have a small patch to the PAT tuple to switch them to v2 and this test passes.

**Comment by mulhearn** [comment]
I'll make a separate PR to demonstrate.

**Comment by diguida** [comment]
@cmsbuild please notice the changes

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@monttj @vadler can you please review and sign? I believe it's a step forward in making the unit tests meaningful

**Comment by Martin-Grunewald** [comment]
@monttj @vadler 
What is holding up this PR?

**Comment by mmusich** [comment]
@davidlange6 would it be possible to merge without waiting for the analysis signatures? Looks to me the change is trivial and goes in the direction of getting free of spurious  condDBv1 dependencies.

**Pull request merged**
