### PR TITLE
HGCal EGamma Fake Control - Cluster Hadronic Energy Fraction Cut (81X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #16800

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@kpedro88 do we need this in 81X patches?
If not, I propose to close this PR.

**Comment by kpedro88** [comment]
If we no longer plan to run Phase2 w/ PU200 in 81X, it shouldn't be needed.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16801 8a315d6
- changes are equivalent to 90X PR  https://github.com/cms-sw/cmssw/pull/16800	8a315d6
- jenkins tests pass and comparisons with baseline show differences only in 2023 wflows with HGCAL
- local validation tests were actually done in 81X first, before signing off the 90X version

I will add a hold label to mak that this changes standard reco outputs

**Comment by slava77** [comment]
hold

this PR changes standard reco outputs beyond simple bugfix level.

Given the scope of 81X, this PR should probably be closed in a few days or so

**Pull request closed without merging**
