### PR TITLE
Pr101x L1T integration development and fixes upto v97.16

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_1_X L1T integration development and fixes upto v97.16.

Content: 
- This PR mostly contains configuration files (29) used for expert offline studies. The only configuration files of this PR used in any central workflows are
```
   Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py`
   L1Trigger/L1TCalorimeter/python/hackConditions_cff.py`
   L1Trigger/L1TMuon/python/simGmtStage2Digis_cfi.py
   L1Trigger/L1TMuonBarrel/python/simBmtfDigis_cfi.py
```
Features and fixes:

- BMTF: sim Digis set default input to TwinMux (previously simDT TP Digis)
- uGMT 
     - emulator: functionality for EMTF track-based cancel out. Default still coordinate-based.
     - packer: activate packing of inputs and upgrade it not to pack empty links and fix segfaulting when BX range is even
- L1REPACK:  
     -  `L1REPACK:Full`fix - use unpacked OMTF as inputs
     - `L1REPACK:CalouGT` - new workflow to only re-emulate Calo and uGT and to use *unpacked uGT* muons
- Calo 
     - Fix Tau emulator discrepancy emul/firmware affecting position of L1Tau candidates if merged
     - Fix EG/Tau emulator: (a) sorting in case 2 cands with same E found at same eta position. (b) fix for iso sums affecting size of the isolation window when extending in HF (TT26 and beyond)
- Calo configurations for purely offline studies:
- Fixes in L1TNtuples 
     - Fix memory leak in L1JetRecoTreeProducer
     - Add caloJets to L1Ntuples, calo jet corrections & caloHT and update met filters, jet id req, new met v7
     - Remove precaled muon triggers from matching for RecoMuonTree

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
