### PR TITLE
Migrate EcalDeadChannelRecoveryBDTG to GBRForest

### LINKED ISSUE #27648: migrate EcalDeadChannelRecoveryBDTG to GBRForest
This is a follow up to  #27175.
The reason to move to GBRForest is to reduce the memory and CPU footprint as well as achieve proper thread safety.

The agreement with @nancymarinelli and @taroni was that this migration can be postponed until the successful validation of the BDT-based ECAL dead channel recovery (initially with TMVA).

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

I don't know what the plans are to resolve https://github.com/cms-sw/cmssw/issues/27648, but as I already wrote the code for the migration to find out if it would be possible and compared the output with TMVA (see https://github.com/cms-sw/cmssw/pull/27175#issuecomment-504985154), I thought I might as well do a PR with the code from back then.

#### PR validation:

CMSSW compiles, local matrix tests pass. However, I'm not sure if the comparisons would catch possible problems. Is the channel recovery now enabled by default so the matrix tests would capture possible differences? That would make validating this PR easier.

#### if this PR is a backport please specify the original PR:

No backport intended.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@nancymarinelli @taroni FYI

**Comment by nancymarinelli** [comment]
Hi
I am not sure what this message means. Somebody else is migrating the 
software or else ?
Thanks
Nancy

On 21/09/19 12:27, perrotta wrote:
> @nancymarinelli @taroni FYI
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by perrotta** [comment]
Changes observed in the number of conversion photons in Phase2 wf 11634.0 are spurious ones.
The same was observed in PR #28048 and #28020.

As I did never notice it before the last couple of days, something should have been merged since then which oririginates such a non-reproducibility in this Phase2 workflow (in all three cases it is the same wf)

@fabiocos @slava77 @kpedro88

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@nancymarinelli @taroni : this PR is a technical migration, that wants to follow up with the discussion we had while reviewing  #27175. Such a discussion is summarized in the github issue #27648.

Since all this is rather technical, we just would like getting confirmation that, once the dead channel recovery is activated, the results will be exactly the same as in the baseline. I imagine that what reported in https://github.com/cms-sw/cmssw/pull/27175#issuecomment-504985154 can be considered as a validation also for this PR, but could you please @guitargeek redo the same validation with this PR, so that to be sure that nothing unwanted sneaked it while passing from your private code to this PR? Will you also be able to quantify the reduction in the memory and CPU footprint? All this should be better added to the PR description, for easier bookkeeping.

By now EcalDeadChannelRecovery is disabled by default, and it will remain as such until the ECAL group will finish with their evaluations. However, since this code is ready and submitted it would be a pity not to merge it in the release since now. @nancymarinelli @taroni could you please provide Jonas with a recipe for enabling the EcalDeadChannelRecovery, and suggest an appropriate sample and workflow where to test it? Or, even better, could you please take care of validating this PR yourself by using the tools/script that you have already available and you are using for testing #27175?

**Comment by guitargeek** [comment]
> However, since this code is ready [...] it would be a pity not to merge it [...]

...or at least do the PR.

Thanks Andrea, that's exactly what I thought as I had the code in my repository for 2 months since our initial check. I just didn't want to throw away the branch with the code that was already written as I hoped it might save @nancymarinelli and @taroni some time.

**Comment by perrotta** [comment]
@nancymarinelli @taroni please provide a clear recipe and a convenient dataset to run with the recovery enabled, so that this PR can be tested. Thank you.

**Comment by nancymarinelli** [comment]
Hello
taroni left CMS

As for testing the dataset, I guess it needs to be done what was done 
for the original PR. Slava certainly knows.
There is no recipe, just switch on the recovery

On 03/10/19 13:48, perrotta wrote:
>   @nancymarinelli @taroni please provide a clear recipe and a convenient dataset to run with the recovery enabled, so that this PR can be tested. Thank you.
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by slava77** [comment]
> Hello taroni left CMS As for testing the dataset, I guess it needs to be done what was done for the original PR. Slava certainly knows. There is no recipe, just switch on the recovery
> […](#)

I did not test anything myself, I only looked at the results from jenkins at the step before this commit https://github.com/cms-sw/cmssw/pull/27175/commits/da9d251ac042c607e698a5c7135626377466c05c
As mentioned in https://github.com/cms-sw/cmssw/pull/27175#issuecomment-516209460

It would be nice to have a better reference input file for a test, something where the recovery would act on more than just one hit out of 100 events. 
@nancymarinelli do you happen to have a file like this?

**Comment by nancymarinelli** [comment]
On 03/10/19 14:26, Slava Krutelyov wrote:
>> Hello taroni left CMS As for testing the dataset, I guess it needs to be done what was done for the original PR. Slava certainly knows. There is no recipe, just switch on the recovery
>> […](#)
> I did not test anything myself, I only looked at the results from jenkins at the step before this commit https://github.com/cms-sw/cmssw/pull/27175/commits/da9d251ac042c607e698a5c7135626377466c05c
> As mentioned in https://github.com/cms-sw/cmssw/pull/27175#issuecomment-516209460
>
> It would be nice to have a better reference input file for a test, something where the recovery would act on more than just one hit out of 100 events.
> @nancymarinelli do you happen to have a file like this?
>
>
No. For the time being I strongly suggest that we follow the same 
procedure we followed for the original PR which was the critical one

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by nancymarinelli** [comment]
to be more precise ... for our validation in the DPG we had data 
reprocessed with many channel killed by hand.
Only thanks to this we could validate the whole thing. But the file 
would not be immediately usable for release tests.
Also, please do not forget, that withing the DPG we still have to launch 
the wide validation for this thing.



On 03/10/19 14:34, Nancy Marinelli wrote:
>
>
> On 03/10/19 14:26, Slava Krutelyov wrote:
>>> Hello taroni left CMS As for testing the dataset, I guess it needs 
>>> to be done what was done for the original PR. Slava certainly knows. 
>>> There is no recipe, just switch on the recovery
>>> […](#)
>> I did not test anything myself, I only looked at the results from 
>> jenkins at the step before this commit 
>> https://github.com/cms-sw/cmssw/pull/27175/commits/da9d251ac042c607e698a5c7135626377466c05c
>> As mentioned in 
>> https://github.com/cms-sw/cmssw/pull/27175#issuecomment-516209460
>>
>> It would be nice to have a better reference input file for a test, 
>> something where the recovery would act on more than just one hit out 
>> of 100 events.
>> @nancymarinelli do you happen to have a file like this?
>>
>>
> No. For the time being I strongly suggest that we follow the same 
> procedure we followed for the original PR which was the critical one
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by slava77** [comment]
> to be more precise ... for our validation in the DPG we had data reprocessed with many channel killed by hand.

@nancymarinelli 
was this done with some global tag or conditions payload?
If so, please share the tag for that payload.
Thank you.

**Comment by nancymarinelli** [comment]
Difficult right now because Taroni left. If I manage to contact her and 
recover the info, I will share. IN the meantime, I think that it is 
necessary to go with the tests we did for the original PR. Also, we had 
agreed that the migration to GBRForest would have happened AFTER how 
foreseen large scale validation. You decided unilaterally to go ahead 
with it now. Our priorities stay the same. We need to do first the large 
scale validation before anything else.

@fcouderc @zghiche

On 07/10/19 13:48, Slava Krutelyov wrote:
>> to be more precise ... for our validation in the DPG we had data reprocessed with many channel killed by hand.
> @nancymarinelli
> was this done with some global tag or conditions payload?
> If so, please share the tag for that payload.
> Thank you.
>
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by perrotta** [comment]
nancymarinelli <notifications@github.com> ha scritto:

> Difficult right now because Taroni left. If I manage to contact her and
> recover the info, I will share. IN the meantime, I think that it is
> necessary to go with the tests we did for the original PR. Also, we had
> agreed that the migration to GBRForest would have happened AFTER how
> foreseen large scale validation. You decided unilaterally to go ahead
> with it now. Our priorities stay the same. We need to do first the large
> scale validation before anything else.

@nancymarinelli, Jonas had this code ready since a while already and  
it is not worth letting it to rot in some private area.
The only request for you is to tell us how did you test the previous  
PR, then nothing else of your time will get wasted.
If this PR does not change the output, and if its computing  
performance are as good as expected, then it will get integrated in a  
transparent way to you and to all other users. In particular, the  
large scale validation can go ahead independently.

**Comment by nancymarinelli** [comment]
@perrotta

I have already said how we did the original PR !
And Slava added to that. We did nothing special, the usual tests in 
jenkins. With the recovery switched off there must be zero differences.

And the recovery must stay OFF until the Ecal DPG asks differently.

@fcouderc @zghiche

On 07/10/19 14:18, perrotta wrote:
> nancymarinelli <notifications@github.com> ha scritto:
>
>> Difficult right now because Taroni left. If I manage to contact her and
>> recover the info, I will share. IN the meantime, I think that it is
>> necessary to go with the tests we did for the original PR. Also, we had
>> agreed that the migration to GBRForest would have happened AFTER how
>> foreseen large scale validation. You decided unilaterally to go ahead
>> with it now. Our priorities stay the same. We need to do first the large
>> scale validation before anything else.
> @nancymarinelli, Jonas had this code ready since a while already and
> it is not worth letting it to rot in some private area.
> The only request for you is to tell us how did you test the previous
> PR, then nothing else of your time will get wasted.
> If this PR does not change the output, and if its computing
> performance are as good as expected, then it will get integrated in a
> transparent way to you and to all other users. In particular, the
> large scale validation can go ahead independently.
>
>
>
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by guitargeek** [comment]
Sorry I didn't mean to provoke this discussion, I just didn't want the code to get lost so I did this PR, and I inferred from @nancymarinelli's comment (https://github.com/cms-sw/cmssw/pull/27175#issuecomment-505133685) that she would appreciate that. But as the validation is a bit complicated due to the recovery not being activated, I can just close the PR and maybe reopen it later? I hope this would be fine for everyone.

**Comment by perrotta** [comment]
> Sorry I didn't mean to provoke this discussion, I just didn't want the code to get lost so I did this PR, and I inferred from @nancymarinelli's comment ([#27175 (comment)](https://github.com/cms-sw/cmssw/pull/27175#issuecomment-505133685)) that she would appreciate that. But as the validation is a bit complicated due to the recovery not being activated, I can just close the PR and maybe reopen it later? I hope this would be fine for everyone.

Let go ahead with this, since it is ready: nobody will get hurt.
The flag to get reverted inside ```RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cfi.py``` is 
```PYTHON
    recoverEBIsolatedChannels = cms.bool(False),##default is false
```

If we run it on a sufficiently large sample of data we should hit a few channels that need to be reverted. Then it is a matter of comparing the results of your code with the ones of the original code.
I am rather busy in these days, but I can check it myself in a week or so. If someone has time to do it earlier on that would be even better, but there is nothing really urgent here. Would anyone know a specific sample where the fraction of channels to be recovered is larger, the check would be more efficient: but I think everything can be dealt with also by reading some "normal" EGamma sample.

**Comment by nancymarinelli** [comment]
Sorry, We would like to have the validation done on the work we had done 
before. If this migration is integrated we will never know if, should 
issues come up, they are related to our work or to the migration


@fcouderc @zghiche

On 07/10/19 16:46, perrotta wrote:
>> Sorry I didn't mean to provoke this discussion, I just didn't want the code to get lost so I did this PR, and I inferred from @nancymarinelli's comment ([#27175 (comment)](https://github.com/cms-sw/cmssw/pull/27175#issuecomment-505133685)) that she would appreciate that. But as the validation is a bit complicated due to the recovery not being activated, I can just close the PR and maybe reopen it later? I hope this would be fine for everyone.
> Let go ahead with this, since it is ready: nobody will get hurt.
> The flag to get reverted inside ```RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cfi.py``` is
> ```PYTHON
>      recoverEBIsolatedChannels = cms.bool(False),##default is false
> ```
>
> If we run it on a sufficiently large sample of data we should hit a few channels that need to be reverted. Then it is a matter of comparing the results of your code with the ones of the original code.
> I am rather busy in these days, but I can check it myself in a week or so. If someone has time to do it earlier on that would be even better, but there is nothing really urgent here. Would anyone know a specific sample where the fraction of channels to be recovered is larger, the check would be more efficient: but I think everything can be dealt with also by reading some "normal" EGamma sample.
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by nancymarinelli** [comment]
WHan I talk of validation I mean the large scale DPG has foreseen for 
veryfing that the MET is not screwed. not the validation of this PR

On 07/10/19 16:50, Nancy Marinelli wrote:
> Sorry, We would like to have the validation done on the work we had 
> done before. If this migration is integrated we will never know if, 
> should issues come up, they are related to our work or to the migration
>
>
> @fcouderc @zghiche
>
> On 07/10/19 16:46, perrotta wrote:
>>> Sorry I didn't mean to provoke this discussion, I just didn't want 
>>> the code to get lost so I did this PR, and I inferred from 
>>> @nancymarinelli's comment ([#27175 
>>> (comment)](https://github.com/cms-sw/cmssw/pull/27175#issuecomment-505133685)) 
>>> that she would appreciate that. But as the validation is a bit 
>>> complicated due to the recovery not being activated, I can just 
>>> close the PR and maybe reopen it later? I hope this would be fine 
>>> for everyone.
>> Let go ahead with this, since it is ready: nobody will get hurt.
>> The flag to get reverted inside 
>> ```RecoLocalCalo/EcalRecProducers/python/ecalRecHit_cfi.py``` is
>> ```PYTHON
>>      recoverEBIsolatedChannels = cms.bool(False),##default is false
>> ```
>>
>> If we run it on a sufficiently large sample of data we should hit a 
>> few channels that need to be reverted. Then it is a matter of 
>> comparing the results of your code with the ones of the original code.
>> I am rather busy in these days, but I can check it myself in a week 
>> or so. If someone has time to do it earlier on that would be even 
>> better, but there is nothing really urgent here. Would anyone know a 
>> specific sample where the fraction of channels to be recovered is 
>> larger, the check would be more efficient: but I think everything can 
>> be dealt with also by reading some "normal" EGamma sample.
>>
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by perrotta** [comment]
@nancymarinelli 
@argiro (for ECal) @SohamBhattacharya @afiqaize

Could you please tell us which which is the status of the DPG (and maybe also EGamma) validation of the Ecal DeadChannelRecovery? When a conclusion about it can be expected, approximately?

Thank you!

**Comment by nancymarinelli** [comment]
@fcouderc, @azghiche
The validation requires an ad-hoc reprocessing of some data with the 
recovery ON. The DPG is planning but for now the sample is not available 
yet.

@perrotta
It will  be an ecal DPG validation, nor and EGAMMs validation. the DPG 
has already validated with Zee and what we could for Met, in Zmumu events.

The large validation is mostly for the MET group. There is no precise 
time line.


On 21/10/19 15:02, perrotta wrote:
> @nancymarinelli
> @argiro (for ECal) @SohamBhattacharya @afiqaize
>
> Could you please tell us which which is the status of the DPG (and maybe also EGamma) validation of the Ecal DeadChannelRecovery? When a conclusion about it can be expected, approximately?
>
> Thank you!
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by fabiocos** [comment]
@nancymarinelli for my understanding, is this sample needed for the validation already requested and in the pipe? Or is this just a plan that at some moment will be followed? And in this case when? Just to set a timescale for this work to converge in a positive way.

**Comment by fabiocos** [comment]
@nancymarinelli @argiro could you please clarify what are the expected next steps to allow this PR to move forward?

**Comment by nancymarinelli** [comment]
@fcouderc

Hello,
as Fabrice and Amina can confirm, a plan is being made to backporting in 
the 10 series the PR (27175)  on top of which, eventually, #28040  will 
have to be added.
The backport is necessary for the validation (comparison with UL2017) 
with JETMET of #27175.
The details of this plas will also be agreed at the beginning of the 
year, with PPD.

Only at the end of this process, #28040 should go in, as agreed long ago.

Best,
  Nancy

On 17/12/19 09:05, Fabio Cossutti wrote:
> @nancymarinelli @argiro could you please clarify what are the expected next steps to allow this PR to move forward?
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by silviodonato** [comment]
Hi @nancymarinelli , please let us know when the backport of #27175 is ready.

**Comment by nancymarinelli** [comment]
@argiro

On 08/01/20 16:01, Silvio Donato wrote:
> Hi @nancymarinelli , please let us know when the backport of #27175 is ready.
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by silviodonato** [comment]
Status: waiting for the backport #27175 and #28514 needed to run the validation of this PR.

**Comment by silviodonato** [comment]
Unless you are planning to update this PR in the next days/weeks, I would close this PR in order to keep open only the active PRs. Of course you can open again this PR as soon as you have any news.

**Comment by guitargeek** [comment]
Okay! Once the EcalDeadChannelRecoveryBDTG is enabled in production so this PR can be easily tested, I will reopen it.

**Comment by perrotta** [comment]
@guitargeek : you reopened this PR.
Do you have any insight from the ECAL DPG which suggests that the tests on the EcalDeadChannelRecovery are now concluded, and we can carry on with this PR?

**Comment by zghiche** [comment]
Hello,
We are in the process of launching the full scale validation for this.

Best regards,

Amina for the DPG

**Comment by guitargeek** [comment]
Ah okay, pardon I was just not sure if it was time to reopen or not, now that https://github.com/cms-sw/cmssw/pull/29010 was merged. Thanks for the notification!

**Comment by guitargeek** [comment]
Just reopening it for a rebase to fix the conflicts

**Comment by perrotta** [comment]
please test
(let give it a try...)

**Comment by perrotta** [comment]
@nancymarinelli  @fcouderc @rchatter since this PR has been momentarily re-opened for technical reasons (rebase needed) let me profit to inquire with you about the status of the validation of the EcalDeadChannelRecovery: are there updates since last November?

@rchatter: the status of that validation is an additional item that could possibly be also addressed in your presentation at the reco meeting tomorrow

@guitargeek if there are no news and we get no time estimate for a possible decision about including the dead channel recovery in the actual ecal local reconstruction, I think this PR could be set back to sleep again...

**Comment by perrotta** [comment]
@guitargeek given the outcome of the discussion we had yesterday at the reconstruction meeting (basically: no time estimate for the validation results) I think this PR could be put in fridge for a little more while...
Thank you anyhow for having kept it up to date!

**Comment by guitargeek** [comment]
No problem! I have followed the meeting. Actually I reopened this PR more by accident. I checked the PR page to see if there were any comments, and the "reopen" button was greyed out. So I clicked on it, thinking that it would not work but it did. So if you broke your own branch by force-push you can't reopen, but if the upstream branch makes your PR need a rebase you can reopen but the button looks different.

**Comment by guitargeek** [comment]
Just reopening this PR to check in. After all there is still a corresponding issue https://github.com/cms-sw/cmssw/issues/27648 open.

**Comment by perrotta** [comment]
please test
(just to keep it hot)

**Comment by perrotta** [comment]
@thomreis since this PR has been momentarily re-opened for technical reasons, let me profit to inquire with you about the status of the validation of the EcalDeadChannelRecovery: are there updates since last July (bi-annual check, see https://github.com/cms-sw/cmssw/pull/28040#issuecomment-662875396)?

**Comment by nancymarinelli** [comment]
@couderc, @pigazzini

On 15/12/20 10:07, perrotta wrote:
> @thomreis since this PR has been momentarily re-opened for technical reasons, let me profit to inquire with you about the status of the validation of the EcalDeadChannelRecovery: are there updates since last July (bi-annual check, see https://github.com/cms-sw/cmssw/pull/28040#issuecomment-662875396)?
>

-- 
________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by thomreis** [comment]
@perrotta to my knowledge there are no updates to the validation status. At least I do not find any related presentation in ECAL meetings of the last half year.

**Comment by nancymarinelli** [comment]
@couderc, @pierazzini

the valitadation from the MET group started some while ago, but it's now 
stopped because the person who was taking care of it is no longer 
available for health reasons. So we are waiting for a replacement. 
Bottom line, no news. The PR stays as it is

  Nancy

On 23/12/20 18:04, Thomas Reis wrote:
> @perrotta to my knowledge there are no updates to the validation status. At least I do not find any related presentation in ECAL meetings of the last half year.
>

-- 
________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by perrotta** [comment]
Thank you @thomreis and @nancymarinelli 
@guitargeek , I think you can put to bed this PR once again...

**Comment by fcouderc** [comment]
@perrotta , @nancymarinelli 

Meanwhile we have had some discussion with the JME group about the validation and they did not see any issue popping out (though the first results were not encouraging, it was due to a bug I believe). I am adding JME conveners (@lathomas @ahinzmann ) to confirm that the validation is ok on their side.

Sorry for the late notice. 

Cheers

Fabrice & Simone

**Comment by lathomas** [comment]
(adding @kirschen )
Hello, 
I can confirm we didn't see any issue, but also no improvement, including for electrons, which sounds a bit surprising. Could someone point us to an ECAL/EGM study showing the expected effect?
Thanks !

**Comment by nancymarinelli** [comment]
Hello
here 3 talks. In link 3 there are more references.

1) 
https://indico.cern.ch/event/830302/contributions/3477927/attachments/1871241/3079254/DeadChannelSummary_RecoMeeting.pdf 

2) 
https://indico.cern.ch/event/817347/contributions/3412127/attachments/1841036/3018464/DeadChannelSummary.pdf 

3) 
https://indico.cern.ch/event/824161/contributions/3446656/attachments/1855556/3047564/DeadChannelCMSSW_June2019.pdf


Nancy

On 04/01/21 09:23, lathomas wrote:
> (adding @kirschen )
> Hello,
> I can confirm we didn't see any issue, but also no improvement, including for electrons, which sounds a bit surprising. Could someone point us to an ECAL/EGM study showing the expected effect?
> Thanks !
>

-- 
________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Pull request closed without merging**
