### PR TITLE
Initialize variables in HGCalClusterT

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes UBSAN warnings.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+1

Technical PR to remove UBSAN warnings, no change is expected. PR test runs fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
