### PR TITLE
Setting up properly peak and deco (strip tracker config) 2017 cosmic WFs 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings, 
I believe the title is explicite enough for a good description 
Please note before being merged , this PR needs to be updated with a deco GT 
(see line 45 in AutoCond) 

Equivalent PR in 91X : #17828

### CODE REVIEW

**Comment by franzoni** [comment]
hello @boudoul 
as agreed verbally, here https://github.com/cms-sw/cmssw/pull/17886 the ingredients from AlCa/Db you wanted for this PR

**Comment by boudoul** [comment]
This PR is not more in conflict  with #17829 - However it needs #17829 to be merged first to consume the GT define there

**Comment by boudoul** [comment]
forgot to thank alcADB ( @franzoni  and @arunhep ) for providing the GTs !

**Comment by boudoul** [comment]
@davidlange6 , please note that these WFs are crucial to make sure that the  cosmic MC worflows are correct in view of  the MC prod  in 900 for phase1 tracker alignement  studies

**Comment by boudoul** [comment]
I just updated this PR to make it fully in synch with the 91X version : #17828

**Comment by ghellwig** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Pull request merged**
