### PR TITLE
Remove hardcoded paths

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Rebase of #22010. 
Changing hard coded directory paths in order to make them configurable.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by thomreis** [comment]
Hi @vukasinmilosevic can you please make a backport to 10_0_X so that we can test it in MWGR#3?

**Pull request merged**
