### PR TITLE
DT DQM data integrity and ML

### PR DESCRIPTION
**Pull request by jfernan2**
Changes comprise:
A) Folders:
- FED folders with general EvtLength informacion and uROS folders with TTS values and specific uROS EvtLength
- Wheel folders with individual ROS information for RO and TDC checks across Links

B) Summary Histograms
- uROS Global errors (yet to be defined by Alvaro) plotted vs uROS based on FED: FEDXXXX_uROSSummary 
- FEDEntries
- ROSummary_ WX  with RO errors, NotOKFlag and TDC checks, computed over all the links of a sector

C) Full summary histograms as in the past, but now denominator takes into account specific uROS EvtLength divided by 3 since an uROS controls 3 sectors and it is not possible to distangle how many events belong to a given ROS afaiu:
- DataIntegrityTDCSummary: only using TDC Fatal bin for computation as in the past (Legacy)
- DataIntegritySummary: using Error1-4 and NotOKFlag computed over all the links of a sector
- DataIntegrityGlbSummary: as the above but including also ErrorG1-12 in the numerator (so identical to DataIntegritySummary since these errors are yet to be defined by Alvaro)

D) Others:
- DTBlockedROChannelsTest on folder  00-ROChannels still being worked out based ONLY on NotOKFlag and averaging to 6 links per chamber
- ML from Adrian on  folder 01-Digi / ML   (to be fully tested/tuned during collisions)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 sorry, but this is not the back-port of anything, am I correct? If yes please have also a master version of this PR

**Comment by jfernan2** [comment]
Hi @fabiocos no, it is not a backport, it is intended to go Online DQM first, that's why it is based on 10_1_1
Thanks

**Comment by fabiocos** [comment]
@jfernan2 well, for the official CMSSW release I would like to follow the usual path of integration (master -> back-port)

**Comment by jfernan2** [comment]
backport of #23020

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@jfernan2 could you please adapt this back-port to the master version?

**Comment by smuzaffar** [comment]
@jfernan2 , for 10.1.X tests, please use https://github.com/cms-sw/cmsdist/pull/3980.

**Comment by jfernan2** [comment]
please test  cms-sw/cmsdist#3980

**Comment by jfernan2** [comment]
Removing the models folder from commit history as in #23020

**Comment by jfernan2** [comment]
please test cms-sw/cmsdist#3980

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#3977

**Comment by smuzaffar** [comment]
please test cms-sw/cmsdist#3980
For 10.1.X, cmsdist PR is cms-sw/cmsdist#3980 :-)

**Comment by jfernan2** [comment]
sorry @smuzaffar I mistyped the number again...

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3980

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#3980

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#3980

**Comment by jfernan2** [comment]
+1
________________________________________

**Comment by jfernan2** [comment]
Needed to have cms-sw/cmsdist#3980 integrated too.
Successfully test and integrated in the Online DQM at P5. 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by jfernan2** [comment]
@fabiocos Could this PR and its cmsdist-#3980 be merged? Its forward port and its corresponding cmsdist have been merged by you and this PR has been extensively tested on Online DQM.  
Thank you in advance

**Comment by fabiocos** [comment]
please test

**Pull request merged**
