### PR TITLE
Update alphaT DQM paths

### PR DESCRIPTION
**Pull request by aelwood**
Along with 74 PR https://github.com/cms-sw/cmssw/pull/8937

To update the DQM for the HLT paths in line with the JIRA ticket https://its.cern.ch/jira/browse/CMSHLT-354

### CODE REVIEW

**Comment by aelwood** [comment]
@perrotta I'm not 100% sure I understand what you mean. I had left in the old alphaT path when it wasn't declared ( a bug ), which I fixed with commit fe54cc8 . If the paths are not in the menu, there is already a protection to just log a debug and not crash the process ( https://github.com/aelwood/cmssw/blob/dqmUpdate75/HLTriggerOffline/SUSYBSM/src/SUSY_HLT_alphaT.cc#L56 ). Is this enough?

**Comment by perrotta** [comment]
I did not look at the details of the code, sorry.
Provided it dorsn't crash in case of missing paths inn the menu?it is  
perfectly fine with me.
Thank you,
Andrea


aelwood <notifications@github.com> ha scritto:

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
