### PR TITLE
Added Erf and Landau functions to FormulaEvaluator

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added Erf and Landau functions which are needed for jet energy corrections.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This was requested from #14430

**Comment by slava77** [comment]
@cmsbuild please test
to get a clean incremental test (without extraneous PRs merged during testing)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14494	5c796ab
- code change is in line with the description; new feature is added
- jenkins tests pass: unit test including testFormulaEvaluator.cc (testCommonToolsUtil) runs OK; comparisons with baseline show no differences

@Dr15Jones I suppose we will need a version in 80X as well.

**Comment by Dr15Jones** [comment]
As usual, an 8_0_X version would happen after this one proves to not cause a problem in the IB.

**Comment by Dr15Jones** [comment]
@slava77 #14522

**Pull request merged**
