### PR TITLE
Updated reference release list for CondDB regression test

### PR DESCRIPTION
**Pull request by ggovi**
Entries for the 80, 81 and 90 have been added.  Most of the entries for 7X  have been removed.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@smuzaffar, @davidlange6 
it looks that the relevant test:
CondCore/CondDB/test/condTestRegression.py
is not being executed by the testing machinery. How can we trigger the execution?

**Comment by smuzaffar** [comment]
@ggovi , only tests mentioned in package/test/BuildFile.xml are run by scram. If you want this test to be run by scram then I would suggest to add something like the following in BuildFile
```
<test name="UniqueNameOfTheTest" command="CommandToRun"/>
e.g.
<test name="condTestRegression" command="condTestRegression.py"/>
```

Note that this is only available in 90X IBs because of new build rules in the release.

**Comment by smuzaffar** [comment]
@ggovi , by thw way, if you want this be run by scram then I would suggest to not create any thing in /tmp directory (e.g. /tmp/cmsCondRegTst) instead use $CMSSW_BASE/tmp

**Comment by ggovi** [comment]
@smuzaffar
thanks for the hints, re-trying...

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by fwyzard** [comment]
@ggovi, is it expected that the test passes on SLC6 but fails on CC7 ?

I just tried
```
cmsrel CMSSW_9_0_X_2017-02-09-1100
cd CMSSW_9_0_X_2017-02-09-1100/src/
cmsenv
git cms-init
git cms-merge-topic 17466
scram b
src/CondCore/CondDB/test/condTestRegression.py 
```
on both architectures.

On `slc6_amd64_gcc530` I get
```
...
runAll() took 12056.305 ms

                                rel  | ref8026-s6 | ref810-s65 | ref766-s64 | self-CMSSW | ref900p3-s  | 
                  CMSSW_7_6_6-gcc493 |       True |       True |       True |       True |       True  | 
                 CMSSW_8_0_26-gcc530 |       True |       True |       True |       True |       True  | 
                  CMSSW_8_1_0-gcc530 |       True |       True |       True |       True |       True  | 
             CMSSW_9_0_0_pre3-gcc530 |       True |       True |       True |       True |       True  | 
  CMSSW_9_0_X_2017-02-09-1100-gcc530 |       True |       True |       True |       True |       True  | 

==> overall status:  True
```

while on `slc7_amd64_gcc620` I get
```
runAll() took 15360.988 ms

NO match found for  CMSSW_9_0_X_2017-02-09-1100-slc7_amd64_gcc620-ref8026-s6530.db
Traceback (most recent call last):
  File "src/CondCore/CondDB/test/condTestRegression.py", line 197, in <module>
    status = crt.summary(verbose=True)
  File "src/CondCore/CondDB/test/condTestRegression.py", line 84, in summary
    ra = radMatch.groups()[0]+'-'+radMatch.groups()[1] 
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by fwyzard** [comment]
Ah, it looks like `scl6` is hardcoded.

With this change
```
diff --git a/CondCore/CondDB/test/condTestRegression.py b/CondCore/CondDB/test/condTestRegression.py
index 3430a6a..a5ba216 100755
--- a/CondCore/CondDB/test/condTestRegression.py
+++ b/CondCore/CondDB/test/condTestRegression.py
@@ -75,7 +75,7 @@ class CondRegressionTester(object):
 
       def summary(self, verbose=False, jsonOut=False):
           if verbose: 
-              radRe = re.compile('^(CMSSW_.*?)-(slc6_amd64_gcc\d\d\d)-(.*)$')
+              radRe = re.compile('^(CMSSW_.*?)-(slc\d_amd64_gcc\d\d\d)-(.*)$')
               relArches = []
               dbNames = []
               for rad in self.status.keys():
```
it now works
```
...
runAll() took 8589.078 ms

                                rel  | self-CMSSW | ref8026-s6 | ref810-s65 | ref766-s64 | ref900p3-s  | 
                  CMSSW_7_6_6-gcc493 |       True |       True |       True |       True |       True  | 
                 CMSSW_8_0_26-gcc530 |       True |       True |       True |       True |       True  | 
                  CMSSW_8_1_0-gcc530 |       True |       True |       True |       True |       True  | 
             CMSSW_9_0_0_pre3-gcc530 |       True |       True |       True |       True |       True  | 
 CMSSW_9_0_X_2017-02-09-1100-slc7_amd64_gcc620 |       True |       True |       True |       True |       True  | 

==> overall status:  True
```

**Comment by ggovi** [comment]
@fwyzard 
thanks, i've added this fix and replaced 90p3 with 90p4.

**Comment by ggovi** [comment]
@smuzaffar 
still cannot get this thing working with scram b runtests.
While running, i'm executing command sequences like:
          releaseDir = '/cvmfs/cms.cern.ch/%s/cms/cmssw/%s' %(arch,rel)
          cmd =  'export SCRAM_ARCH=%s; cd %s/src ; eval `scram run -sh`; cd - ; ' %(arch,releaseDir)
          cmd += 'echo $CMSSW_BASE; echo $RELEASE_BASE; echo $PATH; echo $LD_LIBRARY_PATH;'
          cmd += '%s/test/%s/testReadWritePayloads %s sqlite_file:///%s/%s ' % (releaseDir,arch, readOrWrite, self.dbDir, dbName)

where the rel and arch values ranges in the list:
          map = { 'CMSSW_9_0_0_pre4'   : [ 'slc6_amd64_gcc620', 'ref900p4-s6620.db'],
                  'CMSSW_8_1_0'        : [ 'slc6_amd64_gcc530', 'ref810-s6530.db'],
		  'CMSSW_8_0_26'       : [ 'slc6_amd64_gcc530', 'ref8026-s6530.db'],
		  'CMSSW_7_6_6'        : [ 'slc6_amd64_gcc493', 'ref766-s6493.db'],
          }

It looks like the env stays to one of the IB even after the eval `scram run -sh`...
Both $CMSSW_BASE and $RELEASE_BASE val pointing to:
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2017-02-09-1100

while running the command 'by hand' they are correctly set to:
CMSSW_BASE = /build/gg/CMSSW_9_0_X_2017-02-08-1100
RELEASE_BASE = /cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_6

Any idea on how to fix this?

**Comment by ggovi** [comment]
@smuzaffar 
I think I go it working now. I had to open a process without to inherit the environment from the parent, which is 'owned' by scram...

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by davidlange6** [comment]
@ggovi - does this test really work for you locally?

**Comment by ggovi** [comment]
@davidlange6 
yes, this last version worked for me. It also works in this environment but only with hard-coded paths. I'm trying to make it working for the general CMSSW release environment, but it looks quite tricky...

**Comment by ggovi** [comment]
@davidlange6  @smuzaffar 
in this case it looks that the command:
scram -a slc6_amd64_gcc493 list -c CMSSW_7_6_6 | tail -1 | sed 's|.* ||'
which locally gives to me:
/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_6_patch1
does not provide something right here.
Any idea?

**Comment by ggovi** [comment]
one more attempt ( as usual, it works for me with scram b runtests )

**Comment by ggovi** [comment]
please test

**Comment by davidlange6** [comment]
for 91x

**Pull request closed without merging**
