### PR TITLE
[backport] Update the EXODisappTrk skim source PD

### PR DESCRIPTION
**Pull request by sam7k9621**
#### PR description:
This PR updates the source PD of EXODisapptrk skim which had been changed in #38919.
And it is a backport of CMSSW_12_4_X

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #39268 #38919

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39268

**Comment by sam7k9621** [comment]
Hi @perrotta , could this also be tested, the requester needs this in the upcoming runs
thank you!

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by sam7k9621** [comment]
Hi @perrotta , could this be merged?

**Comment by perrotta** [comment]
+1

**Pull request merged**
