### PR TITLE
[13_2_X] Fix LHCInfoPerLS PopCon incorrectly matching LS between OMS and PPS db and fix LHCInfoPer* PopCons not recoginizing ongoing fills in duringFill mode

### PR DESCRIPTION
**Pull request by JanChyczynski**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42629
and
Backport of https://github.com/cms-sw/cmssw/pull/42837
#42837 depends on #42629 so they have to be backported together

See master PRs for descriptions

#### PR validation:

See master PRs

#### Backporting

Backport of https://github.com/cms-sw/cmssw/pull/42629
and
Backport of https://github.com/cms-sw/cmssw/pull/42837

### CODE REVIEW

**Comment by JanChyczynski** [comment]
Should I squash the 2 commits into one or as it's a backport of 2 PR's it's more clean if they're in separate commits?

**Comment by francescobrivio** [comment]
> Should I squash the 2 commits into one or as it's a backport of 2 PR's it's more clean if they're in separate commits?

I think it's more clear to have two separate commits.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+db
- The comparison with the corresponding code in master was not straightforward because #42360 was only partially backported in 13_2_X with #42361 (which was indeed my suggestion at the time, since I did not imagine that some further fix would have been still backported into the HI release...)
- However, the backported parts are correct, and faithfully reproduce what is in the master PRs https://github.com/cms-sw/cmssw/pull/42837 and https://github.com/cms-sw/cmssw/pull/42629
- bot tests show no issues

**Comment by rappoccio** [comment]
+1

**Pull request merged**
