### PR TITLE
DD4Hep: Vector Tag Parsing

### PR DESCRIPTION
**Pull request by ianna**
* Implement Vector tag parsing - an equivalent to DDLVector

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna in principle this PR should not imply any change in tests, am I correct?

**Comment by fabiocos** [comment]
please test

**Comment by ianna** [comment]
@fabiocos - if there are any differences, they must be unrelated. The PR is a standalone package, not used in relval or production.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
