### PR TITLE
add two CSCTF plots for debugging MPC/TMB errors from CSC

### PR DESCRIPTION
**Pull request by rjwang**
add two CSCTF plots for debugging MPC/TMB errors from CSC

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please submit to 75 and 75 and 80 as well.
75 will be used for HI data taking.
thanks,
F.

**Comment by rjwang** [comment]
Yes, I will do that.

**Comment by rjwang** [comment]
done, see 
https://github.com/cms-sw/cmssw/pull/12470 <https://github.com/cms-sw/cmssw/pull/12470>
https://github.com/cms-sw/cmssw/pull/12471 <https://github.com/cms-sw/cmssw/pull/12471>
https://github.com/cms-sw/cmssw/pull/12472 <https://github.com/cms-sw/cmssw/pull/12472>

**Comment by dmitrijus** [comment]
-1
We probably don't need this pr in 74x anymore - it was integrated into >8_0_X
If there are no plans to integrate this into 74x - please close this PR.

**Pull request closed without merging**
