### PR TITLE
Switching MCSmartSingleParticleFilter to use an input tag (11.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR updates the `MCSmartSingleParticleFilter` to use an `edm::InputTag` rather than a string to specify its input.
This allows to use an instance label different than `"unsmeared"`.

#### PR validation:

See #32491.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #32491.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bug-fix

**Comment by fwyzard** [comment]
backport #32491

**Comment by fwyzard** [comment]
urgent

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@silviodonato @qliphy please consider this PR for CMSSW_11_1_7

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
