### PR TITLE
Fix some minor RooFit user errors

### PR DESCRIPTION
**Pull request by guitargeek**
* One should use `getVal()` and not `getValV()` (the latter should not be called. The "V" stands for `virtual`, and `getValV()` is the function that should be overridden if one wants to change the behavior of `getVal()`)

  * Avoid some memory leaks by not creating a leaking fit result by using the `Save()` option

  * Improve memory management with smart pointers

### CODE REVIEW

**Comment by mmusich** [comment]
nothing happened in the last 13 hours... let's try again

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12434.7` (open issue #39803 )

**Comment by guitargeek** [comment]
@antoniovilela, can this be merged? The analysis signature usually is not done, at least not timely

**Comment by tvami** [comment]
+1
 * I'm on vacation this week

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
@guitargeek 
Another PR updated the same file as you, and it got merged before (sorry). Could you check the conflict?
Thanks.

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+1
 * re-sign

**Comment by tjavaid** [comment]
+1

- re-sign

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
