### PR TITLE
Removed serialization based on Root, since it is not used. (again).

### PR DESCRIPTION
**Pull request by wmtan**
A few  weeks ago, Giacomo Govi removed serialization based on ROOT from this file in 7_5_X.
Unfortunately, this change got lost in CMSSW_7_5_ROOT5_X because of reasons not fully understood
(most likely a merge issue).  The changes got lost in Serialization.cc, but not in Serialization.h.
This inconsistency is causing fatal compilation errors in package CondCore/CondDB in
CMSSW_7_5_ROOT5_X.
This PR restores Giacomo's changes, and fixes the build errors.  Incidentally, this PR makes this file identical in CMSSW_7_5_X and CMSSW_7_5_ROOT5_X.

### CODE REVIEW

**Comment by wmtan** [comment]
@ggovi @cmsbuild ping

**Comment by ggovi** [comment]
+1

**Comment by wmtan** [comment]
This PR fixes the build errors in only one of the two packages that fail to compile.  These test errors are in the base release, and are caused by the other package that fails to compile, which is not fixed by this PR.

**Comment by wmtan** [comment]
#9427 and #9429 together fix all the build errors

**Pull request merged**
