### PR TITLE
Updates to Resonance Decay Filter

### PR DESCRIPTION
**Pull request by DavidMorse**

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by DavidMorse** [comment]
Hi, is there anything specific I should do to obtain ORP approval?

**Comment by perrozzi** [comment]
no, the PR is ready to be merged and it has been discussed yesterday

**Comment by davidlange6** [comment]
Hi- what is the 81x PR corresponding to this change?

**Comment by DavidMorse** [comment]
It is here: https://github.com/cms-sw/cmssw/pull/15285

**Comment by davidlange6** [comment]
+1
thanks

**Pull request merged**
