### PR TITLE
Read ECAL PF thresholds from DB rather than config file

### PR DESCRIPTION
**Pull request by argiro**
Use new record in DB as a source of threshold for Ecal PF reconstruction. Needs new GT as submitted in #22290

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with #22290

**Comment by perrotta** [comment]
please test

(Now that #22290 has been merged, testing with an IB with it as the baseline should get rid of the differences in reco tests)

**Comment by perrotta** [comment]
Still, the HLT AddOn tests failing point out to some possible missing item in the latest GT:
```
----- Begin Fatal Exception 02-Mar-2018 17:04:02 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 3
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Prefetching for module ReducedRecHitCollectionProducer/'reducedEcalRecHitsEB'
   [4] Prefetching for module EleIsoDetIdCollectionProducer/'interestingGedEleIsoDetIdEB'
   [5] Prefetching for module GEDGsfElectronFinalizer/'gedGsfElectrons'
   [6] Prefetching for module ElectronEcalPFClusterIsolationProducer/'electronEcalPFClusterIsolationProducer'
   [7] Prefetching for module CorrectedECALPFClusterProducer/'particleFlowClusterECAL'
   [8] Prefetching for module PFClusterProducer/'particleFlowClusterECALUncorrected'
   [9] Calling method for module PFRecHitProducer/'particleFlowRecHitECAL'
Exception Message:
No "EcalPFRecHitThresholdsRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
when using ``` --conditions auto:run2_mc_l1stage1``` or ```--conditions auto:run2_mc_Fake1```

**Comment by argiro** [comment]
@lpernie , @crovelli , @amassiro  can you help debugging the apparent absence of the EcalPFRecHitThresholdsRcd record in the GT ?

**Comment by perrotta** [comment]
@amassiro #22290 got integrated in the master since three days already.

As I noticed in https://github.com/cms-sw/cmssw/pull/22412#issuecomment-370459508, the EcalPFRecHitThresholdsRcd record seems to be missing in the two following conditions 'run2_mc_Fake1' and 'run2_mc_l1stage1' , and they both refer to the Global Tag '93X_mcRun2_asymptotic_v3'

**Comment by crovelli** [comment]
Thanks, @perrotta. My understanding is that @lpernie added the new record
only to the GTs of the 10.1.x serie (as we requested), that's why these
workflows are crashing... Should we queue the new tag also for the 93x
queue?

**Comment by perrotta** [comment]
My understanding is that either the new tag is added to all relevant GTs, or the conditions for (at least) the two tests that crashes are updated. 

As far as I can see
https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCond.py#L18
the 'run2_mc_l1stage1' condition is the only remaining one in autoCond.py that still points to a 93X GT.
If it cannot be updated, then I imagine that the new record should be queued also there.

@Martin-Grunewald @silviodonato

**Comment by Martin-Grunewald** [comment]
Yes...

**Comment by crovelli** [comment]
Ok, we asked to our DB experts to queue the new record also for this queue
(then a new GT will be needed). Just for my understanding:
why these relvals can't be migrated to more recent GTs? Thanks!

**Comment by perrotta** [comment]
crovelli <notifications@github.com> ha scritto:

> Ok, we asked to our DB experts to queue the new record also for this queue
> (then a new GT will be needed). Just for my understanding:
> why these relvals can't be migrated to more recent GTs? Thanks!

I had added HLT people in the loop in order to answer something  
similar to that question, which is made explicit here...
@Martin-Grunewald : could you please elaborate what do you mean with  
"yes"? :-)
Isn't the "L1 trigger in Stage1 mode" available in 101X* GTs?

**Comment by Martin-Grunewald** [comment]
The yes was referring to having this workflow fixed: it tests older detector setups which were using the 
L1T stage1. I do not know whether a 101 GT would be appropriate.

**Comment by crovelli** [comment]
Thanks to P.Depasse, the relevant tags are now available in the 93x queues
- should be integrated in the GTs

**Comment by lpernie** [comment]
Hi All, 
yes I forgot there is key pointing to 93X_mcRun2_asymptotic_v3 even in 101 condDB.
I will create a 93X_mcRun2_asymptotic_v4 GT to be included in autocond.
Maybe you can make this autocond fix in this PR directly?

**Comment by lpernie** [comment]
Hi @argiro ,
Could you update "Configuration/AlCa/python/autoCond.py" and use 93X_mcRun2_asymptotic_v4 instead of 93X_mcRun2_asymptotic_v3 [1].
This should solve the problem.

[1] https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_asymptotic_v3/93X_mcRun2_asymptotic_v4

**Comment by lpernie** [comment]
please tests

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lpernie** [comment]
+1

**Comment by perrotta** [comment]
+1
- ECAL PF thresholds for PFRecHitQTests taken from DB rather than config file
- No difference in jenkins tests: thresholds themselves did not change

**Comment by fabiocos** [comment]
+1

**Pull request merged**
