### PR TITLE
73: Guess configuration on base of the data file.

### PR DESCRIPTION
**Pull request by alja**
Depending of the data file choose between 3 type of configuration:
reco.fwc (previously default.fwc)
miniaod.fwc
aod.fwc

The default configuration (e.g. when there is no data file is aod.fwc)

### CODE REVIEW

**Comment by alja** [comment]
This PR depends on #7581, which holds new aod configuration file.

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
+1
added one more change for the case cmsShow is started without a file

**Comment by davidlange6** [comment]
+1

**Pull request merged**
