### PR TITLE
Use thread-friendly modules in Validation/RecoTau

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes all CMS deprecation warnings in the package

#### PR validation:

Package compiles without any CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please review. This is part of the last two PRs holding up the removal of the legacy EDFilter class.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
