### PR TITLE
Consumes migration, ExoticaDQM & HWWAnalyzer

### PR DESCRIPTION
**Pull request by wddgit**
Migrate 2 DQM modules to call consumes. Both need
JetCorrectors. This modifies them to get them from
the Event instead of from the EventSetup as has been
done for other modules.

Plus there are changes to ensure needed JetCorrector
producers are run in the RECO configuration sequences.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
thanks @wddgit

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #8817 ce83993a30331cf69c696672e3438f47ee39092c

Migrating DQM modules ExoticaDQM  and HWWAnalyzer to use consumes.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8817/7310/summary.html) against baseline CMSSW_7_5_X_2015-04-23-1100 show no significant differences.

**Pull request merged**
