### PR TITLE
HcalDQM: Update for Run3 based on recent commissioning runs

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

Removed all VME related plots and tasks because no VME in Hcal anymore.
Added and modified some plots in the TPTask --> Affects TPTask
Made change to the charge averaged time calculation requested from Hcal operation colleagues--> affects DigiTask
Reduce the y-axis of FiberuTCAFiberCh to exclude channels. --> Affects RawTask

#### PR validation:
Tested with `cmsRun hcal_dqm_sourceclient-live_cfg.py` and `cmsRun hcalreco_dqm_sourceclient-live_cfg.py` on recent data, private DQM plots reflects the desired changes.

### CODE REVIEW

**Comment by abdoulline** [comment]
@lwang046   commissions -> commissioning (runs) ?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@lwang046 there seems to be a shift in the timing: https://tinyurl.com/ydjyn9n2
In other cases plots are added but empty: https://tinyurl.com/yflw9ra8    https://tinyurl.com/yfsqam6f
Is that expected?

**Comment by lwang046** [comment]
Hi @jfernan2 yeah in the first case the time is calculated as charge averaged time without subtracting noise, a right shift looks reasonable from the calculation formula 
```
for (unsigned int i = i_start; i <= i_end; ++i) {
         double q = dopedsubtr ? adc2fCDBMinusPedestal(conditions, calo_samples, did, digi, i) : calo_samples[i];
         sumQ += q;
         sumQT += (i + 1) * q;
       }
      return (sumQ > 0 ? sumQT / sumQ - 1 : constants::GARBAGE_VALUE);
```

In the second case there is a strong energy cut (>~1GeV) on the digis that can enter the plot.

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
