### PR TITLE
PFProducer fix for PFMuonAlgo's fillPSetDescription

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

Use the PFMuonAlgo's fillPSetDescription for PFMuonAlgo (instead of PFEGammaFilters's one). This was an oversight of the previous refactor work.
This fix was made based on the issue reported here: https://github.com/cms-sw/cmssw/issues/30849.

Also, some functions of PFMuonAlgo were made static to simpler calls from GeneralTracksImporter(WithVeto).

#### PR validation:
 
Made sure it compiles. Also ran matrix test 10824.0 (2018 ttbar) and made sure that the output doesn't have any change.
Also tested with 11634.0 (ttbar 2021) and 23234.0 (ttbar 2026D49).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport.

@bendavid @guitargeek

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
This branch has conflicts that must be resolved
Conflicting files
HLTrigger/Configuration/python/customizeHLTforCMSSW.py

**Comment by hatakeyamak** [comment]
> This branch has conflicts that must be resolved
> Conflicting files
> HLTrigger/Configuration/python/customizeHLTforCMSSW.py

Right. I can fix that, but can I ask a quick question? Basically I want to delete all current parameters under e.g.
process.hltPartcielFlow.PFMuonAlgoParameters and want fillPSetDescription to populate them. In that case,
> for producer in producers_by_type(process, "PFProducer"):
>        del producer.PFMuonAlgoParameters
is sufficient, or better to explicitly list correct parameters in HLTrigger/Configuration/python/customizeHLTforCMSSW.py which should eventually populate various HLT configs.

producer.PFMuonAlgoParameter

**Comment by slava77** [comment]
> For now, I assumed the former.

makes sense to me

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
```
  PFMuonAlgoParameters = cms.PSet(
    maxDPtOPt = cms.double(1),
    trackQuality = cms.string('highPurity'),
    ptErrorScale = cms.double(8),
    eventFractionForCleaning = cms.double(0.5),
    minPtForPostCleaning = cms.double(20),
    eventFactorForCosmics = cms.double(10),
    metSignificanceForCleaning = cms.double(3),
    metSignificanceForRejection = cms.double(4),
    metFactorForCleaning = cms.double(4),
    eventFractionForRejection = cms.double(0.8),
    metFactorForRejection = cms.double(4),
    metFactorForHighEta = cms.double(25),
    ptFactorForHighEta = cms.double(2),
    metFactorForFakes = cms.double(4),
    minMomentumForPunchThrough = cms.double(100),
    minEnergyForPunchThrough = cms.double(100),
    punchThroughFactor = cms.double(3),
    punchThroughMETFactor = cms.double(4),
    cosmicRejectionDistance = cms.double(1)
  ),
```

**Comment by hatakeyamak** [comment]
> ```
>   PFMuonAlgoParameters = cms.PSet(
>     maxDPtOPt = cms.double(1),
>     trackQuality = cms.string('highPurity'),
>     ptErrorScale = cms.double(8),
>     eventFractionForCleaning = cms.double(0.5),
>     minPtForPostCleaning = cms.double(20),
>     eventFactorForCosmics = cms.double(10),
>     metSignificanceForCleaning = cms.double(3),
>     metSignificanceForRejection = cms.double(4),
>     metFactorForCleaning = cms.double(4),
>     eventFractionForRejection = cms.double(0.8),
>     metFactorForRejection = cms.double(4),
>     metFactorForHighEta = cms.double(25),
>     ptFactorForHighEta = cms.double(2),
>     metFactorForFakes = cms.double(4),
>     minMomentumForPunchThrough = cms.double(100),
>     minEnergyForPunchThrough = cms.double(100),
>     punchThroughFactor = cms.double(3),
>     punchThroughMETFactor = cms.double(4),
>     cosmicRejectionDistance = cms.double(1)
>   ),
> ```

Right. These are the right parameter sets for PFMuonAlgoParameters. Can I assume the PR can stay as it is?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
The whole PR basically consists in the one line change
https://github.com/cms-sw/cmssw/pull/30936/files#diff-24b7d20f1967c466ee0593961eb6c237R351

As such, I think this can fix the issue #30849. On the other hand, I don't fully understand what @guitargeek means when he asks in that issue to remove "the configuration parameters from the constructor of PFMuonAlgo (after all it has its own fillPSetDescription function)", and let "the PFProducer configure the PFMuonAlgo correctly".

Since PFMuonAlgo has its own parameters validation, even without the fix in this PR the correct parametes were correctly set by it at their default value. @guitargeek does this PR correspond to what you suggested in the github issue, or were you suggesting something different?

**Comment by guitargeek** [comment]
Hi! With removing the "the configuration parameters from the constructor of PFMuonAlgo" I meant to not define the default parameter values in the constructor of PFMuonAlgo via the `edm::ParameterSet::exists()` hack:

https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L35
https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L20

The `fillPSetDescription` function makes these defaults redundant which might cause trouble down the line, e.g. if the defaults are changed later but not kept in sync. So in the issue, I suggested not only to fix the one line in PFProducer but also to address the underlying problem of redundant defaults by not using `edm::ParameterSet::exists()` anymore.

**Comment by perrotta** [comment]
> Hi! With removing the "the configuration parameters from the constructor of PFMuonAlgo" I meant to not define the default parameter values in the constructor of PFMuonAlgo via the `edm::ParameterSet::exists()` hack:
> 
> https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L35
> https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L20
> 
> The `fillPSetDescription` function makes these defaults redundant which might cause trouble down the line, e.g. if the defaults are changed later but not kept in sync. So in the issue, I suggested not only to fix the one line in PFProducer but also to address the underlying problem of redundant defaults by not using `edm::ParameterSet::exists()` anymore.

Ah, ok, I understand now what you meant!

Therefore, the suggestion here is to complement what already in this PR with a modification of PFMuonAlgo as:
```
      maxDPtOPt_(iConfig.getParameter<double>("maxDPtOPt")),
      etc.
```
and remove the definition of the templated function `getParameter` from there. Correct?

As such, this would prevent bad configurations in possible future applications.

**Comment by guitargeek** [comment]
Yep! Thanks for writing explicitly what the required changes are.

**Comment by perrotta** [comment]
> Thank you for comments.
> 
> I am aware of the suggestion of staying away from the edm::ParameterSet::exists(), but we have to note that PFMuonAlgo is used from both PFProducer and PFBlockProducer, and PFBlockProducer is not using fillDescriptions, so if we remove this now, it will cause a crash. So, I was hoping that this will be considered as an intermediate fix. Or, if you have suggestions on how to stay away from edm::ParameterSet::exists() in PFMuonAlgo with PFBlockAlgo/Producer as it is, I will be certainly happy to adopt it.

Thank you @hatakeyamak 
What about adding a method in PFMuonAlgo that will be temporarily called only by PFBlockProducer and sets those default values for the parameters?

**Comment by guitargeek** [comment]
That is actually a design problem with the PFMuonAlgo which tries to do too much in one class. The functionality required by the PFBlockProducer is this one: https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc#L120

It just requires the configurable parameter `maxDPtOPt`. Maybe it would be better to turn `PFMuonAlgo::hasValidTrack` into a static/free function and add `maxDPtOPt` to the configuration of `GeneralTracksImporter`? Then the configuration would be also more explicit in the configuration files/provenance and not sneaked in via the `exists()` mechanism.

**Comment by hatakeyamak** [comment]
> That is actually a design problem with the PFMuonAlgo which tries to do too much in one class. The functionality required by the PFBlockProducer is this one: https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc#L120
> 
> It just requires the configurable parameter `maxDPtOPt`. Maybe it would be better to turn `PFMuonAlgo::hasValidTrack` into a static/free function and add `maxDPtOPt` to the configuration of `GeneralTracksImporter`? Then the configuration would be also more explicit in the configuration files/provenance and not sneaked in via the `exists()` mechanism.

I think this makes sense. Will try to update along this line.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- A wrongly asssigned PSet in the PFProducer code is here correctly changed to the PFMuonAlgo one, as it should
- That wrongly assigned PSet was ineffective to the previous code, because of automatic switches to the default parameter: during the review, and in the associated github issue #30849, it was pointed out that such a replacement was not safe in case one really wanted to assign new parameters and by mistake some wrong one is also supplied
- The latest commits in this PR address that issue, which looks like being solved here
- Jenkins tests pass and show no differences, as they should

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
