### PR TITLE
Add back a workflow removed by accident in commit 14bf693

### PR DESCRIPTION
**Pull request by hengne**
Add back wrongly removed workflow SMS-T1tttt_mGl-1500_mLSP-100_13 in commit 14bf693

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
ciao @hengne 

is this : https://cmsweb.cern.ch/das/request?input=dataset%3D%2FRelValSMS-T1tttt_mGl-1500_mLSP-100_13%2FCMSSW_7_6_0_pre2-75X_mcRun2_asymptotic_v2-v1%2FGEN-SIM&instance=prod%2Fglobal 

the GEN-SIM which will be picked up by the wf beoing put back ?

Cheers, G.

**Comment by hengne** [comment]
Hi Giovanni, @*franzoni*

  Yes, this is the GEN-SIM to be used for this workflow.

Cheers, Hengne



On Fri, Aug 21, 2015 at 2:58 PM, Giovanni Franzoni <notifications@github.com

**Comment by hengne** [comment]
@franzoni

Hi Giovanni, and all,

These 3 errors don't relate to this particular PR.

The errors are caused by failing to query the input minbias datasets at
T2_CH_CERN.

For example for the first error in workflow 1000.0:

The log:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10874/7539/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/cmdLog

where you can see the query:

das_client.py --cache das-cache.file --limit 0 --query 'file
dataset=/MinimumBias/Run2011A-v1/RAW run=165121 site=T2_CH_CERN'

or web interface:
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FMinimumBias%2FRun2011A-v1%2FRAW+run%3D165121+site%3DT2_CH_CERN

And no file can be found for dataset=/MinimumBias/Run2011A-v1/RAW
run=165121 at T2_CH_CERN.

However, if you remove requirement "site=T2_CH_CERN" you can find the files
and find they are existing on the following sites :
T1_US_FNAL_Disk
T1_US_FNAL_MSS
T2_FR_GRIF_IRFU
T0_CH_CERN_Export
T0_CH_CERN_MSS
T1_US_FNAL_Buffer

There is no "T2_CH_CERN".

So, my questions:

1.) What is the reason these files are removed from T2_CH_CERN? Something
like is it removed on purpose, e.g. these are 2011/2012 old data? Where
should I ask this question, or who should know this?

2.) What should I do then? Ask for a data transfer?

Thanks, Hengne

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
Relevant pds/blocks transferred back to Cern

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
