### PR TITLE
Fix undefined behavior in EgammaTowerIsolation

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Avoid doing iterator arithmetic on an empty container. This code was pointed to by the UBSAN IB.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please test
(Test in a newer IB to get rid of the extra commits which end up with changes in the nanoAOD output)

**Comment by perrotta** [comment]
+1
- Technical fix
- Jenkisn tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
