### PR TITLE
Clean up Phase-2 Geometry D86, D88, D91, D92, D93, D94, D97

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR follows the issue https://github.com/cms-sw/cmssw/issues/43251 to clean up all geometries with I14 and I15. With this PR, T24, T25, T30, I14, I15, O8 become unused geometries. They are in the list of obsolete subdetectors. 

We will need a follow up PR, to introduce new geometry with HFNose to replace D94.

FYI @cms-sw/mtd-dpg-l2 @cms-sw/geometry-l2 @cms-sw/trk-dpg-l2 @emiglior @cms-sw/l1-l2 

#### PR validation:
Try to dump D95, D110 config. runTheMatrix gives the proper config files.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@srimanob Please do not remove D94 which is the only one using HFNose

**Comment by bsunanda** [comment]
-1

**Comment by srimanob** [comment]
Hi @bsunanda 

It would be great if you can provide the timeline of your comment in https://github.com/cms-sw/cmssw/issues/43251#issuecomment-2049490514 ? You mentioned that "Also we need to keep a scenario with C20. If D94 is to be deleted we have to create one with C20 as D111". I also mention in the description of this PR that we need that, I did not ignore the request, but no timeline provided on geometry side.

Is it straightforward to create new geometry with C20? The goal of the cleanup is to completely remove geometry with I14 and I15.

Thx.

**Comment by srimanob** [comment]
I make a draft PR of D115 which is D110 with C20 (C18+HFNose)

**Comment by bsunanda** [comment]
Please do not make that one. I am making one myself. I am committing it now
________________________________

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
hold

We wait a bit until sample in 14_0 is available

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
unhold

**Comment by AdrianoDee** [comment]
I was thinking, shall we keep the geometries that have been used as baseline for a while and have been used for major productions? 

I'm thinking of D88 in this context. I'm asking this since, for example, I remember that at the time of the HLT Phase2 TDR we used D49 and then we couldn't have a fair comparison between what we documented there and what was developed in the months after (being in a newer release were D49 was dropped).

**Comment by srimanob** [comment]
> I was thinking, shall we keep the geometries that have been used as baseline for a while and have been used for major productions?
> 
> I'm thinking of D88 in this context. I'm asking this since, for example, I remember that at the time of the HLT Phase2 TDR we used D49 and then we couldn't have a fair comparison between what we documented there and what was developed in the months after (being in a newer release were D49 was dropped).

The cleaning has a reason behind. Keeping old geometry means we need to keep code related to that geometry also. This will make new code more complicated, something may change in between, i.e. detID. See https://github.com/cms-sw/cmssw/issues/43251#issuecomment-2199591820

**Comment by AdrianoDee** [comment]
> The cleaning has a reason behind. Keeping old geometry means we need to keep code related to that geometry also. This will us pay more price, because new code will come with more complicated structure, something may change in between, i.e. detID. See https://github.com/cms-sw/cmssw/issues/43251#issuecomment-2199591820

I see, understood: maintainability

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by bsunanda** [comment]
+geometry

**Comment by antoniovilela** [comment]
+1

**Comment by mmusich** [comment]
@srimanob after this PR a bunch of unit tests relying on deprecated geometries have started to fail, see [logs](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el9_amd64_gcc12/www/tue/14.1-tue-23/CMSSW_14_1_X_2024-08-20-2300?utests). 
For next clean-up a full cmssw test would be commendable.

**Comment by srimanob** [comment]
> @srimanob after this PR a bunch of unit tests relying on deprecated geometries have started to fail, see [logs](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el9_amd64_gcc12/www/tue/14.1-tue-23/CMSSW_14_1_X_2024-08-20-2300?utests). For next clean-up a full cmssw test would be commendable.

Thx Marco. Sorry for that. I have on my list to update the placeholder of geometry, but I have not managed it.

**Comment by mmusich** [comment]
> Sorry for that. I have on my list to update the placeholder of geometry, but I have not managed it.

No problem, I can give it a try.

**Comment by srimanob** [comment]
We have these 2 placeholders that you can use. By the way, it is still D98. If you would use it, you may consider to move it to D110.

1. https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/GeometryExtended2026DefaultReco_cff.py
2. https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/GeometryExtended2026Default_cff.py
3. https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/GeometryDD4hepExtended2026DefaultReco_cff.py
4. https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/GeometryDD4hepExtended2026Default_cff.py

**Comment by mmusich** [comment]
> We have these four placeholders that you can use. By the way, it is still D98. If you would use it, you may consider to move it to D110.

I have opened https://github.com/cms-sw/cmssw/pull/45764 as a draft. Some tests still fail after moving to the newest geometry (`D110`). Some more work is needed to make them run (or they could fall-back to some earlier Tracker geometry without the sensor splitting in TBPX Layer1).

**Pull request merged**
