### PR TITLE
Excluded gluons and quarks from Geant4 tracking

### PR DESCRIPTION
**Pull request by civanch**
Enabled exclusion of gluons and quarks from Geant4 tracking. Normally this should not happens, if event generator providing correct HepMC status code, but unfortunately, this was observed for some XeXe generators. The problem is discussed at SIM meeting during December CMS week: https://indico.cern.ch/event/684826/contributions/2812929/attachments/1570329/2476913/FullSimDec.pdf 

Also std::abs is used in this class instead of fabs, clean-up of internal methods: pdg code is used instead of pointer, LogInfo and LogWarnings are revised and extended. 

Should not affect results.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
-1
first understand why this should not be fixed at the GEN level AND understand if it is a physics bug or not.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , this PR does not include exceptions but is improving LogInfo and LogWarnings, that may be useful indeed. I will contact with generator peoples but would not expect any fast solutions because this is concern of various generator developers. So, it is worse to merge this PR.

**Comment by civanch** [comment]
@davidlange6 , may be this can be merged?

**Comment by civanch** [comment]
@davidlange6 , a reference on the talk is added to this PR description. The discussion with generator conveners is started, if any modification will be needed it will be implemented in the new PR.

**Comment by civanch** [comment]
please test

**Pull request merged**
