### PR TITLE
[NanoAOD] Add UParT electron and muon raw scores

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR adds the electron and muon UParT raw scores in NanoAOD.

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes MiniAOD workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
