### PR TITLE
[PPS] Thread-safe ES condition retrieval

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

This PR replaces all `edm::EventSetup::get<TRcd>().get(..., edm::ESHandle<T>)` calls to the thread-safe equivalent `T edm::EventSetup::getData(edm::ESGetToken<T, TRcd>)` member in the PPS environment (both in local reconstruction and validation codes).
It also drops the `CTPPSPixelGainCalibrationDBService` helper object made trivial by this new retrieval method.

#### PR validation:

Code compiles, runs, matrix tests all passing. Detailed validation (run 2 reco + direct simulation) performed by @jan-kaspar and successfully passing.

#### if this PR is a backport please specify the original PR and why you need to backport that PR: N/A

Before submitting your pull requests, make sure you followed this checklist:
- [x] verify that the PR is really intended for the chosen branch
- [x] verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- [x] verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by forthommel** [comment]
It seems the only differences are found to be in the `LogErrorHarvester` and exceed the scope of this PR.

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32606	dfa2947 
- code changes are in line with the PR description, essentially technical
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
