### PR TITLE
 Only construct tbb::task_scheduler_init once

### PR DESCRIPTION
**Pull request by Dr15Jones**
With the use of TBB version 44_20160316oss, if we create a tbb::task_scheduler_init, then destroy that instance and create another one, we get a segmentation fault because TBB's global state is not properly reset. It is unclear if this is an allowed use case or not. For now (and possible forever) we will only make one per job.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlt** [comment]
Correction, previous version of TBB behaves the same. It's not specific to `44_20160316oss`.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
