### PR TITLE
L1T offline DQM changes for muon resolution plots - 101x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #23279 

Some upgrades to the L1T offline DQM muon resolution histograms.

 - Proper delta phi calculation with wrap around at pi.
 - Relative pT residuals.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
can this be merged please. We would like to have the improvements available in the offline DQM soon.

**Comment by fabiocos** [comment]
@thomreis after passing test in the master pre-release of course

**Comment by thomreis** [comment]
Hi @fabiocos 
did this pass the test in master already? I hope it can make it in 10_1_7.

**Comment by fabiocos** [comment]
+1

validated in CMSSW_10_2_0_pre5

**Pull request merged**
