### PR TITLE
Zero Material 2017 Plan1 Scenario

### PR DESCRIPTION
**Pull request by ianna**
* Requested by EGM/ECAL group who need "ZeroMaterial" particle gun samples to derive
PF cluster energy correction with the 2017 ECAL local reco. 
* Tracker material files provided by @GiacomoSguazzoni 

@arunhep and @franzoni - please, expect a request for a labelled tag for upgrade2017 GT queue by the end of the day. 

@fcouderc - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

These are all new files which should not interfere with existing release validation.

**Comment by franzoni** [comment]
@ianna
Taking note.
Are you still keen on a tutorial on how to create candidates?

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
Here are a few plots from material budget analyser for 2017Plan1ZeroMaterial scenario:
screen shot 2017-03-21 at 17 36 24
screen shot 2017-03-21 at 17 38 00
screen shot 2017-03-21 at 17 38 32
Compare to 2017Plan1:
screen shot 2017-03-21 at 17 57 28
screen shot 2017-03-21 at 17 58 12
screen shot 2017-03-21 at 17 57 45

**Comment by davidlange6** [comment]
+1

**Pull request merged**
