### PR TITLE
[GEOMETRY-UPGRADE] [GCC12] Added missing array header

### PR DESCRIPTION
**Pull request by smuzaffar**
Adding missing `array` header to fix GCC12 build errors

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , rebase is needed.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
