### PR TITLE
adjust HF TP emulator and compression LUTs

### PR DESCRIPTION
**Pull request by akhukhun**
Moving factor of 2 from the HF TP emulation algorithm to the compression LUTs to match what is done online. MC and emulated TP energies will remain unchanged up-to rounding, but emulated TPs will match data exactly after the change. No change in TP scale (no change needed in Layer-1 tables).

### CODE REVIEW

**Comment by christopheralanwest** [comment]
@rekovic Could you review this PR? It was mentioned on slide 3 of the L1T DPG meeting on 15 May 2017: https://indico.cern.ch/event/639391/contributions/2592154/attachments/1459796/2254401/15MAY2017_cawest_l1dpg.pdf

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@rekovic please attend to this PR

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
