### PR TITLE
new Global Tags including PTracker parameters for geometry

### PR DESCRIPTION
**Pull request by audrium**
This new set of Global Tags adds new condition object - PTrackerParams to all supported scenarios

### CODE REVIEW

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@ianna these GTs contains the records you need.

**Comment by diguida** [comment]
+1

**Comment by ianna** [comment]
@diguida - the tags are not readable due to old schema in V1

**Comment by ianna** [comment]
@davidlange6 - PTrackerParameters tests fail. If the GT contains only geometry tag updates, I'd suggest not to merge the PR.

**Comment by diguida** [comment]
@ianna @davidlange6 
We are moving the dropbox to the latest version with your changes in.

**Comment by davidlange6** [comment]
@diguida - I take it that this PR is now obsolete (and doesn't merge). I'm closing it.

**Comment by ianna** [comment]
@diguida and @davidlange6 - please, take this PR along with #7966

**Comment by diguida** [comment]
@ianna 
this PR has been superseded by #8872 so you have all the ingredients in the GT.

**Comment by ianna** [comment]
@diguida - hmm.. the default GT in #8872 is MCRUN1_74_V6, but I do not see PTrackerParameters tag there. It only appears in MCRUN1_75_V0.

**Comment by diguida** [comment]
@ianna you anticipated me ;-)
Comment to myself: #8872 is only for 741 onwards. This correct set of GT is the one in this PR.
I will make a new branch out of it.

**Comment by diguida** [comment]
@ianna @davidlange6 
@audrium is preparing the new PR with the new GT (yesterday it was impossible for me).
Once done, please do the following:
1. rebase your branch for #7966 on top of `CMSSW_7_5_X_2015-05-05-1100`
2. cherry-pick the commit by @audrium 
3. do your tests
4. The bot will run RelVals, as no unit tests will be failing.

**Comment by audrium** [comment]
@ianna please take a look into this PR: https://github.com/cms-sw/cmssw/pull/8970

**Comment by diguida** [comment]
@audrium thanks! It looks ok. I have just launched the tests.

**Pull request closed without merging**
