### PR TITLE
Include DeepCSV in HLTDebug event content (update HLT menu)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR is an update of the HLT menu.
The main reason is to include DeepCSV in HLTDebug event content (see #23513 and CMSHLT-1905).
This will restore the release validation plots for b-tagging @ HLT

Based on CMSSW_10_2_X_2018-06-10-2300

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
