### PR TITLE
Add small changes in CondCore for PPS proton reco, and serialization …

### PR DESCRIPTION
**Pull request by wpcarvalho**
…test code for LHCOpticalFunctions

#### PR description:

This PR includes: 

- Minor changes needed for reading(writing) optical functions data from(into) POOL databases, consumed by the proton reconstruction introduced by the recently merged PR #25495. 

- A serialization test code for the condition formats `LHCOpticalFunctionsSet` and `LHCOpticalFunctionsCollection` introduced in #25495.

#### PR validation:

Tests run: just followed https://cms-sw.github.io/PRWorkflow.html.

### CODE REVIEW

**Comment by wpcarvalho** [comment]
I forgot to add that  **this PR is essential for UL re-reco**.

**Comment by fabiocos** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by wpcarvalho** [comment]
Hi, still missing a couple of approvals. Target is last open CMSSW_10_6_X release (deadline tomorrow). These small changes are essencial for PPS DB usage in UL reco. Many thanks for reviewing.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
