### PR TITLE
Make mutable counters as static atomic in RecoTau plugins

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Make std::atomic a few mutable counters in some RecoTauTag/RecoTau plugins, for thread safety.
Issue originally reported by the static analyzer during PR automatic tests

#### PR validation:

scram build succeeds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
+1
-Technical: make counters for warning printouts static and atomic
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
