### PR TITLE
Fixup of L1REPACK for tasks

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Follow on fixup as suggested by Matti, #28006 

#### PR validation:

TSG tests

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by fabiocos** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
