### PR TITLE
[HCAL] Fix rechit flags for R45 filter (backport of PR23777)

### PR DESCRIPTION
**Pull request by jaehyeok**
Backport of https://github.com/cms-sw/cmssw/pull/23777 for 10_1_X

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@Martin-Grunewald @gennai
As asked at the TSG meeting yesterday here the backport of the HCAL noise filter fix in the 10_1.

@deguio

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@kpedro88 
This is the HCAL PR for the 10_1 release

**Comment by kpedro88** [comment]
Backport of #23777

**Comment by kpedro88** [comment]
@slava77 @perrotta please check this one as well

**Comment by jfernan2** [comment]
+1

**Pull request merged**
