### PR TITLE
Add function to refine FastSim DeepJet discriminators

### PR DESCRIPTION
**Pull request by wolfmor**
#### PR description:

Requires: https://github.com/cms-data/PhysicsTools-NanoAOD/pull/14

This PR adds a function that uses a regression neural network to refine the DeepJet discriminators of CHS jets in NanoAOD for FastSim to better match FullSim. The function can be called by including the option `--customise PhysicsTools/NanoAOD/jetsAK4_CHS_cff.nanoAOD_refineFastSim_bTagDeepFlav` in the cmsDriver command and requires the ONNX model added in the above mentioned PR to cms-data. The original values are copied to new variables named with the suffix "unrefined".

Due to a bug in ONNX runtime 1.10.0 (see [here](https://github.com/microsoft/onnxruntime/issues/10305)) graph optimization has to be disabled to evaluate the model. The corresponding option is implemented in BaseMVAValueMapProducer for the ONNX backend.

The technique has been presented at the [FastSim Days 2022 Workshop](https://indico.cern.ch/event/1191657/contributions/5016864/). There are plans to make this the default for FastSim in the future and possibly to extend to further collections/variables.

A complete set of commands to produce NanoAOD files with refined DeepJet discriminators is:

`cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi  --relval 100000,1000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,VALIDATION:@standardValidation,DQM:@standardDQMFS -n 10 --conditions auto:run2_mc --beamspot Realistic25ns13TeV2016Collision --datatier GEN-SIM-DIGI-RECO,DQMIO --eventcontent FEVTDEBUGHLT,DQM --fast  --era Run2_2016`

`cmsDriver.py step3  -s PAT --era Run2_2016 -n -1 --conditions auto:run2_mc --mc  --datatier MINIAODSIM --eventcontent MINIAODSIM --filein file:TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_VALIDATION_DQM.root --fast`

`cmsDriver.py  --python_filename NanoAODrefined_cfg.py --eventcontent NANOAODSIM --fast --customise Configuration/DataProcessing/Utils.addMonitoring,PhysicsTools/NanoAOD/jetsAK4_CHS_cff.nanoAOD_refineFastSim_bTagDeepFlav --datatier NANOAODSIM --fileout file:step3_NANO.root --conditions auto:run2_mc --step NANO --filein "file:step3_PAT.root" --era run2_nanoAOD_106Xv2 --mc -n -1`

#### PR validation:

The neural network has been trained on GEN-synchronized FastSim/FullSim jet pairs from SUSY simplified model T1tttt events and has been validated also in TTbar events. In both cases, considerably improved agreement with the FullSim output and an improvement in correlations among output observables and external parameters is seen.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Needs to be backported to 12_6.

@sbein @kpedro88

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type btv

**Comment by kpedro88** [comment]
please test

**Comment by mandrenguyen** [comment]
@wolfmor Would it be worth adding the driver commands you list in the PR description as a RelVal workflow?  In particular, as you indicate that further developments are coming.

**Comment by kpedro88** [comment]
@mandrenguyen we're working on exactly that

**Comment by kpedro88** [comment]
test parameters:
pull_requests = https://github.com/cms-data/PhysicsTools-NanoAOD/pull/14
workflows = 135.14

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@cms-sw/pdmv-l2 @cms-sw/xpog-l2 I added a NANOAOD step to all relval_standard Run2 FastSim workflows for consistency and to have a baseline for comparison to the workflow with refinement.

**Comment by mandrenguyen** [comment]
abort test

**Comment by mandrenguyen** [comment]
enable nano

**Comment by kpedro88** [comment]
@mandrenguyen thanks, I wasn't aware of the new `enable nano` setting. @smuzaffar this doesn't seem to be documented in the [cms-bot commands](http://cms-sw.github.io/cms-bot-cmssw-cmds.html)?

**Comment by smuzaffar** [comment]
thanks @kpedro88 for pointing this out, I will update the bot docs

**Comment by mandrenguyen** [comment]
+reconstruction
New workflows run.  Beyond that it's probably more xpog business than reco

**Comment by swertz** [comment]
Hi @wolfmor , at last week's XPOG meeting, we discussed letting the default discriminators untouched while adding the new refined discriminators with a different name. 

Since we were thinking of the backport to 10_6_X for RunUL FastSim samples, what I would suggest is to merge your PR as it is now to master (ie. default = refined discriminators), while the backport to 10_6_X would make sure the default taggers are not changed.

For a backport to 12_6_X one would do the same, but since your PR only touches CHS jets which are not used in Run3 12_6_X samples, this will have no effect.

**Comment by sbein** [comment]
@swertz sounds good to me. For the Phase0/Phase1 differences, I would slightly tend to perform that check as part of the pdmv validation for these changes, which will also include examining the impact of the refinement on a wider variety of physics processes, e.g., QCD, ZLL, etc.

**Comment by kpedro88** [comment]
@swertz while I understand the desire to avoid changing defaults, I think we should also consider how to facilitate user analysis. Requiring users to change all of their branch names to use the corrected collections just increases the margin for error. Maybe this can be a temporary measure until the corrections are validated (at which point I would argue we should treat them like e.g. standard JECs)?

**Comment by swertz** [comment]
> For the Phase0/Phase1 differences, I would slightly trend towards performing that check as part of the pdmv validation for these changes, which will also include examining the impact of the refinement on a wider variety of physics processes, e.g., QCD, ZLL, etc.

Will that include a comparison between the refined distribution and the corresponding FullSim distribution, like you showed last week? That seems out of the scope of the standard Pdmv validation workflow... If not, shouldn't this be checked beforehand?

> Requiring users to change all of their branch names to use the corrected collections just increases the margin for error. Maybe this can be a temporary measure until the corrections are validated (at which point I would argue we should treat them like e.g. standard JECs)?

We fully agree, and moreover we cannot afford to increase the event size by duplicating variables (refined/unrefined)... this is fine for now as the refinement is being developed, but will have to be cleaned once it is well-validated.
This is also why I was suggesting to merge it as it is now, and to have the refined variables as default in the upcoming NanoV12 campaign.

My point was about backports to 12_6_X or 10_6_X, for existing NanoAOD v11/v9 campaigns: we **cannot** change the meaning of variables for an existing campaign, it will just create confusion. However, (in this particular case) we're fine with adding these additional refined variables for new FastSim samples that will be submitted in these ongoing campaigns.

**Comment by swertz** [comment]
> The pdmv comparison will be FullSim vs FastSim

Perfect then :+1:

> It would actually be more straightforward for the variable names to stay as they are so we do not have to edit the DQM code to create additional plots comparing NANO FullSim btag with FastSim btag_refined

Yes, that's what I was saying. For this PR we can go with the current proposal. But, for backports to 10_6 and 12_6, we will insist that the default variables be left untouched.

**Comment by swertz** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
Hi @wolfmor @kpedro88 @sbein 
SUS is planning for Run3-2022 FastSim production in 12_4. Should this PR and ONNX model for refinement be backport to 12_4? Or if there will be technical detail with backport? Thanks.

**Comment by sbein** [comment]
Hi @srimanob yes, ideally this should be backported so that the refinement can be used in Run 3. My plan was once the backport to UL is merged (https://github.com/cms-sw/cmssw/pull/40828#issuecomment-1438124512)[https://github.com/cms-sw/cmssw/pull/40828#issuecomment-1438124512], I will do the backport to 12_4. This will probably take another week.

**Comment by srimanob** [comment]
Thanks @sbein 
So I will note this in the production plan to @cms-sw/pdmv-l2

**Comment by srimanob** [comment]
Hi @sbein @kpedro88 
Will we face technical issue if backport to 12_6 first? This is not about Run-2, but Run-3 2022 NanoV11. Thx.

**Comment by swertz** [comment]
Since the refinement runs at Nano level, for Run3 samples why can't you simply use the imminent NanoV12 campaigns in 13_0 that will take 12_4 MINI samples as input?

**Comment by srimanob** [comment]
Hi @swertz 
What I am asking is based on the production done for Summer22 campaign. Currently, they run NanoV10 and  11. If SUS want to mix Fast/Full, it is better to run the same version. So either run V12 in production, or backport to 12_6 for V11. I can put this comment on the discussion also. Thx.

https://cms-pdmv.cern.ch/mcm/campaigns?prepid=Run3*22*Nano*&page=-1&shown=16447

**Comment by swertz** [comment]
Hi @srimanob , so much is clear, I was also referring to Summer22 MC. Don't forget that current Summer22 and Nano v10/11 is not "complete" in the sense that many jet-related ingredients (PUPPI tune, taggers) were not updated yet. NanoV12 will be run on Summer22 MC and will contain all the recommended ingredients for analysis of Run3 data.

I can see why you'd want some FastSim MC in 12_6/NanoV11 to be able to quickly implement Fast/Full comparisons with the existing samples, but just keep in mind that for physics results, in most cases you'll need to use NanoV12 anyway.

Another point: this PR only implemented refinement for taggers in CHS jets (which makes sense for the Run2 UL backport), but Run3 samples contain PUPPI jets...

**Pull request merged**
