### PR TITLE
Add HL-LHC high-density beamspot scenario

### PR DESCRIPTION
**Pull request by mdhildreth**
Add beamspot scenario corresponding to highest expected densities at HL-LHC.  NOT TESTED YET! It runs...  Please don't merge yet.

### CODE REVIEW

**Comment by davidlange6** [comment]
@mdhildreth - I guess you missed a change to define HLLHCHighDensityVtxSmearingParameters

that said, as we all agreed months ago not to develop further 620_SLHCX, the better approach is to consider how to implement this via a customize fragment (so far that would be trivial)

**Comment by mdhildreth** [comment]
Ok, I can do that...  I was at least finally able to test that it actually works properly.

**Comment by mdhildreth** [comment]
Oh, huh, I did change Configuration/StandardSequences. I wonder why that didn't show up... Anyway, I can do it with a customization.

**Comment by mdhildreth** [comment]
This would go into Configuration/GenProduction, right?

**Comment by mdhildreth** [comment]
@davidlange6 :  This would go into Configuration/GenProduction, right?

**Comment by davidlange6** [comment]
no - on command line

--customise_commands 'process.simHcalDigis.markAndPass = cms.bool(True) \n'

**Comment by mdhildreth** [comment]
@davidlange6 : Ok, yes that should be even more trivial.

**Pull request closed without merging**
