### PR TITLE
Update GEN-SIM string in runTheMatrix for 11_2_X

### PR DESCRIPTION
**Pull request by chayanit**
This is a PR to update GEN-SIM strings in runTheMatrix as requested by PPS (#31943 and #32003) and issue reported in #32125 . 

The validation has not yet done since there are many missing GEN-SIM files, so I would like to see the list of missing inputs and produce them accordingly. Then I will update the description

@silviodonato, could you provide the command line to run -i all --ibeos test so I can get the full list of samples causing error report and produce them accordingly?

### CODE REVIEW

**Comment by silviodonato** [comment]
please test
@smuzaffar added a test that checks the output of the DAS query. This should allow you to find the missing files.

**Comment by silviodonato** [comment]
the new feature is cms-sw/cms-bot#1412

**Comment by silviodonato** [comment]
> -1
> 
> Tested at: [43ce8b3](https://github.com/cms-sw/cmssw/commit/43ce8b3667703febd49d68fb620d2c3ff992a122)
> 
> CMSSW: CMSSW_11_2_X_2020-11-13-2300
> SCRAM_ARCH: slc7_amd64_gcc820
> You can see the results of the tests here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fa882f/10751/summary.html
> 
> I found follow errors while testing this PR
> 
> **Failed tests: RelVals**
> 
>     * **RelVals**:
> 
> 
> When I ran the RelVals I found an error in the following workflows:
> 23434.999 step2
> 
> runTheMatrix-results/23434.999_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/step2_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU.log
> 
>     * **DAS Queries**: The DAS query tests failed, see the summary page for details.

@chayanit  you can find the error looking for "ERROR" in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fa882f/10751/dasqueries/runall-report-step123-.log

The crash of the pileup samples are visible in the Matrix tests.

@smuzaffar did you expect to see the workflows with errors https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-fa882f/10751/dasqueries/failed_workflows.log ?

**Comment by smuzaffar** [comment]
@silviodonato , yes errors should go in the fail_workflow log but I was search for wrong keyword. This is now fixed https://github.com/cms-sw/cms-bot/commit/f4236bff77fe181715925e03b171bb183934ba3e

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
@silviodonato not sure why the test is taking ages to finish? It has been testing for 13 hours already.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@chayanit it looks like the tests have never started

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
@silviodonato all of GENSIM input files should be in place now. I'm not sure why it still complains missing DAS. 

There is also a matrix failure for 10224.0 and 23434.999 though

**Comment by qliphy** [comment]
@chayanit   I checked "/RelValMinBias_14TeV/CMSSW_11_2_0_pre8-112X_mcRun4_realistic_v3_2026D49noPU-v1/GEN-SIM" on DAS and got "DAS unable to find any results for your query." :
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValMinBias_14TeV%2FCMSSW_11_2_0_pre8-112X_mcRun4_realistic_v3_2026D49noPU-v1%2FGEN-SIM

**Comment by chayanit** [comment]
> @chayanit I checked "/RelValMinBias_14TeV/CMSSW_11_2_0_pre8-112X_mcRun4_realistic_v3_2026D49noPU-v1/GEN-SIM" (used in step2 for workflow 23434.999) on DAS and got "DAS unable to find any results for your query." :
> https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValMinBias_14TeV%2FCMSSW_11_2_0_pre8-112X_mcRun4_realistic_v3_2026D49noPU-v1%2FGEN-SIM

Ah yes, I forgot the MB thanks @qliphy

**Comment by chayanit** [comment]
@smuzaffar , I have produced many GENSIM files but it still complains DAS error for existing files. Is this something to be done with the check at T2 CERN? All the GENSIM files are at T2 FNAL...

**Comment by smuzaffar** [comment]
@chayanit , looks like the new data is not yet known to das services. For example the following (note it is without T2 CERN) does not return any thing. Once the generated data is published and known to das then PRs/Ibs can access it

```
dasgoclient --limit 0 --query 'file dataset=/RelValMinBias_13/CMSSW_11_2_0_pre8-112X_mc2017_realistic_v3-v1/GEN-SIM'
```

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
+1

@silviodonato I think this PR is ready now. All GS files have been produced

**Comment by qliphy** [comment]
@cms-sw/upgrade-l2  Do you have any comments?  This PR is needed for #32003

**Comment by silviodonato** [comment]
merge
let's try this in the morning IB

**Comment by silviodonato** [comment]
@chayanit we have some problems with the pileup samples (see https://github.com/cms-sw/cmssw/issues/32237)

**Pull request merged**
