### PR TITLE
correctly update boundary box preventing overwriting in case a hit ha…

### PR DESCRIPTION
**Pull request by clelange**
…s x value = 0

This fixes a bug in the HGCal layer clustering: the "box" that was built from the hits that pass the energy thresholds was erroneously reset in case a hit had an x-value of 0. This limited the area used for the clustering, losing whole layer clusters for no reason. It's fixed now using a boolean for each layer. The consequence is that some multiclusters will have more energy than before (and a couple more layer clusters will be built).

### CODE REVIEW

**Comment by kpedro88** [comment]
@clelange please apply code checks

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
On 9/14/17 1:38 PM, Clemens Lange wrote:
> …s x value = 0
> 
> This fixes a bug in the HGCal layer clustering: the "box" that was built
> from the hits that pass the energy thresholds was erroneously reset in
> case a hit had an x-value of 0. This limited the area used for the
> clustering, losing whole layer clusters for no reason. It's fixed now
> using a boolean for each layer. The consequence is that some
> multiclusters will have more energy than before (and a couple more layer
> clusters will be built).
> 


Please provide some plots to illustrate the significance of the changes.

**Comment by clelange** [comment]
Here are some plots that indicate what can happen for a single particle gun sample without PU:
A whole layer that contains a clear particle shower can be missed:
before1
The bounding box in this case ends at (x, y) = (~50, ~50) ignoring the cluster:
before

It's a somewhat random effect, since it depends on the sorting of the RecHits within a layer. After a hit with x=0, it can also happen that the bounding box is actually extended to the correct values. Quantitively, the effect is therefore small, and hardly visible in a large sample. I will check this in a PU sample.

**Comment by slava77** [comment]
On 9/15/17 5:35 AM, Clemens Lange wrote:
> Quantitively, the effect is therefore small, and hardly visible in a
> large sample. I will check this in a PU sample.


Thank you.
The goal for my request to see the effects was to quantify the
significance of the fix.

**Comment by clelange** [comment]
Here are a couple of plots based on 300 events from `/RelValDoubleGammaPt25Eta17_27/CMSSW_9_3_0_pre4-PU25ns_93X_upgrade2023_realistic_v0_2023D17PU200-v2/GEN-SIM-RECO`

There is no visible difference in the kinematic distributions of the layer (2D) and multi-clusters, but one can see some in the multiplicity distributions.

layer cluster pT:
[cluster2d_pt_log.pdf](https://github.com/cms-sw/cmssw/files/1310523/cluster2d_pt_log.pdf)

layer cluster multiplicity:
[cluster2d_N.pdf](https://github.com/cms-sw/cmssw/files/1310526/cluster2d_N.pdf)

multicluster pT:
[multiclus_pt_log.pdf](https://github.com/cms-sw/cmssw/files/1310527/multiclus_pt_log.pdf)

multicluster multiplicity:
[multiclus_N.pdf](https://github.com/cms-sw/cmssw/files/1310528/multiclus_N.pdf)

Overall, as I had written above, the effect is tiny, but random, and it's an obvious fix. Since there are other issues with the current `9_3_0` release that other people will raise, it would be good if this PR also made it into `CMSSW_9_3_X` and `master` (see #20522).

**Comment by slava77** [comment]
On 9/18/17 4:47 AM, Clemens Lange wrote:
> Since there are other issues with the current |9_3_0| release that other
> people will raise, it would be good if this PR also made it into
> |CMSSW_9_3_X| and |master| (see #20522
> <https://github.com/cms-sw/cmssw/pull/20522>)

The statement seems rather assertive that there are known problems.
Can you clarify what are the other issues with 9_3_0?

**Comment by clelange** [comment]
@rovere and @felicepantaleo will be able to comment more, I think they will make the PRs. There is something wrong with the PFCluster position, IIRC the wafer position instead of the cell position is used for their position calculation.

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
- Simple bug fix that does what is expected to do
- Effects on final quantities is rather small, as visible in the plots attached https://github.com/cms-sw/cmssw/pull/20521#issuecomment-330196350, as well as in one of the jenkins tests (20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17)
image

**Comment by davidlange6** [comment]
+1

**Pull request merged**
