### PR TITLE
Strip cluster splitter (MC truth based)

### PR DESCRIPTION
**Pull request by wmtford**
1.  Add a new /test/ module ClusterMCsplitStrips that based on MC truth splits strip clusters associated with more than one SimTrack.
2.  Upon adding BuildFile I found and fixed (with help from Nick McColl) a couple of compilation bugs in ClusterAnalyzer.

### CODE REVIEW

**Comment by wmtford** [comment]
The code added with this PR creates test modules that are not put on the 
path for production reco or relVal.  Is this error unique to this PR?

**Comment by slava77** [comment]
Hi Bill, this seems unrelated to your pull request. 

```
%MSG-e FatalSystemSignal:   DQMGenericClient:postProcessorMuonMultiTrackHLT@endJob  08-Apr-2015 17:38:15 CEST PostEndRun
A fatal system signal has occurred: segmentation violation
%MSG

```
@deguio  Federico, could you please take a look and comment if this is known/fixed "soon"?

**Comment by slava77** [comment]
Bill, please update the subject of the PR (the top-most line) to be more descriptive for self-documentation.
Thank you.

**Comment by wmtford** [comment]
Hi Slava,

Sure, done; I didn't realize there was an edit button there, and the 
auto parsing of my branch name didn't come out very well.

Bill

**Comment by deguio** [comment]
ciao @slava77 
this is something we discussed briefly on a private email thread a couple of weeks ago.
@dmitrijus was investigating this but apparently it is not so easy to reproduce the crash.

@dmitrijus are there news on this side?
thanks,
F.

**Comment by dmitrijus** [comment]
Hi,

I finally managed to reproduce this segfault, it is caused by at least one root bug.
I've send an email and started a hypernews thread with more details.

Dmitrijus

**Comment by slava77** [comment]
@cmsbuild please test
in one of my tests got past a failing step4 by just rerunning.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8673 f6ce954

all changes are in /test subdirectories for code that doesn't run in standard workflows
compilation is enough of a confirmation.
code visually looks OK.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
