### PR TITLE
[MiniAOD] Remove Flag_METFilters from MiniAOD

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR removes the `Flag_METFilters` from MiniAOD and also from NanoAOD by virtue that the flag will not be in the input MiniAODs.  The flag is deprecated and has been unsupported by JME for a while now. The recommendation for analyzers ([twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2)) is to apply the individual noise filter flags. Removing the `Flag_METFilters` flag avoids accidental usage by analyzers with the next MiniAOD and NanoAOD production.

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- ran workflow `25202.0_TTbar_13`  and had checked that the `Flag_METFilters` branch is not in NanoAOD anymore

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
@nurfikri89 Should we remove the definition of `metFilters` in https://github.com/cms-sw/cmssw/blob/3ad0e5763428f6b1fed5ac94ccef67d561c1ee18/RecoMET/METFilters/python/metFilters_cff.py#L97-L123 as well?

**Comment by nurfikri89** [comment]
> @nurfikri89 Should we remove the definition of `metFilters` in https://github.com/cms-sw/cmssw/blob/3ad0e5763428f6b1fed5ac94ccef67d561c1ee18/RecoMET/METFilters/python/metFilters_cff.py#L97-L123 as well?

Yes we should. I missed this part. Will do it now.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
