### PR TITLE
Renaming according to CMSHLT-1463

### PR DESCRIPTION
**Pull request by heppye**
https://its.cern.ch/jira/browse/CMSHLT-1463, propagating to online DQM.

### CODE REVIEW

**Comment by heppye** [comment]
@mtosi, @Martin-Grunewald , @silviodonato , could u please provide a quick comment on this PR? Many thanks, Ye (for BTV@HLT)

**Comment by Martin-Grunewald** [comment]
We'd also need a backport PR for 92X!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by heppye** [comment]
@Martin-Grunewald, backport PR is made, https://github.com/cms-sw/cmssw/pull/19768

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
