### PR TITLE
Run4-hgx281 Update D82 geometry version for HFNose

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update D82 geometry version for HFNose (an older version was used in the past)

#### PR validation:

Tested using the workflow 37034.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar I do not understand the reason of the failure - it is happening to workflows not connected with the changes suggested by this PR

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

It seems to be a glitch on the first test. The latter one is OK.

**Comment by bsunanda** [comment]
@silviodonato @qliphy @cvuosalo @srimanob Can this be included in the pre6?

**Comment by srimanob** [comment]
Urgent

**Comment by bsunanda** [comment]
@ianna Could you approve this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
