### PR TITLE
Monitor track selection MVAs in MultiTrackValidator

### PR DESCRIPTION
**Pull request by makortel**
This PR extends MultiTrackValidator (and the plotting scripts) to optionally monitor track selection MVA variables. The motivation is to provide a monitoring tool for track selection MVA tuning.

The monitoring is enabled only for the `trackValidatorBuildingTrackingOnly` module (monitoring the "built tracks"), because the MVA variables are easily available for those, and the track collection of an iteration N is not biased by the existing track selection of itereration N. The plots include
* Distributions of the MVA variable for true and fake tracks
* Efficiency and fake rate vs. cut on the MVA variable
  * for this I had to extend `DQMGenericClient` to be able to do the accumulation for the "cumulative histograms" also in the other direction
     * not sure if the "ascending"/"descending" nomenclature is the clearest one, better suggestions are welcome
  * from these we can make ROC curves
* Plotting includes also the selection efficiencies of true and fake tracks as a function of the cut to allow direct cross-check with TMVA plots
* Iterations with multiple MVA selections (like initialStep) are treated as follows
  * For the first MVA, histograms are filled for all tracks
  * For the second MVA and onwards, histograms are filled only for the not-yet-selected tracks. There are separate histograms for loose-selected and highPurity-selected tracks.
  * The order of MVA's is the one in `ClassifierMerger.inputClassifiers` of that iteration.

In addition this PR fixes a minor bug in `makeTrackValidationPlots.py` (without any options it makes plots for the "pT>0.9 GeV" folders, while that should be active only with `--ptcut` option).

Tested in CMSSW_8_1_0_pre15, no changes expected in standard workflows. New histograms should appear in "trackingOnly" workflows (e.g. 1325.1, 10024.1), but there should be no changes in existing histograms.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by makortel** [comment]
Generation of alternative-comparisons failed for 25202 with
```
/cvmfs/cms-ib.cern.ch/2016-46/slc6_amd64_gcc530/lcg/root/6.06.08-giojec2/lib/libGraf.so: error adding symbols: Bad address
collect2: error: ld returned 1 exit status
Error in <ACLiC>: Compilation failed!
input_line_18:2:3: error: use of undeclared identifier 'compareAll'
 (compareAll(((*(class TFile **)0x7fddfa076028)), ((*(class TFile **)0x7fddfa076030)), 0, 0, ""))
  ^
```
(but likely not important-enough to relaunch the tests since the relmon exists)

**Comment by slava77** [comment]
strange, considering that all other comparisons passed.
Maybe there was a glitch with cvmfs or smth like that.

@smuzaffar 
Could you please grep for the same ``` Compilation failed ``` in alternative comparisons.
Thank you.

**Comment by smuzaffar** [comment]
sorry @slava77 , you want what?

**Comment by slava77** [comment]
@smuzaffar 
as commented in https://github.com/cms-sw/cmssw/pull/16559#issuecomment-259993654
the workflow 25202 alternative-comparisons failed to compile https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-11-11-1100+16559/16894/alternative-comparisons/runDQMComp-25202.0.log.

I wanted to find out if this is happening frequently.
You probably have interactive access to the output files and could check if there are other compilation failures in runDQMComp-*.log files

**Comment by smuzaffar** [comment]
@slava77 , only workflow 25202.0 has this error.
```
$ grep 'Compilation failed' alternative-comparisons/*.log
alternative-comparisons/runDQMComp-25202.0.log:Error in <ACLiC>: Compilation failed!
```
I will add a check for this include some error/warning the comparison ready message.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
Hi @makortel - could you look at fixing this problem, that seems related to this PR. Thanks !

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc530/CMSSW_8_1_X_2016-11-15-2300/pyRelValMatrixLogs/run/10024.5_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_trackingOnlyPhase1PU70_2017+HARVESTFull_trackingOnly_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_trackingOnlyPhase1PU70_2017+HARVESTFull_trackingOnly_2017.log

**Comment by makortel** [comment]
Thanks David, very likely from this PR. I'll take a look.

**Comment by makortel** [comment]
Forgot to mention here that the fixes are in #16660 (90X) and #16661 (81X).

**Pull request merged**
