### PR TITLE
Revert "Gathering detail plots into directories, online & offline & relval & …"

### PR DESCRIPTION
**Pull request by perrotta**
Reverts cms-sw/cmssw#37852, to have it ready just in case it needs to get merged
See https://github.com/cms-sw/cmssw/issues/38044 for the discussion about the issues with #37852,

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by quark2** [comment]
Hi @perrotta, 

It's not a good idea to revert the PR because it has a lot of other updates which is necessary for the GEM DQM. I'll make a hotfix as soon as possible.

**Comment by ahmad3213** [comment]
+1

**Comment by perrotta** [comment]
+1
- Merging this, in order to build the patch release as soon as possible

**Comment by perrotta** [comment]
merge

**Comment by civanch** [comment]
+1

**Pull request merged**
