### PR TITLE
Move GEM trigger primitive producers from DIGI to L1 step

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In preparation for Run-3 MC productions this PR moves the GEM trigger primitive producers from the DIGI to the L1 step. It is necessary to ensure that all steps (DIGI, L1T, DIGI2RAW, and RAW2DIGI) are run correctly, for all the eras (Run2, Run3, Phase-2). The changes are minimal, so that the names of all producers and analyzers involved remain the same. The GEM TP producers are now in new package `L1Trigger/L1TGEM`.

#### PR validation:

I checked that it runs with WF 11634.0 in CMSSW_11_0_X_2019-10-22-1100.

#### if this PR is a backport please specify the original PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by kpedro88** [comment]
```
tmp/slc7_amd64_gcc820/MakeData/DirCache.mk:182: No such file exists: src/SimMuon/GEMDigitizer/test/GEMPadDigiReader.cc. Please fix src/SimMuon/GEMDigitizer/test/BuildFile.
```

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@rekovic @benkrikler could you please check this PR?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
I see no conflict in my test with the integration of #28183 although both PRs touch the L1 event content

**Comment by fabiocos** [comment]
+1

**Pull request merged**
