### PR TITLE
Mirror the outputs from o2o scripts and fix return codes.

### PR DESCRIPTION
**Pull request by hqucms**

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
hold

**Comment by mmusich** [comment]
@hqucms does a 80x backport exist for this one?

**Comment by franzoni** [comment]
dear @hqucms , can you please report here the outcomes of your tests running o2o ? 
@ggovi will be out of office till August 15th , he'll sign at his return, documenting the tests will facilitate/expedite.

**Comment by hqucms** [comment]
@mmusich Not yet... I would like to finalize the changes with Giacomo in this PR and then backport it to 80X to avoid keeping track of changes in two branches. What do you think?

**Comment by mmusich** [comment]
@hqucms we need a 80X version backported ASAP for testing purposes in the existing environment.

**Comment by hqucms** [comment]
@mmusich Done! https://github.com/cms-sw/cmssw/pull/15338

**Comment by mmusich** [comment]
@hqucms thanks a lot!

**Comment by hqucms** [comment]
@mmusich  You are welcome!

**Comment by hqucms** [comment]
@franzoni @mmusich
The tests on my side all look fine:
- The output from the o2o job is displayed on the screen as they come out.
- And they also seem to be properly logged in the AlCa/DB monitoring system. [e.g., https://cms-conddb-dev.cern.ch/logs/O2O_logs/getRunLog?name=SiStripBadChannel&start_time=2016-07-22%2016%3A02%3A18.624337]
- The return code from the o2o job is propagated back now.
- I removed L164-166 because it seems to create a logic bug later at L197-201 (`if exists is None:` evaluates to False if `exists = False`).

One thing I was discussing with @ggovi is L205, the return code when the O2O job is disabled. From the Strips point of view, this is a failure and we should get a non-zero return code. However, this "disabled" case is probably designed for other situations and may not be relevant to us. Please let me know and I am happy to make changes.

**Comment by ggovi** [comment]
-1 
superseded by 15487

**Pull request closed without merging**
