### PR TITLE
Run3-trk05 Remove unused solids, LV, PV in tob.xml

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove unused solids, LV, PV in tob.xml

#### PR validation:

Use cfg's in Geometry/TrackerCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
I don't understand how the name `Geometry/TrackerCommonData/data/v2/tob.xml` got created. It can be left alone, but the new files need proper XML file names. The new files should be:
```
Geometry/TrackerCommonData/data/tob/v1/tob.xml
Geometry/TrackerCommonData/data/tob/v3/tob.xml
```

**Comment by bsunanda** [comment]
@cvuosalo Geometry/TrackerCommonData/data/v2/tob.xml existed before. I modified that file to v3 and Geometry/TrackerCommonData/data/tob.xml to v1

**Comment by cvuosalo** [comment]
@bsunanda Yes, `Geometry/TrackerCommonData/data/v2/tob.xml` has existed for a while. I think we have to keep it for reference. But the new files should be given correct names, as I listed.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @smuzaffar I think the failures are not due to this PR. Could you please check?

**Comment by smuzaffar** [comment]
please test
lets re-run based on latest IB

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo Could you please sign this

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
