### PR TITLE
 Add 2 new GenFilters for use by HI photon team

### PR DESCRIPTION
**Pull request by harmonicoscillator**
backport of #12510

These two gen filters for Pythia8 are meant to mimic the older ones used with Pyquen, which can be found here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/GeneratorInterface/HiGenCommon/src/EcalGenEvtSelector.cc
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/GeneratorInterface/HiGenCommon/src/EcalGenEvtSelectorFrag.cc

@bi-ran has done some sanity checking between the old filters and new filters which can be found here:
https://twiki.cern.ch/twiki/pub/CMS/MITHIGAnalysis2015/MCFilters.pdf

We would like to include these filters in the 75X series to be used for HI MC production.

### CODE REVIEW

**Comment by richard-cms** [comment]
Hello,

I realize lots of other, more important things are going on now, but is there an expected timeline that this could end up in 75X? We'd really like to make official MC in 75X with these filters.

**Comment by covarell** [comment]
Hello,

For what concerns HINEcalGenSelector I cannot see why the same cannot be obtained using two instances in series of:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/GeneratorInterface/GenFilters/src/MCSingleParticleFilter.cc

for example.

About multi-mother the same could be achieved e.g. modifying 

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/GeneratorInterface/GenFilters/src/MCMultiParticleFilter.cc

to accept a vector of mothers.

Please let me know if I misunderstood something.

**Comment by richard-cms** [comment]
@covarell Thanks for the comments. I will take some time to see if I can get the same results using those two filters.

**Comment by richard-cms** [comment]
@covarell What is the least-intrusive method for adding a vector of mothers to https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/GeneratorInterface/GenFilters/src/MCMultiParticleFilter.cc ? 

I could add the mother vector as an untracked parameter, but sometimes that is frowned upon.

I could add the mother vector as a tracked parameter, but then all previous configs using this filter will break.

Any advice?

**Comment by richard-cms** [comment]
@covarell 
After some testing we can definitely remove HINEcalGenSelector in favor of the already-existing filters, thanks very much for the tip.

For PythiaFilterMultiMother, I think we have to choose one of a few options:
1) Add a new GenFilter (PythiaFilterMultiMother)
2) Extend MCMultiParticleFilter.cc with tracked parameters, potentially breaking older gen fragments
3) Extend MCMultiParticleFilter.cc with untracked parameters, which I have a working prototype for but it's causing some crashes.

I would prefer to go with option 1, since it has minimal risk for backwards compatibility, but let me know if there is strong motivation to extend MCMultiParticleFilter and I will continue working on the prototype.

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
I do not see yet the 8_0_X version of this PR, which is needed

**Comment by richard-cms** [comment]
@covarell I see you found #121510, is that sufficient for 80X version?

**Comment by richard-cms** [comment]
I noticed that @covarell has and cmsbuild have already given +1 here, but this PR is not considered fully signed. Is there information missing? The 80X version appears to be fully signed.

**Comment by slava77** [comment]
This is just a feature of this release being a production release.

**Comment by slava77** [comment]
merge

80X PR is available in  #12510 
this is all new code MC only

**Pull request merged**
