### PR TITLE
Geo2018 with Detailed Cavern and MB4Shiedls for CMSSw_10_3

### PR DESCRIPTION
**Pull request by slomeo**

### CODE REVIEW

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi this looks a workaround, in principle one should be able to use 10_5_X for this, am I correct?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
