### PR TITLE
Run3-gex83F Update SD class initializations in SimG4CMS/HGCalTestBeam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update SD class initializations in SimG4CMS/HGCalTestBeam

#### PR validation:

Use test scripts in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
