### PR TITLE
StallMonitor handles case where module does not prefetch

### PR DESCRIPTION
**Pull request by Dr15Jones**
The PathStatusInserter framework modules do not prefetch data (since they do not need it) and therefore the signal about prefetching is never set. This caused StallMonitor to incorrectly assign large stall times to these modules.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@dan131riley can you try this versions with your work on the output module?

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by dan131riley** [comment]
Bogus entries are gone and remaining entries look ok:

StallMonitor>      Module label  # of stalls  Total stalled time  Max stalled time
StallMonitor>  ----------------  -----------  ------------------  ----------------
StallMonitor>  MINIAODSIMoutput            9             1.998 s            0.41 s

**Comment by Dr15Jones** [comment]
@dan131riley thanks!

**Comment by Dr15Jones** [comment]
@dan131riley do the graphs look more reasonable?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
