### PR TITLE
added unit tests for google-benchmark

### PR DESCRIPTION
**Pull request by smuzaffar**
this should be merged with/after cms-sw/cmsdist#4150

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4150

**Comment by Dr15Jones** [comment]
@smuzaffar I do think Utilities/General is the best package to use.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
