### PR TITLE
Run2-alca155 Source code reformatting with clang-format in Calibration/HcalAlCaRecoProducers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Source code reformatting with clang-format in the package Calibration/HcalAlCaRecoProducers

#### PR validation:

Successfully runs the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR:

No back porting needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda sorry, which clang warning are you referring to? This looks like a source code reformatting with clang-format, I do not see warnings from the clang compiler for this packages in https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc700/www/mon/10.6.CLANG-mon-23/CMSSW_10_6_CLANG_X_2019-04-15-2300

**Comment by fabiocos** [comment]
+1

**Pull request merged**
