### PR TITLE
[12.5] Protection for negative kinetic energy in Geant4 tracking

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR should address the issue https://github.com/cms-sw/cmssw/issues/40126 - tracking of a particle with very small negative kinetic energy. This issue should be rare, because never was reported below. The fix does not affect any physics.

PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
type bug-fix

**Comment by civanch** [comment]
backport https://github.com/cms-sw/cmssw/pull/40127

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
