### PR TITLE
Add low lumi HI jet and photon triggers HLT DQM entries

### PR DESCRIPTION
**Pull request by harmonicoscillator**
These are HLT DQM modules meant to be used for the low-lumi PU=0.4 runs.

### CODE REVIEW

**Comment by deguio** [comment]
ciao @richard-cms 
from what I can see those histos are always created even if the HLT paths you are interested in are not in the menu. could you change the code not to book histograms if the interesting paths are not there?
thanks,
F.

**Comment by deguio** [comment]
-1
would like to see this PR integrated and tested in 75 first.
ciao,
F.

**Comment by davidlange6** [comment]
i'll close this and wait for the 75x version

**Comment by richard-cms** [comment]
I will change the modules so that the histograms are not made if the path is not present and resubmit against 75X, sorry for the delay.

**Comment by cfmcginn** [comment]
Hi,
I'm taking over on this DQM integration from @richard-cms. From what I can see of the HLT, the creation of histograms w/o being in the menu path isn't specific to the HI menu, which I believe is the only addition to the code. @deguio, could you elaborate on your comment?

Chris

**Pull request closed without merging**
