### PR TITLE
[13_2_X] Update autoSkim with 2023 PbPb skims

### PR DESCRIPTION
**Pull request by youyingli**
backport of #42754

@mandrenguyen

### CODE REVIEW

**Comment by youyingli** [comment]
@sunilUIET @mandrenguyen  could you please trigger it and sign it if passing?

**Comment by mandrenguyen** [comment]
please test

**Comment by sunilUIET** [comment]
please test

**Comment by youyingli** [comment]
@sunilUIET please sign it. Thanks!

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
