### PR TITLE
[14_0_X] Add Unified ParT to tau NanoAOD (Backport)

### PR DESCRIPTION
**Pull request by lucasrussell01**
#### PR description:

This PR is a Backport to 14_0_X, to add Unified ParT information to taus stored in NanoAOD.
-> These changes require this Backport PR from @AlexDeMoor to be merged https://github.com/cms-sw/cmssw/pull/44660, based on the model in https://github.com/cms-data/RecoBTag-Combined/pull/57

Added (for PUPPI jets):
- UnifiedParT discriminators vs jets, electrons and muons,
- Decay mode corresponding with the UnifiedParT tau node with the highest score,
- Correction for tau pt,
- Charge assignment confidence (signed),
- UnifiedParT scores for individual decay-modes (normalised to the sum of the scores for all tau nodes).

Corresponding ParticleNet 2023 variables are stored for CHS jets.

Performance of UParT is described in: https://indico.cern.ch/event/1403350/contributions/5899772/attachments/2832957/4949984/UParT%202024%20-%20final%20results.pdf

Master PR: https://github.com/cms-sw/cmssw/pull/44691

#### PR validation:

Tested successfully with NanoAOD workflow using CMSSW_14_0 RELVAL file, with pending PR UnifiedParT changes and model merged.

Distributions of UParT and PNet for taus compared here:
https://indico.cern.ch/event/1401414/contributions/5891063/attachments/2838625/4961188/UParT_Integration.pdf

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
test parameters:
  - pull_requests = https://github.com/cms-data/RecoBTag-Combined/pull/57, https://github.com/cms-sw/cmssw/pull/44660

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44691

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by hqucms** [comment]
@cms-sw/orp-l2 Could you please merge this? Thanks!

**Comment by rappoccio** [comment]
+1

**Pull request merged**
