### PR TITLE
Produce r9 and trackIso(hollow cone) in EGamma development path

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

We would like to explore the potential of the variables r9 and track isolation (hollow cone) in the context of phase2 photon paths. The photon paths in Run2/Run3 use these variables, but we haven't yet explored them for phase2. This PR adds these two variables in the development path, and thus makes it easier to study these variables. Once properly studied and cuts are decided, they can be added in real HLT paths as producer+filter. 

#### PR validation:

Phase2 HLT runs fine, and the distribution of new variables look reasonable.
Left plot: r9,  Right plot: track iso (hollow cone)

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by SohamBhattacharya** [comment]
This looks fine for hlt-upgrade. The changes affect only the dev paths and not the menu, and the new variable distributions are reasonable, as already pointed out by Swagata.

**Comment by mmusich** [comment]
>  The changes affect only the dev paths and not the menu, 

if that's the case why do we see changes in trigger results: [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-14-2300+70955d/61692/triggerResults) ?
Aren't these:
```
     Events    Accepted      Gained        Lost       Other  Trigger
          10           0           -           -         ~10  MC_Ele5_Open_Unseeded
          10           0           -           -         ~10  MC_Ele5_Open_L1Seeded
```

part of the menu?

**Comment by SohamBhattacharya** [comment]
> Should there be a backport to 14_0?

I would 

> > The changes affect only the dev paths and not the menu,
> 
> if that's the case why do we see changes in trigger results: [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-14-2300+70955d/61692/triggerResults) ? Aren't these:
> 
> ```
>      Events    Accepted      Gained        Lost       Other  Trigger
>           10           0           -           -         ~10  MC_Ele5_Open_Unseeded
>           10           0           -           -         ~10  MC_Ele5_Open_L1Seeded
> ```
> 
> part of the menu?

The Open paths are the dev paths -- it's run in the menu here for testing/debugging, but not a part of the `realistic` menu.
That's what I'd meant. Sorry for the confusion.

**Comment by mmusich** [comment]
>  Should there be a backport to 14_0?

does this need the changes in https://github.com/cms-sw/cmssw/pull/44025 as well?

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/44423#issuecomment-2003568882

**Comment by SohamBhattacharya** [comment]
> > Should there be a backport to 14_0?
> 
> does this need the changes in #44025 as well?

I'd say not necessarily -- this PR essentially adds a couple of new producers, which can be done in 14_0_X w/o #44025.
(imo there's no real necessity to backport #44025 as it's purely technical changes. But, @rovere did you already have something in mind about backporting?)

**Comment by swagata87** [comment]
> does this need the changes in #44025 as well?

If https://github.com/cms-sw/cmssw/pull/44025 wasn't backported to 14_0_X, then a verbatim backport of my PR will not work. But a backport can still be done. But I'm thinking if a backport is really needed. The new phase2 RAW samples will be produced in 14_0_X, but we can run the HLT menu on those samples from 14_1_X, correct? In that case, I don't see why a backport would be needed..

**Comment by mmusich** [comment]
> I'd say not necessarily

no, a verbatim backport will not work, see https://github.com/cms-sw/cmssw/pull/44025#issuecomment-1985218996

**Comment by SohamBhattacharya** [comment]
> > does this need the changes in #44025 as well?
> 
> If #44025 wasn't backported to 14_0_X, then a verbatim backport of my PR will not work. But a backport can still be done. But I'm thinking if a backport is really needed. The new phase2 RAW samples will be produced in 14_0_X, but we can run the HLT menu on those samples from 14_1_X, correct? In that case, I don't see why a backport would be needed..

In principle yes.. :) 
However, for 2023 samples, we used both 13_1_0 for production as well as for running the menu for AR studies.
We have not tried running the menu with 14_1_X on a 14_0_X "production-like" sample -- which is to be done once we have cut the production release.
If that works, then a backport would not be necessary. So I'd say a backport is not urgent and could be made if the necessity arises. 

But I'm not sure about the policy on how long we can wait before making a backport.

**Comment by swagata87** [comment]
sorry there was a typo which I fixed now. 
and about backport, I think I can try to do it already, to be fully sure that everything will work also from 14_0_X.

**Comment by mmusich** [comment]
@swagata87 can you squash the commits?

**Comment by swagata87** [comment]
backport : https://github.com/cms-sw/cmssw/pull/44452

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
