### PR TITLE
fix TRKDQM @HLT

### PR DESCRIPTION
**Pull request by mtosi**
as reported by @davidlange6 in https://hypernews.cern.ch/HyperNews/CMS/get/dqmDevel/2395.html
this PR fixes 

1. the issue related to the module `hltSiPixelPhase1TrackClustersAnalyzer`,
    which was no more in synch w/ the plugins 
    because of offline updates not propagated to the HLT configuration (again)
2. the typos in the PV validation @HLT configuration

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
