### PR TITLE
Allow running PUPPI v14 customizer on data

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Add separate customize for data and MC for production of UL JME-extended-Nano.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport from #30017

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #30017

**Comment by santocch** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30019	4c1c30d
- changes are the same as in the master branch
- this PR affects only the setup(s) used in special "private" (to POG) production/processing

**Pull request merged**
