### PR TITLE
Fix conddb dump functionality for tags and gts

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
In PR #20215 a new required argument (`destFile`) was added to the `payload2xml` function in `CondCore/Utilities/python/cond2xml.py` and a new argument (`--destfile`) was added to `conddb dump`.
In `conddb` there are 3 calls of `payload2xml`: one for the `payload` type, one for the `tag` type and one for the `gt` type;
but the default value of `destFile` was only passed to the payload-call and not to the other two, causing an error of type:
```
ERROR: payload2xml() missing 1 required positional argument: 'destFile'
```
This PR adds the default value also to the other two calls.

At the same time the command `conddb dump` for the `gt` type was failing also with error:
```
ERROR: type object 'GlobalTag' has no attribute 'name'
```
This is also resolved by fixing a correctly passing the GT name when invoking the `_exists` function in conddb.

#### PR validation:
With these changes the following commands work properly:
- ```conddb dump --type tag SiPixelQuality_byPCL_stuckTBM_v1```
- ```conddb dump --type gt 123X_mcRun1_design_v1```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, a backport to 12_4_X might be considered later on

### CODE REVIEW

**Comment by francescobrivio** [comment]
@ggovi I'd like your feedback on this as I might be missing something here: it seems strange to me that nobody ever noticed this issue so far (altough I must admit I myself have only used the `conddb dump --type payload` up till now...).

**Comment by mmusich** [comment]
Would you mind adding the newly functioning commands to the unit test?
https://github.com/cms-sw/cmssw/blob/master/CondCore/Utilities/test/test_conddb.sh

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
The unit test seems to be successful:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3db343/26305/unitTests/src/CondCore/Utilities/test/test_conddb/testing.log

**Comment by tvami** [comment]
+db
 * discussing privetally with @ggovi he agrees with the fix provided in the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
