### PR TITLE
Remove the dead headers ColumnPacker.hh/ColumnPackerHelper.hh

### PR DESCRIPTION
**Pull request by Teemperor**
ColumnPacker.hh doesn't seem to be used and was never updated since it
was imported to git.

Additionally it doesn't compile because line 749 isn't even a valid
C++ token sequence:

    static_assert((IOIsSameType<stored_type, "requested type>::value");

ColumnPackerHelper.hh is removed because it depends on ColumnPacker
(even though it never includes the related header...).

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding issue https://github.com/cms-sw/cmssw/issues/15248

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
