### PR TITLE
RFC: Migrate SiStripGainsPCLWorker to concurrent and global DQM

### PR DESCRIPTION
**Pull request by mmusich**
In an attempt to solve the issue in https://github.com/cms-sw/cmssw/issues/22281, I've tried to migrate `SiStripGainsPCLWorker` from `DQMEDAnalyzer` to `DQMGlobalEDAnalyzer`. 
Will probably push more commits to clean the code (and I would  also like to make some more extended tests), but comments are already welcome.
Running in a `CMSSW_10_1_X_2018-02-21-2300`, the command `runTheMatrix.py -l 1001.0 -t 4 --ibeos` runs to completion, at variance with the vanilla IB which is segfaulting at [step8](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_1_X_2018-02-21-2300/pyRelValMatrixLogs/run/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step8_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log). 
Incidentally, I've measured the decrease of RSS memory consumption of step3 of  `runTheMatrix.py -l 1001.0 -t 4` and looks sizable (barring errors on my side)
image

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mmusich** [comment]
Last commit should fix the bug causing the spurious differences spotted in the [test comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-23-1100+22320/25222/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/AlCaReco.html).
Now checked explicitly that the [output matches exactly](http://musich.web.cern.ch/musich/display/diff_gains_fix.pdf).

**Comment by davidlange6** [comment]
please test

**Comment by lpernie** [comment]
+1

**Pull request closed without merging**
