### PR TITLE
Add additional MultiTrackValidator instances to validation

### PR DESCRIPTION
**Pull request by makortel**
This PR adds three MultiTrackValidator instances to validation sequence
- `trackValidatorFromPV` (DQM folder "Tracking/TrackFromPV")
  - Monitors tracks associated to the reconstructed primary vertex wrt. TrackingParticles from the hard scatter event, only for events where the primary vertex is correctly identified (i.e. is matched to the generated one)
  - Track-PV association is produced with the same code as in miniAOD, the used association criteria corresponds to the "CompatibilityBTag" flag
  - Monitoring includes the full set of plots
    - Efficiency shows the fraction of hard-scatter TPs that are reconstructed and associated to PV
    - In fake rate the tracks from pileup are counted as fakes
- `trackValidatorFromPVAllTP` (DQM folder "Tracking/TrackFromPVAllTP")
  - Monitors the fake rate (and similar quantities) of PV-associated tracks wrt. all TrackingParticles, i.e. shows how much of the tracks associated to PV are fakes and how much from pileup
- `trackValidatorAllTPEffic` (DQM folder "Tracking/TrackAllTPEffic")
  - Monitors the efficiency of all tracks wrt. all TrackingParticles (in the existing `trackValidator` efficiency is defined wrt. hard-scatter TPs)
  - This quantity is not very interesting for tracking performance, but helps to check if there are differences in pileup simulation between releases (or between classical mixing and premixing)

For the standard validation sequence, the new MTV instances above are set to monitor only generalTracks and highPurity tracks in order to keep the memory use under control. The instances for the "standalone mode" (running MTV privately alone), also the individual iterations are monitored.

In addition the PR includes some cleanup, most notably the recently added summary plots (#9201) are created and filled according to the `doSimTrackPlots`/`doRecoTrackPlots` configuration flags.

Tested in CMSSW_7_6_X_2015-07-10-1100, no changes expected in existing histograms.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10219	58c0caa
- reco code base is changed only with the additional RecoChargedRefCandidateToTrackRef converter and a corresponding producer (not other existing code is affected)
- jenkins tests pass and comparisons with the baseline show no significant differences
    - there are no differences in fwlite-based comparisons of reco products
    - there are some numerical precision level changes in the fits (digma and means) of the existing resolution related histograms, most likely triggered by a change in order of the fits with the new histograms added

**Comment by deguio** [comment]
+1
for the record this PR adds:

------------------------------------------------------------------------------------------
subsystem/folder   histograms       bins
------------------------------------------------------------------------------------------
TrackAllTPEffic             58            6450
TrackFromPV               317         415795
TrackFromPVAllTP       254         409074

**Comment by davidlange6** [comment]
+1

**Pull request merged**
