### PR TITLE
keep phase2_timing_layer functional

### PR DESCRIPTION
**Pull request by bendavid**
Backport of https://github.com/cms-sw/cmssw/pull/25745

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test workflow 20434.0,27434.0
(for completeness)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25746	cef127f
- the backport from the master version (https://github.com/cms-sw/cmssw/pull/25745	232a533) is correct
- jenkins tests pass and comparisons with the baseline show no differences (seen already in the initial round of tests in https://github.com/cms-sw/cmssw/pull/25746#issuecomment-456945179

**Comment by fabiocos** [comment]
+1

@kpedro88 as agreed, missing an evidence for further problems in the master IB related to this code,
I move forward with the merge and the parallel build of mtd5

**Comment by fabiocos** [comment]
merge

**Pull request merged**
