### PR TITLE
Adding back thepeginterface

### PR DESCRIPTION
**Pull request by alberto-sanchez**
We are putting back this code that is require in production while H7 is fully deployed.

This code needs previous versions of  thepeg and herwigpp, which should be available before.

### CODE REVIEW

**Comment by perrozzi** [comment]
@alberto-sanchez can you apply the suggested patch to comply with code style standards?

**Comment by alberto-sanchez** [comment]
@perrozzi , yes working on that

**Comment by perrozzi** [comment]
plase test

**Comment by alberto-sanchez** [comment]
@perrozzi it will fail, it need thepeg and herwigpp, from previous versions

**Comment by alberto-sanchez** [comment]
can this be tested together with https://github.com/cms-sw/cmsdist/pull/3374
?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3374

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by mrodozov** [comment]
This PR changes work fine with gcc6 and the flags used for it but it brakes with 57 errors (coming from few headers) listed here: 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_9_3_X_2017-09-06-1100/GeneratorInterface/ThePEGInterface
Would you please look at it and provide the fix ?

**Comment by alberto-sanchez** [comment]
@mrodozov, @smuzaffar  thanks a lot for the feed-back. The actual problem is in 
thepeg library, introduced in https://github.com/cms-sw/cmsdist/pull/3374
which apparently does not comply with standards. I have managed to run clang-tidy over it and produced a patch file. Hope Mikhail or you can applied. I put that in (/afs/cern.ch/work/a/asanchez/public/1.9.2p1-some-patch0001.patch)

**Pull request merged**
