### PR TITLE
Create Pythia8CUEP8M2T4Settings_cfi.py

### PR DESCRIPTION
**Pull request by efeyazgan**
CP0 = CUETP8M2T4 tune snippet

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
hi @efeyazgan - are there others that are now obsolete and can be cleaned up?

**Comment by efeyazgan** [comment]
@davidlange6 It's hard to say. We will review and let you know.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
