### PR TITLE
Update tracking MiniAOD validation

### PR DESCRIPTION
**Pull request by makortel**
This PR gives a major update to the tracking MiniAOD validation code.
- Compare only charged PackedCandidates
- Check `normalizedChi2` only if PackedCandidate ndof != 0
  - it it is 0, its `normalizedChi2` is 0 by construction
- Check `hasValidHitInFirstPixelBarrel()` only if there are no lost inner hits
  - if there are, this information is not valid
- Record the number of tracks used in the two cases above in the selection flow histogram
- Monitor the overflow of pixel hits, strip hits, and total number of hits
- Add (LogInfo) printout for track-PackedCandidate pairs where differences are outside tolerances
  - Helps to track them down
- Detailed monitoring of the precision of packed floating point values
  - Try to catch and monitor under/overflows and sign changes
  - Limit monitoring mainly to the packed quantities (e.g. prefer covariance matrix elements over the corresponding "errors"), but provide monitoring of most interesting quantities where "equality within packing precision" is not expected (e.g. pT)

Tested in CMSSW_8_0_X_2015-11-11-2300, expecting changes in `Tracking/PackedCandidate` DQM folder.

@rovere @VinInn @arizzi @gpetruc

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
ping

**Comment by VinInn** [comment]
@deguio please review

**Comment by makortel** [comment]
I noticed only now that there was one unused function left (from which gcc warns), and one set of histograms had one extra bin.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
looks ok to me

**Pull request merged**
