### PR TITLE
CTPPS pixel det package rotation

### PR DESCRIPTION
**Pull request by fabferro**
Change in ideal 2018 geometry due to a rotation of the pixel detector packages in pot 56 210 far hor

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@fabferro this looks ideal geometry, is your RECO also dependent on it?

**Comment by fabferro** [comment]
@fabiocos : yes, definitely

**Comment by ianna** [comment]
@fabferro - This file does not exist. Please, either add the file or remove it from configuration:
https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometry/python/geometryRPFromDD_2018_cfi.py#L29
Please, correct this PR.

BTW, the payloads in DB do not have this change yet.

**Comment by ianna** [comment]
-1

**Comment by ianna** [comment]
please test

**Comment by fabferro** [comment]
@ianna : sorry. BTW wrong lines were 
https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometry/python/geometryRPFromDD_2018_cfi.py#L127
https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometry/python/geometryRPFromDD_2018_cfi.py#L126

I fixed them.

**Comment by ianna** [comment]
@fabferro - please, check the following GT candidate:
101X_upgrade2018_design_Candidate_2018_03_21_10_59_15 and if it's ok, I'll request the GT update.

@arunhep - FYI, CTPPS 2018 payload will need to be updated for both MC and data GTs. Thanks.

**Comment by ianna** [comment]
+1

**Comment by fabferro** [comment]
@ianna : GT candidate 101X_upgrade2018_design_Candidate_2018_03_21_11_52_58 seems to working properly

**Comment by fabiocos** [comment]
+1

**Pull request merged**
