### PR TITLE
From cmssw 7 5 0 pre6 relval merge

### PR DESCRIPTION
**Pull request by hengne**
update relval scripts

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

thanks @hengne 
I am not 100% sure if the 7_5 pull requests are forward ported automatically to 7_6 ( @degano : can you please tell us if that's the case ? )
If now, @hengne , can you pelase put the same PR also for the 7_6 branch ? Thanks.

**Comment by hengne** [comment]
@franzoni OK, np.

**Comment by hengne** [comment]
@franzoni Hi Giovanni, seems to me the PRs merged in 75x are auto merged in 76x:
https://github.com/cms-sw/cmssw/commits/CMSSW_7_6_X
So, yes, i will check 76x after this PR is merged in 75x, if not, i will put a PR in 76x directly.

**Pull request merged**
