### PR TITLE
Run3-hcx283 Use ESGetToken in CalibCalorimetry/HcalPlugins

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in CalibCalorimetry/HcalPlugins

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

The tests were not started and this PR is not listed at https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/

**Comment by yuanchao** [comment]
+1
* updated to use ESGetToken
* matrix tests on work flow all passed
* static build warning on std::vector<HcalGenericDetId> thread-unsafe is not part of the modification

**Comment by yuanchao** [comment]
Still the deprecated "get" method is used as: iSetup.get<GlobalPositionRcd>().get(globalAlignments); and iSetup.get<BeamSpotObjectsRcd>().get(label, beamhandle);

**Comment by silviodonato** [comment]
merge

**Pull request merged**
