### PR TITLE
Phase2-hgx48 Introduce fiducial cut off for HGC SimHit

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by lgray** [comment]
Hey everyone, I would like to take a quick look at this PR before we merge it. 
Logic looks fine but just want to make sure there is little degradation in time.
This function gets called a lot and we just put a two sqrts and a ton of multiplies inside of it.

@cseez @kpedro88 @vandreev11

**Comment by lgray** [comment]
It is a negligible performance penalty compared to other issues in GEANT at the moment.
We can come back to it later if it pops back up in terms of slowdown.

**Comment by bsunanda** [comment]
@mmusich @ggovi please sign this

**Comment by mmusich** [comment]
+1
there are only only minimal changes in `CondFormats/GeometryObjects`
@ggovi should give a look and tell if it is ok.

**Comment by bsunanda** [comment]
@ggovi Could you please sign this PR

**Comment by ggovi** [comment]
+1

**Pull request merged**
