### PR TITLE
76X 25ns HLT - round four

### PR DESCRIPTION
**Pull request by perrotta**
Based on CMSSW_7_6_X_2015-09-15-1100

It includes (by now...) updates to the HLT menu up to /dev/CMSSW_7_4_0/HLT/V480

It also includes a fix that prevents FastSim crashing if the new menus integrated with #11043 are run

### CODE REVIEW

**Comment by perrotta** [comment]
While the version of this pull request for  74X (#11295) and for 75X (#11294) give no troubles with the HLT tests, I get segmentation violation if I run this PR in 76X, at least in the CMSSW_7_6_X_2015-09-15-1100 IB where I developed it.

The stack trace [1] is not transparent at all to me. It doesn't seem to point to the new updates in this menu, though... I'll have a look in the next days, possibly starting from a newer IB. Any other hint (or fix, if needed) in the meanwhile is very welcome! 

[1]
Thread 1 (Thread 0x7fc385a93a40 (LWP 3779)):
#0  0x00007fc3875d57dd in read () from /lib64/libpthread.so.0
#1  0x00007fc37f0cb5ae in full_read.constprop () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_X_2015-09-15-1100/lib/slc6_amd64_gcc493/libFWCoreServices.so
#2  0x00007fc37f0cb70e in edm::service::InitRootHandlers::stacktraceFromThread() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_X_2015-09-15-1100/lib/slc6_amd64_gcc493/libFWCoreServices.so
#3  0x00007fc37f0cb843 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_7_6_X_2015-09-15-1100/lib/slc6_amd64_gcc493/libFWCoreServices.so
#4  <signal handler called>
#5  0x00007fc3740ced8d in std::_Rb_tree<unsigned int, std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocat
or<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > >, std::_Select1st<std::pair<unsig
ned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, 
std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Re
f<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track,
 edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track
> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::T
rack, std::allocator<reco::Track> >, reco::Track> > > > >*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#6  0x00007fc3740ced99 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocat
or<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > >, std::_Select1st<std::pair<unsig
ned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, 
std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Re
f<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track,
 edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track
> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::T
rack, std::allocator<reco::Track> >, reco::Track> > > > >*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#7  0x00007fc3740ced99 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocat
or<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > >, std::_Select1st<std::pair<unsig
ned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, 
std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Re
f<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track,
 edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> > > > > >::_M_erase(std::_Rb_tree_node<std::pair<unsigned int const, edm::helpers::KeyVal<edm::Ref<std::vector<reco::Track, std::allocator<reco::Track
> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track> >, edm::Ref<std::vector<reco::Track, std::allocator<reco::Track> >, reco::Track, edm::refhelper::FindUsingAdvance<std::vector<reco::T
rack, std::allocator<reco::Track> >, reco::Track> > > > >*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#8  0x00007fc3740cedc1 in edm::AssociationMap<edm::OneToOne<std::vector<reco::Track, std::allocator<reco::Track> >, std::vector<reco::Track, std::allocator<reco::Track> >, unsigned int> >::~AssociationMap() () from /afs/cern.ch/cms/sw/ReleaseCandidates/
vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#9  0x00007fc3740cedec in edm::Wrapper<edm::AssociationMap<edm::OneToOne<std::vector<reco::Track, std::allocator<reco::Track> >, std::vector<reco::Track, std::allocator<reco::Track> >, unsigned int> > >::~Wrapper() () from /afs/cern.ch/cms/sw/ReleaseCan
didates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#10 0x00007fc3740cedff in edm::Wrapper<edm::AssociationMap<edm::OneToOne<std::vector<reco::Track, std::allocator<reco::Track> >, std::vector<reco::Track, std::allocator<reco::Track> >, unsigned int> > >::~Wrapper() () from /afs/cern.ch/cms/sw/ReleaseCan
didates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libDataFormatsTrackReco.so
#11 0x00007fc38973bd4b in edm::ProducedProductHolder::resetProductData_() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#12 0x00007fc38972f061 in edm::Principal::clearPrincipal() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#13 0x00007fc3896c7172 in edm::EventPrincipal::clearEventPrincipal() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#14 0x00007fc3896d8cd2 in edm::EventProcessor::processEvent(unsigned int) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#15 0x00007fc3896d91f4 in edm::EventProcessor::processEventsForStreamAsync(unsigned int, std::atomic<bool>*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramew
ork.so
#16 0x00007fc3896e89b4 in edm::StreamProcessingTask::execute() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#17 0x00007fc388479bec in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fc384c27d00, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:474
#18 0x00007fc3896d903e in edm::EventProcessor::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#19 0x00007fc3896b583d in statemachine::HandleEvent::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#20 0x00007fc3896b7386 in statemachine::HandleEvent::HandleEvent(boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mp
l_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::my_context) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015
-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#21 0x00007fc3896bfe37 in boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, m
pl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::deep_construct(boost::intrusive_ptr<statemachine::HandleLumis> const&, boost::statechart::state_machine<statemachine::Machine, statemachine::Start
ing, std::allocator<void>, boost::statechart::null_exception_translator>&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#22 0x00007fc3896c002c in boost::statechart::simple_state<statemachine::FirstLumi, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::
na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/
CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#23 0x00007fc3896cfdd4 in edm::EventProcessor::runToCompletion() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-09-13-1100/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#24 0x000000000040d038 in main::{lambda()#1}::operator()() const ()
#25 0x000000000040b496 in main ()

A fatal system signal has occurred: segmentation violation

**Comment by Dr15Jones** [comment]
CMSSW_7_6_X_2015-09-15-1100  had a build problem which lead to a binary incompatibility between some of the libraries. Please try a different IB.

**Comment by perrotta** [comment]
Thank you Chris!
I'm re-launching my tests on CMSSW_7_6_X_2015-09-16-1200
(09-15-11 was the newest 76X IB I was able to access this morning from lxplus)

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_7_6_X_2015-09-16-2300

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
