### PR TITLE
Updating L1 Menu and HLT JECs

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v11) as [80X_mcRun2_design_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v11/80X_mcRun2_design_v9): 
  - updated JEC for HLT (v11) 
  - updated L1 menu for Stage-2 (dev v4)
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v10) as [80X_mcRun2cosmics_startup_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v10/80X_mcRun2cosmics_startup_peak_v8): 
  - updated JEC for HLT (v10) 
  - fixed version of correction level string in JEC for HLT payloads
  - latest version of the L1 menu (dev v4)
  - Ecal readout setting for 2016
  - Strip bad components for 2016
  - JEC resolutions and PF corrections as in pp 
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v11) as [80X_mcRun2_asymptotic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v11/80X_mcRun2_asymptotic_v9): 
  - updated JEC for HLT (v11) 
  - updated L1 menu for Stage-2 (dev v4)
- **RunII Startup scenario** : [80X_mcRun2_startup_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v11) as [80X_mcRun2_startup_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v11/80X_mcRun2_startup_v9): 
  - updated L1 menu for Stage-2 (dev v4)
  - adding JEC uncertainties for 50ns for all algorithms
## RunI data
- **RunI Offline processing** : [80X_dataRun2_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v11) as [80X_dataRun2_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v11/80X_dataRun2_v9): 
  - updated JEC for HLT (v11) 
  - added e/gamma regressions for HLT (needed for HLT+RECO step)
- **RunI HLT processing** : [80X_dataRun1_HLT_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun1_HLT_frozen_v10) as [80X_dataRun1_HLT_frozen_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun1_HLT_frozen_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun1_HLT_frozen_v10/80X_dataRun1_HLT_frozen_v8): 
  - updated JEC for HLT (v11) 
  - adding 7 payloads for GBRWrapperRcd for tracking MVA
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v11) as [80X_dataRun2_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v10/80X_dataRun2_v9): 
  - updated JEC for HLT (v11) 
  - added e/gamma regressions for HLT (needed for HLT+RECO step)
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v7) as [80X_dataRun2_HLT_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v7/80X_dataRun2_HLT_relval_v4): 
  - updated JEC for HLT (v11) 
  - updated L1 menu for Stage-2 (dev v4)
  - adding 7 payloads for GBRWrapperRcd for tracking MVA
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v11) as [80X_dataRun2_HLT_frozen_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v10/80X_dataRun2_HLT_frozen_v8): 
  - updated JEC for HLT (v11) 
  - Adding 7 payloads for GBRWrapperRcd for tracking MVA
- **RunII Offline relval processing** : [80X_dataRun2_relval_v56(https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v6) as [80X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v6/80X_dataRun2_relval_v4): 
  - updated JEC for HLT (v11) 
  - updated L1 menu for Stage-2 (dev v4)
  - added e/gamma regressions for HLT (needed for HLT+RECO step)
## Upgrade
- **PhaseI design scenario** : [80X_upgrade2017_design_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v10) as [80X_upgrade2017_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v10/80X_upgrade2017_design_v8): 
  - updated JEC for HLT (v11) 
  - updated L1 menu for Stage-2 (dev v4)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 
Could you please also update this PR for the changes made in https://github.com/cms-sw/cmssw/pull/14077 ?
Thanks!

**Comment by mmusich** [comment]
@Martin-Grunewald  done

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Pull request merged**
