### PR TITLE
use shunt factor in QIE11 hardcode calibrations

### PR DESCRIPTION
**Pull request by kpedro88**
The QIE11 cards will be operated with a current shunt due to the high levels of charge generated by SiPMs. The starting value of the current shunt is expected to be a factor of 6. This will be reflected in the QIE calibrations, but had been left out of the simulated values until now.

This PR updates the hardcode conditions. A separate update to the database conditions will be made by @abdoulline et al.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@kpedro88 
you mentioned that this is supposed to solve the high-energy hit issue.
jenkins shows no differences in 2017 workflows (including 2017HCALdev).

There are differences in 2023D3, apparently in HB part.
What's missing?

**Comment by kpedro88** [comment]
@slava77 this solves it in the hardcode conditions, which usually aren't applied in central workflows, except for phase2. @abdoulline is preparing the associated database condition update with these values, which will fix 2017.

**Comment by slava77** [comment]
ah, OK.
So, I wait for this then to check #15959

**Comment by abdoulline** [comment]
Kevin and Slava,

new HcalQIEData_2017_v2.0_mc has been submitted to appropriate 81X GT 
queues and a request has been sent to AlCa yesterday. But it needs some 
time to be propagated to GTs.

**Comment by mmusich** [comment]
@abdoulline see updated Global Tags at: #16101 
This is to let people continue working on the development, everything will need to converge into a single scenario via https://github.com/cms-sw/cmssw/pull/15994

**Pull request merged**
