### PR TITLE
[92X] Fix configuration for DA_vect clusterizer in PV Validation tool (after #18330 merging)

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all. Solves issue reported at #18330

### CODE REVIEW

**Comment by mmusich** [comment]
Some support plots, validating the change (test run 275657, `HLTPhysics` 2016C Dataset): 
At final plot level regressions are negligible in the **biases**:

biasescanvas_testforpr18561this_pr_vs_910pre2

there is an (unexpected?) improvement in the **pulls** epecially in the `z`-projection:

pullscanvas_testforpr18561this_pr_vs_910pre2

that is confirmed in the non-differential pull distribution:

c1_ratio_pulltrkz_all_da

vertex chisquare probabilty gets much flatter

c1_ratio_h_fitvtxchi2prob_refitvertexfeatures

and track weights much more peaked at 1.
c1_ratio_h_fitvtxtrackaverageweight__refitvertexfeatures

**Comment by arunhep** [comment]
please test

**Comment by mmusich** [comment]
type bugfix

**Comment by mmusich** [comment]
@arunhep. This PR is not expected to change anything run in relval tests and should fix the issue in the unit tests in recent IBs such as: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_1_X_2017-05-03-1100/unitTestLogs/Alignment/OfflineValidation

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
