### PR TITLE
Run2-hcx206 Take care of Phase2 situations for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modification in CalibCalorimetry/HcalPlugins and HcalTopology due to no HE scenario

#### PR validation:

Used standard runTheMatrix.py with "limited"

#### if this PR is a backport please specify the original PR:

Not to be back ported

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda 
Do we need a backport of this for 10_6 for L1T production campaign?

**Comment by bsunanda** [comment]
@srimanob As I mentioned in the meeting this need not be back ported because this is not affecting the workflows as yet

**Comment by christopheralanwest** [comment]
+1

It's also useful to note that the bug in the output LUTs for the 2023 scenario (which uses `HcalTopologyMode::TriggerMode_2021`) had no effect because [the QIE10 and QIE11 output LUT sizes](https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.h#L53-L54) are the same.

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda there is a conflict due to the clang-format migration, please rebase your file on the newer version

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @fabiocos @kpedro88 The failures are not due to this PR. This is caused by missing files in L1Trigger/L1THGCal which is not touched in this PR. Please take care of this

**Comment by kpedro88** [comment]
@bsunanda it should be fixed in the next IB

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by fabiocos** [comment]
@cvuosalo @ianna could you please have a look? I will consider the previous signature by @rekovic as valid

**Comment by cvuosalo** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by rekovic** [comment]
@bsunanda 
> @srimanob As I mentioned in the meeting this need not be back ported because this is not affecting the workflows as yet

Sorry I missed this discussion, so I am wondering about a few things.    
Does it mean that our current Phase2 model does not include yet these "HCAL situations" as you called them, and that is why the Phase2 MC production does not depend on this PR?  Can you please elaborate on this. Thanks.

**Comment by bsunanda** [comment]
@rekovic @srimanob Rethinking about it - may be worthwhile to backport this to 10_6. Also I am not sure if CaloTower code is retuned for Phase2 scenario. I shall take a look there

**Comment by rekovic** [comment]
@bsunanda 
There are a few new Phase2  GEN-SIM-DIGI-RAW samples with CMSSW_10_6_0_patch2 release that just came out (Ele/Pho/Pi0/Pi guns).  Can this be checked on these samples ?

**Pull request merged**
