### PR TITLE
move TTTrackTruthPair to SimDataFormats/Associations

### PR DESCRIPTION
**Pull request by davidlange6**
As with #33186 - reduce the SimDataFormats dependencies in DataFormats..

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/l1-l2 @cms-sw/upgrade-l2 @cms-sw/hlt-l2 @cms-sw/simulation-l2  do you have any comments?

**Comment by cecilecaillol** [comment]
+l1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
