### PR TITLE
[12_4_X] Updated list of Geant4 process codes

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
It is a backport of #38659. This PR is not urgent but needed for MC production release. It should not affect most of productions and is needed only for dark matter particle bremsstrahlung.

#### PR validation:
private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
-->

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38659

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
