### PR TITLE
Implement async global end transitions

### PR DESCRIPTION
**Pull request by Dr15Jones**
Both global EndLuminosityBlock and global EndRun transitions are now run asynchronously.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 this really should go into a development release, not the 9_2 production release.

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 do I need to create an explicit pull request to _DEVEL?

**Comment by davidlange6** [comment]
sorry - i think this got lost - could you make PRs to DEVEL and ping me - I can merge them in the next hours

**Comment by Dr15Jones** [comment]
#19409 is the _DEVEL version of this same pull request.

**Comment by davidlange6** [comment]
in DEVEL branch now.

**Comment by davidlange6** [comment]
merge

**Comment by Dr15Jones** [comment]
+1
just to get it off my search

**Pull request merged**
