### PR TITLE
Let PFClusterEMEnergyCorrector run without SRB inputs

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Let the `PFClusterEMEnergyCorrector` run also in the absence of the ECAL selective bit readout collections.

If these collections are not present (or empty) the `PFClusterEMEnergyCorrector` will assume all hits to have been read with "full readout", without any zero suppression.

#### PR validation:

None.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #38081.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #38081

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
let's see if the relvas input tets work...

**Comment by missirol** [comment]
assign hlt

to be consistent with the original PR

**Comment by missirol** [comment]
+hlt
 - effectively downgrades an exception to a LogInfo
 - needed as part of [CMSHLT-2315](https://its.cern.ch/jira/browse/CMSHLT-2315), to reduce CPU-GPU discrepancies related to ECAL
 - no differences in PR-tests outputs expected, nor observed

**Comment by missirol** [comment]
Not truly urgent, but this PR is needed for `12_4_0`.

**Comment by qliphy** [comment]
+1

**Pull request merged**
