### PR TITLE
Non elastic pg

### PR DESCRIPTION
**Pull request by mundim**
It was removed a piece of code which was forcing the protons fired in both sides of CMS to obey an elastic condition that was never meant to exist.

### CODE REVIEW

**Comment by slava77** [comment]
-1

due to bad PR submission

**Comment by kpedro88** [comment]
-1

**Comment by Martin-Grunewald** [comment]
-1

**Comment by slava77** [comment]
-1

bad PR submission

**Comment by mundim** [comment]
I tried to correct what was pointed out by the PR process. First of all, I was surprised do see messages about bad code style in part of the code I have not touched. Only after David Lange message I could understand why.

I tried the "code-checks" and got the following:

 % scram build code-checks
Resetting caches
>> Local Products Rules ..... started
>> Local Products Rules ..... done
Unknow target code-checks

The other way (curl ...) asked me a lot of times about files to patch which are no in my working area and apparently, my code doesn't depend on them. So, I'll try to figure out and change by hand and submit a new PR.

**Comment by mundim** [comment]
BTW, I'm working on CMSSW_9_1_0...

**Comment by kpedro88** [comment]
you submitted this PR to master branch which is 9_4_X. code-checks are only available in 93X and 94X versions of scram.

**Comment by mundim** [comment]
Ops... my fault...



Enviado do meu dispositivo Samsung


-------- Mensagem original --------
De : Kevin Pedro <notifications@github.com>
Data: 27/09/2017 16:10 (GMT-03:00)
Para: cms-sw/cmssw <cmssw@noreply.github.com>
Cc: Luiz Martins Mundim Filho <luiz.mundim@cern.ch>, Author <author@noreply.github.com>
Assunto: Re: [cms-sw/cmssw] Non elastic pg (#20617)


you submitted this PR to master branch which is 9_4_X. code-checks are only available in 93X and 94X versions of scram.

**Pull request closed without merging**
