### PR TITLE
Phase2-hgx359M Add the dd4hep version of the new algorithm needed for the V19 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the dd4hep version of the new algorithm needed for the V19 version of HGCal Geometry

#### PR validation:

Dump the geometry for visualisation

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
type hgcal

**Pull request merged**
