### PR TITLE
[12_4_X] Added protection against out-of-range BX values in EMTF unpacker blocks

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR is a partial backport of https://github.com/cms-sw/cmssw/pull/38961. The rest of the changes will go in with https://github.com/cms-sw/cmssw/pull/39389

The PR was made as discussed in https://github.com/cms-sw/cmssw/pull/39388

This PR fixes the crash reported in https://github.com/cms-sw/cmssw/issues/38940. EMTF DAQ readout window is 7 BX wide [-3, 3], but in cases of corrupted data from TPs or faulty configurations it can have a value of 4.

Apaprently, such cases happened during LS2 when GEMs were not working properly. Unpacking this data and trying to use the DQM plots added in https://github.com/cms-sw/cmssw/pull/38818 causes a crash. 

This PR adds a veto for any TP or EMTF track that falls out of this [-3, 3] window since these are clearly not valid.

#### PR validation:

Validated with the failing workflows from https://github.com/cms-sw/cmssw/issues/38940. Everything works and we print out the warning messages about corrupted data.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a partial backport of https://github.com/cms-sw/cmssw/pull/38961. The rest of the changes will go in with https://github.com/cms-sw/cmssw/pull/39389

The PR was made as discussed in https://github.com/cms-sw/cmssw/pull/39388

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test
(The das error in the unit test is clearly unrelated. Let relaunch the tests, if this helps the signature)

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38961
(already partially backported in 12_4_X with #39389)

**Comment by perrotta** [comment]
I was ready to bypass the @cms-sw/l1-l2 signature and merge this PR for the next 12_4_X data taking release.
However, if I'm not wrong https://github.com/cms-sw/cmssw/pull/38818 (the DQM plots added by whom caused the segfault fixed by the backported PR) was never backported into 12_4:_X. Therefore it is probably not strictly necessary having this PR in 12_4_X: let it follow the usual signature procedure, and merge it eventually only if needed.

**Comment by eyigitba** [comment]
@perrotta , yes https://github.com/cms-sw/cmssw/pull/38818 was never backported to 12_4_X. That's why I said this is probably not that urgent in my original comment. I think it's still better to have it go in for consistency though. I'm ok with following the usual signature procedure since there is no rush

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
