### PR TITLE
Fixed bug in tracking sequence

### PR DESCRIPTION
**Pull request by dinardo**
I've fixed a bug in the tracking sequence, I've simply added the lines
`process.load("RecoVertex.BeamSpotProducer.BeamSpot_cfi)`
and then
`process.offlineBeamSpot*`
in the sequence.

### CODE REVIEW

**Comment by dinardo** [comment]
Dear Experts,
I was wondering whether this PR can move forward.
Cheers,
- Mauro.

**Comment by dmitrijus** [comment]
You are merging into the wrong branch. It should go to **master**.

I have told you many countless times that no PR will ever get merged or even looked at, 
unless they are to the master branch or already exist (and/or merged) in the master branch.

**Comment by dmitrijus** [comment]
Actually, **master** version of this does exist and is https://github.com/cms-sw/cmssw/pull/19558/files
Please close this one.

**Comment by dinardo** [comment]
Hi Dmitrijus,
indeed, I perfectly remember what you told me.
This is why I put this very same PR also in PR #19558,
but Marco told me to put PR also in the "patch" branch.
This is why I put this PR (PR #19559)
- Mauro.

**Comment by dmitrijus** [comment]
@dinardo Please change the target to 9_2_X.
Marco's instructions were correct, for that week and that week only :)

**Comment by dinardo** [comment]
Hi Dmitrijus, ok many thanks.
It's done. Cheers,
- Mauro.

**Comment by fwyzard** [comment]
I would suggest to rebase or redo this PR based on a recent 9.2.x release, to get rid of the spurious commits and signature needs.

**Comment by dinardo** [comment]
Hi, it's done. It's PR #19693.
Many thanks,
- Mauro.

**Pull request closed without merging**
