### PR TITLE
Phase2-tb75 Enable the analysis code for HGCal TB for 6-inch wafer to run properly

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Enable the analysis code for HGCal TB for 6-inch wafer to run properly

#### PR validation:

Use the test codes in SimG4CMS/HGCalTestBeam/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

No change is expected. The failure in comparison comes from Run-3 mkfit workflow which should not relate to this PR.

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
