### PR TITLE
DQM: Configuration alias for QualityTester

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

This PR is extracted from #28316, the first in a series to eventually replace #28316.

It replaces the direct invocations of `cms.EDAnalyzer("QualityTester", ...)`  with calls to an alias, to allow changing the module type of `QualityTester` to `EDProducer` in the future.

This PR touches lots of packages, but does not include *any* functional changes. Most of the changes are machine-generated.

#### PR validation:

No functional changes, alias seems to work.

### CODE REVIEW

**Comment by schneiml** [comment]
@cmsbuild ping

**Comment by schneiml** [comment]
please test

no changes expected.

**Comment by schneiml** [comment]
+1

Tests are all clean, as expected.

**Comment by tlampen** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@peruzzim the change in the xpog domain si minimal and coherent with the rest of the PR, please have a look, I will integrate this PR on a next IB

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
