### PR TITLE
Stop gcc 6.2 warnings in PFClusterTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
Made operator<< no longer a friend and declared it in the same
namespace as the class.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
@smuzaffar: Is Jenkins breaking down or are there bugs in CMSSW_9_0_X_2016-12-09-1100? I've seen two mysterious compile errors in Jenkins tests this afternoon.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Trying again in case the previous failure was just a Jenkins glitch

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #16959 d07576a6c53ed2b7c5524c4c86c47e1d0dac4363

Cleaning up Clang warnings related to the ostream operator in PFClusterTools. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-11-1100 show no significant differences, as expected (except for errors in the Jenkins test unrelated to this PR).

**Comment by davidlange6** [comment]
+1

**Pull request merged**
