### PR TITLE
updating PUPPI, 76x

### PR DESCRIPTION
**Pull request by nhanvtran**
This is the companion to #10597 and #10551

### CODE REVIEW

**Comment by nhanvtran** [comment]
I started from 760_pre2, let me know if I need to start from an IB or another setup...

**Comment by slava77** [comment]
@nhanvtran 
#10597 was auto-forward ported to 76X
your proposed changes in this PR are in conflict with 76X head

**Comment by slava77** [comment]
-1
resolve conflicts (or close if not needed)

**Comment by nhanvtran** [comment]
ah okay, I missed the auto-forward port.  @slava77 sorry for the noise...

**Pull request closed without merging**
