### PR TITLE
Restructured code of againstElectronDeadECAL tauID (11_1_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
This is backport of #29627 - actually exactly same development branch is used as in the original PR (already merged to master). Need of the backport is caused by the fact that target release series has been changed during review of the original PR.

Restructured code of againstElectronDeadECAL discriminator to run on either AOD or miniAOD inputs:
- add a version of the discriminant to run on top of pat::Taus to be used with miniAOD data samples;
- use eta and phi of impact position of the leading PFChargedHadron on ECal surface instead of eta and phi of tau at the vertex (taking bending of track in the magnetic field and the zVertex into account); it can be disabled for backwards compatibility; 
- restructure the code in the way that AOD and miniAOD versions of the discriminant are just different instances of the same template code;
- move code preforming extrapolation to the ECal surface from the againstElectronMVA algorithm to an auxiliary helper class which avoids code duplication;
- add output of the againstElectronDeadECAL discriminant produced at AOD (already present in RECO/AOD workflow) to `slimmedTaus` in MiniAOD

Expected some differences:
- small difference in output of PFRecoTauDiscriminationAgainstElectronDeadECAL (AOD) discriminant because of enabled extrapolation to the ECAL (version with the extrapolation disabled gives identical results as one before the changes in this PR);
- new tauID embedded into slimmedTaus in miniAOD.

#### PR validation:

Tested several times during review of original PR basing on the same development branch.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

It is backport of #29627 (actually it uses exactly same development branch as the original/mother PR)

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #29627

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@mbluj 
IIUC, this is not required for the Phase-2 HLT TDR rereco (the main target for 11_1_X).
Is this correct?
Please clarify.
Thank you.

**Comment by mbluj** [comment]
> 
> 
> @mbluj
> IIUC, this is not required for the Phase-2 HLT TDR rereco (the main target for 11_1_X).
> Is this correct?
> Please clarify.
> Thank you.

No, is not required.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30009	84762b7 
- this is identical to the master version https://github.com/cms-sw/cmssw/pull/29627	84762b7 
- this backport is not aiming for the phase-2 HLT needs, but it will be important for potential Run-3 studies in this release cycle. The PR adds new ID variables and should not affect validation of other produced objects.

**Comment by santocch** [comment]
+1

**Pull request merged**
