### PR TITLE
Changed type string to bool

### PR DESCRIPTION
**Pull request by akanugan**
PR description:

It changes the type of imc from string to bool. This issue was raised in parallel #27215 by @jfernan2 so this could be a correction to the previous code.

PR validation:

Local tests run.

It might be somehting @hatakeyamak @abdoulline might be interested in.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
