### PR TITLE
Revert "Adding infra. for L1T object scaling constants from DB"

### PR DESCRIPTION
**Pull request by silviodonato**
Reverts cms-sw/cmssw#32137
see: https://github.com/cms-sw/cmssw/pull/32320#issuecomment-742044876
cc: @trtomei @cbotta

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
