### PR TITLE
Fix clang compile problem with FreeFunctionSelector

### PR DESCRIPTION
**Pull request by Dr15Jones**
Template argument needs to be a pointer to a function

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This fixes the following compiler error
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_CLANG_X_2017-07-14-1100/CommonTools/CandAlgos

**Comment by perrotta** [comment]
+1
This is only included by CommonTools/​CandAlgos/​plugins/​DummyCandSelector.cc, which is not used anywhere, as far as I can see,
Anyhow, if it fixes the clang compiler error it's fine

**Comment by davidlange6** [comment]
merge

**Pull request merged**
