### PR TITLE
AVR-based CSVv2 taggers, updated SV TagInfos in MiniAOD

### PR DESCRIPTION
**Pull request by ferencek**
This PR adds CSVv2 taggers based on secondary vertices reconstructed using the Adaptive Vertex Reconstructor (Run 1 default). PF-based version of CSVv2+AVR is also added to the standard reco. All new taggers were also propagated to PAT. In addition, SV TagInfos from which the SV info is grabbed and stored in MiniAOD has been updated.

To add a little bit of context. These changes are result of a discussion in yesterday's BTV POG meeting.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

this includes a new product
pfCombinedSecondaryVertexV2BJetTags
this technically a new feature.
It currently has no impact on modules running downstream.
There is no guarantee this goes to 74X, but it probably can.

**Comment by ferencek** [comment]
@slava77 Unfortunately, yes, this is a very last minute change. I also forgot to update the event content before the tests were triggered. Sorry about that.

**Comment by slava77** [comment]
Hi Dinko,

is there anything else missing?

if the content changes are missing, the PAT steps will fail, right?

**Comment by ferencek** [comment]
Yes, PAT steps will fail.

**Comment by ferencek** [comment]
At this point this should be all. What is still missing, and is unrelated to this PR, is the CSVSL tagger that requires an updated GT. Unfortunately, it looks like the new GT is not yet available so CSVSL will not be included in the standard reco.

**Comment by slava77** [comment]
It looks like jenkins picked up your latest c363fbc  for tests (based on the status message)

**Comment by ferencek** [comment]
In principle, I could remove pfCSVv2+AVR from the list of default PAT jet btaggers to avoid getting failed PAT tests. I assume this change can be added also after the release is closed after 740pre7 RelVals appear. Let me know.

**Comment by slava77** [comment]
lets leave as is until the ORP next Tuesday.
Be prepared to resubmit without it if some concerns arise.

**Comment by slava77** [comment]
I see
in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7678/2518/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/step5_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT.log

```
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PATJetProducer label='patJets'
Exception Message:
Expression parser error:no method or data member named "nTracks" found for type "reco::VertexCompositePtrCandidate" (char 133)

```

**Comment by ferencek** [comment]
@slava77 Unfortunately, in a rush I didn't realize that I also need to change the method names since they are different in `reco::Vertex` and `reco::VertexCompositePtrCandidate`. The latest commit should address the issue you observed.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 2 event: 101
   [1] Running path 'outpath'
   [2] Calling event method for module PoolOutputModule/'out'
   [3] Calling produce method for unscheduled module PATJetSelector/'selectedPatJets'
   [4] Calling produce method for unscheduled module PATJetProducer/'patJets'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::AssociationVector<edm::RefToBaseProd<reco::Jet>,std::vector<float>,edm::RefToBase<reco::Jet>,unsigned int,edm::helper::AssociationIdenticalKeyReference>
Looking for module label: pfCombinedSecondaryVertexV2BJetTags

```

this is a common problem: PAT tests are made using older relval as an input; nominal resolution is to integrate PAT changes only after data products are available in the relvals

**Comment by slava77** [comment]
an alternative is to keep the PAT tests broken or disable them temporarily, but that's not my decision to make.
(we are running quite a bit of PAT as a part of miniAOD step already, so things will still be testable)

**Comment by davidlange6** [comment]
I suggest that we rather get in the habit of checking new developments in the AOD/validation process and then adding them to the PAT tests/miniAOD�

**Comment by slava77** [comment]
I'm not sure what you mean, David.
the changes made in PAT in this PR are not made for validation.

It's true that the new products are not added to the DQM for monitoring (we have a lot of products like that); but that's not related to the reasons this one has failing tests.

**Comment by davidlange6** [comment]
I wasn't clear - 

This PR apears to 

a) Add producers to reco and products to AOD 
b) Use those products in default PAT sequences

I'm just suggesting we do one, validate it, then do the next.

**Comment by ferencek** [comment]
This was one of my earlier suggestions, to take out the PAT additions from this PR and add them in a separate PR after 740pre7 is out and some RelVals made with that pre-release become available.

**Comment by slava77** [comment]
Ah, ok.
That's in line with what I said as well.

On 2/12/15 1:35 PM, David Lange wrote:
> I wasn't clear -
> 
> This PR apears to
> 
> a) Add producers to reco and products to AOD
> b) Use those products in default PAT sequences
> 
> I'm just suggesting we do one, validate it, then do the next.
> 
> On Feb 12, 2015, at 8:23 PM, Slava Krutelyov <notifications@github.com>
> wrote:
> 
>> I'm not sure what you mean, David.
>> the changes made in PAT in this PR are not made for validation.
>> 
>> It's true that the new products are not added to the DQM for monitoring (we have a lot of products like that); but that's not related to the reasons this one has failing tests.
>> 
>> �
>> Reply to this email directly or view it on GitHub.
>> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7678#issuecomment-74136850>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by slava77** [comment]
@ferencek 
I didn't think of the pat unit tests
thanks for taking out this tagger from the pat list.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7678	5e6882b
tested in CMSSW_7_4_X_2015-02-12-0200 /test area sign517/
the new pfCombinedSecondaryVertexV2BJetTags is showing up now.
the branch is light enough .. eventually, the non-PF taggers are supposed to be dropped though (as discussed a while back)

"bonus"
comparing baseline with thisPR + #7692
the old combinedInclusiveSecondaryVertexV2BJetTags are  changing noticeably, but mainly in the "can't tell" region which shifted from ~0.4 to ~0.5.

The plot is for run1 MC ttbar with PU
all_sign517vsorig_ttbarpuwf202p0c_recojetedmreftobaseprodtofloatsassociationvector_combinedinclusivesecondaryvertexv2bjettags__reco_obj_data_83

**Comment by pvmulder** [comment]
The red distribution is overall more shifted to higher discriminator values, this is what we expect for the new training as shown on slide 8 here: https://indico.cern.ch/event/369384/session/1/contribution/10/material/slides/0.pdf
(note in the presentation, the blue line is the new training)
The peak in the middle is related to PU and is strongly reduced by using CHS.

**Comment by ferencek** [comment]
I see that 740pre7 was just announced but this PR was somehow left behind. It introduces new products and was supposed to be included in the last open pre-release.

**Comment by slava77** [comment]
Uhm, that's unfortunate.

On our (RECO) side we should try to be more proactive after the signature is made to push for collection of the remaining signatures.

@davidlange6 I guess it's too late to redo pre7?
We should aim to have this in pre8.

**Comment by ferencek** [comment]
@monttj, can you sign this PR?

**Comment by ferencek** [comment]
ping @monttj @vadler

**Comment by ferencek** [comment]
@davidlange6 I suggest to override the missing analysis tools signature. The PAT changes are not significant and there is really no reason to delay merging this PR for this long.

**Comment by pvmulder** [comment]
@monttj @vadler @davidlange6 
Any (good) news for this PR?

**Pull request merged**
