### PR TITLE
Remove parameters of GsfElectronBaseProducer not used after #28429

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

As a follow up on https://github.com/cms-sw/cmssw/pull/28429, I suggest to remove many of the electron producer configuration parameters that are not needed anymore. That concerns in particular all the selection cuts and HcalHelper parameters which are duplicate right now and don't need to be (in the past there were different cuts for tracker-driven and ecal-driven but that's not used anymore).

#### PR validation:

CMSSW compiles and local matrix tests pass.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The code simplification and removal of unused parameters makes sense.
Please @afiqaize and @SohamBhattacharya confirm that this is also approved by the EGamma POG

**Comment by SohamBhattacharya** [comment]
@perrotta I see in [1] that the DQM tests have not been run. Can you please let us know why? 
@afiqaize and I wanted to check some of the histograms. 

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ae8fe1/5090/summary.html

**Comment by perrotta** [comment]
> @perrotta I see in [1] that the DQM tests have not been run. Can you please let us know why?
> @afiqaize and I wanted to check some of the histograms.
> 
> [1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ae8fe1/5090/summary.html

Why do you say so? The test have been run, and the only differences are those linked to the MessageLogger in 25202 and 10224 (not relevant), plus the recurrent HI non reproducibility in 8.0 (to be adjusted at some time in DQM, but not relevant for this PR)

**Comment by SohamBhattacharya** [comment]
@perrotta
Sorry for the confusion. We were looking for the plots under 'DQM tests'. 
We just rechecked the differences, and it looks fine.
I've also gone through the changed code and it's okay even for the new Phase-II electrons. 

@afiqaize and I confirm that this is okay with the Egamma group.

**Comment by perrotta** [comment]
+1
- Cleaning of unused parameters and consequent restructuring of the GsfElectron producers is implemented as in the PR description
- Jenkins tests pass and show no differences, as it should
- This cleaning was also [approved](https://github.com/cms-sw/cmssw/pull/29157#issuecomment-600198529) by the EGM POG

**Comment by silviodonato** [comment]
+1

**Pull request merged**
