### PR TITLE
fix merge of FWLite python fix into ROOT6 branch

### PR DESCRIPTION
**Pull request by dan131riley**
Fix problems with the merge of python-fwlite-handle-fix into the ROOT6 branch; should only be applied to CMSSW_7_4_ROOT6_X.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Thanks Dan

**Comment by ktf** [comment]
ROOT6 only. Approving.

**Pull request merged**
