### PR TITLE
MC GT updates with Reco BeamSpot, JECs for HLT and SiPixelQuality along with GEN-SIM samples update for RelVals

### PR DESCRIPTION
**Pull request by arunhep**
This PR contains the MC GT updates explained below as well as update of Gen-SIM samples for relvals with new BeamSpot measurement.
# Summary of changes in Global Tags

## Upgrade

   * **PhaseI 2017 cosmics peak scenario** : [92X_upgrade2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v2) as [92X_upgrade2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v2/92X_upgrade2017cosmics_realistic_peak_v1):
      * RECO Beamspot update
      * JECS for HLT
      * SiPixel channel quality to v4 announced here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2995/1/2.html

   * **PhaseI 2017 cosmics scenario** : [92X_upgrade2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v2) as [92X_upgrade2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v2/92X_upgrade2017cosmics_realistic_deco_v1):
      * RECO Beamspot update for 2017
      * JECs for HLT
      * SiPixel channel quality to v4 announced here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2995/1/2.html

   * **PhaseI 2017 design scenario** : [92X_upgrade2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v2) as [92X_upgrade2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_design_IdealBS_v2/92X_upgrade2017_design_IdealBS_v1):
      * JECs for HLT

   * **PhaseI 2017 realistic scenario** : [92X_upgrade2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v2) as [92X_upgrade2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v2/92X_upgrade2017_realistic_v1):
      * RECO Beamspot update
      * JECS for HLT
      * SiPixel channel quality to v4 announced here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2995/1/2.html

   * **PhaseI 2018 cosmics scenario** : [92X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v2) as [92X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v2/92X_upgrade2018cosmics_realistic_deco_v1):
      * RECO Beamspot update for 2017
      * SiPixel channel quality to v4 announced here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2995/1/2.html

   * **PhaseI 2018 realistic scenario** : [92X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_realistic_v2) as [92X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018_realistic_v2/92X_upgrade2018_realistic_v1):
      * RECO Beamspot update
      * SiPixel channel quality to v4 announced here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2995/1/2.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by franzoni** [comment]
@arunhep @rmanzoni 

+ change in pixel occupancy, dominated by the usage of new events/gensim and not obviously ascribable to the change in pixel quality

+ consistency between new SIM beamspot for 2017 and 2018 is closer to the pixel barycenter (RED is this PR, blue is reference): 
  the amplitude of the sinusoidal patter decreases as expected form the fact that the new beamspot 
alcabeammonitor__validation_hd0phi0


+ overall picture of tracking shows no signs of anomaly / bad
tracking__trackfrompv_generalfrompv_trackingparticlerecoasssociation_chi2mean
tracking__trackfrompv_generalfrompv_trackingparticlerecoasssociation_hits_eta

**Comment by franzoni** [comment]
@slava77 @davidlange6 
After your feedback, we'll proceed with the next steps of condition integration for 92

**Comment by franzoni** [comment]
+1

**Comment by slava77** [comment]
assign reconstruction

@franzoni 
if reco feedback is needed in similar situations in the future, please do not hesitate to assign the reco category to a PR

**Comment by franzoni** [comment]
> please do not hesitate to assign the reco category to a PR

ok, good point.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19203	3e2a3e1
- changes in BS from Realistic50ns13TeVCollision to Realistic25ns13TeVEarly2017Collision. This only affects MC; resim leads to different vertex distribution and subsequent difference.
- jenkins tests (looking at 10024 10 events) appear to be OK.
    - plots posted in https://github.com/cms-sw/cmssw/pull/19203#issuecomment-308430709 are well representative of consistent behavior

**Comment by davidlange6** [comment]
+1

**Pull request merged**
