### PR TITLE
break histos in several folders. Add monitoring plots

### PR DESCRIPTION
**Pull request by argiro**
small but useful improvements in the ECAL pedestal PCL workflow

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
hi @argiro - remind me in which workflows/steps this runs? There are quite a lot of new histograms..

**Comment by argiro** [comment]
Hi,

it runs in the last step (harvesting) of the new ECAL PCL at Tier0. There's 12 new monitoring histograms that are creating in the harvesting, should not be an issue.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
