### PR TITLE
[12_4_X] Push_back 0th weight manually, prevent duplication of PS weights in P8.30x

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

The weight storage logic in Pythia8 had been changed since 8.30x version, causing the duplication of PS weights in CMS. This PR prevents weight duplication by setting `Pythia8ToHepMC::set_store_weights(false)` and keeps the old weight structure the same as in UL by push_back 0th weight manually.

#### PR validation:

Tested with the workflow `555`, `556` (should reduce the number of weights from 134 to 46)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #38012. This PR is intended for 12_4_X, to prevent PS weight duplication in the large scale Run3 MC production.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test workflow 555, 556

**Comment by SiewYan** [comment]
please test workflow 555, 556

retest

**Comment by SiewYan** [comment]
+1

test result is expected, 134 weights reduced to 46 [*]
[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-24-2300+eab68b/50489/556.0_TTbar_NLO_Pow_13TeV_py8+TTbar_Pow_LHE_13TeV+Hadronizer_TuneCP5_13TeV_powhegEmissionVeto2p_pythia8+HARVESTGEN2/Generator__GenWeight_wgtVal.png

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38012

**Comment by perrotta** [comment]
+1
- verbatim backport of the PR merged in master since CMSSW_12_5_X_2022-05-23-2300

**Pull request merged**
