### PR TITLE
Run3-alca248B Changes to the calibration scripts for HCAL Isotrack analysis of 2024 data sets

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Changes to the calibration scripts for HCAL Isotrack analysis of 2024 data sets

#### PR validation:

Use these to extract the most recent calibration dataset for 2024C, 2024D, @0@4E

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
