### PR TITLE
81X  SiStrip Gains PCL cleanup

### PR DESCRIPTION
**Pull request by mmusich**
General cleanup. This PR includes:
- preparation of a new metadata for tier-0 uploads of the `SiStripGainsAfterAbortGap` workflow
- wf. 1001.0 now consumes directly the `autoPCL` dictionary (as Tier-0 does)
- fixing `AlCaHarvesting` and `autoPCL` to run in production the `SiStripGainsAfterAbortGap` workflow

attn: @dimattia

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@hengne  @fabozzi @srimanob, @ggovi 
any comment about this PR? I would like to move along preparing also the 80x equivalent (we need it to activate a still dormant piece of the PCL).

**Comment by ggovi** [comment]
+1

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
