### PR TITLE
Adding no-HF grid-based rho : 75x forward-port

### PR DESCRIPTION
**Pull request by rappoccio**
Forward port of #11771

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11773 a3fbc0333111cc90f4d4880f4503005ee00b0c1e

Adding an eta-restricted (no HF) grid-based rho for future use in Mini-AOD or RECO. There should be no other change in monitored quantities. #11771 is the 74X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-10-13-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
-1

rhos are not a part of HeavyIons processing sequence
complain if there is use case in 75X

**Comment by rappoccio** [comment]
@slava77 I'm not sure what you mean, do I have to do something?

**Comment by slava77** [comment]
Sal, 
considering that now it has settled that 75X is to be used only for HI processing, this PR is not relevant for 75X.
if you think that this PR is needed for 75X for some other reasons, please let us know and this PR can be reconsidered for 75X.

**Comment by rappoccio** [comment]
Hi, Slava,

OK sounds good. Should be closed then.

Cheers,
Sal

**Pull request closed without merging**
