### PR TITLE
Run3-sim49 Second step to remove access of DDCompactview from SimG4CMS/Calo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Getting ready to remove access of DDCompactView from SimG4CMS/Calo/ECalSD

#### PR validation:

Tested with standard runTheMatrix.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
