### PR TITLE
TkDQM: Remove Phase0 pixelCertification module from sequences

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Removes ```pixelCertification``` module from relevant sequences. Fixes crashes as reported [here](https://github.com/cms-sw/cmssw/pull/36203#issuecomment-976311314).
#### PR validation:
Wf 136.73 runs.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA

### CODE REVIEW

**Comment by sroychow** [comment]
test parameters:
- workflow = 136.73

**Comment by mmusich** [comment]
test parameters:
   * workflows =  136.73

**Comment by sroychow** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
type bug fix

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
