### PR TITLE
Remove hard-coded RPC conditions

### PR DESCRIPTION
**Pull request by bapavlov**
The conditions are now managed in the Global Tag, so we could remove the hard-coded conditions.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi @bapavlov -please make the title of this PR descriptive of the change. Thanks

**Comment by bapavlov** [comment]
hi @davidlange6 I have changed the title of the PR to "Remove hard-coded RPC conditions"

**Comment by davidlange6** [comment]
+1

**Pull request merged**
