### PR TITLE
Updated N-subjettiness computation in BoostedDoubleSecondaryVertex tagger

### PR DESCRIPTION
**Pull request by ferencek**
Backport of a single commit from #12984

This PR updates the way the N-subjettiness is computed in the BoostedDoubleSecondaryVertex tagger. This change is necessary in order to collect all the jet constituents of `slimmedJetsAK8` stored in MiniAOD where subjets and the remaining jet constituents are added as daughters. This is a follow-up to #12890

The code changes affect the `pfBoostedDoubleSecondaryVertexAK8BJetTags` discriminator embedded in `slimmedJetsAK8` in MiniAOD but should leave its numerical values unchanged.

### CODE REVIEW

**Comment by slava77** [comment]
@ferencek 
#12890 is not merged yet.
Is this PR logically independent of #12890? Meaning, would either of them work separately and still make sense?
If not,  #12890 should be either updated or superseded.

**Comment by ferencek** [comment]
@slava77, the two PRs are essentially independent. This PR is only needed if one wants to remake the `pfBoostedDoubleSecondaryVertexAK8BJetTags` discriminator from `slimmedJetsAK8`. Logically, it belongs to #12984 and is the only piece of it that can be backported without affecting the standard reco and MiniAOD production in 76X.

So I think it should be fine to have it as a separate PR especially given the fact that #12890 was already tested and signed.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12988	2092595
- code changes are in line with the description; only tagging using miniAOD as input is affected
- jenkins tests pass and comparisons with baseline show no differences (the tagger values in miniAOD are not monitored)
    - inspection of the local copy of miniAOD outputs from jenkins for 134.911 and 25202.0 shows there are no differences in slimmedJetsAK8 tag values

**Comment by davidlange6** [comment]
+1

**Pull request merged**
