### PR TITLE
modify nanoDQMIO configuration

### PR DESCRIPTION
**Pull request by LukaLambrecht**
#### PR description:

This PR prepares the production of the nanoDQMIO dataset for 2022 data.
The modifications are twofold:
- The configuration file listing the monitoring elements (MEs) to be stored is modified in accordance with the requests from subsystems.
- The selection of the MEs is changed so that only those MEs that exactly match a pattern in the configuration file are stored. Previously, each ME that contained a pattern in the configuration file was stored, leading to the storing of some unneeded MEs with overlapping names.

More information on the context of this PR can be found in this [google doc](https://docs.google.com/document/d/1VvDBvkMlKeJWKg9km30Kg3f1Lv3KB2HXE9Ne4HBbKLo/edit?usp=sharing) (note: under development, subject to change).  

#### PR validation:

We performed the tests as listed [here](http://cms-sw.github.io/PRWorkflow.html) (in 'Before making your pull request').
Apart from that, the modified selection and configuration was used to produce nanoDQMIO files locally. No issues were observed and the content of the nanoDQMIO file in terms of ME content is as expected.

#### Backport

This PR is intended for the reprocessing of 2022 data, most likely in 12_4_X.

### CODE REVIEW

**Comment by rvenditti** [comment]
please test

**Comment by LukaLambrecht** [comment]
Sorry for an additional commit, but two more MEs for ECAL were requested.
The commit does not affect any source code, only two additions to the nanoDQMIO configuration file.

**Comment by rvenditti** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
@LukaLambrecht @cms-sw/xpog-l2 shouldn't this also get backported to 12_6_X, besides 12_4_X?
If so, should we wait for it before cutting 12_6_0, or can we postpone this being included in a future 12_6 release after EOY break?

**Comment by vlimant** [comment]
hello, this has nothing to do with xpog, as far as I can tell.

**Comment by vlimant** [comment]
as a side note, using "nano" here is bound to induce confusion as so many level.
is it "as small" as NANO ? is it as flat as NANO ? ...

**Comment by perrotta** [comment]
Thank you @vlimant for your answer.
I wanted to be sure that possible nano productions with 12_6, and their monitoring, were't affected if this PR was left aside. After your confirmation, and given that all other PR requested to be in yesterday at the ORP meeting are now merged, I think we are ready to start building CMSSW_12_6_0 in the next hours.

**Comment by perrotta** [comment]
> as a side note, using "nano" here is bound to induce confusion as so many level. is it "as small" as NANO ? is it as flat as NANO ? ...

@cms-sw/dqm-l2 I think this question is for you.

**Comment by rvenditti** [comment]
in our mind, it should be small as nano, because in this new data-tier we will save just a small subset of Monitor Elements wrt to what is stored in DQMIO. nanoDQMIO  has nothing to do with nanoAOD, so we don't need to backport this PR to 12_6. thanks for checking.

**Pull request merged**
