### PR TITLE
Run3-hcx368X Complete the backport of #46115 where one added file was missed out

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Complete the backport of #46115 where one added file was missed out

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Origibal PR #46115

### CODE REVIEW

**Comment by bsunanda** [comment]
@antoniovilela, @mandrenguyen Could you please make this as Urgent.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = DQM/TrackingMonitorSource

**Comment by smuzaffar** [comment]
please test

lets run the tests and checkout  DQM/TrackingMonitorSource  to make sure the failing unit test run during PR tests

**Comment by bsunanda** [comment]
@smuzaffar this pr is good irrespective of testing with DQM

**Comment by bsunanda** [comment]
urgent

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , this is needed for 14.1.X. This adds the missing Geometry/ForwardCommonData/data/rpd/2021/v2/rpd.xml needed by https://github.com/cms-sw/cmssw/pull/46263 (which is already merged in 14.1.X)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
