### PR TITLE
DD Offline DB Loader Cleanup

### PR DESCRIPTION
**Pull request by ianna**
- Remove unused code
- Remove unneeded dependencies

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild - the errors are not related to the PR:

```
Building shared library tmp/slc6_amd64_gcc491/src/Geometry/EcalAlgo/src/GeometryEcalAlgo/libGeometryEcalAlgo.so
/afs/cern.ch/cms/sw/ReleaseCandidates/volB/slc6_amd64_gcc491/external/gcc/4.9.1-cms/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.9.1/../../../../x86_64-redhat-linux-gnu/bin/ld: cannot find -lCondCoreDBOutputService
/afs/cern.ch/cms/sw/ReleaseCandidates/volB/slc6_amd64_gcc491/external/gcc/4.9.1-cms/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.9.1/../../../../x86_64-redhat-linux-gnu/bin/ld: cannot find -lCondCoreCondDB
collect2: error: ld returned 1 exit status
```

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild - the errors are unrelated to this PR:
```
class  HGCEEDetId found in libDataFormatsHGCDigi.so  is already in libDataFormatsForwardDetId.so
```

**Pull request merged**
