### PR TITLE
Run3-ft18 Modify the run3 scenario with new beampipe, forwardshield and totemT2

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the run3 scenario with new beampipe, forwardshield and totemT2

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @silviodonato I believe the error is not due to this PR - it complains of a product named "puppi" not found in step2 (PAT-DQM) on 2018D data (136.88811). Can you please look into this?

**Comment by silviodonato** [comment]
please test
I've just merged the fix (see #29823)

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
