### PR TITLE
fix on mean s/n calculation

### PR DESCRIPTION
**Pull request by jandrea**
Fix a bug in the mean S/N calculation for the ControlView plots in the SiStrip directory.
We did in 93X but we would like to have it in 94X too. Should we prepare a pull request for 94X ?

### CODE REVIEW

**Comment by boudoul** [comment]
hello @jandrea , Actually this is not needed for 93X (will not be used for data taking) , instead prepare a pull request for master (94X) AND a backport to 92X for the data taking, thanks.

**Comment by jandrea** [comment]
@boudoul Thanks. I will do it in the latest 94X release. Sorry I am new into this. For the backport to 92X, I just need to make a pull request for the latest 92 release ? I don’t find a 92X release (latest is 920_patch3?)

**Comment by boudoul** [comment]
ok I see you PR for master (well you made 94X but the robot understood for you that it was for master , next time you can directly target directly master)

[the policy is simple, for any new PR , don't ask yourself any question, just make a PR for master (which is the default case) ] 

Then in case a backport is needed (like in your case) , look the last IB of the targeted queue .
Example for you : you want to backport in 92X, so you will make a PR in the 92X queue , but attention you should base your code from one of the last 92X IB : CMSSW_9_2_X_2017-09-24-0000

Hope this helps 
btw this PR (for 93X) can be closed

**Comment by jandrea** [comment]
@boudoul Thanks ! That helps a lot. I will backport to 92X now

**Pull request closed without merging**
