### PR TITLE
HLT menu V3.5 (10_3)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT menu V3.5
Based on CMSSW_10_3_X_2018-09-02-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
for addOnTests.py

**Comment by fabiocos** [comment]
+1

**Pull request merged**
