### PR TITLE
CCLUT quality control and preliminary quality definition for GEM-CSC stubs (CCLUT-6)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:
- I updated the CLCT data word. The 3-bit Run-3 pattern number and 4-bit slope (as calculated from the 12-bit comparator code and one of 5 patterns) are assigned in the `pattern_ ` member. In addition, the Run-2 pattern number will be stored in `pattern_ `. For Run-3 scenarios, this Run-2 pattern is but an approximation. The idea is to continue sending LCTs with Run-2 patterns to the EMTF/OMTF to facilitate integration and training/testing of new algorithms for prompt and displaced muons. LCTs in real data will not contain the approximate Run-2 pattern number. In due time, the simulation should also only send the actual Run-3 pattern number.
- The `CSCLCTTools` file was replaced by class `LCTQualityControl` to check for valid stubs
- Preliminary LCT quality definitions were added for Run-3 CSC-only stubs and Run-3 GEM-CSC stubs
- The redundant variables `dynamic_state_machine_zone` and `useOldLCTDataFormat_` have been removed. The former parameter was made redundant in #25165. The latter is superseded by `use_run3_patterns_`

#### PR validation:

Tested in CMSSW_11_2_X_2020-08-06-1100 on `/RelValSingleMuFlatPt2To100/CMSSW_11_0_0-PU25ns_110X_mcRun4_realistic_v3_2026D49PU200-v1/GEN-SIM-DIGI-RAW` and in CMSSW_11_2_0_pre3 on `/RelValSingleMuPt10/CMSSW_11_0_0-110X_mcRun4_realistic_v2_2026D49noPU-v1/GEN-SIM-DIGI-RAW`

Results shown here: https://indico.cern.ch/event/947218/contributions/3980597/attachments/2089339/3510511/CSCPositionResolutionNewPatterns_SD_20200819.pdf

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

FYI @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
It probably would be a good idea to merge CSCLCTTools and all checkValid functions in 3 different classes into a single CSCQualityControl class.

**Comment by dildick** [comment]
Replaced CSCLCTTools with LCTQualityControl

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
There are few errors and warnings in WF 10224.0. @civanch Where can I find out which modules are reporting the messages? Reason why I'm asking is that LCTQualityControl prints out LogErrors if stubs are invalid and I want to make sure no invalid stubs are being produced.

**Comment by civanch** [comment]
please test

let us check that the problem not IB dependent

**Comment by dildick** [comment]
Failure in WF 8. from pixels, unrelated to CSC trigger.

**Comment by dildick** [comment]
@civanch Would any LogErrors that originate from LCTQualityControl in future pull requests be picked up and displayed in the standard tests?

**Comment by dildick** [comment]
@civanch I just realized that I forgot to add a quality control check in the Muon Port Card class.

**Comment by dildick** [comment]
Testing it now `/RelValSingleMuFlatPt2To100/CMSSW_11_0_0-PU25ns_110X_mcRun4_realistic_v3_2026D49PU200-v1/GEN-SIM-DIGI-RAW`

**Comment by dildick** [comment]
...segfault in MuonPortCard::sort when calling checkValid()

**Comment by dildick** [comment]
I need to rewrite part MPC simulation, so there is an MPC card for each endcap, station and sector (as in UXC). Right now, the CSC trigger is reusing the same object over an over, which seems to interfere with quality control.

**Comment by dildick** [comment]
I think that's about it. Still need to check that the MPC works as expected in Run-1 and Run-2/3 scenarios.

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
I'll rerun a Run-1 WFs to be sure

**Comment by dildick** [comment]
WF 9.0 crashes with 
```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 12-Aug-2020 15:45:17.350 CDT
create data set info Default
create data set info Default
create data set info Default
create data set info Default
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 on stream 0 at 12-Aug-2020 15:45:50.716 CDT
cmsRun: symbol lookup error: /cvmfs/cms-ib.cern.ch/nweek-02641/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-09-2300/lib/slc7_amd64_gcc820/libEventFilterCSCRawToDigi.so: undefined symbol: _ZN11CSCCLCTDigiC1EttttttttttsNS_7VersionE
```

**Comment by dildick** [comment]
I suspect I need extra ioread rules such as 
```
   <ioread sourceClass="CSCCLCTDigi"  targetClass="CSCCLCTDigi" version="[-11]" target="version_" source=""> <![CDATA[ version_ = CSCCLCTDigi::Version::Legacy; ]]> </ioread>
   <ioread sourceClass="CSCCLCTDigi"  targetClass="CSCCLCTDigi" version="[-12]" target="slope_" source=""> <![CDATA[ slope_ = 0; ]]> </ioread>
```
But this does not seem to be solving the problem

**Comment by dildick** [comment]
@civanch Do you have any suggestions?

**Comment by dildick** [comment]
I updated the CLCT data word so that I don't introduce new members. Rather, the Run-3 pattern number and slope are assigned in the `pattern_ ` member - in addition to the Run-2 pattern number. The performance on Run-1 and Run-2 WFs should be unchanged. I'll check the efficiency and will post a few plots.

**Comment by dildick** [comment]
WF 9.0 now runs fine. 
```
9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Aug 17 09:53:23 2020-date Mon Aug 17 09:17:10 2020; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by dildick** [comment]
Position resolution plots (not for publication) obtained with `/RelValSingleMuPt10/CMSSW_11_0_0-110X_mcRun4_realistic_v2_2026D49noPU-v1/GEN-SIM-DIGI-RAW`. CLCT (L1T) position is obtained with `getFractionalStrip()`, whereas the true muon position (SIM) is the strip number of the simhit in the 3rd CSC layer. Effect of the upgraded algorithm is most noticeable for prompt, low-pT muons in ME1 and ME2.

Res_CSCCLCT_pos_ME11
Res_CSCCLCT_pos_ME12
Res_CSCCLCT_pos_ME13
Res_CSCCLCT_pos_ME21
Res_CSCCLCT_pos_ME22
Res_CSCCLCT_pos_ME31
Res_CSCCLCT_pos_ME32
Res_CSCCLCT_pos_ME41
Res_CSCCLCT_pos_ME42

**Comment by dildick** [comment]
@civanch Can you rerun the tests, please?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by rekovic** [comment]
@dildick The performance in PU0 is slightly improved, so good.  Please let us know of the performance with PU200 when available.

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
@rekovic My most recent presentation with LCT efficiency at PU200 is this one https://indico.cern.ch/event/946435/contributions/3977016/attachments/2087496/3507142/CSCTP_Eff_SD_20200804.pdf. See page 7-8. Efficiency of Run-3 patterns vs Run-1/2 patterns at PU0 can be found in this recent presentation https://indico.cern.ch/event/947218/contributions/3980597/attachments/2089339/3510511/CSCPositionResolutionNewPatterns_SD_20200819.pdf (CSC Weekly Meeting).

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
