### PR TITLE
CTPPS validation: workaround for -O3 ASAN compilation issue

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:
With `-O3` optimization in the ASAN builds, `Validation/CTPPS/plugins/ValidationCTPPSPlugins/CTPPSTrackDistributionPlotter.cc` is failing to compile with errors of the form:
```
In file included from src/DataFormats/Common/interface/RefVector.h:18,
                 from src/DataFormats/ProtonReco/interface/ForwardProton.h:14,
                 from src/Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc:20:
In member function 'edm::RefVectorIterator<C, T, F>::reference edm::RefVectorIterator<C, T, F>::operator*() const [with C = std::vector<CTPPSLocalTrackLite>; T = CTPPSLocalTrackLite; F = edm::refhelper::FindUsingAdvance<std::vector<CTPPSLocalTrackLite>, CTPPSLocalTrackLite>]',
    inlined from 'virtual void CTPPSProtonReconstructionPlotter::analyze(const edm::Event&, const edm::EventSetup&)' at src/Validation/CTPPS/plugins/CTPPSProtonReconstructionPlotter.cc:608:22:
  src/DataFormats/Common/interface/RefVectorIterator.h:49:39: error: 'this' pointer is null [-Werror=nonnull]
    49 |       return (*nestedRefVector_)[iter_];
```
For various reasons detailed in https://github.com/cms-sw/cmssw/issues/44931#issuecomment-2142898754 this has to be a compiler bug.  Nevertheless, this PR provides a workaround for the compilation errors.

#### PR validation:

Compiles, purely technical fix, harmless.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by smuzaffar** [comment]
@tjavaid , IBs are broken, lets wait for today's 11h00 IB

**Comment by tjavaid** [comment]
please test

**Comment by antoniovilela** [comment]
please test for CMSSW_14_1_ASAN_X

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
