### PR TITLE
HLT menu development for `12_3_X` (Patatrack GPU modules)

### PR DESCRIPTION
**Pull request by missirol**
backport of #37783

#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2288](https://its.cern.ch/jira/browse/CMSHLT-2288): [TSG] Introduction of Patatrack GPU modules in the HLT combined table.

This update introduces in the offline HLT menus the modules for GPU offloading developed so far as part of the Patatrack project (Pixel local reco, Pixel tracking/vertexing, ECAL and HCAL local recos). Effectively, it incorporates the customisation [`customizeHLTforPatatrackTriplets`](https://github.com/cms-sw/cmssw/blob/CMSSW_12_3_2/HLTrigger/Configuration/python/customizeHLTforPatatrack.py#L844) into the HLT menus maintained by TSG. This also coincides with the introduction of "Tasks" in the offline HLT menus. Following the discussion in #36938, it is expected that in the near future `cms.Task` will be replaced by `cms.ConditionalTask` in HLT configs (likely in `12_4_X`).

This PR also includes small changes to the TSG tests to ensure that those tests continue to work even when they are executed on a machine with a GPU.

  - A customisation to HLT+RECO tests is added to remove GPU EventSetup modules from Tasks that are not included in the Schedule; this is needed to make said ES modules available to HLT producers when the test runs on a GPU machine. More details can be found [here (CMSHLT-2288)](https://its.cern.ch/jira/browse/CMSHLT-2288?focusedCommentId=4326483&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4326483).

  - The HLT-integration tests are forced, for now, to run on CPU even if the machine has a GPU. This avoids tests failing due to the current limits in reproducibility of HLT outputs when using GPUs.

Both changes are workarounds in a way, and they could/should be improved in the future.

A small fix in `customizeHLTforPatatrack.py` is also included.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37783

Development of HLT menus for Run-3 startup.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - differences in PR outputs are in line with updates to the GRun menu
 - as noted in https://github.com/cms-sw/cmssw/pull/37783#issuecomment-1117570685, the introduction of Tasks affects the list of "Modules in Paths" reported by the Framework (to be checked if this has any consequences for other HLT utilities, and how `ConditionalTask`s behave in this respect)

**Comment by qliphy** [comment]
+1

**Comment by perrotta** [comment]
Please notice: this PR will not enter CMSSW_12_3_2_patch1, which was just built and we are just waiting for some IB test to finish to announce it

**Comment by missirol** [comment]
Thanks for the notification, Andrea. That is okay, of course.

**Pull request merged**
