### PR TITLE
Fix calo unpacker valgrind 94x

### PR DESCRIPTION
**Pull request by nsmith-**
backport of #21486

### CODE REVIEW

**Comment by nsmith-** [comment]
please test

**Comment by nsmith-** [comment]
+1
Backport because any sequence with `RAW2DIGI` will hit this invalid access.  Luckily, it seems the code never gives the freed memory back to the system, otherwise there would have been segfaults everywhere.

**Comment by thomreis** [comment]
Hi @nsmith- 
The DQM has moved to 10_0_X. This PR can be closed.

**Comment by thomreis** [comment]
It is not for DQM actually, but nevertheless.

**Comment by nsmith-** [comment]
Closing as apparently no previous large reco campaign saw issues, and no new reco campaign is planned for 94x as I understand.

**Pull request closed without merging**
