### PR TITLE
HCAL MC: adding pulse shape 208 for signal reconstruction (11_1_X)

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Backporting new HCAL MC reco pulse shape to 11_1, see https://github.com/cms-sw/cmssw/pull/31014.
It is deactivated by default and can be activated by HcalRecoParams conditions.

#### PR validation:

Workflow 11634.0 runs with default and new pulse shape.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #31014

**Comment by christopheralanwest** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by tlampen** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
