### PR TITLE
hadronizer for HToGG Minlo NNLOPS pLHE relval

### PR DESCRIPTION
**Pull request by chayanit**
#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
@chayanit could you please elaborate, what is the purpose of this PR?. which relval?

**Comment by alberto-sanchez** [comment]
please test

**Comment by chayanit** [comment]
Hi @alberto-sanchez , this is needed for new pLHE RelVal workflow we want to add to the main/standard campaign according to this JIRA https://its.cern.ch/jira/browse/PDMVRELVALS-27
Chayanit

**Comment by chayanit** [comment]
Hi @efeyazgan, we discussed (me and @pgunnell) that as this relval is needed just to test the whole machinery and workflow in the new releases. The process is not so important and there will be no specific physics meaning (https://its.cern.ch/jira/browse/PDMVRELVALS-27). So we decided to keep the same tuning for all MC years. It would be nice if we can have this merge soon. Thanks.

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
