### PR TITLE
add TenTau gen fragments

### PR DESCRIPTION
**Pull request by mtosi**
as PR https://github.com/cms-sw/cmssw/pull/18039

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
assign pdmv
to confirm plans for relval and what this replaces (that can perhaps be cleaned up from the release)

**Comment by fabozzi** [comment]
+1

**Comment by rmanzoni** [comment]
Thanks @mtosi for taking care of this.  

I have a couple of comments, sorry for posting late, but I had the chance to go through this thread just now:
* I believe we only need this fragment `TenTau_E_15_200_pythia8_cfi.py` and not `TenTau_E_0_200_pythia8_cfi.py` because we'll hardly need taus from 0 to 15 GeV. If and when we'll need them we'll act accordingly
* since this is not a _real_ physics process, I would keep the RelVals we already have (ZTT, ZpTT) and have this tau gun sample in addition
* I think it would be useful to increase max tau p_T from 200 GeV to at least 500 GeV so that we populate all the bins. 

Is this reasonable enough? Let me know if this is too much and I'll try to cut corners where possible.

Thanks

**Comment by govoni** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by mtosi** [comment]
could we integrate this PR ?

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
