### PR TITLE
Add 2023 ProdLike workflow

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Allow 2023 to be prod-like workflow (.21)

#### PR validation:
Try to dump the configuration with 
`runTheMatrix.py --what upgrade -l 12434.21 --wm init`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 12434.21,12634.21
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
