### PR TITLE
add eta cut for PFCandidates in Scouting

### PR DESCRIPTION
**Pull request by jsalfeld**
#### PR description:

Added Eta cut option for PFCandidates to HLTScoutinfPFProducer. Once restricted to |eta|<3, the event size decreases by roughly factor 2.

#### PR validation:

I checked running with and without the cut and checked the event content everything is as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fwyzard** [comment]
please use `std::abs` instead of `fabs` .

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
