### PR TITLE
Reduce PCL disk space 80X

### PR DESCRIPTION
**Pull request by ghellwig**
Reduces size of binaries written to disk in the harvesting step of the SiPixelAli to 30% of it's original size.
Addresses issue reported in [Tier-0 Operations HN](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1435/1/1.html).

Backport of  #14961 with #14876 merged.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
@smuzaffar I think the problem with the test labels in #14876 has been propagated to this PR because the current PR is based on #14876. @cmsbuild seems to be confused about the test status.
Could you please have look?

**Comment by mmusich** [comment]
+1

**Comment by ghellwig** [comment]
rebased to remove merge conflicts with #14876

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
