### PR TITLE
Adjust CondFormats/Serialization for boost 1.72.0

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Add the least for our code to work with boost 1.71.0. 
Aims to check indirect dependencies and ping package responsible check the differences

#### PR validation:

Builds CondFormats/Serialization. Unit tests run successfully 

#### Note

Deprecations warning is thrown at build saying 

```
In file included from /build/mrodozov/fix_boost/build_tool_conf/slc7_amd64_gcc820/external/boost/1.71.0/include/boost/detail/endian.hpp:9,
                 from /build/mrodozov/fix_boost/build_tool_conf/slc7_amd64_gcc820/external/boost/1.71.0/include/boost/archive/impl/basic_binary_iarchive.ipp:25,
                 from /build/mrodozov/fix_boost/CMSSW_11_1_X_2019-12-11-1100/src/CondFormats/Serialization/src/templateInstantiations.cc:7:
/build/mrodozov/fix_boost/build_tool_conf/slc7_amd64_gcc820/external/boost/1.71.0/include/boost/predef/detail/endian_compat.h:11:161: note: #pragma message: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
 #pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
```

meaning additional code adjustments are expected.

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters
- pull_request = https://github.com/cms-sw/cmsdist/pull/5387

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
So boost 1.72 was just released on Wednesday

**Comment by mrodozov** [comment]
I noticed, the latest docs were pointing to 72 I'll move it to it but first I have to adjust cmssw :/

**Comment by mrodozov** [comment]
I moved the cmsdist pr to new boost (72) but still in trouble with the endian

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
@Dr15Jones I changed the reference to 1.72.0 so that we have the latest.
the difference between this two:
https://www.boost.org/doc/libs/1_72_0/boost/math/special_functions/detail/fp_traits.hpp
https://www.boost.org/doc/libs/1_67_0/boost/math/special_functions/detail/fp_traits.hpp
shows this, so it might be due to wrong #define that doesn't match somewhere ...
```
8c8
< <title>boost/math/special_functions/detail/fp_traits.hpp - 1.72.0</title>  <link rel="icon" href="/favicon.ico" type="image/ico" />
---
> <title>boost/math/special_functions/detail/fp_traits.hpp - 1.67.0</title>  <link rel="icon" href="/favicon.ico" type="image/ico" />
37c37,39
<   
---
>   <div class="boost-common-header-notice"><a class="boost-common-header-inner" href="/doc/libs/release/boost/math/special_functions/detail/fp_traits.hpp">This is the documentation for an old version of Boost.
>                 Click here to view this page for the latest version.</a></div>
> 
72c74
< #include &lt;<a href="../../../../boost/predef/other/endian.h">boost/predef/other/endian.h</a>&gt;
---
> #include &lt;<a href="../../../../boost/detail/endian.hpp">boost/detail/endian.hpp</a>&gt;
99c101
< #           define BOOST_FPCLASSIFY_PREFIX ::__std_alias::
---
> #           define BOOST_FPCLASSIFY_PREFIX ::__std_alias:: 
101c103
< #           define BOOST_FPCLASSIFY_PREFIX ::_STLP_VENDOR_CSTD::
---
> #           define BOOST_FPCLASSIFY_PREFIX ::_STLP_VENDOR_CSTD:: 
132c134
< /*
---
> /* 
264c266
< #if BOOST_ENDIAN_BIG_BYTE
---
> #if defined(BOOST_BIG_ENDIAN)
266c268
< #elif BOOST_ENDIAN_LITTLE_BYTE
---
> #elif defined(BOOST_LITTLE_ENDIAN)
324c326
< #if BOOST_ENDIAN_BIG_BYTE
---
> #if defined(BOOST_BIG_ENDIAN)
326c328
< #elif BOOST_ENDIAN_LITTLE_BYTE
---
> #elif defined(BOOST_LITTLE_ENDIAN)
438c440
< #if BOOST_ENDIAN_BIG_BYTE
---
> #if defined(BOOST_BIG_ENDIAN)
440c442
< #elif BOOST_ENDIAN_LITTLE_BYTE
---
> #elif defined(BOOST_LITTLE_ENDIAN)
519c521
< #if BOOST_ENDIAN_BIG_BYTE
---
> #if defined(BOOST_BIG_ENDIAN)
521c523
< #elif BOOST_ENDIAN_LITTLE_BYTE
---
> #elif defined(BOOST_LITTLE_ENDIAN)
605c607
<    &amp;&amp; !defined(__VXWORKS__)
---
>    &amp;&amp; !defined(__VXWORKS__)
```

**Comment by Dr15Jones** [comment]
The header file which must have changed is this one:

https://www.boost.org/doc/libs/1_67_0/boost/math/special_functions/detail/fp_traits.hpp

as that is the origin of the traits class.

**Comment by Dr15Jones** [comment]
probably trying to compile the failing file using -E and then looking at exactly what the compiler is trying to parse would help to diagnose the problem.

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
do you have any news on this PR?

**Comment by mrodozov** [comment]
@silviodonato it needs further interface adjustments from db (?). The logs are still there and this will help with what's missing. I can help with the setup (of the external with the PR)

**Comment by smuzaffar** [comment]
@ggovi, can you please provide a fix for boost 1.72 here?

**Comment by ggovi** [comment]
@smuzaffar 
can you please provide a recipe to reproduce the issue?

**Comment by smuzaffar** [comment]
@ggovi , you can run do something like this on cmsdev machines
```
git clone --depth 1 https://github.com/cms-sw/cms-bot
./cms-bot/test-prs.sh cms-sw/cmsdist#5387
cd CMSSW_11_*
cmsenv
scram build -j 8
```
This might take few hours as it will rebuild boost and all externals which depend on boost.

**Comment by mrodozov** [comment]
closing this, it is fixed in more recent PR

**Pull request closed without merging**
