### PR TITLE
Bug fix hector

### PR DESCRIPTION
**Pull request by mundim**
#### PR description:

This is a bug fix for the PPSProtonTransport, in the propagationg using Hector, which was causing all positive pz to be rotated to the negative side.

All the tests (code-checks, code-formats, runtests and runTheMatrix) have been done again with no problem at all.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mundim** [comment]
Trying to understand the code-format problem: I ran the command before 'git add' to the new branch. Sorry...

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
