### PR TITLE
Adding tune-dependent pthat reweighting of Pythia

### PR DESCRIPTION
**Pull request by zleba**
Backport for 10_2_X of the PR https://github.com/cms-sw/cmssw/pull/24179

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
backport #24179

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
@zleba as far as I understand none of the modifications are used in the tests. I just want to make sure you have tested that in this branch.

**Comment by ahinzmann** [comment]
Hi, let me clarify the aim of this PR. As explained in PPDC, we need this for JME MC samples in the Fall18 part1 campaign (QCD_Pt-15to7000_TuneCP5_Flat2018_13TeV_pythia8).
Once this PR is integrated, could a new release for the Fall18 GEN step be made?

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
