### PR TITLE
Changing DCS Filter Application in SiStripClusterMonitor 

### PR DESCRIPTION
**Pull request by ocolegro**
Hello,

This is work that was requested by Francesco Fiori in order to help with the DQM pipeline. This code is implemented to remove the DCS Filter in the SiStripClusterMonitor from a specific cluster trend plot.

Thank you,
Owen

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by ocolegro** [comment]
Hi, I was asked to add a description -

This is work that was requested by Francesco Fiori in order to help with the DQM pipeline.  This code is implemented to remove the DCS Filter in the SiStripClusterMonitor from a specific cluster trend plot.

Thank you,
Owen

**Comment by ocolegro** [comment]
@dmitrijus I do not believe that our PR is responsible for this error, can we please restart the tests?

Thank you

**Comment by jfernan2** [comment]
Hi @ocolegro I'm restarting the test but can you please introduce yourself in order to add you to the list of DQM developers?
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by davidlange6** [comment]
code-checks

**Comment by boudoul** [comment]
hi @ocolegro , the changes in your PR is not compiling, please test first , compile, and provide a fix. Thanks

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
This change is causing segmentation faults in workflows 140.52, 140.54 and 140.51

**Comment by Dr15Jones** [comment]
please test workflow 140.52, 140.54

**Comment by fabiocos** [comment]
@Dr15Jones yes, I have opened an issue #21858

**Pull request merged**
