### PR TITLE
updated the string for MinBias dataset

### PR DESCRIPTION
**Pull request by jnsandhya**
Hi, 
Following the request in : 
https://github.com/cms-sw/cmssw/pull/22968#issuecomment-383095246
Phase 2 GS string has been updated. 

Thanks
Sandhya

### CODE REVIEW

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
@cmsbuild, please test workflow 20261.98

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
