### PR TITLE
Payload generator 7 5 x

### PR DESCRIPTION
**Pull request by andrewj314**
Backporting Pavel's SQlite payload generator tool to 7_5_X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10067	 80daadc
- based on visual code inspection, the changes are the same as in https://github.com/cms-sw/cmssw/pull/9945	cf2e034
- from #9945 signoff: event processing workflows are not affected, confirmed by jenkins (no differences in comparisons)

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
