### PR TITLE
Phase2-hgx273 Zeroth Step for going to V15 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Zeroth Step for going to V15 geometry of HGCal

#### PR validation:

Tested using the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
