### PR TITLE
OS requirement for Triple Muon seeds in the uGT emulator

### PR DESCRIPTION
**Pull request by elfontan**
This PR contains a fix in the correlation class to handle the three-body conditions in order to include the possibility to read the OS requirement for TripleMu seeds with the three-muon invariant mass requirement.
Reference PR: https://github.com/cms-sw/cmssw/pull/33911.

Note that two backports of this PR followed the update of CMSSW_126X. The PR have been backported to the OSW as well. 
- 125X: https://github.com/cms-sw/cmssw/pull/40129
- 124X: https://github.com/cms-sw/cmssw/pull/40130
- OSW: https://github.com/cms-l1t-offline/cmssw/pull/1058

The preparation and online deployment of the new 124X release (CMSSW_12_4_11_patch2) for the last days of the 2022 data-taking have been requested: https://github.com/cms-sw/cmssw/issues/40137.

#### PR validation:
Two special menu have been created for the validation of the updates:
1) baseline [L1Menu_Collisions2022_v1_3_0](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/master/development/L1Menu_Collisions2022_v1_3_0/L1Menu_Collisions2022_v1_3_0.html) + two new seeds as copy of bits 82-83 with an additional OS requirement
2) a reduced menu containing only TauTo3Mu-type seeds with and without opposite sign requirement.
 
CMSSW release used for tests: _CMSSW_12_6_0_pre4_.

**L1Ntuples** have been created **re-emulating the uGT step** to take into account the new menu and the final countings have been checked in three scenarios:
- Default uGT emulator
- Updated uGT emulator adding the cut for all cases involving the three body invariant mass: same countings in default bits and new bits with the expected reduction by the removal of the three SS muon events causing the high rate.
- Updated uGT emulator adding the cut for cases involving the three body invariant mass with an OS requirement parsed from the xml menu: reduction as expected ONLY in the new seeds containing the OS requirement.

Final tests have been performed by producing **test vectors** based on the above mentioned L1 menu and checking the agreement of the firmware and emulator response. 
The run used for the test is 359661 (LS=43), that contains a few cases useful for the debug as pointed out in [CMSLITDPG-960](https://its.cern.ch/jira/browse/CMSLITDPG-960?focusedCommentId=4565477&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4565477):
`/store/data/Run2022E/EphemeralHLTPhysics0/RAW/v1/000/359/661/00000/355c33ec-6253-4590-bc11-94e0ce1b45be.root`.

### CODE REVIEW

**Comment by elfontan** [comment]
A backport to **CMSSW_12_5_X** and **CMSSW_12_4_X** would be needed.

Note that the possibility to deploy a new uGT firmware online next week with this minor change is under consideration. 
If this happens and in parallel a new CMSSW release is going to be built for next week, it would be nice to include this PR to check the impact on the DQM plots. If not possible, we will observe some mismatches in the DQM but we will know the reason.

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
please test 

(relvals timed out)

**Comment by cecilecaillol** [comment]
please test

(relvals timed out)

**Comment by cecilecaillol** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
