### PR TITLE
Phase2-hgx300 Fix the rotation angle of layers in V16 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix the rotation angle of layers in V16 geometry of HGCal

#### PR validation:

Tested using muon tomography

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Do we need the PR for D88 validation?
FYI @perrotta @qliphy

**Comment by bsunanda** [comment]
This is a bug fix for HGCal geometry in D86 and D88
________________________________

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

The change is on Phase2 D86 and D88 which should be expected from this bug fix PR. I assume the validation will be done with CMSSW_12_3_0_pre5. I'm not sure if any plot in the PR test can confirm the fix.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
