### PR TITLE
Add an MPI test program

### PR DESCRIPTION
**Pull request by AliinCern**
#### PR description:

Add a program to test multiple MPI functions: blocking and non-blocking scatter/gather and send/receive.

#### PR validation:

Tested by running `scram b runtests` under HeterogeneousCore/MPICore/test :
```
Package HeterogeneousCore/MPICore: Running test testMPI
 
===== Test "testMPI" ====

        Number of Processes 4
        Number of workSplit First 33
        Number of workSplit Second 1

                Non-Blocking Scatter 

Scattreing Time [0] = 0.131422 ms
Gathering Time [0] = 1.126110 ms

                Blocking Scatter 

Scattreing Time [0] = 0.006184 ms
Gathering Time [0] = 0.007051 ms

                Non-Blocking Send and Receive 

Time Sending Root = 0.055584 ms
Time Receiving Root = 0.019318 ms

                Blocking Send and Receive 

Time Sending Root = 0.004007 ms
Time Receiving Root = 0.006430 ms

                Non-Blocking Send and Receive with Multiple Tasks

Time Sending Root = 0.011206 ms
Time Receiving Root = 0.002526 ms


        ===================================================
        ||      ||  Scatter/Send   ||   Gather/Receive   ||
        ===================================================
        ||  1   ||     0.131422    ||        1.126110     ||
        ---------------------------------------------------
        ||  2   ||     0.006184    ||        0.007051     ||
        ---------------------------------------------------
        ||  3   ||     0.055584    ||        0.019318     ||
        ---------------------------------------------------
        ||  4   ||     0.004007    ||        0.006430     ||
        ---------------------------------------------------
        ||  5   ||     0.011206    ||        0.002526     ||
        ===================================================


---> test testMPI succeeded
TestTime:1
^^^^ End Test testMPI ^^^^
>> Tests for package HeterogeneousCore/MPICore ran.
```

### CODE REVIEW

**Comment by fwyzard** [comment]
@AliinCern can you apply the changes suggested by the bot, please ?

Either use the patch provided by the both, with
```
curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35450/25607/code-format.patch | patch -p1
```
or rerun the checks locally:
```
scram b code-checks
scram b code-format
```

Then:
  - commit the changes
  - squash the history into a single commit
  - force-push the update to the same branch  `mpitest`

**Review by fwyzard — CHANGES_REQUESTED** [review]
this is the first round of review comments, please address them, rerun the `code-checks` and `code-format`, and push the updates

**Comment by fwyzard** [comment]
in the meantime, @smuzaffar @makortel we will need the `HeterogeneousCore/MPICore` package for other changes as well (see for example #32632); could you create it and assign to the `heterogeneous` L2 ?

**Comment by smuzaffar** [comment]
@fwyzard , it is already there https://github.com/cms-sw/cms-bot/blob/master/categories_map.py#L852

**Comment by fwyzard** [comment]
> @fwyzard , it is already there https://github.com/cms-sw/cms-bot/blob/master/categories_map.py#L852

ah, thanks !

**Comment by fwyzard** [comment]
@AliinCern to make the measurements more reliable, can you change the code so that it repeats multiple times
  - sending the data to the workers
  - doing the sum on the workers
  - sending back the results

and then takes the average of the measurements ?

Please make the number of repetitions configurable, like the size of the vectors.

**Review by fwyzard — CHANGES_REQUESTED** [review]
If I read the code correctly, the current implementation will run each function exactly 5 times, and take the average of the time.
Can you make the number of time each function is run configurable ?

So that
```bash
./testMPI 1000000 100 12345
```
will run all 5 functions 100 times over 1000000 elements ?

**Pull request merged**
