### PR TITLE
Cmssw 7 1 x sherpa22

### PR DESCRIPTION
**Pull request by thuer**
Backport of the changes for the SherpaInterface done in 81X

### CODE REVIEW

**Comment by thuer** [comment]
I forgot to mention that it should go with https://github.com/cms-sw/cmsdist/pull/2251

**Comment by covarell** [comment]
please test with cms-sw/cmsdist#2251

**Comment by thuer** [comment]
I thought @bendavid  changes to the GenLumiInfoHeader were also backported (I checked the wrong release). Is there any plan to do so? Otherwise we need to find another place to store the names of the weights

**Comment by covarell** [comment]
The PR is already merged, I will retry the test in a few days:
https://github.com/cms-sw/cmssw/pull/14005#issuecomment-207895991

**Comment by thuer** [comment]
I guess you linked the wrong PR, I was refereing to the one introducing the GenLumiInfoHeader class to GenSimDataFormats

**Comment by covarell** [comment]
Yes, sorry, https://github.com/cms-sw/cmssw/pull/13684

**Comment by thuer** [comment]
They values of the weights are stored anyway, just the strings corresponding to their names were not stored up to now. 
We could remove the saving of the strings and hope that the users know which systematic variations are which (if it is only a few samples I guess this is doable) or I can store the strings in GenRunInfoProduct (need to change that for this, we had this in the original pull request #13230)
I assume only few samples will be produced with 71X I can live with both options

**Comment by covarell** [comment]
Ok the string removal would be the easiest solution in my opinion, since indeed very few samples should be concerned.
@pgunnell @vciulli please read full thread and comment if this workaround is OK for you

**Comment by pgunnell** [comment]
To me, the solution of string removal looks a good idea..thanks a lot for the PR.

**Comment by vciulli** [comment]
Hi, it’s fine to me too.
It should not be too difficult to figure out the order of the weights if needed.

**Comment by thuer** [comment]
please test with cms-sw/cmsdist#2251

**Comment by covarell** [comment]
please test with cms-sw/cmsdist#2251

**Comment by pgunnell** [comment]
Dear all, any update on this?

**Comment by covarell** [comment]
It is merged, so it will be in the next 71X release

**Comment by pgunnell** [comment]
Great! thanks a lot Roberto!

**Pull request merged**
