### PR TITLE
Run3-gex112 Correction to some of the Forward detector SD's for the dd4hep scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correction to some of the Forward detector SD's for the dd4hep scenarios

#### PR validation:

Tested for the new Run3 scenarios

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please Test

**Comment by civanch** [comment]
@bsunanda , here fast sim unit test fails, other tests are fine. what can be done for FastSim?

**Comment by bsunanda** [comment]
@civanch I think that the failure has nothing to do with this PR. this PR addresses only some BRIL detectors and I doubt FastSim even has some.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
