### PR TITLE
Fixed DQM bin by bin tool to upload all produced files to GUI

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Occasionally some root files produced during the comparison wouldn't get uploaded to DQM GUI. This PR fixes that issue. 

#### PR validation:

Tool was validated locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Will make a backport of this as soon as #26929 is merged.

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
