### PR TITLE
[SIMULATION] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Updated unit tests so that they can be run from their own separate directory. Mostly 
- convert `<bin ...>` to `<test....>`
- use the cwd to run tests. New build rules will create a separate directory for each test

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
+1

**Pull request merged**
