### PR TITLE
Calo L1 last20Mismatches Axis Fix Forward Port

### PR DESCRIPTION
**Pull request by aloeliger**
#### PR description:

This PR modifies the function of the last20Mismatches monitoring element to not include duplicate event mismatch reports on the Y-axis, instead just updating the types of mismatches seen for a given combination of Run, Lumi, and Event. As well, empty Y-axis labels are now simply given their corresponding bin number, to prevent empty string labels causing issues as seen before in #32250. This PR fixes the issue first spotted on this hypernews thread: https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2192.html

#### PR validation:

All code compiles, and produces expected plots as seen when using `runTheMatrix.py`. Using @silviodonato 's method to test the DQM merging step, this code eliminates the merging error seen.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a forward port to the master branch / 11_3_X of #32815. It was created by `git cherry-pick` -ing the three relevant commits on top of the current state of the master branch. This fix needs to be ported to be available in future production instances of CaloL1 DQM code.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
Backport #32815 already merged at the commit a48ba55dd39f79c70c0ae60350a13d292c789c87 ( fbad4f6ce99cbb3b04bef92e11f9dd071f0b65a9 )

**Comment by aloeliger** [comment]
@silviodonato I think I have located the issue, a missing "&" (apologies it took me some time to understand and locate this), and the 25202.o workflow plots look fixed in my test. Is there still in time to add this commit into 11_2_X and the MWGR?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
> @silviodonato I think I have located the issue, a missing "&" (apologies it took me some time to understand and locate this), and the 25202.o workflow plots look fixed in my test. Is there still in time to add this commit into 11_2_X and the MWGR?

We can add the fix in 11_2_X at Online DQM at P5 for the GUI used by the shifters, as long as we have a PR, but I understand the fix affects mainly Offline for Tier0

**Comment by aloeliger** [comment]
> > @silviodonato I think I have located the issue, a missing "&" (apologies it took me some time to understand and locate this), and the 25202.o workflow plots look fixed in my test. Is there still in time to add this commit into 11_2_X and the MWGR?
> 
> We can add the fix in 11_2_X at Online DQM at P5 for the GUI used by the shifters, as long as we have a PR, but I understand the fix affects mainly Offline for Tier0

@jfernan2, should I open up a new pull request to 11_2_X with this latest commit?

**Comment by jfernan2** [comment]
> should I open up a new pull request to 11_2_X with this latest commit?
Yes please

**Comment by aloeliger** [comment]
Okay, I have opened a new PR to CMSSW_11_2_X with this fix as well.

**Comment by silviodonato** [comment]
@aloeliger 
in  wf136.731 there are still some differences

before
image
https://tinyurl.com/y3623lfz

and after

image
https://tinyurl.com/y5jvovou

**Comment by aloeliger** [comment]
> @aloeliger
> in wf136.731 there are still some differences
> 
> before
> image
> https://tinyurl.com/y3623lfz
> 
> and after
> 
> image
> https://tinyurl.com/y5jvovou

This difference seems to be what was expected. 

I have removed duplicate events (and therefore labels) from the Y-axis. The PR version does not have duplicate events shown on the Y-axis, instead only reporting each one once, alongside all types of mismatches seen, instead of reporting every mismatch individually.

The current version shows multiple copies of Run 274199, Lumi 21, Event 39733340, alongside multiple reports of the same kind of mismatch.

Comparing between the two, it does not seem like the current PR version of this monitoring element has missed any kinds of mismatches (the previous problem seen on 25202.0), nor does it seem to be reporting mismatches that were not seen.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
