### PR TITLE
add template classes for BeamSpot PaylaodInspector (vs run,time,history)

### PR DESCRIPTION
**Pull request by mmusich**
title says it all.
FYI @mtosi @sarafiorendi @francescobrivio

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@mmusich I see an obsolete architecture used in the test script, but this looks irrelevant because of the subsequent choice made by scram, so I would say it is ok (and indeed it runs in master smoothly for what I may see)

**Comment by fabiocos** [comment]
+1

**Comment by mmusich** [comment]
> @mmusich I see an obsolete architecture used in the test script, but this looks irrelevant because of the subsequent choice made by scram, so I would say it is ok (and indeed it runs in master smoothly for what I may see)

@fabiocos, thanks for the comment. It's actually a copy paste from other similar scripts. I will fix everything consistently in all the scripts.

**Pull request merged**
