### PR TITLE
Remove TestBPHSpecificDecay test

### LINKED ISSUE #45410: [UBSAN] array subscript ... is partly outside array bounds in HeavyFlavorAnalysis/SpecificDecay
In UBSAN IBs, the following [warnings](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_1_UBSAN_X_2024-07-08-2300/HeavyFlavorAnalysis/SpecificDecay) are emitted:

```
>> Compiling edm plugin src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc
(...)
In file included from src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHDecayToResTrkBuilderBase.h:16,
                 from src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHDecayToResTrkBuilder.h:16,
                 from src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHBuToJPsiKBuilder.h:15,
                 from src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:15:
In constructor 'BPHDecaySpecificBuilder<ProdType>::BPHDecaySpecificBuilder() [with ProdType = BPHRecoCandidate]',
    inlined from 'BPHDecayToResResBuilder<ProdType, Res1Type, Res2Type>::BPHDecayToResResBuilder(const std::vector<typename ResType::const_pointer>&, const std::string&, const std::vector<typename Res2Type::const_pointer>&) [with ProdType = BPHRecoCandidate; Res1Type = BPHPlusMinusCandidate; Res2Type = BPHPlusMinusCandidate]' at src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHDecayToResResBuilder.h:76:36,
    inlined from 'BPHBsToJPsiPhiBuilder::BPHBsToJPsiPhiBuilder(const BPHEventSetupWrapper&, const std::vector<std::shared_ptr<const BPHPlusMinusCandidate> >&, const std::vector<std::shared_ptr<const BPHPlusMinusCandidate> >&)' at src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHBsToJPsiPhiBuilder.h:51:69,
    inlined from 'virtual void TestBPHSpecificDecay::analyze(const edm::Event&, const edm::EventSetup&)' at src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:399:74:
  src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHDecaySpecificBuilder.h:49:29: warning: array subscript 'BPHDecayGenericBuilder<BPHRecoCandidate>[3]' is partly outside array bounds of 'unsigned char [304]' [-Warray-bounds]
    49 |   BPHDecaySpecificBuilder() {}
      |                             ^
src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc: In member function 'virtual void TestBPHSpecificDecay::analyze(const edm::Event&, const edm::EventSetup&)':
src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:399:74: note: at offset 272 into object of size 304 allocated by 'operator new'
  399 |     BPHBsToJPsiPhiBuilder* bs = new BPHBsToJPsiPhiBuilder(ew, lJPsi, lPkk);
      |                                                                          ^
In file included from src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHBsToJPsiPhiBuilder.h:15,
                 from src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:16:
In constructor 'BPHDecayToResResBuilder<ProdType, Res1Type, Res2Type>::BPHDecayToResResBuilder(const std::vector<typename ResType::const_pointer>&, const std::string&, const std::vector<typename Res2Type::const_pointer>&) [with ProdType = BPHRecoCandidate; Res1Type = BPHPlusMinusCandidate; Res2Type = BPHPlusMinusCandidate]',
    inlined from 'BPHBsToJPsiPhiBuilder::BPHBsToJPsiPhiBuilder(const BPHEventSetupWrapper&, const std::vector<std::shared_ptr<const BPHPlusMinusCandidate> >&, const std::vector<std::shared_ptr<const BPHPlusMinusCandidate> >&)' at src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHBsToJPsiPhiBuilder.h:51:69,
    inlined from 'virtual void TestBPHSpecificDecay::analyze(const edm::Event&, const edm::EventSetup&)' at src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:399:74:
  src/HeavyFlavorAnalysis/SpecificDecay/interface/BPHDecayToResResBuilder.h:76:36: warning: array subscript 'BPHDecayGenericBuilder<BPHRecoCandidate>[3]' is partly outside array bounds of 'unsigned char [304]' [-Warray-bounds]
    76 |         sCollection(&res2Collection) {}
      |                                    ^
src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc: In member function 'virtual void TestBPHSpecificDecay::analyze(const edm::Event&, const edm::EventSetup&)':
src/HeavyFlavorAnalysis/SpecificDecay/test/stubs/TestBPHSpecificDecay.cc:399:74: note: at offset 272 into object of size 304 allocated by 'operator new'
  399 |     BPHBsToJPsiPhiBuilder* bs = new BPHBsToJPsiPhiBuilder(ew, lJPsi, lPkk);
      |                                                           
```

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

This PR removes a test file since it's giving issues in UBSAN + it's actually tested in DQM, i.e. it's a dupplicate.
See more in https://github.com/cms-sw/cmssw/issues/45410

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport needed

Resolves https://github.com/cms-sw/cmssw/issues/45410

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@elusian @ronchese FYI

**Comment by tvami** [comment]
> @elusian @ronchese FYI

I'll give folks a few days to raise objection before signing.

**Comment by elusian** [comment]
I'm mostly a user for this code, I'll leave @ronchese to comment here.
Just to understand, is BPHWriteSpecificDecay itself (and thus the DQM sequence) affected?

**Comment by tvami** [comment]
>  is BPHWriteSpecificDecay itself (and thus the DQM sequence) affected?

no that seems to be fine

**Comment by tvami** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
