### PR TITLE
including ctpps in DQMOffline standard conf

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

Change of DQM configuration in order to have (CT)PPS properly configured also for Offline plots. 

#### PR validation:

Tested on data with runTheMatrix on workflows 136.867 (2018) and 136.801 (2017)

@forthommel @jfernan2

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@fabferro please do not forget the backport. Thanks!

**Comment by fabferro** [comment]
Changes done by #27571 are embedded here. #27571 might probably be closed.

**Comment by fabferro** [comment]
The tests failing are Run1 MC. Crash due to missing CTPPS geometry record in the GT. No CTPPS during run 1, so that's normal. How can we prevent these "normal" crashes??

**Comment by fioriNTU** [comment]
please test

**Comment by fioriNTU** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
