### PR TITLE
Added single module occupancy plots for on track digis and charge Vs size plots (on track) per layer/disk

### PR DESCRIPTION
**Pull request by akhatiwa**
Added single module occupancy plots for on track digis and charge Vs size plots (on track) per layer/disk

### CODE REVIEW

**Comment by dmitrijus** [comment]
Please introduce yourself (you are the first time contributor). And send an email to DQM core, so we can properly put/assign you somewhere in this list, https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts

**Comment by fioriNTU** [comment]
@akhatiwa please change also the title to this PR to be more descriptive. Thanks!

**Comment by akhatiwa** [comment]
Hi @dmitrijus, Thanks. I sent an email to the DQM core. I am Ajeeta Khatiwada from Purdue University currently working on Pixel DQM. My CERN user id is akhatiwa, email address is ajeeta.khatiwada@cern.ch.

**Comment by fioriNTU** [comment]
@akhatiwa I see you submitted this PR in 9_2_X, you have to do the same in 9_3_X starting from a recent IB. Please do it asap.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
