### PR TITLE
PF tracks to HF extrapolation for Phase2 (and suppress unnecessary warnings)

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

Suppress unnecessary warning for tracks with |eta|>3 not extrapolated to ECAL and HCAL which happens in the phase2 scenarios. Also, update PFTrackTransformer to allow extrapolation of tracks to HF.

#### PR validation:

Compiles. Matrix tests run. Also made sure no change to reco as we are not using extrapolated tracks to HF yet. This is a step 1.
http://hep.baylor.edu/hatake/PFval/val_10_6_0_FwdTrkExtrapolation/

#### if this PR is a backport please specify the original PR:

This is not backport.

@bendavid

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by hatakeyamak** [comment]
Trying to apply patch, but I am getting:
curl -k https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-27123/10252/code-checks.patch  | patch -p1
patch: **** Only garbage was found in the patch input.

I also tried:
scram build code-checks
but doesn't seem to update files.

Any advice?

**Comment by slava77** [comment]
there is a merge conflict here now.
Please rebase.

**Comment by slava77** [comment]
> there is a merge conflict here now.
> Please rebase.

I think this is also the reason for "corrupted" codechecks

**Comment by hatakeyamak** [comment]
This is not ready for further tests yet.

**Comment by slava77** [comment]
On 6/6/19 9:05 AM, Kenichi Hatakeyama wrote:
> This is not ready for further tests yet.
> 

if there is a lot of work still to be done, please close and reopen when
it is ready.
Thank you.

**Pull request closed without merging**
