### PR TITLE
Modernized ES modules in Geometry/MTDNumberingBuilder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- All EventSetup modules now use consumes
- Cleaned up the code in the modules and their helpers
- Merged EventSetup modules headers and source files

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
associated with #26584

**Comment by makortel** [comment]
Related to this package, I noticed an EDAnalyzer defined in
https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDNumberingBuilder/bin/stubs/GeometricTimingDetLoader.h
The placemeng in `bin` is rather weird. The module seems be unused within CMSSW.

**Comment by Dr15Jones** [comment]
Having a module in `bin` is weird. Definitely something for the maintainers to look at.

**Comment by kpedro88** [comment]
This was copied from https://github.com/cms-sw/cmssw/tree/master/Geometry/TrackerNumberingBuilder/bin/stubs, so it has been around since 2007.

**Comment by fabiocos** [comment]
The MTD reconstruction geometry is slightly more than a clone of the Tracker one...

**Comment by fabiocos** [comment]
... of course this does not mean it should not be cleaned

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
