### PR TITLE
3prong1pi0 new dms

### PR DESCRIPTION
**Pull request by andrewj314**
Adding 3prong1pi0 decay mode to new tau ID DMs

### CODE REVIEW

**Comment by slava77** [comment]
Hi AJ,
the 76X is now closed to new features.

Please clarify in more details the performance gains and plan to discuss needs for a new feature exception with PPD, especially if this affects the mainstream monitored discriminants.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by andrewj314** [comment]
Hi Slava,

This was my fault - this PR should have been made a few weeks ago, but I made a mistake and only integrated it into the tau POG repo and neglected to make a PR to merge it into CMSSW. So sorry about that.

It's a simple change - it just adds a 3prong+1pi0 decay mode to  RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByHPSSelection_cfi.py

with a mass window cut of 0.9<m<1.6 - I don't expect it to affect the mainstream monitored discriminants.

Again, this was my fault and I apologize for the delay.

**Comment by cvuosalo** [comment]
@andrewj314:
This change causes very widespread changes to tau quantities. Since you say that you "don't expect it to affect the mainstream monitored discriminants", I think something may be wrong. The changes, though widespread, are small and usually insignificant, but since they are so extensive, it's hard to be sure some quantities aren't being changed in a major way. I'm running an extended test to get better plots, but you can already see some of the changes in the Jenkins results:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-10-12-1100+11766/10588/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-10-12-1100+11766/10588/alternative-comparisons/

**Comment by andrewj314** [comment]
Please find an explanation from Christian Veelken addressing this:
-----------------------------------------------------------------------------------------
I had a look at the plots in
        https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-10-12-1100+11766/10588/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/
and for me they look good. What is see is that almost all distributions change, but by a very small amount only.

From slide 4 of Alex' presentation
        https://indico.cern.ch/event/444476/contribution/2/attachments/1153863/1657642/nehrkorn_2015_09_14.pdf
we expect two effects:
- additional taus are reconstructed and pass the decayModeFindingNewDMs discriminator (the extra 3prong1pi0 taus appear in the top row of Alex' plots)
- some taus migrate into a different decay mode (also the bin contents  of bins outside the top row change somewhat)
        This migration means that also tau pT, eta, etc variables may change by a small amount

What we mean by minor changes is that the tau ID performance is not expected to change by adding the 3prong1pi0 taus.
Due to the migration, however, individual distributions may change a bit (the black and red histograms in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-10-12-1100+11766/10588/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/ correspond to the same tau ID performance, even though the distributions are different by a bit).
--------------------------------------------------------------------------------------------------------------------

**Comment by cvuosalo** [comment]
+1

For #11766 c7fc22e6ddb61a56c4ebcaf044ae7babf2271283

Adding 3prong1pi0 decay mode to new tau ID decay modes.

The code changes are satisfactory. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11766/8794/summary.html) against baseline CMSSW_7_6_X_2015-10-12-1100 show extensive but small differences in tau quantities. These minor differences are expected, as discussed above. An extended test of workflow 202.0_TTbar with 70 events against baseline CMSSW_7_6_0_pre7 also shows extensive but small differences in tau quantities, with some examples shown below. Product size and processing time show no significant change with this PR.
dmiso
dmvspt
dmptallhad

**Comment by davidlange6** [comment]
+1

**Pull request merged**
