### PR TITLE
 [CMSSW_13_3_X Backport] Add superclusterEta of photon in NanoAOD

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:
Same as PR https://github.com/cms-sw/cmssw/pull/43198

#### PR validation:

runTheMatrix tests have been successfully run for the following workflow :
- runTheMatrix.py -l 12434.0

#### Backport
This PR is a backport of PR  https://github.com/cms-sw/cmssw/pull/43198
The addition of this photon variable is needed to be backported to CMSSW_13_3_X.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
