### PR TITLE
Propagate timing to PF TICL Candiates (ROOT622)

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR sets meaningful timing values for PF TICL Candidates.
A validation of the timing error for both MTD and HGCal is ongoing, hence the default value of the switch to compute the timing weighted average is currently set to false.
Study reported [here](https://docs.google.com/presentation/d/12r0rc-P2xNEAipo1jD_KZw53uVKH0NyKNHsgpzcWe24/edit?usp=sharing).

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by slava77** [comment]
how is this different from #32046 ?

it's pointing to the same 11_2_X milestone

**Comment by slava77** [comment]
@smuzaffar 
are we having some issues with web hooks or with jenkins job scheduling?
This PR did not have a code-checks since submission about 2 hours ago.

**Comment by smuzaffar** [comment]
@slava77,  this PR contains commits which github thinks that already have tests passed  ( see the github checks status at the end of the PR). May be this is a new PR based on some othe rPR which we closed. I am explicitly going to start the code check for this now

**Comment by smuzaffar** [comment]
code-checks

**Comment by slava77** [comment]
> @slava77, this PR contains commits which github thinks that already have tests passed ( see the github checks status at the end of the PR). May be this is a new PR based on some othe rPR which we closed. I am explicitly going to start the code check for this now

ah, I didn't realize that it's checking at the commit level.
I think then this goes back to my earlier question https://github.com/cms-sw/cmssw/pull/32175#issuecomment-729744668
from the title I'm guessing that the PR was meant for some other branch of root or perhaps was submitted in error

**Comment by lecriste** [comment]
> I think then this goes back to my earlier question [#32175 (comment)](https://github.com/cms-sw/cmssw/pull/32175#issuecomment-729744668)
> from the title I'm guessing that the PR was meant for some other branch of root or perhaps was submitted in error

@slava77, I pushed this PR branch from `CMSSW_11_2_ROOT622_X_2020-11-18-1100`, which I think it's the IB that @smuzaffar is referring to in https://github.com/cms-sw/cmssw/pull/32046#issuecomment-729462514

Is this enough to make the comparison job run with that ROOT version?

**Comment by slava77** [comment]
> @slava77, I pushed this PR branch from `CMSSW_11_2_ROOT622_X_2020-11-18-1100`, which I think it's the IB that @smuzaffar is referring to in [#32046 (comment)](https://github.com/cms-sw/cmssw/pull/32046#issuecomment-729462514)
> 
> Is this enough to make the comparison job run with that ROOT version?

I see; there is no separate cms-sw/cmssw branch for ROOT622_X, if that other version was needed for a test than it would be managed with "please test for CMSSW_11_2_ROOT622_X".

Anyways, CMSSW_11_2_X_2020-11-18-1100 with rolled-back variant of ROOT is out and I think that we can go back to #32046  and close this PR.

**Comment by perrotta** [comment]
-1
- Unnneeded duplicate of #32046

**Pull request closed without merging**
