### PR TITLE
Fix includes in RecoEcal/EgammaClusterProducers

### PR DESCRIPTION
**Pull request by Teemperor**
This patch makes the headers parsable on their own by adding
the necessary includes to resolve all referenced types.

It adds an include to:
* SuperClusterFwd.h for the class SuperClusterCollection
* Point3D.h for the class math::XZYPoint
* EcalRecHitCollections.h for the class EcalRecHitCollection
* BasicClusterFwd.h for the class BasicClusterCollection

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19364	ae4074b
- technical
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
