### PR TITLE
 New_samples (TTbarLepton_14 and QQH1352T_14) added

### PR DESCRIPTION
**Pull request by sharmaaash**
#### PR description:

 There are some trigger paths which are not available with enough events. An example: like TTbar sample does not have genuine photons so Higgs to diphoton samples might be useful. Following the past strategy with all four samples to be available now for HLT validation. Please follow additional inoformation in this Jira. 
**https://its.cern.ch/jira/browse/PDMVRELVALS-115**  

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by agrohsje** [comment]
What is the motivation for the mass choices, the usage of old tunes, the different printout of events?  What is the purpose of the PR?

**Comment by sharmaaash** [comment]
> What is the motivation for the mass choices, the usage of old tunes, the different printout of events? What is the purpose of the PR?

There are some trigger paths which are not available with enough events. An example: like TTbar sample does not have genuine photons so Higgs to diphoton samples might be useful. So following the past strategy with all four samples to be available now for HLT validation.

**Comment by chayanit** [comment]
> > What is the motivation for the mass choices, the usage of old tunes, the different printout of events? What is the purpose of the PR?
> 
> There are some trigger paths which are not available with enough events. An example: like TTbar sample does not have genuine photons so Higgs to diphoton samples might be useful. So following the past strategy with all four samples to be available now for HLT validation.

I think the questions from GEN are more about the setup in generator level of these samples are outdated and why you need the outdated setup to be produced.

**Comment by silviodonato** [comment]
@sharmaaash please fill the PR description above

**Comment by sharmaaash** [comment]
> @sharmaaash please fill the PR description above

Done.

**Comment by chayanit** [comment]
> > > What is the motivation for the mass choices, the usage of old tunes, the different printout of events? What is the purpose of the PR?
> > 
> > 
> > There are some trigger paths which are not available with enough events. An example: like TTbar sample does not have genuine photons so Higgs to diphoton samples might be useful. So following the past strategy with all four samples to be available now for HLT validation.
> 
> I think the questions from GEN are more about the setup in generator level of these samples are outdated and why you need the outdated setup to be produced. https://github.com/sharmaaash

Please clarify otherwise we can't sign this PR @sharmaaash

**Comment by srimanob** [comment]
Hi @chayanit @agrohsje @shane-breeze 

Would it be easier to clarify from GEN and PdmV on which Tune should be used? I assume no matter much for validation. And @sharmaaash clarify on the motivation of mass?

**Comment by sharmaaash** [comment]
> Hi @chayanit @agrohsje @shane-breeze
> 
> Would it be easier to clarify from GEN and PdmV on which Tune should be used? I assume no matter much for validation. And @sharmaaash clarify on the motivation of mass?

Hi, I am using same mass which was used earlier for validation of these samples. If it is needed to change from old values then let me know.

**Comment by chayanit** [comment]
> > Hi @chayanit @agrohsje @shane-breeze
> > Would it be easier to clarify from GEN and PdmV on which Tune should be used? I assume no matter much for validation. And @sharmaaash clarify on the motivation of mass?
> 
> Hi, I am using same mass which was used earlier for validation of these samples.

@sharmaaash do you still want to keep Higgs mass at 135 GeV? The Tuning should be updated to TuneCP5 for example https://github.com/cms-sw/cmssw/blob/8ee645cf66cc6b32e707fe6d1d95573f47cd7aba/Configuration/Generator/python/H125GGgluonfusion_14TeV_TuneCP5_cfi.py 

Anything else? @agrohsje

**Comment by agrohsje** [comment]
Right. I would just clean-up a bit. Nothing dramatic. 
Use 125 GeV for the Higgs, 172.5 for mtop, CP5, pylistverbostiy can be 0 for both, I think there is no need to print 3 events for Higgs,...

**Comment by sharmaaash** [comment]
Closing this and creating new PR with relevant changes.

**Pull request closed without merging**
