### PR TITLE
Miscellaneous fixes for HLT online DQM 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR bundles together a couple of fixes for the HLT online DQM:
   * I noticed looking at the [Pixel residuals @HLT plots](https://cmsweb.cern.ch/dqm/online/start?runnr=386554;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=HLT/Pixel/Tracks/PXBarrel;focus=;zoom=no;) in recent runs that they were empty. Looking at the [dqm-square log](https://cmsweb.cern.ch/dqm/dqm-square/api?what=get_logs&id=dqm-source-state-run386554-hostdqmfu-c2b03-45-01-pid2856735&db=production) for that run, I also saw a bunch of errors of the type:
   ```
   %MSG-w TrackProducerBase:  TrackRefitter:hltrefittedForPixelDQM  03-Oct-2024 22:56:25 CEST Run: 386554 Event: 2607599
 BeamSpot is not valid
%MSG
%MSG-e TrackRefitter:  TrackRefitter:hltrefittedForPixelDQM  03-Oct-2024 22:56:25 CEST Run: 386554 Event: 2607599
 BeamSpot is (0,0,0), it is probably because is not valid in the event
%MSG
   ```
   I believe the issue is that the current `hltrefittedForPixelDQM` instance clones the one used for offline (`refittedForPixelDQM`) which ultimately clones the template with the offline parameters:
   
   https://github.com/cms-sw/cmssw/blob/180e6a5c307a65a434208d7d55abda866eb9094e/RecoTracker/TrackProducer/python/TrackRefitter_cfi.py#L5
   
   * secondly, also looking at the [HLT quick collection](https://cmsweb.cern.ch/dqm/online/start?runnr=386554;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=Quick%20collection;focus=;zoom=no;) many of the plots are empty, I believe due the usage of deprecated trigger paths in input 
   
The two issues are addressed at 3bf61e34e8f99a0d8831549443f179e9b6c985e4 and 17e3bf7da1fad35f9fd58d073eebeebdc4f68349 respectively. 
   
#### PR validation:

None, will need to be tested via DQM replay

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, might backport to 14.1.x and 14.0.x for 2024 data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
playback kindly provided by @nothingface0 looks good.

Pixel residuals:

Screenshot from 2024-10-04 14-43-41

Object Monitor:

Screenshot from 2024-10-04 14-44-26

**Comment by mmusich** [comment]
+hlt 
   * DQM offline comparisons at https://github.com/cms-sw/cmssw/pull/46245#issuecomment-2393807589 look good
   * DQM online playback looks good (see https://github.com/cms-sw/cmssw/pull/46245#issuecomment-2393625771)

**Comment by antoniovagnerini** [comment]
+1
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
