### PR TITLE
Fix gcc9 warning GeneratorInterface/SherpaInterface

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes a warning in GeneratorInterface
#### PR validation:

Builds without the warning

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by alberto-sanchez** [comment]
+1

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
sorry about that but I had to remove comments :/

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
