### PR TITLE
remove all zero pt particles in constituent subtraction used for heavy ion events [94X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #22226

### CODE REVIEW

**Comment by kpedro88** [comment]
please test with cms-sw/cmsdist#3963

**Comment by kpedro88** [comment]
@mverwe @mandrenguyen is it a problem for HI if this PR is merged into 94X? (I don't think there is any planned use of 94X for HI, but not 100% sure.)

**Comment by kpedro88** [comment]
are we really going to require the collaboration to waste significant amounts on CPU over billions of events for the next N months just to preserve a frozen release for XeXe? This order of priorities will become increasingly unviable as data continue to increase faster than resources.

A few alternatives:
* branch off from the previous 94X release if/when there is a need from XeXe
* revert the change in the contrib that causes the regression in HI (I think it's orthogonal to the important ECF improvement)

**Comment by slava77** [comment]
On 4/27/18 3:21 PM, Kevin Pedro wrote:
> So the claim of a rapidly updatable analysis release is already
> disproven. Quelle surprise.
> 

rapid updates were promised only for 9_4_AN_X branch

**Comment by kpedro88** [comment]
So we want to repeat the current situation where we've been stuck with a rather inefficient 80X analysis release for *years*?

**Comment by slava77** [comment]
On 4/27/18 4:11 PM, Kevin Pedro wrote:
> So we want to repeat the current situation where we've been stuck with a
> rather inefficient 80X analysis release for /years/?
> 

I don't understand the comment.
please clarify

**Comment by kpedro88** [comment]
80X is still the approved analysis release for 2016 data.

Among other things, there is a significant inefficiency in the implementation of prefetching, to the extent that getting user floats for patjets takes as much CPU as running fastjet (usually the slowest module run by users). It is fixed in later CMSSW versions.

Now we are in almost the same situation - ECFAdder can be slower than fastjet without this update.

(There have also been ongoing hassles getting new features into 80X for analysis, so people gave up after a while. This makes the release less useful for analyzers and causes people to repeat work, possibly introducing errors. These implicit demands on collaborators due to poorly considered release policies cannot be ignored.)

When the resource board etc. complains about poor event throughput for analysis jobs, this should be remembered.

**Comment by kpedro88** [comment]
If @rappoccio can help me disentangle the different contrib updates between 1.026 and 1.033, this may be possible.

**Comment by slava77** [comment]
On 4/27/18 4:24 PM, Kevin Pedro wrote:
> 80X is still the approved analysis release for 2016 data.
> 
> Among other things, there is a significant inefficiency in the
> implementation of prefetching, to the extent that getting user floats
> for patjets takes as much CPU as running fastjet (usually the slowest
> module run by users). It is fixed in later CMSSW versions.
> 
> Now we are in almost the same situation - ECFAdder can be slower than
> fastjet without this update.
> 
> (There have also been ongoing hassles getting new features into 80X for
> analysis, so people gave up after a while. This makes the release less
> useful for analyzers and causes people to repeat work, possibly
> introducing errors. These implicit demands on collaborators due to
> poorly considered release policies cannot be ignored.)

They are not ignored.
The release policy allows to quickly put code in the CMSSW_9_4_AN_X
branch and make an analysis release.
This approach technically allows to have modifications that can even
render full RECO or SIM useless, because the AN release branch is meant
specifically for analysis needs.

Your update is currently proposed to the production 9_4_X branch and it
has different restrictions.


> 
> When the resource board etc. complains about poor event throughput for
> analysis jobs, this should be remembered.
>

**Comment by kpedro88** [comment]
I was under the impression that 9_4_AN_X would be forwarded into 9_4_X similar to 9_4_MAOD_X. Perhaps I was mistaken. If so, I retract the "claim... is already disproven" comment.

However, this particular issue is not completely resolved:
1. There is no dedicated cmsdist branch for 9_4_AN_X.
2. This particular change also impacts miniAOD production efficiency (i.e. the billions of 2016 events soon to be submitted). In that case it may be worthwhile to create a hybrid 1.026_ECF version of fastjet-contrib (will require a new branch in our external).

**Comment by mandrenguyen** [comment]
Both the pp reference data and the XeXe data were reconstructed with the pp reconstruction, meaning not running constituent subtraction.  If we want to reprocess the XeXe data, but this time including Cs jets, this PR would be required.   The UE event subtraction can also be done post-RECO.  Cs jets will not be used for the pp reference data.

**Comment by rappoccio** [comment]
Hi Folks

The contrib version is already in cvmfs, sonthe users who want to enable it can set that version in scram manually. It’s annoying, but at least possible.

Cheers
Sal

**Comment by slava77** [comment]
On 4/27/18 7:39 PM, Kevin Pedro wrote:
> I was under the impression that 9_4_AN_X would be forwarded into 9_4_X
> similar to 9_4_MAOD_X. Perhaps I was mistaken. If so, I retract the
> "claim... is already disproven" comment.
> 
> However, this particular issue is not completely resolved:
> 
>  1. There is no dedicated cmsdist branch for 9_4_AN_X.
>  2. This particular change also impacts miniAOD production efficiency
>     (i.e. the billions of 2016 events soon to be submitted). In that
>     case it may be worthwhile to create a hybrid 1.026_ECF version of
>     fastjet-contrib (will require a new branch in our external).
> 

Please clarify if this affects only 2016 in some way. (I think not).
We have the 2017 miniAOD already done.

Instead of trying to cut corners and ignore possible needs of other use
cases of 94X,
I suggest to focus on making an ECF-specific port of the fastjet.

**Comment by slava77** [comment]
On 4/28/18 5:25 AM, Matthew Nguyen wrote:
> Both the pp reference data and the XeXe data were reconstructed with the
> pp reconstruction, meaning not running constituent subtraction. If we
> want to reprocess the XeXe data, but this time including Cs jets, this
> PR would be required. The UE event subtraction can also be done
> post-RECO. Cs jets will not be used for the pp reference data.
> 

Thanks.
Please note that this PR should be considered an integral part of the
fastjet update proposed for 94X.
Please clarify if this PR (together with the fastjet update)  is
required for running CS jets in 94X.

**Comment by slava77** [comment]
On 4/28/18 6:28 AM, rappoccio wrote:
> Hi Folks
> 
> The contrib version is already in cvmfs, sonthe users who want to enable
> it can set that version in scram manually. It’s annoying, but at least
> possible.
> 
> Cheers
> Sal
> 

good point.
This will not work for the central production though.
I wouldn't worry much about it though, because the slower ECF is not
detrimental

**Comment by kpedro88** [comment]
The effect for miniAOD production is only in computational efficiency, not in physics. 2017 is already ~done, so only 2016 would be improved. To me this is still worthwhile.

Getting the later version from cvmfs also requires recompiling ~20 packages, which is suboptimal.

I've prepared a branch with the latest EnergyCorrelator on top of v1.026: https://github.com/cms-externals/fastjet-contrib/compare/cms/v1.026...kpedro88:cms/v1.026ECF

Can I submit this to our existing v1.026 external branch, or should we request a separate branch for it?

**Comment by rappoccio** [comment]
I suppose it won't matter if it is a new branch or the existing one, so perhaps for posterity we should make a new one?

**Comment by slava77** [comment]
Sadly, the CPU efficiency will decrease if we speedup ECF.

**Comment by mandrenguyen** [comment]
@slava77 
"Please clarify if this PR (together with the fastjet update) is required for running CS jets in 94X."
I believe they are coupled.  If we move to the new fastjet-contrib, then this PR is needed.  With the old version of fastjet-contrib, this PR is not needed. @mverwe Do you confirm?

**Comment by slava77** [comment]
> I've prepared a branch with the latest EnergyCorrelator on top of v1.026: cms-externals/fastjet-contrib@cms/v1.026...kpedro88:cms/v1.026ECF

given this focused solution, may I suggest to close this PR.

**Pull request closed without merging**
