### PR TITLE
Run3-alca197 Add a possible AlCa stream for IsoTrackFilter useful for MC productions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a possible AlCa stream for IsoTrackFilter useful for MC productions

#### PR validation:

Tested the new stream using Calibration/HcalAlcaResoProducers/test/AlCaIsoTrackFilterNoHLT_cfg.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
+1
* Add a AlCa stream for IsoTrackFilter (technical)

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1
- A new AlCa stream is made available for possible future usage

**Comment by tvami** [comment]
Hi @bsunanda can you please prepare a short talk to discuss the "possible future usage" of this AlCa stream at the next AlCa meeting (Monday, Aug 30)?

**Comment by bsunanda** [comment]
@tvami We are working on improving 2 AlCaReco streams. Hope we shall see some idea in a month's time. Can we make a presentation with our ideas in a months time? This one is relevant for some MC production for HCAL calibration. We can talk on that as well

**Comment by tvami** [comment]
Hi @bsunanda ok, I added you to the Sept 27 agenda with TBD (https://indico.cern.ch/event/1069948/#2-new-hcal-alca-streams-for-mc), we can come back to the details as this time is approaching.

**Pull request merged**
