### PR TITLE
76X hlt25ns round six

### PR DESCRIPTION
**Pull request by perrotta**
76X branch for the HLT updates integrated after 25ns frozen menu v4
It is based on CMSSW_7_6_X_2015-09-28-2300 and includes #11485

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@perrotta 
This now seems broken, also, why are strange pull requests/commits in this one?

**Comment by Martin-Grunewald** [comment]
@perrotta 
Did you change IB for subsequent commits to the branch?

**Comment by perrotta** [comment]
@Martin-Grunewald : I see. I will redo tomorrow based on latest 760pre6 or later

**Comment by Martin-Grunewald** [comment]
Part of the mess is the interplay of #11584 and #11609 (see there).
But it seems some paths would also have to be removed from FastSim...

**Comment by perrotta** [comment]
Yes, a few paths from the LowPU menu must be removed from fastsim.
Also this for tomorrow

**Comment by perrotta** [comment]
Rebased on CMSSW_7_6_X_2015-10-06-2300 + CMSSW_7_6_X as of now (it will be next  CMSSW_7_6_X_2015-10-07-1100).
Looking at FastSim issue now...

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_7_6_X_2015-10-07-1100 at the same time....

**Comment by lveldere** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_7_6_0_pre7

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
