### PR TITLE
constexpr for Hcal Calib and Cond 

### PR DESCRIPTION
**Pull request by vkhristenko**
adding constexpr to

- HcalCalibrations
- HcalRecoParam

only for these 2 in order to keep changes minimal for hcal reco at this point
https://github.com/cms-sw/cmssw/blob/master/RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc#L547
`reco_->reconstruct` needs only these 2, the rest sits in the `HBHEChannelInfo` that has been accomodated via https://github.com/cms-sw/cmssw/pull/23495

### CODE REVIEW

**Comment by vkhristenko** [comment]
fyi @fwyzard , @makortel

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by pohsun** [comment]
@vkhristenko Although there's no compilation error in the log, AFAIK, non-empty constructor with constexpr is supported since c++14. Do you know which c++ standard are we using? As a newbie in code review, I just want to learn more.

**Comment by fwyzard** [comment]
We are using c++17, with partial support in GCC 6.x and more full support
in GCC 7.x .

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Pull request merged**
