### PR TITLE
MTD code: add debugging statements, clean ETL validation for obsolete one-disk scenario

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR adds to the MTD digitization, reconstruction and validation classes a number of debugging messages, used in the investigation of the track-ETL hits matching efficiency. At the same time, the part of the validation classes that still allowed for a one-disk geometry, no more present in the release since a while, is removed.

#### PR validation:

Code compiles and run. Debugging statements have been actively used, but are not visible with the default ```MessageLogger``` settings. No impact on the physics output is expected.

### CODE REVIEW

**Comment by fabiocos** [comment]
@MartinaMalberti FYI

**Comment by civanch** [comment]
+1

regression problems in MkFit not related to this PR.

**Comment by srimanob** [comment]
+Upgrade

Code related to Upgrade is on debug message.

**Comment by jfernan2** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
