### PR TITLE
[13.2.X] Added efficiencies of matched and unmatched tracks (between HLT and offline) vs LS, vs online lumi and vs PU

### PR DESCRIPTION
**Pull request by mmusich**
backport of  https://github.com/cms-sw/cmssw/pull/42547

#### PR description:

Added histograms vs lumisection, vs online lumi & vs PU to monitor the efficiency of matched and unmatched tracks from HLT to offline. Histograms are filled in the pt and dxy plateau, as the other efficiencies.

#### PR validation:

Run raw2digi, L1Reco, reconstruction, dqmoffline and DQMoutput steps, on HLTMonitoring PD, run 370790.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/42547 in case we get to have a HLTMonitor PD for ppRef or HI data-taking. (N.B. track collection names etc. will need to be customized, once a finalized HLT menu is available).

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
