### PR TITLE
Phase1 Pixel Triplets Seeding by CA - LayerCache cleared after use

### PR DESCRIPTION
**Pull request by felicepantaleo**
The LayerCache should be cleared after use so that we don't get unexpected behavior in following events.

You can test triplets by customizing the process with: customiseForTripletsHLTPixelTracksByCellularAutomaton

@makortel @mtosi @VinInn @rovere

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@felicepantaleo is there a customize similar to customiseForTripletsHLTPixelTracksByCellularAutomaton that could  apply for reco ?

**Comment by felicepantaleo** [comment]
@slava77 
I will make it and commit it.

**Comment by felicepantaleo** [comment]
@slava77 you can now use: customiseForTripletsByCellularAutomaton
Of course it will not produce nice physics results, since it is replacing all the triplets but at least it will work as expected.

**Comment by slava77** [comment]
@cmsbuild please test

@felicepantaleo thanks

**Comment by slava77** [comment]
@felicepantaleo should we call it a bugfix?

**Comment by felicepantaleo** [comment]
@slava77 yes it is

**Comment by slava77** [comment]
type bugfix

to make the bot add a label

**Comment by felicepantaleo** [comment]
bugfix

**Comment by slava77** [comment]
On 9/16/16 8:28 AM, Felice Pantaleo wrote:
> bugfix

https://github.com/cms-sw/cmssw/issues/13028
the magic words should start with "type"

**Comment by felicepantaleo** [comment]
Thanks @slava77 :-)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15862 3bdcae9
- bugfix as described; also adds customiseForTripletsByCellularAutomaton applicable to reco/step3 checks/tests. The modified code is not a part of standard workflows.
- jenkins tests pass
- checked locally with 10224 in  CMSSW_8_1_X_2016-09-19-1100: step3 with customiseForTripletsByCellularAutomaton added leads to a crash in the baseline on the second event, while the version with this PR runs to completion.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
