### PR TITLE
Avoid side-effects in typeid call within rz_harm_poly in MagneticField

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes a clang warning.

#### PR validation:

The code compiles without warning using clang.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The workflow 1000.0 step2 error was a file open problem and thus unrelated to this pull request.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26509	e4d48d1
- technical 
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Pull request merged**
