### PR TITLE
Removal of phase2 Tracker geometries T17, T19, T20 and migrations

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This PR supersedes #31572. In addition to the removals in that PR, the HGCal development geometries D57, D58, D59, D62 are migrated from T17 to T21, producing D68, D69, D70, D71. The muon geometry M5 is removed as no longer relevant (see discussion in #30512). D63 is removed as redundant with D68.

#### PR validation:

* checked that runTheMatrix workflow numbers for existing workflows stayed the same
* ran new workflows 31434.0,31834.0,32234.0,32634.0 successfully

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
workflows = 31434.0,31834.0,32234.0,32634.0

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by emiglior** [comment]
@duartej this is of interest for you

**Comment by christopheralanwest** [comment]
@mmusich Do you have any comments on this PR?

**Comment by mmusich** [comment]
> @mmusich Do you have any comments on this PR?

This PR finally closes issue https://github.com/cms-sw/cmssw/issues/30512, hence has full approval of Tk DPG. Thanks.

**Comment by christopheralanwest** [comment]
+alca

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
