### PR TITLE
Fix CS8/EL8/CS9 openssl build error

### PR DESCRIPTION
**Pull request by smuzaffar**
use OPENSSL_VERSION_NUMBER instead of OPENSSL_API_COMPAT

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test for cs9_amd64_gcc11

**Comment by smuzaffar** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
