### PR TITLE
fix `CaloParticle` class version after #46678

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, addresses https://github.com/cms-sw/cmssw/pull/46678#issuecomment-2513910181 and following

#### PR validation:

Run phase-2 HLT timing workflow successfully

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * enable = hlt_p2_integration, hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
urgent

**Comment by smuzaffar** [comment]
@cms-sw/simulation-l2 , can you please review this?

**Comment by kpedro88** [comment]
+simulation

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
