### PR TITLE
Update Pythia Hook for BB4L

### PR DESCRIPTION
**Pull request by lauridsj**
#### PR description:

This PR replaces the Pythia Hook used for showering events produced with the bb4l generator with a new version provided by the authors.

There are two reasons why this is necessary, both related to the new bb4l version that was released last year:

- The old version that was in CMSSW beforehand had a bug that caused the hook to crash for events that had only an antitop and no top (i.e. tbarW events). This was never noticed because in the old bb4l, tW events were still labeled as ttbar events, while the new bb4l also has events labeled as tW. 
- The new bb4l version also includes the semileptonic decay channel of ttbar, which the old hook does not support.

I have copied the version provided by the authors with as few changes as necessary to adapt it to CMSSW and Pythia 8.2 (the original version was for Pythia 8.3).

Note that some of the flags present in the old hook are no longer present. These flags were meant as cross-checks by the bb4l authors to test the effects of several assumptions of the matching, and were never used in CMS for official MC production. Thus I did not bother to reimplement them in the new version of the hook. (Also note that the most important such flag for an "alternate" matching, `POWHEG:bb4l:ScaleResonance:veto`, is still there.)

In addition, I have added a new flag that was not present in the version of the authors: `POWHEG:bb4l:vetoAllRadtypes`. This flag is not meant for bb4l (and should be left at its default value of false when showering bb4l), but instead for the ttb_NLO_dec generator, which we might want to generate in the future as well. This generator also generates up to one real emission per decaying top, thus has the same final state as bb4l and can use the same hook. However, after checking with the authors, we were notified that it is necessary to modify the hook to also veto Powheg remnant events (`radtype` 2), which is not the case for bb4l. This alternate behavior is implemented with this flag.

#### PR validation:

I have confirmed that, when run on LHE files produced by the old bb4l, the new and old versions of the hook give exactly the same output.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

The PR will need to be backported to all MC production releases, i.e.
10_6_X (UL)
12_4_X (2022)
13_0_X (2023 I think?)
(Any that I missed?)

### CODE REVIEW

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by lauridsj** [comment]
Hey @menglu21 , it looks like the tests are somehow stuck... do you know what is going on?

**Comment by lauridsj** [comment]
Hey  @menglu21 @bbilin , sorry for spamming, but could you maybe have a look at why the tests are stuck / just restart them in case something went wrong? It would be great if we could merge this PR soon so that we could start the MC request for the new bb4l sample + variations. 
Thanks a lot!

**Comment by menglu21** [comment]
not sure what happened, @rappoccio, @sextonkennedy, @antoniovilela could you please have a look

**Comment by rappoccio** [comment]
abort

**Comment by rappoccio** [comment]
@cmsbuild please test

**Comment by lauridsj** [comment]
Hi @menglu21 @bbilin , sorry for the failing test. There was an unused variable in the hook sent by the authors that I didnt notice when compiling myself. I've removed it now.
Could you please restart the tests once again? 
Thanks a lot!

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
