### PR TITLE
Update Default Datasets for 2022 (was 2021)

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Updating the default datasets for 2022 (was 2021) conditions. Prompted by https://github.com/cms-sw/cmssw/pull/46649#issuecomment-2497763234.

#### PR validation:

Checking `runTheMatrix.py -w upgrade -l 11834.0 --dryRun` without this PR:

```
# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN,SIM -n 10 --conditions auto:phase1_2022_realistic --beamspot DBrealistic --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 9000,100 --fileout file:step1.root  > step1_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step2  -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2022 --conditions auto:phase1_2022_realistic --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/1/GEN-SIM --filein  file:step1.root  --fileout file:step2.root  > step2_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidationNoHLT+@miniAODValidation,DQM:@standardDQMFakeHLT+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2022_realistic --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO -n 10 --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --geometry DB:Extended --era Run3 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/1/GEN-SIM --filein  file:step2.root  --fileout file:step3.root  > step3_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step4  -s HARVESTING:@standardValidationNoHLT+@standardDQMFakeHLT+@miniAODValidation+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2022_realistic --mc  --geometry DB:Extended --scenario pp --filetype DQM --era Run3 -n 10 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/1/GEN-SIM --filein file:step3_inDQM.root --fileout file:step4.root  > step4_TTbar_14TeV+2022PU.log  2>&1
 
11834.0_TTbar_14TeV+2022PU Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Nov 25 12:41:20 2024-date Mon Nov 25 12:41:20 2024; exit: 0 0 0 0
```

With this PR:

```
# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN,SIM -n 10 --conditions auto:phase1_2022_realistic --beamspot DBrealistic --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 9000,100 --fileout file:step1.root  > step1_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step2  -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2022 --conditions auto:phase1_2022_realistic --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/CMSSW_13_1_0_pre1-130X_mcRun3_2022_realistic_withNewBSFromEOY2022Data_v2_RV186-v1/GEN-SIM --filein  file:step1.root  --fileout file:step2.root  > step2_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidationNoHLT+@miniAODValidation,DQM:@standardDQMFakeHLT+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2022_realistic --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO -n 10 --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --geometry DB:Extended --era Run3 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/CMSSW_13_1_0_pre1-130X_mcRun3_2022_realistic_withNewBSFromEOY2022Data_v2_RV186-v1/GEN-SIM --filein  file:step2.root  --fileout file:step3.root  > step3_TTbar_14TeV+2022PU.log  2>&1
 

# in: /lustre/home/adrianodif/random_devs/PR_Fix2021/cmssw/src dryRun for 'cd 11834.0_TTbar_14TeV+2022PU
 cmsDriver.py step4  -s HARVESTING:@standardValidationNoHLT+@standardDQMFakeHLT+@miniAODValidation+@miniAODDQM+@nanoAODDQM --conditions auto:phase1_2022_realistic --mc  --geometry DB:Extended --scenario pp --filetype DQM --era Run3 -n 10 --pileup AVE_35_BX_25ns --pileup_input das:/RelValMinBias_14TeV/CMSSW_13_1_0_pre1-130X_mcRun3_2022_realistic_withNewBSFromEOY2022Data_v2_RV186-v1/GEN-SIM --filein file:step3_inDQM.root --fileout file:step4.root  > step4_TTbar_14TeV+2022PU.log  2>&1
 
11834.0_TTbar_14TeV+2022PU Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Nov 25 12:42:30 2024-date Mon Nov 25 12:42:30 2024; exit: 0 0 0 0
```

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
test parameters:
- relval_opts = -w upgrade
- relvals = 11834.0, 13434.0, 11834.99, 11834.13, 11834.19, 11834.21, 11846.0, 11846.19

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
Should the FastSim PU changed to [/RelValMinBias_14TeV/CMSSW_12_5_0_pre4-124X_mcRun3_2022_realistic_v10_Run3FastSim_FastSim-v1/GEN-SIM](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FRelValMinBias_14TeV%2FCMSSW_12_5_0_pre4-124X_mcRun3_2022_realistic_v10_Run3FastSim_FastSim-v1%2FGEN-SIM&instance=prod/global) ?

**Comment by AdrianoDee** [comment]
> [/RelValMinBias_14TeV/CMSSW_12_5_0_pre4-124X_mcRun3_2022_realistic_v10_Run3FastSim_FastSim-v1/GEN-SIM](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FRelValMinBias_14TeV%2FCMSSW_12_5_0_pre4-124X_mcRun3_2022_realistic_v10_Run3FastSim_FastSim-v1%2FGEN-SIM&instance=prod/global)

Actually also this has no more files on disk. I think the problem here is that, given the change of name, the bot is no more able to use the cached files (@smuzaffar)? While for 2022 we have some new MinBias, for 2022FS we don't. I'll have to resubmit a new MinBias batch.

**Comment by smuzaffar** [comment]
> Actually also this has no more files on disk. I think the problem here is that, given the change of name, the bot is no more able to use the cached files (@smuzaffar)?

correct, if query is changed then  bot can not use the cached files. I will try to use the new file and will will try to cache those new files as long as they are accessible via xrootd

**Comment by AdrianoDee** [comment]
please tests

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
Some "non-standard" samples are missing, I'm producing them.

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Ok the final one (FastSim [MinBias](https://cms-pdmv-prod.web.cern.ch/relval/relvals?prepid=CMSSW_14_0_18__Run3_2022_FastSim_MinBiasGS-MinBias_14TeV-00002&shown=1023&page=0&limit=50)) should be ready.

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

(this time for real, the FastSim samples should be the good ones now)

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Comment by iarspider** [comment]
@AdrianoDee now the 2023 WFs [are failing](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_15_0/2024-12-09-2300?selectedArchs=el8_amd64_gcc12&selectedFlavors=X&selectedStatus=failed): 
image

**Comment by AdrianoDee** [comment]
Yes I see, but it does not depends on this PR. For some reason the bot is no more able to fetch the input datasets.

**Comment by iarspider** [comment]
I don't think dataset `RelValMinBias_14TeV/1/GEN-SIM` is valid, right?

**Comment by AdrianoDee** [comment]
Ok this is my bad. Sorry. Let me fix it.

**Pull request merged**
