### PR TITLE
Fix failing tests in FWCore/ParameterSet

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixed tests that had been in the works during the initial transition to using pythone 3 syntax.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failures are not caused by this pull request. The failures are because the following file can not be found:
RecoEgamma/ElectronIdentification/data/LowPtElectrons/RunII_Autumn18_LowPtElectrons_mva_id.xml.gz

**Comment by fabiocos** [comment]
@Dr15Jones that file is in cms-sw/cmsdist#4728 merged in the latest IB, not yet fully built unfortunately... I'll relaunch the test as soon as the build is there

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test 

the error looks unrelated to this PR, and seems related to XRootD, similar to that seen in the last IB for wf 11024 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_6_X_2019-02-27-1100/pyRelValMatrixLogs/run/11024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018PU_GenSimFullINPUT+DigiFullPU_2018PU+RecoFullPU_2018PU+HARVESTFullPU_2018PU+NanoFull_2018PU/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018PU_GenSimFullINPUT+DigiFullPU_2018PU+RecoFullPU_2018PU+HARVESTFullPU_2018PU+NanoFull_2018PU.log#/

**Comment by fabiocos** [comment]
+1

fix a failing unit test, the header consistency issues look spurious

**Pull request merged**
