### PR TITLE
Use GEM clusters in the GEM-CSC local trigger

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Follow-up of #28334 and #27832. This PR switches to using GEM clusters instead of GEM pads in the GEM-CSC local trigger. For now I'm keeping the option to run directly on GEM pads in the code because it may be useful in the optimization of the cluster selection.

EDIT: I turned the useCluster option off again. While ME1/1 looks good, there is a feature in ME2/1 that I need to investigate further. I do need the C++ code.

#### PR validation:

I ran matrix test 22034.0. I also tested the efficiency in high pileup simulations (PU200). LCT efficiency shows <1% drop in efficiency due to overflow of the GEM cluster collection.

#### if this PR is a backport please specify the original PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
This PR would have to be rebased once #28472 is in.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic this PR looks pending since one week, could you please review it?

**Comment by silviodonato** [comment]
@benkrikler  @rekovic please review/sign

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
@rekovic @benkrikler this PR is pending since December 11 and affects only L1T, could you please review/sign?

**Comment by silviodonato** [comment]
@rekovic @benkrikler it would be great if you sign this PR by today in order to have it in CMSSW_11_1_0_pre2

**Pull request merged**
