### PR TITLE
Remove duplicated functions in Provenance.h

### PR DESCRIPTION
**Pull request by wmtan**
For historical reasons, the class "Provenance" has three different member functions that are identical except for the function name. This PR removes two of them, constBranchDescription() and product(), and replaces calls to them with calls to the existing identical function, branchDescription().
It also replaces two iterator loops with two C++11 range based for loops in a file that was modified anyway. This PR should not cause any functional changes whatever.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Comment by perrotta** [comment]
+1
(Provided it passes the tests)

**Comment by Dr15Jones** [comment]
Please test

**Pull request merged**
