### PR TITLE
[DD4hep] Add second name to elementary materials for Geant4 GDML

### PR DESCRIPTION
**Pull request by cvuosalo**
Elementary materials inside ROOT and Geant4 use two names, called variously the "name" and "title" or the "name" and "symbol". With DD4hep, redefined elements were given the second name "CMS element" because it was thought that this second name was not used. However, it does show up in Geant4 GDML and causes confusion when multiple elements all have "CMS element" as a second name.

It should be noted that our code uses ROOT elements unchanged by default, unless they have atomic masses that differ from the standard atomic masses specified for Geant4, in which case the elements are redefined.

This PR leaves ROOT elements unchanged, but for those elements our code redefines to make their atomic masses match the Geant4 standard, their two names are made to match each other. Thus, ROOT elements have names like "HYDROGEN (H)", while redefined elements have names like "Oxygen (Oxygen)". The format of the names doesn't matter as long as the names are unique.

This PR also promotes to Warning messages about composite materials that have undefined components. It is planned to make this condition an exception, with the Warning message as a first step to allow changing any remaining cases in Phase 2 before the exception is implemented.

A simple fix of the DD4hep overlap check config is also included in this PR.

#### PR validation:

The `SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4hep_cfg.py` was run to check the Geant4 materials list and the GDML file to verify that they contain unique element names for both names.

No backport is needed.

### CODE REVIEW

**Comment by civanch** [comment]
@cvuosalo , in Geant4 both name and symbol are used only for printout. There is no practical sense to define symbol for Geant4 element derived from TGeo element.

Geant4 team do not recommend to build elements from G4Element(..) constructor, instead G4NistMaterial::Instance()->FindOrBuildElement(G4int Z) interface should be used.

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@civanch I'm not sure I understand your comment. Should anything be changed in this PR, or is your comment for future consideration?

**Comment by civanch** [comment]
+1

my comments for further fixes: with DD4Hep we have unreasonable material and elements names.

**Comment by qliphy** [comment]
+1

**Pull request merged**
