### PR TITLE
Added 3 sets of PS weights variations

### PR DESCRIPTION
**Pull request by jfernan2**
Validation on:
I have tested the 3 PS weights configurations:

- sqrt(2) and 1/sqrt(2)  (reduced)
- 2 and 0.5  (default)  -> this is the variation considered up to now in CMS samples
- 4 and 0.25  (conservative)

against central default.

As expected, the Conservative one gives large uncertainty in the FSR contribution specially at high jet multiplicities since weights get very large. Differences between Reduced and Default are small at large pT except at high jet multiplicities.

Conservative vs Default:

http://test-project-rivet.web.cern.ch/test-project-rivet/12041PSweightsConVSDef/CMS_2015_I1397174/index.html#CMS_2015_I1397174-d01-x01-y01

Reduced vs Default:

http://test-project-rivet.web.cern.ch/test-project-rivet/12041PSweightsRedVSDef/CMS_2015_I1397174/index.html#CMS_2015_I1397174-d01-x01-y01

### CODE REVIEW

**Comment by perrozzi** [comment]
isn't this exactly the same as https://github.com/jfernan2/cmssw/blob/f73944e7e84211ab4ff210a9487a9d2d44e969fc/Configuration/Generator/python/MCTunes2017/PythiaCP5Settings_cfi.py ?

**Comment by jfernan2** [comment]
Sorry, the right file now: it seems I did git add and the edit the file, so git took the file I used as starting point...
Apologies...

**Comment by perrozzi** [comment]
probably worth adding a sub-directory, like `PSweigts` or similar ?

**Comment by jfernan2** [comment]
even if it is just a single file?

**Comment by perrozzi** [comment]
yes to ease its search, otherwise one has to find it among other 400+ files...
(and we could also store mulitple snippets in case of need)

**Comment by efeyazgan** [comment]
please test

**Comment by perrozzi** [comment]
sorry naive question, I remember that there was a sqrt or square to apply from scale variations mu and pythia parameters, do I remember incorrectly?

**Comment by jfernan2** [comment]
Not in this case since the weights nomenclature is taking that into account according to Pythia manual and Steve:
http://home.thep.lu.se/~torbjorn/pythia82html/Variations.html

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
