### PR TITLE
Modernized RPCTrigger

### PR DESCRIPTION
**Pull request by Dr15Jones**
-Changed the module to a one module (it uses a singleton)
-Use std::unique_ptr
-Switched to efficient edm::Event calls
-Do not call get from EventSetup in the loop

### CODE REVIEW

**Comment by Dr15Jones** [comment]
RPCTrigger could be made into a more efficient module (e.g. stream or global) if the use of the MuonsGrabber singleton were removed from this package. Just removing it from the module is insufficient since helper classess the module calls also modify the singleton.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The failures are from file open errors.

**Comment by Dr15Jones** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
