### PR TITLE
DD Compact View Producer from DB

### PR DESCRIPTION
**Pull request by ianna**
*  Cleanup a DDCompactView producer from DB XML

This allows to pick up CTPPS geometry from DB with the following modifications to Geometry/VeryForwardGeometry/python/geometryRP_cfi.py:

```
import FWCore.ParameterSet.Config as cms

XMLIdealGeometryESSource_CTPPS = cms.ESProducer("XMLIdealGeometryESProducer",
                                                rootDDName = cms.string('cms:CMSE'),
                                                label = cms.string(''),
                                                appendToDataLabel = cms.untracked.string('XMLIdealGeometryESSource_CTPPS')
                                                )

ctppsGeometryESModule = cms.ESProducer("CTPPSGeometryESModule",
    verbosity = cms.untracked.uint32(1),
    compactViewTag = cms.string('XMLIdealGeometryESSource_CTPPS')
)

```

Note, the following addition to a job configuration is needed to pick up the record from a local DB:

```
$ diff testTracks-fromDB.py testTracks.py 
42,48d41
< process.GlobalTag.toGet = cms.VPSet(
<     cms.PSet(record = cms.string('GeometryFileRcd'),
<              tag = cms.string('XMLFILE_Geometry_TagXX_Extended2017_mc'),
<              connect = cms.string("sqlite_file:myfile.db"),
< #             label = cms.string("Extended")
<              )
<     )
52d44
<
```
See https://github.com/cms-sw/cmssw/pull/21974

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by Dr15Jones** [comment]
@ianna there is already a mechanism built in to the EventSetup system to allow you to set a label from the configuration. All ESProducers and ESSources have the parameter `appendToDataLabel` which is a tracked `string`.

**Comment by Dr15Jones** [comment]
THhe `appendToDataLabel` is documented here: https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToWriteESProducer#Labels

**Comment by ianna** [comment]
@Dr15Jones - thanks, I was searching for exactly this one.

**Comment by ianna** [comment]
@Dr15Jones - unfortunately, appendToDataLabel is tracked. It means all .py configurations should be modified.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
