### PR TITLE
Online DQM: Add EMTF DQM plots on GEM information and their comparison to CSC inputs

### PR DESCRIPTION
**Pull request by zuoxunwu**
#### PR description:

This PR is the first PR to include GEM information in the EMTF online DQM collection. Plots added cover GEM occupancy, timing, and comparison of GEM inputs to CSC inputs. 
This PR also fixes a minor mistake in some CSC DQM plots where hits from neighboring chambers were filled in the wrong bins.

#### PR validation:

This development has been studied with RelVal ZMM samples and recent cosmic data. All DQM plots are generated and filled as expected. (As the GEM firmware is being tested and updated, EMTF does not receive meaningful inputs from GEM in cosmic runs for the moment. But the DQM part works fine.) 
The PR passed local unit tests and matrix test. 
Code format check was also run locally and code was updated accordingly.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport.

@eyigitba

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@zuoxunwu all GEM plots seem empty in every workflow, while CSC ones have entries when created (as expected).
Is this the right behaviour?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-07-30-0900+c4601a/44490/dqm-histo-comparison-summary.html
Thanks

**Comment by zuoxunwu** [comment]
Hi @jfernan2, thanks for the check! 
It looks the CSC hits are only filled in workflows 136.731, 136.793, 136.874, and 140.56, which are all Run 2 data samples. It is expected that there was no GEM signal in those runs.

All plots in 14 TeV samples are empty (no CSC or GEM hits). I am not familiar with the workflow to understand if this is expected. Looks to me that there are no EMTFHits in these simulations. In any case, I do not think the issue (if it is an issue) is caused by this PR.

FYI, in case it helps, I did run the DQM plots locally on a RelVal sample (/store/relval/CMSSW_12_0_0_pre4/RelValZMM_14/GEN-SIM-DIGI-RAW/120X_mcRun3_2021_realistic_v2-v1/00000/062257a2-badb-485f-bd55-810659b30d2d.root)
I have dumped the plots at https://xzuo.web.cern.ch/EMTF/pushtest_gem_relval_plots/. All plots look fine.
 
Also adding some EMTF experts to the thread @eyigitba, @jiafulow. 

Thanks!

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
