### PR TITLE
[12.4.X] use ibeos protocol for DQM/Integration unit tests (online DQM unit tests)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39829

#### PR description:

Title says it all, from suggestion at https://github.com/cms-sw/cmssw/issues/39669#issuecomment-1287484400

#### PR validation:

Run successfully `scram b runtests use-ibeos` with the fix

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/39829 to CMSSW_12_4_X

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent
   * please @cms-sw/dqm-l2 have a look (IBs are still broken)

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
