### PR TITLE
EP code bug fix

### PR DESCRIPTION
**Pull request by BetterWang**
Bug fix, urgent for HI run.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@BetterWang: Please explain what changes in reconstruction will result from your bug fix.

**Comment by BetterWang** [comment]
Hi @cvuosalo , there is no change in the reco step.
The bug affects only calibrations read from the confdb.

**Comment by cvuosalo** [comment]
+1

For #11835 884d14b16f0da58ee1c6aec5698826bfe795dde2

Small bug fix for Heavy Ions in HiEvtPlaneAlgos. The fix only affects calibrations and should not change RECO quantities. #11836 is the 75X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-10-15-2300 show no significant differences, as expected. An additional test was done for #11836 that also showed no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
