### PR TITLE
fix CloseByParticleGun config

### PR DESCRIPTION
**Pull request by AuroraPerego**
#### PR description:

This python config file was not updated after the changes done to the `CloseByParticleGunProducer` and this caused wf `29693` to fail during step1.

#### PR validation:

Tested on wf `29693.203` that now runs without errors.

### CODE REVIEW

**Comment by rovere** [comment]
test parameters:
- workflow_opts= -w upgrade
- workflow = 29693.203,29893.203

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
