### PR TITLE
PPS diamond mapping fix for 2023 run

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR updates the XML mappings for PPS diamond detectors for 2023 run campaign.
The change follows recently discovered hardware issue, related to bad fiber input connector in the NEW OptoRX installed to cope with the new high trigger rate foreseen. Backward compatibility is sustained.

During tests of this PR we discovered as well that on of the parameters in the PPS DQM module was not marked as untracked.
This was probably a leftover from a  migration campaign done in https://github.com/cms-sw/cmssw/pull/38907
Appropriate change comes as well with this PR.

See as well related https://github.com/cms-sw/cmssw/pull/40763

#### PR validation:

This PR was validated with relvals 136.793, 1043 and 1044 (which run PPS reconstruction).
The reconstruction of Run 2 and 2022 data seems not affected.
New XML is parsed properly, I ran cmsRun CalibPPS/ESProducers/test/test_totemDAQMappingESSourceXML_cfg.py to parse XML and print its content on the console.
We ran the tests of unpacker on dataset(run 364968) taken after hardware intervention. The raw2digi step produced expected results.
We do not have proper 2023 data taken with new cabling, so full-scale reconstruction tests are not possible yet.

### CODE REVIEW

**Comment by francescobrivio** [comment]
type ctpps

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 136.793,1043,1044

**Comment by francescobrivio** [comment]
Thanks @grzanka for this fix!
Let me just remind you that, as discussed in https://github.com/cms-sw/cmssw/pull/40763#issuecomment-1438862519 we agreed that _for now_ it's ok to have the xml solution, but it would be preferred to it implemented in the GT, the corresponding issue to track this update is https://github.com/cms-sw/cmssw/issues/40967

We will also need a 13_0_X backport if this is intended for 2023 data-taking.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by grzanka** [comment]
> Thanks @grzanka for this fix! Let me just remind you that, as discussed in [#40763 (comment)](https://github.com/cms-sw/cmssw/pull/40763#issuecomment-1438862519) we agreed that _for now_ it's ok to have the xml solution, but it would be preferred to have it implemented in the GT, the corresponding issue to track this update is #40967

Thanks for reminder, we already planned a campaign to move the records to GT, this should be accomplished during summer 2023.

> We will also need a 13_0_X backport if this is intended for 2023 data-taking.

Here is the backport: https://github.com/cms-sw/cmssw/pull/41188

**Comment by francescobrivio** [comment]
+1

**Comment by perrotta** [comment]
type bug-fix

**Comment by tvami** [comment]
urgent
 * the backport is urgent

**Pull request merged**
