### PR TITLE
Update dijet prompt dqm (#19873)

### PR DESCRIPTION
**Pull request by bobaekim**
Dear all,

I created new PR about #19873.
- modified directory
- decrease bins as similar as Jet Monitor

I tested those codes in CMSSW_10_0_3 with runTheMatrix 1325.
Your comments are welcomed and appreciated.
Thank you in advance.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
The DQM histogram memory has been reduced by a factor of about 5 compared to the original proposal, according to the test. No new folder is added, the HLT/JME is filled with additional folders for the newly monitored paths. The histogram binning has been reduced.
Looking at the output of 136.788:

Total bytes: 201151.73 KiB                                    | Total bytes: 201408.36 KiB
11963.23 KiB     HLT/JME                                      | 12377.90 KiB     HLT/JME

The changes in the log files are gone.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
