### PR TITLE
Remove unnecessary explicit template instantiations from DQM/SiStripCommissioningSummary

### PR DESCRIPTION
**Pull request by makortel**
Found by clang.

Tested in CMSSW_10_5_X_2019-01-13-0000, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I'm a bit curious why these classes need to be specializations of `SummaryPlotFactory<T>` template instead of normal classes (still inheriting from `SummaryPlotFactoryBase` base class)?

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
