### PR TITLE
HLT menu development for `13_0_X` (5/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #41113

#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

It includes the integration of the following JIRA tickets.

  - [CMSHLT-2587](https://its.cern.ch/jira/browse/CMSHLT-2587): [HCAL,CSC,GEM] sync `hcalRecAlgos` and `muonDetIdAssociator` ES modules with Run-3 offline reco
  - [CMSHLT-2635](https://its.cern.ch/jira/browse/CMSHLT-2635): [BPH] use pixel-triplet matching in low-mass di-electron triggers
  - [CMSHLT-2637](https://its.cern.ch/jira/browse/CMSHLT-2637): [BPH] use pixel-triplet matching in `HLT_SingleEle*` control triggers
  - [CMSHLT-2651](https://its.cern.ch/jira/browse/CMSHLT-2651): [DAQ] changed compression settings of all OutputModules to (algorithm = "ZSTD", level = 3)
  - [CMSHLT-2684](https://its.cern.ch/jira/browse/CMSHLT-2684): [HIG] triggers for HH4b in semi-resolved topology
  - [CMSHLT-2685](https://its.cern.ch/jira/browse/CMSHLT-2685): [HIG] added PNet-based VBF HToCC triggers
  - [CMSHLT-2688](https://its.cern.ch/jira/browse/CMSHLT-2688): [BPH] added 2023 L1T seeds to BsMuMu triggers (part 2)
  - [CMSHLT-2689](https://its.cern.ch/jira/browse/CMSHLT-2689): [JME] halved PSs of `HLT_PFJetFwd80` and `HLT_AK8PFJetFwd80` (part 2)
  - [CMSHLT-2694](https://its.cern.ch/jira/browse/CMSHLT-2694): [B2G] added backups of `AK8(Di,)PFJet*_MassSD(30,50)` triggers
  - [CMSHLT-2696](https://its.cern.ch/jira/browse/CMSHLT-2696): [TSG] store unseeded E/gamma in Scouting, and use separate L1EG-seeded Scouting triggers
  - [CMSHLT-2698](https://its.cern.ch/jira/browse/CMSHLT-2698): [BPH] removal of four `Dimuon0_Upsilon` triggers from GRun (combined table unchanged)
  - [CMSHLT-2701](https://its.cern.ch/jira/browse/CMSHLT-2701): [JME] additional `HLT_Photon*EB_TightID_TightIso` triggers
  - [CMSHLT-2707](https://its.cern.ch/jira/browse/CMSHLT-2707): [EXO] moved MuShower-seeded DT/CSC-cluster triggers to Muon PD
  - [CMSHLT-2721](https://its.cern.ch/jira/browse/CMSHLT-2721): [BPH] set PS=0 for `HLT_Mu12_IP6_v` and remove `ParkingSingleMuon*` streams/PDs from GRun
  - [CMSHLT-2724](https://its.cern.ch/jira/browse/CMSHLT-2724): [EXO] added HLT-HT cut to L1_Mu6HT240-seeded displaced-jets triggers
  - [CMSHLT-2726](https://its.cern.ch/jira/browse/CMSHLT-2726): [EGM] removed `*ForBParking*` Sequences from `MC_Egamma_Open*` triggers, and add `MC_Egamma_Open*` to GRun menu

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41113

Development of HLT menus for 2023 data-taking and Run-3 MC.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - workflows = 139.004,140.003,140.023,140.043,140.063,12634.0,12634.99,12834.0,13034.0,13034.99

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt
 - changes in the outputs of PR tests are in line with updates to the HLT GRun menu, and the change in name of the fake HLT menus

**Comment by missirol** [comment]
The parent PR was tested in `CMSSW_13_1_X_2023-03-21-2300`. The HLT-Validation tests failed because of a transient issue with file access, see https://github.com/cms-sw/cmssw/pull/41113#issuecomment-1479562884. I don't see issues caused by that PR in that IB.

I think it's okay to merge this backport.

**Comment by perrotta** [comment]
+1

**Pull request merged**
