### PR TITLE
Enable pt-dependent JER-SF and phi-dependent JEC application in PAT [102X backport]

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Enable pt-dependent jet resolution scale factors in PAT. This is needed to apply Autumn18_V7 JER-SF, released last week.
Enable phi-dependent jet energy scale in PAT. This will be needed for 2018 JEC to deal with the HEM issue.
This PR has no impact with the current global tags in any release. However, it will enable using a new global tag (currently in the makings) with pt-dependent JER-SFs and later with phi-dependent JECs.

A test config to apply resolution smearing from a db file has been added under /test.
Here is an example db-file containing pt-dependent JER-SFs:
https://github.com/cms-jet/JRDatabase/blob/master/SQLiteFiles/Autumn18_V7_MC.db

#### PR validation:

Test config runs after inclusion of this PR. It was checked that this does not change the memory consumption, compared to using the old code with Autumn18_V1_MC.db (no pt-dependence).

#### if this PR is a backport please specify the original PR:

Backport of #28096

### CODE REVIEW

**Comment by ahinzmann** [comment]
@peruzzim runMETCorrectionsAndUncertainties is affected by this and I assume you re-run it for the new NanoAOD with the new JER/JEC. This this PR is necessary for the NanoAODv6 production.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@ahinzmann 
are the additional numerous differences in the modified files from just the clang formatting in addition to the changes in the #28077 or does this also include a backport of other developments?

**Comment by ahinzmann** [comment]
Hi Slava,

this is all clang formatting, no additional developments.

Best,
Andreas

**Comment by fabiocos** [comment]
please test

**Comment by slava77** [comment]
backport of #28096 
this is more of a copy-paste from the master version though; it includes clang-format changes on top of #28096

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28098	15fb757 
- code changes are in line with the PR description; added to support additional parameterization in the JEC/JER
- the backport is essentially correct (https://github.com/cms-sw/cmssw/pull/28097#pullrequestreview-298745749) 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
