### PR TITLE
Demangled log printout of Pedereader [14.0.X]

### PR DESCRIPTION
**Pull request by phnattla**
#### PR description:

Demangled PedeReader output to make logs more readable (backport)

#### PR validation:

Used the following command to validated the changes:

```
cmsDriver.py stepHarvest2 -s ALCAHARVEST:SiPixelAliHGCombined --conditions 140X_dataRun3_Express_v3 --scenario pp --data --dasquery='file dataset=/StreamExpress/Run2024F-PromptCalibProdSiPixelAliHGComb-Express-v1/ALCAPROMPT run=383496' --custom_conditions=PCLThresholds_HG_Test_01,AlignPCLThresholdsHGRcd,frontier://FrontierPrep/CMS_CONDITIONS
```

Backport of PR https://github.com/cms-sw/cmssw/pull/45588 to CMSSW_14_0_X

@mmusich @henriettepetersen @TomasKello

### CODE REVIEW

**Comment by mmusich** [comment]
backport https://github.com/cms-sw/cmssw/pull/45588

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/45588

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
