### PR TITLE
Phase2-hgx35Z Try to correct masking for V17 and valid cells for V15/V16

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to correct masking for V17 and valid cells for V15/V16

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Why are the D88 scenarios showing comparison differences for this V17 change? Isn't V17 only used for D92?

**Comment by bsunanda** [comment]
The list of valid cells is corrected for V15/V16. Earlier versions had a larger list and this affects V15/V16 geometries which are in D83 or D86/D88

**Comment by cvuosalo** [comment]
+1

**Comment by pfs** [comment]
Looks good @bsunanda. Looping over the valid DetIds after this PR i get them all within the expected boundaries for V17

https://psilva.web.cern.ch/psilva/HGCAL/pr38302/?match=base

while before this was not the case

https://psilva.web.cern.ch/psilva/HGCAL/K0L/masks/?match=ana_layer

This PR is expected to have some impact on the hits, e.g. additional noise hits produced at DIGI level, given such step relies on the list of valid DetIds provided by the geometry.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please approve this PR

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Change from this PR is expected, as reported in https://github.com/cms-sw/cmssw/pull/38302#issuecomment-1153106213

**Comment by qliphy** [comment]
+1

**Pull request merged**
