### PR TITLE
fix memory leaks in EcalClusterLazyTools

### PR DESCRIPTION
**Pull request by jolange**
see #13497

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13505 7ea1052f0eea9cb15b6850298fc2596e5d8cce8a

Fixing a memory leak in EcalClusterLazyToolsBase. There should be no change in monitored quantities. #13497 and #13504 are the 76X and 80X versions of this PR, and they both have already been approved.

The code fix is satisfactory, and Jenkins tests against baselineCMSSW_8_1_X_2016-03-06-2300 show no significant differences, as expected.

**Pull request merged**
