### PR TITLE
Changed FailPath/SkipEvent to TryToContinue [L1Trigger]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The former options were replaced with the latter some time ago.

#### PR validation:

The configurations are not used anywhere.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
