### PR TITLE
JetCorrector migration in DiJetAnalyzer, GammaJetAnalysis

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Upgrade modules named DiJetAnalyzer and GammaJetAnalysis in the package Calibration/ HcalCalibAlgos from using the deprecated JetCorrector class to use the reco::JetCorrector class.

(This is my second try at this. See PR #39804. Originally I proposed deleting these modules).

#### PR validation:

Note that there are no unit tests or RelVal tests of these modules and nothing in CMSSW uses them that I am aware of besides the standalone test configurations also modified by this PR. Those test configurations did not work before the changes in this PR and will need some work on issues unrelated to JetCorrectors to execute successfully. There are some comments added in the test configurations indicating at least some of the problems that would need to be fixed. I did not address issues unrelated to JetCorrectors in this PR.

I hacked around with this code and made temporary changes (commenting out parts) as a test to be able to see that the JetCorrector parts of it are parseable by Python and the JetCorrector producers execute (verified in Tracer output).

### CODE REVIEW

**Comment by wddgit** [comment]
please test

FYI @makortel

**Comment by tvami** [comment]
Hi @bsunanda @mariadalfonso , do you have any ways to test these changes locally?

**Comment by wddgit** [comment]
If you give me new input files, then I will modify the the test configurations to use them and try executing the existing test configurations again. There are probably more problems than that to fix, but maybe that would be enough to get one or two of the configurations to run successfully (or maybe not). The more recent ones (but still old) are trying to read a CMSSW_7_3_X files or a local file that I do not have.

Note, that after this PR is merged we can proceed to merge the other PR that deletes the old JetCorrector code. After that, you can still upgrade DiJetAnalyzer and GammaJetAnalysis again at your convenience or when it is needed. You won't be able to go back to the old JetCorrectors, but you will be able to make whatever other changes you want or need.

**Comment by wddgit** [comment]
This is now the last PR removing usage of the old JetCorrector class in CMSSW. The other PR that was still under review was just merged.

One point I want to emphasize. You will be able to make further modifications to this code after this is merged. If there is something you do not like, you will be able to fix it. If there are additional improvements desired, you will be able to make them. And since nothing currently uses these modules, this PR will not break anything. It is an incremental change that fixes one problem in these modules and moves them one step closer to being usable. With it, they will use the modern JetCorrectors instead of the deprecated JetCorrectors that don't work anymore.

**Comment by tvami** [comment]
+alca
 * test pass, module not used, HCAL didnt respond in a week...
 * see also https://github.com/cms-sw/cmssw/pull/40139#issuecomment-1335398738

**Comment by perrotta** [comment]
+1

**Pull request merged**
