### PR TITLE
Add workflow 158.181 as 158.0 with concurrent lumis enabled

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Following a suggestion in https://github.com/cms-sw/cmssw/issues/25090#issuecomment-652426145 this PR adds workflow 158.181 as 158.0 with concurrent lumis enabled.

#### PR validation:

Workflow 158.181 runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 158.181

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
