### PR TITLE
Pythia8 gun decaylength2

### PR DESCRIPTION
**Pull request by smrenna**

### CODE REVIEW

**Comment by smrenna** [comment]
The Pythia8 particle guns were not giving a finite decay length for the primary particle.  Now this is fixed.

**Comment by smrenna** [comment]
If this should go in CMSSW_8_0_X, how do I change that?

**Comment by covarell** [comment]
I will just reject this and you can start over... Notice that this should go in 8_1_X now, not 8_0_X (you need to backport if this is really needed in 8_0_X, but I don't think so)

**Comment by covarell** [comment]
-1

**Pull request closed without merging**
