### PR TITLE
Making beamspot DIP server more verbose and additional fixes [12_0_X]

### PR DESCRIPTION
**Pull request by sikler**
#### PR description:

Adding MessageLogger, LogInfo output and setting 'verbose' flag.
Replaced DIM/DIP DNS to local CMS: cmsdimns1.cern.ch.
Fixed sending messages.

#### PR validation at P5:

Works well, tested with fake data on 8 Nov, details and screen shots
[https://twiki.cern.ch/twiki/bin/view/CMS/OnlineBeamSpotRun3#8_Nov_2021_new_information_on_lo](https://twiki.cern.ch/twiki/bin/view/CMS/OnlineBeamSpotRun3#8_Nov_2021_new_information_on_lo)

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by sikler** [comment]
@jfernan2 Please give me some days (I want to test some functionality with help of the local CMS DIP browser https://cmsonline.cern.ch/webcenter/portal/cmsonline/pages_common/dcs/dipbrowser). Well, that thing exists, would have been extra good for the pilot run.

**Comment by francescobrivio** [comment]
@sikler sorry for not following up earlier: what is the status of this PR?

**Comment by sikler** [comment]
@francescobrivio It was tested, worked well, ready to go.
https://twiki.cern.ch/twiki/bin/view/CMS/OnlineBeamSpotRun3#8_Nov_2021_new_information_on_lo

**Comment by francescobrivio** [comment]
That's great @sikler thanks!

@jfernan2 @ahmad3213 @pmandrik I think we need another playback with this before merging right?

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by pmandrik** [comment]
> That's great thanks! BTW, is there already a forwarport of this to 12_2_X @sikler ?
> 
> @jfernan2 @ahmad3213 @pmandrik I think we need another playback with this before merging right?

Hi, we did not remove it since previous green-light for production, so, at the moment the PR is already merged into production.

**Comment by jfernan2** [comment]
+1
Forwardport to master needed

**Comment by sikler** [comment]
@jfernan2 I am doing the forwardport right now.

**Comment by sikler** [comment]
https://github.com/cms-sw/cmssw/pull/36152

**Comment by francescobrivio** [comment]
backport of #36152

**Comment by francescobrivio** [comment]
thanks @sikler!

**Comment by perrotta** [comment]
+1
- This is fully signed, and actually fully tested at P5 (even better: "[already merged into production](https://github.com/cms-sw/cmssw/pull/35860#issuecomment-970470196)")
- There is no need to wait for the results of the IB tests in the master to merge, then

**Pull request merged**
