### PR TITLE
allow scram_arch and cmssw version manipulation from the ExternalLHEP…

### PR DESCRIPTION
**Pull request by perrozzi**
…roducer
(backport to 71x)

### CODE REVIEW

**Comment by perrozzi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/19457/

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
