### PR TITLE
Updating JEC in data/mc and fixes for HI

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in GT
## RunII simulation
- **RunII Ideal scenario** : [76X_mcRun2_design_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v11) as [76X_mcRun2_design_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_design_v11/76X_mcRun2_design_v12): 
  -  updated MC JEC to v6 with updated L2L3Residuals and uncertainties for 25ns.
- **RunII Asymptotic scenario** : [76X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v11) as [76X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_asymptotic_v11/76X_mcRun2_asymptotic_v12): 
  - updated MC JEC to v6 with updated L2L3Residuals and uncertainties for 25ns;
  - adding label JEC with AK4Calo label for pp reference run at 5TeV.
- **RunII Heavy Ions scenario** : [76X_mcRun2_HeavyIon_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v11) as [76X_mcRun2_HeavyIon_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v11/76X_mcRun2_HeavyIon_v12): 
  -  adding event plane calibrations for HI trough HeavyIonRPRcd;
  -  adding label JEC with AK4Calo label for pp reference run at 5TeV.
## RunI data
- **RunI Offline processing** : [76X_dataRun1_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v10) as [76X_dataRun1_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun1_v10/76X_dataRun1_v11): 
  - adding event plane calibrations for HI trough HeavyIonRPRcd;
  - adding label JEC with AK4Calo label for pp reference run at 5TeV;
  - updating AlCaReco Trigger bits to cover 2010 HI runs for new Tracker Alignment AlCaReco producers.
## RunII data
- **RunII Offline processing** : [76X_dataRun2_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v10) as [76X_dataRun2_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_HLT_v11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_v10/76X_dataRun2_v11):
  - adding event plane calibrations for HI trough HeavyIonRPRcd;
  - adding label JEC with AK4Calo label for pp reference run at 5TeV;
  - updating AlCaReco Trigger bits to cover 2010 HI runs for new Tracker Alignment AlCaReco producers.
  - updated DATA JEC to v3 with updated L2L3Residuals and uncertainties for 25ns;

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
