### PR TITLE
adding a pt<1 folder for HighPurity tracks in the DQM

### PR DESCRIPTION
**Pull request by mtosi**
this PR is meant for adding a new set of plots for the tracks collection w/ pT < 1 GeV

those plots are needed in both the validation workflow and the offline certification
for the moment they are not added in the online set of plots

running whiteRabbit -n 11
I see that we are adding 92 new histos, which correspond to an increase of 0.139670 MB
w.r.t. the current setting we have in 80x

@VinInn @rovere @makortel @deguio @fiori

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@mtosi - i don't see where, but this PR appears to add the following printout to all events. Could you have a look. Thanks

Begin processing the 37th record. Run 191226, Event 557090291, LumiSection 398 at 13-Jan-2016 11:06:21.879 CET
bxlumi : 0.000000
totalNumPV : 15
totalNumGoodPV: 12
fracGoodPV: 0.800000
bxlumi : 0.000000

**Comment by mtosi** [comment]
I should have fixed this issue

hope this is fine

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
