### PR TITLE
drop HLT in FastSim

### PR DESCRIPTION
**Pull request by mtosi**
as agreed w/ PdmV, this PR is meant to drop the HLT step from the standard workflow in FastSim

I tested this code running 
runTheMatrix.py --what standard -l 135.1 --command='-n 10'

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by mtosi** [comment]
may I ask what is still preventing this PR to be merged ?
thanks
@fwyzard @Martin-Grunewald @silviodonato

**Comment by mtosi** [comment]
@ssekmen

**Comment by fwyzard** [comment]
@lveldere

**Comment by ssekmen** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@franzoni, @mdhildreth, @davidlange6
Please sign....

**Comment by davidlange6** [comment]
no reason to push every ten minutes..

**Comment by mtosi** [comment]
@davidlange6, I do not get your comment, sorry

**Comment by davidlange6** [comment]
it was signed by fastsim 19 minutes ago…

**Comment by fwyzard** [comment]
What does that has to do with it being signed (or not) by Operations ?

**Comment by davidlange6** [comment]
operations (eg, me) will sign after the others.

**Comment by davidlange6** [comment]
so it looks like PATTriggerProducer needs to be removed from the miniAOD sequence as well?

20-Jan-2017 15:59:08 CET  Successfully opened file file:step1.root
%MSG-e HLTConfigProvider:  PATTriggerProducer:patTrigger@streamBeginRun  20-Jan-2017 15:59:39 CET Run: 1
Falling back to ProcessName-only init using ProcessName 'HLT' !
%MSG
%MSG-e HLTConfigProvider:  PATTriggerProducer:patTrigger@streamBeginRun  20-Jan-2017 15:59:39 CET Run: 1
 Process name 'HLT' not found in registry!
%MSG
%MSG-e HLTPrescaleProvider:  PATTriggerProducer:patTrigger@streamBeginRun  20-Jan-2017 15:59:39 CET Run: 1
 Unknown L1T Type 0 - prescales will not be avaiable!
%MSG
%MSG-e hltConfig:  PATTriggerProducer:patTrigger@streamBeginRun  20-Jan-2017 15:59:39 CET Run: 1
HLT config extraction error with process name 'HLT'
%MSG
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 20-Jan-2017 15:59:39.187 CET
%MSG-w L3Absolute not found:  PATJetUpdater:updatedPatJetsBTAG  20-Jan-2017 15:59:47 CET Run: 1 Event: 1
L2L3Residual and L3Absolute are not part of the jetCorrFactors
of module patJetCorrFactorsBTAG. Jets will remain uncorrected.
%MSG

**Comment by mtosi** [comment]
uhmmm, w/ the unscheduled
I simply add to drop the *patTrigger* from the event [1]

but I agree it would be better to drop it from the sequence,
I did not do it because it was not totally clear to me which file to patch
(I'm not an expert on this part) ...

is it enough to play w/ relval workflow [2] ?

thanks for your help !

[1]
https://github.com/mtosi/cmssw/blob/b17028e830e3833e5f4b8b9dc5c885db1e4861c1/Configuration/EventContent/python/EventContent_cff.py


[2]
https://github.com/mtosi/cmssw/blob/b17028e830e3833e5f4b8b9dc5c885db1e4861c1/Configuration/PyReleaseValidation/python/relval_steps.py

**Comment by davidlange6** [comment]
> On Jan 25, 2017, at 9:18 AM, mia tosi <notifications@github.com> wrote:
> 
> uhmmm, w/ the unscheduled
> I simply add to drop the *patTrigger* from the event [1]
> 

I think so  - just don’t ask for the pat trigger in the output when the fastsim era is active.

**Comment by mtosi** [comment]
sorry the delay,
didn't I already do it in
https://github.com/cms-sw/cmssw/pull/17224/files#diff-94f6d3020af66ea604d6eceace711e33R822
?

**Comment by fwyzard** [comment]
@davidlange6 what is holding this up ?
can you please merge it - and get the FastSim or PAT or whoever is responsible for the broken code fix things ?

**Comment by davidlange6** [comment]
its doesn’t work that way, no. Anyway it seems @mtosi answered yesterday so its on my todo list to confirm (of course its always better to have coherent PRs for faster results)

**Comment by fwyzard** [comment]
I wholeheartedly agree. But there is only so much knowledge about FastSim and PAT within trigger coordination :-(

**Comment by davidlange6** [comment]
of course - there are multiple ways to proceed - but breaking the IBs/releases won’t be one of them.

**Comment by mtosi** [comment]
I agree, of course
I do not have the intention of breaking anything

if you/anybody else can give me some guidelines, I'll be glad to follow them
thanks

**Comment by Martin-Grunewald** [comment]
@davidlange6 
David, could we get this integrated before pre5?
Thanks!

**Comment by davidlange6** [comment]
was investigating how to avoid adding and then removing the pat trigger content. Its more involved than it should be.

**Pull request merged**
