### PR TITLE
Remove duplicate initializations in two  DQM/HcalTasks plugins

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Trivial fix of a few dead assignments, pointed out by the static analyzed

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Tests seem have failed, even if the status didn't chenge since yesterday. Console says:
```
15:48:02 OSError: [Errno 28] No space left on device
```
Trying to abort (if ever needed...) and restart the tests

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
