### PR TITLE
position of variable in TrackerHitAssociator for small performance optimization

### PR DESCRIPTION
**Pull request by ngrenz**
PR of a work intended to optimize gradually the perfrormance of tracker validation code.
Outputs are supposed to be unchanged.

Any comments and suggestions are welcome -more optimizations will follow in the near future

### CODE REVIEW

**Comment by ngrenz** [comment]
@boudoul FYI

**Comment by makortel** [comment]
@ngrenz Did you measure the improvement from these? By just looking the code, I fail to see how these changes would improve timing (except for commenting out `++Nhits` (line 128) and `++dsl` (line 538), although the compiler might already now notice that they're not read and optimize them away, but this is just speculation), but I could be missing something.

(and personally I prefer to have variable declarations in the innermost scope that makes sense, if all other thins are equal)

**Comment by ngrenz** [comment]
@makortel The idea was that one variable is created one time before a for-loop instead of creating and destroying it several times inside the loop.

I have measured the improvement but the result is within the fluctuations of the runtime measurement with igprof (like the optimazation of the for-loops: https://github.com/cms-sw/cmssw/pull/9677 ), therefore it might be better for readability to omit the changes.

**Comment by makortel** [comment]
@ngrenz Well, in general assignment implies destruction of the old object in assigned-to variable, and the construction of the new objects can't really be avoided either. Also, more specifically, the types `EncodedEventId`, `simHitCollectionID`, and `simhitAddr` are just a bunch of integers (integer, pair, and pair of pair and integer, respectively), copying them is cheap (and destruction is ~no-op).

**Comment by ngrenz** [comment]
@makortel Ok, Thanks for the Help

**Pull request closed without merging**
