### PR TITLE
Run3-sim133 Use token instead of label in accessing collection and use TFileService for ROOT histograms in FastSimulation/Validation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use token instead of label in accessing collection and use TFileService for ROOT histograms in FastSimulation/Validation

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

pure technical, regression shows that it is OK

**Comment by rappoccio** [comment]
@bsunanda @civanch is the missing matrix map expected for this PR?

**Comment by rappoccio** [comment]
+1

As discussed in ORP, these are spurious errors.

**Pull request merged**
