### PR TITLE
Keep gen-level nuclear info 

### PR DESCRIPTION
**Pull request by mandrenguyen**
This is a forward port of the 75X PR #12344, which somehow got lost in the shuffle. 
https://github.com/cms-sw/cmssw/pull/12344

This keeps all nuclear information (npart, ncoll, reaction plane) which is necessary when the HepMCProduct is dropped.
This info takes up very little extra space and is contained in:
edm::GenHIEvent                       "heavyIon"                  ""                "HLT" 

This is produced and stored when the following flags are set, e.g., in wf 145:
DIGI:pdigi_hi
--pileup HiMixNoPU

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

(75X! There's a blast from the past...)

**Comment by fabozzi** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
I noticed for some reason this PR causes a bunch of messages like this to be printed in the log for 25202.0 step3:
```
%MSG-w BasicTrajectoryState:  TrackRefitter:refittedForPixelDQM  13-May-2017 01:14:53 CEST Run: 1 Event: 5
curv error not pos-def
[  4.50264e+08-2.74183e+08     -719598 1.78261e+06-1.30321e+06
  -2.74183e+08 1.66961e+08      438191-1.08546e+06      793343
       -719598      438191     1150.03    -2842.11     2053.42
   1.78261e+06-1.08546e+06    -2842.11     7051.35    -4382.02
  -1.30321e+06      793343     2053.42    -4382.02    -3010.24 ]
pos/mom/mf  (-27.4582,-22.8356,-28.562)   (-0.154575,-0.385741,-0.375501)   (0.00180473,0.00150091,3.81049) 
```
Not sure if this is spurious or not, but maybe it should be checked in a larger sample?

**Comment by mandrenguyen** [comment]
@kpedro88 Somewhat hard to imagine that this could be responsible for the change you're observing.  Only the wfs that use pdigi_hi should be affected.  All other wfs should be bit-wise identical.

**Comment by davidlange6** [comment]
Hi @mandrenguyen - it looks like this also causes problems in workflows 300,301,302 - can you fix in the next hours? [I think you've missed a migration that happened since 75x]

Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generatorSmeared

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 17-May-2017 13:16:38 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 1
   [1] Running path 'digitisation_step'
   [2] Calling method for module GenHIEventProducer/'heavyIon'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generatorSmeared

**Comment by mandrenguyen** [comment]
@davidlange6 Thanks for spotting that.  Looking now.

**Pull request merged**
