### PR TITLE
Revert "Revert "Backport of access to tauID and electron discrimination from miniAOD""

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#18234

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
hold
until we are ready for miniAOD v2

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18235	dc38852
- comments from https://github.com/cms-sw/cmssw/pull/17292#issuecomment-283234001 apply here
- the PR is to be merged when we build miniAODv2 release

**Comment by slava77** [comment]
@roger-wolf 

Hi Roger

is this still needed in 80X?
If not, please close the PR.
If yes, please clarify the use case.
Thank you.

**Comment by roger-wolf** [comment]
Hi Slava, 

we have solved the issue of accessing newly created tauIDs and anti-electron discriminator values via a recipe. The branch that we are using in the meantime differs in its implementation from this one (i.e. it contains more user relevant features). 

I think this explicit PR can be closed. If it makes sense to integrate the contained features for upcoming PRs into 80X for potential new releases I'd rather prepare a new PR based on the backport branch that we are currently using in our recipes. 

Concerning closing it, I think I'm not the one who opened this PR. I also see no option to close it. 

Cheers,
Roger

**Comment by perrotta** [comment]
@davidlange6 : could you please close this "revert-revert"? Thank you

**Pull request closed without merging**
