### PR TITLE
Better splitting and Tcrit definition for 4D vertexing (93X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #20709.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Identical to #20709, merged in the master

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
this was not included in 9_3_4
are we waiting for all Phase-2 PR updates to be available to merge this one?

**Comment by davidlange6** [comment]
ideally we'd have the other PR(s) needed for the hgcal re-miniaod - yes. but I just didn't include it ahead of time and didn't want to delay the build for it.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
