### PR TITLE
Run2-sim15 Handle the depth word correctly and use 2 lowest bit to store information crystal/APD

### PR DESCRIPTION
**Pull request by bsunanda**
Also try to use the information if it is a normal or reflected crystal in analysis

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda, you likely forget debug cout, would you expect any difference in comparison?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch The results from this should be the same as after the previous fix. The tests in EBHitResponse is now utilizing the two least significant bit information for APD information. So one can store radiation length and APD information in a standard run. So event content will be different but DIGI-RECO should be unchanged

**Comment by civanch** [comment]
@bsunanda, I also expect zero change of old workflows but there are a lot, even for data, not only for MC. What may be the reason?

**Comment by bsunanda** [comment]
@civanch I do not understand - the changes are made to two classes ECalSD.cc and EBHitResponse apart from the testing code. All these belong to simulation. So the changes to the data cannot come from them. So the comparison might be done against some thing which was produced lot earlier. I dont think these changes will affect simulation results as well.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , results are different for several tests, this is probably due to  EcalSD upgrade or EBHitResponse.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 @civanch Dont understand how this PR affects the failure

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 @smuzaffar @civanch The AddOn test is faulty - it asks for non-existent tag and even changing that it crashes in parts of code not relevant to this PR

**Comment by bsunanda** [comment]
@davidlange6 @smuzaffar @civanch The AddOn test is faulty - it asks for non-existent tag and even changing that it crashes in parts of code not relevant to this PR

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , I have started tests again in order to check if there is a real problem. However, I do not like in the recent update: you add extra dependency to SIM which is an access to biglib. You need this only for few enumeration constants. I would instead move do not change build.xml but move enumeration into common place, alternatively add these constants in the algorithm - some duplication is better than extra dependence.

**Comment by civanch** [comment]
@bsunanda , likely the bug is real, I would not add extra dependency.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch I put the masks in PCaloHit class whose member is having depth which is now presented with packed bit information. So the BuildFile's are not modified and dependency is unchanged.

**Comment by civanch** [comment]
+1
there are about 550 différences in HLT comparaison sub-directory for data and MC WFs, this PR is not responsible for such differences

**Comment by davidlange6** [comment]
hi @bsunanda @civanch - I miss the context behind this PR - is there some more information available?

**Comment by bsunanda** [comment]
@davidlange6 @civanch The main idea of this PR is that one can go beyond the SIM step with information about the depth within crystal. The DIGI step used to assume that depth can be an integer between 0 and 2 (crystal and two areas of the APD's). Now with 0 and 14 bits to store depth within crystal one can go to the end (GEN-SIM-DIGI-RECO) to study depth dependence in energy measurement (this was required by the Higgs mass group and they presented this in one ECAL DPG meeting). With these changes one can in principle make production with or without radiation length information. by changing python parameter

**Comment by davidlange6** [comment]
+1

**Pull request merged**
