### PR TITLE
[13_0_X] remove duplicate monitoring of FB at layer1 data-emulator workspace

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:
This is to remove duplicate monitoring of FB at layer1 in the data-emulator DQM workspace.

#### PR validation:
This will be tested with DQM production.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type hcal, l1t

**Comment by emanueleusai** [comment]
testing at p5

**Comment by hftsoi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42677

**Comment by emanueleusai** [comment]
tests at p5 completed successfully

**Comment by emanueleusai** [comment]
+1

- difference in HLT/SiStrip spurious
- tests at p5 ok (checked by author)

**Comment by rappoccio** [comment]
hold

* Please sign the main branch PR

**Comment by emanueleusai** [comment]
master and other backports signed, can be unheld now

**Comment by rappoccio** [comment]
unhold

**Comment by rappoccio** [comment]
+1

**Pull request merged**
