### PR TITLE
[DD4hep] use assembly instead of complex union shapes

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:
introduce changes in Ecal preshower algorithm as discussed during simulation meeting and agreed with @bsunanda 

#### PR validation:
no overlaps in Ecal preshower detected by ROOT
Screenshot 2021-05-14 at 16 31 16

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , this is Great!

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
