### PR TITLE
Add SV charge [112X]

### PR DESCRIPTION
**Pull request by gouskos**
**PR description:**
Add the sum of the charge of the tracks associated to each SV.
Needed for BTV, Charm tagging calibration in the W+c channel, and analyses

Backport of https://github.com/cms-sw/cmssw/pull/32874

### CODE REVIEW

**Comment by gouskos** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by gouskos** [comment]
+xpog

**Comment by qliphy** [comment]
+1

**Pull request merged**
