### PR TITLE
Replace boost::regex with std::regex

### PR DESCRIPTION
**Pull request by smuzaffar**
Though this does not drop the boost dependency for this package but it is a minor cleanup to replace boost::regex with std::regex.

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi , can you please review this?

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
