### PR TITLE
Totem timing DQM, backport of #22915

### PR DESCRIPTION
**Pull request by nminafra**
This PR is a backport of #22915, **needed for the DQM during the alignment run**, similarly to #22930 

This PR introduces the DQM for Totem vertical timing detectors, using TotemTimingDigi.
This shall be applied on top of #22930 
No conflicts are expected once #22930  is merged.

Test can be done using run 314029, acquired this morning in Global Run

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by perrotta** [comment]
backport of #22915

**Comment by forthommel** [comment]
Timeout with `21234.0`.

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- The reco part of this PR is a backport of #22796, identical commit-wise and code-wise to what already merged in the master
- Digis for the timing detectors in the vertical roman pots are created and saved in output: the new product TotemTimingDigiedmDetSetVector_totemTimingRawToDigi_TotemTiming_* is added to the event output (but it is empty for standard workflows),
- Jenkins tests pass

**Comment by perrotta** [comment]
@forthommel : it is easier to backport only this PR, which contains both the digitazion and the DQM updates that you need for the online DQM, and therefore I'd suggest you to close #22930

If you do so, please modify the title of this PR in order to mention also its digitization part

**Comment by arunhep** [comment]
+1

**Comment by perrotta** [comment]
@nminafra : for completeness of information, could you please report here if and when this PR been was (either will be) tested in the online DQM?

**Comment by nminafra** [comment]
@perrotta This PR was implemented on the online DQM and used during the alignment run. The run numbers are from 314178 to 314278. The tests were mostly successful and we are preparing a "small" bugfixing PR and DQM PR that reduces the size of the plots. They will come as soon as possible and for sure before the beginning of May.

**Comment by ggovi** [comment]
+1

**Comment by dmitrijus** [comment]
+1

The master will have to be merged first. Also, we are running **this** PR online and it works fine.

**Comment by slava77** [comment]
> we are preparing a "small" bugfixing PR and DQM PR that reduces the size of the plots. They will come as soon as possible and for sure before the beginning of May.

May has already started. I'm curious about the status of these updates.

**Comment by nminafra** [comment]
@slava77 indeed, it is basically ready. However I'm waiting for #23101 to be reviewed so i can push the updated DQM which is also using TotemTimingRecHits. I'm not sure if it is better to push the new code here or if it is better to issue a new PR and close this one.

**Comment by fabiocos** [comment]
unhold

scenario D19 is now fully unaffected, as it should be. All the reported differences are concentrated in scenario D21, for which a change of the volume file structure is present, but is expected to leave the detector description unchanged. I assume though that the event navigation history could be affected, causing differences. I am performing a larger statistics check on this

**Comment by nminafra** [comment]
@fabiocos this backport was aligned with master when it was created, now we are waiting for instruction (as asked also by mail by Valentina) to:
- update this PR and backport all relevant code (#22796, #22915, #23101, #23198)
- close this PR and open a new PR for a single backport (#22796, #22915, #23101, #23198)
- close this PR and open one backport per PR.

What is the best way?

Thanks a lot,
Nicola
@forthommel

**Comment by fabiocos** [comment]
@nminafra I believe that the second option may make easier for reviewers to cross check the backprot, and in general may make more clear the real status of things. If this PR is effectively the combination of #22915 and #22796 without additions/modifications I would say it can stay as it is, but please update the description to reflect it. For the other PRs I would suggest separate backports. As this PR is changing the event contet, we need to agree on a moment when to do it because this has an impact on  data taking (change of prompt-reco version)

**Comment by forthommel** [comment]
Many thanks for your suggestion, @fabiocos ! We were just trying to make sure the backport to the 10_1_X development branch was indeed required before triggering this extra work for you.
I will then submit a new combined backport PR and leave @nminafra to close this one, if that works for you @fabiocos @slava77 @perrotta ?

**Comment by fabiocos** [comment]
@forthommel sorry, may be I was not clear: please DO NOT close this PR, and please submit separate backports for the PRs whose backport is not included here

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by forthommel** [comment]
Rebase ongoing...

**Comment by forthommel** [comment]
Done! This backport should now be in-sync with #22796+#22915.

**Comment by perrotta** [comment]
please test

**Comment by forthommel** [comment]
We will close this backport attempt and start from a fresh environment now (the PR structures was sufficiently messy not to have the backports one defined the same way...)

**Comment by forthommel** [comment]
Superseded by #23352

**Comment by pphogat** [comment]
@nminafra It was getting failed so removed it from playback.

**Pull request closed without merging**
