### PR TITLE
update POWHEG EmissionVeto1 for WGamma special case

### PR DESCRIPTION
**Pull request by AndrewLevin**
This pull request follows up on [this](https://github.com/cms-sw/genproductions/pull/1879) pull request from the genproductions repository. 

The case of POWHEG WGamma is special because W+0/1 jets and WGamma+0/1 jets are generated at the same time. In order to avoid a crash that occurs because the number of final state particles is inconsistent with the user-set nFinal variable, a new nFinalMode has been created. The new nFinalMode causes a different check to be done on the number of final state particles.

The logic to set the variable ptHard does not correctly handle this special case, so an exception is called if the new nFinalMode is selected and pThardMode is not set to 0.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@qliphy @AndrewLevin do I understand that nFinal == 3 was not used so far? How was this addition practically tested?

**Comment by qliphy** [comment]
@fabiocos  The detailed discussions can be checked here https://github.com/cms-sw/genproductions/pull/1879  , including also feedback from the authors

@AndrewLevin  may provide more info.

**Comment by AndrewLevin** [comment]
@fabiocos, yes, I have tested that nFinalMode = 3 runs without crashing and the results are physically reasonable

**Pull request merged**
