### PR TITLE
L1T ZDC and uGT Emulator Backport

### PR DESCRIPTION
**Pull request by cfmcginn**
The text below is taken from the merged PR to CMSSW_13_3_X, here:
https://github.com/cms-sw/cmssw/pull/42634

This is a backport to CMSSW_13_2_X as the release for HI datataking

#### PR description:

PR for L1Trigger ZDC emulation, for upcoming heavy ions datataking. L1Trigger/L1TZDC pkg added containing L1TZDCProducer which puts ZDC based EtSum into the event, which can be picked up in trigger emulation and cut on as with any other EtSum object. New EtSum IDs are added for ZDCP and ZDCM (plus and minus). Additional PR from @elfontan interfacing this PR w/ the Global trigger has since been incorporate here (PR https://github.com/cms-sw/cmssw/pull/42635 , now closed; some of the detail in that PR is now incorporated here as of 2023.08.29). This includes an update of the uGT emulator for new ZDC triggers included in the Heavy Ion menu for the 2023 data-taking. The implementation relies on new developments included in the [utm libraries v0_11_0](https://globaltrigger.web.cern.ch/globaltrigger/release/utm/latest_doc/html/releaseNotes/v0_11_0.html).

The main changes are the following:

- The L1Trigger/L1TZDC area containing plugins L1TZDCProducer and L1TZDCAnalyzer, former for producing etSums and the latter primarily used in validation of Produce in comparisons w/ etSums checked offline
- The TriggerMenuParser is adapted to parse the new ZDCPlus and ZDCMinus conditionTypes from the xml menu. A dedicated parsing function parseZdcEnergySum is included to relate these objects to the new ZdcEnergySumTemplate.
- The GlobalBoard is updated to receive a new category of objects similar to the EtSum from the CaloLayer2 coming from the new ZDC Producer included in
- https://github.com/cms-sw/cmssw/pull/42634.
- A dedicated ZdcEnergySumTemplate and a ZdcEnergySumCondition class are developed for checking the EtSum threshold on the ZDC objects.
- Addition of condZdcEnergySum to avoid conflicts with existing condEnergySum
- The ste of input tags to the L1TGlobalProducer is updated in simGtStage2Digis_cfi.py.

The following L1Ntuples workflows are also updated to include the new input tags for ZDC objects:
- L1NtupleEMU_cff.py
- L1NtupleRAW_cff.py
- l1UpgradeTree_cfi.py

#### PR validation:

Emulator output validated against offline ZDC Et Sum calculations ( @hjbossi ) :
[ZDCEmulationValidation.pdf](https://github.com/cms-sw/cmssw/files/12413042/ZDCEmulationValidation.pdf)

The following suite of tests were done after successful build
```
scram b runtests
scram build code-checks
scram build code-format
```
All tests passed

Tagging a few additional users to watch this PR: @ginnocen @icali @elfontan @hjbossi

### CODE REVIEW

**Comment by aloeliger** [comment]
Backport of #42634

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test with https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/23

**Comment by aloeliger** [comment]
+l1

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/8678

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
urgent

**Comment by malbouis** [comment]
urgent

- this is needed for testing HLT menus online

**Comment by smuzaffar** [comment]
@antoniovilela , please do not forget to integrate the externals PR needed for this ( e.g. in this case https://github.com/cms-sw/cmsdist/pull/8678 should have been integrated at the same time ). Anyway , I have merged https://github.com/cms-sw/cmsdist/pull/8678 now

**Pull request merged**
