### PR TITLE
Add NanoAOD flavours parameter to PromptReco

### PR DESCRIPTION
**Pull request by germanfgv**
#### PR description:

Adds the capacity to specify flavours for NanoAOD in PromptReco 

#### PR validation:
Using the updated `RunPromptReco.py` with `--nanoFlavours=@PHYS+@MUPOG`, ConfigBuilder shows the proper flavours:
```
$ python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario=ppEra_Run3_2023 --reco --aod --miniaod --nanoaod --dqmio --global-tag 140X_dataRun3_Prompt_v2 --lfn=file:/eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2024/Muon0/RAW/v13033023/000/369/998/00000/0181983c-310f-4b2e-8d66-57d58a3bf1c1.root --PhysicsSkims=ZMu+EXODisappTrk+LogError+LogErrorMonitor+EXOCSCCluster+EXODisappMuon --nanoFlavours=@PHYS+@MUPOG
Retrieved Scenario: ppEra_Run3_2023
...
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: ALCAPRODUCER Spec: ['@allForPrompt']
Step: SKIM Spec: ['ZMu', 'EXODisappTrk', 'LogError', 'LogErrorMonitor', 'EXOCSCCluster', 'EXODisappMuon']
Step: PAT Spec: 
Step: NANO Spec: ['@PHYS', '@MUPOG']
in prepare_nano @PHYS+@MUPOG
Step: DQM Spec: 
...
```
Here without `--nanoFlavours`:
```
$ python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario=ppEra_Run3_2023 --reco --aod --miniaod --nanoaod --dqmio --global-tag 140X_dataRun3_Prompt_v2 --lfn=file:/eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2024/Muon0/RAW/v13033023/000/369/998/00000/0181983c-310f-4b2e-8d66-57d58a3bf1c1.root --PhysicsSkims=ZMu+EXODisappTrk+LogError+LogErrorMonitor+EXOCSCCluster+EXODisappMuon                            
Retrieved Scenario: ppEra_Run3_2023
...
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: ALCAPRODUCER Spec: ['@allForPrompt']
Step: SKIM Spec: ['ZMu', 'EXODisappTrk', 'LogError', 'LogErrorMonitor', 'EXOCSCCluster', 'EXODisappMuon']
Step: PAT Spec: 
Step: NANO Spec: 
in prepare_nano nanoSequence
Step: DQM Spec: 
...
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_14_0_X
Backport: #44454

### CODE REVIEW

**Comment by mmusich** [comment]
should this functionality be added to the `Configuration/DataProcessing` unit tests?

**Comment by germanfgv** [comment]
> should this functionality be added to the `Configuration/DataProcessing` unit tests?

You are probably right. I'll do so.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
ping bot

**Pull request merged**
