### PR TITLE
use standard libuuid functions, add binary uuid option

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

The EDM Guid class was derived from POOL source that apparently dates back to the COM/DCE days before UUIDs were standardized and before the general availability of libuuid.  Most of the functionality of the Guid class is now available from libuuid.  This PR

1) Replaces most of Guid.cc with calls to libuuid (we're linking to it, we might as well use it).
2) Changes the internal representation of the Guid class to the libuuid uuid_t type.
3) Adds an option to load and store an edm Guid as a 16 byte binary string instead of the 32 byte printable representation normally used (std::string can contain null characters so long as c_str() isn't called).
4) Adds an option to use ::uuid_generate_time() to generate UUIDs, and defaults to ::uuid_generate() instead of ::uuid_generate_random().  uuid_generate() defaults to uuid_generate_random(), but has better fallback behavior in the (unlikely) event that /dev/urandom is unavailable.
5) Uses the binary representation for the ProcessGUID stored with every event in the EventAuxiliary record.  An audit of the code shows that we never print the ProcessGUID nor do we otherwise rely on the string representation.
6) Reverses the sense of the '<' comparison operator to match the standard definition (it could probably be removed--I don't think we ever use it).

#### PR validation:

A standard limited matrix was run, and the Guid unit test was updated to test the new functionality.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
> 5\. Uses the binary representation for the ProcessGUID stored with every event in the EventAuxiliary record.  An audit of the code shows that we never print the ProcessGUID nor do we otherwise rely on the string representation.

How is the ProcessGUID accessed currently then? Is it perhaps something along "by default not accessed, available for debug use"?

**Comment by dan131riley** [comment]
> > 5. Uses the binary representation for the ProcessGUID stored with every event in the EventAuxiliary record.  An audit of the code shows that we never print the ProcessGUID nor do we otherwise rely on the string representation.
> 
> How is the ProcessGUID accessed currently then? Is it perhaps something along "by default not accessed, available for debug use"?

@makortel The only place it is used is in the `edm::isSameEvent()` function,

https://github.com/cms-sw/cmssw/blob/9308c4dcd88414e6d55069443c42df1121a0175d/DataFormats/Provenance/src/EventAuxiliary.cc#L15-L19

which is used in the PoolSource as part of the check that, in the two-file case, an event from the secondary file came from the same source as the event in the primary source with the same EventID:

https://github.com/cms-sw/cmssw/blob/abc9134327fff8fbb378b3c81a56c5850195a9bb/IOPool/Input/src/PoolSource.cc#L45-L50

I think this is mostly for simulated data where it is possible to have events with the same EventID that actually aren't from the same underlying event (I still have an open question whether this check makes any sense for real data, or if we could just hardwire the ProcessGUID to a fixed value for real data).  It used to be useful for debugging data from misbehaving systems, but it isn't usable for that since we switched to fully random UUIDs.  Some details here https://github.com/cms-sw/cmssw/pull/30949#issuecomment-696346960

**Comment by wddgit** [comment]
I don't think this is a problem, but just wanted to note that this also will affect the ID written by the output modules here:

 https://cmssdt.cern.ch/lxr/source/IOPool/Output/src/RootOutputFile.cc#0178

And this is something different than the one in EventAuxilliary and might or might not end up getting used in the ProcessBlock work I am doing.

**Comment by dan131riley** [comment]
> I don't think this is a problem, but just wanted to note that this also will affect the ID written by the output modules here:
> 
> https://cmssdt.cern.ch/lxr/source/IOPool/Output/src/RootOutputFile.cc#0178

createGlobalIdentifier() will still default to the standard ASCII string representation, this PR switches only the ProcessGUID to the binary representation.  (The fileID gets written to the FJR, so it has to stay readable.)

**Comment by makortel** [comment]
> The only place it is used is in the `edm::isSameEvent()` function,

Thanks, and there the `a.processGUID() == b.processGUID()` does not have to care whether the `processGUID()` holds a textual or binary representation.

**Comment by makortel** [comment]
@cmsbuild, please test

Let's refresh, then I'll sign.

**Comment by makortel** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
