### PR TITLE
Restore DQM live clients process names

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR restores the DQM live clients process names which were erroneously all changed to `BeamMonitor` in #39988.
Clients fixed:
 - beam_dqm_sourceclient-live_cfg.py
 - beamfake_dqm_sourceclient-live_cfg.py
 - beamhlt_dqm_sourceclient-live_cfg.py
 - beamhltfake_dqm_sourceclient-live_cfg.py
 - beampixel_dqm_sourceclient-live_cfg.py
 - physics_dqm_sourceclient-live_cfg.py
 - pixel_dqm_sourceclient-live_cfg.py
 - pixellumi_dqm_sourceclient-live_cfg.py

I profit of this PR to also remove the `sistriplas_dqm_sourceclient-live_cfg.py` client which has not been used since Run 1 as suggested in [this comment](https://github.com/cms-sw/cmssw/pull/39975#discussion_r1014156936) (FYI @cms-sw/tracking-pog-l2). 

#### PR validation:
None - as this is a simple bugfix of names

#### Backport:
Not a backport. No backport needed.

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
