### PR TITLE
Backport to 12_2_X: ECAL TPG Parameter Builder changes for double weights

### PR DESCRIPTION
**Pull request by valsdav**
This is a backport of PR #36446 needed to propagate the changes to the CMSSW version currently available for tests in P5. 

## PR description:

The ECALTPGParamBuilder code computes the parameters for the ECAL Trigger Primitives (TP) configuration, including pedestals, weights and transparency calibrations.
This PR introduces the necessary changes to include the double weights configuration in the configuration scripts.
Moreover the code has been revised to include some additional cross-checks for problematic crystals. The weights configuration can be now read from files and not only computed from the pulse shapes.

The necessary OnlineDB, CondDB and trigger emulator changes for the double weights mechanism have been already included in previous PRs : #33220, #33349, #33748

## PR validation:

The full chain of ECAL TP configuration has been tested during the extended MWGR in November. The BEAMV7 key has been created in the OnlineDB by the configuration script and tested in global run.
A description of the double weight mechanism and related DB classes has been given at the Alca meeting and can be found here: https://indico.cern.ch/event/1020767/#16-new-ecal-tpg-db-classes-for

### CODE REVIEW

**Comment by valsdav** [comment]
backport of #36446

**Comment by francescobrivio** [comment]
backport of #36446

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+1

 - backport of #36446
 - all tests pass except for the known issue with `4.76`

**Comment by tvami** [comment]
Hi @valsdav can you please include the string "12_2_X" in the PR title to see where this is a backport to?

**Comment by tvami** [comment]
Also @valsdav is this relevant for Cosmics? 12_2 is only to be used for Feb cosmics, so I'm not sure we really need this backport at all

**Comment by valsdav** [comment]
> Also @valsdav is this relevant for Cosmics? 12_2 is only to be used for Feb cosmics, so I'm not sure we really need this backport at all

Hi @tvami, this is needed indeed to be able to test the ECAL Trigger configuration setup in P5 during the Cosmics run in February.

**Comment by qliphy** [comment]
merge

**Pull request merged**
