### PR TITLE
Adds muon shower triggers for MC data

### PR DESCRIPTION
**Pull request by nabrandman**
#### PR description:

Implements HMT triggers in test vector code with MC data files for uGT emulator in master.

No changes are expected to the output.

This PR does not depend on any other PRs or externals.

#### PR validation:

Performed runTheMatrix with -l 11634.0, passed 5 out of 5 tests. Test vector code was also validated with firmware and was shown to be equivalent.

Changes were checked against "scram build code-format" to ensure they followed CMS Naming, Coding and Style Rules.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport.

### CODE REVIEW

**Comment by elfontan** [comment]
This PR has been validated via test vectors with the firmware group.

**SETUP for producing test vectors**:
cmsrel CMSSW_14_0_6
cd CMSSW_14_0_6/src
cmsenv
git cms-init
git cms-addpkg L1Trigger/L1TGlobal
mkdir -p L1Trigger/L1TGlobal/data/Luminosity/startup
cd L1Trigger/L1TGlobal/data/Luminosity/startup
wget https://raw.githubusercontent.com/cms-l1-dpg/L1MenuRun3/master/development/L1Menu_Collisions2024_v1_2_0/L1Menu_Collisions2024_v1_2_0.xml
cd -

**SCRIPT for producing test vectors**:
cp test/runGlobalFakeInputProducer.py
cmsRun runGlobalFakeInputProducer.py

**_Set of files:_**
```
/store/relval/CMSSW_14_0_1/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/140X_mcRun3_2024_realistic_v4_PU_AlpakaVal_AlpakaDeviceVSHost-v14/50000/34ae12a4-2d90-4d5d-b24\
3-e949af0952ae.root                                                                                                                                                 
/store/relval/CMSSW_14_0_1/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/140X_mcRun3_2024_realistic_v4_PU_AlpakaVal_AlpakaDeviceVSHost-v14/50000/5c08de0e-0571-4792-aa3\
7-1b7d1915dbda.root                                                                                                                                                 
/store/relval/CMSSW_14_0_1/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/140X_mcRun3_2024_realistic_v4_PU_AlpakaVal_AlpakaDeviceVSHost-v14/50000/1aed742b-2f48-4cc3-875\
8-24153c38c79b.root                                                                                                                                                 
/store/relval/CMSSW_14_0_1/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/140X_mcRun3_2024_realistic_v4_PU_AlpakaVal_AlpakaDeviceVSHost-v14/50000/096ba83b-620d-449d-a40\
8-ebb209b54d76.root
```

**_Countings:_**
| L1 Bit | Simulation | Firmware |
| -- | -- | -- |
| L1_TwoMuShower_Loose | 1811 | 1811 |
| L1_SingleMuShower_Nominal | 1727 | 1727 |
| L1_SingleMuShower_Tight | 1768 | 1768 |

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
