### PR TITLE
[SiStrip-DQM] Reduce the number of bins in the Eloss histograms

### PR DESCRIPTION
**Pull request by ptrstn**
Hello,

@dmitrijus , @jfernan2 , I am a new SiStrip-DQM Developer (@boudoul FYI)

I reduced the number of bin in the SiStrip Eloss histograms, since the number was previously way too high.

### CODE REVIEW

**Comment by boudoul** [comment]
Hello @dmitrijus , @jfernan2 , I confirm that @ptrstn is working for me (Tracker DPG) - thanks

**Comment by jfernan2** [comment]
please test

**Comment by schneiml** [comment]
Hi @ptrstn, and welcome to the DQM world! The right place to make yourself a proper DQM developer is the contacts page [0] where you should be able to add yourself to the right e-groups.

Also, feel free to pass by the core-DQM meeting on tuesdays [1]. We'd like subsystem developers to come there to know what you are working on, before we get confronted with the PRs. There is not much to talk about for this PR, but since Tracker DQM tends to have quite a lot of requests, we want you there rather sooner than later.

[0] https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Tracker_SiStrips_and_Pixels
[1] https://indico.cern.ch/event/719755/

**Comment by boudoul** [comment]
Thanks @schneiml , maybe you could then ask your colleagues to review and sign this PR ?

**Comment by schneiml** [comment]
@boudoul the usual procedure for small PRs (like this) is that they will be processed once per week, around the ORP. For things that might require discussion, please e-mail cms-dqm-coreTeam@cern.ch (github notifications won't work reliably) and probably come to the core-DQM meeting (this is sth. we want to require this year).

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

welcome optimization

**Pull request merged**
