### PR TITLE
Extended SimpleMemoryCheck to print RSS info to the logger

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The service now prints both VSize and RSS info in its summary.

#### PR validation:

A test job shows the new output.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
- This PR extends the printout of SimpleMemoryCheck, without modifying any object in the Event: therefore it can be merged in 13_0_X even before switching the master to 13_1_X, to make it already available also in 13_0_X

**Comment by makortel** [comment]
I suspect this PR caused the `GeometryTrackerGeometryBuilderTestDriver` test to fail
```
===== Compare Tracker Parameters for DD and DD4hep ====
The output diff is 932:
72c72
< MemoryReport> Peak virtual size 794.656 Mbytes
---
> MemoryReport> Peak virtual size 713.266 Mbytes
76c76
< [1] run: 1 lumi: 1 event: 1  vsize = 794.656 deltaVsize = 0 rss = 215.047 delta = 0
---
> [1] run: 1 lumi: 1 event: 1  vsize = 713.266 deltaVsize = 0 rss = 158.809 delta = 0
81,82c81,82
< [1] run: 1 lumi: 1 event: 1  vsize = 794.656 deltaVsize = 0 rss = 215.047 delta = 0
< MemoryReport> Peak rss size 215.047 Mbytes
---
> [1] run: 1 lumi: 1 event: 1  vsize = 713.266 deltaVsize = 0 rss = 158.809 delta = 0
> MemoryReport> Peak rss size 158.809 Mbytes
86c86
< [1] run: 1 lumi: 1 event: 1  vsize = 794.656 deltaVsize = 0 rss = 215.047 delta = 0
---
> [1] run: 1 lumi: 1 event: 1  vsize = 713.266 deltaVsize = 0 rss = 158.809 delta = 0
89c89
< [1] run: 1 lumi: 1 event: 1  vsize = 794.656 deltaVsize = 0 rss = 215.047 delta = 0
---
> [1] run: 1 lumi: 1 event: 1  vsize = 713.266 deltaVsize = 0 rss = 158.809 delta = 0
Failure comparing Tracker Parameters for DD and DD4hep: status 255
status = 65280

---> test GeometryTrackerGeometryBuilderTestDriver had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_13_0_X_2023-02-13-1100/unitTestLogs/Geometry/TrackerGeometryBuilder#/

The proper fix would be to make the test either not use the `SimpleMemoryCheck` service, or ignore its output in the comparison.

**Pull request merged**
