### PR TITLE
Drop Type in toModify for DTDQM

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Update the safer syntax for existing parameter in toModify and assignments

As suggested here: #33659 (review)

#### PR validation:

runTheMatrix -l limited

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by smuzaffar** [comment]
@jfernan2 , could this be the change which caused two DQM unit tests to fail in IB https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-06-16-2300/unitTestLogs/DQM/Integration#/ ,  can you please check?

**Pull request merged**
