### PR TITLE
Fix inputLabel of new DTuROS unpacker

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix inputLabel of new DTuROS unpacker
c.f. #21474

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
Fixes the problem in TSG tests discussed in #21474

**Comment by perrotta** [comment]
+1
- It does the job, and fixes the exception in the TSG jobs which reads repacked data
- I think however that a more complete fix should include, in addition, what in https://github.com/cms-sw/cmssw/pull/21474#issuecomment-354954653

**Comment by davidlange6** [comment]
merge

**Pull request merged**
