### PR TITLE
Phase2-hgx229 Update xml files to accommodate some implementation of partial wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Step toward implementation of partial wafers. Modification to xml files for HGCal and HFNose. The changes has no effect on existing workflows. Since it is for Phase2 for which no payload is made for DB, these changes are safe.

#### PR validation:

Tested using standard runTheMatrix.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda: Please add to the PR description the impact of these XML changes to existing payloads, or note that there is no effect.

**Comment by bsunanda** [comment]
@cvuosalo I modified the description.  The changes has no effect on any workflows or any payloads

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
