### PR TITLE
Add workflow to cross run number boundaries in IB tests

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

PR #28214 implemented workflow 250202.183, which was the only workflow that would cross run boundaries for tests of run-dependent MC. It was removed a few months later when run-dependent workflows were "cleaned up" in PR #29457. Other run-dependent workflows are intended for use with full relvals and so many lumiblocks must be crossed before changing the run number. Since AlCa would like to foster further development of run-dependent MC, it is very useful to test that IOV boundaries can be crossed in MC without crashing, and I would like to have this workflow back.

I also added an autoCond key `phase1_2018_realistic_rd` with a value corresponding to a MC GT for 2018 run-dependent MC. The time-dependent relvals have been updated to use this key rather than conditions overrides.

#### PR validation:

After running `runTheMatrix.py -l 250202.183`, I checked that the DIGI-PREMIX and RECO files contain events with two different run numbers:

- Run 315257: events 1-5
- Run 316083: events 6-10

This is the expectation given the configuration.

`runTheMatrix.py -l 250202.182` also completes successfully.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and should not be backported.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 250202.183

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 250202.182, 250202.183

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

From [the logs for step 2 of workflow 250202.183](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e8c6ab/12743/runTheMatrix-results/250202.183_TTbar_13UP18_RD+TTbar_13UP18_RD+DIGIPRMXUP18_PU25_RD_IB+RECOPRMXUP18_PU25_RD+HARVESTUP18_PU25_RD/step2_TTbar_13UP18_RD+TTbar_13UP18_RD+DIGIPRMXUP18_PU25_RD_IB+RECOPRMXUP18_PU25_RD+HARVESTUP18_PU25_RD.log), we see that the IOV boundary is crossed at the expected location:
```
Begin processing the 5th record. Run 315257, Event 5, LumiSection 1 on stream 0 at 05-Feb-2021 20:38:33.889 CET
Begin processing the 6th record. Run 316083, Event 6, LumiSection 2 on stream 0 at 05-Feb-2021 20:38:51.571 CET
```

**Comment by srimanob** [comment]
+Upgrade

@christopheralanwest 
Do you intend to run 250202.183 in IB? How to add it? Thanks.

**Comment by chayanit** [comment]
+1 

the same questions as @srimanob, where would you add 250202.183 in IB?

**Comment by qliphy** [comment]
+1

**Pull request merged**
