### PR TITLE
Updates to relvals

### PR DESCRIPTION
**Pull request by fabozzi**
Some updates to relvals:
- adding a harvesting step to the 2-input relval workflow (RunHLTPhy2017B_RAWAOD)
- adding a NANOAOD wf on data miniAODv2 input (in addition to the MC wf)

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.7803,136.7952

**Comment by fabozzi** [comment]
please test workflow 136.7803,136.7952

**Comment by fabozzi** [comment]
please test workflow 136.7803,136.7952

**Comment by fabiocos** [comment]
please test workflow 136.7803,136.7952

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
