### PR TITLE
Remove unused RecoHI/HiEgammaAlgos python configurations

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Follow up of issue #28632 , removing configurations that seem obsolete since a decade. @mandrenguyen should confirm there is no residual use of these configurations in the HI community.

#### PR validation:

All the HI related tests of the short matrix run smoothly.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by mandrenguyen** [comment]
@fabiocos I know of no use for these ancient scripts.

**Comment by perrotta** [comment]
+1
- Old and apparently unused (as confirmed by HI) scripts removed
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
