### PR TITLE
make Pythia8Interface compatible with DIRE 2.004

### PR DESCRIPTION
**Pull request by mkirsano**
#### PR description:

make Pythia8Interface compatible with DIRE 2.004 in order to upgrade pythia8 to 243. To be tested together with PR cmsdist #5311

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
@mkirsano @mrodozov what is the timescale to finalize this update? Can this converge within a few days, or does it require more? I understand that some patches should be added to the new external version, am I correct?

**Comment by mkirsano** [comment]
@fabiocos @mrodozov In any case this week (I am busy and travelling until late Wednesday). Remains to make the same corrections as for 240. It can be made in git after putting there 243 (I have never done this) or I can do it by a traditional patch.

**Comment by fabiocos** [comment]
@mkirsano @qliphy @agrohsje what is the status of this update?

**Comment by mkirsano** [comment]
@smuzaffar did you apply the patches to pythia8 243 in git? If yes, it should be OK. Is the gen signature needed? @qliphy @agrohsje

**Comment by smuzaffar** [comment]
@mkiani , yes I did see https://github.com/cms-externals/pythia8/commits/cms/243 and 
https://github.com/cms-externals/pythia8/commits/cms/240

**Comment by fabiocos** [comment]
code-checks

**Comment by mkiani** [comment]
> https://github.com/cms-externals/pythia8/commits/cms/240

I think this doesn't concern me, wrongly tagged.

**Comment by smuzaffar** [comment]
that is correct Bilal, please feel free to unsubscribe yourself from this issue.

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#5311

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#5311

**Comment by fabiocos** [comment]
@qliphy @agrohsje @mkirsano so what is the plan of the GEN group about this new version? Do you consider it as ready for integration in CMSSW_11_0_0?

**Comment by qliphy** [comment]
@mkirsano @agrohsje will comment more.      Yes, the plan is not for UL but for future needs.  This is to include new Pythia8 v243 and test Dire/Vincia

**Comment by fabiocos** [comment]
@qliphy @agrohsje @mkirsano well, if this should enter for HLT TDR, we need an urgent feedback

**Comment by mkirsano** [comment]
I think it is ready. Merge is needed for more detailed tests of DIRE.

**Comment by fabiocos** [comment]
@qliphy @agrohsje @mkirsano so can GEN sign this PR?

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
