### PR TITLE
DT DQM updates for HDQM

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR adds 110 plots to DT DQM folders to improve the HDQM monitoring.

#### PR validation:

Tested with runTheMatrix.py -l limited

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport foreseen

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
Retriggering them since DQM file upload failed due to some cmsweb instabilty

**Comment by jfernan2** [comment]
+1
Changes as expected

**Comment by silviodonato** [comment]
+1

**Pull request merged**
