### PR TITLE
drop --catalog option from edmFileUtil check in unittestinputsource (online DQM unit tests)

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Fixes https://github.com/cms-sw/cmssw/issues/41925 by backporting https://github.com/cms-sw/cmssw/pull/39266

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39266

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
backport of #41926

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
