### PR TITLE
Set nullptr for L1TParticleFlow classes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This avoids an uninitialized data warning in DEBUG build

#### PR validation:

Fixes warning in CMSSW_13_0_DBG_X_2022-12-08-2300.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
