### PR TITLE
[14_0_X] Add possibility to read triggerbits for Secondary Datasets from the GT

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #45092
See master PR for a complete description, here I'm only reporting the GT difference:

**Full GT differences:**
- `run2_data`
  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun2_v1/140X_dataRun2_v2
- `run3_data_prompt`
  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_Prompt_frozen_v1/140X_dataRun3_Prompt_frozen_v3
   - Jump from version `v1` to `v3` since the `v2` GT was never propagated to the release (but it was correctly deployed in production, see comment in https://github.com/cms-sw/cmssw/pull/45092#issuecomment-2141723733), so it additionaly includes the change of the `DropBoxMetadataRcd` tag (from `DropBoxMetadata_v8.4_express` to `DropBoxMetadata_v8.5_express`)
- `run3_data`
  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_v3/140X_dataRun3_v4
- `run3_data_PromptAnalysis`
  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_PromptAnalysis_v1/140X_dataRun3_PromptAnalysis_v2

#### PR validation:
See master PR.

#### Backport:
backport of #45092

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45092

**Comment by francescobrivio** [comment]
test parameters:

 - workflow = 141.114

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@francescobrivio can you please post a comprehensive diff of the GT changes as customary when `autoCond.py` is updated?

@cms-sw/alca-l2 it's not entirely clear why for example for this PR is let to the author to change also `autoCond` in the same PR that consumes said change, but for example [here](https://github.com/cms-sw/cmssw/pull/44073#issuecomment-1962900027) it wasn't.

**Comment by mmusich** [comment]
> DQMHistoTests: [Total failures: 2601](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-05-31-1100+3b8fcc/62995/validateJR.html)

Are all of these understood from the GT changes?

**Comment by perrotta** [comment]
> > DQMHistoTests: [Total failures: 2601](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-05-31-1100+3b8fcc/62995/validateJR.html)
> 
> Are all of these understood from the GT changes?

2574 of them are from the well known 12834.7 MkFit workflow
What I am puzzled about, instead, are the differences in the SiStrip BadComponents and Ecal Endcap timing projections in wfs 141.X: what is their origin?
The same also happens in the master PR: let me copy the comment also over there.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by perrotta** [comment]
+alca
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/45092
- Differences in the DQM comparisons for the SiStrip BadComponents and for the Ecal Endcap timing projections in the workflows 141.X can be explained by the different IOVs (also for the 2023) in the reference and targed GTs used in step 4 of those workflows, see https://github.com/cms-sw/cmssw/pull/45092#issuecomment-2152356470 and previous entries in that thread
- The master version of this PR was merged only last night: therefore the IB tests are not yet available. I'm "blindly" signing this PR for the sake of speeding up integration in the possible forthcoming CMSSW_14_0_9 release, assuming that the release managers will verify themselves that there are no issues in those IB tests originated by this PR before merging it.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
