### PR TITLE
DD VecGeom Test

### PR DESCRIPTION
**Pull request by ianna**
* Add a VecGeom test

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
@ianna this looks quite small as a new package. Do you envisage a further development for it?

**Comment by ianna** [comment]
@fabiocos - yes, this is an alternative to DD4hepbased on VecGeom package.

**Comment by kpedro88** [comment]
@ianna can you make the PR to cms-bot to add this new package in the geometry category?

**Comment by mrodozov** [comment]
it's in geometry now

**Comment by ianna** [comment]
@mrodozov - thanks!

+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
