### PR TITLE
updating relvals strings

### PR DESCRIPTION
**Pull request by prebello**
this PR is made to update FullSim and FastSim strings in 10-5-X cycle

FYI @fabiocos

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by prebello** [comment]
please test

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 25400.18,250400.18

**Comment by fabiocos** [comment]
@kpedro88 any comment? Otherwise I would like to merge it to solve the issue of the crashing tests

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@kpedro88 the updated relvals are not upgrade specific, I move forward to see whether all issues are resolved as expected, in case please sign it for reference or comment for possible further updates

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
