### PR TITLE
Fix multiple booking

### PR DESCRIPTION
**Pull request by pohsun**
Fix multiple booking issue for histograms.

### CODE REVIEW

**Comment by VinInn** [comment]
Something when wrong here!

**Comment by pohsun** [comment]
Hi,
      Seems that I misunderstood something.
      Let me explain.... Base on the nightly build of CMSSW_7_5_X. I add
just few lines in DQM/HcalMonitorClient to fix the issue. And the tracker
offline shift leader (F. Fiori) suggest me to update this fix to
CMSSW_7_[345]. Is this not the correct way to make a pull request from
other branches based on 75X?

Po-Hsun

2015-04-29 17:03 GMT+02:00 Vincenzo Innocente <notifications@github.com>:

**Comment by danduggan** [comment]
@pohsun, i'd like to see this tested in 75x before you backport. we can meet later to go over best practices when backporting then :)

**Comment by pohsun** [comment]
Close this PR because of wrong merge.

**Comment by pohsun** [comment]
Hi,
      Thanks for guiding. I just got some help for backport from
experienced college, so I cancel this PR.

Po-Hsun

2015-04-29 17:25 GMT+02:00 danduggan <notifications@github.com>:

**Pull request closed without merging**
