### PR TITLE
Fix headers for check-headers errors reported in PR 27841

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Fix for the issues with ```scram b check-headers``` reported in #27841

#### PR validation:

```scram b check-headers``` errors are solved, the code compiles correctly

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@santcch @qliphy @agrohsje please check, it is just a technical fix

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
