### PR TITLE
Fix the `ThroughputService` and `FastTimerService` DQM folders [12.5.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Include the information about whether Simultaneous Multi Threading (SMT) is enabled or disabled after the processor model name.

Fix the DQM folder used by the `ThroughputService` to take into account the processor model name (and the SMT status) if the corresponding flag is enabled.

#### PR validation:

The processor model name and the SMT status not appear correctly in the DQM folder names for the `FastTimerService` and `ThroughputService`:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40062 to 12.5.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #40062

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
