### PR TITLE
Fixes for PPS geometry on Pixel sensors and materials

### PR DESCRIPTION
**Pull request by diemort**
#### PR description:

This PR addresses a few minor corrections on the PPS geometry in the Pixel sensors and complies the material names in the reco geometry as stated in #34927. The position of the Silicon wafers has been move down to 250um w.r.t. the bottom foil and the envelopes with sensors ad flexible cables has been enlarged to avoid volume overlaps. Besides, the U shape of the Aluminum supports has been changed to a plain squared piece. A detailed list of the file changes and visualization of the new changes in the Pixel sensors is given in this [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/PPSPixelGeometryFix1210pre2).

Includes updated on both DDD and dd4hep files as well as a new entry in dict2021Geometry.py named P7 with the latest geometry XML files.

#### PR validation:

The new changes in the geometry have been validated with the full CMS geometry dump for visualization and overlap check with tolerance 0.01, plus direct and full simulation to confirm hits in both pixel and timing detectors. The position of the pixel sensors have been checked with direct simulation [here](https://twiki.cern.ch/twiki/bin/view/CMS/PPSPixelGeometryFix1210pre2#Comparisons_on_pixel_distance).

All changes follow the Naming Rules for new XML files in geometry.
All workflow tests done.

FYI @fabferro @jan-kaspar

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@AdrianoDee, @srimanob , we agreed today to push this PR needed for geometry scenario.

**Comment by AdrianoDee** [comment]
+Upgrade
As discussed today at the meeting. Only a rebase of #35346.

**Comment by perrotta** [comment]
+1

**Pull request merged**
