### PR TITLE
remove unused fwd headers in DataFormats/TrackerRecHit2D  

### PR DESCRIPTION
**Pull request by davidlange6**
(good thing, as you cant forward declare type defs like this)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test


On 1 Sep 2020, at 21:04, cmsbuild <notifications@github.com> wrote:

﻿

+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-31312/18068

  *   This PR adds an extra 16KB to repository

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31312	a8b37a3 
- technical; compiles

**Comment by qliphy** [comment]
+1

**Pull request merged**
