### PR TITLE
L1TOffline DQM - add efficiency flag to efficiency ME - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Add efficiency flag to L1T offline DQM efficiency ME to avoid plots being normalised in the GUI.

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #20923

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
