### PR TITLE
Always set the thread stack size when configuring TBB, even if the number of threads is not specified (10.3.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Set the thread stack size even if the number of threads is not specified on the command line nor in the `process.options` ParameterSet.

Rewrite the logic handling the number of threads and the thread stack size: now the two parameters should be handle correctly even if one is set on the command line and the other is set in the python configuration.

### CODE REVIEW

**Comment by fwyzard** [comment]
This is needed to prevent a crash when running a module using the acquire/produce semantic with a single thread.

**Comment by fwyzard** [comment]
@makortel @Dr15Jones FYI

**Comment by fwyzard** [comment]
This does fix the crashes observed in the development of the "Patatrack" branch.

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
bugfix

**Comment by fwyzard** [comment]
OK, the minimal fix was actually simpler: just set the thread stack size in the default TBB initialisation.
The 10.2.x backport now does only that, and it still fixes the problem we saw in the Patatrack branch.

I took the opportunity to rewrite the logic handling the number of threads and the thread stack size: now the two parameters should be handle correctly even if one is set on the command line and the other is set in the python configuration.

**Comment by fwyzard** [comment]
@cmsbuild,  please test

**Comment by Dr15Jones** [comment]
+1
clearer logic
the command line still can override the configuration

**Comment by kpedro88** [comment]
+1

**Pull request merged**
