### PR TITLE
a script to check edm class transient member marked transient in root

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar @davidlange6

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
how should we proceed with the idea that this is run as part of the build process?

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones, I am working on it. I need to check how much overhead it will bring in to build time
I am going to update the script so that it can accept multiple rootmap files.

**Pull request merged**
