### PR TITLE
Adapting EGRegression Modifiers to 106X and adding V3 modifier: 106X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This updates the code for the E/gamma electron/photon regressions 

#### if this PR is a backport please specify the original PR:

backport of https://github.com/cms-sw/cmssw/pull/26892

### CODE REVIEW

**Comment by Sam-Harper** [comment]
wont work without the GT changes, @christopheralanwest , I assume you can do that? Thanks!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27203	4daff64 (together with https://github.com/cms-sw/cmssw/pull/27205	31c63f2)
- the backport(s) are correct: all file differences are the same here as in the master PRs
- jenkins tests pass and comparisons with the baseline show differences in the same tested workflows as was observed in the master.

**Comment by fabiocos** [comment]
+operations

identical backport of #26892 , update of Eras and StandardSequences is coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
