### PR TITLE
Extended fix of Geant4 tracking

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Improved handling of Geant4 exceptions due to geometry or navigation. Should correctly handle problems reported in #37373 

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
backport from master

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by qliphy** [comment]
@civanch  Thanks!  Do we need a PR for the master (12_4_X)?   Moreover we need a backported PR to 12_2_X.

**Comment by civanch** [comment]
@qliphy , I took things from the master.

**Comment by perrotta** [comment]
backport of #37216

**Comment by qliphy** [comment]
+1

**Pull request merged**
