### PR TITLE
Hcal DQM: Fix the ZDC illegal cast in HCAL offline DQM[13_2_X]

### PR DESCRIPTION
**Pull request by lwang046**
PR description:

Backport of #42919 , fix the issue raised [here](https://cms-talk.web.cern.ch/t/fast-track-validation-hlt-express-new-hcal-electronicsmap-condition/29957/6)

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
type hcal

**Comment by tjavaid** [comment]
backport of #42919

**Comment by mandrenguyen** [comment]
urgent
Needed for data taking

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
