### PR TITLE
Phase2-hgx134 Temporary fix to validation code

### PR DESCRIPTION
**Pull request by bsunanda**
Uses a constant right now. It will be changed to parameter derived from geometry later - needs further work and testing

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by fabiocos** [comment]
please test workflow 24034.0

**Comment by fabiocos** [comment]
@andrius-k @jfernan2 I would like to have this fix in pre1, could you please have a look at it?

**Comment by fabiocos** [comment]
@mrodozov is the comparison job stuck perhaps? It looks pending since 8 hours. Anyway the crashing workflow is now correctly completed, so the basic target of the fix is achieved, although we would like to see the comparison result

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
