### PR TITLE
Run2-alca154 Source code reformatting with clang-format in Calibration/HcalCalibAlgos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Source code reformatting with clang-format in the packageCalibration/HcalCalibAlgos

#### PR validation:

Successfully runs the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR:

No back porting is needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda same comment as for #26450

**Comment by bsunanda** [comment]
@fabiocos I changed the titles

**Comment by fabiocos** [comment]
+1

**Pull request merged**
