### PR TITLE
DyT v2 on up to eta 1p2

### PR DESCRIPTION
**Pull request by clacaputo**
#### PR description:

This PR activate the new threshold parameterization for the DyT algorithm (introduced in #26343 ) only for muons up to eta 1.2, while using the old DyT threshold for eta greater than 1.2.

This choice has been made after validating the new parameterization in all the eta range [link](https://indico.cern.ch/event/820640/)

The PR changes the default flag for selecting the parameterization mode from False to True and modifies `DynamicTruncation::correctThrByPAndEta` adding:

```cpp
std::set<dyt_utils::etaRegion> regionsToExclude = {dyt_utils::etaRegion::eta2p0, dyt_utils::etaRegion::eta2p2,  dyt_utils::etaRegion::eta2p4 };
if ( ! regionsToExclude.count(this->region) ) thr = parametricThreshold();
```

Parameters for `dyt_utils::etaRegion::eta2p0, dyt_utils::etaRegion::eta2p2, dyt_utils::etaRegion::eta2p4` are left in for future development.

#### PR validation:
Validation has been performed using:
```bash
runTheMatrix.py --nThreads=4 -l 10809.0
```
output
```
10809.0_SingleMuPt1000+SingleMuPt1000_pythia8_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Tue May 14 12:50:00 2019-date Tue May 14 12:18:38 2019; exit: 0 0 0 0 0 0
1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 failed
```

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
Validations shown at the [muon POG meeting](https://indico.cern.ch/event/820640/contributions/3430394/attachments/1843219/3023014/20190513_DyT_v2_CMSSW_10_6_X_MuonPOG.pdf) and at the [general PPD meeting](https://indico.cern.ch/event/816361/contributions/3433631/attachments/1845722/3028137/20190516_DyT_v2_CMSSW_10_6_X_PPD.pdf) have demonstrated that this change has some effect on dyt muons in the barrel (where the tails in the distribution of the momenta resolutions decrease), which translates into an almost negligible effect on the reco muons once the high pt muon algo is chosen with TuneP.

In order to verify whether some change is ever propagated to other high level observables, I generated some 1500 singleMuonPt1000 events with wf 10809.0 (2018 setup).

The number of muons which change their direction is indeed quite small:
all_mini_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_patMuons_slimmedMuons__RECO_obj_eta

Differences in the reconstructed muon pt are slightly larger
all_mini_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_patMuons_slimmedMuons__RECO_obj_pt
(it is unfortunate that this plot cut off at 1 TeV, but the trend is clear)

Differences are more visible if one stick on the muons reconstructed with dyt, before the TuneP algo decides which reconstruction select for the final muon object:
all_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_log10recoTracks_tevMuons_dyt_RECO_obj_pt
all_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_minrecoTracks_tevMuons_dyt_RECO_obj_normalizedChi2,29
all_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_recoTracks_tevMuons_dyt_RECO_obj_ndof

MET as a whole get touched, but not in a significant way:
all_mini_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_patMETs_slimmedMETs__RECO_obj_phi
all_mini_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_patMETs_slimmedMETs__RECO_obj_pt

As weel as other objects, as Taus for example:
all_testPR26778VSorig_SingleMuPt1000in2018wf10809p0c_recoPFTaus_hpsPFTauProducer__RECO_obj_et

**Comment by perrotta** [comment]
Overall, the quick validation [above](https://github.com/cms-sw/cmssw/pull/26778#issuecomment-493436601) confirms what shown in the meetings: changing the fixed dyt threshold with a parameterized one in the barrel has some effect (better resolution due to the reduction of the tails) on dyt muon themselves; it reflects in an almost negligible effect on the final muons (after the TuneP choice) and all other overall event observables.

Given that the code changes in this PR are quite simple, the decision whether to accept it in the Ultra Legacy release must rely on physics considerations rather than on computing code ones.

**Comment by perrotta** [comment]
+1
- Code changes are minimal, and only meant to allow the new parameterization of the thresholds in the barrel (|eta|<1.2)
- Muon pt resolution improved (tails reduced) for dyt muons in the barrel; only a small part of this improvement gets propagated to the finally TuneP selected muon
- Muon POG supports this change

**Comment by perrotta** [comment]
@clacaputo please prepare a 10_6 backport

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

@clacaputo we need a backport of this PR in 10_6_X

**Pull request merged**
