### PR TITLE
Revert "Implement support for concurrent runs in the Framework"

### PR DESCRIPTION
**Pull request by perrotta**
Reverts cms-sw/cmssw#38801

Preparing a revert pr in case the issue reported in https://github.com/cms-sw/cmssw/pull/38801#issuecomment-1267976632 cannot get fixed quickly, and we want to cut 12_6_0_pre3

Hopefully this will get closed without merging

@makortel @wddgit

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by aandvalenzuela** [comment]
please test

- Tests need to be restarted due to a failure in cvmfs.

**Comment by perrotta** [comment]
Tests succeed, then it can be reverted
@rappoccio @makortel @wddgit I'd go ahead with the plan of merging this to have a clean pre3, then, and create a revert-of-revert PR to recreate the original https://github.com/cms-sw/cmssw/pull/38801. Or maybe this is something that you should better do yourself, maybe starting from the original commit, if you intend to apply further fixes already to it

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
Will wait for this to finish in IBs and then build pre3. We can discuss a clean solution for https://github.com/cms-sw/cmssw/pull/39644 in a few days.

**Pull request merged**
