### PR TITLE
Ctpps pixel clusterizer with db

### PR DESCRIPTION
**Pull request by fabferro**
CTPPS pixel clusterizer with calibration done reading data from DB.
Also cleaning corresponding CondFormats from previous PR.

### CODE REVIEW

**Comment by slava77** [comment]
-1
needs a proper rebase (to have no irrelevant commits)
http://cms-sw.github.io/tutorial-resolve-conflicts.html or similar should help

**Comment by fabferro** [comment]
I think I've done some messy thing with git trying to add Arun's changes. Should I close the PR and open a brand new one? Sorry...

**Comment by slava77** [comment]
you can still remake this locally from scratch or by reverting to an older common commit good for both 92X and master (your dev branch from 923patch1 .. or was it patch2)  and then push --force to the same remote topic branch. Remaking from scratch may be easier if you are not really familiar with git.

**Comment by fabferro** [comment]
In my starting branch https://github.com/CTPPS/cmssw/tree/ctpps_pixel_clusterizer_db_2 things seem to have been done correctly... @slava77 any suggestion how to correctly rebase?

**Comment by slava77** [comment]
On 6/28/17 2:10 PM, Fabrizio Ferro wrote:
> In my starting branch
> https://github.com/CTPPS/cmssw/tree/ctpps_pixel_clusterizer_db_2 things

After some thought, I realize that it is not possible to use the same PR
topic  branch anymore for both 92X and 93X.

since this branch was rebased to master head, it can no longer be used
for 92X as well.
So, 92X will have to be closed and we will need advice from AlCa on the
sequence of steps to make a PR with consistent GT for 92X

**Pull request closed without merging**
