### PR TITLE
Make sure output of zip is a list (is a generator in python 3

### PR DESCRIPTION
**Pull request by ericvaandering**
More changes from futurize. Using a generator is best, but to maintain 100% backwards compatibility, we make a list like python 2 does.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Won't this make a list holdings a list?

**Comment by ericvaandering** [comment]
No. I probably thought that too when I first saw it.

```
nakuru:tmp ewv$ python
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = [1,2]
>>> b = list(a)
>>> b
[1, 2]
>>> 
```

**Comment by davidlt** [comment]
`list()` will make a list of tuple, dictionary, list, etc. Basically `list([])` produces a deep copy of list.

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12012	1ff3957
- technical change is applied as described
- jenkins tests pass and comparisons with baseline show no difference

**Comment by mmusich** [comment]
+1

**Pull request merged**
