### PR TITLE
DQM: Clean up DQMServices/Core and its usages

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

While working on the test for #29738, I saw that we have still a lot of obsolete options set on the `DQMStore`. Cleaning that up got a bit out of hand, so therefore a separate PR here.

- All files in `DQMServices/Core` now have a well defined, up to date purpose.
   - I removed some old headers (+usages of `DQMError`), `DQMOldReciever` (from run 1, i think?), the ever-empty `doc/` folder
   - I also removed the tests in `DQMServices/Core`, primarily because the are not set up in scram, so it's not clear how to use them and they might not work any more. Many of them also tested obsolete and removed features.
   - Finally, I removed the "standalone" mode. We gave up supporting it a while ago already. DQMGUI will keep using its CMSSW7 version of `DQMStore` for the future.
- I removed all usages of `forceReset*`, `enableMultiThread`, `referenceFileName`, and `collateHistograms` options on the `DQMStore` across all of CMSSW. The `DQMStore` stopped using these options a while ago. This affects multiple categories of files:
   - Random, potentially obsolete and hard-to-test configs. We could leave them unchanged for historical value, but I think that would be more confusing.
   - Online DQM. The `referenceFileName` there was (maybe?) actually still used in last collisions data taking, but we decided to remove the references entirely anyways.
   - Production offline and HLT configs.  These are pretty important.

#### PR validation:

Not much. Needs more testing.

By construction everything removed here was no longer respected anyways, so nothing should change anywhere. But the changes do affect some important code that I have very little understanding of, so there may be side effects.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
@schneiml , rebase is required

**Comment by Martin-Grunewald** [comment]
-1
No direct modification of the HLT menu dumps under HLTrigger/Configuration. Instead, code a customisation here: HLTrigger/Configuration/python/customizeHLTforCMSSW.py

**Comment by schneiml** [comment]
@Martin-Grunewald since these use
```
process.DQMStore.enableMultiThread = True
```
They will (I think) blow up when `enableMultiThread` is not initialized to `cms.untracked.bool` beforehand. I have no idea how this mechanism works, but I am afraid cusomizing in the end is too late (I have not tried it, though).

Also, is the confdb change here sufficient to make sure this line is no longer added in the future? As said, I ahve very little idea how this works, this was primarily a simple sed to remove all mentions of `enableMultiThread`...

**Comment by schneiml** [comment]
Rebased and removed the `HLTrigger/Configuration` changes. If things work like that, I'll leave the cleanup there to the experts.

**Comment by perrotta** [comment]
@schneiml Tests cannot be run if the HLT configuration is broken.

Please provide the HLT customization in HLTrigger/Configuration/python/customizeHLTforCMSSW.py, as it was [suggested](https://github.com/cms-sw/cmssw/pull/29742#issuecomment-625166546) by Martin (examples can be found in the very same customization file)

**Comment by makortel** [comment]
> since these use
> 
> ```
> process.DQMStore.enableMultiThread = True
> ```
> 
> They will (I think) blow up when `enableMultiThread` is not initialized to `cms.untracked.bool` beforehand. I have no idea how this mechanism works, but I am afraid cusomizing in the end is too late (I have not tried it, though).

Correct, `process.DQMStore.enableMultiThread = True` will raise an exception if `process.DQMStore.enableMultiThread` has not been initialized beforehand with an explicit `cms.` type.

**Comment by schneiml** [comment]
@perrotta @Martin-Grunewald which workflows to test to see if these changes are effective?

**Comment by Martin-Grunewald** [comment]
I think you should keep in your PR the removal of:
```
      dqmstore += "%(process)s.DQMStore.enableMultiThread = True\n"
```
in file HLTrigger/Configuration/python/Tools/confdb.py.

Please put the customisation to remove the attribute ```enableMultiThread```, if it exists in process.DQMStore, in the customizeHLTforCMSSW file.

**Comment by schneiml** [comment]
@Martin-Grunewald how do I know that these changes actually do what they are supposed to? Will this code run in the PR tests?

**Comment by schneiml** [comment]
please test

We'll see, I guess.

**Comment by schneiml** [comment]
I re-added `enableMultiThread` to `DQMStore_cfi`, this seems to be the only sane way to get `cmsRun HLTrigger/Configuration/test/OnLine_HLT_GRun.py` to survive the config phase. I still haven't figured out how to really run the Add-On tests, but I guess this should be fine.

I also applied the confdb change again.

**Comment by makortel** [comment]
> I still haven't figured out how to really run the Add-On tests, but I guess this should be fine.

Run `addOnTests.py`.

**Comment by schneiml** [comment]
> Run `addOnTests.py`.

Ah, that was easy. Seems to take a while though, but looks good so far.

**Comment by schneiml** [comment]
please test

**Comment by schneiml** [comment]
+1

There are no changes out of the background noise (as expected), and as far as I remember the concerns are adressed.

**Comment by perrotta** [comment]
+1
- Reconstruction only involved because ot the removal of a few obsolete parameters from a couple of unit tests in EventFilter/Utilities
- Jenkins tests pass

**Comment by mommsen** [comment]
@srecko, could you please have a look at the DQM changes affecting online, i.e.  EventFilter/Utilities/test/startFU.py and EventFilter/Utilities/test/unittest_FU.py, and if there is some side effect of these changes?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
Do you have any objections?
l1:  @benkrikler @rekovic
alca:  @pohsun @tlampen @tocheng @christopheralanwest

**Comment by rekovic** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
merge
FYI daq:  @emeschi @mommsen

**Pull request merged**
