### PR TITLE
Modifications to include HLT_DoubleMu0 path in the HeavyFlavor DQM package

### PR DESCRIPTION
**Pull request by surnairit**
Dear Experts,

Please incorporate the following modifications to include HLT_DoubleMu0 path in the HeavyFlavor DQM package :

https://github.com/cms-sw/cmssw/commit/208f00d7904f8112b0ef6c8afc7bfaa52f807720
https://github.com/cms-sw/cmssw/commit/d6e1a012d15aa91fd542961296f07dd3973198fe

We have not made any changes in the c++ code.

Regards,
Nairit

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1
(where is 81x port of this?)

**Comment by surnairit** [comment]
@dmitrijus : The 81X PR is here : https://github.com/cms-sw/cmssw/pull/15356

**Comment by davidlange6** [comment]
@surnairit -please fix the 81x PR - see comments at #15356

**Comment by surnairit** [comment]
Updated PR for 81X is here : https://github.com/cms-sw/cmssw/pull/15546

**Comment by perrotta** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
