### PR TITLE
Shift the CSC LCT BX0 from 6 to 8 in simulation

### PR DESCRIPTION
**Pull request by dildick**
# Summary:

The CSC ALCT/CLCT and LCT central bunch crossing numbers (BX0) are known to have distinct values in the simulation and in the firmware.

In the firmware, the conventions are as follows for the central bunch crossing:
* ALCT: BX0 = 3
* CLCT: BX0 = 7
* LCT: BX0 = 8

In the simulation however, the conventions were until now:
* ALCT: BX0 = 6
* CLCT: BX0 = 6
* LCT: BX0 = 6

This pull request modifies the timing in simulation for the CSC local trigger, CSCTF, EMTF and OMTF to match the firmware.

# Details:
* This pull request is 3/3 in a series following:
  - 1/3 https://github.com/cms-sw/cmssw/pull/22099
  - 2/3 https://github.com/cms-sw/cmssw/pull/22102
* ALCTs constructed with the ALCT processor will have BX0=8 throughout the simulation. However, right before they are read out, their BX0's are shifted by -5 BX to BX0=3 so that they agree with the firmware. 
* CLCTs constructed with the CLCT processor will have BX0=7. However, when CLCTs are used in the
CSCMotherboard to be correlated to ALCTs, their BX0's are shifted by +1 BX to BX0=8. That ensures that ALCT and CLCT timing follow the same definition in the correlation algorithm.
* LCTs constructed with the CSCMotherboard will have BX0=8. This new convention has been communicated with MTF experts. A global constant in CSCConstants `LCT_CENTRAL_BX` and `CSCInputBXShift` in the EMTF configuration ensure that the track-finders are modified accordingly.
* With these changes, the CSC local trigger will no longer need a special option to re-emulate from real data.

Validation plots can be found here:
https://indico.cern.ch/event/707700/contributions/2905136/attachments/1604505/2545291/CSCEmulation20180221.pdf

Recent results can be found here: https://indico.cern.ch/event/728612/contributions/3001880/attachments/1647291/2633339/180509_csc_dpg.pdf

FYI @tahuang1991 @ptcox @abrinke1

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
@davidlange6 Sorry. I had to fix something. Can you cancel the current test and start a new one?

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
It appears there are a lot of failures in the comparisons. @ptcox can you help me figure out some of the failures in the CSC DQM?

**Comment by dildick** [comment]
For example, differences can be seen here: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/MuonCSCDigisV_CSCDigiTask.html

Though most of the plots just signal that the shift is indeed working. In the future we would have to update the binning of the plots `CSCWireDigiTimeType` and `CSCComparatorDigiTimeType` (in `MuonCSCDigisV `) to go from 0 to 16.

I also see failures for the `MuonIdentificationV` in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/Muons_MuonIdentificationV.html.

For example in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/Muons_MuonIdentificationV_GlobalMuons.html.

In some cases you can tell by the shape that the distributions are shifted. In other cases it is not so clear.

**Comment by dildick** [comment]
Another example in the Summary directory of `CSC`: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__Summary_Minus_endcap_CFEB_Comparators_Time.png

The shift is clearly seen for the first few bins. For the last few, the brown shaded area is blocking the blue dots - that needs to be fixed in the validation code. But since the number of entries is the same and the shape the same I would say that the shift is working. 

Example that the ALCT timing is now centered at BX3
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__Summary_Minus_endcap_ALCT0_dTime.png

**Comment by dildick** [comment]
Anode Rechits: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__CSCOfflineMonitor_recHits_hRHTimingAnodep21.png
Shape is clearly the same, but the distribution is shifted. This is the case for all anode rechit plots.

Segments: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__CSCOfflineMonitor_Segments_hSTimeAnode.png

Wire digis: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__CSCOfflineMonitor_Digis_hWireTBin_p31.png

This plot now actually looks better than it was before since it contains the whole histogram (red) as opposed to the old one (blue). https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_1_X_2018-02-21-1100+22288/25186/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/CSC__CSCOfflineMonitor_BXMonitor_hALCTgetBX.png

**Comment by civanch** [comment]
+1

**Comment by ptcox** [comment]
So the bottom line is there is nothing unexpected here, I think. The shifts are in line with expectations. Once you're happy with the LCTs we should get Sicheng involved to re-calibrate simulated rechits times, and then update the conditions data fro simulation.

**Comment by tahuang1991** [comment]
Hi Tim, 

Since we already have the branch (private one) including all necessary changes, maybe Sicheng could even use that branch to do any tests before our pulll request is merged to official branch.


Cheers, 
Tao

**Comment by dildick** [comment]
@ptcox I agree with Tao. Sicheng can use this branch for his calibration studies. He can include his changes in this PR or submit a separate one.

**Comment by dildick** [comment]
@rekovic Could you please sign?

**Comment by dildick** [comment]
@ptcox Does Sicheng need to complete his studies and provide a recipe to update the calibration constants in the code for this PR to be merged? Or can we proceed? I would like to move ahead because I have continuing work on the ME11 upgrade TMB emulator.

**Comment by ptcox** [comment]
Hi Sven.

Indara says Sicheng is busy with other things for the next couple fo weeks so this won't be done imminently. Sorry.
It is not updates to the code he needs to provide, but updates to the conditions data for time calibration of rechits in simulated data i.e. a matching global tag for the release with shifted LCT BX0.

Regards,

Tim

**Comment by rekovic** [comment]
Hi @dildick @ptcox, 
Does it make sense to merge this before we have conditions data for time calibration of rechits?
It seems to me the two PRs should go in synchronized.

**Comment by ptcox** [comment]
My opinion is that they should be synchronized, yes.
I don't know what use a release would be with times from CSC local reco  (rechits, segments) broken.

Tim

**Comment by rekovic** [comment]
hold

**Comment by arunhep** [comment]
@fabiocos @dildick 
what is the plan of this PR for 10.1.X ?
We have received a request to update the GTs https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3536.html
which IMHO, should go only if this PR enters in 10.1.X.
Please correct me if I am wrong.

**Comment by dildick** [comment]
@arunhep This PR and the update of the global tag go hand-in-hand. @fabiocos Can the PR still go in 10.1.X?

**Comment by arunhep** [comment]
@fabiocos sure. i will make a PR with the necessary conditions. They have been made available : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3536.html
I am trying to figure out few other updates to combine everything in one PR for GT updates.

**Comment by fabiocos** [comment]
@dildick @arunhep are the conditions needed here present in #22833 ? I am not sure from the description.

**Comment by arunhep** [comment]
@fabiocos indeed they are present.

**Comment by fabiocos** [comment]
@arunhep ok, so up to L1 people to decide, but in principle the holding factor will be removed with the merge of that PR I understand

**Comment by dildick** [comment]
@rekovic can you unhold?

**Comment by rekovic** [comment]
unhold

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
