### PR TITLE
add NApv shots in text file: module with highest values

### PR DESCRIPTION
**Pull request by rrabadan**
NApvShots added in the "modules with highest values" text file

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@davidlange6 
not sure why I don't see this one in 80x. do you see a reason?
thanks,
F.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
