### PR TITLE
Bs tomumu patch3

### PR DESCRIPTION
**Pull request by inugent**
Patch to fix problem with multiple decays being forced in a single event.

### CODE REVIEW

**Comment by covarell** [comment]
1) https://github.com/inugent/cmssw/blob/BSTomumu_Patch3/GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc#L394-L395
Is the logging correct ("ignored decays")? Should it be forced decays?

2) Why do we need the parameter "list_ignored_pdgids" in the pSet? If you want EvtGen to ignore some particles, can't this be done just overriding the "operates_on_particles" vector?

3) The antiparticle of a particle is forced to enter the list of forced decays even if not specified in the vector of forced particles. What would happen if the user.dec file does not contain the definition of the "CDecay" but just for one flavor? Would the program crash/exit?

4) 
https://github.com/inugent/cmssw/blob/BSTomumu_Patch3/GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc#L459-L503
Why 3 loops are needed here (and the vector of vectors is filled)? Can the mixing check be done on the fly (instead of fliing vectors)?

**Comment by deguio** [comment]
+1

**Comment by covarell** [comment]
@inugent , could you please reply on the comments above? This is a high-priority fix...

**Comment by inugent** [comment]
1) https://github.com/inugent/cmssw/blob/BSTomumu_Patch3/GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc#L394-L395
 Is the logging correct ("ignored decays")? Should it be forced decays?
Yes, it should be forced... will fix this.

2) Why do we need the parameter "list_ignored_pdgids" in the pSet? If you want EvtGen to ignore some particles, can't this be done just overriding the "operates_on_particles" vector?
Yes this is for backward compatibility...

This is for backward compatibility with the EvtGenLHCInterface. 

3) The antiparticle of a particle is forced to enter the list of forced decays even if not specified in the vector of forced particles. What would happen if the user.dec file does not contain the definition of the "CDecay" but just for one flavor? Would the program crash/exit?

hmmm probably yes. Maybe we should run the mixing, then find the particles of interest.... 

4) 
https://github.com/inugent/cmssw/blob/BSTomumu_Patch3/GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.cc#L459-L503
 Why 3 loops are needed here (and the vector of vectors is filled)? Can the mixing check be done on the fly (instead of filling vectors)?

Hmmm.. after looking at these comments, maybe we should run the mixing, then find the particles of interest.... But using a vector to track the particles is  the simplest way to organize throwing a dice on which one to decay.

**Comment by covarell** [comment]
For 2) ok to leave the parameter but probably it should issue a warning that it is obsolete and not affect the program (so all the !isignore statements can be dropped)

For 3) I agree that mixing should be run before finding forced particles thus simplifying the logic. Mixing is never forced on or off by the user.

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
For generators it is OK now, I see many other changes which may come from a wrong commit update? In this case, could @inugent close this and open a fresh new PR?

**Comment by deguio** [comment]
+1
this has nothing to do with DQM

**Comment by slava77** [comment]
-1

needs a rebase or a similar cleanup otherwise.

**Comment by inugent** [comment]
replaced by 8699

**Pull request closed without merging**
