### PR TITLE
Revert changes made in BTV DQM with #45577

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR fixes the failing RelVal tests (as raised here https://github.com/cms-sw/cmssw/pull/45577#issuecomment-2304706322) by reverting the changes made in #45577.  After closing inspection while preparing this PR, I think the AK4 CHS to Puppi switch needs to be discussed again for this particular BTV DQM / Validation since no b-tagging variables are set up to be computed at RECO level for AK4 Puppi jets (@cms-sw/btv-pog-l2).

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes the failing RelVal tests: `runTheMatrix.py -i all --ibeos -l 11.0,158.0,158.1,158.2,158.3,158.5,281.0,300.0,301.0,302.0,1311.0`

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
type bug-fix, btv

**Comment by tjavaid** [comment]
+1

- several spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
