### PR TITLE
Add GenStatusFlags

### PR DESCRIPTION
**Pull request by bendavid**

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by bendavid** [comment]
Mysterious to me why it works now and not before, since the only thing I did was rebase it from CMSSW_7_4_X_2015-02-07-0200 to CMSSW_7_4_0_pre7...

**Comment by bendavid** [comment]
Uh sorry now I'm confused.  It says "tests-approved" but "Faled -- Unite Tests failure".

There is no log of any failures in any case.  What is the problem here?

**Comment by bendavid** [comment]
@ktf and all, there is something weird with the integration tests, which look like they are running in a 7_5_X IB, despite the fact that this pull request is for 74x
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7812/2701/summary.html

In any case @davidlange6 the error in the unit test is at the same place as before (and I cannot reproduce locally)

checking expression: "bDiscriminator("aaa")"E

##Failure Location unknown## : Error
Test name: testExpressionParser::checkAll
uncaught exception of type N3edm9ExceptionE
- An exception of category 'Configuration' occurred.
Exception Message:
Expression parser error:method named "bDiscriminator" for type "pat::Jet" was p
assed the wrong types of arguments. (char 0)

**Comment by nclopezo** [comment]
Hi @bendavid and all,
This pull request was automatically ported to 7_5_X here https://github.com/cms-sw/cmssw/pull/7812
And the branch is the same: bendavid:genstatusflags_740p7.
 When jenkins reports the progress or the results, it marks the latest commit which in both pull requests is 00937d12bfabfc5964ed87232825a84b188a6f95 
Since both pull requests have the same commits, when the jenkins runs the tests for https://github.com/cms-sw/cmssw/pull/7812 it also marks this one. I can start to look into how this can be improved. 
Also, if  these changes are only for 7_4_X here https://github.com/cms-sw/cmssw/pull/7812 can be closed to avoid more confusions.

**Comment by nclopezo** [comment]
I started again the tests for this pull request.

**Comment by bendavid** [comment]
No this will also be needed for 75x  (but it's now getting urgent for 74x because it's holding up fixing the HLT validation for pythia8-based relvals)

**Comment by bendavid** [comment]
@nclopezo in that case I would interpret that the tests for this pull request actually succeeded, and instead the tests which failed were for the 75x pull request.
(But in that case there is still something fishy going on which should be understood, maybe depending on the order in which packages are built, etc)

**Comment by bendavid** [comment]
Ok, now it failed with the same error again.  So it looks to me like there is something non-deterministic here...

In addition there is now a matrix failure, which is new, will try to reproduce that one...

**Comment by bendavid** [comment]
And of course I cannot reproduce either the failure in 25202.0, which runs fine for me (against 7_4_0_pre7)

**Comment by davidlange6** [comment]
Hi Josh
The 25202 failure seems like a das glitch (but not in the usual way)

**Comment by bendavid** [comment]
Hi,
So that I can attempt to maybe try to reproduce the unit test failure:

Does the bot running the tests just do 
"git-cms-merge-topic bendavid:genstatusflags_740p7" against the IB indicated in the logs?

How many threads are used for compiling? (Even if I suspect the compilation order of packages is not deterministic)

Any other suggestions?

Thanks,
Josh

**Comment by nclopezo** [comment]
@bendavid 
Hi Josh,
I looked for the complete logs of these tests, but they have been already cleaned up. 
In general cms-bot does 

<pre>
scram project IB_NAME
git cms-merge-topic -u PR_NUMBER
git cms-checkdeps -A -a
</pre>

IB_NAME can be the latest available IB or an specific IB. Anyway, it is always the one that is indicated in the logs. 
Only when it has issues with the PR number, we add manually the branch name (bendavid:genstatusflags_740p7)

The command used for compiling is:
<pre>
scram b -k -j $(getconf _NPROCESSORS_ONLN)
</pre>
Which usually is -j 8

Then, to run the unit tests it does:
<pre>
scram b -k -j $(getconf _NPROCESSORS_ONLN) runtests
</pre> 

you can see the main script here:
https://github.com/cms-sw/cms-bot/blob/master/run-pr-tests

**Comment by nclopezo** [comment]
I started again a set of tests, telling it to run only the unit tests, and to not post any result to this conversation. you can see the progress here: 
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/2835/console

**Comment by bendavid** [comment]
Well from the last test logged in the conversation, the IB used was
CMSSW_7_4_X_2015-02-18-1400

**Comment by arizzi** [comment]
@ktf can you (or some other scram guru) look at what is going on here?

**Comment by ktf** [comment]
My first suspect would be a missing (or incomplete) checkdeps, as suggested by @nclopezo.
While the tests run on jenkins, can you try the exact commands above?

**Comment by bendavid** [comment]
While waiting for the full test to compile, in the meantime
I don't think I understand how the buildfile dependencies are supposed to work.

If I just do 
scram project CMSSW_7_4_X_2015-02-18-1400
git cms-merge-topic -u 7772
git cms-checkdeps -a -b

then I get
-bash-4.1$ git-cms-checkdeps -a -b
>> Checking DataFormats/HepMCCandidate CMSSW_7_4_X_2015-02-18-1400
   x DataFormats/HepMCCandidate/BuildFile.xml
   x DataFormats/HepMCCandidate/interface/GenParticle.h
   x DataFormats/HepMCCandidate/src/classes_def.xml
>> Checking DataFormats/PatCandidates CMSSW_7_4_X_2015-02-18-1400
   x DataFormats/PatCandidates/interface/PackedGenParticle.h
   x DataFormats/PatCandidates/src/PackedGenParticle.cc
   x DataFormats/PatCandidates/src/classes_def_objects.xml
>> Checking DataFormats/StdDictionaries CMSSW_7_4_X_2015-02-18-1400
   x DataFormats/StdDictionaries/src/classes_def_others.xml
   x DataFormats/StdDictionaries/src/classes_others.h
>> Checking PhysicsTools/HepMCCandAlgos CMSSW_7_4_X_2015-02-18-1400
   x PhysicsTools/HepMCCandAlgos/BuildFile.xml
   x PhysicsTools/HepMCCandAlgos/plugins/GenParticleProducer.cc
   x PhysicsTools/HepMCCandAlgos/plugins/GenParticlePruner.cc
>> Checking PhysicsTools/PatAlgos CMSSW_7_4_X_2015-02-18-1400
   x PhysicsTools/PatAlgos/plugins/PATPackedGenParticleProducer.cc
   x PhysicsTools/PatAlgos/python/slimming/packedGenParticles_cfi.py
Checking out these packages: 0

How can it be that there are no BuildFile dependencies pulled in?

If I do git cms-checkdeps -A -a
then there are 131 dependencies checked out (but they're all marked as header dependencies)

If I do git grep DataFormats/StdDictionaries, I see a lot of packages referring to StdDictionaries in their BuildFile which are NOT checked out with git cms-checkdeps -A -a (since they don't have header dependencies there,  just a dependency on the dictionaries which is explicitly declared in the BuildFile)

Am I missing something?

**Comment by bendavid** [comment]
Ok, now I'm able to reproduce the failure, (after running)
scram project CMSSW_7_4_X_2015-02-18-1400
git cms-merge-topic -u 7772
git cms-checkdeps -A -a
scram b -k -j8
scram b -k -j8 runtests

I'm not sure if it is just random that I managed to reproduce the problem this time, or the fact that I ran the exact same sequence of commands as for the bot tests.

**Comment by ktf** [comment]
@smuzaffar we should check whether it does not make sense to have:

```
git cms-merge-topic XXX
```

equivalent to:

```
git cms-merge-topic -u 7772
git cms-checkdeps -A -a
```

I suspect this is not true just to mimic the old "CVS" behavior as much as possible.

@bendavid For `-b` the current policy is that we ignore BuildFile dependencies because in the past it was considered a pain to recompile the whole lot, just because something which depends on you might get an extra dependency linked in (which is most likely harmless).

**Comment by bendavid** [comment]
The auto-created 75x version of this pull request is here btw (in case we want to simply merge this in 75x and see what happens)
https://github.com/cms-sw/cmssw/pull/7812

**Comment by fwyzard** [comment]
Hi,
what is that status of this PR ?
As far as I know it's needed to resurrect many HLT DQM plots.

.A

**Comment by bendavid** [comment]
The corresponding PR
https://github.com/cms-sw/cmssw/pull/7812
was merged in 75x (and is apparently ok there)

Agreed that we should merge this in 74x as soon as we're convinced everything is ok on a technical level.  (Then I'll also have a technically easy backport with some fixes to the definitions of the flags themselves for difficult cases, 75x version of which is https://github.com/cms-sw/cmssw/pull/8006)

**Comment by fwyzard** [comment]
HiJosh,
thanks. So, the plan would be to
  - merge #8006 into 7.5.x
  - fix the HLT DQM plots in 7.5.x
  - backport #7812, #8006, and the HLT DQM fixes to 7.4.x
?

**Comment by fwyzard** [comment]
who should sign for #8006 ?

**Comment by bendavid** [comment]
That would make sense to me.

https://github.com/cms-sw/cmssw/pull/8006 needs an analysis signature.  On the other hand, I don't think any of the changes there will affect the hlt validation updates.  (They either concern pythia6+tauola or border cases identifying b quarks from top/higgs/z/w decays)

**Comment by franzoni** [comment]
this PR is holding the re-deployment of HLT-validation code for 3 POGs.
With the forthcoming deployment of large-scale HLT updates, we want the relevant DQM developers to have time to do their changes before the next prerelease...
Thanks!

**Comment by davidlange6** [comment]
Hi Giovanni

This work can proceed already in 75x.

**Comment by bendavid** [comment]
Ok, but what is the strategy for declaring this ok to be backported to 74x?

**Comment by davidlange6** [comment]
I’m in favor of following the procedure outlined by Andrea

**Comment by bendavid** [comment]
Ok, this feature is also needed for the DIGI-RECO step of the run 2 MC (independent of the HLT validation), mainly as an analysis feature.  If we can still wait for all the HLT related changes, then ok.

**Comment by arizzi** [comment]
how we want to proceed here? @bendavid what was the outcome of the tests you were doing?

**Comment by bendavid** [comment]
As far as I can tell everything is ok in 75x.  The needed changes to HLT dqm are being made on top of this in 75x and also seem ok according to the developers of that.  I would suggest to get this merged in 74x sooner than later, since all of the other changes are technically trivial.

**Comment by arizzi** [comment]
as we may have further developments for packedGenCandidates for 740 it
would be very helpful to have this in the IB asap (so that we do not need
to recompile 131 packages locally)

**Comment by davidlange6** [comment]
ok - merging to take advantage of the full build coming tonight.

**Pull request merged**
