### PR TITLE
Add LA harvester to 1001.2 wf

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

It came up here
https://github.com/cms-sw/cmssw/pull/36241#issuecomment-978192894
that the wf 1001.2 doesnt have the LA harvester step. This PR adds that.

#### PR validation:

`runTheMatrix.py -l 1001.2 -j 0`

is now giving
```
 cmsDriver.py step5  -s ALCAHARVEST:SiPixelLA --conditions auto:run3_data_express --scenario pp --data  --era Run2_2017 --filein file:PromptCalibProdSiPixelLorentzAngle.root -n 100  --no_exec --fileout file:step5.root  > step5_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA.log  2>&1
 ```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by kskovpen** [comment]
+1

**Comment by srimanob** [comment]
Should we test 1001.2 as an additional step introduced in this PR? @tvami @kskovpen 
I don't see it in short matrix test,
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5abfd2/20750/runTheMatrix-results/

**Comment by kskovpen** [comment]
> Should we test 1001.2 as an additional step introduced in this PR? @tvami @kskovpen
> I don't see it in short matrix test,
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5abfd2/20750/runTheMatrix-results/

I agree, let's test it explicitly here as well.

**Comment by kskovpen** [comment]
test parameters:
- workflow = 1001.2

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to add additional ALCA step to a specific workflow, 1001.2. The PR test runs fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
