### PR TITLE
MTD Validation: update of the BTL SimHit validation

### PR DESCRIPTION
**Pull request by casarsa**
This PR updates the BtlSimHitsValidation plugin adding new monitoring histograms for hits produced by different trackIDs in the same BTL crystals.

The new histograms add 6 kB to the output DQM rootfile:
new file size:   267.81 KiB       MTD/BTL
old file size:    261.81 KiB       MTD/BTL

#### PR validation:

The updated validation code has been tested in the CMSSW_14_1_0_pre5 release with the workflows 27634.0_TTbar_14TeV+2026D105, 27834.0_TTbar_14TeV+2026D105PU, and 27834.99_TTbar_14TeV+2026D105PU_PMXS1S2:
the new code produces identical histograms to the current SimHit validation, except for the histogram of the number of hits from different trackIDs in the same cell, which is now filled after the cut to the cell total energy.

A note about the workflow with premixing (27834.99_TTbar_14TeV+2026D105PU_PMXS1S2): in both the old and the new code, the SimHits of the pileup events are not seen by the SimHit validation. The replay doesn't seem to work in this case because we store the accumulated SimHits in the MTD premix.

### CODE REVIEW

**Comment by fabiocos** [comment]
type mtd

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 comments on this PR?

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
