### PR TITLE
Hgcal v7 geometry eefh corrections

### PR DESCRIPTION
**Pull request by vandreev11**
@bsunanda @lgray @pfs @kpedro88 @sethzenz Corrections to the HGCAL V7 geometry. Silicon TP structure adjusted to be within HGC envelope limits, Si cell size has been changed too.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@vandreev11 Why is ```Geometry/HGCalCommonData/data/hgcal.xml``` deleted in this PR? Can you please check that this PR does not negatively interfere with #11880? (i.e. that the v5 sim/digi/reco stills runs if you merge both PRs). Thanks!

**Comment by vandreev11** [comment]
@lgray hgcal.xml file comes for each HGCAL geometry from the directory corresponding to the version,
Geometry/HGCalCommonData/data/v5/hgcal.xml in the case of V5. It was to clean up a bit, in the beginning it was a hope to have hgcal.xml as a universal global description.

**Comment by lgray** [comment]
@vandreev11 Understood, please make sure that #11880 still runs with this change, should take 5 minutes or less (instructions in that PR). Thanks.

**Comment by vandreev11** [comment]
@lgray It takes ages to compile and 1 min to crash. In any case I checked the crash is not due to missing
hgcal.xml file (crashes the same with or without that file). The prointout is
----- Begin Fatal Exception 23-Oct-2015 15:19:22 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing run: 1
   [1] Calling global beginRun for module MixingModule/'mix'
   [2] Using EventSetup component CaloGeometryBuilder/'' to make data CaloGeometry/'' in record CaloGeometryRecord
   [3] Using EventSetup component CaloTowerHardcodeGeometryEP/'' to make data CaloSubdetectorGeometry/'TOWER' in record CaloTowerGeometryRecord
Exception Message:
No data of type "CaloTowerTopology" with label "" in record "HcalRecNumberingRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'Assert' occurred.
Exception Message:
Geant4 is still alive, master thread state must be set to EndRun before Destruct

Abort

**Comment by lgray** [comment]
What version of CMSSW did you start from?
Since it runs for me...

**Comment by lgray** [comment]
And takes little time to compile.

**Comment by vandreev11** [comment]
@lgray It was with CMSSW_8_0_X_2015-10-20-1100.

**Comment by lgray** [comment]
You need to use the 10-20-2300 nightly. Earlier in the day is missing the
Hcal geometry updates (which is why it took forever for you to compile and
then the crash).

**Comment by vandreev11** [comment]
@lgray OK, I did that with the same result, except the compilation is done quickly indeed.
I propose you now merge PR 11055 and check in the environment where you have no crash.

**Comment by lgray** [comment]
@vandreev11 It's likely that this is all OK. Would go ahead with merge, there is some surgery that needs to be done on ToT PR anyway (related to geometry scenarios).

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
