### PR TITLE
[14.0.X] Fix Phase2 ditau HLT path (with DeepTau Isolation)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43855

#### PR description:

This PR implements the usage of Phase2 DeepTau training for ditau Phase 2 trigger, which was integrated with https://github.com/cms-sw/cmssw/pull/42562. In the integrated version, Run2 training files were used. The problem with this implementation has been fixed and this PR proposes this fix and necessary changes.

Hopefully it will fix the issue mentioned here: https://github.com/cms-sw/cmssw/issues/42862

The related JIRA ticket is [CMSHLT-3010](https://its.cern.ch/jira/browse/CMSHLT-3010)

#### PR validation:

The basic tests has been performed, suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).
There was no failed tests.
See also https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925882340. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/43855

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/43855

**Comment by mmusich** [comment]
type tau

**Comment by mmusich** [comment]
ping @cms-sw/reconstruction-l2

**Comment by mandrenguyen** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43855

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
