### PR TITLE
Run3-alca159 Modify the analyzer for studying high eta calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Codes to study high eta calibration using isolated charged hadrons and muons. Also re-arrange the cfg files in a sub-directory

#### PR validation:

Use standard workflows in the matrix

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@christopheralanwest @tocheng @tlampen Please approve this PR

**Comment by tlampen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
