### PR TITLE
delete old headers from CommonTools/Utils. 

### PR DESCRIPTION
**Pull request by davidlange6**
Finishing a migration from 12 years ago...

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
CommonTools/Utils/interface/deltaR.h is still included from
- Calibration/HcalAlCaRecoProducers/plugins/ConeDefinition.h
- 
- 
- 
-

**Comment by davidlange6** [comment]
No,  instead that includes CommonTools/UtilAlgos/interface/DeltaR.h

On Aug 28, 2020, at 10:29 AM, perrotta <notifications@github.com<mailto:notifications@github.com>> wrote:



CommonTools/Utils/interface/deltaR.h is still included from

  *   Calibration/HcalAlCaRecoProducers/plugins/ConeDefinition.h
  *
  *
  *
  *

**Comment by perrotta** [comment]
Yes, indeed I realized it while I was writing the list and I had  
already amended my comment above (which got submitted by mistake)

David Lange <notifications@github.com> ha scritto:

> No,  instead that includes CommonTools/UtilAlgos/interface/DeltaR.h
>
> On Aug 28, 2020, at 10:29 AM, perrotta

**Comment by perrotta** [comment]
+1
- Removed headers are not included anywhere in CMSSW
- Jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
