### PR TITLE
A set of fixes for Ph2 OT cluster/rechit validation histos

### PR DESCRIPTION
**Pull request by lowette**
This PR contains an update of the Ph2 OT cluster and rechit validation code that fixes several outstanding issues in the histograms: fix the number of rechits and clusters (separate issues), and fix the issue of saturation in TH1F's with large bin contents. Also the cluster validation code was streamlined to be much closer to the rechit validation.

### CODE REVIEW

**Comment by lowette** [comment]
I guess I didn't do this very well... I made this on top of CMSSW_9_2_X_2017-09-24-1100, the latest IB I had available (in my institute). Some guidance is appreciated, I rarely contribute code...

**Comment by perrotta** [comment]
@lowette : you are submitting to the master, i.e. 94X by now. 
CMSSW_9_2_X_2017-09-24-110 is far too old for it

**Comment by perrotta** [comment]
-1

**Comment by boudoul** [comment]
Indeed you should use a fresh 94X IB.... 
Adding @delaere as watcher

**Comment by kpedro88** [comment]
-1

**Pull request closed without merging**
