### PR TITLE
HLT development for 13_3 2/N [14_0_X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT development for 13_3 2/N [14_0 branch]

https://its.cern.ch/jira/browse/CMSHLT-2860 The FOG Ubermenu (merge of FOG's "special" menus)
  Here we include the corresponding subtable creation tools and cleaning up ../tables

https://its.cern.ch/jira/browse/CMSHLT-2974 Adding single and double Tau HLT paths using PNet algorithm
https://its.cern.ch/jira/browse/CMSHLT-2976 Removal of hltL1sSingleJet35ObjectMap from HLT_Mu3_PFJet40_v
https://its.cern.ch/jira/browse/CMSHLT-3019 Remove unused IsoMu27+Tau20 Monitoring HLT

#### PR validation:

TSG tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 13_3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+hlt

**Pull request merged**
