### PR TITLE
Add back call to consumes within loop in the MixingModule.

### PR DESCRIPTION
**Pull request by ndaci**
This fix adds back a call to consumes in a loop, that is able to load the correct inputs.
This is needed by the TSG-STEAM group in the context of MC Trigger Rate Studies.

### CODE REVIEW

**Comment by civanch** [comment]
@ndaci , why this consumes call cannot be just in front of the loop?

**Comment by davidlange6** [comment]
the pset changes in the loop..

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
the first error I looked at (for workflow 101) looks to be related to this change? Perhaps some psets are not expected to have this parameter?

----- Begin Fatal Exception 24-Jan-2017 19:49:37 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
MissingParameter: Parameter 'HepMCProductLabel' not found.
----- End Fatal Exception -------------------------------------------------

**Comment by ndaci** [comment]
Thanks @davidlange6 for noticing this. I will update this PR soon and fix this bad behaviour by adding an "if" statement (checking if the parameter exists or not in the pset).

**Comment by ndaci** [comment]
I have added the check for the required parameter. 
I tested the updated code running the following command: 
runTheMatrix.py -l 50202.0 --command='-n 5 --no_exec'

I do not observe crashes anymore, so this update has solved the problem.

**Comment by ndaci** [comment]
@civanch can you please launch the test again? Thanks!

**Comment by mdhildreth** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
