### PR TITLE
Run3-gex164 Try to address the issue of RPC geometry for Run3 applications

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address the issue of RPC geometry for Run3 applications. To be tested by muon group before committing the changes to a new payload

#### PR validation:

An overlap check is performed for the new XML file

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
regression is connected with MKFit not related to this PR.

**Comment by perrotta** [comment]
+1
- It adds a new configuration to be tested by muon group: it does not affect current workflows

**Comment by mileva** [comment]
To ping the relevant people @mileva  @bapavlov @slomeo @jhgoh

**Pull request merged**
