### PR TITLE
 HCAL: Modifications to the HCAL trigger key generation scripts

### PR DESCRIPTION
**Pull request by Michael-Krohn**
#### PR description:

This PR adds the feature to create plots comparing the HCAL effective pedestals before and after a condition change.

#### PR validation:

A basic technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport. This PR updates the "service" scripts for LUTs and Trigger key generation, so the changes do not need to be backported to 12_4_X/12_5_X

### CODE REVIEW

**Comment by tvami** [comment]
hi @Michael-Krohn after code-checks are fine, would you please squash the commits?

**Comment by tvami** [comment]
@Michael-Krohn now you need to rebase too. Also I think you didnt squash the commit, you just renamed it.

**Comment by Michael-Krohn** [comment]
Hi @tvami, yes I was struggling with squashing the commits, but I have finally succeeded

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * tests pass, no diffs besides MsgLogger

**Comment by perrotta** [comment]
+1

**Pull request merged**
