### PR TITLE
backport of tau validation in 102X

### PR DESCRIPTION
**Pull request by aspiezia**
After the changes in CMSSW_11X (https://github.com/cms-sw/cmssw/pull/27925)
and the backport in CMSSW_106X (https://github.com/cms-sw/cmssw/pull/27985),
we would like also to backport in CMSSW_102X.
@rmanzoni @roger-wolf

### CODE REVIEW

**Comment by jfernan2** [comment]
@aspiezia what's the reason behind this backport?

**Comment by jfernan2** [comment]
@aspiezia ìt depends on which UltraLegacy campaigns you plan to validate

**Comment by rmanzoni** [comment]
Hi, 106 we need for sure, if anything for the UL, and Aniello has submitted a pr for that. 102 we were less certain. I think we need to understand if there will be newer 102 samples that will include DeepTau.
Please let us come back to you later today.

**Comment by rmanzoni** [comment]
@jfernan2: we have backports of DeepTau to 10_2_X (adding DeepTau monitor plots is the main goal of @aspiezia's PR), so we thought it would be useful to have it in 10_2_X DQM too.

If the 10_2_X release cycle is not closed I guess it's perhaps ok to have this PR in, even though I agree that this is not critical and the focus is on UL, and hence 10_6_X, and after.

@jfernan2 let us know if there is something that doesn't sound right in this plan.

**Comment by jfernan2** [comment]
@rmanzoni  I do not know if 10_2_X is actually closed, I let @fabiocos to comment but I am afraid there will not be any further production

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@rmanzoni @aspiezia @jfernan2 10_2_X is a production release, so only motivated backports should enter, it is still active for production of course. The point is to understand whether we have a real production use case where to benefit of this code.

**Comment by rmanzoni** [comment]
@fabiocos at the moment, and for the foreseeable future, we don't plan anything that is not managed centrally. To my knowledge, correct me if I'm wrong, there's no 10_2_X campaign ahead of us. For the UL campaigns, we have a corresponding 10_6_X PR, so that is covered. Perhaps the conclusion is that this backport is not needed?

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@aspieza I believe this PR can be closed since the backport is not needed. Thanks

**Comment by aspiezia** [comment]
@jfernan2 that is ok for me.

**Pull request closed without merging**
