### PR TITLE
New conditions objects for HI jet reconstruction

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
New conditions object for UE subtraction in voronoi-based HI jet reconstruction (currently txt files are being used).
@yslai is the main author and the responsible contact.
Discussed with @diguida and reported to @mmusich @rcastello 

The plan for updating reconstruction accordingly is:
- Review this pull-request and update in case of feedback
- Merge this PR into 7_4_0_pre6
- Upload the payloads into DB, produce globaltags for data and MC
- Make pull-request of the reconstruction part, aiming to merge into 7_4_0_pre7

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
+1

https://github.com/cms-sw/cms-bot/pull/297
why is the reco signature here?

**Comment by diguida** [comment]
+1

**Comment by ggovi** [comment]
+1

**Pull request merged**
