### PR TITLE
`SiStripHitEfficiencyHarvester`: Hit efficiency summary saved in dqm files

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to include in `cmssw` the necessary code to automatically produce within the harvested DQM file the final efficiency plot vs layer number, so that it can be extracted from ROOT files directly instead of re-running the harvesting manually.

#### PR validation:

Run the following command:

```
cmsDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 124X_dataRun3_Express_v9 --scenario pp --data --era Run3 --dasquery='file dataset=/StreamExpress/Run2022G-PromptCalibProdSiStripHitEff-Express-v1/ALCAPROMPT run=362437' -n -1 --customise_commands='process.alcasiStripHitEfficiencyHarvester.isAtPCL = cms.bool (False)'
```

and obtained the following plots:
   * from the current setup
   
Summary

   * to be compared with the content of the DQM root file:
   
Screenshot from 2022-12-07 11-34-50

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
I see a lot of diffs in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-06-2300+27ea48/54559/11634.7_TTbar_14TeV+2021_trackingMkFit/

but I doubt that could come from this PR, right Marco?

**Comment by tvami** [comment]
+alca
 * test pass, diffs seen in 11634.7 are understood and known https://github.com/cms-sw/cmssw/issues/39803

**Comment by rappoccio** [comment]
+1

Diffs are spurious and known. https://github.com/cms-sw/cmssw/issues/39803

**Pull request merged**
