### PR TITLE
Retrained track selection MVA for phase1

### PR DESCRIPTION
**Pull request by makortel**
This PR makes use of the retrained track selection MVA (by @hajohajo). The training was done with CA-seeded tracking, but is here applied also for the default tracking, as the training improves performance also there. ~~The MVA payloads are in the GT of #17530, hence it is added here as well for time being (will rebase after #17530 is merged).~~

Here are MTV plots for 1k ttbar+PU35 events in 900pre4 for phase1 (default) and phase1 (CA)
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_0_0_pre4_PR17537/
In summary (phase1 default HP tracks):
* efficiency (w/o pT cut in denominator) increases by ~1 % (especially in |eta|>2.5)
* fake rate decreases by ~40 %
* duplicate rate increases by ~60 % (mostly in |eta|>2.5)

Presentations in tracking POG:
* https://indico.cern.ch/event/604571/contributions/2437905/attachments/1396167/2128415/TrackingMVA_16_1_2017.pdf
* https://indico.cern.ch/event/589546/contributions/2377505/attachments/1374526/2086791/TrackingMVA_21_11_2016.pdf

Tested in CMSSW_9_0_X_2017-02-15-1100 (rebased on top of CMSSW_9_0_X_2017-02-19-1100), expecting changes in phase1 workflows as indicated above. Phase0/2 should have no effect ~~(except possibly because of #17530)~~.

@rovere @VinInn @hajohajo @felicepantaleo

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
On 2/16/17 5:19 AM, Matti Kortelainen wrote:
> The MVA payloads are in the GT of #17530
> <https://github.com/cms-sw/cmssw/pull/17530>, hence it is added here as
> well for time being (will rebase after #17530
> <https://github.com/cms-sw/cmssw/pull/17530> is merged).

There are geometry changes in #17530
Do you happen to know if the reco geometry is affected as well?
If it's unchanged, I should be able to make comparisons using the same
SIM input.

**Comment by makortel** [comment]
@slava77 IIRC the (tracker) reco geometry changes were included in 900pre3.

**Comment by rovere** [comment]
Ciao @slava77, to my knowledge they are mainly overlap bug-fixes, as reported [here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2818/1.html). Maybe @ianna can comment further.

**Comment by slava77** [comment]
#17530 is merged now
time to rebase

**Comment by makortel** [comment]
@cmsbuild, please test

Rebased on top of CMSSW_9_0_X_2017-02-19-1100.

**Comment by slava77** [comment]
some plots, based on the earlier version of this PR (https://github.com/cms-sw/cmssw/pull/17537	521f35f; a separate test was done to check that tracking doesn't change after the GT update) using CMSSW_9_0_X_2017-02-16-1100 as a baseline

ttbar PU35 (wf 10224)
- about 4% increase in pf charged hadrons (compare to https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_9_0_0_pre4_phase1mva/phase1_ttbar_pu35_summary.html
 showing less than 1% increase in efficiency and a moderate decrease in efficiency of the high purity tracks); most of this increase is from the region with eta|>2.5 (given the significant increase in fake+duplicate rate there, a fraction of the increment is probably fakes; since there is no visible change in the jet response in this area, the fakes are apparently not an issue)
all_sign861vsorig_ttbar13tevpu2017wf10224p0c_log10recopfcandidates_particleflow__reco_obj_pt45
all_sign861vsorig_ttbar13tevpu2017wf10224p0c_recopfcandidates_particleflow__reco_obj_eta43

Changes in all combined general tracks are rather modest
all_sign861vsorig_ttbar13tevpu2017wf10224p0c_log10recotracks_generaltracks__reco_obj_pt

The dup rate at high eta is not looking that well; it was mentioned in the PR description though
wf10224_general_dups_eta


Btag ROCs are suggestive of a possible degradation in performance
wf10224_mvav2_l_v_b
wf10224_tche_l_v_b
.. but it may be a fluctuation, given that the stats are low here (100 events tested)

QCD 3TeV dijet (mostly central events) wf 10059 and QCD flat-pt 10071 look similar

flat-pt sample Btag ROC is a bit more mixed (maybe better at very high eff end)
wf10071_mvav2_l_v_b


On the technical side, in 10224 
 CPU is up by about 1% total, where a large fraction appears to be related to the changes in this PR 
```
[jobAverage includes valudation/mixing: scale by ~2 to get just the reco times]

delta/moduleAverage   delta/jobAverage   orig    new
   +0.284660      +0.05 %        76.27 ms/ev ->       101.58 ms/ev detachedQuadStepTrackCandidates
   +0.272317      +0.01 %        17.25 ms/ev ->        22.69 ms/ev mixedTripletStepTrackCandidates
   +0.243758      +0.01 %        24.78 ms/ev ->        31.66 ms/ev detachedQuadStepTracks
   +0.178530      +0.01 %        14.39 ms/ev ->        17.22 ms/ev highPtTripletStepSeeds
   +0.127846      +0.01 %        22.06 ms/ev ->        25.07 ms/ev lowPtQuadStep
   +0.125533      +0.07 %       255.60 ms/ev ->       289.84 ms/ev particleFlowBlock
   +0.114262      +0.06 %       258.02 ms/ev ->       289.29 ms/ev highPtTripletStepTrackCandidates
   +0.113782      +0.05 %       208.74 ms/ev ->       233.92 ms/ev trackExtrapolator
   +0.083387      +0.04 %       247.29 ms/ev ->       268.81 ms/ev detachedTripletStepTrackCandidates
   +0.033441      +0.04 %       666.63 ms/ev ->       689.30 ms/ev lowPtQuadStepTrackCandidates
   +0.025740      +0.02 %       408.86 ms/ev ->       419.52 ms/ev pixelLessStepTrackCandidates

```

Increased track efficiency at high eta and reduced fake+dups in the barrel appears to be more important than the increase in duplicates in high eta (which is apparently mitigated by ~1/2 of this PR increase in the combination of #17537 (this PR) +#17511+ #17544
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_9_0_0_pre4_phase1SeedRegionRebuild2/)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17537	c787349
- implemented as described: switched to new phase-1 MVAs
- jenkins tests pass and comparisons with baseline show differences only in phase-1 workflows
- local tests with extended stats and set of samples in 2017 workflows show changes in line with the MTV plots posted in the description. The net change is somewhat of an improvement overall.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
