### PR TITLE
Update FSQ DQM

### PR DESCRIPTION
**Pull request by fruboes**

### CODE REVIEW

**Comment by fruboes** [comment]
Dears,
 
 it looks this PR was forgotten due to xmas. What is the procedure to resurrect it?


Thanks,
 Tomasz

**Comment by deguio** [comment]
ciao @fruboes 
I didn't forget about your PR. I will review it asap.. sorry for the delay.
could you please add a meaningful explanation so that I have an idea about what this development is for?

thanks,
F.

**Comment by deguio** [comment]
I have only one question about the add of the ak4PFL1FastL2L3CorrectorChain in the sequence. Aren't the jetCorrections available from DB? why it is needed to run producers to have them?

thanks,
F.

@diguida

**Comment by fruboes** [comment]
Dear @deguio ,

 no problem with the delay, I was completely offline anyway for last 3 weeks :)

 This development was done to handle latest trigger paths from FSQ (zerobias+single pixel tracks, high multiplicity triggers and jet paths).  Most important changes:

 -- Migrate to "official" plugin for efficiency calculations 
 -- Ease plotting of basic distributions (e.g pt, eta of jets)
 -- Fixes in plot definitions (py file level), mostly for high multiplicity triggers (also - new plots to monitor the most problematic region)
 -- Use corrected jets (as you noticed). The inclusion of ak4PFL1FastL2L3CorrectorChain is the current way (AFAIU) to apply the corrections (ie JetMET trigger DQM does this that way).

 Please let me know if you have any other doubts/questions here

Cheers,
  Tomasz

BTW Happy New Year :) !!!

**Comment by deguio** [comment]
ok, thanks for the explanation.
I would wait for a comment by @diguida before approving. if those corrections are available already, I would take them from DB instead of running their producers again in the DQM sequence.
F.

**Comment by fruboes** [comment]
This goes bit differently - the sequence you mention fetches the correction constants from DB and uses them to produce corrected jets collection, which is then used by the FSQ module. I think in earlier times it was done differently (every module applied the correction on his own), now it is done centrally.

Tomasz

**Comment by deguio** [comment]
+1
I see it now. Sorry I got confused and I thought that the sequence was producing the corrections as well.
I guess that the collections you need are not made available by default in the reco sequence...

F.

**Comment by diguida** [comment]
@deguio Just for completeness, the description of the module given in https://github.com/cms-sw/cmssw/pull/6942#issuecomment-69723780 is correct. The JEC are therefore fetched via the GT from DB and applied in the job.

**Comment by fruboes** [comment]
thanks for merging!

T.

**Comment by deguio** [comment]
hello @fruboes 
I realized that the changes just merged break the HI workflow. In particular the error is:

----- Begin Fatal Exception 14-Jan-2015 10:36:10 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 152698 lumi: 51 event: 172120
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module L1FastjetCorrectorProducer/'ak4PFL1FastjetCorrector'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: double
Looking for module label: fixedGridRhoFastjetAll
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------


the fixedGridRhoFastjetAll collection is not produced in the HI reco sequence. could you provide an alternative/fix not to break the HI sequence?

to reproduce the error:
runTheMatrix.py -l 140.0

thanks in advance,
F.

**Comment by davidlange6** [comment]
reverting this PR for now. - please resubmit when errors are addressed

**Pull request merged**
