### PR TITLE
[LHERunInfo] comment out the statistics printout

### PR DESCRIPTION
**Pull request by syuvivida**
Commented out the statistics printout of LHERunInfo since it is misleading.
Users should use the information from GenXSecAnalyzer.

### CODE REVIEW

**Comment by covarell** [comment]
@bendavid @govoni are we sure we want to delete this?
It seems someone has put quite some effort in defining a correct output... and the discrepancy found by Steve seems to affect only LHEs with a very small number of events we seldom deal with...

**Comment by bendavid** [comment]
I was thinking more to gracefully silence/avoid the printout for normal running but still have the code there for debugging.

In principle all of this logic (and much of the code) should now be duplicated in the GenXSecAnalyzer

**Comment by syuvivida** [comment]
Hello, 
 Do you guys prefer that I simply disable all the hadronizer filters that calls this statistics function,
for example, HadronizerFilter, etc ...
 while still keeping the LHERunInfo::statistics funcion non-empty?

 Eiko

**Comment by bendavid** [comment]
Does the statistics() function do anything aside from the printout?

**Comment by syuvivida** [comment]
only printout

**Comment by syuvivida** [comment]
@bendavid @covarell @govoni 
I will be offline from tomorrow until Sep 28. If we make a decision today, I could re-commit today.

Eiko

**Comment by covarell** [comment]
I think the best solution would be to keep all the code but change all the cout into a logging level which is not activated by the normal settings of the MessageLogger (e.g. LogDebug)

**Comment by syuvivida** [comment]
@covarell 
I have replaced all cout messages inside LHERunInfo::statistics with LogDebug and also tested the new code by turning on LogDebug.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
