### PR TITLE
Run 3 jetid backport

### PR DESCRIPTION
**Pull request by laurenhay**
PR description:
This PR is a backport to implement the new Run3 JetID criteria and makes them the default. 

See [#40710](https://github.com/cms-sw/cmssw/pull/40710)

PR validation:
Builds and formatting checked.

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
type jetmet

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40710

**Comment by perrotta** [comment]
+1

**Pull request merged**
