### PR TITLE
Fix several unit test post-merge of #41075

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

After #41075 I noticed several unit tests started failing in CMSSW_13_1_X_2023-03-20-2300, see [cmssw dashboard](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc11/www/mon/13.1-mon-23/CMSSW_13_1_X_2023-03-20-2300?utests). The failures are all due to the missing `Tracker*Rcd` records in the base phase-2 Global Tag key in autoCond (`auto:phase2_realistic`). For the moment I just redirect the tests to use one of the geometry-flavoured keys, but eventually also the base one could use the records relative to the default geometry (T21, at the time of writing).

#### PR validation:

Run `scram b runtests`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
urgent
(it would be nice to have the unit tests fixed in the close to be built CMSSW_13_1_0_pre2)

**Comment by tvami** [comment]
+1
 * the unit tests (that are being fixed here) already passed
Screen Shot 2023-03-21 at 13 11 25

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2 @cms-sw/simulation-l2 kind ping

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@mmusich just to understand: if we merge #41119 can the GT changes implemented here for the unit tests get reverted?

**Comment by mmusich** [comment]
> if we merge https://github.com/cms-sw/cmssw/pull/41119 can the GT changes implemented here for the unit tests get reverted?

they can, but I would rather not, as it is in general better practice to rely on the geometry flavored key rather than on a tentative fragile coverage from the base Global Tag.

**Comment by francescobrivio** [comment]
> @mmusich just to understand: if we merge #41119 can the GT changes implemented here for the unit tests get reverted?

@perrotta we discussed already with Marco offline and both PRs should be merged:
 - this PR in any case makes more clear where/when the T21 should be used: "it's always better to fully specify which GT to use and not rely on some fragile tentative match for the default" (quoting Marco)
  - no need to revert #41119

**Comment by mmusich** [comment]
Also, please notice that https://github.com/cms-sw/cmssw/pull/41119 won't be able to fully solve the unit test failures (the one in `SimTracker/TrackerMaterialAnalysis` will stay).

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2 pinging again (this PR is marked "urgent").

**Comment by perrotta** [comment]
> @cms-sw/reconstruction-l2 pinging again (this PR is marked "urgent").

Since the previously failing tests do pass, which was exactly the intent of this PR, I'll merge it before the 1100 IBs. @mandrenguyen @clacaputo if you have any comment or remark please proposed an update to the release after the merge of this PR

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
