### PR TITLE
Geant4 sensitive detectors revision 5 

### PR DESCRIPTION
**Pull request by civanch**
This PR is made instead of #21964. 
Geant4 calorimeter sensitive detectors are updated:

1.     In the base class CaloSD Geant4 interface ProcessHits(..) is implemented. In the 
        derived classes two main methods for sub-detectors : getFromLibrary(..) and 
        getEnergyDeposit(.. ) allow implementation of shower libraries/parametrisation 
        or detailed simulation 
2.     Removed duplicated codes from sub-detector classes and use base class CaloSD methods 
3.     use const G4Step* pointer in protected and private interfaces, use const pointers and 
        references for all other objects, where possible
4.     use std::unique_ptr, auto, and other C++11 features where possible
5.     reduce number of protected class members and reduced number of type conversions
6.     optimized ECalSD run time methods - perform only one search over map of logical 
        volumes instead of doing this in each method
7.     remove usage of G4ParticleTable at initialisation use instead static utility
8.     optimised LogInfo and LogDebug - verbose output is substantially smaller but keeping
        similar information
9.     removed old commented lines
10.   applied corrections suggested by @kpedro88 and @VinInn to previous PRs

Correctness of this PR means identical results for all WFs.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
It turned out that with a probability ~10^-6 detector unit ID=0, in past, always previous ID was used. This pattern is restored but a warning is added. Obviously downstream mixing/digitisation cannot work in such case. Having such situation means problem in geometry or detector description inside HGCAL to be studied separately.

**Comment by civanch** [comment]
please test

**Comment by kpedro88** [comment]
@bsunanda can you look into these cases where HGCal has unitID=0?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , @fabiocos , this PR now provide identical results for most of comparisons (few in 20434 and 21234 seems to be unrelated to calorimeter hits). Because it is a sensitive cleanup (interface change) would you sign it?

**Comment by kpedro88** [comment]
@civanch reco comparisons for 2023D19 and 2023D21 show differences in HGCal hits and ECAL hits. I am not comfortable signing this PR unless those changes are understood (and why they only affect those workflows).

**Comment by civanch** [comment]
@kpedro88 , I do not see differences in hits, what is there and statistical disagreement in tracking, for example, in 21234.0: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-05-22-1100+23226/26627/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D21_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D21+RecoFullGlobal_2023D21+HARVESTFullGlobal_2023D21/Tracking__Track_cutsRecoAK4PFJets_trackingParticleRecoAsssociation_num_assoc(recoToSim)_dzpvcut_pt.png

**Comment by civanch** [comment]
@kpedro88 , now I see simply few hits difference in HGCAL for 20434, all distributions are very similar but this difference may be understood...

**Comment by civanch** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch it is an impressive piece of work. Did you check the simulation performances after this cleaning? 

One minor point that I observe, we have many #define/ifdef DebugLog instructions in the touched classes, could we take the opportunity of this big migration to modernize this to #define/ifdef EDM_ML_DEBUG , as I agreed with @kpedro88 to do for the MTD part?

**Comment by civanch** [comment]
@fabiocos , I would guess, more cleanup of LogDebug/LogInfo/LogVerbatim will be useful. #define/ifdef is the Sunanda style to keep track on the code, for me LogDebug would be enough but I would do this after the discussion. After cleanup of remaining Forward/muon SD classes it would be possible to drop more protected class members in CaloSD and in that iteration improve debug printouts.

The performance should be checked after PR is merged, because CPU checks are specific - the condition should be stable. I would expect ~1% improvement for a standard WF, more useful may be for HGCAL, which is critical from CPU point of view.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
