### PR TITLE
Update TrackingParticleFactory::vectorIsInsideVolume(...) function for SLHC version

### PR DESCRIPTION
**Pull request by jiafulow**
The check of vertex z position should be using the absolute value

### CODE REVIEW

**Comment by boudoul** [comment]
Hi @jiafulow  : is this something only for SLHC  (and I would wonder why) or more generic for any kind of detector scenarios (which then should be propagated to 75X) -  What is the impact on validation plots/analysis based on tracking particle ? - sorry If I missed an earlier discussion about this.

**Comment by jiafulow** [comment]
Hi @boudoul 

I'm not sure what is the correct way to report a possible bug, so I thought I would make a pull request on GitHub. So, I'm sorry that there is no previous discussion. Please tell me what's the correct way, and I'll do that in the future.

I suspect this is an accidental bug. It should not affect anyone who uses official samples, because the default in [trackingTruthProducer_cfi.py](https://github.com/cms-sw/cmssw/blob/CMSSW_6_2_SLHCDEV_X/SimGeneral/MixingModule/python/trackingTruthProducer_cfi.py) has
```
	ignoreTracksOutsideVolume = cms.bool(False)
```
When the switch is false, the check of vertex position is not done. It only matters when a person decides to switch it on to get **only** the tracking particles and tracking vertices **inside the tracker**, as specified by the parameters
```
	volumeRadius = cms.double(120.0),
	volumeZ = cms.double(300.0),
```
However, as it is, the cut on vertex z is applied as a single-sided cut, rather than as a double-sided cut. I believe the expected behavior should be the latter, but I guess it's really up to the experts to decide.

I'm not familiar with the 75X release, but a quick look [here](https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L726) suggests that the same function is affected.

**Comment by boudoul** [comment]
Don't be sorry , always happy when people are fixing bugs!!!  It's indeed most likely something to propagate to 75X, but @mark-grimes is much more expert than me to comment about trackingparticle usage. Thanks

**Comment by mark-grimes** [comment]
@boudoul I'm pretty sure this will have no effect on validation plots, since by default the cut this parameter controls is off.  One needs to set

   process.mix.digitizers.mergedtruth.ignoreTracksOutsideVolume = True

... oh, @jiafulow got there first with an explanation.

@jiafulow, CMSSW_6_2_SLHCDEV_X is a semi-parallel branch of CMSSW_6_2_X_SLHC.  Anything put into CMSSW_6_2_X_SLHC should be automatically forward ported to CMSSW_6_2_SLHCDEV_X.  CMSSW_7_5_X is the main development branch for non-upgrade (and soon for upgrade too, once we merge all the code from CMSSW_6_2_X_SLHC).

I would suggest putting a pull request in on CMSSW_6_2_X_SLHC and CMSSW_7_5_X with the details you just mentioned in the description.  When the CMSSW_6_2_X_SLHC pull request is merged it should automatically be applied to this branch.

**Comment by mark-grimes** [comment]
And by the way, well spotted.  Always good to fix bugs.

**Comment by jiafulow** [comment]
Hi @boudoul , @mark-grimes ,

Thanks for the replies! So, just to make sure I understand correctly, I should open two separate pull requests, one on CMSSW_6_2_X_SLHC, another on CMSSW_7_5_X, right? I'll write down the description in the pull requests.

**Comment by mark-grimes** [comment]
Correct, I think that's the best approach.  Use your original description plus what you said in your comment about it being off by default.  I'm release manager for CMSSW_6_2_X_SLHC so don't worry so much about that one, but the release managers for CMSSW_7_5_X will want as much information as possible.

**Comment by jiafulow** [comment]
Ok, will do.

**Comment by civanch** [comment]
@jiafulow , please, make this fix on top of the one of the recent 7_5_X IB. To be safe, do not try make it as a backport from SLHC but simply edit 7_5_X code. The fix when you show us become obvious but it is difficult to find.

**Comment by jiafulow** [comment]
Hi @civanch 

Ok, I'm editing directly on GitHub, so my pull request should only consist of one single line difference. I hope that's the right thing to do?

**Comment by mark-grimes** [comment]
The change has successfully been automatically added to this branch (see [here](https://github.com/cms-sw/cmssw/blob/CMSSW_6_2_SLHCDEV_X/SimGeneral/TrackingAnalysis/plugins/TrackingTruthAccumulator.cc#L669)).  @jiafulow, could you close this pull request please?

**Comment by jiafulow** [comment]
Ok, sure.

**Pull request closed without merging**
