### PR TITLE
Async global end LuminosityBlock transition

### PR DESCRIPTION
**Pull request by Dr15Jones**
The global end LuminosityBlock transition was supposed to be converted to asynchronous at the same time end Run was changed. This corrects that oversight. This also allowed removing many synchronous methods which were replaced with equivalent asynchronous implementations.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The unit test failure has nothing to do with this pull request.

**Comment by Dr15Jones** [comment]
Please test
Although the previous test only failed because of unrelated reasons

**Comment by Dr15Jones** [comment]
@smuzaffar the unit test failure is not cause by this pull request. It appears to be a race condition in the testing sytem. The error is
```
01-Sep-2017 16:56:32 CEST  Initiating request to open file file:ttbarForMetTests.root
----- Begin Fatal Exception 01-Sep-2017 16:56:32 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file 'ttbarForMetTests.root'
   Additional Info:
      [a] Input file file:ttbarForMetTests.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
+ die 'Failure using recoMET_genMet_cfg.py' 84
+ echo Failure using recoMET_genMet_cfg.py: status 84
Failure using recoMET_genMet_cfg.py: status 84
```

but the file ttbarForMetTests.root is generated in the same shell script that runs the test:
https://github.com/cms-sw/cmssw/blob/CMSSW_9_3_X/RecoMET/METProducers/test/runtests.sh

The file in question was even successfully used by several tests run in the same shell script
```
+ cmsRun /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-08-31-2300/src/RecoMET/METProducers/test/recoMET_caloMet_cfg.py
01-Sep-2017 16:50:17 CEST  Initiating request to open file file:ttbarForMetTests.root
01-Sep-2017 16:50:19 CEST  Successfully opened file file:ttbarForMetTests.root
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 01-Sep-2017 16:50:49.343 CEST
01-Sep-2017 16:50:52 CEST  Closed file file:ttbarForMetTests.root
```
and
```
+ cmsRun /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-08-31-2300/src/RecoMET/METProducers/test/recoMET_tcMet_cfg.py
01-Sep-2017 16:50:58 CEST  Initiating request to open file file:ttbarForMetTests.root
01-Sep-2017 16:51:00 CEST  Successfully opened file file:ttbarForMetTests.root
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 01-Sep-2017 16:51:07.395 CEST
01-Sep-2017 16:56:24 CEST  Closed file file:ttbarForMetTests.root
```

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 There are several tests which do `rm *.root` which if run at the same time as testRecoMETMETProducers would cause the failure happening in this pull request.
```
cdj@cdj> git grep 'rm ' | grep '\*.root' | grep sh | grep test
Alignment/APEEstimation/test/cfgTemplate/createStep2.bash:  rm ${ROOTFILEBASE}/workingArea/*.root
DQMServices/Components/test/run_fastHadd_tests.sh:    rm -fr *.root
DQMServices/Core/python/test/test_DQMMultiThread.sh:  rm -fr *.root
FastSimulation/MaterialEffects/test/getNIFiles.sh:rm *.root
FastSimulation/MaterialEffects/test/getNIFiles_py.sh:rm *.root
HLTrigger/Configuration/test/runIntegration.csh:    rm -f  ${name}/*.root
```

**Comment by smuzaffar** [comment]
good catch @Dr15Jones , yes this explains why these root files disappear.
I can update build rule to create separate unittest-name  directory to starts the test from. That should avoid these type of deletions. Some test might need fixing if they assume that they start from $CMSSW_BASE
OR fix these above mention tests to only delete those root files which they write.

**Comment by Dr15Jones** [comment]
@davidlange6 do you intend on including this in 9_3 or waiting until 9_4?

**Comment by Dr15Jones** [comment]
@davidlange6 the unit test failures are not do to this pull request.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
