### PR TITLE
2D Maps of Impact Parameters for TkDQM

### PR DESCRIPTION
**Pull request by dmeuser**
#### PR description:

We added a total of four 2D histograms showing the mean Impact Parameters as a function of track eta and phi for TkDQM. For each of the following track selections:
- PV track with pT>1 GeV
- PV track with pT>10 GeV

one histogram for dxy and one for dz is added.

#### PR validation:

The changes have been tested by running `runTheMatrix.py -l 10024`, which runs without any failed steps and produces the desired additional plots.
Here is a screenshot of the output DQM file showing one of the four maps:

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.

cc:
@mmusich, @arossi83, @sroychow

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by mmusich** [comment]
@jfernan2 
I think this source is misconfigured (in general) in the HLT case and not only for these plots.
In fact, plots in that directory are *all* empty e.g. in a recent (`CMSSW_11_3_0_pre6`) RelVal campaign (see [here](https://tinyurl.com/yzoptmmw)).
I can try to see why that happens (while it is certainly responsibility of the HLT DQM people to make sure their plots are filled), but it has in fact nothing to do with the changes proposed here.

**Comment by mmusich** [comment]
@jfernan2 after quick exchange with @mtosi we've understood the source of the problem:
In this module:

https://github.com/cms-sw/cmssw/blob/f0cac195d32cda5f4f48bfd99a751449e7624861/DQMOffline/RecoB/plugins/PrimaryVertexMonitor.cc#L399-L402

there is a requirement for the `highPurity` flag to be present for the track to pass the selection. 
The HP flag is not available for HLT tracks, therefore the if statement at line 401 is always failed.
We should make this requirement optional and configure it to be transparent for HLT. 
Let us know if this is something we can follow-up in a separate PR.

**Comment by mmusich** [comment]
@jfernan2 

> in this case cms-tsg-steam-valdqm-developers-trk e-group

yes, these are the people responsible.

> Unless you consider they are not actualy needed 

Tthey are needed to monitor alignment @ HLT

> (I am not sure if the plots you point out as empty in the Validation campaigns are exactly the same as those these PR is adding)

of course they are not the same, as the plots this PR is adding are new and could not be produced in Validation campaign done with an old release.
The point is that the same module is producing both sets of plots (the ones currently in the Validation campaign AND the ones added here), all empty because of the reasons I gave above https://github.com/cms-sw/cmssw/pull/33693#issuecomment-839054568.

>  in a separate PR,

I would prefer to keep the fix separate.
So can this PR be approved? 
Thanks

**Comment by mmusich** [comment]
Follow-up PR at https://github.com/cms-sw/cmssw/pull/33696.

**Comment by mmusich** [comment]
@cmsbuild please test with  #33696

**Comment by mmusich** [comment]
@jfernan2 when this PR is tested with #33696 the 2D plots in [HLT / Vertexing / hltPixelVertices / Alignment](https://tinyurl.com/yfqdf7o8) are filled.

image

**Comment by jfernan2** [comment]
+1
Thank you very much

**Comment by silviodonato** [comment]
+1
 #33696 is already merged

**Pull request merged**
