### PR TITLE
[DD4hep] Update DD4hep 2021 Scenario

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Updates to the scenario are taken from from the 2021 production scenario

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@slomeo - FYI

**Comment by slomeo** [comment]
@ianna : is this PR realted to the probelm with RPC chambers present in #30121 ?

**Comment by ianna** [comment]
> @ianna : is this PR related to the probelm with RPC chambers present in #30121 ?

@slomeo - what is the problem with RPCs? Comparison differences?

**Comment by slomeo** [comment]
@ianna : no, it is't. I'm talking about a histo problem of the RPC Position (i.e see chat in Skype 10/06/2020)

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade
I'll submit a followup PR to unify the scripts, haven't had time yet

**Comment by silviodonato** [comment]
@ianna this PR is in conflict with your #30214

**Comment by ianna** [comment]
The PR is outdated. This scenario is generated automatically from a dictionary as of #30214.

The diff between the two is here just for the record:
```diff
<<<<<<< dd4hep-scenario-sync-with-2021-v1
    <Include ref="Geometry/VeryForwardData/data/pps/2021/v1/pps.xml"/>
    <Include ref="Geometry/ForwardCommonData/data/forward/2021/v1/forward.xml"/>
    <Include ref="Geometry/ForwardCommonData/data/totemt2/2021/v1/totemt2.xml"/>
=======
    <Include ref='Geometry/MuonCommonData/data/muonNumbering/2021/v2/muonNumbering.xml'/>
    <Include ref='Geometry/ForwardCommonData/data/forward/2021/v1/forward.xml'/>
    <Include ref='Geometry/ForwardCommonData/data/totemt2/2021/v1/totemt2.xml'/>
>>>>>>> master

```

**Pull request closed without merging**
