### PR TITLE
Avoid shared_ptr in RecoParticleFlow/PFProducer and remove PFSCEnergyCalibration

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

PR https://github.com/cms-sw/cmssw/pull/26813 "Remove PFElectronAlgo and PFPhotonAlgo used back in Run 1" is still leading to some follow-ups:

* the PFSCEnergyCalibration class is now not used anymore, so it can be removed together with the associated configs in particleFlow_cfi.py
* the remaining calibrations were wrapped in shared_ptrs, probably because they were shared among the various algos, but I think it's easier if the ownership is clear. With PFElectron- and PFPhotonAlgo gone, there are no other algos to share the calibrations with anyway
* therefore I got rid of all usages of shared_ptr in RecoParticleFlow/PFProducer

#### PR validation:

CMSSW compiles and matrix tests pass.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
Fixed conflicts

**Comment by fabiocos** [comment]
@guitargeek the conflict come from #27153, which was ready to go

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

to get cleaner comparisons

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27154	eba7c1f
- this is somewhat technical, in line with the PR description
- jenkins tests pass and there are no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
