### PR TITLE
Add missing newlines in Calibration modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules
CalibCalorimetry/EcalTPGTools
CalibCalorimetry/HcalAlgos
CalibCalorimetry/HcalPlugins
CalibMuon/CSCCalibration
CalibPPS/AlignmentGlobal
CalibPPS/AlignmentRelative
CalibPPS/ESProducers
CalibPPS/TimingCalibration
CalibTracker/SiStripCommon
Calibration/HcalCalibAlgos
Calibration/PPSAlCaRecoProducer
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, whitespace-only changes.

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
