### PR TITLE
Simple CUDA kernels, plugins and executables

### PR DESCRIPTION
**Pull request by fwyzard**
Simple kernels, plugins and executables to test the SCRAM build rules for CUDA.

### CODE REVIEW

**Comment by fwyzard** [comment]
**Not for merging.**

Here are a set of packages with different splitting of CUDA functions, CUDA kernel, plan C wrappers, EDM plugins and standalone tests, that can be used to test the build rules used by SCRAM to handle CUDA code.

**Comment by fwyzard** [comment]
@smuzaffar FYI

**Comment by fwyzard** [comment]
Please enable GPU.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, enable gpu

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@fwyzard , are these unit tests suppose to be running on system with no GPU? If not then we should update thses to not fail is GPU device is not found.

**Comment by fwyzard** [comment]
I did not intend to have them merged, only to use them to test the new build rules.

If you think it would be useful to keep them around, I can add workarounds for systems without GPU.

**Comment by smuzaffar** [comment]
build rules worked fine at least unit tests were build and run successfully on system with GUP

**Comment by fabiocos** [comment]
hold

just to recall this was not intended for direct merge but more for test

**Comment by silviodonato** [comment]
Hi @fwyzard , could you confirm that this PR is still needed/useful?

**Comment by fwyzard** [comment]
@silviodonato , I guess we can cose it now that we have a real CUDA PR under validation

**Pull request closed without merging**
