### PR TITLE
Made AssociationMap thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
Switched the transient std::map to be a tbb::concurrent_unordered_map.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
It isn't possible to get the logs from the tests. When I did the tests on my own I discovered that the build system didn't checkout 'DataFormats/TrackReco' which caused a binary incompatibility. Perhaps that is what happened in this case? In my own area I had done
```
>git cms-checkdeps -a
>git cms-addpkg DataFormats/RecoTrack
>scram b  -j 12
>runTheMatrix.py -s
```
and everything worked fine

**Comment by slava77** [comment]
Chris, Maybe you can add an empty line edit to DF/TrackReco?

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@slava77 I removed an extra line from DataFormats/TrackReco/BuildFile.xml to force the rebuilding.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11189	f36e36f
- code changes look OK
-  the static analyzer still complains about the mutable internal_transient_map_type. I suppose something hiding the issue can be added at some point
- jenkins tests passed and comparisons with baseline show no differences (none expected in these tests)

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
@Dr15Jones your signature is needed here as well

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
