### PR TITLE
add pixel residuals monitoring at HLT

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, to provide pixel track residuals monitoring at the HLT during data-taking operations.

#### PR validation:

Run a 2024 workflow including a non trivial HLT step (via `runTheMatrix.py -l 12834.0 -t 4 -j 8 --ibeos`) and inspected the resulting DQM file. I've found the newly added monitoring elements filled.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported to CMSSW_14_0_X for 2024 data-taking operations.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
+1

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
pixel residuals at HLT plots are now nicely filled (see e.g. https://tinyurl.com/293tjdo3)

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 you already signed this at https://github.com/cms-sw/cmssw/pull/45739#issuecomment-2295858442, can you sign again?
The last push fixed a limitation in the previous implementation that made `SiPixelPhase1ResidualsExtra` fetch the input ME-s from the offline reconstruction and not from the HLT one.
It would be great to have the backport of this (https://github.com/cms-sw/cmssw/pull/45746) included in the next Tier0 release.
Thank you!

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
