### PR TITLE
backport of HCAL iterative phi symmetry calibration AlCaReco for 74X

### PR DESCRIPTION
**Pull request by nilina**
Backport of 75X PR #9075

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by nilina** [comment]
Should I do anything at the moment to further this PR? Thanks.

**Comment by mmusich** [comment]
+1
backport of #9075

**Comment by mmusich** [comment]
@nilina we approve the changes based on PR test in 75X. 
Fror production we will ask for inclusion of the new AlCaReco in the next ORP meeting. N.B. this will mean a new patch release.

**Pull request merged**
