### PR TITLE
bsunanda:Run2-hcx97 Bug fixes for Hcal geometry routines

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by davidlange6** [comment]
please test
(seems the bot is ignoring this pr)

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Hi @bsunanda - what is the expected impact of these changes on hgcal results (eg, are those coming from 8_2_0 are affected?)

**Comment by abdoulline** [comment]
...In addition to David's question: is there any impact on  Run 2 / Phase 1 ?
 Ieta=29 depth > 2 seems to be affected?

**Comment by davidlange6** [comment]
ping @bsunanda

**Comment by ianna** [comment]
@abdoulline and @davidlange6 - as discussed at ORP I was asked to look into this. No affect on Phase 0 is expected. To check the impact on Phase I one should look for cells with ieta=29 and depth=3 in order to check if their delta Eta is a double size compared to cells with ieta=29 and depth=2 or 1. So this PR is actually fixes this bug.

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@davidlange6 @abdoulline @ianna The changes will not affect the standard physics results - the affected codes refer to functionality for some special cases only. Please integrate the code

**Comment by davidlange6** [comment]
+1

**Pull request merged**
