### PR TITLE
Move FastSimulation/BaseParticlePropagator to CommonTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Moving the package to CommonTools properly reflects its dual usage by Fast Simulation and Reconstruction. This was discussed in #26016.

#### PR validation:

Did `git cms-checkdeps -a` and recompiled all the code.  
After the change I did `git grep FastSimulation/Base` and not files were returned.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
@smuzaffar is the comparison still running for this?

**Comment by Dr15Jones** [comment]
As this was just a renaming of a shared library and fixes for includes and include guards, the Reco comparison changes can not be directly attributed to this change.

The changes could be caused by Reco code being dependent on exact memory addresses. Changing the name of the shared library could change the load order of the library as well as the amount of space used to record the name of the shared library in the binary file. Therefore memory in the job could be shuffled around a bit.

**Comment by Dr15Jones** [comment]
+1

**Comment by ssekmen** [comment]
+1

**Comment by slava77** [comment]
> As this was just a renaming of a shared library and fixes for includes and include guards, the Reco comparison changes can not be directly attributed to this change.
> 
> The changes could be caused by Reco code being dependent on exact memory addresses. Changing the name of the shared library could change the load order of the library as well as the amount of space used to record the name of the shared library in the binary file. Therefore memory in the job could be shuffled around a bit.

reco changes are because your PR is more recent than the IB used for tests.
Changes come from #26117 added to the PR build in the jenkins tests

**Comment by slava77** [comment]
@cmsbuild please test

to get cleaner comparisons

**Comment by Dr15Jones** [comment]
@smuzaffar looks like the testing got stuck?

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical: the BaseParticlePropagator package is moved to CommonTools as in the PR description
- It remove dependency of reco code from FastSimulation/BaseParticlePropagator
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez the change looks trivial on the generator side, could you please have a look?

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov the addition of the new package to cms-bot has been prepared, waiting to be merged, then I will merge this PR

**Comment by smuzaffar** [comment]
@fabiocos , cms-bot PR is merged

**Comment by fabiocos** [comment]
@smuzaffar thanks!

**Pull request merged**
