### PR TITLE
[L1-UPGRADE] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes set but unused warnings from clang-16 in CLANG IBs.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by aloeliger** [comment]
Okay, @skkwan isn't available, but a quick look at the phase 2 emulator PR she has made doesn't show a change to any of these variables.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
