### PR TITLE
Protect against null `VertexRef` in `DeepBoostedJetTagInfoProducer.cc`

### PR DESCRIPTION
**Pull request by mandrenguyen**
Avoids an invalid reference exception discussed here:
https://github.com/cms-sw/cmssw/issues/45190

The issue only pops up on AMD for a reason that's not clear to me. 
I have admittedly not investigated why the VertexRef is null.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
Incidentally, is PR testing done on Intel or AMD?

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by VinInn** [comment]
Null vertex ref are normal (if pfCand has no track associated )
I suggest to change the protections as
```
diff --git a/RecoBTag/FeatureTools/src/deep_helpers.cc b/RecoBTag/FeatureTools/src/deep_helpers.cc
index 76b443542b3..faf1649d9b8 100644
--- a/RecoBTag/FeatureTools/src/deep_helpers.cc
+++ b/RecoBTag/FeatureTools/src/deep_helpers.cc
@@ -150,7 +150,7 @@ namespace btagbtvdeep {

   float vtx_ass_from_pfcand(const reco::PFCandidate &pfcand, int pv_ass_quality, const reco::VertexRef &pv) {
     float vtx_ass = pat::PackedCandidate::PVAssociationQuality(qualityMap[pv_ass_quality]);
-    if (pfcand.trackRef().isNonnull() && pv->trackWeight(pfcand.trackRef()) > 0.5 && pv_ass_quality == 7) {
+    if (pv.isNonnull() && pfcand.trackRef().isNonnull() && pv->trackWeight(pfcand.trackRef()) > 0.5 && pv_ass_quality == 7) {
       vtx_ass = pat::PackedCandidate::UsedInFitTight;
     }
     return vtx_ass;
```

the check ```pfcand.trackRef().isNonnull()``` is most probably not required and my guess is that was there to protect against no vex

**Comment by VinInn** [comment]
IN anycase this PR cure the symptom NOT the cause!!!

**Comment by mandrenguyen** [comment]
hold

**Comment by mandrenguyen** [comment]
> IN anycase this PR cure the symptom NOT the cause!!!

Indeed this was clear.  Thanks for the proposed solution, I will update the PR with your suggestion and test it, when I find a free moment (offline F2F meeting happening now)

**Comment by mandrenguyen** [comment]
@VinInn If you prefer, feel free to open a new PR of course.

**Pull request closed without merging**
