### PR TITLE
Puppi tuning for80x

### PR DESCRIPTION
**Pull request by hsatoshi**
Puppi is tuned for 80x release with new samples.
A work with @nhanvtran and @violatingcp.

### CODE REVIEW

**Comment by slava77** [comment]
@hsatoshi please provide some details on changes in physics performance
(puppijets, isolation etc).
I suppose, this work was presented in a JME meeting.
If so, please add a link in the PR description block (edit your original "Puppi is tuned for 80x ...")

Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
(the errors seemed unrelated)

**Comment by hsatoshi** [comment]
(for the record ; I sent an email to Jim and Andreas for a brief explanation of the update)

**Comment by slava77** [comment]
@jdolen @ahinzmann
based on the email exchanges with plots, please clarify if the updates look good to you from the point of view of physics performance.
We can probably wait until Feb 3 meeting to get feedback before integrating this PR, but it will be pushing it against the deadline.

**Comment by ahinzmann** [comment]
@slava77 the updates look good. please go ahead with the integration!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13136	c680e86
- changes in the configuration reduce thresholds on neutrals in the forward region and slightly increase it in the eta<2.5 region. The reduced thresholds in the forward reflects improved performance of the HF in 76X/80X. More details will be presented in JME working meeting on Feb 3 ( @hsatoshi  please add a link to the slides in this PR after the meeting happens)
- jenkins tests pass and comparisons with baseline show differences only in puppi-related objects (jets and MET)
    - there is a clear increase in HF contribution  (all plots are from SinglePh 2015D workflow 134.911)
wf134 911_puppijetscleaned_eta
wf134 911_puppijetscleaned_nconst_fwd
wf134 911_puppimetcleaned_hfemetvsnvtx
wf134 911_puppimetcleaned_hfhadetvsnvtx

- local test on 70 ttbar events from 25202 running PAT step only shows no significant change in CPU and event size comparison shows rather small changes in puppi-related objects
```
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
   2529.5 ->      2543.3         14      0.5   0.02     patJets_slimmedJetsPuppi__DQM.
    895.9 ->       897.6          2      0.2   0.00     patMETs_slimmedMETsPuppi__DQM.
  19207.0 ->     19240.7         34      0.2   0.05     patPackedCandidates_packedPFCandidates__DQM.
-------------------------------------------------------------
    74520 ->       74569         49             0.1     ALL BRANCHES

```

**Pull request merged**
