### PR TITLE
New pixel RecHit infrastructure for FastSim (for Phases 0, 1, 2, and beyond), backport of ##23799 for 94X 

### PR DESCRIPTION
**Pull request by pmaksim1**
This is a backport of the new pixel RecHit infrastructure (#23799) for 94X. It contains:

- pixel RecHit smearing code has been completely rewritten, in order to make it more maintainable, and extensible to other geometries. (The old code assumed a lot of things about the Phase 0 geometry, whereas the new code pushes all physics / geometry issues to pixel template object and the resolution histograms.)

- the pixel resolution histograms are now separated for each type of pixel RecHit (regular vs cluster-on-edge vs cluster-with-big-pixel) as well as for each DetUnit with a specific orientation of local B field (since that determines the drift). Thus, a pixel template matches each pixel resolution histogram file.  [This is very important for Phase 1 Forward, since the blades are tilted about both axes, and thus the angles are different from Phase 0 geometry.]

- pixel templates are loaded from the DB.

- the current code is essentially completely generic, and will work for Phase2 as well.  (Provided that the proper resolution files are provided.)

Note that the hit merging is still off. Its effects have not been studied well enough to turn it on at this time.

### CODE REVIEW

**Comment by pmaksim1** [comment]
@kpedro88, any thoughts on this?  I started from your recipe (thanks!), patched it locally, ran test jobs and everything was fine.   This is now well above my git ability.

**Comment by pmaksim1** [comment]
BTW, I can just start from scratch and copy the files by hand (since now we know what they need to be for 94X, as the merging has been done!).    But that would seem very un git-ty.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by kpedro88** [comment]
@pmaksim you submitted this PR to the master branch. Please submit it to the CMSSW_9_4_X branch.

**Comment by pmaksim1** [comment]
@kpedro88, thanks!  But, how do I do that?   (Sorry this is a super-pedestrian question, but I really don't know, and at this point it would take time to re-watch the GitHub educational videos to find out.)

**Comment by ssekmen** [comment]
@pmaksim1 you just need to choose 9_4_X from the drop down menu that comes out when you are on the pull request page.

**Comment by kpedro88** [comment]
use this link:
https://github.com/cms-sw/cmssw/compare/CMSSW_9_4_X...pmaksim1:new_pixel_fastsim_94X?expand=1

**Comment by slava77** [comment]
On 9/30/18 5:03 PM, Petar Maksimovic wrote:
> @kpedro88
> thanks! But, how do I do that? (Sorry this is a super-pedestrian
> question, but I really don't know, and at this point it would take time
> to re-watch the GitHub educational videos to find out.)
> 
you can click on "Edit" at the top right and then change the target
branch from the drop down that appears right under the PR description

**Comment by pmaksim1** [comment]
@ssekmen @kpedro88 @slava77 , Many thanks!   
I went with Slava's solution (as hopefully the most educational), and updated the base for this PR. (So I presume it's the same PR).

I'm not sure what happens now...

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
@pmaksim1 , looks ok now

**Comment by kpedro88** [comment]
@cmsbuild ping

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

differences are mostly concentrated in FS workflows, apart for spurious PixelPhase1 differences. Differences in the backport wrt to master are justified by unrelated code changes.

**Pull request merged**
