### PR TITLE
add support for `ALCARECOTkAlJetHT` to `trackselectionRefitting`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all. Needed to make use of the new ALCARECO samples created via PR https://github.com/cms-sw/cmssw/pull/38254 in the alignment workflow.

#### PR validation:

Run the unit tests of `Alignment/OfflineValidation` without problems

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but needs to be backported

### CODE REVIEW

**Comment by mmusich** [comment]
@consuegs FYI

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Alignment/OfflineValidation, Alignment/TrackerAlignment, Alignment/MillePedeAlignmentAlgorithm

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type trk

**Comment by tvami** [comment]
+alca
 * tests pass
 * PR according to describtion

**Comment by qliphy** [comment]
+1

**Pull request merged**
