### PR TITLE
Restore "Run4-hgx247 Add some new features for HGCal" (#30323)

### PR DESCRIPTION
**Pull request by silviodonato**
Revert of the revert "Run4-hgx247 Add some new features for HGCal" (#30323)
The first revert was #30458 .

### CODE REVIEW

**Comment by silviodonato** [comment]
hold

**Comment by kpedro88** [comment]
@silviodonato can you remove the changes in L1Trigger/Configuration in this PR? then we can test with https://github.com/cms-data/L1Trigger-L1THGCal/pull/19

**Comment by silviodonato** [comment]
> @silviodonato can you remove the changes in L1Trigger/Configuration in this PR? then we can test with [cms-data/L1Trigger-L1THGCal#19](https://github.com/cms-data/L1Trigger-L1THGCal/pull/19)

sure, I will do it after the meeting

**Comment by silviodonato** [comment]
moved to #30473
@kpedro88

**Pull request closed without merging**
