### PR TITLE
add ecal digi SR flags to FEVT and RECO

### PR DESCRIPTION
**Pull request by slava77**
ecal digi SR flags are needed for PF and can be useful for other studies.

This fixes a problem in RECOfromRECO workflows (or other places rerunning PF from reco) after merging #17794.

### CODE REVIEW

**Comment by slava77** [comment]
@emanueledimarco please cherry-pick this commit to your 90X PR #18016

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test with #1102

**Comment by slava77** [comment]
@cmsbuild please test workflow 1102

wrong syntax last time

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar 
what did I do wrong in https://github.com/cms-sw/cmssw/pull/18141#issuecomment-290693840 ?
the bot did not react to my ```@cmsbuild please test workflow 1102```

**Comment by smuzaffar** [comment]
@slava77 ,your comment https://github.com/cms-sw/cmssw/pull/18141#issuecomment-290695834 override your previous comment.

**Comment by smuzaffar** [comment]
@slava77 , my bad, your two comments were an hour apart, so bot should have reacted. I am looking...

**Comment by slava77** [comment]
On 3/31/17 3:38 PM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , my bad, your two comments were
> an hour apart, so bot should have reacted. I am looking...

yes, I waited for the first one to start and it the bot didn't react, so
I went back to the regular "please test"

**Comment by smuzaffar** [comment]
actually bot is not trained to understand its own message ```I had the issue.....``` to noticed that previous tests are done. So in this case, bot assumed that previous tests are still running so it ignore your comment. I am going to fix this so that bot can understand ```I had the issue.....``` type of messages

**Comment by smuzaffar** [comment]
cms-bot is fixed now to recognize its own ```I had the issue....```  message.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18141	713d5c2
- jenkins tests pass
- the failing 1102 workflow was tested to be working OK before the PR submission

**Comment by davidlange6** [comment]
+1

**Pull request merged**
