### PR TITLE
Payload inspector update 10 2 x for Strip detector

### PR DESCRIPTION
**Pull request by ghost**
New plots added for: 
CondCore/SiStripPlugins/plugins/SiStripThreshold_PayloadInspector.cc
CondCore/SiStripPlugins/plugins/SiStripNoises_PayloadInspector.cc
CondCore/SiStripPlugins/plugins/SiStripLatency_PayloadInspector.cc

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by boudoul** [comment]
hello @jpriscia , could you please add in the title that this is for the strip detector ?  (otherwise we cannot guess if this is for ecal, hcal , whatever in the release notes )  Thank you

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi I see a similar pattern as for #23341, although the extension of the existing code is much reduced here. Everything looks driven by the base classes used, so basically for every plot a new class 
 the same structure is made. The code repetition here looks anyway reduced compared to #23341

**Comment by fabiocos** [comment]
+1

**Comment by mmusich** [comment]
@fabiocos we are already templating the code for "similar" plot types to avoid diverging with the number of classes (see e.g.: https://github.com/cms-sw/cmssw/pull/23316/files#diff-e804948f40594c96ca5bcf7f2badce6fR630) and making use of helper functions: (see e.g. https://github.com/cms-sw/cmssw/pull/23316/files#diff-e804948f40594c96ca5bcf7f2badce6fR729). Classes that output different types of plots can maybe further simplified with some effort. Of course we are happy to include any suggestions about it for the next update.

**Comment by fabiocos** [comment]
@boudoul @mmusich indeed my remark was related to the comparison of two parallel updates based on the same underlying base classes.

**Pull request merged**
