### PR TITLE
Apply Tracker Alignment to phase2 geometries

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is complementary to https://github.com/cms-sw/cmssw/pull/41072. 
In that PR the Tracker Alignment records from the Phase2 simulation GlobalTags were removed, since these are currently using Phase-1 conditions.
This PR, in turn, aims to supply to the Phase-2 workflows geometry-dependent aligned **IDEAL** geometries, by introducing appropriate dictionaries in `autoCondPhase2.py` for `TrackerAlignmentRcd`, `TrackerAlignmentErrorExtendedRcd`,  `TrackerSurfaceDeformationRcd`. 
At the same time the `applyAlignment` parameter of `TrackerDigiGeometryESModule` is set to `True` for all active Phase-2 geometries (and correspondingly in `dict2026Geometry` in order to pass unit tests).
The aim is to further develop Tracker Alignment related workflows for the Phase-2 upgrade detector.

#### PR validation: 

Successfully run: `runTheMatrix.py -l 20834.0 -j 8 --ibeos`
Multi Track Validator comparison at http://musich.web.cern.ch/musich/display/PR_41075_validation_1k/plots_ootb.html (1k events of 20800.0: FourMuPt1_200+2026D8)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

cc:
@consuegs @henriettepetersen @emiglior

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
Everything looks good, shall this PR be moved away from being a draft?

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
Hi @mmusich @tvami 
Could you please turn the draft to PR? Thx.

**Comment by tvami** [comment]
+alca
 * PR according to description
 * tests pass, changes are visible and expected

**Comment by mmusich** [comment]
any comment from @cms-sw/upgrade-l2 ?

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
