### PR TITLE
Revert "L1T offline emulator DQM config upgrades - 102x"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#24291

This PR assumes the output of the L1 simGmtStage2Digis available on input, but this is not true in the standard repacking. Pending a properly tested solution, this update is temporarily reverted.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.867

**Comment by fabiocos** [comment]
see #24551 for details of the problem

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
