### PR TITLE
Update on AlCaRECO Event Content

### PR DESCRIPTION
**Pull request by jeongeun**
specifying module without wildcard 
ALCARECODtCalibCosmics_Output_cff.py
ALCARECODtCalibHI_Output_cff.py
ALCARECODtCalib_Output_cff.py
ALCARECOEcalCalIsolElectron_Output_cff.py
ALCARECOHcalCalHOCosmics_Output_cff.py

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@mmusich @diguida 
Just to clarify:
We (me and Carl) asked Jeongeun to cleanup the wildcards in the module names for event content definitions running in the prompt-like reco application (RECO+PAT+ALCA).
The goal is to have only needed products produced when running unscheduled and avoid spurious ones made by an incidental import * or a similar load of a module matching the wildcard.
This PR is the AlCa part of the cleanup.

**Comment by mmusich** [comment]
@slava77 thanks for the clarification

**Comment by mmusich** [comment]
+1

**Comment by tocheng** [comment]
Hello, I have done test for this PR on 76X and 80X. I use workflow 1325.0 which is TTbar MC at 13TeV to test the event content for AlCa reco on Ecal calibration(ALCARECOEcalCalIsolElectron_Output_cff.py).
I add paths EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron to test the AlCa event content (they are not in the default workflow). And it turns out that the event content differ in EcalCalZElectron and EcalCalWElectron. without the PR, there are three more collections in the output:

recoCaloClusters_reducedEgamma_reducedEBEEClusters_RECO
recoCaloClusters_reducedEgamma_reducedESClusters_RECO
recoSuperClusters_reducedEgamma_reducedSuperClusters_RECO

And this happens in both 76X and 80X.
Please comment whether Ecal calibration needs the three collection. Thanks. @shervin86, @emanueledimarco

**Comment by shervin86** [comment]
Thanks for the checks, I will have a look at the end of the week.

-- 
 							Shervin

**Comment by tocheng** [comment]
Hello,
 sorry if I send comment twice. I sent one a few days ago and can't find it in the conversion.
 I did some test to check the event content before and after this pull request in 76X and 80X.
 I use the workflow 1325.0 which generate ttbar MC at 13TeV and I add AlCa:EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron to test event content related to ALCARECOEcalCalIsolElectron. 
And I find that the version without pull request leads to three extra collections :
recoCaloClusters_reducedEgamma_reducedEBEEClusters_RECO
recoCaloClusters_reducedEgamma_reducedESClusters_RECO
recoSuperClusters_reducedEgamma_reducedSuperClusters_RECO.

Please comment whether they are still needed for Ecal calibration. @shervin86, @emanueledimarco

**Comment by tocheng** [comment]
Hello, did you manage to take a look at it? Many thanks. @shervin86

**Pull request closed without merging**
