### PR TITLE
HIon menu and fillDescription in EcalUncalibRechitProducer

### PR DESCRIPTION
**Pull request by perrotta**
Update the HLT menu with first paths for the HIon table, and the modified EcalUncalibRechitProducer
As of March 1, this pull request port to 75X what is #7915 (for 74X)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6 can you please bypass the L1 signature ?
It is required "only" for changes
  - to the HLT menu
  - to complete my previous #7579

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1
thanks @mulhearn

**Pull request merged**
