### PR TITLE
Phase2-TB76Y Update the analyzer code and scripts for 2023 July HGCal Test Beam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the analyzer code and scripts for 2023 July HGCal Test Beam

#### PR validation:

Tested the new analyser with the updated script

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
