### PR TITLE
CTPPS create Reconstruction workflow test

### PR DESCRIPTION
**Pull request by Glitchmin**
#### PR description:
This PR adds a new test `RecoPPS/Local/TestCTPPSReconstruction` that runs `RecoPPS/Local/test/2023_lhcinfo_test_recoCTPPS_cfg.py`, checking if the standard reconstruction workflow is not crashing.
This workflow:
* transforms data using `RawToDigi`
* reconstructs collisions using `recoCTPPS` 
* creates proton reconstruction plots using `CTPPSProtonReconstructionPlotter`

 and uses `auto:run3_data` Global Tag
#### PR validation:
Run `scram b runtests` to see the mentioned test in the test sequence

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Glitchmin** [comment]
@jfernan2 @mandrenguyen @antoniovilela @sextonkennedy @rappoccio can you please have a look at this, comment and/or sign? It would mean a lot for me to have it merged this week (of course it's not a problem if it won't happen).

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
@cms-sw/orp-l2 this is a simple PR, likely not affecting other workflows or tests: could you please merge at your earliest opportunity, as Adam and the PPS team would like to profit of having it in the release?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
