### PR TITLE
Add l1tPhase2L1CaloEGammaEmulator to the phase 2 L1 event content

### PR DESCRIPTION
**Pull request by epalencia**
This PR adds a new collection to the phase-2 L1 event content.

This PR superseeds https://github.com/cms-sw/cmssw/pull/43872.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
I think @skkwan has a PR open designed to handle this serialization issus: https://github.com/cms-sw/cmssw/pull/44390

**Comment by aloeliger** [comment]
please test with https://github.com/cms-sw/cmssw/pull/44390

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
