### PR TITLE
Removed cmsScimark2 exec and scripts

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR drops `cmsScimark2` binary and related scripts

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
Umm, GitHub claims
> **This branch has conflicts that must be resolved**

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
plase test

use latest IB

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
