### PR TITLE
DQM: SiPixelPhase1- Added Big Pixel Charge Plots  [Backport for 10_1_X of #22324 ]

### PR DESCRIPTION
**Pull request by boudoul**
Added the charge of the big pixels for the barrel and the forward region, as well as per layer and per disk
For inclusive clusters and on-track clusters (for inclusive clusters the plots are disabled by default)

Exact backport of the already merged PR  #22324

Work done by  @emacdonald16

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
This PR is quite different from #22324 
Can these differences be explained?

**Comment by boudoul** [comment]
I do not see any differences...

**Comment by boudoul** [comment]
Hi @dmitrijus , @jfernan2 , what are the differences ?

**Comment by boudoul** [comment]
I guess you meant for differences the whitespaces introduced by the @emacdonald16's editor ?
you can get the original PR without white spaces (almost ) with https://github.com/cms-sw/cmssw/pull/22324/files?w=1  so that you can see that this PR is the exact backport of the code

**Comment by boudoul** [comment]
voila I backported the white spaces ......    so everything is strictly in synch .
@dmitrijus , @jfernan2

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 @dmitrijus do you see any issue with this PR?

**Comment by boudoul** [comment]
@jfernan2 @dmitrijus :  please sign and request this to be in the next 10_1 release (since we missed the 10_1_1)

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
