### PR TITLE
Ecal Geometry: DD Dependency Cleanup v2

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

 * Move all plugins **ASIS** in a plugin directory to avoid direct dependency of the package on DD
 * Run code-checks

_Note_: the code needs a thorough revision: CLHEP usage, code modernization, etc. This will be done as a next step.

Replaces https://github.com/cms-sw/cmssw/pull/27376

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@smuzaffar - FYI, I did run ```scram build code-format``` before submitting the PR...

**Comment by smuzaffar** [comment]
did you commit the changes after running `scram b code-format`? may be it did not run for the re-named files, I will check

**Comment by ianna** [comment]
> did you commit the changes after running `scram b code-format`? may be it did not run for the re-named files, I will check

yep.

**Comment by ianna** [comment]
```
gmake[2]: Entering directory '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300'
>> Local Products Rules ..... started
>> Local Products Rules ..... done
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/BuildFile.xml.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/BuildFile.xml
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/BuildFile.xml. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalAPDAlgo.h.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/interface/DDEcalAPDAlgo.h
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/interface/DDEcalAPDAlgo.h. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalBarrelAlgo.h.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/interface/DDEcalBarrelAlgo.h
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/interface/DDEcalBarrelAlgo.h. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalBarrelNewAlgo.h.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/interface/DDEcalBarrelNewAlgo.h
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/interface/DDEcalBarrelNewAlgo.h. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalEndcapAlgo.h.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/interface/DDEcalEndcapAlgo.h
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/interface/DDEcalEndcapAlgo.h. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalPreshowerAlgo.h.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/interface/DDEcalPreshowerAlgo.h
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/interface/DDEcalPreshowerAlgo.h. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/BuildFile.xml.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/BuildFile.xml
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/plugins/BuildFile.xml. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalAPDAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalAPDAlgo.cc
769 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 768 warnings (767 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalBarrelAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalBarrelAlgo.cc
800 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 799 warnings (798 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc
800 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 799 warnings (798 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalEndcapAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalEndcapAlgo.cc
799 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 798 warnings (797 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalEndcapTrap.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalEndcapTrap.cc
520 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 519 warnings (518 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalPreshowerAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/DDEcalPreshowerAlgo.cc
780 warnings generated.
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
Suppressed 779 warnings (778 in non-user code, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/module.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/plugins/module.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/plugins/module.cc. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalAPDAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/src/DDEcalAPDAlgo.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/src/DDEcalAPDAlgo.cc. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalBarrelAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/src/DDEcalBarrelAlgo.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/src/DDEcalBarrelAlgo.cc. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalBarrelNewAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/src/DDEcalBarrelNewAlgo.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/src/DDEcalBarrelNewAlgo.cc. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalEndcapAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/src/DDEcalEndcapAlgo.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/src/DDEcalEndcapAlgo.cc. Compile command not found.
clang-tidy -export-fixes tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalPreshowerAlgo.cc.yaml -header-filter '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/.*' src/Geometry/EcalCommonData/src/DDEcalPreshowerAlgo.cc
Skipping /build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300/src/Geometry/EcalCommonData/src/DDEcalPreshowerAlgo.cc. Compile command not found.
gmake[2]: Leaving directory '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300'
gmake[2]: Entering directory '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300'
>> Local Products Rules ..... started
>> Local Products Rules ..... done
Changed files:   /src/Geometry/EcalCommonData/plugins/module.cc
  /src/Geometry/EcalCommonData/plugins/DDEcalBarrelAlgo.cc
  /src/Geometry/EcalCommonData/plugins/DDEcalEndcapAlgo.cc
  /src/Geometry/EcalCommonData/plugins/BuildFile.xml
  /src/Geometry/EcalCommonData/plugins/DDEcalPreshowerAlgo.cc
  /src/Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc
  /src/Geometry/EcalCommonData/plugins/DDEcalAPDAlgo.cc
  /src/Geometry/EcalCommonData/plugins/DDEcalEndcapTrap.cc
  /src/Geometry/EcalCommonData/BuildFile.xml
  /src/Geometry/EcalCommonData/src/DDEcalBarrelAlgo.cc
  /src/Geometry/EcalCommonData/src/DDEcalEndcapAlgo.cc
  /src/Geometry/EcalCommonData/src/DDEcalPreshowerAlgo.cc
  /src/Geometry/EcalCommonData/src/DDEcalBarrelNewAlgo.cc
  /src/Geometry/EcalCommonData/src/DDEcalAPDAlgo.cc
  /src/Geometry/EcalCommonData/interface/DDEcalBarrelNewAlgo.h
  /src/Geometry/EcalCommonData/interface/DDEcalEndcapAlgo.h
  /src/Geometry/EcalCommonData/interface/DDEcalAPDAlgo.h
  /src/Geometry/EcalCommonData/interface/DDEcalPreshowerAlgo.h
  /src/Geometry/EcalCommonData/interface/DDEcalBarrelAlgo.h
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/module.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalBarrelAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalEndcapAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/BuildFile.xml.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalPreshowerAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalBarrelNewAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalAPDAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/plugins/DDEcalEndcapTrap.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/BuildFile.xml.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalBarrelAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalEndcapAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalPreshowerAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalBarrelNewAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/src/DDEcalAPDAlgo.cc.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalBarrelNewAlgo.h.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalEndcapAlgo.h.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalAPDAlgo.h.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalPreshowerAlgo.h.yaml
Working on tmp/slc7_amd64_gcc700/code-checks/Geometry/EcalCommonData/interface/DDEcalBarrelAlgo.h.yaml
clang-apply-replacements tmp/slc7_amd64_gcc700/code-checks
gmake[2]: Leaving directory '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300'
gmake[1]: Leaving directory '/build/yana/DD4HEP/Sim/ECal/CMSSW_11_0_X_2019-06-26-2300'
```

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
this looks like `code-checks` not `code-format`

**Comment by ianna** [comment]
> this looks like `code-checks` not `code-format`

yep, I copied the command from the previous PR that failed at code-checks :-)

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna thanks for this cleaning. Since you move DDEcalEndcapTrap.cc into the plugins directory, could you please embed there also the corresponding .h file, following our code rules?
For the rest I think the PR is ok to move forward

**Comment by ianna** [comment]
@fabiocos this is done in the subsequent PR

**Comment by fabiocos** [comment]
@ianna ok, I will merge this one first in next IB, I see the update in #27402

**Comment by fabiocos** [comment]
+1

**Pull request merged**
