### PR TITLE
make HLT use "schedule" [12.1.X]

### PR DESCRIPTION
**Pull request by missirol**
backport of #35858 #36019

TSG would like to backport #35858 to `12_1_X` in view of an upcoming update of `ConfDB`.

(#36019 needs to be backported with it as well, to maintain a unit test functional.)

The goal is to ease the work of HLT developers, making `12_1_X` behave the same as `12_2_X` in terms of the name of the `cms.Schedule` provided by HLT configs.

More information can be found in #35842 and #36237.

This PR is merely technical, and no changes are expected.

#### PR description:

Copied from the description of #35858:

> The first step towards the resolution of #35842 could be the renaming of HLTSchedule to schedule, using one of the standard HLT customisation functions. This PR is an attempt at that.
>
> The final solution will have to come eventually with a change in ConfDB.
> 
> Standalone configs in test/ that use/assume HLTSchedule have been ignored for the moment (except for one that I know is used used to run in unit tests).
> 
> Merely technical; no changes expected.

#### PR validation:

`addOnTests` and unit tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#35858 #36019 

Goal: user support for HLT development in `12_1_X`.

### CODE REVIEW

**Comment by missirol** [comment]
backport of #35858

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by srimanob** [comment]
+Upgrade

For the upgrade part, backport of https://github.com/cms-sw/cmssw/pull/36019

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical backport of #35858 and #36019, to be used for HLT menu sudies and development

**Pull request merged**
