### PR TITLE
Modify scale regex in NanoAOD to catch NNLOPS weights

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Modifies the scale weights regex in GenWeightsTableProducer to store the NNLOPS weights

These weights corrected the underlying NLO MC to the NNLO accuracy. Without them, the NNLOPS MC is not useful. The weights have the normal format, but with -NNLOPS after them. Just change the regex to consider this as well

#### PR validation:

Confirmed that it works for a NNLOPS samples and does not affect others. Tested, for example

/WWJTo2L2Nu_NNLOPS_TuneCP5_13TeV-powheg-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
assign generators

**Comment by mariadalfonso** [comment]
+xpog 
no difference in tests as expected

**Comment by santocch** [comment]
+1

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
