### PR TITLE
Added skimming filter for disappearing muons [13_0_X Backport]

### PR DESCRIPTION
**Pull request by revering**
#### PR description:

Backport of #40666 to 13_0_X for 2023 data taking.

### CODE REVIEW

**Comment by youyingli** [comment]
@kskovpen , this is the backport of #40666 . Please mark "backport" and test.

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40666

**Comment by perrotta** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by youyingli** [comment]
Hi @perrotta , could you also test it?

**Comment by perrotta** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
