### PR TITLE
[12_4_X] Update the autoSkim.py for the Run3 skims and removed unused PD

### PR DESCRIPTION
**Pull request by sam7k9621**
#### PR description:

Addressed the comments in #38479

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

12_4_X backport of #38792

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38792

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
urgent
 * should go into the next 12_4_X

**Comment by tvami** [comment]
@cms-sw/orp-l2 the master of this PR has been in IBs for a while now, can we merge this?

**Comment by perrotta** [comment]
> @cms-sw/orp-l2 the master of this PR has been in IBs for a while now, can we merge this?

As soon as @cms-sw/pdmv-l2 signs it, yes
By the way, this PR backports **both** https://github.com/cms-sw/cmssw/pull/38479 and https://github.com/cms-sw/cmssw/pull/38792

**Comment by tvami** [comment]
I pingged Kirill

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1
- this PR backports both https://github.com/cms-sw/cmssw/pull/38479 and https://github.com/cms-sw/cmssw/pull/38792
- the net result is that the file autoSkim.py in 12_4_X gets synchronized with the master after the merging of this PR

**Pull request merged**
