### PR TITLE
Phase2-hcx228 Add possibility of mapping DetId/TriggerId to ModuleId and viceversa

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add hooks for going  from DetId or TriggerDetId to ModuleId and vice versa

#### PR validation:

Tested with a test code in DataFormats/ForwardDetId/test and standard matrix

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1
it seems, that 334 problematic histograms in DT do not connect  with this PR

**Comment by kpedro88** [comment]
It's not entirely clear to me that the comparison differences are unrelated to this PR, though in principle I don't see what in this PR would change results.

**Comment by bsunanda** [comment]
It cannot be the PR which is causing this issue as all the new codes are unused so far.

**Comment by kpedro88** [comment]
Are you sure it couldn't be caused by the change in `HGCSiliconDetId::geometryCell()`?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
