### PR TITLE
BMTFTriggerAlgoSelector InputTag change for HeavyIons

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is the requested PR which corrects the Input Tag for the module during Heavy Ions configuration.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @panoskatsoulis 
since the master points to the 10_4 branch now please also make a backport PR to 10_3_X.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@panoskatsoulis if this is needed as I believe for HI data taking, a 10_3_X backprot should be provided

**Comment by fabiocos** [comment]
+1

**Pull request merged**
