### PR TITLE
Mc weights slimmer

### PR DESCRIPTION
**Pull request by govoni**
New dataformat added to have in the miniAODs a slimmed version of the MC weights.
Tested locally on a privately generated sample, in CMSSW_7_1_14.

### CODE REVIEW

**Comment by mmusich** [comment]
-1 
needs a rebase

**Comment by covarell** [comment]
-1

**Comment by gpetruc** [comment]
Hi Pietro.

Can you restart from something more recent, e.g. latest 7_6_X prerelase?

Giovanni

**Comment by govoni** [comment]
Ciao Giovanni, I will restart from scratch in the CMSSW_8 something and will make a new PR.

**Comment by lgray** [comment]
Looks like all that needs to be done is:
```
rebase -i --onto CMSSW_8_0_X MCWeightsSlimmer~2 MCWeightsSlimmer
```

**Comment by govoni** [comment]
I redid from scratch here:

https://github.com/cms-sw/cmssw/pull/12101

**Comment by slava77** [comment]
-1
@govoni please close this PR

**Pull request closed without merging**
