### PR TITLE
DBOutputService: Removed deprecated methods

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

The PoolDBoutputService interface (and its Derived class OnlineDBOutputService ) contains methods that have been deprecated in favour of new methods providing the same functionalities with a more explicit signature concerning the payload object ownership policy.  Since all of the clients of the old interface in CMSSW have been migrated to the new interface, in this PR we proceed to remove the deprecated methods.

#### PR validation:

Unit and integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
after merging of #36366 this needs a rebase (file `RecoEgamma/EgammaTools/test/GBRWrapperMaker.cc` has already been taken care of)

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
> This branch has conflicts that must be resolved

@yuanchao tests should have been started after conflicts are resolved. @ggovi I think you'll need to rebase to a later release (tho it seems today's IB is actually broken, so maybe rebase tomorrow)

**Comment by perrotta** [comment]
Please rebase on top of latest CMSSW_12_3_X_2021-12-13-2300, which contains the conflicting PR #36366
It is not broken, as far as I can see...

**Comment by ggovi** [comment]
Replaced by https://github.com/cms-sw/cmssw/pull/36490

**Comment by tvami** [comment]
-1 
 * PR is closed

**Pull request closed without merging**
