### PR TITLE
Removing UP15 suffix from Samples used for >=2017 WFs

### PR DESCRIPTION
**Pull request by boudoul**
Greetings,
This PR is a simple proposal to remove the UP15 suffix from Workflows used in the phase1,phase2 relvals. This suffix was intended to be used for run2 WFs < 2017 and can generate confusion in the output names in the relval sample, like a recent one (2018 scenario) : 
/RelValNuGun_UP15/CMSSW_9_0_0_pre4-PU25ns_90X_upgrade2018_realistic_v4-v1/DQMIO

I let PdmV ( @fabozzi , maybe one should update the other L2 PdmV in the list ) comment, this is just a proposal ...

### CODE REVIEW

**Comment by fabozzi** [comment]
indeed this is the case for all other relvals...

**Comment by fabozzi** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
