### PR TITLE
Updated HF Raddam V2 Implementation

### PR DESCRIPTION
**Pull request by jwwetzel**
This PR updates the HF raddam simulation with a newer dose map and recalibration values.

### CODE REVIEW

**Comment by civanch** [comment]
@jwwetzel , In  HFDarkening class data are const, I do not see why these data are member of a class and are assigned to 2-dim array in class constructor. It is unusual. It would be natural to define this a const data. Of course, if you foresee further refit of these values then it may be left as it is but you will need to provide an interface for modification.

**Comment by civanch** [comment]
@jwwetzel , also if class handle floats, then all operations better to be float including inline functions of HFDarkening.

**Comment by jwwetzel** [comment]
Hi @civanch - The original damage model was based on the HEDarkening.cc class which had (and I think retains) a similar construction.  It is for clarity of understanding the doses as a function of true HF construction.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
-1
abuse of magic numbers.
Sorry @jwwetzel these constants appear to me as completely non-sense, and the code is impossible to maintain. Please restructure your classes.

**Comment by jwwetzel** [comment]
The HFDarkening class was used to compute the recalibration factors, and passed all sanity checks in terms of results.

Please see talk here describing the values and where they originate from.  https://indico.cern.ch/event/400319/contribution/4/attachments/801660/1098684/HFCorrFactors_v2.pdf

**Comment by diguida** [comment]
@jwwetzel 
thanks for the documentation.
From a quick look it looks like you have the same functional form, but different parameters according to the `ieta` bin and the depth.
I would do the following:
* for each depth, define 3 arrays, one per each parameter, with as many elements as the `ieta` bins
* define the formula only once
* when computing the correction, you first sanitise the input (i.e. check that the input values are correctly within the boudaries), then you apply the parameters of the corresponding depth to the unique formula.

C++14 offers you many ways to achieve this...

Finally, maybe the darkening could become part of the HF detector description in the SIM geometry: I am not an expert on this, but maybe this requires more careful thinking.

**Comment by diguida** [comment]
Also, as privately pointed out by @mmusich I see that the bins are evaluated on the fly in `HFDarkening::dose`. I am pretty sure all this parametrisation is well described in the SIM geometry. My recommendation would be therefore to base your representation of the radiation damage on the HF topology.

**Comment by jwwetzel** [comment]
Thank you very much for the comments - I will work on this a bit today yet.

The reason the bins are evaluated on the fly is because the previous radiation model was not parametrized in a way that matched the true HF towers.  The new dose map I retrieved these values from had closer mapping to the true HF, but it is not exact, so these radii correspond specifically to this radiation damage model and not to the true HF geometry, (although they are close).

**Comment by davidlange6** [comment]
@jwwetzel - so what is the status of this PR - should we close it?

**Comment by jwwetzel** [comment]
Hi @davidlange6, 

I would propose that unless there are fatal issues with this plugin, the PR should go forward.

This plugin has been used successfully in the SLHC releases of CMSSW for several years now.  Unless there are serious interfacing issues foreseen, I do not believe an overhaul of the existing code is necessary.

Of course if there are important CMSSW considerations that I am aware of, I would gladly address them.

**Comment by civanch** [comment]
@jwwetzel , this code is simple and is working but it was created for SLHC where simplest requirement was applied: to get results asap. When we merge SLHC code to our development release we are trying also to clean it up using c++11/14 constructions, to be sure that it is thread safe, to be sure that it is not using extra memory, extra CPU, and is good from point of view of future maintenance. So, it is natural to add some improvements.

**Comment by franzoni** [comment]
hello @jwwetzel 
AlCa is asked opinion about this PR at today's orp meeting.
The comments above by @diguida and @mmusich remain valid. In one of your comment after the advice you intended to take on some of the suggestions, are you still meaning to ?
Cheers, @franzoni

**Comment by abdoulline** [comment]
A reminder/query  has been sent to James on January 18 via HCAL CMSSW HN,
now re-sent directly (with several involved people in Cc).

**Comment by jwwetzel** [comment]
Closing this PR and opening a new one.

**Pull request closed without merging**
