### PR TITLE
[RECONSTRUCTION-XPOG] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
- Convert unit tests to use `<test ...command="cmd"/>` instead of using `FW unit tests driver`
- Make sure that test can run from its dedicated test directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction
technical, no changes in comparisons

**Comment by smuzaffar** [comment]
@cms-sw/xpog-l2 can you please review this? This is just a technical update

**Comment by perrotta** [comment]
merge

**Pull request merged**
