### PR TITLE
[Backport] Making miniAOD low pt tracks threshold tunable for 10_6_X (#33777)

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This is a backport to 10_6_X of #33777 

#### PR validation:

All the tests running

#### Further references

BPH Jamboree December 2020 [here](https://indico.cern.ch/event/979184/contributions/4148171/attachments/2163278/3650677/MiniAOD_Run3_Adriano_JamboreeDic2020.pdf)

xPOG Meeting February 2021 [here](https://indico.cern.ch/event/994581/contributions/4181429/attachments/2196037/3712976/xPOG%20Run3%20MiniAOD%20BPH%20Feb2021.pdf)

Further reference [here](https://github.com/AdrianoDee/miniaodstudies/blob/main/README.md)

For a complete documentation, trk4bph meetings: [1](https://indico.cern.ch/event/983890/), [2](https://indico.cern.ch/event/975219/), [3](https://indico.cern.ch/event/968995/) , [4](https://indico.cern.ch/event/964780/), [5](https://indico.cern.ch/event/963424/), [6](https://indico.cern.ch/event/955820/)

### CODE REVIEW

**Comment by AdrianoDee** [comment]
N.B. most of the changes to `PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc` comes from `code-format` checks.

**Comment by perrotta** [comment]
backport of #33777

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 1380 differences found in the comparisons

106X is a production release and this PR is changing outputs of the standard workflows.
This is not allowed by change policy.

- You can change the PR to have no change by default configuration e.g. only with run2_miniAOD_devel, or/and `(bParking & run2_miniAOD_UL)`

**Comment by AdrianoDee** [comment]
@slava77  thanks. Would something like this work?

for `lostTracks_cfi.py`

```

from Configuration.Eras.Modifier_bParking_cff import bParking
bParking.toModify(lostTracks, fillLostInnerHits = True)
(bParking & run2_miniAOD_UL).toModify(lostTracks, minPtToStoreLowQualityProps = 0.0)

from Configuration.Eras.Modifier_run2_miniAOD_devel_cff.py import run2_miniAOD_devel
run2_miniAOD_devel.toModify(lostTracks, minPtToStoreLowQualityProps = 0.0)

```

and for `packedPFCanidates_cfi.py`

```

from Configuration.Eras.Modifier_run2_miniAOD_devel_cff.py import run2_miniAOD_devel
run2_miniAOD_devel.toModify(packedPFCandidates, minPtForLowQualityTrackProperties = 0.0)

from Configuration.Eras.Modifier_bParking_cff.py import bParking
(bParking & run2_miniAOD_UL).toModify(packedPFCandidates, minPtForLowQualityTrackProperties = 0.0)

```

**Comment by slava77** [comment]
> @slava77 thanks. Would something like this work?

I'd use something shorter:
```python
(bParking | run2_miniAOD_devel).toModify(
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33877	dfbfb78
- code changes are in line with the PR description and the follow up review: 
    - the backport is correct; the extra code formatting in PATPackedCandidateProducer.cc and packedPFCandidates_cfi.py is acceptable
    - the changes are enabled only for `bParking | run2_miniAOD_devel` to satisfy the no-change policy
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
    - this signoff relies on changes in physics observed in the 12X PR #33777 (see the PR description there and pre-signoff plots from the bot https://github.com/cms-sw/cmssw/pull/33777#issuecomment-845583418)

**Comment by qliphy** [comment]
+1

**Pull request merged**
