### PR TITLE
[14_2_X] TICLv5a : Improve skeleton linking and parameters tuning

### PR DESCRIPTION
**Pull request by waredjeb**
This is a backport of #46539 

This PR improves the current Skeleton Linking
- New Parameters: tuned parameters for hadronic reconstruction.
- Code refactoring: simply code by refactoring pieces
- Modified TICLGraph: modified logic for traversing the graph and build components

- Small changes to TICLDumper: allow to run TICLDumper with TICLv4. It will consume SuperClusters (new with TICLv5) only in TICLv5

New parameters have been included also at HLT 

The performance against TICLv4 can be found in the DPS approval talk https://indico.cern.ch/event/1462666/contributions/6158255/attachments/2940573/5170734/TICLv5_DPS_version3.pdf

Should be tested with a .203 workflow

E.g.
```
test parameters:

    - workflow_opts= -w upgrade
    - workflow = 29896.203, 29691.203, 29691.204
    - enable = profiling, hlt_p2_timing
```

Edit 06/11/2024:

 - `hltTiclTracksterLinks_cfi` and `hltTiclTracksterLinksUnseeded_cfi`,  Both of them were Unseeded with no differences between them, for consistency I removed `hltTiclTracksterLinksUnseeded_cfi` fixing the Egamma sequence accordingly
 - I 've added the L1Seeded module and sequence for the Recovery Tracksters, it is not used but I added it for consistency with `hltTiclTracksterLinksL1Seeded_cfi`

### CODE REVIEW

**Comment by mmusich** [comment]
@waredjeb, can you clarify what's the purpose of the backport?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by waredjeb** [comment]
> > It would be nice to have in 14_2_X
> 
> is there any plan to use such feature in 14_2_0? Otherwise technically 14_2_X is closed for feature requests and only bug-fixes are acceptable.

This is a bug-fix, the previous configuration was bugged because of tuning of the parameters done on a bugged geometry

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/46539 to 14.2.X
   * overall rationale for the backport remains unclear, see https://github.com/cms-sw/cmssw/pull/46822#issuecomment-2506234082, though it should not harm having this in 14.2.0.

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46539

**Comment by mmusich** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
