### PR TITLE
[RFC] GPU-version of the RawToDigi algorithm (9.4.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Based on #21321, so far I've only added back the removed code.
Next steps are to
  - clean up the history
  - review the actual code and workflow

@slava77, @perrotta : this it not for integration, only for discussion.

@sushildubey171, @felicepantaleo FYI.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
I'm curious how it will deal with CUDA code...

**Comment by slava77** [comment]
-1

Resubmit to master, please.


On Nov 16, 2017 6:46 PM, "cmsbuild" <notifications@github.com> wrote:

The tests are being triggered in jenkins.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/cmssw/pull/21341#issuecomment-345002566>, or mute
the thread

**Comment by fwyzard** [comment]
> Resubmit to master, please.

Can we limit the comments to the useful ones, please ?
I explicitly wrote that *this it not for integration, only for discussion* .

When it will be ready for integration, we will submit it for whatever branch we need it to be in.

**Comment by slava77** [comment]
On 11/17/17 12:26 AM, Andrea Bocci wrote:
>     Resubmit to master, please.
> 
> Can we limit the comments to the useful ones, please ?

I will not provide useful comments until it's in the master.

**Comment by fwyzard** [comment]
> I will not provide useful comments until it's in the master.

OK, we'll do without. Such a tragic loss.

**Comment by slava77** [comment]
On 11/17/17 5:38 AM, cmsbuild wrote:
> # Reco comparison results: 0 differences found in the comparisons


DQM diff looks clean as well, ignoring
random differences in  /PixelPhase1V/Run summary/TrackingParticle, which
are apparently fixed only in 10_0_X

**Comment by fwyzard** [comment]
> DQM diff looks clean as well

Thanks. That's more than expected, since - in its current state - this PR does not touch any production code or workflows, only adding new modules.

**Comment by fwyzard** [comment]
Looks like we need an unrelated fix to the LLVM tool file, along the lines of
```diff
--- /opt/cmssw/slc7_amd64_gcc630/cms/cmssw/CMSSW_9_4_0/config/toolbox/slc7_amd64_gcc630/tools/selected/llvm-cxxcompiler.xml     2017-11-09 22:31:49.000000000 +0100
+++ ./llvm-cxxcompiler.xml      2017-11-17 17:43:46.287736802 +0100
@@ -11,6 +11,7 @@
     <flags REM_CXXFLAGS="-Werror=maybe-uninitialized"/>
     <flags REM_CXXFLAGS="-Werror=unused-but-set-variable"/>
     <flags REM_CXXFLAGS="-Werror=return-local-addr"/>
+    <flags REM_CXXFLAGS="-Werror=potentially-evaluated-expression"/>
     <flags REM_CXXFLAGS="-fipa-pta"/>
     <flags REM_CXXFLAGS="-frounding-math"/>
     <flags REM_CXXFLAGS="-mrecip"/>
@@ -24,7 +25,6 @@
     <flags CXXFLAGS="-Wno-unknown-pragmas"/>
     <flags CXXFLAGS="-Wno-unused-command-line-argument"/>
     <flags CXXFLAGS="-ftemplate-depth=512"/>
-    <flags CXXFLAGS="-Wno-error=potentially-evaluated-expression"/>
     <runtime name="LD_LIBRARY_PATH" value="$LLVM_CXXCOMPILER_BASE/lib64" type="path"/>
     <runtime name="PATH" value="$LLVM_CXXCOMPILER_BASE/bin" type="path"/>
     <runtime name="COMPILER_RUNTIME_OBJECTS" value="/opt/cmssw/slc7_amd64_gcc630/external/gcc/6.3.0"/>
```

**Comment by fwyzard** [comment]
@smuzaffar , with respect to https://github.com/cms-sw/cmssw/pull/21341#issuecomment-345122445 , it looks like 
```sh
scram build COMPILER='llvm compile'
```
does not play nice with CUDA code: it picks up the llvm/clang flags, but still uses gcc as the host compiler.

A clean solution could be to add
```xml
<flags CUDA_FLAGS="-ccbin $(LLVM_CXXCOMPILER_BASE)/bin/clang++"/>
```
to the `llvm-cxxcompiler.xml` tool file.

However that will result in 
> ```
> >> Compiling  /home/fwyzard/CMSSW_9_4_0/src/EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu 
> nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
>```
because CUDA supports only up to clang 3.9 :-(

Can you think of a way to disable building the CUDA code when the compiler is not gcc ?
We should keep in mind that gcc 7 is also going to fail for the same reason.

**Comment by davidlange6** [comment]
> On Nov 23, 2017, at 5:11 PM, Andrea Bocci <notifications@github.com> wrote:
> 
> @smuzaffar , with respect to #21341 (comment) , it looks like
> 
> scram build COMPILER='llvm compile'
> does not play nice with CUDA code: it picks up the llvm/clang flags, but still uses gcc as the host compiler.
> 
> A clean solution could be to add
> 
> <flags CUDA_FLAGS="-ccbin $(LLVM_CXXCOMPILER_BASE)/bin/clang++"/>
> to the llvm-cxxcompiler.xml tool file.
> 
> However that will result in
> 
> >> Compiling  /home/fwyzard/CMSSW_9_4_0/src/EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu 
> nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
> 
> because CUDA supports only up to clang 3.9 :-(
> 
> Can you think of a way to disable building the CUDA code when the compiler is not gcc ?
> We should keep in mind that gcc 7 is also going to fail for the same reason.

For LLVM, perhaps we have some updates to make in our LLVM build as it does not yet require cuda.
 
https://github.com/llvm-mirror/clang/commit/6d4cb407f117d080e04cf6b8ca200ee01c7b502f

but the lack of llvm>3.9 support means that we do need a long term solution to avoid issues here...

gcc7 support seems like a bigger issue we had forgotten about...

**Comment by fwyzard** [comment]
> For LLVM, perhaps we have some updates to make in our LLVM build as it does not yet require cuda.
> llvm-mirror/clang@6d4cb40

This is something different, and a possible long-term approach: using llvm/clang to build the device code instead of nvcc. One still relies on the CUDA runtime and libraries, but uses a standard compiler: https://llvm.org/docs/CompileCudaWithLLVM.html .

The problem I mentioned above instead happens when using nvcc for the device code, and clang for the host code (instead of gcc).

> but the lack of llvm>3.9 support means that we do need a long term solution to avoid issues here... 
> gcc7 support seems like a bigger issue we had forgotten about...

Honestly I can only see two long-term solutions for using CUDA in CMSSW:
  - we wait for or work on the missing feature, and then move to llvm for building all the GPU-related production code (device and cpu, including the whole of cmssw)
  - we stick to the supported approach and compilers, and keep at least one build architecture supported by CUDA

**Comment by makortel** [comment]
Let me note (since it's not reported by cmsbuild) that the `edmWriteConfigs` fails with
```
The executable will return success (0) so scram will continue,
but no cfi files will be written.
An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load /.../tmp/slc6_amd64_gcc630/src/EventFilter/SiPixelRawToDigi/plugins/EventFilterSiPixelRawToDigiGPUPlugins/libEventFilterSiPixelRawToDigiGPUPlugins.so because libcuda.so.1: cannot open shared object file: No such file or directory
```
Probably not the most important thing, but something to be dealt with eventually.

**Comment by fwyzard** [comment]
It's on my list of things to fix...

Thanks,
.Andrea

**Comment by sushildubey171** [comment]
@makortel ,
@fwyzard 
This error occurred because cuda was not setup. To run the GPU code we need to setup the cuda.

Thanks,
Sushil

**Comment by fwyzard** [comment]
Actually, yes and no, depending on what you mean.

You do *not* need to "scram setup cuda" any more from CMSSW 9.4.0 onwards:
the include files and libraries necessary to build and link CUDA code are
set up automatically.

However libcuda.so and some other libraries necessary to actually run CUDA
code are not setup automatically, to avoid conflicts if there already  is
CUDA installed on the machine.

Ciao,
.Andrea

**Comment by slava77** [comment]
@fwyzard @felicepantaleo 
should we expect any more discussion in this PR, to move it from [RFC] to a normal one?
This thread has been silent for some time now.
Please clarify.
Thank you.

**Comment by felicepantaleo** [comment]
@slava77 we have scheduled a small hackathon in a couple of weeks to finalize this PR and create a template for future ones.

**Comment by fwyzard** [comment]
The new development branch for this is [cms-patatrack/GPU_SiPixel_RawToDigi_100X](https://github.com/cms-patatrack/cmssw/tree/GPU_SiPixel_RawToDigi_100X).

**Pull request closed without merging**
