### PR TITLE
MTD digitization: add position dependence to BTL amplitudes

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is based on the update of the BTL digitization discussed in https://indico.cern.ch/event/1254512/contributions/5270125/attachments/2595148/4479504/MTDDPG_BTL_position_20230217.pdf . A position dependence of the amplitude measured in the sensors at the two extremities of the crystal is introduced, with values from tunable parameters, currently from BTL test beam studies.

The BTL digitization validation is updated accordingly to monitor this effect.

#### PR validation:

The code has been used to produce the results shown in the presentation above

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Are differences from PR test expected, @fabiocos ? Thx.

**Comment by fabiocos** [comment]
@srimanob I would say so. As you can see, I have added a smearing to the amplitude that was not there before for BTL, this is clearly changing the random number history for the digitization of MTD, and it reflects on the changes observed, which will trigger small changes in whatever is using it. The change in the amplitudes at the two SiPMs does not trigger big observable changes because only this PR is adding histograms to monitor this, and because in the reconstruction the final result is anyway an average, which should keep things unchanged.

**Comment by emanueleusai** [comment]
+1

**Comment by fabiocos** [comment]
@srimanob @cms-sw/orp-l2 this PR might conflict with #41083 by @ctarricone . I would suggest to move forward earlier with this one, while finalizing the newest code, and then rebase that on top of this, if needed.

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Comment by fabiocos** [comment]
@perrotta according to git everything looked ok, I'll have a look at the status of the code, but presumably it is ok also in this way, thanks

**Pull request merged**
