### PR TITLE
[124X backport] Fix rare crash of the HLT in case the muon OI DNN does not find a good seed strategy

### PR DESCRIPTION
**Pull request by JanFSchulte**
Backport of #38721 to 124X for HLT.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
urgent

Fix needed by HLT for online operations in 12_4_X.

**Comment by missirol** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- https://github.com/cms-sw/cmssw/pull/38721 backport

**Comment by qliphy** [comment]
+1

**Pull request merged**
