### PR TITLE
Enable comparison of HF minBias feature bit readout in CaloLayer1

### PR DESCRIPTION
**Pull request by nsmith-**
backport of #22348 
For use in online DQM at P5 for commissioning running.  Includes a merge of #20465 because it was left unmerged for several months on master, and ended up only in 10_1_X.  Once this is added to DQM tag collector, #20465 can be removed.

### CODE REVIEW

**Comment by nsmith-** [comment]
please test

**Comment by thomreis** [comment]
Hi @nsmith- is it expected that this adds 1 MB of histograms?

**Comment by nsmith-** [comment]
The 10_1_X PR adds only 1 kB, which means the extra MB is coming from #20465, in which case that is xpected (in fact that PR shows about 1 MB added)
If CaloLayer1 is becoming large relatively speaking, I can look into reducing some histograms.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
