### PR TITLE
miscellaneous improvements in `CondFormats/PCLConfig`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a follow-up to https://github.com/cms-sw/cmssw/pull/38195, introducing miscellaneous improvements to the `CondFormats/PCLConfig` package.
   * added integer and string parameter size `enum`s for not yet used parameters and changed the logic to calculate the payload version
   * fully templated also the `AlignPCLThresholdsWriter` writer class;
   * improved the `printAll()` method of `AlignPCLThresholdsHG` in order to give a more synoptic view of the parameters;
   * complemented unit tests in order to test both LG and HG classes;

#### PR validation:

run the dedicated unit tests: `scram b runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
> -1
Not clear from the [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4c313f/25360/runTheMatrixINPUT-results/138.4_PromptCollisions+RunMinimumBias2021+ALCARECOPROMPTR3+HARVESTDPROMPTR3/step2_PromptCollisions+RunMinimumBias2021+ALCARECOPROMPTR3+HARVESTDPROMPTR3.log) what is the reason of failure. I am not expecting this to affect any workflow.

**Comment by tvami** [comment]
+1
 * test pass, no unexpected diffs
 * PR is according to the description

**Comment by qliphy** [comment]
+1

**Pull request merged**
