### PR TITLE
Fix crash in CorrelationConditions uGT emulator 

### PR DESCRIPTION
**Pull request by rekovic**
Missing instantiation of candEtSumVec.  Also added checks of types.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
@rekovic 
please ask for L2 privileges for "L1"

**Comment by Martin-Grunewald** [comment]
please test

**Comment by rekovic** [comment]
@Martin-Grunewald 
> please ask for L2 privileges for "L1"
 
PR https://github.com/cms-sw/cms-bot/pull/650.  Hopefully granted soon.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
