### PR TITLE
[Fireworks][Clang-tidy] make deleted function public

### PR DESCRIPTION
**Pull request by smuzaffar**
We have over 25K clang-tidy warnings about `deleted member function should be public [modernize-use-equals-delete]`. 7.5K of these come from Fireworks sub-system.
Locally tested, it build and all of the `modernize-use-equals-delete` warnings are fixed.

[a]
```
Fireworks/Core/interface/FWGenericParameter.h:78:3: warning: deleted member function should be public [modernize-use-equals-delete]
  FWGenericParameter(const FWGenericParameter&) = delete;                   // stop default
  ^
Fireworks/Core/interface/FWGenericParameter.h:79:29: warning: deleted member function should be public [modernize-use-equals-delete]
  const FWGenericParameter& operator=(const FWGenericParameter&) = delete;  // stop default
                            ^
Fireworks/Core/interface/FWParameterBase.h:47:3: warning: deleted member function should be public [modernize-use-equals-delete]
  FWParameterBase(const FWParameterBase&) = delete;                   // stop default
  ^
Fireworks/Core/interface/FWParameterBase.h:48:26: warning: deleted member function should be public [modernize-use-equals-delete]
  const FWParameterBase& operator=(const FWParameterBase&) = delete;  // stop default

```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by alja** [comment]
+1 Thank You!

**Comment by perrotta** [comment]
+1
(I take https://github.com/cms-sw/cmssw/pull/34665#issuecomment-888497218 as a signature for visualization, even if it did not trigger a change of state)

**Comment by perrotta** [comment]
merge

**Pull request merged**
