### PR TITLE
[DB] [LLVM16]Fix set but unused variables warnings

### PR DESCRIPTION
**Pull request by smuzaffar**
CLANG IBs (which now use clang16) has a lot of warnings like [a]. This PR fixes few of these

[a]
```
warning: variable 'XXX' set but not used [-Wunused-but-set-variable]
```

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_1_CLANG_X

**Comment by smuzaffar** [comment]
please test
lets test for product arch/IB

**Comment by tvami** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
