### PR TITLE
[14.0.X] TkAlignment: Multi-IOV Zmumu mode, fixes to DMR averaged, PV trends

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/45015

#### PR description:

This PR introduces following updates to the TkAl All-in-one validation tool:
   * multi-IOV mode for the Zmumu validation tool
   * small fixes to the PV trend and DMR luminosity-weighted validation tools

#### PR validation:

PR validation: code-checks, code-format and successful unit tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/45015

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild ping?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- Verbatim backport of #45015

**Comment by rappoccio** [comment]
+1

**Pull request merged**
