### PR TITLE
RivetInterface fixes+updates

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

* Fix problem that leads to nan cross sections since Rivet 3.1.1 (Rivet 3.1.0 in 11_1 is ok)
* Add check for nan cross section to unit tests, to prevent this from going unnoticed again
* Add test for yodamerge (failed a couple of times in the past when changes to the CMSSW python configuration were made)
* Pass new Rivet AnalysisHandler options for (de)selecting weights, weight cap, etc.

#### PR validation:

* Passes new test that cross section is not nan
* New options behave as expected for selecting weights

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

* Will need to backport to 11_2

### CODE REVIEW

**Comment by agrohsje** [comment]
please test

**Comment by intrepid42** [comment]
Ok, the order of tests did not go as planned: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b315a6/12984/unitTests/log.txt

Is there any way to have them run in the intended order and not in parallel?

**Comment by smuzaffar** [comment]
@intrepid42 , you can force the order by adding the unit test dependency e.g
```
<test name="TestA" command="TestA.sh"/>
<test name="TestB" command="TestB.sh">
  <flags PRE_TEST="TestA"/>
</test>
```
this will instruct scram ro run `TestA` before `TestB`

**Comment by intrepid42** [comment]
Thank you @smuzaffar!

Tests should run in correct order now, and I also added a test for yoda2root

**Comment by mrodozov** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by agrohsje** [comment]
+generators

**Comment by silviodonato** [comment]
+1

**Pull request merged**
