### PR TITLE
Fix a.clone(b=dict(c=None)) (94X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #22413 to help phase1 FastSim tracking backporting. Original description

> I noticed that
> 
> ```python
> a = cms.PSet(b = cms.PSet(c = ...))
> d = a.clone(b=dict(c=None))
> ```
> 
> did not remove `d.b.c`. This PR adds a unit test for this case and attempts to fix it.

Tested in 9_4_10, no changes expected.

@angirar @ssekmen @pmaksim1

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by ssekmen** [comment]
are these errors related directly to this PR?

**Comment by Dr15Jones** [comment]
The `testPythonParameterSet` unit test failure is definitely not from this pull request and it looks like `condTestRegression` is not either since the latter fails when trying to find a different CMSSW release.

**Comment by ssekmen** [comment]
Thanks, that was also my guess.
Could we please merge this asap so we can proceed with the FastSim backports?

**Comment by kpedro88** [comment]
please test
`condTestRegression` was working last week in 94X, let's just try again to be safe

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
