### PR TITLE
Btag cond format

### PR DESCRIPTION
**Pull request by HeinerTholen**
This pull request was originally here: #7633

@ferencek and Petra Van Mulders suggested to reopen it on 7_4_X since it does not affect the standard reco. The merge conflict from the last PR has been resolved.

EDIT: This PR was opened on 7_5_X, it wouldn't be needed anymore if this one is accepted: #7796

### CODE REVIEW

**Comment by pvmulder** [comment]
This PR consists of added functionality for storing and reading b-tag scale factors from the database, necessary for the start of Run 2. As @HeinAtCERN pointed out, there is no impact on the reco sequence.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@HeinAtCERN:
Reco has approved #7796. You say in this PR that #7867 will not be needed if #7796 is approved. Can we close or give -1 to this PR now, or would you like to wait until #7796 is merged?

**Comment by HeinAtCERN** [comment]
@cvuosalo 
It seems I confused them before. From our side the PR should be merged into 7_4_X, which is the one here (#7867). Now I assumed that all 7_4_X  would be merged into later versions automatically. Is it the case? Otherwise #7796 (against 7_5_X) needs to be merged as well.

**Comment by slava77** [comment]
It's more straightforward to assume no automatic forward ports are done and to submit to all needed branches.

**Comment by cvuosalo** [comment]
+1

for [#7867] d9733d3

This PR adds functionality for storing and reading b-tag scale factors from the database, necessary for the start of Run 2. This PR is not expected to change reconstruction. It is derived from #7633, which was closed. It is the same as the #7796, but for 74X instead of 75X. #7796 has already been tested and approved by Reco. 

Reco code changes are satisfactory.

Jenkins tests against [CMSSW_7_4_X_2015-02-19-1400] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7867/2771/summary.html) show no problems or significant differences.

**Comment by HeinAtCERN** [comment]
Sorry for asking, but here has been no progress for more then a week. Will the responsible people sign off just before a new release comes out? Same for #7796.

**Comment by slava77** [comment]
Alca and DB signatures are still missing.
The RECO signature is in some sense secondary for this PR.

**Comment by HeinAtCERN** [comment]
Do you know whom to ping for Alca and DB?

**Comment by slava77** [comment]
The list of  people resonsible is in the first message from the github bot:
@cerminar, @diguida, @ggovi, @mmusich

**Comment by HeinAtCERN** [comment]
Ah, got it, thanks.

**Comment by ggovi** [comment]
+1

**Comment by diguida** [comment]
+1
It is the same as the #7796, but for 74X instead of 75X. #7796 has already been tested and approved by Alca.

**Comment by HeinAtCERN** [comment]
@ggovi, would you also approve the PR at 7_5_X? It's the same code, the PR is #7796.

**Comment by HeinAtCERN** [comment]
@cvuosalo 
there was an new commit, that you already confirmed at #7796. Would you also approve this commit here again? Thanks.

**Comment by cvuosalo** [comment]
+1

For #7867 a3321729c41106ac7f5cc819baa6cd4df9dcca55

A small change was made since this PR was approved by Reco. The new version looks OK to this reviewer. Jenkins tests are still OK. The twin PR #7796 for 75X has also been approved by Reco.

**Comment by ferencek** [comment]
@davidlange6, can you please merge this PR (it's been fully approved for more than a week and its 75X equivalent #7796 has already been merged)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
