### PR TITLE
Phase2-hgx357 Add a new version of HGCalCellOffest to provide a more correct results for the cell areas

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new version of HGCalCellOffest to provide a more correct results for the cell areas

#### PR validation:

Use  the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
A note on warning, not about this PR

>> Analyzing  src/SimG4CMS/Calo/src/HcalTestNumberingScheme.cc 
src/SimG4CMS/Calo/src/CaloSD.cc:423:102: warning: Called C++ object pointer is null [core.CallAndMessage]
  423 |       edm::LogVerbatim("CaloSim") << "CaloSD: EndofEvent entered for container " << k << " with " << theHC[0]->entries()
      |                                                                                                      ^~~~~~~~~~~~~~~~~~~
1 warning generated.

FYI @bsunanda @civanch

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch Please approve this again

**Comment by bsunanda** [comment]
@civanch Please approve

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
