### PR TITLE
Merge .h with .cc files in RecoEcal/EgammaClusterProducers

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Part of the series of PRs that merges `.h` files with the `.cc` files of the plugins in the RecoEcal subsystem.

This has already been done for the RecoEgamma subsystem (see e.g. https://github.com/cms-sw/cmssw/pull/32438, https://github.com/cms-sw/cmssw/pull/32613, https://github.com/cms-sw/cmssw/pull/32362, https://github.com/cms-sw/cmssw/pull/32266, https://github.com/cms-sw/cmssw/pull/32259).

It makes maintaining the plugins much easier and also excludes the possibility to wrongly include plugin header files (as happened in Validation/EcalClusters and fixed in the second commit of this PR).

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+

**Review by jpata — COMMENTED** [review]
Was renaming `RecoEcal/EgammaClusterProducers/interface/EcalBasicClusterLocalContCorrection.h -> RecoEcal/EgammaClusterProducers/src/EcalBasicClusterLocalContCorrection.h` intentional? Shouldn't it become .cc?

**Comment by guitargeek** [comment]
Yes, that was intentional. `EcalBasicClusterLocalContCorrection` is not a plugin itself, but a helper class for another plugin. That's why it was separate source and header.

**Comment by jpata** [comment]
+reconstruction
- technical, no changes expected or observed in the tests

**Comment by qliphy** [comment]
+1

**Pull request merged**
