### PR TITLE
[NanoAOD] Add number of B & C hadrons for GenJetAK8 and GenJet

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR adds the number of B/C-hadrons branches for `GenJetAK8` and `GenJet` tables . The same branches are removed from the `FatJet` table.  Addresses the Issue [here](https://gitlab.cern.ch/cms-nanoAOD/xpog-coordination/-/issues/68).

#### PR validation:

passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to `14_0_X`

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
tagging @arizzi

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
