### PR TITLE
DD4Hep: Fix XML variable references

### PR DESCRIPTION
**Pull request by vargasa**
### PR Description

See https://github.com/cms-sw/cmssw/pull/27564/#discussion_r308095587

#### PR validation:

```
 cmsRun DetectorDescription/DDCMS/test/python/testTracker2021Geometry.py
```

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - please, review

**Comment by ianna** [comment]
urgent

**Comment by kpedro88** [comment]
+1

**Pull request merged**
