### PR TITLE
Run3-sim153 Reorganize the codes relevant to forward detectors among Calo and Forward projects in SimG4CMS

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Reorganize the codes relevant to forward detectors among Calo and Forward projects in SimG4CMS

#### PR validation:

Tested using the scripts in SimG4CMS/Forward/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

problem is in timeout only.

**Comment by civanch** [comment]
please test

**Comment by rappoccio** [comment]
+1

**Pull request merged**
