### PR TITLE
Revamping ALCARECOTkAlCosmicsInCollisions with cosmicDCTracks

### PR DESCRIPTION
**Pull request by mmusich**
This PR revamps the `TkAlCosmicsInCollisions` ALCARECO workflow, making use of the newly available `cosmicDCTracks` from https://github.com/cms-sw/cmssw/pull/14520.
Added to the `autoAlCa` and RelVal matrix using the `NoBPTX` primary datasets.
Results obtained using the new worklow have been shown by @aspiezia (original author of the commits):
- [Tk Al meeting 6th July 2016](https://indico.cern.ch/event/536851/contributions/2216734/attachments/1304687/1949253/AnielloSpiezia_060716.pdf)
- [Tk Al meeting 13th July 2016](https://indico.cern.ch/event/536882/contributions/2241244/attachments/1308765/1957270/AnielloSpiezia_130716.pdf)

Outlook: addition of the producer to other PDs might be considered when a dedicated trigger becomes available.

attn: @mschrode @tlampen

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
rebased to avoid conflicts in `relval_standard.py`

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@vanbesien, @dmitrijus, @srimanob, @fabozzi, @hengne gentle reminder, proposed changes in your areas are minor.

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
