### PR TITLE
New dqm modules for PFHT paths.

### PR DESCRIPTION
**Pull request by parbol**
These updates add DQM modules for the new PFHT triggers.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
this one is fine in principle
but I believe it needs a rebase
@parbol could you do that?
thanks,
F.

**Comment by deguio** [comment]
-1
rejecting for now. pushing to this same branch will bring it back.
F.

**Comment by davidlange6** [comment]
seems this is now

**Pull request closed without merging**
