### PR TITLE
Update tag&probe package for egm [80X PR]

### PR DESCRIPTION
**Pull request by fcouderc**
same as PR #17820

egm tnp package has diverged from central repository for quite a while now.
Fix this by:

updating the central PhysicsTools/TagAndProbe to fulfil egm needs 
add a new package in cms-analysis for egm specific tnp tree making
This PR has been reviewed by muon conveners so that it does not change the muon tnp tree contents.
@HuguesBrun

It will be needed for legacy re-reco analysis and hence will also be committed in 80X (this PR) .

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
(same as #17820 in 91X)

**Comment by fcouderc** [comment]
Just to check if there is any problem with this one?
Thanks

**Comment by perrotta** [comment]
+1
Same as #17820 (in 91X) and #17959 (in 90X)

**Comment by perrotta** [comment]
@fcouderc : indeed it just slipped in. Thank you for checking!

**Comment by fcouderc** [comment]
thanks a lot!

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
