### PR TITLE
Run3-hcx170B Backport PRs #42463, #42496, #42549, #42550, #42557, #42578 to fix run3 scenario in CMSSW version 13_1_X due to issues in HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport PRs #42463, #42496, #42549, #42550, #42557, #42578 to fix run3 scenario in CMSSW version 13_1_X due to issues in HCAL

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport parts of PRs #42463, #42496, #42549, #42550, #42557, #42578

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cms-sw/orp-l2 @bsunanda 
How about this PR? Do we still need it?

**Comment by civanch** [comment]
@bsunanda , likely this PR may be closed.

**Comment by antoniovilela** [comment]
> @bsunanda , likely this PR may be closed.

Let's close.

**Comment by antoniovilela** [comment]
please close

**Pull request closed without merging**
