### PR TITLE
Fix Phase2 ditau HLT path (with DeepTau Isolation)

### PR DESCRIPTION
**Pull request by hsert**
#### PR description:

This PR implements the usage of Phase2 DeepTau training for ditau Phase 2 trigger, which was integrated with [PR 42662](https://github.com/cms-sw/cmssw/pull/42562). In the integrated version, Run2 training files were used. The problem with this implementation has been fixed and this PR proposes this fix and necessary changes. 

Hopefully it will fix the issue mentioned here: https://github.com/cms-sw/cmssw/issues/42862

The related JIRA ticket is [CMSHLT-3010](https://its.cern.ch/jira/browse/CMSHLT-3010)

#### PR validation:

The basic tests has been performed, suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html). 

There was no failed tests.

### CODE REVIEW

**Comment by mmusich** [comment]
@hsert please apply the code-checks as suggested in the comment https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925254525 .

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Tested positively running on `lxplus921` (chosen in order to enable the `AVX512F AVX512_VNNI` instructions, see https://github.com/cms-sw/cmssw/issues/42862#issuecomment-1925880266) preparing an area in the following way:
```console
cd CMSSW_14_0_0_pre3/src/
cmsenv
git cms-addpkg HLTrigger/Configuration
git cms-addpkg RecoTauTag/RecoTau
git remote add hsert git@github.com:hsert/cmssw.git; git fetch hsert
git cherry-pick ba5c296e89dc1ab1dd1dfc8e3d4f233fff693518
scram b -j 20
```
then editing the file `HLTrigger/Configuration/python/HLT_75e33_cff.py` as follows:
```diff
diff --git a/HLTrigger/Configuration/python/HLT_75e33_cff.py b/HLTrigger/Configuration/python/HLT_75e33_cff.py
index e5ef776f070..83498d1ffa2 100644
--- a/HLTrigger/Configuration/python/HLT_75e33_cff.py
+++ b/HLTrigger/Configuration/python/HLT_75e33_cff.py
@@ -237,6 +237,8 @@ fragment.load("HLTrigger/Configuration/HLT_75e33/paths/HLTAnalyzerEndpath_cff")
 
 fragment.load('L1Trigger.Configuration.GTemulator_cff')
 fragment.l1tGTProducer.GMTTkMuons = cms.InputTag("l1tTkMuonsGmt")
+fragment.l1tGTProducer.CL2Jets = cms.InputTag("l1tSCPFL1PuppiCorrectedEmulator")
+fragment.l1tGTProducer.CL2HtSum = cms.InputTag("l1tSCPFL1PuppiCorrectedEmulatorMHT")
 fragment.GTemulatorTask = cms.Task(fragment.l1tGTProducer, fragment.l1tGTAlgoBlockProducer)
 fragment.GTemulation_step = cms.Path(cms.Sequence(fragment.GTemulatorTask))
 fragment.load('L1Trigger.Phase2L1GT.l1tGTMenu_cff')
```

(these two lines are needed, because there was some change in the L1 collections recently, and it doesn't work out of the box in the existing RelVals), then running

```console
cmsDriver.py step3 -s HLT:@relval2026 --conditions auto:phase2_realistic_T25 --datatier GEN-SIM-DIGI-RAW -n -1 --eventcontent FEVTDEBUGHLT --geometry Extended2026D98 --era Phase2C17I13M9 --python step_3_cfg.py --no_exec --filein file:/eos/cms/store/group/offcomp_upgrade-sw/srimanob/phase2/HLT/Tau/step2.root --fileout file:step3.root --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000
cmsRun -e step_3_cfg.py
```

For the record I find in the `FrameworkJobReport.xml`

```console
$ more FrameworkJobReport.xml | grep CPUModels
    <Metric Name="CPUModels" Value="Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz"/>
```

Without the commit of this PR (`ba5c296e89dc1ab1dd1dfc8e3d4f233fff693518`) the test above fails with:

```
2024-02-04 19:39:40.029941: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: Incompatible shapes: [0,1,1,64] vs. [154]
	 [[{{node inner_muon_norm_1/FusedBatchNorm_1/Mul}}]]
----- Begin Fatal Exception 04-Feb-2024 19:39:40 CET-----------------------
An exception of category 'InvalidRun' occurred while
   [0] Processing  Event run: 1 lumi: 999 event: 5 stream: 0
   [1] Running path 'HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1'
   [2] Calling method for module DeepTauId/'hltHpsPFTauDeepTauProducer'
Exception Message:
error while running session: INVALID_ARGUMENT: Incompatible shapes: [0,1,1,64] vs. [154]
	 [[{{node inner_muon_norm_1/FusedBatchNorm_1/Mul}}]]
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
```

**Comment by mmusich** [comment]
+hlt for https://github.com/hsert/cmssw/commit/ba5c296e89dc1ab1dd1dfc8e3d4f233fff693518
   * see details of the cross-check at https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925882340
   * changes detected at https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925860451 are spurious and are coming from known workflow instabilities:
      * https://github.com/cms-sw/cmssw/issues/39803
      * https://github.com/cms-sw/cmssw/issues/43293
      * https://github.com/cms-sw/cmssw/issues/43790

**Comment by mmusich** [comment]
type tau, bug-fix

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2 please have a look, it would be great to have this in CMSSW_14_0_0

**Comment by mmusich** [comment]
@hsert, would you mind editing the PR title to be more readable for release notes?

**Comment by mmusich** [comment]
> sure, is it better now?

yes, thank you.

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
@hsert, this update did not make it into CMSSW_14_0_0_pre3 (the release milestone was changed in the meanwhile). Can you create a backport for it?

**Comment by mmusich** [comment]
> Can you create a backport for it?

to speed-up the process, I've taken the liberty of opening https://github.com/cms-sw/cmssw/pull/43912.

**Pull request merged**
