### PR TITLE
Update L1 menu tag for data RelVals and 2023/2024, Phase2 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR updates the Run3 2023/2024 and Phase2 MC GTs with the latest L1 Menu tag, i.e. ```L1Menu_Collisions2023_v1_0_0_xml``` as requested in [this CMSTalk post](https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-2023-l1-menu-tag-l1menu-collisions2023-v1-0-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/21177) [1].

In addition, it also updates the Run3 RelVal GTs. 

FYI @missirol @elfontan 

[1] https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-2023-l1-menu-tag-l1menu-collisions2023-v1-0-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/21177

The GT differences are here:

- **2023 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_design_v2/130X_mcRun3_2023_design_v3

- **2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_v3/130X_mcRun3_2023_realistic_v4

- **2023 cosmic realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_realistic_deco_v2/130X_mcRun3_2023cosmics_realistic_deco_v3

- **2023 cosmic design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_design_deco_v2/130X_mcRun3_2023cosmics_design_deco_v3

- **2023 realistic HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_HI_v3/130X_mcRun3_2023_realistic_HI_v4

- **2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2024_realistic_v3/130X_mcRun3_2024_realistic_v4

- **Phase2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun4_realistic_v2/130X_mcRun4_realistic_v3

#### PR validation:
Successfully tested with:
```runTheMatrix.py -l 139.001,12434.0,12834.0,23234.0 -j10 --ibeos```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport but will be backported to 130X

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by missirol** [comment]
Hi @saumyaphor4252 , I think the tests will fail, because the current HLT menu is not compatible with the latest L1T menu. What likely needs to happen is that we/HLT need to open a PR to update the HLT menus, then we can test this AlCa PR and the HLT PR together, and they will have to be integrated in the same IB. The same applies to the `13_0_X` backport.

The question is how quickly we need to prepare the HLT PR. How long can this PR wait? (1 day, a few days, or else)

**Comment by elfontan** [comment]
Thank you @saumyaphor4252 for the quick preparation of the PR and @missirol and @francescobrivio for the comments!
I do not see any urgency on the L1T side, this update is mostly useful to finalize the preparation and integration of the new HLT menu (compatible with the new L1 menu), so we are fine with STORM timelines.

**Comment by missirol** [comment]
> I'd prefer not to hold this more than 1 week if possible.

@francescobrivio , okay. Can you/AlCa also open the 13_0_X (without starting the tests)? We will need it to test the HLT PR in 13_0_X once we have it.

**Comment by francescobrivio** [comment]
> > I'd prefer not to hold this more than 1 week if possible.
> 
> @francescobrivio , okay. Can you/AlCa also open the 13_0_X backport (without starting the tests)? We will need it to test the HLT PR in 13_0_X once we have it.

Will do in few minutes

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/41016

**Comment by francescobrivio** [comment]
+alca

 - diffs are expected and I believe are related to the update of the HLT menu in #41016

**Pull request merged**
