### PR TITLE
Fix For Particle Level Producer

### PR DESCRIPTION
**Pull request by sscruz**
Small fix for ParticleLevelProducer.cc to decrease memory usage. @intrepid42 wants to follow this

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@perrozzi sorry, I guess that the above tests just show that this code doesn't break anything, but they do not run Rivet. Was this validated aside? Could we perhaps think to add a Rivet unit test?

**Comment by perrozzi** [comment]
@fabiocos as far as I can see this is a technical PR. I didn't test it myself, @sscruz should comment

**Comment by perrozzi** [comment]
ok we can think of adding unit tests

**Comment by sscruz** [comment]
Hi @perrozzi, @fabiocos,
indeed this is just a technical PR that doesn't affect the output of the module, it just reduces its memory consumption (which used to get very large when running over large samples). I tested both aspects locally myself in ~10k ttbar events, and indeed the output was the same in the memory usage didn't explode as before.

**Comment by davidlange6** [comment]
perhaps I just miss it - but what is the actual change other than code syntax?

std::unique_ptr<reco::GenParticleCollection> neutrinos(new reco::GenParticleCollection);
vs
auto neutrinos = std::make_unique<reco::GenParticleCollection>();

**Comment by sscruz** [comment]
hi @davidlange6 , doesn't the "new" reserve some memory that is not cleaned up afterwards? I really observed a significant decrease in memory usage...

**Comment by fabiocos** [comment]
I think that this specific change is harmless, my point is that for whatever Rivet related code we basically have no real test apart for standalone manual ones

**Comment by davidlange6** [comment]
Not in my understanding - both implementations do a new that is tracked by the unique_ptr and eventually given to the event.

http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique

________________________________

**Comment by ghellwig** [comment]
I second @davidlange6 that the introduction of `make_unique` should not affect the memory footprint.
The main advantage of `make_unique` is that it's exception-safe and you avoid a naked `new`.

**Comment by fabiocos** [comment]
@sscruz @perrozzi so is the reason of the memory reduction understood? And do we have finally a simple Rivet unit test?

**Comment by intrepid42** [comment]
@fabiocos What kind of unit test do you propose, and how should it be implemented? Is there anything for genJets that we can take as a starting point?

**Comment by fabiocos** [comment]
@intrepid42 see my comment https://github.com/cms-sw/cmssw/pull/22025#issuecomment-381727854 , run some reference analysis whose content is not supposed to change and compare the yaml output for instance. Changes in the generato moight imply the need to update the reference, but changes in the RivetInterface struucture could be tested in this way.

Apart for that, the question about this PR is still unanswered...

**Comment by sscruz** [comment]
hi @fabiocos , I'm afraid I didn't have the time to investigate much about this until now. I have identified that the memory usage decrease was due to me testing in two different samples... Apologies for that.
I still have to investigate further the reason of the high memory usage

**Comment by fabiocos** [comment]
@sscruz are you planning some development, or could we just close this PR and in case open a new one when something else is available?

**Comment by fabiocos** [comment]
@sscruz ok so let's close this PR

**Pull request closed without merging**
