### PR TITLE
Silent getSiThickness::InvalidSiliconDetid

### PR DESCRIPTION
**Pull request by rovere**

### CODE REVIEW

**Comment by kpedro88** [comment]
@rovere can you do the same for `getRadiusToSide()`? It hasn't been a problem so far, but just in case.

**Comment by rovere** [comment]
@kpedro88 there are plenty of other LogError in that same file.
I could easily s/LogError/LogDebug/g but I did only for the thickness since there we tested that the code is ok. Not sure about all the others (few of them return meaningless data if the check fails).
This has to be reviewed properly, better by an HGCAL geometry expert, for the current and future geometries.

**Comment by kpedro88** [comment]
Ah, there are a few more. I see `getWafer()` and `getCell()` as well.

I would prefer to suppress all of them, since they all have the same problematic behavior (triggering on HCAL DetIds).

**Comment by rovere** [comment]
Address #20658

**Comment by kpedro88** [comment]
backport of #20660

**Comment by kpedro88** [comment]
Let's deal with the other messages in a followup PR.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20659	adf09d2
- same as https://github.com/cms-sw/cmssw/pull/20660	dcd7d18  in 93X; to silence inappropriately issued LogError
- jenkins tests pass and show that the error message is gone from the logs

**Comment by davidlange6** [comment]
+1

**Pull request merged**
