### PR TITLE
L1 MHT and forward Jet fixes (75X backport 11676)

### PR DESCRIPTION
**Pull request by harmonicoscillator**
75X backport of #11676 
This PR depends on #11373 (and includes those commits since they are not merged yet).

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@richard-cms @mulhearn - this needs a rebase

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by richard-cms** [comment]
@davidlange6 Sorry I haven't had time to rebase this - does it still actually need a rebase, or are the relval errors transient?

**Comment by davidlange6** [comment]
@richard-cms - github seems happy now.. not sure why something changed

**Pull request merged**
