### PR TITLE
Add DQM for 90m beta star run observables

### PR DESCRIPTION
**Pull request by JanFSchulte**
This PR modifies the Online DQM to monitor the special pixel cluster and track collections used in the 90m beta star run. To be rolled back after this run is over.

(I'm not entirely sure we want this PR for the master branch, as these changes will never be used in 10_2_X...)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fabiocos** [comment]
@JanFSchulte a way of keeping track in the release of this modification would be just to link it to the CMSSW Era for the highBetStart run

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@JanFSchulte 
For master you should use Era or simply drop the PR... or will it be needed for some MC production?

**Comment by Martin-Grunewald** [comment]
@JanFSchulte 
No activity on this for a week - if no longer needed, please close this PR!

**Pull request closed without merging**
