### PR TITLE
HLT Migration to 10_0_2 template (10_0_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT Migration to 10_0_2 template
Basd on CMSSW_10_0_2

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport #22177

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Why did the relvals time out the first test??

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
