### PR TITLE
Fix for large number of efficiency_strings in HLT harvesting (9_4_X)

### PR DESCRIPTION
**Pull request by DryRun**
This is the 9_4_X version of https://github.com/cms-sw/cmssw/pull/21387.

Following up on https://github.com/cms-sw/cmssw/pull/21239, this PR reduces the large number of efficiency strings generated by the HLT harvesting configurations (Exotica, Higgs, and SMP). The large number corresponds to:
[all analyses] * [all triggers] * [all object types] * [all plot types]

I reduced the strings by only using the actual analysis-trigger combinations, rather than compiling all of the triggers into a single giant list. I also moved the creation of the postprocessors to functions, e.g. `make_exo_postprocessor()`.

For Exotica and SMP, the changes were relatively trivial, but hltHiggsPostProcessors_cff.py was much more involved... the lists used in the `for` loops were repeated re-initialized and appended to at random points in the code, making it very difficult to figure out what was going on. I ran some runTheMatrix tests to make sure I didn't accidentally remove any plots, but this might merit more scrutiny. Feedback would be welcome, if anyone has a suggestion for how to do this systematically.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
