### PR TITLE
Phase2-hgx295 Change copper cover to SS cover and remove many obsolete files of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change copper cover to SS cover and remove many obsolete files of HGCal geometry. Change of the cover property will affect predictions of 2026D86 workflow, while the cleanups will not affect any existing workflows used in relvals

#### PR validation:

Checked with all Phase2 scenarios in the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar Please check the code check script - the patch it created was grabage

**Comment by smuzaffar** [comment]
@bsunanda , I think issue is with the merging. there are some conflicts see https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-36061/26525/cms-checkout-topic.log

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild please test with #36021

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
@bsunanda 
It is better to describe what is the expected change in the PR description. 
From the code and fail comparison, 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2021-11-09-1100+c9be95/46753/validateJR.html,
I think it is touched only D86. And the cleanup part does not touch anything else.

**Comment by bsunanda** [comment]
@srimanob I added that in the description of the PR

**Comment by srimanob** [comment]
+Upgrade

This PR touches only Phase-2 D86, as seen in the test comparison. The cleanup part does not touch anything else.
Thanks very much @bsunanda for updating the PR description.

**Comment by qliphy** [comment]
+1

**Pull request merged**
