### PR TITLE
[103X] Change GT. FIX CSC timing for 2016 and 2017 MC. New HIon L1T menu V4_2_0 for HIon

### PR DESCRIPTION
**Pull request by lpernie**
.  CSC MC timing fixed in 2016 and 2017 MC GTs.

.  New HIon L1T menu V4_2_0 for HIon for:
> Data
run2_hlt_relval_hi and
run2_data_promptlike_hi
> MC
phase1_2018_realistic_hi

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of #25322

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
