### PR TITLE
[101X] [Update GT ] Fix PromptLike GT, Rereco GT, and Fix CTPPS geometry BUG in 2017

### PR DESCRIPTION
**Pull request by lpernie**
This PR should fix the issue reported in https://github.com/cms-sw/cmssw/issues/22449
Basically the only new TAGs in 101X_dataRun2_PromptLike_v4 should have been:
CTPPS geometry and ECAL PFrechit tags, but by mistake some other TAGs were changed.
I now created  a new TAG (101X_dataRun2_PromptLike_v5) that solve the problem
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v5/100X_dataRun2_PromptLike_v1

Similar comment for Rereco GT

Plus this PR fix a bug in 2017 CTPPS geometry (in MC and data TAGs)

### CODE REVIEW

**Comment by lpernie** [comment]
please test workflow 136.773

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
locally tested that fix wf 136.773

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
abort

**Comment by lpernie** [comment]
please test workflow 136.733,136.779,136.773

**Comment by lpernie** [comment]
@fabiocos wf 136.733,136.779,136.773 have passed now.
Once comparison is available I can re-trigger all the tests, but I assume all is fine now

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie as far as I can see, testing specific workflows adds them to the baseline short matrix, so repeating the test is not strictly necessary (and the comparison available is not done for tests already included in the map for the short matrix)

**Pull request merged**
