### PR TITLE
Backport codes for adding new data catalogs from Rucio storage description (RucioCatalog) and use it by default instead of trivial data catalogs (TrivialCatalog) #37278, and related bug fixes

### PR DESCRIPTION
**Pull request by nhduongvn**
#### PR description:

Backport to 12_5_X:
https://github.com/cms-sw/cmssw/pull/37278
https://github.com/cms-sw/cmssw/pull/39314
https://github.com/cms-sw/cmssw/pull/39727

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
claimed to be a backport but is submitted to master

**Comment by nhduongvn** [comment]
> -1 claimed to be a backport but is submitted to master
Hi @Martin-Grunewald, how can I make a pull request to submit to CMSSW_12_5_X?

**Comment by Martin-Grunewald** [comment]
See here http://cms-sw.github.io/tutorial.html, scroll down:
```
Or change the “base branch”, i.e. the one to which you want to have your changes merged. Starting from CMSSW_9_1_X and later the base branch for the latest development release is the master branch.
```

**Comment by Martin-Grunewald** [comment]
However, you need to make your changes within 12_5 as you can not submit a PR based on a later release to an earlier release without pulling in a larger number of unrelated commits.

**Comment by ChrisMisan** [comment]
-alca

- not a backport
- invalid commit structure

**Comment by nhduongvn** [comment]
This is a wrong backport so I cancel this pull request.

**Pull request closed without merging**
