### PR TITLE
CTPPS: directory rename Totem -> CTPPS (back-port of #15311)

### PR DESCRIPTION
**Pull request by jan-kaspar**
Several "Totem" directories renamed to simplify code sharing with other CTPPS detectors.

This is a back-port of #15311, see details there.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15317 77d408a29245d77247ec7d3fe68ff3063e09b4f4

Renaming TOTEM directories for CT-PPS. There should be no change in monitored quantities.

#15311 is the 81X version of this PR, and it has already been approved by Reco.

The changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-07-28-1100 show no significant differences, as expected.

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
