### PR TITLE
Add ParticleNet legacy discriminator scores and mass regression to MINIAOD

### PR DESCRIPTION
**Pull request by cmantill**
#### PR description:

Add back the ParticleNet legacy discriminator scores and mass regression for AK8 Jets. This allows a comparison with newer version of ParticleNet and may be useful in scenarios that fall out of the phase space of the newer ParticleNet training.
 
- Changes expected in the miniAOD and nanoAOD output. Added the following branches to nanoAOD: 
```
 FatJet_particleNetLegacy_QCD
 FatJet_particleNetLegacy_Xbb
 FatJet_particleNetLegacy_Xcc 
 FatJet_particleNetLegacy_Xqq 
 FatJet_particleNetLegacy_mass 
```

- Discussion took place at XPOG meeting on March 14th: https://indico.cern.ch/event/1382063/#10-pnet-legacy-in-v14

#### PR validation:

MiniAODv4+NanoAODv12 workflow in CMSSW_13_2_X

Backport to CMSSW_13_2_X

### CODE REVIEW

**Comment by jfernan2** [comment]
enable nano

**Comment by mandrenguyen** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by hqucms** [comment]
It seems a backport to 14_0_X is missing for this. Could you please make one, @cmantill ?

**Comment by hqucms** [comment]
> It seems a backport to 14_0_X is missing for this. Could you please make one, @cmantill ?

I made the backport here: https://github.com/cms-sw/cmssw/pull/44716

**Pull request merged**
