### PR TITLE
[ALIGNMENT] Fix DEVEL warnings on deprecated copy-constructors

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by aandvalenzuela** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by perrotta** [comment]
+alca

**Pull request merged**
