### PR TITLE
Madgraph 2.4.2 cards

### PR DESCRIPTION
**Pull request by lorusso7**
I update the  _DYToll01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff, DYToll012Jets_5f_NLO_FXFX_Madgraph_LHE_13TeV_cff, TTbar012Jets_5f_NLO_FXFX_Madgraph_LHE_13TeV_cff_ and _WTolNu01234Jets_5f_LO_MLM_Madgraph_LHE_13TeV_cff_ configuration file to use the new gridpack generated with Madggraph **2.4.2** .

### CODE REVIEW

**Comment by perrozzi** [comment]
this is meant to be used for Relval, right?

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
