### PR TITLE
Run3-gex164B Fix the bug in the RPC geometry - backport of the PRs #41907, #41921, #41990 from 13_2_X to 13_0_X

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix the bug in the RPC geometry - backport of the PRs #41907, #41921, #41990 from 13_2_X to 13_0_X

#### PR validation:

Use the overlap testing tool

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport the PRs #41907 #41921 #41990 from the master

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
