### PR TITLE
[14_0_X] Fixes for Alpaka Phase2 Pixel Reco

### PR DESCRIPTION
**Pull request by AdrianoDee**
Plain backport of #44874.

### CODE REVIEW

**Comment by fwyzard** [comment]
Looks good to me, as it's identical to #44874.
I'll check the impact on the HLT and sign.

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
> Looks good to me, as it's identical to #44874. I'll check the impact on the HLT and sign.

Note: I've preferred back porting all of it since it was simpler and the changes to Phase2 only were trivial and minimal fixes.

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44874.

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44874

**Comment by fwyzard** [comment]
Looks good from the HLT performance point of view.

#### before
```
Running 4 times over 10300 events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   683.6 ±   0.2 ev/s (10000 events, 98.0% overlap)
   687.3 ±   0.2 ev/s (10000 events, 99.1% overlap)
   684.3 ±   0.2 ev/s (10000 events, 99.0% overlap)
   690.9 ±   0.2 ev/s (10000 events, 98.3% overlap)
 --------------------
   686.5 ±   3.3 ev/s
```

#### after
```
Running 4 times over 10300 events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   683.8 ±   0.2 ev/s (10000 events, 98.9% overlap)
   688.4 ±   0.2 ev/s (10000 events, 98.6% overlap)
   689.3 ±   0.2 ev/s (10000 events, 98.7% overlap)
   686.6 ±   0.2 ev/s (10000 events, 98.7% overlap)
 --------------------
   687.0 ±   2.5 ev/s
```

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mmusich** [comment]
type bug-fix

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
