### PR TITLE
[12_4_X] Save EDMNANO in EcalPhiSymRecoSequence

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38835

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38835

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 139.005

**Comment by tvami** [comment]
type ecal,bugfix

**Comment by tvami** [comment]
urgent
 * should go into 12_4_4

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
+alca
- backport
- wf 139.005 passes
- differences only in msgLogger and MTD

**Comment by perrotta** [comment]
+1
- Merged in master since CMSSW_12_5_X_2022-07-24-0000

**Pull request merged**
