### PR TITLE
Test merge step

### PR DESCRIPTION
**Pull request by deguio**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@nclopezo 
are the tests having problems for this PR? is it normal that they take 20hrs?
I am asking because I added an extra step in the DQM tests, but it shouldn't take that much.

thanks,
F.

**Comment by nclopezo** [comment]
Hi, 
They had the issue discussed here: https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3169.html
I restarted them with CMSSW_7_5_X_2015-03-03-0200

**Comment by deguio** [comment]
ok,
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
Thanks @deguio

**Pull request merged**
