### PR TITLE
Run3-gex97 Add a coorected version of TotemTiming_Station.xml

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a coorected version of TotemTiming_Station.xml

#### PR validation:

This file needs to be include in the Reco Geometry scenario for PPS

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , @cvuosalo , I forget how we do in other cases: the first version is simply *.xml but the second v2/*.xml or v1/*.xml ?

**Comment by cvuosalo** [comment]
@civanch Starting with `v1` like this PR does is correct.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
