### PR TITLE
Fix Validation Script

### PR DESCRIPTION
**Pull request by ianna**
- Do not checkout packages locally
- Add Tracker topology

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
It's based on #13680

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by ianna** [comment]
@ggovi - it is based on the PR you've already approved.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
