### PR TITLE
Fix issues reported by static analyzer in CSCTriggerPrimitives

### PR DESCRIPTION
**Pull request by dildick**
The static analyzer of the latest IB shows quite a few issues with the CSCTriggerPrimitives code. I tried to address them in this pull request
* `static bool` was replaced by `static std::atomic<bool>`. this applies to all occurrences of `config_dumped`
* instances where `std::cout` was placed at the end of an `edm::LogDebug` were replaced by `std::endl` (shouldn't the compiler pick this up?)
* a few instances of local `static` variables in functions were made `const` instead where variables do not change after declaration
* 2D vector patterns in `CSCComparatorDigiFitter` were declared `const`

In addition, I removed `gemCustoms.py` in `SLHCUpgradeSimulations/Configuration` since it is no longer used. Finally, all specific customization functions in `gemGeometryCustoms.py` are outdated and were removed.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by dildick** [comment]
@smuzaffar I plan to update the code shortly with updated C++ style in relevant classes.

**Comment by dildick** [comment]
@smuzaffar can you run the style checker again?

**Comment by dildick** [comment]
`scram build code-checks` is not doing anything on lxplus in CMSSW930pre2:
<PRE>
-bash-4.1$ scram build code-checks
>> Local Products Rules ..... started
>> Local Products Rules ..... done
Unknow target code-checks
<PRE>

Code style is now compliant with conventions

**Comment by davidlange6** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
