### PR TITLE
Make surface deformation plots much faster

### PR DESCRIPTION
**Pull request by hroskes**
The time it takes to run the validation itself does not change noticeably. The time it takes to make the plots decreases by a lot (<1 minute per curve, down from >~10 minutes per curve). The plots themselves are identical to before.

Also some cleanup of unused templates in alternateValidationTemplates, without losing any functionality.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hroskes** [comment]
@cmsbuild sorry, I found a bug

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
