### PR TITLE
jetNDauChargedMVASel for nanoAOD electrons & muons for topMVA inputs

### PR DESCRIPTION
**Pull request by schoef**
#### PR description:

- Adding jetNDauCharged (number of charged tracks of jet associated with lepton) for electrons and muons in nanoAOD. This completes the list of input variables for various lepton MAV flavors and allows to evaluate them on nanoAOD.

- Added DQM plots

The variables amount to ~2.5 bytes/event, i.e. a 0.1% increase in the overall size as checked by @swertz 

Should be included in the next legacy and ultra-legacy nanoAOD production.

#### PR validation:

Tested in private top nanoAOD production

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by gouskos** [comment]
Hi @schoef @swertz a couple of comments.
(a) For future reference and compliteness, can you please add some material in the PR that shows the improvement in performance compared to other lepton-MVAs in CMS after including this variable?   
(b) Please add the corresponding DQM plot in PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
(c) Please convert int to uint8 [since I do not believe the charged track multiplicity associated to a lepton would exceed 255, right?]

**Comment by schoef** [comment]
@gouskos I did (b) and (c) and changed the naming to "jetNDauCharged" because "MVASel" serves no purpose. The variable is called jetNDauChargedMVASel in other context than the table in muon_cff and electron_cff which might be confusing. Do you prefer better naming or more consistent conventions?
(a) should be done by @kskovpen

**Comment by kskovpen** [comment]
@schoef @gouskos This is the standard variable also present in other existing leptonMVA configurations, so the inclusion of this variable would also be usable for other leptonMVA definitions.

**Comment by gouskos** [comment]
@schoef @kskovpen thanks for the follow up

**Comment by gouskos** [comment]
please test

**Comment by gouskos** [comment]
+xpog

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by swertz** [comment]
Thanks again for taking care @schoef ! Could you make a backport to 10_6_X?

@mariadalfonso I forget, will there be a v8 re-nanoAOD for non-UL samples? And if yes will it be in 10_6 or 10_2?

**Comment by mariadalfonso** [comment]
@swertz 

We will not have the v8 central re-nano for the EOY samples.
We can at most consider to re-nano with the V9 with 10_6_X version that contains the whole gen weights rewriting in 2021 if is of any need at that point

**Comment by swertz** [comment]
Thanks for clarifying!

**Pull request merged**
