### PR TITLE
SimDataFormats/PileupSummaryInfo : Changes needed to compile with macOS clang and libc++

### PR DESCRIPTION
**Pull request by gartung**
Root libeg needed to provide \_hepevt\_ symbol.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
i don't think (or rather I'm sure we don't) we want to bring in rootgraphics.

**Comment by gartung** [comment]
libeg is a electron/gamma simulation library

**Comment by davidlange6** [comment]
<tool name="rooteg" version="@TOOL_VERSION@">
  <info url="http://root.cern.ch/root/"/>
  <lib name="EG"/>
  <use name="rootgraphics"/>
</tool>

**Comment by davidlange6** [comment]
whoops - that comment didn't make it

tool name="rooteg" version="@TOOL_VERSION@"
  <info url="http://root.cern.ch/root/"/>
  <lib name="EG"/>
  <use name="rootgraphics"/>
</tool>

**Comment by davidlange6** [comment]
argh - seems I can't post xml

tool name="rooteg" version="@TOOL_VERSION@"
  info url="http://root.cern.ch/root/"/
  lib name="EG"/
  use name="rootgraphics"/
/tool

**Comment by gartung** [comment]
There might be some visualization included. I was just looking for a quick way to resolve _hepevt_.

**Comment by davidlange6** [comment]
this doesn't come from hepmc? I think @mdhildreth can help

**Comment by gartung** [comment]
I am using a newer version of the hepmc libary that does not include _hepmc_.

**Comment by smuzaffar** [comment]
does not SimDataFormats/GeneratorProducts/src/HepEvt.F provide this symbol? May be we are just missing the dependency on SimDataFormats/GeneratorProducts here?

**Comment by gartung** [comment]
I will try you suggestion.

**Comment by civanch** [comment]
please test

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
@gartung - http://lcgapp.cern.ch/project/simu/HepMC/download/

**Comment by gartung** [comment]
Still using HEPMC 2.06.07 in CMSSW_9_0_X branch of CMSDIST, which is NOT available.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
