### PR TITLE
Revive MF map and XML geometry visualization

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

Update code and scripts for the Eve visualization of MF map and XML geometries, which was no longer working.

#### PR validation:

Verified that the updated example configuration scripts work.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
+1

**Comment by alja** [comment]
@namapane 
I'm glad you still find the way to use TEve. Are you running event display remotely or through cvmfs?

BTW, I also saw you are using TEveDigitSets. This have been integrated recently integrated in web-eve (the coming root release 6.32) as ROOT::Experimental::REveDigitSet.

**Comment by namapane** [comment]
> @namapane I'm glad you still find the way to use TEve. Are you running event display remotely or through cvmfs?

Remotely (from a vnc session as plain X is too slow).
I use this code rarely but AFAIK it's the only way to visualize the MF and an XML geometry at the same time. 
Are there other tools that can be used to visualize an XML geometry directly with similar functionality?

> BTW, I also saw you are using TEveDigitSets. This have been integrated recently integrated in web-eve (the coming root release 6.32) as ROOT::Experimental::REveDigitSet.

Uhm actually I'm not the original author of this code (history goes back to the cvs->github migration), I just have been making some updates over time, but I'm not that fluent in the internals...

**Comment by alja** [comment]
@namapane Just for the test I setup cvmfs on my local desktop. Now I can run cmsRun and cmsShow from cvmfs locally. I chose cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre4 project. The cmsRun  Fireworks/Geometry/python/cmsRun_displayGeom_cfg.py opened eve main window. But the scene is empty. I will wait for the release (CMSSW_14_1_0_pre45 I guess) for this to be included and run. 

The test for this PR should be like the line below, right?
``cmsRun  Fireworks/Geometry/python/cmsRun_displayGeom_cfg.py``

**Comment by namapane** [comment]
@alja , here is what is get running 
`cmsRun  Fireworks/Geometry/python/cmsRun_displayGeom_cfg.py` :

image

One question, when you say you run cmsRun from cvmfs, how do you recompile the package?

I must say I have had variable success with different environments (al9/al8/different releases/running within a vnc session or from a linux machine connected to lxplus via ssh, etc. There seems to be some interplay between the architecture and release of the area where the job is started and the actual environment of the physical display. Typical errors I get are of this kind:
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: undefined symbol: LLVMInitializeAMDGPUTargetInfo, version LLVM_17 (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
I think I also got errors that resulted in nothing being displayed, but there was an error message printed out in the cmsRun output, can you check if there's any in yours?

For example: it ran fine in a CMSSW_14_1_0_pre3 area created on lxplus8 when connecting via ssh from the physical display of a private al9 machine at CERN, but I got an error on a  CMSSW_14_1_0_pre3 area created on lxplus**9** in the same environment. 
The same area that worked, does not if I follow the same steps but connect to the private machine via VNC. But the connection via VNC works in earlier releases (eg CMSSW_13_0_16)... I did not find the magic of what works and what not, 

If your local desktop runs al9, can you also try to ssh lxplus8, create a CMSSW_14_1_0_pre3 area, pick this update and recompile, and see if it works? That should be very close to the setup that was working for me (pre3 and el9).

**Comment by osschar** [comment]
We just figured out the libGL error: MESA-LOADER error on el9, you can fix it by doing:
```LD_PRELOAD="/lib64/libLLVM-17.so" cmsShow ...```
see https://cms-talk.web.cern.ch/t/phase2-geometry-visualization/41531

We run Fedora 39 (me) and 40 (Alja) on our desktops ... with cvmfs setup we can create CMSSW environment as usual, we use `el9_amd64_gcc12` or `gcc13` ... and then compile and run locally.

**Comment by namapane** [comment]
@osschar : cool thank you! It solves the problem. Here the MF map with overlaid a section of the MF geomretry, ran through a VNC connection from remote, in CMSSW_14_1_0_pre3 on el9_amd64_gcc12:

image

@alja Does the test now work for you?

**Comment by alja** [comment]
@namapane Great! I did test with cvmfs. It took some time (more than 10min) to create the project, but then it worked.

**Pull request merged**
