### PR TITLE
Fix to topHLTOfflineDQM package by removing warning message

### PR DESCRIPTION
**Pull request by soureek**
Commenting out warning message corresponding to presence of TriggerSummary collection.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
@Soureek89 please read https://www.python.org/dev/peps/pep-0008/
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

This is getting out of hand and I'm tired to point out every mistake you make.
Open google, type "<name of your editor> expand tabs", it should not be anything hard.

The cpp code looks fine, despite being otherwise hard to read.

**Comment by dmitrijus** [comment]
Also, I can't find a 81x version of it.

**Comment by dmitrijus** [comment]
+1

**Comment by Soureek89** [comment]
Please merge this PR if everything is all right. I see that the corresponding PR #15703 in 81X has already been merged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
