### PR TITLE
Move RecoLocalCalo/Castor modules to global types

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted legacy modules to global. This fixes the CMS deprecation warnings.

#### PR validation:

Code compiles without issuing a CMS deprecation warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
