### PR TITLE
"SCALLumi" histos renamed as "OnlineLumi"

### PR DESCRIPTION
**Pull request by acmbulla**
#### PR description:
Minimal changes. Changed the name of some histograms (and variables) that reported erroneously the nomenclature "SCAL", which is no longer used. "Online" is used instead.

#### PR validation:

Run the matrix to test the correctness of the names, Everything went good.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
Just out of curiosity, how is this changing DQMHistoSizes? Can it be just the change in the labels?

**Comment by mmusich** [comment]
> how is this changing DQMHistoSizes? Can it be just the change in the labels?

Good question,  I was also not expecting it. Curiously it seems concentrated on  workflow 1000.0. OTOH the bin-by-bin comparison shows only replacements (or spurious differences). How to reconcile the two?

**Comment by emanueleusai** [comment]
+1

- approving, as the change in size of the histos is not a showstopper

**Comment by mmusich** [comment]
hold 
  * I guess would be good to understand https://github.com/cms-sw/cmssw/pull/41220#issuecomment-1495443996 before merging

**Comment by mmusich** [comment]
@cmsbuild, please test
   * let's see if it reproduces

**Comment by perrotta** [comment]
merge

**Pull request merged**
