### PR TITLE
Add D98 DD4hep workflow for monitoring the instability

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Try to get some clue on instability of Phase-2 DD4hep workflow with previous baseline.

#### PR validation:
Job runs.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

The D98 DD4hep workflow runs fine.

**Comment by srimanob** [comment]
Note to @cms-sw/pdmv-l2 this PR is to follow the instability of Phase-2 DD4hep workflow.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
@cms-sw/reconstruction-l2 Do we need to do something to add back the comparison of 24834.911 ? Thanks.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
