### PR TITLE
[10.3]Change Gts. Fix geometry in LS2 GTs, and new HI 2018 MC GT

### PR DESCRIPTION
**Pull request by lpernie**
.  HI 2018 MC GT: add HCAL tags, new geom
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_HI_v4/103X_upgrade2018_realistic_HI_v6

.  Fix geom in 2019 GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_postLS2_design_v2/103X_postLS2_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_postLS2_realistic_v2/103X_postLS2_realistic_v3

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by boudoul** [comment]
Dear @lpernie , thanks for the update - For  my own curiosity , I was checking the difference beween the 2018 and 2019 GTs (*)  -  I was expecting only a difference in the geometry (and maybe few other things that I may have missed)  but instead I found that the 2019 is pretty outdated on many fronts (e.g most of the conditions are still from 2017)  - Is this intended ?  thanks

(*) https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_postLS2_realistic_v3/103X_upgrade2018_realistic_v7

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie could you please clarify the nature of the changes in HCAL? Are those which missed the last week deadline? BTW, @boudoul has an interesting comment about 2019 status...

**Comment by lpernie** [comment]
Hello All,
1) Those changes in HCAL are the 3 TAGs that HCAL fail to provide in time for pre5. So they are entering now. The GT with those changes have been given to PdmV, but we will need also to have it on autocond.
2) I am investigating a bit about the 2019 Tags. I was planning to answer @boudoul once I complete the investigation. Anyway, the fix introduced in the 2019 GTs goes in the right direction (is a bug fix) and can be approved anyway.

**Comment by fabiocos** [comment]
@lpernie as far as I can see the differences are concentrated in the wf 158 for HI, as one would expect. But they largely affect tracking plots, which looks a bit strange to me if the changes are just for HCAL. Do you understand it?

**Comment by lpernie** [comment]
Hello @fabiocos ,
indeed the [differences](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_HI_v6/103X_upgrade2018_realistic_HI_v4) are only about HCAL tags, and they do not affect tracking.
I saw those differences, but most fluctuation of 1 event in empty histograms.
Btw: I agree  that answer to @boudoul  goes beyond the scope of this single update. I will investigate that separately.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
