### PR TITLE
Hcal update hardcode calib

### PR DESCRIPTION
**Pull request by christopheralanwest**
Backport of PR #17895.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

no questions asked on the 'magic' :-) numbers , given that we have HcalHardcodeCalibrations.cc

More seriously:
are these values and changes reflect in database payloads 
in HcalLUTCorrsRcd or HcalLutMetadataRcd ?

@hatakeyamak @deguio @arunhep @walterjr @abdoulline

**Comment by christopheralanwest** [comment]
These changes only affect HcalLutMetadataRcd and not HcalLUTCorrsRcd. In the process of generating the Plan0 and Plan1 HcalLutMetadata conditions, the "granularity" and "threshold" values in HcalLutMetadataRcd were inadvertently changed to the (incorrect) values in the previous version of the hardcoded calibrations. We will provide updated HcalLutMetadataRcd conditions.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
