### PR TITLE
Changes in trigger path names for HLTriggerOffline/SUSYBSM

### PR DESCRIPTION
**Pull request by kmandal**
Some HLT path names have been changed to make SUSYBSM DQM package consistent with GRun menu.

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by deguio** [comment]
+1
@kmandal please rename this PR to something meaningful for future reference.
thanks,
F.

**Comment by davidlange6** [comment]
@kmandal - please change the title of this PR to be descriptive for the release notes.

**Comment by deguio** [comment]
+1
@kmandal please change the title of this PR.
it won't be merged otherwise.
(approving though)

**Comment by kmandal** [comment]
Hi,

   Sorry for my ignorance. Could you please suggest me how to change the
title of a PR?

Thanks,
Koushik

On Mon, Mar 30, 2015 at 9:25 PM, deguio <notifications@github.com> wrote:

> +1
> @kmandal <https://github.com/kmandal> please change the title of this PR.
> it won't be merged otherwise.
> (approving though)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8433#issuecomment-87733553>.
>



-- 
NISER, SPS



" *DON'T FORGET YOUR ROOT....*"

**Comment by davidlange6** [comment]
click the edit button next to the title on your pull request.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
