### PR TITLE
Phase2-hgx184 Add a new scenario D41 with T14+C8+I9+O3

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Define a new scenario D41 with the more recent version of HGCal geometry (C8). Also changes are made to overall system (O3 derived from O2) and MTD (I9 derived from I7) which need to be changed
 
#### PR validation:

New workflow needs to be defined but can work only after PR with new etl is merged

#### if this PR is a backport please specify the original PR:

It is not a backport

### CODE REVIEW

**Comment by kpedro88** [comment]
@bsunanda from the list in #26071, we also need to add M3 with the change from #25701. Can you coordinate with @bapavlov to incorporate this?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda please update PRs with rebase rather than merge. see http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by bsunanda** [comment]
@kpedro88 I forgot to rebase after merging. I did not think of committing and forgot about that. After tests were successful I simply committed. I am closing this PR and making a new one.

**Pull request closed without merging**
