### PR TITLE
Fixes and modifications on GEM TnP efficiency plots (backport of #42639, 13_1_X)

### PR DESCRIPTION
**Pull request by jo100sun**
#### PR description:

Backport of (#42639)[https://github.com/cms-sw/cmssw/pull/42639]. This PR introduces updates on GEM TnP efficiency plots and bugfix for the GEM edge distance calculation at TrackerMuon propagation. (#40554)[https://github.com/cms-sw/cmssw/pull/40554]

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is backport of (#42639)[https://github.com/cms-sw/cmssw/pull/42639]. We would like to introduce this changes for upcoming run.

@jshlee @watson-ij

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type muon, bug-fix

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by emanueleusai** [comment]
+1

- tests at P5 ok
- DQM differences in Muon plots as expected

**Comment by rappoccio** [comment]
+1

**Pull request merged**
