### PR TITLE
fillDescriptions fix for E/gamma Pixel Matching Modules: 91X

### PR DESCRIPTION
**Pull request by Sam-Harper**
91X backport of : https://github.com/cms-sw/cmssw/pull/18819

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #18819

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
Having said that, we do not need this in 9.1.0 as long as #18819 enters 9.2.0 .
We will use this PR privately, but it can be closed.

**Comment by perrotta** [comment]
+1
Same as  #18819 in the master
It is not needed for 91X, but in case  #18819 cannot enter the next 9.2.0 patch release probably HLT will ask to include this one in a 91X patch: otherwise, this PR can be simply closed

**Comment by slava77** [comment]
should this be closed?

**Comment by Sam-Harper** [comment]
I believe so. Not necessary any more I think. Thanks for the heads up.

**Pull request closed without merging**
