### PR TITLE
[LLVM10] L1Trigger and L1TriggerConfig fix clang warnings

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes clang 10 warnings 

#### PR validation:

builds without warnings with CLANG IB

### CODE REVIEW

**Comment by mrodozov** [comment]
please test for CMSSW_11_1_CLANG_X

**Comment by smuzaffar** [comment]
@mrodozov , no need to test it these PRs for CLANG IB. Just run tests for normal IBs

**Comment by mrodozov** [comment]
please test
let's see the comparison

**Comment by silviodonato** [comment]
Kind reminder @rekovic

**Comment by silviodonato** [comment]
merge
@rekovic please let me know if you have any objections

**Pull request merged**
