### PR TITLE
Tracking DQM: miscellaneous fixes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The aim of this PR is fix various plots in Tracking DQM:
   * the `DistanceOfClosestApproachToBSdz` plot originally included in https://github.com/cms-sw/cmssw/pull/27330 has x-axis range too small (actually ~ half of the statistics goes into the overflow bins right now, see e.g. https://tinyurl.com/smcjqap)
   * the target directory of the Tracking efficiency plots (using muons) is changed, solving long standing  issue https://github.com/cms-sw/cmssw/pull/23614#issuecomment-412922438
   * the file ` DQM/TrackingMonitorSource/python/TrackingSourceConfigTier0_Cosmic_cff.py` is apparently an unused copy of `DQM/TrackingMonitorSource/python/TrackingSourceConfig_Tier0_Cosmic_cff.py`, so it is removed.

#### PR validation:

Minimal standard integration tests have been run:
   * `runTheMatrix.py -l 11634.0 -t 4 -j 8 --command='-n 100'`
   * `runTheMatrix.py -l 7.22,7.21,7.4,7.3,138.1 -t 4 -j 8`

The Beam Spot distance of closest approach with the new x-axis looks like this:

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport and no backport is intended.
cc:
@mtosi @sroychow @arossi83

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by schneiml** [comment]
Hi @mmusich , while you are at it, please be aware of this observation: https://github.com/cms-sw/cmssw/pull/28622#issuecomment-577644454

Specifically:
> Tracking / TrackParameters / PUmonitoring: multi-filled, booked multiple times by multiple instances of the same analyzer.

This is not really a big problem since all analyzers fill the same plots with the same values, but after #28622 these plots will have an inflated number of entries (since all the fill's will go to the same histogram). Currently, the different module instances fill independent histograms and an arbitrary one of these will be saved in the end, which does not make much sense but is fine as long as all the modules produce the same output.

**Comment by mmusich** [comment]
@schneiml thanks for the heads-up but this goes well beyond the scope of this PR. Let's keep it separate. Thanks.

**Comment by jfernan2** [comment]
@mmusich Apart from the changes you described in the PR header, it looks like there are some plots which get no entries now in Tracking / TrackParameters / TrackEfficiency  , those with E/eff string in the name, I guess computing efficiencies
E.g. https://tinyurl.com/ucb95te
Is this change understood? Thanks

**Comment by mtosi** [comment]
@schneiml , sorry but I do not totally get your comment about plots in  
`Tracking/TrackParameters/PUmonitoring`

they are usual MEs booked in
https://cmssdt.cern.ch/dxr/CMSSW/source/DQM/TrackingMonitor/src/TrackingMonitor.cc#439
different instances of the _TrackingMonitor_ module should have the parameter

**Comment by mmusich** [comment]
>  Is this change understood? Thanks

@jfernan2 , yes addressed at: https://github.com/cms-sw/cmssw/pull/28823/commits/a5b5a166a464eefb9be27a317e1f26a9f954718a

re-tested with wf. 20434.0:

   * before:
image
   * after:
image

**Comment by jfernan2** [comment]
please test

**Comment by schneiml** [comment]
@mtosi to be more specific, e.g. `Tracking/TrackParameters/generalTracks/PUmonitoring/NumberOfPVtxVsGoodPVtx` is booked in wf 136.85 step3 by 
```
TrackingMonitor:TrackSeedMondetachedQuadStep@beginRun
TrackingMonitor:TrackSeedMondetachedTripletStep@beginRun
TrackingMonitor:TrackSeedMonhighPtTripletStep@beginRun
TrackingMonitor:TrackSeedMoninitialStep@beginRun
TrackingMonitor:TrackSeedMonjetCoreRegionalStep@beginRun
TrackingMonitor:TrackSeedMonlowPtQuadStep@beginRun
TrackingMonitor:TrackSeedMonlowPtTripletStep@beginRun
TrackingMonitor:TrackSeedMonmixedTripletStep@beginRun
TrackingMonitor:TrackSeedMonmuonSeededStepInOut@beginRun
TrackingMonitor:TrackSeedMonmuonSeededStepOutIn@beginRun
TrackingMonitor:TrackSeedMonpixelLessStep@beginRun
TrackingMonitor:TrackSeedMonpixelPairStep@beginRun
TrackingMonitor:TrackSeedMontobTecStep@beginRun
TrackingMonitor:TrackerCollisionSelectedTrackMonCommongeneralTracks@beginRun
```

I assume it's the same for all in this folder. IIRC there are more colliding groups in other workflows.

**Comment by jfernan2** [comment]
+1
For what this PR changes in terms of DQM

**Comment by silviodonato** [comment]
+1

**Pull request merged**
