### PR TITLE
fix for `TestDQMServicesDemo` unit test [12.1.X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of #35921

#### PR description:

This PR tries to fix the DQM unit test `TestDQMServicesDemo`.
It looks like some API calls in DQM-related scripts needed to be adjusted after the switch from uproot-3 to uproot-4.
See #35868 for some more details.

#### PR validation:

The relevant unit test now passes.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of #35921

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1
Thank you @mmusich

**Comment by qliphy** [comment]
+1

**Pull request merged**
