### PR TITLE
adding premixing PU 2017 workflows

### PR DESCRIPTION
**Pull request by fabozzi**
- adding premixing PU 2017 workflows (labelled as "UP17" workflows)
- same setup as used for relvals submitted in CMSSW_9_2_1 validation

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
hold

**Comment by fabozzi** [comment]
unhold

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
