### PR TITLE
Add QGL input variables in JME Custom-NanoAODs

### PR DESCRIPTION
**Pull request by nurfikri89**
This PR adds input jet variables needed for the quark vs gluon likelihood (QGL) in the JME Custom-NanoAODs. The variables are useful QGL developers when they need to train the likelihood for future new releases. 

The input variables are already calculated together with the QGL discriminant in the [main](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_18/PhysicsTools/NanoAOD/python/jets_cff.py#L569) NanoAOD production. They are not saved in the main NanoAODs by default.

This PR needs to be backported to 10_6_X, once merged, for the ultra legacy campaigns.

### CODE REVIEW

**Comment by nurfikri89** [comment]
FYI JMAR convenors @alefisico  @camclean

**Comment by santocch** [comment]
please test

**Comment by nurfikri89** [comment]
Closing this PR. Messed up the commit history. Will make a new one with fixes to jerc variables

**Comment by nurfikri89** [comment]
New PR for this addition is #29257.

**Pull request closed without merging**
