### PR TITLE
HLTTauValidation: changed DQMBaseFolder from HLT/TauRelVal to HLT/TAU…

### PR DESCRIPTION
**Pull request by slehti**
…/RelVal

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@slehti thanks !

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @slehti -does this not break HLTriggerOffline/Tau/data/QTDefault.xml?

**Comment by slehti** [comment]
> hi @slehti -does this not break HLTriggerOffline/Tau/data/QTDefault.xml?
Does one need to change the path there, too, from HLT/TauRelVal to HLT/TAU/RelVal? My tests run ok without touching that, so I'm not sure what the QTDefault.xml is for and what it will break.

**Comment by davidlange6** [comment]
if the qt test stuff is not used by the tau relval test perhaps it should be removed (either removed or fixed, not left as broken) @slehti

**Comment by davidlange6** [comment]
-1
pending requested changes

**Comment by jfernan2** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
