### PR TITLE
FixLumisPerJobSplittingFor2018

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Fix LumisPerJobSplitting For 2018 which changed from Prompt to Offline in
https://github.com/cms-sw/cmssw/pull/26417/files

#### PR validation:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=request-srimanob_RVCMSSW_11_0_0_pre5RunEGamma2018C__PHATTEST_RelVal_2018C_190831_214637_5994

#### if this PR is a backport please specify the original PR:
backport of https://github.com/cms-sw/cmssw/pull/27910

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
backport of #27910

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
