### PR TITLE
Phase2-hgx360W Provide a method in HGCALDDDConst to access the area of a cell

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provide a method in HGCALDDDConst to access the area of a cell

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@subirsarkar Please approve this

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
