### PR TITLE
Thread safe StorageAccounting

### PR DESCRIPTION
**Pull request by Dr15Jones**
Changed StorageAccounting so that all methods are thread-safe.
Also changed the iterface to avoid multiple lookups via strings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@bbockelm

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 why does the github label say this needs approval by alca and generators?

**Comment by smuzaffar** [comment]
@Dr15Jones , due to changes in following packages
  generator:  GeneratorInterface/LHEInterface
  alca: IORawData/SiPixelInputSources/

**Comment by Dr15Jones** [comment]
Please sign @bendavid @covarell @diguida @mmusich

**Comment by Dr15Jones** [comment]
Ping  @bendavid @covarell @diguida @mmusich It has been 22 days since I submitted this.
@davidlange6

**Comment by diguida** [comment]
+1
minimal changes for AlCa in `IORawData/SiPixelInputSources/src/PixelSLinkDataInputSource.cc`
@Dr15Jones sorry: I was confused by the bot.

**Pull request merged**
