### PR TITLE
HLtriggerOffline/Higgs path update (75X)

### PR DESCRIPTION
**Pull request by jasperlauwers**
Backport of #11206

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by jasperlauwers** [comment]
This has been merged in 76X 8 days ago and now is holding up other pull requests. Is there a reason why it didn't get merged yet?

**Comment by davidlange6** [comment]
as commented in this thread, validation in 76x is needed (which can happen once 760pre6 is built and run throw relval cycle)

**Comment by jasperlauwers** [comment]
Thanks for the explanation. The reason I am asking is because I was asked in #11342 to make a separate PR for adding a new path.
Do I understand correctly that the procedure to follow is to make a PR for that one commit separately and then rebase this one? And that the reason that #11342 doesn't need validation in 76x is because is doesn't make any changes to the code itself (although in this PR it are only two lines) ?

**Pull request closed without merging**
