### PR TITLE
GE21-ME21 segment reconstruction (backport of #39441, 12_4_X)

### PR DESCRIPTION
**Pull request by slowmoyang**
#### PR description:
Backport of #39441. This PR introduces the GE21-ME21 segment reconstruction.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This PR is a backport of #39441 and is opened under @emanueleusai 's [suggestion](https://github.com/cms-sw/cmssw/pull/39441#issuecomment-1263794531).

@jshlee @watson-ij

### CODE REVIEW

**Comment by clacaputo** [comment]
type gem

**Comment by clacaputo** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
+1

- test at p5 completed successfully
- PR deployed to online DQM systems

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39441

**Comment by perrotta** [comment]
hold
(see https://github.com/cms-sw/cmssw/pull/39441#issuecomment-1263794531 and previous entries in the github thread)

**Comment by perrotta** [comment]
Backport not needed any more (it was merged in the online DQM release, anyhow)

**Pull request closed without merging**
