### PR TITLE
Update input file in fwliteWithPythonConfig_cfg.py for 10_6_X

### PR DESCRIPTION
**Pull request by qliphy**
#### PR description:
Fix unit test issue in https://github.com/cms-sw/cmssw/pull/33843

#### PR validation:
Local test succeeded:  FWLiteWithBasicAnalyzer fwliteWithPythonConfig_cfg.py 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport from https://github.com/cms-sw/cmssw/pull/33464

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
