### PR TITLE
Made use of edm::RefCore thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
The internal caching done by an edm::RefCore is now thread safe. All uses of edm::RefCore were also changed to be thread-safe.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9114	2511d40
- changes in the code look OK
- jenkins tests pass and show no differences both in the fwlite and DQM monitoring comparisons with the baseline

**Comment by davidlange6** [comment]
+1

**Pull request merged**
