### PR TITLE
pedestal subtraction for PCC luminosity

### PR DESCRIPTION
**Pull request by benitezj**
#### PR description:

PCC luminosity is corrected for pedestal noise, mainly affecting low inst. lumi runs.
See presentation here (slide 4):
https://indico.cern.ch/event/845626/contributions/3551341/attachments/1901149/3138360/PCC_2017G.pdf

The code also includes a TGraph to check the pedestal value vs lumi section similar to the type1,2 corrections.

#### PR validation:

The code has been tested in local installation of 10_2_2, used for 2018 PCC luminosity.

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@benitezj Do you have a workflow to test the updates? Looks like no workflow in production or standard exercies the AlCaPCC PCL. Thanks.

**Comment by benitezj** [comment]
@tocheng ,  I'm not aware of any workflow tests, but I'm kind of new to PCL dev.  
Perhaps @samhiggie  may know better.

**Comment by pohsun** [comment]
@benitezj It is encouraged to have an automated unit test while adding a new plot. You could follow the description on [twiki:SWGuideDevelopersGuide#Add_tests_to_your_package](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDevelopersGuide#Add_tests_to_your_package) to build one.

**Comment by christopheralanwest** [comment]
please test

**Comment by benitezj** [comment]
@pohsun ,  I added a unit test for package.  Please have a look and let me know if it looks ok.

**Comment by pohsun** [comment]
@benitezj It looks fine. Have you tried to launch the test with `scram b runtests`? If the test results are fine, then we could proceed.

**Comment by christopheralanwest** [comment]
@pohsun These tests are run during the PR integration tests. The output is linked under "Unit Tests" [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-efef91/3739/summary.html).

**Comment by benitezj** [comment]
Yes, the test was run locally then in the PR test. Please proceed.  Thanks.

**Comment by fabiocos** [comment]
please test workflow 1020.0

**Comment by christopheralanwest** [comment]
+1

Thanks @fabiocos for finding the workflow that uses `CorrPCCProducer`

**Comment by fabiocos** [comment]
@benitezj in general it would be advisable to limit the use of git merge in preparing a PR, in particular your first commit could mimic an official merge. From what I can see anyway there should be no confusion in the branch history in my integration check:

```
*   903d345adafcc83653c5b154d67c64587be6928c (HEAD -> tmp/merge-test) Merged refs/pull/28452/head from repository cms-sw with cms-merge-topic
|\  
| * 70f3465dc5ed1df10aa1e6149a78e8189b55a415 (pull/28452_backup, cms-sw/refs/pull/28452/head) unit test for LumiAlCaRecoProducers
| *   21419581ea15b93179832a476707d69eeda5f7c3 .. Merge branch 'master' of github.com:cms-sw/cmssw
| |\  
| * | dc059848c73d9540de88439bf4d3e93f2ec887a9 fix code style
| * | fd78342229fd2109fdf3d9e864db9a3bef32b1c9 fix code style
| * |   083ab913300a4c436055bb8b98911910fc73ea64 update Merge branch 'master' of github.com:cms-sw/cmssw
| |\ \  
| * | | f7b3bd63c627d05d15471981e4e5fd24f19e8edf pedestal subtraction
| * | |   6088153661688efa1cb90784212e9b8960207df7 .. Merge branch 'master' of github.com:cms-sw/cmssw
| |\ \ \  
| * \ \ \   9ebd0abf008a608cea6dd61ae1b12ba58fe4d167 Merge branch 'master' of github.com:cms-sw/cmssw
| |\ \ \ \  
| * | | | | b2e324446d5b9b394dc0283f014403f4907060de pedestal subtraction
| * | | | |   f743bbf4261ee2785ba7afc592977f813f354c67 Merge branch 'master' of github.com:cms-sw/cmssw
| |\ \ \ \ \  
| * \ \ \ \ \   ab35e01174c1c0d4c3c55f75e9c77f6946c1165c Merge pull request #1 from cms-sw/master
| |\ \ \ \ \ \  
* | \ \ \ \ \ \   30a2ff8ff13aaa416259453b54ad0b62588edc91 (tag: CMSSW_11_1_X_2019-12-03-1100, official-cmssw/master, official-cmssw/HEAD, official-cmssw/CMSSW_11_1_X, from-CMSSW_11_1_X_2019-12-03-1100, CMSSW_11_1_X) Merge pull request #28501 from schneiml/dqm-local-bintobin
```

**Comment by fabiocos** [comment]
+1

**Pull request merged**
