### PR TITLE
bsunanda:Run2-alca56 Correct code for IsoTrack and PhiSymmetry calibration

### PR DESCRIPTION
**Pull request by bsunanda**
Useful for closure test with MC

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @davidlange6 The tests are failing because of DAS error in one example. It is happening in all PR's. Can this be fixed?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@sextonkennedy @davidlange6 We are getting this DAS error repeatedly for the past 3 days and this error is unrelated to may of the PR's and this holds up the integration

**Comment by davidlange6** [comment]
Yep. Other infrastructure we depend on isn't working. I guess since the pr is not signed or commented on its not a big delay



On 04 Aug 2016, at 19:47, bsunanda <notifications@github.com<mailto:notifications@github.com>> wrote:


@sextonkennedy<https://github.com/sextonkennedy> @davidlange6<https://github.com/davidlange6> We are getting this DAS error repeatedly for the past 3 days and this error is unrelated to may of the PR's and this holds up the integration

**Comment by bsunanda** [comment]
@mmusich Could you please review this PR and approve this. The failure is unrelated to this PR

**Comment by mmusich** [comment]
+1
(will need to re-rerun the tests)

**Comment by davidlange6** [comment]
@bsunanda @mmusich - we should not add a simulation dependency here. Could you move this plug in to your test directory (or there are other solutions, but this one looks to be the simplest)

**Comment by bsunanda** [comment]
@davidlange6 This is not dependence on simulation - only the same studies can be done to data and MC events.

**Comment by davidlange6** [comment]
You added a dependency on SimDataFormats….

On Aug 5, 2016, at 3:33 PM, bsunanda <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> This is not dependence on simulation - only the same studies can be done to data and MC events.

**Comment by bsunanda** [comment]
This package is meant to have all the algorithms for calibration. We need to apply the same code for data as well as MC. Recently the MC samples are produced with event weight not equal to 1. So we need to have dependence on the summary file with event weight. Now GenParticle is also MC information and stays in DataFormat. This Summary should ideally be located in the same place as GenParticle. Since it is not we get dependency on SimDataFormats. Putting the code in plugins or in test does not remove the dependency. So I do not understand the comment from David.
________________________________
________________________________

**Comment by davidlange6** [comment]
Hi @bsunanda - Sim dependencies are meant to be kept out of the mainstream plugins. eg, the reco should not need Geant4 or SimDataFormats (which is not DataFormats...) to run. I don't see this plugin used outside of tests, so I believe my solution is both correct and simple. (and its main purpose is to fill an tuple, so a test area is the right spot in any case)

**Comment by bsunanda** [comment]
Many of  the files in plugins (not the two which I just changed recently) uses SimDataFormats. The codes are meant to calibrate both Sim and Reco states. I do not see why after 10 years we change philosophy.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by davidlange6** [comment]
@bsunanda - perhaps I misunderstand the role of this package - will look again today.

**Comment by bsunanda** [comment]
@mmusich Could you please approve this again (I followed David's suggestions though I do not agree with his comments)?

**Comment by mmusich** [comment]
+1 
hoping this one won't change again

**Comment by davidlange6** [comment]
+1

@bsunanda -so indeed my comments were incorrect as this package is basically just a private analysis package (unless its usage is well hidden). Assuming that continues, things in the plugins area are completely ok,.

**Pull request merged**
