### PR TITLE
Include new geometry tags in Run-3 MC GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Inclusion of new DDD geometry tags in Run-3 MC GTs. Requested in 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4460.html

This is meant for `CMSSW_12_1_0_pre4` so should not merge before `CMSSW_12_1_0_pre3` is cut (expected to be today, Sept 14)

Differences in the GTs:
  * **2021 design: 121X_mcRun3_2021_design_v2**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v1/121X_mcRun3_2021_design_v2
  * **2021 realistic: 121X_mcRun3_2021_realistic_v3**
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v2/121X_mcRun3_2021_realistic_v3
  * **2021 cosmics: 121X_mcRun3_2021cosmics_realistic_deco_v3**
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v2/121X_mcRun3_2021cosmics_realistic_deco_v3
  * **2021 heavy ion: 121X_mcRun3_2021_realistic_HI_v3**
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v2/121X_mcRun3_2021_realistic_HI_v3
 * **2023 realistic: 121X_mcRun3_2023_realistic_v2**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v1/121X_mcRun3_2023_realistic_v2
 * **2024 realistic: 121X_mcRun3_2024_realistic_v2**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v1/121X_mcRun3_2024_realistic_v2

Differences are in the requested 2 geometry tags:
`XMLFILE_Geometry_120YV2_Extended2021_mc` and `TKRECO_Geometry_120YV2` 

These revisions are included:
 * PPS Run 3 sim and reco geometry was implemented.
 * PPS material names were made unique.
 * Duplicate material names were eliminated.
 * In the extended geometry description, numerical drift of rotation and translation values was reduced by rounding values <=|1e-11| to zero to match their original definitions.
 * In the Tracker Reco geometry record, calculated values of translations <=|1.e-10| were rounded to zero. Also, the third position of the so-called "navType" (_nt2) was updated from 4 to 6. This change occurred in XML during 11_2 development, but it never made it to the DB until now.

#### PR validation:

Geometry validation talk in the Simulation meeting: https://indico.cern.ch/event/1071938/#56-progress-report-on-dd4hep-m

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport but a backport to 12_0_X is expected

cc @cvuosalo @srimanob

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
As written in the description: "This is meant for CMSSW_12_1_0_pre4 so should not merge before CMSSW_12_1_0_pre3 is cut (expected to be today, Sept 14)"
@perrotta @qliphy can you confirm that this schedule is still valid?

**Comment by qliphy** [comment]
> As written in the description: "This is meant for CMSSW_12_1_0_pre4 so should not merge before CMSSW_12_1_0_pre3 is cut (expected to be today, Sept 14)"
> @perrotta @qliphy can you confirm that this schedule is still valid?

Yes, pre3 is to be built quite soon.

**Comment by francescobrivio** [comment]
Tests passed, but, as always when changing the geometry, there are several differences in the comparisons.
@cms-sw/geometry-l2 please could you confirm these differences are expected?

**Comment by tvami** [comment]
@cmsbuild , please test

* many other commits were included in the other test,  maybe this time it will be cleaner?

**Comment by cvuosalo** [comment]
At Tuesday's Simulation meeting, it was decided that the DDD geometry will require one more technical revision. That means there will be one more DB upload, and a new GT version will be needed.
I think it is OK to go ahead with this PR. The GT in this PR contains the major PPS changes. Then the next GT will contain only very minor technical geometry changes.
@tvami Do you agree with this plan? The alternative is to stop this PR, wait for the new DDD revision, and create a new GT that contains all the changes together.

**Comment by tvami** [comment]
> At Tuesday's Simulation meeting, it was decided that the DDD geometry will require one more technical revision. That means there will be one more DB upload, and a new GT version will be needed.
> I think it is OK to go ahead with this PR. The GT in this PR contains the major PPS changes. Then the next GT will contain only very minor technical geometry changes.
> @tvami Do you agree with this plan? The alternative is to stop this PR, wait for the new DDD revision, and create a new GT that contains all the changes together.

Hi @cvuosalo I agree with this plan and then we can consider that other payload as a bugfix maybe

**Comment by francescobrivio** [comment]
+alca

**Comment by tvami** [comment]
> This PR changes the DDD geometry. There is no way to preserve regression in this case. The 2021 DDD workflows that re-generate MC (312.0, 11634.0, and 12434.0) will show comparison differences, but these differences look like statistical fluctuations.

Ok so the new Jenkins results are similar, based on the above, we are ready for it to get merged

**Comment by tvami** [comment]
Hi @perrotta @qliphy sorry for urging you so often, we get a lot of requests for now GTs... Please see
https://github.com/cms-sw/cmssw/pull/35295

**Comment by qliphy** [comment]
@tvami  No problem.  We are now building 12_1_0_pre3 and will start adding new PRs after the build is finished.

**Comment by qliphy** [comment]
+1

**Pull request merged**
