### PR TITLE
Add saturated EGM regression tags to Run-3 MC GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Add saturated electron and photon regression tags as requested in https://cms-talk.web.cern.ch/t/mc-update-of-new-egm-regression-conditions/4637/8

* 123X_mcRun3_2021_design_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v9/123X_mcRun3_2021_design_v10
 * 123X_mcRun3_2021_realistic_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v9/123X_mcRun3_2021_realistic_v10
 * 123X_mcRun3_2021cosmics_realistic_deco_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v9/123X_mcRun3_2021cosmics_realistic_deco_v10
 * 123X_mcRun3_2021_realistic_HI_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v9/123X_mcRun3_2021_realistic_HI_v10
 * 123X_mcRun3_2023_realistic_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v9/123X_mcRun3_2023_realistic_v10
 * 123X_mcRun3_2024_realistic_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v9/123X_mcRun3_2024_realistic_v10
 * 123X_mcRun4_realistic_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun4_realistic_v6/123X_mcRun4_realistic_v7

Diffs are in the 8 requested tags alone, except for the Phase-2 GT where the new L1T menu was also added [as a leftover from https://github.com/cms-sw/cmssw/pull/37089] (no differences expected or observed related to this change.)

#### PR validation:

test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0
  - pull_request  = https://github.com/cms-sw/cmssw/pull/37100

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
@swagata87 I tought the saturated EGM is affecting the **high pT** electrons, but in the test comparison I see [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-01-1100+1f47de/48647/12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/Physics_NanoAODDQM_LowPtElectron.html) for example. Could you clarify if this is expected?

**Comment by francescobrivio** [comment]
@tvami could you update the PR description to include the fact that this PR complements #37089 by including the new L1T menu in `auto:phase2_realistic`? 
For completeness: no differences expected or observed related to this change.

**Comment by swagata87** [comment]
> @swagata87 I tought the saturated EGM was affecting the **high pT** electrons, but in the test comparison I see the LowPtElectron has differences ([here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-01-1100+1f47de/48647/12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/Physics_NanoAODDQM_LowPtElectron.html) for example). Could you clarify if this is expected?

Hi @francescobrivio 
thanks! good catch
apparently, `lowPtRegressionModifier` clones the `regressionModifier106XUL` 
https://github.com/cms-sw/cmssw/blob/92e9d9df6f68c4b25959755a5079f456bf1478e1/RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectrons_cfi.py#L5
and then makes necessary changes on top of it. 

So in my PR(https://github.com/cms-sw/cmssw/pull/37100) since I changed `regressionModifier106XUL`,  it gets propagated to `lowPtRegressionModifier`. 

I saw @perrotta  suggested some changes in https://github.com/cms-sw/cmssw/pull/37100, which will address this issue as well. I will implement his suggestions soon

**Comment by francescobrivio** [comment]
hold

- needs some fixes in #37100 as described in  https://github.com/cms-sw/cmssw/pull/37102#issuecomment-1055948236

**Comment by francescobrivio** [comment]
unhold

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+alca

 - tests are now clean
 - should be merged together with #37100

**Comment by francescobrivio** [comment]
urgent

 - we have other change for the MC GTs in the pipeline targeting pre6

**Comment by perrotta** [comment]
+1

**Pull request merged**
