### PR TITLE
 Update to HLT menu 3p2 with muon fix (102X) 

### PR DESCRIPTION
**Pull request by silviodonato**
Backport of #23949

### CODE REVIEW

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
also sign this backport, please!

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
