### PR TITLE
 A fix for nullptr dereference in SiStripMonitorCluster 

### PR DESCRIPTION
**Pull request by dmitrijus**
Fixes https://github.com/cms-sw/cmssw/issues/21858

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test workflow 140.52, 140.54

**Comment by fabiocos** [comment]
please test workflow 140.52, 140.54 with cms-sw/cmsdist#3642

**Comment by fabiocos** [comment]
@dmitrijus This PR seems to fix the problem, unfortunately the blank space changes makes difficult to compare with the committed code. The dependence on externals is just fake (the new Herwig was pending for the 2300 build). If you are  satisfied please sign it, I would like to add it at 1100.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
@fabiocos blank space changes and actual changes are in separate commits.

This is the actual change 'commit'.
https://github.com/cms-sw/cmssw/pull/21866/commits/6d4a6e30100380453fd528d7c76d83f54ea709ec

**Comment by fabiocos** [comment]
@dmitrijus I see, thanks. I merge it.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
