### PR TITLE
Run3-gex122X  Avoid compilation warnings for AlpgenInterface and Herwig6Interface of  GeneratorInterface

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings for AlpgenInterface and Herwig6Interface of  GeneratorInterface

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by SiewYan** [comment]
@bsunanda , could you remind me what was the displayed warning ?

**Comment by bsunanda** [comment]
Avoid using plain EDAnalyzer . This was needed for a more efficient multi-threaded approach

**Comment by SiewYan** [comment]
Thank you @bsunanda , I do not see any warning in the compilation. 

+1

**Pull request merged**
