### PR TITLE
Fix improper static_cast of HcalAmplifier

### PR DESCRIPTION
**Pull request by lwang046**
A quick fix to avoid issue in #30820

### CODE REVIEW

**Comment by abdoulline** [comment]
@smuzaffar  looks like cmsbuild didn't pick it up (on Sunday morning)...

**Comment by smuzaffar** [comment]
ping bot

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by Dr15Jones** [comment]
This does not appear to have worked. We are still getting reports of improper cast in the UBSAN build. 

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_UBSAN_X_2020-07-31-2300/pyRelValMatrixLogs/run/11834.24_TTbar_14TeV+TTbar_14TeV_TuneCP5_2021PU_GenSimFull_0TINPUT+DigiFullPU_0T_2021PU+RecoFullPU_0T_2021PU+HARVESTFullPU_0T_2021PU+NanoFull_2021PU/step2_TTbar_14TeV+TTbar_14TeV_TuneCP5_2021PU_GenSimFull_0TINPUT+DigiFullPU_0T_2021PU+RecoFullPU_0T_2021PU+HARVESTFullPU_0T_2021PU+NanoFull_2021PU.log#/324

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ad2b0f318b3a875380e0dd17ed790536/opt/cmssw/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_UBSAN_X_2020-07-31-2300/src/SimCalorimetry/HcalSimAlgos/src/HcalAmplifier.cc:50:24: runtime error: member call on address 0x2b0a70929df0 which does not point to an object of type 'HcalSimParameters'
0x2b0a70929df0: note: object is of type 'HFSimParameters'
 a3 70 d5 3f  80 31 13 69 0a 2b 00 00  00 00 00 00 00 00 18 40  b0 72 68 91 ed 7c fd 3f  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'HFSimParameters'
```

**Comment by abdoulline** [comment]
Hm..m... strange  :( 
It does work very much the same way for other "siblings" config.parameters:
https://cmssdt.cern.ch/lxr/source/SimCalorimetry/HcalSimAlgos/src/HcalSiPMHitResponse.cc#0197   - pars.sipmTau()  
https://cmssdt.cern.ch/lxr/source/SimCalorimetry/HcalSimAlgos/src/HcalElectronicsSim.cc#0147   -   pars.threshold_currentTDC()

**Comment by kpedro88** [comment]
see #31039

**Pull request merged**
