### PR TITLE
Using dasgoclient for das queries in runTheMatrix (94X)

### PR DESCRIPTION
**Pull request by fabozzi**
Since the original PR #21015 has been moved to 10_0_X milestones, I remade the one for 94X

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of #21015

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
