### PR TITLE
Enabling tracktrigger sequence for phase2 Tracker (T5)

### PR DESCRIPTION
**Pull request by boudoul**
Greetings 
This PR aims to reintroduce the track trigger sequence for the tracker T5 in the WFs taking into account the new rings belonging to this tracker T5.
At the same time , the local python files used for tracker studies (tracker only configs)  have been updated with all the latest ingredients of the geometries .
Thanks to @sviret for having done all the work

### CODE REVIEW

**Comment by boudoul** [comment]
Just putting here TT clusters and TTstubs maps obtained with 500 muonPt10 events 
cluster_rz
stub_rz

**Comment by boudoul** [comment]
Adding few watchers : @atricomi @delaere

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@boudoul once this test finishes, can you remove 2023D10 from runTheMatrix.py?

**Comment by boudoul** [comment]
ah yes good point, will do after the tests , thanks for the reminder

**Comment by boudoul** [comment]
Hi @kpedro88 , I removed D10 from  runTheMatrix.py in my last commit

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
