### PR TITLE
Optimize NanoAOD buffers at 1k events.

### PR DESCRIPTION
**Pull request by bbockelm**
ROOT will automatically add 16 bytes per branch buffer per event in the event cluster; in the case of NanoAOD files, we've seen up to 143k events per cluster (and 800 branches), resulting in an excess of 900MB of memory usage.

With this change, we explicitly optimize NanoAOD buffers after 1k events, then subsequently flush at more appropriate intervals.  To achieve this, we disable the ROOT auto-flush mechanism and explicitly optimize / flush from the NanoAOD output module itself.

This is the master equivalent of #22445.

### CODE REVIEW

**Comment by gpetruc** [comment]
+1
tested in https://github.com/cms-nanoAOD/cmssw/pull/119 (10k events). the only change is in the compressed size of the output, and it goes in the right direction.

**Comment by gpetruc** [comment]
please test

**Comment by bbockelm** [comment]
@gpetruc - from my prior tests, I only recall compression changes in the noise.  Did you see anything significant?

This should attempt to make optimal compression buffers earlier on in the file (in the extreme case we hit, optimization was done only after 143k events) -- but I would assume this really only changes the first 10MB of data or so.

**Comment by arizzi** [comment]
Sample | kb/event | ref kb/event | diff
-- | -- | -- | --
TTbar MC 94X | 1.452 | 1.510 | -0.058 ( -3.9% )
TTbar MC 80X | 1.501 | 1.557 | -0.056 ( -3.6% )
Data 94X | 0.588 | 0.611 | -0.022 ( -3.6% )
Data 80X | 0.556 | 0.577 | -0.021 ( -3.7% )
Data 80X, Mu Run2016E | 0.556 | 0.507 | 0.049 ( +9.7% )

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
