### PR TITLE
Hcal validation new histograms

### PR DESCRIPTION
**Pull request by kencall**
It makes additions to DQMOffline/Hcal/HcalRecHitsAnalyzer

The following histograms are added for HB and HE:

Emean_vs_ieta (M0)
Emean_vs_ieta (M3)

RecHit Energy (M0)
RecHit Energy (M3)

RecHit Energy (M2 vs. M0)
RecHit Energy (M3 vs. M0)
RecHit Energy (M3 vs. M2)

Log10(M2 Chi2) spectra and profile vs energy.

### CODE REVIEW

**Comment by slava77** [comment]
it's a nice addition.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@dmitrijus  
please, approve this addition

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
