### PR TITLE
HLT DQM for 9.3.x - part 2

### PR DESCRIPTION
**Pull request by fwyzard**
Follow up to #19685.

Merge the following HLT DQM pull requests (in this order):
  - #19178 from physicist87/hltjetmet-promptqdm-updateV2
  - #18994 from anigamova/from-CMSSW_9_2_0
  - #19293 from rappoccio/EXOB2G_HLTMON
  - #19689 from physicist87/Pure-METTrigger-93xV4
  - #19078 from sroychow/higgsHLT92X
  - #19577 from heller3/LepHTMonitoring

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
@davidlange6 right now this is identical to #19685; I'm going to push here more merged PRs.

**Comment by fwyzard** [comment]
I've merged this back into 9.3.x as of CMSSW_9_3_0_pre2, and added #19078 (python only).

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please abort

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6, @smuzaffar, can you merge this, please ?

**Comment by davidlange6** [comment]
hi @fwyzard - in the end #18994 needs updates (now more clear thanks to your updates) - lets see if I can make a PR with the other PRs here.

**Comment by fwyzard** [comment]
All PRs likely need updates, since they sit unmerged for days or weeks.

Can you merge this as-is please, and (ask to) make follow up PRs as needed ?
Otherwise I doubt anything will ever get merged.

Ciao,
.Andrea

**Comment by davidlange6** [comment]
its not an issue of code rot and getting changes made after PRs go in is iffy at best in cms. 

anyway, the best I seem to be able to do is

https://github.com/cms-sw/cmssw/compare/master...davidlange6:HLTDQMv2minusBPH?expand=1

which makes a mess for the BPH merge later. but not that much damage. that can get fixed via a rebase of #18994 after review comments. Does that work?

**Comment by fwyzard** [comment]
Hi David,
it's not code rot, it's simply many overlapping changes coming all at the
same time. The alternative would be to maintain a branch to integrate all
of them, and submit a large PR once a month, à la L1.

Anyway, I'm holiday this week... I do expect I'll need to spend some time
rebasing and syncing the various PRs next week, but I was hoping this one
could be merged in the meantime, along with any other that has no conflicts
and passes the review.

Ciao,
.Andrea

**Pull request merged**
