### PR TITLE
Add cuts to SiStripMonitorTrack

### PR DESCRIPTION
**Pull request by schneiml**
This commit introduces 4 cuts to select only good quality tracks for the track-based histograms of SiStripMonitorTrack:
- pT > 0.8
- P > 2
- numberOfValidTrackerHits > 6
- normalizedChi2 < 10

These parameters were suggested by @dimattia  and @jlagram, via @fioriNTU .

The cuts drop about 60% of all hits. They affect the track-based per-cm histograms in SiStripMonitorTrack. The off-track cluster based plots are unaffected.

### CODE REVIEW

**Comment by fioriNTU** [comment]
@schneiml the cut on Chi2 is reverted in your message, the right cut is Chi2/ndof < 10, probably is this that drops the number of hits by 99%, it is not expected to have this poor efficiency by those cuts.
And the NumberOfHits it is not clear if is Tracker or Strip Hits, in my opinion should be StripHits, but let's ask again to Sandro.

**Comment by schneiml** [comment]
@fioriNTU I suspected that. It is this way round in the e-mail, but given that it goes to ∞ for ndof -> 0...
Also, 99% is a similar amount to what the SiStrip residuals did, so I did not see it as obviously wrong...

**Comment by schneiml** [comment]
@fioriNTU  Now the chi2 cut should be ok. We drop only around 60%.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
if final please submit to 81x as well.
thanks,
F.

**Comment by schneiml** [comment]
After further commuication with Alessandro and Jean-Laurent, the cuts are now only applied to the per-cm histograms. Also, the numberOfValidTrackerHits cut was confirmed.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
