### PR TITLE
Fix HCAL TP validation w/ premixing [92X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #20266

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
abort

**Comment by kpedro88** [comment]
please test workflow 250207.17

**Comment by kpedro88** [comment]
removed commit "consistent packing of TPs w/ premixing" to reduce changes in nominally closed 92X branch

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@civanch @mdhildreth please sign

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
