### PR TITLE
Phase2-hgx335D Add a private scenario to test cassette shift of HGCal V17 geometry version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a private scenario to test the cassette shift of HGCal V17 geometry version

#### PR validation:

Use one of the test scripts in Geometry/HGCalCommonData/test/python to test this

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve

**Comment by bsunanda** [comment]
@srimanob Please approve

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
