### PR TITLE
add PFCandidate Analyzer, add HCAL scale monitoring

### PR DESCRIPTION
**Pull request by webermat**
create PFCandidateAnalyzer, move existing PFCandidate Monitoring histograms from METAnalyzer into newly created module. Add HCAL scale monitoring based on isolated charged hadron candidates comparing HCAL Cluster Energies and Track momentum. Reduce number of bins in phi for PFCandidate eta-phi maps. Clean up METAnalyzer and JetAnalyzer removing OOT pileup histogram for 50 ns bunch spacing (commented out already previously). 80X version of PR  #13587

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by webermat** [comment]
same fix as need for the 81X, parameters were not read in correctly

**Comment by webermat** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by webermat** [comment]
results look fine now

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
might it not be good to merge this PR to have it in offline DQM at some point

**Comment by webermat** [comment]
i know it is quite late to merge this PR now (originally forseen to be done in mid march!). Still it might good to have it, since at least it allows us easily to compare Reco versions of later releases to be compared to 80X versions of the same runs.

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
