### PR TITLE
Various NanoAOD fixes (PDF, PS weights, jets) master version

### PR DESCRIPTION
**Pull request by arizzi**
Changes in this PR:

- Changes to PS weight implementation
- Expand on CaloMET's doc
- Add NNPDF30_nlo_nf_5_pdfas 292200 preferred PDF for some Madgraph aMC… …
- Also add 4f-scheme NNPDF30 nlo PDF set
- Adding some missing info for jets
- Update DQM and fix rawFactor plot also for standard jets

same as #23837 except for
- Electrons and Photons: use scale/smearing only when available (94X, 80X)
- taus: don't use 2015 training on 2018 data
@gpetruc

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.7722,136.7952,136.8521,1325.6,1325.7,1325.8,1325.9,1329.1

**Comment by fabiocos** [comment]
@arizzi @gpetruc I assume this PR is ok for you, as you proposed it. Could you please sign it in case?

**Comment by arizzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
