### PR TITLE
Merge TrackerLayerIdAccessor to TrackerTopology

### PR DESCRIPTION
**Pull request by makortel**
Migrate TrackerLayerIdAccessor to TrackerTopology by moving its functionality to TrackerTopology (following the suggestion of @venturia).

Tested in CMSSW_7_5_0_pre5, no changes expected in results.

@rovere @VinInn @venturia @boudoul

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
(matrix  tests will likely fail due to das problems)

**Comment by slava77** [comment]
@smuzaffar @degano please check what happened to the results:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9449/3997/summary.html
page is 404

**Comment by smuzaffar** [comment]
pelase test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
I am afraid this is deleted by one of our cleanup jobs.
I am re-triggering it again.

**Comment by smuzaffar** [comment]
Here is what had happened.
I have a rsync job going on from vocms12 (old cmssdt) to cmssdt01 to 
copy old PR tests and other stuff to new cmssdt. The way rsync works is 
that it creates all top level directories first with current time as 
their timestamp. We also have a jenkin job which goes to cmssdt and 
delete old jobs based on their timestamp. While rsync was trying to copy 
files for pull-request-integration directory, the cleanup job started 
and it kept the latest 100 PR tests and deleted others.

I have disabled the cleanup job for now and will enable it once the 
rsync is done. For now I have re-triggered the test for this PR. Let me 
know if you find anyother PR with missing test results.

**Comment by makortel** [comment]
The error
```
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-cache/cms.week1/w/tmp/BUILDROOT/6dcf4226cb283cb975dbed0fd2c06f05/opt/cmssw/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-06-04-2300/src/IOPool/Input/src/RootEmbeddedFileSequence.cc:352:
bool edm::RootEmbeddedFileSequence::readOneEvent(edm::EventPrincipal&, size_t&, CLHEP::HepRandomEngine*, const edm::EventID*): Assertion `sequential_ || engine != nullptr' failed.
```
looks like being in the IB itself?

**Comment by slava77** [comment]
@smuzaffar @degano could you please update the PR integration scripts so that the comparisons with the baseline are still triggered if there is at least one successful matrix test.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9449	 d3f837b
- changes in the code are OK
- since jenkins comparisons got blocked by one failing test, I tested this locally in CMSSW_7_5_0_pre5 /test area sign562/: comparisons with the baseline show no differences as expected.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@ianna 
Hi Yana,
this is waiting for geometry signature.
Please check.
Thank you.

**Pull request merged**
