### PR TITLE
Added missing include of memory to Herwig6Instance

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
This fixes a 'check headers' error.

#### PR validation:
The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@alberto-sanchez @efeyazgan @perrozzi @qliphy please review. The change was trivial.

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

the problems in the DQM test were due to the failing IB

**Pull request merged**
