### PR TITLE
Phase2-gex134 Modify C17 to see the new numbering of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify C17 to see the new numbering of HCAL

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

othing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Do we expect to see any changes in Phase-2 D88? Not sure when SubDetId is corrected, and new XML is used, what should be expected?

**Comment by bsunanda** [comment]
This make changes to some rare process. I am not sure if the difference can be seen in tests with small samples

**Comment by perrotta** [comment]
> +Upgrade
> 
> This fix follows the validation report of HCAL [*] and it should be the target for the next Phase-2 DD4hep validation. However, it seems unclear to me if the change is expected also for DDD as file `Geometry/CMSCommonData/python/cmsExtendedGeometry2026D86XML_cfi.py` also changes. The description of validation campaign should be clear.
> 
> [*] https://cms-pdmv.cern.ch/valdb/?srch=dd4hep&selected=CMSSW_12_4_0_pre3_D88_DD4HEP&Reconstruction=true&RFull=true

@srimanob will you take care of notifying it to @cms-sw/pdmv-l2 , so that it can be correctly taken into account in that validation campaign?

**Comment by srimanob** [comment]
Hi @perrotta 
Yes, I will in contact with @cms-sw/pdmv-l2 on the fix. I've put this also in the news of Sim Meeting (May 20, https://indico.cern.ch/event/1162548/)

**Comment by srimanob** [comment]
hold

**Comment by srimanob** [comment]
Hi @abdoulline @bsunanda 

I expect that as this PR fixes the HCAL ID, it should fix the issue reported in https://github.com/cms-sw/cmssw/issues/37087. However, it seems that it does not fix it. Would you mind to test before?

You can try by checkout CMSSW_12_5_0_pre1 and this PR. Running 39434.911 will show the issue in both DIGI and RECO steps.

Digi:
```
%MSG-e HcalDigitizer:  MixingModule:mix 22-May-2022 19:26:09 CEST  Run: 1 Event: 6
bad hcal id found in digitizer. Skipping 1158682625 (HE -6,1,1)
%MSG
```

Reco:
```
%MSG-w HcalDetId:  HcalDigisValidation:AllHcalDigisValidation  22-May-2022 19:29:52 CEST Run: 1 Event: 1
HcalDetID(SimHit) presents conflicting information. Depth: 1, iphi: 1, ieta: 1. Max depth from geometry is: 0. TestNumber = 1
%MSG
```

**Comment by bsunanda** [comment]
Please check how the premix sample was created. Has the sample been recreated after making the fix?
________________________________

**Comment by srimanob** [comment]
This is NoPU sample, created by CMSSW_12_5_0_pre1 and this PR.

**Comment by srimanob** [comment]
This is how I make the test:

```
scram p -n CMSSW_12_5_0_pre1_HCAL CMSSW CMSSW_12_5_0_pre1
cd CMSSW_12_5_0_pre1_HCAL/src/
git cms-rebase-topic bsunanda:Phase2-gex134
scram b -j 8
runTheMatrix.py --what upgrade -l 39434.911 -t 8 --wm init
```
then run configs inside.

**Comment by abdoulline** [comment]
If I understand it right,   wf 39434.911 = TTbar 2026D88 noPU with DDHEP4 xml
https://cmssdt.cern.ch/lxr/source/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#0105

I have a naive question: 
git cms-rebase-topic bsunanda:Phase2-gex134 
  is it an equivalent of: 
git cms-merge-topic 37951  ?

**Comment by srimanob** [comment]
Any investigation, update on this? Thanks.

**Comment by srimanob** [comment]
@cmsbuild please test

Just refresh the test in case we will merge.

**Comment by srimanob** [comment]
Please test workflow 39434.911

**Comment by srimanob** [comment]
Hi @bsunanda @abdoulline 

You can check from the [last PR test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46e449/25595/runTheMatrix-results/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/) on the issue I mention:
- DIGI: `bad hcal id found in digitizer. Skipping 1158677505 (HE -1,1,1)`
- RECO: `HcalDetID(SimHit) presents conflicting information. Depth: 1, iphi: 1, ieta: -1. Max depth from geometry is: 0. TestNumber = 1`

[DIGI step](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46e449/25595/runTheMatrix-results/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step2_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log), [RECO step](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46e449/25595/runTheMatrix-results/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)]

**Comment by bsunanda** [comment]
@srimanob Please uphold this PR. It makes changes in the right direction

**Comment by srimanob** [comment]
unhold

**Comment by srimanob** [comment]
@cmsbuild please test workflow 39434.911

**Comment by srimanob** [comment]
Hi @bsunanda 

It will be great if you could help to understand more the situation.
- Is this PR a bug-fix or to improve?
- As mention [here](https://github.com/cms-sw/cmssw/pull/37951#issuecomment-1159350326), this PR does not fix the issue of bad hcal id in DIGI and RECO step. What is exactly the change that this PR makes.
- Should it go to C18, C19, C20 also? Also backport for 12_5 phase-2 production?

Thanks.

**Comment by bsunanda** [comment]
Hi, this is a bug fix and should be included in all Phase 2 scenarios of CMS. Once this is integrated I can update all calorimeter descriptions with this

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
Failure in INPUT does not relate to this PR.

Would it be better if @bsunanda confirm the issue of bad HCAL ID which still show up in PR test (as [mentioned](https://github.com/cms-sw/cmssw/pull/37951#issuecomment-1159350326) before),
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46e449/27312/runTheMatrix-results/39434.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
As this PR merged after 12_6_0_pre2, I would like to remind @cms-sw/pdmv-l2  to make a clear validation statement on the change of D88.

REF, see comment
https://github.com/cms-sw/cmssw/pull/37951#issuecomment-1129181526

**Comment by kskovpen** [comment]
Thanks @srimanob , we will take a note.

**Pull request merged**
