### PR TITLE
[TsosGaussianStateConversions] proposal fix for Gsf Tracking segmentation fault when no states are passing selection criteria 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Proposal resolution to issue at https://github.com/cms-sw/cmssw/issues/39987. Submitted mostly to check regressions.

#### PR validation:

It was not yet possible to fully reproduce the issue offline, this solves a "simulated" crash according to the recipe detailed at https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1306014157

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported, if it is determined that there are no regressions.

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild  please test

**Comment by slava77** [comment]
type tracking

**Comment by mmusich** [comment]
in principle we might want to backport this and deploy at Tier0 for the last leg of data-taking.

@cms-sw/reconstruction-l2 please also have a look to the related discussion at https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1308440135

**Comment by clacaputo** [comment]
+reconstruction

- attempt for fixing #39987
- the PR doesn't introduce any reco changes
- it adds an extra layer of protection that could fix #39987. See https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1308440135

**Comment by perrotta** [comment]
+1
- Adding an extra protection

**Pull request merged**
