### PR TITLE
Remove Event Interpretation (EI) from relval steps

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

As suggested on https://github.com/cms-sw/cmssw/issues/32643 and after no response from TOP developers for months, we are safely removing EI from relVal steps

Announced on PPD core meeting 15/12/2021
Slide 13 of https://indico.cern.ch/event/1099504/contributions/4626290/attachments/2364681/4039466/21-12-15_News_PPDCoord.pdf
#### PR validation:

 runTheMatrix.py -l limite -i all --ibeos

### CODE REVIEW

**Comment by wajidalikhan** [comment]
Hi @jfernan2, I am not sure if we tagged the relevant people from TOP. I represent TMG (Top Modeling and Generator Group).

**Comment by jfernan2** [comment]
FYI @ kuyoun

**Comment by jfernan2** [comment]
@wajidalikhan the list of TOP Validators we have is:
https://e-groups.cern.ch/e-groups/Egroup.do?egroupName=cms-dqm-validation-developers-top&tab=3

and only one has a github id declared who does not respond

**Comment by jfernan2** [comment]
If there are more people related to TOP PAG working in validation please add them on:
https://twiki.cern.ch/twiki/bin/view/CMS/DQMContacts#TOP

**Comment by jfernan2** [comment]
Adding PF crew since the EI is under their package:
FYI @kdlong @juska @hatakeyamak @chosila @jpata

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hmm, I wonder whether this PR is taking care of these occurences, eg: pfMetEI:
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_3_X_2021-12-12-2300&_filestring=&_string=pfMetEI&_casesensitive=1

**Comment by jfernan2** [comment]
> Hmm, I wonder whether this PR is taking care of these occurences, eg: pfMetEI: https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_3_X_2021-12-12-2300&_filestring=&_string=pfMetEI&_casesensitive=1

In principle not, but I can do it: should I replace with the plain collections?
I.e. pfMetEI   -> pfMet   and   pfJetsEI  ->  ak4PFJets  or   ak4PFJetsCHS   ?
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@wajidalikhan @kuyoun now the TOP DQM modules get 0 entries, at least those which were fed by EI. Do you have any suggestion? Thanks

**Comment by jfernan2** [comment]
please test
I hope to not have screwed up anything....

**Comment by jfernan2** [comment]
It seems I have screwed up the history sorry... I will try to fix...

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jfernan2** [comment]
Now there are a lot of changes in wf 11634.911 but github does not declare any change in input conditions, is it due to the "There are other open Pull requests which might conflict with changes you have proposed:" ?

**Comment by jfernan2** [comment]
OK, I see it is appearing in other PRs too

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR is to remove obsolete EI step from relvals workflow, discussed in https://github.com/cms-sw/cmssw/issues/32643 
It is considered as a technical PR, but need to update also collections used for DQM. PR test runs fine.

**Comment by kskovpen** [comment]
Indeed, thanks @jfernan2 for a nice update.

+pdmv

**Comment by kskovpen** [comment]
+1

**Comment by tvami** [comment]
+alca

**Comment by makortel** [comment]
+core

**Comment by jfernan2** [comment]
wf 4.76 failed to open input file

**Comment by hatakeyamak** [comment]
> Adding PF crew since the EI is under their package: FYI @kdlong @juska @hatakeyamak @chosila @jpata

I don't see a problem with this removal.

**Comment by perrotta** [comment]
+operations
- Output changes consist in the removal of the EI related quantities, some reshuffling of the HLT paths, and kind of expected changes in top, ET, and related monitorings

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
