### PR TITLE
Adjust clang-format after CMSSW_11_0_X_2019-06-13-1100

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Address comments during the review of clang-format review up to CMSSW_11_0_X_2019-06-13-1100

#### PR validation:

code compiles

### CODE REVIEW

**Comment by fabiocos** [comment]
@perrotta concerning your comments to #27113 they are not addressed here because I think they concerns more the definition of the formatting itself, than some possible simple adjustment of the code to cope with its current definition

**Comment by kpedro88** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch @cvuosalo the PR is purely technical, I move forward with its integration, please have a look and comment for further updates in case

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
