### PR TITLE
Revert "Fixes to L3 Muon OI SeedGenerator (TSGForOI) for high efficiency "

### PR DESCRIPTION
**Pull request by bmahakud**
Reverts cms-sw/cmssw#23988

Because this code is added as completely new plugin  in PR : #24267 . This is being done to ease the validation process as suggested by experts. (@Martin-Grunewald )

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
So this PR needs to be integrated first, followed by the new one.

**Comment by fabiocos** [comment]
@slava77 @perrotta in view of integrating into 10_3_0_pre2 could you please understand whether this can be merged soon?

**Comment by perrotta** [comment]
+1
- It fully reverts #23988, as it is required for merging #24267 later on
- With this revert, TSGForOI will return the same as in 10_3_0_pre1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
