### PR TITLE
HCAL DQM Online Histogram for Bad Quality Events

### PR DESCRIPTION
**Pull request by denizsun**
#### PR description:
  - We have added a histogram to Online HCAL DQM by implementing the required changes in the CMSSW_14_1_0_pre3 [1] release.
 - We set up the GUI on the dqmfu-c2b02-46-01 machine by following the instructions provided in [0].
   [0]: https://github.com/cms-DQM/dqmgui_prod_deployment/wiki/Deployment-at-Point-5
   [1]: https://github.com/cms-sw/cmssw/blob/master/DQM/HcalTasks/plugins/RawTask.cc

 - A new histogram will be appeared in 00_Shift/Errors
 - There is a gitlab issue https://gitlab.cern.ch/cmshcal/docs/-/issues/233.
#### PR validation:

- All the PR validation checks and the runTheMatrix test are done. 

- This PR is not a back port.
- All points of checklist is done.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
Hi @denizsun , we are testing the PR online at our playback machines. Could you please have a look at the playback [GUI plots](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Shift;size=M;root=00%20Shift/Errors;focus=Hcal/RawTask/BadQ_FEDvsLSmod60/BadQ_FEDvsLSmod60;zoom=yes;) and opine whether the changes have been well observed? Thanks!

**Comment by denizsun** [comment]
Hi @tjavaid , I had a look at the GUI plots and looks ok.Thanks!

**Comment by nothingface0** [comment]
@denizsun Could you provide us with a recent run number (and the lumisection range) which would lead to this alarm going off, so that we can also check the alarm functionality?

**Comment by denizsun** [comment]
> @denizsun Could you provide us with a recent run number (and the lumisection range) which would lead to this alarm going off, so that we can also check the alarm functionality?

@nothingface0 There is a data run #382262. In this run, the problem occurs at the LS changing from 221-224. 
There is a run#384128, no problem at all.

**Comment by denizsun** [comment]
> @denizsun Is there any run more recent than 382262 for triggering the alarm? This one probably won't be available.

@nothingface0 
The following recent runs have BadQuality Events
Run 384070, LS 100-130
Run 383756, LS 1390-1402
Run 383468, LS 1520-1550

and these shouldn't have trigger BadQulaity events:
Run 383756, LS 150-260
Run 383468, LS 430, 1576, 1839

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

- P5 tests OK. Thanks @nothingface0 
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )
- @denizsun , could you make a backport PR for `14_0_X` so that it can be deployed in production ?

**Comment by mandrenguyen** [comment]
+1

**Comment by denizsun** [comment]
> +1
> 
> * P5 tests OK. Thanks @nothingface0
> * spurious differences seen from unstable WF `12834.7` (open issue [spurious differences in outputs of Run-3 wfs `*.7` #39803](https://github.com/cms-sw/cmssw/issues/39803) )
> * @denizsun , could you make a backport PR for `14_0_X` so that it can be deployed in production ?

**Comment by nothingface0** [comment]
@denizsun we sent you some instructions on how to do it via email :)

**Pull request merged**
