### PR TITLE
Finalize migration to esConsumes of `Alignment/TrackerAlignment` and `Alignment/SurveyAnalysis`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to finalize the migration to `esConsumes` for the packages `Alignment/TrackerAlignment` and `Alignment/SurveyAnalysis`. I profit of it to modernize some of the legacy `edm::EDAnalyzer`s to become thread-efficient.
This is part of issue #31061.
Part of the changes have been performed by @bbilin.

#### PR validation:

The code compiles.
The changes in `Alignment/TrackerAlignment` have been tested explicitly by running the code in `Alignment/SurveyAnalysis/test/run-converter_cfg.py`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and not backport will be needed.

### CODE REVIEW

**Comment by mmusich** [comment]
This requires issue https://github.com/cms-sw/cmssw/issues/34223 to be solved in orther to pass tests.

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
> I found errors in the following unit tests:
> ---> test test_PixelBaryCentreTool had ERRORS

As already reported at https://github.com/cms-sw/cmssw/pull/34248#issuecomment-868544091 this requires issue #34223 to be solved in order to pass tests.

**Comment by makortel** [comment]
Do the changed files get tested in other tests than `test_PixelBaryCentreTool`? Fixing #34223 will take some time (unlikely this week, hopefully next), and I'm wondering if this PR absolutely needs #34223 fixed before merging.

**Comment by mmusich** [comment]
> Do the changed files get tested in other tests than test_PixelBaryCentreTool? 

They don't, but we explicitly run `Alignment/SurveyAnalysis/test/run-converter_cfg.py` which tests the changes in `TrackerAlignment.cc`, while there are no tests implemented for the other package.
I guess @cms-sw/alca-l2 can just proceed with the review.

**Comment by qliphy** [comment]
kindly ping @cms-sw/alca-l2

**Comment by yuanchao** [comment]
+1

* esConsume migration for Alignment/TrackerAlignment & SurveyAnalysis (no related warnings found)
* matrix tests all passed; some unit tests failed

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
