### PR TITLE
Update of the CSC migration to DD4HEP 

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

Update the CSC migration to DD4hep after @bsunanda PRs #29842 #29943 and @ianna PR #29954.

**PR validation:**

1)  validation made by Geometry/CSCGeometryBuilder/test/python/validateCSCGeometryDD4hep_cfg.py

2) validation by runTheMatrix.py -l 25202.1 :

25202.1_TTbar_13+TTbar_13+DIGIUP15APVSimu_PU25+RECOUP15_PU25+HARVESTUP15_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Jun  5 12:30:33 2020-date Fri Jun  5 12:08:56 2020; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
`DetectorDescription/DDCMS/data/cms-geometry-2021.xml` is being deleted in #30093, so it is the wrong file to modify.

**Comment by slomeo** [comment]
@cvuosalo I'll wait till #30093 will be merged then I'll rebase

**Comment by perrotta** [comment]
please test

**Comment by slomeo** [comment]
@cvuosalo done and the comparison is good

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
