### PR TITLE
skims for 74

### PR DESCRIPTION
**Pull request by franzoni**
- back port of skims DEFINITIONS from 75
- superceeds  #9867 , which can be closed
- rationalization of the skim matrix, intended to pass to T0 the PD => "skims to run" correspondence,
  in light of 2015 PD's , see https://hypernews.cern.ch/HyperNews/CMS/get/physics-announcements/3385.html
- collection of skims requirements by DPG/POG/PAGs : https://docs.google.com/spreadsheets/d/1OicL4b3jFUXalsk92GM9qLbNNAVklAGb7bf1T5BwZrY/edit#gid=0
- more local test running, will get back in a few hours
- to follow suit: forward porting to 7_5 and 7_6
                      relval tests, once this PR will have passed
                      integration in the ralval matrix, together with miniAOD - unscheduled

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
note: the relval matrix does not yet invoke any skims
         => the tests from the bot don't address the substance

**Comment by davidlange6** [comment]
@franzoni - is this PR now ready to go in?

**Comment by franzoni** [comment]
Needs one small modification. By end of morning.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
status: tests run with skis one-by-one and skims brought in via the autoSkim matrix; with RECO, Alca and SKIM in the same process. => good !

Facing issue with retainign RECO output
investigating

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1 
for PdmV/DDT and operations

**Comment by franzoni** [comment]
++ SUMMARY
What this PR does is described in the frists post, see there.
Validation and rate measuremetns on the skim producers were carried out by Alexis @alkaloge based on 7_5_0_preX, not being readdressed here.

++ TEST
Conflicts resolved and tests passed, 
all outputs look technically sensible on a handful of events:
. running RECO, and SKIMS in the same process
.              RECO, ALCA producers and SKIMS in the same process, see [1]

Tests failed:
. when activanting unscheduled, and brining in the PAT step and MINIAOD outout [2], a different kind of conflict emerges with ALCA producers, see  [3]


[1]
 cmsDriver.py step2  --process reHLT --conditions auto:run1_hlt_Fake --data  --output '[{"e":"RAW","t":"RAW","o":["drop FEDRawDataCollection_rawDataCollector__LHC"]}]' -s L1REPACK,HLT:@fake -n 5 --filein /store/data/Run2012D/SingleElectron/RAW/v1/000/208/307/FE62613A-D03A-E211-A089-001D09F25479.root --lumiToProcess step1_lumiRanges.log --fileout file:step2.root --no_exec

cmsDriver.py step3 --conditions auto:run1_data_Fake -s RAW2DIGI,L1Reco,RECO,EI,ALCA:SiStripCalZeroBias+SiStripCalMinBias+EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron+TkAlMuonIsolated+TkAlMinBias+HcalCalIsoTrk+MuAlOverlaps+TkAlMuonIsolated+TkAlMinBias+HcalCalIsoTrk+MuAlOverlaps,SKIM:@JetHT,DQM --process reRECO --data --eventcontent RECO,DQM --hltProcess reHLT --scenario pp --datatier RECO,DQMIO -n 5 --filein file:step2.root --fileout file:step3.root --python RECO-ALCA-SKIM-scheduled.py --no_exec


[2]
cmsDriver.py step2 ... 
(see [1])

cmsDriver.py step3 --conditions auto:run1_data_Fake -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron+TkAlMuonIsolated+TkAlMinBias+HcalCalIsoTrk+MuAlOverlaps+TkAlMuonIsolated+TkAlMinBias+HcalCalIsoTrk+MuAlOverlaps,SKIM:@JetHT,DQM --runUnscheduled --process reRECO --data --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp --datatier RECO,MINIAOD,DQMIO -n 5 --filein file:step2.root --fileout file:step3.root --python RECO-ALCA-SKIM-miniAOD-UNscheduled.py --no_exec

[3]
----- Begin Fatal Exception 26-Jun-2015 15:48:23 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 208307 lumi: 591 event: 811767683
   [1] Running path 'ALCARECOStreamEcalCalWElectronOutPath'
   [2] Calling event method for module PoolOutputModule/'ALCARECOStreamEcalCalWElectron'
   [3] Calling produce method for unscheduled module PFCandIsolatorFromDeposits/'elPFIsoValueCharged03PFId'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<reco::IsoDeposit>
Looking for module label: elPFIsoDepositCharged

**Comment by franzoni** [comment]
> PS:
> . when activanting unscheduled, and brining in the PAT step and MINIAOD outout [2], a different kind 
> of conflict emerges with ALCA producers, see [3]

is the same as here:

https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1010/1/1/1/1/1/1/1/1/1/1/1/1/1/2/1/1/1/1/1.html

and being addressed :-)

**Comment by franzoni** [comment]
PS2:

in CMSSW_7_4_6_patch1, this issue:

> PS:
> . when activanting unscheduled, and brining in the PAT step and MINIAOD outout [2], a different kind
> of conflict emerges with ALCA producers, see [3]

is resolved (running a dozen local workflows on a few events each) 

:-)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
