### PR TITLE
Change track muon dataformats scouting (11.1.x)

### PR DESCRIPTION
**Pull request by jsalfeld**
…roducers

#### PR description:

This is a back port of:
https://github.com/cms-sw/cmssw/pull/31962

It includes changes to Scouting Producers and data formats. Due to the back port from 11.2.X, there are 4 small additional changes for which I checked that it compiles and the scouting event content is filled. 

The differences are:

1.) removal of <use name="FWCore/Utilities"/> in DataFormats/Scouting/BuildFile.xml
2.) replacing outRho.reset(new double(*rho)); with outRho = std::make_unique<double>(*rho); and alike for MET in HLTrigger/JetMET/plugins/HLTScoutingPFProducer.cc

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a back port of:
https://github.com/cms-sw/cmssw/pull/31962

backport is needed for timely release of Run-3 scouting investigations

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
backport of #31962

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/hlt-l2  Do you have any comments?

**Comment by fwyzard** [comment]
See the comments in #31962 .

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
@cms-sw/core-l2 do you have any comments?

**Comment by makortel** [comment]
+1

(apologies for the delay)

**Comment by silviodonato** [comment]
+1

**Comment by jsalfeld** [comment]
@silviodonato we would need this in a new release to use it in confDB. Can we request one?

**Comment by silviodonato** [comment]
I think I will build it tomorrow after having merged #32425

**Pull request merged**
