### PR TITLE
remove MkFit clang16 vectorization warnings 

### LINKED ISSUE #41624: [RECONSTRUCTION] [CLANG] `Loop not vectorized` warnings
Hello,

I am opening a separate issue for what we started discussing in https://github.com/cms-sw/cmssw/pull/41616.

CLANG IBs started showing some warnings reporting `loop not vectorized` as of the update to llvm16.
In concrete,  for the reconstruction module `RecoTracker/MkFitCore`:
```
>> Compiling  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/radix_sort.cc
/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/llvm/16.0.3-5d1904f3c7b5c53b7522ba0858baec44/bin/clang++ -c -DGNU_GCC -D_GNU_SOURCE -DTBB_USE_GLIBCXX_VERSION=110201 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DCMSSW_GIT_HASH='CMSSW_13_2_CLANG_X_2023-05-09-2300' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_13_2_CLANG_X_2023-05-09-2300' -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/pcre/8.43-5dcc901acc02f624b22dd9840b2357e8/include -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/bz2lib/1.0.6-2c1f18484cb66c30aba7929f2be5e7d4/include -isystem/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/lcg/root/6.26.11-9720c7273eac1c892ddadde973cf1965/include -isystem/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/tbb/v2021.8.0-4e779f195a25a0aba119b27519937ba0/include -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/xz/5.2.5-83d0a00b575efd1701e07bedf7977343/include -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/zlib/1.2.11-3dfb2715f3608466b74431b80eb9d788/include -I/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/json/3.10.2-a6d86565b09ec3d0e02bf7b52c31bbfc/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Werror=array-bounds -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-c99-extensions -Wno-c++11-narrowing -D__STRICT_ANSI__ -Wno-unused-private-field -Wno-unknown-pragmas -Wno-unused-command-line-argument -Wno-unknown-warning-option -ftemplate-depth=512 -Wno-error=potentially-evaluated-expression -Wno-tautological-type-limit-compare -fsized-deallocation --gcc-toolchain=/pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161 -Ofast -fno-reciprocal-math -mrecip=none -DBOOST_DISABLE_ASSERTS -fopenmp-simd  -fPIC    -MMD -MF tmp/el8_amd64_gcc11/src/RecoTracker/MkFitCore/src/RecoTrackerMkFitCore/radix_sort.cc.d /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/radix_sort.cc -o tmp/el8_amd64_gcc11/src/RecoTracker/MkFitCore/src/RecoTrackerMkFitCore/radix_sort.cc.o
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.cc:290:8: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   void helixAtRFromIterativeCCSFullJac(const MPlexLV& inPar,
       ^
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:248:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   void MkFinder::selectHitIndices(const LayerOfHits &layer_of_hits, const int N_proc) {
                 ^
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:248:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:693:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   void MkFinder::addBestHit(const LayerOfHits &layer_of_hits, const int N_proc, const FindingFoos &fnd_foos) {
                 ^
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:905:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   void MkFinder::findCandidates(const LayerOfHits &layer_of_hits,
                 ^
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:1151:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
   void MkFinder::findCandidatesCloneEngine(const LayerOfHits &layer_of_hits,
                 ^
  /pool/condor/dir_43945/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/189e8911dd83c5e66aafe1fe240371ea/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_2_CLANG_X_2023-05-09-2300/src/RecoTracker/MkFitCore/src/MkFinder.cc:1151:18: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
 1 warning generated.
6 warnings generated.
```

I have seen in older PRs that sometimes this has been fixed by using a pragma statement, others inlining the function (which I believe it won't work here, but correct me if I am wrong) and in other cases the original authors took care of rearranging the code. Any hints on what can we do in those cases?

Many thanks! :)
Andrea.

FYI, @smuzaffar

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

Removes the "loop not vectorized" warnings in https://github.com/cms-sw/cmssw/issues/41624. Four of the loops are not vectorized by any of our compilers, so I commented out the simd pragma for those. For the others that are vectorized by icc and gcc, I added an ifdef to disable the simd pragma for clang. I would have preferred to suppress the warning messages with a compiler pragma, but that doesn't seem to be possible for the case where vectorization is supposed to be forced.  Resolves #41624.

#### PR validation:

Compiles without warnings with clang16 and gcc.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by VinInn** [comment]
some of the loop may vectorize if vdt was used for math

**Comment by dan131riley** [comment]
> some of the loop may vectorize if vdt was used for math

I tried using vdt in the propagation loop, and still couldn't get LLVM to vectorize the loop.  I have some ideas about restructuring those loops so vdt can be effective, but since the issue is said to be "somewhat urgent" I decided that further research is out of scope for this PR (but still a subject for further investigation).

**Comment by slava77** [comment]
> since the issue is said to be "rather urgent" I decided that further research is out of scope for this PR (but still a subject for further investigation).

@cms-sw/reconstruction-l2 
please check and perhaps sign

**Comment by mandrenguyen** [comment]
From the PR description and code changes, I was not expecting any changes to the reco comparisons.
I see small changes in several [workflows](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-05-18-1100+922ee3/57144/validateJR.html)
Was my expectation incorrect?

**Comment by slava77** [comment]
> I see small changes in several [workflows](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-05-18-1100+922ee3/57144/validateJR.html)

do you mean just 12434.7 (mkFit devel test)?
Plots seem to show a one track migration in pixelPair vs pixelLess iteration.
While here the mkFit is recompiled, the changes are in the same workflow that's known to show occasional spurious differences #39803 

 🤷

**Comment by mandrenguyen** [comment]
+1
Small changes to mkFit devel test are expected ([link](https://github.com/cms-sw/cmssw/pull/41730#issuecomment-1560454536))

**Comment by perrotta** [comment]
+1

**Pull request merged**
