### PR TITLE
Cleaning Obsolete files in SLHCUpgradeSimulations/Geometry

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
This PR aims to clean some old/obsolete/unused files in the SLHCUpgradeSimulations/Geometry packages. Most of them are coming from the good old time of slhc releases .
Presumbaly this package can be cleaned further but i'm doing gradually...

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by boudoul** [comment]
Branch rebased

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
