### PR TITLE
SiPixelAlignment PCL harvester, add option to ignore exceeding thresholds on inactive modules when vetoing payload upload

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to add a mechanism to ignore exceeding movements thresholds in the veto of the payload upload logic of the pixel alignment prompt calibration loop harvesting module, when these happen on a **known** inactive region (as flagged by `SiPixelQuality`).
This should be able to address the cases in which a SiPixelAli PCL upload gets stuck due to exceeding thresholds for some time, while there is no actual good reason for it (as the vetoing "alignables" are anyway poorly measured due to the lack of hits on them). A real life case happened in 2024, and is documented in this [cmsTalk thread](https://cms-talk.web.cern.ch/t/express-prompt-trackeralignment-temporary-raising-hg-combined-thresholds-for-bpix-l4/43681).
The logic is done in such a way that this mechanism is steered via the boolean flag `ignoreInactiveAlignables` (by default left to `false`) and the "alignable" is flagged as inactive if at least 50% + 1 of its `deepComponents` are inactive as flagged by `SiPixelQuality`.
This is done via the following action items:
   * ce41c8c4597272144350bbe1584823176dde76dc: use `SiPixelQuality` in `MillePedeFileReader` and percolate consumes in calling classes
   * 13490018f731200be9b4853ea12b5058699d0933: add function to establish if the alignable is active or not 
   * b58a338bbd8fd2061a2cdaee8d2e0172201f1944: add flag to ignore inactive alignables in the veto map
   * 622a1297d47176b208605e96aaa7a084b9affed5, in addition, add `fillDescriptions` to `MillePedeDQMModule`

#### PR validation:

I tested this branch with the following script (trying to reproduce the failed uploads described above):

```bash
#!/bin/bash -ex
cmsDriver.py stepHarvestBlock \
         -s ALCAHARVEST:SiPixelAliHGCombined \
         --conditions 140X_dataRun3_Express_v3 \
         --custom_conditions=SiPixelQuality_phase1_2024_v7_mc,SiPixelQualityFromDbRcd \
         --scenario pp \
         --data \
         --dasquery='file dataset=/StreamExpress/Run2024F-PromptCalibProdSiPixelAliHGComb-Express-v1/ALCAPROMPT run=383377' \
         --era Run3_2024 \
         --no_exec 

cmsRun stepHarvestBlock_ALCAHARVEST.py >& log.log
```

   * with the branch as is the payload is still vetoed
   * if instead I flip this bit
   
```diff   
   diff --git a/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeFileReader_cfi.py b/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeFileReader_cfi.py
index 97e86628ca4..4d3e6a354bd 100644
--- a/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeFileReader_cfi.py
+++ b/Alignment/MillePedeAlignmentAlgorithm/python/MillePedeFileReader_cfi.py
@@ -2,7 +2,7 @@ import FWCore.ParameterSet.Config as cms
 
 MillePedeFileReader = cms.PSet(
     fileDir = cms.string(''),
-    ignoreInactiveAlignables = cms.bool(True),
+    ignoreInactiveAlignables = cms.bool(False),
     millePedeEndFile = cms.string('millepede.end'),
     millePedeLogFile = cms.string('millepede.log'),
     millePedeResFile = cms.string('millepede.res'),
```
   the payload gets written regularly.

In the specifics these were the alignables that got the payload vetoed

image

and here is the corresponding `SiPixelQuality` to be used

image

Also `runTheMatrix.py -l 1001.2,1001.3,1001.4 --ibeos` passes OK.
 
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * worfklows = 1001.2, 1001.3, 1001.4

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
