### PR TITLE
Remove unused constants in CondCore/EcalPlugins/plugins/Ecal*_PayloadInspector.cc

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

See title

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_X with cms-sw/cmssw#45110

**Comment by iarspider** [comment]
@Dr15Jones thanks!

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45110 for CMSSW_14_1_X

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmssw/pull/45110 for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+db
- Unused, indeed

**Comment by rappoccio** [comment]
+1

**Pull request merged**
