### PR TITLE
[RECO] [CLANG] More fixes on unused-but-set-variable warnings

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Follow-up PR for https://github.com/cms-sw/cmssw/pull/40397.
This PR fixes unused-but-set-variable warnings which we get with LLVM14 in CLANG IBS

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by aandvalenzuela** [comment]
please test

- https://github.com/cms-sw/cmssw/pull/40516 already handles warning in `CommonTools/Utils/test/testExpressionParser.cc`

**Comment by mandrenguyen** [comment]
Hello, can you please delete instead of commenting out lines in `TrackTransformerForCosmicMuons.cc` ?

**Comment by aandvalenzuela** [comment]
Hello @mandrenguyen,
Sure, I can do that. I have commented these lines because there is some comented code in https://github.com/cms-sw/cmssw/blob/master/TrackingTools/TrackRefitter/src/TrackTransformerForCosmicMuons.cc#L540 that also uses the `dz` variable. So in case someone uncomments these lines, there won't be trace of this variable. Should I also removed the already commented code?

**Comment by aandvalenzuela** [comment]
please test

- @mandrenguyen, let me know if you also want me to remove the already commented out lines that contain those variables or if it is fine to leave it like that. Thanks!

**Comment by mandrenguyen** [comment]
+reconstruction
technical, no change to reco

**Comment by perrotta** [comment]
+1

**Pull request merged**
