### PR TITLE
Run3-alca223 Fixes the issue reported in #38656

### LINKED ISSUE #38656: [LTO_X - Calibration/HcalAlCaRecoProducers] -Wodr compiler warnings
Hello,

We have seen some compiler warnings of the type `-Wodr` in LTO_X IBs ([CMSSW_12_5_LTO_X_2022-07-07-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/thu/12.5.LTO-thu-11/CMSSW_12_5_LTO_X_2022-07-07-1100) and [CMSSW_12_5_LTO_X_2022-07-06-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/wed/12.5.LTO-wed-11/CMSSW_12_5_LTO_X_2022-07-06-1100), for example) in package `Calibration/HcalAlCaRecoProducers`. See sample stack trace:

```
>> Building edm plugin tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/libCalibrationHcalAlCaRecoProducersPlugins.so
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/c++ -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++1z -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr -shared -Wl,-E -Wl,-z,defs tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaDiJetsProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaEcalHcalReadoutsProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaGammaJetProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaGammaJetSelector.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHBHEMuonFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHBHEMuonProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHEMuonFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHOCalibProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalHBHEMuonFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalHBHEMuonProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalHEMuonFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalIsotrkFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalIsotrkProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaHcalNoiseProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaIsoTracksFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaIsoTracksProducer.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaIsoTracksProducerFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaIsolatedBunchFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaIsolatedBunchSelector.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/AlCaLowPUHBHEMuonFilter.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/PrescalerFHN.cc.o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/ProducerAnalyzer.cc.o -o tmp/el8_amd64_gcc10/src/Calibration/HcalAlCaRecoProducers/plugins/CalibrationHcalAlCaRecoProducersPlugins/libCalibrationHcalAlCaRecoProducersPlugins.so -Wl,-E -Wl,--hash-style=gnu -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/biglib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/lib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/external/el8_amd64_gcc10/lib -L/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/cuda/11.5.2-c927b7e765e06433950d8a7eab9eddb4/lib64/stubs -lHLTriggerHLTcore -lCondFormatsHLTObjects -lDataFormatsHLTReco -lDataFormatsL1TParticleFlow -lDataFormatsMETReco -lDataFormatsTauReco -lCalibrationIsolatedParticles -lDataFormatsJetReco -lDataFormatsParticleFlowCandidate -lSimTrackerTrackerHitAssociation -lDataFormatsParticleFlowReco -lTrackingToolsTrackAssociator -lTrackingToolsTransientTrackingRecHit -lDataFormatsEgammaCandidates -lDataFormatsHcalIsolatedTrack -lDataFormatsL1TCorrelator -lDataFormatsL1TMuonPhase2 -lDataFormatsMuonReco -lTrackPropagationSteppingHelixPropagator -lTrackingToolsDetLayers -lDataFormatsL1TMuon -lDataFormatsRecoCandidate -lTrackingToolsGeomPropagators -lDataFormatsCSCDigi -lDataFormatsEgammaReco -lDataFormatsGsfTrackReco -lDataFormatsVertexReco -lRecoLocalCaloHcalRecAlgos -lSimDataFormatsTrackingAnalysis -lTrackingToolsTrajectoryState -lCalibCalorimetryHcalAlgos -lDataFormatsGEMDigi -lDataFormatsTrackReco -lCalibFormatsHcalObjects -lDataFormatsGEMRecHit -lDataFormatsTrackCandidate -lDataFormatsTrackerRecHit2D -lL1TriggerL1TGlobal -lTrackingToolsRecords -lCondFormatsHcalObjects -lDataFormatsCSCRecHit -lDataFormatsDTRecHit -lDataFormatsFTLRecHit -lDataFormatsL1TGlobal -lDataFormatsTrajectorySeed -lGeometryHcalTowerAlgo -lL1TriggerGlobalTriggerAnalyzer -lRecoLocalTrackerRecords -lCalibTrackerRecords -lDataFormatsL1Trigger -lDataFormatsTrackingRecHit -lGeometryCSCGeometry -lGeometryCaloTopology -lGeometryDTGeometry -lGeometryEcalAlgo -lGeometryGEMGeometry -lDataFormatsL1TrackTrigger -lGeometryEcalCommonData -lGeometryHcalCommonData -lMagneticFieldRecords -lMagneticFieldVolumeBasedEngine -lRecoLocalCaloEcalRecAlgos -lCondFormatsDataRecord -lDataFormatsTrackerCommon -lDetectorDescriptionRegressionTest -lGeometryCaloGeometry -lGeometryCommonTopologies -lMagneticFieldLayers -lCondCoreDBOutputService -lCondFormatsAlignment -lCondFormatsEcalObjects -lCondFormatsL1TObjects -lDataFormatsBeamSpot -lDataFormatsCaloTowers -lDataFormatsEcalRecHit -lDataFormatsGeometryCommonDetAlgo -lDataFormatsHcalRecHit -lDataFormatsHepMCCandidate -lDataFormatsSiStripCluster -lDetectorDescriptionParser -lGeometryHGCalCommonData -lGeometryRecords -lMagneticFieldVolumeGeometry -lSimDataFormatsCrossingFrame -lTrackingToolsAnalyticalJacobians -lCommonToolsUtilAlgos -lCondCoreCondDB -lCondFormatsAlignmentRecord -lCondFormatsESObjects -lDataFormatsCandidate -lDataFormatsDTDigi -lDataFormatsEcalDigi -lDataFormatsGeometrySurface -lDataFormatsHcalDigi -lDataFormatsL1GlobalCaloTrigger -lDataFormatsSiPixelDigi -lDataFormatsTrajectoryState -lDetectorDescriptionCore -lDetectorDescriptionDDCMS -lHeterogeneousCoreCUDACore -lMagneticFieldEngine -lSimDataFormatsTrackerDigiSimLink -lSimDataFormatsTrackingHit -lSimGeneralHepPDTRecord -lCalibFormatsCaloObjects -lCommonToolsUtils -lCondFormatsGeometryObjects -lDataFormatsCLHEP -lDataFormatsCaloRecHit -lDataFormatsEcalDetId -lDataFormatsForwardDetId -lDataFormatsGeometryVector -lDataFormatsHcalDetId -lDataFormatsL1CaloTrigger -lDataFormatsL1GlobalTrigger -lDataFormatsLuminosity -lDataFormatsMuonDetId -lDataFormatsPhase2TrackerCluster -lDataFormatsSiPixelDetId -lDataFormatsSiStripDetId -lFWCoreFramework -lFWCorePrescaleService -lHeterogeneousCoreCUDAServices -lSimDataFormatsCaloHit -lSimDataFormatsTrack -lSimDataFormatsVertex -lCUDADataFormatsCommon -lCondFormatsCommon -lDataFormatsDetId -lDataFormatsFEDRawData -lDataFormatsHcalCalibObjects -lDataFormatsL1GlobalMuonTrigger -lDataFormatsMath -lDataFormatsPhase2TrackerDigi -lDataFormatsScalers -lDataFormatsScouting -lDataFormatsSiPixelCluster -lDataFormatsSiStripDigi -lFWCoreCommon -lFWCoreServiceRegistry -lSimDataFormatsGeneratorProducts -lDataFormatsCommon -lFWCoreParameterSet -lHeterogeneousCoreCUDAUtilities -lFWCoreMessageLogger -lDataFormatsProvenance -lFWCorePluginManager -lFWCoreReflection -lTrackingToolsTrajectoryParametrization -lCondFormatsSerialization -lFWCoreConcurrency -lFWCoreUtilities -lFWCoreVersion -lSimDataFormatsEncodedEventId -lUtilitiesOpenSSL -lUtilitiesXerces -llcg_CoralCommon -llcg_RelationalAccess -llcg_CoralKernel -llcg_CoralBase -lDDAlign -lDDCond -lDDCore -lDDParsers -lMinuit -lMinuit2 -lGpad -lGraf -lPhysics -lHist -lMatrix -lGenVector -lMathMore -lTree -lNet -lGeom -lThread -lboost_filesystem -lMathCore -lRIO -lSmatrix -lboost_regex -lboost_serialization -lboost_system -lCore -lboost_thread -lboost_date_time -lCLHEP -lHepMCfio -lHepMC -lpcre -lbz2 -lcudart -lcudadevrt -lnvToolsExt -lnvidia-ml -lcurl -lgsl -lHepPDT -lHepPID -luuid -ltbb -lxerces-c -llzma -lz -lcuda -lfmt -lHepMC3 -lHepMC3search -lcms-md5 -lopenblas -lssl -lcrypto -lcrypt -ldl -lrt -lstdc++fs -ltinyxml2
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc:42:10: warning: type 'struct Counters' violates the C++ One Definition Rule [-Wodr]
    42 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonProducer.cc:42:10: note: a different type is defined in another translation unit
   42 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc:44:54: note: the first difference of corresponding definitions is field 'nFinal_'
   44 |     mutable std::atomic<unsigned int> nAll_, nGood_, nFinal_;
      |                                                      ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonProducer.cc:42:10: note: a type with different number of fields is defined in another translation unit
   42 |   struct Counters {
      |          ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonFilter.cc:26:10: warning: type 'struct Counters' violates the C++ One Definition Rule [-Wodr]
    26 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonProducer.cc:73:10: note: a different type is defined in another translation unit
   73 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonFilter.cc:28:54: note: the first difference of corresponding definitions is field 'nFinal_'
   28 |     mutable std::atomic<unsigned int> nAll_, nGood_, nFinal_;
      |                                                      ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaHcalHBHEMuonProducer.cc:73:10: note: a type with different number of fields is defined in another translation unit
   73 |   struct Counters {
      |          ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc:66:10: warning: type 'struct Counters' violates the C++ One Definition Rule [-Wodr]
    66 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducer.cc:80:10: note: a different type is defined in another translation unit
   80 |   struct Counters {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksFilter.cc:68:63: note: the first difference of corresponding definitions is field 'nHigh_'
   68 |     mutable std::atomic<unsigned int> nAll_, nGood_, nRange_, nHigh_;
      |                                                               ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c3240aee7d57ae1d85cdfe77a9c684cc/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-1100/src/Calibration/HcalAlCaRecoProducers/plugins/AlCaIsoTracksProducer.cc:80:10: note: a type with different number of fields is defined in another translation unit
   80 |   struct Counters {
      |          ^
Leaving library rule at src/Calibration/HcalAlCaRecoProducers/plugins
```

This warning is also shown in other packages, such as reported in https://github.com/cms-sw/cmssw/issues/38650. It seems there are some elements defined multiple times within the same namespace leading to violation of the C++ One Definition Rule. Could you please have a look at it?

Many thanks,
Andrea.

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address the issue (compilation warnings) reported in #38656
Fixes #38656

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@bsunanda please do code checks and squash it into the first commit

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_12_5_LTO_X

**Comment by tvami** [comment]
@bsunanda if this works, you'll also need to rename the PR, just saying it fixes the issue doesnt say much on the release notes

**Comment by tvami** [comment]
@bsunanda please squash

**Comment by bsunanda** [comment]
@tvami Did the squashing

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * LTO release compiles

**Comment by qliphy** [comment]
+1

**Pull request merged**
