### PR TITLE
HLT menu development for `14_0_X` (5/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44717

#### PR description:

Development of HLT menus for CMSSW_14_0_X. 
   * This version of the GRun HLT menu corresponds to the list of updates to the **"V1.1"** menu for the 2024 pp data-taking period.
   
This update includes the integration of the following JIRA tickets:
- [CMSHLT-3087](https://its.cern.ch/jira/browse/CMSHLT-3087) [HIG] New HLT Path (low pT single lepton + HT + B-tag) for HH to bbWW for 2024
- [CMSHLT-3104](https://its.cern.ch/jira/browse/CMSHLT-3104) [BTV] Migration of MC_PFBTag to ParticleNet
- [CMSHLT-3110](https://its.cern.ch/jira/browse/CMSHLT-3110) [HIG] Moving `HLT_QuadJet*` control paths to ParkingVBF
- [CMSHLT-3119](https://its.cern.ch/jira/browse/CMSHLT-3119) [EXO] Migration of the `QuadPFJet` with 3 B-tag trigger to Particle Net
- [CMSHLT-3120](https://its.cern.ch/jira/browse/CMSHLT-3120) [JME] Adding Dimuon+Jets & Photon+Jets paths for monitoring (CaloJet/Ak8PFJet/Ak8CaloJet)
- [CMSHLT-3122](https://its.cern.ch/jira/browse/CMSHLT-3122) [EXO] Adding new barrel-only displaced single muon paths
- [CMSHLT-3125](https://its.cern.ch/jira/browse/CMSHLT-3125) [TSG] Integrate Alpaka version of `Status_On*` Paths and Pixel local+track+vertex reconstruction
- [CMSHLT-3127](https://its.cern.ch/jira/browse/CMSHLT-3127) [BTV] Set PS=0 for `HLT_Mu8_*_Ele23_*_PFBtagDeepJet_*_v`
- [CMSHLT-3132](https://its.cern.ch/jira/browse/CMSHLT-3132) [TSG] Enforce a naming convention for Alpaka-related modules and their "SerialSync" variants
- [CMSHLT-3133](https://its.cern.ch/jira/browse/CMSHLT-3133) [TSG] Add PS column "2p0E34_NoScouting"
- [CMSHLT-3134](https://its.cern.ch/jira/browse/CMSHLT-3134) [TSG] Technical: "drop" statement in EventContents of Calibration, EcalCalibration and HLTMonitor streams
- [CMSHLT-3135](https://its.cern.ch/jira/browse/CMSHLT-3135) [TSG] Fix "prescale offsets" of Special* PDs
- [CMSHLT-3136](https://its.cern.ch/jira/browse/CMSHLT-3136) [TSG] Remove unused global PSets (post Run2023)
- [CMSHLT-3138](https://its.cern.ch/jira/browse/CMSHLT-3138) [Scouting] Update of the smart prescale of the DoubleEG path in the ScoutingPFMonitor PD
- [CMSHLT-3140](https://its.cern.ch/jira/browse/CMSHLT-3140) [TSG] Set smartPS=1 for HLT_ZeroBias_Alignment_v in ExpressPhysics
- [CMSHLT-3141](https://its.cern.ch/jira/browse/CMSHLT-3141) [TRK] Add Doublet-Recovery Track collection to EventContent of DQM stream
- [CMSHLT-3142](https://its.cern.ch/jira/browse/CMSHLT-3142) [TSG/EXO] Fix crashes from `hltDisplacedhltIter4PixelLessHitDoubletsForDisplacedTkMuons` at start of Run2024B
- [CMSHLT-3144](https://its.cern.ch/jira/browse/CMSHLT-3144) [PF] Increase `hltParticleFlowClusterHBHESoA*.pfRecHitFractionAllocation` to 250
- [CMSHLT-3145](https://its.cern.ch/jira/browse/CMSHLT-3145) [TSG] Disable Ele28+HT and Ele30+Jet cross-triggers
- [CMSHLT-3146](https://its.cern.ch/jira/browse/CMSHLT-3146) [TSG] Remove (temporarily) paths with reproducibility issues (in PRef and HIon)
- [CMSHLT-3150](https://its.cern.ch/jira/browse/CMSHLT-3150) [PF] Modify DQMGPUvsCPU EventContent to include `hltParticleFlowClusterHCAL` and `SerialSync` version
- [CMSHLT-3151](https://its.cern.ch/jira/browse/CMSHLT-3151) [TSG] Backport of online updates to cosmics and circulating menus (V1.1)

Also, move the HLT release template to `CMSSW_14_0_5`, remove `customizeHLTfor44591`

In addition, the following changes are included:
   * 7a581d2bf83a99b336040dd64194f1b1e148ef50: update `customizeHLTforAlpakaPixelReco`
   * 98d5408633a80ad11b214ba300e06a67df980a4b: equip HLT offline customization function to remove unnecessary strain on `Frontier`
   * 07d11a19218f766d0bec56fec4c3da435c01b180 : update of L1T FULL,GRun,2024v10,Special menus in TSG GTs to `L1Menu_Collisions2024_v1_1_0_xml`
   * f7e5c6940f4a91d34681abc32b57422c44198661 : update the list of HLT path owners: menu 2024 V1.1
   * d13c3a64c41e3fc8d80002029de4a2bc887e0491: added `customizeHLTforAlpakaRename` and removed `customizeHLTforAlpaka` calls in `customizeHLTforCMSSW`
   * 2ebf215f32ad849284f2aa461161858890763d55 : Introduce 2024v1.1 frozen menu and remove 2024v1.0

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/44717 to the 2024 production cycle (`CMSSW_14_0_X`)

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-sw/cmssw/pull/44598

**Comment by mmusich** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

Exceptionally not going to wait for the main branch IBs since it's the weekend.

**Pull request merged**
