### PR TITLE
add DQM Validation plots for MSSM Hbb Trigger Paths

### PR DESCRIPTION
**Pull request by heppye**

### CODE REVIEW

**Comment by heppye** [comment]
@deguio , could this PR be tested? Thanks, Ye

**Comment by deguio** [comment]
please test

**Comment by heppye** [comment]
@deguio , the cmsbuild test seems to be fine. Could you please take a look? Thanks, Ye

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
-1
already merged. see #13385

**Comment by deguio** [comment]
+1
already merged in 81x

**Comment by davidlange6** [comment]
+1

**Pull request merged**
