### PR TITLE
DD Cleanup

### PR DESCRIPTION
**Pull request by ianna**
- Remove obsolete package
- Remove const cast

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@smuzaffar - how do I request deleting a package? Thanks.

**Comment by smuzaffar** [comment]
@ianna , just like you did in this PR. Just removing the files is enough.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
