### PR TITLE
cleanup includes in SimDataFormats/GeneratorProducts

### PR DESCRIPTION
**Pull request by davidlange6**
Specifically moves any hepmc includes that can be replaced by forward declarations into the implementation

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by SiewYan** [comment]
please test

**Comment by davidlange6** [comment]
Was there some problem with the previous tests?

**Comment by SiewYan** [comment]
@davidlange6 sorry, i thought the PR is pending for test. I don't see any major difference between the tests.

**Comment by SiewYan** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
