### PR TITLE
Rho 8_0_X backport of PR 15233

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
8_0_X version of the earlier merged PR #15233
Identical commits, only backported to 8_0_X.

SCRAM_ARCH=slc6_amd64_gcc530
CMSSW_8_0_X_2016-10-16-0000
runTheMatrix.py -s

10 10 9 7 5 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed

### CODE REVIEW

**Comment by yetkinyilmaz** [comment]
@slava77 can you trigger the tests so that the PR progresses?
Thanks.

**Comment by yetkinyilmaz** [comment]
Workflow 281 also tested and passed (on CMSSW_8_0_X_2016-10-16-0000 in which run2 workflow is defined).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
merge conflicts are present here
@yetkinyilmaz please update the PR description as well (it says "Needed for the approval of #16120", but that PR is merged already)

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
@yetkinyilmaz: Please fix the merge conflicts as soon as you can. Once those are fixed and Jenkins tests are run, this PR can be approved.

**Comment by yetkinyilmaz** [comment]
Done.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cvuosalo 
this should be tested with customisePPrecoforPPb for signoff.
I'm guessing, a basic 136.731 or similar is a good workflow to start from.

**Comment by mandrenguyen** [comment]
@slava77 @cvuosalo wf 281 now includes the customize

**Comment by slava77** [comment]
@mandrenguyen 
thanks.
Is there a wf with forPbPb ?

**Comment by mandrenguyen** [comment]
@slava77 Ah, good point. For running the pp reco on peripheral PbPb I don't believe we have a relval wf.  Could be added.  In the meantime, just changing customisePPrecoforPPb to customisePPrecoForPeripheralPbPb, will have to suffice.

**Comment by cvuosalo** [comment]
backport #15233

**Comment by cvuosalo** [comment]
@slava77: Are the tests of this 80X version of this PR so essential that we should leave this PR out of 8_0_21, which is about to be built? The same tests were already performed for the 81X version of this PR, as discussed here: #15233. I think I will leave the decision to David. I will approve, start the tests, and report the results when they are available.

**Comment by yetkinyilmaz** [comment]
Just to note, it is tested privately with the following (including wf 281), both before and after yesterday's update.

export SCRAM_ARCH=slc6_amd64_gcc530
scram p CMSSW CMSSW_8_0_X_2016-10-16-0000
cd CMSSW_8_0_X_2016-10-16-0000/src
eval `scram ru -sh`
git cms-merge-topic yetkinyilmaz:rho_80X_01
scram b

runTheMatrix.py -l 281
runTheMatrix.py -s

**Comment by cvuosalo** [comment]
+1

For #16236 02b98ea5232a542bd2d1cdca8620d7ffc513ada6

Adding a Heavy Ion pPb customization to include a rho analyzer and empty area correction. The customization is not used by default. There should be no change in monitored quantities.

#15233 is the 81X version of this PR, and it has already been merged.

The code changes match those in #15233, and Jenkins tests against baseline CMSSW_8_0_X_2016-10-18-2300 show no significant differences, as expected, but DQM comparison results are not available. Additional tests were performed for #15233, including testing the new customization, and they show no problems.

Further tests of this PR are underway, but it has been approved provisionally to allow it to be included in 8_0_21.

**Comment by slava77** [comment]
On 10/20/16 5:30 AM, Carl Vuosalo wrote:
> @slava77 <https://github.com/slava77>: Are the tests of this 80X version
> of this PR so essential 
>that we should leave this PR out of 8_0_21,
> which is about to be built?

yes, considering that 8_0_21 build has started more than 20 hours ago

> The same tests were already performed for
> the 81X version of this PR, as discussed here: #15233
> <https://github.com/cms-sw/cmssw/pull/15233>. I think I will leave the
> decision to David. I will approve, start the tests, and report the
> results when they are available.

thanks in advance for checking the test results.

**Comment by davidlange6** [comment]
+1

**Comment by cvuosalo** [comment]
A test of workflow 281.0_EPOS_PPb with 20 events against baseline  CMSSW_8_0_21 shows no significant differences, as does a test of this workflow with customization customisePPrecoForPeripheralPbPb. The former test shows the expected rho additions to event content:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
      0.0 ->       190.9        191     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoCorr_RECO.
      0.0 ->       126.4        126     NEWO   0.03     doubles_hiFJRhoProducer_mapEtaEdges_RECO.
      0.0 ->       135.2        135     NEWO   0.03     doubles_hiFJGridEmptyAreaCalculator_mapEmptyCorrFac_RECO.
      0.0 ->       193.2        193     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoMCorr_RECO.
      0.0 ->       161.1        161     NEWO   0.04     doubles_hiFJRhoProducer_mapToRho_RECO.
      0.0 ->       202.9        203     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoCorr1Bin_RECO.
      0.0 ->       317.1        317     NEWO   0.07     doubles_hiFJRhoProducer_areaJets_RECO.
      0.0 ->       490.4        490     NEWO   0.11     doubles_hiFJRhoProducer_ptJets_RECO.
      0.0 ->       201.4        201     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoMCorr1Bin_RECO.
      0.0 ->       182.4        182     NEWO   0.04     doubles_hiFJRhoProducer_mapToRhoM_RECO.
      0.0 ->       534.9        535     NEWO   0.12     doubles_hiFJRhoProducer_etaJets_RECO.
-------------------------------------------------------------
   454124 ->      456902       2778             0.6     ALL BRANCHES
```

**Pull request merged**
