### PR TITLE
Phase2-hgx359P Prepare the material file to be updated later once the composition known for materials for the silicon component of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Prepare the material file to be updated later once the composition known for materials for the silicon component of HGCal

#### PR validation:

Tested with appropriate scripts in Geometry/HGCalCommonData/python/

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

@bsunanda , you change indentation in xml for purpose?

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@civanch Yes. For v19 there will be some changes in the material content

**Comment by mandrenguyen** [comment]
@cms-sw/upgrade-l2 can you have a look please?

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
