### PR TITLE
Fix online hi

### PR DESCRIPTION
**Pull request by deguio**
this PR contains:
- fixes to online applications in view of HI runnning (>=75x)
- update of GT and connection string for online
- fix to DQMStore for online applications when saving by LS (don't affect offline WFs)

### CODE REVIEW

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by slava77** [comment]
@deguio 
#12400 has the same change in 
RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py
please remove this change or check with @mmusich to get #12400 closed and superseded by this PR.

**Comment by mulhearn** [comment]
+1

**Comment by slava77** [comment]
#12400 is now merged.
If commit 1a85d12 is removed from this PR, the need for reco signature will go away.

**Pull request closed without merging**
