### PR TITLE
Enhance DQM for Pixel cluster on tracks

### PR DESCRIPTION
**Pull request by VinInn**
removed clusters off track, cleaned and streamlined code
added
plots by outer/inner Ladders (by hand, waiting the histograms manager is enhanced)
added cluster shape monitoring
as fraction of cluster passing the shape filter
and comparison of size prediction and actual

We shall plan back port to start running in production ASAP

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@arizzi @gpetruc @rovere @makortel @boudoul @veszpv @venturia FYI

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
This pull requests appears to be causing two of the IB RelVal workflows to fail: 7.2 and 7.3:
https://cms-sw.github.io/relvalLogDetail.html#slc7_aarch64_gcc530;CMSSW_9_3_X_2017-07-11-1100

**Comment by davidlange6** [comment]
ping @VinInn

**Comment by VinInn** [comment]
add siPixelClusterShapeCache to cosmic wf?
Most probably easier to add isValid to the handle (I suppose is enough) and protect the histo filling...
before tomorrow at noon (can be done even on the web...)

**Pull request merged**
