### PR TITLE
Lin log chi2 cut for patatrack

### PR DESCRIPTION
**Pull request by VinInn**
Modify the parameterization of the chi2cut to a simple linlog.
Chi2 cut "optimized" for PU ~50 using current realistic conditions for pixel detector.

Took the opportunity the address the issues raised in #34400

### CODE REVIEW

**Comment by VinInn** [comment]
@czangela

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test

to get cleaner CPU setup comparisons

**Comment by VinInn** [comment]
tested speed on T4.
Running 4 times over 5000 events with 1 jobs, each with 8 threads, 8 streams and 1 GPUs
triplets GPU only
CMSSW_12_0_0_pre2:                          1167.9 ±   2.9 ev/s
CMSSW_12_0_0_pre3:                          1184.8 ±   6.0 ev/s
CMSSW_12_0_X_2021-06-30-2300:  1187.4 ±  10.3 ev/s
CMSSW_12_0_X_2021-07-08-2300:  1185.2 ±  16.0 ev/s
this PR:                                                    1174.5 ±   9.3 ev/s

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@cmsbuild please code-check ?

**Comment by VinInn** [comment]
Timing on T4 (empty machine, fresh reboot)
```
CMSSW_12_0_0_pre2:                                         713.8 ±   1.6 ev/s
CMSSW_12_0_0_pre3:                                         710.1 ±   2.7 ev/s
CMSSW_12_0_X_2021-07-06-2300:                 749.5 ±   2.8 ev/s
CMSSW_12_0_0_pre4:                                         748.1 ±   2.0 ev/s
this PR:                                                                  748.5 ±   1.6 ev/s
```

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34419	dcdaca5
- code changes are in line with the PR description
    - items from #34400 are mostly/partially addressed
- jenkins tests pass and comparisons with the baseline show small differences in the pixel tracking GPU workflow

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
out of curiosity: how does the performance of `roughLog` compare with CUDA native `::logf` ?

**Comment by fwyzard** [comment]
there is also a fast approximate log2 PTX instruction, `lg2.approx.ftz.f32`, but I've never tried using inline PTX and I don't know if the CUDA `::log2f` uses that or not.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
> out of curiosity: how does the performance of `roughLog` compare with CUDA native `::logf` ?

@VinInn  Do you have numbers for the question?

**Pull request merged**
