### PR TITLE
Customise function to increase cluster number check and seeding limits (81X)

### PR DESCRIPTION
**Pull request by makortel**
This PR adds a customise function to increase cluster number check limits by 10x and `maxElement` for `PixelTripletLargeTipGenerator` and `MultiHitGeneratorFromChi2` by 5x. These should be sufficient to silence "TooManyClusters" and "TooManyTriplets" errors for the high pileup data.

The 80X PR (#16214) was tested in 8_0_20 with

```
cmsDriver.py step3 --conditions 80X_dataRun2_Prompt_v14 -s RAW2DIGI,L1Reco,RECO \
  --runUnscheduled --process reRECO --data --era Run2_2016 --eventcontent RECO \
  --scenario pp --datatier RECO \
  --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2016 \
  -n 5 --nThreads=5--fileout file:step3.root --filein <your-preferred-file> \
  --customise RecoTracker/Configuration/customiseClusterCheckForHighPileup.customiseClusterCheckForHighPileup
```

with a random file from ZeroBiasIsolatedBunch0 RAW.

The branch is based on CMSSW_8_1_0_pre12.

@rovere @VinInn @mtosi

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
.. not very useful for python-only change, but still.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16219 a281db1
- changes are in line with description
- jenkins tests pass but are irrelevant
- local tests with high PU run were done in 80X

**Comment by davidlange6** [comment]
+1

**Pull request merged**
