### PR TITLE
Add heavy ion EventPlane histograms to the Centrality DQM code

### PR DESCRIPTION
**Pull request by satan1028**
Added 6 histograms to DQM code

### CODE REVIEW

**Comment by BetterWang** [comment]
This is an update of the Centrality DQM with plots of Heavy Ion event-plane object.
We would like to have it in the relval to validate the event-plane code and calibration.
The event-plane code will be submitted in a future PR.

Thanks.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@satan1028 - please change the title of this PR to something descriptive for the release notes. Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
