### PR TITLE
Run2-gem28 Add a new version of GE11 geometry slice

### PR DESCRIPTION
**Pull request by bsunanda**
This new version reflects the real situation of installed GE1 chambers (in locations 1,27,28,29,30 on -z side). The earlier description was wrong

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
hi- @bsunanda - is there a summary of the motivations behind the changes in indico?

**Comment by bsunanda** [comment]
@davidlange6 I am not sure. Cesare and Teruki contacted me and it was verified by hardware people. These positions refer to the real positions of chambers installed on CMS last YETS

**Comment by davidlange6** [comment]
please follow up with them - geometry changes should not come undocumented at this point

**Comment by calabria** [comment]
@davidlange6 simply the previous geometry was wrong, it did not reflect the chambers we actually installed. In the previous geometry we had E-1 CH19,26,27,28,29 but actually the installed chambers are E-1 CH1,27,28,29,30. Please, have a look here: https://indico.cern.ch/event/641682/contributions/2603235/attachments/1474368/2282957/DPG-GEMMiniWorkShopJune2017.pdf , slides 9, 10 and 11. The current situation is the one that you see in the pic
schermata 2017-06-09 alle 16 28 06
schermata 2017-06-09 alle 16 33 00

ture in attachment.

**Comment by davidlange6** [comment]
so we've gone from "conforms better" to "wrong". not what I was expecting. Thanks  @bsunanda - please update the description as summarized by @calabria in terms of which chambers are installed.

**Comment by bsunanda** [comment]
@davidlange6 Chambers 1, 27, 28, 29, 30 installed on z =-1 side. The new geometry reflects that. I don't understand your comment.

**Comment by calabria** [comment]
Maybe my comment was not clear: the picures attached to the previous message were for the current situation that is wrong. Instead the picture attached here is obtained with the geometry of this PR, and it clearly shows that the chambers now are correct and consistent with what installed: endcap -1 and chambers 1,27,28,29,30.
schermata 2017-06-10 alle 15 25 31

**Comment by davidlange6** [comment]
all  is clear already - please edit the description at the top of the PR (eg, the first comment) to reflect what this PR really does rather than a vague comment that implies small changes

**Comment by davidlange6** [comment]
+1

**Pull request merged**
