### PR TITLE
fix HLT online DQM client to cope with PbPb HLT strip collections

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, aimed to fix the empty Strip collections at HLT seen in the early 2024 PbPb runs, e.g. [387886](https://cmsoms.cern.ch/cms/runs/report?cms_run=387886)  ([link to DQM](https://cmsweb.cern.ch/dqm/online/start?runnr=387886;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=HLT/SiStrip/MechanicalView;focus=;zoom=no;))

#### PR validation:

~~A full validation will need resolution of [CMSHLT-3392](https://its.cern.ch/jira/browse/CMSHLT-3392) - thus draft for now.~~ See https://github.com/cms-sw/cmssw/pull/46622#issuecomment-2466418452.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_14_1_X

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
for the record, I generated some streamers using a HLT menu that includes [CMSHLT-3392](https://its.cern.ch/jira/browse/CMSHLT-3392) (i.e. `/dev/CMSSW_14_1_0/HIon/V45`) starting from some recent 2024 `HIMinimumBias0` RAW data using this recipe:

```bash
#!/bin/bash -ex

# cmsrel CMSSW_14_1_4_patch3
# cd CMSSW_14_1_4_patch3/src
# cmsenv
# scram b

# run 387968, LS 
INPUTFILE=root://eoscms.cern.ch//eos/cms/tier0/store/hidata/HIRun2024A/HIMinimumBias0/RAW/v1/000/387/968/00000/779d1a75-b20c-4ad6-ab4a-4e049fe61765.root

HLTMENU=/dev/CMSSW_14_1_0/HIon/V45

rm -rf run387968*

# run on 100 events of LS 100-110, with 100 events per input file
convertToRaw -f 100 -l 100 -r 387968:100 -s rawDataRepacker -o . -- "${INPUTFILE}"

tmpfile=$(mktemp)
hltConfigFromDB --configName "${HLTMENU}" > "${tmpfile}"
sed -i 's|process = cms.Process( "HLT" )|from Configuration.Eras.Era_Run3_cff import Run3\nprocess = cms.Process( "HLT", Run3 )|g' "${tmpfile}"
cat <<@EOF >> "${tmpfile}"
process.load('run387968_cff')
process.hltOnlineBeamSpotESProducer.timeThreshold = int(1e6)

# override the GlobalTag, connection string and pfnPrefix
from Configuration.AlCa.GlobalTag import GlobalTag as customiseGlobalTag
process.GlobalTag = customiseGlobalTag(
    process.GlobalTag,
    globaltag = "141X_dataRun3_HLT_v1",
    conditions = "L1Menu_CollisionsHeavyIons2024_v1_0_5_xml,L1TUtmTriggerMenuRcd,frontier://FrontierProd/CMS_CONDITIONS,,9999-12-31 23:59:59.000"
)

process.hltDatasetHIOnlineMonitor.triggerConditions = cms.vstring('HLT_HICentrality50100MinimumBiasHF1AND_Beamspot_v1')
process.options.wantSummary = cms.untracked.bool(True)

# to make it trigger on all events
process.hltL1sCentrality50100MinimumBiasHF1ANDBptxAND.L1SeedsLogicalExpression = cms.string('L1GlobalDecision')
# used to be ('L1_Centrality_30_100_MinimumBiasHF1_AND_BptxAND')

# run the Full L1T emulator, then repack the data into a new RAW collection, to be used by the HLT
from HLTrigger.Configuration.CustomConfigs import L1REPACK
process = L1REPACK(process, "uGT")

# Multi-threading
process.options.numberOfConcurrentLuminosityBlocks = 2      # default: 2
process.options.numberOfStreams = 32                        # default: 32
process.options.numberOfThreads = 32                        # default: 32

# to run without any HLT prescales
del process.PrescaleService

# to reset the MessageLogger (and print at every event)
del process.MessageLogger
process.load('FWCore.MessageService.MessageLogger_cfi')  

# # to run using the same HLT prescales as used online in LS 231
# process.PrescaleService.forceDefault = True
@EOF
edmConfigDump "${tmpfile}" > hlt.py

cmsRun hlt.py &> hlt.log

# remove input files to save space
rm -f run387968/run387968_ls0*_index*.*

#######################################################
# After this, prepare the streamer files with the following recipe:
#######################################################
mv run387968 source
mkdir -p run387968
cp source/run387968_ls0100_streamHIDQM_*.jsn run387968
for file in source/run387968_ls0000_streamHIDQM_*.ini; do
    # Extract the variable part in place of '*'
    variable_part=$(basename "$file" | sed 's/^run387968_ls0000_streamHIDQM_//; s/\.ini$//')

    # Concatenate files with the same variable part
    cat "source/run387968_ls0000_streamHIDQM_${variable_part}.ini" \
        "source/run387968_ls0100_streamHIDQM_${variable_part}.dat" \
        > "run387968/run387968_ls0100_streamHIDQM_${variable_part}.dat"
done
```

and then run the hlt online client after merging this PR with:

```
 cmsRun DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py runInputDir=. outputBaseDir=./output runNumber=387968 runkey=hi_run scanOnce=True
```

I obtained the file that I put at https://cernbox.cern.ch/s/EzDeC2jpSVSEDEo (all Pixel, Strip, Tracking and Vertexing distributions are filled).

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/46622#issuecomment-2466418452
   * waiting for a final validation from the DQM team via online DQM replay.

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 please review / sign.
We'll need to have the backport of this (https://github.com/cms-sw/cmssw/pull/46667) for online operations.

**Comment by antoniovagnerini** [comment]
hi, 46622 was already deployed in production

**Comment by mmusich** [comment]
> hi, 46622 was already deployed in production

then, please sign :)

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
