### PR TITLE
fix non const static and obsolete avx code

### PR DESCRIPTION
**Pull request by VinInn**
trivial technical changes.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
please test
sigh

**Comment by VinInn** [comment]
interesting comments.
Worth fixing. still this is purely  accidental. Happens to be recompiled in this PR.
What is the policy about llvm warning? I suppose half of cmssw is affected....

**Comment by davidlange6** [comment]
cmssw has 40 warnings in the clang IB.. but your PR does appear to cause the error

error: default initialization of an object of const type 'const (anonymous namespace)::Stat' without a user-provided default constructor

(for which there are none in cmssw currently)

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
other clang warnings will be fixed when ALL tracker PR will be merged to avoid conflicts

**Comment by lveldere** [comment]
-1

@VinInn

Hi Vincenzo

Something is wrong with the FastSim changes.
You've undone a recent pr of mine: #13320 

Cheers

Lukas

**Comment by VinInn** [comment]
rebase failed!

**Pull request closed without merging**
