### PR TITLE
L1 Prefiring weight extractor (backport to 9_4_X)

### PR DESCRIPTION
**Pull request by lathomas**
Backport of https://github.com/cms-sw/cmssw/pull/25380 for 9_4_X. 
N.B. This code makes use of external files in 
https://github.com/cms-data/PhysicsTools-PatUtils
which may imply a backport of the following PR as well (?)
https://github.com/cms-sw/cmsdist/pull/4595

### CODE REVIEW

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4636

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4636

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4636

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4636

**Comment by mrodozov** [comment]
not sure why it didn't started

**Comment by perrotta** [comment]
backport of #25380

**Comment by perrotta** [comment]
@lathomas : to simmetrize with the PR in the master, you could profit of the new externals and remove ```pfJetResolutionMCtoDataCorrLUT.root``` from ```PhysicsTools/PatUtils/data/```
(not really relevant, due to the limited gain in size: but having it in one single repository could avoid people making possible mistakes if they want to modify those LUTs privately for their own analysis)

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4636

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4636
(I have no idea what the "an issue with git-cms-merge-topic" can be, also because the log is not accessible. Let retry running the tests)

**Comment by perrotta** [comment]
@mrodozov @smuzaffar : do you have an idea about what the error message https://github.com/cms-sw/cmssw/pull/25646#issuecomment-454582652 refers to, and how to fix it? It currently prevents the central tests to be run

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
a manual cms-merge-topic seems to succeed without any issue...

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#4636

**Comment by fabiocos** [comment]
Ok, this is the report from the console:

10:57:32 + git cms-merge-topic --ssh -u 25646
10:57:32 No release tags specified, using default CMSSW_9_4_X_2019-01-16-2300.
10:57:34 Cloning into '/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_9_4_X_2019-01-16-2300/src'...
11:09:41 error: RPC failed; curl 18 transfer closed with outstanding read data remaining
11:09:41 fatal: The remote end hung up unexpectedly
11:09:41 + grep 'Automatic merge failed' /build/cmsbld/jenkins/workspace/ib-any-integration/git-merge-result
11:09:41 + grep 'Couldn'\''t find remote ref' /build/cmsbld/jenkins/workspace/ib-any-integration/git-merge-result
11:09:41 + git diff --name-only CMSSW_9_4_X_2019-01-16-2300
11:09:42 + grep ALL_OK /build/cmsbld/jenkins/workspace/ib-any-integration/git-merge-result
11:09:42 + echo 'There was an error while running git cms-merge-topic'
11:09:42 There was an error while running git cms-merge-topic
11:09:42 + /build/cmsbld/jenkins/workspace/ib-any-integration/cms-bot/report-pull-request-results GIT_CMS_MERGE_TOPIC_ISSUE --repo cms-sw/cmssw --pr 25646 --pr-job-id 32663
11:09:47 you chose the action GIT_CMS_MERGE_TOPIC_ISSUE
11:09:47 API Rate Limit: 4603/5000, Reset in 1702 sec i.e. at 2019-01-17 11:38:01
11:09:47 + exit 0

**Comment by fabiocos** [comment]
in a test of mine:

11:18 cmsdev15 515> git cms-init --upstream-only ; git checkout -b prova ; git cms-merge-topic 25646
Cloning into '/build/fabiocos/94X/CMSSW_9_4_X_2019-01-16-2300/src'...
Checking connectivity: 1847738, done.
Switched to a new branch 'from-CMSSW_9_4_X_2019-01-16-2300'
Switched to a new branch 'prova'
From .
 * [new ref]                            -> merge-attempt
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Total 10 (delta 8), reused 8 (delta 8), pack-reused 2
Unpacking objects: 100% (10/10), done.
From https://github.com/cms-sw/cmssw
 * [new ref]                 refs/pull/25646/head -> cms-sw/refs/pull/25646/head
Switched to branch 'merge-attempt'
Removing PhysicsTools/PatUtils/data/pfJetResolutionMCtoDataCorrLUT.root
Merge made by the 'recursive' strategy.
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
 PhysicsTools/PatUtils/data/pfJetResolutionMCtoDataCorrLUT.root    | Bin 4222 -> 0 bytes
 PhysicsTools/PatUtils/plugins/L1ECALPrefiringWeightProducer.cc    | 226 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 PhysicsTools/PatUtils/python/L1ECALPrefiringWeightProducer_cff.py |   6 ++
 3 files changed, 232 insertions(+)
 delete mode 100644 PhysicsTools/PatUtils/data/pfJetResolutionMCtoDataCorrLUT.root
 create mode 100644 PhysicsTools/PatUtils/plugins/L1ECALPrefiringWeightProducer.cc
 create mode 100644 PhysicsTools/PatUtils/python/L1ECALPrefiringWeightProducer_cff.py
Switched to branch 'prova'
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
>> Checking PhysicsTools/PatUtils CMSSW_9_4_X_2019-01-16-2300
   - PhysicsTools/PatUtils/data/pfJetResolutionMCtoDataCorrLUT.root
>> Creating dummy files under /build/fabiocos/94X/CMSSW_9_4_X_2019-01-16-2300/poison directory.
   PhysicsTools/PatUtils/data/pfJetResolutionMCtoDataCorrLUT.root
Checking out these packages: 0

**Comment by fabiocos** [comment]
@smuzaffar any idea why the problem appears to be systematic and not just a random glitch?

**Comment by fabiocos** [comment]
@smuzaffar ok, indeed this time it worked, so the glitches with 9_4_X look random as you noticed in IBs...

**Comment by fabiocos** [comment]
@perrotta FYI

**Comment by smuzaffar** [comment]
I also had tried locally (multiple times) and cms-merge-topic worked. Looks like now github behaving normally.

**Comment by perrotta** [comment]
+1
- This is an analysis tool not used by default in any official workflow, but meant for now to private analyses and eventually possibly also nanoAOD production
- Identical to #25380, merged in the master
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
