### PR TITLE
Run3-205D Last step for modernize the HCAL AlCaReco producers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Last step for modernize the HCAL AlCaReco producers

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * diffs in the msg logger only

**Comment by perrotta** [comment]
+1

**Pull request merged**
