### PR TITLE
Added new DQM GUI support to all Online DQM clients

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Added PB output support to all DQM Online clients.

#### PR validation:

PR was validated locally as well as in production during the last MWGR.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by silviodonato** [comment]
Just click on "Ready for review" when is ready

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

This code was successfully running in the last MWGR and is ready to be integrated.

**Comment by andrius-k** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
