### PR TITLE
Prioritize exception from Paths

### PR DESCRIPTION
**Pull request by Dr15Jones**
When multiple exceptions occur when processing an Event, prioritize the exception originating from a Path over those from EndPaths or Accumulators. 

This comes from diagnosing failures coming in the gcc 8 IBs where an exception originating in a Path ultimately leads to missing data which triggers a different exception when running accumulators.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar are the tests for this pull request stuck? The log has the last entry at 20:00 yesterday.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
The unit test failure is from an assert failing while running cmsRun. Unfortunately, the output of cmsRun is not preserved so it is not possible to see what failed.

**Comment by Dr15Jones** [comment]
@fabiocos this change should only effect what exception message is printed when a job fails. The pull request should have absolutely no effect on jobs that run without a problem.

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
@fabiocos I reran the unit test locally 50 times and never had a failure. Therefore I feel comfortable saying it was a transient effect.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
