### PR TITLE
Run3-gex174 Add RPD in the latest version of 2023 Gemetry as requested by the ZDC group for the next HI simulation effort

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add RPD in the latest version of 2023 Gemetry as requested by the ZDC group for the next HI simulation effort

#### PR validation:

Test using th4 g4 overlap tool

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May be required to be backported to 13_2_X for HI simulation effort

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@srimanob Please approve this PR. It is urgently needed. Without this in the IB, the back ports do 13_X_Y does not make sense. Please do this at your earliest convenience

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Actually, I am not clear in the PR after read the PR description again.  The change applied to 2023 geometry. Is this mean that this geometry is good also for future 2023 MC, i.e. legacy at the end of Run-3? Or this is specific for HI only.

Any reference doc or meeting on the change should be ref.

**Comment by makortel** [comment]
> @smuzaffar @markotel This deals with Run3 geometry. I wonder why upgrade signature is needed for this.

Because according to https://github.com/cms-sw/cms-bot/blob/master/categories_map.py these two packages should be reviewed also by upgrade. Adjustments on that policy are not really up to us (we just implement the policy).

**Pull request merged**
