### PR TITLE
Herwig7 hadron flavour identification

### PR DESCRIPTION
**Pull request by knash**
#### PR description:

Pull request to incorporate hadron flavour identification with Herwig7.
This is just a merge of the two PRs from @raggleton and Radek Zlebcik

https://github.com/cms-sw/cmssw/commit/8866ad2aa366cd3ba4aa1086d434ae21b6e1b7a8
and
https://github.com/raggleton/cmssw/commit/b4a6384fcaf66e3ec20b34c9ce75f60353443658

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 511.0

**Comment by santocch** [comment]
+1 

- it does what it has been declared

**Comment by fabiocos** [comment]
@smuzaffar according to my test two of the Merge commits of this PR have exactly the same string message of other similar commits in the past history, as far as I can see they are not jeoparidizing the history. Anyway I wonder whether it might be better/safer to squash all commits into a single one, given there is no special review history to be preserved here

**Comment by smuzaffar** [comment]
@fabiocos , there is no need to squash.

**Comment by fabiocos** [comment]
+1

**Comment by ahinzmann** [comment]
We would need to backport this bugfix to the releases for 2017 and 2018 MC production for Herwig7 samples.

@knash Can you make them?

@All: Would this go to the 9_4_X and 10_2_X queues or some special queues for bug-fixes/patches?

**Comment by knash** [comment]
@ahinzmann Sure thing

**Comment by emilbols** [comment]
@knash @jpata @slava77 It appears this PR was never backported to 106X, which i guess was an oversight. It seems that the herwig7 samples with UL processing all have the parton flavour of jets left undefined because of this. I'm not entirely sure if the hadron flavour is also broken or if it is ok (maybe @ferencek knows?).

FYI: @lathomas @kirschen @XavierAtCERN @smoortga @ahinzmann

**Comment by ferencek** [comment]
@emilbols, hadron flavour is generator-independent so even if the generator/hadronizer is not recognized, the hadron flavour should be correctly defined.

**Pull request merged**
