### PR TITLE
[12_6_X] RPCOccupancyTest crash protection for 0 LS

### PR DESCRIPTION
**Pull request by pmandrik**
#### PR description:
See https://github.com/cms-sw/cmssw/pull/39558

### CODE REVIEW

**Comment by pmandrik** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/dqm-l2 signing a backport PR implies, amongst other thimgs, that you verified that the master version of the PR run without errors and behaved as expected. You already signed the backports of this PR: either sign also this one, or remove the signatures in the two backport ones while waiting for evaluating this one in the master

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Pull request merged**
