### PR TITLE
Handle SiPM nonlinearity in premixing [90X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #17920

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17921	c943ab9
- same change as in 91X version #17920  (the same topic branch)
- same conclusions apply as in the signoff of #17920 for the reco part

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ghellwig** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17921	c5d59a4
- the same change (the same topic branch) as in 91X #17920 
- same conclusions as in the signoff on 91X version

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17921	6884737
- somewhat technical update since the last signoff: the PR was updated with what went to https://github.com/cms-sw/cmssw/pull/18058	6884737. The code change affects only cases which would otherwise crash
- jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
for 91x

**Comment by kpedro88** [comment]
@davidlange6 so premixing won't be used extensively in 90X?

**Comment by davidlange6** [comment]
that boat is sailing already

**Comment by kpedro88** [comment]
By that do you mean the premixing input file was already generated with 900 and won't be regenerated despite other known bugs in 900? That does not seem like a good idea to me.

**Comment by davidlange6** [comment]
no, classic mixing will be used while premixing is validated (in 91x)

**Comment by abdoulline** [comment]
Good to know... thanks

**Comment by kpedro88** [comment]
Okay, in that case I agree this isn't needed in 90X, thanks

**Pull request closed without merging**
