### PR TITLE
fix DDFilteredView::parameters() crashing with a pseudotrapezoid

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:
Adrressing the issue discussed in [#29781 (comment)](https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054), so that [this hack](https://github.com/cms-sw/cmssw/pull/29781#discussion_r422365054) can be removed, as also discussed [here](https://github.com/cms-sw/cmssw/pull/31691#issuecomment-704896866).

@ianna, the problem was not solved in #31691 so I had to fix DDFilteredView. The fix is just an explicit protection for pseudotrapezoids. I guess it could have been implemented using `isASubtraction()` , as [introduced in 31691](https://github.com/cms-sw/cmssw/pull/31691/files#diff-7823e114fef4afa095ad8272d17c4238L168), but this way looks safer to me.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
- Thanks to the protection inserted in DDFilteredView.cc, the hack for pseudotraps introduced with #29781 can be reverted in MagneticField/GeomBuilder/src/DD4hep_volumeHandle.cc
- Jenkins tests pass and show no difference wrt the hacked version of the code

**Comment by silviodonato** [comment]
+1

**Pull request merged**
