### PR TITLE
Phase2-hgc355A Complete the PR #44907 by adding the dd4hep of the algorithm DDHGCalPassive to be used for the V19 Geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Complete PR #44907 by adding the dd4hep of the algorithm DDHGCalPassive to be used for the V19 Geometry of HGCal

#### PR validation:

Use the test in #44907

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Hi @bsunanda 
Is this PR used the DD4hep workflow, or to use, i.e. something to implement in coming PR? Thx.

**Comment by bsunanda** [comment]
@srimanob This will be used in a future code for silicon modules of HGCal. The code is under testing

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
