### PR TITLE
[10.0.X] Update GT: Update all L1T tags

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI data

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v4):
      * Add All L1Tag

   * **RunI Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v3):
      * Add All L1 Tag

## RunII data

   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v2) as [94X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v2/94X_dataRun2_HLTHI_frozen_v3):
      * Add All L1 Tag

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v5) as [94X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v5/94X_dataRun2_HLT_relval_v6):
      * Add All L1 Tag

   * **RunII Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v3):
      * Add All L1 Tag

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v5) as [94X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v5/94X_dataRun2_relval_v6):
      * Add All L1 Tag

   * **RunII Prompt processing** : [94X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v5) as [94X_dataRun2_PromptLike_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v5/94X_dataRun2_PromptLike_v6):
      * Add All L1 Tag

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v4):
      * Add All L1 Tag

## Upgrade

   * **PhaseII realistic scenario** : [94X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v2) as [94X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2023_realistic_v2/94X_upgrade2023_realistic_v3):
      * Add All L1 Tag

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4) as [94X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4/94X_upgrade2018cosmics_realistic_deco_v5):
      * Add All L1 Tag

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v5) as [94X_upgrade2018_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v5/94X_upgrade2018_design_IdealBS_v6):
      * Add All L1 Tag

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v5) as [94X_upgrade2018_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v5/94X_upgrade2018_realistic_v6):
      * Add All L1 Tag

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v4) as [94X_mc2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v4/94X_mc2017cosmics_realistic_peak_v5):
      * Add All L1 Tag

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v4) as [94X_mc2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v4/94X_mc2017cosmics_realistic_deco_v5):
      * Add All L1 Tag

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v5) as [94X_mc2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v5/94X_mc2017_design_IdealBS_v6):
      * Add All L1 Tag

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v5) as [94X_mc2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v5/94X_mc2017_realistic_v6):
      * Add All L1 Tag

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Hi @kkotov 
Most of the crashes are not very helpful but looking at:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21137/24140/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log
I see:
No "L1TMuonEndCapParamsRcd" record found in the EventSetup for synchronization value

Is this related to the change in the record name you proposed?

**Comment by kkotov** [comment]
Hi @lpernie ,
Hmm, the crash happens because 94X_mcRun2_asymptotic_v0 (pointed by run2_mc auto conditions) doesn't have the L1TMuonEndCap tags (both Params and Forest). The other L1T tags are up to date.
As the new EMTF emulator is now merged to the 94X we need to augment the mcRun2 GTs with the new EndCap tags. I've requested 2016 tags in the corresponding queues. Should I have been using 2017 tags instead?

**Comment by lpernie** [comment]
Hi @kkotov ,
So, if I'm correctly understanding, that TAG should be inserted in all mcRun2 GT?
If so, could you queue them?
Just to understand: that TAGs should be added but they will not be consumed right?

**Comment by kkotov** [comment]
Hi @lpernie ,
I already requested the 2016 tags in the mcRun2 GTs of 94X. Just want to confirm that mcRun2 is pre-2017, otherwise I queue 2017 tags instead. I guess I'll need to do the same for 92X as well.

As of the tags, they will be consumed by the new EMTF emulator as the second file in this PR removes the fake producer.

**Comment by lpernie** [comment]
Yes, mcRun2 is pre-2017. Ok, I can update the PR updating mcRun2 GT and see if this solve the problem.

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
@smuzaffar @davidlange6 

Seems like a problem with the IB itself : https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21137/24189/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step3_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT.log

we can retrigger the tests whenever new IB will be available.

**Comment by smuzaffar** [comment]
@arunhep , all tests run fine in IBs https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc630;CMSSW_10_0_X_2017-11-05-0000

**Comment by arunhep** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by arunhep** [comment]
@davidlange6 @smuzaffar @rekovic @kkotov 

we will need your help in sorting out the failures here. 

1. in unit tests the failure message is like : 

=============================================

MessageLogger Summary

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------

dropped waiting message count 0
stat: cannot stat `dqm_empty.root': No such file or directory
read_missing_file_cfg.py ------------------------------------------------------------
09-Nov-2017 08:25:28 CET  Initiating request to open file file:dqm_missing.root
----- Begin Fatal Exception 09-Nov-2017 08:25:29 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
   [2] Calling StorageFactory::open()
   [3] Calling File::sysopen()
Exception Message:
Failed to open the file 'dqm_missing.root'
Input file file:dqm_missing.root was not found, could not be opened, or is corrupted.
   Additional Info:
      [a] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 Fatal Exception      -s AfterModBeginStr                       1        1
    2 fileAction           -s AfterModBeginStr                       1        1

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 Fatal Exception      BeforeEvents                      
    2 fileAction           BeforeEvents                      

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  2                   2

dropped waiting message count 0
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_10_0_X_2017-11-08-2300
status = 0

2. in matrix tests  we see a segmentation failure in almost all the workflows :
e.g.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21137/24290/runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21137/24290/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

the update is only for the L1T tags for which some of them are added and some are replaced.
another change is the removal of https://github.com/cms-sw/cmssw/pull/21137/files#diff-6a37c45eab8a198fec5379e27216dbc3L57 to remove the loading of conditions related to EMTF two times (from individual tag and from GT) @rekovic suggested this as the easiest solution. Is this the reason?

**Comment by arunhep** [comment]
Ok. I made some tests locally. And what needs to be done to make it work is the following.

1. add back this line https://github.com/cms-sw/cmssw/pull/21137/files#diff-6a37c45eab8a198fec5379e27216dbc3L57 so basically keep what we have right now.

2. remove L1TMuonEndCapForest_static_Sq_20170613_v7_mc and all other tags related to L1TMuonEndCapForest from the GTs.

or @rekovic suggest us another way of removing consumption of tags related to L1TMuonEndCapForest outside GT. Because removing of this line  https://github.com/cms-sw/cmssw/pull/21137/files#diff-6a37c45eab8a198fec5379e27216dbc3L57 is causing the segmentation violation.

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
please abort

**Comment by arunhep** [comment]
please test

**Comment by rekovic** [comment]
The error in the first step of AddOn Test `hlt_data_GRun`
does not seem to point to problems with L1T.

```
HcalSeverityLevelComputer: Error: RecHitFlag >>HFDigiTime<< unknown. Ignoring.
%MSG
>> CTPPSIncludeAlignments::PrepareSequence(Measured)
>> CTPPSIncludeAlignments::PrepareSequence(Real)
	first=      -inf, last=      +inf: alignment blocks=1
>> CTPPSIncludeAlignments::PrepareSequence(Misaligned)
13-Nov-2017 06:43:32 CET  Initiating request to open file file:RelVal_Raw_GRun_DATA.root
----- Begin Fatal Exception 13-Nov-2017 06:43:33 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   Additional Info:
      [a] Input file file:RelVal_Raw_GRun_DATA.root could not be opened.
      [b] Fatal Root Error: @SUB=TStorageFactoryFile::ReadBuffer
read from Storage::xread returned 260. Asked to read n bytes: 300 from offset: 0 with file size: 260

----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
maybe eos problem

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@rekovic 
Sorry, no, the error is in the previous L1REPACK step:
```
Module: L1TMuonEndCapTrackProducer:simEmtfDigis (crashed)
Module: none
Module: none
Module: none
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21137/24390/addOnTests/hlt_data_GRun/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run2_hlt_GRun_--relval_9000,50_--datatier_RAW_--eventcontent_RAW_-.log

**Comment by rekovic** [comment]
@Martin-Grunewald Right. Thanks.

**Comment by kkotov** [comment]
This PR fails because of inconsistency between L1TMuonEndCapForest and L1TMuonEndCapParams. 
We've found that the Forests switched the scheme at run 295039: https://cms-conddb-prod.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonEndCapForest_Stage2v1_hlt .
On the other hand Params report the Forest version switch at run 296935:
cmsRun $CMSSW_RELEASE_BASE/src/L1TriggerConfig/Utilities/test/viewECpar.py db=prod run=296934

We will confirm which run the switch really happen with the experts ( @abrinke1 ) and provide you with a newer tag for either of the two types involved.

**Comment by rekovic** [comment]
@kkotov 
As you are going to update the payloads to be in synch, can you please queue them for the GT
and inform @lpernie and @arunhep so that they can adjust this PR accordingly.  Thanks.

**Comment by lpernie** [comment]
yes please let us know what you queues and where and we can proceed.

**Comment by kkotov** [comment]
The new tag is queued: [Search for L1TMuonEndCapParams_Stage2v3_hlt](https://cms-conddb.cern.ch/cmsDbBrowser/logs/global_tag_logs/Prod)

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by arunhep** [comment]
@dmitrijus can you please check and sign it?

**Comment by jfernan2** [comment]
@dmitrijus is offline today, I may sign on behalf of DQM. PR seems fine

**Comment by jfernan2** [comment]
+1

**Comment by arunhep** [comment]
@jfernan2 Thanks !

**Comment by davidlange6** [comment]
please test
(comparison differences seem to be fake)

**Comment by arunhep** [comment]
@davidlange6 can this PR be merged please? With this we will have this duplicity removed for L1T fake EMTF params and we can arrange the queues accordingly. Thanks.

**Comment by arunhep** [comment]
@davidlange6 can this PR be merged please?
we have few other updates lined up for 10.0.X.
Thanks.

**Comment by davidlange6** [comment]
i didn't have a chance to understand the physics changes on Friday. Do you expect them?

**Comment by arunhep** [comment]
@davidlange6 we don't expect physics changes because of these updates.
these updates are mainly for L1T caloParams and BMTF and EMTF parameters.

And i don't see any in 2017, 2018 MC. 
for data wf 136.731 I see only changes in the L1T directory : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-11-15-1100+21137/23739/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/L1T.html

can you please point me to the changes which you may have seen and not directly understood from these updates?

**Comment by kkotov** [comment]
Perhaps, @rekovic can give a better summary of the DQM differences, but as far as I remember, for the L1T, DQM results for data are expected to be different between new and old GTs. We've finally switched to configuring L1T from O2O tags in CondDB as opposed to static pythons as it was before.

**Comment by davidlange6** [comment]
instead of the nominal 1 histogram changed there are ~2000 - I didn't look further yet

**Comment by davidlange6** [comment]
looks like 2017B data, 2016B data

**Comment by rekovic** [comment]
@davidlange6 

When we introduced the NoHackConditions originally we knew that we were missing some BMTF Conditions from the GT.  https://github.com/cms-sw/cmssw/pull/20871#issuecomment-335511298
Then, we had ~2000 comparison histograms with changes https://github.com/cms-sw/cmssw/pull/20871#issuecomment-335498328. The report is now old, and cannot access the histograms. 

Now, this PR provides the missing BMTF conditions, and we now have ~2000 histograms showing differences.  The numbers make sense.  Need to look at the histograms.

**Comment by rekovic** [comment]
All the differences I found have to do with uGMT (i.e. Muons), fund in either `L1TEMU` or `L1T`
folders.

An example being data vs emul comparisons in `L1TEMU`
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-11-15-1100+21137/23739/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/L1TEMU_L1TdeStage2uGMT_data_vs_emulator_comparison.html

Another example is change in `L1T/L1TStage2uGMT`
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-11-15-1100+21137/23739/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/L1T_L1TStage2uGMT.html

As usual, we need to look at the higher statistics RelVal samples to finally validate the new release.
But from what I see from comparisons, the observed changes are at the right place. So,

+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
