### PR TITLE
Add esConsumes to MuonTrajectoryBuilder inheriting classes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Based on static analyzer report, changed those classes inheriting from MuonTrajectoryBuilder which were obtaining data from the EventSetup.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34593	de73ab5
- code changes are technical, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
