### PR TITLE
add XiMinus gen fragment for BPH validation

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:

this PR adds the XiMinus genFragment in order to have this process in the relval matrix as well

the TuneCP5 is used, and the filter efficiency (thanks to @AdrianoDee) is the following
Before Filter: total cross section = 7.893e+10 +- 6.065e+01 pb
== CMSSW: Filter efficiency (taking into account weights)= (487) / (25000) = 1.948e-02 +- 8.741e-04
== CMSSW: Filter efficiency (event-level)= (487) / (25000) = 1.948e-02 +- 8.741e-04    [TO BE USED IN MCM]

I'm going to prepare the backport in 12_4_X as well

### CODE REVIEW

**Comment by mtosi** [comment]
this genFragment could be useful for the upcoming validation of the "rollback of the pixelles tracking to CKF"

**Comment by SiewYan** [comment]
@mtosi , will a new PR on relval matrix pertaining this workflow be done in the future in conjunction with this PR? I could not find any existing test result on the gen fragment.

**Comment by AdrianoDee** [comment]
> @mtosi , will a new PR on relval matrix pertaining this workflow be done in the future in conjunction with this PR? I could not find any existing test result on the gen fragment.

Hi @SiewYan, yes that's the idea. Shall we have this first in or you would prefer to have the matrix wf PR in parallel?

**Comment by SiewYan** [comment]
Hello @AdrianoDee , I am fine to have this in for now. Please mention this PR in the upcoming PR on relval matrix. Thanks!

@Saptaparna , @GurpreetSinghChahal, @menglu21 can sign this shortly (also the backport), if they are fine with it.

**Comment by Saptaparna** [comment]
+1

**Comment by perrotta** [comment]
Just to be sure: this fragment is identical to the one in XiMinus_14TeV_SoftQCDInel_TuneCP5_cfi.py, with as only differences
  - The `MinPt` at 1.0 GeV instead of 1.3 GeV
  - The `crossSection` parameter commented out

 Is this intended?

The cms energy at 14 TeV is also intended for the validation of the  "rollback of the pixelles tracking to CKF"?

**Comment by AdrianoDee** [comment]
Indeed you are right. We would propose then to modify the existing fragment (see #38466 and #38467) closing this PR.

**Comment by perrotta** [comment]
hold
@cms-sw/generators-l2 @mtosi @AdrianoDee please decide the strategy and remain with only one PR, which is the agreed one

**Comment by SiewYan** [comment]
@AdrianoDee , pleas feel free to close this PR in favor of https://github.com/cms-sw/cmssw/pull/38466 and https://github.com/cms-sw/cmssw/pull/38467

**Comment by AdrianoDee** [comment]
@perrotta, @mtosi is on holiday this week. Could you close it for us?

**Comment by perrotta** [comment]
See https://github.com/cms-sw/cmssw/pull/38390#issuecomment-1163910114

**Pull request closed without merging**
