### PR TITLE
Hcal - QIEDelay in SIM

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:
Additional tech.method to perform time scan of the resulting simulated HBHE pulse shape (emulating real detector time scan by configurable delay in FE QIE chip) to adjust its parametrization eventually used for MAHI fit in Reconstruction. 

NB: not used by default.

study validation using this method: https://indico.cern.ch/event/936151/#110-mc-hbhe-signal-shape-time

### CODE REVIEW

**Comment by abdoulline** [comment]
@civanch   may I ask you to type:  please, test ?

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
We don't expect any changes, even for 5.1 or 25.0  in HF plots... To be understood.

**Comment by abdoulline** [comment]
@lwang046   
Long, old block of parameters (for old Run1 reco producers) may need to be updated for delayQIE as well...

 https://github.com/cms-sw/cmssw/blob/52d0edaf1e0be77efa151aa35ef01c67ca8ee2c9/SimCalorimetry/HcalSimAlgos/src/HcalSimParameters.cc#L12

**Comment by abdoulline** [comment]
@civanch   need your "please test" once again...

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
Looks OK to me now.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
