### PR TITLE
Generator Configs for relval rquest with 94X

### PR DESCRIPTION
**Pull request by boudoul**
Greetings,
this PR is meant to add two fragments in view of the MC requests from the tracker with the next pre-release (preparation of V2 MC) 
Possibly the relval machinery will be used for these special requests, therefore I prepared the fragments which would be needed in a release for the relval requests.

Note that the two fragments in questions  are 
1) QCD pt15 to 30 strictly the same as  used in the V1 MC campaign , 
https://cms-pdmv.cern.ch/mcm/requests?prepid=BTV-RunIISummer17GS-00005&page=0&shown=127
https://raw.githubusercontent.com/cms-sw/genproductions/85ccec18763776e0613830cde524bc7a4c77bc49/python/ThirteenTeV/QCD_Pt_15to30_TuneCUETP8M1_13TeV_pythia8_cff.py

2) Cosmic fragment,  strictly the same the one as used in the V1 MC campaign : 
https://cms-pdmv.cern.ch/mcm/requests?prepid=TRK-RunIISummer17CosmicGS-00001&page=0&shown=127
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/TRK-RunIISummer17CosmicGS-00001

### CODE REVIEW

**Comment by boudoul** [comment]
@franzoni, @GurpreetSinghChahal  @fabozzi , those are  the fragments  for the tracker MC requests  to prepare the V2 MC , thank you

**Comment by boudoul** [comment]
Note that once the MC requests will be over, I will be happy to remove them from future releases , since they won't be needed for regular relvals

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
just to check: it is intentional to use the tune CUEP8M1 and not CP5?

**Comment by davidlange6** [comment]
do any relvals use CP5? if that is meant as the default, make the relvals should be updated?

**Comment by fabozzi** [comment]
If we use McM to produce these samples (needed for Trk alignment studies) we will recycle GENSIM from MC v1 production. So I think @boudoul simply ported the gen fragment here

**Comment by perrozzi** [comment]
ok, the current cfg is fine for the purpose.
for the future yes we need to update all the RelVals to CP5 I guess, unless you have other opinions

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Pull request closed without merging**
