### PR TITLE
CTPPS: Diamond mapping 2017 reviewed

### PR DESCRIPTION
**Pull request by nminafra**
This pull request fixes the mapping for the Diamond Timing detectors for the run 2017.
It replaces and fixes (inversion of planes 0,1 with 2,3) the previous file and it is valid for all 2017 data.
This mapping has been checked using the strip detectors.

### CODE REVIEW

**Comment by slava77** [comment]
On 7/27/17 3:37 AM, Nicola Minafra wrote:
> This pull request fixes the mapping for the Diamond Timing detectors for
> the run 2017.
> It replaces and fixes (inversion of planes 0,1 with 2,3) the previous
> file and it is valid for all 2017 data.
> This mapping has been checked using the strip detectors.
> 

Is it normal that it take so long to notice a problem?

**Comment by slava77** [comment]
@cmsbuild please test workflow 136.77,136.78

**Comment by nminafra** [comment]
@slava77 We are commissioning the detector and those bugs in mapping/connections are not easy to spot since they depends on the analog part of our detector.
To check this mapping we had to use the tracks from strips and pixels and transport the protons to the diamonds. 
Moreover, we spotted the inversion of the planes some time ago, but to avoid an explosion of PR, we waited for a confirmation of all the channels.
Just consider that the same people who are commissioning the software were busy commissioning the hardware.

**Comment by slava77** [comment]
On 7/27/17 7:14 AM, Nicola Minafra wrote:

Thank you for the explanation of the timeline.
I was not asking as a complaint, just trying to understand what it takes
and if some tools are missing or if there are some other problems on the
way.

> Moreover, we spotted the inversion of the planes some time ago, but to
> avoid an explosion of PR, we waited for a confirmation of all the channels.

IMO, it makes sense to submit significant bugfixes as early as possible.
(you'd be able to make it to the release 927 earlier this week)

**Comment by nminafra** [comment]
@slava77 Of course, no problem!
Now the hardware is working properly; we still need to optimize a couple of parameters on the hardware that might require minor software corrections, but we are confident that now unpacker and mapping are fine.

**Comment by arunhep** [comment]
+1
no changes in comparisons as expected. 
nothing much to review as the changes are in xml file.

**Comment by ggovi** [comment]
+1

**Comment by forthommel** [comment]
Perfect! thanks @ggovi!
Now, waiting for @davidlange6's input :)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
