### PR TITLE
Regenerate DQMServices/Core/src/ROOTFilePB.proto

### PR DESCRIPTION
**Pull request by davidlt**
We are moving to Protocol Buffers 2.6.1 from 2.4.1. New version does not
have any issues compiling with GCC 6.0.0 (r233941). In addition to that
2.4.1 is a 5 year old release. Remember that Protocol Buffers provide
forward and backward compatibility for written data.

How files were regenerated?

```
cd $CMSSW_BASE/src
protoc --cpp_out=. DQMServices/Core/src/ROOTFilePB.proto
```

Signed-off-by: David Abdurachmanov David.Abdurachmanov@cern.ch

### CODE REVIEW

**Comment by davidlt** [comment]
Local compile tests were fine, but just in case triggered Jenkins tests before merging.

**Comment by smuzaffar** [comment]
please test

**Comment by davidlt** [comment]
Actually it's wrong to test it against any current IB, because protobuf is updated only starting to 2300. Merging.

**Comment by smuzaffar** [comment]
so protobuf cmsdist changes are already merged for 23h00?

**Comment by davidlt** [comment]
Yeah, again tested locally after building.

**Pull request merged**
