### PR TITLE
Backport of PR #11213 (making space for storing "method 3" energy in HBHERecHit)

### PR DESCRIPTION
**Pull request by igv4321**
Backport of PR #11213 to 7_5_X

### CODE REVIEW

**Comment by slava77** [comment]
@igv4321 please use a more verbose subject for the PR (e.g. "Preparing to include Method 3 result into HBHERecHit (backport of #11213)"

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
https://github.com/cms-sw/cmssw/pull/11214#issuecomment-139044536
""
@igv4321 please use a more verbose subject for the PR (e.g. "Preparing to include Method 3 result into HBHERecHit (backport of #11213)"
""
Thank you.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11214	9cae790
- the same changes were applied here as in 76X PR
- new code is not used anywhere yet; the change in the HCAL hit data format should be transparent in 75X with respect to other already generated samples (addition of a member)
- jenkins tests pass and comparisons with baseline show no differences, as expected

**Comment by abdoulline** [comment]
May we get it merged for Igor to proceed with making Method 3 permanently running (as Method 0 does) ?

**Comment by davidlange6** [comment]
@igv4321 @abdoulline - please add a description in the PR name for the release notes. Thanks

**Comment by igv4321** [comment]
Done

**Comment by davidlange6** [comment]
Hi - I'm cleaning up the 75x CMSSW release queue, so closing issues not directly related to analysis or finalizing the HI MC production. Please make sure these requests are included in the 80x release already. Thanks!

**Pull request closed without merging**
