### PR TITLE
[14_0_X] Introduce edm::Async service, and use it in CUDA and Alpaka modules

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/44901. Tests done by @fwyzard in https://github.com/cms-sw/cmssw/pull/44901#issuecomment-2098988869 showed this way of synchronizing host and NVIDIA GPU would improve HLT throughput by about 1.5 % ± 0.3 %.

#### PR validation:

None beyond https://github.com/cms-sw/cmssw/pull/44901

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/44901

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The test failure is
```
===== Test "testTFVisibleDevicesCUDA" ====
Running .WARNING:tensorflow:From /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02840/el8_amd64_gcc12/external/py3-cmsml/0.1.2-db4c88fc7ceb7db3b81affeb6fe4685e/lib/python3.9/site-packages/cmsml/tensorflow/tools.py:120: convert_variables_to_constants (from tensorflow.python.framework.convert_to_constants) is deprecated and will be removed in a future version.
Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.
WARNING:tensorflow:From /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02840/el8_amd64_gcc12/external/py3-tensorflow/2.12.0-b4ed11643f470f05efabc5bddd5c6e30/lib/python3.9/site-packages/tensorflow/python/framework/convert_to_constants.py:952: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This API was designed for TensorFlow v1. See https://www.tensorflow.org/guide/migrate for instructions on how to migrate your code to TensorFlow v2.

46.0

CUDA service enabled: 1
Testing CUDA backend
2024-06-05 19:45:18.727320: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-05 19:45:18.741973: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
0 /job:localhost/replica:0/task:0/device:CPU:0 type: CPU
Available devices: 1
F

testVisibleDevicesCUDA.cc:83:Assertion
Test name: testVisibleDevicesCUDA::test
assertion failed
- Expression: response.size() == 2

Failures !!!
Run: 1   Failure total: 1   Failures: 1   Errors: 0

---> test testTFVisibleDevicesCUDA had ERRORS
```

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/44375 not being merged (whereas its 14_1_X counterpart https://github.com/cms-sw/cmssw/pull/44376 is in `master`) looks related.

**Comment by fwyzard** [comment]
please test with #44375

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@smuzaffar could you sign this backport ?
he 14.1.x PR has been merged a couple of weeks ago.

**Comment by Dr15Jones** [comment]
+1

seems to have all the changes to the PR done in 14_1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
