### PR TITLE
Adapting EGM nano to use it for training energy regression

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

Adapting EGM nano to use it for training energy regression. This includes:
- Lowering electron & photon Et threshold from 5 GeV to 1 GeV (standard nano not affected)
- Adding photon supercluster phi variable

Furthermore, the photon seed cluster variables are cleaned up to be in a consistent fashion with electrons

#### PR validation:

Tested by generating EGM nano privately:
`cmsDriver.py --python_filename egmNano_default_TTree_cfg.py --eventcontent NANOAODSIM --customise Configuration/DataProcessing/Utils.addMonitoring --datatier NANOAODSIM --fileout file:egmNano_TTree_after.root --conditions 130X_mcRun3_2023_realistic_v14 --step NANO:@EGM --scenario pp --filein root://cms-xrd-global.cern.ch//store/mc/Run3Summer23MiniAODv4/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/MINIAODSIM/130X_mcRun3_2023_realistic_v14-v1/2550000/0809841c-f011-4fbb-a0a4-97cc88da1133.root --era Run3_2023 --no_exec --mc -n -1`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not meant to be backported, but if we have #45703 is backported then it'd be nice to have this backported as well.

### CODE REVIEW

**Comment by SanghyunKo** [comment]
FYI @RSalvatico

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
