### PR TITLE
Use new primary vertex filter in hotline and high MET skim (75X)

### PR DESCRIPTION
**Pull request by duanders**
Backport of https://github.com/cms-sw/cmssw/pull/11060 to 75X

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mariadalfonso** [comment]
@srimanob @mmusich please have a look at this PR. 
The equivalent 74 is already fully signed #11220, 
would like to have this asap in the 3.8 T runs

**Comment by mmusich** [comment]
+1 
backport of #11220

**Comment by davidlange6** [comment]
not needed for 75x

**Pull request closed without merging**
