### PR TITLE
Validation RecoEgamma Extended eta monitoring V2

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

This PR is an extension of the previous (37909) with some new histos.
Per request of the EGM conveners, the eta range of a few histograms have been extended from [-2.5, 2.5] to [-3.0, 3.0] to monitor the improvement of electrons reco efficiency in the high eta region for Run 3. These electrons are currently not monitored in the standard release validation of electrons. But it would be necessary to monitor it, in particular in 12_4_0_pre4 and later, because EGM is working in improving the energy correction and ID for the eta-extended electrons.
Therefore, new plots have been introduced to monitor electrons in 2.5<|eta|<3  without affecting the rest of the plots.

list of the 18 added histograms (1) :
h_mc_Eta_Extended_matched
h_scl_EoEtrue_endcaps_new_Extended
h_scl_EoEtrueVsrecOfflineVertices_Extended_pfx
h_scl_bcl_EtotoEtrue_Extended
h_ele_PoPtrueVsEta_Extended_pfx
h_ele_dEtaSc_propVtx_Extended
h_ele_dPhiSc_propVtx_Extended
h_ele_EoPVsEta_Extended_pfx
h_ele_HoE_Extended
h_scl_full5x5_sigietaieta_Extended
h_mc_foundHitsVsEta_Extended_pfx
h_ele_fbrem_Extended
h_ele_provenance_Extended
h_ele_chargedHadronRelativeIso_Extended
h_ele_neutralHadronRelativeIso_Extended
h_ele_photonRelativeIso_Extended
h_ele_absetaEff_Extended
h_ele_etaEff_Extended

One can see/compare those new histos on https://cms-egamma.web.cern.ch/validation/Electrons/Dev/index.php?action=/12_4_0_pre4_2022_DQM_dev/FullvsFull_CMSSW_12_4_0_pre4_eta=4-v09/RECO-RECO_ZEE_14# by taking Extend into the Filter and press Enter

To compensate for the new histograms, we removed some others which are not useful any longer. (Subdetector-based isolation with a cone size that is no longer the default)
tkSumPt_dr04 + barrel & endcaps
ecalRecHitSumEt_dr04  barrel & endcaps
hcalTowerSumEt_dr04_depth1 + barrel & endcaps
hcalTowerSumEt_dr04_depth2 + barrel & endcaps
hcalTowerSumEtBc_dr04_depth1 + barrel & endcaps
hcalTowerSumEtBc_dr04_depth2 + barrel & endcaps
i.e. 18 histograms.

Modifications are made on the following files :
Validation/RecoEgamma/plugins/ElectronMcSignalPostValidator.cc
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.h
Validation/RecoEgamma/test/ElectronMcSignalHistos.txt

Some other small modifications are made on :
Validation/RecoEgamma/test/ElectronMcSignalHistos.txt which is the new list of histos.
Validation/RecoEgamma/test/ElectronMcSignalPostValidationMiniAOD_cfg.py
Validation/RecoEgamma/test/ElectronMcSignalPostValidationPt1000_cfg.py
Validation/RecoEgamma/test/ElectronMcSignalPostValidation_cfg.py
Validation/RecoEgamma/test/ElectronMcFakePostValidation_cfg.py
All "_cfg" files are modified in order to have a more readable "DQM" file name.

(1) the h_mc_Eta_Extended_matched & the h_ele_EoPVsEta_Extended_pfx have been added into the previous PR.

Final but important remarks:
1) a bug in the h_mc_Eta_Extended_matched histo (from the previous PR) has been fixed
2) the following 6 histograms which are function of eta:
h_mc_Eta_matche
h_ele_EoPVsEta_pfx
h_ele_PoPtrueVsEta_pfx
h_ele_foundHitsVsEta_pfx
h_ele_absetaEff
h_ele_etaEff
are present twice (once with the above names, once with "extended" added).
This is in order not to break the upcoming validations. Once the eta-"extended" version of these histograms is present in the default validation, an other PR will be made to remove the "normal" version of these plots. 

#### PR validation:

scram build code-checks → OK
scram build code-format → OK

compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine (49 48 46 35 18 4 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed).
here is the run-log : [runall-report-step123-.log](https://github.com/cms-sw/cmssw/files/8870409/runall-report-step123-.log)

will be backported to 12_4_X

@beaudett @swagata87

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type feature

**Comment by swagata87** [comment]
type egamma

**Comment by emanueleusai** [comment]
@archiron I see some differences seen in the DQM bin-by-bin comparison: http://tinyurl.com/29h4tge5
I can track one difference to the bugfix in h_mc_Eta_Extended_matched. However there are some more diffs related to the extension from 2.5 to 3 in plots in function of eta (e.g. h_ele_seedDphi2_VsEta_pfx and h_ele_seedDrz2_VsEta_pfx). So for these eta-dependent plots you did not add the "extended" version to prevent validation break?
Can you just confirm this is what you wanted to do?

**Comment by archiron** [comment]
I made small modifications to correct the 2 histograms (h_ele_seedDphi2_VsEta_pfx and h_ele_seedDrz2_VsEta_pfx) which are not concerned with the "Extended" modifications.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
@archiron @emanueleusai : the differences in the FastSim workflows visible in the tests are related to the fix to `mc_Eta_Extended_matched`?

**Comment by beaudett** [comment]
Hi @perrotta 
@archiron will correct me if I am wrong, but I think that it is thanks to those plots that he found a bug for which he updated the PR. Is that correct Arnaud ?

**Comment by archiron** [comment]
yes.

**Comment by perrotta** [comment]
+1
- The modifications that show up in the FastSim EGamma DQM plots are [confirmed](https://github.com/cms-sw/cmssw/pull/38569#issuecomment-1181930713) to be an effect of the bug fix to them: 
image

**Pull request merged**
