### PR TITLE
Add electron supercluster eta to NanoAOD content

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

Among the current NanoAOD variables we have the electron eta and the difference (with sign) between the supercluster eta and eta. Since people often want/need to access supercluster eta, I find it an unnecessary complication to have to derive it from `deltaEtaSC` and `eta`. Therefore, I propose to add the actual `superclusterEta`, which is already there for photons. Since `superclusterEta` was also there in the additional table used for EGMNano, I have removed it from there. For the moment, I would keep `deltaEtaSC` just so that people using 2024 prompt nanos won't have to make uncomfortable adjustments to their code to pick another variable in the middle of the dataset.

#### PR validation:

The new variable, `superclusterEta`, now appears in the standard Nano files and behaves as expected.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

If possible, I would like to have it backported to 140X to make it effective in prompt and in the 2024 MC production.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1
I think backport is not an option now

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
