### PR TITLE
Run2-alca134 Backport PR #23343 to reduce o/p rate

### PR DESCRIPTION
**Pull request by bsunanda**
Saves AlCaReco disk space

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
@fabiocos please consider this as well for next 10.1.X release.
this will help in reducing the size of corresponding AlCaRECO by 45% : https://indico.cern.ch/event/727168/contributions/3014708/subcontributions/256011/attachments/1657078/2653157/IsoTrigger06.pdf (slide 9)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
