### PR TITLE
bsunanda:Run2-hcx68 Add xml files for BH (HGCal)

### PR DESCRIPTION
**Pull request by bsunanda**
These xml files define the BH part of the PhaseII high granularity calorimeter

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna The changes to Run2 or PhaseI version are not critical

**Comment by ianna** [comment]
@bsunanda - I think, we've just missed 800 release, but a GT can be updated in due time

**Comment by bsunanda** [comment]
@ianna Could you review and sign this?

**Comment by ianna** [comment]
+1

**Pull request closed without merging**
