### PR TITLE
Update final Run3 MC geometry

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR update the MC Run3 GTs to include the final geometry:
 - BRIL geometry updated to match actual P5 detectors
 - GEM and RPC demonstrator modules are added

For more details see: https://cms-talk.web.cern.ch/t/gt-mc-small-run-3-geometry-revision-for-12-3-0-pre4/4930

The added DD4HEP tags are:
`XMLFILE_Geometry_123DD4hepV1_Extended2021_mc`, label `Extended`
`XMLFILE_Geometry_123DD4hepV1_Extended2021ZeroMaterial_mc`, label `ZeroMaterial`
`XMLFILE_Geometry_123DD4hepV1_Extended2021FlatMinus05Percent_mc`, label `FlatMinus05Percent`
`XMLFILE_Geometry_123DD4hepV1_Extended2021FlatMinus10Percent_mc`, label `FlatMinus10Percent`
`XMLFILE_Geometry_123DD4hepV1_Extended2021FlatPlus05Percent_mc`, label `FlatPlus05Percent`
`XMLFILE_Geometry_123DD4hepV1_Extended2021FlatPlus10Percent_mc`, label `FlatPlus10Percent`
`GEMRECO_Geometry_123DD4hepV1`
`RPCRECO_Geometry_123DD4hepV1`

At the same time the following DDD tags are updated as well in the `autoCondDDD` modifier:
`XMLFILE_Geometry_123YV1_Extended2021_mc`
`GEMRECO_Geometry_123YV1`
`RPCRECO_Geometry_123YV1`

The difference in the GTs is:
**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v3/123X_mcRun3_2021_design_v4

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v3/123X_mcRun3_2021_realistic_v4

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v3/123X_mcRun3_2021cosmics_realistic_deco_v4

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v3/123X_mcRun3_2021_realistic_HI_v4

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v3/123X_mcRun3_2023_realistic_v4

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v3/123X_mcRun3_2024_realistic_v4

#### PR validation:
Validated with
`runTheMatrix.py -l 12034.0,11634.0,7.23,312.0,12434.0,12834.0,11634.911,11634.914 --ibeos -j 15`

#### Backport
Not a backport. Will be backported to 12_2_X if everything goes fine with validation in 12_3_0_pre4.

### CODE REVIEW

**Comment by francescobrivio** [comment]
FYI @cms-sw/geometry-l2

**Comment by francescobrivio** [comment]
test parameters:
 - workflows=12034.0,7.23,12834.0,11634.911,11634.914

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@francescobrivio For testing, PRs #36654 and #36679 must be included. They are not merged yet.

**Comment by francescobrivio** [comment]
@cmsbuild please abort

**Comment by francescobrivio** [comment]
@cmsbuild please test with #36654,#36679

**Comment by qliphy** [comment]
urgent
for 12_3_0_pre4

**Comment by qliphy** [comment]
@francescobrivio   FYI, I add here the comment in the email thread from @srimanob

"The same question I have here,
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4517/1.html
, for this update,
Should the data tag,
GEMRECO_Geometry_123DD4hepV1
RPCRECO_Geometry_123DD4hepV1
goes to data GT as well?"

**Comment by francescobrivio** [comment]
> ----- Begin Fatal Exception 21-Jan-2022 00:16:13 CET-----------------------
> An exception of category 'NoRecord' occurred while
>    [0] Processing global begin Run run: 1
>    [1] Prefetching for module OscarMTProducer/'g4SimHits'
>    [2] Prefetching for EventSetup module MuonOffsetESProducer/'muonOffsetESProducer'
>    [3] Calling method for EventSetup module XMLIdealGeometryESProducer/'XMLFromDBSource'
>    [4] While getting dependent Record from Record IdealGeometryRecord
> Exception Message:
> No "GeometryFileRcd" record found in the EventSetup.
> 
>  The Record is delivered by an ESSource or ESProducer but there is no valid IOV for the synchronization value.
>  Please check 
>    a) if the synchronization value is reasonable and report to the hypernews if it is not.
>    b) else check that all ESSources have been properly configured. 
> ----- End Fatal Exception -------------------------------------------------

This error only appears when I test with  #36654 and #36679.
Otherwise the wf finishes successfully.
@cvuosalo @bsunanda any suggestion?

**Comment by francescobrivio** [comment]
> @francescobrivio FYI, I add here the comment in the email thread from @srimanob
> 
> "The same question I have here, https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4517/1.html , for this update, Should the data tag, GEMRECO_Geometry_123DD4hepV1 RPCRECO_Geometry_123DD4hepV1 goes to data GT as well?"

@qliphy @srimanob quoting from private conversation with Carl:
"Initially, only the MC GT needs to be updated. After the revision is
validated, then propagating to the offline and online GTs could be
contemplated."

**Comment by francescobrivio** [comment]
> This error only appears when I test with #36654 and #36679. Otherwise the wf finishes successfully. @cvuosalo @bsunanda any suggestion?


OK I think I found the issue: I set the wrong timestamp in the DDD modifier.
I'm testing the fix and will push in few minutes.

**Comment by dpiparo** [comment]
Thanks francesco!

**Comment by francescobrivio** [comment]
@cmsbuild please test with #36654,#36679

**Comment by francescobrivio** [comment]
@cmsbuild please abort

something went wrong in the last commit

**Comment by francescobrivio** [comment]
I will close this PR and open a clean new one since I pulled in some unwanted commits while testing locally.

**Comment by francescobrivio** [comment]
-1

 - see https://github.com/cms-sw/cmssw/pull/36764#issuecomment-1018302532

**Pull request closed without merging**
