### PR TITLE
Protection in HistoryBase cycle against unfulfilled condition

### PR DESCRIPTION
**Pull request by ghost**
Correct original HistoryBase code. No protection was present in case of unfulfilled condition within loop.
Backport of https://github.com/cms-sw/cmssw/pull/14905

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by imarches** [comment]
Hi all, the failures are not related to the PR

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
