### PR TITLE
Pixel Heterogeneous DQM: add module rechit @cpu / @gpu comparisons [backport to 12.3.X]

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:

Backport of #37860 

#### PR validation:

Will need PR #37971 to compile.

### CODE REVIEW

**Comment by sroychow** [comment]
code-checks with #37971

**Comment by sroychow** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503, 11634.506, 11634.583, 11634.587
- workflow = 11634.501
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by sroychow** [comment]
enable gpu

**Comment by sroychow** [comment]
please test with #37971

**Comment by sroychow** [comment]
backport of #37860

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
urgent 
   * should be included in the next 12.3.X release, for HLT monitoring purposes.

**Comment by perrotta** [comment]
+1
- Succesfully merged in master since CMSSW_12_5_X_2022-05-20-1100

**Pull request merged**
