### PR TITLE
76X relvals update

### PR DESCRIPTION
**Pull request by srimanob**
(1) Add DisplacedSUSY workflow
(2) Remove obsolete fastsim pu workflows

### CODE REVIEW

**Comment by srimanob** [comment]
please test

**Comment by franzoni** [comment]
Origin of the problem is eos -  not providing this dataset for pileiup overlay, despite it's present at CERN:
https://cmsweb.cern.ch/das/request?input=site%20dataset%3D/RelValMinBias_13/CMSSW_7_5_0_pre4-MCRUN2_75_V1-v1/GEN-SIM&instance=prod/global&idx=0&limit=10

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
which is to say the das query failed ( our most common problem by far)

**Comment by srimanob** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
