### PR TITLE
 BeamSpotOnline in DQM beamspot clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR introduces changes in the DQM code related to BeamSpot.
- The BeamSpot fit results are now also stored in a `BeamSpotOnlineObjects` (introduced in #29662 ) and saved in a payload using the service `cond::service::OnlineDBOutputService`.
- The ` DQM/BeamMonitor/python/*py` configuration files are updated to include the default value of the BeamSpot Online record name for the upload to CondDB.
- Both beamspot python clients `DQM/Integration/python/clients/beam*_dqm_sourceclient-live_cfg.py` are updated to handle the upload of the payload to the database always using `OnlineDBOutputService`
- No changes in the actual fitting of the beamspot are introduced.
- Nothing is removed/deleted from the `BeamMonitor.cc` plugin, only the changes described above are added

There are two still open questions for which I might need help from DQM and DB experts:
1. **For DQM experts:**
Is it ok to have `options = VarParsing.VarParsing()` under `DQM/Integration/python/clients`? I only see usage of this in `DQM/Integration/python/config`, so I was wondering if it is correct or it might cause problems. The options are needed to properly setup the `OnlineDBOutputService`.

2. **For DB experts:**
I'm not sure how to properly configure these lines in `OnlineDBOutputService`:
  - `authenticationPath`
  - `lastLumiFile`
  - `connect` and `preLoadConnectionString`

#### Backporting:
Once this PR is completed and merged, it will need a backport to CMSSW_11_1

### CODE REVIEW

**Comment by francescobrivio** [comment]
Let me tag @ggovi as well, since I worked with him on the preparation of this PR and he might be interested (and he may be able to answer some of the questions).

**Comment by jfernan2** [comment]
@francescobrivio May ask you to add yourself along with your git-username in the comments to the corresponding DQM/Validation e-group in: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts
for future reference? Thanks

**Comment by ggovi** [comment]
@francescobrivio 
authenticationPath,lastLumiFile,connect and preLoadConnectionString params will be set according to the deployment needs. For this PR, I would suggest to leave authenticationPath and lastLumiFile  empty ( string '' ) .

**Comment by francescobrivio** [comment]
> preLoadConnectionString

Ok I will put an empty string in authenticationPath and lastLumiFile.
What about connect and preLoadConnectionString? Are they ok like they are now?

**Comment by francescobrivio** [comment]
> @francescobrivio May ask you to add yourself along with your git-username in the comments to the corresponding DQM/Validation e-group in:
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts
> for future reference? Thanks

I subscribed to Tracker-Online DQM Developer(s). If I understand correctly the twiki is auto-generated and should be updated once my subscription is approved.

**Comment by mmusich** [comment]
> I subscribed to Tracker-Online DQM Developer(s). If I understand correctly the twiki is auto-generated and should be updated once my subscription is approved.

BeamSpot is more a responsibility of Tracking than Tracker, but do to lack of an "online tracking" set of developers, I guess that's fine. This somehow highlights the fact that the DQM developer table does not consider many grey area cases (such as this one, where a DQM package is just a place where really an AlCa/DB operation happens).

**Comment by jfernan2** [comment]
> 
> 
> > @francescobrivio May ask you to add yourself along with your git-username in the comments to the corresponding DQM/Validation e-group in:
> > https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts
> > for future reference? Thanks
> 
> I subscribed to Tracker-Online DQM Developer(s). If I understand correctly the twiki is auto-generated and should be updated once my subscription is approved.

Thanks @francescobrivio Your understanding is correct

**Comment by jfernan2** [comment]
About "Is it ok to have options = VarParsing.VarParsing() under DQM/Integration/python/clients? " 
 It is fine if it works, but we don't know if ORP has some objection

**Comment by jfernan2** [comment]
please test

**Comment by francescobrivio** [comment]
> About "Is it ok to have options = VarParsing.VarParsing() under DQM/Integration/python/clients? "
> It is fine if it works, but we don't know if ORP has some objection, however those clients are run in Online DQM so there should be no problem

Indeed I tested it locally and it works fine. My concern is that locally I run it with the command:
`cmsRun clients/beam_dqm_sourceclient-live_cfg.py runNumber=319579`
so I manually provide the run number.
I'm not sure what happens once this goes "live"?

**Comment by francescobrivio** [comment]
> I found follow errors while testing this PR
> 
> **Failed tests: UnitTests**
> 
>     * **Unit Tests**:
> 
> 
> I found errors in the following unit tests:
> 
> ---> test TestDQMOnlineClient-beam_dqm_sourceclient had ERRORS

About this error: looking at the **Unit tests** log it seems that the error comes from the options.parseArguments(): I'm not sure if the program is trying (and failing) to parse the "unitTest=True" option or if some other python error is going on...

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
> +1

@jfernan2 can you please clarify for my own education how this question from Francesco (https://github.com/cms-sw/cmssw/pull/30448#issuecomment-651203384) is going to be addressed in operations?

> Indeed I tested it locally and it works fine. My concern is that locally I run it with the command:
cmsRun clients/beam_dqm_sourceclient-live_cfg.py runNumber=319579
so I manually provide the run number.
I'm not sure what happens once this goes "live"?

**Comment by jfernan2** [comment]
In operations the run number (and other options) are extracted from some file name by HLTD and it get's passed through multiple levels of indirection until it ends up in cmsRun command as runNumber argument. Hence in live mode, this input is taken by all DQM clients:
https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/inputsource_cfi.py#L12

However, we have tested this PR as it is now at P5 DQM playback and indeed it crashes because runInputDir and runkey are missing in the beamspot client, while they are defined in *inputsource_cfi.py

So, @francescobrivio I am sorry but I have to regret my +1
I will give you now instructions on how to update the PR in order to work at P5, in a separate comment. The same applies to the backport of this PR #30503

**Comment by jfernan2** [comment]
-1

**Comment by francescobrivio** [comment]
> So, @francescobrivio I am sorry but I have to regret my +1
> I will give you now instructions on how to update the PR in order to work at P5, in a separate comment. The same applies to the backport of this PR #30503

I understand. 
If you have instructions to update this PR I'll be glad to apply them (and to the backport of course).

**Comment by jfernan2** [comment]
@francescobrivio 

- unitTest can be taken from  sys.argv like this beam client was doing up to now:
https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py#L23

- runNumber is already declared in *inputsource_cfi.py so you can take options.runNumber  either unitTest is True
https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/unittestinputsource_cfi.py#L27

or False:
https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/inputsource_cfi.py#L12

- transDelay is a new variable, so you should add it to both files above, with a default sensible value. If you need to modify it in live mode, we need to find out how to pass it in operation, I understand this value should not change much for given year, but please advice in this matter.

transDelay should also be added to:
https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/fileinputsource_cfi.py
if it is planned to be used with dedicated files in an offline manual mode.

Thank you very much in advance.

**Comment by jfernan2** [comment]
@francescobrivio  at Online Playback we also get this error:

----- Begin Fatal Exception 03-Jul-2020 16:07:45 CEST-----------------------
An exception of category 'ConditionDatabase' occurred while
[0] Constructing the EventProcessor
[1] Constructing service of type OnlineDBOutputService
Exception Message:
Required Key File "/tmp/.cms_cond/db.key" is missing or unreadable. from DecodingKey::init
----- End Fatal Exception -------------------------------------------------

Any clue if something else is needed for OnlineDBOutputService? Thanks

**Comment by francescobrivio** [comment]
> @francescobrivio at Online Playback we also get this error:
> 
> ----- Begin Fatal Exception 03-Jul-2020 16:07:45 CEST-----------------------
> An exception of category 'ConditionDatabase' occurred while
> [0] Constructing the EventProcessor
> [1] Constructing service of type OnlineDBOutputService
> Exception Message:
> Required Key File "/tmp/.cms_cond/db.key" is missing or unreadable. from DecodingKey::init
> ----- End Fatal Exception -------------------------------------------------
> 
> Any clue if something else is needed for OnlineDBOutputService? Thanks

About this probably @ggovi is best suited to answer, I just copied his implementation from [this example](https://github.com/cms-sw/cmssw/blob/master/CondCore/DBOutputService/test/python/testLumiBasedUpdateAnalyzer_cfg.py).

**Comment by francescobrivio** [comment]
> @francescobrivio
> 
>     * unitTest can be taken from  sys.argv like this beam client was doing up to now:
>       https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py#L23
> 
>     * runNumber is already declared in *inputsource_cfi.py so you can take options.runNumber  either unitTest is True
>       https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/unittestinputsource_cfi.py#L27
> 
> 
> or False:
> 
> https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/inputsource_cfi.py#L12
> 
>     * transDelay is a new variable, so you should add it to both files above, with a default sensible value. If you need to modify it in live mode, we need to find out how to pass it in operation, I understand this value should not change much for given year, but please advice in this matter.
> 
> 
> transDelay should also be added to:
> https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/fileinputsource_cfi.py
> if it is planned to be used with dedicated files in an offline manual mode.
> 
> Thank you very much in advance.

Thanks for the suggestion, I'll try to implement them!

**Comment by francescobrivio** [comment]
Dear @jfernan2 
I tried what you suggest here:

>     * runNumber is already declared in *inputsource_cfi.py so you can take options.runNumber  either unitTest is True
>       https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/unittestinputsource_cfi.py#L27
> 
> 
> or False:
> 
> https://github.com/cms-sw/cmssw/blob/587de05fef8162133dcb899ba4e3bf4ffff0140b/DQM/Integration/python/config/inputsource_cfi.py#L12

but the options that are registered in those two files are only available there.
Do you know how can I access them from the "main" beamspot client (clients/beam_dqm_sourceclient-live_cfg.py)?

**Comment by jfernan2** [comment]
Sorry @francescobrivio  it seems you must first do:

from DQM.Integration.config.inputsource_cfi import options
or
from DQM.Integration.config.unitinputsource_cfi import options

depending on the unitTest value

**Comment by francescobrivio** [comment]
@jfernan2 the last commit (https://github.com/cms-sw/cmssw/pull/30448/commits/49dddb7e3f9827b7f91599c83afba31d6f0e37c6) should fix all the issues related to `options` reported in this comment https://github.com/cms-sw/cmssw/pull/30448#issuecomment-653505786 (thanks for the suggestion btw).
I'm still working on the issue reported in https://github.com/cms-sw/cmssw/pull/30448#issuecomment-653569423

**Comment by francescobrivio** [comment]
After discussion with @ggovi and @gennai I added an option to handle the upload of the BeamSpot conditions to the DB:
- By default the client only creates the (local) .db file
  - the BS fit result is anyway also stored in a txt file so the run2-like workflow is preserved
- The upload to the DB is performed **only if** the option `noDB=False` is passed from command line

@jfernan2 this should now also work in the P5 playback, could you test it?

**Comment by jfernan2** [comment]
@francescobrivio  we tested it in Online and it works fine

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
