### PR TITLE
 include dark current contribution in M2 pedestal constraint for Phase2 [93X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #20422

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20423	5051416
- the same commit and topic branch as the master version in #20422 ; affects only phase-2 in line with the description
- jenkins tests pass: comparisons show differences only in the phase-2 workflows

**Comment by davidlange6** [comment]
+1

**Pull request merged**
