### PR TITLE
retune max value for Chi2

### PR DESCRIPTION
**Pull request by fioriNTU**
To avoid fake alarms for shifters, the chi2 distribution is very sensitive to PU and running conditions, the quality of this distributions is to be checked comparing with a suitable reference

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
forward port https://github.com/cms-sw/cmssw/pull/14531
(please cross-reference if you are submitting multiple PR for the same feature)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
