### PR TITLE
correct missing commas in dflt initializations for ghostTrack in IPProducer

### PR DESCRIPTION
**Pull request by slava77**
This is a follow up to https://github.com/cms-sw/cmssw/issues/26913#issuecomment-497027588

@ferencek

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
as expected, in a few cases the ghostTrack tag infos moved from -2 to 0.
E.g. in Run2018A EGamma wf 136.85

all_OldVSNew_RunEGamma2018Awf136p85c_recoCandidateedmPtrsrecoJetTagInforecoIPTagInfos_pfImpactParameterTagInfos__reRECO_obj_m_data_distanceToGhostTrack_value

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27000	de52341
- differences observed in the jenkins tests are as expected: in some rare cases where the defaults are not reset the values are now at 0 instead of -2

**Comment by fabiocos** [comment]
@slava77 this looks a genuine bug fix that I assume we would like to port to 10_6_X, am I correct?

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
> @slava77 this looks a genuine bug fix that I assume we would like to port to 10_6_X, am I correct?

I do not really see a reason for a backport.
From https://github.com/cms-sw/cmssw/issues/26913#issuecomment-496877602
> The ghost track feature is not really in active use which probably explains why this went unnoticed all this time.

**Comment by fabiocos** [comment]
@slava77 ok, in this case I agree, although strictly speaking it remains a bug

**Pull request merged**
