### PR TITLE
Add more context to exception message in externalGenerator

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Add what the program was doing when the exception happened.
- Make it easier to spot exception message in the log

#### PR validation:

Code compiles and unit tests show the new information.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
NOTE: in the IBs we are getting infrequent failures of the externalGenerator where BOOST is throwing an exception with a  not-so-informative message (i.e. just a generic `library error`). I'm hoping having our side print more info might help track down what is actually happening.

**Comment by Dr15Jones** [comment]
please test

**Comment by SiewYan** [comment]
Unit test does show new information[*].

[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5ed0e8/24545/unitTests/src/GeneratorInterface/Core/test/FailingGeneratorFilterTest/testing.log

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
