### PR TITLE
Adding 2017 LHE-based relvals (93X)

### PR DESCRIPTION
**Pull request by fabozzi**
Adding 2017 versions (noPU and PU) of the LHE-based workflows.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
please test with workflow 1361.17

**Comment by davidlange6** [comment]
please test workflow 1361.17

**Comment by davidlange6** [comment]
+1

**Pull request merged**
