### PR TITLE
GEM online DQM bug fix - full GE1/1

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR fixes a bug on the part of onlineDQM for GEM. The previous version uses `endRun` to draw summary plots, which is not a good idea in online DQM. This new version moves it to `dqmEndLuminosityBlock`.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
@quark2  I guess the same applies here:
there are Clang warnings to fix:
DQM/GEM/plugins/GEMDQMHarvester.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2020-02-17-1100/src/DQM/GEM/plugins/GEMDQMHarvester.cc:31:8: warning: 'dqmEndLuminosityBlock' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

**Comment by quark2** [comment]
Hi @jfernan2, 

I added the missed keyword and tested also into this PR. Thanks!

Best regards, 
Byeonghak Ko

**Comment by andrius-k** [comment]
please test

**Comment by silviodonato** [comment]
@andrius-k @jfernan2 @kmaeshima @fioriNTU @schneiml
can we merge this bug fix?

**Comment by quark2** [comment]
Hi @silviodonato, 

Unfortunately, it's not. We've found an issue related to the last crash and empty plots and now I'm dealing with it. After fixing and getting a result, I'll show it.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
hold
Waiting for fix from GEM

**Comment by quark2** [comment]
Sorry for late fix. This new one is for fix of the percentage issue and the crash-by-geometry issue.

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
Hi @silviodonato I would hold this PR and its backport for the moment until GEM is being introduced into AlCa Geometry DB. The PR only introduces a temporary fix for Online DQM which is not going to be used for the moment given the cancellation of the March MWGR
Thanks

**Comment by quark2** [comment]
I've returned to the stand configuration, using `Configuration.StandardSequences.GeometryRecoDB_cff`. @hyunyong has found the essential reason of the geometry issue and it's about to be fixed so that the standard configuration will be available soon.

**Comment by jfernan2** [comment]
> I've returned to the stand configuration, using `Configuration.StandardSequences.GeometryRecoDB_cff`. @hyunyong has found the essential reason of the geometry issue and it's about to be fixed so that the standard configuration will be available soon.

Thank you @quark2 
Please let us know when the GT is ready to test this at P5

**Comment by quark2** [comment]
Hi @jfernan2, 

Sure, I'll inform that.

Best regards, 
Byeonghak Ko

**Comment by silviodonato** [comment]
Kind reminder to @hyunyong

**Comment by hyunyong** [comment]
Hi @silviodonato,
We have done a test with the candidate GT and it seems working fine.
We don't have the new data GT yet, but AlCaDB is working on that.
@quark2 or I will inform when the new GT is available.

**Comment by quark2** [comment]
Hi all, 

New GTs with GEM geometry has been presented: 

110X_dataRun3_HLT_GEMRecoGEO_v1
111X_dataRun3_HLT_GEMRecoGEO_v1

They are tested in local and everything works well. Could you guys make a playback with them?

Best regards, 
Byeonghak Ko

**Comment by silviodonato** [comment]
@quark2 what does prevent this PR from being merged?

> Hi all,
> 
> New GTs with GEM geometry has been presented:
> 
> 110X_dataRun3_HLT_GEMRecoGEO_v1
> 111X_dataRun3_HLT_GEMRecoGEO_v1
> 
> They are tested in local and everything works well. Could you guys make a playback with them?
> 
> Best regards,
> Byeonghak Ko

**Comment by silviodonato** [comment]
please test

**Comment by jfernan2** [comment]
+dqm
This PR involves DQM Online changes ONLY. Despite this PR has not actually been tested in Online DQM at P5 given the shutdown, I believ it makes sense to propagate the change to master. 
This PR and its backport https://github.com/cms-sw/cmssw/pull/28977 have been put on the queue of changes to the P5 DQM Online system once it comes back to live:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by silviodonato** [comment]
@jfernan2 you are still keeping this PR in hold

**Comment by jfernan2** [comment]
unhold
Sorry

**Comment by silviodonato** [comment]
+1

**Pull request merged**
