### PR TITLE
python 2to3 migration tool fixes.fix_dict

### PR DESCRIPTION
**Pull request by davidlange6**
apply fixes.fix_dict tool from python futurize tool

### CODE REVIEW

**Comment by Dr15Jones** [comment]
How much does this affect our python memory and timing usage? Effectively in python2.7 we are changing an access to an iterator to creating an entire copy of the `items` or `keys` of the dictionary.

**Comment by kpedro88** [comment]
@Dr15Jones I was wondering the same...

**Comment by davidlange6** [comment]
I think I know how to check it - I didn't check yet. I'll try to.

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
-1
I would rather see introduced a uniform syntax with consistent behaviour in python 2 and 3, than changing the behaviour of python 2.

**Comment by davidlange6** [comment]
I'd propose we ue six.iteritems then. It means a migration later, but that would be true regardless..

**Comment by davidlange6** [comment]
even more interesting - this breaks the relval tests - will pursue this one by hand.

**Pull request closed without merging**
