### PR TITLE
Changed set to vector in PFDisplacedVertexSeed

### PR DESCRIPTION
**Pull request by Dr15Jones**
A vector should reduce memory and most likely speed up the use of PFDisplacedVertexSeed.

Added unit tests for the code I touched.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I happen to have noticed this while trying to understand the IB failures using gcc 8. The use of the set bothered me so I changed it to a vector to improve its memory and CPU efficiency.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
As best as I can see from looking at the RECO comparisons, the extremely slight differences (usually just a shifting of an entry from one histogram bin to a neighboring bin) could be explained by slight precision shifts in the values.

**Comment by perrotta** [comment]
Hi @Dr15Jones : a set is ordered according to its element keys, while a vector is not. As a consequence, the order in which ```elements_``` are accessed differs now, and with some debug I could verify that in a few cases also the ```displacedVertex```'s get a different order with this PR wrt the baseline.

Still, it is not obvious to me how do those different orders can be responsible of the tiny changes that you notice in a few reco comparisons. Do you have an idea about how this can happen?

You talk about some different precision, which could indeed be responsible of the tiny changes observed: where such a different precision is implemented in this PR?

**Comment by slava77** [comment]
On 6/15/18 2:12 AM, perrotta wrote:
> Hi @Dr15Jones <https://github.com/Dr15Jones> : a set is ordered
> according to its element keys, while a vector is not. As a consequence,
> the order in which |elements_| are accessed differs now, and with some
> debug I could verify that in a few cases also the |displacedVertex|'s
> get a different order with this PR wrt the baseline.
> 
> Still, it is not obvious to me how do those different orders can be
> responsible of the tiny changes that you notice in a few reco
> comparisons. Do you have an idea about how this can happen?
> 
> You talk about some different precision, which could indeed be
> responsible of the tiny changes observed: where such a different
> precision is implemented in this PR?
> 

due to roundoffs, results of operations made on the same values in a
different order can be different.

Is a change of order actually meaningful? There should be no code that
assumes ordering

**Comment by Dr15Jones** [comment]
@slava77 @perrotta is there still debate going on about the minor change of values?

**Comment by perrotta** [comment]
@Dr15Jones : well, I was waiting that you pointed out to me where there is such a variable saved in a different precision in your code (if this was what you meant  by "slight precision shifts in the values")

On the other hand, we agrees that the change of order of few of the displacedVertex's (due to the change of order of the elements_ of the Set vs Vector) could be deemed responsible of the tiny shifts seen in the outputs. And, by looking at the code I don't think that the order that was originally decided for the ``` std::set <...>  elements_``` had any other meaning rather than help in avoiding double counting (as it was mentioned in the comment in https://github.com/cms-sw/cmssw/pull/23546/files#diff-6903ba4b1023e45802608d40feee031aL36) 

Therefore, if you have no objections, I could consider me ready to sign this off for reco

**Comment by Dr15Jones** [comment]
@perrotta When I was saying 'slight precision shifts in the values' I just meant that if the code was doing math operations (say additions) based on the order of the items in the set, then changing the order can make slight changes to the values at the smallest precision scale. I had not meant to imply some change to saved values. Sorry for the confusion. 

Yes, please go ahead and sign off.

**Comment by perrotta** [comment]
+1
- Technical update
- Due to the different order in which the seeds are stored some tiny difference can be propagated to the reco outputs, as it is visible in some of the jenkins tests outputs

**Comment by fabiocos** [comment]
+1

**Pull request merged**
