### PR TITLE
L1 online DQM histograms for uGMT intermediate muons

### PR DESCRIPTION
**Pull request by thomreis**
In 2017 the L1 uGMT starts to send intermediate muons from between its two sorter stages to the DAQ.

This PR adds intermediate muon DQM histograms coming from data and emulator to the online DQM under the L1T2016 and L1T2016EMU directories, respectively.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @thomreis @rekovic - do we already have these histograms in DQM/L1TMonitor/src/L1TStage2MuonComp.cc?

**Comment by thomreis** [comment]
Hi @davidlange6
L1TStage2MuonComp takes two input collections (For example unpacked muons and emulated muons) and compares them. It only fills the histograms with muons that do not exist in both collections. L1TStage2uGMTMuon takes just one collection of muons and fills the histograms. It can be used with any L1 Muon collection but its use case here is the uGMT intermediate muons.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
