### PR TITLE
Phase2-hgx182 Change in ETL due to change in HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
The recent drawing of endcap region restricts a total thickness of 77 mm for ETL starting from 2986 mm. There will be no longer esalgo.xml in the definition of the scenario. The current one is copied to etl/v1

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
attn: @fabiocos @pmeridian @lgray

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda what is the purpose of v1/etl.xml?

**Comment by bsunanda** [comment]
@kpedro88 I think later etl.xml in data directory should disappear. I think ideally etl geometry should have been organized with v1, v2, ....

**Comment by kpedro88** [comment]
+upgrade
ETL geometry files will be reorganized subsequently

**Comment by bsunanda** [comment]
@fabiocos Could you please approve and merge this PR at the earliest? Without this one cannot define a scenario with new HGCal geometry with MTD?

**Comment by fabiocos** [comment]
@bsunanda @kpedro88 I agree that if the mother volume is still not stable it needs some versioning, on the other had I think everything here is evolving so we just need to adapt. etl.xml and etl/v1/etl.xml coincide, so old scenarios could transparently be adapted to this trivial adjustment, removing the top level etl.xml, without violating any sacred rule (one just needs to verify that all instantiations are properly adjusted)

**Comment by fabiocos** [comment]
+1

to support further developments, this PR in itself changes nothing in the existing geometries

**Pull request merged**
