### PR TITLE
[LLVM Analyzer][L1] Cleanup LLVM analyzer warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

See [report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-10-13-0000/el8_amd64_gcc12/llvm-analysis/index.html)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
