### PR TITLE
Updates on GE21 online/offlineDQM plots with division on modules

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:

This PR provides massive updates on GE21 onlineDQM/offlineDQM plots. This work is focusing on the division of GE21 information by modules (M1-M4). It is necessary because of the electronic configuration of GE21 chambers.

It is also included that the module information is propagated to the GEM unpacker in a better way, which is done by @yeckang.

#### PR validation:

Tests are done with `cmsRun $CMSSW_RELEASE_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True runNumber=361054 dataset=/ExpressPhysics/Run2022F-Express-v1/FEVT` and `runTheMatrix.py -l limited -i all --ibeos` since it makes effects on P5 and reconstruction

@jshlee @watson-ij @seungjin-yang @yeckang

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- plenty of changes in GEM/Digis and GEM/RecHits DQM plots, as expected

**Comment by emanueleusai** [comment]
you can proceed with the backports if you need this online

**Comment by civanch** [comment]
+1

**Comment by clacaputo** [comment]
> you can proceed with the backports if you need this online

As for #39489 , this PR touches data format and can't be integrated into a closed release such as 124X and 125X

**Comment by emanueleusai** [comment]
@clacaputo thank you for the reminder. We (DQM) can deploy off-release PRs to our online systems. So if the authors want to see the new plots in online DQM we need backports to 12_4 (for online pp collisions) and 12_5 (for HI collisions). This makes is easy for us to merge the PRs with the official releases (only!) in our P5 machines, test the backports and properly keep tabs on the PRs installed.
We do not ask the backports to be merged in GitHub, instead we put the PRs on hold indefinitely. This has been done in the past for others GEM PRs.

**Comment by quark2** [comment]
Hi, @emanueleusai, 

You mean, if the backport PRs to 124X and 125X are fine, then they could be deployed to P5 without merge, right?

**Comment by emanueleusai** [comment]
@quark2 from the point of view of DQM, yes we can do that

**Comment by clacaputo** [comment]
+reconstruction

**Comment by srimanob** [comment]
@cmsbuild please test

Just re-trigger the test after a week.

**Comment by srimanob** [comment]
+Upgrade

From upgrade related package, the update on header files and classes_def are mininal.

**Comment by perrotta** [comment]
+1

**Comment by syuvivida** [comment]
Hello,
sorry we would like to check if this PR went into any later 12_6_X release. This PR is merged to the master branch on November 26 but somehow it is not yet in 12_6_2. Thanks!!

**Pull request merged**
