### PR TITLE
Fix N-dimensional strided loops and extend the alpaka tests

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement an N-dimensional vector add test with alpaka and `cms::alpakatools` utilities.
Refactor the checks for accelerators that support multiple threads per block (_e.g._ GPUs) or a single thread with multiple elements (_e.g._ serial CPUs), and use the new constant to simplify the workdiv generation and the strided loops.

#### PR validation:

The new unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
This PR continue the work done in #40580, adding more tests for N-dimensional loops.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
