### PR TITLE
HiGenCommon consumes migration and GenHIEventProducer forward port from 75X

### PR DESCRIPTION
**Pull request by mandrenguyen**
80X version of #14719

### CODE REVIEW

**Comment by covarell** [comment]
Do we foresee MC production for HI in 80X? If not, we do not need this and the 81X version is sufficient

**Comment by mandrenguyen** [comment]
If there is no issue with starting a GEN-SIM campaign in 81X in the near future, then indeed there is no reason that I know of to have this in 80X.

**Comment by davidlange6** [comment]
81x won’t be an option for production for a while. 80x sounds like the right release for HI MC prod in the near future if we need to upgrade from 75x for the mixing.

**Comment by covarell** [comment]
Ok if we are talking abot near future, indeed we need this in 80X

**Comment by mandrenguyen** [comment]
@covarell @govoni If there's nothing problematic here, can you please sign?

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
