### PR TITLE
HLT menu development for `14_0_X` (4/N) 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44415

#### PR description:

Development of HLT menus for CMSSW_14_0_X (branch CMSSW_14_1_X).
  * This is the PR for 14_0_X: this is the release cycle currently used for Run-3 HLT-menu development.
  
This version of the GRun HLT menu corresponds to final list of updates to the "V1.0" menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3092](https://its.cern.ch/jira/browse/CMSHLT-3092) [TSG] Completion of the offline "Special" table and lists of paths for individual special menus [14_0_X]
- [CMSHLT-3099](https://its.cern.ch/jira/browse/CMSHLT-3099) [BPH] Include L1 seed to Dimuon low pt Jpsi trigger
- [CMSHLT-3101](https://its.cern.ch/jira/browse/CMSHLT-3101) [Scouting] Storage of raw `AK4PFJets` in Scouting
- [CMSHLT-3103](https://its.cern.ch/jira/browse/CMSHLT-3103) [TSG] Undo GRun changes due to CMSHLT-2860 (`MinimumBias` PD, smart-PS of `HLT_ZeroBias` in `EventDisplay`)
- [CMSHLT-3104](https://its.cern.ch/jira/browse/CMSHLT-3104) [BTV] Migration of `MC_PFBTag` to `ParticleNet`
- [CMSHLT-3109](https://its.cern.ch/jira/browse/CMSHLT-3109) [ECAL/PF] Integrate `Alpaka` version of ECAL local reco and `PFRecHit`+`PFCluster` reco of `HBHE RecHits`

In addition, the following changes are included:
   * https://github.com/cms-sw/cmssw/commit/9dc11dc177bde898003f469f824b6c4e5fe779ed robustify `test_OnlineVsDevTablesConsistency`
   *  https://github.com/cms-sw/cmssw/commit/1f63ab2386088c37a457d52fe8991e171805a7b0 add `Special` subtable to `DEV` / `dev` `cmsDriver` tests
   * https://github.com/cms-sw/cmssw/commit/d907983b623b0a5b64da5deef19b12621f125db2 Introduce `2024v1.0` frozen menu and remove `2023v1.2` and related test machinery.
   * https://github.com/cms-sw/cmssw/commit/15e3f3ed06ced89a1ee1f8b75f55931ad891f849 update `readme` in `HLTrigger/Configuration/scripts/utils` to CMSSW_14_0_0

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/44415 to the 2024 production cycle (CMSSW_14_0_X)

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * changes in [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-15-1100+5b4a0f/61687/triggerResults): found differences in 7 / 47 workflows look compatible with the path versioning bump (due to the creation of the new online menu) and the updates in the GRun table from https://its.cern.ch/jira/browse/CMSHLT-3103.

**Comment by antoniovilela** [comment]
+1
   - HLT dump.

**Comment by mmusich** [comment]
type hlt-integration

**Pull request merged**
