### PR TITLE
Various improvements and small fixes of the MET uncertainty tools 76X

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #10240 for 76X

### CODE REVIEW

**Comment by monttj** [comment]
please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by monttj** [comment]
please test

**Comment by mmarionncern** [comment]
@cmsbuild branch has been rebased

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by monttj** [comment]
+1
approved already for 75X

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
