### PR TITLE
[13_0_X] Update skim config for 2023 data taking and skim wf 

### PR DESCRIPTION
**Pull request by youyingli**
Backport of  #42107 and #42229

### CODE REVIEW

**Comment by youyingli** [comment]
@sunilUIET, please test

**Comment by sunilUIET** [comment]
please test

**Comment by youyingli** [comment]
@sunilUIET , could you please retrigger again as the timeout problem happens? Thanks!

**Comment by sunilUIET** [comment]
please test

**Comment by youyingli** [comment]
Hi @sunilUIET , @srimanob, please sign it if no other consideration. The backport to 13_1_X will be made after #42226 is merged.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
@youyingli please take note of https://github.com/cms-sw/cmssw/pull/42229#issuecomment-1634814582 : perhaps, before backporting anothes PR with another fix should be merged in master?

In any case, a backport for the intermediate 13_1_X cycle should be prepared also

**Comment by youyingli** [comment]
> @youyingli please take note of [#42229 (comment)](https://github.com/cms-sw/cmssw/pull/42229#issuecomment-1634814582) : perhaps, before backporting anothes PR with another fix should be merged in master?
> 
> In any case, a backport for the intermediate 13_1_X cycle should be prepared also

Yes, I will take care of this issue and create new PRs to master,  13_1_X and 13_0_X. Could you please consider merging this PR in order to be included in the next CMSSW release and produce the new skim dataset for 2023 data taking?

**Comment by perrotta** [comment]
> Yes, I will take care of this issue and create new PRs to master, 13_1_X and 13_0_X. Could you please consider merging this PR in order to be included in the next CMSSW release and produce the new skim dataset for 2023 data taking?

We do not foresee building a new 13_0_X release in the next few days: please go ahead with integrating the fix a preparing the 13_1_X backport

**Comment by rappoccio** [comment]
+1

**Pull request merged**
