### PR TITLE
fix for ECAL selective readout

### PR DESCRIPTION
**Pull request by franzoni**
This PR deploys the fix to ECAL selective readout already introduced in the lat ocmmit of the 90x https://github.com/cms-sw/cmssw/pull/17886

# Summary of changes in Global Tags

## Upgrade

   * **PhaseII realistic scenario** : [90X_upgrade2023_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v9) as [90X_upgrade2023_realistic_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2023_realistic_v9/90X_upgrade2023_realistic_v8):
      * ECAL: 2017 selective readout (fix) https://indico.cern.ch/event/615692/contributions/2484421/

   * **PhaseI 2017 cosmics peak scenario** : [90X_upgrade2017cosmics_realistic_peak_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v18) as [90X_upgrade2017cosmics_realistic_peak_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v18/90X_upgrade2017cosmics_realistic_peak_v17):
      * ECAL: 2017 selective readout (*fix*) - https://indico.cern.ch/event/615692/contributions/2484421/

   * **PhaseI 2017 cosmics scenario** : [90X_upgrade2017cosmics_realistic_deco_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v17) as [90X_upgrade2017cosmics_realistic_deco_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v16) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v17/90X_upgrade2017cosmics_realistic_deco_v16):
      * ECAL: 2017 selective readout (*fix*) - https://indico.cern.ch/event/615692/contributions/2484421/

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v19) as [90X_upgrade2017_realistic_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v19/90X_upgrade2017_realistic_v18):
      * ECAL: 2017 selective readout (*fix*) - https://indico.cern.ch/event/615692/contributions/2484421/

   * **PhaseI 2018 cosmics scenario** : [90X_upgrade2018cosmics_realistic_deco_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v16) as [90X_upgrade2018cosmics_realistic_deco_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v16/90X_upgrade2018cosmics_realistic_deco_v15):
      * ECAL: 2017 selective readout (*fix*) - https://indico.cern.ch/event/615692/contributions/2484421/

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v16) as [90X_upgrade2018_realistic_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v16/90X_upgrade2018_realistic_v15):
      * ECAL: 2017 selective readout (*fix*) - https://indico.cern.ch/event/615692/contributions/2484421/

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
the error looks unrelated to the GT change

**Comment by franzoni** [comment]
please test

**Comment by arunhep** [comment]
@franzoni still the same observation in ECAL plots. Change in occupancy in EB [1]
and no change in EE [2]

[1] : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-14-2300+17936/18798/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/EcalBarrel_EBOccupancyTask.html 

[2] : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-14-2300+17936/18798/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/EcalEndcap.html

**Comment by franzoni** [comment]
@cmkuo
@shervin86
@emanueledimarco

Ecal experts and the lack of impact in EE: may you please comment?
This condition change in this pr assesses only the difference between the C1-scenario-with-problem (provided two weeks ago)
To the tag you released yesterday with the fix.

Does the fix pertain only EB?

**Comment by amassiro** [comment]
The fix can have slightly different effects in EE and in EB due to different pulse shapes.
It will be explained in details tomorrow: https://indico.cern.ch/event/622160/

**Comment by franzoni** [comment]
Difference in EE occupancy are actually there.
The relmon comparisons ( as already explained here https://github.com/cms-sw/cmssw/pull/17886#issuecomment-286843055 ) show differences when a loose bin-to-bin comparison, and the EE differences don't fail the check on the pseudo-chi2 which flags them as "difference.
Below the change in occupancy for EB and EE, red is target (i.e. the GT 2017 realistic of this PR, TTbar), blue is the reference (i.e. the SR/ZS affected by the bug which this PR intends to fix).
91x-eb-occupancy
91x-ee

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
