### PR TITLE
memory reduction most visible for HI processing, done mostly by dropping muon isodeposits in HI (same as #12764)

### PR DESCRIPTION
**Pull request by slava77**
technical PR for pp purposes.

same as in 75X #12764: reducing memory allocations, mostly significant for the HI processing.
This PR is provided for continuity of features.
If we keep the gap, this PR can be closed.
There is a PR for 80X.

see notes in #12764

tested in CMSSW_7_6_3: the only observed changes are in plots made in  DQMOffline/JetMET/src/JetAnalyzer_HeavyIons_matching.cc  where the bug needed to be fixed to avoid crashes (the fix is also proposed with more features in #12194).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12765	e545d4b
- jenkins tests confirm that the only change is in HI jet plots where the bug fix was unavoidable

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
