### PR TITLE
[14_1_X] Add 2024 HiMix MC RelVal workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #45875

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 330,331,332

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
ping @cms-sw/upgrade-l2 
the master version is already merged.

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
