### PR TITLE
NanoAOD Update: trigger, nPV, pileup (10_0_X)

### PR DESCRIPTION
**Pull request by arizzi**
This includes:
 - tune of trigger objects
 - fix of trigger bits when version number changes
 - n goodPV
 - oot pileup

All changes are in PhysicsTools/NanoAOD

backport of #22037

@gpetruc

### CODE REVIEW

**Comment by gpetruc** [comment]
why this didn't trigger code checks?

**Comment by davidlange6** [comment]
its not a PR for the development branch

**Comment by arizzi** [comment]
this needs #21944  (already merged in 94X and 10_1_X)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
apparently the test was not including already #21944 . Anyway the IB including this PR was successful.

**Pull request merged**
