### PR TITLE
add collections for EXONoBPTXSkim (93X)

### PR DESCRIPTION
**Pull request by jalimena**
Add additional collections needed to redo muon timing, which is essential for EXO-17-004, which relies on this skim.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test 136.791

**Comment by fabozzi** [comment]
@kfjack

**Comment by fabozzi** [comment]
please test workflow 136.791

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
