### PR TITLE
Dictionary updated with BPH objects

### PR DESCRIPTION
**Pull request by ronchese**
the following objects have been added to the dictionary to be written
as UserData:
bool
edm::Ref< pat::CompositeCandidateCollection >
edm::Ref< std::vector< reco::Vertex > >
Vector3DBase< float, GlobalTag >

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
to get rid of the DAS error, hopefully

**Comment by monttj** [comment]
+1
This update is required from the PR, #15484

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15783 a53e30d
- new dictionaries are added as described
- jenkins tests pass

It looks like the last class name in the list during dictionary compilation can get garbled: ``` Selected class -> pat::UserHolder<edm::Ref<std:>>  Compiling  /build/cmsbuild/jenkins``` shows up in jenkins logs instead of the full name followed . The same build running locally in single thread shows the full type name for the selected class here and the following messages appear to be in some sensible order
```
Selected class -> pat::UserHolder<edm::Ref<std::vector<pat::CompositeCandidate, std::allocator<pat::CompositeCandidate> >, pat::CompositeCandidate, edm::refhelper::FindUsingAdvance<std::vector<pat::CompositeCandidate, std::allocator<pat::CompositeCandidate> >, pat::CompositeCandidate> > > for ROOT: pat::UserHolder<edm::Ref<vector<pat::CompositeCandidate>,pat::CompositeCandidate,edm::refhelper::FindUsingAdvance<vector<pat::CompositeCandidate>,pat::CompositeCandidate> > > 
>> Compiling LCG dictionary: tmp/slc6_amd64_gcc530/src/DataFormats/PatCandidates/src/DataFormatsPatCandidates/a/DataFormatsPatCandidates_x2r.cc
>> Building LCG reflex dict from header file src/DataFormats/PatCandidates/src/classes_trigger.h
...
```
@Dr15Jones @smuzaffar  Have you seen this happen before?

**Comment by Dr15Jones** [comment]
I don't recall ever seeing that

**Comment by davidlange6** [comment]
+1

**Pull request merged**
