### PR TITLE
update photon path names in SMP HLT DQM config

### PR DESCRIPTION
**Pull request by olivito**
Updating the photon path names in the SMP HLT DQM config, to correspond to changes in this JIRA ticket:
https://its.cern.ch/jira/browse/CMSHLT-230

### CODE REVIEW

**Comment by degano** [comment]
@ktf @davidlange6 we merged the PR creating this new package here: https://github.com/cms-sw/cmssw/pull/6170 but we never assigned it to any category. Which category should we assign it?

**Comment by degano** [comment]
@cmsbuild please test

**Comment by ktf** [comment]
HLT I guess.

@fwyzard @Martin-Grunewald

**Comment by fwyzard** [comment]
I think technically this should be signed by DQM, like the other packages under HLTriggerOffline .

**Comment by ktf** [comment]
Ah, right. No objections on my side. But then why not putting all of them under "DQM"?
@deguio

**Comment by ktf** [comment]
I mean "DQM" the folder.

**Comment by fwyzard** [comment]
Boh ?

There are different packages and folders for Online DQM vs. Offline DQM vs.
Release validation.

They could certainly all go under DQM, if anyone cares enough  to move
them...

Ciao,
.Andrea

**Comment by deguio** [comment]
ciao,
the HLTriggerOffline folder is there for historical reasons only. It is under the DQM responsibility, please assign it to us.

why the "new-package-pending" label is triggered?

ciao,
F.

**Comment by deguio** [comment]
I see, it wasn't assigned the first time the folder has been created.
anyway.. assign to DQM please.

thanks,
F.

**Comment by ktf** [comment]
@degano can you please add the new package to DQM? Thanks.

**Comment by deguio** [comment]
@degano 
not sure if this package was assigned to DQM in the end.
anyway +1 for us.

thanks,
F.

**Comment by degano** [comment]
Assigned to dqm in https://github.com/cms-sw/cms-bot/pull/302.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
