### PR TITLE
Revert "Revert "Move L1Trigger/CSCTrackFinder/src/core_ files to external package""

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmssw#13974

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar - was there a reason you didn't merge this? (I'm happy to, but confused by your message)

**Comment by smuzaffar** [comment]
@davidlange6 , I wanted to merge it just before the 23h00 IB to minimize the chances of ib-any-integration jobs picking it up for PR testing (due to deleted headers in this PR, ib-any-integration job can fail).  But I was late to do so but will do it for 23h00 IB today

**Comment by davidlange6** [comment]
ok. Sounds good.

**Comment by smuzaffar** [comment]
I have added a temporary workaround in cms-bot to avoid the L1Trigger/CSCTrackFinder/src poison headers for PR tests. So we can safely merge it now

**Pull request merged**
