### PR TITLE
Run3-sim52 Try out all run3 + phase2 scenario in dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert all existing Run3 and Phase2 scenarios to dd4hep format and try to check them against failures

#### PR validation:

Use built in cfg files in Geometry/CMSCommonData/test/dd4hep

#### Links to additional material/slides/JIRA tickets/Pull requests:

Nothing special - no back porting is needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda @cvuosalo eventually we want to make sure the phase 2 geometry script ([generate2026Geometry.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/scripts/generate2026Geometry.py)) can output these dd4hep XML files directly, so that we can continue to ensure the consistency of the various phase 2 geometries.

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
