### PR TITLE
adding option to enable FastSim decayer functionality

### PR DESCRIPTION
**Pull request by sbein**
This PR creates an option to enable the FastSim decayer functionality, which was previously enabled without an option. The decayer has been found to have been responsible for considerable mismodeling in the missing ET, a known issue with a heavy-handed correction procedure developed by and adopted by the SUS PAG. The impact of the FastSim decayer on physics was recently studied and presented in the simulation meeting [1]. 

[1] https://indico.cern.ch/event/1182398/contributions/4967736/attachments/2480801/4258724/Sim15July2022_Decayer.pdf

Adopting the GEN decays has many advantages, including the guaranteed synchronization of decay modes btw the generator and simulation steps, the universal ability to allow for the decays of exotic particles without analyzing the family tree of every particle, and avoiding any unforeseen consequences of switching generators, e.g., from Pythia8 to Herwig. Most importantly, defaulting to the GEN decays was seen to improve the modeling of MET and other observables in FastSim significantly, while any bad impacts are for the most part minor [2][3]

The SUSY-derived FastSim MET correction may no longer be necessary, but it is up to PAGs to assess any treatment/uncertainties they think are appropriate for their analyses. It would also be advisable to backport this default behavior to the Run 2 UL release, CMSSW_10_6_X for any future campaigns. 

#### PR validation:

[ALT_0] is the new FastSim:
[2] https://www.desy.de/~beinsam/FastSim/Nano/6July2022/TTbar_12_2_XDev/index.html
[3] https://www.desy.de/~beinsam/FastSim/Nano/6July2022/T1tttt_12_2_XDev/index.html

### CODE REVIEW

**Comment by sbein** [comment]
please test

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
While I interpret the fastsim signature here as that all differences in the fastsim workflows are approved as a consequence of this change, I wonder what do these two workflows, listed under "Workflows with reco comparison differences", correspond to
all_OldVSNew_TTbarFS13in2018RECOwf2018p1
all_OldVSNew_TTbarFS13in2018MINIAODwf2018p1

I imagine that the final field in the name, that should correspond to the workflow number (here 2018.1 for both), got somehow screwed up: @slava77 do you have any idea why?

**Comment by slava77** [comment]
> correspond to all_OldVSNew_TTbarFS13in2018RECOwf2018p1 all_OldVSNew_TTbarFS13in2018MINIAODwf2018p1
> 
> I imagine that the final field in the name, that should correspond to the workflow number (here 2018.1 for both), got somehow screwed up: @slava77 do you have any idea why?

I'm not sure what is the question. 
AOD/RECO and miniAOD files are processed separately and go to separate foldets. In this workflow, unlike in many regular pp workflows the RECO and PAT steps are in separate steps. So, the pattern of the output folder names is different.

**Comment by perrotta** [comment]
> > correspond to all_OldVSNew_TTbarFS13in2018RECOwf2018p1 all_OldVSNew_TTbarFS13in2018MINIAODwf2018p1
> > I imagine that the final field in the name, that should correspond to the workflow number (here 2018.1 for both), got somehow screwed up: @slava77 do you have any idea why?
> 
> I'm not sure what is the question. AOD/RECO and miniAOD files are processed separately and go to separate foldets. In this workflow, unlike in many regular pp workflows the RECO and PAT steps are in separate steps. So, the pattern of the output folder names is different.

Sorry, Slava: I did not realize that "2018.1" was exactly the number of the workflow: I imagined that the year instead was slipped somehow int the report name. Sorry for the noise, then

**Comment by perrotta** [comment]
+1
- Differences wrt the baseline are quite relevant, as expected.
- Let profit of next 12_5_X pre-release to have it more extensively validated

**Pull request merged**
