### PR TITLE
[13.0.X] Fixed channel decoding for the timeout error in SiPixel RawToDigi

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #42010 

#### PR validation:
code compiles

### CODE REVIEW

**Comment by sroychow** [comment]
type bug-fix

**Comment by sroychow** [comment]
urgent
- address issue #41715 
- further [comment](https://github.com/cms-sw/cmssw/pull/42010#issuecomment-1600473752)

**Comment by sroychow** [comment]
test parameters:
- enable_tests = gpu
- workflows_gpu = 10824.507
- relvals_opt= -w upgrade
- relvals_opt_gpu = -w upgrade

**Comment by sroychow** [comment]
please test

**Comment by malbouis** [comment]
should the tests be re-triggered?

**Comment by mmusich** [comment]
please test

**Comment by malbouis** [comment]
@sroychow , would you please confirm that the differences are as expected, also in the master PR: https://github.com/cms-sw/cmssw/pull/42010#issuecomment-1601671765
If we would like to have it for data-taking in the new Run2023D Era, this PR should be merged and a new release cut very soon.
@saumyaphor4252 , FYI as ORM.
Thanks!

**Comment by sroychow** [comment]
@malbouis @jordan-martins After some checks, and also discussing with @mmusich, we think the differences in the GPU comparisons are spurious. If you look at even older PRs (which were merged before), e.g. 42014 or before, you should see some differences pointed out by the bot in the GPU comparisons. I would propose we can merge this PR.

**Comment by malbouis** [comment]
Thanks, @sroychow ! Indeed, it would be good to have this PR merged and a new release cut with this in.
@rappoccio , @perrotta , do you think we could move ahead?

**Comment by mandrenguyen** [comment]
Apologies, but can someone reiterate why we would like to put this bug-fix directly into reconstruction without proper release validation?
I've read the comment from PPD here:
https://github.com/cms-sw/cmssw/pull/42010#issuecomment-1600473752

But according to HLT, this PR will only affect the fallback mode when no GPU is available. 
The motivation to modify the offline reconstruction without full validation is not completely clear to me.
I understand it's a bug-fix, but any change to reco risks to introduce further bugs that we may not be able to spot immediately.

**Comment by missirol** [comment]
> But according to HLT, this PR will only affect the fallback mode when no GPU is available.

Small clarification (already mentioned at the last ORP): the CPU unpacker also runs at HLT for the fraction of events used for GPU-vs-CPU comparisons.

**Comment by mmusich** [comment]
> but I'm not actually sure that the CPU pixel unpacker runs as part of that trigge

This statement is in square contradiction with the whole of https://github.com/cms-sw/cmssw/issues/41715 .
If the pixel legacy unpacker is never run there is no issue to talk about. Please clarify.

**Comment by missirol** [comment]
(I edited my comment above about the GPU-vs-CPU comparisons, as already noticed)

> Do we have a number about the fraction of events that take this path?

I think this has happened very rarely. I think the number is `0` for 2023 collisions, and I could only remember one case where some nodes could not recognise their GPU during MWGR2 of 2023 ([run-363833](https://cmsoms.cern.ch/cms/triggers/hlt_trigger_rates?cms_run=363833&props.11284_11278.selectedCells=0:1&props.11281_11278.selectedCells=Status_OnCPU:2,Status_OnGPU:2)).

**Comment by jordan-martins** [comment]
Hi @mandrenguyen,

Yes, since it is a bug fix, we decided to get in asap for the start of ERA D. 

We do indeed want to perform some validation, and we have asked TRK to propose some approaches to assist PdmV with the best way to propose a quick validation that we could rely on. We wanted to get this in now because we only foresee a rereco of the initial chunk of the DATA from ERA A to C.

Do you think this is too risky? Could you propose a way around this to help us move in the safest way possible?

Thanks,
PPD

FYI @cms-sw/ppd-l2 @cms-sw/pdmv-l2

**Comment by mandrenguyen** [comment]
It would appear this is a long-standing bug in the unpacker, which has a very minor effect on the offline reconstruction, at least judging by the comparisons.
We can validate this bug-fix by the usual procedure, integrating it into the master release, and eventually backporting. 
This procedure can be accelerated, but if we cannot meet the deadline for ERA D, I think I'm not properly understanding the negative consequences. 
The prompt reco will be consistent across all eras with a minor bug (that is already present in all of our published papers?) that will be fixed for an eventual reprocessing.
The HLT will essentially be unaffected, since we are not using CPU at HLT.

I understand that there is some CPU-GPU validation that we would like to converge, but do we really want to risk breaking reco to fix validation? Especially since we heard this is only a partial fix, and there are at least more changes coming on the GPU side.   The risk of directly implementing this bug-fix is admittedly small, but the consequences could be quite bad.  I suppose we should be able to fix the validation using the fixed CPU code without actually deploying the fix in prompt reco for Era D.

**Comment by mmusich** [comment]
> The HLT will essentially be unaffected, since we are not using CPU at HLT.

> The goal is to make sure the two reconstructions give the same results, since (in general) GPU is the default online, while CPU is the fallback online and is used in most offline use cases (e.g. MC).

So it validates a use case than never happens (in practice). Now that this is clarified I guess it also settles the urgency for a fix (and for all future fix requests of this type as well).

> It would appear this is a long-standing bug in the unpacker, which has a very minor effect on the offline reconstruction, at least judging by the comparisons.

The effect is minor when the detector is well-behaved. I am under the impression the effect becomes more sizeable in presence of large rates of soft error recoveries.

**Comment by fwyzard** [comment]
The bugfix should definitely be backported and included in the online reconstruction ASAP.

RECO conveners may have a cavalier approach towards the integrity of the data taking, but DAQ and TSG (should) consider the stability and correctness of the online reconstruction and data taking of paramount importance.

**Comment by mmusich** [comment]
Mostly to clarify to myself

> but I'm not sure it runs as part of the DQMGPUvsCPU stream (pixel tracking on CPU does, but I'm not sure about pixel unpacking on CPU).

In case one of the legacy unpacker event products would be persisted for being outputed in the event stram as we're planning in https://its.cern.ch/jira/browse/CMSHLT-2846 I would think it will start to be run as well.

**Comment by mandrenguyen** [comment]
Does something prevent us from using an era  or process modifier such that:
- We can delay the deployment of the new pixel unpacker code offline until it's validated
- GPUvsCPU validation can be conducted with the modified code
- HLT can deploy the modified code in the unlikely event that it's executed

?

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42010

**Comment by clacaputo** [comment]
+reconstruction

- differences expected, see https://github.com/cms-sw/cmssw/pull/42033#issuecomment-1604355259

**Comment by perrotta** [comment]
+1
- As it was agreed at the joint operation meeting of June 26: this may enter a passible new release on top of the already built 13_0_8

**Comment by fwyzard** [comment]
> Does something prevent us from using an era or process modifier such that:
> 
>     * We can delay the deployment of the new pixel unpacker code offline until it's validated
> 
>     * GPUvsCPU validation can be conducted with the modified code
> 
>     * HLT can deploy the modified code in the unlikely event that it's executed
> 
> 
> ?

@mandrenguyen that's an interesting approach, but looking at the changes, I do not think it can be done: an era or process modifier can affect only the python configuration, while this bug fix is a c++ change.

**Pull request merged**
