### PR TITLE
[94X] more Strip conditions supported by Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
Added more Payload Inspector classes for 4 SiStrip `CondFormats`:
   * `SiStripLorentzAngle`
   * `SiStripBackPlaneCorrections`
   * `SiStripNoises`
   * `SiStripPedestals`

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
The last commit (rebased on top of `CMSSW_9_4_X_2017-09-28-2300`) removes some unused code that was triggering the static analyzer, another couple of comparison plots are also added.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
