### PR TITLE
[MkFit] Format change for windows in json files

### PR DESCRIPTION
**Pull request by leonardogiannini**
#### PR description:

This PR enables having different values for hit selection windows in the backward and forward propagation.

It should be tested with using the new jsons: https://github.com/cms-data/RecoTracker-MkFit/pull/12

At this stage this is a purely technical PR, but new windows will be derived separately for layers where hits can be picked up both in the backward and forward propagation.

#### PR validation:

no differences are found in the MTV validation, as expected

http://uaf-10.t2.ucsd.edu/~legianni/TechnicalPRNewWindows/plots-new-windows/

** minimal differences are expected when mkFit is used for HLT (not a default configuration)
see note https://github.com/cms-sw/cmssw/pull/40679#issuecomment-1419273999

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 5 differences found in the comparisons

there are no relevant difference, as expected.

Hopefully the review/merge can be quick.

**Comment by mandrenguyen** [comment]
@cmsbuild please test
Looks ok, but let's see if a retest fixes the input error

**Comment by mandrenguyen** [comment]
+reconstruction
No effect on comparisons, as expected from PR descriptions.
Code changes look reasonable.

**Comment by perrotta** [comment]
@leonardogiannini @slava77 could you please comment about the differences in the tests on HLT tracking in wf 11634.7, i.e. TTbar_14TeV+2021_trackingMkFit?

**Comment by slava77** [comment]
> @leonardogiannini @slava77 could you please comment about the differences in the tests on HLT tracking in wf 11634.7, i.e. TTbar_14TeV+2021_trackingMkFit?

apparently some track parameters have changed on the HLT side (considering that reco did not change)
The differences are very small https://tinyurl.com/2a7oqyvj  (all is green with KS prob of 0.999) .

11634.7 is running initialStep-like replacement in HLT iter0 .
Since mkFit is not used in production HLT and the differences are tiny, I'd rather take a note and move on.

**Comment by perrotta** [comment]
Just a couple of examples of those differences:
image
image

I think it could be worth to investigate quickly where do they come from: either some part of the HLT tracking is sensitive to these changes (and one has to verify where the sensitivity comes from), or it is another instance of the spurious  differences observed in outputs of wf 11634.7 as reported in the github issue https://github.com/cms-sw/cmssw/issues/39803

**Comment by slava77** [comment]
the differences are expected due to the change in the format of the files in the HLT context, which is maintained at mostly "be good enough", less precise/proper than the offline supported iterations.

the HLT setup is reusing the initialStep hit selection configuration. In the offline the initialStep is using quadruplet seeds, while the HLT includes triplets as well. The updated parameterization is now applied strictly to layers where tracking building is done (after the last seed layer). This means that one of the layers (most likely layer 4) in the triplet seeds of HLT will rely on a default window (different from before this PR).

**Comment by perrotta** [comment]
+1
- Thank you @slava77 for having made the check and provided the possible explanation of the differences observed in wf 11634.7

**Pull request merged**
