### PR TITLE
Use tbb::task_arena to keep SecondaryEventProvider on same thread

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Calls to syncWait can cause the callstack to migrate to another thread unless task_arena::execute is used.

#### PR validation:

Code compiles and workflow 250406.17 which had failed before now runs fine.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
hold

further testing (by removing the previous fix) seems to show this change doesn't actually work.

**Comment by Dr15Jones** [comment]
unhold

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
This is the proper fix for the problem. My original fix of the symptoms is still useful (since it anlso functions as a performance improvements) so I kept it in the code as well.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
