### PR TITLE
Remove workflow 1325.9 testing NanoAOD on 92X

### PR DESCRIPTION
**Pull request by peruzzim**
This PR removes testing workflow 1325.9 that tests NanoAOD on 9_2_X.
Running on this release is not supported anymore.

Addressing #25409.

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by peruzzim** [comment]
@slava77 we have the cleanup of the modifier in our TODO list, it will be done in the next NanoAOD update PR. We would avoid doing it in the current round of integration to avoid confusion.

I leave it to you to decide whether to defer merging this PR until then, depending on what the consequences on the validation workflow are.

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
> @slava77 we have the cleanup of the modifier in our TODO list, it will be done in the next NanoAOD update PR.

Thank you. Sounds like a good plan.

**Comment by slava77** [comment]
[reusing this thread]
@peruzzim @fgolf 
do we have all supported variants of nanoAOD have a corresponding matrix workflow?

**Comment by peruzzim** [comment]
@slava77 only one matrix workflow is missing (94X2016), we propose to fix it in the next round of NanoAOD update to avoid confusion, together with unit tests

**Comment by fabiocos** [comment]
@prebello @zhenhu is it ok for you?

**Comment by prebello** [comment]
+1

sure @fabiocos

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
> @slava77 we have the cleanup of the modifier in our TODO list, it will be done in the next NanoAOD update PR. We would avoid doing it in the current round of integration to avoid confusion.

It is nearly 5 months since that message.
the 92X modifier is still in the release
e.g. 
https://github.com/cms-sw/cmssw/blob/2e3e3823af73ee521584fc9888ee77ec5adbc8d1/PhysicsTools/NanoAOD/python/nano_cff.py#L95-L100

Did the plan to remove change?
@peruzzim please clarify.
Thank you.

**Comment by peruzzim** [comment]
was removed in the integration repository already, this will come with the next PR to upstream CMSSW very soon

**Pull request merged**
