### PR TITLE
Run3-hcx378Z Read old ZDC geometry from DB correctly when dense index was not written out to DB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Run3-hcx378Z Read old ZDC geometry from DB correctly when dense index was not written out to DB

#### PR validation:

Tested with a dedicated script

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a bug fix. It is backported to 14_1_X  as #46536 to read back the older version of ZDC geometry from DB

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
will a backport be needed?  It would be nice to answer this systematically in the PR description.

**Comment by bsunanda** [comment]
I have now updated the description. But I am wondering about backporting since you mentioned that 14_1_X is a closed release and put #46468 on hold (which is also a bugfix of some sort)

**Comment by bsunanda** [comment]
@mandrenguyen Please suggest if I would prepare the backport

**Comment by mandrenguyen** [comment]
If you can explain first exactly what this PR does and why it's needed I would be in better position to comment on whether a backport is necessary.

**Comment by bsunanda** [comment]
The existing code does not load the Reco geometry of ZDC which was pointed to me by Hannah. That was for Reco geometry created by earlier versions which refer to earlier geometry versions. The changes made test if the geometry to be loaded is from the earlier or later version and accordingly load the geometry. So that was a serious bug for geometry in DB.
________________________________

**Comment by hjbossi** [comment]
Just to document also here, my understanding is that this handles the warning we were seeing when running the reconstruction that the list of valid ZDC Det IDs is zero (which has no actual effect as the det IDs are not used elsewhere). We've asked @bsunanda whether this is the only difference or if something else is changed in addition, just so we can effectively evaluate the change.

**Comment by mandrenguyen** [comment]
hold
Folks are checking what is the effect on the output, if any

**Comment by bsunanda** [comment]
@mandrenguyen I do not see why you hold this. PR. Even if this does not affect ZDC reconstruction results, this is a fix for the geometry in DB  to be read back correctly. You can hold a backport but not the original fix

**Comment by bsunanda** [comment]
But that is for 14_1_X. Even if it has no effect, it correctly uploads the geometry which the one in the master does not. That should be the criteria to integrate not what the subsequent steps (reconstruction) provides
________________________________

**Comment by mandrenguyen** [comment]
unhold
@hjbossi reports that this check has now been done.

**Comment by hjbossi** [comment]
Yes, to confirm with our offline checks we saw that the warning observed previously disappears and all other output remains the same. This PR should be able to be safely backported. Thanks to @cfmcginn for his assistance with this check.

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
@bsunanda can you backport to 14_1_X please?
We should try to keep the logs clean of this warning message during data taking.

**Comment by bsunanda** [comment]
@mandrenguyen Submitted the backported PR

**Pull request merged**
