### PR TITLE
Fixed Geant4 exception handling

### PR DESCRIPTION
**Pull request by civanch**
Enable CMS exception handler (derived from G4VException) for handling of exceptions from Geant4. Forward any Geant4 exception to the CMS framework as fatal exception or as a warning.

Clean-up produce method of OscarProducer and OscarMTProducer.

Should not affect results of any WF.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by civanch** [comment]
Hi @davidlange6, likely this fix should be back-ported to 9_4_X and 9_3_X?

**Pull request merged**
