### PR TITLE
consolidate `CalibTracker/SiStripQuality`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to consolidate the package  `CalibTracker/SiStripQuality`.
   * plugins in the  `CalibTracker/SiStripQuality/plugins` directory with an header file have been merged together with their implementation file;
   * the `SealModule` file in the same directory is removed;
   * `SiStripBadStripFromASCIIFile.cc`is moved from  `CalibTracker/SiStripQuality` to `CondTools/SiStrip` (where it belongs)
   * a `fillPSetDescription` method has been added to ` ConditionDBWriter` such that it can be used to populate the configuration descriptors of the inherited classes;
   * `SiStripBadStripFromASCIIFile_cfg.py` configuration has been modernized and included in the package unit tests.
   * the file `CalibTracker/SiStripQuality/data/DefectsFromConstructionDB.dat` is removed from `cmssw` and put in the `cms-data` repo in PR https://github.com/cms-data/CondTools-SiStrip/pull/2;
   * finally there is a general code clean-up and modernization;

#### PR validation:

Relies on the (augmented) unit tests of `CondTools/SiStrip`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test with https://github.com/cms-data/CondTools-SiStrip/pull/2

**Comment by tvami** [comment]
@cmsbuild, please test with https://github.com/cms-data/CondTools-SiStrip/pull/2
 * let's test this in a clean IB

**Comment by francescobrivio** [comment]
This picked up the same IB, so not really a clean comparison. Let's try again.

**Comment by francescobrivio** [comment]
@cmsbuild please test with https://github.com/cms-data/CondTools-SiStrip/pull/2

**Comment by tvami** [comment]
+1
 * diffs in MsgLogger only
 * code changes in line w PR describtion
 * needs to merge with https://github.com/cms-data/CondTools-SiStrip/pull/2

**Comment by qliphy** [comment]
+1

**Pull request merged**
