### PR TITLE
Migrate leftover modules (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10335.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
resubmit tests here too...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10337 85541dfc10057196c1d432f551d96a9aad47b56f

Migration of some remaining E/Gamma and PF modules to support multi-threading. There should be no change in monitored quantities. The 75X and 76X versions of this PR, #10336 and #10335, have already been approved by Reco.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10337/5046/summary.html) against baseline CMSSW_7_4_X_2015-07-27-1800 show no significant differences, as expected.

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
Any reason this is still sitting around?

**Comment by lgray** [comment]
@davidlange6 reminder that this needs to go into 74X 
Pertinent 76X and 75X relvals check out for relevant quantities.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
