### PR TITLE
migrate modules used by the HLT menu to multithreading (HLT) (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
backport #10955 to 75x

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
tracked at #10965

**Comment by Dr15Jones** [comment]
please test

**Comment by fwyzard** [comment]
According to github there are over 250 commits.
Are you sure this does not need to be rebased ?

**Comment by fwyzard** [comment]
Sorry, I commented on the wrong PR

**Comment by davidlange6** [comment]
+1

**Pull request merged**
