### PR TITLE
remove access to bare ROOT objects in `HLTFiltersDQMonitor` [`12_6_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #40426

#### PR description:

Verbatim backport of #40426, to ensure the DQM fix in that PR is included in the next release for data-taking in `12_6_X`.

For further details, please see the description of #40426 (and #40419).

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#40426

Fix to (HLT) offline DQM.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
type bugfix

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
