### PR TITLE
Offline PF hadron calibration for MC-v2

### PR DESCRIPTION
**Pull request by spandeyehep**
The code updates between 80x and 90x brought up the energy scale by 3% in HB and 5% in HE (more details here: [link to HCAL presentation in JME meeting](https://indico.cern.ch/event/652583/contributions/2656096/attachments/1490577/2316750/HCAL_Updated_for_JME_20170710.pdf)

Which was fixed by HCAL team, by proposing new condition: HcalRespCorrs_2017plan1_v5.0_mc
Therefore, we had to re-calibrate PF hadrons according to this new condition. 

No major changes has been made in the code apart from changing few calibration parameters (for book-keeping and consistency).
Detailed summary of the development can be found here: [link](https://spandey.web.cern.ch/spandey/files/slides/930pre1_PFCalibration_21Jul2017.pdf)

This PR affects following package:
RecoParticleFlow/PFClusterTools/

Presentation is due in JERC meeting on 27 July and will be followed up in PPD/AlCa.

### CODE REVIEW

**Comment by slava77** [comment]
why do we need changes in the reco code if this is just to re-hardcode some latest state of calibrations which are not even ever enabled in any regular processing workflows?
perhaps it's better to remove the hardcoded functions from RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc

**Comment by slava77** [comment]
@deguio @hatakeyamak 
what is the difference between the current HcalRespCorrs_2017plan1_v4.0_mc and the proposed
HcalRespCorrs_2017plan1_v5.0_mc in the context of how it was derived?

Was v4 also with uniform unit (~1.0) response at the time it was derived? 
Is there a plot similar to p4 in https://indico.cern.ch/event/652583/contributions/2656096/attachments/1490577/2316750/HCAL_Updated_for_JME_20170710.pdf

I'm trying to understand which other changes happened since v4 was introduced (2017-03-17 in DB) and the time of v5 (2017-06-15 ).
Is the current HCAL response with the full ```  'phase1_2017_realistic' : '92X_upgrade2017_realistic_v8'``` GT now non-unit?
if so, which other calibration or change in software changed the HCAL response since v4 was introduced (2017-03-17)?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19925	fb0e53b
- technical update with hardcoded values for a new parameterization used in private tests and to write the new conditions payloads; validation is needed once actual GT update shows up
- jenkins tests pass and comparisons show no differences

**Comment by hatakeyamak** [comment]
@slava77 

Sorry for the slow response. HcalRespCorrs_2017plan1_v4.0_mc was basically derived based on the 80x 2016 MC samples (plus some adjustment for HEP17 channels because the neutral density filter is now removed, thus "2017plan1"). In the plot you are pointing to, black points are E/p of 2016 MC without the RespCorr update corresponding to HcalRespCorrs_2017plan1_v4.0_mc, and after the RespCorr update, the 2016 MC E/p MPV is ~1 (red points).

We thought this should be a good starting point of 2017 MC, because we didn't really have much changes from 2016 to 2017 for HPD channels (i.e. bulk of channels except HEP17), but when we checked E/p (more precisely E_{HCAL}/(p-E_{ECAL})) in 2017 plan1 90x samples, we got blue points. It's not easy to point out exactly what cause the shift from red to blue, but one primary candidate is the update of the M2 chi2 tuning including photostatistics effects, which happened inbetween 900pre4 and 900pre5/6. CaloScan results by Salavat at that time can found at:
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/900pre6_vs_900pre4_SinglePi/
showing some increase in the rechit energy scale. By HcalRespCorrs_2017plan1_v5.0_mc, we are trying to bring E/p back to 1 in 9_x_y MC samples.

Hope this helps.

**Comment by slava77** [comment]
Hi Ken,

Thank you for the detailed response. It's unfortunate that v4 was based on
80x even though essentially all of the updates in M2 were already available
before v4 was released. It's good that this is appropriately corrected now.
I suppose there was no explicit validation until recently.


@arunhep @franzoni please investigate with JME POG to make sure that we
recover correct response for 2016 and 2017 payloads for the PF hadron
calibrations. It looks like we pushed a biased response in the last
iteration for pre-2017.

**Comment by hatakeyamak** [comment]
We are in close communication with JME and AlCa about this, and JEM is already working on the updated PF calibration.
https://spandey.web.cern.ch/spandey/files/slides/930pre1_PFCalibration_21Jul2017.pdf
and I think we will discuss this on Monday in the AlCa meeting
https://indico.cern.ch/event/655116/
This update is expected go to MC v2 production.

**Comment by slava77** [comment]
On 7/29/17 4:08 PM, Kenichi Hatakeyama wrote:
> We are in close communication with JME and AlCa about this, and JEM is
> already working on the updated PF calibration.
> https://spandey.web.cern.ch/spandey/files/slides/930pre1_PFCalibration_21Jul2017.pdf
> and I think we will discuss this on Monday in the AlCa meeting
> https://indico.cern.ch/event/655116/
> This update is expected go to MC v2 production.

Good.
It is somewhat clear to me that the 2017 setup will be done right
because that's the main focus of the updates.

My last email was to urge  enough effort to keep reco of 2016 and
earlier consistent.
It looks like the last update left it out biased because the PF hadron
calibrations derived for 2017 samples (which have a bias in v4 HCAL
payloads) were applied to all past MC periods.

**Comment by spandeyehep** [comment]
@slava77 Dear Slava,

Coming back to the initial question, the hard-coded functions in RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc are required to perform local tests where we need to turn off "useCalibrationsFromDB". Since this code will be in use for rest of this run, we would like to keep these functions and to make "RecoParticleFlow/PFClusterTools/test/ProducePFCalibration.py" and actual payload consistent & most upto date.

The updates have been presented in AlCa meeting [1] & the corresponding payload has been created, uploaded and queued for the GT of CMSSW 93X [2].

Thanks,
Shubham

Links:
[1] https://indico.cern.ch/event/655116/contributions/2675720/attachments/1501281/2338195/AlCa_talk_930pre1_PFCalibration_31Jul2017.pdf
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3132.html

**Comment by slava77** [comment]
On 8/3/17 3:18 AM, Shubham Pandey wrote:
> @slava77 <https://github.com/slava77> Dear Slava,
> 
> Coming back to the initial question, the hard-coded functions in
> RecoParticleFlow/PFClusterTools/src/PFEnergyCalibration.cc are required
> to perform local tests where we need to turn off
> "useCalibrationsFromDB". Since this code will be in use for rest of this
> run, we would like to keep these functions and to make
> "RecoParticleFlow/PFClusterTools/test/ProducePFCalibration.py" and
> actual payload consistent & most upto date.

Hi Shubham

It is a rather bad choice to hardcode the parameters and imply that
testing of these is the same as testing what will be running in production.

I suggest that you move the validation code to use a locally prepared
payload (write an sql file and pick it up with toGet ) and remove the
hardcoded constants.

**Comment by slava77** [comment]
@davidlange6 
please check this PR and sign or suggest changes.
This was signed for almost two weeks by now.

**Comment by seemasharmafnal** [comment]
Hi Slava, David,

> It is a rather bad choice to hardcode the parameters and imply that testing of these is the same as testing what will be running in production. I suggest that you move the validation code to use a locally prepared payload (write an sql file and pick it up with toGet ) and remove the hardcoded constants.

We also used this code to reconstruct some samples ourselves to make higher level tests (not just validation for the purpose of book-keeping). Moving these hardcoded functions out of this code also has worry of duplicating the hardcoded eta-dependencies etc. 
Since these numbers are expected to stay for this year's running, we think it makes sense to update these in release too (PFEnergyCalibration.cc & ProducePFCalibration.py) & request to merge these changes. 

Thanks, Seema
P.S. - Shubham is away for a local CMS related meeting, and doesn't have good internet there unfortunately.  He will be back online tomorrow. Sorry for delay in responding.

**Comment by davidlange6** [comment]
Apologies - i had meant to ask if we have the corresponding GT?

**Comment by slava77** [comment]
On 8/7/17 7:19 AM, David Lange wrote:
> Apologies - i had meant to ask if we have the corresponding GT?

GT is decoupled from this update.
this PR has only changes to hardcoded parameters needed to write the GT.

>

**Comment by arunhep** [comment]
>Apologies - i had meant to ask if we have the corresponding GT?
although as mentioned by @slava77 that GT updates are decoupled but this PR #20067 contains the condition updates for new PF calibrations.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
