### PR TITLE
Update RunTheMatrix (phase1 aging + fasttimig with new BS)

### PR DESCRIPTION
**Pull request by boudoul**
fix aging Phase1 + define FastTiming WF including the HLLHC_Fix Beamspot introduced in the PR #8320

### CODE REVIEW

**Comment by boudoul** [comment]
Forgot to say that the fastiming WF can be run with 160XX

**Comment by mark-grimes** [comment]
Two small points
 * I'm not sure I like the name `RecoFullFast`, it could create some confusion as to whether it is a FullSim or FastSim step, maybe `RecoFull_FastTimer`?  Anyway, this can be resolved at a later date.
 * It worries me changing the Phase1 global tag at this point, but you know far more than me about this @boudoul.

I'm running some tests privately (since the standard tests won't check this), all going well I merge and cut a release for HGCal.

**Comment by mark-grimes** [comment]
merge

Tested 16000 privately, all looks fine.

**Comment by boudoul** [comment]
Hi @mark-grimes , thanks!
for phase1 GT, it has been changed already in the rereco _fix MC production (and used in recent phase1 relvals)  so runthematrix was just behind with this respect, I just made it uptodate.
I will change in the next iteration the RecoFullFast, that is a good point , it will be queued  soon for the next release

**Pull request merged**
