### PR TITLE
Phase2-hgx359L Equip the correct wafer and passive module names for the V19 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Equip the correct wafer and passive module names for the V19 version of HGCal Geometry

#### PR validation:

Use the dumping facility to test wafers

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
type hgcal

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
