### PR TITLE
Run2-hcx29 Expand Hcal DetId

### PR DESCRIPTION
**Pull request by bsunanda**
Required to use finer eta/phi segmentation of HCAL as demanded in PhaseII. It is backward compatible with all existing data. It passes the short matrix tests and also single pion scans. Showing some comparison with bare 7_6_0_pre5 and with the changes (referred to as 7_6_0_pre8 in the figures:  simulation and RecHit 
rechitstask_emean_vs_ieta_eh
level.
simhitstask_emean_vs_ieta_h

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
@bsunanda - would it affect 71x sim data reprocessing with 76x? (see @boudoul question in #10353)

**Comment by bsunanda** [comment]
I dont think so.
________________________________

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Will check more later. But why not worry about plots like this?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-09-22-1500+11427/10181/validateJR/all_OldVSNew_TTbarPUwf50202p0/all_OldVSNew_TTbarPUwf50202p0c_CaloTowersSorted_towerMaker__RECO_obj_obj_eta.png

**Comment by davidlange6** [comment]
@cmsbuild, please test
(I don't see how this PR could trigger the reported differences..)

**Comment by davidlange6** [comment]
@bsunanda, seems that these results confirm that the pileup workflows break completely. the non PU ones look ok, so maybe that is the important difference in your comparisons and the ones done by the PR system

do we expect problems if “new" and “old" gem-sim are mixed together?

**Comment by bsunanda** [comment]
I did not expect this as long as HcalDetId rather than RawId is used. Could you tell me one PU workflow and let me check if I can fix this.
________________________________

**Comment by civanch** [comment]
For example, 25202

**Comment by bsunanda** [comment]
I have updated the PR by having uniform DetId at the level of mixing unit.
________________________________

**Comment by bsunanda** [comment]
Can someone initiate the testing of this PR?
________________________________

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
Please check - the unit test errror is due to a missing file - cannot be due to this PR
________________________________

**Comment by bsunanda** [comment]
Could you restart the tests?
________________________________

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@cmsbuild , it seems that tests stack, likely needs restart. please test

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by bsunanda** [comment]
The unit test failure is due to opening a file ttbarForMetTests.root.
@cmsbuild  Can you restart the test once the issue of PR 11684 is settled which is curing all the broken tests in the IB
________________________________

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild - the error is unrelated to this PR:
```
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
09-Oct-2015 18:41:15 CEST  Initiating request to open file file:ttbarForMetTests.root
----- Begin Fatal Exception 09-Oct-2015 18:41:16 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file 'ttbarForMetTests.root'
   Additional Info:
      [a] Input file file:ttbarForMetTests.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
Failure using recoMET_caloMet_cfg.py: status 84
status = 21504

---> test testRecoMETMETProducers had ERRORS

```

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
The unit test failure is unrelated to the PR
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test
________________________________
From: Sunanda Banerjee
Sent: 14 October 2015 08:16
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] Run2-hcx29 Expand Hcal DetId (#11427)

The unit test failure is unrelated to the PR
________________________________

**Comment by smuzaffar** [comment]
please test

**Comment by bsunanda** [comment]
This unit test failure is most likely not connected to the PR
________________________________

**Comment by bsunanda** [comment]
Please see the comment.
Slava made a comment on Kevin's pull request here: https://github.com/cms-sw/cmssw/pull/11497#issuecomment-147969678

________________________________

**Comment by bsunanda** [comment]
@davidlange6 This PR has failure in the same unit test as in PR 11497. I could not see any connection of the failure with this PR. We badly need this PR to come as a part of 7_6_0.
________________________________
From: Sunanda Banerjee
Sent: 15 October 2015 14:44
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] Run2-hcx29 Expand Hcal DetId (#11427)

Please see the comment.
Slava made a comment on Kevin's pull request here: https://github.com/cms-sw/cmssw/pull/11497#issuecomment-147969678

________________________________

**Comment by davidlange6** [comment]
@bsunanda - I agree - your concern should be more the changing physics results rather than the failing unit test (which indeed has nothing to do with this PR) - are the changes seen expected?

**Comment by bsunanda** [comment]
@davidlange6 @civanch Together with Vladimir we looked at some of the changes observed in the comparison tests. They are compatible with fluctuations due to random seed. So we think the PR will not bring any incompatibility.
________________________________

**Comment by davidlange6** [comment]
there are usually no random seed changes in PR tests aside those introduced by the PR itself. is there something in this pr that brings an expected change in the way random numbers are consumed?

(I think the fact that plots are unchanged up through and including local reco pretty much rules out an actual change affecting seeds)

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
-1 
a rebase is needed.

**Comment by slava77** [comment]
in fact, if there are real changes from this PR in the physics quantities, this PR can't go to 76X.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Closing this PR in view of the new PR which has been put in now (12406)

**Pull request closed without merging**
