### PR TITLE
[124X] Add new tag for PPS PCL, move SiStrips tags to Prod

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39181

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/39181

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39181

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
+alca

- no differences aside from MTD and msgLogger
- PR according to the description

**Comment by tvami** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-08-26-1100+d8f54f/52402/validateJR.html

I actually wonder why we see anything for MsgLogger, this PR really doesnt do anything, @cms-sw/orp-l2 is this understood?

**Comment by tvami** [comment]
+db

**Comment by perrotta** [comment]
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-08-26-1100+d8f54f/52402/validateJR.html
> 
> I actually wonder why we see anything for MsgLogger, this PR really doesnt do anything, @cms-sw/orp-l2 is this understood?

They are possible additional LogMessages related to the order with which the files for the mixing module are opened, which does not necessarily reproduce from one job and another one

**Comment by tvami** [comment]
> > https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-08-26-1100+d8f54f/52402/validateJR.html
> > I actually wonder why we see anything for MsgLogger, this PR really doesnt do anything, @cms-sw/orp-l2 is this understood?
> 
> They are possible additional LogMessages related to the order with which the files for the mixing module are opened, which does not necessarily reproduce from one job and another one

I see, thanks Andrea!

**Comment by perrotta** [comment]
+1

**Pull request merged**
