### PR TITLE
Cleanup unused pixel CPE code

### PR DESCRIPTION
**Pull request by ahinzmann**
Remove unused code from pixel CPE.
No changes to RECO/AOD/MiniAOD.
Tested with:
runTheMatrix.py -l limited

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
maybe the DAS error goes away

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14490	166eeb9
- code changes look OK: removal of the old CPE hidden behind compiler ifdef
- jenkins tests pass and comparisons with baseline show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
