### PR TITLE
Add EXODisplacedJet skim to DisplacedJet PD and relval (including PR 20586)

### PR DESCRIPTION
**Pull request by kfjack**
Add EXODisplacedJet skim to DisplacedJet PD and relval (including PR 20586)

### CODE REVIEW

**Comment by kfjack** [comment]
@fabozzi I added @jingyuluo's PR #20586 and workflows[136.792] to relval_standard and relval_steps. Please let me know if this is the right way to go? Many thanks!

**Comment by fabozzi** [comment]
@kfjack 
seems ok, thank you!

**Comment by fabozzi** [comment]
please test workflow 136.792

**Comment by kfjack** [comment]
@fabozzi I think the problem is due to missing definition of input RAW data for the DisplacedJet PD. I found there is no /DisplacedJet/Run2017B-v1/RAW as well. Can we use Run2017C instead?

**Comment by jingyuluo** [comment]
Hi @fabozzi and @kfjack , I just realized that the Displaced Jet Paths were only online after HLT v2 menu in 2017, so there is no Run2017B data for DisplacedJet PD...

**Comment by jingyuluo** [comment]
Dear @fabozzi , how is it going on with this? Would it be okay that we can proceed with Run2017C as @kfjack suggested?

Thanks a lot,
Jingyu

**Comment by fabozzi** [comment]
@jingyuluo 
the PR #20699 with 2017C data relvals definition has just been merged
@kfjack can rebase starting from the next IB and add 2017C relval on displacedJet PD

**Comment by kfjack** [comment]
OK, let me start to work on it later today.

**Comment by fabozzi** [comment]
Thank you, Jack. You can close this PR.

**Pull request closed without merging**
