### PR TITLE
Rework MET correction/uncertainty tool

### PR DESCRIPTION
**Pull request by michaelwassmer**
#### PR description:

This PR was created mainly to replace the sequences in PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py with tasks. This was requested on many occasions. Since this module is/was quite long the number of changes is also quite high. I tried to use the opportunity to also improve the style and formatting a bit. Moreover, I removed some old and unnecessary code blocks.

#### PR validation:

- [x] `scram b code-format` without errors
- [x] `scram b code-checks` without errors
- [x] `runTheMatrix.py -l limited -i all --ibeos` without errors

In the end, it's probably best to squash this PR into one commit after the (hopefully succesful) review.

If there are any questions, don't hesitate to ask.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test
I suppose this PR ultimately has nothing to do with 12_5_X, right?  If that's indeed the case, please update the title.

**Comment by michaelwassmer** [comment]
I'm not really sure what the problem is. According to the summary, it is in 'Matrix INPUT Tests Outputs', but I don't know how to find out whether this is a problem from the commit or not. When looking at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ef3c8c/28974/runTheMatrixINPUT-results/matrixTestsINPUT.log there is an error message but I'm not sure what to make of it.

**Comment by mandrenguyen** [comment]
looks fine to me. 
Can you please remove the commented out sequences though? 
Apologies, I should have asked you to do that before re-triggering the tests.

**Comment by michaelwassmer** [comment]
> looks fine to me. Can you please remove the commented out sequences though? Apologies, I should have asked you to do that before re-triggering the tests.

Done

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
Mainly code cleanup, no change to reco.
Tests were retriggered, but only change since last successful test is removal of comments.

**Comment by swertz** [comment]
+1

Useful cleanup, no changes in the output as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
