### PR TITLE
Fixing Memory Coruption for large histograms in DQMFileSaverPB

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

DQMFileSaverPB allocates its buffer to compress the histogram on the stack. This means it is limited to a size of 10MB. There are histograms which are bigger than this (specifically HLT paths vs bx) and thus can exceed this limit and crash the client. We encountered this when running the full menu of 800+ paths.

This PR moves it to the heap.  Feel free to use a different preferred way of doing it. 

#### PR validation:

The firstCollisions v2.0 no longer crashes the P5 DQM workflow when done offline. Further validation to be done by the DQM group.

### CODE REVIEW

**Comment by fwyzard** [comment]
please use `compression_output.data()` rather than `&compression_output[0]`

**Comment by fwyzard** [comment]
On an unrelated note, my guess is that it would be much better **not** to compress the histograms outputby the HLT jobs.

The first merge step usually happens on the same machine as the HLT jobs, so the compression and decompression are likely to add a CPU usage overhead for little gain in bandwidth.

**Comment by Sam-Harper** [comment]
indeed you're right about the .data(), its better. 

also we dont compress at the HLT (as far as I can tell). This is a fix for the DQM workflow which runs I believe on the DQM machines which do compress it.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
type bugfix

**Comment by fwyzard** [comment]
> also we dont compress at the HLT (as far as I can tell). This is a fix for the DQM workflow which runs I believe on the DQM machines which do compress it.

Well, the `DQMFileSaverPB` should only run as part of the HLT menu, where it saves the histograms in ProtoBuf format, that are later merged by the `fastHadd`.
It doesn't make sense to use it anywhere else, as far as I know every other workflow used the DQMIO format.

**Comment by Sam-Harper** [comment]
I also was surprised that that was part of the DQM client workflow and I have to admit,  I dont know the reason why they decided to do that this way. But I defer to the DQM group here and I'm sure they have their reasons. Regardless,  I was curious why it crashed with one menu and  not the other so I dug into it.

Reading back my original comment, it may have given the wrong tone, that was not my intention and I apologise if it did.  I fully agree with everything you said and at the HLT it is all done correctly (and I suspect all set by you).  This is solely a DQM client issue and I agree it was not clear from the original PR description that it only applied there.

**Comment by fwyzard** [comment]
> I also was surprised that that was part of the DQM client workflow and I have to admit, I dont know the reason why they decided to do that this way. But I defer to the DQM group here and I'm sure they have their reasons. Regardless, I was curious why it crashed with one menu and not the other so I dug into it.

👍 

> Reading back my original comment, it may have given the wrong tone, that was not my intention and I apologise if it did.

Not at all.

> I fully agree with everything you said and at the HLT it is all done correctly (and I suspect all set by you).

I don't think I can claim any merit there :-)

> This is solely a DQM client issue and I agree it was not clear from the original PR description that it only applied there.

Sorry, I missed that.

We should try to understand why it is used outside of the HLT, but I'm traveling this weekend, so I won't have a chance to look at any code or workflows until tomorrow.

**Comment by fwyzard** [comment]
On a related note, maybe we should finally add a full online-like wirkflow to the release validation tests ?

Something running the HLT from raw data in DAQ format, writing the output in streamer format and the histograms in protobuf format, followed by a merge step, the online DQM, and the offline repacking.

**Comment by missirol** [comment]
@cms-sw/dqm-l2 , could you please review this PR?
 
 This fix is relevant to P5 operations, and it will need to be backported to `12_4_X` and `12_3_X`.

**Comment by pmandrik** [comment]
Tested successfully at the DQM playback at P5 with 352508 run reported to be a one with the crash previously.

> > also we dont compress at the HLT (as far as I can tell). This is a fix for the DQM workflow which runs I believe on the DQM machines which do compress it.
> 
> Well, the `DQMFileSaverPB` should only run as part of the HLT menu, where it saves the histograms in ProtoBuf format, that are later merged by the `fastHadd`. It doesn't make sense to use it anywhere else, as far as I know every other workflow used the DQMIO format.

ProtoBuf format is also consumed by new DQM GUI, probably the same interface is use to create .pb files for the gui.

**Comment by pmandrik** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by fwyzard** [comment]
> ProtoBuf format is also consumed by new DQM GUI, probably the same interface is use to create .pb files for the gui.

I see... now I'm curious, why
  - in some cases (at HLT ?) the file is compressed as a whole using `google::protobuf::io::GzipOutputStream`
  - in other cases (in the online DQM) the individual MEs are compressed using `zlib` ?

**Pull request merged**
