### PR TITLE
modernize configurations for reading / writing BeamSpot from DB, add unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Being an occasional user of the tools in `RecoVertex/BeamSpotProducer/test` and having finally been tired enough to find them in an unusable state, I decided to do something about it.

#### PR validation:

Relies on the added unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31908	2e434c6 
- test files in  RecoVertex/BeamSpotProducer/test were modified; one unit test (covering two test configs) was added
- jenkins tests pass, including a newly added unit test, which has a reasonably-looking log file

**Comment by mmusich** [comment]
@yuanchao,  @christopheralanwest, @tocheng, @tlampen, @pohsun 
any further comments?

**Comment by christopheralanwest** [comment]
@francescobrivio Do you have any comments on this PR?

**Comment by francescobrivio** [comment]
> @francescobrivio Do you have any comments on this PR?

It's fine for me. Thanks for this @mmusich

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
