### PR TITLE
Consumes migration of  Alignment/ReferenceTrajectories

### PR DESCRIPTION
**Pull request by bbilin**
#### PR description:

This PR is about the consumes migration of Alignment/ReferenceTrajectories and its dependencies. 

#### PR validation:

Ran successfully wf 1001.0 

1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED Step7-PASSED Step8-PASSED  - time date Tue Sep 28 10:38:23 2021-date Tue Sep 28 10:27:48 2021; exit: 0 0 0 0 0 0 0 0 0
1 1 1 1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@makortel @Dr15Jones do you have suggestions about https://github.com/cms-sw/cmssw/pull/35259#issuecomment-919031497?

**Comment by makortel** [comment]
From just browsing the code in this PR it is not immediately clear to me which of the helper classes is constructed outside of `AlignmentProducerAsAnalyzer` constructor. I'm going to continue looking, but I'd like to note already now that adding `ConsumesCollector` arguments to functions that take `Event` or `EventSetup` like here
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/interface/AlignmentProducerBase.h#L90
is not only unnecessary (declaring consumes information there would be way too late), those make reasoning the code by just browsing more difficult.

**Comment by makortel** [comment]
Ok, now I found the incorrect calls
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L40
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L85-L86
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L94

the `consumesCollector()` may be called only in the constructor of an EDModule, as is already done in 
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L13-L14
The helper classes need to be reworked such that either they take the `ConsumesCollector` in their constructor, or the class that uses the helpers declares the consumes information, gets the ESProducts, and passes them to the helper classes. Which of these is easier depends. In rare cases it is possible that neither of these really work (like in #35269), in which case we can discuss more.

**Comment by tvami** [comment]
@bbilin do you maybe have an update on this?

**Comment by bbilin** [comment]
Hi @tvami unfortunately I dont have any updates yet. 

@makortel what I tried was to change, I am stuck as below. So any help, example similar codes or PRs would be useful for me to draw the path. 

What I tried, for example, to replace 

cmssw/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc
Lines 85 to 86 

to

edm::EDLooper::Status AlignmentProducer::duringLoop(const edm::Event &event, const edm::EventSetup &setup,edm::ConsumesCollector iC) {
  if (processEvent(event, setup, iC))
  
  this 
  
  Status duringLoop(const edm::Event&, const edm::EventSetup&, edm::ConsumesCollector) override;
  is coming from FWCore/Framework/interface/EDLooper.h.
  
  So I am stuck here, this is clearly not the path to take. Any help, suggestion is welcome.

**Comment by makortel** [comment]
@bbilin I'm not sure if I understood your question correctly, so please elaborate if I don't answer to it. The problem on lines 85-86
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/plugins/AlignmentProducer.cc#L85-L86
is the call to `consumesCollector()` on line 86. That function can be called only in the `AlignmentProducer` constructor. Trying to get an `edm::ConsumesCollector` in any other way will not work.

The `AlignmentAlgorithmBase::alignmentAlgo_` already gets the `ConsumesCollector` in its constructor
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/CommonAlignmentProducer/src/AlignmentProducerBase.cc#L281-L289

I guess you added the `ConsumesCollector` to the `initialize()` function because the `TrajectoryFactoryPlugin::get()->create()` is being called there, e.g. in
https://github.com/cms-sw/cmssw/blob/52d9ac821888de4114c43c532389d5bf06a7eccd/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc#L279
Can those `create()` calls be moved to the constructors of `AlignmentAlgorithmBase`-derived classes?

**Comment by bbilin** [comment]
Hi @makortel 
It is clearer now, thanks. So, please forgive the syntax for the moment, what you suggest is something like the following around line 87 of cmssw/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc

MillePedeAlignmentAlgorithm::MillePedeAlignmentAlgorithm(const edm::ParameterSet &cfg, edm::ConsumesCollector &iC)
:
theTrajectoryFactory = TrajectoryFactoryPlugin::get()->create(fctCfg.getParameter<std::string>("TrajectoryFactoryName"), theConfig.getParameter<edm::ParameterSet>("TrajectoryFactory"), iC), ...

If true I will try to rework like this.

**Comment by makortel** [comment]
@bbilin Yes, along those lines (I presume the call to `create()` should be done only if `this->isMode(myMilleBit)` as currently in the `initialize()` function).

**Comment by bbilin** [comment]
All clear, sorry, did not have any time until today. Will modify accordingly and commit. Thanks!

**Comment by bbilin** [comment]
Hi @makortel I played around a bit- the changes simplify the dependencies a lot, but what I get is an ld link issue during compilation. I pushed to a separate branch and can merge to the branch of the PR once fixed. 

https://github.com/bbilin/cmssw/tree/ConsumesMigRefTraj2

Any ideas are welcome. Many thanks,

B.

**Comment by makortel** [comment]
@bbilin Could you post the link failure message?

**Comment by bbilin** [comment]
@makortel here it is:

>> Building  edm plugin tmp/slc7_amd64_gcc900/src/Alignment/MillePedeAlignmentAlgorithm/plugins/AlignmentMillePedeAlignmentAlgorithmAuto/libAlignmentMillePedeAlignmentAlgorithmAuto.so
/cvmfs/cms-ib.cern.ch/nweek-02699/slc7_amd64_gcc900/external/gcc/9.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc900/src/Alignment/MillePedeAlignmentAlgorithm/plugins/AlignmentMillePedeAlignmentAlgorithmAuto/MillePedeAlignmentAlgorithm.cc.o: in function `_GLOBAL__sub_I_MillePedeAlignmentAlgorithm.cc':
MillePedeAlignmentAlgorithm.cc:(.text.startup+0x1a4): undefined reference to `edmplugin::PluginFactory<AlignmentAlgorithmBase* (edm::ParameterSet const&, edm::ConsumesCollector&, edm::EventSetup&, AlignmentAlgorithmBase::EventInfo&)>::get()'
collect2: error: ld returned 1 exit status
gmake: *** [config/SCRAM/GMake/Makefile.rules:1700: tmp/slc7_amd64_gcc900/src/Alignment/MillePedeAlignmentAlgorithm/plugins/AlignmentMillePedeAlignmentAlgorithmAuto/libAlignmentMillePedeAlignmentAlgorithmAuto.so] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2

**Comment by makortel** [comment]
I think the new factory `Alignment/CommonAlignmentAlgorithm/interface/MPAlignmentAlgorithmPluginFactory.h` is missing a corresponding `.cc` file with `EDM_REGISTER_PLUGINFACTORY`.

But why is the new factory needed? The construction interface
```cpp
typedef edmplugin::PluginFactory<AlignmentAlgorithmBase*(const edm::ParameterSet&, edm::ConsumesCollector&, edm::EventSetup &, EventInfo &)>
```
can not work because framework does not provide `ConsumesCollector` and `EventSetup` at the same time for any function. `ConsumesCollector` is available only in the EDModule constructor, where `EventSetup` is not, and `EventSetup` is availabe in Event/Lumi/Run processing functions, where `ConsumesCollector` is not.

**Comment by bbilin** [comment]
In order to move "const RefTrajColl trajectories" to the constructor I needed the eventsetup and eventinfo:

https://github.com/bbilin/cmssw/commit/6c4e59604d4f149c214046c46955aa08f15ebe0b#diff-4c09c8c4e948947d5b7a6803913ef72c95343ddebcda5407c94ae4fdef5394cbR130

It seems I need more help then :)

**Comment by makortel** [comment]
Is the need to add `ConsumesCollector` to `TrajectoryFactoryBase::trajectories()` coming from
https://github.com/bbilin/cmssw/blob/6c4e59604d4f149c214046c46955aa08f15ebe0b/Alignment/ReferenceTrajectories/plugins/ReferenceTrajectoryFactory.cc#L169-L185
?

The easiest way, that I can think of, would be moving the construction of `BzeroReferenceTrajectoryFactory` to the constructor of `ReferenceTrajectoryFactory`.

An alternative, if the set of ESProducts that any of the `TrajectoryFactoryBase`-derived classes need is "relatively small", would be to move the esConsumes and getting the ESProducts from `TrajectoryFactoryBase`-derived classes to the responsibility of the caller of `TrajectoryFactoryBase`.

(I can think of some further alternatives, but I'd like to understand if these simpler solutions could be good enough before going there)

**Comment by bbilin** [comment]
Many thanks, it seems the easiest option worked- it compiles- I dont know if it is correct though. The only way to test would be to run it. https://github.com/cms-sw/cmssw/compare/master...bbilin:ConsumesMigRefTraj3?expand=1

**Comment by tvami** [comment]
Hi @bbilin please go ahead with merging the two branches, and let's test them with Jenkins

**Comment by mmusich** [comment]
@tvami the base branch is mine,  I'll cherry pick commits tomorrow.
On the other hand there's no need for using the bot to test.  @bbilin can just run locally wf 1001.0 and confirm it runs.

**Comment by bbilin** [comment]
@mmusich @makortel @tvami  To be able to easily commit for further changes that Matti was mentioning I will close this one and open a new one from the branch I have after I do the test locally today.

**Comment by mmusich** [comment]
cherry-picked commits, rebased and cleaned-up history.
I found a compilation warning in `Alignment/ReferenceTrajectories/plugins/ReferenceTrajectoryFactory.cc`.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
assign trk-dpg

**Comment by mmusich** [comment]
hold

waiting for explicit green-light from the Tracker Alignment group https://github.com/cms-sw/cmssw/pull/35259#issuecomment-928948530

**Comment by mmusich** [comment]
@bbilin can you transform the PR from draft to "open for review"?

**Comment by bbilin** [comment]
@mmusich done. Thanks.

**Comment by makortel** [comment]
> waiting for explicit green-light from the Tracker Alignment group [#35259 (comment)](https://github.com/cms-sw/cmssw/pull/35259#issuecomment-928948530)

Any news from the tests yet?

**Comment by mmusich** [comment]
>  waiting for explicit green-light from the Tracker Alignment group

for the record, the results of validating this PR from the alignment point of view were presented [here](https://indico.cern.ch/event/992976/contributions/4567099/attachments/2327122/3964513/Presentation.pdf).

**Comment by tvami** [comment]
@vbotta do you maybe have an update on the validation of this? pre5 is supposed to close today...

**Comment by tvami** [comment]
>  unfortunately not.

pre5 is now delayed, do you think this could converge on a week's timescale? Thanks @vbotta !

**Comment by tvami** [comment]
Great, thanks @antoniovagnerini !

**Comment by perrotta** [comment]
+1
- Let have this tested in the IBs as early as possible before the final pre

**Pull request merged**
