### PR TITLE
Extended Geometry 2017 Scenarios Cleanup

### PR DESCRIPTION
**Pull request by ianna**
* Extended2017 geometry scenario is now the default one with new Pixel and Hcal 2017 numbering
* All other (mostly identical) scenarios are removed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - as discussed, please let me know if there are any new requests for 2017 geometry updates foreseen. Otherwise, this scenario is going to be a default for 2017 GT

**Comment by ianna** [comment]
@kpedro88 and @bsunanda - FYI

**Comment by rovere** [comment]
@ianna thanks for fixing all istances in SimTracker and Validation code.

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - please merge it.

**Pull request merged**
