### PR TITLE
HLT DQM cleanup

### PR DESCRIPTION
**Pull request by natalia-korneeva**
Moving BTag/ subdirectories to BTV/

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by defranchis** [comment]
@jfernan2 could we proceed with the integration of this PR? Is there anything else that needs to be done or checked? Thanks a lot

**Comment by dmitrijus** [comment]
+1

**Comment by defranchis** [comment]
@davidlange6 could you please review and sign this PR?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
