### PR TITLE
Addition of Hgg trkSumPtHollowConeDR03 variable in NanoAOD

### PR DESCRIPTION
**Pull request by VourMa**
This PR is a follow-up to a couple of updates made to the NanoAOD content to accommodate variables that are needed for the preselection of H -> γγ analyses.

PRs #36037 and #36526 applied the changes advertized in an [XPOG meeting presentation](https://indico.cern.ch/event/1085967/#4-hgg-photon-updates-for-nano) some time ago. The variable `trkSumPtHollowConeDR03` is mentioned in the [slides](https://indico.cern.ch/event/1085967/contributions/4565987/attachments/2335188/3980173/photons_hgg_xpog.pdf#page=9) but was included neither in the aforementioned PRs nor in a subsequent one. After a communication with the XPOG conveners, the Hgg conveners and the authors of the previous relevant PRs, this PR comes to include this variable.

As a simple validation, a custom NanoAOD file was produced with the updated configuration and it included the new branch with reasonable values.

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

New variable visible in DQM and looks reasonable.

**Comment by perrotta** [comment]
+1

**Pull request merged**
