### PR TITLE
Add braces after control statements

### PR DESCRIPTION
**Pull request by fwyzard**
This should add braces after control statements, e.g. change
```
if (something)
  do_something();
```
to
```
if (something) {
  do_something();
}
```

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
I tried applying this - 

the actual changes look like

-    if (triggerResults_ == nullptr) throwTriggerResultsMissing();
+    if (triggerResults_ == nullptr) { throwTriggerResultsMissing(); }


-      if (!localconfservice.isAvailable())
-              throw cms::Exception("TrivialFileCatalog", "edm::SiteLocalConfigService is not available");
+      if (!localconfservice.isAvailable()) {
+              throw cms::Exception("TrivialFileCatalog", "edm::SiteLocalConfigService is not available"); }

**Comment by Dr15Jones** [comment]
I'd say it was an improvement.

**Comment by fwyzard** [comment]
Maybe it expects clang-format to take care of the newlines etc. ?

**Comment by fwyzard** [comment]
@davidlange6 do we merge this ?

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
Hi Fabio

Testing this or doesn’t actually test what it will eventually do (as it introduces new code check rules)


On 9 Jan 2018, at 07:57, Fabio Cossutti <notifications@github.com<mailto:notifications@github.com>> wrote:


please test

**Comment by fwyzard** [comment]
rebased on top of #22112

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
Some history: this was supposed to go in together with the introduction of the clang-format checks.

Shall we try that again, or give up for the time being ?

**Comment by fabiocos** [comment]
@fwyzard I understand that David had started to work on this in #21479 , but then the move stopped. 
@davidlange6 yesterday you commented about scripts you have to make a soft migration without breaking existing PRs, we should follow up on this.

**Comment by davidlange6** [comment]
see comments in #22259 - it seems this check is not able to deal with cmssw automatically.

**Comment by fwyzard** [comment]
@davidlange6 do you think it would make sense to try this together with the clang format changes ?

**Comment by fabiocos** [comment]
@fwyzard I had already discussed this possibility with @davidlange6 and @smuzaffar since we need to systematically go through all the places in the repository. We need just to ensure that the behaviour is the desired one with the latest version of the tool I would say

**Comment by davidlange6** [comment]
I'm personally all for doing more with clang-tidy- at the same time as clang-format or not. Eg, one could discuss one new rule to add per month in core software and slowly apply them (and eventually we'd get somewhere) - the work is that someone should do a precheck that new rules don't cause too many problems when they are applied. This one did create some problems at the time, but that was several LLVM versions ago, so its probably better now..

**Comment by smuzaffar** [comment]
problem caused by this was due to our build rules ( see my comment here https://github.com/cms-sw/cmssw/pull/22259#discussion_r279358502 ) . I am testing it on full CMSSW to see if there are any other issues with this check.

**Comment by smuzaffar** [comment]
-1
@fwyzard, for some cases this check is not generating valid code. For statements which ends with `};` e.g
```
if (condition) return {};
```
it generates code like
```
if (condition) { return {}};
```
In some cases it also adds extra {} for classes/struct
```
diff --git a/OnlineDB/EcalCondDB/interface/LMFLmrSubIOV.h b/OnlineDB/EcalCondDB/interface/LMFLmrSubIOV.h
index 78fc1a87de4..15aa2925220 100644
--- a/OnlineDB/EcalCondDB/interface/LMFLmrSubIOV.h
+++ b/OnlineDB/EcalCondDB/interface/LMFLmrSubIOV.h
@@ -10,7 +10,8 @@
 #include "OnlineDB/EcalCondDB/interface/LMFUnique.h"
 #include "OnlineDB/EcalCondDB/interface/LMFIOV.h"
 
-class LMFLmrSubIOV : public LMFUnique {
+class LMFLmrSubIOV { 
+}: public LMFUnique {
  public:
   friend class EcalCondDBInterface;
 
diff --git a/OnlineDB/EcalCondDB/interface/LMFSextuple.h b/OnlineDB/EcalCondDB/interface/LMFSextuple.h
index 6559c9f769c..1573587ec4a 100644
--- a/OnlineDB/EcalCondDB/interface/LMFSextuple.h
+++ b/OnlineDB/EcalCondDB/interface/LMFSextuple.h
@@ -10,7 +10,8 @@
 /**
  *   sextuple of t1, t2, t3, p1, p2, p3
  */
-class LMFSextuple {
+class LMFSextuple { 
+}{
  public:
   LMFSextuple() {
     for (int i = 0; i < 3; i++) {
```
you can reproduce it by running
```
scram p CMSSW_10_6_X_2019-04-29-2300
cd CMSSW_10_6_X_2019-04-29-2300/src
cmsenv
git cms-merge-topic -u 21478
git cms-addpkg OnlineDB/EcalCondDB
scram b llvm-ccdb
clang-tidy -fix -header-filter "$CMSSW_BASE/src/.*" OnlineDB/EcalCondDB/src/LMFCorrCoefDat.cc
```

**Comment by fwyzard** [comment]
Indeed, I can reproduce it also with a very simple, stand alone test case.

Looks like this option is not ready for prime time... can anyone check if the clang 9 nightly hhas better luck, and/or submit a but report to clang ?

**Comment by davidlange6** [comment]
> On Apr 30, 2019, at 5:34 AM, Malik Shahzad Muzaffar <notifications@github.com> wrote:
> 
> -1
> @fwyzard, for some cases this check is not generating valid code. For statements which ends with }; e.g
> 
> if (condition) return {};
> 

does this syntax make sense?

> it generates code like
> 
> if (condition) { return {}};

not sure what else it should do? perhaps the issue is with the original code...

> 
> In some cases it also adds extra {} for classes/struct

these are more interesting... the feature this seems undocumented, unfortunately

**Comment by makortel** [comment]
> > if (condition) return {};
> does this syntax make sense?

`return {};` is a short hand for the default constructor of the return type of the function.

**Comment by fwyzard** [comment]
>>  `if (condition) return {};`

> does this syntax make sense?

yes, for example when returning a struct by value.

>> `if (condition) { return {}};`

> not sure what else it should do? perhaps the issue is with the original code...

I think it should have become
```
if (condition) {
  return {};
}
```

**Comment by davidlange6** [comment]
> On Apr 30, 2019, at 10:56 AM, Matti Kortelainen <notifications@github.com> wrote:
> 
> if (condition) return {};
> does this syntax make sense?
> 
> return {}; is a short hand for the default constructor of the return type of the function.
> 
ah - didn't know that - thanks -  is then {return {}} not valid and expected syntax then?

**Comment by fabiocos** [comment]
@fwyzard @smuzaffar from the latest checks it looks like this option is not ready for production, at least until a fix is provided for the problematic cases observed. What should we do with this PR? Close it and may be open an issue to track the planned update, verifying whether there is a fix in clang?

**Comment by fwyzard** [comment]
We can do whatever you think makes the most sense.

**Comment by fabiocos** [comment]
hold

pending a solution in clang-tidy for the issue above mentioned

**Comment by smuzaffar** [comment]
There are quite a few bugs opens for this check
https://bugs.llvm.org/buglist.cgi?quicksearch=clang-tidy%20braces&list_id=162527

the one I mentioned https://github.com/cms-sw/cmssw/pull/21478#issuecomment-487903598 is open since DEC 2015 (   https://bugs.llvm.org/show_bug.cgi?id=25970 ).

**Comment by fabiocos** [comment]
@smuzaffar yes, this hold risks to last quite long... :-(

**Comment by fabiocos** [comment]
@fwyzard I have opened #27082 to keep track of this proposal, that we should reconsider when clang-tidy is updated. For the time being I believe this PR could just be closed.

**Comment by fwyzard** [comment]
Tracked by #27082 .

**Pull request closed without merging**
