### PR TITLE
maskCell() bug fix: two masks were swapped

### PR DESCRIPTION
**Pull request by bfonta**
#### PR description:

A bug was found in the cell masks that will be eventually used to mask some of the virtual wafers (the masks allow the implementation of partial wafers, such as "fives" or "threes"). Two masks were swapped.

#### PR validation:

The new masks were tested using RecHits from a particle gun: [before correcting the bug](https://bfontana.web.cern.ch/bfontana/ncor3_bug/layer1/?match=*2_*2) and [after correcting the bug](https://bfontana.web.cern.ch/bfontana/ncor3/layer1/?match=*2_*2). The wafers (2,2) and (-2,-2) were not being correctly masked.

### CODE REVIEW

**Comment by kpedro88** [comment]
@bsunanda FYI

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@b-fontana @kpedro88 is this fix relevant for the forthcoming L1T TDR production?

**Comment by b-fontana** [comment]
@fabiocos No, it is not.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
