### PR TITLE
Modernize L1Trigger/CSCTrackFinder modules

### PR DESCRIPTION
**Pull request by Dr15Jones**
Made CSCTFCandidateProducer a global module since it was causing synchronization on LuminosityBlock boundaries in the DIGI workflows.
-Improved const correctness by holding data members by value instead of pointer
-Switched to using EDPutToken

Made CSCTFTrackProducer a one module since it calls thread-hostile code.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Those statics are why I had to make CSCTFTrackProducer a one module. I believe when I've asked in the passed I was told some of those statics are auto generated from a firmware tool and the code it creates is full of globals.

**Comment by thomreis** [comment]
+1

Thanks @Dr15Jones Just wanted to be sure those have been considered.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
