### PR TITLE
Rename local variables according to the coding rules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Rename local variables in `SiPixelUtils` and `PixelCPEGeneric` according to the coding rules.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32591	b029209 
- technical, as described and earlier discussed in #31721

**Comment by slava77** [comment]
@cms-sw/db-l2 
your signature is needed.
Please check and comment or sign.
Thank you.

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
