### PR TITLE
New GEM-CSC LUT generator

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

The class `CSCUpgradeMotherboardLUTGenerator` was incorporated into a new analyzer that dumps the lookup-tables to text files for simulation and firmware (.txt, .mem). The LUTs are not being used yet; this will be done later. Once this PR is in, we will start working on defining the GEM-CSC bending angle in the stub and setting the quality of the Run-3 stubs. The quality will signal to the EMTF what the source is of the stub bending (CSC-only or GEM-CSC).

New LUTs are available here https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/4. 
```
map GEM pad onto CSC 1/8-strip number
GEMCSCLUT_pad_es_ME1a_even.txt
GEMCSCLUT_pad_es_ME1a_odd.txt
GEMCSCLUT_pad_es_ME1b_even.txt
GEMCSCLUT_pad_es_ME1b_odd.txt
GEMCSCLUT_pad_es_ME21_even.txt
GEMCSCLUT_pad_es_ME21_odd.txt

map GEM roll onto CSC minimum and maximum wiregroup number
GEMCSCLUT_roll_max_wg_ME11_even.txt
GEMCSCLUT_roll_max_wg_ME11_odd.txt
GEMCSCLUT_roll_max_wg_ME21_even.txt
GEMCSCLUT_roll_max_wg_ME21_odd.txt
GEMCSCLUT_roll_min_wg_ME11_even.txt
GEMCSCLUT_roll_min_wg_ME11_odd.txt
GEMCSCLUT_roll_min_wg_ME21_even.txt
GEMCSCLUT_roll_min_wg_ME21_odd.txt
```
#### PR validation:

Tested with 23234.0
```
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Nov 24 13:06:31 2020-date Tue Nov 24 12:44:58 2020; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```
There should be no changes in the performance.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
`useRun3Patterns` and `useComparatorCodes` were replaced by the single parameter `runCCLUT` in a previous PR.

**Comment by rekovic** [comment]
please test

**Comment by dildick** [comment]
Hi, can someone restart the tests?

**Comment by dildick** [comment]
@rekovic @jmduarte

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
This is already tested

**Comment by silviodonato** [comment]
+1

**Pull request merged**
