### PR TITLE
Fix dereference of PVOrig (10_2_X)

### PR DESCRIPTION
**Pull request by gpetruc**
backport of #24138

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24143	f23982f
- this is a rather trivial fix, adding a check for ```PVOrig.isNonnull() ``` before dereferencing it. It should affect only previously crashing events.
    - the "backport" is correct: changes are the same as in https://github.com/cms-sw/cmssw/pull/24138	5317f93
- jenkins tests pass
- I'm relying on tests done by @gpetruc in connection with https://its.cern.ch/jira/browse/CMSCOMPPR-3271 to confirm the problem resolution

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
