### PR TITLE
matrix update for relval after 7_1_20_patch2 gensim

### PR DESCRIPTION
**Pull request by hengne**
Updates include:
1.) backport 3 new BPH workflows to replace 3 old ones that have low gen level efficiency. 
2.) change H130 to H125 workflow name due to default mH value in pythia changed.
3.) change to use realistic Beamspot
4.) update gen-sims produced with 7_1_20_patch2 + realBS
5.) update GTs with realistic BS from @mmusich , diff with previous GTs:
-  run2_mc ==> 
  https://cms-conddb.cern.ch/gtList/GTdiff.html?GlobalTag=MCRUN2_71_V1&GlobalTag2=MCRUN2_71_V3
- run2_mc_50ns == > 
  https://cms-conddb.cern.ch/gtList/GTdiff.html?GlobalTag=MCRUN2_71_V0&GlobalTag2=MCRUN2_71_V2
- run2_design ==> 
  https://cms-conddb.cern.ch/gtList/GTdiff.html?GlobalTag=DESRUN2_71_V0&GlobalTag2=DESRUN2_71_V1

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hengne** [comment]
Seems like the error is from Unit test that the file in the following line is missing in CERN EOS:

https://github.com/cms-sw/cmssw/blob/CMSSW_7_1_X/DQM/Physics/test/topDQM_production_cfg.py#L35

Do anybody have any idea how this can be fixed? Thanks!

Best, Hengne

**Comment by fabozzi** [comment]
Maybe you can change the file backporting whta is used in 76X:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DQM/Physics/test/topDQM_production_cfg.py#L37

**Comment by hengne** [comment]
this might not work, if i check that file used in 76x, and i can find the whole folder is empty, e.g. try this at lxplus.cern.ch:
 
eos ls -l /store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/

**Comment by hengne** [comment]
so, maybe 76x also meet the same IB test error?

**Comment by fabozzi** [comment]
Don't know, but I have not seen this error in recent PR tests in 76X or 80X. I see that the old sample was not even available on DAS.
Adding @deguio since it is DQM package

**Comment by hengne** [comment]
My local test of this topDQM test after changing to use the file in 7_6_X also fails due to failure to access the file (even through xrootd):

==> using COND/Services/RelationalAuthenticationService for auth, sys 1
==> using COND/Services/RelationalAuthenticationService for auth, sys 1
06-Nov-2015 16:00:19 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root
151106 16:00:19 18920 Xrd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@06-Nov-2015 16:00:19 CET  Fallback request to file root://xrootd-cms.infn.it//store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root
151106 16:01:24 18922 Xrd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@151106 16:01:29 18922 Xrd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@151106 16:01:29 18922 Xrd^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@----- Begin Fatal Exception 06-Nov-2015 16:01:30 CET-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root'
   Additional Info:
      [a] Input file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root could not be opened.
Fallback Input file root://xrootd-cms.infn.it//store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root also could not be opened.
      [b] XrdClient::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root', flags=0x10, permissions=0666) => error 'No servers are available to read the file.' (errno=3011)
      [c] Current server connection: root://llrxrd-redir.in2p3.fr:1094//store/relval/CMSSW_7_1_0_pre9/RelValTTbarLepton_13/GEN-SIM-RECO/POSTLS171_V11-v1/00000/90D92DC6-67F0-E311-8D2E-0025905A613C.root
----- End Fatal Exception -------------------------------------------------
~

**Comment by franzoni** [comment]
ciao @hengne @fabozzi 

made clear first that the failure "test runtestPhysicsToolsPatAlgos had ERRORS" is not related to this PR,

12A06D7A-F93B-E311-AA64-003048678BEA.root (8 TeV TTbar)
no longer belongs to any dataset (see [1]), I suspect some permanent deletion has taken place since the last time this test was run (un-announced ?)

The file Francesco points to 90D92DC6-67F0-E311-8D2E-0025905A613C.root exists instead [2], I've placed a request to get it back to T2_CH_CERN. [3]

To the DQM colleagues: wouldn't it be in fact necessary to switch these tests to use GEN-SIM with the updated beamspot (subject of the present PR)?


[1]
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+file%3D%2Fstore%2Frelval%2FCMSSW_7_0_0_pre6%2FRelValTTbar%2FGEN-SIM-RECO%2FPRE_ST62_V8-v1%2F00000%2F12A06D7A-F93B-E311-AA64-003048678BEA.root

[2]
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+file%3D%2Fstore%2Frelval%2FCMSSW_7_1_0_pre9%2FRelValTTbarLepton_13%2FGEN-SIM-RECO%2FPOSTLS171_V11-v1%2F00000%2F90D92DC6-67F0-E311-8D2E-0025905A613C.root

[3]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=530842

**Comment by franzoni** [comment]
+1
for AlCa

**Pull request merged**
