### PR TITLE
Run3-sim99 Collapse .h and .cc files in SimG4CMS/EcalTestBeam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Collapse .h and .cc files in SimG4CMS/EcalTestBeam

#### PR validation:

Use standard test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

RelVal problems are unrelated.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
