### PR TITLE
Run3-hcx282 Use ESGetToken in CalibCalorimetry/CastorCalib

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in CalibCalorimetry/CastorCalib

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by yuanchao** [comment]
+1
* replace deprecated get function with ESGetToken
* matrix WF and unit tests all passed
* static build tests warnings are not part of the modifications

**Comment by silviodonato** [comment]
please test
there is a tiny difference in wf 1325.81 related to taus 
`all_OldVSNew_TTbar13nanoEDM106Xv1in2017wf1325p81c_nanoaodFlatTable_tauTable__DQM_obj_floats__rawDeepTau2017v2p1VSmu_442.png`
image

https://github.com/cms-sw/cmssw/pull/32604#issuecomment-754916101

I'm pretty sure that the difference is not related to this PR, but I prefer to double check.

**Comment by silviodonato** [comment]
please abort

**Comment by silviodonato** [comment]
+1
The differences observed are not related to this PR. 
See #32628

**Comment by silviodonato** [comment]
merge

**Pull request merged**
