### PR TITLE
Sonic interface simplifications

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

* Use Python module name from framework for debugging messages
* Include `verbose` parameter in base client
  * I previously avoided this in case someone wanted to implement a less trivial verbosity scheme (e.g. with different levels). But there hasn't been interest in this, and in any case, it can be done just by overriding the module and client `verbose_` flags.

#### PR validation:

Unit tests run successfully.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- technical, reco changes are minimal

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by qliphy** [comment]
+1

**Pull request merged**
