### PR TITLE
MET bugfix for miniAOD + addition of caloMET in slimmedMET

### PR DESCRIPTION
**Pull request by mmarionncern**
This PR fixes the most important bugs observed in miniAODs during the Phys14 exercise.
(NB. the full fix is only complete with #8027 integrated)

Following changes are implemented :
- pat::MET cor and uncorrected functions are deprecated and now retrieve -1, shift function have to be used instead
- MET smearing is disabled per default from the miniAOD production config file.
- protections in the PATMETSlimmer producer have been added to not crash if jet resolution uncertainties are missing (because they are computed and are relevant only when smearing is applied in the current implementation)
- fix of the jet energy scale uncertainty Up/Down variations which were identical
- fix of the unclustered energy scale variation not properly computed due to skimmed jet collection used to compute the type1 and 2 MET correction (unclustered energy scale variation is linked to the type2 MET correction)
- fix a bug during the type1 computation in PAT, due to muon cleaning not properly taken into account
- add basic caloMET information int he slimmedMET class, can be then accessible in one round for experts who wants to have a look at the caloMET

Changes expected during the validation : 
- smearing has been removed from the MET, MET pt resolution will improve compared to the old code implementation
- fix of the muon cleaning for the type1 MET brings back a perfect agreement between the RECO and PAT level. small variations expected in events containing muons.

### CODE REVIEW

**Comment by mmarionncern** [comment]
@cmsbuild , please test

**Comment by gpetruc** [comment]
I think it would be better if the methods `uncorrectedPt` and such were defined so that they call `shiftedPt` with the appropriate argument (i.e. so that the people doing met.uncorrectedPt() gets the raw MET as they're expecting), and other methods be completely removed rather than having them return -1.

**Comment by mmarionncern** [comment]
@gpetruc , uncorrected function now returns the output of shiftedX methods
Removal of other deprecated functions and contents
Now contains the #8027 fix

**Comment by mmarionncern** [comment]
Following @schoef preferency, caloMet source in miniAOD has been switched to muon corrected caloMet

@cmsbuild , please test

**Comment by nclopezo** [comment]
please test

**Comment by arizzi** [comment]
is there a reason why uncertaintiesRaw is now a factor of 2 smaller than it used to be?
http://arizzi.web.cern.ch/arizzi/8159_2k.html#patMETs_slimmedMETs__PAT

**Comment by arizzi** [comment]
Is there a 75X versione of this PR too?

**Comment by mmarionncern** [comment]
@arizzi : the met uncertainty tool never computed real uncertainties for the raw MET (as nobody is supposed to use the uncorrected pfMET for analyses we did not designed the current tool for that, and there is no time to change it. I am currently rewritting it completely, but this will go on a longer timescale). 
Anyway, the conclusion is that for the raw MET all the variations are equal to the central value.

However, when the jet smearing is enabled, it is also propagated to the raw MET. And due to the uniformity of the tool to handle the jetsmearing variations regardless of the considered MET, the JER variations are really computed as well for the raw met, giving non-null shifts fo the JER uncertainties.

So in the previous  there was 11 identical rawMETs + 1 JERUp rawMET + 1 JERDown rawMET.
Now, I removed the smearing, which means you have 13 identical rawMETs.

This is indeed clearly inefficient, but a change of tool and format has to be done and checked carefully, and there is not enough time to do so before closing 74X. The most inportant is that the Type1 MET is now fully self-consistent, with a proper computation of the systematic uncertainties, and with an access to the raw pf/calo MET for expert use.

**Comment by mmarionncern** [comment]
@arizzi If orgot your second question : there is no yet a similar 75X PR but I can prepare it

**Comment by arizzi** [comment]
frankly I do not get it... why are you filling that vector at all then?
There is little to change in the format, it is a vector it can have any
size...  given that you have to explicitelly fill it for 13 different
values I do not understand why you cannot in that place fill it only once.

**Comment by mmarionncern** [comment]
Remember that I am not the one that designed that format at the beginning, not checking what was used as input. 
This PR has been done in emergency this week to fix bugs, and not the format. Even more because we prefer to put the main effort into the new format which unfortunately will not be ready for 740.

**Comment by gpetruc** [comment]
Hi,

@monttj is there anything holding this PR to be integrated in 7_4_X?  (and similarly  #8219 in 7_5_X)

Giovanni

**Comment by monttj** [comment]
+1
no, I don't have an issue with this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
