### PR TITLE
[Fireworks 11_2_X] Add necessary checks for valid hitMap handle in HGCal proxy builders

### PR DESCRIPTION
**Pull request by alja**
#### PR description:
Add a check for valid hitmap handle

### CODE REVIEW

**Comment by alja** [comment]
@rovere 
Please look. It may be you want to handle digit color differently if hitmap is not available.

**Comment by lecriste** [comment]
I have restored the hitMap in
https://github.com/cms-sw/cmssw/pull/31536

**Comment by silviodonato** [comment]
please test with  #31536

**Comment by alja** [comment]
@lecriste Thank you to follow up.
@rovere Please look  #31536 to know the changes.

**Comment by lecriste** [comment]
@alja, @silviodonato, this PR is superseded by #31536 and can be closed - no need to be tested together in my opinion.

**Comment by alja** [comment]
@lecriste Is it possible map  std::unordered_map<DetId, const HGCRecHit*>* hitmap is empty while trying to visualize reco::CaloCluster or  reco::HGCalMultiCluster collections? If so, the two derived proxy builders (FWCaloClusterProxyBuilder and FWHGCalMultiClusterProxyBuilder) need the check for valid hitmap.

**Comment by lecriste** [comment]
> @lecriste Is it possible map std::unordered_map<DetId, const HGCRecHit*>* hitmap is empty while trying to visualize reco::CaloCluster or reco::HGCalMultiCluster collections?

I don't know whether that could happen but I verified that #31536 does not crash also in such a case.

**Comment by alja** [comment]
@lecriste Yes, I see now. I will close this PR.

**Pull request closed without merging**
