### PR TITLE
Fix deprecation warnings in  RecoMuon sub-system

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed to thread-friendly module types
- added missing esConsumes

#### PR validation:

Code compiles without issuing a CMS deprecation warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+reconstruction
technical, no change to reco observed

**Comment by perrotta** [comment]
+1

**Pull request merged**
