### PR TITLE
Add deep flavour of MiniAOD v2 to NANOAOD

### PR DESCRIPTION
**Pull request by arizzi**
last minute forgotten MiniAODv2 feature to be imported in nanoaod

### CODE REVIEW

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
+1

**Comment by arizzi** [comment]
master PR will come tomorrow

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.8,1325.9

**Comment by fabiocos** [comment]
+1

**Pull request merged**
