### PR TITLE
[14_1] Backport 46574: Rework Muon candidate selection in few tracker ALCARECO

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/46574

#### PR validation:
-

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
Thank you @srimanob  for having taken care of the backport!

**Comment by perrotta** [comment]
+alca
- Verbatim backport of #46574, no issues expected from the tests (whose outcomes will be evaluated by the release managers before merging nonetheless, I imagine)
- Computing performance improvement

**Comment by mmusich** [comment]
type performance-improvements

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46574

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
