### PR TITLE
added esConsumes to modules in  RecoEgamma/EgammaPhotonProducers

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 3 modules 

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by JamminJones** [comment]
the following modules were not modified due to the complexity of the modifications needed: ConversionTrackCandidateProducer, GEDPhotonProducer, PhotonProducer, and TrackProdcuerWithSCAssociation. An Expert will be needed in order to make the necessary modifications.

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
