### PR TITLE
bsunanda:Run2-hcx92 Provide additional service of HcalGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
To give exact number of valid DetId's for each type of detector in method getHxSize(int type)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you approve this

**Comment by ianna** [comment]
@bsunanda - just a couple of questions: where is this new accessor going to be used and why  don't use a direct access to HcalTopology?

**Comment by bsunanda** [comment]
@ianna HcalTopology does not have a list of valid DetId's - so to know the number of valid DetId's -it only provides maximum # of DetId's in each category. This method
 is needed in some of the validation packages.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
