### PR TITLE
bsunanda:Run2-hcx85 Correct several scripts to enable them useful yet again

### PR DESCRIPTION
**Pull request by bsunanda**
Make correction to several cf files in SimG4CMS/Calo/test/python
Make bug fix to the TB analyzer of HGCAL

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , in minbias_cfg.py, monopole_cfg.py, runZee_cfg.py, runTestTime_cfg.py, runScale_cfg.py,run_muon_cfg.py, runHFPMT_cfg.py,runHFPMT0_cfg.py,runEta2_cfg.py, runEta7_cfg.py,runEta13_cfg.py,qcdpt3000-3500_cfg.py, ttbar_cfg.py, zee_cfg.py Physics Lists are incorrect. 

To recover, as minimum, one should use QGSP_FTFP_BERT_EML (valid for run-1 and run-2), more correct probably remove PhysicsList definition fro majority of these scripts and left only in a few where this is really needed now. In future you may add 1 line if you remove too much now. Finally, my filling is that there are too many scripts, because generator configuration and Geant4 configuration can be factorised out of calorimeters configurations.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch These tests were very useful to establish quality of simulation in different parts of the calorimeter. I changed the default as the current default. But for each of the scenarios I tend to run with different PL

**Comment by civanch** [comment]
@bsunanda , yes, this is OK to switch to the default and , of course, worse to check results with alternative lists.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
