### PR TITLE
Add missing includes  and remove override identifier for non-virtual functions for CondFormats

### PR DESCRIPTION
**Pull request by oshadura**
### PR description:
Add missing includes for CondFormats libraries and remove override identifier for non-virtual functions. 

CC: @davidlange6 @vgvassilev   

Tested locally with CXXMODULES IBs and these fixes allowed to enable 29 C++ modules (https://github.com/cms-sw/cmsdist/pull/5600).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by vgvassilev** [comment]
This PR is part of #15248

**Comment by davidlange6** [comment]
hi @ggovi, all - any other comments on the small changes proposed?

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
