### PR TITLE
Fix edmPickEvents.py unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
#37208 PR added a timeout of 15 sec for `edmPickEvents.py` . The unit test query takes more than 15s that is why it is now very frequently failing. I have reverted the change in #37208 and updated the unit test script to properly dump the output if  `edmPickEvents.py` fails. 

I also have updated the dataset used for querying das. Now unit test uses the dataset used by workflow `136.8521` . This allows unit test to make use of already cached das results and open already existing data file from ibeos cache

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@qliphy @perrotta this should fix the `edmPickEvents.py` unit test

**Comment by qliphy** [comment]
+1
thanks @smuzaffar

**Comment by qliphy** [comment]
merge

**Comment by smuzaffar** [comment]
@perrotta , yes really strange. I am looking in to it

**Comment by santocch** [comment]
+1

**Pull request merged**
