### PR TITLE
BUGFIX to ME0 SimHit

### PR DESCRIPTION
**Pull request by clacaputo**
ME0NumberingScheme::baseNumberToUnitNumber, argument changed from MuonBaseNumber to MuonBaseNumber&

Added more LogDebug and test files.

Added the ME0 Digi customization.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9526 f27a10959a6e8b77c6d3e709584cb8f017561627

Minor changes and bug fixes for ME0. The only Reco change is the modification or addition of two Python scripts in a GEM "test" directory. There should be no change in standard Reco workflows.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9526/5392/summary.html) against baseline CMSSW_7_5_X_2015-06-08-2300 show no significant differences, as expected. Some of the Jenkins workflows failed for reasons unrelated to this PR, but since this PR makes such minor Reco changes, the failed workflows would be very unlikely to have revealed any problems.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
