### PR TITLE
[backport] Added new filter, thought for a B -> l HNL X analysis

### PR DESCRIPTION
**Pull request by mgratti**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/33308

Needed for an MC production with B-parking conditions.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Comment by mgratti** [comment]
@silviodonato, @dpiparo, @qliphy
I have realized that, while this PR was merged almost a month ago, it was not actually integrated in the latest available 10_2_X release, CMSSW_10_2_26. Could you please comment?

**Comment by qliphy** [comment]
@mgalanti  The last 10_2 release i.e. 10_2_26 was made in early March, so before this PR merged.
https://hypernews.cern.ch/HyperNews/CMS/get/relAnnounce/2185.html
We can make a 10_2_X to include this PR in next days.

**Comment by mgratti** [comment]
Thank you!

**Comment by silviodonato** [comment]
@mgratti https://github.com/cms-sw/cmssw/releases/CMSSW_10_2_26_patch1
will be available if few minutes/hours

**Pull request merged**
