### PR TITLE
Hlt tau validation conditional plotting4

### PR DESCRIPTION
**Pull request by slehti**
Same as HLTTauDQM: conditional plotting #30243, #30701 and #30845

Now hopefully everything fixed.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@slehti there are at least two workflows (11634.0 and 12434.0) which have HLT/TAU plots with no entries now, is this expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-08-11-2300+a52bd0/38308/dqm-histo-comparison-summary.html

**Comment by slehti** [comment]
Checked workflows 11634.0 and 12434.0. Both the baseline and pr histograms have no entries. Why they are reported as changed plots, is probably due to the x-axis, which has changed.

**Comment by jfernan2** [comment]
Blue is baseline, black is your PR, there are entries in blue:
https://tinyurl.com/y39pzzng
https://tinyurl.com/y4e4x9ls

**Comment by slehti** [comment]
For some reason cant open the GUI. However, I can open the rootfiles  
11634.0 baseline rootjs  vs  11634.0 pr rootjs
12434.0 baseline rootjs  vs  12434.0 pr rootjs
and there I see for the same plots as in your tinyurl the same for baseline and pr. Exactly what expected. Perhaps the markers are overlapping in the overlay GUI?
Example for the L1 (11634.0)
http://cmsdoc.cern.ch/~slehti/base.png
http://cmsdoc.cern.ch/~slehti/pr.png

**Comment by jfernan2** [comment]
OK, I see now: what has changed is the number of x bins, hence the number of entries (2 per bin). Thanks

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
