### PR TITLE
Data and MC global tags for 2018 UL

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR includes global tags for the 2018 ultra-legacy reprocessing that are intended to be final. An unrelated change to the Run 3 prompt GT is included; this change is purely technical and will not affect any workflow.

**Offline GT**
Complete set of conditions for 2018UL. Includes updates to beamspot [1-2], tracker alignment [3-5], muon alignment [6-7], ECAL calibrations [8] and a fix for pixel conditions for a single fill with modified HV settings [9].

Diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v5/110X_dataRun2_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_v5/110X_dataRun2_relval_v6

[1] https://indico.cern.ch/event/840920/#35-ul-2018-sign-off-of-beamspo
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4213/1/1/1.html
[3] https://indico.cern.ch/event/837619/#10-ul-2018-tracker-alignment-s 
[4] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4205.html
[5] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4205/1/1.html
[6] https://indico.cern.ch/event/839963/#33-global-position-record-for 
[7] https://indico.cern.ch/event/840920/#34-ul-2018-sign-off-for-muon-a
[8] https://indico.cern.ch/event/840920/#38-ecal-sign-off-for-ultra-leg
[9] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4197.html

**Prompt-like GTs**

Updated PPS conditions for consistency with 2018 UL. The prompt-like GTs are updated as well because the PPS diamond was introduced after the completion of 2018 prompt reco. A payload is needed to avoid crashes in prompt-like workflows and so we have chosen to use payloads consistent with the offline GT.

Diffs: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HEfail_v3/110X_dataRun2_PromptLike_HEfail_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_v3/110X_dataRun2_PromptLike_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HI_v3/110X_dataRun2_PromptLike_HI_v5

**2018 MC**
Complete set of conditions for 2018UL. Updated tracker alignment scenario and APEs [1]

[1] https://indico.cern.ch/event/840920/#36-ul-2018-sign-off-for-mc-tra

Diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_v3/110X_upgrade2018_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HEfail_v3/110X_upgrade2018_realistic_HEfail_v4

**Run 3 prompt**
Change to EcalADCToGeVConstantRcd tag populated by O2O [1]

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4191.html

Diff:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun3_Prompt_v2/106X_dataRun3_Prompt_v3 

#### PR validation:

For physics validation, please see above. Also, as a technical test, ran `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR:

Not a backport but will be backported to 10_6_X

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
There is a problem with the tag `PPSDiamondTimingCalibration_2017_2018_prompt_v1` in the  promptlike global tag. The errors in the three failing tests are equivalent:
```
----- Begin Fatal Exception 04-Sep-2019 01:19:56 CEST-----------------------
An exception of category 'WrongNumParameters' occurred while
   [0] Processing  Event run: 295606 lumi: 1 event: 37589 stream: 3
   [1] Running path 'reconstruction_step'
   [2] Calling method for module CTPPSDiamondRecHitProducer/'ctppsDiamondRecHits'
Exception Message:
FormulaEvaluator expected at least 4 but was passed only 0
----- End Fatal Exception -------------------------------------------------
```
I will follow up with PPS experts.

**Comment by christopheralanwest** [comment]
please test workflow 138.1

**Comment by christopheralanwest** [comment]
+1

- Comparison test differences seen only in 2018 data and MC workflows
- Payloads have been validated individually by subdetector experts, as described in the introduction to this PR

@fabiocos @kpedro88 I suggest merging this PR prior to building 11_0_0_pre7 so that the global tag updates that complete the 2018 UL preparation enter the standard release validation

**Comment by fabiocos** [comment]
+1

**Pull request merged**
