### PR TITLE
Use gain dependent ToT thresholds for HGC digitization

### PR DESCRIPTION
**Pull request by ttrk**
#### PR description:
The time-over-threshold mode is enabled depending on the gain parameter applied for the sensor. See [1] for the impact of changes.

[1] : https://indico.cern.ch/event/1049055/contributions/4409458/attachments/2265641/3846729/210616_HGC_DPG_dynamic_ADC_TOT.pdf
#### PR validation:

Passed WF 23234.103 in 12_0_0_pre3.

@pfs

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
