### PR TITLE
Add ECAL DCC desync DQM trend plots and update the DQM threshold for Integrity summary

### PR DESCRIPTION
**Pull request by kyungminparkdrums**
#### PR description:

This PR includes two changes related to ECAL DQM:
[1] Adding the ECAL DQM plots for the trend of DCC-SRP and DCC-TCC desync in ECAL DQM (in `Layout/01 Raw Data` and `Layout/11 Trend`).
[2] Update the DQM threshold for the integrity summary for ECAL supermodule, such that if more than 1% of the supermodule has DCC-SRP or DCC-TCC desync errors it is flagged as bad (previous threshold: more than 50 desync errors).

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is the Master PR. Backports are made to `14_0_13` in PR #45761

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

- @kyungminparkdrums , could you please open a backport to `CMSSW_14_1_X` ? Thanks!

**Comment by mandrenguyen** [comment]
+1

**Comment by kyungminparkdrums** [comment]
@tjavaid The PR for the backport to `14_1_X` is open here: https://github.com/cms-sw/cmssw/pull/45933

**Pull request merged**
