### PR TITLE
update relval input strings

### PR DESCRIPTION
**Pull request by prebello**
this PR aims to update input relval strings (reclycled from 10_2_0 release) for FullSim and FastSim relvals.

FYI @fabozzi

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by fabozzi** [comment]
@prebello : 
in the following line:
https://github.com/cms-sw/cmssw/pull/23955
https://github.com/prebello/cmssw/blob/b9c4711b9971af7b4c9ed6d2181730b340b87128/Configuration/PyReleaseValidation/python/relval_steps.py#L2537

please remove the following part, since in 10_2_0 we do not have "v2" 2018 gensim:
'SingleGammaPt35_pythia8_2018':'2','SingleMuPt10_pythia8_2018':'2','SingleMuPt100_pythia8_2018':'2','SingleMuPt1000_pythia8_2018':'2'

Thanks!

FYI: @akssikdar

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
@prebello can you make a backport to 102X as well?

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
