### PR TITLE
Remove obsolete timing modules

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmssw, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
`git-cms-checkdeps` does not find any dependencies; is there any way to check that these modules are not actually used anywhere ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
