### PR TITLE
Add HI jet histograms to offline DQM for pp_on_AA_2018 era

### PR DESCRIPTION
**Pull request by jusaviin**
In this PR the JetMET pp offline DMQ sequence is replaced by HI JetMET sequence if the era is pp_on_AA_2018. There are also small updates on JetMET files to make things work in this new era.

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi Jussi,

I can't seem to find you in the DQM Contacts list. Could you please introduce yourself shortly?

**Comment by stepobr** [comment]
Hi Andrius, just to speed things up - Jussi has pledged in PPD/DQM-DC/Heavy Ion online & offline DQM. He's working in the Heavy Ion group and the task is to fix the jet part in DQM for upcoming PbPb data-taking.

**Comment by fioriNTU** [comment]
Dear @stepobr and @BetterWang , Andrius is following the standard procedure in PR integration, any DQM developer should introduce himself to the DQM core team **before**  submitting any PR.  We are bookkeping a list of contacts at https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts ,  if you foresee other people, not yet included in the page, to make any development, please provide us the name, e-mail and github username at cms-dqm-coreTeam@cern.ch Sorry for the "extra work" but this save a lot of time to our PR reviewer

**Comment by andrius-k** [comment]
+1

**Comment by boudoul** [comment]
Hello , was the commit from @BetterWang eventually picked up ?

**Comment by jusaviin** [comment]
Hello. Sorry for the delay in answer, I was on travel from CERN back to US. I now added the update from @BetterWang to the PR.

For the introduction: thanks for Stepan and Quan for filling the basics. I could add that I did my PhD in the ALICE experiment and now got a post doc position March this year from the UIC group in CMS. I have been assigned to do this service task to update the jet DQM histograms for the heavy ion run. This is my first time ever working with CMSSW, so I'm still learning how to do things in this framework.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@jusaviin the memory addition is quite sizeable, although manageable. Do you foresee further additions? Is this size justified by the simultaneous check of multiple

**Comment by jusaviin** [comment]
We are currently discussing if one more type of histograms needs to be added to some of the jet collections. Depending on the decision that hopefully will come later this week, a small addition might be needed.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
