### PR TITLE
Switch random engine to MixMax

### PR DESCRIPTION
**Pull request by civanch**
New random number generator MIXMAX has better properties and is thread safe. It is proposed to be CMS default. The simulation histories will be different, so only statistical comparison of results is possible.
This PR is proposed for testing but should be merged at appropriate moment.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@fabiocos , this PR was tested in parallel with #22145. A very good statistical agreement is observed versus the baseline.

**Comment by davidlange6** [comment]
I agree -its easy to find distributions that statistically disagree - can be just from different events in the gen level, but should be confirmed.

**Comment by civanch** [comment]
I think, that the agreement should be improved with statistics, at least, for 10000 MinBias events I see very similar distributions. Here we have much lower statistics.

**Comment by Dr15Jones** [comment]
+1
The technical change is just fine.
@fabiocos I do not think this is something core can decide upon.

**Comment by fabiocos** [comment]
@Dr15Jones I just would like to see a general test comparison done on a relatively large number of events, for although I assume that there should be no problem. Vladimir states he has tested this a SimHits level, I think one should just run something like 10823 or 10824 on some 10k events and make a standard RelMon comparison. I am trying to do it...

**Comment by fabiocos** [comment]
A cross check with some 9.5 k MinBias confirms that at hit level no statistically significant difference can be noticed (I attach a semi-random selection of plots checked):

image
image
image

and this propagates to digis:

image

**Comment by fabiocos** [comment]
+1

**Pull request merged**
