### PR TITLE
Phase-2 GT interface update and slice test pattern writers

### PR DESCRIPTION
**Pull request by HaarigerHarald**
#### PR description:

This includes a small interface update specifically GTT sums and an update to the muon interface after #44498.

Additionally it contains the pattern writers for the slice tests, which were already successfully employed during GMT slice tests and will be used during GTT slice tests.

A minor addition of a pt multiplicity cut is also included.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by aloeliger** [comment]
+l1

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
@cmsbuild please test

Re-trigger the test after 2 weeks, to see failure comparison.

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
