### PR TITLE
[12_1_X] Add PilotBeam data in relval matrix and update Run3 data offline GT

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR is partially a backport of #36133 since it adds the PilotBeam data to the relval matrix workflows, and partially a backport of #36326 since it contains updates to the offline Run3 data GT in preparation for the re-reco.

Changes are:
 - Offline Run3 data GT is updated in preparation of the PilotBeams2021 re-reco
 - Added wfs: `136.899, 138.4, 138.5, 139.001, 139.002, 139.003, 139.004`, see #36133 for more details
 -  a modifier `'--procModifiers':'siPixelQualityRawToDigi'` is added in step3 of the 139.00* workflows (MinBias, ZeroBias and HLTPhysics) to pick up the new tag included in the GT following changes introduced in #36286

Diff in GT:
**Run 3 data (offline)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_v8/121X_dataRun3_v12

#### PR validation:
Validated with:
`runTheMatrix.py -l 136.897,136.899,138.1,138.2,138.3,138.4,138.5,139.001,139.002,139.003,139.004 -j8 --ibeos`

#### Backport:
Partial backport of #36133 and #36326

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36133

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36326

**Comment by francescobrivio** [comment]
urgent

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 136.897,136.899,138.1,138.2,138.3,138.4,138.5,139.001,139.002,139.003,139.004

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by jfernan2** [comment]
+1

**Comment by kskovpen** [comment]
+1

**Comment by francescobrivio** [comment]
Thanks to all for the prompt signature, I let my colleagues @malbouis or @tvami add the _alca_ signature.
@cms-sw/l1-l2 a kind ping, your signature is required because the same updates to L1T configs as in #36133 are applied here in this backport.

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
@perrotta @qliphy since this is a backport, maybe we can again skip the L1T signiture? There is a L1T signiture on the master PR so I'm sure Vladimir agrees.

**Comment by perrotta** [comment]
+1
- It fully backports #36133 (Add PilotBeam data in relval matrix tests), merged in master since a while already
- From #36326 it only imports the autoCond mofications for Run3 data, which are needed for the re-reco of the pilot beam data. It does not import the modifications to the PPS geometry, instead.

**Comment by perrotta** [comment]
merge
(@cms-sw/l1-l2 already signed the PRs in master...)

**Pull request merged**
