### PR TITLE
Report # events per Lumi for output files in framework job report

### PR DESCRIPTION
**Pull request by Dr15Jones**
DMWM needs to obtain the number of events written per LuminosityBlock for each output file.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@ericvaandering

**Comment by davidlange6** [comment]
+1

**Comment by ericvaandering** [comment]
Since this is so minor, any chance of backports to other releases?

**Comment by Dr15Jones** [comment]
@davidlange6 WMDM would like me to backport this to all production release branches. I'm afraid I've lost track of which branches are still used for production. Could you remind me?

**Comment by ericvaandering** [comment]
Is Liz's dyslexia infecting you? DMWM

**Pull request merged**
