### PR TITLE
Migrate Validation/Geometry to D92

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR provided fix of unit test after https://github.com/cms-sw/cmssw/pull/38702 was merged. Discussion is in https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1261879490

#### PR validation:
None. To be tested with https://github.com/cms-sw/cmssw/pull/39571 and https://github.com/cms-sw/cmssw/pull/39572

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport and no need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
Full test is done in https://github.com/cms-sw/cmssw/pull/39571#issuecomment-1266486468

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cms-sw/geometry-l2 @cms-sw/dqm-l2 with this (simple) fix the unit test materialBudgetHGCalPlot now succeed, instead of failing as in the IBs. Would you agree signing, so that this fix can be included already in pre3?

**Comment by civanch** [comment]
+1

fixes are obvious

**Comment by perrotta** [comment]
+1
- I agree with @civanch that these fixes are obvious: let me superseed the @cms-sw/dqm-l2 signature here, then, so that we can try to recover a few red buttons in the IB test pages

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
