### PR TITLE
[CORE] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please tes

**Comment by makortel** [comment]
The `TestDQMOfflineConfigurationGotAll` failed with
```
+ echo 'Final DQMOfflineConfiguration should not run any sequences.'
Final DQMOfflineConfiguration should not run any sequences.
+ echo 'Please update parameters for TestDQMOfflineConfiguration unittest to run the extra sequences.'
Please update parameters for TestDQMOfflineConfiguration unittest to run the extra sequences.
```
The cause is not immediately clear to me

**Comment by iarspider** [comment]
> `TestDQMOfflineConfigurationGotAll`

https://github.com/cms-sw/cmssw/pull/46791

**Comment by smuzaffar** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
