### PR TITLE
[124X backport] Add GEM recHits and segments to AlCaRecos

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

Backport of [38859](https://github.com/cms-sw/cmssw/pull/38859)

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38859

**Comment by tvami** [comment]
test parameters:
 * workflows = 1001.3,1002.3

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type gem,bugfix

**Comment by ChrisMisan** [comment]
+alca
- pr in line with the description
- tests pass, new collections were created successfully
- size increase was discussed in the main pr
- differences are only in MTD and msgLogger

**Comment by qliphy** [comment]
+1

**Pull request merged**
