### PR TITLE
add tracking monitoring to online beam spot

### PR DESCRIPTION
**Pull request by mtosi**
as requested by tracking POG (@VinInn  and @rovere )
the tracking monitor of tracks used by the online beam spot measurement application is needed

### CODE REVIEW

**Comment by mtosi** [comment]
this PR should go on top of https://github.com/cms-sw/cmssw/pull/19034

**Comment by dmitrijus** [comment]
@mtosi Is there a PR to master branch of this?

**Comment by mtosi** [comment]
no yet :(
@hreus told me we need it for the upcoming days
I'll work on it tomorrow

**Comment by mtosi** [comment]
https://github.com/cms-sw/cmssw/pull/19132 ;)

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
@mtosi should this PR be closed? Thanks

**Comment by mtosi** [comment]
I was not remember about this !
thanks !
the monitoring is already in place, I think thanks to #19132
=> I'm closing this

**Pull request closed without merging**
