### PR TITLE
Fix for proper separation of the ZDCP and ZDCM triggers in the uGT

### PR DESCRIPTION
**Pull request by elfontan**
#### PR description:
Bug fix related to the uGT emulator changes for ZDC triggers (https://github.com/cms-sw/cmssw/pull/42634) in view of the 2023 HI data-taking.

The countings from ZDCP and ZDCM were the same because the type of the `m_gtEnergySumZdcTemplate` (containing the information parsed by the menu about the type of the ZDC EtSum, Plus or Minus) was not properly checked. 

#### PR validation:
A complete test have been performed in CMSSW_13_2_3 following the recipe below (documented in the [ZDCL1TEmulator twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/ZDCL1TEmulator)):
```
cmsrel CMSSW_13_2_3
cd CMSSW_13_2_3/src
cmsenv
git cms-init
git remote add cms-l1t-offline https://github.com/cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline l1t-integration-CMSSW_13_2_0_pre3
git cms-merge-topic -u cms-l1t-offline:l1t-integration-v164-CMSSW_13_2_0_pre3
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter.git L1Trigger/L1TCalorimeter/data
git cms-addpkg L1Trigger/L1TCommon
git cms-addpkg L1Trigger/L1TGlobal
git cms-addpkg L1Trigger/Configuration
git cms-addpkg L1Trigger/L1TZDC
mkdir L1Trigger/L1TZDC/data
cd L1Trigger/L1TZDC/data
wget https://raw.githubusercontent.com/cms-data/L1Trigger-L1TCalorimeter/master/zdcLUT_HI_v0_1.txt
cd -
mkdir -p L1Trigger/L1TGlobal/data/Luminosity/startup/
cd L1Trigger/L1TGlobal/data/Luminosity/startup/
wget https://raw.githubusercontent.com/mitaylor/HIMenus/main/Menus/L1Menu_CollisionsHeavyIons2023_v1_1_0.xml
cd -
git cms-checkdeps -A -a
scram b -j 8
```
and manually adding to the configuration file the following lines:
```
process.etSumZdcProducer = cms.EDProducer('L1TZDCProducer',
  zdcDigis = cms.InputTag("hcalDigis", "ZDC")
)

process.etSumZdc = cms.Path(process.etSumZdcProducer)
process.schedule.append(process.etSumZdc)
```
Countings from different ZDC seeds (Plus and Minus) are now different. See a quick test on 1000 events based on `/store/user/shuaiy/RiceHIN/L1Emulator/SkimedZeroBias_HIRun2018A_v1_RAW_run326776/HIForward/SkimedZeroBias_HIRun2018A_v1_RAW_run326776/201228_010151/0000/skimedZeroBias_1.root`:
- BEFORE FIX:
```
500  L1_ZDCP1  1000
502  L1_ZDCP512  59
505  L1_ZDCM512  59
```
- AFTER FIX:
```
500  L1_ZDCP1  1000
502  L1_ZDCP512  67
505  L1_ZDCM512  59
```
A cross-check with the expected countings from the standalone framework of the HI group was successfully performed on a larger statistics. 

The PR has been prepared starting from CMSSW_13_3_X_2023-09-13-1100:
```
cmsrel CMSSW_13_3_X_2023-09-13-1100
cd CMSSW_13_3_X_2023-09-13-1100/src
cmsenv
git cms-init
git cms-addpkg L1Trigger/L1TGlobal
scram b && scram b code-checks && scram b code-format && scram b
```

Backport to CMSSW_13_2_X needed for the HI data-taking: https://github.com/cms-sw/cmssw/pull/42781.

[cc: @hjbossi @cfmcginn @ginnocen @icali]

### CODE REVIEW

**Comment by aloeliger** [comment]
urgent

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
