### PR TITLE
92x - Present Calo conditions used at p5, for v2 L1 menu and post-MD2.

### PR DESCRIPTION
**Pull request by rekovic**
backport of https://github.com/cms-sw/cmssw/pull/19929

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3316

**Comment by smuzaffar** [comment]
@rekovic , this PR for CMSSW_9_2_X which cmsdist Pr is for 93X. so this will not work.
We fist need to get the changes in 93X and then backport them to 92X.

**Comment by arunhep** [comment]
@rekovic please cherry-pick the following commit https://github.com/arunhep/cmssw/commit/2c6f178de0d2ed78358bb3b5ee284815e6100018
which contains the GT updates for 2017 MC to remove 0.7 factor from HF TPs.
@franzoni

**Comment by rekovic** [comment]
@smuzaffar 
>@rekovic , this PR for CMSSW_9_2_X which cmsdist Pr is for 93X. so this will not work.
We fist need to get the changes in 93X and then backport them to 92X.

OK. Will wait.

**Comment by rekovic** [comment]
@arunhep  Thx. 
Done.

**Comment by davidlange6** [comment]
please test

**Comment by arunhep** [comment]
@rekovic here is the commit for including latest JECs for HLT : https://github.com/arunhep/cmssw/commit/b98b4eeb83f2d01bac413110162031b1e028b2d5
@franzoni

**Comment by rekovic** [comment]
@davidlange6 
Apparently, testing will require a backport of external PRs (alike 93x cms-sw/cmsdist#3316)

**Comment by davidlange6** [comment]
please test

**Comment by arunhep** [comment]
# Summary of changes in Global Tags 
 
## 2017 MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [92X_upgrade2017cosmics_realistic_peak_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v10) as [92X_upgrade2017cosmics_realistic_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v10/92X_upgrade2017cosmics_realistic_peak_v8): 
      * remove of HF  TP scale factor 0.7 from HCALLUTs : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2977.html
      * Update of JECs@HLT to the ones currently running for data-taking: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3091.html

   * **PhaseI 2017 cosmics scenario** : [92X_upgrade2017cosmics_realistic_deco_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v10) as [92X_upgrade2017cosmics_realistic_deco_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v10/92X_upgrade2017cosmics_realistic_deco_v8): 
      * remove of HF  TP scale factor 0.7 from HCALLUTs : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2977.html
      * Update of JECs@HLT to the ones currently running for data-taking: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3091.html

   * **PhaseI 2017 design scenario** : [92X_upgrade2017_design_IdealBS_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v10) as [92X_upgrade2017_design_IdealBS_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_design_IdealBS_v10/92X_upgrade2017_design_IdealBS_v8): 
      * remove of HF  TP scale factor 0.7 from HCALLUTs : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2977.html
      * Update of JECs@HLT to the ones currently running for data-taking: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3091.html

   * **PhaseI 2017 realistic scenario** : [92X_upgrade2017_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v10) as [92X_upgrade2017_realistic_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v10/92X_upgrade2017_realistic_v8): 
      * remove of HF  TP scale factor 0.7 from HCALLUTs : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2977.html
      * Update of JECs@HLT to the ones currently running for data-taking: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3091.html

**Comment by arunhep** [comment]
when this PR can be tested? its 93X version #19929 has been merged already.

**Comment by rekovic** [comment]
@smuzaffar 
> @rekovic , this PR for CMSSW_9_2_X which cmsdist Pr is for 93X. so this will not work.
We fist need to get the changes in 93X and then backport them to 92X.

Can we get the cmsdist for this 92X to provide us with externals?  
93X PR has been merged last week.

**Comment by smuzaffar** [comment]
@rekovic , you can use cms-sw/cmsdist#3322 for 92X

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3322

**Comment by arunhep** [comment]
@rekovic when will the internal validation be available? its hard to see the changes on 10 events.
I see changes only in relevant directories.

changes in wf136.731 for data comes only from this PR and not from condition changes in GT.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-08-01-1100+19930/21706/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/L1T_L1TStage2CaloLayer2.html

can you please confirm this?

**Comment by davidlange6** [comment]
hi @rekovic - should we go ahead with 928 without this or will the various issues (printouts, validation, multiplicity of similar cffs) all be addressed by this afternoon?

**Comment by rekovic** [comment]
@davidlange6 
This has been validated. Sent the report and added you in the thread afterwards.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by arunhep** [comment]
+1

**Pull request merged**
