### PR TITLE
Removed use of deprecated code in DQMOffline/PFTau

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Removed use of legacy module.
- Removed unnecessary include of deprecated header.

#### PR validation:

Code compiles and no deprecation warnings occur for the package.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
