### PR TITLE
Add more pixel payload inspections

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is expand the set of Pixel conditions browsable with the Payload Inspector.
It adds inspectors for:
   * `SiPixelQualityProbabilities`
   * `SiPixelFEDChannelContainer`
   * `SiPixel2DTemplateDBObject`

I profit of this PR to add a `README` file for the package   
   
#### PR validation:

Run successfully the unit tests of this package as well as private testing of the added plots.
Example plot obtained with:
```bash
 getPayloadData.py \
     --plugin pluginSiPixelFEDChannelContainer_PayloadInspector \
     --plot plot_SiPixelFEDChannelContainerTest \
     --tag SiPixelStatusScenarios_UltraLegacy2018_v0_mc \
     --time_type Run --iovs '{"start_iov": "1", "end_iov" : "1"}' \
     --db Prod \
     --input_params '{"Scenarios":"320824_103,316758_983,320934_254"}' \
     --test ;
```
001eb939-bb2a-4620-a569-480bdb2dc8f3
and example plot obtained with: 
```bash
getPayloadData.py \
    --plugin pluginSiPixelFEDChannelContainer_PayloadInspector \
    --plot plot_SiPixelFEDChannelContainerScenarios \
    --tag SiPixelStatusScenarios_UltraLegacy2017_v0_mc \
    --time_type Run --iovs '{"start_iov": "1", "end_iov" : "1"}' \
    --db Prod \
    --test ;
```
image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
kind reminder @ggovi

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
@mmusich  the test results show "CMSSW code rules violation":
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e701f/13281/summary.html
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e701f/13281/codeRules/cmsCodeRule1.txt

Can you have a check?  You may also refer to https://github.com/cms-sw/cmssw/pull/25301

**Comment by mmusich** [comment]
@qliphy 

>  the test results show "CMSSW code rules violation":
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e701f/13281/summary.html
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e701f/13281/codeRules/cmsCodeRule1.txt

> Can you have a check? You may also refer to #25301

few remarks:

1. I didn't add the `namespace` in the current PR, It was already included in the baseline:  https://github.com/cms-sw/cmssw/blob/835a0cf070f05c242c7b75015d49a280c3f51db9/CondCore/SiPixelPlugins/interface/SiPixelTemplateHelper.h#L31  
2. obeying the rule would in my opinion clutter the file with a lot of `cond::payloadInspector` that would make the file less readable.
3. I have another branch that I should submit as a PR shortly that is touching this same package. As this PR is already signed in the interest of saving time, can we merge it as is? I'll propose changes in the subsequent one.

Thank  you

**Comment by qliphy** [comment]
Thanks @mmusich 
I think your point make sense.  Adding @silviodonato who may comment more or move forward this PR.

**Comment by silviodonato** [comment]
`using namespace cond::payloadInspector; ` was already there, so I'm ok with this PR.

**Comment by silviodonato** [comment]
PS. the `using namespace` is inside a namespace scope. This should prevent `using namespace` from having "long-range" effects, so we should not be worried about this.

**Pull request merged**
