### PR TITLE
Towards the first hlt menu for 2016 - 80X

### PR DESCRIPTION
**Pull request by perrotta**
Starting HLT menu for 2016.
This PR replaces #14427, which had problems of mergeability.
Based on CMSSW_8_0_6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@perrotta 
Looks like you did not update the 80X branch - why?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
This PR is updated in synchro wiith its 81X version.
It will however keep failing when tested until the GT fixes in #14281 are not merged

**Comment by Martin-Grunewald** [comment]
Ah yes! Another PR stuck...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Oh well, #14281 is still not integrated in 80X.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I can't reproduce this error running the addOn tests offline!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
