### PR TITLE
Rct to digi

### PR DESCRIPTION
**Pull request by mulhearn**
This is the 76X verison of #9931.

This code is not included in any standard work flows.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by isobelojalvo** [comment]
This is strange, it passed this check for 75X.

**Comment by mulhearn** [comment]
please test

**Comment by isobelojalvo** [comment]
Hi, Is there anything I can do about this?

**Comment by mulhearn** [comment]
@isobelojalvo I don't see why these tests didn't run.  I am going to restart them.  I don't think there is anything wrong with the PR.

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
@degano  is there something going wrong with the Jenkin's test?  I can't seem to get these to rerun for this PR?!  Any idea what is going on here?

**Pull request merged**
