### PR TITLE
HLT phase-2: fix HGCAL Layercluster and create common constants configuration for HGCAL

### PR DESCRIPTION
**Pull request by felicepantaleo**
This PR fixes a bug where the value of fCperElectron was accidentally set to `0`. This caused noise hits to seed the creation of layerclusters.
In this PR I have moved all the constants to a common file, so it's easier to maintain. 
I have also updated the constants to Calorimeter Geometry v16.

@rovere @SohamBhattacharya @waredjeb fyi

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
type bug-fix

**Comment by mmusich** [comment]
type hgcal

**Comment by mmusich** [comment]
+hlt
   * bug-fix seems uncontroversial

**Comment by mmusich** [comment]
@felicepantaleo please open a backport to 14.0.x as well

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
