### PR TITLE
80X: MC updates for trancheIV

### PR DESCRIPTION
**Pull request by mmusich**
- See: [Talk at PPD general 11.08.2016](https://indico.cern.ch/event/562065/contributions/2270369/)
- Changes in Physics performance for Tranche-IV 2016 MC production are expected
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v19) as [80X_mcRun2_design_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v19/80X_mcRun2_design_v17): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Jet Energy Corrections to Spring16_25nsV6 version
  - updated/add Jet Energy resolution / resolution scale factor to Spring16_25nsV6 version 
  - updated btag Jet Probability tagger calibration for BTV HIP mitigation
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v19) as [80X_mcRun2_asymptotic_Candidate_2016_09_02_09_21_09](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_Candidate_2016_09_02_09_21_09) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v19/80X_mcRun2_asymptotic_Candidate_2016_09_02_09_21_09): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Tracker Alignment fixing z-shrinkage effect  
  - updated Jet Energy Corrections to Spring16_25nsV6 
  - updated Beamspot for new Tracker alignment 
  - updated Btag Jet Probability tagger calibration for BTV HIP mitigation
- **RunII Startup scenario** : [80X_mcRun2_startup_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v18) as [80X_mcRun2_startup_Candidate_2016_09_02_09_19_47](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_Candidate_2016_09_02_09_19_47) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v18/80X_mcRun2_startup_Candidate_2016_09_02_09_19_47): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
- **RunII Proton-Lead scenario** : [80X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_pA_v1) as [80X_mcRun2_pA_Candidate_2016_09_02_10_22_08](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_pA_Candidate_2016_09_02_10_22_08) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_pA_v1/80X_mcRun2_pA_Candidate_2016_09_02_10_22_08): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Tracker Alignment fixing z-shrinkage effect  
  - updated Jet Energy Corrections to Spring16_25nsV6 
  - updated Beamspot for new Tracker alignment 
  - updated Btag Jet Probability tagger calibration for BTV HIP mitigation
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v17) as [80X_mcRun2cosmics_startup_peak_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v17/80X_mcRun2cosmics_startup_peak_v15): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v12) as [80X_mcRun2_HeavyIon_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v12/80X_mcRun2_HeavyIon_v10): 
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Btag Jet Probability tagger calibration for BTV HIP mitigation
## Upgrade
- **PhaseI realistic scenario** : [80X_upgrade2017_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_realistic_v9) as [80X_upgrade2017_realistic_Candidate_2016_09_02_10_24_47](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_realistic_Candidate_2016_09_02_10_24_47) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_realistic_v9/80X_upgrade2017_realistic_Candidate_2016_09_02_10_24_47): 
  - updated AlCaRecoTriggerBits for EcalTrg AlCaReco
  - updated MC pulse shape for HB iPhi=+54 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Btag Jet Probability tagger calibration for BTV HIP mitigation
  - updated Jet Energy Corrections to Spring16_25nsV6 
- **PhaseI design scenario** : [80X_upgrade2017_design_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v17) as [80X_upgrade2017_design_Candidate_2016_09_02_10_25_48](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_Candidate_2016_09_02_10_25_48) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v17/80X_upgrade2017_design_Candidate_2016_09_02_10_25_48): 
  - updated AlCaRecoTriggerBits for EcalTrg AlCaReco
  - updated MC pulse shape for HB iPhi=+54 
  - updated Btag Jet Probability tagger calibration for BTV HIP mitigation
  - updated Jet Energy Corrections to Spring16_25nsV6

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
hold 
- some of the changes need to be improved / rolled back depending on the outcome of the ` 8_0_16_Tranch4GT_v2` [validation campaing](https://cms-conddb.cern.ch/PdmV/valdb/?srch=Tranch&selected=8_0_16_Tranch4GT,8_0_16_Tranch4GT_pmx,8_0_16_Tranch4GT_v2&Reconstruction=true&RFull=true)

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
   * all needed conditions updates for Tranche-IV MC production (excepted updated L1 menu) included in this PR

**Comment by davidlange6** [comment]
+1

**Pull request merged**
