### PR TITLE
Checksum parameter cfi export (76X)

### PR DESCRIPTION
**Pull request by smorovic**
CRC32 is checked by default, however parameter to control this is not exported.

We need a way to switch this off in heavy ion test setup, so two changes are provided:
- export of the parameter (for the new template)
- reuse adler32 setting as default (as we replaced adler32 with crc32c, for existing templates).

Also, two other not previously exported parameters were added to cfi files, and input source parameter defaults were changed to defaults used in production.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #11535 e1b814d567a9ea7cac4bc2841428098c3bebadf8

For Heavy Ions, exporting checksum parameter so it can be toggled as necessary.  There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11535/8456/summary.html) against baseline CMSSW_7_6_X_2015-09-27-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
