### PR TITLE
Puppi isolation miniAOD electrons & photons

### PR DESCRIPTION
**Pull request by ishvetso**
this is effectively a copy of #15722, history of commits cleaned

### CODE REVIEW

**Comment by ishvetso** [comment]
there is one feature to be added as was discussed: add associatedPackedPFCandidates() to reco::Photon. Do we have to do that for reco::Electron as well?

**Comment by gpetruc** [comment]
For the change to the PAT producers, I think it would be good to add also one parameter `addPuppiIsolation` that can be set to true to turn the feature on or false to turn the feature off 
(in the latter case, you can skip the consumes and getByToken, and fill the variables with zeros or -999)

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
please test

**Comment by ishvetso** [comment]
There is an update related to associatedPackedPFCandidates(). However, I get the compilation error:
 In member function 'virtual void ReducedEGProducer::produce(edm::Event&, const edm::EventSetup&)':
/afs/cern.ch/work/i/ishvetso/EgammaWork/for_PR_electrons_v7/CMSSW_8_1_X_2016-09-05-1200/src/RecoEgamma/EgammaPhotonProducers/src/ReducedEGProducer.cc:352:117: error: passing 'const reco::Photon' as 'this' argument discards qualifiers [-fpermissive]
     photon.setAssociatedPackedPFCandidates(edm::RefProd<pat::PackedCandidateCollection>(pc),keys.begin(), keys.end());    
                                                                                                                     ^
In file included from /afs/cern.ch/work/i/ishvetso/EgammaWork/for_PR_electrons_v7/CMSSW_8_1_X_2016-09-05-1200/src/RecoEgamma/EgammaPhotonProducers/src/ReducedEGProducer.cc:22:0:
/afs/cern.ch/work/i/ishvetso/EgammaWork/for_PR_electrons_v7/CMSSW_8_1_X_2016-09-05-1200/src/DataFormats/EgammaCandidates/interface/Photon.h:143:10: note:   in call to 'void reco::Photon::setAssociatedPackedPFCandidates(const edm::RefProd<std::vector<pat::PackedCandidate> >&, T, T) [with T = __gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int> >]'
     void setAssociatedPackedPFCandidates(const edm::RefProd<pat::PackedCandidateCollection> & refprod,

any ideas?

**Comment by monttj** [comment]
Apart from the error message, RECO should not have dependency on PAT. 
Once PAT (miniAOD) is data tier, I am not sure if this is unavoidable. 
But miniAOD is still the one which will be updated more frequently than RECO. So this could possibly break the consistency in RECO later? 

Regards,
Taejeong

**Comment by slava77** [comment]
BTW, looks like I need to repeat my comment for the third time from 
https://github.com/cms-sw/cmssw/pull/15628#discussion_r77454488

```
[associatedPackedPFCandidates] will not be a member method of reco::Photon ...
```
"will NOT"
reco::Photon should be left unchanged

**Comment by ishvetso** [comment]
@slava77  I didn't understand what is the exact suggestion. if we need to access associatedPackedPFCandidates for reco::Photon, I don't see any other way as to introduce associatedPackedPFCandidates() to reco::Photon.

**Comment by slava77** [comment]
On 9/9/16 1:09 AM, Ivan Shvetsov wrote:
> @slava77 <https://github.com/slava77> I didn't understand what is the
> exact suggestion. if we need to access associatedPackedPFCandidates for
> reco::Photon, I don't see any other way as to introduce
> associatedPackedPFCandidates() to reco::Photon.

reco::Photon is logically an upstream object with respect to associated
packed candidates.
So, there is no need for it to know of possible downstream information
derived after its creation.

you can compute the list of associated packed candidates per reco::Photon
either on the fly in the modules that need this information
or make a new module that would write an association container of packed
candidate pointers per reco::Photon.

**Comment by ishvetso** [comment]
09.09.16 20:24, Slava Krutelyov пишет:
> On 9/9/16 1:09 AM, Ivan Shvetsov wrote:
> > @slava77 <https://github.com/slava77> I didn't understand what is the
> > exact suggestion. if we need to access associatedPackedPFCandidates for
> > reco::Photon, I don't see any other way as to introduce
> > associatedPackedPFCandidates() to reco::Photon.
>
> reco::Photon is logically an upstream object with respect to associated
> packed candidates.
> So, there is no need for it to know of possible downstream information
> derived after its creation.
>
> you can compute the list of associated packed candidates per reco::Photon
> either on the fly in the modules that need this information
> or make a new module that would write an association container of packed
> candidate pointers per reco::Photon.
>
so in the end that means a ValueMap, right? and then changing this in 
CITK ...

**Comment by slava77** [comment]
either a value map or compute it on the fly.

**Review by dmitrijus — APPROVED** [review]

**Comment by slava77** [comment]
@ishvetso 
please update on the status of this PR

**Comment by ishvetso** [comment]
sorry, no update so far, probably later this week.

**Comment by slava77** [comment]
-1
superseded by #16055

**Pull request closed without merging**
