### PR TITLE
[DQM] Fixed UnitTest crashes in ASAN

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR fixes 4 UnitTest crashes detected with ASAN in https://github.com/cms-sw/cmssw/pull/36249#issuecomment-979758151

Three of them are related to vectors being called with indexes beyond their size in clients of estDQMOnlineClient-*
The fourth, in TestDQMServicesDemo, was already detected in https://github.com/cms-sw/cmssw/issues/36063 has been fixed by removing the ulimit request, which we are not sure why it ws here but the developer has left CMS more than year ago.

Validation: tested that UnitTests in ASAN run fine

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters

- addpkg=DQM/Integration

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#7469 for CMSSW_12_2_ASAN_X

**Comment by jfernan2** [comment]
test parameters:

- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#7469 for CMSSW_12_2_ASAN_X

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#7469 for CMSSW_12_2_ASAN_X

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
