### PR TITLE
Add maximum of pileup pT hats in JME custom NanoAOD

### PR DESCRIPTION
**Pull request by nurfikri89**
**PR description:**

This PR adds the maximum of the pileup pT hats into the JME custom NanoAOD. This is done by modifying `NPUTablesProducer.cc`  to find the maximum value in the `vector<float>` returned by `getPU_pT_hats()` and then store in the PileUp table. 

A flag is also added and set to **false** in `globals_cff.py` so that this variable will not be stored in the main NanoAODs. The flag is set to true in `custom_jme_cff.py` so that it will be stored in the JME custom NanoAOD format.  

The variable is needed by JERC analyses, which will use the JME Custom NanoAODs.

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

This PR needs to be backported to 10_6_X, once merged, for the ultra legacy campaigns.

### CODE REVIEW

**Comment by nurfikri89** [comment]
FYI JMAR convenors (@camclean @alefisico) and JERC contact (@anmalara)

**Comment by mariadalfonso** [comment]
please test workflow 25202.15,10224.15,11024.15,1325.6,1325.7,1325.8,136.7952,1329.1,136.8521

**Comment by mariadalfonso** [comment]
@nurfikri89 
please quote the size increase associated to the addition of vector of floats.

**Comment by nurfikri89** [comment]
> @nurfikri89
> please quote the size increase associated to the addition of vector of floats.

Hi @mariadalfonso, this only stores a [single float](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc#L98) and that it is not stored by default (by setting the flag to [false](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/globals_cff.py#L18)) so that central nano are not touched, only just the [JMEnano](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/custom_jme_cff.py#L882).

**Comment by mariadalfonso** [comment]
> > @nurfikri89
> > please quote the size increase associated to the addition of vector of floats.
> 
> Hi @mariadalfonso, this only stores a [single float](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc#L98) and that it is not stored by default (by setting the flag to [false](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/globals_cff.py#L18)) so that central nano are not touched, only just the [JMEnano](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/custom_jme_cff.py#L882).

yes, indeed, we need to know the JMEnano size increase/decrease for any update.
Please pick the ttbar MC with PU.
the JMEnano is becoming by far too large ~ > 10kB per event.

**Comment by nurfikri89** [comment]
> > > @nurfikri89
> > > please quote the size increase associated to the addition of vector of floats.
> > 
> > 
> > Hi @mariadalfonso, this only stores a [single float](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc#L98) and that it is not stored by default (by setting the flag to [false](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/globals_cff.py#L18)) so that central nano are not touched, only just the [JMEnano](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/custom_jme_cff.py#L882).
> 
> yes, indeed, we need to know the JMEnano size increase/decrease for any update.
> Please pick the ttbar MC with PU.
> the JMEnano is becoming by far too large ~ > 10kB per event.

Understood. Will make the test.

**Comment by nurfikri89** [comment]
> > > @nurfikri89
> > > please quote the size increase associated to the addition of vector of floats.
> > 
> > 
> > Hi @mariadalfonso, this only stores a [single float](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc#L98) and that it is not stored by default (by setting the flag to [false](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/globals_cff.py#L18)) so that central nano are not touched, only just the [JMEnano](https://github.com/cms-sw/cmssw/blob/1865a0acc0216c3091ed3a892ad87251cba24567/PhysicsTools/NanoAOD/python/custom_jme_cff.py#L882).
> 
> yes, indeed, we need to know the JMEnano size increase/decrease for any update.
> Please pick the ttbar MC with PU.
> the JMEnano is becoming by far too large ~ > 10kB per event.

Hi @mariadalfonso, by running over 5K events on a UL17 TTJets sample, the size per event is 9.478 kb/event which is an increase of 0.04% from 9.474 kb/event.

**Comment by mariadalfonso** [comment]
please test workflow 25202.15,10224.15,11024.15,1325.6,1325.7,1325.8,136.7952,1329.1,136.8521

**Comment by mariadalfonso** [comment]
+xpog 
minor addition to the JMEnano,

**Comment by silviodonato** [comment]
merge

**Pull request merged**
