### PR TITLE
First Round of Phase 1 Tracking changes for Heavy Ions

### PR DESCRIPTION
**Pull request by abaty**
This PR makes many changes aimed at improving the Heavy Ion Tracking for use with the Phase 1 pixel detector. In particular, it is for HI tracking done under the Run2_2017_trackingPhase1QuadProp era. The following changes are made:

1) Fixed a missing product in the regional muon tracking which was causing a crash.
2) Changed tracking iterations to use all 4 layers of the pixels instead of the first 3
3) Added tracking iterations: LowPtQuadStep, DetachedQuadStep, and highPtTripletStep
4) Changed seeding from triplets to Cellular Automaton quadruplets

Most of these changes are attached to the 'trackingPhase1QuadProp.' modifier. I am not sure if this is more appropriate to use than the 'trackingPhase1' modifer; perhaps someone can comment.

In order to Test this PR, one needs do the following:

1) Merge the PR and do a 'scram build.'
2) Comment out lines 38-50 in RecoHI/Configuration/python/Reconstruction_HI_cff.py in order to prevent issues related to workflows downstream of the tracking (some of these do not work in Run2_2017 era, but are out of the scope of this PR).
3) Copy and run the config file found here: /afs/cern.ch/user/a/abaty/work/public/forPeople/forPhase1PR_May5/
, which runs the Run2_2017 track reconstruction on a sample of MB Hydjet events privately produced with SIM of the new pixel detector.
@mandrenguyen

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by abaty** [comment]
After discussions with @mandrenguyen , we have decided to add an additional commit which turns off the MVA track selectors in the HI tracking workflow.  We will turn them back on once new ones can be trained later in the development cycle.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
- Lot of "# 'CA' can be removed" comments: shouldn't they be more conveniently dealt with by the modifier, instead?

- It is not always clear where you consider "CA" as the default, and when you add it with the modifier: could you please review all its appearances here, and verify that everything is coherent with the design you have in mind?

- About the tests: one should be able to easily test your setup, and keept tested during the continuous  evolution of the code in CMSSW. Please provide a workflow to be included in the matrix for that purpose: the complicate procedure you envision in the general description of this pull request cannot be considered for a regular verification of the HI tracking in phase1. If there are currently issues for Reconstruction_HI_cff.py in phase1, please adjust it too with a modifier, so that a working version of it can remain available.

**Comment by mandrenguyen** [comment]
@perrotta Would it be acceptable if we include a Phase I relval wf in a separate PR?  #18684 has to be first be merged for the HI reco for phase 1 to run directly from the  driver.   
With that PR included one just needs to add --scenario HeavyIons to each step of any wf to test.   An example can be found on our working twiki: 
 https://twiki.cern.ch/twiki/bin/view/CMSPublic/HiRecoTaskForce2018
In any case, we can discuss at the RECO meeting.

**Comment by perrotta** [comment]
@mandrenguyen : good point. Let have  #18684 merged first, then. At that point, it will be easier to compare also the event contents, etc.
Yes, we can discuss it at the reco mtg on Friday.

**Comment by abaty** [comment]
@perrotta 

> Lot of "# 'CA' can be removed" comments: shouldn't they be more conveniently dealt with by the modifier, instead?
Most of these comments were referring to being able to also run an older non-CA triplet+quadruplet seeding workflow for cross-comparisons.  I have cleaned up the code a bit to remove the modules this was referring to; they were not needed for the main workflow.  The output is still the same after cleaning.

> It is not always clear where you consider "CA" as the default, and when you add it with the modifier: could you please review all its appearances here, and verify that everything is coherent with the design you have in mind?
New iterations (highPtTriplet, lowPtQuadruplet, detachedQuadruplet) are only run in the 2017 era, and therefore only have a CA seeding.  The pixelPair iteration and jetCore iterations currently do not have CA implemented in the 2017 era, so they have non-CA default seeding.  All other non-muon iterations are run in both eras, so the CA seeding in these iterations is non-default and attached to the era modifier.  Thus, in the current implementation CA is only used in the 2017 era.

With PR #18684 merged, a prescription for testing with driver commands can be found here the the first two sections:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/HiRecoTaskForce2018
I also tested workflow 140.53, and found small differences in the track distributions.  This is probably to be expected, as the track selectors were turned off.

**Comment by makortel** [comment]
Hi

I want to make a couple of clarifications regarding the pp 2017 tracking.

> Most of these changes are attached to the 'trackingPhase1QuadProp.' modifier. I am not sure if this is more appropriate to use than the 'trackingPhase1' modifer; perhaps someone can comment.

Given that you're using CA, I'd suggest to use `trackingPhase1` modifier. That's also the one that is included in the `Run2_2017` era (and onwards). (`trackingPhase1QuadProp` modifier is in `Run2_2017_trackingPhase1QuadProp` era with the main purpose of having an easy-to-switch alternative seeding to CA).

> The pixelPair iteration and jetCore iterations currently do not have CA implemented in the 2017 era, so they have non-CA default seeding.

There is no CA to be done for pixel pair iterations, as CA is all about joining consecutive pairs and with one pair there is nothing to join.

**Comment by abaty** [comment]
@makortel 
Thank you for the suggestion, I will change to the trackingPhase1 modifier.

**Comment by perrotta** [comment]
please test

**Comment by abaty** [comment]
I made a mistake with git a few minutes ago which resulted in the bot pinging quite a few extra people; very sorry for that.

In any case, the era modifier has been updated, and we should be ready to test now using `Run2_2017` instead of `Run2_2017_trackingPhase1QuadProp`.

**Comment by perrotta** [comment]
There are several changes also in non Phase1 workflows, see for example
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-05-23-1100+18646/20195/validateJR/all_OldVSNew_RunHI2011wf140p53/

They becomes even more evident when propagated to higher level observables, e.g. pf
image

Or in the DQM plots, see for example
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-05-23-1100+18646/20195/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/Tracking_TrackParameters_GeneralProperties.html
where the HighPurity tracks show the largest discrepancy, e.g.:
image

Can you please comment?

**Comment by abaty** [comment]
Changes to the non-Phase1 distributions are expected, due to the second commit temporarily turning off the MVA estimator in the highPurity definition.  This will also affect downstream things which use the HP tracks, like PF.

**Comment by slava77** [comment]
On 5/24/17 7:02 AM, abaty wrote:
> Changes to the non-Phase1 distributions are expected, due to the second
> commit temporarily turning off the MVA estimator in the highPurity
> definition. This will also affect downstream things which use the HP
> tracks, like PF.

can this be handled with a phase-1 era modifier?
temporary major regressions to something that already works just to be
able to advance with something that's not yet working in full is not a
good approach.

**Comment by abaty** [comment]
I have changed the behavior to only turn off the MVA for Phase1 eras.

The PFCand distributions after (top) and before (bottom) changes are now identical for WF 140.53:
withchanges
baseline

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Begin processing the 688th record. Run 1, Event 688, LumiSection 1 at 25-May-2017 16:35:17.321 CEST
----- Begin Fatal Exception 25-May-2017 16:35:17 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 688 stream: 0
   [1] Running path 'reconstruction_step'
   [2] Prefetching for module GsfElectronSelector/'electronsWithPresel'
   [3] Prefetching for module GsfElectronEcalDrivenProducer/'ecalDrivenGsfElectrons'
   [4] Prefetching for module GsfElectronCoreEcalDrivenProducer/'ecalDrivenGsfElectronCores'
   [5] Prefetching for module TrackListMerger/'hiGeneralTracks'
   [6] Prefetching for module HIMultiTrackSelector/'hiRegitMuInitialStepSelector'
   [7] Prefetching for module TrackProducer/'hiRegitMuInitialStepTracks'
   [8] Prefetching for module CkfTrackCandidateMaker/'hiRegitMuInitialStepTrackCandidates'
   [9] Prefetching for module SeedCreatorFromRegionConsecutiveHitsTripletOnlyEDProducer/'hiRegitMuInitialStepSeeds'
   [10] Calling method for module PixelTripletHLTEDProducer/'hiRegitMuInitialStepHitTriplets'
Exception Message:
Did not find the layer pair from vector<pair+third layers>. This is a sign of some internal inconsistency
I was looking for layer pair 1,2. Triplets have the following pairs:
 0,1: 3rd layers 2 4 5
 0,4: 3rd layers 6
 0,5: 3rd layers 7
----- End Fatal Exception -------------------------------------------------

**Comment by perrotta** [comment]
To reproduce: I run wf 10023.0 with 2000 events (a bit more than 668 are enough...), then I replaced step 3 with the step 3 in https://twiki.cern.ch/twiki/bin/view/CMSPublic/HiRecoTaskForce2018#cmsDriver_commands (replacing in it "--era Run2_2017_trackingPhase1QuadProp" with "--era Run2_2017")

**Comment by abaty** [comment]
@perrotta @mandrenguyen 

Interesting find.  This does not appear to directly related to the commits in this PR; I was able to reproduce it in a fresh build of `CMSSW_9_2_X_2017-05-26-1100 ` after making the minimal amount of changes needed to get the code to run (an ESPrefer of the MVA selectors, and commenting a downstream module which will be fixed by this PR).

I am not currently sure what is causing the error only on this event, I will need to do some more investigation.

**Comment by makortel** [comment]
I think I have an idea what is going on. Important differences between `trackingPhase1` and `trackingPhase1QuadProp` in pp initialStep (as `hiRegitMuInitialStep*` are cloned from there) are
* `trackingPhase1` (CA quadruplet seed):
   * `initialStepSeedLayers` are quadruplets
   * `initialStepHitDoublets` generates hit doublets for all adjacent layer pairs (BPix1+BPix2, BPix2+BPix3, BPix3+BPix4 etc), that are then given to the CA to join
* `trackingPhase1QuadProp` (old-style triplet seeds + "pixel seed extension" trajectory filter)
   * `initialStepSeedLayers` are triplets
   * `initialStepHitDoublets` generates hit doublets only for the innermost layer pair (BPix1+BPix2 in the example above)

What happens here is that the doublets-for-CA have pairs for BPix2+BPix3 (indices "1,2" in the exception message), but those are not found from a "pair + third layers" vector constructed internally in the old-style triplet generator.

Recipe to fix depends on how you want to seed `hiRegitMuInitialStep`, CA quadruplets/triplets, old-style quadruplets/triplets etc.

**Comment by abaty** [comment]
@makortel 

Thank you for the clear explanation.  I have changed the Phase1 doublets for this iteration to be only BPix1+BPix2, giving the old-style triplet seeds.  I think in the future @echapon and co. will investigate moving the muons to CA as well for full parity with pp.

Workflow 10023.0 now runs to completion.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@abaty : do you also plan to provide a "2018 phase1" HI MC workflow to test more easily these and forthcoming HI developments? That would be really welcome: it could either stay in this PR, or in a separate one if you prefer.

**Comment by abaty** [comment]
@perrotta : I will defer to @mandrenguyen 's decision with regards to a 2018 workflow.  Regardless, I would prefer place it in a separate PR if we decide to provide one now.

**Comment by mandrenguyen** [comment]
I'll add a phase I MC wf in a separate PR once this one is merged.

**Comment by makortel** [comment]
@abaty In addition, depending on your further plans, it might be more clear to change the `hiRegitMuInitialStepSeedLayers` to have triplet layers instead of quadruplets. On the other hand, the doublet and triplet generators work exactly the same whether the input seeding layers are phase0 initialStep triplets or phase1 initialStep quadruplets, so this would be more of a cosmetic change (one source of confusion less when debugging by looking `edmConfigDump` output).

**Comment by perrotta** [comment]
After the last commit, there are no more crashes in my tests jobs,

I also looked at the cpu time taken by the new tracking modules: although it is not easy to compare with workflows running with a different track reconstruction (as it is the case for both phase1 pp or pre-phase1 HI reco), I don't see anything worrying. The same for the size of the produced track objects, which does not show any evident blow up. Of course, some better comparison will be likely performed as soon as some dedicated workflow will be prepared, as anticipated in https://github.com/cms-sw/cmssw/pull/18646#issuecomment-304680995

At this point, this PR is basically ready to be signed off by reco. Just let us know if you plan to follow up with the suggestion of @makortel in https://github.com/cms-sw/cmssw/pull/18646#issuecomment-304793749 , or if you would like to also postpone it to a future PR.

**Comment by abaty** [comment]
@makortel @perrotta  We are planning on making a larger PR fairly soon that revamps to muon tracking to have full or nearly-full parity with the pp algorithms.  The people who bid EPR to do this sit across from me in my office, and are aware of the changes made here.  If we moved from quad to triplet seed layers, I would expect that change to be undone very soon, so I don't think it is necessary at this point.

I will just also mention that we have done preliminary timing tests as a function of centrality, and did not see anything too shocking when comparing with the old tracking times.

**Comment by makortel** [comment]
> If we moved from quad to triplet seed layers, I would expect that change to be undone very soon, so I don't think it is necessary at this point.

I agree.

**Comment by perrotta** [comment]
+1
According to https://github.com/cms-sw/cmssw/pull/18646#issuecomment-304868089 and clarification in https://github.com/cms-sw/cmssw/pull/18646#issuecomment-304869820

**Comment by davidlange6** [comment]
+1

**Pull request merged**
