### PR TITLE
Raised nPix threshhold on pp_on_AA_2018 era track cluster checker

### PR DESCRIPTION
**Pull request by abaty**
The thresholds used for the track cluster checker were previously copied from what was used in XeXe collisions in 2017.  However, PbPb collisions are expected to have more hits, so we checked if these cuts were appropriate for 2018 data.  Based on the plot at [1], we determined that it would be best if we slightly raised the threshold on the number of pixels.

[1] https://indico.cern.ch/event/754818/contributions/3127986/attachments/1709774/2757318/clusterCheck.pdf

@mandrenguyen

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24466	5432500
- the cut on the number of pixel clusters is increased from 100K to 150K specifically for the 2018 pp_on_AA processing setup.
    - this should affect only particularly central events, around o(1E-3) of minbias events and around o(1e-2) of average triggered events. This is based on my source of 2K minbias events and 230 filtered events having zero events with more than 100K, but getting close to it, similar to what's shown in the slide attached with the PR description.
- jenkins test pass and comparisons with the baseline show no differences (none are expected).

**Comment by fabiocos** [comment]
+1

**Pull request merged**
