### PR TITLE
add minbias dataset for D49

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/pull/28775#issuecomment-577586004

#### PR validation:

Ran matrix for workflow 23434.1001

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
workflow = 23434.1001

**Comment by kpedro88** [comment]
please test

**Comment by silviodonato** [comment]
merge
thanks @kpedro88

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
