### PR TITLE
FastSim: 74X: bug fix: use same tau DQM plot harvester as FullSim

### PR DESCRIPTION
**Pull request by lveldere**

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
failure of test is not related to this pr

**Comment by slava77** [comment]
@cmsbuild please test
``` 140.53 ... Step0-DAS_ERROR ```
hoping that that one was intermittent

**Comment by slava77** [comment]
@cmsbuild please test
Looking at jenkins console for this PR:
```
error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/cms-sw/cms-bot/info/refs

```

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8800	dd11143
the same code change as in https://github.com/cms-sw/cmssw/pull/8799	 2eea599; affects only fastsim post-validation in tau

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Pull request merged**
