### PR TITLE
Fix upgrade WF steps and names

### PR DESCRIPTION
**Pull request by kpedro88**
1. Remove track trigger from T5 workflows with PU (just noticed this inconsistency the other day)
2. Modify sample names to denote Timing, Neutron workflow variations (for easier RelVal submission, requested by Stefan Piperov and discussed with @fabozzi)

This PR will be backported to 91X.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
