### PR TITLE
Pixel Cluster Counting Automation in 9_1_X

### PR DESCRIPTION
**Pull request by samhiggie**
This PR is a back port of a working branch that is in the process of final sign off in master:
https://github.com/cms-sw/cmssw/pull/18233#issuecomment-301598404

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

it's unclear why this is pushed to 91X, considering that 91X is not really operational for the pixel detector local reco

**Comment by capalmer85** [comment]
@franzoni asked us to backport so that we could implement the producers in AlCaRecos.  We are using 91X online at cms, right?

**Comment by slava77** [comment]
I think that reusing the same samhiggie:PCC_9_1_X for both this CMSSW_9_1_X and master (92X) will no longer work.
The 92X original PR #18233 can not be merged anymore

It would be easier to close this one and reopen with a different topic branch so that the 92X PR can go in.

**Comment by samhiggie** [comment]
Due to conflicts with files:
cmssw/Calibration/LumiAlCaRecoProducers/python/ALCARECOLumiPixelsMinBias_cff.py
Going to close this PR and do the back port to 9_1_X  later.

**Pull request closed without merging**
