### PR TITLE
Modernized HLTMuonPointingFilter

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- converted from legacy to global module
- added ESGetTokens

This is part of #25090
#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fwyzard** [comment]
@Dr15Jones thanks for taking care of this.

If I'm not mistaken, after your changes the only non-`const` data members are `thePropagator` and `m_cacheRecordId`.
Since `Propagator::propagate()` is `const`, I think we can use the propagator returned by the EventSetup directly, without making a copy.
Then the module could become `global` instead of `stream` ?

**Comment by Dr15Jones** [comment]
> Since Propagator::propagate() is const, I think we can use the propagator returned by the EventSetup directly, without making a copy.

@fwyzard thanks for the suggestion. My ownly worry is are we actually sure that all the classes inheriting from Propagator are actually thread-safe? For example, 
https://github.com/cms-sw/cmssw/blob/master/TrackPropagation/Geant4e/interface/Geant4ePropagator.h

looks problematic to me as it has non-const pointers as member data.

**Comment by Dr15Jones** [comment]
Ultimately I'm not the person who has to maintain the code so I'll happily convert it to global if you want.

**Comment by fwyzard** [comment]
@Martin-Grunewald what do you prefer ?

**Comment by Dr15Jones** [comment]
@makortel is of the opinion that Propagator is const thread safe and the clone is used to allowing calling the non-const interface.

**Comment by fwyzard** [comment]
So... does the fact that the module compiles with a `const` propagator means that it only uses the thread safe part of the interface ?

```diff
diff --git a/HLTrigger/special/plugins/HLTMuonPointingFilter.cc b/HLTrigger/special/plugins/HLTMuonPointingFilter.cc
index edb68ca4336..b70aecbb737 100644
--- a/HLTrigger/special/plugins/HLTMuonPointingFilter.cc
+++ b/HLTrigger/special/plugins/HLTMuonPointingFilter.cc
@@ -44,9 +44,7 @@ HLTMuonPointingFilter::HLTMuonPointingFilter(const edm::ParameterSet& pset)
       // Get a surface (here a cylinder of radius 1290mm) ECAL
       theCyl(Cylinder::build(theRadius, Cylinder::PositionType{}, Cylinder::RotationType{})),
       thePosPlane(Plane::build(Plane::PositionType{0, 0, static_cast<float>(theMaxZ)}, Plane::RotationType{})),
-      theNegPlane(Plane::build(Plane::PositionType{0, 0, static_cast<float>(-theMaxZ)}, Plane::RotationType{})),
-      thePropagator(nullptr),
-      m_cacheRecordId(0) {
+      theNegPlane(Plane::build(Plane::PositionType{0, 0, static_cast<float>(-theMaxZ)}, Plane::RotationType{})) {
   LogDebug("HLTMuonPointing") << " SALabel : " << pset.getParameter<edm::InputTag>("SALabel")
                               << " Radius : " << theRadius << " Half lenght : " << theMaxZ
                               << " Min pixel hits : " << thePixHits << " Min tk layers measurements : " << theTkLayers
@@ -61,15 +59,12 @@ bool HLTMuonPointingFilter::filter(edm::Event& event, const edm::EventSetup& eve
   bool accept = false;
 
   const TrackingComponentsRecord& tkRec = eventSetup.get<TrackingComponentsRecord>();
-  if (not thePropagator or tkRec.cacheIdentifier() != m_cacheRecordId) {
-    // get the new propagator from the EventSetup and clone it (for thread safety)
-    ESHandle<Propagator> propagatorHandle = tkRec.getHandle(thePropagatorToken);
-    thePropagator.reset(propagatorHandle.product()->clone());
-    if (thePropagator->propagationDirection() != anyDirection)
-      throw cms::Exception("Configuration")
-          << "the propagator " << thePropagatorName
-          << " should be configured with PropagationDirection = \"anyDirection\"" << std::endl;
-    m_cacheRecordId = tkRec.cacheIdentifier();
+  ESHandle<Propagator> propagatorHandle = tkRec.getHandle(thePropagatorToken);
+  Propagator const& propagator = *propagatorHandle.product();
+  if (propagator.propagationDirection() != anyDirection) {
+    throw cms::Exception("Configuration")
+        << "the propagator " << thePropagatorName
+        << " should be configured with PropagationDirection = \"anyDirection\"" << std::endl;
   }
 
   ESHandle<MagneticField> theMGField = eventSetup.getHandle(theMGFieldToken);
@@ -95,7 +90,7 @@ bool HLTMuonPointingFilter::filter(edm::Event& event, const edm::EventSetup& eve
 
     LogDebug("HLTMuonPointing") << " InnerTSOS " << innerTSOS;
 
-    TrajectoryStateOnSurface tsosAtCyl = thePropagator->propagate(*innerTSOS.freeState(), *theCyl);
+    TrajectoryStateOnSurface tsosAtCyl = propagator.propagate(*innerTSOS.freeState(), *theCyl);
 
     if (tsosAtCyl.isValid()) {
       LogDebug("HLTMuonPointing") << " extrap TSOS " << tsosAtCyl << " number of pixel hits " << pixelHits
@@ -117,9 +112,9 @@ bool HLTMuonPointingFilter::filter(edm::Event& event, const edm::EventSetup& eve
                                     << " number of muon hits " << nMuonHits;
         TrajectoryStateOnSurface tsosAtPlane;
         if (tsosAtCyl.globalPosition().z() > 0)
-          tsosAtPlane = thePropagator->propagate(*innerTSOS.freeState(), *thePosPlane);
+          tsosAtPlane = propagator.propagate(*innerTSOS.freeState(), *thePosPlane);
         else
-          tsosAtPlane = thePropagator->propagate(*innerTSOS.freeState(), *theNegPlane);
+          tsosAtPlane = propagator.propagate(*innerTSOS.freeState(), *theNegPlane);
 
         if (tsosAtPlane.isValid()) {
           if (tsosAtPlane.globalPosition().perp() < theRadius) {
diff --git a/HLTrigger/special/plugins/HLTMuonPointingFilter.h b/HLTrigger/special/plugins/HLTMuonPointingFilter.h
index 5c9ab21997d..ab8d54a2c27 100644
--- a/HLTrigger/special/plugins/HLTMuonPointingFilter.h
+++ b/HLTrigger/special/plugins/HLTMuonPointingFilter.h
@@ -67,8 +67,5 @@ private:
   const Cylinder::CylinderPointer theCyl;
   const Plane::PlanePointer thePosPlane;
   const Plane::PlanePointer theNegPlane;
-
-  std::unique_ptr<Propagator> thePropagator;
-  unsigned long long m_cacheRecordId;
 };
 #endif  // Muon_HLTMuonPointingFilter_h
```

**Comment by Dr15Jones** [comment]
>So... does the fact that the module compiles with a const propagator means that it only uses the thread safe part of the interface ?

That is the thought.

**Comment by Martin-Grunewald** [comment]
It seems ```stream``` is safe against someone modifying the underlying class called eve if OK now?

**Comment by fwyzard** [comment]
It would be a problem only if somebody introduces non-thread-safe behaviour in a `const` method (which would be bad practice).

**Comment by Dr15Jones** [comment]
@Martin-Grunewald @fwyzard were you able to come to a decision on how you'd like this handled?

**Comment by fwyzard** [comment]
I've offered options, but the decision is up to @Martin-Grunewald !

**Comment by Martin-Grunewald** [comment]
OK, ```global``` is fine with me.

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
