### PR TITLE
Updated AK8 path names for 2024 data-taking

### PR DESCRIPTION
**Pull request by marinakolosova**
#### PR description:

* Replaced AK8 paths from B2G DQM monitoring
* The new paths were introduced in [CMSHLT-3028](https://its.cern.ch/jira/browse/CMSHLT-3028)

#### PR validation:

I have tested the changes by re-running the HLT, RECO+DQM and Harvesting steps with cmsDriver and checked that the new folders are now created and filled.

I have also checked: 
runTheMatrix.py -l limited -i all --ibeos

with output:
47 46 45 36 19 1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed

The above changes will be backported to:
CMSSW_14_1_X (#44615)
CMSSW_14_0_X (#44617)

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 can you please have a look?

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
