### PR TITLE
Add new pLHE relvals for 3 MC years noPU/PU

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:

According to JIRA (https://its.cern.ch/jira/browse/PDMVRELVALS-27) and discussed in preMccM meeting, we would like to include one pLHE relval to test the whole machinery in new releases, getting ready for UL, starting from 10_6_0 

#### PR validation:

1. Local test has been done under IB CMSSW_10_6_X_2019-04-11-2300 by running 10 events for every new added workflows (1307,1307.17,1307.18 and 25215,25215.17,25215.18) with command line
e.g.
runTheMatrix.py --what standard -l 1370.0 -t 4 --command='-n 10' >& run10evt.log &
2. Also tested by real injection on 10_6_0_pre4 and everything ran successfully for noPU, will also inject PU relvals for the test and inform here
https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=CMSSW_10_6_0_pre4__Testfullsim_noPU_pLHE-1555909206

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 1370.18,25215.18

**Comment by fabiocos** [comment]
@chayanit could you please add some description about the PR and its validation in the initial filed, filling the form?

**Comment by chayanit** [comment]
> @chayanit could you please add some description about the PR and its validation in the initial filed, filling the form?

Hi @fabiocos, I added information above. However, it seems there is some issue with EOS so the test failed. We are sorting this out and will let you know.

**Comment by chayanit** [comment]
Hi, could anyone restart the test? it seems EOS is available again. 
Thanks,
Chayanit

**Comment by chayanit** [comment]
Dear @davidlange6, @slava77, @fabiocos,
Could you ask for another test? There was issue with EOS access that's why the test failed. Now it should work. 
Thanks,
Chayanit

**Comment by slava77** [comment]
please test workflow 1370.18,25215.18

**Comment by kpedro88** [comment]
please test workflow 1370.18,25215.18

**Pull request closed without merging**
