### PR TITLE
Create new collection for Hcal lasermon digis + Hcal unpacker updates

### PR DESCRIPTION
**Pull request by jkunkle**
This is a backport of this pull request #22385 aimed at 10_0_4.  The intent is to have it available for testing at p5.  The backport did not require any merging, so we expect no isues.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #22385

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Please @jkunkle : edit the title with something more descriptive, even better if it is the same as you used for the PR in the master (so that they can get easily linked each other)

**Comment by perrotta** [comment]
+1
- Identical to #22385, which is now merged in the master
- Backport to 10_0_X required for its usage foreseen in the commissioning data taking
- Keep laser monitoring data in the event
- In case of data with extra samples in FED, those extra samples are now also unpacked and saved for further private studies (not being used for the current workflows)
- No change expected and observed in reco outputs in the standard workflows, while new output will get stored in case of lasermon events or extra samples in the FED

**Comment by lpernie** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
Hi @fabiocos 
if possible it would be nice to have this one in 10_0_4. it would give the possibility to test extensively the changes in p5 during the cruzet.
thanks,
F.

**Comment by slava77** [comment]
@fabiocos 
what is the plan for the next build?

**Comment by fabiocos** [comment]
@slava77 @jkunkle this is in 10_1_X already. If this should be tried at P5 before 10_1_0, we need to consider a 10_0_5 (DataFormats are changed here)

**Comment by deguio** [comment]
Hi @fabiocos 
right. we would like to have a 10_0_5 available to test this indeed.
thanks,
F.

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
@fabiocos 
just a warning in case someone will pay attention to the production logs,
this PR is expected to lead to ~2K lines of warnings per job (8 thread case).
This shouldn't be a big deal for  logCollection and archiving at T0, but may become quite distracting for log file content inspection

more in #22706

**Comment by davidlange6** [comment]
hum - should those extra lines not show up in the PR tests? [2k lines is pretty annoying actually]

**Comment by deguio** [comment]
Hi,
the warnings are triggered by new calibration channels being included in the readout in recent runs at p5. this PR should actually reduce the number of warnings that we would get with the old version of the code.

at the moment we (hcal DPG and hca OPS) are deciding how to configure readout/emap/unpacker in an optimal way to support transparently the use of the HF calib channels. a dedicated discussion will happen on Monday.

In the meantime it would be beneficial to have this PR included in the 10_0_5 build as it fixes the behaviour of the old unpacker when processing lasermon channels.

**Comment by slava77** [comment]
On 3/23/18 2:13 AM, Federico De Guio wrote:
> Hi,
> the warnings are triggered by new calibration channels being included in
> the readout in recent runs at p5. this PR should actually reduce the
> number of warnings that we would get with the old version of the code.

Ah, I had the sign of the issue wrong in my head.
This PR is actually better, but still not good enough.

> 
> at the moment we (hcal DPG and hca OPS) are deciding how to configure
> readout/emap/unpacker in an optimal way to support transparently the use
> of the HF calib channels. a dedicated discussion will happen on Monday.
> 
> In the meantime it would be beneficial to have this PR included in the
> 10_0_5 build as it fixes the behaviour of the old unpacker when
> processing lasermon channels.
>

**Pull request merged**
