### PR TITLE
bsunanda:Run2-alca43 Correct for isolated track trigger

### PR DESCRIPTION
**Pull request by bsunanda**
Recover from no event selection status

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@mmusich @Martin-Grunewald Could you please review this PR quickly. We are getting no events in teh IsoTrack trigger and we found the reasons and corrected the code as well as the HLT menu which can be integrated only when the correct code is there.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@bsunanda seems this PR doens't merge anymore (?)

**Comment by fwyzard** [comment]
-1

Please provide enough details to understand the impact on the HLT.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
+1
@bsunanda I think for this to pass we need some checks on the impact on the HLT side, can you please follow up on Andrea's questions?

**Comment by bsunanda** [comment]
@mmusich We are preparing a few slides as suggested Sezen  and send it to TSG for review

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
