### PR TITLE
Remove deprecated JetPartonCorrector

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Remove dead code not referenced or used by anything. It hasn't been under development for many years. This is motivated by the ::JetCorrector migration. This code inherits from the deprecated ::JetCorrector class. We are migrating away from that class with the intent to delete it entirely soon.

@smuzaffar This package will be basically empty after this PR is merged. I don't know how to delete a package or if it is worth the effort, but this package could be deleted entirely.

#### PR validation:

None needed. Just deletions.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by smuzaffar** [comment]
@wddgit , you still have a `BuildFile.xml` in this package. Please delete this file too and then git will remove the package directory as it will be empty

**Comment by wddgit** [comment]
please test

I force pushed a revised commit that also removes BuildFile.xml. @smuzaffar, thanks.

**Comment by wddgit** [comment]
please test

I don't see how this could fail? Maybe a temporary glitch? Try again.

**Comment by perrotta** [comment]
merge

**Pull request merged**
