### PR TITLE
update DeepFlavour training for 2016 NanoAOD and re-run it (master)

### PR DESCRIPTION
**Pull request by gpetruc**
same as #24276 but for the master branch

the changes from #24117 show up in this because it's the same branch for 10_2_X and 10_3_X (but I believe git is smart enough to understand it)

### CODE REVIEW

**Comment by gpetruc** [comment]
please test workflow 136.7722,136.8521,1325.6,1325.8,1325.9,1329.1

**Comment by fabiocos** [comment]
@gpetruc I assume this is ok for you

**Comment by fabiocos** [comment]
+1

**Comment by gpetruc** [comment]
+1

**Pull request merged**
