### PR TITLE
udpates to stage2 unpacking

### PR DESCRIPTION
**Pull request by mulhearn**
This PR brings stage-2 unpacking up to date.  It adds stage-2 unpackers to standard sequence, but these should do nothing when their RAW payloads are not present.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
@cmsbuild, please build

**Comment by mulhearn** [comment]
I think we have pushed this back to 800...

**Comment by mulhearn** [comment]
This is pushed back to 80x.

**Pull request closed without merging**
