### PR TITLE
Pr80x l1t integration 89.9 CMSSW_8_0_24

### PR DESCRIPTION
**Pull request by rekovic**
80x PR for Level1

This PR Includes all fixes for the L1T emulator:
- BMTF unpacker memory leak
- TwinMux memory leak (already in 81x)
- Layer2 emulator to do what in FW (bug in FW tower max eta in TowerCount for HI)
- Turn off warnings in L1T Ntuple maker.
- uGT handling of saturated Et bins in CorrelationConditions to be as in FW.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
hold

**Comment by rekovic** [comment]
unhold

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
@rekovic something went wrong when moving to 8_0_24 as development release.

A couple of commits that were in `l1t-integration-v89.9` are not in `l1t-integration-v89.9-CMSSW_8_0_24` anymore. Notably, changes to the MuonCaloSumProducer, the L1Ntuples, and for the muon phi extrapolation to the vertex are missing in the 8_0_24 version of the tag. Below is a diff of the L1Trigger directory of the two tags. 

```
git diff --name-only l1t-integration-v89.9 l1t-integration-v89.9-CMSSW_8_0_24 -- L1Trigger

L1Trigger/Configuration/python/customiseReEmul.py
L1Trigger/Configuration/python/customiseSettings.py
L1Trigger/L1TCalorimeter/data/IsoIdentification_adapt_extrap_v16.07.29.txt
L1Trigger/L1TCalorimeter/data/IsoIdentification_adapt_extrap_v16.08.08.txt
L1Trigger/L1TCalorimeter/data/Tau_Calibration_LUT_NewLayer1Calibration_Emu_v10.1.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Calibration_LUT_NewLayer1Calibration_SK1616_EmuOldFormat_v11.0.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_NewLayer1Calibration_noCompressionBlock_Emu_v5.1.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_NewLayer1Calibration_noCompressionBlock_Emu_v5.2.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_NewLayer1Calibration_noCompressionBlock_SK1616_EmuOldFormat_v6.0.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_NewLayer1Calibration_noCompressionBlock_SK1616_EmuOldFormat_v6.1.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_22_NewLayer1Calibration_noCompressionBlock_SK1616_EmuOldFormat_v6.2.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_5_NewLayer1Calibration_noCompressionBlock_Emu_v5.1.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_5_NewLayer1Calibration_noCompressionBlock_Emu_v5.2.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_5_NewLayer1Calibration_noCompressionBlock_SK1616_EmuOldFormat_v6.0.0.txt
L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_5_NewLayer1Calibration_noCompressionBlock_SK1616_EmuOldFormat_v6.1.0.txt
L1Trigger/L1TCalorimeter/data/lut_30to40_hfHighPt_experiment2_changeLimits_add_mult.txt
L1Trigger/L1TCalorimeter/data/lut_30to40_hfHighPt_experiment2_changeLimits_eta.txt
L1Trigger/L1TCalorimeter/data/lut_eta_compress_noeta29.txt
L1Trigger/L1TCalorimeter/python/hackConditions_cff.py
L1Trigger/L1TGlobal/data
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_CaloSliceTest_2015.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v6_uGT_v2.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v6_uGT_v2a.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v6_uGT_v3.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v6_uGT_v3a_NG.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v7_uGT.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v7_uGT_v1.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v7_uGT_v2.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v7_uGT_v3.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_25nsStage1_v7_uGT_v4.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2015_5TeV_pp_reference_v5_uGT_v2_mc.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2016_dev_v3.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Collisions2016_v2c.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_CollisionsHeavyIons2015_v4_uGT_v2.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_CollisionsHeavyIons2015_v5_uGT.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_HeavyIons2016_v1.1.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_HeavyIons2016_v1.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1Menu_Reference_2014.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/L1TriggerMenu.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/L1_Example_Menu_2013.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_ALGOBX_MASK_V1.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_FINOR_MASK_v17.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_PRESCALES_v10.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_VETO_MASK_v1.xml
L1Trigger/L1TGlobal/data/Luminosity/startup/menu.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/prescale_L1TGlobal.csv
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-algorithm.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-bin.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-cut.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-ext_signal.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-ext_signal_set.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-external_requirement.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-menu.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-object_requirement.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-scale.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/complex-scale_set.xsd
L1Trigger/L1TGlobal/data/Luminosity/startup/xsd-type/simple-types.xsd
L1Trigger/L1TGlobal/data/README.md
L1Trigger/L1TGlobal/plugins/L1TGlobalPrescaler.cc
L1Trigger/L1TMuon/interface/MicroGMTConfiguration.h
L1Trigger/L1TMuon/plugins/L1TMuonCaloSumProducer.cc
L1Trigger/L1TMuon/python/simDigis_cff.py
L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc
L1Trigger/L1TMuonEndCap/src/Forest.cc
L1Trigger/L1TNtuples/BuildFile.xml
L1Trigger/L1TNtuples/interface/L1AnalysisL1Upgrade.h
L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h
L1Trigger/L1TNtuples/interface/L1AnalysisRecoMuon2.h
L1Trigger/L1TNtuples/interface/L1AnalysisRecoMuon2DataFormat.h
L1Trigger/L1TNtuples/interface/MuonID.h
L1Trigger/L1TNtuples/plugins/L1Muon2RecoTreeProducer.cc
L1Trigger/L1TNtuples/python/L1NtupleAOD_cff.py
L1Trigger/L1TNtuples/python/l1MuonRecoTree_cfi.py
L1Trigger/L1TNtuples/python/l1UpgradeTfMuonTree_cfi.py
L1Trigger/L1TNtuples/src/L1AnalysisL1Upgrade.cc
L1Trigger/L1TNtuples/src/L1AnalysisRecoMuon2.cc
```

**Comment by dmitrijus** [comment]
Please close this (and any PRs which you don't want officially merged).

**Comment by rekovic** [comment]
this is superseded by #16966

**Pull request closed without merging**
