### PR TITLE
Geometry Clang Check readability-avoid-const-params-in-decls

### PR DESCRIPTION
**Pull request by ianna**
Replacement for https://github.com/cms-sw/cmssw/pull/20224

* Geometry part of @davidlange6's #19660

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
thanks @ianna for applying change to files under tests. code-checks should not have complained about those files. I will check why this happened

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
