### PR TITLE
Remove the process name dependence for HCAL DPG skims (90X)

### PR DESCRIPTION
**Pull request by kfjack**
The process name was hard coded in the HCAL DPG skims (JetHTJetPlusHOFilter / PhotonJetPlusHOFilter). Remove this dependence. Back port from #18384.

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of #18384

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
