### PR TITLE
Phase2-gex04 Fix some 2026 geometries by removing interfering duplicate file

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix some 2026 geometries by removing interfering duplicate file

#### PR validation:

Use runTheMatrix.py with limited option

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Is worthwhile to be back ported. This is a bug fix to some Phase2 scenarios

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
What happened in the comparison tests? 3365 differences?

**Comment by kpedro88** [comment]
The changes are isolated to the D49 workflow. @bsunanda thought the wrong muon constants might have been used in the geometry before this fix.

**Comment by bsunanda** [comment]
@kpedro88 @cvuosalo This was exactly my suspicion. I think this needs back porting to 11_1_X.

**Comment by kpedro88** [comment]
@bsunanda I agree, this indicates a bug. It won't affect the 11_1_X re-reco, but it will impact new samples.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
