### PR TITLE
Cleanup of Tracking code

### PR DESCRIPTION
**Pull request by VinInn**
removed several obsolete packages and classes
did a bit of modernization in some places recently touched by other migrations

purely technical: shall produce zero regression

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
+1
Utilities/ReleaseScripts

**Comment by VinInn** [comment]
Let's wait @smuzaffar fix, and then we try again...

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3599

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21456	1cd489f
- mostly a cleanup. 
    - also, the inheritance of some classes previously derived from ReferenceCounted was simplified (BasicVertexState, BasicTransientTrack). Perhaps this can lead to some epsilon size speedup.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by davidlange6** [comment]
merge

**Pull request merged**
