### PR TITLE
CTPPS new reconstruction geometry related to TOTEM RP detectors - backport of #14029

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #14029 from CMSSW 81X

This PR includes geometry needed by reconstruction algorithms and data structures used by alignment code

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@grzanka 
please clarify if this was building in local tests.

**Comment by grzanka** [comment]
@slava77 I'll check it. This PR was exact copy of the same commits submitted to 81X.
Before refactoring everything was working correctly.

BTW - is there any change related to unique_ptr between 80X and 81X ?

**Comment by slava77** [comment]
@Dr15Jones @wmtan 
please take a look  and let us know if there are some issues with backporting from 81X related to use of unique_ptr
.. that we need to switch back to auto_ptr or smth?

**Comment by Dr15Jones** [comment]
@slava77 as far as I can tell CMSSW_8_0_X does not support `unique_ptr` for this use. So the backport does require going back to `auto_ptr`

**Comment by grzanka** [comment]
@slava77 @Dr15Jones is there any universal solution which would allow us to compile the same code in 80X and 81X ?

**Comment by slava77** [comment]
It would be much better though to  have the minor edits needed to compile in 80X to be applied during backporting.
For future developments/updates, unless you edit the same context lines, development in 81X and then backpot to 80X should be simple.

**Comment by grzanka** [comment]
@slava77 OK - I'll implement it tomorrow.

**Comment by grzanka** [comment]
@slava77 I've just replaced unique_ptr with auto_ptr, hope this helps

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@ggovi your signature is needed here

@grzanka I notice that #14029 has "+18,662 −0" while this PR has "+18,665 −0" changes
Do you know where the difference is?

**Comment by grzanka** [comment]
@slava77 the difference comes from the fact that you've asked me to replace unique_ptr with auto_ptr and I did it.

**Comment by slava77** [comment]
On 5/31/16 9:06 AM, Leszek Grzanka wrote:
> @slava77 <https://github.com/slava77> the difference comes from the fact
> that you've asked me to replace unique_ptr with auto_ptr and I did it.

Thanks for the clarification.
Maybe it helps to get the remaining signatures and merge faster.

**Pull request merged**
