### PR TITLE
Introduce `conddb` script unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is inspired from https://github.com/cms-sw/cmssw/issues/34378.
In commit 0daa900 a unit test to check basic functionalities of the `conddb` script is added.
In commit 2927fc9 a protection for `conddb diffGlobalTagsAtRun` is added, in order not go in error if it's run=1 (that's MC)

#### PR validation:

The newly introduced unit test passes:
```
scram b runtests_test_conddb
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test with #34402

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@mmusich   Please resolve the conflict.

**Comment by mmusich** [comment]
@qliphy done

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
test parameters:
pull_request = cms-sw/cmsdist#7142

**Comment by qliphy** [comment]
please test

**Comment by mmusich** [comment]
test parameters:

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Can we please merge this before the release gets broken in 10,000 other ways? Thanks

**Comment by davidlange6** [comment]
Having just waited 2 weeks for a simple db PR (whose absence broke the second round of your PR tests), I guess this PR is still too young to be signed:)

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
