### PR TITLE
Fix includes and typos inRecoJets/JetProducers

### PR DESCRIPTION
**Pull request by Teemperor**
We use the VertexCollection in QGTagger.h, so we also need to include VertexFwd.h here.

In PileupJPTJetIdAlgo.h we foward declare the non-existent class ParameterSet**s**, but instead we want to forward declare ParameterSet.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding issue https://github.com/cms-sw/cmssw/issues/15248

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19162	d04543b
- technical
- jenkins tests pass (Reco comparison results: 0 differences found in the comparisons)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
