### PR TITLE
Microstate monitoring update (DAQ) 81X

### PR DESCRIPTION
**Pull request by smorovic**
Fixes to microstate monitoring in DAQ EvF:
- Global EoL microstate state should not be set in initialization stage.
- GlobalEoL should only be set for thread/stream after postStreamEndLumi
- Per thread/stream breakdown of some states for input state monitoring (to analyze the effective impact of limitations imposed by the multithreading model).
- Two states removed, two new input states added

PR also includes new test mode for FedRawDataSource used to fill ramdisk in fakeBU mode looping over events from raw files.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15955 c0fbc6f64d578703287e7409a840ee08794cbec5

For the DAQ, fixes for microstate monitoring. There should be no change in offline monitored quantities.

#15956 is the 80X version of this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-22-0900 show no significant differences, as expected.

**Comment by emeschi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
