### PR TITLE
Bin lookup in the JetCorrectorParameters class (undo revert)

### PR DESCRIPTION
**Pull request by aperloff**
This pull request is an update to the previously merged and then reverted pull request https://github.com/cms-sw/cmssw/pull/17812 (revert at https://github.com/cms-sw/cmssw/pull/18036). The problem was that a new warning message was introduced that was being tripped too often. There was no new error mode, but the message was new and led to really large logs. The code to print this message has now been shut off. Nothing else changed between this pull request and #17812.

### CODE REVIEW

**Comment by kpedro88** [comment]
@davidlange6 does this look acceptable?

**Comment by davidlange6** [comment]
whats the point of potentially having the message? it is apparently routine and not a sign of any problem - or is that not the case?

**Comment by davidlange6** [comment]
eg, if its routine, there is no reason to keep the commented code

**Comment by aperloff** [comment]
It's useful for developers, but too verbose for general users. In general what it means is that the jet eta or jet pt is outside the bounds of the available bins (i.e. an eta of 6 is requested when the bin edge is at 5.191). Thus the code returns a correction of 1. In the past this was a silent event, and this message was just very useful to me when testing and debugging the code. I would propose to keep the commented code for future editing of this software or do implement a debug/verbosity option. Thoughts?

**Comment by davidlange6** [comment]
I don't really see how its useful for any but the simplest of developers at this point. are there plans to make the set of bins cover all of the expected phase space (which would be a typical way of doing this)? then the errors would be a sign of a problem.

**Comment by aperloff** [comment]
Okay, I've removed the comment. The code is the same otherwise.

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by aperloff** [comment]
The failing unit tests seems to be xrootd errors again. Nothing to do with this PR.

**Comment by davidlange6** [comment]
please test

**Comment by aperloff** [comment]
@davidlange6 It seems like everything is okay. What do you think? Can this be merged into CMSSW?

**Pull request merged**
