### PR TITLE
Run3-hcx285 Make use of ESGetToken in CalibCalorimetry/HcalTPG...

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in CalibCalorimetry/HcalTPG...

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by yuanchao** [comment]
+1
* migrate from deprecated get(handle) to esconsumes with token.
* matrix run wf tests and unit tests all passed
* static build warnings are not part of this PR.

**Comment by silviodonato** [comment]
ping @cms-sw/l1-l2 (@jmduarte @rekovic )

**Comment by bsunanda** [comment]
@jmduarte @rekovic @silviodonato Please approve

**Comment by silviodonato** [comment]
merge @jmduarte @rekovic

**Comment by silviodonato** [comment]
merge
 @jmduarte @rekovic

**Pull request merged**
