### PR TITLE
Updated list of magnetic field steppers and EM physlists for Geant4 10.4

### PR DESCRIPTION
**Pull request by civanch**
These modifications are recommended by Geant4 experts for the version 10.4. None of those should affect current results, because the default configuration is not changed. This PR includes:

1) addition of optional magnetic field steppers provided by Geant4 team. If enabled this may allow speed-up of FullSim. Two old obsolete steppers are removed from the list.
2) More optimal configuration of CMS custom EM physics constructors, may be result as a tiny optimisation of CPU/memory

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch as far as I can see the default stepper is unchanged. What about the changes in the physics lists? What should be the effect?

**Comment by civanch** [comment]
@fabiocos , I have checked, that these modifications do not change results - random number sequence not changed. These minor changes means do not instantiate objects, which are  not used and skip some calls to these objects.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
