### PR TITLE
Fix sorting index for lost tracks in UnifiedParticleTransformer producer

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR fixes an issue found in the UnifiedParticleTransformer producer, that relates to the index used to access the sorting list of lost tracks. The indices of the lt_sortedindices vector correspond to the indices of the original collection (e.g. LTs collection), however in the second for loop, the lt_sortedindices is accessed using the index of the lt_sorted vector (which has been trimmed and is smaller than the LTs collection). To get back the correct index to access the elements of the lt_sortedindices one should use the "get()" function from the lt_sorted vector, which returns the index of the LTs collection.

@SWuchterl @DickyChant

#### PR validation:

Tested locally by comparing the features produced by the CMSSW producer to those used by the b-hive inference.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
please test

**Comment by stahlleiton** [comment]
Since the unified particle transformer model has already been trained for 2024 pp, I made a commit to add a flag to enable the bug fix. This flag is set to false by default to avoid affecting central production.

**Comment by mandrenguyen** [comment]
please test

**Comment by AlexDeMoor** [comment]
Would it be possible to have documentation regarding this bugfix? More specifically, it would be very useful to understand this one and its impact.

Also, the same ordering is used by the cpf and npf candidates from most of the btagger since DeepJet

**Comment by stahlleiton** [comment]
> Would it be possible to have documentation regarding this bugfix? More specifically, it would be very useful to understand this one and its impact.
> 
> Also, the same ordering is used by the cpf and npf candidates from most of the btagger since DeepJet

The bug is not present for the cpf and npf since in those two cases, the second for loop (where the sorted list is used) is done over the same collection (jet constituents) as the for loop that filled the sorted vector. So the indices are consistent.

However, in the case of lost tracks, the second for loop is done over a different collection than the one used to fill the sorted vector, which introduces the issue.

The main consequence of using the wrong index when accessing the sorted list is that one can either get the default value returned (i.e. 0) or a wrong value, so the elements are assigned to entry 0 multiple times (thus it stores less lost tracks in the features vector than elements in the sorted vector) or to another position it should not.

**Comment by mandrenguyen** [comment]
@AlexDeMoor Are you satisfied with this explanation/solution?

**Comment by mandrenguyen** [comment]
+1

**Comment by AlexDeMoor** [comment]
We have followed the discussion offline about some details of this bugfix and the potential impact of it. For now, everything is ok on the tagger side and we will have further evaluation later. This bugfix is not affecting UParT for the 2024 data giving us time to ensure the lost tracks are totally ok.

**Comment by mandrenguyen** [comment]
type btv

**Pull request merged**
