### PR TITLE
Removed use of static from components method

### PR DESCRIPTION
**Pull request by Dr15Jones**
The components method was using a static variable to hold the return
value from the function. Comments on the function stated it was hoped
that the routine would never be called. To fix the thread safety problem
and minimize the memory usage, the code was changed to use an std::atomic
pointer to cache the return value if and only if components was called.

This problem was found by the static analyzer.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
This commit fixes the crash. One should always read the C++ standard :).

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #7403 8dd5373c345843408d129284dbb620c364c7ea62

Very limited code change to convert a static variable into a thread-safe one.

Code changes are satisfactory.

Jenkins tests [CMSSW_7_4_X_2015-01-28-1400 ]
(https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7403/2200/summary.html):
compilation, unit tests, matrix tests, static checks are all OK.

As expected, there are no differences compared to the baseline in the
following:

[alternative-comparisons]
(https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-01-28-1400+7403/5767/alternative-comparisons/)
(after stripping false positives like timer data)

and

[validateJR] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-01-28-1400+7403/5767/validateJR/)

**Pull request merged**
