### PR TITLE
Remove PV usage in packed gen particles

### PR DESCRIPTION
**Pull request by alberto-sanchez**
This PR, cleans not used code, and makes the creation of MINIAODSIM from GEN-only samples easy.

### CODE REVIEW

**Comment by perrotta** [comment]
pleae test

**Comment by slava77** [comment]
please test

**Comment by perrotta** [comment]
please test
(test failure seems unrelated to this PR)

**Comment by gpetruc** [comment]
Hi Alberto,

Thanks for the PR.
Can you change the title to "Remove PV usage in packed gen particles" or something similar?
The current title is a bit confusing, as regular MINIAODSIM files do contain the reconstructed PVs.

Giovanni

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18083	ab2f746
- technical change removing unused code/branch, as described
- jenkins tests pass and comparisons show no differences

**Pull request merged**
