### PR TITLE
Redo PixelJetPuId multi-threading (74X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Redo PixelJetPuId multi-threading (74X)
(c.f. #9138)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Errors unrelated to this PR.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
