### PR TITLE
[DD4hep] backport of 32339 and 32371 to assure thread-safe dd4hep workflow

### PR DESCRIPTION
**Pull request by ianna**
#### PR validation:

@qliphy - as requested

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
backport

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test workflow 11624.911, 11642.911

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
