### PR TITLE
[10_6_X] feat: allow for not sorting during PATJetUpdater call

### PR DESCRIPTION
**Pull request by andrzejnovak**
Backport of #32297 needed for jetmet/btv nano production

### CODE REVIEW

**Comment by perrotta** [comment]
backport of  #32297

**Comment by santocch** [comment]
please test

**Comment by perrotta** [comment]
+1
- As for the (basically identical) master version of this PR; it ended up that this will only involve some (private? future?) nanoAOD production, while the change is completely transparent to reco: let assign xpog for evaluating it, then
- Jenkins tetst pass and show no differences wrt the baseline, as expected

**Comment by perrotta** [comment]
assign xpog

**Comment by santocch** [comment]
+1

**Comment by andrzejnovak** [comment]
Pinging @mariadalfonso in case the backport needs to be signed as well.

**Comment by mariadalfonso** [comment]
+xpog
changes inline with master

**Comment by silviodonato** [comment]
+1

**Pull request merged**
