### PR TITLE
Remove unnecessary import of L1GTScales

### LINKED ISSUE #43823: [ASAN] Relval failing with asan libaray load issue
Since CMSSW_14_0_ASAN_X_2024-01-24-2300 we see many Relvals are failing with error [a]. this normally happens when an executable without any explicit linking to `libasan.so` load any shared library which is linked with `libasan`. I noticed that The relvals which are failing are using `-s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@relval2026` (i.e `HLT:@relval2026`) option to cmsDriver. e.g. for wf `24834.0 step2` (which fails) the cmsDriver command is
```
cmsDriver.py step2  -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@relval2026 --conditions auto:phase2_realistic_T25 --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry Extended2026D98 --era Phase2C17I13M9  --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --prefix 'python2 /data/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 14400 '  --filein filelist:step1_dasquery.log --fileout file:step2.root  --suffix "-j JobReport2.xml "  --nThreads 4
```

while for workflow `1.0 step2` comamnd
```
cmsDriver.py step2  -s DIGI,L1,DIGI2RAW,HLT:@fake --datatier GEN-SIM-RAW --eventcontent RAWSIM --conditions auto:run1_mc  --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --prefix 'python2 /data/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 14400 '  -n 100  --filein  file:step1.root  --fileout file:step2.root  --suffix "-j JobReport2.xml "  --nThreads 4 
```

works. Changing `HLT:@fake` to `HLT:@relval2026` also causes wf `1.0 step2` to fail with same error [a].

https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_ASAN_X_2024-01-22-2300...CMSSW_14_0_ASAN_X_2024-01-24-2300 are the changes after which we start seeing these failures. 

Any idea what `HLT:@relval2026` does? Does it run any external process  which try to load cmssw libs? 

[a] 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_ASAN_X_2024-01-29-2300/pyRelValMatrixLogs/run/24834.0_TTbar_14TeV+2026D98/step2_TTbar_14TeV+2026D98.log#/
```
==2720140==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves  https://github.com/cms-sw/cmssw/issues/43823

#### PR validation:

`cmsDriver.py` command of step2 of workflow 24834.0 succeeds in ASAN IB.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test for CMSSW_14_0_ASAN_X

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
Hi @aloeliger @epalencia 

Would you mind to answer or ping relevant ppl on question in https://github.com/cms-sw/cmssw/issues/43823#issuecomment-1919362024
So that we have a clear statement before the deletion happens in this PR. Thx.

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
