### PR TITLE
Run3-gex160 Modify the correct combination of ZDC xml files in Phase2 scenarios which are useful for dd4hep version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the correct combination of ZDC xml files in Phase2 scenarios which are useful for dd4hep version

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , does this PR fix overlaps in ZDC?

**Comment by bsunanda** [comment]
No - it just corrects the use of units, removal of duplicate materials and use of correct region names. I have to work on the overlap now. So it has no effect on DDD version - only for DD4hep version.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
