### PR TITLE
Add displaced pT measurement to L1T::Muon object

### PR DESCRIPTION
**Pull request by dildick**
An extra member `ptNoVtx` was added to the `L1T::Muon` object opening up the possibility to develop pT assignment algorithms for non-prompt L1 muons. The changes proposed does not affect the performance of the l1 trigger. The extra member `ptNoVtx` will only be filled in phase-2 scenarios where displaced muon triggers are enabled. It should not be used in Run-2 or Run-3 scenarios. The default value is 0.

@tahuang1991

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
@davidlange6 Those commits should not have been added. They are part of a follow-up branch. I'll undo them.

**Comment by dildick** [comment]
The test failed because of the incomplete code that I removed after the test started. The previous set of tests were just fine (https://github.com/cms-sw/cmssw/pull/19780#issuecomment-315900420)

**Comment by dildick** [comment]
Could you run the tests again please? Thanks.

**Comment by dildick** [comment]
Could you run the tests again please? Thanks.

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
@davidlange6 Could you sign please?

**Comment by dildick** [comment]
@davidlange6 Could you sign please?

**Comment by dildick** [comment]
@davidlange6 We really need to have these updates in asap to further develop the displaced muon trigger for the muon TDR. Could you please sign this PR at once? Alternatively, please comment why the integration is taking so long.

**Comment by davidlange6** [comment]
hi @dildick - sorry for not getting to this - the issue is the same as before - its just a data format change and I can't see where this is going. maybe its good just to combine this and the PR that uses it into one?

**Comment by dildick** [comment]
@davidlange6 I am working on a producer for displaced l1 muons in CMSSW. @tahuang1991 and I would like to start porting our private code to CMSSW to have these objects available. Our algorithms have shown to work as expected. the results are included in the draft muon tdr. The image below shows how the Phase-2 muon trigger would look like. 

image

The idea is that the EMTF/BMTF/OMTF calculate the displaced (unconstrained) pt alongside the prompt pt. The muons are sent to a sorter where they are collected as l1 muon candidates. On the other hand the muons and tracks are fed into a matching algorithm, which produces track+muon candidates. Muons that could not be matched to tracks and that are not vetoed are displaced muon candidates. The vetoing step is essential to keep the rate down for the single and double displaced muon trigger. This scheme is what we want to build in simulation step by step. 

There are several issues that are holding the development:
- TT tracks are still missing in simulation; I was promised that they will be ported soon. Still I can start porting the displaced pT assignment algorithms.
- A displaced muon pT measurement (this pull request). Next to the prompt pT measurement we absolutely need a displaced muon pT measurement in the dataformat.
- Run-2 algorithms should not be interfered with. To not upset any physics analyses we have chosen to do the displaced muon pT assignment after the muons are already built. We plan to recalculate the pT based on the stub content of the muon. This requires the precise knowledge of the stub content of EMTF/OMTF/BMTF. Stubs are directly accessible for EMTF. For OMTF it is simply not possible yet to know which stubs were used by the algorithm. I contacted Karol Bunkowski and @konec to look into it. For BMTF, this brings me to my next bullet point
- The BMTF does not save the tracks and track segments that it constructed, unlike the EMTF. I want to change that, so that I can easily find out which eta/phi segments were used to build a barrel muon. This is the idea behind https://github.com/cms-sw/cmssw/pull/19990

@davidlange6  I am not planning to combine these change in one big request. Some of my pull requests already take way too long to get integrated. By making one giant pull request, I will definitely lose a huge amount of time and possibly a lot of work. I presented the status of the studies back in May at the Upgrade workshop discussed my ideas with @rekovic. He did not have any objections. Over the past few weeks/months we have made various presentations in all sorts of upgrade meetings. This work needs to move forward now.

**Comment by dildick** [comment]
@davidlange6 do you have any questions/comments?

**Pull request closed without merging**
