### PR TITLE
Run2-hcx175 Add noise filter summary collection to all AlCaReco o/p files

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie @arunhep Please approve this

**Comment by lpernie** [comment]
Hi @bsunanda , could you add a description to the PR?

**Comment by abdoulline** [comment]
@lpernie  it's probably too late now for Sunanda to answer, so I take the liberty to mention:
it's important to have a *small* HcalNoisSummary (collection) in HCAL AlCa outputs to have a direct possibility for analysts to apply HCAL noise filters for cleaning AlCa results.

**Comment by arunhep** [comment]
@abdoulline how much is the increase in event size we expect with this change?

**Comment by bsunanda** [comment]
This addition will change event size by 1-2% depending on the AlCaReco. It is indeed a very small collection with noise summary information. If you really want to have accurate numbers we have to work it out for each AlCaReco

**Comment by arunhep** [comment]
@bsunanda the worry is that few of the AlCaRECOs are already over budget and is stressing the T0 disk. Specially the size of HcalCalHBHEMuonFilter. you may have received an email from Thiago about it. 1-2% is still acceptable but i think we need to work towards the overall size reduction of HCAL AlCaRecos.

**Comment by abdoulline** [comment]
Arun, I've just

in  this PR

One of the RelVals,  JetHT2017F
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23134/27780/runTheMatrix-results/136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017/

in step2.root has  HcalNoiseSummary collection,

               name             | uncompressed  Bytes   | compressed Bytes
HcalNoiseSummary_hcalnoise__RECO.    491.53                     140.21

I suppose this is kind of maximal (as it's high-occupancy JetHT2017F 
sample) size estimate per AlCa event (?)

    Salavat

**Comment by arunhep** [comment]
@abdoulline ok thanks for these numbers. they look reasonable.

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
