### PR TITLE
added esConsumes to modules in L1Trigger/RegionalCaloTrigger

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by JamminJones** [comment]
the module L1RCTProducer is in the same package but was not updated because it uses complex logic to decide when to get EventSetup data. Modification of this module will have to be done by an expert.

**Comment by Dr15Jones** [comment]
This was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
