### PR TITLE
Refactorize track-time stamping for PF to run after all tracks are imported.

### PR DESCRIPTION
**Pull request by lgray**
Fixes cases where some tracks that were imported did not receive time stamps since they came in from the non-generic importing steps (attached conversions and such).

@bendavid

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1
Changes in ttbar D8 workflow (w/ timing layer) are very minor, no obvious problems
Code looks reasonable

**Comment by lgray** [comment]
@slava77 can you run a check in 200 PU just to make sure.

**Comment by slava77** [comment]
On 3/17/17 11:11 AM, Lindsey Gray wrote:
> @slava77 can you run a check in 200 PU just to make sure.

Do we have pre6 relvals with this in PU200?

**Comment by kpedro88** [comment]
@lgray needs rebase

**Comment by perrotta** [comment]
ping @lgray: please rebase

**Comment by perrotta** [comment]
@lgray : this PR is stuck since 20 days already. Please close it if you don't need it anymore being integrated

**Pull request closed without merging**
