### PR TITLE
Add "pixel tracking only" workflow to 2017 matrix, and it and "tracking only" workflow to 2018 matrix

### PR DESCRIPTION
**Pull request by makortel**
This PR adds a "pixel tracking only" workflow aiming to have a minimal step3 configuration for producing pixel tracks and vertices (+ their validation). Such a workflow is useful e.g. for future tracking R&D.

Tested in CMSSW_10_0_X_2017-12-13-2300, no changes expected in existing workflows.

@VinInn @felicepantaleo @fwyzard

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 10024.5,10824.1,10824.5

**Comment by perrotta** [comment]
+1
- The newly inserted workflows do run

**Comment by civanch** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
