### PR TITLE
Remove compiler warnings in E/gamma packages

### PR DESCRIPTION
**Pull request by lgray**
Remove comparison of now-boolean variable to a signed quantity (always true).
Remove inclusion of magnetic field from ConversionTools (not being used and throws a strange warning).

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17107 5e9b747
- changes are as described; the more notable is the logic bugfix in EcalUncalibRecHitRecAnalFitAlgo.h (which is not used in any workflows in CMSSW)
- jenkins tests pass and comparisons with baseline show no relevant differences
    - 23234 comes up with changes in the ftlRecHits timeError which are apparently related to missing set of the value in the constructor https://github.com/cms-sw/cmssw/blob/ed1181df91f64d26fc069f469379c49414a893ba/DataFormats/FTLRecHit/src/FTLUncalibratedRecHit.cc#L8-L9

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@slava77 I'll fix up the uninitialized variable today.

**Pull request merged**
