### PR TITLE
Use database objects to set MSB in LUTs for HCAL 2017 HE TP

### PR DESCRIPTION
**Pull request by matz-e**
Companion to #15945.

Use information from the `HcalTPChannelParameter` object to set two MSB in the linearization LUTs.

Posting separately as it is self-contained and only affects one package.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@matz-e this PR results in a segfault in the workflows emplyoing the 2017dev Hcal geometry: 10624.0, 	10824.0

**Comment by matz-e** [comment]
Yes, this needs #16072 to be merged.

**Comment by abdoulline** [comment]
CMSSW_8_1_X_2016-10-04-2300  has the access activated, 
may we get the tests restarted, please?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@rekovic, @mulhearn, @davidlange6 ping for pre13

**Comment by kpedro88** [comment]
@rekovic, @mulhearn, @davidlange6 another ping...

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
