### PR TITLE
[Phase-2 L1T] Updated of GCT jets and taus collection

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:

Restricting total number of GCT jets/taus to 6 per eta half (12 in total, previously was 36). Updated seed tower energy threshold to 5 GeV to suppress PU contribution. The calibrations of jets/taus have been updated using Spring23 samples in 14X release.

#### PR validation:

Reviewed here: https://github.com/cms-l1t-offline/cmssw/pull/1230

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.

### CODE REVIEW

**Comment by aloeliger** [comment]
+l1

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by epalencia** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test after a month.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
