### PR TITLE
[93X] Offline DQM extensions for L1T EGamma (calo layer 2) and fixes

### PR DESCRIPTION
**Pull request by kreczko**
This PR implements the features requested in Jira ticket [CMSLITDPG-171](https://its.cern.ch/jira/browse/CMSLITDPG-171):
 - changes to the electron thresholds
 - additional histograms for all electron probes
 - additional histograms for a subset of electron probes

In addition, this PR includes
 - fixes for the last bins for the efficiency histograms in L1T EGamma, Jets, Sums and Taus (last bin was ommited)
 - L1TEfficiency harvesting can now handle 2D histograms (needed for ticket)
 - changed `edm::LogError` to `edm::LogWarning` for the message regarding a missing matched L1T jet

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks

**Comment by kreczko** [comment]
code-checks

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
