### PR TITLE
Make sampicSubDetId a tracked parameter

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

This PR changes sampicSubDetId to the tracked parameter as requested in #38365 

#### PR validation:

PR was tested with 136.8562.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This change needs to be included in the 12_4_X backport #38365 and in future backport to 12_3_X.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by Martin-Grunewald** [comment]
I think this class plugin should get a fillDescriptions method to take care of parameters & values, whether tracked or untracked. For sure this is required for usage within HLT.

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
```fillDescriptions``` is documented here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp .

**Comment by tvami** [comment]
+alca
 * tests pass
 * I agree that the fillDescribtion should be done, but given that this PR's backport holds back the 12_4_0 creation, I'd say we do that in another PR

**Comment by clacaputo** [comment]
+reconstruction

- pr needed for bp #38365
- `fillDescription` to be implemented for `TotemDAQMappingESSourceXML` in future pr
- no reco changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
