### PR TITLE
Added consumes to GlobalDetLayerGeometryESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- Added use of consumes
- Switched to using ESGetTokens.

#### PR validation:

The code compiles.

This in meant to be just a refactoring so no changes are expected.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Part of #26748

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27011	ae8052f
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
@Dr15Jones this PR needs a rebase

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27011	4a4233c
- the updated version is equivalent to the previously signed one https://github.com/cms-sw/cmssw/pull/27011	ae8052f. The changes include some code reformating.
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
