### PR TITLE
Fix track sort order in PixelTrackProducerFromSoAAlpaka [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Port the fix to `PixelTrackProducerFromSoA` from #42428 by @silviodonato to `PixelTrackProducerFromSoAAlpaka`.

Clean up `PixelTrackProducerFromSoA` and `PixelTrackProducerFromSoAAlpaka`.

#### PR validation:

The online HLT menu v1 was run with these changes.

#### Backport status

Backported of #44441 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #44441

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
