### PR TITLE
clean up use of array parameters in L1T modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Replace user functions with ParameterSet::getParameter<std::array<...>>.
Remove the checks for C++14, and other unused code.

#### PR validation:

Technical, no changes expected.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
Please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
