### PR TITLE
Phase2-hgx359A Modify some of the scripts in Validation/HGCalValidation/test/python to be in line with the current defaults of scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify some of the scripts in Validation/HGCalValidation/test/python to be in line with the current defaults of scenarios

#### PR validation:

Tested the scripts by using them

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
