### PR TITLE
add extendable x-axis to hit efficiency plots (#21100 backport)

### PR DESCRIPTION
**Pull request by mtosi**
backport of https://github.com/cms-sw/cmssw/pull/21100

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@mtosi is this PR still needed in 94X or can just be closed?

**Comment by mtosi** [comment]
I've just re-looked at this (I forgot about it at all :( )
it would be better to have it in, for backward / forward compatibility, I would say

thanks

**Comment by fabiocos** [comment]
@mtosi thank you, although I am not sure which practical use this PR might have at this point. If its integration is required, @jfernan2 @andrius-k could you please check it?

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
