### PR TITLE
Make provenance handling event level thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
Modify how provenance is handled so once we use more than one thread per event the code will be thread-safe.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 Why does the bot think this has a new package? I hadd to change code in the already existing ```HeavyFlavorAnalysis/Onia2MuMu```  package in order to avoid a compilation failure.

**Comment by davidlt** [comment]
Because it was never assigned to anyone: https://github.com/cms-sw/cms-bot/blob/master/categories.py

**Comment by Dr15Jones** [comment]
The test failure is not from this pull request. The file requested by the test failed to open via eos.

**Comment by smuzaffar** [comment]
As @davidlt  said, it was never assigned to any one. @davidlange6, should we assign analysis category to HeavyFlavorAnalysis/Onia2MuMu?

**Comment by davidlange6** [comment]
Yes, should be analysis

**Comment by smuzaffar** [comment]
cms-bot ping

**Pull request merged**
