### PR TITLE
[10_6_X] ParticleNetAK4 jet tagger

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/31570. 
The addition of the ParticleNetAK4 discriminants to miniAOD is controlled by the `run2_miniAOD_UL` modifier in this backport.

Needs cms-data/RecoBTag-Combined#35.

FYI @camclean @alefisico

### CODE REVIEW

**Comment by qliphy** [comment]
test parameters:
- pull_request=cms-data/RecoBTag-Combined#35

**Comment by qliphy** [comment]
please test

**Comment by silviodonato** [comment]
test parameters

**Comment by silviodonato** [comment]
test parameters:
- pull_request=https://github.com/cms-sw/cmsdist/pull/6288

**Comment by silviodonato** [comment]
please test

**Comment by jpata** [comment]
+reconstruction

- backports the ParticleNetAK4 tagger to 106X for UL miniaod
- needs cms-data/RecoBTag-Combined#35 to be merged first
- tagger is enabled only for UL workflows using the appropriate modifier and shows up in the appropriate monitoring
- no other unexpected reco modifications

**Comment by silviodonato** [comment]
merge
@cms-sw/analysis-l2 please let us know if you have any comments

**Comment by santocch** [comment]
+1

**Pull request merged**
