### PR TITLE
Validation/RecoEgamma and DQMOffline/EGamma: Increase the x-axis scale for all plots as a function of number of offline vertices

### PR DESCRIPTION
**Pull request by nancymarinelli**
…fline vertices

#### PR description:

Simple change of the x-axis scale of all plots as a function of the number of offline vertices. To accomodate 2021 PU level. Would possibly be usefull to back port to 10_X_Y if that is meant to be used for 2021 tests 

#### PR validation:

I tried in the 11_0_X most recent IB the runTheMatrix --what standard -l 1332.0

### CODE REVIEW

**Comment by nancymarinelli** [comment]
> A new Pull Request was created by @nancymarinelli for master.
> 
> It involves the following packages:
> 
> Validation/RecoEgamma
> 
> @andrius-k, @kmaeshima, @schneiml, @cmsbuild, @jfernan2, @fioriNTU can you please review it and eventually sign? Thanks.
> @davidlange6, @slava77, @fabiocos you are the release manager for this.
> 
Hi guys, I had forgotten to make the same change also in DQMOffline/EGamma. I just did that and pushed to this PR.

**Comment by jfernan2** [comment]
Hi @nancymarinelli, could you please make sure that subsystem name appears in the title of the PR?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@nancymarinelli this PR is modifying a variable number of histograms in Egamma and EgammaV folders depending on the workflows. Can you please check that the behaviour is what you expect? 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-27-1100+be48d6/31937/dqm-histo-comparison-summary.html

**Comment by nancymarinelli** [comment]
yes, it does what is it supposed to do

On 28/05/19 11:57, jfernan2 wrote:
> @nancymarinelli this PR is modifying a variable number of histograms in Egamma and EgammaV folders depending on the workflows. Can you please check that the behaviour is what you expect?
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-27-1100+be48d6/31937/dqm-histo-comparison-summary.html
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
