### PR TITLE
Add 2023 geometry unit test, remove T1

### PR DESCRIPTION
**Pull request by kpedro88**
Changes in this PR:
1. Add unit test to compare outputs of 2023 geometry generation script to current versions of the corresponding files. This should prevent inconsistencies of the type that have occurred recently.
2. Add a few features to the script:
  * `-D` is now used to specify an existing detector version (requested a while ago by @lgray) in lieu of specifying each subdet version. `-V` is now used for the previous functionality, to specify a new version number for an unknown setup to facilitate testing.
  * A list of deprecated detector and subdetector version numbers is kept, to prevent any of them from being reused accidentally.
3. Removed T1 and replaced with T3 in relevant detector versions. This was implemented as D1->D7, D5->D8, D6->D9. D3 was removed, as it would be redundant with D4 with this change. Importantly, all workflow numbers were kept the same, by designating what were previously the D3 numbers as "conflicts" to be skipped. This was requested by the tracking group because reco efforts are increasingly based on T3 and may not provide sensible performance for T1. The specific implementation of the change in this PR was agreed with upgrade management.

In the future, I also plan to remove C1 and reduce the number of detector versions. However, due to the intended use of 90X for TDR production, these further changes are tentatively delayed until 91X, in order to avoid confusion.

Failing test result:
```
Package Configuration/Geometry: Running test test2023Geometry
 
===== Test "test2023Geometry" ====
argument 0: test2023Geometry
argument 1: /bin/bash
argument 2: Configuration/Geometry/test
argument 3: runtests.sh
shell is: /bin/bash
Current directory is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100
topdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100
testdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/src/Configuration/Geometry/test
tmpdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/tmp/slc6_amd64_gcc530
testbin is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/test/slc6_amd64_gcc530
Running script: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/src/Configuration/Geometry/test/runtests.sh
GeometryExtended2023D6_cff.py differs
GeometryExtended2023D5Reco_cff.py differs
status = 256

---> test test2023Geometry had ERRORS

^^^^ End Test test2023Geometry ^^^^
```
Passing test result:
```
Package Configuration/Geometry: Running test test2023Geometry
 
===== Test "test2023Geometry" ====
argument 0: test2023Geometry
argument 1: /bin/bash
argument 2: Configuration/Geometry/test
argument 3: runtests.sh
shell is: /bin/bash
Current directory is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100
topdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100
testdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/src/Configuration/Geometry/test
tmpdir is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/tmp/slc6_amd64_gcc530
testbin is: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/test/slc6_amd64_gcc530
Running script: /uscms_data/d3/pedrok/phase2/wf/CMSSW_9_0_X_2016-12-07-1100/src/Configuration/Geometry/test/runtests.sh
status = 0

---> test test2023Geometry succeeded

^^^^ End Test test2023Geometry ^^^^
```

This PR supersedes #16908.

@slava77, this might cause some "missing matrix map" warnings...

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Well, that's slightly embarrassing, but clearly demonstrates the need for this unit test...

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Pull request merged**
