### PR TITLE
80x: add pixel barycenter computation tool

### PR DESCRIPTION
**Pull request by mmusich**
Backport of #14730:
Making available in release tool needed for Pixel barycenter computation:
https://twiki.cern.ch/twiki/bin/view/CMS/TkAlignmentPixelPosition

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
test failure is unrelated

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
