### PR TITLE
Restructure PixelPhase1 DQM packages

### PR DESCRIPTION
**Pull request by schneiml**
To shorten the discussion around issue #22576, here is a proposal.

We planned something in this direction from the beginning, but decided to stick with the style of the old tracker DQM packages to keep the consistency.

This PR is likely to break a few WF that depend on the Phase1Pixel DQM in a nonstandard way (I vaguely remember some stuff in HLT DQM), since the config needs to be adapted for the new package names. Lets see.

@fabiocos @fioriNTU

### CODE REVIEW

**Comment by fioriNTU** [comment]
@schneiml well, I wasn't aware you were doing this, coming back to TkDQM? :-)
You impression is right, the HLT DQM will be broken now, we have to edit the config there. My plan for doing this "migration" was to create a plugin ad-hoc for HLT purposes, in a way we completely disentagle the two things. I won't ask you to do it, even if surely you are the best person to put hands in Phase1 DQM. In the case you wish to continue and fix the whole thing, we can discuss it tomorrow.

**Comment by schneiml** [comment]
@fioriNTU I planned to do it at some point, since it is probably much faster to do for me than for you... And I do feel some remaining responsibility when people complain about Phase1 DQM.

For the HLT stuff, I have no idea and just did the obvious things for now. If workflows/people complain we can talk about more complex solutions. But we can talk tomorrow anyways!

**Comment by fabiocos** [comment]
@schneiml thank you for starting this effort. In any case at this point it should be done with calm without breaking anything. Such a migration is clearly to be considered now for 10_2_X.

**Comment by schneiml** [comment]
@fabiocos for sure, this is one of the least urgent things we have at the moment, but I wanted to get it out of the way. It is not a very complicated change after all.

**Comment by fabiocos** [comment]
@schneiml could you please rebase the PR, so as we can go back to it?

**Comment by schneiml** [comment]
rebased to master, hope nothing broke (only whitespace issues).

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@schneiml @fioriNTU @dmitrijus now it looks a good moment to move forward with this PR. I would like just to ensure that no HLT stuff is broken, or it is updated accordingly. Was this verified?

**Comment by fioriNTU** [comment]
@fabiocos I let @schneiml reply, however I am quite sure it doesn't break anything, in that case we would have observed crashes in the tests

**Comment by schneiml** [comment]
@fabiocos I am afraid I also can't do much more than what the PR/IB tests test.

I am worried about this code [1] and friends, but given it does not import the Python configs and that edm plugins are not namespaced, it looks safe.

[1] https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by schneiml** [comment]
Rebased to `CMSSW_10_2_X_2018-04-25-2300`, resolved one conflict in the configuration file.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
