### PR TITLE
MiniAOD: met filter flag on bad muon

### PR DESCRIPTION
**Pull request by mariadalfonso**
Here additional MET filter flags

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

looks like the various filters are generated by copy-paste with minor modifications.
It would be better to have a more flexible filter that can handle more cases so that we do not generate new copy-pasted code that may have maintenance issues if ever needs to be updated.

**Comment by slava77** [comment]
since this is considered not essential for rereco, I'd rather we properly review this at regular pace.
Code quality is not really at production level.

**Comment by cvuosalo** [comment]
@mariadalfonso: Massive copy/paste of code is not an advisable software development method for maintainable production code. Instead of five nearly identical filter classes, there should only be one which is parameterized and configurable for multiple needs. This configurability can be achieved with constructor parameters, templates, inheritance, or maybe multiple method functions.

**Comment by cvuosalo** [comment]
@mariadalfonso: The 810pre12 deadline is rapidly approaching. What is the plan for completing this PR?

**Comment by mariadalfonso** [comment]
I close these PR since I made those in a super hurry to meet the 8_0_20 re-reco deadline.

For the 81X - that target next year, if needed we can re-open other PRs that 
1) rework the class as you requested in https://github.com/cms-sw/cmssw/pull/15761
and allow the needed large scale testing
2) look at the Prompt-Reco H dataset with the various charged hadron PF-fixes and alignments and hw HIP fix. 
3) come up with a real PF fix for the remaining muon problems.

**Pull request closed without merging**
