### PR TITLE
Updating in all the relevant Global Tags the L1 menu to the version for post-TS2 data-taking: L1Menu_Collisions2016_v6r5_ugt_1board_xml

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v7) as [81X_mcRun2_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v7/81X_mcRun2_design_v6): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v6) as [81X_mcRun2cosmics_startup_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v6/81X_mcRun2cosmics_startup_peak_v7): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v7) as [81X_mcRun2_asymptotic_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v7/81X_mcRun2_asymptotic_v8): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
- **RunII Startup scenario** : [81X_mcRun2_startup_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v8) as [81X_mcRun2_startup_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v8/81X_mcRun2_startup_v9): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
## RunII data
- **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v3) as [81X_dataRun2_HLT_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v2/81X_dataRun2_HLT_relval_v3): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
- **RunII Offline relval processing** : [81X_dataRun2_relval_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v9) as [81X_dataRun2_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v9/81X_dataRun2_relval_v8): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v11) as [81X_upgrade2017_realistic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v11/81X_upgrade2017_realistic_v12): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`
- **PhaseI design scenario** : [81X_upgrade2017_design_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v9) as [81X_upgrade2017_design_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v9/81X_upgrade2017_design_v10): 
  - updated L1 uGT menu to `L1Menu_Collisions2016_v6r5_ugt_1board_xml`

### CODE REVIEW

**Comment by mmusich** [comment]
hold

**Comment by Martin-Grunewald** [comment]
There is a merge conflict in this PR. I do not know whether I picked correctly for HLT...

**Comment by Martin-Grunewald** [comment]
I have reverted what I picked previously as it gave a merge-conflict as well.
I assume you'd need to update this PR and then I pick again??

**Comment by mmusich** [comment]
@Martin-Grunewald, yes I placed yesterday another PR to grant Hcal people a new key in autoCond #15884 and didn't want to mix them up to create unnecessary dependencies. 
Either one of the two had to be merged first and you lost :)
That's sort of inevitable if people place their PRs at the very last minute before the release closes...
Now it merges. Enjoy

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
+1
change already included in https://github.com/cms-sw/cmssw/pull/15875

**Comment by davidlange6** [comment]
already merged (with a different commit?) -closing to avoid potential conflicts

**Comment by mmusich** [comment]
@davidlange6, thansk. 
I am not sure why the commit hash of the PR #15875 (https://github.com/cms-sw/cmssw/pull/15875/commits/b30818f27431978def1d373c826f1aab27d9e48f) is different from https://github.com/cms-sw/cmssw/pull/15879/commits/3c0828213884dd922f415a8e46eefc158dde7a76 of this PR, but the changes are the same.

**Pull request closed without merging**
