### PR TITLE
Enable general gamma process for Geant4

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
General gamma process is a new method for gamma transport available with Geant4 10.7. For Run-3 CMS this bring ~1% CPU advantage with statistically same results. For Phase-2 the speed-up should be more.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

General gamma process uses different number of calls to the random number generator, so no regression is expected.

**Comment by qliphy** [comment]
For the record:  There is a on-going check on size change from this PR in https://github.com/cms-sw/cms-bot/pull/1595

**Comment by civanch** [comment]
@qliphy , @slava77, on SIM step there should be some increase of memory due to extra data tables built at initialisation. From the report I do not understand is this value is significant or not, also do not understand if there is any effect of RECO. At least, at my tests, which are not very accurate I do not see a significant overhead.

**Comment by qliphy** [comment]
+1

**Pull request merged**
