### PR TITLE
Move GEMDigi dictionary generating classes

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Move GEMDigi dictionary generating classes from EventFilter/GEMRawToDigi to DataFormats/GEMDigi and update references

Per issue #30586 only DataFormats should have objects generating dictionaries.

@jshlee @quark2

#### PR validation:

Checked upgrade workflow 11621.0 still completes successfully with the changes. Grep'd through cmssw for references to the moved objects, and ran code-checks.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
@watson-ij  there seems to be erros due to duplicated dictionaries:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6335d8/7998/dupDict/

**Comment by watson-ij** [comment]
> @watson-ij there seems to be erros due to duplicated dictionaries:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6335d8/7998/dupDict/

So, the classes.h and classes_def.xml in EventFilter is deleted with this PR, and those classes are moved into the DataFormats. But it looks like the EventFilter classes_def is still being picked up in the Jenkins build? Not sure if theres a way around that?

**Comment by slava77** [comment]
also, the extra lines in the logs are like
```
Warning in <TInterpreter::ReadRootmapFile>: class  GEMVfatStatusDigi found in libEventFilterGEMRawToDigi.so  is already in libDataFormatsGEMDigi.so 
```

**Comment by slava77** [comment]
it looks like most of the moved header files have a wrong include guard,
e.g. 
```#ifndef EventFilter_GEMRawToDigi_VFATdata_h``` in VFATdata.h
please update

**Comment by smuzaffar** [comment]
@slava77 , old lib from IB should not be visible is a local version of it is built but if one remove a package then old lib from release is still visible. In this case, yes full release is solution

**Comment by smuzaffar** [comment]
By the way, today's 11h IB is already a full IB.

**Comment by slava77** [comment]
test parameters:
- full = true

**Comment by slava77** [comment]
@smuzaffar 
full = true 
did not help.
The dup.txt still points to EventFilter/GEMRawToDigi/src/classes_def.xml which was removed in this PR
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6335d8/8024/dupDict/dup.txt

I suppose we just assume it's OK and merge,
or is there something that can be checked on the PR test side?

**Comment by slava77** [comment]
> I suppose we just assume it's OK and merge,

I'm actually still waiting for https://github.com/cms-sw/cmssw/pull/30740#issuecomment-659535871 to be resolved; but that's a cosmetic/style update

**Comment by watson-ij** [comment]
https://github.com/cms-sw/cmssw/pull/30740#issuecomment-659535871 should be taken care of now.

**Comment by smuzaffar** [comment]
@slava77 , you are right. full is not behaving properly for only cmssw PRs. I works when cmsdist PRs are involved. In case you want to test now, then please test with cms-sw/cmsdist#6090 (dummy cmsdist PR). I will fix the bot testing script to set correct env for full cmssw PRs later

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#6090

**Comment by slava77** [comment]
+1

for  https://github.com/cms-sw/cmssw/pull/30740	1823c7f
- code changes are in line with the PR description and the follow up review
    - the data formats moved from EventFilter/GEMRawToDigi were apparently only lightly reviewed, quite likely due to its originally more internal need for these classes. Style should be followed better for the centrally distributed DataFormats. Some cleanup/update for non-persisted types, members, and methods would be useful, to follow http://cms-sw.github.io/cms_coding_rules.html#2--naming-rules-1. @jshlee @watson-ij  please take a note for a to-do list.
- jenkins tests pass and comparisons with the baseline show no differences
    - unit test failures are not related to this PR

**Comment by slava77** [comment]
dqm, simulation, and upgrade signatures are still needed here.
Please check.

**Comment by kpedro88** [comment]
+upgrade

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
