### PR TITLE
MTD geometry: add test workflows for scenario D53, update material budget validation

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is a follow-up of #28788 adding:

- definition of test workflows for scenario D53 in the upgrade section of PyReleaseValidation. No test is added to the standard matrix, as the workflows is fully functional up to GEN-SIM, the RECO geometry needs to be updated. Anyway the availability of the definition is useful to perform tests and debugging;

- update of Validation/Geometry adding the materials needed by the new ETL. This allows the user to produce material budget plots for the new scenario D53, showing the increase in the ETL region due to the double disk structure.

image

#### PR validation:

The produced material budget plot is linked above. Test workflows runs in step1, and fail as expected for the time being in step2.

### CODE REVIEW

**Comment by fabiocos** [comment]
@pmeridian @parbol FYI

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1
No dqm changes

**Comment by fabiocos** [comment]
@jfernan2 indeed this PR is not supposed to affect DQM output of any standard workflow, the validation of material budget is made with standalone configurations

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@chayanit comments? Objections?

**Comment by chayanit** [comment]
+1
looks fine for me

**Comment by silviodonato** [comment]
+1

**Pull request merged**
