### PR TITLE
Patch for ttbarNLO@13TeV workflow

### PR DESCRIPTION
**Pull request by mkiani**
Patch for ttbarNLO@13TeV workflow

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by bendavid** [comment]
The 13TeV gridpack was produced with ptj=20, so qcutME in the pythia configuration actually needs to be set to 20.

**Comment by mkiani** [comment]
@bendavid  Done...

**Comment by bendavid** [comment]
+1

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@inugent 
please be aware of this change, this will be disruptive of the incremental validation, for one sample

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
