### PR TITLE
bsuanda:Run2-hcx123 Fix bug for wrong depth indexing in Plan 1

### PR DESCRIPTION
**Pull request by bsunanda**
Correctly provide the depth index within HCalSD taking care of many special conditions - main impact on depth index for Plan1 when  testNumbering is not chosen at the SIM phase.
Also adds the tools to test this effort

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - please, provide description

**Comment by Dr15Jones** [comment]
@muzaffar
Was there a cvmfs problem ?

**Comment by civanch** [comment]
@bsunanda , you need disable
 #define EDM_ML_DEBUG

**Comment by abdoulline** [comment]
We need to test it thoroughly:

(1)  if it cures the issue described in slides 21/22 of 

https://indico.cern.ch/event/624968/contributions/2534560/attachments/1438163/2215131/CMSSW_Status_April4_2017.pdf

(2)  if it doesn't affect _default_ (for 2017 MC) layer-> DetId-depths assignment in DIGI
otherwise it (fix) needs back-porting to 90X for MC production...

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Close this in view of PR#18194

**Pull request closed without merging**
