### PR TITLE
[14_0_X] Fix for is not a valid DT id error

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44417

### CODE REVIEW

**Comment by jfernan2** [comment]
type bug-fix

**Comment by aloeliger** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44417

**Comment by aloeliger** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
