### PR TITLE
[124X backport] Keep Run2 EGamma IDs in Run3 nano(v10)

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

This is a combined backport of https://github.com/cms-sw/cmssw/pull/38810 and https://github.com/cms-sw/cmssw/pull/38853. This is intended to keep Run2 ID decisions of electron and photon in Run3 nano(v10), as an intermediate solution for early analyses until the latest greatest IDs trained with Run3 samples are available, which would require a few more weeks to converge. 

#### PR validation:
CMSSW compiles.
11634.0 works fine.

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by mariadalfonso** [comment]
both photons and electrons IDs are back.

https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/168
Screen Shot 2022-07-30 at 10 13 14


Screen Shot 2022-07-30 at 10 18 28

**Comment by mariadalfonso** [comment]
backport of #38810 
backport of #38853

**Comment by mariadalfonso** [comment]
+xpog

backport inline with master

**Comment by mariadalfonso** [comment]
@clacaputo, @jpata this is waiting your signature

**Comment by clacaputo** [comment]
+reconstraction

- backport of #38810 and #38853
- code is inline with master

**Comment by mariadalfonso** [comment]
> +reconstraction

@clacaputo can you actually sign ?
the bot didn't recognise it

**Comment by clacaputo** [comment]
> @clacaputo can you actually sign ?
> the bot didn't recognise it

Sorry for the typo

**Comment by qliphy** [comment]
+1

**Pull request merged**
