### PR TITLE
DD4hep: Update TEC in 2021 Scenario

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Use updated version of TEC xml file with correct units
* Set the world dimentions

#### PR validation:

```
cmsRun DetectorDescription/DDCMS/test/python/testGeometry2021.py
```

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - please review

**Comment by fabiocos** [comment]
@ianna sorry, this looks largely overlapping with @slomeo 's #27744, where I have asked Sergio to remove for non 2021 scenarios, am I correct? Probably it is better to merge that and rebase on top

**Comment by ianna** [comment]
@fabiocos - yes, it's based on his PR. As soon as that is merged, I'll rebase this one.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna I've squashed the history to avoid adding to github large useless xmls, see #27777

**Comment by ianna** [comment]
@fabiocos - sure, it's fine with me.

**Comment by ianna** [comment]
merged as https://github.com/cms-sw/cmssw/pull/27777

**Pull request closed without merging**
