### PR TITLE
[13_0_HLT_X] Improve memory usage in ParameterSet

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR backports https://github.com/cms-sw/cmssw/pull/42742 in order to allow a file written in 14_0_X to be read by a 13_0_X `cmsRun` in order to run the HLT step in 13_0_X in the upcoming 2023 MC campaign. 

The last commit was needed to get the backport to compile, because of https://github.com/cms-sw/cmssw/pull/43898 was in 13_0_X already before the backport.

**Note that files written with a release containing this PR will be unreadable by earlier 13_0_X releases.** Therefore this PR is to be merged only in the 13_0_HLT_X branch.

Resolves https://github.com/cms-sw/framework-team/issues/918

#### PR validation:

I modified the `test_MC_23_setup` test, added in https://github.com/cms-sw/cmssw/pull/44578, to use my local 13_0_18 + this PR developer area and to fail if the HLT step fails, and the test passed.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/42742

### CODE REVIEW

**Comment by makortel** [comment]
hold

**Comment by smuzaffar** [comment]
> @smuzaffar What kind of additional setup we'd need for that special release?

@makortel , I think creating a cms-sw/cmssw CMSSW_13_0_HLT branch should be enough take care of 13_0_18_HLT release. This PR should be then merged in to `CMSSW_13_0_HLT` branch. All the changes in CMSSW_13_0_X branch can be automatically forward ported the  `CMSSW_13_0_HLT`

**Comment by makortel** [comment]
The unit test failures seem to be caused by an error in creating a proxy certificate? (at least for those the error was clearly visible)

**Comment by makortel** [comment]
> Few weeks back we discussed in ORP that this PR would be merged into a special e.g. 13_0_18_HLT release that would then be used for the HLT step in the upcoming MC production (because files written with this PR would be unreadable with 13_0_X releases without this PR). Just to confirm, is still this the case?

@cms-sw/pdmv-l2 @cms-sw/ppd-l2 Could you please confirm if the plan above still holds?

**Comment by AdrianoDee** [comment]
> > Few weeks back we discussed in ORP that this PR would be merged into a special e.g. 13_0_18_HLT release that would then be used for the HLT step in the upcoming MC production (because files written with this PR would be unreadable with 13_0_X releases without this PR). Just to confirm, is still this the case?
> 
> @cms-sw/pdmv-l2 @cms-sw/ppd-l2 Could you please confirm if the plan above still holds?

Hi Matti, sorry for the delay. Yes the plan is still that.

**Comment by makortel** [comment]
Thanks @AdrianoDee. @smuzaffar Could you create `CMSSW_13_0_HLT_X` and `CMSSW_12_4_HLT_X` branches, and I'll adjust the base branch of this PR (and open another one for the 12_4 backport)?

**Comment by smuzaffar** [comment]
@makortel 13.0.HLT and 12.4.HLT IBs are now active ( https://github.com/cms-sw/cms-bot/pull/2229). You need to change the base branch for this PR to CMSSW_13_0_HLT_X.

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
unhold

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparisons show https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cms-sw/orp-l2 Please double check the base branch before merging :)

**Comment by makortel** [comment]
@cms-sw/dqm-l2 @cms-sw/simulation-l2 Could you please review and sing this backport?

**Comment by makortel** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42742

**Comment by civanch** [comment]
+1

fine to sim but test is not complete?

**Comment by makortel** [comment]
The tests on top of 13_0_HLT_X https://github.com/cms-sw/cmssw/pull/44921#issuecomment-2116192342 succeeded, but maybe the bot still looks for the 13_0_X tests in https://github.com/cms-sw/cmssw/pull/44921#issuecomment-2099136671 for the test label?

**Comment by makortel** [comment]
@cms-sw/dqm-l2 Could you review and sign? Thanks!

**Comment by tjavaid** [comment]
+1

- [Spurious difference](https://tinyurl.com/29rm9d26) seen from unstable WF `12434.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
