### PR TITLE
[14_0_X SIM] Added Russian roulette to ZDC and optionally to HGCal

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR substitutes #43545 and #43570. It is proposed for more performant ZDC simulation. Baseline simulation is expected to be unchanged.

1) Extra option to simulate faster ZDC and HGCal is added. If enabled the Russian roulette method may be applied in these calorimeters. For ZDC it is enabled by default, for HGCal - disabled.

2) When ZDC simulation is enabled, CPU time for MinBias events increased in ~5.5 times, for ttbar - in ~1.5 times. In this PR some optimization is introduced, which is not significant: ~9% for MinBias and ~3% for ttbar. In the default simulation (ZDC is not enabled), no change is expected. Having not a big improvement, this PR is useful, because remove from simulation relatively rare tracks going out of ZDC, further tracking of these tracks has no sense. 

3) Also unused headers in few classes are removed. An option is added to remove e+-, gamma from simulation, which may be useful for GPU R&D.

#### PR validation:
private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: ZDC part may be backported to 3_0_HeavyIons

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by mmusich** [comment]
well, 

```
----- Begin Fatal Exception 16-Dec-2023 01:31:00 CET-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'L1TAnalyzerEndpath'
   [2] Prefetching for module L1TGlobalSummary/'L1TGlobalSummary'
   [3] Prefetching for module L1TGlobalProducer/'simGtStage2Digis'
   [4] Prefetching for module L1TStage2Layer2Producer/'simCaloStage2Digis'
   [5] Prefetching for module L1TCaloLayer1/'simCaloStage2Layer1Digis'
   [6] Prefetching for module EcalTrigPrimProducer/'simEcalTriggerPrimitiveDigis'
   [7] Calling method for module MixingModule/'mix'
Exception Message:
Unavailable Conditions of type HcalMCParams for cell (0x54000140) (Det 5:5 subdet 2:2 ZDC+ UNKNOWN 0,0)
----- End Fatal Exception -------------------------------------------------
```

looks like something is missing in the conditions.
The failing driver command is:

```
cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi -s GEN,SIM,DIGI,L1,DIGI2RAW --mc --scenario=pp -n 10 --conditions auto:run3_mc_HIon --relval 9000,50 --datatier "GEN-SIM-RAW" --eventcontent RAWSIM --customise=HLTrigger/Configuration/CustomConfigs.L1T --era Run3_pp_on_PbPb_2023 --fileout file:RelVal_Raw_HIon_MC.root
``` 

and `run3_mc_HIon` maps to:

https://github.com/cms-sw/cmssw/blob/31c88c081311b010cf76884b7905d6ec85a608f9/Configuration/HLT/python/autoCondHLT.py#L40

@cms-sw/hcal-dpg-l2 @cms-sw/alca-l2 FYI

**Comment by civanch** [comment]
Now I disable ZDC...

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
There is known MkFit problem and new one for WF 312.0 - needs to be understood. In general, regression is expected in this PR.

**Comment by civanch** [comment]
+1

I think this PR can be merged. Discovered problem #43582 should  be fixed for full ZDC simulation. It should be done in next PRs.

**Comment by rappoccio** [comment]
+1

**Comment by makortel** [comment]
This PR broke DBG builds, see https://github.com/cms-sw/cmssw/issues/43666

**Pull request merged**
