### PR TITLE
Phase 2 Integration GTTFileReader expansion and refactor 

### PR DESCRIPTION
**Pull request by NJManganelli**
#### PR description:

The aim of this PR is to extend the capability of GTT workflows by validating and fixing a minor discrepancy in the loading of vertices from APx/EMPv2 formatted buffer files (APx/Serenity GTT boards), and add a partial implementation for doing the same for tracks written to buffer files (at the stage of "GTT Input"). Along the way, the code is refactored to move common elements from GTTFile{Reader,Writer}.cc plugins to a GTTInterface.h header, as a code/maintainability improvement. Some compile-time constants are made python-configurable (as advised by Tom Williams).

The changes and capabilities added here are not invoked in a typical Phase 2 L1T workflow, and are currently only called for the L1Trigger/DemonstratorTools/test/gtt/createFirmwareInputFiles_cfg.py tool (which is used for creating - and now consuming - buffer files in APx/EMPv2 format for integration tests, and as **stepping stones towards eventual Phase 2 GTT packer/unpacker**)

Presented in https://indico.cern.ch/event/1352629/contributions/5695626/attachments/2763970/4814068/NickManganelli_GTT_01_12_2023.pdf
PR validation:

This PR passes
scram b code-format
scram b code-checks
scram b
runTheMatrix.py -l limited -i all --ibeos
GTT Firmware workflows: cmsRun createFirmwareInputFiles_cfg.py maxEvents=1008 format=W inputFiles=L1Trigger/DemonstratorTools/python/TT_TuneCP5_14TeV-powheg-pythia8_Phase2Spring23DIGIRECOMiniAOD-PU200_131X_mcRun4_realistic_v5-v1_GEN-SIM-DIGI-RAW-MINIAOD_APxBuffers_cff.py tracks=X vertices=Y readerformat=Z (X and Y in 'donotload' , 'load' , 'overwrite' ; W and Z in 'APx' or 'EMPv2'

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is the port from the cms-l1t-offline integration branch to the master branch
https://github.com/cms-l1t-offline/cmssw/pull/1188

### CODE REVIEW

**Comment by NJManganelli** [comment]
Number of commits grew quite a bit. If squashing some of them is strongly desired, please let me know

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@NJManganelli Is this ready from your side? You mentioned an issue in your last message in https://github.com/cms-l1t-offline/cmssw/pull/1188. I think our review was done.

**Comment by NJManganelli** [comment]
> @NJManganelli Is this ready from your side? You mentioned an issue in your last message in https://github.com/cms-l1t-offline/cmssw/pull/1188. I think our review was done.

All good on my side. The issue mentioned prevents switching to the alternative BoardDataReader constructor as Tom suggested, but I don't have time to try debugging that issue for this PR. I will try to reproduce and submit an issue later on.

**Comment by subirsarkar** [comment]
@cmsbuild Please test

**Comment by aloeliger** [comment]
+l1
- Already reviewed by L1 as part of https://github.com/cms-l1t-offline/cmssw/pull/1188
- @cms-sw/upgrade-l2

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
> Number of commits grew quite a bit. If squashing some of them is strongly desired, please let me know

We are currently requiring squashing in the more obvious cases.

In general however, grouping commits is encouraged in order to simplify the history in cmssw.

**Pull request merged**
