### PR TITLE
New DDTrackerRingAlgo algorithm + Baseline_tilted xml output from tkLayout

### PR DESCRIPTION
**Pull request by ghugo83**
DDTrackerRingAlg tilts and positions n copies of a module at prescribed phi values within a ring. The module can also be flipped if requested.

### CODE REVIEW

**Comment by mark-grimes** [comment]
@ghugo83, you can modify an open pull request by pushing commits to the same branch.  Probably easier since it keeps the conversation all in one place.

**Comment by mark-grimes** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild  - the errors are unrelated to this PR

**Comment by smuzaffar** [comment]
please test

**Comment by ghugo83** [comment]
@mark-grimes @ianna @smuzaffar 
Are the errors related to this PR?
Because the tracker's tilted layout shouldn't of course be run on cmssw yet. The set of xml is just given as example of use here.
The interest of this PR is in DDTrackerRingAlgo.

**Comment by smuzaffar** [comment]
These are AddOn Tests which are failing. I guess we should not run AddOn Tests for SLHC releases ...... right?

**Comment by ghugo83** [comment]
Yes, AddOn Tests shouldn't be run for SLHC releases.
Please note that my last commit will not have any influence on the previous errors.

**Comment by smuzaffar** [comment]
please test

cms-bot is updated to not run addon tests for SLHC releases

**Comment by ghugo83** [comment]
thanks ;)

**Comment by mark-grimes** [comment]
Correct, addon tests should not be run for SLHC so the previous test failures can be ignored.  I was a little concerned about the `new` at [Geometry/TrackerCommonData/plugins/DDTrackerRingAlgo.cc:L162](https://github.com/cms-sw/cmssw/pull/10920/files#diff-8fa1dfd991be5357eb8c22144c15a6bcR162) but I've followed it through and `DDRotation` does indeed take ownership.  In principal this pull request is okay since it doesn't change any of the default running, but I was going to test the new geometry privately before merging.

**Comment by delaere** [comment]
I visualized the new geometry with fireworks (using a recipe from Gabrielle while the xml were not yet in the PR) and everything looks fine.

**Comment by ghugo83** [comment]
Before running Fireworks, please of course edit src/Fireworks/Geometry/python/cmsShowFF_displayGeom_cfg.py, replacing :
process.load("Geometry.CMSCommonData.cmsIdealGeometryXML_cfi")
by :
process.load("Geometry.CMSCommonData.cmsExtendedGeometryPhase2Baseline2015TiltedXML_cfi")

Then :
cmsShowFF -c $CMSSW_RELEASE_BASE/src/Fireworks/Core/macros/simGeo.fwc Fireworks/Geometry/python/cmsShowFF_displayGeom_cfg.py
to visualize the tilted geometry.


This week I also implemented cones instead of tubes for the tilted rings volumes. It will not affect the geometry visualization but if you want I can push these updated xml.

**Comment by mark-grimes** [comment]
After a lot of messing around I found out visualisation doesn't work with my external monitor plugged in.  Must be a bug in my X11.  Anyway...

All looks okay, but can't see anyway that this geometry can be used.  Surely it also needs a cff file in `Configuration/Geometry` so that it can be used with cmsDriver?  I had a go using `Configuration/Geometry/python/GeometryExtendedPhase2TkBE5DPixel10D_cff.py` as a template but got segfaults in gen-sim.  I guess the numbering is also different or something, I'll let the experts figure that out.

I'll assume the other components are coming later.

**Comment by mark-grimes** [comment]
merge

**Comment by mark-grimes** [comment]
P.S. Is a version of this PR also in for 7_6_X?  If so could you post the number?

**Comment by ghugo83** [comment]
Thanks ;)
Yes exactly, the numbering will be different.
There is not a version of this PR for 7_6_X but Gaelle Boudoul told me she will take care of it.
So there are two additional commits :
- cones instead of rings;
- globalRotstr naming (nothing to do with cones, sorry for the commit's message)
Have a good wd!

**Comment by mark-grimes** [comment]
merge

Try again, maybe the extra commit upset cmsbot.

**Comment by boudoul** [comment]
FYI : Corresponding PR in 76X PR #11249

**Pull request merged**
