### PR TITLE
Cleanup and update to stay in sync with modifications done in 75X

### PR DESCRIPTION
**Pull request by iik1997**
See discussion in #12544 and #12570. This update should help to avoid crashes of Castor online DQM  in case if recent modifications of Castor/ZDC unpackers in 75X are going to be propagated also to 76X (and 80X).
@popovvp, @cbaus, @vanbesien,  @hvanhaev

### CODE REVIEW

**Comment by iik1997** [comment]
Similar PR for 80X: https://github.com/cms-sw/cmssw/pull/12621

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
