### PR TITLE
[12_1_X] Improve DQM beamspot clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Title says it all - Backport of #35932

#### PR validation:
Validated with DQM playback system and also during data-taking, see https://github.com/cms-sw/cmssw/pull/35918#issuecomment-956087758 and https://github.com/cms-sw/cmssw/pull/35918#issuecomment-956119341 for the outcome of the data-taking.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of #35932

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #35932

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
please test with #35930

**Comment by jfernan2** [comment]
+1
Backport tested in Online DQM at P5

**Comment by perrotta** [comment]
+1
- Simple update: even if not strictly needed for the premix sample (digi) production, it can be safely backported to 12_1
- Already succesfully merged in the master release and in 12_0_X

**Pull request merged**
