### PR TITLE
TTTrack bug fix for POCA 

### PR DESCRIPTION
**Pull request by tomalin**
There was a bug in the variable "thePOCA", which represents the point of closest approach of the helix to the line x=y=0. This will affect anyone who uses the function TTTrack::POCA().

However, people using other TTTrack functions, such as those giving access to the helix parameters, will be unaffected.

I'd suggest back-porting this fix to CMSSW 11.1, if possible, as although I suspect few people use TTTrack::POCA(), the bug will confuse anyone who does.

### CODE REVIEW

**Comment by silviodonato** [comment]
@tomalin please make also the backport for 11_1_X

**Comment by tomalin** [comment]
I've added a second PR, https://github.com/cms-sw/cmssw/pull/30666 , identical to this one, except that it (hopefully) backports this bug fix to 11_1_X.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
