### PR TITLE
Run3-hcx307 Bug fix for evaluation of tShift in HFFibre

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix for evaluation of tShift in HFFibre

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

May need back porting to 12_0

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
@bsunanda   Lev insists this change is undesired...

**Comment by bsunanda** [comment]
@civanch Please do not approve this PR. I have some doubt about this

**Comment by civanch** [comment]
hold

**Comment by bsunanda** [comment]
After discussion with Salavat and Lev I found that these changes are not needed

**Pull request closed without merging**
