### PR TITLE
No need to check into base classes of std classes in DictionaryTools.

### LINKED ISSUE #41865: [GCC12] Missing dictionary for __pair_base in many workflows
Many el8_amd64_gcc12 workflows (that are able to get run despite of the build failures) fail with an exception along
```
----- Begin Fatal Exception 03-Jun-2023 17:13:23 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Calling ProductRegistry::initializeLookupTables
Exception Message:
No data dictionary found for the following classes:

  __pair_base<csc::L1Track,MuonDigiCollection<CSCDetId,CSCCorrelatedLCTDigi> >
  __pair_base<int,bitset<6> >

Most likely each dictionary was never generated, but it may
be that it was generated in the wrong package. Please add
(or move) the specification '<class name="whatever"/>' to
the appropriate classes_def.xml file along with any other
information needed there. For example, if this class has any
transient members, you need to specify them in classes_def.xml.
Also include the class header in classes.h

A type listed above might or might not be the same as a
type stored in the Event (or Lumi or Run). Instead it might
be the type of a data member, base class, wrapped type, or
other object needed by a stored type. Below is some additional
information which lists the stored types associated with the
types whose dictionaries were not found:

  std::vector<std::pair<csc::L1Track,MuonDigiCollection<CSCDetId,CSCCorrelatedLCTDigi> > > (produced in current process)
  std::vector<std::pair<int,std::bitset<6> > > (produced in current process)

Missing dictionaries are associated with these branch names:

  cscL1TrackCSCDetIdCSCCorrelatedLCTDigiMuonDigiCollectionstdpairs_simCsctfTrackDigis__HLT.
  int6stdbitsetstdpairs_mix_AffectedAPVList_HLT.

If you do not need these branches and they are not produced
in the current process, an alternate solution to adding
dictionaries is to drop these branches on input using the
inputCommands parameter of the PoolSource.
----- End Fatal Exception -------------------------------------------------
```
(e.g. https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_2_X_2023-06-03-1100/pyRelValMatrixLogs/run/3.0_ProdQCD_Pt_3000_3500/step2_ProdQCD_Pt_3000_3500.log#/)

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/41865. By @pcanal (https://github.com/cms-sw/cmssw/issues/41865#issuecomment-1583447001).

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

for clean dqm comparison

**Comment by smuzaffar** [comment]
@makortel , this looks good to go in. It does fix the gcc12 relvals

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
