### PR TITLE
Allow TrackClusterRemover to work on either pixel or strip clusters alone (92X backport)

### PR DESCRIPTION
**Pull request by JanFSchulte**
Right now, the TrackClusterRemover uses both pixel and strip clusters at all times. This PR introduces the possibility to have it run on either of them alone (92X backport of #19543 for HLT)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- (Same as #19543 in the master)
- This PR add protections and allow running in case there are only pixel or strip clusters
- No effect on jenkins tests, as expected

**Comment by JanFSchulte** [comment]
@davidlange6 Since you merged the PR for the master branch, could you also merge this backport? It's actually more important for HLT at the moment. Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
