### PR TITLE
Utilities/StaticAnalyzers: only report the use of TFileService functions if the parent function does not override a edm::one function

### PR DESCRIPTION
**Pull request by gartung**
Tested locally.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by gartung** [comment]
@makortel I am working on the output script.

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
hold

**Comment by gartung** [comment]
unhold

**Comment by gartung** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
