### PR TITLE
[Misc2][clang-tidy] make deleted function public

### PR DESCRIPTION
**Pull request by smuzaffar**
Cleanup for clang-tidy warning `deleted member function should be public [modernize-use-equals-delete]`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
+core

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34691	77f04ba
- technical
- reco is only in EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.h

**Comment by jfernan2** [comment]
+1

**Comment by tvami** [comment]
+alca

**Comment by ggovi** [comment]
+1

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by perrotta** [comment]
@cms-sw/generators-l2 @cms-sw/l1-l2 this looks rather technical, and simple: do you have any commment or complain? Otherwise, we can merge

**Comment by perrotta** [comment]
+1
(@cms-sw/l1-l2 @cms-sw/generators-l2  this PR is technical, and changes are quite trivial: just complain in case you have problems with it, and we'll revert it)

**Comment by perrotta** [comment]
merge

**Comment by agrohsje** [comment]
+generators
as before: a trivial pr but when checking on friday the label was still tests rejected.

**Pull request merged**
