### PR TITLE
Use dxy sign of GSF track instead of IPTools for pat::Electron

### PR DESCRIPTION
**Pull request by afiqaize**
#### PR description:

Propagate the dxy sign fix for muons (#28753) to electrons as well.

#### PR validation:

Made nAODs from a bb4l AOD samples (~6k events) before and after the code change, verified that only dxy sign changed.

A backport to 106X ala #29537 can be made if needed.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
+1
- The code changes are in line with the PR description and completely similar to those already integrated for muons with #28753
- Jenkins tests pass and show differences only in electron dxy and its error in nanoAOD

**Comment by silviodonato** [comment]
+1

**Comment by perrotta** [comment]
@afiqaize @SohamBhattacharya : do you plan to backport this to 10_6_X (similarly to what was done for the muons with #29537)? Please let us know, and prepare a backport PR at your earliest convenience if needed

**Comment by afiqaize** [comment]
@perrotta yes we plan to do so. The PR will come today.

**Pull request merged**
