### PR TITLE
Run4-hgx265 Update tests for ESGetToken and also for checking content in geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update tests for ESGetToken and also for checking content in geometry

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
