### PR TITLE
Fix addOnTestsHLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix addOnTestsHLT

#### PR validation:

TSG tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
urgent
(for next 13_3 release)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
