### PR TITLE
MTD geometry: Fix MTDGeometryBuilder text to avoid rounding issues with alternative architectures

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The integration of https://github.com/cms-sw/cmssw/pull/46683 is causing failures in the ```Geometry/MTDGeometryBuilder``` unit test on both aarch64 and MULTIARCHS builds. This appears an issue with numerical precision. To address it:

- position precision printouts is limited to 2 digits (i.e. 100 microns) for unit test output, while keeping 4 digits in the regular log file for direct inspection;
- the numerical accuracy requited for rotation checks is moved from std::numeric_limits<float> to 10 times as big, to prevent failure on aarch64.

#### PR validation:

Code runs, provides the desired output, and does not trigger any ```DIFFERENCE``` message on lxplus-arm (el9_aarch64_gcc12) vs cmsdev45 (el8_amd64_gcc12). ```cms-data/Geometry-TestReference``` reference file is built on the default architecture.

### CODE REVIEW

**Comment by fabiocos** [comment]
type mtd

**Comment by fabiocos** [comment]
type bugfix

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/17

**Comment by bsunanda** [comment]
+geometry

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/17 for CMSSW_15_0_MULTIARCHS_X/el8_amd64_gcc12

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
https://github.com/cms-data/Geometry-TestReference/pull/17 was needed to go with this PR.

**Pull request merged**
