### PR TITLE
[91X] Offline DQM modules for L1 Trigger, Stage 2 CaloLayer2 (Electrons + Photons)

### PR DESCRIPTION
**Pull request by kreczko**
This PR includes Offline DQM components for the Stage 2 Calo Layer 2 objects and is an extension of #16704. In particular, this DQM focuses on electrons and photons and their L1T-reco comparison including the L1T emulator.
Furthermore, it includes two fixes to #16704 where histograms were assigned the incorrect names.

This PR has been tested on the DoubleEG dataset in `CMSSW_9_1_0_pre1`.

@dmitrijus & @rekovic please review and sign off.

@bortigno This should complete the first draft for the two DQM modules.

@davidlange6 tried not to replicate mistakes from #16704, but apologies in advance if I did.
Please beware: as in the previous PR, the biggest file, `L1TEGammaOffline.cc`, is not loaded by default.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
@rekovic & @dmitrijus : I've fixed the problem that occurred in the last iteration of testing.
Could you please trigger the tests again?

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
@davidlange6 The tests have passed, looking forward to the feedback.
@rekovic @mulhearn one of you still needs to sign it.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
