### PR TITLE
"is not" -> "!=" in PatAlgos trigTools.py 

### PR DESCRIPTION
**Pull request by slava77**
to check if a simple solution to #33967  can work

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- addpkg = PhysicsTools/PatExamples,RecoMET/METFilters,TopQuarkAnalysis/Configuration

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> DQMHistoTests: Total failures: 357

these seem unrelated, but better rerun again after the 2300 IB shows up

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34253	31f276e
- technical
- jenkins tests pass and comparisons with the baseline show no relevant changes
    - there are differences in several ML inference plots : in 25.0 in what appears to be ONNX-based jet tag, and in 1325.81 one ONNX-based jet tag and one TF-based deep-tau ID. Looking at the job logs, the machines are not the same: orig has SSE4.1 SSE4.2 AVX while the PR has  SSE4.1 SSE4.2 AVX AVX2 FMA. Some small differences are expected in this case.

**Comment by qliphy** [comment]
+1

**Pull request merged**
