### PR TITLE
EP code bug fix

### PR DESCRIPTION
**Pull request by BetterWang**
Same as #11835, urgent bug fix for HI run.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11836 83ea180c3f7ad0261a771a6824a4879bd0742812

Small bug fix for Heavy Ions in HiEvtPlaneAlgos.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11836/8938/summary.html) against baseline CMSSW_7_5_X_2015-10-15-2300 show no significant differences. An extended test of workflow 140.53_RunHI2011 with 70 events against baseline CMSSW_7_5_X_2015-10-15-1100 also shows no significant differences.

**Comment by slava77** [comment]
@BetterWang 
what's the effect of the fix and where does it become important?
We signed off, but mainly because there is no visible effect in the tests done.

**Comment by slava77** [comment]
regarding https://github.com/cms-sw/cmssw/pull/11836#issuecomment-149050665
I found an answer in the 76X version of the  PR
Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
