### PR TITLE
Bug fix for tag lock clean up at session closing time

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

We provide a fix for a bug affecting the implicit cleanup of Tag locks when a DB session is being closed/deleted.
The available testing workflow has been rewritten to provide a more representative test case.

#### PR validation:

Unit tests and integration tests.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
please test
refresh

**Comment by francescobrivio** [comment]
+alca
 - bugfix
 - tests passed with no differences as expected

**Comment by qliphy** [comment]
+1

**Pull request merged**
