### PR TITLE
[NanoAOD, JMENano] Updates for Nano and JMENano

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR aims to add changes related to NanoAOD, JMENanoAOD and ensuring consistency of PuppiProducer instances when processing MiniAODs for production and analysis. The following changes are made:

**NanoAOD**
These changes are intended to be for the next NanoAOD campaign (`v13`?)
- Add missing `RUN3WINTER22PUPPIrunsBCDEprompt` JetID version for jets.
- Add (puppi-weighted) charged and neutral multiplicities for jets.
- Add HF energy fractions for AK4 jets.
- Add energy fractions for AK8 jets.
- Add jet area for subjets. Fix the documentation of subjet collection.

**JMENanoAOD**
- Add Run-3 JetIDs.
- Remove AK8CHS jet collection.
- Reduce content for AK4CHS collection by removing PUID/QGL tagger inputs and most flavour-tagging discriminants.
- Increase pT thresholds for AK4CHS, AK4GEN, AK8GEN.
- Rename some branches.

**PuppiProducer consistency**
- Improve `setupPuppiForPackedPF()` in `jetTools.py` by adding `packedpuppiNoLep` instance.
- In `runMETCorrectionsAndUncertainties.py`, make it optional to provide a different `PuppiProducer` module label rather than stick to a hard-coded label (`puppiNoLep`). Set the previously hard-coded label as the default option.

#### PR validation:
- passes the standard runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes the following NanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 2500.0,2500.001,2500.002,2500.01,2500.011,2500.012,2500.1,2500.2,2500.21,2500.3,2500.31,2500.4`

#### If this PR will be backported please specify to which release cycle the backport is meant for:
To be backported to earlier 13_X releases for Run-3 JMENano production but not 13_0_X because there is already the ongoing 2023 NanoAOD production.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by simonepigazzini** [comment]
Hi @nurfikri89, do you plan to add the MINI from MINI functions in this PR?

**Comment by nurfikri89** [comment]
> Hi @nurfikri89, do you plan to add the MINI from MINI functions in this PR?

Hi @simonepigazzini, no I will follow up with a separate PR. Given the latest plan to reMini 2022 samples with 13X, we can already request a JMENano production for 2022 and 2023 after this PR is merged.

**Comment by simonepigazzini** [comment]
+1

**Comment by mandrenguyen** [comment]
please test
Argh, i'm sorry I can't see the test results anymore.
Hopefully reco should sign quickly.

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
