### PR TITLE
Realistic vertex smearing for 2015 PbPb MC (81X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
Update the vertex smearing based on final beamspot fits to the data (taking into account the shift of the pixel detector).   The corresponding reco beamspot will be put in a GT and added shortly.
Since the reco beamspot tag is not yet in place, the HI reco relval workflow is not updated to use this vertex smearing.     I tested the PR with:

cmsDriver.py  MinBias_8TeV_pythia8_TuneCUETP8M1_cff --conditions auto:run2_mc_hi --scenario HeavyIons -n 1 --eventcontent RAWSIM --relval 2000,1 -s GEN,SIM --datatier GEN-SIM --beamspot RealisticHICollision2015 --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1_HI

There will also be a backport to 75X.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@mandrenguyen , you removed VtxSmearedUpdatedHICollision2015_cfi, please, confirm that this "Updated" beam-spot is not used anywhere.

**Comment by mandrenguyen** [comment]
@civanch :  Indeed it was never used anywhere.  We intended to have an improved guess, but in the end decided to just use the initial predictions.  Now that the data is recorded, I think "Realistic" is the appropriate name.

**Pull request merged**
