### PR TITLE
Mini-PR: Remove duplicated fm and mum constants

### PR DESCRIPTION
**Pull request by ghugo83**
These constants are duplicated and were defined inside DD4hep already.

@cvuosalo

### CODE REVIEW

**Comment by cvuosalo** [comment]
@ghugo83 The XML files should be given a new version (`v2`).

**Comment by ghugo83** [comment]
>The XML files should be given a new version (v2).

The v1 XML versions are actually unused, and were the ones introducing the duplicated constants, so I removed the XML change.
The duplication of constants appeared fully by the their definition in DDDefinitions2Objects

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911, 11650.911

**Comment by civanch** [comment]
@ghugo83 , why there is no regression?

**Comment by ghugo83** [comment]
@civanch This was just to remove duplicate definitions, there should not be any regression (just less warnings on a dd4hep run).

**Comment by cvuosalo** [comment]
Problem is not fixed yet. The DD4hep workflows report:

Evaluator        WARN  +++ Overwriting variable: name=fm value=1e-12*m  Evaluator::Object : existing variable [setVariable error]
Evaluator        WARN  +++ Overwriting variable: name=mum value=1e-6*m  Evaluator::Object : existing variable [setVariable error]

**Comment by cvuosalo** [comment]
There is also a big new problem. I don't think it is due to this PR:

%MSG-w EcalGeom:  OscarMTProducer:g4SimHits 07-Apr-2021 21:16:39 CEST  Run: 1 Event: 1
ECalBarrelNumberingScheme::getUnitID(): Not enough levels found in EcalBaseNumber ( 11) Returning 0
%MSG

There are thousands of these messages in the workflow logs.

**Comment by cvuosalo** [comment]
The contents of the simulation geometry are very slightly changed by this PR. Maybe that is enough to trigger a change in the random seeds?

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
Could you point where is the previous definition of "mum" and "fm"?

**Comment by davidlange6** [comment]
Why would that have happened?

**Comment by ghugo83** [comment]
>Problem is not fixed yet. The DD4hep workflows report:
Evaluator WARN +++ Overwriting variable: name=fm value=1e-12m Evaluator::Object : existing variable [setVariable error]
Evaluator WARN +++ Overwriting variable: name=mum value=1e-6m Evaluator::Object : existing variable [setVariable error]

I have checked and re-checked, and this PR properly removes these specific error messages. Had you recompiled?

>The contents of the simulation geometry are very slightly changed by this PR. Maybe that is enough to trigger a change in the random seeds?

In theory, the geometry should have not change at all by removing duplicated constants.
Then it occurs that `fm` was wrong in CMS anyway (that's obviously 10^(-15)m )...

>Could you point where is the previous definition of "mum" and "fm"?
Now instead, the XML parser rely on the DD4hep variables defined in:https://github.com/AIDASoft/DD4hep/blob/master/DDParsers/src/Evaluator/setSystemOfUnits.cpp#L265 
(The errors were thrown from within DD4hep: the DD4hep evaluator during XML parsing was complaining because it also had access to DDParsers/src/Evaluator/setSystemOfUnits.cpp)



```
Evaluator        WARN  +++ Overwriting variable: name=fm value=1e-12*m  Evaluator::Object : existing variable [setVariable error]
Evaluator        WARN  +++ Overwriting variable: name=mum value=1e-6*m  Evaluator::Object : existing variable [setVariable error]
```

**Comment by ianna** [comment]
> Then it occurs that `fm` was wrong in CMS anyway (that's obviously 10^(-15)m )...

`1×10−15 m` is not the same as` 1×10−15 * m`. It is `"1e-12*m"` because `m == 1000` ;-)

**Comment by cvuosalo** [comment]
@ghugo83 I think this PR is fine now. Earlier I accidentally wrote an incorrect message that I then deleted, and I think you saw that in your email, but the PR is OK.

**Comment by cvuosalo** [comment]
Concerning the comparison differences in this PR: They are due to a change in the simulation histories. It seems surprising that the simulation history would change with the tiny change in the simulation geometry caused by this PR, but that may well be the case here.
Searching the XML files, it appears that `fm` is only used in this way: "0*fm". Maybe the change from `0e-12` to `0e-15` in many places was enough to cause a change in the simulation history?

**Comment by davidlange6** [comment]
Well unless one divides or multiplies by these numbers....

On Apr 9, 2021 9:16 PM, Carl Vuosalo ***@***.***> wrote:

Concerning the comparison differences in this PR: They are due to a change in the simulation histories. It seems surprising that the simulation history would change with the tiny change in the simulation geometry caused by this PR, but that may well be the case here.
Searching the XML files, it appears that fm is only used in this way: "0*fm". Maybe the change from 0e-12 to 0e-15 in many places was enough to cause a change in the simulation history?

**Comment by ghugo83** [comment]
>Maybe the change from 0e-12 to 0e-15 in many places was enough to cause a change in the simulation history?
Not likely, this variable does not seem used aside from test XML files anyway.

I think the tiny change in simulation history is not related.

**Comment by cvuosalo** [comment]
@ghugo83 Actually, `fm` is used quite a bit. It is in `beampipe.xml`, `cavern.xml`, and others.

**Comment by civanch** [comment]
Is it really needed to have a dimension in fm? Geant4 geometry work within tolerance, the default kTolerance=1.0e-9 mm. Any shift or thickness below the tolerance is meaningless and may be problematic, because a track may have trouble to understand in which volume to make next step.

**Comment by cvuosalo** [comment]
@civanch From my scan of the XML files, it looks like `fm` is only used with `0*fm`, that is, the femtometer values are always zero, so they shouldn't cause any problem for Geant4.

**Comment by cvuosalo** [comment]
@silviodonato Could this PR please be included in pre6?

**Comment by silviodonato** [comment]
please test

> I think the tiny change in simulation history is not related.

Let's try again. @cvuosalo yes, it can go in pre6, but I would wait until we understand the origin of the change in the history

**Comment by civanch** [comment]
At least, "mum" is defined and used in https://cmssdt.cern.ch/lxr/source/Alignment/CocoaApplication/test/table2DWithMirror.xml and there is a definition https://cmssdt.cern.ch/lxr/source/Alignment/CocoaUtilities/src/ALIUtils.cc It is likely not relevant. "fm" is used in line 57 of https://cmssdt.cern.ch/lxr/source/Alignment/CocoaApplication/test/table2DWithMirror.xml - should be replaced by 0. Also, likely not relevant.

**Comment by silviodonato** [comment]
@cms-sw/geometry-l2 could you confirm that the changes are understood and you want this PR in pre6?

**Comment by cvuosalo** [comment]
@silviodonato Yes, I confirm we want this change put into pre6. This PR changes the geometry, though only slightly, so that apparently triggers a change in the simulation history and causes the comparison differences. These differences are only statistical fluctuations.

**Comment by silviodonato** [comment]
+1
the differences appear only in the DD4HEP wf 11634.911

**Pull request merged**
