### PR TITLE
NanoAOD for MiniAODv2 - part 2, e/gamma (master)

### PR DESCRIPTION
**Pull request by gpetruc**
Second set of NanoAOD updates: e/gamma smearing, Fall17 photon id, LHE particles, updated b-jet regression (https://github.com/cms-sw/cmsdist/pull/3887)
This is the master PR corresponding to https://github.com/cms-sw/cmssw/pull/22753

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by arizzi** [comment]
please test with cms-sw/cmsdist#3887

**Comment by gpetruc** [comment]
please test with cms-sw/cmsdist#3887

**Comment by prebello** [comment]
+1

**Comment by smuzaffar** [comment]
cms-bot ping

**Comment by fabiocos** [comment]
@kpedro88 could you please check?

**Comment by kpedro88** [comment]
+1

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3887

**Comment by fabiocos** [comment]
+1

**Pull request merged**
