### PR TITLE
Hlt updates on top of745plus epsilon 76X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Need a separate branch for 76X
Replaces 76X PR #9775.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by civanch** [comment]
+1

**Pull request merged**
