### PR TITLE
Adjustments to HCAL HF TP 2016 fine-grain

### PR DESCRIPTION
**Pull request by matz-e**
Changes to the HCAL HF fine-grain, after problems with #14471 became apparent in DQM (see #15389):
- separate HF threshold from HBHE
- includes back-port of #15514 (expanding the compression methods to allow several FG bits)
- properly sets FG bit 1 for HF TP (@nsmith-, I misread your comment [here](https://github.com/cms-sw/cmssw/pull/14471#issuecomment-218728012))
- access with `tp.t0().fineGrain(1)`

Creating this PR now for DQM to test.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by matz-e** [comment]
Sorry, had to make some additional adjustment after talking with @jmmans. This should now match the next (i.e. upcoming) firmware version for the HCAL HF TPs.

**Comment by mmusich** [comment]
please test

**Comment by abdoulline** [comment]
@rekovic, @mmusich, @mulhearn
it stays idle for 17 days...

**Comment by rekovic** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
