### PR TITLE
Move FFTJet to JetMETCorrections/FFTJetObjects

### PR DESCRIPTION
**Pull request by davidlange6**
Break part of the circular dependency between CondFormats/(DataRecord,JetMETObjects) and JetMETCorrections/FFTJetObjects. I believe this undoes part of the changes made in my previous (and apparently unsuccessful) attempt. This file appears to be unused..

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
