### PR TITLE
[14.0.X] add `Era_Run3_2024`, `Era_Run3_2025`, Tier0 reco scenario for 2024, and change default era in `PyReleaseValidation`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43761

#### PR description:

In response to https://github.com/cms-sw/cmssw/issues/43756, following https://github.com/cms-sw/cmssw/pull/41271#issuecomment-1506968258:
   * add `Era_Run3_2024`, `Era_Run3_2025` (currently straight copies of Run3) 
   * add Tier0 reco scenario for 2024
   * change default era in `PyReleaseValidation` for 2024 MC workflows

#### PR validation:

   * ` runTheMatrix.py --what upgrade -l 12824.0` runs fine
   * `scram b runtests` runs fine:
   
```
Creating test log file logs/el9_amd64_gcc12/testing.log
Pass    2s ... Configuration/DataProcessing/TestConfigDP_1
Pass   14s ... Configuration/DataProcessing/TestConfigDP_10
Pass   12s ... Configuration/DataProcessing/TestConfigDP_11
Pass  150s ... Configuration/DataProcessing/TestConfigDP_12
Pass  131s ... Configuration/DataProcessing/TestConfigDP_2
Pass   24s ... Configuration/DataProcessing/TestConfigDP_3
Pass   33s ... Configuration/DataProcessing/TestConfigDP_4
Pass  273s ... Configuration/DataProcessing/TestConfigDP_5
Pass   98s ... Configuration/DataProcessing/TestConfigDP_6
Pass  155s ... Configuration/DataProcessing/TestConfigDP_7
Pass  228s ... Configuration/DataProcessing/TestConfigDP_8
Pass   11s ... Configuration/DataProcessing/TestConfigDP_9
Pass    1s ... Configuration/PyReleaseValidation/test-das-selected-lumis
Pass  175s ... Configuration/PyReleaseValidation/test-runTheMatrix-interactive
```   

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of  https://github.com/cms-sw/cmssw/pull/43761 to the data-taking release.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/upgrade-l2 @cms-sw/pdmv-l2 kind ping.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
