### PR TITLE
Update track-PV and track-jet associations in tracking validation, add more collections to standalone mode

### PR DESCRIPTION
**Pull request by makortel**
This PR contains the following updates to tracking validation
- Associate tracks to PV by simple dz(PV) cut instead of the PV sorter (in "fromPV" variants of MultiTrackValidator)
  - Main motivation is to be able to do the same association with tracking-only information, and whether running (tracking-only) RECO on the fly or using RECO+DIGI as an input
- Monitor the tracks from AK4 PFJet constituents instead of those in cone of DeltaR < 0.4
  - It is more interesting to us to monitor what exactly gets clustered
- For standalone mode (not used in RelVals), add iteration selections using originalAlgo and algoMask
- Generalize the configuration of monitored iterations such that it will be straightforward to customize the iterations for e.g. Phase1 tracking with eras

Tested in CMSSW_8_0_X_2015-11-12-1100, expecting changes in `Tracking/TrackFromPV`, `Tracking/TrackFromPVAllTP`, and `Tracking/Track/cutsRecoAK4PFJets_trackingParticleRecoAsssociation` DQM folders.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
ping

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
