### PR TITLE
`SiStripZeroSupperssion`: discard processing unphysical clusters in `suppressHybridData`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is meant as a patch for the issue described at https://github.com/cms-sw/cmssw/issues/43078, where the fix consists simply in discarding the APVs in which the request of the strip number is higher than the maximum allowed in the module.

   * 5318f5d1c371fdb0825c96f1f1dfdd1118d17e00: adds a utility method to `SiStripDetId` that returns if the underlying Strip module is connected to 4 or 6 APVs.
   * ca4a99f3ba9d71e6973f88e120b7bc44de431bc3: discard strip digi payloads with unphysical numer of strips in `processHybrid`, using `SiStripDetId::numberOfAPVs()`.

#### PR validation:

Run the following script:

```bash
#!/bin/bash -ex

# CMSSW_14_1_5_patch1       
                                                                                              
hltGetConfiguration run:388419 \
  --globaltag 141X_dataRun3_HLT_v1 \
  --data \
  --no-prescale \
  --no-output \
  --max-events -1 \
  --input file:converted.root  > hlt.py

# Define a function to execute each iteration of the loop
process_file() {
    inputfile="$1"
    outputfile="${inputfile%.root}"
    cp hlt.py hlt_${outputfile}.py
    sed -i "s/file:converted\.root/\/store\/group\/tsg\/FOG\/error_stream_root\/run388419\/${inputfile}/g" hlt_${outputfile}.py
    cmsRun hlt_${outputfile}.py &> "${outputfile}.log"
}

# Export the function so it can be used by parallel
export -f process_file

# Find the root files and run the function in parallel using GNU Parallel
eos ls /eos/cms/store/group/tsg/FOG/error_stream_root/run388419/ | grep '\.root$' | parallel -j 4 process_file
```

which runs over the list of error stream files from [run-388419](https://cmsoms.cern.ch/cms/runs/report?cms_run=388419) ([elog/1247892](http://cmsonline.cern.ch/cms-elog/1247892)) where we had in excess of 1k HLT crashes, and didn't observe residual crashes. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, if accepted it will be backported to CMSSW_14_1_X for data-taking purposes

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
test parameters:
   * workflows = 161, 161.02, 161.03, 161.1, 161.2, 161.3, 161.4, 180.0, 180.1, 181, 181.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
fixes https://github.com/cms-sw/cmssw/issues/43078

**Comment by jfernan2** [comment]
+1

**Pull request merged**
