### PR TITLE
GEM DQM updates - full GE1/1

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR updates and extends the part of onlineDQM for GEM. The details are following: 

 - The existing parts are fixed to match the VFAT version which is used in CMSSW currently
 - Summary plot is added
 - Histograms which displays the status of devices (AMCs, GEBs, VFATs) by time are added

Please see [this](https://indico.cern.ch/event/881121/contributions/3712072/attachments/1972921/3282493/20200120_DQM_Online_PR.pdf) to check more details, especially the visualization with [DQM GUI](https://github.com/dmwm/deployment) (there is also an update for GEM part for onlineDQM GUI, which will be PRed soon)

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by boudoul** [comment]
Thanks for the PR.
 @andrius-k, @kmaeshima, @schneiml, @jfernan2, @fioriNTU , assuming the PR review will converge, could please put this PR on the DQM plan for the next MWGR ? Thanks

**Comment by schneiml** [comment]
@boudoul next MWGR as in the one started today? We'd need a backport to 10_6 first for that, I just tried merging this one but it seems to be based on a later release.

**Comment by boudoul** [comment]
Hi @schneiml , obviously not the one started today , the PR should go first in a careful review and then for a backport (likley 11_0) , not to mention that there is no GEM in the current MWGR ...

**Comment by schneiml** [comment]
@boudoul ok, we got a bit surprised there exactly because GEM is not really doing anything... For next MWGR makes more sense.

**Comment by jfernan2** [comment]
Hi @quark2, I can't seem to find you in [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts). Could you please briefly introduce yourself?

**Comment by jshlee** [comment]
@jfernan2 - @quark2 is Byeonghak Ko, he is listed as a GEM Validation DQM Developer. We need to update that page with Byeonghak as the Online DQM Developer too.

Jason.

**Comment by jfernan2** [comment]
Thank you @jshlee 
He was my guess, but I could not figure out since he has no name in Github

**Comment by jfernan2** [comment]
@quark2  there are code format patchs to apply to this PR

**Comment by quark2** [comment]
Wait, I found that after `scram build code-format` it cannot be compiled well. My bad... I'll fix it asap.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@quark2 it seems the compilation problems are still there...

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@quark2 as I mentioned by email, since this PR is going to Online DQM, the tests performed in github are blind to Online DQM, so indeed the validation with runTheMatrix should give no additional output
Have you tried to perform a private test in your own DQM GUI following the instructions I sent to you?

**Comment by quark2** [comment]
@jfernan2 Sorry for my late response... I think I did it all as your guide. You can see some visual details in [1], some plots on DQM GUI of onlineDQM.

[1] https://indico.cern.ch/event/881121/contributions/3712072/attachments/1972921/3282493/20200120_DQM_Online_PR.pdf

**Comment by jfernan2** [comment]
Thanks @quark2 I understand the screenshot comes from your private DQM GUI. Do you plan to enable these changes for next MWGR? Or do you when GEM will try to run in Online DQM in an effective way?

**Comment by quark2** [comment]
Yes, the screenshots are from my private DQM GUI. Also yep, my team has a plan for the coming MWGR with the modules you saw.

**Comment by jfernan2** [comment]
@quark2 then can I please ask you for a presentation of your plans for ONline DQM in next DQM General meeting on Friday 7yj 14h?
https://indico.cern.ch/event/870366/

**Comment by quark2** [comment]
Yep, sure. But I have no idea what I have to say. I found some previous slides, [1], [2], [3], and I think I can follow them to make my slides. Is it a good idea?

[1] https://indico.cern.ch/event/859681/contributions/3620208/attachments/1941631/3220038/191108_csc_dqm_review.pdf  
[2] https://indico.cern.ch/event/859681/contributions/3620216/attachments/1941691/3219743/DT_DQM.pdf  
[3] https://indico.cern.ch/event/862708/contributions/3634807/attachments/1945771/3228279/RPC_DQM_sequences_review_v3.pdf

**Comment by srimanob** [comment]
@quark2 
If you get a green light from DQM, please prepare backport to 11_0. We expect to have release by end of release meeting next week (Feb 11). This will allow us to run replay and get report by Feb 14 (Joint operation meeting)

**Comment by quark2** [comment]
Sorry for late reply... The new module is developed under 11_0 (and adapting the master well, as verified) so that I think I'm already ready. I've checked again that the module works well in 11_0.

**Comment by silviodonato** [comment]
urgent

**Comment by quark2** [comment]
Umm, then should I make a new PR to 11_0_X? Otherwise, what should I do?

**Comment by srimanob** [comment]
@quark2 
Yes, please make other PR for 11_0 branch. But first, make sure that this PR run well with master branch (11_1).

**Comment by quark2** [comment]
Now I understand. I'll make it asap. Btw, to make sure, is https://github.com/cms-sw/cmssw/tree/CMSSW_11_0_X right?

**Comment by fioriNTU** [comment]
Q

> Now I understand. I'll make it asap. Btw, to make sure, is https://github.com/cms-sw/cmssw/tree/CMSSW_11_0_X right?

yes @quark2 , please submit the PR asap

**Comment by quark2** [comment]
Okay. But first, I'll make a update for this PR (which is also on the PR to 11_0_X), a minor bug fix.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
hold
Testing it in Online DQM playback

**Comment by jfernan2** [comment]
unhold
Tested succesfully in DQM Online playback

**Comment by silviodonato** [comment]
+1

**Pull request merged**
