### PR TITLE
Add jet collections to GTT framework

### PR DESCRIPTION
**Pull request by cgsavard**
PR description:
This PR adds two new jet collections for studying track jet performance:

tpfastjets clusters tracking particles with the fast jet algorithm
trutrkfastjets clusters L1 tracks with truth information with the fast jet algorithm

PR validation:
I have checked that the producers work correctly with the L1TrackObjectNtupleMaker and have run the necessary code checks.

These changes were checked by L1T in this PR [here](https://github.com/cms-l1t-offline/cmssw/pull/1171) where I was told to make a corresponding PR into CMSSW.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@cgsavard 

There is an unused variable that is causing the build errors:
```
L1Trigger/L1TTrackMatch/plugins/TPFastJetProducer.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-21-2300/src/L1Trigger/L1TTrackMatch/plugins/TPFastJetProducer.cc:146:9: warning: variable 'nStubLayerTP_g' set but not used [-Wunused-but-set-variable]
```

**Comment by cgsavard** [comment]
@aloeliger Ah yes, I have now removed the variable

**Comment by epalencia** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
