### PR TITLE
Small "cosmetic changes" to test PR workflow

### PR DESCRIPTION
**Pull request by dinardo**
I made just "cosmetic changes" with respect to PR 19034.
I'm just testing here how to make a PR NOT into master branch as suggested from experts, in fact I'm trying to make a PR into CMSSW_9_2_X.
- Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
Dear experts,
I'm not sure who is watching this (I hope Tomas Hreus, @threus): you might have been following our recent email exchange with Marco Rovere (@rovere) . He, Marco, unambiguously said I should make PR NOT into master branch. Tomas suggested to look into this twiki https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector and see which is the branch I should make PR into.

I tried once again to make PR NOT into master branch, this time with just "cosmetic changes", just to try and see. As you can see from the thread of messages I got the message from cms-bot: "CMSSW_9_2_X branch is closed for direct updates. cms-bot is going to move this PR to master branch". Somehow I can't make PR other than into master brach.

Can you please explain how to make PR NOT into master brach ?
I'm not sure what I'm doing wrong.

Many thanks for your support.
Kind regards,
- Mauro.

**Comment by davidlange6** [comment]
All new features need to be requested for the master branch (maybe elsewhere too). The master and CMSSW_9_2_X branches are currently the same, which is why you see this redirection.

Cheers
David

On Jun 3, 2017, at 4:28 PM, Mauro <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear experts,
I'm not sure who is watching this (I hope Tomas Hreus, @threus<https://github.com/threus>): you might have been following our recent email exchange with Marco Rovere (@rovere<https://github.com/rovere>) . He, Marco, unambiguously said I should make PR NOT into master branch. Tomas suggested to look into this twiki https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector and see which is the branch I should make PR into.

I tried once again to make PR NOT into master branch, this time with just "cosmetic changes", just to try and see. As you can see from the thread of messages I got the message from cms-bot: "CMSSW_9_2_X branch is closed for direct updates. cms-bot is going to move this PR to master branch". Somehow I can't make PR other than into master brach.

Can you please explain how to make PR NOT into master brach ?
I'm not sure what I'm doing wrong.

Many thanks for your support.
Kind regards,

  *   Mauro.

**Comment by rovere** [comment]
Please Mauro, please, at least take the time to carefully read what I already wrote you. The "patch" in the branch name is not ancillary......

Mauro,
the situation is pretty simple: there is a branch, named 920patchX that is meant for producing quick patch releases and another branch, master, which is the current development branch, so basically identical to 92X (as I said, for the time being, it's not granted for the future).
DQM Online is running releases from 920patchX, so if you want to have something quickly deployed there, you simply have to make a PR against 920patchX branch. Keep in mind that every commit is a snapshot of the full release, so also the starting point of your work will make a difference to DQM guys on the mergeability of your PR or not or, said in another way, on the number of changes your PR will bring in in their production system. The bottom line is: better ask them what they are actually running on production and start from that exact point in time.
The master branch works as usual: start from a recent IB and build your patch on top.
As for submitting the PR to different branches, the GitHub site has this ability when you click the button "Compare and make PR" or something similar. You will re redirected to a page in which you can freely select on top of which branch you want your PR to merge into and the branch that you are asking to merge. No magic, no tricks.

Ciao,
--Marco.

**Comment by dinardo** [comment]
Many thanks Marco, now it's clear.
Kind regards,
- Mauro.

**Comment by dmitrijus** [comment]
To add to @rovere comment.

Your PR will never be merged into any of the branch unless the code changes (or the pull request for them) exist in the master branch.

The first step you have to do, always:
**1. make a PR to master branch**

Once this is done and only once it is done, 
you can request the changes to be merged into online DQM or the production branch (such as 920patchX).

**Comment by dinardo** [comment]
Many thanks Dmitrijus,
now it even more clear.

I think, I hope :-), I got everything.

Many thanks,
- Mauro.

**Comment by rovere** [comment]
@dinardo have you read the thread/discussion in #19267 ??
There was an explicit action item for you to check why the changes introduced there were somehow heavily affecting beampixel; Have you had the time/chance to do that?
Is this added commit a result of that study? I doubt since this exact commit is already included in #19267 and, now, if we merge this PR we will have a conflict on the other.
Please clarify and take proper actions.

**Comment by dinardo** [comment]
@rovere Hi Marco, yes I did. I intend to do those studies later next week. I naively thought to keep this PR#19088 up to date with PR#19267 since it's moving along. Sorry about that. Ciao, - Mauro.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
