### PR TITLE
SiStrip DQM-popCon classes reorganisation (removing uses of edm::Service)

### PR DESCRIPTION
**Pull request by pieterdavid**
This is a set of (purely technical) changes that I prepared last year as part of an effort to reduce the number of edm::Service classes in the strip tracker offline software (see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiStrip_edmServicesToESProducersPopConSourceHandlers), forgot to submit back then, and revived now (rebased after the `boost::lexical_cast` removal (on yesterday's 11:00 IB tag), and with a few commits added) because it makes it much easier to port these classes from the subdetector-DetIds to using the TrackerTopology (see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiStripLocalReco_notesSiStripSubDetIdToTrackerTopologyMigration).

This moves quite a bit of code around (I modified the inheritance structure and use of templates, because without the services it looked more sensible to have the most specific code - that used to be in the services - to the most specific classes in the hierarchy), so there is a risk of breaking things, but I don't really know how to properly test these changes (I tried to run the test configs, but at least some of them look outdated/broken)... maybe the DQM can provide some guidance on that? Thanks in advance!

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by pieterdavid** [comment]
(forgotten yesterday): CC @OlivierBondu  @alesaggio @vidalm . The xxxDetId->TrackerTopology migration is tracked at https://github.com/cms-sw/cmssw/issues/19398

**Comment by dmitrijus** [comment]
Hi @pieterdavid, there is one more major change needed for DQM.
This is forbidden in the current framework,`edm::Service<DQMStore>().operator->(); `
You are not supposed to access DQMStore. 

Please move to the DQMEDHarvester / DQMStore::IBooker interface.

Some documentation: https://twiki.cern.ch/twiki/bin/view/CMS/DQMOfflineThreadedMigration#The_DQMEDHarvester

It's old, because most of DQM have been already migrated 2 years ago. These few modules you are now changing were not :(

**Comment by pieterdavid** [comment]
Thanks for having a look, @dmitrijus . That looks like a significant change indeed... I will be on holidays for the next two weeks, but I will have a look at it as soon as I'm back.
In the mean time, we had a short discussion about this in the SiStrip calibration and local reco meeting (last Wednesday), and we were not certain if these modules (that look like they have not been modified or used for quite some time) are still necessary. If anyone could provide some insight into that, that would also be useful ;-)

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
