### PR TITLE
Improve uniform_groups-related functions

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Address the comments to the `uniform_groups` and `independent_groups` implementation:
  - improve the description of the range-for types;
  - rename `iterator` to `const_iterator`;
  - add forward declaration and type alias for `const_iterator`.

#### PR validation:

All unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@antoniovilela @rappoccio, can you pick this for pre2 ?

**Comment by makortel** [comment]
Thanks!

**Comment by rappoccio** [comment]
+1

**Pull request merged**
