### PR TITLE
TwinMux unpacker updates according to new firmware version (v12)

### PR DESCRIPTION
**Pull request by jpazzini**
Updated the decoding of the packed data according to new TwinMux firmware version (v12).
Removed possibility to pass the bc0 bit in favour of the MB3_phiBending information.

### CODE REVIEW

**Comment by jpazzini** [comment]
please consider this for an urgent approval, as it will be needed for the DT subsystem in Global Runs

**Comment by deguio** [comment]
please test

**Comment by jpazzini** [comment]
test succeeded, please merge asap

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Is there an 81X version of this PR?

**Comment by davidlange6** [comment]
+1

**Comment by jpazzini** [comment]
@mulhearn no, there is no 81X version of this PR; should I open one or is it going to be automatically propagated from 80X -> 81X?

**Comment by fcavallo** [comment]
Sorry to reopen this thread: actually we need to include this PR in CMSSW_804, which is the release used at T0 presently.
In fact, as long as the right TwinMux unpacker (i.e. correctly matching the firmware) is not used in the reconstruction and DQM offline, we can't monitor the TwinMux behavior.
Please tell us if we should do something on git or if you can handle this request as it is.
thank you!!!

**Pull request merged**
