### PR TITLE
relval def cleanups in 76x

### PR DESCRIPTION
**Pull request by davidlange6**
for
@boudoul

### CODE REVIEW

**Comment by boudoul** [comment]
thanks @davidlange6 
@cmsbuild , please test

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by boudoul** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
