### PR TITLE
Topic fill description uncalib rechit for 75 x

### PR DESCRIPTION
**Pull request by matteosan1**
Same as 7877 but for CMSSW_75X.
Add fillDescription method to EcalUncalibRechit producer.
@Martin-Grunewald @perrotta

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@matteosan1 
I think you need to rebase to 75X reduce the amount of commits and signatures pulled in.

**Comment by Martin-Grunewald** [comment]
@matteosan1 
Actually I think you submitted this PR to 74X instead of to 75X, that's why there
are so many commints in addition. Just resubmit to the correct 75X queue.

**Comment by slava77** [comment]
-1
appears to be either a wrong branch or missing rebase

**Comment by deguio** [comment]
-1
should go to 75 probably

**Comment by matteosan1** [comment]
Hi,
I don't know if it is possible but I have not been able to move this PR 
to CMSSW_7_5_X as originally inteded.
I have then done a new PR 7911.

On 2/23/15 17:48, Slava Krutelyov wrote:
>
> -1
> appears to be either a wrong branch or missing rebase
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7901#issuecomment-75580910>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Comment by Martin-Grunewald** [comment]
@matteosan1 
Thanks! OK, so then this PR (7901) should be closed!

**Pull request closed without merging**
