### PR TITLE
[13_1_X] Update the ZDC geometry fix and pixel conditions in MC GTs

### PR DESCRIPTION
**Pull request by consuegs**
#### PR description:

Partial backport of [#42551](https://github.com/cms-sw/cmssw/pull/42551).

- Updated the ZDC reco geometry tags requested in this [CMSTalk post](https://cms-talk.web.cern.ch/t/update-zdc-geometry-for-run3-data-and-mc/24637)

   - For 2022 MC: `ZDCRECO_Geometry_132DD4hepV2`
   - For 2023 MC: `ZDCRECO_Geometry_132DD4hepV3`

- Updated SiPixelDynIneff tag to `SiPixelDynamicInefficiency_phase1_2023_v2_fix3` requested for 2022 realistic MC in this [CMStalk post](https://cms-talk.web.cern.ch/t/mc-gt-pixel-bad-components-and-dynamic-inefficiency-payloads-for-the-upcoming-2022-mc-campaign/26670)

- Updated SiPixel BadComponents tags for 2022 realistic MC as requested in this [CMSTalkPost](https://cms-talk.web.cern.ch/t/mc-gt-pixel-bad-components-and-dynamic-inefficiency-payloads-for-the-upcoming-2022-mc-campaign/26670):

   - pre-EE leak:
        `SiPixelQuality_phase1_2022_v2b_mc`
        `SiPixelQuality_forDigitizer_phase1_2022_v2b_mc`
   - post-EE leak:
        `SiPixelQuality_phase1_2022_v5_mc`
        `SiPixelQuality_forDigitizer_phase1_2022_v5_mc`

GT differences:

- _phase1_2022_design:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_design_v3/131X_mcRun3_2022_design_v4

- _phase1_2022_realistic:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_v4/131X_mcRun3_2022_realistic_v6

- _phase1_2022_realistic_postEE:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_postEE_v4/131X_mcRun3_2022_realistic_postEE_v6

- _phase1_2022_cosmics:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_realistic_deco_v4/131X_mcRun3_2022cosmics_realistic_deco_v6

- _phase1_2022_cosmics_design:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_design_deco_v3/131X_mcRun3_2022cosmics_design_deco_v4

- _phase1_2023_design:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_design_v7/131X_mcRun3_2023_design_v8

- _phase1_2023_cosmics_design:_ 

   - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_design_deco_v7/131X_mcRun3_2023cosmics_design_deco_v8

#### PR validation:

Tested with:

`runTheMatrix -l 12034.0,12434.0,12834.0,11601.0 -j 8 --ibeos`

#### Backport:

Partial backport of [#42551](https://github.com/cms-sw/cmssw/pull/42551)

### CODE REVIEW

**Comment by consuegs** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * tests pass
 * PR in line with description
 * lot of diff in plots but that's expected from the GT change

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42551

**Comment by mmusich** [comment]
> backport of https://github.com/cms-sw/cmssw/pull/42551

out of curiosity why targeting directly 13.1.X without a 13.2.X backport ? (of did I miss it?)

**Comment by perrotta** [comment]
+1

**Pull request merged**
