### PR TITLE
JPT_TrackJetsSeeds_Reco_and_PATrereco

### PR DESCRIPTION
**Pull request by kodolova**
#### PR description:

Presented at Reconstruction meeting
https://indico.cern.ch/event/923095/

#### PR validation:

Tests are performed according:https://cms-sw.github.io/PRWorkflow.html
Result of runTheMatrix test is in:
/afs/cern.ch/work/k/kodolova/public/HMUMUBB/CMSSW_11_1_X_2020-06-08-1100/src
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
-1

it looks like this should be rebased to 11_2_X 
http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by slava77** [comment]
@kodolova 
please edit the PR title to be self-descriptive and somewhat grammatically correct ("Jpt 11 1 x" is not good enough)

**Comment by kodolova** [comment]
No, I thought that it is done automatically. 
I tried it now and immediately get:
[kodolova@lxplus778 src]$ git push my-cmssw JPT_11_1_X
Enter passphrase for key '/afs/cern.ch/user/k/kodolova/.ssh/id_rsa': 
To github.com:kodolova/cmssw.git
 ! [rejected]                JPT_11_1_X -> JPT_11_1_X (non-fast-forward)
error: failed to push some refs to 'git@github.com:kodolova/cmssw.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I am sorry but there is not good instruction step by step how to work with git. 
Could you advice?

**Comment by perrotta** [comment]
Dear Olga, I followed line by line the instructions posted [above](https://github.com/cms-sw/cmssw/pull/30160#issuecomment-642098303) by Slava and I ended up with a github branch in 12_2_X which only contains your commits:
```
cmsrel CMSSW_11_2_X_2020-06-10-2300
cd CMSSW_11_2_X_2020-06-10-2300/src
cmsenv
git cms-rebase-topic kodolova:JPT_11_1_X
```

At this point you can simply try to push in your current branch
```
git push my-cmssw JPT_11_1_X
```
or, if it fails for any reason, just open a new branch and submit a new PR with it (and close this one), as I could have done with
```
git checkout -b jptFromKodolova
git push my-cmssw jptFromKodolova
```
for which you can check my perrotta:jptFromKodolova branch.

**Comment by kodolova** [comment]
Thank you! I repeated in new project area and got the same error. I think that I do need to open the new branch and new PR. Something is broken with this one.

**Comment by kodolova** [comment]
I have created the new PULL request.
JPT_TrackJets seed reco and PAT rereco 11_2_x based 

How to kill #30160?

**Comment by perrotta** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/closing-a-pull-request

**Comment by kodolova** [comment]
Sorry again...  When I try: https://github.com/kodolova/cmssw
I see : Pull requests 0
Are there any problems with my git account?

**Comment by perrotta** [comment]
Please stay in THIS pull request
You should have a button here below, close to the green "Comment" one.

**Comment by perrotta** [comment]
-1
(just to take this out of our list until it gets closed)

**Pull request closed without merging**
