### PR TITLE
Add run numbers to DQM output

### PR DESCRIPTION
**Pull request by schneiml**
This is an attempt to fix the long-standing issue of mislabeled DQM plots on meeting slides. (Once discussion here settles, this should also be backported to 80X.) 

The solution is to simply put the run number onto the plot itself. However this is not that easy in the obvious place (the DQM GUI) since the rendering is not aware of runs and such. So, I tried a simple solution here: just add it to the histogram title in an additional harvesting step.

At the moment this is only applied to tracker-related plots, but we might want to turn it on for everything. (Nothing obviously breaks from changing all histogram titles, but probably something will.)

Implemetation issues are that the run number in the ME seems to be 0 in the relevant places (is this only used for step1 or multi-run harvesting or something?) and that dqmEndJob does not know the run, with the usual fix of storing the value in endLumi. Another is that this plugin should run once at the very end of the harvesting sequence, which I don't see how to do. The current solution works but is not optimal.

The change to the `DQMStore` is needed to access the `getContents` method via the `IGetter`, which I would call a bug fix. My solution is moderately elegant, others are possible but not much better.

### CODE REVIEW

**Comment by dmitrijus** [comment]
hold

Code looks fine and thanks for the fix. But shouldn't there a better way?

Perhaps you can check the full path of histogram to get the run number, for the render plugin?
I will let @vanbesien comment.

What I don't like is this changes names, for _all_ histograms.
Meaning if it accidentally end up in any production sequence......

I also don't know whether histograms with different titles will break matching / comparison scripts.
@anorkus .

Dmitrijus

**Comment by schneiml** [comment]
This is my very question. 

As far as I see the renderplugin does not see anything like the run number; the paths there start with the top folder (as in the DQMStore). In general, the renderer (which is a separate process) is not aware of runs, as far as I remember. 

Changing titles should be much less problematic than changing _names_, but I exepct that in some corner of CMSSW there will be some code that will break due to this. OTOH, on a opt-in basis this should be fine. Currently I opted-in the Tracker stuff, even though I don't even know whether anything there breaks.

**Comment by schneiml** [comment]
@vanbesien @dmitrijus any new opinions?

**Comment by boudoul** [comment]
I take the liberty to add @deguio and @rovere here  - I know both of them are not supposed to review  anymore DQM PRs , but perhaps they can help commenting there - Thanks

**Comment by rovere** [comment]
Mislabelled plots in slides are a responsibility of the author, not of the DQM Team.
Changing dynamically the name of the histograms during the harvesting is a no go, for several reasons.
I have no power in DQM, but I -1 this.

**Comment by schneiml** [comment]
> Mislabelled plots in slides are a responsibility of the author, not of the DQM Team.

Providing tools to make authors' lifes easier, however, is. (As far as I
see. Otherwise there is no point in having a DQM framework at all...)

> Changing dynamically the name of the histograms during the harvesting is a no go, for several reasons.

Caution with terminology here: no _names_ are touched. _Titles_ are.

> I have no power in DQM, but I -1 this.

I accept and even tend to agree with that, but it does not solve the
problem. Fixing it in the GUI would solve the problem.

**Comment by rovere** [comment]
The DQM Framework is meant to monitor the performance of the detector/release/MC/everything, it's not meant to be a tool to prepare slides. As I said, you can add the run-number later on.

If you want to know the run number in the DQMGUI you have a huge header in front of view.
If you want to download a plot in ROOT format you have the run_number in the URL, so you can save it with a proper filename.

How are you going to treat the overlay of several histograms?

Anyway, I take note of this request and see what I can think of (I had other ideas more or less on the same topic). 

I'd honestly put it in low priority.

**Comment by schneiml** [comment]
> The DQM Framework is meant to monitor the performance of the detector/release/MC/everything, 

It just happens that part of that is reporting in meetings, and in the
elog, and ...

> If you want to know the run number in the DQMGUI you have a huge header in front of view.
> If you want to download a plot in ROOT format you have the run_number in the URL, so you can save it with a proper filename.

However, if you just right-click -> save image, the run number is gone.
Sure, you can type it, but the error rate of humans typing numbers is
insanely high (copy-paste tends to be even worse).

> How are you going to treat the overlay of several histograms?

This is not possible with the approach in this PR and this is why I
agree it is a bad solution. (But it is a solution we can have today).

The right place for the run-number to go? Where would you put it in a
paper? Maybe in the caption, but more likely in the stat box, which also
serves as a legend for the color coding and is therefore the natural
place for it. So there it should go. This obviously needs changes to the
GUI, though maybe it could be hacked together in a render plugin if the
numbers where available.

> Anyway, I take note of this request and see what I can think of (I had other ideas more or less on the same topic). 
> I'd honestly put it in low priority.

With a bit of Fermi estimation, I'd guess there are maybe a dozen of
mistakes per year, so it is not insanely urgent. But it would make the
shifters life easier.

**Comment by rovere** [comment]
The solution of today is usually the production of tomorrow, where tomorrow > 1 week, usually.
The StatBox was exactly my target, but hidden to the render plugins and handled centrally.
As I said, I'll work on this topic, with some low priority.

**Comment by schneiml** [comment]
This would be perfect. If we can expect it to happen within finite time, we can probably live without it until then.

**Comment by rovere** [comment]
You can for sure live w/o it since we survived up to now ;)
It will be done in a finite, and I hope small, amount of time. Not sure for the next release, but the next to next is a good candidate.

**Comment by dmitrijus** [comment]
Please close this PR :)

**Pull request closed without merging**
