### PR TITLE
Update L1T to l1t-ts-v6-cand (80x)

### PR DESCRIPTION
**Pull request by mulhearn**
Updates the L1T algorithms to match l1t-tsg-v6-cand.

This PR has been rebased to CMSSW_8_0_8.  It includes the latest fixes from the 81x version.

It no longer contains data files, as they are now available in the release.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
@mulhearn - could you rebase this given that the other PRs are merged

**Comment by mulhearn** [comment]
Now working on rebase...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Pull request merged**
