### PR TITLE
bsunanda:Run2-alca50 Modify HcalDbHardcode for non-empty filler of logical map

### PR DESCRIPTION
**Pull request by bsunanda**
Hardcoded version of FrontEnd map is provided. FrontEnd map is needed for HCAL noise removal codes in the context of an evolving detector.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
@bsunanda please provide some description of the proposed code changes and some context for its need.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@kpedro88 until https://github.com/cms-sw/cmssw/issues/15188 is solved there is not much point in re-triggering over and over again

**Comment by kpedro88** [comment]
@mmusich ah, I didn't realize files were actually missing this time. My assumption is always that DAS just sucks.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
@bsunanda please provide some description of the proposed code changes and some context for its need.

**Comment by bsunanda** [comment]
@mmusich I have provided some description here

**Comment by mmusich** [comment]
@bsunanda thanks for the description. 
For my understanding which use case does this update address that is not taken care of by https://github.com/cms-sw/cmssw/pull/15141? Phase-II?

**Comment by bsunanda** [comment]
@mmusich Yes PhaseII or even PhaseI beyond 2019 (when HB will have SiPM)

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
