### PR TITLE
workaround for -O3 compilation issues in Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

This PR has a workaround for the compiler errors seen with '-O3' optimization covered in https://github.com/cms-sw/cmssw/issues/44931#issuecomment-2134850535.  This is likely a compiler bug, but I'm not optimistic about getting a simple replication for a gcc bug report.

#### PR validation:

Compiles, purely technical fix.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@dan131riley Thanks!

**Comment by Dr15Jones** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
