### PR TITLE
Fixed all the "hidden" overlaps inside the CSC subsystem

### PR DESCRIPTION
**Pull request by slomeo**
Fixed all the "hidden" overlaps inside the CSC subsystem (needed for Scenario 2021).

The "hidden" overlaps are not seen by cmsShow but only by 
SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck_cfg.py script.

The new code has been checked by @ptcox

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , please, comment

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
