### PR TITLE
GPU RawToDigi C940

### PR DESCRIPTION
**Pull request by sushildubey171**
This is GPU version of RawToDigi.

- The cabling map required for RawToDigi is stored in the ascii file (name of file Pixel_Phase1_Raw2Digi_GPU_Cabling_Map.dat) in directory EventFilter/SiPixelRawToDigi/test and uploaded to the GPU memory.

- Headers and trailers checks are performed in the SiPixelRawToDigi.cc for each FED.

- The program first collects raw data of each FED together maximum upto 128 events and then transfers to the device memory asynchronously using cuda streams. The entry point to the GPU code is `RawToDigi_wrapper` in SiPixelRawToDigi.cc

- The device functions `RawToDigi_kernel` performs RawToDigi conversion on GPU

- After RawToDigi conversion `applyADCthreshold_kernel` is invoked (optional through bool convertADCtoElectrons) which performs calibrations ADC to Electrons and applies channel thresholding. The ADC to Electrons calibration and thresholding is required by Clustering algorithm.

### CODE REVIEW

**Comment by slava77** [comment]
given changes in   EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc 
and a PR only to 94X,
my guess is that this is not submitted to the right repository.

@sushildubey171 
@boudoul @veszpv 
please clarify

**Comment by makortel** [comment]
Better add @felicepantaleo as well

**Comment by VinInn** [comment]
-1
In my opinion this is not the way this kind of code should be engineered...
the C++ and GPU code should be fully separated eventually with a common driver and set of utilities
Most probably two different producers sharing some common code.

AND the C++ code should be identical to what is currently using, not even a single debug statement should be modified: only refactoring is allow (provided it does not negatively impact computational efficiency)

**Comment by sushildubey171** [comment]
@felicepantaleo ,
@fwyzard 
could you please take a look at this PR
thanks a lot !

**Comment by slava77** [comment]
-1

if this is really ready for integration, please submit to the master branch.
If this is not ready for integration and needs a review within PATATRACK etc and possibly significant redesign can happen, please open a PR in your own repo and collect comments there first and once about ready, submit to the master branch.

Quick comment on large files which are not meant to be human readable and do not represent source code: if they are needed, they should go to externals. The tentative upper limit is 1K lines for the source tree for such files if the need is compelling enough.

**Comment by fwyzard** [comment]
> given changes in EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc and a PR only to 94X, my guess is that this is not submitted to the right repository.

@slava77 , this *is* the right repository, unless you are now suggesting we should fork CMSSW somewhere else.

No, the PR is not ready for being integrated, and it was not supposed to be.

Do you have in mind a better way to make the code available for people CMS-wide to review and discuss ?
Otherwise, we *are* going to make PRs, etc. Please, feel free to ignore them if you don't care about this development.

**Comment by slava77** [comment]
On 11/15/17 4:20 PM, Andrea Bocci wrote:
>     given changes in
>     EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc and a PR
>     only to 94X, my guess is that this is not submitted to the right
>     repository.
> 
> @slava77 <https://github.com/slava77> , this /is/ the right repository,
> unless you are now suggesting we should fork CMSSW somewhere else.
> 
> No, the PR is not ready for being integrated, and it was not supposed to be.
> 
> Do you have in mind a better way to make the code available for people
> CMS-wide to review and discuss ?
> Otherwise, we /are/ going to make PRs, etc. Please, feel free to ignore
> them if you don't care about this development.

I provided my comments on how to collect comments depending on readiness
together with the last "-1" to this 94X PR.

**Comment by fwyzard** [comment]
Indeed, thank for your comments.

**Comment by davidlange6** [comment]
A PR for comments is indeed fine (imo) - ideally it should be for the development branch, and definitely it should be explained (even better, labeled) as a PR that is made for comments and not for integration. (eg, people seem to use RFC as one indicator)

**Comment by felicepantaleo** [comment]
thanks Slava for clarifying the procedure, we can then close this PR and start reviewing directly in Sushil's branch.

**Comment by felicepantaleo** [comment]
@davidlange6 I completely agree with you. What do you propose?
Just adding RFC in the title of a PR?

**Comment by davidlange6** [comment]
Its more when making PRs to avoid this sort of discussion:)
but - yes, add RFC and a paragraph of text to start the discussion of what feedback is desired by the authors.

**Pull request closed without merging**
