### PR TITLE
Tracker alignment - several MP developments

### PR DESCRIPTION
**Pull request by adewit**
This:
- Changes the default storage area for MillePede output files to the millepede group area (instead of the user's personal CAF storage space)
- Adds more robust copying of files into and out of alignment jobs
- Adds a new user option to the script that launches alignment jobs

### CODE REVIEW

**Comment by tocheng** [comment]
please test

**Comment by tocheng** [comment]
@adewit Will there be a backport to 10_2_X?

**Comment by adewit** [comment]
@tocheng I don't think a backport to 10_2_X is necessary in this case.

**Comment by tocheng** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
