### PR TITLE
DQM-HcalCommon+HcalTasks: fix clang warnings hides overloaded virtual function

### PR DESCRIPTION
**Pull request by gartung**
by adding using directives and also pad call to Container2D with 0's so the correct initialize function is called. Fixes these warnings: 
 /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/ba81249bb4729771235b98cb83b6e8d8/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_CLANG_X_2016-12-13-1100/src/DQM/HcalCommon/interface/HashMapper.h:33:22: warning: 'hcaldqm::mapper::HashMapper::getHash' hides overloaded virtual functions [-Woverloaded-virtual]
                                 virtual uint32_t getHash(HcalDetId const& did) const
                                                 ^
  /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/ba81249bb4729771235b98cb83b6e8d8/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_CLANG_X_2016-12-13-1100/src/DQM/HcalCommon/interface/HashMapper.h:45:25: warning: 'hcaldqm::mapper::HashMapper::getName' hides overloaded virtual functions [-Woverloaded-virtual]
                                 virtual std::string getName(HcalTrigTowerDetId const& tid) const
                                                    ^ 
/build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/ba81249bb4729771235b98cb83b6e8d8/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_CLANG_X_2016-12-13-1100/src/DQM/HcalCommon/interface/HashFilter.h:44:18: warning: 'hcaldqm::filter::HashFilter::initialize' hides overloaded virtual function [-Woverloaded-virtual]
                                 virtual void initialize(FilterType ftype, HashType htype,

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @davidlange6 This one fixes ~300 clang warnings in DQM/HcalTasks

**Comment by dmitrijus** [comment]
+1

**Comment by gartung** [comment]
Appears to be a failure caused by changes
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17015/17057/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step4_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT.log

**Comment by gartung** [comment]
@dmitrijus please retest. I think I got all of instance of initialize where I needed to add the extra parameter.

**Comment by Dr15Jones** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
@deguio - could you confirm these changes are correct? (some of them look like workarounds to bugs to me) Thanks-

**Comment by deguio** [comment]
for some reason I didn't get notified for this.
@vkhristenko is looking into this PR (thanks!) and will comment here directly.
cheers,
F.

**Comment by davidlange6** [comment]
hi all - any news on this ?

**Comment by vkhristenko** [comment]
@davidlange6 , sorry for the delay. let's just go with that. I never personally compiled cmssw with clang, gcc only.
VK

**Comment by davidlange6** [comment]
its not a matter of compilation with clange/gcc - its a question of if the code changes are ok or are covering up bugs (will be the same problem in gcc just that gcc doesn’t currently complain)

**Comment by vkhristenko** [comment]
in there I intentionally overwrite the base class method. no bugs. 

for my reference, http://stackoverflow.com/questions/18515183/c-overloaded-virtual-function-warning-by-clang

Vk

**Comment by davidlange6** [comment]
+1

ok, thanks

**Pull request merged**
