### PR TITLE
RecoTracker/TkNavigation: Change return type of ESProducers.

### PR DESCRIPTION
**Pull request by gartung**
Remove shared_ptr class member that is not needed.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
Looks OK

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Those workflows are failing in the IB.

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21997	76613e6
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
