### PR TITLE
add option to switch off time calibration 80x

### PR DESCRIPTION
**Pull request by argiro**
this will be useful at HLT, where timing is not ran, in order to save time and avoid confusing results

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by argiro** [comment]
It would be great if this could be merged ASAP to match the schedule of PFG and make it into the trigger. Thanks !

**Comment by slava77** [comment]
@argiro 
You should have added that this is urgent in the PR message itself or by email.
The most recent 80X release (8_0_14) is already built (not announced yet)

**Comment by argiro** [comment]
ok, we'll wait for the next round tnx

**Comment by cvuosalo** [comment]
+1

For #15112 295fcdd27c10948488d0095b81f3327d55ddf431

Adding the option to the ECAL rec hit producer to switch off time calibration. The option defaults to false, so there is no change in the behavior of standard workflows. There should be no change in monitored quantities.

#15113 is the 81X version of this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-07-03-0000 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
