### PR TITLE
Work around inconsistency in ExternalLHEProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
The ExternalLHEProducer puts the 'same' data product into the Run
at both beginRun and endRun. This is not a behavior the framework
was intended to support (and causes sematic problems). However,
in order to avoid breaking existing workflows, we must accomodate
this behavior for the moment.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 @smuzaffar this is the fix for the recent IB RelVal failures involving ExternalLHEProducer.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test workflow 514.0

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 the workflow 514.0 ran fine with this change but was failing in the IBs. Looks like the fix worked and doesn't show any signs of any unwanted side-effects.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
