### PR TITLE
HLT DQM online fix (101X backport)

### PR DESCRIPTION
**Pull request by silviodonato**
101X backport of #22901

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien I think this is an important fix to run HLT DQM online in the next data taking. You might also consider to ask for a patch release in order to use this fix as soon as possible at P5.

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
