### PR TITLE
Hlt object monitor squashedv2

### PR DESCRIPTION
**Pull request by muell149**
new changes for HLT online DQM

### CODE REVIEW

**Comment by deguio** [comment]
ciao @muell149 
could you avoid instantiating all the histograms with new and instead use the standard booking method:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/DQMServices/Core/interface/DQMStore.h#L316
?
moreover I am not sure I understand the usage of hist_photonPt for all the histos.

I was also thinking that maybe substituting the repetitions with a for loop would help in keeping the code clean.
updating this branch should update the PR in 76x as well.
thanks,
F.

**Comment by deguio** [comment]
-1
leaving the 76x alive. thanks for understanding. we can reopen in 75 and 74 as soon as we converge on a final version of the code

**Comment by muell149** [comment]
@deguio thanks, I kept the TH1s because I can easily set the axis labels and I don't think I can do that with ME's. Do you still want me to change the booking to strictly ME's?

Cheers,
Charlie

**Comment by deguio** [comment]
ciao @muell149 
the TH1 object is always exposed to the user. 
you can use one of the methods at:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DQMServices/Core/interface/MonitorElement.h#L339-L346

this would avoid having useless double copies of all the MEs
ciao,
F.

**Comment by muell149** [comment]
Thanks @deguio, I've made the updates to just use the MEs and not make unnecessary TH1s. I will work on turning the booking into a for loop eventually, but if it's OK can we merge this as-is?

Cheers,
Charlie

**Comment by deguio** [comment]
status:
this is already running in production at the online given the urgency. however there was a request of optimization of the code with loops to make it more maintainable and less error prone. moreover the trackRefitter is throwing errors and a change to fix them is also needed.

**Comment by deguio** [comment]
-1
this one doesn't merge anyway

**Pull request closed without merging**
