### PR TITLE
updates needed for protobuf 3.15.1 and TF(py3) 2.4.1

### PR DESCRIPTION
**Pull request by smuzaffar**
These changes are needed for TF 2.4.1 ( which is now only available for python3). C++ TF interface should still work, only python2 TF interface is not available.

More changes needed for CMSSW TF

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks with cms.week1.PR_00ab7aee/46.0-a6e28c3cc6110fef3740691e488ad684

**Comment by andrius-k** [comment]
Hi @smuzaffar,
Does this PR change the way [DQMFileSaverPB](https://github.com/cms-sw/cmssw/blob/ba6e8604a35283e39e89bc031766843d0afc3240/DQMServices/FileIO/plugins/DQMFileSaverPB.cc) is writing the messages described in this file: https://github.com/cms-sw/cmssw/blob/ef4096c64f79cc6ad14dff827e0fae825302d61e/DQMServices/Core/src/ROOTFilePB.proto ?
Any changes in the way bytes are being packed will break the new Online DQM GUI.

**Comment by smuzaffar** [comment]
@andrius-k , I have no idea. Is there any unit tests to check this type of change?

**Comment by andrius-k** [comment]
@smuzaffar nope, we don't have any unit tests for that. What is the purpose of this change? What is TF 2.4.1 in this case?

**Comment by smuzaffar** [comment]
Tensorflow (TF) version 2.4.1 . The current version 2.3.1 is vulnerable [a]

[a] https://github.com/cms-sw/cmsdist/security/dependabot/pip/requirements.txt/tensorflow/open
```
Vulnerable versions: >= 2.3.0, < 2.3.2
Patched version: 2.3.2
Impact
Under certain cases, a saved model can trigger use of uninitialized values during code execution. This is caused by having tensor buffers be filled with the default value of the type but forgetting to default initialize the quantized floating point types in Eigen:
```

**Comment by smuzaffar** [comment]
I would suggest to add such a test, without it we can not guarantee that it will not break dqm gui.

**Comment by andrius-k** [comment]
Alright, knowing how strict the restrictions of the backwards compatibility of the PB format are, I'd say the likelihood of this breaking the binary packing rules is very low. 
I don't see any problems integrating this.
For the future, indeed, we could provide some unit tests to ensure the compatibility.

**Comment by jfernan2** [comment]
Since all the unit tests in DQM/Integration are using DQMFileSaverPB plugin which at the end uses the files modifed in this PR, let's trigger the tests to see if something "big" appears

**Comment by jfernan2** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#32993
lets rerun tests based on latest IB

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683
let rerun tests based on latest IB

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683
DAS errors are not related to this PR

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6683

**Comment by smuzaffar** [comment]
any objections @cms-sw/dqm-l2 @cms-sw/analysis-l2 . This is needed for protobuf 3.15

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy this looks good to go with https://github.com/cms-sw/cmsdist/pull/6683 .
Changes for analysis involve only unit tests to be run under python3. As we are dropping Tensorflow 2.4.1 python2 support, so it is better to update these unit tests to only use python interface for TF.

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
