### PR TITLE
Add reco::Muon displacedMuons to offline validation sequences

### PR DESCRIPTION
**Pull request by 24LopezR**
#### PR description:

In this PR we add the code to include the reco::Muon displaced muon AOD [collection](https://indico.cern.ch/event/1128824/contributions/4737393/attachments/2393995/4093001/PR_addDisplacedMuonsInRECO_MuonPOG.pdf) to the Muon offline validation. An analyzer is added to Validation/RecoMuon/src, very similar to the one for standard muons. Also the necessary configuration files are added, and the sequences included in the global configuration. 
Validation for standard muon collection is left unchanged.

See presentation on MUO POG General meeting: [https://indico.cern.ch/event/1389920/#2-displaced-muon-in-the-valida](https://indico.cern.ch/event/1389920/#2-displaced-muon-in-the-valida)

#### PR validation:

New offline DQM has been run on a real validation sample: workflow 12524.0 DisplacedSUSY with 5000 events.
The code runs smoothly and the new validation folder Muons/RecoDisplacedMuonV is in the DQM file with the correct plots. As an example, see Dxy plot of reco tracks for dSA [1] and dGl [2].

[1] 
Screenshot from 2024-03-08 09-31-05
[2]
Screenshot from 2024-03-08 09-31-47

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

It is not necessary to backport this PR.

### CODE REVIEW

**Comment by 24LopezR** [comment]
Apparently, I added the validation sequence to fastsim and this should not be there. I fixed it and rerun the tests and now they run OK.

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
