### PR TITLE
Add reco::displacedMuons to offline validation (backport)

### PR DESCRIPTION
**Pull request by 24LopezR**
#### PR description:

In this PR we add the code to include the reco::Muon displaced muon AOD [collection](https://indico.cern.ch/event/1128824/contributions/4737393/attachments/2393995/4093001/PR_addDisplacedMuonsInRECO_MuonPOG.pdf) to the Muon offline validation. An analyzer is added to Validation/RecoMuon/src, very similar to the one for standard muons. Also the necessary configuration files are added, and the sequences included in the global configuration.
Validation for standard muon collection is left unchanged.

See presentation on MUO POG General meeting: https://indico.cern.ch/event/1389920/#2-displaced-muon-in-the-valida

#### PR validation:

Same validation as in PR #44353. Basic tests (`scram b runtests`) have been run aswell.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of PR #44353 to release 14_0_X. The motivation for this backport is to have the code to validate the displacedMuon collection available in 14_0_X, meant for data taking during 2024.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
backport of #44353

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
