### PR TITLE
Fix issues #34648

### LINKED ISSUE #34648: Unit failure:  test_PixelBaryCentreTool had ERRORS
Please check 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-27-1100/unitTestLogs/Alignment/TrackerAlignment#/

It appears first in CMSSW_12_0_X_2021-07-26-2300 after merging https://github.com/cms-sw/cmssw/pull/34542

Local test output as below:
cmsrel CMSSW_12_0_X_2021-07-26-1100
cd CMSSW_12_0_X_2021-07-26-1100/src/
cmsenv
git cms-addpkg Alignment/TrackerAlignment
 git cms-merge-topic 34542 
 scram b -j9
cd Alignment/TrackerAlignment/test/
source pixelPositions.sh

The command 'cmsRun alignment_forGeomComp_auto:run2_data_TrackerAlignment_2009_v1_express_r272011_1.py' failed. Please check the log file.

From alignment_auto_run2_data_TrackerAlignment_2009_v1_expressr272011_1.log
----- Begin Fatal Exception 27-Jul-2021 18:33:25 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Running EventSetup component MuonGeometryConstantsESModule/'muonGeometryConstants
Exception Message:
No data of type "DDCompactView" with label "" in record "IdealGeometryRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

fixes #34648

#### PR validation:

```
Using template /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/alignment_forGeomComp_cfg_TEMPLATE.py
and plotting macros from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/MillePedeAlignmentAlgorithm/macros/
Running in /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/

============================================================
 Run 272011: auto:run2_data / TrackerAlignment_2009_v1_express (=1) vs auto:run2_data / SiPixelAli_PCL_v0_prompt (=2)
============================================================
Removing old file treeFile_auto_run2_data_TrackerAlignment_2009_v1_express_r272011_1.root
Removing old file treeFile_auto_run2_data_SiPixelAli_PCL_v0_prompt_r272011_2.root

Processing allMillePede.C...
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./GFUtils/GFHistManager_C.so
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./MillePedeTrees_C.so
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./PlotMillePede_C.so
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./PlotMillePedeIOV_C.so
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./CompareMillePede_C.so
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./PlotMilleMonitor_C.so
Processing pixelPositionChange.C+("/afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/treeFile_auto_run2_data_TrackerAlignment_2009_v1_express_r272011_1.root", "/afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/treeFile_auto_run2_data_SiPixelAli_PCL_v0_prompt_r272011_2.root")...
Info in <TUnixSystem::ACLiC>: creating shared library /afs/cern.ch/work/h/hyunyong/CMSSW_12_0_X_2021-07-26-1100/src/Alignment/TrackerAlignment/test/PixelBaryCentrePlottingTools/./pixelPositionChange_C.so
Info in <TCanvas::Print>: pdf file canvas0_0.pdf has been created
Info in <TCanvas::Print>: pdf file canvas0_1.pdf has been created
Info in <TCanvas::Print>: pdf file canvas0_2.pdf has been created
Info in <TCanvas::Print>: pdf file canvas0_3.pdf has been created
Info in <TCanvas::Print>: pdf file canvas0_4.pdf has been created
Info in <TCanvas::Print>: pdf file canvas1_0.pdf has been created
Info in <TCanvas::Print>: pdf file canvas1_1.pdf has been created
Info in <TCanvas::Print>: pdf file canvas1_2.pdf has been created
Info in <TCanvas::Print>: pdf file canvas1_3.pdf has been created
Info in <TCanvas::Print>: pdf file canvas1_4.pdf has been created
====================================================
BPIX:
====================================================
x1 x2: -0.0262721 -0.0262721
y1 y2: -0.0759665 -0.0759665
z1 z2: -0.498492 -0.498492
Delta(x,y,z) = 2-1 = (0,0,0) mum
====================================================
Pixel:
====================================================
x1 x2: -0.0400418 -0.0400418
y1 y2 -0.200817 -0.200817
z1 z2: -0.55104 -0.55104
Delta(x,y,z) = 2-1 = (0,0,0) mum
|  | *treeFile_auto_run2_data_TrackerAlignment_2009_v1_express_r272011_1.root* || *treeFile_auto_run2_data_TrackerAlignment_2009_v1_express_r272011_1.root*||
| *Position* |  *BPIX* | *Full Pixel* | *BPIX* | *Full Pixel* |
|  x  | -0.0262721 | -0.0400418 | -0.0262721 | -0.0400418 |
|  y  | -0.0759665 | -0.200817 | -0.0759665 | -0.200817 |
|  z  | -0.498492 | -0.55104 | -0.498492 | -0.55104 |

====================================================
====================================================
====================================================
```

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
fixes https://github.com/cms-sw/cmssw/issues/34648

**Comment by francescobrivio** [comment]
urgent

**Comment by francescobrivio** [comment]
please test

**Comment by mmusich** [comment]
please abort

**Comment by mmusich** [comment]
test parameters:
 * addpkg Alignment/TrackerAlignment

**Comment by mmusich** [comment]
@cmsbuild please test

Now it will actually test the failing tests

**Comment by tvami** [comment]
+alca

* the unit test reported in https://github.com/cms-sw/cmssw/issues/34648 is now successful, see:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ac83ba/17265/unitTests/src/Alignment/TrackerAlignment/test/test_PixelBaryCentreTool/testing.log
* the comparison failures are due to different input files in the step 1

**Comment by qliphy** [comment]
+1

**Pull request merged**
