### PR TITLE
Ecal timing CC deployment backport to 13_0_X

### PR DESCRIPTION
**Pull request by jking79**
#### PR description:

PR description:

PR for deployment of ECAL CC timing reconstruction backport to 13_0_X

encoding the non corrected CC in the 8 bit Timing Error:
More details https://indico.cern.ch/event/1210633/contributions/5091427/attachments/2527245/4347248/ECAL_2022_timeError.pdf
Added encoding constants declaration to EcalConstants.h
Added functions to set and return non corrected time to EcalUncalibratedRecHit.h & [EcalUncalibratedRecHit.cc](http://ecaluncalibratedrechit.cc/)
Added function to return non corrected time to EcalRecHit.h

Modified ecalMultiFitUncalibRecHit_cfi.py to make crossCorrelationMethod default timing reconstruction
More details: https://indico.cern.ch/event/1114550/contributions/4887537/attachments/2451361/4200675/ECAL_DPG_25May22.pdf

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 13_0_X. The ECAL CC timing reconstruction to be default for 2023 p-p data taking.

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
backport of #41353

**Comment by clacaputo** [comment]
please test

**Comment by mandrenguyen** [comment]
hold
... as 13_0_X is closed.  
This backport can be discussed at the ORP

**Comment by clacaputo** [comment]
Considering the outcome of the ORP20230502, this PR can be closed. @cms-sw/orp-l2

**Comment by perrotta** [comment]
> Considering the outcome of the ORP20230502, this PR can be closed. @cms-sw/orp-l2

Yes, thank you!

**Pull request closed without merging**
