### PR TITLE
Remove outdated jercVars from JME custom NanoAOD for AK4 and AK8 jets

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

Temporarily remove the so-called JERC variables from the JME custom NanoAOD content, to fix the crash in the IB reported in #29245.
JME experts will then re-add updated variables as needed.

@lathomas @ahinzmann please forward this information to the developers

### CODE REVIEW

**Comment by peruzzim** [comment]
@alefisico @camclean @nurfikri89

**Comment by peruzzim** [comment]
please test 25202.01

**Comment by peruzzim** [comment]
please test workflow 25202.01

**Comment by peruzzim** [comment]
I'm afraid `PhysicsTools/PatAlgos/python/tools/jetCollectionTools.py` needs fixing too, it should be touched only by JME experts so I will close this PR and encourage them to propagate the changes there.

**Comment by nurfikri89** [comment]
@peruzzim Should I use PR #29239 to include this fix?

**Comment by peruzzim** [comment]
that would certainly work and will also be needed to test it successfully, thank you really much!

**Comment by nurfikri89** [comment]
Will be fixed in PR #29257

**Pull request closed without merging**
