### PR TITLE
Add tau3mu HLT producer

### PR DESCRIPTION
**Pull request by rmanzoni**
back port of #19696

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please merge the changes from #19696 also here!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
This PR could not have possibly created any runtime error as it adds a so-far unused plugin.
I also can not reproduce the issue in my own area.
```
%MSG

A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.

```
but NO stack trace is actually there!
This is a similar problem to #19752.

**Comment by Martin-Grunewald** [comment]
+1
can't reproduce jenkins error

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #19696

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Well, the same unclear error happens again.
Redoing the tests once more?

**Comment by davidlange6** [comment]
@smuzaffar - could we save /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/addOnTests.log into the test results summary pages to make debugging add-on tests easier?
 [maybe it is there already but I can't find it..]

**Comment by Martin-Grunewald** [comment]
Please update this PR with the changes from #19696

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
