### PR TITLE
Run3-alca229 Try to fix the issue on Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc as reported in #39134

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to fix the issue on Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc as reported in #39134

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
+alca
- no differences aside from MTD
- fix in line with the recommendation in https://github.com/cms-sw/cmssw/issues/39134

**Comment by perrotta** [comment]
+1

**Pull request merged**
