### PR TITLE
[NanoAOD] Add ParticleNet-based Muon ID (Rework of #46153)

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Rework of https://github.com/cms-sw/cmssw/pull/46153. 
The updated model file is in https://github.com/cms-data/PhysicsTools-NanoAOD/pull/18.

> PR description:
> 
> This PR adds ParticleNet-based Muon ID for NanoAODv15.
> The feature was discussed during Muon POG meeting [(23/09/2024)](https://indico.cern.ch/event/1457874/) and it will be discussed during XPOG meeting [(2/10/2024)](https://indico.cern.ch/event/1462345/)
> 

#### PR validation:

`runTheMatrix.py -w nano --ibeos -l 2500.211`

### CODE REVIEW

**Comment by hqucms** [comment]
test parameters:
 - pull_requests = https://github.com/cms-data/PhysicsTools-NanoAOD/pull/18
 - enable = nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
@jlidrych Could you please check the implementations here and make sure everything is correct? Please also provide a comparison of the model output using this NanoAOD-based implementation vs the training framework to see if the results agree with each other.

**Comment by hqucms** [comment]
> @jlidrych Could you please check the implementations here and make sure everything is correct? Please also provide a comparison of the model output using this NanoAOD-based implementation vs the training framework to see if the results agree with each other.

ping @jlidrych @cms-sw/muon-pog-l2

**Comment by jlidrych** [comment]
My apologies for slow reply.
[Here](https://indico.cern.ch/event/1457874/contributions/6137867/attachments/2932728/5194822/PNetValidation.pdf) are the validation plots. 
Please let me know if you would like to see some additional plots.

**Comment by hqucms** [comment]
> My apologies for slow reply. [Here](https://indico.cern.ch/event/1457874/contributions/6137867/attachments/2932728/5194822/PNetValidation.pdf) are the validation plots. Please let me know if you would like to see some additional plots.

Thanks a lot @jlidrych ! Looks good to me.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please abort

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
ignore tests-rejected with ib-failure

The dasquery failures are also present in the IBs.

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
I'm seeing an error that I believe comes from this PR:

`customising the process with nanoAOD_customizeCommon from PhysicsTools/NanoAOD/nano_cff
Starting  cmsRun  step4_NANO.py
----- Begin Fatal Exception 31-Oct-2024 21:04:55 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step4_NANO.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file PhysicsTools/NanoAOD/data/PNetMuonId/model.onnx anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/cern.ch/work/m/mnguyen/public/integration/CMSSW_14_2_X_2024-10-30-2300/poison:/afs/cern.ch/work/m/mnguyen/public/integration/CMSSW_14_2_X_2024-10-30-2300/src:/afs/cern.ch/work/m/mnguyen/public/integration/CMSSW_14_2_X_2024-10-30-2300/ext\
ernal/el8_amd64_gcc12/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-10-30-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el8_amd64_gcc12/cms/cmssw/CMSSW_14_2_X_2024-10-30-2300/external/el8_amd64_gcc12/data
Current directory is: /tmp/mnguyen/135.4_ZEEFS_13
`

Can you take a look?

**Comment by mandrenguyen** [comment]
^^ I think this was due to a delay in the 11AM IB becoming available such that the external cms-data was not found.  I think you can disregard.  Sorry for the noise.

**Pull request merged**
