### PR TITLE
Update for module veto and afterglow correction parameters [CMSSW_13_0_X]

### PR DESCRIPTION
**Pull request by radla118**
#### PR description:
Backport of the PR https://github.com/cms-sw/cmssw/pull/41242

#### PR validation:
Validated by running runTheMatrix.py -l 1020.0 configuration.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
The modified parameters are intended to be used for the 2023 data-taking period (CMSSW_13_0_X).

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:

 - workflow = 1020.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
also tagging @cms-sw/fastsim-l2

**Comment by tvami** [comment]
urgent
 * we should include this in 13_0_3

**Comment by perrotta** [comment]
+1
- The fastsim error does not look related to this PR: since it is said to be urgent, let have it merged for the next IB, and the following build of the 13_0_3 release

**Comment by perrotta** [comment]
merge

**Pull request merged**
