### PR TITLE
Phase2-hgx346X Add new collection names and information of Calibration Cells to the HGCal SD Class

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add new collection names and information of Calibration Cells to the HGCal SD Class. This is to replace #42961 which was messed up

#### PR validation:

Tested using the cfg file in SimG4CMS/Calo/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by antoniovilela** [comment]
@civanch @srimanob 
Vladimir, will you open the issue as mentioned in https://github.com/cms-sw/cmssw/pull/42961#issuecomment-1756001870

**Comment by srimanob** [comment]
Here it is, https://github.com/cms-sw/cmssw/issues/42986

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by antoniovilela** [comment]
@bsunanda @srimanob @civanch
Sunanda, Vladimir, could you explain in the issue create by Phat (https://github.com/cms-sw/cmssw/issues/42986) the rationale of having the Phase-2 detector SIM collections by default, even if empty, why one cannot have a switch, etc.?
With this we will at least document in the issue for future reference.
Thanks.

**Comment by civanch** [comment]
+1

let us move the discussion to the issue #42986

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1
   - The issue of having Phase-2 branches in Run 3 workflows will be followed up in https://github.com/cms-sw/cmssw/issues/42986

**Pull request merged**
