### PR TITLE
[12_4_X] Add check of Tracker HV in BeamSpot DQM clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #39347 
This also includes the backport of #38925 (update the unitTest input file) which is a 1 commit PR that was never backport to 12_4_X.

A check on the Tracker HV (both pixels and strips) is added in order not to run on events which are by construction not useful for the BeamSpot determination.
Plus some minor improvements to the DQM BeamSpot clients.

#### PR validation:
See master PR

#### Backport:
Backport of #39347

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #39347

**Comment by francescobrivio** [comment]
type performance-improvement

**Comment by francescobrivio** [comment]
urgent

 - meant for the new 12_4_X release for data-taking

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
+1

**Comment by syuvivida** [comment]
This PR passed the test at playback.
+1

**Comment by saumyaphor4252** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
