### PR TITLE
GT Updates: 92X offline, relval, promptLike, and HLT_frozen GT updated to make the release self-consistent with the data taken with it 

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI data

   * **RunI HLT processing** : [92X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_frozen_v6) as [92X_dataRun2_HLT_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_frozen_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_HLT_frozen_v6/92X_dataRun2_HLT_frozen_v7):
      * SnapShot of 92X_dataRun2_HLT_Queue

   * **RunI Offline processing** : [92X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_v5) as [92X_dataRun2_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_v5/92X_dataRun2_v7):
      * Marchchereco Queue

## RunII data

   * **RunII Offline processing** : [92X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_v5) as [92X_dataRun2_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_v5/92X_dataRun2_v7):
      * Match Rereco Queue

   * **RunII Offline relval processing** : [92X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_relval_v6) as [92X_dataRun2_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_relval_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_relval_v6/92X_dataRun2_relval_v8):
      * Match Rereco Queue + correct L1menu

   * **RunII Prompt processing** : [92X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_PromptLike_v5) as [92X_dataRun2_PromptLike_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_PromptLike_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_PromptLike_v5/92X_dataRun2_PromptLike_v7):
      * SnapShot of 92X_dataRun2_Prompt_Queue

   * **RunI HLT processing** : [92X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_frozen_v6) as [92X_dataRun2_HLT_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_dataRun2_HLT_frozen_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_dataRun2_HLT_frozen_v6/92X_dataRun2_HLT_frozen_v7):
      * SnapShot of 92X_dataRun2_HLT_Queue

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
+1

- changed are seen only in data workflows as expected
- the amount of change of conditions is rather big and all these conditions have been validated in separate dedicated validation campaigns by PdmV.
- these conditions are already part of 94X in PR #20707

**Comment by arunhep** [comment]
hold

**Comment by arunhep** [comment]
@lpernie we need to check wf1010.0, last time when we deployed legacy and re-reco conditions in 94X we saw the problem in this wf https://github.com/cms-sw/cmssw/pull/20707#issuecomment-334055250
I am checking it. If this crashes here as well, then you may have to add this commit https://github.com/cms-sw/cmssw/pull/20736/commits/a553ba396caa19a35b946f11b8cf7b3fe798a3b9

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
unhold

**Comment by arunhep** [comment]
please test workflow 1010

**Comment by lpernie** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
please test
(comparisons are gone)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
