### PR TITLE
Add miniAODDQM FastSim Validation

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR follows the discussion in https://github.com/cms-sw/cmssw/pull/37347 and https://github.com/cms-sw/cmssw/issues/37351, especially on DQM part from @jfernan2 [here](https://github.com/cms-sw/cmssw/pull/37347#issuecomment-1079388839)
This PR is a first attempt to add @miniAODDQM to FastSim validation sequence.

Note:
- Code style can be adjusted (i.e. completely separate between FullSim and FastSim, or share as this PR), following the suggestion from @cms-sw/dqm-l2 
- There are warning from JetMET analyzer as it looks for HLT. I assume this is a task of JetMET to modify the code to accept NoHLT from FastSim.
- Next steps:
   - Adding VALIDATION:@miniAODValidation is maybe the next step. My stupid question, what is difference between VALIDATION:@miniAODValidation and DQM:@miniAODDQM. How we choose which module should land on which?
   - NanoAOD: The structure needs to change, by splitting GEN out from NANO.

FYI @sbein 

#### PR validation:
Run the config files from the following `runTheMatrix` work,
`runTheMatrix.py --what upgrade -l 13234.0 --command="-n 100" --wm init`

Additional DQM histrograms are up as expected. One can see from https://tinyurl.com/25u6xovu (with this PR), compared with https://tinyurl.com/27xwxcqh (without this PR)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
+dqm

- extra memory added caused by running miniAODDQM sequence on fastsim

**Comment by srimanob** [comment]
@emanueleusai 
Could you please give a hint on what to be landed on Validation and DQM steps of MiniAOD? Thanks.

Note that, I add this PR (MiniAOD validation) together with the discussion of NanoAOD validation for FastSim in today SIM meeting (Talk of Run-3 FastSim workflow), 
https://indico.cern.ch/event/1182398/

**Comment by emanueleusai** [comment]
> @emanueleusai Could you please give a hint on what to be landed on Validation and DQM steps of MiniAOD? Thanks.
> 
> Note that, I add this PR (MiniAOD validation) together with the discussion of NanoAOD validation for FastSim in today SIM meeting (Talk of Run-3 FastSim workflow), https://indico.cern.ch/event/1182398/

@srimanob can you clarify your question? What does landing on Validation and DQM steps of MiniAOD mean?

**Comment by srimanob** [comment]
Hi @emanueleusai 

Currently if I check on what VALIDATION and DQM are done for miniaod, I see:

```
validationMiniAOD = cms.Sequence(type0PFMEtCorrectionPFCandToVertexAssociationForValidationMiniAOD *
JetValidationMiniAOD * METValidationMiniAOD * tauValidationSequenceMiniAOD * bTagMiniValidationSource)
```
and

```
DQMOfflineMiniAOD = cms.Sequence(jetMETDQMOfflineRedoProductsMiniAOD*bTagMiniDQMSource*muonMonitors_miniAOD*MuonMiniAOD*DQMOfflinePF)
```

My curiosity is how do we know what should be in VALIDATION, or DQM? For example, the differences between `bTagMiniValidationSource` and `bTagMiniDQMSource`. 

Thanks.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
@srimanob thank you for the explanation, I lack the historical perspective of this code to grasp the reasoning behind this choice in the miniAOD sequences. @jfernan2 perhaps has a better insight on this.

> Hi @emanueleusai
> 
> Currently if I check on what VALIDATION and DQM are done for miniaod, I see:
> 
> ```
> validationMiniAOD = cms.Sequence(type0PFMEtCorrectionPFCandToVertexAssociationForValidationMiniAOD *
> JetValidationMiniAOD * METValidationMiniAOD * tauValidationSequenceMiniAOD * bTagMiniValidationSource)
> ```
> 
> and
> 
> ```
> DQMOfflineMiniAOD = cms.Sequence(jetMETDQMOfflineRedoProductsMiniAOD*bTagMiniDQMSource*muonMonitors_miniAOD*MuonMiniAOD*DQMOfflinePF)
> ```
> 
> My curiosity is how do we know what should be in VALIDATION, or DQM? For example, the differences between `bTagMiniValidationSource` and `bTagMiniDQMSource`.
> 
> Thanks.

**Comment by jfernan2** [comment]
> Currently if I check on what VALIDATION and DQM are done for miniaod, I see:
> 
> ```
> validationMiniAOD = cms.Sequence(type0PFMEtCorrectionPFCandToVertexAssociationForValidationMiniAOD *
> JetValidationMiniAOD * METValidationMiniAOD * tauValidationSequenceMiniAOD * bTagMiniValidationSource)
> ```
> 
> and
> 
> ```
> DQMOfflineMiniAOD = cms.Sequence(jetMETDQMOfflineRedoProductsMiniAOD*bTagMiniDQMSource*muonMonitors_miniAOD*MuonMiniAOD*DQMOfflinePF)
> ```
> 
> My curiosity is how do we know what should be in VALIDATION, or DQM? For example, the differences between `bTagMiniValidationSource` and `bTagMiniDQMSource`.
 
It is up to the subsystems to decide what runs and define the sequences, in this case Validation and DQM are exactly identical:

bTagMiniDQMSource  https://github.com/cms-sw/cmssw/blob/ab53a690cf1c49616d5d559305dd1e6884021ad4/DQMOffline/RecoB/python/bTagMiniDQM_cff.py#L75


bTagMiniValidationSource   https://github.com/cms-sw/cmssw/blob/ab53a690cf1c49616d5d559305dd1e6884021ad4/DQMOffline/RecoB/python/bTagMiniDQM_cff.py#L100

despite the names

**Comment by davidlange6** [comment]
> On Jul 21, 2022, at 12:15 PM, jfernan2 ***@***.***> wrote:
> 
> 
> Currently if I check on what VALIDATION and DQM are done for miniaod, I see:
> 
> validationMiniAOD = cms.Sequence(type0PFMEtCorrectionPFCandToVertexAssociationForValidationMiniAOD *
> JetValidationMiniAOD * METValidationMiniAOD * tauValidationSequenceMiniAOD * bTagMiniValidationSource)
> 
> and
> 
> DQMOfflineMiniAOD = cms.Sequence(jetMETDQMOfflineRedoProductsMiniAOD*bTagMiniDQMSource*muonMonitors_miniAOD*MuonMiniAOD*DQMOfflinePF)
> 
> My curiosity is how do we know what should be in VALIDATION, or DQM? For example, the differences between bTagMiniValidationSource and bTagMiniDQMSource.
> 
> It is up to the subsystems to decide what runs and define the sequences, in this case Validation and DQM are exactly identical:
> 
> bTagMiniDQMSource https://github.com/cms-sw/cmssw/blob/ab53a690cf1c49616d5d559305dd1e6884021ad4/DQMOffline/RecoB/python/bTagMiniDQM_cff.py#L75
> 
> bTagMiniValidationSource https://github.com/cms-sw/cmssw/blob/ab53a690cf1c49616d5d559305dd1e6884021ad4/DQMOffline/RecoB/python/bTagMiniDQM_cff.py#L100
> 
> despite the names

Eg, there uss no point in having this validation sequence..

Once upon a time the distinction was that things that needed MC truth information were to run in the validation sequence and things that did not ran in dqm. Is this no longer recommended by the dqm group?

**Comment by jfernan2** [comment]
I am not in charge of DQM any longer since Jan 2022, however from the technical point of view, afaik, Validation (close to PdmV) and DQM (close to DC) sequences are different in what samples to be run and target of the developers/users concerns. I see no problem on reusing or recycling sequences in one and another. What should not be run is VALIDATION and DQM simultaneously

**Comment by makortel** [comment]
> What should not be run is VALIDATION and DQM simultaneously

Umm, doesn't the reco step of every RelVal MC workflow do that?

**Comment by srimanob** [comment]
> > What should not be run is VALIDATION and DQM simultaneously
> 
> Umm, doesn't the reco step of every RelVal MC workflow do that?

As I check, we have both `@miniAODValidation` and `@miniAODDQM` since CMSSW_8_1_0_pre6
https://github.com/cms-sw/cmssw/pull/14469

However, we can fix if this is not the proper thing to be done.

**Comment by srimanob** [comment]
@cms-sw/pdmv-l2 @cms-sw/dqm-l2 
This PR is ready to review, Thanks.

The last change (after rebase) is to add nanoDQM sequence. This is to prepare for the next PR for NanoDQM. It will need more intervention in `runTheMatrix` side to handle NANO + NanoDQM, so I would like to do it separately.

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
Note that, I open the issue https://github.com/cms-sw/cmssw/issues/38828 to follow up on the review of sequences used in MC relvals.

**Comment by srimanob** [comment]
+Upgrade

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
code-checks

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
This PR seems to go far beyond expectation, to complete the MiniAODValidation and also harvesting for FastSim. Should we discuss it maybe at the DQM meeting, so that POGs (specially Tau and JetMET) aware of the change? @cms-sw/dqm-l2

**Comment by srimanob** [comment]
This PR can be closed as it is taken over by https://github.com/cms-sw/cmssw/pull/38834 for complete task of FastSim validation.

**Pull request closed without merging**
