### PR TITLE
FixZeroOccupancyOnline

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR fix the Pixel zero occupancy rocs plots in Online DQM
The plots where broken by the switch to multithread in Offline

The fix is not very elegant but it works, the logic of the previous code was completely wrong: for each module zero occupancy rocs in the full shell/half cylinder where added up, now they are counted only once each 10 lumisections

Since these plots are produced only in Online DQM I am not sure if I should make the same PR in 81X, please let me know.

### CODE REVIEW

**Comment by fioriNTU** [comment]
@dmitrijus can you please start the tests, would be great to have this integrated in the next Online release if possible

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
You have to make and merge 81x version of it first, you know the drill.

**Comment by fioriNTU** [comment]
@dmitrijus ok, I will do it asap, I was not sure since this PR has impact only in Online DQM and the "Phase 0" DQM will be completely superseeded by the Pahse I at the beginning of 2017

**Comment by fioriNTU** [comment]
Sorry, I found another minor bug here, the plots were filled with a bin in advance ... I will add again to the tag collector even if it is not so urgent now

**Comment by dmitrijus** [comment]
You need to get into 81x - I guess another PR and link it here.

**Comment by dmitrijus** [comment]
found it: https://github.com/cms-sw/cmssw/pull/16199

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
