### PR TITLE
GEM-CSC Trigger for Run-3

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR puts in place the missing pieces for the GEM-CSC trigger for Run-3
* I removed `CSCUpgradeMotherboard`, and absorbed `CSCGEMMotherboardME11` and `CSCGEMMotherboardME21` into `CSCGEMMotherboard`. There are now just two motherboards remaining (`CSCMotherboard` and `CSCGEMMotherboard`) down from 6. The old GEM processor (`GEMCoPadProcessor`) and an obsolete lookup table class `CSCUpgradeMotherboardLUT` were deleted.
* This massive reduction in number of classes makes the `CSCTriggerPrimitivesBuilder` a lot simpler. 
* The GEM-to-CSC matching is now CSC-central, that is: GEM coordinates (pad, roll) are translated into key halfstrip and key wiregroup. It is used to be GEM-central, but there is no latency in the trigger to do these operations. For all coordinate translations, we rely on `CSCLUTReader` and LUTs in https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/tree/master/GEMCSC/CoordinateConversion. 
* Matching in a chamber in a BX is first attempted for ALCT-CLCT-GEM, then CLCT-2GEM, then ALCT-2GEM. ALCT-CLCT type LCTs are not rejected if there are no matching GEMs.
* The GE2/1-ME2/1 integrated local trigger is not supported for D41 or D49 geometries with 8 eta partitions. Only the GE2/1 geometry with 16 eta partitions is supported. I tested it with a D76 geometry which works well.
* The matching is still based on difference in half-strip. Soon, we'll change that to incorporate the CCLUT slope. The halfstrip windows are set to be >98% efficient for pT > 5 GeV muons. I suppose this could be lowered further to pT > 3 GeV.
* Quality control tests were expanded for the new GEM-CSC trigger primitives. Though I did delete the QC in `CSCMuonPortCard`. After all, the QC class is designed to operate on a single (O)TMB, rather than on an entire endcap trigger sector. 
* The `GEMInternalCluster` class members are properly initialized in the constructor. 

Follow-up of https://github.com/cms-sw/cmssw/pull/34513, https://github.com/cms-sw/cmssw/pull/33974 and https://github.com/cms-sw/cmssw/pull/33570. 

Documentation is being compiled in a detector note (should be ready by end of the Summer).

#### PR validation:

Tested the code so far on `/RelValSingleMuPt10/CMSSW_11_3_0-113X_mcRun4_realistic_v7_2026D76noPU-v1/GEN-SIM-DIGI-RAW`. A few efficiency plots are added below. 

Efficiency is ~98% in ME1/1 across the eta range. Efficiency is ~98% in ME2/1 across the eta range, except for near |eta|~1.8 and 2.05 where the high voltage drops. This drop can be mitigated if the number of layers on an ALCT is reduced to 3. However, because the backgrounds in Phase-2 not well understood I am keeping the number of layers to at least 4.

I ran interactively on a few thousand events. I did not see any LogWarnings from the `LCTQualityControl` class about potentially invalid ALCTs, CLCTs or LCTs.

I'll also check the performance on PU200, but that should be largely unaffected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

FYI @tahuang1991 @rathjd

### CODE REVIEW

**Comment by dildick** [comment]
LCT efficiency (CSC trigger) for 10 GeV prompt muons in ME1/1 without pileup

Screen Shot 2021-07-21 at 8 48 27 PM

LCT efficiency (GEM-CSC trigger) for 10 GeV prompt muons in ME1/1 without pileup

Screen Shot 2021-07-21 at 8 48 20 PM

LCT efficiency (CSC trigger) for 10 GeV prompt muons in ME2/1 without pileup

Screen Shot 2021-07-21 at 8 48 13 PM

LCT efficiency (GEM-CSC trigger) for 10 GeV prompt muons in ME2/1 without pileup

Screen Shot 2021-07-21 at 8 48 52 PM

**Comment by dildick** [comment]
Seems like the only PU200 relval with a decent GE2/1 geometry is `/RelValSingleMuPt10/CMSSW_11_2_0_pre9-PU_112X_mcRun4_realistic_v4_2026D66PU200-v1/GEN-SIM-DIGI-RAW`. I'll try this later.

**Comment by dildick** [comment]
@cecilecaillol After this, I expect another PR to enable the GEM-CSC matching based on the CCLUT slope, and some fine-tuning of the matching parameters. But probably nothing as big as the past few PRs... All the machinery is in place.

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
I think I fixed this
```
-bash-4.2$ USER_CUDA_FLAGS='--expt-relaxed-constexpr' USER_CXXFLAGS='-Wno-register -fsyntax-only' scram build -k -j 32 COMPILER='llvm compile'

>> Local Products Rules ..... started
>> Local Products Rules ..... done
------- copying files from src/GEMCode/GEMValidation/scripts -------
>> copied makeCCLUT.sh
>> Creating project symlinks
>> Entering Package L1Trigger/CSCTriggerPrimitives
>> Entering Package GEMCode/GEMValidation
>> Entering Package Validation/MuonCSCDigis
>> Compile sequence completed for CMSSW CMSSW_12_0_X_2021-07-18-0000
```

**Comment by dildick** [comment]
@cecilecaillol Can you restart the tests, please?

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
Not sure why the warning did not show up locally before. Anyway, I had to remove another `virtual` statement in front of a `run()` function in the `CSCMotherboard` which is now obsolete.

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
The relval failure is not related to this PR.

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
@dildick despite the relval failure is not related to the changes in this PR, I'd like to see a complete check of the PR to get the DQM comparison since none of the trials performed so far concluded, so I am retriggering the tests again

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
@jfernan2 Thanks for the quick turn-around. There are a few minor changes in the L1T CSC DQM, but that's expected since we enhanced ME1/1 and/or ME2/1 LCTs depending on the era.

**Comment by dildick** [comment]
And there are no differences in Run-1 or Run-2 scenarios. I was not expecting any.

**Comment by dildick** [comment]
In all the performance with the tests look good. That will be it for CSC and GEM-CSC trigger for a while. I have all features for CMSSW_12_0_0_pre5 in. There will be a few updates in late Summer or Fall for GEM-CSC trigger, but nothing major.

@qliphy If you want to sign this PR. Thanks.

**Comment by qliphy** [comment]
+1

**Pull request merged**
