### PR TITLE
Run3-gex103 Use of ESGetToken in Validation/Geometry and updating the cfg's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use of ESGetToken in Validation/Geometry and updating the cfg's

#### PR validation:

Use the cfg's in the test directory

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
