### PR TITLE
[13.0.X] Move `RecoPixelVertexing` subsystems to `RecoTracker`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/41058

#### PR description:

Moved all `RecoPixelVertexing` subsystems to `RecoTracker`:
   * `RecoPixelVertexing/Configuration`  → `RecoTracker/Configuration`
   * `RecoPixelVertexing/PixelTrackFitting`  → `RecoTracker/PixelTrackFitting`
   * `RecoPixelVertexing/PixelTriplets`  → `RecoTracker/PixelSeeding`
   * `RecoPixelVertexing/PixelLowPtUtilities`  → `RecoTracker/PixelLowPtUtilities`
   * `RecoPixelVertexing/PixelVertexFinding`  → `RecoTracker/PixelVertexFinding`

Technical, no regressions expected.

#### PR validation:

Run successfully: 
   * standard limited matrix: `runTheMatrix.py -l limited --ibeos`
   * `addOnTests.py`
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/41058

### CODE REVIEW

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+1

**Comment by VinInn** [comment]
what about 
```RecoPixelVertexing/PixelVertexFinding``` => ```RecoVertex/PixelVertexFinding```

**Comment by perrotta** [comment]
> what about
> `RecoPixelVertexing/PixelVertexFinding` => `RecoVertex/PixelVertexFinding`
> ?

@VinInn this is a backport of a PR discussed at length in the master (and not yet merged, by the way): if you have any different suggestion you should rather post it there. Perhaps with some extremely good argument to justify something different from what was agreed so far.

**Comment by mmusich** [comment]
> what about
`RecoPixelVertexing/PixelVertexFinding` => `RecoVertex/PixelVertexFinding`

Indeed this makes more sense, thanks for the suggestion. Unfortunately doing it in master implies recollecting a lot of signatures.

**Comment by missirol** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
hold
- This will of corse not be backported, unless strictly needed by a (possible future) backport of the porting of pixel tracks to Alpaka, see e.g. #41117

**Comment by fwyzard** [comment]
> hold
> 
>     * This will of corse not be backported, unless strictly needed by a (possible future) backport of the porting of pixel tracks to Alpaka, see e.g. [[WIP] Porting Pixel Tracks to Alpaka #41117](https://github.com/cms-sw/cmssw/pull/41117)

OK, though this is the opposite of what was said during the ORP two weeks ago.

Otherwise I would have asked **not** to merge #41058 in the first place.

At this point, I guess we have to see how best to proceed with the Alpaka developments and backport.

**Comment by perrotta** [comment]
> OK, though this is the opposite of what was said during the ORP two weeks ago.

At the ORP it was decided that this PR will only get backported if needed by a contemporary backport of the porting of pixel tracks to Alpaka, which is what is written in the entry you are referring to. The PRs with those portings are still under development in the master, let conclude their iter over there before deciding what to backport and how to do it.

**Comment by mmusich** [comment]
> what about
RecoPixelVertexing/PixelVertexFinding => RecoVertex/PixelVertexFinding
?

I am ready to submit a PR to master [that does it](https://github.com/cms-sw/cmssw/compare/master...mmusich:cmssw:move_PixelVertexFinding_from_RecoTracker_to_RecoVertex?expand=1).

Shall I wait for the alpaka migration to complete in master?

**Comment by AdrianoDee** [comment]
> > what about
> > RecoPixelVertexing/PixelVertexFinding => RecoVertex/PixelVertexFinding
> > ?
> 
> I am ready to submit a PR to master [that does it](https://github.com/cms-sw/cmssw/compare/master...mmusich:cmssw:move_PixelVertexFinding_from_RecoTracker_to_RecoVertex?expand=1).
> 
> Shall I wait for the alpaka migration to complete in master?

I would wait yes ( :

**Comment by perrotta** [comment]
Clearly this PR does not need to be backported to 13_0_X any more, see https://github.com/cms-sw/cmssw/pull/41223#issuecomment-1495650568

**Comment by mmusich** [comment]
Coming back to this very old thread:

> I am ready to submit a PR to master [that does it](https://github.com/cms-sw/cmssw/compare/master...mmusich:cmssw:move_PixelVertexFinding_from_RecoTracker_to_RecoVertex?expand=1).
> Shall I wait for the alpaka migration to complete in master?

now that the alpaka migration is done, I guess we could finally go ahead and do it. I am not sure if to target already `14_1_X` or let it for `14_2_X` (probably `14_2_X` sounds better to avoid complications with the HI data-taking preps).

**Comment by fwyzard** [comment]
I agree it would be safer to do it early in `14_2_X`.

**Comment by mmusich** [comment]
> I agree it would be safer to do it early in 14_2_X.

Here it is: https://github.com/cms-sw/cmssw/pull/45842

**Pull request closed without merging**
