### PR TITLE
Define new run2_miniAOD_devel and run2_nanoAOD_102Xv1 modifiers

### PR DESCRIPTION
**Pull request by peruzzim**
As agreed for support of running on different miniAOD in nanoAOD production, and for protecting backports that would modify the miniAOD content.

### CODE REVIEW

**Comment by peruzzim** [comment]
@fabiocos @slava77 could you please test this? It would be nice to have it integrated as soon as possible (together with the backport #25444) to work on adapting the other open PRs. Thank you really much

**Comment by fabiocos** [comment]
please test

@peruzzim you have the right launch the test as well (in this case not testing really anything)

**Comment by fabiocos** [comment]
+operations 

the DQM failures cannot be related to this PR

**Comment by fabiocos** [comment]
@peruzzim @fgolf I expect a PR where the nanoAOD changes are moved under the new modifier, am I correct?

**Comment by fabiocos** [comment]
+1

**Comment by peruzzim** [comment]
@fabiocos yes, PR to nanoAOD using these modifiers is coming

**Pull request merged**
