### PR TITLE
Prepare for concurrent IOVs

### PR DESCRIPTION
**Pull request by wddgit**
Change return type of produce from shared_ptr to
unique_ptr.  Slightly improves performance also.
Also one fix added by 'scram b code-checks'.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
