### PR TITLE
added unit test for das-selected-lumis.py

### PR DESCRIPTION
**Pull request by smuzaffar**
Latest dasgoclient changed json output which broke `das-selected-lumis.py` ( see https://github.com/cms-sw/cmssw/issues/37052 ). This PR adds unit test to run `das-selected-lumis.py` to to make sure that it can properly read `dasgoclient` json output.

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#7650

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
