### PR TITLE
ECAL - Sort digis collections coming from GPU unpacking - 123x

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Contrary to the ECAL digis collections unpacked on a CPU, which are sorted by detector ID, the collections produced from digis that were unpacked on GPU are unsorted. This causes problems with the `find()` function of the `edm::DataFrameContainer`, which only works for sorted detector IDs.
Sorting the collections produced by `EcalCPUDigisProducer` fixes this.

This also adds some code simplifications to `HLTEcalPhiSymFilter`, which is the module for which the issue manifested itself first.

Addresses https://its.cern.ch/jira/browse/CMSHLT-2335

#### PR validation:

The digis collection stored by `hltEcalPhiSymFilter` matches between CPU and GPU machines after sorting the collections.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #38321 needed for ECAL calibrations

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38321

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

See https://github.com/cms-sw/cmssw/pull/38321#issuecomment-1153715807.

**Comment by jpata** [comment]
+reconstruction
- fixes for HLT
- no effect observed in offline reco in the tests
- backport of https://github.com/cms-sw/cmssw/pull/38321

**Comment by qliphy** [comment]
+1
tested in master IB

**Pull request merged**
