### PR TITLE
Fix CMS deprecation warnings in GeneratorInterface/Hydjet2Interface

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Remove uses of legacy module types and getting data from EventSetup without a token.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
NOTE: the modules changed are not using consumes for Event data which means they will not run (and haven't all of Run 2). Perhaps the modules in this package should be reviewed to see if they should be removed from CMSSW.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping @cms-sw/generators-l2

**Comment by SiewYan** [comment]
Looks good

**Comment by SiewYan** [comment]
+1

**Comment by SiewYan** [comment]
> NOTE: the modules changed are not using consumes for Event data which means they will not run (and haven't all of Run 2). Perhaps the modules in this package should be reviewed to see if they should be removed from CMSSW.

Given there are on-going effort on integrating Hydjet, I reckon this interface will be updated with consume? What do you think? @Gurpreet, @Saptaparna,

**Comment by qliphy** [comment]
please test
just to refresh the test results before merging this PR

**Comment by wouf** [comment]
No DatabasePDG files found in the new hydjet2 (2.4.3) version. For which reason this PR is needed?

**Comment by SiewYan** [comment]
@wouf , the Hydjet2Interface expecting changes from the on-going upgrade? I saw that you are working on a new version under test? If so, could you uses @Dr15Jones 's to fix the CMS depreciation warning message?

**Comment by SiewYan** [comment]
-1

**Comment by wouf** [comment]
@SiewYan I mean that this PR has conflict with #36316 because of  DatabasePDG.* files. In PR#36316, these files were deleted. If You just didn't change it, I think everything would be fine.

**Comment by Dr15Jones** [comment]
@SiewYan how do you wish to proceed with this PR?

**Comment by SiewYan** [comment]
@Dr15Jones , I suggest to close it for now in favour of @wouf's on-going PR #36316

**Pull request closed without merging**
