### PR TITLE
feat: update TopMuEG skim to latest HLT paths in BTV

### PR DESCRIPTION
**Pull request by AnnikaStein**
#### PR description:

- this PR modifies the existing TopMuEG skim by moving to latest recommended HLT paths as suggested by the BTV-POG
- see also recent presentation in BTV-POG WG meeting with relevant slides: [here](https://indico.cern.ch/event/1141147/#5-topmueg-skim-code-for-mueg-t)

#### PR validation:

- a test configuration is added to DPGAnalysis/Skims/test (new test directory created as this is the first DPG / POG skim with a test)
- setup given as follows: `skims -s SKIM:TopMuEG --mc --dasquery=file dataset=/RelValTTbar_14TeV/CMSSW_12_1_0_pre2-PU_121X_mcRun3_2021_realistic_v1-v1/GEN-SIM-RECO -n 100 --conditions auto:phase1_2021_realistic --eventcontent=FEVTDEBUGHLT --datatier=RAW-RECO --python_filename=test_TopMuEG_SKIM.py --processName=SKIMTopMuEG --no_exec --era=Run3`
- example runs over 100 events obtained from RelVal samples, using CMSSW_12_1_0_pre2
- from the initial 100 events, 3 pass, 97 fail
- for this example, skim reduces file size from 484MB to 19MB

####
@johnalison @soureek

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
Nice work on updating the skim. Could all the "keep" statements in the test fragment be reduced to just a few lines by using more inclusive wildcards or this is not possible?

**Comment by AnnikaStein** [comment]
> Nice work on updating the skim. Could all the "keep" statements in the test fragment be reduced to just a few lines by using more inclusive wildcards or this is not possible?

Thank you for the feedback.

It should indeed be possible to reduce some of the lines by manually combining them with wildcards. However, this test fragment is just the result of using the TopMuEGPath as part of [DPG skims](https://github.com/cms-sw/cmssw/blob/master/DPGAnalysis/Skims/python/Skims_DPG_cff.py#L310-L319) which automatically produces this list of keep and drop statements. Maybe it would then make sense to keep it as it is, allowing comparisons with related test configurations of other DPG skims. If I understand correctly, this is a fundamental difference with respect to PAG skims, where the EventContent / keep / drop is defined individually per test configuration, because the use case is different.

Should we decide to still manually adapt the keep / drop statements explicitly to our needs and simplifying or reducing them, this would also be an opportunity to check with all experts involved which branches are of interest. (Tagger outputs? Tagger inputs? Different generations of taggers?)

**Comment by kskovpen** [comment]
Thanks for the explanations! I think this is fine, unless @cms-sw/orp-l2 have other suggestions.

**Comment by qliphy** [comment]
> Thanks for the explanations! I think this is fine, unless @cms-sw/orp-l2 have other suggestions.

fine with me.

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
+1

**Pull request merged**
