### PR TITLE
SiStripCalCosmicsNano ALCANANO: produce NANOEDMAOD

### PR DESCRIPTION
**Pull request by pieterdavid**
#### PR description:

After the first attempt https://github.com/cms-sw/cmssw/pull/34985 failed at the merging step in the CMSSW_12_1_0_pre3 relvals ([hypernews](https://hypernews.cern.ch/HyperNews/CMS/get/relval/15942.html), [log](https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_RVCMSSW_12_1_0_pre3RunCosmics2021__RelVal_2021GR5_210921_144932_6110)) we learned (see also discussion with the Tier0 [CMSTZ-937](https://its.cern.ch/jira/browse/CMSTZ-937) and [dmwm](https://mattermost.web.cern.ch/cms-o-and-c/channels/dmwm) teams) that the workflow should produce NANOEDMAOD (nanoaod::FlatTable etc.), and the conversion to flat trees for NANOAOD is done in the merging step in the production system.
Hence this PR reverts the changes to ConfigBuilder from https://github.com/cms-sw/cmssw/pull/34985 (which changed the output module for ALCARECO skims with NANOAOD data tier), since this is not needed (to facilitate local testing I added a customise method, such that cmsDriver with `--customise=CalibTracker/SiStripCommon/customiseAlCaNano.flatSiStripCalCosmicsNano` directly produces the flat trees, as before).
This should at least stop the failing merge of the outputs in the relvals, although the conversion to flat trees when merging may need some more changes in the production system (I left `dataTier="NANOAOD"` in the [FilteredStream config](https://github.com/cms-sw/cmssw/blob/e99fe4b3b8919db12e17fb76ad7f12f34bbbb64a/Configuration/StandardSequences/python/AlCaRecoStreams_cff.py#L452-L459), anticipating that the same mechanism may be used as for physics skims, which seems to get the dataTier from the CMSSW config in [dmwm.DMCore.StdBase.determineOutputModules](https://github.com/dmwm/WMCore/blob/c05f7999c2c1345b61f29202d3d45e701e76f248/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L204-L234)).

#### PR validation:

Tested one of the runTheMatrix workflows that contain this (138.1), and converted to flat tree with the config from `Configuration/DataProcessing/test/RunMerge.py --input-files file:SiStripCalCosmicsNano.root --mergeNANO`

CC: @mmusich @FlorianBury @mdelcourt @robervalwalsh @tsusa @connorpa @tvami @malbouis @mariadalfonso @gouskos @davidlange6 @amaltaro

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 7.2, 7.21, 7.22, 7.23, 7.24, 7.3, 7.4, 134.813, 136.733, 138.1, 138.2

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * PR in line with the describtion
 * output file `SiStripCalCosmicsNano.root` in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c3960c/19280/runTheMatrix-results/138.1_RunCosmics2021+RunCosmics2021+RECOCOSDPROMPTRUN3+ALCACOSDPROMPTRUN3+HARVESTDCPROMPTRUN3/

**Comment by tvami** [comment]
@perrotta @qliphy this is essentially "fully-signed" now

**Comment by tvami** [comment]
@pieterdavid should we have a 12_0_X backport? aiming for 12_0_3 maybe? (not 12_0_2, unless 12_0_2 takes more time -- I thought it was going to be cut by today)

**Comment by pieterdavid** [comment]
> @pieterdavid should we have a 12_0_X backport? aiming for 12_0_3 maybe? (not 12_0_2, unless 12_0_2 takes more time -- I thought it was going to be cut by today)

It's a small change, so if that'd be useful to get it tested faster, sure - I'll submit the backport in the next ~hour (need to connect to a meeting first)

**Comment by pieterdavid** [comment]
The backport for 12_0_X is https://github.com/cms-sw/cmssw/pull/35490

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/35490

**Comment by tvami** [comment]
> The backport for 12_0_X is #35490

this didn't seem to got registered by the bot

**Comment by qliphy** [comment]
+1

**Pull request merged**
