### PR TITLE
Backport of #28430 (Add variables for PileUp Jet ID BDT in JME Custom-NanoAODs)

### PR DESCRIPTION
**Pull request by nurfikri89**
**Backport of additions from** #28430

This PR adds jet variables needed to train the BDT for PileUp jet ID in the JME Custom-NanoAODs which are not included in the main NanoAODs. The variables are not stored in MiniAODs so they need to be re-calculated again by scheduling pileupJetIdCalculator. Then, the variables need to be stored in ValueMaps and this is done by scheduling PileupJetIDVarProducer plugin which will be added also. The rest is just normal procedure to save variables in NanoAODs. At the moment, these variables are set to be calculated and stored only for AK4PFCHS jets.

**if this PR is a backport please specify the original PR:**

Original PR is #28430

### CODE REVIEW

**Comment by nurfikri89** [comment]
FYI JMAR convenors @alefisico @camclean

**Comment by santocch** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by peruzzim** [comment]
+xpog

changes limited to the JME-specific NANOAOD version

**Comment by peruzzim** [comment]
backport #28430

**Comment by silviodonato** [comment]
+1

**Pull request merged**
