### PR TITLE
[10.3.X] Update GTs. HI MC conditions + MVA selectors into data GTs

### PR DESCRIPTION
**Pull request by lpernie**
##  HI MC
Added Pixel/Strip Quality
Added 6 ECAL TAG (4 EcalTPG  + Laser + Pedestal)
Added HE failure scenario
Added 2 HCAL Tags
. [103X_upgrade2018_realistic_HI_v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_HI_v4/103X_upgrade2018_realistic_HI_v2)

##  2018 MC
Added to all tags additional Geometry from Ianna: XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc
This scenario includes a detailed cavern description and the MB4 shields
in YB+2 and YB-2. It is requested for production.

##  Data
Added MVA selectors to:
.  103X_dataRun2_v3
.  103X_dataRun2_relval_v6
.  103X_dataRun2_PromptLike_HEfail_v4
. 103X_dataRun2_PromptLike_v6
.  103X_dataRun2_HLT_relval_v4

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie I see a number of differences in the histograms that are likely unrelated to this PR and could be due to overlapping merges, do you agree? Is the update final for you?

**Comment by lpernie** [comment]
Hello @fabiocos ,
I agree. 
There are still 4 tags missing from HCAL. They should arrive tomorrow. I will update the PR as soon they arrive.

**Comment by lpernie** [comment]
please test

**Comment by tocheng** [comment]
+1

**Pull request merged**
