### PR TITLE
fixed a bug (related to dxy;el/mu+other case) and add the 3rd highest pt plots

### PR DESCRIPTION
**Pull request by ryonamin**
This is based on the changes #8034.
I have tested this new code in my local area and it works.

There are two independent modifications.
1) bug fix related to dxy plot 
We found that we get an error in specific cases in which trigger path has electron/muon objects and
additionally other objects (e.g. photons).
The problem was caused by
HLTriggerOffline/Exotica/src/HLTExoticaPlotter.cc, line:148.
Previously we tried to fill even for non-electron/muon object because the condition (dxys.size() >0) is satisfied.
So now we fill the histograms only if the object is electron/muon.

2) add the 3rd highest Pt plot (the other changes)
This is a request from a trigger developer.

### CODE REVIEW

**Comment by deguio** [comment]
I fear this one needs a rebase

**Comment by deguio** [comment]
ciao @ryonamin 
this PR doesn't merge. If I understand correctly what happens you should:
- submit again the equivalent of #8034 
- add on top the current #8178

this should be enough to have 74 aligned with 75. could you confirm? please make a single PR so that it will be fully functional since the beginning.

thanks,
F.

**Comment by deguio** [comment]
-1

**Comment by ryonamin** [comment]
Thank you for the explaination. I have learned. I will make a new PR as you suggested.

**Pull request closed without merging**
