### PR TITLE
Changed binary to logical operations in TrackingTools packages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

These clear up clang warnings.

#### PR validation:

Compiling with clang no longer shows the warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction
Technical, just changed bitwise OR to logical OR

**Comment by rappoccio** [comment]
+1

Technical PR

**Pull request merged**
