### PR TITLE
Phase2-hgx198 preparing for corner centered wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Changes made in view of wafer centering vs corner centering

#### PR validation:

Tried with workflow of 3 different scenario of Phase2 geometry D28, D31 and D41

#### if this PR is a backport please specify the original PR:

Needed for the next set of changes

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
