### PR TITLE
L1T DQM migrate modules to DQMGlobalEDAnalyzer

### PR DESCRIPTION
**Pull request by thomreis**
Migrate L1T DQM modules to DQMGlobalEDAnalyzer.

- uGMT
- uGMTMuon
- MP7ZeroSupp
- MuonComp
- RegionalMuonCandComp
- uGT
- OMTF
- BMTF

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Nice work!

**Comment by dmitrijus** [comment]
hold

We need to migrate a few modules to new DQM... Otherwise, this might cause crashes.
See issue: https://github.com/cms-sw/cmssw/issues/21880

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Fixed conflicts.

**Comment by thomreis** [comment]
Hi @fwyzard , do you have a suggestion how to resolve this error? The DQMEDAnalyzer, as a stream module, was providing this function `callWhenNewProductsRegistered` but the DQMGlobalEDAnalyzer does not.

```
In file included from /cvmfs/cms-ib.cern.ch/nweek-02508/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-01-24-2300/src/L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h:21:0,
                 from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-01-24-2300/src/DQM/L1TMonitor/interface/L1TStage2uGT.h:33,
                 from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-01-24-2300/src/DQM/L1TMonitor/src/L1TStage2uGT.cc:12:
/cvmfs/cms-ib.cern.ch/nweek-02508/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-01-24-2300/src/L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h: In instantiation of 'l1t::L1TGlobalUtilHelper::L1TGlobalUtilHelper(const edm::ParameterSet&, edm::ConsumesCollector&, T&, const edm::InputTag&, const edm::InputTag&) [with T = L1TStage2uGT]':
/cvmfs/cms-ib.cern.ch/nweek-02508/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-01-24-2300/src/L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h:262:32:   required from 'l1t::L1TGlobalUtil::L1TGlobalUtil(const edm::ParameterSet&, edm::ConsumesCollector&, T&, const edm::InputTag&, const edm::InputTag&) [with T = L1TStage2uGT]'
/cvmfs/cms-ib.cern.ch/nweek-02508/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-01-24-2300/src/L1Trigger/L1TGlobal/interface/L1TGlobalUtil.h:253:70:   required from 'l1t::L1TGlobalUtil::L1TGlobalUtil(const edm::ParameterSet&, edm::ConsumesCollector&&, T&, const edm::InputTag&, const edm::InputTag&) [with T = L1TStage2uGT]'
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-01-24-2300/src/DQM/L1TMonitor/src/L1TStage2uGT.cc:19:185:   required from here
/cvmfs/cms-ib.cern.ch/nweek-02508/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-01-24-2300/src/L1Trigger/L1TGlobal/interface/L1TGlobalUtilHelper.h:172:13: error: 'class L1TStage2uGT' has no member named 'callWhenNewProductsRegistered'; did you mean 'callWhenNewProductsRegistered_'?
      module.callWhenNewProductsRegistered(std::ref(*this));
      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fwyzard** [comment]
hi @thomreis,
apologies, I have seen this only now.

I will try to understand the issue in the coming days.

**Comment by fwyzard** [comment]
@thomreis , I see additional problems with the migration, unrelated to the `L1TGlobalUtil`: a `global` module is not allowed to change its member variables in the `beginRun` transitions; instead it would need to use the `RunCache` mechanism.

My guess is that the reason why `callWhenNewProductsRegistered()` is not implemented for global modules is similar: it would potentially need to update member variables on a per-event basis, which is not possible with a global method.

I see two ways of going forward:
  - rewrite the modules to comply with the global interface
  - implement a new "stream module with global histograms" DQM module

I can look into the second idea, but not on a short time scale.

**Comment by fwyzard** [comment]
@Dr15Jones @wddgit do you think it would be possible to implement `callWhenNewProductsRegistered()` from `global` modules ?

**Comment by fwyzard** [comment]
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2 what do you think of a `stream` module that makes use of `global` monitor elements ?

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by thomreis** [comment]
It is not sure anymore if we want this PR merged. Once this is decided I will rebase or close the PR.

**Comment by fwyzard** [comment]
If you don't care about having any of these modules running inside the HLT
itself, you can decide to close it.

Ciao,
.Andrea

**Comment by wddgit** [comment]
PR #22382 fixes the global and limited Analyzers so that callWhenNewProductsRegistered will work now in those cases. It was a bug. It already worked in all the other cases.

**Comment by thomreis** [comment]
Closing this PR for now as it is not intended to be run in the HLT and the memory problem has been solved differently.

**Pull request closed without merging**
