### PR TITLE
Material Budget Tool Fixes

### PR DESCRIPTION
**Pull request by schneiml**
This is a set of patches for the material budget tools that I made some time ago for the large FPIX material budget correction project. It is not supposed to be merged right now.

Apart from some convenience changes, it fixes the issue that the Material Budget Validation tools don't work correctly in some IBs and some releases. This issue is caused by code interacting with Geant that depends on initialisation order (actually, it seems to me that what this code does is safe; but in practice, it does not work), related to retrieving a list of materials.

My fix is based on the observation that for the usual use case (described here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackerMaterialBudgetValidation ) this is not needed. 

If we want to go down this route, all the non-functional and superfluous code could and should be removed from the Tools, but I don't really have time to do it now. Also, this means removing a lot of features from the Tool. I have no idea what these are supposed to do and who uses or used them.

(On a side note: all (or at least some of) the `runP_` things except for `runP_Tracker` seem to be broken and are superseded by `runP_Tracker`. They should probably be deleted.)

For everybody who wants to use the Tool for the normal Validation plots, I can only recommend to apply this patch. For CMSSW in general, we have to decide whether the Tool should be fixed properly, or stripped down to the parts that work.

@veszpv @ianna @civanch @zucchett @rovere

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
just to clarify is this a RFC or a real PR?

**Comment by schneiml** [comment]
@davidlange6 I'd say that is a quickfix that should not really go into CMSSW. OTOH, the tools right now are so broken that they can't properly be used at all...

A proper fix using this approach would involve removing all the code that is now superfluous or permanently broken. I don't plan to do that.

**Comment by davidlange6** [comment]
Thanks - could you update the title of the PR accordingly? Thanks

**Comment by schneiml** [comment]
According to what? Assuming we accept that as a fix (as I read from the +1's), I can remove the "RFC"...

**Comment by davidlange6** [comment]
Right, remove RFC, as its no longer a RFC.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
