### PR TITLE
General clean-up of the SimG4Core/CustomPhysics library

### PR DESCRIPTION
**Pull request by civanch**
Some re-design of classes defining CustomParticles is done. It become possible to perform exotic simulation in MT mode. 

Extra python fragment Exotica_MT_SIM_cfi.py may be recommended for exotica simulation instead of old Exotica_HSCP_SIM_cfi.py

Code clean-up include implementing of naming convention for header files and one obsolete class is removed.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
code-checks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
