### PR TITLE
Update L1TrackTrigger step to DD4hep

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This is a PR to handle the DD4hep for L1TrackTrigger step. The overall discussion on DIGI-L1-HLT step is at https://github.com/cms-sw/cmssw/issues/36837

Remaining question include
- Do we still need to check the supported geometry? It is currently hardcoding on XML filename.
This can be followed in the follow up PR.

#### PR validation:
Using `runTheMatrix.py --what upgrade -l 39434.0,39434.911 --wm init`
- Running with DDD workflow, no change is expected.
- Running DD4hep workflow, a job can now pass the L1TrackTrigger step.
```
----- Begin Fatal Exception 20-Feb-2022 16:45:03 CET-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing global begin Run run: 1
   [1] Prefetching for module L1FPGATrackProducer/'TTTracksFromExtendedTrackletEmulation'
   [2] Calling method for EventSetup module trackerDTC::ProducerES/'TrackTriggerSetup'
Exception Message:
NullPointer 
----- End Fatal Exception -------------------------------------------------
```
 To run with full step, one can trigger the test as in https://github.com/cms-sw/cmssw/pull/37078#issuecomment-1053558439

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport, and no need to backport

### CODE REVIEW

**Comment by srimanob** [comment]
The question includes do we still want to keep geometry checking or not?
https://github.com/cms-sw/cmssw/pull/37005/files#diff-ca3eec71dd6d2278c5a8e14b1ae3e0b7afbbc2cb4fd8fa1567571158482c0bdbR358

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
tagging also @tschuh  about https://github.com/cms-sw/cmssw/pull/37005#issuecomment-1047060611

**Comment by srimanob** [comment]
Thanks @mmusich 
It should be good to discuss how do L1T and L1Track teams plan for changes needed to be implemented together with DD4hep. In the current PR, I just ignore the geometry check when DD4hep is used.

FYI @tschuh @bundocka @cms-sw/l1-l2

**Comment by tschuh** [comment]
The geometry check was used at the time when the code got merged into official cms release to bypass some automated tests which did combine geometries (it was the flat geometry I think) with incompatible cabling maps (for tilted geometries). That lead to thrown exceptions and failed tests and eventually to not merge able code.
In the meanwhile we decided that we want a black list instead of a white list and we will try an empty one to begin with. I mean if we see that we don't need that check anymore I guess we could drop it or disable it by default so that a user could use it on purpose. @tomalin what do you think?
What is the actual issue with that check right now?

**Comment by srimanob** [comment]
@tschuh 
Thanks for the comment. If we need, I can try to adapt the dd4hep part to read through the XML file from FileInPath since the DD4hep config will come as
```
process.DDDetectorESProducer = cms.ESSource("DDDetectorESProducer",
    appendToDataLabel = cms.string(''),
    confGeomXMLFiles = cms.FileInPath('Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D88.xml')
)
```
instead of
```
process.XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring(
        'Geometry/CMSCommonData/data/materials/2021/v1/materials.xml',
        'Geometry/CMSCommonData/data/rotations.xml',
        'Geometry/CMSCommonData/data/extend/v2/cmsextent.xml',
        'Geometry/CMSCommonData/data/cavernData/2021/v1/cavernData.xml',
        'Geometry/CMSCommonData/data/cms/2026/v5/cms.xml',
```
Just to make sure I don't mess up the code in the part that you may not need :)

**Comment by tschuh** [comment]
So only for me to understand: Usually L1Tracking code will be called with geometry config source which has a PSet which contains a vector strings. Now with this DD4hep (what is that by the way?) L1Tracking code will be called with geometry config source which has different PSet member? My first question would be if one could not make those PSets look identical?

**Comment by srimanob** [comment]
DD4hep is a toolkit that handles geometry. It is the default geometry handling for CMS for Run-3 (DDD still work but to be dropped in future). The way we currently handle DDD and DD4hep now is using if/else. 

If defined Phase-2 DD4hep workflow will work with compatible geometry anyways, we may not need to check the geometry support. For example, DD4hep workflows which are defined in 
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2026.py

I personally would like to avoid updating DD4hep or DDD PSets since it may effect several places. @cms-sw/geometry-l2 may have additional comments.

**Comment by tschuh** [comment]
Many thanks for this clarification. With our next attempt to merge new code I will check if the current tests require such a check and maybe the problem disappears and if not I can also interface to DD4hep, for now I suggest you do what ever needed to make further progress.

**Comment by srimanob** [comment]
Thanks.
I will keep the PR as is. In case we fix another issue and the workflow can run with this PR, I will enable it for review.

**Comment by srimanob** [comment]
Hi @tschuh @cms-sw/l1-l2 
I think this PR is ready to review and to merge. Could you please?  Thanks.
Then we can follow on unifying the config file of DDD and DD4hep, code clean up.

DD4hep phase-2 wf is now run-able with this PR, together with https://github.com/cms-sw/cmssw/pull/37078 and https://github.com/cms-sw/cmssw/pull/37079

Test result is as expected,
https://github.com/cms-sw/cmssw/pull/37079#issuecomment-1053708966

**Comment by srimanob** [comment]
+Upgrade

This PR will make Phase-2 D88 DD4hep wf runs until complete. The config clean up, geometry checking code for DD4hep should come in the follow up PR. PR test result is as expected, https://github.com/cms-sw/cmssw/pull/37079#issuecomment-1053708966

**Comment by srimanob** [comment]
Kindly ping @cms-sw/l1-l2 
Thanks.

**Comment by epalencia** [comment]
+l1

**Comment by srimanob** [comment]
@cmsbuild please test

Just for refresh the result as the last test was more than a week. The result for standalone test is no change is expected. 

The test with https://github.com/cms-sw/cmssw/pull/37078 shows us that DD4hep Phase-2 wf can run now,
https://github.com/cms-sw/cmssw/pull/37078#issuecomment-1053630969

**Comment by srimanob** [comment]
I think this PR is ready to go. The failure of wfs 312.0 and 25202.0 does not related to this PR as no L1Track is used in Run-1 and Run-2.

**Comment by qliphy** [comment]
+1

**Pull request merged**
