### PR TITLE
Revert back from oversight about rawDataRepacker and rawDataCollector for the BeamPixel DQM application

### PR DESCRIPTION
**Pull request by dinardo**
In making a change to the code I, wrongly, realized that I could merge two sections of the code.
I was wrong because I confused `rawDataCollector` with `rawDataRepacker`.
I reverted back to the original form.
Sorry about that.
- Mauro.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi @dinardo, could you please make sure that there is a name of the subsystem in the title of the PR?

**Comment by andrius-k** [comment]
Hi @dinardo, could you please make sure that there is a name of the subsystem in the title of the PR?

**Comment by dinardo** [comment]
Hi Anrdius,
ok it's done.
- Mauro.

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
@dinardo Thanks!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
