### PR TITLE
VXBS For High Pt

### PR DESCRIPTION
**Pull request by rbhattacharya04**
This pull request contains

- 3 elements of the VXBS covariance matrix as 3 different float variables

- error on the dxyBS

For Muon. From the discussion we had at the Muon POG, these variables will be enough for implementing VXBS constraint on any kind of muon track.

The error on dxyBS looks similar enough with the error on dxy, which you can see in the attached plot. In the plot the blue curve is error on dxy and red one is error on dxyBS. So if everyone agrees we can drop the error on dxyBs.
[dxybsErr_data.pdf](https://github.com/user-attachments/files/17278706/dxybsErr_data.pdf)

### CODE REVIEW

**Comment by ftorrresd** [comment]
please test

**Comment by rbhattacharya04** [comment]
There was an error. The covariance matrix should have been read form tunePMuonBestTrack. At the first commit, it was read from muonBestTrack. At this commit now, this error is fixed, now it is read from tunePMuonBestTrack.

**Comment by hqucms** [comment]
please test

**Comment by ftorrresd** [comment]
@rbhattacharya04 -- do we already have a conclusion on the choice of dxyBS x dxy?

Also, do you think it could be implemented a DQM monitoring in `PhysicsTools/NanoAOD/python/nanoDQM_cfi.py`? Similar to what was done for #45860 (below)...

https://github.com/cms-sw/cmssw/pull/45860/files

Cheers,
Felipe

**Comment by rbhattacharya04** [comment]
Hi @ftorrresd , we would like to keep the error on dxyBS. if we use the error on dxy, the constraint will be weaker.

On implementing this in nanoDQM, I can only start to work on it after the next Wednesday, 23rd October. So if you think we can wait for this, I shall implement it then.

**Comment by ftorrresd** [comment]
> Hi @ftorrresd , we would like to keep the error on dxyBS. if we use the error on dxy, the constraint will be weaker.
> 
> On implementing this in nanoDQM, I can only start to work on it after the next Wednesday, 23rd October. So if you think we can wait for this, I shall implement it then.

Hi @rbhattacharya04 -- if we can have it by the end of this week, should be all right. Thanks!

F.

**Comment by rbhattacharya04** [comment]
Hi @ftorrresd , I have added the new variables in nanoDQM.

**Comment by hqucms** [comment]
please test

**Comment by rbhattacharya04** [comment]
There was a suggestion just yesterday to add the tuneP_charge in the NanoAODs. So, I have done another commit just adding the tuneP_charge.

**Comment by hqucms** [comment]
please test

**Comment by ftorrresd** [comment]
please abort

**Comment by ftorrresd** [comment]
please test

**Comment by ftorrresd** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by oglez** [comment]
One question about this merge request even if a bit late. Why was the variable Muon_tunep_charge was stored as a Float_t? It does not seem a very packed (and accurate) way of storing something that could be -1, 1 or 0 (when not available...) Perhaps I am missing something here...

**Pull request merged**
