### PR TITLE
Relval updates

### PR DESCRIPTION
**Pull request by fabozzi**
Update gensim recycling for MC relvals: use GENSIM from pre6
Adding 2018B relval set (+ updated prompt-like GT meant to cover the run 317435 we are using for 2018B relvals)
Adding a NANOAOD wf on 2018 data

### CODE REVIEW

**Comment by fabozzi** [comment]
FYI: @arunhep @lpernie

**Comment by fabozzi** [comment]
@zhenhu

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@fabozzi are the new files already available at CERN? I would wait for the integration of this PR so as not to perturb the scrutiny of other PRs...

**Comment by fabozzi** [comment]
@fabiocos 
> are the new files already available at CERN? 
I checked randomly for several sampels and I found the GENSIM at CERN

> I would wait for the integration of this PR so as not to perturb the scrutiny of other PRs
OK

**Comment by fabozzi** [comment]
I am integrating this PR with addition of a NANOAOD workflow on 2018 data. After integration of PR #23749 this should run fine now (my local test confirms this).

**Comment by fabozzi** [comment]
please test workflow 136.8521

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@arunhep @lpernie @fabozzi this PR changes the GT fro PromptLike, with large effects on the comparison. Could you please document the changes implied by this new tag, and mention it in the PR title? I guess they are the conditions for 2018B, right?

**Comment by fabozzi** [comment]
The updated GT is meant to cover the run 317435 we are using for 2018B relvals (the v3 GT covers runs up to June 1st). If there are additional GT updates to mention, please reply

**Comment by fabiocos** [comment]
@fabozzi ok, I see that the differences are all concentrated in the wf 250202.181. So this is likely due to the change of CMSSW_10_2_0_pre6-PU25ns_102X_upgrade2018_realistic_v7-v1 , am I correct?

**Comment by fabozzi** [comment]
@fabiocos 
actually this premix workflow is peculiar because it creates from scratch also a (10 events) premix library that is used in the following step3.

Therefore the actual dependence is from:
'CMSSW_10_2_0_pre6-102X_upgrade2018_realistic_v7-v1', 
which points to the MinBias input GENSIM to create the premix library.

In any case, I think we see an effect here because of the small statistics of the premix library (10 events).

**Comment by fabiocos** [comment]
+1

**Pull request merged**
