### PR TITLE
Adding H->inv paths to the HLT Higgs dqm

### PR DESCRIPTION
**Pull request by jasperlauwers**
Backport of #11636

Adding paths to the dqm:
"HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu140_v",
"HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu80_v",
"HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu140_JetIdCleaned_v",
"HLT_DiPFJet40_DEta3p5_MJJ600_PFMETNoMu80_JetIdCleaned_v" 

The naming of these paths required an additional fix in the code as well.

### CODE REVIEW

**Comment by deguio** [comment]
this one should be submitted to 75x, 76x, 80x as well for consistency

**Comment by deguio** [comment]
please test

**Comment by jasperlauwers** [comment]
It is already in 76x, as it is a backport of #11636 
And my PR in 75x was getting closed before because of "not needed for HeavyIons (only planned 75x usage)" ( #11342 )

The last commit adds a fix as was seen to be necessary in 76X ( issue #12036, fix #12048 ).

**Comment by deguio** [comment]
+1
thanks for clarifying

**Pull request closed without merging**
