### PR TITLE
Superclusterfbrem_10_0_X-v1

### PR DESCRIPTION
**Pull request by archiron**
Updated a mis-leading histogram labelling, without changing its content in : Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc

There is no other changes. All tests passed.

@beaudett @fcouderc

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by archiron** [comment]
Hi, 
sorry to reopen the comments, but I don't see this PR in 10_0_X nor in 10_1_0_pre1 or 10_1_0_pre2 (https://github.com/cms-sw/cmssw/releases/CMSSW_10_1_0_pre2)

Is there a problem with it ?
Arnaud

**Comment by fabiocos** [comment]
https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_10/CMSSW_10_0_3.html

**Comment by archiron** [comment]
Hi, one more (last?) question : 
will the changes be included in the releases 10_1_0_preX ? Should I do a new PR ?
Thanks

**Comment by fabiocos** [comment]
@archiron this my fault, I overlooked the fact that this was not a back-port from the master as it should be. Normally this things should be spotted during the review @dmitrijus @jfernan2 .
#22526 is fixing this (in any case the change was really minor and not impacting physics results).

**Pull request merged**
