### PR TITLE
[Visualization] Replace fabs with std::abs to fix clang compilation warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all. Compilation log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_15_0_CLANG_X_2024-12-16-2300/Fireworks/Calo)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@cmsbuild please ignore tests-rejected with ib-failure

**Comment by iarspider** [comment]
please test for CMSSW_15_0_CLANG_X

**Comment by alja** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
