### PR TITLE
Phase2-hgx352BX Add an example of CMS scenario with only HGCal detector (backport #43841)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add an example of CMS scenario with only HGCal detector (backport #43841)

#### PR validation:

Tested with a configuration given in this PR

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43841

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@civanch @srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
backport of #43841

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
