### PR TITLE
Final global tags for 2017 UL reprocessing [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the global tags relevant for the 2017 UL reprocessing, as well as a fix for PPS conditions in prompt-like global tags. Both data and MC global tags are updated. It is a backport of PR #27342; further details can be found in that thread.

#### PR validation:

Please see the details in the thread for PR #27342.

#### if this PR is a backport please specify the original PR:

This is a backport of PR #27342.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #27342

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Trivial backport of #27342 
- Same pattern of changes in comparison tests as original PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
