### PR TITLE
backport of HLT Hbb filter for 74X

### PR DESCRIPTION
**Pull request by jmduarte**
Adding a Hbb invariant mass HLT filter in 74X needed for a SUSY HLT development for Run 2. Backport of 75X PR #9324 @sezata @duanders @sixie @vlimant

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by jmduarte** [comment]
Hi all,

Sorry for the additional changes. As recommended by @Dr15Jones and @davidlange6 in PR #9324, I undid the changes to the BuildFile, and moved the filter to the plugins directory. We also removed some unnecessary parameters and fixed the saving trigger objects statement. It's ready to be tested again.

Thanks,

Javier

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jmduarte** [comment]
Hi @davidlange6,

I understand this missed the latest ORP today, but I'm wondering what the timeline is for this backport to be merged (so I can align it with respect to a trigger proposal, HLT JIRA ticket submission etc.).

Thanks,

Javier

**Comment by davidlange6** [comment]
+1

**Pull request merged**
