### PR TITLE
modifications for Pixel online DQM config for HI run

### PR DESCRIPTION
**Pull request by threus**
Modifications for Pixel online DQM config for HI run.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
thanks @threus 
this seems to work fine. could you please submit to 76 and 80 as well?
thanks,
F.

**Comment by deguio** [comment]
approving, but don't forget to propagate to 76 and 80.
thanks,
F.

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
@deguio,  is this already running online?

**Comment by slava77** [comment]
@threus is there a PR in 80X?

**Comment by slava77** [comment]
merge

**Comment by deguio** [comment]
@slava77 yes, this runs online already, but I didn't see the corresponding PRs in 80 and 76 yet.
@threus

**Comment by threus** [comment]
@slava77 @deguio PRs for 76 & 80 done just now. Sorry I missed them.

**Pull request merged**
