### PR TITLE
Fixes after root-project/root#16443

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Cherry-picking of https://github.com/cms-sw/cmssw/pull/46079/commits/325c9e33c6a3642c2e0e72b09b836b2f92dbd59a by @guitargeek 

#### PR validation:

Bot tests in https://github.com/cms-sw/cmsdist/pull/9441

### CODE REVIEW

**Comment by guitargeek** [comment]
Thank you very much for this! This time, the update of the interface is 100 % intended and backwards compatible!

I will keep my previous PR open to revert the accidental interface changes when I have done this in ROOT.

**Comment by smuzaffar** [comment]
@iarspider , you meant https://github.com/root-project/root/pull/16443 ... right?

**Comment by smuzaffar** [comment]
code-checks with cms.week1.PR_4c49245c/100.0-8f48bd205455fb76d670172c98ada82d

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test

lets re-run based on latest IB

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/alca-l2 @cms-sw/db-l2 can you please review this?

**Comment by smuzaffar** [comment]
note that is PR is needed to integrate latest `ROOT master` changes (https://github.com/cms-sw/cmsdist/pull/9441)

**Comment by perrotta** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
