### PR TITLE
AJJGenJetFilter to filter photon+2jets events at GenLevel

### PR DESCRIPTION
**Pull request by hbakhshi**
#### PR description:

Here is the accepted PR in the master branch:
#35547

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

we need the [AJJGenJetFilter](https://github.com/hbakhshi/cmssw/blob/AJJGenJetFilter11X/GeneratorInterface/GenFilters/plugins/AJJGenJetFilter.cc) filter to produce some samples for the snowmass studies. the snowmass campaign is based on cmssw_11_0_x

### CODE REVIEW

**Comment by agrohsje** [comment]
please test

**Comment by perrotta** [comment]
backport of #35547

**Comment by perrotta** [comment]
@hbakhshi could you please modify the title in order to have it a bit more descriptive (for example starting from the same title as #35547)?

**Comment by hbakhshi** [comment]
@perrotta done, please let me know if it is not fine yet

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
please test workflow 1001.0, 1000.0, 140.53, 136.85, 136.8311, 136.7611, 136.731, 4.22

**Comment by hbakhshi** [comment]
Hello @SiewYan 
Thanks for triggering the tests. It seems that all the tests are passed. What would be the next step for it to get approved.

**Comment by SiewYan** [comment]
Hello, from my side it looks good.

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by Saptaparna** [comment]
@qliphy and @perrotta: do you have plans of releasing a new version of 11_X, so we can submit this Snowmass request?

**Comment by qliphy** [comment]
@Saptaparna   Yes, we will make a new 11_1_X.
We are waiting for https://github.com/cms-sw/cmssw/pull/35939

**Comment by hbakhshi** [comment]
Hi @qliphy and @perrotta. Any news regarding the new release? We need this filter very urgently for the sample production. Any help is really appreciated

**Comment by perrotta** [comment]
> Hi @qliphy and @perrotta. Any news regarding the new release? We need this filter very urgently for the sample production. Any help is really appreciated

#35939 is still wating for the requested updates to be implemented...

**Pull request merged**
