### PR TITLE
Fix sequences in HLT Upgrade simplified menu

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

This PR optimises the sequence-based HLT Upgrade Phase2 menu. Main ingredients:

* Remove full Tracking sequence from Muon paths that do not use it
* Remove `hltEcalUncalibRecHit` module as a duplicate of `ecalMultiFitUncalibRecHit`
* Optimally reorder filters in Egamma Paths by running full tracking at the very end, before the last filter that needs tracks.

#### PR validation:

Tested using HLT Upgrade Simplified menu.

With these changes, the timing as measured on my development machine went down quite a bit:

before
after

**Nota Bene:** For the timing measurements above, the Tau paths have been disabled temporarily because they were causing the triggering of full tracking on all events. This will likely be fixed once L1 seeding for Tau paths is introduced.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
It is our convention that at HLT, module labels start with lower case ```hlt`` and sequences start with uper case ```HLT```.

**Comment by rovere** [comment]
Ciao @ Martin-Grunewald You mention that already in my last PR.
Currently, I count 116 modules (and 41 sequences) in the Phase2 menu that do not follow this convention.

Would it make sense to have a dedicated PR to address this issue?

**Comment by Martin-Grunewald** [comment]
Sure - it does not have to be this PR.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
