### PR TITLE
Changes to store Daughters of Kshort and Lambda in the miniAOD prunedGenParticle Collection (backport to CMSSW_13_0_X)

### PR DESCRIPTION
**Pull request by gmelachr**
Following the pull request https://github.com/cms-sw/cmssw/pull/42464 and https://github.com/cms-sw/cmssw/pull/42498 this is a new PR to backport changes in CMSSW_13_0_X

### CODE REVIEW

**Comment by simonepigazzini** [comment]
please test

**Comment by perrotta** [comment]
backport of #42464

**Comment by mandrenguyen** [comment]
+1

**Comment by simonepigazzini** [comment]
+1

**Pull request merged**
