### PR TITLE
Hcal_Alca_GammaJet+IsoTrack_DiJets_for_Run2

### PR DESCRIPTION
**Pull request by zhokin2**
updates of Hcal-Alca for Gamma-Jet and IsoTrack from Sunanda, Di-Jets from David, one test file from Natalia on base mainly of 3 branches:
bsunanda:Run2-HcalGammaJet01
bsunanda:Run2-HcalIsoTrack-ana01
davidsheffield:from-CMSSW_7_4_0_pre1

### CODE REVIEW

**Comment by slava77** [comment]
should we close #7475 if this includes the other one.

Please provide a more descriptive documentation

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
Please give this PR a good title and add some description of the changes. Thanks.

**Comment by zhokin2** [comment]
#7468 and #7475 PRs are to closed

**Comment by zhokin2** [comment]
additional corrections on shared files of merged branches (names SealModule
and BuildFile) were made

**Comment by slava77** [comment]
-1

broken and is apparently superseded by #7523

**Comment by zhokin2** [comment]
OK, I just closed this PR.

**Pull request closed without merging**
