### PR TITLE
Fix reco muon validation hlt

### PR DESCRIPTION
**Pull request by abbiendi**
Bug fixes to be applied on master 12_0_X, solve the issue of PR #33610
This should change nothing anywhere comparing with master (where applicable)
the workflows like 1311.0 could be checked by testing #33610 together with this PR

The problem was caused by events where some HLT muon track collections are missing, while trying to access them.

### CODE REVIEW

**Comment by qliphy** [comment]
type bugfix

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
