### PR TITLE
Run3-gex47 Help cpmparison of geometries created by DDD/DD4Hep with PrintGeomInfo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Help cpmparison of geometries created by DDD/DD4Hep with PrintGeomInfo

#### PR validation:

Use the modifications to identify discrepancies between DDD and DD4Hep created geometries

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
@silviodonato @smuzaffar @civanch I think the failures are not due to this PR. Could you please check?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
this is not only this PR which fail data test.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

changes expected; failed WF is due to files absence not this PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
