### PR TITLE
Use unique_ptr, not auto_ptr, in Analysis

### PR DESCRIPTION
**Pull request by wmtan**
The last use of the deprecated std::auto_ptr in the CMS framework is the "put" interface for EDProducts, which also supports std::unique:ptr. This PR changes all put calls in most Analysis packages to use std::unique_ptr instead of std::auto_ptr. Some other instances of std::auto_ptr in Analysis may also have been changed to std::unique_ptr.
Not all Analysis packages are converted in this PR due to dependency issues. The remaining Analysis packages will be converted at a later time.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #14714 8784e2fcd74ab17248660b612f815189bee8afb5

Migration to replace deprecated auto_ptr with unique_ptr in analysis code. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-05-31-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
@wmtan - could you rebase this
thanks

**Comment by wmtan** [comment]
@davidlange6 This PR has been rebased at the request of David Lange

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Comparisons got stuck in the Queued state

**Comment by cvuosalo** [comment]
+1

For #14714 24c77f7b29b11e85078653f9523ebf443160d348

Second approval, after a rebase. New Jenkins tests are still OK.

**Pull request merged**
