### PR TITLE
2023 Scenarios Unit Test Fix

### PR DESCRIPTION
**Pull request by ianna**
- Replace obsolete 2023 scenarios with the new ones

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@smuzaffar and @davidlange6 - please, take this PR to fix the unit test in IB

**Comment by smuzaffar** [comment]
thanks Ianna

**Pull request merged**
