### PR TITLE
[12_3_X] [L1-O2O] ESGetToken migration L1CondDBPayloadWriter and O2O unit tests

### PR DESCRIPTION
**Pull request by panoskatsoulis**
backport #37602 

#### PR description:

This PR implements `WriterProxy` from `CondTools/L1TriggerExt` to inherit from `edm::EDConsumerBase` as it's required for running `esConsumes()` to register `ESGetToken` objects when is called by CondDBPayloadWriter

#### PR validation:

This pkg is part of the L1 O2O and there is not any central wf to be tested 
Tested Locally and from custom patch on machine `conddb-1` writing to sqlite file and Prep respectively 
The local replica of the p5 script is commited together in this PR ( `runL1-O2O-iov.sh` )

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
backport of #37602

### CODE REVIEW

**Comment by panoskatsoulis** [comment]
hold

**Comment by tvami** [comment]
Hi @panoskatsoulis thanks for this PR!
1) can you please include the the title that this is for [12_3_X]
2) What's the reason for the hold?
3) Please add the L1TriggerConfig/L1TConfigProducers/test/runL1-O2O-iov.sh to the BuildFile so it's run like a unit test! Thanks!

**Comment by panoskatsoulis** [comment]
2. have a look here
https://github.com/cms-sw/cmssw/pull/37602#issuecomment-1100914269
3.
it needs some local sqlite that will be able to use locally, in short I don't know how to set up a new unit test
so it's better to come back for this in the next days

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
so, the O2O tests failed:
```
----- Begin Fatal Exception 22-Apr-2022 21:51:59 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing service of type PoolDBOutputService
Exception Message:
A std::exception was thrown.
Connection on "sqlite_file:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-04-22-1100/src/L1TriggerConfig/L1TConfigProducers/data/l1config.db" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 22-Apr-2022 21:51:59 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing service of type PoolDBOutputService
Exception Message:
A std::exception was thrown.
Connection on "sqlite_file:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-04-22-1100/src/L1TriggerConfig/L1TConfigProducers/data/l1config.db" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
----- End Fatal Exception -------------------------------------------------
```

I guess because the local sqlite file was not included in this PR (as instead it has been done in the [master PR](https://github.com/cms-sw/cmssw/pull/37602/files#diff-181695dc2ac26700ac36d3c3a2f06b79db7efe12bfc63f4ed68fd2774797148c ))

**Comment by panoskatsoulis** [comment]
> so, the O2O tests failed:
> 
> ```
> ----- Begin Fatal Exception 22-Apr-2022 21:51:59 CEST-----------------------
> An exception of category 'StdException' occurred while
>    [0] Constructing the EventProcessor
>    [1] Constructing service of type PoolDBOutputService
> Exception Message:
> A std::exception was thrown.
> Connection on "sqlite_file:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-04-22-1100/src/L1TriggerConfig/L1TConfigProducers/data/l1config.db" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
> ----- End Fatal Exception -------------------------------------------------
> ----- Begin Fatal Exception 22-Apr-2022 21:51:59 CEST-----------------------
> An exception of category 'StdException' occurred while
>    [0] Constructing the EventProcessor
>    [1] Constructing service of type PoolDBOutputService
> Exception Message:
> A std::exception was thrown.
> Connection on "sqlite_file:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-04-22-1100/src/L1TriggerConfig/L1TConfigProducers/data/l1config.db" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
> ----- End Fatal Exception -------------------------------------------------
> ```
> 
> I guess because the local sqlite file was not included in this PR (as instead it has been done in the [master PR](https://github.com/cms-sw/cmssw/pull/37602/files#diff-181695dc2ac26700ac36d3c3a2f06b79db7efe12bfc63f4ed68fd2774797148c))

No, this is because of the missing commit with the sqlite file here
the test result are meant to be done here once we have the data repo
for which I opened this PR https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/1

**Comment by mmusich** [comment]
> > guess because the local sqlite file was not included in this PR (as instead it has been done in the [master PR](https://github.com/cms-sw/cmssw/pull/37602/files#diff-181695dc2ac26700ac36d3c3a2f06b79db7efe12bfc63f4ed68fd2774797148c))

> No, this is because of the missing commit with the sqlite file here

I think we are saying the same thing :)

**Comment by panoskatsoulis** [comment]
ah, there was more under the error, yes

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/1

**Comment by panoskatsoulis** [comment]
the test with the externals is gonna fail because of the same reason https://github.com/cms-sw/cmssw/pull/37602#issuecomment-1107577958

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/1

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
```
----- Begin Fatal Exception 24-Apr-2022 16:12:37 CEST-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESProducer: class=L1SubsystemKeysOnlineProdExt label='L1SubsystemKeysOnlineExt'
Exception Message:
Connection to "oracle://cms_omds_adg/cms_trg_r" with role "COND_READER_ROLE" is not available for IB from cond::RelationalAuthenticationService::RelationalAuthenticationService::credentials 
----- End Fatal Exception -------------------------------------------------
```

**Comment by panoskatsoulis** [comment]
> 

check here https://github.com/cms-sw/cmssw/pull/37602#issuecomment-1107914507 @tvami, seems like either a key issue or an issue with the target db.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@panoskatsoulis please update the PR title for this too, thanks!

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * newly introduced unit tests are passing: 
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-70faf5/24240/unitTests/src/L1TriggerConfig/L1TConfigProducers/test/L1O2O_L1TMenu/testing.log
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-70faf5/24240/unitTests/src/L1TriggerConfig/L1TConfigProducers/test/L1O2O_L1TSubs/testing.log

**Comment by epalencia** [comment]
+l1

**Comment by panoskatsoulis** [comment]
@perrotta @qliphy
this is the P5 backport of #37602 
it's also required to be merged

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/37602, successfully merged in IB since CMSSW_12_4_X_2022-04-27-1100
- cms-data externals already available in 12_3 via https://github.com/cms-sw/cmsdist/pull/7825

**Pull request merged**
