### PR TITLE
Limit dependency on CGAL library to RecoHI/HiJetAlgos plugin

### PR DESCRIPTION
**Pull request by Dr15Jones**
The CGAL library causes problems with valgrind therefore we want to
limit its exposure. Moving the dependency out of RecoHI/HiJetAlgos
avoids having other libraries with link to that one having unneeded
dependencies to CGAL. The only module which actually needs to link
to CGAL is VoronoiBackgroundProducer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This should allow valgrind to function again for non HI jobs.

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
I was able to successfully run with valgrind after this change.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #8215 dc8d983244612d61f0ce6ac47ef4735e631df2e3

This PR makes changes in compiling and linking to reduce dependence on the CGAL library. It should not affect program outputs or physics quantities.

The Jenkins tests are OK and show no differences from the baseline.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
