### PR TITLE
Revert "Workaround to produce exactly same data products in Serial and CUDA backends in Alpaka modules possibly used at HLT"

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Reverts cms-sw/cmssw#44698, to be used in conjunction with https://github.com/cms-sw/cmssw/pull/44892

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_0_X

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca
- As discussed during the ORP meeting of May 28, to allow merging https://github.com/cms-sw/cmssw/pull/44892

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Comment by rappoccio** [comment]
Skipping tests and bypassing signatures.

**Comment by fwyzard** [comment]
+heterogeneous

**Pull request merged**
