### PR TITLE
Run3-gex51 Use the modified tob.xml in Run3 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use the modified tob.xml in the Run3 scenario and also reorder some of the xml's for ECAL

#### PR validation:

Tested using private cfg's in SimG4Core/Configuration/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@srimanob, this PR is important for Run-3 and DD4Hep migration, please, review

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
