### PR TITLE
[DQM/TrackerRemapper] add unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to provide catch2 unit test for the classes in the package `DQM/TrackerRemapper` 
Additionally some technical commits are added:
   * refactor code of `Phase1PixelMaps` to check if histograms are booked (ce77cf9 )
   * merge `bookBarrelBins` and `bookForwardBins` with` bookBarrelHistograms` and `bookForwardHistograms` respectively, and propagate it to dependencies (ae32d30)
   * add checks in `Phase1PixelMaps` about the histograms being booked (2b8b5bb )

#### PR validation:

Run the augmented unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by yuanchao** [comment]
+1
* compiles ok, unit tests run

**Comment by qliphy** [comment]
ping @cms-sw/db-l2

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
