### PR TITLE
[14_0_X] Backport of 44970 and 45820 (ScoutingNano event content changes for 2024 and T0 scenario for HLTSCOUT datatier)

### PR DESCRIPTION
**Pull request by patinkaew**
#### PR description:

Backport to 14_0_X of
- https://github.com/cms-sw/cmssw/pull/44970
- https://github.com/cms-sw/cmssw/pull/45820
to actual data-taking release (14_0_X) to allow T0 production tests with 14_0_X and actual T0 production if tests succeed.

Details:
- Change ScoutingNano event content from [#45820](https://github.com/cms-sw/cmssw/pull/45820) since the changes to add ScoutingMuonNoVtx and ScoutingMuonVtx from [#44970](https://github.com/cms-sw/cmssw/pull/44970) are also propagated to [#45820](https://github.com/cms-sw/cmssw/pull/45820). 
- Add ```run3_scouting_nanoAOD_post2023``` to ```Era_Run3_2024```.
- Add T0 processing scenarios for processing HLTSCOUT datatier as input```hltScouting```, ```hltScoutingEra_Run3_2024``` from [#44970](https://github.com/cms-sw/cmssw/pull/44970).
- Add  ```hltScoutingEra_Run3_2024``` scenario to unit test ```run_CfgTest_8.sh``` and add new unit test ```run_CfgTest_13.sh``` specific for ```hltScouting``` scenarios from [#44970](https://github.com/cms-sw/cmssw/pull/44970).
- Add workflow 2500.6 to relval_nano. Since [#45419](https://github.com/cms-sw/cmssw/pull/45419) won't be backported to 14_0_X, only necessary information for workflow ```ScoutingNANOdata140Xrun3``` is added. The input file and lumisection range are the same as in [#45419](https://github.com/cms-sw/cmssw/pull/45419). The names are the same as in [#45419](https://github.com/cms-sw/cmssw/pull/45419) for ```NANO_data14.0```, ```ScoutingPFRun32024RAW14.0```, ```ScoutingNANOdata140Xrun3```, except ```NANO_dataRun3ScoutingPF14.0``` which corresponds to ```scoutingNANO_data14.0``` in [#45419](https://github.com/cms-sw/cmssw/pull/45419). This is to keep a convention used in 14_0_X release.

Event size is measured with relval_nano matrix. These are default ScoutingNano with only scouting objects and without standard offline objects and without gen info (for mc).
- 0.88 kB/event (2500.5 ScoutingNANOdata13X)
- 2.07 kB/event (2500.51 ScoutingNANOmc13X)
- 1.14 kB/event (2500.6 ScoutingNANOdata140Xrun3)

Workflow 2500.5 is similar to 2500.131 and 2500.6 is similar to 2500.237 after [#45419](https://github.com/cms-sw/cmssw/pull/45419), so measured event sizes are the same. 2500.51 uses TTBarMINIAOD13.3 while 2500.227 after [#45419](https://github.com/cms-sw/cmssw/pull/45419) uses TTbarMINIAOD14.0, so measured event sizes are slightly different.

Size reports (root files used and size report html files) can be found in [09.07.2024_ScoutingNano_size_reports](https://indico.cern.ch/event/1441452/#4-scouting-nano-updates-and-pr).

Note: another related PR is [#45949](https://github.com/cms-sw/cmssw/pull/45949) which is a backport of [#45820](https://github.com/cms-sw/cmssw/pull/45820) to 14_1_X to ensure that the event content changes are consistent in subsequent releases across 14_0_X, 14_1_X, and 14_2_X.

#### PR validation:

Pass all standard unit tests from ```scram b runtests``` when running on ```el8_amd64_gcc12```:
```
Pass    2s ... Configuration/DataProcessing/TestConfigDP_1
Pass   10s ... Configuration/DataProcessing/TestConfigDP_10
Pass   11s ... Configuration/DataProcessing/TestConfigDP_11
Pass  129s ... Configuration/DataProcessing/TestConfigDP_12
Pass    1s ... Configuration/DataProcessing/TestConfigDP_13
Pass  115s ... Configuration/DataProcessing/TestConfigDP_2
Pass   22s ... Configuration/DataProcessing/TestConfigDP_3
Pass   27s ... Configuration/DataProcessing/TestConfigDP_4
Pass  245s ... Configuration/DataProcessing/TestConfigDP_5
Pass   85s ... Configuration/DataProcessing/TestConfigDP_6
Pass  140s ... Configuration/DataProcessing/TestConfigDP_7
Pass  371s ... Configuration/DataProcessing/TestConfigDP_8
Pass   10s ... Configuration/DataProcessing/TestConfigDP_9
Pass    2s ... Configuration/PyReleaseValidation/test-das-selected-lumis
Pass  242s ... Configuration/PyReleaseValidation/test-runTheMatrix-interactive
Pass  268s ... Configuration/PyReleaseValidation/test_MC_22_crosscheck
Pass  218s ... Configuration/PyReleaseValidation/test_MC_22_setup
Pass  293s ... Configuration/PyReleaseValidation/test_MC_23_crosscheck
Pass  328s ... Configuration/PyReleaseValidation/test_MC_23_setup
```
when running on ```el9_amd64_gcc12```, pass all unit tests from ```scram b runtests``` except:
```
Fail  209s ... Configuration/PyReleaseValidation/test_MC_23_setup
```
This unit test failure on ```el9_amd64_gcc12``` seems to relate to https://github.com/cms-sw/cmssw/pull/45614.

Next following tests are all done on ```el8_amd64_gcc12```.

Pass all tests from ```runTheMatrix.py -l limited -i all --ibeos```
```
47 46 45 36 19 1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed
```

Other tests:
- ```RunPromptReco.py``` example. The outputs look reasonable:
```
python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario=hltScoutingEra_Run3_2024 \
--global-tag=140X_dataRun3_Prompt_v4 --nanoaod --nanoFlavours=@Scout --lfn=fileIN.root

python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario=hltScoutingEra_Run3_2024 \
--global-tag=140X_dataRun3_Prompt_v4 --nanoaod --miniaod --nanoFlavours=@Scout --lfn=fileIN.root
```
- ```runTheMatrix.py --ibeos -l 2500.6``` (added ScoutingNano workflow) passes and the output nano file looks reasonable
- ```cmsDriver.py``` example. The output looks reasonable:
```
cmsDriver.py step2 -s NANO:@Scout --process NANO \
--data --eventcontent NANOAOD --datatier NANOAOD -n 1000 \
--era Run3_2024 --conditions 140X_dataRun3_Prompt_v4 --filein fileIN.root
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Original PRs are [#44970](https://github.com/cms-sw/cmssw/pull/44970) and [#45820](https://github.com/cms-sw/cmssw/pull/45820). This is a backport to 14_0_X.

FYI: @elfontan @silviodonato

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by patinkaew** [comment]
Hi all,

The latest commit fixed the conflict with https://github.com/cms-sw/cmssw/pull/45850 which was just merged.

**Comment by hqucms** [comment]
please test

**Comment by silviodonato** [comment]
Only @cms-sw/operations-l2  signature is missing

**Comment by silviodonato** [comment]
@cms-sw/operations-l2 do you see any issues on this backport?

**Comment by mandrenguyen** [comment]
backport of #44970
 and #45820

**Pull request merged**
