### PR TITLE
[Backport] Fix for proper separation of the ZDCP and ZDCM triggers in the uGT

### PR DESCRIPTION
**Pull request by elfontan**
#### PR description:
Bug fix related to the uGT emulator changes for ZDC triggers (https://github.com/cms-sw/cmssw/pull/42634, 132X backport: https://github.com/cms-sw/cmssw/pull/42706) in view of the 2023 HI data-taking. Backport of https://github.com/cms-sw/cmssw/pull/42778 for the 2023 HI data-taking.

#### PR validation:
The PR has been prepared starting from CMSSW_13_2_X_2023-09-13-1100:
```
cmsrel CMSSW_13_2_X_2023-09-13-1100
cd CMSSW_13_2_X_2023-09-13-1100/src
cmsenv
git cms-init
git cms-addpkg L1Trigger/L1TGlobal
scram b && scram b code-checks && scram b code-format && scram b
```

[cc: @hjbossi @cfmcginn @ginnocen @icali]

### CODE REVIEW

**Comment by aloeliger** [comment]
urgent

**Comment by aloeliger** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42778

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
