### PR TITLE
Phase2-hcx210 Make validation tools for HFNose RecHits

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make validation tools for RecHits created for HFNose

#### PR validation:

Tested with 3 workflows: 20034.0, 24034.0 and 29034.0. Also ran 26234.0 and ran on the step3.root

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
@bsunanda the code is creating the tools for HGCAL validation but they have not been enabled yet in DQM, hence no real Validation plots have been produced in the Phase2 workflows.

Can you confirm this is the intention so far?
Thanks

**Comment by bsunanda** [comment]
@jfernan2 HFNose detector is not yet in a standard workflow - it is in a special workflow for upgrade. So no attempt is made to make these to appear in DQM plots. Once we establish it in standard Phase2 workflows, we shall add that.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda ok, but how was this new code checked? The proposed test configuration does nto seem to run the nose specific part, am I correct?

**Comment by bsunanda** [comment]
@fabiocos Yes I checked it by generating receipt using #27129 and using the generated SimHit/Digi/RecHit privately using the existing scenario D31

**Comment by bsunanda** [comment]
@fabiocos Please integrate this.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
