### PR TITLE
Update trigger filter bits in CMSSW - backport to 13_0

### PR DESCRIPTION
**Pull request by mstamenk**
Backport from https://github.com/cms-sw/cmssw/pull/41692/commits

@simonepigazzini

### CODE REVIEW

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
verbatim backport https://github.com/cms-sw/cmssw/pull/41692

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41692

**Comment by perrotta** [comment]
@mstamenk did you also prepare the backport for 13_1_X?
If not, please do so, if you want to backport in the older 13_0_X, as here

**Comment by mstamenk** [comment]
Hi @perrotta , I did, here the PR: https://github.com/cms-sw/cmssw/pull/41985#issuecomment-1594255676

**Comment by vlimant** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
