### PR TITLE
IPProducer update

### PR DESCRIPTION
**Pull request by ferencek**
Minor updates to the IPProducer. Changes should be transparent to the RECO output.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #8217 195d4d7c4cec08e4e4e86d3412b813c6fefa1b02

Minor code clean-up that should not have an effect on reco physics quantities. Code changes are satisfactory, and Jenkins tests against baseline [CMSSW_7_4_X_2015-03-12-1400] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8217/2794/summary.html) show no significant differences.

**Comment by cvuosalo** [comment]
Note that the static analyzer complains about the three "using namespace" statements in file IPProducer.h. There probably shouldn't be such statements in a header file. No change is necessary in this PR, but a future PR for 75X that fixes these complaints might be a good idea.

**Comment by davidlange6** [comment]
+1
(but with the same comment as @cvuosalo )

**Comment by ferencek** [comment]
This header file defines a templated EDProducer so it is not likely to be included in other places in the code. However, the fix should be simple enough. Do you want me to update this PR or should we leave this for 7_5_X?

**Comment by ferencek** [comment]
OK, since already merged, I will fix this for 7_5_X.

**Comment by ferencek** [comment]
Since this PR was already propagated to 7_5_X, I decided to add the `using namespace` fix to 7_4_X first.

**Pull request merged**
