### PR TITLE
Removed use of CLHEP::HepMatrix::determinant

### PR DESCRIPTION
**Pull request by Dr15Jones**
The determinant calculation of CLHEP::HepMatrix is not thread safe
since it uses a global memory cache. Switching to SMatrix solve the
problem. One complication is HeMatrix starts counting at 1 while
SMatrix starts at 0.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I did test running workflow 14.0 with this change and it succeeded. It was on workflow 14.0 which helgrind found the problem originally.

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
Starting matrix tests since Jenkins doesn't seem to be giving any results.

**Comment by cvuosalo** [comment]
In file SETFilter.cc, on lines 616-619, the static analyzer notes that the "newPhi" variable is calculated but never used:

double newPhi = result_phi.first;
if(fabs(newPhi - phi)<0.02){// too close?
newPhi = phi + 0.02;
}

Looking at the code, I wonder whether newPhi should be used in place of "result_phi.first". If it really isn't needed, it should be deleted. This issue could be addressed in this PR or a later one.

**Comment by cvuosalo** [comment]
+1

For #8318 57ef14daf633aa25b9557533dda7e361e10a19d0

This PR replaces use of non-thread-safe CLHEP::HepMatrix with a thread-safe matrix class. The new class should duplicate the old functionality, so there should be no change in reco outputs.

The code change is satisfactory, as are the Jenkins test results. Short matrix tests against baseline CMSSW_7_4_X_2015-03-15-0200 show no significant differences, as expected.

**Comment by cvuosalo** [comment]
+1

Trying again to approve. Maybe the bot will notice this time.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
