### PR TITLE
NanoAODv6 updates [102X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport #28122 

#### PR description:

This pull request is the backport to 10_2_X of the updates for the NanoAODv6 campaign.
It's a **cumulative backport** of #28103 and #28122.
Depends on #28095 and #28135.

#### PR validation:

Usual validation in the cms-nanoAOD integration repository.

### CODE REVIEW

**Comment by peruzzim** [comment]
This depends on other pull requests that are not yet merged in 102X, as written in the description. I had not requested tests because of the network issues at CERN this morning. Now I see 28135 (one of the dependencies) is being tested, I don't know if you can start a test now.

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28095,#28135

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28095,#28135

**Comment by perrotta** [comment]
> +xpog
> 
> I don't understand what the "failed comparisons" refer to in the integration setup, can someone with more know-how of the system please check those?
> It runs and differences are shown only in the nanoAOD products, the same branch has been tested extensively in the integration setup, so I sign - but please check the above before merging.

"Failed comparisons" means comparisons that show any difference wrt baseline.
As far as I can see, those differences here are only in the nanoAOD: if you approve them, that's fine.

**Comment by slava77** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

@peruzzim perhaps you already know if this will fail.
I'm trying to understand if this PR can stand by itself.

**Comment by slava77** [comment]
please abort test

**Comment by peruzzim** [comment]
@slava77 it's going to crash without the dependencies

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28145	9547ba3 
- changes in the reco category are only in RecoTauTag/RecoTau/python/tools/runTauIdMVA.py to allow extending the embedded tau IDs in ```slimmedTaus``` for analysis/nanoAOD workflows.  This change is a backport of https://github.com/cms-sw/cmssw/pull/27397	(as of 66a1a43), which was merged to the master branch on July 1.
- jenkins tests pass

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28095,#28135

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28095,#28135

**Comment by fabiocos** [comment]
+1

**Pull request merged**
