### PR TITLE
[81X] Update Hcal tags for SiPM characteristics in Run1/2 MC and data and several fixes in 2017 hcal conditions

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunI simulation
- **RunI Ideal scenario** : [81X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v4) as [81X_mcRun1_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_design_v4/81X_mcRun1_design_v3): 
  - updated `HcalSiPMCharacteristics` in HO
- **RunI Heavy Ions scenario** : [81X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v4) as [81X_mcRun1_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_HeavyIon_v4/81X_mcRun1_HeavyIon_v3): 
  - updated `HcalSiPMCharacteristics` in HO
- **RunI Realistic scenario** : [81X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v4) as [81X_mcRun1_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_realistic_v4/81X_mcRun1_realistic_v3): 
  - updated `HcalSiPMCharacteristics` in HO
- **RunI Proton-Lead scenario** : [81X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v4) as [81X_mcRun1_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_pA_v4/81X_mcRun1_pA_v3): 
  - updated `HcalSiPMCharacteristics` in HO
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v9) as [81X_mcRun2_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v9/81X_mcRun2_design_v8): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v10) as [81X_mcRun2_asymptotic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v10/81X_mcRun2_asymptotic_v9): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII Startup scenario** : [81X_mcRun2_startup_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v11) as [81X_mcRun2_startup_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v11/81X_mcRun2_startup_v10): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII Proton-Lead scenario** : [81X_mcRun2_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v4) as [81X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_pA_v4/81X_mcRun2_pA_v3): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v9) as [81X_mcRun2cosmics_startup_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v9/81X_mcRun2cosmics_startup_peak_v8): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v10) as [81X_mcRun2_HeavyIon_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v10/81X_mcRun2_HeavyIon_v9): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
## RunII data
- **RunII Offline processing** : [81X_dataRun2_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v9) as [81X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v9/81X_dataRun2_v8): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
  - update SiStripDQM TriggerBit selection for Heavy Ion data
- **RunII HLTHI processing** : [81X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v3) as [81X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLTHI_frozen_v3/81X_dataRun2_HLTHI_frozen_v2): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v5) as [81X_dataRun2_HLT_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v5/81X_dataRun2_HLT_relval_v4): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII HLT processing** : [81X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v3) as [81X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_frozen_v3/81X_dataRun2_HLT_frozen_v2): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
- **RunII Offline relval processing** : [81X_dataRun2_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v11) as [81X_dataRun2_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v11/81X_dataRun2_relval_v10): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO
  - update SiStripDQM TriggerBit selection for Heavy Ion data
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v17) as [81X_upgrade2017_realistic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v16) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v17/81X_upgrade2017_realistic_v16): 
  - update L1 menu to be in synch with 2016 queues 
  - updated SiPM characteristics in HO 
  - updated Hcal LUTs for bug fixes 
  - updated Hcal Pedestals: fixes for HB/HO from ADC counts to fC 
  - reduced HcalRespCorr for depth1 in HE by factor 0.5/1.2 = 0.417
- **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v1) as [81X_upgrade2017_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v1/81X_upgrade2017_design_IdealBS_v0): 
  -  updated SiPM characteristics in HO 
  - updated Hcal LUTs for bug fixes 
  - updated Hcal Pedestals: fixes for HB/HO from ADC counts to fC 
  - reduced HcalRespCorr for depth1 in HE by factor 0.5/1.2 = 0.417
- **PhaseII realistic scenario** : [81X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2023_realistic_v2) as [81X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2023_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2023_realistic_v2/81X_upgrade2023_realistic_v1): 
  - updated `HcalSiPMCharacteristics` in HO
  - updated `HcalSiPMParameters` in HO

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
```
%MSG
19-Oct-2016 16:08:30 CEST  Closed file file:step2.root
----- Begin Fatal Exception 19-Oct-2016 16:08:30 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```
doesn't seem to be related to this PR

**Comment by mmusich** [comment]
please test

**Comment by ianna** [comment]
@mmusich - please, include updated tags for 2017 queues. It will allow to switch from xml geometry to DB one.

Note, an update here to DB:Extended is needed:
http://cmslxr.fnal.gov/source/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#0064

**Comment by mmusich** [comment]
@ianna, at next iteration.
What are the correct tags to be picked up for the tracker?
I cannot switch on the geometry from DB until we get the alignment correct.

**Comment by ianna** [comment]
@mmusich - thanks.

```
 Tag: XMLFILE_Geometry_81YV11_Extended2017_mc
 Record: GeometryFileRcd
 Label: Extended

 Tag: TKExtra_Geometry_81YV11
 Record: PGeometricDetExtraRcd

 Tag: TKRECO_Geometry_81YV11
 Record: IdealGeometryRecord

 Tag: HCALRECO_Geometry_81YV11
 Record: PHcalRcd
```

This fixes the problem with mixing vector content in an Hcal reco schema (relevant code changes are already in pre13) and aligns sim geometry and Tracker reco geometry to a current one built from xml. 

Note, there are some more Tracker changes (material related) expected in a week time.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
As expected no changes in any run1/run2 data or mc workflows until https://github.com/cms-sw/cmssw/pull/16070 is merged. 
Expected changes in the 2017 simulation: [relmon](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-19-1100+16266/16464/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/)

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
