### PR TITLE
Update GEM Offline DQM

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
* Regarding `GEMEfficiencyAnalyzer`,
  * Update the way to propagate muons into GEM layers because the existing way is not decent to cosmics scenario. 
  * Combine plots for odd/even chambers into one for reducing memory usage.
  * Update the way to book `MonitorElement`s. Remove `BookingHelper`, which is the wrapper of `IBooker`. Use `GEMDetId` as a key of `MEMap` rather than tuple of int numbers.
  * Create cfi files for comics scenario.
* Exclude `GEMOfflineMonitor` from GEM offline DQM sequence. `GEMOfflineMonitor` creates only `GEMDigi` and `GEMRecHit` occupancy plots but these plots are moved to the online DQM. However, `GEMOfflineMonitor` is not removed because it will make more diverse plots (mainly `GEMSegment`) in the near future.

Here is a link to [slides](https://indico.cern.ch/event/1010727/contributions/4241619/attachments/2199578/3719850/200226-OfflineDQMUpdate.pdf)

#### PR validation:
The offline DQM GUI server is running at the local server. [Link to DQM GUI](http://offlinedqm.sscc.uos.ac.kr:50200/dqm/offline/session/oUsaUn).
Please check out the manual of GUI at the last page of the [slides](https://indico.cern.ch/event/1010727/contributions/4241619/attachments/2199578/3719850/200226-OfflineDQMUpdate.pdf)

This PR is tested with two workflows:
* For pp, `runTheMatrix.py -w upgrade -l 12411.0`, which is `TenMuExtendedE_0_200+2023`.
* For comics, I used custom [UndergroundCosmicMu_cfi without magnetic field](https://gist.github.com/seungjin-yang/307384bbf301391788abf2ac21c089fb), whose result is shown in GUI.

@jshlee, @szaleski

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by seungjin-yang** [comment]
The variable name change was incomplete. The new commit fixed it and is tested with workflow `34611.0`, which is `TenMuExtendedE_0_200+2026D76`.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@seungjin-yang plots look fine but all are empty, I guess ue to stats of the Jenkins test samples

**Comment by seungjin-yang** [comment]
> @seungjin-yang plots look fine but all are empty, I guess ue to stats of the Jenkins test samples

Yes, GEM detectors cover the high eta region. Neither TTBar nor ZMM will produce a sufficient number of muons flying into the high eta region. So, I have generated muon gun samples with the GEM eta coverage option and a lot of cosmic muons. What should I do?

**Comment by jfernan2** [comment]
No problem @seungjin-yang your validation plots show enough stats

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
