### PR TITLE
color reconnection variations

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan of course this PR test has just shown that the python has a correct syntax, nothing, else. The validation of these fragments has been done elsewhere I assume, anyway here they cannot break anything.

**Comment by fabiocos** [comment]
+1

**Comment by efeyazgan** [comment]
@fabiocos yes, they can't break anything here. Physics validation is described in paper GEN-17-002.

**Pull request merged**
