### PR TITLE
Update of DQM combo PR for L1T, including updates from 81x

### PR DESCRIPTION
**Pull request by mulhearn**
This is intended to supercede #13763.

Now that PR #13767 it is only 60 files.

It also includes some updates from 81X after the corresponding tgs-v4 and DQM PRs which addressed problems with the IB.  With these changes, L1Trigger, DataFormats/L1TMuon, and EventFilter/L1TRawToDigi are identical with CMSSW_8_1_0_pre2.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by nsmith-** [comment]
FYI @mulhearn the DQM/L1TMonitor files that you synced were changed by this 81X PR: https://github.com/cms-sw/cmssw/pull/13691
I guess it never got a backport

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
