### PR TITLE
Add missing newlines in DataFormats modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
DataFormats/Common
DataFormats/HcalCalibObjects
DataFormats/HepMCCandidate
DataFormats/L1Scouting
DataFormats/L1ScoutingRawData
DataFormats/L1TCalorimeterPhase2
DataFormats/L1TrackTrigger
DataFormats/L1Trigger
DataFormats/OnlineMetaData
DataFormats/Portable
DataFormats/PortableTestObjects
DataFormats/SiPixelClusterSoA
DataFormats/SoATemplate
DataFormats/TestObjects
DataFormats/TrackingRecHitSoA
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, whitespace-only changes.

**Comment by makortel** [comment]
+core

**Comment by smorovic** [comment]
+daq

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by makortel** [comment]
+heterogeneous

**Comment by menglu21** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
