### PR TITLE
Phase I: new BPIX module cable materials, new FPIX portcard material and dimensions

### PR DESCRIPTION
**Pull request by friccita**
Modifications to Phase I Pixel geometry/material description:
- BPIX: new module cable materials (one for L1, one for L2-L4)
- FPIX: new portcard material, new temporary dimensions (to be possibly modified in later iteration of geometry description refinement, after receiving feedback from FNAL engineers)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by makortel** [comment]
For my education, could somebody clarify if these changes impact reco geometry and/or alignment, or only passive material is added/changed? Or, in other words, can one run GEN-SIM + DIGI-RECO consistently with this PR alone? I guess using GEN-SIM from 810pre6 or earlier (i.e. essentially `runTheMatrix.py -i all - l 10024.0`) should continue to work as before with this PR.

**Comment by friccita** [comment]
@makortel These changes don't  affect reco geometry or alignment; only passive materials were modified.

**Comment by makortel** [comment]
Thanks @friccita.

**Comment by ghellwig** [comment]
@friccita Is the information you are providing here relevant to create [MediumProperty](https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/DataFormats/GeometrySurface/interface/MediumProperties.h) objects?

**Comment by friccita** [comment]
@ghellwig I am not familiar with MediumProperty objects; are they derived somehow from the material definitions in xml files?

**Comment by ghellwig** [comment]
@friccita this is actually, what I wanted to know, too ;)
I recently ran into some problems because this object had no values set for the phase1-FPIX.
See also this [HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3331/1/1/2/1/1/1/1/1/1/1.html).

**Comment by friccita** [comment]
@ghellwig For me, it's the first time that I've heard of MediumProperty objects... From poking around in the code on Git, I gather that these objects are defined using a radiation length and hadronic interaction length. The material definitions in the Detector Description (DD) do not include any information about radiation lengths or hadronic interaction lengths, as those are calculated by GEANT during simulation using only elemental composition info provided in the xml material definitions. I have defined new materials similarly in the past for the 2015 geometry description, and since MediumProperty issues have not arisen there, then that suggests to me that these new xml material definitions are not related to the creation of MediumProperty objects.

**Comment by VinInn** [comment]
@ghellwig 
 the information provided here IS indeed relevant to create MediumProperty objects.
One has to run a proper "sequence" as outlined by @rovere last Friday

**Comment by ghellwig** [comment]
@VinInn 
I guess you are referring to [this talk](https://indico.cern.ch/event/512686/contributions/2182630/attachments/1280489/1901936/TrackerDPG_POG_20160527_MR.pdf)?
Does that mean, that the proper sequence is not run in the reconstruction of the phase1 relvals?
Or do I have to run the sequence in the user job?

**Comment by ianna** [comment]
@ghellwig 
Yes, it does. In order to include this, the following file needs to be updated, then the changes have to be propagated to a GT:
http://cmslxr.fnal.gov/source/Geometry/TrackerRecoData/data/PhaseI/trackerRecoMaterial.xml?v=CMSSW_8_1_X_2016-05-31-2300
IMHO, it is better to be done centrally rather then in an individual job. Though the latter is possible.

**Comment by VinInn** [comment]
@ghellwig , yes that talk
what I mean is that once the Sim geometry is ready one has to generate the proper reco geometry
using the "procedure"  (sorry not sequence in terms of workflow) outlined in there

**Comment by ghellwig** [comment]
@VinInn, @ianna thank you for the clarification and updates!

**Comment by mmusich** [comment]
@ianna, @VinInn  @rovere can you clarify who's in charge of:
"the following file needs to be updated, then the changes have to be propagated to a GT" ?
Thanks,
M.

**Comment by ianna** [comment]
@mmusich - Tracker DPG/POG should sign off on the file content.

**Comment by VinInn** [comment]
sign off == getting some relval, eventually an alignment excercise...

**Comment by mmusich** [comment]
@VinInn we can organize all these steps once we have the changes propagated in DB.

**Comment by VinInn** [comment]
@musich @ianna then we need the xml file, we can inspect (diff) it,  maybe run 1000 events
and "sign off" the file content for the loading in DB and start proper validation

**Comment by davidlange6** [comment]
+1

**Comment by kpedro88** [comment]
When I try to run upgrade workflow 11000.0 in CMSSW_8_1_X_2016-06-02-1100, I get an error in step1:
```
%MSG-e SimG4CoreGeometry:  (NoModuleName) 02-Jun-2016 10:30:35 CDT pre-events
DDG4Builder::  material materials:micro_twisted_boundle_1 is not valid (in the DDD sense!)
%MSG
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'SimG4CoreGeometry' occurred.
Exception Message:
 material is not valid from the Detector Description: materials:micro_twisted_boundle_1 
```

It looks like that material was introduced in this PR. Please fix ASAP.

**Comment by friccita** [comment]
@kpedro88 What is the geometry configuration loaded in workflow 11000.0?

**Comment by kpedro88** [comment]
@friccita This uses the Phase2 geometry: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Configuration/Geometry/python/GeometryExtended2023sim_cff.py
The underlying XML list is: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Geometry/CMSCommonData/python/cmsExtendedGeometry2023simXML_cfi.py

**Comment by friccita** [comment]
@kpedro88 I see... cmsExtendedGeometry2023simXML_cfi.py loads these files Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull*.xml for the pixel barrel layer definitions, which use the new materials defined for Phase I BPIX module cables. I will make another pull request to fix the PhaseII/materials.xml file so that it also includes these new materials from PhaseI.

**Comment by kpedro88** [comment]
@friccita Great, thanks!

**Pull request merged**
