### PR TITLE
Fix BuildFiles to avoid SCRAM warnings about missing tools/packages

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix SCRAM warnings about missing tools/packages
```
****WARNING: Invalid tool IOMC/EventVertexGenerators. Please fix src/TauAnalysis/MCEmbeddingTools/plugins/BuildFile.xml file.
****WARNING: Invalid tool Calibration/LumiAlCaRecoProducers. Please fix src/Calibration/LumiAlCaRecoProducers/plugins/BuildFile.xml file.
****WARNING: Invalid tool DataFormats/MuonData. Please fix src/HLTrigger/HLTanalyzers/BuildFile.xml file.
****WARNING: Invalid tool CondTools/CTPPS. Please fix src/RecoCTPPS/PixelLocal/BuildFile.xml file.
****WARNING: Invalid tool CondTools/CTPPS. Please fix src/RecoCTPPS/PixelLocal/plugins/BuildFile.xml file.
****WARNING: Invalid tool histogrammar. Please fix src/PhysicsTools/PythonAnalysis/test/BuildFile.xml file.

```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20561	fe4bbf8 
- technical 
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
