### PR TITLE
Update tag&probe package for egm [91X PR]

### PR DESCRIPTION
**Pull request by fcouderc**
egm tnp package has diverged from central repository for quite a while now.
Fix this by:

updating the central PhysicsTools/TagAndProbe to fulfil egm needs (this PR)
add a new package in cms-analysis for egm specific tnp tree making
This PR has been reviewed by muon conveners so that it does not change the muon tnp tree contents.
@HuguesBrun

It will be needed for legacy re-reco analysis and hence will also be committed in 80X.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@fcouderc 
please edit the title of this PR to be something more descriptive and grammatically appropriate.

**Comment by fcouderc** [comment]
can we integrate this, I would like to have it as well for 80X for the analysis of the legacy re-reco

**Comment by perrotta** [comment]
+1
The updates are concentrated in the PhysicsTools area, and no issues are spotted in them.
The Reco related change in DataFormats/RecoCandidate only adds a wrapper to a RefVector in the classes_def.xml file

**Pull request merged**
