### PR TITLE
Change the type1 jet pt threshold from 10 to 15 GeV (74X)

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #11362 for 74X.

Follows the decision taken in https://indico.cern.ch/event/447792/?filterActive=1&showDate=all&showSession=4
Will be added for miniAOD reprocessing, should not be part of promptReco.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
can I get AT signature rights on miniAOD-related PRs?

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
