### PR TITLE
use auto:run2_data_promptlike_hi in RECOHID18 instead of a hardcoded GT

### PR DESCRIPTION
**Pull request by slava77**
the issue of having a frozen/hardcoded GT showed up somewhat tangentially in tests of #25858 https://github.com/cms-sw/cmssw/pull/25858#issuecomment-467211412

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
it looks like we need to wait for the next IB to restart the tests

**Comment by fabiocos** [comment]
@slava77 yes, the latest low pt electrons update comes with the update of the external model file unfortunately

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@prebello @zhenhu @kpedro88 this looks a quite straightfoward fix
@tocheng I think it is what one should expect from the use of autoCond

**Comment by kpedro88** [comment]
+upgrade

**Comment by tocheng** [comment]
> @prebello @zhenhu @kpedro88 this looks a quite straightfoward fix
> @tocheng I think it is what one should expect from the use of autoCond

Thanks for noting. Indeed it will make life easier. 
The heavy Ion prompt like data GT will need to be updated to be compatible with PPS and GEM development. I will include this update in my PR which will deliver soon.

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
