### PR TITLE
fix a typo in --era specification

### PR DESCRIPTION
**Pull request by hengne**
fix a typo in --era specification noticed by @boudoul

### CODE REVIEW

**Comment by davidlange6** [comment]
@hengne - maybe a "_" could be added to HLTDR250ns (e.g., HLTDR2_50ns) to avoid the possibility for further confusion

**Comment by hengne** [comment]
@davidlange6 i think that's a good idea. this will require to change all the workflows that using that step, which has a potential to introduce new bugs, and better be tested well before a PR to change.

**Comment by davidlange6** [comment]
Right - it means a query replace in 3 places according to the search in git. (and fortunately a test will crash if not ok in this case)

**Comment by hengne** [comment]
@davidlange6 I can do this change and test carefully with the current 760pre7 regular Relval update PR that I am currently preparing.  Sounds good? I hope I can have it done by today or during the weekend.

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
sounds good. Thanks-

**Comment by boudoul** [comment]
+1

**Pull request merged**
