### PR TITLE
HLT customisation for Patatrack pixel tracks and GPU offload

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a customisation script for the HLT:
  - enable the Patatrack pixel track reconstruction, with quadruplets or triplets, running on CPU or GPU
  - optionally, add the possibility to offload the ECAL unpacking and local reconstruction to run on GPU
  - optionally, add the possibility to offload the HCAL local reconstruction to run on GPU

The new customisation is not used by any workflows.

#### PR validation:

Validated in CMSSW_12_1_0_pre1 with
```bash
cmsDriver.py reHLT \
    --processName reHLT \
    -s HLT:@relval2021 \
    --conditions 120X_mcRun3_2021_realistic_v4 \
    --datatier GEN-SIM-DIGI-RAW \
    -n 10 \
    --eventcontent FEVTDEBUGHLT \
    --geometry DB:Extended \
    --era Run3 \
    --customise=HLTrigger/Configuration/customizeHLTforPatatrack.customizeHLTforPatatrackTriplets \
    --filein /store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
```
resulting in
```
19-Aug-2021 17:28:58 CEST  Initiating request to open file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
19-Aug-2021 17:29:00 CEST  Successfully opened file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
%MSG-e TkDetLayers:   TSGFromL2Muon:hltL3NoFiltersNoVtxTrajSeedOIHit@streamBeginRun  19-Aug-2021 17:29:42 CEST Run: 1 Stream: 0
 ForwardDiskSectorBuilderFromDet: Trying to build Petal Wedge from Dets at different z positions !! Delta_z = -0.951241
%MSG
Begin processing the 1st record. Run 1, Event 2, LumiSection 1 on stream 0 at 19-Aug-2021 17:29:43.362 CEST
#--------------------------------------------------------------------------
#                         FastJet release 3.4.0
#                 M. Cacciari, G.P. Salam and G. Soyez                  
#     A software package for jet finding and analysis at colliders      
#                           http://fastjet.fr                           
#	                                                                      
# Please cite EPJC72(2012)1896 [arXiv:1111.6097] if you use this package
# for scientific work and optionally PLB641(2006)57 [hep-ph/0512210].   
#                                                                       
# FastJet is provided without warranty under the GNU GPL v2 or higher.  
# It uses T. Chan's closest pair algorithm, S. Fortune's Voronoi code
# and 3rd party plugin jet algorithms. See COPYING file for details.
#--------------------------------------------------------------------------
Begin processing the 2nd record. Run 1, Event 1, LumiSection 1 on stream 0 at 19-Aug-2021 17:29:52.870 CEST
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:00.396 CEST
Begin processing the 4th record. Run 1, Event 4, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:03.761 CEST
Begin processing the 5th record. Run 1, Event 5, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:07.514 CEST
Begin processing the 6th record. Run 1, Event 7, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:11.653 CEST
Begin processing the 7th record. Run 1, Event 8, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:18.739 CEST
Begin processing the 8th record. Run 1, Event 6, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:20.226 CEST
Begin processing the 9th record. Run 1, Event 9, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:28.354 CEST
Begin processing the 10th record. Run 1, Event 10, LumiSection 1 on stream 0 at 19-Aug-2021 17:30:33.571 CEST
19-Aug-2021 17:30:42 CEST  Closed file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 TkDetLayers          -e TSGFromL2Muon:hl                       1        1
    2 fileAction           -s file_close                             1        1
    3 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 TkDetLayers          Run: 1 Stream: 0                  
    2 fileAction           PostGlobalEndRun                  
    3 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Error                   1                   1
System                  3                   3

dropped waiting message count 0
```

Tested successfully both with and without a GPU.
The physics validation and the GPU vs CPU comparison will follow after the customisation has been merged.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

To make the bot happy, even if the new customisation is not used anywhere.

**Comment by fwyzard** [comment]
FYI @amassiro @thomreis @mariadalfonso @mmasciov

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Taking for good the validation of the customization as reported in the PR description

**Comment by missirol** [comment]
(Leaving a comment for @fwyzard, even though the PR is closed)

If using an HLT config with only a subset of triggers, it can happen that some of the customisations are silently skipped.

I noticed this when testing a config with (only) the path `MC_PFMET`, which contains `HLTDoFullUnpackingEgammaEcalWithoutPreshowerSequence` but not `HLTDoFullUnpackingEgammaEcalSequence`; in this case, the ECAL customisation function is (unnecessarily) skipped due to [this check](https://github.com/cms-sw/cmssw/pull/34956/files#diff-632cc5cca01989675d152c8bed40514779a64465494fee20070edfd57680d020R350).

I guess one option is to just improve a bit the safeguards at the beginning of the functions (maybe just the ECAL one). I was wondering if it would be okay to remove the safeguards altogether (and then, if no path uses the customised sequences/tasks, those will be ignored in any case?).

**Comment by fwyzard** [comment]
@missirol thanks for the comment.

We cannot run the customisation unconditionally, as they would fail if the configuration is missing the modules it references, *e.g.*
```python
process.hltEcalDigisLegacy = process.hltEcalDigis.clone()
```
will fail if `hltEcalDigis` is not available, *etc.*

It may be enough to change
```diff
-if not 'HLTDoFullUnpackingEgammaEcalSequence' in process.__dict__:
+if not any(seq in process.__dict__ for seq in ['HLTDoFullUnpackingEgammaEcalMFSequence', 'HLTDoFullUnpackingEgammaEcalWithoutPreshowerSequence', 'HLTDoFullUnpackingEgammaEcalSequence'):
```

Could you give it a try ?

**Comment by missirol** [comment]
Thanks, @fwyzard . Yep, will try.

**Pull request merged**
