### PR TITLE
Move ModelpMSSMFilter to src

### PR DESCRIPTION
**Pull request by mmrowietz**
#### PR description:

The ModelpMSSMFilter was backported to this CMSSW version as part of the Run-II pMSSM effort. In newer versions of CMSSW, GenFilters like the ModelpMSSMFilter are put into the plugins directory in GeneratorInterface/GenFilters/plugins. The plugins directory is not built in this version of CMSSW, which means the ModelpMSSMFilter has to be in the src directory (like all the other GenFilters).
No output changed are expected by this, and no other PRs are expected to be affected.
The relevant backports are:
backport of filter
backport of fixes
This PR was already done in CMSSW_9_4_X
[CMSSW_9_4_X version ](https://github.com/cms-sw/cmssw/pull/30705)
#### PR validation:
PR validation:

A test fragment containing the filter was successfully converted to a config using cmsDriver and run with cmsRun.

### CODE REVIEW

**Comment by mmrowietz** [comment]
please test

**Comment by mmrowietz** [comment]
please test

**Comment by ssekmen** [comment]
please test

**Comment by silviodonato** [comment]
@alberto-sanchez @SiewYan @qliphy @GurpreetSinghChahal @mkirsano @agrohsje can we merge this PR?

**Comment by davidlange6** [comment]
just to correct a comment above - plugins directories are built in this CMSSW release. They do however, need a build file in the plugins directory in order to specify how the plugins should be built (just as in the current master branch).

**Comment by qliphy** [comment]
+generators

**Comment by silviodonato** [comment]
+1

**Pull request merged**
