### PR TITLE
Properly zero terminate a string in DQMEventInfo.

### PR DESCRIPTION
**Pull request by dmitrijus**
Properly zero-terminate a string in DQMEventInfo.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
thanks @dmitrijus 
please submit the same for 75 as well. no automatic forward port..
F.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
