### PR TITLE
Backport to 12_3_X CSC DQM Run3 related updates PR#37732

### PR DESCRIPTION
**Pull request by barvic**
#### PR description:
Backport to 12_3_X of CSC DQM Run3 related updates PR #37732

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Would like to deploy this DQM update to P5 production for online DQM, while 12_3_X is used there to monitor ongoing CSC Run3 system validation.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by barvic** [comment]
Hi @emanueleusai @perrotta, could it be merged as well? (12_4_X PR #37732 was merged today)

**Comment by emanueleusai** [comment]
PR has been tested at P5 and is ready to go from our side

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1
tested at P5 and master IB

**Pull request merged**
