### PR TITLE
Phase2 TK Digitizer validation suite updated

### PR DESCRIPTION
**Pull request by boudoul**
The validation suite updated thread safe DQM framework. 
Superseeding the original PR from @suchandradutta : PR #14355 
The DigiCommon has been removed and put in TrackerTopology as requested in   PR #14355 
Cluster validation code updated as well to cope with this. @thomaslenzi @delaere please check

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #14709 12cce1f6043c0100cc2e6d9e2ba89ab2fe2f00b7

Revisions to the Phase 2 tracker digitizer validation suite. There should be no change in non-Phase 2 workflows. Changes to Reco code are very minimal.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-05-29-2300 show no significant differences, as expected.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
