### PR TITLE
Use standard naming for configs in CondTools/RunInfo

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added _cfg.py to configuration file names
This avoids conflicts with auto generated files coming from fillDescriptions.

#### PR validation:

Can not full run unit tests as the machine I worked on did not have access to oracle DB.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
An additional improvement would by to move these files out of the python directory as they are never meant to be `import`ed to python. Could go into a `config` directory instead.

**Comment by francescobrivio** [comment]
Hi Chris,
I only had time to have a _very_ quick look at this PR for now, but some of the renamed pythons in RunInfo are the actual scripts executed in the LHCInfo O2Os.

This is the master branch so it's not a big deal for operations at the moment, but it will be once we'll move to newer releases (i.e. we'll have to remember to change the script names in the appropriate machines).
We'll take a better look tomorrow and provide feedback!

FYI @JanChyczynski

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+db

 - all tests pass, no differences observed in comparisons
 - with the caveat (reminder) described in https://github.com/cms-sw/cmssw/pull/44407#issuecomment-2006569561

**Comment by antoniovilela** [comment]
> > Hi Chris, I only had time to have a _very_ quick look at this PR for now, but some of the renamed pythons in RunInfo are the actual scripts executed in the LHCInfo O2Os.
> > This is the master branch so it's not a big deal for operations at the moment, but it will be once we'll move to newer releases (i.e. we'll have to remember to change the script names in the appropriate machines). We'll take a better look tomorrow and provide feedback!
> > FYI @JanChyczynski
> 
> @Dr15Jones Hi Chris, Sorry for the delay! I went through the full list of updated configs and I see 3 cases:
> 
> * RunInfo config --> this is especially important for the RunInfo Start/End run O2Os, if this breaks then cDAQ won't be able to start a new run!
> * Old LHCInfo configs --> soon to be retired from production
> * New LHCInfoPer* configs --> being deployed in production these days
> 
> So I don't see any issue with this PR _per-se_ as long as:
> 
> 1. We don't backport it to 14_0_X (is this foreseen?)
> 2. We (@cms-sw/alca-l2 @cms-sw/db-l2 @JanChyczynski) remember to update all the O2O scripts once we switch to CMSSW >= 14_1_X in production!

@francescobrivio @JanChyczynski 
In which repository are the O2O scripts maintained? It would be good to open an issue there, so that you remember to make this update.

**Comment by antoniovilela** [comment]
+1

**Comment by francescobrivio** [comment]
> @francescobrivio @JanChyczynski
> In which repository are the O2O scripts maintained? It would be good to open an issue there, so that you remember to make this update.

Dear @antoniovilela, many thanks for the nice suggestion!
Here are the issues:
 - LHCInfo O2Os: https://gitlab.cern.ch/cms-ppdweb/o2o-lhcinfo-repo/-/issues/1
 - RunInfo O2Os: https://gitlab.cern.ch/cms-ppdweb/O2O/-/issues/1

**Pull request merged**
