### PR TITLE
(Splash only) Special timing plot configuration for splash events

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

During splash events, we often have very poor signal shapes. In addition, it is useful to view these events in a wider time window than the default configuration. This PR changes the timing windows and removes a chi-square constraint to make DQM more useful during splash events. This is not meant to be merged into CMSSW.

#### PR validation:
Validated by the standard DQM configuration. No issues seen.

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters

- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
@abhih1 if you just want this for the current Splash runs but not merged into CMSSW for further runs, as I understand from the PR description, then we should NOT merge the master version of this PR, and just add this PR in current Online DQM

Is this statement correct?
Thanks

> #### PR description:
> During splash events, we often have very poor signal shapes. In addition, it is useful to view these events in a wider time window than the default configuration. This PR changes the timing windows and removes a chi-square constraint to make DQM more useful during splash events. This is not meant to be merged into CMSSW.
> 
> #### PR validation:
> Validated by the standard DQM configuration. No issues seen.
> 
> A forward port to the master is made here: #35735

**Comment by abhih1** [comment]
Hi @pmandrik 
Thanks for your suggestion. I have made another PR implementing this method. Please take a look: https://github.com/cms-sw/cmssw/pull/35747

**Comment by abhih1** [comment]
Ok. Closing.

**Pull request closed without merging**
