### PR TITLE
Fix to allow histogram rebinning to work again for Tracker DQM trend plots in ROOT6

### PR DESCRIPTION
**Pull request by vdutta**
In ROOT6 the TH1 kCanRebin option doesn't work anymore. This affects the behavior of the current tracker DQM trend plots. They are no longer correctly updated to accommodate an expanded histogram axis to show trends vs lumi section for longer runs for example, since the histograms can no longer be rebinned. This fix updates the use of the SetBit(kCanRebin) option to SetCanExtend(TH1::kAllAxes) as recommended for ROOT6 in the Tracker DQM code and is needed quite urgently to restore the correct behavior for the trend plots. Also, the code for DQMRootSource (DQMServices/FwkIO/plugins/DQMRootSource.cc) is updated for the merging of rebinnable histograms during harvesting to be compatible with the new ROOT6 behavior (the old TestBit(TH1::kCanRebin) is replaced with the new CanExtendAllAxes()).

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by venturia** [comment]
If this PR could merged and put in production at T0 (and online) it would be very useful. As long as it is not there some Tracker DQM plots are broken.

**Comment by danduggan** [comment]
@venturia, at least for online DQM, you've already got this in. this PR was included as of this past Tuesday evening.

**Comment by venturia** [comment]
Thanks!
On Jun 7, 2015, at 11:37 , danduggan <notifications@github.com<mailto:notifications@github.com>>
 wrote:


@venturia<https://github.com/venturia>, at least for online DQM, you've already got this in. this PR was included as of this past Tuesday evening.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
