### PR TITLE
PR for HLT online DQM monitoring code for Proton-Lead run in 81X (upd…

### PR DESCRIPTION
**Pull request by varuns23**
…ated #16346)

@mtosi @silviodonato @diguida @vanbesien @dmitrijus

### CODE REVIEW

**Comment by varuns23** [comment]
PR made using CMSSW_8_1_X_2016-11-02-1100

**Comment by diguida** [comment]
@varuns23 thanks for the follow-up changes. Can you please add this PR to the [DQM Twiki for 2016 pPb run](https://twiki.cern.ch/twiki/bin/view/CMS/DQMHeavyIon2016)?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by varuns23** [comment]
Added to twiki

**Comment by dmitrijus** [comment]
+1

**Comment by varuns23** [comment]
Any update from hlt or orop side?

@mtosi @silviodonato @diguida @vanbesien

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
