### PR TITLE
[12_4_X] Update of ECAL conditions for Run3 MC production 12_4

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38514

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38514

### CODE REVIEW

**Comment by tvami** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/38514

**Comment by tvami** [comment]
type ecal

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+1

 - differences are understood (see https://github.com/cms-sw/cmssw/pull/38514#issuecomment-1167690858)

**Comment by perrotta** [comment]
+1

**Pull request merged**
