### PR TITLE
Introduce HGCal within CaloGeometry infrastructure

### PR DESCRIPTION
**Pull request by lgray**
Adds HGCal to CaloGeometry to allow for better integration with the rest of CMSSW.

Also adds in ability to use testbeam geometries in Fireworks reco geometry dumper.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

unit tests failures do not appear related to this PR...

**Comment by ianna** [comment]
+1

**Comment by lgray** [comment]
@alja Could you please take a look at this PR at your soonest convenience!

**Pull request merged**
