### PR TITLE
simplify MU-DPG custom nano configuration

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

having imports at top level of nano cff was not desirable. With a simple change in ConfigBuilder, we can move everything in the autoNANO mapping.

#### PR validation:
nano matrix was successful

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by battibass** [comment]
Thanks a lot @vlimant I had the same idea when I made the previous implementation, but I didn't date touching `ConfigBuilder`

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
