### PR TITLE
Correction of a tag name (Ecal O2O unit test fix)

### PR DESCRIPTION
**Pull request by depasse**
Realted to the error described in PR #23606

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@depasse @ggovi thanks for the prompt reaction. Anyway, why this was working up to Friday evening and it has stopped top do so since then? What has changed to cause this failure?

@ggovi if this is ok for you, could you please sign it?

**Comment by depasse** [comment]
Hypothesis : this code was created on 17 February.
On Friday, it was the first time that there was a switching Bon -> Boff. So the first time the wrong tag was called.
Giacomo, this code is only for testing purposes, no ? As the O2O in production works well.

**Comment by ggovi** [comment]
@fabiocos 
I think Pierre is right, the code with the wrong tag was previously never invoked.
@depasse 
yes this is the validation test. The production script is a different one, no failures on it.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@depasse thank you for the explanation, it makes sense

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@boudoul you are right, this title was bit too generic... I have appended a note

**Comment by boudoul** [comment]
Thank you @fabiocos !

**Pull request merged**
