### PR TITLE
Phase2-hgx327D Delete some of the obsolete files in Geometry/HGCalCommonData/test area and make some more general

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Delete some of the obsolete files in Geometry/HGCalCommonData/test area and make some more general

#### PR validation:

Test the modified scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
Hi @bsunanda 
Is there a part of the unit-test in this PR, or all does not effect the unit test at all? If there is a part that updates the unit-test, maybe we can trigger the full test before merging it. Thanks.

**Comment by bsunanda** [comment]
@srimanob These are not part of unit test - only used to test during implementation. Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+

- Straightforward configuration cleanup.

**Pull request merged**
