### PR TITLE
Removed unused fwkJobReports from MessageLogger in Geometry Subsystem

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The parameter fwkJobReports is an obsolete parameter which has had no functionality for many years.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
there appear to be DQM failures in Phase 2 workflows for SiOuterTrackerV, but I'm not sure how that could be related to this PR.

**Comment by makortel** [comment]
See https://github.com/cms-sw/cmssw/issues/31644.

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
