### PR TITLE
Clean up Phase-2 geometry (Up to D85)

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to clean up Phase-2 Geometry as discussed in
https://github.com/cms-sw/cmssw/issues/38594

There will be a follow up PR on resetting workflow number.

#### PR validation:
Comparison of outputs from `runTheMatrix.py --what upgrade -n` shows that we have less Phase-2 workflows. All D49-D85 workflows are removed. Log files can be found in `/afs/cern.ch/user/s/srimanob/public/ForPhase2SW/Geometry/2022CleanUp`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. 
No need of backport, or special requests.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
unhold

**Comment by srimanob** [comment]
Back to this PR, any objection to reset the workflow number as proposed [here](https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1174216575). So the first upgrade workflow will be 200000 (2026D86+FourMuPt_1_200_pythia8_GenSimHLBeamSpot+DigiTrigger+RecoGlobal+HARVESTGlobal which was 38600.0)

@cms-sw/orp-l2 @cms-sw/simulation-l2 @cms-sw/reconstruction-l2 @kpedro88

**Comment by srimanob** [comment]
Proposal from HGCAL to separate PR to resetting the workflow ID.

**Comment by srimanob** [comment]
+Upgrade

As agree in ORP, this PR goes first. Then the resetting PR comes later with clean IB.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 any objection to merge this?

**Comment by perrotta** [comment]
+1

**Comment by iarspider** [comment]
@srimanob IB Unit Tests still use `GeometryExtended2026D49_cff` and thus are failing, see e.g. [this](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-09-28-2300/unitTestLogs/CondTools/SiPixel#/3307-3307).

**Comment by srimanob** [comment]
Hi @iarspider 
Thanks. I collect the unit test failure in https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1261879490. I will follow up and provide fixes.

**Comment by srimanob** [comment]
Staring from CMSSW_12_6_X_2022-10-05-1100, unit tests seem to be OK now.

**Pull request merged**
