### PR TITLE
New ETL geometry with 11 rings based on engineering drawings, add approximate support plate

### PR DESCRIPTION
**Pull request by fabiocos**
The ETL geometry is updated according to specifications by @lgray from FNAL engineers. The rings have been updated from 9 to 11, and the positions are now according to the provided spreadsheet.
An approximate description of the aluminum support plate is also added, with a 6 mm thick plate between rings and a restricted 3.4 mm plate within rings, in the space in between front and rear modules. The services description in tkLayout has not been modified. The module size now used in 95 x 49 mm.

The numbering scheme code has been adapted accordingly.

The ETL geometry remains free from overlaps (tested with Geant4 code), and the numbering scheme has been reverified with the test code. According to the Geant4 dump of SD positions, the ETL module are correctly placed.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
real tests should be done using PhaseII scenarios D24 and D25

**Comment by fabiocos** [comment]
assign geometry

@smuzaffar apparently I missed to updated the bot for the addition of these packages back in #23126, to be fixed

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 FYI, this is affecting PhaseII geometry

**Comment by kpedro88** [comment]
assign upgrade
@fabiocos can you please add the new packages to the upgrade category?

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
