### PR TITLE
Code to turn on VINCIA plugin version 2

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be tested against cmsdist #3480

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#3480

**Comment by smuzaffar** [comment]
@mkirsano , code-checks should be passed before bot can start the normal tests.

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#3480

**Comment by mkirsano** [comment]
Must be a problem of synchronization with cmsdist PR

**Comment by davidlange6** [comment]
hi @mkirsano - are you sure because you tested it? - I don't see how your build files indicate that they should depend on vincia.

**Comment by mkirsano** [comment]
Indeed, sorry

**Comment by efeyazgan** [comment]
please test

**Comment by smuzaffar** [comment]
please abort test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3480
this need external PR too

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3480

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3480

**Comment by perrozzi** [comment]
so @mkirsano you say that this version of the plugin is not compatible with pythia8 230 right?

**Comment by mkirsano** [comment]
I will look a bit more into this. VINCIA itself compiles with pythia8 230.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3480

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
