### PR TITLE
DD4hep: Fix TOB g4 Overlaps

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

TOB presented overlaps that were not seen before by using the overlaps configuration file:

```
cmsShow -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS
```

Overlaps being fixed were found by running g4 check:

```
cmsRun SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4Hep_cfg.py
```

###### Master
Screenshot from 2020-08-19 15-05-04

###### Reference
Screenshot from 2020-08-19 15-07-53

###### ThisPr
Screenshot from 2020-08-19 15-11-49

#### PR validation:

```
$cmsRun g4OverlapCheckDD4Hep_cfg.py 2>DD4heloOVL.txt  # Go for some coffee
$grep TOB DD4heloOVL.txt # No output expected
```

#### Notes:

Partially related to: https://github.com/cms-sw/cmssw/issues/31143
Further validation steps: https://github.com/cms-sw/cmssw/pull/27689
@ghugo83: This may be of your interest :)

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@civanch I was in the middle of uploading the Run 3 geometry DB payloads, but now I will have to start over after this PR gets merged, since it changes the geometry for 2021.

**Comment by civanch** [comment]
@cvuosalo , are you sure if this is the last fix?

**Comment by civanch** [comment]
@vargasa , great fix!

**Comment by cvuosalo** [comment]
@civanch No, I'm not sure what other fixes might occur. Andres just mentioned in #31143 that he will create an issue listing more overlaps.

**Comment by civanch** [comment]
@cvuosalo , it is up to you. We will have PPS fixes, this fix and may be other existing overlaps will require extra fix. But you may integrate this one when this PR will be merged, because tracker is a very important sub-system.

**Comment by vargasa** [comment]
> @civanch No, I'm not sure what other fixes might occur. Andres just mentioned in #31143 that he will create an issue listing more overlaps.

@cvuosalo posted here https://github.com/cms-sw/cmssw/issues/31182, however none of the volumes in that list are familiar to me, I'd hope not to see tracker overlaps again but I thought the same in April :sweat_smile: @civanch thank you!

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
urgent

**Review by ianna — CHANGES_REQUESTED** [review]
@vargasa - please, note that `testTracker2021Geometry.py` has been deleted from `DetectorDescription/DDCMS`. If you need a Tracker-specific test please, place it under `Geometry/Tracker*`. This PR `testTracker2021Geometry.py` configuration uses a complete 2021 scenario. There is a test for it already present `testGeometry2021.py` :-)

Please, rebase.
Thanks

**Review by ianna — APPROVED** [review]
Well done! Thanks!

**Pull request merged**
