### PR TITLE
fillDescriptions migration and parameter cleanup in DAQ modules (75X)

### PR DESCRIPTION
**Pull request by smorovic**
Changes:
- Migrating production DAQ modules EvFDaqDirector, EvFOutputModule, FedRawDataInputSource and FastMonitoringService to using fillDescriptions. Removing cfi python files for those cases.
- Removing obsolete parameters from those modules
- Allow FastMonitoringService to find definition file in both CMSSW_BASE and CMSSW_RELEASE_BASE (those differ when running from project area).

Update: another two changes were pushed (PR was anyway not signed yet):
- FedRawDataInputSource also checks in CMSSW_BASE and CMSSW_RELEASE_BASE for input JSON definition file
- Disabling optimization for Exception generator, as the loop in test 9 is otherwise optimised out
  (updated also in 76X and 80X PRs)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try tests again in hopes they will not land on machine that is out of disk space.

**Comment by cvuosalo** [comment]
+1

For #12146 b0cc638bb512ec2babdd469beea47bf91e0e535a

fillDescriptions migration in DAQ modules.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12146/9397/summary.html) against baseline CMSSW_7_5_X_2015-10-30-1100 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
