### PR TITLE
Use new primary vertex filter in hotline and high MET skim (74X)

### PR DESCRIPTION
**Pull request by duanders**
Backport of https://github.com/cms-sw/cmssw/pull/11060 to 74X

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 
for https://github.com/duanders/cmssw/commit/484bd29868ecf067fb6e928a3d8064495b335cee
backport of #11060

**Comment by mariadalfonso** [comment]
@franzoni please have a look at this PR, we would like to have the VTX fix for the coming 3.8T Hotline

**Comment by mariadalfonso** [comment]
@srimanob @boudoul can you please have a look at this PR ? This modification was done also in the offline miniAOD #10604.  This PR is already ported in 76 and 75 #11060 and  #11218. Ideally we need before the 3.8 Tesla

**Comment by srimanob** [comment]
+1
It looks OK for me, as I check the RecoMET/METFilters/python/primaryVertexFilter_cfi.py
Seem to be the same as 2012 analysis

**Comment by davidlange6** [comment]
@srimanob @duanders - we need this signed and checked in the 76x IBs - is it part of the IB relval skim tests?

**Comment by duanders** [comment]
@davidlange6 - The hotline skim was in the relval sequences originally (under RECOD), but it seems to have been removed.  Not sure why.  What else can we do to test?

**Pull request closed without merging**
