### PR TITLE
SimG4: DD4hep Geometry Tests

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add DDDWorld test
* Add G4 regions description test
* Remove Geometry producer plugin
* Move tests to a test/plugin directory
* Add script to run the tests automatically

#### PR validation:

```scram b runtests```

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - please, approve

**Comment by kpedro88** [comment]
+1

**Pull request merged**
