### PR TITLE
DD4hep: Update Units Check Script

### PR DESCRIPTION
**Pull request by ianna**
* Update print to Python3
* Align error marker when there are tabs used in a line

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@ianna I see that you have protected the script against reports for MaterialFraction. There are anyway other cases that could be considered. Running the script in the form proposed in this PR:

/build/fabiocos/104X/25281/CMSSW_10_4_X_2018-11-19-2300/src/DetectorDescription/DDCMS/data/materials.xml: line# 4 warning: numerical value without units: 
  <ElementaryMaterial name="Aluminium" density="2.7*g/cm3" symbol=" " atomicWeight="26.98*g/mole" atomicNumber="13"/>

                                                                                                                ^----- 

atomicNumber is a pure number

/build/fabiocos/104X/25281/CMSSW_10_4_X_2018-11-19-2300/src/DetectorDescription/DDCMS/data/materials.xml: line# 336 warning: numerical value without units: 
  <CompositeMaterial name="Aluminium 2219" density="2.84*g/cm3" symbol=" " method="mixture by weight">

                                     ^-----                                                             

Aluminium 2219 is just the material name

It depends on how stringent you want to do the test, as you may have multiple instances of numerical values in the same line, and the logic in the check does not easily disentangle them I am afraid, do you agree?

**Comment by ianna** [comment]
@fabiocos - yes, I'm not sure how far we want to go with the script.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
