### PR TITLE
[14_1_X] Fix ZMu skimming code for 2024 PbPb data taking

### PR DESCRIPTION
**Pull request by flodamas**
#### PR description:

Backport of #46584

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test workflow 142.0

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46584

**Comment by AdrianoDee** [comment]
urgent
(see https://github.com/cms-sw/cmssw/pull/46458#pullrequestreview-2411210271)

**Comment by mmusich** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Pull request merged**
