### PR TITLE
Produces Hcal Digi plots where the HF TPs are separated between 3x2 and 1x1 TPs

### PR DESCRIPTION
**Pull request by kencall**
The new 1x1 HF trigger primitives are saved in the same collection as the 3x2 HF trigger primitives.
All of the existing trigger primitive plots are retained; however, new plots have been defined which use exclusively the 3x2 or 1x1 tigger primitives.

plots labled *v0 use the 3x2 trigger primitives
plots labled *v1 use the 1x1 trigger primitives

### CODE REVIEW

**Comment by dmitrijus** [comment]
plaase test

**Comment by abdoulline** [comment]
@dmitrijus 
Could you please, restart the test (there was a typo in your previous request)?

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
