### PR TITLE
[13.0.X] Add protection to avoid crash in `lowPtGsfEleGsfTracks` (and other e/gamma reco)

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/41442

#### PR description:

This PR is to fix a GSF crash in prompt-reco, as reported in https://github.com/cms-sw/cmssw/issues/41442

#### PR validation:

`runTheMatrix.py -l 12434.0` ran fine.
Also, checked with 1k MC events that electron reconstruction is otherwise not effected and physics results are identical after this change (see https://github.com/cms-sw/cmssw/issues/41442#issuecomment-1526071451)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/41450

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
backport of #41450

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
