### PR TITLE
NanoAOD Update: trigger, nPV, pileup (9_4_X)

### PR DESCRIPTION
**Pull request by arizzi**
This includes:
 - tune of trigger objects
 - fix of trigger bits when version number changes
 - n goodPV
 - oot pileup

All changes are in PhysicsTools/NanoAOD

backport of #22037

@gpetruc

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by arizzi** [comment]
can someone please retrigger the tests?

**Comment by fabiocos** [comment]
+code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar apparently something went wrong with the test, could you please check?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
