### PR TITLE
Logging service for Condition Workflows

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

We are adding a new service to provide recollection of log messages, with the aim to store them in the database, related to the condition data stored in the same context.

The target and main use case for this implementation are the workflows providing the lumi-based conditions for HLT.

#### PR validation:

A dedicate unit tests validates the base Logger. Two integration tests are exercising the use case with an Oracle db destination.

### CODE REVIEW

**Comment by ggovi** [comment]
Wondering how to avoid to fix this type of issues  AFTER the PR submission. Running scram build code-format before the first submission seems to be not the way...

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by yuanchao** [comment]
@ggovi Though the duplicated include clause of "Exception.h" probably won't affect, is this intended or by accident?
CondCore/DBOutputService/src/PoolDBOutputService.cc

**Comment by ggovi** [comment]
@yuanchao thanks...

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by yuanchao** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
