### PR TITLE
Db geom

### PR DESCRIPTION
**Pull request by deguio**
move to geometry from DB

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@ianna 
could you please have a quick look and confirm that this addresses the change you asked?
thanks,
F.

**Comment by ianna** [comment]
@deguio - yes, thanks!

**Comment by deguio** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
-1

merge conflicts

```
Auto-merging DQMOffline/JetMET/test/run_PromptAna.py
CONFLICT (content): Merge conflict in DQMOffline/JetMET/test/run_PromptAna.py
Auto-merging DQM/Integration/python/test/castor_dqm_sourceclient-live_cfg.py
Automatic merge failed; fix conflicts and then commit the result.

```

**Comment by deguio** [comment]
should be ok now.

**Comment by deguio** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7666	 17e4a1d
the only reco-category related change is in 
Validation/Configuration/test/SingleMuPt10_valid_cfg.py 

jenkins tests completion will be enough for our side

**Comment by slava77** [comment]
that was a DAS glitch in 4.22
we need to start detecting these in jenkins
(fixing DAS is not an option, I guess)

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Pull request merged**
