### PR TITLE
Prepare CSCGeometryESModule for concurrent IOVs 

### PR DESCRIPTION
**Pull request by wddgit**
Main issue is replacing the shared_ptr data member
and its usage. Multiple threads cannot access the same
one concurrently.

Also add Framework change to clear the caches before
destroying the EventSetupProvider.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
-geometry

@ianna I accidently signed for framework and geometry. I did the -1 here so you could take a look. Please override if you find this change acceptable.

**Comment by wddgit** [comment]
We are considering changing the approach for these modifications. Closing and will likely resubmit later.

**Pull request closed without merging**
