### PR TITLE
Final global tags for 2017 UL reprocessing

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the global tags relevant for the 2017 UL reprocessing, as well as a fix for PPS conditions in prompt-like global tags. Both data and MC global tags are updated.

The changes are as follows:

106X_dataRun2_v17:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v17/106X_dataRun2_v13

106X_dataRun2_relval_v16:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v16/106X_dataRun2_relval_v12

106X_dataRun2_PromptLike_HEfail_v9:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v9/106X_dataRun2_PromptLike_HEfail_v8

106X_dataRun2_PromptLike_v10:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v10/106X_dataRun2_PromptLike_v9

106X_dataRun2_PromptLike_HI_v10:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v10/106X_dataRun2_PromptLike_HI_v9

106X_mc2017_realistic_v7:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v7/106X_mc2017_realistic_v5

#### PR validation:

An enormous amount of work went into validating the conditions for this PR. Details can be found at the sign-off talks listed at:

- Data: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4163.html
- MC: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4159.html

As a technical check, I ran `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR:

This PR is not a backport but a backport will be prepared for 10_6_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The differences in pre-2017 workflows are not expected. They appear to only affect `EcalRecHitsSorted` collections and downstream quantities. The differences arise because a change has been made to the pre-2017 history of the `EcalPFRecHitThresholdsRcd` tag:
```
lxplus793>conddb diff EcalPFRecHitThresholds_UL_Run1_Run2_2017_v1 EcalPFRecHitThresholds_2018_v1_offline
[2019-06-26 14:49:33,059] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Range               pro::EcalPFRecHitThresholds_UL_Run1_Run2_2017_v1 Payload  pro::EcalPFRecHitThresholds_2018_v1_offline Payload  
------------------  --------------------------------------------------------  ---------------------------------------------------  
[1, 265475)         9fdf3a78064032372f6107368c8da1c1a44a94f2                  9f22e391bcdcabe1f9f13608961bbed938c8a05c             
[265475, 286694)    0d6c3b61b14fec97f10bfba826350bc7f2a8f413                  9f22e391bcdcabe1f9f13608961bbed938c8a05c             
[286694, Infinity)  f6ae126e7828a2b6f89869d65bdfd1902f9574f7                  9f22e391bcdcabe1f9f13608961bbed938c8a05c             
```
I will follow up with ECAL experts offline to have this fixed.

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
hold

The data GTs should not modify 2018 IOVs. Updated data GTs are being prepared.

**Comment by christopheralanwest** [comment]
unhold

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The last update introduced two changes:

- The beamspot tag used by the offline data GT was updated by appending the `BeamSpotObjects_post2017_LumiBased_v1 ` to a copy of the `BeamSpotObjects_2017UL_LumiBased_v1` tag. This was done to ensure that the 2018 history is unchanged.
- A purely technical change to the 2017 realistic MC GT: an obsolete, unused record was removed.

**Comment by christopheralanwest** [comment]
+1

- Changes seen only in 2017 workflows, except for PPS quantities in 2018 data. PPS is a special case as its reconstruction software was developed in parallel to the 2017 UL preparation and therefore there is no requirement to leave the 2018 PPS quantities unchanged during the 2017 UL preparation.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
