### PR TITLE
updating triggerObjects_cff V10

### PR DESCRIPTION
**Pull request by mrcthiel**
Adding photon and muon leg trigger filters of HLT_Mu17_Photon30_IsoCaloId_v* on V10 as requested in https://github.com/cms-sw/cmssw/pull/39309#issuecomment-1293281091

### CODE REVIEW

**Comment by swertz** [comment]
enable nano
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

Goes along #39309; only differences seen in nanoAOD trigger objects for muons and photons in V10 workflows.

**Comment by rappoccio** [comment]
+1

* Addition to nano is expected.

**Comment by swertz** [comment]
Strictly speaking this should still be backported to 12_4_X.

**Pull request merged**
