### PR TITLE
New HCalTower cleaner including rechits

### PR DESCRIPTION
**Pull request by safarzad**
new HCALTowerCleaner module is added to be able to do rechit filter online

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Can you remove the ```fix a bug in the JetId cleaned module``` from THIS PR so that
it is ONLY adding a new plugin?

**Comment by safarzad** [comment]
I do not know why they are mixed up, how can I remove it?

**Comment by Martin-Grunewald** [comment]
Simply copy the original file into your area and push as another commit to your branch...

**Pull request closed without merging**
