### PR TITLE
Conditions Updater for HLT: Added OMS service as source of Run and Lumi info

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

The OMS online service has been recently developed to provided the info about on-going Run and Lumisection ID. This PR integrates the access to this service to obtain the two parameters in the context of condition updates for the HLT workflow

#### PR validation:

Since the OMS service is available only at the P5 network, a specific test has been executed in a dedicated online deployment.  
The existing unit and integration tests have been executed in the normal offline CMSSW environment, to validate the offline use cases.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by tlampen** [comment]
+alca

**Comment by silviodonato** [comment]
+1

**Pull request merged**
