### PR TITLE
[DB] [LLVM16] Code format changes applied

### PR DESCRIPTION
**Pull request by smuzaffar**
changes suggested by llvm16  clang-format

### CODE REVIEW

**Comment by francescobrivio** [comment]
@smuzaffar the suggested change is only to have the `struct` definition in one line instead of 3: do we need to run tests for this PR?

**Comment by smuzaffar** [comment]
although no need to run tests such PRs but when you will sign it then bot will start the tests any way :-)

**Comment by francescobrivio** [comment]
+1

 - simple code formatting, no actual change in the code

**Comment by perrotta** [comment]
please abort

**Pull request merged**
