### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/40181).

In some cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

This PR cleans unnecessary includes from CMSSW BuildFiles that were added in the last months.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by aloeliger** [comment]
+l1

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by makortel** [comment]
+core

**Comment by tvami** [comment]
> ---> test DRNTest had ERRORS

is this a known problem?

**Comment by makortel** [comment]
The `DRNTest` has been failing randomly in the past. Taking a closer look now, the symptoms seem to match https://github.com/cms-sw/cmssw/issues/32918

**Comment by tvami** [comment]
+alca

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by civanch** [comment]
+1

**Comment by clacaputo** [comment]
+reconstruction

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
