### PR TITLE
Remove CMS custom hacks for Oracle OCCI old C++ ABI compatibility BP 

### PR DESCRIPTION
**Pull request by mrodozov**
Backport of 26083 to 10_3

#### PR description:

See the title

#### PR validation:

Compiled the PR with this changes https://github.com/cms-sw/cmsdist/pull/4778 to see if something was missing.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4778

**Comment by fabiocos** [comment]
backport #26083

**Comment by fabiocos** [comment]
@ggovi this is the backport needed for the O2O test in MWGR1, could you please check it?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge 

@ggovi I understand that all O2O tests on your side are successful, please sign it for future reference

**Comment by ggovi** [comment]
+1

**Pull request merged**
