### PR TITLE
Run3-gex136A Handle compilation warnings in OnlineDB/CSCCondDB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Handle compilation warnings in OnlineDB/CSCCondDB

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type performance-improvements,csc

**Comment by tvami** [comment]
Hi @bsunanda thanks for this PR, would you mind squashing in the `code checks` commit into the other? Thanks

**Comment by tvami** [comment]
hi @bsunanda I'm ready to sign this, but please squash. Thanks!

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+db

**Pull request merged**
