### PR TITLE
DetectorDescription Clang tidy code-checks-all

### PR DESCRIPTION
**Pull request by ianna**
* Deleted members should be public
* Modernize deprecated headers
* Use nullptr [modernize-use-nullptr]
* Access DDRotation members via member functions
* Avoiding the copy if a local copy of the variable is never modified [performance-unnecessary-copy-initialization]
* Making a const reference if the variable is copy-constructed from a const reference but is only used as const reference [performance-unnecessary-copy-initialization]

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
