### PR TITLE
Backport 19058 to 9_2_0_patchX

### PR DESCRIPTION
**Pull request by DryRun**
As in title, backport #19058 to 9_2_0_patchX for online DQM (adds more protection against crashes due to calibration channels in QIE10/11 digi collections).

### CODE REVIEW

**Comment by dmitrijus** [comment]
@DryRun This needs to go into master first.
By the time it is merged, the DQM will move away from 9_2_0_patchX. Actually, we already did :)

**Comment by deguio** [comment]
@DryRun 
can this one be closed?

**Comment by jfernan2** [comment]
@DryRun Can this be finally closed?

**Comment by DryRun** [comment]
Hi all - yes, I think this PR isn't needed. I'll close it.

**Pull request closed without merging**
