### PR TITLE
Removed legacy b tagging using tight track selection from MiniAOD (90X)

### PR DESCRIPTION
**Pull request by ferencek**
90X backport of #17839

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
Same as #17839 in 91X

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
it looks technical.
Do you really need it in 90X?

**Comment by ferencek** [comment]
@slava77, given the intended usage of the 90X release cycle, I would agree with you that this PR is not really needed. Closing.

**Pull request closed without merging**
