### PR TITLE
Replace boost::array with std::array

### PR DESCRIPTION
**Pull request by Teemperor**

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@Teemperor I know that this is not the scope of this PR, but couldn't we use this opportunity to migrate the `boost::array` to `std::array` to drop the boost dependency? Or is there some algorithm used that requires it to be `boost::array`?

**Comment by ghellwig** [comment]
@Teemperor ping

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@Teemperor while looking more carefully, it might be that your initial version of this PR might have been the correct way to go because you are changing a CondFormat now...
@ggovi can you maybe comment if this is now some kind of (forbidden) schema evolution?

**Comment by ghellwig** [comment]
@ggovi could you comment on my question in https://github.com/cms-sw/cmssw/pull/21543#issuecomment-349895251, please?

**Comment by ggovi** [comment]
@Teemperor @ghellwig 
the replacement boost::array -> std::array is definitely a schema evolution. It can't be done, since we already have CMSSW releases which are potentially writers for the corresponding payloads.
@Teemperor I'm afraid you will have to change class name or stay with boost

**Comment by Teemperor** [comment]
No problem, that's then just adding the missing include. Let me revert to the old version.

**Comment by ghellwig** [comment]
@ggovi thanks for clarifying
@Teemperor sorry to have blocked this PR from being merged by my initial comment

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by ghellwig** [comment]
@Teemperor I believe, it would be good for the release notes, if you changed the title of this PR back to the original one.

**Pull request merged**
