### PR TITLE
Add customize configuration file to produce/keep a collection of part…

### PR DESCRIPTION
**Pull request by wulsin**
…icles simulated by GEANT combined with generated particles.

A similar PR was submitted for 7_1_X (needed for Run II GEN-SIM production):  https://github.com/cms-sw/cmssw/pull/11082

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by wulsin** [comment]
The motivation for using the GenPlusSimParticleProducer module for the simulation of exotic long-lived particles has been described in two presentations to the Simulation group:  
4 Apr 2014:  https://indico.cern.ch/event/310815/session/1/contribution/12/attachments/594838/818730/20140404_SimulationMtg.pdf
6 Mar 2015:  https://indico.cern.ch/event/377207/session/0/contribution/6/attachments/752124/1031818/20150306_SIMExotica.pdf

**Comment by davidlange6** [comment]
+1

**Pull request merged**
