### PR TITLE
Phase2-hgx335C Extend testing of the V16/V17 geometry versions of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend testing of the V16/V17 geometry versions of HGCal. These tests are not expected to produce changes in any existing scenarios

#### PR validation:

Use these testing tools to make more elaborate tests of HGCal geometries (V17 and V16)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@emanueleusai @srimanob Please approve this PR

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
