### PR TITLE
Update the time resoultion of GEM Digitization

### PR DESCRIPTION
**Pull request by woohyeonHeo**
##### Update on GEM Digitization simulation

- Changing the time resolution of GEMDigi to the more realistic value
- <https://indico.cern.ch/event/1471927/contributions/6197521/attachments/2959308/5210343/ME0_P2UG_Review.pdf> 
: Page 26 and 27

#### PR validation:

- The code format has applied with `scram build code-format` and tested with `scram build code-checks`
- The branch has tested with the following command
```
runTheMatrix.py -w upgrade -l 3211.0
```

### CODE REVIEW

**Comment by woohyeonHeo** [comment]
@watson-ij

**Comment by civanch** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
