### PR TITLE
small changes for performance optimization

### PR DESCRIPTION
**Pull request by ngrenz**
First PR of a work intended to optimize gradually the perfrormance of tracker validation code .
Outputs are supposed to be unchanged.
Any comments and suggestions are welcome -more optimizations will follow in the near future

### CODE REVIEW

**Comment by ngrenz** [comment]
@boudoul  FYI

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
IIUC, most of the changed loops could be expressed also using the (C++11) range-for (index/iterator is used only to retrieve an element without any fancy games), which is guaranteed to give the best performance. Although probably not better than what you wrote already, but IMHO it would be clearer to read (and write).

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
