### PR TITLE
Bug fixes to PU jet ID variables

### PR DESCRIPTION
**Pull request by ahinzmann**
Three bug fixes to the definition of the PU jet ID variables. Two affect the behavior on AOD+MiniAOD, and one affects the behavior on MiniAOD (particularly if used with non-standard vertices like in di-photon final states).

The fixes come together with a new training including the fixed definitions. The training has been prepared and will be linked to this PR once uploaded.

### CODE REVIEW

**Comment by slava77** [comment]
@ahinzmann 
we wait for training and then test/merge this.
Does this sound good?

**Comment by ahinzmann** [comment]
ok!

**Comment by cvuosalo** [comment]
@ahinzmann: Is the new training ready yet?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15119 063f6d61f4fdb440216badb99cc68161779290ad

Bug fixes to pile-up jet ID quantities. There should be no change in upstream RECO quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-07-14-1100 show only small changes in the PU jet ID MVA output, as would be expected. An example from workflow 136.731_RunSinglePh2016B is shown below.


mva

**Comment by davidlange6** [comment]
+1

**Pull request merged**
