### PR TITLE
ME0TriggerPseudoBuilder  mistook GEM strip pitch unit as radiu and this commit is to fix it

### PR DESCRIPTION
**Pull request by tahuang1991**
#### PR description:
pitch() from GEM geometry returns the strip pitch in cm and was supposed to be converted into radius before it is compared with deltaphi. JiaFu found this bug and  this PR is to fix this bug in  L1Trigger/ME0Trigger/src/ME0TriggerPseudoBuilder.cc

This PR is independent from Sven's previous PR to update Me0 trigger built from GEM trigger pads.   This PR is to fix a old bug in  ME0 pseudo-triggers  which is actually used by EMTF .

#### PR validation:
I ran test with step 20034.0 and everything seems right .   
Summary from test 20034.0:
1 1 1 1 tests passed, 0 0 0 0 failed

FYI: @jshlee @dildick  @rekovic @jiafulow

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by dildick** [comment]
@tahuang1991 While you are making this change, I suggest that you hook up the corresponding producer to the `me0TriggerPseudoDigiTask` task as `me0TriggerConvertedSegments` - to avoid a naming clash. So the new task would look like:

```
me0TriggerPseudoDigiTask = cms.Task(
    simMuonME0PseudoReDigisCoarse,
    me0RecHitsCoarse,
    me0TriggerPseudoDigis,
    me0TriggerConvertedSegments
)
```

**Comment by rekovic** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
