### PR TITLE
Revert "PPS: rename directories with misleading names"

### PR DESCRIPTION
**Pull request by silviodonato**
Reverts cms-sw/cmssw#29037

### CODE REVIEW

**Comment by perrotta** [comment]
@silviodonato : are you planning to revert #29093?

As far as I can see, there are a few unit tests which fail with some related message, e.g.:
```
&gt; Warning in &lt;TInterpreter::ReadRootmapFile&gt;: class  PPSTimingCalibration found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
&gt; Warning in &lt;TInterpreter::ReadRootmapFile&gt;: class  PPSTimingCalibration::Key found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
&gt; Warning in &lt;TInterpreter::ReadRootmapFile&gt;: class  pair&lt;PPSTimingCalibration::Key,pair&lt;double,double&gt; &gt; found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
```

The CondFormats/CTPPSReadoutObjects package does not exist any more after that PR, and so should its library.

The issue must be related to what described by @Dr15Jones in https://github.com/cms-sw/cmssw/pull/29037#issuecomment-593979957

**Comment by mrodozov** [comment]
is this related to the failing tests ?

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
@perrotta, yes, I reverted #29037 because there were many failures in the IB tests.
I would postpone #29037 after pre4.

**Comment by perrotta** [comment]
> @perrotta, yes, I reverted #29037 because there were many failures in the IB tests.
> I would postpone #29037 after pre4.

You will postpone the same issue to pre5...

**Comment by silviodonato** [comment]
> > @perrotta, yes, I reverted #29037 because there were many failures in the IB tests.
> > I would postpone #29037 after pre4.
> 
> You will postpone the same issue to pre5...

I prefer to have more time to understand and fix the problem, without the pressing of the pre4 deadline.

**Comment by Dr15Jones** [comment]
@pcanal could you comment about the new ROOT warning? Our guess is ROOT is checking all directories listed in LD_LIBRARY_PATH for root map files even if a given library is found multiple directories in the environment variable.

**Comment by pcanal** [comment]
Yes, ROOT looks in all directories in LD_LIBRARY_PATH for rootmap files.

> even if a given library is found multiple directories in the environment variable.

There seems to be protection against that in the code ... or more exactly the duplicate avoidance is base in the rootmap filename.

Note that in the example above it does complains (3 different time) about 2 distincts libraries.

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
