### PR TITLE
L1TCalo Layer 1 unpacker guard against no FED data in event

### PR DESCRIPTION
**Pull request by nsmith-**
Unbelieveably this hasn't been an issue since Layer1 has been in every run so far.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
@davidlange6 this has been in 81x for 5 days and is needed critically online... can we merge this guy to?

**Comment by davidlange6** [comment]
+1

**Comment by mulhearn** [comment]
Thanks!

**Pull request merged**
