### PR TITLE
HGCal DB Geometry Reader

### PR DESCRIPTION
**Pull request by ianna**
- Read PHGCal geometry from DB
- Update DB geometry writer configuration for 2023
- Clean up DB geometry test
- Migrate test to thread-safe ED Analyzer

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@ggovi - could you, please, sign it?

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
