### PR TITLE
New L1REPACK workflow for DATA with simulation of TPs (81x) try3

### PR DESCRIPTION
**Pull request by rekovic**
Rebased and replace for #15182.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
tests fail for a missing file:

Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/MINIAODSIM/PU25ns_80X_mcRun2_asymptotic_v4-v1/10000/A65CD249-BFDA-E511-813A-0025905A6066.root'

@davidlt
who's responsible of transferring back the files needed by the tests ?

**Comment by franzoni** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by franzoni** [comment]
study equivalente to what done for https://github.com/cms-sw/cmssw/pull/15117 ongoing (delays due to das issues), will close and post here in the coming days

**Comment by franzoni** [comment]
We've carried out the same study already done last week for 80x, see  https://github.com/cms-sw/cmssw/pull/15117#issuecomment-232073749 

. We've managed to run the relval: both
step1: L1REPACK:FullSimTP+HLT and
step2: L1REPACK:FullSimTP+RECO+DQM
run ok over 100 events

In the 1d histogram, the yellow single histogram is TP's spectrum from HCAL DQM sequence and TP's from L1REPACK:FullSimTP; the coinciding green curves are the TP's emulated by HCAL DQM (dark curve) w/ the HCAL L1 object updated to recover loss of response and the TP's from the L1REPACK:FullSimTP sequence. 
This proves that L1REPACK:FullSimTP emulates the HCAL primitives like the standard existing sequences.
 
tp-spectrum-yellooldcond-greennewconditionsstandardandvlad


As a proof of sanity of the emulation + HCAL DMQ chain, two two maps show changes induced by the updated HCAL L1 object: primitives are added in the high |eta| region (the first map is emulation with the same L1 object as used online, the second with the update to recover response)

map-tpetcutemul-reference

map-tpetcutemul-updated-vladim pngir p

**Comment by franzoni** [comment]
@fabozzi @rekovic

**Comment by franzoni** [comment]
+1

**Pull request merged**
