### PR TITLE
Avoid unnecessary exceptions in validation

### PR DESCRIPTION
**Pull request by Dr15Jones**
Switch from calling AssociationMap::operator[] which can throw an
exception if the key is missing to calling find() which will not
throw.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I found these while trying to debug a job. They were preventing me from being able to easily use `catch throw` in the debugger.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
