### PR TITLE
Partially fix CLCT position bias after CCLUT (CCLUT-8)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In recent studies, a bias was found in the 1/2-strip, 1/4-strip and 1/8-strip positions of about 0.17. The bias has now been eliminated for the 1/2 position. A bias of < 0.1 strip remains for the 1/4 and 1/8 strip positions (this may be due to how we define the 1/n-strip position: center or middle). New LUTs provided here: https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/3.

#### PR validation:

Tested with ```/RelValSingleMuPt10/CMSSW_11_0_0-110X_mcRun4_realistic_v2_2026D49noPU-v1/GEN-SIM-DIGI-RAW``` and ```/RelValSingleMuFlatPt2To100/CMSSW_11_0_0-110X_mcRun4_realistic_v2_2026D49noPU-v1/GEN-SIM-DIGI-RAW```

Most recent presentation summarizing the results https://indico.cern.ch/event/965106/contributions/4062917/attachments/2122267/3572271/CSCResolutionNewPatterns_SD_20201014.pdf

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991 Please pick-up the new .mem files from https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives.

### CODE REVIEW

**Comment by dildick** [comment]
A few validation plots (not for publication):
 
Res_CSCCLCT_poscomparison_
Res_CSCCLCT_poscomparison_ME11
Res_CSCCLCT_poscomparison_ME12
Res_CSCCLCT_poscomparison_ME13
Res_CSCCLCT_poscomparison_ME21
Res_CSCCLCT_poscomparison_ME22
Res_CSCCLCT_poscomparison_ME31
Res_CSCCLCT_poscomparison_ME32
Res_CSCCLCT_poscomparison_ME41
Res_CSCCLCT_poscomparison_ME42

**Comment by dildick** [comment]
The CCLUT algorithm is not enabled yet, so there shouldn't be changes in any of the workflows.

**Comment by dildick** [comment]
I had a closer look at the CLCT bending resolution. Preliminary plots (not for publication) are attached. 

Res_CSCCLCT_bendcomparison_ME11
Res_CSCCLCT_bendcomparison_ME12
Res_CSCCLCT_bendcomparison_ME13
Res_CSCCLCT_bendcomparison_ME21
Res_CSCCLCT_bendcomparison_ME22
Res_CSCCLCT_bendcomparison_ME31
Res_CSCCLCT_bendcomparison_ME32
Res_CSCCLCT_bendcomparison_ME41
Res_CSCCLCT_bendcomparison_ME42

It seems that for the position LUT the ```ceil```. For the bending LUT ```floor``` seems more appropriate...

Anyway it would be good to check the bending resolutions for highly displaced muons and see if it looks similar.

**Comment by dildick** [comment]
For non-ME1/1 there is an bending bias of about -0.1, which I have yet to sort out.

**Comment by dildick** [comment]
Look-up tables in https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/3 were updated with the correct slope definition.

**Comment by dildick** [comment]
I also ran a test to see how well the CCLUT algorithm would interface with the Run-2 EMTF. 

Run-2 CSC LCTs + Run-2 EMTF

Eff_EMTF_eta_Pt20_
Eff_EMTF_phi_Pt20_
Eff_EMTF_pt_Pt20_
Eff_EMTF2_eta_Pt20_

Run-3 CSC LCTs + Run-2 EMTF

Eff_EMTF_eta_Pt20_
Eff_EMTF_phi_Pt20_
Eff_EMTF_pt_Pt20_
Eff_EMTF2_eta_Pt20_

As can be seen, without modifcations (update the pT assignment), the EMTF may take a 5 to 20% hit in efficiency.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by rekovic** [comment]
@dildick 
> As can be seen, without modifcations (update the pT assignment) the EMTF takes a 5 to 20% hit in efficiency, depending on the pT cut. The track-building efficiency (before pT assignment) seems unaffected by the CCLUT algorithm.

This is only seen your offline study (plots above), no changes in the current EMTF is expected, correct ?

What about the PR #31631 which also touches the file ` L1Trigger/CSCTriggerPrimitives/src/CSCCathodeLCTProcessor.cc`
(and a test expert like `L1Trigger/CSCTriggerPrimitives/test/macros/CCLUTLinearFitWriter.cpp`)?  Can these two PRs be made orthogonal?

**Comment by dildick** [comment]
@rekovic To your first question: correct. The CCLUT algorithm is not enabled yet. This analysis was done by turning it on.

In #31631 I merge `use_run3_patterns_` and `use_comparator_codes_` into `runCCLUT_` and `alctClctOffset_` is made a constant in `CSCConstants.h`. #31631 Should does not change algorithms in CSC.

**Comment by civanch** [comment]
please test

**Comment by jfernan2** [comment]
Hi @dildick I see no changes in the Validation plots, is that expected?

**Comment by dildick** [comment]
@jfernan2 Yes, we have yet to turn on the CCLUT algorithm.

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
@civanch Do you have any questions?

**Comment by dildick** [comment]
@rekovic @jmduarte Could you sign off, please? Thanks.

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
@rekovic Can you please sign off?

**Comment by dildick** [comment]
@silviodonato Can this be merged?

**Comment by silviodonato** [comment]
do you have any comments ? @cms-sw/l1-l2

**Comment by dildick** [comment]
@silviodonato @rekovic Please sign.

**Comment by silviodonato** [comment]
@rekovic this PR is ready for 13 days and affects mainly L1T.
@dildick I will include this in the pre-release

**Comment by silviodonato** [comment]
urgent

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by dildick** [comment]
@rekovic @silviodonato Thanks.

**Pull request merged**
