### PR TITLE
Removed FwkJob category from MessageLogger config

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The FwkJob category has not been supported for many years.
These changes are needed to be able to remove the default setup of FwkJob from within MessageLogger itself. 

Other uses of FwkJob in CMSSW declare the category explicitly so are not dependent upon a change to MessageLogger.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please test
(to get rid of the differences in reco outputs likely due to the extra commits tested together with this purely technical pull request)

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- technical for reco
- jenkins tests pass

**Comment by christopheralanwest** [comment]
+alca

**Comment by silviodonato** [comment]
merge

**Pull request merged**
