### PR TITLE
HcalDQM - esConsumes Migration

### PR DESCRIPTION
**Pull request by lwang046**
PR description:

Replacement of several remaining obsolete ESHandle's with ESGetToken's in Hcal/DQMCommon and Hcal/DQMTasks packages
Related issue: #31061

PR validation:

runTheMatrix.py -l limited -i all --ibeos test okay

### CODE REVIEW

**Comment by abdoulline** [comment]
👍🏻
Minor point:  it seems that there are several redundant semicolon lines, like this one: 
https://github.com/cms-sw/cmssw/pull/33816/files#diff-f6ef06253a88236e9ec2fa6f12421f7dc4d2f0c59957386341979897abbed452R25

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
