### PR TITLE
[BeamSpot] update cfg to rerun track and PV fitting before BS determination

### PR DESCRIPTION
**Pull request by rmanzoni**
back port of 
https://github.com/cms-sw/cmssw/pull/9560

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Jenkins comparisons have been queued for 7 hours. Let's try to run the tests again.

**Comment by cvuosalo** [comment]
@nclopezo, @degano: The Jenkins comparisons for this PR have been stuck in Queued state for two consecutive tests. Could you please check what is going wrong?

**Comment by mmusich** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #9561 9784fabf2ab857ff0a34eac7988c6856f66e7f41

Updating beam spot config to rerun track and PV fitting before beam spot determination. The modified config is separate from standard sequences. #9561, the 75X version of this PR, has already been approved and merged.

The code changes are satisfactory. Jenkins tests show no problems, but the comparisons did not complete. However, the same code changes were already tested in #9561 without problems, so the repeating the full Jenkins tests again is not necessary.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
