### PR TITLE
Create Bs_JpsiPhi_V3.dec

### PR DESCRIPTION
**Pull request by heppye**
Add decay file for BPH. A cross PAG request from HIN.

### CODE REVIEW

**Comment by taweiXcms** [comment]
This file is needed for Heavy ion Bs meson PbPb sample.

**Comment by mandrenguyen** [comment]
@bendavid, @vciulli, @covarell
Can you have a look and sign, so this can go in 755?

**Comment by covarell** [comment]
In what does this differ from V1 and V2?

**Comment by mandrenguyen** [comment]
@taweiXcms 
Can you reply?

**Comment by taweiXcms** [comment]
Hi,

V3 has a better description of angular distribution.
This is the EvtGen file used and suggested by the BPH group for Pythia8 generation.
While v2 is suitable for Pythia6.

Ta-Wei
On Nov 3, 2015, at 3:30 PM, Roberto Covarelli <notifications@github.com<mailto:notifications@github.com>> wrote:


In what does this differ from V1 and V2?

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
are we planning both pythia6 and pythia8 production in this or any other release? If not, we should rely on our version control software (git) to revise existing files as opposed to adding a new file.

**Comment by davidlange6** [comment]
@heppye - ping

**Comment by heppye** [comment]
@davidlange6 , based on the communication with @taweiXcms, HIN would like to switch to pythia8  and  Bs_JpsiPhi_V3.dec is necessary for their study. For now, this is the only additional decay file that HIN needed. For the future version control, may HIN MC contact comment more. Please merge this decay file first if possible.

**Pull request merged**
