### PR TITLE
add historgrams with variable size bins

### PR DESCRIPTION
**Pull request by popovvp**

### CODE REVIEW

**Comment by deguio** [comment]
@vanbesien

**Comment by vanbesien** [comment]
@popovvp 
Can you check:
https://github.com/popovvp/cmssw/blob/74xVB/DQM/CastorMonitor/src/CastorRecHitMonitor.cc#L70

In the for loop j goes from 1 to 18 (incl).
You are giving numbers 2 to 19 (incl) as indexes to array yErh, which is an array of size 19, meaning that the available indexes go from 0 to 18 (incl).
This is probably not what you want.
(Also, please keep the code clean and remove commented code lines)

**Comment by popovvp** [comment]
that is correct - array must be for one bin more (nbins+1)

**Comment by vanbesien** [comment]
@popovvp 
Hi, thanks for fixing the for-loop. It makes much more sense now.
I see that you also replaced "hallchan = ibooker.book1D(s,s,22000,-20000.,200000.);" by a new version with a much more normal amount of bins. Very good.

As far as I can see, now there is only one histogram left with an unreasonably high amount of bins, namely the "hBunchOcc = ibooker.bookProfile(s,s,4000,0,4000, 100,0,1.e10,"");" here:
https://github.com/popovvp/cmssw/blob/9f9d3e5deb6c3009c233c8f4c8234084f7f9cd60/DQM/CastorMonitor/src/CastorDigiMonitor.cc#L58

**Comment by deguio** [comment]
-1
please continue any discussion in #7783 
rejecting for 74

**Pull request closed without merging**
