### PR TITLE
Remove some more printouts from RECO step

### PR DESCRIPTION
**Pull request by davidlange6**
Some notes:

-- I'm not sure why CMS has two copies of ObjectViewCleaner.  They seem identical, presumably the one in Validation/RecoTau should be removed
-- The beam spot fitter change reflects that if "improve" is called and does not find a new minimum, it returns status=4 (which is then turned into status=4000 by the time the exit of TH1F::Fit is called

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@degano, @nclopezo: Jenkins has been running for 12 hours. When will there be results?

**Comment by nclopezo** [comment]
The tests were being affecter by the issue discussed here:
 https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3169.html

I restarted them with the today's IB.

**Comment by civanch** [comment]
+1

**Comment by diguida** [comment]
+1
`LogWarning` downgraded to `LogInfo`

**Comment by deguio** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #8010 dcc47f7bf784b17f6c75caf03011c0ee216fcab8

This PR eliminates some unnecessary diagnostic outputs.

The code changes are satisfactory. Jenkins [tests] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8010/6365/summary.html) against baseline CMSSW_7_4_X_2015-03-03-0200 are OK and confirm the reduction in the unnedded warning messages.

**Comment by davidlange6** [comment]
the bot should notice my new commit...

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by deguio** [comment]
+1

**Comment by diguida** [comment]
+1
no changes w.r.t. previous signature

**Comment by cvuosalo** [comment]
+1

For #8010 24fab1f86598182e4038405a12ac138721a216e7

Very tiny change since previous Reco approval. New Jenkins tests are OK.

**Comment by civanch** [comment]
+1

**Pull request merged**
