### PR TITLE
Migrate module config in EgammaAnalysis to use default cfipython

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. 

In this PR, 2 files were changed.  
        modified:   EgammaAnalysis/ElectronTools/python/calibratedElectrons_cfi.py
        modified:   EgammaAnalysis/ElectronTools/python/calibratedPatElectrons_cfi.py

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Similar to other similar improvements of the reco module configs rought ahead in this campaign
- In practice here it only removes the duplicate definitions of `recHitCollectionEB` and `recHitCollectionEE`
- I assume @cms-sw/analysis-l2 agrees with this technical update

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
