### PR TITLE
[10.3.X] [Change GTs] Update L1T + change 2018MC trackerAl + DynInEff

### PR DESCRIPTION
**Pull request by lpernie**
###  2018 MC
.   [103X_upgrade2018_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_design_v6/103X_upgrade2018_design_v1)
.  L1T menu
.   [103X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v9/103X_upgrade2018_realistic_v2)
.  L1T menu
.  Tracker Alignment scenario
.   [103X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v8/103X_upgrade2018cosmics_realistic_deco_v3)
.  L1T menu
.  Tracker Alignment scenario

###  PostLS2 MC
.   [103X_postLS2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_postLS2_design_v5/103X_postLS2_design_v1)
.  L1T menu
.   [103X_postLS2_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_postLS2_realistic_v5/103X_postLS2_realistic_v1)
.  L1T menu

###  2023 MC
.   [103X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2023_realistic_v7/103X_upgrade2023_realistic_v1)
.  L1T menu

###  Data
.  [103X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_relval_v4/103X_dataRun2_relval_v2)
.  L1T menu
.   [103X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_HLT_relval_v1/103X_dataRun2_HLT_relval_v1)
.  L1T menu

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie @boudoul as far as I understand this update of GT does not contain the tracker alignment yet, it just affects the L1T

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Hi @fabiocos , I just added also the tracker geometry for 2018 MC scenario.
I will snow make the backport in 10.2.X

**Comment by mmusich** [comment]
Hi @lpernie, 
based on the GT difference, this PR is also changing the `SiPixelDynamicInefficiency` payload:
```
$ conddb diff 103X_upgrade2018_realistic_v2 102X_upgrade2018_realistic_v9
[2018-08-06 17:55:44,010] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Record                         Label  pro::103X_upgrade2018_realistic_v2 Tag  pro::102X_upgrade2018_realistic_v9 Tag     
-----------------------------  -----  --------------------------------------  -----------------------------------------  
L1TUtmTriggerMenuRcd           -      L1Menu_Collisions2018_v2_0_0-d1_xml     L1Menu_Collisions2018_v1_0_0-d1_xml        
SiPixelDynamicInefficiencyRcd  -      SiPixelDynamicInefficiency_PhaseI_v6    SiPixelDynamicInefficiency_PhaseI_v4       
TrackerAlignmentRcd            -      TrackerAlignment_MC2018_v1              TrackerAlignment_Upgrade2017_realistic_v2  
```
since the old version of the dynamic inefficiency payload is what actually made 10_2_0 fail (see details at: https://indico.cern.ch/event/747635/contributions/3092001/attachments/1696718/2731311/follow_up_10_2_0.pdf), can it be made explicit that this was changed in the PR description (and in the backport as well)?
Thanks,
M.

**Comment by lpernie** [comment]
Hello @mmusich , sure I will make this clear. I will work on the description of both PRs now.
Btw, maybe you can clarify this to me: this geometry should go into 102X_upgrade2018cosmics_realistic_Queue too?
But I just saw that there there are different Pixel conditions.

**Comment by mmusich** [comment]
Hi Luca, the new Tracker Alignment should be applied to every 2018 scenario.
About the `SiPixelDynamicInefficiency` I think that for consistency it would be better to keep the same tag between cosmics and collisions, but I don't think it can actually play a role (at the cosmics occupancies).
@tvami @tsusa please comment.

**Comment by tvami** [comment]
Hi Luca, I can confirm what Marco says: the DynEff payload does not have significant effect on MC, but for consistency reasons we could include it.

**Comment by lpernie** [comment]
@mmusich now the PR should be completed

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
please test workflow 136.7722,136.7952,136.8521,1325.6,1325.8,1325.9,1329.1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
