### PR TITLE
bsunanda:Run2-hcx33 Testing HGCal Geometry and Topology

### PR DESCRIPTION
**Pull request by bsunanda**
Tester for HGCal geometry and topology

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@bsunanda please rebase

**Comment by bsunanda** [comment]
Done that
________________________________

**Comment by bsunanda** [comment]
Is it merged? I am not so sure about that.

**Comment by bsunanda** [comment]
I rebased the PR

**Comment by bsunanda** [comment]
Hi Yana - can you please check why this PR is closed. I have updated the PR by rebasing it. I expect it to be merged soon. Regards      Sunanda
________________________________
From: Sunanda Banerjee
Sent: 30 September 2015 16:09
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-hcx33 Testing HGCal Geometry and Topology (#11556)

Done that
________________________________

**Comment by lgray** [comment]
@bsunanda You seem to have accidentally closed this PR, perhaps clicking the wrong button. Github won't let you reopen a PR if you rebase it while it is closed. Please submit a new PR.

**Pull request closed without merging**
