### PR TITLE
Convert PFEGAlgo to use a GlobalCache + GBRForest (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10410

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Apologies, this will fail until #10370 is merged into CMSSW 74X.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test
Running on the IBs with all PRs this depends on integrated.

**Comment by cvuosalo** [comment]
+1

For #10474 c984b5e1425a91287dac530532ff5be361bebd15

Converting PFEGAlgo to use GlobalCache + GBRForest to reduce memory use. There should be no significant change in monitored quantities. This PR is a 74X backport of #10410, which has already been merged into 76X.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-07-30-2300 show no significant differences, as expected. Errors in the Jenkins tests are not related to this PR. Memory use reduction was verified in the review of #10410.

**Comment by lgray** [comment]
@davidlange6 reminder that this needs to go into 74X 
Pertinent 76X and 75X relvals check out for relevant quantities.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
