### PR TITLE
Prep work for the Run-3 GEM-CSC integrated local trigger (III)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

More prep work for the Run-3 GEM-CSC integrated local trigger. Follow-up of https://github.com/cms-sw/cmssw/pull/33617
* Move CCLUT into separate class `ComparatorCodeLUT`
* Separate class to match GEM clusters to CSC TPs `CSCGEMMatcher` (at the moment it's all contained in the TMB code)
* Revert last piece of #29562 in the anode processor 
* Add more useful features in the `GEMInternalCluster`
* Small bugfix for the CCLUT algorithm where rarely the half-strip number was assigned 65535 or some other unphysical value (see example below). 
```
%MSG-e LCTQualityControl:   CSCTriggerPrimitivesProducer:cscTriggerPrimitiveDigis 02-Jun-2021 15:56:23 CDT  Run: 341761 Event: 47
CSCCLCTDigi with invalid half-strip: 65535; allowed [0, 31]
%MSG
%MSG-e LCTQualityControl:   CSCTriggerPrimitivesProducer:cscTriggerPrimitiveDigis 02-Jun-2021 15:56:23 CDT  Run: 341761 Event: 47
Invalid stub in  E:1 S:1 R:1 C:2 L:0 (1 errors):
CSC CLCT #1: Valid = 1 Quality = 5 Pattern = 3 StripType = 1 Bend = 1 Strip = 65535 KeyStrip = 31 CFEB = 1 BX = 7 Comp Code 3668
%MSG
```

#### PR validation:

Tested on 10k events taken with the B904 test-stand. There should be no changes to workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by dildick** [comment]
A few validation plots with B904 data: 

Screen Shot 2021-06-03 at 11 31 54 PM
Screen Shot 2021-06-03 at 11 32 01 PM
Screen Shot 2021-06-03 at 11 32 07 PM
Screen Shot 2021-06-03 at 11 32 16 PM
Screen Shot 2021-06-03 at 11 32 25 PM
Screen Shot 2021-06-03 at 11 32 31 PM
Screen Shot 2021-06-03 at 11 32 38 PM
Screen Shot 2021-06-03 at 11 32 44 PM
Screen Shot 2021-06-03 at 11 32 52 PM
Screen Shot 2021-06-03 at 11 32 59 PM
Screen Shot 2021-06-03 at 11 33 05 PM
Screen Shot 2021-06-03 at 11 33 11 PM

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
Full PDF here: 
[CSC_dataVsEmul_B904_Cosmic_Run_210531_165323.pdf](https://github.com/cms-sw/cmssw/files/6599761/CSC_dataVsEmul_B904_Cosmic_Run_210531_165323.pdf)

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@dildick , rebase is needed

**Comment by cecilecaillol** [comment]
+l1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
