### PR TITLE
[14_1_X] Add dedxLikelihood to 2023 UPC rereco

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46401

@mandrenguyen 

#### PR validation:

Tested with relvals 180,180.1,181,181.1,141.901,142.901,142.903

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
