### PR TITLE
allow `TriggerResultsFilter` to throw for invalid `HLTPathStatus` patterns [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #39044

#### PR description:

Re-phrasing from https://github.com/cms-sw/cmssw/pull/39044#issuecomment-1225387237:

> - this PR updates `TriggerResultsFilter` to throw an exception as expected (if `throw=True`) if `usePathStatus=True` and the specified trigger-results patterns have no matches;
> - in addition, if `throw=True`, `TriggerResultsFilter` will now throw an exception if the parsing of the trigger-results expression fails (up to now, this only led to a warning).

More details on this update can be found in #39044.

#### PR validation:

Relies on the validation done for the original PR.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39044

Backport of a (small) bugfix to the release cycle currently used for online operations. It is expected to have no impact on any current production use cases.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
