### PR TITLE
Fix `BeamSpotAnalyzer::fillDescriptions`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

As reported by @francescobrivio, PR https://github.com/cms-sw/cmssw/pull/35236 introduced a wrong type for the parameter `BSAnalyzerParameters` (which should be a `PSet` and non a `VPSet`).
This is fixed in this PR, together with completing the rest of descriptions coming from the `BeamFitter` and `PVFitter` classes.
I profit of this PR to introduce a unit test to check the functionality of the analyzer.

#### PR validation:

Relies on the unit tests provided in this PR

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
Sorry, I'm not sure what we expect to see in the unit test
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2418d1/22710/unitTests/src/RecoVertex/BeamSpotProducer/test/testBeamSpotAnalyzer/testing.log

```
 Total number of events processed: 0
-------------------------------------
%MSG-w BeamFitter: 
No event read! No Fitting!
%MSG
[BeamSpotAnalyzer] beamfit fails !!!
```

is this expected?

**Comment by mmusich** [comment]
> is this expected?

of course it is....

https://github.com/cms-sw/cmssw/blob/83ae0ba51edf6cb43c0cb16771bd748c2770d86f/RecoVertex/BeamSpotProducer/test/testBeamSpotAnalyzer.cc#L18

**Comment by tvami** [comment]
+alca
 * unit test results as expected
 * Jenkins diffs show MsgLogger only
 * code change in line w description

**Comment by jpata** [comment]
+reconstruction
- technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
