### PR TITLE
[13_3_X] Add use of unsubtracted jets in RecoBTag info producers

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

backport of https://github.com/cms-sw/cmssw/pull/44422

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44422

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
No change to reco

**Comment by antoniovilela** [comment]
hold
   - To avoid accidentally merging it, before applying fix from https://github.com/cms-sw/cmssw/pull/44591.

**Comment by mmusich** [comment]
+hlt
   * in this cycle the new parameter `unsubjet_map` of `DeepBoostedJetTagInfoProducer` has never been defined as `untracked`.

**Comment by mandrenguyen** [comment]
+1 
resign

**Comment by antoniovilela** [comment]
unhold

**Comment by rappoccio** [comment]
+1

**Pull request merged**
