### PR TITLE
remove phase2 tk customization functions

### PR DESCRIPTION
**Pull request by kpedro88**
Now that #16181 is merged, we can finally get rid of customization functions for Phase2. The last remaining piece was some geometry conditions, which I have moved into the appropriate geometry cffs.

Tested with 20024.0 and 22424.0, no crashes observed. There should be no changes in the comparison as far as I can tell.

attn: @ebrondol, @boudoul, @ianna

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
No changes in the comparisons

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
@kpedro88 , looks like this Pr broke the unit test https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc530/CMSSW_8_1_X_2016-10-30-2300/unitTestLogs/RecoLocalCalo/HGCalRecProducers

**Comment by kpedro88** [comment]
@smuzaffar sorry, will fix

**Comment by slava77** [comment]
On 11/3/16 7:10 AM, Kevin Pedro wrote:
> @smuzaffar <https://github.com/smuzaffar> sorry, will fix

I think Sunanda cleaned it up already in
https://github.com/cms-sw/cmssw/pull/16419/files#diff-a785d2fb837d9291229504778244b4b8

**Comment by smuzaffar** [comment]
thanks for find this out, looks good for 23h IB

**Comment by smuzaffar** [comment]
@davidlange6 , looks like a bug in dependency generation script. It is ignoring .py files if they are not under python directory
https://github.com/cms-sw/cmssw-config/blob/master/SCRAM/findDependencies.pl#L126
that is why RecoLocalCalo/HGCalRecProducers package was not checked out when this PR was tested. I am going to update the script to look for any .py file under src and cfipython tree.

**Comment by kpedro88** [comment]
@smuzaffar I had previously noticed that behavior when checking for imports of `Configuration.StandardSequences.Eras`. It looks like your fix will only pick up unit tests and other such centrally used configs, which is good. I hope it will continue to ignore the hundreds of unmaintained cmsRun config files in test directories scattered throughout CMSSW...

**Comment by smuzaffar** [comment]
ah OK, finding only python files used by unit test is not easy to find (though not impossible). I will see if I can improve the logic.

**Comment by kpedro88** [comment]
It might be useful to really find all python files as a non-default option, but I think in general we should ignore the various cmsRun configs that people add and then forget.

**Comment by smuzaffar** [comment]
agreed

**Pull request merged**
