### PR TITLE
Remove OrPairSelector.h

### PR DESCRIPTION
**Pull request by Teemperor**
This file isn't valid C++ because it contains a typo, as line 13 ends
with ";)" even though it should end with ");". As it was never
modified since it was imported to git and is broken since then,
I think we can safely remove it.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@Teemperor 
please fix the syntax and recover the file.
Thank you.

**Comment by slava77** [comment]
-1

**Comment by davidlange6** [comment]
hi @slava77 - why? its broken since 3+ years after all.

**Comment by slava77** [comment]
On 6/21/17 12:52 AM, David Lange wrote:
> hi @slava77 <https://github.com/slava77> - why? its broken since 3+
> years after all.

It's a part of the suite of selectors.
All of them should be removed if this one is removed.
A simpler option is to fix the typo in this one, which is why I
suggested it.

**Comment by Teemperor** [comment]
Yeah, let's just fix the typo. I made a new PR #19394 for this (because I can't rename the branch of this PR). Thanks!

**Pull request closed without merging**
