### PR TITLE
Re-introduce the new HCAL method 3 response correction

### PR DESCRIPTION
**Pull request by fwyzard**
Re-introduce the new HCAL response for Method 3 in CMSSW 8.0.x, in order to better match Method 2.

### CODE REVIEW

**Comment by fwyzard** [comment]
This reverts dff7512bdb579a12d960593ad291ddee29d46a95 .

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
