### PR TITLE
Clean up ME0MuonTrackCollProducer

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

While reviewing #31190  some possible further cleaning was pointed out in https://github.com/cms-sw/cmssw/pull/31190#issuecomment-677478367
Before forgetting about it, here are the simplifications proposed for the code (plus a few additional ones)
 
Of course, we wish that some heavier cleaning with the removal from the CMSSW release of all unused ME0 related files can be done at some point: @jshlee @watson-ij @ArnabPurohit @trocino

#### PR validation:

It compiles
No changes expected

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Some cleanup of a plugin only used in a MuonIdentification test script
- The files have also been moved so that there is no dependence any more of CommonTools/RecoAlgos to RecoMuon/MuonIdentification
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Comment by trocino** [comment]
> Of course, we wish that some heavier cleaning with the removal from the CMSSW release of all unused ME0 related files can be done at some point: @jshlee @watson-ij @ArnabPurohit @trocino

Sorry for coming back to this a bit late... We are investigating with the GEM community about the use of this ME0-related code, especially ME0MuonSelector of PR  #31190 . It may be used — even just in private code — for Phase-II studies. Anyway we will consider how to clean it up, e.g. by merging the ME0MuonSelector with the standard MuonSelectors in DataFormats/MuonReco.

**Comment by perrotta** [comment]
> > Of course, we wish that some heavier cleaning with the removal from the CMSSW release of all unused ME0 related files can be done at some point: @jshlee @watson-ij @ArnabPurohit @trocino
> 
> Sorry for coming back to this a bit late... We are investigating with the GEM community about the use of this ME0-related code, especially ME0MuonSelector of PR #31190 . It may be used — even just in private code — for Phase-II studies. Anyway we will consider how to clean it up, e.g. by merging the ME0MuonSelector with the standard MuonSelectors in DataFormats/MuonReco.

Thank you Daniele @trocino : I have opened issue #31424 to keep track of it

**Comment by makortel** [comment]
@smuzaffar The duplicate dictionary checker is now complaining that `ME0MuonTrackCollProducer` is found in two libraries
```
pluginCommonToolsRecoAlgos_plugins.so
pluginRecoMuonMuonIdentificationPlugins.so
```
https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc7_amd64_gcc820/www/thu/11.2-thu-11/CMSSW_11_2_X_2020-09-10-1100/testLogs/dupDict-edmPD.log
I assume this warning will disappear once we get a full build (only patch builds since the merge of this PR for slc7_amd64_gcc820).

But should a file being moved out from a package result that package be built in a patch build?

**Comment by smuzaffar** [comment]
@makortel , correct , full build should fix this and yes the package from which the file was removed is rebuild in the patch release. But as the dict checking script reads .edmplugincache files (both from patch and full release) to get the list of dicts ( https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py#L249 ) that is why it sees both definitions . I think we can improve it by not reading the plugins which are defined in .poisonededmplugincache.

**Comment by makortel** [comment]
Thanks, I didn't realize the script was using `.edmplugincache` (which also explains some confusion I had when checking the content shared object files). 

> I think we can improve it by not reading the plugins which are defined in .poisonededmplugincache.

Sounds good, thanks.

**Pull request merged**
