### PR TITLE
Trigger Object Tag and Probe DQM source : 101X 

### PR DESCRIPTION
**Pull request by Sam-Harper**
This is the 10_1_X flavour of https://github.com/cms-sw/cmssw/pull/24319

Needed for HLT deployment.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #24319

**Comment by Martin-Grunewald** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by andrius-k** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
