### PR TITLE
Don't use ElectronHcalHelper in EgammaHLTProducers

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Hi! One pieces of the EgammaElectronAlgos that I do not really like is the ElectronHcalHelper, because it is essentially a non-threadsafe wrapper around EgammaTowerIsolation. I don't think this abstraction layer is needed. Using the isolation classes directly results in shorter and more direct code, enables a few conversions from stream to global plugins among the EgammaHLTProducer plugins and we can also use this opportunity to spread some usage of `ESGetToken` instead of manual cashing of event setup products. Also, not using it removes the dependence of the EgammaHLTProducers on libEgammaElectronAlgos.

#### PR validation:

CMSSW compiles and local matrix tests pass.

#### if this PR is a backport please specify the original PR:

No backport intended.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Kind of technical, it accomplishes what declared in the PR description, plus a few additional simplifications
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
