### PR TITLE
[Payload Inspector]  Remove PY3 check as boost will be built with python3

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
**EDIT**: This PR now contains also #30099.

   * commit b2430de8c062709523a64ab5501ff9a9e9fcd7d9 Remove PY3 checks for unit tests. This was needed as boost_python was build with python2 while in PY3 IBs the default python was python3. cms-sw/cmsdist#5903 should now build boost python with python3 in PY3 IBs, so there is no need to have these speical conditions in BuildFile.xml

   * commit 47db651f030e95acade42adda7cecc0088f92980 This is an attempt to fix issue reported at https://github.com/cms-sw/cmssw/pull/30099#issuecomment-638596697.

#### PR validation:

I tested the fix with the recipe proposed here: https://github.com/cms-sw/cmssw/pull/30099#issuecomment-638733475 
```
/cvmfs/cms-ib.cern.ch/cms-bot/test-prs.sh cms-sw/cmssw#30099 cms-sw/cmsdist#5903
cd CMSSW_11_2_PY3_X_2020-06-03-2300/
cmsenv
scram build -j 8
test/slc7_amd64_gcc820/testSiStripPayloadInspector
```

and it runs fine with the fix. 
I also tested it in the main branch in `CMSSW_11_2_X_2020-06-10-2300` and it runs fine.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
code-checks

**Comment by mmusich** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5903,https://github.com/cms-sw/cmssw/pull/30099

**Comment by smuzaffar** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5903,#30099

**Comment by mmusich** [comment]
@smuzaffar I tried to add you commit 1c964668d01b79b5d8937770d826029cc11202e0 directly here.
Let's see if that works.

**Comment by mmusich** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5903

**Comment by smuzaffar** [comment]
@mmusich  , it was failing because the last PY3 IBs available (from 06-10-2300) was without pythia8 changes. We now have a new PY3 IB which should work now.

**Comment by mmusich** [comment]
@smuzaffar 

> I found errors in the following unit tests:
>---> test TestFWCoreParameterSetDriver had ERRORS
>---> test test-rivet-list had ERRORS
>---> test GeometryDTGeometryBuilderTestDriver had ERRORS
>---> test materialBudgetTrackerPlots had ERRORS

The errors in CondCore unit tests are gone.
I suppose these tests are already failing in the IB. https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc820/www/thu/11.2.PY3-thu-23/CMSSW_11_2_PY3_X_2020-06-11-2300?utests

**Comment by smuzaffar** [comment]
please test
Lets test this for normal Ibs (i.e for python2)
@mmusich , yes these unit tests are already failing in IB. This PR looks good.

**Comment by smuzaffar** [comment]
please test
looks like some network issues

**Comment by smuzaffar** [comment]
@ggovi, @Martin-Grunewald, @fwyzard can you please review this?
For PY3 Ibs, we want to build boost python with python3 and these changes are needed to go along with cms-sw/cmsdist#5903 .

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
