### PR TITLE
Added the TestProcessor system

### PR DESCRIPTION
**Pull request by Dr15Jones**
The TestProcessor system allows one to write unit tests for individual CMSSW modules.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos @smuzaffar the unit test and clang compilation errors are false positives.

The unit test failures are the ones in the IB caused by the change to jemalloc which changed the allowed configuration parameters.

The clang compilation error stems from python2.7 headers not being C++17 compatible.

**Comment by fabiocos** [comment]
@Dr15Jones for the unit tests ok, @smuzaffar is modifying the jemalloc tool file. Concerning the other issue, as far as I can see the problem is not caused by this PR, just a pre-existent issue that is put in evidence by it, as headers including BootPython.h are used. Still, should we consider this just as "normal"?

**Comment by perrotta** [comment]
+1
- For reco, it solves ambiguity in DataFormats/TrackReco/interface/HitPattern.h (technical)
- Jenkins tests pass (excluding the unit test and the clang build discussed elsewhere in this thread)

**Comment by Dr15Jones** [comment]
@fabiocos it would be nice to get this into the release today so when I speak about it tomorrow someone could give it a try.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
