### PR TITLE
Backporting EG UL regression code to 1030

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

The custom reco for the light by light analysis also needs custom energy regressions. Therefore the code for the new regressions needs backported, both sc and ele/pho.  The SC code is being used in the release but its defaults are set to the correct setting for 103X. The ele/pho is just additional code mostly except for a minor modification to deal with the changes. 

We do not expect any changes to any workflow that exists. 

backport of https://github.com/cms-sw/cmssw/pull/26892, https://github.com/cms-sw/cmssw/pull/26763

#### if this PR is a backport please specify the original PR:
https://github.com/cms-sw/cmssw/pull/26892
https://github.com/cms-sw/cmssw/pull/26763

### CODE REVIEW

**Comment by slava77** [comment]
@Sam-Harper 
is this for pp_on_AA RECO (up to AOD output)?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
> @Sam-Harper
> is this for pp_on_AA RECO (up to AOD output)?

According to what we discussed on Friday, this is meant to a one shot re-reco, with a dedicated era, which has to be based on pp_on_AA

**Comment by Sam-Harper** [comment]
> > @Sam-Harper
> > is this for pp_on_AA RECO (up to AOD output)?
> 
> According to what we discussed on Friday, this is meant to a one shot re-reco, with a dedicated era, which has to be based on pp_on_AA

Yes, that is the case. @rchudasa  is preparing the reco changes (just python via a modifier). 

So super special thing for one analysis to be done once. However for provenance, it would be ideal if its in the release (there is a debate ongoing whether this will be done centrally or not)

**Comment by slava77** [comment]
> > > @Sam-Harper
> > > is this for pp_on_AA RECO (up to AOD output)?
> > 
> > 
> > According to what we discussed on Friday, this is meant to a one shot re-reco, with a dedicated era, which has to be based on pp_on_AA
> 
> Yes, that is the case. @rchudasa is preparing the reco changes (just python via a modifier).
> 
> So super special thing for one analysis to be done once. However for provenance, it would be ideal if its in the release (there is a debate ongoing whether this will be done centrally or not)

well, this is in conflict with https://github.com/cms-sw/cmssw/pull/27633#issuecomment-516451806
> We don't use or modify pp_on_AA era as it modifies many Egamma thresholds to higher values which we don't want.

**Comment by Sam-Harper** [comment]
Ah misspoke, yes ruchi is correct, I just read that as pp. Yes its standard pp.

**Comment by slava77** [comment]
> Reco comparison results: 0 differences found in the comparisons

is the backport supposed to be enabled in python to see some effect?

@Sam-Harper please remind me if it is going to be running in the RECO step or in miniAOD.

**Comment by Sam-Harper** [comment]
At the moment, it'll be at the analysis level. But we would like to enable it for reco if the regresssions come in time.

**Comment by slava77** [comment]
> At the moment, it'll be at the analysis level. But we would like to enable it for reco if the regresssions come in time.

If this is just for analysis, isn't it possible to run the analysis in 10_6_X and avoid the backport?

**Comment by Sam-Harper** [comment]
It might also be for reco if we can get the regressions in time. 

Moving to 106X would probably delay this analysis significantly, things are never smooth. For 103X, its a small change and can be verified to be a null op as far as the release is concerned.

**Comment by slava77** [comment]
> It might also be for reco if we can get the regressions in time.

for this, we are then missing changes in regressionModifier_cfi.py and a definition of a modifier to pick it up; in the context of this backport I guess that instead of ```run2_egamma_2018``` we'd use ```egamma_lowPt_exclusive``` from #27633 .

**Comment by Sam-Harper** [comment]
Yes, I'm waiting for that PR to merge before I can activate it here.  I understand two PRs are a bit awkward but I didnt want Ruchi having to deal with regression changes and I didnt want to do her PR :)

**Comment by slava77** [comment]
that PR is in /master. For backports interdependent PRs should be avoided.

Please comment on the apparently missing changes in the regressionModifier_cfi.py.
The era mod is a smaller change.

**Comment by Sam-Harper** [comment]
The regression modifier config will be special for the regression Ruchi makes. And that isnt final yet. Therefore its not in the release.

**Comment by slava77** [comment]
On 8/7/19 5:01 AM, Sam Harper wrote:
> The regression modifier config will be special for the regression Ruchi
> makes. And that isnt final yet. Therefore its not in the release.
> 

do I understand correctly, that there will also be another PR for
egamma_lowPt in the master version as well?
If so, please clarify the timeline.
Thank you.

**Comment by Sam-Harper** [comment]
Ruchi needs to finalise her regression. On this we need to decide which release and conditions are going on. Once we do that we will progress.  I dont know the timeline

We are currently boot strapping the system. 

1) the light by light modifiers go in and the release strategy is decided
2) the regression depends on the release stategy, once we have a plan here, we can set that

**Comment by slava77** [comment]
I see.
I somehow thought that everything is ready and the RECO/AOD processing is strongly preferred to be done ASAP, which sort of leaves only 10_3_X as an option (with the standard requirement that anything new should appear in 11_X/master first).

**Comment by Sam-Harper** [comment]
Its very close. It would be better you talk to Ruchi not me about the schedule though. She has the trainings and  is close. However all this talk of doing it in 106X would require a retraining. 

So can we have all the discussion on the other PR where Ruchi can respond to it all. Thanks!

**Comment by slava77** [comment]
well, it sounds like we better use the already existing email thread then.

**Comment by slava77** [comment]
@rchudasa 
please clarify on the status of the regression.
I'd like to make sure that this setup works for low pt before signing off on the backport.

**Comment by rchudasa** [comment]
> @rchudasa
> please clarify on the status of the regression.
> I'd like to make sure that this setup works for low pt before signing off on the backport.

I tried to validate the regression on flat pt photon sample by applying low pt trained photon regressions (produced with help of Sam). But, I am not getting the expected results. Currently, we are trying to debug it. I hope it will be solved by end of this week.

**Comment by slava77** [comment]
> > @rchudasa
> > please clarify on the status of the regression.
> > I'd like to make sure that this setup works for low pt before signing off on the backport.
> 
> I tried to validate the regression on flat pt photon sample by applying low pt trained photon regressions (produced with help of Sam). But, I am not getting the expected results. Currently, we are trying to debug it. I hope it will be solved by end of this week.

@rchudasa 
please clarify on the status of debugging.
Thank you.

**Comment by slava77** [comment]
> @rchudasa
> please clarify on the status of debugging.
> Thank you.

it's almost one week since last Friday reco meeting (the ETA for debugging was about a week).

**Comment by rchudasa** [comment]
I am working on it and I apologize that few cross-checks took more than expected time. There has been progress now and we expect to close it next week.

**Comment by slava77** [comment]
Based on https://github.com/cms-sw/cmssw/pull/27898#issuecomment-529881810 it looks like this can be confirmed as useful for lowpt.
Please let me know if this PR is complete or if some new python configuration updates are expected here.
Thank you.

**Comment by Sam-Harper** [comment]
We would like to add the final python config which will appear when Ruchi finishes the ele & pho regressions

**Comment by Sam-Harper** [comment]
This has now been merged onto the branch of https://github.com/cms-sw/cmssw/pull/27898 so I'll close this PR this evening as a result.

**Pull request closed without merging**
