### PR TITLE
Removed redundant tests in Thinning*TestAnalyzers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The exact same test was being performed in code just above the lines which were removed.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This should fix the new Clang Analyzer warning for FWCore/Integration.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

Hoping for clearer comparisons

**Comment by makortel** [comment]
Comparison failures are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
ignore tests-rejected external-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
