### PR TITLE
Improvements/Fixes for Condition DB tools

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

- Removed warning from sqlalchemy, appearing at run time in query output
- Mark on going run in listRun

#### PR validation:

Standalone tests

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Alignment,CondCore,CondTools

**Comment by smuzaffar** [comment]
please test
testing with extra packages to run other unit tests which use conddb

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
