### PR TITLE
Avoid short-circuiting ESWatchers in  ElectronSeedGenerator

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Be sure to call check for all ESWatchers for each event.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- The fix is technically rather trivial. I take the liberty to merge it in time for the 1100 IB, but please @cms-sw/reconstruction-l2 complain if you don't agree with it, and we can always revert it if so.

**Comment by perrotta** [comment]
merge

**Comment by mandrenguyen** [comment]
+reconstruction

**Pull request merged**
