### PR TITLE
record for xtal-dependent seeding thresholds

### PR DESCRIPTION
**Pull request by argiro**
#### PR description:

A new feature is planned in PF reconstruction, whereby seeding is made using xtal-dependent thresholds.  This PR is to introduce the new record that provides the thresholds, so that the DB can be populated and the new feature introduced later.

#### PR Validation:
N/A

### CODE REVIEW

**Comment by tlampen** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi could you please have a look?

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar and here it looks the same happened as for #28327 ... I wonder whether there is any correlation with the fact that it is the same signature

**Comment by fabiocos** [comment]
@argiro for my understanding, on which time scale do you plan to add this new feature using the record of this PR?

**Comment by argiro** [comment]
> On 11 Nov 2019, at 15:55, Fabio Cossutti <notifications@github.com> wrote:
> 
> @argiro for my understanding, on which time scale do you plan to add this new feature using the record of this PR?

say by the end of the month. Is  MSSW_11_0_0_pre13: 2019/11/19 a hard deadline ?

**Comment by smuzaffar** [comment]
@fabiocos , looks like some glitch with CERN network. Github was not able to deliver the webhook because
```
We couldn’t deliver this payload: Failure when receiving data from the peer
```

**Comment by smuzaffar** [comment]
@fabiocos , I have setup cms-bot to also pool every 30mins to re-process recently updated (with in 60mins) PRs. This will allow to deal with such glitches

**Comment by fabiocos** [comment]
@smuzaffar thanks, this may be helpful in cases like this

**Comment by fabiocos** [comment]
@argiro if the development to use this PR needs to be in 11_0_0 for HLT TDR initial production it should be there by the closure of the development (unless this is revisited for updated needs)

**Comment by fabiocos** [comment]
+1

**Comment by argiro** [comment]
thanks Fabio, it is not needed for HLT TDR

**Pull request merged**
