### PR TITLE
further miscellaneous clean-up / improvements to SiStrip payload inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a quick follow-up to https://github.com/cms-sw/cmssw/pull/37265, for a commit that didn't make it in time in that PR.
Just a further clean-up to conform to `cmssw` coding rules and adding improving few plot legends for `SiStripNoises` and `SiStripPedestals` comparisons.

#### PR validation:

Private. Example of plots produced with the extension introduced here with the following commands:

```console
getPayloadData.py --plugin pluginSiStripNoises_PayloadInspector \
   --plot plot_SiStripNoiseValueComparisonSingleTag \
   --tag SiStripNoise_CRAFT_21X_v4_offline \
   --input_params '{}'  \
   --time_type Run \
   --iovs '{"start_iov": "50725", "end_iov": "51415"}'  \
   --db Prod --test;
 
 getPayloadData.py --plugin pluginSiStripPedestals_PayloadInspector \
    --plot plot_SiStripPedestalValueComparisonPerStripSingleTag \
    --tag SiStripPedestals_v2_prompt \
    --input_params '{}' \
    --time_type Run \
    --iovs '{"start_iov": "348767", "end_iov": "348878"}' \
    --db Prod --test ;
```

| SiStrip Noise | SiStrip Peds |
| ------------- | ------------- |
|  noisesFurtherPR |  pedestalsFurtherPR |

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+1

 - mainly cosmetic improvements as detailed in the PR description
 - differences in 39434.911 are known and already reported in #37315

**Comment by perrotta** [comment]
+1

**Pull request merged**
