### PR TITLE
Run3-gem57 Make sure that change of units in dd4hep will not affect GEM/ME0 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make sure that change of units in dd4hep will not affect GEM/ME0 geometry

#### PR validation:

Tested using cfg files in Geometry/GEMGeometryBuilder/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
In `Geometry/GEMGeometryBuilder/src/GEMGeometryBuilder.cc`, please delete line 33:
```
#include "CLHEP/Units/GlobalSystemOfUnits.h"
```
and change line 200:
```
const Surface::PositionType posResult(float(trans.x() / cm), float(trans.y() / cm), float(trans.z() / cm));
```
to
```
using geant_units::operators::convertMmToCm;
const Surface::PositionType posResult(convertMmToCm(trans.x()), convertMmToCm(trans.y()), convertMmToCm(trans.z()));
```

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
