### PR TITLE
adding HLT object monitoring to HLT online DQM

### PR DESCRIPTION
**Pull request by muell149**
updating HLT object monitoring for cleaner booking and fixing a few histogram axis ranges.

### CODE REVIEW

**Comment by deguio** [comment]
ciao @muell149 
should I assume that an additional commit will come for this PR? or this is final?
let me know.
thanks,
F.

**Comment by muell149** [comment]
ciao @deguio there aren't any expected additional commits coming anytime this week/next week. This is final.

cheers
charlie

**Comment by deguio** [comment]
+1
ok. the code runs at the online only and it has been tested since a while.
I thought we agreed on some optimization (loops mainly). I guess you can do that with a separate PR.

ciao and thanks,
F.

**Comment by muell149** [comment]
@deguio  The optimization is present in this PR. booking of hists is automated with loops and the number of data structure overall is reduced. There is also more parameters specified now in the python cfg. This shortened things by ~250 lines of code and the running time is roughly identical to before.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
