### PR TITLE
Update GT and Expected Result

### PR DESCRIPTION
**Pull request by ianna**
- Use latest GT for run2
- Expected result from XML comparison is updated

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by degano** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@ktf - I wonder who is responsible for DQM signature. It looks like there is a class MonitorElementMgr which is not used anywhere but brings DQM dependency to this package. I'd like to remove it.

**Comment by ktf** [comment]
I think all the validation packages are under DQM.

**Comment by ianna** [comment]
@deguio - do you think, DQM needs MonitorElementMgr class in this package? Thanks.

**Comment by deguio** [comment]
+1
already approved #7443

**Pull request merged**
