### PR TITLE
Phase2-hgx315ZC Add the testing code for partial wafer positioning for V17 HGCal Geometry as done in #38345 (now closed)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the testing code for partial wafer positioning for V17 HGCal Geometry as done in #38345 (now closed)

#### PR validation:

Use cfg's in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please approve this PR

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please note the failure was due to DAS error. Ithas nothing to do with this PR. Please approve this. I am asking for re-test nevertheless

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Update the test code, nothing change in the workflow.

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Updates/additions to the tests

**Pull request merged**
