### PR TITLE
pattch for efficiency in BsToMuMu_forSTEAM_13TeV_TuneCUETP8M1_cfi.py

### PR DESCRIPTION
**Pull request by inugent**
Patch for low Bs->mumu efficiency reported by Bilal Kiani

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
To be super-picky the filter efficiency in the fragment should be updated

**Comment by inugent** [comment]
Hello,
   Ok, I will update this, but please wait... I am checking another 
issue for ||Bilal Kiani.
Best regards,
Ian

||

**Comment by covarell** [comment]
-1 
Submitter asked for more time

**Pull request closed without merging**
