### PR TITLE
Add 2023 FastSim Era

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR follows the new Era of Run_3 2023 in https://github.com/cms-sw/cmssw/pull/41271
This PR needs to be used with https://github.com/cms-sw/cmssw/pull/42327 to complete FastSim setup for 2023.

#### PR validation:
Run private production and compare DQM. One can see better FastSim-FullSim agreement with new era:
+ PFJet Rapidity: https://tinyurl.com/2bnl3p8f
+ Delta R (PFJet-vs-GenJet): https://tinyurl.com/28uxfr3n
+ SumET: https://tinyurl.com/2dmgo4xr
+ ak8PFJetsPUPPI: https://tinyurl.com/28nln9tp
+ NanoAOD, PNetPerJet: https://tinyurl.com/26wbsplf
+ NanoAOD, MET: https://tinyurl.com/2cpo27jh

For all plots:
+ Black: FullSim (private)
+ Blue: FastSim (default, same GEN as FullSim)
+ Orange: FastSim (New era, same GEN as FullSim)
+ Red: FullSim (relvals, as ref)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Need backport to 13_0, 13_1, 13_2

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/42327
- workflows = 14034.0,14234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
test parameters:
- workflows = 14034.0,14234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Fail in wf 14034.0 comparison is expected, it is 2023 FastSim workflow. No change is expected in other workflow.

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
