### PR TITLE
[Backport] Fix BoostedDoubleSVProd crashing with nan/inf daughters

### PR DESCRIPTION
**Pull request by andrzejnovak**
#### PR description:
Backport of #27238

Needed for a fix to this Nano production
https://its.cern.ch/jira/browse/CMSCOMPPR-6445.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #27238

**Comment by perrotta** [comment]
-1
Please address first the issues raised in the master version of this pull request, and then come back to this backport

**Comment by perrotta** [comment]
@andrzejnovak please update with the LogWarning's, as in the master version of this PR

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Correct backport of #27238 
- The fix provides a rescue from nan/inf values in daughter jets parameters, and will allow nanoAOD and analysis to continue running even in presence of such pathological cases
- A fix for the wrong jet parameters has to be provided independently: issue #27374 has been opened for that
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
