### PR TITLE
Vincia shower weights for uncertainty bands

### PR DESCRIPTION
**Pull request by mseidel42**
See http://vincia.hepforge.org/current/share/Vincia/htmldoc/VinciaUncertainties.html

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by efeyazgan** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
