### PR TITLE
[13_2_X] update relval matrix to add WFs for 2022E era

### PR DESCRIPTION
**Pull request by sunilUIET**
#### PR description:

This PR adds 140.071-140.078 WFs for release validation that use 2022 era E data.

Once this PR is converged, PR will be created to backport to 13_1_X, 13_0_X and 12_4_X

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:

workflows = 140.071,140.072,140.073,140.074,140.075,140.076,140.077,140.078
relvals_opt = -w standard

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
