### PR TITLE
Migrate legacy type modules to one type

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Migrate three legacy type modules to one type

ESDaqInfoTask
ESDataCertificationTask
ESDcsInfoTask

#### PR validation:

Relies on existing tests. Minimal changes were done to migrate this code. They should behave the same.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by thomreis** [comment]
Should these not rather be migrated to `DQMEDAnalyzer`?

**Comment by makortel** [comment]
> Should these not rather be migrated to `DQMEDAnalyzer`?

In principle yes, but
* `ESDaqInfoTask` does its work in `beginLuminosityBlock`, which wouldn't work with `DQMEDAnalyzer`. It might work with `DQMOneLumiEDAnalyzer`, but we'd prefer to leave further improvements for @cms-sw/dqm-l2 
* `ESDataCertificationTask` doesn't seem to do much useful work (or I failed to see it) but seems to follow the same pattern
* `ESDcsInfoTask` does work in `beginLuminosityBlock` (in addition to `analyze()`), so in similar arguments only minimal work away from legacy modules is done in this PR

**Comment by wddgit** [comment]
ESDataCertificationTask books some histograms but never fills them. It's remotely possible some other module retrieves them from DQMStore and fills them but I doubt it. It has been in this state since 2013.

If we are going to do more than the minimal migration, then I would recommend deleting the entire module. Possibly there are some other files needing modification, maybe configurations that try to run or read the histograms. I'm not sure.

I suppose I could try to do this instead. Do you want me to delete it?

**Comment by makortel** [comment]
> I suppose I could try to do this instead. Do you want me to delete it?

Since the module is being run as part of runTheMatrix, I'd leave it for DQM experts to clean up if it is indeed deemed unnecessary (unless @cms-sw/dqm-l2 instructs otherwise)

**Comment by emanueleusai** [comment]
Let's leave it like this for the time being. we will discuss with the ECAL DQM developers if they are ok with the module being removed.

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
