### PR TITLE
Removed CMS deprecated warnings from `RecoLocalTracker`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
Part of the migration in #31061 and #36404.
Went systematically through all of the CMSDEPRECATED_X warnings in the `RecoLocalTracker` subsystem from `CMSSW_12_3_CMSDEPRECATED_X_2021-12-15-2300` and removed deprecated API calls.
 * removed unnecessary header includes;
 * added `esConsumes`;
 * profited to reorganize `RecoLocalTracker/SiStripClusterizer/test/` plugins;
 * remove `endl` at the end of LogMessages;
 * remove occurrences of deprecated  `getByLabel`;
    
#### PR validation:

`cmssw` compliles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Still to do:
> 
>     * remove `endl` at the end of LogMessages;
> 
>     * remove occurrences of deprecated  `getByLabel`;
> 
> 

@mmusich 
please clarify if these are planned for this PR.
Thank you.

**Comment by mmusich** [comment]
> please clarify if these are planned for this PR.

Yes,  I planned to (in a few days). Otherwise they can come later in a follow-up PR. In its current state it should deliver what the title promises.

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild, please test

In the last push, I performed all the changes that I wanted to make for now, so I guess the review can proceed at earliest convenience.
Thanks.

**Comment by clacaputo** [comment]
Hi @mmusich , cmsbot test doesn't point to any change/failed comparisons, as it was intended, but I noticed that most of the code modified is located in various `test` folders and it isn't used in any unit test (AFAIK). 
Is it used somewhere else? If not, do you tried to compare the outputs locally?

**Comment by mmusich** [comment]
> Is it used somewhere else? 

No, it is meant to be used for private checks. 

>  do you tried to compare the outputs locally?

I did check for some module they don't throw at runtime, but didn't check outputs. In any case the changes are trivial and compilation most likely guarantees also the functionality is not spoiled. 
Incidentally all the modules that were still using the `getByLabel` mechanism are failing in the current release, while the functionality is restored with this PR.

**Comment by srimanob** [comment]
+Upgrade

For Phase2 related code in this PR, all modified files are under Process/SubProcess/test. So, no change is expected. This is purely technical PR. PR test runs fine.

**Comment by clacaputo** [comment]
+reconstruction

- technical, no reco changes
- no differences spotted in the test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Re-sign

**Comment by mmusich** [comment]
pinging @cms-sw/reconstruction-l2

**Comment by clacaputo** [comment]
+reconstruction

- resigning after small code fix, no changes expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
