### PR TITLE
Physics List updates for future migration to Geant4 10.6 

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In order to perform final set of tests of the new version of Geant4 a set of modifications for CMS custom Physics Lists is applied:
  1) FTFP_BERT_EMM - the default is unchanged
  2) FTFP_BERT_EML - use default EM physics configuration and custom part of hadron inelastic with possibility to configure different transition region between the Bertini cascade and the FTFP string model
  3) FTFP_BERT_EMY, FTFP_BERT_EMZ, and QBBC are unchanged, only debug printout is modified
  4) g4Sim_Hits_cfi.py - two extra parameters are added.
  5) Custom hadronic physics class CMSHadronPhysicsFTFP_BERT is rewitten to be maximally similar to Geant4 10.6

No change in baseline simulation is expected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , this may be useful for our tests, when propagated to the GEANT4 branch.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
