### PR TITLE
skip nonexistent branch checks in L1TGlobalUtilHelper

### LINKED ISSUE #26182: Unable to read 2018D data using CMSSW_10_2_10
From hypernews: https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3647.html

```
I can use CMSSW_10_2_10 to process 17Sep2018 Run 2018/A/B/C data without any problem.
However, when I run on 2018D PR data, I get the following error

Exception Message:
No Dictionary for class: 'vector<reco::FeaturesTagInfo<btagbtvdeep::DeepDoubleBFeatures> >â€™ 

I was wondering whether anyone know how to fix this problem.
```

The pull request #25370 which was a backport to CMSSW_10_2 removed the class DeepDoubleBFeatures thereby making it not possible to read the Run2018D processed data.

### PR DESCRIPTION
**Pull request by slava77**
backport of #26328

this is expected to resolve #26182 
thanks @Dr15Jones for suggesting a solution.

some notes leading to the resolution are in https://github.com/cms-sw/cmssw/issues/26182#issuecomment-479004269 and following

### CODE REVIEW

**Comment by slava77** [comment]
@cmkuo 
please check on your side that this resolves the problem that you reported earlier

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cmkuo** [comment]
@slava77 Many thanks for looking into this problem. This fix cures the problem I reported.

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
