### PR TITLE
Fix deprecated-copy warnings in CondFormats/PhysicsToolsObjects and PhysicsTools/MVAComputer

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:
Fix deprecated-copy warnings ([rule-of-three](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)) violation) in CondFormats/PhysicsToolsObjects and PhysicsTools/MVAComputer:

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/BitSet.cc: In function 'PhysicsTools::Calibration::BitSet PhysicsTools::Calibration::convert(const PhysicsTools::BitSet&)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/BitSet.cc:47:12: warning: implicitly-declared 'PhysicsTools::Calibration::BitSet::BitSet(const PhysicsTools::Calibration::BitSet&)' is deprecated [-Wdeprecated-copy]
    47 |     return result;
      |            ^~~~~~
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/Calibration.h:4,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/BitSet.cc:2:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/CondFormats/PhysicsToolsObjects/interface/MVAComputer.h:32:15: note: because 'PhysicsTools::Calibration::BitSet' has user-provided 'PhysicsTools::Calibration::BitSet& PhysicsTools::Calibration::BitSet::operator=(const PhysicsTools::Calibration::BitSet&)'
   32 |       BitSet &operator=(const BitSet &other) {
      |               ^~~~~~~~
>> Compiling  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/ProcLinear.cc
CMSSW_CPU_TYPE= /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DTBB_USE_GLIBCXX_VERSION=120301 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DCMSSW_GIT_HASH='CMSSW_14_0_DEVEL_X_2023-11-26-2300' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_14_0_DEVEL_X_2023-11-26-2300' -I/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/cms/coral/CORAL_2_3_21-821f5a7f8bb5dc2d52bc1a7792e2e524/include/LCG -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/pcre/8.43-37eb2e8b73bab83d6645ecfd5d73dcaa/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/curl/7.79.0-959a9188e043d67b2825f64cfeb54266/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/lcg/root/6.26.11-1ef575234f3b954353280f3578660947/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/xerces-c/3.1.3-c7b88eaa36d0408120f3c29826a04bf6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/zlib/1.2.11-51072030b7f93c3ac6c4235f21e413cb/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/fmt/8.0.1-54e94b39f5cf29341bb9c4765764e1ca/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tinyxml2/6.2.0-d17873b4d6a42a43226cf689f82ec1ef/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-unused-parameter -Wunused -Wparentheses -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr  -fPIC  -MMD -MF tmp/el8_amd64_gcc12/src/PhysicsTools/MVAComputer/src/PhysicsToolsMVAComputer/ProcLinear.cc.d /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/ProcLinear.cc -o tmp/el8_amd64_gcc12/src/PhysicsTools/MVAComputer/src/PhysicsToolsMVAComputer/ProcLinear.cc.o
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/MVAComputer.cc: In member function 'void PhysicsTools::MVAComputer::setup(const PhysicsTools::Calibration::MVAComputer*)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/MVAComputer.cc:104:52: warning: implicitly-declared 'PhysicsTools::Variable& PhysicsTools::Variable::operator=(const PhysicsTools::Variable&)' is deprecated [-Wdeprecated-copy]
   104 |       var.var = Variable(iter->name, config[i].mask);
      |                                                    ^
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/VarProcessor.h:19,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/MVAComputer.h:19,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/MVAComputer.cc:21:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/Variable.h:133:12: note: because 'PhysicsTools::Variable' has user-provided 'PhysicsTools::Variable::Variable(const PhysicsTools::Variable&)'
  133 |     inline Variable(const Variable &orig) : name(orig.name), flags(orig.flags) {}
      |            ^~~~~~~~
>> Compiling  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/ProcMLP.cc
CMSSW_CPU_TYPE= /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DTBB_USE_GLIBCXX_VERSION=120301 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DCMSSW_GIT_HASH='CMSSW_14_0_DEVEL_X_2023-11-26-2300' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_14_0_DEVEL_X_2023-11-26-2300' -I/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/cms/coral/CORAL_2_3_21-821f5a7f8bb5dc2d52bc1a7792e2e524/include/LCG -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/pcre/8.43-37eb2e8b73bab83d6645ecfd5d73dcaa/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/boost/1.80.0-826a207b8543c52970cb1f72d50f068c/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/bz2lib/1.0.6-d065ccd79984efc6d4660f410e4c81de/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/curl/7.79.0-959a9188e043d67b2825f64cfeb54266/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/libuuid/2.34-27ce4c3579b5b1de2808ea9c4cd8ed29/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/lcg/root/6.26.11-1ef575234f3b954353280f3578660947/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/xerces-c/3.1.3-c7b88eaa36d0408120f3c29826a04bf6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/xz/5.2.5-6f3f49b07db84e10c9be594a1176c114/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/zlib/1.2.11-51072030b7f93c3ac6c4235f21e413cb/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/fmt/8.0.1-54e94b39f5cf29341bb9c4765764e1ca/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/md5/1.0.0-5b594b264e04ae51e893b1d69a797ec6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tinyxml2/6.2.0-d17873b4d6a42a43226cf689f82ec1ef/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -Wno-error=array-bounds -Warray-bounds -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-unused-parameter -Wunused -Wparentheses -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr  -fPIC  -MMD -MF tmp/el8_amd64_gcc12/src/PhysicsTools/MVAComputer/src/PhysicsToolsMVAComputer/ProcMLP.cc.d /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/ProcMLP.cc -o tmp/el8_amd64_gcc12/src/PhysicsTools/MVAComputer/src/PhysicsToolsMVAComputer/ProcMLP.cc.o
>> Compiling  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/ProcMatrix.cc
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/MVAComputer.h: In instantiation of 'static _OI std::__copy_move<_IsMove, _IsSimple, _Category>::__copy_m(_II, _II, _OI) [with _II = std::_Rb_tree_const_iterator<PhysicsTools::MVAComputer::InputVar>; _OI = PhysicsTools::MVAComputer::InputVar*; bool _IsMove = false; bool _IsSimple = false; _Category = std::bidirectional_iterator_tag]':
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_algobase.h:495:30:   required from '_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = _Rb_tree_const_iterator<PhysicsTools::MVAComputer::InputVar>; _OI = PhysicsTools::MVAComputer::InputVar*]'
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_algobase.h:522:42:   required from '_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = _Rb_tree_const_iterator<PhysicsTools::MVAComputer::InputVar>; _OI = PhysicsTools::MVAComputer::InputVar*]'
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_algobase.h:530:31:   required from '_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = _Rb_tree_const_iterator<PhysicsTools::MVAComputer::InputVar>; _OI = __gnu_cxx::__normal_iterator<PhysicsTools::MVAComputer::InputVar*, vector<PhysicsTools::MVAComputer::InputVar> >]'
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_algobase.h:620:7:   required from '_OI std::copy(_II, _II, _OI) [with _II = _Rb_tree_const_iterator<PhysicsTools::MVAComputer::InputVar>; _OI = __gnu_cxx::__normal_iterator<PhysicsTools::MVAComputer::InputVar*, vector<PhysicsTools::MVAComputer::InputVar> >]'
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/MVAComputer.cc:112:14:   required from here
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/MVAComputer.h:92:12: warning: implicitly-declared 'PhysicsTools::Variable& PhysicsTools::Variable::operator=(const PhysicsTools::Variable&)' is deprecated [-Wdeprecated-copy]
    92 |     struct InputVar {
      |            ^~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/interface/Variable.h:133:12: note: because 'PhysicsTools::Variable' has user-provided 'PhysicsTools::Variable::Variable(const PhysicsTools::Variable&)'
  133 |     inline Variable(const Variable &orig) : name(orig.name), flags(orig.flags) {}
      |            ^~~~~~~~
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/string:50,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/locale_classes.h:40,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/ios_base.h:41,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/ios:42,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/ostream:38,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/iostream:39,
                 from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/36ee15c53d3074956fb6548fe912a5bd/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_DEVEL_X_2023-11-26-2300/src/PhysicsTools/MVAComputer/src/MVAComputer.cc:1:
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_algobase.h:353:23: note: synthesized method 'PhysicsTools::MVAComputer::InputVar& PhysicsTools::MVAComputer::InputVar::operator=(const PhysicsTools::MVAComputer::InputVar&)' first required here
  353 |             *__result = *__first;
      |             ~~~~~~~~~~^~~~~~~~~~
```

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_0_DEVEL_X

**Comment by iarspider** [comment]
please test

**Comment by tvami** [comment]
+analysis
 * technical PR, code compiles/runs in DEVEL version of CMSSW
 * diffs in 12434.7 are understood, see https://github.com/cms-sw/cmssw/issues/39803 , otherwise clean diffs (MsgLogger)

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
@iarspider can you fix the merge conflicts please?

**Comment by tvami** [comment]
+1
 * resign, see https://github.com/cms-sw/cmssw/pull/43400#issuecomment-1828280330

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
