### PR TITLE
backticks are deprecated, use repr() instead

### PR DESCRIPTION
**Pull request by ericvaandering**
Another automated fix up by futurize

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by ericvaandering** [comment]
Could someone trigger the tests again?

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Pull request merged**
