### PR TITLE
90X Fireworks: save and read pixel topology in new format

### PR DESCRIPTION
**Pull request by alja**
Save pixel topology pramters per given det id like:
pitchX
pitchY
offsetsX == localX(0.f)
offsetY  ==  localY(0.f)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by alja** [comment]
## Validation

I have used Fireworks/Geometry/plugins/ValidateGeometry.cc to cross check model with fireworks::TrackUtils
canvas_1
canvas_1

**Comment by alja** [comment]
### concern with big pixels and local X,Y
Big pixels can't be stored in parameters. So far I added a prameter (5th in a row) which marks big pixel layout. Its implementation is hardcoded in TrackUtils.

When big pixels will be enabled in phase 2, the code has to add new scenario.

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
@ianna 
Please follow that

**Comment by alja** [comment]
Sceenshot od 90X sim data:

**Pull request merged**
