### PR TITLE
Run3-alca211C Add generatedparticles to the list of saved objects for IsoTrack AlCaRecoDB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add generatedparticles to the list of saved objects for IsoTrack AlCaRecoDB. It only adds for MC samples

#### PR validation:

Use runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hi @bsunanda to accept this, we need to know the size change. Please provide these numbers. Also some of the motivation would be nice for why you need these to be added permanently, it is unusual to a add GEN info to ALCARECOs.

**Comment by bsunanda** [comment]
@tvami @yuanchao This has no effect on data - only on MC samples where genparticle is present. I ran on data and there was no increase. For MC there was 0.2% increase in the standard case (where the event size is 34 kB for dipion sample) and 2.3% increase in the new AlCaReco (where the event size is 3.8 kB in the same dipion sample)

**Comment by tvami** [comment]
> @tvami @yuanchao This has no effect on data - only on MC samples where genparticle is present. I ran on data and there was no increase. For MC there was 0.2% increase in the standard case (where the event size is 34 kB for dipion sample) and 2.3% increase in the new AlCaReco (where the event size is 3.8 kB in the same dipion sample)

Thanks, this is what we needed to know! ~2% should be fine!

**Comment by tvami** [comment]
+alca
 * tests pass
 * Max 2% increase the the MC AlCaRECOs is expected, which should be fine

**Comment by qliphy** [comment]
+1

**Pull request merged**
