### PR TITLE
migrate L1 and HLT summary modules to one::EDAnalyzer

### PR DESCRIPTION
**Pull request by fwyzard**
Migrate summary modules
- L1GtTrigReport
- HLTrigReport
  to one::EDAnalyzer. They could be migrated to global::EDAnalyzer, but since we do not run them online it's probably not worth it.

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
tracked at #10964

**Pull request merged**
