### PR TITLE
Add boosted taus to nanoAOD (backport of #33528)

### PR DESCRIPTION
**Pull request by swozniewski**
#### PR description:

- adds boosted taus to nanoAOD, which is a backport of #33528
- configuration of input taus to anti-Ele-MVA-ID in runTauIdMVA.py had to be made configurable, which was missed in an earlier backport and is now consistent with other IDs in that file.
- modifier treatment in nano_cff was aligned with present structure which technically differs from master

#### PR validation:

passed code checks, unit tests, most limited matrix tests; remaining two matrix tests passed after adding the latest commit fixing the anit-Ele-MVA incompatibility

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of #33528 needed for nanoAOD v9 production

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by swozniewski** [comment]
I added a followup as requested in #33528

**Comment by perrotta** [comment]
Besides #33528 (which does not need the reco signature in its master version) this PR also backports one missing reco feature/fix that was merged in the master with #33150 and evidently forgotten in the backport PR #33153: this is a simple and uncontroversial addition, with no expected effect on standard workflows, and I don't expect issues from it.

**Comment by gouskos** [comment]
Hi @swozniewski I think all the rest look good but I have a comment on the DQM side.
Currently the DQM histograms are booked although not filled.
Please add in: 
`PhysicsTools/NanoAOD/python/nanoDQM_cff.py` 
something similar to these three lines: 
[particlenet mass regression BP](https://github.com/cms-sw/cmssw/pull/33588/files#diff-5f4338f7d7671c8348d9097ff44f255cc0b36d204c639782856a7c36cbc8fbdaR78)
So the DQM histograms are not produced in previous releases

**Comment by qliphy** [comment]
+1

**Pull request merged**
