### PR TITLE
PPS: rename directories with misleading names

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

There were two instances of directories with misleading names in the (CT)PPS code tree:
 * CondFormats/CTPPSReadoutObjects: contained all PPS cond-formats, not just readout,
 * RecoCTPPS/TotemRPLocal: beyond the code for Si strip detectors (from TOTEM), contained also the code for diamond and UFSD sensors.

We profit from this renaming, to replace CTPPS with PPS in the affected directory names.

In RecoPPS, we put all the local-reconstruction (within a single RP) into a single directory "Local".

This is a technical RP, no changes in the results are expected.

#### PR validation:

Running
```
runTheMatrix.py -l limited -j 10 --ibeos
```
gave
```
34 33 32 26 16 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```

The plots below compare proton reconstruction with CMSSW_11_1_0_pre3 (blue) and this PR (red dashed) - there is no difference as expected.
make_cmp

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by perrotta** [comment]
@jan-kaspar there are conflicts to be resolved, see above

**Comment by jan-kaspar** [comment]
> @jan-kaspar there are conflicts to be resolved, see above

Thanks, I see. Now I also realise that there will be conflict with my other PR #29046. Since the latter PR is very small (thus hopefully fast), I suggest that I resolve all conflicts once #29046 is merged. Just to avoid that people need to sign again and again. What do you think?

**Comment by jan-kaspar** [comment]
For some reason one commit was ignored by the force-push. I'm going to fix it now. Please do not start tests until a further notice.

**Comment by jan-kaspar** [comment]
> For some reason one commit was ignored by the force-push. I'm going to fix it now. Please do not start tests until a further notice.

Fixed - 76ece33 is the last commit that I intended to push. Tests can be triggered now.

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
The migration (renaming) of PPS related packages seems to me done here correctly. In the release there shouldn't be any remaining instance of the previous "CondFormats/CTPPSReadoutObjects" and "RecoCTPPS/TotemRPLocal" or "RecoCTPPS/PixelLocal" packages, now fully renamed.

However, the jenkins tests report about dublicate plugins and dictionaries, and also in the logs the following kind of warning appear (e.g.):
```
Warning in <TInterpreter::ReadRootmapFile>: class  CTPPSBeamParameters found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  CTPPSPixelAnalysisMask found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  CTPPSPixelDAQMapping found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
...
```

Mostly for my own education: is it due to the fact that a full build would be needed to get rid in memory of the removed plugins and libraries? Or is there really anything else that must be fixed here?

@Dr15Jones @makortel

**Comment by Dr15Jones** [comment]
@perrotta the warnings
```
Warning in <TInterpreter::ReadRootmapFile>: class  CTPPSBeamParameters found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
```

comes from ROOT. I believe ROOT's plugin system doesn't seem to have the same facility as the CMS one to pull plugins from the local lib directory before getting them from the release lib directory. Instead, it appears to treat the local and release directories equally. If that hypothesis is correct, then the only way to get away from those warnings is to have the change in the release.

**Comment by perrotta** [comment]
> @perrotta the warnings
> 
> ```
> Warning in <TInterpreter::ReadRootmapFile>: class  CTPPSBeamParameters found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so 
> ```
> 
> comes from ROOT. I believe ROOT's plugin system doesn't seem to have the same facility as the CMS one to pull plugins from the local lib directory before getting them from the release lib directory. Instead, it appears to treat the local and release directories equally. If that hypothesis is correct, then the only way to get away from those warnings is to have the change in the release.

Thank you @Dr15Jones !

And I imagine that the duplicate plugins and libraries reports have a similar origin, and they are also expected to disappear once the change is in the release.

**Comment by perrotta** [comment]
+1
- The migration only consists in renaming more appropriately a few directories.
- It is propagated correctly whenever they are addressed in CMSSW
- Jenkins tests pass, and show no differences
- Warning reports about duplicate plugins and libraries are expected to disappear once the change is merged in the release

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
merge

db:  @ggovi
alca:  @franzoni @pohsun @tlampen @tocheng @christopheralanwest
analysis:  @santocch
dqm:  @andrius-k @jfernan2 @kmaeshima @fioriNTU @schneiml
Please have a look. This PR simply renames several directories.

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+geometry

**Comment by silviodonato** [comment]
@jan-kaspar I reverted this PR with #29093 because it is causing many IB errors in CMSSW_11_1_X_2020-03-03-2300 (slc7 amd64 gcc820).
The errors are 
`class  CTPPSBeamParameters found in libCondFormatsCTPPSReadoutObjects.so  is already in libCondFormatsPPSObjects.so `

@jan-kaspar please open a new PR, I think we need some help from @ggovi to fix the problem with CondFormatsCTPPSReadoutObjects

**Comment by perrotta** [comment]
> @jan-kaspar I reverted this PR with #29093 because it is causing many IB errors in CMSSW_11_1_X_2020-03-03-2300 (slc7 amd64 gcc820).
> The errors are
> `class CTPPSBeamParameters found in libCondFormatsCTPPSReadoutObjects.so is already in libCondFormatsPPSObjects.so `
> 
> @jan-kaspar please open a new PR, I think we need some help from @ggovi to fix the problem with CondFormatsCTPPSReadoutObjects

It is supposedly an issue with root, see [above](https://github.com/cms-sw/cmssw/pull/29037#issuecomment-593979957) 
I would rather ask the advice of the fwk gurus first (@Dr15Jones,@smuzaffar,@makortel)

**Comment by jan-kaspar** [comment]
> It is supposedly an issue with root, see [above](https://github.com/cms-sw/cmssw/pull/29037#issuecomment-593979957)
> I would rather ask the advice of the fwk gurus first (@Dr15Jones,@smuzaffar,@makortel)

OK, I am waiting for further advice.

**Comment by mrodozov** [comment]
If you see the IBs, you'll notice the ROOT 620 IB which is also using the master branch of cmssw doesn't have the unit tests breaking and it's also the only one that is a full build (by chance, due to change relevant only to this specific build, this one https://github.com/cms-sw/cmsdist/pull/5619 ).
I'm suspecting there is no problem with this PR but we have to build full builds to dispose of the unit test failures.

**Comment by perrotta** [comment]
> If you see the IBs, you'll notice the ROOT 620 IB which is also using the master branch of cmssw doesn't have the unit tests breaking and it's also the only one that is a full build (by chance, due to change relevant only to this specific build, this one [cms-sw/cmsdist#5619](https://github.com/cms-sw/cmsdist/pull/5619) ).
> I'm suspecting there is no problem with this PR but we have to build full builds to dispose of the unit test failures.

Thank you @mrodozov !
Then, it was reverted too quickly in the IB, and delaying its inclusion will only postpone the problem to pre5.
My impression is that we should rather "revert the revert" and have a full build in the IBs to clean up the unit tests.

**Comment by mrodozov** [comment]
this would be easier (merge it again in cmssw) but I'd rather try to do it manually to confirm so that we don't mess it up further 😅

**Comment by jan-kaspar** [comment]
Thanks everyone! Is any action needed from our side?

**Comment by perrotta** [comment]
@mrodozov @silviodonato : was any attempt made to merge this again manually in the IB and make a full build, as suggested [above](https://github.com/cms-sw/cmssw/pull/29037#issuecomment-594468272)?

@silviodonato do you plan to eventually "revert the revert", or should we ask @jan-kaspar to prepare an identical PR to be merged after pre4? Please advise.

**Comment by silviodonato** [comment]
@perrotta I made #29093

**Comment by jan-kaspar** [comment]
Thanks @silviodonato !

**Comment by santocch** [comment]
+1

**Comment by tlampen** [comment]
+1

**Pull request merged**
