### PR TITLE
[LLVM Analyzer][Heterogeneous] Remove dead assignments

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

This fixes clang-analyzer warnings https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-29-0000/el8_amd64_gcc12/llvm-analysis/index.html

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by fwyzard** [comment]
If this does not introduces new warnings because we ignore the return values of the CUDA calls, OK for me.

**Comment by fwyzard** [comment]
+!

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
