### PR TITLE
Jet updates for Mini and (JME)Nano, add recipe for puppi JetMET reclustering

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR makes several changes in MiniAOD, NanoAOD and JMENano:

1) MiniAOD
- In `applySubstructure_cff.py`, sync the AK8 jet pt cuts, when collecting PF constituents, for Run-2 MiniAOD with Run-3 RECO-level cuts.
- Use `updateJetCollection` to setup `DeepJet` and `UParT` taggers for AK8 subjets.
- Minor: Cleanup of postfix usage in `applySubstructure_cff.py`.

2) NanoAOD
- Add `subGenJetAK8Idx` to match reco-level (`SubJet`) to gen-level(`SubGenJetAK8`) AK8 subjets.
- Add `rawMass` for `CorrT1METJet` collection.

3) JMENano
- Add energy fraction and puppi weight of leading PF constituent of each PF type in AK4 Puppi jets.
- Remove pt requirement for UParT regression nodes.
- Update JMENano+Repuppi  autoNano (`@JMErePuppi `) configuration to include rebuilding of `slimmedJetsAK8` collection.

The functions in `puppiJetMETReclusteringTools.py` and `puppiJetMETReclusteringFromMiniAOD_cff.py` scripts are designed to schedule the rebuilding of AK4 Puppi jets (`slimmedJetsPuppi`), AK8 Puppi jets (`slimmedJetsAK8`) and PuppiMET (`slimmedMETsPuppi`) with MiniAODs as input. The functions try to follow, as best as possible, how they are setup in the PAT step for MiniAOD production.

These recipes were previously used to propagate Puppi tune studies through private NanoAOD production. We find it helpful to have these functions in CMSSW if, (a) we need to produce NanoAOD (privately or special validation campaigns), and (b) also for analyzers if they need to tune and update puppi in their analyses.

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes reMiniAOD+reNano Run-2 UL workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`
- passes `JMErePuppi ` workflows: `runTheMatrix.py -i all --ibeos  -l 2500.225,2500.235`

### CODE REVIEW

**Comment by hqucms** [comment]
test parameters:
 - enable = nano
 - workflow = 10224.15,11024.15,11634.15,25202.15

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
ignore tests-rejected with ib-failure

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
