### PR TITLE
Make CaloTSamples(Base) to compile with C++20

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Title says it all

#### PR validation:

Package `CalibFormats/CaloObjects` builds in CPP20 IB.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by iarspider** [comment]
Ah, you've beat me to it :) Thanks!

**Comment by francescobrivio** [comment]
+1

 - technical
 - tests clean, no differences expected or observed

**Comment by perrotta** [comment]
+1

**Pull request merged**
