### PR TITLE
move testdata to external repo IOPool-Input

### PR DESCRIPTION
**Pull request by smuzaffar**
- Move testdata in to external data repository cms-data/IOPool-Inout
- Updated unit test to find testdata from external data (using `CMSSW_SEARCH_PATH`)
- Update TestPoolInput.sh print the command it runs and fail when something goes wrong

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4627

**Comment by wddgit** [comment]
If I build a local working area with IOPool/Input and want to run the
unit tests (something I do regularly), then what is the recipe of
commands I will need to issue to setup these test data files? Or is it
somehow automatic? I'm not complaining, this seems like a reasonable
change. I just want to know what I need to do.

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@wddgit , data files will be available in your dev area too and unit test will automatically find them via CMSSW_SEARCH_PATH

**Comment by fabiocos** [comment]
+1

**Pull request merged**
