### PR TITLE
New stop-run control and more debugging info on JSON parse error in input source (DAQ) - 81X

### PR DESCRIPTION
**Pull request by smorovic**
81X port of #15647
- File-based based mechanism to stop data processing based on specific pid
- dump json library message full content of the json file in case before parsing exception is thrown

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15649 39d9b24
- daq code changes, reco is not affected
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
