### PR TITLE
slimmedMETsNoHF and possible cleanup

### PR DESCRIPTION
**Pull request by wajidalikhan**
#### PR description:

- slimmedMETsNoHF collection in MiniAOD  is just MET without considering PF candidates in the HF region
- Its impact on the MiniAOD size is negligible 
- it clusters a new CHS jet collection (ak4PFJetsCHSNoHF) which is used for its Type-1 correction consuming a non-negligible CPU time
- No use cases at the moment therefore it can be removed from MiniAOD production workflow

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+reconstruction
Thanks for the cleanup!

**Comment by mandrenguyen** [comment]
please test

**Comment by hqucms** [comment]
@cms-sw/dqm-l2 Could you please have a look and sign it? Thank you!

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Pull request merged**
