### PR TITLE
reimplementation of Track classifiers and Track Collection mergers

### PR DESCRIPTION
**Pull request by VinInn**
have fully reimplemented track selectors and merger.
Separated all concerns:
one class to use mva,
one class to use cuts (mimics mva output)
one class to merge selectors
one class to merge collections.
to be done
re-implement duplicate identification and merging
port to HLT

do not esclude that some non-main-stream use-cases are not covered yet.
some more cleanup and optimization is surely required.

I have also implemented a macro to instantiate a sort of DynArray as C++14 does not support anymore
dynamical array.

Full backward compatibility is not maintained.
1) 
The vertex identification uses only delta-z and not the track-vertex association:
the latter (besides being utterly slow to verify with the current implementation) it is only working
for Iter0: tracks from all other iterations are not associated to any vertex
2)
quality looseSetWithPV and highPuritySetWithPV is not set (nobody is using it)
and does not make much sense when using MVA anyhow (it can mark if the mva is prompt or detached, maybe. TBD)
3) Iter5 and 6 are MVA only
4) Muon iterations cuts are not identical (and requires further tuning)
5) Duplicate rate a bit higher than before (it needs further tuning anyhow...)
6) JetCore uses a simplified cut-based selection, waiting for its own specific MVA

manually ported from CMSSW_7_5_X #9538 (original by @VinInn).
manual rebase of #10233

### CODE REVIEW

**Comment by VinInn** [comment]
@lveldere , please verify that the "merge" complies with your expectations

**Comment by VinInn** [comment]
FastSim is broken again as my fixes went in a class that has been now deleted.
No ETA for the fix at least from my side.
if @lveldere helps, we may converge before the end of the next week.

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
So, the FastSim errors prevent the workflows from running.
I think this should be fixed first.
@lveldere  Lukas, please check

**Comment by VinInn** [comment]
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Sun Jul 26 18:49:39 2015-date Sun Jul 26 18:41:54 2015; exit: 1 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Sun Jul 26 18:49:35 2015-date Sun Jul 26 18:41:55 2015; exit: 1 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Sun Jul 26 18:44:08 2015-date Sun Jul 26 18:41:57 2015; exit: 0 0
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Sun Jul 26 18:45:51 2015-date Sun Jul 26 18:42:00 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Sun Jul 26 18:51:15 2015-date Sun Jul 26 18:44:13 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Sun Jul 26 18:51:13 2015-date Sun Jul 26 18:45:54 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Sun Jul 26 18:56:34 2015-date Sun Jul 26 18:49:36 2015; exit: 1 0 0
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Sun Jul 26 18:54:20 2015-date Sun Jul 26 18:49:41 2015; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Sun Jul 26 18:57:57 2015-date Sun Jul 26 18:51:15 2015; exit: 1 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN  - time date Sun Jul 26 18:58:01 2015-date Sun Jul 26 18:51:18 2015; exit: 1 0 0 0 0 0
5 5 4 3 3 0 tests passed, 5 0 0 0 0 0 failed
```

workflow should be ok
results to be verified by @lveldere

**Comment by slava77** [comment]
@cmsbuild please test
... jenkins state is "rage" though
rage
so, tests will likely not go through immediately

**Comment by VinInn** [comment]
@makortel , can you give a "spin" of MTV for this PR as done for the previous pr?
thanks

**Comment by makortel** [comment]
Sure.

**Comment by smuzaffar** [comment]
looks like mesos plugin for jenkins was creating problems. We tried to 
restart the jenkins service yesterday but no use. So we now have 
disabled mesos plugin and are looking in to the issue.
For now, jenkins is back and running normal jobs. Few special IBs 
(DEVEL, THREADED, slc7, ROOT5), which need mesos/docker will not be 
build but we will update these to run on non-mesos nodes.

**Comment by lveldere** [comment]
@VinInn 

I'm available this afternoon and tomorrow to contribute if that is still needed.

**Comment by VinInn** [comment]
@lveldere 
if you can, just run a fastsim simulation with this PR to verify that no major regression is present,
thanks

**Comment by lveldere** [comment]
@VinInn 

okay, i'll try that out today.

**Comment by slava77** [comment]
@cmsbuild please test
... I couldn't find a pending test for this PR in jenkins (for which https://github.com/cms-sw/cmssw/pull/10373#issuecomment-125023379 was issued)

**Comment by lveldere** [comment]
@VinInn 

Changes to FastSim are minor.
Merge looks okay.

**Comment by lveldere** [comment]
+1

**Comment by makortel** [comment]
Here are the tracking validation results comparing ttbar noPU, QCD 3 TeV noPU, and ttbar 25ns PU 750pre6 samples re-recoed in CMSSW_7_6_X_2015-07-24-2300 and in the IB+this PR
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_6_X_2015-07-24-2300_pr10373/index.html

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
Here are some notable diffs from the comparisons:

QCD 3 TeV is a sample with the largest  noticeable impact on performance
- about 3% overall increase in the number of tracks is mainly from short tracks (5 hits or less), this is characteristic for most of the samples 
all_sign568vsorig_qcd13tevpt3ts3t5wf1313p0c_recotracks_generaltracks__reco_obj_found
- about 6% decrease in IVFs mostly on the low-track-count vertices, this doesn't seem to happen in less energetic jetty events
all_sign568vsorig_qcd13tevpt3ts3t5wf1313p0c_recovertexs_inclusivesecondaryvertices__reco_obj_trackssize
- loss in efficiency vs vertex position is quite evident in HP at intermediate vertex displacements; on the other hand there is a noticeable increase at high values (the increase in efficiency apparently is "balanced" by fake rate increase)
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_6_X_2015-07-24-2300_pr10373/75X_mcRun2_asymptotic_v1_noPU_highPurity/RelValQCD_Pt_3000_3500/effvspos.pdf

TTbar PU 35 has a similar feature in the vtxposition efficiency with HP selections
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_6_X_2015-07-24-2300_pr10373/75X_mcRun2_asymptotic_v1_PU_highPurity_25ns/RelValTTbar/effvspos.pdf


SingleElectron 1 TeV essentially all jetCore moved to the initialStep (probably OK). This doesn't happen in other samples.
all_sign568vsorig_singleelectron13pt1000wf1316p0c_recotracks_generaltracks__reco_obj_algo

On the technical side, there is a clear improvement in timing: there is about 1.6% decrease in the total reco time, coming primarily from the changes in the selectors -> classifiers.

All of it looks kind of "good enough" although the change appears to be an overall degradation in performance.
Would you like to tune some more?

**Comment by VinInn** [comment]
the comparison is w/r/t  750pre6 which is known to be buggy.
It should be compared w/r/t 750pre4 or better 760_pre1
The gain in efficiency at large "R" is intentional even if the fake rate increases.
Jet core is a special iteration as it is inclusive, so by itself tells us little.
About IVF: not sure how significant is in QCD 3TeV. we need to check in TTBAR and of course its impact
in BTV.
I think that we need, more generally, better understand (and tune) reco for very-high pt jets.
I consider these results "good enough". Matt is working on retuning jet-core using MVA. He is also looking to the duplicare remover.

@slava77,  If it is ok for you, I propose to merge this and continue validation and tuning
(at least the c++ part is in and hopefully stable)

**Comment by makortel** [comment]
@VinInn No, the comparison is wrt. 750pre6 RAW re-recoed in CMSSW_7_6_X_2015-07-24-2300, so it should show only the effect of this PR. I added 750pre4 to the plots behind the link (750pre1 has different directory names in the DQM file, and I didn't want to invest effort for that now).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10373	60e709a
- refactoring of selectors to classifiers introduces higher flexibility and speeds up tracking reco
- general track efficiency is mostly unchanged, some minor degradation in performance is seen with high-putrity selections. Short tracks added appear to be mostly fakes.
- updated tuning to selectors/classifiers is expected to come soon (hopefully, making things better)

**Comment by VinInn** [comment]
so wrt pre4 in
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_6_X_2015-07-24-2300_pr10373/75X_mcRun2_asymptotic_v1_noPU_highPurity/RelValTTbar/effvspos.pdf
we fully recovered the efficiency at large R.
the fake rate is a bit higher and will need some work work.
the efficiency for high-pt jet is higher, fake rate to be retuned.
I think we are going in the right direction

**Comment by VinInn** [comment]
@davidlange6 , analysis in not really touched

**Comment by davidlange6** [comment]
@VinInn @slava77 - so the thinking is that DynArray will not be something we want to store as a data format later?

**Comment by VinInn** [comment]
DynArray is allocated on the stack and does not make sense to store it.
With @makortel , we were thinking to propose to move to FWCore/Utilities a set of "utilities" that may be useful also outside tracker. We will prepare a specific PR for that

**Comment by slava77** [comment]
On 7/29/15 2:54 AM, Vincenzo Innocente wrote:
> DynArray is allocated on the stack and does not make sense to store it.
> With @makortel <https://github.com/makortel> , we were thinking to
> propose to move to FWCore/Utilities a set of "utilities" that may be
> useful also outside tracker. We will prepare a specific PR for that


I support this and looking forward for a PR.
The DynArray, to me, is just a more elegant VLA that doesn't disturb
llvm/clang

**Comment by davidlange6** [comment]
@VinInn - I believe this breaks the run1 tracking customize function. Could you update it?

    from RecoTracker.IterativeTracking.RunI_iterativeTk_cff import *
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_X_2015-07-29-2300/python/RecoTracker/IterativeTracking/RunI_iterativeTk_cff.py", line 16, in <module>
    earlyGeneralTracks.selectedTrackQuals[0] = cms.InputTag("initialStepSelector","initialStep")
AttributeError: 'EDProducer' object has no attribute 'selectedTrackQuals'

**Comment by VinInn** [comment]
nice...
will produce a separate PR, should be easy

**Comment by VinInn** [comment]
well in 760_pre2 + #10126
```
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT]$ cmsDriver.py step3 --datatier GEN-SIM-RECO,DQMIO --conditions auto:run1_mc -s RAW2DIGI,L1Reco,RECO,EI,ALCA:EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron+HcalCalIsoTrk,VALIDATION,DQM --eventcontent RECOSIM,DQM -n 100 --filein file:step2.root --fileout file:step3.root --customise RecoTracker/Configuration/customiseForRunI.customiseForRunI
```

produces
```
----- Begin Fatal Exception 31-Jul-2015 13:39:55 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 47 event: 4601
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module TrackingMonitor/'TrackSeedMonjetCoreRegionalStep'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<TrackCandidate>
Looking for module label: jetCoreRegionalStepTrackCandidates
Looking for productInstanceName: 
```

**Pull request merged**
