### PR TITLE
Change the type1 jet pt threshold from 10 to 15 GeV

### PR DESCRIPTION
**Pull request by mmarionncern**
Following the discussion of https://indico.cern.ch/event/446476/, the jet pT threshold in type1 MET is raised from 10 to 15 GeV.

Packages modified :
- JetMETCorrections/Type1MET
- PhysicsTools/PatUtils

Expected changes in performances :
All MET variables will be impacted in a quite minimal way. Preliminary studies shows that changes are indeed here, but minimal on DY/QCD/ttbar and W+jets events.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmarionncern** [comment]
ping?

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
