### PR TITLE
Clean unused HCAL DB packages

### PR DESCRIPTION
**Pull request by kpedro88**
I identified two packages of unused, unmaintained HCAL DB code: `OnlineDB/HcalCondDB` and `CaloOnlineTools/HcalOnlineDb`. I have removed these packages to reduce the incidental maintenance and dependency burden from their continued existence.

attn: @abdoulline, @bsunanda 

@smuzaffar @davidlange6 should I remove these packages from cms-bot/categories.py?

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@ggovi please take a look

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
