### PR TITLE
Add DQM module using HeavyFlavorAnalysis for BPH common decays

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

This PR adds a DQM module based on the HeavyFlavorAnalysis package to create plots for several decays relevant for BPH.
The new plots are available under Physics/HeavyFlavor in the DQM
A more detailed explanation of what plots are available can be found at https://indico.cern.ch/event/1119491/#1-tracking-monitor-in-bph-fina
This PR depends on PR #38524

#### PR validation:
The tests with runTheMatrix return ok, privately tested on a few relvals.
Added processing time is 0.11 s/ev, added size to a DQM file is 0.15%, increase in peak memory consumption is ~10MB

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported to 12_4_X

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test with #38524

**Comment by perrotta** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/38524

**Comment by elusian** [comment]
Hello
there are 12 decays tracked, each of them has 10 plots (120 plots). For each track in the decay there are 8 plots, there are 36 tracks total (288 plots).
For short lived decays (Onia, Psi2S, K*0, phi) we also split the plots based on whether they are used in a long lived decay. That adds 4*2 (4 decays, split by two) decay folders (80 plots) and (2+4+2+2)*2 tracks folders (160 plots). 
Sum is 648 as expected

**Comment by mmusich** [comment]
as far as I can see from [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-06-28-1500+cca9e8/51317/dqm-histo-comparison-summary.html) the 648 histograms are added flatly to most collision workflows. I am wondering if that really makes or we want to limit it somehow to certain datasets (in data) via autoDQM?

**Comment by emanueleusai** [comment]
@elusian thank you for the explanation, makes sense.
I am interested in @mmusich 's idea to limit to certain datasets, if it makes sense. Perhaps it can be limited to BPH's most used streams?

**Comment by elusian** [comment]
@emanueleusai we can in principle run this sequence only in the DoubleMuonLowMass primary dataset.
If I understand correctly, this implies creating a new Sequence in DQMOffline_cff (currently this module is inside PostDQMOfflineMiniAOD since it needs PAT), adding it to autoDQM.py and then have it added in the primary dataset sequences (not handled in this PR).
Is that ok?

**Comment by emanueleusai** [comment]
sounds correct to me

**Comment by mmusich** [comment]
@elusian, thanks for the update, two comments:
   * first I think the new sequence should be phase-2 allowed.
   * second, should we add the tag explicitly to some relval workflows? It seems to me, right now is not tested.

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1347, 1349, 1350, 1364, 1365, 1366, 136.884, 136.896, 136.860, 136.898
   * relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/38524
   * workflows = 1347, 1349, 1350, 1364, 1365, 1366, 136.884, 136.896, 136.860, 136.898
   * relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

**Comment by mmusich** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

From the upgrade side, the updated workflows run fine.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
