### PR TITLE
Removed deprecation warnings from  HLTrigger/JetMET

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- switched modules to be global::EDFilter
- improved const correctness of CommonHcalNoiseRBXData so it can be used with global::EDFilter
- removed unnecessary include of deprecated header

#### PR validation:

Code compiles without deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
