### PR TITLE
update configurations for phase2 Inner Tracker ntuple unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Trivial update of configuration on test configuration files after the updates introduced in https://github.com/cms-sw/cmssw/pull/27517 and https://github.com/cms-sw/cmssw/pull/27449

#### PR validation:

`scramv1 b runtests` in the local installation used to make this PR.

#### if this PR is a backport please specify the original PR:

This PR is not a backport.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
