### PR TITLE
PixelBarrelEfficiency75

### PR DESCRIPTION
**Pull request by fioriNTU**
Fix for pixel barrel hit efficiency plots

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests.
I don't see the corresponding fix for 74. don't you want to backport the fix there as well?
F.

**Comment by davidlange6** [comment]
+1

**Comment by fioriNTU** [comment]
Hi Federico,
sorry for late reply, I am just back from holidays. Actually I submitted 
a PR also for 74X with the same fix, looking in github 
(https://github.com/cms-sw/cmssw/pull/10624) the fix is in PR 10624. 
Could you check please?

Ciao,
FF

Il 14/08/2015 17.44, Federico De Guio ha scritto:
>
> +1
> provided it passes the tests.
> I don't see the corresponding fix for 74. don't you want to backport 
> the fix there as well?
> F.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/10632#issuecomment-131155264>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Pull request merged**
