### PR TITLE
Fix getByLabelWithoutRegistration (81X).

### PR DESCRIPTION
**Pull request by ndaci**
This is an 81X version of #13041 that was created by @jingyucms. 
The changes fix a segmentation fault.
The fix is urgently needed by the TSG/STEAM subgroup.

An 80X backport version will follow.

### CODE REVIEW

**Comment by civanch** [comment]
Modifications are fine but in non-modified line 223 std::auto_ptr is used. Should replacement of  std::auto_ptr be done in this PR or in the next one?

**Comment by ndaci** [comment]
Why should "std::auto_ptr" be replaced? And by what?
Thanks in advance for the clarification.

**Comment by civanch** [comment]
please test
In new compilers std::auto_ptr should be replaced by std::unique_ptr, if not possible then by std::shared_ptr

I would guess the fix should be done in a separate PR.

**Comment by davidlt** [comment]
@ndaci because it's deprecated by C++ standards since C++11.

**Comment by civanch** [comment]
@ndaci , the line 222 of MixingModule.cc is not needed at all, having such consumes within a loop is not a correct thing, in the constructor there is a place where HepMCProduct consumes declaration is set.

**Comment by ndaci** [comment]
Thanks for the tests and interpretations.
Ok, should I simply remove the incriminated line ?

**Comment by civanch** [comment]
I think so.

**Comment by civanch** [comment]
please test

**Comment by tobias-pook** [comment]
When do you plan the backport ? We plan to produce n-tuples for some groups with the production version 8_0_X soon and this fix is needed to include gen filter results. We otherwise need to merge topic from a user fork.

**Comment by ndaci** [comment]
The backport PR #14064 was open simultaneously. I got no news there for now.

**Comment by fwyzard** [comment]
> @ndaci , the line 222 of MixingModule.cc is not needed at all, having such consumes within a loop is not a correct thing, in the constructor there is a place where HepMCProduct consumes declaration is set.

Looks like the `consumes` was actually needed... @ndaci , can you make a PR for 8.0.x, 8.1.x and 9.0.x that adds it back ?

By the way, tje comment about it being inside a loop is just moot - if the module is configured with multiple input collections, `consumes` has to be called for all of them.

**Pull request merged**
