### PR TITLE
Powheg-bb4l FSR veto

### PR DESCRIPTION
**Pull request by mseidel42**
FSR emission veto for Powheg-bb4l by Tomas Jezo

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@intrepid42 can this be approved as it is? is there also a PR to master?

**Comment by intrepid42** [comment]
@perrozzi Yes, this should be ok as it is. PowhegHooksBB4L.h is nearly unaltered from the Powheg/b_bbar_4l repository, just added the veto counter.

Will do the PR for master later.

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
what was the master PR for this?

**Comment by intrepid42** [comment]
https://github.com/cms-sw/cmssw/pull/18856

**Comment by davidlange6** [comment]
+1

**Pull request merged**
