### PR TITLE
[JME NanoAOD] Backport of #32722 (Changes for event size reduction) to 10_6_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #32722

#### PR description:

This PR is to reduce the size of custom JME NanoAODs. The following changes are made:
- Check that `npuProd[ibx].getPU_pT_hats()` size is more than 0 in `PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc`.
- Switch on storing Parton Shower (PS) weights.
- b-tagging algorithm outputs are saved for AK4 jets with pT > 15 GeV.
- Low-level input variables for PileUp jet ID and Quark-Gluon Likelihood are saved for AK4 jets with pT > 10 GeV.
- Remove AK4 PF and AK8 PF jet collections.
- Add separate AK8 GEN and AK8 Puppi jet collections for JEC studies. Minimal information are saved.
- For reclustered GEN jet collections, the minimum pT at the jet clustering level uses the default value (3 GeV) in `RecoJets/JetProducers/python/ak4GenJets_cfi.py`.
- For reclustered reco-level jet collections, the minimum pT at the jet clustering level is set to be 0. Then, only jets with (JEC-corrected) pT > 8 GeV are saved. Additionally for MC samples, jets with pT < 8 GeV are saved if they are matched to GEN jets.

With this PR, the event size is now reduced to **6.42 kb/event** from **9.32 kb/event**. The comparison was made using 10K events from a TTJets RunIISummer19UL17MiniAOD sample. The changes in this PR was discussed in the 13/01/2021 XPOG meeting [1]. 

[1] https://indico.cern.ch/event/978436/

#### if this PR is a backport please specify the original PR:

Original PR is #32722

### CODE REVIEW

**Comment by slava77** [comment]
please test workflow 25202.15,10224.15,11024.15

(assuming the wf indices are the same in 106X)

**Comment by slava77** [comment]
backport of #32722

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32759	7b84fce 
- the backport is correct (the diffs here and in #32722 are the same); this PR is not affecting the production reco or re-miniAOD
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by gouskos** [comment]
+xpog

**Comment by silviodonato** [comment]
+1

**Pull request merged**
