### PR TITLE
Make EventSetupRecordDataGetter used by HLT a stream::EDAnalyzer

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Make EventSetupRecordDataGetter used by HLT a stream::EDAnalyzer

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
(errors were unrelated - ESRawToDigi hickup)

**Comment by Martin-Grunewald** [comment]
@ktf, @nclopezo 
I suppose 'please test' here does not work for me as I am not an L2 for the areas where
signature is required for this PR? In any case, can you trigger the tests now that the
ESRawToDigi is fixed via the full IB build?
Thanks

**Comment by Martin-Grunewald** [comment]
@Dr15Jones
Chris, could you please write 'please test' in this PR so that the tests are being redone
after the ESRawToDigi issue causing the tests to fail is now fixed? Thanks!

**Comment by nclopezo** [comment]
@Martin-Grunewald, There was a case in which @cmsbuild ignored the "please test". I fixed it, and from now on you should be able to trigger them again after the previous tests results are posted. @ktf

**Comment by Martin-Grunewald** [comment]
@nclopezo 
Thanks!

**Pull request merged**
