### PR TITLE
2015 Tracker Material Variations for 71x

### PR DESCRIPTION
**Pull request by ianna**
- Backport of https://github.com/cms-sw/cmssw/pull/14010:
- Tracker with +/- 5 and +/- 10 percent material

As requested by Federico Ferri in the context of systematic studies for the Higgs->gamma gamma analysis. The material variations produced by Giacomo Sguazzoni.

The DB payloads are marked with 71YV6 and will be included in Run 2 MC GT queues with labels.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
```
# in: /build/yana/CMSSW_7_1_19/relval going to execute cd 1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15
 cmsDriver.py ZMM_13TeV_TuneCUETP8M1_cfi  --conditions auto:run2_mc -n 10 --eventcontent FEVTDEBUG --relval 18000,300 -s GEN,SIM --datatier GEN-SIM --beamspot NominalCollision2015 --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 -n 2 --conditions=MCRUN2_71_V7::All --geometry Extended2015FlatPlus10Percent,Extended2015Reco --fileout file:step1.root  > step1_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1
 

# in: /build/yana/CMSSW_7_1_19/relval going to execute cd 1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15
 cmsDriver.py step2  --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --conditions auto:run2_mc -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval,RAW2DIGI,L1Reco --datatier GEN-SIM-DIGI-RAW-HLTDEBUG -n 10 --magField 38T_PostLS1 --eventcontent FEVTDEBUGHLT -n 2 --conditions=MCRUN2_71_V7::All --geometry Extended2015FlatPlus10Percent,Extended2015Reco --filein file:step1.root  --fileout file:step2.root  > step2_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1
 

# in: /build/yana/CMSSW_7_1_19/relval going to execute cd 1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15
 cmsDriver.py step3  --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --conditions auto:run2_mc -s RAW2DIGI,L1Reco,RECO,EI,VALIDATION,DQM --datatier GEN-SIM-RECO,DQMIO -n 10 --magField 38T_PostLS1 --eventcontent RECOSIM,DQM -n 2 --conditions=MCRUN2_71_V7::All --geometry Extended2015FlatPlus10Percent,Extended2015Reco --filein file:step2.root  --fileout file:step3.root  > step3_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1
 

# in: /build/yana/CMSSW_7_1_19/relval going to execute cd 1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15
 cmsDriver.py step4  --conditions auto:run2_mc -s HARVESTING:validationHarvesting+dqmHarvesting --filetype DQM --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --mc  --magField 38T_PostLS1 -n 2 --conditions=MCRUN2_71_V7::All --geometry Extended2015FlatPlus10Percent,Extended2015Reco --filein file:step3_inDQM.root --fileout file:step4.root  > step4_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1

```
```
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed May  4 09:13:46 2016-date Wed May  4 09:04:51 2016; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
