### PR TITLE
Added customizations to run pp reco on peripheral HI events

### PR DESCRIPTION
**Pull request by mandrenguyen**
Same as #13603 
Modifies number of cluster limits in tracking and allows us to store calotowers.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@mandrenguyen: When is a new 75X release with this PR needed?

**Comment by mandrenguyen** [comment]
Hi @cvuosalo 
Within a couple of weeks would be nice.

**Comment by slava77** [comment]
@mandrenguyen 
what kind of PbPb data do you expect this to run on?
Would it go all the way to HIHardProbes (IIRC, the more complex events are in it) ?

**Comment by mandrenguyen** [comment]
@slava77 Yes, but it will be run on the peripheral event triggers. 
Large scale tests have already been done for the 30-100% most central events, which show that the memory consumption is reasonable.

**Comment by slava77** [comment]
@mandrenguyen 
are these triggers selected separately or is there a filter that will need to be passed to the cmsDriver as well?

Will the reprocessing that you consider be done with central workflow submission machinery, or is this purely for (super)user level reprocessing at HI T2?

**Comment by mandrenguyen** [comment]
@slava77 Yeah, we'll have to filter on the trigger paths in the cfg.  I believe this will be done with the central workflow machinery, but using the Vanderbilt HI T2

**Comment by slava77** [comment]
IIRC, the central workflow machinery needs cmsDriver command.

**Comment by mandrenguyen** [comment]
@slava77 If it's not possibly to invoke the standard HLT path filter from driver, I guess we'll have to do something about that.  That seems outside the scope of this PR though, as that's potentially useful for other workflows.

**Comment by slava77** [comment]
@mandrenguyen 
Thanks for making the cut values updates.

For the peripheral triggers in HIHardProbes, wouldn't you just run on the HIHardProbesPeripheral PD?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
@slava77 The full plan of primary datasets and trigger paths to be processed is here:  https://twiki.cern.ch/twiki/bin/viewauth/CMS/PbPb2015PeriphReReco75Xpp
We will follow up and figure out how to process this combination of trigger paths and PDs outside the scope of this PR.

**Comment by slava77** [comment]
@mandrenguyen 
Is it going to be once in a lifetime processing case or do you plan to do something regularly?
For continuing support this setup likely needs a relval matrix setup.
It doesn't have to be in this PR, I'm just using this thread to understand initial goal.

I'd like to ask for a presentation in the next RECO meeting (will do more officially by email)

**Comment by mandrenguyen** [comment]
@slava77 Wei Li (current HI convener) is managing this.  I think he was going to make the request at PPD, but if you think it's more appropriate, I can advise him to present at RECO.

**Comment by slava77** [comment]
On 3/10/16 6:02 AM, mandrenguyen wrote:
> @slava77 <https://github.com/slava77> Wei Li (current HI convener) is
> managing this. I think he was going to make the request at PPD, but if
> you think it's more appropriate, I can advise him to present at RECO.

I think that both PPD and RECO will need to be aware of what goes in,
more so in case if you would like a regular relval setup.
pp with HI inputs looks like a pretty good candidate to be checked
regularly,
if this kind of reprocessing will happen again.

**Comment by slava77** [comment]
@mandrenguyen 
please clarify the logic to change the cuts in modifyClusterLimits method.
Specifically
- why was jetCoreRegionalStepSeeds ClusterCheckPSet.cut left unchanged. Is this intentional?
- somewhat technical at this point -- you also include modifications to the following modules that are not running in pp (more may be better, but if we cleanup the loaded modules in 81X, the customisations will fail since the don't check for existence of these modules):
```
	globalSeedsFromTriplets	
	globalMixedSeeds 	
	globalPixelLessSeeds
	globalPixelSeeds
	globalSeedsFromPairsWithVertices
	regionalCosmicTrackerSeeds
	photonConvTrajSeedFromQuadruplets
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13604	3dd7bfe
- code changes are in line with what needs to be done to get tracking to run on moderately complex HI inputs
- jenkins tests pass (they don't really test much)
- tested locally with HIHardProbes (262694 LS 190) and HIHardProbesPeripheral (262768 LS 378) from 2015 with a setup derived from 50ns relval processing, including extras that will not be used in HI reprocessing
```
cmsDriver.py step3  --conditions auto:run2_data_25ns14e33_v4\
 -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias\
 --runUnscheduled  --process reRECO --data  --eventcontent RECO,AOD,MINIAOD --scenario pp\
 --datatier RECO,AOD,MINIAOD --customise \
Configuration/DataProcessing/RecoTLR.customiseDataRun2Common,\
SLHCUpgradeSimulations/Configuration/postLS1Customs.customise_New_HCAL,\
RecoHI/Configuration/customise_PPwithHI.customisePPwithHI\
 -n 100 --filein file:a.root --repacked
```
    - HIHardProbes events fail track seeding in ~50% of events
    - HIHardProbesPeripheral didn't have any errors related to too many clusters
The events to be used in HI reprocessing are apparently even less dense than the inclusive HIHardProbesPeripheral
- caloTowers show up in the AOD event content and add about 10% to the file size.

**Comment by slava77** [comment]
BTW, the previous commit did not have the jetCore seed limits updated: about 10% of events were over the limit in HIHardProbesPeripheral; after the update they all passed.

**Pull request merged**
