### PR TITLE
re-insert HLTMon sequence everywhere

### PR DESCRIPTION
**Pull request by deguio**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
@deguio - do we then reintroduce all the printouts? Or are those fixed now?

**Comment by deguio** [comment]
ciao @davidlange6 
they will be fixed soon once the output module for the data relvals will be modified to save FEVTHLTDEBUG. @fabozzi is looking into this.
at the T0 we shouldn't suffer this problem since there specific sequences are called for each PD. the HLTMon sequence should effectively run on top of the HLTMonitor PD only (express-like).

**Comment by deguio** [comment]
this is final and merged in 76 and following

**Pull request closed without merging**
