### PR TITLE
Automatically size the Pixel FED buffer used by SiPixelRawToClusterCUDA [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Automatically resize the Pixel FED buffer used by `SiPixelRawToClusterCUDA` to construct a contiguous copy of the FED data to be copied to the GPU.

The value of the `MaxFEDWords` parameter is not used. It is kept for backwards compatibility with older configurations, but it will not be written to the cfi files and will be ignored if present.

#### PR validation:

Tested on events from run 355872 that would crash with a segmentation fault or raise an exception, because the Pixel had a larger occupancy than expected.
With these changes all crashes disappear.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. 

Backport of #38868 to 12.4.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #38868

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
urgent

**Comment by clacaputo** [comment]
+reconstruction

- backport #38868 
- technical PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
