### PR TITLE
Phase2-hgx270 Bug correction for HGCal scintillator Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug correction for HGCal scintillator Geometry

#### PR validation:

Tested using standard workflow of runTheMatrix

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
