### PR TITLE
Remove PileupJetIdAlgo from DQM/PhysicsHWW.

### PR DESCRIPTION
**Pull request by dmitrijus**
... and use the proper one from RecoJets/JetProducers.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
-1
some more update will come. rejecting for now after discussing with @dmitrijus 
to be kept open.

**Comment by dmitrijus** [comment]
Hi,

can be merged now. This removes all code and configuration which
originally was duplicated from RecoJets. Now the RecoJets code and 
configuration is used for DQM/PhysicsHWW.

Also backports https://github.com/cms-sw/cmssw/pull/8656 to 74x.
The additional (unusued) method caused the wrong method to be picked up at runtime
and all the parameter passing got screwed up (passing this=0x0) and segfaulting.

Please remove or tell me how to do it (I have no idea)
DQM/PhysicsHWW/data/mva_JetID_v1.weights.xml
from cms-data.

Dmitrijus

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Do we have the same change submitted in 75X as well?

**Comment by dmitrijus** [comment]
Hi,

not yet, but I will do that after we merge this one.

Dmitrijus

**Comment by davidlange6** [comment]
Hi all
I suggest that we should get this all to work in 75x first..

**Comment by deguio** [comment]
+1
@davidlange6 agreed. approving in the meantime.

**Comment by dmitrijus** [comment]
Done for 75x

**Comment by slava77** [comment]
@cmsbuild please test
(it looks like recent test jobs are coming back successful)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9350	 6da5b30
- reco is minimally affected (removal of actually unimplemented but declared function in RecoJets/JetProducers/interface/PileupJetIdAlgo.h 
- compilation went OK and jenkins run time tests completed as well

**Comment by deguio** [comment]
this one should be merged before #9919
thanks,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
