### PR TITLE
Run3-gex172 Update 2021 and 2023 scenarios with the corrected geometry for the GE21 demonstration chamber

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update 2021 and 2023 scenarios with the corrected geometry for the GE21 demonstration chamber

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
No difference is seen because we use DB (GT) for Run-3, not XML. What is the plan for new GT?
@bsunanda @cms-sw/alca-l2 
Thx.

**Comment by bsunanda** [comment]
Shall make new payloads but I don't know how to make a Global Tag for that

**Comment by bsunanda** [comment]
+geometry

**Comment by antoniovilela** [comment]
> Shall make new payloads but I don't know how to make a Global Tag for that

@cms-sw/alca-l2 @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

No change is expected from this PR as we use DB, not XML. The report of this issue can be found [here](https://indico.cern.ch/event/1333324/) (See status of geometry presentation).

**Comment by saumyaphor4252** [comment]
> Shall make new payloads but I don't know how to make a Global Tag for that

Hi @bsunanda yes please provide the new payload and we will take care of the GTs.

**Comment by antoniovilela** [comment]
+1
   - As discussed by e-mail, the GT update will be made after this pre-release (pre4) is out. The validation of the geometry will happen in the next pre-release (pre5).

**Pull request merged**
