### PR TITLE
Move `DiMuonMassBiasClient` to a regular harvesting path

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Inspired by the discussion at https://github.com/cms-sw/cmssw/issues/39180#issuecomment-1227738895 I move the `DiMuonMassBiasClient` to a regular harvesting path, actually into the `DQMHarvestMuon` sequence which as per `autoDQM` is run in the `@muon` sequence

https://github.com/cms-sw/cmssw/blob/d9d4aec32230b7d62e51c4622dfd654e8cea106a/DQMOffline/Configuration/python/autoDQM.py#L96-L99

that would be run at Tier-0 for the `Muon` PD (cf also: https://github.com/dmwm/T0/blob/0f4f9d27c5366da57c456c4ae01da81c75524595/etc/ProdOfflineConfiguration.py#L698)

I profit of this PR to remove [remove useless DMQToken produce and consumes](https://github.com/cms-sw/cmssw/commit/a5bab3b6c16061202c6fb8bbb6af0c0848d8a40a) as pointed out in https://github.com/cms-sw/cmssw/issues/39180#issuecomment-1227738895

#### PR validation:

Run successfully several workflows [that were failing](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_5/2022-08-24-2300?selectedArchs=el8_amd64_gcc10&selectedFlavors=X&selectedStatus=failed) before issue https://github.com/cms-sw/cmssw/issues/39180 was solved in threading mode:

```console
runTheMatrix.py -nel 1000.0,10042.0,10842.0 -j 8 -t 4
```

EDIT:
unfortunately I could not find a RelVal workflow in the matrix that mimics Tier0 in this respect (i.e. that runs `ALCA:TkAlDiMuonAndVertex` in the same step as DQM and then a regular harvesting, so I've created one for this purpose: 1002.4.

after that I've tested with :
```console
runTheMatrix.py -l 1002.4 -t 4 -j 8 --ibeos
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will need to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 10042.0,10842.0

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * enable_test = threading
   * workflows_threading =  10042.0,10842.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1002.4
   * relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by kskovpen** [comment]
+pdmv

Thanks Marco

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- Wouldn't it be worth adding the newly created 1002.4 workflow into the matrix used regularly for the PR tests, if it really mimics Tier0?

**Comment by mmusich** [comment]
> Wouldn't it be worth adding the newly created 1002.4 workflow into the matrix used regularly for the PR tests, if it really mimics Tier0?

arguably yes, and perhaps we should add also 1001.3 and 1002.3

**Comment by srimanob** [comment]
Good idea. Currently we have upto 2021 data defined in
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py

**Pull request merged**
