### PR TITLE
backport of PR #38502 to 12_2_x

### PR DESCRIPTION
**Pull request by agrohsje**
Hi @qliphy : backport of https://github.com/cms-sw/cmssw/pull/38502 to 12_2 for run3 winter 22 mc campaign .
You mentioned 12_3 as potential backport. However, I only found Phase 2 and cosmics at 13.6 TeV, so I think we only need backport to 12_2 and 12_4. Let me know if you had something else in mind. Thanks!

### CODE REVIEW

**Comment by agrohsje** [comment]
add generators

**Comment by Saptaparna** [comment]
+1

**Comment by Saptaparna** [comment]
Please test

**Comment by Saptaparna** [comment]
Sorry for initiating additional tests.

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
