### PR TITLE
added classes to store Phase2TrackerCluster1D

### PR DESCRIPTION
**Pull request by jdefaver**
minimal modification to be able to store Phase2TrackerCluster1D in standard workflows

@delaere @ebrondol @boudoul @lowette @atricomi @kpedro88

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
``` edm::RefProd<edmNew::DetSetVector<Phase2TrackerCluster1D> > ``` is
used in TrackClusterRemoverPhase2, which is not used anywhere.
I suppose, you'd discover the need for a dictionary much sooner if the TrackClusterRemoverPhase2 had a test config (I guess it wasn't tested at run time).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14958	e1e95db
- jenkins tests pass (compilation is enough)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
