### PR TITLE
Toward HLT menu V3.0 (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Toward HLT menu V3.0 (92X)
Based on CMSSW_9_2_9

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #20112

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for addOnTests.py change

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Could you please sign again? The core part (addOnTests) has not changed from your previous signature.

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
@Martin-Grunewald can you make PRs (for both 92x and 93x) to move the `@relval` HLT menu to the new v3 ?

**Comment by Martin-Grunewald** [comment]
@fwyzard Yes, sure!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
