### PR TITLE
CCLUT generator macro; LUTs in half-strip format (CCLUT-7)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Macro that generates the look-up tables for the Run-3 CSC trigger in https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives (both for CMSSW simulation and firmware). The script performs a linear fit to 5 (patterns) x 3942 (valid comparator codes) possible combinations of >= 3 hits in a CSC. The patterns are those in `CSCPatternBank::clct_pattern_run3_`. Fit results (plots can be found in [DN-19-059, Sec.4.2](https://gitlab.cern.ch/tdr/notes/DN-19-059/blob/master/temp/DN-19-059_temp.pdf)) are used in the CLCT processor to correct the key half-strip, and assign the 1/4-strip bit, 1/8-strip bit and the 5-bit CLCT bending angle. See also: https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/2.

There are 6 types of LUTs:
```
* CSCComparatorCodePatternConversionLUT_pat*_v1.txt: converts (Run-3 pattern, Comparator Code) -> Run-1/2 pattern
* CSCComparatorCodePosOffsetLUT_pat*_float_v1.txt:   Key half-strip position offset in floating point
* CSCComparatorCodePosOffsetLUT_pat*_v1.txt:         4-bit key half-strip position offset  
* CSCComparatorCodeSlopeLUT_pat*_float_v1.txt:       floating point slope
* CSCComparatorCodeSlopeLUT_pat*_v1.txt:             5-bit slope
* rom_pat*.mem:                                      memory files for CSC OTMB firmware
```

The CCLUT procedures in the CLCT processor have been updated to use the new LUTs.

#### PR validation:

Code compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
`printCode()` function was updated to print out the pattern like 
```
Pattern 0, Code 3793 111011010001
L1: --------X__ -> 01
L2: -------___- -> 00
L3: -----X__--- -> 01
L4: ---__X----- -> 11
L5: -_X_------- -> 10
L6: __X-------- -> 11
    0123456789a
```

**Comment by dildick** [comment]
And while I'm at it, I think I'll change the CCLUT functions in the CLCT processor, so that they are half-strip oriented.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
