### PR TITLE
CSC stub central BX shift

### PR DESCRIPTION
**Pull request by tahuang1991**
1. change the central BX in CSC digitizer, from 6 to 8 for wire digi and from 6 to 7 for strip digi
2. change the readout window for CSC common trigger, from [3,9] to [5,11]
3. change LCT central BX used in overlap muon track-finder, from 6 to 8
4. change the CSCInputBxShift in Endcap muon track-finder, from 0 to -2

### CODE REVIEW

**Comment by dildick** [comment]
@tahuang1991 don't forget to shift the central BX in the GEM-CSC trigger: https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/L1Trigger/CSCTriggerPrimitives/src/CSCMotherboard.cc#L138

**Comment by dildick** [comment]
can this code be tested please?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@tahuang1991 , in comparisons muons/CSC run-1 and run-2 2016 WF results are different. Is this expected?

**Comment by dildick** [comment]
@civanch it's quite possible that the results are different. We did not modify the legacy track-finder to account for the BX shift. We only modified the stage-2 track-finder.

**Comment by ptcox** [comment]
How can I see these differences? All I end up with is a pkl file that I 
do not know what to do with.
I do not understand why there would be differences in CSC simulation 
arising from shifting the BX0 time bin. That does not affect CSC 
simulation. But DigiToRaw is after L1 emulation so is something broken 
there?

Tim

Vladimir Ivantchenko wrote:

**Comment by civanch** [comment]
For example:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-07-2300+18226/19287/25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/ 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-09-1100+18211/19294/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/ 
Full list in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-04-07-2300+18226/19287/

What is the needs of the shift proposed in this PR? Is it for run-2 2017 or for run-2 in general?

**Comment by ptcox** [comment]
Thanks. Yes, I see the change to digi times has of course (with 
hindsight) induced changes in all time-related downstream histograms, 
e.g. rechit and segment times. Since the digi times have been changed 
the rechit times need to be re-tuned to center on 0 for IP muons. Those 
values are stored in conditions data separately for simulated and real 
data. New values for simulated muons need to be determined and added to 
conditions data. That will clearly take some time. I guess this 
modification cannot be approved until that is done.

Vladimir Ivantchenko wrote:

**Comment by tahuang1991** [comment]
Sure,  I think it is fine to postpone these changes. The central BX of CSC stubs are inconsistent between data and MC, and we then modified CSC Digitizer and L1 emulator to fix this. L1 emulator is where We reach so far. Anything related to offline reconstruction is unchanged and we also do not know how our modification would effect offline reconstruction. The reason why Sven and I pushed this to CMSSW is to make sure that everyone could be aware of this issue.

Cheers,
Tao

**Comment by dildick** [comment]
@tahuang1991 Something that we forgot, is to adjust the magic 6's in EMTFHitTools.cc:
* https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc#L14
* https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc#L102
* https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc#L117
* https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc#L82
* https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc#L112

In addition, a public member 
<PRE>
CSCConstants::Central_LCT_BX_MC = 8
</PRE> 
needs to be added to https://github.com/cms-sw/cmssw/blob/master/L1Trigger/CSCCommonTrigger/interface/CSCConstants.h

**Comment by davidlange6** [comment]
hi all - what are the plans for this PR?

**Comment by davidlange6** [comment]
seems no answer. Closing this.

**Comment by ptcox** [comment]
I missed your query about this.
It definitely needs some more work - rechit times must be tuned to center on 0 for IP muons and resulting values need to be inserted in conditions data for simulation. I believe this work was going to get done, but I haven't heard any recent news.
When all the pieces are ready I presume the updates will be submitted again.

Tim


On May 30, 2017 at 12:31:24, David Lange (notifications@github.com) wrote:

seems no answer. Closing this.

**Pull request closed without merging**
