### PR TITLE
Esmaeel new emtf

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by bortigno** [comment]
Hi @EsmaeelEskandari this PR has stuff that is running online and that is useful for the EMTF. I see that it is not included in the #16513 (which I understand should include everything for L1T) - am I wrong? can you please look at it? @abrinke1 @thomreis  

@dmitrijus  In addition in the DQM tag collector page I see that is referred as CLOSED which is also confusing. could you please clarify?

Thank you both!!

**Comment by thomreis** [comment]
@bortigno no this is not in PR #16513 but in #16518.

**Comment by bortigno** [comment]
thanks @thomreis !

**Comment by dmitrijus** [comment]
@EsmaeelEskandari Why is this a conflict? :(

@bortigno For the moment online DQM runs exactly the same code it was running a week ago. We haven't updated L1T application to 8_0_23, it runs the old 8_0_20. It runs this PR and few others.
This was a decision we made, since we could not get L1T integrated on top of 8_0_23.

Now I am waiting for a new release of 80x with hopefully most of the changes for L1T already present to continue. It does take time to do a proper review - these changes HUGE!

'CLOSED' on a pull requests means it won't be merged into CMSSW. We can still use that PR for instantiating a cmssw area in online DQM. We are already too many L1T pull requests open, which causes too much confusion and frustration to both me and the release integration team.

**Comment by EsmaeelEskandari** [comment]
Dear DQM core,

Is it needed to resolve 15748 PR conflicts?

Cheers,
Esmaeel.

**Comment by dmitrijus** [comment]
Well, if you want to have running online (from the tag collector).

**Pull request closed without merging**
