### PR TITLE
fixing some problems with HCAL DQM code

### PR DESCRIPTION
**Pull request by vkhristenko**
on top of PR13399 as it touches the config of hcalcalib application

1) eliminated try/catch
2) from OfflineMC sequence I remove RawTask module
3) put a copy constructor for ContainerSingle1D as it won't work as is when trying to place such an object into a vector... - crashes hcalcalib application otherwise... 

VK

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
@abdoulline 
Salavat, so we agreed that I remove TP Task from MC. But if I recall correctly, for Cosmics, we do need that. Am I right, or I'm being wrong once again...

VK

**Comment by abdoulline** [comment]
Viltor,

frankly I don't remember if anybody cares at all about HCAL TPs DQM in 
Cosmics data. But if it can be kept without much of efforts - why not do it.

S.

**Comment by vkhristenko** [comment]
I removed TP Task from Cosmics Offline Sequence.
needs a retest

VK

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please submit to 81x as well

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
@vkhristenko - seems there were problems with this PR reported by @Martin-Grunewald. We need also an 81x PR. Thanks! 

 believe this PR in 800patch2 creates this error in HIon workflow:

 %MSG
----- Begin Fatal Exception 27-Feb-2016 11:02:07 CET-----------------------
An exception of category 'HCALDQM' occurred while
   [0] Processing run: 1 lumi: 2 event: 301
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module TPTask/'tpTask'
Exception Message:
TPTask::Collection HcalTrigPrimDigiCollection isn't availablevalHcalTriggerPrimitiveDigis
----- End Fatal Exception -------------------------------------------------

**Comment by Martin-Grunewald** [comment]
I was referring to https://github.com/cms-sw/cmssw/pull/13488
but I assume this is the 80X version, not the 800patchX version...

**Comment by vkhristenko** [comment]
looking...

**Comment by vkhristenko** [comment]
@davidlange6 @Martin-Grunewald 

I have a stupid question, when trying to check for which workflow it threw this exception, 
https://github.com/cms-sw/cmssw/pull/13488 this guy points me here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13412/11427/summary.html

which was not the latest comparison tests performed. 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13412/11566/summary.html - these were the latest Tests performed and there were no errors or exceptions for the HI Workflow.... or any other.... Indeed 11427 did have that exception, but i believe it's not present anymore after the successive commits that I did.

Am I wrong??? 
VK

**Comment by Martin-Grunewald** [comment]
I do not know: the test where the failure occurs is NOT a standard PR jenkins test,
so you may simply not excercising the problem....

**Comment by vkhristenko** [comment]
@Martin-Grunewald , can you tell me the workflow number for the runTheMatrix???
My apology, I just want to try to reproduce this....

VK

**Comment by Martin-Grunewald** [comment]
@vkhristenko 
Its is failing on one of the TSG tests (generated with cmsDriver):
```
# with command line options: RelVal --step=RAW2DIGI,L1Reco,RECO,VALIDATION,DQM --conditions=auto:run2_mc_HIon --filein=file:RelVal_DigiL1RawHLT_HIon_MC.root --custom_conditions= --fileout=RelVal_RECO_HIon_MC.root --number=25 --mc --no_exec --datatier SIM-RAW-HLT-RECO --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.Base --era=Run2_HI --customise= --scenario=HeavyIons --python_filename=RelVal_RECO_HIon_MC.py --processName=RECO
```
I do not know anycorresponding relval matrix number... but I guess anything using teh above should do.

**Comment by vkhristenko** [comment]
Ok, so, jenkins tests didn't include HIon MC...
For pp I already did that once... i removed that module from mc hi

VK

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
@vkhristenko - could you rebase this - it no longer merges Thanks

**Comment by vkhristenko** [comment]
I think I did something stupid by merging 80X
will close and reopen on top of 80X branch
VK

**Comment by deguio** [comment]
superseded by #13543

**Pull request closed without merging**
