### PR TITLE
updated runTheMatrix: un-used code clean and new options for IB

### PR DESCRIPTION
**Pull request by smuzaffar**
- un-used code cleanup
- new option --maxStep=n added to run only first n steps
- if --step1=True is passed then only step1 is run and for rest of the steps it generates a wf_steps.txt file with all the exact commands to be run. Note the -n -e doe snot show the exact commands (input and output files are missing)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , if no objections then I would like to get this merged

**Comment by davidlange6** [comment]
hi @smuzaffar - i'm a bit lost by the "step1only" changes, which naively look like an option that is obsoleted by the maxsteps option. Was this step1only not fully implemented before?

**Comment by smuzaffar** [comment]
currently, the ```--step1``` option is only used with ```--showMatrix|-n``` to dump the das queries. ```--maxStep``` could replace --step1 one-day but for now I did not want to change the interface (no idea if any one outside is using it).

**Comment by smuzaffar** [comment]
I can update the PR so that WorkFlowRunning only use on maxStep

**Comment by davidlange6** [comment]
this would be best I think - then the obsolete option can get removed with some warning (eventually)

**Comment by smuzaffar** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by smuzaffar** [comment]
hold

**Comment by smuzaffar** [comment]
unhold

**Pull request merged**
