### PR TITLE
[BTV,DQM] Expand MiniAOD input DQM and Validations plots with latest taggers, switch to slimmedJetsPuppi

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR expands the BTV DQM & Validation plots by adding `ParticleNet` and `UParT`  taggers that are stored in MiniAOD. The jet collection has changed to AK4 Puppi jets (`slimmedJetsPuppi`). The working point cut values updated to Summer23BPix campaign. Removed a few files and consolidated their contents into a single file. 

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos` with the exception of a few workflows which failed because of missing relval input files.
- passes MiniAOD workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
please test

**Comment by nurfikri89** [comment]
Unit test fail due to this #46682?

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
> Unit test fail due to this #46682?

yes but it should be fixed now

**Comment by smuzaffar** [comment]
please test

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
