### PR TITLE
Temporary protection against missing jet corrector collection

### PR DESCRIPTION
**Pull request by fabiocos**
This PR, code proposed by Carlos Erice Cid in:
https://github.com/cericeci/cmssw/commit/2b5c37ca974963a275e6990bdf4c8875f26cdc35 
protects the top DQM modules for single leptons against missing input jet correction sequences,
that are causing failures at Tier0, see 
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1846.html
https://hypernews.cern.ch/HyperNews/CMS/get/dqmDevel/2406.html

It does not really solve the problem, that requires an update of the sequences to ensure that the producer of the needed collection run, but it protects against job failures.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 1001.2,1040.1

**Comment by fabiocos** [comment]
code privately tested to prevent the problem seen in express at the Tier0

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
