### PR TITLE
Urgent bugfix for miniaod covariance

### PR DESCRIPTION
**Pull request by arizzi**
Covariance information in miniaod 9XY is broken due to uninit data member when reading back from disk.
IOREAD added.

This PR also introduce a better exception when the user attempt to unpack tracks of candidates for which there are no track details

93X PR will follow in few minutes

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

the integration will proceed in normal order: 93X/master should go in first

**Comment by arizzi** [comment]
@slava77 that's fine #20234 is there already

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
in case the DAS errors are transient

**Comment by slava77** [comment]
backport of #20234

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20233	efce0b8
- the same change as in master/93X in #20234: adds a missing reset to the transient atomic data member m_, present already for other older similar data members
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
