### PR TITLE
[90X] Geometry independent SiPixelAli PCL

### PR DESCRIPTION
**Pull request by ghellwig**
- replace hard-coded labels with automatically deduced labels, based on the used tracker geometry
- move MillePede-related part from PCLTrackerAlProducer to MillePedeAlignmentAlgorithm
  --> step towards unification of PCLTrackerAlProducer and AlignmentProducer

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
hold

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
unhold

**Comment by mmusich** [comment]
@tlampen @mschrode @usarica - as verbally discussed yesterday during the alignment meeting - we'll wait for explicit sign-off on the HipPy side, since the algorithm is not run in the PR tests.

**Comment by ghellwig** [comment]
@usarica do you have any objections regarding this PR? Further development depends on its integration.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
