### PR TITLE
INVALID: New Fireworks aod configuration, additional checks for type ids in newItem callbacks

### PR DESCRIPTION
**Pull request by alja**

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
was this PR meant for 73x?

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
@alja - is this pr meant for 73x or 74x? Confused by the title..

**Comment by alja** [comment]
@davidlange6 
yes, that is for 73.

**Comment by davidlange6** [comment]
ok - but its in the 74 queue, so you'll want to make a new pull request�

**Comment by alja** [comment]
@davidlange6 
I see (I meant to be in 73 queue), I will make a new PR and close this one.

**Comment by alja** [comment]
The PR is redone at #7680

**Pull request closed without merging**
