### PR TITLE
point seeded tracking regions (backport PR #9149)

### PR DESCRIPTION
**Pull request by mtosi**
this PR is needed to make use of the point seeded tracking region
which might be very useful in order to cope w/ the slight inefficiency we see in the track reconstruction between 2 and 3 in phi

### CODE REVIEW

**Comment by slava77** [comment]
Mia
was this closed on purpose?

We need to move this code in later releases as well to /plugins instead of /src

**Comment by mtosi** [comment]
ciao,
yes, I closed it because it was not working at the beginning,
it should be fine, now
and I'm reopening it ... I noticed that I have to fix this code in 75x and 76x as well

**Comment by slava77** [comment]
Hi Mia,

Please move the producer to the /plugins directory.

Thanks

**Comment by mtosi** [comment]
I changed yesterday, but I forgot to push !
thanks for the reminder
it should be ok, now...shouldn't it ?

**Comment by slava77** [comment]
@cmsbuild please test

Mia, thank you.

**Comment by mtosi** [comment]
;)

**Comment by slava77** [comment]
Mia,
please update the PR subject here as well to be more descriptive (not just a pointer to a PR number)

Thanks

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10225	fc8f2e1
- code for PointSeededTrackingRegionsProducer was backported from 75X. It is not used in other places in the release at this point 
- jenkins test passed and showed no difference in comparisons with baseline as expected

**Comment by davidlange6** [comment]
@mtosi - please change the title to describe the changes in the PR - thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
