### PR TITLE
Update L1T Menu tag for 2023/2024/Run4 in MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR updates the L1T Menu tag in the MC GTs for 2023/2024/Run4 to the latest available tag, i.e. `L1Menu_Collisions2023_v1_1_0-v2_xml`, as requested in [this CMSTalk message](https://cms-talk.web.cern.ch/t/update-of-the-2023-l1-menu-tag-l1menu-collisions2023-v1-1-0/23386/3).

In addition, the `run3_[data|hlt]_relval` symbolic GTs are updated as well with the same tag via the autoCondModifier `L1TUtmTriggerMenuForRelValForRun3`.

*EDIT:*
As per @missirol's request I also updated the same tag in `Configuration/HLT/python/autoCondHLT.py`

FYI @caruta

The GT differences are:
 - **2023 design**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_design_v4/131X_mcRun3_2023_design_v5
 - **2023 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_v4/131X_mcRun3_2023_realistic_v5
 - **2023 cosmic realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_realistic_deco_v4/131X_mcRun3_2023cosmics_realistic_deco_v5
 - **2023 cosmic design**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_design_deco_v4/131X_mcRun3_2023cosmics_design_deco_v5
 - **2023 realistic HI**:
    - ~https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v9/131X_mcRun3_2023_realistic_HI_v10~
    - Superseeded by `131X_mcRun3_2023_realistic_HI_v11` which has the correct L1T Menu for HI (and it's also identical to the v9 GT)
 - **2024 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2024_realistic_v2/131X_mcRun3_2024_realistic_v3
 - **Phase2 realistic**:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun4_realistic_v3/131X_mcRun4_realistic_v4

#### PR validation:
Successfully tested with
`runTheMatrix.py -l 140.001,160.0,12434.0,12834.0,23234.0 -j 8 --ibeos`

#### Backport:
Not a backport, but a 130X backport will be provided soon.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
 - workflows = 140.001,160.0,12434.0,12834.0,23234.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
@francescobrivio , thanks for the PR. I would like to ask a favor, in order to minimise PRs (and backports).

Could you please update `autoCondHLT.py` [here](https://github.com/cms-sw/cmssw/blob/master/Configuration/HLT/python/autoCondHLT.py#L21-L22) as follows ?
```diff
-    'FULL'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0_xml'                        ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-04-26 12:17:38.000"] ), ),
-    'GRun'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0_xml'                        ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-04-26 12:17:38.000"] ), ),
+    'FULL'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0-v2_xml'                     ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-05-02 08:03:44.000"] ), ),
+    'GRun'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0-v2_xml'                     ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-05-02 08:03:44.000"] ), ),
```

**Comment by francescobrivio** [comment]
> @francescobrivio , thanks for the PR. I would like to ask a favor, in order to minimise PRs (and backports).
> 
> Could you please update `autoCondHLT.py` [here](https://github.com/cms-sw/cmssw/blob/master/Configuration/HLT/python/autoCondHLT.py#L21-L22) as follows ?
> 
> ```diff
> -    'FULL'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0_xml'                        ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-04-26 12:17:38.000"] ), ),
> -    'GRun'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0_xml'                        ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-04-26 12:17:38.000"] ), ),
> +    'FULL'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0-v2_xml'                     ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-05-02 08:03:44.000"] ), ),
> +    'GRun'         : ( ','.join( [ 'L1Menu_Collisions2023_v1_1_0-v2_xml'                     ,l1tMenuRecord,connectionString,l1tMenuLabel, "2023-05-02 08:03:44.000"] ), ),
> ```

Ciao @missirol, sure no problem!
Just two questions:
1. Is there a specific reason to use `"2023-05-02 08:03:44.000"` as you suggest? Or "my" `"2023-05-02 12:00:00.000"` works also for you?
2. This change should be applied to the 130X backport (coming soon) as well, correct?

**Comment by missirol** [comment]
>     1. Is there a specific reason to use `"2023-05-02 08:03:44.000"` as you suggest? Or "my" `"2023-05-02 12:00:00.000"` works also for you?

We usually put the exact timestamp of the tag in the db. This practise predates me, and I admit I don't know if it has any practical implications. If you don't disagree, I suggest to simply follow this practise (exact timestamp).
 
>     2. This change should be applied to the 130X backport (coming soon) as well, correct?

Correct.

**Comment by francescobrivio** [comment]
> If you don't disagree, I suggest to simply follow this practise for `autoCondHLT.py` (exact timestamp).

IIUC, as long as the timestamp is after the tag creation it should be fine, but sure I can follow the HLT convention - I will force-push the change in few minutes.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
+hlt

 - The HLT changes are okay (and thanks for updating `autoCondHLT.py`).

 - This PR is a prerequisite for integrating the next version of the 2023 HLT menu in a future PR in the next days (as that new HLT menu will require the L1T menu included here, i.e. `2023-v1_1_0`).

 - It might worth noting that the change to the 2023-HIon MC GT in this PR is somewhat counter to a change recently done by AlCa in #41202. I think this choice does not pose a problem to HLT per se, as the relevant HIon wfs (e.g. [here](https://github.com/cms-sw/cmssw/blob/85b455d63c5685b15564a5e0804565583e8b05ee/Configuration/PyReleaseValidation/python/relval_steps.py#L1827)) use a "fake" HLT menu (compatible with virtually any L1T menu). Maybe it would be good to clarify with L1T what is the intended L1T menu for this (HIon) GT, but this doesn't necessarily need to be clarified in this PR.

**Comment by francescobrivio** [comment]
hold

> It might be worth noting that the change to the 2023-HIon MC GT in this PR is somewhat counter to a change recently done by AlCa in https://github.com/cms-sw/cmssw/pull/41202. I think this choice does not pose a problem to HLT per se, as the relevant HIon wfs (e.g. [here](https://github.com/cms-sw/cmssw/blob/85b455d63c5685b15564a5e0804565583e8b05ee/Configuration/PyReleaseValidation/python/relval_steps.py#L1827)) use a "fake" HLT menu (compatible with virtually any L1T menu). Maybe it would be good to clarify with L1T what is the intended L1T menu for this (HIon) GT, but this doesn't necessarily need to be clarified in this PR.

Thanks for noticing Marino, indeed this was a miscommunication (and misunderstanding from my side).
I'll update the HI GT later this morning.

**Comment by francescobrivio** [comment]
unhold

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
+hlt

 - The HLT changes are okay (and thanks for updating `autoCondHLT.py`).

 - This PR is a prerequisite for integrating the next version of the 2023 HLT menu in a future PR in the next days (as that new HLT menu will require the L1T menu included here, i.e. `2023-v1_1_0`).

**Comment by saumyaphor4252** [comment]
+alca
- tests pass
- HLT changes are expected, and okay as mentioned above https://github.com/cms-sw/cmssw/pull/41485#issuecomment-1532202297
- other diffs only in MsgLogger

**Comment by perrotta** [comment]
+1
- Let have this merged before moving the master to 13_1_X, so that we can avoid one backport

**Pull request merged**
