### PR TITLE
Revert decrease of precision introduced in ea3f693d

### PR DESCRIPTION
**Pull request by maxgalli**
Backport to 13_3_X of https://github.com/cms-sw/cmssw/pull/43253

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by antoniovilela** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43253

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
