### PR TITLE
Fix compareStringsPlain error for 53X

### PR DESCRIPTION
**Pull request by hroskes**
Partial backport of #6244 to fix cosmic track splitting and other validations.  The NavigationSchool parameter is only needed for the 7X releases, but the compareStringsPlain fix is necessary in every release where the All In One Tool is used.

### CODE REVIEW

**Comment by mmusich** [comment]
@tlampen @hroskes, to ease the integration procedure in 53X, could you please merge the committs of PR #6587 #6475 #6459 and #6071 in a single PR? All the updates are in the same package. 
Thanks

**Comment by hroskes** [comment]
@mmusich @tlampen, I just rebased this branch on the other PRs

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
