### PR TITLE
Ecal AlcaReco for Electrons

### PR DESCRIPTION
**Pull request by shervin86**
Summary of changes to ALCARECO definition:
- two event contents 
  - EcalCalElectron -> existing but updated (light version of AOD + gsfTracksExtra)
  - EcalUncalElectron -> new format (saving all ECAL DIGIs for fast ECAL rerecoes)
- 3 selections defined:
  - Zee -> two electrons
  - ZSC -> 1 electron + 1 SC at highEta
  - Wenu 
- 6 ALCARECO paths: 2 output formats x 3 selections
- 4 ALCARECO streams defined:
  - EcalCalZElectron: running two paths (Zee and ZSC) on DoubleElectron, EcalCalElectron output format
  - EcalCalWElectron: running the Wenu path on SingleElectron, EcalCalElectron output format
  - EcalUncalZElectron: same as EcalCalZElectron, but EcalUncalElectron output format
  - EcalUncalWElectron: same as EcalCalWElectron, but EcalUncalElectron output format
- Addition path defined but stream not running on any PD:
  - EcalRecalElectron: runs over  EcalUcal{Z,W}Electron

Changelog:
- cleaned BuildFile
- separated plugins
- code cleanup and porting to CMSSW_7_4
- new selections defined in python
- new streams defined (see above)
- added few instructions in documentation to test the streams

@ferriff @crovelli @emanueledimarco would like to follow the PR

### CODE REVIEW

**Comment by shervin86** [comment]
How to run the matrix by myself to check after the fixes?
Should I then close this PR and make another one with fixes?

**Comment by shervin86** [comment]
I've not changed the following files:
- Configuration/StandardSequences/ReconstructionCosmics_cff.py
- RecoLocalCalo/HcalRecProducers/HBHEIsolatedNoiseReflagger_cfi.py
but one error comes from them:

```
ValueError: Trying to override definition of hbhereco while it is used by the sequence localReconstructionCosmics
 new object defined in: /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_4_X_2015-02-18-1400/python/RecoLocalCalo/HcalRecProducers/HBHEIsolatedNoiseReflagger_cfi.py
 existing object defined in: /afs/cern.ch/work/s/shervin/CMSSW_7_4_X_2015-02-18-1400/python/Configuration/StandardSequences/ReconstructionCosmics_cff.py
```

**Comment by davidlange6** [comment]
@shervin86

First - this needs to go in 75x

As for the error - you are for some reason including Reconstruction_cff in a cosmics reco job. This is not allowed and creates the error. Perhaps your reconstruction better belongs in the reco sequence

**Comment by emanueledimarco** [comment]
@davidlange6 This is the definition of the datasets format and selections for the Z->ee / W->menu skim that will be used with startup data (I think will be 74x). This does not touch any plan for MC.
If 75x is for after data taking, then we need this as a fix for 74x.

**Comment by davidlange6** [comment]
On Feb 20, 2015, at 3:29 PM, Emanuele Di Marco <notifications@github.com>
 wrote:

> @davidlange6 This is the definition of the datasets format and selections for the Z->ee / W->menu skim that will be used with startup data (I think will be 74x). This does not touch any plan for MC.
> If 75x is for after data taking, then we need this as a fix for 74x.
> 

yes - you and many others:) But develop in 75x while we get 74x ready for MC production

**Comment by emanueledimarco** [comment]
@davidlange6 ok, thanks. I think this is reasonable. @shervin86 Can you close this PR and put it on the 75x queue, please?

**Comment by shervin86** [comment]
Closing this PR.

**Pull request closed without merging**
