### PR TITLE
[14_0_x Backport] EXOSoftDisplacedVertices skim

### PR DESCRIPTION
**Pull request by LangFelixAT**
Backport of #43936

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 140.103, 141.103

**Comment by AdrianoDee** [comment]
@LangFelix1 could you change the name of the PR to make it clear it's a 14_0_X back port? As is it looks like a duplicate when browsing the PR list.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
