### PR TITLE
Fixes in CalibTracker/SiStripChannelGain

### PR DESCRIPTION
**Pull request by Dr15Jones**
replaced non-standard __gnu_cxx::hash_map with std::unordered_map
removed the use of a static variable

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by arunhep** [comment]
+1

@Dr15Jones does this moving from hash_map to unordered_map saves some CPU time?

**Comment by Dr15Jones** [comment]
Switching from `__gnu_cxx::hash_map` to `std::unordered_map` probably makes no difference for CPU or memory use. However, classes in the namespace `__gnu_cxx` are gcc extensions to the language and not standard. `std::unordered_map` is standard and available on all compilers.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
