### PR TITLE
Phase2-hgx360C increase the debug tools for testing the forthcoming V19 version of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

increase the debug tools for testing the forthcoming V19 version of HGCal geometry

#### PR validation:

Use scripts in Geometry/HGCalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@subirsarkar please approve this PR

**Comment by bsunanda** [comment]
@srimanob @subirsarkar Please approve this PR

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
