### PR TITLE
Remove CSCTriggerGeometry and CSCTriggerGeomManager

### PR DESCRIPTION
**Pull request by dildick**
The class `CSCTriggerGeometry` is not thread-safe. Instead, one should  use `CSCGeometry`. `CSCTriggerNumbering` has sufficient auxiliary functions to obtains a CSC's ring and chamber number. This PR removes the class `CSCTriggerGeometry` and `CSCTriggerGeomManager` and related calls from CMSSW.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
please test
(Several differences are reported in the jenkins outputs, but they likely come from the many other commits tested together with this one. Let retry launching the tests: up to now I see no pull requests merged on top of the latest CMSSW_10_0_X_2017-12-06-2300, therefore I hope this one will get tested independently)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21655	b51f729
- technical cleanup from the reco perspective
- jenkins tests pass and comparisons with baseline show no differences

**Comment by dmitrijus** [comment]
+1

**Comment by dildick** [comment]
@rekovic could you sign please?

**Comment by davidlange6** [comment]
merge

**Pull request merged**
