### PR TITLE
remove ROOTCLING ifdefs that are no longer needed (were never?) 

### PR DESCRIPTION
**Pull request by davidlange6**
given that cling understands c++ - changes block modules build. There is one more case in DataFormats/Common that changes class definition so we are still looking at that one.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by jpata** [comment]
@davidlange6 for my understanding, do you know if the cling-based functionality of ` DPGAnalysis/SiStripTools`, `DataFormats/CaloTowers` is tested anywhere? I understand they are processed during `scram b`, but I'm not sure if any output validation is done. Just curious.

**Comment by davidlange6** [comment]
Yes, both packages have dictionaries.

On Jul 17, 2020, at 2:13 PM, Joosep Pata <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> for my understanding, do you know if the cling-based functionality of DPGAnalysis/SiStripTools, DataFormats/CaloTowers is tested anywhere? I understand they are processed during scram b, but I'm not sure if any output validation is done. Just curious.

**Comment by makortel** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by jpata** [comment]
+1

**Comment by silviodonato** [comment]
please test

> Reco comparison results: 19 differences found in the comparisons

this is the first time is see changes in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-07-16-2300+7ea8b7/37785/validateJR/all_mini_OldVSNew_TTbarPUwf25202p0/all_mini_OldVSNew_TTbarPUwf25202p0c_edmTriggerResults_TriggerResults__RECO_obj_paths__20__accept.png

**Comment by slava77** [comment]
hold

**Comment by jpata** [comment]
I approved by mistake, thanks for catching the issues. I'll check again the comparisons.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

On Jul 21, 2020, at 8:56 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



-1

Tested at: 0b6087b<https://github.com/cms-sw/cmssw/commit/0b6087bebc6e6d4945d7d9476b4ade142c611457>

CMSSW: CMSSW_11_2_X_2020-07-20-2300
SCRAM_ARCH: slc7_amd64_gcc820
You can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7ea8b7/8165/summary.html

I found follow errors while testing this PR

Failed tests: UnitTests

  *   Unit Tests:

I found errors in the following unit tests:

---> test materialBudgetTrackerPlots had ERRORS

**Comment by davidlange6** [comment]
interesting.. so how does one go from path[21] (or 28 or 29) to cff for that filter?

**Comment by davidlange6** [comment]
ok, the job log 
trkPOGFilters
trkPOG_manystripclus53X
trkPOG_toomanystripclus53X

which are using Multiplicities.h

**Comment by davidlange6** [comment]
I begin to reach the conclusion that this PR fixes rather than breaks.

Eg, we have a met filter that computes two multiplicities in tracker and flags
cut = cms.string("( mult2 > 20000+7*mult1)")
and a second one with
cut = cms.string("(mult2>50000) && ( mult2 > 20000+7*mult1)")

In the current test workflows I looked at (136.731), these never fire. however, printouts suggest that it should

Eg, in the first few events I see
mult1 = 3396 mult1 = 36895. 
  --> should be both false
mult1 = 6033 mult2 = 65940
  --> should be both true
mult1 = 3939 mult2 = 47651
  --> one should be true the other false

anyway, its a bit deep into StringCutObjectParser for me to be confident in not missing something.

(but if so - have these filters been used in run2?)

**Comment by jpata** [comment]
Thanks for the investigations @davidlange6 ! Is it known why the behaviour of the multiplicities changes with the removal of the cling defs?

As for if these paths have been used and what the change in output entails, perhaps @mtosi @JanFSchulte know?

thanks.

**Comment by davidlange6** [comment]
I don’t, no. I’m not familiar with how the cut parser relies on dictionaries @Dr15Jones maybe does? The class structure here is quite different with and without the defs (which means the dictionary looked different than the class object in memory)

On Jul 22, 2020, at 1:59 PM, Joosep Pata <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the investigations @davidlange6<https://github.com/davidlange6> ! Is it known why the behaviour of the multiplicities changes with the removal of the cling defs?

As for if these paths have been used and what the change in output entails, perhaps @mtosi<https://github.com/mtosi> @JanFSchulte<https://github.com/JanFSchulte> know?

thanks.

**Comment by mtosi** [comment]
ciao, sorry for this naive question,but 
https://cmssdt.cern.ch/dxr/CMSSW/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc#97
is a "standard" EDFilter ? I mean, it adds a flag into the Event and then return the boolean
is this boolean used as in the EDFilters ?

**Comment by mtosi** [comment]
the cut should reflect outliers in the 2D plot which summaries the correlation between the strip and pixel clusters multiplicities https://tinyurl.com/y2fa4494

**Comment by davidlange6** [comment]
Yes, its input to a MET filter, which is what’s showing a monitoring difference

On Jul 22, 2020, at 2:56 PM, mia tosi <notifications@github.com<mailto:notifications@github.com>> wrote:



ciao, sorry for this naive question,but
https://cmssdt.cern.ch/dxr/CMSSW/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc#97
is a "standard" EDFilter ? I mean, it adds a flag into the Event and then return the boolean
is this boolean used as in the EDFilters ?

**Comment by mtosi** [comment]
the code https://cmssdt.cern.ch/dxr/CMSSW/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc#47
is an EDFilter which adds a flag w/ the result of the expression and returns the boolean itself

are you telling me that it returns True regardless of the results of the expression ?

**Comment by davidlange6** [comment]
You can see that from the monitoring plots here for example

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-07-21-1100+7ea8b7/37901/validateJR.html


On Jul 22, 2020, at 3:02 PM, mia tosi <notifications@github.com<mailto:notifications@github.com>> wrote:



the code https://cmssdt.cern.ch/dxr/CMSSW/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc#47
is an EDFilter which adds a flag w/ the result of the expression and returns the boolean itself

are you telling me that it returns True regardless of the results of the expression ?

**Comment by mtosi** [comment]
similar cut is applied in the offline reco, actually it was supposed to be applied
https://cmssdt.cern.ch/lxr/source/RecoTracker/TkSeedGenerator/python/trackerClusterCheck_cfi.py#0007 (!!!)
@VinInn can you remind me the reason for not having retuned this cut ?
I remember (old) studies which highlighted how similar selections were able to clean beam background events or events w/ issues in the detector

it is true that some LLP might find interesting some off-diagonal events

and therefore, we would really want to remove these flags from the MET filters

**Comment by VinInn** [comment]
No clue

**Comment by Dr15Jones** [comment]
> I don’t, no. I’m not familiar with how the cut parser relies on dictionaries @Dr15Jones maybe does? The class structure here is quite different with and without the defs (which means the dictionary looked different than the class object in memory)

The cut parser uses the dictionary to associate the names of functions (which are in the cut) to the actual functions to be called. If the use of `#define` lead to a _one definition rule_ violation then we are in compiler undefined territory.

**Comment by davidlange6** [comment]
Its pretty clear that the goal was to isolate everything in the class not needed to evaluate the function call from the root dictionary. This includes member data changes. There are a variety of PRs doing this dating from 2013 and 2014… Some were as part of the root6 migration clearly - so possibly this broke in run2 where it looks like the filter is also not desired for detector reasons (well, I guess that was only after 2017)

On Jul 22, 2020, at 3:48 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:



I don’t, no. I’m not familiar with how the cut parser relies on dictionaries @Dr15Jones<https://github.com/Dr15Jones> maybe does? The class structure here is quite different with and without the defs (which means the dictionary looked different than the class object in memory)

The cut parser uses the dictionary to associate the names of functions (which are in the cut) to the actual functions to be called. If the use of #define lead to a one definition rule violation then we are in compiler undefined territory.

**Comment by jpata** [comment]
@davidlange6 thanks for that summary. For completeness, could you drop a hint here how you traced the issue exactly to the modules
```
trkPOGFilters
trkPOG_manystripclus53X
trkPOG_toomanystripclus53X
```
When I produce the job log with `process.options.wantSummary=True`, I only find the TrigReports for the generic trigger paths, not the granular triggers/cffs, so I must be missing something. Thanks!

**Comment by davidlange6** [comment]
On Jul 23, 2020, at 4:36 PM, Joosep Pata <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> thanks for that summary. For completeness, could you drop a hint here how you traced the issue exactly to the modules

trkPOGFilters
trkPOG_manystripclus53X
trkPOG_toomanystripclus53X


When I produce the job log with process.options.wantSummary=True, I only find the TrigReports for the generic trigger paths, not the granular triggers/cffs, so I must be missing something. Thanks!


With wantSummary you should have the output of each path in the job. Reco+Mini has a main path plus a path for each met filter (and skims and alcas and…). The counting of those paths is apparently the same as in the histogram. Eg

TrigReport     1   28        100        100          0          0 Flag_trkPOG_manystripclus53X

Then RecoMET/METFilters has the definitions of the paths

**Comment by jpata** [comment]
Per David's quick investigations above (thx for the tips!), I also confirm that this PR seems to change the behaviour in trkPOGFilters, trkPOG_manystripclus53X, trkPOG_toomanystripclus53X in the a number of investigated events. 

I observe on the workflow `136.731`:
```
Begin processing the 4th record. Run 274199, Event 40112763, LumiSection 21
...
  this PR                                                  |  base release

  name=(mult2>50000) && ( mult2 > 20000+7*mult1)           |  name=(mult2>50000) && ( mult2 > 20000+7*mult1)
  mult2=47651                                              |  mult2=0
  value=0                                                  |  value=0
  name=( mult2 > 20000+7*mult1)                            |  name=( mult2 > 20000+7*mult1)
  mult1=3939                                               |  mult1=3939
  mult2=47651                                              |  mult2=0
  value=1                                                  |  value=0
```
(full logs in `/afs/cern.ch/user/j/jpata/public/30748/*.log`)

which seems rather like a different input (`mult2=0` in the base release) than a different behaviour of the cut parser. Perhaps I miss something.

**Comment by davidlange6** [comment]
hi @jpata - I think you are correct - I must have miss understand the log. I gather these multiplicities are subdet=5 (aka, Pixel) and subdet=0 (aka, Strip) with the number of clusters from clusterSummaryProducer as the metric. Is 0 expected for one of these (mult2 is nominally strips if I got it right)?

**Comment by jpata** [comment]
When I print out the raw data in https://github.com/cms-sw/cmssw/blob/master/DataFormats/TrackerCommon/interface/ClusterSummary.h#L109 the behaviour in the base release seems incorrect as you point out. The multiplicity vectors contain valid numbers, however, the `mult2()` function returns 0. I have not been able to understand the underlying reason, but I suspect it's something along the lines of Chris's suggestion of undefined behaviour.

Now the question is how to proceed. Would it be viable to merge this PR which fixes a bug but changes previous behaviour?
As I understand from Mia above, for the TRK pog, these bugged filters could be removed. How about JetMET @ahinzmann @lathomas @kirschen (sorry I'm not sure who is the reco contact)?

**Comment by jpata** [comment]
The Multiplicities data structure contains physical and valid data up until the call to `StringCutObjectSelector::operator()`, at which point `mult2=0` and the stack trace as recorded by `gdb` becomes corrupted. 

This further points to the fact that the base release has undefined behaviour, which could be due to conflicting class definitions between the dictionaries as interpreted by cling and compiled by gcc. 

The behaviour of `ByClusterSummaryMultiplicityPairEventFilter` with this PR included seems correct, i.e. the Multiplicities data structures contain reasonable values throughout and the `StringCutObjectSelector` returns reasonable outputs. I would say this PR can be merged, with the understanding that previously incorrect behaviour is changed and corrected.

There seems to be one other spot in cmssw where `#ifdef __ROOTCLING__` is used to substantially change the class: https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/DetSetVectorNew.h#L13.

**Comment by davidlange6** [comment]
Yes, I opened a PR for that which has some runtime issues that I’ve yet to understand..



There seems to be one other spot in cmssw where #ifdef __ROOTCLING__ is used to substantially change the class: https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/DetSetVectorNew.h#L13.

**Comment by jpata** [comment]
+1

- fixes previously buggy result in `ByClusterMultiplicityFilter` that changes reco output in some trigger paths: `trkPOGFilters, trkPOG_manystripclus53X, trkPOG_toomanystripclus53X`
- code looks good and is otherwise technical, i.e. no algorithmic changes

**Comment by silviodonato** [comment]
+1

**Pull request merged**
