### PR TITLE
Phase2-sim157 Update the scripts in SimG4Core/PrintGeomInfo to handle the new scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts in SimG4Core/PrintGeomInfo to handle the new scenarios

#### PR validation:

Tested the new scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
