### PR TITLE
bsunanda:Run2-alca63 Update isotrack code needed for validation of simulation

### PR DESCRIPTION
**Pull request by bsunanda**
To utilize MC sample generated with event weight the code is updated and also added facility to PU weighting

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
