### PR TITLE
hltGetConfiguration updates to deal with FinalPaths and new OutputModule

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

hltGetConfiguration updates to deal with FinalPaths and new OutputModule
Based on CMSSW_12_2_1

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/36878
Required by new ConfDb

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type backport

**Comment by Martin-Grunewald** [comment]
backport of #36878

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
