### PR TITLE
Cleanup Configuration/Generator/python

### PR DESCRIPTION
**Pull request by perrozzi**
Removed 7TeV and 8TeV old cfg.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
I have learnt from https://github.com/cms-sw/cmssw/pull/19668 and https://github.com/cms-sw/cmssw/pull/19843 that some workflows fails won't be captured by the runTheMatrix test. 
What shall I do to avoid problems?
Shall I sign and promptly fix any report of failing compilation of the IB?
Other options?
@Dr15Jones

**Comment by Dr15Jones** [comment]
@perrozzi By 

> some workflows fails won't be captured by the runTheMatrix test.

I assume you mean the limited number of workflows run during the pull request testing cycle.

>What shall I do to avoid problems?
Shall I sign and promptly fix any report of failing compilation of the IB?
Other options?

If you know a specific workflow that uses code in a pull request, you can explicitly add that workflow number to the `please test` request. Else you could checkout the pull request yourself and do a full `runTheMatrix`. I do that sometimes when I worry the framework code might hit a rarely used case. But mostly I just let it go into the IB and promptly fix a problem that arises.  My personal philosophy is the IBs are there expicitly to catch such cases.

**Comment by davidlange6** [comment]
Grepping through the workflows in runTheMatrix.py -l all -ne should tell you all of the configs in use.

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
