### PR TITLE
Include HI menu in 75X

### PR DESCRIPTION
**Pull request by perrotta**
This pull request integrates the HLT menu for the HI runs of 2015, as it will be saved for future runs and used for the HI MC production.

The HI menus fir CMSSW_7_5_X are not yet complete, because we still miss the one for the pp reference runs at 5 TeV. A dedicated pull request will be prepared as soon as ready.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1

**Comment by diguida** [comment]
@perrotta please take my commit with the following from your release:

````
$ git remote add diguida https://github.com/diguida/cmssw.git
$ git fetch diguida
$ git checkout includeHImenuIn75X
$ git cherry-pick 11dd190
````

**Comment by diguida** [comment]
and then push:

````
git push my-cmssw includeHImenuIn75X
````

**Comment by perrotta** [comment]
@diguida : done, thanks!

**Comment by perrotta** [comment]
(Now tests should get restarted...)

**Comment by perrotta** [comment]
please test

**Comment by diguida** [comment]
@perrotta given that you put the changes made by me in https://github.com/diguida/cmssw/commit/11dd190a1cabd89c2dc1b2956f93dba8ae665886 into https://github.com/cms-tsg-storm/cmssw/commit/f5462865ae2464615c4150cd9ce1e218871dcdd9, the cherry-picked commit https://github.com/cms-tsg-storm/cmssw/commit/fd8663d36b5daa6ab3350b4735d9a6a025aac521 is only explanatory test :-).
Maybe you want to squash the two commits...

**Comment by perrotta** [comment]
Yes, I know.
But I want to be sure that there are no conflicts, then I picked your  
commit as well: quite likely it was not needed, but it doesn' hurt also.
A.


Salvatore Di Guida <notifications@github.com> ha scritto:

**Comment by mmusich** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by diguida** [comment]
re-running the test I made in #12637:
````
$ runTheMatrix.py -i all -l 140.1,145.0,300.0
140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 19:23:58 2015-date Wed Dec  2 19:22:40 2015; exit: 0 16640 0 0
145.0_HydjetQ_MinBias_5020GeV+HydjetQ_MinBias_5020GeVINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 19:24:48 2015-date Wed Dec  2 19:22:42 2015; exit: 0 16640 0 0
300.0_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  2 19:37:56 2015-date Wed Dec  2 19:22:47 2015; exit: 0 0 0 0
3 1 1 1 tests passed, 0 2 0 0 failed
````

The errors in `140.1` and `145.0` are:

````
----- Begin Fatal Exception 02-Dec-2015 19:23:54 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module GenHIEventProducer/'heavyIon'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generator

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
````

**Comment by diguida** [comment]
wf `300.0` is ok, so I believe wf `140.{0,4},145.0` were previously broken.

**Comment by diguida** [comment]
Indeed: https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc491;CMSSW_7_5_X_2015-11-30-2300:
140.2, 140.3 failing with DAS error
140.1, 1401.4 failing with the same error as https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161402953: see https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_5_X_2015-11-30-2300/pyRelValMatrixLogs/run/140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI/step2_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI.log
300.{0,2} ok

**Comment by diguida** [comment]
I confirm that the wf currently running in IB for HI Run2 MC are ok:

````
301.0_Pyquen_DiJet_pt80to120_2760GeV+Pyquen_DiJet_pt80to120_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  2 22:08:45 2015-date Wed Dec  2 21:47:49 2015; exit: 0 0 0 0
302.0_Pyquen_ZeemumuJets_pt10_2760GeV+Pyquen_ZeemumuJets_pt10_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  2 22:04:47 2015-date Wed Dec  2 21:47:50 2015; exit: 0 0 0 0
2 2 2 2 tests passed, 0 0 0 0 failed
````

**Comment by Martin-Grunewald** [comment]
@musich @diguida @lveldere 

There is a problem with FastSim for the new HIon HLT menu:
```
----- Begin Fatal Exception 03-Dec-2015 07:29:00 CET-----------------------
An exception of category 'InvalidInput' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'reconstruction_step'
   [2] Calling event method for module L1FastjetCorrectorProducer/'ak4PFL1FastjetCorrector'
Exception Message:
 cannot find key 10 in the JEC payload, this usually means you have to change the global tag
----- End Fatal Exception -------------------------------------------------
```

The GT used is ```'75X_mcRun2_HeavyIon_v10'```, ie the new ```'run2_mc_hi'```.
Or could it be that FastSim runs standrad reco as opposed to HI reco?

What does key-10 mean?

The cmsDriver command is 
```
# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: TTbar_Tauola_13TeV_cfi --step=GEN,SIM,RECOBEFMIX,DIGI,L1,L1Reco,RECO,HLT:HIon --fast --conditions=auto:run2_mc_HIon --custom_conditions= --fileout=FastSim_GenToHLT_HIon_MC.root --number=25 --mc --no_exec --datatier GEN-SIM-DIGI-RECO --eventcontent FEVTDEBUGHLT --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --customise=SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1_HI --customise= --scenario=HeavyIons --python_filename=FastSim_GenToHLT_HIon_MC.py --processName=HLT
```

**Comment by mmusich** [comment]
@Martin-Grunewald the key-10 means that it is missing the L1 Fast Jet corrections (that are needed for the HLT step...) https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/CondFormats/JetMETObjects/interface/JetCorrectorParameters.h#L118. We have a payload correcting for that (the one we actually deployed online)

**Comment by Martin-Grunewald** [comment]
@mmusich 
Could you please add the payload to the HIon GT?

**Comment by mmusich** [comment]
a new GT needs to be integrated @diguida

**Comment by diguida** [comment]
@mmusich I suppose it is the `AK4PF` label that needs to be changed.

**Comment by mmusich** [comment]
I suspect that also the `AKCalo` needs it...
```
$conddb list JetCorrectorParametersCollection_HI_PythiaCUETP8M1_5020GeV_753p1_v10_AK4Calo_offline
$ conddb dump 1e7673fed9c20fc35241c49e71784162a0d15a9c > 1e7673fed9c20fc35241c49e71784162a0d15a9c.xml
$ less 1e7673fed9c20fc35241c49e71784162a0d15a9c.xml | grep first
<first>1</first>
<first>2</first>
```
key = 10 is missing too

**Comment by diguida** [comment]
hold
ok, I think something is really wrong in the JEC for HI both in MC and data... Let's ask the developer.

**Comment by hengne** [comment]
@diguida @mmusich i think this time i am in the right PR.

**Comment by hengne** [comment]
@diguida @mmusich has this [https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161406179] been fixed already in some other PR, or we still need to look into it?

**Comment by hengne** [comment]
@diguida @mmusich @davidlange6 @davidlt @yetkinyilmaz 
I found the crash here [https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161406179]  is coming from the last commit [https://github.com/cms-sw/cmssw/commit/fcc5b236d2df80db3f6fc2af33645bf27a6d5d21]  in PR [https://github.com/cms-sw/cmssw/pull/12344], which was added in between CMSSW_7_5_5_patch1 and CMSSW_7_5_5_patch2 . The line added is here [https://github.com/cms-sw/cmssw/pull/12344/files#diff-10b0ede38d51cb80eb0d12828aa6213dR5]:
```
 heavyIon = cms.EDProducer("GenHIEventProducer",
-                            doReco     = cms.bool(True),
-                            doMC       = cms.bool(True),
-                            generators = cms.vstring("generator"),
-                            ptCut      = cms.double(0),
+                          src = cms.InputTag("mix","generator"),
                           )
```
 I am trying to understand this, and found there is no such a module with label "mix" and instance "generator" in the sequence. The "process.mix" in the sequence is not about "generator".  I couldn't found a solution yet. Could any of you have a look and help to fix this? Maybe @yetkinyilmaz ?

**Comment by yetkinyilmaz** [comment]
I am working on fixing this right now.
This should not hold the PR #12644
The workflow 300 should be ok right now and it can be sufficient for the 
test.

**Comment by diguida** [comment]
@yetkinyilmaz it does not hold this PR, but it holds release validation as we have massive HI RelVal MC failures. As a consequence, we cannot test the changes of this PR.

**Comment by yetkinyilmaz** [comment]
@diguida @hengne the PR to fix the GenHIEventProducer problem above is:
https://github.com/cms-sw/cmssw/pull/12660

**Comment by diguida** [comment]
@perrotta @Martin-Grunewald I have done the needed fix in data and MC GT: https://github.com/cms-sw/cmssw/compare/CMSSW_7_5_X...diguida:includeHImenuIn75X_v1
Please force the update of the history of this branch by doing this:

````
$ cmsrel CMSSW_7_5_X_2015-12-03-1100
$ cd CMSSW_7_5_X_2015-12-03-1100/src/
$ cmsenv
$ git cms-init
$ git remote add cms-tsg-storm https://github.com/cms-tsg-storm/cmssw.git
$ git fetch cms-tsg-storm
$ git remote add diguida https://github.com/diguida/cmssw.git
$ git fetch diguida
$ git checkout -b includeHImenuIn75X_v1 diguida/includeHImenuIn75X_v1
$ git cms-addpkg Configuration/AlCa
$ git cms-addpkg Configuration/HLT
$ git cms-addpkg FastSimulation/Tracking
$ git cms-addpkg HLTrigger/Configuration
$ git cms-checkdeps -a
$ scram b -r -j 32
#run your tests here
$ git push cms-tsg-storm +HEAD:includeHImenuIn75X
````

**Comment by hengne** [comment]
@yetkinyilmaz thanks!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
@diguida : I cherry-picked in this PR the latest commit in your 
https://github.com/cms-sw/cmssw/compare/CMSSW_7_5_X...diguida:includeHImenuIn75X_v1
which is the only difference between our branches as far as I can see.
Please tell me in case anything else got forgotten,.

**Comment by diguida** [comment]
@perrotta it is ok, the changes in autoCond are correctly picked, but looks like github does not like it, as I rebased my branch:
https://github.com/cms-tsg-storm/cmssw/compare/includeHImenuIn75X...diguida:includeHImenuIn75X_v1

**Comment by diguida** [comment]
please test

**Comment by perrotta** [comment]
@diguida : rebased to CMSSW_7_5_X_2015-12-03-1100

**Comment by diguida** [comment]
@perrotta thanks. Still github fails to see them the same, but the changes w.r.t. the base CMSSW_7_5_X are the same:

````
$ git diff --stat CMSSW_7_5_X_2015-12-03-1100..cms-tsg-storm/includeHImenuIn75X
 Configuration/AlCa/python/autoCond.py                         |    12 +-
 Configuration/HLT/python/autoCondHLT.py                       |     8 +-
 FastSimulation/Tracking/python/HLTIterativeTracking_cff.py    |     1 +
 HLTrigger/Configuration/python/HLT_FULL_cff.py                | 10480 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------
 HLTrigger/Configuration/python/HLT_GRun_cff.py                |  1333 +++++++++++----------
 HLTrigger/Configuration/python/HLT_HIon_cff.py                | 11501 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------
 HLTrigger/Configuration/python/HLT_PIon_cff.py                |   737 ++++++++----
 HLTrigger/Configuration/python/HLT_PRef_cff.py                |  8415 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 HLTrigger/Configuration/python/HLTrigger_Datasets_HIon_cff.py |    27 -
 HLTrigger/Configuration/python/HLTrigger_Datasets_PRef_cff.py |    44 +
 HLTrigger/Configuration/python/Tools/options.py               |     3 +-
 HLTrigger/Configuration/python/customizeHLTforCMSSW.py        |     5 +-
 HLTrigger/Configuration/python/customizeHLTforMC.py           |     2 +
 HLTrigger/Configuration/tables/HIon.txt                       |   279 ++++-
 HLTrigger/Configuration/tables/PRef.txt                       |    18 +
 HLTrigger/Configuration/tables/makeOnlineHIon                 |     2 +-
 HLTrigger/Configuration/tables/makeSubTables                  |     6 +-
 HLTrigger/Configuration/tables/online_hion.txt                |   281 ++++-
 HLTrigger/Configuration/test/OnLine_HLT_FULL.py               | 12587 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------
 HLTrigger/Configuration/test/OnLine_HLT_GRun.py               |  1427 ++++++++++++-----------
 HLTrigger/Configuration/test/OnLine_HLT_HIon.py               | 12533 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------
 HLTrigger/Configuration/test/OnLine_HLT_PIon.py               |   821 ++++++++-----
 HLTrigger/Configuration/test/OnLine_HLT_PRef.py               |  8928 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 HLTrigger/Configuration/test/cmsDriver.csh                    |    14 +-
 HLTrigger/Configuration/test/getHLT.sh                        |     7 +-
 HLTrigger/Configuration/test/runAll.csh                       |     2 +-
 HLTrigger/Configuration/test/runOne.csh                       |     6 +-
 27 files changed, 61142 insertions(+), 8337 deletions(-)
$ git diff --stat CMSSW_7_5_X_2015-12-03-1100..includeHImenuIn75X
 Configuration/AlCa/python/autoCond.py                         |    12 +-
 Configuration/HLT/python/autoCondHLT.py                       |     8 +-
 FastSimulation/Tracking/python/HLTIterativeTracking_cff.py    |     1 +
 HLTrigger/Configuration/python/HLT_FULL_cff.py                | 10480 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------
 HLTrigger/Configuration/python/HLT_GRun_cff.py                |  1333 +++++++++++----------
 HLTrigger/Configuration/python/HLT_HIon_cff.py                | 11501 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------
 HLTrigger/Configuration/python/HLT_PIon_cff.py                |   737 ++++++++----
 HLTrigger/Configuration/python/HLT_PRef_cff.py                |  8415 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 HLTrigger/Configuration/python/HLTrigger_Datasets_HIon_cff.py |    27 -
 HLTrigger/Configuration/python/HLTrigger_Datasets_PRef_cff.py |    44 +
 HLTrigger/Configuration/python/Tools/options.py               |     3 +-
 HLTrigger/Configuration/python/customizeHLTforCMSSW.py        |     5 +-
 HLTrigger/Configuration/python/customizeHLTforMC.py           |     2 +
 HLTrigger/Configuration/tables/HIon.txt                       |   279 ++++-
 HLTrigger/Configuration/tables/PRef.txt                       |    18 +
 HLTrigger/Configuration/tables/makeOnlineHIon                 |     2 +-
 HLTrigger/Configuration/tables/makeSubTables                  |     6 +-
 HLTrigger/Configuration/tables/online_hion.txt                |   281 ++++-
 HLTrigger/Configuration/test/OnLine_HLT_FULL.py               | 12587 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------
 HLTrigger/Configuration/test/OnLine_HLT_GRun.py               |  1427 ++++++++++++-----------
 HLTrigger/Configuration/test/OnLine_HLT_HIon.py               | 12533 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------
 HLTrigger/Configuration/test/OnLine_HLT_PIon.py               |   821 ++++++++-----
 HLTrigger/Configuration/test/OnLine_HLT_PRef.py               |  8928 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 HLTrigger/Configuration/test/cmsDriver.csh                    |    14 +-
 HLTrigger/Configuration/test/getHLT.sh                        |     7 +-
 HLTrigger/Configuration/test/runAll.csh                       |     2 +-
 HLTrigger/Configuration/test/runOne.csh                       |     6 +-
 27 files changed, 61142 insertions(+), 8337 deletions(-)
````

**Comment by perrotta** [comment]
@diguida : if you are fine now with this PR, could you please un-hold?

**Comment by diguida** [comment]
@perrotta almost there... We need another change to the re-reco GT. Please update your last commit by cherry-picking https://github.com/diguida/cmssw/commit/5e5452200640cdffea9dbb5336fb246402cc18bb

**Comment by diguida** [comment]
@perrotta almost there... We need another change to the re-reco GT. Please update your last commit by cherry-picking https://github.com/diguida/cmssw/commit/f7f73bdc0b85f337a2bef8e3bb8eff5119bd7a7e

**Comment by diguida** [comment]
unhold
Once the latest commit is picked, we are fine.

**Comment by perrotta** [comment]
cherry-picked your last commit (difference with previous here in last 28ae940d90b7408c6ccf60eb5bc3f107f2bc98fc)

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi , @lveldere, @ssekmen @civanch 
Could you please sign for fastsim?
Thanks!

**Comment by civanch** [comment]
+1
from my point of view it is minimally concern of FastSim

**Comment by davidlange6** [comment]
+1

**Pull request merged**
