### PR TITLE
FRDStreamSource Dangling Reference Fix : 12_4_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR fixes a dangling reference in FRDStreamSource when reading multiple error stream files. The fileNames() function returns  std::vector<std::string> which the code sets iterators to which then instantly become invalid as they are dangling. 

This keeps an internal copy of the returned std::vector<string> and sets the iterators to that. 

#### PR validation:

It now successfully processes events in multiple files rather than spewing random garbage to the terminal. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Will be backported to 12_3_X as useful for hilton setup there.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test
Thanks for finding and fixing it!

**Comment by smorovic** [comment]
+1

**Comment by missirol** [comment]
type bugfix

**Comment by perrotta** [comment]
+1

**Pull request merged**
