### PR TITLE
Removed unneeded uses of unique_ptr from GsfElectronAlgo

### PR DESCRIPTION
**Pull request by Dr15Jones**
In addition to being a code cleanup, this avoids an apparent compiler bug in clang 7 where default constructors are required but missing.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This fixes the linking problem seen in the CLANG IBs

**Comment by Dr15Jones** [comment]
please test

**Comment by guitargeek** [comment]
Thank you, I missed that in my last PR.

**Comment by guitargeek** [comment]
Are the remaining unique pointers also causing these clang errors by the way? They are a bit more involving to get rid of.

**Comment by Dr15Jones** [comment]
@guitargeek 
> Are the remaining unique pointers also causing these clang errors by the way? They are a bit more involving to get rid of.

Only 1 caused a clang problem. The ones I didn't change seemed to be a reasonable use of `std::unique_ptr`.

**Comment by perrotta** [comment]
@Dr15Jones , for my own education:
- You say that only 1 caused a clang problem: is it GeneralData, correct?
- If so, why did you remove the unique_ptr also for EventSetupData?
- (Saying it differently) why didn't you remove it also for EventData and ElectronData? Only because they are a bit more involved to get rid of it?

**Comment by Dr15Jones** [comment]
@perrotta 
> (Saying it differently) why didn't you remove it also for EventData and ElectronData?

GeneralData and EventSetupData were being 'new'ed in the constructor and 'delete'd in the destructor thereby having a lifetime equal to the parent class. That is exactly the same lifetime as member data.

EventData and ElectronData are 'new'ed and 'delete'd each event.

**Comment by perrotta** [comment]
Right.
Thank you Chris!


Chris Jones <notifications@github.com> ha scritto:

**Comment by Dr15Jones** [comment]
ping

**Comment by Dr15Jones** [comment]
This change is needed to fix the broken builds on CLANG

**Comment by perrotta** [comment]
+1
- The fix is technical and integrate what proposed in the description (and thank you Chris for the further explanation)
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
