### PR TITLE
81x: fix SiPixelAli PCL update logic

### PR DESCRIPTION
**Pull request by mmusich**
- SiPixelAli workflow activated when Tier-0 moved to 80X_dataRun2_Express_v12 [Tier-0 HN](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1471/1/1/1/1.html)
- 5 uploads performed in the period 2016-08-04 / 2016-08-06
  - link to [ConditionsUoploader Logs](https://cms-conddb.cern.ch/logs/dropBox/searchUserLog?beginDate=2016-07-01&fileName=SiPixelAli&endDate=2016-08-08&metadata=&fileHash=&userText=&username=&backend=&statusCode=Any)
- Runs used to compute uploads:
  - 278167: [ALCAPROMPT DQM](https://goo.gl/r7AU0W)  (not justified)
  - 278175: [ALCAPROMPT DQM](https://goo.gl/2U5msD) (justified)
  - 278193: [ALCAPROMPT DQM](https://goo.gl/b9X9AS)  (not justified)
  - 278239: [ALCAPROMPT DQM](https://goo.gl/uajZvz)  (not justified)
  - 278240: [ALCAPROMPT DQM](https://goo.gl/jBtPa6)  (not justified)

Unexpected upload pattern understood as a bug in the applied corrections size check → reverted the last update of the DropBoxMetadaRcd, to redirecting alignment producer output to the pre-DB (latest since is at run 278272). Consumed uploads are not problematic, issue only with the rate.
We’ll revert this change, when bug in PCL code fixed.

attn: @mschrode @ghellwig @tlampen

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
@mmusich I must admit that I never checked the logic in the result file reader, but if I understood it correctly, the current code would trigger an update if one of the movements is above `maxMoveCut_`, but a later alignable shows a movement between `Cutoffs[alignableIndex]` and `maxMoveCut_`. Is this the intended behaviour?
This leads me to the question what the exact rationale is for `maxMoveCut_`. Against what exactly are you protecting with this?

**Comment by mmusich** [comment]
Hi @ghellwig we want to prevent the PCL machinery to automatically put in place very large diplacements  > `maxMoveCut_`, because the change in physics output of Prompt Reco might be sizable and we want to first check it via validation procedure. The maximum value should be set now to 200 um for translations, which is larger than any movement measured since beginning of operations.

**Comment by ghellwig** [comment]
@mmusich thanks for clarifying. But still, shouldn't the following `continue` statement be a `break` statement?

https://github.com/mmusich/cmssw/blob/25bc784e977aaadf0db253e23bf7777bb169e1d2/Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc#L167

Otherwise, we will trigger an update in the scenario I described above in https://github.com/cms-sw/cmssw/pull/15385#issuecomment-238220740.

**Comment by mmusich** [comment]
@ghellwig indeed. I believe same holds true for the `std::abs(ObsErr) > maxErrorCut_)`

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
please test
@mmusich I agree with you. On a different note: The code in this class can be streamlined by removing the private members which are anyway not used, if I am not mistaken:
```
    bool PedeSuccess = false;
    bool Movements   = false;
    bool Error       = false;
    bool Significant = false;
    bool HitMax      = false;
    bool HitErrorMax = false;
```

These are just set and never read.

**Comment by mmusich** [comment]
@ghellwig done, cleaned it up for all unused variables

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig actually thinking it better I believe that those parameters were originally included to be used in the  "non-expert" canvas of the DQM monitoring, it was just not implemented, but I think would be still desirable.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@mschrode @tlampen @ghellwig if you don't have further comments I would proceed with approval and backport.

**Comment by tlampen** [comment]
No additional comments, please proceed, thanks for fixing this!

**Comment by ghellwig** [comment]
@mmusich I am fine with leaving them in, but in this case the following line is probably wrong:

https://github.com/mmusich/cmssw/blob/6234e9971b4019bfecc7ef090ec04ce8c511f9ce/Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc#L166

Anyways, I was not suggesting to remove all members, but only the ones without public methods to access them.
My proposal is to fix L166 and leave the other variables. Of course, only if this line is indeed wrong, since there is no hint what this variable is intended to be used for.

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided tests are passing

**Comment by davidlange6** [comment]
+1

**Pull request merged**
