### PR TITLE
HGCAL V6 geometry Z partitions

### PR DESCRIPTION
**Pull request by vandreev11**
@bsunanda, @pfs, @lgray New HGCAL V6 geometry Z partition for HE backing calorimeter as 6 and 6 layers

### CODE REVIEW

**Comment by vandreev11** [comment]
@mark-grimes, @fratnikov I wonder why it is not yet merged. Thanks

**Comment by fratnikov** [comment]
Two reasons:
1. this is XML, so doesn't affect nightly builds. v6 is not in RelVals. 
  Thus this waits until further progress with v6
2. modified file doesn't look specific to v6: is v5 intact with these PR?

**Comment by vandreev11** [comment]
@fratnikov 2. v5 is in tact, in the sense that v5 geometry is frozen and is not affected by v6. Particle Flow needs to be synchronized.

**Comment by fratnikov** [comment]
merge
This affects nothing than v6 HGCAL indeed

**Pull request merged**
