### PR TITLE
Update triggers for Run2 monopole analysis

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to update the trigger used for whole Run2 skim for monopole analysis

#### PR validation:
Skim was run already. This is to update the trigger name only. 2017/2018 triggers are the same.

#### if this PR is a backport please specify the original PR:
This PR will need to backport as it will be used for UL processing.

### CODE REVIEW

**Comment by srimanob** [comment]
Hi @kfjack,
Here is the update for monopole skim.

**Comment by srimanob** [comment]
Hi @zhenhu @pgunnell @prebello 
Could you please trigger the test? This is needed for the new 10_6_1. Thx.

**Comment by fabiocos** [comment]
please test

**Comment by prebello** [comment]
> Hi @zhenhu @pgunnell @prebello
> Could you please trigger the test? This is needed for the new 10_6_1. Thx.

done by Fabio

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
