### PR TITLE
74x: Merge Fireworks changes from 73

### PR DESCRIPTION
**Pull request by alja**
merge changes from:
#8368
#7910
#8473

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@alja  - looks like the forward ported (to 75x) version of this PR creates problems for ROOT6. Could you have a look and propose a fix? thx

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_5_X_2015-03-24-2300/Fireworks/Core

**Pull request merged**
