### PR TITLE
add customisation for pixel gains to 11_1_X

### PR DESCRIPTION
**Pull request by jsalfeld**
#### PR description:

adding pixel gain customisation at HLT to 11_1_X.

backport of #31655

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
@jsalfeld please make a PR for `master`. We can backport a PR in `11_1` only after having merged it in `master`

**Comment by fwyzard** [comment]
@silviodonato this PR is a (partial) backport of https://github.com/cms-sw/cmssw/pull/31655

@jsalfeld could you add also the `customiseFor2018Input` function from that same PR ?
```python
def customiseFor2018Input(process):
    """Customise the HLT to run on Run 2 data/MC"""
    process = customisePixelGainForRun2Input(process)
    process = synchronizeHCALHLTofflineRun3on2018data(process)
```

**Comment by silviodonato** [comment]
backport of #31655

**Comment by jsalfeld** [comment]
> @silviodonato this PR is a (partial) backport of #31655
> 
> @jsalfeld could you add also the `customiseFor2018Input` function from that same PR ?
> 
> ```python
> def customiseFor2018Input(process):
>     """Customise the HLT to run on Run 2 data/MC"""
>     process = customisePixelGainForRun2Input(process)
>     process = synchronizeHCALHLTofflineRun3on2018data(process)
> ```

@fwyzard my recent commit should add the function, if I understand correctly

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
