### PR TITLE
Introduce AlCaPPS_Run3 scenario

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Another T0 replay (https://github.com/dmwm/T0/pull/4686) revealed that we are missing another scenario. This PR adds that.

#### PR validation:
doing
```
cmsrel CMSSW_12_5_X_2022-06-15-1100
cd CMSSW_12_5_X_2022-06-15-1100/src
cmsenv
git cms-addpkg Configuration/DataProcessing
git cms-adpkg IOPool/Streamer
scram b -j
```
edit `IOPool/Streamer/test/NewStreamIn2_cfg.py`
so that it reads
`/eos/cms/store/t0streamer/Data/ALCAPPS/000/352/929/run352929_ls0006_streamALCAPPS_StorageManager.dat`

then doing
```
python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario ppEra_Run3 --global-tag 123X_dataRun3_Prompt_v11 --lfn=file:myout11.root --alcareco PPSCalMaxTracks
 cmsRun -e RunPromptRecoCfg.py
```
I can reproduce the problem in https://github.com/dmwm/T0/pull/4686.

After this PR doing 
```
python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario AlCaPPS_Run3 --global-tag 123X_dataRun3_Prompt_v11 --lfn=file:myout11.root --alcareco PPSCalMaxTracks
 cmsRun -e RunPromptRecoCfg.py
```

I get the file running with the correct output
```
Type                                  Module                      Label             Process   
----------------------------------------------------------------------------------------------
BXVector<GlobalAlgBlk>                "hltGtStage2ObjectMap"      ""                "HLT"     
GlobalObjectMapRecord                 "hltGtStage2ObjectMap"      ""                "HLT"     
edm::TriggerResults                   "TriggerResults"            ""                "HLT"     
trigger::TriggerEvent                 "hltTriggerSummaryAOD"      ""                "HLT"     
edm::DetSetVector<CTPPSDiamondDigi>    "ctppsDiamondRawToDigiAlCaRecoProducer"   "TimingDiamond"   "RECO"    
edm::DetSetVector<CTPPSDiamondLocalTrack>    "ctppsDiamondLocalTracksAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSDiamondRecHit>    "ctppsDiamondRecHitsAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSPixelCluster>    "ctppsPixelClustersAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSPixelDataError>    "ctppsPixelDigisAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSPixelDigi>     "ctppsPixelDigisAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSPixelLocalTrack>    "ctppsPixelLocalTracksAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<CTPPSPixelRecHit>    "ctppsPixelRecHitsAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<TotemTimingDigi>    "totemTimingRawToDigiAlCaRecoProducer"   "TotemTiming"     "RECO"    
edm::DetSetVector<TotemTimingLocalTrack>    "diamondSampicLocalTracksAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<TotemTimingRecHit>    "totemTimingRecHitsAlCaRecoProducer"   ""                "RECO"    
edm::DetSetVector<TotemVFATStatus>    "ctppsDiamondRawToDigiAlCaRecoProducer"   "TimingDiamond"   "RECO"    
edm::TriggerResults                   "TriggerResults"            ""                "RECO"    
vector<CTPPSLocalTrackLite>           "ctppsLocalTrackLiteProducerAlCaRecoProducer"   ""                "RECO"    
vector<TotemFEDInfo>                  "ctppsDiamondRawToDigiAlCaRecoProducer"   "TimingDiamond"   "RECO"    
vector<reco::ForwardProton>           "ctppsProtonsAlCaRecoProducer"   "multiRP"         "RECO"    
vector<reco::ForwardProton>           "ctppsProtonsAlCaRecoProducer"   "singleRP"        "RECO"  
```

With the new version I can also successfully run
```
 python3 Configuration/DataProcessing/test/RunExpressProcessing.py --scenario AlCaPPS_Run3 --global-tag 123X_dataRun3_Prompt_v11 --lfn=file:myout11.root --alcarecos PPSCalMaxTracks 
```

The unit test also is introduced

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport but needs to be backported to 12_4_X for sure

### CODE REVIEW

**Comment by tvami** [comment]
type ctpps

**Comment by tvami** [comment]
atn @vavati @grzanka

**Comment by tvami** [comment]
@cmsbuild , please test
 * (although nothing really tests this, except for the sanity check in the unit test)

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

- creates a new scenario for the PPS stream
- pass private tests and produces the expected results
- to be tested at a future Tier0 replay

**Pull request merged**
