### PR TITLE
TkAlInOneTool: optional muon pT cut and set default eta ranges in Zmm validation

### PR DESCRIPTION
**Pull request by adewit**

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by smuzaffar** [comment]
@adewit , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by perrotta** [comment]
-1
(Not for reco, rebase needed)

**Comment by kpedro88** [comment]
FYI, how to rebase: http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by adewit** [comment]
Can someone explain to me how rebasing helps in this case? Currently trying to do it but given that the 59 commits that have been removed from the master branch are on the branch my two commits are on, I don't see how rebasing is going to remove the commits. In any case it's at patch 4 of 61 with lots of merge conflicts, so I would much rather just cherry pick my two commits off this branch and make a new PR from a fresh branch based on the latest master. Any objections?

**Comment by mmusich** [comment]
Hi @adewit the way I solved it in another PR was to restart from a clean IB, cherry-pick my commits and push-force on the same branch.
For you would be something like:
```
cmsrel CMSSW_10_4_X_2018-12-10-2300
cd CMSSW_10_4_X_2018-12-10-2300/src/
cmsenv
git cms-init
git cms-addpkg  Alignment/OfflineValidation
git cherry-pick eed1b36
git push my-cmssw +HEAD:zmm-vals
```

**Comment by adewit** [comment]
Thanks @mmusich, I didn't know you could force push on to a branch like that - will do it like this!

**Comment by kpedro88** [comment]
@adewit for future reference, you can specify `--old-base` in `cms-rebase-topic` to select only a few commits to rebase (where `--old-base` is the hash of the last commit before your changes). This is described in the page I linked.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
