### PR TITLE
Bug fix in Phase2 Tracker Digitizer  validation code

### PR DESCRIPTION
**Pull request by suchandradutta**
The TOF cut was not defined in the configuration file ( python/Phase2TrackerValidateDigi_cfi.py) and
the there was a typo in the analyzer  (test/Phase2TrackerValidateDigi.cc)

@delaere @boudoul

### CODE REVIEW

**Comment by boudoul** [comment]
Hello @suchandradutta ,  since you are fixing this package, could you please update the cfg in the test directory ? It is still using D4 which is deprecated, please use D17 (as phase2  baseline scenario) - What is the impact of your fix on plots produced so far by this package ? Thanks

**Comment by kpedro88** [comment]
If you're updating the test config, note also that the `Phase2C2` era is now just called `Phase2`.

**Comment by kpedro88** [comment]
please test

**Comment by suchandradutta** [comment]
@boudoul  there is basically no impact of the fix on plots produced so far as the cut was hard-coded before and transformed to config parameter. Anyway I have checked with and without the TOF cut to select SimHits in the validation code and found  no difference. Attaching the plots here.

With TOF cut

efficiency_tofcut

Without TOF cut

efficiency_notofcut

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
