### PR TITLE
Made CandidateTriggerObjectProducer a stream module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Also removed unnecessary member variables in order to decrease the cost of doing the replicas per stream.

This was found in #25090.
#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
merge
@santocch

**Comment by santocch** [comment]
+1

**Pull request merged**
