### PR TITLE
add option to restrict single-Path jobs of hltIntegrationTests to a subset of triggers [`14_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #44005

#### PR description:

From the description of #44005:

>This PRs adds a functionality to the utility `hltIntegrationTests`.
>
>Currently, given a HLT menu with N Paths (excluding `HLTriggerFinalPath`), `hltIntegrationTests` runs N+1 jobs: one job running the full HLT menu in question, and N jobs each running only one of the N Paths of the menu standalone. This PR adds the option to run the 1-Path-standalone jobs for only a subset M of the Paths in the menu (M < N). This can be useful when testing an update which is known to modify only M Paths, where one normally wants to run (a) the full HLT menu, and (b) standalone jobs only for the M Paths in question, given that the other N-M Paths are unchanged.
>
>This is implemented by adding the command-line argument `--paths` to `hltIntegrationTests`. In analogy to the `--paths` argument of `hltGetConfiguration`, one can specify patterns to select certain Paths using a comma-separated list. One can also specify Paths to be ignored/dropped by prepending the character `-` to a given pattern (e.g. `--paths "*HLT*,-HLTriggerFinalPath"` to ignore the Path `HLTriggerFinalPath`). The script `hltListPaths` is updated accordingly (technically, changing its CLI in a non-backward-compatible way). More details are provided in the help messages of the scripts updated in this PR.
>
>Note.
> - `hltIntegrationTests [MENU] -x "--paths A,B,C"` (before and after this PR) corresponds to running 4 jobs: one with a menu containing only 3 Paths (A, B, C), plus 1-Path jobs for each of those 3 Paths (A, B, C).
> - `hltIntegrationTests [MENU] --paths A,B,C` (possible only with this PR) also corresponds to running 4 jobs: one with a 'full' menu containing all its Paths (possibly many more than A, B and C), plus 1-Path jobs only for the 3 Paths specified via `--paths` (i.e. A, B and C).
>
>Minor code improvements are included as well.
>
>Merely technical. No changes expected.

#### PR validation:

None beyond the checks done for #44005.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#44005

Backporting to `14_0_X` for HLT-menu development in 2024.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
urgent
   * needed for trigger development

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
