### PR TITLE
Phase2-hgx172 Fix the memory problem in validation code

### PR DESCRIPTION
**Pull request by bsunanda**
May be a fix to the issue #25234

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@kpedro88 do you confirm this is solving the observed issue?

**Comment by kpedro88** [comment]
yes, the memory issue no longer occurs.

**Comment by fabiocos** [comment]
@andrius-k @jfernan2 could you please sign or comment? I would like to get rid of the memory problem that is affecting comparisons

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@andrius-k @jfernan2 please sign it for reference, or comment for a possible further update

**Comment by andrius-k** [comment]
+1

**Pull request merged**
