### PR TITLE
 Change ECAL DQM Presample and Trigger primitive plots thresholds [13_0_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:
This PR changes the thresholds of 

- Presample Quality plot to remove the ring of red spots observed in the Ecal endcaps
- Trigger Primitive emulator quality plot to remove the red towers at high eta in the endcaps

These are known issues due to ageing and radiation effects and the thresholds will need to be assessed and changed further, if need be.

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 13_0_X, which is used in production at the moment.
Master PR is https://github.com/cms-sw/cmssw/pull/42242.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #42242

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in ECAL DQM plots as expected
- test p5 ok

**Comment by rappoccio** [comment]
+1

**Pull request merged**
