### PR TITLE
Run3-gex174E Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for the Heavy Ion MC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for the Heavy Ion MC

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be used for HI MC. Needed to make the payload

### CODE REVIEW

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob This is purely Run3 geometry. I do not see why upgrade signature is needed for this. Please sign this to be integrated

**Comment by srimanob** [comment]
Is this backport discussed already with PPD? 
13_0 is not only for HI, but also pp. If we need only for HI, should we just add 2023HI geometry instead of replacing 2023.

Sorry if this is already discussed. I am almost out since beginning of Nov.

@cms-sw/alca-l2 @cms-sw/pdmv-l2

**Comment by bsunanda** [comment]
@srimanob Yes, it is discussed. With this back ported we can make the payload and then with the new payload MC can start using 13_0_HI

**Comment by srimanob** [comment]
Could you please clarify on this question, https://github.com/cms-sw/cmssw/pull/43418#issuecomment-1836713673

thanks.

**Comment by srimanob** [comment]
[Alca slide on 27 Nov](https://indico.cern.ch/event/1348789/contributions/5677108/attachments/2760535/4807043/AlCaDB_27.11.2023.pdf) mentioned about pending decision. I assume the decision is made, right?

**Comment by civanch** [comment]
This backport is needed, because 13_3_X is the release for 2024 MC production.

**Comment by antoniovilela** [comment]
hold
   - Hold integration in 13_0_X as this is intended for CMSSW_13_0_HeavyIon_X .

**Comment by civanch** [comment]
@antoniovilela , @rappoccio , I guess this PR may be unhold.

**Comment by civanch** [comment]
@bsunanda , it is agreed to close this PR.

**Pull request closed without merging**
