### PR TITLE
FirstVersionsofDiTauHLTPaths_forPhase2 [13_2_X]

### PR DESCRIPTION
**Pull request by hsert**
First versions of ditau HLT paths for Phase2 with charged isolation and DeepTau Isolation (using Run2 training) are added.

Detailed description of PR is given in the original PR: https://github.com/cms-sw/cmssw/pull/42562

We would like that PR will be backported to CMSSW_13_2_X release, to be compatible wtih other Phase 2 HLT PRs.

I used CMSSW_13_2_X_2023-08-18-1100 release for testing. After initialization, the merged branch is rebased with
```git cms-rebase-topic --old-base CMSSW_13_3_X_2023-08-15-1100 hsert:tauHLTPhase2_dev```
and run the following runMatrix test, and there was no failed run.
```runTheMatrix.py -l limited -i all --ibeos```

### CODE REVIEW

**Comment by missirol** [comment]
@hsert , the title of this PR is incomplete ("..."). Maybe take this opportunity to change the titles of your 3 PRs as follows: "foo" (master), "foo [13_2_X]" (this PR), and "foo [13_1_X]", where "foo" is the title of the PR to master.

**Comment by missirol** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Pull request merged**
