### PR TITLE
temporarily remove `HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1` from phase-2 HLT menu

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

See https://github.com/cms-sw/cmssw/issues/42862, temporary measure to avoid relval failures.

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@rovere @SohamBhattacharya please confirm you are OK with the (temporary) removal of the failing tau HLT path in the phase-2 menu (given the conclusions at https://github.com/cms-sw/cmssw/issues/42862#issuecomment-1749516622).

**Comment by mmusich** [comment]
+hlt
   * taking "thumbs up" as a confirmation ;)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
