### PR TITLE
NanoAOD: pass through for muon and Isotrack above 15 GeV in pt, regardless of ID or dxy/dz

### PR DESCRIPTION
**Pull request by mdunser**
#### PR description:

This PR is to pass through all muons from MiniAOD to NanoAOD above pT > 15 GeV, regardless of the ID. This is needed to make more detailed tag-and-probe efficiency studies for the w-mass measurement.

The total size difference is of the order of 0.25%. We ran tests on 50k events for ttbar and dy and the difference in size is:

ttbar: 105727232 vs. 105437681 bytes with pass-through ON versus OFF, ratio 1.00275
    (41754 versus 37945 muons, 10% more)
dy: 61925228 vs. 61753275 bytes with pass-through ON versus OFF, ratio: 1.00278
    (68772 versus 66746 muons, 3% more)

#### PR validation:

Ran 50k Mini->Nano events for DY and ttbar MC in the SMP-RunIISummer16NanoAODv8 campaign.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
@mdunser 
can you prepare at the same time the backport to 10_6

**Comment by mdunser** [comment]
the backport PR to the CMSSW_10_6_X branch is here: https://github.com/cms-sw/cmssw/pull/32107

**Comment by mariadalfonso** [comment]
> 
> The total size difference is of the order of 0.25%. We ran tests on 50k events for ttbar and dy and the difference in size is:

In data (Single/Dimuon) different eras the size increase is in the range 1%-1.4%

**Comment by mariadalfonso** [comment]
@mdunser @bendavid 

not clear to us is this update goes in the right direction. And the size additions is not negligible https://github.com/cms-sw/cmssw/pull/32103#issuecomment-725538581.

We expected for Wmass you will go for a private renanoAOD because 
1. you need tracks to complete the tag and probe, 
2. need to do the muon refitting 
3.  the precision of some variable like in nanoAOD is not enough

We prefer to have a discussion at the next xPOG on nov25.
I will put on hold this PR until then

**Comment by mariadalfonso** [comment]
hold

**Comment by bendavid** [comment]
While the muon refitting+momentum scale corrections are still being finalized, we're proceeding with the rest of the analysis.

The idea was that if this change makes it for nanov8, then at least we could avoid any private nanoaod production for the data for the moment.

(we also think that the precision increases for the generator information can be made selective enough to be applied across the board, but this will take a bit more time/study)

**Comment by mariadalfonso** [comment]
unhold

was discussed in xPOG march 17 https://indico.cern.ch/event/994591/#2-need-from-wmass

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
Early test of the muon part were reported here
https://github.com/cms-sw/cmssw/pull/32103#issuecomment-725538581

The relaxing of the isotrack lead to  + 5.5% increase in DoubleMuon events
and 1.1 % in JetHT

Some distribution is shown here 
IsoTrackZtautau
DoubleMuonIsoTrack
JetHTIsoTrack

**Comment by mariadalfonso** [comment]
@sroychow @mdunser 
one thing to consider is the relax the dxy,dz only for pt>15.
you will not use probe of pt~5/10 GeV

**Comment by sroychow** [comment]
@mariadalfonso yes we did discuss this earlier today and shall update the PR accordingly. I am just checking the size differences with the updated cuts in the scenarios where the size increases were the most(e.g., mc106Xul16, data106Xul17) in the nano integration tests.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
* Double Muon is now +4.2%  (this is considered the worst case scenario and the dataset is small); JetHT is +0.8%
* both muon/isotrack have the dxy and dz added ; so the cut can be applied a posteriori

@mdunser : can you update the title ?
NanoAOD: pass through for muon *and Isotrack* above 15 GeV in pt, regardless of ID or dxy/dz

@sscruz
take note and let us know if additional limitations for the T&P exist from the muon POG point of view

**Comment by sscruz** [comment]
@mariadalfonso this looks good for us, with this PR we will have most ingredients we need for tnp measurements in the Z. Something I don't see here is the isStandandAlone muon flag (was proposed by @mdunser et al in https://indico.cern.ch/event/994591/contributions/4239801/attachments/2210344/3740674/xpog_wmass.pdf), that would be useful for us. Is that expected to go in another PR?

**Comment by mdunser** [comment]
> @mdunser : can you update the title ?
> NanoAOD: pass through for muon _and Isotrack_ above 15 GeV in pt, regardless of ID or dxy/dz
> 
@mariadalfonso : done!

**Comment by mariadalfonso** [comment]
> @mariadalfonso this looks good for us, with this PR we will have most ingredients we need for tnp measurements in the Z. Something I don't see here is the isStandandAlone muon flag (was proposed by @mdunser et al in https://indico.cern.ch/event/994591/contributions/4239801/attachments/2210344/3740674/xpog_wmass.pdf), that would be useful for us. Is that expected to go in another PR?

@sscruz 
it went in with this PR https://github.com/cms-sw/cmssw/pull/33208/files

**Comment by mariadalfonso** [comment]
+xpog

**Comment by qliphy** [comment]
+1

**Pull request merged**
