### PR TITLE
Add HLT Timing scripts.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Add a script that will be used to monitor the performance of HLT Phase2 simplified menu periodically.

#### PR validation:

Tested the script locally.

### CODE REVIEW

**Comment by rovere** [comment]
FYI @smuzaffar

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Pull request merged**
