### PR TITLE
Ep combination protection

### PR DESCRIPTION
**Pull request by rafaellopesdesa**
The W' group reported that the electron Ep combination was returning unphysical values at high energies when the track pT was consistent with 0. We added a protection in the combination code to only use the Ep combination MVA at high energies when the track pT error is smaller than 10 times the track pT. It is a pretty safe cut that removes these badly measured tracks from the determination of the electron energy.

Reference: https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3446/1/1/1/1.html

### CODE REVIEW

**Comment by fcouderc** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

@fcouderc , since jenkins testing is a limited resource, there is also a limited list of people to trigger the tests

**Comment by slava77** [comment]
@cmsbuild please test
the comparison job failed

**Comment by rafaellopesdesa** [comment]
Hi,

I don't fully understand the result. Looking at the DQM comparison, I see
differences in HcalHitsV, but that doesn't make much sense given that the
only modification was on very high level EGamma code. Is that something
expected?

Thanks,
-- Rafael.

**Comment by davidlange6** [comment]
Is a bug in Dqm for fast sim.

**Pull request merged**
