### PR TITLE
Enable packing/unpacking for Phase2 HCAL

### PR DESCRIPTION
**Pull request by kpedro88**
With #20758, we have a Phase2 GT that contains a functioning emap with all the HB upgrade cells.

This means that we no longer have to skip packing/unpacking for HB in Phase2 workflows. Among other things, this will enable premixing to work for the Phase2 HB.

(These changes were also propagated to 2019/post-LS2, but had to be disabled because there isn't a 2019 GT queue yet.)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
* No differences in 2019 comparison (after most recent commit)
* 1 difference in 2023 comparisons: plot that involves emap-related quantities, change is expected since the emap is different
* reco comparisons show missing ZDC collections. Previously, the ZDC digi collection was being passed through the fake HCAL unpacker, but there are no ZDC entries in the emap for the real unpacker. Right now ZDC is unpacked via the Castor unpacker, but Castor is removed in the phase2 detector. Probably the ZDC unpacking needs to be moved back into HCAL (maybe in conjunction with moving to QIE10 readout); I'm discussing this with experts now, and can post a GitHub issue to track the progress. @slava77 @perrotta please advise

**Comment by slava77** [comment]
On 10/16/17 12:35 PM, Kevin Pedro wrote:
> Probably the ZDC unpacking needs to be moved back into HCAL (maybe in
> conjunction with moving to QIE10 readout); I'm discussing this with
> experts now, and can post a GitHub issue to track the progress. @slava77
> <https://github.com/slava77> @perrotta <https://github.com/perrotta>
> please advise

let's wait for clarification here from ZDC before proceeding with this PR.

**Comment by abdoulline** [comment]
My understanding is that HCAL emap contained entries for old ZDC detector, which doesn't exist anymore (since unsuccessful attempt to use it for the _very last time_ in 2016 for HI data taking).
Old ZDC unpacking has been moved to CASTOR (following ZDC FEDs move to is) early in 2016 

https://github.com/cms-sw/cmssw/commit/8395990671ad125b19a8af8493ae362c6cc3012a#diff-0b2dd580fc15df181abe8beefafaae43

Instead, ZDC group has been developed a hodoscope ("RPD") detector, for which HcalZDCDetId has been extended
 https://github.com/cms-sw/cmssw/commits/master/DataFormats/HcalDetId/interface/HcalZDCDetId.h
but since that time there were no more published developments (SIM/RECO) to my knowledge...

**Comment by perrotta** [comment]
@kpedro88 : my understanding after the reco meeting was that the ZDC group would have taken care in due time of the packing/unpacking of their detector inside HCal, and in the meanwhile we can go on with this PR and remain without the ZDC collections for Phase2 data.
Is this summary correct? Can we therefore ask for merging this PR now? Do you have some further info to be reported here after your inquiry (anticipated in https://github.com/cms-sw/cmssw/pull/20920#issuecomment-337010059) with the ZDC experts?

**Comment by kpedro88** [comment]
@perrotta yes, this summary is correct. We should go forward with this PR. Here are some excerpts from the email discussion with @BetterWang:
>1) ZDC will be part of HCAL (ideally HF, since we use the same
electronics, readout chain) for 2018 run and Phase2;
>2) ZDC will be unpacked and calibrated by HCAL software; the current
ZDC unpacker should be discarded to give way to the HCAL unpacker.
>3) ZDC will not be simulated in any simulations (pp, or HI) at the
moment (might update for HI in long term, but not before LS2), if has
to, maybe just use a dummy packer?
>4) ZDC/RPD EMAP history can be found at [1]. We might want to double check it.
>[1] http://cmsdoc.cern.ch/cms/HCAL/document/Mapping/ZDC/

>If the [ZDC] simulation is used in the future, it will need to be upgraded to use QIE10 readout instead of QIE8, in order to be consistent with data. (Hopefully it can just be packed like HF QIE10 digis to reduce duplication of effort.)
>
>There was already some work done in the HCAL unpacker to support ZDC w/ QIE10, see #16150.

>ZDC was read out from CASTOR in 2016 pPb run. It works really fine during data taking.
We couldn't use QIE10 to read out from HF due to the radiation damage to the fibers.
In 2018, we will reinstall new fibers before the HI run, and read out from HCal.

**Comment by perrotta** [comment]
Thank you @kpedro88 for the confirmation

**Comment by perrotta** [comment]
+1
- HCal packing/unpacking enabled for Phase2
- ZDC collections are now missing, but ZDC will not be simulated in any simulations (pp, or HI) at the
moment (https://github.com/cms-sw/cmssw/pull/20920#issuecomment-338677675)

**Comment by kpedro88** [comment]
@ghellwig, @arunhep, @cerminar, @franzoni, @lpernie please sign

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
