### PR TITLE
[12_3_X] Add AlCaLumiPixels_Run3 scenario and unit test

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/37434

#### PR validation:

Unit test runs

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/37434

### CODE REVIEW

**Comment by tvami** [comment]
urgent
 * needed for the 12_3_X coming out this weekend

**Comment by tvami** [comment]
Attn @cms-sw/alca-l2 @benitezj

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hi @cms-sw/operations-l2 , given that `CMSSW_12_4_X_2022-04-05-1100` (which contained the master version of the PR) ran fine and the results in this PR are good as well, can we merge this, too? Thanks!

**Comment by perrotta** [comment]
+1
- Verbatim backport of #37434

**Pull request merged**
