### PR TITLE
new rechit containers

### PR DESCRIPTION
**Pull request by lveldere**
this pr replaces #9855 
- BaseTrackerRecHit
  BaseTrackerRecHit::initialise qualWord_ in all constructors
- SiTrackerGS*RecHit
  - preparation for arbitrary hit combinations in fast tracking emulation
  - Note: these containers are FastSim-only
- FastSimulation/EgammaElectronAlgos/
  - removed outdated obsolete modules
- TrajectorySeedProducer & TrackCandidateProducer 
  - next step towards arbitrary hit combinations
- SiTrackerGaussianSmearingRecHitConverter
  - adapt to updated recHitContainer
- Miscelaneous
  - several other classes needed to be migrated to the updated recHitConainer

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@smuzaffar 

Hi Malik

Any idea why i don't get any test results?

Thanks

Lukas

**Comment by cvuosalo** [comment]
@cmsbuild please test
try again

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I'm checking this locally
[jenkins is not super-reliable]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10018	fdf4def
- tested locally in CMSSW_7_6_X_2015-07-04-2300 /test area sign567/ using only short matrix jenkins tests
- no changes in regular reco
- there are small changes in fastsim workflows at about 1% level in tracking: in 5.1 (ttbar) and in 135.4 (ZEE) there is about 1% loss of the number of tracks (1 and 5 tracks, correspondingly). Changes are very localized (other track parameters are unchanged)
- fastsim DQM plots are in line with the loss of tracks: in both 5.1 and 135.4 the plots with duplicates are now empty (or is it loopers?) [the following plots are ZEE fastsim]. (It's unclear if the disappearance of duplicates is the same as the reduction in the number of tracks)
wf135p4_dups
wf135p4_loopers

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@slava77 

Thanks a lot!
In my private tests I only looked at real tracks,
where I didn't see *any* change.

It would make sense something has changed there,
since the SiTrackerGSRecHit2D::sharesInput function is better defined than before.
I'll have to ask Matti Kortelainen how the duplicates are defined in the track Validation,
before I can say more.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
@lveldere Duplicate rate is defined as
```
tracks associated to a TrackingParticle that is associated to >= 2 tracks
-------------------------------------------------------------------------
                                all tracks
```

**Pull request merged**
