### PR TITLE
Ss threadsafe ecal digi to raw

### PR DESCRIPTION
**Pull request by sabasehrish**

### CODE REVIEW

**Comment by sabasehrish** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
ping

**Comment by mommsen** [comment]
+1

**Comment by Dr15Jones** [comment]
@davidlange6

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@sabasehrish  @mommsen @argiro 
this PR was reverted on Aug 10 with #20119 to solve problems reported in  #20116
is there a plan to make updates and reintroduce changes from this PR?

**Comment by Dr15Jones** [comment]
The original implementer of the pull request no longer is working for CMS.

**Pull request merged**
