### PR TITLE
[93X] Improvements to L1 Offline DQM - part 1 (issue #19590)

### PR DESCRIPTION
**Pull request by kreczko**
This PR implements the improvements requested in issue #19590 by the L1T team.

@tapperad et all, please have a look

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
@rekovic @mulhearn please review & sign for L1T

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
