### PR TITLE
[14_1_X] Fix beamspot in PATElectronProducer and Muon ID flags in PackedCandidates

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Combined backport of https://github.com/cms-sw/cmssw/pull/46412 and https://github.com/cms-sw/cmssw/pull/45818

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46412
and https://github.com/cms-sw/cmssw/pull/45818

**Comment by mandrenguyen** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
