### PR TITLE
A trivial modification allowing item indexing by subdetector

### PR DESCRIPTION
**Pull request by igv4321**
This change does not affect any existing code.
Please check and approve quickly.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
The change in the CondFormat does not affect the persistency. However, the enum in HcalDetIdTransform will change the value of N_TRANSFORMS from 3 to 4. Is this required explicitly? Naively, I would consider safer to introduce SUBDET as last item in the enum, in order to avoid changes in the existing values, in case they are involved in persistent data.

**Comment by igv4321** [comment]
Automatic increment of N_TRANSFORMS is exactly what is intended.
N_TRANSFORMS by itself is not a valid transform number, it only
indicates now many transform enums are there.  The allowed
transform numbers are 0 <= n < N_TRANSFORMS (enforced in HcalDetIdTransform.cc)

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@igv4321 @ggovi - related to @ggovi's question - do we have conditions stored in the affected formats in GTs?

**Comment by mmusich** [comment]
@davidlange6 seems to me it can hardly be the case since the CondFormat has been created in #15419 (merged 6 days ago). 
The important point it that no persistent data created in the meanwhile is used for production later on.

**Comment by davidlange6** [comment]
I agree - was looking for a cross check

**Comment by igv4321** [comment]
@davidlange6 @ggovi -- No, we don't have conditions relying on this class stored yet. Note, however, that this is besides the point. This particular class has been designed with extensibility in mind -- extending the number of possible transforms does not invalidate the records already stored in the database (what we don't want to do is to replace an existing transform with another one).

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
