### PR TITLE
More plots from GE21 for the GEM DQMs, a backport to 12_4_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
We have several updates on GEM DQMs.

- Migrations of some plots to other places (online -> offline or vice versa)
- More plots for GE21 is now available

This PR is the backport of #38398 (+#38526) to CMSSW_12_4_X.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
type feature

**Comment by emanueleusai** [comment]
backport of #38398

**Comment by emanueleusai** [comment]
please test

**Comment by quark2** [comment]
Hi @emanueleusai, 

Because we wish this update is applied to the upcoming run, could you attach urgent tag?

**Comment by jpata** [comment]
+reconstruction
- on the reco side, it's transparent / minimal (no observed changes)
- the reco part is a direct backport of https://github.com/cms-sw/cmssw/pull/38398

**Comment by quark2** [comment]
I've found that an update on the configurations on some plots is needed to avoid unexpected issues

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
