### PR TITLE
adding MWGR5 run with all detectors (including GEM) in Run3 data workflow

### PR DESCRIPTION
**Pull request by amassiro**
PR description:
This PR is updating the data run3 workflow (prompt reco run 3 workflow 138.1 and express workflow 138.2) with a recent run, 338714, from MWGR#5 2020,  where all detectors (including Tracker and GEM) were present in the acquisition.

PR validation:
runTheMatrix.py -l 138.1 --command "-n 500"
runTheMatrix.py -l 138.2 --command "-n 500"

if this PR is a backport please specify the original PR and why you need to backport that PR:
I plan to backport this PR once this PR is integrated or soon to be

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by boudoul** [comment]
Hi @chayanit , @christopheralanwest , @tlampen  :  is there any GT update for run3 data that would be nice to incorporate in this PR at the same time ?

**Comment by tlampen** [comment]
Hi @boudoul ,
We plan to produce GTs as soon as the Tier-0 results are available.

**Comment by christopheralanwest** [comment]
> Hi @chayanit , @christopheralanwest , @tlampen : is there any GT update for run3 data that would be nice to incorporate in this PR at the same time ?

@boudoul The GTs in autoCond are already up-to-date.

@chayanit Don't you want to test this PR with workflows 138.1 and 138.2? Neither are included in the short matrix.

**Comment by srimanob** [comment]
test parameters:

- workflows = 138.1, 138.2

**Comment by srimanob** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

From @christopheralanwest comment, I think this PR is good to go.

**Comment by silviodonato** [comment]
do you have any comment @cms-sw/pdmv-l2 ?

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
