### PR TITLE
Implementation of tau embedding in relval wfs

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

First implementation of tau embedding wfs in the relval machinery, following the discussion at the PPD meeting: https://indico.cern.ch/event/1146289/contributions/4811411/attachments/2426987/4155240/PPD-Embedding-2022-04-14.pdf. One wf (136.9) is introduced in a separate tauembed definition or relvals that will be used for tests in the production system.

#### PR validation:

The new wf runs fine locally.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
test parameters:
- workflow = 100.0
- relvals_opt = -w tauembed

**Comment by mariadalfonso** [comment]
does this replace the wf [7.3] ?
experienced problems here  https://github.com/cms-sw/cmssw/pull/32167

**Comment by kskovpen** [comment]
> does this replace the wf [7.3] ?
> experienced problems here #32167

The existing wfs are untouched.

**Comment by mariadalfonso** [comment]
> > does this replace the wf [7.3] ?
> > experienced problems here #32167
> 
> The existing wfs are untouched.

The question is: should this wf replace the outdated config in the 7.3 ?

**Comment by mmusich** [comment]
> The question is: should this wf replace the outdated config in the 7.3 ?

`7.3    CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18`

??

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by kskovpen** [comment]
@cms-sw/upgrade-l2 would you have any comments on this PR? Thanks!

**Comment by srimanob** [comment]
I'm not sure I follow the PR, as I missed the discussion.

- Why do we need specific `relval_` for this case? I mean we split it with big category like standard (which is mostly for data in today use), premix, ... etc. Why customization of tau embedding need special category. Can't it just be with standard, i.e. brach out from `workflows[136.XXX]`.
- Why do you choose that specific lumi (`Run2016C={276092: [[91, 95]]}`), instead of using the same as predefined 2016C., Run2016C={276092: [[115, 149]]}? Something that is special should be noted.

**Comment by kskovpen** [comment]
Hi @srimanob , many thanks for the review. Agreed that it can be part of standard wfs and using the predefined inputs. The PR has been updated.

**Comment by kskovpen** [comment]
test parameters:
- workflow = 136.9

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
@srimanob now should be good. Please let me know otherwise :)

**Comment by srimanob** [comment]
Hi @kskovpen 
I understand from your comment that you will just used predefined one, instead of 
`Run2016C={276092: [[91, 95]]}`

However, it is fine to me to use this too.

**Comment by srimanob** [comment]
+Upgrade

New workflow for tau embedding is introduced in this PR. New workflow (`136.9`) runs fine.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
@kskovpen could you please update the PR description with the updated wf number?

By the way, is it safe/recommented to overwrite the definition of the `Run2016C` lumi in relval_steps.py? Shouldn't it be renamed otherwise? (I am just asking: you are certainly the person that knows better the usage of that file, then I'll fully rely on your opinion if you'll confirm it)

**Comment by kskovpen** [comment]
test parameters:
- workflow = 136.9

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

Small change after the last sign, on definition of RUN to be used.

**Comment by perrotta** [comment]
+1

**Pull request merged**
