### PR TITLE
Code Fix to read tower geometry correctly in Ecal DQM StatusManager [Master]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR fixes the code to read tower geometry correctly in Ecal DQM StatusManager. 
Additionally the `toGet` method of accessing the DB tags is removed from the Ecal DQM config, on the suggestion of AlcaDB.

#### PR validation:
PR is validated by running a local test which creates an sqlite file which is uploaded to the DB and verified with an online DQM run on a test DQM GUI. Everything looks as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is the Master PR. The backport to 12_4_X is https://github.com/cms-sw/cmssw/pull/38359 and 12_3_X is https://github.com/cms-sw/cmssw/pull/38360

### CODE REVIEW

**Comment by emanueleusai** [comment]
type ecal

**Comment by tvami** [comment]
Sorry can somebody elaborate on how this PR adds the tags in the title of the PR? And why this isnt happening through a GT? Thanks!

**Comment by abhih1** [comment]
Hi @tvami 
The changes made here is essentially to create a local sqlite file with the correct tower and channel status info, which is then uploaded to the DB manually (using local scripts). I have updated the PR description to be more clear. Sorry for the confusion!
Despite the names having "hlt" in them they are not really hlt tags and their update has been done manually this way.
The last time this was updated was in 2016 and the relevant codes didnt seem to work anymore and this PR makes them functional again to create the sqlite file with the correct tower mapping, and also updates the tower list.

Hope this answers your question.

**Comment by tvami** [comment]
Thanks @abhih1 for the answer, it's clear, however this seems the perfect example of having the payload stored in a multi-IOV tag in the GT. This is kind of the reason why GTs exist (to avoid the PR changes like this one)

**Comment by emanueleusai** [comment]
So @abhih1 and @tvami, how do we want to proceed? CLose this one and add the DB tags to the GT or go forward with the current PR? 
I am certainly in favor of the GT solution unless this is an urgent matter.

**Comment by tvami** [comment]
@simonepigazzini @camendola do you guys wanna chime in here? Why wasnt the append to the tag the first move anyway?

**Comment by abhih1** [comment]
Hi, I would like the PR to be merged for this time atleast, since as I said earlier the code  in`DQM/EcalCommon/src/StatusManager.cc` itself was broken before and needs to reflect the correct way of reading towers. 
The rest of the changes was only to update the latest settings which were not changed since 2016 and nobody now knows the workflow or reasons behind this.
But moving forward I can discuss with the ECAL colleagues and look into moving to the GT option.

**Comment by tvami** [comment]
Maybe you could decouple the changes in `DQM/EcalCommon/src/StatusManager.cc` from the rest in this PR (and call it a bugfix)? 
The AlCaDB objection is about uploading a local sqlite file, specifically the `DQM/EcalCommon/data/mask-ECAL.db`, although the upload of the txt files is also something, I dont fully understand: isnt there also a tag for bad channels?

**Comment by abhih1** [comment]
Hi @tvami I have cleared the rest of the files and only kept the bug fix in the PR now.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@abhih1 thanks! Please change the title to the PR and also change the backport PRs

**Comment by tvami** [comment]
type bugfix

**Comment by emanueleusai** [comment]
+1

**Comment by malbouis** [comment]
maybe a late comment for a future PR. the tags updated in this PR could be included in the GT and these lines would be replaced by access to GT: https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py#L125-L132
As per @tvami [comment](https://github.com/cms-sw/cmssw/pull/38357#issuecomment-1155554747).
It is anyways not so good practice to have toGet method in such a code.

**Comment by abhih1** [comment]
@malbouis Could you please point me to an example of such an access to GT?

**Comment by tvami** [comment]
Well, we should discuss the details, but provided that 
 * you dont change this tag very frequently
 * this is used in the express 

You change those lines in https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py#L125-L132 to
```
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run3_data_express', '')
```
and you are done. 

The GT already contains a tag for the record `EcalDQMChannelStatusRcd`, it's called [EcalDQMChannelStatus_v1_express](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/EcalDQMChannelStatus_v1_express) also for `EcalDQMTowerStatusRcd` the tag is [EcalDQMTowerStatus_v1_express](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/EcalDQMTowerStatus_v1_express) and indeed it was not updated in this (or the previous) decade. However, that part is extremely easy to fix, Chiara can do the upload any time (well it should be going through some validation first)

**Comment by abhih1** [comment]
@tvami  Thanks. Then are the tags below not present in the GT?  These are the ones we recently updated: 

https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/EcalDQMChannelStatus_v1_hlt 
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/EcalDQMTowerStatus_v1_hlt

**Comment by tvami** [comment]
Yes, the update you did to those tags should have gone to the tags I was referring to. Plus the change of lines Helena referred to needs to be changed as well.

Another way to go would be to add the _hlt tags to the HLT GTs and then load that, but that means more work for more parties, so I'd just go with my proposal

**Comment by tvami** [comment]
> Ok thanks. I agree, best to take the path of least resistance

Ok, should then the change of  https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py#L125-L132 be done in this PR?

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
> So before we do this change the express tags have to be updated then?

Yes, the upload should be done asap indeed

**Comment by abhih1** [comment]
Ok. Please let me know what I should do from my end.

**Comment by tvami** [comment]
We need Chiara to do the append

**Comment by tvami** [comment]
@abhih1 actually we can make this parallel, please commit your changes to this PR, and when the append happens it happens. There is really no technical requirement that the append has to happen before you let the code know that the condition will be taken from the GT

**Comment by tvami** [comment]
Hi @abhih1 we had a bit of a chat with the DQM convenors, what we should do is to cut a new HLT GT and we can include the tags that you were referring to (which I understand have the correct payload in the last IOV) and use that in the DQM clients. The action item from your side is to remove the lines https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py#L125-L132 completally

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
hi @abhih1 
please rewrite the PR description according to the requested changes (e.g. there is no local sqlite anymore).

Also
> if this PR is a backport please specify the original PR and why you need to backport that PR:
N/A

Well that's very far from the truth given that you already did the 12_3_X and 12_4_X backports, please also comment on the urgency about deploying this at the online machines

**Comment by abhih1** [comment]
> hi @abhih1 please rewrite the PR description according to the requested changes (e.g. there is no local sqlite anymore).

Hi @tvami, sure but could you please explain to me how these tags will be updated, now that they are added to the GT? Next time we need to update the towers what is the procedure to follow if there's no local sqlite file anymore?

> Also
> 
> > if this PR is a backport please specify the original PR and why you need to backport that PR:
> > N/A
> 
> Well that's very far from the truth given that you already did the 12_3_X and 12_4_X backports, please also comment on the urgency about deploying this at the online machines

Well I thought the question is whether this is a backport, which it is not as this is the Master PR, and in the actual backport PRs to 12_3_X and 12_4_X I do mention it in the description. But if you'd like I can mention the backport PRs here as well.

**Comment by abhih1** [comment]
Ok thanks. I've updated the description

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
