### PR TITLE
Phase2-hgx74 Correct HGCal Geometry for the last layer of highest ieta of BH

### PR DESCRIPTION
**Pull request by bsunanda**
Overcomes the segmentation fault in validation phase

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - please, provide description

**Comment by ianna** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1
comparisons show very minor changes in a few quantities for 2023 workflows with HGCal

**Comment by ianna** [comment]
+1

**Pull request merged**
