### PR TITLE
[12.5.X] supply DQM for `SiPixelCalSingleMuonTight`

### PR DESCRIPTION
**Pull request by mmusich**
backport of #39382

#### PR description:

With the foreseen increase of isolated muon trigger rates (see https://its.cern.ch/jira/browse/CMSHLT-2465 ) it becomes possible to run the `SiPixelCalSingleMuonTight` at express, allowing for quasi-online efficiency monitoring.
This PR adds a stub of DQM monitor for that AlCa flavour to start producing basic cluster properties histograms that are used as ingredients of the hit efficiency measurement.

#### PR validation:

Run

```console
 runTheMatrix.py -l 1002.4 -t 4 -j 8 --iboes
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of #39382, needed for data-taking monitoring purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, new-feature

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1002.4

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
