### PR TITLE
More BuildFiles cleaning

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/33282).

This PR cleans unnecessary includes from CMSSW BuildFiles that were recently added for 11_3_0_pre6.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by yuanchao** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
+heterogeneous

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
