### PR TITLE
Change output from RECO to AOD in Run3 Data RelVal wfs

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Following discussions in https://github.com/cms-sw/cmssw/issues/43432  we (RECO) would like to move from RECO output to AOD output in Run3 Data RelVal Workflows. 

From the reco side, we would like to profile a workflow which more closely resembles what is done in prompt reco or in a reprocessing campaign. One imagines that moving the majority of relval workflows to AOD would be beneficial to disk load of release validation (a factor 10 in reduction from RECO to AOD).

As the primary responsible of these workflows, we brought this up with @cms-sw/pdmv-l2
They tend to agree that it doesn't make sense to have all real data wfs write RECO (it's not the case for MC), but suggested we bring the issue to a wider audience

#### PR validation:

Tested that RelVal workflows affected run fine and produce AOD output

### CODE REVIEW

**Comment by slava77** [comment]
Is any of the POG/DPG validation relying on RECO in the relvals?
I recall that some groups run some extra workflows manually.
I guess we may not find out until after the relval validation reports come back with problems.

**Comment by srimanob** [comment]
Hi @jfernan2 
One thing I don't understand. You mentioned about profiling as a main motivation to update the workflows. But the profiling comes automatically with newly updated workflow? You still have DQM in the sequence. I just wondering how do you deal with that currently? Can that way (update output or whatever) also manage AOD output?

**Comment by srimanob** [comment]
OK, understand.
My wonder is that why don't we just make a profiling workflow as we does for MC, instead of changing all. But clearly, if no need, then it is OK. We may not figure out the need until it is gone as mentioned in the original issue.

**Comment by mandrenguyen** [comment]
> OK, understand. My wonder is that why don't we just make a profiling workflow as we does for MC, instead of changing all. But clearly, if no need, then it is OK. We may not figure out the need until it is gone as mentioned in the original issue.

Well, if we need to be a bit disruptive to identify where RECO is still being used, maybe it's worth the temporary headache.  That seems preferable to just keep using it forever "just in case", given that it uses an order of magnitude more disk resources.

**Comment by srimanob** [comment]
I am fine to let it goes ;)

**Comment by srimanob** [comment]
+Upgrade

**Comment by jfernan2** [comment]
kind ping @cms-sw/pdmv-l2

**Comment by AdrianoDee** [comment]
please test

Just to refresh the tests that run some of these wfs.
Will sign as soon as they are fine, sorry for the delay.

**Comment by smuzaffar** [comment]
ignore tests-rejected with ib-failure

please ignore the unit test failure. It is a known issue https://github.com/dmwm/dasgoclient/issues/37

**Comment by AdrianoDee** [comment]
+pdmv
(thanks @smuzaffar for the notice)

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
