### PR TITLE
[12.4.X]  New high granularity pixel alignment for the PCL 

### PR DESCRIPTION
**Pull request by mmusich**
backport of #38449 and #38508

PR description:

This is the last PR towards using a higher granularity (HG) for the pixel alignment in the PCL, following https://github.com/cms-sw/cmssw/pull/38371. It is planned to run the HG alignment in parallel to the LG alignment, with only the LG alignment updating the conditions. More details can also be found in [1].

In detail the following things are changed/added in this PR:
   * Adapt `MillePedeFileReader` and `MillePedeDQMModule` to read and store the high granularity alignment
   * Read and use the new thresholds in `MillePedeDQMModule` and `MillePedeAlignmentAlgorithm`
   * Store/read the `pede` results for the HG alignment in/from a separate folder, to avoid overwriting the LG result in the harvesting step.
   * Two new methods in the new HG threshold object, to get and store the float maps
   * Add workflows for the production and the harvesting required for the HG alignment in `CommonAlignmentProducer`
   * Add the new workflows to the PCL configuration
   * Add the LG and HG alignment to the 1001.2 workflows, which can be used with the `runTheMatrix.py` command
    * Add a relval customizer in `CommonAlignmentProducer` to override the 20 LS veto and required entries per structure in the HG aligment

PR validation:

The PR can be tested using the adapted relval workflow with `runTheMatrix.py -l 1001.2`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of  #38449 and #38508. As explained in the description it's needed for deplyoment of the new workflow in the 2022 high intensity data-taking. 

cc:
@dmeuser, @connorpa, @antoniovagnerini, @consuegs

[1] https://indico.cern.ch/event/1167313/contributions/4906905/attachments/2461217/4219804/AlCaDB_Meeting_13_06_22.pdf

### CODE REVIEW

**Comment by tvami** [comment]
urgent
 * needed for 12_4_X on Tuesday

**Comment by tvami** [comment]
+1

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38449

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38508

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test parameters: 
   * addpkg = Alignment/TrackerAlignment

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca
 * tests pass,
 * 1001.2 has the correct results
 * unit test is fixed

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

Backport

**Comment by tvami** [comment]
@cms-sw/orp-l2 we are essentially fully signed for this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
