### PR TITLE
Phase-2 L1T: fix isolation type for GT e/g objects

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

This is a bug-fix.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

- Trivial fix

**Comment by aloeliger** [comment]
Corresponds to https://github.com/cms-l1t-offline/cmssw/pull/1105

**Comment by AdrianoDee** [comment]
+upgrade
(Techical trivial fix)

**Comment by perrotta** [comment]
+1

**Pull request merged**
