### PR TITLE
bsunanda:Run2-hcx69 Create scenario to run with new HCAL TP

### PR DESCRIPTION
**Pull request by bsunanda**
This scenario is a temporary solution for HCAL 2016: TP's updated but rest as in 2015

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna  @davidlange6 This is the results of the HCAL group meeting of yesterday which puts in a solution that at least HCAL TP's can be updated. We are working on how the channels need to be updated. Could you please try to review and approve this at the earliest. I am preparing a backporting request to 8_0_X

**Comment by ianna** [comment]
+1

note, the PR is not tested by relval tests

**Comment by davidlange6** [comment]
@bsunanda - is there a recipe to test this through GEN-SIM-DIGI-RECO chain?

**Comment by bsunanda** [comment]
@davidlange6 I tested the code using the two following cmsDriver commands:
cmsDriver.py TTbar_Tauola_14TeV_cfi --conditions 80X_mcRun2_asymptotic_v5 -n 10 --era Run2_2016 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Gauss --geometry Extended2016a,Extended2016aReco --fileout file:step1.root --no_exec
cmsDriver.py step2 --conditions 80X_mcRun2_asymptotic_v5 -n 10 --era Run2_2016 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW --datatier GEN-SIM-DIGI-RAW --geometry Extended2016a,Extended2016aReco --filein file:step1.root --fileout file:step2.root --no_exec
There were no crashes.

**Comment by davidlange6** [comment]
@bsunanda - sorry for the slow answer - lets not make another scenario - this can be the 2016 geometry until you get the rest to work.  (so just move cmsExtendedGeometry2016aXML_cfi.py to cmsExtendedGeometry2016XML_cfi.py)
Thx

**Comment by bsunanda** [comment]
@davidlange6 Some of us are using cmsExtendedGeometry2016XML_cfi.py to test the loading of new constants in DB matching all specifications. I would remove GeometryExtended2016a and the corresponding Reco but like to preserve the cmsExtendedGeometry2016XML_cfi.py for our next step

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Please check this

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 - Reminder...

**Comment by bsunanda** [comment]
@davidlange6 Could you please accept this for 8_1_X as well. You have already accepted the backporting of this to 8_0_X

**Pull request merged**
