### PR TITLE
Revert "Merge pull request #15458 from mdhildreth/HIPPreMix80X"

### PR DESCRIPTION
**Pull request by mandrenguyen**
This reverts commit ff83b4754c878333ca6cdc4f9bd5119ecf12449f, reversing
changes made to 0125196b589633a3c00814f3bd4eff1de7279b9e.

@davidlange6 @mdhildreth :  Is this your preferred (interim) solution ?

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
Seems it's the only solution at the moment. Can someone confirm it actually fixes the problem?

Cheers
David

On May 1, 2017, at 12:11 PM, mandrenguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


This reverts commit ff83b47<https://github.com/cms-sw/cmssw/commit/ff83b4754c878333ca6cdc4f9bd5119ecf12449f>, reversing
changes made to 0125196<https://github.com/cms-sw/cmssw/commit/0125196b589633a3c00814f3bd4eff1de7279b9e>.

@davidlange6<https://github.com/davidlange6> @mdhildreth<https://github.com/mdhildreth> : Is this your preferred (interim) solution ?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cms-sw/cmssw/pull/18528

Commit Summary

  *   Revert "Merge pull request #15458 from mdhildreth/HIPPreMix80X"

File Changes

  *   M DataFormats/StdDictionaries/src/classes_def_others.xml<https://github.com/cms-sw/cmssw/pull/18528/files#diff-0> (1)
  *   M DataFormats/StdDictionaries/src/classes_def_vector.xml<https://github.com/cms-sw/cmssw/pull/18528/files#diff-1> (2)
  *   M DataFormats/StdDictionaries/src/classes_others.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-2> (1)
  *   M DataFormats/StdDictionaries/src/classes_vector.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-3> (1)
  *   M DataFormats/WrappedStdDictionaries/src/classes.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-4> (4)
  *   M DataFormats/WrappedStdDictionaries/src/classes_def.xml<https://github.com/cms-sw/cmssw/pull/18528/files#diff-5> (1)
  *   M SimGeneral/Configuration/python/SimGeneral_EventContent_cff.py<https://github.com/cms-sw/cmssw/pull/18528/files#diff-6> (1)
  *   M SimGeneral/DataMixingModule/plugins/DataMixingSiStripMCDigiWorker.cc<https://github.com/cms-sw/cmssw/pull/18528/files#diff-7> (167)
  *   M SimGeneral/DataMixingModule/plugins/DataMixingSiStripMCDigiWorker.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-8> (14)
  *   M SimGeneral/DataMixingModule/python/mixOne_simraw_on_sim_cfi.py<https://github.com/cms-sw/cmssw/pull/18528/files#diff-9> (9)
  *   M SimGeneral/MixingModule/plugins/MixingModule.cc<https://github.com/cms-sw/cmssw/pull/18528/files#diff-10> (89)
  *   M SimGeneral/MixingModule/python/SiStripSimParameters_cfi.py<https://github.com/cms-sw/cmssw/pull/18528/files#diff-11> (5)
  *   M SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.cc<https://github.com/cms-sw/cmssw/pull/18528/files#diff-12> (37)
  *   M SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-13> (21)
  *   M SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.cc<https://github.com/cms-sw/cmssw/pull/18528/files#diff-14> (148)
  *   M SimTracker/SiStripDigitizer/plugins/SiStripDigitizerAlgorithm.h<https://github.com/cms-sw/cmssw/pull/18528/files#diff-15> (18)

Patch Links:

  *   https://github.com/cms-sw/cmssw/pull/18528.patch
  *   https://github.com/cms-sw/cmssw/pull/18528.diff

**Comment by mandrenguyen** [comment]
@davidlange6 I confirmed that the offlinePrimaryVertices are sensible again (i.e., have non-beamspot values) with this reversion in place.

**Comment by davidlange6** [comment]
Ok thanks. I'll try to have a release put together tomorrow

Cheers,
David


On 1 May 2017, at 18:37, mandrenguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> I confirmed that the offlinePrimaryVertices are sensible again (i.e., have non-beamspot values) with this reversion in place.

**Pull request merged**
