### PR TITLE
CSC DQM Run3 related updates (12_4_X)

### PR DESCRIPTION
**Pull request by barvic**
#### PR description:

CSC DQM update for CSC Run3 related development (Run3 data formats, CSC-GEM readout, HMT Showers)

- Added CSC Run3 related plots (per chamber and summary) to the processing code. 
     - 9 summary plots (Run3 firmware check, HMT readout status, CSC-GEM VFATs readout) are enabled for online-offline configurations.
     - Run3-related per chamber plots are disabled for online-offline configurations by default. 
- (D)CFEBs data clusters finder code update with fixes for static analyzer (corresponding plots are disabled by default for online/offline DQM configurations anyway).
- Disabled empty and obsolete summary plots for offline configuration.
- Code cleanup.

NOTE: Would need additional CSC layouts/render plugin update after this PR will be merged. 

#### PR validation:

Tested with current real data samples from P5 during ongoing CSC Run3 commissioning and production validation.
Attached snapshot of the online-dev DQM GUI with added 9 summary plots.
cDQM_Run3_added_summary_plots

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Please advise if 12_3_X backport is needed for deployment at P5

### CODE REVIEW

**Comment by barvic** [comment]
Just updated DQM GUI proper screenshot with intended online layout changes for new plots.
 
cDQM_Run3_added_summary_plots_good

**Comment by emanueleusai** [comment]
@barvic concerning your request for a backport. Yes, we would like to have a 12_3 backport to deploy at P5. Please go ahead and prepare the backport.

**Comment by emanueleusai** [comment]
just to clarify my comment: 12_4 is about two months away, so if CSC wants it online asap, the 12_3 backport is the way to go.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
