### PR TITLE
Backport to 111X of L1-O2O fractional prescale propagation

### PR DESCRIPTION
**Pull request by hjkwon260**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is backport of https://github.com/cms-sw/cmssw/pull/30886. L1-O2O fractional prescale is planned to be tested in next MWGR and private global run.

One commit 6abb51c is added since edm::mpl is not present for 111X.

Ping @gekobs @panoskatsoulis @BenjaminRS @bundocka as well.

#### PR validation:
runTheMatrix test, code format check passed

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
Any objection from @cms-sw/alca-l2 @cms-sw/db-l2 @cms-sw/l1-l2 ?

**Comment by tlampen** [comment]
+alca

**Comment by ggovi** [comment]
The changes in this PR are introducing a the new class in replacement of an existing one; it looks like only the 'private' L1T workflow have been adapted for this replacement, while all of the consumer code ( HLT?) has not been touched.  This is obviously ok until you don't need updates on the existing tags ( implemented with the old class ). What is the plan/intention for this?

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@ggovi Changes in the GlobalTrigger on which the Offline worflows would depend need changes (changes of ints to floats, etc).  Work is started on this by the L1T GlobalTrigger experts.

**Comment by silviodonato** [comment]
urgent
to be included for the MWGR

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
