### PR TITLE
Replace C-style arrays with std::arrays (follow-up on #43771)

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Implement suggestions from https://github.com/cms-sw/cmssw/pull/43771#discussion_r1464007982

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR. Failure in comparison does not come from this PR.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
