### PR TITLE
Add mising std::vector<LocalTrajectoryParameters> dictionary

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Running ROOT under debug under the direction of Philippe Canal found this class being created on the fly by cling.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
