### PR TITLE
Adding fastjet shape correction for analysis in 76x (port of #11285)

### PR DESCRIPTION
**Pull request by rappoccio**
Forward-port of #11285.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11287 fa97fcfd2b0582eff8b12f92af6854fff2eba813

Adding Fast Jet shape correction, but disabled by default. There should be no change in standard workflows. The shape correction is intended for expert use by analysts. #11285 and #11286 are the 74X and 75X versions of this PR, and they have already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-09-16-1200 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
