### PR TITLE
fix standard and upgrade validation workflows

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

fixes what I broke in #44087

#### PR validation:

11024.15 ran properly

### CODE REVIEW

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2
Let's get this in soon to fix the RelVals.

**Comment by perrotta** [comment]
> @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 Let's get this in soon to fix the RelVals.

@antoniovilela @rappoccio it is rather annoying having all those errors in the IB, as they can hide real ones
Since the fix here is quite trivial, could you please bypass @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 signatures and get it merged?

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Comment by AdrianoDee** [comment]
+pdmv

(Signing just for the records and apologies for the delay)

**Pull request merged**
