### PR TITLE
Geant4e test example

### PR DESCRIPTION
**Pull request by lviliani**
An example including the basic functions to refit tracks with Geant4e has been added.

### CODE REVIEW

**Comment by civanch** [comment]
@lviliani , usually all test macro are in test sub-directory. Why in this case they are in doc? It is minor thing but I am confused.

**Comment by Dr15Jones** [comment]
Is the Geant4e code thread safe?

**Comment by lviliani** [comment]
@civanch , in the old Geant4e package the test example was in that sub-directory. That's why I put it there. Anyway it can be also moved in the test sub-directory.

**Comment by VinInn** [comment]
The assignment of this package is wrong...
this is reco not sim!

**Comment by civanch** [comment]
@Dr15Jones , the main parts of Geant4e (EM physics and navigation) are thread safe. Thread safety of Geant4e implementation within this package was not validated - the plan was first restore functionality in sequential mode. Probably, optimal will be to make an alternative plugin working in MT mode as we did for OscarProducer.

@VinInn, concerning package assignment: I fully agree that even depending on G4 it is RECO as other TrackPropagation sub-packages.

@lviliani , I would move all three python files from doc to test for consistency.

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@nclopezo - seems the tests are stuck. Could you have a look

**Comment by nclopezo** [comment]
Hi, they are in the queue, the queue is a bit full, they should start later during the afternoon.

**Comment by davidlange6** [comment]
Thanks!

**Pull request merged**
