### PR TITLE
Run3-alca240 Add one more isolated bunch AlCaReco to the AlCa matrix

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add one more isolated bunch AlCaReco to the AlCa matrix. May need to be back ported to CMSSW version 13_0_X

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May need to be back ported to version 13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
This should have been tested together with your other PR -- or well in the first place the commit should have gone to the other PR. The wf `1002.3` and `1002.4` tests the AlCaRECO matrix through the `ALCAPRODUCER:@allForPrompt` mechanism.

Since you have testing rights and seem to be exercising them happily... I let you put a meaning cmsbuild command together that actually does something related to your changes

**Comment by tvami** [comment]
test parameters:
  - workflows = 1002.3,1002.4
  - pull_request  = https://github.com/cms-sw/cmssw/pull/40952

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * now the `HcalCalIsolatedBunchFilter` is produced in the test https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1ef74e/31198/runTheMatrix-results/1002.3_RunZeroBias2022B/HcalCalIsolatedBunchFilter.root

**Comment by perrotta** [comment]
+1

**Pull request merged**
