### PR TITLE
 Validation/Configuration/python/autoValidation.py Phase2 modification

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

add electronValidation sequence in Phase2 because RECO branches did not appear into the root files (only the miniAOD ones). One line added in Validation/Configuration/python/autoValidation.py and one one sequence (electronOnlyValidation) added in autoValidation. 

#### PR validation:

tests with :

27434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D35_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D35+RecoFullGlobal_2023D35+HARVESTFullGlobal_2023D35/
29434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D42_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D42+RecoFullGlobal_2023D42+HARVESTFullGlobal_2023D42/
20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19/
20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17/
11624.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2021_GenSimFull+DigiFull_2021+RecoFull_2021+HARVESTFull_2021+ALCAFull_2021/
10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/

and all ran perfectly (the 2 last tests (11624 & 10824) are made to verify if the introduction did not alter the results.). 

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch -> OK
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html) -> OK
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html) -> OK

@beaudett

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @archiron, could you please make sure that subsystem name appears in the title of the PR?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@archiron this PR is adding 1377 histograms in the EGammaV folder, intended for phase2 Validation. Can you please add a PR description in the header for the records? Thanks!

**Comment by archiron** [comment]
> 
> 
> @archiron this PR is adding 1377 histograms in the EGammaV folder, intended for phase2 Validation. Can you please add a PR description in the header for the records? Thanks!

done yesterday morning. The description was already included but I kept the  signs.

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by beaudett** [comment]
Hello,
could it be envisioned to backport this PR into CMSSW_10_6 ? Thanks. F.

**Comment by fabiocos** [comment]
@beaudett for which purpose?

**Comment by beaudett** [comment]
we get requests from PPD to validate Phase 2 samples (in 10_6)  and we can't without this PR. To be honest, I don't know if there will an other request of such validation, but in case, it would be nice to have this PR included.

**Pull request merged**
