### PR TITLE
Run2-hcx210 Update dense indexing for Hcal Calibration Channels

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update dense indexing of Hcal calibration channels to be used during LS2 and post LS2 period

#### PR validation:

Tested with a specific code to see the translation from DetId to DenseId and vice versa

#### if this PR is a backport please specify the original PR:

Not to be back ported

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda for my understanding, is this modification backward compatible? From the tests I would say so, but I would like to have a confirmation

**Comment by bsunanda** [comment]
@fabiocos So far we used only CALIB_HX channels. Now we are adding HBX, HEX, HOX channels. The dense indexing for the earlier channels are backward compatible. The new ones are new any way

**Comment by fabiocos** [comment]
+1

**Pull request merged**
