### PR TITLE
HLT menu development for `14_2_X` (1/N)  [`15_0_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_2_X` (branch `CMSSW_15_0_X`): 
   * This is the PR for the master branch, which will then be backported down to 14_2_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
   * These updates correspond to the first batch of changes accumulated in the 14_2_X release cycle targeting the 2025 HLT menus. We start by migrating all sub-tables to `CMSSW_14_2_0` template, remove `customisations` for 14_2_X and update `get*HLT.sh` scripts
   
This update includes the integration of the following JIRA tickets:
- [CMSHLT-3402](https://its.cern.ch/jira/browse/CMSHLT-3402) [DQM,BTV] Product to be added in `EventContent` to solve empty online DQM plots: BTV
- [CMSHLT-3403](https://its.cern.ch/jira/browse/CMSHLT-3403) [TRK,AlCa] Request to add `HLT_IsoMu24_*` and `HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_*` to `hltDatasetHLTMonitor`
- [CMSHLT-3405](https://its.cern.ch/jira/browse/CMSHLT-3405) [TSG] Backport of latest online updates to TrackerVR menu
- [CMSHLT-3406](https://its.cern.ch/jira/browse/CMSHLT-3406) [TSG,DQM] Remove unneeded output collections from hltOutputDQMGPUvsCPU
- [CMSHLT-3407](https://its.cern.ch/jira/browse/CMSHLT-3407) [HIN] Removal of `HLT_PPRefDmesonTrackingGlobal_Dpt*` and `HLT_HICsAK4PFJet*` triggers from the combined table

In addition, the following changes are included:
- 83963d9165a6d988e4bd22d45af1d01f22985841: update input files for TSG tests to more modern datasets `Run2024I`
- f0e3769fc8507ee0a76ea0e1107290476ec86a4f: update hltPathOwners.json and README file

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_2_X` (current branch of HLT development).

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
