### PR TITLE
introduce DiMuonVertexValidation in Alignment validation suite

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR adds the necessary code to run the analysis presented [here](https://indico.cern.ch/event/992964/contributions/4340538/) and [here](https://indico.cern.ch/event/1025492/contributions/4343121/attachments/2235708/3789275/mm_ZMMVertex_PPDGeneral_29Apr2021.pdf). 
A new module `DiMuonVertexValidation` is added as well as templated configuration file that can be used to submit the job.
I have chosen not to interlace the new plugin with the all-in-one tool as there is anyway an improved version of the framework that is being worked up right now and should land into `cmssw` in the near future. 
Once that's available the analysis will be included there. 

#### PR validation:

Run augmented unit tests with `scram b runtests`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport is needed.
@vbotta @antoniovagnerini

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by yuanchao** [comment]
+1
* histogram plots for DiMuonVertexValidation
* code built ok (warnings are not part of the PR)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
