### PR TITLE
<backport of #19446> 92X backport for adding the calojet collection to MiniAOD

### PR DESCRIPTION
**Pull request by jingyuluo**
This is a 92X equivalent of PR #19446 , the same branch (jingyuluo:miniAOD-CaloJet) is used.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

this should be OK for 92X

**Comment by slava77** [comment]
backport of #19446

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20041	46778ba
- backport of https://github.com/cms-sw/cmssw/pull/19446	46778ba; the same topic branch and the same commit are used as in 93X
- jenkins tests pass

this simply adds a new product ```recoCaloJets_slimmedCaloJets__``` and should be straightforward to integrate in 92X both for the MCv1 and for the prompt reco.

**Comment by slava77** [comment]
-1
it looks like we are not updating 92X anymore for miniAOD

**Comment by jingyuluo** [comment]
Ok, I'll close this PR then...

**Pull request closed without merging**
