### PR TITLE
Update DQM (offline + HLTEvF) HLT track monitoring for Run3 era

### PR DESCRIPTION
**Pull request by mmasciov**
### PR description:

Along the line of PR #37090, this PR updates DQM HLT track monitoring for Run3, removing deprecated collections.
After confirming with @RSalvatico and @ram1123 (for EGM), this PR also updates EGM track monitoring with the same purpose.

FYI: @mmusich, @vmariani, @AdrianoDee, @kjpena, @slezki

### PR validation:

PR is technical, with no change in physics: only collections monitored in DQM are updated for Run3.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - outputs look as expected, as far as I can tell: O(1k) MEs are removed in Run-3 wfs, and those MEs were empty pre-PR (at least the ones I checked)

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
