### PR TITLE
Run3-gex108XA Backport al Geometry related files - xml and code for the corrected Run3 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport al Geometry related files - xml and code for the corrected Run3 geometry. These files and corrections to the algorithm (dd4hep version) were committed through a number of PR's. These files match with PR #36654

#### PR validation:

The runTheMatrix test workflows are not affected. They will be done once the scenarios are modified

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR backports #36338, #36470, #36486, #36551, #36648, #36653, #36663, #36755

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
It was a file open error in 4.76

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta @qliphy On both occasions the failure is in a workflow with missing file. This PR has nothing to do with the failure

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Backport of Run-3 related xml.

**Comment by perrotta** [comment]
Backport of #36653, #36486, #36338, #36470, #36551, #36755
(please check, and update the PR description with it)

**Review by perrotta — COMMENTED** [review]
This backport looks correct: it only remains to explain why only the modification to Geometry/ForwardCommonData/plugins/dd4hep/DDBHMAngular.cc was imported from #36648. If the intention was not to backport the test files, then there is no need to write that this PR also backports #36663, which is only an update to one of the files not  backported from #36648.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
This PR now fully backports #36338, #36470, #36486, #36551, #36648, #36653, #36663, #36755, thus reflecting correctly what stated in the PR description

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Add xml files and related stuffs needed for the updated Run3 geometry, but does not implement it yet

**Pull request merged**
