### PR TITLE
Phase2-hgx360F First attempt to make a Phase2 scenario with 0 overlaps with zero tolerance in lieu of #46565

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The first attempt to make a Phase2 scenario with 0 overlaps with zero tolerance in lieu of #46565

#### PR validation:

Tested using scripts in SimG4Core/PrintGeomInfo/test/python and also the scenario 32434.0 of runTheMatrix.py

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 32434.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,Run4

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , there are 64 cases when */2026/* directories are used. Likely we should not remove them now but should we created */run4/* instead and switch to this?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild please test
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by smuzaffar** [comment]
@makortel , bot search for `ERROR` keyword in the log and in this case it found
```
ERROR importing file  relval_data_highstats name 'base_wf_number_2022' is not defined
```

this is way it marked it failed. I will update the bot to include this in the summary if there is nothing else to show

**Comment by smuzaffar** [comment]
@srimanob , may be problem is reading [all relvals](https://github.com/cms-sw/cmssw/pull/46610#issuecomment-2459466706) `cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,Run4` .  You should only include the one which defined `32434.0` workflow

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 32434.0
- relvals_opt = -w Run4

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Thanks @makortel, just opened a "fix" for the `data_highstats` wf (https://github.com/cms-sw/cmssw/pull/46701). I'm not sure to understand why they were anyway loaded given no `data_highstats` was included in https://github.com/cms-sw/cmssw/pull/46610#issuecomment-2459466706. Let's see what happens with only `-w Run4`.

**Comment by AdrianoDee** [comment]
> I'm not sure to understand why they were anyway loaded given no `data_highstats` was included in [#46610 (comment)](https://github.com/cms-sw/cmssw/pull/46610#issuecomment-2459466706).

Ok apparently the simple fact that in `-w` option there's `highstats` have them loaded for some reason. That's definitely unexpected: looking at it.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@Moanwar, @subirsarkar Please approve this PR

**Comment by bsunanda** [comment]
@AdrianoDee, @DickyChant Please approve this PR

**Comment by bsunanda** [comment]
@antoniovilela, @mandrenguyen, Please approve and merge this PR

**Comment by bsunanda** [comment]
Impossible to remove the conflicts. So closing this in view of #46755

**Pull request closed without merging**
