### PR TITLE
Phase2-hgx316E Add a new scenario 2026D93 for the HGCal version 17 with no explicit cell declaration within full wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario 2026D93 for the HGCal version 17 with no explicit cell declaration within full wafers. The corresponding workflow for tuba at 14 TeV is 41434.0

#### PR validation:

Tested for the 2 workflows 41034.0 and 41434.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test workflow 41434.0

This is to test new D93 workflow.

**Comment by srimanob** [comment]
+Upgrade

This PR adds a new workflow for D93. PR test of new workflow runs fine.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
