### PR TITLE
Run3-gex40 Add scenarios with modified tracker material budgets for the Run3 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add 4 scenarios with modified tracker material budgets (changed by +-5%  or +-10%) for the Run3 scenario

#### PR validation:

Tested using a cfg file in Geometry/CMSCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , this one may be not needed in 11_2? what you think?

**Comment by bsunanda** [comment]
@civanch I also think it need not be back ported to 11_2_X. It is needed for Run3 data analysis which may be 11_3 or other future version

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
@bsunanda Is there still another PR required to create the 5/10% scenarios? I think DB loader scripts still need to be made.

**Comment by bsunanda** [comment]
@cvuosalo Yes - but that PR should be made after integrating this. Could you please approve this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@silviodonato @qliphy Can this PR be integrated?

**Comment by silviodonato** [comment]
+1

**Pull request merged**
