### PR TITLE
Backport of #31831 (Add maximum of pileup pT hats in JME custom NanoAOD) to 10_6_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #31831

**PR description:**

This PR adds the maximum of the pileup pT hats into the JME custom NanoAOD. This is done by modifying `NPUTablesProducer.cc`  to find the maximum value in the `vector<float>` returned by `getPU_pT_hats()` and then store in the PileUp table. 

A flag is also added and set to **false** in `globals_cff.py` so that this variable will not be stored in the main NanoAODs. The flag is set to true in `custom_jme_cff.py` so that it will be stored in the JME custom NanoAOD format.  

The variable is needed by JERC analyses, which will use the JME Custom NanoAODs. 

As mentioned in a comment in #31831, by running over 5K events on a UL17 TTJets sample, the size per event is 9.478 kb/event which is an increase of 0.04% from 9.474 kb/event.

**if this PR is a backport please specify the original PR:**

Original PR is #31831

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog
the changes are inline with master

(I noted that code-format tests are not triggered for backports and now looks like that the alignment of lines is not proper)

**Comment by qliphy** [comment]
code-checks

**Comment by qliphy** [comment]
@nurfikri89  Can you have a check with above code-checks output? thanks!

**Comment by nurfikri89** [comment]
Hi @qliphy . I have applied the code-format patch.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/xpog-l2  Would you please review and sign again?

**Comment by mariadalfonso** [comment]
+xpog
the changes are inline with master

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
