### PR TITLE
Updated cfg beampixel 10 0 4 vtx

### PR DESCRIPTION
**Pull request by dinardo**
Updated correct RecoPixelVertexing sequence.
- Mauro.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@dinardo after the move to 10_1_X this PR can be closed

**Comment by dinardo** [comment]
Do I need to make a PR for 10_1_X?

**Comment by fabiocos** [comment]
@dinardo in case this is needed and not yet part of the release, you need a master version, and then a backport to 10_1_X, as usual

**Pull request closed without merging**
