### PR TITLE
dummy PR to test gcc630 vs gcc530

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
Hi @smuzaffar - Looks good to me - @VinInn, @rovere - I presume that we do not expect identity in tracking when comparing across two different compilers for the usual reasons? [this is a gcc530 vs gcc630 test]
@slava77

**Comment by VinInn** [comment]
with Ofast, no. the compiler may refactor "better".
In any case I am using gcc6 since long (and now even gcc7) and dit not noticed any major performance difference

**Comment by davidlange6** [comment]
ok, good-then I think we can declare success and get a bigger scale validation.

**Comment by slava77** [comment]
On 3/15/17 1:35 AM, David Lange wrote:
> Hi @smuzaffar <https://github.com/smuzaffar> - Looks good to me -
> @VinInn <https://github.com/VinInn>, @rovere <https://github.com/rovere>
> - I presume that we do not expect identity in tracking when comparing
> across two different compilers for the usual reasons? [this is a gcc530
> vs gcc630 test]
> @slava77 <https://github.com/slava77>

HCAL fits are not so stable numerically either.
Looking at a few diffs, it seems like they trigger just as many small
diffs as tracking.

**Pull request closed without merging**
