### PR TITLE
Alpaka-related updates

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Various Alpaka-related updates:
  - move `HeterogeneousCore/AlpakaCore/interface/MakerMacros.h` under `alpaka/`
  - rename `alpaka_hip_async` to `alpaka_rocm_async`
  - adopt the "alternative module loading" approach in the Alpaka test

#### PR validation:

All unit tests should pass.

#### PR backport:

To be backported to `CMSSW_13_0_X` for 2023 data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@makortel this is a subset of #40725, hopefully without any controversial parts.

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
