### PR TITLE
Optimize NanoAOD buffers at 1k events.

### PR DESCRIPTION
**Pull request by bbockelm**
ROOT will automatically add 16 bytes per branch buffer per event in the event cluster; in the case of NanoAOD files, we've seen up to 143k events per cluster (and 800 branches), resulting in an excess of 900MB of memory usage.

With this change, we explicitly optimize NanoAOD buffers after 1k events, then subsequently flush at more appropriate intervals.  To achieve this, we disable the ROOT auto-flush mechanism and explicitly optimize / flush from the NanoAOD output module itself.

### CODE REVIEW

**Comment by fabiocos** [comment]
@bbockelm I think we would need this before in the master branch...

**Comment by fabiocos** [comment]
please test

**Comment by bbockelm** [comment]
@fabiocos - I created a new PR against master here: https://github.com/cms-sw/cmssw/pull/22624

**Comment by fabiocos** [comment]
@bbockelm thanks, looking at it

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
