### PR TITLE
[HeaderCheck][Reco] RecoVertex/KinematicFitPrimitives

### PR DESCRIPTION
**Pull request by mrodozov**
- Remove unused files

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26659	e7f03ab
- the cleanup looks OK: the commit which introduced this code a85d1e94b3223de9a3be1b3168df339a9452bfce ("First port from ORCA" made in 2006) did not have any use cases of either RecoVertex/KinematicFitPrimitives/interface/KinematicVertexAssociator.h or RecoVertex/KinematicFitPrimitives/interface/KinematicVertexDistance.h
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
