### PR TITLE
HF 1x1 TP production fixes

### PR DESCRIPTION
**Pull request by matz-e**
I have discovered two bugs in the code ported:
- long fibers were used instead of short ones
- ieta rings ±29 were not properly integrated with ieta rings ±30

With the fixes in this PR, 1x1 TP matching to the 2x3 TP is improved a lot.

### CODE REVIEW

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by abdoulline** [comment]
May we have it in pre5, please? 
Here is Matthias' results with this update
 https://indico.cern.ch/event/483399/session/0/contribution/5/attachments/1212017/1768073/hf_tp_update.pdf

**Comment by davidlange6** [comment]
@mulhearn - ping

**Comment by abdoulline** [comment]
@mulhearn - ping
(it's quite inconvenien to always merge this PR before running any further development/test jobs...)

**Comment by davidlange6** [comment]
I declare that @mulhearn signed it once already...

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Sorry for missed ping...

**Pull request merged**
