### PR TITLE
reorganise HLTrigger/Timer utilities (11.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Reorganise the `memory_usage` and `processor_model` utilities:
  - move the code from the plugin to the library
  - add unit tests
  - implement experimental support for monitoring per-thread peak memory usage with jemalloc

#### PR validation:

Unit tests compile, run, and give the expected results.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #29970

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@silviodonato this is the CMSSW PR that goes with https://github.com/cms-sw/cmsdist/pull/5897

**Comment by silviodonato** [comment]
+1

**Pull request merged**
