### PR TITLE
o2o ECAL(originally from depasse)

### PR DESCRIPTION
**Pull request by franzoni**
Porting to 80x of CMSSW tools used by ECAL o2o.
Originally 3 commits in this PR https://github.com/cms-sw/cmssw/pull/15319 , all three ported here.

. comment original by pierre: Ecal O2O tools in 8_0_1 (from O2O machine) to be transferred in 8_0_15.
. added handling of passwords via VarParsing

### CODE REVIEW

**Comment by franzoni** [comment]
@cmsbuild 
please test


@depasse @jeanfay @mmusich 
NOTA BENE: no central CMSSW sequence uses the o2o software involved in this PR

**Comment by mmusich** [comment]
please test

**Comment by franzoni** [comment]
@cmsbuild 
please test

**Comment by franzoni** [comment]
@depasse the PR for 81x has been placed
we'll need to follow up for the next steps

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
