### PR TITLE
HLT menu development for `12_4_X` (3/N) [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2282](https://its.cern.ch/jira/browse/CMSHLT-2282): [EXO] PFMETNoMu trigger with HF cleaning + low-pT double-photon triggers _(2nd and last part of the integration)_
  - [CMSHLT-2317](https://its.cern.ch/jira/browse/CMSHLT-2317): [BPH] new triggers for Bs->MuMuGamma search _(currently disabled, i.e. PS=0)_
  - [CMSHLT-2327](https://its.cern.ch/jira/browse/CMSHLT-2327): [BPH] new dimuon triggers for Upsilon and PsiPrime analyses _(currently disabled, i.e. PS=0)_
  - [CMSHLT-2328](https://its.cern.ch/jira/browse/CMSHLT-2328): [BPH] new trigger for Bc-meson spectroscopy _(currently disabled, i.e. PS=0)_
  - [CMSHLT-2333](https://its.cern.ch/jira/browse/CMSHLT-2333): [EGM,HIG] Naming: removed "`NoPixelVeto`" label from Diphoton Paths _(2nd and last part of the integration)_
  - [CMSHLT-2337](https://its.cern.ch/jira/browse/CMSHLT-2337): [MUO] Removal of 2 deprecated MC triggers of MUO POG
  - [CMSHLT-2339](https://its.cern.ch/jira/browse/CMSHLT-2339): [ECAL,TSG] Update HLT customisation for 2018 Data with ECAL UL calibrations (done in 2d0ece85df90b70385199e96c7f2b69184f0fafe)

`HLT/V62` also includes an update as part of [CMSHLT-2261](https://its.cern.ch/jira/browse/CMSHLT-2261), changing the prescale (PS) of the Path `HLT_DoubleMu4_3_Jpsi_v` from 20 to 10 (but PS changes are not tracked in CMSSW, and are thus not visible in this PR).

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are in line with the updates to the GRun HLT menu

**Comment by qliphy** [comment]
+1

**Comment by missirol** [comment]
Thanks @qliphy !

**Pull request merged**
