### PR TITLE
Provide a utility for efficiently copying multiple files to the local

### PR DESCRIPTION
**Pull request by bbockelm**
disk using "best practices" for reading from the local SE.

Ideally, this can be used for merging log files (which are not ROOT
format) from the local SE.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
-1
Brian, please make this for CMSSW_8_0. Also I don't think this belongs on IOPool/Common since it has nothing to do with ```PoolSource``` or ```PoolOutputModule```.  Is there a package which this code depends upon which also depends upon all the other packages it needs? If so, then this code should go into that top most package.

**Comment by Dr15Jones** [comment]
After a quick look, I take back my objection to putting this in IOPool/Common.

**Comment by bbockelm** [comment]
@Dr15Jones - will open a second PR for CMSSW_8_0_x branch.  However, I suspect we'll be asked for a backport to a release so I'll leave this open.

**Comment by davidlange6** [comment]
@cmsbuild, please test

@bbockelm @Dr15Jones - being a completely new function, we can stick with 76x and rely on the forward port

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
