### PR TITLE
Update frozen HLT menu from 2016 to 2017 (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update frozen HLT menu from 2016 to 2017 (93X)
Based on CMSSW_9_3_X_2017-07-19-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for additional addOnTests

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
