### PR TITLE
Updated IVF trackMinLayers cut in jetTools.py for MiniAOD

### PR DESCRIPTION
**Pull request by ferencek**
With #15605 merged, it is no longer necessary to relax the `trackMinLayers` cut in jetTools.py.

The following plots show the impact of this update. In 1D histograms the thick red line is always the same and shows the discriminator value stored in MiniAOD (i.e. computed from AOD) while the thin blue line shows the same discriminator recomputed from MiniAOD.

**1) Using slimmed IVF vertices stored in MiniAOD:**

csvv2ivf
csvv2ivf_scatter
csvv2ivf_diff

**2) Using IVF vertices recomputed from MiniAOD using the default `trackMinLayers` cut:**

csvv2ivf_ivffromminiaod
csvv2ivf_ivffromminiaod_scatter
csvv2ivf_ivffromminiaod_diff

**3) Using IVF vertices recomputed from MiniAOD with `trackMinLayers=0`:**

csvv2ivf_ivffromminiaod_trackminlayers0
csvv2ivf_ivffromminiaod_trackminlayers0_scatter
csvv2ivf_ivffromminiaod_trackminlayers0_diff

**4) Using IVF vertices recomputed from MiniAOD produced with #15605 merged and using the default `trackMinLayers` cut:**

csvv2ivf_ivffromminiaod_tklayersinminiaod
csvv2ivf_ivffromminiaod_tklayersinminiaod_scatter
csvv2ivf_ivffromminiaod_newminiaod_diff

**MiniAOD ROC curves:**

Legend
- filled red squares = 1)
- open black circles = 2)
- open blue triangles = 3)
- open green squares = 4)

rocs

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@ferencek 
does this affect the standard btagers?

**Comment by slava77** [comment]
please add commits from this PR to #15659 
both edit the same file and it looks like the context lines overlap.

**Comment by ferencek** [comment]
@slava77, whether the standard taggers are affected depends on how they are run. If they are run on top of MiniAOD with IVF vertices remade, then they are affected (see the last 3 1D histograms above). However, there will be no impact on the standard reco.

Also, I would prefer to keep this PR separate from #15659 regardless of the fact that they modify the same file. This PR was anticipated in https://github.com/cms-sw/cmssw/pull/15421#issuecomment-242484979 while #15659 addresses a very specific bug introduced in #15421.

**Comment by slava77** [comment]
On 8/31/16 8:36 AM, Dinko Ferencek wrote:
> @slava77 <https://github.com/slava77>, whether the standard taggers are
> affected depends on how they are run. If they are run on top of MiniAOD
> with IVF vertices remade, then they are affected (see the last 3 1D
> histograms above). 

> However, there will be no impact on the standard reco.

good to know

> 
> Also, I would prefer to keep this PR separate from #15659
> <https://github.com/cms-sw/cmssw/pull/15659> regardless of the fact that
> they modify the same file. This PR was anticipated in #15421 (comment)
> <https://github.com/cms-sw/cmssw/pull/15421#issuecomment-242484979>
> while #15659 <https://github.com/cms-sw/cmssw/pull/15659> addresses a
> very specific bug introduced in #15421
> <https://github.com/cms-sw/cmssw/pull/15421>.

The questions is then which PR should go first?
I expect merge conflicts.

**Comment by ferencek** [comment]
@slava77, there won't be any merge conflicts since the two modify lines which are not too close to each other. I also tested locally and they merge with no problems.

**Comment by slava77** [comment]
On 8/31/16 8:53 AM, Dinko Ferencek wrote:
> @slava77 <https://github.com/slava77>, there won't be any merge
> conflicts since the two modify lines which are not too close to each
> other. I also tested locally and they merge with no problems.

OK.

Do you have a ROC curve for the light.vs.b?

**Comment by ferencek** [comment]
No, I don't have them at the moment but will see what I can do about that since they would be useful to have.

**Comment by ferencek** [comment]
@slava77, I added ROC curves to the PR description. Overall, things look OK. The first nice feature is that the MiniAOD performance closely matches the one from AOD and the second one is that the `trackMinLayers` cut does not have a strong impact as long as the track layer info is stored in MiniAOD.

**Comment by slava77** [comment]
```
On 9/1/16 2:20 AM, Petra Van Mulders wrote:
> Seeing these ROC curves and the discriminator shapes makes me think that
> it is indeed best to use trackMinLayers=0.
> 
> Cheers,
> Petra
> 
> On 01/09/16 01:33, Dinko Ferencek wrote:
>>
>> I think that the ROC curves added to the description of #15684 
>> <https://github.com/cms-sw/cmssw/pull/15684> give us the needed 
>> answers. It should be fine to stay with |trackMinLayers=0| since the 
>> performance is similar to the one in AOD and the one with the default 
>> |trackMinLayers| cut with the "new" MiniAOD. However, there could be 
>> some small differences in efficiencies/mistag rates for the same 
>> discriminator cuts due to small differences in discriminator shapes.
>>
```

Does this mean that this PR is not really necessary?

**Comment by ferencek** [comment]
@slava77, in a way, yes, since there is no significant impact on the performance. On the other hand, it is better not to treat MiniAOD as a special case and have a uniform setup for both AOD and MiniAOD. In addition, we do see small differences in the discriminator distributions so it is better to integrate this PR. 

The only place where we are making an exception and will not integrate this change is the 80X release cycle because the old MiniAOD does not store the tracker layer info.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15684 8841d00
- code change is as described. This applies only for (re)running b-tagging IVF on top of miniAOD. Standard workflows are not affected.
- jenkins tests pass
- local check of expanded config for 136.722 shows unchanged configuration as expected.

**Pull request merged**
