### PR TITLE
Tau decay products in NanoDQM

### PR DESCRIPTION
**Pull request by Ksavva1021**
#### PR description:

This PR adds tau decay product information in NanoAOD. A collection of tau decay products is created on the fly and then stored in a new NanoAOD table. Additional information stored is as follows for each candidate in the table:

- 3-momenta
- PDG ID
- Index of its mother tau

Size tests have been conducted to assess the size increase on NanoAOD. These tests have been conducted using two RelVal samples:

- TTBar (/w PU)
- ZTT

The cumulative contribution of the tau decay products in NanoAOD is expected to be around 1.3 % (TTBar) and 2% (ZTT). Breakdowns are available [here](https://cernbox.cern.ch/s/7ImmLYlChHIIS41).

This PR also allows the tau decay products to be monitored by NanoDQM.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of PRs https://github.com/cms-sw/cmssw/pull/42987 & https://github.com/cms-sw/cmssw/pull/43382

### CODE REVIEW

**Comment by Ksavva1021** [comment]
Adding @mbluj as a watcher

**Comment by mandrenguyen** [comment]
unassign reconstruction
since it only relates to nano, this is xpog business

**Comment by mandrenguyen** [comment]
+reconstruction
Not sure why unassigned didn't work, so I'll just sign

**Comment by mbluj** [comment]
> v12 is with 13.0 and is closed. if this goes in 13.3, then it will be in the upcoming v13

Yes, right. It was mistype, I meant v13... So, indeed there is not need to backport to 13_2

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by vlimant** [comment]
type tau

**Pull request merged**
