### PR TITLE
Introduce `DiMuonMassBiasMonitor` for Tk Alignment ALCARECO monitoring purposes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to expand on the concept introduced at https://github.com/cms-sw/cmssw/pull/38378, about adding the DQM monitoring for the `ALCARECOTkAlDiMuonAndVertex` stream and adds a new DQM Analyzer (`DiMuonMassBiasMonitor`) to monitor the bias of the di-muon mass system as a function of the component track kinematics.

#### PR validation:

Relies on the existing unit tests. 
The output of it has been uploaded to a test GUI for convenience of inspection and it's available by connecting to:
```console
 ssh -NL 8060:localhost:8060 <USER>@lxplus724.cern.ch
````
and visiting https://tinyurl.com/2gapbtzy.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported to CMSSW_12_4_X for data-taking operations.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type trk,new-feature

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
