### PR TITLE
HLT menu development for `13_2_X` (4/N) [`13_3_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for CMSSW_13_2_X.

This is the PR for the master branch, which will then be backported down to 13_2_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

This version of the HIon HLT menu corresponds to the "V1.1" menu for the 2023 heavy-ion data-taking period (the corresponding frozen menu is not added to the release, as not needed by any central wf).

In addition, the following changes are included:
   *  3da0c3e353bd46072d27b0d508080b81668a55b4 update of L1T `HIon` menu in TSG GTs to [`L1Menu_CollisionsHeavyIons2023_v1_1_3_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsHeavyIons2023_v1_1_3_xml)
   * e6c1126b64eaa119fd056cf7423a835fbd50358b update of L1T `PRef` menu in TSG GTs to [`L1Menu_CollisionsPPRef2023_v1_1_2_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsPPRef2023_v1_1_2_xml)
       
This update includes the integration of the following JIRA tickets:

- [CMSHLT-2947](https://its.cern.ch/jira/browse/CMSHLT-2947) [HIN]: Wrong SiPixel inputs to `hltFullIter0PixelClusterCheckPreSplittingPPOnAAForDmeson`
- [CMSHLT-2942](https://its.cern.ch/jira/browse/CMSHLT-2942) [HIN]: Modify cluster filter parameters for HIon menu v1.1
- [CMSHLT-2944](https://its.cern.ch/jira/browse/CMSHLT-2944) [HIN]: Adding `HighRate` paths to V1.1
- [CMSHLT-2940](https://its.cern.ch/jira/browse/CMSHLT-2940) [TSG]: Wrong update of online HIon menu in `Run2023HI/v1.0.2/HLT/V16`
- [CMSHLT-2936](https://its.cern.ch/jira/browse/CMSHLT-2936) [HIN]: Request to split `HIForward` PD in "V1.1" `HIon` menu (20 PDs)
- [CMSHLT-2939](https://its.cern.ch/jira/browse/CMSHLT-2939) [HIN]: Add a `HIMB` copy paths to control express
- [CMSHLT-2932](https://its.cern.ch/jira/browse/CMSHLT-2932) [TSG]: Clean-up of prescale table for `HIon` paths in menu v1.1
- [CMSHLT-2938](https://its.cern.ch/jira/browse/CMSHLT-2938) [TSG]: Duplicate of L1T-seed module in `HIon` menu ("L1MinimumBiasHF1AND")
- [CMSHLT-2937](https://its.cern.ch/jira/browse/CMSHLT-2937) [HIN]: Fixing `RawPrime` data
- [CMSHLT-2933](https://its.cern.ch/jira/browse/CMSHLT-2933) [DQM]: Crash of `DQM` visualization event that consumes `streamEventDisplay`
- [CMSHLT-2866](https://its.cern.ch/jira/browse/CMSHLT-2866) [TSG]: Removal of `ReservedDoubleMuonLowMass` PD and stream
- [CMSHLT-2922](https://its.cern.ch/jira/browse/CMSHLT-2922) [HIN]: Summary of Heavy Ion requests after V1.0
- [CMSHLT-2912](https://its.cern.ch/jira/browse/CMSHLT-2912) [HIN]: Update of the HIN 2023 PbPb menu for UPC ZDC-based jet triggers
- [CMSHLT-2929](https://its.cern.ch/jira/browse/CMSHLT-2929) [HIN/AlCa]: Addition of ZDC seeds for some AlCa paths
- [CMSHLT-2925](https://its.cern.ch/jira/browse/CMSHLT-2925) [DQM]: Add triggers to `HIEventDisplay` dataset
- [CMSHLT-2926](https://its.cern.ch/jira/browse/CMSHLT-2882) [HIN]: Fix names of `HIUPC` Muon triggers (no `"MaxPixelTrack"`)
- [CMSHLT-2918](https://its.cern.ch/jira/browse/CMSHLT-2918) [HIN]: Replacement of jet seeds for DMeson triggers
- [CMSHLT-2917](https://its.cern.ch/jira/browse/CMSHLT-2917) [TSG]: Fix `hltL1sSingleJet80BptxAND` module in 2023 HIon menu

#### PR validation:

TSG tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but should be backported to CMSSW_13_2_X.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * as a side note, an online menu based off these updates (HLT HIon 2023 menu "v1.1") was [successfully deployed](https://cmsonline.cern.ch/webcenter/portal/cmsonline/Common/Elog?_piref683379043.strutsAction=%2FviewMessageDetails.do%3FmsgId%3D1197905) at P5 on Oct 2nd since run 374668.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
