### PR TITLE
Remove CaloGeometryRecord caching

### PR DESCRIPTION
**Pull request by argiro**
Fix a rare crash in clustering

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cvuosalo unless something had changed tests don't run against the patchesX branch.

**Comment by slava77** [comment]
@argiro 
Stefano
the fix should be done based on a recent 7_4_12_patch release (or, even the 7_4_12_patchX branch itself)

**Comment by argiro** [comment]
> On 23 Sep 2015, at 05:59, Slava Krutelyov <notifications@github.com> wrote:
> 
> @argiro 
> Stefano
> the fix should be done based on a recent 7_4_12_patch release (or, even the 7_4_12_patchX branch itself)
> 

I did it based on 7_4_12_patch4, what is wrong exactly ?

**Comment by lgray** [comment]
Hi Stefano, the problem is that you used the same branch to make the CMSSW
 7_4_X PR and the 7_4_patchX PR, and they are somewhat diverged at the
moment.

I would recommend that you take down the 7_4_X, rebase this branch and
update it using the commands I showed you yesterday except using
CMSSW_7_4_12_patchX instead of CMSSW_7_4_X, and then make a new branch that
you rebase to 7_4_X and then submit a new 7_4_X PR.

**Comment by argiro** [comment]
so #11414 is ok, but #11415 is not, correct ?

**Comment by lgray** [comment]
Right now 11414 is based on 7_4_X, since it shared the same branch as 11415.
You can see in 11415 that there is only one commit being brought in by the
PR, that's what we want to achieve for 11414.
However, it means you have to take down one of them and make a new PR based
on a new branch with the right history, since right now both PRs come from
the same branch.

**Comment by argiro** [comment]
closing and rebasing

**Pull request closed without merging**
