### PR TITLE
Fix DQM/L1TMonitor BuildFile

### PR DESCRIPTION
**Pull request by dmitrijus**
So that it generates proper plugins.
I hope it does not crash the IB this time.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by smuzaffar** [comment]
@dmitrijus , plugins/*.cc files only need DQM/L1TMonitor and FWCore/PluginManager. So please cleanup the dependency in DQM/L1TMonitor/plugins/BuildFile.xml.

You can also cleanup DQM/L1TMonitor/plugins/SealModule.cc and remove unused include FWCore/Framework/interface/MakerMacros.h

**Comment by dmitrijus** [comment]
Done!

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
thanks @dmitrijus 
could you submit for 80x as well?
cheers,
F.

**Comment by deguio** [comment]
+1

**Comment by dmitrijus** [comment]
I will make 80x after I'm sure this does not break the IB.

**Comment by davidlange6** [comment]
+1

**Comment by deguio** [comment]
please submit to 80x as well
thanks,
F.

**Pull request merged**
