### PR TITLE
Replaced AK8 and AK8 paths for ParticleNet DQMOffline monitoring for 2023 (master)

### PR DESCRIPTION
**Pull request by marinakolosova**
#### PR description:

Modified the PNet monitoring for AK4 and AK8 jets:
* Replaced AK4 CHS jets with Puppi
* Renamed the paths to match the ones for 2023 (JIRA: [CMSHLT-2695](https://its.cern.ch/jira/browse/CMSHLT-2695), [CMSHLT-2759](https://its.cern.ch/jira/browse/CMSHLT-2759)
* Added PNet monitoring in offlineHLTSourceOnAOD (PNet DQM not processed otherwise)

#### PR validation:

Went through the validation procedure described in [HLTValidationAndDQM](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTValidationAndDQM) to produce the PNet DQM histograms. 

The above changes will be backported to:
CMSSW_13_1_X
CMSSW_13_0_X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@marinakolosova @cms-sw/dqm-l2 

There is an error in the latest IB for wf 140.031, quite likely related to this PR, see https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_13_2_X_2023-05-15-1100/pyRelValMatrixLogs/run/140.031_RunMuonEG2022B/step3_RunMuonEG2022B.log#/

The log says:
```
%MSG
----- Begin Fatal Exception 15-May-2023 14:31:55 CEST-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing  Event run: 355769 lumi: 64 event: 41848823 stream: 0
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module ParticleNetJetTagMonitor/'particleNetAK4BTagMonitoring'
Exception Message:
AssociationVector: trying to use [] operator passing a reference
 with the wrong product id (i.e.: pointing to the wrong collection)
 keyRef.id = 5:3567, ref.id = 5:3565
----- End Fatal Exception -------------------------------------------------
```

Please have a look and provide a fix at your earliest

**Comment by marinakolosova** [comment]
Hi @perrotta, 

As this is urgent I reverted to just renaming the paths. Shall I create a new PR?

Thank you, 
Marina

**Comment by perrotta** [comment]
> As this is urgent I reverted to just renaming the paths. Shall I create a new PR?

Thank you @marinakolosova 
I think a correct fix should be implemented, I don't know whether "renaming the paths" can be such a correct fix.
"Urgent" does not mean that it has to be fixed within hours: if you can properly debug that workflow 140.031 and provide a proper fix in a day or two it is still fine. Then the fixed PR will get backported, if needed

**Comment by marinakolosova** [comment]
Hi @missirol @perrotta, a fix is provided here [PR41694](https://github.com/cms-sw/cmssw/pull/41694)

**Pull request merged**
