### PR TITLE
[CondCore] Print what executable is missing in condTestRegression.py

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Technical PR to print which executable is missing: https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/test/condTestRegression.py#L178

#### PR validation:

Tested locally

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by iarspider** [comment]
@tvami the `condTestRegression` test is failing in IBs as well [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_6_X_2022-08-31-1100/unitTestLogs/CondCore/CondDB#/51-51), do you know where the `run_condTestRegression.sh` should be coming from?

**Comment by mmusich** [comment]
> do you know where the run_condTestRegression.sh should be coming from?

isn't it created on the fly?

https://github.com/cms-sw/cmssw/blob/617fb50a01716b4bb99212da6a38203a8c45d121/CondCore/CondDB/test/condTestRegression.py#L153-L156

**Comment by smuzaffar** [comment]
Change in this PR is fine as it now properly prints the correct message about the missing executable in local area ( code then goes on and search for the executable in release dirs). But this is not going to fix the unit test.

**Comment by tvami** [comment]
@cmsbuild , please test
 * the IBs look clean for this unit test now https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_6_X_2022-09-06-1100/unitTestLogs/CondCore/CondDB#/51-51

**Comment by tvami** [comment]
+db
 * all tests are clear now

**Comment by perrotta** [comment]
+1

**Pull request merged**
