### PR TITLE
Fixed crash in RepeatingCachedRootSource

### LINKED ISSUE #36007: RepeatingCachedRootSource is broken
attn: @wddgit 

RepeatingCachedRootSource is broken in recent releases, it looks like due to the process block persistency changes, with `RepeatingCachedRootSource::makeRootFile()` passing in `processBlockHelper=nullptr`.  This was missed because the RepeatingCachedRootSource unit test was also broken, which is fixed by #36006.  With that PR, the unit test fails with this stack trace:

```
#0  0x00007f623cf98801 in edm::ProcessBlockHelper::initializeFromPrimaryInput (this=0x0, storedProcessBlockHelper=...) at /mnt/data1/dsr/CMSSW_12_1_0_pre3/src/FWCore/Common/src/ProcessBlockHelper.cc:123
#1  0x00007f61f55984b4 in edm::RootFile::RootFile (this=0x7f61e8e51e00, fileName="file:/mnt/data1/dsr/data/20a08d38-8b7f-4ce4-b24b-edc023ddd078.root", processConfiguration=..., logicalFileName="file:/mnt/data1/dsr/data/20a08d38-8b7f-4ce4-b24b-edc023ddd078.root", filePtr=std::shared_ptr<edm::InputFile> (use count 10, weak count 0) = {...}, eventSkipperByID=std::shared_ptr<edm::EventSkipperByID> (use count 4, weak count 0) = {...}, skipAnyEvents=false, remainingEvents=1000, remainingLumis=-1, nStreams=1, treeCacheSize=20971520, treeMaxVirtualSize=-1, processingMode=edm::InputSource::RunsLumisAndEvents, runHelper=0x7f6207fb7f28, noEventSort=true, productSelectorRules=..., inputType=edm::InputType::Primary, branchIDListHelper=std::shared_ptr<edm::BranchIDListHelper> (use count 6, weak count 0) = {...}, processBlockHelper=0x0, thinnedAssociationsHelper=std::shared_ptr<edm::ThinnedAssociationsHelper> (use count 6, weak count 0) = {...}, associationsFromSecondary=0x0, duplicateChecker=std::shared_ptr<edm::DuplicateChecker> (use count 4, weak count 0) = {...}, dropDescendants=false, processHistoryRegistry=..., indexesIntoFiles=std::vector of length 1, capacity 1 = {...}, currentIndexIntoFile=0, orderedProcessHistoryIDs=std::vector of length 1, capacity 1 = {...}, bypassVersionCheck=false, labelRawDataLikeMC=true, usingGoToEvent=false, enablePrefetching=true, enforceGUIDInFileName=false) at /mnt/data1/dsr/CMSSW_12_1_0_pre3/src/IOPool/Input/src/RootFile.cc:553
#2  0x00007f61f5582187 in std::make_unique<edm::RootFile, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::ProcessConfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<edm::InputFile>&, std::shared_ptr<edm::EventSkipperByID>&, bool&, int, int, int, unsigned int const&, int, edm::InputSource::ProcessingMode, edm::propagate_const<std::unique_ptr<edm::RunHelperBase, std::default_delete<edm::RunHelperBase> > >&, bool, edm::ProductSelectorRules&, edm::InputType, std::shared_ptr<edm::BranchIDListHelper>&, decltype(nullptr), std::shared_ptr<edm::ThinnedAssociationsHelper>&, decltype(nullptr), std::shared_ptr<edm::DuplicateChecker>&, bool, edm::ProcessHistoryRegistry&, std::vector<std::shared_ptr<edm::IndexIntoFile>, std::allocator<std::shared_ptr<edm::IndexIntoFile> > >&, int, std::vector<edm::Hash<2>, std::allocator<edm::Hash<2> > >&, bool, bool, bool, bool, bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::ProcessConfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<edm::InputFile>&, std::shared_ptr<edm::EventSkipperByID>&, bool&, int&&, int&&, int&&, unsigned int const&, int&&, edm::InputSource::ProcessingMode&&, edm::propagate_const<std::unique_ptr<edm::RunHelperBase, std::default_delete<edm::RunHelperBase> > >&, bool&&, edm::ProductSelectorRules&, edm::InputType&&, std::shared_ptr<edm::BranchIDListHelper>&, decltype(nullptr)&&, std::shared_ptr<edm::ThinnedAssociationsHelper>&, decltype(nullptr)&&, std::shared_ptr<edm::DuplicateChecker>&, bool&&, edm::ProcessHistoryRegistry&, std::vector<std::shared_ptr<edm::IndexIntoFile>, std::allocator<std::shared_ptr<edm::IndexIntoFile> > >&, int&&, std::vector<edm::Hash<2>, std::allocator<edm::Hash<2> > >&, bool&&, bool&&, bool&&, bool&&, bool&&) () at /cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h:857
#3  0x00007f61f557f296 in edm::RepeatingCachedRootSource::makeRootFile (this=0x7f62087e7680, logicalFileName="file:/mnt/data1/dsr/data/20a08d38-8b7f-4ce4-b24b-edc023ddd078.root", pName="file:/mnt/data1/dsr/data/20a08d38-8b7f-4ce4-b24b-edc023ddd078.root", isSkipping=false, filePtr=std::shared_ptr<edm::InputFile> (use count 10, weak count 0) = {...}, skipper=std::shared_ptr<edm::EventSkipperByID> (use count 4, weak count 0) = {...}, duplicateChecker=std::shared_ptr<edm::DuplicateChecker> (use count 4, weak count 0) = {...}, indexesIntoFiles=std::vector of length 1, capacity 1 = {...}) at /mnt/data1/dsr/CMSSW_12_1_0_pre3/src/IOPool/Input/src/RepeatingCachedRootSource.cc:287
```

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Properly handle ProcessBlocks.

#### PR validation:

Code compiles, and using the fixed unit tests it now runs.

fixes #36007

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test with #36006

**Comment by makortel** [comment]
+1

The error occurs already in the IBs. The test fixed in #36006 succeeds with this PR. @perrotta @qliphy I'd suggest to merge this PR and #36006 together.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
