### PR TITLE
L1T offine DQM changes for pp reference run - part1+2 - 94x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #21228 

To make the L1T offline DQM work for the pp reference run the trigger paths used must be adapted for the pp reference run HLT menu.

Part 2: L1T EG and L1T Jets

### CODE REVIEW

**Comment by thomreis** [comment]
Merged in PR #21197 to avoid conflicts.
This PR can now handle the backports of #21188 (merged already) and #21228 .

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request closed without merging**
