### PR TITLE
Apply esConsumes to DeDxEstimatorProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Extended DeDxTools to not directly interact with EventSetup.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI This came from the investigation into production modules using EventSetup.

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/33015	4aef1c5 
- technical
- jenkins tests pass (ignoring unrelated test infrastructure issues)

**Comment by silviodonato** [comment]
kind reminder @cms-sw/fastsim-l2

**Comment by silviodonato** [comment]
merge

**Pull request merged**
