### PR TITLE
Run3-gex94X Backport #35404 the new Run3 scenario with the updated PPS Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #35404 the new Run3 scenario with the updated PPS Geometry

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backporting #35404

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by AdrianoDee** [comment]
+Upgrade

**Comment by perrotta** [comment]
backport of #35404

**Comment by perrotta** [comment]
+1
- This PR backports comprehensively:
  - #35404
  - The definition of the "V7" forward detector geometry from #35380
  - The fix of the Sim Geometry definition in Geometry/HcalCommonData/python/hcalDDDSimConstants_cff.py from #35349
- All backports do not affect the running configurations of the already started campaigns in 12_0_X, as it was stated in the comments and reviews of the original PRs and verified by the lack of modifications observed in the automatic tests

**Pull request merged**
