### PR TITLE
2023dev Scenario Fix

### PR DESCRIPTION
**Pull request by ianna**
- Fixes crash in RPC geometry builder

### CODE REVIEW

**Comment by ianna** [comment]
@boudoul - you may want to fix 2023sim and 2023LReco scenarios accordingly.

**Comment by ianna** [comment]
@davidlange6 - as requested. I think, I'll need to rebase it though.

**Comment by davidlange6** [comment]
@ianna - yes, looks like a  rebase is needed - the IB is there now.

**Comment by ianna** [comment]
please test

**Pull request merged**
