### PR TITLE
Migrate TrackDetectorAssociator to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of https://github.com/cms-sw/cmssw/issues/31061. It migrates `TrackDetectorAssociator` helper class to EventSetup consumes as part of my attempt to fix failures of https://github.com/cms-sw/cmssw/pull/31746 (i.e. some user of it has been migrated to it). On the same go I migrated calling EDModules to ES consumes, and did some related minimal refactoring.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31802	d67bd80 
- technical; in line with the PR description
- jenkins tests pass with no relevant differences

**Comment by christopheralanwest** [comment]
+alca

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
