### PR TITLE
[DO NOT MERGE - TEST ONLY] Remove #31730 and #32021 from #31907

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

This PR is a copy of #31907 after having removed commits
- https://github.com/cms-sw/cmssw/pull/31907/commits/7884c359200bc3b0996f7503b110afa4f946be7c (Backport of #31730)
- https://github.com/cms-sw/cmssw/pull/31907/commits/02d8281f16dad355fd0623c3da11a92edc289743 (Backport of #32021)

The purpose of this PR is only the review of  #31907

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by rovere** [comment]
Thanks @silviodonato for this.
I briefly spoke with Andrea that alerted me about that.

**Comment by jfernan2** [comment]
It seems only change sin EGamma and HGCAL folders are produced:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-11-17-1100+d355e5/39938/dqm-histo-comparison-summary.html

**Comment by rovere** [comment]
Dear all,
this confirms the analysis I've posted in the original PR.
@silviodonato should we start the review process of #31907 or do you have additional checks you'd like to perform before doing that?
By the way, since the code changes in #31907 have been all reviewed, in single PRs, in `11_2`, I imagine the process could be rather smooth.
Let me know how you would like to proceed. I'll be happy to help if it's needed.

**Comment by perrotta** [comment]
> By the way, since the code changes in #31907 have been all reviewed, in single PRs, in `11_2`, I imagine the process could be rather smooth.

This check was great, and certainly helps in the review of #31907. I'll do my best to go through it as quicly as possible. Please however take into account that #31907 includes the backport of 9 different PRs merged in the master, and for a few of them that backport is not even complete. In the masters there were other HGCal related PRs merged which were not included in that backport, and this also must be taken care of while comparing the codes in the two releases, I commit myself in speeding up the review, but do not expect it can be concluded too soon.

**Comment by rovere** [comment]
> > By the way, since the code changes in #31907 have been all reviewed, in single PRs, in `11_2`, I imagine the process could be rather smooth.
> 
> This check was great, and certainly helps in the review of #31907. I'll do my best to go through it as quicly as possible. Please however take into account that #31907 includes the backport of 9 different PRs merged in the master, and for a few of them that backport is not even complete. In the masters there were other HGCal related PRs merged which were not included in that backport, and this also must be taken care of while comparing the codes in the two releases, I commit myself in speeding up the review, but do not expect it can be concluded too soon.

Thanks a lot @perrotta 
In doing the backport, I included the very bare minimum to avoid the inclusion of un-necessary code.
I'll be glad to help the review process in all possible ways.

**Pull request closed without merging**
