### PR TITLE
Initial Implementation of ProducesCollector

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Initial implementation of the ProducesCollector. The ProducerBase::produces function is now a protected member of ProducerBase. When produces needs to be called in a helper class (outside the module constructor), the ProducesCollector must be used. This PR also migrates all the code in the repository to work with this change. It does not affect modules that call produces directly inside their constructor.  The purpose is to reduce the number of things that depend on ProducerBase. Helper classes used by modules no longer need to depend on it.

#### PR validation:

Includes a new unit test for the ProducesCollector class.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

This should not change the results of any output.

**Comment by wddgit** [comment]
This PR is really very simple. ProducersCollector holds only a pointer to ProducerBase. A helper class calls the "produces" function of the collector which calls an identical "produces" function in ProducerBase instead of directly calling a ProducerBase function. There is nothing complicated going on with this one. It is analogous to ConsumesCollector.

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28154	ef9f5cd 
- technical 
- jenkins tests pass and comparisons show no  (relevant) differences

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@ssekmen @sbein @rekovic @civanch could you please check this PR?

**Comment by wddgit** [comment]
5 reviewers approved but still waiting for 3 on this PR. This one is a really simple technical software change. It creates a ProducesCollector analogous to the ConsumesCollector so
that modules do not have to interact directly with the ProducerBase class. Unless I've made a blatant mistake, it should have no effect on results or performance. It just improves code organization, reduces dependences, and makes the code easier to maintain. The changes outside the Core code simply migrate modules to use the new interface.

**Comment by fabiocos** [comment]
code-checks

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
In my test there is no real merge conflict with #28214 so the integration of this PR may move forward seamlessly

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@civanch please have a look, the implementation looks coherent with all the other areas as far as I can understand. I plan to integrate this PR in next IB tonight

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
