### PR TITLE
ECAL - Sort digis collections coming from GPU unpacking

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Contrary to the ECAL digis collections unpacked on a CPU, which are sorted by detector ID, the collections produced from digis that were unpacked on GPU are unsorted. This causes problems with the `find()` function of the `edm::DataFrameContainer`, which only works for sorted detector IDs.
Sorting the collections produced by `EcalCPUDigisProducer` fixes this.

This also adds some code simplifications to `HLTEcalPhiSymFilter`, which is the module for which the issue manifested itself first.

Addresses https://its.cern.ch/jira/browse/CMSHLT-2335

#### PR validation:

The digis collection stored by `hltEcalPhiSymFilter` matches between CPU and GPU machines after sorting the collections.

### CODE REVIEW

**Comment by missirol** [comment]
FYI: @fwyzard @Sam-Harper

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by Sam-Harper** [comment]
thank you Thomas. 

I do have one suggestion for HLTEcalPhiSymFilter, I get a bit nervous when folks do finds without checking their validity. Perhaps we can do a quick check to see that the result is valid and does not point to end() and if not throw an exception.

Given that this logic should always work unless there is change in the assumptions (that all rechits are in uncalibrated rec  and are in ecal digis and they are all sorted) and the results will be garbage if those assumptions change, I think it is reasonable to throw an exception. If the original author had done this, we would all have saved a bit of time debugging.

What do folks think?

**Comment by thomreis** [comment]
Good point. I had in mind to check for `end()` but then forgot about it when rushing to make the PR before leaving the office.

**Comment by fwyzard** [comment]
I'm wondering - if the digis are supposed to  be always sorted, should they be sorted already on the gpu by the unpacker ?

**Comment by Sam-Harper** [comment]
Thanks Thomas.  Also to note FOG is deploying a fix for the menu where we read the CPU collection for now. Obviously this isnt a long term fix as it means we always produce both CPU and GPU collections on a GPU but we are currently doing that anyway and can easily afford the CPU cost.  So we need this fix in but I would say its not an emergency fix, we have some time so you dont have to rush on the weekend :)

**Comment by missirol** [comment]
please test

**Comment by thomreis** [comment]
> I'm wondering - if the digis are supposed to be always sorted, should they be sorted already on the gpu by the unpacker ?

For the amplitude reconstruction each detector ID is handled independently of the others so sorted digis are not needed for that. Since this is the only module that consumes the digis on the GPU side (apart from the converters) I think it is not needed to sort the GPU digis at the moment. Would sorting on the GPU have an advantage?

**Comment by fwyzard** [comment]
> For the amplitude reconstruction each detector ID is handled independently of the others so sorted digis are not needed for that. 

OK, so the digis don't _need_ to be sorted, on their own.

> Since this is the only module that consumes the digis on the GPU side (apart from the converters) I think it is not needed to sort the GPU digis at the moment. Would sorting on the GPU have an advantage?

I think soring on the gpu _could_ be faster than sorting on the cpu; but I don't know for sure without implementing it and measuring it,
If sorting on the cpu is negligible in terms of reconstruction time, doing it on the gpu may not be worth it.


Unless we end up wanting to have sorted digis on the gpu _because_ of the modules that consume them, of course.
We can check with the PF group if that would be useful for them... though I would think _not_: my naive guess is that a parallel algorithm should not care about the ordering of its inputs.

**Comment by missirol** [comment]
+hlt

 - fixes a problem observed by ECAL, in one of the AlCa streams, for events processed on GPU at HLT (see [CMSHLT-2335](https://its.cern.ch/jira/browse/CMSHLT-2335))
 - there is a discussion ongoing on what the best implementation is [*], but I already sign the PR since the fix is valid and there might be interest in including [#38323](https://github.com/cms-sw/cmssw/pull/38323) in `12_4_0` (expected this week), and [#38322](https://github.com/cms-sw/cmssw/pull/38322) in the next release of `12_3_X`

[*] [This comment](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DataFormats/Common/interface/DataFrameContainer.h#L28-L29) suggests that usage of `DataFrameContainer::sort` (as in this PR) is sub-optimal.

**Comment by jpata** [comment]
+reconstruction
- fixes for HLT
- no effect observed in offline reco in the tests

**Comment by jpata** [comment]
type ecal

**Comment by thomreis** [comment]
@cms-sw/hcal-dpg-l2 this might interest you. To my knowledge HCAL uses `edm::DataFrameContainer` as well to store digis and if the digis coming from the GPU are not sorted this would lead to issues with `find()` like the ones we have observed in ECAL.

**Comment by mariadalfonso** [comment]
@thomreis

The HCAL-GPU production code is only limited to the RECO OOT-fit. 
The BIG speed gain is on this step.
The code for the HCAL-DIGI is in the release but pretty much untested and is not meant to be used (in addition to this PR probably many more things need to be taken care).

**Pull request merged**
