### PR TITLE
Update and cleaning of BPH trigger DQM/RelVal plots - backport to 12_5_X

### PR DESCRIPTION
**Pull request by vjmastra**
#### PR description:

Update DQM and RelVal code for BPH Trigger plots to take into account new triggers (eg inclusive dimuon trigger HLT_DoubleMuon4_3_LowMass_v), few changes in path names and cleaning of empty plots

Short report in STEAM meeting: https://indico.cern.ch/event/1180797/#17-b-physics-quarkonia-pag

#### PR validation:

Code has been tested following [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTValidationAndDQM#CMSSW_12_4_X_on_Run3_MC) in CMSSW 12_6_0_pre3 on a BuMixing RelVal [file](https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Frelval%2FCMSSW_12_6_0_pre2%2FRelValBuMixing_14%2FGEN-SIM-DIGI-RAW%2F125X_mcRun3_2022_realistic_v3-v1%2F2580000%2F0a16f6be-0412-493b-b8ee-ca62d9e6da98.root&instance=prod/global) 

Output file: /afs/cern.ch/user/v/vmastrap/public/bph-dqm-12_6_0_pre3/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 12_4_X (and 12_5_X) to have plots in the offline DQM GUI (now using 12_4)

Backport from 12_6 of PR #39768: https://github.com/cms-sw/cmssw/pull/39768
Backport to 12_4_X: https://github.com/cms-sw/cmssw/pull/39979

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39768

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- HLT path update PR

**Comment by perrotta** [comment]
@vjmastra @emanueleusai about the "cleaning" part of this PR: I see that large chunks of code have been just commented out, in separate but connected part of the code and configuration. I wouldn't really call it "cleaning", indeed...
Is there any reason why they need to stay there, even commented out? Wouldn't a real cleaning that removes all those parts, if not necessary, be more appropriate?
If they need instead to stay there, because they are expected to get resurrected any time soon, probably a cleaner way to do it is to add an additional configuration parameter that allows to switch them on and off when needed. Or at lease a few additional comment lines that explain to possible future maintainers of this code what those commented out lines are intended to, and what needs to be uncommented if they want to resurrect a given feature.
PS: I know that I already approved myself the master version of this PR; but evidently I missed this point. Please comment here, and if you think to really clean up the code and configurations, please make it in the master first, and then backport in this PR and in #39979

**Comment by emanueleusai** [comment]
@perrotta I agree the unused code should just be removed. @vjmastra can you clarify if the commented line are corresponding to the empty plots? if that's the case we should just remove them.

**Comment by vjmastra** [comment]
Dear @perrotta @emanueleusai 
I apologize for the late reply
I agree with you that this is indeed not a cleaning from the code point of view, but it is in the sense that many (empty) plots have been removed
If you think it is the case, I can try to make a better and cleaner update of the code for what concerns the commit "remove empty RelVal plots"

**Comment by perrotta** [comment]
> Dear @perrotta @emanueleusai I apologize for the late reply I agree with you that this is indeed not a cleaning from the code point of view, but it is in the sense that many (empty) plots have been removed If you think it is the case, I can try to make a better and cleaner update of the code for what concerns the commit "remove empty RelVal plots"

Yes, @vjmastra please do, starting from the master

**Comment by rappoccio** [comment]
At this point, is there any motivation to backport this to 12_5 since the datataking period is over? Should we leave it in the master branch alone?

**Comment by rappoccio** [comment]
+1

I suppose there's no harm in putting this in for consistency, it's already ready to go.

**Pull request merged**
