### PR TITLE
Remove outdated options in the CSC local trigger. 

### PR DESCRIPTION
**Pull request by dildick**
This PR removes the parameters `isMTCC` and `isTMB07` in the CSC local trigger.

The parameter `isMTCC` sets the CSC algorithm to the settings used for the Magnet Test and Cosmic Challenge (when the CSC system was partially installed above ground at P5). `isTMB07` sets the CSC algorithm to the default setting - which has been used since the start of physics data taking. The `isMTCC` algorithm still uses distrips. Distrips have not been used since the 2007 version of the firmware was installed. In addition, distrips are not used to trigger the chambers in the 2007 version of the simulation. So the options can be safely removed.

I also removed two outdated LCT quality definitions in the `CSCMotherboard` class.

I compared the output of the trigger primitive reader on 10,000 events in 2018D data before and after the pull request. I see no differences. 

FYI @tahuang1991 @ptcox @lpernie

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @dildick 
while you are at the code cleanup you might want to take a look at the findings of the static checks.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24254/29749/llvm-analysis/

**Comment by dildick** [comment]
@thomreis sure

**Comment by dildick** [comment]
@thomreis Do you have any more questions regarding this PR?

**Comment by thomreis** [comment]
Hi @dildick 
do you plan to fix any of the bugs listed on the static checks page? There is one in the CSCMotherboard.cc file for example. I guess also the rest could be easily fixed since it seems to be mostly unused variables.
Let me know if you think that this is out of the scope of this PR and if it  should rather be done in a separate one.

**Comment by thomreis** [comment]
Hi @dildick 
very good, thank you. The this one can go ahead.

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
