### PR TITLE
Switching BoostedDoubleSV tagger to v4 training for AK8 jets (80X)

### PR DESCRIPTION
**Pull request by ferencek**
80X backport of #17294 for legacy 80X re-MiniAOD.

@cvernier

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@ferencek are the files in 80X already?

**Comment by ferencek** [comment]
@slava77, yes, the v4 training file is already in 80X (see https://github.com/cms-sw/cmsdist/issues/2793).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17609	caf4b54
- change from V3 to V4 in input training file; affects double boosted tagging variable in slimmedJetsAK8 in miniAOD
- jenkins tests pass and comparisons with baseline show no differences (the relevant variable is not monitored)

I'm going to put this on hold until the rereco release is to be built.
To go with #17603

**Comment by slava77** [comment]
hold

until rereco release is to be built

**Pull request merged**
