### PR TITLE
Update monopole autoskim

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This main goal for this PR is to update autoSkim for monopole analysis. However, the structure of autoSkim has been updated following the discussion in https://github.com/cms-sw/cmssw/issues/37656
   + `autoSkimRunII` is made (clone of current `autoSkim`).
   + autoSkim is now for Run-3. The review and following PR should come when PDs are available.

#### PR validation:
None. No change is expected for the PR test since monopole skim will not change anything in DQM histograms.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
No need of backport.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by kskovpen** [comment]
Thanks @srimanob

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
Ping @cms-sw/pdmv-l2

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by tvami** [comment]
hi @srimanob (writing with my on ORM hat this week), 
I have a question and a comment: 
`EXOMONOPOLE` is being added to `SinglePhoton`, but `SinglePhoton` doesnt exists since 2017/2018. I hope that's clear.
And then the question: `EXOMONOPOLE` is not added to `MET`, is that on purpose? Thanks

**Comment by srimanob** [comment]
Hi @tvami 

Here are clarifications:
- For this PR, I made monopole on both singlephoton and egamma and I leave the message at the PR description that "autoSkim is now for Run-3. The review and following PR should come when PDs are available." So I expect responsible person to review and make an updated PR.
- It is by intension not to do the skim on MET (yet). We need analysis strategy, and reduce more the size. I may request when rereco happens.

**Comment by tvami** [comment]
Thanks Phat, I'll then remove the monopole skim from the MET

**Pull request merged**
