### PR TITLE
DAQ: support for FRD file header with file locking

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

- raw (FRD) file format for DAQ3 has recently been modified to include metadata in the header, so json files can be removed (due to 2 MB block constraint in huge-page ramdisk). Initially support was added with file broker mode. Now it is added to the file-locking mode which is used in testing and in Hilton.
- Support for the file header is also added to the single-buffer mode.
- Error handling in file locking mode is improved. It also allows unit test to catch problem in case JSON (raw) files can not be found. Since throwing exception is an issue in separate file discovery thread used by input source, error condition is propagated to the main thread instead of throwing directly.

PR includes also two bug fixes:
 - unique_ptr release() calls do not execute destructor of allocated object wrapped with unique_ptr. This created a (small) memory leak and also caused processed files to not be deleted in single-threaded input source mode (which is available, but not used by default in production setup).

 - in the check of non-opened fd value comparision was with 0, it should be compared with -1.

#### PR validation:

Verified to work correctly in DAQ test system in single-buffered/multi-buffered running modes, with file broker/locking, and with/without file header (and combinations).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by perrotta** [comment]
+1
- Updates relevant for DAQ
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
