### PR TITLE
Link board upgrade

### PR DESCRIPTION
**Pull request by bapavlov**
In the present system the Link Boards readout the RPCs every 25 ns, so although the RPCs has an excellent timing on the end the time is measured in BX (bunch crossings), where 1 BX =25 ns.
For PhaseII the RPC Link Boards are planed to be upgraded. The upgraded PhaseII Link Boards would be able to measure more precisely the RPC time, thus enabling precise time for the whole RPC system. The PR enables upgraded PhaseII Link Board readout to be simulated.  

We have added also an option to turn on/off electron digitization in the same way as it's done in the following PR:
#https://github.com/cms-sw/cmssw/pull/17898

### CODE REVIEW

**Comment by civanch** [comment]
@bapavlov , in the digi class you substitute cout by emd::LogInfo. It is enough to have one LogInfo statement and than use "\n" as cartrige return, the printout will be more readable.

There is special treatment of e-, why not also e+? there is some fraction inside RPC.

**Comment by bapavlov** [comment]
@civanch OK. I'll fix an issue with emd::LogInfo. 
About e-/e+ : 
Some time ago both e-/e+ were excluded on the digi step. Then it has been decided to exclude only e-,
because of their huge abundance in the SimHits. Anyway now it's a good occasion to add one more flag to deal with e+. So, I'll add such a flag.

**Comment by bapavlov** [comment]
Hi, @kpedro88, @calabria . Just to let you know that we are planning some changes in the digitizer.

**Comment by kpedro88** [comment]
@bapavlov are these changes important/necessary for the muon TDR central production?

**Comment by civanch** [comment]
@bapavlov , so, you do not apply a special treatment on low-energy e- but exclude it from new SimHits only. Likely majority of e+ will come from e+e- pair creation with not so low energy. Would number of SimHits be reasonable if a threshold (~1 MeV) for e- energy is applied? In that case, extra limit on e+ is not needed.

**Comment by bapavlov** [comment]
@kpedro88 yes, the changes are important for the production

**Comment by kpedro88** [comment]
@bapavlov needs rebase
@davidlange6 apparently this one is needed too...

**Comment by civanch** [comment]
please test

**Comment by bapavlov** [comment]
Sorry for the last commits. No further commits from my side.

The last updates just add up the functionality that the number of the simulated bunch crossing could be changed from the configuration file. It was requested yesterday by the people working on the RPC HSCP trigger. They want also to be able to re-digitize only the RPC digis, so we add function called customise_rpcRedigi to SimMuon/RPCDigitizer/python/customizeRPCDigi.py

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
add reconstruction
(as this is another PR of SIM code changing the RECO sequence)

**Comment by davidlange6** [comment]
in general we need really good reasons to introduce random numbers into the reco sequence.

**Comment by jhgoh** [comment]
@davidlange6 The customization function is not for the central production. It is only for a trigger study, re-digitization+reco will be done in analysis level.

**Comment by davidlange6** [comment]
maybe the customize is best left for private code then.

**Comment by jhgoh** [comment]
yep. or could it be OK to put into test directory?

**Comment by jhgoh** [comment]
We removed the customization function to be done in analysis level. 
The instruction to apply the redigi-on-the-fly will be  provided separately in a specific twiki page.

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
hi @bapavlov - given what i now understand to be the agreed production plan, i would suggest reverting e6a9a033ebc92ded4e38ffa6f1c7d6388a9c1be4

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by jhgoh** [comment]
This PR is to be used in the TDR production, so this one have to be back ported to 91X.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
