### PR TITLE
BuildFile cleanup: Remove un-used dependency

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Removed unnecessary dependencies

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
I suspect that the error is related somehow indirectly.
@smuzaffar did you check this already why it fails in jenkins  ? I'd guess that it worked in the local tests.

**Comment by slava77** [comment]
> I suspect that the error is related somehow indirectly.
> @smuzaffar did you check this already why it fails in jenkins ? I'd guess that it worked in the local tests.

ping

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort
@slava77 , I locally did not run 'cms-checkdeps -a -A' that is why it did not fail. I will update the PR soon.

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26395	d735c35
- technical
- jenkins tests pass and comparisons show no differences

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
