### PR TITLE
Backports of gen status flag related changes to 74x

### PR DESCRIPTION
**Pull request by bendavid**
Backports a fix to the definition of the status flags (critical for analysis/MINIAOD), plus agreed to backport together the relevant HLT validation changes making use of the new status flags.  (Fixing empty HLT validation plots which appeared on the transition to pythia8)

### CODE REVIEW

**Comment by bendavid** [comment]
@arizzi @gpetruc

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
