### PR TITLE
Enabling time-based sampling in LHCInfo O2O

### PR DESCRIPTION
**Pull request by ggovi**
In this PR:
- implement an O2O workflow to check the current Fill and search for next closed Fill
- execute the various queries sampling the target parameter with configurable time granularity
- provide a command line tool to dump the LHCInfo payload content

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
backport of #23068

**Comment by fabiocos** [comment]
+1

**Pull request merged**
