### PR TITLE
Backport to 74X of PR #8199 (cosmicMuonValidation)

### PR DESCRIPTION
**Pull request by abbiendi**
tested on 74X, ok.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@degano, @nclopezo: Are the Jenkins tests stuck for this PR?

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
@nclopezo, @degano: Jenkins comparisons for this PR are not complete. From the [logs] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-03-31-2300+8612/6984/alternative-comparisons/runDQMComp-25.0.log), it looks like a syntax error where dOpt is null instead of 0. Could you please investigate and fix this problem?

**Comment by cvuosalo** [comment]
+1

For #8612 c0dbcac4703211e6f04a67defc2a86d7cfafe981

This PR enhances cosmic muon validation. It also removes low-quality, unmatched muon tracks from validation plots since such tracks are often from PU or fake muons. This PR is the same as the already merged #8199 for 75X.

The code changes are satisfactory, as are the Jenkins test [results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8612/2528/summary.html). The Jenkins comparisons with baseline CMSSW_7_4_X_2015-03-31-2300  show no significant differences. The Jenkins comparisons are incomplete because of some problem unrelated to this PR. Since the code for this PR was already tested in #8199, it is unlikely that the missing comparisons would reveal any problems.

**Comment by deguio** [comment]
+1

**Comment by abbiendi** [comment]
Hi, just to know, is this PR still waiting to be merged ? why ?
thanks,
  Giovanni

On Apr 7, 2015, at 10:59 AM, cmsbuild wrote:


This pull request is fully signed and it will be integrated in one of the next CMSSW_7_4_X IBs unless changes (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @davidlange6<https://github.com/davidlange6>, @degano<https://github.com/degano>, @ktf<https://github.com/ktf>, @smuzaffar<https://github.com/smuzaffar>

**Comment by davidlange6** [comment]
@abbiendi - yes, this PR is still pending in the 74x milestone (as you can easily see by looking at the PR in github)

it needs a successful validation in 75x.

**Comment by abbiendi** [comment]
hi David,

this is quite unfortunate, as I am developing more improvements on top of this (both on the physics quality of the validation and on the technical performance -cpu-time/memory usage) that I am testing right now. Since I see there are also others' developments going on, this could introduce extra work, as for the need of rebasing and testing locally again, and chained delays.

  Giovanni


On Apr 16, 2015, at 2:06 AM, David Lange wrote:


@abbiendi<https://github.com/abbiendi> - yes, this PR is still pending in the 74x milestone (as you can easily see by looking at the PR in github)

it needs a successful validation in 75x.

**Comment by davidlange6** [comment]
I'm not sure how we could keep problems out of this important production release without a testing cycle for new developments. I'm open to suggestions..



On Apr 16, 2015, at 5:21 PM, abbiendi <notifications@github.com<mailto:notifications@github.com>> wrote:

hi David,

this is quite unfortunate, as I am developing more improvements on top of this (both on the physics quality of the validation and on the technical performance -cpu-time/memory usage) that I am testing right now. Since I see there are also others' developments going on, this could introduce extra work, as for the need of rebasing and testing locally again, and chained delays.

Giovanni


On Apr 16, 2015, at 2:06 AM, David Lange wrote:


@abbiendi<https://github.com/abbiendi> - yes, this PR is still pending in the 74x milestone (as you can easily see by looking at the PR in github)

it needs a successful validation in 75x.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
