### PR TITLE
Fix `SiPixelVCal` Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The  `SiPixelVCal` payload inspector was never used for lack of uploaded payloads. Now that the commissioning procedures for the Pixel gain calibration for Run-3 have started few bugs hindering the correct display of conditions at the  [payload inspector in CondDB](https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod) were found. These are fixed in this PR (b8f074a).
I profit to:
   * introduce a test script for this condition object in commit: 9000fd6 
   * complete the migration of `SiPixelLorentzAngle_PayloadInspector` to use class templates from #29622 in commit: 9e4545b 

#### PR validation:

Several standalone tests (outputs available [here](http://musich.web.cern.ch/musich/display/plots_VCal/)) plus  `scramv1 b runtests`  passed

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

NA

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@mmusich   This PR leads to a unit failure in recent IB.  Would you please have a check?

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-15-2300/unitTestLogs/CondCore/Utilities#/181-181
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'cond::BasicPayload'
getPayloadData.py --discover test not passed... found no entries
---> test testGetPayloadData had ERRORS

**Pull request merged**
