### PR TITLE
Phase2-hgx187 Update V10 geometry with input from Philippe

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the choice of wafer type from a study of radiation levels with Fluka simulation. Also added an additional method in HGCalGeometry to find area of individual cells - useful for evaluating signals at Digi level

#### PR validation:

Tested with the workflow as suggested in PR #26212

#### if this PR is a backport please specify the original PR:

These changes are to be added before freezing the V10 geometry of HGCal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@ianna @cvuosalo Could you please approve this PR. It should be a part of V10 geometry

**Comment by bsunanda** [comment]
@fabiocos could you also include this PR as a part of pre3.

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

the provided test runs smoothly as well as the D41 scenario test workflow 29034.0

**Pull request merged**
