### PR TITLE
Moved creating SiPixelTemplateStore from DB to an ESProducer [13_0]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All DB construction was switched to using EventSetup. Cases using reading from files were kept local to module.
The new ESProducer was added as a Task to all needed Sequences.

#### PR validation:

Code compiles.

backport of https://github.com/cms-sw/cmssw/pull/42514 and https://github.com/cms-sw/cmssw/pull/42597

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42514
backport of https://github.com/cms-sw/cmssw/pull/42597

**Comment by missirol** [comment]
+hlt

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by mmusich** [comment]
+hlt

**Comment by perrotta** [comment]
+alca

**Comment by perrotta** [comment]
+db

**Comment by emanueleusai** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
