### PR TITLE
add 2 production-like workflows for HI 2018

### PR DESCRIPTION
**Pull request by zhenhu**
To solve issue #24587 . 

Added two realistic chains that combine all the ingredients:

- the remapper introduced in #24819 on input data in HI-like format, as proposed in #24619 

- the `Run2_2018_pp_on_AA` era

- the realistic sequence suggested by Slava: `RAW2DIGI,L1Reco,RECO,EI,DQM:@common+@standardDQM+@ExtraHLT`. (EI and DQM bugs have been fixed by #24958)

- the `103X_dataRun2_Prompt_v2` GT, the `HIMinimumBias0` and `HIMinimumBiasReducedFormat0` datasets, and Run 325174 suggested by Ivan

Local test with steamer files runs successfully. But the RAW files for run 325174 are not available on DAS yet.

### CODE REVIEW

**Comment by zhenhu** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
Run 325174 is available on DAS now! I slightly updated the input dataset names. Local test successful.

**Comment by zhenhu** [comment]
please test workflow 140.56,140.57

**Comment by zhenhu** [comment]
+1

**Comment by zhenhu** [comment]
> @zhenhu thank you a lot, I would like to see the final test once the samples are repacked and available in eos, I assume this should happen in the week end

Hi @fabiocos and @kpedro88 , the final test with RAW input from DAS is also successful. Could you please review and sign it again?

**Comment by fabiocos** [comment]
merge

@kpedro88 the only change compared to your signature is the version of the input, please sign it in case again for reference

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
