### PR TITLE
Use ESGetToken in ESProducers in L1Trigger/TrackTrigger

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #26748. For some reason the `scram b code-format` made a lot of unrelated formatting changes to `TTStubAlgorithm_official.h`, they are all isolated in the last commit.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
