### PR TITLE
Run3-174I Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for the Heavy Ion MC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for the Heavy Ion MC

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backporting the scenario relevant for ZDC in CMS setup to be used for Heavy Ion MC simulation

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

this is minimal update to have ZDC

**Comment by rappoccio** [comment]
+1

**Pull request merged**
