### PR TITLE
Pr90x L1T Stage2 for Phase2

### PR DESCRIPTION
**Pull request by rekovic**
PR 90x for change in configuration to use L1T Stage2 (as opposed to L1T Legacy) in Phase2 era.
This PR also includes (needed to pass tests) https://github.com/cms-sw/cmssw/pull/17260 which fixed crashes in HCAL TPs for Phase2 

This PR is needed for Phase2 MC Production.

Details:
  - Use phase2_common era modifier to 
    - switch in L1T configuration to use Stage2 
    - configure conditions of L1T Muon, Calorimeter, and Global (as in Stage2)
    - configure L1T RAW2DIGI and DIGI2RAW to use Stage2 products
  - Include back in  simHcalTrigPrimitiveDigis and simHcalTTPDigis into hcalDigiSequence

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
ping @franzoni 
ping @civanch 
Can you please review and sign.
attn @davidlange6 
We would like this to be used for Phase2 Tracker TDR MC.
Thanks

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
ping @franzoni,  @arunhep, @cerminar  
Please review and sign/comment.

**Comment by franzoni** [comment]
hello @rekovic 

do you understand the changes in LocalTrigger of DT's , in the 2023 workflows of the matrix ? 
see for instance https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-01-25-1100+17248/18001/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D7_GenSimHLBeamSpotFull14+DigiFull_2023D7+RecoFullGlobal_2023D7+HARVESTFullGlobal_2023D7/DT_03-LocalTrigger-TM.html 

all the 2023 are affected by that.

**Comment by franzoni** [comment]
+1

signing for AlCa since the only file you've modified which is under our signature 
only changes the logic behind the HCAL trigger primitives
and I can't imagine (a simple explanation ) for that to be the reason of the DT local trigger change 
( see my previous post )

**Comment by rekovic** [comment]
Thanks @franzoni 
Compared to Legacy, the Stage2 trigger has all new muon track finders.
However, none of DT or DT TP code was changed, so I am not sure about these plots.

**Comment by davidlange6** [comment]
+1
(but @rekovic - you need to migrate away from is chosens..)

**Comment by davidlange6** [comment]
Hi @rekovic - I notice belatedly that this looks to have broken some relval tests. Can you have a look

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_0_X_2017-02-01-2300/pyRelValMatrixLogs/run/21253.0_QCD_Pt_600_800_14+QCD_Pt_600_800_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4/step2_QCD_Pt_600_800_14+QCD_Pt_600_800_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4.log

**Comment by rekovic** [comment]
@davidlange6, @matz-e  The exceptions seem to be due to `HcalTrigPrimDigiProducer` and the LUTs used.

<pre>
   [3] Calling method for module HcalTrigPrimDigiProducer/'simHcalTriggerPrimitiveDigis'
Exception Message:
LUT has 1024 entries for 1661 but 1186 was requested.
----- End Fatal Exception -------------------------------------------------
</pre>

**Comment by davidlange6** [comment]
these were the changes that presumably led to the errors

	• #17341 from davidlange6: more workflows that can not use recycled gensim at this point
	• #17320 from syuvivida: Fix of GenFilterInfo in 90X release
	• #17278 from ggovi: conddb tools improvements
	• #17248 from cms-l1t-offline: Pr90x L1T Stage2 for Phase2
	• #17337 from franzoni: alignment (asy and real) Consistent with Fpix updated Thickness (290 instead of 300 mum)
	• #17335 from kpedro88: Fix or suppress warnings related to Phase0 HE in 2017
	• #17098 from VinInn: Remove Trajectory from event

unless there is an undocumented change in the GT, this is presumably from 17248.. we can revert it to confirm?

**Comment by rekovic** [comment]
`simHcalTriggerPrimitiveDigis` were not executed prior to 17248.

**Comment by davidlange6** [comment]
ok, so yes, its due to this PR. ..we’ll back this out later today while you and hcal work on the fix. (which is presumably an inconsistent configuration)

**Comment by matz-e** [comment]
I'll look into it.

**Comment by rekovic** [comment]
ok

**Comment by matz-e** [comment]
So… HCAL has not yet defined any trigger modes beyond 2017, and this is tripping this crash. I'll work on a solution.

**Comment by davidlange6** [comment]
and as an added bonus, this PR generates a bunch of errors that we need a fix for

!@#$ Converted hit with station 1, CSC_ID 1, sector index 6, subsector 2, wire 5, strip 213, BX 0, neighbor 0 has no match
!@#$ Option 1 with endcap 1, station 1, CSC_ID 1, ring 4, chamber 24, wire 4, strip 28, BX 0, neighbor 0
!@#$ Option 2 with endcap 1, station 1, CSC_ID 1, ring 4, chamber 24, wire 4, strip 31, BX 0, neighbor 0
!@#$ Option 3 with endcap 1, station 1, CSC_ID 2, ring 1, chamber 19, wire 23, strip 22, BX 0, neighbor 0
!@#$ Option 4 with endcap 1, station 1, CSC_ID 4, ring 2, chamber 18, wire 44, strip 122, BX 0, neighbor 0
!@#$ Option 5 with endcap 1, station 2, CSC_ID 3, ring 1, chamber 10, wire 53, strip 10, BX 0, neighbor 0
!@#$ Option 6 with endcap 1, station 2, CSC_ID 3, ring 1, chamber 10, wire 53, strip 10, BX 0, neighbor 1
!@#$ Option 7 with endcap 1, station 2, CSC_ID 2, ring 1, chamber 12, wire 12, strip 102, BX 0, neighbor 0
!@#$ Option 8 with endcap 1, station 2, CSC_ID 7, ring 2, chamber 6, wire 48, strip 147, BX 0, neighbor 0
!@#$ Option 9 with endcap 1, station 2, CSC_ID 7, ring 2, chamber 12, wire 13, strip 24, BX 0, neighbor 0
!@#$ Option 10 with endcap 1, station 2, CSC_ID 7, ring 2, chamber 18, wire 20, strip 128, BX 0, neighbor 0
!@#$ Option 11 with endcap 1, station 3, CSC_ID 3, ring 1, chamber 10, wire 59, strip 148, BX 0, neighbor 0

**Comment by rekovic** [comment]
@davidlange6 Which test workflow produced the above cout ?

**Pull request merged**
