### PR TITLE
Update BuildFile for TopQuarkAnalysis/TopEventSelection 

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In #27214 a header consistency check failure was missed before the integration, and the same problem may be seen in CMSSW_11_0_X_2019-06-19-2300 . This PR updates the BuildFile of ```TopQuarkAnalysis/TopEventSelection``` adding the dependency on Utilities/Xerces .

#### PR validation:

```scram b code-checks``` is now successful on ```TopQuarkAnalysis/TopEventSelection```, and the code compiles correctly.

### CODE REVIEW

**Comment by smuzaffar** [comment]
As `TopQuarkAnalysis/TopEventSelection/interface/TtSemiLRSignalSelObservables.h` includes `PhysicsTools/MVATrainer/interface/MVATrainer.h` so I would suggest to add `<use name="PhysicsTools/MVATrainer"/>` instead

**Comment by fabiocos** [comment]
@smuzaffar let me try it and update

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@santocch I will merge this fix in next IB, please have a look

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
