### PR TITLE
Add ECAL TPG double weight tags and remove GEMELMapRcd from GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR is a technical update of the GTs:
- Adds new ECAL TPG double weights tags as requested in [this HN post](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4387.html) and further detailed in [this presentation at the AlCaDB meeting](https://indico.cern.ch/event/1020767/contributions/4284465/attachments/2217442/3754331/21_03_29%20-AlcaDB%20meeting%20-%20double%20weights%20CMSSW%20integration.pdf).
  - Since the tags are now included in the GTs I removed ` SimCalorimetry/EcalTrigPrimProducers/python/ecalTrigPrimESDoubleWeights_cff.py` and updated `SimCalorimetry/EcalTrigPrimProducers/python/ecalTriggerPrimitiveDigis_cff.py`
- Removes the `GEMELMapRcd` tag from all the GTs as requested in [this HN post](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4368.html).

GTs diff:
**Run 1 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun1_design_v2/113X_mcRun1_design_v3

**Run 1 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun1_realistic_v2/113X_mcRun1_realistic_v3

**Run 1 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun1_HeavyIon_v2/113X_mcRun1_HeavyIon_v3

**Run 1 proton-heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun1_pA_v2/113X_mcRun1_pA_v3

**Run 2 startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_startup_v2/113X_mcRun2_startup_v3

**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_l1stage1_v3/113X_mcRun2_asymptotic_l1stage1_v4

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_design_v3/113X_mcRun2_design_v4

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_preVFP_v3/113X_mcRun2_asymptotic_preVFP_v4

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_asymptotic_v3/113X_mcRun2_asymptotic_v4

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2cosmics_asymptotic_deco_v3/113X_mcRun2cosmics_asymptotic_deco_v4

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_HeavyIon_v3/113X_mcRun2_HeavyIon_v4

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun2_pA_v3/113X_mcRun2_pA_v4

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_v5/113X_dataRun2_v6

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HEfail_v5/113X_dataRun2_HEfail_v6

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_relval_v5/113X_dataRun2_relval_v6

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_PromptLike_HI_v5/113X_dataRun2_PromptLike_HI_v6

**Run 3 data HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_HLT_v3/113X_dataRun3_HLT_v1

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HLT_relval_v6/113X_dataRun2_HLT_relval_v1

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_Express_v5/113X_dataRun3_Express_v1

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_Prompt_v5/113X_dataRun3_Prompt_v1

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017_design_v4/113X_mc2017_design_v5

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017_realistic_v4/113X_mc2017_realistic_v5

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017cosmics_realistic_deco_v4/113X_mc2017cosmics_realistic_deco_v5

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mc2017cosmics_realistic_peak_v4/113X_mc2017cosmics_realistic_peak_v5

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_design_v4/113X_upgrade2018_design_v5

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_v4/113X_upgrade2018_realistic_v5

**2018 Run-dependent MC**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_RD_v3/113X_upgrade2018_realistic_RD_v4

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_HI_v4/113X_upgrade2018_realistic_HI_v5

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018_realistic_HEfail_v4/113X_upgrade2018_realistic_HEfail_v5

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018cosmics_realistic_deco_v4/113X_upgrade2018cosmics_realistic_deco_v5

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_upgrade2018cosmics_realistic_peak_v4/113X_upgrade2018cosmics_realistic_peak_v5

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_design_v7/113X_mcRun3_2021_design_v8

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_realistic_v9/113X_mcRun3_2021_realistic_v10

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021cosmics_realistic_deco_v8/113X_mcRun3_2021cosmics_realistic_deco_v9

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2021_realistic_HI_v7/113X_mcRun3_2021_realistic_HI_v8

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2023_realistic_v7/113X_mcRun3_2023_realistic_v8

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun3_2024_realistic_v7/113X_mcRun3_2024_realistic_v8

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_mcRun4_realistic_v6/113X_mcRun4_realistic_v7

#### PR validation:
Tested with:
`runTheMatrix.py -l limited,140.0,1325.516,7.22,145.0,281.0,136.8642,138.2,138.1,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0 --ibeos -j 9`

#### Backport
This PR is not a backport but will be backported to 113X.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
 - workflow = 140.0,1325.516,7.22,145.0,281.0,136.8642,138.2,138.1,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
FYI @valsdav

**Comment by valsdav** [comment]
Hi @francescobrivio,  it looks all fine from ECAL side. 
Thanks a lot

**Comment by christopheralanwest** [comment]
+1 

- Purely technical change moves tags from hardcoded `ESSource` to GT
- No changes expected or observed in any workflow

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
