### PR TITLE
clean-up of unused HLTrigger/Configuration customization functions

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to address [CMSHLT-3299](https://its.cern.ch/jira/browse/CMSHLT-3299) by cleaning up few bits of unused customizations in the `HLTrigger/Configuration` area:

1) `customizeHLTforAlpaka.py`: remove all customization, but keep the file for future developments
2) `customizeHLTforNewDatasetDefinition.py`: remove completely.
3) `customizeHLTforCMSSW.py`: remove the following functions:
```
def customiseHCALFor2018Input(prcess):
def customiseFor2017DtUnpacking(process):
def customisePixelGainForRun2Input(process):
def customisePixelL1ClusterThresholdForRun2Input(process):
def customiseCTPPSFor2018Input(process):
def customiseEGammaRecoFor2018Input(process):
def customiseBeamSpotFor2018Input(process):
def customiseECALCalibrationsFor2018Input(process):
def customiseFor2018Input(process):
def checkHLTfor43774(process):
```
4) `customizeHLTforMC.py`: remove its content completely but keep the file (it is called from various places in CMSSW).

#### PR validation:

`addOnTests.py` runs fine. No regressions are expected

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, will not be backported

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by fwyzard** [comment]
> `customizeHLTforAlpaka.py`: remove all customization, but keep the file for future developments

I would actually remove the file, and any references to it, since we are only using alpaka-based modules in the menu.

I think that any further developments can use regular customisations.

**Comment by mmusich** [comment]
> any references to it

there's no reference left as of today. 

> I think that any further developments can use regular customisations.

I was under the impression it might still be useful to use a separate customization function to be activated only upon usage of the `alpaka` modifier, but I have no strong opinion. In case it become useful again it can easily be resurrected, so we can remove the file in the next regular STORM update.

**Pull request merged**
