### PR TITLE
Improve plotting utilities to generate Tracker maps given user input

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a quick follow-up to https://github.com/cms-sw/cmssw/pull/45795, in which few improvements are added to the tools to generate Tracker maps given user input introduced there:
   * f47039b168c7084cfc9c08bba14323b706fb06c1 adds help functions to `printPixelROCsMap`, `printPixelTrackerMap`, `printPixelLayersDisksMap` and `printStripTrackerMap`
   * 2931551ccc0a2d1aae903080b5cd82970b56097d adds unit tests (`testPrintTkMaps`)
   * 8c91a071efd51965c5c5879ee545dafb64bf5e40 improves `printPixelROCsMap` to accept full, barrel and forward drawing options
  
#### PR validation:

`scram b runtests_testPrintTkMaps` runs fine.

Example map obtained collecting the bad ROCs for [run-386872](https://cmsoms.cern.ch/cms/runs/report?cms_run=386872) in which ROCs 7 and 15 disabled on the Layer1 modules for the full run (see e.g.  [here](https://indico.cern.ch/event/1455577/contributions/6186152/attachments/2949810/5184828/TkDQM_L1_thresholds_Oct24.pdf#page=12) and [here](https://tinyurl.com/29wrmg82)).

Phase1PixelROCMap_barrel

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
ping @cms-sw/dqm-l2

**Comment by antoniovagnerini** [comment]
+1
- spurious errors from HGCal DQM test (open issue #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
