### PR TITLE
Pr103x HeavyIon  2018 CaloLayer2, Un/Packer, Emulator,  O2O

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_3_X

EtSum type algorithms designed for HeavyIon 2018 data taking.
 *  kTowerCount,
 * kCentrality,
 *  kAsymEt,
 *  kAsymHt,
 *  kAsymEtHF,
 *  kAsymHtHF
are implemented in CaloLayer2 subsystem of the L1 trigger.  

Changes are made in the CaloLayer 
 - Unpacker, 
 - Packer, 
 - Emulator, 
 - O2O online producer

This PR does not depend on the updated UTM library, and can be merged independently.

However, this PR is needed merged for a PR on GlobalTrigger (#24570) to be tested, which in turn
also depends on the new UTM library v 0.7.1 (https://github.com/cms-sw/cmsdist/pull/4338).

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic as far as I can see from comparisons, they are not affecting only HI workflows but also regular pp ones. Could you please confirm that this is intended?

**Comment by rekovic** [comment]
@fabiocos 
There are new added types EtSums for Hi in the DataFormat, but not meaningful for p-p.   They will be available in every wf that emulates Calo, also wf's with packer and unpacker,  .   Can you please point me to a DQM plot that you might be referring to?  Thx.

**Comment by fabiocos** [comment]
@rekovic you may check failed comparisons for wfs 10024, 10224, 10042 for instance...

**Comment by fabiocos** [comment]
+1

checking with @rekovic just additional information is added with no modification to the existing one

**Pull request merged**
