### PR TITLE
Backport Puppi speedups [10_6_X]

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This PR is a combined backport of three speedups for Puppi:
1. Use reserve for vectors of candidates (see #37717)
2. Avoid creating/filling reco objects unnecessarily in `useExistingWeights` case (based on #27929)
3. Avoid use of unnecessary candidate vector and temporary object in `useExistingWeights` case (based on #28033)

In my test of the `useExistingWeights` case (on a UL17 ttbar sample), the combination of these three changes reduced the CPU usage of `PuppiProducer` by 50%.

#### PR validation:

Code compiles and runs. CPU impact quantified with igprof. Compared AK8 jet pT in a ttbar workflow to confirm that no changes occurred.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

See above. Reason: to speed up ultra-legacy analysis processing.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by jpata** [comment]
type jetmet

**Comment by clacaputo** [comment]
test parameters

- enable_test = profiling

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@jpata  @kpedro88 , looks like the default workflow for profiling `35234.21` ( https://github.com/cms-sw/cms-bot/pull/1721/files ) is not available in 10.6.X thatis why [PR profiling job](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-profiling/233/console) is failing . if profiling is needed for 10.6.X then can we adjust bot to use a different workflow?

**Comment by jpata** [comment]
Actually we were not sure what will happen when profiling in this backport, good to know that it fails due to the missing Phase2 workflow. I guess it's not critical here, one can rely on the profiling in the master.

**Comment by kpedro88** [comment]
To my recollection, none of the prodlike workflows used for profiling are available in 10_6_X.

**Comment by clacaputo** [comment]
+reconstruction

- backport of different speedup improvements for PUPPI
  - WFs used in profiling aren't available for 10_6_X 
  - the effect of #37717 can be seen here https://github.com/cms-sw/cmssw/pull/37717#issuecomment-1113558599
- no reco changes expected or observed

**Review by perrotta — COMMENTED** [review]
Since you are cleaning and you are not verbatim backporting the three PRs, you can also consider:

**Comment by kpedro88** [comment]
@perrotta done in the latest commit

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
+1
- Code speedup, no changes on outputs

**Pull request merged**
