### PR TITLE
2017 HCAL TPs in HE are actually truncated at 10 bits.

### PR DESCRIPTION
**Pull request by matz-e**
Adjustment after talking with @jmmans last week.  Changing the names to keep
the code flexible and allowing different compression scales in the future.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
mmh, 18h of running, seems the tests are stuck

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@ghellwig, @cerminar, @rekovic, @franzoni, @mmusich, @mulhearn, @davidlange6 ping for pre13

**Comment by mmusich** [comment]
@cmsbuild, please test
for some reason the comparison with the baseline is not available

**Comment by matz-e** [comment]
I don't know why @cmsbuild says that comparisons are ready… the linked page shows them as running…

**Comment by mmusich** [comment]
please test
let's try another time (from visual inspection seems OK)

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@ghellwig, @cerminar, @rekovic, @franzoni, @mmusich, @mulhearn, @davidlange6 please sign

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1
still the comparisons from the cms-bot relvals are missing

**Comment by davidlange6** [comment]
please test
(lets see if we get comparisons)

**Comment by davidlange6** [comment]
+1
@smuzaffar - can you have a look at why the comparisons seem never to finish?

**Comment by smuzaffar** [comment]
@davidlange6 , could not find any reason why previous job did not upload the results. I will update the script to have more debug information.
For now I just reran the testst and comparison results are available now,

**Pull request merged**
