### PR TITLE
Backport of New Trigger Filter Bits for Muon POG NanoAOD

### PR DESCRIPTION
**Pull request by rbhattacharya04**
This pull request is the backport of the pull request - https://github.com/cms-sw/cmssw/pull/44345

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44345

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
