### PR TITLE
`HcalRespCorrs_PayloadInspector`: add comparison and correlation of two response corrections payloads

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Updated `HcalRespCorrs_PayloadInspector`.
Implemented:
  * `HcalRespCorrsComparatorBase` (and its derived classes)
  * `HcalRespCorrsCorrelationBase` (and its derived classes)

The added plot are in the same style as the ones used for https://its.cern.ch/jira/browse/CMSALCA-283

#### PR validation:

Run the testing script added in this PR:

```
getPayloadData.py \
    --plugin pluginHcalRespCorrs_PayloadInspector \
    --plot plot_HcalRespCorrsComparatorTwoTags \
    --tag HcalRespCorrs_2024_v1.0_data \
    --tagtwo HcalRespCorrs_2024_v2.0_data  \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "1"}' \
    --iovstwo '{"start_iov": "1", "end_iov": "1"}' \
    --db Prod \
    --test;

getPayloadData.py \
    --plugin pluginHcalRespCorrs_PayloadInspector \
    --plot plot_HcalRespCorrsCorrelationTwoTags \
    --tag HcalRespCorrs_2024_v1.0_data \
    --tagtwo HcalRespCorrs_2024_v2.0_data  \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "1"}' \
    --iovstwo '{"start_iov": "1", "end_iov": "1"}' \
    --db Prod \
    --test;
```

and obtained the following plots.
HcalRespCorrsCompareTwoTags

HcalRespCorrsCorrelateTwoTags

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+db

**Comment by rappoccio** [comment]
+1

**Pull request merged**
