### PR TITLE
New ME0GeometryBuilder for baseline ME0 geometry

### PR DESCRIPTION
**Pull request by pietverwilligen**
Use the newest ME0GeometryBuilder also for the M1 geometry (it was already in use for the M2 geometry where ME0 consist of 10 eta partitions). This PR provides the most detailed description of the ME0 Geometry also for the M1 geometry with a single eta partition. This PR is needed for studies the GEM Reco&Val group will perform on (eventually reprocessed by ourself) DIGI-RECO samples.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@pietverwilligen @calabria 

I noticed that ME0 hits are now placed at 0 in local y instead of some not very realistic but still more practical ~flat distribution along the chamber length

all_oldvsnew_ttbar14tev2023d4wf21234p0c_me0detidme0rechitsownedrangemap_me0rechits_reco_obj_collection_data_localposition_y

If I'm not mistaken, this should mean that downstream ME0 reco is broken.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-01-13-1100+17175/17858/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFull_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4/Muons_RecoMuonV_MultiTrack_extractMe0Muons.html

Please check and comment when should we expect a fix.

**Comment by pietverwilligen** [comment]
I provided a bugfix: PR #17250

**Pull request merged**
