### PR TITLE
bsunanda:Phase2-hgx64 streamline the validation codes and the cff files

### PR DESCRIPTION
**Pull request by bsunanda**
Make the standard validation codes simpler and use the default configuration to match the current default of HGCal geometry (hexagonal EE and FH + HCal as BH)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
