### PR TITLE
HLT menu development for `12_4_X` (4/N) + migration to `12_4_0` + frozen menu `V1.2` for 2022 [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

 - Development of HLT menus for `CMSSW_12_4_X`.
 - Migration of HLT configs to release template `CMSSW_12_4_0`.
 - Introduction of `V1.2` frozen (GRun) menu to be used for MC production in `12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2267](https://its.cern.ch/jira/browse/CMSHLT-2267): [EXO] Update of displaced-ditau trigger
  - [CMSHLT-2287](https://its.cern.ch/jira/browse/CMSHLT-2287): [TSG] Update of `HLTDebug*` EventContents with `DQMGPUvsCPU` output collections
  - [CMSHLT-2304](https://its.cern.ch/jira/browse/CMSHLT-2304): [MUO,BPH] Change L1T seed of `HLT_Mu15`, remove `HLT_Mu7p5_TkX`
  - [CMSHLT-2315](https://its.cern.ch/jira/browse/CMSHLT-2315): [ECAL] Disable energy-recovery in ECAL RecHit producers
  - [CMSHLT-2326](https://its.cern.ch/jira/browse/CMSHLT-2326): [EXO] Update of 2 triggers with new displaced-global-muon reconstruction
  - [CMSHLT-2336](https://its.cern.ch/jira/browse/CMSHLT-2336): [TSG] Disable unclaimed triggers (90 triggers in total)
  - [CMSHLT-2343](https://its.cern.ch/jira/browse/CMSHLT-2343): [TSG] Add `DQMGPUvsCPU` stream to `HIon` and `PRef` menus
  - [CMSHLT-2344](https://its.cern.ch/jira/browse/CMSHLT-2344): [BPH] Disabled `HLT_DoubleMu2_Jpsi_DoubleTkMu0_Phi_v`
  - [CMSHLT-2346](https://its.cern.ch/jira/browse/CMSHLT-2346): [BPH] Removed `*ToCSCS*` single-muon 2018-Parking triggers and dataset
  - [CMSHLT-2348](https://its.cern.ch/jira/browse/CMSHLT-2348): [BPH] Disabled single-muon 2018-Parking triggers _(integrated partially; Paths not yet removed nor replaced)_
  - [CMSHLT-2353](https://its.cern.ch/jira/browse/CMSHLT-2353): [L1T] Update of MET L1T seeds

In addition, HLT configs will now use `cms.ConditionalTask`s instead of `cms.Task`s thanks a recent update of `ConfDB` ([`V03-04-00`](https://github.com/cms-sw/hlt-confdb/releases/tag/V03-04-00)). Further details on the reasons behind this change can be found in https://github.com/cms-sw/cmssw/issues/36938.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
@Martin-Grunewald 

I noticed that [`runIntegration.csh`](https://github.com/cms-sw/cmssw/blob/7d1b9f3d4e39dca4c67abbd4cac32d95cdc9d79c/HLTrigger/Configuration/test/runIntegration.csh) does not make use of the Frozen GRun menu. Should that be updated similarly to [`runOne.csh`](https://github.com/cms-sw/cmssw/blob/7d1b9f3d4e39dca4c67abbd4cac32d95cdc9d79c/HLTrigger/Configuration/test/runOne.csh) ? If so, should I do it in this PR (and backport), or in a future one?

**Comment by Martin-Grunewald** [comment]
Yes, it should be added under 'frozen' together with the Fake* in these PRs.

**Comment by Martin-Grunewald** [comment]
... and also under 'all'

**Comment by missirol** [comment]
> under 'frozen' together with the Fake*

In runOne, "frozen" does not include the Fake menus (those are only under "fake"). I assume we want to keep the same structure ("frozen"=frozenGRun, "fake"=fake menus).

**Comment by Martin-Grunewald** [comment]
Ah yes, fake for the fakes, frozen for the real non-fake menus such as 2022v12!!

**Comment by missirol** [comment]
please test

The latest force-push only updates the script `runIntegration.csh`, and this change won't be detected by the PR tests. The rest of the PR is unchanged with respect to its original version.

In the [PR outputs](https://github.com/cms-sw/cmssw/pull/38482#issuecomment-1165060810), there are a few differences reported that I don't fully understand:
 - one is in [`GlobalRecHitsV/HCals`](https://tinyurl.com/28wg9ut2), and I don't know exactly how that gets filled; in the HLT menu, there were changes to the HLT ECAL (not HCAL) RecHits, but other than that nothing that can explains these diffs in an obvious way;
 - the other is in [`HLT/SiStrip`](https://tinyurl.com/22d9l2hu) (similarly to https://github.com/cms-sw/cmssw/pull/38241#issuecomment-1150473390); this might be related to the removal of some BPH triggers that were using regional tracking, but this is just speculation on my part.

It's worth stressing that (by construction) this PR only changes the outputs of HLT; it does not affect the outputs of any other reconstruction/simulation step.

**Comment by missirol** [comment]
+hlt

 - outputs of PR tests are in line with changes to the HLT menus, even though some differences are not fully understood by me (see https://github.com/cms-sw/cmssw/pull/38482#issuecomment-1165303040)
 - in particular, it is not clear what causes the differences in [`GlobalRecHitsV/HCals`](https://tinyurl.com/28wg9ut2), and I don't see how HLT changes can induce those diffs (I see nothing to be changed on the HLT side, and I don't really know how plots are filled)

**Comment by missirol** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 , please consider reviewing this PR and its backport. The latter is needed for the upcoming MC production in `12_4_X`.

The changes in `Configuration/PyReleaseValidation` are simple.

**Comment by missirol** [comment]
I think I understand now the differences in [`GlobalRecHitsV/HCals`](https://tinyurl.com/28wg9ut2).

This PR modifies the `FEVTDEBUGHLT` EventContent adding (among others) new collections of HCAL RecHits, i.e. `hltHbherecoLegacy` and `hltHbherecoFromGPU` (the latter is filled only on GPU).

In the wfs in question, this modifies the output of "step2", which is the input to "step3". The histograms in questions are filled in "step3" by the Validation plugin `GlobalRecHitsAnalyzer`. For HCAL RecHits only, the latter plugin uses _all_ the `HcalRecHit` collections available in the input file:
https://github.com/cms-sw/cmssw/blob/0f0c0f386988fd5bab9233ee34166f43bc4c6c18/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc#L31

This can explain the differences (more entries in those HCAL plots post-PR, because the EDM input contains more collections of HCAL RecHits). I dare say that HLT makes no guarantee that the collections in `FEVTDEBUHLT` are mutually exclusive, so the logic of the Validation plugin might have to improved (by the relevant experts).

**Comment by srimanob** [comment]
+Upgrade

From the upgrade side, only HLT key is updated from 2021 to 2022.

**Comment by perrotta** [comment]
urgent

**Comment by missirol** [comment]
@cms-sw/pdmv-l2 , a second ping to review this PR (and its backport). The only change to review is the renaming of `HLT:@relval2021` to `HLT:@relval2022`.

We should start testing these PRs in IBs asap, to exclude unexpected issues in time for the next `12_4_X` release early next week.

**Comment by kskovpen** [comment]
+pdmv

**Comment by missirol** [comment]
Thanks, @kskovpen . Could you please sign the backport (#38483) as well?

**Comment by kskovpen** [comment]
Sorry - this did!

**Comment by qliphy** [comment]
+1

**Pull request merged**
