### PR TITLE
10_6_X Fixed FullModelHadronicProcess.cc energy deposit model

### PR DESCRIPTION
**Pull request by ctdax**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [previous PR](https://github.com/cms-sw/cmssw/pull/46728) to CMSSW_10_6_X. This backport is necessary because CMSSW_10_6_X was the version used for the recently submitted [HSCP dE/dx analysis.](https://cms-results.web.cern.ch/cms-results/public-results/publications/EXO-18-002/)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
@cms-sw/orp-l2 we'd like to ask for a new 10_6_X release with this

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46728

**Comment by mandrenguyen** [comment]
+1
As requested by @tvami we will start with a 10_6_X build followed by a 12_4_X.

**Comment by mandrenguyen** [comment]
Correction:  The 10_6_X build requires https://github.com/cms-sw/cmsdist/pull/9546
So we will start with 12_4_X

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/9546 is now merged for 10.6.X

**Pull request merged**
