### PR TITLE
Fix the customization functions of genpart pruning in NanoGEN

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Fix bugs in genparticle pruning functions in NanoGEN. Previously the Nano pruner wasn't actually propogated to the GenParticleTable, and the mini pruner somehow had the source messed up.

#### PR validation:

Confirmed that both the Mini-like pruner and NanoAOD-like pruner work on MiniAOD and gridpack input

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
+xpog

update in nanoGEN

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
