### PR TITLE
Run4-hgx286N Update HGCal xml files in view of future extension of algorithms

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update HGCal xml files in view of future extension of algorithms

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Could you check and approve this PR at your earliest convenience?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
In general, I would prefer that geometry components have unique names. Unique names make it easier to search through the code to find how a component is used. You are adding several versions of `LayerRotation`. It would be helpful if you could append a few letters to each one to make them unique.

**Comment by bsunanda** [comment]
LayerRotation is used as an angle and also the name of a rotation matrix using the same rotation angle. These are used in algorithms. Cannot afford to change the name. The value may differ in different version of HGCAL geometry. This is an evolving case and hopefully at some point we shall have only one version.

**Comment by bsunanda** [comment]
@cvuosalo, @ianna, @kpedro88, @srimanob Can you please approve this PR

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
