### PR TITLE
[DQM] Modify DQMGUI upload test to only run in automated environments

### PR DESCRIPTION
**Pull request by nothingface0**
#### PR description:

After @smuzaffar's recommendation, modify `TestDQMGUIUpload` to only run for PRs and IBs, and not for local testing, when the `DQMServices/Demo` package is checked out. The test checks for the `CMSBOT_CI_TESTS` env var, or a `--force` argument, to override the variable.

Also fix the timestamp of the renamed file to include the hour, which was missing before, it will help with debugging.

A `--help` argument to print the script's usage is also added.

See also: #46682

#### PR validation:

Tested on LXPLUS. DQMGUI dev is currently unavailable for full testing.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.

### CODE REVIEW

**Comment by rseidita** [comment]
@cmsbuild please abort

Didn't notice the "DQMGUI dev not available" part

**Comment by smuzaffar** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
