### PR TITLE
Changes to CalibFormats/SiPixelObjects to fix gcc 8 compiler errors

### PR DESCRIPTION
**Pull request by Dr15Jones**
This avoids potential buffer problems with calls to sprintf as well as removed unnecessary try {} catch block.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

the differences look the old known ones

**Pull request merged**
