### PR TITLE
Ignore srp block error - 808_pX

### PR DESCRIPTION
**Pull request by argiro**
Same as #14771 for 808. This will prevent problems with EB-11 such as the ones seen in run 274420

### CODE REVIEW

**Comment by mmusich** [comment]
@argiro I would say this needs a rebase

**Comment by davidlange6** [comment]
yes, it does... @argiro

**Comment by argiro** [comment]
mhh wait something must have gone wrong

S

**Comment by argiro** [comment]
Close this one and rebase

**Pull request closed without merging**
