### PR TITLE
Fill Photon PF ID DNN score properly

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Solves https://github.com/cms-sw/cmssw/issues/42949. 

#### PR validation:
`12434.7` and `12434.0` runs fine. 
photon's pfDNN() now shows meaningful results.

### CODE REVIEW

**Comment by swagata87** [comment]
type bug-fix, egamma

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
