### PR TITLE
Use TFile::GetUUID() for job report GUID in DQMRootOutputModule

### LINKED ISSUE #28534: DQMRootSource and DQMRootOutputModule don't use the same file ID
Since the DQM file type is not using the standard RootFile IO, it doesn't have the `edm::createGlobalIdentifier()` embedded in a `MetaData` tree.
Rather, it uses the method `TFile::GetUUID` to read the file ID out of input files in:
https://github.com/cms-sw/cmssw/blob/81e12a9da6b3864a9d1aac5d433c7147f578fd2a/DQMServices/FwkIO/plugins/DQMRootSource.cc#L641

The DQMRootOutputModule should then correspondingly report the correct UUID from `m_file->GetUUID()` rather than creating an unrelated ID and passing it to the job report:
https://github.com/cms-sw/cmssw/blob/81e12a9da6b3864a9d1aac5d433c7147f578fd2a/DQMServices/FwkIO/plugins/DQMRootOutputModule.cc#L337

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

`DQMRootSource` uses `TFile::GetUUID()` to report the GUID of the file to the framework job report, while `DQMRootOutputModule` uses `edm::createGlobalIdentifier()` but without saving it to the file, leading to inconsistency with file names and GUIDs in the job reports (see #28534).

As the simplest fix this PR proposes to use the `TFile::GetUUID()` also in `DQMRootOutputModule` for the job report.

Fixes #28534. 

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Follow-up to comment https://github.com/cms-sw/cmssw/issues/28534#issuecomment-561786308

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
