### PR TITLE
Remove dependencies in FWCore BuildFiles

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The extra dependencies were shown by the libCheck done by the IBs.
#### PR validation:

Code compiles.

completes makortel/framework#145

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by fwyzard** [comment]
+hlt

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by jfernan2** [comment]
+1

**Comment by francescobrivio** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
