### PR TITLE
give `OnlineLuminosityRecord` info to HLT's `LumiMonitor` plugin [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #39859

#### PR description:

From the description of #39859:

>This PR address the 2nd item in the description of #39756, plus a related comment in https://github.com/cms-sw/cmssw/issues/39756#issuecomment-1282752666.
>
>The `LumiMonitor` DQM plugin, used inside HLT, is updated to read the values of online instantaneous luminosity and mean PU from the so-called 'online-metadata' digis, when the corresponding info from SCAL is not available (i.e. from Run 3 onwards).
>
>To improve clarity, some of the plot labels, transient variables, and configuration parameters are renamed. I changed "scal lumi/PU" to a more generic "online lumi/PU", but of course feel free to suggest better names.
>
>Minor technical improvements (e.g. `const`-ness of class data members) were done in the process.
>
>(In case this is backported to `12_4_X`, it should not warrant a new `ConfDB` parsing, since the new configuration parameter of `LumiMonitor`, i.e. `onlineMetaDataDigis`, already defaults to the intended collection; at the same time, `hltOnlineMetaDataDigis` should in principle be included in the `DQMHistograms` EndPath in the HLT menus.)

cee90096ba579dc5c76937417c29c4aeda385d30 fixes a couple of pixel-related harvesting outputs which depend on the outputs of the `LumiMonitor` plugin; please see https://github.com/cms-sw/cmssw/pull/39859#issuecomment-1296284482 for details.

This is not an exact backport because of 357bb684d: the renaming of the parameter `LumiMonitor.FolderName (-> .folderName)`, done in #39859, is not backported to `12_4_X` in order to avoid extra complications to HLT online operations (see https://github.com/cms-sw/cmssw/pull/39859#discussion_r1005798625).

#### PR validation:

None beyond the validation done for #39859.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39859

Fix for HLT online DQM.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

This now includes the non-update discussed in https://github.com/cms-sw/cmssw/pull/39859#discussion_r1005798625, to avoid the need for changes to the `12_4_X` online HLT menus (the description of this PR has been updated accordingly).

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/pull/39859#issuecomment-1296284482.

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
@cms-sw/dqm-l2

Regarding https://github.com/cms-sw/cmssw/pull/39859#issuecomment-1294737391, can this 12_4_X backport please be tested in playback mode in the online DQM?

**Comment by emanueleusai** [comment]
testing at p5

**Comment by missirol** [comment]
@emanueleusai , clearly the error is not related to this PR.

I can only guess you took it via a `merge-topic`, and this led to including https://github.com/cms-sw/cmssw/pull/39845 in the process.

If it helps, I can rebase this PR on `12_4_10_patch3`.

**Comment by missirol** [comment]
please test

@emanueleusai , I rebased this PR on `12_4_10_patch3`. Could you please retry to test it?

**Comment by missirol** [comment]
+hlt

**Comment by syuvivida** [comment]
@missirol We saw the same errors if testing the same input file from run 361197 with CMSSW_12_5_1 + PR 39597, 39935. Do you happen to know why? 

Begin processing the 1st record. Run 361197, Event 5811668, LumiSection 4 on stream 0 at 03-Nov-2022 10:23:43.689 CET
----- Begin Fatal Exception 03-Nov-2022 10:23:44 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Processing  Event run: 361197 lumi: 4 event: 5811668 stream: 0
   [1] Running path 'l1tEmulatorMonitorPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'valEmtfStage2Digis'
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1TMuon/data/emtf_luts/ph_lut_Run3_2022_data/ph_init_neighbor.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/poison:/cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/src:/cmsnfsdqmdataBegin processing the 1st record. Run 361197, Event 5811668, LumiSection 4 on stream 0 at 03-Nov-2022 10:23:43.689 CET
----- Begin Fatal Exception 03-Nov-2022 10:23:44 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Processing  Event run: 361197 lumi: 4 event: 5811668 stream: 0
   [1] Running path 'l1tEmulatorMonitorPath'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'valEmtfStage2Digis'
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1TMuon/data/emtf_luts/ph_lut_Run3_2022_data/ph_init_neighbor.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/poison:/cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/src:/cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/external/slc7_amd64_gcc10/data:/opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_1/src:/opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_1/external/slc7_amd64_gcc10/data
Current directory is: /home/dqmdevlocal/output
----- End Fatal Exception -------------------------------------------------
03-Nov-2022 10:23:44 CET  Writing DQM Root file: ./upload/DQM_V0001_L1TEMU_R000512692.root
DQMFileSaver::globalEndRun()
03-Nov-2022 10:23:45 CET  Closed file /fff/BU0/ramdisk/run512692/run512692_ls0004_streamDQM_sm-c2a11-43-01.dat/dqmdata/dqm_cmssw/playback_1102_CMSSW_12_5_1_39597_39935/external/slc7_amd64_gcc10/data:/opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_1/src:/opt/offline/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_5_1/external/slc7_amd64_gcc10/data
Current directory is: /home/dqmdevlocal/output
----- End Fatal Exception -------------------------------------------------
03-Nov-2022 10:23:44 CET  Writing DQM Root file: ./upload/DQM_V0001_L1TEMU_R000512692.root
DQMFileSaver::globalEndRun()
03-Nov-2022 10:23:45 CET  Closed file /fff/BU0/ramdisk/run512692/run512692_ls0004_streamDQM_sm-c2a11-43-01.dat

**Comment by missirol** [comment]
I don't know, but I can give you my guess.

The branch of PR-39935 includes PR-39844; if you are merging PR-39935 via merge-topic on top of `12_5_1`, you are effectively also merging PR-39844 in your local build. The issue is that PR-39844 also requires a cms-data update which did not go into `12_5_1`, so you end up with an inconsistent setup (you could try to include this cms-data update in your local area; in general, you could try using `git cms-cherry-pick-pr`, or requiring that PRs that need to be 'manually' merged in the online DQM be based on a CMSSW release, and not an IB).

That said, this DQM issue in 12_5_X appears entirely unrelated to this PR..

**Comment by syuvivida** [comment]
Test at p5 was successful

**Comment by syuvivida** [comment]
+1

**Comment by missirol** [comment]
@syuvivida , thanks for making the test.

Could you please also review the 12_5_X (#39896) and 12_6_X (#39859) of this PR?

**Comment by perrotta** [comment]
+1
- "Almost" verbatim backport of the corresponding PR in the master, see https://github.com/cms-sw/cmssw/pull/39859#discussion_r1005798625: this was evaluated by HLT the safest way to propagate the changed parameters, and DQM approved

**Pull request merged**
