### PR TITLE
Option to remove hwwdqm

### PR DESCRIPTION
**Pull request by davidlange6**
to allow multithreaded prompt reco

### CODE REVIEW

**Comment by deguio** [comment]
ciao david,
I am fine with the proposal of making available a hww-less DQM sequence. however it would be nice to give a chance to #9212 first.

one related question. is there a remote chance that the root version sourced at the T0 differs from the one coming with the release? 
before this fix
https://sft.its.cern.ch/jira/browse/ROOT-7245
we observed several non-reproducible errors like the one we are trying to fix.

thanks,
F.

**Comment by davidlange6** [comment]
> On May 22, 2015, at 12:31 PM, deguio <notifications@github.com> wrote:
> 
> ciao david,
> I am fine with the proposal of making available a hww-less DQM sequence. however it would be nice to give a chance to #9212 first.

Right - (but you should sign it asap). This is a backup solution

> 
> one related question. is there a remote chance that the root version sourced at the T0 differs from the one coming with the release? 
> before this fix
> https://sft.its.cern.ch/jira/browse/ROOT-7245
> we observed several non-reproducible errors like the one we are trying to fix.

no there isn’t. Root comes from the release. we see the same errors from time to time in 75x IB tests in any case.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by deguio** [comment]
+1

**Pull request merged**
