### PR TITLE
Update geometry check in GEMPadDigiProducer

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In response to https://github.com/cms-sw/cmssw/pull/31451#issuecomment-693682969 to address warnings like 

```
%MSG-e GEMPadDigiProducer:  GEMPadDigiProducer:simMuonGEMPadDigis  14-Sep-2020 20:54:58 CEST Run: 1 Event: 1
GE2/1 geometry (8 partition) appears corrupted
%MSG
```

#### PR validation:

Tested with WF 30634.0 (step1 and step2) introduced in #31451.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@silviodonato Can this be merged?

**Comment by silviodonato** [comment]
do you have any comments @rekovic ?

**Comment by kpedro88** [comment]
@silviodonato @qliphy please just merge this

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
