### PR TITLE
Update `testTrackAnalyzers` 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to update the `catch2` unit test `testTrackAnalyzers` such that it is more modular and can therefore test all the plugins in `Alignment/OfflineValidation`.
In order for this to succeed I, had to rename a couple of cfi files existing in the `Alignment/OfflineValidation/python/` directory, because they were conflicting with the ones auto-generated by the corresponding plugin's `fillDescriptions` method.

#### PR validation:

`scram b runtests_testTrackAnalysis` runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
