### PR TITLE
[10_2_X] Backport of O2O test setup modified to work across boost version changes 

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See description at https://github.com/cms-sw/cmssw/pull/35440 and https://github.com/cms-sw/cmssw/pull/35472

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/35440 and https://github.com/cms-sw/cmssw/pull/35472

resolves https://github.com/cms-sw/cmssw/issues/28812

### CODE REVIEW

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/35440

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/35472

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Unit tests pass now:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7b3f1c/19350/unitTests/success.html

Is there anything else to be done here @ggovi ?

**Comment by ggovi** [comment]
@tvami That's just it, thanks!

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1
Duplicate Dictionaries Warning already in IB

**Pull request merged**
