### PR TITLE
New GTs for 75X: Hcal MC response corrections and other fixes

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes
## Run1 simulation
- Ideal: [75X_mcRun1_design_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_design_v5) : As [75X_mcRun1_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_design_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun1_design_v4/75X_mcRun1_design_v5):
  - adding BTag conditions as GRBForest payloads;  
  - Hcal response corrections from Data/MC comparison.
- Realistic: [75X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_realistic_v5): As [75X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun1_realistic_v4/75X_mcRun1_realistic_v5):
  - adding BTag conditions as GRBForest payloads;
  - Hcal response corrections from Data/MC comparison.
- Heavy Ion: [75X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_HeavyIon_v5): As [75X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun1_HeavyIon_v4/75X_mcRun1_HeavyIon_v5):
  - adding BTag conditions as GRBForest payloads;
  - Hcal response corrections from Data/MC comparison;
  - Adding new Centrality table in `HeavyIonRcd` with label `HFtowersHydjetDrum5`.
- Proton Lead: [75X_mcRun1_pA_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_pA_v5): As [75X_mcRun1_pA_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun1_pA_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun1_pA_v4/75X_mcRun1_pA_v5):
  - adding BTag conditions as GRBForest payloads;
  - Hcal response corrections from Data/MC comparison.
## Run1 data
- Offline: [75X_dataRun1_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_v5): As [75X_dataRun1_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_v4]) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_v5/75X_dataRun1_v4):
  - adding BTag conditions as GRBForest payloads;
  - adding HF tower description for HeavyIons as new label in HevayIonRcd;
  - updating HCAL channel quality: mark 18 HCAL channels of a particular HPD as bad (0x8002) in the run range 253937 - 255294 due to a mistakenly set low bias voltage.
  - taxonomy change for Muon APE tags 
- HLT: [75X_dataRun1_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v3): As [75X_dataRun1_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_HLT_frozen_v2/75X_dataRun1_HLT_frozen_v3):
  - taxonomy change for Muon APE tags;
  - taxonomy change for SiStrip back-plane corrections in deconvolution mode;
  - new snapshot time: 2015-09-21 07:47:14.
## Run2 simulation
- Ideal: [75X_mcRun2_design_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_design_v5): As [75X_mcRun2_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_design_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_design_v5/75X_mcRun2_design_v4):
  - adding BTag conditions as GRBForest payloads;
  - new 25ns JEC including PUPPI;
  - Hcal response corrections from Data/MC comparison;
  - Hcal ZS thresholds to simulate HF zero suppresion settings;
  - New 25ns JECs for HLT;
  - New L1 menu for stage1 (v5).
- Startup: [75X_mcRun2_startup_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_startup_v5): As [75X_mcRun2_startup_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_startup_v4/75X_mcRun2_startup_v2):
  - adding BTag conditions as GRBForest payloads;
  - new Pixel dead channel map (from Run2015C);
  - new 50ns JEC including PUPPI;
  - Hcal response corrections from Data/MC comparison;
  - Hcal ZS thresholds to simulate HF zero suppresion settings.
- Asymptotic: [75X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_asymptotic_v6): As [75X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_asymptotic_v5) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_asymptotic_v5/75X_mcRun2_asymptotic_v6):
  - adding BTag conditions as GRBForest payloads;
  - new Pixel dead channel map (from Run2015C);
  - new 50ns JEC including PUPPI;
  - Hcal response corrections from Data/MC comparison;
  - Hcal ZS thresholds to simulate HF zero suppresion settings;
  - New 25ns JECs for HLT;
  - New L1 menu for stage1 (v5).
- Heavy Ion: [75X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_HeavyIon_v5): As [75X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_mcRun2_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_mcRun2_HeavyIon_v4/75X_mcRun2_HeavyIon_v5):
  - adding BTag conditions as GRBForest payloads;
  - new Pixel dead channel map (from Run2015C);
  - new 25ns JEC including PUPPI;
  - Hcal response corrections from Data/MC comparison;
  - Hcal ZS thresholds to simulate HF zero suppresion settings;
  - New 25ns JECs for HLT;
  - New L1 menu for stage1 (v5);
  - Adding new Centrality table in `HeavyIonRcd` with label `HFtowersHydjetDrum5`.
## Run2 data
- Offline: [75X_dataRun2_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_v6): As [75X_dataRun2_v5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_v5) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_v5/75X_dataRun2_v6):
  - adding BTag conditions as GRBForest payloads;
  - adding new Centrality Table for HF tower description for HeavyIons as new label in HevayIonRcd; 
  - updating HCAL channel quality: mark 18 HCAL channels of a particular HPD as bad (0x8002) in the run range 253937 - 255294 due to a mistakenly set low bias voltage;
  - updating JEC for data (25ns-50ns transitions are handled via IOV) including new labels for PUPPI;
  - taxonomy change for Muon APE tags.
- HLT: [75X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HLT_frozen_v3): As [75X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_HLT_frozen_v2/75X_dataRun2_HLT_frozen_v3):
  - taxonomy change for Muon APE tags; 
  - taxonomy change for SiStrip back plane corrections in deconvolution mode;
  - new snapshot time: 2015-09-21 07:47:14.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
@Martin-Grunewald seems to fail due to mismatch with the HLT menu (we have put the version V5 L1 Stage1 menu in the MC GTs as requested)

**Comment by Martin-Grunewald** [comment]
@mmusich
Great, thanks! Indeed we now need to switch the relval HLT menus as well. I'll do so!
(BTW, what is the status for 76X?)

**Comment by mmusich** [comment]
@Martin-Grunewald errr... as soon as #10353 is merged we will have a solid base to build the new version....

**Comment by Martin-Grunewald** [comment]
@mmusich 
75X: please see #11391

**Comment by mmusich** [comment]
@Martin-Grunewald thanks!

**Comment by diguida** [comment]
@Martin-Grunewald @mmusich 
IIRC I have a "minimal" set of GT in 76X including all changes but HCAL geometry... If so, you can use it for testing in a private branch. Then, when #10353 is included, you can just rebase and add the missing fixes in the menu.

**Comment by mmusich** [comment]
superseded by #11391

**Comment by diguida** [comment]
-1
superseded by #11391

**Comment by mmusich** [comment]
since this needs corresponding changes to the HLT menu, I am going to close it.

**Pull request closed without merging**
