### PR TITLE
Replace has_key with in for dictionaries

### PR DESCRIPTION
**Pull request by ericvaandering**
Has been available since 2.2 and will be removed in python 3. http://legacy.python.org/dev/peps/pep-0290/#testing-dictionary-membership 

Generated with the automated tool python futurize.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12004	50ca38b
- changes are as described
- jenkins tests pass (ignoring known unit test failures); comparisons with the baseline show no differences

**Comment by fwyzard** [comment]
+1

**Pull request merged**
