### PR TITLE
Restoring 2023 RelVal Inputs

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

In PR https://github.com/cms-sw/cmssw/pull/46793 I had the brilliant idea of removing 2023 inputs dataset. Of course this was a silly mistake. Restoring them here.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test workflows 12634.0, 12634.21, 12634.99

**Comment by AdrianoDee** [comment]
@iarspider

**Comment by AdrianoDee** [comment]
test parameters:
- relval_opts = -w upgrade
- relvals = 12634.0, 12634.21, 12634.99

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
