### PR TITLE
optimization of SiStip RecHits Validation

### PR DESCRIPTION
**Pull request by ngrenz**
Optimization by deleting of unused variables, set of variables only one time and restructure of if-statements.

In addition some suggestion from the pull request #10586 (with same name and
content as this pull request) were implemented.
The suggestion, with major reconstruction of the code like rewritting the code for the use of a enum will be made in a later pull request.

The outputs are supposed to be unchanged.
Any comments and suggestions are welcome.

### CODE REVIEW

**Comment by ngrenz** [comment]
@boudoul FYI

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
