### PR TITLE
Convert all remaining RECO & MiniAOD modules that are executed to threaded FW (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11140

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray please compile  and do basic checks locally  first; restart jenkins tests only after a particular issue is resolved locally.

**Comment by lgray** [comment]
@slava77 I did compile and do basic checks locally. This is a CLANG
compilation error, and not from my PR.

**Comment by slava77** [comment]
with a closer look, regarding https://github.com/cms-sw/cmssw/pull/10671#issuecomment-129848121, the calls to jenkins tests seem reasonable

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

also das.

**Comment by lgray** [comment]
waiting on #10595

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10671 b87ccd09351a6c3d198528ee58f948599fea6e01

Converting all remaining Mini-AOD modules to support multi-threading. There should be no changes in monitored quantities. #10620 is the 76X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10671/7421/summary.html) against baseline CMSSW_7_5_X_2015-08-17-2300 show no significant differences, as expected. #10620 has additional information about the multi-threading performance improvements of this PR.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@monttj @mulhearn please resign this PR. Thanks!

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
@mulhearn  please sign, thanks.

**Comment by cvuosalo** [comment]
+1

For #10671 caa5adc16c34ff38d7ce80f685eaae5925d9ce08

Convert remaining legacy modules in RECO to support multi-threading. There should be no change in monitored quantities. #11140 is the 76X version of this PR, and it has already been merged.

Jenkins tests against baseline CMSSW_7_5_X_2015-09-10-2300 show no significant differences, as expected. See #10806 for information about the performance of this PR.

**Comment by lgray** [comment]
@mulhearn please sign. thanks!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@cmsbuild please test
@slava77 @monttj had to rebase to remove conflict with l1 trigger changes of a similar nature.

**Comment by mulhearn** [comment]
+1

**Comment by lgray** [comment]
@mulhearn this PR no longer needs L1 signing (the changes were done in your group's PR so I removed the commit here)

**Comment by lgray** [comment]
@mulhearn Thanks for the prompt response in any case. :-)

**Comment by cvuosalo** [comment]
+1

For #10671 13095bd804acc2865822d078136975eb191ac672

This PR was already fully approved, but then a rebase was necessary. New Jenkins tests against baseline CMSSW_7_5_X_2015-09-15-2300 show no significant differences.

**Comment by lgray** [comment]
@monttj Please resign. Thanks!

**Comment by slava77** [comment]
@monttj 
please check this PR
Thank you.

**Comment by lgray** [comment]
@monttj please check and sign this PR. Thanks!

**Comment by lgray** [comment]
@davidlange6 This one too whenever you feel like it (it's in 74X/76X for a while now)

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
Would be nice if this one can be merged soon.

**Comment by lgray** [comment]
@davidlange6 possible to merge this one? It is running fine in 760pre5, unless you are waiting for more validation to come through.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
