### PR TITLE
Remove edmConvertToStreamModule.py, it's no longer needed

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Remove edmConvertToStreamModule.py, it's no longer needed. This utility would convert legacy type modules to ```stream``` type modules. It was written such that it was only useful for modules in the repository. At this point in time, all modules in the repository have been converted or deleted. Therefore, this is no longer needed or useful.

#### PR validation:

None. This only deletes unused code.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by rappoccio** [comment]
+1

**Pull request merged**
