### PR TITLE
Remove Legacy Files

### PR DESCRIPTION
**Pull request by ianna**
* GeomDetUnit is a type alias of GeomDet and the header file of the first includes the latter
* Remove other include files which define error since the classes themselves have been moved
* Remove double includes

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19368	c5b105a
- technical. Despite a large set of files changed, I do not expect significant interference with other still open PRs, due to changes only in the header include part
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
@ianna, you need rebase - there is one conflict.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19368	26686d7
- changes since last signoff by reco: rebase after RecoLocalTracker/Phase2ITPixelClusterizer/test/Phase2ITPixelClustersValidation.cc  removal, no other changes
- jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
