### PR TITLE
Phase2-hgx268 Extending scintillator DetId to contain tile type c/m and SiPM type

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extending scintillator DetId to contain tile type c/m and SiPM type

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
@kpedro88 do you have any comments?

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
