### PR TITLE
fixes needd to run RelMon under python3

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Pull requests comparion jobs for PY3 IBs do not run (https://github.com/cms-sw/cmsdist/pull/5537#issuecomment-584898831 ) as RelMon scripts are not python3 compatible. 

PyROOT with python3 does not like `from ROOT import *` ( https://github.com/root-project/root/blob/master/bindings/pyroot/ROOT.py#L632-L635) so explicitly import things we use from ROOT. 

#### PR validation:

ReRun pr comparison job locally under PY3 IBs.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1264

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , can we get this in? It fixes PR comparison for PY3 IBs.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
