### PR TITLE
[DQM-RECONSTRUCTION] Changes suggested by new llvm18 clang-format

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR applies clang-format changes suggested by new llvm18 ( see https://github.com/cms-sw/cmssw/issues/45870 )

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
