### PR TITLE
Add debugging capabilities to the CachingAllocator

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Extend the alpaka `CachingAllocator` to optionally fill with a configurable value all memory blocks that are: allocated, cached for re-use, re-used, or deallocated.
    
Extend the AlpakaService to configure the host and device `CachingAllocator`s.

Add a simple test to load the `AlpakaService`.

---

To fill the NVIDIA GPU memory before every allocation or reuse with `0xA5`, you can now use
```python
process.AlpakaServiceCudaAsync.deviceAllocator.fillAllocations = True
```

To fill the NVIDIA GPU memory before every deallocation or caching with `0x5A`, you can now use
```python
process.AlpakaServiceCudaAsync.deviceAllocator.fillDeallocations = True
```

To use different values and combination for allocations, deallocation, caching, and reuse, the full options are
```python
process.AlpakaServiceCudaAsync.deviceAllocator.fillAllocations = True,
process.AlpakaServiceCudaAsync.deviceAllocator.fillAllocationValue = 0xA5,
process.AlpakaServiceCudaAsync.deviceAllocator.fillReallocations = True,
process.AlpakaServiceCudaAsync.deviceAllocator.fillReallocationValue = 0x69,
process.AlpakaServiceCudaAsync.deviceAllocator.fillDeallocations = True,
process.AlpakaServiceCudaAsync.deviceAllocator.fillDeallocationValue = 0x5A,
process.AlpakaServiceCudaAsync.deviceAllocator.fillCaches = True,
process.AlpakaServiceCudaAsync.deviceAllocator.fillCacheValue = 0x96
```

To do the same for the pinned host memory used in the GPU transfers, `process.AlpakaServiceCudaAsync.hostAllocator` accepts the same options.

To do the same for AMD GPUs, replace `AlpakaServiceCudaAsync` with `AlpakaServiceROCmAsync`.

To do the same for the CPU memory used by the alpaka modules running on the host, replace `AlpakaServiceCudaAsync` with `AlpakaServiceSerialSync`.

#### PR validation:

The new unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

Self-signed because @makortel is still away. I'm happy to address any comments and accept any suggestions to improve the system when he comes back.

**Comment by mmusich** [comment]
ignore tests-rejected with external-failure

**Comment by rappoccio** [comment]
merge

**Pull request merged**
