### PR TITLE
MTD geometry, digitization, reconstruction and validation: technical cleaning of code

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses a number of technical issues related to MTD code, without implying any effect on its output. In detail:

- Move ```EventSetup``` use to ```ESGetToken``` (~~with the exception of digitization, already addressed by @makortel in #31697~~)
- Remove the ```RecHitTools``` class, now obsolete and unused
- Remove the ```RecoMTD/Navigation``` package, unused and not needed after the developments in #33272 (no point in maintaining useless code)
- clang-tidy cleaning of code

#### PR validation:

code compiles and run, geometry unit tests look ok, and test wf 34634.0 do not show differences in its DQM output

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
The only detected warnings in test are https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-925ef4/14101/llvm-analysis/esrget-sa.txt related to digitization, left out of this cleaning on purpose.

**Comment by perrotta** [comment]
> The only detected warnings in test are https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-925ef4/14101/llvm-analysis/esrget-sa.txt related to digitization, left out of this cleaning on purpose.

#31697, still supposed to be a "draft" seems unattended since some while (can you confirm @makortel?): wouldn't it be more advisable to implement also those updates here?
In any case that PR has already several conflicts to be fixed, a few more wouldn't probably hurt too much...

**Comment by makortel** [comment]
> > The only detected warnings in test are https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-925ef4/14101/llvm-analysis/esrget-sa.txt related to digitization, left out of this cleaning on purpose.
> 
> #31697, still supposed to be a "draft" seems unattended since some while (can you confirm @makortel?): wouldn't it be more advisable to implement also those updates here?
> In any case that PR has already several conflicts to be fixed, a few more wouldn't probably hurt too much...

I'll try to find time in next week or two to finish #31697. To me either way is fine (a few conflicts more indeed won't hurt much more).

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@makortel @perrotta if you prefer, I can embed Matti's update in my PR to complete the MTD migration

**Comment by perrotta** [comment]
> @makortel @perrotta if you prefer, I can embed Matti's update in my PR to complete the MTD migration

Please complete the migration here (Matti already wrote that "either way is fine" to him). Thank you!

**Comment by fabiocos** [comment]
This should complete the cleaning for MTD code

**Comment by fabiocos** [comment]
please test

**Comment by makortel** [comment]
> > @makortel @perrotta if you prefer, I can embed Matti's update in my PR to complete the MTD migration
> 
> Please complete the migration here (Matti already wrote that "either way is fine" to him). Thank you!

Just to confirm, that was indeed fine for me. Thanks!

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
I am adjusting things in order to make the combined integration of this PR and #33340 simple, minimizing possible
 conflicts

**Comment by fabiocos** [comment]
now this PR and #33340 could be integrated independently, the order should not matter any more

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Code cleaning implemented as planned
- Jenkins tests pass with no differences in outputs

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Technical cleaning, no change is expected.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
