### PR TITLE
update of RAWAODSIM event content

### PR DESCRIPTION
**Pull request by gennai**
RAWMINIAODSIM related configuration will require more work as apparently it does not yet save all the collections we want.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by gennai** [comment]
@franzoni, @mdhildreth  can you please review it and eventually sign? Thanks.

**Comment by gennai** [comment]
@franzoni, @mdhildreth I know everybody is busy, this is becoming a bit ridiculous :-) ... can you please review it and eventually sign? Thanks.

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
