### PR TITLE
GT Updates with Pixel Local Reco conditions for V2 MC

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## Upgrade 
 
   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v3) as [94X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v3/94X_upgrade2018cosmics_realistic_deco_v1): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v4) as [94X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v4/94X_upgrade2018_design_IdealBS_v2): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v4) as [94X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v4/94X_upgrade2018_realistic_v2): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

## 2017_MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v3) as [94X_mc2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v3/94X_mc2017cosmics_realistic_peak_v1): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v3) as [94X_mc2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v3/94X_mc2017cosmics_realistic_deco_v1): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v4) as [94X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v4/94X_mc2017_design_IdealBS_v2): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v4) as [94X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v4/94X_mc2017_realistic_v2): 
      * update of pixel local reco conditions for V2 MC : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3313.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
Attn. @boudoul @tvami @veszpv

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
