### PR TITLE
Add GEM geometry v7 and v7_10deg version to gemGeometryCustoms.py

### PR DESCRIPTION
**Pull request by geonmo**
1. "gemGeometryCustoms" script is related to changing geometry xml files.
   - On this PR, geometry GE21 v7 and v7_10deg version is added.
2. To fix GEMSpec's strip information is required for v7_10deg
   - Number of strips : 384->192

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by geonmo** [comment]
@ianna Could you check this PR?

**Comment by ianna** [comment]
+1

**Comment by geonmo** [comment]
@davidlange6 Hello! Could you check and merge this PR to 76X_IB?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
