### PR TITLE
[81X] update phase-I geometry in all autoCond keys

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v13) as [81X_upgrade2017_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v13/81X_upgrade2017_realistic_v12): 
  - updated version of geometry tags (`81YV7`) for phase-I; see [AlCa HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2628.html)
- **PhaseI design scenario** : [81X_upgrade2017_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v11) as [81X_upgrade2017_design_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v11/81X_upgrade2017_design_v10): 
  - updated version of geometry tags (`81YV7`) for phase-I; see [AlCa HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2628.html)
- **PhaseI HcalDev scenario** : [81X_upgrade2017_HCALdev_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_v2) as [81X_upgrade2017_HCALdev_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_HCALdev_v2/81X_upgrade2017_HCALdev_v1): 
  - updated version of geometry tags (`81YV8`) for phase-I; see [AlCa HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2627.html)

### CODE REVIEW

**Comment by mmusich** [comment]
@ianna @kpedro88

**Comment by mmusich** [comment]
please test

**Comment by kpedro88** [comment]
@ianna should the new geometry tag for HCAL 2017dev be accessed just with `DB:Extended`, or is there a different label to use?

**Comment by mmusich** [comment]
@kpedro88. It should be accessed via `DB:Extended`

**Comment by ianna** [comment]
@kpedro88 - confirm, it is a default geometry in this GT queue (e.g. DB:Extended)

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@ianna what exactly are we expecting to be changed between the two version of the geometry?
Changes in phaseI simulation are all over the place. Are pixel changed as well?

**Comment by mmusich** [comment]
I am talking about for example:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-19-2300+15924/15982/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/

**Comment by slava77** [comment]
On 9/21/16 12:52 AM, Marco Musich wrote:
> I am talking about for example:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-19-2300+15924/15982/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/
> 

wouldn't a sequence of random numbers change eventually if more or less
any part of the geometry changes?
And once it changes, all observables will lose correlation between a
baseline and a changed geometry.

**Comment by mmusich** [comment]
@slava77 that's what I suspected, thanks. 
Then, what is the correct procedure to limit the changes to physical ones? Something to get empirical answer to https://github.com/cms-sw/cmssw/pull/15889#issuecomment-248580006

**Comment by slava77** [comment]
On 9/21/16 5:34 AM, Marco Musich wrote:
> @slava77 <https://github.com/slava77> that's what I suspected, thanks.
> Then, what is the correct procedure to limit the changes to physical
> ones? Something to get empirical answer to #15889 (comment)
> <https://github.com/cms-sw/cmssw/pull/15889#issuecomment-248580006>

For the actual diffs in geometry, I'd be curious to know as well.
Especially if there is a tool to visualize this in some way.
(not sure if payload dumps can help)

**Comment by ianna** [comment]
@mmusich - no, it's only Hcal. Pixel changes should come on top of these, so the differences better be understood.

@kpedro88 - FYI

**Comment by ianna** [comment]
@slava77 - comparison results from running with this PR should be identical to the ones you've observed in #15889 (if there are no additional differences between eras)

I can produce some comparison plots with validation script: xml vs db

**Comment by slava77** [comment]
@ianna 
Changes in comparisons should be different from what is in #15889
due to additional changes in reco settings applied only in #15889

as an example, caloJets here:
all_oldvsnew_ttbar13tev2017wf10024p0c_recocalojets_ak4calojets__reco_obj_eta

and caloJets in #15889 
all_oldvsnew_ttbar13tev2017wf10024p0c_recocalojets_ak4calojets__reco_obj_eta

If all changes from this PR are related to HCAL DB geometry and related payloads setup, then it seems more reasonable to combine it with #15889 in one PR.

**Comment by kpedro88** [comment]
@slava77 The HCAL geometry changes should only be in `81VY8`, which is only used in the HCALdev GTs. Those GTs are only used in #15889, so the changes could not show up in a comparison here.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
