### PR TITLE
Remove `DQMReferenceHistogramRootFileRcd` from all GTs

### LINKED ISSUE #40: Remove `DQMReferenceHistogramRootFileRcd` from GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

DQM confirmed that the tags corresponding to the `DQMReferenceHistogramRootFileRcd` record are not used anymore. 
Removal of the consumption of the tag has happened in cms-sw/cmssw#35491

Now I've removed this tag from the queues, and created new GTs without them as discussed in the HN [1]. Here are the diffs wrt to the previous tags [2]

[1] 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4483.html

[2]
Diff OldGT-NewGT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_design_v4/121X_mcRun1_design_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_realistic_v4/121X_mcRun1_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_HeavyIon_v5/121X_mcRun1_HeavyIon_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_startup_v4/121X_mcRun2_startup_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_l1stage1_v4/121X_mcRun2_asymptotic_l1stage1_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_design_v4/121X_mcRun2_design_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_preVFP_v4/121X_mcRun2_asymptotic_preVFP_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_v4/121X_mcRun2_asymptotic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2cosmics_asymptotic_deco_v4/121X_mcRun2cosmics_asymptotic_deco_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_HeavyIon_v4/121X_mcRun2_HeavyIon_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_pA_v4/121X_mcRun2_pA_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_v4/121X_dataRun2_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HEfail_v4/121X_dataRun2_HEfail_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_relval_v4/121X_dataRun2_relval_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_PromptLike_HI_v4/121X_dataRun2_PromptLike_HI_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v4/121X_dataRun3_HLT_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HLT_relval_v4/121X_dataRun2_HLT_relval_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v4/121X_dataRun3_Express_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v4/121X_dataRun3_Prompt_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_v4/121X_dataRun3_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_design_v4/121X_mc2017_design_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_realistic_v4/121X_mc2017_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_deco_v4/121X_mc2017cosmics_realistic_deco_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_peak_v4/121X_mc2017cosmics_realistic_peak_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_design_v4/121X_upgrade2018_design_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_v4/121X_upgrade2018_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_RD_v4/121X_upgrade2018_realistic_RD_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HI_v4/121X_upgrade2018_realistic_HI_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HEfail_v4/121X_upgrade2018_realistic_HEfail_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_deco_v6/121X_upgrade2018cosmics_realistic_deco_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_peak_v4/121X_upgrade2018cosmics_realistic_peak_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v8/121X_mcRun3_2021_design_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v9/121X_mcRun3_2021_realistic_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v9/121X_mcRun3_2021cosmics_realistic_deco_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v9/121X_mcRun3_2021_realistic_HI_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v8/121X_mcRun3_2023_realistic_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v8/121X_mcRun3_2024_realistic_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun4_realistic_v4/121X_mcRun4_realistic_v5

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport is needed

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/40

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 136.897,140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Differences are only in the MsgLogger, anyway all clean results, as expected!

**Comment by francescobrivio** [comment]
@tvami 
 - `120X_mc2017_realistic_forppRef5TeV_v2` was not changed, please remove it from the list of the diffs
 - There are two cases (`121X_dataRun3_HLT_v*` and `121X_dataRun2_HLT_relval_v*`) where you created new GTs but they are identical to the old ones because the `DQMReferenceHistogramRootFileRcd` record was not present in the orginal GT. Is this due to an automatic script? Or is it done on purpose?

**Comment by tvami** [comment]
> * `120X_mc2017_realistic_forppRef5TeV_v2` was not changed, please remove it from the list of the diffs

Done. Also I propose to deal with this for good with an autoCond modifier. I can deal with this in a follow-up PR

> * There are two cases (`121X_dataRun3_HLT_v*` and `121X_dataRun2_HLT_relval_v*`) where you created new GTs but they are identical to the old ones because the `DQMReferenceHistogramRootFileRcd` record was not present in the orginal GT. Is this due to an automatic script? Or is it done on purpose?

Right, this is due to my semi-automatized process, and indeed I noticed it as well, but only after the GT was created, so I thought it makes sense to include the new GT. It doesnt make a difference but it's good for bookkeeping.

**Comment by francescobrivio** [comment]
+alca

 - see comment https://github.com/cms-sw/cmssw/pull/35533#issuecomment-934348022

**Comment by perrotta** [comment]
+1
- GT update/cleaning

**Pull request merged**
