### PR TITLE
Remove unused headers for phys & misc packages

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

This is the last batch of unused header removal.

Following the issue #31505, the following headers are unused in several package:
 - PhysicsTools/FWLite/interface/WSelectorFast.h
 - PhysicsTools/MVAComputer/interface/MVAModuleHelper.h
 - PhysicsTools/PatExamples/interface/WPlusJetsEventSelector.h
 - PhysicsTools/PatUtils/interface/JetSelector.h
 - PhysicsTools/PatUtils/interface/JetSelector.icc
 - PhysicsTools/PatUtils/interface/PatSelectorByFlags.h
 - PhysicsTools/PatUtils/interface/RefHelper.h
 - PhysicsTools/SelectorUtils/interface/Variables.h
 - PhysicsTools/UtilAlgos/interface/DummyMatchSelector.h
 - PhysicsTools/UtilAlgos/interface/EventSelector.h
 - PhysicsTools/UtilAlgos/interface/MCMatchSelector.h
 - PhysicsTools/UtilAlgos/interface/NtpProducer.h
 - PhysicsTools/UtilAlgos/interface/SelectedOutputCollectionTrait.h
 - PhysicsTools/UtilAlgos/interface/SelectionAdderTrait.h
 - PhysicsTools/UtilAlgos/interface/StoreContainerTrait.h
 - PhysicsTools/UtilAlgos/interface/TwoObjectCalculator.h
 - PhysicsTools/Utilities/interface/GammaPropagator.h
 - PhysicsTools/Utilities/interface/GammaZInterference.h
 - PhysicsTools/Utilities/interface/Number.h
 - PhysicsTools/Utilities/interface/ZLineShape.h
 - TopQuarkAnalysis/TopTools/interface/TopologyWorker.h
 - TrackingTools/AnalyticalJacobians/interface/CurvilinearJacobian.h
 - TrackingTools/GsfTools/interface/GaussianSumUtilities.h
 - TrackingTools/GsfTools/interface/GaussianSumUtilities.icc
 - TrackingTools/PatternTools/interface/MediumProperties.h
 - TrackingTools/Records/interface/Records.h

#### PR validation:

Code compiles. Run local limited runTheMatrix.py tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport forseen.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jpata** [comment]
There is some overlap with the PR https://github.com/cms-sw/cmssw/pull/35105

EventFilter/DTRawToDigi/interface/DTROS25Data.h
EventFilter/ESRawToDigi/interface/ESCrcKchipFast.h
JetMETCorrections/InterpolationTables/interface/BoxNDScanner.h
JetMETCorrections/InterpolationTables/interface/MultivariateFunctorScanner.h
JetMETCorrections/InterpolationTables/interface/rescanArray.h
JetMETCorrections/Type1MET/interface/CorrectedMETProducerT.h
(list may be incomplete, please verify yourself)

Can you please remove from this PR any file already touched by 35105?

**Comment by yuanchao** [comment]
> There is some overlap with the PR #35105
> 
> EventFilter/DTRawToDigi/interface/DTROS25Data.h
> EventFilter/ESRawToDigi/interface/ESCrcKchipFast.h
> JetMETCorrections/InterpolationTables/interface/BoxNDScanner.h
> JetMETCorrections/InterpolationTables/interface/MultivariateFunctorScanner.h
> JetMETCorrections/InterpolationTables/interface/rescanArray.h
> JetMETCorrections/Type1MET/interface/CorrectedMETProducerT.h
> (list may be incomplete, please verify yourself)
> 
> Can you please remove from this PR any file already touched by 35105?

Ouch. I thought I've removed them. Fixing

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
Can you please update the list of removed files in the PR description following https://github.com/cms-sw/cmssw/pull/35252#issuecomment-918281582? Thanks!

**Comment by yuanchao** [comment]
> Can you please update the list of removed files in the PR description following [#35252 (comment)](https://github.com/cms-sw/cmssw/pull/35252#issuecomment-918281582)? Thanks!
It's now updated.

**Comment by jpata** [comment]
I checked the git history of all headers, and did a quick google search for each for possible non-cmssw use / references in documentation. To me, all look like they can be removed, as they are unused in cmssw, in some cases duplicates, and basically untouched since the git migration 8 years ago.

For example, https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/TrackingTools/AnalyticalJacobians/interface/CurvilinearJacobian.h looks like an outdated version of https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/TrackingTools/AnalyticalJacobians/interface/AnalyticalCurvilinearJacobian.h.

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/PhysicsTools/UtilAlgos/interface/MCMatchSelector.h is an outdated version of https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/CommonTools/UtilAlgos/interface/MCMatchSelector.h.

**Comment by jpata** [comment]
+reconstruction
- for bec9a31
- technical
- checked according to https://github.com/cms-sw/cmssw/pull/35252#issuecomment-920794929
- no reco changes observed

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
