### PR TITLE
[14_1_X] Rename MUODPG nano flatTable producers

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

The PR addresses a (second) issue observed when attempting the cantral production of the MUODPG nano custom flavour:

`Configuration/DataProcessing/test/RunMerge.py` retains, out of collections from `NANOEDMAODoutput`, only the ones whose producer's name is of the form `*Table`.
The MUOPDG nano flavour sequence was adapted accordingly.

A small difference in the event content, too small to affect event-size significantly, is expected.

#### PR validation:

Tested using dedicated `runTheMatrix.py` workflows.
Also, in 14_0_X, I tested that running the actual [PdmV production workflow](https://cms-pdmv-prod.web.cern.ch/rereco/api/requests/get_cmsdriver/ReReco-Run2024E-Muon1-ZMu_PromptMUODPGNano-00001), followed by `Configuration/DataProcessing/test/RunMerge.py`, produces a properly-filled ntuple.

#### PR backport:

This PR is intended to be backported to `CMSSW_14_0_X`

### CODE REVIEW

**Comment by battibass** [comment]
please test

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
very nice @battibass ; I do not expect any issue with this in master, please prepare the backport

**Comment by vlimant** [comment]
please abort

**Comment by vlimant** [comment]
please test

**Comment by battibass** [comment]
> very nice @battibass ; I do not expect any issue with this in master, please prepare the backport

@vlimant thanks a lot for the quick reaction, the backport is in #45334.

In the end I did not keep the _trigger stuff_, do you think this is a problem?

**Comment by vlimant** [comment]
+1
no problem

**Pull request merged**
