### PR TITLE
Cones Unit Test Bugfix

### PR DESCRIPTION
**Pull request by ianna**
* compare volumes to 5 digits

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , I am not sure that we need to make the check with 5 digit only, this test indicate a change which happens very rarely - this time full geometry module was substituted but only G4Cons demonstrates a difference. I would say, that the old approach in this unit test was reasonable.

**Comment by ianna** [comment]
@civanch - the rest of unit test did use some tolerance in comparison.

**Comment by civanch** [comment]
@ianna , may be this is not needed any more?

**Comment by ianna** [comment]
Superseded by https://github.com/cms-sw/cmssw/pull/21959

**Pull request closed without merging**
