### PR TITLE
Implementing dedicated LHE filter for removing events with mttbar below a certain threshold

### PR DESCRIPTION
**Pull request by gsorrentino18**
#### PR description:

This PR implements a new filter, requested by GEN conveners, which removes events with invariant TTbar mass below a given threshold at LHE level. 
An additional cut on the quarks pT is also applied, and both mass and pT thresholds can be customized in the _cfi file.

#### PR validation:

The filter has been tested locally in the CMSSW_12_0_X_2021-04-27-1100 release.

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @gsorrentino18 . Thanks so much for this PR. As we often have say 600 to 1000 and above 1000 or so, you might add min/max? You should also call the file Filter instead of filter to be consistent. When you check pdgid(top)+pdgid(antitop)=0 you could add an else if this is not the case and throw a message as you do before. 
What do you think?

**Comment by gsorrentino18** [comment]
> Hi @gsorrentino18 . Thanks so much for this PR. As we often have say 600 to 1000 and above 1000 or so, you might add min/max? You should also call the file Filter instead of filter to be consistent. When you check pdgid(top)+pdgid(antitop)=0 you could add an else if this is not the case and throw a message as you do before.
> What do you think?

Hi Alexander, thanks for your comments.
About the min/max you mentioned, if I understand well, what are you asking is adding also a maximum threshold for tt invariant mass?
If so, I could do it in two different ways:
1. Adding a max value and setting it to an arbitrary large number (like 999999) when the filter is used for selecting only ttbar events over a minimum threshold.
2. Adding a flag in order to specify if the ttbar mass will have to lie in a given mass window or only above a minimum threshold. This just to avoid putting the arbitrary number as max in the config file. 
Let me know what do you prefer.

**Comment by agrohsje** [comment]
Hi @gsorrentino18 , I have no strong preference. I would probably always use -1 as default and if 
mttmax > -1 and mtt > mttmax  veto 
mttmin > -1 and mtt < mttmin veto  .

**Comment by agrohsje** [comment]
Thanks Giulia. Can you remove the old file from this PR and still add -1 as initial values from min and max ?

**Comment by agrohsje** [comment]
Hi @gsorrentino18. Sorry, misunderstanding. My point was that min and max are not initialized in c++. 
What you had in the python was ok.

**Comment by gsorrentino18** [comment]
> Hi @gsorrentino18. Sorry, misunderstanding. My point was that min and max are not initialized in c++.
> What you had in the python was ok.

Ok. I'll go back to the previous python values and initialize min, max and pTmin as well. Thanks

**Comment by agrohsje** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
