### PR TITLE
Adding harvesting step to NANOAOD workflows

### PR DESCRIPTION
**Pull request by fabozzi**
This adds a harvesting step to NANOAOD workflows.
Hopefully, it should fix the error message of 1325.7 that is reported when testing PRs

### CODE REVIEW

**Comment by fabozzi** [comment]
@arizzi FYI

**Comment by fabozzi** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
@slava77 @smuzaffar this should allow now to have a comparison also for wf 1325.7 in the standard test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
