### PR TITLE
[Bug-fix] Add NANOAOD output to RECONANORUN3 step

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This is a bug fix PR as Nano output is missing from RECONANORUN3 step (both 2022 and 2023).
Thanks for @VinInn to spot this.

#### PR validation:
Try with workflow `140.065`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
To be discussed if backport is needed or not.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test workflow 140.065

**Comment by mmusich** [comment]
@srimanob what about merging first https://github.com/cms-sw/cmssw/pull/42031 and then customizing also the ZB specialized ones?

**Comment by srimanob** [comment]
> @srimanob what about merging first #42031 and then customizing also the ZB specialized ones?

Sure, I just sign it. I will adapt this PR later.

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
test parameters:
- workflows = 140.065,141.008

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

NANOAOD is produced in Run-3 data workflow with the PR.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
