### PR TITLE
Pr93x TTStub Bulider & TTCluster Association from 10_1_x

### PR DESCRIPTION
**Pull request by rekovic**
This is a back-port of https://github.com/cms-sw/cmssw/pull/21765, available from 10_1_0_pre1.

Needed for L1T MC Production in 9_3_X.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport of #21765

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by kpedro88** [comment]
if the cut change is confirmed, it should be done in the latest release cycle as well, for consistency

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
Now the PR is nothing but a backport of #21765

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
Should be ready for merging, as previously signed by @kpedro88 @civanch.

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@civanch as far as I can see the code that you already signed for simulation is unchanged

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
