### PR TITLE
Fix SimHitsCaloHitsDumper

### PR DESCRIPTION
**Pull request by fabiocos**
Restore the functionality of this old analyser to quickly dump Sim Hits and Calo Hits from an event.
Add FastTimer hits to the collections to be considered.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by fabiocos** [comment]
@civanch  This analyser is not running in any test/production wf to my knowledge, so its effect should be null. It may be tested with the cfg provided (just used for MTD simulation development)

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
