### PR TITLE
add jets, report str.

### PR DESCRIPTION
**Pull request by popovvp**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by vanbesien** [comment]
@popovvp

See my comment in #7693:
As far as I can see, now there is only one histogram left with an unreasonably high amount of bins, namely the "hBunchOcc = ibooker.bookProfile(s,s,4000,0,4000, 100,0,1.e10,"");" here:
https://github.com/popovvp/cmssw/blob/750p2/DQM/CastorMonitor/src/CastorDigiMonitor.cc#L84

**Comment by deguio** [comment]
-1
rejecting for now. feel free to commit to the same branch to address @vanbesien comments
thanks,
F.

**Comment by davidlange6** [comment]
closing as its rejected without response for a few weeks

**Pull request closed without merging**
