### PR TITLE
Phase2-hgx226 Correct wafer size for the HGCal V11 version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct wafer size for the v11 version. It is also wrong for v9 and v10. But the corrected size is not added in the old workflows

#### PR validation:

Tested with standard matrix test

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@bsunanda @kpedro88 as far as I can see only scenarios not previously used for production are modified, and this should be acceptable IMO. Are the new xml files provided for private studies and/or reference?

**Comment by bsunanda** [comment]
V11 is the current default for HGCal DPG and we shall improve from that version. So the changes in the V11 wafer size is extremely useful. The changes for v9 and v10 are made in v9c and v10c - they are not in any workflow - but may be one can make specific scenarios for some comparisons for change in version - they will be indeed some private scenarios to my current understanding

**Comment by kpedro88** [comment]
+upgrade
changes isolated to D46 as expected

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
