### PR TITLE
Backport Updates on DQMOffline/ZCounting

### PR DESCRIPTION
**Pull request by davidwalter2**
#### PR description:

The plugin from DQMOffline/ZCounting is currently not working due to issues with the last filter of trigger path. This PR fixes this problem. Additional updates on the functionality are done.

- new implementation of trigger tools using HLTConfigProvider to automatically find last filter of trigger path. This way the filter name has not explicitly specified.
- removing era modifier as they are not needed for current run 3 data taking.
- moving z counting to electrons into a separate plugin. This way the z counting to muons is concise. The plugin for electrons does not function yet but is planned to be updated in the future.

#### PR validation:

cmsDriver.py

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of [PR39119](https://github.com/cms-sw/cmssw/pull/39119).

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by davidwalter2** [comment]
Can we test again?

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39119

**Comment by perrotta** [comment]
+1

**Pull request merged**
