### PR TITLE
Fireworks: Auto detect geometry version from global tag.

### PR DESCRIPTION
**Pull request by alja**
With this PR cmsShow reads global tag from data file, guess geometry version from it and load that geometry if necessary.

### CODE REVIEW

**Comment by alja** [comment]
@smuzaffar @ianna  
-1
This PR depends on on changes in  https://github.com/cms-data/Fireworks-Geometry

**Comment by silviodonato** [comment]
> @smuzaffar @ianna
> -1
> This PR depends on on changes in https://github.com/cms-data/Fireworks-Geometry

I take this as a "please close this PR". If I am wrong, please let me know and I will reopen the PR

**Comment by smuzaffar** [comment]
The data files is too big to put it in github repository. @alja , can you please share the file via your public AFS area? We can copy this file to cmssdt03 server and include it from there.

**Comment by alja** [comment]
@smuzaffar 
I have put updated Fireworks-Geomtery directory here /afs/cern.ch/user/a/amraktad/public/Fireworks-Geometry
Let me know if I can help any further.

**Comment by alja** [comment]
@smuzaffar 
I have run code formatting and committed the change to same branch https://github.com/alja/cmssw/tree/geo-gt, but I will wait to reopen this PR after Fireworks-Geometry update.

**Comment by smuzaffar** [comment]
@lja , we need some changes for the data external to pick extra files, I will do those and will open a PR for data external.

**Comment by smuzaffar** [comment]
test parameters
- pull_requests = cms-data/Fireworks-Geometry#10,ms-sw/cmsdist#5713

**Comment by smuzaffar** [comment]
@alja , please apply the code format changes suggested and start the test by commenting "please test"

**Comment by smuzaffar** [comment]
PR cms-data/Fireworks-Geometry#10,cms-sw/cmsdist#5713 are need to get the new data

**Comment by smuzaffar** [comment]
@alja , you need to apply the code formatting here

**Comment by alja** [comment]
@smuzaffar 
I applied the code formatting and checked it in the same branch, but this changes is not shown here. I wonder if this is because this PR is closed.
Here is the branch for this PR:
https://github.com/alja/cmssw/tree/geo-gt
And here is the formatting commit:
https://github.com/alja/cmssw/commit/28c32210ef67a6b31b5b7730adbf215047da30bc

**Comment by alja** [comment]
@smuzaffar 
Is there  a command to 'refresh' this PR after applying changes on the same branch?

**Comment by smuzaffar** [comment]
You did not apply all changes. It still complains about https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29169/14476/code-format.patch ( see https://github.com/cms-sw/cmssw/pull/29169#issuecomment-607443597 ) . Apply these changes to your branch and PR will be automatically refreshed.

**Comment by alja** [comment]
@smuzaffar Thanks, I can see now cmsbuid comments. I applied the patch.

**Comment by smuzaffar** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
