### PR TITLE
more DT DQM fixes

### PR DESCRIPTION
**Pull request by fcavallo**
really urgent (some histos didn't get filled!)

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
this one can go in the next 74x build. it will fix few histos produced at the online.
no changes observed in the offline comparison

**Comment by fcavallo** [comment]
hi everybody, sorry to bother you. This PR is really urgent: we need it for the online DQM at P5.
Are there conjectures on how long it is going to take to be merged?
thank you!!!

**Comment by danduggan** [comment]
@fcavallo, this PR was manually added on top of the release for online DQM. Any updates for offline DQM (express/prompt) will come with the next release with this PR (once it's been merged).

**Comment by fcavallo** [comment]
Wonderful! I can already see the previously missing plots on the online DQM! Thank you so much, Dan!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
