### PR TITLE
Change of StoN cut in hit selection for SiPixAli in PCL + 0T configs for the same

### PR DESCRIPTION
**Pull request by JanFSchulte**
Changes the StoN cut in the hit selection for SiPix Alignment of pixel large structures in PCL form 18 to 12 to conform with default value used in Alignment group. Also adds configs for running this alignment at 0T, in case this is needed at some point.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@JanFSchulte the new configurations for 0T, i.e.:
   *  `Alignment/CommonAlignmentProducer/python/ALCARECOPromptCalibProdSiPixelAli0T_cff.py`
   *  `Alignment/CommonAlignmentProducer/python/AlcaSiPixelAliHarvester0T_cff.py` 

are not exercised in the production worklfow. Is this what is desired? In the long run we should aim to have the production configuration to adapt to the B-field and change the configuration accordingly.

**Comment by mmusich** [comment]
please test

**Comment by JanFSchulte** [comment]
@mmusich : I have added the 0T configs just to have something in the release in case of emergency. A proper solution in the production configuration is still to be developed

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
