### PR TITLE
Fix for  issue 37970  - address undetermined output of cand DNN in mkFit

### PR DESCRIPTION
**Pull request by leonardogiannini**
#### PR description:

This PR addresses issue https://github.com/cms-sw/cmssw/issues/37970

In the cand level DNN run after MkFit the output is undetermined if the propagation to the beamline is invalid. This happens in 0.1% of cases at most.

This behaviour is flagged and the output set to -1 (i.e. failing the selection).

I also added a check on ndof > 0 (used to divide chi2), which didn't create problems so far.

#### PR validation:

Example of difference in workflow 12434

no PR https://github.com/cms-sw/cmssw/pull/37918    ------     | with PR https://github.com/cms-sw/cmssw/pull/37918    -----    | fixed

  0.951501 the output                                                          |  0.951501 the output                                                          |  0.951501 the output
  0.931231 the output                                                          |  0.931231 the output                                                          |  0.931231 the output
  0.877139 the output                                                          |  0.877139 the output                                                          |  0.877139 the output
  0.557774 the output                                                          |  0.557774 the output                                                          |  0.557774 the output
  0.97176 the output                                                           |  0.97176 the output                                                           |  0.97176 the output
  0.761749 the output                                                          |  -nan the output                                                              |  -1 the output                                                               
  0.485212 the output                                                          |  0.485212 the output                                                          |  0.485212 the output
  -0.888864 the output                                                         |  -0.888864 the output                                                         |  -0.888864 the output
  0.990027 the output                                                          |  0.990027 the output                                                          |  0.990027 the output
  0.769534 the output                                                          |  0.769534 the output                                                          |  0.769534 the output
  0.962413 the output                                                          |  0.962413 the output                                                          |  0.962413 the output

The physics changes in MTV validation are almost zero, as expected.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@leonardogiannini given the bug-fix looks uncontroversial, I've taken the liberty to make a backport at https://github.com/cms-sw/cmssw/pull/38011

**Comment by mmusich** [comment]
type bug-fix

**Comment by jpata** [comment]
+reconstruction
- bugfix for https://github.com/cms-sw/cmssw/issues/37970
- minor physics changes are expected (fixes occasional random values in DNN output)

**Comment by perrotta** [comment]
+1

**Pull request merged**
