### PR TITLE
Run2-gex128 Rearrange 2017 scenarios in view of updates foreseen

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange 2017 scenarios in view of updates foreseen

#### PR validation:

Use the runTheMatrix test workflows as well as cfg'sin test area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please Test

**Comment by cvuosalo** [comment]
You're changing Extended2017 to Extended2017Plan0. Is "Extended2017" not currently used in any code?

**Comment by bsunanda** [comment]
I plan to use the new 2017 scenario there. I consulted with HCAL DPG SW expert about this. The current status is confusing. The defaukt usage is with 2017Plan1. The new 2017 scenario also uses this but with something which can work with dd4hep. As soon as this IB is integrated I shall migrate the versions in HcalCommonData to CMSCommonData. This will be for 2017 as well as 2018.

**Comment by bsunanda** [comment]
All current 2017 applications use the DB version.

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by srimanob** [comment]
Do we need this urgently? My proposal is to discuss first in the SIM meeting?
What is the definition of `Plan0`?

**Comment by civanch** [comment]
@bsunanda , all, would it be more safe not to rename whatever file but create a new one with clear name like "DD4hep" inside? The alternative may be to edit existing file, this from one hand may be risky but reduce necessity to edit downstream files - we may come to situation of expansion of modifications. 

A safe variant may be to preserve old files with different name and edit existing.

**Comment by bsunanda** [comment]
@srimanob Please sign it now

**Comment by bsunanda** [comment]
In a subsequent PR I shall introduce what we discussed in the SIM meeting.

**Comment by srimanob** [comment]
+Upgrade

There will be a follow up PR as discussed in the SIM meeting, https://indico.cern.ch/event/1153217/, on migration Run-2 to DD4hep.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@bsunanda   After this PR gets merged, there are some unit test failures appearing in the IB test, please have a look and fix:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-25-1100/unitTestLogs/CalibTracker/SiStripESProducers#/


----- Begin Fatal Exception 25-Apr-2022 15:12:57 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_4_X_2022-04-25-1100/src/CalibTracker/SiStripESProducers/test/python/SiStripBadAPVListBuilder_byHand_cfg.py
Exception Message:
 unknown python problem occurred.
ModuleNotFoundError: No module named 'Configuration.Geometry.GeometryExtended2017_cff'

**Comment by qliphy** [comment]
https://github.com/cms-sw/cmssw/blob/CMSSW_12_3_X/CalibTracker/SiStripESProducers/test/python/SiStripBadAPVListBuilder_byHand_cfg.py#L117
https://github.com/cms-sw/cmssw/blob/master/CondTools/SiStrip/test/SiStripApvGainFromASCIIFile_cfg.py#L28
https://github.com/cms-sw/cmssw/blob/master/CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader_cfg.py#L177

**Pull request merged**
