### PR TITLE
bugfix on 25ns PU spectra for 2015

### PR DESCRIPTION
**Pull request by mdhildreth**
Use correct lumi spectrum for 25ns running.  Yes, both files are now the same, so there is only one scenario proposed.

### CODE REVIEW

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
@mdhildreth - we should remove one of these at some point not to cause confusion..

**Comment by ktf** [comment]
cmsbuild is definitely getting out of control.. ;)

**Comment by davidlange6** [comment]
seems that cmsbuild needs some more variety…

**Pull request merged**
