### PR TITLE
reminiAOD workflows from 80X input (93X)

### PR DESCRIPTION
**Pull request by fabozzi**
Added two re-miniAOD workflows from 80X input (data and MC)
following implementation of #19304 

The relvals have been tested here:
https://hypernews.cern.ch/HyperNews/CMS/get/relval/7795.html

@slava77

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
