### PR TITLE
Fix build errors due to ROOT6 only code

### PR DESCRIPTION
**Pull request by wmtan**
This PR fixes the build errors in 7_5_ROOT5_X due to automatic merges of ROOT6 specific code from CMSSW_7_5_X.
Please expedite this technical and trivial PR. It should not require L2 signatures.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by wmtan** [comment]
Please merge this PR. The link error above is not caused by this PR, and is not reproducible by me. The build output shows that there was no attempt to build the DQMServices/ClientConfig package, so that there is a link error when building any package dependent on it. That is not a problem due t this PR.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar Is the package DQMServices/ClientConfig missing from this branch?

**Comment by davidlt** [comment]
@Dr15Jones  `DQMServices/ClientConfig` is among ~158 failing packages in ROOT5 IBs. Thus not available in the IB. I guess, `DQMServices/Core` could have triggered `DQMServices/ClientConfig` to be rebuilt, but there were no changes in headers. That is the reason why `DQMServices/ClientConfig` was not checked out and rebuilt. Thus still missing. Speculation.

@smuzaffar I thought that `-A` was suppose to checkout based on build file dependencies?
```
            ‐A    will check all dependencies i.e. header (‐h), python(‐p) and
            BuildFile(‐b)
```
Or does in some different way?

**Comment by davidlange6** [comment]
@Dr15Jones - build dependencies are incomplete when the build fails...

**Pull request merged**
