### PR TITLE
Faster Geant4 tracking in magnetic field

### PR DESCRIPTION
**Pull request by civanch**
This modification include two improvements:
1) new Geant4 stepper G4DormandPrinc475 recommended by the Geant4 team
2) "Smart tracking" option enabled with the threshold 2 MeV: if a charged particle has smaller energy loose parameters of tracking in field are used (mainly affect low-energy e-)

As a result, simulation histories will be different and full validation is required.

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by civanch** [comment]
+1
many différences are expected, because of different sim histories

**Comment by fabiocos** [comment]
This PR is at present meant for parallel tests on top of CMSSW_10_2_0_pre4

**Comment by fabiocos** [comment]
hold

pending ongoing validation on top of CMSSW_10_2_0_pre4

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+1

**Pull request merged**
