### PR TITLE
Removed unused functions in ClusteringTest

### PR DESCRIPTION
**Pull request by Dr15Jones**
The removed functions have not been called since the second commit to the file which occured in 2006.

This fixes a clang warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26009	d677227
- code changes are technical and are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
