### PR TITLE
NANO: rework for Prompt (part2) backport

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of #34695

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
@mariadalfonso please don't care for your evaluation about the failed RelVals-INPUT tests: they are linked to #34633, and not expected to be fixed so soon
Just stick on the other tests and comparisons

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
