### PR TITLE
Making the |eta| cut configurable in QCD bc->e filter

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
This PR is to make the |eta| cut configurable in QCD b/c->electron filter. Currently the |eta| cut is hard-coded in the `.cc` file and it is |eta|<2.5. This is a problem for e/gamma's PF electron ID DNN training targeting eta-extended electrons (in the region 2.5 < |eta| < 3.0) for Run3. The eta-extended electrons were introduced by https://github.com/cms-sw/cmssw/pull/35309 and now we are trying to provide a meaningful PF ID for them. While retraining the PF electron ID for these high eta electrons, we figured out that QCD b/c->e samples are all restricted to |eta|<2.5. We would like to improve it for 12_4 so that the MC samples produced with 12_4 release are more appropriate for our use-case. 

#### PR validation:
I wanted to test by running the following workflows, which looks like the only ones available using b/c->e filter.
`4007.0 QCD_Pt_30_80_BCtoE_8TeV+DIGIPU1+RECOPUDBG`
`4008.0 QCD_Pt_80_170_BCtoE_8TeV+DIGIPU1+RECOPUDBG`
But they did not run due to `FileOpenError`. 

So I tested locally by doing this:
`cmsDriver.py Configuration/Generator/python/egm.py  --fileout file:step1.root --mc --eventcontent GEN --datatier GEN-SIM-RAW --conditions auto:phase1_2021_realistic --beamspot Run3RoundOptics25ns13TeVLowSigmaZ --step GEN,SIM -n 100  --geometry DB:Extended --era Run3 --python_filename bctoe.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring`

where `Configuration/Generator/python/egm.py` is this file: 
https://swmukher.web.cern.ch/swmukher/egm.py

and then `cmsRun bctoe.py` 

It ran fine. 

This PR is not a backport.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by Saptaparna** [comment]
+1 thanks @swagata87

**Comment by smuzaffar** [comment]
@Saptaparna , cmsbot does not recognize `+1 <and some text>` :-) so if you want to sign it then please just use `+1` on the first line of comment and rest of the text can go in next line

**Comment by qliphy** [comment]
+1
Signed by Generator.

**Pull request merged**
