### PR TITLE
Update AJJGenJetFilter.cc

### PR DESCRIPTION
**Pull request by hbecerri**
#### PR description:

Implementing comments from PR #39706, #35547 (see https://github.com/cms-sw/cmssw/pull/35547/files#r726169540 and https://github.com/cms-sw/cmssw/pull/35547/files#r726169761)

### CODE REVIEW

**Comment by perrotta** [comment]
please test
(thank you @hbecerri )

**Comment by hbecerri** [comment]
hi @perrotta, not sure what this error means

**Comment by perrotta** [comment]
@hbecerri (as well as @cms-sw/generators-l2 ) errors with das queries are clearly unrelated with this PR, please don't consider them

**Comment by hbecerri** [comment]
> @hbecerri (as well as @cms-sw/generators-l2 ) errors with das queries are clearly unrelated with this PR, please don't consider them

OK, thanks! what should I do next?

**Comment by perrotta** [comment]
> OK, thanks! what should I do next?

Take a coffee and wait that @cms-sw/generators-l2 review your PR? (Or ping them if you want it do be done urgently)

**Comment by Saptaparna** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
