### PR TITLE
Phase2-hgcv121 Bug fix for HGCal V9 Geometry + First Validation

### PR DESCRIPTION
**Pull request by bsunanda**
Take care of missing hits in FH

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda it's preferable to make separate commits for actual bug fixes vs. debug logging, so it is easier to see what was actually done to fix the bug(s)

**Comment by kpedro88** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 I know. But when I worked on the validation code I discovered the bug which is just one line in the xml file. So I did not create a separate PR for this. I shall remember this for future

**Comment by fabiocos** [comment]
+1

affecting only Phase2 HGCal code

**Pull request merged**
