### PR TITLE
Puppi 74x miniaodpass2

### PR DESCRIPTION
**Pull request by nhanvtran**
PUPPI update with tuning (neutral pT cuts and slopes) and bug fixes (uniformized charged particle treatment between AOD/miniAOD based on fromPV definition)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
there is a segfault in packedPFCandidates
... not obvious how this comes about from this PR
... the segfault is not present in the plain IB used for testing

**Comment by nhanvtran** [comment]
Hi all, 

So the issue is tracked to these lines here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L212-L216

specifically, line 215.  

This was code written by @arizzi and @jshlee 

In this latest PR, the number of puppiWeights should be the same as number of original PF candidates, but the for the number of puppi PF candidates, all the PF candidates with zero weight are removed.  Do the experts have any idea?  I will keep digging...

**Comment by nhanvtran** [comment]
Ok, digging a bit more, it is as suspected.  

The PATPackedCandidateProducer is expecting there to be 1-to-1 correspondence between the PUPPI PF candidates and the original PF collection.  Is this essential upstream in the miniAOD workflow**?  We prefer to remove the 0-weight candidates from the PUPP PF candidate collection to reduce speed issues related to jet clustering and other computations which will become even more taxing in higher PU environments

** e.g. here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L255

**Comment by jshlee** [comment]
Hi @nhanvtran, 
I guess there doesnt need to be a 1-to-1 correspondence between the PUPPI PF candidates and the original PF collection. The mapping just needs to be sorted in the PATPackedCandidateProducer so that the correct weights are saved.

Regards,
Jason.

**Comment by arizzi** [comment]
the sorting is already ther, we just miss the -1 protection I guess when sorting

**Comment by arizzi** [comment]
I mean try adding at L241 the same as in L237

**Comment by jshlee** [comment]
as @arizzi says
changing lines #L240-L242 to below should work.

    for(size_t i=0,ntk=mappingPuppi.size();i<ntk;i++){
        int origInd = mappingPuppi[i];
        mappingPuppi[i]=reverseOrder[mappingPuppi[i]];
        if (origInd>=0 ) mappingPuppi[i]=reverseOrder[origInd]; 
    }

**Comment by nhanvtran** [comment]
Hi @arizzi @jshlee 

Thanks for the feedback, but this fix doesn't work.  As I reported, the crash happens in #L215 so anything downstream wouldn't fix this (and I checked that it doesn't)

**Comment by arizzi** [comment]
@nhanvtran then the valuemap that is passed to PATPackedCandidate producer is not correctly filled... the value map should contains the values for all input cands, also the zeros... I guess the bug is in the producer of the valuemap.

**Comment by nhanvtran** [comment]
@arizzi 
Well this is exactly the point -- that we want to remove the 0-weight cands from the PUPPI collection.  My question to you all is if it is necessary to have the same number of puppiCands and pfCands?

**Comment by arizzi** [comment]
@nhanvtran we do not need to have the same number, you just need to fill correctly the maps. Anyhow the issue is on 215 (and I was checking 214). So a protection is needed there as:

if((*puppiCandsMap)[pkref]).key() >=0) mappingPuppi[((*puppiCandsMap)[pkref]).key()]=ic;

**Comment by nhanvtran** [comment]
Thanks @arizzi, @jshlee and I were also discussing and put in a similar type of protection.  I guess that we also should include the additional fix described above 

for(size_t i=0,ntk=mappingPuppi.size();i<ntk;i++){
    int origInd = mappingPuppi[i];
    if (origInd>=0 ) mappingPuppi[i]=reverseOrder[origInd]; 
}

I'm running the tests now and then will verify that your fix gives the behavior we want.

**Comment by nhanvtran** [comment]
Ok, at the risk of creating larger troubles, I put back in the 0-weight pf candidates.  It turns out it was more complicated than we thought and we need to revisit the code if we want to sort out this issue

I'll do the same for PR 10404

**Comment by arizzi** [comment]
what was the problem?
Il 28/lug/2015 20:41, "nhanvtran" <notifications@github.com> ha scritto:

**Comment by nhanvtran** [comment]
I realize that there are other issues with making this change upstream in the PUPPI code, basically that the puppiCandMap and the puppiCands should also be in sync -- so some of the PUPPI producer code should be modified 

I will consult also with Jason since he added the original code (he's traveling tomorrow).  so in the meantime, I know this fix works and practically doesn't change the results other than the 0-weight candidates are going into the computation of the puppi jets and puppi MET

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by nhanvtran** [comment]
hold on...there is a bug associated with this reverting of the code...will provide an update within the hour...

**Comment by nhanvtran** [comment]
ok it's fixed now

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1

superseded by #10551 
@nhanvtran Please hit the close button

**Pull request closed without merging**
