### PR TITLE
Use unique_ptr, not auto_ptr in RecoJet and RecoMET

### PR DESCRIPTION
**Pull request by wmtan**
In preparation for removing framework support for deprecated auto_ptr arguments in put() calls, this pull request replaces the use of auto_ptr with unique_ptr in RecoJet and RecoMET packages. Also, std::make_unique is used when appropriate.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Comparisons got stuck

**Comment by cvuosalo** [comment]
+1

For #15826 f3a8737d443e9c5482d18227d1fbe8b421594c68

Migrating deprecated auto_ptr to unique_ptr in RecoJet and RecoMET. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-14-1100 show no significant differences, as expected.

**Pull request merged**
