### PR TITLE
Level-1 Trigger changes for HI Firmware (75X backport of #12176)

### PR DESCRIPTION
**Pull request by harmonicoscillator**
75X backport of #12176 

We expect to take take with 75X, so this backport is the most important.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by richard-cms** [comment]
Is there anything else we need to get this merged into 75X? @mulhearn

**Comment by richard-cms** [comment]
We really really want this to end up in 7_5_5, is there anything I can do to help that?

**Comment by davidlange6** [comment]
+1
These can be made easier to review if the new functionality is separated from the variable renaming

**Pull request merged**
