### PR TITLE
more robust protection against infinite loops in Ecal multifit (74x)

### PR DESCRIPTION
**Pull request by bendavid**
Main 74x branch version of https://github.com/cms-sw/cmssw/pull/11368

### CODE REVIEW

**Comment by bendavid** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
please test

**Comment by bendavid** [comment]
please test

**Comment by slava77** [comment]
code change looks ok

**Comment by cvuosalo** [comment]
+1

For #11369 166c338fde5ad9579167923178beaff631db43cf

Another bug fix for an infinite loop in ECAL multifit.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11369/8215/summary.html) against baseline CMSSW_7_4_X_2015-09-18-1100 show no significant differences. I reproduced the bug in CMSSW_7_4_12_patch1 and confirmed that it is fixed by this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
