### PR TITLE
Converted HcalDigiToRaw to global module

### PR DESCRIPTION
**Pull request by sabasehrish**

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
For the conversion, it may also be advisabe to make const in HcalDigiToRaw.h the edm::InputTag and the edm::EDGetTokenT class elements: do you plan to do so?

**Comment by sabasehrish** [comment]
Yes, I will create a new pull request.

**Comment by perrotta** [comment]
@sabasehrish : why a new pull request???
Please update this one if you just want to make const those class elements

**Comment by sabasehrish** [comment]
I am not done with all my changes yet, I will let you know when to check awn sign again. Thanks.

**Comment by sabasehrish** [comment]
I am done with my changes.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
Technical
Conversion to global module looks correct
No effect on standard workflows

**Comment by davidlange6** [comment]
+1

**Pull request merged**
