### PR TITLE
Example of passing data to/from CmsRun module

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added an example of using boost python to be able to pass data into
and out of the CmsRun python module.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@jpivarski FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by jpivarski** [comment]
Is this an implementation of what we talked about last week? If so, that was fast! Is like to try it out when it's ready.

**Comment by Dr15Jones** [comment]
@jpivarski yes, this is a simple example of what we discussed.

**Comment by fabiocos** [comment]
@Dr15Jones I assume that the crashes are unrelated to this PR, right?

**Comment by Dr15Jones** [comment]
@fabiocos the unit test failures are unrelated.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
