### PR TITLE
Usage of displaced collections in the B-parking data

### PR DESCRIPTION
**Pull request by mgratti**
This PR includes modifications to allow usage of displaced muon collections in the B-parking data, in view of the upcoming b-parking UL re-reco, at small cost in miniAOD size.

(1) the two collections of reco::Tracks, `displacedGlobalMuons` and `displacedTracks`, are added to the miniAOD in general (not for a specific era).
The size increase was checked in a MINIAODSIM sample with similar PU conditions as the b-parking data and was found to be

displacedGlobalMuons: +256 Bytes/event +0.2%
displacedTracks: +343 Bytes/event +0.3%
Note that the `displacedStandAloneMuons` (dSA) are already included by default.

(2) thanks to the extra information (TrackExtra and TrackingRecHits) made available for the PAT muons by #31350, it should be possible to extrapolate the PAT muon trajectory to the innermost hit of the dSA, allowing for a more precise dR matching, compared to simple dR matching. In order to use this information also for low pt muons, it is proposed to lower the minimum pt at which the information is saved in MINIAOD from 4.5 GeV to 3.0 GeV, but only for the b-parking era.

The size increase was evaluated by Josh to be about 1 KB/evt, corresponding to less than +1%
#30544 (comment)

Additionally, the PR validation was done by running runTheMatrix.py -l limited -i all --ibeos, the output is attached
[runall-report-step123-master.log](https://github.com/cms-sw/cmssw/files/6616854/runall-report-step123-master.log) 

From other PRs for the b-parking, I saw mentioned the workflow ‘1304.181’ for the purpose of testing the b-parking era. 

A backport to 106X is needed and is open at #34008

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- workflow 136.898,1304.182

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> displacedGlobalMuons: +256 Bytes/event +0.2%
> displacedTracks: +343 Bytes/event +0.3%

if the costs are so small, why not enable for all miniAOD?
This is a master version and we are not restricted to no-change rules of the production 10_6_X release

**Comment by mgratti** [comment]
> > displacedGlobalMuons: +256 Bytes/event +0.2%
> > displacedTracks: +343 Bytes/event +0.3%
> 
> if the costs are so small, why not enable for all miniAOD?
> This is a master version and we are not restricted to no-change rules of the production 10_6_X release

I don't have anything against this.

**Comment by rappoccio** [comment]
Yeah, for the master we should add it everywhere.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar 
did the test jobs get stuck here or do we have some overload of cms-bot/jenkins?
please check.

[I'm not sure if another "please check" will just slow this even further]

**Comment by smuzaffar** [comment]
@slava77 , no the comparison job is pending in jenkins queue (  https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/ ) .  Due to extra clang tidy/format PRs, there is some extra load on jenkins

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34024	863227a
- code changes are in line with the PR description and the follow up review
    - data products (displaced tracks) are added to the miniAOD in general
    - relaxed cut on selected muon hits (`slimmedMuonTrackExtras`) is applied only in bParking setup
    - @mgratti please update the PR description to reflect this
- jenkins tests pass and comparisons with the baseline show new products in miniAOD outputs (e.g. in wf 136.88811 they add up to 0.6% of the total file size); separately, as observed in 10_6_X tests the size of `slimmedMuonTrackExtras` increases in `bParking` workflow 136.898 and adds about 0.2% to the event size.

**Comment by qliphy** [comment]
+1

**Pull request merged**
