### PR TITLE
[HGCal] Bug fix in Validation

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR fixes a [bug](#36991) introduced by #36712, and removes some code duplication.
No changes are expected in the output, except for a new set of validation plots in the `SimCluster` subfolder of the HGCal validation, named `ticlSimTracksters_fromCPs`.  

#### PR validation:

```runTheMatrix -l limited```

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
@lecriste thanks for this fix. You mention in the PR description that no changes are expected in the output but the PR seems to introducing 1602 new MEs
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-03-28-1100+996b5a/49244/dqm-histo-comparison-summary.html
Most of them have entries but with null mean and stddev values. Is this expected?

**Comment by lecriste** [comment]
@jfernan2 yes, I meant no changes to the existing MEs. I updated the description accordingly.

**Comment by jfernan2** [comment]
OK, but the reason for having null mean and stddev is...?

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Pull request merged**
