### PR TITLE
Addition of RelVal to HLT HG Combined PCL workflow

### PR DESCRIPTION
**Pull request by phnattla**
#### PR description:

This PR implements a RelVal to PR #46888, which introduced a new High Granularity Tracker Alignment Prompt Calibration Loop using both MinumumBias and Z → µµ data ("HG Combined alignment"), aiming to provide alignment conditions for the High Level Triggers (HLT). 
The new RelVal has the id 1002.5.

#### PR validation:

The following command was successfully used to validate:
```
runTheMatrix.py -l 1002.5 --ibeos
```

Cc: @mmusich @henriettepetersen @TomasKello

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1002.5

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@perrotta FYI

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
