### PR TITLE
Modified muon selection for heavy-ion miniAOD

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Modified muon selection for heavy-ion miniAOD

#### PR validation:

Tested with workflow 159

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 159

**Comment by perrotta** [comment]
@cmsbuild please test with #30354  workflow 140.5611

**Comment by perrotta** [comment]
please test workflow 140.5611 with #30354
(order matters..)

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.5611 with #30354

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.5611 with #30354

**Comment by perrotta** [comment]
+1
- The new selection studied for PAT muons in Run3 HI has been compared with the current one thanks to the new HI re-miniAOD workflows defined with #30354: the size of slimmed muons is rather similar to the one obtainable with the current (pp) selection, just a 1.4% size increase for that specific branch (fraction of permil in the overall event size)
- Jenkins tests pass and show no differences anywhere else

**Comment by perrotta** [comment]
@cmsbuild please test workflow 140.5611
(tests still pending seem to prevent this PR being considered as signed)

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.5611

it looks like the bot was asleep

**Comment by slava77** [comment]
... that also triggered an update in the signature list

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
