### PR TITLE
remove histogrammar (obsolete package)

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:
removes unit tests for histogrammar python package (removed in https://github.com/cms-sw/cmsdist/pull/5219)

#### PR validation:

fixes test failures in https://github.com/cms-sw/cmsdist/pull/5219

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@davidlange6 this package looks unused within CMSSW, apart for the test removed here (and introduced by you 3 years ago). So I assume this should be ok, do you know whether anybody was giving it a try?

**Comment by davidlange6** [comment]
as its analysis related, people using it most likely won't be doing so within cmssw. Anyway, its ok to remove - its been replaced quite a while ago and no longer supported

**Comment by santocch** [comment]
+1

**Pull request merged**
