### PR TITLE
Fix customise for RunI

### PR DESCRIPTION
**Pull request by VinInn**
fix  damage done by #10126 and #10373

### CODE REVIEW

**Comment by VinInn** [comment]
tested with
```
cmsDriver.py step3 --datatier GEN-SIM-RECO,DQMIO --conditions auto:run1_mc -s RAW2DIGI,L1Reco,RECO,EI,ALCA:EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron+HcalCalIsoTrk,VALIDATION,DQM --eventcontent RECOSIM,DQM -n 100 --filein file:step2.root --fileout file:step3.root --customise RecoTracker/Configuration/customiseForRunI.customiseForRunI
```

in 25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT

**Comment by VinInn** [comment]
@mtosi , @davidlange6 FYI

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
easy to fix, I hope.
I'll provide a commit/patch to @VinInn for inclusion in this PR and in #10125

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
@VinInn  Thanks for reporting the issue with RecoTLR , it looks like it's in the part of the code that was there for ages.
@Dr15Jones 
Do we have some new syntax checking?

**Comment by cvuosalo** [comment]
The file FinalTrackSelectors /plugins /TrackListMerger.cc has problems with possible zero-size arrays being accessed, as found by the static analyzer around line 430. Fixing this problem might be complicated, so it can be done in a later PR.

**Comment by slava77** [comment]
there is a solution to zero size and VLA in general in  CommonTools/Utils/interface/DynArray.h

**Comment by cvuosalo** [comment]
+1

For #10500 07ceb0878c1553f1cc5a7d861c55c05bbc8545b4

Fixing a problem in Run 1 customization. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-08-03-1600 show no significant differences, as expected. Checking T0 configs shows the new code doesn't introduce any configuration problems. The Run 1 tracking customization function for step 3 of workflow 25.0_TTbar runs successfully, showing the TrackSeedMonjetCoreRegionalStep error has been fixed. See #10126 for more details on the original error.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
