### PR TITLE
Further CaloL2 O2O updates (supersedes #24922)

### PR DESCRIPTION
**Pull request by bundocka**
Supersedes #24922
Not critical for #24869

This PR brings the CaloL2 O2O fully inline with the firmware.

Remove etSumX & etSumY calibration LUTs: these are replaced by met & metHF calibration LUTs
Add metPhi & metHFPhi calibration LUTs
Add demux LUTs to conversion script
Update caloParams & helper class
NB. The etSumXCalibration & etSumYCalibration nodes that have been repurposed in CaloParamsHelper.h and CaloParamsHelperO2O.h were never used anywhere in CMSSW, so this is backwards compatible.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@thomreis @bundocka in which plots is the effect of this update of the emulator supposed to appear? Funnily we get changes in many L1T checks but not here, is this due to just a small statistics? Were effects verified in offline tests?

**Comment by fabiocos** [comment]
@bundocka @thomreis @rekovic ping

**Comment by bundocka** [comment]
@fabiocos This update shouldn't affect the emulator at all, it just renames two caloParam nodes that were never used anywhere, and adds two new ones, so that the O2O is consistent with all the configurable parameters at CaloL2. This is not critical for HI data taking, and can be merged into the L1T O2O release manually.

**Pull request merged**
