### PR TITLE
`CalibTracker`: fallback to the `OnlineLuminosityRecord` when SCAL is not available

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It was noticed during 2022 900GeV collision runs that the information for PU and instantaneous luminosity is always identically zero for all runs (see e.g.: https://tinyurl.com/25cqyvlu).
This is due to the fact that the online PU and inst. luminosity information were taken from the SCAL FED digis which are not available anymore in Run-3. This PR fixes the problem by adding a fall-back to the `OnlineLuminosityRecord ` provided by the S/W FED 1023.

#### PR validation:

`cmssw` compiles, unit tests are running correctly.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but needs to be backported all the way down to 12.3.X.

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix,trk

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
FYI @robervalwalsh @mdelcourt @jlagram

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
Although there is this dead initialization
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5fbd66/25552/llvm-analysis/report-9c8e4f.html#EndPath
Not sure if we want to fix it in this PR....

**Comment by mmusich** [comment]
>  Not sure if we want to fix it in this PR....

clearly beyond the scope.

**Comment by perrotta** [comment]
+1

**Pull request merged**
