### PR TITLE
[10_2_X] OfflineDQM: Offline  L1T muon DQM with coordinates extrapolated to the muon system CMSLITDPG-729

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/24561

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
@stahlleiton Could you please make sure that the name of the subsystem is mentioned in the title of the PR?

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
Hi @stahlleiton, as 10_2 is no longer being used maybe this PR should be closed?

**Comment by fabiocos** [comment]
@rekovic @thomreis ping

**Comment by thomreis** [comment]
Hi @fabiocos 
I think this PR is not needed anymore. @stahlleiton can you please close it.

**Pull request closed without merging**
