### PR TITLE
Hcal 2017 DB Writer and Reader Fix

### PR DESCRIPTION
**Pull request by ianna**
- Correct Hcal geometry summary for DB: CaloSubdetector parameters are no longer ordered by dense index
- Adjust both DB reader and writer

@davidlange6 and @mmusich - a DB tag will shortly follow.

This PR fixes https://github.com/cms-sw/cmssw/issues/15985

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@slava77 - please, have a look at comparison results when they are available. This PR changes Hcal reco geometry reader from DB.

**Comment by mmusich** [comment]
Thansk @ianna! 
In view of the simplifications of the phase-I workflows proposed in https://github.com/cms-sw/cmssw/pull/15994 I'd need the full list of recommend DB tags to properly describe the geometry changes included in `Extended2017new`.
So far my understanding is:

```
IdealGeometryRecord: TKRECO_Geometry_81YV10
PGeometricDetExtraRcd: TKExtra_Geometry_81YV10
PTrackerParametersRcd: TKParameters_Geometry_81YV10
GeometryFileRcd:  to be updated  
HcalParametersRcd: to be updated  
PCaloTowerRcd: to be updated                        
PHcalRcd: to be updated                      
```

am I missing something? 
Thanks,

Marco

**Comment by ianna** [comment]
@mmusich - I think, the following will have to be updated as well (for consistency) as some materials have changed.
```
IdealGeometryRecord: TKRECO_Geometry_81YV10
PGeometricDetExtraRcd: TKExtra_Geometry_81YV10
PTrackerParametersRcd: TKParameters_Geometry_81YV10
```

**Comment by ianna** [comment]
+1

**Comment by mmusich** [comment]
@ianna about: https://github.com/cms-sw/cmssw/pull/16211#issuecomment-253785069. Thanks. Have those changes in the material already become the default in xml? Can you point me to PRs?

**Comment by ianna** [comment]
@mmusich - there is at least one pending PR https://github.com/cms-sw/cmssw/pull/16137

**Comment by ianna** [comment]
@ggovi and @davidlange6 - please, include it in pre13

**Pull request merged**
