### PR TITLE
Store variable names in ROOT GBRForest files

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added storing and retrieving variable names from files.

#### PR validation:

Code compiles. Running a job that uses the original xml files still works.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
So I converted the files in `RecoEgamma/ElectronIdentification/data/Spring16_HZZ_V1` to be their ROOT equivalents (using this PR), changed the `RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Spring16_HZZ_V1_cff.py` to point to the new files and ran step4 of workflow 11834.21. The files were read (tested using strace) and the job completed just fine.

**Comment by swagata87** [comment]
thanks @Dr15Jones 
 - related to https://github.com/cms-sw/cmssw/issues/37867 and https://github.com/cms-sw/cmssw/issues/38089
 (tagging the related issues in this PR so that necessary PRs/issues can be found easily afterwards)

**Comment by clacaputo** [comment]
+reconstruction

- technical PR
- no reco changes

**Comment by qliphy** [comment]
+1

**Pull request merged**
