### PR TITLE
Configure HcalMinBias AlCaReco for heavy Ion 2018

### PR DESCRIPTION
**Pull request by tocheng**
Backport #25007

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@deguio This is something you want to follow

**Comment by fabiocos** [comment]
@tocheng @deguio @andrius-k can we converge on this by 1100 today? Or do you see issues to be clarified?

**Comment by abdoulline** [comment]
I don't see problems.

**Comment by tocheng** [comment]
+1

**Comment by tocheng** [comment]
@fabiocos Sorry for the delay, I approved the PR

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@andrius-k please check anyway and sign it for reference or comment

**Pull request merged**
