### PR TITLE
new plots for tracking DQM  80x

### PR DESCRIPTION
**Pull request by mtosi**
back-port of PR https://github.com/cms-sw/cmssw/pull/16013
@dmitrijus @rovere @VinInn

### CODE REVIEW

**Comment by mtosi** [comment]
in addition, it is really important to have it integrated as soon as possible,
because this PR fixes the range of some plots vs inst lumi

**Comment by cvuosalo** [comment]
backport #16013

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

For #16014 7534d71393d3610e0af383cb3df3e15f593eb8dd

Adding new tracking DQM plots. There should be no change in monitored RECO quantities.

#16013 is the 81X version of this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-09-28-1100 show the new DQM plots and no other significant differences, as expected.

**Comment by mtosi** [comment]
@dmitrijus @vanbesien could this PR been signed, please ?
thanks

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by cvuosalo** [comment]
+1

For #16014 95705622d8c59e7280bce11e31514483c704360c

Second approval, after some code revisions. The new code is satisfactory, and the new Jenkins results show no problems, just the revised DQM plots and changes due to the changes in the stopping reason.

**Comment by mtosi** [comment]
@dmitrijus @vanbesien can this PR be signed, please ?
it would be really useful to have integrated asap ....

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
