### PR TITLE
dqm for DoubleMu3_DCA_PFMET50_PFMHT60

### PR DESCRIPTION
**Pull request by gkaratha**
Dear experts,

No new code developed. Only reuse what was already there for a modified path. Thanks

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

please read https://www.python.org/dev/peps/pep-0008/ in your spare time.

**Comment by mtosi** [comment]
can you please quantify the increase in #bins ?

**Comment by gkaratha** [comment]
Dear @mtosi ,

I did not increase the bins. They are the same as in DoubleMu3_DZ_PFMET50_PFMHT60. Or I did not understand the question? Thanks

**Comment by mtosi** [comment]
are you adding new histograms ?

**Comment by gkaratha** [comment]
Yes for a new path

**Comment by mtosi** [comment]
can you quantify the #bins you are adding, please ?

**Comment by gkaratha** [comment]
ok sure! if i am not mistaken 354 in total, for all different plots (meaning i dont count numerator/denominator) . But is less than in the doublemu3_dz_pfmet50_pfmht60. I created less plots now. Thanks

**Comment by gkaratha** [comment]
also i can remove some plots that i think are redundant (like 2d for muon pt)

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by gkaratha** [comment]
Hi I will do that. Clearly, yesterday that I made the PR was mergable. I will rebase it. Thanks

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@dmitrijus @davidlange6 
can we proceed w/ the integration of this PR ?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
