### PR TITLE
HcalDQM - Drop type specs for python files

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

Drop type specs in DQM/HcalTasks and DQMOffline/Hcal configurations files

#### PR validation:

runTheMatrix.py -l limited -i all --ibeos test okay

### CODE REVIEW

**Comment by jfernan2** [comment]
Thanks a lot for this PR @lwang046 
May I ask you to modify also any right hand side assignment? Explicit types on the right hand side should be avoided, like those on lines https://github.com/cms-sw/cmssw/blob/df8df1814f515034b47ce2489cb54bced5ecffe5/DQM/HcalTasks/python/OfflineSourceSequence_pp.py#L15-L22
Thank you!

**Comment by jfernan2** [comment]
Thank you @lwang046 
Could you do the same (drop type in every right hand side assignment) for the rest of python files in the package?
Thanks

**Comment by lwang046** [comment]
Hi @jfernan2 thanks for pointing out the missed ones that needs to be fixed. I tried to go file by file in this package and fixed all files that I can identify except this file which I'm not sure if it needs change: https://github.com/cms-sw/cmssw/blob/master/DQM/HcalTasks/python/HcalQualityTests.py

**Comment by jfernan2** [comment]
Thanks a lot @lwang046 
HcalQualityTests.py  seems OK since it is a genuine module declaration, so no real assignments but declarations

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
