### PR TITLE
Temporarily revert "Add vertex resolutions and pulls vs x,y,z positions in tracking DQM"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#26822

Following investigations of crashes in the IB after the integration of #26822

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.831

**Comment by fabiocos** [comment]
@mmusich indeed in a standalone test of mine this revert fixes the reproducible crash of 136.831 . I integrate the revert for the next IB, and we may come back to this code as soon as the fix is available

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by jfernan2** [comment]
+1

**Pull request merged**
