### PR TITLE
Roll back era for early Run 2 heavy-ion relval worflow

### PR DESCRIPTION
**Pull request by mandrenguyen**
As discussed in #19470 the Run 2 heavy-ion reco workflows were migrated to use the Run2_2016 era.  Since we didn't use the HI reco in 2016, this doesn't make much sense. 
This PR removes Run2_2016 from the era.

### CODE REVIEW

**Comment by kpedro88** [comment]
The actual Era used in most of 2015 was Run2_25ns. Is there a specific reason to use 50ns for HI?

**Comment by mandrenguyen** [comment]
@kpedro88   Since we have a long bunch spacing for PbPb, I thought we ran the detectors in 50ns mode.  Now that I look back at the original customize though, I see that you're right, we used the 25ns settings.  
For reference, see customisePostLS1_HI, here:
https://github.com/cms-sw/cmssw/blob/master/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py
I will switch that, thanks!

**Comment by slava77** [comment]
On 6/30/17 6:51 AM, mandrenguyen wrote:
> @kpedro88 <https://github.com/kpedro88> Since we have a long bunch
> spacing for PbPb, I thought we ran the detectors in 50ns mode. Now that
> I look back at the original customize though, I see that you're right,
> we used the 25ns settings.
> For reference, see customisePostLS1_HI, here:
> https://github.com/cms-sw/cmssw/blob/master/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py
> I will switch that, thanks!
> 

There is a Run2_HI era which is supposed to cover the needs present
earlier in the customisePostLS1_HI

**Comment by Martin-Grunewald** [comment]
AFAIK it is a sub-era of 2015, ie, need to use: ```--era=Run2_2015,Run2_HI```

**Comment by slava77** [comment]
On 6/30/17 7:10 AM, Martin Grunewald wrote:
> AFAIK it is a sub-era of 2015, ie, need to use: |--era=Run2_2015,Run2_HI|

I vaguely recall that when I converted the T0 setup from customise to
eras I have checked
that the Run2_HI (used in
DataProcessing/python/Impl/HeavyIonsEra_Run2_HI.py)
delivers the same as what was used in 75X.

... also, there is no Run2_2015 era

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hmm, ok, in fact what I use is --era=Run2_2015,Run2_HI, but you want 2015, right?

**Comment by slava77** [comment]
On 6/30/17 7:46 AM, Martin Grunewald wrote:
> Hmm, ok, in fact what I use is --era=Run2_2015,Run2_HI, but you want
> 2015, right?

git grep Run2_2015
produces 0 hits.

I suppose the cmsDriver ignores it and we are back to just Run2_HI
that I think is enough.

**Comment by Martin-Grunewald** [comment]
--era=Run2_2016,Run2_HI,

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
