### PR TITLE
Raw iso pt sum rework

### PR DESCRIPTION
**Pull request by andrewj314**
Rebase of reworking of raw iso pt sum calculation to 8_0_X. No changes to reco quantities are anticipated - this is a simple fix that calculates the pt sum for isolation once and stores it so that it may be used for each iso WP, rather than have each iso WP calculate the pt sum separately.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@andrewj314: Please add to the PR description the changes to reco quantities that are expected from this PR.

**Comment by andrewj314** [comment]
@cvuosalo Updated! See the first comment - we do not expect changes to reco quantities

**Comment by cvuosalo** [comment]
@andrewj314: Your description makes it sound like this PR will not change much. However, if you look at the Jenkins DQM plots, there are thousands of changes in tau isolation quantities, including efficiencies. This large number may be partly due to there being an unnecessarily large number of DQM plots for taus, but still it is hard to reconcile your description of no changes with the DQM plots showing that seemingly every quantity with tau isolation in the name is showing changes.

**Comment by andrewj314** [comment]
@cvuosalo This is indeed surprising - all that's happening is that the pt sum is calculated once, rather than for each WP. The pt sum should be the same for each WP, so I really don't know why this is changing physics results. I will look into it.
@veelken is there any reason we'd expect to see this simple rework change tau isolation quantities?

**Comment by andrewj314** [comment]
@cvuosalo Could you please point me to these DQM plots? I couldn't find them in the cmsbuild link. Thanks!

**Comment by cvuosalo** [comment]
@andrewj314: The DQM plots are here in alternative-comparisons:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-04-1100+12261/11137/alternative-comparisons/

25202.0 and 50202.0 have especially large numbers of differences.

**Comment by cvuosalo** [comment]
Here are some examples of differences found in a test of workflow 25202.0_TTbar_13 with 70 events against baseline CMSSW_8_0_X_2015-11-03-2300.
ptsum
ratio
eff

**Comment by cvuosalo** [comment]
@andrewj314: When might this PR get updated?

**Comment by andrewj314** [comment]
@cvuosalo There are substantial relvals that need to be done in order to find out what's causing the large discrepancy in measured quantities. Given that the tau pog's priority is to get PR #12298 added to 76x in the next 7-10 days, we are going to focus on achieving that and then push this PR to 80x once we fix the errors.

**Comment by cvuosalo** [comment]
@andrewj314: When will work on this PR resume?

**Comment by andrewj314** [comment]
@cvuosalo Now that the new discriminators have been added to 76x (PR #12586) (or at least now that it's wrapping up) I will resume work on this. I will continue to try to get to the bottom of why it's changing measured quantities so severely.

**Comment by cvuosalo** [comment]
@andrewj314: Please give an update about the status of this PR.

**Comment by andrewj314** [comment]
On recommendation of the tau pog conveners, I'm closing this PR until we can get PR #12586 ported to 80x

**Pull request closed without merging**
