### PR TITLE
Dynamic PPS timing calibration fit [backport of 44235]

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

Extension to the existing calibration fit that calculates the parameter from the histogram, instead of relying on the pre-defined ranges. Logic works as follows:

Find the peak of counts in the TOT 1-d distribution (the peak must be located at TOT<20ns) -> this define the TOTMAX_bin
From TOTMAX_bin move to higher TOT till the counts are below THR% of max -> this define the upper_tot_range for the fit (in any case below 18 ns)
From TOTMAX_bin move to lower TOT till the counts are below THR% of max -> this define the lower_tot_range for the fit (in any case above 8ns)
Fit the 2d profile in the range (upper_tot_range, lower_tot_range)
#### PR validation:

Standard wfs for PPS timing calibration.

#### Backport of #44235

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
test parameters: 
- workflows =1043.0,1044.0,1045.0

**Comment by saumyaphor4252** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44235

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/44235
- Sccessfully merged in master since CMSSW_14_1_X_2024-03-01-2300

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
