### PR TITLE
hltDiff: compare TriggerResults event by event (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
Compare two TriggerResults collections event by event.
These can come from two collections in the same file(s), or from two different sets of files.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
though this only adds a new stand-alone command line tool, so there is nothing to be tested...

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
