### PR TITLE
Static Analyzer: Update EventSetupRecord::get report to included modules not mapped to packages.

### PR DESCRIPTION
**Pull request by gartung**
The class name of the top level function, eg. produce, with the template bracket and arguments stripped is used as the module name. 

```
...
no-package:
  CaloCleaner:
  - 'CaloCleaner::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<CastorRecHit>::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<EcalRecHit>::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<HBHERecHit>::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<HFRecHit>::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<HORecHit>::produce(edm::Event &, const edm::EventSetup &); '
  - 'CaloCleaner<ZDCRecHit>::produce(edm::Event &, const edm::EventSetup &); '
...
```

Verified with output from an older IB that the modules not mapped to packages appear under the package "no-package".

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
