### PR TITLE
corrected wrong cfi file called for PhaseIPixel tag in dumpSimGeometry_cfg.py

### PR DESCRIPTION
**Pull request by friccita**
In dumpSimGeometry_cfg.py, the wrong cfi.py file was being loaded for the PhaseIPixel tag; I have changed it to the correct filename.

### CODE REVIEW

**Comment by boudoul** [comment]
I will  take the opportunity of his PR to suggest for this PR or a subsequent one to remove the super obsolete Tracker scenarios , I see at least three of them in this file to be removed : 

    elif score == "Phase1_R34F16":
        process.load('Geometry.CMSCommonData.Phase1_R34F16_cmsSimIdealGeometryXML_cff')
 
    elif score == "Phase2Tk":
       process.load('Geometry.CMSCommonData.cmsExtendedGeometryPhase2TkBEXML_cfi')
        
    elif score == "SLHC":    process.load('SLHCUpgradeSimulations.Geometry.Phase1_R30F12_HCal_cmsSimIdealGeometryXML_cff')

Thanks 
Gaelle

**Comment by boudoul** [comment]
Thanks @friccita 
@cmsbuild please aknowledge changes

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
