### PR TITLE
PCC Auto. Integration backport to CMSSW_10_0_0 from 10_1_0_pre1

### PR DESCRIPTION
**Pull request by samhiggie**
Backport from PR:
https://github.com/cms-sw/cmssw/pull/22439 
please see this PR for discussion

### CODE REVIEW

**Comment by arunhep** [comment]
@samhiggie can you please change the title of this PR ? This is quite generic.
you can use the same title as master PR with mention of 10.0.X here.

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
@samhiggie @capalmer85 why the milestone of this PR is still 10_1_X ?
OTOH, i think this PR can be closed because this PR https://github.com/cms-sw/cmssw/pull/22590 from @cerminar is going to supersede this. Once https://github.com/cms-sw/cmssw/pull/22590 will be merged in master, we can open a backport in 10.0.X. 
pls see that https://github.com/cms-sw/cmssw/pull/22590 contains your commits as well.

**Comment by arunhep** [comment]
@samhiggie can you please close this PR ?

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
