### PR TITLE
Fix mismatched calo signals warning and make accessors consistent

### PR DESCRIPTION
**Pull request by kpedro88**
It was noticed (by @fwyzard in https://hypernews.cern.ch/HyperNews/CMS/get/simDevelopment/1835.html) that the warning "Mismatched calo signals" occasionally appeared in premixing workflows in 94X.

I eventually determined this was an unintended side effect of #17920. Before that PR, `CaloHitResponse::add()` didn't use the built-in `+=` operator for `CaloSamples`, but a separate, simpler algorithm that didn't check the precise size. We don't bother to do high-fidelity premixing for HO, so the warning started to appear in the (fairly rare) occurrence of premixing pileup hits in HO. It has no effect on physics, but is slightly irritating.

To fix this, I made a `setPreciseSize()` accessor for `CaloSamples` that resizes the associated vector. I also made `setSize()` resize the data vector (and appropriately modified the one place where `setSize()` was already used). The `HcalSiPMHitResponse` class uses this when high fidelity premixing is not enabled, and that suppresses the warning as intended.

attn: @abdoulline

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@arunhep please sign

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
