### PR TITLE
Fixed MC truth for SimHits

### PR DESCRIPTION
**Pull request by civanch**
Fixed filling of MC truth to PSimHits.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
in private tests SimHits now restored. In comparisons to this PR there are many fails, which is expected. 

@davidlange6, what WFs should be tested privately?

**Comment by lgray** [comment]
@civanch Please test 22405 with particle type changed to k_long (pdgid = 130).

@rovere Does this PR fix things for you?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
