### PR TITLE
Support of private frontier Key for workflow-specific caching

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

We are enabling the use of workflow-specific private keys for the condition data access with frontier. The goal is ensuring that the fresh-keys identifying the cached data in the squids are not shared with other workflows/processes. In this way, unintended interferences and unwanted data are avoided. 

The keys will be provided as an external parameter for the read-only ESSource-based workflows, and as the content of a specified file for the update-capable workflows.

#### PR validation:

Unit tests and integration tests

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by tlampen** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
