### PR TITLE
[92X] L1T Validation Module with GeneratorParticle Information: remove low pt objects and fill overflow in last bin

### PR DESCRIPTION
**Pull request by ly615**
This PR makes two updates in Validation/L1T package which is used to fill the L1TriggerVsGen histograms for L1T RelVal: remove the low pt gen objects (i.e pt < 10GeV);  fill the overflow pt entries (i.e pt >160GeV) in the last pt bin 120-160 GeV.

### CODE REVIEW

**Comment by perrotta** [comment]
-1
to be rebased

**Comment by kpedro88** [comment]
-1
wrong branch? or needs rebase
(http://cms-sw.github.io/tutorial-resolve-conflicts.html)

**Comment by rekovic** [comment]
@ly615
Need to rebase to 93x. Start with the latest 93X IB release.
I think you want only the last commit here, so can cherry-pick.

**Comment by davidlange6** [comment]
closing as there is no fix in the last days.

**Pull request closed without merging**
