### PR TITLE
Removed ParameterSet usage from CondFormats/EcalObjects

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The ParameterSet are now handled by the ES modules.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by yuanchao** [comment]
+1

* removed ParameterSet usage
* matrix and unit tests passed

**Comment by ggovi** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33956	f09f862
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences (including the GPU part which is modified by this PR)

**Comment by qliphy** [comment]
+1

**Pull request merged**
