### PR TITLE
add HL objects (towers, jets)

### PR DESCRIPTION
**Pull request by popovvp**

### CODE REVIEW

**Comment by deguio** [comment]
@popovvp 
this PR seems not mergeable. could you please rebase?
thanks,
F.



@vanbesien

**Comment by deguio** [comment]
-1

**Comment by deguio** [comment]
to be rebased

**Comment by davidlange6** [comment]
@cmsbuild, please test 
there are commits here

**Comment by vanbesien** [comment]
Checked: Comments https://github.com/cms-sw/cmssw/pull/8910#issuecomment-97414966, https://github.com/cms-sw/cmssw/pull/8807#issuecomment-95930806 and https://github.com/cms-sw/cmssw/pull/7693#issuecomment-74292413 seem to have been handled now.

For the rest this PR is also okay for me.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@popovvp - for the record, what is HL stand for?

**Comment by popovvp** [comment]
HL = High Level objects

**Comment by davidlange6** [comment]
I guess you mean Castor HL objects - eg, rechits? can be good to have a more descriptive name in the title

**Comment by popovvp** [comment]
High level objects taken from the next steps of analysis after
RecHits (towers, jets of different kinds, etc.)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
