### PR TITLE
Updates on DQMOffline/Trigger for Muons

### PR DESCRIPTION
**Pull request by sscruz**
Backport from  #18968

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
@sscruz can you check if this PR is included #19961 ?

**Comment by mtosi** [comment]
@sscruz can you please check if the code in this PR is already included in #19961 ?
thanks

**Comment by sscruz** [comment]
Hi @mtosi, I just checked and my code seems to be in place in #19961. However, I'm on holidays so I haven't been able to run #19961 to see if I still everything is still working properly. 
Sorry about this, 
Sergio

**Comment by mtosi** [comment]
enjoy your holidays !
please, let us update as soon as you are back ;)

**Comment by sscruz** [comment]
hi @mtosi , I managed to run #19961 and all the histograms introduced by this PR seem to be in place. 
Sorry this took a bit!

**Comment by mtosi** [comment]
thanks
  mia

**Comment by mtosi** [comment]
@sscruz 
let me cross check
your developments are in #19961 
and #19961 is in #20620, which is close to be merged (hopefully)

=> shall we close this PR ?

**Comment by sscruz** [comment]
hi @mtosi , 
yes, that is correct!

**Comment by mtosi** [comment]
then, please
@sscruz @davidlange6 could we please close this PR ?

**Pull request closed without merging**
