### PR TITLE
DD4Hep: DDDetector from DB - allow to delay a Solid Definition

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Allow different order of the solids in the XML definition

#### PR validation:

```
cmsRun DetectorDescription/DDCMS/test/python/testGeometry2021FromDB.py
```

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by cvuosalo** [comment]
@ianna: For documentation, could you please add detail to this PR description? What "different" order is now allowed? What does DD4hep require?

**Pull request merged**
