### PR TITLE
Update for phase1 geometry of phase0 misalignment scenarios

### PR DESCRIPTION
**Pull request by consuegs**
Update for phase1 geometry of phase0 misalignment scenarios. Main change: object Ids.

Previous file Scenarios_cff.py, containing phase0 geometry scenarios will contain now phase1 geometry scenarios and Scenarios_phase0_cff.py will store phase0 geometry scenarios for documentation purposes

### CODE REVIEW

**Comment by boudoul** [comment]
Hello @consuegs , Just for me to understand - You mentionned in the description that you keep phase0 **for documentation**  , I guess this is more than for documention, are you not going to use this for the Ultra Legacy work when adressing the 2016 period (phase0) ?

**Comment by mmusich** [comment]
> Hello @consuegs , Just for me to understand - You mentionned in the description that you keep phase0 **for documentation** , I guess this is more than for documention, are you not going to use this for the Ultra Legacy work when adressing the 2016 period (phase0) ?

Hi @boudoul, allow me to chime in. 
While it is certainly true that the phase0 scenarios **might** still be used to create a step-0 misalignment for the phase-0 geometry in the context of the ultra-legacy, the purpose of this PR is mainly to document the **phase-I** scenarios that the alignment group has prepared to allow POGs to perform systematic misalignment studies. As you see the phase-0 file is untouched (only renamed) and remains available in case of need. 
cc @hroskes @connorpa

**Comment by consuegs** [comment]
> Hello @consuegs , Just for me to understand - You mentionned in the description that you keep phase0 **for documentation** , I guess this is more than for documention, are you not going to use this for the Ultra Legacy work when adressing the 2016 period (phase0) ?

Hi @boudoul, as explained by @mmusich, I meant for documentation purposes, in the sense of upcoming work (not related to campaigns as the ultra-legacy effort) in which we will definitely need an up to date file for the creation of misalignment scenarios

**Comment by boudoul** [comment]
Thanks @consuegs and @mmusich for the clarifications !

**Comment by fabiocos** [comment]
@consuegs @mmusich besides the PR test, what is the expected effect of this? Am I correct that it does not affect directly production workflows, but just the preparation of alignment to be stored in the DB?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
