### PR TITLE
Phase2-hgx293Y Add a test to verify the list of Valid DetId and their corners

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a test to verify the list of Valid DetId and their corners for HGCal geometry

#### PR validation:

Make use of cfg's in Geometry/HGCalGeometry/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
The test failure seems to related to the new GT, issue is opened in https://github.com/cms-sw/cmssw/issues/35927

**Comment by srimanob** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/35766

**Comment by srimanob** [comment]
+Upgrade

This PR is to add tests.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
