### PR TITLE
gcc7 warning fix: move anonymous::CheckBinLabels in to MEtoEDM class

### PR DESCRIPTION
**Pull request by smuzaffar**
- move anonymous::CheckBinLabels in to MEtoEDM which is only user of this function
- cleanup unnecessary include statements

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by smuzaffar** [comment]
+1

**Comment by smuzaffar** [comment]
@rekovic can you please check and sign it if looks good to you ... I don't think it is effecting any L1 code though.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
