### PR TITLE
L1T DQM offline muon efficiency upgrades

### PR DESCRIPTION
**Pull request by thomreis**
Upgrades for the L1T offline DQM code to produce efficiency and resolution plots.

- Separate efficiency plots for all TF regions
- pt cut + quality cut combinations configurable from cfg file
- Add efficiency vs. number of vertex plots
- Add q/pT resolution histograms
- Use L1T muon coordinates at the vertex
- Use DQMGenericClient to divide numerator and denominator histograms
- Use only L1T muons from BX 0

### CODE REVIEW

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be reviewed/merged please?

**Comment by fabiocos** [comment]
@thomreis @dmitrijus the PR is not mergeable, could someone rebase it so as we can move forward?

**Comment by thomreis** [comment]
+1

I guess the DQMEDAnalyzer PR #21871 was expected to create some conflicts when merged.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 can you please sign this one again?

**Comment by jfernan2** [comment]
+1

**Comment by thomreis** [comment]
@fabiocos @davidlange6 all conflicts have been resolved and tests are OK. Can this be merged please?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
