### PR TITLE
add conddb subcommand to list ALL tags in condDBv2

### PR DESCRIPTION
**Pull request by apfeiffer1**
add subcommand to conddb tool to list ALL tags in condDBv2 (>7200 at present!)

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by apfeiffer1** [comment]
cmsbot please test

... again. There is nothing in the relvals which used the command-line
command at all (and esp. not the newly added subcommand).


On Tue, Mar 24, 2015 at 12:01 PM, cmsbuild <notifications@github.com> wrote:

>  -1
> Tested at: 007f0d0
> <https://github.com/cms-sw/cmssw/commit/007f0d0f5780f9d41f998a610fa3a8798d2e8d13>
> The relvals timed out after 1 hour.
>
> you can see the results of the tests here:
>
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8470/2994/summary.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8470#issuecomment-85451136>.
>



-- 
Thanks,
       cheers, andreas

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
