### PR TITLE
fix Radix Sort for size = N*256+1 [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport of #38599 from @VinInn :

> As the title says.
> 
> purely technical. no regression expected as used in production only for vertex sorting that never exceeds 100 or so.
> 
> thanks @cericeci for pointing out the failure and provide a test

#### PR validation:

See #38599 .

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38599.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #38599

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/heterogeneous-l2 if you want this in the next 12_4_3, intended for operations, please sign it.
Otherwise it will move to the next 12_4_X

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1
- Succesfully merged in CMSSW_12_5_X_2022-07-15-1100

**Pull request merged**
