### PR TITLE
relval matrix updates, PR#13516 port to 81x

### PR DESCRIPTION
**Pull request by hengne**
PR# https://github.com/cms-sw/cmssw/pull/13516 port to 81x

List of updates:
-  update golden json to the EOY re-reco complete version
-  turn on multiCore with 4 cores for DIGI/HLT/RECO steps. N cores setting defined in workflow steps, and wmcontral read these numbers for relval production.
-  re-arrange upgrade workflows removing old 8TeV workflows.
-  phase1 workflows set to 13TeV
-  Update relval_2017 IB tests workflow list to be: [10021.0,10024.0,10025.0,10026.0,10023.0,10224.0,10225.0]
-  turn on realistic Beamspot for phase1 gen-sim, turn on phase1 GT for realistic BS, build on top of PR #13394 
-  update phase1 gen-sim input
-  Add 3 data 2015 HighLumi run High stats workflows needed for cross POG studies
-   Add a new TTbar workflow wrapped from an ext-gen workflow, starting from LHE generation (then pythia gen-sim, digi, reco, etc.,).
-  Update minibias inputs for mixing and premixing.

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
strange DAS error, should be temporary, i just run the same das command, and it works fine:
[heli@hengnepc1 src]$ das_client.py --cache das-cache.file --limit 0 --query 'file dataset=/MinimumBias/Run2011A-v1/RAW run=165121 site=T2_CH_CERN'
/store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/0699429A-B37F-E011-A57A-0019B9F72D71.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/18E0AF9F-BA7F-E011-AC1C-001D09F24259.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/1E9D751C-CE7F-E011-A67E-0030487CD6E6.root
/store/data/Run2011A/MinimumBias/RAW/v1/000/165/121/2C1B50CC-C17F-E011-9FE6-003048F1C836.root

**Comment by hengne** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@hengne - we should leave the # of cores as a parameter with default of 1 for the purposes of this PR. Changing it needs some coordination for the integration builds.

**Comment by hengne** [comment]
@davidlange6 Hi David, there is some complication of doing this. There are the following way of specifying N cores to the workflows:
1.) -t option in the runTheMatrix.py, this will apply the N cores to all the cmsDriver steps including the harvest step...
2.) hardcode in the MatrixInjector.py, this can change the signature of relval jobs running on the sites, but cannot make the local test also running in the designed Ncores. The local test to have the consistent setup with what is running on the sites is important to verify the workflows. This is a feature we need to have. 
3.) hardcode in relval_steps.py through "--nThreads" option of cmsDriver, for only those HLT/DIGI/RECO cmsDriver steps that designed to run in multicore, and MatrixInjector take this option from the cmsDriver command in each step and propagate it to the wmcontral. 

Solution 3.) is the current solution implemented. Which is the best solution I can think of so far, and the only simplest solution can fit all our need.

But now, you mention you want to keep it default at 1 for this PR, so that means if we want to use multicore for relval submission, our relval managers need to modify the codes every time to have 4 cores. 

One can of course design and implement new features in the runTheMatrix.py to specify only the nCores for given steps, but I haven't had a good design yet, and the implementation will need time. 

So, give above, what could be your suggestion to fits all our needs from both sides?

best, Hengne

**Comment by davidlt** [comment]
The potential problem is that runTheMatrix.py does look into CPU utilisation and available memory on the system, or collected metadata for workflow/step execution. Basically it doesn't have a scheduling it. I haven't look into this particular aspect of runTheMatrix.py, but we don't want to have -j 32 and end up running 32 x 4 threads and forcing machine to go offline due to lack of resources (cpu and memory).

**Comment by davidlt** [comment]
Simply put, make yourself a selection of workflows that will have some step running in multi-threaded mode. Run `runTheMatrix.py -i all -l<list_of_workflows>`, measure load averages/cpu utilisation/memory consumption of any child process (accumulate that). Do the same after your changes. If the numbers are increased, we potentially have an issue.

**Comment by hengne** [comment]
same change applied as in PR# https://github.com/cms-sw/cmssw/pull/13516
i.e. turn off muticore by default, and use -t option in runTheMatrix to specify multiCore, with HARVEST step remains 1 core.

**Comment by hengne** [comment]
please test

**Comment by fabozzi** [comment]
This seems the IB issue reported here:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3451.html

**Comment by hengne** [comment]
need to have that problem fixed and rebase once more here.

**Comment by mmusich** [comment]
@hengne do you foresee to work more on this one? Can we have this  commit https://github.com/hengne/cmssw/commit/54a7ebafc68a24eaca86ef11fad8d51b4eb94dc8 signed in https://github.com/cms-sw/cmssw/pull/13494 if this is not expected to converge quickly?

**Comment by hengne** [comment]
@mmusich sorry for my delay in #13494 .. i realized it's a mistake that I am "watching" the whole cmssw repository that the flux made me missed some important messages with @hengne inside..

**Comment by hengne** [comment]
do any body know if this issue fixed? I may rebase this PR and test again.
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3451.html

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by mmusich** [comment]
+1
for https://github.com/hengne/cmssw/commit/d3e3d2bfff3616fcc056a27acf74ca9a4dff4c65

**Pull request merged**
