### PR TITLE
bsunanda:Phase2-gem21 Add GEM geometry which will be in 2017 slice test

### PR DESCRIPTION
**Pull request by bsunanda**
During 2016 EYETS 5 super-chambers of GE11 will be inserted on -ve Z side. This is included in a new scenario for 2017 (not disturbing the present default)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna I am not sure if the additional scenario will be acceptable. I do not want to disturb the default 2017 scenario - but having additional scenario for GEM will be useful

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@bsunanda - on the second thought, they have to go to 2017 scenario, I think.

@slava77 and @davidlange6 - please, comment

**Comment by slava77** [comment]
On 11/14/16 8:53 AM, Ianna Osborne wrote:
> @bsunanda <https://github.com/bsunanda> - on the second thought, they
> have to go to 2017 scenario, I think.
> 
> @slava77 <https://github.com/slava77> and @davidlange6
> <https://github.com/davidlange6> - please, comment

Why is there a new file for ge11?
Geometry/MuonCommonData/data/PhaseII/gem11.xml
Is it a copy of an existing file?
I thought that the geometry is settled and the "right one"
(TDR_BaseLine/gem11.xml ?) should be used.


I also expect that this will go to 2017 scenario.


On a related topic: did we have the Phase-1 pixel  pilot blade in the
2016 geometry?

**Comment by davidlange6** [comment]
pretty amazing for an active member of the sim group to come with a surprise geometry change now that the geometry is finalized.
The delay incurred to include this in 2017 geometry can be proposed to the xeb and we’ll change the 810 schedule accordingly..

**Comment by calabria** [comment]
@slava77 @davidlange6 that is a new file containing only the chambers foreseen for the slice test, the design is the same of the full detector. maybe the PhaseII folder is not approriate to contain that file. Also the title of the PR is misleading... anyway no geometry was included for GE11 demonstrators until now in the 2017 scenario (reduced of full)...
@mmaggi @pietverwilligen

**Comment by davidlange6** [comment]
> On Nov 14, 2016, at 6:15 PM, Cesare <notifications@github.com> wrote:

> . anyway no geometry was included for GE11 demonstrators until now in the 2017 scenario (reduced of full)...
> @mmaggi @pietverwilligen

Right, and your months too late in proposing it..

**Comment by slava77** [comment]
On 11/14/16 9:15 AM, Cesare wrote:
> @slava77 <https://github.com/slava77> @davidlange6
> <https://github.com/davidlange6> that is a new file containing only the
> chambers foreseen for the slice test, the design is the same of the full
> detector.

Is the chamber numbering "natural" and matching the full layout or is
it agnostic of the full layout and e.g. chamber 1 here corresponds to
something else in the complete design layout?

**Comment by calabria** [comment]
as far as I know, Sunanda did not change the numbering and infact from the geometry tester the chamber numbers are preserved.

**Comment by bsunanda** [comment]
I tried to keep the numbering to be the same as the complete layout. But I do think that this one needs a full fledged validation before replacing the default 2017 scenario.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Please approve this

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
For 90x.

**Pull request closed without merging**
