### PR TITLE
Enable concurrent lumis by default in cmsDriver.py

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR suggests to enable concurrent lumis by default in cmsDriver.py when at least two streams and threads are requested. More specifically, the default value of `--nConcurrentLumis` is changed to `0`, which is then interpreted as "2 if number of streams is not 1 or if number of streams is 0 and number of threads is not 1, otherwise 1".

Consequently the forcing of concurrent lumis in the specific multi-lumi or concurrent lumi test workflows is removed (and the workflow 158.181 is removed completely because it would be equal to multithreaded 158.0). This change implies that in PR tests the multi-lumi workflows will be run without concurrent lumis, but in IBs the concurrent lumis is enabled. I hope this is acceptable.

This PR also adds an option `--nConcurrentIOVs` to cmsDriver.py as a preparatory step for enabling also concurrent IOVs enabled (in reality I enabled concurrent IOVs already, but decided to leave it to a subsequent PR because we may want to limit specific Records to 1 IOV that would need more discussion, I'd like to enable concurrent lumis sooner, and this PR alone could be enough for one discussion).

In addition, this PR removes explicit types on setting/overriding `process.options` and `process.maxEvents` that are not needed anymore.

#### PR validation:

Limited matrix  + `1302.181,1304.181,1361.181,136.8861,136.8862` runs, and the number of concurrent lumis is set properly in the configuration depending if run with many threads or not.

@Dr15Jones

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 1302.181,1304.181,1361.181,136.8861,136.8862

**Comment by makortel** [comment]
I opened this PR as "RFC" because we haven't really discussed on the strategy to enable the concurrent lumis, so this would be my proposal to start the discussion.

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
@makortel You have already tried 

> Limited matrix + 1302.181,1304.181,1361.181,136.8861,136.8862 runs, and the number of concurrent lumis is set properly in the configuration depending if run with many threads or not.

so everything should be ok.
However, since it is not urgent, I will merge this PR on Saturday morning just to minimize the impact of possible problems.

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
+1

**Pull request merged**
