### PR TITLE
RecoMTD: new class for storing variables for BTD and GNN training

### PR DESCRIPTION
**Pull request by kdeleo**
#### PR description:

This PR adds a new class to RecoMTD/TimingIDTools that stores the variables used for the training of the MTD track quality BDT and for the training of the vertex clustering GNN.

Presentation on BDT at MTD DPG:
- https://indico.cern.ch/event/1475908/#4-status-of-mtd-track-quality

Presentations on GNN at MTD DPG:
- https://indico.cern.ch/event/1475908/#5-vertex-reconstruction-with-g
- https://indico.cern.ch/event/1475908/#3-vertex-reconstruction-with-g

#### PR validation:
Example configuration added in test/mvaTrainingSaveNtuple_cfg.py

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
type mtd

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
