### PR TITLE
Pr112x Fractional Prescales L1T + HLT  and L1T uGT displaced muons

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:
backport of two PRs: 
Fractional Prescales (L1T + HLT) 
https://github.com/cms-sw/cmssw/pull/32741
and uGT emulation of displaced muons
https://github.com/cms-sw/cmssw/pull/32743

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
urgent
for the MWGR

**Comment by jfernan2** [comment]
+1
Based on the changes for the DQM package

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test with #32772

**Comment by silviodonato** [comment]
please test with #32772

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
