### PR TITLE
Apply clang-tidy and clang-format changes [LLVM 14]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Code-checks/format changes needed due to llvm 14.0.6 integration.

Equivalent to #41414.

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 13.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/heterogeneous-l2 is there any reason why not to sign this trivial PR? Please either sign or close, because I don't think this needs any discussion.
Please also notice that if you want to have the [13_0_X PR](https://github.com/cms-sw/cmssw/pull/41501) merged, you need to prepare also a backport for 13_1_X

**Comment by fwyzard** [comment]
@perrota, I do not think we foresee backporting the Alpaka work to 13.1.x, as far as I'm concerned we are interested only the master branch (for development) and in the 13.0.x branch (for data taking).

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by perrotta** [comment]
> @Perrota, I do not think we foresee backporting the Alpaka work to 13.1.x, as far as I'm concerned we are interested only the master branch (for development) and in the 13.0.x branch (for data taking).

@fwyzard since it is almost costless if we prepare all backports at once, I would consider also a backport to 13_1_X, just in case someone decides to move the data taking release to it sometime next summer (which was considered among the possible options in the cross coordination meeting when the release schedule for the year was decided)

**Comment by fwyzard** [comment]
ok... will do

**Comment by fwyzard** [comment]
#41556

**Pull request merged**
