### PR TITLE
Improve parameters handling and output from conditions upload_script_v2

### PR DESCRIPTION
**Pull request by Dres90**
#### PR description:

Client Script for conditions upload_V2 improvements:
- Handle arguments and options like v1 uploader. Improve -h to give proper details for each option.
- Display upload output directly on client

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by Dres90** [comment]
Updated client script to remove dependency on Requests module which is no longer included by default on Python 2.7.15+ instances used

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
