### PR TITLE
DQM-related cleanup by clang-tidy (master branch)

### PR DESCRIPTION
**Pull request by fwyzard**
Apply clang-tidy 4.0.1 cleanup

Enabled checks:
  - boost-use-to-string
  - cppcoreguidelines-no-malloc
  - google-build-explicit-make-pair
  - misc-inefficient-algorithm
  - misc-string-compare
  - misc-uniqueptr-reset-release
  - modernize-avoid-bind
  - modernize-deprecated-headers
  - modernize-loop-convert
  - modernize-make-shared
  - modernize-make-unique
  - modernize-pass-by-value
  - modernize-redundant-void-arg
  - modernize-replace-auto-ptr
  - modernize-shrink-to-fit
  - modernize-use-auto
  - modernize-use-bool-literals
  - modernize-use-emplace
  - modernize-use-equals-default
  - modernize-use-equals-delete
  - modernize-use-nullptr
  - modernize-use-override
  - modernize-use-transparent-functors
  - modernize-use-using
  - performance-faster-string-find
  - performance-for-range-copy
  - performance-implicit-cast-in-loop
  - performance-inefficient-string-concatenation
  - performance-type-promotion-in-math-fn
  - performance-unnecessary-copy-initialization
  - performance-unnecessary-value-param
  - readability-container-size-empty
  - readability-redundant-string-cstr
  - readability-static-definition-in-anonymous-namespace
  - readability-uniqueptr-delete-release

See http://releases.llvm.org/4.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html for details.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
These are the same changes as the first commit of #21652.
The idea is that if this is merged, the review of the other changes in #21652 might be clearer.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
