### PR TITLE
HLT menu fixes (11_2_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu fixes
Based on CMSSW_11_2_3

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #33176 
Bug-fix and recent GT updates of Ecal SC ES modules.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #33176

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
