### PR TITLE
Run3-hcx253 Make additional tests for DetId setting in SIM/RECO

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

There was doubt about DetId for comparison between RecHit ID's with those from calibration constants. Some tests are introduced at the level of geometry/topology as well as in numbering schemes to test these 

#### PR validation:

Utilize specific cfg files in the test directories of Geometry/HcalTowerAlgo and SimG4CMS/Calo

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
