### PR TITLE
Update relval_standard.py

### PR DESCRIPTION
**Pull request by wouf**
5TeV Hydjet settings was added

### CODE REVIEW

**Comment by franzoni** [comment]
hello @wouf  thanks for this. 
in relval_standard.py, can you please leave wf 140 mapped to the runI workflow and introduce a new wf number for the runII ? That'll make operations easier to handle. Otherwise the PR is fine (I'll +1 it as soon as you address).
Please interact with @kkrajczar and @mandrenguyen for a proposal on how/when to phase out the runI form the  relvals in production and phase in the new runII workflow.
Cheers, g

**Comment by wouf** [comment]
Hello @franzoni  I set it 145. Is it ok for You?

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by franzoni** [comment]
+1
can you please agree wtih @kkrajczar if/when to phase out the run1 HIN full sim workflows used in production of relvals for release validation, to replace them with the run2 ones ?
An email to cms-PPD-PdmV-val-admin@cern.ch addressing @hengne would be useful. Thanks !

**Comment by davidlange6** [comment]
+1

**Pull request merged**
