### PR TITLE
Run2-hcx159 Correct bug affecting several special cases for getPosition and getClosestCell

### PR DESCRIPTION
**Pull request by bsunanda**
It affects Plan1 geometry as well as BH geometry for specific ieta values

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
50k single-pion MC test (with current 2017 = "Plan1" HCAL) shows no any difference w/wo this PR -

https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/94X_PR20976_vs_94X_SinglePi/

Plot "RecHits hE (GeV) vs ieta R = 0.3 Cone" explicitly involves "getPosition" in question.

**Comment by bsunanda** [comment]
@ianna @civanch Can you approve this PR?

**Comment by ianna** [comment]
@slava77 - FYI:
* Reco comparison results: 180 differences found in the comparisons

**Comment by ianna** [comment]
@bsunanda and @abdoulline - I wonder why nearly half of TrackingParticle tests report failure?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-19-1100+20976/23215/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1V.html

**Comment by bsunanda** [comment]
@ianna I cannot say about TrackingParticles but without these changes the geometry tests for HCAL fails. So please approve this

**Comment by davidlange6** [comment]
@ianna - the pixel 2017 comparisons differ due to buggy dqm code (that apparently is already not supported)

otherwise, it looks like the differences are only seen in 2019 workflows (eg, after LS2 barrel upgrade)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
