### PR TITLE
BackPort DeepCSV Template

### PR DESCRIPTION
**Pull request by tiwariPC**
This PR includes:

- Back porting of following PRs to 90X:
  - [https://github.com/cms-sw/cmssw/pull/18515](url)
    - DeepNNTagInfoProducer.cc has been templated to work for pf as well as calo jets. Required config files in python directory were added.
  - [https://github.com/cms-sw/cmssw/pull/18315](url)
    - DeepCMVA in the RECO Default content
    - DeepCSV training for Phase I: removes the probcc discriminators and changes treatment of default values

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
#18515 (in the master) is now submitted to 92X
Please don't forget to explicitly make a 91X version of it, if needed

**Comment by JyothsnaKomaragiri** [comment]
@perrotta we need #18515 explicitly in 91X as well.

**Comment by tiwariPC** [comment]
Please add the file following this pull request 
https://github.com/cms-data/RecoBTag-Combined/pull/5

**Comment by tiwariPC** [comment]
I tested it locally, it worked after including DeepCSV_PhaseI.json file manually. If possibel please include this file for testing

**Comment by slava77** [comment]
I see "+phase1Pixel.toModify" and similar in default reco configs for deep NN tags. RECO changes in 90X are not allowed.
Please modify the PR to keep the standard workflows unchanged.

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
We expect that either today or within a few days HLT will stop using 90X for trigger developments.
This PR is likely not needed in this case.
Please clarify if you have other needs that require a 90X PR.
Thank you.

**Comment by JyothsnaKomaragiri** [comment]
@slava77 Thanks. We also learnt that HLT will switch to 91X. 
So we do not require to work on this PR.

**Comment by slava77** [comment]
@JyothsnaKomaragiri @tiwariPC 
please close this PR if it is indeed not necessary

**Pull request closed without merging**
