### PR TITLE
get rid of CMS deprecation warnings in some `Cond*` packages

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+1
 * Jenkins tests pass
 * unit tests all good

**Comment by perrotta** [comment]
+1

**Comment by qliphy** [comment]
@mmusich   This PR seems to bring some issue in IB.  Would you please have a check?

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_X_2021-11-22-2300/pyRelValMatrixLogs/run/136.73_RunSingleMu2016B+RunSingleMu2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSingleMu_HIPM+HARVEST2016_L1TMuDQM/step4_RunSingleMu2016B+RunSingleMu2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSingleMu_HIPM+HARVEST2016_L1TMuDQM.log#/41-41

---
An exception of category 'iGetter Error' occurred while
   [0] Processing global end LuminosityBlock run: 274199 luminosityBlock: 77
   [1] Calling method for module SiPixelCertification/'sipixelCertification'
Exception Message:
ME Pixel/EventInfo/reportSummary was requested but not found.

**Comment by mmusich** [comment]
@qliphy I don't think this is related.

**Comment by qliphy** [comment]
@mmusich  I checked again as following and got the same results:

cmsrel CMSSW_12_2_X_2021-11-22-1100
cd CMSSW_12_2_X_2021-11-22-1100/src
runTheMatrix.py -l 136.73 --job-reports -t 4 --ibeos
and I got 
1 1 1 1 tests passed, 0 0 0 0 failed

However, I got an error if including this PR:
cmsrel CMSSW_12_2_X_2021-11-22-1100
cd CMSSW_12_2_X_2021-11-22-1100/src
git cms-merge-topic 36203
scram b -j11
runTheMatrix.py -l 136.73 --job-reports -t 4 --ibeos
1 1 1 0 tests passed, 0 0 0 1 failed

And the error message shown in:
step4_RunSingleMu2016B+RunSingleMu2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSingleMu_HIPM+HARVEST2016_L1TMuDQM.log

----- Begin Fatal Exception 23-Nov-2021 10:49:05 CET-----------------------
An exception of category 'iGetter Error' occurred while
   [0] Processing global end LuminosityBlock run: 274199 luminosityBlock: 77
   [1] Calling method for module SiPixelCertification/'sipixelCertification'
Exception Message:
ME Pixel/EventInfo/reportSummary was requested but not found.
----- End Fatal Exception -------------------------------------------------

**Comment by mmusich** [comment]
@qliphy it doesn't seem likely, none of the modules I touched is run in relvals.

**Comment by mmusich** [comment]
I tried the same and for me also  CMSSW_12_2_X_2021-11-22-1100 is failing:
```console
   106	11:14	cmsrel CMSSW_12_2_X_2021-11-22-1100
   107	11:14	cd CMSSW_12_2_X_2021-11-22-1100/src
   109	11:14	cmsenv
   111	11:14	runTheMatrix.py -l 136.73 --job-reports -t 4 --ibeos
   113	11:32	more 136.73_RunSingleMu2016B+RunSingleMu2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSingleMu_HIPM+HARVEST2016_L1TMuDQM/step4_RunSingleMu2016B+RunSingleMu2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSingleMu_HIPM+HARVEST2016_L1TMuDQM.log
   ```
gets me 
   ```
   %MSG-s LegacyModules:  AfterModConstruction 23-Nov-2021 11:31:30 CET pre-events
The following legacy modules are configured. Support for legacy modules
is going to end soon. These modules need to be converted to have type
edm::global, edm::stream, edm::one, or in rare cases edm::limited.
  AlcaBeamMonitorClient AlcaBeamMonitorClient
  SiStripDaqInfo siStripDaqInfo
  SiStripDcsInfo siStripDcsInfo
  SiStripCertificationInfo siStripCertificationInfo
  DQMMessageLoggerClient DQMMessageLoggerClient
  DQMFEDIntegrityClient dqmFEDIntegrity
%MSG
23-Nov-2021 11:31:32 CETSuccessfully opened file file:step3_inDQM.root
%MSG-w FastTimerServiceClient:   FastTimerServiceClient:dqmFastTimerServiceClient@endLumi  23-Nov-2021 11:31:35 CET Run: 274199 Lumi: 77
no lumiVsLS ME is available in HLT/LumiMonitoring
%MSG
%MSG-w FastTimerServiceClient:   FastTimerServiceClient:dqmFastTimerServiceClient@endLumi  23-Nov-2021 11:31:35 CET Run: 274199 Lumi: 77
no puVsLS ME is available in HLT/LumiMonitoring
%MSG
%MSG-w FastTimerServiceClient:   FastTimerServiceClient:dqmFastTimerServiceClient@endProcessBlock  23-Nov-2021 11:31:37 CET post-events
no lumiVsLS ME is available in HLT/LumiMonitoring
%MSG
%MSG-w FastTimerServiceClient:   FastTimerServiceClient:dqmFastTimerServiceClient@endProcessBlock  23-Nov-2021 11:31:37 CET post-events
no puVsLS ME is available in HLT/LumiMonitoring
%MSG
DQMFileSaver::globalEndRun()
----- Begin Fatal Exception 23-Nov-2021 11:31:45 CET-----------------------
An exception of category 'iGetter Error' occurred while
   [0] Processing global end LuminosityBlock run: 274199 luminosityBlock: 77
   [1] Calling method for module SiPixelCertification/'sipixelCertification'
Exception Message:
ME Pixel/EventInfo/reportSummary was requested but not found.
----- End Fatal Exception -------------------------------------------------

```

**Comment by qliphy** [comment]
Thanks @mmusich  It seems the test depends on the node.  For some it works for others not.
Sorry for the noise. Let's wait for the new IB outcome.

**Comment by qliphy** [comment]
> @qliphy There is a fix for this issue #36218.

thanks @sroychow

**Pull request merged**
