### PR TITLE
[ROOT6] RPageSinkFile is now in ROOT::Experimental::Internal namespace

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

RPageSinkFile was moved to a different namespace in https://github.com/root-project/root/pull/14646 .

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
Testing here: https://github.com/cms-sw/cmsdist/pull/9025

**Comment by iarspider** [comment]
please test for CMSSW_14_1_X

**Comment by rappoccio** [comment]
+1

**Comment by aandvalenzuela** [comment]
Hello @iarspider, it seems this PR broke ROOT6 IBs [CMSSW_14_1_ROOT6_X_2024-02-21-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_ppc64le_gcc12/www/wed/14.1.ROOT6-wed-23/CMSSW_14_1_ROOT6_X_2024-02-21-2300)

**Pull request merged**
