### PR TITLE
Run2-hcx142 Make codes compatible with current HCAL geometry

### PR DESCRIPTION
**Pull request by bsunanda**
The codes used for isolated charged particle in calibration or in the HLT makes use of HCAL geometry which needs updating because of Plan 1 version of HCAL (old access method would not work).

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Can you review and approve this PR?

**Comment by lpernie** [comment]
Hi @bsunanda , could you also add a description for the PR?

**Comment by bsunanda** [comment]
@lpernie added a description

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
