### PR TITLE
Nano modifiers106

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of https://github.com/cms-sw/cmssw/pull/31109
backport of https://github.com/cms-sw/cmssw/pull/32463
In addition adapt sequences to use the nanoAOD_106Xv2 to read mini made with run2_miniAOD_UL modifier

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by chayanit** [comment]
please abort

**Comment by chayanit** [comment]
PS. it seems the test never started so I aborted it

**Comment by mariadalfonso** [comment]
code-checks

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Pull request merged**
