### PR TITLE
Run3-gex39 Fix a bug in the zdcmaterials.xml file and also remove unnecessary materials

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix a bug in the zdcmaterials.xml file and also remove unnecessary materials

#### PR validation:

Tested using a script in Geometry/ForwardCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

May be needed to backport to 11_2_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , you likely need to make backport of this PR to 11_2

**Comment by bsunanda** [comment]
@civanch I prefer if this is back ported. But do not have a very strong view.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Thanks for the clean-up.

**Pull request merged**
