### PR TITLE
DropBox Metadata: document adding HP beamspot by run

### PR DESCRIPTION
**Pull request by franzoni**
+ the prompt calibration loop will host soon a second workflow to measure the beam spot which will use a high rate (80 Hz) of JetHT -like events from a novel dedicate stream
+ this new workflow will, like the existing beamspot PCL workflow, produce measurements per run as well as results with IOV's that fragment the runs
+ in this PR we document the inclusion in DB of the DropBox Metadata that will steer the release to the conditions database of the beamspot results by run

These changes don't affect any of the standard sequences.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
