### PR TITLE
TECRing7 +/- 1.33 mm scenarios added

### PR DESCRIPTION
**Pull request by eavdeeva**
backport of 7070
#7070

TECRing7 plus and minus 1.33 mm Scenarios added (plain TECRing7-moved scenarios and TECRing7+LS1BPixRepair)

### CODE REVIEW

**Comment by mmusich** [comment]
@eavdeeva please rebase to last IB

**Comment by diguida** [comment]
@eavdeeva ping
Please rebase to latest IB,
We will include it in the 53X to be built soon

**Comment by diguida** [comment]
@eavdeeva ping
In this release cycle, I do not think you need this fix for TEC R7. If this is not the case, please rebase, otherwise close it.

**Comment by mmusich** [comment]
-1

**Pull request closed without merging**
