### PR TITLE
Special L1T cleanup for HLT (10_0_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Special L1T cleanup for HLT (10_0_X)
Based on 10_0_3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #22557

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
