### PR TITLE
Fix to enable hpsPFTauDiscriminationByDeadECALElectronRejection in run2 reminiAODs

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
Changes to fix the master/11_2_X-related part of https://github.com/cms-sw/cmssw/issues/31015 issue:
* Rerun the anti-electron-in-deadECal tauID with any of  `run2_miniAOD_80XLegacy`, `run2_miniAOD_94XFall17`, `run2_miniAOD_UL` re-miniAOD modifiers to enable desired behaviour with leading track extrapolation to the ECal surface.

Introduced changes are expected to:
* not change output when run for non-reminiAOD eras/modifiers,
* modify considered tauID with any of  `run2_miniAOD_80XLegacy`, `run2_miniAOD_94XFall17`, `run2_miniAOD_UL` re-miniAOD modifers.

#### PR validation:

`runTheMatrix.py -l limited -i all` successful

Checks with custom configurations for miniAOD production (with cmsDriver) that setups with considered modifiers are as expected.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
> not store considered tauID within patTaus for `run2_miniAOD_80XLegacy` and `run2_miniAOD_94XFall17` eras.

why not?
I expect that we should aim to provide all the best available discriminants for all available inputs.

**Comment by mbluj** [comment]
> 
> 
> > not store considered tauID within patTaus for `run2_miniAOD_80XLegacy` and `run2_miniAOD_94XFall17` eras.
> 
> why not?
> I expect that we should aim to provide all the best available discriminants for all available inputs.

I think we want to store it in miniAOD only when no old miniAOD era is setup to keep miniAOD produced with those legacy eras unchanged. Is it incorrect?

**Comment by slava77** [comment]
> I think we want to store it in miniAOD only when no old miniAOD era is setup to keep miniAOD produced with those legacy eras unchanged. Is it incorrect?

sorry, with so many negations, I'm not sure I understand.
I expect that in the master branch miniAOD we aim to produce as complete and as similar output as possible for all re-miniAOD variants (all run2_miniAOD_\* modifiers) and they should be as close as possible to the latest miniAOD made on AOD inputs created from scratch.

**Comment by mbluj** [comment]
> 
> 
> > I think we want to store it in miniAOD only when no old miniAOD era is setup to keep miniAOD produced with those legacy eras unchanged. Is it incorrect?
> 
> sorry, with so many negations, I'm not sure I understand.
> I expect that in the master branch miniAOD we aim to produce as complete and as similar output as possible for all re-miniAOD variants (all run2_miniAOD_* modifiers) and they should be as close as possible to the latest miniAOD made on AOD inputs created from scratch.

Sorry for not clear answer.
My expectation was different: I thought that with master we want reproduce what is present in different re-miniAOD variants with older releases. For new variants I would expect either new or no modifiers. I can change this PR if it is what is indeed a demanded behaviour.

**Comment by slava77** [comment]
> Sorry for not clear answer.
> My expectation was different: I thought that with master we want reproduce what is present in different re-miniAOD variants with older releases. For new variants I would expect either new or no modifiers. I can change this PR if it is what is indeed a demanded behaviour.

I guess we are in a bit of a mix for tau miniAOD made from different AOD inputs.
Perhaps this discussion can be a reason for a follow up to simplify and streamline the (re)miniAOD setup for tau in the master branch.
IIRC, there were no practical use cases so far for a master branch or the latest production release to be able to read the old production AOD and run old version of miniAOD on top of it aiming to produce the same result that could be trivially made by running the code in the old release.
This is at least the case for reco/miniAOD.

What I described above (https://github.com/cms-sw/cmssw/pull/31047#issuecomment-670576326)  is the ultimate goal to have the latest-greatest (re)miniAOD regardless of the version of the AOD input; the modifiers are added to adjust the sequences/configuration where the AOD input differs.
The modifiers are added still in a way to minimize recomputation of existing data stored in AOD for parts of products that are expected to have no changes
(instead of, e.g., bluntly re-running all of the tau reco from AOD; similarly, jets read from AOD are not reclustered in re-miniAODs).
We were probably not always consistent with the "latest-greatest" design setup when backports were introduced and there was a competing need to backport just the minimal update of some new/fixed variable.
Also, when a new development was added in the master, the old "optimizations"  to remove recomputations managed by the modifiers were apparently not always updated.
As a result, by virtue of the old production release requirement, the master version ended up applying the same minimal changes and eventually diverging from the goal of delivering the best/latest setup for the latest release in a coherent way with (re)miniAOD made from other  older AOD input variants.

So, if the above makes sense, at least for this PR, let's simplify and provide the latest variant of dead ECAL discriminant for all reminiAOD modifier cases (where we know that the AOD input does not have the right/best value of the discriminant).

**Comment by mbluj** [comment]
@slava77 thanks for your explanation. It makes sense to me; this PR will be updated.

**Comment by mbluj** [comment]
PR updated, its description adjusted.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31047	16c5230 
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show differences only in the slimmedTaus in tauID values corresponding to the deadECAL discriminant; as expected, the difference appears in the re-miniAOD workflow for 2017. 
    - manual check of the jenkins outputs shows that re-miniAOD 2018 workflow also has event-by event differences in againstElectronDeadECAL (which apparently cancel out in the histogram of this boolean variable).

**Comment by slava77** [comment]
@silviodonato @qliphy 
this is missing just the analysis signature.
May I suggest to bypass it here.
Thank you.

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
