### PR TITLE
Improvements on `SiPixelLorentzAngle` PCL workflow: layer-dependent cluster size cut and output maps 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR collects a series of improvements coming from the commissioning of the `SiPixelLorentzAngle` PCL workflow being commissioned at https://github.com/dmwm/T0/pull/4635 and builds on top of PRs https://github.com/cms-sw/cmssw/pull/36565 and https://github.com/cms-sw/cmssw/pull/36538:
   * adds output LorentzAngle maps to `SiPixelLorentzAnglePCLHarvester` (6f7e47f064bfe050d983032e3ee7e06c19cd3e09 and ea87669d60f5326bd00666ae121f0f1805ffc621)
   * layer-dependent cluster y-size cut in `SiPixelLorentzAnglePCLWorker` (e0df5ae8f661a7751a60f7b7d997d29737f6b7e5)
   * add `SiPixelLorentzAngleFullMapCompare` to Pixel Payload Inspector (6dcc84e14c7a25e6c70d017d59c25ddc3ed15aaf), triggers also DQM signature

#### PR validation:

Privately run 

```console
 cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiPixelLorentzAngle --conditions 121X_dataRun3_Express_TIER0_REPLAY_Run2_v1 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Tier0_REPLAY_2021-SiPixelCalSingleMuon-Express-v1/ALCARECO' --customise_commands='process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.TriggerResultsTag = cms.InputTag ( "TriggerResults","","HLT" ) ; process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.HLTPaths = ["*"]' --nThreads=4 
```

followed by:

```console
 cmsDriver.py stepHarvest -s ALCAHARVEST:SiPixelLA --conditions 121X_dataRun3_Express_TIER0_REPLAY_Run2_v1 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiPixelLorentzAngle.root -n -1
```

For what concerns the PI update (6dcc84e14c7a25e6c70d017d59c25ddc3ed15aaf), here's an example of plot obtainable (using the results of the Tier-0 replay):

badaa251-0920-4125-a57a-99d80cf368f4

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

WIll be backported to `CMSSW_12_2_X`

### CODE REVIEW

**Comment by tvami** [comment]
urgent
 * @cms-sw/orp-l2  this is the PR I just mentioned

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+1
 * changes as expected: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-02-01-1100+401fce/48158/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5+ALCAHARVD7/AlCaReco_SiPixelLorentzAngle_SectorMonitoring.html 
 * every other diff is in MsgLogger only

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
