### PR TITLE
Better era imports

### PR DESCRIPTION
**Pull request by kpedro88**
This PR addresses ~90% of the instances of importing `Configuration.StandardSequences.Eras`, replacing those imports with the modifier-specific cff files now available. Most of the edits were made automatically using a Python script, with a few corner cases fixed by hand afterward.

Remaining types of Era imports still to be dealt with:
1) In various Tracking cff files, there is a call to `getattr(eras,era)` in a general loop.
2) `cmsRun` configs generated by `cmsDriver` use the import to initialize the `cms.Process` object. (Most of the tracked configs are stored in `test` directories, so aren't picked up by checkdeps.)
3) Only in Configuration/DataProcessing, `import Configuration.StandardSequences.Eras as eras`.

These special cases of imports should probably be addressed by someone who understands the expected function of the code.

This PR is going to touch a huge number of categories, but I would appreciate merging it quickly once it's confirmed not to cause any regressions, in order to avoid never-ending rebases. We should start enforcing the new way of importing specific modifiers in open PRs. I tested this PR using the short matrix in the latest IB and all tests passed.

attn: @davidlange6, @Dr15Jones, @slava77

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Since the bot ran out of tags:
@HuguesBrun, @ferencek, @OlivierBondu, @trocino, @rociovilar, @Sam-Harper, @barvic, @wmtan, @GiacomoSguazzoni, @rafaellopesdesa, @tocheng, @VinInn, @bellan, @nhanvtran, @gkasieczka, @rovere, @deguio, @schoef, @mschrode, @idebruyn, @ptcox, @richard-cms, @nickmccoll, @battibass, @gbenelli, @wddgit, @JyothsnaKomaragiri, @mverzett, @dkotlins, @wmtford, @cbernet, @gpetruc, @matt-komm, @mariadalfonso, @pvmulder, @bachtis this is something you requested to watch as well.

**Comment by slava77** [comment]
@kpedro88 
which tests have passed, actually? Did you see that the matrix ran, or did you check comparisons as well?

Please check expanded configs in several standard workflows to confirm that your changes provide identical results.

**Comment by kpedro88** [comment]
@slava77 I saw that all workflows in the short matrix ran to completion with no errors. I was planning to rely on the comparisons from the bot. Is there a way that I can run the comparison generation script myself?

**Comment by slava77** [comment]
comparisons are not enough.
There are many things that are not monitored.
So, the best check is the expanded configuration (python dump)

We post a link to Reco tools in every RECO/AT meeting.
comparisons are described in https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Compare_outputs_FWLite_style and a similar DQM.
If you want to run RelMon-based comparisons, you can find the individual wflow scripts in the cms-bot outputs (next to the output directory)

**Comment by kpedro88** [comment]
Ah, I see what you mean now. I can write a script to call edmConfigDump on everything and diff vs. a clean IB.

**Comment by makortel** [comment]
> 1) In various Tracking cff files, there is a call to getattr(eras,era) in a general loop.

I can take care of this (after this PR gets merged).

**Comment by kpedro88** [comment]
@makortel thanks! (the second commit in this PR shows which files have that usage)

**Comment by kpedro88** [comment]
@slava77 I wrote a script to run `edmConfigDump` on all the .py files generated by the short matrix in my working area and in a clean IB `CMSSW_8_1_X_2016-09-27-1100`. I then ran a script to `diff` each pair of config dumps. The diffs showed that all the dumps are identical. (I also checked a few random ones by hand to confirm.)

**Comment by slava77** [comment]
On 9/27/16 1:32 PM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> I wrote a script to run
> |edmConfigDump| on all the .py files generated by the short matrix in my
> working area and in a clean IB |CMSSW_8_1_X_2016-09-27-1100|. I then ran
> a script to |diff| each pair of config dumps. The diffs showed that all
> the dumps are identical. (I also checked a few random ones by hand to
> confirm.)

Nice.
Thank you for checking.

**Comment by Dr15Jones** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by kpedro88** [comment]
Comparisons look good to me at a glance.

Again, would prefer to merge quickly to avoid conflicts popping up... (this will also make it quicker to test any other PRs that modify Era-related code)

**Comment by davidlange6** [comment]
I agree. All - any additional checks needed beyond what can be done over the next few hours (eg, as to merge by the next IB)?

**Comment by davidlange6** [comment]
please comment if not ok even if now merged

**Comment by makortel** [comment]
(this is probably the wrong place to comment but anyway)

Interestingly, in CMSSW_8_1_X_2016-09-28-2300 after a single edit in `Configuration/StandardSequences/python/Eras.py` `git cms-checkdeps -a` still adds gazillion packages. Checking `/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-09-28-2300/etc/dependencies/pyusedby.out.gz` (where the dependence information is apparently read by `git-cms-checkdeps`), it indeed lists many files "depending" on `Eras.py`.

Are we missing something (additional) here?

**Comment by davidlange6** [comment]
i guess it will change once we have a full build of the IB instead of a patch. we’ll try to trigger a full build today

**Comment by kpedro88** [comment]
@makortel `CMSSW_8_1_X_2016-09-29-2300` was a full build. I tried modifying Configuration.StandardSequences.Eras and running checkdeps, and now it only finds 10 packages. Hurray!

```
Configuration/Applications (python)
Configuration/DataProcessing (python)
DQM/Integration (python)
DQM/TrackingMonitorSource (python)
HLTrigger/Configuration (python)
L1Trigger/L1TNtuples (python)
L1Trigger/TrackTrigger (python)
RecoTracker/IterativeTracking (python)
Validation/RecoTau (python)
Validation/RecoTrack (python)
```

**Comment by slava77** [comment]
On 9/30/16 12:52 PM, Kevin Pedro wrote:
> @makortel <https://github.com/makortel> |CMSSW_8_1_X_2016-09-29-2300|
> was a full build. I tried modifying Configuration.StandardSequences.Eras
> and running checkdeps, and now it only finds 10 packages. Hurray!
> 

nice

**Comment by makortel** [comment]
@kpedro88 Nice indeed :) I'll attack now on the remaining imports in tracking.

**Pull request merged**
