### PR TITLE
new susy GEN configuration

### PR DESCRIPTION
**Pull request by franzoni**
- as agreed at recent PPD general meeting (both fast and full sim)  https://indico.cern.ch/event/385859/
- LM1 in the process of being gotten rid of

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@duanders

**Comment by franzoni** [comment]
+1
local tests of newly introduced workflows are ok

**Comment by davidlange6** [comment]
+1

**Pull request merged**
