### PR TITLE
Migrate Ecal Validation to multi-thread

### PR DESCRIPTION
**Pull request by mengleisun**
Migrate the Validation code to multu-thread.
Involved packages:
Validation/EcalClusters 
Validation/EcalDigis
Validation/EcalRecHits

### CODE REVIEW

**Comment by mengleisun** [comment]
The error in test 4.53 doesn't seem to be caused by the migrated Validation package.

**Comment by deguio** [comment]
-1
ciao @mengleisun 
this should go to 75x first. and then backported to 74. no need to submit to 73.
ciao and thanks,
F.

**Comment by mengleisun** [comment]
ciao @deguio 
I have just sent a same PR to 75X for test. This PR under 73 can be closed.
Thank you.

cheers,
Menglei

**Comment by davidlange6** [comment]
closing the 73x cycle

**Pull request closed without merging**
