### PR TITLE
[backport] Prevent propagation of heavy neutrino by Geant4 

### PR DESCRIPTION
**Pull request by mgratti**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/33299

Needed for an MC production with B-parking conditions.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

Problems in tests are not related to this PR. There is an issue with SiPixelQuality object. Also regression is wrong in WFs 160.53

**Comment by qliphy** [comment]
+1

**Comment by mgratti** [comment]
@silviodonato, @dpiparo, @qliphy 
I have realized that, while this PR was merged almost a month ago, it was not actually integrated in the latest available 10_2_X release, CMSSW_10_2_26. Could you please comment?

**Comment by qliphy** [comment]
We will make a new 10_2_X to include this PR in next days.

**Comment by qliphy** [comment]
@mgratti  https://github.com/cms-sw/cmssw/releases/CMSSW_10_2_26_patch1  is now available.

**Comment by mgratti** [comment]
Thank you

**Pull request merged**
