### PR TITLE
Modernize several modules in TopQuarkAnalysis

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061.

Also change `PhysicsTools::Calibration::MVAComputer::getProcessors() const` to return `const` pointers to contained `VarProcessor` processor objects as required by ESProduct policies.

#### PR validation:

Unit tests of `TopQuarkAnalysis/TopEventSelection`, `TopQuarkAnalysis/TopEventProducers`, and `TopQuarkAnalysis/TopJetCombination` succeed when run with https://github.com/cms-sw/cmssw/pull/35588.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
+1
* esconsumes migration, new edanalyzer migration for MVAcomputer
* unit tests passed

**Comment by tvami** [comment]
+db
 * Jenkins tests pass
 * PR in line with the description

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
