### PR TITLE
add timing VS lumi (for HLT monitoring)

### PR DESCRIPTION
**Pull request by mtosi**
the main goal is to have this update in 80x for monitoring the timing vs lumi @ p5

I added a DQM source which produce the inst lumi vs LS
which has to be run w/in HLT menu
its timing should be ~neglible
hltlumimonitoring

then, the timing VS lumi is done by the FastTimerServiceClient

the current configuration makes the lumi profile by using SCAL,
but it can be configured in order to make use of the pixel-based luminosity as well

### CODE REVIEW

**Comment by fwyzard** [comment]
@mtosi , please see the comments at #14938

**Comment by fwyzard** [comment]
also, once you have updated the code, could you squash all the changes in only one or two commits ?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
I do not think they are related to this PR

**Comment by perrotta** [comment]
please test
(it was a DAS error, unrelated to this PR)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Merge conflicts - please resolve.

**Comment by Martin-Grunewald** [comment]
@mtosi 
Mia, please realise that action from YOUR side is needed on this PR!

**Comment by Martin-Grunewald** [comment]
@mtosi 
Here are still merge conflicts claimed by github!

**Comment by mtosi** [comment]
thanks martin
sorry for the delay, last week I did not have time to follow this up
I'm going to do it now

**Comment by mtosi** [comment]
it should be fix, now

**Comment by Dr15Jones** [comment]
Does this need a rebase?

**Comment by slava77** [comment]
-1
needs a rebase or a fix otherwise

**Comment by mtosi** [comment]
it should be fine, now (hope so)
@dmitrijus

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
please test

**Comment by mtosi** [comment]
I think it is not related to this or

**Comment by dmitrijus** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by dmitrijus** [comment]
80x: https://github.com/cms-sw/cmssw/pull/15169#issuecomment-233401408

**Pull request merged**
