### PR TITLE
[HGCal Trigger] Fix bug in auto-encoder trigger cell normalization

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
Fixes a bug in the normalization of the trigger cells after decoding network. Modules were effectively being scaled to the MSB of the module sum, instead of preserving the total module sum.

Associated internal PR and review:
- PFCal-dev#473

#### PR validation:
Private tests in `L1Trigger/L1THGCalUtilities/test`:
```
cmsRun testHGCalL1T_RelValV11_cfg.py
cmsRun testHGCalL1T_multialgo_V11_cfg.py
```
Tested D49, D60 and D68 workflows
```
runTheMatrix.py -w upgrade -l 23234.0 --maxSteps=2 
runTheMatrix.py -w upgrade -l 28234.0 --maxSteps=2 
runTheMatrix.py -w upgrade -l 31434.0 --maxSteps=2
```
---
@dnoonan08 FYI

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
Hi @jbsauvan 
Sorry for my late response. My comments:

- Do you expect to see any difference in DQM? I don't see failure in comparison except MessageLogger
- Would you mind to fix
https://github.com/cms-sw/cmssw/blob/c198781f925250102b3df04da72f63727aee93d6/L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorAutoEncoderImpl.cc#L265-L266
as mentioned in (*). It never reads the initialization because you always have
https://github.com/cms-sw/cmssw/blob/c198781f925250102b3df04da72f63727aee93d6/L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorAutoEncoderImpl.cc#L274-L275
?

Thanks in advance.

(*)
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b6682b/16412/llvm-analysis/runStaticChecks.log

**Comment by jbsauvan** [comment]
Thanks a lot @srimanob 
This algorithm (the trigger cell energies compression using an auto-encoder) is actually not activated by default, so nothing should change in the DQM.

I'll fix the `cellU,cellV`.

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
