### PR TITLE
 GenParticles2HepMCConverter null pointer protection 10X

### PR DESCRIPTION
**Pull request by jhgoh**
10X version of PR #22440

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@perrozzi I understand that this PR is changing the event history for particle guns, are we sure that there is nothing assuming the absence of input particle on that? I would say so, no effect is seen in the output of the test...

**Comment by fabiocos** [comment]
+1

affecting only generator history for particle guns (technical fix to circumvent problems in NanoAOD creation)

**Pull request merged**
