### PR TITLE
Changes in DTDataIntegrity for Online DQM and addition of ML Occupancy Test

### PR DESCRIPTION
**Pull request by jfernan2**
Changes comprise:
A) Folders:
-FED folders with general EvtLength informacion and uROS folders with TTS values and specific uROS EvtLength
-Wheel folders with individual ROS information for RO and TDC checks across Links

B) Summary Histograms
-uROS Global errors (yet to be defined by Alvaro) plotted vs uROS based on FED: FEDXXXX_uROSSummary
-FEDEntries
-ROSummary_ WX with RO errors, NotOKFlag and TDC checks, computed over all the links of a sector

C) Full summary histograms as in the past, but now denominator takes into account specific uROS EvtLength divided by 3 since an uROS controls 3 sectors and it is not possible to distangle how many events belong to a given ROS afaiu:
-DataIntegrityTDCSummary: only using TDC Fatal bin for computation as in the past (Legacy)
-DataIntegritySummary: using Error1-4 and NotOKFlag computed over all the links of a sector
-DataIntegrityGlbSummary: as the above but including also ErrorG1-12 in the numerator (so identical to DataIntegritySummary since these errors are yet to be defined by Alvaro)

D) Others:
-DTBlockedROChannelsTest on folder 00-ROChannels still being worked out based ONLY on NotOKFlag and averaging to 6 links per chamber
-ML from Adrian on folder 01-Digi / ML (to be fully tested/tuned during collisions)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
The crash in the AddOn is not related to the changes in this PR

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Review by fabiocos — COMMENTED** [review]
Usually data files are stored in separate external packages, for tensorflow models we have such an example in RecoBTag/Combined data package. @smuzaffar @davidlange6 Do we have a strict policy about this? Here for the time being we have just one file,
@jfernan2 is it possible that we will have more models in the future?

**Comment by davidlange6** [comment]
> On Apr 23, 2018, at 1:39 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @fabiocos commented on this pull request.
> 
> Usually data files are stored in separate external packages, for tensorflow models we have such an example in RecoBTag/Combined data package. @smuzaffar @davidlange6 Do we have a strict policy about this? Here for the time being we have just one file,
> @jfernan2 is it possible that we will have more models in the future?

Yes, we should not put binary data into cmssw.

**Comment by fabiocos** [comment]
@jfernan2 could you please elaborate a bit about the use of tensorflow in this occupancy test? Do I understand correctly that this is used so far only in the online sequences, and therefore it is noit tested in any of the usual relval workflows? Was this tested standalone?

@smuzaffar in this case I think we should have a new cms-data external package. BTW I see several xml files in the DTMonitorClient package, I guess they could be moved into the external data package as well...

**Comment by jfernan2** [comment]
@fabiocos Yes, this ML test is only run at Online DQM, so not run on any relvals, however it has been extensively tested offline. Online DQM will be a first test with real data for the ML algotirthm, so we do not expect additional models
I add @AdrianAlan and @battibass as main developers/responsibles of the DT ML, they can comment further.
I see there's supposed to be a RecoBtag/Combined/data folder with the models, according to:
http://cmslxr.fnal.gov/source/RecoBTag/Combined/python/pfDeepCMVAJetTags_cfi.py#0008
but the folder is not present, so could you please give explicit instructions if our models folder is not allowed?
Thanks

**Comment by jfernan2** [comment]
@fabiocos Which xml files do you mean btw? I only see those in DQM/DTMonitorClient/test/ which are 5 year old now, coming form a CMSSW620 snapshot, I'm afraid they are obsolete and not used any longer. They were created before I joined DT, so I can't tell further.

**Comment by battibass** [comment]
@jfernan2 : from a quick look I think that the only file actually called by some DQM module is [this one](https://github.com/cms-sw/cmssw/blob/master/DQM/DTMonitorClient/test/QualityTests.xml) included in the online DQM sequences [here](https://github.com/cms-sw/cmssw/blob/master/DQM/DTMonitorModule/python/dt_dqm_sourceclient_common_cff.py#L88-L93) and used [here](https://github.com/cms-sw/cmssw/blob/master/DQM/DTMonitorModule/python/dt_dqm_sourceclient_common_cff.py#L118).

I don't think the other `QualityTest*.xml` files are used. Also I think the `*Layout.xml` files were actually used to configure an old GUI system that is used anymore, so I guess they could safely be removed.

**Comment by jfernan2** [comment]
@fabiocos @smuzaffar We have cleaned up the unused xml files after consulting DT experts. Can you please give some advice about the TensorFlow models files or review the PR as it is? Thanks

**Comment by jfernan2** [comment]
ping

**Comment by jfernan2** [comment]
@fabiocos @smuzaffar any news about this? It is not an urgent PR but we would like to have it at some point. Not sure what is the show stopper, is there anything we should do for xml files or models forlder? Thanks in advance

**Comment by fabiocos** [comment]
@jfernan2  sorry for the delay. I think that normally for data files we have a dedicated package in https://github.com/cms-data corresponding to the cmssw package. For DQM there is for instance https://github.com/cms-data/DQM-SiStripMonitorClient . So i suggest to have a cms-data DQM-DTMonitorClient package where the data files are moved. @smuzaffar What else should we add to get it working? A corresponding entry in CMSDIST, as https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_2_X/gcc630/data-DQM-SiStripMonitorClient.spec , then?

**Comment by jfernan2** [comment]
Thanks! I'm not sure how to create a new repository on cms-data, I have tried to look for info on the own git and in twikis, but it seems I have no privileges (?)

**Comment by smuzaffar** [comment]
@jfernan2 , I will take care of new repository.

**Comment by smuzaffar** [comment]
@jfernan2 , data external is available via https://github.com/cms-sw/cmsdist/pull/3977.
You need to cleanup this PR to drop occupancy_cnn_v1.pb from from the history

**Comment by jfernan2** [comment]
Done. Thanks!

**Comment by smuzaffar** [comment]
@jfernan2 , both  models/occupancy_cnn_v1.pb and DQM/DTMonitorClient/models/occupancy_cnn_v1.pb files are still part of history. Please try to collapse these commits in to one to get these files out of the history (see http://cms-sw.github.io/faq.html#how-do-i-collapse-multiple-commits-into-one ). Once you gave the new commit then force push it to your DTDQMdataIntegrity_and_ML102 branch

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#3977

**Comment by jfernan2** [comment]
@smuzaffar Thanks. I tried the instructions there but it seems the reference is still there in the history. This is what I did:
git reset --soft c7fa281
git commit --amend
(Here I was forced to do a pull: "because the tip of your current branch is behind its remote counterpart." 
git pull -a my-cmssw DTDQMdataIntegrity_and_ML102
git push my-cmssw DTDQMdataIntegrity_and_ML102

**Comment by jfernan2** [comment]
please test with cms-sw/cmsdist#3977

**Comment by jfernan2** [comment]
+1
from DQM side it is fine

**Comment by smuzaffar** [comment]
hold
@jfernan2 , please use `git reset --soft 0811eb61e66388c91980544b24cd950e5a162fbc` i.e. the commit before your changes.

**Comment by jfernan2** [comment]
thanks @smuzaffar Now I think I got it and made it right.

**Comment by smuzaffar** [comment]
@jfernan2 , No, binary files are still there in the history. I think you need to do something like this
```
git clone git@github.com:jfernan2/cmssw
cd cmssw
git checkout DTDQMdataIntegrity_and_ML102
git reset --soft 0811eb61e66388c91980544b24cd950e5a162fbc
git commit -a -m 'Changes in DTDataIntegrity for Online DQM and addition of ML Occupancy Test'
git push -f  origin DTDQMdataIntegrity_and_ML102
```
after this you should have only one commit in your DTDQMdataIntegrity_and_ML102 branch

**Comment by jfernan2** [comment]
Thanks a lot @smuzaffar 
That really worked, it seems that starting from a fresh repository is mandatory.

**Comment by smuzaffar** [comment]
unhold
thanks @jfernan2

**Comment by smuzaffar** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
________________________________________

**Comment by fabiocos** [comment]
@jfernan2 sorry, in which workflow is the external data file supposed to be used? The latest test did not used it.

**Comment by jfernan2** [comment]
@fabiocos It is only used in Online DQM at P5, that's why I started creating the backport in 10_1_X #22970 
This is related to email I sent you last week about "Hanging PRs and Online DQM"
Thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
