### PR TITLE
Update Alignment/OfflineValidation package

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

 This PR:
   * introduces `EventSetup` consumes for the `PrimaryVertexValidation` and `GeneralPurposeTrackAnalyzer` analyzers;
   * introduces a new `EDAnalyzer` to compute quickly the Distribution of the Median Residuals, outside of the all-in-one meta-tool (this is meant for fast checks at the Dataset level to make sure input data makes sense, and not for validation purposes). 
   * the classes `Phase1PixelMaps` and `PixelRegionContainers` from the Pixel Payload inspector suite are modified to make them usable outside of `CondCore/SiPixelPlugins` and are interlaced with the `EDAnalyzers` of `Alignment/OfflineValidation`

#### PR validation:

Relies on private validation of the touched modules and using the existing unit tests, which have been modified by this PR.
I provide here couple of examples of plots which can be obtained using the modifications proposed here.

| DMRs per layer | occupancy maps |
|-|-|
| DMR_y_Barrel_ByLayer | pixelBarrelEntries |

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tlampen** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild ping?

**Comment by qliphy** [comment]
+1

**Pull request merged**
