### PR TITLE
Clean up BuildFiles under TauAnalysis/

### PR DESCRIPTION
**Pull request by fwyzard**
Clean up BuildFile.xml filea with `xmllint --format`.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
> ERROR: empty variable. PR had errors - #29731.

yes this looks strange. I will check the jenkins job what went wrong

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
