### PR TITLE
enabling 2D plots for muon inner track monitoring

### PR DESCRIPTION
**Pull request by mtosi**
add 2D plots (eta vs phi) for monitoring the muon inner track

in order to have a reasonable monitoring, even for this category which generally has low stat,
(and to keep as low as possible the #bins)
I introduce new input parameters for handling the binning of 2D plots

by default they assume the same value as the 1D for back-compatibility
and only in the muon inner track configuration they have been set to a factor 1/2 w.r.t. standard

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, pleast test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Pull request merged**
