### PR TITLE
Adding vertex selections before the fit of the BeamSpot

### PR DESCRIPTION
**Pull request by francescobrivio**
Adding the necessary information to have the possibility to apply a selection on the Primary Vertices before the actual fit of the BeamSpot.
This is the backport of the 91X version.

### CODE REVIEW

**Comment by slava77** [comment]
backport of #18201

**Comment by slava77** [comment]
@cmsbuild please test

which group is the primary customer of this?
Is it needed for TSG?
@Martin-Grunewald

**Comment by perrotta** [comment]
@francescobrivio : errors are related, e.g.:

----- Begin Fatal Exception 05-Apr-2017 00:37:06 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=AlcaBeamMonitor label='AlcaBeamMonitor'
Exception Message:
MissingParameter: The required parameter 'useOnlyFirstPV' was not specified.
----- End Fatal Exception ------

 Please provide fixes.

**Comment by perrotta** [comment]
@francescobrivio : do you still need this backport to 90X?

If so, please justify here why it is needed and apply the same fixes and updates as in #18201 
If not, please close

**Comment by francescobrivio** [comment]
@perrotta yes we still need the backport.
I will implement all the fixes as in #18201

**Comment by perrotta** [comment]
The updates here do not coincide with the ones in #18201 : it is hard to review as such.
Please sinchronize the PRs in 90X and in the master (as soon as you have implemented the last adjustments requested for 91X)

**Comment by perrotta** [comment]
-1
Since #18201 got reverted in 91X, and still no fix was provided for having it back
Furthermore, this 90X version already needed to be adjusted in order to correspond to the one in the master. If the corresponding PR will be re-merged at some point in the master release, then another, cleaner backport will have to be produced (if still needed)

**Pull request closed without merging**
