### PR TITLE
HBHEgpu: add correlated noise

### PR DESCRIPTION
**Pull request by mariadalfonso**
Resynchronise gpu and cpu with recent modification of the non diagonal noise
see notes here under
`implement the modification to follow up on recent noise correlation that are important in view of the Run3 ageing`
https://github.com/cms-sw/cmssw/issues/32413

Changes expected in gpu-Run3 only.

@fwyzard @vkhristenko

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by jpata** [comment]
LGTM on the code. I ran in addition the test in
```bash
cd RecoLocalCalo/HcalRecProducers/test
cmsRun make_GPUvsCPU_HCAL_rechits.py
cmsRun make_GPUvsCPU_HCAL_plots.puy
```
and I got the following plots:

Screenshot from 2021-03-08 15-22-57
Screenshot from 2021-03-08 15-23-16

@mariadalfonso could you comment on 2dM0, is the non-diagonal feature expected? Thanks!

**Comment by jpata** [comment]
+reconstruction
- updates GPU MAHI code to correspond to the latest CPU updates
- tests confirm no reco differences, GPU code runs, CPU-to-GPU comparisons look good

**Comment by silviodonato** [comment]
+1

**Pull request merged**
