### PR TITLE
NanoAODv7 code updates [102X]

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

Backport changes for NanoAODv7 to 10_2_X.

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #29276

**Comment by peruzzim** [comment]
backport #29212

**Comment by peruzzim** [comment]
please abort

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #29276,cms-data/PhysicsTools-NanoAOD#12

**Comment by peruzzim** [comment]
@silviodonato will need updating the cms-data package also in 10_2_X

**Comment by smuzaffar** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #29276,cms-sw/cmsdist#5697

cms-sw/cmsdist#5697 is backport for data external

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #29276,cms-sw/cmsdist#5697

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #29276,cms-sw/cmsdist#5697

**Comment by peruzzim** [comment]
+xpog

**Comment by peruzzim** [comment]
everything looks ok for what I can see, I'm doing additional checks before actually launching the production but I think this can be merged together with #29276 as soon as RECO signs

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
+1
- This PR backports together #29212 (NanoAODv7 code updates), #28196 (eras for nanoAOD workflows), and all the clang based format changes interveaned since 10_2_X in the affected code
   - Rather painfull to try to compare the changes wrt the original ones
   - At least in the configuration and reco-related part the backport looks correct
- As for the backported #29212 PR, changes in reco code refer to
  - PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc, where two configuration parameters needed to fix the sign of the impact parameter were added: their default settings do not affect reco outputs
  - Modifications in RecoJets/JetProducers/plugins/BetaStarVarProducer.cc only affect nanoAOD, which is the only user of the "BetaStarPackedCandidateVarProducer" by now
- Jenkins tests show no differences in reco outputs; I assume that changes observed in the nanoAOD outputs have been implicitly considered validated by @peruzzim, while signing this PR for xpog

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
