### PR TITLE
Remove CMS deprecated warnings from L1Trigger/ConfigUtilities

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed to thread-friendly module types
- added esConsumes

#### PR validation:

Code compiles and no longer issues the warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
