### PR TITLE
Fixes for DeepDoubleX

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This PR cleans up a few issues from #30016:
* removes an unnecessary `edm::Ptr` that caused an exception when running on `packedCandidate`: `PFJet constituent is not of PFCandidate type` (reported on Mattermost)
* the new dependency on `pat::Jet` in the DeepDoubleX code was not handled properly: when running on `reco::Jet`, the `dynamic_cast` to `pat::Jet` would fail, creating a `nullptr`, which would then be passed to `commonCandidateToFeatures()`/`getDRSubjetFeatures()` for another `dynamic_cast`, leading to a segfault.
* the requirement to run only on `pat::Jet` should be reflected in `jetTools` as it is for other discriminators. I added a simple check; not sure if it's optimal or comprehensive in this case.

#### PR validation:

Ran jetToolbox several times and observed correct behavior (either runs to completion or throws `"Input is not a pat::Jet."` when expected), rather than unexpected exceptions or segfaults.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be backported to 10_6_X for those running on UL samples. Other backports can be made upon request.

attn: @andrzejnovak

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by mariadalfonso** [comment]
@kpedro88
do you think would be useful to have in 12-4 for Run3 analysis ? if Yest also backport there

**Comment by jpata** [comment]
@cms-sw/btv-pog-l2 @emilbols just to check you are aware and agree.

**Comment by soureek** [comment]
@jpata +1 from  BTV

**Comment by perrotta** [comment]
+1
- Tests are 11 days old, but still available
- The fixes are conceptually simple, I see no need to rerun the tests to refresh them

**Pull request merged**
