### PR TITLE
Adding Run 334393 as test Run for LS2  (Backport)

### PR DESCRIPTION
**Pull request by boudoul**
#### PR description:

Updating RunTheMatrix in order to use Run 334393 taken in January 2020 as test Run for LS2

#### PR validation:

runTheMatrix.py -l 138.1 --command "-n 100" is running fine

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of the master PR #28900 
reason :  11_0_X is the present data taking cycle, so better to have a backport here

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 138.1

**Comment by kpedro88** [comment]
backport of #28900

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
ping @cmsbuild

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
backport of  #28900

**Comment by silviodonato** [comment]
+1

**Pull request merged**
