### PR TITLE
Run3-gex83B Convert all SD's in SimG4CMS/ShowerLibraryProducer using the new way of initiating

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert all SD's in SimG4CMS/ShowerLibraryProducer using the new way of initiating

#### PR validation:

Tested using workflows in SimG4CMS/ShowerLibraryProducer/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , let us revert class names back.

**Pull request merged**
