### PR TITLE
Protection in HistoryBase cycle against unfulfilled condition

### PR DESCRIPTION
**Pull request by ghost**
Correct original HistoryBase code. No protection was present in case of unfulfilled condition within loop.

### CODE REVIEW

**Comment by makortel** [comment]
The proposed change reminds me of some older e-mail threads. Are you sure the fix is correct, and sufficient?

(I'm not against the fix, but I fear that it is not sufficient. The function has several other issues as well.)

**Comment by imarches** [comment]
Hi @makortel, this is the minimal fix that makes our code work (apparently correctly) on the new RECODEBUG files, as we tested on our ntuples. I agree that the code could be improved in several ways, but I'd rather leave this to some expert or, eventually, I could try to do it myself in a moment where I have more time for that. For the time being I can offer just this minimal fix.

**Comment by makortel** [comment]
@imarches Ok. But could you at least protect also the access to `*its` on line 97? I guess the simplest would be to add the following right after the loop after line 90
```
if(!flag)
  return false;
```

**Comment by imarches** [comment]
Hi @makortel thanks for the suggestion. The compact implementation of the code is implemented

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
