### PR TITLE
Fixed GenHFHadronMatcher

### PR DESCRIPTION
**Pull request by Dr15Jones**
The nanoAOD jobs were crashing in GenHFHadronMatcher because of a missing simulation parentage of a tau. This was fixed with the first commit.
Took the opportunity to modernize the module, especially since it is being used in an 8 thread job.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
backport #25026

**Comment by Dr15Jones** [comment]
please test

**Comment by zhenhu** [comment]
please test workflow 10887.0,11087.0

**Comment by Dr15Jones** [comment]
please test workflow 10887.0,11087.0

**Comment by zhenhu** [comment]
> +1
> Tested at: [0914ef2](https://github.com/cms-sw/cmssw/commit/0914ef2831d3945d31fadba3795d6f1e8670922b)
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25025/31319/summary.html

Hi @Dr15Jones , for some reason, I can not find logs for 10887.0 and 11087.0

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
