### PR TITLE
[10.2.X]Change 2018 MC GTs: TrackAl + DynInEff

### PR DESCRIPTION
**Pull request by lpernie**
###  2018 realistic scenario:
 .  [102X_upgrade2018_realistic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v9/102X_upgrade2018_realistic_v11)
.  New tracker alignment scenario
.  Consistent SiPixelDynamicInefficiency

###  2018 cosmic scenario:
 .  [102X_upgrade2018cosmics_realistic_deco_v10](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v8/102X_upgrade2018cosmics_realistic_deco_v10)
.  New tracker alignment scenario
.  Consistent SiPixelDynamicInefficiency

### CODE REVIEW

**Comment by lpernie** [comment]
Backport of #24202

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
@fabiocos @mmusich here the PR for 10.2.X

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
