### PR TITLE
Add DontCountDetsAboveNClusters 

### PR DESCRIPTION
**Pull request by rovere**
Add DontCountDetsAboveNClusters to standard cosmic seeders to ignore/exclude too noisy detids from the overall count of SiStripClusters

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

Marco, what is the expected impact?
Is this needed more for proper cosmics or for pp data taking?
If for cosmics, do we need to have this feature in 72X for MWGR etc?

**Comment by rovere** [comment]
Ciao Slava,
the effect is to reconstruct muons also in the case in which some unexpected noisy sistrip appears: basically we would ignore the clusters coming from noisy SiStrip in the overall count of clusters used to reject the event at reconstruction time.

As far as I know 7_3_1_patch2 has been used for PrompReco for 233238, and that is why I submitted PR for both 74 and 73.

It only affect the cosmic reconstruction.

There has been a rather long, private thread about this topic that I'd be happy to fully forward to you, in case you want/ask for it.

Thanks for checking, as usual.

Ciao,
M.

**Comment by slava77** [comment]
On 2/3/15 6:57 AM, Marco Rovere wrote:
> Ciao Slava,
> the effect is to reconstruct muons also in the case in which some
> unexpected noisy sistrip appears: basically we would ignore the clusters
> coming from noisy SiStrip in the overall count of clusters used to
> reject the event at reconstruction time.
> 
> As far as I know 7_3_1_patch2 has been used for PrompReco for 233238,
> and that is why I submitted PR for both 74 and 73.
> 

Ciao Marco,

Thanks for the clarification.
Now the fact of switching to 73X for data processing at T0 has
registered well in my memory.


		--slava

> It only affect the cosmic reconstruction.
> 
> There has been a rather long, private thread about this topic that I'd
> be happy to fully forward to you, in case you want/ask for it.
> 
> Thanks for checking, as usual.
> 
> Ciao,
> M.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7520#issuecomment-72645675>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by davidlange6** [comment]
@slava77 - we should try to build a release tomorrow for cruzet. Do you have issues to bring up with this PR?

**Comment by slava77** [comment]
David, this and 7521 was on Carl's list.
Carl, please update is 7521 looks good.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #7520 425a60cb710ebf99246f58ba789c13e47a0a8a4d

Very tiny code change for cosmics seeders to exclude excessively noisy detIDs from the SiStripClusters count. Jenkins tests were done on reference CMSSW_7_3_X_2015-02-01-1400, which also includes #7496. The Jenkins results show differences due to #7496, but there are no differences caused by this PR. An extended test with 1000 events for workflow 4.22 (cosmics) showed no differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
