### PR TITLE
Added 2-D histogram of trigger tower flags vs Et; Revert FEStatus to run based: getting LS reports from FEMap instead.

### PR DESCRIPTION
**Pull request by tanmaymudholkar**
This branch departs from 8.0.20, and contains the commits already proposed in #16112 and merged in 8.0.21; there shouldn't be a conflict while merging this PR into CMSSW_8_0_X branch. The main features:
- Add a new 2-D histogram to show the correlation between TT flags and Et deposited in a given trigger tower.
  - It is a backport of #16206 in CMSSW_8_1_X.
- Fix issue in offline DQM where FE Status Flag plots only display stats from last LS
  - Harvesting step in offline DQM causes LS-based plots to only keep stats from the last LS due to multi-threading, which affects all FE Status Flag plots in offline DQM since the introduction of PR  #15411 (starting `CMSSW 8_0_18` or ~run 279498).
  - Revert changes introduced in that PR: set `ecalRawDataClient.MEs.QualitySummary` and `ecalRawDataTask.MEs.FEStatus` to be run-based again.
  - To maintain functionality of GOOD channel reporting introduced in that PR, get RawData info instead from `ecalRawDataTask.MEs.FEStatusErrMapByLumi` (introduced later, in PR #16112) which, by design, is already reset every LS, and is filled independently of the affected MEs above.
  - Originally in #16304: the new commit https://github.com/cms-sw/cmssw/pull/16205/commits/13c7189766c368143134af7326c8d73c702e481a is a cherry-pick of https://github.com/cms-sw/cmssw/pull/16304/commits/f306f23eb803a619f46e30f1c1b3131637f0d20c so it can be used online.
  - It is a backport of #16305 in CMSSW_8_1_X.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1
Did you cherry picked the commits? Or was it a merge-topic?
Once that older PR gets merged - we will see if this one gets a conflict :)

**Comment by tanmaymudholkar** [comment]
Hi @dmitrijus , I did a cherry-pick. (started out from base 8_0_20, cherry-picked both commits in #16112 , and added my own commit on top). I'll keep an eye on this, and if there is a conflict I can make a new PR -- thanks for letting me know.

**Comment by tanmaymudholkar** [comment]
Just for some additional background related to the update in this PR: a rather urgent fix was implemented by ECAL DQM which needed to be patched on the deployment server. In order to avoid conflicts, in consultation with @diguida , I updated this PR.

**Comment by diguida** [comment]
@tanmaymudholkar @dmitrijus to be crystal clear: the new commit https://github.com/cms-sw/cmssw/pull/16205/commits/13c7189766c368143134af7326c8d73c702e481a is a cherry-pick of https://github.com/cms-sw/cmssw/pull/16304/commits/f306f23eb803a619f46e30f1c1b3131637f0d20c included in #16304 . Given that this branch departs fro 8.0.20, it can me used online.

**Comment by diguida** [comment]
@tanmaymudholkar can you please update the title of the PR to be like this:

Added 2-D histogram of trigger tower flags vs Et; Revert FEStatus to run based: getting LS reports from FEMap instead.

and the description:
This branch departs from 8.0.20, and contains the commits already proposed in #16112 and merged in 8.0.21;  there shouldn't be a conflict while merging this PR into CMSSW_8_0_X branch. The main features:

- Add a new 2-D histogram to show the correlation between TT flags and Et deposited in a given trigger tower.
 - It is a backport of #16206 in CMSSW_8_1_X.
- Fix issue in offline DQM where FE Status Flag plots only display stats from last LS
 - Harvesting step in offline DQM causes LS-based plots to only keep stats from the last LS due to multi-threading, which affects all FE Status Flag plots in offline DQM since the introduction of PR #15411 (starting `CMSSW 8_0_18` or ~run 279498).
 - Revert changes introduced in that PR: set `ecalRawDataClient.MEs.QualitySummary` and `ecalRawDataTask.MEs.FEStatu`s to be run-based again
 - To maintain functionality of GOOD channel reporting introduced in that PR, get RawData info instead from `ecalRawDataTask.MEs.FEStatusErrMapByLumi` (introduced later, in PR #16112) which, by design, is already reset every LS, and is filled independently of the affected MEs above.
 - Originally in #16304: the new commit https://github.com/cms-sw/cmssw/pull/16205/commits/13c7189766c368143134af7326c8d73c702e481a is a cherry-pick of https://github.com/cms-sw/cmssw/pull/16304/commits/f306f23eb803a619f46e30f1c1b3131637f0d20c so it can be used online.
 - It is a backport of #16305 in CMSSW_8_1_X.

**Comment by tanmaymudholkar** [comment]
@diguida Thanks for the suggestion. I have updated the title and description of the PR as you requested. Sorry for the confusion!

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
To clarify, this PR is the backport of https://github.com/cms-sw/cmssw/pull/16305 and https://github.com/cms-sw/cmssw/issues/16206

**Comment by davidlange6** [comment]
+1

**Pull request merged**
