### PR TITLE
[llvm14][Sim] Fixed set but not used variables warnings

### PR DESCRIPTION
**Pull request by smuzaffar**
In CLANG IBs ( with llvm 14), we see few warnings about variable set but not used. This PR fixes few of those for `Sim` packages. I also cleanup some dead code which was not doing any thing, please let me know if this code should be deleted instead of commenting out.

### CODE REVIEW

**Comment by civanch** [comment]
I will try to study R-hadron hadronic physics code (which is really messy). @bsunanda , can you, please, have a look into test codes for forward detectors? In general, it is OK to remove commented lines. What I am not sure is Bsc modifications.

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@civanch this PR comments out a lot of (by now dead) code.
Wouldn't it be preferable to clean it up and remove these commented out parts completely from the code?
If you agree we can ask @smuzaffar to complete the cleaning and remove them, otherwise we will merge this PR as it is.

**Comment by civanch** [comment]
@perrotta , this is a very old code (was written ~20 years ago) for R-hadron interaction with matter. In my view, there is no real physics model behind but something very approximate. However, when I asked in Exotica group if we should rewrite this code or keep as it is they answer: "please, keep". 

I would propose to merge this PR as it is. I will try to find out a time to, at least, put comments explaining (first of all to myself)), what the code is doing and will remove commented lines. I will just create an issue for that. This PR may be merged.

**Comment by perrotta** [comment]
+1

**Pull request merged**
