### PR TITLE
Pr101x TTStubCluster Association in  FEVTDEBUG eventcontent

### PR DESCRIPTION
**Pull request by rekovic**
Adding TTStub && TTCluster Association products to  `SimTrackerFEVTDEBUG` EventContent:

```
'keep *_TTClusterAssociatorFromPixelDigis_*_*',
'keep *_TTStubAssociatorFromPixelDigis_*_*'
```

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
hmmm.... the three Phase-II workflows fail (200340, 20434 and 21234). Example [log ](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22415/26430/runTheMatrix-results/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17.log)

Not immediately obvious how adding to EventContent does this.  Investigating.

**Comment by rekovic** [comment]
Coming back to this problem. 

The crash happens in a non-related code, in `RecoTauTag/RecoTau` in this [while loop](https://github.com/rekovic/cmssw/blob/930ceba8a4cb2e8bf0408cfc5a68fd24da980672/RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin2.cc#L259-L270), 
more precisely in the call to a `set(reco::Candidate&)` in an instance of `AddFourMomenta` class [here](https://github.com/rekovic/cmssw/blob/930ceba8a4cb2e8bf0408cfc5a68fd24da980672/RecoTauTag/RecoTau/plugins/RecoTauPiZeroStripPlugin2.cc#L267) .

Useful excerpt from valgrind report
```
==23928== Invalid read of size 8
==23928==    at 0x39E2AD60: AddFourMomenta::set(reco::Candidate&) const (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libPhysicsToolsCandUtils.so)
==23928==    by 0x4FADC726: reco::tau::RecoTauPiZeroStripPlugin2::operator()(reco::PFJet const&) const (in /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/pluginRecoTauTagRecoTauPlugins.so)
==23928==    by 0x4FAA11D3: RecoTauPiZeroProducer::produce(edm::Event&, edm::EventSetup const&) (in /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/pluginRecoTauTagRecoTauPlugins.so)
==23928==    by 0x4C88862: edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4C4A1A1: edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4B64E49: decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4B64FEA: bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4B6655A: std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4B67824: edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x5FE342B: tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all(tbb::task&, tbb::task*) (custom_scheduler.h:509)
==23928==    by 0x4C18D77: edm::EventProcessor::processLumis(std::shared_ptr<void> const&) (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==    by 0x4C1E01E: edm::EventProcessor::runToCompletion() (in /cvmfs/cms-ib.cern.ch/nweek-02513/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-02-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so)
==23928==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==23928==

```

attn @davidlange6 @fabiocos

**Comment by rekovic** [comment]
Recipe to quickly reproduce the problem:

``` 
cmsrel CMSSW_10_1_X_2018-03-05-1100
cd CMSSW_10_1_X_2018-03-05-1100/src
cmsenv
git cms-init
git cms-merge-topic -u 22415
scramv1 b -j 4
runTheMatrix.py -l 20034.0
```
Also atn @perrotta @slava77

**Comment by rekovic** [comment]
please test with #22584

**Comment by rekovic** [comment]
ok.  the #22584 of @perrotta fixes the problems this PR had.

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
@fabiocos 
Can you please merge this simple PR in 10_1_X, now that https://github.com/cms-sw/cmssw/pull/22584 has been merged and running.

We need this PR in 10_1_X and have it run for a day or two, before we make 9_3_6 with its back-port 
(i.e. https://github.com/cms-sw/cmssw/pull/22584)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
