### PR TITLE
update number/names of layers/disks for phase 1 upgrade

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by capalmer85** [comment]
If I say "please test", will the bot comply?

**Comment by capalmer85** [comment]
@cmsbuild please test

**Comment by capalmer85** [comment]
@dmitrijus, @vanbesien... ok... so I can't ask @cmsbuild to do anything.

**Comment by dmitrijus** [comment]
please trest

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
Using std::cout/cerr is not allowed, please replace those with edm::LogWarning

**Comment by capalmer85** [comment]
@dmitrijus I changed the std::cout's.  Sorry about that.

**Comment by dmitrijus** [comment]
+1

**Comment by capalmer85** [comment]
Still not merged?

**Comment by capalmer85** [comment]
Why is this not merge? @davidlange6 Is this not running online?  @dmitrijus

**Comment by dmitrijus** [comment]
@capalmer85 This PR should be running on the online DQM.

I don't know why it has not been merged. The change seems trivial and should only affect the online DQM.

**Comment by davidlange6** [comment]
+1
unfortunate no attempt is made to make this backwards compatible..hopefully it stays online only.

**Comment by capalmer85** [comment]
@davidlange6 if that feedback was given any time between mid-june and now, I would have worked on tried.

**Comment by Dr15Jones** [comment]
It appears this pull request is causing the gcc7 builds to have linking problems:https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_9_3_X_2017-08-29-1100/DQM/PixelLumi

I believe the easiest fix would be to change 
```C++
static size_t const kNumLayers = 5;
static size_t const kNumDisks = 12;
static size_t const kOffsetLayers = 0;
static size_t const kOffsetDisks = 4;
```

to
```C++
static size_t constexpr const kNumLayers = 5;
static size_t constexpr const kNumDisks = 12;
static size_t constexpr const kOffsetLayers = 0;
static size_t constexpr const kOffsetDisks = 4;
```

**Comment by smuzaffar** [comment]
@Dr15Jones , https://github.com/cms-sw/cmssw/pull/20293/files fixes this. Should we use
```static size_t constexpr const``` instead of ```static constexpr size_t```

**Comment by Dr15Jones** [comment]
From http://en.cppreference.com/w/cpp/language/constexpr
> A constexpr specifier used in an object declaration implies const

so no need to change the other pull request.

**Pull request merged**
