### PR TITLE
Change CandidateBoostedDoubleSecondaryVertexComputer to use GBRForest (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of  #11607.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
[unclear why the comparisons got stuck]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11608	 3f27577
- the same change as in 76X #11607 . At this point, the effect is only on the allocated memory in CandidateBoostedDoubleSecondaryVertexComputer initialized but not running
- jenkins tests pass and comparisons show no differences
- memory test (igprof) done in 76X should apply here as well.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
