### PR TITLE
Strip APV gains dumped in TTree

### PR DESCRIPTION
**Pull request by ghost**
SiStripApvGainReader modified to dump gains in a TTree
Executable version of the cfg also added

### CODE REVIEW

**Comment by boudoul** [comment]
Hi @jpriscia , thanks for this development - Just a suggestion : In the process of improving the documentation  of our packages,  it might be good to start to add a readme file explaining what is this APV gain reader and usage of the cfg  - Thank you

**Comment by ggovi** [comment]
please test

**Comment by jpriscia** [comment]
Hi @boudoul , readme added. Cheers

**Comment by boudoul** [comment]
Thanks, appreciated !

**Comment by jpriscia** [comment]
Hi @mmusich , sorry, I messed up with the commit.
Now there is the config file and a corresponding executable. The clone has been removed

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
the error reported in the addOn tests is not related to the code changes.
```
----- Begin Fatal Exception 13-Feb-2018 18:22:47 CET-----------------------
An exception of category 'FastSimulation' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 16 stream: 3
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
HelixTrajectory: should not be reached (no solution).
----- End Fatal Exception -------------------------------------------------
```
can tests be restarted?

**Comment by fabiocos** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
