### PR TITLE
Customise functions reducing the list of tracking particles saved by the mixing module

### PR DESCRIPTION
**Pull request by battibass**
This PR adds a set of functions to reduce the size of the FEVTHLTDEBUG event content.
It is intended to be used for the production L1T/HLT Phase2 samples.

All changes to the event content definition are applied in customization function to avoid any interference with standard workflows.

The PR superseeds [PR 17446](https://github.com/cms-sw/cmssw/pull/17446)

@rekovic

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
