### PR TITLE
Adding HLTObject monitoring into online DQM

### PR DESCRIPTION
**Pull request by muell149**
new changes for HLT online DQM

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by muell149** [comment]
Hi @danduggan @deguio ,

Do you understand the issue with these RelVal errors? I'm having trouble understanding what part my code is causing this. Sorry again for the trouble.

Cheers,
Charlie

**Comment by deguio** [comment]
the error is not related.
we will plug on the online system today.
ciao,
F.

**Comment by muell149** [comment]
Thanks @deguio !!

**Comment by deguio** [comment]
status:
this is already running in production at the online given the urgency. however there was a request of optimization of the code with loops to make it more maintainable and less error prone. moreover the trackRefitter is throwing errors and a change to fix them is also needed.

**Comment by deguio** [comment]
-1
rejecting for now not to merge a version which is not final

**Pull request closed without merging**
