### PR TITLE
CPPF emulator @maseguracern, Max 2 clusters per chamber

### PR DESCRIPTION
**Pull request by maseguracern**
This is the first version of the CPPF emulator. we use the RPC Digitization and
reconstruction as intermediate steps.
Under test you can find two examples, one unpacking 2017F RAW Data (cppf_emulator_RAW.py)
and another one using generated MC events (cppf_emulator_MC.py).
The output of the unpacker is an edm branch named emulatorCppfDigis, following
the CPPFDigi dataformat already committed in CMSSW_10_1_X.

one improvement was performed: 
Save maximum 2 CPPFDigis per RPC chamber (hardware performance suggested by the hardware experts).
one analyzer in the folder test as an example was included .

 @abrinke1 @camilocarrillo @jhgoh @mileva

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
backport of #22694

**Comment by fabiocos** [comment]
+1

**Comment by BrieucF** [comment]
@rekovic, @ram1123, @abrinke1 FYI: It looks like important features such has having maximum 2 clusters per chamber per BX were added to this backport (compared to #22694) but never introduced in the central branch. A new PR is being prepared to solve this

**Pull request merged**
