### PR TITLE
80X HLTriggerOffline/Higgs - MuMu SameSign paths without DZ

### PR DESCRIPTION
**Pull request by jasperlauwers**
Adding to Config file:
HLT_Mu17_Mu8_SameSign_v
HLT_Mu20_Mu10_SameSign_v

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
Is there are a 81x version of this?
We usually don't accept 80x - only changes, unless there is a really good reason.

**Comment by jasperlauwers** [comment]
There is here: #14636

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
