### PR TITLE
avoid {using namespace} statements in header files

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by mulhearn** [comment]
This PR also removes use of "using" in cc files, which I would prefer to leave as is.

**Comment by iahmad-khan** [comment]
@mulhearn i have removed that only from header files , and added in cc files where it was required , at this point i couldn't spot removal of 'using' from cc files ,  if you figure out  somewhere in cc file, i ll update the pr .

**Comment by mulhearn** [comment]
Ah, apologies, misread the diff!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
