### PR TITLE
[14.0.X] Fix HLT customization for alpaka PF

### PR DESCRIPTION
**Pull request by waredjeb**
This PR is a backport of [#43999](https://github.com/cms-sw/cmssw/pull/43999)

This PR fixes the customization of Alpaka-PF introduced with [#43979](https://github.com/cms-sw/cmssw/pull/43979) with moving the CPU serial module to `DQM_HcalReconstruction_v6`

GPU vs CPU comparison at DQMOnline will follow up, currently we are only saving the needed collections

Validated running:

```
https_proxy=http://cmsproxy.cms:3128/ hltGetConfiguration /dev/CMSSW_14_0_0/GRun --unprescale --output all --globaltag auto:phase1_2024_realistic --mc --max-events 10 --input /store/mc/Run3Winter24Digi/TT_TuneCP5_13p6TeV_powheg-pythia8/GEN-SIM-RAW/133X_mcRun3_2024_realistic_v8-v2/80000/dc984f7f-2e54-48c4-8950-5daa848b6db9.root --customise HLTrigger/Configuration/customizeHLTforAlpaka.customizeHLTforAlpaka > hlt.py 
```

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #43999

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@waredjeb can you expand the description of this PR ?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/pull/43999#discussion_r1497971481 needs to be fixed first.

**Comment by mmusich** [comment]
type pf

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu = 12434.402, 12434.403, 12434.404, 12434.412

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
unhold

**Comment by rappoccio** [comment]
+1

**Pull request merged**
