### PR TITLE
[GEM] Unpacker update for the vfat making information

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

* GEM Unpacker and data formats are updated to save the vfat masking information
* Minor bugfix for the VFATStatus (Positional information)
* The results of this update has approved in GEM DPG meeting ([link](https://indico.cern.ch/event/1202028/contributions/5054418/attachments/2511952/4317915/Masking_status_20_Sep.pdf))
* Backport to `CMSSW_12_5_X` and `CMSSW_12_4_X` are needed.

#### PR validation:

* The code format has applied with `scram build code-format` and tested with `scram build code-checks`.

@jshlee @quark2

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
Do I understand correctly from the PR description that this code is not actually tested in any relVal workflow?

**Comment by yeckang** [comment]
> Do I understand correctly from the PR description that this code is not actually tested in any relVal workflow?

In the current relVal workflow, we don't use any data with the GEM data format v302 as far as I know.
But I tested it with the several data that we took the last month.

**Comment by mandrenguyen** [comment]
What is GEM data format v302?

**Comment by yeckang** [comment]
> What is GEM data format v302?

It's the raw data format version with new firmware. The masking information that I mentioned in the PR description is only in this version.

**Comment by mandrenguyen** [comment]
I need quite a bit more information.  
Is this new data format the standard going forward?
If so, shouldn't there be a relval workflow with the new data?
We have already deployed a new 12_4_X release without this fix, and there is no plan to update the release again this year.  What is the consequence for data taking?

**Comment by yeckang** [comment]
> I need quite a bit more information.
> Is this new data format the standard going forward?
> If so, shouldn't there be a relval workflow with the new data?
> We have already deployed a new 12_4_X release without this fix, and there is no plan to update the release again this year. What is the consequence for data taking? Can you provide a recipe for testing?

The data format v302 is already employed in P5. And we updated the unpacker for it with the previous PR. (#38062)
But we didn't put every feature with the new data format. This PR is for that missing part.

**Comment by emanueleusai** [comment]
+1

**Comment by AdrianoDee** [comment]
type gem

**Comment by AdrianoDee** [comment]
From my point of view I have no comments on this (code-wise). 

Given it seems to propose some sensitive change to data formats (especially related to the back-port to `12_4_X`), even if redundant, it would be helpful to hear from @cms-sw/gem-dpg-l2 that for sure has a better insight on this. 

Also a way of testing this would help.

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
Hi @yeckang 
Would you mind to ping @cms-sw/gem-dpg-l2 in parallel. I have pinged by email. Thanks.

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test before merging.

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1
- Not for backport in the pp data taking release 12_4_X, at least not without discussion

**Pull request merged**
