### PR TITLE
Run2-hcx129 Backport bug fixes for cff files for Hcal AlCaRecos

### PR DESCRIPTION
**Pull request by bsunanda**
Some of the changes are already integrated to 9_2_X. Some o/p definition changes are in the PR 19033 submitted on May 31

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@franzoni @arunhep Can you sign this? We have issues for Phisymmetry calibration otherwise. This is a backport from the master to 9_1_X

**Comment by bsunanda** [comment]
@franzoni @arunhep Can you sign this? We have issues for Phisymmetry calibration otherwise. This is a backport from the master to 9_1_X

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by franzoni** [comment]
can this PR be closed ? 
91 is ~stale for data taking

**Comment by bsunanda** [comment]
Yes I agree. So closing this PR

**Pull request closed without merging**
