### PR TITLE
Me0 global reco selectors

### PR DESCRIPTION
**Pull request by dnash86**
This PR brings ME0Muon production in SLHC releases in line with what is in 76X (in PR #11398).  

Note: The main difference in its current state between this PR for SLHC releases and what was sent for 76X is that the ME0MuonCollProducer is still in Validation/RecoMuon, not moved to CommonTools/RecoAlgos as we were requested to do for 76X.  This package has been used by multiple analyzers in SLHC as is, but if need be I can make the same move to CommonTools/RecoAlgos as was done in 76X.  Let me know.

### CODE REVIEW

**Comment by mark-grimes** [comment]
please test

Did you mean to put this on the 6_2_X_SLHC branch?  I'll start testing, but this may have to go in on the SLHCDEV branch.

**Comment by dnash86** [comment]
@mark-grimes  Ah, yes, this is probably more appropriate for the SLHCDEV branch.  Should I re issue the PR there?  (I guess I should send the PR to CMSSW_6_2_SLHCDEV_X, and not CMSSW_6_2_X_SLHC, is that correct?)

**Comment by mark-grimes** [comment]
Yes, that's correct.  You may or may not have to rebase, see if the changes are as you would expect when you try the SLHCDEV pull request.

**Comment by dnash86** [comment]
The comparison to SLHCDEV seemed identical to the comparisons to SLHC, so I sent the PR as is.

**Pull request closed without merging**
