### PR TITLE
Add FastSim changes to the run2 era

### PR DESCRIPTION
**Pull request by mark-grimes**
This adds the customisations present in `SLHCUpgradeSimulations.Configuration.fastSimCustoms.customise_fastSimPostLS1` to the `run2` era.  Nothing is changed unless the `run2` era is explicitly activated.

Two points:
- [EDIT - this point no longer relevant] `process.genMixPileUpFiles` is not created. It's not easy to create brand new parameters with an era and I couldn't see it used anywhere.  Is it definitely required?
- I think there's a bug in the original customisation.  The line [SLHCUpgradeSimulations/Configuration/python/fastSimCustoms.py#L11](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SLHCUpgradeSimulations/Configuration/python/fastSimCustoms.py#L11) doesn't do anything.  The correct path is `famosPileUp.PileUpSimulatorBlock.PileUpSimulator` not `famosPileUp.PileUpSimulator` (see [PileUpProducer_cff.py](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/FastSimulation/PileUpProducer/python/PileUpProducer_cff.py)).  The (what I consider) correct path is used here.

Testing has been limited.  I just made sure the files can be parsed properly since nothing is changed if the era is not active.  I'll worry about ensuring identity between the two methods (customisation versus era) once all the pull requests are in.

Also, I haven't taken the customisations out of the run2 helper function [customiseRun2EraExtras](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py#L233). The postLS1Customs.py file is being heavily modified by #7579, and this would likely cause a conflict.  Applying the modification twice has no harm so I'll remove those lines in a later pull request.

### CODE REVIEW

**Comment by mark-grimes** [comment]
About to push a change that adds `process.genMixPileUpFiles` - it's used in some function somewhere.

**Comment by lveldere** [comment]
Hi Mark

I made a simpler version of the pileup file setting.
How do I test it? How do I explain CMSSW which era I want?

Lukas

**Comment by mark-grimes** [comment]
You can pass `--era run2` to cmsDriver.
If you want to test the whole sequence also add `--customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customiseRun2EraExtras`.  This is a temporary helper function that does the final parts that I haven't migrated to the era yet.  This is what I was talking about in the description where I haven't removed the commands yet.

**Comment by lveldere** [comment]
Hi Mark

Here is a cleaner version that also work with the new fastsim pu mixing
(I believe your version won't do the trick)
https://github.com/lveldere/cmssw/compare/fastsim-pufiles-run2

do you include this in your pr? or shall I do the pr?

Cheers

Lukas

**Comment by mark-grimes** [comment]
About to push your fixes...

**Comment by davidlange6** [comment]
bypassing era PRs - lets discuss once Mark has the full set implemented - currently they have no effect

**Comment by lveldere** [comment]
+1

**Comment by mark-grimes** [comment]
please test

This last push should fix the tests - forgot to update the fastsim customisation for the parameter name change.

**Comment by davidlange6** [comment]
ok, now really bypassing..

**Pull request merged**
