### PR TITLE
[Phase-2] [backport] Fix usage of L1 egamma seeds in Phase-2 HLT

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42791
(Needed for HLT-upgrade annual review)

Tagging Phase-2 Egamma HLT contacts/validators: @ravindkv @skeshri

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42791

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of #42791
   * needed for 2023 AR

**Pull request merged**
