### PR TITLE
Fixed backward propagator

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
GeometryProducer is used in order to prepare Geant4 geometry for use in backward propagation. The code is updated in order to take into account possible use of DDD and potentially DD4Hep. This addresses #31920 .

Also CMSSteppingVerbosity is improved, code-check warnings in Notification sub-library are fixed.

These modifications do not affect any WF used in validation. 

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
May require backport to 11_2_0

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
Type bug-fix

**Comment by qliphy** [comment]
+1

**Pull request merged**
