### PR TITLE
SiPixel Quality PCL for cmssw 10_0_X

### PR DESCRIPTION
**Pull request by tocheng**
Backport of PR #22455 

Not just code rebase. Some modification is done in SiPixelStatusProducer to be compatible with CMSSW_10_0_X framework.

The accumulator feature in EDProducer is not available before CMSSW_10_1_X.
https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkOneModuleInterface#edm_Accumulator,
so one has to use "produce()" function.

To make the "produce()" function in the EDAnalyzer run in the unscheduled mode,
ALCARECO trigger bit 
https://github.com/tocheng/cmssw/blob/SiPixelQualityPCL_For_CMSSW_10_0_X/CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc#L76
https://github.com/tocheng/cmssw/blob/SiPixelQualityPCL_For_CMSSW_10_0_X/CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc#L165-L191

is stored as a string event-by-event
https://github.com/tocheng/cmssw/blob/SiPixelQualityPCL_For_CMSSW_10_0_X/CalibTracker/SiPixelQuality/plugins/SiPixelStatusProducer.cc#L292-L294

Both the per-event ALCARECO trigger bit string and  the per-lumi collection is stored in the ALCARECO output.
https://github.com/tocheng/cmssw/blob/SiPixelQualityPCL_For_CMSSW_10_0_X/CalibTracker/SiPixelQuality/python/ALCARECOSiPixelCalZeroBias_Output_cff.py#L8-L15

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by tocheng** [comment]
@arunhep @lpernie The error of Relval tests are due to the SiPixelDetectorStatus object siPixelStatusProducer_siPixelStatus is NOT present in the ALCARECO/ALCAPROMPT. 
The effected workflows are 1001.0, 1001.2.

I thought I solve the problem of running "produce()" in the unscheduled mode. But it turns out that not only need you put a collection to the events in the produce, but also you need to save the collection in the output ALCARECO (otherwise "produce()"  is still isolated from process in unscheduled mode).

Now I solve the problem by producing ALCARECO trigger bit as a string per-event and save it per-event in the ALCARECO output, it takes 1KB space per-event. The Relval tests should be fine now.

**Comment by tocheng** [comment]
Close PR as we only need it for >=CMSSW_10_1_X releases

**Pull request closed without merging**
