### PR TITLE
ParticleLevelProducer based on Rivet

### PR DESCRIPTION
**Pull request by mseidel42**
* Produces
  * GenJetCollections (jets, fat jets, dressed leptons)
  * GenParticleCollections (neutrinos, photons, GenJet constituents, jet tag particles [taus, charm/bottom hadrons])
  * METCollection
* Collections are created from native Rivet code -> CMS analyses which use these collections are easily implemented in Rivet

Credits to @jhgoh for the initial PseudoTopProducer :)

### CODE REVIEW

**Comment by jhgoh** [comment]
With this PR, we can directly use the Rivet routines. We can keep binary level consistency between edm and Rivet analysis.

Usually it will be OK, but I'm not sure what will happen in the multi-threading mode, we are now creating a RivetAnalyzer instance in the module and it can create static objects for caching. 
But thinking about the use cases, we will use this module in specific analyses and does not have serious MT issues.
It will be safe if we switch to edm::one::EDProducer<>, maybe experts can correct me.

**Comment by perrozzi** [comment]
please test

**Comment by intrepid42** [comment]
@jhgoh Do I understand correctly that there are two potential problems?

* It might not run with multithreading

Is there any documentation how this needs to be solved?

* Not possible to run multiple instances of the module (this would be needed to run with different clustering options in the same job)

I can add a hash of the pset to the projection names, that may prevent the caching issues between multiple instances?

The idea is that this may be integrated into MiniAOD production one day.

**Comment by intrepid42** [comment]
Backported changes from #18404 

@perrozzi please test :)

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @intrepid42 - are the changes in 36f8c686182ca8f1a11fe32eb5b2a781a60f2630 picked up in the master branch?

**Comment by intrepid42** [comment]
@davidlange6 yes

**Comment by davidlange6** [comment]
via what PR?

**Comment by intrepid42** [comment]
https://github.com/cms-sw/cmssw/pull/18404

**Comment by davidlange6** [comment]
ok, indeed, I don't understand the commits in github in this case. seems consistent.

**Comment by davidlange6** [comment]
+1

**Comment by jhgoh** [comment]
I believe this PR is related with #18116. Please consider to merged it as well.

**Pull request merged**
