### PR TITLE
MTD Geometry: DD4hep migration, preliminary update and cleaning of ideal geometry test

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR updates DD4hep scenarios D50 and D53 according to the most recent updates, and refresh the ```MTDCommonData``` tests. With the opportunity a few constants for the scenario D53 are added to ```ETLDetId``` and ```ETLNumberingScheme```, and the MtdSD test verbosity is improved. While preparing the migration of ```MTDNumberingBuilder``` (to come in a next PR), I realized that even the old basic DD4hep geometry test had occasional problems with the printed strings, but no sign of issue with the computed DetIds or positions (which makes me think this is mostly a printout issue, although I do not fully understand it).
I have refreshed and simplified the test to avoid useless code duplication and multiple output streams, getting the same results.

#### PR validation:

The standalone ```MTDCommonData``` tests run and produce consistent output.

### CODE REVIEW

**Comment by fabiocos** [comment]
@cvuosalo @ianna this PR (and the next one) would benefit from #29387 for the ```geoHistory``` computation

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

@fabiocos , since some moment, we are trying use LogVerbatim instead of LogInfo, because in the last variant log files are polluted by date and time at each printout, which make a problem to use diff/tkdiff

**Comment by fabiocos** [comment]
@civanch in general I agree about ```LogVerbatim``` vs ```LogInfo```. Anyway 1) several statements are under the debug flag ```EDM_ML_DEBUG``` ,  so no affecting normally anything, and the test code is never run in default workflows, but always in standalone tests where I do want to have the output. As you see I have tried to avoid multiple streams, i.e. both ```MessageLogger``` and external files as in the DDD tests, because I notice some issues with printing names coming from DD4hep that I am not fully understanding, but I am afraid might be made worse by multiple streams. And in that case I use different labels of messages to collect them in files I can directly compare with the old ones, I have a python script to parse MessageLogger output that can selectively do this (may be I should make it available).

**Comment by silviodonato** [comment]
please test workflow 23434.1001

**Comment by fabiocos** [comment]
@silviodonato the problems in the IB need to be solved, before a meaningful test for this PR can be made

**Comment by silviodonato** [comment]
+1

`23434.1001_TTbar_14TeV+RecoFullGlobalPU_TestOldDigi_2026D49PU+HARVESTFullGlobalPU_2026D49PU Step0-PASSED Step1-PASSED  - time date Thu Apr  9 23:29:03 2020-date Thu Apr  9 22:30:05 2020; exit: 0 0`

**Pull request merged**
