### PR TITLE
[13.1.X] Fixed channel decoding for the timeout error in SiPixel RawToDigi

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:

Backport of #42010  

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42010

**Comment by clacaputo** [comment]
+reconstruction

- differences expected, see https://github.com/cms-sw/cmssw/pull/42033#issuecomment-1604355259

**Comment by perrotta** [comment]
+1

**Pull request merged**
