### PR TITLE
[DD4hep] Reintroduce Namespace

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Record namespace (e.g. XML file name) for every Volume

Screenshot 2020-10-21 at 17 50 17

Note: now there are two member functions in `DDNamespace` that do pretty much the same thing: `addVolumeNS` and `addVolume`. A general cleanup will be done to keep the latter after this PR is merged.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold

@silviodonato - please, integrate https://github.com/cms-sw/cmssw/pull/31879 first since it's easier to deal with this PR if a rebase is required. Thanks!

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
@ianna , could this PR be the reason behind failing unit tests in IBs? Tests are failing due to differences in the logs

**Comment by smuzaffar** [comment]
ok https://github.com/cms-sw/cmssw/pull/31934 might fix the issue

**Comment by ianna** [comment]
> ok #31934 might fix the issue

yes, it does for a DT test. I'm waiting for confirmation from @fabiocos if I should fix the MTD code as well.

**Comment by ianna** [comment]
> > ok #31934 might fix the issue
> 
> yes, it does for a DT test. I'm waiting for confirmation from @fabiocos if I should fix the MTD code as well.

Ok, #31934 fixes MTD tests as well

**Pull request merged**
