### PR TITLE
Fix 'Assigned value is garbage or undefined' warning from llvm-analyzer in AlgoMuon

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Log: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-35945a.html#EndPath)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
