### PR TITLE
NanoAODv6, config fixes for UL

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

This PR fixes issues described in #28158, using modifiers that are loaded by Run2_201? eras to identify configuration changes that are linked to the year, and not to the MINIAOD input version for NANOAOD production.

It only changes the NANOAOD content when running on UL samples, doing nothing for 80X, 94X and 102X Run-2 samples.

#### PR validation:

Validated as usual within the nanoAOD integration setup, for both Run-2 and UL available samples.

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521,250202.118

**Comment by peruzzim** [comment]
+xpog

as expected, workflow 10824.0 shows difference due to the proper configuration

**Comment by fabiocos** [comment]
@peruzzim @chayanit @pgunnell @srimanob to be clear about https://github.com/cms-sw/cmssw/pull/28196#issuecomment-543253037 : this is the structure in place without need for further developments, anyway to be used suitable NANOAODreHLT steps need to be defined in PyRelVal ```relval_steps.py``` as done already for RECO sequences

**Comment by fabiocos** [comment]
+operations

the update to ```Configuration/Eras``` looks coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
