### PR TITLE
Phase2-hgx281 Compare DDD against DD4Hep scenario for 2026D76 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Compare DDD against DD4Hep scenario for 2026D76 scenario. Used in testing the geometry through detailed printouts

#### PR validation:

Compared the workflow 34634 with DDD and DD4Hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda 
I'm not sure I understand the PR title and description. Is it to add a test, or something else? Thanks.

**Comment by bsunanda** [comment]
@srimanob We have been struggling to find the reason of failure of Phase2 scenario in dd4hep. We use different codes for the algorithms and the main purpose of this PR is to see if the 2 sets of algorithms used for V14 HGCal give the same results. There are debug statements which are made similar outputs. Running the codes separately for silicon cells, wafers, full silicon layers, mixed layers and comparing the two sets of outputs using diff show identical results from ddd and dd4hep. This required changes in the debug statements, defining a few cdi's, cfg's which are parts of this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
