### PR TITLE
TOB Potting Overlap Bugfix

### PR DESCRIPTION
**Pull request by ianna**
* Move TOBPotting by ~mm
* Move TIBRailBottom by 0.05 cm
* Move TOBConnect23 out of TOBCFTube2

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , I do not see overlaps in tracker any more.

**Comment by ianna** [comment]
@civanch - thanks!

**Comment by ianna** [comment]
+1

**Comment by boudoul** [comment]
big thanks @ianna @civanch !

**Comment by ianna** [comment]
Replaced by https://github.com/cms-sw/cmssw/pull/17383

**Pull request closed without merging**
