### PR TITLE
DD4hep: DDCompactView as an Ideal Geometry ES Record

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add an ES Producer and a test of a DDCompactView 

#### PR validation:

The test is added to run automatically in this PR

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
Strange that this test fails which is part of this package, but not touched by the PR:
```
===== Test "cmsRun testDDGEMAngularAlgorithm.py" ====
----- Begin Fatal Exception 24-May-2019 00:39:15 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-05-23-1100/src/DetectorDescription/DDCMS/test/python/testDDGEMAngularAlgorithm.py
Exception Message:
 unknown python problem occurred.
RuntimeError: ESInputTag passed one string 'TestDDGEMAngular' which does not contain a ':'. Please add ':' to explicitly separate the module (1st) and data (2nd) label or use two strings.

At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-05-23-1100/python/FWCore/ParameterSet/Types.py(608): _setValues
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-05-23-1100/python/FWCore/ParameterSet/Types.py(546): __init__
  /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-05-23-1100/src/DetectorDescription/DDCMS/test/python/testDDGEMAngularAlgorithm.py(21): <module>

----- End Fatal Exception -------------------------------------------------
Failure using cmsRun /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-05-23-1100/src/DetectorDescription/DDCMS/test/python/testDDGEMAngularAlgorithm.py: status 90
status = 23040

---> test DetectorDescriptionDDCMSTestDriver had ERRORS

```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
