### PR TITLE
Fix GCC8 compiler warnings, A real bug

### PR DESCRIPTION
**Pull request by wddgit**
As far as I can see from the code in the CMSSW
repository this only affects some debug printout

I just guessed at what the behavior is supposed
to be although it seems the only reasonable possibility.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by thomreis** [comment]
+1

This seems to make sense.

**Comment by fabiocos** [comment]
@thomreis as far as I can see the DQM differences are related to L1, so they might be real and not just fake ones, am I correct?

@wddgit this PR seems to excite all sort of possible check failure. While the compiler warnings and header consistency seems to me unrelated, the code rule violations affect also files touched by this PR, could we take the opportunity to clean them?

@smuzaffar how should I interpret the "internal compiler error: Segmentation fault" messages that I see in the new header checks? It does not seem to me that we are having problems in the main build

**Comment by thomreis** [comment]
Hi @fabiocos 
this PR alone should not create any differences. It might come from one of the additional commits in the test.
In any case the failing distributions look almost identical.

**Comment by wddgit** [comment]
please test

@fabiocos I fixed the code rule violations in the same package

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@wddgit thank you a lot!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
