### PR TITLE
Fix IB test failures due to missing outdated energy correction files

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

Some of the IB tests still look for the legacy 9_4_X electron & photon energy correction files. The deletion of the outdated correction file in cms-data/EgammaAnalysis-ElectronTools#12 and #46138 caused the IB test failures as the default energy correction file is the legacy one when there is no modifier.

(the master is okay since the legacy workflows were cleaned up in #45240)

So I cherry-picked one of the line changes in #45240 - this should make the default energy correction file the UL version when there is no modifier.

Fix https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/12#issuecomment-2454167466 and https://github.com/cms-sw/cmssw/pull/46138#issuecomment-2454179806

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by SanghyunKo** [comment]
This particular workflow `136.7611` had a modifier `run2_miniAOD_80XLegacy` and therefore still wanted to access the legacy correction file. I just removed the modifier (which is not present in the master branch anyway).

**Comment by jfernan2** [comment]
please test

**Comment by SanghyunKo** [comment]
ugh, sorry... I've found another access to obsolete modifiers. Hopefully the test succeeds this time.

**Comment by jfernan2** [comment]
Have you performed any standalone test already, right?

**Comment by SanghyunKo** [comment]
@jfernan2 at least it works for the workflow `136.8311`. I'm not sure about the workflow `136.7611` since it keeps failing to read the input legacy AOD files when I tried locally. 

136.8311
```
[sako@cms tests]$ runTheMatrix.py -l 136.8311
processing relval_standard
processing relval_highstats
processing relval_pileup
processing relval_generator
processing relval_extendedgen
processing relval_production
processing relval_ged
ignoring relval_upgrade from default matrix
processing relval_2017
processing relval_2023
ignoring relval_identity from default matrix
processing relval_machine
processing relval_unsch
processing relval_premix
Running in 4 thread(s)

Preparing to run 136.8311 RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017

# in: /u/user/sako/egm/CMSSW_10_6_44/work/tests going to execute cd 136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017
 echo '{
"305064" : [[2, 101]]
}' > step1_lumiRanges.log  2>&1
 

# in: /u/user/sako/egm/CMSSW_10_6_44/work/tests going to execute cd 136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017
 (dasgoclient --limit 0 --query 'lumi,file dataset=/JetHT/Run2017F-17Nov2017-v1/AOD run=305064' --format json | das-selected-lumis.py 2,101 ) | sort -u > step1_dasquery.log  2>&1
 
---

# in: /u/user/sako/egm/CMSSW_10_6_44/work/tests going to execute cd 136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017
 cmsDriver.py step2  --conditions auto:run2_data_relval -s PAT,DQM:@miniAODDQM --process PAT -n 100 --data  --era Run2_2017,run2_miniAOD_94XFall17 --eventcontent MINIAOD,DQM --runUnscheduled  --scenario pp --datatier MINIAOD,DQMIO --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root  > step2_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017.log  2>&1
 

# in: /u/user/sako/egm/CMSSW_10_6_44/work/tests going to execute cd 136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017
 cmsDriver.py step3  --conditions auto:run2_data_relval --scenario pp -s HARVESTING:@miniAODDQM --filetype DQM --data  --era Run2_2017,run2_miniAOD_94XFall17 -n 100  --filein file:step2_inDQM.root --fileout file:step3.root  > step3_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017.log  2>&1
 
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017 Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Nov  6 00:45:46 2024-date Wed Nov  6 00:09:02 2024; exit: 0 0 0
1 1 1 tests passed, 0 0 0 failed
```

136.7611
```
05-Nov-2024 16:57:01 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root
%MSG-w XrdAdaptorInternal:  file_open 05-Nov-2024 16:57:02 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?xrdcl.requuid=b85f9fed-df5c-4323-a7bc-ec76db9853f9.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 05-Nov-2024 16:57:02 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?tried=&xrdcl.requuid=daa1e470-c4d7-434c-8589-5a59b8ff04f6.
%MSG
05-Nov-2024 16:57:02 CET  Fallback request to file root://xrootd-cms.infn.it//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root
%MSG-w XrdAdaptorInternal:  file_open 05-Nov-2024 16:57:03 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?tried=+1213xrootd-redic.pi.infn.it&xrdcl.requuid=3d88ee56-5dd6-473f-a151-c47ec80e43e7.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 05-Nov-2024 16:57:03 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?tried=+1213xrootd-redic.pi.infn.it,&xrdcl.requuid=877c4dea-2e6a-4ac0-99f4-91e76c603c20.
%MSG
----- Begin Fatal Exception 05-Nov-2024 16:57:03 CET-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root; No such file or directory^@
' (errno=3011, code=400). No additional data servers were found.
      [b] Last URL tried: root://eoscms.cern.ch:1094//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?tried=&xrdcl.requuid=daa1e470-c4d7-434c-8589-5a59b8ff04f6
      [c] Problematic data server: eoscms.cern.ch:1094
      [d] Disabled source: eoscms.cern.ch:1094
      [e] Input file root://eoscms.cern.ch//eos/cms/store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root could not be opened.
Fallback Input file root://xrootd-cms.infn.it//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.^@
' (errno=3011, code=400). No additional data servers were found.
      [g] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2016E/JetHT/AOD/18Apr2017-v1/100000/02FB8769-5433-E711-BBDE-0025905A6076.root?tried=+1213xrootd-redic.pi.infn.it,&xrdcl.requuid=877c4dea-2e6a-4ac0-99f4-91e76c603c20
      [h] Problematic data server: cms-xrd-global.cern.ch:1094
      [i] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by hqucms** [comment]
Hi @SanghyunKo -- I wondering if it would be better to follow the other path, i.e., we don't touch any of these old modifiers in the cmssw 10_6_X branch, but rather adding back the deleted files in the cms-data repo and create a new tag for 10_6_X?

**Comment by smuzaffar** [comment]
> Hi @SanghyunKo -- I am wondering if it would be better to follow the other path, i.e., we don't touch any of these old modifiers in the cmssw 10_6_X branch, but rather adding back the deleted files in the cms-data repo and create a new tag for 10_6_X?

I agree, we can just create a new tag of cms-data for 10.6.X. I would start with existing V00-03-01 tag and add the new files and create V00-03-01-01 or V00-03-02

**Comment by SanghyunKo** [comment]
I really wanted to avoid that since we're reviving obsolete and buggy files just to make the test successful, which jeopardizes the purpose of the test... but fine. We have several outdated workflows in 10_6_X IB tests, and I understand adding the files back is the simplest trick. As long as we don't add them back in the master (V00-04), I can deal with it.

**Comment by SanghyunKo** [comment]
opened cms-data/EgammaAnalysis-ElectronTools#13, closing this PR.

**Pull request closed without merging**
