### PR TITLE
Run3-gex78 Make a selection of SD's to be initialized

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a selection of SD's to be initialized; needed for special scenarios (test beam, testing dd4hep)

#### PR validation:

Tested using cfgs in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@srimanob, can you, please, have a look?

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@silviodonato @qliphy Could this be merged with the master?

**Comment by qliphy** [comment]
+1

**Pull request merged**
