### PR TITLE
load jet calibration LUT for Stage1 50ns run

### PR DESCRIPTION
**Pull request by jingyucms**
Hi @mulhearn 
As this LUTs has not yet covered by online global tag but needed by online DQM. I make this PR for online DQM to use. No need to merge.
Cheers
Jingyu

### CODE REVIEW

**Comment by deguio** [comment]
I am not sure about:
L1Trigger/L1TCalorimeter/data/jetCalibrationLUT_stage1_symmetric.txt

@davidlange6 is this something that can go in cmssw? or should be put in some external repo?
thanks,
F.

**Comment by deguio** [comment]
not that my opinion matters since it is not a DQM package...  ;)
ciao,
F.

**Comment by jingyucms** [comment]
@deguio no need to go into CMSSW, just temporary file. Will remove when we have a proper global tag.

**Comment by mulhearn** [comment]
I think actually the very latest version of the LUT is in this PR:
  https://github.com/cms-sw/cmssw/pull/10491/files
and have already been copied to the cms-data repo in 74X/75X/76X.
But I don't have a working 74X version of the PR because of conflicts (updates were on top of things not in 74X yet)...

**Comment by jingyucms** [comment]
Close, see #10698

**Pull request closed without merging**
