### PR TITLE
HeavyIon EP code backport

### PR DESCRIPTION
**Pull request by BetterWang**
[+] back port EP code #9022 to 74X
In order to develop Q2 trigger for HI data taking, we are advised to port #9022 to 74X.
So, a HLT template can be made to trigger development.
This update will not change the HI workflow, and is not related to any HLT related software.
The only change will be the EventPlane data format in HI event content.

### CODE REVIEW

**Comment by slava77** [comment]
@BetterWang is this backport making changes in standard reconstruction? It's OK to backport code which can be enabled in configuration. Backports for code changing (current default) physics output in a noticeable way should be discussed in appropriate meetings.

@degano please wake up the cms-bot

**Comment by davidlange6** [comment]
@smuzaffar can help with jenkins too

**Comment by BetterWang** [comment]
Hi @slava77 , this update is only affecting HI workflow.
And the official data taking release will be 75X.
This PR is requested in order to have a HLT template generated in 74X then port to 75X, (which I don't know how it works).

@ssanders50 may want to follow this.

**Comment by smuzaffar** [comment]
yes , cms-bot was stuck for last three hours. I just forced it again.

**Comment by slava77** [comment]
On 6/1/15 9:56 AM, Quan Wang wrote:
> Hi @slava77 <https://github.com/slava77> , this update is only affecting
> HI workflow.
> And the official data taking release will be 75X.
> This PR is requested in order to have a HLT template generated in 74X
> then port to 75X, (which I don't know how it works).


I understand that this is only for HI.
Please let me know if this PR changes the standard HI workflow results
in 74X.
Does it change default HLT performance?

Does it change default RECO performance?

Thanks.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@degano @smuzaffar could you please check the status of the jenkins comparisons script.
The comparisons are still pending for 18 hours for this PR (typical run is ~10 mins or less).

**Comment by smuzaffar** [comment]
comparison jobs were failing due to missing base line results on new 
cmssdt01 machine and old backend server (i.e. vocms12) was not 
available. I have fixed it and triggered the comparison job again. 
Hopefully it will run soon (once we have a empty machine)

**Comment by slava77** [comment]
the test results here are already 404 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9382/2675/summary.html; probably never got redirected from the old back-end.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9382	9b31b25
- checked in 75X that a cherry pick of this PR returns an empty commit ==> backport is correct
- only HI workflows are affected
- tested locally in CMSSW_7_4_4_patch2 /test area sign549/ on 100 events in 140.53: the code runs OK. The only change is in the hiEvtPlane objects (not monitored with standard tools in 74X) and no effects downstream.

@davidlange6 @Martin-Grunewald  
once this is integrated, the developers need a release with these code changes known to HLT configuration tools

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
same here, got deleted by jenkin cleanup job. re-triggering it now

**Comment by slava77** [comment]
Hi Quan,
The index -1 issue is here as well, right?
Please fix here and update.

**Comment by BetterWang** [comment]
Hi @slava77 , I am testing the patch, will update soon.

**Comment by BetterWang** [comment]
Back ported the bug fix and DQM update from 75X.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9382	75c1d0b
- code changes are OK (I expected only the negative index issues to be fixed, not everything else from 75X developments; but OK for HI needs here in 74X).
- tested in CMSSW_7_4_4_patch2 /test area sign549/ with 100 events on 140.53
    - recoEvtPlanes_hiEvtPlane_recoLevel was changed to recoEvtPlanes_hiEvtPlane

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
@deguio 
Federico,
this is waiting for the DQM signature.
Could you please check.
Thanks

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
