### PR TITLE
DD4hep: Tracker overlaps TIB

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

master overlaps:

masterc

master + thisPr Overlaps:

thisprc

#### PR validation:

```
cmsRun test/python/testTracker2021Geometry.py >Tracker2021.log
cmsShow -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS


Path:
/Tracker_2/TIDB_2
````

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@vargasa - very nice!

**Comment by ianna** [comment]
@fabiocos - the reported errors are due to the other PR merged in the IBs

**Comment by intrepid42** [comment]
Hi, I guess it included https://github.com/cms-sw/cmssw/pull/27610 but not https://github.com/cms-sw/cmsdist/pull/5107

Should be fixed with next IB?

**Comment by intrepid42** [comment]
This may work: `please test with cms-sw/cmsdist#5107`

(or wait for next IB tomorrow)

**Comment by fabiocos** [comment]
please just wait for next IB to build, unfortunately sooner or later we need to break for a few hours in order to integrate this external

**Comment by vargasa** [comment]
Hello @fabiocos. Just checking, is there anything to be done here?

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@vargasa @ianna in this PR you are essentially promoting a LogDebug to LogInfo (LogVerbatim is just an unformatted LogInfo), is this really needed/desired ?

**Comment by vargasa** [comment]
Hi @fabiocos. Yes, at this phase of development it is needed.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
