### PR TITLE
Add cms_ prefix to float<BITS>x<ELEM_NUM>_t typedefs

### PR DESCRIPTION
**Pull request by davidlt**
We have recently moved to Eigen 3.3 with

- Many ARM NEON improvements, including support for ARMv8 (64-bit code),
  VFPv4 (fused-multiply-accumulate instruction), and correct tuning of
  the target number of vector registers.

Internally Eigen loads `arm_neon.h` on AArch64 target to use ARM NEON
intrinsics. The header defines extra system types:

    float<BITS>x<ELEM_NUM>_t

Let's add `cms_` prefix to our types to avoid conflicts with system
types, which lead to compilation errors.

NOTE: these types are not directly used within CMSSW.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlt** [comment]
Fixed. I guess, I missed it while grepping for its usage in CMSSW.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16748 bcb0d92de1b57af41609d95f63d41e398b721c70

Technical change to avoid name clash between CMS-declared types from ExtVec.h and system types. There should be no change in run-time behavior.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-11-23-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
