### PR TITLE
Fixes to L1T for simultaneous packing of Gt Inputs  and Calo/GMT Outputs

### PR DESCRIPTION
**Pull request by mulhearn**
A bug in the Stage2 unpacker for L1T made it impossible to pack GT inputs Calo/GMT outputs using the same code as designed.  This led to crashes being untested until an early MW GR.  The GT input unpacking was disabled.   

This PR is the proper fix, which allows GT unpacker to be turned back on.  This PR includes updates to our integration tests which check the unity of GT packing + unpacking.  (As for Calo and GMT).

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by davidlange6** [comment]
@mulhearn - this has merge conflicts now - could you rebase?

**Comment by mulhearn** [comment]
Yep!

**Comment by mulhearn** [comment]
Made obsolete by #14323.

**Pull request closed without merging**
