### PR TITLE
[DD4hep] Torus Replacement with Tubs

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Torus replaced with Tubs - @bsunanda, please, comment
* Overlaps in EE eliminated

Mixture of `Torus` and `Tubs` shapes where some of the`Torus` shapes extrude each other:
Screenshot 2020-06-08 at 16 10 19

Calculations for the `Tubs` radii are based on squaring the circle, e.g. the new shapes should have an equivalent material budget:
Screenshot 2020-06-08 at 18 32 32

Thickness of the cooling pipes left unchanged.

Final result:
Screenshot 2020-06-08 at 17 55 13

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
@ianna I noticed you change `float` to `double` in `DEcalPreshowerAlgo.cc`. Was that important for getting rid of overlaps?

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
> @ianna I noticed you change `float` to `double` in `DEcalPreshowerAlgo.cc`. Was that important for getting rid of overlaps?

This change allowed to reduce its memory footprint by 20%.

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
