### PR TITLE
Protection for negative kinetic energy in Geant4 tracking

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR should address the issue #40126 - tracking of a particle with very small negative kinetic energy. This issue should be rare, because never was reported below. The fix does not affect any physics. 

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
type bug-fix

**Comment by civanch** [comment]
DAS error

**Comment by civanch** [comment]
Please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
