### PR TITLE
Small changes in HCAL TP LUTs

### PR DESCRIPTION
**Pull request by akhukhun**
The PR includes the following changes:

- use average adc2fC over four CapId's instead of the first one to calculate linearization LUTs.
   This has a small effect on TPs.
- pass HF FG bit threshold through the input LUTs as it's done online
- small cleanup to remove extra LUT arrays.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
