### PR TITLE
Change SiPixel LA PCL naming in autoPCL file

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Inspired by the mistake in https://github.com/dmwm/T0/pull/4635#pullrequestreview-810983243
We propose to rename this mapping to be consistent with the wf name.  It is necessary in order for the ALCAHarvesting step to succeed, see [dmwm/T0#4635 (comment) ](https://github.com/dmwm/T0/pull/4635#discussion_r753606998) as autoPCL is used in the ConfigBuilder.

#### PR validation:

Tried to run
`runTheMatrix.py -l 1001.2`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 1001.2

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

- changes inline with PR description

**Comment by mmusich** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

Technical PR of naming. PR test runs fine with no change.

**Comment by bbilin** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
