### PR TITLE
Add hi detached triplet step

### PR DESCRIPTION
**Pull request by mandrenguyen**
Adds a tracking iteration to recover displaced tracks into the HI reco sequence (important for b-tagging).
Comes right after the initial step, as is now done in the pp tracking.
The low pT HI step now has a misleading naming convention (second triplet).  We propose to fix that in the next pre-release to keep this PR as simple as possible.
The # of extra tracks produced by this step is relatively modest (< 10% increase), so event size will not change dramatically.
The extra CPU time is also relatively modest compared to the current total tracking time.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
.. I'm checking this

**Comment by slava77** [comment]
-1

when running 140.53 for 200 events in CMSSW_7_4_X_2015-01-28-1400 I get a seg fault
on event 173


```
%MSG-e FatalSystemSignal:  PixelTrackProducer:hiDetachedTripletStepPixelTracks  29-Jan-2015 18:16:42 CET Run: 182124 Event: 1910451
A fatal system signal has occurred: segmentation violation
%MSG

#6  0x00007f5dd31725f5 in ClusterShapeHitFilter::isCompatible(SiPixelRecHit const&, Vector3DBase<float, GlobalTag> const&, SiPixelClusterShapeCache const&, Cl
usterShapeHitFilter::PixelData const*) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-28-1400/lib/sl
c6_amd64_gcc491/libRecoPixelVertexingPixelLowPtUtilities.so
#7  0x00007f5dd3178f3a in ClusterShapeTrackFilter::operator()(reco::Track const*, std::vector<TrackingRecHit const*, std::allocator<TrackingRecHit const*> > c
onst&, TrackerTopology const*) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-28-1400/lib/slc6_amd64
_gcc491/libRecoPixelVertexingPixelLowPtUtilities.so
#8  0x00007f5dd313d31a in PixelTrackReconstruction::run(std::vector<std::pair<reco::Track*, SeedingHitSet>, std::allocator<std::pair<reco::Track*, SeedingHitSet> > >&, edm::Event&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-28-1400/lib/slc6_amd64_gcc491/libRecoPixelVertexingPixelTrackFitting.so
#9  0x00007f5dbfec20cd in PixelTrackProducer::produce(edm::Event&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-28-1400/lib/slc6_amd64_gcc491/pluginRecoPixelVertexingPixelTrackFittingPlugins.so

```

**Comment by mandrenguyen** [comment]
please test

**Comment by nclopezo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7393	1ce5a6d

based on tests in CMSSW_7_4_X_2015-01-28-1400 /test area sign500/
- Non-HI workflows are not affected, as expected.
- The HI workflows with tracker present (140.53) show changes connected to the additional iteration

Techincal numbers based on 200 event run:
- memory increases by about 100 MB: max RSS 2537.84 => 2628.11
- CPU time increases by about 5%: from 71.5 s/evt to 75.2 s/evt
- RECO size increases by 1.7%, driven by about 6% increase in the size of the hiGeneralTracks collection; muons collection size increases by 12%.

Here are selected modules from the reco sequence:
```
Only f2 module count: 8
        hiDetachedTripletStepClusters    2.14353 ms/ev
        hiDetachedTripletStepSeedLayers          1.99445 ms/ev
        hiDetachedTripletStepPixelTracks         381.438 ms/ev
        hiDetachedTripletStepSeeds       26.1941 ms/ev
        hiDetachedTripletStepTrackCandidates     1013.48 ms/ev
        hiDetachedTripletStepTracks      334.495 ms/ev
        hiDetachedTripletStepSelector    1.47264 ms/ev
        hiDetachedTripletStepQual        3.38571 ms/ev
         Total only f2: 1764.61 ms/ev
common modules (most significant diffs):
        hiSecondPixelTripletTrackCandidates      5911.62 ms/ev -> 6569.2 ms/ev
        hiSecondPixelTripletGlobalPrimTracks     917.875 ms/ev -> 1145.84 ms/ev
        hiGeneralTracks          406.83 ms/ev -> 600.664 ms/ev
        muons    2174.67 ms/ev -> 2368.58 ms/ev
        particleFlowEGamma       11707.7 ms/ev -> 12514.4 ms/ev
 Total times: 71647.9 ms/ev -> 75244 ms/ev       delta: 3596.17

```

wf140p53_hitk_algo
wf140p53_hitk_nlayers

**Pull request merged**
