### PR TITLE
[MiniAOD] Increase AK4 CHS pt cut and remove unsupported taggers for AK4 CHS and AK8 Puppi jets 

### PR DESCRIPTION
**Pull request by nurfikri89**
This PR is  the long awaited follow up of Issue #37167. The following changes to MiniAOD content are introduced:

- AK4 CHS jets (`slimmedJets`) pT threshold increase from `10 GeV` to `15 GeV`.
- Remove PileupJetID and Quark-Gluon Likelihood taggers for AK4 CHS jets.
- Remove unsupported taggers for AK4 CHS jets.
- Remove unsupported taggers for AK8 Puppi jets (`slimmedJetsAK8`).

Event size decreases by about 2.6%. The size comparison test was performed with 5000 events from a Run3Summer23 TTTo4Q AODSIM file.

List of tagger outputs stored for AK4CHS jets:

```
pfJetBProbabilityBJetTags
pfJetProbabilityBJetTags
pfTrackCountingHighEffBJetTags
pfDeepCSVJetTags:probb
pfDeepCSVJetTags:probc
pfDeepCSVJetTags:probudsg
pfDeepCSVJetTags:probbb
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probb
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probc
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probele
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probg
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probmu
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h2p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum3h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum3h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h2p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup3h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup3h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probuds
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptcorr
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptnu
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptreshigh
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptreslow
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:BvsAll
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:CvsB
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:CvsL
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:QvsG
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsEle
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsJet
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsMu
```

List of tagger outputs stored for AK4Puppi jets:

```
pfDeepCSVJetTags:probb
pfDeepCSVJetTags:probbb
pfDeepCSVJetTags:probc
pfDeepCSVJetTags:probudsg
pfJetBProbabilityBJetTags
pfJetProbabilityBJetTags
pfTrackCountingHighEffBJetTags
pfDeepFlavourJetTags:probb
pfDeepFlavourJetTags:probbb
pfDeepFlavourJetTags:probc
pfDeepFlavourJetTags:probg
pfDeepFlavourJetTags:problepb
pfDeepFlavourJetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probb
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probc
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probele
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probg
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probmu
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h2p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum3h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum3h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h2p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup3h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup3h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptcorr
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptnu
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptreshigh
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptreslow
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:probg
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:probq
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptcorr
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptnu
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptreshigh
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptreslow
pfParticleTransformerAK4JetTags:probb
pfParticleTransformerAK4JetTags:probbb
pfParticleTransformerAK4JetTags:probc
pfParticleTransformerAK4JetTags:probg
pfParticleTransformerAK4JetTags:problepb
pfParticleTransformerAK4JetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:BvsAll
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:CvsB
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:CvsL
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:QvsG
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsEle
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsJet
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsMu
pfParticleNetFromMiniAODAK4PuppiForwardDiscriminatorsJetTags:QvsG
pfParticleTransformerAK4DiscriminatorsJetTags:BvsAll
pfParticleTransformerAK4DiscriminatorsJetTags:BvsL
pfParticleTransformerAK4DiscriminatorsJetTags:CvsB
pfParticleTransformerAK4DiscriminatorsJetTags:CvsL
pfParticleTransformerAK4DiscriminatorsJetTags:QvsG
```

List of tagger outputs stored for AK8Puppi jets:

```
pfParticleNetFromMiniAODAK8JetTags:masscorr
pfParticleNetFromMiniAODAK8JetTags:probHbb
pfParticleNetFromMiniAODAK8JetTags:probHcc
pfParticleNetFromMiniAODAK8JetTags:probHgg
pfParticleNetFromMiniAODAK8JetTags:probHqq
pfParticleNetFromMiniAODAK8JetTags:probHte
pfParticleNetFromMiniAODAK8JetTags:probHtm
pfParticleNetFromMiniAODAK8JetTags:probHtt
pfParticleNetFromMiniAODAK8JetTags:probQCD0hf
pfParticleNetFromMiniAODAK8JetTags:probQCD1hf
pfParticleNetFromMiniAODAK8JetTags:probQCD2hf
pfParticleNetJetTags:probHbb
pfParticleNetJetTags:probHcc
pfParticleNetJetTags:probHqqqq
pfParticleNetJetTags:probQCDb
pfParticleNetJetTags:probQCDbb
pfParticleNetJetTags:probQCDc
pfParticleNetJetTags:probQCDcc
pfParticleNetJetTags:probQCDothers
pfParticleNetJetTags:probTbc
pfParticleNetJetTags:probTbcq
pfParticleNetJetTags:probTbel
pfParticleNetJetTags:probTbmu
pfParticleNetJetTags:probTbq
pfParticleNetJetTags:probTbqq
pfParticleNetJetTags:probTbta
pfParticleNetJetTags:probWcq
pfParticleNetJetTags:probWqq
pfParticleNetJetTags:probZbb
pfParticleNetJetTags:probZcc
pfParticleNetJetTags:probZqq
pfParticleNetDiscriminatorsJetTags:H4qvsQCD
pfParticleNetDiscriminatorsJetTags:HbbvsQCD
pfParticleNetDiscriminatorsJetTags:HccvsQCD
pfParticleNetDiscriminatorsJetTags:TvsQCD
pfParticleNetDiscriminatorsJetTags:WvsQCD
pfParticleNetDiscriminatorsJetTags:ZbbvsQCD
pfParticleNetDiscriminatorsJetTags:ZccvsQCD
pfParticleNetDiscriminatorsJetTags:ZvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HbbvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HccvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HggvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HqqvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HtevsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HtmvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HttvsQCD
```

FYI JME L2 (@abenecke @alkaloge), BTV L2 (@SWuchterl @mondalspandan) and XPOG (@vlimant @hqucms)

#### PR validation:

passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by nurfikri89** [comment]
@vlimant @hqucms, can this be backported to `14_0_X`?

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by mandrenguyen** [comment]
type jetmet, btv

**Comment by vlimant** [comment]
you may prepare a backport indeed

**Comment by mandrenguyen** [comment]
+1

**Comment by hqucms** [comment]
@nurfikri89 The comparison seem to show some changes in the threshold of `slimmedJetsPuppi` too, e.g.,:
- [c_log10patJets_slimmedJetsPuppi__reRECO_obj_et.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-14-2300+edbb09/61112/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_log10patJets_slimmedJetsPuppi__reRECO_obj_et.png)
- [c_log10patJets_slimmedJetsPuppi__reRECO_obj_energy.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-02-14-2300+edbb09/61112/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_log10patJets_slimmedJetsPuppi__reRECO_obj_energy.png)

I suppose that's not expected? Could you please double check?

**Comment by nurfikri89** [comment]
@hqucms yes, this is unexpected. that is weird. I will take a closer look at it with my private files.

**Comment by hqucms** [comment]
A consequence of the changes proposed [above](https://github.com/cms-sw/cmssw/pull/43965#issuecomment-1946856917) is the that all derivations of `selectedPatJets` now will not have a pt cut (unless specifically defined). A diff of the full config using `edmConfigDump` reveals the following differences:

```diff
 process.selectedPatJetsAK8PFPuppiSoftDrop = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("patJetsAK8PFPuppiSoftDrop")
@@ -582706,7 +582726,7 @@ process.selectedPatJetsAK8PFPuppiSoftDrop = cms.EDFilter("PATJetSelector",
 
 
 process.selectedPatJetsAK8PFPuppiSoftDropSubjets = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("patJetsAK8PFPuppiSoftDropSubjets")
@@ -582806,7 +582826,7 @@ process.selectedPatJetsForMetT2SmearCorrPuppi = cms.EDFilter("PATJetSelector",
 
 
 process.selectedPatJetsNoHF = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("patJetsNoHF")
@@ -582912,7 +582932,7 @@ process.selectedVerticesForPFMEtCorrType0Puppi = cms.EDFilter("VertexSelector",
 
 
 process.slimmedJets = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("updatedPatJetsTransientCorrectedSlimmedDeepFlavour")
@@ -582920,7 +582940,7 @@ process.slimmedJets = cms.EDFilter("PATJetSelector",
 
 
 process.slimmedJetsAK8 = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("updatedPatJetsTransientCorrectedSlimmedAK8DeepTags")
@@ -582928,7 +582948,7 @@ process.slimmedJetsAK8 = cms.EDFilter("PATJetSelector",
 
 
 process.slimmedJetsPuppi = cms.EDFilter("PATJetSelector",
-    cut = cms.string('pt > 15'),
+    cut = cms.string(''),
     cutLoose = cms.string(''),
     nLoose = cms.uint32(0),
     src = cms.InputTag("updatedPatJetsTransientCorrectedSlimmedPuppiWithDeepTags")
```

I think most of them will not make a real difference as the pt cut is already applied at previous steps, but it might change the behavior of `SoftDropSubjets` (a question for @cms-sw/jetmet-pog-l2 is that, should there be a pt cut for soft drop subjets?) and `selectedPatJetsNoHF` (are these NoHF jets actually used?).

**Comment by hqucms** [comment]
please test

**Comment by mandrenguyen** [comment]
What is the change in event size after the latest commit?

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
