### PR TITLE
Switch HLT:@relval2017 to HLT:Fake2

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Switch HLT:@relval2017 to HLT:Fake2
Based on CMSSW_10_0_0_pre3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
I assume that all the differences in the 2017 workflow output are the expected consequence of the change in configuration, correct?

**Comment by Martin-Grunewald** [comment]
Yes, they are related to HLT quantities, affected by this PR.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
