### PR TITLE
Add Run3 promptData JetID

### PR DESCRIPTION
**Pull request by etzia**
#### PR description:

@laurenhay  @rkogler 

The JetID criteria for the prompt reco 2022 and 2023 data have been implemented.
The criteria can be found in
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13p6TeV

#### PR validation:
I have run successfully the following checks:
scram b code-checks
scram b code-format

### CODE REVIEW

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@etzia there are compilation warnings https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-58eb2b/35644/summary.html

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
@etzia : there is a compilation failure that needs to be sorted out in order for this PR to move forward. Please resolve or close

**Comment by jfernan2** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by mandrenguyen** [comment]
> failures independent of the PR. something else is broken apparently

The failure was due to this:  https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/28#event-11495636303
but it should be fixed now in the latest IB

**Comment by vlimant** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
