### PR TITLE
CTPPS: era-related modifications - backport of #14616

### PR DESCRIPTION
**Pull request by grzanka**
Backport of #14616 merged into 81X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
... I can't recall if there is a dependent PR that may prevent testing.
will find out soon

**Comment by grzanka** [comment]
@slava77 can you first merge this one: #14696 ?

**Comment by slava77** [comment]
@cmsbuild please test
retesting to get a clean comparison set; the last attempt used too old IB and had to merge many things on top

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14716	de44b27
- defines ctpps_2016 era as a part of Run2_2016 and includes the totemRP unpackers and event content; backport from 81X is correct: changes are the same modulo small changes in the context lines.  #14616 is in 81X for a few days already
- jenkins tests pass and comparisons show no differences
- relying on tests with JetHT 273725, which includes CTPPS  (totem RP) in readout, done in 81X checkout

**Comment by slava77** [comment]
hold

this PR will change the event content
we need to sort out when it can happen in PropmtReco (related to changes in processing version, aquisition Era, etc). To be discussed in ORP or elsewhere.

**Comment by slava77** [comment]
@grzanka 
may I ask you to take out changes in 
Configuration/StandardSequences/python/RawToDigi_cff.py from this PR
when you make a backport of the local reco, please add it there.
This is to still be able to do backports in sequence of 81X merging and also minimize the number of PRs in 80X that change the set of running modules in the standard setup.

Please check/think of this being feasible with all the other PRs in the chain.

**Comment by grzanka** [comment]
@slava77 what do you mean by "backport of the local reco" ?

**Comment by slava77** [comment]
On 6/3/16 6:49 AM, Leszek Grzanka wrote:
> @slava77 <https://github.com/slava77> what do you mean by "backport of
> the local reco" ?

backport of
"CTPPS: TOTEM RP local reconstruction algorithms "
https://github.com/cms-sw/cmssw/pull/14605
I suppose, it's coming/needed as well.

**Comment by grzanka** [comment]
Usually I start preparing backport once PR is merged into 81X. Right now PR #14605 is not yet merged.
I can fix it on Monday.

**Comment by slava77** [comment]
On 6/3/16 12:57 PM, Leszek Grzanka wrote:
> Usually I start preparing backport once PR is merged into 81X. Right now
> PR #14605 <https://github.com/cms-sw/cmssw/pull/14605> is not yet merged.
> I can fix it on Monday.

I don't need a change in #14605 or its backport now.
Now I need the change in
Configuration/StandardSequences/python/RawToDigi_cff.py
removed from this PR.
It will allow to continue backports and will not introduce problems with
data operations.

**Comment by grzanka** [comment]
@slava77 I've removed change to Configuration/StandardSequences/python/RawToDigi_cff.py from PR #14716 (this one) as you requested. 

I will add it back to backport of #14605 once it will be merged into 81X.

**Comment by slava77** [comment]
@cmsbuild please test

@grzanka thank you.

**Comment by slava77** [comment]
unhold

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14716	6de7cf9
- since the previous commit, the requested update to this PR was implemented: changes that modify standard sequences were removed for the moment to be able to continue CTPPS code integration and to not interfere with data taking operations (changes in event content lead to need for primary dataset version updates)
- jenkins tests pass and comparisons show no differences

**Pull request merged**
