### PR TITLE
add new pixelShape for phase1

### PR DESCRIPTION
**Pull request by VinInn**
Title says all.
Trained on 910_pre3.
It improves in particular in FPIX (data as well)

expect regressions

99p9 file added in case one desires to test it on BPIX1 ...

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@venturia @veszpv @boudoul @kandrosov @arizzi @gpetruc FYI

**Comment by VinInn** [comment]
MC ttbar PU35 930_pre1
 (old vs new, mind the scale)
FPIX
PastedGraphic-145.png
BPIX
PastedGraphic-146.png

**Comment by VinInn** [comment]
Data
slide2

**Comment by VinInn** [comment]
MTV
http://innocent.home.cern.ch/innocent/RelVal/pu35_newpcsf/plots_summary.html

**Comment by slava77** [comment]
The color plots are unreadable due to bad resolution.
Is there a PDF version of it?

**Comment by VinInn** [comment]
[pcsf.pdf](https://github.com/cms-sw/cmssw/files/1133070/pcsf.pdf)

**Comment by slava77** [comment]
On 7/8/17 8:49 AM, Vincenzo Innocente wrote:
> pcsf.pdf <https://github.com/cms-sw/cmssw/files/1133070/pcsf.pdf>

thanks.
This is marginally better.

**Comment by slava77** [comment]
On 7/8/17 8:44 AM, Vincenzo Innocente wrote:
> MTV
> http://innocent.home.cern.ch/innocent/RelVal/pu35_newpcsf/plots_summary.html

On average, it looks like the efficiency is unchanged, while fake rates
are up.
Or is there some other argument why this is overall better?


for "all tracks" by iteration, the detachedTriplet and mixedTriplet look
the worst.
Does this need a retuning of MVA selections?

**Comment by slava77** [comment]
> Trained on 910_pre3

The Vcal change showed up after that and has some noticeable effects on charge distribution in MC

from comparisons here, changes in performance are fairly small.
Would they change significantly if training was redone post-Vcal change?

**Comment by VinInn** [comment]
Eventually. MVA retuning is in the cooking (there are other issues as well).
It was one of the reason that we did not updated yet the cluster shape filter.
Seen the situation with data, it is obvious that "retuning" will go on for a (long) while.

it is better because it is more efficient in FPIX (more uniform as well)

**Comment by VinInn** [comment]
@kandrosov will retrain, and we will see...

**Comment by slava77** [comment]
On 7/8/17 9:12 AM, Vincenzo Innocente wrote:
> Eventually. MVA retuning is in the cooking (there are other issues as well).
> It was one of the reason that we did not updated yet the cluster shape
> filter.
> Seen the situation with data, it is obvious that "retuning" will go on
> for a (long) while.
> 
> it is better because it is more efficient in FPIX (more uniform as well)

Please clarify which plots show this most convincingly?

In general tracks both all and HP plots show essentially no change
(<0.3%) up to |eta| of 2,
while the fake rate is up in this same region.

http://innocent.home.cern.ch/innocent/RelVal/pu35_newpcsf/plots_ootb/effandfake1.pdf
http://innocent.home.cern.ch/innocent/RelVal/pu35_newpcsf/plots_highPurity/effandfake1.pdf

There is perhaps up to 0.5% increase in efficiency for |eta|>2.
It also looks like the fakes are somewhat unchanged in this region,
which is good.
Is this the improvement in FPIX?


Given that the update was made based on 910_pre3,
is it still consistent with the changes in BPIX geometry?
(I don't know the level of detail in the parameterization file if it
goes down to the phi index)

If the main argument is the improvement in FPIX,
can this update be restricted to the range relevant to this forward
region only?

**Comment by VinInn** [comment]
@slava, @kandrosov will provide you details: he is the expert.
from the top row of the 2D plots of the DQM is is obvious that the old one is wrong in FPIX
(both MC and data) and this is consistent with the fact the largest changes in 910_pre3 were in FPIX
@veszpv and @venturia can provide you details.

I observed an increase of single pixel clusters associated to tracks in data in the barrel where a much longer is predicted: not clear if it is a side effect or a feature of the new filter

**Comment by VinInn** [comment]
let me close this.
@kandrosov is making a new calibration with 930_pre1.
Either solves the issue in the barrel or we need to understand deeper

**Pull request closed without merging**
