### PR TITLE
PPS renaming AlCa Prompt producers and PPSCalTrackBasedSel AlCa Reco to autoAlca.py

### LINKED ISSUE #53: Rename PPS ALCARECOs
PPS ALCARECOs have to be renamed because for the AlCaPrompt step, the AlCaPrompt producers need to have the following string in the name: "PromptCalibProd" as it is required here: https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/python/Impl/AlCa.py#L63

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR is a refactoring (renaming) of the AlCa Prompt producers responsible for PPS Timing Calibration.
It resolves cms-AlCaDB/AlCaTools#53 

The changes are necessary for T0 replay with PPS. The suggestions for renaming appeared in the discussion of #36273
It is following https://github.com/cms-sw/cmssw/pull/36698

This PR initially contained refactoring of PPS timing calibration producers (hence the branch name `CTPPS:pps_timing_calibration_tier0_renaming`).
As suggested in https://github.com/cms-sw/cmssw/pull/36702#issuecomment-1018693912
I've merged here as well commits from other PRs:
- https://github.com/cms-sw/cmssw/pull/36730
- https://github.com/cms-sw/cmssw/pull/36698
- https://github.com/cms-sw/cmssw/pull/36707

#### PR validation:

Tested with:
```
runTheMatrix.py -l 1041 --ibeos
runTheMatrix.py -l 1042 --ibeos
```

### CODE REVIEW

**Comment by grzanka** [comment]
@malbouis @tvami FYI

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by yuanchao** [comment]
@cmsbuild please abort

**Comment by yuanchao** [comment]
test parameters:

    workflows=1042

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by yuanchao** [comment]
+1
* renaming of the AlCa Prompt producers for PPS
* matrix WF tests passed

**Comment by srimanob** [comment]
+Upgrade

This PR is considered as technical, to rename (refactor) PPS workflow on calibration.

**Comment by malbouis** [comment]
@cms-sw/pdmv-l2 , this PR too, like PR #36698 is purely technical. Would you please consider signing it?

**Comment by kskovpen** [comment]
+1

**Comment by tvami** [comment]
urgent

**Comment by perrotta** [comment]
@grzanka @ChrisMisan if we attempt to merge together the three PPS/AlCa PRs #36702, #36707 and #36730, the first two conflict with each other, as they attempt to modify the same files in contiguos lines.

May I suggest you to merge all them in one single PR, resolving the conflicts where needed?

The sooner you proceed with the new file, the higher the chance to have them integrated quickly.

**Comment by grzanka** [comment]
> @grzanka @ChrisMisan if we attempt to merge together the four PPS/AlCa PRs #36698, #36702, #36707 and #36730, the first three conflict with each other, as they attempt to modify the same files in contiguos lines.
> 
> May I suggest you to merge all them in one single PR, resolving the conflicts where needed?

@perrotta Do you prefer a completely new PR or merging all commits from other PRs into this one ?

**Comment by perrotta** [comment]
> @perrotta Do you prefer a completely new PR or merging all commits from other PRs into this one ?

No strong opinion, whatever you prefere.
In any case, please adapt the title of the PR and its description to take all updates into account.

**Comment by grzanka** [comment]
> > @perrotta Do you prefer a completely new PR or merging all commits from other PRs into this one ?
> 
> No strong opinion, whatever you prefere. In any case, please adapt the title of the PR and its description to take all updates into account.

In that case, I fill first merge commits from other PRs onto this one (fixing the conflicts if needed) and then modify the title and description.

**Comment by tvami** [comment]
@grzanka please also add the text "resolves https://github.com/cms-AlCaDB/AlCaTools/issues/53 " in the final PR description, thanks! (Just so that github connects these issues)

**Comment by grzanka** [comment]
> > @perrotta Do you prefer a completely new PR or merging all commits from other PRs into this one ?
> 
> No strong opinion, whatever you prefere. In any case, please adapt the title of the PR and its description to take all updates into account.

It's done now, all commits are merged into this PR.

**Comment by grzanka** [comment]
> @grzanka please also add the text "resolves [cms-AlCaDB/AlCaTools#53](https://github.com/cms-AlCaDB/AlCaTools/issues/53) " in the final PR description, thanks! (Just so that github connects these issues)

Done

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+1
 * tests pass except for the known issues
 * the PR is techincal, just renames files so that T0 can recognize them

**Comment by tvami** [comment]
Hi @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 please consider signing it again, there was nothing changed from what you already signed earlier

**Comment by srimanob** [comment]
+Upgrade

Technical PR on renaming of PPS Timing Calibration alca prompt producer. PR test runs fine.

**Comment by kskovpen** [comment]
+1

**Comment by tvami** [comment]
Hi @perrotta @qliphy this is essentially fully signed now, let's merge it and then have a backport to 12_2_X

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
