### PR TITLE
CMSSW_7_5_X DQM updates for AlphaT HLT paths (v2)

### PR DESCRIPTION
**Pull request by MarkBaber**
Addition of DQM monitoring to new AlphaT path, supersedes https://github.com/cms-sw/cmssw/pull/10704

Addition of DQM monitoring for the following HLT paths:
- HLT_PFHT200_PFAlphaT0p51_v
- HLT_PFHT200_DiPFJetAve90_PFAlphaT0p57_v
- HLT_PFHT250_DiPFJetAve90_PFAlphaT0p55_v
- HLT_PFHT300_DiPFJetAve90_PFAlphaT0p53_v
- HLT_PFHT350_DiPFJetAve90_PFAlphaT0p52_v
- HLT_PFHT400_DiPFJetAve90_PFAlphaT0p51_v

Remove number of monitoring histograms

### CODE REVIEW

**Comment by danduggan** [comment]
please test
@MarkBaber, yes please do close your other PRs and we'll continue with these.

**Comment by danduggan** [comment]
+1
@MarkBaber, the difference in bins is much more manageable now. for the direct commenting out of code, it's not too pretty and I'd avoid it, but I'll let @davidlange6 comment on integrating as is.

**Comment by MarkBaber** [comment]
https://github.com/cms-sw/cmssw/pull/10877 has been merged, can we also merge this?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
