### PR TITLE
re-organize workflows exercising the `SiPixelAliHGCombined` PCL workflow

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Better usage of relval resources: exercise the new `PromptCalibProdSiPixelAliHGComb` workflow introduced at https://github.com/cms-sw/cmssw/pull/43721 only on di-muon resonant data in the newly added workflow `1001.4` , while it is removed on the existing ones `1001.2` and `1001.3` which run over ZeroBias and SingleMuon data.

#### PR validation:

`runTheMatrix.py -l 1001.2,1001.3,1001.4 -t 4 -j 8 --ibeos` runs

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be backported to CMSSW_14_0_X.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1001.2, 1001.3, 1001.4

**Comment by mmusich** [comment]
please test for CMSSW_14_0_ASAN_X

**Comment by mmusich** [comment]
please test for CMSSW_14_1_ASAN_X

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 any comment about this?

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
