### PR TITLE
Change Phase-2 CPE unit test to use T21 geom

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Follow up to https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1262186076
Change Phase-2 CPE unit test to use T21 geom

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, and backport is not needed

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-data/CalibTracker-SiPixelESProducers/pull/3

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
The relevant unit test
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b0c67e/27912/unitTests/src/CondTools/SiPixel/test/createDBObjecs/testing.log
already passed

**Comment by tvami** [comment]
+db
 * needs to merge with https://github.com/cms-data/CalibTracker-SiPixelESProducers/pull/3

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
ping bot
(once again... @smuzaffar bot is working intermittently today)

**Pull request merged**
