### PR TITLE
More esConsumes migration in the Alignment area

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of https://github.com/cms-sw/cmssw/issues/31061

Packages migrated to esConsumes:
   * `Alignment/CommonAlignment`
   
Packages partially migrated:
   * `Alignment/HIPAlignmentAlgorithm`
   *  `Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc ` 

#### PR validation:

Compilation + `scramv1 b run tests` + `runTheMatrix.py -l 1001.0 -t 4`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, no backport is needed.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1001.0

**Comment by christopheralanwest** [comment]
please test

**Comment by yuanchao** [comment]
+1
* migrate to recommended esConsumes (HIPAlignmentAlgorithm.cc & MillePedeAlignmentAlgorithm.cc not yet)
* WF matrix tests and unit tests all passed
* Static build warnings are from those not yet migrated modules

**Comment by silviodonato** [comment]
+1

**Pull request merged**
