### PR TITLE
PAT btag update (80X)

### PR DESCRIPTION
**Pull request by ferencek**
A follow-up to #13098 that synchronizes PAT with the recent cleanup of old b-taggers. No changes to RECO but it affects MiniAOD by updating the list of default b-taggers stored with slimmed jets.

This is a 80X backport of #13685 and if possible, would like to include it in the 80X MiniAOD production together with #13605.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
An extended test of workflow 25202.0_TTbar_13 with 70 events against baseline CMSSW_8_0_2 shows no significant differences. There is no change in RECO event content. Mini-AOD event content shows very small increases in patJets collections:

```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
   1531.6 ->      1538.2          7      0.4   0.01     patJets_slimmedJetsAK8__RECO.
   3515.6 ->      3545.6         30      0.9   0.04     patJets_slimmedJets__RECO.
   2561.5 ->      2577.5         16      0.6   0.02     patJets_slimmedJetsPuppi__RECO.
-------------------------------------------------------------
    79862 ->       79914         53             0.1     ALL BRANCHES
```

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13686 1c63730fead56d14525fb9ae6c13e681a2c5083f

Small b-tag update for patJets.

#13685 is the 81X version of this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-03-08-2300 show no significant differences, as expected. As discussed above, patJets collections in Mini-AOD increase in size very slightly, but RECO event content is unchanged.

**Pull request merged**
