### PR TITLE
Run3-sim123 Update the validation scripts for HFNose in Validation/HGCalValidation and macros in SimG4CMS/Calo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the validation scripts for HFNose in Validation/HGCalValidation and macros in SimG4CMS/Calo

#### PR validation:

Use the scripts in the test directories

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
