### PR TITLE
Adding cosmics path for HLT validation (110X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Adding cosmics path for HLT validation (110X)
Based on CMSSW_11_0_X_2019-10-06-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@Martin-Grunewald are the differences seen in the DQM test expected? They do not seem spurious, and involve non cosmics samples, I would like to ensure they are related to the changes introduced by this PR in an understood way

**Comment by Martin-Grunewald** [comment]
Well, the newly added path is run on ALL samples, not just cosmics samples, as it is part of the GRun menu used nearly everywhere!

**Comment by fabiocos** [comment]
@Martin-Grunewald sure, I understand that the differences you observe are expected ones (running a cosmics path on top of a TTbar event...)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
