### PR TITLE
Phase2-hgx325B Try to understand the issue of missing silicon rechits in the D88 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to understand the issue of missing silicon rechits in the D88 geometry of HGCal

#### PR validation:

Test the new codes with the scripts in Validation/HGCalValidation/scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by pfs** [comment]
@bsunanda just a clarification: this PR is mostly a validation plugin to check the missing hits? i.e., not a proposed fix by itself?

**Comment by bsunanda** [comment]
@pfs We have not found out a solution. But we understood from the study that some SimHits do not appear as RecHits. We need a more systematic study for this

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
type hgcal

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
