### PR TITLE
bsunanda:Run2-hcx11 Add new products required for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
Extend DetId to forward detectors in view of HGCal and related detectors. Also add definitions for Digi and RecHit

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , I may be miss something, where boost is used in these codes?

**Comment by bsunanda** [comment]
Removed boost from BuildFile and dependency on messagelogger in codes which do not use it
________________________________

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
there are few unittest which are failing due to this in the latest 75X IB. Looks like duplicate
DataFormats/HGCDigi/src/classes_def.xml:   <class name="HGCEEDetId"/>
DataFormats/ForwardDetId/src/classes_def.xml:  <class name="HGCEEDetId" ClassVersion="13">

**Pull request merged**
