### PR TITLE
Use standard fitters

### PR DESCRIPTION
**Pull request by a-kapoor**
Standard full sim fitters used in 7 iterations of fastsim:
1)DetachedTripletStep
2)InitialStep
3)LowPtTripletStep
4)MixedTripletStep
5)PixelLessStep
6)PixelPairStep
7)TobTecStep

### CODE REVIEW

**Comment by lveldere** [comment]
@ANSH0712 

would you mind removing the lines, 
rather than commenting out?

how does the CPU consumpton change?

**Comment by ANSH0712** [comment]
Done !
I have made three tests.. The full sim fitter changes have resulted in upto
20% increase in time consumption

On Fri, Jan 22, 2016 at 2:37 PM, lveldere <notifications@github.com> wrote:

> @ANSH0712 <https://github.com/ANSH0712>
>
> would you mind removing the lines,
> rather than commenting out?
>
> how does the CPU consumpton change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173854783>.
>



-- 
ANSHUL KAPOOR
Research Student at IISER Pune
-----Please Don`t Spam----------
anshul.kapoor@cern.ch
anshul.kapoor@students.iiserpune.ac.in

**Comment by lveldere** [comment]
What cmsDriver command did you use to measure the time consumption?



---------- Forwarded message ----------

**Comment by ANSH0712** [comment]
I used the user+sys output of basic linux "time" command. Considering the
only changes I was comparing were mine, any differences in user+sys time
would be only because of these changes.

On Fri, Jan 22, 2016 at 2:48 PM, lveldere <notifications@github.com> wrote:

> What cmsDriver command did you use to measure the time consumption?
>
>
>
> ---------- Forwarded message ----------
> From: Anshul Kapoor <notifications@github.com>
> Date: Fri, Jan 22, 2016 at 10:13 AM
> Subject: Re: [cmssw] Use standard fitters (#13031)
> To: cms-sw/cmssw <cmssw@noreply.github.com>
> Cc: lveldere <lukasvanelderen@gmail.com>
>
>
> Done !
> I have made three tests.. The full sim fitter changes have resulted in upto
> 20% increase in time consumption
>
> On Fri, Jan 22, 2016 at 2:37 PM, lveldere <notifications@github.com>
> wrote:
>
> > @ANSH0712 <https://github.com/ANSH0712>
> >
> > would you mind removing the lines,
> > rather than commenting out?
> >
> > how does the CPU consumpton change?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173854783>.
> >
>
>
>
> --
> ANSHUL KAPOOR
> Research Student at IISER Pune
> -----Please Don`t Spam----------
> anshul.kapoor@cern.ch
> anshul.kapoor@students.iiserpune.ac.in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173855776>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173856708>.
>



-- 
ANSHUL KAPOOR
Research Student at IISER Pune
-----Please Don`t Spam----------
anshul.kapoor@cern.ch
anshul.kapoor@students.iiserpune.ac.in

**Comment by lveldere** [comment]
Thanks, but which cmsDriver command were you running?
I need to know what you tested exactly.
Lukas

**Comment by ANSH0712** [comment]
This was the exact command.
cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi \
--conditions auto:run2_mc --fast -n 1000 \
--era Run2_25ns \
--magField 38T_PostLS1 --beamspot NominalCollision2015 \
--datatier AODSIM,DQMIO --eventcontent AODSIM,DQM \
-s
GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,RECO,VALIDATION:tracksValidationTrackingOnly
\
--python_filename fastsim.py --fileout fastsim.root

On Fri, Jan 22, 2016 at 2:59 PM, lveldere <notifications@github.com> wrote:

> Thanks, but which cmsDriver command were you running?
> I need to know what you tested exactly.
> Lukas
>
> On Fri, Jan 22, 2016 at 10:23 AM, Anshul Kapoor <notifications@github.com>
> wrote:
>
>
> > I used the user+sys output of basic linux "time" command. Considering the
> > only changes I was comparing were mine, any differences in user+sys time
> > would be only because of these changes.
> >
> >
> > On Fri, Jan 22, 2016 at 2:48 PM, lveldere <notifications@github.com>
> > wrote:
> >
> > > What cmsDriver command did you use to measure the time consumption?
> > >
> > >
> > >
> > > ---------- Forwarded message ----------
> > > From: Anshul Kapoor <notifications@github.com>
> > > Date: Fri, Jan 22, 2016 at 10:13 AM
> > > Subject: Re: [cmssw] Use standard fitters (#13031)
> > > To: cms-sw/cmssw <cmssw@noreply.github.com>
> > > Cc: lveldere <lukasvanelderen@gmail.com>
> > >
> > >
> > > Done !
> > > I have made three tests.. The full sim fitter changes have resulted in
> > upto
> > > 20% increase in time consumption
> > >
> > > On Fri, Jan 22, 2016 at 2:37 PM, lveldere <notifications@github.com>
> > > wrote:
> > >
> > > > @ANSH0712 <https://github.com/ANSH0712>
> > > >
> > > > would you mind removing the lines,
> > > > rather than commenting out?
> > > >
> > > > how does the CPU consumpton change?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173854783>.
> > > >
> > >
> > >
> > >
> > > --
> > > ANSHUL KAPOOR
> > > Research Student at IISER Pune
> > > -----Please Don`t Spam----------
> > > anshul.kapoor@cern.ch
> > > anshul.kapoor@students.iiserpune.ac.in
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173855776>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173856708>.
> >
> > >
> >
> >
> >
> > --
> > ANSHUL KAPOOR
> > Research Student at IISER Pune
> > -----Please Don`t Spam----------
> > anshul.kapoor@cern.ch
> > anshul.kapoor@students.iiserpune.ac.in
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173858985>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/13031#issuecomment-173860161>.
>



-- 
ANSHUL KAPOOR
Research Student at IISER Pune
-----Please Don`t Spam----------
anshul.kapoor@cern.ch
anshul.kapoor@students.iiserpune.ac.in

**Comment by lveldere** [comment]
In that case 20% is definitely too much...
Let's keep this for testing purposes for now.

**Comment by ANSH0712** [comment]
Should I close the pull request then ?

**Comment by lveldere** [comment]
unfortunately yes.

**Comment by lveldere** [comment]
please test

**Comment by ANSH0712** [comment]
Latest estimates on timing do not show any significant change. May be we can merge this pull request.

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
