### PR TITLE
Run3-gex136B Handle compilation warnings in CalibMuon/CSCCalibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Handle compilation warnings in CalibMuon/CSCCalibration

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type performance-imporvements,csc

**Comment by ChrisMisan** [comment]
+alca
- changes in the results are in the message logger and MTD, where are expected
- theAverageGain might be thread unsafe but it was not a part of the PR https://github.com/cms-sw/cmssw/blob/9e24389184eed64841f7ff8f90c34ca59eb2e25b/CalibMuon/CSCCalibration/interface/CSCConditions.h#L199

**Comment by perrotta** [comment]
+1

**Pull request merged**
