### PR TITLE
HCALDQM: fix castorDigis.InputLabel for heavy ion run type

### PR DESCRIPTION
**Pull request by DryRun**
Important fix for HCALDQM for the XeXe run: the InputLabel of process.castorDigis should be rawDataRepacker for heavy ion runs, not rawDataCollector.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
I assume there is a 92x PR, right?

**Comment by DryRun** [comment]
Hi @dmitrijus -- I added this commit to the existing online DQM PR at https://github.com/cms-sw/cmssw/pull/20111, which we have basically given up on merging. For this small fix, should I make a standalone PR?

**Comment by dmitrijus** [comment]
No, no need. I guess you want it for online DQM and online DQM already runs #20111
We should try to get #20111 merged.

It's huge and it is somewhat unclear what it does (and how it affects the memory usage), so there is reluctance to get it merged. Please write to @davidlange6 if you really need it merged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
