### PR TITLE
Adding HTXS stage 1.2 classification (106X backport)

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This adds the HTXS stage 1.2 classification, keeping stage 1.1, 1 and 0 available 

#### PR validation:

Verified to run correctly using runRivetHTXS_cfg.py

#### if this PR is a backport please specify the original PR:

backport of #28444 , needed for nanoAOD

### CODE REVIEW

**Comment by qliphy** [comment]
Adding @intrepid42 @xjanssen

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by adewit** [comment]
Hi - this hasn't moved for nearly 2 weeks. Who should I ping to bring this up in the next release meeting?

**Comment by fabiocos** [comment]
@adewit there is not automatism for backports, in general they are linked to a validation of the master version https://cms-sw.github.io/PRWorkflow.html . And this code has been only recently integrated in the master branch.
In this specific case, this PR (and its 10_2_X version #28464) is affecting the nanoAOD output in my understanding: @peruzzim @fgolf could you please comment about these backport requests? Should this be linked to a next nanoAOD campaign?

**Comment by peruzzim** [comment]
@fabiocos we envisage to include the stage 1.2 HTXS in the next NanoAOD campaign.
If this is a faithful backport of #28444 (which I have not checked, it's not easy to do because of a lot of code format changes included in this PR), then I understand that the stage 1.2 classification is added next to the existing stage 1 and 1.1 (these are the ones currently saved in NanoAOD).
Therefore I would not expect this PR to break the consistency of any existing workflow.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
not impacting the existing nanoAOD

**Pull request merged**
