### PR TITLE
Concurrently run beginStreams

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Have each stream's beginStream transition run in its own TBB task.

#### PR validation:

Code compiles. Framework unit tests pass.

NOTE: It could very well be that CMSSW modules are doing thread unsafe activities in beginStream. This change needs to be tests on a large sample of multi-threaded jobs.

### CODE REVIEW

**Comment by makortel** [comment]
> NOTE: It could very well be that CMSSW modules are doing thread unsafe activities in beginStream. This change needs to be tests on a large sample of multi-threaded jobs.

@smuzaffar Should we put this in for DEVEL first?

**Comment by Dr15Jones** [comment]
> Should we put this in for DEVEL first?

that is what I was thinking

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
> > Should we put this in for DEVEL first?
> 
> that is what I was thinking

yes sounds reasonable.

**Comment by smuzaffar** [comment]
enable threading

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
The PR looks good to me. I'm a bit hesitant to give `+1` though when the target branch is still `master`.

**Comment by smuzaffar** [comment]
+core
I have changed the base branch to 12.1.DEVEL now. @qliphy , @perrotta can you please merge it before 11am today so that i can we can test this change in 11h00 DEVEL IBs?

**Comment by perrotta** [comment]
+1
- Here it is, for DEVEL IBs by now

**Pull request merged**
