### PR TITLE
Cell offset and Cell area calculation of partial wafer cells for HGCAL V18

### PR DESCRIPTION
**Pull request by bhattlokesh2027**
PR description:
The cells present along the cut of partial wafer have irregular shape, so PR includes calculation of centroid and area of these cells.

PR validation:
This PR is only meant for V18 version of HGCAL with testing script added in the PR.

If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
@cmsbuild please test with 27234.0

Test should be done on affected geometry, i.e. D104 with C22 (V18 HGCAL).

**Comment by srimanob** [comment]
@cmsbuild  please test with 27234.0

**Comment by srimanob** [comment]
Hi @smuzaffar 
It seems the test is never done. Will trigger again help?

**Comment by srimanob** [comment]
@cmsbuild please test with 27234.0

**Comment by srimanob** [comment]
@smuzaffar @rappoccio @antoniovilela 
Could you please help to trigger the test as above? I tried several times in past few weeks, and it never work. Thanks.

**Comment by makortel** [comment]
@cmsbuild, please test workflow 27234.0

**Comment by srimanob** [comment]
> @cmsbuild, please test workflow 27234.0

Ah, I use the wrong word. Thanks @makortel

**Comment by srimanob** [comment]
@cmsbuild, please test workflow 27234.0

**Comment by bsunanda** [comment]
@srimonab Please sign this

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
@bhattlokesh2027 
Please write meaningful commit messages explaining what is addressed in each commit. You may also squash the commits into a single one [1]. If the squash is done correctly, the PR will not need to be re-signed.
Thanks.

[1]
https://cms-sw.github.io/faq.html#how-do-i-collapse-multiple-commits-into-one
https://git-scm.com/book/en/Git-Tools-Rewriting-History
N.B.
Always create a backup branch.
Check locally before (force-)pushing to the PR branch.

**Comment by antoniovilela** [comment]
@bhattlokesh2027
ping

**Comment by bhattlokesh2027** [comment]
Extremely sorry for the late reply and bad commit messages.
Should I use " git reset " and " git commit --amend " or should I use the " git rebase -i " command to avoid resign.

**Comment by bsunanda** [comment]
I believe you make your comments in the git page and do not change the code in the repository.
________________________________

**Comment by bhattlokesh2027** [comment]
second commit was made to address the excess bracket and removing some edm.
third commit was made to address code formatting.

**Comment by antoniovilela** [comment]
You may also simply update the commit messages to sometrhing meaningful (as in https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Comment by bhattlokesh2027** [comment]
@antoniovilela 
Sorry for the delay, I have updated the commit messages. Please let me know if any further changes are required.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
