### PR TITLE
Remove LeptonVertexSignificance as obsolete

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of https://github.com/cms-sw/cmssw/issues/31061. I encountered this class by pure chance when looking around in the static analyzer. Given that its constructor signature `LeptonVertexSignificance(const edm::EventSetup& iSetup, edm::ConsumesCollector&& iC)` can not have ever worked (`ConsumesCollector` argument was added in #1126) and that the class is not used anywhere in CMSSW, I decided to try to remove it.

#### PR validation:

None.

### CODE REVIEW

**Comment by slava77** [comment]
-1

superseded by #35680 
`LeptonVertexSignificance` gets to live another day.

**Comment by makortel** [comment]
I don't really understand why we want to keep code that has been unused (an unusable) for 8+ years, but fine.

**Comment by slava77** [comment]
> I don't really understand why we want to keep code that has been unused (and unusable) for 8+ years, but fine.

in this case @Dr15Jones made an update in parallel with this PR and it seemed perhaps differently wasteful to abandon that work.

**Comment by Dr15Jones** [comment]
I don’t care if the code I changed goes away.

**Pull request closed without merging**
