### PR TITLE
Reorganise RecoMuon/L2MuonProducer plugins

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Move plugins from the `src` to the `plugins` directory, and merge the header and source files.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
please test
(It is hard to imagine how all those quite significant differences in the miniAOD slimmed jets can come from this PR: let try to relaunch the tests once more. just in case...)

**Comment by davidlange6** [comment]
These differences were understood on Thursday to be due to non-deterministic sorting in python. Its fixed now if I understand.

**Comment by perrotta** [comment]
> These differences were understood on Thursday to be due to non-deterministic sorting in python. Its fixed now if I understand.
> 

Thank you @davidlange6 
Let have a look at the new test results then, once available

**Comment by slava77** [comment]
> DQMHistoTests: Total failures: 892

these are apparently from TimingService. I thought that these diffs were skipped/ignored before.
@smuzaffar do you know?

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34399  714a55c
- code changes are technical, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by smuzaffar** [comment]
@slava77 , yes looks like moving Relmon to python3 is not skipping the timing services related stuff. @davidlange6 is looking in to it.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
