### PR TITLE
GT Updates : Fixing HLT and Prompt-like GTs to fix PR20568

### PR DESCRIPTION
**Pull request by arunhep**
update of HLT and Prompt GT to fix #20568

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@davidlange6 here is the fix of #20568

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by smuzaffar** [comment]
please test workflow 136.769,136.779

**Comment by davidlange6** [comment]
merge

**Pull request merged**
