### PR TITLE
add L1nano NANO in Prompt/Tier0 configuration [130X]

### PR DESCRIPTION
**Pull request by vlimant**
plain backport of #41868

### CODE REVIEW

**Comment by perrotta** [comment]
Thank you @vlimant 
Could you also prepare an identical backport for the intermediate release 13_1_X, so that we won't forget it?

About the tests: is there any workflow/unit test that can try it, or should we just "please run", and merge once those tests succeed?

**Comment by drkovalskyi** [comment]
Looks good for Tier0.

**Comment by perrotta** [comment]
please test

**Comment by vlimant** [comment]
`python3 $CMSSW_BASE/src/Configuration/DataProcessing/test/RunPromptReco.py --scenario ppEra_Run3 --reco --aod --miniaod --nanoaod --dqmio  --alcareco TkAlMinBias+SiStripCalMinBias --lfn=/store/data/Run2023C/HLTPhysics/RAW/v1/000/368/382/00000/86a26e18-1c93-48f2-a4bd-384d1cca7dbf.root  --global-tag 130X_dataRun3_Prompt_v3 ran` successfully  as in 13.2, and the L1 branches were present

**Comment by perrotta** [comment]
> Could you also prepare an identical backport for the intermediate release 13_1_X, so that we won't forget it?

I made such a backport for 13_1_X, see #41889
This can be safely merged, then

**Pull request merged**
