### PR TITLE
Add filter for intermediate resonance particles [10_6_X]

### PR DESCRIPTION
**Pull request by jieunyoo**
Attempt to backport this request to 10_6_X
This is from PR # #40254

### CODE REVIEW

**Comment by perrotta** [comment]
This is highly badly coordinated. We have just built a 10_6_31_patch1 release, and I don't think we will be able to build another 10_6_X patch release in the coming days, due to more urgent requests queued.
Please @cms-sw/generators-l2 collect all requests from your group, and come to the ORP meeting with them.
I would suggest that starting from now whatever is not requested at the ORP is not dealt with by the release managers.

**Comment by jieunyoo** [comment]
Hi @perrotta . Thanks for the comment. It would be ok for the 10_6_X_patch release. Sorry for the trouble. I’m not familiar with this workflow. Is there a generators meeting I should go to to get this approved? Basically I want to get a UL sample made with this filter. What are the best and quickest ways to go about this since we need this signal sample for my thesis work. Without this filter, we would need say 10 million samples of the same thing requested, and that seems inefficient and I don’t know if it would be approved since it’s so large, so I was working on this filter.  Thanks !

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #40254

**Comment by menglu21** [comment]
> This is highly badly coordinated. We have just built a 10_6_31_patch1 release, and I don't think we will be able to build another 10_6_X patch release in the coming days, due to more urgent requests queued. Please @cms-sw/generators-l2 collect all requests from your group, and come to the ORP meeting with them. I would suggest that starting from now whatever is not requested at the ORP is not dealt with by the release managers.

@perrotta sorry for the inconvenience, we'll follow your suggestion.

**Comment by menglu21** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@jieunyoo please prepare similar backports for 12_4_X (for 2022 analyses) and 12_6_X

**Comment by Saptaparna** [comment]
Hi @perrotta yes, we were not notified in advance. Usually we would have had a presentation from the requester in the GEN meeting. In fact, yesterday I had a chat with the requester and pointed to an alternate way to generate samples instead of integrating this PR in the release. @jieunyoo just because the PR is merged doesn't mean that a new release will be available for your sample submission. The UL campaign has been operational for 2+ years, so why is this request being made now. Also, please request presentations in the GEN meeting in advance, so we have an idea of what to bring to Andrea and Sal's attention at the ORP meeting. There is a structure in place and bypassing the structure takes everyone by surprise.

**Comment by jieunyoo** [comment]
Hi. Thanks for the reply. Sure, I did not know about the workflow. I will definitely bring this up in the generators meeting. Could you please let me know which meeting I need to attend and add my name? I will send you an email as well requesting this. 
We just decided on my thesis topic this past September 2022. So that is why this request is being made now. I researched different ways to make a cut on the pT. My MC contact suggested at first to make a cut on bornktmin in the card, however after research and speaking with a Powheg author, we found out that is not the correct way. Determining this took time. Also, it took time to figure out that we could make such a filter. It also took time to find out that we would need a specific CMSSW pull request made in order to use this filter and ask for a sample to be made. I provided a custom CMSSW tar package to my MC contact, but we found out later that MCM can not take that.
So in conclusion there is currently no filter available for this. The only CMSSW filter available for a cut on pT is available for final state partons; none is available for intermediate resonances.
The alternative way to get this is to do private production of samples which takes time. I would like to request a MC production (going later through the MC channels) and the only way to request it officially is to get this in CMSSW since MC contacts don't deal with this.
If we do not have this filter, then in order to get enough statistics for the high pT region, we will need 10 times more samples. To not waste computational time, we hope to have this filter in CMSSW.
Are there plans for another to be made available @perrotta? What would be the timeline? I'm sure that there will be other fixes by other analysts for CMSSW_10_6_X since all UL analyses need to use this. I think this filter will also be useful for any other analysts who are doing an UL analysis on boosted topologies, and as I see it now, many boosted analyses are in the works. My apologies if my timing was bad in requesting this. This is my first time editing CMSSW. Also, I wasn't aware of these different release cycles or deadlines, but now I'm subscribed to your CMSTalk channel and will follow them and know better next time. Thank you!

**Comment by Saptaparna** [comment]
@jieunyoo I understand. You are more than welcome to present your work and plans with timeline at GEN meeting on Monday (the meeting starts at 14:00 CERN and I will send you the coordinates via email).

**Comment by Saptaparna** [comment]
@perrotta and @rappoccio Would it be possible for us to create a new release with this PR so the analysts can request samples? thanks! :)

**Pull request merged**
