### PR TITLE
New Tests PR Tests for HIN 2023 and 2024

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR proposes:
- the addition of two HIN MC workflows for PR tests for 2023 and 2024 conditions;
- the addition of default input datasets for `HIN2023` and `HIN2024` conditions.

#### PR validation:

Tests run.

I think a backport to `14_1_X` would be useful.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test with #46418

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
