### PR TITLE
fix script by changing run number and example tags to working ones (using CMS Phase-I geometry)

### PR DESCRIPTION
**Pull request by tlampen**

### CODE REVIEW

**Comment by ghellwig** [comment]
@tlampen why this PR?
what's wrong with the current version of the script that I just updated a few days ago?

**Comment by ghellwig** [comment]
@tlampen to be more precise: Your changes are bound to break the unit test in which the script is called because you use an sqlite file on afs which can vanish, while using the auto GT and a tag from the database is certainly a better choice.

**Comment by ghellwig** [comment]
-1

**Comment by tlampen** [comment]
Reason for this PR is that the current script does not work out-of-the box with the specified runs and geometries, which are from 2016, while the code is now compatible only with Phase-I geometries (the update of your PR). I just wanted to change the runs and geometries to ones of 2017.
I admit that specifying an sqlite file is a bad choice here. Which tag from DB works with auto:run2_data in 92X?

**Comment by ghellwig** [comment]
@tlampen what exactly does not work?
The current code works both for 2016 and 2017 geometries. I chose a geometry-independent configuration that selects the pixel modules, regardless of phase-0 or phase-1 geometry.
In addition you did not change the code, but just the example tags. Of course, we could change them at some point, but to use the tool you anyway have to change them to those you want to check.
Or am I missing a point here?

**Comment by ghellwig** [comment]
Btw. running the unit tests via `scram b runtests` will show you that the current script works because this is what is used in the unit tests.

**Comment by tlampen** [comment]
You are right, it indeed works with both geometries. I had a wrong impression about this, maybe because I didn't work in a fresh environment. I wanted to changed the example to tags to Phase-1 tags, but this isn't then necessary at the moment. Maybe this could be changed when a high-quality alignment is now produced with collision data.
Thanks for the tip about unit tests!

**Comment by ghellwig** [comment]
I agree, that it makes sense to check also a phase-1 run, but I would wait here still some time.
But, good that the open questions are resolved now.

**Comment by ghellwig** [comment]
Btw, could you also close this PR then?

**Comment by tlampen** [comment]
Ok, let's see later if we want to update to phase-1 example tags.

**Pull request closed without merging**
