### PR TITLE
Add histogram full name if exception happens in DQMRootSource

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is meant to help track down any future cases of problems while merging histograms during harvesting.

#### PR validation:

Code compiles and does show full histogram name when the exception is thrown.

### CODE REVIEW

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
I think that the logic error [pointed out](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-83f41b/28573/llvm-analysis/report-960b59.html#EndPath) by the static analyzer is true, and some check on the existence of `file` should be added before L563. As of now, the logic if `file = nullptr` looks buggy to me.

@cms-sw/dqm-l2 could you please have a look?

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
> I think that the logic error [pointed out](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-83f41b/28573/llvm-analysis/report-960b59.html#EndPath) by the static analyzer is true, and some check on the existence of `file` should be added before L563. As of now, the logic if `file = nullptr` looks buggy to me.
> 
> @cms-sw/dqm-l2 could you please have a look?

I've opened a PR with a possible fix for what reported by the static analyzer: #39895
Let continue the discussion over there

**Pull request merged**
