### PR TITLE
adding HLT_PFMET100_PFMHT100_IDTight_BeamHaloCleaned_v to Higgs DQM

### PR DESCRIPTION
**Pull request by safarzad**

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by safarzad** [comment]
The errors are not due to the new path, under investigation by Higgs trigger contact

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
(The same PR has no error in 81X and the base IB was identical to CMSSW_8_0_13_patch1....)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
