### PR TITLE
L1TGlobalProducer: migrate to stream module (80x)

### PR DESCRIPTION
**Pull request by fwyzard**
re-submission of #14351 after fixing a non-threadsafe construct

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
no crashes or hangs running over 100k collision events with 16 threads

**Comment by fwyzard** [comment]
Tested again over 100k collision events, with CMSSW_8_0_7_patch2 and without these commits:

> Found 0 events out of 100000 with differences

If anyone can think of other tests to do, please let me know.

**Comment by rekovic** [comment]
performing L1T unit tests

**Comment by rekovic** [comment]
will report shortly

**Comment by rekovic** [comment]
L1T unit tests passed

+1

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
This PR seems stuck in the "tests-started" label, even though tests have completed successfully.
Could you please have a look?
Thanks!

**Comment by smuzaffar** [comment]
@Martin-Grunewald , for now I have updated the "Tested at: " message to point to the latest commit '0fc6d42'. I will update PR testing job to use the correct commit next time

**Comment by mulhearn** [comment]
Thank you at @fwyzard, this is very much appreciated.

**Pull request merged**
