### PR TITLE
Add options to bypassVersionCheck in Merge step

### PR DESCRIPTION
**Pull request by srimanob**
Add options to bypassVersionCheck in Merge step to solve 
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4413.html

Not clear we will need, just in case.

### CODE REVIEW

**Comment by srimanob** [comment]
@fabiocos 
This PR is a conclusion from the discussion I have with @vlimant @amaltaro to solve the merging problem. Could you please review it quickly? The target for now is to 9_4_X to allow merging in HLT step (using RAW from 10_4/5/6) to happen. Thx very much.

**Comment by fabiocos** [comment]
From the discussions in https://github.com/dmwm/WMCore/issues/9054 and https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4413.html I understand that there is consensus in setting the default of the bypass option to True.

**Comment by fabiocos** [comment]
please test

not testing much in this contest

**Comment by fabiocos** [comment]
+operations

the updates to Configuration/DataProcessing are coherent with the stated purpose in the supporting discussion

**Comment by fabiocos** [comment]
+1

**Pull request merged**
