### PR TITLE
PFCaloJet and PFClusterJet

### PR DESCRIPTION
**Pull request by yongjiexin3**
These codes are for implementing the PFCaloJets and PFClusterJets. 
Test file is located here :  RecoJets/JetProducers/test/PFClusterJets_PFCaloJets_producer.py
To run it :  cmsRun PFClusterJets_PFCaloJets_producer.py

The twiki page describing these procedure and also the results are here: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/JMARPFCaloJetAndPFClusterJets

The most recent presentation about this is located here. 
https://indico.cern.ch/event/364109/contribution/3/material/slides/0.pdf

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
please update the subject of the PR (the top-most line) to be more descriptive instead of "E cal h cal calo jet linker"
please also add a link to a more recent presentation describing performance of the new code/sequences

**Comment by yongjiexin3** [comment]
Hi Slava,
         Thank you for the suggestions.  Requested information are added.

Cheers,
Yongjie

On Wed, Mar 4, 2015 at 5:29 PM, Slava Krutelyov <notifications@github.com>
wrote:

> please update the subject of the PR (the top-most line) to be more
> descriptive instead of "E cal h cal calo jet linker"
> please also add a link to a more recent presentation describing
> performance of the new code/sequences
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8033#issuecomment-77264289>.
>



-- 
Yongjie Xin
Research Assistant, Department of Physics and Astronomy,
Johns Hopkins University

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8033	161bde9

 tested in CMSSW_7_5_X_2015-03-04-0200 /sign524/ with a longer version of the matrix run by jenkins.

There are no changes in monitored quantities as expected from changes in this code.
The changes affect objects created in test workflows only at this point.
The test config file provided with this PR runs OK and the timing of the modules running in the test (no PU here though) appear similar to what's expected from PF or calo parts.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
