### PR TITLE
do not make release-based customisation depend on the runtime environment

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@Martin-Grunewald @silviodonato 
David asked (and I agree) not to make a check on the actual release at runtime. 

This is not particularly useful, as anyway we end up having different versions of the customisation file in different releases.

And it can be harmful - for example, it broke the CMSSW_8_3_0 build out of CMSSW_9_0_0_pre4 , because the version check did not pass there.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
