### PR TITLE
Use #include <...> for external headers

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Use `#include <...>` instead of `#include "..."` for external headers.

#### PR validation:

Full release builds and unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
The same unit test passes in a local working area:
```
Creating test log file logs/el8_amd64_gcc12/testing.log
Skip    0s ... FWCore/Utilities/typedefs_t (Disabled via BuildFile)
Pass    0s ... DataFormats/Math/DataFormatsDeltaR_t
Pass    0s ... DataFormats/Math/DataFormatsEta_t
Pass    0s ... DataFormats/Math/DataFormatsAsin_t
Pass    0s ... DataFormats/Math/DataFormatsMulSymMatrix_t
Pass    0s ... DataFormats/Math/DataFormatsProjectMatrix_t
Pass    0s ... DataFormats/Math/DataFormatsMatrices_t
Pass    0s ... DataFormats/Math/DataFormatsExtVec_t
Pass    0s ... DataFormats/Math/DataFormatsSign_t
Pass    0s ... DataFormats/Math/DataFormatsSSEVec_t
Pass    0s ... DataFormats/Math/DataFormatscrossV4_t
Pass    0s ... DataFormats/Math/testGraph
Pass    0s ... FWCore/Utilities/HRTime_t
Pass    0s ... FWCore/Utilities/testFWCoreUtilitiesCatch2
Pass    0s ... DataFormats/Math/testDataFormatsMathPacking
Pass    0s ... DataFormats/Math/testMathApproximations
Pass    0s ... FWCore/Utilities/RunningAverage_t
Pass    0s ... FWCore/Utilities/TestHelper_t_testAdler32
Pass    1s ... FWCore/Utilities/InputTag_t
Pass    1s ... FWCore/Utilities/TestHelper_t_testFriendlyNames
Pass    1s ... DataFormats/Math/DataFormatsFastMath_t
Pass    1s ... DataFormats/Candidate/testDataFormatsCandidate
Pass    2s ... DataFormats/Math/DataFormatsSimilarityFast_t
Pass    4s ... DataFormats/Math/DataFormatsSimilarity_t
Pass    5s ... DataFormats/Math/simpleCholeskyTest
Pass    6s ... DataFormats/Math/DFM_MathRepr
Pass    6s ... DataFormats/Math/DFM_Atan2
Pass    7s ... DataFormats/Math/DFM_Math
Pass    8s ... DataFormats/Math/CholeskyInvert_t
Pass    8s ... FWCore/Reflection/TestFWCoreReflectionDumpClassVersion
Pass    8s ... FWCore/Reflection/TestFWCoreReflectionCheckClassVersion
Pass   23s ... FWCore/Reflection/TestFWCoreReflectionClassVersionUpdate
Pass   24s ... FWCore/Utilities/testFWCoreUtilities
Pass   26s ... DataFormats/Math/CholeskyInvertOnGPU_t
Pass   33s ... DataFormats/Math/testMathApproxMath
Pass   63s ... DataFormats/Math/testAtan2FastMath
Pass  125s ... DataFormats/Math/testAtan2
Pass  125s ... DataFormats/Math/testAtan2VDT
```

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/46416 and https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
