### PR TITLE
[10.1.X] fix of IB test failures by updating the prompt GT

### PR DESCRIPTION
**Pull request by arunhep**
this is the fix for the problems mentioned here : #22865 (comment)
@fabiocos please merge this with #22834

### CODE REVIEW

**Comment by arunhep** [comment]
please test workflow 136.77,136.778

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
@arunhep are the changes in the 136.788 wf compared to the first set expected? In order to gain time in tests I have merged the combination of PRs, but I would like a confirmation of this.

**Comment by arunhep** [comment]
@fabiocos 
diff of global tags : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v9/101X_dataRun2_PromptLike_v7
shows the update of PF calibrations for hadronic part as well as EGM part and hence the differences.

**Comment by fabiocos** [comment]
@lpernie @arunhep at this point I assume we can close it, right?

**Comment by arunhep** [comment]
@fabiocos yup sure.

**Pull request closed without merging**
