### PR TITLE
EMTF DQM Update and Bugfix

### PR DESCRIPTION
**Pull request by swang373**
Updates to the EMTF firmware broke the monitor elements which relied on the track sector variables. This is currently patched such that the sector value is retrieved from the EventHeader, though updates are expected to be made to the unpacker that will affect this behaviour later on.

The CSC chamber numbering schemes are now correctly implemented with respect to the geometry outlined in "CMS IN-2007/024".

### CODE REVIEW

**Comment by dmitrijus** [comment]
Is there an 8_1_X version this?
It should be done, otherwise I can't sign this.

You don't need my signature to have it running online,
only if you want to merge this into official CMSSW.

**Comment by swang373** [comment]
@dmitrijus,
Thanks for letting me know, I'll notify you when an equivalent PR for 8_1_X has been created.

**Comment by swang373** [comment]
@nsmith- @mulhearn 
Is there a separate 81X DQM branch to which I should port these bugfixes, or so should I make a pull request to a cms-l1t-offline integration branch that will then be pull-requested here?

**Comment by dmitrijus** [comment]
Any news on 81x development/branch?

**Comment by mulhearn** [comment]
Sorry, we've been distracted by preparations for MC production.  We need to provide updated standard sequences that will provide what you need in RAW2DIGI stage and ValL1Emulator.  Then these ad-hoc sequences here can be cleaned up, then we can merge this in 81x, then we can put it in 80x online.  Meanwhile, we have to live with having these as PRs into DQM local area a bit longer I'm afraid, but I hope to end this within ~ 1 week.

**Comment by vanbesien** [comment]
Hey guys,

After the merging of #14570 in https://github.com/cms-sw/cmssw/releases/CMSSW_8_0_9, what is still needed from this PR?
It obviously doesn't merge anymore on 8_0_9 or 8_0_10.
Can you check?

**Comment by swang373** [comment]
Hi @vanbesien ,

Sorry for the late reply. @nhaubrich can confirm that the modifications in this pull request have been superseded by commits in the latest [L1T DQM development branch](https://github.com/cms-l1t-offline/cmssw/tree/l1t-dqm-CMSSW_8_0_9). This PR can be ignored.

**Comment by vanbesien** [comment]
Thanks, @swang373.
Can you confirm that this means that we can deploy 8_0_10 for online without any patches for L1T?
This is what we will do, unless you tell us otherwise.

**Comment by swang373** [comment]
Hi @vanbesien ,

Now that you mention it, a PR must be made at the very least such that the EMTF DQM module doesn't break. The transition from 8_0_8 to 8_0_9 brought a lot of changes to code outside of the DQM package that only our module relied on (unpacker, data formats, etc.). I'll work on that now.

Just a side note, the uGT PR's may or may not have been included in the cms-l1t-offline DQM development branch. I'll check that now.

**Pull request closed without merging**
