### PR TITLE
improved element-removal in HLTProcess (hltGetConfiguration)

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

~~This PR adds an extra check in the function that converts the outputs from ConfDB into a HLT configuration file, in order to ensure certain syntax errors are avoided. This converter is most commonly used when downloading a menu using `hltGetConfiguration`.~~

This PR adds an improvement in how `HLTProcess` removes certain elements from the `python` output obtained from ConfDB (functionality used for certain types of HLT configuration files). This comes into play, for example, when downloading a menu using `hltGetConfiguration`.

This update leads to no change for the menus that are currently in use (those are obviously converted without any syntax errors already) [*].

~~The additional syntax check~~ This update was needed when downloading from ConfDB a particular menu that made use of Tasks (`hltGetConfiguration` removes some modules a posteriori depending on the menu, and afterwards there was one comma too many inside one Task). Some details are in https://github.com/cms-sw/hlt-confdb/issues/32.

FYI: @Sam-Harper @fwyzard

[*] I took this chance to add a couple of comments to the output of `hltGetConfiguration` (independent of the syntax check added in this PR).

#### PR validation:

Private tests. Verified that `hltGetConfiguration` produces the same configuration for all menus in `/dev/CMSSW_12_2_0/`, and that the original issue with one Task-based menu is solved.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by Sam-Harper** [comment]
thanks Marino. The issue here is actually for a very specific case:

https://github.com/cms-sw/cmssw/blob/767bceb8a0265d6690288e6937481efa13698ea6/HLTrigger/Configuration/python/Tools/confdb.py#L656-L669

basically we remove process.hltDQMFileSaverPB and that is what causes the issues as we didnt consider the implication when it was the only module in the path and a sequence. We could just fix this specific case here  in the search/replaces

Not so bothered on the solution , just saying there is not necessarily a need for a global one as its an error in the above lines

**Comment by missirol** [comment]
Thanks, Sam. I agree; I just somehow found it easier to write a generic check at the end. If Martin has preferences, or sees issues, he will let us know.

**Comment by fwyzard** [comment]
@missirol, rather than fixing the syntax after the fact I would find it better to make the correct replacement to begin with :-)

In case it needs to be used in more than one place, you could wrap that n a function like
```python
def removeFromSequencesAndTasks(data, label):
    import re
    if label in data:              
        label_re = r'\b(process\.)?' + label
        data = re.sub(r'( \+|,) ' + label_re, '', data)
        data = re.sub(label_re + r'( \+|,) ', '', data)
        data = re.sub(label_re, '',  data)
        
    return data
```

**Comment by missirol** [comment]
Thanks, Andrea. I'll give this a try.

**Comment by missirol** [comment]
Thanks again, I tried to implement the suggested solution (I think this is also more in line with what Sam had in mind). I had to tweak it minimally to be a bit more flexible with whitespaces. Also, I added it as member of `HLTProcess`, so not as a standalone function, just b/c that seemed more consistent with the rest of the whole file.

I checked some examples with this [snippet](https://gist.github.com/missirol/87505cd7093a983cec5cbd39c8debba3).

Also re-tested that the standard tables (as produced from `hltGetConfiguration`) are unchanged, and the original use case is fixed.

**Comment by missirol** [comment]
I updated the PR title and description, according to the changes in the implementation.

**Comment by missirol** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
