### PR TITLE
revise GEN release validation samples

### PR DESCRIPTION
**Pull request by covarell**
Proposal to revise GEN validation samples:
- Added more used LHE-based workflows (also testing aMCatNLO and Powheg) and others, spanning a wider range of MC generators used in CMS 
- removed old/redundant workflows, fixed duplicated workflow numbers 
- reordered samples in the way they should be 
  (generator = RelVal to be run for every release validation cycle
  extendedgen = RelVal to be run only for major changes and on demand)

Proposal to be discussed @bendavid @franzoni @mkiani

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by covarell** [comment]
+1

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by franzoni** [comment]
@davidlange6 , would it be possible having this PR integrated in 76x ?

**Comment by covarell** [comment]
Workflows are reordered now to reduce IB time.
At the moment, workflows to be run in RelVal are:
- all included in relval_generator
- 513, 514, 521, 522, 523, 524, 551, 552, 554, 555, 556 from relval_extendedgen
@franzoni @fabozzi

**Comment by covarell** [comment]
+1

**Comment by srimanob** [comment]
please test

**Comment by covarell** [comment]
@srimanob @davidlange6 are there any remaining issues with this PR? We would need it asap.

**Comment by davidlange6** [comment]
@srimanob - any remaining commens on this PR?

**Comment by srimanob** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
