### PR TITLE
Tau customization for Phase2 (92X)

### PR DESCRIPTION
**Pull request by mbluj**
Tau customization for Phase2 studies: backport of #19788 to CMSSW_9_2_X release series. Please check original PR for details.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
assign upgrade

@kpedro88 please confirm that this is needed in 92X

**Comment by kpedro88** [comment]
-1
not needed in 92X

**Comment by mbluj** [comment]
-1
> not needed in 92X
>
I think it is reasonable to have it in 92X if backport to 91X acceptable
(#19790). It is not a deep modification anyway.

M.

**Comment by kpedro88** [comment]
@mbluj 92X is not being used for Phase2.

**Pull request closed without merging**
