### PR TITLE
Made modules global in RecoEcal/EgammaClusterProducers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed use of beginRun methods and the mutable state
- no more mutable state allowed change to global

This is part of the work where framework requires stream modules to explicitly state they want Run/LuminosityBlock transitions.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
