### PR TITLE
Adding UL16 PUID and fixing QGL values in nanoAOD

### PR DESCRIPTION
**Pull request by alefisico**
#### PR description:

- Introduce a fix to nan values of QGL in nanoAOD.
- Adds to nanoAOD the UL16 PUID values for APV and non APV.
- Also includes a fix in JMEnano to propage UL16 PUID
- This PR should be tested on top of #33857 
- This PR will be backport to CMSSW_10_6_X right after

#### PR validation:

- Run the usual `runTheMatrix` and `scram build code-format` without errors.

FYI @camclean @singh-ramanpreet

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test with #33857

**Comment by mariadalfonso** [comment]
test parameters:

pull_request = cms-data/RecoJets-JetProducers#13

**Comment by mariadalfonso** [comment]
please test with #33857

**Comment by singh-ramanpreet** [comment]
Probably both PR need to be mentioned together with comma separated.
> please test with #33857,https://github.com/cms-data/RecoJets-JetProducers/pull/13

**Comment by mariadalfonso** [comment]
please test with #33857,cms-data/RecoJets-JetProducers#13

**Comment by mariadalfonso** [comment]
please test with #33857

**Comment by gouskos** [comment]
please test

**Comment by mariadalfonso** [comment]
see error in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c88107/15540/unitTests/src/PhysicsTools/NanoAOD/test/runtestPhysicsToolsNanoAOD/testing.log

```
    from RecoJets.JetProducers.PileupJetID_cfi import pileupJetId, _chsalgos_94x, _chsalgos_102x, _chsalgos_106X_UL16, _chsalgos_106X_UL16APV, _chsalgos_106X_UL17, _chsalgos_106X_UL18
ImportError: cannot import name _chsalgos_106X_UL16
```

**Comment by singh-ramanpreet** [comment]
> see error in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c88107/15540/unitTests/src/PhysicsTools/NanoAOD/test/runtestPhysicsToolsNanoAOD/testing.log
> 
> ```
>     from RecoJets.JetProducers.PileupJetID_cfi import pileupJetId, _chsalgos_94x, _chsalgos_102x, _chsalgos_106X_UL16, _chsalgos_106X_UL16APV, _chsalgos_106X_UL17, _chsalgos_106X_UL18
> ImportError: cannot import name _chsalgos_106X_UL16
> ```

Hi @mariadalfonso 
The test used `CMSSW_12_0_X_2021-06-01-2300`, which does not have training merged.
I think it's in the next one `CMSSW_12_0_X_2021-06-02-1100` (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_0_X)

I don't know if the next build is available for testing.

**Comment by mariadalfonso** [comment]
test parameters:

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
> ## Comparison Summary
> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons
> 

> * Reco comparison results: 1261 differences found in the comparisons
1260 are from HI wf 140.53

Changes as spotted by the tests are:
 qgl fix (nan --> -1)
Screen Shot 2021-06-03 at 13 54 19

or jetID for UL16
Screen Shot 2021-06-03 at 13 47 24

**Comment by mariadalfonso** [comment]
+xpog

changes inline with the description

**Comment by qliphy** [comment]
+1

**Pull request merged**
