### PR TITLE
adding dqm for double lepton trigger

### PR DESCRIPTION
**Pull request by clint-richardson**
80X backport for PR13930 (https://github.com/cms-sw/cmssw/pull/13930)

### CODE REVIEW

**Comment by clint-richardson** [comment]
updated to reflect request from TSG about path naming convention

**Comment by clint-richardson** [comment]
hello, could you please retest these?

**Comment by perrotta** [comment]
please test

**Comment by clint-richardson** [comment]
updated to track 81X request changes

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Please align this with 81x version.
For example, this commit is missing: https://github.com/cms-sw/cmssw/pull/13930/commits/6b7c357c2345e6118177b18e31c2359919c153fa

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
