### PR TITLE
[12_3_X] Added protection from multiple creation of geometry

### LINKED ISSUE #38624: Segfault in dd4hep geometry when changing runs
There seems to be something fishy happening with the dd4hep geometry at run boundaries. Probably related to https://github.com/cms-sw/cmssw/issues/38586 as well. 

```
cmsrel CMSSW_12_3_6
cd CMSSW_12_3_6/src
cmsenv
cmsRun /eos/cms/store/group/alca_global/multiruns/results/dev02/slc7_amd64_gcc10/CMSSW_12_3_6/378852_0p_3f/alcaConfig.py 
```
leads to
```
Wed Jul  6 01:38:58 CEST 2022
Thread 2 (Thread 0x7f3a03744700 (LWP 23601) "cmsRun"):
#0  0x00007f3a27e441d9 in waitpid () from /lib64/libpthread.so.0
#1  0x00007f3a1fd56fd7 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00007f3a1fd57b4a in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00007f3a2843cf90 in std::execute_native_thread_routine (__p=0x7f3a165966e0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#4  0x00007f3a27e3cea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f3a27b65b0d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f3a25cb8540 (LWP 22356) "cmsRun"):
#0  0x00007f3a27b5addd in poll () from /lib64/libc.so.6
#1  0x00007f3a1fd5728f in full_read.constprop () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#2  0x00007f3a1fd57c1c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#3  0x00007f3a1fd5a56b in sig_dostack_then_abort () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f3a01f31b82 in dd4hep::typeName[abi:cxx11](std::type_info const&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/external/slc7_amd64_gcc10/lib/libDDCore.so.1.19
#6  0x00007f3a01f124ff in dd4hep::ObjectExtensions::addExtension(unsigned long long, dd4hep::ExtensionEntry*) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/external/slc7_amd64_gcc10/
lib/libDDCore.so.1.19
#7  0x00007f3a0249c143 in cms::DDDetector::DDDetector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std:
:allocator<char> > const&, bool) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/libDetectorDescriptionDDCMS.so
#8  0x00007f39ffc5c247 in magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB::produce(IdealMagneticFieldRecord const&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/s
lc7_amd64_gcc10/pluginDD4hep_MagneticFieldGeomBuilderPlugins.so
#9  0x00007f39ffc682b1 in edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::default_delete<MagneticField> >, IdealMagneticField
Record, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordI
mpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}::operator()() const () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/li
b/slc7_amd64_gcc10/pluginDD4hep_MagneticFieldGeomBuilderPlugins.so
#10 0x00007f39ffc697e6 in decltype ({parm#1}()) edm::convertException::wrap<edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::d
efault_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::except
ion_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}>(edm::eventsetup::Callback<magneticfiel
d::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::default_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFi
eldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&
)::{lambda()#1}::operator()() const::{lambda()#1}) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginDD4hep_MagneticFieldGeomBuilderPlugins.so
#11 0x00007f39ffc69904 in edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::default_delete<MagneticField> >, IdealMagneticField
Record, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordI
mpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginDD4hep_Ma
gneticFieldGeomBuilderPlugins.so
#12 0x00007f39ffc6b48f in void edm::SerialTaskQueueChain::actionToRun<edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::default
_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_pt
r const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&>(edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESPro
ducerFromDB, std::unique_ptr<MagneticField, std::default_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::det
ail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&) () from /cvmfs/cms.ce
rn.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginDD4hep_MagneticFieldGeomBuilderPlugins.so
#13 0x00007f39ffc6b501 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::eventsetup::Callback<magneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<Magnet
icField, std::default_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<IdealMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__except
ion_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}>(tbb::detail::d1::task_group&, edm::eventsetup::Callback<m
agneticfield::DD4hep_VolumeBasedMagneticFieldESProducerFromDB, std::unique_ptr<MagneticField, std::default_delete<MagneticField> >, IdealMagneticFieldRecord, edm::eventsetup::CallbackSimpleDecorator<Idea
lMagneticFieldRecord> >::runProducerAsync(tbb::detail::d1::task_group*, std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceT
oken const&)::{lambda()#1}&&)::{lambda()#1}>::execute() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/pluginDD4hep_MagneticFieldGeomBuilderPlugins.so
#14 0x00007f3a2a713075 in tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms.cern.ch/
slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/libFWCoreConcurrency.so
#15 0x00007f3a28c67b8c in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x7f3a2474ac00, this=0x7f3a2473fe00) at /data/cmsbld/jenkins/workspa
ce/auto-builds/CMSSW_12_3_1-slc7_amd64_gcc10/build/CMSSW_12_3_1-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.4.0-d3ee2fc4dbf589032bbf635c7b35f820/tbb-v2021.4.0/src/tbb/task_dispatcher.h:322
#16 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x7f3a2473fe00) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_3_1-
slc7_amd64_gcc10/build/CMSSW_12_3_1-build/BUILD/slc7_amd64_gcc10/external/tbb/v2021.4.0-d3ee2fc4dbf589032bbf635c7b35f820/tbb-v2021.4.0/src/tbb/task_dispatcher.h:463
#17 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_3_1-slc7_amd64_gcc10/build/CMSSW_12_3_1-build/BU
ILD/slc7_amd64_gcc10/external/tbb/v2021.4.0-d3ee2fc4dbf589032bbf635c7b35f820/tbb-v2021.4.0/src/tbb/task_dispatcher.cpp:168
#18 0x00007f3a2a49299c in edm::EventProcessor::beginRun(edm::Hash<2> const&, unsigned int, bool&, bool&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/libFWCoreF
ramework.so
#19 0x00007f3a2a493815 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_6/lib/slc7_amd64_gcc10/libFWCoreFramework.so
#20 0x000000000040a266 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const ()
#21 0x00007f3a28c5615b in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_3_1-slc7_amd64_gcc10/build/CMSSW_12_3_1-build/BUILD/slc7_amd64_g
cc10/external/tbb/v2021.4.0-d3ee2fc4dbf589032bbf635c7b35f820/tbb-v2021.4.0/src/tbb/arena.cpp:698
#22 0x000000000040b094 in main::{lambda()#1}::operator()() const ()
#23 0x000000000040971c in main ()
```

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
backport of #38640 in order to fix #38624

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: 
no

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
@civanch please don't forget the 12_4_x backport (I am a bit more dubtfull about the need of this 12_3_X one...)

**Comment by mmusich** [comment]
-1
   * tested with the config provided at https://github.com/cms-sw/cmssw/issues/38624 and it does NOT fix.

**Comment by civanch** [comment]
@mmusich , the problem is in the same place or in a different one?

**Comment by mmusich** [comment]
> the problem is in the same place or in a different one?

the stack trace is exactly the same as before.
Tested with:
```
cmsrel CMSSW_12_5_X_2022-07-07-1100
cd CMSSW_12_5_X_2022-07-07-1100/src/
cmsenv
git cms-merge-topic 38641
scram b -j 20
eos cp /eos/cms/store/group/alca_global/multiruns/results/dev02/slc7_amd64_gcc10/CMSSW_12_3_6/378852_0p_3f/alcaConfig.py .
cmsRun alcaConfig.py
```

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by mmusich** [comment]
@civanch 
   * please change the title to something more meaningful;
   * please incorpotate the last commit from https://github.com/cms-sw/cmssw/pull/38640
   * Also please put in the title that it's for [12.3.X] otherwise it will be confusing.

**Comment by civanch** [comment]
please test

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38640

**Comment by mmusich** [comment]
+1
   * with the understanding that the caveats at https://github.com/cms-sw/cmssw/pull/38653#issuecomment-1179001530 should be dealt with in a later PR

**Comment by qliphy** [comment]
+1
further improvement tracked with a github issue https://github.com/cms-sw/cmssw/issues/38669

**Pull request merged**
