### PR TITLE
add HINorminal2015 BS to 71

### PR DESCRIPTION
**Pull request by srimanob**
Add HINorminal2015 BS to 71 (Sorry for confusion in branch name).

### CODE REVIEW

**Comment by srimanob** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@davidlange6 
I just see that the new 7_1_20 is out without this one. Could you please consider this for the patch one? We need HINorminal BS for the production.

**Comment by davidlange6** [comment]
@srimanob - yes - sorry I missed it before

**Pull request merged**
