### PR TITLE
Fixing Memory Coruption for large histograms in DQMFileSaverPB : 12_3_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

PR description:
This is the backport of https://github.com/cms-sw/cmssw/pull/38112

DQMFileSaverPB allocates its buffer to compress the histogram on the stack. This means it is limited to a size of 10MB. There are histograms which are bigger than this (specifically HLT paths vs bx) and thus can exceed this limit and crash the client. We encountered this when running the full menu of 800+ paths.

#### PR validation:
DQM team report successful playback

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/38112

needed for P5 DQM release series (aka 12_3, 12_4)

### CODE REVIEW

**Comment by Sam-Harper** [comment]
please test

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38112

**Comment by missirol** [comment]
Timeout errors are clearly not related to this PR. I leave it @cms-sw/dqm-l2 , or ORP, to restart the tests if they prefer.

This PR is relevant for current P5 operations (see notes of recent Joint-Ops meetings).

**Comment by qliphy** [comment]
please test

**Pull request merged**
