### PR TITLE
add condition formats corresponding to L1T global UTM library

### PR DESCRIPTION
**Pull request by mulhearn**
Provides the Cond Formats needed by L1T Global for use with the new UTM library.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Update underway for CondCore and CondFormats/DataRecord, but these will be totally vanilla.

**Comment by mulhearn** [comment]
I just noticed, I think we had best define the std::vector/maps as type blob....  one last update coming with that.

**Comment by mulhearn** [comment]
OK that should do it...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Update:  in my local compilation testSerialization passed.

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Pull request merged**
