### PR TITLE
SiPixelQuality harvester fix for segmenation fault for CMSSW_10_1_X

### PR DESCRIPTION
**Pull request by tocheng**
Backport of PR #23150

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

the fix has been tested to correct the crash discussed in the thread https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1873/1/1/1/1/1/1/1/1/1/1/1.html

**Pull request merged**
