### PR TITLE
Phase2-hgx144 Add a new geometry version of HGCal from Shuichi Kunori

### PR DESCRIPTION
**Pull request by bsunanda**
This is a follow up of a design shown by Chris Seez in the DPG meeting. It provides some inner support structure

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@franzoni, @kpedro88 Can you sign this - I am not sure who signs for operation

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
