### PR TITLE
Added consumes calls to MTDTransientTrackingRecHitBuilderESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This includes using edm::ESGetToken.

#### PR validation:

The runTheMatrix.py workflows that use the module still run.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar When I said #28223 depends on this pull request when I did the 'please test' I did NOT mean that this pull request needed #28223. How does one specify a single direction dependency across PR rather than a bi-directional?

**Comment by Dr15Jones** [comment]
This does NOT depend on #28223 so the `requires-external` label is incorrect.

**Comment by kpedro88** [comment]
+upgrade

**Comment by Dr15Jones** [comment]
The test failures are from #28223  not this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
