### PR TITLE
update offline DQM muon threshold for ppRef_2017 era

### PR DESCRIPTION
**Pull request by BetterWang**
update offline DQM muon threshold for ppRef_2017 era
This is the back port of #21208

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test
there were issues with eos earlier

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@BetterWang is this PR still needed in 94X or can just be closed?

**Comment by BetterWang** [comment]
No longer needed. Should be closed.

**Pull request closed without merging**
