### PR TITLE
MTD Validation: add histograms for detailed material budget vs eta study

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR adds a few histograms to the MTD specific class of ```Validation/Geometry``` for specialized checks in BTL and ETL separately, beyond the basic material budget plots vs eta and phi.  

#### PR validation:

The desired histograms are correctly produced, in particular I attach the output for 20234:

[MB_along_z_neutrinos_2D.pdf](https://github.com/cms-sw/cmssw/files/12300396/MB_along_z_neutrinos_2D.pdf)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
the differences in the test seem unrelated to this PR, which is not affecting production workflows.

**Comment by civanch** [comment]
+1

what is strange (but unrelated to this PR): regression failures are spread over  many WFs

**Comment by makortel** [comment]
> what is strange (but unrelated to this PR): regression failures are spread over many WFs

It would be great if these seemingly random comparison differences would be reported in issues. These differences look similar to https://github.com/cms-sw/cmssw/issues/42525, and I see
* the baseline tests were run on `Intel(R) Xeon(R) CPU E5-2683 v4`
* the PR tests were run on `Intel(R) Xeon(R) Silver 4216 CPU`

**Comment by emanueleusai** [comment]
+1

- spurious dqm differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
