### PR TITLE
Various packages: clean up clang warning unknown warning group

### PR DESCRIPTION
**Pull request by gartung**
warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
 #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                               ^

warning: unknown warning group '-Wunused-but-set-variable', ignored [-Wunknown-warning-option]
 #pragma GCC diagnostic ignored "-Wunused-but-set-variable"
                               ^

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by fwyzard** [comment]
Why do we meed to protect
```
#pragma GCC ...
```
lines from CLANG ?

Aren't pragmas supposed to be compiler-specific anyway ?

**Comment by gartung** [comment]
Apparently clang tries to interpret them.

**Comment by fwyzard** [comment]
Is the problem with the `#pragma` itself, or with the warning option ?
From the changes it looks like other `#pragma GCC ...` lines are fine ?

**Comment by gartung** [comment]
-Wmaybe-uninitialized and -Wunused-but-set-variable are unknown to clang. The other it understands.

**Comment by fwyzard** [comment]
Ah, I see.
Why not add `-Wno-unknown-warning-option` to the clang command line instead ?

**Comment by fwyzard** [comment]
By the way, the reason for my comment is to keep all related (warning) options in a single place, i.e. the Makefile / SCRAM BuildFile / SCRAM rules.
Since here the options are in the code itself, maybe we could add
```
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
```
there ?

E.g. instead of changing
```diff
+#ifndef __clang__
 #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
-
+#endif
```
do
```diff
+#pragma GCC diagnostic ignored "-Wunknown-warning-option"
 #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
```

**Comment by smuzaffar** [comment]
@fwyzard , I liked you first option i.e. add `-Wno-unknown-warning-option` to clang. Do you see any disadvantage with this approch as compare to the `#pragma GCC diagnostic ignored "-Wunknown-warning-option"`

**Comment by fwyzard** [comment]
Mhm, no,  not really.

**Comment by smuzaffar** [comment]
hold
cmssdt PR cms-sw/cmsdist#3836 should avoid these warnings

**Comment by smuzaffar** [comment]
cms-sw/cmsdist#3836 has taken care of these clang warning ( https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc630/www/sat/10.1.CLANG-sat-11/CMSSW_10_1_CLANG_X_2018-03-10-1100 ). So closing this PR

**Pull request closed without merging**
