### PR TITLE
Add energy correlation functions to jet tools 75

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #11028

The energy correlations functions are currently the default algorithm for W-tagging in ATLAS.
They are not run in RECO/AOD/MiniAOD, but added them to CMSSW for cross check analyses.
They can be tested with:
RecoJets/JetProducers/test/testJetTools_cfg.py

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try again in case errors are transient

**Comment by cvuosalo** [comment]
+1

For #11074 140d35cecea5dff811a444b89cd327ca590129d9

Adding energy correlation functions to jet tools. This new tool doesn't run in standard workflows, so there should be no changes in run-time behavior. #11028 is the 76X version of this PR, and it has already been merged.

The new code is satisfactory. Jenkins tests against baseline CMSSW_7_5_X_2015-09-02-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
