### PR TITLE
AlCaReco matrix update 

### PR DESCRIPTION
**Pull request by tocheng**
Backport of PR https://github.com/cms-sw/cmssw/pull/20294 to CMSSW_9_2_X
to update 2017 AlCaReco matrix in the release

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
