### PR TITLE
Add reduced lepton time-life info to NanoAOD (14_0_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds base lepton time-life info to common (Phys) NanoAOD tables while lepton track parameters can be added through customization.
This is backport of #44637 to 14_0_X; further details in the original PR.

#### PR validation:

Tested with the standard nanoAOD workflow.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44637 for 2024 nanoAOD.

### CODE REVIEW

**Comment by hqucms** [comment]
type tau

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by mbluj** [comment]
> Please fix conflicts.

I was busy until now, but I am on it and I hope rebase, test and push in 30' from now.

**Comment by mbluj** [comment]
Rebased to solve conflicts, basic tests with nano wf successful - ready for re-testing and eventually merging.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 Could you please check and sign? Thanks!

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by hqucms** [comment]
@cms-sw/orp-l2 Could you please merge this? Thanks!

**Comment by rappoccio** [comment]
+1

**Pull request merged**
