### PR TITLE
Add a customisation to run the "GRun" HLT menu on Run 2 data/MC

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a customisation to run the "GRun" HLT menu on Run 2 data/MC.

`customiseFor2018Input` takes care of two things:
  - reverts the HCAL configuration that the one in 2018
  - reverts the Pixel calibrations to the scheme used in the Run 2 conditions

#### PR validation:

None yet.

### CODE REVIEW

**Comment by fwyzard** [comment]
This PR is incomplete: it adds the required customisation, but not a way to call it.

Some ideas
  - add an extra "2018" menu, identical to the "GRun" menu, but including the extra customisation
  - add an extra "2018" menu, that is just a thin wrapper that imports the "GRun" menu and aplies the extra customisation:
    ```pytyon
    from HLT_GRun_cff import fragmet
    from customizeHLTforCMSSW import *
    fragment = customiseFor2018Input(fragment)
    ```
  - apply the customisation to the HLT menus based on the process Era:
    ```python
    (~run3_common).toModify(fragment, customiseFor2018Input)
    ```
    However, to work for the self-contained HLT menus, one would need to start using eras correctly there - and we would still need two dumps, one for 2018 and one for Run3.

**Comment by fwyzard** [comment]
@Martin-Grunewald what do you think ?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
please test
I trivially solved the conflict with #31671
please double check

**Comment by Martin-Grunewald** [comment]
@silviodonato Thanks!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1
The differences are related to https://github.com/cms-sw/cmssw/pull/31674

**Pull request merged**
