### PR TITLE
Create XibStar.dec

### PR DESCRIPTION
**Pull request by heppye**
And BPH decay file

### CODE REVIEW

**Comment by bendavid** [comment]
+1
@davidlange6 can this still go directly in cmssw or do you prefer to start putting new files in cms-data also for this area?

**Comment by davidlange6** [comment]
@bendavid - the file is 40 lines. i don't have a big problem with it.

**Comment by covarell** [comment]
-1
Fragment is wrong
Aliases are defined for the ancestor particle and never used. There should be an alias for each particle in the chain and the Decay block should be defined for those aliases

**Comment by heppye** [comment]
Hi Roberto, so the file in https://github.com/heppye/cmssw/blob/CMSSW_5_3_X/GeneratorInterface/ExternalDecays/data/Xib.dec should be ok. However, when test closer, I find the decay chain cann't be put into evtgen no matter what I have tried. It seems like because of  the defination of Xibstar0 (+-5324) and Xib (5132) in the particle table of evtgen 'evt.pdl' are not the same as  the decay table of pythia6. Could you or anyone confirm this? should I update the evt.pdl for this decay mode? I would be very appreciated if you or anyone else could comment on this. The decay file could be found at : https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/BPH-Summer12-00185/0

**Comment by inugent** [comment]
Hello,
  I am testing it.
Ian

**Comment by heppye** [comment]
Hi Ian, thank you very much for taking time to look into it. Another decay mode which is not related to this request but also may be affected by the same problem is https://github.com/heppye/cmssw/blob/CMSSW_5_3_X/GeneratorInterface/ExternalDecays/data/Xib_JpsiXi_mumu.dec. Looking forward for your testing results.

**Comment by inugent** [comment]
Hello,
  The first thing I notice is that the:
Alias MyXi_b0 Xi_b*0
Alias Myanti-Xi_b0 anti-Xi_b*0
ChargeConj MyXi_b0 Myanti-Xi_b0
you are renaming a Xi_b*0 as MyXi_b0.  This is confusing for the reader and should be fixed.
For Xi_b*0 the mass is 5.97, while for Xi_b+/- it is 5.84. Therefore if one decays Xi_b*0->Xi_b+/- pi+/- you violate energy conservation (m_{pi+/-}=0.139). This is why you get a crash. Best regards,
Ian
crash message:
EvtGen:Too many iterations to determine the mass tree. Parent mass= 5.97 0
EvtGen:This is the current decay chain
This top particle is MyXi_b0
MyXi_b0 -> MyXi_b- pi+ 
EvtGen:End of decay chain.
EvtGen:will take next combo with non-zero likelihood
EvtGen:Sorry, no luck finding a valid set of masses. This may be a pathological combo
cmsRun: EvtParticle.cpp:486: void EvtParticle::generateMassTree(): Assertion `0' failed.
zsh: abort      cmsDriver.py Configuration/Generator/python/MyTest.py --conditions  -s   GEN

**Comment by inugent** [comment]
PS if you want to fix this, you need to have a evt.pdl with the correct masses such that energy and momentum for this decay and all decay leading to this particle (ie check that the production mechanisms are valid after the mass change). This assumes that the physics process can occur and that the masses in the evt.pdl are wrong and need to be updated.

**Comment by heppye** [comment]
ok, thanks for the quick response and the suggestion. However, in pythia6, -5324 is 'Xi*_bbbar', and in evt.pdl -5324  is 'anti-Xi_b*0'  . If you set 'pythiaPylistVerbosity = cms.untracked.int32(1), ' in your test python script and you will see that the Xi*_bbar events does not actually decay in the mode defined in the decay chain.

**Comment by heppye** [comment]
p.s. I change the mass as your suggested and it is crash but still not seem to be right.

**Pull request closed without merging**
