### PR TITLE
CTPPS: bug fix in run ranges for FEDs channels mapping

### PR DESCRIPTION
**Pull request by forthommel**
Forward-port of #18461 onto the `master` branch

This PR modifies the run ranges parser to account for scenarios where the first event number in a run is 0 instead of 1, thus preventing any channels mapping to be defined for this event.
It hence allows runs at the edge of these ranges to properly retrieve a channels mapping for both the strips and diamond detectors.

Contrarily to #18461 it does not introduce the bug fix raised in #18283 (comment) by @perrotta preventing the CRC check to be performed on the VFAT frame is the unpacker verbosity is set to 0, as this latter is already covered in #18283.

`runTheMatrix -l limited` on d8fa8df4642819eeedd862a7f3830d29913b77e6 yielded `16 16 15 13 7 1 1 1 tests passed, 1 0 0 0 0 0 0 0 failed` (again, `DAS_ERROR` on `4.22`)

### CODE REVIEW

**Comment by forthommel** [comment]
type bugfix

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
Tested on the same input file where the crash was experienced:
/store/data/Run2016H/ZeroBias/RAW/v1/000/283/820/00000/462D2A5B-B19A-E611-B100-02163E01382E.root
this PR actually fixes it.

**Comment by arunhep** [comment]
+1

**Pull request merged**
