### PR TITLE
fix of Hit TkMap filling

### PR DESCRIPTION
**Pull request by fioriNTU**
Valid, Invalid and Inactive hits were normalized to the number of Tracks, while we want the integrated number on the Map

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by Dr15Jones** [comment]
This appears to need a rebase

**Comment by fioriNTU** [comment]
@Dr15Jones yes sorry I did a mistake
will close and open a new one

**Pull request closed without merging**
