### PR TITLE
Avoid uninitialized data warnings in PtAssignmentEngine2017

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Rearranged code to keep temporary variables in the local scope to guarantee no uninitialized variable warnings from ASAN builds.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
NOTE: as far as I could tell, the ASAN build warnings about possible use of uninitialized variables were false positives. However, this change does avoid future maintenance problems causing such issues.

**Comment by Dr15Jones** [comment]
code-checks

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
Any objections? @rekovic

**Comment by silviodonato** [comment]
Kind reminder @rekovic (CMSSW_11_1_0_pre7 is scheduled for tomorrow)

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
