### PR TITLE
Pileup summary info slimmer for MiniAOD (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10592

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Trying again... Seems unrelated.

**Comment by lgray** [comment]
please test

**Comment by lgray** [comment]
@slava77 any idea here? IB is broken?

**Comment by slava77** [comment]
yes, that IB was broken

**Comment by lgray** [comment]
IB is fixed now it seems.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 Just to put you in the loop here.

@monttj It would be very good to have this in for the MiniAOD reprocessing.

**Comment by monttj** [comment]
+1
There would be no issue with this PR from AT side.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@monttj @vadler can you please re-sign once the tests finish? Thanks.

**Comment by lgray** [comment]
@slava77 I added the backport of #10748 to this ongoing PR for 74X.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
@cmsbuild please test

refreshing the jenkins tests.

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
