### PR TITLE
Heppy 8 0 24 patch1

### PR DESCRIPTION
**Pull request by cbernet**
Hello, 

Here is the most recent version of the heppy analysis framework. 

Another pull request will follow shortly for 81X. 

More changes are expected in the following weeks from the CERN group (@gpetruc) and the VHbb group (@arizzi) but we should first merge this one.

Indeed, even though the number of commits is small, heppy has been synced manually -- a painful process -- with the most recent developments from the FCC collaboration, and this pull request is actually very important. Among other things, one can now find in PhysicsTools/HeppyCore: 

- a test suite with fairly good coverage (~100 unit tests). 
- reference documentation: http://fcc-support-heppy.web.cern.ch/fcc-support-heppy/moduleIndex.html (still working on it)
- papas : a generic particle flow simulation similar to Delphes
- the particles package, which contains a set of particle-like classes that can be used transparently in different experiments
- hooks to read the LCIO event data model (ILC, CLIC)

Best, 

Colin.

### CODE REVIEW

**Comment by cbernet** [comment]
could we proceed through the merging procedure asap? the rest of CMSSW is not affected, no reason to keep this pending. You could as well press merge, with no side effect whatsoever.

Thank you, 

Colin

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
Hi Colin,

Would it be possible to split the PR so that people can see the diff for all files easily?
Currently we have to click on the "diff" for each file at the end due to too many files.
Same for future 81X. 

Thank you,

Regards,
Taejeong

**Comment by cbernet** [comment]
Hi Tae Jeong, 

This is not possible, sorry. 

What would you do with these diffs anyway?  Do you actually want to check them all? 
I did that already for the many PRs I got from FCC and CMS contributors, so you can consider this PR reviewed. 

Please let me know today if you don’t want it this PR. 
I can manage heppy completely on my github account if these PRs are too much overhead for you guys. 

Cheers, 

Colin

**Comment by monttj** [comment]
+1

**Comment by cbernet** [comment]
Thank you for signing Tae Jeong.

I would like to give some more information as I realize my previous post was a little bit terse. As mentioned above, a large fraction of heppy developments is done outside CMSSW, in the context of the FCC. At the beginning, Giovanni, Andrea, and myself decided that the easiest would be that I sync manually the standalone version of heppy (https://github.com/cbernet/heppy) with the one in CMSSW (PhysicsTools/HeppyCore). We also considered managing heppy in an external github repo for CMS, and also to use it as an external tool, but we concluded that these solutions were not adequate.  

This manual sync requires many diffs and topical fixes to make sure that both the standalone and the CMS versions of heppy work. 

After syncing a given package in heppy, I make a sync commit such as https://github.com/cms-sw/cmssw/pull/16758/commits/103c1a287ff3122c0682977dd3016c762cbd5b87. As a result, each of these commits contain changes that actually occured in different pull requests on the other side. As you can imagine, it's not really possible to split them, hence my previous answer.

I will try and make smaller PRs in the future, but this is not easy. First, it is very time consuming for me to do this sync, and I'd prefer not to do it too often. My time on heppy would be better used on documentation or actual development. Second, I'm getting PRs from other people (e.g. Giovanni and Andrea who also manage and collapse many PRs with their communities, but also FCC people). Some of them are very big, and I can't really split them. See e.g. this one: https://github.com/cbernet/heppy/pull/29

Anyway, I don't think this is that much of an issue. I'm acting as administrator of heppy in both CMS and the FCC, and I know exactly what is going on in this package. I verify closely all changes, and I make sure that the code is working, in particular with a large (and growing) test suite. 

I think you could simply delegate the review of PhysicsTools/HeppyCore to me for future pull requests. For PhysicsTools/Heppy/, @arizzi, @gpetruc , and myself make sure that everything's ok. 

Cheers, and sorry for the rather long mail!

**Comment by cbernet** [comment]
Dear all, I see that this PR requires discussion at the ORP meeting.  

Is there any particular point to be discussed in addition to what has already been said on this thread? Anything I can do? 

Thanks, 

Colin

**Comment by cbernet** [comment]
Hello, could you please let me know what has to be done before we can merge this PR?

**Comment by davidlange6** [comment]
Hi @cbernet all - thanks to @arizzi  for pointing me to this - so, PRs for CMSSW go first to the development release (which is the default when you make a pull request). Lacking that, I've missed this PR which indeed has been stuck a while. The release for development is 90x. (from there, things can be back ported to where they are needed in a stable way). Let me see if I can manage to make a PR.

Regarding comments above, some code review is in any case needed - as by going into CMSSW we end up with the code even after its developer decides to move on to other tasks. I don't see that being an issue here but rather a general statement.

From a quick look - the big root file needs to be (re)moved. What is its function?

**Comment by cbernet** [comment]
> Le 19 déc. 2016 à 18:38, David Lange <notifications@github.com> a écrit :
> 
> Hi @cbernet <https://github.com/cbernet> all - thanks to @arizzi <https://github.com/arizzi> for pointing me to this - so, PRs for CMSSW go first to the development release (which is the default when you make a pull request). Lacking that, I've missed this PR which indeed has been stuck a while. The release for development is 90x. (from there, things can be back ported to where they are needed in a stable way). Let me see if I can manage to make a PR.
> 
> Regarding comments above, some code review is in any case needed - as by going into CMSSW we end up with the code even after its developer decides to move on to other tasks. I don't see that being an issue here but rather a general statement.
> 
> From a quick look - the big root file needs to be (re)moved. What is its function?
> 
> 

Hi David, 
This root file is for testing. 

C

**Comment by davidlange6** [comment]
ok, we'll have to distribute it (and its friends) in a different way- @iahmad-khan -could you make a new data directory for all the root files in these packages. Thanks.

**Comment by cbernet** [comment]
Actually, I could remove this root file. Sorry I just realized that these root files are used for testing heppy in another environment (the FCC, not CMS). 
They should be of no use in CMS but I need to check that. 

I am on vacation and will come back to this subject in January.
If you think it’s better to close this PR, please feel free to do so. 

I wish you all a very nice end of year break!

C

**Comment by davidlange6** [comment]
Thanks - i'll start a PR in 90x and see if we converge on that before the holidays - then pick this one up.

**Pull request closed without merging**
