### PR TITLE
[ROOT6] Add missing init in default constructor

### PR DESCRIPTION
**Pull request by pcanal**
This were discovered running valgrind.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
So there is evidence that default constructed objects were used before "properly" initialized, isn't it?
Do we know where?

Are we sure that the initialization values used in this PR are the correct one?
Are we sure that those uninitialized objects should be really used?

**Comment by slava77** [comment]
> So there is evidence that default constructed objects were used before "properly" initialized, isn't it?

this is persisted data. Technically all data members can be read.

**Comment by VinInn** [comment]
> On 21 Feb, 2022, at 4:39 PM, Slava Krutelyov ***@***.***> wrote:
> 
> So there is evidence that default constructed objects were used before "properly" initialized, isn't it?
> 
> this is persisted data. Technically all data members can be read.
> 
> 
ok, so some of them are meaningless for some use-cases or what?
Again, when not set what tells the "user" that they shall not be used/trusted?

and I do not understand, crap-out/crap-in: but root will set to something in reading. so what kind of valgrind error are we getting?

v.

**Comment by slava77** [comment]
for operational purposes, to retain repeatable outputs, I think that the persisted data should be initialized.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/37032 is for master branch

**Comment by perrotta** [comment]
> #37032 is for master branch

Thank you @smuzaffar !

**Comment by smuzaffar** [comment]
closing it in favour of https://github.com/cms-sw/cmssw/pull/37032

**Pull request closed without merging**
