### PR TITLE
Update reference manual scripts

### PR DESCRIPTION
**Pull request by altundag**
- Update doxygen config file
  - Set MACRO_EXPANSION flag (before, doxygen was not able to keep track of defined final specifier)
  - Enable UML class diagrams
- Rewrite main page generator script
  - Update tag collector source
- Rewrite classes page parser script

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by altundag** [comment]
Why we need this pr?
   * Generating UML diagrams
      * As requested by a user, with this pr, users will be able to get UML diagrams
   * MACRO_EXPANSION flag
      * Please see the following thread to get more information: https://hypernews.cern.ch/HyperNews/CMS/get/workbook/257.html
   * The source of the contact persons has been updated
      * I have updated the contact person source (it was cms tag collector before)
      * Contact info in the tree view (main pages of RefMans, e.g. https://cmssdt.cern.ch/SDT/doxygen/CMSSW_7_5_1/doc/html/index.html) is coming from the new source: https://github.com/cmsdoxy/cmsdoxy/blob/master/CMSSWTagCollector/cmssw.py

Also, I will create the same pr for 7_6_X and 7_5_X. Thanks.

**Comment by davidlt** [comment]
Your `Data['PERSON_MAP']` seems to be outdated.

https://github.com/cms-sw/cms-bot/blob/master/categories.py

`CMSSW_L2` contains up to date list.

**Comment by altundag** [comment]
Hello,

Yes, actually, I was looking for help for the list. Do we have a better source for that list? Are you maintaining the list somewhere?

Thanks

**Comment by altundag** [comment]
Ops, sorry I mixed up the links. the problem in the source you gave was the real names. I didn't want to get the github names but real names. Do you have any idea how can I match those github names with real ones?

Thanks

**Comment by davidlt** [comment]
You could make yourself a mapping between GItHub user names and real names, or, this could be maintained in the same file at cms-bot repository.

@davidlange6 @smuzaffar ideas?

**Comment by smuzaffar** [comment]
one can get the detail of a github user via
curl -k -i https://api.github.com/users/smuzaffar 

if needed we can have a jenkins job running every day to dump Data['PERSON_MAP'] in cms-bot/contants.py

**Comment by cmsdoxy** [comment]
Hello,

Thanks a lot for the suggestions! BTW, since the source is out of the cmssw repository, I can handle this change without changing something in the cmssw/Documentation. So, this pr is still valid.

Thanks again

**Comment by cmsdoxy** [comment]
--for now, I will try to use github api and if I see a problem (for example, some people might have given fake names), I will ask your help again.

**Comment by davidlange6** [comment]
Just to clarify, we don’t require real names in github profiles to make pull requests against the CMSSW repo.

**Comment by degano** [comment]
@cmsbuild please test
The error above seems to be das-related.

**Comment by davidlt** [comment]
There is no need for Jenkins testing here (there is nothing to test here by Jenkins).

**Comment by altundag** [comment]
Hello @davidlange6,

I can maintain the name list by hand for now(?) Where can I find the current list then?

Thanks

**Comment by davidlt** [comment]
It's here: https://github.com/cms-sw/cms-bot/blob/master/categories.py I guess, you don't know the actual names behind the accounts.

The main question would be, do we want to maintain real names also in `categories.py`, or documentation guys maintain their own mappings internally.

**Comment by davidlange6** [comment]
that is a list of L2s not a list of contributors. the github api that Shahzad suggested already is the best source of information. But there is no requirement for any information beyond github account name.

**Comment by altundag** [comment]
Yes, I know the python file you stated (actually, I am executing it in the source[1] to get variables defined in it), but as you said, the problem is real names behind the accounts. 

I am up for both, we can maintain the names in the cms-bot repo or I can maintain them in the source*. But I guess it is better to maintain them in the cms-bot repo since it is well known for the CMSSW people (if we compare it with the source repo[2]).

1. https://github.com/cmsdoxy/cmsdoxy/blob/master/CMSSWTagCollector/cmssw.py#L10-L11
2. https://github.com/cmsdoxy/cmsdoxy/blob/master/CMSSWTagCollector/

**Comment by davidlt** [comment]
Thus, additional question. Who should be listed in CMSSW documentation? I thought, it always was L2s. The top people responsible for the category/domain.

I guess, CMSSW documentation was always open for public (not hidden behind SSO), so the names were always visible to everyone. Thus keeping real names of L2s in `categories.py` doesn't sound like an issue.

You can quickly figure out real names by looking into commits, in particularly author field (real name + CERN email).

**Comment by altundag** [comment]
Ok, then, I will fork the cms-bot repo and insert the real names* into **categories.py** and create a pr for that.

This is ok for the cms-bot project right?

*: I will not change something in the file (not break the current structure) but just define dictionary type map variable which contains real-github name map.

**Pull request closed without merging**
