### PR TITLE
Clean up aging.py and set up HB TDR aging

### PR DESCRIPTION
**Pull request by kpedro88**
Followup to #18118 to set up the aging customise functions for the barrel TDR. I removed a bunch of very old stuff from aging.py, and added a set of functions and corresponding HCAL conditions for the agreed-upon aging scenarios:
>i) 300 fb-1, 1000fb-1 and 3000fb-1 with an instantaneous luminosity of 5E34, the nominal scenario
>ii) 3000fb-1 and 4500fb-1 with an instantaneous luminosity of 7.5E34, the ultimate scenario

Currently the HCAL conditions ignore the lumi ramp-up period after LS3/4 and just use the final instantaneous lumi (for simplicity).

For future reference, here are the two HL-LHC schedules:
HL-LHC schedules

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
more eos/xrootd problems, awesome

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
