### PR TITLE
DQMServices/Core: proposed change to DQMEDHarvester

### PR DESCRIPTION
**Pull request by gartung**
This changes DQMEDHarvester to a modified edm::one::producer. The config files need changing from EDAnalyzer to EDProducer in cases where a class inherits from DQMEDHarvester. I believe I have made all of the changes needed but this needs further testting

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by gartung** [comment]
@Dr15Jones can you stop and restart the testing please.

**Comment by Dr15Jones** [comment]
please test

**Comment by gartung** [comment]
@Dr15Jones

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by gartung** [comment]
@kpedro88  Please abort test. I have found a few more thanks to Chris' suggestion of using edmPluginHelper to find the class type.

**Comment by kpedro88** [comment]
please abort
@gartung let me know when it's ready to test

**Comment by Dr15Jones** [comment]
@gartung please close this one

**Comment by gartung** [comment]
Did that on Friday.

**Pull request closed without merging**
