### PR TITLE
Make JobReport::reportReadBranches thread safe

### LINKED ISSUE #37363: PileUp::endStream() has a race condition in JobReport
As discussed in https://cms-talk.web.cern.ch/t/crab-jobs-failed-with-exit-code-50115/8567/19 , the `PileUp::endStream()` calls can happen concurrently.

https://github.com/cms-sw/cmssw/blob/40f81cc631c5c1d2cab343a84a722cb120f02637/Mixing/Base/src/PileUp.cc#L198-L204

Those calls call EmbeddedRootSource::endJob()

https://github.com/cms-sw/cmssw/blob/7356243aa00b72d631153095cf6b8dca5e58efba/IOPool/Input/src/EmbeddedRootSource.cc#L43-L46

which calls InputFile::reportReadBranches();

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/IOPool/Input/src/InputFile.cc#L106-L109

where the check to see if the info has already been printed is not thread safe

https://github.com/cms-sw/cmssw/blob/05bf287fcdb7188310b9dbbd132b0f4df5733a0a/FWCore/MessageLogger/src/JobReport.cc#L570-L573

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

CRAB jobs have been failing to parse the job report because of this race condition.

This is related to https://cms-talk.web.cern.ch/t/crab-jobs-failed-with-exit-code-50115/8567/19

#### PR validation:

Code compiles.

Fixes #37363

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by belforte** [comment]
it was production jobs, not CRAB. Not that it matters.. but the error comes from a WMA log as per Dan Riley's post https://cms-talk.web.cern.ch/t/crab-jobs-failed-with-exit-code-50115/8567/18

**Comment by makortel** [comment]
+1

I suppose this fix should be backported, maybe 12_3_X and 12_2_X would be sufficient.

**Comment by perrotta** [comment]
+1

**Pull request merged**
