### PR TITLE
Fix crosstalk

### PR DESCRIPTION
**Pull request by kpedro88**
It turns out that the measured gain for SiPMs in fC/GeV includes the crosstalk. Therefore, when this gain is divided out of the Geant4 energy in the simulation to calculate the number of photoelectrons, the crosstalk should also be divided out. We model the crosstalk with a Borel-Tanner distribution which has mean 1/(1-lambda).

@mariadalfonso showed that this fixes the single pion response: https://dalfonso.web.cern.ch/dalfonso/HCAL/isoTrack/AbsoluteHCALResponse_afterfixes.pdf

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@smuzaffar can you prod the bot?

**Comment by kpedro88** [comment]
@civanch, changes in the 2017 workflows are expected. The plots look reasonable to me. Ideally we could see some RecoJet/GenJet energy distributions trending toward 1, but I don't think such plots are in the standard validation/DQM suite. @mariadalfonso's slides linked in the PR description show the effect for a single pion scan.

**Comment by slava77** [comment]
[re-posting my message sent by email but lost by github]

On 10/21/16 1:20 PM, Kevin Pedro wrote:
> @civanch <https://github.com/civanch>, changes in the 2017 workflows are
> expected. The plots look reasonable to me. Ideally we could see some
> RecoJet/GenJet energy distributions trending toward 1, but I don't think
> such plots are in the standard validation/DQM suite. @mariadalfonso
> <https://github.com/mariadalfonso>'s slides linked in the PR description
> show the effect for a single pion scan.

RecoOverGen and CorrOverGen distributions are in the standard JetMET DQM
plots.

**Comment by kpedro88** [comment]
I find it odd that those didn't show any changes from this PR, then. Maybe the matrix test stats are too low.

**Comment by slava77** [comment]
- TTbar 2017 wf has 10 events. You can guess how many jets there will be.
- there are many changes in this PR. Jenkins comparisons adjust the threshold in this case to show only more significant diffs, in this case the threshold is 10% KS prob https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-21-1100+16302/16505/RelMonComparisonParams.txt

**Comment by kpedro88** [comment]
@civanch, changes in the 2017 workflows are expected. The plots look
reasonable to me. Ideally we could see some RecoJet/GenJet energy
distributions trending toward 1, but I don't think these are in the
standard validation/DQM suite. @mariadalfonso's slides linked in the PR
description show the effect for a single pion scan.

**Comment by slava77** [comment]
On 10/21/16 1:20 PM, Kevin Pedro wrote:
> @civanch <https://github.com/civanch>, changes in the 2017 workflows are
> expected. The plots look reasonable to me. Ideally we could see some
> RecoJet/GenJet energy distributions trending toward 1, but I don't think
> such plots are in the standard validation/DQM suite. @mariadalfonso
> <https://github.com/mariadalfonso>'s slides linked in the PR description
> show the effect for a single pion scan.

RecoOverGen and CorrOverGen distributions are in the standard JetMET DQM
plots.

**Pull request merged**
