### PR TITLE
Modernized DetIdAssociatorESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed framework constructs (e.g. ParameterSet and EventSetup records) from DetIdAssociators
- created DetIdAssociatorMakers which get configurations from the ParameterSet, set what EventSetup data products will be consumed and then create the appropriate DetIdAssociator.

#### PR validation:

The code compiles.

This is intended to be a refactoring so should not change any results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Part of #26748

**Comment by slava77** [comment]
> removed framework constructs (e.g. ParameterSet and EventSetup records) from DetIdAssociators

what was the problem with this?
Is there a rule somewhere that a tool delivered by an ES producer can not be constructed with a ParameterSet in the argument?

**Comment by Dr15Jones** [comment]
> what was the problem with this?
Is there a rule somewhere that a tool delivered by an ES producer can not be constructed with a ParameterSet in the argument?

From a maintenance standpoint, the less couplings the better. For example, we strongly discourage Event data products from knowing about the `edm::Event` or the parameter set system. I personally apply those same philosophies to data products in the EventSetup system as well.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27010	f8f515e
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
@christopheralanwest @pohsun @santocch could you please check?

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
this code it looks like will need clang-format cleaning

**Comment by Dr15Jones** [comment]
@fabiocos can the formating be done in a separate pull request or does it have to be in this one?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@Dr15Jones we will do it separately, I am just checking how much is left (or undone) in recent PRs

**Comment by santocch** [comment]
+1

**Pull request merged**
