### PR TITLE
make `TrackerSystematicMisalignments` a one module

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.
Addresses this https://github.com/cms-sw/cmssw/pull/34120#issuecomment-888261463.
I profit of this to merge the header file with the plugin src code.

#### PR validation:

Run unit tests `scramb runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
failure are unrelated.
The unit test (which is the only relevant thing) actually [succeeded](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7037e4/17335/unitTests/src/Alignment/TrackerAlignment/test/test_ProduceSystematicMisalignment/testing.log)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
