### PR TITLE
[12.4.X] supply DQM for `SiPixelCalSingleMuonTight`

### PR DESCRIPTION
**Pull request by mmusich**
backport of #39382

#### PR description:

With the foreseen increase of isolated muon trigger rates (see https://its.cern.ch/jira/browse/CMSHLT-2465 ) it becomes possible to run the `SiPixelCalSingleMuonTight` at express, allowing for quasi-online efficiency monitoring.
This PR adds a stub of DQM monitor for that AlCa flavour to start producing basic cluster properties histograms that are used as ingredients of the hit efficiency measurement.

#### PR validation:

Run

```console
 runTheMatrix.py -l 1002.4 -t 4 -j 8 --iboes
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of #39382, needed for data-taking monitoring purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, new-feature

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1002.4

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent 
   * would be good to have for data-taking when collisions resume.

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
@cms-sw/dqm-l2 has this been tested in P5? 
Although, as far as I understood, this should only affect **offline dqm** to allow extra monitoring at Express-level.

**Comment by mmusich** [comment]
> has this been tested in P5?

testing in the online DQM serves no purpose at all as this is run only in the offline DQM.

**Comment by rovere** [comment]
Could @cms-sw/dqm-l2 please review and sign again this PR?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
