### PR TITLE
TriggerResultsFilter: migrate to L1 Stage2 (81x)

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
forward port of #14878 , rebased on 8.1.x

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Mhm, looks like this error is unrelated to my changes ?

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
There are quite a few empty HLT Btag plots now in wf 25202
see in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-06-14-1100+14879/14461/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/HLT_BTag_Discriminator.html

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14879	8f9f56f
- reco is minimally affected
- jenkins tests pass and reco products are unchanged; there are differences in HLT plots though. So, chances are this PR gets updated.

**Comment by fwyzard** [comment]
I don't expect to update this PR, though there may be a follow up from @silviodonato or xavier.coubez@cern.ch to recover the plots (if this PR is indeed the reason they are empty).

**Comment by slava77** [comment]
On 6/15/16 4:14 PM, Andrea Bocci wrote:
> I don't expect to update this PR, though there may be a follow up from
> @silviodonato <https://github.com/silviodonato> or xavier.coubez@cern.ch
> <mailto:xavier.coubez@cern.ch> to recover the plots (if this PR is
> indeed the reason they are empty).

the plots are not empty in the baseline.
So, it is due to this PR (but it could as well reveal a latent
bug/feature in modules making these plots)

**Comment by silviodonato** [comment]
Ciao,
the release validation plots of HLT BTagging are ok in 81X ( https://goo.gl/KGmS4D ).
Perhaps the problem is related with the TriggerResults in https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/HLTriggerOffline/Btag/src/HLTBTagPerformanceAnalyzer.cc , but I don't understand how ...

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich
Please sign also this one!

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
