### PR TITLE
Get DataFormats/Math to compile on ICC.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlt** [comment]
`ExtVec_t.cpp` is crashing ICC IIRC. I will try to find a minimal testcase for Intel.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by ktf** [comment]
Intel already knows about this. Nothing do be done on your side.

**Comment by ktf** [comment]
Changes are trivial. Bypassing reco signature. Complain if not ok.

**Pull request merged**
