### PR TITLE
Add SoA macros to CUDADataFormats/Common.

### PR DESCRIPTION
**Pull request by ericcano**
#### PR description:

The SoA macros generate classes that subdivide externally allocated buffer in
columns with alignement adequate for GPUs (by default).
An test validates the SoA and provides usage example.

#### PR validation:

This PR provide new tools and does not interfere yet with current production code. The tools itself is validated with a test program.

### CODE REVIEW

**Comment by makortel** [comment]
Thanks @ericcano. `DataFormats/Common` is not a good place for this code though, because it would add a dependence on Eigen, and, if I understood correctly, currently these SoAs can not be stored in ROOT.

Given the dependence on Eigen, even a new package could be the justified. I presume the intention would be to use the SoA's  also in pure host code (without any dependence on CUDA), the best placement would likely still be under `DataFormats` (even if for now the Event products using the SoA's would be transient). There is a strong connection to GPUs, so perhaps the package would be best placed under `heterogeneous` category for review and maintenance.

@cms-sw/heterogeneous-l2

**Comment by makortel** [comment]
@ericcano Would you be able to present this model of building SoAs in the core software meeting on next Tuesday (Nov 9) or on the following week (Nov 16)?

**Comment by ericcano** [comment]
@makortel Yes, next Tuesday is fine.
Regarding the location, I will move all to `HeterogeneousCore/Common`

**Comment by makortel** [comment]
> Yes, next Tuesday is fine.

Thanks!

> Regarding the location, I will move all to `CUDADataFormats/Common`

This is better concerning use in CUDA data formats, but I have an impression that these SoA's would be used also in host data formats (e.g. with Alpaka), in which case a better place for this code would be a package that does not bring the dependence on CUDA. I.e. while in the near term this package would be fine, I'd guess in the not-so-distant future we'd need to move it. I don't have good suggestions though right now, a lot depends on the intended scope (along "CUDA vs. any memory", if the SoA's would eventually be persisted, ...).

**Comment by ericcano** [comment]
Indeed, it is orthogonal to memory allocation. There are currently some dependency to cuda  includes, but it's possible to make them conditional on the compiler used.

Regarding SoA vs AoS, AoS will be more cache friendly on CPUs, so we'll have to see what we want to use where.

**Comment by fwyzard** [comment]
> Regarding SoA vs AoS, AoS will be more cache friendly on CPUs, so we'll have to see what we want to use where.

Unless we get the compiler to vectorise on the cpu, then the SoA may be more cache friendly also on the CPU ?

**Comment by fwyzard** [comment]
A possible package for these file: `DataFormats/SoA`

**Comment by ericcano** [comment]
The core software meeting presentation can be found [here](https://indico.cern.ch/event/1095513/contributions/4608024/attachments/2341751/3993656/SoA%20stores%20and%20view.pdf).

**Comment by ericcano** [comment]
> Unless we get the compiler to vectorise on the cpu, then the SoA may be more cache friendly also on the CPU ?

My guess was that components adjacent in memory would fit in one/few cache lines (64B on intel), but only SoA gives a chance to vectorize, indeed, so it's a hard guess to decide which memory layout is better on CPU.

In the SoA case, looping on adjacent indices in CPU "kernels" will probably leverage the remainder of the cache lines, one per parameter (unless there are more parameters/columns to work on than available cache lines).

**Comment by Martin-Grunewald** [comment]
-1
rebase needed!

**Comment by fwyzard** [comment]
I think this PR has been superseded by all the development work merged in 12.5.x and 12.6.x, up to #39319 .

@ericcano, do you agree this one could be closed ?

**Comment by ericcano** [comment]
> @ericcano, do you agree this one could be closed ?

Yes

**Pull request closed without merging**
