### PR TITLE
Update HSCParticle object to be compatible with MiniAOD

### PR DESCRIPTION
**Pull request by enibigir**
#### PR description:

This PR added new objects for the HSCP collection in MiniAOD

#### PR validation:

The following tests have been performed successfully: 

- scram b runtests use-ibeos
- runTheMatrix.py -l limited -i all --ibeos
- scram build code-checks
- scram build code-format

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
@cmsbuild , please test workflow 11684.0
 * I think this actually uses the object

**Comment by tvami** [comment]
> Undefined workflows: 11684.0

Hmm ok then this was removed in the meantime...

**Comment by tvami** [comment]
+analysis

**Comment by tvami** [comment]
@enibigir can you rename the PR to "Update HSCParticle object to be compatible with MiniAOD", or something similar? In the end you dont actually add a new object type here, just update/extend it.

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Pull request merged**
