### PR TITLE
Remove BX comparisons for CLCT and LCT in CSC L1T DQM [11_3_X]

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Remove the BX comparisons for CLCT and LCT in CSC L1T DQM. The data CLCTs and LCTs have their BX information truncated. I had previously added this PR #33335 to simulate this truncation in the emulator. Even with function, there will always be substantial differences because the BX's are defined differently in data and emulator. For that reason it is best to remove the BX comparisons for CLCT and LCT altogether. The ALCT BX is not truncated, so those comparisons still make sense.

#### PR validation:

Code compiles. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

To be back-ported once #33357 is merged.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by dildick** [comment]
@jfernan2 This simple PR should pass all tests. I checked it previously when I was working on #33335. I'm running all matrix tests and will post the output when they are done.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick there are changes, can you confirm they are what you expect?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-04-08-2300+87b232/42150/dqm-histo-comparison-summary.html
Thanks

**Comment by dildick** [comment]
I don't see any "_data" histograms. Why is that? 

In principle, the code will run fine on real data. But on MC relval, it won't make sense. Because one type of TPs will have their BXs compressed, whereas the other won't. An example where this happens:

Screen Shot 2021-04-09 at 8 59 30 AM

**Comment by dildick** [comment]
I suppose I could add a check if the module is running on real data or not. If data, use `getBXData`. If MC, use `getBX`. That would fix the failures.

**Comment by dildick** [comment]
@jfernan2 It turns out that BX comparisons of the CLCT and LCT do not make much sense, even with the bit masking. To avoid confusion for shifters it is probably best to remove these plots from the DQM. The ALCT BX comparison does make sense, so that one is kept.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
@jfernan2 Thanks! After this, I'll wait a bit with DQM dev until I have received feedback from this week's MWGR. And then perhaps 1 more PR to get it into good shape for Run-3

**Comment by silviodonato** [comment]
+1

**Pull request merged**
