### PR TITLE
bsunanda:Run2 hcx86 Bug fix to assign BH geometry correctly

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar @davidlange6 I did not make the commit to the DQM part. I wonder how it got added to this PR

**Comment by smuzaffar** [comment]
@bsunanda, can you pelase re-create/re-base on top of CMSSW_8_1_X?

**Comment by bsunanda** [comment]
@smuzaffar I did it on top of CMSSW_8_1_X_2016-07-08-1100. Shall I do that again?

**Comment by smuzaffar** [comment]
yes please

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar still it shows dam dependency

**Comment by smuzaffar** [comment]
Can you try to do something like this
```
git clone --reference /afs/cern.ch/cms/git-cmssw-mirror/cmssw.git  git@github.com:cms-sw/cmssw
cd cmssw/
git remote add bsunanda git@github.com:bsunanda/cmssw
git fetch bsunanda Run2-hcx86:Run2-hcx86
git checkout CMSSW_8_1_X
git checkout -b new-Run2-hcx86
git cherry-pick 761b80036f0d01811e9bfb6967b73c4009718d38
git push -f bsunanda new-Run2-hcx86:Run2-hcx86

```

**Comment by bsunanda** [comment]
@smuzaffar just did that

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by smuzaffar** [comment]
cmsbot should recognize it now and update the labels

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
