### PR TITLE
Remove deprecated heavy-ion reconstruction 

### PR DESCRIPTION
**Pull request by mandrenguyen**
The old version of the HI reco that was based on `--scenario HeavyIons` has not been used since 2015, and has since been supplanted by the `era` functionality. 
This is a first attempt at cleaning up some old stuff that is causing maintenance issues.  
It should be noted that we will no longer have a running workflows for heavy ion data from 2015 and earlier.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
@mandrenguyen 
With this clean up PR, I see you clean up also workflow of RUN-1. So, we do not support Run-1 HI anymore?

**Comment by mandrenguyen** [comment]
@srimanob Yeah, that's the main point that needs to be decided here.  For Run 1 we used the old `scenario HeavyIons`, which is a different reconstruction workflow.  Now with the `pp_on_AA` process modifier we mostly just tune parameters of the pp reco.  We have not been maintaining the old style reconstruction, and it's starting to cause issues to keep this legacy code around.  OTOH we have never setup the era-based reconstruction for Run 1.  I think if we wanted to reconstruct Run 1 data in a new release we would have to set up an appropriate era.

**Comment by makortel** [comment]
> OTOH we have never setup the era-based reconstruction for Run 1. I think if we wanted to reconstruct Run 1 data in a new release we would have to set up an appropriate era.

The design intent of the Era system was that "no Era" corresponds to Run 1. Re-reconstructing Run 1 data is tested in PRs and IBs.

**Comment by mandrenguyen** [comment]
> > OTOH we have never setup the era-based reconstruction for Run 1. I think if we wanted to reconstruct Run 1 data in a new release we would have to set up an appropriate era.
> 
> The design intent of the Era system was that "no Era" corresponds to Run 1. Re-reconstructing Run 1 data is tested in PRs and IBs.

No era will give you vanilla pp reconstruction.  That will not run in heavy-ion events, we will explode the memory.  I introduced a `pp_on_AA` process modifier which is loaded by the dedicated Run 2 and Run 3 heavy-ion eras.  We could extend it to Run 1 as well, but there's a big difference between having something that technically executes and something that can actually be used for physics. Since there's no plan to reprocess Run 1 data with a new release, it would not make any sense to dedicate personpower to that. 
That's more or less the case with the old scenario based HI reco now.  We know it technically executes, because it runs in relval.  However, I would not trust the output for physics.  No one has used this reconstruction since whatever cmssw release we had in 2015.

**Comment by srimanob** [comment]
@makortel @mandrenguyen 
Do we need the discussion? Or this is already agreed on the scope of this PR. Thx.

**Comment by mandrenguyen** [comment]
> @makortel @mandrenguyen Do we need the discussion? Or this is already agreed on the scope of this PR. Thx.

I think so, yes.  We can continue here or maybe briefly at the ORP meeting.  Or is there a better forum?

**Comment by srimanob** [comment]
> > @makortel @mandrenguyen Do we need the discussion? Or this is already agreed on the scope of this PR. Thx.
> 
> I think so, yes. We can continue here or maybe briefly at the ORP meeting. Or is there a better forum?

OK for me, or RECO meeting.

**Comment by makortel** [comment]
For pp reco I'd be comfortable only with a very high level decision on abandoning the capability of reprocessing Run 1 data (I'm personally not against, but AFAIK this has been a requirement since the beginning). But I don't know how much of that applies to HI reco. Maybe consult at least O&C L1s? (@sextonkennedy)

**Comment by mandrenguyen** [comment]
> For pp reco I'd be comfortable only with a very high level decision on abandoning the capability of reprocessing Run 1 data (I'm personally not against, but AFAIK this has been a requirement since the beginning). But I don't know how much of that applies to HI reco. Maybe consult at least O&C L1s? (@sextonkennedy)

Following up, there was an email exchange  with @sextonkennedy as well as the data preservation experts (with @makortel in the loop).  Conclusion: there does not appear to be an objection to deprecating the old reco in new releases.

**Comment by mandrenguyen** [comment]
@srimanob I raised the issue at the ORP, but I guess you couldn't make it. Since this would need to be signed by @cms-sw/pdmv-l2 and @cms-sw/upgrade-l2 should we continue the discussion here, or is there another forum in which you would like to follow up.  Also, @makortel if you have any further comments, please say so.

**Comment by srimanob** [comment]
I am happy to sign. Maybe comment in O&C doc for today meeting should be enough. So that we can decide if it should go wider for discussion or we move on.

**Comment by antoniovilela** [comment]
@mandrenguyen 
Could you forward us (ORP), if possible, the emails exchanged with O&C L1, so we can understand the full picture?
Otherwise, people seem happy, so I would encourage everyone to sign.
Thanks.

**Comment by mandrenguyen** [comment]
ping @cms-sw/pdmv-l2 @cms-sw/upgrade-l2

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
@mandrenguyen I just noticed there are some conflicts to be solved. Sorry for the delay on my side not helping there.

**Comment by fabiocos** [comment]
In #43846 I have update RecoHI/HiTracking to allow the PR to correctly work even without this PR, so I expect this is the cause of the issue

**Comment by rappoccio** [comment]
@mandrenguyen there are some conflicts that were introduced, can you fix? Thanks.

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
