### PR TITLE
Run3-alca226 Update the macros to e used for Run3 analysis of hadron calorimeter calibration data with isolated muons

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the macros to e used for Run3 analysis of HCAL calibration data with isolated muons

#### PR validation:

Use the macros to analyze Run3 calibration data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
type hcal

**Comment by ChrisMisan** [comment]
@bsunanda please squash the commits

**Comment by ChrisMisan** [comment]
@bsunanda I have a couple comments for possible future improvements of the code, they're applying to the whole HcalCalibAlgos. 

There is a lot of code which abuses if statement, this can all go into one loop:
https://github.com/cms-sw/cmssw/blob/7654b671ce6f103ca900252d8879e1a9858f3f18/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc#L682

There is no reason why those kind of variables shouldn't be an array:
https://github.com/cms-sw/cmssw/blob/7654b671ce6f103ca900252d8879e1a9858f3f18/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc#L410

There's a lot of commented lines which doesn't make sense syntax-wise when uncommented:
https://github.com/cms-sw/cmssw/blob/7654b671ce6f103ca900252d8879e1a9858f3f18/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc#L1001

Instead of using preprocessor directives you should consider using a flag exposed to the python configuration:
https://github.com/cms-sw/cmssw/blob/7654b671ce6f103ca900252d8879e1a9858f3f18/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc#L395

There is a lot of memory management issues, for example in this file:
https://github.com/cms-sw/cmssw/blob/592b4a940ecd991a4c0ddd8c3965766aafb7b87a/Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C

maybe it'd be better to use smart pointers instead of manually managing the memory?

Please consider using unordered sets and maps when ordering is not necessary:
https://github.com/cms-sw/cmssw/blob/592b4a940ecd991a4c0ddd8c3965766aafb7b87a/Calibration/HcalCalibAlgos/macros/AnalyzeLepTree.C

Initializations could be inlined:
https://github.com/cms-sw/cmssw/blob/592b4a940ecd991a4c0ddd8c3965766aafb7b87a/Calibration/HcalCalibAlgos/macros/HBHEMuonHighEta.C#L318

There are comments which are misleading or incorrect:
https://github.com/cms-sw/cmssw/blob/592b4a940ecd991a4c0ddd8c3965766aafb7b87a/Calibration/HcalCalibAlgos/macros/HBHEMuonHighEta.C#L547

**Comment by bsunanda** [comment]
@ChrisMisan I am squashing this right now. I shall slowly update the other parts as pointed out by you

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
+alca
- PR in line with the description
- differences in MTD and msgLogger

**Comment by perrotta** [comment]
+1

**Pull request merged**
