### PR TITLE
Add PFCluster validation to ECAL-only and HCAL-only workflows

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add PFCluster validation to ECAL-only and HCAL-only workflows

#### PR validation:

Ran the ECAL-only (11634.511) and HCAL-only (11634.521) matrix workflows.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test workflow 11634.511, 11634.521

**Comment by fwyzard** [comment]
The almost complete rewrite of `Validation/CaloTowers/test/CaloScan/template_2018_since_1010pre2.py` is  due to the conversion to UNIX-style line endings.

**Comment by mariadalfonso** [comment]
@fwyzard 
why we have the caloTowers in these HCAL-only or ECAL-only thing ?

**Comment by fwyzard** [comment]
Mhm, I'm confused...

In `Validation/Configuration/python/globalValidation_cff.py` I see that we have `calotowersValidationSequence` only in `globalValidationHCAL`:
```python
globalValidationHCAL = cms.Sequence(
      hcalSimHitsValidationSequence
    + hcaldigisValidationSequence
    + hcalSimHitStudy
    + hcalRecHitsValidationSequence
    + calotowersValidationSequence
)
```
and not in `globalValidationECALOnly` or `globalValidationHCALOnly`.

In `Validation/CaloTowers/test/CaloScan/template_2018_since_1010pre2.py` I didn't make any changes about calotowers, though the whole file shows up as changed because of fixing the newlines (I suggest looking at the changes [hiding whitespace changes](https://github.com/cms-sw/cmssw/pull/30636/files?diff=unified&w=1)).

However I'm confused because it looks like I am adding `globalValidationHCALOnly` from scratch, when I thought I only added one module to an existing sequence ?

**Comment by abdoulline** [comment]
Andrea,

just one particular aspect: 
there is no calotowersValidationSequence in globalValidationHCAL  anymore:
https://github.com/cms-sw/cmssw/pull/30464/files

    Salavat

**Comment by fwyzard** [comment]
OK, I've rebased it and now the diff makes more sense ...

**Comment by fwyzard** [comment]
@abdoulline indeed, looks like I started from a stale branch, and for some reason git did not give me any conflicts.
After rebasing it looks better.

**Comment by fwyzard** [comment]
@cmsbuild, please test workflow 11634.511, 11634.521

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
