### PR TITLE
Calo Geometry Loader: DD dependency cleanup

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add an extra template parameter to allow usage of a different DDCompactView in the template specialization 

Note: Migration away from using CLHEP is not part of this PR.

#### PR validation:

usual RelVal tests

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna for my understanding, what is the idea behind this update? To pass a DD4hep structure instead of a DD one?

**Comment by ianna** [comment]
> @ianna for my understanding, what is the idea behind this update? To pass a DD4hep structure instead of a DD one?

yes, that's the idea

**Comment by fabiocos** [comment]
+1

**Pull request merged**
