### PR TITLE
[Fireworks] Backport of auto detect geometry version from global tag

### PR DESCRIPTION
**Pull request by alja**
This PR is backport of #29169 to CMSSW_11_0_X branch.

### CODE REVIEW

**Comment by alja** [comment]
@smuzaffar 
-1 the change is depends on changes in  https://github.com/cms-data/Fireworks-Geometry

**Comment by smuzaffar** [comment]
test parameters
 - pull_request = cms-sw/cmsdist#5728

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
@alja can we proceed with merging this PR and cms-sw/cmsdist#5728?

**Comment by alja** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
