### PR TITLE
Hlt tau validation update cmssw900

### PR DESCRIPTION
**Pull request by slehti**
Added L1IsoTaus, and support for using tag and probe (meant for prompt monitoring).

### CODE REVIEW

**Comment by slava77** [comment]
-1

looks like it's submitted to a wrong release

**Comment by kpedro88** [comment]
-1

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
please rebase (for CMSSW 9.1.x) and/or submit for the correct branch (for 9.0.x)

**Comment by davidlange6** [comment]
closing - please submit a rebased PR. Thanks

**Pull request closed without merging**
