### PR TITLE
[NanoAOD] Add pthatmax variable

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR switches on the flag to save the `pthatmax` variable in the `Pileup` table for central NanoAOD, beginning from `v13`. The event size increase is negligible (0.002 kb /event).

#### PR validation:

- passes the standard runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes the following NanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 2500.0,2500.001,2500.002,2500.01,2500.011,2500.012,2500.1,2500.2,2500.21,2500.3,2500.31,2500.4`

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
