### PR TITLE
MTD geometry: fix BTL numbering scheme to work with DD4hep through Geant4

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses the failure of the validation of BTL simulation and reconstruction when comparing DDD and DD4hep versions, see 
https://cms-talk.web.cern.ch/t/valdb-13-2-0-pre1-phase2-d99-dd4hep-reconstruction-fullsim-mtd-reports-status-has-been-changed/26069/3
The problem is observed in the global z coordinate of the BTL SimHits, and it is given by incorrect ```BTLDetId``` being filled for the DD4hep version, as shown by debugging dumps.

Unit tests are showing agreement between the two versions of geometry since 2020, but the way the BTL ```BaseNumber``` object is filled in the ```MtdSD``` interface to Geant4 does not clean the DD4hep output for the appended version number in the name of the volume, as instead is done in the geometry test code. Such a cleaning is now done inside the BTL numbering scheme natively, causing the unit test and Geant4-based simulation to behave in the same way.

At the same time, all MTD geometry unit tests have been updated to scenario 2026D98 (identical to D95 as far as MTD is concerned, no need to update external references).

#### PR validation:

Unit tests run without issue, the debugging printout of the numbering scheme and ```MtdSD``` is the same for 100 single muons tracked by Geant4.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by bsunanda** [comment]
+geometry

**Comment by fabiocos** [comment]
@ctarricone FYI

**Comment by fabiocos** [comment]
@bsunanda @civanch ideally I believe I should replicate the test https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDCommonData/test/DD4hep_TestMTDIdealGeometry.cc should be replicated interfacing it with g4SimHits as done in https://github.com/cms-sw/cmssw/blob/master/SimG4Core/PrintGeomInfo/plugins/PrintSensitive.cc in order to avoid possible mismatches between checks in future

**Comment by fabiocos** [comment]
type bugfix

**Comment by civanch** [comment]
@fabiocos , I think yes, SIM geometry should be fully tested in PrintGeomInfo. You may tune existing tests and add a new is needed.

**Comment by fabiocos** [comment]
The test discussed above is added in the latest commit, and run as a uit test. The same reference file used by unit tests in ```Geometry/MTDCommonData``` is used here, saving space and allowing a cross check between the basic model build in DDD/DD4hep as used in reconstruction geometry, and its translation into the Geant4 geometry model.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@civanch @smuzaffar I did the development disabling biglib with ```scram b disable-biglib```, to speed up compilation, and the test was working smoothly both in CMSSW_13_2_0_pre1 and CMSSW_13_2_0_pre2. Enabling biglibs causes a failure also in CMSSW_13_2_0_pre1. I am investigating.

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
The newly added unit test was successful as expected, the errors appear unrelated this PR

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@cms-sw/orp-l2 @smuzaffar there seems to be a problem with inputs unrelated to this PR, I see it also in other PRs

**Comment by fabiocos** [comment]
please test

**Comment by srimanob** [comment]
Hi @fabiocos 
Thanks very much for the prompt fix. Do you test only with printout, or you have some plots for comparison also? If yes, maybe good to attach it in this PR.

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@srimanob the printout of the DetIds ad position is the crucial test, the problem was in the way the DetIds were built from the list of volume names and corresponding copy numbers. Anyway I asked to @ctarricone to make a DQM comparison as well, which shows the solution of the problem, as can be also seen in the validation plots of the test above BTW. Cristian, could you please post those plots here as supporting documentation?

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Comment by ctarricone** [comment]
@srimanob @fabiocos I tested the PR 42127 on the 13_2_0_pre1_Phase2_D98 release comparing the DDD and DD4hep setup on MinBias samples of 1000 events. You can find all the distributions comparing 13_2_0_pre1_Phase2_D98 w/PR42127 DDD  (blue line) and 13_2_0_pre1_Phase2_D98 w/PR42127 DD4hep (red points) at the following link:
https://cernbox.cern.ch/s/sVQsUmrSnNCYbMo

**Pull request merged**
