### PR TITLE
move scripts in CondCore to python3

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
Just FYI: I tried to test this PR inCMSSW_12_0_X_2021-07-06-1100 by running `CondCore/Utilities/python/CondDBFW/uploadConditions.py`. I saw this error:
```
Traceback (most recent call last):
  File "CondCore/Utilities/python/CondDBFW/uploadConditions.py", line 21, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
```
Maybe there was something wrong with my setup, but now the script is not giving the Oracle error message but rather this different error.

**Comment by mmusich** [comment]
@cvuosalo see please https://github.com/cms-sw/cmssw/issues/34349

**Comment by yuanchao** [comment]
+1

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
just to test again with new IB

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
