### PR TITLE
Move Data ReReco ZeroBias RelvVals to use @rerecoZeroBias DQM sequence

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

As discussed in  this JIRA ticket https://its.cern.ch/jira/browse/PDMVRELVALS-50 we  (Tracker DPG) would like to have the `ZeroBias` Run2 Data Relvals produced using a DQM sequence containing  `@commonSiStripZeroBias`, see: https://github.com/cms-sw/cmssw/blob/56a9801944a3f85dc458b2c8b7e4c33737929dca/DQMOffline/Configuration/python/autoDQM.py#L5 in lieu of `@standardDQM`see: https://github.com/cms-sw/cmssw/blob/56a9801944a3f85dc458b2c8b7e4c33737929dca/DQMOffline/Configuration/python/autoDQM.py#L103  for the `ZeroBias` PD as it currently it is in the relval matrix.
This would allow to test the sequence that is actually run at Tier-0 during physics production certification and spot beforehand possible issues affecting production, as it recently happened e.g. for the issues leading to PR: https://github.com/cms-sw/cmssw/pull/27246. 
The DQM and PdmV teams have suggested to use the sequence `@rerecoZeroBias` defined at https://github.com/cms-sw/cmssw/blob/56a9801944a3f85dc458b2c8b7e4c33737929dca/DQMOffline/Configuration/python/autoDQM.py#L87 (introduced in this commit https://github.com/cms-sw/cmssw/pull/26391/commits/33902118dd338d05d5630cc16c0b9d99f5696723) which is supposed to be used also during the UltraLegacy Run3 data re-reco

#### PR validation:

Standard tests with runTheMatrix for the touched workflows pass:
```
runTheMatrix.py -l 134.710,134.812,134.912,136.732,136.745,136.756,136.767,136.778,136.789,136.801,136.813,136.825,136.837,136.856,136.868,136.880,136.892 -t 4 -j 8 --ibeos
```

though I had to refrain to use `@rerecoZeroBias` for the following worflows 134.710,134.812,134.912,136.732,136.745,136.756,136.767,136.778 because using this sequence they would break, as harvesting step fails with:
```
----- Begin Fatal Exception 27-Jun-2019 11:22:17 CEST-----------------------
An exception of category 'StdException' occurred while
[0] Processing global end LuminosityBlock run: 251251 luminosityBlock: 139
[1] Calling method for module SiPixelCertification/'sipixelCertification'
Exception Message:
A std::exception was thrown.
DQM object not found: Pixel/EventInfo/reportSummary
----- End Fatal Exception -------------------------------------------------
```
interestingly for the phase-0 pixel geometry (2015,2016).
@fioriNTU @schneiml @jfernan2 FYI, as this might have implications for the UL 2016 re-reco.

#### if this PR is a backport please specify the original PR:

This PR is not a backport

cc:
@jandrea @arossi83

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.789,136.801,136.813,136.825,136.837,136.856,136.868,136.880,136.892

**Comment by schneiml** [comment]
Two comments:
- What will be used for the (UL) rereco is not decided by the code here, but by what we (DQM) tell PdmV to run. The request from Tracker side to use `@commonSiStripZeroBias` (via `@rerecoZeroBias`) is well known and should be respected no matter what happens to this PR.
- This PR however *does* significantly improve our PR tests, by moving them closer to what will run in production (we used `@commonSiStripZeroBias` in Prompt since a long time and we will be using it for rerecos in the future).

**Comment by fabiocos** [comment]
@prebello @zhenhu @kpedro88 could you please have a look at this? @jfernan2 this is involving DQM sequences

**Comment by fabiocos** [comment]
There is no conflict with #27449 in case that is merged (as we would like to do quickly)

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by chayanit** [comment]
@mmusich , we have received report from PPS validator in 11_0_0_pre4 campaign recently. They complained about missing DQM plots in ZeroBias relvals and seems to be caused by this PR. Have you noticed about this? 
Cheers,
Chayanit

**Comment by mmusich** [comment]
@chayanit. This PR has been taylored for the needs of Tracker / Tracking, and indeed has fared perfectly fine for the purposes of Tracker / Tracking. You can check that in our validation reports that are all OK for 11_0_0_pre4 (see https://cms-pdmv.cern.ch/valdb/?srch=11_0_0_pre4&Reconstruction=true&RData=true).
As for other DPGs, it's a pity that PdmV did not advertise the ticket where this PR was discussed: https://its.cern.ch/jira/browse/PDMVRELVALS-50 as I explicitly requested. 
Can you clarify why this did not happen?
By the way: the PPS addition to the sequence has been done in this commit https://github.com/cms-sw/cmssw/commit/835a4affdca2c16630807949e9c4c3d9e969c5a2#diff-cbd7e70fcf453b18b0264833a02bcee8. It seems it did not enter in 11_0_0_pre4, but will be there in 11_0_0_pre5.

**Comment by chayanit** [comment]
@mmusich clearly, this thing happened before I started so I can't answer why the advertise did not happen. I'm just trying to dig out what was happened and I think everything is clear now. I will inform PPS validators that everything should be fine in next releases. Thanks.

**Comment by mmusich** [comment]
@chayanit 

> I will inform PPS validators that everything should be fine in next releases. 

Actually I don't think it will fine either in 11_0_0_pre5 because the `@ctpps` tag needs to be added to `rerecoZeroBiasFakeHLT` as that is the sequence which is run on 2017 and 2018 after this PR https://github.com/cms-sw/cmssw/pull/27467 has been merged.
I can fix it in the PR I have open on these file https://github.com/cms-sw/cmssw/pull/27727 (after I test it runs fine).

**Pull request merged**
