### PR TITLE
a first unit test for backward compatibility of Scouting data formats [`13_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #41093

#### PR description:

This PR adds a unit test to catch non-backward-compatible changes to the Scouting data formats.

From the description of #41093:

>This PR adds a refined version of the unit test described in https://github.com/cms-sw/cmssw/issues/41040#issuecomment-1470567862 [*]. The aim of the test is to fail whenever non-backward-compatible changes are introduced in the Scouting data formats.
>
>The implementation of the test could certainly be improved (one suggestion is in https://github.com/cms-sw/cmssw/issues/41040#issuecomment-1470689465), but I decided to open a draft PR because I think the test in this PR is better than nothing. (I plan to address https://github.com/cms-sw/cmssw/issues/41040#issuecomment-1470689465, but I don't have an ETA for that.)
>
>[*]
>
>More precisely, there are two unit tests, one for the Run-2 Scouting data formats ("Scouting*"), and one for the Run-3 ones ("Run3Scouting*"). The two tests have the same structure:
>
> - a 1st step reads O(100) events from an existing EDM file, and writes the Scouting collections to disk (this first step should fail if non-backward-compatible changes are made to the data formats);
>
> - a 2nd step uses FWLite to print to stdout one entry/object for each of the Scouting data formats being tested. To check that the correct values are read, the test compares the output of step-2 to a reference in the form of a text file. This is currently done for 1 object per data format. It might be necessary to check more than 1 object (and/or more than 1 event), because https://github.com/cms-sw/cmssw/pull/41025#issuecomment-1471777700 showed that some issues can only be spotted when checking multiple objects/events.

#### PR validation:

The new unit tests pass locally.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41093

Unit test for Scouting data formats in the release cycle currently used online.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
hold

Unit test fails on PowerPC, see #41189.

**Comment by missirol** [comment]
The latest push backports the fix in #41219 for PowerPC builds.

I don't know if the "hold" should stay: the pyroot issue described in #41189 and #41222 may, or may not, require further changes to the unit test. Maybe it's better to wait a bit.

**Comment by missirol** [comment]
unhold

The `pyroot` issue described in https://github.com/cms-sw/cmssw/pull/41189 and https://github.com/cms-sw/cmssw/issues/41222 hasn't been solved yet. Given that `ROOT6_X` IBs do not run for `13_0_X`, I dare say this backport could be merged. I let Core-Sw decide.

**Comment by makortel** [comment]
+core

Let's get them in. In the longer term we'll working on an alternative testing mechanism (in reaction to https://github.com/cms-sw/cmssw/issues/41348, along https://github.com/cms-sw/cmssw/pull/41395)

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/41189 and https://github.com/cms-sw/cmssw/pull/41219

**Pull request merged**
