### PR TITLE
Final fix for HcalCalPedestals

### PR DESCRIPTION
**Pull request by diguida**
Following comment by @bsunanda in #10054

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
currently testing with:
```
cmsDriver.py HCalCalPedestals -s ALCA:HcalCalPedestal --data --scenario=pp -n 100 --conditions auto:run2_data_FULL --customise=SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField AutoFromDBCurrent --processName=USER --filein root://eoscms//eos/cms/store/data/Run2015B/TestEnablesEcalHcal/RAW/v1/000/251/252/00000/82A5CE77-D025-E511-8EC3-02163E0136E2.root
```

**Comment by diguida** [comment]
@kodolova this is something you might want to watch as well.

**Comment by mmusich** [comment]
The test was successful.
It gives:
```
File ALCARECOHcalCalPedestal.root Events 16393
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
EventAuxiliary 133.318 30.4614
EventSelections 73.1914 3.04752
BranchListIndexes 18.078 2.27567
EventProductProvenance 16.0756 2.12566
```

**Comment by mmusich** [comment]
well. It didn't crash, but it should have some different output.
```
OutALCARECOHcalCalPedestal_noDrop = cms.PSet(
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring('pathALCARECOHcalCalPedestal')
    ),
    outputCommands = cms.untracked.vstring(
	'keep *_gtDigisAlCaMB_*_*',
        'keep HBHERecHitsSorted_hbherecoMB_*_*',
        'keep HORecHitsSorted_horecoMB_*_*',
        'keep HFRecHitsSorted_hfrecoMB_*_*',
        'keep HFRecHitsSorted_hfrecoMBspecial_*_*',
        'keep HBHERecHitsSorted_hbherecoNoise_*_*',
        'keep HORecHitsSorted_horecoNoise_*_*',
        'keep HFRecHitsSorted_hfrecoNoise_*_*')
)
```

**Comment by diguida** [comment]
ok, seems that I need another fix...

**Comment by diguida** [comment]
Issue found: it is a bug in the `keep` statement (well, I'd rather call it regression...)
Bad, we need to change the output for MinBias too.

Problems are always coming on Friday.

**Comment by mmusich** [comment]
@diguida yes, since we changed the cloning the keep should be changes as well

**Comment by mmusich** [comment]
a mininal set would be:
```
'keep *_gtDigisAlCaPedestals_*_*',
'keep HBHERecHitsSorted_hbherecoPedestals_*_*',
'keep HORecHitsSorted_horecoPedestals_*_*',
'keep HFRecHitsSorted_hfrecoPedestals_*_*'
```
@kodolova @bsunanda can you comment please? We cannot guess what you need.
For the DIGI do you need all flavours of them?

**Comment by diguida** [comment]
@mmusich I have tested everything. Let me summarise also the discussion we had:
* for `HcalCalMinBias` AlCaReco: everything is ok.
 * On the events firing its own trigger bits, the AlCaReco will:
    * clone the HCAL un-packer into `hcalDigiAlCaMB` module and customise it (actually it is a no-op, as the input collection is `rawDataCollector, and the samples included are still 10),
    * clone the L1GT un-packer in `gtDigisAlCaMB` module and customise it.
    * Next, the `RecHit` producers for HBHE, HF and HO are cloned into `hbherecoNoise`, `hfrecoNoise` and `hfrecoMBspecial`, `horecoNoise`, and customised in order to consume digis from `hcalDigiAlCaMB` module, to change the first sample in the time slice reconstruction values (starting from 0 in HBHE, from 0 or 2 in HF, from 0 in HO) and not to override them from conditions, and to switch off ZS in reconstruction.
 * The output module will keep `RecHit`s coming from modules included in the standard NZS reconstruction sequence (`hbherecoMB`, `horecoMB`, `hfrecoMB` are defined in [hcalLocalRecoNZS_cff](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/RecoLocalCalo/Configuration/python/hcalLocalRecoNZS_cff.py), the L1GT digis unpacked in the AlCaReco (but not the HCAL digis), and the `RecHit`s produced by the four local reconstruction modules in it.

* For `HcalCalPedestal`, the idea behind by code inspection and discussions with @kodolova and @mmusich it is to:
 * unpack special digis from a dedicated collection in a dedicated PD/stream
 * run NZS reconstruction on top of it
 * store the `RecHit`s for computing HCAL calibrations.
In order to do this, the steps are similar to the ones in `HcalCalMinBias`, with few differences, and avoiding changing modules, rather than cloning:
 * No event selection based on trigger bits (it is a dedicated stream), but filter on calibration events in `hltHcalCalibrationRaw` collection;
 * clone the HCAL un-packer module and customise it: this is done by cloning into the newly defined `hcalDigiAlCaPedestal` module, and by changing the input collection to be `hltHcalCalibrationRaw`'
 * clone the L1GT un-packer in `gtDigisAlCaPedestal` module and customise it;
 * clone the `RecHit` producers for HBHE, HF and HO into `hbherecoPedestal`, `hfrecoPedestal`, `horecoPedestal`, and customised in order to consume digis from `hcalDigiAlCaPedestal` module, to change the first sample in the time slice reconstruction values (starting from 0 in HBHE, from 0 or 2 in HF, from 0 in HO) and not to override them from conditions, and to switch off ZS in reconstruction
 * store the L1GT digis unpacked in the AlCaReco (but not the HCAL digis), and the `RecHit`s produced by the three local reconstruction modules in it.

This is done by the fix by @mmusich already in, as well as trimming and changing the output collections.

@kodolova @bsunanda please confirm.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
## Test Setup
* Test run on data: `TestEnablesEcalHcal` for run 251252 (13 TeV collisions, 3.8T);
* Input data tier: RAW
* Number of events: 247930
* Events selected: 16393

````
cmsDriver.py HCalCalPedestal -s ALCA:HcalCalPedestal --data --scenario=pp --conditions auto:run2_data_FULL -n -1 --customise=SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField AutoFromDBCurrent --processName=USER --filein root://eoscms//eos/cms/store/data/Run2015B/TestEnablesEcalHcal/RAW/v1/000/251/252/00000/82A5CE77-D025-E511-8EC3-02163E0136E2.root
````

## Output Collections

````
Type                                                                        Module                  Label     Process
------------------------------------------------------------------------------------------------------------------------
L1GlobalTriggerReadoutRecord                                                "gtDigisAlCaPedestal"   ""        "USER"
L1MuGMTReadoutCollection                                                    "gtDigisAlCaPedestal"   ""        "USER"
edm::SortedCollection<HBHERecHit,edm::StrictWeakOrdering<HBHERecHit> >      "hbherecoPedestal"      ""        "USER"
edm::SortedCollection<HFRecHit,edm::StrictWeakOrdering<HFRecHit> >          "hfrecoPedestal"        ""        "USER"
edm::SortedCollection<HORecHit,edm::StrictWeakOrdering<HORecHit> >          "horecoPedestal"        ""        "USER"
vector<L1MuGMTCand>                                                         "gtDigisAlCaPedestal"   ""        "USER"
vector<L1MuRegionalCand>                                                    "gtDigisAlCaPedestal"   "CSC"     "USER"
vector<L1MuRegionalCand>                                                    "gtDigisAlCaPedestal"   "DT"      "USER"
vector<L1MuRegionalCand>                                                    "gtDigisAlCaPedestal"   "RPCb"    "USER"
vector<L1MuRegionalCand>                                                    "gtDigisAlCaPedestal"   "RPCf"    "USER"
````

consistently with the output commands

````
'keep *_gtDigisAlCaPedestal_*_*',
'keep HBHERecHitsSorted_hbherecoPedestal_*_*',
'keep HORecHitsSorted_horecoPedestal_*_*',
'keep HFRecHitsSorted_hfrecoPedestal_*_*'
````

## Event size

Total average uncompressed size: ~250 kB/event
Total average compressed size:  ~72 kB/event

````
File ALCARECOHcalCalPedestal.root Events 16393
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event)
HBHERecHitsSorted_hbherecoPedestal__USER. 163869 54901.9
HORecHitsSorted_horecoPedestal__USER. 42702.7 14115.7
HFRecHitsSorted_hfrecoPedestal__USER. 13763.2 2229.53
EventAuxiliary 134.97 35.4452
L1GlobalTriggerReadoutRecord_gtDigisAlCaPedestal__USER. 78.4958 9.7785
L1MuGMTReadoutCollection_gtDigisAlCaPedestal__USER. 28.3514 8.66907
L1MuRegionalCands_gtDigisAlCaPedestal_RPCb_USER. 22.244 8.52626
L1MuRegionalCands_gtDigisAlCaPedestal_RPCf_USER. 22.244 8.52626
L1MuRegionalCands_gtDigisAlCaPedestal_CSC_USER. 22.2081 8.47295
L1MuRegionalCands_gtDigisAlCaPedestal_DT_USER. 22.1723 8.45452
L1MuGMTCands_gtDigisAlCaPedestal__USER. 21.92 8.16727
EventProductProvenance 130.113 7.39175
EventSelections 74.9883 6.19795
BranchListIndexes 20.0239 4.52949
````

## Data rate

@kodolova please comment further, based on the expected rate for your stream and PD.

**Comment by diguida** [comment]
adding the test file, in order to reproduce the test.

**Comment by diguida** [comment]
@cmsbuild please notice the change.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
