### PR TITLE
Provide direct access to multiple fine-grain bits in HCAL TP (80X)

### PR DESCRIPTION
**Pull request by matz-e**
Expand the most common TP access method to allow querying multiple FG bits.

Backport of #15970.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@matz-e , how important this  PR for 8_0?

**Comment by matz-e** [comment]
I keep getting asked how to access the fg bits by people using 80x. This would make that a bit more obvious. If you don't want it in,  no problem from my side.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
