### PR TITLE
[HeaderCheck][ANALYSIS] Cleanup headers to avoid header inconsistency errors

### PR DESCRIPTION
**Pull request by smuzaffar**
- Removed unused header files
- Drop ElectroWeakAnalysis/ZMuMu/src and ElectroWeakAnalysis/ZMuMu/interface
  - All ElectroWeakAnalysis/ZMuMu/src/*.cc code is commented and no one uses any header from ElectroWeakAnalysis/ZMuMu/interface

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@santocch could you please check this PR? Not sure whether this code is used outside CMSSW?

**Comment by santocch** [comment]
+1

- no evidence anywhere this is still used... no python file in github use any of the class deleted.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
