### PR TITLE
 [14_2_X backport] MTD geometry: Fix MTDGeometryBuilder text to avoid rounding issues with alternative architectures

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Exact backport to CMSSW_14_2_X of https://github.com/cms-sw/cmssw/pull/46761 . It requires https://github.com/cms-data/Geometry-TestReference/pull/17

#### PR validation:

Code was developed and tested on 14_2_X, moved to 15_0_X during PR test.

### CODE REVIEW

**Comment by fabiocos** [comment]
type bugfix

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/17

**Comment by civanch** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by fabiocos** [comment]
@mandrenguyen @smuzaffar in order to let this work in 14_2_X you need to merge there also the external data https://github.com/cms-data/Geometry-TestReference/pull/17

**Comment by smuzaffar** [comment]
Ok , I have opened https://github.com/cms-sw/cmsdist/pull/9553 for 14.2.X

**Pull request merged**
