### PR TITLE
Replace vstring with VInputTag in edmtest::AddIntsProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Title says it all. I want to use product instance labels for `AddIntsProducer` input.

#### PR validation:

Framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Segfault in
```
#3  0x00002acab5296d89 in sig_dostack_then_abort () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002acad3217535 in TIDRing::computeCrossings(TrajectoryStateOnSurface const&, PropagationDirection) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libRecoTrackerTkDetLayers.so
#6  0x00002acad3217c5c in TIDRing::groupedCompatibleDetsV(TrajectoryStateOnSurface const&, Propagator const&, MeasurementEstimator const&, std::vector<DetGroup, std::allocator<DetGroup> >&) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libRecoTrackerTkDetLayers.so
#7  0x00002acad3216ac5 in TIDLayer::groupedCompatibleDetsV(TrajectoryStateOnSurface const&, Propagator const&, MeasurementEstimator const&, std::vector<DetGroup, std::allocator<DetGroup> >&) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libRecoTrackerTkDetLayers.so
#8  0x00002acacb30fce4 in GeometricSearchDet::compatibleDetsV(TrajectoryStateOnSurface const&, Propagator const&, MeasurementEstimator const&, std::vector<std::pair<GeomDet const*, TrajectoryStateOnSurface>, std::allocator<std::pair<GeomDet const*, TrajectoryStateOnSurface> > >&) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libTrackingToolsDetLayers.so
#9  0x00002acacb30fc7d in GeometricSearchDet::compatibleDets(TrajectoryStateOnSurface const&, Propagator const&, MeasurementEstimator const&) const () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libTrackingToolsDetLayers.so
#10 0x00002acadde137c1 in fastsim::TrackerSimHitProducer::interact(fastsim::Particle&, fastsim::SimplifiedGeometry const&, std::vector<std::unique_ptr<fastsim::Particle, std::default_delete<fastsim::Particle> >, std::allocator<std::unique_ptr<fastsim::Particle, std::default_delete<fastsim::Particle> > > >&, RandomEngineAndDistribution const&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/pluginFastSimulationSimplifiedGeometryPropagatorAuto.so
#11 0x00002acadddf0eb9 in FastSimProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/pluginFastSimulationSimplifiedGeometryPropagatorAuto.so
#12 0x00002acaa60d12e6 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetupImpl const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-08-25-1100/lib/slc7_amd64_gcc820/libFWCoreFramework.so
```
I don't see how this PR could have caused that.

**Comment by makortel** [comment]
Apparently there were random crashes in 2018 https://github.com/cms-sw/cmssw/issues/24051

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
