### PR TITLE
Make the HLT vertex filters robust to L3Muon duplicates - 94X backport

### PR DESCRIPTION
**Pull request by aboletti**
Backport of   #21331 

Two HLT filters, used in some BPH HLT paths, has been updated to be robust to the presence of duplicates in the L3Muon collection.

The changes affect the part of the code that selects the 2 muons and 1 (2) track(s) matched with the three (four) tracks used to build the vertex.
They include:
- veto to the selection of two identical muons
- reduction of the exception message to the cases in which not enough matching muons/tracks are found

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by franzoni** [comment]
https://github.com/cms-sw/cmssw/pull/21331#issuecomment-345343261

Hello @aboletti , can you address the same comments as received to https://github.com/cms-sw/cmssw/pull/21331

**Comment by franzoni** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
