### PR TITLE
MTD Validation: add selection on vxt Ndof>4 in Primary4DVertexValidation 

### PR DESCRIPTION
**Pull request by kdeleo**
#### PR description:

As suggested by @werdmann, the selection on the ndof had been added in the ```Primary4DVertexValidation```, furthermore we have fixed the filling of the number of vertices vs PU histograms, which was wrongly made on vertex and not on event basis.

#### PR validation:

The PR has been tested on workflow on TTbar14TeV+PU200 producing the expected effect

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@ctarricone FYI

**Comment by fabiocos** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- changes in [12434.7](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-13-1100+f74a5f/58856/12434.7_TTbar_14TeV+2023_trackingMkFit) are spurious
- changes in phase2 [24834.911](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-09-13-1100+f74a5f/58856/24834.911_TTbar_14TeV+2026D98_DD4hep) MTD plots as expected

**Comment by rappoccio** [comment]
+1

**Pull request merged**
