### PR TITLE
Update L1TdeStage2uGT_cfi.py

### PR DESCRIPTION
**Pull request by apana**
Update list of algorithms that need to be blacklisted.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@apana form my understanding, in which test on which data one is supposed to observe an effect from this change?

**Comment by thomreis** [comment]
Hi @fabiocos 
for example the non-centraBX histograms here https://goo.gl/JaaWt2 should get less entries.
The emulator does not handle certain multi BX algos correctly and that leads to data vs. emulator mismatches. The initial list of blacklisted algos was made with the v0.0.1 L1 menu, while the v1.0.0 has added additional multi BX algos.

**Comment by fabiocos** [comment]
@thomreis thanks, my question is: was this verified? Should we see it for instance by checking workflow 136.855?

**Comment by fabiocos** [comment]
+1

**Comment by thomreis** [comment]
Since this is mainly used in the online DQM it is checked in the online playback system before deployment. It could also be verified in the offline workflows as long as there are enough events.

**Pull request merged**
