### PR TITLE
Updating EGM HLT supercluster regression tags for Run 3 in MC

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Follow-up to https://github.com/cms-sw/cmssw/pull/37491 

Request to update tags is in
https://cms-talk.web.cern.ch/t/mc-gt-updating-egm-hlt-supercluster-regression-tags-for-run-3-in-mc/9343

Adding the EGM HLT supercluster regression tags for Run 3 in MC:
 * 123X_mcRun3_2021_design_v14
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v13/123X_mcRun3_2021_design_v14
 * 123X_mcRun3_2021_realistic_v14
  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v13/123X_mcRun3_2021_realistic_v14
 * 123X_mcRun3_2021cosmics_realistic_deco_v14
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v13/123X_mcRun3_2021cosmics_realistic_deco_v14
 * 123X_mcRun3_2021_realistic_HI_v14
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v13/123X_mcRun3_2021_realistic_HI_v14
 * 123X_mcRun3_2023_realistic_v14
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v13/123X_mcRun3_2023_realistic_v14
 * 123X_mcRun3_2024_realistic_v15
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v13/123X_mcRun3_2024_realistic_v15
 * 123X_mcRun4_realistic_v11
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun4_realistic_v10/123X_mcRun4_realistic_v11

Diffs in the tags are according to the request:
```
Tag: pfscecal_EBCorrection_online_Run3_120X_v1_mc
Rcd: GBRDWrapperRcd
Label: pfscecal_EBCorrection_online

Tag: pfscecal_EECorrection_online_Run3_120X_v1_mc
Rcd: GBRDWrapperRcd
Label: pfscecal_EECorrection_online

Tag: pfscecal_EBUncertainty_online_Run3_120X_v1_mc
Rcd: GBRDWrapperRcd
Label: pfscecal_EBUncertainty_online

Tag: pfscecal_EEUncertainty_online_Run3_120X_v1_mc
Rcd: GBRDWrapperRcd
Label: pfscecal_EEUncertainty_online
```

#### PR validation:

test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport to 12_3_X is expected

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
assign hlt

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by missirol** [comment]
@tvami , to follow the strategy proposed by EGM, the flag also needs to be updated here:
https://github.com/cms-sw/cmssw/blob/3663ce41cc7502b1f716ea52c9b1c6d996343ddc/RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc#L70

**Comment by tvami** [comment]
Hi @missirol following up on our conversation in https://github.com/cms-sw/cmssw/pull/37557#issuecomment-1100293458
you are suggesting to have custom commands when Run-2 data is used. But my argument about MC production would maybe  go in the direction that custom commands should be used to Run-3 instead.

Let me actually ask this about MC, because it's still not clear to me. If somebody wants to simulate Run-2 MC in 12_4_X now, and they'll go through the `HLT` step in their simulations, then by using https://github.com/cms-sw/cmssw/pull/37588/commits/9548c78993edea69b8a619e99ee2f057ac153d91 they'll assume that that the Run-2 GT has conditions that are trained with PS, right? But that's not the case, given what the payloads in this PR were created only for Run-3 alone. Is the answer to this just that that a given CMSSW should be used for a given year, and so never use 12_4_X for Run-2 simulations (unless it's the TSG and they know what they are doing)

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
> @tvami , to follow the strategy proposed by EGM, the flag also needs to be updated here:
> 
> https://github.com/cms-sw/cmssw/blob/3663ce41cc7502b1f716ea52c9b1c6d996343ddc/RecoEcal/EgammaClusterAlgos/src/SCEnergyCorrectorSemiParm.cc#L70

Thanks, I changed that in https://github.com/cms-sw/cmssw/pull/37588/commits/a2c4db2b5dee253475b1a970b58696729b3bb98c

I can squash the commits into one after we agreed that changing the flag in the cpp is indeed the best way forward (as opposed to doing it in the HLT menu)

**Comment by missirol** [comment]
> Let me actually ask this about MC, because it's still not clear to me. If somebody wants to simulate Run-2 MC in 12_4_X now, and they'll go through the `HLT` step in their simulations, then by using [9548c78](https://github.com/cms-sw/cmssw/commit/9548c78993edea69b8a619e99ee2f057ac153d91) they'll assume that that the Run-2 GT has conditions that are trained with PS, right? But that's not the case, given what the payloads in this PR were created only for Run-3 alone. Is the answer to this just that that a given CMSSW should be used for a given year, and so never use 12_4_X for Run-2 simulations (unless it's the TSG and they know what they are doing)

For what concerns the HLT step, I would say 'yes, that is the answer' (others like Martin and Silvio can probably give you a better answer since they have more experience than me). That's indicated by the fact that, in recent releases, we are basically not running the HLT in RelVal wfs that are not for Run 3 (we run Fake menus). Another loosely-related example (that's before my time, though), is what was done for Run-2 UL MCs where the simulation+reconstruction was in 10_6_X for all years, but the HLT step was simulated alone in the same release cycle that had been used for any given data-taking year (`8_X` for UL16, `9_X` for UL17, `10_X` for UL18).

PS. In case you are wondering about Phase 2, that's a special case (under development).

**Comment by tvami** [comment]
The failed unit test doesnt seem to be connected to this PR:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b85a3e/23960/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-l1tstage2_dqm_sourceclient/testing.log

**Comment by tvami** [comment]
> The failed unit test doesnt seem to be connected to this PR: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b85a3e/23960/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-l1tstage2_dqm_sourceclient/testing.log

Yes, known issue:
https://github.com/cms-sw/cmssw/issues/37584

**Comment by tvami** [comment]
Anyway, I think the changes are mostly expected, I see changes in HLT / EGM folders. One question tho: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-15-1100+b85a3e/49643/11634.914_TTbar_14TeV+2021_DDDDB+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/JetMET_MET.html

is the MET expected to be changed?  @swagata87

**Comment by swagata87** [comment]
> Anyway, I think the changes are mostly expected, I see changes in HLT / EGM folders. One question tho: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-15-1100+b85a3e/49643/11634.914_TTbar_14TeV+2021_DDDDB+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/JetMET_MET.html
> 
> is the MET expected to be changed? @swagata87

HLT MET, right? 
even then, I'm surprised to see changes in caloMET! 
As far as I know, in HLT the CaloMETProducer just uses CaloTowers to calculate MET, and it should have nothing to do with the HLT supercluster regression! For caloMet I see that among 88 comparisons 2 has failed. Is there any way to know which 2? Or is there any link to plots for these 2 comparisons? 

About PFMET, it's better to ask JET/MET experts. As far as I know, jet/met HLT runs the `PFProducer` (hltParticleFlow) configured in a special way. They had put `useEGammaFilters= False` and `useEGammaElectrons = False`. To the best of my knowledge, this should mean that egamma supercluster regression should have zero effect on PF jet/MET.

**Comment by missirol** [comment]
I cannot see any difference reported for MET distributions. The fact is that many of these MET folders in the DQM outputs contain a plot of the overall HLT results (a.k.a. "triggerResults"), and it's that one which shows differences (which is expected, as it includes counts of EGM triggers):
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-15-1100+b85a3e/49643/11634.914_TTbar_14TeV+2021_DDDDB+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/JetMET__MET_pfMet_Cleaned_triggerResults.png

**Comment by swagata87** [comment]
> I cannot see any difference reported for MET distributions. The fact is that many of these MET folders in the DQM outputs contain a plot of the overall HLT results (a.k.a. "triggerResults"), and it's that one which shows differences (which is expected, as it includes counts of EGM triggers): https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-15-1100+b85a3e/49643/11634.914_TTbar_14TeV+2021_DDDDB+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/JetMET__MET_pfMet_Cleaned_triggerResults.png

thank you Marino, for clarifying this. 
then it is understood now..

**Comment by tvami** [comment]
urgent
 * this should go into pre3 so that the condition change goes through a release validation

**Comment by tvami** [comment]
`TestDQMOnlineClient-l1tstage2_dqm_sourceclient` issues are still not resolved, so @cms-sw/hlt-l2 @cms-sw/reconstruction-l2 please consider signing this w the tests results in https://github.com/cms-sw/cmssw/pull/37588#issuecomment-1100479906

**Comment by malbouis** [comment]
+alca

- EGM HLT supercluster regression for MC GTs.
- switch of flag in EGM code to True. From now on the PS correction will be included.
- failures in integration tests are understood.

**Comment by missirol** [comment]
+hlt

 - #37606 contains the minimal update to keep TSG recipes correct after this PR is merged (changes/improvements to #37606 will be discussed in TSG with EGM experts, as a follow-up to https://github.com/cms-sw/cmssw/pull/37557#issuecomment-1100380030)

**Comment by clacaputo** [comment]
+reconstruction

- no reco changes expected or observed
- failing unit test not related to this PR https://github.com/cms-sw/cmssw/pull/37588#issuecomment-1100493773

**Comment by qliphy** [comment]
merge

**Pull request merged**
