### PR TITLE
Run3-hcx305 Update some of the cfg's in Validation/HcalHits in view of changes to SD classes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update some of the cfg's in Validation/HcalHits in view of changes to SD classes

#### PR validation:

Tested the cfg's 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not to  be back ported

### CODE REVIEW

**Comment by bsunanda** [comment]
@abdoulline I still have issues running run_HB_cfg.py also HE, HF. The issue is that it looks for edm::HepMCProduct in the input file. Can you take a look in the input files and try to resolve this?

**Comment by abdoulline** [comment]
@bsunanda   
These tests are **very old**, ca CMSSW_3_1_X, not sure they were (ever) used since...
 And the content of these input GEN files (as of 2010) - now I can only guess
(etaphi+-44, +-244,  +- 344  for HB, HE, HF respectively - like pion gun with antiparticle shot at ieta = 4, 24, 34 and iphi = 4, the latter being even - not quite good for HE and HF...)   
And their content may not be compatible with modern CMSSW versions...  
I can _try to remake_ these input files (re-generate input GEN files, then if OK - commit the changes) _after_ this PR is meged ?

**Comment by abdoulline** [comment]
@bsunanda 
Alternatively - we can replace input files with the particle energy (50 GeV) gun.  It should work right away?

**Comment by perrotta** [comment]
@abdoulline what about removing those tests at all, if not needed any more?
All code in the release need effort to maintain and keep it up to date, as in this case, and whatever is not going to be used any more by anyone should be better removed.

**Comment by abdoulline** [comment]
@perrotta Andrea,  
fine with me, but this (removing something from Validation/HcalHits ) needs Sunanda's agreement, I believe.

**Comment by abdoulline** [comment]
@bsunanda   
I've found old MC generaton configs (served for generation of the input files in question)  in my archives and updated them for producing the same files in 12_X [*]
Now run_HB_cfg.py (and _HE, _HF) runs OK with your PR.

---------------------------------------------------------------------
[*]
E.g. in run_HB_cfg.py  to be replaced  3_1_X  -> 12_X in the fileNames:

(i)
https://github.com/cms-sw/cmssw/blob/7be998cafd127d362e174170d6d2de8fac91a198/Validation/HcalHits/test/run_HB_cfg.py#L41

with

(ii) 
      fileNames = cms.untracked.vstring('file:/afs/cern.ch/cms/data/CMSSW/Validation/HcalHits/data/12_X/mc_pi50_etaphi-+44.root')

**Comment by bsunanda** [comment]
@abdoulline Thanks for all this. Please suggest what will be the final line - replace the file or modify the cfg's?

**Comment by abdoulline** [comment]
@bsunanda 
I'd suggest to modify (in all three configs in question) a few symbols in the fileNames 
"3_1_X"  -> "12_X"    
to use updated files from new directory.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
