### PR TITLE
xrange migration in fwk packages for python3

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

at least one unit test in my python3 fwk test fails due to the use of xrange (now range in python3). Migrate using

futurize -f libfuturize.fixes.fix_xrange_with_import -w --no-diffs -n .

(the fwk packages so far)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26410	885a056
- technical 
- jenkins tests pass

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@santocch please check, it looks ok to me, I will move forward with the integration

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
