### PR TITLE
Phase2-hgx316BBB Investigate the differences between ddd and dd4hep versions in HGCal V17 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Investigate the differences between ddd and dd4hep versions in HGCal V17 geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by qliphy** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@srimanob Can you please sign this urgently?

**Comment by srimanob** [comment]
Hi @bsunanda 

Could you please clarify the result of this PR? Does it make the result from DDD and DD4hep consistent? 
Any study, or presentation? I can't interpret from the PR description. Thanks.

**Comment by bsunanda** [comment]
The algorithms provide identical results. Fireworks do not show any overlaps - but the G4 tool shows inconsistencies. Anyway, the tools in this PR are good. I can make a presentation in some SIM meetings about our findings.

**Comment by bsunanda** [comment]
@srimanob Please sign this. Our investigation using the changes in this PR revealed that the algorithms in DDD and DD4hep provide identical volume parameters and translation matrix (there is no rotation here).

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
