### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/35215).

In many cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

In one place, a missing include has been added to not cause a false positive in my BuildFile checker.

This PR cleans unnecessary includes from CMSSW BuildFiles that were recently added for 12_1_0_pre4.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by tvami** [comment]
+alca

**Comment by alja** [comment]
+1

**Comment by SiewYan** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35701	a8feafd 
- code changes are technical; apparently quite a few updates in the reco packages are cleaning up the dependencies after a few of the relatively recent esConsumes and related PRs
- jenkins tests pass

**Pull request merged**
