### PR TITLE
include hcalRecAlgos ES producer in cosmic workflow [84X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #17782

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
```
The release you are using, "CMSSW_8_4_0_patch1" , predates
a release ("CMSSW_9_0_0_pre4") used in writing the input file, root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_0_0_pre4/RelValMinBias_13/GEN-SIM/90X_mcRun2_asymptotic_v1-v1/10000/020D6CED-73EA-E611-8ED3-0025905B855A.root.
Forward compatibility cannot be supported.

```

@Dr15Jones it looks like we need some fix here from the framework side

**Comment by davidlange6** [comment]
I don't think there is a "problem" to fix.

**Comment by slava77** [comment]
On 3/7/17 2:53 AM, David Lange wrote:
> I don't think there is a "problem" to fix.
> 

Just to understand more clearly:
we will not allow reading 900pre4 files (830-equivalent)
in 84X releases.
Correct?

**Comment by davidlange6** [comment]
I don't think we should change the fwk to allow it,  no (but that said, the short matrix ran when I built 840 and 840patch1, so perhaps the check is not as reliable as it should be:) )

anyway, 840 is a hack for mwgr2/3

**Comment by perrotta** [comment]
+1
In CMSSW_8_4_X the same crash observed in cosmic workflows in 90X and 91X does not (yet) shows up,
However, the HcalRecAlgos are included in the 84X cosmics configs only through some of the otherwise redundant AlCa steps in these workflows, as pointed out by @kpedro88 in https://github.com/cms-sw/cmssw/pull/17782#issuecomment-284450944 . 
Therefore, this PR which correctly includes HcalRecAlgos in the RecoLocalCalo_Cosmics config is needed for robustness (at least).

**Pull request merged**
