### PR TITLE
update of `HLTriggerJSONMonitoring` for `DatasetPath`s

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is an attempt to update the plugin `HLTriggerJSONMonitoring` to take into account the existence of the so-called `DatasetPath`s in Run-3 HLT menus.

_Context_ :
`DatasetPath` is HLT jargon for what is a normal `cms.Path` that selects events based on the results of other `cms.Path`s (which, most commonly, correspond to physics triggers).

In the Run-3 HLT menus, `DatasetPath`s effectively provide the definition of Primary Datasets. A `DatasetPath` can have its own prescales (PD-level prescales), as well as "smart"-prescales for its triggers (where a "smart-prescale" is a prescale that applies to a given trigger-path only for a specific PD, and not for others; smart-prescales in `DatasetPath`s are applied via a `TriggerResultsFilter` module).

`HLTriggerJSONMonitoring` currently does not know about `DatasetPath`s, and reports as PD counts the counts of the OR of the relevant triggers. This means that PD-level prescales and smart-prescales are ignored in the counts reported for each PD by this plugin. As a consequence, this can lead to OMS reporting inaccurate PD rates.

_Implementation_ :
If a `DatasetPath` (e.g. `Dataset_X`) exists in the configuration, `HLTriggerJSONMonitoring` now assigns only the Path `Dataset_X` to PD `X`, and does not include the `DatasetPath` in the standard list of trigger paths (see https://github.com/cms-sw/cmssw/pull/38418#issuecomment-1159760327). Otherwise, the current behaviour applies (which I think relies on the PSet `datasets`).

_Comments_ :
This update is meant to be backward-compatible (no changes if used with older menus, improved outputs for current menus).
This (or a similar update) will need to be backported to `12_4_X`, and possibly `12_3_X`.

In addition
 - the default value of 1 InputTag in `fillDescriptions` is changed to use `@currentProcess` instead of `HLT` as process name;
 - a simple unit-test for `HLTriggerJSONMonitoring` is added in `test/` (the unit test is a mock-up HLT menu, and maybe it could be simplified further; right now, it tests more than just `HLTriggerJSONMonitoring`).

Tagging @fwyzard and @Sam-Harper , so they can review.

#### PR validation:

The outputs of the new unit test are as expected.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by fwyzard** [comment]
👍 

On top of these changes, I would suggest to drop the dataset paths from the list of paths in the output.
This way we avoid the duplicate information in OMS etc.

By the way ... it's clearly late for 2022, but maybe for next year we could rename the "stream paths" to Stream_Name, following the same convention ?

**Comment by missirol** [comment]
> On top of these changes, I would suggest to drop the dataset paths from the list of paths in the output. This way we avoid the duplicate information in OMS etc.

Okay, will do (I was wondering if it would have been better to keep the plugin agnostic to this, and ask OMS to omit `DatasetPaths` in certain tables, but I don't have a strong preference).
 
> By the way ... it's clearly late for 2022, but maybe for next year we could rename the "stream paths" to Stream_Name, following the same convention ?

Sounds good to me (iiuc, these are the current FinalPaths named `*Output`), but I don't really know how much work this is inside `ConfDB`.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Realised that some comments inside the plugin needed to be updated.

Took the opportunity to improve a bit the unit test, basically copying from [testLogMonitorFilter](https://github.com/cms-sw/cmssw/blob/d564ee31b404beab30efddf14d6891160749cdc4/HLTrigger/special/test/testLogMonitorFilter.sh) by Chris Jones.

I think the PR is now ready on my side.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
I tested the PR with a real HLT menu, and, as far as I can tell, the `json` outputs are as expected (with and without `DatasetPath`s)

Unless anybody has further comments, I'll sign the PR tomorrow (and open the backports).

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
