### PR TITLE
Fix EventSetupIncorrectConsumes test

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

The `EventSetupIncorrectConsumes` test succeeds if the configuration the test runs fails. The job was failing (i.e. test succeeding), but for wrong reason: the configuration did not exist. This PR adds a configuration that tests the functionality properly, i.e. that an exception is thrown if `esConsumes()` is called outside of the EDModule constructor. Thanks to @Dr15Jones for finding this out. The test is also improved to fail if the job fails in a different way.

The second commit removes some `noexcept` specifiers to allow the exception from `esConsumes()` to propagate through `EDConsumerBaseAdaptor` classes.

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by Dr15Jones** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
