### PR TITLE
added esConsumes to modules in SimMuon/GEMDigitizer

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 6 modules
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
@kpedro88 ping

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
