### PR TITLE
limit the number of seeds, same as in CkfTrackCandidateMakerBase

### PR DESCRIPTION
**Pull request by slava77**
this is a follow up to https://cms-talk.web.cern.ch/t/high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met/13471/5

this PR introduces a limit on the number of seeds acceptable for mkFit processing at 500K (same as in CkfTrackCandidateMakerBase)

In the problematic event of the MET PD there were 2969225 seeds in the pixelLess iteration

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cms-sw/tracking-pog-l2 FYI, let us know if you have any concerns about this.

**Comment by mmusich** [comment]
@jpata 

> let us know if you have any concerns about this.

from a quick look, this would be equivalent to what is done for CKF here: 

https://github.com/cms-sw/cmssw/blob/bb2e40ea7870ee15e549388c95ce380846336b95/RecoTracker/CkfPattern/src/CkfTrackCandidateMakerBase.cc#L567

and here: 

https://github.com/cms-sw/cmssw/blob/bb2e40ea7870ee15e549388c95ce380846336b95/RecoTracker/CkfPattern/src/CkfTrackCandidateMakerBase.cc#L193-L204

so this should reproduce the *status quo ante* mkFit.
No particular objections on my side.

**Comment by clacaputo** [comment]
+reconstruction

- follow up to [high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met](https://cms-talk.web.cern.ch/t/high-memory-usage-in-reco-job-for-workflow-promptreco-run356323-met/13471/5)
- max number of seeds in MkFit limited as in `CkfTrackCandidateMakerBase`

**Comment by qliphy** [comment]
+1

**Pull request merged**
