### PR TITLE
[GENERATORS] Apply code-checks/format with misc-definitions-in-headers

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by agrohsje** [comment]
Hi @smuzaffar . Should I ignore the 2 errors here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-417dcd/15813/summary.html ?

**Comment by qliphy** [comment]
@agrohsje   You can ignore the error messages, which are from other files not touched by this PR.

"Duplicate Dictionaries" is from https://github.com/cms-sw/cmssw/pull/33978/ and being fixed.

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
