### PR TITLE
clean up SiPixel digitizer and clusterizer code removing variables used for pre-phase2 TDR studies

### PR DESCRIPTION
**Pull request by emiglior**
This PR is some extra clean-up of PR #24325 and #24329.
In this PR we remove few parameters of the pixel digitizer and of the clusterizer (featuring "Stack" in the name of the variable) which were introduced long time ago in the code of the current pixel detector (phase1 pixel TDR epoch?) for preliminary studies on phase2 tracker and not are used anymore.

Additional details can be found in 
https://hypernews.cern.ch/HyperNews/CMS/get/pixelOfflineSW/1433.html

People following these developments are : @avartak @suchandradutta @kpedro88 
 @mmusich @tsusa

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- In the current default and all used configs the removed feature is never used
  -  In the digitiizer  theAdcFullScaleStack==theAdcFullScale in the default and all used configs -> never used
  - In the clusterizer theStackADC == maxADC8bitVal_ == 255 -> never used
-  From https://hypernews.cern.ch/HyperNews/CMS/get/pixelOfflineSW/1433/2.html :
   - In the digitiizer the “stack” stuff is only used for something called “P20TB” which must be a Phase2 component
   - In the clusterizer the first layer “stack” is used is layer 5, which cannot have anything to do with the present phase1 detector
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
