### PR TITLE
add DQM Validation plots for MSSM Hbb Trigger Paths. 

### PR DESCRIPTION
**Pull request by heppye**
add DQM Validation plots for MSSM Hbb Trigger Paths.

### CODE REVIEW

**Comment by heppye** [comment]
this PR have been checked by STEAM experts already. Information could be found at https://its.cern.ch/jira/browse/CMSHLT-470. Please process if possible.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
@cmsbuild new commits here

**Comment by deguio** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by heppye** [comment]
@davidlange6 , could the PR be merged now?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
