### PR TITLE
Run3-gex109A Avoid some compilation warnings in Validation codes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid some compilation warnings in Validation codes (CaloTowers, EcalClusters, EcalDigis, EcalHits)

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by bsunanda** [comment]
@jfernan2 Could you approve it again! Somehow the earlier approval was not registered correctly

**Comment by perrotta** [comment]
+1

**Pull request merged**
