### PR TITLE
Adding XeXe, fixed PbPb, and 5 TeV pp (2017) placeholder

### PR DESCRIPTION
**Pull request by gsfs**
Backport of PR #21833.
These changes are already in CMSSW_9_3_X being used for XeXe MC

### CODE REVIEW

**Comment by civanch** [comment]
@gsfs , @franzoni, @fabiocos, others,  is it a good idea to change the name when IP parameters are fixed?

**Comment by gsfs** [comment]
We wanted to make sure people were clear about which version of the beam spot they were using. The older name was already used for a large body of existing MC samples. Having new samples with a shifted beam spot but the same beam spot name did not seem like a good idea. Note that the old name is commented out so that it will not be used by mistake.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
