### PR TITLE
WIP: New DQM GUI based on files

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This PR brings the new DQM GUI to CMSSW. The code is already at a working state but a lot of work still needs to be done.

The main purpose of this PR right now is to test it in P5.

#### PR validation:

PR was validated locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by silviodonato** [comment]
I see 168 commits, I would suggest to squash the commits when the PR is ready

**Comment by perrotta** [comment]
@andrius-k @cms-sw/dqm-l2 can this PR get closed? As such it cannot even get tested at P5...

**Comment by emanueleusai** [comment]
This is so old it wouldn't even show up in our DQM PR tracker. Yes we can close this.
The new DQM GUI is in a separate github repo.
I was not in DQM at the time, so I'm not sure what was the reasoning behind including the GUI's code in CMSSW...

**Comment by perrotta** [comment]
> This is so old it wouldn't even show up in our DQM PR tracker. Yes we can close this. The new DQM GUI is in a separate github repo. I was not in DQM at the time, so I'm not sure what was the reasoning behind including the GUI's code in CMSSW...

Thank you @emanueleusai 
Let close this, then.
If someone is interested in retrieving it, the closed PR can still get accessed

**Pull request closed without merging**
