### PR TITLE
add clang-format file to CMSSW

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

adds .clang-format to CMSSW (see #26082 for some history)

#### PR validation:

has no effect yet.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@davidlange6 @smuzaffar as we are not enforcing yet clang-format, the addition of the agreed instruction should be ineffective, and the failure in the addOn test unrelated. I am rerunning the tests, and for instance fastsim1 now succeed. I agree in merging this PR to let the migration work start

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
a standalone run of addOn tests is ok.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar is this finally ok for you?

**Comment by smuzaffar** [comment]
+core

**Pull request merged**
