### PR TITLE
Add Frontier digital signature test workflows for Matrix IB tests

### PR DESCRIPTION
**Pull request by hengne**
Add Frontier digital signature test workflows for Matrix IB tests:

 test workflows added:

```
Run1 data:
workflows[5504.72] = ['',['RunMu2012D_DigiSigTest','HLTD_DigiSigTest','RECODR1reHLT_DigiSigTest','HARVESTDR1reHLT_DigiSigTest']]
workflows[5504.76] = ['',['ZMuSkim2012D_DigiSigTest','HLTDSKIM_DigiSigTest','RECODR1reHLT_DigiSigTest','HARVESTDR1reHLT_DigiSigTest']]

Run1 HIN:
workflows[550140.53] = ['',['RunHI2011_DigiSigTest','RECOHID11_DigiSigTest','HARVESTDHI_DigiSigTest']]

Run1 fullSim:
workflows[55030] = ['', ['ZMM_DigiSigTest','DIGI_DigiSigTest','RECO_DigiSigTest','HARVEST_DigiSigTest']]

Run2 Data:
workflows[550134.903] = ['',['RunDoubleMuon2015D_DigiSigTest','HLTDR2_25ns_DigiSigTest','RECODR2_25nsreHLT_DigiSigTest','HARVESTDR2_25nsreHLT_DigiSigTest']]
workflows[550134.908] = ['',['RunSingleMuPrpt2015D_DigiSigTest','HLTDR2_25ns_DigiSigTest','RECODR2_25nsreHLT_DigiSigTest','HARVESTDR2_25nsreHLT_DigiSigTest']]

Run2 fullSim:
workflows[5501329] = ['', ['ZEE_13_DigiSigTest','DIGIUP15_DigiSigTest','RECOUP15_DigiSigTest','HARVESTUP15_DigiSigTest']]

Run2 fastSim:
workflows[550135.4] = ['ZEE_13', ['ZEEFS_13_DigiSigTest','HARVESTUP15FS_DigiSigTest','MINIAODMCUP15FS_DigiSigTest']]


2017 upgrade fullSim:

11425.0 ZEE_13TeV_TuneCUETP8M1_2017DigiSigTest_GenSimFullDigiSigTest+DigiFullDigiSigTest_2017DigiSigTest+RecoFullDigiSigTest_2017DigiSigTest+HARVESTFullDigiSigTest_2017DigiSigTest


```

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
@hengne - as this doesn't merge now , I'm closing - we should come back to this PR when you have a moment to reimplement...

**Comment by DrDaveD** [comment]
So since this is closed, is there something still tracking the issue to make sure it doesn't get forgotten?  Is there for example a github issue?  I can't find one.

**Pull request closed without merging**
