### PR TITLE
Silent getSiThickness::InvalidSiliconDetid

### PR DESCRIPTION
**Pull request by rovere**
Forward port of #20659

### CODE REVIEW

**Comment by rovere** [comment]
Address #20658

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20660	dcd7d18 
- silenced pretty noisy LogError (previously issued in apparently inappropriate way)
- jenkins tests pass and comparisons with baseline show no differences
    - despite ```No significant changes to the logs found``` in the jenkins report,  wf 20034 had 276 error messages in the baseline which are now gone

#20658 can be closed once this is merged

**Comment by davidlange6** [comment]
+1


On 27 Sep 2017, at 19:18, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


This pull request is fully signed and it will be integrated in one of the next master IBs (tests are also fine). This pull request will now be reviewed by the release team before it's merged. @davidlange6<https://github.com/davidlange6>, @slava77<https://github.com/slava77>, @smuzaffar<https://github.com/smuzaffar> (and backports should be raised in the release meeting by the corresponding L2)

**Pull request merged**
