### PR TITLE
Migrate module configuration in RecoPixelVertexing to use default cfipython

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. (The previous PRs : #33207, #33307, #33352, #33543, #33563, #33671, #34007, #34091, #34009, #34155, #34371, #34480, #34543, #34571 )
 
In this PR, 1 file changed.  
        modified:   RecoPixelVertexing/PixelLowPtUtilities/python/AllPixelTracks_cfi.py

Update
- Replace explicit configuration with a reference from cfipython/. (migrating EDProducer("type", .. -> typeDefaylt.clone() ) 
- Remove the type specifications already presented in cfipython/fillDescriptions reference for improved syntax safety.

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_0_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

the test failures are not related to this PR, let's try again

**Comment by jpata** [comment]
+reconstruction
- technical, no changes expected/observed

**Comment by perrotta** [comment]
+1

**Pull request merged**
