### PR TITLE
SimG4Core/Configuration: hardcoded GTs do not age well

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description

Title says it all. I looked at this because of #31143 

#### PR validation:

None. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
The error looks spurious

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
