### PR TITLE
Implement edm::View support for BXVector

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Implement edm::View support for BXVector

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Could you please have a look?
Thanks!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
If you also wanted to support `edm::Ptr` access (an `edm::View` does let one get an `edm::Ptr` for each item in the collection) then you'd follow the example in `edm::OwnVector`

http://cmslxr.fnal.gov/source/DataFormats/Common/interface/OwnVector.h#0536

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Well, if I add that part, I get more than 2000 lines of compiler errors which I do not understand.
The files are at /afs/cern.ch/user/g/gruen/public
There must be something else missing in the implementation of  T for BXVector (T)

**Comment by Dr15Jones** [comment]
@Martin-Grunewald could you make the log containing all the errors available somewhere?

**Comment by Dr15Jones** [comment]
@Martin-Grunewald I see that you did make them available. Guess the coffee hasn't kicked in yet this morning :).

**Comment by Dr15Jones** [comment]
This seems to have done the trick
```C++
  template <class T>
  inline
  void
  setPtr(BXVector<T> const& obj,
         std::type_info const& toType,
         unsigned long index,
         void const*& ptr) {
    obj.setPtr(toType, index, ptr);
  }
  template <class T>
  inline
  void
  fillPtrVector(BXVector<T> const& obj,
                std::type_info const& toType,
                std::vector<unsigned long> const& indices,
                std::vector<void const*>& ptrs) {
    obj.fillPtrVector(toType, indices, ptrs);
  }
namespace edm {
  template <class T>
  struct has_setPtr<BXVector<T> > {
    static bool const value = true;
  };
}
```

I.e. `setPtr` and `fillPtrVector` both need to be in the global namespace. The reason is how functions are found in C++.  If you call `foo( bar ) ` where `bar` is in a namespace, C++ will first look for `foo` in the same namespace as `bar` and if that fails it will look for `foo` in the global namespace. In the example I had you look at, `OwnVector` resides in the `edm` namespace, hence why the two stand alone functions were also in that namespace. But your class resides in the global namespace so the functions need to do that as well.

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Great, thanks a lot! Done in https://github.com/cms-sw/cmssw/pull/13602

**Pull request merged**
