### PR TITLE
getProducerParameterSet

### PR DESCRIPTION
**Pull request by tschuh**
#### PR description:

second getProducerParameterSet function to get ParameterSet of module without Provenance.

#### PR validation:

only build of FWCore/Framework without git cms-checkdeps -a -A

### CODE REVIEW

**Comment by smuzaffar** [comment]
@tschuh , please update the title of this PR

**Comment by makortel** [comment]
@tschuh Could you please explain the motivation for the new overload?

**Comment by tschuh** [comment]
I have no idea how to get the Provenance of an ESProducer. But I was able to figure out process name and the module label.
I needed the configuration of TTStubAlgorithm_official_Phase2TrackerDigi_. Is there a better way to get the ParameterSet of this module?

**Comment by Dr15Jones** [comment]
If you get the data from the EventSetup, you can ask the ESHandle for the `ComponentDescription` which has the `ParameterSetID` for the module which created that data.

**Comment by tschuh** [comment]
I struggle to get the ESProducer. If I do what I naively expect I have to do like:
`void beginRun(const Run& iRun, const EventSetup& iSetup) {
    ESHandle<TTStubAlgorithm<Ref_Phase2TrackerDigi_>> handleTTStubAlgorithm;
    iSetup.get<TTStubAlgorithmRecord>().get(handleTTStubAlgorithm);
}`
I am getting a NoRecord exception during run. I guess the record is not stored in EventSetup. How can I get an ESProducer without record?

**Comment by makortel** [comment]
To get an ESProduct from the EventSetup an ESProducer is needed (+ESSource for the record) in the configuration. From your message I interpret that your job does not have one. Are you then trying to access the ParameterSet of a job that produced the input of your job?

**Comment by tschuh** [comment]
I am working with RelVal samples. They contain TTStubs using a TTStubAlgorithm during production. Unfortunately I need something from the TTStubAlgorithm which has not been stored in the TTStubs. Therefore I am reconstructing the TTStubAlgorithm and I want to ensure that it uses the same configuration as the TTStubAlgorithm during production. Since the configuration has been stored in the samples I am extracting that from there.
I would like to avoid a situation where I have even the possibility to configure something in my EDProudcer in a different way as the RelVal sample producer. We have this already with tracker geometries which is annoying.

**Comment by makortel** [comment]
Could you just include the configuration of the same ESProducer in your job than what was run in the RelVal?

The provenance system is not intended to propagate configuration values from an earlier job to a later job, but to have the ability to  (mostly visually) inspect how a given event has been processed. (of course it can be abused to propagate values, but then you are on your own).

Said that, the inability to propagate configuration fragments is a weakness in our configuration system.

**Comment by tschuh** [comment]
Well, I could load the default release configurations. However, people are playing with this bend window configuration and tracker geometries for example. I can never be sure that for a given relval sample the default config has been used (by purpose or by mistake).

**Comment by makortel** [comment]
So RelVals are being produced with customize functions (or customize commands) altering these parameters?

**Comment by silviodonato** [comment]
@tschuh do you still need this PR?

**Comment by tschuh** [comment]
Ah sorry, got distracted. I use the code from this PR in PR #29151 which seems half approved. So it would be nice, else wise I will likely define the function somewhere else. This seems the correct place for me but I don't mind where it goes.

**Comment by makortel** [comment]
As I mentioned in https://github.com/cms-sw/cmssw/pull/29151#issuecomment-603442561, we do not really like this use of `pset::Registry()` singleton, but its use in #29151 is tolerated because we do not have any better mechanism to cross check if a module is configured in the same way in two separate jobs (issue #29288). We do not, however, endorse such a use of `pset::Registry()`, and therefore this function will, unfortunately, not be accepted inside `FWCore`.

**Comment by makortel** [comment]
-1

**Comment by tschuh** [comment]
Alright, no worries and many thanks for the help so far.

**Pull request closed without merging**
