### PR TITLE
move `PCLMetadataWriter` from `Calibration/TkAlCaRecoProducers` to `CommonTools/ConditionDBWriter`

### LINKED ISSUE #72: Move `PCLMetadataWriter` to `CommonTools`
Move `Calibration/TkAlCaRecoProducers/plugins/PCLMetadataWriter.cc` to `CommonTools`

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-AlCaDB/AlCaTools/issues/72

#### PR description:

Title says it all.
At the beginning of PCL times, all the workflows were for Tracker calibration, so it made sense to put `PCLMetadataWriter` in `Calibration/TkAlCaRecoProducers`. Now, with the proliferation of workflows from other subsystems, it makes sense to push it somewhere more central. I identified `CommonTools/ConditionDBWriter` as a potential candidate.
Profited of the PR to modernize the loops.

#### PR validation:

`cmssw` compiles.
Tested in dry mode: `runTheMatrix.py -l 1001.0,1001.2,1001.3 -j 0`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Calibration/TkAlCaRecoProducers
   * workflow = 1001.2,1001.3

**Comment by tvami** [comment]
+1
 * PR according to the description 
 * test pass

**Comment by tvami** [comment]
@cms-sw/orp-l2 we are essentially fully signed

**Comment by qliphy** [comment]
+1

**Pull request merged**
