### PR TITLE
[81X] Update HCal TP parameters and fixes in 2017 wf

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags 
 
## RunI simulation 
 
   * **RunI Ideal scenario** : [81X_mcRun1_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v5) as [81X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_design_v5/81X_mcRun1_design_v4): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunI Heavy Ions scenario** : [81X_mcRun1_HeavyIon_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v5) as [81X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_HeavyIon_v5/81X_mcRun1_HeavyIon_v4): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunI Realistic scenario** : [81X_mcRun1_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v5) as [81X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_realistic_v5/81X_mcRun1_realistic_v4): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunI Proton-Lead scenario** : [81X_mcRun1_pA_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v5) as [81X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_pA_v5/81X_mcRun1_pA_v4): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
## RunII simulation 
 
   * **RunII Ideal scenario** : [81X_mcRun2_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v11) as [81X_mcRun2_design_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v11/81X_mcRun2_design_v10): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v12) as [81X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v12/81X_mcRun2_asymptotic_v11): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII Startup scenario** : [81X_mcRun2_startup_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v13) as [81X_mcRun2_startup_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v13/81X_mcRun2_startup_v12): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII Proton-Lead scenario** : [81X_mcRun2_pA_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v5) as [81X_mcRun2_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_pA_v5/81X_mcRun2_pA_v4): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v11) as [81X_mcRun2cosmics_startup_peak_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v11/81X_mcRun2cosmics_startup_peak_v10): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v11) as [81X_mcRun2_HeavyIon_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v11/81X_mcRun2_HeavyIon_v10): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
## RunII data 
 
   * **RunII Offline processing** : [81X_dataRun2_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v10) as [81X_dataRun2_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v10/81X_dataRun2_v9): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII HLTHI processing** : [81X_dataRun2_HLTHI_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v4) as [81X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLTHI_frozen_v4/81X_dataRun2_HLTHI_frozen_v3): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v7) as [81X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v7/81X_dataRun2_HLT_relval_v6): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII HLT processing** : [81X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v4) as [81X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_frozen_v4/81X_dataRun2_HLT_frozen_v3): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
   * **RunII Offline relval processing** : [81X_dataRun2_relval_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v13) as [81X_dataRun2_relval_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v13/81X_dataRun2_relval_v12): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
 
## Upgrade 
 
   * **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v23](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v23) as [81X_upgrade2017_realistic_v22](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v22) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v23/81X_upgrade2017_realistic_v22): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
      * updated Hcal gains and SiPM configuration from the initial test beam analysis to get better agreement with expected running conditions ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2734.html))
      * updated Hcal pedestals to fix the ADC2fc conversion for HB and HO the QIE offsets were not taken into account the excess of low pt rechits ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2734.html))
 
   * **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v7) as [81X_upgrade2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v7/81X_upgrade2017_design_IdealBS_v6): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))
      * updated Hcal gains and SiPM configuration from the initial test beam analysis to get better agreement with expected running conditions ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2734.html))
      * updated Hcal pedestals to fix the ADC2fc conversion for HB and HO the QIE offsets were not taken into account the excess of low pt rechits ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2734.html))
 
   * **PhaseII realistic scenario** : [81X_upgrade2023_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2023_realistic_v4) as [81X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2023_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2023_realistic_v4/81X_upgrade2023_realistic_v3): 
      * bug fix in Hcal Trigger Primitive Parameters ([ref.](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2726.html))

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by kpedro88** [comment]
@mmusich thanks for the quick turnaround!

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
