### PR TITLE
Unify tracking iteration configurations in RECO, DQM, and VALIDATION, and automatize cluster removal

### PR DESCRIPTION
**Pull request by makortel**
This PR demonstrates an approach for automatizing the cluster remover configurations in each tracking iteration making reordering the iterations super easy, that I used for the results shown in May 9 TRK POG  meeting https://indico.cern.ch/event/527844/contributions/2161117/attachments/1269921/1881271/slides_phase1_20160509.pdf. It started as a desire to reduce copy-paste between RECO, DQM, and VALIDATION configurations, but I soon realized that the same approach can be used also to automatize the cluster remover configurations.

~~The PR is currently marked as "RFC", because I'm unsure if~~
- ~~this is the way we want to solve the two "problems"~~
- ~~now is a good time do such changes~~
  - ~~I'm mainly thinking interference with Phase2 era migration, although I'd naively think this PR would make life easier also there~~

I tested all `(full workflow, trackingOnly workflow) x (Run2_2016, Run2_2016_trackingLowPU, Run2_2017, Run2_2017_trackingPhase1PU70, Run2_2017_trackingRun2, FastSim)` combinations as generated by #14540, and there should be no changes in RECO quantities. Validation (MultiTrackValidator) shows some changes because the order of input per-iteration track collections has changed in some of the combinations. In addition, the last commit 7293c47 adds plots for `duplicateMerge` tracks for `trackingLowPU` era that was inadvertently omitted before.

Tested in CMSSW_8_1_X_2016-05-16-2300 (rebased on top of CMSSW_8_1_X_2016-05-23-2300), no changes expected in standard workflows, except in MultiTrackValidator `*_coll` plots.

@rovere @VinInn ~~Please comment soon if the approach presented here has any chance to get integrated, i.e. I could use it to add `detachedTripletStep` back and reorder the iterations for phase1 (if not, I'll do them "manually").~~

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
Great work @makortel !
I was just looking for something like that as I wanted to test to swap Detached and LowPt.
They share almost 50% of the seeds but lowPt MVAcannot be used in Detached due to the high fake rate. The opposite may work and eventually save time in detached (LowPt is fastish anyhow)

**Comment by VinInn** [comment]
what does it mean "Build errors"????

**Comment by davidlt** [comment]
Jenkins is running the matrix now. Looks good at first glance.

**Comment by rovere** [comment]
Ciao Matti,
it has long been awaited and thanks for doing it!
From a quick inspection, I'd only factorise the ClusterChargeMasker out of the definition of any iteration and, in case, make it itself a "peculiar" iteration, otherwise moving around MixedTriplet will also move this around, which is not something we want, at least it does not fit the logic of this PR.

See, e.g. [here](https://roverepublic.web.cern.ch/roverepublic/IterSwapping/MixedTripletSwapped/html/), where I swapped MixedTriplet in the second place and that moved also (wrongly. IMHO) the ClusterChargeMasker.

I'm open to other suggestions/implementation related to this 'side-effect'

**Comment by makortel** [comment]
I take @VinInn's and @rovere's comments such that I removed the "[RFC]" from the PR description.

I agree with @rovere that it would be good to factor ClusterChargeMasker out from MixedTripletStep, but I would leave that to subsequent PR as I'd like to get this one merged soon in order to use the new machinery for phase1 (it is not immediately clear what would be the best way to do that).

**Comment by rovere** [comment]
Yes, indeed I give my powerless +1 for this PR: we can factor out the ClusterChargeMasker later on.

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
the comparisons are lost, apparently

**Comment by slava77** [comment]
in step3 of 11200 and 10600 in CMSSW_8_1_X_2016-05-23-1100 
```
ValueError: Trying to override definition of initialStepSeedLayers 
   while it is used by the sequence iterTrackingEarly
```
I don't think we can break phase 2 workflows at this point.

**Comment by makortel** [comment]
Thanks @slava77, I had indeed omitted the phase2 customizations. I rebased on top of CMSSW_8_1_X_2016-05-23-2300 and included a fix (last commit 5b7e864). The upgrade workflows 10600 and 11200 should work now.

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14544	5b7e864
- code changes are in line with the description
- jenkins tests pass and comparisons show differences only in MTV plots vs _coll (expected)
- local tests confirm that phase2 workflows are working now and have no differences in outputs

Looks like there is a flip in order of 
- cutsRecoTracksPixelPairStep and cutsRecoTracksDetachedTripletStep 
- cutsRecoTracksPixelPairStepHp and cutsRecoTracksDetachedTripletStepHp
wf1340_effic_vs_coll


Only histogram vs collection name have changed, which is expected based on the description.
Excluding the following pattern, there are no changes in DQM plots.
```
effic_vs_coll\|num_assoc\\\(recoToSim\\\)_coll\|num_assoc\\\(simToReco\\\)_coll\|num_reco_coll\|fakerate_vs_coll\|duplicatesRate_coll\|num_duplicate_coll\|num_pileup_coll\|pileuprate_coll
```

**Comment by makortel** [comment]
@slava77 To clarify what should happen (in  <= 2016 workflows) is that detachedTripletStep is moved before lowPtTripletStep (i.e. `lowPtTriplet,pixelPair,detachedTriplet` -> `detachedTriplet,lowPtTriplet,pixelPair`). Your plot looks consistent (as pixelPair is the only one of these three having entries).

**Comment by makortel** [comment]
@davidlange6 (Sorry for being hasty, but) is there anything holding back this PR? I have one phase1 tracking PR-to-be-submitted waiting for an IB with this one.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
