### PR TITLE
Run3-gex99B Use ESGetToekn in some of the codes in SimTracker/Track(Vertex)Association

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToekn in some of the codes in SimTracker/Track(Vertex)Association

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
