### PR TITLE
Update BeamSpotOnline tags for CRUZET

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR is the forward port of #34333 to update the GTs for CRUZET 2021:
- udpated names of the tags in the DQM online clients that write the payloads
- removed the ESSource in the `onlinebeammonitor` DQM client (avaid crash from multiple sources)
- update HLT and Express GTs which contain the new tags:
  - [BeamSpotOnlineHLT](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/BeamSpotOnlineHLT)
  - [BeamSpotOnlineLegacy](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/BeamSpotOnlineLegacy)

See #34333 for more details.

The GT diffs are:
**Run 3 data HLT**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v2/113X_dataRun3_HLT_v3

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v3/113X_dataRun3_Express_v4

#### PR validation:
Tested with:
```
runTheMatrix.py -l 138.2 --ibeos -j 8
addOnTests.py -j 8
```

#### Back/Forward-port
This is the forward port of #34333 to master.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
  - workflow = 138.2

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by qliphy** [comment]
test parameters:
- workflow = 138.2

**Comment by qliphy** [comment]
please test

**Comment by francescobrivio** [comment]
> please test

@qliphy is it normal that `comparison` and `required` tests are still "Pending"?

**Comment by qliphy** [comment]
> @qliphy is it normal that `comparison` and `required` tests are still "Pending"?

Sometimes it happened.  @smuzaffar 
Let's wait a bit more.  Otherwise we can abort and make test again.

**Comment by qliphy** [comment]
urgent

**Comment by francescobrivio** [comment]
+alca

**Comment by qliphy** [comment]
@cms-sw/dqm-l2  Do you have any comments?

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
