### PR TITLE
Use 11_2_X geometry in online and offline data global tags

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

PR #31529 updated the reco geometry for 11_2_X. It was always planned to perform the corresponding updates to the online GTs (and the offline GTs, which use the same tags) once the MC validation was completed, but this was never done. This PR remedies the situation.

The GT diffs are as follows. Some of the tags were already multi-IOV tags with `hlt` synchronization. For those, the updates were implemented as IOV appends. For those records in which the data GTs used the MC tags, new tags with `hlt` synchronization were required.

The GT diffs are as follows:

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_v4/113X_dataRun2_v5

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HEfail_v4/113X_dataRun2_HEfail_v5

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_relval_v4/113X_dataRun2_relval_v5

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_PromptLike_HI_v4/113X_dataRun2_PromptLike_HI_v5

**Run 3 data (HLT)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_HLT_v2/112X_dataRun3_HLT_v3

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HLT_relval_v5/112X_dataRun2_HLT_relval_v6

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_Express_v4/112X_dataRun3_Express_v5

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun3_Prompt_v4/112X_dataRun3_Prompt_v5

#### PR validation:

The payloads are identical to those already validated in simulation.

Technical tests were performed as well:

- `runTheMatrix.py -l limited,136.8642,138.1,138.2 --ibeos`
- addOnTests -j 8

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

A backport to 11_2_X is planned as the online GTs are intended for use in 11_2_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 136.8642,138.1,138.2

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Only runs >= 340848 are expected to be affected by this change and no change is observed in comparison tests

**Comment by silviodonato** [comment]
+1

**Pull request merged**
