### PR TITLE
fix clang linking issue in `SimMuon/MCTruth`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Addresses https://github.com/cms-sw/cmssw/pull/46860#issuecomment-2528482541

#### PR validation:

Compilation + linking in `CMSSW_15_0_CLANG_X_2024-12-08-2300` succeeds.
Verified that the plugins are known to the framework:

```console
$ edmPluginHelp -p Phase2SeedToTrackProducer
1  Phase2SeedToTrackProducer  (global::EDProducer)  "pluginSimMuonMCTruthPlugins.so"

  This plugin has not implemented the function which defines its
  configuration descriptions yet. No descriptions are available.
  Its PSets will not be validated, and no cfi files will be generated.

$ edmPluginHelp -p SeedToTrackProducer
1  SeedToTrackProducer  (global::EDProducer)  "pluginSimMuonMCTruthPlugins.so"

  This plugin has not implemented the function which defines its
  configuration descriptions yet. No descriptions are available.
  Its PSets will not be validated, and no cfi files will be generated.
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_15_0_X
just in case

**Comment by mmusich** [comment]
please test for CMSSW_15_0_CLANG_X

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
