### PR TITLE
python 2to3 migration tool fix_basestring

### PR DESCRIPTION
**Pull request by davidlange6**
apply fixes.fix_basestring tool from python futurize tool

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Wouldn't this break our python 7 code if we happen to have any unicode? See
https://docs.python.org/2/library/functions.html#basestring

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @ggovi @fabozzi @prebello @cmsdoxy could you please check and sign it in case?

**Comment by ggovi** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
I guess we will just try to avoid using unicode.

**Comment by fabiocos** [comment]
@Dr15Jones @davidlange6 I understand that this PR is ok to move forward

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
