### PR TITLE
PoolSource's firstLuminosityBlockForEachRun properly skips Lumis

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

When skipping Lumis while using firstLuminosityBlockForEachRun could cause the first Run number used to be incorrect.

#### PR validation:

The newly added unit tests checking correctness after skipping passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@silviodonato I know this is late, but if there is a chance to get this PR into pre6, it would help for next round of run-dependent MC testing. (if too late, those tests can wait)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
