### PR TITLE
Option to print periodically from SimpleMemoryCheck

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added option 'printEachSample'.

#### PR validation:

Compiles. Tested manually.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

The previous failures look like a failure of our infrastructure as no FileInPath functioned.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
