### PR TITLE
RPC DQM updates for Run3 [backport to 12_3_X]

### PR DESCRIPTION
**Pull request by minerva1993**
#### PR description:

Update of RPC DQM

remove histograms (ClusterSize 1D MEs / from summary folders, RPCChamberQuality, ClusterSizeIn1Bin and some other 1D distributions) - reducing DQM root file size by ~ 0.7 MB.
Change of plot format: ClusterSize 1D ME (cluster size vs entries) to 2D (cluster size vs roll, z axis to be entries) ME
Refine report summary map to present dead channel fraction correctly (instructions will be updated once related DQM GUI codes are updated)
Added 'Noise summary map' for shifters (GUI will be modified as well)
Bug fixes
Delete unused and duplicated file
Presented at RPC weekly meeting: https://indico.cern.ch/event/1156425/#5-rpc-status-for-the-dqm-shift

#### PR validation:

Passed `runTheMatrix.py -l limited -i all --ibeos`
Passed `scram b runtests`, `code-checks`, `code-format`
In addition, tested with Cosmic22 data

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backporting #37902 for p5 online DQM test

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
tests completed successfully

**Comment by perrotta** [comment]
backport of #37902

**Comment by qliphy** [comment]
+1

**Pull request merged**
