### PR TITLE
Add  position computation with linear weights for pathological low energy clusters

### PR DESCRIPTION
**Pull request by matteosan1**
This PR fixes a crash seen in prompt reco (run: 237686 lumi: 7 event: 33623).
The issue is due to very low energy cluster whose hits log-weights were all 0.

### CODE REVIEW

**Comment by bachtis** [comment]
Funny. @lgray , data dont like your logarithm :-) :-) :-)

**Comment by lgray** [comment]
@bachtis Considering that none of the zero suppression cuts have changed and the W0 is a relative cut on fraction of energy of a hit in a cluster. 

Talking to Matteo this cluster was 40-50 hits with each hit being ~0.2 GeV or so before multiplying by the assigned fraction for the cluster. This could easily make the fractions go crazy and you could end up with very very small rechit energies. 

Wouldn't worry about using vdt in realistic situations (as proven by CSA14 and PHYS14).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #8530 265693bb250a3df9c428067ff18984c0038d77ba

ECAL bug fix for a crash seen in prompt reco. The fix checks for and handles very low energy clusters.

The code change is satisfactory, as are the Jenkins tests. Extended tests against baseline CMSSW_7_3_5 show some very slight differences in some photon distributions from the workflow 19.0_SingleGammaPt35+SingleGammaPt35, but these differences are within the statistical uncertainties.

**Comment by cvuosalo** [comment]
hold

Double-checking some of the differences indicates that this fix may have an undesirable effect on photon efficiency. We've decided to run some more tests to be sure.

**Comment by cvuosalo** [comment]
Additional tests with workflow 19.0_SingleGammaPt35+SingleGammaPt35 using ten times more statistics verify that this PR makes only insignificant changes to monitored quantities.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
