### PR TITLE
Update Phase-2 L1T Correlator code to l1ct-125x-v1.16

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR ports to the CMSSW master branch two small updates to the correlator trigger code, for serializing and de-serializing electron objects in GT format (for GT emulator usage), and producing pattern files for integration tests (for correlator internal CI, not run in production)

Code is from @cerminar  

The corresponding PR to the L1T Phase-2 integration branch is https://github.com/cms-l1t-offline/cmssw/pull/1066 for @aloeliger 

#### PR validation:
Tested on `CMSSW_13_2_X_2023-05-09-2300`  with `runTheMatrix.py  -l 23234.0` and `L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_binaryFiles_cfg.py`

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
I really can't see how this PR can break any matrix workflow that is not phase-2, so I'd guess the test failures were either from some technical issue or a problem with the underlying IB in which the test was run.
I can re-trigger them, but to save some energy perhaps I can wait until you've had a look at the code in case you have code quality issues to fix

**Comment by gpetruc** [comment]
please test 
(retrying)

**Comment by aloeliger** [comment]
:confused:  These look like issues being fixed with https://github.com/cms-sw/cmssw/pull/41647. It might be worth testing with that PR attached.

**Comment by aloeliger** [comment]
please test with #41647

**Comment by aloeliger** [comment]
Hmm. None of these errors are consistent, and all the job reports mention are unexpected job termination.

**Comment by aloeliger** [comment]
The output of a lot of the job doesn't show any errors even. This is potentially a network/job management issue, not an issue with the PR itself?

**Comment by aloeliger** [comment]
Absent any better ideas, I am going to try this again just to check. Other PRs are passing their tests, so I don't think any systemic issues should be present.

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test with https://github.com/cms-sw/cmssw/pull/41647

whoops

**Comment by aloeliger** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
