### PR TITLE
First HLT menu compatible with L1Menu_Collisions2015_25ns_v2 - 73X

### PR DESCRIPTION
**Pull request by perrotta**
It is based on #7032, which is therefore fully included here, and can be closed.
It ends up with /dev/CMSSW_7_3_0/HLT/V47 (/dev/CMSSW_7_3_0/GRun/V24) the first HLT Run2 menu compatible with L1Menu_Collisions2015_25ns_v2

The overall list of menu updates with respect to what is in CMSSW_7_3_0 is:
- Moving HLT config to use 730 ConfDB template
- CMSHLT-202: Modify HLT_PFJet40
- CMSHLT-204: Various fixes for hadronic B2G paths (but revert the AK8Calo corrections because it looks like something is broken with it in the online GT's: to be updated once they will get fixed)
- CMSHLT-215: Bug fix for B2G Mu + 2 Jets Path
- Fixes HLT cfg dumps for TrackerGeometricDetESModule (same as #7045 already merged in 74X)
- Move default postLS1 L1 menu from _v1 to _v2
- Change in hltBLifeTimeL3FilterCSVsusy, CMSHLT-200
- Migration tau paths to a new L1 menu with L1_IsoTaus, CMSHLT-214
- Remove 'HighQ' from the name of the L1 muon seeds (as for L1 menu v2)
- Updated L1 seeds for hltL1sL1SingleJet36 and hltL1sL1SingleJet16 (use L1_SingleJet36 by now)
- Replaced L1_SingleEG35er with L1_SingleEG35 everywhere
- Updated L1 seeds and b-tagging sequence in Double Lepton + HT triggers (plus controls), CMSHLT-216
- Displaced jet triggers, CMSHLT-196
- Allow in GRun paths for the 7e33 menu formerly integrated with CMSHLT-160 and CMSHLT-164
- HLT_PFMETXXX_PFMHTXXX for 7E33 menu, CMSHLT-203
- BPH quarkonia paths for 7E33, CMSHLT-211
- Higgs diphoton paths, CMSHLT-199
- Add L1_DoubleMu0er16_WdEta18 to 5 BPH paths, CMSHLT-229
- Updated alpha-T paths, CMSHLT-207
- Dilepton paths for 7E33 CMSHLT-213
- Control path for electron + HT cross trigger, CMSHLT-197
- Update on TOP SingleLepton+Jets paths, CMSHLT-193
- Migration to next ConfDB CMSSW code template
- Fix prescales for HLT_Dimuon0er16_Jpsi_etc, as in a late request on CMSHLT-145
- New strip CPE configuration (only for 25ns menu), CMSHLT-228
- New relaxed tau+MET trigger for 7e33 menu, CMSHLT-226
- Changing the placehoder L1 seed to the real one for Electron+HT cross trigger, CMSHLT-233
- Migration electron legs of tau paths to WP75, CMSHLT-232
- Update cuts and names for single photon paths, CMSHLT-230
- Fix a few prescales
- Update of PixelSeed configuration, CMSHLT-237
- Cleanup: make module labels conform to HLT conventions

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@perrotta 
I suppose #7293 is not included here?

**Comment by perrotta** [comment]
@Martin-Grunewald : yes, I have not updated it yet.
I will do later on, or you can also do.
It would only updates the HLT configs, though.

**Comment by mulhearn** [comment]
+11

**Comment by mulhearn** [comment]
+1

**Comment by perrotta** [comment]
hold

**Comment by deguio** [comment]
+1
this doesn't involve DQM.

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@perrotta 
the fastsim dumps have a merge conflict in then, such as:
```
    L1GtObjectMapTag = cms.InputTag( "simGtDigis" ),
    L1TechTriggerSeeding = cms.bool( False )
)
<<<<<<< HEAD
hltPreAK8PFHT850TrimR0p1PT0p03Mass50 = cms.EDFilter( "HLTPrescaler",
    L1GtReadoutRecordTag = cms.InputTag( "simGtDigis" ),
=======
hltPreAK8PFHT700TrimR0p1PT0p03Mass50 = cms.EDFilter( "HLTPrescaler",
    L1GtReadoutRecordTag = cms.InputTag( "gtDigis" ),
>>>>>>> cms-sw/refs/pull/7116/head
    offset = cms.uint32( 0 )
)
hltAK8HtMht = cms.EDProducer( "HLTHtMhtProducer",
    usePt = cms.bool( False ),
```

**Comment by perrotta** [comment]
@Martin-Grunewald : yes, this PR will need to be rebased once next 73X (patch) release will become available. Up to now it is (and must stay) based on CMSSW_7_3_1_patch2: merge conflicts with the latest IB are expected, since PR's with FastSim development/fixes were included in it

**Comment by perrotta** [comment]
hold

**Comment by Martin-Grunewald** [comment]
Ah, ok!

**Comment by slava77** [comment]
-1

conflicts
rebase is needed, likely

**Comment by perrotta** [comment]
This pull request is not meant to be merged any more: close it.
(Keep the git branch alive just in case)

**Pull request closed without merging**
