### PR TITLE
bsunanda:Run2-alca42 Update the trigger usage + provide tools for monitoring

### PR DESCRIPTION
**Pull request by bsunanda**
Use both loose as well as tight selection cuts for isolated track studies

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@mmusich @franzoni Could you approve this

**Comment by bsunanda** [comment]
@mmusich @franzoni one more reminder

**Comment by bsunanda** [comment]
@mmusich @franzoni Pinging you once more. Could you approve this?

**Comment by bsunanda** [comment]
@mmusich @franzoni Pinging you once more. Could you approve this?

**Comment by bsunanda** [comment]
@mmusich @franzoni Pinging you once more. Could you approve this?

**Comment by bsunanda** [comment]
@mmusich @franzoni @davidlange6 Pinging you once more. Could you approve this?

**Comment by bsunanda** [comment]
@mmusich @franzoni @davidlange6 Pinging you once more. Could you approve this?

**Comment by abdoulline** [comment]
@mmusich @franzoni 
Marco and Giovanni,, I'm afraid this PR (improvement, not a dramatic code change) stays way too long without your attention...

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
