### PR TITLE
For PR testing only - Python3 in cmsRun

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

master version of #26401 for PR testing [with plenty of unneeded merge commits]

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test with #26408

**Comment by Dr15Jones** [comment]
Seems like the cmssw_das_client.py has an import problem.

**Comment by davidlange6** [comment]
plus i need to rebase.

**Comment by davidlange6** [comment]
ah - never mind - #26418 fixes

**Pull request closed without merging**
