### PR TITLE
Moving CaloRecHitAuxSetter.h and HBHERecHitAuxSetter.h

### PR DESCRIPTION
**Pull request by igv4321**
Moved the headers CaloRecHitAuxSetter.h and HBHERecHitAuxSetter.h to DataFormats/HcalRecHit so that HBHERecHit class can use them

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by igv4321** [comment]
I thought "scram b" is supposed to catch problems like this... Anyway, please restart the tests.

**Comment by smuzaffar** [comment]
@igv4321 , ```git cms-checkdeps -a ``` takes care of this. So ideally one should run it after touching public header files

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17534	1346851
- technical change: files moved
- jenkins tests passed (compilation and matrix tests are done already)

**Pull request merged**
