### PR TITLE
LogVerbatim to LogDebug for GE0SegAlgoRU

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Replaces LogVerbatim calls with LogDebug for some debugging output in GE0SegAlgoRU after some performance issues were found in #37527 

#### PR validation:

Checked an upgrade workflow runs properly. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jshlee** [comment]
test please

**Comment by perrotta** [comment]
please test

**Comment by clacaputo** [comment]
test parameters:

- enable_test = profiling

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
type performance-improvements

**Comment by watson-ij** [comment]
I guess this is the line we wanted to see?

`[32   -> 143 ] [0.6    -> 0.0   ]  [7.76      -> 0.29     ]         [ 0.29     /1319.05   - 7.76     /1315.14   *100% ] = [-0.57 % ]         GEMSegmentProducer::produce`

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8e3dfb/23933/profiling/35234.21/RES_CPU_compare_35234.21.txt

**Comment by clacaputo** [comment]
> I guess this is the line we wanted to see?
> 
> `[32 -> 143 ] [0.6 -> 0.0 ] [7.76 -> 0.29 ] [ 0.29 /1319.05 - 7.76 /1315.14 *100% ] = [-0.57 % ] GEMSegmentProducer::produce`
> 
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8e3dfb/23933/profiling/35234.21/RES_CPU_compare_35234.21.txt

Hi @watson-ij , indeed, moving to`LogDebug` reduces the CPU timing of `GEMSegmentProducer::produce`

**Comment by AdrianoDee** [comment]
+upgrade

**Pull request merged**
