### PR TITLE
More Nano step-related fixes for Run3/Phase2 workflows

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

1. Apply the fix from #36341 to some other workflows that similarly skipped the standalone Nano step
2. Put the `run3_nanoAOD_devel` modifier into the `Run3` Era (easier way to make sure workflows are consistently applying it)

attn: @cms-sw/xpog-l2 

#### PR validation:

Compared output of this command for 12_1_0_pre5 and this branch: `runTheMatrix.py -w upgrade -nel 10024.1,11624.1,11634.17,11834.17,12834.17,13034.17,11834.98,11834.99,11634.21,11834.21,11834.9821,11834.9921,35034.21,35234.21,35234.98,35234.99,35234.9821,35234.9921 --dryRun`. (This tests trackingOnly, deepCore, prodLike, premix workflows.)

### CODE REVIEW

**Comment by kpedro88** [comment]
resolves #36347

**Comment by kpedro88** [comment]
type bug-fix

**Comment by kpedro88** [comment]
test parameters:
workflows = 10024.1,11634.1,11723.17,11834.21,35034.21,35234.21,35234.9921

**Comment by kpedro88** [comment]
please test

**Comment by qliphy** [comment]
urgent
to be included for 12_2_0_pre3

**Comment by perrotta** [comment]
@kpedro88 Tests did not finish, yet. But there is at least an issue with 11723.17 to be fixed

**Comment by kpedro88** [comment]
For future reference, the crash and relevant trace:
```
%MSG-e BasicSingleTrajectoryState:  GsfTrackProducer:electronGsfTracks  03-Dec-2021 19:34:31 CET Run: 1 Event: 5
asking for componenets to a SingleTrajectoryState
%MSG
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e7669cd1d991022314b0cb0a8ff2f065/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/src/TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248: virtual const Components& BasicSingleTrajectoryState::components() const: Assertion `false' failed.

Thread 1 (Thread 0x2b65f44920c0 (LWP 15499) "cmsRun"):
#0  0x00002b65f240bddd in poll () from /lib64/libc.so.6
#1  0x00002b65f86d59d7 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#2  0x00002b65f86d630c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  0x00002b65f86d97ab in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b65f234e387 in raise () from /lib64/libc.so.6
#6  0x00002b65f234fa78 in abort () from /lib64/libc.so.6
#7  0x00002b65f23471a6 in __assert_fail_base () from /lib64/libc.so.6
#8  0x00002b65f2347252 in __assert_fail () from /lib64/libc.so.6
#9  0x00002b660004b4e8 in BasicSingleTrajectoryState::components() const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libTrackingToolsTrajectoryState.so
#10 0x00002b661c355dc7 in MultiStatePropagation<Plane>::propagateWithPath(TrajectoryStateOnSurface const&, Plane const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libTrackingToolsGsfTools.so
#11 0x00002b661c35570c in GsfPropagatorAdapter::propagateWithPath(TrajectoryStateOnSurface const&, Plane const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libTrackingToolsGsfTools.so
#12 0x00002b6620d5f6d1 in GsfPropagatorWithMaterial::propagateWithPath(TrajectoryStateOnSurface const&, Plane const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libTrackingToolsGsfTracking.so
#13 0x00002b6620d6221e in GsfTrajectoryFitter::fitOne(TrajectorySeed const&, std::vector<std::shared_ptr<TrackingRecHit const>, std::allocator<std::shared_ptr<TrackingRecHit const> > > const&, TrajectoryStateOnSurface const&, TrajectoryFitter::fitType) const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libTrackingToolsGsfTracking.so
#14 0x00002b6620b5eaa2 in (anonymous namespace)::KFFittingSmoother::fitOne(TrajectorySeed const&, std::vector<std::shared_ptr<TrackingRecHit const>, std::allocator<std::shared_ptr<TrackingRecHit const> > > const&, TrajectoryStateOnSurface const&, TrajectoryFitter::fitType) const () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginTrackingToolsTrackFittersPlugins.so
#15 0x00002b666c9b416e in TrackProducerAlgorithm<reco::GsfTrack>::buildTrack(TrajectoryFitter const*, Propagator const*, std::vector<AlgoProductTraits<reco::GsfTrack>::AlgoProduct, std::allocator<AlgoProductTraits<reco::GsfTrack>::AlgoProduct> >&, std::vector<std::shared_ptr<TrackingRecHit const>, std::allocator<std::shared_ptr<TrackingRecHit const> > >&, TrajectoryStateOnSurface&, TrajectorySeed const&, float, reco::BeamSpot const&, edm::RefToBase<TrajectorySeed>, int, signed char) () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/libRecoTrackerTrackProducer.so
#16 0x00002b666c843791 in TrackProducerAlgorithm<reco::GsfTrack>::runWithCandidate(TrackingGeometry const*, MagneticField const*, std::vector<TrackCandidate, std::allocator<TrackCandidate> > const&, TrajectoryFitter const*, Propagator const*, TransientTrackingRecHitBuilder const*, reco::BeamSpot const&, std::vector<AlgoProductTraits<reco::GsfTrack>::AlgoProduct, std::allocator<AlgoProductTraits<reco::GsfTrack>::AlgoProduct> >&) () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginRecoTrackerTrackProducerPlugins.so
#17 0x00002b666c83cf99 in GsfTrackProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02709/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_X_2021-12-02-1100/lib/slc7_amd64_gcc900/pluginRecoTrackerTrackProducerPlugins.so
```

The interesting thing is that this workflow runs fine in 12_1_0_pre5 (with or without this PR). It appears that it's not crashing in 12_2_X IBs only because the Reco step is removed entirely without this PR.

@perrotta what do you want to do here? I don't have the time or expertise to debug this workflow...

**Comment by qliphy** [comment]
> The interesting thing is that this workflow runs fine in 12_1_0_pre5 (with or without this PR). It appears that it's not crashing in 12_2_X IBs only because the Reco step is removed entirely without this PR.

@kpedro88     The Reco step for 11723.17 is only removed between  CMSSW_12_2_X_2021-11-29-1100 [1] and CMSSW_12_2_X_2021-11-29-2300 [2],  as @perrotta  commented previously [here](https://github.com/cms-sw/cmssw/issues/36347#issuecomment-985560212),  with a suspect being #36167 from you.   Can you check what happened in #36167 for 11723.17 and whether we can revert it back (partly)? Thanks!

[1] https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_2/2021-11-29-1100?selectedArchs=slc7_amd64_gcc900&selectedFlavors=X&selectedFlavors=X&selectedStatus=failed&selectedStatus=known_failed&selectedStatus=passed

[2] https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_2/2021-11-29-2300?selectedArchs=slc7_amd64_gcc900&selectedFlavors=X&selectedFlavors=X&selectedStatus=failed&selectedStatus=known_failed&selectedStatus=passed

**Comment by kpedro88** [comment]
@qliphy I'm saying that if I copy the exact step3 command from CMSSW_12_2_X_2021-11-29-1100:
```
cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --conditions auto:phase1_2021_realistic --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 10 --eventcontent RECOSIM,MINIAODSIM,DQM --geometry DB:Extended --era Run3 --procModifiers seedingDeepCore  --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary  --filein  file:step2.root  --fileout file:step3.root  --suffix "-j JobReport3.xml "  --nThreads 4 > step3_QCD_Pt_1800_2400_14+2021_seedingDeepCore+QCD_Pt_1800_2400_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST.log  2>&1
```

it crashes in a clean CMSSW_12_2_X_2021-12-03-1100 IB. So this specific crash is not caused by #36167; rather, #36167 accidentally hid the real problem by removing the RECO step, so the crash was not visible until now.

**Comment by perrotta** [comment]
I have verified what @kpedro88 wrote. If I run 
````
 runTheMatrix.py -l 11723.17 > & rtm_11723.17.out &
````
in CMSSW_12_2_X_2021-11-29-1100 (i.e. before #36167 was merged), that workflow crashes as well.

But in the IB tests of CMSSW_12_2_X_2021-11-29-1100 the same workflow succeed. The difference is in the input events, which in the PR tests are produced from scratch at step1, while in the IB tests they are taken from the store. (I cannot verify in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-71105c/20969/summary.html because that page does not open now, but this is what I see in my local lxplus)

Therefore, it confirms that the crash of 11723.17 in the tests does not depend on  #36167, or even on this PR.
Since the other failing workflows seem to have been fixed, I would propose to **merge this PR even if the test fail, and wait for the resuts IB tests**

(We can even re-run the tests without 11723.17, if people prefere not to have the "test rejected" status. And in any case, the issue must be debugged, but by Tracking and/or EGamma, since it involves `GsfTrackProducer:electronGsfTracks`)

**Comment by perrotta** [comment]
test parameters:
workflows = 10024.1,11634.1,11834.21,35034.21,35234.21,35234.9921

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
@perrotta thanks for confirming, I agree with your proposal for this PR.

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 please check andsign, if you agree with this PR: this is the last one missing before building pre3

**Comment by srimanob** [comment]
+Upgrade

**Comment by bbilin** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by perrotta** [comment]
I have opened an issue for the crash observed in 11723.17:  #36369

**Pull request merged**
