### PR TITLE
DQM: Code in preparation to the ucoming MWGR

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This is a backport of #30357 and #30592 to 11_1_3. This code is required to run the new DQM GUI during the upcoming MWGR.

This is planned to be merged.

#### PR validation:

PR was validated in the P5 playback system.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #30357 and #30592.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort 
https://github.com/cms-sw/cmssw/pull/30592 not merged yet

**Comment by silviodonato** [comment]
@andrius-k could you confirm that you do not need a new release including this PR for the MWGR? Thanks

**Comment by andrius-k** [comment]
Hi @silviodonato, it's not required to merge this PR for the MWGR. I will make more commits to it and will deploy it manually to the Online machines. The main PRs that we would like to have merged once the work is done are these: #30357 and #30592.

**Comment by silviodonato** [comment]
@cms-sw/dqm-l2 what is the plan of this PR and https://github.com/cms-sw/cmssw/pull/30592?

**Comment by andrius-k** [comment]
Hi @silviodonato,
#30592 is ready to be integrated. This PR is no longer required and therefore can be closed.

**Comment by andrius-k** [comment]
There were developments that depend on the changes implemented in this PR so it would be better to integrate this PR as well.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
