### PR TITLE
Run3 gex108 Modify all Run3 geometry scenarios by including demonstration chambers of GE21 & RPC, and detectors in forward region (BHM, PLT, BCMF) plus removing BSC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify all Run3 geometry scenarios by including demonstration chambers of GE21 & RPC, and detectors in forward region (BHM, PLT, BCMF) plus removing BSC

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

If successful, it needs to be back ported to 12_2_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , I would indeed propose to add to g4SimHits two new Boolean parameters to RPS and GEM SD, which will disable hits in demonstrator chambers by default. Corresponding additions are needed also in SD classes. Doing this, we will be able to establish Run-3 geometry before all problems of demonstrator hits will be resolved. Also it may be useful for production do not have these hits.

**Comment by bsunanda** [comment]
@civanch Thanks Vladimir; I am working on this

**Comment by bsunanda** [comment]
@civanch @watson-ij  I still get failure in GEMStripDigiValidation for accessing GEM geometry parameters. I think Ian was looking into this updating the GEMGeometry builder. Can he point me to the PR which he had and if it is integrated with the master

**Comment by bsunanda** [comment]
This PR is broken into 3 parts: #36652, #36653 and #36654. The first 2 PR's are ready to be merged first. The 3rd PR has to wait when these 2 PR's and the ones from GEM group are merged.

**Pull request closed without merging**
