### PR TITLE
bsunanda:Run2 hcx12 Correct double definitions

### PR DESCRIPTION
**Pull request by bsunanda**
Remove double definitions of some of the DetId's in the Digi definitions

### CODE REVIEW

**Comment by davidlange6** [comment]
@bsunanda - this is only part of the problem. You have made duplicate classes:
DataFormats/ForwardDetId/interface/HGCEEDetId.h
DataFormats/ForwardDetId/interface/HGCEEDetId.h

please fix the entire problem..

**Comment by davidlange6** [comment]
@bsunanda - ping

**Comment by bsunanda** [comment]
I shall try to fix this at the earliest
________________________________

**Comment by bsunanda** [comment]
There is no duplicate class definition in DataFormats/ForwardDetId
we have 2 classes with very similar names: HGCEEDetId and HGCHEDetId for EcalEndcap and HcalEndcap parts
________________________________

**Comment by deguio** [comment]
+1
does this need a rebase?
DQM not touched

**Comment by ianna** [comment]
@bsunanda - please, rebase

**Comment by davidlange6** [comment]
@bsunanda - then I have a different question - why can't these all live in the same package? DataFormats/ForwardDetId (FowardDigi) seems appropriate given the project name.

**Comment by bsunanda** [comment]
Do you mean the definition of DetId, Digi, RecHit be in the same package? It was never done in the past for other detectors. It can be - if different I would like ForwardDetId, ForwardDigi, ForwardRecHit rather than HGCDigi, HGCRecHit which were given in 6_2_X_SLHC.
________________________________

**Comment by mmusich** [comment]
@bsunanda would you please rebase?

**Comment by bsunanda** [comment]
I have rebased this and forced this in
________________________________

**Comment by davidlange6** [comment]
@bsunanda - no, I want all the detids in one package and all the digis in another. Otherwise I think forward is going to be a more appropriate name than hgcal but you should ask the project team

**Comment by bsunanda** [comment]
That is how they are right now. For DetIds it is clear that Forward is the right one because we are opening a group of DetId's where HGCal is one of them. For Digi/Reco I am happy to rename the packages as FcalDigi and FcalRecHit and then the geometry packages will be named FcalCommonData, FcalGeometry, ... I can raise this to others - but would project manager care?
________________________________

**Comment by bsunanda** [comment]
Could this PR be integrated now? Thanks and regards                   Sunanda
________________________________
From: Sunanda Banerjee
Sent: 15 July 2015 18:49
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2 hcx12 Correct double definitions (#9461)

That is how they are right now. For DetIds it is clear that Forward is the right one because we are opening a group of DetId's where HGCal is one of them. For Digi/Reco I am happy to rename the packages as FcalDigi and FcalRecHit and then the geometry packages will be named FcalCommonData, FcalGeometry, ... I can raise this to others - but would project manager care?
________________________________

**Pull request closed without merging**
