### PR TITLE
Remove constructors taking CSCDMBStatusDigi from CSCDMBHeader and CSCDMBTrailer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

`CSCDMBHeader` and `CSCDMBTrailer` both have a constructor taking `CSCDMBStatusDigi` and doing a `memcpy(this, ...)` from it. The problem is that both `CSCDMBHeader` and `CSCDMBTrailer` have a `boost::shared_ptr` as their first member, and it makes no sense to overwrite those via a `memcpy`. These constructors are not called (anymore?) in CMSSW, and judging from the git history it looks like they could be leftovers from #4034. This PR suggests to remove these constructors.

This issue was found by GCC 9.

In addition this PR replaces the `boost::shared_ptr`'s with `std::shared_ptr` in these two classes, and makes the `dynamic_cast`s const-correct.

#### PR validation:

The code compiles without warnings with GCC 9.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Those constructors with CSCDMBStatusDigi as argument are indeed never used in CMSSW, and they can be safely removed
- As such, this is a technical pull request, with no effect on jenkins tests output

**Comment by perrotta** [comment]
@ptcox

**Comment by fabiocos** [comment]
+1

**Pull request merged**
