### PR TITLE
Remove obsolete CSC DQM module in L1Trigger/CSCTriggerPrimitives

### PR DESCRIPTION
**Pull request by dildick**
This PR is a follow-up of #24171. The module `CSCTriggerPrimitivesDQM` in `L1Trigger/CSCTriggerPrimitives` used to function as a (maybe even the?) DQM module for the CSC trigger primitives. Since then, it has been superseded by dedicated modules in `DQM/CSCMonitorModule`. It was enabled in the DQM chain until 2014 at which point it was turned off as explained here: https://github.com/dmitrijus/cmssw/commit/069cc0a00b211ce1bcf8c37600237bfbf9eb0982. It also used to be enabled in test configurations in ` DQM/CSCMonitorModule`. Furthermore, `CSCTriggerPrimitivesDQM` is derived from `CSCTriggerPrimitivesReader` which has the same purpose, namely comparing unpacked ALCT/CLCT/LCT with re-emulated ALCT/CLCT/LCT. It is therefore deemed obsolete and can safely be removed.

Part of this project is also to update the `CSCTriggerPrimitivesReader`. That will be done in a future PR.

@tahuang1991 @lpernie

### CODE REVIEW

**Comment by dildick** [comment]
@thomreis Can you start the tests, please?

**Comment by lpernie** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
