### PR TITLE
Migrate RawToDigi to Tasks

### PR DESCRIPTION
**Pull request by makortel**
Title says it all. Supersedes #25110 by including a "Task" somewhere in the added task names, and keeping the sequences for "backwards" compatibility (to avoid a massive migration as in #25110). I did migrate three customize functions that replaced a module with a `Sequence` (because one can't add a `Sequence` to a `Task`).

Tested in CMSSW_10_4_X_2018-11-01-2300, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25162	2f469c3
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no relevant differences (ignoring occasionally random changes in DQM plots with the following directory pattern ```/HLT/Run summary/TAU/\|IsoTaus\|L1TStage2CaloLayer2/NonIsolated[^$]*Tau\|L1TStage2CaloLayer2/Isolated[^$]*Tau\|TausEtEtaPhi\|/L1TEMU```)

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
ping

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+operations

the modifications to the StandardSequences are coherent with the purpose of the PR.  A run of 136.85 with the Tracer service enabled confirms that the list of executed modules in a typical Run2 workflow is unchanged.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
