### PR TITLE
GEM-CSC Integrated trigger clean-up

### PR DESCRIPTION
**Pull request by dildick**
- Removed obsolete dataformat GEMCSCLCTDigi that was never used
- Algorithm matchGEMPads was removed since it is obsolete in 81X studies. The GEM-CSC bending angle is calculated at the time the CSCCorrelatedLCTDigi is constructed. 
- Obsolete algorithm matchRPCDigis was removed. 
- Configurations for the obsolete algorithms were removed
- switch off algorithm in RE3/1, RE4/1: RPC-CSC integrated trigger primitives will not be considered for PhaseII studies

This PR to be integrated after https://github.com/cms-sw/cmssw/pull/14562

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@civanch The dataformat GEMCSCLCTDigi was never used. We plan to put GEM-CSC bending angle information in the CSCCorrelatedLCTDigi dataformat by reinterpreting some of the fields.

**Comment by dildick** [comment]
Rebased onto CMSSW 810 pre7

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@civanch GEMCSCLCTDigi has intentionally been removed. The dataformat is not being used anywhere in the simulation. I'm not sure what I can do from my side so that the changes pass the build tests.

**Comment by civanch** [comment]
@dildick , can you modify the test in way that it will work? The test was intended for validation L1Trigger/CSCTriggerPrimitives, it should configured in appropriate way. This would be the best solution. If you have no way to recover this test then we should exclude it, probably, in different PR.

**Comment by dildick** [comment]
@civanch My apologies. I just realized I forgot to delete GEMCSCLCTDigi.cc. This has been done now.

**Comment by civanch** [comment]
Please test

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
@cmsbuild PR #14858 was signed.

**Comment by dildick** [comment]
@civanch I'm not sure what is happening, but @cmsbuild is not parsing the messages...

**Comment by civanch** [comment]
@dildick , it is not sending your messages to you but does send to other assignees. Note, that L1 signature is not yet provided for this PR.

**Comment by mulhearn** [comment]
passes our L1T unit and comparison tests as expected...

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
