### PR TITLE
Make HLTPrescaler stage-2 aware

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Make HLTPrescaler stage-2 aware

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
hi Martin, could you make two version of this module, one for GT and one for uGT ?
This would save checking for both collections every time.

**Comment by Martin-Grunewald** [comment]
Since the only non-stage-2 use case is the Fake menu, it should not be a problem:
and we always tested the handle first, so would not gain cpu time.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
