### PR TITLE
make TriggerMatchProducer and JetHTJetPlusHOFilter stream modules

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of #25090
Made `TriggerMatchProducer` and `JetHTJetPlusHOFilter` stream modules.
Profited of this to remove `TriggerMatchProducer.icc` file and include it in the class header.

#### PR validation:

It compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@chayanit, @wajidalikhan, @jordan-martins any objection to move on with this PR?

**Comment by chayanit** [comment]
How come PdmV assigned to this PR? I don't see anything related or do I miss anything?

**Comment by boudoul** [comment]
Hello @chayanit , I assume it is due to the fact that skims definition and maintenance are part of the PdmV responsibilities.

**Comment by chayanit** [comment]
@kfjack could you have a look to this PR?

**Comment by kfjack** [comment]
@chayanit It should be fine (tested JetHTJetPlusHOFilter locally as well).

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
