### PR TITLE
Run2-trk04 Add 8 scenarios for 2017/18 setup with changed material budget of tracker

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add 8 scenarios for 2017/18 setup with changed material budget of tracker

#### PR validation:

Tested using cfg's from test area by dumping the geometries

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
