### PR TITLE
Add LHEPtFilter plugin needed for MC generation [93X backport]

### PR DESCRIPTION
**Pull request by ajgilbert**
#### PR description:
Backport of #28443, needed in 9_3_X for official production of 2017 MC using this filter.

> Adds a new plugin in GeneratorInterface/GenFilters that applies a user specified pT (or pT range) cut to the p4 sum of a subset of LHE-level particles. This is needed specifically for the production of Wgamma samples binned in the photon pT, but may be useful more generally in the future.

#### PR validation:

All tests in `runTheMatrix.py` passed.

#### if this PR is a backport please specify the original PR:

Yes, #28443

### CODE REVIEW

**Comment by kpedro88** [comment]
backport of #28443

**Comment by kpedro88** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
