### PR TITLE
PPS: rename directories with misleading names

### PR DESCRIPTION
**Pull request by silviodonato**
Copy of #29037 (ie. revert of revert #29093) by @jan-kaspar 

#### PR description:

There were two instances of directories with misleading names in the (CT)PPS code tree:
 * CondFormats/CTPPSReadoutObjects: contained all PPS cond-formats, not just readout,
 * RecoCTPPS/TotemRPLocal: beyond the code for Si strip detectors (from TOTEM), contained also the code for diamond and UFSD sensors.

We profit from this renaming, to replace CTPPS with PPS in the affected directory names.

In RecoPPS, we put all the local-reconstruction (within a single RP) into a single directory "Local".

This is a technical RP, no changes in the results are expected.

#### PR validation:

Running
```
runTheMatrix.py -l limited -j 10 --ibeos
```
gave
```
34 33 32 26 16 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```

The plots below compare proton reconstruction with CMSSW_11_1_0_pre3 (blue) and this PR (red dashed) - there is no difference as expected.
make_cmp

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The failing unit tests refer to duplications with directories/packages which do not exist any more.
This is the same issue that was observed with the previos PR (although I do not remember those failing unit tests: are they new?), and it will likely disappear as soon as a full build in the IB with this PR merged is done.

For me this PR can go on as it is, but please @mrodozov @Dr15Jones,@smuzaffar,@makortel @silviodonato suggest how to proceed

**Comment by silviodonato** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by tlampen** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical to #29037, merged first and then reverted
- The migration only consists in renaming more appropriately a few directories.
- It is propagated correctly whenever they are addressed in CMSSW
- Jenkins tests pass, and show no differences
- Warning reports about duplicate plugins and libraries are expected to disappear once the change is merged in the release, and a full build follows

**Comment by perrotta** [comment]
PR https://github.com/cms-sw/cms-bot/pull/1271 was created to update the category maps with the new (i.e. renamed) packages

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
@smuzaffar @mrodozov could you add new packages in https://github.com/cms-sw/cms-bot/blob/master/categories_map.py? They should be a trivial rename "CTPPS" -> "PPS"

**Comment by mrodozov** [comment]
@perrotta already did in cms-sw/cms-bot#1271 (right?)

**Comment by perrotta** [comment]
> @perrotta already did in [cms-sw/cms-bot#1271](https://github.com/cms-sw/cms-bot/pull/1271) (right?)

Yes. Thank you @mrodozov

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
