### PR TITLE
Add parameterSet retrieval function to Event

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added the method parameterSet to the base class for all Events, edm::EventBase. This function guarantees that the ParameterSetRegistry has already been filled before attempting to do a lookup.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I'm anticipating that clang might give warnings if I missed a place where I should have added `override`.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
