### PR TITLE
Adding general track to ALCARECO for muonalign

### PR DESCRIPTION
**Pull request by lpernie**
Hi @mmusich,
This the new PR on the addition of general tracks to the ALCARECO stream for muon alignment you requested on 80X.
It follows the PR in https://github.com/cms-sw/cmssw/pull/15221.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
https://github.com/lpernie/cmssw-1/commit/11801a388c01a3b610983871f1d1a1b034b6a64f needs to be first in 81x. Thanks @lpernie

**Comment by mmusich** [comment]
please test

**Comment by lpernie** [comment]
Hello @mmusich ,
I saw tests failed. I'm still a bit confused about adding DQM after general tracks (I sent a mail a while ago). If I add a DQM module after General Track path, I would assume the DQM module is expecting muons, but it actually only have general tracks:
I refer in particular to: https://github.com/lpernie/cmssw-1/blob/11801a388c01a3b610983871f1d1a1b034b6a64f/Configuration/StandardSequences/python/AlCaRecoStreams_cff.py#L177 , where DQM is on top of something that only have general tracks:
https://github.com/lpernie/cmssw-1/blob/11801a388c01a3b610983871f1d1a1b034b6a64f/Alignment/CommonAlignmentProducer/python/ALCARECOMuAlCalIsolatedMu_cff.py#L50

**Comment by mmusich** [comment]
@lpernie we need also https://github.com/lpernie/cmssw-1/commit/03d52a91aee8d42167d922410206da2d953f5d57 as a standalone PR in 81x.

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@lpernie Hi Luca, can you update the 81x version as well?

**Comment by lpernie** [comment]
@mmusich Done!

**Comment by mmusich** [comment]
backport of #15221 and #15753

**Comment by mmusich** [comment]
+1

**Review by dmitrijus — APPROVED** [review]

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by franzoni** [comment]
+1

ok both for AlCa (already signed) and for operations 

(simply adding 3 needed sequences:
pathALCARECOMuAlCalIsolatedMuGeneralTracks  pathALCARECOMuAlZMuMuGeneralTracks   pathALCARECOMuAlOverlapsGeneralTracks
to: AlCaRecoStreams_cff.py
)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
