### PR TITLE
[DD4hep] evaluate all numeric parameters in tracker detector description

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

A follow up to the thread-safety issue reported by @Dr15Jones that was addressed in https://github.com/cms-sw/cmssw/pull/32339:
all numeric constants should be evaluated.

Both step1 and step2 run to completion.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by ianna** [comment]
@silviodonato and @cvuosalo - which IB workflows are dd4hep based? Thanks

**Comment by silviodonato** [comment]
@ianna 11624.911 and 11642.91 (see https://github.com/cms-sw/cmssw/pull/32096)

**Comment by ianna** [comment]
please test workflow 11624.911, 11642.91

**Comment by ianna** [comment]
Hmm...
```
ValueError: Undefined workflows: 11642.91
```

**Comment by ianna** [comment]
please test workflow 11624.911

**Comment by ianna** [comment]
@cvuosalo and @civanch - it looks like the dd4hep workflows finished successfully even though the label was not updated :-)

**Comment by silviodonato** [comment]
@ianna usually we see the crash of the DD4HEP workflows only in the IB test. The PR tests are single thread and "often" run without errors. The good news is that we don't see the two failing workflows in `CMSSW_11_3_X_2020-12-02-2300` IB tests (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_3_X)

**Comment by qliphy** [comment]
> @ianna usually we see the crash of the DD4HEP workflows only in the IB test. The PR tests are single thread and "often" run without errors. The good news is that we don't see the two failing workflows in `CMSSW_11_3_X_2020-12-02-2300` IB tests (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_3_X)

@ianna  As @silviodonato mentioned this seems to fix the IB issue for the two failing DD4hep workflows 11642.911 and 11624.911.  Would you please backport #32371 and #32339 to 11_2_X?  In 11_2_X IB, we still see the issues.
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_2/2020-12-01-2300?selectedArchs=cc8_amd64_gcc9&selectedFlavors=X&selectedStatus=failed

**Comment by ianna** [comment]
> > @ianna usually we see the crash of the DD4HEP workflows only in the IB test. The PR tests are single thread and "often" run without errors. The good news is that we don't see the two failing workflows in `CMSSW_11_3_X_2020-12-02-2300` IB tests (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_3_X)
> 
> @ianna As @silviodonato mentioned this seems to fix the IB issue for the two failing DD4hep workflows 11642.911 and 11624.911. Would you please backport #32371 and #32339 to 11_2_X? In 11_2_X IB, we still see the issues.
> https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_2/2020-12-01-2300?selectedArchs=cc8_amd64_gcc9&selectedFlavors=X&selectedStatus=failed

ok, will do it asap

**Pull request merged**
