### PR TITLE
Static analysis warnings fixes 

### PR DESCRIPTION
**Pull request by civanch**
It is the same PR as 11097

### CODE REVIEW

**Comment by davidlt** [comment]
@civanch this also fixed G4 related segfaults in DEVEL IBs?

@davidlange6

**Comment by civanch** [comment]
@davidlt , yes, it should fix few IB crashes. Not for the first time static analysis helps.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlt** [comment]
Let's put it in and see if it resolves the issues.

**Comment by davidlt** [comment]
@davidlange6 @civanch do we need this in `CMSSW_8_0_X`? Is this just static analyzer cleanups?

**Comment by civanch** [comment]
@davidlt, it is written that this PR is the same as #11097, which has been integrated in 7_6_X, likely these fixes are in 8_0_X already. However, there are still a lot of static analysis complains in 8_0_X for SIM and I plan to reduce them in coming weeks.

**Pull request merged**
