### PR TITLE
Changed legacy modules in L1Trigger/TrackTrigger

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Changed modules to be thread friendly types. These modules are used in workflow 20034.0.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by Dr15Jones** [comment]
@kpedro88 we should probably make an issue that this code should be looked at in more detail. E.g. the module is a template but it appears only 1 type can work with it.

**Comment by kpedro88** [comment]
thanks @Dr15Jones 
FYI: @mdhildreth @skinnari @delaere

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge
cc: @rekovic

**Pull request merged**
