### PR TITLE
Remove redundant unique_ptr constructor call from DigiAccumulatorMixModFactory

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Cleanup follow-up to #27097.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@makortel there will likely be a conflict in this PR with #27171

**Comment by makortel** [comment]
@fabiocos Thanks for the heads-up, I'll rebase after #27171 (conflict should be straightforward to resolve).

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
Rebased to fix the conflict.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
