### PR TITLE
new Tau discriminator and Jet leg efficiency added

### PR DESCRIPTION
**Pull request by vmuralee**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by vmuralee** [comment]
> @vmuralee Is this a backport PR? If not, please make a forward PR to master (12_5_X).

This is the backport PR for 12_4_X , what step I have to follow for the backport

**Comment by perrotta** [comment]
> > @vmuralee Is this a backport PR? If not, please make a forward PR to master (12_5_X).
> 
> This is the backport PR for 12_4_X , what step I have to follow for the backport

@vmuralee please do exactly what @qliphy wrote, i.e. make an identical PR in the master

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
some unit test fail with the following error (likely related to your PR)
----- Begin Fatal Exception 06-Aug-2022 06:37:10 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297557 lumi: 123 event: 197153873 stream: 0
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module HLTTauRefProducer/'TauRefProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<reco::SingleTauDiscriminatorContainer>
Looking for module label: hpsPFTauDiscriminationByMuonRejection3
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

see log: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15875b/26670/runTheMatrixINPUT-results/136.7803_RunHLTPhy2017B_RAWAOD+RunHLTPhy2017B_RAWAOD+DQMHLTonRAWAOD_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_RAWAOD+RunHLTPhy2017B_RAWAOD+DQMHLTonRAWAOD_2017+HARVESTDQMHLTonAOD_2017.log

@vmuralee could you please look into it?

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
@vmuralee there's a lot of messages like this in the logs (probably related to your code changes):
%MSG-w HLTTauDQMOffline:  HLTTauDQMOfflineSource:hltTauOfflineMonitor_Inclusive  25-Aug-2022 07:53:20 CEST Run: 160960 Event: 10001698
HLTTauDQML1Plotter::analyze: unable to read L1 met collection caloStage2Digis:EtSum
%MSG

See:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15875b/27072/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

Also there are failures in runthematrix

**Comment by emanueleusai** [comment]
@vmuralee what are the plans for this PR?

**Comment by emanueleusai** [comment]
-1

- stale PR

**Comment by vmuralee** [comment]
The integration will continue with the PR #39651. Closing this PR.

**Pull request closed without merging**
