### PR TITLE
[14_2_X backport]: MTD reconstruction: save correct outermost hit position also for tracks w/o last hit in mtd

### PR DESCRIPTION
**Pull request by martinamalberti**
#### PR description:
Exact backport to CMSSW_14_2_X of  PR https://github.com/cms-sw/cmssw/pull/46752

#### PR validation:
Code was developed and tested on 14_2_X, moved to 15_0_X during PR test.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
