### PR TITLE
FastSim Treatment in HLT tests (74X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
FastSim Treatment in HLT tests (74X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
Hi @davidlange6 .

This PR was first merged in 74X, and as far as I understand it then was reverted before building CMSSW_7_4_4. Nonetheless, its content was fully included in #9292, and therefore nothing got apparently lost in the procedure.

However, I think that some comment should remain in the "Conversation" of a Pull Request which gets reverted, and perhaps the same PR should remain in a different state rather than "Merged": all this to avoid confusions, possible mistakes and potential loss of possible updates (see also my correlated comments in #9115 and #9138)

Thank you,
Andrea

**Comment by davidlange6** [comment]
@perrotta - why do you think this PR got reverted?

**Comment by Martin-Grunewald** [comment]
@perrotta @davidlange6 
I do see this in 744...

**Comment by perrotta** [comment]
Yes, as I wrote above all the content of this PR is in 744, but only  
because it was also included in #9292.
Thus, we are happy that the whole content is there. As in the other  
two cases, it was apparently merged but it is not listed in  
https://github.com/cms-sw/cmssw/releases/CMSSW_7_4_4.

Therefore, in this case nothing got lost, but the same (dangerous)  
issue that I also notified in the other two PR's happened also for  
this one.

Andrea



Martin Grunewald <notifications@github.com> ha scritto:

**Comment by davidlange6** [comment]
> On May 31, 2015, at 6:24 PM, perrotta <notifications@github.com> wrote:
> 
> Yes, as I wrote above all the content of this PR is in 744, but only 
> because it was also included in #9292.
> Thus, we are happy that the whole content is there. As in the other 
> two cases, it was apparently merged but it is not listed in 
> https://github.com/cms-sw/cmssw/releases/CMSSW_7_4_4.
> 
> Therefore, in this case nothing got lost, but the same (dangerous) 
> issue that I also notified in the other two PR's happened also for 
> this one.

its the way git works, as it works on the basis of commits. If you are merging commits already merged, it has nothing to do and thus does nothing. Maybe there is some way to grab that PR # even when there are no new commits, but its what we have implemented.

I don’t understand the “danger”. 

David

**Pull request merged**
