### PR TITLE
Sim magnetic field

### PR DESCRIPTION
**Pull request by civanch**
Clean-up and extension of magnetic field for simulation:
1) added possibility to use a special set of parameters for integration in magnetic field in set of geometry regions;
2) fixed problem in initialisation printouts;
3) defined chord finder parameters in one place of the code;
4) clean-up simulation of monopole transportation in field;
5) removed unused headers and obsolete comments, added improved comments.

No change in results is expected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@fabiocos , this PR is only addition and technical cleanup. Such type of PRs are valid is no change is observed in regression tests.

**Comment by fabiocos** [comment]
@civanch indeed the test does not show any difference, so we could merge it. At some point anyway we will need a larger scale test, and as we have been already reproduced the GEN-SIM in pre3 I would like to avoid redoing them multiple times in a row.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
