### PR TITLE
Drop Herwig6Interface, MCatNLOInterface, PomwigInterface

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Drop Herwig6Interface, MCatNLOInterface and PomwigInterface due to removal of legacy MC generators (https://github.com/cms-sw/cmsdist/pull/7763).

### CODE REVIEW

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7763

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7763

**Comment by iarspider** [comment]
(last commit should read "... for herwig6")

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7806

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , I suggest that we merge this (along with cmsdist PRs) in DEVEL IBs to test full runTheMatrix. If DEVEL IBs show no failure then we can backport these for `master` branch.

**Comment by smuzaffar** [comment]
@qliphy @perrotta , we would like to test these changes first in DEVEL IBs, if @cms-sw/generators-l2 has no objections then please include these for next DEVEL IBs ( along with the cmsdist PRs)

**Comment by qliphy** [comment]
merge
to test for next DEVEL IBs

**Comment by santocch** [comment]
+1

**Pull request merged**
