### PR TITLE
Fixes for CLANG_X+CPP20

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

See https://github.com/cms-sw/cmsdist/pull/9288.

* Move definition of `LHERunInfo::Process` comparision operators before usage [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c0e2b3/40307/build-logs/GeneratorInterface/LHEInterface/log.html)
* Add include of Track.h to make class fully defined [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c0e2b3/40307/build-logs/RecoTracker/FinalTrackSelectors/log.html)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , can you please review and sign it. This only moves the `LHERunInfo::Process` comparision operators . This is needed for CLANG 18 with c++20

**Comment by menglu21** [comment]
+1

**Comment by menglu21** [comment]
sorry for overlooking it

**Comment by rappoccio** [comment]
+1

**Pull request merged**
