### PR TITLE
fix to psu tracker map code

### PR DESCRIPTION
**Pull request by fioriNTU**
fix for the psu tracker map

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10256	e969181
- the same code change as in 75X. reco is not affected (code is used only in DQM and calibration)
- jenkins tests OK and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
