### PR TITLE
Fastsim: Muon HLT: refactor seeding configuration

### PR DESCRIPTION
**Pull request by lveldere**
modify the standard configuration for muon seeds,
rather than replacing it.

move configuration for HLT muon tracking to FastSimulation/Tracking

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1 

Slight changes in FastSim HLT muon directory.
Expected since configuration now better in line with standard HLT.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
