### PR TITLE
Add LHE HT and generator weights to TagAndProbe tree

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Adding to TagAndProbe tree:
* LHE HT for correct stitching of HT-binned samples
* Weights for ME scale variations (can replace statistically limited MG vs aMCatNLO comparisons)
* Weights for PS scale variations

#### PR validation:

Compiles in 11_2, no working EGM config available, unfortunately.

Validated and used in 10_2 (https://github.com/cms-sw/cmssw/compare/CMSSW_10_2_X...intrepid42:TnP_102X):

image

@jainshilpi

### CODE REVIEW

**Comment by santocch** [comment]
please test

**Comment by silviodonato** [comment]
do you have any comments @santocch ?

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
