### PR TITLE
relval update data workflow reco step, and re-work the LHE-based fullSim workflows for HLT validation

### PR DESCRIPTION
**Pull request by hengne**
Two major changes:

1.) update RECODR2_25ns and _2016 adding missing customization function according to discussion with @slava77 in PR #14117 

Discussion: https://github.com/cms-sw/cmssw/pull/14117/files#r61775898

2.) re-work the LHE-based fullSim workflows for HLT validation (will keep them in the future). Merge the previous separated LHE and GEN-SIM steps into one step to adapt to the current structure of GEN-SIM recycling in the matrix. Both the noPU and PU workflows are worked out.

### CODE REVIEW

**Comment by hengne** [comment]
please test.

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by covarell** [comment]
please test

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by hengne** [comment]
@covarell @govoni could you please help to verify the gen fragments and sign? Thanks!

**Comment by govoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
