### PR TITLE
move TreeWriterForEcalCorrection in to a plugin directory

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #27913
Move TreeWriterForEcalCorrection in to a plugin directory to avoid duplicate dictionary errors in IB

https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc7_amd64_gcc700/www/fri/10.6-fri-11/CMSSW_10_6_X_2020-05-01-1100/testLogs/dupDict-edmPD.log

- TreeWriterForEcalCorrection
  - pluginFastSimulationEventProducer.so
  - pluginFastSimulationSimplifiedGeometryPropagatorAuto.so

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
Any objections from fastsim ( @civanch @lveldere @mdhildreth @sbein @ssekmen ) ?

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
