### PR TITLE
read chunks of lhe compressed files in LHEReader

### PR DESCRIPTION
**Pull request by davidlange6**
now considerably faster.. per file overhead is now purely xml parsing.

### CODE REVIEW

**Comment by bendavid** [comment]
Does this only affect the compressed case, or does it also speed up uncompressed reading?

**Comment by davidlange6** [comment]
I implemented only the compressed case.

**Comment by bbockelm** [comment]
Something similar can be done in the uncompressed case.  I would expect speedups, but perhaps not quite as impressive - I can't tell from reading the code what kind of buffering Xerces might do internally.

@davidlange6 - two thoughts:

1.  You can avoid keeping the separate uncompressed buffer and reading directly into the one provided by Xerces.  This would save a significant amount of memory and avoid the memcpy.
2.  Another alternate I just thought of is to add the `IOFlags::OpenWrap` flag when opening the file (https://github.com/davidlange6/cmssw/blob/lhereader/GeneratorInterface/LHEInterface/src/LHEReader.cc#L56); this will turn on lazy-download if possible.  That should benefit both the compressed and uncompressed case.

**Comment by bendavid** [comment]
If lazy download uses (and does not free up as it goes) a significant amount of disk space per file, then that would kill the current workflow by filling up the worker node disk.

**Comment by bbockelm** [comment]
Well, lazy-download cleans up at file close.  It also will automatically turn itself off if less than N GB is available on the local disk (IIRC, N=4).

What's the size of the individual pLHE files?

**Comment by bbockelm** [comment]
@davidlange6 - what pset did you use to test this?

**Comment by bbockelm** [comment]
David sent me a sample pset and LHE file off-list.

The good news for the uncompressed case is that it appears Xerces uses a 48KB buffer.  While I still prefer larger (MB-sized), this is much better than the compressed case (8KB with random reads).

I'm going to tweak the patch to take into account my suggestions above.

**Comment by bbockelm** [comment]
FYI - my revised PR is in #10287.

**Pull request closed without merging**
