### PR TITLE
pACentrality DQM in 81X

### PR DESCRIPTION
**Pull request by smdogra**
Added DQM module for Centrality variables in pPb run.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by kpedro88** [comment]
@smdogra Why did the last commit in this PR introduce an import of `Configuration.StandardSequences.Eras`? Please restore the proper import `from Configuration.Eras.Modifier_pA_2016_cff import pA_2016` unless there is a very good reason not to do so.

**Pull request merged**
