### PR TITLE
Move TcdsRawToDigi

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

Moving TCDS Raw to Digi module to another location which allows Utilities to not be monitored by reco.

#### PR validation:

Compilation successful.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
Thanks for this! Looks like there are a couple of python modifications needed as well

```
$ git grep tcdsRawToDigi_cfi *
Configuration/StandardSequences/python/RawToDigi_cff.py:from EventFilter.Utilities.tcdsRawToDigi_cfi import *
Configuration/StandardSequences/python/RawToDigi_cff.py:tcdsDigis = EventFilter.Utilities.tcdsRawToDigi_cfi.tcdsRawToDigi.clone()
Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py:import EventFilter.Utilities.tcdsRawToDigi_cfi
Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py:unpackTcds = EventFilter.Utilities.tcdsRawToDigi_cfi.tcdsRawToDigi.clone(
Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py:import EventFilter.Utilities.tcdsRawToDigi_cfi
Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py:unpackTcds = EventFilter.Utilities.tcdsRawToDigi_cfi.tcdsRawToDigi.clone(
DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py:from EventFilter.Utilities.tcdsRawToDigi_cfi import * # To monitor LHC status, e.g. to mask trigger primitives quality alarm during Cosmics
DQM/Integration/python/clients/info_dqm_sourceclient-live_cfg.py:from EventFilter.Utilities.tcdsRawToDigi_cfi import *
```

**Comment by smorovic** [comment]
Thanks, I pushed Python changes now.
Suspiciously, I still get:
```
 unknown python problem occurred.
ModuleNotFoundError: No module named 'EventFilter.OnlineMetaDataRawToDigi.tcdsRawToDigi_cfi'
```
when I try in a local project area despite the file being generated in cfipython of the project.
Let's see if it works in cmsdist test ( should be covered by unit test in EventFilter/Utilities).

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by smorovic** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- technical

**Comment by perrotta** [comment]
+operations

**Comment by elfontan** [comment]
**NOTE** that we need to update also [SimL1EmulatorRepack_uGT_cff.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py#L20-L22) accordingly.
I was getting the following exception when running hltGetConfiguration witht the _--l1-emulator uGT option_:

_Exception Message:
 unknown python problem occurred.
ModuleNotFoundError: No module named 'EventFilter.Utilities.tcdsRawToDigi_cfi'
At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-02-09-2300/python/Configuration/StandardSequences/SimL1EmulatorRepack_uGT_cff.py(20): <module>_

@smorovic do you want to proceed with the change or do you want me to proceed?

Warm regards,
--Elisa

**Comment by smorovic** [comment]
Hi @elfontan,
I will created https://github.com/cms-sw/cmssw/pull/36924
Let me know if you find any other issue.

Best Regards,
Srecko

**Comment by elfontan** [comment]
Hi @smorovic,
thank you very much!

Cheers,
--Elisa

**Pull request merged**
