### PR TITLE
Fix hgcal ageing

### PR DESCRIPTION
**Pull request by rovere**
Mainly python changes in order to treat ageing within HGCAL correctly. All involved configuration parameters have been assigned to RefToPSet so that their handling all along the release is cleaner and not subject to the specific load sequences of the different cff/cfi/cfg involved in different steps (DIGI+RECO).
I decided to leave the customization as is (i.e. via a call to customize) rather than migrate everything to some specific sub-era since many other detectors would have been affected. It could be an improvement for the future if deemed useful.
Finally, I modified the customization function that now has only to change the RefToPset definitions in order to perform its task.

@malgeri

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- HGCal ageing parameters defined via refToPSet: implementation corresponds to what declared in the description
- No changes expected with respect to the code in the baseline release, no changes observed in the jemkins comparisons of the upgrade workflows

**Comment by fabiocos** [comment]
+1

**Pull request merged**
