### PR TITLE
Bug fixes and adding a Fake2 HLT menu (90X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Adding a Fake2 HLT menu (90X)
Based on CMSSW_9_0_0_pre6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
eos problem - let's try again

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
backport of #17796

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
Closing this PR - it is superseeded by #17853

**Pull request closed without merging**
