### PR TITLE
Turn on track selection MVA in Heavy Ions

### PR DESCRIPTION
**Pull request by istaslis**
Turn on track selection MVA in Heavy Ions after payloads have been uploaded and conditions have been updated.
@mandrenguyen @yetkinyilmaz @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9391 519d275bbd5dfae8485c8e4443a6b46edec27b05

For Heavy Ions, track selection via MVA is enabled.

The code changes are satisfactory. Jenkins tests show no significant differences for all workflows except for RunHI2011wf140p53, as expected. Extended tests for workflows HydjetQ_MinBias_2760GeVwf140p0 and RunHI2011wf140p53 against baseline CMSSW_7_5_X_2015-06-01-110 using 100 events show extensive changes as expected for the change in track selection (see below).
Disk size of reco products changes marginally. The number of tracks increase by about 1-2%, but the resulting size of PF candidates decrease by roughly 5%.
CPU timing appears to improve somewhat. Selector times increase roughly 2-5 times, but amounting to only several ms/event, while PF times are reduced considerably by 5-25%, amounting to 50-400 ms/event (depending on workflow details), and seeming to result in a small net reduction in CPU time.

**wf HydjetQ_MinBias_2760GeVwf140p0**
effic140p0
effvseta
efvshits
fakerate140p0
fakevsdr
rechits140p0
all_testpr9391vsorig_hydjetq_minbias_2760gevwf140p0c_log10recopfjets_akvs4pfjets__reco_obj_energy
all_testpr9391vsorig_hydjetq_minbias_2760gevwf140p0c_log10recotracks_higeneraltracks__reco_obj_pt
all_testpr9391vsorig_hydjetq_minbias_2760gevwf140p0c_recotracks_higeneraltracks__reco_obj_eta

**wf RunHI2011wf140p53**
effvseta
etahipur
all_testpr9391vsorig_runhi2011wf140p53c_log10recotracks_higeneraltracks__rereco_obj_pt
all_testpr9391vsorig_runhi2011wf140p53c_recotracks_higeneraltracks__rereco_obj_eta

**Comment by davidlange6** [comment]
+1

**Pull request merged**
