### PR TITLE
  MET Filter update for mAOD reprocessing

### PR DESCRIPTION
**Pull request by schoef**
- The HBHE Iso Noise filter flag is promoted to a separate boolean in mAOD. 
- The eeBadSC filter is added to the recommended MET filters flag.
- Thresholds for the ecalDeadCellFilter and the ecalBoundaryEnergyFilter are updated. The latter flag is added to mAOD
- Fixing the Flag_goodVertices in mAOD
- Moving the scraping and the primary vertex filter into the RecoMet/MetFilters

This is an update of #10406

### CODE REVIEW

**Comment by schoef** [comment]
@slava
I tested already your proposal in #10406. 
I got some errors from the pluginlibraryloader in a wider test but this shouldn't be a problem of this code.
I'm done with commits, please test.

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@schoef 
Robert, you could have just updated the old PR (well, if it was easy ;) )
The errors seem legitimate:

e.g. in 4.53
```
from PhysicsTools.PatAlgos.slimming.metFilterPaths_cff   import *
  File "/tmp/cmsbuild/workspace/ib-any-integration/CMSSW_7_4_X_2015-08-05-2300/python/PhysicsTools/PatAlgos/slimming/metFilterPaths_cff.py", line 5, in <module>
    from RecoMET.METFilters.metFilters_cff import HBHENoiseFilterResultProducer, HBHENoiseFilter, HBHENoiseIsoFilter, CSCTightHaloFilter, hcalLaserEventFilter, EcalDeadCellTriggerPrimitiveFilter, eeBadScFilter, ecalLaserCorrFilter, EcalDeadCellBoundaryEnergyFilter, primaryVertexFilter 
ImportError: cannot import name HBHENoiseIsoFilter
```

it looks like you missed some commits

**Comment by schoef** [comment]
@slava77 
OK, stupid error on my side, please test.

How can I run all the test offline? I now do

runTheMatrix.py --das-options="--cache das-cache.file --limit 0" --job-reports -j 4 -s -l 1306.0,101.0,1003.0,50202.0,9.0,25202.0

I got a few file-open errors in the HI sequences but other than that seems OK.

**Comment by slava77** [comment]
@cmsbuild please test

@schoef your matrix config is good

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10604	120e850
- code changes are as expected
    - note that the good PV filter previously defined in ALCARECODtCalibHI_cff.py with a 15 cm cut is now defined in primaryVertexFilter_cfi.py with a 24 cm range in z
    - among the running modules (using prompt reco setup for run2): trackingFailureFilter and goodVertices are removed; HBHENoiseIsoFilter and EcalDeadCellBoundaryEnergyFilter are added
- same code as in 75X  and in 76X version
- jenkins tests passed and comparisons with the baseline show no relevant differences
- tested additionally with run2 prompt reco setup in CMSSW_7_4_X_2015-08-09-1100 /test area test10604/: using doubleMuon PD file from run 251721:
    - there is no significant change in CPU: the new EcalDeadCellBoundaryEnergyFilter takes ~ 5 ms/evt (HBHENoiseIsoFilter is almost invisible)
    - MEM_LIVE based on igprof is essentially unchanged: I observed a 4.5 MB increase after 10 events, but wasn't able to trace it to a modified module. Due to the change in introduced modules the call tree is slightly different and the change in memory appeared to point to untouched modules (like tracking or pixel clustering) suggesting some memory paging fluctuations
    - the list persisted products in RECO/AOD/MINIAOD is unchanged

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
@mmusich @diguida please check, AlCa signature is needed

**Comment by mmusich** [comment]
+1
clean up of `ALCARECODtCalibHI` and `ALCARECODtCalib` configurations.

**Comment by mmusich** [comment]
@slava77 sorry for the delay

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
