### PR TITLE
DQM: Remove MEtoMEComparitor

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

No idea what it does. But it seems to be unused, the sequence it is on is not mentioned anywhere. So I assume it is not used.

#### PR validation:

None, assume module is unused.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by schneiml** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the sequence removed from StandardSequences looks used nowhere within CMSSW

**Comment by fabiocos** [comment]
@schneiml @jfernan2 @andrius-k this looks unused within CMSSW, is there no use case in some standalone online application?

**Comment by schneiml** [comment]
@fabiocos not in online DQM (that would be part of CMSSW). For private things in general, there is no way for me to tell, and I don't have any hot ideas who might be using it.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
