### PR TITLE
Cleanup of exotic physics configuration and Geant4 physics lists

### PR DESCRIPTION
**Pull request by civanch**
In this PR the main interface to Geant4 Physics Lists is substantially simplified. This become possible after upgrade of CMS physics for magnetic  monopole simulation.

Magnetic monopole physics configuration and all other exotica particle configurations are moved in one place and are controlled via flags of g4SimHits. Additional fragment is added to demonstrate list of custom parameters for Exotica simulation. 

Old CustomPhysics interfaces are preserved, a new interface CMSExoticaPhysics is added. 

This modifications are pure technical and no change in mainstream production is expected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
some increased number of differences in regression does not connected with this PR

**Comment by civanch** [comment]
@arunhep , @lpernie , would you have time to check and sign this PR. It includes many files but is only a simple interface change. One class is affected in Alignment.

**Comment by arunhep** [comment]
@civanch do we expect tracking differences because of this PR?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-05-08-1100+23165/26440/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018/Tracking_TrackFromPV.html

and vertexing differences here : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-05-08-1100+23165/26440/10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU/Vertexing_PrimaryVertexV.html

**Comment by civanch** [comment]
@arunhep , these 2222 differences seems to be in all new PR comparisons. This issue was discussed yesterday at the core meeting and was assumed to be connected with ROOT12 migration.

**Comment by arunhep** [comment]
+1
@civanch thanks !

**Comment by fabiocos** [comment]
@prebello @fabozzi this PR is strictly speaking a technical change of Geant4 interfaces, but it would deserve a test of GEN-SIM, as it affects so many classes at the same time.
@civanch do you have more extensive technical changes in the pipe on the short term?

**Comment by civanch** [comment]
@fabiocos , yes, I have for 10_2 two extra technical PRs, which should not modify simulation histories (as this PR).  To avoid mess with other developments, technical modifications are proposed one at the time. The next will follow, when this one will be merged. In these cases, no difference in regresion is enough to confirm that PR is OK (unfortunately we have 2222 unrelated différences here due to ROOT). Two extra PRs not yet proposed are 1) Calorimer sensitive detectors cleanup 2) Restoring watcher functionality.

Also there is a configuration change (Geant4 tracking in magnetic field), which will bring about 10% CPU speedup but will change simulation histories, so  this one will need full validation.

**Comment by civanch** [comment]
@fabiocos , I still think this PR does not need any special tests, because it basically take few lines of code concerning magnetic monopole from each Physics List and move it into one central place. Because we have many Physics Lists classes it is many identical modifications. All concern exotica simulation, not mainstream, which should not be affected at all. Few other modifications are automatic triggered by code-checks. Unfortunately, due to ROOT migration we have 2222 differences unrelated to this PR.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
