### PR TITLE
New tune snippets

### PR DESCRIPTION
**Pull request by pgunnell**

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @pgunnell - please clarify the plans that require these to be part of the release? Thanks

**Comment by perrozzi** [comment]
I would say that the basic tune snippets have always been included in the
release,
cfr
https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/Pythia8CUEP8M1Settings_cfi.py

**Comment by davidlange6** [comment]
Presumably that was done to include them in relval. Is that the plan? (it would be a good plan, but maybe its good just to get the entire plan requested at once) @fabozzi

**Comment by perrozzi** [comment]
I think there is at least another reason.
In case the tune snippet is not included in CMSSW, for each and every cfg you need to add it manually or download it as a separate file. I think it would be very error prone.
Have a look at this (random) example
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/HIG-RunIISummer15GS-02869

**Comment by fabozzi** [comment]
@perrozzi 
Looking ahead, we will need to include the new tune (currently your proposal is CP5) in 2017 MC relvals. And for this we need the corresponding cfg fragment to be deployed in the release as well, right?

**Comment by perrozzi** [comment]
@fabozzi yes indeed

**Comment by perrozzi** [comment]
fyi, we already have requests from lumi trying to produce events with the new tunes, writing them by hand and not getting them right.
I repeat, I think this snippets need to be in the release.
Do you have comments?

**Comment by efeyazgan** [comment]
And it should be all 5 tunes, not only the central one.

**Comment by efeyazgan** [comment]
@davidlange6 when do we expect this to be merged?

**Comment by perrozzi** [comment]
Hi David, this has become urgent, can you please merge or comment?
Thanks

**Comment by davidlange6** [comment]
lets discuss in the release meeting as I seem not to understand fully

**Comment by davidlange6** [comment]
+1

**Pull request merged**
