### PR TITLE
Extend EventSetup produce method return types

### PR DESCRIPTION
**Pull request by wddgit**
Allow the produce functions of EventSetup ESProducers to
return unique_ptr &lt; const T &gt; and shared_ptr &lt; const T &gt;
without having to register const T in addition to registering T.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
please test
given the large number of reported differences with base line, best to see if they were caused by other pull requests.

**Comment by fabiocos** [comment]
@wddgit this PR needs to be rebased

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
unit test is failing IB too due to root update.

**Pull request merged**
