### PR TITLE
Ecal PayloadInspector

### PR DESCRIPTION
**Pull request by depasse**
Tests for Ecal PayloadInspector for Pedestals and ChannelStatus

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
hello @depasse ,
by deploying your two commits in the DEMO working area,
I find there's a problem with the discovery of the plugins you've added, discovery which is carried out by the python script which is run ~daily by the cmsDbBrowser to register the payload-inspector dedicated plugins in the existing CMSSW releases. 

You find below instructions to run the registration script, and reproduce the error and test your fix to the code.
Please take a look at the examples which were presented in the tutorial and try to https://indico.cern.ch/event/626460/contributions/2542086/ reflect that structure.

```
cd /afs/cern.ch/user/f/franzoni/public/4alca/CMSSW_9_1_0_pre2/src
[in place of this path you need to go to your development area including the plugins you want to add]

cmsenv
/afs/cern.ch/user/f/franzoni/public/4alca/getPayloadData.py --discover
```

**Comment by depasse** [comment]
I have changed the predefined plugin EcalPed_PayloadInspector by EcalPedestals_PayloadInspector : where must I declare the new plugin name ?
Otherwise 
/afs/cern.ch/user/f/franzoni/public/4alca/getPayloadData.py --plugin pluginEcalChannelStatus_PayloadInspector --plot plot_EcalChannelStatusEBMap --tag EcalChannelStatus_v1_hlt --time_type Run --iovs '{"start_iov": "291318", "end_iov": "291318"}' --db Prod --test > channeltest   WORKS WELL : json is created  
BUT
$ /afs/cern.ch/user/f/franzoni/public/4alca/getPayloadData.py --plugin pluginEcalPedestals_PayloadInspector --plot  plot_EcalPedestalEEM12Map --tag EcalPedestals_hlt --time_type Run --iovs '{"start_iov": "283019", "end_iov": "283019"}' --db Prod --test > pedtest
Traceback (most recent call last):
  File "/afs/cern.ch/user/f/franzoni/public/4alca/getPayloadData.py", line 178, in <module>
    iovs = deserialize_iovs(args.db, args.plugin, args.plot, args.tag, args.time_type, json.loads(args.iovs))
  File "/afs/cern.ch/user/f/franzoni/public/4alca/getPayloadData.py", line 28, in deserialize_iovs
    plugin_obj = import_module(plugin_name)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/external/python/2.7.11-mlhled2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dynamic module does not define init function (initpluginEcalPedestals_PayloadInspector)

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
hello @depasse 
thanks for addressing the registration name issue.

I've downloaded your updated branch and deployed in the DEMO working area 
( reminder: we're happy to do this to help, on a best effort basis, to speedup the commissioning of new PI plots )
and deployed your commits in a locally installed CMSSW release 
which is used for PI (at the moment) by the dev version of the browser.

Please use this instance of the cmsDbBroswer https://cms-conddb-dev.cern.ch/cmsDbBrowser/ 
to look look at your plots under the DEMO "release"
and report here if the content is as you expect it

We'll proceed with the signing of this PR, then .


@arunhep

**Comment by franzoni** [comment]
example: https://cms-conddb-dev.cern.ch/cmsDbBrowser/payload_inspector/Prod/DEMO/eyJ0YWciOiJFY2FsUGVkZXN0YWxzX0xlZ2FjeTIwMTZfdGltZV92MyIsInBsb3QiOiJwbG90X0VjYWxQZWRlc3RhbHNFQlIxMiIsInBsdWdpbiI6InBsdWdpbkVjYWxQZWRlc3RhbHNfUGF5bG9hZEluc3BlY3RvciIsImlvdnMiOnsic3RhcnRfaW92IjoiNTQwMDM1MjMzNDUwMjk1Mjk2MCIsImVuZF9pb3YiOiI1NDAwMzUyMzM0NTAyOTUyOTYwIn19

**Comment by depasse** [comment]
Hi Giovanni,

yes the machinery works correctly.  It is a first step.
We'll see what we can do with the .png method option (and the possibility to plot the diff between 2 IOVs would be an appreciated tool, too)
Thanks a lot for your help.

Pierre
________________________________

**Comment by ggovi** [comment]
+1

**Comment by depasse** [comment]
Superseded by #18519

**Pull request closed without merging**
