### PR TITLE
Run2-TB34 Update some of the code for material budget calculation and re-arrange

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Debugged the material budget part and in course of that re-arranged the code between src and plugin area

#### PR validation:

Tested the code by running for material budget and got acceptable results

#### if this PR is a backport please specify the original PR:

Need to be added to master. No back porting is required

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

the proposed test cfg runs smoothly

**Pull request merged**
