### PR TITLE
get trigger type via TCDS for l1dqm 74x

### PR DESCRIPTION
**Pull request by danduggan**
updating the call for the event type and accessing the tcds payload, same as #8190 but for 74x

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
+1
thanks @danduggan

**Comment by ktf** [comment]
Please fix the title.

**Comment by danduggan** [comment]
@ktf, better?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
