### PR TITLE
[14_0_X backport] Produce sMajor, sMinor in EgammaHLTClusterShapeProducer

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/43885
Useful for phase2 HLT studies of displaced e/gamma paths.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
