### PR TITLE
Add layer counting capability to PixelActivityFilter

### PR DESCRIPTION
**Pull request by JanFSchulte**
Backport of #22951 

Adds possibility to cut on number of pixel layers with clusters for the 90m beta* run.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by venturia** [comment]
Have you considered the possibility to add a black list of modules (detid) not to be considered when the number of hits are computed?

**Comment by JanFSchulte** [comment]
@venturia No, I have never considered this. So far there has been so request from the users of this filter to be able to do this.

**Comment by venturia** [comment]
Since I have understood that the people interested have to tune the cuts, I am wondering if rejecting noisy modules could be part of the tuning process and, therefore, this feature could be useful

**Pull request merged**
