### PR TITLE
Add electrons from HGCAL in the pfCandidate collection

### PR DESCRIPTION
**Pull request by rovere**
The previously saved collection is created before merging the Barrel and HGCAL-related, sim-driven, components together. The newly saved collection will contain all pfcandidates that should be used to perform physics studies.
This will only affect PhaseII workflows. I expect no regression and very tiny effect on the event size of the final ROOT file.

Also, electrons built within the HGCAL volume were not saved into the particleFlow pfCandidate collection, causing strange effects (artificial MET, missing JETs etc...). Now they are forced into the final collection.

@malgeri, @cseez, @felicepantaleo @kpedro88 

Backport of #20614

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
backport of #20614

**Comment by kpedro88** [comment]
please test

**Comment by rovere** [comment]
Electrons were not part of the final particleFlow candidate collections since ged* collections are empty for the HGCAL case. We force them to be included, instead. The effects are quite evident from, e.g., ZEE sample 0PU (black with this fix, blue w/o, basically the current release):
screenshot 2017-09-22 12 32 37

It is clear that we have a shoulder in the MET due to the fact that, when one (or both) electrons are within the HGCAL acceptance, they are missing from the pfCandidates and they create fake MET.

The same argument holds for the JET distribution that had a drop in the HGCAL eta region that this PR will fix (mind, plots are normalized by area):
screenshot 2017-09-22 12 42 05

With this fix, I'd expect people to be able to carry out meaningful physics studies using particleFlow pfCandidates

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20615	a9e1211
- backport of #20614 with changes identical to already merged master version https://github.com/cms-sw/cmssw/pull/20614	c55b98d; needed for HGCAL TDR release
- jenkins tests pass and comparisons with baseline show about the same differences as was seen in the master PR testing, starting from PF candidate content adding electrons

**Comment by davidlange6** [comment]
merge

**Pull request merged**
