### PR TITLE
Various small fixes on MET (90X)

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #16712 for 90X

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by mmarionncern** [comment]
Extra small fixes are needed, unwanted behaviors spotted during late tests

**Comment by monttj** [comment]
+1

**Comment by mmarionncern** [comment]
Fixes done, ready to resume the signature validation

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16713 d864ec1
- changes are in line with the description (in 81X PR). The standard production workflows are minimally affected: shiftedPatJetRes\* modules now consume ak4GenJetsNoNu instead of slimmedGenJets which differ in numerical precision and also in the pt threshold. All other changes appear to affect analysis recipes setups.
- jenkins tests pass and comparisons with baseline show differences in METUnc_JetRec{Up,Down} plots
- higher stat test on ttbar PU35 (1K events from 8_1_0 relval) show only minor reshuffling in slimmedMETs and slimmedMETsPuppi METUnc_JetRec{Up,Down}  plots.

@mmarionncern 
is it intentional that the method applied in standard PAT/miniAOD production runMetCorAndUncForMiniAODProduction has no distinction for runOnData true/false?
Its companion runMetCorAndUncFromMiniAOD has runOnData propagated appropriately.

**Comment by mmarionncern** [comment]
@slava77 That boolean is so far only used to remove the storage of the getMET in the patMET objects. This is handled by the external configuration options already existing in cmssw for the miniAOD production.
However this is true we could make it configurable as well for the runMetCorAndUncForMiniAODProduction if some people need it in the future

**Pull request merged**
