### PR TITLE
uMNio data skipping implemented for urgent HLT patch

### PR DESCRIPTION
**Pull request by Spudmeister**
This patch to the HcalUnpacker.cc is needed for the HCAL laser operations in global

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
For HLT online? Then we'd need a PR for 80X also!

**Comment by slava77** [comment]
Some more details are needed with probably a link to a presentation (or/and an email with run coordination included with details and when this is needed).

**Comment by Spudmeister** [comment]
I had intended this pull request to be for 8_0_X, as I based my changes on 8_0_X.  Is there a way to choose what release the pull request is for?

**Comment by slava77** [comment]
On 4/20/16 4:14 PM, Spudmeister wrote:
> I had intended this pull request to be for 8_0_X, as I based my changes
> on 8_0_X. Is there a way to choose what release the pull request is for?
> 

target branch can not be changed after PR is created.
You will need to close one of the 81 PRs you made and create a new for 80X
There is a drop-down menu (or edit in the URL) of the target release
branch to be used before submission

**Comment by slava77** [comment]
@cmsbuild please test

@Spudmeister what's the ETA for 80X PR?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14158	9f195f4
- HCAL unpacker to skip unpacking calibration laser PIN diode inputs coming in the same FED stream.
- jenkins tests pass and comparisons with baseline show no difference (all inputs so far were apparently with getFormatVersion == 1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
