### PR TITLE
Add `pixelgpu` online DQM client and augment DQM/Integration unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a follow-up to my previous PR https://github.com/cms-sw/cmssw/pull/41939 and to the TSG ticket https://its.cern.ch/jira/browse/CMSHLT-2846.
The main goal is to add `DQM/Integration/python/clients/pixelgpu_dqm_sourceclient-live_cfg.py`: a new DQM online client designed to monitor the GPU and CPU Pixel collections from within the  `streamDQMGPUvsCPU` stream. 
At the moment only the `SiPixelRawDataError` collections are monitored by `SiPixelPhase1RawDataErrorComparator`, but in future, once more event products could be persisted after the ongoing `alpaka` migration, also other clients that are currently run within the HLT menu itself could be moved here.
I profit of this PR to include the new GPUVsCPU client (and the two existing ECAL and HCAL ones) in the battery of unit tests.
For data a corresponding PR to `cms-data` has been created (https://github.com/cms-data/DQM-Integration/pull/4) in order to supply the necessary input files (albeit - alas - these files lack the proper pixel collections (`SiPixelRawDataErroredmDetSetVector_hltSiPixelDigisFromSoA_*_*` and `SiPixelRawDataErroredmDetSetVector_hltSiPixelDigisLegacy_*_*`) that became available after [CMSHLT-2846](https://its.cern.ch/jira/browse/CMSHLT-2846) was closed).

#### PR validation:

Run successfully:
```
scram b runtests_TestDQMOnlineClient-ecalgpu_dqm_sourceclient
scram b runtests_TestDQMOnlineClient-hcalgpu_dqm_sourceclient
scram b runtests_TestDQMOnlineClient-pixelgpu_dqm_sourceclient
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but to be backported for deployment in 2023 data-taking.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-data/DQM-Integration/pull/4

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test
  * even though unit tests passed [OK](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-98ba67/34226/unitTests/failed.html)

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 could you please have a look to this one and corresponding https://github.com/cms-data/DQM-Integration/pull/4 ?

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
