### PR TITLE
Test also ESGetToken in ESTestAnalyzers

### LINKED ISSUE #28709: ESGetToken does not work in TestProcessor
A `TestProcessor` configuration where the module-to-be-tested reads an ESProduct from an ESProducer appears to fail if the module retrieves the product with `ESGetToken`. This behavior is demonstrated in #28708.

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR suggests to test also ESGetToken to retrieve ESProducts in ESTestAnalyzers.

Fixes #28709.

#### PR validation:

~~Currently the TestProcessor unit test fails.~~ Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

To demonstrate failure

**Comment by Dr15Jones** [comment]
@makortel the test did not appear to fail.

**Comment by makortel** [comment]
Right, because the changes did not trigger tests of `FWCore/TestProcessor`. If you want, I can add a dummy change in there to trigger the tests.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
TestProcessor tests are now run successfully

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
