### PR TITLE
[12_5_X] [L1T] Backport of: phase-2, update trackjet simulation

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

This PR contains all the improvements in the track jet code and the improved tagging of displaced jets (and their selection):
The work was presented in many GTT through the years but a summary is also presented in the last GTT meeting:
https://indico.cern.ch/event/1146596/

Several bug fixes are included and also an optimization of the code itself that makes the code 2 times faster than before. In the last slide there is a validation of the improved code.

#### PR validation:

code-format, code-checks, local validation

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38337. We need it for our Phase-2 MC production

### CODE REVIEW

**Comment by cecilecaillol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38337

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by AdrianoDee** [comment]
+upgrade
- backport of https://github.com/cms-sw/cmssw/pull/38337;
- needed for L1T MC production in 12_5_X.

**Comment by cecilecaillol** [comment]
please test

**Comment by AdrianoDee** [comment]
+upgrade
- back port of https://github.com/cms-sw/cmssw/pull/38337;
- review comments applied here also.

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
