### PR TITLE
[14_0_X] Fix RelMon Piecharts using `Chart.js`

### PR DESCRIPTION
**Pull request by AdrianoDee**
Plain backport of https://github.com/cms-sw/cmssw/pull/44977.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44977

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
