### PR TITLE
Changing default values of Calo Layer 2 DQM D/E Agreement plots (L1TEMU)

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Changing default values of CaloLayer2 Agreement plots to be zero in the edge case where the histograms are not filled.
Requested in: https://its.cern.ch/jira/browse/CMSLITDPG-770

Backport of #24884

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
Hi @vukasinmilosevic, could you please make sure that subsystem name appears in the title of the PR?

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

integrated successfully in master, used in online, looks safe to move forward

**Pull request merged**
