### PR TITLE
[L1T][DQMOffline] L1TEGammaOffline fixes (CMSLITDPG-585)

### PR DESCRIPTION
**Pull request by kreczko**
Jira issue: https://its.cern.ch/jira/browse/CMSLITDPG-585

Fixes:
 - early stopping in probe matching
 - adjusted cuts for efficiency vs &eta;/&phi;

@thomreis I am not quite sure if the cuts are as requested, could you please check?

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
@kreczko 
are we still waiting for @thomreis to answer 
> @thomreis I am not quite sure if the cuts are as requested, could you please check?

or are we good to go ?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
the problem seems related to a system-wide trouble, not to this specific PR

**Comment by fabiocos** [comment]
please test

**Comment by thomreis** [comment]
Hi @kreczko 
now that the master points to 10_3_X you might also want to make a PR to the 10_2_X branch.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
