### PR TITLE
Adding postLS2 (2019) design key and 2019 workflow updates

### PR DESCRIPTION
**Pull request by arunhep**
This PR will bring two changes : 

- adding of phase1_2019_design key with the GT containing design conditions for 2018 with HCAL electronics map update for 2019.
- update of 2019 workflows to switch them to consume 2019 GT keys

# Summary of Global Tag updates

## Upgrade

   * **PostLS2 design scenario** : [100X_postLS2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_design_v1) as [100X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_design_v1/100X_upgrade2018_design_IdealBS_v1): 
      * first GT for postLS2 design scenario with an update of HCAL electronics map. All other conditions are same as 2018 design.

@kpedro88 @abdoulline

### CODE REVIEW

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
thanks @arunhep

**Comment by kpedro88** [comment]
+1

**Comment by arunhep** [comment]
@fabozzi @GurpreetSinghChahal can you please sign this?

**Comment by arunhep** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
