### PR TITLE
[HGCAL] Fix bugs in Validation plotting

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR fixes two bugs in the Validation plotting scripts by:
  - Differentiating plot names
  - Skipping TH2 objects when computing ratios

#### PR validation:

`makeHGCalValidationPlots.py` with any possible option

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@lecriste can you please add subsystem [HGCAL] into the title of the PR?
Thanks

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
