### PR TITLE
Phase2-hgx327G Remove and modify many more test scripts in Geometry/HGCalCommonData in view of retaining only stuffs for V16, V17 and TB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove and modify many more test scripts in Geometry/HGCalCommonData in view of retaining only stuffs for V16, V17 and TB

#### PR validation:

Tested the modified scripts locally. They are not part of any unit test or any production sequence

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Technical PR on test script of HGCal. No change is expected.

**Comment by rappoccio** [comment]
+1

Technical PR.

**Pull request merged**
