### PR TITLE
Several improvements to L1 tracking code

### PR DESCRIPTION
**Pull request by tomalin**
#### PR description:

This consists of several improvements from the Phase 2 L1 tracking group.

1. "combined" versions of the prompt & displaced tracking are now run by default, corresponding to the current firmware choice. 
2. Serious bugs were fixed in the duplicate track removal. In addition, dependencies of the "combined module" version of the duplicate removal "wiring map" on the older non-combined module have been removed.
3. The L1 Track Quality variable is digitized according to the latest agreement.
4. The tracking performance plotting ROOT macro L1TrackNtupleMaker.C now prints both fake track rate and duplicate track rate in its summary printout.
5. For the HYBRID_NEWKF version of the L1 tracking, which corresponds to FW, but is not the current default for L1 trigger studies, the Kalman Filter Track fit EDProducers have been significantly rearranged, with the advantage that the output TTTrack collection is now created from the end of the chain, and so includes the TrackQuality variable.
6. Truncation has been reduced in the MatchProcessor module.

N.B. The changes to the duplicate track removal algorithm in this PR are dependent on the changes in cms-data from this PR https://github.com/cms-data/L1Trigger-TrackFindingTracklet/pull/6 , so the two PRs must be introduced into the same version of CMSSW.

### CODE REVIEW

**Comment by tomalin** [comment]
This PR should be noted by @aehart and @skinnari and @zdemirag .

**Comment by tomalin** [comment]
This is waiting for one additional improvement to the code from the L1 tracking community, before I remove the "Draft" tag.

**Comment by aloeliger** [comment]
test parameters:
- pull_requests = https://github.com/cms-data/L1Trigger-TrackFindingTracklet/pull/6

**Comment by tomalin** [comment]
Closing, as replaced by rebased PR https://github.com/cms-sw/cmssw/pull/46360 .

**Pull request closed without merging**
