### PR TITLE
HGC Clustering Checkpoint

### PR DESCRIPTION
**Pull request by lgray**
This is the preliminary version of the merged EM + hadron clustering.

Some final investigations concerning using the expected penetration depths of charged hadrons need to be done, for instance to help stop low energy tracks earlier in the calorimeter. This is very important for correct functioning of the clustering in high pileup.

This PR is meant to serve as a checkpoint of this work. 
There are a few things to follow up before we commit this for central production.

@pfs @vandreev11

### CODE REVIEW

**Comment by fratnikov** [comment]
@lgray What is the status of this PR? Does it need to be merged?

**Comment by lgray** [comment]
Hi Fedor, yes it can be merged.

**Comment by fratnikov** [comment]
"This pull request contains merge conflicts that must be resolved." Can it be resolved?
What is relation of this PR to #7043 (which I guess is merged already)?

**Comment by lgray** [comment]
Ah, it looks like something changed in configs. I'll rebase soon and update.

**Comment by lgray** [comment]
Working on the rebase of this now.

**Comment by lgray** [comment]
@fratnikov @mark-grimes Rebase will come in a moment, I'll close this PR and open a new one. If it's possible, could this be included in SLHC23?

**Pull request closed without merging**
