### PR TITLE
Phase2-hgx193 PhUpdate HGCal geometry for the support structure

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The support structure of HGCal and absorber layers had issues in v10 geometry and this is addressed in this PR. So it will affect D41 workflow

#### PR validation:

Tested with runTheMatrix.py for the workflow 29034.0

#### if this PR is a backport please specify the original PR:

Aiming for the next pre-release of 10_6_0 (pre5) and MC productions with V10 geometry of HGCal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade
changes confined to D41 workflow, as expected, and appear quite minor

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
