### PR TITLE
Run2-hcx164 Get a list of merged depth for a given eta, phi cell

### PR DESCRIPTION
**Pull request by bsunanda**
Given the DetId to a topology class it returns a vector of depth indices which are merged to the neighboring eta-phi tower

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Most likely the code is included in #21683 - in that case let that PR to go ahead and then I shall close this

**Comment by ianna** [comment]
@bsunanda - yes, please, close this PR. Thanks.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
closing as agreed above

**Pull request closed without merging**
