### PR TITLE
run stage1 emulator for l1t dqm 75x

### PR DESCRIPTION
**Pull request by jingyucms**
similar 9118 (https://github.com/cms-sw/cmssw/pull/9118) but for 75x

### CODE REVIEW

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
ciao @jingyucms 
please remove the DQMStore parameter from the configs. as far as I can see it is not used and not needed. please also rename the flag stage1_layer2_ to stage1_layer2 so that the naming convention is consistent.
there are also a number of methods which are empty and can just be removed.

then one question. is the sequence l1Stage1HwValEmulatorMonitor supposed to be run? I don't see it included anywhere. please clarify.

thanks in advance,
F.

**Comment by jingyucms** [comment]
ciao @deguio 
so l1Stage1HwValEmulatorMonitor is intended to be included in the master config file. So as I create a new  DQM/Integration/python/test/l1tstage1emulator_dqm_sourceclient-live_cfg.py . It is parallel to DQM/Integration/python/test/l1temualator_dqm_sourceclient-live_cfg.py. It will create a folder called L1TEMUStage1 dedicated for stage1 emulator comparison plots by running l1Stage1HwValEmulatorMonitor

**Comment by deguio** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
+1
@jingyucms if you want this to be run in the online, please make this PR with the last change you made available for 74 as well.
thanks,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
