### PR TITLE
Razor hlt 0t dqm 76x

### PR DESCRIPTION
**Pull request by jmduarte**
Razor HLT DQM changes for 0T menu for 76X

### CODE REVIEW

**Comment by jmduarte** [comment]
@danduggan @deguio @davidlange6 

Hello,

Can one of you request tests so we can merge this PR? This is needed for the merger of the razor HLT paths for the 0T menu as seen in this JIRA ticket

https://its.cern.ch/jira/browse/CMSHLT-571

Thanks!

Javier

**Comment by perrotta** [comment]
please test

**Comment by jmduarte** [comment]
Hello, 

I update all three pull requests with an additional commit 83109d352db9529f2e879d7675cdc05b3fd57f03 that should fix the issue. Please re-test.

Thanks,
Javier

**Comment by deguio** [comment]
please test

**Comment by jmduarte** [comment]
Can this be merged or are there any other issues?

Thanks!

Javier

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
