### PR TITLE
L1T DQM Revert "Remove L1TMuon data."

### PR DESCRIPTION
**Pull request by rekovic**
PR for L1T DQM TEST.

Revert the removal of L1Trigger/L1TMuon/data directory which supposed ly caused L1T DQM. 

It is not clear why this was not a problem in the Matrix tests.

Detail:
This reverts commit 57239ce872aab7759fd71ae6d00604f3a3b3b401.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
what is the problem you are trying to solve @rekovic ?

**Comment by rekovic** [comment]
Hi @davidlange6  
Apparently L1T DQM was failing because L1Trigger/L1TMuon/data was deleted. 

This could go in after we merge #19310, which I believe is ready.

**Comment by davidlange6** [comment]
i don't see how - please let us know how to reproduce.

**Comment by rekovic** [comment]
I agree.  
This is just a test PR for the online DQM.  They pull PRs to their liking .

**Comment by davidlange6** [comment]
please don't make PRs not for integration to the CMSSW repo. Thanks

**Comment by davidlange6** [comment]
-1
please close

**Pull request closed without merging**
