### PR TITLE
backports of fixes and cleanups from CMSSW_8_1_X

### PR DESCRIPTION
**Pull request by roger-wolf**
Dear colleagues, 

this is a backort of minor fixes and cleanups form 81X. the changes are very local and act only on the high level analysis and end-user part. The change in PhysicsTools/PatAlgos/python/tools/coreTools.py initiated the backport on an end-user request. 

Cheers,
Roger

### CODE REVIEW

**Comment by cvuosalo** [comment]
@roger-wolf: This PR has merge conflicts.

**Comment by roger-wolf** [comment]
Hi Carl, 
the changes to the files that I introduce are minimal and high level at the same time. My mistake might be that I applied them on top of the CMSSW_8_0_X. I could use branch belonging to the latest 80X release instead or do you have another recommendation for me? 
Cheers,
Roger

**Comment by slava77** [comment]
This branch has conflicts that must be resolved

**Comment by roger-wolf** [comment]
Hi guys, 

the conflicts do not come from my side -- it was my bad that I based this PR on a branch that seems not compatible any more with 80X. I think it is easiest for me to close this PR and to re-apply my limited number of changes on something which is compliant with 80X from the beginning. Can I retract this PR myself? (Never done/tried this so far). 

Cheers,
Roger

**Comment by slava77** [comment]
-1
superseded by #15705

**Pull request closed without merging**
