### PR TITLE
Run3-gex83L Modify the remaining calorimeter SD's to access objects from EventSetup correctly

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the remaining calorimeter SD's to access objects from EventSetup correctly

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@qliphy @perrotta All the failures are for missing input files. Please take care of that

**Comment by qliphy** [comment]
@bsunanda 

I noticed from e..g [1]
A fatal system signal has occurred: external termination request
and
Waiting for stacktrace completion failed: timed out waiting for GDB to complete.
Probably it is just a glitch. 

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c900c6/17171/runTheMatrixINPUT-results/11634.511_TTbar_14TeV+2021_Patatrack_ECALOnlyCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST/step2_TTbar_14TeV+2021_Patatrack_ECALOnlyCPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST.log

**Comment by qliphy** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch Please approve this. This is the last PR for the SD's

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@bsunanda according to the [static analyzer](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c900c6/17180/llvm-analysis/report-ee9829.html#EndPath) there is still one more file to be migrated: `/SimG4CMS/Calo/src/HcalTestAnalysis.cc`
There is no need to hold this PR for it, as it can be deferred to a forthcoming PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
