### PR TITLE
Delete old scripts accessing geometry with prior-run2 GT in Calibration/TkAlCaRecoProducers

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Following the up the migration of Geometry_cff to GeometryDB_cff (https://github.com/cms-sw/cmssw/pull/35278), proper GlobalTag needs to be set in advance. We take the chance to clean up deprecated AlCa/DB script in TkAlCaRecoProducers.

#### PR validation:

Remove deprecated scripts: Alca_BeamFit_Workflow.py, Alca_BeamSpot_Harvester.py (GR_R_38X_V9)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a back port and no back port expected.

### CODE REVIEW

**Comment by tvami** [comment]
assign tracking-pog

**Comment by mmusich** [comment]
-1 
   * superseded by https://github.com/cms-sw/cmssw/pull/39170

**Comment by ChrisMisan** [comment]
-alca

- to remove this PR from pending queue

**Comment by tvami** [comment]
@yuanchao given the PR https://github.com/cms-sw/cmssw/pull/39170 please close this one, thanks

**Comment by yuanchao** [comment]
Close for #39170 is done.

**Pull request closed without merging**
