### PR TITLE
Phase2-hgx286 Define the big partitions for next version of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Define the big partitions for next version of HGCal

#### PR validation:

Tested to see no overlaps

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
