### PR TITLE
update getPayloadData.py to python3 in sync with changing boost_python to python3

### PR DESCRIPTION
**Pull request by davidlange6**
Goes together with https://github.com/cms-sw/cmsdist/pull/7085

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
will fail without the cmsdist update 
(the tests are happening there)

**Comment by davidlange6** [comment]
hi @smuzaffar @ggovi - this PR is ready to go - if the failing unit test in the cmssw IB has eventually been fixed, we could run tests one more time if you want.

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = Alignment,CondCore,CondFormats
- pull_request = cms-sw/cmsdist#7085

**Comment by smuzaffar** [comment]
please test
@davidlange6 , lets tests it here too based on a newer IB where we have opencv and llvm using py3 only.

**Comment by smuzaffar** [comment]
@qliphy , @silviodonato this is a technical update to make this script py3 compatible. Can you please merge this and  cms-sw/cmsdist#7085 for 23h00 IB?

**Comment by qliphy** [comment]
merge

**Comment by mmusich** [comment]
It looks like the update to python3 was not complete here.
by using the options (unfortunately not tested in the unit test, that I will have to update).
```
getPayloadData.py --plugin pluginSiPixelGainCalibrationForHLT_PayloadInspector --plot plot_SiPixelGainCalibForHLTGainComparisonTwoTags --tag SiPixelGainCalibrationHLT_2009runs_ScaledForVCal_hlt --input_params '{}' --tagtwo SiPixelGainCalibration_hlt_2021_v0 --time_type Run --iovs '{"start_iov": "326851", "end_iov": "326851"}' --iovstwo '{"start_iov": "1", "end_iov": "1"}' --db Prod --suppress-output --image_plot
```

one gets:
```
Traceback (most recent call last):
File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-07-08-2300/bin/slc7_amd64_gcc900/getPayloadData.py", line 302, in <module>
shutil.copyfileobj( f, sys.stdout )
File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/shutil.py", line 202, in copyfileobj
buf = fsrc_read(length)
File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-07-08-2300/external/slc7_amd64_gcc900/bin/../../../../../../../slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
````

**Pull request merged**
