### PR TITLE
[HGCAL] Reorganizing layer cluster plots into subfolders

### PR DESCRIPTION
**Pull request by Xingfu23**
#### PR description:

The plots in the plots folder contain layer cluster plots that cannot be load or viewed in DQM GUI due to the enormous number of plots in a single layer cluster plot folder. We reorganized the layer cluster folder into subfolders so that we can check the relevant plots in DQM GUI but also have a nicer structure of the output plots.

We expect there is no change in DQM files neither in size or memory as no new histograms are created or deleted.

#### PR validation:

We have check with a ttbar workflow and plots are visible. Here is our website testing result
https://xisu.web.cern.ch/xisu/HGCValid_hgcalLayerClusters_Plots/

@apsallid  @rovere @felicepantaleo @ebrondol @lecriste

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by rovere** [comment]
@Xingfu23 thanks a lot for this improvement!

**Pull request merged**
