### PR TITLE
Improvements to CSC trigger primitives following long cosmic run at B904 (CCLUT-16)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

* Last week we took at long cosmic run, 115k events, with the B904 GEM-CSC test stand (http://cmsonline.cern.ch/cms-elog/1118979). I analyzed the CSC trigger primitives. I determined that there was a minor disagreement between firmware and emulation for the CLCT algorithm. When CCLUT is applied, the deadzone around a CLCT takes into account possible correction of the CLCT half-strip position. This has a particular effect when CLCTs are around 5 half-strips apart from each other. The CCLUT correction on CLCT1 can move them apart (in which case CLCT2 would be kept) or closer together (in which case CLCT2 is eliminated)
   - Previously: 1) find CLCT1, 2) find CLCT2, 3) apply CCLUT to CLCT1, 4) apply CCLUT to CLCT2.
   - Currently: 1) find CLCT1, 2) apply CCLUT to CLCT1, 3) find CLCT2,  4) apply CCLUT to CLCT2.
* Other changes:
   - A `PulseArray` class was introduced, largely to hide the 2D array and some of the trigger logic. This should not change anything.
   - A redundant ghost cancellation function was removed. Only the ghost cancellation function that operates on each wiregroup remains. This is also how it's done in the firmware - in parallel on each wiregroup.
   - A CLCT median timing logic was removed -  we cannot implement this in the OTMB firmware anyway.
   - Pieces of the logic in the findCLCT function or pretrigger function were put in separate functions (`markPreTriggerZone`, `markBusyZone`, `constructCLCT`, `constructPreCLCT`, `clearPreTriggers`) to make it easier to understand and maintain the code.
* Disagreements for ALCTs and CLCTs are now at the same level: about 1 in 17,000 to 20,0000 trigger primitives is off. (Although this is with cosmics.) The CCLUT code calculation is well understood. In all, there are just  7 CLCTs different. Those may be worth investigating further. Most likely, there are small differences in other parts of the CLCT algorithm (other than CCLUT).

#### PR validation:

Tested so far on the cosmic data. 

Results from short run 10k events:
[CSC_dataVsEmul_B904_Cosmic_Run_210609_142357_ArrangePatFinderAndCCLUT.pdf](https://github.com/cms-sw/cmssw/files/6789029/CSC_dataVsEmul_B904_Cosmic_Run_210609_142357_ArrangePatFinderAndCCLUT.pdf)

Results from long run 115k events:
[CSC_dataVsEmul_B904_Cosmic_Run_210701_135109.pdf](https://github.com/cms-sw/cmssw/files/6789033/CSC_dataVsEmul_B904_Cosmic_Run_210701_135109.pdf)

I will test it on 25k Run-2 data events tomorrow and attach the plots (excluding ME+1/1/9, ME+1/1/10, ME+1/1/11). There are no differences compared to https://github.com/cms-sw/cmssw/pull/34245
[CSC_dataVsEmul_CMS_Run_322022_PostAlctClctWork.pdf](https://github.com/cms-sw/cmssw/files/6793716/CSC_dataVsEmul_CMS_Run_322022_PostAlctClctWork.pdf)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@tahuang1991

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
If you could wait with merging until I've uploaded the Run-2 results. Thanks.

**Comment by dildick** [comment]
I uploaded the Run-2 results. They are the same as in #34245.

**Comment by dildick** [comment]
@civanch Do you have any questions? The only modifications I made in data formats was add more constants in DataFormats/CSCDigi/interface/CSCConstants.h

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
