### PR TITLE
Activate the production of counting TkMaps as TH2F, and changing clus…

### PR DESCRIPTION
**Pull request by ssilvado**
Hello, 

as requested I am activating the production of Number of Valid, Missing and Inactive hits as TH2F, and also changing Cluster width scale.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 is this PR ok to go in?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
