### PR TITLE
Various updates to CMSSW that are not directly related to GPU development (10.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
We are pushing to this branches the fixes and improvements to the CMSSW code that we are making during the development of the GPU algorithms, but are not GPU specific.

Various improvements to pixel-related modules
  - mark `PixelDigi` constructor as `explicit`
  - improve `SiPixelGainCalibrationOffline::getPed` exception error message

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild,  please test

**Comment by ghellwig** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
