### PR TITLE
Revert test wf 511.1

### PR DESCRIPTION
**Pull request by fabiocos**
Revert the Herwig7 + Openloops + MadGraph test workflow 511.1, systematically exceeding TimeOut limits (sometimes even after the improvements by D. Lange).
Backport of #24995

### CODE REVIEW

**Comment by fabiocos** [comment]
backport #24995

**Comment by fabiocos** [comment]
please test 

nothing to be really tested but...

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@alberto-sanchez @efeyazgan @qliphy as agreed, I move forward. Please sign it in case for reference

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
