### PR TITLE
Gem validation update

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

* Re-organizing the plots in GEM Validation
* Small bug fix in 1D efficiency plot in GEM Validation
* 2D plots in GEM Validation is not generated in default.
* New matching method between the GEM objects and muon sim hit with using GEMDigiSimLink
* The update is presented in GEM DPG general meeting ([link to the slides](https://indico.cern.ch/event/997112/contributions/4189296/attachments/2174041/3670734/19_Jan_2021_GEMValidationTool.pdf))
* Optimised for release validation

#### PR validation:

* The branch has tested with following commands to check if it works in 2 different geometry versions.
```
runTheMatrix.py -w upgrade -l 31011.0
runTheMatrix.py -w upgrade -l 23211.0
```
* The code format has applied with `scram build code-format`

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@yeckang could you please if the changes produced but your PR are consistent with what you expect? It is not clear to me from the description

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-01-22-2300+17cdf6/40950/dqm-histo-comparison-summary.html

Thanks

**Comment by yeckang** [comment]
@jfernan2 It looks okay for me. But there is small mistake in the time of fight plot range. I'm testing the fixed script now. If it looks okay, I will push it again.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
