### PR TITLE
remove access to HcalCholeskyMatrix

### PR DESCRIPTION
**Pull request by kpedro88**
After #14856, the HcalCholeskyMatrix objects are no longer used. This PR removes all the CMSSW access for these classes, based on the discussion in #14954.

Not altered in this PR:
CondFormats/HcalObjects
CondCore/Utilities

attn: @abdoulline

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Looks spurious to me...
```
----- Begin Fatal Exception 29-Jun-2016 20:14:17 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@mmusich @ggovi when you get a chance...

**Comment by kpedro88** [comment]
@mmusich @ggovi reminder

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@ggovi ping

**Comment by abdoulline** [comment]
@ggovi 
Giacomo, please approve.

**Comment by abdoulline** [comment]
@ggovi 
Giacomo, please approve.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
