### PR TITLE
Apply code checks to the OnlineDB packages

### PR DESCRIPTION
**Pull request by fwyzard**
Apply `clang-tidy` automated code changes.
Apply `clang-format` automated code formatting.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@fwyzard @cms-sw/core-l2 sorry for the silly question. Why didn't this PR apply the code-format fixes to ` OnlineDB/EcalCondDB/interface/IRunIOV.h ` ? From #31322 it looks like these fixes should have been applied https://github.com/cms-sw/cmssw/pull/31322/commits/d328dc555015969ad2047bcb9e6a7a2f78cd177a

**Comment by makortel** [comment]
Doing
```sh
cmsrel CMSSW_11_1_0_pre7 # released May 8th
cd CMSSW_11_1_0_pre7/src
cmsenv
git cms-addpkg OnlineDB/EcalCondDB
clang-format -i OnlineDB/EcalCondDB/interface/*
```
does change `OnlineDB/EcalCondDB/interface/IRunIOV.h` as in https://github.com/cms-sw/cmssw/commit/d328dc555015969ad2047bcb9e6a7a2f78cd177a. Just guessing but maybe `clang-format` didn't get run on that file for some reason?

**Pull request merged**
