### PR TITLE
Fix expression evaluator unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Added missing 'const' to match the `reco::genericExpression::operator()` signatures. This should fix ExpressionEvaluatorUnitTest.
use CMSSW_BASE/tmp to create tmp `VI_*` files

### CODE REVIEW

**Comment by smuzaffar** [comment]
FYI @VinInn

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
unit tests now runs fine
```
===== Test "ExpressionEvaluatorUnitTest" ====
10 4
0 1
An exception of category 'ExpressionEvaluator' occurred.
Exception Message:
error in opening patch area for /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-07-2300 

0 1
0,1,2,3,4,5,6,7,89,,10,...,1598,1599,
If HERE OK

---> test ExpressionEvaluatorUnitTest succeeded
```

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27723	d0fb95f
- technical; most of the fix is in https://github.com/cms-sw/cmsdist/pull/5143	2bdc04e and the dependent piece in https://github.com/cms-sw/cmssw-config/compare/V05-08-63...V05-08-65
- jenkins tests pass

**Comment by smuzaffar** [comment]
@fabiocos , can we get this in.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
