### PR TITLE
GEM Geometry from DB Builder Cleanup

### PR DESCRIPTION
**Pull request by ianna**
* Partial commit of GEM geometry cleanup

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@calabria - this should address @davidlange6 comment on #19018
 
Note, this is only a part of a more extensive code cleanup. If the PR tests pass, please merge the commit to your branch and I'll close this one.

**Comment by slava77** [comment]
@ianna @calabria 
is this meant to be a replacement to #19018 that has to go in first?

If instead, it's a contribution to #19018 , please close this and submit the changes as a PR to calabria:for2017SliceTest

Thank you.

**Comment by ianna** [comment]
@slava77 - it is a contribution to #19018

@calabria - shall I make a PR to your branch or will you pick up the commit?

**Comment by calabria** [comment]
@ianna thanks a lot. I am going to pick up your update.

**Comment by slava77** [comment]
-1
relevant new commit from here (	0a976ac ) was already picked up in #19018

**Pull request closed without merging**
