### PR TITLE
relval updates after 7_6_0 campaign

### PR DESCRIPTION
**Pull request by hengne**
Major updates:
- update fullSim and fastSim mixing and premixing inputs.
- update golden json file for 2015 run2 data
- add high stats (~100k stats) ZMM and TTbar noPU and PU25ns workflows in highstats set. To be run in major X_Y_0 releases for various POGs studies. Can also be produced on demand for pre-releases with sufficient motivation but will not do that for pre-releases by default.
- add high stats HLTPhysics data 2015D workflow in highstats set for HLT studies.
- add workflow to test re-miniAOD using AOD as input, successful done, but cannot run DQM/Harvest in the 2nd miniAOD step because AOD input data contents missing part of the info that needed for the RECO-miniAOD comparison, which exists RECO datacontent not in AOD data contents by design.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by davidlange6** [comment]
"add workflow to test re-miniAOD using AOD as input, successful done, but cannot run DQM/Harvest in the 2nd miniAOD step because AOD input data contents missing part of the info that needed for the RECO-miniAOD comparison, which exists RECO datacontent not in AOD data contents by design."

I would argue that this is a bug. The miniAOD is derivable from AOD so its monitoring should be too. What exactly is missing?

**Comment by hengne** [comment]
@davidlange6 Hi David, will the updates here be automatically ported to 8_0_X? If not, I can make a PR to 80X to port these updates. Thanks! 
best, Hengne

**Comment by hengne** [comment]
@davidlange6 no, this is not a bug, this is by design a difference in the
RECO and AOD data contents.  If I use RECO file as input (with RECO
datacontents), the DQM for miniAOD works. But if use AOD datacontents as
input, it fails. I have spent quite some time to understand this. And found
the origin is the PFTools, where the save observable from RECO and miniAOD
are compared.

https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/Validation/RecoParticleFlow/python/miniAODDQM_cff.py

and an exception looks like this:

----- Begin Fatal Exception 29-Oct-2015 18:31:00 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 3 event: 101
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module PFJetDQMAnalyzer/'JetValidation1'
   [3] Calling produce method for unscheduled module
PATJetSlimmer/'slimmedJets'
   [4] Calling produce method for unscheduled module
PATJetSelector/'selectedPatJets'
   [5] Calling produce method for unscheduled module
PATJetProducer/'patJets'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::BaseTagInfo
Looking for module label: pfSecondaryVertexTagInfos
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound
exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options"
PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

and if I trace down to the data contents I can find the RECO and AOD data
contents are indeed different:

https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoBTag/Configuration/python/RecoBTag_EventContent_cff.py

One can add these RECO contents in AOD, or can remove those DQM plots using
RECO contents. But what ever the solution is, it is a later story not much
relevant to the exercise here: the goal is to make sure running the miniAOD
with AOD data contents can work (no crash). So the second DQM of the 2nd
miniAOD step is something in the next step.

**Comment by davidlange6** [comment]
an 80x PR would be much more efficient. Thanks!

**Comment by davidlange6** [comment]
I think its a big design flaw. don’t you think its useful to both run an aod->miniAod conversion workflow (one that is desired to be supported for production, which is not the case of reco->miniAod) and to monitor it?

**Comment by hengne** [comment]
I agree. I will see if I can figure this out.

**Comment by hengne** [comment]
@fabozzi ping ;-)

**Comment by fabozzi** [comment]
+1

**Pull request closed without merging**
