### PR TITLE
fix wrong auto-forward-port of RecoTLR of  #11741 

### PR DESCRIPTION
**Pull request by slava77**
auto-forward-port of  #11741  made multiple wrong choices.
It's good that in this case the wrong choices would break compilation and will be noticeable.

Note for the future: better backport than forward port (not sure it would have helped though in this case)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar @davidlange6 
it would be nice to merge this before the 1100 IB will be cut

**Comment by smuzaffar** [comment]
@slava77 , while tests are still running I see this error for relvals
```
++ timeout 7200 runTheMatrix.py '--das-options=--cache das-cache.file --limit 0' --job-reports -j 4 -s -l 1306.0,101.0,1003.0,50202.0,9.0,25202.0
Deprecated, please use -l limited
processing relval_standard
ERROR in Step
overwritting RunHLTPhy2015C not allowed
```

**Comment by davidlange6** [comment]
Argh. Is a new mess with forward porting the configuration/pyreleasevalidation changes that I merged into 75 today. 
________________________________________

**Comment by slava77** [comment]
ok, it looks like the IB is dead for more reasons than just my 75X PR auto forward port

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@davidlange6  it's still open

**Pull request merged**
