### PR TITLE
Backport of #12523: Small bugfixes in alignment workflows

### PR DESCRIPTION
**Pull request by hroskes**
- fix the bug I mentioned in the alignment meeting yesterday in the systematic misalignment tool
  - new geometry comparison for applying "misalignment" with no shift, I think what's left is rounding errors:
    image
- fix bug that Gregor mentioned last week, of not copying png and pdf files
- a couple of other minor bugs

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ghellwig** [comment]
Any reason why this has not been merged, yet? I see that a 76X release has been created in the mean time, if I am not mistaken.
-Gregor

**Comment by davidlange6** [comment]
+1

**Pull request merged**
