### PR TITLE
[Do not merge]Testing draft PR

### PR DESCRIPTION
**Pull request by smuzaffar**
please ignore this PR. This is just to test bot changes for handling draft PRs

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by smuzaffar** [comment]
bot changes for draft Pr looks good.
@iarspider , what do you think about the `fully signed message`? Should we also disable it for draft PRs?

**Comment by iarspider** [comment]
> bot changes for draft Pr looks good. @iarspider , what do you think about the `fully signed message` [#46933 (comment)](https://github.com/cms-sw/cmssw/pull/46933#issuecomment-2541816289)? Should we also disable it for draft PRs?

Good question. We can delay posting that message (and adding fully-signed label), and instead post a message prompting user to remove draft status. In that case we can even skip welcome message completely?

**Comment by smuzaffar** [comment]
> We can delay posting that message (and adding fully-signed label), and instead post a message prompting user to remove draft status.

sounds good to me.

> In that case we can even skip welcome message completely?

No, I would like to see the welcome message. Bot should add the welcome message as soon as draft PR is converted to normal PR.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
looks good

**Pull request closed without merging**
