### PR TITLE
Add LogWarning in OnlineBeamSpotESProducer::checkSingleBS

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Title says it all.
Minor improvement to add a` LogWarning` (which was forgotten in the past implementation of the class) in case we fall back to PCL in the `checkSingleBS` method of `OnlineBeamSpotESProducer`.

#### PR validation:
Code compiles.

#### Backport:
Not a backport, no backport needed.

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
hold

- I have one minor thing to add, I'll do it tomorrow!

**Comment by francescobrivio** [comment]
unhold

 - minor fix applied in https://github.com/cms-sw/cmssw/pull/45565/commits/4905ad338f7165d98c15ad394adb5f6042235ffe

**Comment by francescobrivio** [comment]
@cmsbuild please test

- in any case I'm only changing the logwarning messages, so I don't expect any change in Physics

**Comment by francescobrivio** [comment]
Failures in DQM comparisons come almost exclusively from `12834.7` which is known from https://github.com/cms-sw/cmssw/issues/39803 (other failures are from `MessageLogger`, i.e. not relevant).

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Comment by mmusich** [comment]
@francescobrivio do you mind backporting this?

**Comment by francescobrivio** [comment]
> @francescobrivio do you mind backporting this?

👍 will do!

**Pull request merged**
