### PR TITLE
added pileup scenario for 2018 ultra legacy

### PR DESCRIPTION
**Pull request by plujan**
This adds a pileup scenario for the 2018 ultra legacy, generated in the same way as the 2017 UL scenario #26572 . The new scenario is named "2018_25ns_UltraLegacy_PoissonOOTPU".

Since the automated tests won't actually exercise this scenario, I've tested it manually by running a cmsDriver command with --pileup 2018_25ns_UltraLegacy_PoissonOOTPU and verified that it runs correctly.

### CODE REVIEW

**Comment by tsusa** [comment]
@plujan Could you please post the command that was used to produce the 2018  PU scenario?

**Comment by plujan** [comment]
It's basically this:
`brilcalc lumi --xing -b "STABLE BEAMS" -u hz/ub -i Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json --xingTr 0.2 -o output.csv` and then processing the results bunch-by-bunch into a final histogram.

The full process is documented in the PileupTools repo: https://github.com/CMS-LUMI-POG/PileupTools (I haven't committed the 2018 yet but the process documented in Results2017UL is the same).

**Comment by civanch** [comment]
please test

**Comment by plujan** [comment]
Hmm, I have no idea what triggered that failure, but it's clearly unrelated to this PR -- can you retest?
```
RuntimeError: An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1THGCal/data/panel_mapping_jan19_0.txt anywhere in the search path.
```

**Comment by makortel** [comment]
The problem is in the latest IB, better wait for the next one before relaunching the tests.

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of the StandardSequences is coherent with the purpose of this PR

**Comment by fabiocos** [comment]
+1

**Comment by plujan** [comment]
Just for the final record, here's a link to the talk which has some more details and plots describing this scenario: https://indico.cern.ch/event/826107/contributions/3465964/attachments/1861686/3059846/PileupPPD20190613.pdf

**Pull request merged**
