### PR TITLE
A small fix to dqmMemoryStats.py

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

A small fix to a `dqmMemoryStats.py` tool.

#### PR validation:

The tool was tested locally after applying the fix.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k for my understanding which observed issue is being addressed by this fix?

**Comment by schneiml** [comment]
@fabiocos the regular expression assumes that all non-histogram `MonitoElement`s (which are parsed using this expression) need to have non-empty values. That is typically true in our DQM output, but it blew up now and then when values are not correctly populated.

**Comment by fabiocos** [comment]
+1

@schneiml ok, thanks for the clarification

**Pull request merged**
