### PR TITLE
Phase2-gex335R Backport #40644 to CMSSW_13_0_X to complete v17 definition of HGCal with different lateral sizes of the components inside a silicon module

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #40644 to complete v17 definition of HGCal with different lateral sizes of the components inside a silicon module. This PR affects mainly all workflows which use V17 or V17n geometry versions of HGCal

#### PR validation:

Tested using the runTheMatrix test workflows 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of the PR #40644

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
type backport

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Backport PR. Just to note, we currently have no plan to use C17 for 13_0 Phase-2 production as we never make relvals and make a call for validation. Not clear the goal of backport but it is harmless to update.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
backport of #40644

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @srimanob @perrotta Just taken care of Andrea's comments. Please approve

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , put , please, [13_0_X] in the front of the title.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@srimanob @perrotta @rappoccio Could you approve this and integrate this?

**Comment by srimanob** [comment]
+Upgrade

Backport PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
