### PR TITLE
[14_1_X] Add UPC monopole skim for 2024 PbPb

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46434

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by mandrenguyen** [comment]
@AdrianoDee can you sign this backport as well?

**Comment by AdrianoDee** [comment]
+pdmv

**Pull request merged**
