### PR TITLE
use era Run2_2016 for testRecoMETMETProducers unit test

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by smuzaffar** [comment]
This just fixes the unit test. So merging it now for 23h00 IB.

**Comment by slava77** [comment]
@smuzaffar 
could you please make a backport for 80X.
Thank you.

**Comment by smuzaffar** [comment]
@slava77,  done here https://github.com/cms-sw/cmssw/pull/15264

**Pull request merged**
