### PR TITLE
HCAL: Bugfix of PFA1' Trigger Primitive algo by removing peak-finder

### PR DESCRIPTION
**Pull request by Michael-Krohn**
#### PR description:

Removing the peak-finder when the FIR filter, PFA1', is running to reconstruct the TP energy. This is to match what is in the firmware on detector. Also, on detector the peak-finder is only run when PFA2 is enabled, which has been implemented in this modification.

#### PR validation:

A basic technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport.

### CODE REVIEW

**Comment by abdoulline** [comment]
@Michael-Krohn  please, submit a backport to 12_4_X (not waiting for the full revision of this PR).

**Comment by cecilecaillol** [comment]
please test

**Comment by abdoulline** [comment]
It looks like there was a technical (input file reading) issue in wf 250202.4 irrelevant to the PR per se...

**Comment by perrotta** [comment]
please test
- I agree with @abdoulline that the error is irrelevant here; let retest anyhow to see if it disappears
- @cms-sw/l1-l2 feel free to sign even if those test haven't finished yet, if you are happy with the code changes and with the results of the previous tests

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
