### PR TITLE
Remove unused code to alleviate maintenance burden

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

To address GH issue https://github.com/cms-sw/cmssw/issues/43527 

#### PR validation:

The following processes ran fine:
```
136.8_RunSinglePh2017C
4.17_RunMinBias2011A
140.008_RunEGamma2022A
25034.21_TTbar_14TeV+2026D98PU_ProdLike
158.0_HydjetQ_B12_5020GeV_2018_ppReco
160.4_ZEE_5362_HI_2023 
```

### CODE REVIEW

**Comment by swagata87** [comment]
FYI @bellan  @cms-sw/egamma-pog-l2

**Comment by swagata87** [comment]
type pf, egamma

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
