### PR TITLE
Phase2-hgx211 Modify the tests and try to put tests in HGCal Geometry area

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the tests and test DD4Hep algorithms using similar xml files as for DDD

#### PR validation:

Make use of private tests

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - please review

**Comment by bsunanda** [comment]
@ianna I did send you an email about one of the existing algos in a separate mail. Could you please take a look into this

**Comment by fabiocos** [comment]
@kpedro88 this PR involves only test and developments geometries, and it looks ok to me to move forward

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
