### PR TITLE
Data and MC global tags for 2018 UL [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR, a backport of PR #27923, introduces global tags for the 2018 ultra-legacy reprocessing. See the description of PR #27923 for details. 

The GT diffs with respect to the previous 10_6_X autoCond GTs are as follows:

**Offline**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v21/106X_dataRun2_v22
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v20/106X_dataRun2_relval_v21

**Prompt-like**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v10/106X_dataRun2_PromptLike_HEfail_v11
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v11/106X_dataRun2_PromptLike_v12
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v11/106X_dataRun2_PromptLike_HI_v12

**2018 MC**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v7/106X_upgrade2018_realistic_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v7/106X_upgrade2018_realistic_HEfail_v8

With these changes, the tag content of the modified GTs are consistent with those in the master branch:

**Offline**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v6/106X_dataRun2_v22
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_v6/106X_dataRun2_relval_v21

**Prompt-like**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HEfail_v5/106X_dataRun2_PromptLike_HEfail_v11
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_v5/106X_dataRun2_PromptLike_v12
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HI_v5/106X_dataRun2_PromptLike_HI_v12

**2018 MC**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_v4/106X_upgrade2018_realistic_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HEfail_v4/106X_upgrade2018_realistic_HEfail_v8

#### PR validation:

For physics validation, please see description in PR #27923. Also, as a technical test, ran `runTheMatrix.py -l limited -i all --ibeos`.

#### if this PR is a backport please specify the original PR:

Backport of PR #27923.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
Backport #27923

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Modified global tags will have identical tag content to the GTs in autoCond in the master branch
- Comparison tests show differences only in 2018 workflows

**Comment by fabiocos** [comment]
+1

**Pull request merged**
