### PR TITLE
RelVal fix for HI Jet DQM

### PR DESCRIPTION
**Pull request by kurtejung**
minor fixes for HI Jet DQM relval

Extension of PR #19943

### CODE REVIEW

**Comment by smuzaffar** [comment]
@kurtejung , can you please apply the code-checks suggested too. As of today, all new PRs needs to have code-checks passed
https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3422/3.html

**Comment by smuzaffar** [comment]
please test workflow 140.51,140.52

**Comment by smuzaffar** [comment]
@kmaeshima, @vanbesien, @vazzolini, @dmitrijus , can we get dqm signatures for this PR. This fixes two failing workflows (140.51, 140.52)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
