### PR TITLE
Run3-alca202X Add the treemaker for the new AlCaReco of HcalHBHEMuon

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the treemaker for the new AlCaReco of HcalHBHEMuon

#### PR validation:

Tested by running the new and old tree makers on corresponding AlCa o/p files

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
Hi @bsunanda I think these config files should be under `test`, only the `_cfi` and `_cff` files should be under `python`. Otherwise I have no comments, everything looks good to me

**Comment by bsunanda** [comment]
@tvami the _cfi _cff are in the directory python while the cfg's are in test/python. These scripts are not compiled using "scram b" command. This is natural to create a subdirectory under test and put the cfg's there. We maintain this in a number of packages where we keep large number of cfg's. It is good that all test cfg's are kept separate from other test codes. If you are worried of the name "test/python" we can rename it as "test/cfgs" - but the first name is certainly more preferable.

**Comment by tvami** [comment]
Ahhh it slipped my attention that it was indeed under /test, but there is a subdirectory called python there. I guess that should be fine, although it's a bit misleading. Let's see what the release managers say about this structure @perrotta @qliphy

**Comment by tvami** [comment]
+alca
 * let's see what the release managers say about this https://github.com/cms-sw/cmssw/pull/35383#issuecomment-926181974

**Comment by perrotta** [comment]
+1
- I see no issues in using a \python subdirectory under \test

**Pull request merged**
