### PR TITLE
Added PhysList for study of HGCAL TB

### PR DESCRIPTION
**Pull request by civanch**
A new Physics List FTFP_BERT_EMY Physics List is added for HGCal test-beam studies. This should not affect 8_1 production.

EMY is a configuration of Geant4 electromagnetic physics (so, called EM option3)recommended for more accurate simulation at relatively low energy (HEP detector studies, medical, space science). This configuration force >2 steps of a charged particle inside any volume, and more strong step limit near any geometry boundary. This may be useful for more accurate simulation of MIP particles in Si sensors. We can expect factor 2 slowdown of simulation for HGCall test-beam. This Physics List already used by CALICE developer to understand test-beam results of sampling calorimeter with a small sampling fraction, other EM configurations were not sufficiently accurate.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @civanch - please add a short description of EMY and how it differs from EMM in its implementation. Thanks

**Comment by civanch** [comment]
@davidlange6 , the description is extended.

**Comment by davidlange6** [comment]
Hi @civanch - thanks I really meant in the code - could you add it there too?

**Comment by civanch** [comment]
@smuzaffar , would it be possible to clone this PR to 9_0_X

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , I have added a description to the header

**Comment by davidlange6** [comment]
+1

**Pull request merged**
