### PR TITLE
TEC Pp Connectors Overlap Bugfix

### PR DESCRIPTION
**Pull request by ianna**
* Correct translation of TECPpConnectors in Z using its own half width:
```
diff Geometry/TrackerCommonData/data/Run3/trackerbulkhead.xml Geometry/TrackerCommonData/data/trackerbulkhead.xml
180c180
<    <Translation x="[PatchpanelR2]+0.5*[PpConnectorsLength]+[PpBoxSideX]" y="-0.5*[PpBoxWidth]-[PpBoxSideY]" z="-0.5*[PatchpanelThick]+0.5*[PpConnectorsThick]"/>
---
>    <Translation x="[PatchpanelR2]+0.5*[PpConnectorsLength]+[PpBoxSideX]" y="-0.5*[PpBoxWidth]-[PpBoxSideY]" z="-0.5*[PatchpanelThick]+0.5*[PpBoxThick]"/>
185c185
<    <Translation x="[PatchpanelR2]+[PpConnectorsLength]+[PpBoxLengthL]+0.5*[PpConnectorsLength]+[PpBoxSideX]" y="-0.5*[PpBoxWidth]-[PpBoxSideY]" z="-0.5*[PatchpanelThick]+0.5*[PpConnectorsThick]"/>
---
>    <Translation x="[PatchpanelR2]+[PpConnectorsLength]+[PpBoxLengthL]+0.5*[PpConnectorsLength]+[PpBoxSideX]" y="-0.5*[PpBoxWidth]-[PpBoxSideY]" z="-0.5*[PatchpanelThick]+0.5*[PpBoxThick]"/>
190c190
<    <Translation x="[PatchpanelR2]+0.5*[PpConnectorsLength]+[PpBoxSideX]-[PpBoxDistX]" y="-1.5*[PpBoxWidth]-[PpBoxSideY]-[PpBoxDistY]" z="-0.5*[PatchpanelThick]+0.5*[PpConnectorsThick]"/>
---
>    <Translation x="[PatchpanelR2]+0.5*[PpConnectorsLength]+[PpBoxSideX]-[PpBoxDistX]" y="-1.5*[PpBoxWidth]-[PpBoxSideY]-[PpBoxDistY]" z="-0.5*[PatchpanelThick]+0.5*[PpBoxThick]"/>
195c195
<    <Translation x="[PatchpanelR2]+[PpConnectorsLength]+[PpBoxLengthL]+0.5*[PpConnectorsLength]+[PpBoxSideX]-[PpBoxDistX]" y="-1.5*[PpBoxWidth]-[PpBoxSideY]-[PpBoxDistY]" z="-0.5*[PatchpanelThick]+0.5*[PpConnectorsThick]"/>
---
>    <Translation x="[PatchpanelR2]+[PpConnectorsLength]+[PpBoxLengthL]+0.5*[PpConnectorsLength]+[PpBoxSideX]-[PpBoxDistX]" y="-1.5*[PpBoxWidth]-[PpBoxSideY]-[PpBoxDistY]" z="-0.5*[PatchpanelThick]+0.5*[PpBoxThick]"/>
```
* Copy the xml file as a separate Run 3 copy to avoid backward geometry changes

There are no changes in other volumes, nor material budget. See the screenshots: before and after the fix, and full children tree in its mother volume :
screenshot 2017-01-17 10 50 42
screenshot 2017-01-17 10 49 35
screenshot 2017-01-17 10 51 56

### CODE REVIEW

**Comment by ianna** [comment]
@veszpv and @civanch - FYI.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@ianna  - why "Run3"?

**Comment by ianna** [comment]
@davidlange6 - hasn't run 2 already ended?

**Comment by davidlange6** [comment]
no - anyway, I think you are trying just to change this for the 2017+ geometries, which is good. Maybe something more generic like a 'v2' would be better?

probably its worth a comment to remember this fix in case the run 1/2015/2016 geometries can be updated at some point.

**Comment by ianna** [comment]
@davidlange6 - ok, I'll change this to v2

**Comment by ianna** [comment]
@davidlange6 - it is included in #17199 with requested changes.

**Pull request closed without merging**
