### PR TITLE
Rename UP19 to UP21 in matrix workflows and introduce phase1_2021_cosmics key

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
As a follow-up of comment https://github.com/cms-sw/cmssw/pull/26510/files#r279264544, `UP19` is renamed as `UP21` in the matrix workflows recently introduced in PR https://github.com/cms-sw/cmssw/pull/26510, in the spirit of the migration happening at PR https://github.com/cms-sw/cmssw/pull/26535.
I profit of this PR to introduce also a new `autoCond` key (`phase1_2021_cosmics`) containing conditions for the 2021 cosmics / beam-halo simulation, as it has been requested [here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4124.html).

#### PR validation:

`runTheMatrix -l 7.23,8.2` runs without issues.

#### if this PR is a backport please specify the original PR:

This is not a backport.

@boudoul FYI

### CODE REVIEW

**Comment by tocheng** [comment]
@mmusich Thanks Marco!

**Comment by tocheng** [comment]
+1

**Comment by mmusich** [comment]
I've rebased to avoid the merge conflict now that https://github.com/cms-sw/cmssw/pull/26535 is merged.

**Comment by fabiocos** [comment]
please test workflow 7.23

**Comment by fabiocos** [comment]
@tocheng @christopheralanwest @pohsun @kpedro88 @prebello @zhenhu this PR will finalize the 2021 update, fixing the few anticipated crashes in the IB. Could you please check and comment or sign it?

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
