### PR TITLE
[12_3_X] Add protection vs Minuit2 Fatal Root Error and update VxErrCorr in Vx3DHLTAnalyzer

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38687
This PR fixes the `beampixel` DQM client crashes observed recently, see master PR for detailed description

#### PR validation:
Code compiles + private tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Backport of #38687

FYI @dinardo

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #38687

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@emanueleusai @ahmad3213 @rvenditti could you please test this PR in the Playback system with a recent collision run where the `beampixel` client was crashing?

**Comment by emanueleusai** [comment]
@francescobrivio thank you for the heads up, we will test once https://github.com/cms-sw/cmssw/pull/38687#discussion_r918290833 is addressed

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
> @francescobrivio thank you for the heads up, we will test once [#38687 (comment)](https://github.com/cms-sw/cmssw/pull/38687#discussion_r918290833) is addressed

@emanueleusai the comment was addressed in the last push

**Comment by tvami** [comment]
type bugfix

**Comment by francescobrivio** [comment]
@emanueleusai did you have the chance to test this PR at P5?
This fixes the crashes of the `beampixel` client, so ot would be good to have it in production soon.
Thanks!

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
tested successfully, to be deployed soon

**Comment by qliphy** [comment]
+1

**Pull request merged**
