### PR TITLE
clang check modernize-make-shared

### PR DESCRIPTION
**Pull request by davidlange6**
for comment (and likely not mergeable - this is what clang-tidy check modernize-make-shared does

### CODE REVIEW

**Comment by slava77** [comment]
-1
(to drop from reco-pending list)
looks fine for the "make_shared" part

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
Framework changes are good.

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
