### PR TITLE
FastTimerService: add protection for invalida characters in DQM

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
This should fix the issue reported in #21872 but actually introduced in #21865 .

**Comment by fwyzard** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
