### PR TITLE
[HGCAL] Update modifier in HGCalValidator

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

With the latest RelVal campaign just announced ([link](https://cms-talk.web.cern.ch/t/new-validation-campaign-12-3-0-pre6-phase2-d88-added/8647)) PdmV is moving rapidly to D88. In this PR we update the modifier in HGCalValidator to be able to correctly run on V16 HGCAL geometry scenario. 

This should effect only the workflows that use the new V16 modifier, removing some empty histograms. 

@rovere @felicepantaleo @pfs @ebrondol @lecriste

### CODE REVIEW

**Comment by apsallid** [comment]
I cannot understand why even though I rebase to the latest IB and I only pushed one commit, I see so many commits here. I will close the PR, but do you have a clue why this is happening?

**Comment by apsallid** [comment]
OK, sorry I see we moved to 12_4.

**Comment by tvami** [comment]
@apsallid did you mean to close this PR (by deleting your branch)?

**Comment by apsallid** [comment]
Hi @tvami ,

Yes, I started rebasing but it was taking quite some time, making me a little nervous to be honest with so many commits rebased. So, I thought maybe it was better to delete the branch and start fresh, since it was only two lines added.

**Pull request closed without merging**
