### PR TITLE
Use RooMinimizer instead of RooMinuit after ROOT deprecation for RooMunuit

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

ROOT has changed the RooMinuit usage in here:
https://github.com/root-project/root/pull/8369
here:
https://github.com/root-project/root/pull/8596
and here:
https://github.com/root-project/root/pull/8567
suggesting to use RooMinimizer
https://github.com/root-project/root/blob/master/roofit/roofitcore/inc/RooMinuit.h

#### PR validation:

PhysicsTools/TagAndProbe is building

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@qliphy , @silviodonato @perrotta can we merge this? this is needed for root master IBs where build fails
```
CMSSW_12_0_ROOT6_X_2021-07-15-2300/src/PhysicsTools/TagAndProbe/src/TagProbeFitter.cc:36:10: fatal error: RooMinuit.h: No such file or directory
   36 | #include "RooMinuit.h"

```

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
