### PR TITLE
Drop DetectorDescription/Schema package which just hold data files

### LINKED ISSUE #33312: DetectorDescription/Schema data files duplication
Hi,
  We have duplicate data files for https://github.com/cms-sw/cmssw/tree/master/DetectorDescription/Schema . These files are abvailable vis cmssw/src and cms-data.  @ianna , do you know if we are using these data files?

 Data files from `cmssw/src` are picked for  IB, releases and cmssw PR tests. But for external PR tests ( e.g. cmsdist, cms-data etc.) these files are picked up from cms-data area.

I would suggest to move the cmssw/src/DetectorDescription/Schema/data to cms-data/DetectorDescription-Schema repository.
Any objections @ianna?

### PR DESCRIPTION
**Pull request by smuzaffar**
As discussed https://github.com/cms-sw/cmssw/issues/33312, looks like these data files are not used any more. @ianna suggested to drop these. Later we can update cmsdist to drop the cms-data/DetectorDescription-Schema too.

Fixes cms-sw/cmssw#33312

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = DetectorDescription,Geometry

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@smuzaffar   A unit failure appears after this PR gets merged:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-06-12-1100/unitTestLogs/Geometry/CMSCommonData#/230-230
"Error, schema file not found
DetectorDescription/Schema/DDLSchema.xsd
Quitting, cannot test XML files without a schema"

**Comment by smuzaffar** [comment]
@qliphy , I will add the missing data file in the cms-data repo

**Pull request merged**
