### PR TITLE
 Run4-hgx274 Modify packing of the part for scintillator in the conversion code for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify packing of the part for scintillator in the conversion code for HGCal

#### PR validation:

Tested by making new sub-sets of xml files which will be made into final xml file once the geometry algorithms are tested

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 @srimanob Please review and approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
