### PR TITLE
Track trigger primitives in 81X

### PR DESCRIPTION
**Pull request by sviret**
This PR is an 'analog' rebase of https://github.com/cms-sw/cmssw/pull/15075, to the latest available IB. It's addressing all the comments of https://github.com/cms-sw/cmssw/pull/15075, so should be ready to be pushed in 81X.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by boudoul** [comment]
hello  @rekovic, @mulhearn , could you please review this PR ? Thanks

**Comment by davidlange6** [comment]
is it possible to get some idea of the changes since the last time this big PR was reviewed? the commit history is unfortunately lacking..

**Comment by sviret** [comment]
@davidlange6, most of the technical comments you made on https://github.com/cms-sw/cmssw/pull/15075 were implemented. The only comment which was not implemented was related to use of detid+1 and detid+2 in order to get module sensors. I can find a temporary workaround to that, but a real solution would imply a modification of the tracker topology class, which is something I will not do.

**Comment by davidlange6** [comment]
any easy way to get a diff?

**Comment by sviret** [comment]
@davidlange6 here is a diff of the files I have modified between this commit and the last one (in pre11) from #15075  (pre7) 

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/plugins/TTStubBuilder.cc CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/plugins/TTStubBuilder.cc
78c78
<     std::map< int, std::vector< TTStub< Ref_Phase2TrackerDigi_ > > > moduleStubs; /// Temporary storage for stubs before max check
---
>     std::unordered_map< int, std::vector< TTStub< Ref_Phase2TrackerDigi_ > > > moduleStubs; /// Temporary storage for stubs before max check
88c88
<       tempOutput.clear();
---
>       // tempOutput.clear();
139c139
<         TTStub< Ref_Phase2TrackerDigi_ > tempTTStub = tempOutput.at( iTempStub );
---
>         const TTStub< Ref_Phase2TrackerDigi_ >& tempTTStub = tempOutput[iTempStub];
157,159c157,159
<             std::vector< TTStub< Ref_Phase2TrackerDigi_ > > tempStubs;
<             tempStubs.clear();
<             tempStubs.push_back( tempTTStub );
---
>             std::vector< TTStub< Ref_Phase2TrackerDigi_ > > tempStubs(1,tempTTStub);
>             //tempStubs.clear();
>             //tempStubs.push_back( tempTTStub );

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/src/TTClusterAlgorithm_official.cc CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/src/TTClusterAlgorithm_official.cc
157,158c157,164
< 
<       if ( abs( candCluster.at(0)->row() - candCluster.back()->row() ) < mWidthCut || /// one should add 1 to use <=
---
>       /*
>       std::cout << candCluster.at(0)->row() - candCluster.back()->row() << " / " 
> 		<< static_cast<int>(candCluster.at(0)->row() - candCluster.back()->row()) << " / " 
> 		<< abs( candCluster.at(0)->row() - candCluster.back()->row() ) << " / " 
> 		<< std::abs( candCluster.at(0)->row() - candCluster.back()->row() ) << " / " 
> 		<< mWidthCut << std::endl;
>       */
>       if ( std::abs(  static_cast<int>(candCluster.at(0)->row() - candCluster.back()->row()) ) < mWidthCut || /// one should add 1 to use <=
172c178
<       if ( abs( candCluster.at(0)->row() - candCluster.back()->row() ) < mWidthCut || /// one should add 1 to use <=
---
>       if ( std::abs(  static_cast<int>(candCluster.at(0)->row() - candCluster.back()->row()) ) < mWidthCut || /// one should add 1 to use <=

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_MBIAS_TkOnly_FLAT_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_MBIAS_TkOnly_FLAT_81X.py
51c51
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_MBIAS_TkOnly_TILTED_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_MBIAS_TkOnly_TILTED_81X.py
51c51
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_PGUN_TkOnly_FLAT_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_PGUN_TkOnly_FLAT_81X.py
64c64
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_PGUN_TkOnly_TILTED_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_PGUN_TkOnly_TILTED_81X.py
67c67
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')
121a122,123
> #process.schedule = cms.Schedule(process.generation_step,process.genfiltersummary_step,process.endjob_step,process.RAWSIMoutput_step)
> 

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_PU_TkOnly_FLAT_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_PU_TkOnly_FLAT_81X.py
59c59
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

diff -r CMSSW_8_1_0_pre7/src/L1Trigger/TrackTrigger/test/SLHC_PU_TkOnly_TILTED_81X.py CMSSW_8_1_0_pre11/src/L1Trigger/TrackTrigger/test/SLHC_PU_TkOnly_TILTED_81X.py
62c62
< process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:upgradePLS3', '')
---
> process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

**Comment by delaere** [comment]
@davidlange6, is there anything missing to move forward with the PR?
We would like to have it integrated asap since other people depend on it for the TDR studies.

Thanks!

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 can this go into pre12?

**Comment by davidlange6** [comment]
HI @sviret - maybe the tracker team can suggest someone to make the simple modifications to TrackerTopology in a later pull request. Meanwhile, the customize scenario comments I made seem to not to be addressed (its a bit hard to check things) - could you move those someplace more appropriate?

**Comment by sviret** [comment]
@delaere, @davidlange6, concerning the TrackerTopology modification, I can include it in the next PR, which will include the TTTrack stuff porting in 81X. The PR is basically ready so adding that shouldn't be a big deal.

@ebrondol, @boudoul, concerning the customisation function, I indeed didn't removed customize_digiTkOnly from phase2Tk*** function. These function are used extensively by L1Tracking people for tests, in particular with the tilted geometry. I can remove it and put something in the L1TrackTrigger package instead, but this will be much less practical than the custom function, which is the simplest alternative I found.

**Comment by davidlange6** [comment]
Hi @sviret - sounds good to have the functionality for your internal tests in the L1TrackTrigger area.

**Comment by sviret** [comment]
@davidlange6 just made the modif requested, but looks like something has gone wrong when I pushed the commit (many packages I did never touched have been added, apparently). Is there anyway to go back to the previous situation...

**Comment by davidlange6** [comment]
do you still have the commands you issued in your history buffer?

**Comment by sviret** [comment]
@davidlange6 , I started from the latest IB (CMSSW_8_1_X_2016-09-21-2300). Then I applied the following commands:

[###]> git-cms-addpkg L1Trigger/TrackTrigger
[###]> git-cms-addpkg SLHCUpgradeSimulations/Configuration
[###]> git-cms-addpkg SimTracker/TrackTriggerAssociation
[###]> git-pull https://github.com/sviret/cmssw 81X_TTPrimitives_2

There I made my modifications, added to modified files, commited and pushed to the branch 81X_TTPrimitives_2:

[###]> git push https://github.com/sviret/cmssw 81X_TTPrimitives_2
Counting objects: 12002, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2595/2595), done.
Writing objects: 100% (8549/8549), 4.04 MiB | 0 bytes/s, done.
Total 8549 (delta 6469), reused 7680 (delta 5881)
remote: Resolving deltas: 100% (6469/6469), completed with 1834 local objects.
To https://github.com/sviret/cmssw
   5cbea77..45f3cd6  81X_TTPrimitives_2 -> 81X_TTPrimitives_2

**Comment by davidlange6** [comment]
likely 
git rebase CMSSW_8_1_X_2016-09-21-2300
git push my-cmssw 81X_TTPrimitives_2

**Comment by sviret** [comment]
@davidlange6 did the rebase, don't know if it's ok now

**Comment by davidlange6** [comment]
doesn't look like it..
lets see.

**Comment by davidlange6** [comment]
git push my-cmssw HEAD:<your_branch_name> 

seems to work better for me.

**Comment by sviret** [comment]
For me it's not, unfortunately.... Looks as if I'm once again defeated by git.....

**Comment by davidlange6** [comment]
i'll make a new PR then. I made it with

   253	13:50	scram p CMSSW_8_1_X_2016-09-22-0900
   254	13:50	cd CMSSW_8_1_X_2016-09-22-0900
   255	13:50	cmsenv
   256	13:51	cd src
   257	13:51	git cms-merge-topic 15691
   258	13:52	git checkout -b rb15691
   259	13:52	git push my-cmssw HEAD:rb15691

**Comment by davidlange6** [comment]
replaced by #15949

**Pull request closed without merging**
