### PR TITLE
Replace roll to ieta in GEM

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

* Replace roll to ieta in GEMDetId for consistency between software and hardware words.
* But we keep the roll() to backward compatible.

#### PR validation:

* The branch has tested with following commands to check if it works in 2 different geometry versions.
`runTheMatrix.py -w upgrade -l 31011.0`
`runTheMatrix.py -w upgrade -l 23211.0`
* The code format has applied with `scram build code-format`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by jfernan2** [comment]
@yeckang can you please add your name and github account to the corresponding e-group on
https://twiki.cern.ch/twiki/bin/view/CMS/DQMContacts#GEM
?
Thanks

**Comment by yeckang** [comment]
@jfernan2 I just added myself to Validation DQM Developer(s) e-groups. I'm waiting for approval.
Thanks

**Comment by jfernan2** [comment]
Thank you @yeckang 
Can you please confirm that the changes introduced by this PR are what you expect?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-01-2300+2d1fd5/41445/dqm-histo-comparison-summary.html

**Comment by yeckang** [comment]
@jfernan2
What I expected for this PR is changing the names and titles that contain 'roll' in it. And I see the titles are changed correctly.
Thanks

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
