### PR TITLE
Muon FSR recovery for miniaod and nanoaod [106X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport #28118

Rebase of #28118 on the 10_6_X branch
@arizzi @gpetruc

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28136	7c0de1e 
- the backport of #28118 is correct (the same code changes are applied).
- this PR adds new producers at the level of muon analysis, to be used in the nanoAOD  workflows (not enabled in this PR). The reco category is affected only in the DataFormats/PatCandidates/src/classes_def_objects.xml file where new dictionary declarations are added
- jenkins tests pass

**Comment by slava77** [comment]
I dropped +1 to get the #28221 addressed here as well

**Comment by peruzzim** [comment]
added #28221 backport

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28136	3062388 
- changes since the last reco signoff are in the analysis category code backporting #28221 
- jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
