### PR TITLE
MiniAOD reprocessing (74X, Gen): Sorted mother and daughter RefVectors in the GenParticlePruner

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #9709 and #10028

This PR is part of preparations for possible MiniAOD reprocessing of the Spring15 MC and 50ns Run2012B Data in 74X. More info at the following links:
- https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2445.html
- https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#Gen

### CODE REVIEW

**Comment by ferencek** [comment]
@monttj, can you please start the tests

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
