### PR TITLE
Fix unit tests to avoid bot rebuild every thing

### PR DESCRIPTION
**Pull request by smuzaffar**
Last night we updated the configuration to kill any test which runs over 1 hour and caught this test failing. These tests are doing "scram b" which for IBs re-build full IB and take more than 1 hour. 

I updated the tests to not run "scram b".

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 please review and sign this. This is just a technical update to avoid the unit test rebuilding full cmssw during IB tests

**Comment by smuzaffar** [comment]
@qliphy , please also merge this

**Comment by qliphy** [comment]
merge

**Comment by agrohsje** [comment]
sorry. didn't check mails over the weekend. let me sign for completeness.

**Comment by agrohsje** [comment]
+generators

**Pull request merged**
