### PR TITLE
Phase2-hgx216 Add one more dd4hep algorithm

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert DDHGCalWaferAlgo (used in TB applications as well as in V7) from DDD to DD4Hep scenario

#### PR validation:

Tested using the cfg files in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@cvuosalo @ianna Could you please sign this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
