### PR TITLE
DAQ file broker client (10_3_X)

### PR DESCRIPTION
**Pull request by smorovic**
New rebased PR as there was conflict in  #23819.
In addition it enables File Broker keep alive by default.

### CODE REVIEW

**Comment by mommsen** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23944	4c7f2cd
- the changes are only in files specific to DAQ, not really related to reco
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by kpedro88** [comment]
+1

**Pull request merged**
