### PR TITLE
Modify vertex validation to use timing when possible.

### PR DESCRIPTION
**Pull request by lgray**
This PR modifies the vertex matching to take advantage of timing information if it is available.

Examples (red is 4D vertexing, blue is 3D):
screen shot 2016-10-09 at 17 20 43
screen shot 2016-10-09 at 17 24 47

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
Thanks @lgray. I'm not entirely sure of the benefit of adding a second constructor to `VertexAssociatorByPositionAndTracks` though. My concern is that the EDProducer uses one convention of special values of timing parameters (`< 0.0`) to denote if the time matching is disabled, and the associator uses another one (`std::numeric_limits<double>::max()`).

Personally I'd like if the associator would use the same convention as the configuration. Then, when trying to understand what the configuration parameters actually do, one can essentially skip the code of EDProducer.

Minor point but I thought to mention.

**Comment by civanch** [comment]
@lgray , it would be more correct if useTiming flag is a class member which is defined in the constructor but not deeply inside the code. All actions when time is taken into account will be enabled by such flag.

**Comment by lgray** [comment]
@civanch This option is a bit "forward looking" in the sense that there will be an efficiency associated assigning the timing to the tracks in vertices, and it may be the case that there are some vertices without timing information. Therefore the behavior of the analyzer should be determined per-vertex.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@makortel I agree with your statements about the constructors and consistency. I'll fix it up in another PR.

**Comment by makortel** [comment]
Thanks @lgray.

**Pull request merged**
