### PR TITLE
[JMENanoAOD] Backport of #39000 (Updates for Run-3) to 12_4_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #39000

#### Orignal PR description:
This PR updates JMENano to be compatible with Run-3 data and MC, starting with the upcoming NanoAODv10 production. The following major changes are made: 

- `Sequences` have been changed to `Tasks` and JMENano can now run in Prompt.
- Updated names of NanoAOD-related config files and modules.
- Add a dedicated function for reclustering and content customisation of AK4 Puppi jets.
- Recluster both AK4 CHS and AK4 Puppi jet collections but modify their table names and content depending on era (i.e Run-2 or Run-3).
- Increase pt threshold for stored reclustered AK8 reco jets to 15 GeV.
- The JMENano workflows are enabled back again, which was disabled by PR #35140. Enable Run-3 workflows and added one wf: 11634.15.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- backport of https://github.com/cms-sw/cmssw/pull/39000 and nothing else
- no reco changes, POG internal workflows

**Comment by srimanob** [comment]
test parameters:

- workflows = 10224.15,11024.15,25202.15,11634.15

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mariadalfonso** [comment]
+xpog
backport inline with master

remaining items notes here in master's PR
https://github.com/cms-sw/cmssw/pull/39000#issuecomment-1214946228

**Comment by srimanob** [comment]
+Upgrade

Backport PR

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
@mariadalfonso your comment in https://github.com/cms-sw/cmssw/pull/39000#issuecomment-1214946228 implied that this PR  cannot be set to central production until items 2 and 5 from 
https://github.com/cms-sw/cmssw/pull/39000#issuecomment-1208526750 aren't solved.

Does your signature in this backport PR (which, if merged, will automatically include this PR in all future central nanoAOD productions in 12_4_X) means that these issues are now to be considered to be solved? Can we safely merge this in 12_4_X since now, then?

**Comment by mariadalfonso** [comment]
@perrotta 
This PRs does not interfere with the main nanoV10 analysis nano and only affect the custom JMEnano. Those are effectively two different productions that can use different releases (i.e. 12_4_6 for analysis nano and 12_4_7 for JMEnano)

We should merge this PR now as it is, as it can help the private production of JMEnano:
JME is producing them now with them aim of deriving residuals, and this can serve as first validation.

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/39078#issuecomment-1222187882

**Pull request merged**
