### PR TITLE
Detect and remove all duplicate pixels [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Detect and remove all duplicate pixels, after unpacking each pixel module but before running the clustering.
Use shared memory for inter-thread communication and to speed up marking and detecting the duplicates.

#### PR validation:

Running the online pixel reconstruction and the full HLT menu on GPU over non-problematic events shows only a moderate slow down:

reconstruction | pixel tracking | full HLT
---|---|---
no duplicate removal                                                          |1566 ± 16 ev/s (--)    | 873 ± 4 ev/s (--)
duplicate removal with `atomicOR` (ce8a57bd815d631764ada169206d0eeb0e33b09e)  |1530 ± 17 ev/s (-2.3%) | 872 ± 4 ev/s (-0.2%)
duplicate removal with `atomicCAS` (25220129fa7dc0e5caac01f2800234e2ad956877) |1519 ± 14 ev/s (-3.0%) | 869 ± 2 ev/s (-0.4%)

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #38946 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #38946

**Comment by fwyzard** [comment]
urgent

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by civanch** [comment]
+1

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by clacaputo** [comment]
+reconstruction

- backport #38946

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
I see that this PR updates a DataFormat, although just adding a method to retrieve information, there is no change in data members or interfaces, so probably it is still ok for a patch release (which is already built)

**Pull request merged**
