### PR TITLE
Update BasicGenValidation_cff.py

### PR DESCRIPTION
**Pull request by menglu21**
#### PR description:
Backport from #29146

#### PR validation:
Procedure:
scram project CMSSW_7_1_45 & cmsenv
git cms-rebase-topic --old-base CMSSW_11_1_0_pre5 menglu21:master
git branch -m portFrom111XTo71X_genvalidation
then do the same things with original PR

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Original PR is #29146

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of #29146

**Comment by jfernan2** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by jfernan2** [comment]
+1
There are 3111 failures and -10kB, I guess that unrelated to this PR since they are in the DQM/TimerService

**Comment by silviodonato** [comment]
please test
to refresh the comparison results

**Comment by jfernan2** [comment]
The failures are repited. As far as I can see from RelMon they include CASTOR and DQM (TimerService) folders, might they be realted to the CMSW 71X version?

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@jfernan2 I made an issue https://github.com/cms-sw/cmssw/issues/29365 to keep track of the difference. Indeed we had these fake errors since a long time.

**Pull request merged**
