### PR TITLE
Adding fake alignment to make tracker geometry test work

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
To solve the issue reported in https://github.com/cms-sw/cmssw/issues/35118
When https://github.com/cms-sw/cmssw/pull/35092 was introduced, it will take alignment from the GT. However, for the unit test, we can pick the fake alignment instead.

#### PR validation:
Test with `testTrackerHierarchy_cfg.py` and `testTracker_cfg.py`, they now run fine.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport. Will backport together with https://github.com/cms-sw/cmssw/pull/35092 to 12_0 if needs.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@srimanob you have the same [problem]( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-38413e/18238/unitTests/src/Geometry/TrackerGeometryBuilder/test/GeometryTrackerGeometryBuilderTestDriver/testing.log)

also in

https://github.com/cms-sw/cmssw/blob/511cc96f0568c1e21e2a88ec14dcb12b57d3dd4d/Geometry/TrackerGeometryBuilder/test/python/testTracker_cfg.py#L4

Please update that one as well.

**Comment by srimanob** [comment]
Thanks @mmusich 
Done.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by qliphy** [comment]
type bugfix

**Comment by mmusich** [comment]
@srimanob @qliphy 
I guess the relval input errors seen here in tests ([log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-38413e/18240/runTheMatrixINPUT-results/runall-report-step123-.log)):
```bash
136.72413_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMININANO_data2016UL_HIPM_met+HARVESTDR2_REMININANO_data2016UL_HIPM_met Step0-PASSED Step1-FAILED Step2-NOTRUN  - time date Thu Sep  2 08:42:21 2021-date Thu Sep  2 08:41:32 2021; exit: 0 256 0
```
are spurious and in fact due to the issues discussed at https://github.com/cms-sw/cmssw/pull/34714#issuecomment-911211072.
Shall this be retested with https://github.com/cms-sw/cmssw/pull/35121 ?

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
