### PR TITLE
[L1-UPGRADE] [CLANG]Fixes warnings reported by clang 14

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes clang 14 warnings about variable set but unused

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
Hi @cecilecaillol 

It seems this PR is technical, however the deletion seems to touch what you have. Do you confirm that what have been deleted are not needed?

**Comment by jbsauvan** [comment]
Hi @srimanob 
For what concerns the `L1THGCal` package, the deletion is fine as it is concerning an unused variable.

**Comment by srimanob** [comment]
+Upgrade

As confirm in https://github.com/cms-sw/cmssw/pull/40530#issuecomment-1384916469, this PR is purely technical.

**Comment by perrotta** [comment]
+1

**Pull request merged**
