### PR TITLE
Catch more circular dependencies (backport 20502)

### PR DESCRIPTION
**Pull request by Dr15Jones**
This is a backport of #20502

### CODE REVIEW

**Comment by Dr15Jones** [comment]
backport #20502

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
I ran the full runTheMatrix.py suite and no additional problems were uncovered.

**Comment by ghellwig** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Dr15Jones** [comment]
@fwyzard Are you still interested in getting this back ported? If so, then I will deal with the conflict.

**Comment by fwyzard** [comment]
Hi @Dr15Jones , 
I think it's a pity that the PR was not merged one and a half months ago... by now, with the data taking almost over, we (TSG and I) think we can leave 9.2.x as it is.

**Comment by Dr15Jones** [comment]
@fwyzard thanks Andrea.

**Comment by Dr15Jones** [comment]
close

**Pull request closed without merging**
