### PR TITLE
Update CondDBFW to Python3

### PR DESCRIPTION
**Pull request by Dres90**
#### PR description:

Update CondDBFW to Python3
The new conditions uploader uses the CondDBFW mini framework in CMSSW to locally validate the Conditions DB files and lighten the load on the server. Since the Python version for CMSSW has been updated, this functionality was broken. This PR updates CondDBFW to Python3 and restores the uploadConditions_v2.py script functionality.

#### PR validation:

Multiple uploads have been run with this new CondDBFW to the PREP database and they have all been successful. This Python 3 code is already in use in the server side.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Diff in the comparison are just due to "The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline". Unit tests pass nicely, I think that is the real test of this PR anyway, right @ggovi ?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
