### PR TITLE
Update Higgs Dalitz paths (74X)

### PR DESCRIPTION
**Pull request by jasperlauwers**
backport of #11340

### CODE REVIEW

**Comment by perrotta** [comment]
@jasperlauwers : only the last commit in this ticket is actually the backport of #11340.
Could you please make separate pull requests for separate updates/fixes?
As such you would speed up the merging of the part which relates to the additional monitoring of the new Dalitz path(s), and as a consequence the integration of the new paths in the HLT menu.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@davidlange6 should comment about policies, but decoupling the two set of changes should speed up the integration.

**Comment by jasperlauwers** [comment]
All commits before the last one are in #11209
I'm a bit lost in what exactly you want me to do. Also because #11209 contains a new path (HLT_Ele23_WPLoose_Gsf_WHbbBoost_v1) that didn't need to be fully merged in 75x and 74x to get the green light from STEAM.
Could you please clearify if you want me to rebase #11209 on top of the new commit in this PR so this commit can be merged faster?

**Comment by perrotta** [comment]
@jasperlauwers : we already decided to include the new paths even if these 74X/75X PR's could not be fully signed yet, because the DQM update requested (included in your last commit) is trivial, and already merged in 76X. Therefore, do whatever you prefer with these backport PR's (provided you keep taking care of them whenever needed).

Anyhow, I think that n principle you should have rather had to backport one PR at a time instead of mixing all them together, especially if the easy one is requested for the integration of the new paths in the HLT menu, and it can be stopped by the toughest part of the cumulative PR.

(Please, contact me privately if you want to continue this discussion. Or join us tomorrow at the TSG meeting)

**Comment by deguio** [comment]
+1
I would have created a PR containing only the last commit so that the cfg path update can be merged faster, but fine. approving this one.

**Comment by jasperlauwers** [comment]
The PR has been updated to the commits that have been validated in 7_6_0_pre6.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jasperlauwers** [comment]
The commits in this PR have been validated in 7_6_0_pre6. Can it be merged?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
