### PR TITLE
Extended hltDiff with CVS/JSON/ROOT output formats [7_6_X]

### PR DESCRIPTION
**Pull request by bartosik-hep**
Extended the event-by-event validation code with output in different formats:
- **CSV**: can be directly inserted in GoogleDoc Sheets for custom statistical calculations
- **JSON**: can be used in the interactive [Web-interface](https://cms-hltdiff-visual.web.cern.ch/cms-hltDiff-visual/) for a deeper view on the affected triggers/modules
- **ROOT**: can be uploaded to the DQM GUI for a fast visual validation

No large summary printed by default any more. This info can be found in CSV files or with increased verbosity level.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Really 76X?
I assume it should be 80X (and 81X).

**Comment by bartosik-hep** [comment]
I have submitted the one for 81X: [#15083](https://github.com/cms-sw/cmssw/pull/15083)
Is 8_0_X also needed?

**Comment by fwyzard** [comment]
Hi @bartosik-hep ,
please make an 8.0.x PR as well.

I do not think we need a 7.6.x PR, though.

Thank you,
.Andrea

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request closed without merging**
