### PR TITLE
Fix clang warning in OnlineDB/SiStripO2O

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

After moving to LLVM 12 new warning surfaced:
`OnlineDB/SiStripO2O/plugins/SiStripPayloadHandler.cc:67:16: warning: field 'condObjBuilder' is uninitialized when used here [-Wuninitialized]`
in CLANG IBs.
I'm not sure if moving the object initialization in the constructor body is fine but either way I'm bringing this to attention

#### PR validation:

builds without warning for CLANG IB

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_CLANG_X

**Comment by smuzaffar** [comment]
looks like this does fix the wraning for CLANG IB ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1ae7c8/15940/build-logs/OnlineDB/SiStripO2O/log.html ). @ggovi , if no  do you have any objections? If not then can youplease sign it?

**Comment by Dr15Jones** [comment]
So the framework discourages holding a `edm::Service<>` as a member data. It would be better to just make the `edm::Service<>` a local variable of the function where it is being used.

**Comment by mrodozov** [comment]
forgot about that :/ sry

**Comment by mrodozov** [comment]
please test for CMSSW_12_0_CLANG_X

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
