### PR TITLE
L1 Modify Btag Jet Types [Merged with 14_0_0_pre3]

### PR DESCRIPTION
**Pull request by Duchstf**
Description from https://github.com/cms-l1t-offline/cmssw/pull/1198

> #### PR description:
> 
> Modifications of jet types in order to package the btagging scores. 
> 
> #### PR validation:
> 
> Everything should compiles, I tested this in conjunction with this PR in the hardware development branch: https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-common/-/merge_requests/156#note_7488170
> 

It was merged there, propagating the same changes to master.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
I have more or less forgotten to use the dedicated upgrade workflow for testing phase 2 PRs (https://github.com/cms-sw/cmssw/pull/43271). We should be doing that.

**Comment by aloeliger** [comment]
please test workflow 24834.78

**Comment by aloeliger** [comment]
test_parameters:
- workflow = 24834.78
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by aloeliger** [comment]
test parameters:
- workflow = 24834.78
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@cms-sw/hlt-l2 @cms-sw/upgrade-l2  It seems like the [phase-2 L1T Trigger testing workflow](https://github.com/cms-sw/cmssw/blob/7e39f77df910152dc5c26df153b8f967d9269331/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1895-L1911) ([PR](https://github.com/cms-sw/cmssw/pull/43271)) (that I just remembered about for phase 2 PRs, that's on me), has overlap of the phase 2 GT paths getting run because both the `L1P2GT` step added for L1T global trigger, and the HLT step attempt to run the prototype phase 2 GT. We would like this workflow, or something similar, available for testing a complete L1Trigger step while the L1 phase 2 prototype fork gets slowly deprecated in favor of the superior PR testing here, but I am flexible on fixing this particular overlap. 

We could cut HLT and subsequent steps from this workflow, or attempt to cut the independent GT step out and just trust HLT to run it, or remove it from the HLT step. I have no preferences here, but wanted to poll the other relevant parties in case there was an opinion on this.

**Comment by mmusich** [comment]
adding HLT upgrade to the discussion @rovere @SohamBhattacharya

**Comment by aloeliger** [comment]
> @cms-sw/hlt-l2 @cms-sw/upgrade-l2 It seems like the [phase-2 L1T Trigger testing workflow](https://github.com/cms-sw/cmssw/blob/7e39f77df910152dc5c26df153b8f967d9269331/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1895-L1911) ([PR](https://github.com/cms-sw/cmssw/pull/43271)) (that I just remembered about for phase 2 PRs, that's on me), has overlap of the phase 2 GT paths getting run because both the `L1P2GT` step added for L1T global trigger, and the HLT step attempt to run the prototype phase 2 GT. We would like this workflow, or something similar, available for testing a complete L1Trigger step while the L1 phase 2 prototype fork gets slowly deprecated in favor of the superior PR testing here, but I am flexible on fixing this particular overlap.
> 
> We could cut HLT and subsequent steps from this workflow, or attempt to cut the independent GT step out and just trust HLT to run it, or remove it from the HLT step. I have no preferences here, but wanted to poll the other relevant parties in case there was an opinion on this.

@cms-sw/hlt-l2 @cms-sw/upgrade-l2 just wanted to issue a gentle ping on this one.

**Comment by Martin-Grunewald** [comment]
Can you please elaborate? HLT Phase-II should no longer run L1T itself, but only some unpacker getting the L1T decisions and L1T objects from some AlgBlk, with L1T run in a previous step?

**Comment by aloeliger** [comment]
> Can you please elaborate? HLT Phase-II should no longer run L1T itself, but only some unpacker getting the L1T decisions and L1T objects from some AlgBlk, with L1T run in a previous step?

@Martin-Grunewald Running WF 26834.78, added by upgrade request for testing L1T, and defined like so:

https://github.com/cms-sw/cmssw/blob/7e39f77df910152dc5c26df153b8f967d9269331/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1895-L1911

Note, that it is running the following L1T+HLT steps: L1,L1TrackTrigger,L1P2GT (Global trigger step added by GT team request), & HLT

I get the following error in step 2:

```
----- Begin Fatal Exception 08-Apr-2024 11:51:43 CDT-----------------------
An exception of category 'LogicError' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Duplicate Product Identifier 
The Framework requires a unique branch name for each product
which consists of four parts: a friendly class name, module label,
product instance name, and process name. A product has been
registered with a duplicate branch name. The most common way
to fix this error is to modify the product instance name in
one of the offending 'produces' function calls. Another fix
would be to delete one of them if they are for the same product.

    friendly class name = edmHLTPathStatus
    module label = pSinglePuppiJet230
    product instance name = 
    process name = HLT

The following additional information is not used as part of
the unique branch identifier.

    branch types = Event  Event
    class name = edm::HLTPathStatus

Note that if the four parts of the branch name are the same,
then this error will occur even if the branch types differ!
```

If you dump out the schedule, you get the following:

```
cms.Schedule(*[ process.digitisation_step, process.L1simulation_step, process.L1TrackTrigger_step, process.Phase2L1GTProducer, process.Phase2L1GTAlgoBlockProducer, 
process.pDoubleEGEle37_24, process.pDoubleIsoTkPho22_12, process.pDoublePuppiTau52_52, process.pDoubleTkEle25_12, process.pDoubleTkMuon15_7, process.pIsoTkEleEGEle22_12, 
process.pPuppiHT400, process.pPuppiHT450, process.pPuppiMET200, process.pQuadJet70_55_40_40, process.pSingleEGEle51, process.pSingleIsoTkEle28, process.pSingleIsoTkPho36, 
***process.pSinglePuppiJet230***, process.pSingleTkEle36, process.pSingleTkMuon22, process.pTripleTkMuon5_3_3, process.digi2raw_step, process.GTemulation_step, 
process.pSingleIsoTkEle28, process.pPuppiHT450, ***process.pSinglePuppiJet230***, process.pDoubleEGEle37_24, process.pDoubleTkMuon15_7, process.pDoubleTkEle25_12, 
process.pDoubleIsoTkPho22_12, process.pIsoTkEleEGEle22_12, process.pQuadJet70_55_40_40, process.pPuppiMET200, process.pSingleTkEle36, process.pPuppiHT400, 
process.pTripleTkMuon5_3_3, process.pSingleTkMuon22, process.pSingleEGEle51, process.pDoublePuppiTau52_52, process.pSingleIsoTkPho36, process.L1T_SinglePFPuppiJet230off, 
process.L1T_PFPuppiHT450off, process.L1T_PFPuppiMET220off, process.HLT_AK4PFPuppiJet520, process.HLT_PFPuppiHT1070, process.HLT_PFPuppiMETTypeOne140_PFPuppiMHT140, 
process.L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4, process.L1T_DoublePFPuppiJets112_2p4_DEta1p6, 
process.HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4, process.HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4, 
process.HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4, process.HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4, 
process.HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4, process.HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4, 
process.L1T_SingleTkMuon_22, process.L1T_DoubleTkMuon_15_7, process.L1T_TripleTkMuon_5_3_3, process.HLT_Mu50_FromL1TkMuon, process.HLT_IsoMu24_FromL1TkMuon, 
process.HLT_Mu37_Mu27_FromL1TkMuon, process.HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon, process.HLT_TriMu_10_5_5_DZ_FromL1TkMuon, process.L1T_TkEm51, 
process.L1T_TkEle36, process.L1T_TkIsoEm36, process.L1T_TkIsoEle28, process.L1T_TkEm37TkEm24, process.L1T_TkEle25TkEle12, process.L1T_TkIsoEm22TkIsoEm12, 
process.L1T_TkIsoEle22TkEm12, process.HLT_Ele32_WPTight_Unseeded, process.HLT_Ele26_WP70_Unseeded, process.HLT_Photon108EB_TightID_TightIso_Unseeded, 
process.HLT_Photon187_Unseeded, process.HLT_DoubleEle25_CaloIdL_PMS2_Unseeded, process.HLT_Diphoton30_23_IsoCaloId_Unseeded, process.HLT_Ele32_WPTight_L1Seeded, 
process.HLT_Ele115_NonIso_L1Seeded, process.HLT_Ele26_WP70_L1Seeded, process.HLT_Photon108EB_TightID_TightIso_L1Seeded, process.HLT_Photon187_L1Seeded, 
process.HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded, process.HLT_DoubleEle23_12_Iso_L1Seeded, process.HLT_Diphoton30_23_IsoCaloId_L1Seeded, 
process.HLT_DoubleMediumChargedIsoPFTauHPS40_eta2p1, process.MC_JME, process.MC_BTV, process.MC_Ele5_Open_Unseeded, process.MC_Ele5_Open_L1Seeded, 
process.HLTriggerFinalPath, process.HLTAnalyzerEndpath, process.endjob_step, process.FEVTDEBUGHLToutput_step ], tasks=[process.patAlgosToolsTask])
```

Emphasis mine. GT's new "menu paths" are being added twice, presumably by the two things that care about them, HLT and GT (In fact, I tested removing HLT from this workflow. It broke, but at a later step because HLT wasn't around).

This overlap should be removed so that this step is available for tesitng the complete trigger upgrade workflow. I don't really care where the overlap is removed, so if there are opinions on that, I can be flexible.

**Comment by Martin-Grunewald** [comment]
What is ```pSinglePuppiJet230``` doing? Calculating the L1T decision or just 'unpacking' it from RAW?
If it is the former it should be in the GT or other L1T step, if the latter is must be in HLT for HLT to get the decision (and possibly related objects) - at least this is my understanding.
 @rovere @SohamBhattacharya

**Comment by aloeliger** [comment]
> What is `pSinglePuppiJet230` doing? Calculating the L1T decision or just 'unpacking' it from RAW? If it is the former it should be in the GT or other L1T step, if the latter is must be in HLT for HLT to get the decision (and possibly related objects) - at least this is my understanding. @rovere @SohamBhattacharya

@Martin-Grunewald It is calculating the relevant L1T seed as part of the GT step. It was included as part of the GT step `P2L1GT`, and then again as part of the HLT step (likely because this is phase 2, and there is nothing to "unpack").

**Comment by Martin-Grunewald** [comment]
Yes, but we need to agree, as you say, where what is to be done. HLT should not need to run L1T as it is either run online (and packed up in RAW) or in MC in the L1T/P2GT step (and packed up in RAW). HLT just needs to access the info in RAW (ie, to pull out the decision and the associated jet objects). That was the agreement I recall. It may simply mean that as in the past the P1L1GT step was not there, it was added to HLT. So it could be removed? Requiring work on the HLT Phase-II to remove?   @rovere @SohamBhattacharya please comment!

**Comment by SohamBhattacharya** [comment]
N.B. #44751 Removes the P2GT steps from withing the HLT config, as now there is a dedicated step for it.

**Comment by aloeliger** [comment]
test parameters:
- pull_requests = https://github.com/cms-sw/cmssw/pull/44751
- workflow = 24834.78
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by aloeliger** [comment]
+l1

**Comment by Duchstf** [comment]
@srimanob Hello, I think this is the usual workflow of L1 phase 2 software? To be honest I think these kinds of things should be unncessary but we have been doing this for years now? In anycase I copied the PR description. 

The point is we are just adding a modification to phase 2 jet types to accommodate for b-tag jet scores to be sent to the global trigger. This is merged in L1 development cmssw branch but not propagated into master branch so this is the purpose of the PR. 

Thanks, 

Duc.

**Comment by srimanob** [comment]
Hi @Duchstf 
Let's me re-phase my question, I don't understand "[Merged with 14_0_0_pre3]" in the PR title. From CMSSW point-of-view, the PR should be merged to master first, then backport to 14_0. So, I just wonder why it goes to 14_0 first before this PR. That is what I ask for clarification.

However, as this PR goes to master, it is fine to me.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
