### PR TITLE
Add Phase 2 Outer Tracker with sensors updates + OTST MB update. Remove T18.

### PR DESCRIPTION
**Pull request by ghugo83**
**PR description:**

This PR introduces a Phase 2 Outer Tracker with thicker sensors (+ other updates in modules) + includes very significant changes in OTST MB.
Was presented at: https://indico.cern.ch/event/889563/contributions/3760870/attachments/1992522/3323596/hugo.pdf 

The new Tracker is called T20.
Geometry scenario: 2026D56.
Workflows: 266xx (no PU), 268xx (PU).

**OT:** 
- Sensor thickness: 200 → 290 um
Total Outer Tracker weight: +56 kg (1630 kg → 1686 kg).
- MB modules update: sensors inactive Si (inactive edges + deep diffused) + MPA.
- New PS module model. Sensors have different lengths, s-sensor slightly longer than p-sensor.

Before PR: http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/repository-git-dev/OT616_200_IT613/weightsouter.html
After PR: http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/repository-git-dev/OT616_IT613/weightsouter.html
sensors_ratio

**OTST:**
Many changes in geo and MB from Mechanics, the most significant one being: CFRP skin: 2 mm → 4 mm. 
Total OTST mass: 147 kg → 300 kg.
otst_ratio

NB: Only Outer Tracker is updated here, no IT included. An existing Inner Tracker is directly called (T17).

Following comparisons should be made:
T17 versus T20 (2026D51 versus 2026D56).

**PR validation:**
Following was done for validation:
- Solved all overlaps on CMSSW with Fireworks and Geant4 tools.
- Even if the active geometry is different from T15, logically there should be no DetId diff (based on how the DetIds are computed in CMSSW). Checked that this is the case indeed.
This allows to reuse the fakeConditions from T15.
- Checked workflow numbering.
- Checked that workflows with D56 run smoothly with no extra error / warning.

FYI: @dpiparo @civanch @ianna @emiglior @skinnari @mmusich @jalimena @bsunanda @fabiocos @kpedro88

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
do you have any comments @rekovic ?

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
