### PR TITLE
Remove obsolete signals from ActivityRegistry

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The last Services trying to use those signals were removed from CMSSW.

#### PR validation:

After doing `git cms-checkdeps -a` the code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
