### PR TITLE
Update Data/MC GTs in 106X

### PR DESCRIPTION
**Pull request by tocheng**
#### PR description:

The PR is to update the DATA/MC GTs in autoCond

#### **Run-1/Run-2 Data**
Difference between GTs in PR and GTs in master branch is due to JEC/JER update (for 2018 data), LHCinfo, PPS geometry fix, PF calibration at HLT and pixel 1D/2D templates plus GenErr Lorentz angle for 2017 data
Diff
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v8/106X_dataRun2_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v6/106X_dataRun2_relval_v1

#### **Prompt-like Data**
Difference between GTs in PR and GTs in master branch is due to LHCinfo, LHC optical function, PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_4/106X_dataRun2_PromptLike_HEfail_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v4/106X_dataRun2_PromptLike_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v4/106X_dataRun2_PromptLike_HI_v1

#### **HLT**
Difference between GTs in PR and GTs in master branch is due to PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_frozen_v9/101X_dataRun2_HLT_frozen_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_v8/103X_dataRun2_HLT_relval_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_HI_v4/103X_dataRun2_HLT_relval_HI_v3

#### **Run-1 MC**
No difference between GTs in PR and GTs in master branch.
Diff
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_v1/105X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_v1/105X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_v1/105X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_v1/105X_mcRun1_pA_v1

#### **2015 MC**
No difference between GTs in PR and GTs in master branch except difference in 2015 simulation due to HLT PF calibration
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_v2/105X_mcRun2_startup_v1
Diff
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_v2/105X_mcRun2_asymptotic_l1stage1_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_v2/105X_mcRun2_pA_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_v2/105X_mcRun2_HeavyIon_v2

#### **2016 MC**
No difference in 2016 simulation as the latest JEC/JER is already in
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v3/105X_mcRun2_asymptotic_v4
**ECAL ideal condition update**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v3/105X_mcRun2_design_v3

Difference in cosmic GTs is due to PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2cosmics_startup_deco_v2/105X_mcRun2cosmics_startup_deco_v4

#### **2017 MC**
Differences are due to **JEC/JER update** and PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v3/106X_mc2017_realistic_v1
**ECAL ideal condition update** and PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_design_IdealBS_v4/106X_mc2017_design_IdealBS_v2

Cosmic GTs change due to PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_deco_v2/106X_mc2017cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_peak_v2/106X_mc2017cosmics_realistic_peak_v1

#### **2018 MC**
Differences are due to **JEC/JER update**+**Tracker mis-alignment scenario**+PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v4/106X_upgrade2018_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v4/106X_upgrade2018_realistic_HEfail_v1
Differences are due to **Tracker mis-alignment scenario**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_deco_v3/106X_upgrade2018cosmics_realistic_deco_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_peak_v3/106X_upgrade2018cosmics_realistic_peak_v1

**ECAL ideal condition update**+PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_v3/106X_upgrade2018_design_v1

Heavy Ion GTs changes due to PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v2/106X_upgrade2018_realistic_HI_v1

#### **Run-3 MC**
Differences are due to **Pixel quality for Run-3**+**HCAL eMap and L1 object update**+PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_postLS2_design_v4/106X_postLS2_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_postLS2_realistic_v4/106X_postLS2_realistic_v1

#### **Phase-2 MC**
Differences are due to **Phase-2 tracker DTC eMap**+PF calibration at HLT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_v2/105X_upgrade2023_realistic_v5

#### PR validation:

The updates are motivated by

1)JEC/JER update : see [JEC/JER twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC)
                                [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4118.html) for JEC/JER in data for 2016-2018 
2)Tracker mis-alignment scenario for 2018 : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4112.html)
3) ECAL design condition updates for 2016-2018 : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4115.html)
4) Pixel quality for Run-3 : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4116.html)
5) HCAL eMap and L1 object update for Run-3 (and MWGR analysis) : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4113.html)
6) Phase-2 tracker DTC eMap : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4111.html)
7) PF calibration PR #25883 
8) LHC info for 2016 to 2018
9) 2017 pixel 1D/2D templates plus GenErr Lorentz angle for 2017 data : see [hn announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4117.html)
10) PPS geometry fix in https://github.com/cms-sw/cmssw/pull/26316

Not include PPS optical function to support proton reconstruction
so this PR can be decoupled from #26394 (and #26350 )

runTheMatrix test is performed.

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please abort

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
Another commit will be done today, adding PF calibration at HLT to support #25883

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
The test failure is due to adding LHC optical function, leading to two ES sources for the same record label. I am coordinating with #26394 @jan-kaspar to see what is the best solution.

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @slava77 let me keep this on hold while other PRs are being validated, I will add it before closing for pre4

**Comment by fabiocos** [comment]
@tocheng this needs to be rebased I assume after the merge of #26394

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
