### PR TITLE
CCC PSet migration with HLT for 75X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
CCC PSet migration with HLT for 75X
Includes #8351 plus required HLT changes

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

if tests succeed

**Comment by Martin-Grunewald** [comment]
+1

**Comment by makortel** [comment]
Is clang using C++14 already? I've understood that in C++11 constexpr impliest const for member functions (while in 14 not). Anyway, it's trivial to add the consts and I can do it tomorrow. Is separate PR ok, or is the fix needed in this one?

**Comment by davidlt** [comment]
CMSSW moved to C++14 as default in 7_5_X.

**Comment by makortel** [comment]
Ok, that explains (was that announced somewhere and I just missed it? I do recall Vincenzo's question in some HN but no answer to it). But why is gcc not complaining?

**Comment by davidlt** [comment]
I don't remember an announcement email. Well GCC is GCC and not everything is by a standard (would be yet another case), which might be fixed in newer GCC versions.

**Comment by makortel** [comment]
Ok, thanks.

**Comment by Martin-Grunewald** [comment]
Yes, great, let's just add more overhead!
OK, so how do I test this clang stuff? What flags tell my developer area to do that on default?
Do we need to keep both gcc and clang happy? How do I test both in one go?

**Comment by Martin-Grunewald** [comment]
Hi,

I think one needs to change
```
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-03-17-1400/src/FWCore/Utilities/interface/VecArray.h:70:25: note: 'size' declared here
    constexpr size_type size() noexcept { return size_; }
```
to
```
constexpr size_type size() noexcept const { return size_; }
```
right?

**Comment by slava77** [comment]
I compared this PR with changes in 74X PR #8343 and I see a difference in phase1 files (RecoTracker/IterativeTracking/python/Phase1PU70_TobTecStep_cff.py and 13 more )
The 74X version of these has ``` minGoodCharge = cms.double(2069) ``` before this PR, while the 75X version has "-1" (cut disabled?); so the clusterChargeCut PSet is not in place.

Is this a result of SLHC forward ports in 75X?

Other changes are consistent with 74X.

**Comment by makortel** [comment]
@Martin-Grunewald Yes, and I'm going to do it "now".

**Comment by makortel** [comment]
@slava77 Yes, this difference is related to the SLHC-porting. #8173 disabled CCC in Phase1 configuration files. After the consolidation by Vincenzo, the `-1` should be replaced with `SiStripClusterChargeCutNone` (but probably in a subsequent PR?).

**Comment by makortel** [comment]
@Martin-Grunewald The fix is in #8371, feel free to cherry-pick here if deemed necessary.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by slava77** [comment]
is the bot asleep again?

**Comment by makortel** [comment]
@Martin-Grunewald Referring to @davidlt's comment (https://github.com/cms-sw/cmssw/pull/8371#issuecomment-82798792), could you cherry-pick the fix here?

**Comment by Martin-Grunewald** [comment]
@makortel 
I had made the fix already - luckily same as yours.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
General question: would it make sense to set up the clang IBs for 75X? Or do we want to discover potential further "existing" errors by clang in PR tests?

@ktf

**Comment by davidlt** [comment]
@makortel CMSSW_7_4_X already for some time fully compiles under Clang. Currently we have CMSSW_7_4_CLANG_X and special IBs are not yet migrated to CMSSW_7_5_X. The problem was that each day some PR kept breaking CMSSW + Clang, thus pr-checker was updated also to test with Clang.

**Comment by makortel** [comment]
@davidlt The 74X clang IB presumably uses C++11? Ok, there are probably not that many cases in CMSSW where switching to C++14 breaks something (i.e. non-const constexpr methods).

**Comment by davidlt** [comment]
@makortel 7_4_X is still C++11, doesn't matter if it's GCC, Clang, or ICC. All use the same C++ standard we set.

**Comment by diguida** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8353	e122a45
compared to the code changes checked in https://github.com/cms-sw/cmssw/pull/8353	fd1dc4a, there are only changes in the FWCore/Utilities/interface/VecArray.h related to C++14 issue.


jenkins tests run ok and show no differences as expected

additional tests were done in connection with signoff of #8343 and are not repeated here

**Pull request merged**
