### PR TITLE
Switch off BTVHLTOfflineSource temporarily

### LINKED ISSUE #38626: Crash for run 355207-355208 in express StreamHLTMonitor
As pointed out here https://cms-talk.web.cern.ch/t/paused-jobs-for-run-355207-collisions/12561 the following error is encountered when running ```express_StreamHLTMonitor``` workflow for both runs 355207 and 255208

```
2022-07-07 09:05:58,824:CRITICAL:CMSSW:Error running cmsRun
{'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc7_amd64_gcc10', 'scramv1', 'CMSSW', 'CMSSW_12_3_6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '']}
CMSSW Return code: 8006

2022-07-07 09:05:58,824:CRITICAL:CMSSW:Error message: An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 355207 lumi: 582 event: 669724552 stream: 6
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module BTVHLTOfflineSource/'BTVHLTOfflineSource'
Exception Message:
RefCore: A request to resolve a reference to a product of type 'reco::Candidate' with ProductID '1:2358'
can not be satisfied because the product cannot be found.
Probably the branch containing the product is not stored in the input file.
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

full info can be found here:
```/afs/cern.ch/user/c/cmst0/public/PausedJobs/ExpressHLTMonitor/job/WMTaskSpace/cmsRun1```

a possible fix, even a temporary one, should be found urgently

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/38626 as suggested by @jfernan2 (thanks Javi)
Temporarily fix until BTV provides a better solution

#### PR validation:

Running on faulty express files is fine now

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is not a backport but @ttedeschi will submit the 12_4_X and 12_3_X backports

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix,btagging

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
@cmsbuild , please test
 * tho nothing will test it

**Comment by jfernan2** [comment]
FYI @marco-link @arsahasransu

**Comment by jfernan2** [comment]
FYI @marco-link @johnalison @JyothsnaKomaragiri @natalia-korneeva @SWuchterl as BTV HLT DQM And Validation Code Developers 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Btag_and_vertexing

**Comment by tvami** [comment]
> in light of https://github.com/cms-sw/cmssw/issues/38626#issuecomment-1177617148 should this PR be discarded in favor of a less invasive fix?

Yes, I'll close when the new PR is available.

**Comment by tvami** [comment]
closing in favour of https://github.com/cms-sw/cmssw/pull/38635

**Pull request closed without merging**
