### PR TITLE
CTPPS Strip detectors: updated mapping for dedicated run

### PR DESCRIPTION
**Pull request by nminafra**
This PR updates the mapping for Totem strip detectors for dedicated 90m run.
In more detail: one fiber was damaged and it was swapped with a working one in one of the detector packages that is not installed anymore.

Runs during the alignment fill can be used for the tests, for example run 314277.
Here a DQM sample:
[DQM dev](https://goo.gl/MJhSHQ)

Thanks

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
