### PR TITLE
Made GenericSelectorByValueMap a global::EDProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the CMS deprecation warnings.

#### PR validation:

Code compiles without issuing CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please abort
(trying to recover resources for the tests of more urgent PRs)

**Comment by aandvalenzuela** [comment]
Hi @perrotta,

Do you agree that I start the testing again in the aborted PRs? I can see now that [#39642](https://github.com/cms-sw/cmssw/pull/39642) and [#39644](https://github.com/cms-sw/cmssw/pull/39644) are finally running the comparison.

Thank you,
Andrea

**Comment by rappoccio** [comment]
+1

**Pull request merged**
