### PR TITLE
GTUpdates : All GTs updated with HCAL Pedestals with effective label

### PR DESCRIPTION
**Pull request by arunhep**
Motivation of separating the HCAL pedestals for HCAL SiPMs is given here : https://indico.cern.ch/event/680480/contributions/2787885/attachments/1556785/2448593/Dual_peds_S.A._Nov13_2017.pdf

# Summary of changes in Global Tags 
 
## RunI simulation 
 
   * **RunI Heavy Ions scenario** : [100X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun1_HeavyIon_v1) as [94X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun1_HeavyIon_v1/94X_mcRun1_HeavyIon_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunI Ideal scenario** : [100X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun1_design_v1) as [94X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun1_design_v1/94X_mcRun1_design_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunI Proton-Lead scenario** : [100X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun1_pA_v1) as [94X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun1_pA_v1/94X_mcRun1_pA_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunI Realistic scenario** : [100X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun1_realistic_v1) as [94X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun1_realistic_v1/94X_mcRun1_realistic_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

## RunII simulation 
 
   * **RunII Asymptotic scenario** : [100X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_asymptotic_v1) as [94X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_asymptotic_v1/94X_mcRun2_asymptotic_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII CRAFT scenario** : [100X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2cosmics_startup_deco_v1) as [94X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2cosmics_startup_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2cosmics_startup_deco_v1/94X_mcRun2cosmics_startup_deco_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII Heavy Ions scenario** : [100X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_HeavyIon_v1) as [93X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_HeavyIon_v1/93X_mcRun2_HeavyIon_v0): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * Insertion of L1T TwinMux tags
      * Insertion of L1T BTMF parameter tags

   * **RunII Ideal scenario** : [100X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_design_v1) as [94X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_design_v1/94X_mcRun2_design_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII Proton-Lead scenario** : [100X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_pA_v1) as [94X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_pA_v1/94X_mcRun2_pA_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII Startup scenario** : [100X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mcRun2_startup_v1) as [94X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_startup_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mcRun2_startup_v1/94X_mcRun2_startup_v1): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

## RunI data 
 
   * **RunI HLT processing** : [100X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_frozen_v1) as [94X_dataRun2_HLT_frozen_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_frozen_v1/94X_dataRun2_HLT_frozen_v5): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunI Offline processing** : [100X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_v1) as [94X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_v1/94X_dataRun2_v4): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * Insertion of L1T EMTF Forest tag

## RunII data 
 
   * **RunII HLTHI processing** : [100X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLTHI_frozen_v1) as [94X_dataRun2_HLTHI_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLTHI_frozen_v1/94X_dataRun2_HLTHI_frozen_v4): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII HLT relval processing** : [100X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_relval_v1) as [94X_dataRun2_HLT_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_relval_v1/94X_dataRun2_HLT_relval_v7): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunII Offline processing** : [100X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_v1) as [94X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_v1/94X_dataRun2_v4): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * Insertion of L1T EMTF Forest tag

   * **RunII Offline relval processing** : [100X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_relval_v1) as [94X_dataRun2_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_relval_v1/94X_dataRun2_relval_v7): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of other offline tags to bring this queue closer to offline dataRun2 queue

   * **RunII Prompt processing** : [100X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_PromptLike_v1) as [94X_dataRun2_PromptLike_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_PromptLike_v1/94X_dataRun2_PromptLike_v8): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **RunI HLT processing** : [100X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_dataRun2_HLT_frozen_v1) as [94X_dataRun2_HLT_frozen_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_dataRun2_HLT_frozen_v1/94X_dataRun2_HLT_frozen_v5): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

## Upgrade 
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v1) as [94X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v1/94X_upgrade2018cosmics_realistic_deco_v5): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of regular HCAL Pedestals
      * update of tracker misalignment scenario which is being used for MC V2

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v1) as [94X_upgrade2018_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v1/94X_upgrade2018_design_IdealBS_v6): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of regular HCAL Pedestals

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v1) as [94X_upgrade2018_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v1/94X_upgrade2018_realistic_v6): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of regular HCAL Pedestals
      * update of tracker misalignment scenario which is being used for MC V2

   * **PostLS2 realistic scenario** : [100X_postLS2_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_realistic_v1) as [DES19_70_V2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/DES19_70_V2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_realistic_v1/DES19_70_V2): 
      * first GT for postLS2 scenario with an update of HCAL electronics map. All other conditions are same as 2018 realistic.

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [100X_mc2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v1) as [94X_mc2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_peak_v1/94X_mc2017cosmics_realistic_peak_v5): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of tracker misalignment scenario which is being used for MC V2

   * **PhaseI 2017 cosmics scenario** : [100X_mc2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v1) as [94X_mc2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_deco_v1/94X_mc2017cosmics_realistic_deco_v5): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of tracker misalignment scenario which is being used for MC V2

   * **PhaseI 2017 design scenario** : [100X_mc2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v1) as [94X_mc2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_design_IdealBS_v1/94X_mc2017_design_IdealBS_v6): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html

   * **PhaseI 2017 realistic scenario** : [100X_mc2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v1) as [94X_mc2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_realistic_v1/94X_mc2017_realistic_v6): 
      * update of HCAL Pedestals with label effective : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360.html
      * update of regular HCAL Pedestals which are being used for MC V2
      * update of tracker misalignment scenario which is being used for MC V2

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
Attn @abdoulline

**Comment by arunhep** [comment]
please test

**Comment by abdoulline** [comment]
Thnx @arunhep

**Comment by arunhep** [comment]
+1

- no changes in Run-1 and data wfs. This is expected because the tags inserted for HCAL pedestals have no consumer code right now.
- 2017 Mc wf changes are because of other updates like tracker misalignment scenario and HCAL regular pedestal updates

**Comment by davidlange6** [comment]
+1

**Comment by mmusich** [comment]
Hi @arunhep,
clicking by curiosity on the hyperlinks in your [description](https://github.com/cms-sw/cmssw/pull/21395#issue-275582810https://github.com/cms-sw/cmssw/pull/21395#issue-275582810), at least all the __2017_MC__ ones are broken. I think `*x_upgrade2017*` in the GT name  should be renamed `*X_mc2017*` in the browser hyperlinks, isn't it?

**Comment by arunhep** [comment]
thanks @mmusich for pointing it out.
I corrected them and check all others as well.

**Comment by kpedro88** [comment]
@arunhep can we also get a 2019 design GT?

**Comment by arunhep** [comment]
@kpedro88 can you tell us what are the different use cases in near future for design and realistic 2019 GTs ? I called it realistic because the starting point of this GT is 2018 realistic.
I don't want to have too many queues open already if we don't foresee updates separate for design and realistic in near future.

**Comment by kpedro88** [comment]
@arunhep since we've had both design and realistic for 2017 and 2018, I assume it will be desired for 2019 as well. The workflow already exists, so needs a corresponding GT. I don't expect many updates will be made to it in the near future - it can just start from 2018 design + new HCAL emap.

**Comment by arunhep** [comment]
@kpedro88 alright. why don't you point me to both the realistic and design workflows for 2019 or better postLS2 and I will open a PR with addition of this extra key and switch those workflows to consume these GTs instead of 2018 ones.

**Comment by abdoulline** [comment]
@arunhep 
Arun, unfortunately we need to update  Run 1 and Run 2 GTs with fixed pedestals conditions listed here:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3360/3/2.html
Sorry for inconvenience...

**Pull request merged**
