### PR TITLE
L1T: address issue 36647 with int overrun

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Fixes undefined behavior from int overruns. Addressing issue https://github.com/cms-sw/cmssw/issues/36647

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
@cecilecaillol did you check that this PR actually fixes the issue?
At a first sight, it just moves it to `etComponentSum`...

**Comment by perrotta** [comment]
> @perrotta How can I check if the PR fixes the issue?

@Dr15Jones opened https://github.com/cms-sw/cmssw/issues/36647, perhaps he can provide some suggestion

**Comment by perrotta** [comment]
hold
(while waiting for the confirmation that the fix as implemented is effective)

**Comment by perrotta** [comment]
@cecilecaillol @emanueleusai any suggestion about how to proceed here?

**Comment by cecilecaillol** [comment]
@perrotta I can make etComponentSum a long int too, but I still dont know how to check if this will actually solve the problem.

**Comment by perrotta** [comment]
@Dr15Jones @smuzaffar @makortel : can any of you suggest us how to run UBSAN on the proposed fix, so that it can be verified its effectiveness (or further adjust, if needed) before merging it?

**Comment by smuzaffar** [comment]
please test for CMSSW_12_4_UBSAN_X
this is run relval for UBSAN and then one can check workflow [1000.0/step2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_12_4_UBSAN_X_2022-04-25-1100/pyRelValMatrixLogs/run/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step2_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT.log#/3523) if this has fixed the ubsan issues

**Comment by smuzaffar** [comment]
so looks like it does fix the `L1Trigger/GlobalCaloTrigger/src/L1GctJetFinderBase.cc:580:19: runtime error: signed integer overflow: 268432611 * 157 cannot be represented in type 'int'` issue. Though there are only issues e.g. `DQM/L1TMonitor/src/L1TGMT.cc:205:40: runtime error: signed integer overflow: 15991514 * 3564 cannot be represented in type 'int'` but workfow `1000.0/step2` is now clean of https://github.com/cms-sw/cmssw/issues/36647

**Comment by Dr15Jones** [comment]
@perrotta as Shahzad has shown, if you create a build area from one of the UBSAN IBs 
```
scram project CMSSW_12_4_UBSAN_X_2022-04-25-1100
```
then build and run the RelVal workflow
```
runTheMatrix -l 1000.0
```
you should get the full UBSAN report.

**Comment by perrotta** [comment]
+1
- Thank you @cecilecaillol

**Pull request merged**
