### PR TITLE
backport of PR #7491 (regional PF clustering for muon)

### PR DESCRIPTION
**Pull request by HuguesBrun**
backport of PR #7491 

The PR is working fine in `CMSSW_7_3_1_patch1` but the compilation fails in the last IB (`CMSSW_7_3_X_2015-02-04-0200`): for this IB the RecoEgamma/EgammaHLTProducers package is not compiling even without the PR.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
I can't confirm any compilation failures - with or without this PR.

**Comment by Martin-Grunewald** [comment]
@cmsbuild  please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
Removing this plugin may be a problem - are all of these configs obsolete?

https://github.com/cms-sw/cmssw/search?utf8=✓&q=EgammaHLTRechitInRegionsProducer

**Comment by HuguesBrun** [comment]
Hi @davidlange6,
It is declared in the HLTRechitInRegionsProducer.cc:
https://github.com/HuguesBrun/cmssw/blob/usePFclusteringInRegionsForMuonsBackPort73/RecoEgamma/EgammaHLTProducers/src/HLTRechitInRegionsProducer.cc#L277
I did that to be consistent with what I did in CMSSW_7_4_X (PR #7491)

**Comment by davidlange6** [comment]
+1

ah - missed that. Thanks

**Pull request merged**
