### PR TITLE
DD Core Cleanup

### PR DESCRIPTION
**Pull request by ianna**
- Remove circular dependency
- Clean up commented out code
- Clean up unused code

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild :

```
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at hudson.remoting.Command.readFrom(Command.java:92)
	at hudson.remoting.ClassicCommandTransport.read(ClassicCommandTransport.java:70)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE
Sending e-mails to: cms-sdt-logs@cern.ch
Notifying upstream projects of job completion
Loading slave statistic
Slave statistic loaded

Deleting project workspace... 
Finished: FAILURE
```

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
