### PR TITLE
L1T BlockHeader changes for L1T ZS DQM

### PR DESCRIPTION
**Pull request by thomreis**
Added the ZS validation flag to the L1T BlockHeader to be used with the online DQM zero suppression module.
This is the 90x version of https://github.com/cms-sw/cmssw/pull/17956

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
backport of #17956

**Comment by thomreis** [comment]
@davidlange6 can this be merged to 90x? We took data this year with the 902 release where the ZS flag handled by this PR is set.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
