### PR TITLE
Turn-on by default the MaxSample algo for EB for gain-switching hits

### PR DESCRIPTION
**Pull request by emanueledimarco**
In 90X this is the tested option on both data and MC. It could be replaced by more sophisticated multifit versions if tested OK in time. 
This is related to PR #17259 (80X) and PR #17279 (90X).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@emanueledimarco 
if I'm not mistaken, in 80X we switched from max sample to global reco for the gain-switch
https://github.com/cms-sw/cmssw/pull/17308/commits/ed952acd6b5eb1fcc5ed3679a505b8276dc925d6

Is the implementation delivered with gainSwitchUseMaxSampleEB appropriate for that or will you need to make a change to it?

**Comment by argiro** [comment]
@slava77, ed952ac was for the re-miniaAOD fix, which is a patched workflow. This is a fix for the standard production workflow embedded in the multifit module.

**Comment by slava77** [comment]
@argiro 
just to clarify, do you mean that the issue with setting of kOutTime seen in the patched workflow is not happening here (and the flags are set appropriately)?

**Comment by argiro** [comment]
> On 08 Feb 2017, at 11:06, Slava Krutelyov <notifications@github.com> wrote:
> 
> @argiro
> just to clarify, do you mean that the issue with setting of kOutTime seen in the patched workflow is not happening here (and the flags are set appropriately)?
> 

yes, the Multifit module does set flags appropriately

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17442	d3d9722
- ecal EB hit reco change as described, affecting both data and MC
- jenkins tests pass and comparisons show small differences only in RunSinglePh2016B wf 136.731, consistent with the change made in this PR
- local test with single ele 1TeV gun shows mostly very small changes. The most significant change is in the low-chi2 EB rechit population; the hit energies are essentially unchanged; occasional changes in EB hit energies propagate downstream without any particular pattern

wf1316_eb_chi2

wf1316_eb_e5x5_over_sim

The effect on data with gain switch is expected to be significant, in agreement with earlier studies in 80X.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
