### PR TITLE
updates to tau3mu HLT producer

### PR DESCRIPTION
**Pull request by rmanzoni**
- add safety check on di-muon masses in order to remove duplicated muons (ad added rate)
- apply all selections but isolation at the tau building step (easier to compute isolation efficiencies)
- sort taus by pt
- fix isolation condition logic

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
