### PR TITLE
Removed duplicate cfi file in L1Trigger/L1CaloTrigger

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The same named cfi file was generated and placed in cfipython and the package's python directory.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
If one tried to use this `_cfi.py` file, it would attempt to load itself.

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
