### PR TITLE
add TracksFilter.cc (backport #21241)

### PR DESCRIPTION
**Pull request by mtosi**
backport #21241

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
-1
Just to take off our radars. It can be updated together with #21241, if still needed

**Comment by fabiocos** [comment]
@mtosi is this PR still needed or can be closed?

**Comment by mtosi** [comment]
it was meant to be used for an HLT path, which is no longer planned
we will re-open this if needed
thanks (for the patience as well)

**Pull request closed without merging**
