### PR TITLE
Porting PR #530 into CMSSW ahead of cms-l1t-offline

### PR DESCRIPTION
**Pull request by kkotov**
Following Vladimir's request I bring recent CaloL2 changes in CMSSW before cms-l1t-offline catches up.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by kkotov** [comment]
@rekovic The last two commits resolved conflicts of PR with the parallel cms-l1t-offline:l1t-integration-CMSSW_9_2_0. Now it is ready to be tested again and eventually merged

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@kkotov
Your last commit caused L1TStage2Layer2Producer to crash. 
Needs fix.

**Comment by kkotov** [comment]
@rekovic Screw this stuff. I ripped off all of the calo emulator and created a fresh O2O-only PR #19164

**Pull request closed without merging**
