### PR TITLE
Revert "Revert "CSJet update for fastjet-contrib 1.044""

### PR DESCRIPTION
**Pull request by mseidel42**
This reverts https://github.com/cms-sw/cmssw/pull/30838

Needs https://github.com/cms-sw/cmsdist/pull/6209

Multi-stream problems fixed in cms-sw/cmssw#30888

### CODE REVIEW

**Comment by agrohsje** [comment]
+1

**Comment by perrotta** [comment]
@intrepid42 did you test this PR and the attached external with (e.g.) wf 1302.18 multithread?
Please confirm that it runs now without errors, after #30888 has been merged

**Comment by intrepid42** [comment]
> @intrepid42 did you test this PR and the attached external with (e.g.) wf 1302.18 multithread?
> Please confirm that it runs now without errors, after #30888 has been merged

Hi @perrotta , yes, I verified this locally. Is it possible to have multithreaded unit tests? If yes I can add one, so that we spot this kind of error easier

**Comment by perrotta** [comment]
+1
- Identical to #30590, already merged and then reverted because of failures in multithread jobs
- Multi-stream issues were in Rivet, now fixed by #30888: this PR can then get re-merged now
- Technical for reco (true is the default input value for `set_do_mass_subtraction()` )
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
