### PR TITLE
L1T muon unpacker fix for crash with corrupt uGT RO record

### PR DESCRIPTION
**Pull request by thomreis**
This addresses the issue https://github.com/cms-l1t-offline/cmssw/issues/642 
The L1T muon unpacker was crashing when encountering an event with a corrupt uGT readout record.

Throwing an exception if a corrupt RO record is encountered since this data should not be used.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
type bugfix

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
