### PR TITLE
L1T offline DQM efficiency plots for the muons (9_1_X)

### PR DESCRIPTION
**Pull request by astakia**
Changes for the related code (PRs: #16233, #16234) to run centrally.
Based on the PR by @cbbrainerd and @z4027163 : #18085
This PR on the cms-sw:master : #18616

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport of #18085 and #18616

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
92x PRs #18085 and #18616 are already merged.

**Comment by thomreis** [comment]
@davidlange6 could you take a look at this please before 910 is made?
Your comments for error and warning messages that you made for #18085 are already being addressed in https://github.com/cms-sw/cmssw/pull/18706 and #18664 , respectively.

**Comment by davidlange6** [comment]
lets see if #18706 and #18664 (or #18662 I guess, signed for 5 minutes now) in fact get 92s back to a working state.

**Comment by astakia** [comment]
backport of #18616 and #18085

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
