### PR TITLE
[12_6_X] Nano: restore Run2/3 consistency between electron/photon IDs; remove scale+smearing correction for Run3

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

Backport of #40209, see description there

#### PR validation:

Same as #40209

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport needed for nanoAODv11 production in 12_6_X.

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
type egamma

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

Same changes as in #40209

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40209

**Comment by perrotta** [comment]
+1

**Pull request merged**
