### PR TITLE
Change CaloRecHitProducer to produce new HCAL RecHit SoA

### PR DESCRIPTION
**Pull request by jsamudio**
#### PR description:

This PR depends on #45238 and #45199. It implements changes to the `CaloRecHitSoAProducer` which disables the functionality of converting ECAL rechits, and changes the produced SoA to the new HCAL rechit SoA. This is the first integration step for the use of Alpaka HCAL rechits with the `PFRecHitProducer`.

#### PR validation:

Validated with workflow `12434.423` and checking the cluster DQM plots as well.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will need a backport to `14_0_X`

@fwyzard @hatakeyamak @kakwok

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fwyzard** [comment]
@jsamudio could you squash the last commit into the previous one ?

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
@jsamudio I've open the 14.0.x backport in #45278.

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
type pf, hcal

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
