### PR TITLE
AMPT bug (related to #23573) fixing 

### PR DESCRIPTION
**Pull request by wouf**
Fixing AMPT bug related to #23573 warning.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@wouf thank you for this, the fix look trivial and safe. Which real test on a ampt workflow was done? This code is not run in the usual PR tests, and I guess we have not even relvals for it

**Comment by wouf** [comment]
@fabiocos I tested it with CMSSW_10_2_0_pre5 - it worked fine.

**Comment by fabiocos** [comment]
@wouf thank you, I assume it worked fine also from the physics output point of view, did you produce some validation plot?

**Comment by wouf** [comment]
No no physical related changes was made. The changes is made for the case of ISUB=161, which is a process of the Higgs sector. AMPT author's limited tests shows that this location is never reached. To check if this right Zi-Wei (original AMPT author), asked to put the "stop" command here (and report to him if this unexpected case will happend), so in this version simulation will abort here.

**Comment by fabiocos** [comment]
@wouf ok, thank you

**Comment by fabiocos** [comment]
+1

**Pull request merged**
