### PR TITLE
Backport of #10356: Allow selection of subdetector for track splitting

### PR DESCRIPTION
**Pull request by hroskes**
Focus track splitting validation on any subdetector by requiring 2 hits there.  The default is still BPIX (which was hardcoded before).

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hroskes** [comment]
@mmusich @cmsbuild
I added 2 more (trivial but useful) commits, hopefully @cmsbuild will reset and be happier this time

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild 
let's see hopefully this time we get rid of these DAS failures

**Comment by mmusich** [comment]
+1
for https://github.com/hroskes/cmssw/commit/3182b374bc4a3f82ee59dbed6e8e5065f950c8d0

**Comment by davidlange6** [comment]
+1

**Pull request merged**
