### PR TITLE
Update python tests - py3 only

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Updates python tests to py3 only for https://github.com/cms-sw/cmsdist/pull/6770

#### PR validation:

all tests run with the default IB

### CODE REVIEW

**Comment by davidlange6** [comment]
Hi @mrodozov - could you instead do this for all of the tests in this directory? (Or I can make a PR)

**Comment by mrodozov** [comment]
@davidlange6 yes sure I'll update it

**Comment by mrodozov** [comment]
please test

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
