### PR TITLE
MTD geometry: add BTL V3 (one crystal thickness only) to MTD scenario I17 (global scenario D105)

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR adds a new BTL scenario V3 on top of the just integrated MTD scenario I17, added in #43407 . This new configuration, developed by @pauris123 , differs from V2 for the crystal thickness, set everywhere to 3.75 mm, as it will be in reality (purchase order ongoing). This is the opportunity to drop the crystal thickness from the geometry construction, and have 6 equal readout units along z. 

The numbering scheme for the time being is just adapted to the existing ```BTLDetId```, creating an effective crystal thickness index, so as to postpone the major update to the moment in which the BTL V1 can be finally dropped, allowing us to optimize the bit fields structure for a final configuration.

#### PR validation:

All basic geometry checks (when geometry scenario is adapted) look reasonable, and a complete workflow runs. No overlap is detected at ideal geometry level, and visual inspection in fireworks appears ok.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 27634.0

**Comment by srimanob** [comment]
+Upgrade

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Pull request merged**
