### PR TITLE
Modernize plugins in `DQM/BeamMonitor`

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR migrates from `edm::EDAnalyzer` to  `edm::one::EDAnalyzer<>` the last plugins in the `DQM/BeamMonitor` package
that were reported by the Static Analyzer in [the latest IB report for 12_1_X](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_1_X_2021-09-30-1100/slc7_amd64_gcc900/llvm-analysis/index.html).
I also fixed some dead assignment in the same package that were again reported by the SA.

Not being the original author of these plugins, and since most of them are untouched since a couple of years, I would
like to have comments on whether the migration was done propely or not.

[EDIT] after the comments received the plugins have been actually migrated to use `DQM*EDAnalyzer`s.

#### PR validation:
Code compiles

#### Backport:
Not a backport, no backport needed.

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
FYI @tvami

**Comment by jfernan2** [comment]
+1

**Comment by francescobrivio** [comment]
fyi @mmusich 
not sure if you have more info on these plugins...?

**Comment by mmusich** [comment]
Hi @francescobrivio in this specific pacakage there's the stuff that runs in offline DQM to check the different BeamSpots (online, offline from DB, from fit, etc.) 
On the ones you touched I am not totally sure if they are run or not in production.
But in general shouldn't those become `DQMEDAnalyzer`s instead?

**Comment by francescobrivio** [comment]
> Hi @francescobrivio in this specific pacakage there's the stuff that runs in offline DQM to check the different BeamSpots (online, offline from DB, from fit, etc.) On the ones you touched I am not totally sure if they are run or not in production. But in general shouldn't those become `DQMEDAnalyzer`s instead?

@mmusich Yea that's a good point, I'll do that! 
But just to be sure is there any documentation describing `DQMEDAnalyzer` vs `edm::one::EDAnalyzer`?
Also, should the `TKStatus.h` plugin: https://github.com/cms-sw/cmssw/blob/a686932f1b9c01341d8936a04bb95ca540308772/DQM/BeamMonitor/plugins/TKStatus.h#L26 be migrated as well?
(sorry to bother with questions on packages that are not really your responsibility 😅 )

**Comment by mmusich** [comment]
>  Also, should the TKStatus.h plugin: 

I think that should stay as is (e.g. `edm::one::EDAnalyzer`). 
I am wondering if @sikler knows more about it.

**Comment by francescobrivio** [comment]
> HTH

It does!Thanks I'll have a look and migrate to DQMEDAnalyzer

**Comment by jfernan2** [comment]
Just to clarify:
- in Online DQM we may not core about concurrent LSs, since data are processed linearly as they come.
- in Offline DQM, concurrent LSs are a problem, and that's why all the DQM classes were introduced

**Comment by francescobrivio** [comment]
hold

 - migration to DQMEDAnalyzer possibly needed, to be checked

**Comment by francescobrivio** [comment]
unhold

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
Nice, now we know what runs in production;)

**Comment by francescobrivio** [comment]
I think I forgot to update the configurations, _i.e._ I should propagate the `DQMOneEDAnalyzer` changes to all the occurrencies such as:
https://github.com/cms-sw/cmssw/blob/1c158e71216d54113a909581cdad111e675bcb86/DQM/BeamMonitor/python/AlcaBeamMonitorClient_cfi.py#L3

Sorry about that! 😅 I'll get back to this asap!

**Comment by francescobrivio** [comment]
@mmusich I see some difference in the Tracking comparison (e.g. [wf 9.0 results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-05-1100+e03a95/45987/9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST/Tracking.html)) and sometimes in the HLT comparisons as well (e.g. [wf 11634.0 results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-10-05-1100+e03a95/45987/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/)).
I believe for the tracking case they come from the `dqmHarvestingFakeHLT` step, specifically from:
https://github.com/cms-sw/cmssw/blob/668228d3a520915d44d3bd4933e76d4a5f8a1978/DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py#L81
but I'm not sure how to interpret them...any help?

**Comment by mmusich** [comment]
@francescobrivio they don't look related to your changes

**Comment by francescobrivio** [comment]
> @francescobrivio they don't look related to your changes

Thanks! I will re-trigger the tests now that a new IB should be availble, let's see how it goes...

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
By the way,  isn't 

> `edm::EDAnalyzer to DQMOneEDAnalyzer<edm::one::WatchLuminosityBlocks>`

deprecated?
https://github.com/cms-sw/cmssw/issues/25090#issuecomment-665681777

**Comment by jfernan2** [comment]
> 
> 
> By the way, isn't
> 
> > `edm::EDAnalyzer to DQMOneEDAnalyzer<edm::one::WatchLuminosityBlocks>`
> 
> deprecated? [#25090 (comment)](https://github.com/cms-sw/cmssw/issues/25090#issuecomment-665681777)

Yes, you are right... I had not realized, we were using this in the last round of changes

**Comment by francescobrivio** [comment]
Closing for now, I will go back to work on this when I have a bit more time (added to my todo list).

**Pull request closed without merging**
