### PR TITLE
[13_0_X backport] Fall17V2 Electron IDs and Isolations saved only in Run2 Nanos

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

Backport of PR #42726. See description there. 

#### PR validation:

Same as PR #42726. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport required for processing of 2022 and 2023 data/MC which will happen in 13_0_X.

### CODE REVIEW

**Comment by antoniovilela** [comment]
please test

**Comment by Prasant1993** [comment]
> please test

hi @antoniovilela, We should first do "enable nano" and execute the test command.

**Comment by antoniovilela** [comment]
> > please test
> 
> hi @antoniovilela, We should first do "enable nano" and execute the test command.

True, thanks.

**Comment by antoniovilela** [comment]
please abort

**Comment by antoniovilela** [comment]
enable nano

**Comment by antoniovilela** [comment]
please test

**Comment by rappoccio** [comment]
@cms-sw/xpog-l2 is this one ready to go?

**Comment by jordan-martins** [comment]
Hi,
We should include this in a new 130X and then cut the release. We need to start the Re-mini and Re-nanos now-ish.

Thanks,
PPD
@malbouis

**Comment by simonepigazzini** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
