### PR TITLE
CTPPS: backport of diamond track fitting to 8_0_X

### PR DESCRIPTION
**Pull request by forthommel**
Backport of #17817 to the `8_0_X` branch for the foreseen re-reconstruction of 2016 data.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@forthommel this wasn't on the required feature list for the legacy. So, it may make it in the shadow of other needed features.

**Comment by forthommel** [comment]
@slava77 thanks for the build. Indeed, as discussed outside this scope we wanted the RecHits and geometry (along with all other changes backported through #17815) to be present in `8_0_X`, but we were also interested in having the tracks (once tested and merged in `9_1_X` with #17817).

**Comment by forthommel** [comment]
Hi @slava77, @davidlange6! Can we expect this backport to be part of the next `8_0_X` release?

**Comment by slava77** [comment]
backport of #17817
to get the bot add a backport label

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18238	e5717ca
- changes are the same as in 91X version https://github.com/cms-sw/cmssw/pull/17817 1744996 which went to 910pre2 and there were apparently no issues at run time in relvals (although 2016H where diamonds are present is not a part of relvals)
- jenkins tests pass and comparisons show no differences while the size check reports changes (expected as seen in 91X PR tests)

This was requested earlier for legacy rereco if it makes it in time before release build.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
