### PR TITLE
Improved handling of slimmedGenJets in JetFlavour and GenHFHadronMatcher

### PR DESCRIPTION
**Pull request by bartosik-hep**
- Protected **JetFlavour** tool against missing jet constituents in **miniAOD**. No crashes any more.
- Switched off jet reclustering in the test configuration of **GenHFHadronMatcher** in **miniAOD**.
  - Excluded neutrinos from reclustered jets in **AOD** to match the ones in **miniAOD**.

### CODE REVIEW

**Comment by bartosik-desy** [comment]
Dear @vadler, @monttj, as far as I understand this PR is not yet merged. Do you know if there are going to be some further checks or can it be merged already now? And maybe you know the approximate schedule for the next CMSSW_7_6_X release, when the changes from this PR are expected to be integrated for general use?

**Comment by monttj** [comment]
+1
I am sorry it is delayed. I expect it could be merged into next release in two weeks?

**Comment by monttj** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
