### PR TITLE
DD4Hep: Tracker Algorithm Migration DDPixBarLayerUpgrade 

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Tracker Algorithm Migration ```DDPixBarLayerUpgrade```

#### PR validation:

Screenshot from 2019-07-25 10-56-24

```
cmsRun DetectorDescription/DDCMS/test/python/testDDPixBarLayerUpgradeAlgorithm.py
cmsShow -c $CMSSW_RELEASE_BASE/src/Fireworks/Core/macros/simGeo.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=testPixBarLayerUpgradeAlgo

```

FYI: @ianna

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by vargasa** [comment]
#### PR validation:

Screenshot from 2019-07-25 10-56-24

```
cmsRun DetectorDescription/DDCMS/test/python/testDDPixBarLayerUpgradeAlgorithm.py
cmsShow -c $CMSSW_RELEASE_BASE/src/Fireworks/Core/macros/simGeo.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=testPixBarLayerUpgradeAlgo

```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
