### PR TITLE
Cleanup of dependencies from CondDBv1 code by moving to CondDBv2, and new interface for logging and FronTier security

### PR DESCRIPTION
**Pull request by ggovi**
- Clean up from CondDBv1: removed dependencies from packages: `CondCore/DBCommon`, `CondCore/ORA`, `CondCore/MetaDataService`, `CondCore/TagCollection`, in particular in `Configuration/StandardSequences/python/FrontierConditions_GlobalTag_cfi.py` used by `cmsDriver` to set up condition access.
- Added `TagLog` functionality
- Added the possibility to configure Frontier connection in order to request the server sends digital signatures on every response. This is done by setting a `string` data member in `ConnectionPool` or the corresponding parameter in a `ParameterSet`. An unit test has been added. The default is `""`, so the current behaviour is kept.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@davidlange6 
This PR should fix the problem ( that was probably not visible with merge-topic ). The corresponding branch has been rebased on the IB of 01-19-1100. Is this ok?
Please let us know if you want the branch rather to revert your revert...

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlt** [comment]
This had some disastrous effect, `Fail: 306` on `slc6_amd64_gcc530` which was the only full rebuild.

**Comment by davidlange6** [comment]
backing out again (lets understand why our build checks aren't catching this via developer builds / PR tests.

**Comment by davidlt** [comment]
Removals. Because IBs / patch releases are based on other releases, whatever is removed is still found in base release.

**Comment by mmusich** [comment]
@ggovi as privately discussed RelVals were failing because of this: 
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py#L3

```
File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-01-22-2300/python/RecoTauTag/Configuration/RecoPFTauTag_cff.py", line 57, in <module>
    from RecoTauTag.Configuration.HPSPFTaus_cff import *
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-01-22-2300/python/RecoTauTag/Configuration/HPSPFTaus_cff.py", line 32, in <module>
    from RecoTauTag.Configuration.loadRecoTauTagMVAsFromPrepDB_cfi import *
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_X_2016-01-22-2300/python/RecoTauTag/Configuration/loadRecoTauTagMVAsFromPrepDB_cfi.py", line 3, in <module>
    from CondCore.DBCommon.CondDBSetup_cfi import *
ImportError: No module named DBCommon.CondDBSetup_cfi
```

**Pull request merged**
