### PR TITLE
NanoAOD developments, 29Nov2018 version [104X part 2]

### PR DESCRIPTION
**Pull request by peruzzim**
This is to sync master to the latest NanoAOD developments added in #25368 (updated ecalBadCalibFilter + fixes to EGM ID and energy scale in 2016).

It also customises the RecHit input collection in ecalBadCalibFilter when running with nanoAOD modifiers, as done in #25459.

Does not depend on any other PR not yet merged.

### CODE REVIEW

**Comment by peruzzim** [comment]
please test

**Comment by peruzzim** [comment]
+xpog

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25473	4c00a4a
- reco part of the code changes are in line with the PR description. @peruzzim thank you for synchronizing the part of RecoMET/METFilters/python/ecalBadCalibFilter_cfi.py which diverged in the last 10_2_X PR #25459
- jenkins tests pass and comparisons with the baseline show no differences up to nanoAOD
    - nanoAOD step in 1325.7_TTbar_13_94Xv2NanoAODINPUT*/step2.root now has a ```Product added nanoaodFlatTable_extraFlagsTable__DQM.```
    - I'm a bit surprised that nothing else has changed in 1325.7 (```--era Run2_2017,run2_nanoAOD_94XMiniAODv2```) or in 10824.0 (```--era Run2_2018 ```). Apparently all relevant modifications went with a different modifier, which is not checked.

**Comment by peruzzim** [comment]
@slava77 that sounds correct, changes were in 80X and 94Xv1 + the new flags in that added table.
As we agreed, we're going to update the tests to check all combinations in a later PR.

**Comment by fabiocos** [comment]
@peruzzim but as these tests are not probing the latest modifier, was this at least tested privately? I guess this happened in your build procedure, just would like to ensure

**Comment by peruzzim** [comment]
@fabiocos yes, it went through default testing plus, for additional confidence, I manually re-tested that the PR runs using the last IB (the validation procedure is now messed up a bit by the many dependencies that are needed on top of the last built non-IB release...). The same was done for the 102X version.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
