### PR TITLE
added new Utilities/OpenSSL and move unit tests to it

### LINKED ISSUE #37523: CS9 OpenSSL deprecated functions warnings and thread safety
For CS9 IBs (where we have OpenSSL 3.0) we have many warnings like [a]. I opened a PR https://github.com/cms-sw/cmssw/pull/37490 to fix it. I think we can fix allof these by using `EVP_Digest*` function.  But I just noticed that the following code is not thread safe 
```
#if OPENSSL_API_COMPAT < 0x10100000L
  OpenSSL_add_all_digests();
  EVP_MD_CTX* mdctx = EVP_MD_CTX_create();
#else
  OPENSSL_init_crypto();
  EVP_MD_CTX* mdctx = EVP_MD_CTX_new();
#endif
```
Specially call to `OpenSSL_add_all_digests() or OPENSSL_init_crypto()` which should be call once .  @makortel any idea how to achieve it properly? 

[a]
```
src/L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:84:17: warning: 'int SHA1_Init(SHA_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    84 |   if (!SHA1_Init(&ctx))
      |        ~~~~~~~~~^~~~~~
In file included from src/L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:75:
/usr/include/openssl/sha.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
      |                           ^~~~~~~~~
  src/L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:87:19: warning: 'int SHA1_Update(SHA_CTX*, const void*, size_t)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    87 |   if (!SHA1_Update(&ctx, buf, len))
      |        ~~~~~~~~~~~^~~~~~~~~~~~~~~~
In file included from src/L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:75:
/usr/include/openssl/sha.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~~
  src/L1TriggerConfig/Utilities/src/L1TCaloParamsViewer.cc:91:18: warning: 'int SHA1_Final(unsigned char*, SHA_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    91 |   if (!SHA1_Final(hash, &ctx))
```

### PR DESCRIPTION
**Pull request by smuzaffar**
This fixes https://github.com/cms-sw/cmssw/issues/37523 . 
`OpenSSL_add_all_digests and OPENSSL_init_crypto` are not thread-safe. So as suggested in https://github.com/cms-sw/cmssw/issues/37523#issuecomment-1095083240, I added  utility function to initialize openssl.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

@cms-sw/db-l2 , any objection on this change

**Comment by tvami** [comment]
+db
 * looks good!

**Comment by perrotta** [comment]
+1

**Pull request merged**
