### PR TITLE
[10_6_X] Removed duplicated muons in HepMC to G4 interface

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39427 
This PR substitute #39436

#### PR validation:
private

Backport of https://github.com/cms-sw/cmssw/pull/39427

### CODE REVIEW

**Comment by civanch** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39427

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
@perrotta @rappoccio this is essentially fully signed now

**Comment by tvami** [comment]
I agree that `FixForFinalStateRadiation` is a more clear name indeed.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Comment by SohamBhattacharya** [comment]
Hi, I have a naive question:
Is it enough to add `--procModifiers run2_final_state_rad` to cmsDriver to enable this fix?

**Comment by tvami** [comment]
Yes, from `CMSSW_10_6_31` on

**Comment by SohamBhattacharya** [comment]
> Yes, from `CMSSW_10_6_31` on

@tvami Unfortunately that does not seem to work -- the config builder [1] tries to import the modifier from `Configuration.ProcessModifiers.run2_final_state_rad_cff` and complains that it cannot find a module called `run2_final_state_rad_cff`, as the modifier actually exists as `Configuration.Eras.Modifier_run2_final_state_rad_cff`.
Of course when running locally I can just move and rename the modifier file appropriately, but I was wondering how to get this to work with cmsDriver, as that would be needed for central MC requests.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_31/Configuration/Applications/python/ConfigBuilder.py#L2105-L2106

**Comment by tvami** [comment]
:(

would `--procModifiers Modifier_run2_final_state_rad_cff` work?

**Comment by SohamBhattacharya** [comment]
> :(
> 
> would `--procModifiers Modifier_run2_final_state_rad_cff` work?

Unfortunately not, as the config builder tries to get it from `Configuration.ProcessModifiers`, whereas this exists under `Configuration.Eras`.

**Comment by tvami** [comment]
That's unfortunate, do you want to submit the PR that fixes this, or should I? (And then we'll need a new release [again])

**Comment by SohamBhattacharya** [comment]
> That's unfortunate, do you want to submit the PR that fixes this, or should I? (And then we'll need a new release [again])

I could do it, if that's fine.

**Pull request merged**
