### PR TITLE
Better exception message from ESSourceProductResolverBase

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Improved the exception message originating from ESSourceProductResolverBase
- convert non cms::Exception
- include which data product is begin retrieved in message

#### PR validation:

Code compiles. I tested it in a situation where an inheriting resolver was throwing a non-cms exception. The new message is a great improvement.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@wddgit please review

**Comment by wddgit** [comment]
I'll take a look after lunch.

**Comment by Dr15Jones** [comment]
please test

**Comment by wddgit** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
