### PR TITLE
EMTF remove core_gen_summer_2013

### PR DESCRIPTION
**Pull request by abrinke1**
Pre-PR to streamline PR #20286 
Removes 56 unused files from the 2016 EMTF emulator
Should be mergable ASAP

### CODE REVIEW

**Comment by abrinke1** [comment]
@rekovic @davidlange6 
Please test.

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
