### PR TITLE
STEAM : (re)enable HLTDQM in the main sequence

### PR DESCRIPTION
**Pull request by mtosi**
as discussed with DQM core,
TSG would need to (re)enable the whole HLTDQM @Tier0,
when the DQM step is run on the physics PDs (SingleMuon, ZeroBias, etc.)

modules which were in the @ExtraHLT are now back in the main sequence

I ran the 136.868 test of the runTheMatrix,
and because it is using DQM:@standardDQM+@ExtraHLT+@miniAODDQM (relval),
I also ran DQM:@standard (standard), DQM (default), DQM:@common (common), DQM:@ExtraHLT (extraHLT)

what I get is the following
relval.memory:Total bytes: 220.97 MiB
TOT 56844333 #histos: 174781
HLT 18221303 ( 32.1 %) #histos: 78773 ( 45.1 %)

standard.memory:Total bytes: 208.91 MiB
TOT 54330445 #histos: 161181
HLT 17014257 ( 31.3 %) #histos: 67378 ( 41.8 %)

default.memory:Total bytes: 210.83 MiB
TOT 54620382 #histos: 169106
HLT 17304194 ( 31.7 %) #histos: 75303 ( 44.5 %)

common.memory: Total bytes: 122.65 MiB
TOT 35190979 #histos: 132342
HLT 11663074 ( 33.1 %) #histos: 70968 ( 53.6 %)

extraHLT.memory:Total bytes: 76.73 MiB
TOT 25188338 #histos: 105527
HLT 12431752 ( 49.4 %) #histos: 73530 ( 69.7 %)

as far as I know / read / understand / discuss about,
Tier0 runs @common in many PDs

ps: I also tried to clean the HLT directory
- B2GHLTOffline --> B2G
- Higgs --> HIG
- Photon --> EXO/Photon or HIG/DiPhoton or EGM/Photon
- TopHLTOffline --> TOP

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
ciao
as agreed yesterday
I reran the DQM:@common in both the default 10_2_0 and w/ the updates from this PR
and the outcome is the summarized by [1]
hope it is fine, please let me know if I can do extra tests

thanks !

[1]
dqmMemoryStats.py -i common_PR24155_DQM_V0001_R000317435__Global__CMSSW_X_Y_Z__RECO.root -r common_ref_DQM_V0001_R000317435__Global__CMSSW_X_Y_Z__RECO.root -x --summary -d 2
********************************************************************************
************************* DQM level 2 folder breakdown *************************
* Size cutoff: 512.00 KiB                                                      *
********************************************************************************
11.77 MiB        HLT/JME
4.68 MiB         HLT/HIG
4.07 MiB         HLT/TOP
3.44 MiB         HLT/SUSY
3.21 MiB         HLT/EXO
2.14 MiB         HLT/EGM
1.36 MiB         HLT/BTV
1.17 MiB         HLT/B2G
Total bytes: 31.85 MiB

**Comment by schneiml** [comment]
Thanks @mtosi!

As mentioned in person, I don't see _technical_ problems with adding  another 30MB on top of the 120MB that we already have in `common`; the Tier0 memory fix from earlier this year should easily allow for that. There are many other things that could be unhappy with the larger output, but since we had larger files before, and were only limited by the Tier0 memory, I think there should not be any issue.

Of course there is a whole independent  discussion of how to fairly allocate space in DQM to the subsystem, but given the special role of HLT for CMS, I also have no concerns there. 

So, I think we are good to go with this. We should pre-warn Tier0 to watch the memory in their validation (once this hits a release), but I don't expect problems.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@mtosi @schneiml @andrius-k as far as I can see the addition of lines is in old data workflows, and should not massively affect 2018 workflows. Still I see lots of warning messages that suggest that modules are not really run, and this should be better fixed

**Comment by fabiocos** [comment]
%MSG-w TopMonitor:  TopMonitor:topElecMuonHLTMonitor_Mu12Ele23_ref  13-Aug-2018 11:45:25 CEST Run: 315489 Event: 47769870
Electron ID handle not valid 

%MSG

what is the point of running these modules?

**Comment by mtosi** [comment]
@fabiocos thanks for pointing this, I did not realize it :(
when I ran the DQM:@common which should represent the DQM sequence run on the different PDs at Tier0, I did not find any warning messages like that

I found

> ******************* RunOnData *******************
> ************** MC dependence removal ************
> removing MC dependencies for photons
> removing MC dependencies for out of time photons
> removing MC dependencies for electrons
> removing MC dependencies for muons
> removing MC dependencies for taus
> removing MC dependencies for taus boosted
> removing MC dependencies for jets
> adding L2L3Residual JEC for: patJetCorrFactorsAK8
> adding L2L3Residual JEC for: patJetCorrFactorsPuppi
> adding L2L3Residual JEC for: patJetCorrFactorsAK8PFCHSSoftDrop
> adding L2L3Residual JEC for: patJetCorrFactorsAK8PFPuppiSoftDropSubjets
> adding L2L3Residual JEC for: patJetCorrFactors
> adding L2L3Residual JEC for: patJetCorrFactorsAK8PFPuppiSoftDrop
> adding L2L3Residual JEC for: patJetCorrFactorsNoHF
> adding L2L3Residual JEC for: patJetCorrFactorsAK8Puppi
> adding L2L3Residual JEC for: patJetCorrFactorsTransientCorrectedSlimmedAK8DeepDoubleB
> adding L2L3Residual JEC for: patJetCorrFactorsTransientCorrectedSlimmedDeepFlavour
> 09-Aug-2018 17:03:46 CEST  Initiating request to open file file:step2.root
> 09-Aug-2018 17:03:48 CEST  Successfully opened file file:step2.root
> %MSG-w L1TStage2uGTTiming:  L1TStage2uGTTiming:l1tStage2uGTTiming@beginRun  09-Aug-2018 17:05:23 CEST Run: 317435
> Algo "L1_SingleIsoEG30er1p5" not found in the trigger menu L1Menu_Collisions2018_v1_0_0. Could not retrieve algo bit number.
> %MSG
> %MSG-w L1TStage2uGTTiming:  L1TStage2uGTTiming:l1tStage2uGTTiming@beginRun  09-Aug-2018 17:05:23 CEST Run: 317435
> Algo "L1_SingleEG15" not found in the trigger menu L1Menu_Collisions2018_v1_0_0. Could not retrieve algo bit number.
> %MSG
> %MSG-w L1TStage2uGTTiming:  L1TStage2uGTTiming:l1tStage2uGTTiming@beginRun  09-Aug-2018 17:05:23 CEST Run: 317435
> Algo "L1_SingleJet60_FWD" not found in the trigger menu L1Menu_Collisions2018_v1_0_0. Could not retrieve algo bit number.
> %MSG
> Begin processing the 1st record. Run 317435, Event 90109054, LumiSection 69 on stream 0 at 09-Aug-2018 17:05:55.940 CEST
> %MSG-w Configuration:  HLTHighLevel:ALCARECOTkAlMinBiasNOTHLT  09-Aug-2018 17:05:56 CEST Run: 317435 Event: 90109054
> none of the requested paths and pattern match any HLT path - no events will be selected
> %MSG
> %MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigis  09-Aug-2018 17:06:06 CEST Run: 317435 Event: 90109054
> NULL pointer to FEDRawData for FED: id 434
> Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
> %MSG
> %MSG-e hltPrescaleTable:  PATTriggerProducer:patTrigger  09-Aug-2018 17:06:39 CEST Run: 317435 Event: 90109054
> No HLT prescale table found
> Using default empty table with all prescales 1
> %MSG
> Begin processing the 2nd record. Run 317435, Event 90343541, LumiSection 69 on stream 0 at 09-Aug-2018 17:06:42.848 CEST
> %MSG-w Configuration:  HLTHighLevel:ALCARECOTkAlMinBiasNOTHLT  09-Aug-2018 17:06:42 CEST Run: 317435 Event: 90343541
> none of the requested paths and pattern match any HLT path - no events will be selected
> %MSG

**Comment by mtosi** [comment]
may I ask some suggestions on how to get a reasonable workflow for testing the Teir0 configuration ?

in the meantime, I've already contacted the relevant parties (at least the ones related to the wrning message you pointed), and if I do not get an answer by tomorrow, I would suggest to put in DQM:ExtraHLT all the modules which are not ready to be run at the Tier0
=> we can start to have some HLTDQM produced at Tier0, at least

**Comment by schneiml** [comment]
Sadly, their are no runTheMatrix sequences that that represent Tier0 DQM well. The usual suspects (1001.2 for Express, 136.868 or similar for prompt) use DQM configs that are very far from Tier0 reality.

A quick grep shows that 1003.0 uses a DQM config that looks remotely Tier0-like, but on Run1 data, which might not be ideal for your purposes...

**Comment by mtosi** [comment]
@fabiocos , may I ask you some advise on how to proceed w/ his PR ?

where can I find the list of warning messages and/or the list of "bad guys" 
(modules which seem to trigger unwanted printouts) ?

I could check which is the sequence they are called by

thanks

**Comment by fabiocos** [comment]
@mtosi you may inspect the output of the relvals in the PR test , see above the link https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24155/29793/summary.html and go to Matrix Tests Outputs. 

In the comparison section you have the file 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-08-12-1100+24155/27964/validateJR/logRootQA.log
where the lines added are detailed for workflow. Anyway even when no new lines are added, I see lots of warning, for instance looking at the 2018 test workflow 136.85 step3 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24155/29793/runTheMatrix-results/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM.log

**Comment by fabiocos** [comment]
@mtosi @schneiml @andrius-k in order to speed up things, we may merge this PR as it is, and in the meanwhile a revision of the sequences producing warnings can be done. Anyway I would like to ensure that there is no issue with T0 workflows

**Comment by schneiml** [comment]
@fabiocos for final confirmation from Tier0, we will need a Tier0 replay. The thing that we are most worried about is that this will increase Tier0 memory consumption, and we need them to check if they are still happy with it (my guess is yes, but the final word is on them).

For the errors/warnings in general, I am not sure; I seems that nothing crashes, so I think trying to see what happens at Tier0 and fixing things later is an acceptable solution. In general, the problem is that there is not just one, but many Tier0 configurations, which run different subsets of DQM. The relvals run the union of these and more, so everything should be covered, but we don't know what precisley will happen in each of the PDs.

**Comment by fabiocos** [comment]
@schneiml on which input is this sequence supposed to run? One can try to reproduce a T0-like workflow using Configuration/DataProcessing Just picking a recent Express file from collisions data and building a T0 like configuration with Configuration/DataProcessing 

python RunExpressProcessing.py --scenario ppEra_Run2_2018 --global-tag 102X_dataRun2_Express_v1 --lfn /store/t0streamer/Data/HLTMonitor/000/321/124/run321124_ls0006_streamHLTMonitor_StorageManager.dat --fevt --dqmio 

(it requires specifying the correct input in the .py

process.source = cms.Source("NewEventStreamFileReader",
    fileNames = cms.untracked.vstring('/store/t0streamer/Data/HLTMonitor/000/321/124/run321124_ls0006_streamHLTMonitor_StorageManager.dat')
)

) it works, but if I pick the StreamExpress 

process.source = cms.Source("NewEventStreamFileReader",
    fileNames = cms.untracked.vstring('/store/t0streamer/Data/Express/000/321/124/run321124_ls0573_streamExpress_StorageManager.dat')
)

it fails:

----- Begin Fatal Exception 15-Aug-2018 10:25:34 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 321124 lumi: 573 event: 854929078 stream: 7
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module HTMonitor/'PFHT1050_Softdropmonitoring'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Jet
Looking for module label: ak8PFJetsPuppiSoftDrop
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

**Comment by schneiml** [comment]
@fabiocos thanks for giving the DataProcessing route a try, I have used these tools in the past but don't have a proper recipe (and then the risk of running something completely irrelevant is high, which is why I usually don't recommend it).

As I understand, the new sequences should run on all PDs (including Express), though HLT does not care about Express (@mtosi can confirm). They enter the prompt reco DQM sequence via `@common`, which is why testing only `@common` should be a good test (Tier0 will run additional, PD-dependent sequences as well, but those should be unmodified).

For Express, IIRC the `extra` was always turned on (via `@HLTMon`, which happens to be part of the default `DQMOffline`, that is usually only used in the relvals), so on the high level nothing should change. In the details, of course, all the HLT DQM config cleanup is used there as well.

**Comment by fabiocos** [comment]
@schneiml well, DataProcessing is the best emulation of the T0 workflows we have, so I would encourage to test it and understand what it does. I think that waiting for a T0 replay to realize whether something works or not is not a robust procedure. Anyway at this point I will merge this PR for a better validation in IB, but I would like to see these issues addressed before back-porting to a production version

**Comment by fabiocos** [comment]
+1

**Comment by schneiml** [comment]
@fabiocos re DataProcessing: Well, I hope it is not an emulation, but actually the real thing! (that is what I was promised...). The problem is that Tier0 things are always relative to the Tier0 config that is not part of CMSSW, so it requires a lot of care to get things right. While for a simple, approximate test, `runTheMatrix` does the job, and is a lot easier to use...

**Comment by davidlange6** [comment]
> On Aug 17, 2018, at 2:59 AM, Marcel Schneider <notifications@github.com> wrote:
> 
> @fabiocos re DataProcessing: Well, I hope it is not an emulation, but actually the real thing! (that is what I was promised...). The problem is that Tier0 things are always relative to the Tier0 config that is not part of CMSSW, so it requires a lot of care to get things right. While for a simple, approximate test, runTheMatrix does the job, and is a lot easier to use...
> 

and as an added bonus, it calls the same infrastructure underneath. So, you just have to know what pieces you want to run and you can make the same test with both tools.

**Pull request merged**
