### PR TITLE
Fix assert in ExternalGeneratorFilter

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Found by gcc10 in cs8_amd64_gcc10 https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/cs8_amd64_gcc10/CMSSW_12_3_X_2021-12-07-2300/GeneratorInterface/Core

#### PR validation:

None

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by SiewYan** [comment]
Thanks @makortel for catching it!

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
