### PR TITLE
Update DeepCore wf from 11634.17 (TTbar) to 11723.17 (QCD_Pt_1800_2400_14)

### PR DESCRIPTION
**Pull request by silviodonato**
As discussed in https://github.com/cms-sw/cmssw/issues/32543, 
this PR updates the DeepCore wf from 11634.17 (TTbar) to 11723.17 (QCD_Pt_1800_2400_14) given that `/RelValQCD_Pt_1800_2400_14/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM` is ready.

Tested on lxplus with
`runTheMatrix.py -i all --ibeos -l 11723.17`

cc @vberta @mtosi

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by srimanob** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
