### PR TITLE
add multicore processing in relval

### PR DESCRIPTION
**Pull request by hengne**
- add multicore processing in relval
- on top of GT PR #13280

### CODE REVIEW

**Comment by hengne** [comment]
please test with #13280

**Comment by hengne** [comment]
@mmusich this one is on top of #13280

**Comment by mmusich** [comment]
@hegne, I hope either this one of #13280 gets merged soon, so that we can decouple autoCond.py development. We need to update several Global Tags.

**Comment by hengne** [comment]
@mmusich indeed. i also have a couple of relval developments to add.

**Comment by hengne** [comment]
please test with cms-sw/cmsdist#13280

**Comment by hengne** [comment]
please test

**Comment by smuzaffar** [comment]
@hengne , do you want to include #13280 for this PR testing?

**Comment by hengne** [comment]
@smuzaffar , i think in the end i realized we don't need this, because it is make on top of #13280 
but, what is the actual command to test a PR together with another one? i think i will need this info in the future. Thanks!

**Comment by smuzaffar** [comment]
the only way to do this is to make a PR based on other PR just like 13284 which was made based on #13280 :-)

**Comment by hengne** [comment]
@smuzaffar Aha, ;-D

**Comment by fabozzi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
