### PR TITLE
Move to ROOT pre-6.06 (almost final)

### PR DESCRIPTION
**Pull request by davidlt**
This is needed for ROOT 6.04 and 6.06 (this is what we have it `CMSSW_8_0_ROOT64_X` branch). This must go together with cms-sw/cmsdist#2023

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2023

**Comment by davidlt** [comment]
I would advice building non-incremental build with this if you want to test.

**Comment by davidlange6** [comment]
should we just start an IB?

**Comment by davidlt** [comment]
I looked at a diff between CMSSW_8_0_X and CMSSW_8_0_ROOT64_X branches (which is small) and all the pieces seems to be here and it's the same ROOT that's running in DEVEL IBs, which works fine. Thus I would prefer a local test where you build cmssw-tool-conf, create a your custom CMSSW and build that as RPM (a clean build).

**Comment by smuzaffar** [comment]
lets get this in IB

**Comment by smuzaffar** [comment]
merge

**Pull request merged**
