### PR TITLE
Remove CMS custom hacks for Oracle OCCI old C++ ABI compatibility

### PR DESCRIPTION
**Pull request by mrodozov**
Removes custom oracle calls introduces in this commit 
https://github.com/cms-sw/cmssw/pull/22384/commits/03499f00f522994e3bb857938dc0435d7fbea077
and keeps the changes introduced in later commits.

Revert https://github.com/cms-sw/cmssw/pull/22384 commit 03499f00f52

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4645

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4645

**Comment by fabiocos** [comment]
@smuzaffar is the error message related to the use of the DEVEL IB instead of the main one?

**Comment by smuzaffar** [comment]
@fabiocos , please ignore that error.  Error was due to an update in cms-bot and this has been fixed and latest tests has anyway override the previous failure results.

**Comment by smuzaffar** [comment]
@fabiocos , I would like to merge this for DEVEL IB to run all tests.

**Pull request merged**
