### PR TITLE
HLT menu development

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu development
PS drop in PF
Btag monitoring
Based on CMSSW_11_2_X_2020-07-16-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Looks like the failures are from the underlying IB!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
