### PR TITLE
Moved test modules in DataFormat/Math to thread friendly types

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed CMS deprecation warnings.

#### PR validation:

Code compiles without deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
please test
(assuming DAS errors are transient)

**Comment by mandrenguyen** [comment]
+reconstruction
technical, no change to reco

**Comment by rappoccio** [comment]
+1

**Pull request merged**
