### PR TITLE
Add HLT-Scouting collections to `MINIAOD` event content (follow-up of #42863)

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

https://github.com/cms-sw/cmssw/pull/42863 added the HLT-Scouting collections to the `MINIAODSIM` event content (i.e. MINIAOD content of standard MC samples). This PR suggests two improvements on top of https://github.com/cms-sw/cmssw/pull/42863.

 1. Add the HLT-Scouting collections to the `MINIAOD` event content (not only to `MINIAODSIM`), [as per request of the Scouting group](https://indico.cern.ch/event/1345833/contributions/5665746/attachments/2750274/4786758/ScoutingMeeting_2023Nov10.pdf#page=5).

     - Pro: for Primary Datasets (PDs, real data) whose RAW event content includes HLT-Scouting objects, the latter objects will also be included in MINIAOD. Right now, only one such PD exists, named `ScoutingPFMonitor`. It is used for offline studies related to Scouting, and the Scouting group currently uses a workflow with "two-file solution" to access offline objects from MINIAOD and HLT-Scouting objects from AOD. Having both in MINIAOD will simplify this workflow significantly. Note that this change (adding HLT-Scouting to MINIAOD) has no impact on any other PD, to my knowledge, as those PDs do not retain HLT-Scouting objects in RAW in the first place.

     - Con 1: the size of the MINIAOD samples of the `ScoutingPFMonitor` PD will increase. This size increase has not been quantified. It is assumed to be at most 10% based on the checks done in #42863. Since this only applies to a single PD with relatively low rate ([below ~40 Hz during normal pp data-taking in 2023](https://cmsoms.cern.ch/cms/triggers/hlt_trigger_rates?cms_run=370293&cms_ls_from=388&cms_ls_to=388&props.19540_19396.selectedCells=ScoutingPFMonitor:2)), I dare say this cost is rather small. For example, if I check the total size of all the `Run2023` MINIAOD samples on DAS, I get 1.65 PB. If I restrict that to the `ScoutingPFMonitor` PDs, I get 2.8 TB (0.16% of the total).
       ```bash
       rm -f tmp.txt
       for ddd in $(dasgoclient -query "dataset dataset=/*/*Run2023*/*MINIAOD* status=VALID"); do
         dasgoclient -query "file dataset=$ddd | sum(file.size)" >> tmp.txt
       done
       cat tmp.txt | awk '{sum += $2} END {print sum}'
     
       rm -f tmp.txt
       for ddd in $(dasgoclient -query "dataset dataset=/*Scouting*/*Run2023*/*MINIAOD* status=VALID"); do
         dasgoclient -query "file dataset=$ddd | sum(file.size)" >> tmp.txt
       done
       cat tmp.txt | awk '{sum += $2} END {print sum}'
       ```

     - Con 2: the size of MINIAOD samples derived from data tiers such as FEVTDEBUGHLT will also increase (again by a guess-stimated ~10% or less). I do not know this kind of use cases in detail. I see this happens, for example, in wfs such as `141.001` where there is a `reHLT` step on data with `--eventcontent FEVTDEBUGHLT` (followed by a 2nd step with RECO, MINI, NANO, etc). Here too, I would guess this use case is limited, and the overall cost of this increase could be considered small.

 2. Integrate this better in the way HLT currently provides collections to the 'central' event contents in CMSSW. This PR defines a PSet `HLTriggerMINIAOD` in `HLTrigger/Configuration` (`HLTriggerMINIAOD` in this PR includes only the HLT Scouting event content), similarly to the way `HLTriggerAOD` and others are defined. This part of the PR is purely technical, it's just meant to homogenise how extra HLT-related collections are inserted in different data tiers.

`HLTrigger_EventContent_cff.py` was not modified directly, but recreated by running an updated version of `HLTrigger/Configuration/test/getEventContent.py`.

If approved, I would suggest to backport this PR to `CMSSW_13_3_X` to keep `HLTrigger/Configuration` as similar as possible in `13_3_X` (currently used for HLT-menu development) and later cycles (and to cover the unlikely scenario of taking data relevant to Scouting in 2024 with `13_3_X`).

(Since changes to `HLTrigger/Configuration/test` are normally done only by @cms-sw/hlt-l2, I could also close this PR and let this update be done by TSG/STORM in one of the next HLT PRs.)

Attn: @elfontan @kelmorab (TSG/Scouting conveners)

#### PR validation:

Ran a couple of `runTheMatrix.py` wfs for Run-3 data and MC, and checked that the HLT-Scouting collections are present in the MINIAOD(SIM) outputs.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_3_X`

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@missirol 
Hmm, on one side I see the solution adopted here given the precedent. On the other side it looks like HLT is (ab)used to solve offline probems. Since it is straight forward and I do not have a better solution, OK, let's go ahead.
Could you please make the 13_3 backport PR?
Thanks!

**Comment by mmusich** [comment]
+hlt
   * as per https://github.com/cms-sw/cmssw/pull/43327#issuecomment-1818388874 and M.M. deeming uncontroversial.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
