### PR TITLE
[10.2.X] Introduce a special AlCaReco for Strip Small Bias Scans 

### PR DESCRIPTION
**Pull request by mmusich**
backport of #24383 

---
Greetings,
in the Tracker DPG we are trying to find a systematic solution to the chronic lack of RECO data-tier to analyze the output of SiStrip (small) Bias scans.
These scans are not affecting physics  (so they are standard production runs) and therefore normally only standard `AOD` output is available for the high rate (ie. non commissioning) datasets, which is not enough for the sensor aging monitoring purposes.
A viable solution would be to run one of our `ALCARECO` producers saving tracks and Strip clusters , but this solution might be in general disfavored  due to concerns about output dataset size.
Since we are scanning only few (fixed) power groups in a small bias scan and we are interested only in the clusters of tracks that have at least one hit on one of the modules being scanned, and we could select the output tracks to drastically reduce the data throughput. 
This is what has been implemented in the PR. 
A new track selector `CalibrationTrackSelectorFromDetIdList`, allowing to save a collection of track candidates leaving hits through a certain list of Tracker modules is employed in the novel `SiStripCalSmallBiasScan` `ALCARECO` producer.
The new `ALCARECO` producer has been added to several 2018 matrix workflows, including wf 136.85 which is in the short list used in PR tests. 
To allow the `ALCARECO` producer to run I have changed the `AlCaRecoTriggerBits` in the `run2_data_relval` and `run2_data_promptlike`  autoCond keys with temporary candidate GTs. 
@lpernie @tocheng you might want to change them into full-fledged Global Tags.
I report here for completeness the average compressed size in bytes/event of the branches of the new `ALCARECO` compared with `SiStripCalMinBias`.

| Branch name | `SiStripCalMinBias` | `SiStripCalSmallBiasScan` |
| ------------- | ------------- |------------- |  
|recoTrackExtras                  |39791      |1982.09  |     
|TrackingRecHitsOwned             |27896.9    |1505.75  |     
|recoTracks                       |24399.7    |1160.07  |     
|SiStripClusteredmNewDetSetVector |22430.6    |1043.46  |     
|SiPixelClusteredmNewDetSetVector |13553.5    |1001.83  |     
|LumiScalerss_scalersRawToDigi    |1179.33    |951.02	|       
|EventProductProvenance           |1004.8     |786.41	|   
|DcsStatuss                       |349.09     |310.52	|   
|L1AcceptBunchCrossings           |217.85     |196.37	|   
|edmTriggerResults                |192.13     |181.04	|   
|DetIdedmEDCollection             |158.74     |144.52	|   
|edmTriggerResults                |127.18     |118.99	|   
|edmTriggerResults                |71.18      |63.34	|   
|L1GlobalTriggerReadoutRecord     |63.36      |56.98	|   
|EventAuxiliary                   |56.24      |52.17	|   
|EventSelections                  |28.55      |24.4	|   
|BranchListIndexes                |17.88      |15.5     |

### CODE REVIEW

**Comment by tocheng** [comment]
please test

**Comment by prebello** [comment]
please test

**Comment by mmusich** [comment]
Last commit introduces updates Global Tags. As agreed with AlCa/DB, there are some more changes (other than the updated TriggerBits) due to tags that have become available / fixed in the meanwhile and not yet included in other PRs. 
# Summary of changes in Global Tags 
 
## RunII data 
 
   * **RunII Offline relval processing** : [102X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_relval_v6) as [102X_dataRun2_relval_v5](https://cms-conddb.cern.ch/
cmsDbBrowser/list/Prod/gts/102X_dataRun2_relval_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_relval_v6/102X_dataRun2_relval_v5): 
      * Updated `AlCaRecoTriggerBits` to add `SiStripCalSmallBiasScan`
      * New tag for CTTPS XML geometry removing bugged payload

   * **RunII Prompt processing** : [102X_dataRun2_PromptLike_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_PromptLike_v8) as [102X_dataRun2_PromptLike_v7](https://cms-conddb.cern
.ch/cmsDbBrowser/list/Prod/gts/102X_dataRun2_PromptLike_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_PromptLike_v8/102X_dataRun2_PromptLike_v7): 
      * Updated `AlCaRecoTriggerBits` to add `SiStripCalSmallBiasScan`
      * new pixel quality tag populated by PCL
      * 2D Pixel templates (not yet used in any workflow, but available in the Prompt GT)

**Comment by lpernie** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by mmusich** [comment]
@prebello, @zhenhu, @pgunnell,
any objection in signing this PR as its 10.3.X counterpart is now already in CMSSW_10_3_0_pre3 (and CMSSW_10_3_0_pre4)?
Thanks

**Comment by prebello** [comment]
+1

@mmusich absolutely as tests were approved after new GTs

**Comment by fabiocos** [comment]
+operations

the backport is consistent with the master version

**Comment by fabiocos** [comment]
+1

validated by M. Musich on old data, not active by default at Tier0

**Comment by mmusich** [comment]
I also checked that this works on recent data taking advantage of ConfigDP tools:

```bash
cmsrel CMSSW_10_2_0_pre4
cd CMSSW_10_2_4_patch1/src/
cmsenv
git cms-addpkg Configuration/DataProcessing
git cms-merge-topic 24437
scramv1 b -j 8
cmsenv
cd Configuration/DataProcessing/test/
python RunPromptReco.py --scenario=ppEra_Run2_2018 --reco --global-tag 102X_dataRun2_Prompt_v5 --lfn=/store/data/Run2018D/EGamma/RAW/v1/000/322/625/00000/F683DC0C-ADB4-E811-84A1-FA163E448F1D.root --alcarecos=SiStripCalSmallBiasScan
```

unpickle the config via [0]:

change the trigger bit selection in GT:
by adding the lines:
```python
process.GlobalTag.toGet = cms.VPSet(
cms.PSet(record = cms.string("AlCaRecoTriggerBitsRcd"),
         tag = cms.string("test"),
         connect = cms.string('sqlite_file:/afs/cern.ch/user/m/musich/public/forStripDBcontacts/test.db')
         )
)
```
in the configuration file and then run with:
```bash
cmsRun myPset.py
```
I run over 100 events with no problem.


[0]
```python
import pickle
pickleHandle = open('RunPromptRecoCfg.pkl','rb')
process = pickle.load(pickleHandle)
f = open('myPSet.py', 'w')
f.write(process.dumpPython())
f.close()
```

**Pull request merged**
