### PR TITLE
Add DMQ FakeBeamMonitor plugin and clients - backport to 11_1_X

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:

This PR is the backport of #30690 to CMSSW_11_1_X

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi @francescobrivio 
We're testing this PR in the DQM playback system atm and it looks fine. Would you like us to run the newly introduced client?

**Comment by francescobrivio** [comment]
> Hi @francescobrivio
> We're testing this PR in the DQM playback system atm and it looks fine. Would you like us to run the newly introduced client?

Hi @andrius-k 
I think the idea was to test them during this MWGR. 
Simone @gennai is coordinating this test and I think he wanted to try this tomorrow or Friday. 
So maybe he can comment better.

**Comment by gennai** [comment]
So this is a fake client which produces a random beamspot value to test the population of the DB (this will be the new workflow for Run3). In normal conditions we do not need it but as we want to make a test we cannot use the standard client as with cosmic data will always give 0,0,0 as BS position. So we would like to use this fake module ONLY during the test we would like to perform tomorrow or Friday depending on Run Coordination

**Comment by andrius-k** [comment]
Ok, I understand. Just keep in mind that if you want to verify there are no configuration or any other unexpected errors we can run this client in the playback system for a few minutes.

**Comment by andrius-k** [comment]
Hi,@gennai, I tried running the new client in the DQM playback system and it crashes with the following error in the configuration:
```
> /cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_0715_CMSSW_11_1_0_patch2_30678_30696/src/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py(388)<module>()
-> if (not process.runType.getRunType() == process.runType.hi_run):
(Pdb) 
----- Begin Fatal Exception 15-Jul-2020 13:13:21 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_0715_CMSSW_11_1_0_patch2_30678_30696/src/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
Exception Message:
 unknown python problem occurred.
BdbQuit: 

At:
  /opt/offline/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/lib/python2.7/bdb.py(68): dispatch_line
  /opt/offline/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/lib/python2.7/bdb.py(49): trace_dispatch
  /cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_0715_CMSSW_11_1_0_patch2_30678_30696/src/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py(388): <module>

----- End Fatal Exception -------------------------------------------------
```

Could you please confirm that this crash won't happen during the upcoming MWGR?

**Comment by gennai** [comment]
@andrius-k it depends the reason of the crash :-) Did you set noDB=True while running? Other reason could be a missing last_lumi.txt file. @francescobrivio can you try to reproduce the crash?

**Comment by francescobrivio** [comment]
I've not seen this crash before, but I can try to reproduce it. @andrius-k what was the command that you used to launch the client?

**Comment by andrius-k** [comment]
@francescobrivio the command that to launch the client was this (from the log):
`-- starting process: ['cmsRun', '/cmsnfsdqmdata/dqmdata/dqm_cmssw/playback_0715_CMSSW_11_1_0_patch2_30678_30696/src/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py', 'runInputDir=/fff/BU0/ramdisk', 'runNumber=500462', 'runkey=cosmic_run'] --`

Production system launches DQM Online clients in the same way.

@gennai Keep in mind that our playback and production systems are very similar, so a crash in playback is a strong suggestion of a crash in prod.

**Comment by gennai** [comment]
@andrius-k point taken, consider that to make the test we would like we will need some real time interaction as It may require to copy a db.key file locally where the jobs is running to access the database and to make sure the url from where the LS number is taken must be working. We will need to coordinate a bit and maybe set up a zoom meeting. The test could just last 10-20 mins if everything works

**Comment by andrius-k** [comment]
@gennai cool, reach out to DQM DOC (me) whenever you're ready to make a test and we can set up a meeting!

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@francescobrivio @gennai there were changes to this PR made by @andrius-k yesterday in the test done at the MWGR, as you suggested. We should include them in this PR, right? If we are expecting to make similar test in the future or actually use the code in online you should push these changes to the PR. Andrius can provide the diff if needed. Thanks

**Comment by jfernan2** [comment]
+1
Tested at online DQM

**Comment by jfernan2** [comment]
-1
Sorry, approved by mistake: some changes are pending to get in syncro with Online tests

**Comment by silviodonato** [comment]
https://github.com/cms-sw/cmssw/pull/30690 has been merged
@jfernan2 are there any pending changes?

**Comment by jfernan2** [comment]
@silviodonato   yes, we need that @francescobrivio  changes this parameter to work with noDB = True by default:

lastLumiFile = cms.untracked.string('last_lumi.txt'),

This needs to be changed too in Master (despite the merged PR), I had understood from @francescobrivio that the url set in the PR was needed, but the actual behaviour in a current test in the playback DQM@P5 shows that a default file should be the right configuration in order to not connect to the DB and crash since DAQ is not giving a run number

Sorry for the late notice

**Comment by francescobrivio** [comment]
> @silviodonato yes, we need that @francescobrivio changes this parameter to work with noDB = True by default:
> 
> lastLumiFile = cms.untracked.string('last_lumi.txt'),
> 
> This needs to be changed too in Master (despite the merged PR), I had understood from @francescobrivio that the url set in the PR was needed, but the actual behaviour in a current test in the playback DQM@P5 shows that a default file should be the right configuration in order to not connect to the DB and crash since DAQ is not giving a run number
> 
> Sorry for the late notice

Sorry again for the delay, this should be now fixed in 47b48bd.
I will also open a new PR in Master as soon as I can to fix the same thing.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
hold
waiting for the fix in 11_2_X

**Comment by jfernan2** [comment]
+1

**Comment by francescobrivio** [comment]
> hold
> waiting for the fix in 11_2_X

Hi @silviodonato, 
the fix in 11_2_X has been merged (#30943) and DQM has approved.
Is there anything else to do to unhold and merge this PR?

**Comment by silviodonato** [comment]
unhold
@francescobrivio thanks for the reminder

**Comment by silviodonato** [comment]
+1

**Pull request merged**
