### PR TITLE
[14_1_X] Use dedicated GT in pp ref 2024 relval workflow

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #46003

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 149.1

**Comment by perrotta** [comment]
+alca

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
