### PR TITLE
Adding 2023GReco to be tests in IB

### PR DESCRIPTION
**Pull request by boudoul**
I also  separated 2017 and 2023 introducing the relval_2023.py file (instead of having everything in relval_2017...) 

The WFs listed in  relval_2023.py : 
[10821.0,10824.0,10825.0,10826.0] #2023sim scenario
[10621.0,10624.0,10625.0,10626.0] #2023with tilted tracker
[11221.0,11224.0,11225.0,11226.0]  #2023Greco with Flat Tracker

What would be great is to have one of the 106xx wf  and one of the 112xx (=2023 with Flat) from the WFs listed above  tested  in PR tests (to avoid to discover a broken IB afterwards..) 

Note that the WFs from the list above can be run without --what upgrade option

@slava77 @ebrondol

### CODE REVIEW

**Comment by boudoul** [comment]
adding @kpedro88 for information

**Comment by kpedro88** [comment]
@boudoul - I agree, I would strongly suggest to put some Phase2 WFs in the PR tests...

**Comment by slava77** [comment]
we need to have these workflows running first before adding them to jenkins.
Unfortunately the time gap where there were available and still running has passed.
Hopefully in one of the next IBs

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by hengne** [comment]
+1

this solution looks good to me. and i also strongly agree to put some phase2 workflows in PR tests, otherwise the PR test means nothing to those phase2 developments (does not only mean the relval developments, but more about those developments relval workflows are using, sim/reco/trigger/dqm etc.), and they are essentially not tested at PR level before getting merged to the release.

**Comment by davidlange6** [comment]
@boudoul @kpedro88 - dumb question - do you see why runTheMatrix.py -i all -l all is looking for gen-sim for the tilted workflows? Is the geometry stable enough to want to reuse the gen-sim in IB tests?

**Comment by kpedro88** [comment]
@davidlange6 - @boudoul added these lines to relval_steps.py in #14610:
```
defaultDataSets['2023GReco']='CMSSW_8_1_0_pre4-80X_mcRun2_asymptotic_v13_2023LReco-v'
defaultDataSets['2023tilted']='CMSSW_8_1_0_pre4-80X_mcRun2_asymptotic_v13_2023tilted-v'
```

I guess the intention is to reuse minbias for PU workflows, but I'm not sure if we expect the geometry to be that stable in general. (In particular, I'm planning to make some changes this week...)

**Comment by boudoul** [comment]
Hi @davidlange6 : It is indeed premature to recycle gensim : the geometry developments will continue ...
The MinBias should be updated each time we are generating a new one ( I already warned pdmV @srimanob, @hengne, @fabozzi , to keep this uptodate, at least they should explain to Stefan how to do it) 
Btw Is is possible to disable the -i all option from the 2023 Wfs in IB tests?  or should I comment the default dataset lines in relval steps ?

**Comment by kpedro88** [comment]
@boudoul @davidlange6 it would be good to converge soon...

**Comment by davidlange6** [comment]
+1

**Pull request merged**
