### PR TITLE
Run2-hcx195 Remove direct CLHEP reference in the algorithm for HCAL endcap

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove direct reference to CLHEP in all the algorithms - the last ones related to HCAL endocarps

#### PR validation:

Standard runTheMatrix.py works fine

#### if this PR is a backport please specify the original PR:

Meant for master and no back porting is needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
The errors seem not due to this PR. This PR affects geometry and failures are in Trigger jobs

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
