### PR TITLE
Remove duplicate CLCTs and LCTs from trigger path in L1T CSC DQM

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Remove duplicate CLCTs and LCTs from trigger path in L1T CSC DQM to better compare with DAQ path. Duplicates are (C)LCTs that have the same properties as (C)LCTs found before by the emulator, except for the BX, which is off by +1. These are typically not in the CSC DAQ because the L1A will only pick up the first one, not the second one. 

#### PR validation:

Tested on 10k events from B904 cosmic data run taken today. This run had a fixed CLCT slope mapping in the CCLUT algorithm - seems to be working now. In all, good agreement can be seen for CLCTs. 

There are still discrepancies for CLCTs, which can be attributed to (1) too many CLCTs in emulation, (2) too few CLCTs in emulation. (1) cannot be easily fixed I think since we don't know where the L1A is in the emulation. (2) might be worthwhile to look at because it points to real flaws in the CLCT emulation algorithm.

Validation plots added also below:

[CSC_dataVsEmul_B904_Cosmic_Run_210609_142357.pdf](https://github.com/cms-sw/cmssw/files/6628263/CSC_dataVsEmul_B904_Cosmic_Run_210609_142357.pdf)

I should note that the comparison was done for a pretrigger zone with size 5. CSC trigger devs are still debating whether or not this is something we should pursue. In the code now we set the pretrigger zone to 224, meaning that we accept any CLCT 2BX after a pretrigger, as opposed to a trigger that is spatially matched to the pretrigger.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
Few validation plots for CLCTs (all validation plots can be found in the PDF attached to the description of this PR)

Screen Shot 2021-06-09 at 11 18 28 PM
Screen Shot 2021-06-09 at 11 18 33 PM
Screen Shot 2021-06-09 at 11 18 38 PM
Screen Shot 2021-06-09 at 11 18 43 PM
Screen Shot 2021-06-09 at 11 18 48 PM
Screen Shot 2021-06-09 at 11 18 53 PM
Screen Shot 2021-06-09 at 11 18 58 PM
Screen Shot 2021-06-09 at 11 19 04 PM
Screen Shot 2021-06-09 at 11 19 10 PM
Screen Shot 2021-06-09 at 11 19 16 PM
Screen Shot 2021-06-09 at 11 19 22 PM

**Comment by dildick** [comment]
A before and after picture

Before (with duplicates)

Screen Shot 2021-06-09 at 3 46 22 PM
Screen Shot 2021-06-09 at 3 50 14 PM

After (without duplicates)

Screen Shot 2021-06-09 at 3 46 27 PM
Screen Shot 2021-06-09 at 3 50 17 PM

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick I see no changes in Offline, are your changes intended for Online DQM perhaps?

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
It's possible that the matrix tests would not show any differences. The effect is about 1 in 1000.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
