### PR TITLE
[125X] Bugfix to the destructor of two TkDQM scripts

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39573

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39573

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix,trk

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39573

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
