### PR TITLE
Phase2-gex160Z Remove overlaps in the Phase2 scenarios which used to be caused by an error in zdc.xml

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove overlaps in the Phase2 scenarios which used to be caused by an error in zdc.xml

#### PR validation:

Tested using scripts in SimG4Core/PrintGeomInfo/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@AdrianoDee @srimanob if you sign this in the next 5' we can still include this fix in 13_1_X

**Comment by AdrianoDee** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
