### PR TITLE
[PPS] Added gtStage2DigisAlCaRecoProducer to ALCARECOPRODUCER [14_0_X backport]

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This is backport of #44044 

The PR adds the hltGtStage2Digis production step in the PPS ALCARECO sequence and preserves this product in the output. This change follows the discussion in [CMSHLT-2989](https://its.cern.ch/jira/browse/CMSHLT-2989), in which the the hltFEDSelectorL1 products are added to the HLT output in order to have access to the prescale values in the final dataset.

### CODE REVIEW

**Comment by mmusich** [comment]
type ctpps

**Comment by mmusich** [comment]
backport of #44044

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by vavati** [comment]
Is there anything else PPS needs to do to get this PR merged ?

**Comment by perrotta** [comment]
> Is there anything else PPS needs to do to get this PR merged ?

The master PR should be merged first, hopefully today (as it s fully signed)

**Comment by grzanka** [comment]
> > Is there anything else PPS needs to do to get this PR merged ?
> 
> The master PR should be merged first, hopefully today (as it s fully signed)

Master PR is merged https://github.com/cms-sw/cmssw/pull/44044 , I hope this PR can proceed with merging as well.
It's important for us to include it for data taking.

**Comment by mmusich** [comment]
urgent
   * to be included in the release to be used at Tier0 for first collisions (see also https://its.cern.ch/jira/browse/CMSHLT-3093)

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/44044
- Succesfully merged in master since CMSSW_14_1_X_2024-03-04-2300

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 please sign

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
