### PR TITLE
`SiPixelLorentzAnglePCLHarvester`: protect the computation of the LA error in case of missing covariance matrix

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, resolves the issue reported at https://github.com/cms-sw/cmssw/pull/38996#issuecomment-1216704561

#### PR validation:

Run successfully with this branch:
```console 
runTheMatrix.py -l 1001.2 -j 8 -t 4
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will be included in the backport of https://github.com/cms-sw/cmssw/pull/38996 (https://github.com/cms-sw/cmssw/pull/39075)

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by mmusich** [comment]
test parameters:
    * workflows = 1001.2

**Comment by tvami** [comment]
urgent
 * the backport should go into the next 12_4_X

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
