### PR TITLE
L1T offine DQM changes for pp reference run - 94x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #21188 

To make the L1T offline DQM work for the pp reference run the trigger paths used must be adapted for the pp reference run HLT menu.

This PR includes commit https://github.com/cms-sw/cmssw/pull/21069/commits/66db527b397c0d1d6c3627a429c530e23124e103 from PR #21069 to get the era "Run2_2017_ppRef" and https://github.com/cms-sw/cmssw/pull/21122/commits/243c2e492843bc624622e65e7d0ce588f94fcbdf from PR #21122 since that commit is not yet in #21069.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
Superseded by #21236

**Pull request closed without merging**
