### PR TITLE
fix PV validation @HLT

### PR DESCRIPTION
**Pull request by mtosi**
as reported by @davidlange6 in https://hypernews.cern.ch/HyperNews/CMS/get/dqmDevel/2395.html (thanks !!!!)
this PR fixes the typo in the PV validation @HLT

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
this is the backport of the commit 
b5b1c1c98b652354ed7a2696ae0d5a13623a16f8
included in PR https://github.com/cms-sw/cmssw/pull/20767

**Comment by dmitrijus** [comment]
+1

thanks :)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
