### PR TITLE
DQM: Allow per-lumi MEs in DQMOneEDAnalyzer

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

After the discussion started by @Dr15Jones in #29314 , I remembered that we still had the option to do the lumi-switching in the `DQMStore` on a per-event basis. This allows modules like `METAnalyzer` to book per-lumi histograms but remain `DQMOneEDAnalyzer` and yet not block concurrent lumis.

The cost is higher overhead. The `enterLumi/leaveLumi` calls should be fast in the common case (take a lock, do a map lookup, do nothing), but with many lumi MEs (for example when per-lumi saving by default like in the UL ReReco) all the pointer bending could cause some overhead. However, even that might still be negligible, or could be optimized a bit more if it is a problem.

#### PR validation:

I tested a workflow with `METAnalyzer` and it seems to come out well. The PR tests should catch eventual differences.

I also updated the unit tests to excercise this feature and it seems fine. However, I don't observe any concurrent lumis in the unit tests, even though they are enabled and there should not be any blocking modules. It would be nice to see some test case where events actually alternate between lumis.

### CODE REVIEW

**Comment by schneiml** [comment]
please test

There should not be any differences, and that should actually sort of validate the change.

**Comment by schneiml** [comment]
please test

Maybe now.

**Comment by schneiml** [comment]
Unless anybody objects (@Dr15Jones , @makortel ?) I think this is a viable solution. Paying special attention to the `DQMOneEDAnalyzer`s in RelVals is of course mandated, esp. if concurrent lumis are actually used (I don't think the DQM unit tests that enable concurrent lumis actually managed to produce some events where the one modules went back-and forth between lumis).

Otherwise, I think we can go ahead here.

**Comment by schneiml** [comment]
please test

Nothing changes, but the pervious comparison is gone and things may have changed in master.

**Comment by schneiml** [comment]
The changes in 1330 are unexpected. They were also present in the previous tests and are not in #29438 (which is clean otherwise). So, this needs to be investigated.

**Comment by schneiml** [comment]
It turns out the changes here are a well known problem.

So, this looks all fine to me.

**Comment by schneiml** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
