### PR TITLE
SiStrip Payload Inspector: refinements to `SiStripCondObjectRepresent`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to introduce several improvements and clean-ups into the SiStrip payload inspector classes and builds on top of https://github.com/cms-sw/cmssw/pull/37265 and https://github.com/cms-sw/cmssw/pull/37333:
   * d29103bd0410d15609b8a03629e6379aa5478d55 adds a `THStack` plot for the gains broken down by subdetector.
   * b07b4015e0a7f857a17ccbb3af0327ad89804d6f and 86d19b1c19f9bff9bf6a64d9a69abb8ae3908fff streamline the code in order to adhere to more modern pattern employed in other classes in the same package.
   * 4be848be2675a6e0ad0be29cde80761172812b70 rationalizes the usage of `TrackerMaps` for the `SiStripDetVOff` object by using class templates
   * 66339a9158c854deec2249017506f4cbb2f35407 and ab32dc477066cc72735735834f85c64264974114 perform the infrastructural changes to percolate the tag names into the `SiStripCondObjectRepresent` classes.
   * finally I profit of this PR to propose d21c579baad42bc40bc4ef55ccc41fcfbb7e6d91 as well, which instead is related to the Tracker Alignment inspectors (graphical improvements of the legends)

#### PR validation:

The touched classes were tested privately with e.g. the following commands:

```console
getPayloadData.py --plugin pluginSiStripNoises_PayloadInspector --plot plot_SiStripNoiseCompareByPartition --tag SiStripNoise_v2_prompt --tagtwo SiStripNoise_v2_prompt --time_type Run --iovs '{"start_iov": "348878", "end_iov": "348878"}' --iovstwo '{"start_iov": "349927", "end_iov": "349927"}' --db Prod --test ;
```
b30334e2-6ca8-462e-b9e7-8926c16865e2

```console
etPayloadData.py --plugin pluginSiStripNoises_PayloadInspector --plot plot_SiStripNoiseDiffByPartition --tag SiStripNoise_v2_prompt --tagtwo SiStripNoise_v2_prompt --time_type Run --iovs '{"start_iov": "348878", "end_iov": "348878"}' --iovstwo '{"start_iov": "349927", "end_iov": "349927"}' --db Prod --test ;
```
cf6480fe-399e-4778-950a-6586cfbd6af1

```console
getPayloadData.py --plugin pluginSiStripDetVOff_PayloadInspector --plot plot_SiStripDetVOff_IsModuleVOff_TrackerMap --tag SiStripDetVOff_v6_prompt --time_type Time --iovs '{"start_iov": "7083471724997514240", "end_iov": "7083471724997514240"}' --db Prod --test ;
```
52b055e5-0b8f-4651-a267-46525a441fcb

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
> -1
> 
> Failed Tests: Build ClangBuild

So, I removed the clang warnings reported [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9e5910/23742/clang-new-warnings.log) in the last push, but I am not able to reproduce the compilation failure in my checkout using: 

```console
scram b vclean && BUILD_LOG=yes USER_CXXFLAGS=-DUSE_CMS_DEPRECATED scram b -k -j 16
```

so I am not sure if triggering the test would result again in a failure.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
@cmsbuild, please abort.
   * I have understood the issue.

**Comment by tvami** [comment]
Hi @smuzaffar  do you maybe have an idea why this is missing: 

> /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-04-07-1100/src/CondCore/Utilities/interface/PayloadInspector.h:18:10: fatal error: pybind11/pybind11.h: No such file or directory

**Comment by mmusich** [comment]
> Hi @smuzaffar do you maybe have an idea why this is missing:

I've understood what's wrong. I'll push a commit shortly. This will just make tests pass, perhaps I'll figure some re-factoring.

**Comment by smuzaffar** [comment]
looks like missing dependency on `CondCore/Utilities` somewhere :-)

**Comment by mmusich** [comment]
@smuzaffar I already did it...

**Comment by smuzaffar** [comment]
humm, but you have updated CondTools/SiStrip/plugins/BuildFile.xml . I think it is better to update CondCore/SiStripPlugins/BuildFile.xml  as the `CondCore/Utilities` deps is in CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@smuzaffar 

> I think it is better to update CondCore/SiStripPlugins/BuildFile.xml as the CondCore/Utilities deps is in CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h

There is no such file in release (see: https://github.com/cms-sw/cmssw/tree/master/CondCore/SiStripPlugins), shall I add it?

**Comment by smuzaffar** [comment]
ah Ok, sorry I did not check that @mmusich . In that case what is the purpose of `CondCore/SiStripPlugins/interface` ? My worry was that as there are header files in `CondCore/SiStripPlugins/interface`  which can be included by other packages (and then those packages also have to add the missing CondCore/Utilities deps in their BuildFiles) . Looks like `CondTools/SiStrip` is the only package using  one of the headers file of `CondCore/SiStripPlugins` ... why not merge these 2 packages?  otheriwse
- CondCore/SiStripPlugins/interface/SiStripCondObjectRepresent.h is only used by CondCore/SiStripPlugins/plugins so move it to CondCore/SiStripPlugins/plugins  directory so that no one else can include it
- CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h is used by  `CondTools/SiStrip` so we need a CondCore/SiStripPlugins/BuildFile.xml in which please add deps on all packages included in CondCore/SiStripPlugins/interface/SiStripPayloadInspectorHelper.h and update `CondTools/SiStrip/plugins/BuildFile.xml` to dep on  CondCore/SiStripPlugins

I personally would prefer to merge the packages

**Comment by mmusich** [comment]
> I personally would prefer to merge the packages

as they are supposed to carry out separate tasks, I would rather not merge them, I went for the recipe you recommended at https://github.com/cms-sw/cmssw/pull/37492#issuecomment-1092494582

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+db
 * tests pass, diffs seen are known

**Comment by perrotta** [comment]
+1

**Pull request merged**
