### PR TITLE
fixed problem by which the boost_serialization tag would never be closed

### PR DESCRIPTION
**Pull request by argiro**
This fixes issue #17664. @ggovi  @franzoni please merge

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by argiro** [comment]
Hard to believe the failures are caused by this PR

**Comment by franzoni** [comment]
>  Hard to believe the failures are caused by this PR

correct.
Can you please rebase the branch of this PR to the current master ?  One needs to include this PR https://github.com/cms-sw/cmssw/pull/19667 , a fix which became necessary after https://github.com/cms-sw/cmssw/pull/19469 was merged.

**Comment by argiro** [comment]
I think it was rebased automatically.

**Comment by franzoni** [comment]
the issue stems from the bot using CMSSW_9_3_X_2017-07-09-2300.
Ri-triggering the tests will move the IB test are based upon, which will solve the issue.

**Comment by franzoni** [comment]
please test

**Comment by ggovi** [comment]
@argiro 
good catch stefano, thanks a lot for the fix! plus it's a easy fix, did not expect that!

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
