### PR TITLE
L1T offline DQM configuration to run also for cosmics runs

### PR DESCRIPTION
**Pull request by thomreis**
Run the stage2 L1T offline DQM also for cosmics data.
The legacy behaviour should remain unchanged and no L1 DQM is produced for legacy cosmics data.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

An increase in histogram memory is expected since before no L1T DQM histograms were produced for cosmic runs.

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be reviewed/merged please?

**Comment by fabiocos** [comment]
@thomreis This PR is not mergeable (due to the merge of @21754 I guess), please rebase it

**Comment by thomreis** [comment]
+1

Conflict has been resolved.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign this again.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@thomreis is the increase in memory restricted to cosmics workflows, as I understand from the sequences?

**Comment by thomreis** [comment]
@fabiocos yes, it should be restricted to cosmics workflows. For normal pp running the configuration was already running before and nothing has changed there.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
