### PR TITLE
Print correct timestamp in HP beamspot txt file

### PR DESCRIPTION
**Pull request by sarafiorendi**
This PR is a further refinement of the HP beamspot workflow (integrated with #22299).
It allows to print in the output .txt file the correct beginning-time of the lumi-section for which the BS is measured.

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
I thing the tests got stuck

**Comment by lpernie** [comment]
abort

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
