### PR TITLE
add the identifier of the algorithm where the track was first found

### PR DESCRIPTION
**Pull request by VinInn**
This Pull Request adds to TrackBase the identifier of the algorithm where a track was first found.
This information is required to properly compute tracking efficiency using tag&probe methods
(cfr comments by Paris at the physics plenary on 7/5/2015).

No regression expected, no regression observed.

backport to 7_4_X is requested.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Hi Vincenzo, 

"backport to 7_4_X is requested." usually means you (or a tracking POG contact) makes a PR for 74X.
Then it gets considered.
This change has to be integrated before the DR campaign starts, otherwise it's a no-go for 74X.

@davidlange6 please comment if this was noted already as a priority item to make a 742 release.

**Comment by VinInn** [comment]
@slava77 .
Was to inform reco and orp.
I will make a new PR for 7_4_X as soon as this one is approved (do not want to modify to different PR's)
Th only way I know to make a PR is to create a patch and apply it by hand: never manage any git-magic

**Comment by davidlange6** [comment]
i’m not aware of discussion of this topic. (It looks like I missed on this week). Its for 75x for now, which it seems we will be using soon enough.

**Comment by VinInn** [comment]
this is needed for the first data.
Either this, or skimmed RAW (which was my original request)

**Comment by VinInn** [comment]
The third option is to "persistify" earlyGeneralTracks
does not provide the full information, will need an additional analysis,
should allow to compute the efficiency though

**Comment by davidlange6** [comment]
as a pure addition to a data format, its something we can consider once checked in 750pre5. a good topic for the next reco meeting

**Comment by VinInn** [comment]
cherry picking 9f16947 may be enough in 74X to flag muon-seeded that "overwrites" previous iterations...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
I will prepare a presentation on Thursday about "Evaluating tracking efficiency using muon tag&probe"

**Comment by slava77** [comment]
Hi Vincenzo,

Does it make sense to keep only two algos that the track was reconstructed with?
I was thinking we should introduce an algo map instead, setting flags for all cases where the track was reconstructed.

**Comment by VinInn** [comment]
Hi @slava77 , we are just discussing what the best strategy is.
At the moment the algo is the "smallest", and I am not sure we really care how many times a " track" was actually found (if a track is found say in iter 0,3,5,9 oriAlgo will be 0 independently of who wins and how).
The real problem is that we run several mergers, any external object need to be propagated (see MVA and quality for instance), so adding maps or similar stuff makes the code and config extremely complex.
There is also the subtle issue that the tracks can be actually different.
We are seriously thinking (at least for the post earlyGeneralTrack algos) to save somehow all tracks that have been "discarded" during the merging step (either as a different collection or flagged with some quality flag)

**Comment by slava77** [comment]
Hi Vincenzo, 
to be more explicit what I had in mind is to save a long int algosPickAName_; with bits matching the corresponding algo set to 1.

**Comment by VinInn** [comment]
that's an interesting option
will look into it

**Comment by VinInn** [comment]
I have added an algomask that summarize all algos a track has been found as suggested by @slava77

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
rebase issue?

**Comment by VinInn** [comment]
will close and reopen later

**Pull request closed without merging**
