### PR TITLE
use `EvFFEDExcluder` instead of `EvFFEDSelector` for `rawPrimeDataRepacker`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Taking advantage of PR https://github.com/cms-sw/cmssw/pull/39993 we can actually use `EvFFEDExcluder` instead of `EvFFEDSelector` for `rawPrimeDataRepacker`, allowing for a more compact set of FEDs to exclude in the 2018 RAW' worklflow defined in PR https://github.com/cms-sw/cmssw/pull/39863, following up on https://github.com/cms-sw/cmssw/pull/39863#discussion_r1006485795
 
#### PR validation:

`runTheMatrix.py -l 140.58 -t 4 -j 8 --ibeos` runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Possibly to 12_5_X.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows=159,159.02,159.03,140.56,140.58,140.6

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
> -1
> Failed Tests: RelVals

failure are clearly unrelated. I will wait for a new IB to appear to re-trigger the tests.

**Comment by mmusich** [comment]
@cmsbuild, please test
   * let's see if with the new IB the failure goes away.

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 ping

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
I can hardly believe that the differences observed in the DQM of the 140.6 HI workflow are due to this PR, but before merging let me check with @mmusich if there is any possible connection that I am missing...

**Comment by missirol** [comment]
Sorry to interject, but this may be relevant to the HLT HIon menu that's going online today/tomorrow (the HLT menu uses the old, pre-PR, list).

I think this PR leads to a larger list of FEDs, and the DQM plots reflect this. For example, FEDs 1124-1129 (HO), 1140-1142 (HB) and 1468 (GEM) [[see list on OMS]](https://cmsoms.cern.ch/cms/runs/report/fullscreen/4637?cms_run=360761&cms_run_sequence=GLOBAL-RUN) are not present in the original list (pre-PR), and one can see more entries post-PR in the corresponding DQM plots ([example-1](https://tinyurl.com/29wfpm3s), [example-2](https://tinyurl.com/26a6b6jc)).

**Comment by perrotta** [comment]
> Sorry to interject, but this may be relevant to the HLT HIon menu that's going online today/tomorrow (the HLT menu uses the old, pre-PR, list).
> 
> I think this PR leads to a larger list of FEDs, and the DQM plots reflect this. For example, FEDs 1124-1129 (HO), 1140-1142 (HB) and 1468 (GEM) [[see list on OMS]](https://cmsoms.cern.ch/cms/runs/report/fullscreen/4637?cms_run=360761&cms_run_sequence=GLOBAL-RUN) are not present in the original list (pre-PR), and one can see more entries post-PR in the corresponding DQM plots ([example-1](https://tinyurl.com/29wfpm3s), [example-2](https://tinyurl.com/26a6b6jc)).

Thank you @missirol , this makes sense

**Comment by perrotta** [comment]
> Sorry to interject, but this may be relevant to the HLT HIon menu that's going online today/tomorrow (the HLT menu uses the old, pre-PR, list).
> 
> I think this PR leads to a larger list of FEDs, and the DQM plots reflect this. For example, FEDs 1124-1129 (HO), 1140-1142 (HB) and 1468 (GEM) [[see list on OMS]](https://cmsoms.cern.ch/cms/runs/report/fullscreen/4637?cms_run=360761&cms_run_sequence=GLOBAL-RUN) are not present in the original list (pre-PR), and one can see more entries post-PR in the corresponding DQM plots ([example-1](https://tinyurl.com/29wfpm3s), [example-2](https://tinyurl.com/26a6b6jc)).

Thank you @missirol , this makes sense

**Comment by perrotta** [comment]
+1
- Merging in master, giving the [comment](https://github.com/cms-sw/cmssw/pull/40005#issuecomment-1318240996) on the larger number of FEDs selected wrt what is in the baseline

**Comment by perrotta** [comment]
> Sorry to interject, but this may be relevant to the HLT HIon menu that's going online today/tomorrow (the HLT menu uses the old, pre-PR, list).
> 
> I think this PR leads to a larger list of FEDs, and the DQM plots reflect this. For example, FEDs 1124-1129 (HO), 1140-1142 (HB) and 1468 (GEM) [[see list on OMS]](https://cmsoms.cern.ch/cms/runs/report/fullscreen/4637?cms_run=360761&cms_run_sequence=GLOBAL-RUN) are not present in the original list (pre-PR), and one can see more entries post-PR in the corresponding DQM plots ([example-1](https://tinyurl.com/29wfpm3s), [example-2](https://tinyurl.com/26a6b6jc)).
> 
> Edit: I notified HLT HIon experts.

Maybe I should have asked before merging... But were these extra FEDs intended to be included, or was it a mistake instead?

**Comment by missirol** [comment]
I edited my comment above adding that I notified HLT HIon experts; let's also tag @mandrenguyen. My guess is that the post-PR list is correct, but I do not know and this needs to be clarified by an expert (and if so, this also needs to be fixed in the online HLT menu asap..).

**Comment by mandrenguyen** [comment]
I pass the baton to @abaty and @icali who know better than I which FEDs should be included/excluded.

**Comment by mandrenguyen** [comment]
thanks @mmusich for pointing this out.  This offline code is simply used for testing conversion from raw to rawprime offline.  The more urgent thing is to fix the HLT menu.

**Comment by mmusich** [comment]
@perrotta 

> there is any possible connection that I am missing...

That's correct,  this PR is including more FEDs to be repacked. As we pointed out in #39863, this option is safer (but unpracticable at HLT AFAIU)

**Pull request merged**
