### PR TITLE
Restructure XML Data Directories by Year and Version Step 3

### PR DESCRIPTION
**Pull request by ianna**
* Files renamed without changes:
 - Geometry/CMSCommonData/data/PostLS2/beampipe.xml → Geometry/CMSCommonData/data/beampipe/2023/v1/beampipe.xml
 - Geometry/CMSCommonData/data/PhaseII/caloBase.xml → Geometry/CMSCommonData/data/caloBase/2023/v1/caloBase.xml
 - Geometry/CMSCommonData/data/PostLS2/cmsBeam.xml → Geometry/CMSCommonData/data/cmsBeam/2023/v1/cmsBeam.xml

* Remove unused files

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hold
until next IB - it looks like the test picked up Sunanda's PR which was integrated at about an hour ago

**Comment by kpedro88** [comment]
@ianna you edited `dict2023Geometry.py`, therefore you need to rerun `generate2023Geometry.py` to update the configs. The unit test tells you which ones need to be updated (well, all of them):
```
cmsExtendedGeometry2023D10XML_cfi.py differs
cmsExtendedGeometry2023D4XML_cfi.py differs
cmsExtendedGeometry2023D7XML_cfi.py differs
cmsExtendedGeometry2023D9XML_cfi.py differs
cmsExtendedGeometry2023D12XML_cfi.py differs
cmsExtendedGeometry2023D8XML_cfi.py differs
cmsExtendedGeometry2023D11XML_cfi.py differs
```

And of course this will conflict with #17970 and #17995...

**Comment by ianna** [comment]
@kpedro88 - I actually did regenerate them and tested locally. It's the IB problem. I'll wait for a clean one.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - how about this one?

**Comment by kpedro88** [comment]
I would prefer to merge at least #17995 before this one.

**Comment by ianna** [comment]
@davidlange6 - please, merge #17995 asap so that I could update this one.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
hmmm... the tests pass...

**Comment by kpedro88** [comment]
again, tests ran against `CMSSW_9_1_X_2017-03-22-2300` which didn't have D13

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - it looks like unrelated problem in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18004/18696/addOnTests/hlt_data_GRun/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run2_hlt_GRun_--relval_9000,50_--datatier_RAW_--eventcontent_RAW_-.log:
```
25-Mar-2017 12:03:58 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root
[2017-03-25 12:04:43.739926 +0100][Error  ][AsyncSock         ] [eoscms.cern.ch:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout
[2017-03-25 12:05:28.496067 +0100][Error  ][AsyncSock         ] [eoscms.cern.ch:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout
[2017-03-25 12:05:28.496945 +0100][Error  ][PostMaster        ] [eoscms.cern.ch:1094 #0] Unable to recover: [ERROR] Socket timeout.
[2017-03-25 12:05:28.497052 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_prepare (flags: kXR_stage , priority: 0, paths: /eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root). Trying to recover.
[2017-03-25 12:05:28.497287 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_query (code: kXR_Qconfig, arg length: 9). Trying to recover.
[2017-03-25 12:05:28.497336 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Impossible to send message kXR_open (file: /eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  file_open 25-Mar-2017 12:05:28 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root.
%MSG
[2017-03-25 12:05:28.498651 +0100][Error  ][XRootD            ] [eoscms.cern.ch:1094] Unable to send the message kXR_open (file: /eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root?tried=, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ): [FATAL] Socket timeout
25-Mar-2017 12:05:28 CET  Fallback request to file root://cms-xrd-global.cern.ch//store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root
[2017-03-25 12:05:29.515662 +0100][Error  ][AsyncSock         ] [xrootd-cms-redir-01.cr.cnaf.infn.it:1094 #0.0] Unable to connect: Connection refused
%MSG-w XrdAdaptorInternal:  file_open 25-Mar-2017 12:08:25 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root?tried=+1213llrxrd-redir.in2p3.fr,+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,eoscms.cern.ch,eoscms-srv-b2.cern.ch,xrootd-cms-redir-01.cr.cnaf.infn.it.
%MSG
[2017-03-25 12:10:05.852309 +0100][Error  ][XRootDTransport   ] Message 0xd6c2210, stream [1, 0] is a response that we're no longer interested in (timed out)


A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.

Thread 7 (Thread 0x7f330e135700 (LWP 19583)):
#0  0x00000037e0ae5309 in syscall () from /lib64/libc.so.6
#1  0x00007f3310cf542f in XrdSys::LinuxSemaphore::Wait (this=0x7f33136496b0) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f33133c4e78) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f33133c4e60) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f3310cf55b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f330eb36700 (LWP 19582)):
#0  0x00000037e0ae5309 in syscall () from /lib64/libc.so.6
#1  0x00007f3310cf542f in XrdSys::LinuxSemaphore::Wait (this=0x7f33136496b0) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f33133c4e78) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f33133c4e60) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f3310cf55b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f330f537700 (LWP 19581)):
#0  0x00000037e0ae5309 in syscall () from /lib64/libc.so.6
#1  0x00007f3310cf542f in XrdSys::LinuxSemaphore::Wait (this=0x7f33136496b0) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f33133c4e78) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f33133c4e60) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f3310cf55b9 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClJobManager.cc:33
#5  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f330ff38700 (LWP 19580)):
#0  0x00000037e0e0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f3310b80323 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f3310c98e72 in XrdCl::TaskManager::RunTasks (this=0x7f3314b4db40) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f3310c99009 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdCl/XrdClTaskManager.cc:37
#4  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f3310939700 (LWP 19579)):
#0  0x00000037e0ae90a3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f3310b84a87 in XrdSys::IOEvents::PollE::Begin (this=0x7f33133c4f40, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f3310b81095 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffd6d4db090) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f3310b7fb48 in XrdSysThread_Xeq (myargs=0x7f3314b4cf80) at /build/cmsbld/auto-builds/CMSSW_9_0_0_pre5-slc6_amd64_gcc530/build/CMSSW_9_0_0_pre5-build/BUILD/slc6_amd64_gcc530/external/xrootd/4.5.0-oenich/xrootd-4.5.0/src/XrdSys/XrdSysPthread.cc:86
#4  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f333a27f700 (LWP 19537)):
#0  0x00000037e0e0f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f335091df87 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f335091e912 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f33533d5a50 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#4  0x00000037e0e07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e0ae8aad in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f335306bc00 (LWP 19519)):
#0  0x00000037e0adf283 in poll () from /lib64/libc.so.6
#1  0x00007f335091e774 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f335091e9da in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f335091ffd2 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00000037e0ae5307 in syscall () from /lib64/libc.so.6
#6  0x00007f3310c1f97a in XrdAdaptor::RequestManager::initialize(std::weak_ptr<XrdAdaptor::RequestManager>) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#7  0x00007f3310bfc142 in XrdFile::open(char const*, int, int) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#8  0x00007f3310bfdcdb in XrdFile::XrdFile(std::string const&, int, int) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libUtilitiesXrdAdaptor.so
#9  0x00007f3310d36f24 in XrdStorageMaker::open(std::string const&, std::string const&, int, StorageMaker::AuxSettings const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/pluginUtilitiesXrdAdaptorPlugin.so
#10 0x00007f33513567e5 in StorageFactory::open(std::string const&, int) const () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libUtilitiesStorageFactory.so
#11 0x00007f33510e4e06 in TStorageFactoryFile::Initialize(char const*, char const*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libIOPoolTFileAdaptor.so
#12 0x00007f33510e5774 in TStorageFactoryFile::TStorageFactoryFile(char const*, char const*, char const*, int, int, bool) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-24-2300/lib/slc6_amd64_gcc530/libIOPoolTFileAdaptor.so
#13 0x00007f334cc800dc in ?? ()
#14 0x00007f3300000000 in ?? ()
#15 0x0000000000000000 in ?? ()

Current Modules:

Module: none (crashed)

A fatal system signal has occurred: external termination request
```

**Comment by ianna** [comment]
and here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18004/18696/addOnTests/hlt_data_GRun2016/cmsRun__cvmfs_cms-ib.cern.ch_week0_slc6_amd64_gcc530_cms_cmssw-patch_CMSSW_9_1_X_2017-03-24-2300_src_HLTrigger_Configuration_test_OnLine_HLT_GRun2016..log:
```
25-Mar-2017 12:12:10 CET  Initiating request to open file file:RelVal_Raw_GRun2016_DATA.root
----- Begin Fatal Exception 25-Mar-2017 12:12:11 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file 'RelVal_Raw_GRun2016_DATA.root'
   Additional Info:
      [a] Input file file:RelVal_Raw_GRun2016_DATA.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 and @smuzaffar - ????

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
Hi @ianna - please rebase

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - please, re-sign

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
