### PR TITLE
Update NanoAOD for MiniAOD v2 - part 3 (master version)

### PR DESCRIPTION
**Pull request by arizzi**
-Use updated jecs for lepton-jets variables
-update tau mva ids
-minor fix in tth lepton MVA

### CODE REVIEW

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.

the error seem unrelated to the PR

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22840	53ce6a8
- most changes are in the PhysicsTools/NanoAOD. The reco-related changes include additions of new payload configurations/setup in RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py . Existing reco/miniAOD tau workflows are not affected.
- jenkins tests pass and comparisons with the baseline show differences only in the nanoAOD (1325.7) workflow: most changes are in tau plots, there are also some in jets and TTH mva plots

**Comment by fabiocos** [comment]
+1

**Comment by vlimant** [comment]
Hi all,

> * The reco-related changes include additions of new payload configurations/setup in RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py . Existing reco/miniAOD tau workflows are not affected.

 this indeed is pulling conditions from outside of the GT ; this is sort of bad for production purpose isn't it ?

**Pull request merged**
