### PR TITLE
Mu pog nano aod v2 backport

### PR DESCRIPTION
**Pull request by rbhattacharya04**
This is the backport of the pull request - https://github.com/cms-sw/cmssw/pull/43642
This backport is meant for the CMSSW 14_0
We want the newly added variables at the original PR, to be included in the Muon POG custom Nano production, which will happen in CMSSW 14_0

### CODE REVIEW

**Comment by vlimant** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
