### PR TITLE
Fix cms::cuda::ESProduct for zero devices

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR
- renames `numberOfCUDADevices()` function to `cms::cuda::numberOfDevices()` to follow the convention established in #28537 (somehow this function slipped through then)
- enables `cms::cuda::ESProduct` to be constructed on a machine without GPUs

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
test parameters
enable_tests = gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@fwyzard Please review.

I was trying to run the patatrack pixel tracking on CPU on a machine without GPUs, and it failed because some EventSetup stuff (IIRC it was PixelCPEFast) tried to construct `cms::cuda::ESProduct()` that tried to ask the number of CUDA devices and threw an exception. Let me know if you'd prefer this PR to be cherry-picked to cms-patatrack/cmssw.

**Comment by fwyzard** [comment]
Going over at the code it looks good to me.
I'm fine with getting the information from the `CUDAService`, but I thought from the framework side you wanted to reduce the reliance on it ?

By the way, do we have any other uses of `numberOfCUDADevices` , possibly in the Patatrack branch ?
I was surprised that I didn't find any.

> Let me know if you'd prefer this PR to be cherry-picked to cms-patatrack/cmssw.

No, if this enters pre4 I'll pick it up when I update Patatrack to it.

**Comment by makortel** [comment]
> I'm fine with getting the information from the `CUDAService`, but I thought from the framework side you wanted to reduce the reliance on it ?

Yeah, this PR is sort-of an quick&easy(&dirty?) fix to get the default constructor working without devices. 

The ESProducts in device memory can be done in a better way that does not require device-targeting ESProducts to be constructed for a CPU-only job. So eventually this behavior will go away.

> By the way, do we have any other uses of `numberOfCUDADevices` , possibly in the Patatrack branch ?

We do not. The `cms::cuda::chooseDevice()` (used by `cms::cuda::ScopedContext`) calls `CUDAService::numberOfDevices()` directly, so it is effectively the same.

> No, if this enters pre4 I'll pick it up when I update Patatrack to it.

Let's try that then.

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

About

> DQMHistoTests: Total failures: 40

see #29076

**Pull request merged**
