### PR TITLE
Delete Hydjet2Analyzer.cc

### PR DESCRIPTION
**Pull request by wouf**
Delete Hydjet2Analyzer.cc from Hydjet  to avoid multiple definition if it with Hydjet2

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
please test

**Comment by covarell** [comment]
@wouf I do not understand this compilation problem, can you test it locally to see if you can reproduce it?

**Comment by davidlt** [comment]
@covarell https://github.com/cms-sw/cmssw/blob/de3e672d6c2f87abbb3a67cda2871b57dee4f591/GeneratorInterface/HydjetInterface/test/BuildFile.xml#L14

There is explicit reference to this file in the BuildFile.

**Comment by davidlange6** [comment]
@wouf - is there a fix planned for this error?

**Comment by wouf** [comment]
Sorry for late reaction, I corrected it.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
