### PR TITLE
SCAL online DQM monitoring

### PR DESCRIPTION
**Pull request by sachikot**
modified DQMScalInfo.cc to scal online dqm monitoring

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
should be:
    l1tscollectionToken_ = consumes<Level1TriggerScalersCollection>(parameters_.getUntrackedParameter<edm::InputTag>("l1TSCollection", edm::InputTag("scalersRawToDigi")));

**Comment by deguio** [comment]
please update

**Comment by danduggan** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
