### PR TITLE
Add wfs to test Run3 skims

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Add Run3 skims to the standard relval wfs. The following wfs are added: 140.103-140.118.

#### PR validation:

Tested on the aforementioned wfs. At the moment, the wfs that run on 2022B (140.105, 140.110, 140.112, 140.113, 140.117, 140.118) will fail in the tests because of the issue at the HLT step. Maybe @cms-sw/hlt-l2 will have an idea what is wrong with the configuration (HLT:relval2022 is used, which should correspond to GRun) when using 2022B data. Alternatively, we can switch to fake HLT when testing these wfs.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be back ported to 12_4_X.

FYI: @sam7k9621 @cms-sw/alca-l2 @bbilin @rappoccio @jmartinb

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by giovanni-mocellin** [comment]
Hi all,
I see from the errors, that the issue you're having here are related to my recent PR (which is now merged, in fact).
If you want to do the tests with it included, you also need to include another PR from cms-data (which is now merged): https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/13

**Comment by kskovpen** [comment]
> Hi all,
> I see from the errors, that the issue you're having here are related to my recent PR (which is now merged, in fact).
> If you want to do the tests with it included, you also need to include another PR from cms-data (which is now merged): [cms-data/L1Trigger-CSCTriggerPrimitives#13](https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/13)

Thanks a lot @giovanni-mocellin

**Comment by kskovpen** [comment]
please test with https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/13

**Comment by kskovpen** [comment]
@giovanni-mocellin do you know if there is some other PR to include in these tests to deal with the problems reported in [140.105](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-89f107/26393/runTheMatrix-results/140.105_RunBTagMu2022B+RunBTagMu2022B+HLTRUN3+RECONANORUN3+SKIMBTAGMURUN3)?

**Comment by tvami** [comment]
@kskovpen that doesnt seem connected. Giovanni changed things for CSS-GEM. This issue now is PPS

@elfontan @panoskatsoulis can you maybe comment on the issue with the L1T menu 
```
An exception of category 'ConditionsError' occurred while
   [0] Processing  Event run: 355442 lumi: 20 event: 33041904 stream: 0
   [1] Running path 'HLT_PPSMaxTracksPerRP4_v1'
   [2] Calling method for module L1TGlobalProducer/'hltGtStage2ObjectMap'
Exception Message:
 Error L1 menu loaded in via conditions does not match the L1 actually run 1135184612 vs 2016981387. This means that the mapping of the names to the bits may be incorrect. Please check the L1TUtmTriggerMenuRcd record supplied. Unless you know what you are doing, do not simply disable this check via the config as this a major error and the indication of something very wrong
```

**Comment by tvami** [comment]
@kskovpen also 2022A was 900 GeV... wouldnt it be better to use a 13.6 TeV run for these relvals?

**Comment by kskovpen** [comment]
> @kskovpen also 2022A was 900 GeV... wouldnt it be better to use a 13.6 TeV run for these relvals?

Once we understand the current issues (which are in 2022B), we can harmonize things further.

**Comment by panoskatsoulis** [comment]
> @kskovpen that doesnt seem connected. Giovanni changed things for CSS-GEM. This issue now is PPS
> 
> @elfontan @panoskatsoulis can you maybe comment on the issue with the L1T menu
> 
> ```
> An exception of category 'ConditionsError' occurred while
>    [0] Processing  Event run: 355442 lumi: 20 event: 33041904 stream: 0
>    [1] Running path 'HLT_PPSMaxTracksPerRP4_v1'
>    [2] Calling method for module L1TGlobalProducer/'hltGtStage2ObjectMap'
> Exception Message:
>  Error L1 menu loaded in via conditions does not match the L1 actually run 1135184612 vs 2016981387. This means that the mapping of the names to the bits may be incorrect. Please check the L1TUtmTriggerMenuRcd record supplied. Unless you know what you are doing, do not simply disable this check via the config as this a major error and the indication of something very wrong
> ```

Hi Tamas, not sure but smells like an issue with the utm library
Maybe, some mismatching of the ult lib in the cmssw release that was used to make the Rcd in the db and the utm library that the release in the workflow uses? (it's just a guess)

**Comment by elfontan** [comment]
Hi @tvami, @panoskatsoulis,
honestly the utm libraries are the same since a while, I would be surprised to see an issue appearing now related to them...
I am now looking at the part of the emulator launching the message to understand what _run 1135184612 vs 2016981387_ is referring to ([L1TGlobalProducer.cc](https://github.com/cms-sw/cmssw/blob/5222b47952a15160dd438f421170741529cc363e/L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc#L330-L343)). 
We are comparing _(*m_uGtAlgBlk)[0].getL1FirmwareUUID() << " vs " << utml1GtMenu->getFirmwareUuidHashed()_, not sure about the difference, I have to see.

(Maybe @Sam-Harper @fwyzard can help me to clarify here? If I am not mistaken, you were mentioning something related to this UUID-UuidHashed during some discussions this week... Sorry and thanks in advance!)

**Comment by missirol** [comment]
> Maybe @cms-sw/hlt-l2 will have an idea what is wrong with the configuration (HLT:relval2022 is used, which should correspond to GRun) when using 2022B data.

@kskovpen , apologies, I saw this only now. My understanding is the following.

 - The issue is related to the tag containing the L1TMenu in the GT used by these new workflows (`auto:run3_hlt_relval`, i.e. `124X_dataRun3_HLT_relval_v6`).

 - That tag contains a payload that does not match exactly the L1T menu used online for the input data used by these workflows. Note: they are not expected to match in the first place, as `run3_hlt_relval` should always contain the very-latest L1T menu (and only that) as a single-IOV tag, and this normally differs from the L1T menu used for a run from the past.

I think one way out is to include in these wfs the `L1REPACK` step (which re-runs L1T with whatever L1T menu is loaded by the GT); this is what is done, for example, in other existing RelVals that run on older data, e.g. wf `139.004`.

Would that be an option? Could be something like this
```diff
-steps['HLTRUN3']=merge( [ {'-s':'HLT:@%s'%hltKey2022,},{'--conditions':'auto:run3_hlt_relval'},{'--era':'Run3'},steps['HLTD'] ] )
+steps['HLTRUN3']=merge( [ {'-s':'L1REPACK:Full,HLT:@%s'%hltKey2022,},{'--conditions':'auto:run3_hlt_relval'},{'--era':'Run3'},steps['HLTD'] ] )
```

Based on the above, I would expect wfs like `140.001` and `140.106` to have this same issue (Run2022A), but they are passing. I think the reason is that input files for those wfs have 0 events, so one doesn't get to see the error. Examples:
```
root://xrootd-cms.infn.it//store/data/Run2022A/MinimumBias/RAW/v1/000/353/053/00000/58149c44-cd32-4bd9-ace7-e63b35943d50.root
root://xrootd-cms.infn.it//store/data/Run2022A/JetHT/RAW/v1/000/353/053/00000/f053075a-5de7-4eef-9aae-5065f28e971b.root
root://cms-xrd-global.cern.ch//store/data/Run2022A/Commissioning/RAW/v1/000/353/053/00000/dee4b7f2-b4a8-412c-8524-fe4e61c8062f.root
```

**Comment by kskovpen** [comment]
> > Maybe @cms-sw/hlt-l2 will have an idea what is wrong with the configuration (HLT:relval2022 is used, which should correspond to GRun) when using 2022B data.
> 
> @kskovpen , apologies, I saw this only now. My understanding is the following.
> 
> * The issue is related to the tag containing the L1TMenu in the GT used by these new workflows (`auto:run3_hlt_relval`, i.e. `124X_dataRun3_HLT_relval_v6`).
> * That tag contains a payload that does not match exactly the L1T menu used online for the input data used by these workflows. Note: they are not expected to match in the first place, as `run3_hlt_relval` should always contain the very-latest L1T menu (and only that) as a single-IOV tag, and this normally differs from the L1T menu used for a run from the past.
> 
> I think one way out is to include in these wfs the `L1REPACK` step (which re-runs L1T with whatever L1T menu is loaded by the GT); this is what is done, for example, in other existing RelVals that run on older data, e.g. wf `139.004`.
> 
> Would that be an option? Could be something like this
> 
> ```diff
> -steps['HLTRUN3']=merge( [ {'-s':'HLT:@%s'%hltKey2022,},{'--conditions':'auto:run3_hlt_relval'},{'--era':'Run3'},steps['HLTD'] ] )
> +steps['HLTRUN3']=merge( [ {'-s':'L1REPACK:Full,HLT:@%s'%hltKey2022,},{'--conditions':'auto:run3_hlt_relval'},{'--era':'Run3'},steps['HLTD'] ] )
> ```
> 
> Based on the above, I would expect wfs like `140.001` and `140.106` to have this same issue (Run2022A), but they are passing. I think the reason is that input files for those wfs have 0 events, so one doesn't get to see the error. Examples:
> 
> ```
> root://xrootd-cms.infn.it//store/data/Run2022A/MinimumBias/RAW/v1/000/353/053/00000/58149c44-cd32-4bd9-ace7-e63b35943d50.root
> root://xrootd-cms.infn.it//store/data/Run2022A/JetHT/RAW/v1/000/353/053/00000/f053075a-5de7-4eef-9aae-5065f28e971b.root
> root://cms-xrd-global.cern.ch//store/data/Run2022A/Commissioning/RAW/v1/000/353/053/00000/dee4b7f2-b4a8-412c-8524-fe4e61c8062f.root
> ```

Many thanks for your feedback @missirol

**Comment by kskovpen** [comment]
Suggestion from @missirol worked - thanks. 
Summary: 
- 140.001, 140.002, 140.103, 140.104, 140.105, 140.106, 140.113, 140.114, 140.115, 140.116, 140.117 run fine and have data at CERN
- 140.107, 140.108, 140.109, 140.110, 140.111, 140.112 do not have data at CERN (unless I overlooked it somehow)
- 140.118 does not have the corresponding PD, probably we should use ParkingBPH1-6.
Let's test this again to confirm.
@sam7k9621 please check that all current skims are included in these new wfs - I think, yes, but it never hurts to double check.

**Comment by kskovpen** [comment]
please test with https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/13

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by srimanob** [comment]
I think relval_standard.py needs update.

**Comment by kskovpen** [comment]
> I think `relval_standard.py` needs update from `Run*2022A` to `Run*2022B`.

Indeed, I forgot to push it.

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
As expected, those with data not at CERN, failed. Propose to go ahead and merge it - to be further updated with the more recent data, when available. Now retriggering the tests with available inputs.

**Comment by kskovpen** [comment]
test parameters:
- workflows = 140.001, 140.002, 140.103, 140.104, 140.105, 140.106, 140.113, 140.114, 140.115, 140.116, 140.117
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
What is your intention of cosmic skim?
- If need in` --scenario pp`, you should add `from DPGAnalysis.Skims.SkimsCosmics_DPG_cff import *` to the end of https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/Skims_cff.py
- If need in `--scenario cosmic`, you should remove `LogError+LogErrorMonitor` because they are not defined/included in https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/SkimsCosmics_cff.py

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
test parameters:

- workflows = 140.001,140.002,140.103,140.104,140.105,140.106,140.113,140.114,140.115,140.116,140.117
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
Do you really need cosmic skim in pp?
If not, maybe remove the workflow and also 
`from DPGAnalysis.Skims.SkimsCosmics_DPG_cff import *`
then wf 1000 should be OK.

If needed, I think we need more work to do.

**Comment by kskovpen** [comment]
> Do you really need cosmic skim in pp? If not, maybe remove the workflow and also `from DPGAnalysis.Skims.SkimsCosmics_DPG_cff import *` then wf 1000 should be OK.
> 
> If needed, I think we need more work to do.

I've been trying to see how to make it work, but OK, I agree, let's for now remove it.

**Comment by kskovpen** [comment]
test parameters:

- workflows = 140.001,140.002,140.103,140.104,140.105,140.106,140.113,140.114,140.115,140.116
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by tvami** [comment]
@kskovpen wait so how will this affect T0? Will the Cosmics skims fail?

**Comment by kskovpen** [comment]
> @kskovpen wait so how will this affect T0? Will the Cosmics jobs fail due to the errors above?

There is no such dependence. What we are trying to do now is to fully synchronize the T0 and RelVal definitions.

**Comment by kskovpen** [comment]
@srimanob would you agree if we go ahead with the current implementation and add more things as they come?

**Comment by srimanob** [comment]
@kskovpen @tvami 

Looking on Tier-0 setting,
https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=356005
There is a cosmics skim which should be fail. However, it seems we have 0 events on this SKIM from HLT,
https://cmsoms.cern.ch/cms/triggers/hlt_trigger_rates?cms_run=356005&props.11280_11278.selectedCells=Physics:2&props.11282_11278.selectedCells=Cosmics:2

Maybe that is the reason why we don't see the issue yet.

Should this be disabled on Tier-0 site? I assume it does not pick up the skim from the release automatically.

**Comment by srimanob** [comment]
@kskovpen 
I am happy to sign it. Few things:
+ Do you need to update the PR description, on error from HLT?
+ Maybe if we can transfer all needed datasets for PR test, then it would be great. I assume that this can be done by @cms-sw/alca-l2 also.

**Comment by kskovpen** [comment]
> @kskovpen @tvami
> 
> Looking on Tier-0 setting, https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=356005 There is a cosmics skim which should be fail. However, it seems we have 0 events on this SKIM from HLT, https://cmsoms.cern.ch/cms/triggers/hlt_trigger_rates?cms_run=356005&props.11280_11278.selectedCells=Physics:2&props.11282_11278.selectedCells=Cosmics:2
> 
> Maybe that is the reason why we don't see the issue yet.
> 
> Should this be disabled on Tier-0 site? I assume it does not pick up the skim from the release automatically.

Thanks a lot for the investigations @srimanob. I believe that there is no automatic retrieval of relval configuration to apply at T0 but maybe we could double check with T0 experts.

**Comment by kskovpen** [comment]
> @kskovpen I am happy to sign it. Few things:
> 
>     * Do you need to update the PR description, on error from HLT?
> 

Yes, we should, but maybe lets also discuss with T0.

>     * Maybe if we can transfer all needed datasets for PR test, then it would be great. I assume that this can be done by @cms-sw/alca-l2 also.

If we can get these datasets transferred, it would be great. If anyone knows who is responsible for this, please let us know.

**Comment by tvami** [comment]
> If we can get these datasets transferred, it would be great. If anyone knows who is responsible for this, please let us know.

I can do this

**Comment by tvami** [comment]
> Looking on Tier-0 setting, https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=356005 There is a cosmics skim which should be fail. 

I requested a replay on a cosmics run over the weekend, it all just ran fine

**Comment by srimanob** [comment]
> > Looking on Tier-0 setting, https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=356005 There is a cosmics skim which should be fail.
> 
> I requested a replay on a cosmics run over the weekend, it all just ran fine

Which RUN? Cosmics run or collision run?

**Comment by tvami** [comment]
> Which RUN? I assume cosmics run is OK. What is not OK is running cosmics skim on collision run.

We tested the whole config on a cosmics run and the whole config on a collision run. Both were successful

**Comment by tvami** [comment]
let me double check, these are the PDs to be copied, right?
```
/Cosmics/Run2022B-v1/RAW
/DisplacedJet/Run2022B-v1/RAW
/MET/Run2022B-v1/RAW
/EGamma/Run2022B-v1/RAW
/Tau/Run2022B-v1/RAW
/DoubleMuon/Run2022B-v1/RAW
/MuonEG/Run2022B-v1/RAW
/ParkingBPH/Run2022B-v1/RAW
```
did I miss anything?

**Comment by srimanob** [comment]
Replay was done on Run 356005, right? It has 0 events of cosmics,
https://cmsweb.cern.ch/couchdb/t0_workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/PromptReco_Run356005_Cosmics

**Comment by kskovpen** [comment]
> let me double check, these are the PDs to be copied, right?
> 
> ```
> /Cosmics/Run2022B-v1/RAW
> /DisplacedJet/Run2022B-v1/RAW
> /MET/Run2022B-v1/RAW
> /EGamma/Run2022B-v1/RAW
> /Tau/Run2022B-v1/RAW
> /DoubleMuon/Run2022B-v1/RAW
> /MuonEG/Run2022B-v1/RAW
> /ParkingBPH/Run2022B-v1/RAW
> ```
> 
> did I miss anything?

Yes, thanks.

**Comment by tvami** [comment]
So https://cmsweb.cern.ch/das/request?input=dataset%3D%2FParkingBPH%2FRun2022B-v1%2FRAW&instance=prod/global
doesnt exists essentially (has zero events)

the rest I made a rule for
```
bash-4.2$ rucio add-rule cms:/Cosmics/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
a60c6a2bd05841a3956a68fdfddc9707
bash-4.2$ rucio add-rule cms:/DisplacedJet/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
0c8078cf6d4c4f579295b779bfe25cc2
bash-4.2$ rucio add-rule cms:/MET/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
c9a52b0f10eb4466b055b6d182930643
bash-4.2$ rucio add-rule cms:/EGamma/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
099d5fa468a040699a3ee6aaaa0c5cac
bash-4.2$ rucio add-rule cms:/Tau/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
0b553cb0ada74bf6aa3d4d1f362a8b9d
bash-4.2$ rucio add-rule cms:/DoubleMuon/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
a3ea0b8c78c84af1ac48483ddc2c4a55
bash-4.2$ rucio add-rule cms:/MuonEG/Run2022B-v1/RAW 1 T2_CH_CERN --lifetime 2592000
6f83a0737cfc4c02a0a0cbb534686ace
```

**Comment by kskovpen** [comment]
> > Which RUN? I assume cosmics run is OK. What is not OK is running cosmics skim on collision run.
> 
> We tested the whole config on a cosmics run and the whole config on a collision run. Both were successful

While the skims are tested in replays, I assume that there is no validation done for it in terms of physics output. Maybe we can go ahead with the current relval implementation and test it at T0 as the possible next step.

@tvami when you hear back from our friend rucio that the datasets have been transferred, please report here :)

**Comment by tvami** [comment]
@kskovpen you can go ahead, the transfer is complete

**Comment by kskovpen** [comment]
test parameters:
- workflows = 140.001,140.002,140.103,140.104,140.105,140.106,140.113,140.114,140.115,140.116,140.117,140.107,140.108,140.109,140.110,140.111,140.112
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
test parameters:

- workflows = 140.001,140.002,140.103,140.104,140.105,140.106,140.113,140.114,140.115,140.116,140.117,140.107,140.108,140.109,140.110,140.111,140.112
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
test parameters:

- workflows = 140.001,140.002,140.103,140.104,140.105,140.106,140.113,140.114,140.115,140.116,140.117,140.107,140.108,140.109,140.110,140.111,140.112
- relvals_opt = -w standard

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
@srimanob you are welcome to sign :)

**Comment by srimanob** [comment]
OK, now seems we are in good shape.

I think one clarification should be done is that will we have cosmics datasets in pp collision? And will the skim is need there? Where should this be clarified? In the joint meeting? However, that can be done beyond this PR. I would suggest at the moment, take it out from Tier-0. @tvami @kskovpen

**Comment by srimanob** [comment]
+Upgrade

This PR adds RUN-3 skim workflows to runTheMatrix. All added workflows pass the PR test. One remaining question on cosmics with pp skim, to be followed up.

**Comment by tvami** [comment]
> Where should this be clarified? In the joint meeting? 

I think that's a good place for it, ORM this week is @mdmorris , please be sure the PdmV and DDT is present at the meeting.

> I would suggest at the moment, take it out from Tier-0. 

Given that it causes no problems for now, I'd say we should do this when the HLT menu changes and the merger happens, so we'll need to modify the config anyway.

Anyway, the final plan should be discussed on Friday and the ORM should follow up on the results of the discussion

**Comment by srimanob** [comment]
Seem to be a good plan to move, thanks.

**Comment by kskovpen** [comment]
+pdmv

**Comment by kskovpen** [comment]
@cms-sw/orp-l2 please consider merging this PR so that we could proceed with the backport to 12_4

**Comment by perrotta** [comment]
+1

**Pull request merged**
