### PR TITLE
Changed Type1PFMET to global::EDProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the CMS deprecation warnings.

#### PR validation:

Code compiles without CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by rappoccio** [comment]
Unit tests may be showing spurious failure. Restarting.

**Comment by rappoccio** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- technical PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
