### PR TITLE
Configuration parameter copy and modify functions extended

### PR DESCRIPTION
**Pull request by Dr15Jones**
The `clone` and `Modifier.toModify` methods have been extended to allow further modifications to the parameters after they have been copied.
1) Specify `None` as the value of the parameter will cause the parameter to be removed from the configuration
2) Parameters within embedded PSets can now be modified using a python dict as the value. The keys of the dictionary are the parameter
    names and the values are the new values to use.
The `clone` and `Modifier.toModify` both call the same helper function to do the work of modifying the copied parameters.

This also fixed the problem with the previous pull request for this feature.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I tested this with #13216 by running `runTheMatrix.py -l 5.1,140.1` where those two workflows exhibited the two different failures seen in the IB. With this pull request the jobs ran fine.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test aborted because it timed out

**Comment by makortel** [comment]
@Dr15Jones It looks like `PSet.clone()` does not work with `dict` arguments. Example (tested in CMSSW_8_1_X_2016-02-22-1100):
```
$ cat foo.py
import FWCore.ParameterSet.Config as cms
p1 = cms.PSet(anInt = cms.int32(1), a = cms.PSet(b = cms.int32(1)))
p2 = p1.clone(a = dict(b = 2))
print p2.a.b.value()
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 3, in <module>
    p2 = p1.clone(a = dict(b = 2))
  File .../CMSSW_8_1_X_2016-02-22-1100/python/FWCore/ParameterSet/Types.py", line 653, in clone
    myparams[key].setValue(value)
AttributeError: 'PSet' object has no attribute 'setValue'
```

**Comment by Dr15Jones** [comment]
#13526

**Pull request merged**
