### PR TITLE
Add purity plots to vertex validation plus some cleanup

### PR DESCRIPTION
**Pull request by makortel**
This PR adds the following plots to vertex validation
- Following in two flavours, as reco PV matched to gen PV, and reco PV not matched to gen PV
  - Purity of reco PV (pT-weighted fraction of tracks of the reco PV matched to TPs from gen PV)
  - pT-weighted fraction of tracks associated to gen PV but are not associated with reco PV (denoted here "missing")
  - Purity of each reco vertex vs. the index of the vertex in the vertex collection
- Fake rate vs. purity
- New sum(pT^2) plots for
  - Reco vertices not associated to gen PV
  - Reco vertices not associated to gen PV such that pT of tracks associated to gen PV is removed
  - Reco vertices associated to gen PV
  - Reco vertices associated to gen PV, when gen PV is not the highest sum(pT^2) one

The plots require the track-TrackingParticle association, so this mode is made mandatory now and the configuration switch is removed. 

On a related note, following cleanup is done
- Remove unnecessary stuff from V0Validator and move all previously hard-coded configuration to configuration
  - For better interoperability with edmConfigBrowser
- Remove PrimaryVertexAnalyzer and PrimaryVertexAnalyzer4PU as obsolete
  - "Fixes" bunch of static analyzer issues

Tested in CMSSW_7_5_X_2015-03-15-1400. Should have no effect on any existing plot, just adds new plots.

@rovere @VinInn

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by makortel** [comment]
Removed more unused stuff from V0Validator and added missing `override`s to it and PrimaryVertexAnalyzer4PUSlimmed. Clang compiles fine locally.

**Comment by makortel** [comment]
ping

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
