### PR TITLE
Add processGUID() singleton, and use it in InputSource, StatisticsSenderService, and CondorStatusService

### LINKED ISSUE #36351: Correlate entries in monit_prod_cmssw_pop_* with those in monit_prod_condor_raw_metric*
Each CMSSW job reports popularity entries in monit_prod_cmssw_pop_*. 
Also, each job reports utilization and other things in monit_prod_condor_raw_metric*.

There is no ID to be used as unique identifier between these entities, and this is needed. For example, if a job was accessing a file X from local/remote storage, we want to know the CPU efficiency degradation.

Files are listed in monit_prod_cmssw_pop_* and CPU utilization in monit_prod_condor_raw_metric*. No way to correlate this. 

Is it very difficult to add an ID that will help people to join both sources of information? 

Thanks

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR adds `processGUID()` function to return a singleton `edm::Guid` as a process-level GUID, and uses that in InputSource, StatisticsSenderService, and adds a new Chirp field for it in CondorStatusService. The GUID helps to correlate information in different monitoring systems that come from the same process.

Resolves #36351.

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Would this be better (than #36567) then?

**Comment by Dr15Jones** [comment]
@makortel I think this looks better (since it is much simpler).

**Comment by makortel** [comment]
+1

Any possible further adjustments (https://github.com/cms-sw/cmssw/issues/36351#issuecomment-999625939) can be done in a follow-up PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
