### PR TITLE
Add pulse max check parameter

### PR DESCRIPTION
**Pull request by mbandrews**
- Add parameter in PresampleTask to disable digi pulse max check during a cosmics run
- Modify online dqm cfg to use std sequences as much as possible: this greatly avoids issues with missing modules during cmssw updates

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mbandrews** [comment]
Any updates on this?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
