### PR TITLE
Properly handle failed file opening in DQMRootSource

### PR DESCRIPTION
**Pull request by Dr15Jones**
Since ROOT 6 is unable to propagate exceptions through cling,
it is necessary to trap file open errors in TFileAdaptor and
then call edm::threadLocalException::getException() to get
the underlying exception to be rethrown.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This code replicates the steps done in InputFile.cc
https://github.com/cms-sw/cmssw/blob/master/IOPool/Input/src/InputFile.cc#L22

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
