### PR TITLE
[ALCA_DB] Apply code-checks/format with misc-definitions-in-headers

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping @cms-sw/alca-l2  @cms-sw/db-l2

**Comment by francescobrivio** [comment]
+alca
 - technical
 - tests passed

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by smuzaffar** [comment]
@ggovi , can you please sign this?

**Comment by smuzaffar** [comment]
@qliphy @silviodonato , can we please merge this, it only contains code-format changes for one file

**Comment by qliphy** [comment]
merge

**Comment by ggovi** [comment]
+1

**Pull request merged**
