### PR TITLE
HCAL: fixing fine grain bits to be set based on unpacked TDC 

### PR DESCRIPTION
**Pull request by gk199**
#### PR description:

Changes are made in HcalFinegrainBits.cc to have both HB and HE fine grain bits set based on unpacked TDC. The fine grain bit algorithm relies on trigger primitives, which are prior to where the HB TDC packing (6:2 bit LUT) is performed. The 6:2 packing occurs in PackerHelp.h (tdc1 and tdc2 implemented in https://cmssdt.cern.ch/lxr/source/EventFilter/HcalRawToDigi/plugins/PackerHelp.h). With the change, HB and HE rely on the same logic, using `tdc_boundary` to compare to the TDC values. 

Variable name `tdc_HE` was changed to `tdc_boundary` to be more clear. This encodes the prompt – delayed boundaries for both HB and HE. 

Initial fine grain bit PR #34600 and #35599. L1 emulator PR (relies on the FG bits) #36919. 

#### PR validation:

Tested in `CMSSW_12_4_X_2022-03-21-1100`. Passed `runTheMatrix.py`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Will be backported to 12_3_X if possible, as this is relevant to Run 3 L1 trigger work.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
> @perrotta, @dpiparo, @qliphy Do you know why the tests are still pending? The test command was issued 2 days ago.

@smuzaffar should we simply restart the tests, or is there anything blocking them that has to be fixed?

**Comment by smuzaffar** [comment]
please test
yes, if you do not see any bot activity and jenkins is not busy then feel free to restart any pr test

**Comment by perrotta** [comment]
Since the L1 signature was given before the test could finish, could anybody confirm that the test outputs are as expected, in particular the changes observed in the L1T HCAL DQM plots for the Run3 wf 11834 (and no changes in all other workflows)?

image

**Comment by gk199** [comment]
Changes in hcalOccSentFb2 are expected, due to the changes in setting fine grain bits 1,2, and 3 (zero indexing). hcalOccSentFb is filled [here](https://cmssdt.cern.ch/lxr/source/DQM/L1TMonitor/src/L1TStage2CaloLayer1.cc#0309) when `t0().fineGrain(1)` (fine grain bit 1 in SOI) is set. Due to the PR, fineGrain(1) will be set more often in HB, leading to DQM plot changes. Checked with HCAL DQM expert @lwang046.

**Comment by perrotta** [comment]
+1

**Pull request merged**
