### PR TITLE
[DQM DT] Changes to put back DT Noise plot in Online DQM

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR brings back a DT Noise plot in Online DQM. It sets a contant threshold of 500Hz for noise per single wire in Cosmics level, while it sets a variable threshold per chamber in Collisions taking into account known expected background rates at DT subdetector from previous studies. A Inst. Lumi of 2E34 is assumed 

These changes affect ONLY Online DQM GUI

Presented and approved on DT DPG meeting:

https://indico.cern.ch/event/1357468/contributions/5715460/attachments/2771641/4830403/DTnoiseMeeting.pdf

#### PR validation:

Tested privately in development DQM GUI with collision and cosmic runs

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport needed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by battibass** [comment]
thanks @jfernan2

**Comment by syuvivida** [comment]
This PR has been tested successfully by applying the PR on top of CMSSW_13_0_10 at online DQM machines at p5, using the DQM streamers of 370580. Additionally, https://github.com/dmwm/deployment/pull/1296 for DQMGUI layout was also tested. We had to test in CMSSW_13_0_10 as CMSSW_14_0_X cannot read the streamers of 13_0_10.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
enable profiling

**Comment by jfernan2** [comment]
please test
Testing for the last IB

**Comment by tjavaid** [comment]
+1

- Tests on the online DQM machines at P5 OK with Run `370580` using `CMSSW_13_0_14` (thanks @syuvivida and @nothingface0 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
