### PR TITLE
added esConsumes to modules in RecoLocalMuon/CSCRecHitD

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 2 modules. This required propagating the consumes collector through many helper classes.

#### PR validation:
the code compiles

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30598	86792e2 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by civanch** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
