### PR TITLE
bsunanda:Phase2-TB61 Modify the cfg's for HGCal TB in view of changes in initialuizing SD's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the cfg's for HGCal TB in view of changes in initialuizing SD's

#### PR validation:

Tested to see if the cfg's work with the recent changes

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
