### PR TITLE
Fix approximated SiStrip clusters workflow by saving SiStrip FED error information 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It has been shown (see [talk](https://indico.cern.ch/event/1271490/contributions/5484101/attachments/2679179/4647438/DPG_RawPrime_20230705.pdf)) that events repacked in the RAW' data format and then reconstructed with the dedicated process modifier `approxSiStripClusters` have a different content in terms of tracks w.r.t. the standard reconstruction starting from RAW data (with full SiStrip ADC information). Part of that is expected from information loss intrinsic to the procedure, but dedicated checks showed that in some events few perfectly valid seeds lead to no track reconstructed when data is repacked with the RAW' data format.
This has been shown to depend on the fact the currently the RAW' data format is not saving the list of SiStrip FED errors (collection  `DetIdedmEDCollection_siStripDigisHLT_*_*`) which is used in the tracking setup to construct the list of inactive componets:

https://github.com/cms-sw/cmssw/blob/a5b91a1d0848665cc6f5d3ddb11be28272302e1c/RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc#L405-L417

which is then used in trajectory building.
This PR proposed to fix this issue by keeping the missing collection (2bb7f37fdc2c5ed211c120f1e17b14b655d61d9b, supposed eventually to come from the HLT) in the repack procedure and then to use it in the `MeasurementTrackerEventProducer` (1f49f6ee100618d603f6862ebad60294f144465d).
After that is no longer necessary to run the SiStrip unpacker `siStripDigis` in the RAW2DIGI step, therefore that's excluded from execution profiting of the process modifier (6cc72b501cc8e3f44bf0e86529a539aefe729636).

#### PR validation:

Run successfully `runTheMatrix.py -l 140.58 -t 4 -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, to be backported to at least CMSSW_13_2_X

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows=159,159.02,159.03,140.56,140.58,140.6

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mandrenguyen** [comment]
+reconstruction
An increase in tracks in observed, consistent with expectations 
[c_recoTracks_generalTracks__reRECO_obj_phi.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-04-1100+971b83/58249/validateJR/140.58_RunHI2018/all_reRECO_step3/c_recoTracks_generalTracks__reRECO_obj_phi.png)
Recovered tracks are mostly from pixel pair iteration, consistent with studies that showed that rawprime was mostly losing tracks from that step.
[c_recoTracks_generalTracks__reRECO_obj_originalAlgo.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-08-04-1100+971b83/58249/validateJR/140.58_RunHI2018/all_reRECO_step3/c_recoTracks_generalTracks__reRECO_obj_originalAlgo.png)

**Comment by perrotta** [comment]
+1

**Pull request merged**
