### PR TITLE
Removed unused fwkJobReports from MessageLogger in GeneratorInterface Subsystem

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The parameter fwkJobReports is an obsolete parameter which has had no functionality for many years.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by SiewYan** [comment]
+1

**Comment by SiewYan** [comment]
The failures come from message logger, which is expected.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
