### PR TITLE
Added extra Physics Lists for neutron background study

### PR DESCRIPTION
**Pull request by civanch**
For neutron background study 3 new Physics Lists are added: FTFP_BERT_HP_EMM, FTFP_INCLXX_EMM, and FTFP_INCLXX_HP_EMM. Should not affect mainstream production.

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch were these lists minimally tested in a standalone way? Obviously this PR test just shows they compile...

**Comment by civanch** [comment]
@fabiocos , they are tested by Geant4 team - no extra hadronic component is added from us, EMM is our production variant for electromagnetic physics. FTFP_BERT_HP is the Geant4 default for high precision neutrons, we already have FTFP_BERT_HP_EML, now FTFP_BERT_HP_EMM is added. All these is well tested.
FTFP_INCLXX and FTFP_INCLXX_HP are used not so frequently and there are known advantages and concerns to use INCLXX cascade model. In past, I tried to avoid include them as CMSSW options but Sergio several times ask about such possibility for neutron background study. I think, that if a physics list is available in Geant4 distribution, then we can provide a possibility to CMS users try it out if there is a request.

**Comment by fabiocos** [comment]
@civanch in between the detailed physics validation done by Geant4 (of the model but not of the CMSSW interface proposed here) and that can be redone once this code is available, and the mere fact that this code compiles, there is a cmsRun with a modified physics list showing that this code runs on some events without crashing/doing anything odd. Was this done by you? I assume yes, I just would like to have a confirmation about it.

**Comment by civanch** [comment]
@fabiocos , I run 100 MinBias events for each Physics LIst - no problem observed , except the fact that all these new Physics Lists are substantially slower the CMS default, but this is expected.

**Comment by fabiocos** [comment]
@civanch ok thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
