### PR TITLE
BD hadron track monitoring in standard validation sequence

### PR DESCRIPTION
**Pull request by smoortga**
This PR introduces the DQM monitoring tools for B and D Hadron Tracks (for BTV group) in the standard validation sequence. The tools were introduced in PR: https://github.com/cms-sw/cmssw/pull/17444

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the errors are related to this PR

```
   [2] Calling method for module PATJetProducer/'patJetsBDHadron'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<pat::JetCorrFactors>
Looking for module label: patJetCorrFactors
```

If I'm not mistaken, they are in MC workflows with validation/DQM step and no PAT step

**Comment by smoortga** [comment]
Yes if PAT is not ran in some workflow that uses validation/DQM, then my strategy indeed fails... I did not know this was the case.

How do you think I should solve this? Do you think the problem would be solved when I add the pfImpactParameterTagInfos [here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L165) as I did before? If they get slimmed out anyway later on in the workflow of miniAOD (as we discussed in the mail thread), I think it doesn't matter we include them there.

Please let me know what you think because I don't have much experience with all of these validation workflows. Is there a way I can myself perform some tests before updating the PR?

Thanks,

Cheers
Seth

**Comment by slava77** [comment]
On 3/21/17 11:37 AM, smoortga wrote:
> Yes if PAT is not ran in some workflow that uses validation/DQM, then my
> strategy indeed fails... I did not know this was the case.
> 
> How do you think I should solve this? Do you think the problem would be
> solved when I add the pfImpactParameterTagInfos here
> <https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L165>
> as I did before? If they get slimmed out anyway later on in the workflow
> of miniAOD (as we discussed in the mail thread), I think it doesn't
> matter we include them there.
> 
> Please let me know what you think because I don't have much experience
> with all of these validation workflows. Is there a way I can myself
> perform some tests before updating the PR?

"runTheMatrix.py -l limited"

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
Hi @smoortga,
this change needs to go into the master/development branch first (91x), before it can be merged into 90x.

**Comment by smoortga** [comment]
@dmitrijus , Oh ok I see, I will make the PR for 91X first then. Thanks!

Cheers
Seth

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

4.53 issue may be fixed one way or another

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
+1
Validation stuff.
Code looks reasonable

**Comment by smoortga** [comment]
is it also possible to get this (backport) PR merged here in 90X? The same PR in 91X (https://github.com/cms-sw/cmssw/pull/18053) has been merged.

Thanks
Cheers
Seth

**Comment by davidlange6** [comment]
+1

**Pull request merged**
