### PR TITLE
separate baseDataSetRelease values for fastsim 2017

### PR DESCRIPTION
**Pull request by kpedro88**
Implements suggestion in https://github.com/cms-sw/cmssw/pull/25490#issuecomment-453515553

attn: @ssekmen @zhenhu @fabiocos

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 25400.17,250399.0,250400.17,250402.17,250405.17,250406.17,250407.17,250408.17,250409.17
(here I am testing every fastsim workflow that failed in the last IB, for completeness)

**Comment by kpedro88** [comment]
@makortel @zhenhu @ssekmen we have encountered again the problem from #25513.

1. https://github.com/cms-sw/cmssw/blob/55227c1d2af91fbed43a0bd4ac1f8db1f6dddce7/Configuration/PyReleaseValidation/python/relval_steps.py#L1051 needs to have `/PREMIX` changed to `/GEN-SIM-DIGI-RAW` to select a dataset with the correct event content. I can make this change, however:
2. The only 10_2_X dataset for `/RelValFS_PREMIXUP17_PU50` is `/RelValFS_PREMIXUP17_PU50/CMSSW_10_2_8-PU25ns_102X_mc2017_realistic_v5_FastSim-v1/PREMIX`, so we have nothing to provide that will work in this release.

What should we do about this? Can we launch another relval that will produce the needed output?

**Comment by makortel** [comment]
I'd think the only option is to produce a new pileup library with `GEN-SIM-DIGI-RAW` data tier and including `L1,DIGI2RAW` steps.

**Comment by zhenhu** [comment]
So, it seems a possible solution would be:
First get this PR merged and build an temporary official release (but missing the premix library input).
Then I will produce the missing input /RelValFS_PREMIXUP17_PU50/CMSSW_10_2_10-PU25ns_XXXXX/PREMIX in this new release, which will fix the input issue.

**Comment by fabiocos** [comment]
@zhenhu we may merge this PR, as it will fix part of the problem. But I do not think you need this to build the new library, all the ingredients should be already in the release, right?

**Comment by zhenhu** [comment]
OK, then I will build the new library with 10_2_9 plus these new changes. Once the job finished, we can update the input path here and test workflows again.

**Comment by kpedro88** [comment]
@zhenhu yes, the missing library can be produced without this PR. I think that is a better way to go.

Please note, the library needs to be produced as GEN-SIM-DIGI-RAW (with the steps L1,DIGI2RAW included). You can read #25513 for details.

**Comment by zhenhu** [comment]
@kpedro88 premix library workflow injected
```
cmsDriver.py SingleNuE10_cfi  --conditions auto:phase1_2017_realistic --pileup_input das:/RelValMinBiasFS_13_UP17_ForMixing/CMSSW_10_2_8-102X_mc2017_realistic_v5_FastSim-v1/GEN-SIM-RECO --fast  --era Run2_2017_FastSim --eventcontent PREMIX --procModifiers premix_stage1 --relval 100000,500 -s GEN,SIM,RECOBEFMIX,DIGI,L1,DIGI2RAW --datatier GEN-SIM-DIGI-RAW --pileup AVE_50_BX_25ns --io FS_PREMIXUP17_PU50.io --python FS_PREMIXUP17_PU50.py
```
The output dataset name would be /RelValFS_PREMIXUP17_PU50/CMSSW_10_2_9-PU25ns_102X_mc2017_realistic_v5_FastSim-v1/GEN-SIM-DIGI-RAW

However, due to the computing issue reported in [JIRA4232](https://its.cern.ch/jira/browse/CMSCOMPPR-4232), all the relvals we submitted recently were stuck there. So we don't know when this file will be available.

**Comment by zhenhu** [comment]
Hi @kpedro88 , the premix library is ready
`/RelValFS_PREMIXUP17_PU50/CMSSW_10_2_9-PU25ns_102X_mc2017_realistic_v5_FastSim-v1/GEN-SIM-DIGI-RAW`
Could you please update the dataset name in this PR?

**Comment by kpedro88** [comment]
please test workflow 25400.17,250399.0,250400.17,250402.17,250405.17,250406.17,250407.17,250408.17,250409.17
thanks @zhenhu

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
