### PR TITLE
Implement HRRealTime for AArch64

### PR DESCRIPTION
**Pull request by davidlt**
We will be reading CNTVCT_EL0 (the virtual counter), which is prepared for us by OS.
The system counter sits outside multiprocessor in SOC and runs on a different frequency.
Increments at a fixed frequency, typically in the range 1-50MHz.
Applications can figure out system counter configuration via CNTFRQ_EL0.

Notice:
```
    Reads of CNTVCT_EL0 can occur speculatively and out of order relative to other
    instructions executed on the same PE.
    For example, if a read from memory is used to obtain a signal from another agent
    that indicates that CNTVCT_EL0 must be read, an ISB is used to ensure that the
    read of CNTVCT_EL0 occurs after the signal has been read from memory
```
More details:
```
    Chapter D6: The Generic Timer in AArch64 state
    ARM DDI 0487B.a, ID033117 (file: DDI0487B_a_armv8_arm.pdf)
```
This should resolve a failing HRTime_t unit test from FWCore/Utilities.

Signed-off-by: David Abdurachmanov <davidlt@cern.ch>

### CODE REVIEW

**Comment by davidlt** [comment]
please test

**Comment by Dr15Jones** [comment]
Nice!

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
