### PR TITLE
migrate PrimaryVertexMonitor to concurrent DQM

### PR DESCRIPTION
**Pull request by VinInn**
An exercise to see how complex it is.
Complex is, impossible not.
Having the "slave class" available in the constructor would save some copying around of config, tags and tokens.
Making stateless all DQM analyzers will be a challenge

### CODE REVIEW

**Comment by VinInn** [comment]
@fwyzard FYI

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@fioriNTU FYI

**Comment by fwyzard** [comment]
@VinInn do you think it would be easier to keep the module a "stream" EDAnalyzer, and just make the histograms global ?

**Comment by VinInn** [comment]
We need to see how the state is used in real cases.
I am sure "users" will prefer that and use your approach of simple forwarding all book&fill calls
prepending ```histograms.```
Maybe you can provide TWO different analyzerd if possible: one global and one stream...

**Comment by fwyzard** [comment]
I will have to think what happens to a stream module, when two streams are analyzing different runs...

**Comment by VinInn** [comment]
I checked Tracking DQM and most probably Global is ok.
I will try to use the same technique used here for
https://cmssdt.cern.ch/dxr/CMSSW/source/DQM/TrackingMonitor/interface/TrackingMonitor.h
that sports a highly distributed set of russian-doll classes each doing the whole construct/book/fill
business: 
much easier to keep it const asis and percolate tokens and configuration that trying to separate Monitor element from book&fill

**Comment by fwyzard** [comment]
OK... for reference, #21766 is an alternate implementation of this PR.
I make no claims to whether it is better or worse than this, it is just for reference.

**Comment by VinInn** [comment]
for this specific class  #21766 is most probably even easier to implement (and to maintain?).
Not sure for TrackingMonitor and its nested classes

**Comment by fwyzard** [comment]
@VinInn , in the end do you prefer this approach or the one in #21766 ?

**Comment by VinInn** [comment]
For this specific class I think does not matter much (once the migration is achieved)
I think the experience by Matti in #21764 is more relevant (and Matti went the  #21766 way)
We need to see what is better/easier in TrackingMonitor

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by VinInn** [comment]
superseeded by  #21766 ....
will close

**Pull request closed without merging**
