### PR TITLE
Cmssw 81 x sherpa weights

### PR DESCRIPTION
**Pull request by thuer**
Adding the possibility of additional weights (scale / pdf variation) for Sherpa 2.2. Sherpa stores the weighst in form of named weights which we do not do in CMSSW, so the relevant names are stored in GenLumiInfoHeader for further use.

### CODE REVIEW

**Comment by thuer** [comment]
any news on this pull request?

**Comment by covarell** [comment]
@bendavid is the new way of storing in line with what you had in mind?

**Comment by bendavid** [comment]
yes, looks ok.  @thuer I assume that there is also an appropriate name for the nominal weight stored as the first element in the weightNames?

**Comment by thuer** [comment]
The names given by sherpa are used, the nominal one would be just "Weight"

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by thuer** [comment]
@covarell is this needed for 8_0_X as well?

**Pull request merged**
