### PR TITLE
Fix memory leaks from EcalRecHitProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
valgrind found several memory leaks coming indirectly from EcalRecHitProducer

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try again to see if AddOn error was a fluke.

**Comment by Dr15Jones** [comment]
@cvuosalo I'll run valgrind on it to get to the bottom of the problem.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Valgrind found the bad interaction within ROOT. My change works around the problem.

**Comment by Dr15Jones** [comment]
ROOT is like the mythical hydra, cut off one bug and two more grow :(

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #16876 b4b504ffa994ef215ab0a5f6253fd888765eee6b

Fixing memory leaks by replacing bare pointers with unique_ptr in the EcalRecHitProducer. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-07-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
