### PR TITLE
move test_CreateFileLists test to CommonAlignment

### PR DESCRIPTION
**Pull request by smuzaffar**
As `tkal_create_file_lists.py` is part of `Alignment/CommonAlignment` package , so this PR proposes to move unit test ` test_CreateFileLists` in to  `Alignment/CommonAlignment` .

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cms-sw/alca-l2 , should I drop https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/scripts/mps_create_file_lists.py too ? This was previously used by `test_CreateFileLists` unit test . If nothing outside cmssw ising calling it then I suggest to drop it too?

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
> , should I drop https://github.com/cms-sw/cmssw/blob/master/Alignment/MillePedeAlignmentAlgorithm/scripts/mps_create_file_lists.py too ? This was previously used by test_CreateFileLists unit test . If nothing outside cmssw ising calling it then I suggest to drop it too?

Taking the liberty of tagging @connorpa @antoniovagnerini @consuegs (but I think it should be dropped)

**Comment by tvami** [comment]
type trk

**Comment by tvami** [comment]
@smuzaffar will you do the drop in this PR? I'll wait with signing this then

**Comment by smuzaffar** [comment]
please test

> @smuzaffar will you do the drop in this PR? I'll wait with signing this then

@tvami , I just have update this PR to drop [mps_create_file_lists.py](https://github.com/cms-sw/cmssw/pull/38296/commits/75b384a0a9319c4f415d3961ce5256bf0a9cdef1)

**Comment by tvami** [comment]
+alca
 * tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
