### PR TITLE
Split the dR plot for neutral hadrons in two eta ranges in the EB

### PR DESCRIPTION
**Pull request by nancymarinelli**
PR description:

Minor update in Validation/RecoEgamma/plugins/PhotonValidator.cc, .h. The plot in EB of dR between PF photon candidate and PF neutral hadron candidates is now split
in two |eta| regions (<1 and >1) mainly needed for Phase2, where |eta| >1 receives contributions from the HGCAL reco

This PR superseded #42009 which is now closed 

PR validation:
Test was made locally using the cmsDriver for PhaseI and PhaseII on the HggGluonfusion sample. All works fine
This PR needs to be backported to the 13_1_X series

### CODE REVIEW

**Comment by emanueleusai** [comment]
type egamma

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in DQM plots in EGammaV as expected from the content of the PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
