### PR TITLE
Fix error code on fallback file open error with test, 12_4_X backport

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Fix error code returned by cmsRun on a FallbackFileOpenError. There was a bug where it returns FileOpenError in the fallback case.

There is more discussion and more information related to this bug in issue https://github.com/cms-sw/cmssw/issues/42040. FYI @stlammel

Note that in original version of this PR there was a unit test included. We deleted the unit test in the 12_4_X backport only and plan to add it when the Rucio 12_4_X backport is completed. The unit test depends on the Rucio backport. 

#### PR validation:

Verified manually and with existing unit tests.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42249

**Comment by makortel** [comment]
No, wait ...

**Comment by makortel** [comment]
So the unit tests are strictly speaking incorrectly set up for 12_4_X (starting from setting `SITECONFIG_PATH`), because the Rucio catalog development has not yet been backported to 12_4_X (as noted in https://github.com/cms-sw/cmssw/issues/42040#issuecomment-1653691146). The fix itself is still correct.

Possible options forward
1. backport the Rucio catalog to 12_4_X
2. redo the tests with TFC (i.e. with `storage.xml`)
3. remove the tests from this backport, and rely on the tests in later releases

Since the Rucio catalog was planned to be backported to 12_4_X anyway, the option 2 feels like a wasted effort. Let's discuss more in #42040.

**Comment by wddgit** [comment]
We could just go ahead and merge this bug fix without the unit test. The backport to Rucio can continue independently.  The unit test isn't that important given the level of development occurring in 12_4_X and that the test is running in master already.

Also note that even though the current version of the unit test contains lines that are nonsensical for Trivial File Catalog, the log files show the test is actually verifying proper behavior. One file open attempt leads to FileOpenError and with two file open attempts there is a FallbackFileOpenError.

**Comment by makortel** [comment]
Hmm. I suppose the risk for the `site-local-config.xml` used in the IBs for not having fallbacks (that would cause the unit test to fail) would be tiny. Relying on the IB's `site-local-config.xml` would mean that the xrootd servers and redirectors would see file open attempts for nonexistent files. The number of such file open attempts should be fairly small (3 per IB flavor times 2 per day) though.

**Comment by makortel** [comment]
We decided to not include the unit tests in this PR. The tests will be backported as part of the Rucio catalog backport to 12_4_X, or soon afterwards.

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
Comparisons show https://github.com/cms-sw/cmssw/issues/39214, which is a known issue in this release cycle.

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
