### PR TITLE
Initializing members of reco::HLTTau

### PR DESCRIPTION
**Pull request by mrodozov**
Fix comp warning for gcc7 listed here
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_9_4_X_2017-09-27-2300/RecoTauTag/HLTProducers

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
ping cms-bot

**Comment by smuzaffar** [comment]
ping cms-bot

**Comment by perrotta** [comment]
+1
- Technical: fix comp warnings in gcc7 by initializing private parameters for all HLTTau(...) constructors
- Jenkins tests show no effect (none expected)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
