### PR TITLE
[Backport 14.0.X] backport customize BTVNano changes 

### PR DESCRIPTION
**Pull request by Ming-Yan**
#### PR description:

backport for customize btvnano https://github.com/cms-sw/cmssw/pull/43485

#### PR validation:

nano matrix

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport from CMSSW_14_1_X(master) for this changes https://github.com/cms-sw/cmssw/pull/43485

### CODE REVIEW

**Comment by jfernan2** [comment]
assign btv-pog

**Comment by jfernan2** [comment]
assign pf

**Comment by jfernan2** [comment]
enable nano

**Comment by vlimant** [comment]
as mentioned before, https://github.com/cms-sw/cmssw/pull/44587 is already taking care of `btagPNetCvNotB` which therefore has to be removed from here

**Comment by Ming-Yan** [comment]
> as mentioned before, #44587 is already taking care of `btagPNetCvNotB` which therefore has to be removed from here

Hi @vlimant thanks, indeed the commits here is exactly same( I did not see the differences from git diff for `PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py`) how can I fix it technically?

**Comment by Ming-Yan** [comment]
> as mentioned before, #44587 is already taking care of `btagPNetCvNotB` which therefore has to be removed from here

Hi @vlimant thanks, indeed the commits here is exactly same( I did not see the differences from git diff for `PhysicsTools/NanoAOD/python/jetsAK4_Puppi_cff.py`) how can I fix it technically?

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43485

**Comment by vlimant** [comment]
if you rebase to the latest 14.0.X IB, the change relative to `btagPNetCvNotB` will already be there and should not appear in the PR ; maybe this will all go away in conflict resolving

**Comment by jfernan2** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mondalspandan** [comment]
+1

**Comment by swagata87** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by hqucms** [comment]
@cms-sw/orp-l2 Could you please merge this so we can proceed with the integration of https://github.com/cms-sw/cmssw/pull/44660? Thanks!

**Comment by hqucms** [comment]
> > @cms-sw/orp-l2 Could you please merge this so we can proceed with the integration of #44660? Thanks!
> 
> @cms-sw/xpog-l2 @cms-sw/reconstruction-l2 @cms-sw/orp-l2
> 
> Please clarify the impact of the changes in this PR for RECO & MiniAOD (hopefully no impact). Thanks.

@antoniovilela This one has no impact on RECO & MiniAOD (& official NanoAOD) -- it only introduces a custom flavor of NanoAOD.

**Comment by mandrenguyen** [comment]
> > > @cms-sw/orp-l2 Could you please merge this so we can proceed with the integration of #44660? Thanks!
> > 
> > 
> > @cms-sw/xpog-l2 @cms-sw/reconstruction-l2 @cms-sw/orp-l2
> > Please clarify the impact of the changes in this PR for RECO & MiniAOD (hopefully no impact). Thanks.
> 
> @antoniovilela This one has no impact on RECO & MiniAOD (& official NanoAOD) -- it only introduces a custom flavor of NanoAOD.

+1 from reco

**Comment by rappoccio** [comment]
+1

**Pull request merged**
