### PR TITLE
Manage PluginFactory plugins with unique_ptr in FastSim

### PR DESCRIPTION
**Pull request by makortel**
Also always use the `unique_ptr` constructor. This PR is preparatory work to change the PluginFactory to return a `std::unique_ptr`.

Tested in CMSSW_10_5_X_2019-02-05-1100 , no changes expected.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

@ssekmen ping

**Comment by fabiocos** [comment]
@ssekmen do you have any comment? Or is it ok for you to go?

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
