### PR TITLE
DD Core Clean Up: Remove DDPartSelector

### PR DESCRIPTION
**Pull request by ianna**
* Remove unused class declarations

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna to be clear, this is unused and not affecting any existing functionality of DD, right?

**Comment by ianna** [comment]
@fabiocos - correct. Please, note, an early integration would help to speed up further cleanup needed in order to migrate to DD4Hep. Thanks.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
