### PR TITLE
DD4Hep: Update to the new DD4hep version

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* New API for an instance checks: ```isA``` checks is the Shape is an exact type, ```isInstance``` checks if the Shape is a derived type, ```instanceOf``` is deprecated
* Update tests reference
* Cleanup tests and test scripts

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@mrodozov - FYI

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/5285

**Comment by ianna** [comment]
I do not see what the error is, but it's unrelated to this PR:
```
===== Test "materialBudgetTrackerPlots" ====
+ VGEO_DIR=/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry
+ TEST_DIR=/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/materialBudgetTrackerPlots
+ '[' -d /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/materialBudgetTrackerPlots ']'
+ mkdir /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/materialBudgetTrackerPlots
+ cd /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/materialBudgetTrackerPlots
+ cmsRun /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/single_neutrino_cfg.py nEvents=1000
+ for geom in '{'\''Extended2015'\'','\''Extended2017Plan1'\''}'
+ cmsRun /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_DEVEL_X_2019-10-20-2300/src/Validation/Geometry/test/runP_Tracker_cfg.py geom=Extended2015 label=Tracker

---> test materialBudgetTrackerPlots had ERRORS

```

**Comment by smuzaffar** [comment]
@ianna, all look good. 
@fabiocos , this should go with cms-sw/cmsdist#5292

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
