### PR TITLE
Python3 syntax error cleanup

### PR DESCRIPTION
**Pull request by davidlange6**
remove fwk use of atoi (obsolete since python2.0 apparently..)
update more print statements
replace iteritems with six.iteritems

(all things identified by unit test errors in DEVEL build)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by Dr15Jones** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
