### PR TITLE
Forgot one file in PR #23751 (Update of Powheg gridpacks for GEN tests)

### PR DESCRIPTION
**Pull request by covarell**
Forgot one file in PR #23751, sorry

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test workflow 514.0, 517.0, 520.0, 524.0, 527.0, 530.0, 552.0, 554.0, 556.0

**Comment by fabiocos** [comment]
changes look unrelated to this PR

**Comment by fabiocos** [comment]
@covarell @efeyazgan @alberto-sanchez the output looks ok to me, I would say we can move forward with this PR

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
