### PR TITLE
(once again) adding cp5 for relvals

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by prebello** [comment]
+1

tests approved

**Comment by efeyazgan** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
please test workflow 555,515,521,527

randomly sampling the modified workflows

**Comment by fabiocos** [comment]
+1

**Pull request merged**
