### PR TITLE
Phase2-sim125 Try to address good cell definition for V17 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to address good cell definition for V17 version of HGCal Geometry. The valid function needs to be modified. The rest are tools for debugging and left for future fixes

#### PR validation:

Tested using the scripts in SimG4CMS/Calo/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test

Just to refresh the test.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
