### PR TITLE
Phase2-hcx251 Make the 2026D47 scenario work for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Making the scenario with HFnose working with dd4hep.

#### PR validation:

Validated with the cfg's in Geometry/CMSCommonData/test/dd4hep area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
