### PR TITLE
Remove all references to JetCrystalsAssociator

### PR DESCRIPTION
**Pull request by mrodozov**
Remove (unused?) class to move with gcc 7 and gcc 8 updates.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4699

**Comment by Dr15Jones** [comment]
If we are removing code, why does this need to be tested with an external change?

**Comment by Dr15Jones** [comment]
please test

**Comment by mrodozov** [comment]
> If we are removing code, why does this need to be tested with an external change?
It doesn't, but it was convenient to test the gcc cmsdist PR & this changes at once (we ended up removing this code because of the gcc PR).

**Comment by fabiocos** [comment]
the removed objects do not appear in any sequence, so I would say this PR should be safe.

**Comment by perrotta** [comment]
+1
- Removed objects are never accessed anywhere else in CMSSW, or in a sequence
- Jenkins tests pass

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
