### PR TITLE
Phase2-gex147 Correct the order of the xml files in defining a scenario - it is a must for dd4hep option

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the order of the xml files in defining a scenario - it is a must for dd4hep option

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Change is for DD4hep which does not show in PR test. Thing to be validate when Phase-2 DD4hep workflow will run.

**Comment by perrotta** [comment]
+1

**Pull request merged**
