### PR TITLE
bug fix for stage1 dqm

### PR DESCRIPTION
**Pull request by jingyucms**
1) change Stage1 Client histogram folder
2) make sure GMT fed will not be affected when swap GT fiber between stage1 and legacy
3) restrict layer2 to unpack only 1Bx for data emulator comparison

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
-1
this seems to be buggy
F.

**Comment by jingyucms** [comment]
@deguio Looks like it affects HLT. I will fix it. 
Cheers
Jingyu

**Comment by jingyucms** [comment]
please test

**Comment by deguio** [comment]
-1
rejecting for now. rebase needed.

**Comment by deguio** [comment]
the equivalent of this PR has been merged in 74 already

**Comment by davidlange6** [comment]
@jingyucms @deguio - is this PR obsolete now?

**Comment by jingyucms** [comment]
@davidlange6 @deguio The 74x version of this one is in the release already, so this one also needed to be in. Please Test.

**Comment by deguio** [comment]
@jingyucms you need to rebase. see my previous comment.
please rebase asap
thanks,
F.

**Comment by jingyucms** [comment]
Close

**Pull request closed without merging**
