### PR TITLE
HLT update for 25ns (75X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT update for 25ns (75X).
Based on 751.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need new GTs with L1T menu ```L1Menu_Collisions2015_25nsStage1_v4```

**Comment by Martin-Grunewald** [comment]
updated

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
please test
@cmsbuild why all this DAS errors?
Let's give a final push

**Comment by mmusich** [comment]
+1 
for https://github.com/cms-tsg-storm/cmssw/commit/b6d9dc3529a89285a012ed4ca071b0e1b5d2a5a3

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
