### PR TITLE
Fastsim: use fastsim era in global validation

### PR DESCRIPTION
**Pull request by lveldere**
- The fastsim era is used to apply fastsim mods to globalValidation_cff.py
- The fastsim era is used to apply fastsim mods to post validation
- Other validation sequences and the DQM sequence will follow

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

the only relevant changes are in the fastsim generator directory.
these changes are expected: this pr introduces proper post validation in this directory for fastsim.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12642	f055fe9
- changes in the code are in line with the description
- jenkins tests pass. In comparisons with the baseline there are no changes in reco  product quantities;  in the DQM plots, only in the /Generator/ directory  there are changes which look like just a removal of the relative normalization of the plots

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1
changes makes sense to me.

**Comment by lveldere** [comment]
operations, pdmv

Would you mind reviewing?
Please let me know if there are any comments or questions.

**Comment by srimanob** [comment]
+1 
For PdmV, only change in havesting step.

**Comment by acaudron** [comment]
@lveldere
Sorry to arrive late on this but we realised (thanks to @swertz @pablodecm) one thing recently due to this PR: in the relval validation for the b-tagging plots, some of them disappear for fastsim. This due to the fact we are not running exactly the same sequence on fast and fullsim as some plots for fullsim are produced by the DQMOffline sequence. In fastsim we modified the sequence to also produced these plots as the DQMOffline one is not ran.

Basically you removed this sequence:
https://github.com/cms-sw/cmssw/pull/12642/files#diff-2a5bcde0d120eb3959a5690f13018de7L42
and then you did this change:
https://github.com/cms-sw/cmssw/pull/12642/files#diff-280a22a34e1b642031a67e76fefd1e28R96
which implies now the sequence is the same for full and fastsim for b-tagging as now it will take for fastsim:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Validation/Configuration/python/globalValidation_cff.py#L89

So basically in your "if" for FastSim you need to have a replace (or a remove and add) to run the proper b-tagging validation sequence. We have a similar issue for the postvalidation sequence due to this change:
https://github.com/cms-sw/cmssw/pull/12642/files#diff-819af2ec677272fddf1fef50e788a88bR1242

So basically, we would appreciate if it can be fixed soon. Let say that there are not the most important plots but we would still appreciate to be able to monitor them.

Thanks

**Comment by lveldere** [comment]
Hi Adrien

Thanks for reporting.
Now it makes sense.
I'll look into it next week.

Cheers

Lukas

**Comment by lveldere** [comment]
HI Adrien

Can you point me to the FullSim configuration for b-tag DQM?
In which path is it run?

- VALIDATION:@standardValidation
- VALIDATION:@miniAODValidation
- DQM:@standardDQM
- DQM:@miniAODDQM

At the moment FastSim runs a version of VALIDATION:@standardValidation
and soon FastSim will run a modified version of DQM:@standardDQM

Thanks

Lukas

On Fri, Feb 26, 2016 at 5:16 PM, Lukas Vanelderen <lukasvanelderen@gmail.com

**Pull request merged**
