### PR TITLE
avoid having axis resized for LogMessageMonitor

### PR DESCRIPTION
**Pull request by deguio**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by nclopezo** [comment]
Hi @deguio, 
This PR caused [compilation errors](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_4_ROOT5_X_2015-04-23-2300/DQM/TrackingMonitor) in [CMSSW_7_4_ROOT5_X](https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_4_ROOT5_X), should I just revert it from the CMSSW_7_4_ROOT5_X branch?

**Comment by deguio** [comment]
ciao @nclopezo 
yes, this is for root6 only.

**Pull request merged**
