### PR TITLE
Run4-hgx278 Correct material budget plot for V14

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct material budget plot for V14 geometry of HGCal - absorber structure at lower R

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Are the differences in the Phase 2 workflows expected?

**Comment by bsunanda** [comment]
Yes they are expected. A bug fix affects the simulation flows

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda 
Would you mind specifying which plots that show the difference as expected? Just to complete the document of this PR. Thanks.

**Comment by bsunanda** [comment]
When we modify absorber structures in geometry, all results will be affected. These will affect mostly the hadronic sections of HGCal. When geometry is changed, random # sequence is modified and this affects everything

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
