### PR TITLE
DQM TrackerMonitorTrack improvements (80X version)

### PR DESCRIPTION
**Pull request by schneiml**
This PR adds a number of changes on top of #13240. See also #13393
- Location and naming of the residual histograms for SiPixel is improved
- Cuts on pT and dxy significance are applied for all residuals. Such cuts were missing in the original SiStrip version. The histograms are now closer to the old SiPixel residuals histograms.
- The source code now compiles into two modules to keep the configrations of SiPixel and SiStrip independent.
- Some other cleanup.

These changes affect the configuration options for the TrackMonitorTrack module. I updated the config files as far as I could follow; however, the new SiPixelMonitorTrackResiduals might be added in more places. Also, some files use options that were probably broken before, i did not touch these.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 
for https://github.com/schneiml/cmssw/commit/9bca63f06fd2543651d9920a7095acfc6ed414f4
changes in AlCa package (`Alignment/OfflineValidation`) are in line with code description:
   * remove unnecessary interface `fillHitQuantities` from `Alignment/OfflineValidation/interface/TrackerValidationVariables.h`
   * added filter functionality in `fillTrackQuantities` method of same class, to allow cuts on pT and dxy significance. Filter is always passed when running the standalone Tracker Alignment offline validation suite.

**Comment by deguio** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
