### PR TITLE
SiStripDAQPopCon.py: improve readability of output

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Improve readability of output by converting returned stdout/stderr content from bytes. See [this log file](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_2_ASAN_X_2021-11-08-2300/unitTestLogs/CondTools/SiStrip#/17) for example of why this is needed.

### CODE REVIEW

**Comment by iarspider** [comment]
assign db

**Comment by ggovi** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by tvami** [comment]
+db
 * unit tests look much nicer now: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-35d347/20403/unitTests/src/CondTools/SiStrip/test/SiStripDAQ_O2O_test/testing.log

**Comment by perrotta** [comment]
+1

**Pull request merged**
