### PR TITLE
Instrument cmssw for nvidia nvprof/nvvm (10.0.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Instrument cmssw for nvprof/nvvm
  - implement a Service to provide CMSSW-aware annotations to nvprof/nvvm
  - highlight selected modules and delayed modules
  - update for CMSSW 10.0.x

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #21946

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@fwyzard is this really needed in 10_0_X as well, or it is enough to integrate it in the development release?

**Comment by fwyzard** [comment]
I would rather have it in10.0.x as well, since this is the base release we are currently using for the GPU development, and because it can be used for profiling non-GPU modules as well.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
