### PR TITLE
New GT with PF hadron calibration.

### PR DESCRIPTION
**Pull request by diguida**
PF hadron calibration computed on top of the changes in HCAL digitisation and  time slew model is added to all scenarios.

### CODE REVIEW

**Comment by mmusich** [comment]
please test
should work out-of-the-box

**Comment by diguida** [comment]
@slava77 this is the "minimal" set of GT with only the new PF Calibration.

**Comment by davidlange6** [comment]
merging - please comment on any issues in parallel with the IB!. Thanks

**Comment by slava77** [comment]
The subject of the PR may be a bit misleading.
"PF hadron calibration computed on top of the changes in HCAL method3 with time slew model"
- method 3 is not used to reconstruct energies in reco. So, it's just the slewing and other digitization changes.

**Comment by diguida** [comment]
@slava77 thanks for your comment: I wrote it in a rush.
I have just changed it to: PF hadron calibration computed on top of the changes in HCAL digitisation and  time slew model is added to all scenarios.

Is it ok?

**Comment by diguida** [comment]
@davidlange6 @slava77 @mmusich 
Good news: the latest IB https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_6_X_2015-10-08-2300 containing this set of GT and (since the previous https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_6_X_2015-10-08-1100) #11684 fixes the problem with JEC. There is still two unit test failures as in https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc493/www/thu/7.6-thu-23/CMSSW_7_6_X_2015-10-08-2300

**Comment by diguida** [comment]
@ggovi one of the unit test failures in the latest IB is related to the missing key for accessing ORACLE in read-only mode:https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc493/CMSSW_7_6_X_2015-10-08-2300/unitTestLogs/CondCore/DBCommon

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
To clarify more. The test errors in this PR are due to the fact that the IB used as baseline for tests here https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_6_X_2015-10-07-2300 does not contain the `TMath` fix in #11684: this latter PR entered https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_7_6_X_2015-10-08-1100

**Comment by ggovi** [comment]
@diguida 
Probably related to expired afs token... Any action required on this?

**Comment by slava77** [comment]
On 10/9/15 3:19 AM, Salvatore Di Guida wrote:
> @slava77 <https://github.com/slava77> thanks for your comment: I wrote
> it in a rush.
> I have just changed it to: PF hadron calibration computed on top of the
> changes in HCAL digitisation and time slew model is added to all scenarios.
> 
> Is it ok?


Thank you. It looks more clear now.

**Comment by diguida** [comment]
@ggovi I could not reproduce it, so I think it is an issue with afs...
Thanks for your check.

**Pull request merged**
