### PR TITLE
fastsim: use fastsim era to define fastsim customs to mixing

### PR DESCRIPTION
**Pull request by lveldere**
Transforming a fullsim configuration for MixingModule to a fastsim configuration, now happens via the fastsim era, rather than a hidden cmsDriver option.

This approach is probably a bit more robust.
If implemented earlier it would have avoided occasions of the past where FastSim did not pick up changes to the fullsim mixing configuration.

Along the way I removed some code duplication in the standard fullsim mixing configuration files.

@mdhildreth 
Could you let me know whether this needs discussion?

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by mdhildreth** [comment]
should be ok...

**Comment by mdhildreth** [comment]
+1

**Pull request merged**
