### PR TITLE
Prepare for concurrent IOVs, miscellaneous packages

### PR DESCRIPTION
**Pull request by wddgit**
Change the return type of produce functions of ESProducers
from shared_ptr to unique_ptr.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by wddgit** [comment]
please test

Try the tests again. The failure looks unrelated to my changes. The seg fault is in reco::parser code which seems to be unrelated to my work. But in the IBs this test is passing. There are some slightly troubling warning messages in the log that almost made me suspect my code, but then I noticed those warnings are in the IB logs already ... FYI @Dr15Jones

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24953	077156f 
- mostly technical; in line with the PR description
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

technical code cleaning

**Pull request merged**
