### PR TITLE
Cleaning matrix75 x

### PR DESCRIPTION
**Pull request by boudoul**
- this is intended to synchronize 75X and 76X for runthematrix
- It includes the changes from @franzoni for run2 data + factorizing relval_step( MatrixUtil.py)
- It includes changes from @davidlange6 for unschedule (superseeding PR #10503 )
- It includes changes from @franzoni : removing miniaod step
- It removes the option magfield added by mistake by @srimanob

Some check should be further done with the baseDataSetRelease but testing already as it is now
the jsonfile2015 should also be fixed

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
the error is 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10558/6937/runTheMatrix-results/matrixTests.log

ERROR importing file  relval_standard No module named golden_json_2015

**Comment by boudoul** [comment]
Thanks @davidlange6 I will fix this (I miss one commit from DPGAnalysis , I will update my branch )

**Comment by boudoul** [comment]
@cmsbuild ,  please test

**Comment by boudoul** [comment]
grr... I though I fixed this, will look

**Comment by boudoul** [comment]
please test

**Comment by boudoul** [comment]
workflows[1355] duplication removed, adding the HI workflows in baseDataSetRelease as discussed with @srimanob

**Comment by boudoul** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
Please test

**Comment by boudoul** [comment]
+1

**Pull request merged**
