### PR TITLE
BeamSpotProducer transtion to Minuit2

### PR DESCRIPTION
**Pull request by menasce**
RecoVertex/BeamSpotProducer: 
Certified transition from TVirtualFitter interface to Minuit2 for 3d beam spot fit. The fit now converges as used to in the old implementation.

People involved: @diguida and @mmusich

### CODE REVIEW

**Comment by slava77** [comment]
git says there is a merge conflict here

**Comment by mmusich** [comment]
@menasce please rebase

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8384	5261a85
the same (relevant) code changes as in #8385

jenkins test run and show differences in expected places:
-  the log messages no longer contain %MSG-e NoBeamSpotFit: AlcaBeamMonitor:AlcaBeamMonitor@endLumi
- in DQM histograms related to beam spot monitoring, as expected (in AlcaBeamMonitor) with values that indicate a working fit

**Comment by diguida** [comment]
@slava77 
Sorry for the dummy question.
Concerning the DQM histograms, I was giving a look to wf 1000.0 and 1001.0, where I see this AlCa producer is run.
For 1000.0 I can see the file with plot comparison [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_5_X_2015-03-18-2300+8384/2495/alternative-comparisons/). For 1001.0 I should look at the DQM file itself, in folder AlCaBeamMonitor.
Is this correct?

**Comment by slava77** [comment]
Hi Salvatore,
indeed, the 1001 apparently has no RelMon or "alternative-comparisons" file.
The DQM file is available in the matrix outputs and can be pulled in and compared manually, I suppose.

**Comment by diguida** [comment]
+1

**Comment by diguida** [comment]
@slava77 
Thanks for the pointer. See some plots:
4.53 2012B Photon PD
screen shot 2015-03-20 at 15 33 29
1000.0 2011A MinBias
screen shot 2015-03-20 at 15 37 21

**Comment by davidlange6** [comment]
+1

**Pull request merged**
