### PR TITLE
Phase2-hgx338A First step to introduce calibration cells for HGCAL silicon sensors

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The first step to introduce calibration cells for HGCAL silicon sensors

#### PR validation:

Tested by running the parameter analyzer for different versions of HGCal

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this. we need this for the next update

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
