### PR TITLE
Fastsim: HF: use shower library also for run1

### PR DESCRIPTION
**Pull request by lveldere**
rebase of #11674

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by lveldere** [comment]
thanks @smuzaffar

**Comment by lveldere** [comment]
+1

changes in workflow 5.1 expected (HF model and sim particle selection have changed for run1)
no changes in workflow 135.4, as expected (changes do not affect run2 era)

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
