### PR TITLE
Phase2-hgx265 Attempt to make CMSSW geometry compatible with flat geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Attempt to make CMSSW geometry compatible with flat geometry

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda I'm surprised to see a large amount of comparison changes in D49. Is this expected?

**Comment by bsunanda** [comment]
We expect differences from earlier version even for D49 - there were bugs which computed the inner radii of last layers of HGCal-EE. So all versions with HGCal will be affected.

**Comment by kpedro88** [comment]
What is the effect on D49 physics performance?

**Comment by bsunanda** [comment]
Most likely it will be enhanced. There were missing cells in the earlier version in the last 2 layers of EE section. But it would not affect too much.

**Comment by kpedro88** [comment]
It would be good to confirm this as part of validating the PR.

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda just to be clear, I'm waiting to see some physics validation before signing this PR.

**Comment by bsunanda** [comment]
c_RZ_AllDetectorsSimHitD49New
c_RZ_AllDetectorsSimHitD49Old
c_E_AllDetectorsSimHitD49New
c_E_AllDetectorsSimHitD49Old

I attach 4 files here. First 2 are R-Z plots of all SimHits for 2026D49 scenario for the corrected (New) and the earlier version (Old). One can see that for last 2 layers of EE (around Z = 3600 mm) the occupancy in the new plots go down to lower values and number of entries have increased for same number of t-tbar events

The other 2 plots are energy deposits in all detectors. There is no significant difference with a slight increase in mean for the new plots. 

Bothe observations are expected from the fix in the geometry.

**Comment by bsunanda** [comment]
@kpedro88 I also have plots from the DIGI and RECHit level. They bear similar conclusions. Can you now sign off the PR?

**Comment by bsunanda** [comment]
@kpedro88 @silviodonato Can you approve this PR and get it integrated? I need that for a followup PR

**Comment by kpedro88** [comment]
+upgrade
@bsunanda thanks for the validation plots

**Comment by qliphy** [comment]
+1

**Pull request merged**
