### PR TITLE
ME1a CLCT will use ME1a SimHit Strip and be saved into ME1a plot

### PR DESCRIPTION
**Pull request by sifuluo**
#### PR description:
Trying to fix the comparison failures mentioned: https://github.com/cms-sw/cmssw/issues/37268

### CODE REVIEW

**Comment by perrotta** [comment]
Thank you @sifuluo!

As additional (unrelated but welcome) cleaning, could you also please:
- Remove from CSCStubResolutionValidation.h the following unused class members:
  - `inputTag_`
  - `simTrackMinPt_` , `simTrackMinEta_` , `imTrackMaxEta_`
- Replace in CSCStubResolutionValidation.h the line
```
   ~CSCStubResolutionValidation() override;
```
with
```
   ~CSCStubResolutionValidation() override = default;
```
and remove the doing-nothing destructor from  CSCStubResolutionValidation.cc

**Comment by sifuluo** [comment]
Either/both the changes to the destructor will fail the compiling.
So I only removed the unused class members

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Indeed: bot seems stuck
@smuzaffar do you have any hint?

**Comment by smuzaffar** [comment]
humm, strange , I am am checking

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
code-checks

**Comment by smuzaffar** [comment]
looks like github is coming back, bot has reacted and started the test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@sifuluo please create backports of this PR to propagate the fix
Thanks

**Comment by perrotta** [comment]
+1

**Pull request merged**
