### PR TITLE
CSC RU segment algorithm tuned for ME0

### PR DESCRIPTION
**Pull request by nickmccoll**
Translated CSC RU algorithm (https://indico.cern.ch/event/578871/contributions/2345178/attachments/1358089/2053858/16_10_19-Voytishin_Palichik-CSCSegBuilderCSCWeekly.pdf) for use in ME0. It is not a direct port as some of the assumptions made for the CSC do not apply to ME0. It is now set as the default. Also updated standard segment algorithm to use the chamber as the coordinate reference frame. 

Right now the default cfg parameters are for a 10 eta partition geometry and 768 strips...this will change once the geometry is finalized.

### CODE REVIEW

**Comment by slava77** [comment]
what are the common parts of ME0SegAlgoRU with the CSC version?
common parts or parts different in some magic numbers constants should be the same code with different parameter calls.
Please provide some analysis for this.

It looks like the default me0Segments are changed: please provide a link to some slides summarizing physics performance changes. (was it in UPSG a week ago?)

Please provide timing for events with PU200
and check a memory profile on ~1K 10mu events.
I suppose, both can be checked using just the ME0 local reco.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
assign upgrade

**Comment by nickmccoll** [comment]
Hi @slava77,

"what are the common parts of ME0SegAlgoRU with the CSC version?"
The two implementations share no common code. I had to completely re-work the ME0 version in order to get the ME0 specific changes in. 

"It looks like the default me0Segments are changed: please provide a link to some slides summarizing physics performance changes. (was it in UPSG a week ago?)"
Yes that is correct, please find them here: https://indico.cern.ch/event/615597/contributions/2483219/attachments/1416650/2169216/nmccoll_2_22_17_UPSGME0.pdf

Note, that the results with this geometry will be a little different from the ones shown here. To attain the same results the final ME0 geometry with the needed number of strips and eta partitions will have to be integrated.

"Please provide timing for events with PU200
and check a memory profile on ~1K 10mu events.
I suppose, both can be checked using just the ME0 local reco."

Do I follow these instructions to get the correct results?
https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#pp_MC_Benchmark_setup_for_timing

Thanks!
Nick

**Comment by slava77** [comment]
On 3/1/17 6:19 PM, Nick McColl wrote:
> "Please provide timing for events with PU200
> and check a memory profile on ~1K 10mu events.
> I suppose, both can be checked using just the ME0 local reco."
> 
> Do I follow these instructions to get the correct results?
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#pp_MC_Benchmark_setup_for_timing
> 

yes
sort of (most of the cmsDriver and input .root file is to be picked
based on a relevant phase-2 workflow)

The time and memory details can be enabled with
--customise Validation/Performance/TimeMemoryInfo.py

**Comment by slava77** [comment]
-1

superseded by #17687; to move to 91X

**Pull request closed without merging**
