### PR TITLE
No longer use TrackAssociatorByChi2 to get dca to beam spot

### PR DESCRIPTION
**Pull request by Dr15Jones**
Moved the calculation of tracking parameters at the closest approach
to the beam spot to a stand alone function. This allows TrackAssociatorByChi2
and the VertexFitterResult to share the code with the minimum amount of
coupling.

This is the first step to fixing the consumes problem with TrackAssociators.

### CODE REVIEW

**Comment by ktf** [comment]
please test

**Comment by Dr15Jones** [comment]
@cmsbuild please notice the update and retest

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7036	 ffb97c4

based on jenkins: no differences in 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-01-03-1400+7036/5436/validateJR/
or 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-01-03-1400+7036/5436/alternative-comparisons/ (after stripping the timer data).

@nclopezo @ktf 
Giulio and David, I'm puzzled by the available set of matrix results:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7036/1737/runTheMatrix-results/ has more tests running than 
what shows up in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-01-03-1400+7036/5436/
However, all of the tests running are appearing in the validateJR 

The list of tests is supposedly generated here
https://github.com/cms-sw/cms-bot/blob/29090789fdf4cf320be62bc822e8054856eaceb1/run-ib-comparison-baseline#L13
but the actual list is longer (e.g. 25202 is not in -s)

**Comment by davidlange6** [comment]
AlCa changes are trivial - so will bypass. Complain if not ok.

**Pull request merged**
