### PR TITLE
Run3-gex91 Backport all xml related changes for CMS geometry in 12_1_X

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport all xml related changes for CMS geometry in 12_1_X

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

These are back ports from many PR's which have all been merged with the master sometime ago

### CODE REVIEW

**Comment by AdrianoDee** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Could you please document in this thread the plan for this backport? I missed the discussion, and it would be good to have the plan documented. If the XML is changed, do we really want to create new DB payloads for DDD still in 12_0?

**Comment by bsunanda** [comment]
During the O&C meeting, it was pointed out that the geometry definition in 12_0 should be final and only from 12_0 to 12_1 the default will move from ddd to dd4hep. To have identical geometry, we need to backport all xml files to 12_0. We also will move the changes due to dd4hep once we find dd4hep works fine in the xml and in the DB version in 12_1. This needs the treatment of rotation matrices (in the code which makes the big xml file) corrected. Also the precision of at least the rotation matrices need to be made identical for dd4hep wrt ddd.

**Comment by bsunanda** [comment]
@civanch @cvuosalo @srimanob I wonder why you are not signing this PR

**Comment by srimanob** [comment]
Hi @bsunanda 

I was looking into this PR, but I am not sure how this PR is prepared without https://github.com/cms-sw/cmssw/pull/35152
There is a part of that PR to migrate generateGeometry script to python3. Without it, how can you generate i.e. Geometry/CMSCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py
automatically. 12_0 moved to Python3 since 12_0_0_pre5.

**Comment by bsunanda** [comment]
Closing in favor of #35169

**Pull request closed without merging**
