### PR TITLE
ECAL : SRP and TPG tools

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:

Bug correction in EcalSRPHandler.cc and EcalTPGParamBuilder.cc, py to display SRP conditions, remove CondDBCommon in Align py files

#### PR validation:

All  cmsRun ..py files give foreseen results.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by rekovic** [comment]
@depasse 
Change in the `EcalTPGParamBuilder.cc` is expected to have effect on ECAL TPs?  
However, I see almost no failure in test DQM report 
```
DQMHistoTests: Total histograms compared: 2939508
DQMHistoTests: Total failures: 1
DQMHistoTests: Total nulls: 0
``` 

Can you elaborate, please.  Thx.

**Comment by depasse** [comment]
Yes,

there was 1 offending line:
https://github.com/cms-sw/cmssw/blob/master/CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc#L2612

should have subdetId()==2 for Ecal EndCaps  rather than subdetId()==1 (Ecal Barrel).

Either, TPG for EE considered always LaserAlphas = 1, that is wrong.

________________________________

**Comment by fabiocos** [comment]
@rekovic @benkrikler so do we have any conclusion?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
