### PR TITLE
[12_0_X] TkDQM: Fix tracker maps for run3

### LINKED ISSUE #34607: TrackerMap script not working in CMSSW_11_3_2
Tracker DQM uses a standalone [script](https://github.com/cms-sw/cmssw/blob/master/DQM/SiStripMonitorClient/test/SiStripDQM_OfflineTkMap_Template_cfg_DB.py) to produce 2-Dimensional  plots of various monitored quantities. Example of TkMaps for a run taken in 2018([link](https://tkmaps.web.cern.ch/tkmaps/files/data/users/event_display/Data2018/Beam/321/321122/ZeroBias/)). The script in turn runs the ```SiStripOfflineDQM``` module. The script takes as input legacy ```TDirectory``` based ```DQM_*.root```  file. 

Currently the script is crashing in ```CMSSW_11_3_2``` when we try to run it for producing the maps for the CRUZET runs. 
 It crashes from line [205](https://github.com/cms-sw/cmssw/blob/master/DQM/SiStripMonitorClient/plugins/SiStripOfflineDQM.cc#L205) which is calling the ```DQMStore::open``` [function](https://github.com/cms-sw/cmssw/blob/master/DQMServices/Core/src/DQMStore.cc#L790). The crash comes from this [line](https://github.com/cms-sw/cmssw/blob/master/DQMServices/Core/src/DQMStore.cc#L796). From my understanding, the support to read ```TDirectory``` based ROOT files were dropped in this PR #[28622](https://github.com/cms-sw/cmssw/pull/28622). 
 
 To solve the issue, I tried implementing a function to read the contents of the ```TDirectory``` based ROOT file with the LegacyIOhelper class, but not all maps are being filled correctly. I am still investigating. Can the DQM experts give some suggestions? 
 @arossi83 @mmusich @tsusa

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Fix to tracker map creation script.  Adds a unit test for offline Tkmap creation.

#### if this PR is a backport please specify the original PR and why you need to backport that PR: 
Backport of #34966. Resolves #34607.

### CODE REVIEW

**Comment by sroychow** [comment]
type bug-fix

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
backport of #34966

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
