### PR TITLE
Split testConfigDP into smaller parts

### LINKED ISSUE #42747: [PPC64] TestConfigDP times out
Recent occurrences: [1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-04-2300/unitTestLogs/Configuration/DataProcessing#/1357-1357), [2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Configuration/DataProcessing#/1167-1167), [3](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-06-2300/unitTestLogs/Configuration/DataProcessing#/803-803), [4](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-07-2300/unitTestLogs/Configuration/DataProcessing#/1164-1164), [5](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-08-2300/unitTestLogs/Configuration/DataProcessing#/1415-1415). First failure seem to be on 2023-08-23

The point at which the unit test fails seems random.

### PR DESCRIPTION
**Pull request by iarspider**
Resolves https://github.com/cms-sw/cmssw/issues/42747

#### PR description:

testConfigDP frequently times out in PowerPC IBs. This PR, following suggestion in #42747, splits it into multiple smaller tests. 

The splitting is arbitrary, I'm open to suggestions of different ways to split (and definitely open to suggestions of better test names). 

#### PR validation:

Bot tests.

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc12

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc12

**Comment by rappoccio** [comment]
+1

**Pull request merged**
