### PR TITLE
Migrate FastSimulation modules to use esConsumes

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Migrate FastSimulation modules to use esConsumes

#### PR validation:

Depends on existing tests

### CODE REVIEW

**Comment by makortel** [comment]
@cms-sw/fastsim-l2 Could you review and sign, please?

**Comment by makortel** [comment]
@cms-sw/fastsim-l2 Could you review and sign, please?

**Comment by makortel** [comment]
ping @cms-sw/fastsim-l2

**Comment by makortel** [comment]
@cms-sw/fastsim-l2 Could you please review and sign? This PR has been open now for two weeks now without any action. Getting these EventSetup-consumes migration PRs merged would help us a lot. Thanks!

**Comment by perrotta** [comment]
> @cms-sw/fastsim-l2 Could you please review and sign? This PR has been open now for two weeks now without any action. Getting these EventSetup-consumes migration PRs merged would help us a lot. Thanks!

@civanch @lveldere @mdhildreth @sbein @ssekmen : if any of you is not supposed any more to take care of fastsim related pull requests, please remove yourself from https://github.com/cms-sw/cms-bot/blob/master/categories.py
Otherwise, could you please review this and the other longstanding pull requests with a `fastsim-pending` label?

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
According to the static analyzer, there are still several `EventSetupRecord::get` function called in FamosManager, FamosProducer, as well as in other FastSim plugins not touched by this PR.

Is there any reason why the migration was not completed, at least in these already touched files? For them up to now only the ConsumesCollector is passed as argument, but nothing has been migrated.

What is the plan?

**Comment by makortel** [comment]
As far as I can tell, `FamosManager` is used only by `FamosProducer`, and `FamosProducer` is not being run in IBs (with `git grep` I see `FamosProducer` being used only in `FastSimulation/EventProducer/python/FamosSimHits_cff.py` that itself is not imported anywhere). I'd prefer the maintainers (@cms-sw/fastsim-l2) to take care of migrating such code, or removing it if is not needed anymore.

**Comment by perrotta** [comment]
> As far as I can tell, `FamosManager` is used only by `FamosProducer`, and `FamosProducer` is not being run in IBs (with `git grep` I see `FamosProducer` being used only in `FastSimulation/EventProducer/python/FamosSimHits_cff.py` that itself is not imported anywhere). I'd prefer the maintainers (@cms-sw/fastsim-l2) to take care of migrating such code, or removing it if is not needed anymore.

Ok for the partial migration now
@cms-sw/fastsim-l2 please have a look at the modules listed in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-613210/18106/llvm-analysis/esrget-sa.txt [1] and either remove them or finalize their migration to esConsumes

[1]  For the record:
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:101:3: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<GeometricSearchTracker> >' with argument of type 'const std::string' with argument of type 'edm::ESHandle<GeometricSearchTracker>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:105:3: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<TrackerInteractionGeometry> >' with argument of type 'const std::string' with argument of type 'edm::ESHandle<TrackerInteractionGeometry>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:111:5: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<MagneticFieldMap> >' with argument of type 'const std::string' with argument of type 'edm::ESHandle<MagneticFieldMap>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:126:5: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<CaloGeometry> >' with argument of type 'edm::ESHandle<CaloGeometry>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:130:5: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<CaloTopology> >' with argument of type 'edm::ESHandle<CaloTopology>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:94:3: warning: function 'FamosManager::setupGeometryAndField' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<TrackerGeometry> >' with argument of type 'const std::string' with argument of type 'edm::ESHandle<TrackerGeometry>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-27-1100/src/FastSimulation/EventProducer/src/FamosProducer.cc:68:3: warning: function 'FamosProducer::produce' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<TrackerTopology> >' with argument of type 'edm::ESHandle<TrackerTopology>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]
```

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
Issue #35243 have been opened to keep track of the still missing migrations

**Pull request merged**
