### PR TITLE
Revert #19250

### PR DESCRIPTION
**Pull request by fwyzard**
The changes proposed in #19250 were clearly never tested, and lead to crashes in the DQM and Harvesting steps.

They should be reverted.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by slava77** [comment]
quite likely this PR is now generating about 5K differences due to NaNs in DQM plots.
The discrepancy showed up between CMSSW_9_3_X_2017-07-26-2300 (not present yet) and CMSSW_9_3_X_2017-07-27-2300 (and is still present in 07-31-1200).
Here is an example from an unrelated PR test
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-07-31-1200+19853/21669/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HLT.html

**Comment by mtosi** [comment]
I'm a little bit confused :(
this PR touches only a subset of histograms
while the NaNs pointed out by your relmon are in totally unrelated
directories !
I do not understand :(

  mia

**Comment by fwyzard** [comment]
Why would reverting a PR cause issues that weren't there before ?

.A

**Comment by davidlange6** [comment]
maybe more likely its due to #19933 - i see now a protection against a denominator being 0 was removed.

**Comment by fwyzard** [comment]
ah, I see what you mean - I checked the protection for the TClopperPearson but not for the division.
I can make an update tomorrow.

**Pull request merged**
