### PR TITLE
Write a JSON file with the resource usage for each module

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Write a JSON file with the detailed resource usage for each module:
  - real (wall clock) time,
  - CPU time,
 - allocated and de-allocated memory.

The JSON file is created at the end of the job, so it should have no impact on the performance; it is also disabled by default.

Most of the machinery is in place (commented out) for creating files for each event, lumisection, and/or run.

Note: this implementation uses [Niels Lohmann's JSON for Modern C++](https://github.com/nlohmann/json) header-only library .

#### PR validation:

The HLT menu runs and produces the `resources.json` file.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test with cmsdist#5641

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5641

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5641

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5641

**Comment by fwyzard** [comment]
@Martin-Grunewald do you prefer to review this (once the external has been made available), or are you OK if I "sign" this for HLT ?

**Comment by silviodonato** [comment]
please test
(cms-sw/cmsdist#5641 has been merged)

**Comment by fwyzard** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
