### PR TITLE
MiniAOD b-tag tweaks

### PR DESCRIPTION
**Pull request by ferencek**
This PR introduces the following changes:
- adds b-tag discriminators to AK8 jets (the set of discriminators kept in sync with the PAT jet defaults)
- updates subjet b-tag discriminators from CSV+AVR to CSVv2+AVR
- removes b tagging from CMSTopTag fat jets (no need to run it since these jets are not stored in MiniAOD anyways)
- puts SoftDrop subjets in front of CMSTopTag subjets (this is important to correctly store the AK8 jet daughters since the CMSTopTag subjets are derived from CA8 jets and could in principle contains extra constituents not clustered inside AK8 jets. SoftDrop subjets are derived from AK8 jets).
- fixes minor inconsistencies in TopTagInfo handling

Observed increase in the event size is at sub-per-mille level (tested on 9k events from /RelValProdTTbar_13/CMSSW_7_4_0_pre8-MCRUN2_74_V7-v1/AODSIM).

@gpetruc @arizzi @rappoccio @dmajumder

### CODE REVIEW

**Comment by arizzi** [comment]
@ferencek is there a twin PR on 75X?

**Comment by ferencek** [comment]
@arizzi, I first wanted this to be reviewed and tested for 74X. Also, the policy on automatic vs manual forward porting is a bit confusing so I did not want to rush with a 75X PR. If and when needed, a 75X PR will be created.

**Comment by ferencek** [comment]
Just a general comment. The way we handle AK8 daughters at the moment is a but fragile. If somebody in the future reverses the order of subjet collections or adds a new one in front, things might not work as intended. Should there be a comment left in the cfg file?

**Comment by rappoccio** [comment]
@ferencek yes, that would definitely help.

**Comment by gpetruc** [comment]
Ah, ok, now I understand... indeed we assume that the subjets only contain
candidates from the original jets.

A protection could be to change these lines

https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/PhysicsTools/PatUtils/plugins/JetSubstructurePacker.cc#L77-L78
so that if a subjet has a daughter that is not  also daughter of the AK8
then the subjet is not added as daughter and its daughters are not marked
as already added.

    Giovanni

**Comment by ferencek** [comment]
@gpetruc, this is in principle OK from the point of view of ensuring that AK8 daughters are all stored correctly but this is not necessarily optimal from the event size point of view. CA8 and AK8 jets generally tend to have quite different shapes so I would be surprised that subjets derived from CA8 jets would quite often have some extra constituents wrt to AK8 jets. So a possible (and maybe not so unlikely) scenario is that because of a single extra constituent in one or more of the subjets, we would duplicate a lot of daughter pointers.

**Comment by rappoccio** [comment]
@ferencek Even the CA8 jets are preclustered with AK8, though, so I'm not sure this happens in practice. You may be right but I think these corner cases are pretty rare.

**Comment by ferencek** [comment]
@rappoccio, aah, indeed, preclustering would reduce the likelihood of this happening (I somehow keep forgetting about preclustering ;) ). However, in busy final states, where it maybe matters even more not to duplicate stuff, this would probably not be so unlikely.

**Comment by gpetruc** [comment]
Yes, i understand.
However i suppose there is no easy way to be able to tell for sure whether
the sub-jets are made from ak8 or not at configuration or creation time.
If we were to put instead an asser that daughters are all in the AK8, it
could happen that all test events pass but the thing eventually crashes in
production (after all, in the tests i had made on some events in the qcd
high pt relval i had not found any spurious daughter even if i was using
the cmsTopTag and not the softDrop...).
Other bright ideas?
Saving separately the the spurious daughters and asking people to veto them
seems a bit a complication.

Giovanni

**Comment by ferencek** [comment]
OK, I added a comment but it would probably still be good to implement Giovanni's suggestion.

**Comment by ferencek** [comment]
@gpetruc, please have a look at the latest commit and let me know if there is anything missing or can be improved.

**Comment by gpetruc** [comment]
@ferencek the modification looks ok to me

**Pull request merged**
