### PR TITLE
Implementation of dedicated tau decayer for resonances

### PR DESCRIPTION
**Pull request by smrenna**
Pythia8 has the capability to define a decay handler for specific particles through DecayHandler.

This request is a special tau decayer that can be used to bias tau pair decays to contain at least one lepton.   It is meant to be used with Powheg samples containing taus so that no Powheg events are lost.

Since DecayHandler is meant to decay one particle at a time, while the standard Pythia tau decayer decays the correlated pair, part of the decay history is saved and then used to fill the products of the second (correlated) tau.

### CODE REVIEW

**Comment by smrenna** [comment]
What does it mean 'tests pending'?     Do you want me to put a cmsRun script in the tests directory?    Also, I ran the code cleanup scripts, which was basically formatting of the code.   Are these automatically added to the pull request?

**Comment by smrenna** [comment]
@bendavid this is the pull request

**Comment by SiewYan** [comment]
please test

**Comment by silviodonato** [comment]
generators:  @alberto-sanchez @agrohsje @efeyazgan @mkirsano @qliphy @SiewYan
Any chance to get this PR signed by today in order to include it in 11_1_0_pre7?

**Comment by SiewYan** [comment]
I am not sure if @bendavid has any comment on this since he is mentioned.

**Comment by bendavid** [comment]
Since the target for this is eventually a backport to 7_1_X, I don't think it's very important which current release it ends up in.

**Comment by silviodonato** [comment]
@bendavid do you have any comments? Is this PR ready to be merged?

**Comment by intrepid42** [comment]
Hi all, I made some validation plots, things look as expected: https://mseidel.web.cern.ch/mseidel/cms/PDG_TAUS/

In particular, here is the number of tau->charged lepton decays:
image
As expected, 0 lepton is depleted completely, and the ratio betwen 1 and 2 leptons stays the same.

To check spin correlations, here is a plot of the dPhi between the two charged leptons, in case of both taus decaying to charged leptons:
image

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
