### PR TITLE
Protect against missing track info in MiniAOD

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #20740

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #20740, merged in 93X 
- Just meant to the special case of analyses re-running  pileup jet ID on top of an existing MiniAOD; no effect on standard workflows

**Comment by davidlange6** [comment]
merge

**Pull request merged**
