### PR TITLE
enable MiniAOD validation, change GenJets to genJetsNoNu for default validation

### PR DESCRIPTION
**Pull request by webermat**
...validations.
Includes a fix for the previous PR https://github.com/cms-sw/cmssw/pull/8504

The MiniAOD validation modules are now put in file
 Configuration/StandardSequences/python/Validation_cff.py 
into validationMiniAOD  instead of the prevalidationMiniAOD sequence

Reorganisation for the MET Harvesting to include a PostProcessor for an overall MET Resolution summary plot and a MET PostProcessorHarvester to compare output of RECO and MiniAOD validations. 

Tested successfully locally using the mentioned unscheduled Validation
runTheMatrix.py -l 11325 -i all

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild @nclopezo 
did the comparison script get stuck? It says queued, still after 6 hours since tests completed.

**Comment by nclopezo** [comment]
Hi @slava77,

There was an issue generating the baseline for the comparison. I am generating it again, and I will restart the comparison as soon as it is available.

**Comment by deguio** [comment]
ciao @webermat 
is there a reason why you moved the valid modules into validationMiniAOD instead of leaving them in the prevalidationMiniAOD sequence?

everything should live in the prevalidation step apart from modules that require trigger results.
thanks,
F.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8672	ed7c357
the introduced changes are not affecting the main monitoring setup used for checking RECO performance: the outputs of DQM plots didn't change for the jenkins workflows (RECO,Validation/DQM in the step2/3).

It's unclear though how or if this interferes with issues that lead to #8632

**Comment by slava77** [comment]
(just in case someone else checks the outputs comparisons from jenkins tests in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8672/4139/summary.html)
the 4.53 workflow has an issue due to a das glitch: different file name was returned and as a result different events were processed.
So, I ignored the discrepancies for this workflow.

@nclopezo David, could you please add a check that the step1_dasquery.log files are the same in the baseline and in the tested PR area. It can either be reported in the "comparison is ready" message; depending on severity then someone can request a rerun of the tests

**Comment by nclopezo** [comment]
Hi Slava, 
I added the check. I restarted the comparisons for this PR to test that it works correctly.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@deguio , @danduggan - what is the status of this PR?

**Comment by webermat** [comment]
The issues of PR  #8632 misbehaving was traced back to the MET part of the miniaod sequence. Running the DQM sequence before the minaod validation MET sequence solves that issue, but that is not the desired solution. Thus for now we put the jet part of the jetmet miniaod monitoring sequence into the forseen validation sequence. Once we figure out how to solve the issue on the MET part the miniaod MET monitoring sequence will follow.

**Comment by webermat** [comment]
Tested successfully that runTheMatrix.py -l 11325 -i all runs still fine.

**Comment by deguio** [comment]
please test
thanks @webermat

**Comment by slava77** [comment]
@cmsbuild please test
new IB CMSSW_7_5_X_2015-05-23-1100 is in and seems ok at least on the build side

**Comment by slava77** [comment]
uhm, it looks like jenkins still starts jobs using 05-22-2300 which is broken
need to trigger tests later again

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8672	5721562
- jenkins tests passed OK (compilation is only relevant here, since the miniAOD validation is not in the jenkins tests)
- tested locally in CMSSW_7_5_X_2015-05-23-1100 /test area test8672/ with 11325 workflow running: it completed fine and DQM file output showed no difference (new plots, if any are not picked up by the diff script)

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
while checking the output of the MiniAOD vs RECO directory, the default collection in MiniAOD for genjets changed to the ak4GenJetsNoNu collection. Thus we move to ak4GenJetsNoNu as default for RECO too. This hardly affects QCD dijet datasets, but leads to sizable differences for TTbar samples.

**Comment by deguio** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
I thought this PR was supposed to modify only miniAOD-related parts of the code, not the standard validation sequence.

Matthias, please update the PR subject and description (at the top of the PR page).
We should not bury default jet collection changes in seemingly unrelated PR names

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8672	10a17d1
- compared to the last sign-off 5721562, input jet collections were changed in the standard validation sequence
- jenkins tests pass ok; comparisons with the baseline show differences in jet plots as expected from the change in the jet collection input
- tested workflow 11325 (it includes miniAOD) locally in CMSSW_7_5_X_2015-05-23-1100 /test area test8672/: miniAOD and jet validation plots have changed in a minor way (as expected for ak4GenJets -> ak4GenJetsNoNu switch).

**Pull request merged**
