### PR TITLE
Allow a boost on particles in MCSingleParticle Filters [80X Backport]

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/18532

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by govoni** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by govoni** [comment]
+1

**Comment by mandrenguyen** [comment]
@davidlange6 Can you merge this one please?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
