### PR TITLE
Add new ECAL PF RecHit thresholds for 2021 Run 3 MC

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

This PR is to add a new ECAL tag, EcalPFRecHitThresholds_34sigma_TL235, to the 2021 Run-3 MC GTs as per request from the ECAL group (https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4462.html), aiming the Run 3 MC Campaign (in 120X).

The differences wrt the previous GTs are listed below.

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v1/121X_mcRun3_2021_realistic_v2

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v1/121X_mcRun3_2021cosmics_realistic_deco_v2

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v1/121X_mcRun3_2021_realistic_HI_v2  

#### PR validation:

runTheMatrix.py -l 159.0,11634.0,7.23 --ibeos -j4

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR will be backported to 120X.

### CODE REVIEW

**Comment by malbouis** [comment]
test parameters:

workflows = 159.0,11634.0,7.23

**Comment by malbouis** [comment]
test parameters:

- workflows = 159.0,11634.0,7.23

**Comment by malbouis** [comment]
please test

**Comment by tvami** [comment]
urgent

* the backport of this is needed for the PF calibration

**Comment by tvami** [comment]
> * DQMHistoTests: Total failures: 1155

 * ECAL changes are expected.

 * Are the changes (a big amount) in the b-tagging expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO/Btag.html

 * There are also a few changes in JetMET, ParticleFlow (I'd have expected more changes here...)
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO/

@bendavid @hatakeyamak @juska @kdlong

**Comment by tvami** [comment]
Let me also tag @cms-sw/ecal-dpg-l2 (please also add any other relevant people)

**Comment by hatakeyamak** [comment]
I went over observed changes quickly. Not surprising, there are quite a few changes in ECAL related reco quantities, so it's hard to digest all of them, but by looking at PF validation plots, I see that changes are specifically coming from PF photons [1], which we expect. This [2] shows PF photon candidate p distribution, and we see a big suppresion at low pt, which again we expect. So, the observed changes are certainly going in the direction we expect.

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO/ParticleFlow_PackedCandidates.html

[2] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/validateJR/all_OldVSNew_TTbar14TeV2021wf11634p0/all_OldVSNew_TTbar14TeV2021wf11634p0c_log10recoPFCandidates_particleFlow__RECO_obj_p72.png

**Comment by tvami** [comment]
> * Are the changes (a big amount) in the b-tagging expected?
>   https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO/Btag.html

Maybe the b-tagging conveners could take this? @johnalison @soureek

**Comment by hatakeyamak** [comment]
> > * Are the changes (a big amount) in the b-tagging expected?
> >   https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-10-1100+617f1e/45373/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO/Btag.html
> 
> Maybe the b-tagging conveners could take this? @johnalison @soureek

We should certainly hear from b-tag experts, but from what I see, many of failures comes from low entry plots where the original blue ones have just one or only handful entries, and in new/test red ones some of the entries disappear. Due to increased thresholds, such behaviors don't seem too surprising.

**Comment by tvami** [comment]
+alca

 * The changes in the Jenkins tests are expected and understood
 * b-tagging was contacted privately to explain the changes in those plots

**Comment by perrotta** [comment]
+1

**Pull request merged**
