### PR TITLE
HLTforUPCAnalysisfor8019pX

### PR DESCRIPTION
**Pull request by illuzate**

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by stahlleiton** [comment]
I guess this should be integrated in CMSSW_8_0_X instead of  CMSSW_8_0_19_patchX, right?

**Comment by dmitrijus** [comment]
81x will have to be merged first, we do not allow anything to be merged in 8_0_X unless it is a backport.
And you are correct, this has to go into CMSSW_8_0_X.

**Comment by davidlange6** [comment]
right - please close this PR and open a new PR on the right branch(es)
Thanks

**Comment by illuzate** [comment]
Hi.
Thank you very much for comments.
Actually, I had tried to PR with base CMSSW_8_0_X first, but it says "Can’t automatically merge".
That is the reason why I had set base as "CMSSW_8_0_19_patchX".
I have tried to PR with CMSSW_8_0_7 environment, with base "CMSSW_8_0_X", but it says again "Can’t automatically merge".
What should I do? Or it can be ignored?
Thank you for your time and consideration.


Best regards,
Beomgon Kim


________________________________
보낸 사람: David Lange [notifications@github.com]
보낸 날짜: 2016년 10월 20일 목요일 오후 4:46
받는 사람: cms-sw/cmssw
참조: Beomgon Kim; Mention
제목: Re: [cms-sw/cmssw] HLTforUPCAnalysisfor8019pX (#16277)

right - please close this PR and open a new PR on the right branch(es)
Thanks

**Comment by dmitrijus** [comment]
Try again! I guess something managed to get merged in that small window.
```
1. make the dev area for the latest IB
2. apply your changes (cherry pick or rebase or whatever you prefer)
3. git push -f
```

if above fails to merge, go back before step 2 and do `git checkout CMSSW_8_0_X`before applying your changes.

**Pull request closed without merging**
