### PR TITLE
Extend L1T CSC DQM with option for ME234/2 chambers and ME2/1 chamber at B904

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

We are currently testing Run-3 trigger motherboard firmware for ME1/3 and MEX/2 chambers with Virtex-2 FPGAs, and for MEX/1 chambers with Virtex-6 FPGAs. We have an ME4/2 and ME2/1 chamber with full trigger+DAQ at B904 for this purpose. This PR extends the L1T CSC DQM with option for ME234/2 and MEX/1 chambers at B904 (follow-up of https://github.com/cms-sw/cmssw/pull/33876). The results also hold for ME1/2 and ME1/3 because they share the same electronics setup (but do have different size and geometry).

Thanks to @barvic for helping with debugging, and to Karoly Banicz for taking the data.

#### PR validation:

Tested on the ME4/2 B904 chamber with a few thousand cosmic events.

[CSC_dataVsEmul_B904_Cosmic_Run_210810_160642 (1).pdf](https://github.com/cms-sw/cmssw/files/7087706/CSC_dataVsEmul_B904_Cosmic_Run_210810_160642.1.pdf)

There should be no changes in the tests because the algorithm did not change, just the analysis code.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

FYI @tahuang1991

### CODE REVIEW

**Comment by smorovic** [comment]
+1

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Please test with https://github.com/cms-sw/cmssw/pull/35121

**Comment by smorovic** [comment]
+1

**Comment by dildick** [comment]
@jfernan2

**Comment by dildick** [comment]
@jfernan2 Could you run the tests, please? Thanks!

**Comment by jfernan2** [comment]
Please test with #35121

**Comment by dildick** [comment]
A few failures, all from messagelogger

**Comment by jfernan2** [comment]
+1

**Comment by smorovic** [comment]
+1

**Comment by qliphy** [comment]
please test 
last test was done some days ago.
@cms-sw/l1-l2  Please comment on this PR.

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
There are differences in the DD4Hep workflow 11634.911 comparisons:   https://github.com/cms-sw/cmssw/issues/35109

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
