### PR TITLE
Threaded dqm migration5

### PR DESCRIPTION
**Pull request by anorkus**
multi-thread DQM migration in some of DQMOffline packages

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @anorkus 
thanks for this. few comments:
- please remove any instance of the DQMStore like: https://github.com/cms-sw/cmssw/pull/8168/files#diff-d0a3cd030ae720f1911b96b09ec0df32R57

- please change the comment at: https://github.com/anorkus/cmssw/blob/threaded_dqm_migration5/DQMOffline/EGamma/plugins/PhotonDataCertification.cc#L44 to endJob

- please change this to be a normal beginRun otherwise it won't be called:
https://github.com/anorkus/cmssw/blob/threaded_dqm_migration5/DQMOffline/Trigger/src/EgHLTOfflineClient.cc#L67

thanks,
F.

**Comment by deguio** [comment]
+1
thanks @anorkus

**Comment by davidlange6** [comment]
+1

**Pull request merged**
