### PR TITLE
[106X] Rename modifier run2_final_state_rad

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

Moved:
`Configuration/Eras/python/Modifier_run2_final_state_rad_cff.py` --> `Configuration/ProcessModifiers/python/run2_final_state_rad_cff.py` 
This enables the usage of the modifier by passing `--procModifiers run2_final_state_rad` to cmsDriver.
Look at [1] for details.

[1] https://github.com/cms-sw/cmssw/pull/39942#issuecomment-1335769783

Tagging @tvami

### CODE REVIEW

**Comment by tvami** [comment]
hi @SohamBhattacharya please include "[106X]...." in the beginning of the PR title

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
