### PR TITLE
correct dependencies and includes

### PR DESCRIPTION
**Pull request by davidlange6**
Correct BuildFile for TrackingTools/AnalyticalJacobians, and correct includes in Calibration/EcalTBTools (found during random modules IB debugging)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by yuanchao** [comment]
+1
* correct BuildFile.xml and adding includes
* no build warning / errors
* matrix tests and unit tests all passed

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
