### PR TITLE
fix to checksums of simple LHE files + remove whatever fake blank spaces/tabs were created by some editor

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by bendavid** [comment]
This should go in 75x no?

**Comment by covarell** [comment]
Also did the PR for 75x (#8418), if possible it should be backported to 74x I believe (this is independent of any other cmssw code, so ideally it should be available to users in the maximum number of releases)

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
