### PR TITLE
Phase2-hgx360C Update a few test scenario definitions to test V19 geometry preparation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update a few test scenario definitions to test V19 geometry preparation

#### PR validation:

Use tests in Geometry/HGCalCommonData/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar could you approve this?

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
