### PR TITLE
[10_6_X] MXNet-based implementation of the ParticleNet tagger

### PR DESCRIPTION
**Pull request by hqucms**
Backport of https://github.com/cms-sw/cmssw/pull/28902.

Currently the ParticleNet tagger is not added to the MiniAOD sequence. But we plan to enable it for UL re-MiniAOD.

Needs:
 - DNN model: https://github.com/cms-data/RecoBTag-Combined/pull/26
 - MXNet 1.5: https://github.com/cms-sw/cmsdist/pull/5592

We should also integrate https://github.com/cms-data/RecoBTag-Combined/pull/24 together with the update to MXNet 1.5.

### CODE REVIEW

**Comment by slava77** [comment]
test parameters
- pull_request = cms-sw/cmsdist#5717

**Comment by slava77** [comment]
> Currently the ParticleNet tagger is not added to the MiniAOD sequence. But we plan to enable it for UL re-MiniAOD.

if this is planned for UL, please add the tagger via ```run2_miniAOD_devel```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
> > Currently the ParticleNet tagger is not added to the MiniAOD sequence. But we plan to enable it for UL re-MiniAOD.
> 
> if this is planned for UL, please add the tagger via `run2_miniAOD_devel`

ping

**Comment by hqucms** [comment]
> > > Currently the ParticleNet tagger is not added to the MiniAOD sequence. But we plan to enable it for UL re-MiniAOD.
> > 
> > 
> > if this is planned for UL, please add the tagger via `run2_miniAOD_devel`
> 
> ping

@slava77 Done in https://github.com/cms-sw/cmssw/pull/29062/commits/d6a874011a3a736a48aa96f156d73d3c4fa49139.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please abort

**Comment by slava77** [comment]
test parameters
- pull_request =

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
>  Tested with other pull request(s) [cms-sw/cmsdist#5717](https://github.com/cms-sw/cmsdist/pull/5717)

@smuzaffar I thought that doing as in https://github.com/cms-sw/cmssw/pull/29062#issuecomment-614020547 I would get the extra requirements reset.

> test parameters
> 
>     * pull_request =

What it the right way to reset the extras?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29062	d6a8740 
- code changes are in line with the PR description and the follow up review. The backport is a bit closer to the master version than the 10_2_X, but it's still fairly close to the #29063 . 
    - The new code is enabled with run2_miniAOD_devel and otherwise does not affect the production workflows.
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
- I checked locally with run2_miniAOD_devel added to wfs 1325.7 and 136.8311 to confirm that the particleNet taggers run and that the values are consistent with the tagger results in the master version (on 1000 events there were no differences above 1E-4 level relative, compared to the tag results in 11_1_0_pre5; I'm taking this as close enough for a validation for physics purpose as well).

**Comment by silviodonato** [comment]
do you have comments @santocch?

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
