### PR TITLE
DQM online client - GT fix for condition DB access 

### PR DESCRIPTION
**Pull request by popovvp**
removed out of GT tags in DQM Integration client Castor python-file

### CODE REVIEW

**Comment by diguida** [comment]
@popovvp the changes proposed here are not 100% fine. In particular:

1. the removal of lines https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fL30 to https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fL58, and the use of only https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fR30 is ok: your client will use the GlobalTag and condition access as specified in the central DQM online configuration.
2. the uncommenting of https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fL60 and https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fL61 is not good: this forces you application to use the re-reco Global Tag used in release validation, which is specified by the `run2_data` key in [`autoCond`](https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Configuration/AlCa/python/autoCond.py): as clarified in the comment, this is useful only for testing purposes offline.

Please, amend the commit by commenting out https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fR31 and https://github.com/cms-sw/cmssw/pull/16564/files#diff-3d9d457e24541d87ac089a37cc36fd1fR32.

As agreed verbally with @franzoni , adding @franzoni @mmusich (I am not able to find Arun's GitHub username)

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
@arunhep

**Comment by diguida** [comment]
@popovvp the change in https://github.com/cms-sw/cmssw/pull/16564/commits/37029360f61d57ff68ceca4ceba20b2df79ce55d looks ok to me.

**Comment by dmitrijus** [comment]
castor_dqm_sourceclient-live_cfg.py  should be in DQM/Integration/python/clients, not root.

**Comment by diguida** [comment]
@popovvp please reset your branch to https://github.com/cms-sw/cmssw/pull/16564/commits/37029360f61d57ff68ceca4ceba20b2df79ce55d and force the update:

````
# On local branch dgmgt81x
$ git reset --hard HEAD~1
$ git push my-cmssw +HEAD:dgmgt81x
````

**Comment by diguida** [comment]
@popovvp the refurbished branch with the single commit https://github.com/cms-sw/cmssw/pull/16564/commits/f687f477bcca1a67cc64dc523a03d774d6bffc51 looks ok to me.
@dmitrijus please start the tests.

@popovvp given that we want this running in 8.0.X, please back-port this to a branch departing from `CMSSW_8_0_24` branch:

```
$ cmsrel CMSSW_8_0_24
$ cd CMSSW_8_0_24/src
$ cmsenv
$ git cms-addpkg DQM/Integration
$ git checkout -b dgmgt80x
$ git cherry-pick f687f47
$ scram b -j 8
# run your tests!
$ git push my-cmssw dgmgt80x
```

and then make a PR for this branch.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@diguida do you happen to know where the 90x fwdport of this is?

**Comment by diguida** [comment]
@mmusich thanks for launching the tests.
I am checking

**Comment by diguida** [comment]
@mmusich the automatic forward-port to 9.0.X did not pick this PR as it was closed, and re-opened later. Thanks for catching this. So, another action on @popovvp:
Go [here](https://github.com/cms-sw/cmssw/compare/CMSSW_9_0_X...popovvp:dgmgt81x?expand=1) and push the "Create Pull Request" button.

**Comment by popovvp** [comment]
not to confuse - shoud I submit new PR to 90X ? Pls confirm.

**Comment by diguida** [comment]
@popovvp you should submit two Pull Requests:

1. for 80X following the instructions in https://github.com/cms-sw/cmssw/pull/16564#issuecomment-261500263
1. for 90X following the instructions in https://github.com/cms-sw/cmssw/pull/16564#issuecomment-261502316

**Comment by diguida** [comment]
Forward-port to 9.0.X: #16683

**Comment by mmusich** [comment]
@diguida thanks!

**Comment by diguida** [comment]
@mmusich well, thanks to @popovvp for fulfilling point 2. :-)

**Comment by diguida** [comment]
@popovvp the changes in https://github.com/cms-sw/cmssw/pull/16564/commits/f687f477bcca1a67cc64dc523a03d774d6bffc51 (refurbished commit after some hiccups) look ok to me.
@dmitrijus can you please re-launch the tests?
@mmusich is it ok for you to un-hold this PR in order to proceed further with integration?

**Comment by dmitrijus** [comment]
+1

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
