### PR TITLE
NanoAODv6 updates, part 2

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

This pull request contains the second (and, in our intentions, last) part of code updates for the NanoAODv6 campaign.

Summary of changes:

- added a couple of secondary vertex variables
- added selection bitmap for HEEP 7.0 electron ID
- added photons from muon FSR
- store mass of new physics particles in the generator
- updated jet ID to WINTER17PUPPI, SUMMER18, SUMMER18PUPPI versions

Depends on #28118.

#### PR validation:

Validated as usual within the nanoAOD integration setup.

A merged backport of #28103 and this PR will follow to 10_2_X and 10_6_X.

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28118,#28096

testing explicitly all NanoAOD workflows with other pull requests intended for NanoAODv6 campaign

**Comment by peruzzim** [comment]
+xpog

tests show differences in nanoAOD collections, as expected

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28118,#28096

re-testing after jet ID update (bugfix for forgotten propagation to NanoAOD of #27184)

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28118

re-testing after updating module names in #28118 and adapting the configuration to that change here

**Comment by peruzzim** [comment]
+xpog

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
