### PR TITLE
Run3-gem42 Remove reference to GE21 from Run3 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to GE21 from Run3 scenario

#### PR validation:

Tested by modifying the workflow 11034.0 changing input from XML rather than from DB

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special. But the payload for 2021 in DB needs recreation

### CODE REVIEW

**Comment by bsunanda** [comment]
@kpedro88 This PR needs to be rebased after your PR #30477 is merged

**Comment by bsunanda** [comment]
@kpedro88 - I can do a simple thing - make the changes directly into v2 version of muonnumbering.xml. Then other changes are not needed.

**Comment by kpedro88** [comment]
it's up to @ianna and @cvuosalo if they want to allow changes directly in the v2 version of the xml

**Comment by bsunanda** [comment]
@cvuosalo @ianna I made this PR to remove unnecessary reference to GE21 detectors in 2021 scenario. The simplest changes would have been to directly edit the file muonNumbering/2021/v2/muonNumbering.xml. That will solve editing dict2021 file. Can I do that?

**Comment by cvuosalo** [comment]
@bsunanda @ianna It seems to me that this change is just a bug fix and doesn't require a new version. I still have to re-create the 2021 DB payloads, so I don't think v2 needs to be preserved unchanged.

**Comment by bsunanda** [comment]
@cvuosalo @ianna Thanks. That saves a lot of changes

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
