### PR TITLE
Synchronizing L1T O2O in CMSSW with what have been developed at p5

### PR DESCRIPTION
**Pull request by kkotov**
PR includes:
1) updating tag versions for L1TMuonEndCapParams (v1) and L1TMuonBarrelParams (v1)
2) "transactionSafe" parameter (true by default) that can be changed to force O2O committing to CondDB even if some XMLs tirggered parsing errors (a last resort to start the run no matter what)
3) "ForFunctionManager" concise summary added to printout to be filtered and sent back to the FM
4) change Endcap to EndCap to make colleagues happy (what's next, Overlap to OverLap?)
5) striping off the 2016 XML scheme for the prescales/vetos
6) homogenizing names under L1TriggerConfig/Utilities

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@rekovic have these changes been tested in the O2O environment?

**Comment by rekovic** [comment]
@ggovi 

I would imagine @kkotov should have done it, but I am not sure.  Unfortunately @kkotov is not
available any more, so this would have to be done/repeated.   Are you in place to test it?

**Comment by rekovic** [comment]
Hi @ggovi 
This PR has been tested at P5 with a small fix in `L1Trigger/L1TMuonEndCap/python/fakeEmtfParams_cff.py`
A working version of o2o2018_debug_v2.sh is made at the conddb machine at P5.

**Comment by ggovi** [comment]
@rekovic 
so you need to update the PR for the small fix?

**Comment by ggovi** [comment]
@rekovic 
I would suggest to close this, reopen a new PR with the fix...

**Pull request merged**
