### PR TITLE
Fix dd4hep modifier import

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

https://github.com/cms-sw/cmssw/pull/28847 missed to migrate two cfi configuration files for the new location of `dd4hep` Modifier. This PR fixes the those two files.

#### PR validation:

Evaluating the two cfi files through python succeeds.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type bugfix

**Comment by makortel** [comment]
urgent

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@smuzaffar @makortel @silviodonato BTW, I find bizarre that this problem has affected many IBs, but apparently not the CLANG one.  Again an issue of old files still being used?

**Comment by makortel** [comment]
> BTW, I find bizarre that this problem has affected many IBs, but apparently not the CLANG one. Again an issue of old files still being used?

That would be by best guess as well, the last full CLANG build was on CMSSW_11_1_CLANG_X_2020-02-04-2300 i.e. before https://github.com/cms-sw/cmssw/pull/28847

**Comment by smuzaffar** [comment]
looks like `git-cms-sparse-checkout` is not working properly for changes/packages where we just move files. In https://github.com/cms-sw/cmssw/pull/28847 we moved  `Configuration/Era/python/Modifier_dd4hep_cff.py` to  `Configuration/ProcessModifiers/python/dd4hep_cff.py` so ideally Configuration/Era package should have been checked out in the patch release too but it did not [a]. So that is why in patch release Configuration/Era/python/Modifier_dd4hep_cff.py was still accessible. 

[a]
```
>pwd
/cvmfs/cms-ib.cern.ch/nweek-02614/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-02-05-2300/src/Configuration
>ls -l
total 8
lrwxrwxrwx. 1 cvmfs cvmfs 76 Feb  5 23:41 AlCa -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/AlCa
drwxr-xr-x. 4 cvmfs cvmfs 35 Feb  5 23:36 Applications
lrwxrwxrwx. 1 cvmfs cvmfs 86 Feb  5 23:41 DataProcessing -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/DataProcessing
lrwxrwxrwx. 1 cvmfs cvmfs 78 Feb  5 23:41 EcalTB -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/EcalTB
```
#Below ERA should be a local package but it is symlink to full release area
```
lrwxrwxrwx. 1 cvmfs cvmfs 76 Feb  5 23:41 Eras -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/Eras
lrwxrwxrwx. 1 cvmfs cvmfs 84 Feb  5 23:41 EventContent -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/EventContent
lrwxrwxrwx. 1 cvmfs cvmfs 81 Feb  5 23:41 Generator -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/Generator
drwxr-xr-x. 5 cvmfs cvmfs 64 Feb  5 23:36 Geometry
lrwxrwxrwx. 1 cvmfs cvmfs 82 Feb  5 23:41 GlobalRuns -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/GlobalRuns
lrwxrwxrwx. 1 cvmfs cvmfs 75 Feb  5 23:41 HLT -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/HLT
lrwxrwxrwx. 1 cvmfs cvmfs 78 Feb  5 23:41 JetMET -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/JetMET
drwxr-xr-x. 3 cvmfs cvmfs 20 Feb  5 23:36 ProcessModifiers
lrwxrwxrwx. 1 cvmfs cvmfs 91 Feb  5 23:41 PyReleaseValidation -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/PyReleaseValidation
lrwxrwxrwx. 1 cvmfs cvmfs 79 Feb  5 23:41 SVSuite -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/SVSuite
lrwxrwxrwx. 1 cvmfs cvmfs 80 Feb  5 23:41 Skimming -> ../../../../../cms/cmssw/CMSSW_11_1_X_2020-02-04-2300/src/Configuration/Skimming
drwxr-xr-x. 4 cvmfs cvmfs 31 Feb  5 23:36 StandardSequences
```

**Comment by makortel** [comment]
> looks like `git-cms-sparse-checkout` is not working properly for changes/packages where we just move files.

Good catch. Do you think it could be fixed in the near future, or should we just create an issue?

**Comment by smuzaffar** [comment]
@makortel , fix is trivial ( https://github.com/cms-sw/cms-git-tools/pull/108 )

**Comment by makortel** [comment]
Excellent, thanks!

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
