### PR TITLE
Fix pixel cluster reconstruction for layer 1 in alcalumipixel stream (in 92X)

### PR DESCRIPTION
**Pull request by capalmer85**
Same as #20343 but for 92X.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by capalmer85** [comment]
@arunhep any feedback before signoff?  This needs to go in before the re-reco.

**Comment by arunhep** [comment]
+1

**Comment by capalmer85** [comment]
@lpernie could you trigger here too please?

**Comment by lpernie** [comment]
please test

**Comment by capalmer85** [comment]
@lpernie thanks!

FYI, I did "runTheMatrix.py -l 1001,1020" and everything succeeded (note that these are both running on pixel phase0 detector data).

**Comment by capalmer85** [comment]
@lpernie, @arunhep, @davidlange6 looks like the test aborted for some reason.   From the link above:

New build name is 'PR cmssw#20388 cmsdist#'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'PR cmssw#20388 cmsdist#', new value: 'PR cmssw#20388 cmsdist#'
Build was aborted
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: ABORTED

These tests passed in the PR for the master:  #20343

**Comment by lpernie** [comment]
Hello @smuzaffar , could you please comment on this? Thanks

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@lpernie , looks like git checkout was stuck and build timed out after 10hours
```
+ git cms-merge-topic -u 20388
No release tags specified, using default CMSSW_9_2_X_2017-09-11-1100.
Cloning into '/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-09-11-1100/src'...
Build timed out (after 600 minutes). Marking the build as aborted.
```

**Comment by lpernie** [comment]
I see, thanks for explanation

**Comment by arunhep** [comment]
IMHO this PR is not needed anymore. @capalmer85 please close this unless you think otherwise.

**Comment by capalmer85** [comment]
Yes. Agreed.

**Pull request closed without merging**
