### PR TITLE
Phase 2 GTT fix miscellaneous bugs and add Displaced TrackJet HT

### PR DESCRIPTION
**Pull request by NJManganelli**
#### PR description:

This PR combines several smaller PRs that fixed bugs and made additions for Phase 2 GTT workflows (outside of the nominal SimL1 workflow), as recommended by @aloeliger:

(1)
"This PR fixes cases when no options to load tracks or vertices from buffers is specified in the GTT F/W workflow and the input file does not contain lists of buffers to load from

This does not affect nominal workflows pertaining to AR; but this is also not time-sensitive and can be deferred in review as needed."

(2)
"Phase 2 GTT fix off-by-one error and collection mismatch in L1TrackObjectNtupleMaker"

(3)
"This PR adds the GTT Displaced Track HT(Miss) word into the emulation buffers for GTT to GlobalTrigger (the buffers encoding jets, sums, vertices, etc. and eventually mesons, taus, isolated tracks...)"

#### PR validation:

scram b code-format
scram b code-checks
scram b
+ the checks in the integration branch appropriate to each PR (running NTuplizer, GTT firmware buffer workflow, etc.)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is an aggregate combining the following small PRs from cms-l1t-offline Phase 2 integration branch:
https://github.com/cms-l1t-offline/cmssw/pull/1233
https://github.com/cms-l1t-offline/cmssw/pull/1234
https://github.com/cms-l1t-offline/cmssw/pull/1235

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
