### PR TITLE
L1T EMTF O2O 2018 

### PR DESCRIPTION
**Pull request by rekovic**
This PR fixes the params needed for successful O2O of L1T EMTF:
 - Remove unused "Endcap", now use "EndCap"
 - Change "EMTF-1" to "EMTFp1"

This has been tested offline and has been running centrally at P5 as local installation on condb machines as fix to L1T O2O.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic is there a master version of this PR?

**Comment by rekovic** [comment]
@fabiocos 
No there is not at the moment.
We will make one, once L1T O2O running with CMSSW_10_1_5 + this PR is successfully tested.

**Comment by arunhep** [comment]
@rekovic do you have a status update for this PR ?

**Comment by rekovic** [comment]
@abrinke1 Please make a change from "Stage2v1_hlt" to "Stage2v3_hlt" in 
https://github.com/abrinke1/cmssw/blob/c73ff5275da91511b40186945f38dad30ccd9ed2/CondTools/L1TriggerExt/python/L1O2OTagsExt_cfi.py#L15

so that the proper EMTF tag is updated by the O2O at P5.
The patch is being deployed at P5.

**Comment by abrinke1** [comment]
Hi @rekovic , @gekobs ,
Does this only apply to the EMTF tag, or also to the other tags in this file?
https://github.com/abrinke1/cmssw/blob/EMTF_PR_2018_10_1X_O2O/CondTools/L1TriggerExt/python/L1O2OTagsExt_cfi.py
I see Stage2v0_hlt, Stage2v1_hlt, and Stage2v3_hlt all represented right now.  Should all tags be changed to Stage2v3_hlt?
Cheers, Andrew

**Comment by gekobs** [comment]
Hi @abrinke1,
I think no.
I am checking this data GT https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_v7
and as you can see the tag names are a mixture of v0, v1 and v3, but the only tag which shows an old IOV is the MuonEndCapParams one. (as well as the Forest, the End**c**ap and the OverlapParams but they are not meant to be o2o).
Does it sounds reasonable?
Cheers, Giacomo

**Comment by abrinke1** [comment]
@rekovic @gekobs ,
Done.  Also, one other question, since I happened to notice.  In L1O2OTagsExt_cfi.py, the L1TriggerKeyListExt and L1TriggerKeyExt tags are both set to Stage2v0_hlt.  But in the 101X_dataRun2_HLT_v7 Global Tag [1], the L1TriggerKeyListRcd has tag L1TriggerKeyList_CRAFT09_hlt, and the L1TriggerKeyRcd has tag L1TriggerKey_CRAFT09v3_hlt.  I have no idea what these keys do, or if they matter.  But I thought I'd point it out.
Cheers,
Andrew

[1] https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_v7

**Comment by lpernie** [comment]
please test

**Comment by rekovic** [comment]
@abrinke1 
Can you please update your branch with the fix Giacomo Zechinelli deployed online.

**Comment by abrinke1** [comment]
Hi @gekobs , @rekovic ,
Can you point me to the branch or PR with Giacomo's fix?
Cheers, Andrew

**Comment by rekovic** [comment]
@abrinke1 

https://github.com/cms-sw/cmssw/blob/a3e3ad4cba8fe81daeeb2aaba145470afbc9609c/CondTools/L1TriggerExt/python/L1O2OTagsExt_cfi.py#L15
 
Plase chhange  "Stage2v1_hlt" to "Stage2v3_hlt"

**Comment by rekovic** [comment]
@fabiocos 
With the simple change that @abrinke1 is going to make, this PR will be identical to the O2O fix 
that we are currently running at P5.  So, I would like to have it merged in 10_2_0, so we can deploy that release on ConDB machine and get rid of the current fixed installed there locally.

**Comment by rekovic** [comment]
@abrinke1 
Please disregard my previous request, as you have already made that change in your last commit 58524e7

**Comment by rekovic** [comment]
@fabiocos 
This is ready to go in.  I am changing the title of this PR and removing "TEST"

@ggovi @arunhep please review/sign.

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@fabiocos you are correct.
Making one now for 10_2_X.  Thanks.

**Comment by ggovi** [comment]
+1

**Comment by rekovic** [comment]
backport #23759

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
From discussion with Fabio.
will close now this 10_1_X.
will have to fix the #23759 which was reverted in 10_2_X and make 3 new PRs.
(10_3_x, 10_2_x, and 10_1_x)

**Comment by rekovic** [comment]
The proposed fix was to introduce back the dropped DataFormats.

**Comment by rekovic** [comment]
abort test

**Comment by fabiocos** [comment]
please abort

**Pull request closed without merging**
