### PR TITLE
[muon] disable trigger matching

### PR DESCRIPTION
**Pull request by drkovalskyi**
Disable patMuon trigger matching to address the issue reported in https://github.com/cms-sw/cmssw/issues/23704

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
privately verified that it fixes also 136.855 (as obviously expected)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

as agreed as temporary workaround to avoid crashes. A complete solution will be developed after CMSSW_10_2_0_pre6

**Comment by jfernan2** [comment]
+1

**Pull request merged**
