### PR TITLE
Create Pythia8CUEP8M2T4Settings_cfi.py and CP1-5 cfi's. 

### PR DESCRIPTION
**Pull request by efeyazgan**
backport the tune snippet CP0(=CUETP8M2T4) to 71X

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by perrozzi** [comment]
maybe wirth adding the CPi snippets as well

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by perrozzi** [comment]
(can change the PR name to reflect the enlarged scope)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
