### PR TITLE
Sync Materials in 2015 Dev Scenario

### PR DESCRIPTION
**Pull request by ianna**
- Include all new materials to 2015 dev scenario from what is now 2015 Prod scenario.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@ianna - seems that this is not only adding new materials, but changing existing materials. Is that correct?

**Comment by civanch** [comment]
@davidlange6 , no, only additions are in this PR (changed line - removed space).

**Comment by davidlange6** [comment]
isn not the definition of "AQBB borated concre" changed?

**Comment by civanch** [comment]
@ianna , David is right , better to remove lines 247-249 with addition of water because the accuracy of material composition will not be improved (I believe it is within uncertainty) but the sum of mass fractions become not normalized. You will need renormalise all other components.

**Comment by ianna** [comment]
@davidlange6 - there has been a bug fix for it in a production scenario to make up to 100%. Now the material in both scenarios is identical. It would have been just a warning in a workflow.

**Comment by ianna** [comment]
@davidlange6 and @civanch - The change to 2015 prod scenario has been introduced on 8 Jul 2015:
https://github.com/cms-sw/cmssw/commit/de8287825ac2385aa645c8ea086300e94a983c9b#diff-d53c10c6f873438ad2c6c4ba45c8b78c

**Comment by davidlange6** [comment]
+1

I see - thanks

**Comment by civanch** [comment]
@ianna , weight fractions should be normalized: the sum should be 1.0. Just now I make a sum and 1.00000001 is the sum without this extra water. If this water will be added we will have a permanent warning.

**Comment by ianna** [comment]
@civanch - There should be already a warning in a prod scenario then. In any case, I'll be validating both dev and pro scenarios as a next step including a full report on overlaps. The validation script is being integrated into an IB test step and we'll get a full comparison report for every IB.

**Pull request merged**
