### PR TITLE
elide newCombinedSeeds in electron seeding

### PR DESCRIPTION
**Pull request by slava77**
instead of making a trivial merge-by-copy done in newCombinedSeeds, pass the inputs directly to the ElectronSeedProducer.
This PR avoids extra work spent in copying and reduces the memory utilization.
- ElectronSeedProducer and its utility methods are updated to be able to take a vector of seed collections as input
- ```newCombinedSeeds``` remains in the sequence definitions as a placeholder (it is not running in unscheduled mode because it is not consumed). I did not completely remove ```newCombinedSeeds``` yet pending some better understanding if the concept of combining seeds is useful in general (perhaps it is): it will be very easy to introduce a non-trivial seed combiner (e.g. with hit filter or other manipulation).

Inspired by observations of large memory use in HIHardProbes processing
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_3_1_patch1-orig.cmsRunGlibC.PromptReco_Run326383_HIHardProbes.IgProf.1.MEM_LIVE/20
This is on event 326383:1:51371 (at the end of the first event in the job).

Tested in CMSSW_10_3_1_patch1
- Using the profile for one event as a reference of a bad case of memory use, as much as 5GB reduction in the peak can be expected. Given stochastic nature of getting a peak in multi-threaded execution, the reduction is probably smaller.
- comparison of peaks in 8-thread execution shows 2.1GB reduction in the peak after 2h of running and 3.0 GiB after 21h (the job is still running as of submission time [numbers to be updated]).
- short matrix tests pass and comparisons show no differences

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

try again

```
A std::exception was thrown.
Can not get data (Additional Information: [frontier.c:1124]: No more proxies.
```
looks transient

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25199	2e345f4 
- jenkins tests pass and comparisons show no differences as expected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
