### PR TITLE
Force clearing EventSetup caches before destruction

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by wddgit** [comment]
please test

Note that the entire change in this PR is contained in PR #24348. If that one is merged first, this one can be closed. If this one is merged first, then I will rebase the other one. I have other PR's I want to submit that need this one line change, which is why I am trying to push this through faster (and it only needs Core approval)

**Comment by wddgit** [comment]
please test

Try again, failure appears unrelated to this Pull Request

**Comment by wddgit** [comment]
The test failure is unrelated to this PR. Maybe I will try to rerun the tests again tomorrow. This is the error in test 4.22.

---- Begin Fatal Exception 22-Aug-2018 20:42:23 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root'

**Comment by mrodozov** [comment]
please test

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
