### PR TITLE
Update some texts in the pull_request_template

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Prompted by this discussion:
https://github.com/cms-sw/cmssw/pull/38357#issuecomment-1162808389
I believe we should update the text regarding PR that are intended to be backported in the first place. 

I open this PR as RFC to understand how people feel about the change

### CODE REVIEW

**Comment by tvami** [comment]
@cms-sw/orp-l2 what do you think?

**Comment by qliphy** [comment]
> @cms-sw/orp-l2 what do you think?

Thanks @tvami   I think this update is nice and useful.

**Comment by tvami** [comment]
@qliphy shall this be merged then? Thanks!

**Comment by qliphy** [comment]
> @qliphy shall this be merged then? Thanks!

I am fine with this. We also need core to have a look.  @smuzaffar @perrotta  If this looks good to you, please go ahead. thanks!

**Comment by perrotta** [comment]
Perhaps removing "[RFC}" from the title may convince Core to have a look...

**Comment by tvami** [comment]
> Perhaps removing "[RFC}" from the title may convince Core to have a look...

Sure, tho I thought that means "request for comments" which is exactly what I wanted from the relevant parties. :D

**Comment by smuzaffar** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
