### PR TITLE
[NanoAOD] Backport of #37744 (Setup AK4 Puppi jets as default AK4 collection for Run 3) to 12_4_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #37744

#### PR description:

This PR sets the AK4 Puppi jet collection as the default AK4 jet collection for Run 3 NanoAOD production. The AK4 Puppi jet collection is retrieved from MiniAOD (`slimmedJetsPuppi`) and are saved in the `Jet` table in NanoAODs, although with less variables stored, compared to AK4 CHS jets, due to the unavailable trainings for PileUp Id, Quark-Gluon Likelihood and b-jet/c-jet energy regression.

The reco jet configurations have been split up into three different cff files. Two new cff files for AK4 Puppi jets (`jetsAK4_Puppi_cff.py`) and AK8 Puppi jets  (`jetsAK8_cff.py`) with `jets_cff.py` renamed to `jetsAK4_CHS_cff.py`. All AK8 Puppi related configurations in `jets_cff.py` are moved to `jetsAK8_cff.py`. For Run 2 compatibility, Run 2 modifiers are set up in various files to switch from AK4 Puppi jets to AK4 CHS jets. Some housekeeping were also done like moving the AK4 and AK8 DeepInfo functions and switches from `nano_cff.py` to `jetsAK4_CHS_cff.py` and `jetsAK8_cff.py`.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

backport inline with master

**Comment by mariadalfonso** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37744

**Comment by qliphy** [comment]
+1

**Pull request merged**
