### PR TITLE
[94X] DeepFlavour Negative Tagger

### PR DESCRIPTION
**Pull request by emilbols**
backport of https://github.com/cms-sw/cmssw/pull/23467

The only difference is that the DeepFlavour model is no longer updated

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 96 differences found in the comparisons

changes in 94X are not allowed at this point.
Please adjust the implementation of this backport to preserve the default behavior.

**Comment by emilbols** [comment]
OK, so i guess we should not update the DeepFlavour model?

**Comment by slava77** [comment]
On 7/10/18 12:56 PM, emilbols wrote:
> OK, so i guess we should not update the DeepFlavour model?
> 
> —


right, not in the default setup

**Comment by emilbols** [comment]
I restored the deepFlavour model to the original setup. That should be the reason that there were differences with the baseline.

**Comment by slava77** [comment]
> Reco comparison results: 90 differences found in the comparisons

the last update was not good enough, apparently.

**Comment by emilbols** [comment]
So the discriminator distribution slightly changed, which it shouldn't have. I think i found the issue, i was calculating deltaR using the vertex flight direction as done in deepCSV, but it should be done using the vertex momentum for deepflavour. If there are no differences with the baseline now, i will propagate this to the master as well.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
I believe that this is the right console for the tests
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/29079/console
this appears to be stuck.
Please check.

**Comment by slava77** [comment]
@cmsbuild please test

hoping that a restart will work

**Comment by smuzaffar** [comment]
things have not still recovered from the yesterday's CVMFS issue https://cern.service-now.com/service-portal/view-outage.do?n=OTG0044912

looks like VM cmsbuild82 is in bad state, I am talking out of system.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23763	3dc27e4
- the backport of a combination of https://github.com/cms-sw/cmssw/pull/23467	b626752 and https://github.com/cms-sw/cmssw/pull/23781	319c283  (current state of the master branch) is correct; this backport excludes the change to the new training made for the master to preserve backward compatibility in this production release.
- jenkins tests pass and comparisons with the baseline show no differences.

**Comment by fabiocos** [comment]
@slava77 I understand that the default behaviour is kept with this backport, but in principle the user has in case the possibility to access the new training by changing the input file that here is omitted, right?

**Comment by fabiocos** [comment]
+1

the update has been made backward compatible for the default proposed configuration

**Comment by fabiocos** [comment]
merge

**Pull request merged**
