### PR TITLE
Fix bug in FormulaEvaluator involving parenthesis and precedence order [10_2]

### PR DESCRIPTION
**Pull request by Dr15Jones**
A sub-expression involving a parenthesis was not using the top node as the representation for the expression. That mixed with precedence order fixing resulted in part of the expression being lost.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
backport #24049

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 609 differences found in the comparisons

IIUC, 10_2_0 was validated already for the area affected by the bugfix.
Either 10_2_0 should be invalidated, or inclusion of this PR will require a full validation cycle in 10_3_X
and hopefully by then no significant production has started yet, because it will have to be scrapped in time for integration of this PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24050	61fd3ca
- changes are the same as in https://github.com/cms-sw/cmssw/pull/24049	611a792. This affects miniAOD jet-related outputs. Given that 10_2_X is still in sort of almost in production, I think that it may be worth to have a fix and assume what was already made in 10_2_X "production" can be updated/redone
- jenkins tests pass and comparisons with the baseline show differences as expected in miniAOD jet-related quantities

**Comment by fabiocos** [comment]
+1

as discussed at the ORP we merge this fix before the beginning of MC production, assuming that data will be anyway reprocessed at mAOD level in not so long a time

**Comment by fabiocos** [comment]
merge

**Pull request merged**
