### PR TITLE
Fix multiple booking in fillSummary.

### PR DESCRIPTION
**Pull request by pohsun**
Fix multiple booking issue for histograms.

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
ciao @pohsun 
thanks for this. actually the most offending part in terms of multiple booking is step1 and not the harvesting.
do you plan to fix it as well?
you can find the list of histos which are booked multiple times at:
~deguio/public/ForPohsun/log.log

ciao and thanks,
F.

**Comment by deguio** [comment]
@pohsun 
can I count on you for the fixing of step1 as well?
thanks in advance,
F.

**Comment by deguio** [comment]
+1

**Comment by pohsun** [comment]
@deguio
Sure, I'm going to fix step1.

Po-Hsun

2015-05-12 17:26 GMT+02:00 deguio <notifications@github.com>:

**Comment by davidlange6** [comment]
+1

**Pull request merged**
