### PR TITLE
git trigger type via TCDS for l1dqm (rebased)

### PR DESCRIPTION
**Pull request by danduggan**
l1 fix from #8188 rebased to allow merge in online cluster. the fix now gets the trigger type via TCDS.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by deguio** [comment]
would like to see this PR submitted to 74 and 75. unless I missed it, it hasn't been done.
thanks,
F.

**Comment by deguio** [comment]
@jingyucms

**Comment by deguio** [comment]
+1

**Pull request merged**
