### PR TITLE
`TriggerRatesMonitor`: monitor all HLT Paths, but not per PD

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR suggests an update of the plugin `TriggerRatesMonitor`, a DQM plugin used inside the HLT menu to produce histograms counting the number of events accepted by a given trigger (L1T or HLT), Primary Dataset (PD) and stream.

The current implementation creates a subdirectory named `HLT/` which in turn contains a subdirectory for every PD; in each PD subdirectory, there are 5 histograms for each Path assigned to said PD.

If a Path is assigned to _N_ PDs, each of its 5 histograms will be created and filled _N_ times, leading to duplicate information. Such a duplication is particularly visible in the case of trigger menus such as the PbPb one,
where there is a large number of PDs split in a round robin, with each PD having the same content in terms of trigger Paths. In addition, the current approach ignores trigger Paths which are not assigned to any PD (such Paths exist, they are normally used for monitoring purposes, to compute the result of a given trigger Path without writing out the events it accepts).

This PR removes the per-PD structure in the `HLT/` directory created by `TriggerRatesMonitor`, simply filling the latter directory with 5 histograms for every Path in the trigger menu (with 1 subdirectory per Path, each with 5 histograms), ignoring its relation to any PDs (information on the Primary Datasets is already provided in the `Datasets/` directory created by this same plugin).

On Oct-27 in run-387440, while using the 2024 PbPb menu in a commissioning run (no stable beams), a large delay in the macro-merging of the `DQMHistograms` pb files was observed, and the current suspicion is that the large size of these files in the PbPb menu might be part of the problem; this led to this attempt to reduce the number of histograms.

#### PR validation:

Tested in `CMSSW_14_1_4` with the script below. After including this PR, the file size of the output `DQMHistograms` file in `.root` format in the example goes from ~30 MB to ~2 MB, and the number of histograms goes from 46743 to 3948.
```bash
#!/bin/bash -ex

# run 387440, LSs 1-30
INPUTFILE=root://eoscms.cern.ch//eos/cms/store/group/tsg/STORM/RAW/Run2024J_HIEphemeralHLTPhysics_run387440/235844d9-333c-43a9-9c92-b1ce47ce19d1.root

HLTMENU=/cdaq/physics/Run2024HI/v1.0.0/HLT/V7

rm -rf run387440*

# create 1 file with 100 events from LS 15
convertToRaw -f 100 -l 100 -r 387440:15 -o . -- "${INPUTFILE}"

tmpfile=$(mktemp)
hltConfigFromDB --configName --adg "${HLTMENU}" > "${tmpfile}"
sed -i 's|process = cms.Process( "HLT" )|from Configuration.Eras.Era_Run3_cff import Run3\nprocess = cms.Process( "HLT", Run3 )|g' "${tmpfile}"
cat <<@EOF >> "${tmpfile}"

process.load('run387440_cff')

process.hltOnlineBeamSpotESProducer.timeThreshold = int(1e6)

process.options.wantSummary = True
process.options.numberOfThreads = 1
process.options.numberOfStreams = 0

# override the GlobalTag, connection string and pfnPrefix
from Configuration.AlCa.GlobalTag import GlobalTag as customiseGlobalTag
process.GlobalTag = customiseGlobalTag(
    process.GlobalTag,
    globaltag = "141X_dataRun3_HLT_v1",
    conditions = "L1Menu_CollisionsHeavyIons2024_v1_0_5_xml,L1TUtmTriggerMenuRcd,frontier://FrontierProd/CMS_CONDITIONS,,9999-12-31 23:59:59.000"
)

# run the Full L1T emulator, then repack the data into a new RAW collection, to be used by the HLT
from HLTrigger.Configuration.CustomConfigs import L1REPACK
process = L1REPACK(process, "uGT")

# remove all output streams
streamPaths = [pathName for pathName in process.finalpaths_()]
for foo in streamPaths:
    process.__delattr__(foo)

# # to run using the same HLT prescales as used online in LS 231
# process.PrescaleService.forceDefault = True
@EOF
edmConfigDump "${tmpfile}" > hlt.py
rm -rf "${tmpfile}"

cmsRun hlt.py &> hlt.log

fastHadd add -o output_streamDQMHistograms.pb run387440/run*_ls*_streamDQMHistograms_pid*.pb
fastHadd convert -o output_streamDQMHistograms.root output_streamDQMHistograms.pb

rm -rf run387440* output_streamDQMHistograms.pb
```

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

To be backported to `CMSSW_14_1_X` for data-taking purposes (used at HLT).

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent 
  * HLT will need a patch with this in 14.1.x

**Comment by missirol** [comment]
Feedback from @fwyzard paraphrased below

> the problem with having all these plots in the same directory is that this can slow down the rendering in the DQM GUI

Based on that, I changed the implementation in order to produce 1 subdirectory per Path under `HLT/[Path name]`. Each per-Path directory then contains 5 histograms.

**Comment by mmusich** [comment]
please test

**Comment by missirol** [comment]
Mh, tests seem stuck ?

**Comment by smuzaffar** [comment]
looks like the baseline generation for 27th OCT IB was stuck, I have restarted that but I guess it is better to restart the tests there to use latest IB

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
+hlt

**Comment by missirol** [comment]
> looks like the baseline generation for 27th OCT IB was stuck, I have restarted that but I guess it is better to restart the tests there to use latest IB

Thanks @smuzaffar !

**Comment by missirol** [comment]
@cms-sw/dqm-l2, kind ping (backport was already signed and merged).

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge
   - @cms-sw/dqm-l2 please check a posteriori.

**Comment by antoniovagnerini** [comment]
+1

**Pull request merged**
