### PR TITLE
update dqm  client config for online beam spot running pixel tracking

### PR DESCRIPTION
**Pull request by sushilchauhan**
update of DQM config for online beam spot for 2016 running. Now using pixel tracking (as pileup is high) and few minor updates.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
tested in the online already

**Comment by dmitrijus** [comment]
merged in 81x: https://github.com/cms-sw/cmssw/pull/14316

**Comment by sushilchauhan** [comment]
although not sure about the comment from dmitrijus but this PR was for 80X and 14316 for 81X (which seems already merged)

**Comment by dmitrijus** [comment]
the comment was just to add a cross-reference between pull requests.

**Comment by sushilchauhan** [comment]
ah ok. Thanks you!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
