### PR TITLE
Make sure StreamerInputSource throws an error (75x)

### PR DESCRIPTION
**Pull request by dmitrijus**
... and fix DQMStreamerReader to catch that error.

(foward port of https://github.com/cms-sw/cmssw/pull/12564)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
Is this change already tested/patched online?
Is the fix essential now during HI data taking?

**Comment by slava77** [comment]
merge

**Pull request merged**
