### PR TITLE
Geant4 sensitive detectors cleanup 1

### PR DESCRIPTION
**Pull request by civanch**
Geant4 sensitive detectors were developed at different time by different developers, it turn out that there are a lot of duplicated code, variable shadowing, many protected members in base and derived classes. There is a possibility to make code faster and be more clean but any such change requires editions in many files. This is a first clean-up, which includes:
  1) use of const pointers and references were possible
  2) removal of all protected members from the base class
  3) implement common intialisation in the base class
  4) substitute remaining auto_ptr by std::unique_ptr
No change of algorithms, so expected unchanged results.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
code-checks

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 7556 differences found in the comparisons

looks like negative FPIX hits are dead
I hope the last commits have fixed it.

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
code-checks

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , @davidlange6 , this is not the last PR for sensitive detectors, I want to optimise and clean-up them in several iterations. Hope that in each new PRs less number of classes will be touched, because this one if intended to clean-up common interfaces.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
