### PR TITLE
Phase-2 L1T: Consolidation of e/g object interface

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

This PR addresses several issues with the interface of `TkElectron` and `TkEm` objects and the HW objects used by the Phase2 GT emulator:

- add ID score to both the hardware and CMSSW electron objects;
- add interface to retrieve object in GT hw format;
- remove Ref. to `Egamma` standalone objects since they are not the actual ancestors due to architectural choice in L1T hardware. The ref is replaced by an `edm::Ptr` to the calorimeter primitive (different in barrel and endcap).
- further cleanup of the `TkElectron` interface and of data members;
- charge is now populated for all `TkElectrons`;
- change charge definition for GT electrons in accordance with new convention;
- use non-PV-based photon isolation in hardware objects; 
- eta and phi at vertex (from the track) are now used for the `TkElectron` coordinates.

*NOTE*: backward compatibility is maintained via IO rule in the reflex dictionary.

#### PR validation:

Successfully tested reading files produced with previous versions of the object data formats.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cerminar** [comment]
Not sure what happens here with the tests. The workflows mentioned above are not Phase-2 ones. Also, why is https://github.com/cms-sw/cmssw/pull/43275 added to the test setup? 
Thanks

**Comment by mmusich** [comment]
> Not sure what happens here with the tests.

was a transient failure with the IB...

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by aloeliger** [comment]
+l1

**Comment by cerminar** [comment]
Hello, this conversation looks very silent....any feedback?

**Comment by srimanob** [comment]
@cmsbuild please test

Sorry, I just have a chance to review. Let's re-trigger the test after 2 weeks.

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
