### PR TITLE
Do not catch polymorphic exception by value

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixes a gcc810 compiler warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
please test

to cross check failures in comparison, although they are likely unrelated to this technical fix

**Comment by fabiocos** [comment]
+1

technical adjustement

**Comment by fabiocos** [comment]
merge

**Pull request merged**
