### PR TITLE
Extended tracking cut per CMS region in SIM for electrons/positrons

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Extended existing features to have tracking cut per particle and per detector region: added possibility to apply low-energy parametrization of a detector response for e+- by this mechanism. By default, this feature is not applied, so should be no regression in any WF. Some details are discussed in SIM meeting: https://indico.cern.ch/event/829622/contributions/3475747/attachments/1868386/3073294/VI20190625.pdf

#### PR validation:
Private runs and TB2006.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
