### PR TITLE
Clean-up Geant4 Physics Lists

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:

This PR includes few modifications in view of coming new Geant4:
1) CMSSW EM physics configuration has minor inaccuracy, which is now fixed, this may bring change of histories and regression discrepancy in part of tests. This fix was pending for long and now a good time to implement.
2) FTFP_BERT_EMY physics list provide crashes in CMS geometry, which were recently understood and more safe parameters for Geant4 tracking are proposed
3) Custom physics configuration historically have parameters , which are not used, so they are removed

#### PR validation:
private

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
change in histories is expected, physics should not be affected

**Comment by fabiocos** [comment]
@civanch for documentation, do you have a reference for the fix in EM lists that change history? Any link to a validation?

**Comment by civanch** [comment]
@fabiocos , this fix make EM physics similar to one of Geant4 standard EM physics: https://github.com/Geant4/geant4/blob/geant4-10.5-release/source/physics_lists/constructors/electromagnetic/src/G4EmStandardPhysics.cc 
The difference is in proton/anti_proton ionisation and elastic scattering which should not reuse the same model class, because they are slightly different. This is a minor effect, modification is done to be coherent with Geant4.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
