### PR TITLE
Interface for high multiplicity triggers in CSC

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR add a basic interface for high multiplicity triggers (e.g. boosed tau->3 mu, long-lived particles to muon showers, muon-jets, etc.) in CSCs for Run-3 and beyond. At least 2 bits in the ALCT->(O)TMB data stream and at least 1 bit in the (O)TMB->EMTF data stream can be repurposed for such exotic objects. We will reassign the unused synchronization error (`syncErr`) data word in the LCT. No changes are expected. The bit values have yet to be finalized and implemented.

#### PR validation:

Tested with WF 20434.0. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by dildick** [comment]
In a future PR, I'll probably introduce masks and shifts in the CSCALCTDigi data format. That way I can reserve the two highest bits `BXN[4]` and `BXN[3]` to count stubs/hits.

**Comment by dildick** [comment]
Hi, can someone initiate the tests?

**Comment by dildick** [comment]
@fabiocos Can you initiate the tests please?

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder for @rekovic

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
