### PR TITLE
Update PbPb skims for 2023

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Update the HLT paths for the PbPb prompt skims to correspond to the 2023 menu.
Also open up the Z boson selection a bit. 

#### PR validation:

compiles. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will need a backport to 13_2_X

@youyingli

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @sunilUIET , could you please test it with workflow 140.56 as there is no 2023 PbPb collision data for testing and 140.56 is closer? If the test is approved, could @sunilUIET sign it, and could @mandrenguyen make another PR to 13_2_X?

**Comment by mandrenguyen** [comment]
please test workflow 140.56

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
