### PR TITLE
GE21 recHits in GEM onlineDQM, a backport to 12_4_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:

With this PR GE21 recHits are generated and drawn in the GEM onlineDQM. It makes effect only on the onlineDQM system, not on any other places, such as muon reconstruction.

#### PR validation:

Test are done with `cmsRun $CMSSW_RELEASE_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of #39860 to 12_4_X.

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39860

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
test at p5 successful

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

* Simple configuration change

**Comment by quark2** [comment]
Hi @emanueleusai, 

Sorry for my late request. Could you deploy this PR to P5?

**Comment by emanueleusai** [comment]
this should be online already. Are you seeing any issues?

**Pull request merged**
