### PR TITLE
Run3-sim150 Change some of the defaults of FullSim for Test Beam simultion

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change some of the defaults of FullSim for Test Beam simultion

#### PR validation:

Apply them for TB simulation applications

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
