### PR TITLE
[DQM] Fix for DQM merging exception due to duplicated labels

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR fixes the crash in DQM merging due to duplicated lables reported on:
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2328/1/1/1/1/1.html

### CODE REVIEW

**Comment by jfernan2** [comment]
plese test

**Comment by perrotta** [comment]
please test

**Comment by tvami** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
