### PR TITLE
Migrate deprecated EDAnalyzers in CondTools/DT to the One version.

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Migrations in https://github.com/cms-sw/cmssw/issues/36404 for CondTools/DT. Partially response of [this spreadsheet](https://docs.google.com/spreadsheets/d/18hTA-VwyNAQcclQM-vgXFJRqxPegDLJC4sZqAQAAuAk/edit#gid=0).

#### PR validation:

Code compiles. code-checks & code-format

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backports foreseen.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * technical changes

**Comment by tvami** [comment]
@yuanchao why did you do https://github.com/cms-sw/cmssw/pull/37124/commits/d6ff5e2eb80d320e625f0dabe0f1502f1cf92934 ?
Now the test-approved is gone

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+1
 * last commit didnt change anything

**Comment by francescobrivio** [comment]
@cmsbuild , please test with https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/11

 - not related to this PR but needed to fix the IB

**Comment by perrotta** [comment]
+1
- There is no reason to re-run the comparisons because all updates are in the \test area
- All workflows and affected unit tests run to completion

**Pull request merged**
