### PR TITLE
[PPS] Cloning of geometry definition objects prior to their usage/modification in validation tools

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

As raised in #32448 some configuration files are loaded and used without any cloning. Thus a risk exists that a configuration script using these without precaution can induce competing behaviours/steerings of the ESProducer/ESSource.
For now, as the PPS validation suite is orthogonal to the data reconstruction flow it is not affecting anything. Nevertheless this PR defines a function to automate the cloning of all critical objects prior to their use.

#### PR validation:

PPS-related unit tests pass successfully. No effect expected on standard reconstruction chain.

#### if this PR is a backport please specify the original PR and why you need to backport that PR: N/A

Before submitting your pull requests, make sure you followed this checklist:
- [x] verify that the PR is really intended for the chosen branch
- [x] verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- [x] verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@fabferro @jan-kaspar @silviodonato

### CODE REVIEW

**Comment by forthommel** [comment]
Can someone please issue the "please test"?

**Comment by civanch** [comment]
please test

**Comment by forthommel** [comment]
It seems that the only differences are to be found in the logging and TimerService parts.

**Comment by jfernan2** [comment]
+1

**Comment by forthommel** [comment]
@silviodonato, adding you to the cc list as you raised the issue documented in #32448 in the first place...!

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
