### PR TITLE
Run4-hgx284x Modify the conversion code to make titles for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the conversion code to make titles for HGCal

#### PR validation:

Created the new title files for V15

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
