### PR TITLE
 HLTriggerOffline/Higgs - Adding AHttH paths, updating PU range and correcting/removing empty histograms - Backport of #9109

### PR DESCRIPTION
**Pull request by jasperlauwers**
Adding AHttH paths, updating PU range and correcting or removing empty histograms.

cc: @HuguesBrun, @d-salerno

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@jasperlauwers 
please rebase this one so that can be merged
thanks,
F.

**Comment by d-salerno** [comment]
One of the files here is subject of another PR https://github.com/cms-sw/cmssw/pull/9619.
PR 9619 should be the new standard for hltHiggsValidator_cfi.py.
Cheers,
Daniel

**Comment by davidlange6** [comment]
@jasperlauwers - please change the title of this PR to be descriptive for the release notes. Thanks!

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
