### PR TITLE
Fix alca beam monitor ls histograms

### PR DESCRIPTION
**Pull request by rovere**
In the AlcaBeamMonitor package there are several histograms which plot quantities vs LS. When plotting these with any overlaid reference, the default normalisation kicks in, making the interpretation of the results impossible. Therefore all such histograms have been flagged as "efficiency plots" so that the DQMGUI knows that they should not be normalised.
Expect no difference.

### CODE REVIEW

**Comment by rovere** [comment]
To ease the review process, the only real changes (besides code deletion) are:
[Line 169](https://github.com/cms-sw/cmssw/pull/16263/files#diff-01428542bfdcaf9e5ab268afe81b16caR169)
[Line 175](https://github.com/cms-sw/cmssw/pull/16263/files#diff-01428542bfdcaf9e5ab268afe81b16caR175)
[Line 183](https://github.com/cms-sw/cmssw/pull/16263/files#diff-01428542bfdcaf9e5ab268afe81b16caR183)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
