### PR TITLE
Streamline calling of unscheduled EDProducers

### PR DESCRIPTION
**Pull request by Dr15Jones**
When a data product from an unscheduled EDProducer was requested, we used to have UnscheduledProductResolver call a virtual function of Principal to call a virtual function of UnscheduledHandler to trigger looking the Worker which then calls the module. Now we setup to have the UnscheduledProductResolver have direct access to the Worker and therefore invoke it directly without any lookup or extra virtual calls.
This refactoring is needed for work to allow asynchronous calling of unscheduled EDProducers.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
