### PR TITLE
Fixes for SiStripCalCosmicsNano

### PR DESCRIPTION
**Pull request by robervalwalsh**
#### PR description:

* Removed lumi section selection from step `RunCosmics2021` that is not necessary and yields a DAS_ERROR. when running the step
* Removed redundant `seqALCARECOSiStripCalCosmics` from `pathALCARECOSiStripCalCosmicsNano.` It prevents error when running the step `ALCA:SiStripCalCosmicsNano` on existing `SiStripCalCosmics` samples. 

#### PR validation:
For both commits
```
runTheMatrix.py -l 138.1,138.2 -i all
```
Running step `ALCA:SiStripCalCosmicsNano` on existing `SiStripCalCosmics` sample:
```
cmsDriver.py step3nano \
--conditions 123X_dataRun3_Prompt_v3 \
--datatier ALCARECO \
--eventcontent ALCARECO \
--scenario cosmics \
-s ALCA:SiStripCalCosmicsNano \
--era Run3 \
-n 100 \
--filein  /store/data/Commissioning2021/Cosmics/ALCARECO/SiStripCalCosmics-PromptReco-v1/000/346/514/00000/55e45b5c-3abf-41c7-8938-ef79d26ab8be.root \
--customise=CalibTracker/SiStripCommon/customiseAlCaNano.flatSiStripCalCosmicsNano \
--customise_commands="process.ALCARECOStreamSiStripCalCosmicsNano.fileName = cms.untracked.string('calibTreeNano_run346514.root')"
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 7.2, 7.21, 7.22, 7.23, 7.24, 7.3, 7.4, 134.813, 136.733, 138.1, 138.2

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by robervalwalsh** [comment]
> Hi @robervalwalsh
> Do I understand the PR description correctly that you will always run `ALCA:SiStripCalCosmicsNano` on top of `seqALCARECOSiStripCalCosmics`?

Hi @srimanob,
Yes

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
>  Yes

what about the possible future Tier-0 case? `SiStripCalCosmicsNano` explicitly consumes `SiStripCalCosmics` event products e.g.:

https://github.com/cms-sw/cmssw/blob/9624bb7563907e344872c9504a8bb5d36111c885/Calibration/TkAlCaRecoProducers/python/ALCARECOSiStripCalCosmicsNano_cff.py#L18

N.B.: I am not saying what is proposed here's not correct, just that `SiStripCalCosmicsNano` should never be run in central sequences unless `SiStripCalCosmics` is present as well after this change

**Comment by robervalwalsh** [comment]
> N.B.: I am not saying what is proposed here's not correct, just that `SiStripCalCosmicsNano` should never be run in central sequences unless `SiStripCalCosmics` is present as well after this change. Taggin @cms-sw/alca-l2 for their knowledge.

I agree that should be case. The problem I faced was to run `SiStripCalCosmicsNano` on existing `SiStripCalCosmics` samples, without running all the steps, as I described in the `cmsDriver` command in the PR description.

**Comment by srimanob** [comment]
Should this PR get in?
Ping @cms-sw/pdmv-l2

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1

**Pull request merged**
