### PR TITLE
Do not catch polymorphic exception by value [CondDB]

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixes a gcc810 compiler warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by fabiocos** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I see an issue reproted in the new section https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23719/28975/headers_chks.log that seems unrelated to this PR, but it caught in the test. 

We may clean it separartely

**Comment by smuzaffar** [comment]
@fabiocos , this header check failure looks like a glitch in CVMFS. The missing file error
```
fatal error: FWCore/Utilities/interface/Exception.h: No such file or directory
```
is false, I can not reproduce it.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
