### PR TITLE
HLT update to L1T menu v5 incl. GT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT update to L1T menu v5 incl. GT
This PR includes the GT changes from #14077

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 
Please check and sign.
Thanks!

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test
(after fixing merge conflicts due to auto-ported PRs from 80X entering 81X)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
