### PR TITLE
Take frozen HLT menu from /frozen ConfDB location (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Take frozen HLT menu from /frozen ConfDB location (92X)
Based on CMSSW_9_2_X_2017-08-03-1100

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19117

**Comment by Martin-Grunewald** [comment]
backport of #20034

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
