### PR TITLE
[HeaderCheck][ALCA][DB] Cleanup headers to avoid header inconsistency errors

### PR DESCRIPTION
**Pull request by smuzaffar**
Clean up headers which are not used. The header `SerializationManual.h` is referenced here https://cmssdt.cern.ch/lxr/source/CondFormats/Serialization/python/condformats_serialization_generate.py#0562 
```
         if os.path.exists( './src/SerializationManual.h' ) :
             source += '#include "%s/%s/src/SerializationManual.h"\n' % (self.split_path[1], self.split_path[2])
```
but `condformats_serialization_generate.py` is looking in `src` directory while deleted header ` CondFormats/SiPixelObjects/interface/SerializationManual.h` is in interface directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi could you please have a look? The deleted SerializationManual.h is not the one used by the script mentioned by @smuzaffar

**Comment by fabiocos** [comment]
@ggovi ping

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
