### PR TITLE
Migrate L1 step to Tasks

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates the L1 (simulation) step to use Tasks in the configuration. This change should increase the available concurrency in the jobs running the L1.

#### PR validation:

Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

Fixed the addon test failure (stupid mistake...)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic could you please check?

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of StandardSequences is coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
