### PR TITLE
Add a sequence for DQMMessageLogger and use it in autoDQM

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR adds in ```DQMOffline``` a sequence for the ```DQMMessgaeLogger``` module and uses it in ```autoDQM```. This solves the failures observed for ZeroBias samples in CMSSW_11_0_X_2019-10-30-2300 , based on the diagnosis and suggestiopn by @Dr15Jones https://github.com/cms-sw/cmssw/pull/28156/files#r341171685 .

#### PR validation:

Test wf 134.71 passes

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 134.812,134.912,136.732,136.745,136.756,136.767,136.778,136.789,136.801,136.813,136.88

**Comment by fabiocos** [comment]
@jfernan2 apart for the definition of the sequence there are other issues with these workflows

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar @jfernan2 this fix unveils another issue in the HARVESTING step that needs to be addressed separately. I will integrate for the time being this PR as anyway it fixes part of the crashes.
Please comment for possible further updates

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
from the message in the HARVESTING step even when not crashing I see this fix is incorrect there:

```
Step: HARVESTING Spec: ['@rerecoZeroBiasFakeHLT', '@miniAODDQM']
DQMMessageLoggerSeq is not a possible harvesting type. Available are ['FH_DR_GROUP', 'SusyPostProcessorSequence', 'SUSY_HLT_PhotonMET_pt36', 
```

so this needs to be further adjusted

**Comment by fabiocos** [comment]
this problem seems simply solved by replacing ```DQMMessageLoggerSeq``` with ``` DQMMessageLoggerClientSeq``` in the harvesting part of autoDQM, although @jfernan2 should confirm this is the intended behaviour. The exception anyway is not due to this, but as far as I can see related to missing sequences after the revision

**Comment by fabiocos** [comment]
@jfernan2 ok, I think the source of the problem is the revision of the SiStrip ```rerecoZeroBias``` and ```rerecoZeroBiasFakeHLT```

**Comment by jfernan2** [comment]
+1

**Pull request merged**
