### PR TITLE
Clang Check modernize-deprecated-headers

### PR DESCRIPTION
**Pull request by ianna**
* Geometry part from @davidlange6 https://github.com/cms-sw/cmssw/pull/19556

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - ping

**Comment by kpedro88** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
