### PR TITLE
Phase2-hgx353X Add a new scenario 2026D109 utilizing the V18 version of HGCAL after removing some of the gaps (backport of #43903)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario 2026D109 utilizing the V18 version of HGCAL after removing some of the gaps (backport of #43903)

#### PR validation:

Tested using the runTheMatrix test workflow 29234.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of the PR #43903 for the master

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
@cmsbuild please test with 29234.0

**Comment by bsunanda** [comment]
+geometry

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43903

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
