### PR TITLE
Run3-hgx218 Conevrt one DDHGCalNoTaperEndcap algorithm to DD4Hep format

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert the algorithm DDHGCalNoTaperEndcap from DDD to DD4Hep format

#### PR validation:

Tested with scripts kept in Geometry/HGCalCommonData/test/python area

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
