### PR TITLE
81x: add pixel barycenter computation tool

### PR DESCRIPTION
**Pull request by mmusich**
Making available in release tool needed for Pixel barycenter computation:
https://twiki.cern.ch/twiki/bin/view/CMS/TkAlignmentPixelPosition

attn: @tlampen, @mschrode, 
@ghellwig please comment if there is any other more suitable place to put this.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mschrode** [comment]
@mmusich @ghellwig @tlampen How about moving it to Alignment/TrackerAlignment/macros?

**Comment by ghellwig** [comment]
@mmusich do I understand it correctly that you rely on MillePede only with this tool? If yes, I think it is already at the right place. If not, @mschrode's  suggestion looks reasonable.

**Comment by mmusich** [comment]
@ghellwig yes, basically was an add-on from Gero Flucke to quickly derive the barycenter position, designed to be included in `MillePedeAlignmentAlgorithm` making use of the existing suite of macros availble in `Alignment/MillePedeAlignmentAlgorithm/macros/GFUtils/`.
There is no particular reason in general to use MillePede to do this job, but since the parsing of the output was already at hand...  
I've just updated the configuration to make it work in current releases.

**Comment by ghellwig** [comment]
@mmusich ok, this means, in its current implementation it works only with MillePede, but in principal it could be generalized to use, let's say, the resulting sqlite file instead of the millepede.res file, right?
I would then say that the current location is fine.

**Comment by ghellwig** [comment]
Before approving, I would like to hear the final opinion of @mschrode and @tlampen

**Comment by tlampen** [comment]
For me it seems that the directory MillePedeAlignmentAlgorithm/macros/ contains only files related to MPS.  Therefore TrackerAlignment/macros would sound a more consistent location. Does the depencency of MillePede cause difficulties in that location?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig @mschrode @tlampen I moved the configuration to `Alignment/TrackerAlignment/test`. The macro stays in `MillePedeAlignmentAlgorithm` where I think it should belong in any case. The  `Alignment/TrackerAlignment/macros` sub-package in any case doesn't exist.

**Comment by mschrode** [comment]
@mmusich @ghellwig @tlampen OK I was not aware the script depends on tools in MillePedeAlignmentAlgorithm/macros. Then I fully agree, it should stay there.

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by davidlange6** [comment]
+1

**Pull request merged**
