### PR TITLE
[10_6_X] Adding SiPixel on track charge and shape probs to MiniAOD content

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See request to ReRECO 2017/2018 SM and MET data in [1]. This assumed refitting tracks to get the required low-level pixel reco information. As an alternative (actually it's an improvement, so better then alternative) it was recommended to save the required information in the MiniAOD. This PR does that,  i.e. adds  SiPixel on track charge and shape probs to MiniAOD content. Since in 2017/2018 the Pixel layer 1 was very noisy, and alternative version that excludes L1 was added as well.

Adding it to RECO/AOD as a new object `siPixelTrackProbQXY`:
```
edmDumpEventContent ReRECO_RAW2DIGI_L1Reco_RECO_EI.root | grep siPixelTrackProbQXY  
edm::Association<vector<reco::SiPixelTrackProbQXY> >    "siPixelTrackProbQXY"       ""                "RECO"    
vector<reco::SiPixelTrackProbQXY>     "siPixelTrackProbQXY"       ""                "RECO"    
```

While adding it to MiniAOD as a member of the isolatedTracks collection.

Please note that most of the changes in the PR are due to code-checks/code-formats.

Further details will be presented in the Tracking POG meeting on Monday [2]

[1] https://its.cern.ch/jira/browse/PDMVRERECO-48
[2] https://indico.cern.ch/event/1098365/#5-proposal-to-use-low-level-pi

#### PR validation:
Running 
```
cmsDriver.py ReRECO --conditions 106X_dataRun2_v24 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2018,Configuration/DataProcessing/Utils.addMonitoring --datatier MINIAOD --era Run2_2018,pf_badHcalMitigation --eventcontent MINIAOD --nThreads 8 --no_exec --number 100 --python_filename 4HLT2MiniAOD.py --scenario pp --step RAW2DIGI,L1Reco,RECO,EI,PAT --runUnscheduled --data  --filein root://cms-xrd-global.cern.ch//store/data/Run2018C/SingleMuon/RAW/v1/000/319/337/00000/004ED286-5582-E811-8895-FA163E126126.root
```
before the PR and after the PR the sizes change as follows:
-rw-r--r-- 1 tvami cms 8177333 Nov 24 16:30 ReRECO_RAW2DIGI_L1Reco_RECO_EI_PAT.root
--> 
-rw-r--r-- 1 tvami cms 8185759 Nov 24 16:26 ReRECO_RAW2DIGI_L1Reco_RECO_EI_PAT.root
i.e an 1.00103041 increase in size is expected.

Here is the timing report for before the PR
```
 Time Summary: 
 - Min event:   3.23837
 - Max event:   31.758
 - Avg event:   11.6797
 - Total loop:  238.961
 - Total init:  111.42
 - Total job:   353.645
 - EventSetup Lock:   644.041
 - EventSetup Get:   110.653
 Event Throughput: 0.418479 ev/s
 CPU Summary: 
 - Total loop:  1052.11
 - Total init:  58.428
 - Total extra: 0
 - Total job:   1113.87
 ```

and after the PR
```
 Time Summary: 
 - Min event:   4.21454
 - Max event:   33.0982
 - Avg event:   12.851
 - Total loop:  272.262
 - Total init:  117.273
 - Total job:   392.587
 - EventSetup Lock:   788.184
 - EventSetup Get:   128.934
 Event Throughput: 0.367293 ev/s
 CPU Summary: 
 - Total loop:  1220.08
 - Total init:  64.1806
 - Total extra: 0
 - Total job:   1287.24
 ```

Content was validated on MC Signal samples, and on data as well, please see more plots in [2]

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/36247

cc @mmusich

### CODE REVIEW

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
code-checks

**Comment by slava77** [comment]
can the changes be minimized?
It's rather hard to keep track of the updates.

Which PR corresponds to this one in the master?

**Comment by tvami** [comment]
> can the changes be minimized? It's rather hard to keep track of the updates.

I think not, I need to do code-checks for submitting the PR, and when doing code-checks, it reorganizes half of the already existing code. Do you want me to submit a PR that just does the code checks? Merge it quickly and then rebase this PR so it will really only show my changes? 

> 
> Which PR corresponds to this one in the master?

None yet, I thought you'd have comments on the implementation so I wanted to wait for feedback before doing the master PR: "Needs a forward port to Master. But the main consumer is 10_6_X so I prefer to have the review done here, and then apply the changes in master. There is stuff I'd do differently in Master anyway (like the esConsume migration)"

**Comment by slava77** [comment]
> "Needs a forward port to Master. But the main consumer is 10_6_X so I prefer to have the review done here

that's against the normal policy

**Comment by slava77** [comment]
> I need to do code-checks for submitting the PR

this is not required for the old releases before the code-checks became standard

**Comment by slava77** [comment]
image

smth broken?

**Comment by tvami** [comment]
Hi @slava77 
I made a verbatim PR to master:
https://github.com/cms-sw/cmssw/pull/36247
I made that a draft PR since many things cant be just copied one to one. 
I'll have a further look tomorrow, but anyway that nicely shows what are the differences.

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36247

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
assign x-pog
 * for MiniAOD

**Comment by slava77** [comment]
@tvami 
please remove code-checks
it is much harder to review

**Comment by tvami** [comment]
> @tvami please remove code-checks it is much harder to review

Is there a way to do that with a command? Or you just mean that I should start from a scratch CMSSW? Does this also mean you have no more comments in the master PR?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hi @slava77 I've started from scratch and included the responses from the review in master. It is much more readable indeed.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
The idea from Slava to use the DeDxHitInfo's clusters and an approximation for the angles seems to be giving compatible results with my proposed solution, thus I'm closing this backport PR

**Pull request closed without merging**
