### PR TITLE
enabling UL regression for 2018 (and likely Run3)

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:
This PR enables the 106X UL regressions for 2018, given the imminent update of these conditions in the GT. 

The 2017UL is already in the global tags so matrix tests ran locally without errors.  Of course they are not fully correct yet as they are not the 2018UL corrections.

Also from looking around at the modifiers it appears Run3 activates the egamma 2018 modifier so Run3 also gets this. Which is good, they should be using this.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by christopheralanwest** [comment]
I don't understand the comparison tests. There are differences in 2018 and 2026 workflows. Conditions have not yet been updated and both Run-3 and Phase-2 inherit from the previous Era. So I expected 2018, Run-3 and Run-4 workflows to switch to using the new 2017 regression, inducing reco changes in all three Eras. If this is unexpected, please resolve the issue prior to adding the updated GT candidates.

**Comment by Sam-Harper** [comment]
Indeed, it is puzzling that Run3 didnt change. Something to track down.

**Comment by Sam-Harper** [comment]
On closer inspection, Run3 does change. Just Run3 wasnt run in these tests which is odd. Anyways not my problem :D

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-07-31-2300+5fe69e/32888/

**Comment by Sam-Harper** [comment]
The full suite of  runTheMatrix.py -l limited -i all --ibeos do pass though (which includes Run3, I also manually checked the config before and after this change and it is disabled/enabled as expected).

**Comment by christopheralanwest** [comment]
Does the same command work in a recent IB? I suspect that when 13 TeV workflows were moved to 14 TeV in #27433, a change should have been made to the list of RelVals selected by the "limited" option. The old RelVal 11624.0 does not exist anymore.

Attn: @zhenhu @kpedro88

**Comment by kpedro88** [comment]
@christopheralanwest good catch, I missed that in #27433. I'll submit a quick fix.

**Comment by slava77** [comment]
please test workflow 11634.0,12434.0,12834.0

**Comment by slava77** [comment]
assign alca

> The 2017UL is already in the global tags so matrix tests ran locally without errors. Of course they are not fully correct yet as they are not the 2018UL corrections.

I guess we have to wait for the GT to be updated as well before merging this PR.

**Comment by christopheralanwest** [comment]
@Sam-Harper Please go ahead and create GT candidates for all 11_0_X relevant queues and update autoCond. Once either this PR or PR#27683 is merged, I will convert the candidates in the other PR to versioned GTs. Do not update 106X_dataRun3_Prompt_Queue as condition updates to the prompt queues need to go through a separate validation procedure.

**Comment by slava77** [comment]
It looks like 2023 and 2024 GTs are incomplete
e.g. in 12434.0

```
   [7] Calling method for module GEDGsfElectronFinalizer/'gedGsfElectrons'
Exception Message:
No data of type "GBRForestD" with label "electron_eb_ecalOnly_1To300_0p2To2_mean" in record "GBRDWrapperRcd"
```

**Comment by christopheralanwest** [comment]
The conditions for the 2023 and 2024 scenarios needed to be finalized at the same time as PR #26892 and so no attempt was made to include features that were under active development. By the time PR #26892 was merged, the new regression was disabled for Run-3 scenarios. Since the tags needed to support the 2017 UL regression were not relevant for these scenarios, they were not added to the GT.

The tags needed to resolve the failures of the 2023 and 2024 are exactly those which will be introduced in the GT candidates that I requested Sam to make.

**Comment by Sam-Harper** [comment]
okay all the tags should be made and are now in autoCond

**Comment by slava77** [comment]
please test workflow 11634.0,12434.0,12834.0

**Comment by christopheralanwest** [comment]
Why haven't the data GTs been updated? You will want to update the 110X_dataRun2_2017_2018, 110X_dataRun2_relval, 110X_dataRun2_PromptLike, 110X_dataRun2_PromptLike_HEfail and 110X_dataRun2_PromptLike_HI queues.

Should the multi-IOV tags be assigned a "prompt" synchronization so that they can be used directly in prompt queues or does EGamma plan to provide separate prompt tags? The 106X prompt-like queues are configured to accept tags with "offline" synchronization but tags with offline synchronization are not allowed in prompt GTs. I don't know why the 106X prompt-like queues were configured as offline queues but I would rather use them to maintain collision prompt reco in the absence of collision data.

I will convert the candidate GTs to versioned GTs once reco signs off on this PR.

**Comment by Sam-Harper** [comment]
> Why haven't the data GTs been updated? You will want to update the 110X_dataRun2_2017_2018, 110X_dataRun2_relval, 110X_dataRun2_PromptLike, 110X_dataRun2_PromptLike_HEfail and 110X_dataRun2_PromptLike_HI queues.

Opps, just forgot to.

>Should the multi-IOV tags be assigned a "prompt" synchronization so that they can be used directly in prompt queues or does EGamma plan to provide separate prompt tags?

I have no idea what this is.  I dont really see the need to provide seperate tags but we can if theres a good use case? Is there a naming convention to follow?

**Comment by Sam-Harper** [comment]
Also I guess I want to update all the 106X data queues as well? As they are the point of all of this?

**Comment by Sam-Harper** [comment]
Hi @christopheralanwest ,

So further clarifications with the global tag queues:
110X_dataRun2_2017_2018, 110X_dataRun2_relval, 110X_dataRun2_PromptLike, 110X_dataRun2_PromptLike_HEfail and 110X_dataRun2_PromptLike_HI

Does not match with the AlCa slides 
image

We can briefly chat to clarify the situation after the AlCa meeting.

**Comment by christopheralanwest** [comment]
There are two sets of data conditions, one intended for prompt reconstruction and one intended for offline reconstruction.

Tags that are used in prompt queues have special requirements to ensure reproducibility of prompt reconstruction. Tags that are assigned a "prompt" synchronization can only be updated for IOVs that have not yet been reconstructed at the Tier-0. In contrast, there is no such restriction for appends to tags with "offline" synchronization as they are intended for offline re-recos and such a restriction wouldn't make sense.

Normally we don't change the promptlike queues for updated conditions. It is unnecessary because we don't actually plan to re-run prompt reco on a dataset in a newer release. The offline queues are intended for that purpose. But your situation is a special case because the UL preparation introduced new record:label combinations, without which CMSSW would crash. In this case we have to make a change. 

You can create the 106X backport PR. The PR comparison tests will contain additional, spurious changes at this point because #27605 has not yet been merged, but the conditions updated in that PR have already been approved in the queue. I am anticipating that #27605 will be merged tomorrow and that's why I've approved the conditions already. I will create a backport of #27683 today with GT candidates. Once either that PR or this one is merged, I will create versioned GTs with both sets of conditions included.

**Comment by Sam-Harper** [comment]
updated with data

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The differences in the comparison tests for pre-2017 data are apparently a consequence of the modified supercluster tags:

```
lxplus727>conddb diff 110X_dataRun2_2017_2018_Candidate_2019_08_05_15_03_17 110X_dataRun2_2017_2018_Candidate_2019_08_03_03_51_45 | grep pf | awk '{print "conddb diff "$3" "$4}' | bash
[2019-08-05 23:12:54,563] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
[2019-08-05 23:12:55,306] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Range               pro::pfscecal_EBCorrection_offline_v2_UL2017To2018V1 Payload  pro::pfscecal_EBCorrection_offline_v2_2017UL_offline_v1 Payload  
------------------  ------------------------------------------------------------  ---------------------------------------------------------------  
[1, 288377)         df39f2ab34bc36a72e070edc4aa3db6280588fb7                      dcf618d66591194f8d0d2bdb18406d269210af1f                         
[288377, 314472)    =                                                             =                                                                
[314472, Infinity)  627b86862a2857158ebe968902e1295aef82f292                      dcf618d66591194f8d0d2bdb18406d269210af1f                         

[2019-08-05 23:12:56,028] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Range               pro::pfscecal_EBUncertainty_offline_v2_UL2017To2018V1 Payload  pro::pfscecal_EBUncertainty_offline_v2_2017UL_offline_v1 Payload  
------------------  -------------------------------------------------------------  ----------------------------------------------------------------  
[1, 288377)         be67051e600fa019019a52bb2d2d443adb4edeee                       11112dcf6533a6b84ee5754749b7ceb2e6b443bb                          
[288377, 314472)    =                                                              =                                                                 
[314472, Infinity)  79393f0a61a1eaa7f1382fe171e98520c43b82e3                       11112dcf6533a6b84ee5754749b7ceb2e6b443bb                          

[2019-08-05 23:12:56,734] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Range               pro::pfscecal_EECorrection_offline_v2_UL2017To2018V1 Payload  pro::pfscecal_EECorrection_offline_v2_2017UL_offline_v1 Payload  
------------------  ------------------------------------------------------------  ---------------------------------------------------------------  
[1, 288377)         e924cb8de379a13b505ea7430bac0e95af9585d1                      7d3032b75b0028bbf25c60dda4c07cc30daa6537                         
[288377, 314472)    =                                                             =                                                                
[314472, Infinity)  749e28bb394e9eb940c996d91a6858f957cb289d                      7d3032b75b0028bbf25c60dda4c07cc30daa6537                         

[2019-08-05 23:12:57,468] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Range               pro::pfscecal_EEUncertainty_offline_v2_UL2017To2018V1 Payload  pro::pfscecal_EEUncertainty_offline_v2_2017UL_offline_v1 Payload  
------------------  -------------------------------------------------------------  ----------------------------------------------------------------  
[1, 288377)         aaa38d3c04e65f06ab20d80d00a9186669bbcc65                       d9f919258536f8eca8e2b572d48f1211a53ed4aa                          
[288377, 314472)    =                                                              =                                                                 
[314472, Infinity)  d927d97cf440e7dfac76fc95866ed8419790e0a4                       d9f919258536f8eca8e2b572d48f1211a53ed4aa                          

```

The pre-2017 payloads in the new GT correspond to the following tags:

| Hash                          |            Tag |
| ---------------------| -----------| 
|df39f2ab34bc36a72e070edc4aa3db6280588fb7 | pfscecal_EBCorrection_offline_v2 |
|be67051e600fa019019a52bb2d2d443adb4edeee | pfscecal_EBUncertainty_offline_v2 |
|e924cb8de379a13b505ea7430bac0e95af9585d1 | pfscecal_EECorrection_offline_v2 |
|aaa38d3c04e65f06ab20d80d00a9186669bbcc65 | pfscecal_EEUncertainty_offline_v2 |

These correspond to the [payloads that were used prior to the 2017 UL](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v13/106X_dataRun2_v11). I thought that the era affected _all_ of the regressions but it looking at https://github.com/cms-sw/cmssw/blob/dc71ac5b51aa23d8d35db6ff17c0a3e243335e86/RecoEgamma/EgammaTools/python/regressionModifier_cfi.py#L3, it seems that only the electron/photon regressions are affected. So are the changes to pre-2017 IOVs a bug fix to revert to the behavior prior to #26892?

**Comment by Sam-Harper** [comment]
Hi Chris, 

Yes  the "pfscecal_EBCorrection_offline_v2" family of corrections are those which existed before the ultra legacy and were used for 2016. 2017, 2018. 

The era only effects ele/pho regressions as they have new client code. The SC has existing client code. So yes this was a mistake on my part in the rush to get 2017UL done, we accidently messed up pre-2017 for a release cycle and this is bringing it back to compliance.

**Comment by slava77** [comment]
I'm a bit lost in the discussion of a proper finalization of this PR.
Is the last commit and the tests with it can be considered final for now, or is there another update coming imminently?

**Comment by christopheralanwest** [comment]
please test

**Comment by Sam-Harper** [comment]
we added in the PF cluster corrections as well into the GTs in the very recent commit. So now it is final and hopefully no more changes are coming.

**Comment by christopheralanwest** [comment]
The tags included in the GT candidates from the last commit pass technical tests:

- The data tags beginning with "ecalPFClusterCor" modify only 2018 and later IOVs
- The prompt tags have identical content to the corresponding offline tags
- The payloads in the 2018 data IOVs have the same hash as the corresponding 2018 MC tags
- The tag differences are the same for each of the categories:
    - offline
    - promptlike
    - cosmics
    - collision realistic (2021 is a special case as the updated EGamma regression payloads were never added to those GTs)

I will convert these GT candidates to versioned GTs once reco signs off.

**Comment by slava77** [comment]
> Reco comparison results: 10096 differences found in the comparisons

This includes changes in 
- Run-1 data (but not MC): why only data, or why a change at all? Some details are needed in the PR description if this is eventually confirmed to be intentional.
    - A typical situation for Run-1 is "we just need it to run and not be completely broken". Does this apply here?
- 2016 data (but not MC). Same question as above.
    - OTOH, since this is one of the UL targets, I'd expect that only a consistent update of conditions should happen.
- 2018 HI data (but not MC). Same question.
    - here the MC jenkins tests may be insufficient to see a difference in egamma due to higher thresholds; however this PR does not change ```phase1_2018_realistic_hi``` so the lack of differences in 2018 HI MC seems to be not accidental
    - except for the higher thresholds applied in pp_on_AA, I'd still expect that the 2018 regressions/conditions from pp should mostly apply for 2018 and the MC GT should have an update.

**Comment by Sam-Harper** [comment]
For Run-1 and 2016, I believe this is us resetting it back to the "correct" values. There was only a single tag IOV for the data before, leading Run-1 and 2016 to be sacrificed for the sake of our sanity. 

For 2018 HI, I think it was because I was told to queue there but yes you are correct we should probably queue the MC if we queue the data.

However in retrospect, we shouldnt have queued this to the HI queue, its not needed and in appropriate for those queues.  Basically it should match the PF cluster rec-hit thresholds and those still use the old ones. 

In about 30mins, I'll revert that change.

**Comment by Sam-Harper** [comment]
Okay I had though it was perhaps the reason was, we needed it but then perhaps HION were not activing the e/gamma modifier. However they are as far as I can tell so I'm deeply confused why its not crashed.

**Comment by Sam-Harper** [comment]
Ah okay, it looks like its not crashing because its not being run. Okay I'll update the HION MC tomorrow, its too late for me to start now.

**Comment by christopheralanwest** [comment]
> However in retrospect, we shouldnt have queued this to the HI queue, its not needed and in appropriate for those queues. Basically it should match the PF cluster rec-hit thresholds and those still use the old ones.
> 
> In about 30mins, I'll revert that change.

Should any of the changes to the HI data and MC implemented in #27205 to support #26892 be reverted as well? In particular, the changes to the HI prompt-like GT:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v9/106X_dataRun2_PromptLike_HI_v7

include changes that were not performed for the 106X_upgrade2018_realistic_HI GT:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v4/106X_upgrade2018_realistic_HI_v2

Also, #27205 implemented changes to Phase-2 GTs:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_v5/106X_upgrade2023_realistic_v3

Were those changes appropriate? Certainly I wouldn't expect corrections for the current EE to be relevant for 2026. It seems that either they should not have been updated in #27205 or they should be updated to the 2018UL tags here.

**Comment by Sam-Harper** [comment]
Okay yet again I'm getting terribly confused here. I think I need a holiday.  Again sorry for the noise.

Okay we have a mess which is a bit of my own doing and a bit of my predecessors fault. 

The crux of the issue is that we have to update GTs that use the 2017/2018 era modifiers. Those values will be incorrect for anything which does not have the PF rec-hit thresholds of the UL.  That is just life and we can deal with that later.

What is problematic are relevant data/MC queues going out of sync with each other, as Slava spotted the HI queues. 

I think I'll just update the MC queues for 106X_upgrade2018_realistic_HI_v4 if thats all right so its 2018.

**Comment by christopheralanwest** [comment]
Your proposal to update the GT in the `106X_upgrade2018_realistic_Queue` sounds consistent from an AlCa perspective. I'm not qualified to comment if it's sensible from a reco point of view.

**Comment by slava77** [comment]
please test workflow 12434.0,12834.0

**Comment by slava77** [comment]
> This branch has conflicts that must be resolved
Conflicting files
Configuration/AlCa/python/autoCond.py

**Comment by christopheralanwest** [comment]
The conflict arises because PR #27733 was merged. Please re-make the auto:run1_data, auto:run2_data and auto:run2_data_relval candidates so that your updated GTs also include the fix to the HBHE negative energy filter. The HBHE negative energy filter condition is approved in the queues so simply remaking the GTs should be sufficient.

**Comment by Sam-Harper** [comment]
okay remake all the candidate GTs tomorrow for 106X_dataRun2_X and 110X_dataRun2_X. I didnt touch run1 data so I will continue not to touch that.

**Comment by fabiocos** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27644	475cadd
- code changes are in line with the PR description and the follow up review
    - I'm mostly assuming that the GT updates are consistent
- jenkins tests pass and comparisons with the baseline show differences in ecal/egamma-related quanties in line with the changes in the GTs
    - Run-1 workflows show no change
    - 2016 data workfow using run2_data_relval changed due to PF and ecal corrections changed, not related to the egamma regression setting for 2018
    - 2018 and later workflows for data and MC (including HI) changed. Changes are fairly small in most cases.
        - The most significant changes are in the 2018 data HI workflow where it looks like many more clusters are made (also, a part not related to the egamma regression enabling for 2018). This propagates downstream with somewhat reducing impact at PF stage. 

in wf 140.56:
- about 50% more barrel superclusters in ECAL (10% more in endcap)
all_OldVSNew_RunHI2018wf140p56c_log10max1e-5,recoSuperClusters_particleFlowSuperClusterECAL_particleFlowSuperClusterECALBarrel_reRECO_obj_correctedEnergy

- 0 -> 2 ged electrons
- 10 more ged photons
all_OldVSNew_RunHI2018wf140p56c_recoPhotons_gedPhotons__reRECO_obj_et

**Comment by christopheralanwest** [comment]
Since the conditions used in this PR seem to be final, I created a commit (https://github.com/cms-sw/cmssw/commit/53e47f2f9d60692cd7be1ced25a1dacd9e191038) that converts the GT candidates in this PR to versioned GTs. Please cherry-pick this commit and add it to your PR. There are also three changes relative the conditions in your PR:

- The 2018 UL EGamma regression conditions have been added to `auto:run1_data` and `auto:run2_data`
- `HBHENegativeEFilter_v2.0_offline` (which corrects 2016 as well as 2017) is used instead of `HBHENegativeEFilter_v3.0_offline` (which only corrects 2018) in `auto:run2_data_relval`. 
- For `110X_upgrade2018_realistic_HI`, the label contains "sigma" but the tag name contains "mean": https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HI_Candidate_2019_08_08_14_56_36/110X_upgrade2018_realistic_HI_Queue The tag and label are now consistent.

**Comment by Sam-Harper** [comment]
done, thanks Chris!

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

Changes seen only in expected workflows:
- 2018 data and MC, including HI scenarios
- Run 3 MC
- pre-2017 data, as described in the response to https://github.com/cms-sw/cmssw/pull/27644#issuecomment-518411332

In particular, no changes are seen to pre-2018 MC or 2017 data.

The number of changes in comparison tests before and after the latest commit are the same, cross-checking that no unexpected changes were introduced in the last commit. For most workflows, the number of reco changes is the same. New differences are seen in:

- 4.53: Cosmics2011A
- 140.53: RunHI2011
- 1000.0: RunMiniBias2011A

These correspond to the addition of changes to the `auto:run1_data` (and the identical GT in `auto:run2_data`), which was mistakenly left unchanged relative to the version in master in the second-to-last commit.

There are changes to the number of reco differences in two workflows:

- 136.85: RunEGamma2018A
- 136.731: RunSinglePh2016B

The changes to the number of differences in 136.85 from the last commit is again a consequence of the modified `auto:run2_data` GT in the last commit. For workflow 136.731, the small number of changes is a consequence of using the `HBHENegativeEFilter_v2.0_offline` tag rather than `HBHENegativeEFilter_v3.0_offline`. Version 2.0 fixes the negative energy filter also for 2016 IOVs whereas 3.0 fixes the filter only for 2017 IOVs.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27644	f1e5398
- code changes are in line with the PR description and the follow up review. Changes since the last reco signoff https://github.com/cms-sw/cmssw/pull/27644#issuecomment-520619367 are only in the auto global tags https://github.com/cms-sw/cmssw/pull/27644/files/475caddc4631e417bb43875aff35b1357a488dbe..f1e5398eb0e16bdb55d9d22d85846f850203e8cf
- jenkins tests pass and comparisons with the baseline show more differences compared to the previous tests. Most notably, differences now appear also in pre-2017 data. This appears to be OK based on previous discussion and https://github.com/cms-sw/cmssw/pull/27644#issuecomment-521344873

**Comment by fabiocos** [comment]
+1

**Pull request merged**
