### PR TITLE
MkFit TrackCandidate error rescale + relaxed selection for overlap hits

### PR DESCRIPTION
**Pull request by mmasciov**
### PR description:

This PR introduces two updates for mkFit tracking iterations:
(1) rescale covariance of TrackCandidate's before CMSSW final fit (where the rescaling option is configurable);
(2) relax selection of overlap hits.

It requires cms-data/RecoTracker-MkFit#9.

### PR validation:

Rescaling the covariance of TrackCandidate's allows to better match CKF performance in terms of residuals, with a consequent decrease in duplicate tracks (from the duplicate merging/cleaning across mkFit and CKF iterations). E.g.:
http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/rescaleError100/MTV_TTbarPU50_rescaleError100_defaultIters_mkFitOnly/plots_highPurity/effandfakePtEtaPhi.pdf

Similarly to CKF tracks, a few % bias in track pT is introduced, due to a known feature related the description of the detector material in endcaps. E.g.:
http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/rescaleError100/MTV_TTbarPU50_rescaleError100_defaultIters_vsCKF/plots_highPurity/residualPt.pdf

Relaxing the selection of overlap hits allows to increase the track hit multiplicity, with a reduction of fake tracks:
http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/rescaleError100/MTV_TTbarPU50_rescaleError100_extractedGeoms_overlapHitCuts_mkFitOnly/

For more details, please refer to presentations at TRK POG:
(1) https://indico.cern.ch/event/1133724/#4-mkfit-status-report
(2) https://indico.cern.ch/event/1142469/#5-mkfit-status-report

FYI @mmusich @vmariani

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-data/RecoTracker-MkFit#9

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
What sort of changes do you expect downstream from tracking due to this change? As I understand, this is expected to reduce fake tracks, so would the following increase if PFCandidates be expected?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-15-1100+e44227/49637/validateJR/all_OldVSNew_RunDoubleEG2017Cwf136p793/all_OldVSNew_RunDoubleEG2017Cwf136p793c_recoPFCandidates_particleFlow__reRECO_obj_eta.png

all_OldVSNew_RunDoubleEG2017Cwf136p793c_recoPFCandidates_particleFlow__reRECO_obj_eta

**Comment by mmusich** [comment]
type tracking

**Comment by jpata** [comment]
+reconstruction
- improved tracking performance around eta 2.5
- requires https://github.com/cms-data/RecoTracker-MkFit/pull/9

**Comment by perrotta** [comment]
+1
- Changes observed in downstream quantities, e.g. https://github.com/cms-sw/cmssw/pull/37580#issuecomment-1103581891. are consistent with the explanation provided in https://github.com/cms-sw/cmssw/pull/37580#issuecomment-1104127888, and therefore expected (welcome, I would say...)

**Pull request merged**
