### PR TITLE
[NanoAOD] Fix typo of imported ParticleNet tagger list for AK4 Puppi jets

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:
This PR fixes a typo bug for the imported ParticleNet tagger list in `nanoAOD_addDeepInfoAK4` function in `jetsAK4_Puppi_cff.py`. Confirmed by @scooperstein that this is a typo. Replace `CHS` with `Puppi`. 

#### PR validation:
passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

#### Backport:
To be backported to `13_1_X` and `13_0_X`.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
Does this affect the PNet output when running the evaluation on top of MINI or also when producing MINI collections? I.e. do we have a problem for prompt MINI/NANO or does this affect only workflows that re-evaluate PNet on top of MINI?

**Comment by simonepigazzini** [comment]
Thanks @scooperstein, this is what I expected and it is good to hear.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
type bug-fix

**Comment by simonepigazzini** [comment]
+1

**Pull request merged**
