### PR TITLE
 Introduced new era for 2015 opendata nanoaod processing 

### PR DESCRIPTION
**Pull request by snehavireshwardixit**
#### PR description:
[Introduced new era for 2015 opendata nanoaod processing]

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
We have unwanted changes in the electron table
see here 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2022-08-11-1100+6afc20/52091/validateJR.html

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by srimanob** [comment]
@snehavireshwardixit @mariadalfonso 
I think I miss the discussion somewhere sometimes (e.g. PPD General yesterday). 
Why this PR does not appear in master first? Thanks.

**Comment by vlimant** [comment]
isn't the rational that this change is only needed un 10.6 to be able to have a nano version for the 2015 opendata samples ?

**Comment by davidlange6** [comment]
Still best to follow the usual process as to be ready for the next time a nano version would be desired in some possible future..

**Comment by vlimant** [comment]
looking twice at this, indeed, it could/should also be in master.
@snehavireshwardixit are you able to make the same PR against master using a different branch ?

**Comment by perrotta** [comment]
Indeed: it MUST go in master first. Backports will be taken into account only after the master version is merged and tested working

**Comment by nsmith-** [comment]
There is no way to apply this as a patch to master because the entirety of the NanoAOD config structure has been redesigned. We would have to start from scratch to implement the 2015 customizations.

**Comment by vlimant** [comment]
please close

you may reopen a PR from the work done in that branch if needed

**Pull request closed without merging**
