### PR TITLE
[14.0.X] Update 2024 geometry and GEM alignment conditions in 2024 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
backport of https://github.com/cms-sw/cmssw/pull/44497

_Note that the GT versions here are different than the ones in master PR because descoping was done for https://github.com/cms-sw/cmssw/pull/44598#issuecomment-2047343312 which increased the version numbers of the GTs for this backport. But the net effect of the master and backport PR is the same, with just the geometry update._

#### PR description:
The PR updates the 2024 geometry and compatible GEM alignment conditions tags in the relevant MC GTs:
- `140X_mcRun3_2024_design_v9`
- `140X_mcRun3_2024_realistic_v10`
- `140X_mcRun3_2024cosmics_realistic_deco_v10`
- `140X_mcRun3_2024cosmics_design_deco_v8`

More details with the full list of tag updates and links to relevant presentations can be found in the CMS Talk request in [1]. 

[1] https://cms-talk.web.cern.ch/t/gt-mc-data-update-of-2024-gem-and-rpc-geomtery-conditions-for-data-and-mc/36739

**GT Differences with the last ones are here**:

- **Phase1 2024 design**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_design_v8/140X_mcRun3_2024_design_v9

- **Phase1 2024 realistic**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v9/140X_mcRun3_2024_realistic_v10

- **Phase1 2024 cosmics realistic**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_realistic_deco_v9/140X_mcRun3_2024cosmics_realistic_deco_v10

- **Phase1 2024 cosmics design**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_design_deco_v7/140X_mcRun3_2024cosmics_design_deco_v8

#### PR validation:
See master PR https://github.com/cms-sw/cmssw/pull/44497
See also the Full Track validation in https://its.cern.ch/jira/browse/CMSALCA-260 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/44497

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
test parameters:
- workflows = 13050.0,13049.0,13046.0,13040.0,12933.0,12841.0,12802.0,12824.0,12834.1,13052.0
- relvals_opt = --what upgrade,standard

**Comment by saumyaphor4252** [comment]
please test

**Comment by saumyaphor4252** [comment]
The reason for holding this PR in 140X is some degradation and changes observed in muon reconstruction from the GT update in the ongoing Full Track Validation in https://its.cern.ch/jira/browse/CMSALCA-260, which are not fully understood and expected. See for eg:

- https://tinyurl.com/25pr9vng (More in https://tinyurl.com/2as75dre)
- https://tinyurl.com/2am5m337

image
image

Also FYI @bsunanda @cms-sw/muon-dpg-l2 @cms-sw/muon-pog-l2 (maybe also @cms-sw/upgrade-l2 )

We are going to do one last check with another run, but otherwise we will be considering to revert the changes until this is understood. 

Also @cms-sw/muon-dpg-l2 @cms-sw/muon-pog-l2 it would be great if you could provide some feedback on how critical these changes would be by taking a look at the validation plots in https://its.cern.ch/jira/browse/CMSALCA-260.

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

Following on https://github.com/cms-sw/cmssw/pull/44512#issuecomment-2047814589: more details can be found in https://its.cern.ch/jira/browse/CMSALCA-260 but to summarize:

- The degradation is highly reduced with the validation using a comparatively recent run 370776 and is understood from the ideal alignment scenario. The alignment will soon be updated with 2024 13.6Tev data to fix this (See [this comment](https://its.cern.ch/jira/browse/CMSALCA-260?focusedId=6347881&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6347881))
- The change in the STA muon/Global muon chi2/ndof at negative eta is understood from the fact that the alignment corrections are larger in that region ( See [this comment](https://its.cern.ch/jira/browse/CMSALCA-260?focusedId=6348702&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6348702))

**Comment by perrotta** [comment]
please test
- Errors are related to the failing das queries (exception of category 'FileInPathError'): let try with the new IB now available

**Comment by mmusich** [comment]
>  Errors are related to the failing das queries (exception of category 'FileInPathError'): let try with the new IB now available

not related to das queries, but rather to the fact that the last test dragged in https://github.com/cms-sw/cmssw/pull/44660 without the corresponding `cms-data` update.

**Comment by perrotta** [comment]
backport of #44594

**Please notice** that the following GTs are identical:
- `140X_mcRun3_2024_design_v9` and `140X_mcRun3_2024_design_v7`
- `140X_mcRun3_2024_realistic_v10` and `140X_mcRun3_2024_realistic_v8`
- `140X_mcRun3_2024cosmics_realistic_deco_v10` and `140X_mcRun3_2024cosmics_realistic_deco_v8`
- `140X_mcRun3_2024cosmics_design_deco_v8` and `140X_mcRun3_2024cosmics_design_deco_v6`

Therefore, this PR is backporting exactly what is currently in the master of cmssw, which was merged with #44594

**Comment by perrotta** [comment]
> > Errors are related to the failing das queries (exception of category 'FileInPathError'): let try with the new IB now available
> 
> not related to das queries, but rather to the fact that the last test dragged in #44660 without the corresponding `cms-data` update.

Thank you @mmusich for the clarification.
In any case, tests must be rerun (and with the new IB which already contains #44660 and he corresponding `cms-data` update they are expected to succeed)

**Comment by perrotta** [comment]
+alca
- Differences wrt the baseline are identical to those already observed in [master](https://github.com/cms-sw/cmssw/pull/44497#issuecomment-2016548734)
- They are now fully understood and validated, see https://github.com/cms-sw/cmssw/pull/44512#issuecomment-2070941119
- GEM DPG will update the alignment as soon as enough stat will be collected from this year data

**Comment by antoniovilela** [comment]
> +alca
> 
> * Differences wrt the baseline are identical to those already observed in [master](https://github.com/cms-sw/cmssw/pull/44497#issuecomment-2016548734)
> * They are now fully understood and validated, see [[14.0.X] Update 2024 geometry and GEM alignment conditions in 2024 MC GTs #44512 (comment)](https://github.com/cms-sw/cmssw/pull/44512#issuecomment-2070941119)
> * GEM DPG will update the alignment as soon as enough stat will be collected from this year data

Hi Andrea, sorry if this was discussed yesterday and I missed. Is this PR meant for 14_0_6?
Thanks.

**Comment by perrotta** [comment]
> > +alca
> > 
> > * Differences wrt the baseline are identical to those already observed in [master](https://github.com/cms-sw/cmssw/pull/44497#issuecomment-2016548734)
> > * They are now fully understood and validated, see [[14.0.X] Update 2024 geometry and GEM alignment conditions in 2024 MC GTs #44512 (comment)](https://github.com/cms-sw/cmssw/pull/44512#issuecomment-2070941119)
> > * GEM DPG will update the alignment as soon as enough stat will be collected from this year data
> 
> Hi Andrea, sorry if this was discussed yesterday and I missed. Is this PR meant for 14_0_6? Thanks.

Hi Antonio.
Yesterday I was traveling and I was not able to connect to the ORP.
In any case, this PR is not for data taking, as it only updates some MC GTs. Therefore it is not urgently needed in 14_0_6. It doesn't hurt also: therefore if you still have to build it, feel free to decide whether to include it or not.
Thank you

**Comment by antoniovilela** [comment]
> > > +alca
> > > 
> > > * Differences wrt the baseline are identical to those already observed in [master](https://github.com/cms-sw/cmssw/pull/44497#issuecomment-2016548734)
> > > * They are now fully understood and validated, see [[14.0.X] Update 2024 geometry and GEM alignment conditions in 2024 MC GTs #44512 (comment)](https://github.com/cms-sw/cmssw/pull/44512#issuecomment-2070941119)
> > > * GEM DPG will update the alignment as soon as enough stat will be collected from this year data
> > 
> > 
> > Hi Andrea, sorry if this was discussed yesterday and I missed. Is this PR meant for 14_0_6? Thanks.
> 
> Hi Antonio. Yesterday I was traveling and I was not able to connect to the ORP. In any case, this PR is not for data taking, as it only updates some MC GTs. Therefore it is not urgently needed in 14_0_6. It doesn't hurt also: therefore if you still have to build it, feel free to decide whether to include it or not. Thank you

Thanks.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
