### PR TITLE
Fix use of TimeType enum after PR 28186

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Addressing problems with conddb in unit tests after #28157, #28161 and #28186. This PR adapts ```conddb``` to the change by @davidlange6 in #28186.

#### PR validation:

The code correctly compile in python (both 2 and 3).

### CODE REVIEW

**Comment by smuzaffar** [comment]
@fabiocos , can you please also update the following in this PR. This should fix all of the unit tests

```
--- a/CondCore/Utilities/python/conddblib.py
+++ b/CondCore/Utilities/python/conddblib.py
@@ -221,9 +221,9 @@ def getSchema(tp):
 class Tag:
     __tablename__       = 'TAG'
     columns             = { 'name': (sqlalchemy.String(name_length),_Col.pk), 
-                            'time_type': (sqlalchemy.Enum(TimeType),_Col.notNull),
+                            'time_type': (sqlalchemy.Enum(*tuple(TimeType.__members__.keys())),_Col.notNull),
                             'object_type': (sqlalchemy.String(name_length),_Col.notNull),
-                            'synchronization': (sqlalchemy.Enum(Synchronization),_Col.notNull),
+                            'synchronization': (sqlalchemy.Enum(*tuple(Synchronization.__members__.keys())),_Col.notNull),
                             'description': (sqlalchemy.String(description_length),_Col.notNull),
                             'last_validated_time':(sqlalchemy.BIGINT,_Col.notNull),
                             'end_of_validity':(sqlalchemy.BIGINT,_Col.notNull),

```

**Comment by fabiocos** [comment]
@smuzaffar thanks, let me update the PR accordingly

**Comment by fabiocos** [comment]
please test with #28199

**Comment by fabiocos** [comment]
@smuzaffar @ggovi the PR looks to solve the problem with the unit tests, I would integrate it to see what is the outcome of the next IB. 

@ggovi please have anyway a look

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@smuzaffar @davidlange6 @mrodozov I am puzzled, the test here did not show any failure, but the IB has still 10 O2O workflows failing

**Comment by smuzaffar** [comment]
tests were run based on Ib where we did not have https://github.com/cms-sw/cmsdist/pull/5273 . looks like https://github.com/cms-sw/cmsdist/pull/5273 broke frontier client. I am looking in to it

**Comment by smuzaffar** [comment]
by the way tests runs if I use old frontier client. I will provide a fix soon

**Comment by fabiocos** [comment]
@smuzaffar yes, the test was running before the previous-to-last IB was ready, but also that . So In case I suggest to revert the last frontier change in next IB, unless a fix is obvious.
The test of the O2O tests in the cmsdist PR was just partial I see. In case you may use #28199 to force the test of the failing tests as well

**Comment by smuzaffar** [comment]
cms-sw/cmsdist#5273 shoudl fix the error [a]. I have cancelled the 11h IB and will restart once Pr tests are done for cms-sw/cmsdist#5273 (at least the unit test part)

[a]
---> test SiStripDCS_O2O_test succeeded
---> test SiStripDAQ_O2O_test succeeded
---> test EcalTPGPedestals_O2O_test succeeded
---> test EcalTPGLutIdMap_O2O_test succeeded
---> test EcalTPGFineGrainEBIdMap_O2O_test succeeded
---> test EcalLaser_O2O_test succeeded
---> test EcalTPGPhysicsConst_O2O_test succeeded
---> test EcalTPGBadStripStatus_O2O_test succeeded
---> test EcalTPGWeightIdMap_O2O_test succeeded
---> test EcalDAQ_O2O_test succeeded
---> test EcalDCS_O2O_test succeeded
---> test EcalTPGFineGrainTowerEE_O2O_test succeeded
---> test EcalADCToGeV_update_test succeeded
---> test EcalTPGFineGrainStripEE_O2O_test succeeded
---> test EcalTPGFineGrainEBGroup_O2O_test succeeded
---> test EcalIntercalibConstants_O2O_test succeeded
---> test EcalTPGSpike_O2O_test succeeded
---> test EcalTPGCrystalStatus_O2O_test succeeded
---> test EcalTPGTowerStatus_O2O_test succeeded
---> test EcalTPGWeightGroup_O2O_test succeeded
---> test EcalTPGLinearizationConst_O2O_test succeeded
---> test EcalTPGLutGroup_O2O_test succeeded
---> test EcalTPGSlidingWindow_O2O_test succeeded

**Pull request merged**
