### PR TITLE
backport of #8642 to 74X

### PR DESCRIPTION
**Pull request by wouf**

### CODE REVIEW

**Comment by bendavid** [comment]
This would actually be needed for 71x instead no?

**Comment by wouf** [comment]
we are doing generator validation under 7_4_X at this moment

**Comment by bendavid** [comment]
Why?  (And which release is actually planned to be used for upcoming HI GEN-SIM?

**Comment by wouf** [comment]
yes, please have a look https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TValidationSamples

**Comment by wouf** [comment]
sorry, I mean yes, we need it in 71X, could You please change the branch

**Comment by wouf** [comment]
Sorry for this I will create new one

**Pull request closed without merging**
