### PR TITLE
Updating to HLT paths to be monitored by TOP PAG in 2016

### PR DESCRIPTION
**Pull request by soureek**
Removing Lepton + btags/jets triggers from the list of triggers as the TOP PAG does not intend to monitor  them further in 2016. The reason being these triggers are not being used in TOP analyses. Also adding token for "hltTriggerSummaryAOD" collection present in both data and MC. Replaced "cout" commands with edm::LogWarning.

### CODE REVIEW

**Comment by Soureek89** [comment]
For your information, changes to the package has been tested OK by running the matrix and whiteRabbit tests.

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
Please fix the space issues, just like you did for 81x https://github.com/cms-sw/cmssw/pull/14410

**Comment by Soureek89** [comment]
Removed tabspace as mentioned in comment and updated trigger list for single electron triggers in the "topSingleElectronHLTOfflineDQM" sequence in DQMOffline/Trigger/python/topSingleLeptonHLTEventDQM_cfi.py.

I noticed the mismatch in the list of triggers in "triggerExtras" under "setup" and "preselection" steps which should not be there and updated to the current paths to be monitored.

**Comment by Soureek89** [comment]
Can you please test the changes? The last commit was updated almost 13 days ago.

**Comment by perrotta** [comment]
please test

**Comment by Soureek89** [comment]
Closing this PR as another new PR [1] has been opened in order to accommodate some additional trigger path to be monitored and modification of the topHLTriggerOfflineDQM sequence.

[1] https://github.com/cms-sw/cmssw/pull/14886

**Pull request closed without merging**
