### PR TITLE
HCALDQM: Fix crash in new 2018 relvals

### PR DESCRIPTION
**Pull request by DryRun**
Fixes a crash in the new 2018 relvals (https://github.com/cms-sw/cmssw/pull/23196#issuecomment-389586444).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 this PR is fixing a crash keeping #23196 on hold. Could you please review and fix it in case?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
