### PR TITLE
DQM for J/psi phi paths

### PR DESCRIPTION
**Pull request by lecriste**

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@lecriste 
please quantify the increase in #bins 
then, are you sure you took one of the most recent IB ?
I see many differences in the source, and I'm not sure this change was intended

**Comment by lecriste** [comment]
@mtosi
if the m(tk1,tk2) histograms will be added the number of bins will increase of 80.
Most of the differences in the source comes from some automatic formatting and from the introduction of a single function for enum=11 numerator and denominator in place of the previous code duplication. I used the yesterday IB.

**Comment by mtosi** [comment]
only 80 bins ?
I'm surprised !
so, you are telling me that you are adding 40 bins per path ?
I think I saw that the plot as function of phi has 32 bins .....

please, quantify the increase of bins by this PR
in addition, if you are adding an extra plot, are you sure it is enable
only for the relevant plots ?
thanks
  mia

**Comment by lecriste** [comment]
Of course 80 bins is the increase given only by the possible additional histogram that will be enabled for the relevant paths only.
This PR brings 70 bins per track, so 210 among numerator, denominator and efficiency, which means 420 per path (two tracks), so 840 bins in total.

In this PR I have also disabled for each path the histograms which are not filled, don't know whether this reduces the overall number of bins.

**Comment by mtosi** [comment]
can you please quantify the #bins ?
thanks

**Comment by lecriste** [comment]
As said [before](https://github.com/cms-sw/cmssw/pull/20745#issuecomment-334410668): this PR adds ~840 bins.

In this PR I have also disabled for each BPH path the histograms which are not filled, don't know whether this reduces the overall number of bins.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

(old tests)

**Comment by davidlange6** [comment]
+1
looks like this PR removes 50k bins..

**Pull request merged**
