### PR TITLE
Remove last usage of edm::LazyGetter and edm::RefGetter

### PR DESCRIPTION
**Pull request by Dr15Jones**
The classes edm::LazyGetter and edm::RefGetter were no longer being
used in CMSSW. This removes the last remnants of code that referred
to those two classes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
