### PR TITLE
PPS: theta*_x and theta*_y histograms in DQM

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR adds histograms of proton scattering angles (theta*_x and theta*_y) among the standard DQM plots. These histograms are essential to judge the reconstruction quality.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@jan-kaspar I am afraid the GUI is having issues with the "*" in the ME names, have you tried to upload it to a test GUI?
I have and it complains, could it be possible to remove the "*" from the ME name?
Thanks

**Comment by jan-kaspar** [comment]
> @jan-kaspar I am afraid the GUI is having issues with the "_" in the ME names, have you tried to upload it to a test GUI? I have and it complains, could it be possible to remove the "_" from the ME name?

Thanks for your check! In bec62d1 I remove both the star and the underscore.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
