### PR TITLE
HLT menu development for `13_2_X` (2/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #42698

#### PR description:

Development of HLT menus for `CMSSW_13_2_X`.

This version of the PRef HLT menu corresponds to the "V1.0" menu for the 2023 pp "reference run" (the corresponding frozen menu is not added to the release, as not needed by any central wf).

In addition, adbe2f0b742 updates the L1T "pp-ref" menu in TSG GTs to [`L1Menu_CollisionsPPRef2023_v1_0_0`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsPPRef2023_v1_0_0_xml).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2883](https://its.cern.ch/jira/browse/CMSHLT-2883): [HIN] Main requests for 2023 ppRef menu
 - [CMSHLT-2892](https://its.cern.ch/jira/browse/CMSHLT-2892): [AlCa] AlCaDB requests for 2023 ppRef menu
 - [CMSHLT-2897](https://its.cern.ch/jira/browse/CMSHLT-2897): [HIN] D-meson triggers for 2023 ppRef menu
 - [CMSHLT-2901](https://its.cern.ch/jira/browse/CMSHLT-2901): [TRK] Rename `hltSiStripClusters*` to `hltMeasurementTrackerEvent*`
 - [CMSHLT-2903](https://its.cern.ch/jira/browse/CMSHLT-2903): [BRIL] Set PS=1 for `AlCaLumiPixelsCountsExpress` PD in "PRef" column

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42698

Development of HLT menus for 2023/2024.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - Outputs of the PR tests are in line with the update of the HLT menus ("frozen" and "fake" menus). Differences are only technical (e.g. menu names), no physics changes.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping to merge this backport PR.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind re-ping. Hopefully, this can enter the next IB.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , one more ping to merge this PR, please.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
