### PR TITLE
bsunanda:Run2-hcx44 Add protection to HcalTopology

### PR DESCRIPTION
**Pull request by bsunanda**
LUT code calls function for invalid DetId and then tests if it is valid DetId. Protection nee

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @ianna Please take look at this urgently in view of 7_6 release
________________________________

**Comment by civanch** [comment]
+1

**Comment by davidlt** [comment]
Add reference to the issue: #11979

**Comment by davidlt** [comment]
ping^1

**Pull request merged**
