### PR TITLE
Run3-gex90 Make unique material names as default for all Run3 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make unique material names as default for all Run3 scenarios

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Could you change an additional line in `Configuration/Geometry/python/dict2021Geometry.py`? As in my PR #34974, change:
''Geometry/TrackerCommonData/data/PhaseI/v2/pixbarmaterial.xml', `
to
`'Geometry/TrackerCommonData/data/PhaseI/v3/pixbarmaterial.xml', `
for "T3".
Then I can remove this change from #34974.
After that, we merge #34974 first, followed by this PR.

**Comment by bsunanda** [comment]
OK - I shall do that
________________________________

**Comment by bsunanda** [comment]
@cvuosalo Can I also take the v3/pixbarmaterial.xml. Without that the PR won't be complete

**Comment by bsunanda** [comment]
@cvuosalo So you need to remove the changes in dict2021geometry.py and remove the addition to pixbarmaterial.xml

**Comment by bsunanda** [comment]
@cvuosalo Please confirm

**Comment by bsunanda** [comment]
@cvuosalo Or I can take your advice that let your PR get merged and then I can get this PR tested

**Comment by civanch** [comment]
@bsunanda , @cvuosalo, I think that #34974 should be merged first, at least, this would be an ideal sequence.

**Comment by bsunanda** [comment]
@cvuosalo I shall take your and Vladimir's comments. I shall only change dict2021 and create the scenaruos. I am not triggering the tests till your PR gets merged.
________________________________

**Comment by cvuosalo** [comment]
I have removed `dict2021Geometry.py` from #34974. Wouldn't it be harmless to include `v3/pixbarmaterial.xml` in this PR as well as #34974? Whichever PR gets merged second would just find that the identical file is already present in the master.

**Comment by bsunanda** [comment]
@cvuosalo I think I shall wait till your PR gets merged first

**Comment by civanch** [comment]
urgent

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @perrotta @qliphy I tested against the latest IB and I think it is OK

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@perrotta, @qliphy tests are fine, would it possible to merge it without upgrade sign - @srimanob is aware about this PR but he may have problem to access these days.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
