### PR TITLE
Add test for cross-site catalog access

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

While investigating https://ggus.eu/index.php?mode=ticket_info&ticket_id=160073 I realized we didn't have a test for the cross-site catalog access (that is used in the wild at least for specifying the xrootd fallback). This PR adds such a test.

#### PR validation:

Unit test succeeds.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Could you take a look?

**Comment by Dr15Jones** [comment]
My only comment is I'd prefer if the various 'site' files were in a separate sub-directory of test just to keep the test directory less cluttered.

**Comment by makortel** [comment]
@cmsbuild, please test

Organized the files better.

**Comment by makortel** [comment]
+1

RelVals-INPUT tests timed out, nothing in this PR can impact those (and I'm leaning towards retesting not being worth it).

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
