### PR TITLE
ME0MuonSelector cleanup pass

### PR DESCRIPTION
**Pull request by davidlange6**
The modules IB pointed out duplicated structs between MuonSelector and ME0MuonSelector. To avoid this, I added a namespace to the me0 set of functions for lack of better idea. 

There were in addition #includes of plugin/*.cc files which have been cleaned up and rearranged to avoid duplicate plugin problems. There may be other issues not fixed by this PR.. [Perhaps #including cc files  can be prevented by code checks...:)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by guitargeek** [comment]
Hi @davidlange6, I have to mention something else related to this `ME0MuonSelector`.

It is used in `CommonTools/RecoAlgos/plugins/ME0MuonTrackCollProducer.cc`, which is used by `CommonTools/RecoAlgos/python/me0Associator.py`. This python file is in turn not used in production, there is only a test file in `RecoMuon/MuonIdentification/test/testME0MuonAnalyzer_Example.py`. Note this is again in the MuonIdentification package,  just like the `ME0MuonSelector` that you change in this PR.

Therefore, we have a rather awkward dependency relation between be packages: `CommonTools` uses `RecoMuon` to define a plugin+configuration that is not common at all, and then the tests of this are again in  `RecoMuon`.

Would you also think it's better to have everything in `RecoMuon` to avoid the dependency of `CommonTools` on reco? I think, CommonTools should ideally be higher up in the dependency hierarchy.

In practice, this suggestion implies to move:
`CommonTools/RecoAlgos/plugins/ME0MuonTrackCollProducer.cc` -> `RecoMuon/MuonIdentification/plugins/ME0MuonTrackCollProducer.cc`
`CommonTools/RecoAlgos/python/me0Associator.py` -> `RecoMuon/MuonIdentification/python/me0Associator.py`

**Comment by perrotta** [comment]
By the way, something else that could be cleaned straightforwardly in this ME0MuonTrackCollProducer.cc is the following (just listing what jumps to the eyes as being obviously uselessly included):

- Remove the duplicated
```
#include "DataFormats/TrackReco/interface/Track.h"
#include "DataFormats/TrackReco/interface/TrackFwd.h"
```
- Remove the unneeded dependencies on
```
#include "DataFormats/MuonDetId/interface/CSCDetId.h"
#include "DataFormats/MuonDetId/interface/DTChamberId.h"
...
#include "DataFormats/CSCRecHit/interface/CSCSegmentCollection.h"
#include "DataFormats/DTRecHit/interface/DTRecSegment4DCollection.h"
```
- Remove the unneeded dependency on:
```
#include "DataFormats/HepMCCandidate/interface/GenParticle.h"
```
- Remove the unneeded dependencies on
```
#include "DataFormats/VertexReco/interface/Vertex.h"
#include "DataFormats/VertexReco/interface/VertexFwd.h"
```
as well as the commented out line
```
  //std::vector<double> findSimVtx(edm::Event& iEvent);
```

**Comment by perrotta** [comment]
@Fedespring @cericeci : profiting of this PR, could you plese check if all those "ME0" muons stuffs are still needed at all in the standard workflows (or any other "local" one)? If not, this could be a good opportunity to start cleaning all them out

**Comment by davidlange6** [comment]
> Would you also think it's better to have everything in RecoMuon to avoid the dependency of CommonTools on reco? I think, CommonTools should ideally be higher up in the dependency hierarchy.

Clearly that would be an improvement, yes. [but I don't really follow the design logic (or why we would need a ME0 specific muon selector)] Probably best addressed by those responsible for muon selectors?

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
someone knows how to find the failure? I don't manage.

**Comment by makortel** [comment]
Hmm, I see at the end of
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6a2320/8878/addOnTests/hlt_data_GRun/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run3_hlt_GRun_--relval_9000,50_--datatier_RAW_--eventcontent_RAW_-.log
only
```
Fatal system signal has occurred during exit
```
We've seen that symptom before on cc8 that lead to https://github.com/cms-sw/cmssw/issues/30432.

**Comment by davidlange6** [comment]
Odd, I had to reload to see the word “fatal” in that log..  ok, I will restart the tests..

On Aug 24, 2020, at 5:52 PM, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:



Hmm, I see at the end of
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6a2320/8878/addOnTests/hlt_data_GRun/cmsDriver.py_RelVal_-s_L1REPACK:Full_--data_--scenario=pp_-n_10_--conditions_auto:run3_hlt_GRun_--relval_9000,50_--datatier_RAW_--eventcontent_RAW_-.log
only

Fatal system signal has occurred during exit


We've seen that symptom before on cc8 that lead to #30432<https://github.com/cms-sw/cmssw/issues/30432>.

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
I don't think this simple PR should be delayed any further,
@trocino and Arnab Purohit (please provide the github name of Arnab, to be listed among the reco contacts), who are replacing @Fedespring and @cericeci, please virify independently from this PR if there is any ME0 related code that can be removed from the release, so that there will be no need to maintain it further in the future

**Comment by perrotta** [comment]
+1
- Technical 
- Jenkins tests pass
- Further cleanings and rearrangements of the code were suggested in the thread: they can be implemented in a separate PR, or even not needed in case some useless code can be removed from the release (up to the muon POG reco contacts to verify it)

**Comment by qliphy** [comment]
+1

**Pull request merged**
